### ISSUE TITLE
Content actions menu disappears on save

### ISSUE THREAD

**Issue by nzdev** [umbraco/Umbraco-CMS#10010]
A brief description of the issue goes here.

Actions menu disappears on save of content.

I am seeing this issue on Umbraco version: 8.12.1

Reproduction
------------

### Bug summary

Actions menu disappears on save of content.

### Specifics

In the content section, saving a document makes the actions menu disappear.

### Steps to reproduce

Create a new document in the content section. Click save. 

### Expected result

The action menu does not dissapear.

### Actual result
The actions menu on the top right disappears.

**Comment by nul800sebastiaan** [comment]
Hmm, no idea what's going on for you @nzdev - seems to work for me? Did I miss something in my repro steps?

https://user-images.githubusercontent.com/304656/111753992-c4e95f80-8897-11eb-9f4a-b83a8e99ba9d.mp4

**Comment by nul800sebastiaan** [comment]
I'll close this for now but let us know if you can still repro.
