### ISSUE TITLE
Cannot insert an image inside a grid

### ISSUE THREAD

**Issue by elit0451** [umbraco/Umbraco-CMS#10029]
## Seen in 
Umbraco version 8.12.1 (haven't checked any previous versions)

## Description
When trying to add an image as a grid content, a js error is preventing the image selection. The error states that `TypeError: Cannot read property 'focalPoint' of null` at DependencyHandler.axd

## Steps to reproduce
- Create a folder in the Media section and add some images;
- Create Doc type with a Grid layout;
  - Stick to the default settings, just remove the "2 column layout" under **Grid Layouts**;
- Choose Image as a type of content;
- Click to insert an image and try to select some image;

## Expected:
A user is able to select an image and insert it in the grid, when images are allowed (either the option "Allow all editors" is enabled or the "Image' box is checked).
<img src="https://user-images.githubusercontent.com/21998037/111972668-fcf1dc00-8afd-11eb-8ad6-fbd9e7d39269.png" height=500>

## Actual:
JS error is preventing image selection, so no image is selected.

**Comment by MMasey** [comment]
I've also been able to replicate this issue. Here's an image of the error in the console, along with where it appears to be occurring in the code. I've noticed some odd behavior with the media picker in other parts of the backoffice too which I think may also be related. 

![image](https://user-images.githubusercontent.com/6573613/111974693-98cc1980-8af7-11eb-96f2-3dce8c45424d.png)

**Comment by abjerner** [comment]
Should be the same as https://github.com/umbraco/Umbraco-CMS/issues/9982 and thus fixed in https://github.com/umbraco/Umbraco-CMS/pull/9987 😄

(which means fixed in 8.12.2)

**Comment by elit0451** [comment]
Great! Then will go ahead and close down this issue. Thanks for the info!
