### ISSUE TITLE
`umbTabsNav` directive documentation doesn't work as expected

### ISSUE THREAD

**Issue by snerpton** [umbraco/Umbraco-CMS#10021]
Provided documentation for `umbTabsNav` directive results in an error when you use the example markup.

## Umbraco version

- Umbraco version: 8.8.2
- Browser: Chrome 89.0.4389.90 (Official Build) (x86_64) on MacOS 11.2.3

Reproduction
------------

Create a back-office section and insert `umb-tabs-nav` directive using the example markup and controller code found at https://our.umbraco.com/apidocs/v8/ui/#/api/umbraco.directives.directive:umbTabsNav

### Bug summary

There is a related thread on Our Umbraco reporting the same issue:

https://our.umbraco.com/forum/using-umbraco-and-getting-started/104005-umb-tabs-nav-shows-as-collapsed-until-resize-container

### Expected result

Code samples for `umbTabsNav` should work as detailed in the documentation i.e. ability click on 'Tab 1' and 'Tab 2' to view each tab's content.

### Actual result

Loading the page results in the following javascript error:

```
Error: [$compile:ctreq] Controller 'form', required by directive 'valTab', can't be found!
https://errors.angularjs.org/1.8.0/$compile/ctreq?p0=form&p1=valTab
    at angular.js?cdv=2029199028:138
    at getControllers (angular.js?cdv=2029199028:10741)
    at getControllers (angular.js?cdv=2029199028:10748)
    at nodeLinkFn (angular.js?cdv=2029199028:10657)
    at compositeLinkFn (angular.js?cdv=2029199028:9900)
    at publicLinkFn (angular.js?cdv=2029199028:9765)
    at lazyCompilation (angular.js?cdv=2029199028:10179)
    at boundTranscludeFn (angular.js?cdv=2029199028:9943)
    at controllersBoundTransclude (angular.js?cdv=2029199028:10703)
    at ngRepeatAction (angular.js?cdv=2029199028:33980)
```

which in turn links to the following documentation on the Angular JS site:

https://code.angularjs.org/1.8.0/docs/error/$compile/ctreq?p0=form&p1=valTab

### Posible solutions

As per the Angular JS documentation found at:

https://docs.angularjs.org/api/ng/directive/ngForm

I found updating:

`<div ng-controller="My.Controller as vm">`

to:

`<ng-form val-form-manager ng-controller="My.Controller as VM">`

or:

`<div ng-form="some-form-name" val-form-manager ng-controller="My.Controller as VM">` 

resolved the javascript error, and tabs worked as expected.

Happy to create a pull request if helpful.

---
_This item has been added to our backlog [AB#11067](https://dev.azure.com/umbraco/243e7927-03b2-44e2-908f-d4ac7ea5daaa/_workitems/edit/11067)_

**Comment by nul800sebastiaan** [comment]
I'm not sure what the correct thing to do is here, will ask around and get back to you.

**Comment by nul800sebastiaan** [comment]
Thanks again @snerpton - we'll be having a look at this in our next upcoming sprint.

**Comment by snerpton** [comment]
@nul800sebastiaan Perfect result, thank you :-)

**Comment by abjerner** [comment]
The documentation for `umbEditorHeader` has an example on how to use tabs - it may be used for inspiration for updating the docs for `umbTabsNav` (I think):

https://our.umbraco.com/apidocs/v8/ui/#/api/umbraco.directives.directive:umbEditorHeader

**Comment by madsrasmussen** [comment]
I have had a look at this and you are right the umbTabsNav uses the valTab directive which depends on a form and the validation-manager.

I had to do a bit of testing because the error doesn't happen if you use it inside a dashboard or property editor because these are already wrapped.

I have added the extra part to the documentation with a note that the form and directive are required.

You can see the PR here: #10083
