### ISSUE TITLE
Unsaved changes warning is always shown when changing content node permissions.

### ISSUE THREAD

**Issue by nikolajlauridsen** [umbraco/Umbraco-CMS#10043]
Whenever I change permissions for a specific content node, it always shows the "You have unsaved changes" dialog if I close the editor by clicking away, even if I've clicked saved just before, and the changes are persisted even if I click "Discard changes". It's worth noting that this doesn't happen if I click the "close" button, see gif for more detail.

![discard-warning](https://user-images.githubusercontent.com/16456704/112122204-53275380-8bc0-11eb-94d5-a8bb24dd1e96.gif)

## Umbraco version

I am seeing this issue on Umbraco version: I'm seeing this on the v8/dev branch (so 8.12.2?)

Reproduction
------------

1. Create a simple content type
2. Create a content node
3. Right-click on the node and click Permissions...;
4. Then click Set permissions for...;
5. Pick a user group and enable or disable an action;
6. Click Save.
7. You will now see the "You have unsaved changes" dialog if you click discard you can see that the changes are persisted

### Expected result

The window closes with no dialog.

### Actual result

The dialog is shown.

---
_This item has been added to our backlog [AB#13150](https://dev.azure.com/umbraco/243e7927-03b2-44e2-908f-d4ac7ea5daaa/_workitems/edit/13150)_

**Comment by nielslyngsoe** [comment]
Fixed by https://github.com/umbraco/Umbraco-CMS/pull/10777
Did though find somehow related issue, which is described here: https://github.com/umbraco/Umbraco-CMS/issues/10778
