### ISSUE TITLE
NetCore: MenuRenderingNotification should send TreeAlias, so you can tell what tree you are on.

### ISSUE THREAD

**Issue by KevinJump** [umbraco/Umbraco-CMS#10054]
The 'menuRenderingNotification' doesn't contain the tree alias, so when you subscribe to this notification event, you can't tell which tree you are on (e.g content, media, settings, etc.. so you can't write code to selectively add/remove items)

on v8 the 'TreeAlias' is part of the Sender object for Menu Rending events., 

this was added for Tree Node Rendering in pr PR #10024 - suspect very similar code is needed for MenuRendingNotifcations. 

There are also other items on the Sender object missing in netcore (e.g SectionAlias, TreeGroup, TreeTitle).

However I am not sure how useful they are and if they need adding? (e.g it really shouldn't matter what section your tree is in if you know the TreeAlias)

**Comment by bergmania** [comment]
Make sense.. I also added it to `RootNodeRenderingNotification`.

Thanks for reporting
