### ISSUE TITLE
Tab/Focus order when creating doctypes is broken

### ISSUE THREAD

**Issue by Myster** [umbraco/Umbraco-CMS#10058]
When I try and create a document type using the keyboard I have issues with tab and focus order.
**Steps to Reproduce:**
Edit a doctype.
Click Add Property
Type name > Tab ...  select datatype > enter > Tab 
Now my address bar has focus, rather than the 'mandatory' checkbox 😢
I cannot press tab to focus on the ''Add property" button 😢

Umbraco is awesome 😁 ... this was working in earlier versions of Umbraco, but has since regressed.

Umbraco version 8.6.1

**Comment by nul800sebastiaan** [comment]
This works great in 8.12.2! You'll think that version is even more awesome 😉


https://user-images.githubusercontent.com/304656/112444503-65cf9300-8d4e-11eb-945a-c44baf9f53fe.mp4
