### ISSUE TITLE
rel=nofollow on links

### ISSUE THREAD

**Issue by Myster** [umbraco/Umbraco-CMS#10051]
There seems to be some small demand for the ability to 'easily' add rel=nofollow on a link by link basis: as evidenced here:
https://our.umbraco.com/forum/using-umbraco-and-getting-started/91058-umbraco-link-configurations
If this is a needed feature perhaps this issue will garner some likes.

**Thoughts**
1 ) Does this need to be on the link picker, the RTE, or both?
2 ) It may be useful to have an extensible method to enable the addition of other attributes/classes/ids/data-attributes to a link also?

**Comment by nul800sebastiaan** [comment]
Thanks @Myster - we recommend extension methods or PropertyValueConverters for this for now. Browser vendors are shifting to privacy by default (https://blog.mozilla.org/security/2021/03/22/firefox-87-trims-http-referrers-by-default-to-protect-user-privacy/)  and we expect the rel attribute to no longer be necessary not too long from now.

**Comment by rbottema** [comment]
Small nitpick: the `rel=nofollow` is used for SEO purposes: telling the search index not to follow the link, saving crawl budget. Maybe you are confusing it with the `rel=noopener`, which is indeed used for privacy and security purposes. I don't think it changes the answer from Umbraco, just wanted to clarify.
