### ISSUE TITLE
Would be nice if default urlReplacements merged with umbracoSettings.config specified ones.

### ISSUE THREAD

**Issue by mistyn8** [umbraco/Umbraco-CMS#10062]
https://github.com/umbraco/Umbraco-CMS/blob/9ac4eacdbd0b8858bd5a9e19f2d830a862bc61c6/src/Umbraco.Core/Configuration/UmbracoSettings/RequestHandlerElement.cs

Defaults are dropped if `<urlReplacing><char/></urlReplaceing>` exists..

So you have to remember to redefine all the defaults even if all you want to do is override a single entry.

**Comment by nul800sebastiaan** [comment]
Yes would be nice @mistyn8. Unfortunately that is an enormous breaking change (everybody's URLs would change), so we have to maintain the current behavior for now. For now and for v9 we have no changes planned for this feature.

**Comment by mistyn8** [comment]
just a documentation update then?
https://our.umbraco.com/Documentation/Reference/Config/umbracoSettings/index-vpost8_6_0 is a little sparse ;-)
