### ISSUE TITLE
umbImageCrop directive is not responsive (umb-image-crop)

### ISSUE THREAD

**Issue by markadrake** [umbraco/Umbraco-CMS#10064]
I'm having some trouble reusing the umbImageCrop directive (umb-image-crop) in a responsive manner. I'm wondering if anyone has used this in something they've done and could point me to what I'm doing wrong to ensure the resulting viewport maintains the aspect ratio of the crop.

## Umbraco version

I am seeing this issue on Umbraco version: 8.12.1+ (or latest)

Reproduction
------------

### Bug summary

- Although the `max-size` attribute works to resolve the issue, it's not elegant, and you can set a value that is still too large for the viewport which results in the same issue.

### Specifics

**Source code:**

`<umb-image-crop 
    src="model.images[0].image"
    crop="model.crop"
    width="{{model.cropSize.width}}"
    height="{{model.cropSize.height}}"></umb-image-crop>`

- **Src** is the image source.
- **Crop** is an object containing x1, x2, y1, and y2 (all null to begin)
- **Width** depends on the aspect ratio I've defined elsewhere, but lets say this is 1920.
- **Height** same as width, but lets say this value is 1080.

**When the image width above is larger than the dialog width...**

- The width of the viewport (including the semi-opaque margin) is reduced so that it fits inside of the dialog. This is to prevent scrolling on the x-axis. Makes sense.
- The height of the viewport remains true to the height value assigned. That's to say - the height is not automatically adjusted for the new width dimension. The result is a viewport that is not true to the original aspect ratio (width/height).
- Further, the image cropper holds true to the width value. So you may fight trying to scroll the image further to the left and think to yourself "this isn't working" when actually it's the viewport that's the problem (you've scrolled the image to the far-right constraint already).

**What does the max-size attribute do anyways?**

Well, if we use the max-size attribute it constrains both the width and height value. The problem is there's no way to simply say "the max size should be dependent on the available width". I can't say "100%" here. I have to give it a specific number.

Temporary fix - I'll use the `max-size` attribute...

For now I'll use the max-size attribute... But there must be something I've missed? If there is indeed no way to force responsiveness, would HQ mind if I updated this directive to include an optional parameter to allow true responsiveness?

### Steps to reproduce

- Try the source code for yourself. I'm using it in a custom dialog.
- Apply a large image crop size, say 1920x1080 (16:9 ratio).
- Use a small or medium sized dialog so the width is less than 1920px.
- The UI is not responsive in the sense it respects the aspect ratio of the crop, and it's also provides a confusing UX because the image extends beyond the margin, so you may think "why can't I push this image left any further"?

### Expected result

- I think the default behavior of this component should be to maintain the aspect ratio of the requested image size. 
- No need to set a `max-size` attribute at all. But if you do, it too needs to respect the available width. If the available width is smaller than the max size, it should become responsive too.

### Actual result

- Aspect ratio is not respected.
- UI is not responsive.
- UX is confusing in this state. (Moving the image around when the viewport is not accurately displaying how much of the image is actually in the crop.)

## References

- [Umbraco Forums Post](https://our.umbraco.com/forum/using-umbraco-and-getting-started/105478-trouble-making-umbimagecrop-directive-responsive-umb-image-crop)
- [umbimagecrop.directive.js](https://github.com/umbraco/Umbraco-CMS/blob/34e80d86e8c0b754f6b7a02e307f53cb32806bbe/src/Umbraco.Web.UI.Client/src/common/directives/components/imaging/umbimagecrop.directive.js)
- [umb-image-crop.html](https://github.com/umbraco/Umbraco-CMS/blob/34e80d86e8c0b754f6b7a02e307f53cb32806bbe/src/Umbraco.Web.UI.Client/src/views/components/imaging/umb-image-crop.html)

**Comment by markadrake** [comment]
This is mostly copied from [the post I made on the official Umbraco Forums](https://our.umbraco.com/forum/using-umbraco-and-getting-started/105478-trouble-making-umbimagecrop-directive-responsive-umb-image-crop). I thought providing a bug report may bring it to the attention of other developers.

**Comment by emma-hq** [comment]
Hey Marc,

Thanks for submitting this issue - it's a good one. So much so that we're actually looking at this internally. I've spoken to the frontend-team and have been informed that Media picker v3 will have a responsive umbImageCrop directive. 

The work that's happening is here #9461 so you can keep an eye on the progress here. 

With that in mind, I'll close this issue but of course feel free to get in touch if you've any questions.

Emma

**Comment by markadrake** [comment]
Thanks for the speedy update @emma-hq! I wasn't aware the team was updating this component, much less already addressing some of my primary concerns with it. I apologize for the oversight and additional issue/ticket here.

If you don't mind me asking this question here:

1. Would HQ consider exposing some of the ImageProcessor plugins as part of the UI? 
[An example could be brightness](https://imageprocessor.org/imageprocessor-web/imageprocessingmodule/brightness/).

When we adjust an image crop in the backoffice, I can't think of a scenario when it's not in regards to how the image is displayed on the frontend. So although this may on the surface sound strange - why would I want to apply brightness, contrast, filters, rounded corners, or other pluguins when I'm simply changing the image crop? It's to give the editor control of how the image is displayed, so it's not hardcoded in the template. (Or potentially, default values could be assigned when this data type is configured.)

**Comment by emma-hq** [comment]
Thanks for the input @markadrake  - I completely see what you mean here. Could I get you to log an issue for the above and I'll label it as a feature and we can discuss at hq? Might even be worth waiting for the v3 release and then raising it, in case there's something you'd like to add.

Emma
