### ISSUE TITLE
NetCore: Can't enable AppData mode for models builder in Alpha4

### ISSUE THREAD

**Issue by TwoMoreThings** [umbraco/Umbraco-CMS#10060]
A brief description of the issue goes here.

Despite changing the ModelsMode to AppData in appsettings.json, the back office still show the mode as PureLive, leaving no way to generate models.

## Umbraco version

I am seeing this issue on Umbraco version: Alpha4 (9.0.0-alpha004+f59d36624d2767815768a571c801a870107042fa)

Reproduction
------------
Update the umbraco template to alpha4 and created a new solution.
edit the appsettings.json ModelsMode to AppDatat
build and run the solution
go to Setting and the models builder tab and check the models mode.

I've tried this a couple of times on fresh solutions. First time round I ran the solution and created a couple of doctypes then changed the modelsmode. The second time I changed the mode before building and running the solution.

I also tried (for the first solution), deleting the generated models that were created in PureLive mode. I also tried changing the project setting RazorCompileOnBuild and that made no difference

Finally (in both solutions) I tried creating a new doctype to see if that helped, this made no difference.

### Expected result

I'd expect the mode to show as AppData and have the option to generate models. Models do show as out of date

### Actual result

The mode shows as PureLive and there is no way to generate models, although models do show as out of date

![2021-03-25 08_25_41-appsettings json - testAlpha4 - Visual Studio Code - Insiders](https://user-images.githubusercontent.com/13945979/112442470-c5747100-8d43-11eb-990e-9bcbcbb2dc05.png)
![2021-03-25 08_25_15-Settings - localhost](https://user-images.githubusercontent.com/13945979/112442474-c5747100-8d43-11eb-847d-4b756888de4b.png)

**Comment by nul800sebastiaan** [comment]
Could it be this @TwoMoreThings ? https://twitter.com/BjarkeBerg/status/1374790572444094468

**Comment by nul800sebastiaan** [comment]
And following the thread: https://twitter.com/BjarkeBerg/status/1374790572444094468 might need to include models in project..

**Comment by TwoMoreThings** [comment]
I'm not getting the option to generate models so there's nothing to include in the project :(
t

**Comment by nul800sebastiaan** [comment]
Ah interesting, yeah I can reproduce it:

![image](https://user-images.githubusercontent.com/304656/112479233-210b2280-8d75-11eb-8f26-95a47385bf6c.png)

**Comment by bergmania** [comment]
I can confirm the bug.

### Workaround:
Change the method `Startup.ConfigureServices` to:
```
        public void ConfigureServices(IServiceCollection services)
        {
            var builder = services.AddUmbraco(_env, _config)
                .AddBackOffice()
                .AddWebsite()
                .AddComposers();

            builder.Services.Configure<ModelsBuilderSettings>(builder.Config.GetSection(Constants.Configuration.ConfigModelsBuilder));
            
            builder.Build();
        }
```

**Comment by OwainWilliams** [comment]
If anyone else stumbles across this issue, you also need to add two usings to the top of the Startup File.

using Umbraco.Cms.Core;
using Umbraco.Cms.Core.Configuration.Models;

**Comment by bergmania** [comment]
I added another workaround if anyone are interested

**Comment by Jeavon** [comment]
I upgraded some docs samples from alpha3 to alpha4, I'm unsure if it's directly related to this issue but I had to move the models out of the umbraco folder with alpha4 in order to reference them in the views, might be related to the namespace changes, maybe I'm missing something else...

`"ModelsDirectory":  "~/models" `

**Comment by bergmania** [comment]
I think you should just explicitly add the folder to your solution, as the folder is ignored in the template (because that make sense If you use PureLive). 

Another thing that make sense to change if not using Live modes, are this setting in the csproj:

```
 <!--Set this to true ModelsBuilder mode is not PureLive -->
    <PropertyGroup>
        <RazorCompileOnBuild>false</RazorCompileOnBuild>
    </PropertyGroup>
```
