### ISSUE TITLE
NetCore (alpha4): Problem with models builder and nested content

### ISSUE THREAD

**Issue by AndyButland** [umbraco/Umbraco-CMS#10073]
I found a problem using a nested content data type related to model builder (using V9 alpha 4).

To replicate:

- Create an element type, called "Nested Item", with one tab "Content" and one text string property "Title".
- Create a document type with template, called "Home", with one tab "Content" and one nested content property "Nested Items".
- Configure the nested content property to use the element type.
- Create an instances of the "Home" content

Under _Settings > Models Builder_ I see "Last generation failed with the following error":

```
Failed to build PureLive models.
Roslyn compiler could not create ModelsBuilder dll:
The type or namespace name 'NestedItem' could not be found in the global namespace (are you missing an assembly reference?)
The type or namespace name 'NestedItem' could not be found in the global namespace (are you missing an assembly reference?)

at Umbraco.Cms.Infrastructure.ModelsBuilder.RoslynCompiler.CompileToFile(String pathToSourceFile, String savePath)
at Umbraco.Cms.Web.Common.ModelsBuilder.PureLiveModelFactory.GetModelsAssembly(Boolean forceRebuild)
at Umbraco.Cms.Web.Common.ModelsBuilder.PureLiveModelFactory.EnsureModels()
```

Looking at the generated code, I can see the nested content property on "Home" is reference like this:

```
public global::System.Collections.Generic.IEnumerable<global::NestedItem> NestedItems ...
```

If I remove that `global::` prefix, it compiles OK.

**Comment by bergmania** [comment]
Thanks for reporting.. I'm not sure why it needs to have the `global::`. Maybe we should just remove it...

**Comment by elit0451** [comment]
I don't think it is related to the `global::` prefix - that is the way we have it in v8 and there it works. 
I've also compared the auto-generated code with segments from the files generated through `AppData` mode and they are identical, so it is something else, not related to the generated code 🤔  

P.S. No errors from generating the models with `AppData` mode.

**Comment by chris-evansnz** [comment]
@elit0451  in regards to AppData mode; how do we properly enable this using v9 alpha 004? 

We have the following in our appsettings.json file:

```
"ModelsBuilder": {
      "ModelsMode": "AppData",
      "Enable": true
    }
```

But despite this, the backoffice still claims to be in PureLive mode, and we can't see any .cs files turn up for our doctypes.
      
![image](https://user-images.githubusercontent.com/58791033/114970347-5d422680-9ece-11eb-8ec0-dbdfd3bcf5a0.png)

**Comment by AndyButland** [comment]
Hi @chris-evansnz - I noticed this was already reported as an issue with alpha 4.  There's a workaround suggestion and the possibility of upgrading to a nightly discussed [here](https://github.com/umbraco/Umbraco-CMS/issues/10060).
