### ISSUE TITLE
Integrate with ArcGIS Webmaps or web feature layers including options for filtering.

### ISSUE THREAD

**Issue by mbrooksNPDC** [umbraco/Umbraco-CMS#10105]
A brief description of your feature request goes here.

Integrate with ArcGIS Webmaps or web feature layers including options for filtering.

In the terratype documentation there is talk of potential future work integrating ArcGIS products similar to the way Google, Bing and Leaflet is currently used.

Please consider ArcGIS webmaps or Web Feature layers  including filtering and exposing related (and dynamic) tables.

Contact ESRI, there are a lot companies who partner with them.
I look forward to using more capabilities further than embedding our corporate data via iframe. 

Thanks for the consideration

How can you help?
-------------------------------

**Comment by nul800sebastiaan** [comment]
Thanks @mbrooksNPDC, we have no such plans for integration. We recommend developing a package (plugin) for that. We have some documentation around making packages here: https://our.umbraco.com/documentation/Extending/Packages/
