### ISSUE TITLE
Support Upload in Block List

### ISSUE THREAD

**Issue by bjarnef** [umbraco/Umbraco-CMS#10103]
Based on Umbraco v8.12.2 it seems the `Umbraco.Upload` is currently not supported in block list.
Is there a specific reason this isn't supported?

It could be useful in a list of files, where a "Block File" is used.

![image](https://user-images.githubusercontent.com/2919859/113680850-98b84600-96c1-11eb-9042-9003ea0f7b56.png)

A media picker could be used, but we don't always want to create uploads in media section.
For this specific use-case the block list items are created dynamically via a form, where it is possible to use set a title/name and select a file via file upload.

**Comment by nul800sebastiaan** [comment]
I can't remember exactly why this isn't possible, but unfortunately we've tried multiple times and have not been able to make this work. Therefore you will get this error instead.

**Comment by bjarnef** [comment]
Yes, it could be useful though, but not sure if some if there is something technically preventing this from working. For the specific use-case I have used media picker instead, where I however don't really need to re-use the media picker thus a file upload would have been great.

**Comment by bjarnef** [comment]
I just tried comment out this line with `Umbraco.UploadField`:

https://github.com/umbraco/Umbraco-CMS/blob/d428a4543f33bb7094cf7db5f6b6fdc2d1de3063/src/Umbraco.Web.UI.Client/src/common/services/blockeditormodelobject.service.js#L232

The UI part seems to be working:

![image](https://user-images.githubusercontent.com/2919859/114071749-c52ab880-98a1-11eb-8172-5c7f058c99db.png)

But it breaks here on save because content guid is empty:

![image](https://user-images.githubusercontent.com/2919859/114071706-b47a4280-98a1-11eb-885a-327fa2479226.png)

![image](https://user-images.githubusercontent.com/2919859/114071490-7846e200-98a1-11eb-8964-ec12288a7db0.png)

**Comment by bjarnef** [comment]
I had a look at it here https://github.com/umbraco/Umbraco-CMS/pull/10115 but it seems something is missing. However I am able to render to file name 😅

**Comment by nielslyngsoe** [comment]
Hi @bjarnef, If I recall correctly the problem of uploading files within Bl or NC, is that the input field might be gone when submitting the document. I think the HTML-input holding the file still needs to be represented when submitting.

There might be other details to why its not working of today, which i cant remember right now.

It would though be possible if we handled files differently. Example uploaded the file instantly and not just when the document is begin submitted. But that would require another infrastructure for file upload.

**Comment by bjarnef** [comment]
@nielslyngsoe the Upload looks almost like we know it, but it has some strange issues with loading the correct image with more blocks in the list.

On a content node it seems there is easy access to content item and the `UploadedFiles` property, but it seems to be different for the BL. Anyway I played a bit with it here 😁 
https://github.com/umbraco/Umbraco-CMS/pull/10115
