### ISSUE TITLE
Allow error messages in the backoffice to be displayed for longer

### ISSUE THREAD

**Issue by Slipoch** [umbraco/Umbraco-CMS#10116]
Allow errors and warnings that are displayed in the backoffice to be displayed for longer.

**Comment by nul800sebastiaan** [comment]
Hi there @Slipoch, what is the reason behind this request please?

**Comment by Slipoch** [comment]
The client cannot see he missed a mandatory field. He saw a eed box appear and couldnt see the field outline.Sent from my Galaxy
-------- Original message --------From: Sebastiaan Janssen ***@***.***> Date: 09/04/2021  4:38 pm  (GMT+10:00) To: umbraco/Umbraco-CMS ***@***.***> Cc: Slipoch ***@***.***>, Mention ***@***.***> Subject: Re: [umbraco/Umbraco-CMS] Allow error messages in the backoffice to
  be displayed for longer (#10116) 
Hi there @Slipoch, what is the reason behind this request please?

**Comment by nul800sebastiaan** [comment]
Thanks @Slipoch - I really need a little bit more information than this, could you show a screenshot of where this went wrong, or a screen recording would be even better?

**Comment by nul800sebastiaan** [comment]
Thanks again for the report, I'll close this for now until we get some more information.
