### ISSUE TITLE
The Generic Media File Extension Label is Illegible

### ISSUE THREAD

**Issue by craigs100** [umbraco/Umbraco-CMS#10111]
## Brief description of the issue ##

When uploading a file type that doesn't generate and thumbnail the file extension is laid over a generic icon. The extension text's background colour is pale pink (#fee4e1) and the text is white (#ffffff). This makes it very difficult to read the file type.

## Umbraco version ##

I am seeing this issue on Umbraco version: 8.12.2

### Steps to reproduce

From any media picker, upload a pdf file (for instance but any non-graphic file will do) and note the icon thus:-
![illegible-icon-label](https://user-images.githubusercontent.com/1143883/113926261-da411200-97e3-11eb-8a05-aa06c66b6cdf.png)

This is due to the colour set in Umbraco-CMS/src/Umbraco.Web.UI.Client/src/less/components/umb-file-icon.less line 24 (@ui-active) being #fee4e1

### Expected result

A clearer, more legible contrast between the font color and background-color. The following image shows a background-color of #d70240 but any approved brand colour that provides adequate contrast and therefore legibility would do:-

![legible-icon-label](https://user-images.githubusercontent.com/1143883/113926786-8a167f80-97e4-11eb-8035-a375333b7ad8.png)
 

(I'd have done a PR myself but I couldn't work out where @ui-active was set ;) )

**Comment by bjarnef** [comment]
Originally it looked like this https://github.com/umbraco/Umbraco-CMS/pull/6293

But the color of `@ui-active` has changed since then, so we should either update the text color or choose a different background color for the label. @nielslyngsoe

**Comment by craigs100** [comment]
Probably simpler, and more brand compliant to change the text to black? Didn't realise the significance of ui-active till later.

**Comment by nielslyngsoe** [comment]
I´m sad that we didn't spot this earlier, but it did come to my awareness recently and therefore its begin fixed in the next release, as part of Media Picker 3.
https://github.com/umbraco/Umbraco-CMS/pull/9461
