### ISSUE TITLE
ContentService Published event not firing for scheduled publish

### ISSUE THREAD

**Issue by f33n3y** [umbraco/Umbraco-CMS#10114]
## Umbraco version

8.6.3

Reproduction
------------
Create a component to listen for ContentService.Saving events by following the Umbraco Docs example:
https://our.umbraco.com/documentation/Implementation/Composing/#example---creating-a-component-to-listen-for-contentservicesaving-events

Add some dummy logic in the event handler 
Set a breakpoint and debug
Publish a test page and check your breakpoint is hit
Now schedule the page for publish 
You should find that the event handler and breakpoint never gets hit (but page does publish successfully). 

### Bug summary

Our website has a strong dependency on publish events to send data off to be indexed in Azure.
Our client relies a lot on scheduled publishing to publish content at certain times but due to event handlers not firing for scheduled publish, key logic is not firing and items are never being indexed.

### Expected result

As a publish is taking place, I would have expected events relating to publishing to fire

### Actual result

No content service events seem to fire when a scheduled publish takes place

**Comment by nul800sebastiaan** [comment]
Thanks @f33n3y - we'll have a look and see what's up.

**Comment by nul800sebastiaan** [comment]
Hey @f33n3y, I've given it a spin (on version 8.12) and this work as I expect it to. When you schedule a node then it saves it without publishing. As soon as the scheduler sees it's time to publish the node, it will do so an trigger the `Publishing` event, which is what you should be hooking into, this is my sample code I used to verify this:

```csharp
using Umbraco.Core;
using Umbraco.Core.Composing;
using Umbraco.Core.Events;
using Umbraco.Core.Services;
using Umbraco.Core.Services.Implement;

namespace Umbraco812Solution.Core
{
    [RuntimeLevel(MinLevel = RuntimeLevel.Run)]
    public class EventHandlersComposer : ComponentComposer<EventHandlersComponent>
    { }

    public class EventHandlersComponent : IComponent
    {
        public void Initialize()
        {
            ContentService.Publishing += ContentService_Publishing;
        }

        private void ContentService_Publishing(IContentService sender, ContentPublishingEventArgs e)
        {
            foreach (var node in e.PublishedEntities)
            {
				// Set a breakpoint on the next line so we know it worked
                var x = node.Id;
            }
        }

        public void Terminate()
        {
            ContentService.Publishing -= ContentService_Publishing;
        }
    }
}
```

I can't imagine that this doesn't work in 8.6, but if it doesn't then I'd recommend you attempt to upgrade to 8.12 and try again.
