### ISSUE TITLE
Umbraco "rollback to" doesn't include saved revisions

### ISSUE THREAD

**Issue by shearer3000** [umbraco/Umbraco-CMS#10131]
Hi – The “Rollback to” list of previous versions only includes “Saved + Published” content and not revisions that were only “Saved”.
Our content editor wishes to rollback to a specific “Saved” content revision. Is this possible?
Thanks

**Comment by nul800sebastiaan** [comment]
Hi @shearer3000, this is not possible any more, we had this in v4(6?) but it caused problem with the amount of data for saving all those versions in the database for each little change that editors saved. 
That said, I think it would be really cool to have a package that could try to do something similar maybe using the local storage api in browsers. 
We have no plans to include this as a feature in CMS at the moment.
