### ISSUE TITLE
Opt out of Google's FLoC user profiling

### ISSUE THREAD

**Issue by SimonHilo** [umbraco/Umbraco-CMS#10147]
Based on the arguments given by EFF, I believe we should make opting out of Google's FLoC initiative the default setting in Umbraco:

https://www.eff.org/deeplinks/2021/03/googles-floc-terrible-idea

### The problem in short
FLoC is a new technology built in to Chrome that enables targeted advertising. It's supposed to be more private way of targeting ads. It skips the whole sharing of people's browsing history, and groups people together in "cohorts" by a in-browser algorithm. But it still has privacy issues as explained in the link above. 

Worse is that it can be used to discriminate based on race, sex, political view etc. EFF writes: "The power to target is the power to discriminate. By definition, targeted ads allow advertisers to reach some kinds of people while excluding others. A targeting system may be used to decide who gets to see job postings or loan offers just as easily as it is to advertise shoes." Read the link above for an elaboration of this argument.

### Opting out
Limited testing of FLoC is already rolled out in certain places in the latest Chrome, and it is (of course) opt-out for both users and site owners. 

As site owners we can opt out of having our site used for profiling users by setting a HTTP response header:

> Permissions-Policy: interest-cohort=()

I think we should make this the default in Umbraco, making FLoC opt-in for Umbraco site owners.

I'll make a PR that adds this header.

Other links:
https://blog.google/products/chrome/privacy-sustainability-and-the-importance-of-and/
https://github.com/WICG/floc
https://plausible.io/blog/google-floc

**Comment by beltofte** [comment]
Looked at the pull request. Removing the Permissions-Policy could be dangerous - it has other purposes too. See [w3c's documentation](https://github.com/w3c/webappsec-permissions-policy/blob/main/permissions-policy-explainer.md). 

The best solution, even though that it is more complex to implement, would be to check if the Permissions-Policy header exist, and in this case add interest-cohort=() to the list of header values. If the Permissions-Policy header does not exist, then just add it with the empty interest-cohort value.

**Comment by SimonHilo** [comment]
I see. It wasn't as simple as I expected. I'll give it another shot.

**Comment by emma-hq** [comment]
Hey @SimonHilo 

Just to let you know we see this and we're talking about it internally. Will shout when we have decided on anything!

Emma

**Comment by SimonHilo** [comment]
Thanks, Emma. I'm aware that it's a political suggestion.

There's lots of discussion about this in the wordpress community:
https://make.wordpress.org/core/2021/04/18/proposal-treat-floc-as-a-security-concern/

I hope we can have the same discussion here.

My position is that FLoC is bad, and we should take a stand while the spec is still in its infancy. Should it turn into something mature that developers use and need, we can reverse the decision. And i'm only suggesting changing the default.

**Comment by nul800sebastiaan** [comment]
Thanks @SimonHilo for sharing your concerns! We feel it's not our place or task to enforce this kind of blocking, we believe site implementers should be free to use whatever services they think make sense for their sites (as well as block them when they want). 

I'll therefore close this issue and your pull request, while letting you know that we do appreciate the effort and it's  good that people can see from your PR how they could block FLoC if they wanted to.

At the same time, we will keep monitoring the situation and we very much encourage more discussion on this issue and elsewhere. We can always reconsider if something critical were to come up.
