### ISSUE TITLE
SQL Index contains NTEXT column

### ISSUE THREAD

**Issue by JohnBergman** [umbraco/Umbraco-CMS#10165]
Our DBA reported this to use today and I wanted to raise it here.

Umbraco 8.12.1

The table umbracoPropertyData has a clustered primary key that appears to include all columns, where textValue is NTEXT in the table.

Below is the message from the DBA

-=-
An online operation cannot be performed for index 'PK_umbracoPropertyData' because the index contains column 'textValue' of data type text, ntext, image or FILESTREAM. For a non-clustered index, the column could be an include column of the index. For a clustered index, the column could be any column of the table. If DROP_EXISTING is used, the column could be part of a new or old index. The operation must be performed offline. [SQLSTATE 42000] (Error 2725)  USE [StarsLinkUmbracoPreview]; ALTER INDEX [PK_umbracoPropertyData] ON [dbo].[umbracoPropertyData] REBUILD WITH (ONLINE = ON); [SQLSTATE 01000] (Error 0).  The step failed.
 
We’re working on our part in having the job intelligent enough to switch between Online or Offline when needed.  However, I want to bring to your attention the column:
 
        Table           Column          Data Type
        PropertyData    textValue       nText
 
The Data types text and nText are deprecated.  If you need to store more than 8000 or 4,000 characters they should be replaced by varchar(MAX) and nvarchar(MAX).  If you don’t need to store that many characters then it should be varchar(#) or nvarchar(#) where the # is appropriately sized to the max characters to be allowed in the field.

**Comment by nul800sebastiaan** [comment]
Thanks @JohnBergman, a default Umbraco install does not add keys or indexes to the ntext field (`textvalue`). You can see the indexes and primary keys we create for it here: https://github.com/umbraco/Umbraco-CMS/blob/v8/contrib/src/Umbraco.Core/Persistence/Dtos/PropertyDataDto.cs - the primary key only includes the `Id` column.

We know this is a deprecated type, but for backwards compatibility we're still keeping it around for now.
