### ISSUE TITLE
Upload file/Replacement with the same name 

### ISSUE THREAD

**Issue by davit20** [umbraco/Umbraco-CMS#10173]
If you have uploaded a file in the media section and you want to change something inside it doesn't take new changes after file upload with the same name

Reproduction
------------

For example, 
1. I have uploaded UmbracoTest.css file. (inside btn backgroud-color: #e30613)
2. I want to change backgroud-color in the file, I changed it with #228B22 color and uploaded a file with the same name(UmbracoTest.css) for the same media file.
3. when I checked the file by clicking on the file URL I see that there is no new file and is the old one.(with color #e30613)
4. But if you upload file with the different name it works correctly.

### Specifics
Using Umbraco 8.12.2 version 
browser chrome Version 90.0.4430.72 (Official Build) (64-bit)
I didn't check it in other browsers.

**Comment by davit20** [comment]
Hi @nul800sebastiaan 
There are some situations that back-office users want to add some CSS for some pages/page contents.
We have many pages so we decided to give an opportunity to back-office users to apply some custom CSS for page content and as a developer, I'm not defining the new CSS script for example for one page.

![image](https://user-images.githubusercontent.com/20552762/115752563-45294600-a3ab-11eb-88cf-58710cc94e13.png)
![image](https://user-images.githubusercontent.com/20552762/115752908-9e917500-a3ab-11eb-8a4a-1172bd7914ad.png)

**Comment by nul800sebastiaan** [comment]
Alright, thanks for the additional info. This sounds like an excellent question for the forums where our friendly community can help you find the best solution for your requirements. 
Make sure to head on over to https://our.umbraco.com and ask follow up questions there! 👍
