### ISSUE TITLE
Adding image via RTE shows a property that isn't used.

### ISSUE THREAD

**Issue by iishnz** [umbraco/Umbraco-CMS#10206]
Within the Rich Text editor, when adding a media image, there is a property called "Caption", filling in this property has no effect
when rendering, further more the value does not get saved.

## Umbraco version

The version of Umbraco I am using is 8.13.0

### Reproduction

On a fresh install of Umbraco

1. Create a doc type
2. Add a property of type Rich Text Editor
3. Add an image into the Media section
4. Create a content page using the Doc Type you made
5. In the RTE property, click the media picker
6. Fill in the properties; Alternative text (optional), Caption (optional), and select an Image
7. Notice in the Backoffice that you do not see the Caption appear anywhere
8. Render the page, and observe that you do not see the Caption appear anywhere

### Specifics

I believe this might be a result of this PR: #5596 

### Expected result

Either there shouldn't be a Caption property when adding an image via the RTE - or it's disabled - or it should be rendered out, otherwise this is a very confusing UX.

**Comment by nul800sebastiaan** [comment]
Thanks for the report @iishnz, did you check if you the caption is output as the alt text instead? I believe that's where it might end up..

**Comment by iishnz** [comment]
Hi @nul800sebastiaan There is a separate Alternative Text property which correctly updates/sets the alt attribute of the image.  
If the Alternative Text property is left blank and the Caption property is populated the alt attribute on the image tag is blank, so the caption does not seem to interact with the alt attribute - However if it did, that would still be confusing.

**Comment by creativesuspects** [comment]
I'm seeing the same issue on Umbraco 9.0.1. The Alternative Text property is used to set the alt-attribute for the image. The Caption property does nothing, when I set the Caption property the value is not being saved at all.

https://user-images.githubusercontent.com/161342/141976517-da04cdf1-e7ae-4a4b-9928-ee7ea5d623cc.mp4

**Comment by nul800sebastiaan** [comment]
Fixed in https://github.com/umbraco/Umbraco-CMS/pull/11807

**Comment by kjac** [comment]
It seems this issue has indeed been fixed for V9+.

@russellshome while V8 is LTS, we are no longer fixing things nor creating patch releases for fixes unless they are regressions from V8.15 (during LTS regressions are fixed for the last three minors).
