### ISSUE TITLE
NetCore: Only "en-US" pages are reachable.

### ISSUE THREAD

**Issue by olibos** [umbraco/Umbraco-CMS#10218]
### Bug summary

For an unknown reason, this release routes only pages in "en-US".
If I change the default language to any other language than "en-US" the page will not be reachable anymore.
Video sample: http://www.youtube.com/watch?v=pCmTfT4Mu30

### Specifics

Umbraco: 9.0.0-beta001
Tested on Chrome, Edge & Firefox

### Steps to reproduce

* Setup a simple website
* Add an empty document type with "Allow vary by culture" checked.
* Create a page in content
* Save & Publish
* The page is available 👍
* Go in Settings>Languages
* Update the default language to any other language than "en-US"
* Return to Content
* Save & Publish
* In "Links" we have now: "This document is published but its URL cannot be routed" 😭

### Expected result

The page should be routable whatever its language.

### Actual result

Only en-US pages are reachable (even "en" are not routed).

**Comment by bergmania** [comment]
Hi @olibos ..

Thanks for reporting.. The description and video have nice details, so we will need to investigate..

**Comment by olibos** [comment]
Hello @bergmania ,

Thank you for your response.
In the meantime I've found the reason!
In https://github.com/umbraco/Umbraco-CMS/blob/v9/dev/src/Umbraco.Core/Routing/PublishedRouter.cs#L323 , the router set the request culture to a default culture which breaks the ContentFinderByUrl because it will try to find the page "/fr" in "en-US" which is of course not available. I've added a pull request #10221 .

I don't know if this may cause other issue.
Let me know if I can help.

**Comment by olibos** [comment]
Hello @bergmania ,

My test was not correct.
So I've made a new one with the latest v8/contrib and the issue is in v8. So it's not specific to Umbraco 9!

I'll make a new issue for V8

Note: Iv'e checked with the latest nuget package and the issue is already in production 😭

**Comment by olibos** [comment]
Nevermind, I've forgot to set "Culture and Hostnames" which is required for the routing.
