### ISSUE TITLE
Models not generated on PureLive

### ISSUE THREAD

**Issue by skartknet** [umbraco/Umbraco-CMS#10220]
While I was testing #10213 I installed a brand new V9 site and found out that the models are not being generated at all.

On the Models Builder dashboard I can see that the mode is PureLive, but there's nothing being generated on the '~/umbraco/models' folder. The file ood.flag is in the folder and the dashboard says the models are out-of-date.

If I create a new doctype or I re-run the site nothing changes and models are still missing.

This applies to version 9.0.0-beta001.

**Comment by bergmania** [comment]
Hi @skartknet 

Do you have any interesting entries in the log? Normally `PureLive` works fine, so I guess it has something with your models to do.

**Comment by skartknet** [comment]
No, nothing on the logs :(

When I make some changes to a doctype I just get this: 
![image](https://user-images.githubusercontent.com/1685262/116966287-27d17180-acf3-11eb-93fa-e7bdcf507b3a.png)

**Comment by bergmania** [comment]
Interesting.. How is your doctypes setup? Maybe you can export them and add to this issue, then I can see if I can reproduce the issue..

**Comment by Shadyn** [comment]
Just going to throw this out there as I've been having the same issue for a week.  If there are doctypes that inherit other doctypes, the parent doctype needs to have a constructor without the publishedValueFallback.  This does not get generated currently by modelsbuilder, so it will fail to generate the models (or fail to compile in appdata mode)

![image](https://user-images.githubusercontent.com/4174228/117025809-d7d9b700-acc0-11eb-8c61-f70c6eeb7772.png)

Once I changed that for all of the parent doctypes, all the models began to work.  Not sure where this gets implemented.

**Comment by skartknet** [comment]
@bergmania false alarm. I thought the models were created when the doctypes are but I have found out that they are generated when a new page using the doctypes is created.
