### ISSUE TITLE
Cannot schedule content when logged in as Administrator (v9 beta 1)

### ISSUE THREAD

**Issue by adamhearn** [umbraco/Umbraco-CMS#10251]
Updating my Scheduled Content Dashboard package for Umbraco 9 I can't save a schedule entry with the test site. Site created with the documented dotnet steps, logged in as the default [administrator] user, single document type with one field. I can create and publish content without issue. When I apply a schedule time I get an unauthorised error shown.

## Umbraco version

I am seeing this issue on Umbraco version: v9 beta 1

Reproduction
------------

### Steps to reproduce

Create content item
Populate fields
Create schedule entries release and/or expiry

Saving the schedule the UI shows:

![image](https://user-images.githubusercontent.com/13589850/117534301-a6c2f480-afe8-11eb-8a7b-73f280782a4d.png)

### Expected result

Schedule should save as expected

### Actual result

Schedule is not persisted to the DB
The schedule times remain in the dialog

Provided HAR file taken from Edge:
[localhost.zip](https://github.com/umbraco/Umbraco-CMS/files/6445625/localhost.zip)

### Issue

Seems to be that the Administrator group has all permissions except for "Send To Publish" [which on the face of it makes perfect sense]. However, if that permission is granted the schedule request is processed/saved as expected. Maybe an incorrect RBAC assignment?!

**Comment by bergmania** [comment]
Hi @adamhearn ..

I can confirm I can reproduce, and the behaviour is different from Umbraco 8.
