### ISSUE TITLE
Umbraco 7.15.7 CSS subfolder not saving and not working in Umbraco backoffice - Upgraded from7.12.1

### ISSUE THREAD

**Issue by createitcarlos** [umbraco/Umbraco-CMS#10259]
I have tried this on Our but I thought is I would try here:

Here is my question on Our. I think I found the issue but it is in the Umbraco Core, so not quite messing with that unless you all have a hotfix I can do.

[](https://our.umbraco.com/forum/using-umbraco-and-getting-started/105967-css-subdirectories-in-umbraco-7157-issue-please-help)

Issue:

I recently updated to Umbraco 7.15.7 from 7.12.1 and found out that one of my CSS files was not being pulled in that was set up in a sub directory of the "/CSS/" folder that was working prior to the update.

I set up the subfolder for the CSS in my admin as: "myfolder/overrides.css" which in Umbraco admin had created it as "/css/myfolder/overrides.css" BUT now Umbraco is changing the css folder structure and not allowing subfolders for the CSS sheets on 'Save'. My assumption is it is a config setting, but I can't seem to find out which one. If that is the problem at all.

That said, Umbraco is now changing my subfolder CSS files to "/css/myfolderoverrides.css" with no slash between the folder and the stylesheet file name. Please help me out. I have quite a few of these because our instance runs multiple applications.

---------------

Also
So I tracked down, what I think, may be the crux of my issue. Though I may be wrong. Looking at the SaveFileController.cs I saw that the "SaveStylesheet" method was rewritten between Umbraco 7.12.1 and 7.15.7.

It looks like some clean up routines were written to sanitize files names for XSS. Which make sense, however, I think it broke the ability to create Subfolders for the CSS (probably for the Javascript subfolders to, have not tested) files.

In the 7.15.7 version the code for the routine in the SaveFileController.cs line 241 looks like this:

```csharp
    [HttpPost]
    public JsonResult SaveStylesheet(string filename, string oldName, string contents)
    {
        // sanitize input - stylesheet names have no extension
        var svce = (FileService)Services.FileService;

        filename = CleanFilename(filename.CleanForXss());
        oldName = CleanFilename(oldName);

        if (filename != oldName)
        {
            var stylesheetExists = svce.GetStylesheetByName(filename);
            if (stylesheetExists != null)
                return Failed(ui.Text("speechBubbles", "cssErrorText"), "A file named '" + filename + ".css' already exists.");
        }

        var stylesheet = svce.GetStylesheetByName(oldName);
        if (stylesheet == null)
            stylesheet = new Stylesheet(filename);
        else
            stylesheet.Path = filename;
        stylesheet.Content = contents;

        try
        {
            if (svce.ValidateStylesheet(stylesheet) == false)
                return Failed(ui.Text("speechBubbles", "cssErrorText"), ui.Text("speechBubbles", "cssErrorHeader"),
                                new FileSecurityException("File '" + filename + "' is not a valid stylesheet file."));

            svce.SaveStylesheet(stylesheet);
        }
        catch (Exception e)
        {
            return Failed(ui.Text("speechBubbles", "cssErrorText"), ui.Text("speechBubbles", "cssErrorHeader"), e);
        }

        return Success(ui.Text("speechBubbles", "cssSavedText"), ui.Text("speechBubbles", "cssSavedHeader"),
            new
            {
                path = DeepLink.GetTreePathFromFilePath(stylesheet.Path),
                name = stylesheet.Path,
                url = stylesheet.VirtualPath,
                contents = stylesheet.Content
            });
    }

    private static string CleanFilename(string filename)
    {
        return filename
            .Replace('\\', '/')
            .TrimStart('/')
            .EnsureEndsWith(".css");
    }
```

I noticed the `CleanForXss()` at the top of this method. I then followed that and in that method I found in the `Umbraco.Core` is the `StringExtensions.cs` file and on line 192, I found this clean up routine that looks like it tags a bunch of characters and cleans it up before passing back to the `SaveFileController.cs` to the `SaveStylesheet` method.

`private static readonly char[] CleanForXssChars = "*?(){}[];:%<>/\\|&'\"".ToCharArray();`

In Umbraco 7.12.1 the `SaveFileController.cs` and the `SaveStylesheet` method looks like this:

```csharp
    [HttpPost]
    public JsonResult SaveStylesheet(string filename, string oldName, string contents)
    {
        // sanitize input - stylesheet names have no extension
        filename = filename
            .Replace('\\', '/')
            .TrimStart('/')
            .EnsureEndsWith(".css");

        var svce = (FileService) Services.FileService;
        var stylesheet = svce.GetStylesheetByName(oldName);
        if (stylesheet == null)
            stylesheet = new Stylesheet(filename);
        else
            stylesheet.Path = filename;
        stylesheet.Content = contents;

        try
        {
            if (svce.ValidateStylesheet(stylesheet) == false)
                return Failed(ui.Text("speechBubbles", "cssErrorText"), ui.Text("speechBubbles", "cssErrorHeader"),
                                new FileSecurityException("File '" + filename + "' is not a valid stylesheet file."));

            svce.SaveStylesheet(stylesheet);
        }
        catch (Exception e)
        {
            return Failed(ui.Text("speechBubbles", "cssErrorText"), ui.Text("speechBubbles", "cssErrorHeader"), e);
        }

        return Success(ui.Text("speechBubbles", "cssSavedText"), ui.Text("speechBubbles", "cssSavedHeader"),
            new
            {
                path = DeepLink.GetTreePathFromFilePath(stylesheet.Path),
                name = stylesheet.Path,
                url = stylesheet.VirtualPath,
                contents = stylesheet.Content
            });
    }
```

Much smaller and looks like it is self contained.

That said, @UmbracoHQ, how do I fix this.

We have quite a few sub folders for our CSS files that I would like to edit with through the admin, which is the beauty of using Umbraco for this. I don't want to have to keep uploading files directly to the server if I need to make a quick CSS update to the site. That is just frustrating.

**Comment by createitcarlos** [comment]
I did a screencast to show what is going on.
[](https://drive.google.com/file/d/1igs3i98rHpyLeIcZt_DvLH44GJFdk39p/view?usp=sharing)

**Comment by nul800sebastiaan** [comment]
Hi @createitcarlos, thanks for the report. Sorry that we broke it, but unfortunately for you, it was for the greater good. The update to use `CleanForXSS` was needed for a security issue and we can't just have different rules for CSS folders, it would re-introduce the security issue. In general we would recommend editing CSS locally with an editor like VS or VS Code, committing them to source control and then deploying them.

Unfortunately we have no plans any more to work on v7 bugs as it is in maintenance mode. I can also not in good conscience encourage you to send us a pull request since we can't prioritize this before [v7 goes into "security only" mode (July 2021)](https://umbraco.com/blog/announcement-support-lts-and-eol-for-umbraco-cms-cloud-and-packages/).

As an alternative, maybe this package could work for you, but I have to warn that we didn't verify if this is a secure package to use, so you should give that some serious consideration: https://our.umbraco.com/packages/backoffice-extensions/umbraco-config-editor-manager/

I'm sorry I can't be of much more help here.

**Comment by createitcarlos** [comment]
Hey @nul800sebastiaan , 
Yeh that package is made for 8.   We are not quite ready for 8, which we know have been out or quite some time.  Which we have used for other project, but our main site is roughly 300+ nodes at this point and we can't upgrade quite yet.  
I know V7 is in maintenance mode.  If I were to do an update on our own local for the time being, would I just bypass the CleanForXSS.

Or yes we could do deployments directly to the server. 

I see in the /scripts/ (JS) "create" you have an option to create the folder via the menu, but the CSS section you can not.  

Thank you for responding.  If you have a quick idea on how to bypass it and we will only do it on our server for just the stylesheets, we would take responsibility for it. If not, it is understandable

**Comment by nul800sebastiaan** [comment]
Fair enough, I thought it was much older than that. Sorry, apart from a custom build of v7 I don't have a quick fix, you could look at the code of that package, v8 and v7 are not super different so it could be backported to v7, which would be much preferred so that you can still apply any future possible security updates to v7.
