### ISSUE TITLE
User invitation with caching server does not work

### ISSUE THREAD

**Issue by pguilmettenmedia** [umbraco/Umbraco-CMS#10270]
When the Umbraco instance is fronted by a caching server, invited users cannot complete the password form sent by email because of missing anti-forgery tokens cookies.

## Umbraco version

Umbraco 8.8.0

Reproduction
------------

### Bug summary

When the Umbraco instance is fronted by a caching server, invited users cannot complete the password form sent by email because of missing anti-forgery tokens cookies.

### Specifics

Umbraco version: 8.8.0 but this also happens on 8.13.0
Url: `umbraco/backoffice/UmbracoApi/Authentication/GetCurrentInvitedUser`
Browser: Chrome 90.0.4430.93
I also tried on Microsoft Edge and Mozilla Firefox.

Invited users cannot complete the password form because the `UMB-XSRF-TOKEN` and `UMB-XSRF-V` aren't set when `umbraco/backoffice/UmbracoApi/Authentication/GetCurrentInvitedUser` is called because Azure Front Door seems to return the cached version.

Azure Front Door looks at the `Cache-Control` header to determine if the response should be cached or not. For the `GetCurrentInvitedUser` request, the `Cache-Control` header is set to `no-cache`, but I don't know if this should be set to `no-cache, no-store` instead to make sure the request always reach the origin server so the cookies can be set by the `SetAngularAntiForgeryTokens` attribute.

### Steps to reproduce

- Setup a caching server in front of the Umbraco server (in my case it's Azure Front Door with caching enabled)
- Invite a user through the backoffice
- Click on the link in the email
-  Fill and submit the password form

### Expected result

User should now have his password set.

### Actual result

User cannot complete the password form because of missing anti-forgery tokens in the request. The user is stuck on the password form page and the submit button does nothing (it only shows an `X` in the button because the request failed).

**Comment by nul800sebastiaan** [comment]
Thanks @pguilmettenmedia, I know people have made Frontdoor work for them before, so it all can work just fine. I have had a little ask around and what I heard back is that this seems to be a configuration problem on the Frontdoor service. You might want to disable some WAF rules to get this to work, though I don't know which ones! 😅 

I would recommend you head on over to the forums at https://our.umbraco.com and ask follow up questions there! 👍

**Comment by pguilmettenmedia** [comment]
Thank you @nul800sebastiaan!

I created a post on the forums to see if someone can help me : https://our.umbraco.com/forum/using-umbraco-and-getting-started/106036-user-invitation-with-caching-server-azure-front-door-does-not-work
