### ISSUE TITLE
RebuildIndex failing with an Empty Queue in CloseStaleReaders()

### ISSUE THREAD

**Issue by oselly** [umbraco/Umbraco-CMS#10273]
Since upgrading from 8.2.2 to 8.12.2 we've been suffering with a lot of IndexRebuild failures due to the below error (seems to be the same issue as https://github.com/Shazwazza/Examine/issues/220:

`Failed to load resource: the server responded with a status of 409 (Could Not Rebuild)`

`Possibly unhandled rejection: {"errorMsg":"Failed to rebuild index","data":"The index could not be rebuilt at this time, most likely there is another thread currently writing to the index. Error: System.InvalidOperationException: Queue empty.\r\n   at System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)\r\n   at Examine.LuceneEngine.OpenReaderTracker.CloseStaleReaders(Directory dir, TimeSpan ts) in C:\\projects\\examine-qvx04\\src\\Examine\\LuceneEngine\\OpenReaderTracker.cs:line 56\r\n   at Examine.LuceneEngine.Providers.LuceneIndex.EnsureIndex(Boolean forceOverwrite) in C:\\projects\\examine-qvx04\\src\\Examine\\LuceneEngine\\Providers\\LuceneIndex.cs:line 437\r\n   at Examine.LuceneEngine.Providers.LuceneIndex.CreateIndex() in C:\\projects\\examine-qvx04\\src\\Examine\\LuceneEngine\\Providers\\LuceneIndex.cs:line 507\r\n   at Umbraco.Examine.IndexRebuilder.RebuildIndex(String indexName) in D:\\a\\1\\s\\src\\Umbraco.Examine\\IndexRebuilder.cs:line 43\r\n   at Umbraco.Web.Editors.ExamineManagementController.PostRebuildIndex(String indexName) in D:\\a\\1\\s\\src\\Umbraco.Web\\Editors\\ExamineManagementController.cs:line 148","status":409}`

We have a few custom indexes which we use to add page view count to allow us to display the most popular news articles etc but this problem happens on both our custom indexes and the default External/Internal/Member indexes.

This happens either when we programmatically call `IndexRebuilder.RebuildIndex` or using the built in functions within the BackOffice settings page.

I am seeing this issue on Umbraco version: 8.12.2 (We recently upgraded from 8.2.2 where we didn't experience any issues and these issues only started occurring the day after we upgraded). 

Typically it seems to be reproducible by loading up the CMS, idling for a few minutes and then clicking the rebuild index button although I've not tried on an empty installation yet.

In the same Umbraco 8.12.2 codebase I've tried downgrading the Examine package back to 1.0.1 (which it was previously using) instead of 1.1.0 (which it updated to as part of the umbraco upgrade) but that seems to have had no effect on solving the issue

**Comment by Shazwazza** [comment]
Pretty sure that's this issue in Examine https://github.com/Shazwazza/Examine/issues/220

**Comment by Shazwazza** [comment]
Should be fixed with Examine 1.2.1 https://github.com/Shazwazza/Examine/releases/tag/v1.2.1
