### ISSUE TITLE
Version conflict on NuGet with the latest (8.13.0) and System.Text.Encoding.CodePages

### ISSUE THREAD

**Issue by mzajkowski** [umbraco/Umbraco-CMS#10282]
While upgrading one of the projects from 8.10.2 into the latest 8.13.0 via NuGet, we're experiencing the issue with one of the dependencies (System.Text.Encoding.CodePages - https://www.nuget.org/packages/System.Text.Encoding.CodePages/) not matching the provided boundaries in the lib (screenshot).

![image](https://user-images.githubusercontent.com/11617260/118646135-16529400-b7e0-11eb-9007-b6f47da8f4c9.png)

Is it intentional or it can be extended to support the latest versions of the library too?
It might be a case that library is/was referenced from another lib outside of the UmbracoCms.Web.dll, but as it's getting added there it might be good to either confirm it or extend the boundaries maybe?

## Umbraco version

I am seeing this issue on Umbraco version: 

8.13.0

Reproduction
------------

If you're filing a bug, please describe how to reproduce it. Include as much
relevant information as possible, such as:

### Steps to reproduce

Update Umbraco package via NuGet from 8.10.2 to the latest - 8.13.0.

### Expected result

Update completed. All good.

### Actual result

Update failed - dependency problem.

**Comment by nul800sebastiaan** [comment]
Unfortunately this happens (quite unpredictably) to some people. The discussion in PR contains some helpful comments to help fix it up! https://github.com/umbraco/Umbraco-CMS/pull/10000
