### ISSUE TITLE
8.14-RC - Some tours can't be completed

### ISSUE THREAD

**Issue by nul800sebastiaan** [umbraco/Umbraco-CMS#10298]
### Which Umbraco version are you using?

8.14.0-rc

### Bug summary

In some tours you get stuck because the field you need to update doesn't get highlighted.

### Steps to reproduce

- On "Data structure" Tour, Document types, on step 24 when it says to add content, it doesn't allow people to actually add the content and if you click next, it goes to last step. ![image](https://user-images.githubusercontent.com/304656/118965151-a3c0f000-b968-11eb-831a-d8322ca6e429.png)

Right now that's the only one I can remember but I'll run through I few more since I saw it somewhere else as well.

---
_This item has been added to our backlog [AB#12107](https://dev.azure.com/umbraco/243e7927-03b2-44e2-908f-d4ac7ea5daaa/_workitems/edit/12107)_

**Comment by warrenbuckley** [comment]
This seems to come from Starter Kit package that overrides/add extra tours and not from the core CMS stuff we ship

**Comment by warrenbuckley** [comment]
@nul800sebastiaan I can't reproduce this anymore with latest in V8/dev and with the Starter Kit installed via the installer flow.
Can you re-test & verify this is no longer a problem please to ensure its now been fixed by something else.

**Comment by nul800sebastiaan** [comment]
Can't repro either, all good.
