### ISSUE TITLE
Uploading SVG results in a "file"

### ISSUE THREAD

**Issue by soreng** [umbraco/Umbraco-CMS#10295]
### Which Umbraco version are you using?

v9-beta002

### Bug summary

When uploading an SVG to the media lib, it creates a media of type "File", instead of the "Vector Graphics (SVG)" that is created by the installer.

### Steps to reproduce

Upload https://upload.wikimedia.org/wikipedia/commons/4/4f/SVG_Logo.svg to the media section

### Expected result / actual result

The resulting media is of type "File", expected it to be of type "Vector Graphics (SVG)"

**Comment by nul800sebastiaan** [comment]
Thanks @soreng, looks like we're a bit out of sync between the v8 and v9 branch, doing a merge should fix this and https://github.com/umbraco/Umbraco-CMS/issues/10289 as well. 🤞

**Comment by bergmania** [comment]
I can repro, even after the last merge.. Ill look into it..

**Comment by warrenbuckley** [comment]
Fixed in this PR for V9
https://github.com/umbraco/Umbraco-CMS/pull/10320
