### ISSUE TITLE
8.14-RC - A few areas where focus lock doesn't work properly

### ISSUE THREAD

**Issue by nul800sebastiaan** [umbraco/Umbraco-CMS#10297]
### Which Umbraco version are you using?

8.14.0-rc

### Bug summary

When performing some actions in the backoffice you get stuck, you can not click anywhere and have to refresh the whole backoffice. 

### Steps to reproduce

The identified features are:

- Adding an image to the grid allows you to select an image but then you can't do anything else after that
- Using the "Insert" button in Template, Views, Partial Views and Partial View Macros
- Updating granular permissions on user groups

A known workaround for now is to use keyboard shortcuts (CTRL+S) to save what you're working on but can't use the backoffice any more, then at least you don't lose your progress.

---
_This item has been added to our backlog [AB#12067](https://dev.azure.com/umbraco/243e7927-03b2-44e2-908f-d4ac7ea5daaa/_workitems/edit/12067)_

**Comment by nielslyngsoe** [comment]
Issue originate from this PR: https://github.com/umbraco/Umbraco-CMS/pull/8522

**Comment by nul800sebastiaan** [comment]
Fixed in https://github.com/umbraco/Umbraco-CMS/pull/10331
