### ISSUE TITLE
Missing Culture Bug

### ISSUE THREAD

**Issue by Ric-Carey** [umbraco/Umbraco-CMS#10296]
### Which Umbraco version are you using?

8.12.0

### Bug summary

Hello,

Bit of a strange one to report – its actually been raised on https://our.umbraco.com/forum/using-umbraco-and-getting-started/95684-missing-culture-bug-in-back-office 

But we have replicated it in a more specific way. If you have culture and hostnames set up on the website. When you are browsing the content it will work fine. But if you then search for a node the page will load from e.g /umbraco/#/content/content/edit/2109  - which causes an error to be shown to the user and the list view not to load:

`System.InvalidOperationException: Missing culture in mapping options. at Umbraco.Web.Models.Mapping.ContentMapDefinition.GetName(IContent source, MapperContext context) in D:\a\1\s\src\Umbraco.Web\Models\Mapping\ContentMapDefinition.cs:line 224 at Umbraco.Web.Models.Mapping.ContentMapDefinition.Map(IContent source, ContentItemBasic`1 target, MapperContext context) in D:\a\1\s\src\Umbraco.Web\Models\Mapping\ContentMapDefinition.cs:line 144 at Umbraco.Core.Mapping.UmbracoMapper.<>c__DisplayClass8_0`2.<Define>b__1(Object source, Object target, MapperContext context) in D:\a\1\s\src\Umbraco.Core\Mapping\UmbracoMapper.cs:line 106 at Umbraco.Core.Mapping.UmbracoMapper.Map[TTarget](Object source, Type sourceType, MapperContext context) in D:\a\1\s\src\Umbraco.Core\Mapping\UmbracoMapper.cs:line 206 at Umbraco.Core.Mapping.UmbracoMapper.Map[TSource,TTarget](TSource source, MapperContext context) in D:\a\1\s\src\Umbraco.Core\Mapping\UmbracoMapper.cs:line 190 at Umbraco.Core.Mapping.UmbracoMapper.Map[TSource,TTarget](TSource source, Action`1 f) in D:\a\1\s\src\Umbraco.Core\Mapping\UmbracoMapper.cs:line 178 at Umbraco.Web.Editors.ContentController.<>c__DisplayClass27_0.<GetChildren>b__0(IContent content) in D:\a\1\s\src\Umbraco.Web\Editors\ContentController.cs:line 531 at System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext()`

If you refresh the page – ctrl f5 – then the url will return and append ?mculture=en-GB on which then the page works. The way Umbraco’s back office has been coded means that when you don’t have that querystring in the url – and you browse around, all the pages will start failing – likewise when you refresh and it appends the culture URL it will then start working on all pages again. 

My suggestion is either – return the querystring version of the url that you are currently in – in search results. Or have some kind of way of identifying that the querystring isn’t present and redirect the user back.

Hope that makes sense?

Cheers
Ric 

### Steps to reproduce

See above

**Comment by nul800sebastiaan** [comment]
Thanks @Ric-Carey, this was fixed in 8.13.0: https://github.com/umbraco/Umbraco-CMS/pull/9865
Give the upgrade a go! 👍
