### ISSUE TITLE
8.14-RC - Media Picker v3 displays alias for crops instead of the label for the crop

### ISSUE THREAD

**Issue by nzdev** [umbraco/Umbraco-CMS#10306]
### Which Umbraco version are you using?

8.14-RC

### Bug summary

Media Picker v3 displays alias for crops instead of the label for the crop.
![image](https://user-images.githubusercontent.com/834725/119121023-0ad1c800-ba81-11eb-829f-f177661343c5.png)

### Steps to reproduce

Set image crops on a media picker v3 as per screenshot
![image](https://user-images.githubusercontent.com/834725/119121115-276e0000-ba81-11eb-8832-61dc2b653634.png)
Select an image with the media picker

### Expected result / actual result

Label for crop displayed for each crop

---
_This item has been added to our backlog [AB#12104](https://dev.azure.com/umbraco/243e7927-03b2-44e2-908f-d4ac7ea5daaa/_workitems/edit/12104)_

**Comment by nul800sebastiaan** [comment]
Thanks @nzdev! Fixed in https://github.com/umbraco/Umbraco-CMS/pull/10326
