### ISSUE TITLE
(v9-beta002) Using content templates does not work

### ISSUE THREAD

**Issue by jonat123** [umbraco/Umbraco-CMS#10300]
### Which Umbraco version are you using?

(v9-beta002)

### Bug summary

After creating a Content template in the backoffice, and trying to create a new content node based on the content template, it fails and throws a 404:

_Request error: The URL returned a 404 (not found):
/umbraco/backoffice/umbracoapi/content/GetEmpty_ 

And the node is not created and the content section keeps loading.

### Specifics

Looking in the browser console, it is possible to see an angular error:
![image](https://user-images.githubusercontent.com/54025331/118975229-14b9d500-b974-11eb-996a-1585c7d30301.png)
****

### Steps to reproduce

1. Follow documentation here: https://our.umbraco.com/documentation/Getting-Started/Backoffice/Content-Templates/ And create a content template

2. Try and create a node based on the content template.

3.  Click save and it fails with an 404 error message.

### Expected result / actual result

Expected a new content node based on my content template to be created.

Instead, it ends up failing.

**Comment by nathanwoulfe** [comment]
Thanks @jonat123, I was able to reproduce, and realised the fix was a small one, so it's now in #10302 and ready to merge :)

**Comment by bergmania** [comment]
Will be fixed in beta003
