### ISSUE TITLE
Namespace errors

### ISSUE THREAD

**Issue by deanleigh** [umbraco/Umbraco-CMS#10316]
### Which Umbraco version are you using?

9

### Bug summary

Creating a project in Visual Studio in V9 causes an error on build if the project name contains illegal characters such as spaces. underscores etc…

### Steps to reproduce

Creating a project in Visual Studio in V9 from the VS Template
Name it with spaces
Build

### Expected result / actual result

Build error

**Comment by bergmania** [comment]
Should be fixed by: https://github.com/umbraco/Umbraco-CMS/pull/10314
