### ISSUE TITLE
NetCore: Health-Check links are broken

### ISSUE THREAD

**Issue by idseefeld** [umbraco/Umbraco-CMS#10312]
### Which Umbraco version are you using?

v9.0.0-beta003

### Bug summary

There is a wrong path segment e.g. in:
https://github.com/umbraco/UmbracoCMSDocs/blob/main/Articles/HealthChecks/Guides/ExcessiveHeaders.md

which needs to be:

https://github.com/umbraco/UmbracoCMSDocs/blob/main/Articles/Health-Check/Guides/ExcessiveHeaders.md

In detail: `.../Health-Check/...` instead of `.../HealthChecks/...`

### Steps to reproduce

Open back office > Settings > Health Check > Security and click on `Read more` buttons

**Comment by bergmania** [comment]
Hi @idseefeld 

Thanks for reporting.. Ill fix up.. Actually the links should now point to our like https://our.umbraco.com/documentation/Extending/Health-Check/Guides/ExcessiveHeaders

**Comment by idseefeld** [comment]
👍 😁

**Comment by bergmania** [comment]
All healthcheck links are now updated and redirects to our.
