### ISSUE TITLE
8.14-RC - Slider no longer focus on handles

### ISSUE THREAD

**Issue by bjarnef** [umbraco/Umbraco-CMS#10318]
### Which Umbraco version are you using?

8.14.0-RC

### Bug summary

It seems the slider using noUiSlider no longer focus on each handle when using keyboard.
Instead it focus on the slider bar, but not the handles itself. So when using range it isn't clear which handle is active.
It seem this may have changed with the Media Picker v3 changes here: https://github.com/umbraco/Umbraco-CMS/pull/9461

### Specifics

![LKPIA9nGT6](https://user-images.githubusercontent.com/2919859/119385432-68a32180-bcc6-11eb-8424-35fb621efddf.gif)

### Steps to reproduce

Add a property to a document type using Slider data type and with range enabled, e.g. the following configuration:

![image](https://user-images.githubusercontent.com/2919859/119385541-8c666780-bcc6-11eb-9fcc-0983b4a29f41.png)

### Expected result / actual result

I would expect each handle to get focus and clearly visible which handle being active.
The accessibility haven't been improved with these changes.
Previous the handles got focus like in the gif in this PR: https://github.com/umbraco/Umbraco-CMS/pull/8074 - now it is just the slider itself which has a slightly focus with a change in background color and border color, but isn't very useful - especially not with a range slider.

![2020-05-07_11-23-59](https://user-images.githubusercontent.com/2919859/81279620-abf90680-9057-11ea-862f-15486de374e6.gif)

---
_This item has been added to our backlog [AB#12103](https://dev.azure.com/umbraco/243e7927-03b2-44e2-908f-d4ac7ea5daaa/_workitems/edit/12103)_

**Comment by bjarnef** [comment]
@nielslyngsoe @madsrasmussen why was the outline removed from in handles in https://github.com/umbraco/Umbraco-CMS/commit/ee07a87a551724851ab2a67147d3c4f2ea01b2e5 ? 🤔

**Comment by nul800sebastiaan** [comment]
Thanks @bjarnef! Guess the answer was: you're right! 🙈  Fixed in https://github.com/umbraco/Umbraco-CMS/pull/10324
