### ISSUE TITLE
Can't Add Property to Media Type

### ISSUE THREAD

**Issue by 0Neji** [umbraco/Umbraco-CMS#10317]
### Which Umbraco version are you using?

8.10.1

### Bug summary

I'm attempting to add a new property to the `Image` media type. Pretty simple, just want to add a `Description` property I can use for alt text without having to set this up every time.

I've done a fair bit with data types and content types so my code *feels* right but clearly I'm either missing something, or there's something wrong with the saving of media types.

### Specifics

Hi,

I'm attempting to add a new property to the `Image` media type. Pretty simple, just want to add a `Description` property I can use for alt text without having to set this up every time.

I've done a fair bit with data types and content types so my code *feels* right but clearly I'm either missing something, or there's something wrong with the saving of media types.

My code is as follows:

```csharp
    using System.Linq;
    using Example.Core.Services.Interfaces;
    using Umbraco.Core.Models;
    using Umbraco.Core.Services;

    namespace Example.Core.Services
    {
        public class ConstructMediaTypeService : IConstructMediaTypeService
        {
            #region Services

            private readonly IMediaTypeService _umbracoMediaTypeService;

            private readonly IDataTypeService _dataTypeService;

            #endregion

            #region Constructors

            public ConstructMediaTypeService(IMediaTypeService mediaTypeService, IDataTypeService dataTypeService)
            {
                _umbracoMediaTypeService = mediaTypeService;

                _dataTypeService = dataTypeService;
            }

            #endregion

            #region Initialisation Methods

            public void InitialiseMediaTypes()
            {
                InitialiseImageMediaType();
            }

            private void InitialiseImageMediaType()
            {
                IMediaType imageType = _umbracoMediaTypeService.Get("Image");

                PropertyGroup imagePropertyGroup = imageType.PropertyGroups.First(x => x.Name == "Image");

                IDataType dataType = _dataTypeService.GetDataType("Textstring");

                PropertyType descriptionPropertyType = new PropertyType(dataType);

                descriptionPropertyType.Id = 1249238749;
                descriptionPropertyType.Name = "Description2";
                descriptionPropertyType.Alias = "description2";

                imageType.AddPropertyType(descriptionPropertyType, "Image");

                _umbracoMediaTypeService.Save(imageType);
            }

            #endregion
        }
    }
```

So, kicks on on startup. As I step through the code it all looks correct, I can see the `Image` property group gets assigned the new property (please see image below). There are no errors thrown but the property just doesn't display on the media type.

![capture](https://user-images.githubusercontent.com/4700480/119368342-ce81b000-bcaa-11eb-9000-31a8de3b1b6d.png)

Thanks,

Ben

### Steps to reproduce

- Please see code in "Specifics".
- Once set up, run the code in debug - it should get hit on startup.
- If you debug you'll see that it gets hit and appears to add the property in code.
- Once the code has run, view the `Image` media type in Umbraco and you'll see that the `Description` property isn't present.

### Expected result / actual result

The code above appears to add the new property to the media type but once saved and in Umbraco, it isn't present.

**Comment by nul800sebastiaan** [comment]
Hi @0Neji! Well.. tricky one, but Umbraco doesn't appreciate you inventing your own identifier, so just don't specify that one. Here's my full code sample that works:

```csharp
using Umbraco.Core;
using Umbraco.Core.Composing;
using Umbraco.Core.Models;
using Umbraco.Core.Services;

namespace Umbraco812Solution.Core
{
    [RuntimeLevel(MinLevel = RuntimeLevel.Run)]
    public class ApplicationComposer : ComponentComposer<ApplicationComponent>
    { }

    public class ApplicationComponent : IComponent
    {
        private readonly IMediaTypeService _umbracoMediaTypeService;

        private readonly IDataTypeService _dataTypeService;

        public ApplicationComponent(IMediaTypeService mediaTypeService, IDataTypeService dataTypeService)
        {
            _umbracoMediaTypeService = mediaTypeService;

            _dataTypeService = dataTypeService;
        }


        private void InitialiseImageMediaType()
        {
            var imageType = _umbracoMediaTypeService.Get("Image");
            var dataType = _dataTypeService.GetDataType("Textstring");
            var descriptionPropertyType = new PropertyType(dataType)
            {
                Name = "Description2",
                Alias = "description2"
            };
            
            imageType.AddPropertyType(descriptionPropertyType, "Image");

            _umbracoMediaTypeService.Save(imageType);
        }


        public void Initialize()
        {
            InitialiseImageMediaType();
        }

        public void Terminate()
        { }
    }
}
```

One thing to note: you might have to add `[RuntimeLevel(MinLevel = RuntimeLevel.Run)]` to your `IComponent` as well to make sure all the contexts are ready.
