### ISSUE TITLE
8.14-RC: Rename Media Picker V3 to Media Picker

### ISSUE THREAD

**Issue by hemraker** [umbraco/Umbraco-CMS#10321]
In the releases candidate for Umbraco 8.14 the new Media Picker (#9461) is listed as **_Media Picker v3_**. I find this slightly confusing as there are no v1 and v2, just a Media Picker. 
![image](https://user-images.githubusercontent.com/3663619/119456781-4e575b00-bd3b-11eb-800f-77d808851778.png)
![image](https://user-images.githubusercontent.com/3663619/119457432-f9681480-bd3b-11eb-9bb5-bfa7ae86c6bc.png)

I don't see a case where one would not use the new Media Picker going forward (it's too good 😉), so I would suggest naming it **_Media Picker_**. The "old" Media Picker could be named **_Media Picker (Legacy)_** or **_Media Picker (Old)_** and still be available for backwards compatibility until it's deprecated.

---
_This item has been added to our backlog [AB#12109](https://dev.azure.com/umbraco/243e7927-03b2-44e2-908f-d4ac7ea5daaa/_workitems/edit/12109)_

**Comment by rasmusjp** [comment]
Maybe following the same naming convention as in v7 when the new pickers were introduced? The old ones were prefixed with `(Obsolete)` e.g. the media picker was renamed to `(Obsolete) Media Picker` and it was marked as deprecated, so you could only use it on an existing project were it already was in use or if you enabled oblosete editors in `umbracoSettings.config`

**Comment by hemraker** [comment]
@rasmusjp I like it 😊

**Comment by warrenbuckley** [comment]
PR for review is here  - https://github.com/umbraco/Umbraco-CMS/pull/10332

**Comment by nul800sebastiaan** [comment]
Fixed in https://github.com/umbraco/Umbraco-CMS/pull/10332
