### ISSUE TITLE
List view not showing custom icons

### ISSUE THREAD

**Issue by skttl** [umbraco/Umbraco-CMS#10339]
### Which Umbraco version are you using?

8.13.0

### Bug summary

When using custom icons from /App_Plugins/*/backoffice/icons, they don't show up in the list view.

![image](https://user-images.githubusercontent.com/3726467/119813820-0591d480-beea-11eb-9c8c-31741d5ef3b2.png)

### Steps to reproduce

Add some icons in App_Plugins/*/backoffice/icons, and select them on a doctype used in a list view.

Open the list view and see the document type icon missing.

### Expected result / actual result

Expected the icon to show, just like the default icons does.

**Comment by skttl** [comment]
FYI, the grid view does the same :)

**Comment by bjarnef** [comment]
Fixes in https://github.com/umbraco/Umbraco-CMS/pull/10345
