### ISSUE TITLE
Media Picker 3 doesn't save minimum amount filed

### ISSUE THREAD

**Issue by TwoMoreThings** [umbraco/Umbraco-CMS#10337]
### Which Umbraco version are you using?

V9 Beta003

### Bug summary

When you enter a value for the minimum amount of media items (I entered 1) and then click Save, the value disappears and just the placeholder 0 shows

### Specifics

Running in Chrome via IIS Express from Visual Studio in debug mode

### Steps to reproduce

Create a new dataype using the media picker 3 editor and set a minimum amount and click save

https://user-images.githubusercontent.com/13945979/119721873-92de1600-be63-11eb-89c4-e54b3a7819a3.mp4

### Expected result / actual result

I expect the value I enter to be saved, instead the value is cleared

**Comment by TwoMoreThings** [comment]
This is the result when trying to select media
![requires 0 more](https://user-images.githubusercontent.com/13945979/119722448-3b8c7580-be64-11eb-9a4c-2862d909e51b.png)

**Comment by nul800sebastiaan** [comment]
Thanks Tom! We're working on it 👍 This duplicates issue https://github.com/umbraco/Umbraco-CMS/issues/10289
