### ISSUE TITLE
Document type child nodes not showing custom icons

### ISSUE THREAD

**Issue by skttl** [umbraco/Umbraco-CMS#10340]
### Which Umbraco version are you using?

8.13.0

### Bug summary

When using custom icons from /App_Plugins/*/backoffice/icons, they don't show up in the document type editor, when showing allowed child node types.

![image](https://user-images.githubusercontent.com/3726467/119814049-44278f00-beea-11eb-87a8-e185fa01e718.png)

### Steps to reproduce

Add some icons in App_Plugins/*/backoffice/icons, and select them on a doctype used as a child node for another document type.

Open the parent document type, and see the icon is missing on the child types.

### Expected result / actual result

Expected the icon to show, just like the default icons does.

**Comment by bjarnef** [comment]
PR submitted: https://github.com/umbraco/Umbraco-CMS/pull/10344 🔥

**Comment by nathanwoulfe** [comment]
Fixed in #10344
