### ISSUE TITLE
Umbraco backend slow even after using high cpu

### ISSUE THREAD

**Issue by dharmendrasingh88** [umbraco/Umbraco-CMS#10359]
### Which Umbraco version are you using?

8.13

### Bug summary

I have used a high configuration windows server.But umbraco backend rendering very slow

### Steps to reproduce

Just host on server and login in backend add some properties in pages and you can see

**Comment by nul800sebastiaan** [comment]
Hi there - this sounds like an excellent question for the forums where our friendly community can help you find the best solution for your requirements. 
Make sure to head on over to https://our.umbraco.com and ask follow up questions there! 👍
