### ISSUE TITLE
Settings Model is not updated, if template is changed after content is created

### ISSUE THREAD

**Issue by casperclifforth** [umbraco/Umbraco-CMS#10373]
### Which Umbraco version are you using?

8.12.2

### Bug summary

We have created some initial content using Block Lists and custom Settings Models.

Afterwards we needed to change the Setting Model properties, so we removed and added new properties.

Using the editor we could change the values on the existing Block Model content and their associated Settings, but we found that the changes on the Settings Model was not being being effectuated when visiting the existing content.

To make the changes to the Settings Model work we had to delete the whole existing Block List entries and create them again and set the new property. Only after that the content was updated.

We observed that the underlying data in SQL table [umbracoPropertyData] was not updated for the Settings. When the contentTypeKey for SettingsData changed, the data was not updated.

First when the content was deleted from the Block List and recreated, the data in SQL was updated.

### Steps to reproduce

Create content using Block List and Block Content. Add values to Settings Pane.
Update the Settings Model; remove or add properties or change it to a new model.
Edit the Settings content data.
Try to output the Content item and observe the missing content.

### Expected result / actual result

Expected result where the content has been created **after** the Settings Model was changed:

`
            {
              "isContentBlock": true,
              "alias": "blockContent",
              "value": [
                {
                  "type": "teaserModuleBlockType",
                  "value": [
                    {
                      "alias": "header",
                      "value": "Working"
                    },
                    {
                      "alias": "paragraph",
                      "value": "Working"
                    },
                    {
                      "isContentBlock": true,
                      "alias": "button"
                    }
                  ],
                  "settings": [
                    {
                      "alias": "textColor",
                      "value": "50,76,89"
                    },
                    {
                      "alias": "gradientColor",
                      "value": "0,0,0"
                    },
                    {
                      "alias": "backgroundColor",
                      "value": "153,0,0"
                    }
                  ]
                }
              ]
            }
`

Actual result. Content has been created before model was changed. 
Not working content - notice the missing settings property:
`
            {
              "isContentBlock": true,
              "alias": "blockContent",
              "value": [
                {
                  "type": "teaserModuleBlockType",
                  "value": [
                    {
                      "alias": "header",
                      "value": "Not working"
                    },
                    {
                      "alias": "paragraph",
                      "value": "Not working"
                    },
                    {
                      "isContentBlock": true,
                      "alias": "button"
                    }
                  ]
                }
              ]
            }
`

---
_This item has been added to our backlog [AB#13607](https://dev.azure.com/umbraco/243e7927-03b2-44e2-908f-d4ac7ea5daaa/_workitems/edit/13607)_

**Comment by nul800sebastiaan** [comment]
Thanks @casperclifforth - this is correct. For performance reasons we don't want to do this automatically because we don't know how much content is in your site that would need an update. It could be very easy but often this will be a large operation we don't want to run while you're saving your document type.

Specifically, for the Block List editor this is an extra heavy operation as we'd need to deserialize and (re)serialize all the data, which requires quite a bit of processing.

So we do this progressively, when you load a content node and update it, the new settings will be added. We recommend you code your frontend so that it takes into account the fact that the settings might be null.

Note: for the same reasons as above, this behavior is the same for any updates to any datatypes you make, we never update the content that has already been created with that datatype.

You are of course welcome to create a [`DataTypeService.Saved`](https://our.umbraco.com/documentation/reference/events/datatypeservice-events) handler that will do the updates to the content.

**Comment by mastrup** [comment]
Just tested this on 8.15.0.
As @nul800sebastiaan says, the specific block editor is updated with the new values and works just fine afterwards.
In your view you just have to take into account that the values might be null.

But if you for example change the doctype used for settings on a specific Block Editor, the block editor wil stop working no matter how many null-checks you set up. I believe that the issue (#10031) raised by @FransdeJong matches this.

**Comment by nul800sebastiaan** [comment]
Fixed in https://github.com/umbraco/Umbraco-CMS/pull/10993

**Comment by RBerntsen** [comment]
> Fixed in #10993

Awesome, thanks!
