### ISSUE TITLE
8.13 - Non-variant properties are editable in non default language

### ISSUE THREAD

**Issue by dawoe** [umbraco/Umbraco-CMS#10379]
### Which Umbraco version are you using?

8.13

### Bug summary

We have a doctype that is set to allow vary by culture. Some properties on the doctype don't vary by culture.
In 8.12 and earlier these properties were disabled in the non default languages when editing content. A editor also saw from which language it was inherited.

In 8.13 and onwards these properties are editable in the non default language and there is no indication that you will change it for all languages. This is very confusing for editors. To make it even worse when they work in split view they don't see the change reflected in both languages. Only after saving.

### Specifics

This can be tested on a blank Umbraco install or with the default starter kit installed.

### Steps to reproduce

- Configure one or multiple extra languages.
- Create a doctype and set it to allow at root and vary by culture
- Add a media picker property and disable allow vary by culture
- Add a text string property and allow vary by culture

Create a content item in english for this and fill both properties.
Create a content item in another language. 

#### Expected

The property that does not allow vary by culture is disabled like in 8.12.3

![variant-8 12 3](https://user-images.githubusercontent.com/1193822/120616726-bf90bf80-c459-11eb-8f1c-b686e7eed428.jpg)

#### Actual
No indication that property should managed in the default language. Property can be edited

![variant-8 13](https://user-images.githubusercontent.com/1193822/120616841-da633400-c459-11eb-8230-e4251ba9487e.jpg)

**Comment by dawoe** [comment]
Seems it is fixed again in 8.14

**Comment by nul800sebastiaan** [comment]
Probably already fixed in 8.13.1 as well? Not sure what version you're on 😅 

Can't repro in 8.13.1 anyway, so should be all good.

![image](https://user-images.githubusercontent.com/304656/120646741-1c9c6d80-c47a-11eb-814a-5b8ab926888a.png)

**Comment by dawoe** [comment]
Could reproduce it on 8.13 after I saw somebody posted it on our
