### ISSUE TITLE
Examine ISearchResults.Skip() always returning empty

### ISSUE THREAD

**Issue by jattwood** [umbraco/Umbraco-CMS#10377]
### Which Umbraco version are you using?

8.13.0

### Bug summary

When implementing paging on ISearchResults by using the Skip() method, the IEnumerable<ISearchResult> always returns empty/null even when the ISearchResults count is positive.

Removing the skip method successfully returns content.

This has been working on all previous versions, paging via skip() now fails in U 8.13.0. 

### Specifics

Consider this snippit: 
```
var searcher = index.GetSearcher();
            var criteria = searcher.CreateQuery(IndexTypes.Content, BooleanOperation.And);

            var examineQuery = criteria.ManagedQuery(searchModel.Keywords).And().GroupedOr(new[] { "__NodeTypeAlias" }, new[] { "article", "experience", "privilege", "brandPartner", "publisher", "contributor" });
            examineQuery.OrderByDescending(new SortableField[] { new SortableField("date") }); 
            int pageIndex = searchModel.CurrentPage - 1;
            int pageSize = searchModel.ItemsPerPage;
            ISearchResults searchResult = examineQuery.Execute(maxResults: pageSize * (pageIndex + 1));
            IEnumerable<ISearchResult> pagedResults = searchResult.Skip(pageIndex * pageSize);
```

### Steps to reproduce

Using umbraco examine search that uses pagination via the Skip() method, the results set will always be empty.

### Expected result / actual result

Expected result is that the search results would return the content in the index at the point specified in the skip() method.

**Comment by Shazwazza** [comment]
If this is a bug, it's not an Umbraco bug. this is Examine's code. There are tests in Examine covering Skip: 
https://github.com/Shazwazza/Examine/blob/dev/src/Examine.Test/Search/FluentApiTests.cs#L2072
https://github.com/Shazwazza/Examine/blob/dev/src/Examine.Test/Search/FluentApiTests.cs#L2109
https://github.com/Shazwazza/Examine/blob/dev/src/Examine.Test/Search/FluentApiTests.cs#L1102

If you can simplify and provide steps to reproduce, please report on the https://github.com/Shazwazza/Examine issue tracker.

**Comment by jattwood** [comment]
Ok will do, something is up with Skip(). I'll try another simplified example and post on Examine. Thanks for the reply. Cheers

**Comment by Shazwazza** [comment]
Thanks. I've also added 2 other tests: 

Paging_With_Max_Results
https://github.com/Shazwazza/Examine/blob/dev/src/Examine.Test/Search/FluentApiTests.cs#L2109

Paging_With_Skip_Take (btw, SkipTake is new in the latest Examine)
https://github.com/Shazwazza/Examine/blob/dev/src/Examine.Test/Search/FluentApiTests.cs#L2169

**Comment by jattwood** [comment]
Interesting. I upgraded Umbraco to 8.14 which ships with Examine 1.2.0 I believe. Skip() still returns 0 count of IEnumerable<ISearchResult> with ISearchResults > 0 however, using SkipTake(x) I am able to get the expected result.

Not sure what’s up as I am just using the normal Umbraco External Index and this was working previously.

I’ll post this on Examine. Thanks for your valuable time Shannon!

Jamie
