### ISSUE TITLE
Install Package containing Document Types Fails if using SQL Server Compact

### ISSUE THREAD

**Issue by uSkinned** [umbraco/Umbraco-CMS#10381]
### Which Umbraco version are you using?

Umbraco 8.14.0

### Bug summary

This issue only occurs when using SQL Server Compact.

### Steps to reproduce

If you attempt to install a package containing document types, records will be inserted into table cmsPropertyTypeGroup.

This table now contains 4 new records relating to the new Media Picker. IDs of these new Media Types are 52,53,54,55

If you install a package you will get error 'A duplicate value cannot be inserted into a unique index.' error on the id column.

For some reason which I cannot figure out SQL Server Compact does not set the identity seed for the ID column to start at ID 56 where as SQL Server does not have this issue.

If you run the following SQL command before attempting to install a package containing document types you will not get the issue and the package will install successfully:

ALTER TABLE [cmsPropertyTypeGroup] ALTER COLUMN [Id] IDENTITY (56,1)

---
_This item has been added to our backlog [AB#12326](https://dev.azure.com/umbraco/243e7927-03b2-44e2-908f-d4ac7ea5daaa/_workitems/edit/12326)_

**Comment by sotirisf** [comment]
Does the ALTER TABLE command have any adverse effect if ran on SQL Server?

**Comment by uSkinned** [comment]
I havent tested this however it shouldnt have any adverse effect.

**Comment by emma-hq** [comment]
Hey @uSkinned 

Thanks for reporting this one. We'll take a look and let you know our thoughts.

Emma

**Comment by emma-hq** [comment]
Hey @uSkinned 

We'll take a look at this at HQ. Thanks again for bringing it to our attention :)

Emma

**Comment by Xiliath** [comment]
> Great, getting a lot of users not paying attention to our reference to Umbraco Compatibility and trying to install against 8.14.0. Pointing them at the workaround however not great for novice users so would be awesome to get this fixed as soon as possible.
> 
> Cheers,
> 
> Marc

You are getting these reports because those users (including me) are trying to install against Umbraco Cloud and we don't have any version options there (as far as I know).

**Comment by uSkinned** [comment]
Just in case anyone else comes across this. My original fix does work if you run the query using CompactView which can be downloaded from here:

https://sourceforge.net/projects/compactview/

The command you need to run is:

ALTER TABLE [cmsPropertyTypeGroup] ALTER COLUMN [Id] IDENTITY (56,1)

**Comment by warrenbuckley** [comment]
Fixed in this PR by Nikolaj https://github.com/umbraco/Umbraco-CMS/pull/10603
Due for next release 8.16
