### ISSUE TITLE
v9: Members created with built-in macros not approved programmatically

### ISSUE THREAD

**Issue by Jay-umbr** [umbraco/Umbraco-CMS#10392]
### Which Umbraco version are you using?

v9

### Bug summary

We have a tutorial on how to use built in snippets to implement simple login and signup functionality.
https://our.umbraco.com/documentation/Tutorials/Members-Registration-And-Logins/

It works almost 100% the same as in v8, except in v9 the Register partial does not seem to Approve the member automatically. It does in v8.

### Specifics

Since the member needs to be manually approved, they are not able to login after registration and signing out. The workflow is a bit odd.
-when registered, system logs the member in automatically. They will be logged in despite not being approved
-if they log out they cannot log in again, as they are not approved

### Steps to reproduce

Please follow this tutorial
https://our.umbraco.com/documentation/Tutorials/Members-Registration-And-Logins/
I recommend going through with the logged in status partial view to verify sign in issues with new members.

### Expected result / actual result

new users made through built in macros are able to sign in right away, and are approved in the backoffice (like in v8)

**Comment by emma-hq** [comment]
Hey @Jay-umbr 

Thanks for this one too! It's already been labelled so it's heading to the right place. We'll let you know what we come up with

Emma
