### ISSUE TITLE
v9: IsHelpers template methods not working correctly

### ISSUE THREAD

**Issue by Jay-umbr** [umbraco/Umbraco-CMS#10391]
### Which Umbraco version are you using?

v9

### Bug summary

When verifying https://our.umbraco.com/Documentation/Reference/Querying/IPublishedContent/IsHelpers/ against v9 I noticed these two methods:

IsAllowedTemplate(int templateId)
IsAllowedTemplate(string templateAlias)

Do not work correctly.

### Specifics

IsAllowedTemplate(int templateId) always returns true, no matter on which page it is called and whether the ID even exists or not.

IsAllowedTemplate(string templateAlias) does not seem to be implemented (cannot convert string to int). It throws an error on the frontend, as it expects an integer.

### Steps to reproduce

I tried this with a simple setup, where I tried to check whether the current page is allowed to use the home page template or not.
Something like

```
if(Model.IsAllowedTemplate(1021)){
<p>True</p>
}
else{
<p>False</p>
}
```

### Expected result / actual result

IsAllowedTemplate(int templateId) returns true or false depending on whether the template selected is allowed under the model/doctype.
IsAllowedTemplate(string templateAlias) should work similarly, except with an alias.

**Comment by emma-hq** [comment]
Hiya Jay!

Thanks for this report and all the info. Makes it nice and straightforward for us to work with. We'll shout if we need any more info

Emma

**Comment by warrenbuckley** [comment]
## Investigation Notes
The IPublishedContent extension method for IsAllowedTemplate() does not support TemplateAlias and seems just needs to be added.

You can use it with TemplateAlias VSCode, Visual Studio or Rider should show the available overloads
`@if(Model.IsAllowedTemplate(true, true, "home"))`
![image](https://user-images.githubusercontent.com/1389894/121340860-f82c0f80-c917-11eb-9189-f055c6d2bb36.png)

I verified the above works with the correct and incorrect template alias name
But we have no overload for Model.IsAllowedTemplate("home") if we have had this previously in V8

When using the int overload approach, you are correct @Jay-umbr that it does not validate it correctly
`@if(Model.IsAllowedTemplate(10600))` 

> But I believe this is because the default code settings for WebRouting are setup incorrectly IMO, if we are allowing AlternativeTemplates to be allowed out of the box by default surely we should Validate them too.

Thoughts ⬆️ @bergmania 


```
        /// <summary>
        /// Gets or sets a value indicating whether the use of alternative templates are disabled.
        /// </summary>
        public bool DisableAlternativeTemplates { get; set; } = false;

        /// <summary>
        /// Gets or sets a value indicating whether the use of alternative templates should be validated.
        /// </summary>
        public bool ValidateAlternativeTemplates { get; set; } = false;
```

You can modify your appsettings.json or appsettings.development.json to include the following JSON config keys inside `Umbraco.CMS`

```json
"WebRouting": {
    "ValidateAlternativeTemplates": true,
    "DisableAlternativeTemplates": false
 },
```

**Comment by bergmania** [comment]
@warrenbuckley, IMO we should just have the same defaults as we have in v8. Those we can discuss are the ones that has different default value and value in web.config (by default), like we saw for `HideTopLevelNodeFromPath`.

**Comment by warrenbuckley** [comment]
@bergmania the V8 defaults in UmbracoSettings.config are both false.
Now off to test this functionality out of the box in V8 to see if it behaves the same.

```xml
<web.routing trySkipIisCustomErrors="true" 
    internalRedirectPreservesTemplate="false" 
    disableAlternativeTemplates="false" 
    validateAlternativeTemplates="false"
    disableFindContentByIdPath="false" 
    umbracoApplicationUrl="">
  </web.routing>
```

**Comment by warrenbuckley** [comment]
I can confirm this has the same behaviour as V8 out of the box, so you need to enable the setting in V8 `validateAlternativeTemplates="true"` in the web.routing section of UmbracoSettings.config

So the only issue left is to add the missing overload to simply just pass along the template name/alias which I will do a PR for

**Comment by warrenbuckley** [comment]
PR for this is here - https://github.com/umbraco/Umbraco-CMS/pull/10425

**Comment by elit0451** [comment]
Spoke to @Jay-umbr and he confirmed that this is an issue introduced sometime ago in v8, but he saw it first when testing v9. Just FYI 🙂
