### ISSUE TITLE
Rebuild Database Cache button does nothing

### ISSUE THREAD

**Issue by JoseMarcenaro** [umbraco/Umbraco-CMS#10394]
### Which Umbraco version are you using?

v9.0.0-beta003

### Bug summary

Clicking the "Rebuild" button on the Caches block of the Settings / Published Status section seems to do nothing.
My cache was broken and I could not fix it with this.
As a test, I manually emptied the cmsContentNu table:
```
delete [dbo].[cmsContentNu] 
```
After doing that, clicking the button does not rebuild the table contents

### Steps to reproduce

Remove all rows from the cmsContentNu table and run the command

### Expected result / actual result

The table is not rebuild and remains empty
The expected / v8 behavior is to rebuild it.

**Comment by warrenbuckley** [comment]
## Notes
I can reproduce this error for V9 and can confirm this was working fine in V8

**Comment by bergmania** [comment]
Thanks for reporting @JoseMarcenaro.. 

The issue is fixed in this PR: https://github.com/umbraco/Umbraco-CMS/pull/10519

**Comment by JoseMarcenaro** [comment]
Thanks @bergmania 
Please dismiss the #10441 PR then (or should I do it? I'm not familiar with the workflow)

**Comment by warrenbuckley** [comment]
Fixed in this PR #10519

**Comment by bergmania** [comment]
> Thanks @bergmania
> Please dismiss the #10441 PR then (or should I do it? I'm not familiar with the workflow)

Sorry I didn't see your attempt to resolve it.  Your solution would work, but in that case the trees would not be locked. You can see the additional change I did in my PR.
