### ISSUE TITLE
Rename Content apps for v9

### ISSUE THREAD

**Issue by patrickdemooij9** [umbraco/Umbraco-CMS#10399]
### Umbraco version

v9

### Description

Now that we are moving to v9 and seeing that we also changed the name for the different model builder modes, should we also do this change for content apps?

Content apps started out as something just for content. But we now have the ability to also add them to Members and Document Types (and in the future may be to more places). Their name should ideally be updated to reflect those changes. The suggestions in the issue discussed below that I personally agree with most are:

- Context app
- Editor app

There is some more discussion about it here: https://github.com/umbraco/Umbraco-CMS/issues/8863.

This would be a breaking change as it'll also change the formatting in the package.manifest, but this is probably the best timing to do so together with the other changes of v9.

### How can you help?

If this is accepted, I can go through the code and replace all instances to the new naming.

**Comment by nielslyngsoe** [comment]
`Editor app` is a good proposal and gives some context to it ;-)

Whether this detail will create more annoyance for upgrades, compared to the value of it. I don't know. But now the conversation is started... :-)
