### ISSUE TITLE
Umbraco 9 Beta Password Isn't working

### ISSUE THREAD

**Issue by DavidArmitage** [umbraco/Umbraco-CMS#10401]
### Which Umbraco version are you using?

Umbraco version 9.0.0-beta003

### Bug summary

I created a new project from scratch.
When I registered and configured the DB I set the password.
this all complete find and I was able to login fine when ever I want.

I then tested changing the password in the Umbraco backend.
This seem to look as you would expect and it seemed to work with no errors.

But they when I tested logging in the password was still the old one. I tried to do this multiple times. I just dont think the reset password functionality is working.

### Steps to reproduce

I created a new project from scratch.
When I registered and configured the DB I set the password.
this all complete find and I was able to login fine when ever I want.

I then tested changing the password in the Umbraco backend.
This seem to look as you would expect and it seemed to work with no errors.

But they when I tested logging in the password was still the old one. I tried to do this multiple times. I just dont think the reset password functionality is working.

### Expected result / actual result

The password should have changed to the new one.

**Comment by warrenbuckley** [comment]
I can repro this @bergmania 
Will start to investigate

**Comment by warrenbuckley** [comment]
OK so if you change your password via clicking your user avatar top right and change from that dialog it works without issue.
Investigating further we have two different HTTP requests for the two different approaches

![image](https://user-images.githubusercontent.com/1389894/121326997-f4de5700-c90a-11eb-9b3a-d9ba9e9f1faa.png)
