### ISSUE TITLE
Multinode Treepicker xPath doesn't work when the Documenttype name is in camelcase

### ISSUE THREAD

**Issue by jordan-umbrace** [umbraco/Umbraco-CMS#10408]
### Which Umbraco version are you using?

8.13.0

### Bug summary

When using a Multinode Treepicker and applying the xpath query when the Document Type you want to pick has an uppercase letter(e.g. Legal Documents -> legalDocuments), Umbraco throws an error each time you visit the node. It also doesn't find the starting node when picking.

<img width="1280" alt="Screen Shot 2021-06-07 at 12 52 38" src="https://user-images.githubusercontent.com/16898679/121005172-d1db6800-c78f-11eb-8b67-fff90d003fa3.png">

### Specifics

Checked in other browers.
This problem occurs on the Sitenode of my website, which holds all other nodes.

### Steps to reproduce

Add Legal Documents and Legal Document Document types. Allow Legal Document to be created under Legal Douments. In the Content Section, add Legal Documents and multiple pages of Legal Document.
Back to Settings, add a Multinode Treepicker on the Sitenode. Click 'Query for root node' and add '$site/legalDocuments'. Also Allow items of type 'Legal Document'.
Now go back to the SiteNode in the Content Section and pick a 'Legal Document'. It will not open the Legal Documents folder = the xpath doesn't work. 

- Weird thing is, it works when the picked item doesn't have a capitalized letter in the Document Name. (e.g. Picking items of Doctype 'Project' works perfectly)

### Expected result / actual result

Desired outcome: After entering the Docuemnt Type in the xpath, I should see the chosen folder in the picker.

Actual results: I just see the full Content Tree, with all the nodes grayed out.

**Comment by nul800sebastiaan** [comment]
The point of the XPath query would be to find a single node as start node, it looks like you're trying to find a bunch of pages of the same type. What `$site/legalDocuments` does is find the first instance of a node with the `nodeTypeAlias` of `legalDocuments` as a child node of the `$site`. 

So I did something similar here:

![image](https://user-images.githubusercontent.com/304656/121020782-fee44680-c7a0-11eb-8e1b-6bb0286a5d66.png)

My filter is `$site/contentPage`. There's 2 of those under `$site` (About Us and Test Content Page), it took the first one as the start node of this picker.

I assume you wanted the editor to only be able to select items of type "Legal Document", which is the `Allow items of type` config option under the XPath.

![image](https://user-images.githubusercontent.com/304656/121021037-3e129780-c7a1-11eb-8bf3-aea566cda395.png)

For further questions, I will refer you to the forum where our friendly community will be able to help you find the best solution for your particular use case: https://our.umbraco.com

**Comment by dampee** [comment]
@nul800sebastiaan  I tried this also in 8.13.0 and it was not working when changed the xpath to ourBlog

**Comment by nul800sebastiaan** [comment]
Try as I might, it works as expected for me:

https://user-images.githubusercontent.com/304656/121137857-6947c600-c837-11eb-8a5d-fdb5d869eedd.mp4
