### ISSUE TITLE
ImplementPropertyType attribute is misleading

### ISSUE THREAD

**Issue by JasonElkin** [umbraco/Umbraco-CMS#10419]
### Which Umbraco version are you using?

8.5 - 9-beta3

### Bug summary

When modelsbuilder was embedded into Umbraco the `ImplementPropertyType` attribute was retained but some of it's functionality removed. Specifically the use of the attribute to define a custom implementation of a property and prevent modelsbuilder from generating it.

The code comments/docs suggest that the attribute will still behave this way, but it wont.

It's also confusing that the name is the same as the attribute still used in ModelsBuilder.Original, and actually doesn't do what it's name suggests either - it doesn't actually implement the property "type".

### Steps to reproduce

Generate some AppData/SourceCode models in Umbraco:

![image](https://user-images.githubusercontent.com/7151793/121264203-b4e98680-c8ae-11eb-8318-dceb43c1d2c0.png)

### Expected result / actual result

Can it be renamed to something more accurate e.g. `ImplementsProperty`?

Is it even necessary? Poking around in code it seems that it's only used to get the property alias of a model's property. Now that properties cannot be given custom names the property name will always be a valid alias for the property anyway (although not _the_ alias I guess because of casing conversion from alias to property)

**Comment by mbogunovic** [comment]
@JasonElkin  Agreed, I've gone through the same pain of spending too much time because of using the wrong namespace. If anyone encounters a similar issue that the properties are generated even though you used ImplementPropertyType attribute check this issue https://github.com/umbraco/Umbraco-CMS/issues/7495

**Comment by kjac** [comment]
Hi @JasonElkin,

Thanks for raising this - sorry for the quite belated response 😞 

I do get where you're going, but the naming does actually make sense when we dig somewhat deep.

The `Alias` property of `ImplementPropertyTypeAttribute` is used by the static `PublishedModelUtility.GetModelPropertyType()` method to retrieve... the `IPublishedPropertyType` of a models builder model property.

![image](https://user-images.githubusercontent.com/7405322/212302074-5e7656f8-87f5-4522-987d-18dcbbdd5c18.png)

![image](https://user-images.githubusercontent.com/7405322/212302371-4232dcf0-b894-4ce5-b2f9-6486268e3215.png)

As all of this is public (and static no less!) it's impossible to know who might be using it out in the wild and for what. While it's not really used for anything internally, removing it would be a terribly breaking thing to do by now 🙈

**Comment by JasonElkin** [comment]
Yeah @kjac , I looked at that code, all it's used for is to tie a property to its alias, which now only serves to preserve the original casing of the property alias (the ModelsBuilder property name is now always the alias but in pascal case).

It's still got nothing to do with "type" so renaming would be nice, but I appreciate it's a breaking change.

The absence of customisability in the core ModelsBuilder seems to be causing less confusion/fewer problems these days anyway so I guess it's less of a problem than it was.

**Comment by abjerner** [comment]
IMO the attribute has lost it's use case in vanilla Umbraco installations, but when looking at packages, my custom [Limbo Models Builder](https://github.com/limbo-works/Limbo.Umbraco.ModelsBuilder) package listens for this attribute, in which case it works like in the original Models Builder.

So removing it would be a breaking change for me and possibly others like already mentioned. My package does however have it's own attribute with a similar purpose, so it wouldn't be a big problem here if Umbraco's property is removed in a future major version of Umbraco.
