### ISSUE TITLE
v9 project template can result in invalid appsettings.json

### ISSUE THREAD

**Issue by JasonElkin** [umbraco/Umbraco-CMS#10424]
### Which Umbraco version are you using?

9.0.0-beta003

### Bug summary

Passwords and connection strings entered into New Project wizard in Visual Studio will result in invalid appsettings.json if they are not valid JSON.

### Steps to reproduce

Create a new v9 project from the template in Visual Studio.
Use a password and/or connection string that contains a `"` and/or `\` (both reasonably common scenarios).

![image](https://user-images.githubusercontent.com/7151793/121345088-58bd4b80-c91c-11eb-87b2-ca3f6c0343cb.png)

appsettings will be invalid:

![image](https://user-images.githubusercontent.com/7151793/121345341-a639b880-c91c-11eb-9274-dd15c50be034.png)

But you probably won't notice until you actually try and run the site and get this message:

![image](https://user-images.githubusercontent.com/7151793/121345404-b5b90180-c91c-11eb-9db8-13412e59aad7.png)

### Expected result / actual result

Text entered in those fields to be safely encoded.

**Comment by bergmania** [comment]
Hi @JasonElkin .. Thanks for reporting. That issue make sense, we will look into it :)

**Comment by warrenbuckley** [comment]
@JasonElkin this is fixed in this PR
https://github.com/umbraco/Umbraco-CMS/pull/10467
