### ISSUE TITLE
Can't create a Rich Text Editor with default configuration

### ISSUE THREAD

**Issue by elit0451** [umbraco/Umbraco-CMS#10427]
### Which Umbraco version are you using?

v9

### Bug summary

When choosing to create a new Rich Text Editor with the default configuration, it results in the error: _"Value cannot be null. (Parameter 'key')"_. In the latest v8, this behaviour is **not** present and there you can create a new Rich Text Editor with the default configuration without a problem.

### Specifics

https://localhost:44331/umbraco/backoffice/umbracoapi/datatype/PostSave returns 500

### Steps to reproduce

1. Create a new doc type
2. Select a new Rich Text Editor under "**Create a new configuration**" 
3. Submit without changing anything
4. Error pops up

### Expected result / actual result

Expected: Able to save the RTE without a problem
Actual: Not able to save the RTE with default settings

**Comment by bergmania** [comment]
Fixed by this commit https://github.com/umbraco/Umbraco-CMS/commit/5eb94736578b4efe0fccfa8890283ce66d2fd0cc
