### ISSUE TITLE
Searching in mediapicker doesn't filter according to allowedtypes

### ISSUE THREAD

**Issue by SofusMunch** [umbraco/Umbraco-CMS#10429]
### Which Umbraco version are you using?

8.14

### Bug summary

When setting allowed media types for mediapicker3 the search function doesn't filter the result according to the selected allowed types. It does show a "not allowed" error in the property editor if invalid types are chosen, but in my case there are specific media types some users shouldn't even see. 

It's also inconsistent since not allowed types aren't selectable when navigating the tree in the picker, but are selectable as a search result. 

### Steps to reproduce

Not selectable;
![not selectable](https://user-images.githubusercontent.com/789813/121506602-26772100-c9e4-11eb-9cd3-30e62a8be26a.png)

Selectable after search:
![searched_selectable](https://user-images.githubusercontent.com/789813/121506614-29721180-c9e4-11eb-8fb9-5b5858c11ff3.png)

**Comment by patrickdemooij9** [comment]
Created a PR to fix this issue: https://github.com/umbraco/Umbraco-CMS/pull/10451

**Comment by nul800sebastiaan** [comment]
Fixed in https://github.com/umbraco/Umbraco-CMS/pull/10451 and cherry picked for 8.14.1 in 8a810e698c1b99affc9536abcd06f0cb3f40e581
