### ISSUE TITLE
v9 - Default "upload" datatypes have no accepted file extensions (or do they?)

### ISSUE THREAD

**Issue by JeffreyPerplex** [umbraco/Umbraco-CMS#10438]
### Which Umbraco version are you using?

9.0.0-beta003

### Bug summary

If you go the default upload datatypes in "Settings"

![afbeelding](https://user-images.githubusercontent.com/12457148/121578287-ce174200-ca2a-11eb-9a1f-f315fa070a5a.png)

and click on one of them you see that there are no valid file extensions (it's empty)

![afbeelding](https://user-images.githubusercontent.com/12457148/121578223-bc359f00-ca2a-11eb-987e-a86fabfe3cd4.png)

### Steps to reproduce

1) Clean install
2) Go to /umbraco#/settings/dataTypes/edit/-101 or one of the others
3) The file extensions settings are there, but empty...

**Comment by Matthew-Wise** [comment]
I believe 
https://github.com/umbraco/Umbraco-CMS/blob/v9/dev/src/Umbraco.Core/PropertyEditors/FileUploadConfiguration.cs is missing a Data Contract attribute. 

Just haven't had time to make the change and test it

**Comment by bergmania** [comment]
@Matthew-Wise, do you want me to fix it, or did you already start?

**Comment by Matthew-Wise** [comment]
@bergmania You can do it :) I wont get to it today :(
