### ISSUE TITLE
Umbraco 9 - Insert value via Template Build in Umbraco freezes installation

### ISSUE THREAD

**Issue by JeffreyPerplex** [umbraco/Umbraco-CMS#10436]
### Which Umbraco version are you using?

9

### Bug summary

0) Fresh Umbraco installation 9.0.0-beta003
1) I've created a document type called Homepage
2) Go to edit the template

/umbraco#/settings/templates/edit/1055

![afbeelding](https://user-images.githubusercontent.com/12457148/121575518-c4400f80-ca27-11eb-8a61-076b8391d0cc.png)

3) Go to "Insert..."

![afbeelding](https://user-images.githubusercontent.com/12457148/121575543-cf933b00-ca27-11eb-8ad4-4e2281cc2a99.png)

4) Click "Value"

![afbeelding](https://user-images.githubusercontent.com/12457148/121575571-d621b280-ca27-11eb-9ced-22cc437ca796.png)

5) Choose field => "Text" (the only property that I added to the document type):

![afbeelding](https://user-images.githubusercontent.com/12457148/121575639-e46fce80-ca27-11eb-8b1a-90ae3f726d96.png)

6) Click "Submit"

Result: The UI completely freezes...

![afbeelding](https://user-images.githubusercontent.com/12457148/121575836-1a14b780-ca28-11eb-959a-66553c2df72e.png)

### Specifics

Both in Firefox & Chrome

### Steps to reproduce

See the bug itself :)

### Expected result / actual result

That my browser did not freeze ;)

**Comment by bergmania** [comment]
Thanks for reporting @JeffreyPerplex..

Sadly I can't reproduce..  Just to be sure, this was on windows right?

Can you reproduce, while having the developer tool open in FF or Chrome, and see if there are any errors shown?

![Animation](https://user-images.githubusercontent.com/1561480/121738728-e3f43800-cafa-11eb-8d19-248ad24e3848.gif)

**Comment by bergmania** [comment]
Okay, so I managed to reproduce.. Seems to be something with the release build..

**Comment by kjac** [comment]
I can reproduce this on beta-003 but not on the nightly build (and nor on the latest v9/dev). I think this might have been automagically fixed...

**Comment by bergmania** [comment]
Thanks, @kjac.. 

I guess this has been related fixed again in a merge from v8 🙈
