### ISSUE TITLE
Typo in mediapicker3 template/view

### ISSUE THREAD

**Issue by SofusMunch** [umbraco/Umbraco-CMS#10430]
### Which Umbraco version are you using?

8.14

### Bug summary

umb-media-picker3-property-editor.html and inline template in mediapicker3 component:

The "addMediaAt"-button disabled attribute is misspelled (disbled). It also needs to be ng-disabled to work:

### Steps to reproduce

![mediapicker typo](https://user-images.githubusercontent.com/789813/121507661-21ff3800-c9e5-11eb-847f-43ae67e0c26a.JPG)

![mediapicker typo component](https://user-images.githubusercontent.com/789813/121508271-b5d10400-c9e5-11eb-903f-5f2631ecf967.JPG)

**Comment by nathanwoulfe** [comment]
Fixed in #10440
