### ISSUE TITLE
9.0.0-beta003 Cannot acquire MainDom Azure Linux SQL Server Express

### ISSUE THREAD

**Issue by mkchmiel** [umbraco/Umbraco-CMS#10457]
### Which Umbraco version are you using?

9.0.0-beta003

### Bug summary

Issue is happening within a Azure environment. CMS running as an App Service Docker Container and SQL Server Express running on Ubuntu 16.04LTS. Since I cannot complete the install in the cloud I do it locally while pointing to the cloud sql server. Once completed I deploy the docker image. Add the connection string to the app server. After this most certainly will encounter the error.

Unhandled exception. System.TimeoutException: Cannot acquire MainDom at Umbraco.Cms.Core.Runtime.MainDom.Acquire()...

Found some documentation stating I should add to application settings:
Umbraco.Core.LocalTempStorage:"EnvironmentTemp" and
Umbraco.Core.MainDom.Lock:"SqlMainDomLock" but having both of these does not change the error message.
Interestingly enough if I remove the connection string the site works but then I am unable to complete the install as I cant connect to the azure sql server instance.
![image](https://user-images.githubusercontent.com/1263432/121827877-4bd58a80-cc83-11eb-887e-94d527443bcd.png)

If there is any way I can help or provide additional details please give me a heads up, I would be glad to contribute to this project.

### Steps to reproduce

1. Setup standard Umbraco beta 9 instance
2. Update your project and solution name
3. Right click project add docker and update docker file to also include umbracoprereleases before build
3. Locally complete install via debug, using the azure sql database as connection (not this same connection that works locally does not work once deployed)
4. Verify deployed version is showing install screen
5. Notice that attempting to input the identical connection from local install does not work
![image](https://user-images.githubusercontent.com/1263432/121828378-04e89480-cc85-11eb-95bd-34ba7fcd9fc9.png)
6. Go to Settings/Configuration of the app service, and add the connection string manually to the connection string
![image](https://user-images.githubusercontent.com/1263432/121827877-4bd58a80-cc83-11eb-887e-94d527443bcd.png)
7. Site will now fail and present the Cannot acquire MainDom error

### Expected result / actual result

Site should be able to get passed the connection portion of the install in Azure and or not encounter MainDom error if work around followed

**Comment by nzdev** [comment]
Is MainDom locking still required as there are no AppDomains on .net core?

**Comment by mkchmiel** [comment]
I want to comment I may have been wrong about that connection string setting, checking the error logs this morning it seems that the error "Cannot acquire MainDom" comes up after some time? Not completely understand this flow yet

**Comment by Shazwazza** [comment]
There are appdomains in netcore. Maindom is still required in order to synchronize access to file based things (i.e. nucache and examine). Azure and IIS manage the appdomain/process and they can overlap so synchronizing access to these resources is still required. The code detects if it's a linux system and will always use the sqlmaindom lock, potentially there's code that need to do some additional checks to ensure that if there is no db configured (i.e. install/upgrade/etc...) that maindom just allows access.

**Comment by mkchmiel** [comment]
Guess you were right Shazwazza.
...\Umbraco-CMS-9-9.0-beta003\src\Umbraco.Core\Runtime\MainDom.cs
Line 167 acquired = _mainDomLock.AcquireLockAsync(LockTimeoutMilliseconds).GetAwaiter().GetResult(); results in false
and line 184 causes error for this ticket

..\src\Umbraco.Core\Runtime\MainDomSemaphoreLock.cs Line 36
AcquireLockAsync(int millisecondsTimeout) takes us to

..\Umbraco.Core\SystemLock.cs
_semaphore2.WaitOne(millisecondsTimeout) returning false after 40000 (40 seconds)

I am new to azure app services but as soon as I figure out what causes the error or at the very least why it occurs ill update

**Comment by mkchmiel** [comment]
Ok this appears to be a setup issue with azure, closing this ticket. Just noting here that it helped greatly being able to console log the exceptions and then use the log stream to see the issue.
