### ISSUE TITLE
v9 - Label property editor always show "Default" next to ValueType

### ISSUE THREAD

**Issue by bjarnef** [umbraco/Umbraco-CMS#10461]
### Which Umbraco version are you using?

9.0.0-beta001

### Bug summary

When creating a datatype instance on Label property editor in v9, it always show "Default" next to ValueType dropdown.

![image](https://user-images.githubusercontent.com/2919859/121865773-a102b200-ccfe-11eb-8431-52db54dc669b.png)

I don't think that is expected behavior. Either it should show something like "(default)" at String value in the dropdown, e.g. "String (default)" ... or the label should be hidden when not default option is selected.

### Steps to reproduce

Create a datatype instance of Label property editor. Note that is always shows "Default" next to ValueType dropdown even though selecting another value type.

**Comment by bergmania** [comment]
Fixed in this commit: https://github.com/umbraco/Umbraco-CMS/commit/ff99e6c6fdf64b6afa62265661d96d0c03e44012
