### ISSUE TITLE
Pluggin using issue

### ISSUE THREAD

**Issue by vishnukum-code** [umbraco/Umbraco-CMS#10478]
### Which Umbraco version are you using?

9

### Bug summary

Hi,

I would love to use this plugin. Unfortunately it gave me an error in Umbraco 9 its perfectly works in Umbraco 8 and previous.
angular.js:15635 Error: [$controller:ctrlreg] http://errors.angularjs.org/1.8.0/$controller/ctrlreg?p0=Novicell.NcWidthBreakpoint

Do you think you can fix it? It would be really great.

Thanks!

### Steps to reproduce

![controller-error](https://user-images.githubusercontent.com/77272103/122163155-544fe000-ce92-11eb-8353-24ac0764c78f.png)

**Comment by nathanwoulfe** [comment]
Hi @vishnukum-code you'll need to talk to the crew at Novicell about their plans for upgrading the package to support V9 - it's not something to be fixed at the Umbraco end.

Given the re-platforming from V8 to V9, you should expect that most packages that work on V8 won't work on V9 (some will, depends on what the plugin is doing, but in general you'd be best to wait for V9-compatible versions to be released)

**Comment by bjarnef** [comment]
It seems the issues are regarding the `Novicell.NcWidthBreakpoint` and `Novicell.Theme` controllers.
Are these custom added in App_Plugins or maybe via a package?

Do you have Angular view calling these controllers, but the controllers are not included in a package.manifest?

**Comment by vishnukum-code** [comment]
Hello @nathanwoulfe  thanks for your reply .
you right i should wait for V9-compatible versions

**Comment by vishnukum-code** [comment]
Hi @bjarnef  thanks for your reply.
All things are perfect because of these plugins works in umbraco8 version perfectly. And controllers are also included in package.manifest i checked it again.
