### ISSUE TITLE
Media Picker v3 - Multiple Items "Add" Not disabled when max count is reached 

### ISSUE THREAD

**Issue by TRexStark** [umbraco/Umbraco-CMS#10474]
### Which Umbraco version are you using?

8.14.0

### Bug summary

Media Picker v3 with multiple items
When you set a maximum value for the items
The "Add" button remains active

I actually found where the bug is:
in umbraco.directives.js > line 20126 > disbled="!vm.allowAdd"
it should be disabled. As soon as I fixed this in my installation, the button becomes disabled

**UPDATE:**
When I did the above fix, another issue emerged.
When the Add button is disabled, if you remove one of the Media items added, the button does not become enabled.

### Steps to reproduce

Just create a Media Picker v3 property with a max items limit and add your items until you reach the maximum allocated.

### Expected result / actual result

Either the button becomes disabled or hidden altogether.

**Comment by nathanwoulfe** [comment]
Hey @TRexStark this one has been fixed in #10440, hopefully will be part of 8.14.1
