### ISSUE TITLE
Replacing ContentFinderByUrl causes "This document is published but its URL cannot be routed"

### ISSUE THREAD

**Issue by Myster** [umbraco/Umbraco-CMS#10487]
### Which Umbraco version are you using?

8.10.1, and 8.12.2

### Bug summary

If I replace the ContentFinderByUrl with my own implementation (that calls ContentFinderByUrl as it's base implementation) then everything in the front end works correctly, but the back office info tab says "This document is published but its URL cannot be routed"

### Steps to reproduce

Add this Composer:

```
	[RuntimeLevel(MinLevel = RuntimeLevel.Run)]
	public class ContentFinderComposer : IUserComposer
	{
		public void Compose(Composition composition)
		{
			composition.ContentFinders().Replace<ContentFinderByUrl, MasterContentFinder>();
		}
	}
```

With this content Finder:
```
	public class MasterContentFinder : IContentFinder
	{
		private readonly ILogger _logger;
		private readonly ContentFinderByUrl _finderByUrl;
		private readonly ContentFinderByIdPath _finderByIdPath;

		public MasterContentFinder(IWebRoutingSection webRoutingSection, ILogger logger)
		{
			_logger = logger;
			_finderByUrl = new ContentFinderByUrl(logger);
			_finderByIdPath = new ContentFinderByIdPath(webRoutingSection, logger);
		}

		public bool TryFindContent(PublishedRequest request)
		{
			// do not run in the CMS
			if (request.UmbracoContext.IsFrontEndUmbracoRequest == false)
				return false;

			if(_finderByUrl.TryFindContent(request))
			{
				//irrelevant code removed
				return true;
			}

			return false;
		}
	}

```

work-around is to set the content finder to insert your new one instead of replace the existing one.

`composition.ContentFinders().InsertBefore<ContentFinderByUrl, MasterContentFinder>();`

### Expected result / actual result

I would expect the back office to show the correct URL in the "Links" section

**Comment by Myster** [comment]
Aside: the "irrelevant code removed" is set up to redirect to the canonical URL and ensure that any URLs for a given piece of content all redirected to the canonical URL

**Comment by patrickdemooij9** [comment]
The issue here lies within:
`if (request.UmbracoContext.IsFrontEndUmbracoRequest == false)
				return false;`

Umbraco will do a request within the backoffice to show the correct URL, but it'll fail because of this check. You'll notice that even though it says that it cannot route your page, the URL does still work on the normal website.

Do you need that piece of code there?

**Comment by Myster** [comment]
Ahh, my mistake, thank you!
