### ISSUE TITLE
Media Item on click Remove file(s) and then Save button doesn't remove the file from blob storage 

### ISSUE THREAD

**Issue by davit20** [umbraco/Umbraco-CMS#10501]
### Which Umbraco version are you using?

8.14

### Bug summary

The file is not removed from Blob storage. and still exists with the same URL on the blob storage.

### Steps to reproduce

If you already have a media item type of **File**,  click on **Remove file(s)** and then click on **Save**. The file will be removed from the media item but the file still exists with the same URL on the blob storage.

**Comment by nul800sebastiaan** [comment]
That seems to be a problem with the blob storage provider, make sure to get in touch with whomever made the provider that you're using. 😃

**Comment by davit20** [comment]
I'm using Azure blob storage. What can be the problem?

**Comment by nul800sebastiaan** [comment]
We don't provide a blob storage provider out of the box with Umbraco, so you're likely using https://github.com/umbraco-community/UmbracoFileSystemProviders.Azure or another solution. That solution should be fixed to delete items when removing them.
