### ISSUE TITLE
v9 - Render Block List partial async

### ISSUE THREAD

**Issue by bjarnef** [umbraco/Umbraco-CMS#10508]
### Which *exact* Umbraco version are you using?

9.0.0-beta004

### Bug summary

In https://github.com/umbraco/Umbraco-CMS/issues/10507#issuecomment-865886350 I noticed Visual Studio warning about `@Html.Partial()` in Block List default.chtml.

```
@inherits Umbraco.Cms.Web.Common.Views.UmbracoViewPage<Umbraco.Cms.Core.Models.Blocks.BlockListModel>
@{
    if (!Model.Any()) { return; }
}
<div class="umb-block-list">
    @foreach (var block in Model)
    {
        if (block?.ContentUdi == null) { continue; }
        var data = block.Content;

        @Html.Partial("BlockList/Components/" + data.ContentType.Alias, block)
    }
</div>
````

https://github.com/umbraco/Umbraco-CMS/blob/v9/9.0-beta004/src/Umbraco.Web.UI.NetCore/Views/Partials/blocklist/default.cshtml

### Steps to reproduce

I found this: https://stackoverflow.com/a/52723364/1693918

It seems we can use the following instead, which still render the block elements as expected.

```
@inherits Umbraco.Cms.Web.Common.Views.UmbracoViewPage<Umbraco.Cms.Core.Models.Blocks.BlockListModel>
@{
    if (!Model.Any()) { return; }
}
<div class="umb-block-list">
    @foreach (var block in Model)
    {
        if (block?.ContentUdi == null) { continue; }
        var data = block.Content;

        @await Html.PartialAsync("BlockList/Components/" + data.ContentType.Alias, block)
    }
</div>
```

![image](https://user-images.githubusercontent.com/2919859/122927931-a5b40f80-d369-11eb-8bd6-0c36740ebaf2.png)

![image](https://user-images.githubusercontent.com/2919859/122927876-992fb700-d369-11eb-8b03-6fcd48125790.png)

Furthermore it seems the following would also work in .NET Core (the first one is probably the preferred and easiest to handle if migrating a site to Umbraco v9):

```
@inherits Umbraco.Cms.Web.Common.Views.UmbracoViewPage<Umbraco.Cms.Core.Models.Blocks.BlockListModel>
@{
    if (!Model.Any()) { return; }
}
<div class="umb-block-list">
    @foreach (var block in Model)
    {
        if (block?.ContentUdi == null) { continue; }
        var data = block.Content;

        <partial name="@("BlockList/Components/" + data.ContentType.Alias)" model="@block" />
    }
</div>
```

**Comment by bjarnef** [comment]
@bergmania any specific reason not to render the partial async here? 🔃

**Comment by bergmania** [comment]
> @bergmania any specific reason not to render the partial async here? 🔃

Hi @bjarnef, 
No, I don't see any reasons not to render the partials async.

**Comment by bjarnef** [comment]
PR submitted: https://github.com/umbraco/Umbraco-CMS/pull/10511
