### ISSUE TITLE
Preview uses cached content - v8.11.1

### ISSUE THREAD

**Issue by jebastin-jeyaraj** [umbraco/Umbraco-CMS#10510]
### Which *exact* Umbraco version are you using? For example: 8.13.1 - don't just write v8

8.11.1

### Bug summary

**When previewing a page it's showing the content from cache instead of showing the recently added content.**

### Steps to reproduce

1. Edit any node/page in Umbraco back office.
2. Click the preview button

### Expected result / actual result

To show the recently added content.

**Comment by nul800sebastiaan** [comment]
Unfortunately that's not something we can reproduce or have seen before @jebastin-jeyaraj. Could be anything really, I would recommend reviewing any custom code you may have or otherwise ask around on the forum where our friendly community might be able to help you along: https://our.umbraco.com/

**Comment by nul800sebastiaan** [comment]
Forgot to add the video I made, this is my result on v8.11.1: 

https://user-images.githubusercontent.com/304656/123137012-d7a1a080-d453-11eb-874d-5265b115bdcb.mp4

**Comment by rbottema** [comment]
Could it perhaps have something to do with the `CachedPartial`, as in #10384?
