### ISSUE TITLE
Mandatory Nested Content forces validation on all properties in said NC

### ISSUE THREAD

**Issue by Frost117** [umbraco/Umbraco-CMS#10520]
### Which *exact* Umbraco version are you using? For example: 8.13.1 - don't just write v8

8.14.0

### Bug summary

When you have a Nested content propertype in the backoffice that forces validation to pick a element type, it will then force the same validation across all the properties inside the element type, even though it is not set as mandatory on the element type.

![image](https://user-images.githubusercontent.com/32164310/123075346-71e3f300-d418-11eb-8ba6-07dce44efe6f.png)

![image](https://user-images.githubusercontent.com/32164310/123075308-698bb800-d418-11eb-9425-b3898e02566b.png)

![image](https://user-images.githubusercontent.com/32164310/123075415-81fbd280-d418-11eb-82e0-e488176ea507.png)

### Steps to reproduce

1. Make an Element type with the following: 
Two textfields.
Make one of them Mandatory, leave the other as non-mandatory

2. Make a Documentype with a nested content property editor, where you select the element type from earlier.
3. Enable mandatory state on the Documentype for the Nested content, and allow to be created in root.
4. Create a content node.
5. You will now see that the non-mandatory field is set to be Mandatory

### Expected result / actual result
I expect that the Mandatory setting is only applied for the select property and not everything inside the Nested content.

The actual result is that we get everything set as mandatory that is in the Nested content

---
_This item has been added to our backlog [AB#12571](https://dev.azure.com/umbraco/243e7927-03b2-44e2-908f-d4ac7ea5daaa/_workitems/edit/12571)_

**Comment by nul800sebastiaan** [comment]
I can reproduce, even if you make none of the inner properties mandatory, but the full nested content property itself is mandatory.


https://user-images.githubusercontent.com/304656/123146048-c52c6480-d45d-11eb-80b6-15c33cdd1d9c.mp4

But also if the nested content property itself is not mandatory, correcting the mandatory inner property doesn't seem to propogate.

This was supposed to be fixed in https://github.com/umbraco/Umbraco-CMS/issues/8954 but I guess something is still missing here. I did verify the code from the related PR #10013 was released in 8.14.

**Comment by nul800sebastiaan** [comment]
Fixed in https://github.com/umbraco/Umbraco-CMS/issues/10520 and cherry picked for 8.15.0 in 3e226384c3eb7940cad6357f3dbab4411c1a5bdc

**Comment by nul800sebastiaan** [comment]
FYI: more fixing is coming: https://github.com/umbraco/Umbraco-CMS/issues/10788

We'd love it if people could test the builds:

8.14 - https://dev.azure.com/umbraco/Umbraco%20Cms/_build/results?buildId=69291&view=results
8.15 - https://dev.azure.com/umbraco/Umbraco%20Cms/_build/results?buildId=69293&view=results

The build artifacts will appear in about 45 minutes from now where you can click "3 published, 1 consumed":

![image](https://user-images.githubusercontent.com/304656/128508615-2e89cf78-4ed5-4147-8a1e-4db9cb6942c1.png)

After copying in the new files, make sure to update the version of your ClientDependency.config (just make it 1 higher or lower) and then you should be able to test it out.

Releases for 8.14/8.15 are coming on the 17th of Aug, the RC of 8.16 is coming on the 12th. So hopefully in the mean time this will work and help people.
