### ISSUE TITLE
v9 Linux case-sensitive directories

### ISSUE THREAD

**Issue by nikcio** [umbraco/Umbraco-CMS#10538]
### Which *exact* Umbraco version are you using? For example: 8.13.1 - don't just write v8

9.0.0-beta004

### Bug summary

When running Umbraco on Linux you can encounter errors due to Linux being case-sensitive with file paths. This means that for example `views/propertyEditors/grid/dialogs/layoutconfig.html` would return a 404 not found because the actual path to the file is `views/propertyeditors/grid/dialogs/layoutconfig.html`.

I first encountered this problem when running Umbraco in a docker container with [Caddy](https://caddyserver.com/) as the webserver.

### Specifics

The problem is in itself pretty easy to fix due to it being a result of a simple typo. But as I see it this might also cause problems in the future due to the problem being extremely easy to overlook when developing. Therefore, you'll first notice the error when you encounter a broken GUI on a Umbraco instance running on Linux.

## Solutions

As I see it this problem has two obvious solutions which come with pros and cons.

### Solution 1 - Fixing typos

The first solution is pretty simple: Just fix the typos as they come up. But the problem with this solution is that it might be extremely difficult to notice changes that introduce typos. So for this to be a viable long-term solution there would need to be implemented some kind of test to catch these typos. Personally, I don't know of any way to do this in a reliable and scalable manner.

### Solution 2 - Recommending case-insensitive file system

The second solution is a bit more complicated. This solution is simply to recommend a case-insensitive file system. You can do this with an installation of Linux >= 5.2. Here there was added support for [case-insensitive names in ext4](https://kernelnewbies.org/Linux_5.2#Optional_support_for_case-insensitive_names_in_ext4). This can be added by following guides like this one: [Using the Linux kernel's Case-insensitive feature in Ext4](https://www.collabora.com/news-and-blog/blog/2020/08/27/using-the-linux-kernel-case-insensitive-feature-in-ext4/). The problem with this is that it's pretty complicated to get a Linux version with the case-insensitivity plugin available and from what I can read many people dislike making directories case-insensitive because it introduces security issues. (For more info about this read [Here](https://lwn.net/Articles/784041/))

**Note**: I haven't personally been able to figure out how to create a case-insensitive directory with my setup in Docker.

**Note 2**: I'm unsure if this problem arises when using a different webserver for example Nginx.

### Steps to reproduce

With the current version 9.0.0-beta004 the url: `views/propertyEditors/grid/dialogs/layoutconfig.html` is broken which means you can't add a layout to a grid when running Umbraco on Linux with [Caddy](https://caddyserver.com/) in front.

**Comment by bergmania** [comment]
Hi @nikcio 

Thanks for the bug report.

We intend to request our resources in the correct casing. I totally agree this is a bit fragile when most Umbraco developers develop on case insensitive filesystems. 

We try to avoid these challenges are to execute our Unit, Integration & Acceptance tests on both Linux and Windows. Sadly our acceptance tests that use the grid do not set up a complex configuration. That could be a future acceptance test.

Thanks for providing a second solution. I was not aware of this. That said, I still think it is Umbraco's responsibility to request our resources in the correct casing in the first place.

I have fixed the errors regarding `views/propertyEditors/*` here https://github.com/umbraco/Umbraco-CMS/pull/10544

**Comment by nikcio** [comment]
@bergmania this sounds great. I had set up a pull request with the fix here: [#10539](https://github.com/umbraco/Umbraco-CMS/pull/10539) but I'll just go ahead and close it so it doesn't become a duplicate PR.

**Comment by bergmania** [comment]
Fixed in #10539..
