### ISSUE TITLE
User Avatars result in broken images when using Azure Filesystem Provider

### ISSUE THREAD

**Issue by robertjf** [umbraco/Umbraco-CMS#10537]
### Which *exact* Umbraco version are you using? For example: 8.13.1 - don't just write v8

8.14.0

### Bug summary

User Avatars cannot be retrieved when the Azure Filesystem Provider is utilised:

![image](https://user-images.githubusercontent.com/818101/123499009-f3d15780-d676-11eb-863d-c299960344c6.png)

This is because Blob Storage Urls are case-sensitive but something is causing the urls to be redirected (301) to lowercase:

![image](https://user-images.githubusercontent.com/818101/123499057-401c9780-d677-11eb-8da1-ba19077afa3d.png)

When the User Avatars are saved, they are saved in the following folder: `/media/UserAvatar`.

I can verify the file exists in Azure, and when I browse to it's url directly I can view the image:

![image](https://user-images.githubusercontent.com/818101/123499256-c5547c00-d678-11eb-8129-8e65990801f6.png)

https://lifesupportscounselling.blob.core.windows.net/media/UserAvatars/39fbd101bf1e84464dc84eb363e66041ff0df5e3.jpeg

I haven't been able to verify where the redirect is coming from but perhaps the easiest way to deal with this is to simply save the image path as lowercase when uploading the file?  I.e. UserAvatars should be useravatars perhaps...

### Steps to reproduce

1. Configure Umbraco with the Azure Filesystem Provider
2. Upload a user Avatar

### Expected result / actual result

User Avatar should not result in a 404 error.

**Comment by marcemarc** [comment]
@robertjf just thought about the origin of the redirect.... do you have SEO checker installed or similar? Have found this lowercases the urls for images etc

**Comment by robertjf** [comment]
@marcemarc I'll take a look at that - we do indeed have it installed.

**Comment by robertjf** [comment]
@marcemarc turns out that is indeed the case!  Turning off "Enable url rewriting" in the SEO Checker General Settings fixed the issue:

![image](https://user-images.githubusercontent.com/818101/123525562-fd110180-d714-11eb-88e0-1e46651d4fbf.png)
