### ISSUE TITLE
v9-beta0004: Can't use AddUnique and consume scoped dependencies at the same time

### ISSUE THREAD

**Issue by mattbrailsford** [umbraco/Umbraco-CMS#10548]
### Which *exact* Umbraco version are you using? For example: 8.13.1 - don't just write v8

v9.0.0-beta004

### Bug summary

Registering unique services are always registered as singleton and so you can't access transient or scoped services within them.

### Specifics

I'm creating a service in v9 which needs to be able to query for content and so I a have a dependency on the `IPublishedContentQuery` interface. At the same time, I need my class to be replaceable so that developers can swap the implementation and so I register is using `AddUnique`

Unfortunately this setup is not possible as `IPublishedContentQuery` is registered as a scoped dependency and `AddUnique` ALWAYS registers the given service as a singleton and so .NET Core blows up on boot with the error.

    Cannot consume scoped service 'Umbraco.Cms.Core.IPublishedContentQuery' from singleton 'Vendr.Umbraco.Extractors.IUmbracoProductNameExtractor'.

I'm personally not sure why `IPublishedContentQuery` needs to be scoped as this shouldn't be specific to the given request. Unfortunately I can't find any other way of fetching published content that would work outside of a scoped dependency.

### Steps to reproduce

Create a service that consumes the `IPublishedContentQuery` interface and register is with the DI container using `AddUnique`. On application boot the error will be displayed.

### Expected result / actual result

`IPublishedContentQuery` shouldn't be a scoped dependency and so no error should be thrown, or, there should be some other way of querying for content that doesn't need to be scoped.

**Comment by bergmania** [comment]
@Shazwazza do you see any reason `PublishedContentQuery` cant inject `IPublishedSnapshotAccessor` instead of `IPublishedSnapshot` and thereby open up for `IPublishedContentQuery` and `UmbracoHelper` is registered as singletons?

**Comment by Shazwazza** [comment]
Have replied with review here: https://github.com/umbraco/Umbraco-CMS/pull/10551#pullrequestreview-700291297
