### ISSUE TITLE
when resolving UmbracoHelper in custom middleware DI throws NullReferenceException

### ISSUE THREAD

**Issue by vmachacek** [umbraco/Umbraco-CMS#10540]
### Which *exact* Umbraco version are you using? For example: 8.13.1 - don't just write v8

9.0.0-beta0004

### Bug summary

When I'm trying to resolve `UmbracoHelper` in custom middleware I get NullReferenceException in umbraco infrastructure code. 

registration:
```
app.UseUmbraco()
      .WithMiddleware(u =>
    {
        u.WithBackOffice();
        u.WithWebsite();
        u.AppBuilder.MapWhen(ctx => ctx.Request.Path.StartsWithSegments("/robots.txt"),
                        b => b.UseMiddleware<RobotsTxtMiddleware>());
    })
    .WithEndpoints(u =>
    {
        u.UseInstallerEndpoints();
        u.UseBackOfficeEndpoints();
        u.UseWebsiteEndpoints();
});
```

middleware:
```
public class RobotsTxtMiddleware
    {
        const string Default =
            @"User-Agent: *\nAllow: /";

        private readonly RequestDelegate next;

        public RobotsTxtMiddleware(RequestDelegate next)
        {
            this.next = next;
        }

        public async Task InvokeAsync(
            HttpContext context,
            UmbracoHelper uHelper)
        {
            ....
        }
    }
```

### Steps to reproduce

- dotnet new 
- add middleware
- register middleware
- go to /robots.txt
- see exception

### Expected result / actual result

expected: insance of UmbracoHelper to be resolved. 

actual: NullReferenceException is thrown in infrastructure code

**Comment by bergmania** [comment]
Hi @vmachacek, I just looked into this, and it makes good sense. 

The `UmbracoHelper` requires `UmbracoContext` to be initialized, but it is not because "/robots.txt" is considered a client-side request.

What do you need from `UmbracoHelper`? 

There are a couple of possible workarounds. It would be very bad for performance if we had to initialize `UmbracoContext` for all client requests.

**Comment by vmachacek** [comment]
My main objective is to generate sitemap.xml based on latest published content and also robots.txt based at the root of umbraco content. The root node have property which contains contents for robots.txt in a text field.

The respective middlewares are registered with `builder.AppBuilder.MapWhen` with condition on the url, so they wont kick in during processing of irrelevant requests.

I understand creating `UmbracoHelper` after calling `EnsureUmbracoContext` is expensive operation, so I will cache it in the middleware. 

This is what I ended up with 

```
public async Task InvokeAsync(
            HttpContext context,
            IUmbracoContextFactory contextFactory, 
            IServiceProvider provider
            )
        {
            using (var uContext = contextFactory.EnsureUmbracoContext())
            {
                var uHelper = provider.GetRequiredService<UmbracoHelper>();

....
```

this solved my issue
