### ISSUE TITLE
v9-beta004: TypeFinder only searches assemblies that reference Umbraco

### ISSUE THREAD

**Issue by mattbrailsford** [umbraco/Umbraco-CMS#10554]
### Which *exact* Umbraco version are you using? For example: 8.13.1 - don't just write v8

v9.0.0-beta004

### Bug summary

In Umbraco v8 it was possible to use the TypeFinder to locate types across any assembly, however it appears that in v9 the default implementation only searches assemblies that hold a reference to Umbraco core dll.

### Specifics

In Vendr we have a series of custom collection builder implementations that should be dynamically populated by looking for types in assemblies that are decorated with a specific attribute. This used to work in v8 where I we could define our collection builder and then register it with the composer using Umbraco's TypeFinder to auto look up these types (these types could be created by me or 3rd parties).

In v9 however, this doesn't appear to work the same. In Vendr we have some of these types defined in our core project Vendr.Core and some in another project Vendr.Umbraco. When loading my site and checking the collection it appears that only the ones defined in Vendr.Umbraco have been found. On deeper investigation I believe this is because the TypeFinder uses an `IAssemblyProvider` to know which assemblies to search though, which appears to have a default implementation via `DefaultUmbracoAssemblyProvider` which only searches assemblies that themselves have a reference to the Umbraco core dll, which Vendr.Core does not.

I can test this to an extent by explicitly passing the type finder a list of assemblies to search, and when I do that, it does indeed find those types. Unfortunately, as types may be implemented by third parties, I can't explicitly list the assemblies to search and so ideally I need the type finder to search all assemblies in the bin folder (which I believe is what v8 used to do?)

### Steps to reproduce

Define some types in an assembly that doesn't reference Umbraco. Then use the type finder to try and locate those types and non of them will be found.

### Expected result / actual result

I was expecting that the type finder would search all DLLs and not just those that reference Umbraco

**Comment by mattbrailsford** [comment]
Just confirming that in v8 there were no restrictions on the dlls searched https://github.com/umbraco/Umbraco-CMS/blob/d428a4543f33bb7094cf7db5f6b6fdc2d1de3063/src/Umbraco.Core/Composing/TypeFinder.cs#L99

**Comment by mattbrailsford** [comment]
The only way I've managed to get around this currently is to pass assemblies to the type finder. Given my comments earlier though that I don't know the assemblies that reference mine, I attempted to use the `FindAssembliesWithReferencesTo` from Umbraco, but this is internal so have had to do a dirty hack right now.

````csharp
    public class VendrAssemblyProvider
    {
        private readonly ILoggerFactory _loggerFactory;

        public VendrAssemblyProvider(ILoggerFactory loggerFactory)
        {
            _loggerFactory = loggerFactory;
        }

        public IEnumerable<Assembly> Assemblies
        {
            get
            {
                var a = typeof(global::Umbraco.Cms.Core.Constants).Assembly;
                var t = a.GetType("Umbraco.Cms.Core.Composing.FindAssembliesWithReferencesTo");
                var c = t.GetConstructors(BindingFlags.Instance | BindingFlags.NonPublic | BindingFlags.Public)[0];
                var finder = c.Invoke(new object[]{
                    new[] {
                        typeof(Core.Constants).Assembly
                    }, new[] {
                        "Vendr.Common",
                        "Vendr.Core"
                    },
                    true,
                    _loggerFactory
                });

                var m = t.GetMethod("Find");
                return (IEnumerable<Assembly>)m.Invoke(finder, Array.Empty<object>());
            }
        }
    }
````

**Comment by Shazwazza** [comment]
Type scanning is slow. Type scanning in v9 uses a much better approach which is directly borrowed from .netcore to scan plugins that we know are plugins which is substantially faster. IMO scanning every single assembly should definitely not be done. Seems like an easy solution is to create a PR to make FindAssembliesWithReferencesTo public?

**Comment by Shazwazza** [comment]
Also - TypeLoader is what is typically used for all plugins. This is because it avoids type scanning entirely on startup if there's already a known hash. This is how all plugins in umbraco work with type scanning. We only type scan for a single type: IDiscoverable. If your lib needs to type scan too I would recommend using TypeLoader if possible to avoid the physical assembly scan on every startup.

You could create your own instance of TypeLoader with your own instance of TypeFinder using your own instance of DefaultUmbracoAssemblyProvider. Then seems like you don't need to worry about FindAssembliesWithReferencesTo at all?

**Comment by mattbrailsford** [comment]
Ahhh, cool. I’ll review this tomorrow and if anything needs making public I’ll submit a PR.

Don’t mind it being a different approach as long as it is still possible some how. Just knowing it’s safe to open up some bits if needs be is what I needed 👍🏻

**Comment by Shazwazza** [comment]
I think just creating a new `DefaultUmbracoAssemblyProvider` with your own `entryPointAssembly`, passing this to a new instance of `TypeFinder` and passing that instance to `TypeLoader` will do what you want without having to expose any new public APIs.

**Comment by mattbrailsford** [comment]
I seem to recall there was a hard coded list of namespaces passed to the Assembly Finder but I don’t have the code at hand to check, but I’ll see what I find tomorrow. 

Thanks for the suggestion though, at least I know what the recommended approach should be 👍🏻

**Comment by mattbrailsford** [comment]
Ok, so looking through the classes you mention:

`TypeLoader` is sealed so can't be inherited, but I don't think it necessarily needs to be. The problem then though is that it's `CacheKey` is hard coded so whichever type loader runs first, is going to be an issue with the next type loader. 

I think reusing the `TypeFinder` class should be ok, but to implement a custom `AssemblyProvider` we will need to make `FindAssembliesWithReferencesTo` public or update the `DefaultUmbracoAssemblyProvider` provider to allow overriding the list of assembly names to look for as this is currently hard coded

    var finder = new FindAssembliesWithReferencesTo(new[] { _entryPointAssembly }, Constants.Composing.UmbracoCoreAssemblyNames, true, _loggerFactory);

So what would be the preference here?

We could make a `TypeLoaderBase` with an abstract `CacheKey` property and move most of the `TyperLoader` functionality to the base class? 

RE `AssemblyProvider`, would you rather make `FindAssembliesWithReferencesTo` public? Or tweak the provider interface to expose an overridable list of assemblies to look for?

**Comment by Shazwazza** [comment]
You should just be able to do this:

```cs
var assemblyLoader = new DefaultUmbracoAssemblyProvider(typeof(MyProjectType).Assembly, loggerFactory);

var typeFinder = new TypeFinder(loggerFactory.CreateLogger<TypeFinder>(),  assemblyLoader, ...);

var typeLoader = new TypeLoader(typeFinder, ....);
```

The cache key doesn't matter. This saves a giant type list and appends to it for new types found. TypeLoader maintains a single file for all types. It's fine, there's no reason to have multiple files and caches.  There shouldn't be any reason to change anything else.

Did you try the above?

**Comment by mattbrailsford** [comment]
I'll take a look, but `DefaultUmbracoAssemblyProvider` still has a hard coded list of assembly namespaces to look in 

https://github.com/umbraco/Umbraco-CMS/blob/v9/dev/src/Umbraco.Core/Composing/DefaultUmbracoAssemblyProvider.cs#L36

**Comment by mattbrailsford** [comment]
Tried taking a bit of a look at this and was struggling a little. Given this is all needed within the `Configure` startup phase we can't inject any dependencies at that point so creating the TypeFinder + TypeLoader requires the instantiation of a lot of dependencies, or the ability to locate those from some already instantiated instances somewhere (which I don't know where to get them).

I think if this is the recommended way of achieving this, we may need some helpers to create "custom type loader" configurations.

**Comment by Shazwazza** [comment]
Yes if you need to use this during configuration to find types to register in DI then it's not easy and we need to expose more startup things on the IUmbracoBuilder. I just tried this and made some tweaks to make this possible without having to new-up a bunch of your own services.  There's still some code to setup but at least the required services are there for you. Some other changes are required too but this is all good and showed that some dependency chains aren't quite right. 

I'll post a solution soon based on a new branch.

**Comment by Shazwazza** [comment]
OK, lots of work done here: https://github.com/umbraco/Umbraco-CMS/pull/10646

**Comment by mattbrailsford** [comment]
Awesome stuff. I’ll take a look next week. Thanks for jumping on this 🙏

**Comment by mattbrailsford** [comment]
@Shazwazza don't suppose there is anywhere PR's automatically get compiled to is there? Or do I need to pull and compile the source?

**Comment by nul800sebastiaan** [comment]
@mattbrailsford Have a look at the PR - there's links to the build server which is public:

![image](https://user-images.githubusercontent.com/304656/125315342-52652980-e337-11eb-8eac-43b7660b7c3d.png)

From there you can download the PR results. 

I know that we also have the "Nightly" builds but I'm not sure what triggers one of those https://our.umbraco.com/documentation/UmbracoNetCoreUpdates#umbraco-9-nightly-builds, probably merge to `v9/dev`, so until it's merged the output on the build server should work for testing. 

You can download the nupkg files from the "2 Published" link, DevOps is not making it very obvious where the artifacts are.. 

![image](https://user-images.githubusercontent.com/304656/125315710-abcd5880-e337-11eb-956e-b14416506474.png)

**Comment by nul800sebastiaan** [comment]
Oh and to install from downloaded packages, you can use, for example, `dotnet nuget add source c:\packages` - https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-nuget-add-source#examples 

Then you can pick your source in VS or your IDE to be the local source.

**Comment by mattbrailsford** [comment]
Cool cool. I’ll get that tested tomorrow now. 👍🏻

**Comment by mattbrailsford** [comment]
Ok, so I wrapped the code from this post https://github.com/umbraco/Umbraco-CMS/issues/10554#issuecomment-877486106 and put it into a factory which now makes my code like this 

![image](https://user-images.githubusercontent.com/527305/125457314-46953c20-f1e9-4e78-bed4-43d9a34bde10.png)

And it does indeed appear to find my types and create a hash in the TEMP folder

![image](https://user-images.githubusercontent.com/527305/125457243-a2326f51-bf5e-4a4b-8f34-22873e37e54d.png)

Not sure if there is anything else you need me to check?

**Comment by Shazwazza** [comment]
Thanks @mattbrailsford , so you just tested with the custom code but not with the configuration option?

**Comment by mattbrailsford** [comment]
@Shazwazza yea, given it wouldn’t be a workable solution for Vendr on the whole. Can give it a try though as a test just to see if it works?

**Comment by Shazwazza** [comment]
But did you see my comment about HostStartup? With that you can add your own custom configuration values without relying on the end user to include them. These can even be hard coded values - such as an assembly entry point.

**Comment by mattbrailsford** [comment]
@Shazwazza ok, I’ll take another look tomorrow 👍🏻

**Comment by bergmania** [comment]
@mattbrailsford, did you find a solution so this issue can be closed?

**Comment by bergmania** [comment]
I will close this for now, we can reopen if it is still a problem
