### ISSUE TITLE
CurrentPage issue

### ISSUE THREAD

**Issue by vishnukum-code** [umbraco/Umbraco-CMS#10569]
### Which *exact* Umbraco version are you using? For example: 8.13.1 - don't just write v8

9

### Bug summary

When i try to use CurrentPage for getting child node in controller's action it's throwing an exception is ("No UmbracoRouteValues feature was found in the HttpContext")

![CurrentPageIssue](https://user-images.githubusercontent.com/77272103/124096907-aab74400-da78-11eb-8e23-760e22ab8ac5.png)

### Steps to reproduce

![Umbraco9Issue](https://user-images.githubusercontent.com/77272103/124097042-cae70300-da78-11eb-9200-dc2de4e6b5f7.png)

**Comment by bergmania** [comment]
Hi @vishnukum-code 

Can you post the entire controller. I have too little info to reproduce.

**Comment by vishnukum-code** [comment]
hello @bergmania here you can see all of my controller code :-

using Microsoft.AspNetCore.Mvc;
using Umbraco.Cms.Core.Cache;
using Umbraco.Cms.Core.Logging;
using Umbraco.Cms.Core.Routing;
using Umbraco.Cms.Core.Services;
using Umbraco.Cms.Core.Web;
using Umbraco.Cms.Infrastructure.Persistence;
using Umbraco.Cms.Web.Website.Controllers;
using Partner.AppCode.Model.PartialViewModels;
using Partner.AppCode.Services;
using System.Linq;
using Umbraco.Extensions;
using System;

namespace Partner.Controllers
{
    public class HeaderController : SurfaceController
    {
        private readonly ISettingService _settingService;

        public HeaderController(IUmbracoContextAccessor umbracoContextAccessor,
            IUmbracoDatabaseFactory databaseFactory,
            ServiceContext services,
            AppCaches appCaches,
            IProfilingLogger profilingLogger,
            IPublishedUrlProvider publishedUrlProvider,ISettingService settingService
            )
            : base(umbracoContextAccessor, databaseFactory, services, appCaches, profilingLogger, publishedUrlProvider)
        {
            _settingService = settingService;
        }
        [HttpGet]
        public ActionResult Render()
        {
            var navigation = _settingService.GetNavigation();
            if (navigation == null) return null;

            var vm = new HeaderViewModel(navigation, null)
            {
                Current = navigation
            };

            return PartialView("Navbar",vm);
        }
        [HttpGet]
        public ActionResult SubNavRender()
        {
            try
            {
                var HideList = CurrentPage.AncestorsOrSelf().Where(x => x.HasProperty("hideSubnav") && x.Value<bool>("hideSubnav") == true).ToList();
                if (HideList.Any() == true)
                {
                    return null;
                }
                //var items = CurrentPage.AncestorOrSelf(2).Children.Where(x => x.IsVisible()).Where(x => x.IsHiddenInSubnav() == false).ToList();
                //var vm = new SubnavViewModel(CurrentPage)
                //{
                //    Title = CurrentPage.Name,
                //    Items = items
                //};

                return PartialView("SubNavBar");
            }
            catch (Exception ex)
            {
                return null;
            }
        }
    }
}

**Comment by nikolajlauridsen** [comment]
Hey @vishnukum-code, it looks like you're trying to use child actions, which are no longer a thing in netcore, and therefore Umbraco V9, I'd recommend using [view components](https://docs.microsoft.com/en-us/aspnet/core/mvc/views/view-components?view=aspnetcore-5.0) instead. 

To make extra sure I tried creating a surface controller which received a form where I could access the `CurrentPage` with no issue, so I don't think this is a bug, I think it's intentional, generally speaking, surface controllers are only for post backs now, I also found [this forum post](https://our.umbraco.com/forum/umbraco-9/105872-render-action-from-surface-controller#comment-330149)  where Marc Goodson does a good job explaining it.
