### ISSUE TITLE
Is the dotnetcore version dead?

### ISSUE THREAD

**Issue by bjorn-ali-goransson** [umbraco/Umbraco-CMS#10586]
### Which *exact* Umbraco version are you using? For example: 8.13.1 - don't just write v8

1

### Bug summary

I'm really interested in checking out the .NET Core version, but barely seeing any development happening ...

Is there an unofficial branch somewhere? Is there something which I have missed?

### Steps to reproduce

Sorry for barging in like this.

**Comment by nul800sebastiaan** [comment]
Hi @bjorn-ali-goransson, it seems like you missed a lot, we're almost ready to publish a release candidate of version 9: https://umbraco.com/blog/coming-up-umbraco-9-release-candidate/

Tip: at the bottom of that page you can also sign up for our newsletter to get regular updates of what we're up to! 😉

**Comment by nul800sebastiaan** [comment]
Ps. `[v9/dev](https://github.com/umbraco/Umbraco-CMS/tree/v9/dev)` is the branch. 👍
