### ISSUE TITLE
8.15RC Multiple actions were found that match the request: GetByIds on type Umbraco.Web.Editors.EntityController

### ISSUE THREAD

**Issue by nzdev** [umbraco/Umbraco-CMS#10580]
### Which *exact* Umbraco version are you using? For example: 8.13.1 - don't just write v8

8.15RC

### Bug summary

Content fails to load in the content tree with error: 
![image](https://user-images.githubusercontent.com/834725/124224803-72883200-db5a-11eb-84d5-38257f37d3aa.png)

### Specifics

```
An error occurred
Multiple actions were found that match the request: GetByIds on type Umbraco.Web.Editors.EntityController GetByIds on type Umbraco.Web.Editors.EntityController GetByIds on type Umbraco.Web.Editors.EntityController

Exception Details
System.InvalidOperationException: Multiple actions were found that match the request: GetByIds on type Umbraco.Web.Editors.EntityController GetByIds on type Umbraco.Web.Editors.EntityController GetByIds on type Umbraco.Web.Editors.EntityController
Stacktrace
at System.Web.Http.Controllers.ApiControllerActionSelector.ActionSelectorCacheItem.SelectAction(HttpControllerContext controllerContext)
   at Umbraco.Web.WebApi.ParameterSwapControllerActionSelector.SelectAction(HttpControllerContext controllerContext) in D:\a\1\s\src\Umbraco.Web\WebApi\ParameterSwapControllerActionSelector.cs:line 89
   at System.Web.Http.ApiController.ExecuteAsync(HttpControllerContext controllerContext, CancellationToken cancellationToken)
   at System.Web.Http.Dispatcher.HttpControllerDispatcher.<SendAsync>d__15.MoveNext()
```

### Steps to reproduce

Click on a node in the content tree

### Expected result / actual result

Node loads

**Comment by nul800sebastiaan** [comment]
Hey there @nzdev - I will need a few more words from you please, of course we tested clicking on nodes in the content tree a lot and I can't repro the problem! If you have some more info on how to reproduce I'm all ears, for now I'll close this one though.

**Comment by nathanwoulfe** [comment]
Possibly related - I've seen similar the last couple of days when working on some Plumber stuff on 8.13.1. Intermittently, and not the same endpoint as @nzdev, but the same error. Resolved by restarting the site, until it potentially happens again...

Absolutely do not have multiple actions matching the erroneous request, was a controller with one method only.
