### ISSUE TITLE
8.15-RC: Install fails. could not load assembly "MessagePack"...

### ISSUE THREAD

**Issue by KevinJump** [umbraco/Umbraco-CMS#10587]
### Which *exact* Umbraco version are you using? For example: 8.13.1 - don't just write v8

8.15.0-rc

### Bug summary

When Installing Umbraco 8.15-RC via nuget and visual studio the web install process fails with the message 

> Could not load file or assembly 'MessagePack, Version=2.2.0.0, Culture=neutral, PublicKeyToken=b4a0369545f0a1be' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)

### Steps to reproduce

Visual studio v16.10.2

- Visual Studio New ASP.NET Web Application (.Net Framework)
   - Framework : .Net Framework 4.7.2
   - Create Empty
-  install umbraco via nuget 
   -  `install-package UmbracoCms -pre`
- build project
- view in browser
- step though install process
- "Install" (not customize so SQL with starter kit)

error is shown 
![image](https://user-images.githubusercontent.com/431231/124276295-807a8a80-db3b-11eb-80cd-00630a625f9b.png)

### Expected result / actual result

installation process should work.

**Comment by abjerner** [comment]
Hi Kevin,

I also spotted this earlier today. Unfortunately there is not much that can be done for the RC, but the dependencies should be fixed for the next release:

https://github.com/umbraco/Umbraco-CMS/commit/6816ae7ca41fb825b54dd23c9ffdfb1de32722a2

**Comment by KevinJump** [comment]
so running : 
```
update-package MessagePack -version 2.2.85
```

should make it OK ?

**Comment by abjerner** [comment]
Yes, for the first dependency gone wrong. If you fix that one, and try again, you'll see a similar error for K4os.Compression.LZ4. So try something like:

``` 
Install-Package K4os.Compression.LZ4 -version 1.1.11
```

I haven't tested this last bit, but seeing Seb's commit, I think that should fix it.

**Comment by KevinJump** [comment]
👍 yep - as long as you do that before you install it all works

**Comment by nul800sebastiaan** [comment]
Thanks for jumping in @abjerner! Fixed for the final release indeed. And now added to our checklist is: test a NuGet install and upgrade 😅
