### ISSUE TITLE
Cannot migrate from Umbraco 7 to Umbraco 8 with v8.14

### ISSUE THREAD

**Issue by simonech** [umbraco/Umbraco-CMS#10609]
### Which *exact* Umbraco version are you using? For example: 8.13.1 - don't just write v8

8.14

### Bug summary

When trying to upgrade from Umbraco v7.15.5 to v8.14.0 (and .1), it's not possible to login to the old v7 DB anymore

### Specifics

The operation works fine with v8.13.1

### Steps to reproduce

- Install an empty/basic v8.14 site using VS
- Install v8
- replace the connection string to a DB with content from v7.15.5 and update the configuration status to 7.15.5
- launch the site: it will ask to login to Authorize the upgrade
- enter username and password of admin user of v7.15.5 db

### Expected result / actual result

I should be able to login.

Instead, I get a "login failed for user", and the HTTP response to the `PostLogin` is a 500 whose message is:
`Cannot find user with id 0`.

I've tried downgrading to 8.13.1 and everything works fine.
By looking at the code, it seems the problem was introduced with this PR https://github.com/umbraco/Umbraco-CMS/pull/10199 , specifically the commit https://github.com/umbraco/Umbraco-CMS/pull/10199/commits/ea669d623d1eaabde72457bee435ba53acf52a6b

The problem is that the admin in v7 has `id=0` while in v8 it is -1. So that code basically always returns null when user id is 0, making it impossible to login.

Fix is either remove the `id == default` part of the `if`or don't perform the check during an upgrade scenario.

Since this is a backport of a netcore fix, I suspect it will affect also v9, and you might not be able to upgrade from v7 to v9, even though probably it is not a recommended scenario,

**Comment by nul800sebastiaan** [comment]
@simonech Ouch! Yeah for all versions before 8 the default id of the first user was 0. I have asked if this was intentional and what we intend to do with it but I assume we can just remove `id == default ||` there!

**Comment by simonech** [comment]
I can send a PR if just removing is enough.
Otherwise, if you want to do it only during installation from v7 I guess it becomes a bit more complicated.
But if idea is not to allow migration from v7 to v9, that can stay in v9.

**Comment by nul800sebastiaan** [comment]
No I think it's just an oversight, so I'm checking with some people! It's definitely not to block people from upgrading although we only support migrating from v7 to v8, once that is done you should be able to migrate/upgrade to v9 as well. 👍

**Comment by nul800sebastiaan** [comment]
Happy for a PR of course, just don't know yet if there's something more to do than just remove that check! But it would be a good start I'd say. 🙂

**Comment by simonech** [comment]
Probably also need to fix the test that verifies it

-- 
Simone Chiaretta
Microsoft MVP ASP.NET - ASPInsider
Blog: http://codeclimber.net.nz
RSS: http://feeds2.feedburner.com/codeclimber
twitter: @simonech

On 8 July 2021 at 13:48:02, Sebastiaan Janssen ***@***.***)
wrote:

Happy for a PR of course, just don't know yet if there's something more to
do than just remove that check! But it would be a good start I'd say. 🙂

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/umbraco/Umbraco-CMS/issues/10609#issuecomment-876371934>,
or unsubscribe

**Comment by nul800sebastiaan** [comment]
Fixed in https://github.com/umbraco/Umbraco-CMS/pull/10622
