### ISSUE TITLE
Opening SVG in media shows media edit path

### ISSUE THREAD

**Issue by bjarnef** [umbraco/Umbraco-CMS#10605]
### Which *exact* Umbraco version are you using? For example: 8.13.1 - don't just write v8

 8.14.1

### Bug summary

I noticed on a Umbraco Cloud project when clicking link on an SVG file in media section in opens e.g. /umbraco/#/media/media/edit/1107 and not path to media. Preview of SVG image is shown in the browser though.

I checked another project on Umbraco v8.13.1, but I don't recall if it always has worked this way.
I wonder if `openSvg()` has changed this behaviour: https://github.com/umbraco/Umbraco-CMS/commit/ac4128d89e34750ae9e26317bb7286b3a8adf6df

Opening and image works as expected though, e.g. /media/8d87081be008216/building.jpg

### Steps to reproduce

Upload an SVG file in media section, save media and click the link in the "Links" box under Info tab.

**Comment by nul800sebastiaan** [comment]
Yes this is on purpose for security reasons so we wrap the svg in an `img` tag instead of just opening it and possibly executing any malicious javascript in it.

**Comment by bjarnef** [comment]
Ahh okay, it seems to open a new window replacing the document HTML. Refreshing this will however show the edit page in backoffice instead of refreshing resource. Not sure there are something to do about this.

However I noticed it has changed, so we don't have the checkered background, so you can see preview of a white SVG.
https://github.com/umbraco/Umbraco-CMS/pull/8007

I will report this in another PR.
