### ISSUE TITLE
Error deriving class from UmbracoApplication with latest version

### ISSUE THREAD

**Issue by CampanaP** [umbraco/Umbraco-CMS#10611]
### Which *exact* Umbraco version are you using? For example: 8.13.1 - don't just write v8

8.14.1

### Bug summary

We usually start up umbraco with the following classes for initialize the DI:

`    public class ApplicationStartUp : IUserComposer
    {
        public void Compose(Composition composition)
        {
        ... DI initialization
`
and for global.asax
`    public class CustomGlobal : UmbracoApplication
    {
        public void Init(HttpApplication application)
        {
            application.BeginRequest += Application_BeginRequest;
            application.EndRequest += Application_EndRequest;
        }
       .... application start, end methods with DI methods
`

With Umbraco 8.14 this worked fine, but on the latest minor version (8.14.1) the methods from the CustomGlobal class are executed before the application startup, so all the DI classes are not initialized.

Are we missing something?

### Specifics

Code compile without error but on runtime umbraco fail to boot.

### Steps to reproduce

ApplicationStartup.cs
![image](https://user-images.githubusercontent.com/33429416/124715064-d6b44880-df02-11eb-9998-f1eeef9d547b.png)
CustomGlobal.cs
![image](https://user-images.githubusercontent.com/33429416/124715097-e03db080-df02-11eb-95c6-2907003676a9.png)
Global.asax
![image](https://user-images.githubusercontent.com/33429416/124715139-ee8bcc80-df02-11eb-9397-6ce021684294.png)

On execution the cache object in CustomGlobal.cs is null

### Expected result / actual result

Umbraco starting normally

**Comment by nul800sebastiaan** [comment]
Absolutely nothing changed in that regard from 8.14 to 8.14.1 ([you can look at the compare if you're curious](https://github.com/umbraco/Umbraco-CMS/compare/release-8.14.0...release-8.14.1)).

I believe you've probably just been lucky in the order in which things got added so far. You might need to specify that you want this to run after your cache manager - https://our.umbraco.com/documentation/implementation/composing/#composebefore-and-composeafter

For any further questions, you can ask around on the forums where our friendly community can help you find the best solution for your requirements. 
Make sure to head on over to https://our.umbraco.com and ask follow up questions there! 👍
