### ISSUE TITLE
No last synced Id found, this generally means this is a new server/install. The server will build its caches and indexes, and then adjust its last synced Id to the latest found in the database and maintain cache updates based on that Id.

### ISSUE THREAD

**Issue by No1sBothered** [umbraco/Umbraco-CMS#10624]
### Which *exact* Umbraco version are you using? For example: 8.13.1 - don't just write v8

8.14.1

### Bug summary

When restarting Umbraco the following line is added to the log file:

No last synced Id found, this generally means this is a new server/install. The server will build its caches and indexes, and then adjust its last synced Id to the latest found in the database and maintain cache updates based on that Id.

This is not a new server/install.

Is this an indication of a wider issue?

### Specifics

Umbraco 8.14.1
Azure Web App
Azure SQL Database

### Steps to reproduce

Restart the Azure Web App

**Comment by nul800sebastiaan** [comment]
When you restart the azure web app, your temp data gets deleted, so that's a normal and expected that is will need to rebuild caches.

**Comment by No1sBothered** [comment]
OK thanks
