### ISSUE TITLE
v9-rc001 bug in UmbracoDictionaryTranslate method causes error in blocklist editor

### ISSUE THREAD

**Issue by KevinJump** [umbraco/Umbraco-CMS#10627]
### Which *exact* Umbraco version are you using? For example: 8.13.1 - don't just write v8

v9 rc001

### Bug summary

A bug in the UmbracoDictionaryTranslate method causes an object exception when viewing the block editor. 

**if**
one of the labels or descriptions of a doctype being using in the block editor begins with the `#` character but does not contain and `_`

```
System.IndexOutOfRangeException, System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e: Index was outside the bounds of the array.
Stacktrace
at Umbraco.Extensions.LocalizedTextServiceExtensions.UmbracoDictionaryTranslate(ILocalizedTextService manager, ICultureDictionary cultureDictionary, String text)
...
```

This is because there is a split method used in the UmbracoDictionaryTranslate function that does not then do a bounds check.

### Steps to reproduce

- create a new block list editor datatype. 
- include a doctype as a block
- save
- chanse a property label on the block doctype to start with a '#' 
- save the block doctype
- view the blocklist datatype

see the error

### Expected result / actual result

should not error. 
should fail silently ? and display the value as is e.g ` #textstring`

There might be a migration issue, v8 to v9 people might label a control `#custom/pageTitle`. however in v8 this needs to be `#custom_pageTitle` - ideally this would update but at the very least i suppose it should not error.

**Comment by nikolajlauridsen** [comment]
Fixed in #10628 🎉
