### ISSUE TITLE
Umbraco 9 (Dutch) translations are not shown everywhere

### ISSUE THREAD

**Issue by inetzo** [umbraco/Umbraco-CMS#10645]
### Which *exact* Umbraco version are you using? For example: 8.13.1 - don't just write v8

9.0.0-rc001

### Bug summary

In 9.0.0-rc001 and before, the translations for example the Save and Publish buttons are not shown. Some parts are translated, but some commonly used parts, like the save buttons, are not. The translations are in the XML file: https://github.com/umbraco/Umbraco-CMS/blob/4f06c1f33a54daf4752a439778626202960db68c/src/Umbraco.Web.UI.NetCore/umbraco/config/lang/nl.xml#L173

![afbeelding](https://user-images.githubusercontent.com/18665536/125130521-6c1d2b80-e101-11eb-9ea4-1e7921a349ee.png)

### Steps to reproduce

Set the user's language to Dutch. The "Save and Publish" button for example should show the translation "Opslaan en publiceren".

### Expected result / actual result

I would expect that translation in the XML file are used in the backoffice interface.

**Comment by nikolajlauridsen** [comment]
Hey @inetzo, thanks for letting us know, I've gone ahead and created a PR that fixes the issue here #10678, so it should be all patched up once that gets merged 😄
