### ISSUE TITLE
Grid Property Editor with AllowedDocType != [] in package.manifest results in corrupted [[]] rather than a string[]

### ISSUE THREAD

**Issue by mistyn8** [umbraco/Umbraco-CMS#10644]
### Which *exact* Umbraco version are you using? For example: 8.13.1 - don't just write v8

v9-rc001

### Bug summary

The packageManifest parser appears to correctly parses the gridEditors, however by the time we come to interact with the Add Content in the grid property editor the allowedDoctypes  Array has become corrupt.

### Specifics

package manifest
```
{
  "gridEditors": [
    {
      "name": "3 Values",
      "alias": "valuesCallToAction",
      "view": "/App_Plugins/DocTypeGridEditor/Views/doctypegrideditor.html",
      "render": "/App_Plugins/DocTypeGridEditor/Render/DocTypeGridEditor.cshtml",
      "icon": "icon-item-arrangement",
      "config": {
        "allowedDocTypes": [ "valuesCallToAction" ],
        "nameTemplate": "",
        "enablePreview": true,
        "viewPath": "/Views/Partials/Grid/Editors/DocTypeGridEditor/",
        "previewViewPath": "/Views/Partials/Grid/Editors/DocTypeGridEditor/Previews/",
        "previewCssFilePath": "",
        "previewJsFilePath": ""
      }
    }
  ]
}
```
```
@inject IManifestParser ManifestParser

@{ 
    foreach (var gridEditor in ManifestParser.Manifest.GridEditors)
    {
        //if (editors.Contains(gridEditor) == false) editors.Add(gridEditor);

        <p>@(JsonConvert.SerializeObject(gridEditor))</p>
    }
}
```
correctly shows the same as above..

but then at the Add Content stage in the grid property editor we see
```
allowedDoctypes = [[]]
```
![image](https://user-images.githubusercontent.com/12418214/125116520-c065e280-e0e4-11eb-976b-86a3e252f036.png)

### Steps to reproduce

Add a package.manifest file in App_plugins to include a gridEditor, with allowedDocTypes != []

### Expected result / actual result

allowedDoctypes is consistenty a `string[]`

---
_This item has been added to our backlog [AB#13512](https://dev.azure.com/umbraco/243e7927-03b2-44e2-908f-d4ac7ea5daaa/_workitems/edit/13512)_

**Comment by mistyn8** [comment]
Investigating a little more..

https://github.com/umbraco/Umbraco-CMS/blob/4f06c1f33a54daf4752a439778626202960db68c/src/Umbraco.Web.BackOffice/Controllers/BackOfficeController.cs#L262-L267

Seems to be where the array becomes '[[]]'

Testing
```
public string GetGridConfigJson()
        {
            return JsonConvert.SerializeObject(_gridConfig.EditorsConfig.Editors);
        }
```
returns the correct json

**Comment by mistyn8** [comment]
### Observe  the allowedDocTypes array serialisation...

**System.Text.Json.JsonSerializer**
```
public string GetGridConfigJsonSystem()
        {
            return s.JsonSerializer.Serialize(_gridConfig.EditorsConfig.Editors);
        }

```
```json
,{"Name":"3 Values",
"NameTemplate":null,"Alias":"valuesCallToAction",
"View":"/App_Plugins/DocTypeGridEditor/Views/doctypegrideditor.html",
"Render":"/App_Plugins/DocTypeGridEditor/Render/DocTypeGridEditor.cshtml",
"Icon":"icon-item-arrangement",
"Config":{"allowedDocTypes":[[]],"nameTemplate":"",
"enablePreview":true,"viewPath":"/Views/Partials/Grid/Editors/DocTypeGridEditor/",
"previewViewPath":"/Views/Partials/Grid/Editors/DocTypeGridEditor/Previews/",
"previewCssFilePath":"",
"previewJsFilePath":""}}
```

vs 

**NewtonSoft.Json**
```
public string GetGridConfigJson()
        {
            return JsonConvert.SerializeObject(_gridConfig.EditorsConfig.Editors);
        }
```
```json
{"name":"3 Values",
"nameTemplate":null,"alias":"valuesCallToAction",
"view":"/App_Plugins/DocTypeGridEditor/Views/doctypegrideditor.html",
"render":"/App_Plugins/DocTypeGridEditor/Render/DocTypeGridEditor.cshtml",
"icon":"icon-item-arrangement",
"config":{"allowedDocTypes":["valuesCallToAction"],"nameTemplate":"",
"enablePreview":true,"viewPath":"/Views/Partials/Grid/Editors/DocTypeGridEditor/",
"previewViewPath":"/Views/Partials/Grid/Editors/DocTypeGridEditor/Previews/",
"previewCssFilePath":"",
"previewJsFilePath":""}}
```

**Comment by mistyn8** [comment]
Bit sledgehammer.. but Startup.cs to replace globally with Newtonsoft.Json serializer?

```csharp
        public void ConfigureServices(IServiceCollection services)
        {
            services.AddControllers().AddNewtonsoftJson();
#pragma warning disable IDE0022 // Use expression body for methods
            services.AddUmbraco(_env, _config)
                .AddBackOffice()
                .AddWebsite()
                .AddComposers()
                .Build();
#pragma warning restore IDE0022 // Use expression body for methods

        }
```

**Comment by nikolajlauridsen** [comment]
Thanks a lot for reporting @mistyn8 and for the great investigation work.

This is indeed a bit of an odd one, but I found [this blog post](https://josef.codes/custom-dictionary-string-object-jsonconverter-for-system-text-json/) that seems to cover the same issue, it does indeed seem to be due to a difference in how newtonsoft and the built in serializer handles `Dictionary<string, object>`, although I'm really not sure what's the best way to solve this, I don't think it's necessarily a good idea to replace it globally with Newtonsoft

**Comment by mistyn8** [comment]
Though people might want to revert to the familiarity of Newtonsoft? ;-)

**Comment by mistyn8** [comment]
Slightly less sledgehammer approach with an angular interceptor, for just the gridConfig API endpoint.

```
using Microsoft.AspNetCore.Mvc;
using Umbraco.Cms.Core.Configuration.Grid;
using Umbraco.Cms.Web.Common.Controllers;
using Newtonsoft.Json;
using Microsoft.AspNetCore.Authorization;
using Umbraco.Cms.Web.Common.Authorization;
using Umbraco.Cms.Web.BackOffice.Controllers;
using Umbraco.Cms.Web.Common.Attributes;
using Umbraco.Extensions;

namespace www.Controllers
{
    [ApiController]
    [PluginController("AllowedEditorsFix")]
    [Route("umbraco/backoffice/AllowedEditorsFix/[controller]/[Action]")]
    public class GridController : UmbracoAuthorizedApiController
    {
        private readonly IGridConfig _gridConfig;

        public GridController(IGridConfig gridConfig)
        {
            _gridConfig = gridConfig;
        }

        //[Authorize(Policy = AuthorizationPolicies.BackOfficeAccess)]
        [HttpGet]
        public string GetGridConfigJsonNet()
        {
            return JsonConvert.SerializeObject(_gridConfig.EditorsConfig.Editors);
        }        
    }    
}
```
App_Plugins/AllowedEditorsFix/
```
angular.module('umbraco.services').config([
    '$httpProvider',
    function ($httpProvider) {

        $httpProvider.interceptors.push(['$q', function ($q) {
            return {
                'request': function (request) {
                    // Redirect any requests to built in content delete to our custom delete
                    if (request.url.indexOf("/umbraco/GetGridConfig") === 0) {
                        console.log("intercepting");
                        request.url = '/umbraco/backoffice/AllowedEditorsFix/Grid/GetGridConfigJsonNet'
                    }

                    return request || $q.when(request);
                }
            };
        }]);

    }]);
```
Package.Manifest
```
{
  "javascript": [
    "~/App_Plugins/TSD/AllowedEditorsFix/Js/allowedEditorsFix.resources.js"
  ]
}

```

**Comment by argentini** [comment]
On a related note, when I publish and deploy, *.manifest files return a 404, even if I add the mime types to the startup. They do work if the *.manifest file is in another path under wwwroot. What's weird is that other file types like *.js work fine within App_Plugins.

**Comment by nul800sebastiaan** [comment]
Sorry for the delay on this one, good thing @skttl pinged us about it as I agree this should work. It looks like @nikolajlauridsen found some converter code that might work but as I understand, it was complicated to implement. We'll have another look in our next sprint!

**Comment by nikolajlauridsen** [comment]
Hey all, I've taken another look at this, and after looking around for quite a while, I found a much simpler solution, a ResultFilter, this allows us to switch the output formatter over to `Newtonsoft` for the specific controllers/actions where we need to use it. This way people can still use the `System.Text.Json` serializer for output formatting if they so please. 

However I did notice another thing, that the `GetGridConfig` doesn't have the angular protection bit on the json response (the `)]}',` part), and it seems to me that it really should, since it's meant to be used with angular, so I've made a PR where I just apply the angular json formatter, this means that we get a `string[]` again, as expected. 

However I'd very much like some feedback on on whether adding the angular `)]}',` part, will mess things up for anyone, since that is not my intention, and if it does we'll go back to the normal json result, but with a newtonsoft json output formatter, but if it poses no challenges it would be nice to add that part as well. Thoughts?
