### ISSUE TITLE
Umbraco 9 - LoginProvider Duplicate Key

### ISSUE THREAD

**Issue by cleversolutions** [umbraco/Umbraco-CMS#10656]
### Which *exact* Umbraco version are you using? For example: 8.13.1 - don't just write v8

9 rc1

### Bug summary

When login from external provider, the second login you add throws an exception ```Cannot insert duplicate key row in object 'dbo.umbracoExternalLogin' with unique index 'IX_umbracoExternalLogin_LoginProvider'.``` I believe this index should be non-unique.

### Specifics

I've added an oidc external login provider to v9-rc1 so creatively called "Umbraco.oidc". It works great when the first user signs up; however it pops an exception when he second user signs up or connects their account to the external provider. 

I'm pretty sure LoginProvider column in umbracoExternalLogin table should not have a unique index on it.

This is the exception
```
SqlException: Cannot insert duplicate key row in object 'dbo.umbracoExternalLogin' with unique index 'IX_umbracoExternalLogin_LoginProvider'. The duplicate key value is (Umbraco.oidc). The statement has been terminated.
System.Data.SqlClient.SqlConnection.OnError(SqlException exception, bool breakConnection, Action<Action> wrapCloseInAction)
System.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, bool breakConnection, Action<Action> wrapCloseInAction)
System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, bool callerHasConnectionLock, bool asyncClose)
System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, out bool dataReady)
System.Data.SqlClient.TdsParser.Run(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj)
System.Data.SqlClient.SqlBulkCopy.RunParser(BulkCopySimpleResultSet bulkCopyHandler)
System.Data.SqlClient.SqlBulkCopy.CopyBatchesAsyncContinuedOnSuccess(BulkCopySimpleResultSet internalResults, string updateBulkCommandText, CancellationToken cts, TaskCompletionSource<object> source)
System.Data.SqlClient.SqlBulkCopy.CopyBatchesAsyncContinued(BulkCopySimpleResultSet internalResults, string updateBulkCommandText, CancellationToken cts, TaskCompletionSource<object> source)
System.Data.SqlClient.SqlBulkCopy.CopyBatchesAsync(BulkCopySimpleResultSet internalResults, string updateBulkCommandText, CancellationToken cts, TaskCompletionSource<object> source)
System.Data.SqlClient.SqlBulkCopy.WriteToServerInternalRestContinuedAsync(BulkCopySimpleResultSet internalResults, CancellationToken cts, TaskCompletionSource<object> source)
System.Data.SqlClient.SqlBulkCopy.WriteToServerInternalRestAsync(CancellationToken cts, TaskCompletionSource<object> source)
System.Data.SqlClient.SqlBulkCopy.WriteToServerInternalAsync(CancellationToken ctoken)
System.Data.SqlClient.SqlBulkCopy.WriteRowSourceToServerAsync(int columnCount, CancellationToken ctoken)
System.Data.SqlClient.SqlBulkCopy.WriteToServer(DataTable table, DataRowState rowState)
System.Data.SqlClient.SqlBulkCopy.WriteToServer(DataTable table)
NPoco.SqlBulkCopyHelper.BulkInsert<T>(IDatabase db, IEnumerable<T> list, SqlBulkCopyOptions sqlBulkCopyOptions)
NPoco.SqlBulkCopyHelper.BulkInsert<T>(IDatabase db, IEnumerable<T> list)
NPoco.DatabaseTypes.SqlServerDatabaseType.InsertBulk<T>(IDatabase db, IEnumerable<T> pocos)
NPoco.Database.InsertBulk<T>(IEnumerable<T> pocos)
Umbraco.Cms.Infrastructure.Persistence.Repositories.Implement.ExternalLoginRepository.Save(int userId, IEnumerable<IExternalLogin> logins)
Umbraco.Cms.Core.Services.Implement.ExternalLoginService.Save(int userId, IEnumerable<IExternalLogin> logins)
Umbraco.Cms.Core.Security.BackOfficeUserStore.UpdateAsync(BackOfficeIdentityUser user, CancellationToken cancellationToken)
Microsoft.AspNetCore.Identity.UserManager<TUser>.UpdateUserAsync(TUser user)
Microsoft.AspNetCore.Identity.UserManager<TUser>.AddLoginAsync(TUser user, UserLoginInfo login)
Umbraco.Cms.Web.BackOffice.Security.BackOfficeSignInManager.LinkUser(BackOfficeIdentityUser autoLinkUser, ExternalLoginInfo loginInfo)
Umbraco.Cms.Web.BackOffice.Security.BackOfficeSignInManager.AutoLinkAndSignInExternalAccount(ExternalLoginInfo loginInfo, ExternalSignInAutoLinkOptions autoLinkOptions)
Umbraco.Cms.Web.BackOffice.Security.BackOfficeSignInManager.ExternalLoginSignInAsync(ExternalLoginInfo loginInfo, bool isPersistent, bool bypassTwoFactor)
Umbraco.Cms.Web.BackOffice.Controllers.BackOfficeController.ExternalSignInAsync(ExternalLoginInfo loginInfo, Func<IActionResult> response)
Umbraco.Cms.Web.BackOffice.Controllers.BackOfficeController.RenderDefaultOrProcessExternalLoginAsync(AuthenticateResult authenticateResult, Func<IActionResult> defaultResponse, Func<IActionResult> externalSignInResponse)
Umbraco.Cms.Web.BackOffice.Controllers.BackOfficeController.Default()
Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor+TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, object controller, object[] arguments)
System.Threading.Tasks.ValueTask<TResult>.get_Result()
Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask<IActionResult> actionResultValueTask)
Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, object state, bool isCompleted)
Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(ref State next, ref Scope scope, ref object state, ref bool isCompleted)
Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, object state, bool isCompleted)
Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(ref State next, ref Scope scope, ref object state, ref bool isCompleted)
Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
Umbraco.Cms.Web.Website.Middleware.PublicAccessMiddleware.InvokeAsync(HttpContext context, RequestDelegate next)
Microsoft.AspNetCore.Builder.UseMiddlewareExtensions+<>c__DisplayClass6_1+<<UseMiddlewareInterface>b__1>d.MoveNext()
Umbraco.Cms.Web.BackOffice.Middleware.BackOfficeExternalLoginProviderErrorMiddleware.InvokeAsync(HttpContext context, RequestDelegate next)
Microsoft.AspNetCore.Builder.UseMiddlewareExtensions+<>c__DisplayClass6_1+<<UseMiddlewareInterface>b__1>d.MoveNext()
Microsoft.AspNetCore.Builder.Extensions.MapMiddleware.Invoke(HttpContext context)
Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
Microsoft.AspNetCore.Localization.RequestLocalizationMiddleware.Invoke(HttpContext context)
Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
SixLabors.ImageSharp.Web.Middleware.ImageSharpMiddleware.Invoke(HttpContext context)
Microsoft.AspNetCore.Diagnostics.StatusCodePagesMiddleware.Invoke(HttpContext context)
StackExchange.Profiling.MiniProfilerMiddleware.Invoke(HttpContext context) in C:\projects\dotnet\src\MiniProfiler.AspNetCore\MiniProfilerMiddleware.cs
Umbraco.Cms.Web.Common.Middleware.UmbracoRequestMiddleware.InvokeAsync(HttpContext context, RequestDelegate next)
Umbraco.Cms.Web.Common.Middleware.UmbracoRequestMiddleware.InvokeAsync(HttpContext context, RequestDelegate next)
Microsoft.AspNetCore.Builder.UseMiddlewareExtensions+<>c__DisplayClass6_1+<<UseMiddlewareInterface>b__1>d.MoveNext()
Umbraco.Cms.Web.Common.Middleware.PreviewAuthenticationMiddleware.InvokeAsync(HttpContext context, RequestDelegate next)
Microsoft.AspNetCore.Builder.UseMiddlewareExtensions+<>c__DisplayClass6_1+<<UseMiddlewareInterface>b__1>d.MoveNext()
Umbraco.Cms.Web.Common.Middleware.UmbracoRequestLoggingMiddleware.InvokeAsync(HttpContext context, RequestDelegate next)
Microsoft.AspNetCore.Builder.UseMiddlewareExtensions+<>c__DisplayClass6_1+<<UseMiddlewareInterface>b__1>d.MoveNext()
Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
```

### Steps to reproduce

This is hard to reproduce, you would need an OAuth and OIDC server. Likely easier if you just enable Google Authentication OAuth 2. In my case I'm connecting to our own OIDC/OAuth2 server using an extension to the IUmbracoBuilder as below

```
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authentication.OpenIdConnect;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.IdentityModel.Protocols.OpenIdConnect;
using Umbraco.Cms.Core.DependencyInjection;
using Umbraco.Cms.Web.BackOffice.Security;
using Umbraco.Extensions;
using System.Threading.Tasks;

public static class AuthenticationServerExtensions
{
    public static IUmbracoBuilder AddAuthenticationServer(this IUmbracoBuilder builder)
    {
        var authServerOptions = new AuthenticationServerOptions();
        builder.Config.GetSection(AuthenticationServerOptions.AuthenticationServer).Bind(authServerOptions);

        // create the autoLinkOptions with the OnAutoLinking action set
        var autoLinkOptions = new ExternalSignInAutoLinkOptions(
            autoLinkExternalAccount: true,
            defaultUserGroups: new string[] {"editor"}
        );
        var autoLinkAction = new AutoLinkAction();
        autoLinkOptions.OnAutoLinking = autoLinkAction.Action;

        builder.AddBackOfficeExternalLogins(backOfficeLoginOPtions =>
        {
            backOfficeLoginOPtions.AddBackOfficeLogin(new BackOfficeExternalLoginProviderOptions(
                "btn-success",
                "fa-cloud",
                autoLinkOptions,
                denyLocalLogin: authServerOptions.DenyLocalLogin,
                autoRedirectLoginToExternalProvider: authServerOptions.AutoRedirectLoginToExternalProvider
            ), backOfficeAuthOptions =>
            {
                backOfficeAuthOptions.AddOpenIdConnect("Umbraco.oidc", "City Account", openIdOptions =>
                {
                    // use cookies
                    openIdOptions.SignInScheme = CookieAuthenticationDefaults.AuthenticationScheme;

                    // pass configured options along
                    openIdOptions.Authority = authServerOptions.Authority;
                    openIdOptions.ClientId = authServerOptions.ClientId;
                    openIdOptions.ClientSecret = authServerOptions.ClientSecret;

                    // Use the authorization code flow
                    openIdOptions.ResponseType = OpenIdConnectResponseType.Code;
                    openIdOptions.AuthenticationMethod = OpenIdConnectRedirectBehavior.RedirectGet;

                    // map claims
                    openIdOptions.TokenValidationParameters.NameClaimType = "name";
                    openIdOptions.TokenValidationParameters.RoleClaimType = "role";
                    
                    openIdOptions.RequireHttpsMetadata = true;
                    openIdOptions.GetClaimsFromUserInfoEndpoint = true;
                    openIdOptions.SaveTokens = true;

                    // add scopes
                    openIdOptions.Scope.Add("openid");
                    openIdOptions.Scope.Add("email");
                    openIdOptions.Scope.Add("roles");

                    // options.SecurityTokenValidator = new JwtSecurityTokenHandler
                    // {
                    //     // Disable the built-in JWT claims mapping feature.
                    //     InboundClaimTypeMap = new Dictionary<string, string>()
                    // }; 

                    openIdOptions.UsePkce = true;

                    openIdOptions.Events.OnAuthorizationCodeReceived = (AuthorizationCodeReceivedContext context) => {
                        return Task.CompletedTask;
                    };

                    openIdOptions.Events.OnTokenValidated = (TokenValidatedContext) => {
                        return Task.CompletedTask;
                    };

                    openIdOptions.Events.OnUserInformationReceived = (UserInformationReceivedContext ctx) => {
                        return Task.CompletedTask;
                    };
                });
            });
        });
        return builder;
    }
}

```
Invoke in startup by adding ```AddAuthenticationServer()```  for example
```
services.AddUmbraco(_env, _config)
                .AddBackOffice()
                .AddWebsite()
                .AddComposers()
                .AddAuthenticationServer()
                .Build();
```

Link up one user. It should work great. Link up a second user and you get the exception.

### Expected result / actual result

It shouldn't toss an exception.

**Comment by Shazwazza** [comment]
Yes I think this is a bug, the unique index needs to be across login provider and user id I think.

**Comment by cleversolutions** [comment]
That makes sense. I’ll submit a PR tomorrow.

**Comment by keithswright** [comment]
Hi Guys, 

Thanks for fixing this issue. I just came across it today myself. 
However, when I checkout the source on the v9/dev branch, I don't see the fix. 

I think something went wrong with the merge:
Branch **cleversolutions/temp-10656** contained the changes to fix this issue
A new branch **cleversolutions/temp-10674** was branched off from **cleversolutions/temp-10656** and a new commit (acda7706bec0a6e038a438bc8f1856d0a080019c ) was added to remove the changes made on **cleversolutions/temp-10656**. 
Because both branches have been merged now to v9/dev, including the commit that reverts the changes on **cleversolutions/temp-10674**, the fix has been reverted out. 

My Apologies if I have missed something obvious and this is all nonsense.

**Comment by keithswright** [comment]
Yes, and looking at that PR on github, it looks fine.

But the PR was merged into the v9/dev branch. And when I checkout the head of the V9/dev branch and look at the code, I see the code from some, but not all of the commits in the PR. 

The changes made to add comments (0ca4dd176ca35a9d43d0c4db292a7c2a99a90942) are on v9/dev:

![image](https://user-images.githubusercontent.com/19530085/128906342-bbdfffbd-5e1a-4974-9886-966f6f6b43d8.png)

But the changes to the index (d4760f546794cc82ce65507d5b22ef2da5762f3d, d045003fb5ff352611b38d75fbe032be884cab6c) and the column length are not on V9/dev:

![image](https://user-images.githubusercontent.com/19530085/128906983-5e25a1e8-fff1-4d9b-8f63-1a724c5181ad.png)

![image](https://user-images.githubusercontent.com/19530085/128907183-f1b1b38c-039e-4742-a045-b2883913ceae.png)

And I believe its because this commit reverts the changes to the index and column length: acda7706bec0a6e038a438bc8f1856d0a080019c

**Comment by cleversolutions** [comment]
🤦‍♂️ That is exactly what happened. If Linus were reading this he would call me a dumb git lol. @Shazwazza will #10721 re-add this code, or should I submit a new PR?
Thanks,
Evan

**Comment by Shazwazza** [comment]
yes, I fixed up the changes and the correct values should be there, but please review. For example: 

https://github.com/umbraco/Umbraco-CMS/pull/10721/files#diff-3fdcbcc46f9fdf61a779626a8bba119f52dad113ce227e0614b196fe71731b55

and 

https://github.com/umbraco/Umbraco-CMS/pull/10721/files#diff-3d0ac4f8fe380fb06bfadd3bb4936a06c9d6ecfa7a4ebee02468711c9ca4d4b9

**Comment by cleversolutions** [comment]
I see my changes are still in there. In fact while I was reviewing the PR it got merged 😄 @keithswright if you look at v9/dev now you will see the fixes are there. I think now is a great time for me to pull v9/dev and validate that our custom external login provider still works. H5YR @Shazwazza!

**Comment by Shazwazza** [comment]
My PR https://github.com/umbraco/Umbraco-CMS/pull/10670 has just been merged to v9/dev so please test, feedback, etc... 

There is a breaking change in how setting up an external provider is done now which you will see. External provider options now correctly use IOptions so you can configure their options separately, via config, and in all the ways that IOptions work.

**Comment by keithswright** [comment]
Thanks for your help guys. 
Sorry to pollute this thread, but while I have you... This issue came up for me because I am trying to implement external login for **members**. It is a hacky solution at the moment, but it is working for us for the while we build other features. I was hoping the official external member login will be built in V9 by the time we go live (end of 2021). Do you guys think this might happen within this time frame? Because if not, I may have to put more effort towards building a more robust member external login ourselves.

**Comment by Shazwazza** [comment]
Unfortunately external login providers for members will probably not make it to 9.0.0 release since that feature isn't actually part of the CMS in v8. My own library called UmbracoIdentity filled this gap for v8 but that will be retired since this functionality will become directly available in v9.x at some stage. 

That said, it should be more than possible to make this work on your own since Umbraco 9.0.0 comes with all of the identity requirements for external logins: IMemberSignInManager/MemberSignInManager, IMemberManager/MemberManager.  Most of the concepts can be ported over from the aspnetcore examples for external logins (which are based on sign in manager and user manager, but are backed by EFCore providers... but the underlying provider will not matter).

**Comment by cleversolutions** [comment]
I have the same priority on the horizon (late 21 early 22 timeframe) of getting external sign in with members working on a number of sites. @Shazwazza want me to open a new issue to track this feature request?

**Comment by keithswright** [comment]
Thanks for the info guys!

**Comment by luke-barnett** [comment]
@keithswright I'm wanting to do the same thing, do you have any hints as to where to start so I can then follow my nose?

**Comment by keithswright** [comment]
Hi @luke-barnett 

What we ended up doing was kinda by-passing the umbraco authentication. 
We use Azure AD B2C for authentication

**Comment by keithswright** [comment]
Hi @luke-barnett 

We are using Umbraco in a headless way with a SPA (which is a whole other story) so it means that we can use Bearer tokens for authentication. I don't think this would work for you if you are using Umbraco to render your pages using razor.
But Ill describe what we have done (although still not in production yet), in case it is of any use to you.

We are using Azure AD B2C and we added a new authentication scheme, instead of using Umbraco's member authentication scheme.

We used this library:
https://github.com/AzureAD/microsoft-identity-web

and in our startup we added this, which is pretty much as per the documnetation:

```
services.AddAuthentication(JwtBearerDefaults.AuthenticationScheme)
                    .AddMicrosoftIdentityWebApi(options =>
                    {
                        _config.Bind("AzureAdB2C", options);

                        options.TokenValidationParameters.NameClaimType = "name";
                    },
                    options => { _config.Bind("AzureAdB2C", options); });
```

To secure a controller, we decorate with this:

`   
[Authorize(AuthenticationSchemes = JwtBearerDefaults.AuthenticationScheme)]
`

On the client side, our site is a SPA making API calls to Umbraco go get data.

To prompt for login, we use:

https://github.com/AzureAD/microsoft-authentication-library-for-js

This much all works great for restricting access and allowing someone log in externally. 
But we also needed an admin screen for members profiles and instead of rolling our own, we are trying out using Umbraco's. But because our authentication is totally external, Umbraco has no idea that these members exist.

Our current approach to this, broadly, is to expose a custom "members" API  from umbraco to Azure AD B2C.
So now, when someone logs in on Azure AD B2C, we make a call to umbraco to check if that member exists, if not, we create a new one. 
This custom API also take care of adding "external logins" to the user so that they can login with Google, facebook etc.

So far so good, but its all still in test and not in production until Q1 next year.

**Comment by cleversolutions** [comment]
I might be able to submit a PR to add external login support to members this fall.

**Comment by ashirafumiiro** [comment]
I also needed to get members from our Asp.Net core API and use the identity users (exposed via API endpoints) for umbraco members login. My first attempt was to implement `IMemberService` and replaced the Umbraco default implementation via services configuration. I was able to load the memmbers and the only issue I am struggling with is with `IMemberManager.ValidateCredentialsAsync()`. The `MemberSignInManager.PasswordSignInAsync` works fine though. Is this an approach that can work for my case in the meantime?

**Comment by pykos** [comment]
> Hi @luke-barnett
> 
> We are using Umbraco in a headless way with a SPA (which is a whole other story) so it means that we can use Bearer tokens for authentication. I don't think this would work for you if you are using Umbraco to render your pages using razor. But Ill describe what we have done (although still not in production yet), in case it is of any use to you.
> 
> We are using Azure AD B2C and we added a new authentication scheme, instead of using Umbraco's member authentication scheme.
> 
> We used this library: https://github.com/AzureAD/microsoft-identity-web
> 
> and in our startup we added this, which is pretty much as per the documnetation:
> 
> ```
> services.AddAuthentication(JwtBearerDefaults.AuthenticationScheme)
>                     .AddMicrosoftIdentityWebApi(options =>
>                     {
>                         _config.Bind("AzureAdB2C", options);
> 
>                         options.TokenValidationParameters.NameClaimType = "name";
>                     },
>                     options => { _config.Bind("AzureAdB2C", options); });
> ```
> 
> To secure a controller, we decorate with this:
> 
> ` [Authorize(AuthenticationSchemes = JwtBearerDefaults.AuthenticationScheme)]`
> 
> On the client side, our site is a SPA making API calls to Umbraco go get data.
> 
> To prompt for login, we use:
> 
> https://github.com/AzureAD/microsoft-authentication-library-for-js
> 
> This much all works great for restricting access and allowing someone log in externally. But we also needed an admin screen for members profiles and instead of rolling our own, we are trying out using Umbraco's. But because our authentication is totally external, Umbraco has no idea that these members exist.
> 
> Our current approach to this, broadly, is to expose a custom "members" API from umbraco to Azure AD B2C. So now, when someone logs in on Azure AD B2C, we make a call to umbraco to check if that member exists, if not, we create a new one. This custom API also take care of adding "external logins" to the user so that they can login with Google, facebook etc.
> 
> So far so good, but its all still in test and not in production until Q1 next year.

@keithswright we are developing a very similar app with a SPA front end, but I can not setup the member authentication via 
`
services.AddAuthentication(JwtBearerDefaults.AuthenticationScheme)
                    .AddMicrosoftIdentityWebApi(options =>
                    {
                        _config.Bind("AzureAdB2C", options);

                        options.TokenValidationParameters.NameClaimType = "name";
                    },
                    options => { _config.Bind("AzureAdB2C", options); });
`
Would you be willing to elaborate on your solution or maybe get in touch?

**Comment by keithswright** [comment]
Hi @pykos 

Startup.cs configuration is exactly what worked for us. However, ADB2C proved to be too much of a nightmare for us to configure using the giant XML files etc and swapped over to Identity Server. So now we just use:

```
            services.AddAuthentication(IdentityConstants.ApplicationScheme)
                    .AddJwtBearer("Bearer", options =>
```

Something that comes to mind is that you might need to decorate your controllers with the [Authorize] attribute and the name of the authentication scheme that you want to use for that request. Your controllers might still be using the default umbraco authentication scheme. There might be a more convenient way to do this, but this is what worked for me:

I have created a custom default render controller according to this tutorial and decorated it accordingly:
https://our.umbraco.com/documentation/reference/routing/custom-controllers#replace-umbracos-default-rendercontroller

All of our public (non-backoffice) urls need to be secured with JwtBearerDefaults.AuthenticationScheme. But we don't necessarily want to force a user to be logged in either (some of the site is publicly available), so we use a combination of [Authorize] and [AllowAnonymous] on this default controller. If you have no publicly available content, remove the [AllowAnonymous] attribute:

It looks something like this (i have removed some code for legibility, so it might not compile as it is written here):

`

    [Authorize(AuthenticationSchemes = JwtBearerDefaults.AuthenticationScheme)]
    [AllowAnonymous]
    public class CustomRenderController : RenderController
    {
        public CustomRenderController(ILogger<RenderController> logger, ICompositeViewEngine compositeViewEngine, IUmbracoContextAccessor umbracoContextAccessor)
            : base(logger, compositeViewEngine, umbracoContextAccessor)
        {
        }
    }

`

Hope this solves you issue

**Comment by gdiazderadaa** [comment]
> I might be able to submit a PR to add external login support to members this fall.

Can I just ask if this has made it to any release and if so, which one is it? I'm facing the issue in 9.0.1

Thanks

**Comment by keithswright** [comment]
I think it was 9.3. 
We have it working now and we are on 9.3.1

https://umbraco.com/blog/umbraco-93-release

**Comment by gdiazderadaa** [comment]
> I think it was 9.3. We have it working now and we are on 9.3.1
> 
> https://umbraco.com/blog/umbraco-93-release

Nice one, thanks!
