### ISSUE TITLE
Member's username with backslash not supported (domain\username format)

### ISSUE THREAD

**Issue by adamhearn** [umbraco/Umbraco-CMS#10665]
### Which *exact* Umbraco version are you using? For example: 8.13.1 - don't just write v8

9.0.0-rc001

### Bug summary

I have a site that I'm updating to v9 and am seeing an issue with Members. The problem is that having a backslash in the username field causes the member to be uneditable.

### Specifics

I use IIS with Windows Authentication enabled and record (programatically) the connecting user as a member using the Name property of the authenticated Identity. This is in the format DOMAIN\username. The members show was per:

![Web capture_13-7-2021_93045_localhost](https://user-images.githubusercontent.com/13589850/125418921-d7f736c3-8cd2-4bb6-9e0d-7799df5c19aa.jpeg)

Whenever I edit the member I get the following message and the Save button spins forever:

![image](https://user-images.githubusercontent.com/13589850/125441777-40054067-ce71-4828-83a6-147bc84b8dae.png)

Prior releases of v9 (beta) didn't work in various areas but I don't recall that I was unable to edit one of the existing member entries in my DB.

### Steps to reproduce

Migrate a v8 database content with member's usernames in the form domain\username to v9

Edit the member

### Expected result / actual result

Username should support the form provided by User.Identity.Name

**Comment by nul800sebastiaan** [comment]
Just to confirm, `test\jane` is a perfectly valid login that can indeed be updated.

**Comment by nul800sebastiaan** [comment]
And in v9 I indeed get an `Invalid username` 

![image](https://user-images.githubusercontent.com/304656/125452420-13566799-a3b8-45ff-8a92-1cfa867966ed.png)

For some background: we moved from ASP.NET Membership to .NET Identity which should explain the difference. Probably need to look into how domain logins are supposed to be stored in Identity.

**Comment by adamhearn** [comment]
Usernames are validated in the underlying framework (IUserValidator::ValidateUserName) where the following characters are [by default] allowed:

`abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789-._@+`

It would simple to add support for the backslash by adding the following to ConfigureMemberIdentityOptions::Configure

```
// Support Down-Level Logon Name format names
options.User.AllowedUserNameCharacters += "\\";
```

Of course the value c/should be taken from app options but presently there's only a config section for Member Password so this would need to be a new section with supporting class injected into the ConfigureMemberIdentityOptions class.

I could provide the change as required but let me know what is wanted.

**Comment by nikolajlauridsen** [comment]
It seems reasonable to me to add the character like you suggested since it's allowed in V8. 

There is also a `UserPasswordConfigurationSettings` where it could be added, but since this has to do with user names, it might make more sense to have it on the `SecuritySettings` itself? But at the end of the day, I think the specific character "\\" should just be allowed by default, since it was in V8. 

I'm not sure if there is any reason not to do this, any thoughts @Shazwazza?
