### ISSUE TITLE
External Login Provider Icons Not Displayed

### ISSUE THREAD

**Issue by cleversolutions** [umbraco/Umbraco-CMS#10674]
### Which *exact* Umbraco version are you using? For example: 8.13.1 - don't just write v8

v9/dev

### Bug summary

Icons for External Login Providers do not render on the login page. 

### Specifics

The external login provider icon is rendered to the page accessing the SocialIcon property of the external login provider's properties for example
```<i class="fa" ng-class="login.properties.SocialIcon"></i>```

The external login provider's does not contain a SocialIcon property, it should be Icon. This is rendered further down the page in a script tag 
```
providers: [{..."properties":{"ButtonStyle":"btn-success","Icon":"fa-cloud", ...}}]
```

### Steps to reproduce

Add an external login provider and load the login page. The external login providers won't have nice icons on them.

### Expected result / actual result

The external login providers should have nice icons beside them.

**Comment by emma-hq** [comment]
Hey @cleversolutions 

Thanks for raising this issue! I'll take a look today and see what we can do. have a chat with some of the front end team and see how to proceed. 

Emma

**Comment by emma-hq** [comment]
Hey @cleversolutions 

I can already see that you've worked on a solution so a massive #h5yr for that! 👍 I'll label accordingly and we'll take a look at your solution and see about getting this sorted.

Thanks again for your contribution, both here and on the pr,

Emma

**Comment by cleversolutions** [comment]
Thanks @emma-hq, I always like to bring solutions not problems 😄
