### ISSUE TITLE
UserService.SavedUserGroup event returns wrong list of AddedUsers when removing user

### ISSUE THREAD

**Issue by inetzo** [umbraco/Umbraco-CMS#10679]
### Which *exact* Umbraco version are you using? For example: 8.13.1 - don't just write v8

8.14.1 and below

### Bug summary

When a user is removed from the Usergroup and the UserService.SavedUserGroup event is fired, the property AddedUsers returns a list of all backoffice users. When a user is added to the group, it only contains the added users.

![afbeelding](https://user-images.githubusercontent.com/18665536/125621177-972aa69c-da4d-47b4-bf19-69bd00a0ec54.png)

![afbeelding](https://user-images.githubusercontent.com/18665536/125621210-8a93b7af-6c33-4ef5-87f5-1efaab8c2d67.png)

![afbeelding](https://user-images.githubusercontent.com/18665536/125621234-143d4087-2529-4833-8104-10620625c9cb.png)

### Steps to reproduce

Add an component to catch the UserService.SavedUserGroup event:

```
    public class UserGroupComponent: IComponent
    {

        public UserGroupComponent()
        {

        }

        public void Initialize()
        {
            UserService.SavedUserGroup += UserService_SavedUserGroup;
        }

        private void UserService_SavedUserGroup(Umbraco.Core.Services.IUserService sender, Umbraco.Core.Events.SaveEventArgs<Umbraco.Core.Events.UserGroupWithUsers> e)
        {

            foreach (var group in e.SavedEntities)
            {

                int addedUsersCount = group.AddedUsers.Count();

                int removedUsersCount = group.RemovedUsers.Count();

            }

        }

        public void Terminate()
        {

        }


    }


    public class UserGroupComposer : IUserComposer
    {

        public void Compose(Composition composition)
        {
            composition.Components().Append<UserGroupComponent>();
        }

    }
```

### Expected result / actual result

I woud expect that the AddedUsers list has no items when no new users are added.

**Comment by inetzo** [comment]
Looks like the RepositoryBase.GetMany returns all items if the length of array with ids is 0.

**Comment by nul800sebastiaan** [comment]
Fixed in https://github.com/umbraco/Umbraco-CMS/pull/10681
