### ISSUE TITLE
V9: TemplateRenderer does not render _ViewStart.cshtml

### ISSUE THREAD

**Issue by lauraneto** [umbraco/Umbraco-CMS#10683]
### Which *exact* Umbraco version are you using? For example: 8.13.1 - don't just write v8

9.0.0-rc001

### Bug summary

When the `RenderTemplateAsync` method of the `IUmbracoComponentRenderer` is called to render a template, only the actual content of the view is returned, the `_ViewStart.cshtml` content is ignored.

### Specifics

On the `ExecuteTemplateRendering` method, when calling `this._viewEngine.GetView`, `isMainPage` is set to `false` resulting in the `_ViewStart.cshtml` never being called.
This should be either `true` or configurable.

### Steps to reproduce

1. Create a `_ViewStart.cshtml` file under the Views directory with any content.
2. Add the code snippet below to a page template, replacing the `1` in line 2 with an existing node id in your umbraco instance. Make sure the node id used uses a different template to prevent infinite recursion.
```
@inject IUmbracoComponentRenderer _umbracoComponentRenderer
@await _umbracoComponentRenderer.RenderTemplateAsync(1);
```
3. Check that the rendered result does not contain the `_ViewStart.cshtml` code

**Comment by p-m-j** [comment]
Closed by #10684
