### ISSUE TITLE
MediaPicker 3 HasValue() and Fallback.ToDefault not working as expected

### ISSUE THREAD

**Issue by AreYouSureYouKen** [umbraco/Umbraco-CMS#10697]
### Which *exact* Umbraco version are you using? For example: 8.13.1 - don't just write v8

8.14.1

### Bug summary

The new Umbraco 8.14.1 MediaPicker3 returns `MediaWithCrops` instead of an `IPublishedContent`. 
However when using the `HasValue(string alias)` extension from `Umbraco.Web` assembly `PublishedContentExtensions` this always returns true, even if there are no images selected
Same goes for using the `Fallback.ToDefault` with a default value in the `Model.Value()` method.
This does not properly fall back to the default value if there is no image selected.

### Steps to reproduce

Add two MediaPicker3 properties to a page.
Call them Overview Image and Header Image for example
Add to the template this line:
`Model.Value<MediaWithCrops>("overviewImage", fallback: Fallback.ToDefaultValue, defaultValue: Model.Value<MediaWithCrops>("headerImage"))`
Fill only the header image and not the overview image

Observe that it returns a null value

Then add an image to the overview image

Observe that it returns a `MediaWithCrops` value of the selected image.

### Expected result / actual result

Proper `HasValue()` functionality of returning False when an image(or multiple) has not been selected
Proper fallback functionality in the Value() method

**Comment by emma-hq** [comment]
Hey @AreYouSureYouKen 

Thanks for reporting this one. There's some ongoing work on the media picker - I'm going to look into that and see if any of the work addresses what you've reported here and then report back to you. 

Emma

**Comment by nul800sebastiaan** [comment]
A lot of this was changed again in 8.15, the new mediapicker is returning `IPublishedContent` - I encourage you to upgrade and try again! 👍
