### ISSUE TITLE
MultiUrlPicker throws api error 

### ISSUE THREAD

**Issue by emma-hq** [umbraco/Umbraco-CMS#10694]
### Which *exact* Umbraco version are you using? For example: 8.13.1 - don't just write v8

v9 RC001

### Bug summary

When I try to create a page with a multiurl picker I am encountering this error upon page load. 

Request error: The URL returned a 404 (not found):
/umbraco/backoffice/umbracoapi/entity/GetUrl

### Specifics

![image](https://user-images.githubusercontent.com/78740801/125944712-30c398fd-1093-4bee-a2d0-1c64e93eb700.png)
Each time you click on a page with a multi url picker on it, you get this error.

### Steps to reproduce

On a clean install
1. Create a doctype of any page
2. Add page of content
2. Add a multi url picker property to doc type
3. Select a page in the picker
4. Save and publish
5. Load page. 

### Expected result / actual result

No error

**Comment by emma-hq** [comment]
Oh hi Emma, thanks for submitting this issue. I can reproduce so will label this accordingly. 

Emma

**Comment by deMD** [comment]
Also happens when updating from an U8 project :)

![image](https://user-images.githubusercontent.com/22070292/125951530-40610a38-ebd5-43c7-bfa2-7a77dbd30d4e.png)

**Comment by prjseal** [comment]
I get this issue too, on a site which was created using the beta and upgraded to rc1

**Comment by javz3** [comment]
Same, get the issue too on V9 RC

**Comment by nul800sebastiaan** [comment]
Fixed in https://github.com/umbraco/Umbraco-CMS/pull/10722
