### ISSUE TITLE
Umbraco 8.14.1 Mandatory MediaPicker3 unable to add after mandatory message

### ISSUE THREAD

**Issue by AreYouSureYouKen** [umbraco/Umbraco-CMS#10696]
### Which *exact* Umbraco version are you using? For example: 8.13.1 - don't just write v8

8.14.1

### Bug summary

When marking the new MediaPicker3 as mandatory, a notification appears when trying to save or publish the page. This works as expected. After that however an error appears in javascript if you want to then select an image in the Media picker
![image](https://user-images.githubusercontent.com/5592855/125946892-39f6b6ab-0848-4eb8-a94c-66ac504479e5.png)
this happens because vm.model.value is empty (not an empty array as expected)

### Specifics

Tested in Chrome and Firefox with the new MediaPicker3 with a basic configuration (allow multiple: false, enable focal point: true, no crops defined)

### Steps to reproduce

Add a MediaPicker3 single configuration to a node, mark it as mandatory.
Create this new item, save/publish with no media item selected, error should appear
Try to add a media item without reloading the page

### Expected result / actual result

Able to select an image while the error is still on screen, as this is possible with all other property types as well.

**Comment by AreYouSureYouKen** [comment]
I have found a fix for it myself but I am not entirely sure how to contribute this to the project itself, if anyone could help me out with that so that I can fix certain bugs myself as well in the future that would be great!

The fix is:

Add the line:
if (!vm.model.value) vm.model.value = [];

in  Umbraco/Js/umbraco.directives.js 
Before line number: 20243

**Comment by AreYouSureYouKen** [comment]
One more note, after adding a media item, with the mandatory message still visible. I am unable to publish. I can however press save, the message will disappear and then I can publish.

**Comment by patrickdemooij9** [comment]
This might be fixed with https://github.com/umbraco/Umbraco-CMS/pull/10633, but I am not 100% sure

**Comment by nul800sebastiaan** [comment]
Fixed in https://github.com/umbraco/Umbraco-CMS/pull/10633 and cherry picked for 8.14.1 in 3def2ee2ad2897e1d1c6d9b1d077e4c4652d01d4
