### ISSUE TITLE
Upgrade error from 8.14.1 to 8.15.0: SQL exception concerning FK_umbracoRedirectUrl_umbracoNode_uniqueID

### ISSUE THREAD

**Issue by wvdweerd** [umbraco/Umbraco-CMS#10698]
### Which *exact* Umbraco version are you using? For example: 8.13.1 - don't just write v8

8.14.1, using Sql Server 2016

### Bug summary

When trying to upgrade from 8.14.1 to 8.15.0 I get a SQL exception when the database migration steps are processed: "'FK_umbracoRedirectUrl_umbracoNode_uniqueID' is not a constraint. Could not drop constraint."

### Specifics

Interesting part from the log:
- Database upgrade started
- Execute "AddCmsContentNuByteColumn"
- SQL [0]: "ALTER TABLE [cmsContentNu] ALTER COLUMN [data] NTEXT NULL"
- SQL [1]: "ALTER TABLE [cmsContentNu] ADD [dataRaw] VARBINARY(MAX) NULL"
- Execute "UpgradedIncludeIndexes"
- SQL [2]: "ALTER TABLE [umbracoRedirectUrl] DROP CONSTRAINT [FK_umbracoRedirectUrl_umbracoNode_uniqueID]"
- Exception ("488e55ee"):
System.Data.SqlClient.SqlException (0x80131904): 'FK_umbracoRedirectUrl_umbracoNode_uniqueID' is not a constraint.
Could not drop constraint.

Looking into the database there is indeed no FK on my UmbracoRedirectUrl table. 

Should there be such a FK constraint?
Or should the upgrade just ignore this "error" when there is no FK to drop and just continue?

### Steps to reproduce

I started this Umbraco project with a clean version 8.9.1, and applied all updates up to 8.14.1 (and now to 8.15.0).
In the database (backup) of this rfirst version there also was no FK on the UmbracoRedirectUrl table.
So this could be a good way to reproduce the problem.

### Expected result / actual result

I expected the database migration to be exceuted without errors.

**Comment by wvdweerd** [comment]
After installing a brand new 8.41.1 Umbraco website I saw in the corresponding database that this foreign key existed for the table umbracoRedirectUrl.
So I added this FK with the following sql script to my Umbraco website that I wanted to update:

```
ALTER TABLE [dbo].[umbracoRedirectUrl]  WITH CHECK ADD  CONSTRAINT [FK_umbracoRedirectUrl_umbracoNode_uniqueID] FOREIGN KEY([contentKey])
REFERENCES [dbo].[umbracoNode] ([uniqueId])
GO

ALTER TABLE [dbo].[umbracoRedirectUrl] CHECK CONSTRAINT [FK_umbracoRedirectUrl_umbracoNode_uniqueID]
GO

```

After this the upgrade to 8.15.0 went without any errors.

So probably it was just my database that was out-of-sync in some way.

**Comment by vaskinhu** [comment]
I had the same issue

**Comment by thomashdk** [comment]
Same issue from 8.14.3 to 8.16
