### ISSUE TITLE
Upgrading from 8.14.1 to 8.15 fails

### ISSUE THREAD

**Issue by jesperordrup** [umbraco/Umbraco-CMS#10693]
### Which *exact* Umbraco version are you using? For example: 8.13.1 - don't just write v8

8.14.1

### Bug summary

Running update-pacage umbracoCms -version 8.15.0 does not upgrade the solution. Dlls are remaning on v 8.14.1

### Steps to reproduce

![image](https://user-images.githubusercontent.com/3120151/125925619-c75f9551-a732-4225-98d0-5b5ce59a4d1b.png)

## Before
![image](https://user-images.githubusercontent.com/3120151/125925873-4ea59aec-a47a-44ae-9587-f1e5eab1c7e9.png)

## updating
![image](https://user-images.githubusercontent.com/3120151/125925961-9edee757-d3cc-4d67-b7cd-cba9849506a1.png)

* Video showing update
https://www.loom.com/share/37375b440a644118b6d5e6eddf03e0c2

## After
![image](https://user-images.githubusercontent.com/3120151/125926416-cb6fb752-4064-4630-a99a-92ebe85cb616.png)

## Running first time

* not upgraded (version number in web.config remains the same)
* no process starting 
* Sidenote: the master.cshtml file is replaced with an empty master.cshtml file (minor)

**Comment by nul800sebastiaan** [comment]
Thanks @jesperordrup! That is surprising, we always test NuGet upgrades before we release an RC of a minor. I had to try for myself and as you can see it works (on my machine).

https://user-images.githubusercontent.com/304656/125937158-394e4a4c-7973-4c87-b043-9bbc79bfde41.mp4

In the middle of this video you might notice that NuGet is asking you a question about overwriting things, to which you should answer "No to all", possibly you didn't see this prompt and thought the upgrade was already finished. In that case: try agiain! 👍

**Comment by jesperordrup** [comment]
@nul800sebastiaan 

I do type no to overwriting (the L option). 

It must be something that confuses nuget - just dont know enough about nuget to figure out when nuget doesnt copy files when supposed to. Lets see if anyone else experience this.

Extra:
I did a clean install of Umbraco 8.14.1 and tried upgrading that. That went 100% as expected.

**Comment by nul800sebastiaan** [comment]
Hmm, very strange, it doesn't ring any bells to me! Maybe try doing it using the visual NuGet Explorer in VS, that might give you an actual error message?
