### ISSUE TITLE
`inert` attribute not being removed when calling `editorService.closeAll()`

### ISSUE THREAD

**Issue by mattbrailsford** [umbraco/Umbraco-CMS#10708]
### Which *exact* Umbraco version are you using? For example: 8.13.1 - don't just write v8

8.14 + 8.15

### Bug summary

#8522 introduced the adding of an `inert` attribute on the main editor window when opening a dialog however this isn't getting removed when calling `editorService.closeAll()` and so the editor becomes completely unresponsive.

### Specifics

We are receiving reports from Vendr users who have upgraded to 8.14+ that when they use the discounts editor (which opens in a dialog), when they close the editor dialog, the whole editor becomes unresponsive.

On investigation, this appears to come down to the fact that in #8522 a new attribute is added to the main editor window, "inert" which is styled such that it blocks all pointer events, preventing clicks on the background window while the dialog is open. It appears that most of the work with this attribute is concentrated around the dialog service, and when you call close on this service, the attribute is removed.

Unfortunately, this doesn't appear to take into account that a dialog can be controlled via the editor service too, which is what our dialog is using such that on completion the dialog calls `editorService.closeAll()` however this doesn't appear to be removing the `inert` attribute and so the main editor window remains unresponsive.

### Steps to reproduce

1. Launch a dialog via the editor service `editorService.open(...);`
2. Close the dialog calling `editorService.closeAll()`
3. Editor becomes completely unresponsive

### Expected result / actual result

`inert` attribute should be removed when dialog is closed and main editor should become responsive again.

**Comment by nul800sebastiaan** [comment]
Thanks @mattbrailsford for the fix! And apologies for breaking this scenario for you!

**Comment by nul800sebastiaan** [comment]
Fixed in https://github.com/umbraco/Umbraco-CMS/commit/1f4cc81af8c5ce7b286238e29773f8a2be9c4182 and cherry picked for 8.14.2 in 98266d462c5821327d8d4320a08224447c370e8a (will also be available in 8.15.1).
