### ISSUE TITLE
Outdated log directory shown

### ISSUE THREAD

**Issue by rjsmith2** [umbraco/Umbraco-CMS#10703]
### Which *exact* Umbraco version are you using? For example: 8.13.1 - don't just write v8

9.0.0 RC1

### Bug summary

When you trigger an error during Umbraco installation, it shows outdated path for logs. 
It says "See the log for full details (logs can typically be found in the App_Data\Logs folder)."

![image](https://user-images.githubusercontent.com/7023709/126038071-2ac49e7c-e7db-40a2-877e-6e87cf07a76f.png)

### Specifics

localhost:80/

### Steps to reproduce

During installation, give it a improper SQL setup so the error occurs.
So this would show up:
![image](https://user-images.githubusercontent.com/7023709/126038147-981c65b5-5cd7-4d91-adda-09d5889d2c33.png)

### Expected result / actual result

Should say "See the logs for full details (logs can typically be found in the Umbraco/Logs)."

**Comment by nikolajlauridsen** [comment]
Hey @rjsmith2 thanks for reporting 😃 I'll go ahead and close this issue since it was fixed in #10636
