### ISSUE TITLE
Can not upgrade from v8.14.1 to Umbraco 8.15.0 via nuget

### ISSUE THREAD

**Issue by nick-hoang** [umbraco/Umbraco-CMS#10723]
### Which *exact* Umbraco version are you using? For example: 8.13.1 - don't just write v8

8.14.1

### Bug summary

Here's the error message:

```
Error downloading 'UmbracoCms.8.15.0 : ImageProcessor.Web [4.10.0.100, 4.999999.0), ImageProcessor.Web.Config [2.5.0.100, 2.999999.0), Microsoft.AspNet.SignalR.Core [2.4.0, 2.999999.0), Microsoft.CodeDom.Providers.DotNetCompilerPlatform [2.0.1, 2.999999.0), UmbracoCms.Web [8.15.0, 8.15.0]' from 'https://api.nuget.org/v3-flatcontainer/umbracocms/8.15.0/umbracocms.8.15.0.nupkg'.
Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host.
  An existing connection was forcibly closed by the remote host
  GET https://api.nuget.org/v3-flatcontainer/umbracocms/8.15.0/umbracocms.8.15.0.nupkg
  OK https://api.nuget.org/v3-flatcontainer/umbracocms/8.15.0/umbracocms.8.15.0.nupkg 4855ms
```

The bug here is in the config of dependencies: [https://prnt.sc/1ebcd28](https://prnt.sc/1ebcd28)

### Steps to reproduce

1. Have a site in Umbraco 8.14.1
2. Run Install-Package UmbracoCms -Version 8.15.0 
3. Get the error in Package manager console

### Expected result / actual result

No errors, to able to upgrade from 8.14.1 to v8.15.0 normally

**Comment by nul800sebastiaan** [comment]
Hi @nick-hoang - that looks like an error on your end somewhere. I found this: https://stackoverflow.com/a/39029994/5018

Maybe some proxy server or something in the network blocking NuGet? 

I'm afraid we can't help with that, so I'll close this issue :)

**Comment by nick-hoang** [comment]
Hi @nul800sebastiaan 

Thanks for your time, it's all good now. And it's quite strange that it couldn't pull the ImageProcessor.Web package yesterday, other packages work perfect, but it work well today. I think it's an issue from Nuget...

Cheers,
Nick
