### ISSUE TITLE
QueryString max length exceeded

### ISSUE THREAD

**Issue by Tzepii** [umbraco/Umbraco-CMS#10734]
### Which *exact* Umbraco version are you using? For example: 8.13.1 - don't just write v8

8.15

### Bug summary

I suppose as part of v8.15 performance optimisation, you group multiple calls to umbraco/backoffice/UmbracoApi/Content/GetEmptyByKey?contentTypeKey=
to single call with array parameter, but you don't take into condideration that there is a limit on Querystring lenght. My combined call looks like:
https://localhost:44325/umbraco/backoffice/UmbracoApi/Content/GetEmptyByKeys?contentTypeKeys[]=57c24069-4a8b-45ae-aeab-23e079be9712&contentTypeKeys[]=618c83b8-ca75-48ee-b69c-f1d7cd2b6d55&contentTypeKeys[]=8adf066e-76c1-4285-a288-61cd5f538ddb&contentTypeKeys[]=998a6065-68dc-41b8-8ebf-976602462483&contentTypeKeys[]=7f5898bb-c9f4-4794-9339-d87720ffe784&contentTypeKeys[]=334f271c-fa4a-4db6-8df2-c80e0c73018f&contentTypeKeys[]=6d7563e7-369f-41db-88ea-c0ab51c63903&contentTypeKeys[]=e9e34059-41b3-4b22-99c9-869de5f3f595&contentTypeKeys[]=59097d4c-12db-4428-9f89-002dd1d9a2a7&contentTypeKeys[]=e0fd5b0a-e9ee-45a4-8cc0-fa436e15c623&contentTypeKeys[]=87149ae4-d4dd-46b4-98cc-af1a927f2f28&contentTypeKeys[]=e735de90-2cd3-4568-a724-f3bc17590d7b&contentTypeKeys[]=d89ee708-5875-4c1a-aef6-27da51d43602&contentTypeKeys[]=21e395b0-3483-4330-93d2-a966effec4ef&contentTypeKeys[]=d99c3069-f106-47bc-998f-5747540edbac&contentTypeKeys[]=a0a09396-043e-470a-a28c-20cd877ff9aa&contentTypeKeys[]=99c0392b-835f-4a7b-b020-4083d158dc0d&contentTypeKeys[]=47ad83f7-ce8a-431d-8c9f-5a19c866a052&contentTypeKeys[]=a7298666-ca3d-4265-9387-01e17e4eca92&contentTypeKeys[]=40704fc8-d7f0-460a-b364-02dae053ebd9&contentTypeKeys[]=c14d54ef-0e44-4f40-95e1-86d4a216c6fd&contentTypeKeys[]=77ace462-a163-4c0e-bfb6-c49697ce8308&contentTypeKeys[]=fae7e903-275f-4a2f-802f-d14535e0724f&contentTypeKeys[]=ad884d02-5c77-4cd4-8904-c860c31f369b&contentTypeKeys[]=ba02a3fd-14ce-4ef3-9201-2195cdfae40d&contentTypeKeys[]=8569fe0c-6fd8-49e2-9bb3-b665db739e84&contentTypeKeys[]=fd1bbf4b-68ee-43df-acbb-0d317401df87&contentTypeKeys[]=5a1c11da-c430-4a25-8821-b2362212671a&contentTypeKeys[]=32d8f9a8-8c12-4ae7-8285-e969e47ce890&contentTypeKeys[]=5b14f1cc-3901-47a5-aafa-904c139f8de9&contentTypeKeys[]=96662765-7734-4189-a0cf-85eb2a4ae0c3&contentTypeKeys[]=9054e2b7-0060-468e-99b6-eb1d8aaff0eb&contentTypeKeys[]=2e62e7f9-f281-4098-98f1-f4a024241c2a&contentTypeKeys[]=2a377d23-9dde-4862-adf9-457a45714317&contentTypeKeys[]=ecfd7fe9-2201-4c52-bc4a-471868aefa31&contentTypeKeys[]=ba0a31b5-4b05-41c5-a131-71aabb5ad8c2&contentTypeKeys[]=1b6442b8-7f88-4410-b665-4920e626cc20&contentTypeKeys[]=ccb12c0a-e9bf-4e30-b1fa-e67193a35b6a&contentTypeKeys[]=405a82cb-5530-4288-a8c5-a3b7ba2479b0&contentTypeKeys[]=5697db66-f152-49d3-aee2-526b31c04e90&contentTypeKeys[]=430d6f2d-0636-4b69-bd0b-2e3f258cfafe&contentTypeKeys[]=02d0836e-e7f8-4d09-9e9e-1459543d7cdf&contentTypeKeys[]=7fe5b715-1a1c-4ead-b91a-801d0d50e917&contentTypeKeys[]=d0c93621-56ca-4a4c-9a0b-df0f23a067dd&parentId=-20

and on standard web config setings this return a 404 error. 
As a work around add maxQueryStringLength="100000" to httpruntime in web.config but this poses other security issues, so this is not a solution.

### Steps to reproduce

instal umazel theme from packages, then navigate to content items in backoffice

### Expected result / actual result

An error with message:Request error: The URL returned a 404 (not found):
/umbraco/backoffice/UmbracoApi/Content/GetEmptyByKeys

**Comment by bjarnef** [comment]
I think this a duplicate of https://github.com/umbraco/Umbraco-CMS/issues/10718 which has been fixed in

**Comment by Tzepii** [comment]
if the resolution is this: 
{ contentTypeKeys: scaffoldKeys.join(","), parentId: parentId })),
the it is not a fix, it just shorten the query string a bit. I think the fix must be something like changing the request from get to post or other way.

**Comment by bjarnef** [comment]
@Tzepii yes, that's a temporary workaround, but as mentioned it is fixed in PR https://github.com/umbraco/Umbraco-CMS/pull/10726 which change this to a POST request, which allow sending more ids in the request.

**Comment by bjarnef** [comment]
@nul800sebastiaan I think this one can be closed 👍
