### ISSUE TITLE
Issue when upgraded from 8.14 to 8.15 when inviting user into the backoffice. 

### ISSUE THREAD

**Issue by Landhaai** [umbraco/Umbraco-CMS#10746]
### Which *exact* Umbraco version are you using? For example: 8.13.1 - don't just write v8

8.14.0 & 8.15

### Bug summary

On our instance of umbraco 8.14 i could invite users into the backoffice (stmp config was working)

When upgrading to 8.15 the invite loader keeps on spinning and when running locally i get a stackoverflow error. This is when using the exact same STMP config. 

Debug console output:
An unhandled exception of type 'System.StackOverflowException' occurred in Unknown Module.

The user is still made but no mail ever gets send to the emailaddress

### Steps to reproduce

Install 8.14, check if the smtp settings work and invite user.
Upgrade using nuget to 8.15, run the website and let it install the upgrade. 
Invite user again 

### Expected result / actual result

Invite user email send

**Comment by nul800sebastiaan** [comment]
Thanks @Landhaai unfortunately I can't reproduce this problem, upgraded from 8.14.0 to 8.15 and password reset still works as expected. Possibly you overlooked something during the upgrade, this blog post is a bit old but still mostly applicable to identifying upgrade issues: https://cultiv.nl/blog/how-to-diagnose-umbraco-upgrade-problems/

If that doesn't help, I recommend you head on out  to the forums where our friendly community can help you find the best solution for your requirements. Add some more details of what your smtp config looks like and what error(s) your seeing exactly in your logs.
Make sure to head on over to https://our.umbraco.com and ask follow up questions there! 👍

**Comment by nul800sebastiaan** [comment]
I've just had this happen on a different 8.15 site, so I'll re-open and investigate.

**Comment by Landhaai** [comment]
Alright, keep me posted on what you find :)

**Comment by nul800sebastiaan** [comment]
The cause is here, not sure how to fix it yet: https://github.com/umbraco/Umbraco-CMS/commit/dd111226090642cd6777630ff45e432ce8349656#r54134090

**Comment by nul800sebastiaan** [comment]
PR to fix is here: https://github.com/umbraco/Umbraco-CMS/pull/10767

**Comment by nul800sebastiaan** [comment]
Fixed in https://github.com/umbraco/Umbraco-CMS/pull/10767 and cherry picked for 8.15.2 7c336554db55fc3f0725b29718a4b6649b5fa97f

**Comment by Landhaai** [comment]
Thank you so much :)
