### ISSUE TITLE
Issue in 8.14.1 when opening a crop on a selected image in the new media picker.

### ISSUE THREAD

**Issue by nielslyngsoe** [umbraco/Umbraco-CMS#10743]
This seems to still be a problem on 8.14.1 when opening a crop on a selected image in the new media picker.
![image](https://user-images.githubusercontent.com/1074004/125922435-8f7b6b37-7d6b-44da-b5a1-7f7088939b48.png)

The offending code is here:
![image](https://user-images.githubusercontent.com/1074004/125922506-cea600e2-bd8c-4084-b261-639b5e0518db.png)

But it seems that there is still a problem injecting the dependency?

_Originally posted by @sniffdk in https://github.com/umbraco/Umbraco-CMS/issues/10325#issuecomment-881293383_

---
_This item has been added to our backlog [AB#13006](https://dev.azure.com/umbraco/243e7927-03b2-44e2-908f-d4ac7ea5daaa/_workitems/edit/13006)_

**Comment by bjarnef** [comment]
I noticed it is using this service https://github.com/umbraco/Umbraco-CMS/blob/v8/contrib/src/Umbraco.Web.UI.Client/src/common/services/windowresizelistener.service.js

It seems `WinReszier` should be `WinResizer` instead.
Furthermore I wonder if there's a specific reason the service is using jQuery and not vanilla JS.

```
window.addEventListener('resize', event => {
   ...
});
```

https://ryfarlane.com/article/width-and-resize-vanilla-javascript

**Comment by bjarnef** [comment]
Fixed in https://github.com/umbraco/Umbraco-CMS/pull/10745
It wasn't injecting `windowResizeListener` correct and thus undefined when accessing the functions in Image Crop directive.

**Comment by nul800sebastiaan** [comment]
@bjarnef where is this jQuery used?

**Comment by bjarnef** [comment]
@nul800sebastiaan the parts using `$` in `windowResizeListener` but it has been like that since the service was added. I guess it is more about future enhancement of Umbraco, so we limit the use of jQuery when possible and maybe someday Umbraco don't have jQuery as dependency as many of the functions can be written in vanilla JS these days 😎🤓😁👌

**Comment by nul800sebastiaan** [comment]
We should get rid of that dependency, I didn't think we even had a dependency except for a few very select things.

**Comment by nul800sebastiaan** [comment]
Fixed in https://github.com/umbraco/Umbraco-CMS/pull/10745 and cherry picked for 8.14.3 in f7529e0cf52220759ec458f8328268d5dbc3cecb - merged up to 8.15.2 e8926ab17daa716ddd2d850304a3266a7bdcf71a.
