### ISSUE TITLE
Published Content not appearing on non-master server after PublishAndSave through HangFire

### ISSUE THREAD

**Issue by garpunkal** [umbraco/Umbraco-CMS#10744]
### Which *exact* Umbraco version are you using? For example: 8.13.1 - don't just write v8

8.15

### Bug summary

We have the following setup 

- Master - with Umbraco and HangFire
- Slave - only front read only. 

We have a HangFire task that runs only on the Master server, it works perfectly and the content created and updated on Master server. 

However, the content doesn't updated on front server, we couldn't even see a CacheInstruction created. 

After save and publish via backoffice/or a refresh memory cache, the content appears on frontend server.

We use the scope provider to encapsulate our work,
` using (var scope = _scopeProvider.CreateScope(autoComplete: true))` 

We use the activator for HangFire (https://our.umbraco.com/forum/umbraco-8/96445-hangfire-dependency-injection).

The task appears to run perfectly, but the content just never makes it to the frontend webserver through the HangFire task. 

We've tried many different approaches to get this to work through the code, including refreshing cache, rebuilding the cache, even the workarounds in this ticket: https://github.com/umbraco/Umbraco.Cloud.Issues/issues/411

We've found that scheduling the content item, rather than SaveAndPublish, does make it's way to the frontend server, but the images doesn't show for some reason (likely down to the original issue). 

Let me know if you need anymore information. It's difficult to replicate without a CD/CM setup.

### Steps to reproduce

Setup multi instance environment:

- Master - with Umbraco and HangFire
- Slave - only front read only. 

Create a hangfire task on master server that publishes content. 

See if the content replicates to both servers.  

### Expected result / actual result

Content publishes to master and frontend servers.

**Comment by emma-hq** [comment]
Hey @garpunkal 

Thanks for reporting this one. And for all the info you've given us so far. It is going to be difficult to replicate but we've had a few issues submitted relating to Hangfire so I'll take a look across them and see if I can get some info form those tickets too.

Emma

**Comment by garpunkal** [comment]
Thanks Emma. More than happy to help or share more code.  Just give us a shout.

**Comment by emma-hq** [comment]
Hey @garpunkal 

Thanks for all the info and for your patience here. I've had a look and worked with others to try to replicate the issue and haven't been able to. There are so many moving parts in this one so it's difficult for us to ascertain whether it's an umbraco bug or the way the load balancing has been set up or a hangfire issue. As a result, I'd be reluctant to tag as up-for-grabs. Is there anything you can pinpoint in the schedule save event that is causing the issue?

In the meantime, it might be worth you investigating using Umbraco's built in scheduler instead. Docs are here [https://our.umbraco.com/documentation/reference/Scheduling/](https://our.umbraco.com/documentation/reference/Scheduling/)
BackgroundTaskRunner is a great place to start. I'll close the issue for now with all this in mind but if you run into any problems, let us know.

Emma
