### ISSUE TITLE
no able to open umbraco login becouse URL limit for /DependencyHandler.axd is reached - cdn cloudfront

### ISSUE THREAD

**Issue by xanderekpl** [umbraco/Umbraco-CMS#10769]
### Which *exact* Umbraco version are you using? For example: 8.13.1 - don't just write v8

8.15.0

### Bug summary

We have problem to open Login page because one of resources return error 413 on cloud-front AWS. (to long query)

![Inkedimage (12)_LI](https://user-images.githubusercontent.com/1809452/127500799-31196095-82c6-4cf9-820e-c3d8fa7d4417.jpg)

![image](https://user-images.githubusercontent.com/1809452/127498021-8146a067-75f6-4c21-82a2-3ac7b1e14bc3.png)

### Specifics

i've made investigation and found that LazyLoad is trying to load all JS app plugins created/installed during development

there is no problem on localhost as they are not merged via Client dependency
all of scripts are send to Client dependency and URL created by it contains to many characters. 

currently we have around 15 plugins installed or created by ourselves.  and we reach limit of 8192 bytes (~8300)

the limit on CDN is strict 

but chromium limit can also late make difference in another scenarios:
https://chromium.googlesource.com/chromium/src/+/refs/heads/main/docs/security/url_display_guidelines/url_display_guidelines.md#:~:text=Chrome%20limits%20URLs%20to%20a,is%20used%20on%20VR%20platforms.

### Steps to reproduce

create a lot of plugins with connected js files -> and check langth of url  generated by CD
please check links with CD on

![image](https://user-images.githubusercontent.com/1809452/127500338-dacee1f0-ac75-4884-ac74-7c15bd6a94bb.png)

### Expected result / actual result

if number of scripts is longer to attach there should be split and 2 or more request to CD.

**Comment by nul800sebastiaan** [comment]
Hey thanks @xanderekpl - I don't think this is something that we can fix in the CMS, the ClientDependency project is what we use to load everything in. Could you please report it there? https://github.com/Shazwazza/ClientDependency - thanks in advance! 👍

**Comment by xanderekpl** [comment]
@nul800sebastiaan  partialy agree but CD depends on list of string umbraco is sending there. CD is doing all what umbraco expect -> all links to one url
even if CD will improve generating hash if umbraco will send to many links it will popup again

i think there is room to do something on umbraco side too. -> not send all links to CD if reaching limit

and BTW this creating limit to number o plugins allowed in umbraco

**Comment by nul800sebastiaan** [comment]
Possibly! I am not too familiar with this. Will have to get @Shazwazza involved probably, but he's very busy at the moment.

I would say: if you can possibly delete a few files from that huge plugin that you have then that would be a temporary solution. Each plugin gets it's own DependencyHandler URL so there is 1 that is generating that really long querystring for you now. Probably could just split out some files in a separate App_Plugins directory and a new package.manifest. Out of curiosity, can you add here what it says in the `s=` parameter of the URL that's too long please? So something like `L3VtYnJhY28vYXNzZXRzL2Nzcy91bWJyYWNvLmNzczsvdW1icmFjby9saWIvYm9vdHN0cmFwLXNvY2lhbC9ib290c3RyYXAtc29jaWFsLmNzczsvdW1icmFjby9saWIvZm9udC1hd2Vzb21lL2Nzcy9mb250LWF3ZXNvbWUubWluLmNzczs`.

**Comment by xanderekpl** [comment]
s=L3VtYnJhY28vbGliL2pxdWVyeS9qcXVlcnkubWluLmpzOy91bWJyYWNvL2xpYi9qcXVlcnktdWkvanF1ZXJ5LXVpLm1pbi5qczsvdW1icmFjby9saWIvanF1ZXJ5LXVpLXRvdWNoLXB1bmNoL2pxdWVyeS51aS50b3VjaC1wdW5jaC5taW4uanM7L3VtYnJhY28vbGliL2FuZ3VsYXIvYW5ndWxhci5qczsvdW1icmFjby9saWIvdW5kZXJzY29yZS91bmRlcnNjb3JlLW1pbi5qczsvdW1icmFjby9saWIvbW9tZW50L21vbWVudC5taW4uanM7L3VtYnJhY28vbGliL2ZsYXRwaWNrci9mbGF0cGlja3IuanM7L3VtYnJhY28vbGliL2FuaW1lanMvYW5pbWUubWluLmpzOy91bWJyYWNvL2xpYi9hbmd1bGFyLXJvdXRlL2FuZ3VsYXItcm91dGUuanM7L3VtYnJhY28vbGliL2FuZ3VsYXItY29va2llcy9hbmd1bGFyLWNvb2tpZXMuanM7L3VtYnJhY28vbGliL2FuZ3VsYXItYXJpYS9hbmd1bGFyLWFyaWEubWluLmpzOy91bWJyYWNvL2xpYi9hbmd1bGFyLXRvdWNoL2FuZ3VsYXItdG91Y2guanM7L3VtYnJhY28vbGliL2FuZ3VsYXItc2FuaXRpemUvYW5ndWxhci1zYW5pdGl6ZS5qczsvdW1icmFjby9saWIvYW5ndWxhci1hbmltYXRlL2FuZ3VsYXItYW5pbWF0ZS5qczsvdW1icmFjby9saWIvYW5ndWxhci1tZXNzYWdlcy9hbmd1bGFyLW1lc3NhZ2VzLmpzOy91bWJyYWNvL2xpYi9hbmd1bGFyLXVpLXNvcnRhYmxlL3NvcnRhYmxlLmpzOy91bWJyYWNvL2xpYi9hbmd1bGFyLWR5bmFtaWMtbG9jYWxlL3RtaER5bmFtaWNMb2NhbGUubWluLmpzOy91bWJyYWNvL2xpYi9uZy1maWxlLXVwbG9hZC9uZy1maWxlLXVwbG9hZC5taW4uanM7L3VtYnJhY28vbGliL2FuZ3VsYXItbG9jYWwtc3RvcmFnZS9hbmd1bGFyLWxvY2FsLXN0b3JhZ2UubWluLmpzOy91bWJyYWNvL2xpYi9jaGFydC5qcy9jaGFydC5taW4uanM7L3VtYnJhY28vbGliL2FuZ3VsYXItY2hhcnQuanMvYW5ndWxhci1jaGFydC5taW4uanM7L3VtYnJhY28vbGliL3dpY2ctaW5lcnQvZGlzdC9pbmVydC5taW4uanM7L3VtYnJhY28vbGliL3VtYnJhY28vRXh0ZW5zaW9ucy5qczsvdW1icmFjby9saWIvdW1icmFjby9OYW1lc3BhY2VNYW5hZ2VyLmpzOy91bWJyYWNvL2xpYi91bWJyYWNvL0xlZ2FjeVNwZWVjaEJ1YmJsZS5qczsvdW1icmFjby9qcy91dGlsaXRpZXMuanM7L3VtYnJhY28vanMvYXBwLmpzOy91bWJyYWNvL2pzL3VtYnJhY28ucmVzb3VyY2VzLmpzOy91bWJyYWNvL2pzL3VtYnJhY28uZGlyZWN0aXZlcy5qczsvdW1icmFjby9qcy91bWJyYWNvLmZpbHRlcnMuanM7L3VtYnJhY28vanMvdW1icmFjby5zZXJ2aWNlcy5qczsvdW1icmFjby9qcy91bWJyYWNvLmludGVyY2VwdG9ycy5qczsvdW1icmFjby9qcy91bWJyYWNvLmNvbnRyb2xsZXJzLmpzOy91bWJyYWNvL2pzL3JvdXRlcy5qczsvdW1icmFjby9qcy9pbml0LmpzOy9BcHBfUGx1Z2lucy9DREZIZWFsdGhDaGVjay9oZWFsdGhjaGVjay5qczsvQXBwX1BsdWdpbnMvQ3VzdG9tL2NvbXBvbmVudHMvYmxvY2stZmllbGQtdmFsdWUtY2xlYW5lci9ibG9ja0ZpZWxkVmFsdWVDbGVhbmVyLmpzOy9BcHBfUGx1Z2lucy9DdXN0b20vY29udGVudEFwcHMvc2NoZWR1bGVkUGFnZXMvY29udHJvbGxlci5qczsvQXBwX1BsdWdpbnMvQ3VzdG9tL2NvbnRlbnRBcHBzL3NjaGVkdWxlZFBhZ2VzL3NlcnZpY2UuanM7L0FwcF9QbHVnaW5zL0N1c3RvbS9kYXNoYm9hcmRzL2NoZWNrVG91ckRhdGEvY29udHJvbGxlci5qczsvQXBwX1BsdWdpbnMvQ3VzdG9tL2Rhc2hib2FyZHMvY2hlY2tUb3VyRGF0YS9zZXJ2aWNlLmpzOy9BcHBfUGx1Z2lucy9DdXN0b20vZGFzaGJvYXJkcy9jaGVja1RvdXJEYXRhL2RhdGFodWIuanM7L0FwcF9QbHVnaW5zL0N1c3RvbS9kYXNoYm9hcmRzL2ltcG9ydFRvdXJEYXRhL2ltcG9ydFRvdXJEYXRhVmlld3NDb250cm9sbGVyLmpzOy9BcHBfUGx1Z2lucy9DdXN0b20vZGFzaGJvYXJkcy9pbXBvcnRUb3VyRGF0YS92aWV3cy9kZWZhdWx0L2NvbnRyb2xsZXIuanM7L0FwcF9QbHVnaW5zL0N1c3RvbS9kYXNoYm9hcmRzL2ltcG9ydFRvdXJEYXRhL3ZpZXdzL2RlZmF1bHQvc2VydmljZS5qczsvQXBwX1BsdWdpbnMvQ3VzdG9tL2Rhc2hib2FyZHMvaW1wb3J0VG91ckRhdGEvaW1wb3J0VG91ckRhdGFIdWIuanM7L0FwcF9QbHVnaW5zL0N1c3RvbS9kYXNoYm9hcmRzL2ltcG9ydFRvdXJEYXRhL3ZpZXdzL2RldGFpbERpYWxvZ0NvbnRyb2xsZXIuanM7L0FwcF9QbHVnaW5zL0N1c3RvbS9kYXNoYm9hcmRzL211bHRpcGxlVG91ck9wdGlvbnMvY29udHJvbGxlci5qczsvQXBwX1BsdWdpbnMvY3VzdG9tL2Rhc2hib2FyZHMvcHVibGlzaFF1ZXVlL2NvbnRyb2xsZXIuanM7L0FwcF9QbHVnaW5zL2N1c3RvbS9kYXNoYm9hcmRzL3B1Ymxpc2hRdWV1ZS9zZW5kVG9RdWV1ZUNvbnRyb2xsZXIuanM7L0FwcF9QbHVnaW5zL2N1c3RvbS9kYXNoYm9hcmRzL3B1Ymxpc2hRdWV1ZS9zZXJ2aWNlLmpzOy9BcHBfUGx1Z2lucy9jdXN0b20vZGFzaGJvYXJkcy9wdWJsaXNoUXVldWUvaHViLmpzOy9BcHBfUGx1Z2lucy9DdXN0b20vZGFzaGJvYXJkcy9zY2hlZHVsaW5nL1NjaGVkdWxpbmcuU2VydmljZS5qczsvQXBwX1BsdWdpbnMvQ3VzdG9tL2Rhc2hib2FyZHMvc2NoZWR1bGluZy9TY2hlZHVsaW5nLkNvbnRyb2xsZXIuanM7L0FwcF9QbHVnaW5zL0N1c3RvbS9kYXNoYm9hcmRzL3NjaGVkdWxpbmcvcGx1Z2lucy9zbWFydC10YWJsZS5taW4uanM7L0FwcF9QbHVnaW5zL0N1c3RvbS9kYXNoYm9hcmRzL3NlYXJjaENvbmZpZy9jb250cm9sbGVyLmpzOy9BcHBfUGx1Z2lucy9DdXN0b20vZGFzaGJvYXJkcy9zZWFyY2hDb25maWcvc2VydmljZS5qczsvQXBwX1BsdWdpbnMvQ3VzdG9tL2Rhc2hib2FyZHMvdG91ckxheW91dFB1Ymxpc2gvY29udGVudEludGVyY2VwdG9yLmpzOy9BcHBfUGx1Z2lucy9DdXN0b20vZGFzaGJvYXJkcy90b3VyTGF5b3V0UHVibGlzaC9kYXRhSHViLmpzOy9BcHBfUGx1Z2lucy9DdXN0b20vZGFzaGJvYXJkcy90b3VyTGF5b3V0UHVibGlzaC9zZXJ2aWNlLmpzOy9BcHBfUGx1Z2lucy9DdXN0b20vZGFzaGJvYXJkcy90b3VyTGF5b3V0UHVibGlzaC9jb250cm9sbGVyLmpzOy9BcHBfUGx1Z2lucy9DdXN0b20vZWRpdG9ycy9ibG9ja0xpc3QtcmVmZXJlbmNlLXBpY2tlci9qcy9ibG9ja0xpc3RSZWZlcmVuY2VQaWNrZXIucHJvcGVydHlFZGl0b3IuY29udHJvbGxlci5qczsvQXBwX1BsdWdpbnMvQ3VzdG9tL2VkaXRvcnMvYmxvY2tMaXN0LXJlZmVyZW5jZS1waWNrZXIvanMvYmxvY2tMaXN0UmVmZXJlbmNlUGlja2VyLmVkaXRvckRpYWxvZy5jb250cm9sbGVyLmpzOy9BcHBfUGx1Z2lucy9DdXN0b20vZWRpdG9ycy9jaGVja2JveGxpc3QtZWRpdG9yL2NvbnRyb2xsZXIuanM7L0FwcF9QbHVnaW5zL0N1c3RvbS9lZGl0b3JzL2NvbXBhcmUtcm93LWVkaXRvci9jb250cm9sbGVyLmpzOy9BcHBfUGx1Z2lucy9DdXN0b20vZWRpdG9ycy9kZW1vLWVkaXRvci9jb250cm9sbGVyLmpzOy9BcHBfUGx1Z2lucy9DdXN0b20vZWRpdG9ycy9kZW1vLWVkaXRvci9kaWFsb2cuY29udHJvbGxlci5qczsvQXBwX1BsdWdpbnMvQ3VzdG9tL2VkaXRvcnMvZHluYW1pYy1kcm9wZG93bi1lZGl0b3IvZHluYW1pY0Ryb3Bkb3duRWRpdG9yLnByb3BlcnR5RWRpdG9yLmNvbnRyb2xsZXIuanM7L0FwcF9QbHVnaW5zL0N1c3RvbS9lZGl0b3JzL2R5bmFtaWMtZHJvcGRvd24tZWRpdG9yL2R5bmFtaWNEcm9wZG93blJlc291cmNlcy5qczsvQXBwX1BsdWdpbnMvQ3VzdG9tL2VkaXRvcnMvZXh0ZW5kZWQtY29sb3VyLXBpY2tlci9leHRlbmRlZENvbG91clBpY2tlci5wcm9wZXJ0eUVkaXRvci5jb250cm9sbGVyLmpzOy9BcHBfUGx1Z2lucy9DdXN0b20vZWRpdG9ycy9odG1sLW9wdGlvbnMtZWRpdG9yL2pzL2h0bWxPcHRpb25zLnByb3BlcnR5RWRpdG9yLmNvbnRyb2xsZXIuanM7L0FwcF9QbHVnaW5zL0N1c3RvbS9lZGl0b3JzL2h0bWwtb3B0aW9ucy1lZGl0b3IvanMvaHRtbE9wdGlvbnMucHJldmFsdWVzLmNvbnRyb2xsZXIuanM7L0FwcF9QbHVnaW5zL0N1c3RvbS9lZGl0b3JzL2h0bWwtb3B0aW9ucy1lZGl0b3IvanMvaHRtbE9wdGlvbnMuZWRpdG9yRGlhbG9nLmNvbnRyb2xsZXIuanM7L0FwcF9QbHVnaW5zL0N1c3RvbS9lZGl0b3JzL2h0bWwtb3B0aW9ucy1lZGl0b3IvanMvaHRtbE9wdGlvbnMuY29udGVudFNlcnZpY2UuanM7L0FwcF9QbHVnaW5zL0N1c3RvbS9lZGl0b3JzL2ljb24tcGlja2VyL2NvbnRyb2xsZXIuanM7L0FwcF9QbHVnaW5zL0N1c3RvbS9lZGl0b3JzL2ljb24tcGlja2VyL2ljb25QaWNrZXJSZXNvdXJjZXMuanM7L0FwcF9QbHVnaW5zL0N1c3RvbS9lZGl0b3JzL2ljb24tcGlja2VyL2RpYWxvZy5jb250cm9sbGVyLmpzOy9BcHBfUGx1Z2lucy9DdXN0b20vZWRpdG9ycy9yZWFkb25seXNldC1lZGl0b3IvY29udHJvbGxlci5qczsvQXBwX1BsdWdpbnMvQ3VzdG9tL3U4cC5VbWJyYWNvLlJlZGlyZWN0cy9TY3JpcHRzL1NlcnZpY2VzL1JlZGlyZWN0c1NlcnZpY2UuanM7L0FwcF9QbHVnaW5zL0N1c3RvbS91OHAuVW1icmFjby5SZWRpcmVjdHMvU2NyaXB0cy9Db250cm9sbGVycy9EYXNoYm9hcmRzL0RlZmF1bHQuanM7L0FwcF9QbHVnaW5zL0N1c3RvbS91OHAuVW1icmFjby5SZWRpcmVjdHMvU2NyaXB0cy9Db250cm9sbGVycy9EaWFsb2dzL1JlZGlyZWN0LmpzOy9BcHBfUGx1Z2lucy9DdXN0b20vdThwLlVtYnJhY28uUmVkaXJlY3RzL1NjcmlwdHMvQ29udHJvbGxlcnMvRGlhbG9ncy9JbXBvcnRFeHBvcnQuanM7L0FwcF9QbHVnaW5zL0N1c3RvbS91OHAuVW1icmFjby5SZWRpcmVjdHMvU2NyaXB0cy9Db250cm9sbGVycy9FZGl0b3JzL0luYm91bmQuanM7L0FwcF9QbHVnaW5zL0N1c3RvbS91OHAuVW1icmFjby5SZWRpcmVjdHMvU2NyaXB0cy9Db250cm9sbGVycy9FZGl0b3JzL0Rlc3RpbmF0aW9uLmpzOy9BcHBfUGx1Z2lucy9DdXN0b20vdThwLlVtYnJhY28uUmVkaXJlY3RzL1NjcmlwdHMvQ29udHJvbGxlcnMvRWRpdG9ycy9PdXRib3VuZC5qczsvQXBwX1BsdWdpbnMvQ3VzdG9tL3U4cC5VbWJyYWNvLlJlZGlyZWN0cy9TY3JpcHRzL0NvbnRyb2xsZXJzL0VkaXRvcnMvT3JpZ2luYWxVcmwuanM7L0FwcF9QbHVnaW5zL0N1c3RvbS91OHAuVW1icmFjby5SZWRpcmVjdHMvU2NyaXB0cy9Db250cm9sbGVycy9FZGl0b3JzL1JhZGlvR3JvdXAuanM7L0FwcF9QbHVnaW5zL0N1c3RvbS91OHAuVW1icmFjby5SZWRpcmVjdHMvU2NyaXB0cy9Db250cm9sbGVycy9FZGl0b3JzL1NpdGUuanM7L0FwcF9QbHVnaW5zL091ci5VbWJyYWNvLk1hdHJ5b3Noa2EvY29udGVudC1pbnRlcmNlcHRvci5qczsvQXBwX1BsdWdpbnMvT3VyLlVtYnJhY28uTWF0cnlvc2hrYS9ncm91cHNlcGFyYXRvci5jb250cm9sbGVyLmpzOy9BcHBfUGx1Z2lucy9PdXIuVW1icmFjby5NYXRyeW9zaGthL2RpcmVjdGl2ZXMvbWF0cnlvc2hrYS10YWJiZWQtY29udGVudC5kaXJlY3RpdmUuanM7L0FwcF9QbHVnaW5zL091ci5VbWJyYWNvLk1hdHJ5b3Noa2EvZGlyZWN0aXZlcy9tYXRyeW9zaGthLXZhbC10YWIuZGlyZWN0aXZlLmpzOy9hcHBfcGx1Z2lucy9PdXIuVW1icmFjby5UaGVEYXNoYm9hcmQvVGhlRGFzaGJvYXJkLmNvbnRyb2xsZXIuanM7L0FwcF9QbHVnaW5zL3VTeW5jOC91c3luY184OTEuanM7L0FwcF9QbHVnaW5zL3VTeW5jOC91U3luY1NlcnZpY2UuanM7L0FwcF9QbHVnaW5zL3VTeW5jOC91U3luY0h1Yi5qczsvQXBwX1BsdWdpbnMvdVN5bmM4L2JhY2tvZmZpY2UvdVN5bmM4L3VTeW5jRGFzaGJvYXJkQ29udHJvbGxlci5qczsvQXBwX1BsdWdpbnMvdVN5bmM4L3NldHRpbmdzL3NldHRpbmdzQ29udHJvbGxlci5qczsvQXBwX1BsdWdpbnMvdVN5bmM4L3NldHRpbmdzL2V4cGFuc2lvbkNvbnRyb2xsZXIuanM7L0FwcF9QbHVnaW5zL3VTeW5jOC9zZXR0aW5ncy91U3luY0NvbnRyb2xsZXIuanM7L0FwcF9QbHVnaW5zL3VTeW5jOC9jaGFuZ2VEaWFsb2dDb250cm9sbGVyLmpzOy9BcHBfUGx1Z2lucy91U3luYzgvY29tcG9uZW50cy91U3luY1JlcG9ydFZpZXdDb21wb25lbnQuanM7L0FwcF9QbHVnaW5zL3VTeW5jOC9jb21wb25lbnRzL3VTeW5jUHJvZ3Jlc3NWaWV3Q29tcG9uZW50LmpzOy9BcHBfUGx1Z2lucy91U3luY0hpc3Rvcnkvc3luY0hpc3RvcnlTZXJ2aWNlLmpzOy9BcHBfUGx1Z2lucy91U3luY0hpc3Rvcnkvc3luY0hpc3RvcnlDb250cm9sbGVyLmpzOy9BcHBfUGx1Z2lucy91U3luY0hpc3Rvcnkvc3luY0hpc3RvcnlEaWFsb2dDb250cm9sbGVyLmpzOw&t=Javascript&cdv=72

**Comment by xanderekpl** [comment]
And please look we are talking about LOGIN PAGE to UMBRACO: -> there is one request to ALL  JS not one per plugin
![image](https://user-images.githubusercontent.com/1809452/127503595-1625d947-1269-4263-bcc3-700906598b34.png)

**Comment by nul800sebastiaan** [comment]
Okay, thanks, that actually isn't what I was expecting (1 dependencyhandler request per plugin). Guess I'm wrong, and it's not even that many files. Strange that we've not seen this problem before. I guess the CDN you're using is very strict.

**Comment by nul800sebastiaan** [comment]
Maybe for now you don't need the `demo-editor`, that's 2 files less, it might just be enough for now if you just remove those 2.

**Comment by xanderekpl** [comment]
yep we will remove not needed of course -> as we know reason,
but like to left my findings so they are not forgotten and you can fix this sooner or later ;)

**Comment by nul800sebastiaan** [comment]
Yeah, it's only a temporary fix!

**Comment by abjerner** [comment]
Hi @xanderekpl 

In your main Web.config, could you try adding the `maxQueryStringLength` attribute to the `<httpRuntime />` element?

```xml
    <httpRuntime requestValidationMode="2.0" enableVersionHeader="false" targetFramework="4.7.2" maxRequestLength="51200"
                 maxQueryStringLength="500"
 />
```

This changes the allowed length on _your server_, so it doesn't directly do anything for your CDN. But ClientDependency seems to listen for this attribute as well, so if you set the attribute to a lower value, ClientDependency will split the output into more files, so that the length of each URL is shorter.

I just tried with 500 for the attribute value to test that ClientDependency actually listens for this, so you may be able to get it working with a higher value.

At least this works when I test locally in my 8.15.0 installation. I seems that you're running in debug mode locally, in which case Umbraco's requests each file individually. If you disable debug mode, ClientDependency should start bundling the files, so you can test and confirm locally before pushing to live.

<hr />

When I check the documentation for the `maxQueryStringLength` attribute, the default value seems to be `2048` bytes:

https://docs.microsoft.com/en-us/dotnet/api/system.web.configuration.httpruntimesection.maxquerystringlength?view=netframework-4.7.2

Seeing that your query string are a lot longer than this, have you by any chance set the `maxQueryStringLength` to something higher?

**Comment by xanderekpl** [comment]
@abjerner I will check this as we have adjusted httpRuntime  becouse of bug from blockeditor,
i will come back with findings tomorrow

**Comment by xanderekpl** [comment]
@nul800sebastiaan @abjerner 
the reason was indeed extended maxQueryStringLength changed by us as workaround for bug with blockeditor.

we've set limits to 8000 (we can't update now to 8.15.1)  but this is enough to split urls to few requests :)

thanks to all involved

**Comment by Attackmonkey** [comment]
Another related issue to this that I've spotted, thanks to this one is that the max query string length can be set in TWO places, the HTTP Runtime element, in `system.web` as in the example above, but it can also be set in in the request filtering area of `system.webserver` in the config file, like so:

```
<security>
  <requestFiltering>
    <requestLimits maxAllowedContentLength="52428800" maxQueryString="250" maxUrl="400"/>
  </requestFiltering>
</security>
```

If you set the max URL length or query string in this way, Umbraco doesn't pick it up and pass it to the Client Dependency Handler, as it's only looking in the HTTP Runtime element. Ideally I guess it should look in BOTH locations and return the lowest of either to be on the safe side. If you have it set as in the example above and not in httpRuntime, then as soon as you disable debugging, the back office stops working, as the ClientDependency URLs are too long for the configured length and they 404, resulting in a blank screen on the back office URL.
