### ISSUE TITLE
Cancel Content Node Permissions Settings does not reset form

### ISSUE THREAD

**Issue by nielslyngsoe** [umbraco/Umbraco-CMS#10778]
### Which *exact* Umbraco version are you using? For example: 8.13.1 - don't just write v8

8.15.0

### Bug summary

When canceling the Permissions dialog, the form or data-model is not reset. meaning when opening again it has same values as it had when you cancelled.

![image](https://user-images.githubusercontent.com/6791648/127866924-1aa9a722-8fa7-4ba4-97cf-4f33a42311d0.png)

### Steps to reproduce

- Right click a Content node
- Click Persmission
- Make sure there is one permission setting for a group
- Click edit on a permission group
- Change some actions.
- Click Cancel
- Click edit on the same permission group again
- See that the changed actions before are still changed.

### Expected result / actual result

That the form value was reset when canceled. Aka. form value are not connected to the model until its submitted. Aka. The data model used for the form should have been a clone and send back when form is submitted.

**Comment by xrasod** [comment]
Added PR for resetting the initial state of the model rather than changing the model the form is using. In effect it should accomplish the same.

**Comment by kjac** [comment]
Looks like this one was fixed in https://github.com/umbraco/Umbraco-CMS/pull/11593 😄
