### ISSUE TITLE
Publish doesn't copy backoffice files

### ISSUE THREAD

**Issue by nikcio** [umbraco/Umbraco-CMS#10773]
### Which *exact* Umbraco version are you using? For example: 8.13.1 - don't just write v8

9.0.0-rc001

### Bug summary

I have a problem where multiple folders aren't copied when publishing a Umbraco 9 project. The files all come from umbraco and are located in the umbraco\ folder.

**List of the folders**

* umbraco\config (This folder is only sometimes omitted)
* umbraco\PartialViewMacros
* umbraco\UmbracoBackOffice
* umbraco\UmbracoInstall
* umbraco\UmbracoWebsite

### Specifics

I have tried modifying the standard configuration of the project file:

**Standard configuration**
```
<ItemGroup>
      <Compile Remove="umbraco\Data\**" />
      <Compile Remove="umbraco\logs\**" />
      <Compile Remove="umbraco\MediaCache\**" />
    </ItemGroup>
    <ItemGroup>
      <EmbeddedResource Remove="umbraco\Data\**" />
      <EmbeddedResource Remove="umbraco\logs\**" />
      <EmbeddedResource Remove="umbraco\MediaCache\**" />
    </ItemGroup>
    <ItemGroup>
      <None Remove="umbraco\Data\**" />
      <None Remove="umbraco\logs\**" />
      <None Remove="umbraco\MediaCache\**" />
    </ItemGroup>
    <ItemGroup>
      <Content Remove="umbraco\Data\**" />
      <Content Remove="umbraco\logs\**" />
      <Content Remove="umbraco\MediaCache\**" />
      <None Include="umbraco\**\*.*">
        <ExcludeFromSingleFile>true</ExcludeFromSingleFile>
        <CopyToPublishDirectory>Always</CopyToPublishDirectory>
      </None>
    </ItemGroup>
```

**Example of changing the file**
```
<ItemGroup>
      <Compile Remove="umbraco\Data\**" />
      <Compile Remove="umbraco\logs\**" />
      <Compile Remove="umbraco\MediaCache\**" />
    </ItemGroup>
    <ItemGroup>
      <EmbeddedResource Remove="umbraco\Data\**" />
      <EmbeddedResource Remove="umbraco\logs\**" />
      <EmbeddedResource Remove="umbraco\MediaCache\**" />
      <EmbeddedResource Update="umbraco\**\*.*">
        <ExcludeFromSingleFile>true</ExcludeFromSingleFile>
        <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
      </EmbeddedResource>
    </ItemGroup>
    <ItemGroup>
      <None Remove="umbraco\Data\**" />
      <None Remove="umbraco\logs\**" />
      <None Remove="umbraco\MediaCache\**" />
      <None Update="umbraco\**\*.*">
        <ExcludeFromSingleFile>true</ExcludeFromSingleFile>
        <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
      </None>
    </ItemGroup>
    <ItemGroup>
      <Content Remove="umbraco\Data\**" />
      <Content Remove="umbraco\logs\**" />
      <Content Remove="umbraco\MediaCache\**" />
      <Content Update="umbraco\**\*.*">
        <ExcludeFromSingleFile>true</ExcludeFromSingleFile>
        <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
      </Content>
    </ItemGroup>
```

It seems no matter what I do the files are not copied over. The only thing I can think of is that it has something to do with the files being copied in during build as a part of the Umbraco.Cms.StaticAssets. But other assets like the ones in wwwroot are copied over perfectly.

I've only been able to publish and get the config folder in the output but I've only been able to do this locally.

**Picture of the folders content after publish**

![image](https://user-images.githubusercontent.com/24605285/127744890-d75afeab-4b8a-456d-895d-7e0c256ad0c3.png)

### Steps to reproduce

Create a new Umbraco 9 project from the template
Build the project to generate the files
Publish the project. Either with the VS publish user interface or with the `dotnet publish` command
You can now see the umbraco folder missing content in the published folder.

### Expected result / actual result

I expected the files to be copied over on publish

---
_This item has been added to our backlog [AB#13091](https://dev.azure.com/umbraco/243e7927-03b2-44e2-908f-d4ac7ea5daaa/_workitems/edit/13091)_

**Comment by nikcio** [comment]
**Note** The same is true if you have any App_Plugins which are being copied in on build

**Comment by elit0451** [comment]
Hi @nikcio, thanks for reporting this issue. I've made a PR that makes sure to copy the correct files on publish. Though, I can't see from your screenshot if you are checking the contents of **.../publish/umbraco** folder because that is where the output from publishing will result (for example from running `dotnet publish`). 🙂

**Comment by nikcio** [comment]
@elit0451 I just needed a quick screenshot of what I meant. The same result was present at the publish folder. 😅
