### ISSUE TITLE
Nested content with mandatory property fails to validate item when it failed validation the first time

### ISSUE THREAD

**Issue by nul800sebastiaan** [umbraco/Umbraco-CMS#10788]
### Which *exact* Umbraco version are you using? For example: 8.13.1 - don't just write v8

8.15.1 and `v8/contrib`

### Bug summary

I thought I'd tested all the scenarios for https://github.com/umbraco/Umbraco-CMS/pull/10563 but I think the only one I didn't test is: the nested content property is NOT mandatory but one of the properties on the NC item IS mandatory.

https://user-images.githubusercontent.com/304656/128149565-291e3114-2f07-4b80-ad58-d176021e9535.mp4

As you can see I can't publish, even saving and then trying to publish doesn't help. I have to save and refresh the page and then I can Save & Publish.

Relates to: #10520 & #8954

### Steps to reproduce

Install this in a clean install to get to the state as shown in the video above. This will show you the issue we're dealing with:

[Issue8954_1.0.0.zip](https://github.com/umbraco/Umbraco-CMS/files/6929836/Issue8954_1.0.0.zip)

---
_This item has been added to our backlog [AB#13189](https://dev.azure.com/umbraco/243e7927-03b2-44e2-908f-d4ac7ea5daaa/_workitems/edit/13189)_

**Comment by nul800sebastiaan** [comment]
Fixed in  https://github.com/umbraco/Umbraco-CMS/pull/10806

**Comment by nul800sebastiaan** [comment]
Cherry picked for 8.14 in 9ccabd51b9783bd68d2a3dcf68827976bf167e00 - also cherry picked the other required PR #10563 to 8.14 and I think it all works now.

Will also be available in 8.15.3 and 8.16.0 and onwards.

**Comment by nul800sebastiaan** [comment]
We'd love it if people could test the builds:

8.14 - https://dev.azure.com/umbraco/Umbraco%20Cms/_build/results?buildId=69291&view=results
8.15 - https://dev.azure.com/umbraco/Umbraco%20Cms/_build/results?buildId=69293&view=results

The build artifacts will appear in about 45 minutes from now where you can click "3 published, 1 consumed":

![image](https://user-images.githubusercontent.com/304656/128508615-2e89cf78-4ed5-4147-8a1e-4db9cb6942c1.png)

After copying in the new files, make sure to update the version of your ClientDependency.config (just make it 1 higher or lower) and then you should be able to test it out.

Releases for 8.14/8.15 are coming on the 17th of Aug, the RC of 8.16 is coming on the 12th. So hopefully in the mean time this will work and help people.

**Comment by jonroberts24** [comment]
Will this update also fix the issue where all the fields show as Required (red asterisk on each field)- but in fact are not required and will allow empty fields when saving?

**Comment by nul800sebastiaan** [comment]
@jonroberts24 I believe that this is the scenario? 

https://user-images.githubusercontent.com/304656/128704096-19d42e7b-4123-4276-bf90-b174c4e2d6a8.mp4

This was a recording tested on the build I linked to above but PLEASE do try it for yourself, since maybe I am overlooking some kind of scenario that you have that I don't have.

I do recommend going to 8.15 in any case though :-)

**Comment by d-gibbs** [comment]
We seem to be experiencing a similar issue in **v8.17.1** - in our particular case the problem arises when using the 'Custom validation' option on nested content items.

Example:

![image](https://user-images.githubusercontent.com/59481722/144831674-65ffb476-516d-4aeb-b0d2-c527accb09eb.png)

Repro steps:

- Trigger custom validation error (in our case enter > 120 chars into textarea field)
- Resolve issue, e.g. update content to be < 120 chars
- Submit form
- Observe that 'Parent validation error' is not cleared and form cannot be saved

Example vid: https://www.awesomescreenshot.com/video/6305908?key=370e4dc68ca2ec18f7adce695a3dbee8

Please let me know if there is anything further you need or if this should be opened as a separate issue.

Thank you
