### ISSUE TITLE
LocalDb Fails with Umbraco 9.0.0 rc1

### ISSUE THREAD

**Issue by maldworth** [umbraco/Umbraco-CMS#10790]
### Which *exact* Umbraco version are you using? For example: 8.13.1 - don't just write v8

v9.0.0 rc1

### Bug summary

Fails to use LocalDb for the sqlserver connection string "umbracoDbDSN"

### Steps to reproduce

I followed instructions here using the template to create a project.
https://umbraco.com/blog/umbraco-9-release-candidate/

### Expected result / actual result

Expected Resultes:
Should work with LocalDb as it does with a full SQL Server

Actual Results:
I made the connection string
```
"ConnectionStrings": {
  "umbracoDbDSN": "Data Source=(LocalDb)\\MSSQLLocalDB;Database=Umbraco9Test;Trusted_Connection=True;"
}
```

And when I run the solution, I get this error:
![image](https://user-images.githubusercontent.com/187903/128197766-2cf2a161-b7ee-4e87-a3a2-f2dbe5367f01.png)

**Comment by nul800sebastiaan** [comment]
That's probably fixed with this PR - https://github.com/umbraco/Umbraco-CMS/pull/10766
I believe a new build should be available on the nightlies server for this, since this PR was merged yesterday.
