### ISSUE TITLE
Update ImageProcessor dependencies to the latest version

### ISSUE THREAD

**Issue by nul800sebastiaan** [umbraco/Umbraco-CMS#10807]
We are shipping with rather outdated dependencies for ImageProcessor.

**Comment by nul800sebastiaan** [comment]
Fixed in https://github.com/umbraco/Umbraco-CMS/commit/7d0558d59f05172b8b7bbe0af8904a881b22d916

**Comment by tl-ben** [comment]
UmbracoCms.NuSpec now has a reference to ImageProcessor.Web 4.12.1.100, it should be 4.12.1 (there is no .100 package).  If you try and get umbraco 8.16 rc via nuget it currently fails because it can't find a version of ImageProcessor.Web that is valid.

**Comment by tl-ben** [comment]
Oops, ignore me, it's been corrected in 8.16 branch.  The live rc nuget package doesn't work though (might not be an issue).

**Comment by nul800sebastiaan** [comment]
Yes, very sorry about that, I believe you should be able to work around it with some ignoring of dependencies - https://github.com/umbraco/Umbraco-CMS/issues/10837
