### ISSUE TITLE
Multinode Treepicker: not showing title and description in Content Editor

### ISSUE THREAD

**Issue by GogoDeveloper** [umbraco/Umbraco-CMS#10817]
### Which *exact* Umbraco version are you using? For example: 8.13.1 - don't just write v8

9.0.0-rc001

### Bug summary

When adding a Property with the Multinode Treepicker as Data Type, the title and description are invisible in the content editor.

Document Type Property:
![image](https://user-images.githubusercontent.com/44864908/128673129-35396b8f-4133-4ba3-af99-ca0ce6847ba2.png)

Content Editor:
![image](https://user-images.githubusercontent.com/44864908/128673175-d6908c3e-6cc9-479d-9ac8-b75d7a6826ca.png)

### Steps to reproduce

1. Added another language, and forgot to set the new language as default.
2. Created a document type.
3. Created property with Multinode Treepicker as data type.
4. Set the document type to allow vary by culture.
5. Set the other language as default.
6. Deleted the document type.
7. Recreated the document type.

### Expected result / actual result

Expected Result:
![image](https://user-images.githubusercontent.com/44864908/128673821-6a17a2aa-ab59-43b8-ae75-a589eca1fff5.png)

Actual Result:
![image](https://user-images.githubusercontent.com/44864908/128673911-e31f78de-eeac-4747-b044-8f759c3f8ba5.png)

**Comment by GogoDeveloper** [comment]
I changed the alias of the property and then it worked. But as soon as I changed it back to "navigation" the problem reappeared.

**Comment by bjarnef** [comment]
It seems this may be related to this issue: https://github.com/umbraco/Umbraco-CMS/issues/9816

**Comment by GogoDeveloper** [comment]
> It seems this may be related to this issue: #9816

Yeah seems so.

**Comment by nul800sebastiaan** [comment]
👍 Thanks for finding the other issue @bjarnef and thanks @GogoDeveloper for reporting. Right now it's not possible to use the `navigation`  alias, not sure why. We'd love some help getting https://github.com/umbraco/Umbraco-CMS/issues/9816 fixed though, which is why it's marked as "up for grabs". I'll close this one as a duplicate.
