### ISSUE TITLE
When adding Nested Content "Type to filter..." does not work

### ISSUE THREAD

**Issue by Myster** [umbraco/Umbraco-CMS#10816]
### Which *exact* Umbraco version are you using? For example: 8.13.1 - don't just write v8

8.10.1

### Bug summary

When adding an element to a Nested Content property, there is a box "Type to filter..." 
Typing in this box does not filter the list of controls below.

### Steps to reproduce

Create property of type Nested Content .
Create many Controls to add to it.
Edit a page with that control
Click Add Content for that property
Type something in the 'Type to filter...' box

### Expected result / actual result

I expect to see filtered results but I see this:
![image](https://user-images.githubusercontent.com/354777/128651406-8f73250d-6d77-49d5-a9ab-2bc99e6fcd3c.png)

Also note:
The same issue occurs in the permissions tab of the Doctype Editor:
![image](https://user-images.githubusercontent.com/354777/128651786-d66cbe4a-f3f4-43cd-b420-f71c9e1e2c6b.png)

**Comment by bjarnef** [comment]
I think the filtering issue in child node selector should have been fixed in https://github.com/umbraco/Umbraco-CMS/pull/9641 so it should have been fixed from v8.10.2 patch release.

I don't recall filtering is an issue in Nested Content in latest releases, but I haven't checked that part.

**Comment by nul800sebastiaan** [comment]
I just had a look in 8.15 and this has indeed been fixed since! 👍
