### ISSUE TITLE
Invite User is not working

### ISSUE THREAD

**Issue by russellshome** [umbraco/Umbraco-CMS#10828]
### Which *exact* Umbraco version are you using? For example: 8.13.1 - don't just write v8

8.15.1

### Bug summary

Invite User fails to send email and displays an empty message.

### Specifics

![InviteUserIssue](https://user-images.githubusercontent.com/8239408/128941666-fa637f50-62e8-42a9-a210-e96b285ca1c4.png)

### Steps to reproduce

Create new Umbraco website

In web.config set up mailSettings such as below (or any valid SMTP settings)

&lt;mailSettings&gt;
      &lt;smtp deliveryMethod="SpecifiedPickupDirectory" from="noreply@testing.com"&gt;
        &lt;specifiedPickupDirectory pickupDirectoryLocation="c:\mail" /&gt;
      &lt;/smtp&gt;
&lt;/mailSettings&gt;

Go to Umbraco Admin - Users - Invite User
Enter valid information and click Send Invite

### Expected result / actual result

Expected: 
- Mail is sent
- User is created

Actual: 
- Mail is not sent
- there are javascript errors 
- an empty message box is displayed.
- the user IS created

**Comment by russellshome** [comment]
I tried creating a site using version 8.14.2 0 Invite User works fine in that version.

I think the issue must have been introduced in 8.15.0

**Comment by emma-hq** [comment]
Hey @russellshome 

Thanks for the report and the info - super helpful when people narrow things down to a specific version for us. I'll try to reproduce and report back here.

Emma

**Comment by nul800sebastiaan** [comment]
Thanks @russellshome this will be fixed in the upcoming 8.15.2 next week: https://github.com/umbraco/Umbraco-CMS/issues/10746
