### ISSUE TITLE
RedirectToCurrentUmbracoPage not working with UrlProviderMode Absolute

### ISSUE THREAD

**Issue by konius** [umbraco/Umbraco-CMS#10820]
### Which *exact* Umbraco version are you using? For example: 8.13.1 - don't just write v8

9.0.0-rc001

### Bug summary

In SurfaceController if using `RedirectToCurrentUmbracoPage` with  `UrlProviderMode Absolute` throws an exception (attached).

![Screenshot 2021-08-09 190038](https://user-images.githubusercontent.com/3933562/128737165-715445a9-185e-42c0-8d47-eb7d0feae34a.jpg)

### Specifics

Setting the following in the apsettings.json:

```
"WebRouting": {
  "UrlProviderMode": "Absolute"
}
```

If the provider is `Relative` - works.

### Steps to reproduce

1. Create a test SurfaceController
2. Post to surface controller using `Html.BeginUmbracoForm<TestController>`
3. Return `RedirectToCurrentUmbracoPage`

### Expected result / actual result

Expected to be redirected to the current page.

**Comment by Zeegaan** [comment]
Issue should now be fixed in https://github.com/umbraco/Umbraco-CMS/pull/10838 

Thank you for reporting this 👍
