### ISSUE TITLE
Update v8.15.0 to 8.16.0-RC or create a new 8.16.0-RC website via NuGet fails

### ISSUE THREAD

**Issue by idseefeld** [umbraco/Umbraco-CMS#10837]
### Which *exact* Umbraco version are you using? For example: 8.13.1 - don't just write v8

8.15.0 / 8.16.0-RC

### Bug summary

A dependency to ImageProcessor.Web is missing. ERROR message:
```
Attempting to gather dependency information for package 'UmbracoCms.8.16.0-rc' with respect to project 'ukontor', targeting '.NETFramework,Version=v4.7.2'
Gathering dependency information took 7,1 sec
Attempting to resolve dependencies for package 'UmbracoCms.8.16.0-rc' with DependencyBehavior 'Lowest'
Unable to find a version of 'ImageProcessor.Web' that is compatible with 'UmbracoCms 8.16.0-rc constraint: ImageProcessor.Web (>= 4.12.1.100 && < 4.999999.0)'.
Time Elapsed: 00:00:07.9941868
========== Finished ==========
```
Latest release of ImageProcessor.Web on NuGet is 4.12.1 and not 4.12.1.100

### Steps to reproduce

Just create a new empty .Net framework website and try to install v8.16.0-RC.

**Comment by nul800sebastiaan** [comment]
Ah, thank! An unfortunate typo slipped in, will fix! For now you can add `-IgnoreDependencies` I think and upgrade ImageProcessor manually.

**Comment by nul800sebastiaan** [comment]
Fixed in 33feb808dd934cd4b1160ea9bd66b7783507d05f - thanks again! 👍

**Comment by ronaldbarendse** [comment]
To elaborate on the suggested workaround provided by @nul800sebastiaan: the following commands can be executed on the Package Manager Console to install or update to 8.16 RC.

```powershell
Install-Package UmbracoCms.Web -Version 8.16.0-rc
Install-Package ImageProcessor.Web -Version 4.12.1
Install-Package ImageProcessor.Web.Config -Version 2.6.0
Install-Package Microsoft.AspNet.SignalR.Core -Version 2.4.2
Install-Package Microsoft.CodeDom.Providers.DotNetCompilerPlatform -Version 3.6.0
Install-Package UmbracoCms -Version 8.16.0-rc -IgnoreDependencies
```

Note that you might end up with dependency errors if you try to restore the NuGet packages (e.g. on a CI/build environment) or try to update/install other packages... This issue is already fixed for the final 8.16 release, so this 'only' affects testing the RC 😇

**Comment by nul800sebastiaan** [comment]
That works, although I added `Serilog.Sinks.Async` and `Serilog.Sinks.Map` which I needed to update (coming from 8.13).

**Comment by ronaldbarendse** [comment]
Ah yes, I should mention I was upgrading from 8.15.2 😄 When upgrading from earlier versions, you might indeed need to manually add/update other dependencies as well...
