### ISSUE TITLE
SqlMainDomLock config fails clean install on local environment

### ISSUE THREAD

**Issue by bjarnef** [umbraco/Umbraco-CMS#10848]
### Which *exact* Umbraco version are you using? For example: 8.13.1 - don't just write v8

8.14.1

### Bug summary

When hosting an Umbraco site on Azure it is recommended to set SqlMainDomLock: https://our.umbraco.com/Documentation/Fundamentals/Setup/Server-Setup/azure-web-apps#recommended-configuration

```
<add key="Umbraco.Core.MainDom.Lock" value="SqlMainDomLock" />
```

This also works great, however on local with this setting it cause issues when you want to clone down the project and run a clean install - and afterwards import settings and content with uSync.

With no LocalDb in App_Data and the following connection string:

```
<connectionStrings>
	<remove name="umbracoDbDSN" />
	<add name="umbracoDbDSN" connectionString="Data Source=(LocalDB)\MSSQLLocalDB;AttachDbFilename=|DataDirectory|\Umbraco.mdf;Integrated Security=True" providerName="System.Data.SqlClient" />
</connectionStrings>
```

and cleaned version status:

```
<add key="Umbraco.Core.ConfigurationStatus" value="" />
```

It then fails booting the site:

![image](https://user-images.githubusercontent.com/2919859/129318331-add5525e-56e3-4dad-9934-b5c8c4de5bef.png)

### Steps to reproduce

If I comment out the `Umbraco.Core.MainDom.Lock` config it start the installer. However currently with v8.14.1 I am getting errors. Not sure if something has changed regarding this in v8.14, but Umbraco was recently upgraded (from v8.9.0) in the project and previous I recall this didn't failed with these errors, but showed the installer steps.

![image](https://user-images.githubusercontent.com/2919859/129321130-d7923138-90c2-4d0b-b1fb-63909b7ba367.png)

With LocalDb installed it used the create a LocalDb (.mdf) in App_Data folder.

```
{"@t":"2021-08-13T07:43:51.9501436Z","@mt":"Booting site '{HostingSiteName}', app '{HostingApplicationID}', path '{HostingPhysicalPath}', server '{MachineName}'.","HostingSiteName":"myproject","HostingApplicationID":"/LM/W3SVC/3/ROOT","HostingPhysicalPath":"C:\\VSProjects\\my-project\\MyProject.Web\\","MachineName":"LAPTOP-TVMJ2DRH","SourceContext":"Umbraco.Core.Runtime.CoreRuntime","ProcessId":18004,"ProcessName":"w3wp","ThreadId":59,"AppDomainId":23,"AppDomainAppId":"LMW3SVC3ROOT","Log4NetLevel":"INFO ","HttpRequestNumber":1,"HttpRequestId":"c275ed6d-6a92-4204-a22f-e9373d008033"}
{"@t":"2021-08-13T07:43:52.1705559Z","@mt":"Acquiring.","SourceContext":"Umbraco.Core.Runtime.MainDom","ProcessId":18004,"ProcessName":"w3wp","ThreadId":59,"AppDomainId":23,"AppDomainAppId":"LMW3SVC3ROOT","MachineName":"LAPTOP-TVMJ2DRH","Log4NetLevel":"INFO ","HttpRequestNumber":1,"HttpRequestId":"c275ed6d-6a92-4204-a22f-e9373d008033"}
{"@t":"2021-08-13T07:43:52.1775362Z","@mt":"Acquired.","SourceContext":"Umbraco.Core.Runtime.MainDom","ProcessId":18004,"ProcessName":"w3wp","ThreadId":59,"AppDomainId":23,"AppDomainAppId":"LMW3SVC3ROOT","MachineName":"LAPTOP-TVMJ2DRH","Log4NetLevel":"INFO ","HttpRequestNumber":1,"HttpRequestId":"c275ed6d-6a92-4204-a22f-e9373d008033"}
{"@t":"2021-08-13T07:43:52.1914983Z","@mt":"{StartMessage} [Timing {TimingId}]","StartMessage":"Resolving composer types.","TimingId":"a9c9afe","SourceContext":"Umbraco.Core.Runtime.CoreRuntime","ProcessId":18004,"ProcessName":"w3wp","ThreadId":59,"AppDomainId":23,"AppDomainAppId":"LMW3SVC3ROOT","MachineName":"LAPTOP-TVMJ2DRH","Log4NetLevel":"INFO ","HttpRequestNumber":1,"HttpRequestId":"c275ed6d-6a92-4204-a22f-e9373d008033"}
{"@t":"2021-08-13T07:43:52.3142157Z","@mt":"{EndMessage} ({Duration}ms) [Timing {TimingId}]","EndMessage":"Resolved.","Duration":118,"TimingId":"a9c9afe","SourceContext":"Umbraco.Core.Runtime.CoreRuntime","ProcessId":18004,"ProcessName":"w3wp","ThreadId":59,"AppDomainId":23,"AppDomainAppId":"LMW3SVC3ROOT","MachineName":"LAPTOP-TVMJ2DRH","Log4NetLevel":"INFO ","HttpRequestNumber":1,"HttpRequestId":"c275ed6d-6a92-4204-a22f-e9373d008033"}
{"@t":"2021-08-13T07:43:54.8257745Z","@mt":"{EndMessage} ({Duration}ms) [Timing {TimingId}]","EndMessage":"Booted.","Duration":2961,"TimingId":"c6c947f","SourceContext":"Umbraco.Core.Runtime.CoreRuntime","ProcessId":18004,"ProcessName":"w3wp","ThreadId":59,"AppDomainId":23,"AppDomainAppId":"LMW3SVC3ROOT","MachineName":"LAPTOP-TVMJ2DRH","Log4NetLevel":"INFO ","HttpRequestNumber":1,"HttpRequestId":"c275ed6d-6a92-4204-a22f-e9373d008033"}
{"@t":"2021-08-13T07:43:55.6361708Z","@mt":"New url {Url} detected, re-discovering application url.","Url":"http://faceaface.com.local:80/umbraco","SourceContext":"Umbraco.Core.Sync.ApplicationUrlHelper","ProcessId":18004,"ProcessName":"w3wp","ThreadId":120,"AppDomainId":23,"AppDomainAppId":"LMW3SVC3ROOT","MachineName":"LAPTOP-TVMJ2DRH","Log4NetLevel":"INFO ","HttpRequestNumber":2,"HttpRequestId":"b0d5571b-4179-4dfe-a68b-eddb539cbb77"}
{"@t":"2021-08-13T07:43:55.6481760Z","@mt":"ApplicationUrl: {UmbracoAppUrl} (UmbracoModule request)","UmbracoAppUrl":"http://faceaface.com.local:80/umbraco","SourceContext":"Umbraco.Core.Sync.ApplicationUrlHelper","ProcessId":18004,"ProcessName":"w3wp","ThreadId":120,"AppDomainId":23,"AppDomainAppId":"LMW3SVC3ROOT","MachineName":"LAPTOP-TVMJ2DRH","Log4NetLevel":"INFO ","HttpRequestNumber":2,"HttpRequestId":"b0d5571b-4179-4dfe-a68b-eddb539cbb77"}
{"@t":"2021-08-13T07:43:56.9703349Z","@mt":"Umbraco must install or upgrade.","@l":"Warning","SourceContext":"Umbraco.Web.UmbracoModule","ProcessId":18004,"ProcessName":"w3wp","ThreadId":120,"AppDomainId":23,"AppDomainAppId":"LMW3SVC3ROOT","MachineName":"LAPTOP-TVMJ2DRH","Log4NetLevel":"WARN ","HttpRequestNumber":2,"HttpRequestId":"b0d5571b-4179-4dfe-a68b-eddb539cbb77"}
{"@t":"2021-08-13T07:43:59.5578490Z","@mt":"Configured database is reporting as not being available.","@l":"Warning","@x":"System.Data.SqlClient.SqlException (0x80131904): An attempt to attach an auto-named database for file C:\\VSProjects\\my-project\\MyProject.Web\\App_Data\\Umbraco.mdf failed. A database with the same name exists, or specified file cannot be opened, or it is located on UNC share.\r\n   at System.Data.SqlClient.SqlInternalConnectionTds..ctor(DbConnectionPoolIdentity identity, SqlConnectionString connectionOptions, SqlCredential credential, Object providerInfo, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance, SqlConnectionString userConnectionOptions, SessionData reconnectSessionData, DbConnectionPool pool, String accessToken, Boolean applyTransientFaultHandling, SqlAuthenticationProviderManager sqlAuthProviderManager)\r\n   at System.Data.SqlClient.SqlConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningConnection, DbConnectionOptions userOptions)\r\n   at System.Data.ProviderBase.DbConnectionFactory.CreatePooledConnection(DbConnectionPool pool, DbConnection owningObject, DbConnectionOptions options, DbConnectionPoolKey poolKey, DbConnectionOptions userOptions)\r\n   at System.Data.ProviderBase.DbConnectionPool.CreateObject(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)\r\n   at System.Data.ProviderBase.DbConnectionPool.UserCreateRequest(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)\r\n   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)\r\n   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)\r\n   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)\r\n   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)\r\n   at System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)\r\n   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)\r\n   at System.Data.SqlClient.SqlConnection.Open()\r\n   at Umbraco.Core.Persistence.DbConnectionExtensions.IsAvailable(IDbConnection connection) in D:\\a\\1\\s\\src\\Umbraco.Core\\Persistence\\DbConnectionExtensions.cs:line 55\r\nClientConnectionId:47798efc-59a9-4ed1-aa18-6ea7ea4a198c\r\nError Number:15350,State:1,Class:14","SourceContext":"System.Data.IDbConnection","ProcessId":18004,"ProcessName":"w3wp","ThreadId":144,"AppDomainId":23,"AppDomainAppId":"LMW3SVC3ROOT","MachineName":"LAPTOP-TVMJ2DRH","Log4NetLevel":"WARN ","HttpSessionId":"f0e3k2raiv3mx1i44o5iz3cs","HttpRequestNumber":3,"HttpRequestId":"d5aeb144-514f-4f87-b44d-f92373f6b254"}
{"@t":"2021-08-13T07:43:59.5728105Z","@mt":"An error occurred in InstallStatus trying to check upgrades","@l":"Error","@x":"System.Exception: Cannot connect to the database.\r\n   at Umbraco.Core.Persistence.UmbracoDatabaseFactory.Initialize() in D:\\a\\1\\s\\src\\Umbraco.Core\\Persistence\\UmbracoDatabaseFactory.cs:line 225\r\n   at System.Threading.LazyInitializer.EnsureInitializedCore[T](T& target, Boolean& initialized, Object& syncLock, Func`1 valueFactory)\r\n   at Umbraco.Core.Persistence.UmbracoDatabaseFactory.EnsureInitialized() in D:\\a\\1\\s\\src\\Umbraco.Core\\Persistence\\UmbracoDatabaseFactory.cs:line 207\r\n   at Umbraco.Core.Persistence.UmbracoDatabaseFactory.CreateDatabase() in D:\\a\\1\\s\\src\\Umbraco.Core\\Persistence\\UmbracoDatabaseFactory.cs:line 261\r\n   at Umbraco.Core.Scoping.Scope.get_Database() in D:\\a\\1\\s\\src\\Umbraco.Core\\Scoping\\Scope.cs:line 241\r\n   at Umbraco.Core.Migrations.Install.DatabaseBuilder.IsUmbracoInstalled() in D:\\a\\1\\s\\src\\Umbraco.Core\\Migrations\\Install\\DatabaseBuilder.cs:line 117\r\n   at Umbraco.Web.Install.InstallHelper.get_IsBrandNewInstall() in D:\\a\\1\\s\\src\\Umbraco.Web\\Install\\InstallHelper.cs:line 148\r\n   at Umbraco.Web.Install.InstallHelper.<InstallStatus>d__10.MoveNext() in D:\\a\\1\\s\\src\\Umbraco.Web\\Install\\InstallHelper.cs:line 86","SourceContext":"Umbraco.Web.Install.InstallHelper","ProcessId":18004,"ProcessName":"w3wp","ThreadId":144,"AppDomainId":23,"AppDomainAppId":"LMW3SVC3ROOT","MachineName":"LAPTOP-TVMJ2DRH","Log4NetLevel":"ERROR","HttpSessionId":"f0e3k2raiv3mx1i44o5iz3cs","HttpRequestNumber":3,"HttpRequestId":"d5aeb144-514f-4f87-b44d-f92373f6b254"}
{"@t":"2021-08-13T07:44:02.5824833Z","@mt":"Configured database is reporting as not being available.","@l":"Warning","@x":"System.Data.SqlClient.SqlException (0x80131904): An attempt to attach an auto-named database for file C:\\VSProjects\\my-project\\MyProject.Web\\App_Data\\Umbraco.mdf failed. A database with the same name exists, or specified file cannot be opened, or it is located on UNC share.\r\n   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)\r\n   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)\r\n   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)\r\n   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)\r\n   at System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)\r\n   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)\r\n   at System.Data.SqlClient.SqlConnection.Open()\r\n   at Umbraco.Core.Persistence.DbConnectionExtensions.IsAvailable(IDbConnection connection) in D:\\a\\1\\s\\src\\Umbraco.Core\\Persistence\\DbConnectionExtensions.cs:line 55\r\nClientConnectionId:47798efc-59a9-4ed1-aa18-6ea7ea4a198c\r\nError Number:15350,State:1,Class:14","SourceContext":"System.Data.IDbConnection","ProcessId":18004,"ProcessName":"w3wp","ThreadId":213,"AppDomainId":23,"AppDomainAppId":"LMW3SVC3ROOT","MachineName":"LAPTOP-TVMJ2DRH","Log4NetLevel":"WARN ","HttpRequestNumber":4,"HttpRequestId":"5b8f99d8-1c1d-46d3-90d6-c94aca473154"}
{"@t":"2021-08-13T07:44:02.5864709Z","@mt":"An unhandled exception occurred","@l":"Error","@x":"System.Exception: Cannot connect to the database.\r\n   at Umbraco.Core.Persistence.UmbracoDatabaseFactory.Initialize() in D:\\a\\1\\s\\src\\Umbraco.Core\\Persistence\\UmbracoDatabaseFactory.cs:line 225\r\n   at System.Threading.LazyInitializer.EnsureInitializedCore[T](T& target, Boolean& initialized, Object& syncLock, Func`1 valueFactory)\r\n   at Umbraco.Core.Persistence.UmbracoDatabaseFactory.EnsureInitialized() in D:\\a\\1\\s\\src\\Umbraco.Core\\Persistence\\UmbracoDatabaseFactory.cs:line 207\r\n   at Umbraco.Core.Persistence.UmbracoDatabaseFactory.get_SqlContext() in D:\\a\\1\\s\\src\\Umbraco.Core\\Persistence\\UmbracoDatabaseFactory.cs:line 176\r\n   at Umbraco.Core.Scoping.Scope.get_SqlContext() in D:\\a\\1\\s\\src\\Umbraco.Core\\Scoping\\Scope.cs:line 147\r\n   at Umbraco.Core.Persistence.Repositories.Implement.DomainRepository.GetBaseQuery(Boolean isCount) in D:\\a\\1\\s\\src\\Umbraco.Core\\Persistence\\Repositories\\Implement\\DomainRepository.cs:line 53\r\n   at Umbraco.Core.Persistence.Repositories.Implement.DomainRepository.PerformGetAll(Int32[] ids) in D:\\a\\1\\s\\src\\Umbraco.Core\\Persistence\\Repositories\\Implement\\DomainRepository.cs:line 37\r\n   at Umbraco.Core.Cache.FullDataSetRepositoryCachePolicy`2.GetAllCached(Func`2 performGetAll) in D:\\a\\1\\s\\src\\Umbraco.Core\\Cache\\FullDataSetRepositoryCachePolicy.cs:line 166\r\n   at Umbraco.Core.Cache.FullDataSetRepositoryCachePolicy`2.GetAll(TId[] ids, Func`2 performGetAll)\r\n   at Umbraco.Core.Persistence.Repositories.Implement.DomainRepository.GetAll(Boolean includeWildcards)\r\n   at Umbraco.Core.Services.Implement.DomainService.GetAll(Boolean includeWildcards) in D:\\a\\1\\s\\src\\Umbraco.Core\\Services\\Implement\\DomainService.cs:line 72\r\n   at Skybrud.Umbraco.Redirects.Domains.DomainUtils.FindDomainForUri(IDomainService domainService, Uri current)\r\n   at Skybrud.Umbraco.Redirects.Routing.RedirectsInjectedModule.ContextOnEndRequest(Object sender, EventArgs eventArgs)\r\n   at System.Web.HttpApplication.SyncEventExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute()\r\n   at System.Web.HttpApplication.ExecuteStepImpl(IExecutionStep step)\r\n   at System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously)","SourceContext":"Umbraco.Web.UmbracoApplicationBase","ProcessId":18004,"ProcessName":"w3wp","ThreadId":213,"AppDomainId":23,"AppDomainAppId":"LMW3SVC3ROOT","MachineName":"LAPTOP-TVMJ2DRH","Log4NetLevel":"ERROR","HttpRequestNumber":4,"HttpRequestId":"5b8f99d8-1c1d-46d3-90d6-c94aca473154"}
{"@t":"2021-08-13T07:44:03.0701206Z","@mt":"Configured database is reporting as not being available.","@l":"Warning","@x":"System.Data.SqlClient.SqlException (0x80131904): An attempt to attach an auto-named database for file C:\\VSProjects\\my-project\\MyProject.Web\\App_Data\\Umbraco.mdf failed. A database with the same name exists, or specified file cannot be opened, or it is located on UNC share.\r\n   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)\r\n   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)\r\n   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)\r\n   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)\r\n   at System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)\r\n   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)\r\n   at System.Data.SqlClient.SqlConnection.Open()\r\n   at Umbraco.Core.Persistence.DbConnectionExtensions.IsAvailable(IDbConnection connection) in D:\\a\\1\\s\\src\\Umbraco.Core\\Persistence\\DbConnectionExtensions.cs:line 55\r\nClientConnectionId:47798efc-59a9-4ed1-aa18-6ea7ea4a198c\r\nError Number:15350,State:1,Class:14","SourceContext":"System.Data.IDbConnection","ProcessId":18004,"ProcessName":"w3wp","ThreadId":120,"AppDomainId":23,"AppDomainAppId":"LMW3SVC3ROOT","MachineName":"LAPTOP-TVMJ2DRH","Log4NetLevel":"WARN ","HttpRequestNumber":5,"HttpRequestId":"f4978ca2-82c2-4ef2-a749-b52e5e3c1f40"}

```

**Comment by bjarnef** [comment]
It seems I needed an empty connection string as well to trigger the installer. I can't remember if I needed to clear this, when I previous tried this on v8.9.0

```
<connectionStrings>
	<remove name="umbracoDbDSN" />
	<add name="umbracoDbDSN" connectionString="" providerName="System.Data.SqlClient" />
</connectionStrings>
```

![image](https://user-images.githubusercontent.com/2919859/129324069-760f8f4d-45c6-49e0-bc15-3c4fb3ff748b.png)

**Comment by nul800sebastiaan** [comment]
I tried your scenario with 8.15.1 and without the key `<add key="Umbraco.Core.MainDom.Lock" value="SqlMainDomLock" />` in the web.config, like so

```xml
  <appSettings>
    <add key="Umbraco.Core.ConfigurationStatus" value=""/>
    <add key="Umbraco.Core.ReservedUrls" value=""/>
    <add key="Umbraco.Core.ReservedPaths" value=""/>
    <add key="Umbraco.Core.Path" value="~/umbraco"/>
    <add key="Umbraco.Core.HideTopLevelNodeFromPath" value="true"/>
    <add key="Umbraco.Core.TimeOutInMinutes" value="360"/>
    <add key="Umbraco.Core.DefaultUILanguage" value="en-US"/>
    <add key="Umbraco.Core.UseHttps" value="false"/>
    <add key="Umbraco.Core.AllowContentDashboardAccessToAllUsers" value="true"/>
    <add key="Umbraco.Core.ContentDashboardBaseUrl" value=""/>
    <add key="ValidationSettings:UnobtrusiveValidationMode" value="None"/>
    <add key="webpages:Enabled" value="false"/>
    <add key="enableSimpleMembership" value="false"/>
    <add key="autoFormsAuthentication" value="false"/>
    <add key="dataAnnotations:dataTypeAttribute:disableRegEx" value="false"/>
    <add key="owin:appStartup" value="UmbracoDefaultOwinStartup"/>
    <add key="Umbraco.ModelsBuilder.Enable" value="true"/>
    <add key="Umbraco.ModelsBuilder.ModelsMode" value="PureLive"/>
    <add key="Umbraco.Web.PublishedCache.NuCache.Serializer" value="MsgPack"/>
    <add key="Umbraco.Core.VersionCheckPeriod" value="0"/>
	
  </appSettings>
  <!--
        Important: if you're upgrading Umbraco, do not clear the connectionString/providerName during your Web.config merge.
    -->
  <connectionStrings>
    <remove name="umbracoDbDSN"/>
    	<add name="umbracoDbDSN" connectionString="Data Source=(LocalDB)\MSSQLLocalDB;AttachDbFilename=|DataDirectory|\Umbraco.mdf;Integrated Security=True" providerName="System.Data.SqlClient" />
  </connectionStrings>
```

This results in a failure as it's trying to use the specified database, which does not exist. 
In 8.9.1 this scenario creates a JS error and never starts the installer

![image](https://user-images.githubusercontent.com/304656/129376361-9f2b1b53-9d42-4a35-9437-665ed6009e41.png)

So, yes, always clear the connection string if the database does not exist, that's how it's always worked: a fresh install can be done by clearing `Umbraco.Core.ConfigurationStatus` and `connectionString`.

**Comment by bjarnef** [comment]
@nul800sebastiaan the issue it not about running the installer, but the boot fails when this key exists in web.config:

``` 
<add key="Umbraco.Core.MainDom.Lock" value="SqlMainDomLock" />
```

When Umbraco is installed, there is no issues with having this key in web.config, but it I include this in web.config because it is recommended on Azure and another colleague clone down the project by clearing the clearing `Umbraco.Core.ConfigurationStatus` and `connectionString` the person also need to comment out `Umbraco.Core.MainDom.Lock` which otherwise will cause this boot error.

**Comment by nul800sebastiaan** [comment]
I don't understand your scenario then, which values exactly would you expect to work in web.config? I believe I tried the scenario's you were describing and without MsgPack they would also fail.

**Comment by bjarnef** [comment]
1. Install Umbraco with default starterkit (SQL CE)
2. Add `<add key="Umbraco.Core.MainDom.Lock" value="SqlMainDomLock" />` to web.config
3. Boot failed

![image](https://user-images.githubusercontent.com/2919859/129556452-6b108414-6925-4b14-8294-6edd70bdd5c9.png)

With same project deleted `Umbraco.sdf` in App_Data folder, reset connection string an empty string and `Umbraco.Core.ConfigurationStatus` to an empty string.

```
<add key="Umbraco.Core.ConfigurationStatus" value="" />
```

```
<connectionStrings>
      <remove name="umbracoDbDSN" />
      <add name="umbracoDbDSN" connectionString="" />
</connectionStrings>
```

When running site again it trigger the installation:

![image](https://user-images.githubusercontent.com/2919859/129557302-95fcf38d-84de-4be5-9a5c-4cae819bbec6.png)

With LocalDB installed install Umbraco using custom LocalDB connection string: `Data Source=(LocalDB)\MSSQLLocalDB;AttachDbFilename=|DataDirectory|\Umbraco.mdf;Integrated Security=True`

![image](https://user-images.githubusercontent.com/2919859/129557528-1c7953fe-1e60-49e1-b568-3c08102f9435.png)

But if the web.config contains `<add key="Umbraco.Core.MainDom.Lock" value="SqlMainDomLock" />` the booting fails.
It doesn't seems to be an issue running the site if the database already exists and Umbraco is installed.

**Comment by bjarnef** [comment]
@nul800sebastiaan I don't recall what I previous did to run a clean install.
For this specific project I have written down I needed to choose custom connection string and pasting `Data Source=(LocalDB)\MSSQLLocalDB;AttachDbFilename=|DataDirectory|\Umbraco.mdf;Integrated Security=True`

![image](https://user-images.githubusercontent.com/2919859/129689356-40562663-00d9-460f-ab97-82f1ee388a0e.png)

However I don't recall if, with LocalDb installed, the installer would create the Umbraco.mdf in App_Data or if I first created the Umbraco.mdf with a tool.

**Comment by bjarnef** [comment]
Okay, I created the mdf-file from SSMS and copied it to App_Data folder. After that I could run installing using the connection string `Data Source=(LocalDB)\MSSQLLocalDB;AttachDbFilename=|DataDirectory|\Umbraco.mdf;Integrated Security=True`.

However I needed to comment out `<add key="Umbraco.Core.MainDom.Lock" value="SqlMainDomLock" />` locally to run installation, otherwise the booting fails.

It could of course have a transform of web.config to only insert `<add key="Umbraco.Core.MainDom.Lock" value="SqlMainDomLock" />` on e.g. staging, development and release/live environments on Azure, but not sure if there's a reason Umbraco can't boot the site with this config locally? //cc @Shazwazza

**Comment by nul800sebastiaan** [comment]
I think it's mostly that you're doing something that is unsupported 😅  

Just to summarize the scenario:

- You're generating an empty LocalDb file named `Umbraco` and putting it in App_Data
- The web.config contains no umbraco version and blank values for all the connection string attributes
- `Umbraco.Core.MainDom.Lock` is set to `SqlMainDomLock`

First of all: I didn't know you could even do this, I love this trick to use LocalDb, thanks! 

Second of all.. this does works for me, so I am missing a step 😅 What am I missing??

Ps. We should have the option in the installer to automatically generate the localdb file, I am sure we can do it.

**Comment by nul800sebastiaan** [comment]
I'd also love to see the logs for when it fails to boot, that's the best way to narrow this one down.

**Comment by bjarnef** [comment]
@nul800sebastiaan yes exactly. Not sure if the value in `Umbraco.Core.MainDom.Lock` key matter - if I just remove the key the installer works.

Yeah, if it probably also possible to create the LocalDb in App_Data using command line or a PowerShell script, but I didn't find a way to do this, so just created the database from SSMS, closed the connection and moved the db file to App_Data 😁 

It would be great if pasting a custom connection string `Data Source=(LocalDB)\MSSQLLocalDB;AttachDbFilename=|DataDirectory|\Umbraco.mdf;Integrated Security=True` it would create the LocalDb or SQL Ce in case LocalDb isn't installed (I think Umbraco Deploy handle something similar when cloning down a project and run the site). Currently it just fails with "Could not connect to database", when the database file doesn't exist.

**Comment by nul800sebastiaan** [comment]
Should just be in the dropdown after SQL CE, if we detect that LocalDb exists then you can also choose it from the dropdown and we fill in the connection string for you. Indeed, I know deploy does it but I am not sure what dark magic goes in it.

That said, I have tested that scenario above and it works for me! 😅 

I'll ask around to see if we want to make easy installs to LocalDb into a feature.

**Comment by bjarnef** [comment]
Yeah, I just tested again with `Umbraco.Core.MainDom.Lock` key on a clean Umbraco v8.14.1 and v8.15.1 and the installer was running.

This project is running on Umbraco v8.14.1 as well. Just tried the same steps again on this project and the installer is running with and wihtout `Umbraco.Core.MainDom.Lock` key in web.config.

In this specific project I am also using uSync and Hangfire, so not sure if it was related to these packages doing something on startup as well.

**Comment by dinc5150** [comment]
I'm getting the same error @bjarnef on v18.15.5. My setup is a little different though. Usually, I'd assume that it's a different issue, however what caught my eye was that I'm using uSync and Hangfire too. I've recently upgraded from V7 and added Hangfire for scheduled tasks. 

The issue happens roughly every 2 days on the live server and is running on an Azure VM under IIS (not an app service).

I don't have the app setting `Umbraco.Core.MainDom.Lock` in my web.config. 

I'm getting the "Boot Failed' screen and the exact same error as you:
```
System.TimeoutException: Cannot acquire MainDom
at Umbraco.Core.Runtime.MainDom.Acquire() in D:\\a\\1\\s\\src\\Umbraco.Core\\Runtime\\MainDom.cs:line 172
```

Looking at the logs, it looks like the site cleanly shuts down to reboot and fails to boot. Not sure what causing the shutdown. 

I thought I'd share just in case it's something in common that we have. 

Another error that is appearing around the same time in the Event Viewer (Not the Serilogs) is:
```
Exception has been thrown by the target of an invocation. (\wwwroot\web.config line 139)
```
On Line 139 of the web.config
```
  <roleManager enabled="true" defaultProvider="UmbracoRoleProvider">
      <providers>
        <clear />
139:        <add name="UmbracoRoleProvider" type="Umbraco.Web.Security.Providers.MembersRoleProvider" />
      </providers>
    </roleManager>

```
And seems to happen a lot just before it goes offline and then constantly whilst its offline until I restart the service. Not sure if this is related.

My suspects so far:
 - Hangfire
 - Custom Owin Startup to setup Hangfire
 
I'm going to have a look at disabling Hangfire and running the scheduled tasks differently to see if it's the cause, but I'm not sure.

Hopefully something in the above helps you pinpoint the issue @bjarnef

**Comment by dinc5150** [comment]
Just a quick follow up on this. After removing Hangfire for over a month the issue did not occur. I re-introduced Hangfire with a task that runs 3 x a week and the issue has come back. It doesn't seem to be affected by the running task as the site will go down on days that the task is not scheduled to run.

So definitely looks like something to do with Hangfire, but not sure exactly what's causing the instance in my case.

**Comment by SouthCentralCode** [comment]
Had the exact same issue, and stopped it by removing my custom own hangfire startup.  The problem for me is intermittent, the app pool restarts on a schedule every 24 hours.  And is usually ok but every once in a while i get the boot failed issue.  Sometimes touching the web config fixes it, sometimes it doesn't.

**Comment by nios87** [comment]
> Just a quick follow up on this. After removing Hangfire for over a month the issue did not occur. I re-introduced Hangfire with a task that runs 3 x a week and the issue has come back. It doesn't seem to be affected by the running task as the site will go down on days that the task is not scheduled to run.
> 
> So definitely looks like something to do with Hangfire, but not sure exactly what's causing the instance in my case.

Did you ever find out the cause? We have the same problem with the same setup..

**Comment by dinc5150** [comment]
Unfortunately we are still experiancing the issue. sometimes will go a week or two without issue, and then sometimes it does it daily.  It seems to happen when IIS does a recycle of the app pool, so what we do is schedule it to recycle at a low traffic time of day and then monitoring will kill the w3wp process if the boot fails. Not ideal, but it's been the only solution so far.
