### ISSUE TITLE
Umbraco.MediaPicker3 not showing validation messages when mandatory

### ISSUE THREAD

**Issue by chrden** [umbraco/Umbraco-CMS#10851]
### Which *exact* Umbraco version are you using? For example: 8.13.1 - don't just write v8

8.15.1

### Bug summary

Umbraco.MediaPicker3 does not fire validation on Save/Save & Publish when set to 'Field is mandatory'

### Specifics

You can see from these screenshots that I have clicked 'Save and publish', the event has fired and saved the changes to the node in draft (the green button is showing the 'x') but there is no validation message to show that the 'Listing image small' field is mandatory

![image](https://user-images.githubusercontent.com/22013176/129350219-b6cde9e9-a0cc-44df-89f7-0b78d9a66606.png)

In this screenshot I have just tried to 'Save' the node which does not fire but no validation is showing

![image](https://user-images.githubusercontent.com/22013176/129350983-a2237975-83c0-4005-897e-d59beaeaa5fb.png)

### Steps to reproduce

Add Umbraco.MediaPicker3 as the data type of a property to a document type and set as 'Field is mandatory' in Validation settings 
Create/Save/Save and Publish changes to this node in but leave the above Umbraco.MediaPicker3 field without a value

### Expected result / actual result

Expected: Validation would display for Umbraco.MediaPicker3 property on Save and Save and Publish
Actual: No validation is shown for either Save or Save and Publish

**Comment by nul800sebastiaan** [comment]
Hey there @chrden - something seems to  be wrong on your end there, I just tested this in 8.15.1 and it works as expected for me! 

![image](https://user-images.githubusercontent.com/304656/129374645-e3190197-6cdb-4f5f-a681-abc0ac124f28.png)


Maybe there's something more I need to set up than just a MediaPicker3? 

If you've upgraded from a previous version of Umbraco then it could be that you didn't get all the new files, you could have a look and check with the tips in this blog post, it's a bit old but most of it is still pretty accurate: https://cultiv.nl/blog/how-to-diagnose-umbraco-upgrade-problems/

I'll close this for now, but if you  have more steps to reproduce we can have another look.

**Comment by ProNotion** [comment]
I am having this issue at the moment in v13.10.0 and I have a suspicion that the reason is if your media picker is configured with `min:0` (or `min:`) and `max:1` and the property is marked as mandatory the validation will not show. If you change it to `min:1` and `max:1` then you at least get validation showing albeit not the mandatory message you might want or expect to see.

Update: In my case there was a custom interceptor that was causing the issue.
