### ISSUE TITLE
Umbraco 8.16-rc install fails missing ImageProcessor.Web

### ISSUE THREAD

**Issue by KevinJump** [umbraco/Umbraco-CMS#10854]
### Which *exact* Umbraco version are you using? For example: 8.13.1 - don't just write v8

8.16.0-rc

### Bug summary

Installation via nuget fails. 

```
Attempting to resolve dependencies for package 'UmbracoCms.8.16.0-rc' with DependencyBehavior 'Lowest'
install-package : Unable to find a version of 'ImageProcessor.Web' that is compatible with 'UmbracoCms 8.16.0-rc constraint: ImageProcessor.Web (>= 4.12.1.100 && < 4.999999.0)'.
At line:1 char:1
+ install-package UmbracoCms -pre
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand
```

Looks like the nuget package is dependent on a package that isn't publicly available on nuget. ?

### Specifics

Nuget Package is depdendent on 

  ImageProcessor.Web (>= 4.12.1.100 && < 4.999999.0)'.
 ImageProcessor.Web.Config (>= 2.6.0.100 && < 2.999999.0)

If you fake these packages locally the site does install. 

### Steps to reproduce

```
install-package UmbracoCms -version 8.16.0-rc
```

**Comment by abjerner** [comment]
I had a look at the issue/commit history, and it seems to be a silly human error, as the other .nuspec files were updated correctly. There is also already an issue for it: https://github.com/umbraco/Umbraco-CMS/issues/10837

And Seb fixed it here: https://github.com/umbraco/Umbraco-CMS/commit/33feb808dd934cd4b1160ea9bd66b7783507d05f

**Comment by nul800sebastiaan** [comment]
Thanks Anders, yep, I'll close as a duplicate, sorry for the inconvenience!  https://github.com/umbraco/Umbraco-CMS/issues/10837
