### ISSUE TITLE
Umbraco style changes (image cropper, form answer types)

### ISSUE THREAD

**Issue by NikitaRVT** [umbraco/Umbraco-CMS#10876]
8.15.1

### Bug summary

With Umbraco update changed style for image cropper options and "Choose answer type" pop-up menu items (form creation). 

### Steps to reproduce

1. Image cropper options

- Open any image settings and check the position of the image cropping options. (Arranged in one column)
![image](https://user-images.githubusercontent.com/56531878/129715381-bdf45dfe-01f9-4a40-b222-552727cf2e85.png)

2. "Choose answer type" pop-up menu items (from creation).

- Create new form (or open existing), 
- Press "Add question" -> "Choose answer type"
- Pictograms and text size became smaller
![image](https://user-images.githubusercontent.com/56531878/129719636-0176d6de-8b37-49a7-b93f-b16f1800d172.png)

Remark: No any additional code used, only UmbracoCms source code.

### Expected result / actual result

1. Image cropper options
![image](https://user-images.githubusercontent.com/56531878/129719919-bc5d8123-b121-4a96-b565-041de91f710a.png)

2. "Choose answer type" pop-up menu items (from creation).
![image](https://user-images.githubusercontent.com/56531878/129720113-c4979c9e-b787-427e-9d97-db2215176a7d.png)

---
_This item has been added to our backlog [AB#13387](https://dev.azure.com/umbraco/243e7927-03b2-44e2-908f-d4ac7ea5daaa/_workitems/edit/13387)_

**Comment by bjarnef** [comment]
The second part you mention is regarding Umbraco Forms and have been fixed in https://github.com/umbraco/Umbraco.Forms.Issues/issues/610

**Comment by NikitaRVT** [comment]
> The second part you mention is regarding Umbraco Forms and have been fixed in [umbraco/Umbraco.Forms.Issues#610](https://github.com/umbraco/Umbraco.Forms.Issues/issues/610)

Thanks! What about first part?

**Comment by nul800sebastiaan** [comment]
Yep, that used to look a lot better in the image cropper: 

![image](https://user-images.githubusercontent.com/304656/129744007-5c31c335-8d58-4b17-903f-a612f86ffbe4.png)


We'll have to have a look at this! This broke in 8.14 when we introduced the new media picker, I assume there's some shared CSS between the Image Cropper datatype and the new MediaPicker.

**Comment by nul800sebastiaan** [comment]
It's this change that made a single item list: https://github.com/umbraco/Umbraco-CMS/blame/d615c1e88b57d151c0e71bdcc6f152fbceb7d644/src/Umbraco.Web.UI.Client/src/less/property-editors.less#L603

**Comment by bjarnef** [comment]
Without having looked closer at the markup and css, I think the crop list can use `display: flex; flex-flow: row wrap;` ... alternatively CSS grid. https://caniuse.com/?search=grid which is being well supported, but there is better support for flexbox, which probably is sufficient in this case.

**Comment by nul800sebastiaan** [comment]
Fixed for 8.15.3 and 8.16.0 in https://github.com/umbraco/Umbraco-CMS/commit/c72cb1683b9626c4a38a68c08a4c959ca85b1778
