### ISSUE TITLE
File Upload extensions isn't validated

### ISSUE THREAD

**Issue by bjarnef** [umbraco/Umbraco-CMS#10897]
### Which *exact* Umbraco version are you using? For example: 8.13.1 - don't just write v8

8.14.1

### Bug summary

With the new file upload extensions I want to limit a specific property to accept csv-files only and not e.g. xslx-files.
However when selecting an xslx-file no validation errors are shown and the xslx-file is uploaded.

### Steps to reproduce

- Create an instance of file upload and add csv to accepted extensions.

![image](https://user-images.githubusercontent.com/2919859/130020379-3ab6f63a-f56b-41f4-80ed-78b119d726e5.png)

- Add a property to a document type using this datatype.

![image](https://user-images.githubusercontent.com/2919859/130020531-ace1bf0f-fcce-4b4c-bf42-80c33f5f9027.png)

- In content upload a xslx-file and click save or save & publish. Notice no validation errors are shown on upload (via click or drag & drop) or during save.

![image](https://user-images.githubusercontent.com/2919859/130020684-e863c15e-b696-445d-b2bf-8a1d7d56900c.png)

### Expected result / actual result

When uploading file when an non accepted format it should show a validation error and don't upload the file.

The csv extension is added to the `accept` attribute here though.

![image](https://user-images.githubusercontent.com/2919859/130022941-a4e830e1-5dca-4b98-bd52-eff2fa1d67a4.png)

---
_This item has been added to our backlog [AB#13506](https://dev.azure.com/umbraco/243e7927-03b2-44e2-908f-d4ac7ea5daaa/_workitems/edit/13506)_

**Comment by bjarnef** [comment]
In fact the xslx-file shouldn't even be available to select in windows explorer, when clicking the file upload.
https://stackoverflow.com/a/23706177/1693918 (in the first example only Excel files are selectable in file explorer).

**Comment by nul800sebastiaan** [comment]
Ah yeah, this is definitely not working correctly. We'll have to have a look at this, not just a frontend issue, also something we need to validate on the server.

**Comment by nul800sebastiaan** [comment]
Fixed in https://github.com/umbraco/Umbraco-CMS/pull/10987
