### ISSUE TITLE
Umbraco 9.0.0 RC002 - Can't copy content at root

### ISSUE THREAD

**Issue by KevinJump** [umbraco/Umbraco-CMS#10903]
### Which *exact* Umbraco version are you using? For example: 8.13.1 - don't just write v8

9.0.0 rc002

### Bug summary

Attempting to copy a content item/tree at the root level fails. 

if you right click on the root node of your site and select copy, and then attempt to copy the content to the root. the screen disappears and nothing gets copies. 

_copying content beneath the root level works._ 

### Steps to reproduce

1. Create a content item in the root of the site.
2. right click - copy
3. select 'Content' as the destination

screen closes no copy happens. 

![rc002-copyfail](https://user-images.githubusercontent.com/431231/130058746-2bbb65bf-9f41-44c1-815b-31127d4a7877.gif)

### Expected result / actual result

Content should be copied to root level next to existing content.

**Comment by bergmania** [comment]
Thanks for reporting @KevinJump. I can confirm I can repro on both `v9/dev` and `v8/dev`.. Seems to be introduced by this PR: https://github.com/umbraco/Umbraco-CMS/pull/10762

**Comment by nul800sebastiaan** [comment]
Turns out this is an issue that originates from 8.16-RC https://github.com/umbraco/Umbraco-CMS/pull/10762

@bjarnef Would you have a chance to check this out please? I can just revert the PR for final release of 8.16 but it would be nicer to fix properly! 😁

**Comment by bjarnef** [comment]
@nul800sebastiaan yeah, I know what is going on. I'll have a look - not only an issue regarding copy, but also move action.

**Comment by bjarnef** [comment]
PR: https://github.com/umbraco/Umbraco-CMS/pull/10907
