### ISSUE TITLE
Umbraco 9.0.0 RC002 - Content creation issue

### ISSUE THREAD

**Issue by BatJan** [umbraco/Umbraco-CMS#10902]
### Which *exact* Umbraco version are you using? For example: 8.13.1 - don't just write v8

9.0.0-rc002

### Bug summary

I'm experiencing an issue with creating content nodes in the latest Umbraco 9 RC. Whenever I create a node and hit "Save and Publish" it acts a bit strange and sometimes I temporarily see an error message before the backoffice reloads and then the content node is created twice.

However if I create a content node and just save it without publishing then it works fine and I can create subnodes etc. - But I can also only save them - If I try to publish any of the node it's the same odd behavior.

I was wondering whether it has something to do with the document types not having any templates assigned but that did not seem to make any difference when I tried.

I have recoded a video where you can see what's happening.

### Steps to reproduce

See the steps here https://user-images.githubusercontent.com/1932158/130056070-d22c0557-3d4e-4739-9e6c-70cefe1f972d.mp4 - There is a long period of time where it seems like nothing happens. But just waaait for it :-)

### Expected result / actual result

I would expect to be able to save and publish a node without any issues at approximately the same speed as the save action :)

**Comment by bergmania** [comment]
Thanks for reporting @BatJan.. Looks like a nasty bug, but I can't reproduce it directly on `v9/dev`  or from my test project running `9.0.0-rc2`.

Are you able to post the error you see sometimes, or do the log contain any errors?

**Comment by nul800sebastiaan** [comment]
@BatJan I know you just upgraded from RC1, so maybe it's related to that, refresh browser cache maybe?

**Comment by BatJan** [comment]
Hmm, it appears to have been a cache issue as @nul800sebastiaan suggested. I was upgrading from 9.0.0-rc001 to 9.0.0-rc002 via nuget in VS2019 and the issue had already been there on the 9.0.0-rc001 release. But when I tried building and running the solution using the CLI the issue disappeared... So guess it's fixed the cache somehow just puzzled that building using VS2019 did not achieve the same thing. Also tried a clean install, which worked like a charm so I'll close this issue for now and reopen should I encounter it again or be able to provide more detail at a later point.
