### ISSUE TITLE
LocalizedTextServiceExtensions not using culture parameter

### ISSUE THREAD

**Issue by soreng** [umbraco/Umbraco-CMS#10906]
### Which *exact* Umbraco version are you using? For example: 8.13.1 - don't just write v8

v9-rc002

### Bug summary

https://github.com/umbraco/Umbraco-CMS/blob/fbbfcd84c78c24f2ba11ac9c212d8868599fbe4f/src/Umbraco.Core/Services/LocalizedTextServiceExtensions.cs#L46-L47

The culture parameter is not used, and the service is missing overloads that don't have the parameter.

### Steps to reproduce

Pass another culture as parameter

**Comment by bjarnef** [comment]
@soreng I think this is what you already fixed in https://github.com/umbraco/Umbraco-CMS/pull/10720

**Comment by soreng** [comment]
@bjarnef something like that - but there was an overload I had used, that was removed - I was working on a PR with that in it 

Will see if I can get it fixed in a bit
