### ISSUE TITLE
v9 Block List Thumbnail Selector Empty on *nix

### ISSUE THREAD

**Issue by cleversolutions** [umbraco/Umbraco-CMS#10912]
### Version

v9/dev

### Bug summary

The catalog appearance thumbnail selector is empty when hosted on MacOS. It should render a tree view allowing selection of static files from App_Plugins and wwwroot.

### Specifics

On Windows you get a tree picker with App_Plugins and wwwroot folders; however, on MacOS, the tree picker is empty.
<img width="498" alt="image" src="https://user-images.githubusercontent.com/23444011/130238158-befc73d6-b244-450c-925e-e26802d057a5.png">

I believe this is a regression from #10794 

Specifically, `_fileSystem.GetDirectories` is returning full paths, but we are comparing only local paths so `AppPlugins` and `WebRoot` fail to be recognized, they pass the test on line 42 and the loop continues. The screenshot below shows `directory` and `AppPlugins` constant failing to compare.
<img width="986" alt="image" src="https://user-images.githubusercontent.com/23444011/130243751-6070d62e-2eda-4f18-bf9b-026cba56ce57.png">

Even more specifically, I think there is a bug in `Umbraco.Cms.Core.IO.PhysicalFileSystem.GetRelativePath(string fullPathOrUrl)`. When I call it on directory it returns an absolute path. 
```
_fileSystem.GetRelativePath(directory)
"Users/evanm/src/Umbraco-CMS/src/Umbraco.Web.UI/App_Plugins"
```

I believe`GetRelativePath` is assuming a file system url starts with c:\ (or equivalent) rather than '/' ie '/var/wwwroot/'
```
public string GetRelativePath(string fullPathOrUrl)
        {
            // test URL
            var path = fullPathOrUrl.Replace('\\', '/'); // ensure URL separator char

            // if it starts with the root URL, strip it and trim the starting slash to make it relative
            // eg "/Media/1234/img.jpg" => "1234/img.jpg"
            
            // **** I think this is wrong. File paths on Unix systems start with '/' I think this assumes file paths start with C:\
            // and so will pass onto the next test.
            if (_ioHelper.PathStartsWith(path, _rootUrl, '/'))
                return path.Substring(_rootUrl.Length).TrimStart(Constants.CharArrays.ForwardSlash);

            // if it starts with the root path, strip it and trim the starting slash to make it relative
            // eg "c:/websites/test/root/Media/1234/img.jpg" => "1234/img.jpg"
            if (_ioHelper.PathStartsWith(path, _rootPathFwd, '/'))
                return path.Substring(_rootPathFwd.Length).TrimStart(Constants.CharArrays.ForwardSlash);

            // unchanged - what else?
            return path;
        }
```

I think something as simple as reversing these two tests would fix it such as:
```
        public string GetRelativePath(string fullPathOrUrl)
        {
            // test URL
            var path = fullPathOrUrl.Replace('\\', '/'); // ensure URL separator char

            // if it starts with the root path, strip it and trim the starting slash to make it relative
            // eg "c:/websites/test/root/Media/1234/img.jpg" => "1234/img.jpg"
            // or on unix systems "/var/wwwroot/test/Meia/1234/img.jpg"
            if (_ioHelper.PathStartsWith(path, _rootPathFwd, '/'))
                return path.Substring(_rootPathFwd.Length).TrimStart(Constants.CharArrays.ForwardSlash);

            // if it starts with the root URL, strip it and trim the starting slash to make it relative
            // eg "/Media/1234/img.jpg" => "1234/img.jpg"
            if (_ioHelper.PathStartsWith(path, _rootUrl, '/'))
                return path.Substring(_rootUrl.Length).TrimStart(Constants.CharArrays.ForwardSlash);

            // unchanged - what else?
            return path;
        }
```

### Steps to reproduce

On MacOS (again this works great on Windows)
1. Create a clean v9/dev site
2. Create a BlockList data type
3. Add a Block to it
4. Click Add Thumbnail under Catalogue Appearance

### Expected result / actual result

The StaicFilesTreeController allows App_Plugins and Webroot to be navigable on MacOS.

**Comment by cleversolutions** [comment]
I can submit a PR. The change to PhysicalFileSystem I proposed works, but I'm not sure if it has any regressions.
<img width="883" alt="image" src="https://user-images.githubusercontent.com/23444011/130250636-0c73abb1-9828-40d2-a33d-7d05d1560f12.png">

**Comment by nul800sebastiaan** [comment]
@cleversolutions A PR is always much appreciated of course! 👍  We will have a look during review if it causes any other problems.

**Comment by cleversolutions** [comment]
Sounds great! Merge requested 😄
