### ISSUE TITLE
Block List doesnt save values 

### ISSUE THREAD

**Issue by Amalie-Wowern** [umbraco/Umbraco-CMS#10910]
### Which *exact* Umbraco version are you using? For example: 8.13.1 - don't just write v8

8.15.2

### Bug summary

I can not save values in a new property added to the document type after a created the the documenttype when im using block editor

### Steps to reproduce

- Create element type 
- add properties
- Save
- Create Bock List with inline editing
- Add elemt type
- Save
- Block list til document type
- Save
- Go to content page with document type 
- Fill out properties
- Save and publish
- Go to element type
- Add a new property - i have only tested with textstring
- Save
- Go to content page 
- Fill out the new property
- Publish

### Expected result / actual result

Expected result
The new values are saved and published

Actual result
The new values are deleted

---
_This item has been added to our backlog [AB#13498](https://dev.azure.com/umbraco/243e7927-03b2-44e2-908f-d4ac7ea5daaa/_workitems/edit/13498)_

**Comment by nul800sebastiaan** [comment]
Yikes! Thanks @Amalie-Wowern - I can reproduce the problem.


https://user-images.githubusercontent.com/304656/130233723-51b93c91-e36d-4114-8d62-7e2d0bbbf37d.mp4

**Comment by nul800sebastiaan** [comment]
By the way, it DOES save the second time you edit this, just the first time it doesn't seem to know what you're trying to do.

**Comment by nul800sebastiaan** [comment]
As an update, this is only true when you restart the site. I have had a look at the `BlockEditorPropertyEditor` and the new property seems to disappear in `ResolveBlockItemData`. There must be something with a cache not being updated when saving the document type.

I've tracked it down to 8.15, the same problem does not occur in 8.14. I'll have to ask the team have a look at it.

**Comment by Amalie-Wowern** [comment]
Thank you for the quick support and the good findings.
It will be much easier to work with this version with that knowledge and i am looking forward for a fix in a later version

**Comment by nul800sebastiaan** [comment]
This is fixed in https://github.com/umbraco/Umbraco-CMS/pull/10938 and will be available in 8.16.0 Thursday/8.15.3 patch next week. Sorry for the inconvenience!
