### ISSUE TITLE
Umbraco V9 rc002: Keys are shown instead of values

### ISSUE THREAD

**Issue by jkulker** [umbraco/Umbraco-CMS#10927]
### Which *exact* Umbraco version are you using? For example: 8.13.1 - don't just write v8

Umbrac 9 RC0002

### Bug summary

After updating to rc002 the dictonary values are not shown anymore in the fields when creating content. Instead the key values are shown.

![image](https://user-images.githubusercontent.com/38132206/130441625-8645388a-0fb5-4514-a0d2-b8b4d79c4fd7.png)

### Specifics

Editing content

### Steps to reproduce

Updating from release candidate 1 to 2

### Expected result / actual result

When using #title in  in field translate it to a specific value in the dictonary per language

---
_This item has been added to our backlog [AB#13539](https://dev.azure.com/umbraco/243e7927-03b2-44e2-908f-d4ac7ea5daaa/_workitems/edit/13539)_

**Comment by jkulker** [comment]
Looks like translation are completly broken

**Comment by meyntony** [comment]
**Steps to reproduce**
I have made a repo, that contains the SQL CE database so just switching between the commits can help you see the error:

**Comment by nul800sebastiaan** [comment]
This might be the same problem as https://github.com/umbraco/Umbraco-CMS/issues/10977 - would be good to check while fixing this as well.

**Comment by bergmania** [comment]
I can verify this issue exists, and seems to have been introduced by this PR: https://github.com/umbraco/Umbraco-CMS/pull/10628

Will need to find a solution that works on both cases..

**Comment by elit0451** [comment]
Fixed in #10986
