### ISSUE TITLE
Creating a new page result in 404 error

### ISSUE THREAD

**Issue by bjarnef** [umbraco/Umbraco-CMS#10932]
### Which *exact* Umbraco version are you using? For example: 8.13.1 - don't just write v8

8.15.1

### Bug summary

On a clean Umbraco Cloud project based on v8.15.1 I am getting an 404 error when using the "create" action to create a content node.

### Steps to reproduce

Create a new page at root level, e.g. a Home Page.
An error notification is shown.

![image](https://user-images.githubusercontent.com/2919859/130574639-605dab4e-ee5f-4bfa-b4f7-d6eedd017369.png)

**Comment by nul800sebastiaan** [comment]
Hmmm, works for me! Make sure to reach out to Cloud support, something seems to be wrong with your specific project on Cloud. :)

**Comment by bjarnef** [comment]
Yeah, I couldn't reproduce on a non-cloud project. Something seems to request "/umbraco/backoffice/UmbracoApi/Content/GetById?id=-1 and also noticed several console errors in Deploy dashboard. So probably something in Deploy or caused by the new infrastructure on Umbraco Cloud.

**Comment by nul800sebastiaan** [comment]
Yes, I should have specified: I created a new cloud project, new doctype, allowed at root, and it worked for me!

**Comment by bjarnef** [comment]
@nul800sebastiaan yeah, I also can't reproduce on live environment, only local environment, so really strange 😅

**Comment by bjarnef** [comment]
I think it may happens here in Deploy `contentResource.getById`

![image](https://user-images.githubusercontent.com/2919859/130587228-1a0c6e03-3f1d-4227-bf0d-2b1f011de663.png)

**Comment by bjarnef** [comment]
Bingo.

Something must have changed recently here in Umbraco Deploy.

![image](https://user-images.githubusercontent.com/2919859/130587930-3358e31e-e6c6-42fc-9ee1-fdf45f06a5df.png)

![image](https://user-images.githubusercontent.com/2919859/130587880-f6a5bd88-72d8-47f2-9112-8e09424ad672.png)

**Comment by bjarnef** [comment]
@nul800sebastiaan can you transfer this issue to Umbraco Deploy issue tracker?

**Comment by bjarnef** [comment]
In various places in Umbraco Core it check for `id > -1`.

https://github.com/umbraco/Umbraco-CMS/blob/v8/contrib/src/Umbraco.Web.UI.Client/src/views/media/media.create.controller.js#L17

https://github.com/umbraco/Umbraco-CMS/blob/v8/contrib/src/Umbraco.Web.UI.Client/src/views/content/content.create.controller.js#L34-L38
