### ISSUE TITLE
dropdownFlexible should be in lower case

### ISSUE THREAD

**Issue by SigmundurMorkore** [umbraco/Umbraco-CMS#10937]
### Which *exact* Umbraco version are you using? For example: 8.13.1 - don't just write v8

9.0.0-rc002

### Bug summary

When running in production and creating a dropdown field, Umbraco will throw an error saying it cannot find dropdownFlexible.html:

```
Request error: The URL returned a 404 (not found):
views/propertyeditors/dropdownFlexible/dropdownFlexible.html
```

This is because the correct URL should be: `views/propertyeditors/dropdownflexible/dropdownflexible.html`

Issue is presumably caused by this line: https://github.com/umbraco/Umbraco-CMS/blob/d428a4543f33bb7094cf7db5f6b6fdc2d1de3063/src/Umbraco.Web/PropertyEditors/DropDownFlexiblePropertyEditor.cs#L11 and it hasn't been an issue until now because Windows is case insensitive while Linux is case sensitive.

### Steps to reproduce

1. Start Umbraco in production
2. Create a DocumentType
3. Add a dropdown

---
_This item has been added to our backlog [AB#13850](https://dev.azure.com/umbraco/243e7927-03b2-44e2-908f-d4ac7ea5daaa/_workitems/edit/13850)_

**Comment by nul800sebastiaan** [comment]
Yeah we don't officially support Linux yet, a few kinks to straighten out first. We'd love a PR to fix this though! I don't remember what our method is, if we rename the file in the proper casing or the string that builds the path. I'll have to ask around. Would you be up for sending a pull request to fix it once I have the answer? 🙂

**Comment by SigmundurMorkore** [comment]
Yeah, I know Linux support isn't 100% official yet, but have started moving over to Linux in anticipation of official Linux support :)

If it's not too difficult I'd love to try to make a PR!

**Comment by nul800sebastiaan** [comment]
You're correct, we realized that we do a ToLower when copying the files in the gulp task, so all files will be lower cased already. so yes, it would be great to fix the few areas of code that still refer to the wrong filenames! 👍
