### ISSUE TITLE
Multi Url Picker is not updating model

### ISSUE THREAD

**Issue by TheBekker** [umbraco/Umbraco-CMS#10955]
### Which *exact* Umbraco version are you using? For example: 8.13.1 - don't just write v8

8.15.1

### Bug summary

While creating a custom property editor that uses the "Multi Url Picker", i noticed that it's not updating it's model on the fly.
It only updates when saving/publishing the whole page.

### Specifics

``MultiUrlPickerController`` listens for "**formSubmitting**" event to update ``$scope.model.value`` but othervise never updating the model value.

### Steps to reproduce

Best way to show:

1. Make properties render out their model.
2. Change value of an Multi Url Picker

https://user-images.githubusercontent.com/3404996/130952760-c972912f-4bad-4b1d-b07f-7ae3fc7827a7.mp4

### Expected result / actual result

``model.value`` should update, when property is changed.

**Comment by nul800sebastiaan** [comment]
Fixed in https://github.com/umbraco/Umbraco-CMS/pull/10957
