### ISSUE TITLE
GetLocalCropUrl Obsolete message is misleading

### ISSUE THREAD

**Issue by SofusMunch** [umbraco/Umbraco-CMS#10956]
### Which *exact* Umbraco version are you using? For example: 8.13.1 - don't just write v8

9-RC2

### Bug summary

GetLocalCropUrl is obsolete in RC-2, replaced by, I assume, GetCropUrl. The obsolete message however says:

"Use **GetCrop** to merge local and media crops, get automatic cache buster value and have more parameters."

Which is a bit confusing.

### Steps to reproduce

Use GetLocalCropUrl.

**Comment by nul800sebastiaan** [comment]
Thanks, you're right! Fixed in https://github.com/umbraco/Umbraco-CMS/commit/e62dd04295cfc794d5f898b0272c6dc378367348
