### ISSUE TITLE
Open In Media Library link on media view blade causes an exception on load

### ISSUE THREAD

**Issue by jaddie** [umbraco/Umbraco-CMS#10950]
### Which *exact* Umbraco version are you using? For example: 8.13.1 - don't just write v8

V9-RC002

### Bug summary

Content Structure:
Home[Homepage Blocks][Thumbnail Image Block][Image]-> Click image to open blade, Image doesn't load properly for certain files, but also if at this point click Open In Media Library link, attached error appears
![image](https://user-images.githubusercontent.com/68933/130800561-d0325d34-e5b5-4b03-af95-8a90a01af000.png)

Although the image does appear as even regardless of the error which seems to be trying to find ancestors, but is expecting id to be an int when a guid is being provided instead. This does not appear to be a regression from RC1->RC2 & existed before RC1 as I tried the older code to no avail.
Example link:
https://localhost:44362/umbraco/backoffice/umbracoapi/entity/GetAncestors?id=5ae6fb5e-902e-4b9f-adb2-8c293a1f24fa&type=media&culture=

### Steps to reproduce

Create Doc Type
Add Property -> Image Media Picker
Create Content
Select image
Save & publish
Click title of the image displayed on the thumbnail
Click Open In Media Library on the blade displayed

### Expected result / actual result

Media is loaded without errors popping up

---
_This item has been added to our backlog [AB#13527](https://dev.azure.com/umbraco/243e7927-03b2-44e2-908f-d4ac7ea5daaa/_workitems/edit/13527)_

**Comment by bjarnef** [comment]
@jaddie @nul800sebastiaan I got it working in PR https://github.com/umbraco/Umbraco-CMS/pull/10975 so now `entityResource.getAncestors()` works with `int`, `Guid` and `Udi` 👍

**Comment by nul800sebastiaan** [comment]
We found that this error was actually fixed in v8 after we merged it up to v9 rc002. I've verified that this is no longer an issue on the latest v9 source code. We expect to release a rc003 soon-ish (probably next week) to have some more bug fixes in there. Thanks for reporting @jaddie!

And thanks for the PR @bjarnef - we'll have to have a look at that as well :)
