### ISSUE TITLE
When starting Umbraco loads media and content from the database multiple times

### ISSUE THREAD

**Issue by deMD** [umbraco/Umbraco-CMS#10969]
### Which *exact* Umbraco version are you using? For example: 8.13.1 - don't just write v8

9.0.0-rc002

### Bug summary

When the website is starting I noticed in the logs that the media and content seems to get loaded from the database multiple times. It also loads from the localcache dbs. This only seems to happen after a release to Azure.

### Specifics

SEQ excerpt:
```

27 Aug 2021 11:48:11.896
Completed. (182ms) [Timing 778080c]
27 Aug 2021 11:48:11.713
Loading media from database [Timing 778080c]
27 Aug 2021 11:48:11.712
Completed. (108ms) [Timing d112e21]
27 Aug 2021 11:48:11.603
Loading content from database [Timing d112e21]
27 Aug 2021 11:48:11.506
Completed. (132ms) [Timing 6a414fd]
27 Aug 2021 11:48:11.373
Loading media from database [Timing 6a414fd]
27 Aug 2021 11:48:11.372
Completed. (144ms) [Timing f2bbc80]
27 Aug 2021 11:48:11.228
Loading content from database [Timing f2bbc80]
27 Aug 2021 11:48:11.166
Completed. (157ms) [Timing ef3d254]
27 Aug 2021 11:48:11.008
Loading media from database [Timing ef3d254]
27 Aug 2021 11:48:11.003
Completed. (137ms) [Timing 7aef011]
27 Aug 2021 11:48:10.865
Loading content from database [Timing 7aef011]
27 Aug 2021 11:48:10.756
Completed. (137ms) [Timing a6a95e5]
27 Aug 2021 11:48:10.619
Loading media from database [Timing a6a95e5]
27 Aug 2021 11:48:10.612
Completed. (91ms) [Timing 7bd8b5e]
27 Aug 2021 11:48:10.521
Loading content from database [Timing 7bd8b5e]
27 Aug 2021 11:48:10.149
Adding examine event handlers for 3 index providers.
27 Aug 2021 11:48:10.121
Completed. (233ms) [Timing f060098]
27 Aug 2021 11:48:09.888
Loading media from database [Timing f060098]
27 Aug 2021 11:48:09.839
Completed. (1408ms) [Timing 5a9e0ee]
27 Aug 2021 11:48:08.437
Loading content from database [Timing 5a9e0ee]
27 Aug 2021 11:48:00.408
Completed. (219ms) [Timing f982411]
27 Aug 2021 11:48:00.189
Loading media from database [Timing f982411]
27 Aug 2021 11:48:00.174
Completed. (274ms) [Timing 7868c75]
27 Aug 2021 11:47:59.899
Loading content from database [Timing 7868c75]
27 Aug 2021 11:47:53.901
Completed. (119ms) [Timing 430c693]
27 Aug 2021 11:47:53.782
Loading media from database [Timing 430c693]
27 Aug 2021 11:47:53.772
Completed. (197ms) [Timing 01c195a]
27 Aug 2021 11:47:53.575
Loading content from database [Timing 01c195a]
27 Aug 2021 11:47:47.062
Completed. (125ms) [Timing 7aff028]
27 Aug 2021 11:47:46.936
Loading media from database [Timing 7aff028]
27 Aug 2021 11:47:46.900
Completed. (117ms) [Timing aa22542]
27 Aug 2021 11:47:46.782
Loading content from database [Timing aa22542]
27 Aug 2021 11:47:41.724
Completed. (246ms) [Timing d4f5b12]
27 Aug 2021 11:47:41.478
Loading media from database [Timing d4f5b12]
27 Aug 2021 11:47:41.447
Completed. (254ms) [Timing c88405d]
27 Aug 2021 11:47:41.192
Loading content from database [Timing c88405d]
27 Aug 2021 11:47:18.313
Adding examine event handlers for 3 index providers.
27 Aug 2021 11:47:18.277
Completed. (239ms) [Timing 32bfe1d]
27 Aug 2021 11:47:18.037
Loading media from database [Timing 32bfe1d]
27 Aug 2021 11:47:18.010
Completed. (466ms) [Timing f144e79]
27 Aug 2021 11:47:17.544
Loading content from database [Timing f144e79]
27 Aug 2021 11:25:19.892
Completed. (253ms) [Timing bd773d5]
27 Aug 2021 11:25:19.638
Loading media from local cache file [Timing bd773d5]
27 Aug 2021 11:25:19.598
Completed. (262ms) [Timing b8e4788]
27 Aug 2021 11:25:19.335
Loading content from local cache file [Timing b8e4788]
27 Aug 2021 11:25:16.418
Creating the media store, localMediaDbExists? true
27 Aug 2021 11:25:16.386
Creating the content store, localContentDbExists? true
27 Aug 2021 11:25:16.346
Registered with MainDom, localContentDbExists? true, localMediaDbExists? true
27 Aug 2021 11:25:14.677
Content root path: C:\home\site\wwwroot
27 Aug 2021 11:25:14.677
Hosting environment: Test
27 Aug 2021 11:25:14.677
Application started. Press Ctrl+C to shut down.
27 Aug 2021 11:25:11.407
uSync: Startup Complete 9ms
27 Aug 2021 11:25:11.180
Profiler is VoidProfiler, not profiling (must run debug mode to profile).
27 Aug 2021 11:25:10.188
Acquired. 
```

### Steps to reproduce

Publish a site on Azure

### Expected result / actual result

Expected result is that the site loads only from the local cache if available, and if not only load from database one time.

**Comment by nul800sebastiaan** [comment]
Thanks @deMD - just trying to reproduce, how do I see the logs you're seeing please (keep in mind that I know very little about azure, I've heard of the term SEQ but not sure where to find it, so I'll need some pointing out please 🙏).

**Comment by deMD** [comment]
You should be able to see the same logs in the Umbraco backoffice log viewer.

**Comment by deMD** [comment]
One specific detail I notice I missed in the opening issue post, I did upgrade the site from rc1 to rc2.

**Comment by nul800sebastiaan** [comment]
Thanks @deMD! That's easier indeed. So far, so good, these occur for me after restarting the website, I'll keep an eye on it but I don't know what else to do to trigger this constant reloading. I've browsed the frontend a bit as well.

![image](https://user-images.githubusercontent.com/304656/131693675-8e6d456b-3c73-48f3-ab03-ee4225017b61.png)

Maybe you could attempt to deploy a fresh RC2 with something like the starter kit to see if it still is an issue there. That said I fail to see how it could be an upgrade issue, don't think anything could get "stuck" during an upgrade.

**Comment by nul800sebastiaan** [comment]
Ah, I also see uSync in the mix there, after you try a fresh clean RC2, try what happens if you add uSync in the same way you did for this site?

**Comment by nul800sebastiaan** [comment]
No change overnight for me, I just tried to overwhelm the site with some loader.io traffic as well but that didn't make a difference either.

At this point I'll close the issue for now and ask you to try out the above suggestions of a clean RC2 with something installed like starter kit and then add uSync if it doesn't load media and content constantly. Let us know if you have more info to reproduce and we can have a look at it again!

**Comment by deMD** [comment]
Issue returned after upgrading to RC3. Seems to only trigger on a site set as a replica server.

**Comment by deMD** [comment]
Issue seems to be something with shutting down the site not releases resources in Azure (I think). Manually stopping the site and restarting after a few minutes caused the site to start properly again
