### ISSUE TITLE
ImageSharp does not appear to handle some PNG files properly

### ISSUE THREAD

**Issue by jaddie** [umbraco/Umbraco-CMS#10961]
### Which *exact* Umbraco version are you using? For example: 8.13.1 - don't just write v8

V9-RC002

### Bug summary

I've been messing around trying to work out if there is a bug in Umbraco or ImageSharp but in the latest version I've noticed images are not rendering properly in some cases now, anything that is a PNG won't render properly. I've attached one for testing with, it renders about 30% of the way & then glitches and that's it.

Any help to figure out why this is happening would be great!
![pump99logo-1](https://user-images.githubusercontent.com/68933/130987525-5412a299-f0a5-4971-b7c1-21e60c3238be.png)

### Specifics

https://staging.pump99.co.uk/ as an example of what it looks like on the front-end, scroll to the bottom of the page, JPG files are unaffected it seems

### Steps to reproduce

Not 100% sure, seems to be PNG files but not all of them causing issues, if I had to hazard a guess I'd say it seems like ImageSharp is still too unstable to use really, I did try to use the pre-release version & rebuild Umbraco, but that caused all sorts of fun with .netstandard so I gave up & am taking a break from it now.

### Expected result / actual result

The image should render without issue, or if there is a problem manipulating the image, then it should catch this error & at least serve the original full size file so the site doesn't look terrible

**Comment by jaddie** [comment]
Just as a note for this issue btw for anyone else that might come across this, I cannot say this with 100% certainty, as I tried it with a local Umbraco 9 build & it worked as @nul800sebastiaan said, however the original site still wouldn't work, I then remembered I am using .net6.0 so edited the csproj back to .net5.0 and erased everything from the TEMP/Mediacache folder & it working again it seems, I will keep an eye & see if it was a fluke or not & also test with a fresh local build and change that to .net6.0, but something to keep in mind for the future.

**Comment by nul800sebastiaan** [comment]
Ah, well, it shouldn't be caused by the compilation since ImageSharp comes compiled.. but.. maybe there was a weird interaction indeed. Anyway, let's keep an eye on it, seems like a fluke at the moment! 😄

**Comment by brianpopow** [comment]
This was (very likely at least) an issue with ImageSharp version 1.0.3 in combination with .net6.0 with png files. The issue was fixed with [Fix1704](https://github.com/SixLabors/ImageSharp/issues/1704). There is now a hotfix version 1.0.4 which was created especially for that.
