### ISSUE TITLE
AppSettings.json to configure Serilog.File Sink  doesn't seem to work

### ISSUE THREAD

**Issue by mistyn8** [umbraco/Umbraco-CMS#10965]
### Which *exact* Umbraco version are you using? For example: 8.13.1 - don't just write v8

v9-rc002

### Bug summary

```
 "Serilog": {
    "MinimumLevel": {
      "Default": "Information"
    },
    "WriteTo": [
      {
        "Name": "Async",
        "Args": {
          "configure": [
            {
              "Name": "Console"
            },
            {
              "Name": "File",
              "Args": {
                "restrictedToMinimumLevel": "Warning"
              }
            }            
          ]
        }
      }      
    ]
  },
```
I'm expecting that the json files only now write warning logs, but information logs are still appended.

### Specifics

Ps I'm wanting to do this as Using `Seq` Sink for better structured logging/reporting/interrogation.. so would like information logging there, so only require minimal logging in json files.

https://github.com/serilog/serilog/wiki/Configuration-Basics#overriding-per-sink

Setting the `minimumLevel` for serilog globally would affect all sinks.

https://github.com/umbraco/Umbraco-CMS/blob/48fcfcae21c579231268147167619274482abef3/src/Umbraco.Infrastructure/Logging/Serilog/LoggerConfigExtensions.cs presumably is where config needs to take account of appsettings.json

### Steps to reproduce

update `appsettings.json` as in the summary, and json file based logs are not restricted to `Warning`.

**Comment by bergmania** [comment]
Hi @mistyn8 ..

I can confirm this is not possible. Ill make a PR to make it possible.  As the UmbracoFile is not using a regular File Sink due to performance concerns, It will be something like using a "UmbracoFile" name, like this example

```json
{
  "Serilog": {
    "MinimumLevel": {
      "Default": "Information",
    },
    "WriteTo": [
      {
        "Name": "UmbracoFile",
        "Args": {
          "restrictedToMinimumLevel": "Warning"
        }
      },
      {
        "Name": "Async",
        "Args": {
          "configure": [
            {
              "Name": "Console",
              "Args": {
                "restrictedToMinimumLevel": "Information"
              }
            }
          ]
        }
      }
    ]
  },
}

```
