### ISSUE TITLE
Setting up SMTP on V9

### ISSUE THREAD

**Issue by meyntony** [umbraco/Umbraco-CMS#11017]
Version 9 RC2

### Bug summary

Although I setup the SMTP server in the appsettings.json as follows
```
"Umbraco": {
    "CMS": {
      "Hosting": {
        "Debug": false,
      },
      "Global": {
        "Id": "5f01b867-abd8-45dc-8c74-06de5e470208",
        "Smtp": {
          "From": "smtpumbraco@gmail.com",
          "DeliveryMethod": "Network",
          "Host": "smtp.gmail.com",
          "Port": 587,
          "Username": "smtpumbraco@gmail.com",
          "Password": "somePublic***Password",
          "SecureSocketOptions": "SslOnConnect"
        }
      }
    }
```
I get the following error in the umbraco logs when Umbraco trys to send me notifications

> No connection could be made because the target machine actively refused it 127.0.0.1:25

Even if I'm not configuring it correctly, I don't see why it should try to search for a local SMTP server on the default SMTP port i.e. 25, when the configuration is for port 587.

### Specifics

Since the documentation does not exist yet: https://our.umbraco.com/documentation/Umbraco-Cloud/set-up/SMTP-settings/

I used the `appsettings-schema.json` to guess the config details.

### Steps to reproduce

[This repo that has both version 8 and version 9](https://gitlab.com/umbracohowto/OurUmbracoSMTP)

Version 8 for the same SMTP credentials works just fine. I have made another branch in the same repo for version 9

### Expected result / actual result

Expected no error, but an email in my inbox but:
Error:
![image](https://user-images.githubusercontent.com/85172999/131827042-8745b8d7-5e02-4135-9051-c80611c02541.png)

**Comment by nul800sebastiaan** [comment]
I can reproduce, the host is ignored and my password reset email arrives on my localhost (PaperCut SMTP is great for local SMTP testing).

**Comment by nul800sebastiaan** [comment]
Still an issue in vLatest!

**Comment by bergmania** [comment]
I cannot reproduce :).

In your test repro, you override the settings in  [`appsettings.json`](https://gitlab.com/umbracohowto/OurUmbracoSMTP/-/blob/version-9/ourumbraco/appsettings.json), but overrides them with local information in [`appsettings.Development.json`](https://gitlab.com/umbracohowto/OurUmbracoSMTP/-/blob/version-9/ourumbraco/appsettings.Development.json)..

That would give the error you see.
You will need do not run in `ASPNETCORE_ENVIRONMENT = Development` or remove the info from `appsettings.Development.json`. To change the `ASPNETCORE_ENVIRONMENT `, you can find the 
environment variables in [launchSettings.json](https://gitlab.com/umbracohowto/OurUmbracoSMTP/-/blob/version-9/ourumbraco/Properties/launchSettings.json)

**Comment by meyntony** [comment]
```
"Smtp": {
          "From": "smtpumbraco@gmail.com",
          "DeliveryMethod": "Network",
          "Host": "smtp.gmail.com",
          "Port": 587,
          "Username": "smtpumbraco@gmail.com",
          "Password": "somePublic***Password",
          "SecureSocketOptions": "StartTls"
        }
```

@bergmania : Yes, that was it :) 
Thanks for the tutorial for handling config transforms :) For those reading this will also help https://blog.elmah.io/config-transformations-in-aspnetcore/

btw my config still didn't work, I had to change the `SecureSocketOptions `to `StartTls` from `SslOnConnect` and then everything worked as expected, but that was on me as well.
