### ISSUE TITLE
CORS Origin Issue

### ISSUE THREAD

**Issue by Ibrahimogod** [umbraco/Umbraco-CMS#11018]
### Which *exact* Umbraco version are you using? For example: 8.13.1 - don't just write v8

V 8.15.2

### Bug summary

I'm Trying To do and HTTP Options Request But I'm Getting an Error CORS Origin I tried to add 
<add name="Access-Control-Allow-Origin" value="*" /> 
to the Web.config file but error still exists 

### Steps to reproduce

Let Me know how to solve the Issue 

### Expected result / actual result

Love you alll

**Comment by nul800sebastiaan** [comment]
Hi there @Ibrahimogod, this sounds like an excellent question for the forums where our friendly community can help you find the best solution for your requirements. 

Make sure to head on over to https://our.umbraco.com and ask follow up questions there! 👍
