### ISSUE TITLE
Structured logging with IProfilingLogger.TraceDuration does not work

### ISSUE THREAD

**Issue by Nikkelmann** [umbraco/Umbraco-CMS#11033]
### Which *exact* Umbraco version are you using? For example: 8.13.1 - don't just write v8

9.0.0-rc002

### Bug summary

Calling `TraceDuration<T>` with `string startMessage` and `object[] startMessageArgs` does not output the expected text in the log.

Might be related to #9958

### Steps to reproduce

Code used to log:
`_profilingLogger.TraceDuration<MyService>("Fetching data with Type Id: {typeId} from {catalog}", new object[] { typeId, catalog })`

### Expected result / actual result

**Expected log output:**
"Fetching data with Type Id: 1 from assorted" [Timing "c6f1746"]

**Actual log output:**
"Fetching data with Type Id: {typeId} from {catalog}" [Timing "c6f1746"]

**Comment by bergmania** [comment]
Hi @Nikkelmann, thanks for reporting.. Fixed in https://github.com/umbraco/Umbraco-CMS/pull/11034
