### ISSUE TITLE
Crop Urls Ignored in an Img Srcset

### ISSUE THREAD

**Issue by nobledm** [umbraco/Umbraco-CMS#11047]
### Which *exact* Umbraco version are you using? For example: 8.13.1 - don't just write v8

Cloud (8.15.1)

### Bug summary

Umbraco will only use the last listed crop url in an image srcset. Unless another img tag on the page uses another crop url of the same image, in which it will then use those two but still ignore every other srcset url. This problem does not occur for picture tag.

### Specifics

Am using Media Picker 3 local crops, have not tested global or using the legacy picker. Showing simplest form of code snippets.

```
<img src="@content.Image.GetLocalCropUrl("mobile")"
        srcset="
         @content.Image.GetLocalCropUrl("mobile") 588w, 
         @content.Image.GetLocalCropUrl("tablet") 1077w,
         @content.Image.GetLocalCropUrl("desktop")" />
```

If trying to use a simple img srcset like above, Umbraco site will only ever load the 'desktop'. I've confirmed all the different crop urls are being inserted as expected and all look fine in the rendered html.

I have tested a case where I inserted a second image tag, no srcset, that only grabbed the 'mobile' alias. In that case the srcset would load the 'mobile' and 'desktop' in their appropriate breakpoints, but tablet was ignored.

Changing the img srcset for a picture tag doesn't have the same problem so is something to work around. So the below works as expected.

```
<picture>
        <source 
            srcset="
             @content.Image.GetLocalCropUrl("mobile") 588w, 
             @content.Image.GetLocalCropUrl("tablet") 1077w, 
             @content.Image.GetLocalCropUrl("desktop")">
        <img src="@content.Image.GetLocalCropUrl("mobile")" />
</picture>
```

### Steps to reproduce

Create Local Crops on a Media Picker 3 image.
Render them in an image srcset tag.
See if anything but the final one in the list (presumably largest) is loaded.

### Expected result / actual result

If loading on an uncached small screen (eg: below 588px wide), it should load the 'mobile' alias crop of the image. 'desktop' should only ever be loaded when screen width above 1077w instead of on all sizes.

**Comment by rbottema** [comment]
You mention the generated HTML is correct, and from there Umbraco's job is done. Which image to display is the browser's responsibility and different browsers will choose different images based on the circumstances. For example, Chrome chooses a higher resolution URL if that one is already cached in the browser. This is according to the HTML spec, for example [as described on MDN:](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/img#attr-srcset)

> The user agent selects any of the available sources at its discretion. This provides them with significant leeway to tailor their selection based on things like user preferences or bandwidth conditions.

If you need to ensure certain resolutions are loaded at certain resolutions (for example due to different aspect ratios), the `picture` element is indeed the way to go. [This article on MDN](https://developer.mozilla.org/en-US/docs/Learn/HTML/Multimedia_and_embedding/Responsive_images) is an interesting read about it: they call it the 'art direction problem' versus the 'resolution switching problem'.

**Comment by greystate** [comment]
This doesn't (initially) sound like a problem with Umbraco (as long as the media URLs are rendered correctly).

One issue I've had when implementing something similar is that it's ultimately up to the browser to choose the "best" image for the situation - e.g. if the 'desktop' crop has already been cached, then it's probably better to just use that and not set off another download.

A couple of things I noticed (and please feel free to correct me if they don't make sense, or you've left them out for brevity):

- You're not using the `sizes` attribute that (usually) goes along with the `w` descriptors,  to give the browser hints as to how much of the screen the image is supposed to use.
- There's no `width` + `height` attributes either (which could also give a hint to the size)

**Comment by nobledm** [comment]
The above snippets are bare for brevity.

I did a bunch of testing with the code in question and it works exactly as expected outside of Umbraco. The part that made me think it was something with how Umbraco was interacting was that the srcset works if somewhere else on the page a crop url earlier in the set was being requested. As I mentioned in the initial post, something like this:

`<img src="@content.Image.GetLocalCropUrl("mobile")"
        srcset="
         @content.Image.GetLocalCropUrl("mobile") 588w, 
         @content.Image.GetLocalCropUrl("tablet") 1077w,
         @content.Image.GetLocalCropUrl("desktop")" />
         
  <img src="@content.Image.GetLocalCropUrl("mobile")" />`
  
Would have the image srcset properly work for the mobile & desktop sizes, but tablet would never be grabbed. Nothing was changed with the srcset, all that happened was a specific call for one of the other crops.

Cache was being cleared each time I was testing for non-desktop sizes so that shouldn't be a problem. I wouldn't rule out it's someway the browser is talking to Umbraco that's causing the issue maybe? I'm not well versed in that area.

**Comment by nul800sebastiaan** [comment]
Hi there @nobledm - this sounds like an excellent question for the forums where our friendly community can help you find the best solution for your requirements. 

I think @greystate is right here, we're not doing anything special in that regard in Umbraco. I would recommend you post your actual code, the output and the expected output so people can help you get to where you want.

Make sure to head on over to https://our.umbraco.com and ask follow up questions there! 👍
