### ISSUE TITLE
Mandatory Image not validating after first time failure

### ISSUE THREAD

**Issue by jawood1** [umbraco/Umbraco-CMS#11057]
### Which *exact* Umbraco version are you using? For example: 8.13.1 - don't just write v8

8.16

### Bug summary

I initially started getting this issue most recently on an existing install that I had upgraded from 8.14.1 to 8.16 with a slight difference in the outcome to a fresh installation.

On upgrade I could no longer save and publish the page if the the image field was mandatory even and I applied an image before the validation error occurred. 

I then thought to test this using a fresh install of Umbraco 8.16 to see if it was just me or a bug.

On the fresh install when I added a mandatory image field then saved and published without an image I got the validation error. Once I added the image it wouldn't allow me to save without refreshing the page.

### Specifics

I've tested this on the latest versions of Firefox and Chrome.

Looking in the console logs on initial save without the image I get a 400 error. Once the image is added it won't allow me to save and no further logs are produced.

![image](https://user-images.githubusercontent.com/47325234/132543050-bd638dce-4a87-4019-8885-aee0253fc855.png)

### Steps to reproduce

1. Save and Publish the page without an image field being filled

![on inital save](https://user-images.githubusercontent.com/47325234/132542097-22ffa2ac-14ab-46f3-b6a7-25c752b579b7.PNG)

2. Add an image, Validation error isn't cleared and the page won't save.

![image](https://user-images.githubusercontent.com/47325234/132542269-98d35401-a478-4fe8-bb16-e1d54981f138.png)

### Expected result / actual result

Once the image is added for the page to save.

---
_This item has been added to our backlog [AB#14294](https://dev.azure.com/umbraco/243e7927-03b2-44e2-908f-d4ac7ea5daaa/_workitems/edit/14294)_

**Comment by emma-hq** [comment]
Hiya @jawood1 

Thanks for reporting this. I'll take a look and reproduce and tag. If it's regression, which I suspect given your report, I'll label it as such and we'll look at cherry picking the solution. I'll let you know what happens!

Emma

**Comment by nul800sebastiaan** [comment]
Thanks @jawood1 - we'll have to have a look, I can reproduce. The workaround for now is to Save first and then Save & Publish, then it will indeed work properly.

https://user-images.githubusercontent.com/304656/136032641-7a88e91e-03cf-412d-8dcd-7dda111b4d22.mp4

**Comment by nul800sebastiaan** [comment]
Cherry picked for 8.17.1 in da48f8435a914cf809a05b0305c154d55715e5a3
