### ISSUE TITLE
Custom Indexes No Longer Work

### ISSUE THREAD

**Issue by AaronSadlerUK** [umbraco/Umbraco-CMS#11063]
### Which *exact* Umbraco version are you using? For example: 8.13.1 - don't just write v8

9.0.0-rc3

### Bug summary

Since upgrading to V9 RC3 the site no longer boots, due to an issue creating the indexes

```
InvalidOperationException: A suitable constructor for type 'SecretProject.Core.Components.KnowledgebaseIndex' could not be located. Ensure the type is concrete and services are registered for all parameters of a public constructor. 
```

### Steps to reproduce

Register a custom index as below:

 ```   public class IndexHelperComposer : IComposer
    {
        public void Compose(IUmbracoBuilder builder)
        {
            IServiceCollection services = builder.Services;
            services
            .AddExamineLuceneIndex<KnowledgebaseIndex, ConfigurationEnabledDirectoryFactory>("KnowledgebaseArticles");
        }
    }
```
```
        public class KnowledgebaseIndex : UmbracoExamineIndex, IUmbracoContentIndex, IDisposable
    {
        private readonly ILogger<KnowledgebaseIndex> _logger;
        public KnowledgebaseIndex(
            ILoggerFactory loggerFactory,
            string name,
            IOptionsSnapshot<LuceneDirectoryIndexOptions> indexOptions,
            IHostingEnvironment hostingEnvironment,
            IRuntimeState runtimeState)
            : base(loggerFactory, name, indexOptions, hostingEnvironment, runtimeState)
        {
            _logger = loggerFactory.CreateLogger<KnowledgebaseIndex>();
            LuceneDirectoryIndexOptions namedOptions = indexOptions.Get(name);
            if (namedOptions == null)
            {
                throw new InvalidOperationException($"No named {typeof(LuceneDirectoryIndexOptions)} options with name {name}");
            }


            if (namedOptions.Validator is IContentValueSetValidator contentValueSetValidator)
            {
                PublishedValuesOnly = contentValueSetValidator.PublishedValuesOnly;
            }
        }

        void IIndex.IndexItems(IEnumerable<ValueSet> values) => PerformIndexItems(values.Where(v => v.ItemType == "knowledgebaseArticle"), OnIndexOperationComplete);
    }
```

### Expected result / actual result

Index to be created as per v9 RC2

**Comment by bergmania** [comment]
`IOptionsSnapshot<LuceneDirectoryIndexOptions> indexOptions` needs to be updated to `IOptionsMonitor<LuceneDirectoryIndexOptions> indexOptions`

**Comment by AaronSadlerUK** [comment]
Making that change shows a conversion error:

`cannot convert from 'Microsoft.Extensions.Options.IOptionsMonitor<Examine.Lucene.LuceneDirectoryIndexOptions>' to 'Microsoft.Extensions.Options.IOptionsSnapshot<Examine.Lucene.LuceneDirectoryIndexOptions>'`


Nope it builds fine, all the projects have dependencies on rc3:

![image](https://user-images.githubusercontent.com/9937803/132692804-5cffd610-5181-4847-ae62-d0234599127d.png)

**Comment by AaronSadlerUK** [comment]
Ok so an update on this, interestingly another project I was referencing, even though it had a dependency of rc3, it didn't want to build.

I removed and then re-added the project reference, and hey presto it works 🤔 Visual Studio cache maybe? Although I did clear all those...

It's now showing in the back office though, I'll update my blog post to outline this change.

Thanks @bergmania!
