### ISSUE TITLE
Sort permission in granular permissions not working as expected

### ISSUE THREAD

**Issue by jesperweber** [umbraco/Umbraco-CMS#11066]
### Which *exact* Umbraco version are you using? For example: 8.13.1 - don't just write v8

8.16.0

### Bug summary

Sort permission in granular permissions only works if you set sort permissions on every descendant nodes.

### Steps to reproduce

1. Create a node with two or more children
2. Create a user group with the following permissions
![image](https://user-images.githubusercontent.com/2575817/132699809-050c0131-970c-4910-a4d6-9ada481d44c3.png)
3. Add a user to the user group and login with that user
4. Try to sort the children (you have the sort option in the menu because you have the sort permission on the parent node) but the sort dialog don't show any children to sort
![image](https://user-images.githubusercontent.com/2575817/132700206-310b70d3-db47-401d-a502-a9f58c3a73e2.png)

If you add the browse and sort permissions to one or more of the children then you can sort these specific children, but this means that you have to add the sort permission on every descendant node and every time a new node is created.
![image](https://user-images.githubusercontent.com/2575817/132700553-4fd87ee0-81ec-4e91-81eb-ab09f72dca53.png)

Now you can sort the to children with the sort permission

![image](https://user-images.githubusercontent.com/2575817/132700571-38af7c92-9f3e-4301-b51c-b5ec0dd62bef.png)

### Expected result / actual result

If I set the sort permission on a node in granular permission I would expect to be able to sort every descendents.

**Comment by nul800sebastiaan** [comment]
Hi @jesperweber and sorry for the late reply. I've given this scenario a go (admittedly in 8.17, not 8.16, but I can't imagine we changed anything related to this). Unfortunately the scenario seems to work for me.

https://user-images.githubusercontent.com/304656/136027662-ca03e8cd-d4a8-4c61-bae4-0d3e4c35575f.mp4

If you have more steps to reproduce then we can have another look but for now I'll close this issue as everything seems to work as expected.

**Comment by jesperweber** [comment]
Hi @nul800sebastiaan, we just had another of our customers reporting the same issue.

I just upgraded to 8.17.1 and is still able to recreate the issue.

When looking at the requests when opening the sort dialog I see a request to umbraco/backoffice/UmbracoApi/Content/GetChildren but the request returns an empty collection for the items property.

![sort](https://user-images.githubusercontent.com/2575817/142205827-5e64d112-5a40-40dc-b705-519ada0f90e8.gif)
