### ISSUE TITLE
8.15.3 to 8.16 NuGet dependency error

### ISSUE THREAD

**Issue by timlaughlin** [umbraco/Umbraco-CMS#11077]
### Which *exact* Umbraco version are you using? For example: 8.13.1 - don't just write v8

8.15.3

### Bug summary

Getting the following dependency error when trying to upgrade via NuGet

Install-Package : Unable to resolve dependencies. 'System.Collections.Immutable 5.0.0' is not compatible with 'UmbracoCms.Web 8.16.0 constraint: System.Collections.Immutable (>= 1.7.1 
&& < 1.999999.0)'.

### Steps to reproduce

PM> Install-Package UmbracoCms -Version 8.16.0

**Comment by nul800sebastiaan** [comment]
Hi @timlaughlin - seems annoying.. do you have `System.Collections.Immutable` already installed (and is it v5.0.0?). 
I'm afraid we had some problems with this and other dependencies causing YSODs, unfortunately we had to limit the versions installed. 

If you have any nugets installed that absolutely require the 5.0.0 version of  `System.Collections.Immutable`  then I think the only way to work with that is to uninstall that one, do the upgrade, then re-install it with the `-IgnoreDependencies` flag.

I know this is super annoying but we need to work with the unfortunate limitations that nuget has here and do right by the largest amount of our users. Unfortunately, you're the small minority having to work around this I'm afraid. 

Please do feedback here, I will keep reading and I'm sure we can get you upgraded! I'll close this for now but only for the reason that our hands our tied. I can keep helping you complete the upgrade. Promise I'll have faster response times than 11 days 🙈
