### ISSUE TITLE
U9 GetCropUrl Not Working From RC001 till RC003

### ISSUE THREAD

**Issue by Lachanophobia** [umbraco/Umbraco-CMS#11087]
### Which *exact* Umbraco version are you using? For example: 8.13.1 - don't just write v8

V9-RC003

### Bug summary

I am working with U9 in a new project from the very first day it was released. The GetCropUrl() never worked for me.

I have upgrade the U version from RC001 to RC002 and now to RC003. I have seen there was some fixes about the image processor and the crop Urls but I had no luck.

I tried to create a new project from the scratch in RC003 and try the crop Urls. And they worked!

So then, I copied all my .cs, .razor and .cshtml files from my old project to the new one and I replaced the appsettings.json file to have all my settings and to connect to my DB.
I run the project and again it didn't work!! Its really frustrating ! 

here is a code sample of mine. I have change the value of the Layout to null just to make it clear that no styles are applied.

```
@inherits UmbracoViewPage<BasePageViewModel>
@{
    Layout = null;
    var page = Model.Content as Page;
    var banner = page.BlockList.FirstOrDefault(x => x.Content.ContentType.Alias == BannerBlog.ModelTypeAlias).Content as BannerBlog;
}

@*@Html.GetBlockListHtml(Model, page.BlockList)*@

<p>
    @(banner.BannerImage.GetCropUrl(100, 50)) <br>
    @(banner.BannerImage.GetCropUrl(100, 100)) <br>
    @(banner.BannerImage.GetCropUrl(400, 700)) <br>
</p>

<img src="@(banner.BannerImage.GetCropUrl(100, 50))"/>
<img src="@(banner.BannerImage.GetCropUrl(100, 100))"/>
<img src="@(banner.BannerImage.GetCropUrl(400, 700))"/>
```
and that's the result (I have zoomed out to fit all the images in the screenshot)
![image](https://user-images.githubusercontent.com/78937287/133082080-476c9468-e11f-4f40-88e5-9c5058f8dfff.png)

Here are the crop Urls I am getting 
/media/acqhkczm/pic-banner.jpg?width=100&height=50&rnd=132760024173600000
/media/acqhkczm/pic-banner.jpg?width=100&height=100&rnd=132760024173600000
/media/acqhkczm/pic-banner.jpg?width=400&height=700&rnd=132760024173600000

I have also tried to add parameters like "useCropDimensions" or "imageCropMode" and to use alias instead of dimension. Again nothing!  

in case that matters, I am using "ModelsMode": "SourceCodeAuto"

Any help would be mush appreciated!! 

### Steps to reproduce

.. No clue!  

### Expected result / actual result

To Crop The Image!

**Comment by nul800sebastiaan** [comment]
Sorry for the frustrating experience, indeed before RC003 we had some problems generating them. You unfortunately now have cached items that will stick around for a while. Make sure to delete everything from `~/mediacache`  and try again, that should do the trick! 🤞 

If not, let us know and we can have another look.

**Comment by Lachanophobia** [comment]
Hi Sebastiaan!

Thanks for the response! Sorry but it seems it was my bad, I finally found the issue! When I was on the RC002 I had add in the startup file "app.UseStaticFiles();" and it seems that doesn't work with the image processor.

 So on RC1 it was broken, on RC2 I broke it.. and I was just so confused on whats going wrong!

**Comment by nul800sebastiaan** [comment]
Oh no! Good to hear that you've found the problem though! 👍
