### ISSUE TITLE
GetCropUrl() not taking focal point, zoom or width/height into consideration

### ISSUE THREAD

**Issue by bjornnorlen** [umbraco/Umbraco-CMS#11098]
### Which *exact* Umbraco version are you using? For example: 8.13.1 - don't just write v8

Umbraco version 9.0.0-rc001

### Bug summary

The method GetCropUrl() doesn't work properly since it doesn't take focal points or zooming into considerations. It also seems like the width/height properties are mixed up.

### Specifics

Umbraco version 9.0.0-rc001
Tested in Edge and Chrome

Creating settings for the picker:
![image](https://user-images.githubusercontent.com/19406378/133262273-5911a89e-e4bd-48c6-a2f3-87315088226e.png)

Cropping the image in the content-section. The first image should be cropped so the top of the trees are visible. The second image is zooming in on the cars. The third image is cropped to the right and has a width of 200px and a height of 400px:
![image](https://user-images.githubusercontent.com/19406378/133262370-85e5d3d6-e825-42ff-a7f4-b7346d2a2a49.png)

The images rendered on the front-end. The first image isn't showing the top of the trees, the second image doesn't zoom and the third image has the width/height properties mixed up:
![image](https://user-images.githubusercontent.com/19406378/133262402-18148073-b998-48f9-a1cd-3f10a619a6a4.png)

The code used for rendering:
![image](https://user-images.githubusercontent.com/19406378/133262425-2b843681-c007-4d03-a92f-45e223cbc1ed.png)

Also, according to https://github.com/umbraco/Umbraco-CMS/issues/10747 the method GetLocalCropUrl() is obsolete and if that's the case the documentation with examples for the picker might need an update: https://our.umbraco.com/Documentation/Fundamentals/Backoffice/Property-Editors/Built-in-Property-Editors/Media-Picker-3/index-v9. 

### Steps to reproduce

- Create a document type
- Add the media picker editor (not the legacy one)
- Enable focal point and define crops
- Render the crops with GetCroptUrl()

### Expected result / actual result

Expecting that the images are cropped according to focal point, zoom and width/height properties defined.

**Comment by nul800sebastiaan** [comment]
Sorry that you went through all the trouble making this big bug report @bjornnorlen - we have fixed the cropping issues in the latest RC003 and I would encourage you to try that one instead. Next time you notice a bug do make sure you're on the latest version, things are moving fast at the moment 🙈

**Comment by bjornnorlen** [comment]
@nul800sebastiaan Thanks for the fast reply :) I was looking for a way to upgrade but didn't find how to do it until I found this: https://our.umbraco.com/Documentation/Fundamentals/Setup/Upgrading/general-v9. I've upgraded to rc003 but it's failing to install (getting a MissingMethodException). I'll see if I can resolve it or find any posts about it, otherwise I'll create an issue.
