### ISSUE TITLE
Multi-URL Picker does not save values when used in a nested block list item when using the new tabs feature

### ISSUE THREAD

**Issue by argentini** [umbraco/Umbraco-CMS#11100]
### Which *exact* Umbraco version are you using? For example: 8.13.1 - don't just write v8

Umbraco v9 RC3

### Bug summary

Multi-URL Picker does not save values when used in a nested block list item when using the new tabs feature. The picker is empty after save. The property editors should be directly under the tab, not in a standard panel.

### Steps to reproduce

Add a multi-URL picker to a block list item child of another block list item and try to save data. The block list items should both use the new tabs feature.

**Comment by backlash1897** [comment]
I can confirm the bug in Umbraco 9 RC3. Values are saved for a regular document property, but not when used in a block referenced by block list editor

**Comment by nul800sebastiaan** [comment]
We'll need some more info on how to reproduce I am afraid. Both in v8 and v9 this seems to work for me: 

https://user-images.githubusercontent.com/304656/133435781-b8a5a57e-32e1-4966-ac8c-2a51aba0da8d.mp4

Surely if you can both reproduce I must have done something different, so I need to know what that is.

Maybe the best way would be to share your site + db with us or generate a package.xml from the backoffice with all the relevant doctypes, and datatypes so we can import it and give it a whirl. 

https://user-images.githubusercontent.com/304656/133436413-912deecc-f51a-4b36-b7d2-b45f2857b587.mp4

**Comment by backlash1897** [comment]
I have narrowed down the bug I perceive to a scenario where the multi-url editor is placed directly inside a property tab (the new feature) of an element type, not inside a property group.
[package.zip](https://github.com/umbraco/Umbraco-CMS/files/7170635/package.zip)

**Comment by argentini** [comment]
@backlash1897 yes, I'm using the new tabs for all my editors. So that makes sense.

**Comment by nul800sebastiaan** [comment]
Makes sense, I'll test that!

**Comment by nul800sebastiaan** [comment]
Alright, I've reproduced now with that setup! Sorry for the delay. We'll get on it. 

![11100_2](https://user-images.githubusercontent.com/304656/134186299-3efec72c-d233-4be4-ab16-706e520e30b1.gif)
