### ISSUE TITLE
V9: Saving document types generates new property group unique keys on each save.

### ISSUE THREAD

**Issue by AndyButland** [umbraco/Umbraco-CMS#11116]
### Which *exact* Umbraco version are you using? For example: 8.13.1 - don't just write v8

Latest v9/dev

### Bug summary

When saving a document type, the property groups are getting new unique Ids generated each time.

### Steps to reproduce

- Create a document type with a property group and save.
- Find the Id of the new document type from the querystring and query the following in the database

```
select * from cmsPropertyTypeGroup where contenttypenodeid = <id>
```

- Observe the `uniqueId` field.
- Make a change and save the document type.
- Note that the `uniqueId` field has changed.

### Expected result / actual result

The unique Id should not change.

Have confirmed on a V8 site - recent, but not the latest - that it doesn't,

**Comment by bergmania** [comment]
I can confirm it is also a problem in v8.17
