### ISSUE TITLE
v9: Nested Content not rendered when group name contains "System".

### ISSUE THREAD

**Issue by PhyxionNL** [umbraco/Umbraco-CMS#11114]
### Which *exact* Umbraco version are you using? For example: 8.13.1 - don't just write v8

v9 RC3

### Bug summary

If you have nested content with a group name that contains **System**, the properties don't get rendered:
![image](https://user-images.githubusercontent.com/7643972/133584649-87243a73-066a-4061-afa4-d03f7414be76.png)

### Steps to reproduce

- Create a composition.
- Create a group and name it **Test System**.
- Add any property (doesn't matter).
- Create content type from said composition.
- Create nested content with said content type.
- Add nested content to a document type.
- Go to content and try to add the nested content.
- Notice that nothing gets rendered apart from "Item 1".

### Expected result / actual result

This should work, it does in Umbraco 8.

---
_This item has been added to our backlog [AB#13949](https://dev.azure.com/umbraco/243e7927-03b2-44e2-908f-d4ac7ea5daaa/_workitems/edit/13949)_

**Comment by PhyxionNL** [comment]
Also happens when **System** is within the name, so updated report to reflect it.

**Comment by rickbutterfield** [comment]
I believe the issue also exists in v8.17.0-rc. I've managed to narrow it down to this line of code I believe, where you can see from what I've output in the console that `tab.alias` and `ncTabAlias` don't match, so this will never return the correct nested content.

![image](https://user-images.githubusercontent.com/200450/133607821-6f96af50-1b6f-40c0-92d7-a2ca163d63c3.png)

**Comment by rickbutterfield** [comment]
Comparing with the same site running on v8.16...

![image](https://user-images.githubusercontent.com/200450/133609002-dc7e829d-b821-4ee0-800d-0133b481eadf.png)

**Comment by ronaldbarendse** [comment]
@rickbutterfield Thanks for narrowing it down! Looks like `ncTabAlias` is still set to the name, instead of the newly added `alias`.

**Comment by nul800sebastiaan** [comment]
ah, we'll need to fix before we release 8.17 / v9rc4 👍

**Comment by OzoneNZ** [comment]
Looks like the same issue I described in umbraco/Umbraco-CMS#11083 where I found the same `contentType.ncTabAlias` / `tab.alias` mismatch as @rickbutterfield - potentially one of the issues can be closed as a duplicate?

Also wanted to note that this was occurring for **any** property group name in my experience, regardless of whether `System` was in the name
