### ISSUE TITLE
Not possible to delete default membership group

### ISSUE THREAD

**Issue by bjarnef** [umbraco/Umbraco-CMS#11132]
### Which *exact* Umbraco version are you using? For example: 8.13.1 - don't just write v8

8.17.0-RC

### Bug summary

In Umbraco v8.17.0 it is possible to add tabs to document types, media types and member types.

Member types currently by default as a "Membership" group.
It is possible to drag this group in reorder mode to "Convert group to tab" or create a new tab "Membership" and move the properties to this tab.

![image](https://user-images.githubusercontent.com/2919859/133928122-bd9d89ab-4db1-46ea-8d72-c58fa2956c33.png)

It still has the "Membership" under a "Generic" tab and you will get this error on save.

![image](https://user-images.githubusercontent.com/2919859/133928140-6a925eec-e119-4062-b1f0-e0e11f79c19d.png)

I can remove this group and all looks good, but when reloading the page the "Membership" group is back.

https://user-images.githubusercontent.com/2919859/133928198-3977b70d-e6ae-4367-be08-c879d299d686.mp4

### Steps to reproduce

For default member group drag the existing "Membership" group to convert this to a tab or create a new tab "Membership" and move properties to this and delete old "Membership" group.

**Comment by bjarnef** [comment]
It seeems the existing "Membership" group also ignores to be renamed to something else than "Membership"

https://user-images.githubusercontent.com/2919859/133928390-c3a8df48-e8b1-487c-8403-157fa2d7e768.mp4

**Comment by bjarnef** [comment]
Currently the Membership group always contains these core properties, but isn't visible when editing the member type.

![image](https://user-images.githubusercontent.com/2919859/133929321-f738fc4e-a5f1-467a-8938-54d22f216943.png)

**Comment by bjarnef** [comment]
I think this has something to do which the hardcoded standard group name here:
https://github.com/umbraco/Umbraco-CMS/blob/f69cee87f94f46ec014ca36d213552cd4813e6fc/src/Umbraco.Core/Constants-Conventions.cs#L244-L247

used here:
https://github.com/umbraco/Umbraco-CMS/blob/v8/contrib/src/Umbraco.Core/Persistence/Repositories/Implement/MemberTypeRepository.cs#L144-L150

and here:
https://github.com/umbraco/Umbraco-CMS/blob/v8/contrib/src/Umbraco.Core/Persistence/Repositories/Implement/ContentTypeCommonRepository.cs#L249-L266

**Comment by bjarnef** [comment]
@ronaldbarendse since you have done some work on groups and tabs in the upcoming v8.17 maybe you have some thought how to solve this or in future versions?

It would be great if we was able to:

- Rename default Membership group
- Move properties to a tab and remove default Membership group

**Comment by Zeegaan** [comment]
This issue should now be fixed in https://github.com/umbraco/Umbraco-CMS/pull/11587, thanks for the report! 🐛
