### ISSUE TITLE
Solution

### ISSUE THREAD

**Issue by alandraper** [umbraco/Umbraco-CMS#11133]
### Which *exact* Umbraco version are you using? For example: 8.13.1 - don't just write v8

9.0.0-rc001

### Bug summary

The [walkthrough](https://our.umbraco.com/documentation/UmbracoNetCoreUpdates?_ga=2.67495318.640401762.1632064571-1446305646.1632064571#steps-to-create-an-umbraco-solution-using-the-dotnet-new-template) talks about creating an Umbraco Solution, when really it only creates a Project. 

Walkthrough should say create an Umbraco Project using the dotnet new template. 

### Steps to reproduce

dotnet new umbraco -n MyCustomUmbracoProject 

### Expected result / actual result

Creates a .csproj Project file, but no .sln Solution file.

**Comment by bergmania** [comment]
You are right.. I updated the docs..
