### ISSUE TITLE
Unhandled exception loading SqlCe

### ISSUE THREAD

**Issue by alandraper** [umbraco/Umbraco-CMS#11142]
### Which *exact* Umbraco version are you using? For example: 8.13.1 - don't just write v8

9.0.0-rc003

### Bug summary

Debugging in Visual Studio, I get the following unhandled exception. I'm using SQL Server, not SQLCE

The site still seems to load. 

> `System.IO.FileNotFoundException: 'Could not load file or assembly 'C:\Work\MyProject\bin\Debug\net5.0\Umbraco.Persistence.SqlCe.dll'. The system cannot find the file specified.'    at System.Runtime.Loader.AssemblyLoadContext.LoadFromPath(IntPtr ptrNativeAssemblyLoadContext, String ilPath, String niPath, ObjectHandleOnStack retAssembly)
   at System.Runtime.Loader.AssemblyLoadContext.LoadFromAssemblyPath(String assemblyPath)
   at System.Reflection.Assembly.LoadFrom(String assemblyFile)
   at Umbraco.Extensions.UmbracoBuilderExtensions.AddUmbracoSqlCeSupport(IUmbracoBuilder builder)` 

### Steps to reproduce

Fresh install of rc003, build and debug in Visual Studio unhandled exception during startup. Note that I do not have this problem debugging in VS Code.

**Comment by bergmania** [comment]
Hi @alandraper.. It makes no sense this is reported as an unhandled exception, as it is wrapped in a try-cache(all). It is expected this will happens if SqlCE is not referenced.

**Comment by nul800sebastiaan** [comment]
I've tried a few combinations in Visual Studio, but I don't see this error. Maybe have a look at the generated .csproj file and post it here? I've seen some issues with local caches not being expired, maybe we can spot something there. Also. not sure which VS version you're using? Make sure you've updated your VS to the latest. 

For now I'll close this one but if you have more steps to reproduce we can have another look!
