### ISSUE TITLE
V9: MediaPicker3 casing incorrect

### ISSUE THREAD

**Issue by craigs100** [umbraco/Umbraco-CMS#11150]
### Which *exact* Umbraco version are you using? For example: 8.13.1 - don't just write v8

V9.0.0-RC3

### Bug summary

Error bar appears when configuring a MediaPicker3 during a docType set up on Linux

### Specifics

The infinite editor is looking for "views/propertyeditors/MediaPicker3/prevalue/mediapicker3.crops.html" but the actual path is "views/propertyeditors/mediapicker3/prevalue/mediapicker3.crops.html"
Note the casing of MediaPicker vs mediapicker

### Steps to reproduce

When assigning a MediaPicker to a docType, when the property editor's inifinite editing slideout slides out, there is a red error bar showing stating "Request error: The URL returned a 404 (not found):
views/propertyeditors/MediaPicker3/prevalue/mediapicker3.crops.html"

### Expected result / actual result

No error

**Comment by nul800sebastiaan** [comment]
Good catch @craigs100 - should be fixed by https://github.com/umbraco/Umbraco-CMS/pull/11154 which is ready for review now.
