### ISSUE TITLE
Media Picker Preview Background Color Hides White PNG Images with Transparency

### ISSUE THREAD

**Issue by argentini** [umbraco/Umbraco-CMS#11152]
### Which *exact* Umbraco version are you using? For example: 8.13.1 - don't just write v8

Umbraco v9 RC3

### Bug summary

Since white PNG images are very common, it would make sense to color the media picker preview a light gray so they can be seen. In this case, the only images that would be hard to see would be light gray PNG images, which are not a common style.

### Steps to reproduce

Add a white PNG with transparency and you see this:

<img width="521" alt="Screen Shot 2021-09-21 at 10 54 04 AM" src="https://user-images.githubusercontent.com/1504331/134194883-7f905bc3-0e9f-4905-9cde-10533d417b3a.png">

### Expected result / actual result

It would be better to see something like this:

<img width="620" alt="Screen Shot 2021-09-21 at 10 53 21 AM" src="https://user-images.githubusercontent.com/1504331/134194946-22c4983d-04da-4884-9c2f-333891477419.png">

**Comment by nul800sebastiaan** [comment]
Thanks @argentini - this is fixed for the upcoming RC4 already! 👍 

![image](https://user-images.githubusercontent.com/304656/134203002-ddb1dda0-5edb-433e-87f3-354459c14092.png)
