### ISSUE TITLE
Unpublished ContentService not updating IPublishedContents parent's children

### ISSUE THREAD

**Issue by V414** [umbraco/Umbraco-CMS#11164]
### Which *exact* Umbraco version are you using? For example: 8.13.1 - don't just write v8

8.16.0

### Bug summary

I've made a post in further detail on the forum asking for support: [https://our.umbraco.com/forum/using-umbraco-and-getting-started/107082-contentservice-unpublished-event-not-updating-ipublishedcontent-parents-children](https://our.umbraco.com/forum/using-umbraco-and-getting-started/107082-contentservice-unpublished-event-not-updating-ipublishedcontent-parents-children)

### Specifics

The shortened version is that in the ContentService.Unpublished event (so after the Unpublishing event has taken place), accessing the parent of the content that has been unpublished, and checking its children still shows the unpublished content. 

I can rule out my code as the issue, as the behaviour does not happen with the Trashed and Trashing events (I use the same method for both events, and in the Trashed event it doesn't show the trashed content as a valid child).

### Steps to reproduce

Create a page in umbraco, then create a child to that page.

Within the ContentService.Unpublished event, use the unpublished content's parent's ID (I have stored mine in a custom SQL DB) to create an IPublishedContent of the parent, andthen check the parents.children() (either a breakpoint or a console output)

When you unpublished the child content, checking the parents.children() still lists the child (when it shouldn't because its been unpublished).

### Expected result / actual result

The ContentService.Unpublishing event should still show the content we're trying to unpublish as a valid child, but between this event and the ContentService.Unpublished event the IPublishedContent's cache should be updated and only show the valid child objects that have been published - and not include the content we've just unpublished.

**Comment by nul800sebastiaan** [comment]
Hi @V414 - I'm not entirely sure what you're doing with the deleting and things but I'll explain to you how an Unplish works because there lies the root of your problem:

When you unpublish an item we do NOT one by one unpublish all of the descendants, with a large descendants tree, that could take a very long time, So the only thing we do is set the `Published` flag on the item you just unpublished to `False`:

![image](https://user-images.githubusercontent.com/304656/134355779-1a7b806d-0c19-4216-9c0a-9ce8cee32c11.png)

Note here that items 1121 and 1122 are children of the unpublished 1120 and their `Published` flag is still `True`.

In fact that item is still in NuCache as well, also with a `"Published": false` flag:

![image](https://user-images.githubusercontent.com/304656/134356843-65b2f94a-8ec4-41ee-88be-bbe1ae3ad874.png)

Again this is to prevent having to do excessive updates to insert or remove large branches of content.

When you ask for one of the descendants from the cache, we walk up the tree of parents and make sure that all of the ancestors are published before we give you the content item out of the cache. If the parent, or the parent's parent, or parent's parent's parent (and so on) has `"Published": false` on it, we stop and give a 404 back.

So, as I said I'm not quite sure what you're doing with deleting comments in your custom tables, but in order to make it work, I believe you need to do the same thing and make sure that all of the ancestors of that item are set to  `"Published": true`.

Hope this helps!

**Comment by V414** [comment]
Hi @nul800sebastiaan, thanks for the quick reply!

> When you unpublish an item we do NOT one by one unpublish all of the descendants, with a large descendants tree, that could take a very long time, So the only thing we do is set the `Published` flag on the item you just unpublished to `False`:

The thing is, I'm not trying to unpublish a parent and expecting its children to be unpublished (although thank you for the above details, it helps me understand the wider situation) - instead, I'm only trying to unpublishing a child, and then checking the parents.children() within the event, only to find that the unpublished child is still there... 

Is that also expected behaviour? Because I thought unpublished children normally don't show up as a valid children in other circumstances?

**Comment by nul800sebastiaan** [comment]
Did you check the `Published` flag when iterating the children though?

**Comment by nul800sebastiaan** [comment]
I don't know what your code looks like but in the `ContentService` you will still get unpublished children back, maybe that's your problem (please only use the `ContentService` if you have to do write operations, never for just read operations unless you really must get unpublished items as well).

**Comment by V414** [comment]
> I don't know what your code looks like but in the `ContentService` you will still get unpublished children back, maybe that's your problem (please only use the `ContentService` if you have to do write operations, never for just read operations unless you really must get unpublished items as well).

That's hit the nail on the head, and exactly what I'm doing/trying to do, e.g. 

`IPublishedContent parent = umHelper.Content(dbUpdateNote.PolicyId);

 var test1 = parent.Children();
 var test2 = parent.Children.Where(x => x.IsPublished());`
 
 Both test1 and test2 return the unpublished child

**Comment by V414** [comment]
My issue is that this doesn't happen in the trashed event I have - and surely its not expected behaviour? 

If I was making the check in the Unpublishing event I'd understand, but this is in the Unpublished event- so I thought all the cache's etc would have been updated before running my code?

**Comment by nul800sebastiaan** [comment]
You'd expect so.. not sure. I know cache updates are async so possibly the umbracoHelper doesn't know *yet* that the item is gone. Could you throw a `Thread.Sleep` for 5 seconds in there to see if it then works?

**Comment by V414** [comment]
`Thread.Sleep(10000);

IPublishedContent parent = umHelper.Content(dbUpdateNote.PolicyId);

Thread.Sleep(10000);

var test1 = parent.Children();
var test2 = parent.Children().Where(x => x.IsPublished());`
          
Still show's the child object in both test1 and test2... :(

**Comment by dawoe** [comment]
How do you create your umbracoHelper...If am I correct (probably not) this is a request based instance. So it might not have your changes.

Dave

**Comment by rasmusjp** [comment]
To ensure that caches are updated when subscribing to events you'll need to run your code when the scope is completed, see https://github.com/umbraco/Umbraco-CMS/issues/7485#issuecomment-576939899 for more info

**Comment by V414** [comment]
> How do you create your umbracoHelper...If am I correct (probably not) this is a request based instance. So it might not have your changes.
> 
> Dave

```
var umHelper = Umbraco.Web.Composing.Current.UmbracoHelper;
IPublishedContent rawParentPolicy = null;

using (var scope = _scopeProvider.CreateScope(autoComplete: true)) {
IUmbracoDatabase db = scope.Database;

GW_UpdateTextNotesSchema dbUpdateNote = db.FirstOrDefault<GW_UpdateTextNotesSchema>("where UmbracoId = '" + rawNote.Id + "'");
if (dbUpdateNote != null)
{
  rawParentPolicy = umHelper.Content(dbUpdateNote.PolicyId);

  db.Delete(dbUpdateNote);
  Debug.WriteLine("Note removed from DB");
}

//Some other stuff
scope.Complete();
}
```

**Comment by V414** [comment]
> To ensure that caches are updated when subscribing to events you'll need to run your code when the scope is completed, see [#7485 (comment)](https://github.com/umbraco/Umbraco-CMS/issues/7485#issuecomment-576939899) for more info

@rasmusjp I've just tested the idea that the scope's are the issue - but no luck (I didn't think they would be, because its my own database I'm editing with them, nothing to do with umbraco)

```
var umHelper = Umbraco.Web.Composing.Current.UmbracoHelper;
IPublishedContent rawParentPolicy = null;
int parentid = 0;

using (var scope = _scopeProvider.CreateScope(autoComplete: true))
{
IUmbracoDatabase db = scope.Database;

GW_UpdateTextNotesSchema dbUpdateNote = db.FirstOrDefault<GW_UpdateTextNotesSchema>("where UmbracoId = '" + rawNote.Id + "'");
if (dbUpdateNote != null)
{
parentid = dbUpdateNote.PolicyId;

db.Delete(dbUpdateNote);
Debug.WriteLine("Note removed from DB");
}

//Always complete the scope
scope.Complete();
}

rawParentPolicy = umHelper.Content(parentid);

var test1 = rawParentPolicy.Children();
var test2 = rawParentPolicy.Children().Where(x => x.IsPublished());
      
//I've moved the other logic down here into a different scope that starts after these tests
```

test1 and test2 still show the unpublished child.

**Comment by V414** [comment]
I'll also just add again that my code works with the Trashed event - I use the very same method (so same scope, creation of umbracoHelper etc) it lists the children correctly. (it seems to be specific to ContentService.Unpublished)

**Comment by rasmusjp** [comment]
But your code is still in the `ContentService.Unpublished`? I'm fairly certain you need to inject `IScopeProvider` into your class and add the method to be ran after the caches have been updated by calling `_scopeProvider.Context.Enlist("SomeUniqueName", scopeCompleted => OnScopeCompleted(scopeCompleted));`, and then create a `OnScopeCompleted(bool scopeCompleted)` method an add you code there. You might also want to inject the `IPublishedSnapshotService` and access the cache through that, something like this
```csharp
using (var snapshot = publishedSnapshotService.CreatePublishedSnapshot(null)) {
  var children = snapshot.Content.GetById(id).Children()
}
```

// note it's pseudo code and have not been tested

**Comment by V414** [comment]
Yup, the code is running within the Unpublished method (so I guess Umbraco has a scope open itself?) - I'll give the _scopeProvider.Context / Snapshot thing a try now... 

In the meantime, any idea why my code works with the Trashed event but not this one?

**Comment by rasmusjp** [comment]
Yes, Umbraco wraps everything in it's own scope so that's not finished when you run your code inside the events, I know in the link I posted it was mentioning CacheRefreshers, but it applies for all Events

I'm not sure why it works for the Trashed event, but every time I need to access the published cache in an event I always do `_scopeProvider.Context.Enlist` to ensure the scope Umbraco opened has been closed

Also note you might want to check if the scope was completed or rolled back before running you code

```csharp
// Do not continue if the scope did not complete - the transaction may have been canceled and rolled back
if (!scopeCompleted) return;
```

**Comment by V414** [comment]
@rasmusjp that's fixed it!

Where I was adding in the method I instead replaced it with:

_scopeProvider.Context.Enlist("UnpublishingTest", scopeCompleted => OnScopeCompleted(rawContent, scopeCompleted));

I then created a small method (as instructed), to run it once it had finished (and a check in case it hadn't):

```
private static void OnScopeCompleted(IContent rawContent, bool scopeCompleted)
    {
      if (scopeCompleted)
      {
        DB_DeletionLogic.DeleteNoteFromDatabase(rawContent);
      }
    }
```

And the original method is now showing the correct children (e.g. its excluding the unpublished one)!

To get it working with my own db code I created a fresh IScopeProvider to run in my method (which I didn't realise was possible before):

`IScopeProvider _scopeProvider = Umbraco.Web.Composing.Current.ScopeProvider;`

Which works as expected.

**Comment by emma-hq** [comment]
Hey @V414 

I'm with you on this. Whilst the behaviour might be less than intuitive, given the discussion here, it is safe to say it is not a bug. It's better for us to take a look at the docs and work there to ensure that the behaviour is explained and expected. 

Thanks to all for the input!

Emma
