### ISSUE TITLE
V9: Keys not serialized into package.xml for content type folders and tabs

### ISSUE THREAD

**Issue by AndyButland** [umbraco/Umbraco-CMS#11170]
### Which *exact* Umbraco version are you using? For example: 8.13.1 - don't just write v8

Latest v9/dev

### Bug summary

Similar to the issue fixed with [this PR](https://github.com/umbraco/Umbraco-CMS/pull/11163), we really need Guid keys serialized for all Umbraco schema data that might be created from a package migration.

For most we have - but for those without it presents an issue for Umbraco Deploy in that the `.uda` files generated in a local environment when the package is installed will differ from the keys used in schema created by the package migration running in an upstream environment.

What's still missing are:

- Content type folders (serialized only with the name currently on a child document type - e.g. `<DocumentType Folders="Compositions">`.

### Steps to reproduce

- Install package containing the features noted in a local environment
- Push updated .csproj file to an upstream environment using Umbraco Deploy
- Attempt to transfer content

### Expected result / actual result

Should be able to transfer content but currently get schema mismatch errors.

**Comment by bergmania** [comment]
Folder keys are in a PR here: #11172
