### ISSUE TITLE
Member groups stopped working

### ISSUE THREAD

**Issue by AaronSadlerUK** [umbraco/Umbraco-CMS#11189]
### Which *exact* Umbraco version are you using? For example: 8.13.1 - don't just write v8

v9-rc004

### Bug summary

When a node is restricted to a member group and the member is in that group, it redirects to the login page.

### Steps to reproduce

Create a member
Assign member to a group
Restrict public access to a node to the group
Try to access the node with the member

### Expected result / actual result

The member should be able to access the node once logged in

---
_This item has been added to our backlog [AB#14115](https://dev.azure.com/umbraco/243e7927-03b2-44e2-908f-d4ac7ea5daaa/_workitems/edit/14115)_

**Comment by AaronSadlerUK** [comment]
Just to add, the sign-in method used is:

```
var member = await _memberManager.FindByEmailAsync(model.Username);
await _memberSignInManager.SignInAsync(member, false); 
```

Found in:

```
private readonly IMemberManager _memberManager;
private readonly IMemberSignInManager _memberSignInManager;
```

**Comment by nul800sebastiaan** [comment]
This isn't working for me either using the partial view macro snippets. When I log in I can see that I'm definitely logged in but going to the protected area kicks me back to the login page. 

![image](https://user-images.githubusercontent.com/304656/134694654-10a2d528-75b3-4dca-bc13-1ba193d05ccc.png)

I've made sure to check that the member is in the correct role, should have worked.

**Comment by nul800sebastiaan** [comment]
I think we're getting the "wrong" `HttpContext` here somehow. Seems related to https://github.com/umbraco/Umbraco-CMS/pull/11155

![image](https://user-images.githubusercontent.com/304656/134707201-39da9070-35a1-4568-b136-186a94aafd56.png)
![image](https://user-images.githubusercontent.com/304656/134707218-f719a3ec-dc3c-4133-97d1-849221b3f99f.png)
