### ISSUE TITLE
Security concern

### ISSUE THREAD

**Issue by zidingz** [umbraco/Umbraco-CMS#11182]
Hey there!

I belong to an open source security research community, and a member (@vikychoi) has found an issue, but doesn’t know the best way to disclose it.

If not a hassle, might you kindly add a `SECURITY.md` file with an email, or another contact method? GitHub [recommends](https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository) this best practice to ensure security issues are responsibly disclosed, and it would serve as a simple instruction for security researchers in the future.

Thank you for your consideration, and I look forward to hearing from you!

(cc @huntr-helper)

**Comment by nul800sebastiaan** [comment]
Yes will do at some point 👍 

For now, when you create a new issue, we link to where you should report security issues:

![image](https://user-images.githubusercontent.com/304656/134527458-b5bc6922-6606-41f5-bce0-f9089c6618bc.png)

Which links you to: https://umbraco.com/about-us/trust-center/security-and-umbraco/how-to-report-a-vulnerability-in-umbraco/
