### ISSUE TITLE
Missing JSON Schema Property for Smidge Version

### ISSUE THREAD

**Issue by warrenbuckley** [umbraco/Umbraco-CMS#11188]
### Which *exact* Umbraco version are you using? For example: 8.13.1 - don't just write v8

9.0.0RC004

### Bug summary

The JSON schema that is automatically generated for Umbraco does not contain the setting used if you wish to use a Version value for Smidge/Runtime Minification

`public const string ConfigRuntimeMinificationVersion = ConfigRuntimeMinification + ":Version";`

As this is not set in the C# Options model it does not get serialised as JSON Schema.

### Steps to reproduce

Try using the JSON schema and you will see that we don't have a property for Version inside `Umbraco:CMS:RuntimeMinification`

**Comment by bergmania** [comment]
PR: https://github.com/umbraco/Umbraco-CMS/pull/11268
