### ISSUE TITLE
V9: Many (13) references to settings in web.config in en.xml (and translated equivalents)

### ISSUE THREAD

**Issue by p-m-j** [umbraco/Umbraco-CMS#11191]
### Which *exact* Umbraco version are you using? For example: 8.13.1 - don't just write v8

v9/dev

### Bug summary

> Debug mode is turned on by setting <b>debug="true"</b> on the <b>&lt;compilation /&gt;</b> element in web.config.
> Database not found! Please check that the information in the "connection string" of the "web.config" file is correct.

These need updating and presumably removing for the time being in the translation files.

### Steps to reproduce

Open src/Umbraco.Web.UI/umbraco/config/lang/en.xml and search for web.config

**Comment by p-m-j** [comment]
Help getting these up-to-date across all languages would be most appreciated!

**Comment by imrishabh18** [comment]
@p-m-j I would like to take this issue up. Can you guide me with what are things that I should work on?

**Comment by nul800sebastiaan** [comment]
@imrishabh18 so whenever the web.config is referred to, change that to the equivalent config in v9's appsettings. https://our.umbraco.com/documentation/Reference/V9-Config/GlobalSettings/

**Comment by p-m-j** [comment]
@nul800sebastiaan not sure this issue should be closed, there're a lot of other languages that need updating.

Might be worth removing all the updated entries from the other languages so they are accurate but in english only.
