### ISSUE TITLE
v8: `IEmailSender` not registered in DI container

### ISSUE THREAD

**Issue by mattbrailsford** [umbraco/Umbraco-CMS#11206]
### Which *exact* Umbraco version are you using? For example: 8.13.1 - don't just write v8

Umbraco v8.17.0-rc2

### Bug summary

Umbraco has a `IEmailSender` for helping sending emails, but this isn't registered in the DI container like it is in v9. It currently requires use of a hard coded EmailSender class.

### Steps to reproduce

Accept an `IEmailSender` constructor dependency.
Run application
Get error because it's not registered in container

### Expected result / actual result

`IEmailSender` should be registered with the DI container and should successfully resolve as a constructor arg.

**Comment by nul800sebastiaan** [comment]
I made a bit of a mess but with some help from @p-m-j I got there in the end! Thanks for the report @mattbrailsford! 👍

**Comment by nul800sebastiaan** [comment]
Fixed in https://github.com/umbraco/Umbraco-CMS/issues/11206 for 8.17.0.

**Comment by p-m-j** [comment]
Don't think you made a mess at all @nul800sebastiaan, the static helpers for services were the idiomatic way to work in umbraco for so long and I don't think there would have been a problem with adding one as long as the service was registered in the container.

**Comment by nul800sebastiaan** [comment]
Ah I was just referring to the mess with multiple PRs and forgetting to revert stuff. The final commit is nice and clean!
