### ISSUE TITLE
Block list single item mode inserts empty block when cancelling

### ISSUE THREAD

**Issue by sebastiandammark** [umbraco/Umbraco-CMS#11218]
### Which *exact* Umbraco version are you using? For example: 8.13.1 - don't just write v8

Umbraco version 8.16.0

### Bug summary

When inserting a new item in Single Item Mode and cancelling, the block list contains an empty element.

### Steps to reproduce

1. Create a Block List property in Single Item Mode
2. Insert a new block item
3. Hit escape

Now you have an empty Block List Item in your Block List

### Expected result / actual result

I would expect the empty item to be removed

**Comment by nathanwoulfe** [comment]
This is fixed by #11353 👍
