### ISSUE TITLE
V9: Inserting partial via template doesn't use await

### ISSUE THREAD

**Issue by bjarnef** [umbraco/Umbraco-CMS#11220]
### Which *exact* Umbraco version are you using? For example: 8.13.1 - don't just write v8

9.0.0

### Bug summary

When inserting a partial view via template editor in backoffice it just use the following like in v8:

```
@Html.Partial("Breadcrumb")
```

It should instead use the recommended approach in .NET5:

```
@(await Html.PartialAsync("Breadcrumb"))
```

### Steps to reproduce

Insert a partial via backoffice template editor and notice it render the partial like in v8, but not `async`.

**Comment by louisjrdev** [comment]
So I was potentially going to make this change looks simplish based on needing to change the snippet that is created in this [file](https://github.com/umbraco/Umbraco-CMS/blob/5bfab13dc5a268714aad2426a2b68ab5561a6407/src/Umbraco.Web.UI.Client/src/common/services/templatehelper.service.js).

However, how is the multi targeting of V8 and V9 working in the js if at all?

**Comment by bjarnef** [comment]
@louisjrdev the V8 and V9 code base is in two separate branches. `v9/contrib` is now the default branch. So you could eventually fork this and submit a PR target on this branch.
https://github.com/umbraco/Umbraco-CMS/blob/v9/contrib/src/Umbraco.Web.UI.Client/src/common/services/templatehelper.service.js

**Comment by louisjrdev** [comment]
@bjarnef Aha nice, I thought that was  the case but just wanted to check. 

Great I will probably get a PR in for this soon, but if anyone else wants to work on it in the meantime feel free.

**Comment by bjarnef** [comment]
Microsoft also mention in the docs here:
https://docs.microsoft.com/en-us/aspnet/core/mvc/views/partial?view=aspnetcore-5.0#synchronous-html-helper

> Partial and RenderPartial are the synchronous equivalents of PartialAsync and RenderPartialAsync, respectively. The synchronous equivalents aren't recommended because there are scenarios in which they deadlock. The synchronous methods are targeted for removal in a future release.

So maybe in .NET6 or later it is removed completely anyway.
