### ISSUE TITLE
Modelsbuilder schema is missing Enabled

### ISSUE THREAD

**Issue by patrickdemooij9** [umbraco/Umbraco-CMS#11232]
### Which *exact* Umbraco version are you using? For example: 8.13.1 - don't just write v8

v9

### Bug summary

We currently have the appsettings-schema.json for the Modelsbuilder to make options easier to find. If I check the schema against the documentation here: https://our.umbraco.com/documentation/reference/templating/modelsbuilder/configuration, I can see that the Enable is missing.

### Steps to reproduce

Try typing Enable in the Modelsbuilder section within appsettings.json. You'll see that there is no autocomplete for it.

### Expected result / actual result

Enable should be an autocomplete option within the appsettings.json. If the Enable doesn't actually exist in code, then the documentation should be updated.

**Comment by bergmania** [comment]
Thanks.. The documentation is wrong. Enabled is removed, instead there ModelsMode can be Nothing. Ill update docs

**Comment by patrickdemooij9** [comment]
Thanks for the quick response @bergmania!
