### ISSUE TITLE
Settings model not working in Block List Editor

### ISSUE THREAD

**Issue by bjornnorlen** [umbraco/Umbraco-CMS#11236]
### Which *exact* Umbraco version are you using? For example: 8.13.1 - don't just write v8

Umbraco 9.0.0

### Bug summary

Adding a settings model to a content block makes the element crash on the front-end. The settings model has it own unique property aliases but when trying to get them in the code I can only get the properties of the content model.

### Specifics

I've created two element types, one which has the content and one which has the settings. I've then created a blocklist datatype and added the content element as an available block. Then I added the settings element as a settings model to the block. The blocklist datatype is then added to a document type with a template which renders all the blocks. In the content-section I can add values in the settings-section for the element. However, I can't use the properties in the settings model, it has the values of the content model. Heading and PreHeading is part of the content model, not settings:

![image](https://user-images.githubusercontent.com/19406378/135628351-8a81d146-49fe-4186-9263-616f05e8df14.png)

On the front-end I get an error:

![image](https://user-images.githubusercontent.com/19406378/135628513-6b65b366-70bc-49ee-abfb-d7cbf11614dd.png)

I´m using modelsbuilder and have made sure to rebuild the models in the backoffice and the the properties in the two element types has their own distinct aliases. If I remove the settings template it renders the content without problem.

### Steps to reproduce

- Create two element types with their own distinct properties
- Create a blocklist datatype which takes on of the elements as a content template and then add the other one as a settings template. 
- Create a document type with template and add the blocklist datatype. 
- Render the blocklist datatype in the template.
- Add a partial view in the location which is specified in the rendering for the document type template and then render the element code.

### Expected result / actual result

I expect that the settings model has it's own properties and not the same as the content model.

**Comment by ronaldbarendse** [comment]
@bjornnorlen You're casting both `Model.Content` and `Model.Settings` to the same element type (`ElementChangemaker`), but as you can see from the exception, the settings model is a different element type (`BackgroundAndBorder`).

You can remove the explicit casting by using the generic `BlockListItem<TContent, TSettings>`, like shown in https://github.com/umbraco/Umbraco-CMS/pull/8854#issuecomment-906421607.

In your example, the first line should be updated to:

```cshtml
@inherits Umbraco.Cms.Web.Common.Views.UmbracoViewPage<BlockListItem<ContentModels.ElementChangemaker, ContentModels.BackgroundAndBorder>>
```

Also make sure you're null-checking `Model.Settings` before using any properties on it, as it might be `null` if you already had block list items saved before adding the settings model or if you later change the settings model.

**Comment by bjornnorlen** [comment]
@ronaldbarendse Thank you for the quick reply, that did the trick. I was looking in the documentation for the block list editor, underneath "default rendering": https://our.umbraco.com/Documentation/Fundamentals/Backoffice/property-editors/built-in-property-editors/Block-List-Editor/

I didn't see that the content and settings variables used different types of contentmodels but it makes sense. Thanks again!
