### ISSUE TITLE
Error when accessing Membes section without Settings section: membertype/GetAllTypes

### ISSUE THREAD

**Issue by LennardF1989** [umbraco/Umbraco-CMS#11258]
### Which *exact* Umbraco version are you using? For example: 8.13.1 - don't just write v8

9.0.0

### Bug summary

If you login with a User that has no access to the Settings section, but does have access to the Members section, you will get the following error:

```
Authorization error: Unauthorized access to URL:
/umbraco/backoffice/umbracoapi/membertype/GetAllTypes
Contact your administrator for information.
```

### Steps to reproduce

1. Create a usergroup with access to Members, but not to Settings.
2. Create a user with the created usergroup
3. Login as the user
4. Go to the Members section, the error will show immediately.

### Expected result / actual result

No error is shown and/or the API should not be authorized for the Settings section permission only.

---
_This item has been added to our backlog [AB#14271](https://dev.azure.com/umbraco/243e7927-03b2-44e2-908f-d4ac7ea5daaa/_workitems/edit/14271)_

**Comment by nul800sebastiaan** [comment]
Interesting, I tried this in v8, but it seems to be only a v9 problem.

I can reproduce in v9: 


![image](https://user-images.githubusercontent.com/304656/135847413-9ebbc4a7-8835-436f-b37b-68f421a80c4e.png)

**Comment by bergmania** [comment]
PR: https://github.com/umbraco/Umbraco-CMS/pull/11264
