### ISSUE TITLE
Template is created when creating element type

### ISSUE THREAD

**Issue by bjarnef** [umbraco/Umbraco-CMS#11285]
### Which *exact* Umbraco version are you using? For example: 8.13.1 - don't just write v8

v8/contrib

### Bug summary

With latest changes in `v8/contrib` branch when I create an element type, it also create a template.

https://user-images.githubusercontent.com/2919859/136075770-16073bd1-d8f8-4b62-9ef7-f23864532410.mp4

### Steps to reproduce

Create an element type and note that a template also is created.
The only action that should create a template is the "Document Type with Template" action from the context menu.

**Comment by bjarnef** [comment]
It doesn't happen when creating a document type and switch the toggle at "Is an Element Type".

https://user-images.githubusercontent.com/2919859/136076625-7cd643fc-45d0-4506-bc03-98ce681e54a3.mp4

**Comment by bjarnef** [comment]
The `/umbraco/backoffice/UmbracoApi/ContentType/PostSave` set the following payload:

![image](https://user-images.githubusercontent.com/2919859/136077443-6d105e87-600c-4c35-8503-904874e2744e.png)

Not sure why it set template value, when this is an element type. What has changed? 🤔

**Comment by bjarnef** [comment]
I just tried on a v9.0.0 project, where it doesn't happen.

@nul800sebastiaan do you have a clue on what has changed here? 😬

**Comment by bjarnef** [comment]
Ahh it seems it also is related to https://github.com/umbraco/Umbraco-CMS/pull/11008

The `createElement()` function has changed to not set `notemplate` param, so it creates a template.

**Comment by BarryFogarty** [comment]
NB I have just created #11300 which sounds like it also relates to this issue, I will add a comment there too.
