### ISSUE TITLE
[v9] Creating a Composition in the backoffice does not set it to be an Element Type

### ISSUE THREAD

**Issue by BarryFogarty** [umbraco/Umbraco-CMS#11300]
### Which *exact* Umbraco version are you using? For example: 8.13.1 - don't just write v8

9.0.0

### Bug summary

When creating a Composition in the backoffice, the 'Is an Element Type' toggle is not set.  Therefore, the newly created composition is not avaialbe for selection (greyed out) in the Compositions list on other document types.

### Steps to reproduce

Using the context menu option, create a new Composition in the backoffice
Note that the 'Is an Element Type' toggle is not set to True the permissions tab

**Comment by bjarnef** [comment]
Creating a composition shouldn't set/enable "Is an Element Type" property. A composition is just a document type and until used on other document types it is basically just a regular document type.
A composition is not an element type.

**Comment by BarryFogarty** [comment]
Hmm ok, I thought that but tested it by switching off the element type flag, and it became grey out in my target document type.  But I have tried this on another, and it doesn't affect it like that, so there must have been another reason why I could not add it when it was not an Element Type.  Thanks for the clarification anyway, I'll see if I can work out another reason for this behaviour.

**Comment by nul800sebastiaan** [comment]
I'll close this for now as we don't have any unexpected behavior here that we know of 😃
