### ISSUE TITLE
v9 IPublishedContentQueryAccessor isn't usable

### ISSUE THREAD

**Issue by p-m-j** [umbraco/Umbraco-CMS#11319]
### Which *exact* Umbraco version are you using? For example: 8.13.1 - don't just write v8

9.0.0

### Bug summary

`IPublishedContentQueryAccessor` is registered with singleton lifetime and takes a dependency on `IServiceProvider`.
`IPublishedContentQuery` is registered with scoped lifetime.

When `PublishedContentQueryAccessor` is instantiated the root service provider is injected.
When `TryGetValue` is called the accessor attempts to resolve the scoped service from the root service provider and throws.

### Steps to reproduce

```csharp
public class DemoComposer : IComposer
{
    public void Compose(IUmbracoBuilder builder) => builder.Components().Append<DemoComponent>();
}

public class DemoComponent : IComponent
{
    public DemoComponent(IPublishedContentQueryAccessor queryAccessor)
    {
        // Throws cannot resolve scoped service 'Umbraco.Cms.Core.IPublishedContentQuery' from root provider.
        _ = queryAccessor.TryGetValue(out IPublishedContentQuery query);
    }

    public void Initialize() { }

    public void Terminate() { }
}
```

**Comment by p-m-j** [comment]
Workaround for short term

```csharp
public class WorkaroundComponent : IComponent
{
    public WorkaroundComponent(IServiceProvider serviceProvider, IUmbracoContextFactory contextFactory)
    {
        contextFactory.EnsureUmbracoContext();

        using (IServiceScope scope = serviceProvider.CreateScope())
        {
            // Doesn't throw.
            IPublishedContentQuery query = scope.ServiceProvider.GetRequiredService<IPublishedContentQuery>();
        }
    }

    public void Initialize() { }

    public void Terminate() { }
}
```

**Comment by hifi-phil** [comment]
That is a shame, the existing IPublishedContentQueryAccessor definitely didn't work for me when I used it, as you said, maybe I needed to use it in a using scope but that isn't obvious. 

So the question I would ask is, is the IPublishedContentQueryAccessor even valid where it is unless it's used internally?
