### ISSUE TITLE
Focal point is displaced in some browsers

### ISSUE THREAD

**Issue by greystate** [umbraco/Umbraco-CMS#11339]
### Which *exact* Umbraco version are you using? For example: 8.13.1 - don't just write v8

**9.0.0**

(Also seen in versions `8.15.2` and `8.16.0` (both on Umbraco Cloud), as well as a clean `v8.17.0`

### Bug summary

In Safari 15 on macOS, the focal point is positioned wrong in the Image Cropper.

### Specifics

This bug is due to missing support for the CSS property `contain`, as used in `property-editors.less`:

https://github.com/umbraco/Umbraco-CMS/blob/e7da8558e55fe297e7156691a79a87df2d211ea4/src/Umbraco.Web.UI.Client/src/less/property-editors.less#L609

Effectively, the focal point is positioned within a displaced "window" as visualized here:

![focalpoint-displaced](https://user-images.githubusercontent.com/5463/136661729-ac1ea6f8-5e68-4c06-b3f1-b7eb5202854b.jpg)

This also has the unfortunate side-effect of the **Remove file(s)** link being unclickable as it's covered by an invisible layer.

In Safari's *Develop* menu (which needs to be enabled in *Preferences*) it is possible to enable an experimental feature called **CSS Containment**, which fixes the problem; albeit only for that single browser :)

Firefox 92 (and other chromium browsers, presumably) does not exhibit the problem.

### Steps to reproduce

Using Safari on a Mac, in a clean install of Umbraco 9.0.0, go to the Media section and upload an image. Observe that the focal point is not positioned in the center of the image, as expected.

Also, when clicking in the image to position the focal point, observe that the focal point is positioned a little below and to the left of the point clicked.

### Expected result / actual result

The focal point should be positioned in the center of the image, but is actually positioned a little below and to the left.

**Comment by nathanwoulfe** [comment]
This is indeed fixed in #11340
