### ISSUE TITLE
Blocklist cancel not really cancelling

### ISSUE THREAD

**Issue by patrickdemooij9** [umbraco/Umbraco-CMS#11343]
### Which *exact* Umbraco version are you using? For example: 8.13.1 - don't just write v8

v9 (but probably 8 too)

### Bug summary

The cancel functionality of the blocklist is different from the other list like pickers (link picker for example).
When you cancel with the blocklist editor, it'll still generate a new item for you and add it to the list. While if you do the same with the link picker, it'll not generate an item for you.
![CancelNotCancel](https://user-images.githubusercontent.com/11466511/136689766-153ad900-44e5-4796-b09b-d7b8f6e5e9c1.gif)

### Steps to reproduce

- Create document type with a blocklist attached.
- Create a new page
- Add a new item
- Click cancel
- Your item is still created.

### Expected result / actual result

When I cancel on the creation of the item, I would expect it to not create the item at all. Keep the functionality the same as the other list pickers.

**Comment by daxter44** [comment]
Workflow after button click looks like : 
1. Add new item 
2. Check that item is created 
3. if second point is success open new item edit window. 

So if we would to fix Your issue workflow after button click shuld look like this : 

1. Create new item but not show it on layout  ( only in memory) 
2. Open edit window on hid'ed item
3. Delete item when cancel 
4. show item in layout if saved  

Right ? 
Can You hint me any another place where it works like You want ? i try to follow like there .

**Comment by nathanwoulfe** [comment]
Fixed in #11353, thanks @patrickdemooij9
