### ISSUE TITLE
Missing Italian translation breaking reset password email

### ISSUE THREAD

**Issue by Prev-I** [umbraco/Umbraco-CMS#11345]
### Which *exact* Umbraco version are you using? For example: 8.13.1 - don't just write v8

8.16

### Bug summary

I've founded those keys are missing, thus preventing the correct usage of the recover password feature:

```
    <key alias="setPasswordInstruction"></key>
    <key alias="setPasswordConfirmation"></key>
    <key alias="resetCodeExpired"></key>
    <key alias="resetPasswordEmailCopySubject"></key>
    <key alias="resetPasswordEmailCopyFormat"></key>
```

The resulting email only contains the resetPasswordEmailCopyFormat tag and no useful content.

### Steps to reproduce

Create an user with italian language
Request a password reset email (from the login form).
The resulting  email will have [resetPasswordEmailCopyFormat] as body instead of the correct text.

### Expected result / actual result

I expect to be able to reset password of Italian users

**Comment by nul800sebastiaan** [comment]
Oh, I've just realized that you mentioned v8 is your version and this PR was for v9, I'll see if it makes sense to cherry pick it to v8 as well.
