### ISSUE TITLE
Umbraco 9 tags input does not look ahead as you type a tag name (and exception is thrown)

### ISSUE THREAD

**Issue by argentini** [umbraco/Umbraco-CMS#11371]
### Which *exact* Umbraco version are you using? For example: 8.13.1 - don't just write v8

9.0.1

### Bug summary

Typing tags into a tag input behaves as though there are no existing tags on other pages. There is no lookup of existing tags that match what you are typing.

### Specifics

Typing tags into a tag input behaves as though there are no existing tags on other pages. There is no lookup of existing tags that match what you are typing. When a new tag is entered by pressing the RETURN key, Angular throws an exception:

<img width="501" alt="Screen Shot 2021-10-13 at 6 37 43 PM" src="https://user-images.githubusercontent.com/1504331/137222128-3fc003fe-dabe-4dd4-b7c3-feb783e7259f.png">

The tag does appear to be saved with the page, however.

### Steps to reproduce

Use the tags input on various pages in the CMS to see that look ahead is not working.

### Expected result / actual result

Tags should be recommended as you type, based on existing matches in the same tag group.

**Comment by emma-hq** [comment]
Hiya @argentini 

Thanks for reporting this and thanks for the screenshot. I'll take a look and recreate and shout here if I have any questions around reproduction. 

Emma
