### ISSUE TITLE
Smidge issue on publish

### ISSUE THREAD

**Issue by AaronSadlerUK** [umbraco/Umbraco-CMS#11374]
### Which *exact* Umbraco version are you using? For example: 8.13.1 - don't just write v8

9.0.1

### Bug summary

I have published the Umbraco V9 website using dot net publish, and then deployed to the server, I am getting the following errors in the log:

```
System.InvalidOperationException: Could not parse umbraco-backoffice-css.css as a valid smidge path
```

```
System.InvalidOperationException: Could not parse umbraco-backoffice-extensions-js.js as a valid smidge path
```

When I try to access the files directly, I just get a server error.

### Steps to reproduce

Publish the umbraco website in release mode
Run the published website
Access the backoffice

There will be a console error, and an entry in the log file

**Comment by hfloyd** [comment]
FYI - Forum conversation here: https://our.umbraco.com/forum/using-umbraco-and-getting-started/108469-backofficeadmin-css-smidgenuglify-error-breaking-package-styling

**Comment by hfloyd** [comment]
Related: 
https://github.com/umbraco/Umbraco.Cloud.Issues/issues/501
