### ISSUE TITLE
Draft translated content prevents other versions being indexed

### ISSUE THREAD

**Issue by smarshallsay** [umbraco/Umbraco-CMS#11383]
### Which *exact* Umbraco version are you using? For example: 8.13.1 - don't just write v8

9.0.1

### Bug summary

Having a draft version of a page in one language is preventing other versions being indexed.

### Steps to reproduce

Create a node with two language versions for instance US English and Polish. 
Save and publish the en-US version, leave the Polish one as a draft.
Search for the English version of page using the external indexer tool in the CMS, 0 results.
Save and publish the Polish version, 1 results.

### Expected result / actual result

Expected: Published version of  a page always indexed
Actual: Having any drafts 'unpublishes' all language versions from the index

**Comment by jonnymoo** [comment]
Hi all, I have a need for this to be fixed and I working on it. I've identified how it got introduced and I have a proposed solution to follow shortly.

**Comment by dawoe** [comment]
Hi @nul800sebastiaan 

I see there is a PR for this. Any chance this can get merged soon. I have applied the changes of this PR in my project and can confirm these solve the problem.

Dave
