### ISSUE TITLE
There is no TEMP environment variable on Linux azure app service

### ISSUE THREAD

**Issue by keithswright** [umbraco/Umbraco-CMS#11389]
### Which *exact* Umbraco version are you using? For example: 8.13.1 - don't just write v8

9.0.0

### Bug summary

When deploying to azure app service, the advice is to use "EnvironmentTemp" for LocalTempStorageLocation, so that a unique nucache path is created for each instance of the application

The logic to create the temp file paths uses an environment variable called "TEMP" which does not exist on linux app services and the UI of the portal does not allow you add an configuration setting called "TEMP".

### Specifics

The logic in question is in:

Umbraco.Cms.Web.Common.AspNetCore.AspNetCoreHostingEnvironment

            public string LocalTempPath
            {
            get
            {
                if (_localTempPath != null)
                {
                    return _localTempPath;
                }

                switch (_hostingSettings.CurrentValue.LocalTempStorageLocation)
                {
                    case LocalTempStorage.EnvironmentTemp:

                        // environment temp is unique, we need a folder per site

                        // use a hash
                        // combine site name and application id
                        // site name is a Guid on Cloud
                        // application id is eg /LM/W3SVC/123456/ROOT
                        // the combination is unique on one server
                        // and, if a site moves from worker A to B and then back to A...
                        // hopefully it gets a new Guid or new application id?
                        string hashString = SiteName + "::" + ApplicationId;
                        string hash = hashString.GenerateHash();
                        string siteTemp = Path.Combine(Environment.ExpandEnvironmentVariables("%temp%"), "UmbracoData", hash);

                        return _localTempPath = siteTemp;

                    default:

                        return _localTempPath = MapPathContentRoot(Cms.Core.Constants.SystemDirectories.TempData);
                }
            }
        }`

### Steps to reproduce

Deploy an umbraco site to a linux instance and set the configuration as per the documentation:

https://our.umbraco.com/Documentation/Fundamentals/Setup/Server-Setup/azure-web-apps

### Expected result / actual result

Expected:

Umbraco's local cache files are created in a temporary folder on a local disk with a unique file path

Actual:

The files are created, and with a unique file path, but in the following location:

/site/wwwroot/**%temp%**/UmbracoData/b4a25dca1fb0e8f6a554f275d23a88272c22e2b0/NuCache/

A side effect of this is, I believe that the /home/site/wwwroot folder is on a network drive and so reading and writing will be slower than a local disk.

**Comment by bergmania** [comment]
Hmm.. I guess `Environment.ExpandEnvironmentVariables("%temp%")` could just be replaced by `Path.GetTempPath()`
