### ISSUE TITLE
URL replacing doesn't work as expected

### ISSUE THREAD

**Issue by bjarnef** [umbraco/Umbraco-CMS#11381]
### Which *exact* Umbraco version are you using? For example: 8.13.1 - don't just write v8

9.0.1

### Bug summary

It seems the URL replacing in V9 doesn't work as expected and we know from e.g. V8.
It has been documented here: https://our.umbraco.com/documentation/Reference/V9-Config/RequestHandlerSettings/

Also see the following forum thread: https://our.umbraco.com/forum/umbraco-9/107221-urlreplacing-for-umbraco-9

I added the following the `appsettings.json` under `Umbraco > CMS` in the JSON. It actually shows intellisense for this in VS, which is nice 👍 

However after stopping application, rebuild and starting application again plus publishing a new, it doesn't seems to have any effect. I tried with  `appsettings.Development.json` as well, but the still no change.

```
"RequestHandler": {
        "ConvertUrlsToAscii": "try",
        "CharCollection": [
          {
            "Char": "ø",
            "Replacement": "o"
          }
        ]
      }
```

In this case I have a  search page "Søg" i Danish. I would expect the URL to change to `/sog` , but stll the default URL `/soeg`  which is default from here: https://github.com/umbraco/Umbraco-CMS/blob/5bfab13dc5a268714aad2426a2b68ab5561a6407/src/Umbraco.Core/Configuration/Models/RequestHandlerSettings.cs#L38

I guess this just not overwrite the default char collection somehow?

### Steps to reproduce

Replace characters in `appsettings.json` which is different from default char collection here: https://github.com/umbraco/Umbraco-CMS/blob/5bfab13dc5a268714aad2426a2b68ab5561a6407/src/Umbraco.Core/Configuration/Models/RequestHandlerSettings.cs#L20-L46

Find a node which the char, rename the node or create a new node and notice the char in the URL isn't replaced.

```
"RequestHandler": {
        "ConvertUrlsToAscii": "try",
        "CharCollection": [
          {
            "Char": "ø",
            "Replacement": "o"
          }
        ]
      }
```

However it does seem this example work:
https://our.umbraco.com/documentation/Reference/V9-Config/RequestHandlerSettings/#char-collection

```
{
  "Char": "ñ",
  "Replacement": "n"
}
```

Create a page "Somethiñg" and notice the URL is `/something`.

---
_This item has been added to our backlog [AB#15635](https://dev.azure.com/umbraco/243e7927-03b2-44e2-908f-d4ac7ea5daaa/_workitems/edit/15635)_

**Comment by matthewcare** [comment]
I suspect this TODO in `Umbraco.Cms.Core.Configuration.Models.RequestHandlerSettings` answers some questions.
```
// We need to special handle ":", as this character is special in keys

// TODO: implement from configuration

//// var collection = _configuration.GetSection(Prefix + "CharCollection").GetChildren()
////    .Select(x => new CharItem()
////    {
////        Char = x.GetValue<string>("Char"),
////        Replacement = x.GetValue<string>("Replacement"),
////    }).ToArray();

//// if (collection.Any() || _configuration.GetSection("Prefix").GetChildren().Any(x =>
////    x.Key.Equals("CharCollection", StringComparison.OrdinalIgnoreCase)))
//// {
////    return collection;
//// }

//// return DefaultCharCollection;

/// <summary>
/// Gets or sets a value for the default character collection for replacements.
/// </summary>
/// WB-TODO
public IEnumerable<IChar> CharCollection { get; set; } = DefaultCharCollection;
```

**Comment by matthewcare** [comment]
@bjarnef 
Turns out it didn't map anything at all that was defined in `appsettings.json`. Opened a PR for review :)

**Comment by bjarnef** [comment]
@matthewcare it does seem to work for chars not defined in default char collection though like this:

```
{
  "Char": "ñ",
  "Replacement": "n"
}
```

**Comment by nul800sebastiaan** [comment]
Fixed in https://github.com/umbraco/Umbraco-CMS/pull/11386

**Comment by thomashdk** [comment]
Hi

It's like all my char replacement are ignored in Umbraco 11.4.1 ?

I have tried by using the CharCollection and the UserDefinedCharCollection. Nothing helps.

It worked in 10.5.1, but after I updated it stopped ? Every replacement added are ignored ?
