### ISSUE TITLE
Missing azuregalleryrelease.ps1 build file

### ISSUE THREAD

**Issue by KPGDL** [umbraco/Umbraco-CMS#11419]
### Which *exact* Umbraco version are you using? For example: 8.13.1 - don't just write v8

8.17.0

### Bug summary

The build file `Umbraco-CMS/build/build.ps1` is referencing to the file that is not existing in the repository: `Umbraco-CMS/build/Azure/azuregalleryrelease.ps1`

PrepareAzureGallery, line 455 in `Umbraco-CMS/build/build.ps1` (V9/contrib)

![image](https://user-images.githubusercontent.com/92784527/137895534-0ccbf1c4-b47b-4dc9-a957-bcf858326e18.png)

### Steps to reproduce

Fork the repository, select V9/contrib, try to build with build.ps1 file in build directory.

**Comment by uppercuut** [comment]
This happened to me as well , 

but when I built it using visual studio after running the command it built successfully and worked normally

**Comment by elit0451** [comment]
Fixed in #11540
