### ISSUE TITLE
Media Multinodepicker not working after opening second time

### ISSUE THREAD

**Issue by patrickdemooij9** [umbraco/Umbraco-CMS#11424]
### Which *exact* Umbraco version are you using? For example: 8.13.1 - don't just write v8

Latest contrib on v9 & v8

### Bug summary

When using a multinode treepicker for media, you can only open it once. If you open it a second time, it'll not load anything.
![BugMultiNode](https://user-images.githubusercontent.com/11466511/137965824-ffbe0725-5d8c-4cb5-a90a-78eb14cb09cb.gif)

### Steps to reproduce

- Create a multinode treepicker datatype with Media and an allowed media type
- Add the datatype to a document type
- Create a page with given document type
- Open multinode treepicker
- Close it
- Open it again. It'll now not load anything

### Expected result / actual result

Should be able to load every time

**Comment by RasmusUmbraco** [comment]
Ibrahim has done a great job of fixing this on V9 👍 
The issue is still present on V8 if anyone would like to have a go at it 😊

**Comment by kjac** [comment]
This one does seem to have gone a bit stale. The picker works fine in V10+, so I will go ahead and close this issue now.

![11424](https://user-images.githubusercontent.com/7405322/212095135-1935dde7-8673-41c7-8ac2-db18755eb7ce.gif)
