### ISSUE TITLE
Performance: Don't load all translation files if they are not going to be used

### ISSUE THREAD

**Issue by patrickdemooij9** [umbraco/Umbraco-CMS#11438]
### Which *exact* Umbraco version are you using? For example: 8.13.1 - don't just write v8

v9

### Bug summary

Was playing around the memory viewer a bit to see what is currently using all the memory and I saw that the following fields: "XAttribute", "XElement" and "XText" had quite a high count on the memory viewer. Decided to look a bit further into it and apparently this is caused by the translations being loaded from the xml files. 
![image](https://user-images.githubusercontent.com/11466511/138229637-d3a482a1-64ea-402a-9d2e-f9374d905404.png)

However, for many websites we only really use one language. So having to keep 19 other languages in memory seems a bit unnecessary for me. Is there a reason that all the languages are kept in the memory instead of being loaded when they are actually used?

### Steps to reproduce

Run a v9 website and take a snapshot of the memory. Looking into the objects "XAttribute", "XElement", "XText" and "Dictionary<string, string>" will all show references to the translation logic.

### Expected result / actual result

Only load translations of languages that are actually used. Maybe load them when they are being used (though maybe this has a big performance hit) or allow us to exclude translation files so that we don't have to keep it in memory.

**Comment by elit0451** [comment]
Fixed in #11576
