### ISSUE TITLE
Weirdness when setting granular permissions for usergroups

### ISSUE THREAD

**Issue by LennardF1989** [umbraco/Umbraco-CMS#11458]
### Which *exact* Umbraco version are you using? For example: 8.13.1 - don't just write v8

v9.0.1

### Bug summary

I was setting an Umbraco instance for a client yesterday, and had to lock down some nodes. This was quite a struggle, because two things happened:
- If I misclicked the node and hit cancel, to unselect it the overlay opens again. If I then click the right node, it still shows the wrong node as the active node. Clicking submit then adds the wrong node to the granular permissions.
- Another way to go about permissions is to whitelist everything, and then blacklist everything you don't want someone to have access to. This works, but the granular permissions won't select the node unless at least one permissions is granted.

### Steps to reproduce

1. Make sure you have at least 2 nodes under Content.
2. Go to a User Group, eg. Administrators.
3. Go to granular permissions, click Add. 
4. Select the first node in the list. The overlay opens. Cancel it.
5. Select the first node in the list in attempt to uncheck it. The overlay opens. Cancel it. The checkbox is now gone.
6. Select the second node in the list. The overlay opens. Still shows the name of the first node. Submit it.
7. First node is now added to the granular permissions.
8. Remove the node and click Add.
9. Select the first node, uncheck all permissions and click submit.
10. Node is added to granular permissions with no permissions (as expected).
11. Save the usergroup, the node is now gone.

### Expected result / actual result

1. When I misclick the node, I expect to be able to uncheck it without it opening the overlay again. Or better, when I hit cancel, I expect the checkmark to not been shown at all. The selection never happened. The current behavior causes a situation where you can leave multiple checks if you don't uncheck.
2. When I selected the right node after misclicking the first time, I expect that one to be added to granular permissions.
3. When I remove all permissions from a node, I expect it to still be there after saving the page.

**Comment by elit0451** [comment]
Hi @LennardF1989 😊 
It took some time before you could hear from us but we have some great news 🎊 
The issues you mentioned should be entirely fixed (in #11577), so you will no longer need to do any workarounds for your use case.
