### ISSUE TITLE
Error During Examine Indexing

### ISSUE THREAD

**Issue by wicketbr** [umbraco/Umbraco-CMS#11487]
### Which *exact* Umbraco version are you using? For example: 8.13.1 - don't just write v8

9.0.1

### Bug summary

When the Examine Index is being rebuit and content larger that 32k is encountered, the following error is thrown:

Exception thrown: 'Lucene.Net.Util.BytesRefHash.MaxBytesLengthExceededException' in Lucene.Net.dll
Exception thrown: 'System.ArgumentException' in Lucene.Net.dll

It seems that there is no error catching happening around this indexing. So, when a single item can't be indexed the indexing stops being built. My only workaround at this time is to unpublish all of my large content pages, rebuild the indexes, then republish those pages.

### Steps to reproduce

To reproduce you simply need a content item that has an extremely large amount of HTML in it. It seems to be a problem with any content item over 32k in size. Then, in the BackOffice, go to Settings, Examine Management, ExternalIndex, and click Rebuild Index.

### Expected result / actual result

I would expect that if one content item cannot be indexed that it would just be skipped and the index would continue being built for the remaining pages.

---
_This item has been added to our backlog [AB#14878](https://dev.azure.com/umbraco/243e7927-03b2-44e2-908f-d4ac7ea5daaa/_workitems/edit/14878)_

**Comment by p-m-j** [comment]
Resolved in 9.1.0, thanks for the report!
