### ISSUE TITLE
User Picker filter is not working

### ISSUE THREAD

**Issue by tnielsenskybruddk** [umbraco/Umbraco-CMS#11520]
### Which *exact* Umbraco version are you using? For example: 8.13.1 - don't just write v8

8.17.0

### Bug summary

The filter function in the User Picker is not working. Nothing happens when I type in the textbox.

### Steps to reproduce

I have set up a new Umbraco 8.17.0.

I have added a User Picker as property editor on a documenttype. When editing a page of this documenttype, I open the User Picker.

It works and shows all users. But if I try to filter nothing happens. I can see the list updates, but the text is not passed along with the request (postFilter).
![userpicker_filter](https://user-images.githubusercontent.com/3634628/138957304-5d262b00-8be1-42a9-b642-b842b62ac3a0.png)

### Expected result / actual result

I expected the User Picker list to become shorter with only the items which contains the text I have typed in the textbox.

**Comment by nikcio** [comment]
@mikecp This should've been fixed with #11605. Might be time to close this one.

**Comment by nul800sebastiaan** [comment]
Thanks for the reminder @nikcio - indeed this is now fixed in 8.18, I'll close this one!
