### ISSUE TITLE
Fix link localization in EnsureInternalLinks

### ISSUE THREAD

**Issue by glombek** [umbraco/Umbraco-CMS#11525]
### Which *exact* Umbraco version are you using? For example: 8.13.1 - don't just write v8

8 Unknown (January 2021)

### Bug summary

"URL Provider caches resolved fragments, resulting in localized URLs not returning expected."

Issue based on PR #9624 which was closed as the implementation was not ideal and was left untouched from February.

It seems the issue was with the `HtmlLocalLinkParser.EnsureInternalLinks` method was ignoring the current culture and returning any link already cached.

The solution should not get the culture from the CurrentCulture, but use the content variant. I also wonder if this would be possible to fix within the UrlProvider itself rather than this singular use case.

### Steps to reproduce

(Steps to reproduce are untested.)

Link to internal content in an RTE property.

Render the page with this property in culture A so the cache is populated.

Render the same page in culture B and links will point to pages in culture A.

**Comment by glombek** [comment]
Cannot replicate in v9. I suggest we close this unless the original reporter provides more detail. (cc @emma-hq)

**Comment by emma-hq** [comment]
Sounds like a plan 😁  Thanks Joe!
