### ISSUE TITLE
Routing issue with UmbracoAuthorizedApiController, UmbracoAuthorizedJsonController etc

### ISSUE THREAD

**Issue by enkelmedia** [umbraco/Umbraco-CMS#11523]
### Which *exact* Umbraco version are you using? For example: 8.13.1 - don't just write v8

9.0.1

### Bug summary

I'm creating a controller for a backoffice-plugin and try to use the default route to pass an id to my controller. I can get the controller to "answer" on the right route but the id-parameter is always empty.

It looks like something with the route-registration might be wrong for these controllers or I'm missing something.

### Specifics

I've tried both UmbracoAuthorizedApiController and UmbracoAuthorizedJsonController  and also with and wihout the "PluginController"-attribute on the controller-class.

### Steps to reproduce

My controller looks like this:

```csharp
[PluginController("Obviuse")]
public class SiteBackofficeController : UmbracoAuthorizedApiController 
{
    [HttpGet]
    public object GetDashboardOverview(int id)
    {
        return Ok(new
        {
            id = id, 
            message="Nice"
        });
    }
}
```

When I call this controller from my js-code passing in /122 for the id-parameter, the controller action is hit but the id-parameter is 0 (default for int).

```javascript
$http.get('/umbraco/backoffice/Obviuse/SiteBackoffice/GetDashboardOverview/123').then((e) => {
    console.log(e.data);
});
```

If I change the call to an explicit querystring id things works just fine.

```javascript
$http.get('/umbraco/backoffice/Obviuse/SiteBackoffice/GetDashboardOverview?id=123').then((e) => {
    console.log(e.data);
});
```

### Expected result / actual result

The routing should work and set the id-parameter when calling the controller with /123

**Comment by elit0451** [comment]
Fixed in #11557
