### ISSUE TITLE
Media picker with 'accepted types' shows all media

### ISSUE THREAD

**Issue by Ambertvu** [umbraco/Umbraco-CMS#11563]
### Which *exact* Umbraco version are you using? For example: 8.13.1 - don't just write v8

9.0.1

### Bug summary

When using the Media picker with an accepted type and trying to select an image, there is no visible distinction in what is allowed to be selected or not.

You currently only see an disallowed icon when hovering over an image.

### Steps to reproduce

- Create a media picker with an accepted type (example, SVG)

- Upload a normal jpg
- Upload a SVG

- Use the media picker with an accepted type to select an image. 
![image](https://user-images.githubusercontent.com/13347420/139837292-2bdaa433-8cda-4c52-bec2-844e34ce019a.png)
Left is JPG, right is SVG, both look clickable.

### Expected result / actual result

I'd expect it to only shows items of that type in the view where you select the image, or have a clear distinction in what's selectable and what's not. (grayed out)

**Comment by uppercuut** [comment]
Hello, i have tested it on 
contrib/v9 
it was working fine

**Comment by Ambertvu** [comment]
> Hello, i have tested it on contrib/v9 it was working fine

I've also just now tested it on a fresh install (Umbraco 9.1 instead of 9.0.1.) and its the same. There is no visual distinction between a svg and an image. You only see not-allowed icon when hovering over an item.
