### ISSUE TITLE
Submenu navigation is not working

### ISSUE THREAD

**Issue by ttaylor29** [umbraco/Umbraco-CMS#11581]
### Which *exact* Umbraco version are you using? For example: 9.0.1 - don't just write v9

8.1.4

### Bug summary

I am trying to make a Content page have sub pages underneath.  That is all working, but after I set Text Only In Navigation' to true, it is never showing the underneath items:

![image](https://user-images.githubusercontent.com/23564255/140458062-583ebfbe-e065-4beb-81e3-522def86488d.png)

What could be the issue? I didn't change anything navigation setup. 

### Specifics

Top1
     Top1.1
     Top1.2

So It won't let me go to Top1, but a menu is not showing for Top1.1 and Top1.2

### Steps to reproduce

Publish out Content page and sub pages, then go to the website and the Top1 page does not show up for menu sub menu

### Expected result / actual result

To be able to go to the submenu pages on Top1.1 and Top1.2

**Comment by ttaylor29** [comment]
Seems like the items are there, so I guess CSS is blocking it:

![image](https://user-images.githubusercontent.com/23564255/140460665-ac00402b-c924-44fc-a9d8-50468d1eec3a.png)

**Comment by nul800sebastiaan** [comment]
Hi there - this sounds like an excellent question for the forums where our friendly community can help you find the best solution for your requirements. 

Make sure to head on over to https://our.umbraco.com and ask follow up questions there! 👍
