### ISSUE TITLE
Create Member Groups & Properties Programatically in umbraco 8

### ISSUE THREAD

**Issue by ssplyuvrajsingh** [umbraco/Umbraco-CMS#11595]
Umbraco version - : 8.17.0

### Bug summary

Is it possible to create a member group and member group properties programmatically?

I have the need to create a specific Member Group programmatically and then add specific properties to it, this is for a package I'm creating.

### Steps to reproduce

![image_2021_11_08T11_00_15_251Z](https://user-images.githubusercontent.com/58556669/140735173-8a2353bb-e84b-4814-999f-cc11c05f2cd9.png)

**Comment by nul800sebastiaan** [comment]
Hi there - this sounds like an excellent question for the forums where our friendly community can help you find the best solution for your requirements. 

Make sure to head on over to https://our.umbraco.com and ask follow up questions there! 👍
