### ISSUE TITLE
Block list editor content and settings model properties 

### ISSUE THREAD

**Issue by AndyButland** [umbraco/Umbraco-CMS#11598]
### Which *exact* Umbraco version are you using? For example: 9.0.1 - don't just write v9

8.17.0

### Bug summary

With block list editors, we can have both a "content" and "settings" model that the editor can populate.  Whilst presented differently, they aren't particularly different in terms of setup - both are element types and can use the full range of property editors.

When examining the data actually stored - i.e. in `umbracoPropertyData` table - there are differences.  See an example in [this PR](https://github.com/umbraco/Umbraco.Deploy.Contrib/pull/50) with how media picker values are stored.

This issue looks to stem from the methods `ToEditor` and `FromEditor` in `BlockEditorPropertyEditor` only operating on the "content" data, and not the "settings" one.  By omitting these it can cause issues such as [this](https://github.com/umbraco/Umbraco.Deploy.Issues/issues/86), where the expected data isn't stored and hence serialized and deserialized correctly in deploy operations.  And we could have situations where for certain property editors incorrect values are being stored, as we aren't transforming the data between the back-office and the stored data 

### Steps to reproduce

- Create two element types, each with a media picker on it.
- Configure a block list data type that uses the two elements types as the "content" and "settings" model.
- Use this data type on a document type.
- Create a content item based on the document type and populate the media picker on both "content" and "settings"
- Observe the data stored in `umbracoPropertyData` and how the stored value for the media item on "content" and "settings" differs (the former as a serialized string, the latter as a JToken).

### Expected result / actual result

Storage and handling of properties on "content" and "settings" models should be the same.

---
_This item has been added to our backlog [AB#14994](https://dev.azure.com/umbraco/243e7927-03b2-44e2-908f-d4ac7ea5daaa/_workitems/edit/14994)_

**Comment by nikolajlauridsen** [comment]
Fixed in #11722
