### ISSUE TITLE
Blocklist custom view not rendered on MacOS

### ISSUE THREAD

**Issue by gerwim** [umbraco/Umbraco-CMS#11596]
### Which *exact* Umbraco version are you using? For example: 9.0.1 - don't just write v9

9.0.1

### Bug summary

We have a blocklist with a custom view, which is not rendering on MacOS (I have not tested Linux, it might have the same issue).

### Specifics

I've checked it on:

### Server (MacOS)
❌ Firefox (MacOS)
❌ Firefox (Windows)

### Server (Windows)
✅ Firefox (MacOS)
✅ Firefox (Windows)

### Steps to reproduce

1. Create a document type which has a block list as component
2. Create a custom view for the component
3. Select the custom view for the component in Umbraco, e.g.:
![image](https://user-images.githubusercontent.com/1841721/140741671-02434a88-ac95-4c21-87a3-44ad97cd5816.png)
4. Add the page as content
5. Add content to the blocklist

You'll have the following result:
### ✅ Windows
![image](https://user-images.githubusercontent.com/1841721/140742142-9b1f8329-78f1-4863-b053-3bd748e145f2.png)

### ❌ MacOS
![image](https://user-images.githubusercontent.com/1841721/140742322-f108eebb-ab2f-413b-886c-7f8806d07730.png)

### Expected result / actual result

Custom view should be rendered on MacOS.

**Comment by nul800sebastiaan** [comment]
Check your console in your browser on MacOS? It is probably looking for a filename with different casing, the filesystem on mac is case sensitive so there's probably some kind of mismatch.

**Comment by gerwim** [comment]
@nul800sebastiaan: there's no error in the console.

It would also be weird it's a casing issue, as the field is not an free form input type. You actually have to select the file:
<img width="559" alt="image" src="https://user-images.githubusercontent.com/1841721/140785344-65055ef1-7308-4993-a0fc-47f4f1052706.png">

**Comment by nul800sebastiaan** [comment]
Is there an error in the network tab of your browser then? Errors in the logs? :-)

**Comment by nul800sebastiaan** [comment]
I just gave it a go on Linux and I can't reproduce the problem. A custom view with mixed-cased filenames does indeed work. 

However, I just noticed your folder is called `grid` - are you sure the items in there are supposed to work with the block list editor? I guess since it works in Windows, the answer is yes. 

There's some more documentation on https://our.umbraco.com/Documentation/Fundamentals/Backoffice/property-editors/built-in-property-editors/Block-List-Editor/#build-a-custom-backoffice-view

I would love to hear more on how to reproduce, maybe if you post your `singleColumnRow.html` I could try it out on Linux and see if I can see anything else that might be wrong.

**Comment by gerwim** [comment]
@nul800sebastiaan Thanks for your feedback and investigation.

> I would love to hear more on how to reproduce

I will try to create a minimalist repro and push it to a github project later this week.

**Comment by gerwim** [comment]
@nul800sebastiaan I have created a new project on 9.0.1 and can not reproduce this. I will close this issue and reopen it if I know what is actually causing it to have a proper repro. Thank you for looking into this!

**Comment by nul800sebastiaan** [comment]
@gerwim strange! But thanks for letting us know!

**Comment by gerwim** [comment]
@nul800sebastiaan Well today we figured it out. We're using Umbraco Cloud and we're using Deploy. On both the development and staging environment the blocklist actually rendered properly (as seen above). But, on the live environment it was broken (just like my MacOS screenshot). However, it was not caused by the hosting environment, but rather an index issue.

In our custom view we had (notice index 0 on the tabs):
```
 <div ng-repeat="property in block.content.variants[0].tabs[0].properties"
```
For some reason, most of the time the data is actually in the first index, but not always. So the code has been refactored to work with data being in different indexes.

I'm sorry for the confusion caused. 😅
