### ISSUE TITLE
after upgrading from 8.7 to 8.17 the backoffice is corupted

### ISSUE THREAD

**Issue by m-ali-unosoft** [umbraco/Umbraco-CMS#11611]
### Which *exact* Umbraco version are you using? For example: 9.0.1 - don't just write v9

8.17

### Bug summary

after upgrading from 8.7 to 8.17 the backoffice is corupted
![umb-bo](https://user-images.githubusercontent.com/59240060/141394323-d14dbbe0-d98b-40d2-ba23-0736b794b057.png)

### Steps to reproduce

![umb-bo](https://user-images.githubusercontent.com/59240060/141394361-87b7b09b-3dc6-4818-bb91-d626728ecdf3.png)

**Comment by nul800sebastiaan** [comment]
Make sure to bump the version in `ClientDependency.config` and try again. If that doesn't help, not all of the files will have been copied correctly to the `/umbraco` folder, should be solved by deleting the folder and doing a build, should copy the correct files in. 

If you keep having problems, make sure to head to the forums where our friendly community can help you find the best solution for your requirements. 

Make sure to head on over to https://our.umbraco.com and ask follow up questions there! 👍
