### ISSUE TITLE
MNTP with maximum of zero doesn't mean unlimited

### ISSUE THREAD

**Issue by bjarnef** [umbraco/Umbraco-CMS#11633]
### Which *exact* Umbraco version are you using? For example: 9.0.1 - don't just write v9

9.1.0

### Bug summary

I notitced the following with latest changes in `v9/contrib` branch and the default starter kit installed.

With a MNTP datatype configurated through infinite editing and a maximum of zero this used to mean unlimited. However I am note sure if this has changed from v8 to v9?

![image](https://user-images.githubusercontent.com/2919859/141695843-c965c597-a0a5-4299-b98f-30cb6f683625.png)

![image](https://user-images.githubusercontent.com/2919859/141695922-c12cd643-acc9-4318-9485-fe9451394da0.png)

### Steps to reproduce

Add a property using a datatype based on MNTP property editor though infinite editing, which by default set minimum and maximum to 0.

Go to content and select a few nodes in the MNTP property and hit Save & Publish.
Note that validation error is shown.

![image](https://user-images.githubusercontent.com/2919859/141696051-8a799972-d95e-4ae0-85b7-47f62f8f0ea5.png)

**Comment by bjarnef** [comment]
It seems there changes were recently made in `contentpicker` property editor used for both Content Picker and MNTP:
https://github.com/umbraco/Umbraco-CMS/pull/11330

**Comment by bjarnef** [comment]
Currently behavior based on Umbraco v9.0.1

![image](https://user-images.githubusercontent.com/2919859/141800895-241ade1e-2f06-4250-9428-c5cd8a3606c9.png)

**Comment by bjarnef** [comment]
@nul800sebastiaan @nathanwoulfe can you reproduce this issue?

**Comment by richarth** [comment]
I've just run into this with 9.1.0-rc.  I set up a MNTP without a min and max value so there could be an unlimited number selected, but the MNTP has been saved with a min and max of 0.

This causes an issue when I select an item as the system thinks only 0 items can be selected.

**Comment by daniel-shuy** [comment]
Created #11639 to fix it

**Comment by nathanwoulfe** [comment]
This is fixed in #11639, which I've just merged into v8/contrib, will need to be merged up and included in 9.1
