### ISSUE TITLE
MTNP throws Newtonsoft.Json.JsonSerializationException when selecting node

### ISSUE THREAD

**Issue by bjarnef** [umbraco/Umbraco-CMS#11647]
### Which *exact* Umbraco version are you using? For example: 9.0.1 - don't just write v9

9.0.1

### Bug summary

I started noticed these Newtonsoft.Json.JsonSerializationException exceptions when selecting nodes from MTNP.
I don't recall it originally was an issue when I started the project on v9.0.0, but it seems these are showing up in v9.0.1 (not sure if it could be related to Umbraco Forms or Deploy as these has also been patch updates on Umbraco Cloud).

https://user-images.githubusercontent.com/2919859/142163354-614d0448-d753-4d90-a3be-372c2d531d1c.mp4

It may be related to this issue https://github.com/umbraco/Umbraco-CMS/issues/11448 where I also from time to time get these exception when fetching previous selected content in MNTP.

### Steps to reproduce

Configurate a MNTP on v9.0.1 and select a node.
A Newtonsoft.Json.JsonSerializationException exception is thrown.

---
_This item has been added to our backlog [AB#15132](https://dev.azure.com/umbraco/243e7927-03b2-44e2-908f-d4ac7ea5daaa/_workitems/edit/15132)_

**Comment by bergmania** [comment]
Hi @bjarnef.. We added the task in next sprint (startning monday) so we can look into this issue.

**Comment by bjarnef** [comment]
@bergmania Umbraco Cloud patch updated  `Umbraco.Deploy.Cloud` from v9.0.0 to v9.0.1 which seems to have broken stuff.

![image](https://user-images.githubusercontent.com/2919859/142669889-e57ea505-eeb6-4901-921d-ed0762ad5ec2.png)

Locally I just reverted back to  `Umbraco.Deploy.Cloud` v9.0.0, rebuild the project and now part of the MNTP picker started working again - at lease get convert `ids[0] as GuidUdi` part didn't fail, so the previous selected nodes are initialized and selecting new nodes are added to list.

![image](https://user-images.githubusercontent.com/2919859/142670067-27982a4c-87e5-40bf-a7a1-776173a83e87.png)

![image](https://user-images.githubusercontent.com/2919859/142670212-152d0b79-2587-4868-85eb-7888c148b949.png)

**Comment by bjarnef** [comment]
I reverted `Umbraco.Deploy.Forms` to v9.0.0 and this exception is gone as well.

I wonder what was changes in these versions?

![image](https://user-images.githubusercontent.com/2919859/142671557-65a77543-2a72-4434-b2c8-a630a3a22694.png)

**Comment by AndyButland** [comment]
Just to update here - and sorry for the delay, I missed the notification - I've just double-checked the changes for Deploy between 9.0.0 and 9.0.1 in Deploy and I can't see anything that could be related here.

I've also tested with the latest bundle available on Cloud and am not able to replicate when following the steps in the raised issue.

**Comment by bjarnef** [comment]
It seems this has been fixed in 9.1.2 so I'll close this issue.
