### ISSUE TITLE
Umbraco 9.0.1 on .net 6 fails to properly process PNG images when cropping

### ISSUE THREAD

**Issue by maartenmensink** [umbraco/Umbraco-CMS#11655]
### Which *exact* Umbraco version are you using? For example: 9.0.1 - don't just write v9

9.0.1

### Bug summary

Umbraco/ImageSharp fails to process PNG images when cropped. A incorrect image is returned. 

### Specifics

localhost:44373/media/2jgleq4v/test.png?width=396&height=273&rnd=132630541505230000

### Steps to reproduce

1. Create fresh umbraco project 9.0.1
2. Update to .net 6
3. Upload png image
4. Go to info open image in new tab
5. Add crop params.

### Expected result / actual result

A properly processed image

**Comment by bergmania** [comment]
Seems to be related to this. https://github.com/umbraco/Umbraco-CMS/pull/11306

Did you test on 9.1?

**Comment by maartenmensink** [comment]
@bergmania i will retest today.

**Comment by bergmania** [comment]
As far as I can see it works as expected in 9.1, Ill close for now, but if you still have issues feel free to reopen the issue :)

**Comment by maartenmensink** [comment]
Retested 9.1 on .net 6 works as expected

**Comment by bergmania** [comment]
> Retested 9.1 on .net 6 works as expected

Thanks for testing it out 💪
