### ISSUE TITLE
Breaking changes in the UmbracoAuthorizedApiController.cs 

### ISSUE THREAD

**Issue by luis-cortina** [umbraco/Umbraco-CMS#11663]
### Which *exact* Umbraco version are you using? For example: 9.0.1 - don't just write v9

9.0.1

### Bug summary

We created custom backoffice extensions (tree, some custom data views). We needed this screens and the api calls (controllers)  that they generated to be only available to back office users and we inherited from the UmbracoAuthorizedApiController.cs. When we migrated from Rc3 to v9.0.1 our api calls started to break and is due the the following change:

https://github.com/umbraco/Umbraco-CMS/commit/ef73e181f1d8d88b3e95ee57b34e0ec59185e25c#diff-b91b6a370d39a736a5f0df950945b7689c0fa6f5cd68bf9fc23cea417dba0411

There is a JSON Formatter (AngularJsonMediaTypeFormatter) that adds this string to every Json result `")]}',\n";`.

Is this change intended? Seems like a very disruptive breaking change.

### Steps to reproduce

Broken JSON Picture
![image](https://user-images.githubusercontent.com/25346332/142507292-047f1d80-81b0-4988-9196-47e164124361.png)

### Expected result / actual result

UmbracoAuthorizedApiController.cs should behave as before this change.

**Comment by bergmania** [comment]
This change is actrually indended, because the `UmbracoAuthorizedApiController` is intented to be used for backoffice request. This `")]}',\n"` prefix should be handled by AngularJS. How are you using the API since AngularJS are not handling /removing the prefix?

**Comment by p-m-j** [comment]
Further reading https://github.com/umbraco/Umbraco-CMS/discussions/11186

**Comment by luis-cortina** [comment]
Hi @bergmania:
I'm using the angular $http service to make calls to the back office api. Given @p-m-j comment and issue I would say this should have been considered/advertised as a breaking change. 

My workaround so I don't have to change my angular code is I created a Base Controller that uses the Backoffice Access Authorization Policy and protects the api from unauthorized access. I have to try a bit more with angular xsrf tokens but this work for now.

```
   [Authorize(Policy = AuthorizationPolicies.BackOfficeAccess)]
    public class BackOfficeController : Controller
    {
        
    }

```

Any suggestions besides this?

Luis

**Comment by p-m-j** [comment]
Angular.js $http definitely should strip the cruft https://docs.angularjs.org/api/ng/service/$http#security-considerations

**Comment by luis-cortina** [comment]
$http did the trick. All my calls were not using it.

**Comment by IanIsFluent** [comment]
Adding this cruft on purpose in 2021 is insane IMO. 🤷 

'As a quick fix it was suggested that developers should use the previously mentioned unparsable cruft to make ensure browsers refused to evaluate the response whilst adding to Ajax handling code to strip the characters for legitimate uses.'

**Comment by huzzi** [comment]
Hi @luis-cortina just wondering how you've used $http to fix the issue? Thanks
