### ISSUE TITLE
UserPWD Reset CallbackUrl -Current.RuntimeState.ApplicationUrl - gets the first binding in iis (alphabetically) and not anything to do with umbraco domains

### ISSUE THREAD

**Issue by mistyn8** [umbraco/Umbraco-CMS#11668]
### Which *exact* Umbraco version are you using? For example: 9.0.1 - don't just write v9

8.15.1

### Bug summary

The backoffice user reset pwd email generated callback URLs, seem to bear no relation to the current browser shown domain, or hostname/cultures set in the backoffice.

We have a setup where multiple bindings are added to iis, and then a canonical urlrewrite ensures only one primary domain is in use for the site.

However, each time we add a new is binding (that takes the top binding alphabetically), the callback URL in the resetpwd email changes to be that domain, and not the canonical domain (and only domain that the frontend/backend of our umbraco site is accessible by)

I think this is down to 
https://github.com/umbraco/Umbraco-CMS/blob/a86baa4798fbdf902361bc5c32c6eab56d845b1d/src/Umbraco.Web/Editors/AuthenticationController.cs#L556

Although we are on 8.15.1, github shows this code is still present in the v8/dev and v8/contrib branches.

### Steps to reproduce

Set up umbraco site, add multiple bindings in iis.
Generate a reset user pwd email from the frontend on any of these domains, and the email URL callback takes the first binding on iis alphabetically..

### Expected result / actual result

reset pwd should match the current browser url domain shown.

**Comment by mistyn8** [comment]
Stumbled on.. https://our.umbraco.com/documentation/Reference/V9-Config/umbracoSettings/#umbracoapplicationurl

Should that be used/need to  be used to correct this issue?

**Comment by enz1n0** [comment]
Hi,
do you have some news?  I have same problem with 8.14 notifications, I think this is the code which create the problems:
SendNotification(user, entities, action, **_runtimeState.ApplicationUrl**);

**Comment by kjac** [comment]
Hi @mistyn8,

Thank you for reahing out. Sorry for the very late response 😞 

You are spot on though - if you [configure the application URL](https://docs.umbraco.com/umbraco-cms/reference/configuration/webroutingsettings#umbraco-application-url) explicitly, that URL will always be used for various tasks including sending emails. If none is defined, Umbraco will assume that the first requested URL is the application URL.

A few more details can be found here: https://docs.umbraco.com/umbraco-cms/extending/health-check/guides/fixedapplicationurl

**Comment by mistyn8** [comment]
Do I have it correct though in a loadbalanced environment that the `umbracoapplicationurl` needs to be the url that the server can talk to itself.. 

So pwd reset emails would go out with internal domains stamped and not the public one?

**Comment by kjac** [comment]
@mistyn8 I reckon you would be correct, if the server cannot reach itself on its publicly facing URL.

One could argue the need for being able to specify email URLs explicitly - per email type, per language, per ... context? This however would be something to put in a GitHub discussion as a feature request 😄
