### ISSUE TITLE
v9: `LocalTempStorageLocation` setting not respected

### ISSUE THREAD

**Issue by rickbutterfield** [umbraco/Umbraco-CMS#11678]
### Which *exact* Umbraco version are you using? For example: 9.0.1 - don't just write v9

9.1.0

### Bug summary

Following the [configuration instructions for Azure Web Apps](https://our.umbraco.com/Documentation/Fundamentals/Setup/Server-Setup/azure-web-apps), should Examine folders should be stored in a local temp folder rather than with the website files?

### Specifics

`appsettings.json`:
```json
"Hosting": {
    "LocalTempStorageLocation": "EnvironmentTemp"
},
"Examine": {
    "LuceneDirectoryFactory": "SyncedTempFileSystemDirectoryFactory"
}
```

The Examine dashboard shows the path I would have expected them to be stored:

![image](https://user-images.githubusercontent.com/200450/142869165-f907cf69-cb88-480e-85ac-72bf843a3d7a.png)

However they are still stored within `wwwroot\Umbraco\Data\TEMP` on an Azure App Service:

![image](https://user-images.githubusercontent.com/200450/142869351-ee6edb4b-4685-4ce6-89d9-1e505e16e9b4.png)

The folder listed as `LuceneIndexFolder` doesn't exist:

![image](https://user-images.githubusercontent.com/200450/142870020-455bdfde-edd8-4fa9-83ca-dcd65e7f885c.png)

### Steps to reproduce

- Follow the [Azure Web App instructions](https://our.umbraco.com/Documentation/Fundamentals/Setup/Server-Setup/azure-web-apps)
- Deploy the site to an Azure Web App
- Look for the `wwwroot\Umbraco\Data\TEMP` folder 
- Look for the folder listed in the Examine dashboard

### Expected result / actual result

Expected:
Examine files would be stored in the path defined by `LocalTempStorageLocation`

Actual:
Examine files are stored in `wwwroot\Umbraco\Data\TEMP` regardless of this setting

**Comment by bielu** [comment]
@rickbutterfield that is actually respected, SyncedTempFileSystemDirectoryFactory means they are stored in both Temp directory and Data directory.
Also worth to mention, you can't see temp folder from Kudu as that is separate process with separate temp folder :)
please check 
https://stackoverflow.com/questions/52013428/is-is-possible-to-browse-an-azure-app-service-temp-directory

**Comment by rickbutterfield** [comment]
@bielu That's a new one for me! Thanks for the info
