### ISSUE TITLE
URL paths not correct on some file systems

### ISSUE THREAD

**Issue by marklonquist** [umbraco/Umbraco-CMS#11670]
### Which *exact* Umbraco version are you using? For example: 9.0.1 - don't just write v9

9.1.0

### Bug summary

Some URLs for different (static) files have upper case letters in them even though the files are all lowercased. This breaks on some file systems (especially some linux file systems) as they are case sensitive.

Eg the url for assign domain: `umbraco/views/content/assignDomain.html?umb__rnd=b5776ac5577bc027dc9252227b40facf2b60846c`

but the filename is "assigndomain.html" so it results in a 404 for this file.

### Steps to reproduce

Run on a case-sensitive file system and go to "Culture and hostnames". It can potentially happen with other files as well. 

### Expected result / actual result

Gives a 404 but should show the appropriate html

---
_This item has been added to our backlog [AB#15627](https://dev.azure.com/umbraco/243e7927-03b2-44e2-908f-d4ac7ea5daaa/_workitems/edit/15627)_

**Comment by nikolajlauridsen** [comment]
Thanks for the report 🐛 
 
The assigndomain casing issue has been fixed in #11784, so I'll go ahead and close this issue, but please do not hesitate to create another issue if you find other files with the same issue 👍
