### ISSUE TITLE
Naming a Block List property "navigation" breaks CSS

### ISSUE THREAD

**Issue by LennardF1989** [umbraco/Umbraco-CMS#11688]
### Which *exact* Umbraco version are you using? For example: 9.0.1 - don't just write v9

9.1.1

### Bug summary

If you add a property "navigation" to a contentype and add a blocklist to that. That alias will be set as the id-attribute on the "Add ..."-button, which in turn breaks the styling.

https://github.com/umbraco/Umbraco-CMS/blob/5bfab13dc5a268714aad2426a2b68ab5561a6407/src/Umbraco.Web.UI.Client/src/views/propertyeditors/blocklist/umb-block-list-property-editor.html#L31

![image](https://user-images.githubusercontent.com/869973/143062786-597799bc-eca5-417d-8d3e-774469242bd3.png)

![image](https://user-images.githubusercontent.com/869973/143062876-1ab001b5-f461-43de-b5fd-c2679e29b647.png)

### Steps to reproduce

1. Create a doctype and add a property with the alias "navigation" to it.
2. Set the datatype to a block list.
3. Create a node with the doctype from step 1, the blocklist styling will look broken.

### Expected result / actual result

I would prefix the ID with something. Personally, I'd also say "id" is the wrong attribute if you go by HTML conventions. ID is supposed to be guaranteed unique, this is not the case because an user could choose an alias that is also used by something else on the page. A "class" attribute would be better suited.

---
_This item has been added to our backlog [AB#25564](https://dev.azure.com/umbraco/243e7927-03b2-44e2-908f-d4ac7ea5daaa/_workitems/edit/25564)_

**Comment by patrickdemooij9** [comment]
Is also still an issue in v8. I did create a PR for this some time ago: https://github.com/umbraco/Umbraco-CMS/pull/9882

**Comment by aguyfromdenmark** [comment]
Still a problem in 10.1.0.

**Comment by Digipex** [comment]
Issue still happens in 11.0.0

**Comment by kjac** [comment]
Hi @LennardF1989,

Thank you for reporting this 💪 and sorry for the late response on our side.

I can confirm this on V10+ and this also applies to Media Picker 3. 

I have created a PR to fix it: https://github.com/umbraco/Umbraco-CMS/pull/13663

**Comment by kjac** [comment]
Closed in https://github.com/umbraco/Umbraco-CMS/pull/13663
