### ISSUE TITLE
Temporarily able to log in with old member email for roughly 5 minutes

### ISSUE THREAD

**Issue by VasylKyrtyanyk** [umbraco/Umbraco-CMS#11689]
### Which *exact* Umbraco version are you using? For example: 9.0.1 - don't just write v9

Umbraco 8.15.2

### Bug summary

When we change a member's email in a code they are logged out and their account is deactivated until they confirm their new email, however, we have the bug that they are temporarily able to log in with their old email for roughly 5 minutes. I have tried clearing the member index but that did not work. If anyone has any suggestions on what to do I would appreciate it.

### Steps to reproduce

1. change email in code
2. logged out 
3. Try to log in with old email

### Expected result / actual result

expected result: you can't log in with an old email
actual result: you successfully logged in

**Comment by p-m-j** [comment]
When you say change user email, which field is being updated?

```csharp
    public class DemoComponent : IComponent
    {
        private readonly IScopeProvider _scopeProvider;
        private readonly IUserService _userService;

        public DemoComponent(IScopeProvider scopeProvider, IUserService userService)
        {
            _scopeProvider = scopeProvider;
            _userService = userService;
        }

        public void Initialize()
        {
            using (_scopeProvider.CreateScope(autoComplete: true))
            {
                var user = _userService.GetUserById(-1);
                user.Username = "foo@example.com";
                user.Email = "bar@example.com";
                _userService.Save(user);
            }
        }

        public void Terminate()
        {
        }
    }
```

If I run this I can only login with the username "foo@example.com" (database field [dbo].[umbracoUser].[userLogin])

**Comment by VasylKyrtyanyk** [comment]
> When you say change user email, which field is being updated?
> 
> ```cs
>     public class DemoComponent : IComponent
>     {
>         private readonly IScopeProvider _scopeProvider;
>         private readonly IUserService _userService;
> 
>         public DemoComponent(IScopeProvider scopeProvider, IUserService userService)
>         {
>             _scopeProvider = scopeProvider;
>             _userService = userService;
>         }
> 
>         public void Initialize()
>         {
>             using (_scopeProvider.CreateScope(autoComplete: true))
>             {
>                 var user = _userService.GetUserById(-1);
>                 user.Username = "foo@example.com";
>                 user.Email = "bar@example.com";
>                 _userService.Save(user);
>             }
>         }
> 
>         public void Terminate()
>         {
>         }
>     }
> ```
> 
> If I run this I can only login with the username "[foo@example.com](mailto:foo@example.com)" (database field [dbo].[umbracoUser].[userLogin])

I mean about memberService and 
`                member.Email = model.Email;
                member.Username = model.Email;
                                member.IsApproved = false;
                                Members.Logout();
                _memberService.Save(member);`

**Comment by p-m-j** [comment]
You very clearly mentioned members as opposed to users, apologies.

**Comment by kjac** [comment]
This has also been reported in https://github.com/umbraco/Umbraco-CMS/issues/11786 - said issue has a little more to go on and is marked as up for grabs, so I'll close this one as duplicate (although technically #11786 is the duplicate).
