### ISSUE TITLE
[V9.1.1] Missing tabs in the Document Type Editor

### ISSUE THREAD

**Issue by AaronSadlerUK** [umbraco/Umbraco-CMS#11690]
### Which *exact* Umbraco version are you using? For example: 9.0.1 - don't just write v9

9.1.1

### Bug summary

Some  of my tabs are not showing in the Document Type Editor, they are visible in the Content Editor, and they are in the uSync export config file too.

There are no errors in the console log, and looking via the inspector the tabs do not seem to be hidden in the code.

I am unable to try and re-add the missing property editors, as when I save they say the alias is already used, this makes me think it must be a UI issue.

![image](https://user-images.githubusercontent.com/9937803/143207913-4f8ceea6-af4d-4304-aafb-c00976309990.png)

![image](https://user-images.githubusercontent.com/9937803/143208014-9eed4e0c-3e8c-44bb-ab5d-c965def7a687.png)

### Steps to reproduce

At this point I'm not sure, happy to work with an Umbraco Dev with my site as a playground to debug

### Expected result / actual result

All tabs shown in the content editor to be shown in the Document Type editor

**Comment by bielu** [comment]
@AaronSadlerUK check if your tab doesnt have same name as group under, then it will be not rendered -> not sure if it is by design or bug :)

**Comment by AaronSadlerUK** [comment]
@bielu I'm not seeing the group name at all in the Content Editor, so at this point I'm not sure.

![image](https://user-images.githubusercontent.com/9937803/143217476-645bffa5-ce7a-49c1-bea5-34883e3b110e.png)

![image](https://user-images.githubusercontent.com/9937803/143217491-7ee6853d-5678-4c85-997c-85e5c369920a.png)

**Comment by AaronSadlerUK** [comment]
This is what I have in the uSync export for the Main Navigation tab:

```
    <GenericProperty>
      <Key>ecb625b6-cf6e-4563-be6e-3545fb7b77cd</Key>
      <Name>Client Dashboard</Name>
      <Alias>clientDashboard</Alias>
      <Definition>369511b3-44b1-4415-89a6-f9264aaa54da</Definition>
      <Type>Umbraco.MultiUrlPicker</Type>
      <Mandatory>false</Mandatory>
      <Validation></Validation>
      <Description><![CDATA[]]></Description>
      <SortOrder>2</SortOrder>
      <Tab Alias="navigation/mainNavigation">Main Navigation</Tab>
      <Variations>Nothing</Variations>
      <MandatoryMessage></MandatoryMessage>
      <ValidationRegExpMessage></ValidationRegExpMessage>
      <LabelOnTop>false</LabelOnTop>
    </GenericProperty>
    <GenericProperty>
      <Key>c01a40f9-2aa7-437f-bb11-09b503014677</Key>
      <Name>Main Navigation</Name>
      <Alias>mainNavigation</Alias>
      <Definition>0a0f9e28-6fbc-4239-956c-b7617f492b06</Definition>
      <Type>AaronSadler.UmbNav</Type>
      <Mandatory>false</Mandatory>
      <Validation></Validation>
      <Description><![CDATA[]]></Description>
      <SortOrder>0</SortOrder>
      <Tab Alias="navigation/mainNavigation">Main Navigation</Tab>
      <Variations>Nothing</Variations>
      <MandatoryMessage></MandatoryMessage>
      <ValidationRegExpMessage></ValidationRegExpMessage>
      <LabelOnTop>false</LabelOnTop>
    </GenericProperty>
    <GenericProperty>
      <Key>ddf91be7-2ae1-4cd0-bc8a-15d9b592cd35</Key>
      <Name>CTA Button</Name>
      <Alias>mainNavigationCtaButton</Alias>
      <Definition>369511b3-44b1-4415-89a6-f9264aaa54da</Definition>
      <Type>Umbraco.MultiUrlPicker</Type>
      <Mandatory>false</Mandatory>
      <Validation></Validation>
      <Description><![CDATA[]]></Description>
      <SortOrder>1</SortOrder>
      <Tab Alias="navigation/mainNavigation">Main Navigation</Tab>
      <Variations>Nothing</Variations>
      <MandatoryMessage></MandatoryMessage>
      <ValidationRegExpMessage></ValidationRegExpMessage>
      <LabelOnTop>false</LabelOnTop>
    </GenericProperty>
```

```
    <Tab>
      <Key>c11a8a3a-8c97-456b-b0ad-1532c9207083</Key>
      <Caption>Main Navigation</Caption>
      <Alias>navigation/mainNavigation</Alias>
      <Type>Tab</Type>
      <SortOrder>1</SortOrder>
    </Tab>
```

**Comment by ronaldbarendse** [comment]
@AaronSadlerUK It's not showing in the designer, because you can't have a tab (Main Navigation) nested inside of another tab (Navigation):

> ```
> <Alias>navigation/mainNavigation</Alias>
> <Type>Tab</Type>

To ensure editors can still access all properties, the content section will display any groups/tabs that are incorrectly configured (like unsupported nesting, missing parent, etc.). Because you can't create nested tabs within the backoffice UI, my best guess is that this somehow got updated, e.g. by deploying content types using uSync. If you do find a (reproducible) way to end up in this situation, please let us know of course 😉

I recommend manually editing the exported uSync to make it a `<Type>Group</Type>` and do an import (and ensure other content types that are compositions/inherited have the same type).
