### ISSUE TITLE
Unable to get context in controller implementing IVirtualPageController

### ISSUE THREAD

**Issue by aguyfromdenmark** [umbraco/Umbraco-CMS#11692]
### Which *exact* Umbraco version are you using? For example: 9.0.1 - don't just write v9

9.0.1

### Bug summary

[Umbraco documentation here
](https://our.umbraco.com/documentation/reference/routing/custom-routes)

When implementing the `FindContent` method that is required when implementing `IVirtualPageController`, trying to get the Umbraco Context will fail.

I will post my implementation below.

### Steps to reproduce

Create a controller implementing `IVirtualPageController`.

In the `FindContent` method, try getting the Umbraco Context:

` if (_umbracoContextAccessor.TryGetUmbracoContext(out IUmbracoContext context))
            {
                //Removed for brevity
            }`

Register the relevant routes for the controller you created.

Try calling the route you defined. The `FindContent` method will be hit. `.TryGetUmbracoContext()` will return false. 

### Expected result / actual result

It is expected that `.TryGetUmbracoContext(out var context)` returns true and outs a valid instance of `IUmbracoContext`.

**Comment by aguyfromdenmark** [comment]
Controller:
```
public class SitemapController : UmbracoPageController, IVirtualPageController
{
    private readonly IUmbracoContextAccessor _umbracoContextAccessor;

    public SitemapController(ILogger<SitemapController> logger, ICompositeViewEngine compositeViewEngine, IUmbracoContextAccessor umbracoContextAccessor) : base(logger, compositeViewEngine)
    {
        _umbracoContextAccessor = umbracoContextAccessor;
    }

    public IPublishedContent FindContent(ActionExecutingContext actionExecutingContext)
    {
        IPublishedContent siteRoot = null;

        if (_umbracoContextAccessor.TryGetUmbracoContext(out var context))
        {
            siteRoot = context.Content.GetAtRoot().First();
        }

        return siteRoot;
    }

    [HttpGet]
    public ActionResult SitemapIndex()
    {
        //Removed for brevity

        Response.ContentType = "text/xml";
        return View("SitemapIndex", sitemapIndexViewModel);
    }
}
```

Composer for registering route:
```
public class SitemapComposer : IComposer
{
    public void Compose(IUmbracoBuilder builder)
    {
        builder.Services.Configure<UmbracoPipelineOptions>(options =>
        {
            options.AddFilter(new UmbracoPipelineFilter(nameof(SitemapController))
            {
                Endpoints = app => app.UseEndpoints(endpoints =>
                {
                    endpoints.MapControllerRoute("Sitemap Index", "/sitemapindex.xml", new { Controller = "Sitemap", Action = "SitemapIndex" });
                })
            });
        });
    }

}
```

**Comment by aguyfromdenmark** [comment]
Using IUmbracoContextFactory instead of IUmbracoContextAccessor allows you to get the context. 
It seems to me that it is the way it was always meant to be. 
```
using (UmbracoContextReference umbracoContextReference = _umbracoContextFactory.EnsureUmbracoContext())
{
    //Removed for brevity - Use the context here
}
```

**Comment by bergmania** [comment]
UmbracoContext is only set if the request is not considered a client-side request. Whay URL are you using with the SitemapController? if that is `/sitemap.xml` then thats the reason

**Comment by aguyfromdenmark** [comment]
Yes, I am using `/sitemap.xml`. 
But looking at what you are trying to accomplish with a `IVirtualPageController`, you would always need to use the `IUmbracoContextFactory `instead of the `IUmbracoContextAccessor `used in the docs. Right?

**Comment by bergmania** [comment]
Nah... If the url is different e.g. `/sitemap` then it would not be considered a client side request and thereby would UmbracoContext already exist.

**Comment by aguyfromdenmark** [comment]
> Nah... If the url is different e.g. `/sitemap` then it would not be considered a client side request and thereby would UmbracoContext already exist.

Ahh, yeah. I just tried it out, changing my custom route to just `/sitemapIndex` and using `IUmbracoContextAccessor` in `FindContent`. That works. Great!
