### ISSUE TITLE
Redirect Url Management not working

### ISSUE THREAD

**Issue by HefinJ** [umbraco/Umbraco-CMS#11695]
### Which *exact* Umbraco version are you using? For example: 9.0.1 - don't just write v9

9.1.1

### Bug summary

When renaming a page name the redirect manager is not showing a link for the "Original URL" and the "Redirect to" URL - both are showing as "#" as shown in the attached screenshot

![screenshot](https://user-images.githubusercontent.com/26006064/143252153-b8801ebe-93f2-43f9-bd24-733be5eb43f7.png)

### Steps to reproduce

- Using Visual Studio, setup a fresh install of Umbraco
- Run Umbraco
- Create two document types (no properties), "Home" and "Content Page"
- Allow "Home" to be created in root of site, and "Content Page" to be created as a child node of "Home"
- Create a "Home" page in Content area
- Create a child page to home page using "Content Page" e.g. "About Us"
- Rename "About Us" page
- Visit "Redirect Url Management"

### Expected result / actual result

The expected result would be an entry in the "Redirect Url Management" area showing the original url and the new url.  However this does not happen, the urls are just shown as "#"  

![screenshot](https://user-images.githubusercontent.com/26006064/143253172-3c65d7ef-1690-4bdc-b343-9b7d87f91de5.png)

This also happens un the "Info" area of the page that was renamed, as shown below:

![screenshot1](https://user-images.githubusercontent.com/26006064/143253381-5577ad0b-1094-4873-83ef-1685ca28a972.png)

**Comment by maartenmensink** [comment]
Just encountered this issue in Umbraco 9.1.2

**Comment by maartenmensink** [comment]
It seems that the data is stored correctly.

I renamed test to test2. So the old url is shown in the Url property

![image](https://user-images.githubusercontent.com/339653/147072329-86eb1ed5-d255-4535-996d-278bc209d935.png)

If i search for test it also correctly finds the redirect.

![image](https://user-images.githubusercontent.com/339653/147072695-499039d9-47ea-4e00-bccc-329499d14506.png)

But when i navigate to /test no redirection is performed to test2

tested on commit latest v9/contrib 380b70046fb3c1db88163047a64927c943368b60

**Comment by maartenmensink** [comment]
On mapping the call `_publishedUrlProvider?.GetUrl(source.ContentId, culture: source.Culture)` returns a `#`
![image](https://user-images.githubusercontent.com/339653/147076130-7e20d3a9-edcb-4414-ba0e-4adf599d1dcc.png)

Which results in calling In the `DefaultUrlProvider.GetUrl(........)`  which result in  a check if the `domainUrl is not null` be the method `AssembleUrl` handles a null for domain

![image](https://user-images.githubusercontent.com/339653/147076046-4950ffbf-f740-4137-a6dc-590e031c56b7.png)

![image](https://user-images.githubusercontent.com/339653/147076711-8531b7b8-ee48-4c88-bf08-0c81d6d00b7e.png)

cc @nul800sebastiaan

**Comment by bjarnef** [comment]
I noticed this as well on a project on v9.1.2 and all existing redirect rules are not showing # in "Original URL" and "Redirect To" to columns.

The project was original started on v8 and later migrated to v9.0.0 and patched to v9.0.1 on Umbraco Cloud.
I don't recall it was an issue on v9.0.x

Later it has been upgraded t v9.1.2 to fix issues with MNTP and entity lookups.
https://github.com/umbraco/Umbraco-CMS/pull/11685

![image](https://user-images.githubusercontent.com/2919859/147500847-f93c98cd-b941-4538-a895-b63f68f41e44.png)

@p-m-j maybe you know if something has changed regarding this from v9.0.x to v9.1.x?

**Comment by p-m-j** [comment]
Looks like changes to DefaultUrlProvider.GetUrlFromRoute in c77dc5dc00875b06cc435099c7d0b6709b69b21a break it.

Culture is empty string

```csharp
if (domainUri is not null || culture == defaultCulture || culture is null)
{
    var url = AssembleUrl(domainUri, path, current, mode).ToString();
    return UrlInfo.Url(url, culture);
}
```
Can fix by changing to
```csharp
if (domainUri is not null || culture == defaultCulture || string.IsNullOrEmpty(culture))
```

**Comment by bjarnef** [comment]
@p-m-j thanks for the tip. Seems to work to me and PR submitted: https://github.com/umbraco/Umbraco-CMS/pull/11799

**Comment by smarshallsay** [comment]
I am still encountering this issue even after updating to 9.3.0. Any pointers on things I can try? DB Schema looks fine and i've tried removing all cuiltures/hostnames and secondary languages.
