### ISSUE TITLE
Blazor Server Only Works On Home Page/Root On Umbraco 9 - Fails On Internal Pages

### ISSUE THREAD

**Issue by YodasMyDad** [umbraco/Umbraco-CMS#11706]
### Which *exact* Umbraco version are you using? For example: 9.0.1 - don't just write v9

v9.0.1

### Bug summary

Blazor Server fails for internal pages because it is trying to load /_blazor/initializers. This works for the home page (Root of the site), but for other pages on the site, it fails and returns a 404. This is because it's appending the page name.

i.e. For a Node on the site called Login and a URL of /login/ it tries to load the following URL  /login/_blazor/initializers.

This results in a 404 and Blazor fails to load. I don't know enough about Blazor to say whether this is a Blazor issue or a Umbraco issue, but as far as I can tell it should not be appended the page name before /_blazor/initializers.

### Specifics

Bug happens on all internal pages attempting to use a Blazor Server component.

### Steps to reproduce

https://user-images.githubusercontent.com/1932292/143854945-0f1f8b0b-651d-416b-8580-3aac6404a3e1.mp4

### Expected result / actual result

Blazor should work on all pages and as far as I'm aware the page name should not be appended to the initializers URL

**Comment by nul800sebastiaan** [comment]
As discussed on Discord, this can be fixed by https://github.com/umbraco/Umbraco-CMS/issues/10656#issuecomment-896245280 - adding `<base href="~/" />` in the `<head>` section seems to do the trick.
