### ISSUE TITLE
Mini-profiler script tag has one too many " signs

### ISSUE THREAD

**Issue by krebil** [umbraco/Umbraco-CMS#11711]
### Which *exact* Umbraco version are you using? For example: 9.0.1 - don't just write v9

9.0.1

### Bug summary

the generated script tag from mini-profiler has an extra " sign along it's attributes.
![image](https://user-images.githubusercontent.com/1363512/144069881-0062528d-8cc0-47a7-87c3-2313cf891476.png)
It breaks hotwired/turbo and I suppose other scripts that go through script tag attributes.

### Steps to reproduce

Install Umbraco 9.0.1, 
run in debug mode and check the source

**Comment by nul800sebastiaan** [comment]
Thank @krebil - not something we can fix, it's coming from the mini profiler plugin.. somewhere around here it seems to be building this string; https://github.com/MiniProfiler/dotnet/blame/a48fc7a9de95f0bbf583c3094d55b36096484493/src/MiniProfiler.Shared/Internal/Render.cs#L57

I'm sure they're enjoy a pull request to fix it!
