### ISSUE TITLE
Login and Registration do not show textboxes in the richtext editor when entered via macros.

### ISSUE THREAD

**Issue by Cocklebiddy** [umbraco/Umbraco-CMS#11721]
### Which *exact* Umbraco version are you using? For example: 9.0.1 - don't just write v9

v9.1.1

### Bug summary

I am trying to get to work the Login and Registration macro-in-richtext-editor situation. In _Umbraco 8_ it works perfectly. In _Umbraco 9_ there no issues while preparing everything, but the end result is that **no textboxes appear**. There is no trace of any '<textbox ....' in the source of the richtext field. The only difference is that I am using a _Umbraco Grid layout_ and inside this, the rich text.

### Specifics
![image](https://user-images.githubusercontent.com/10795599/144505903-2ea8080b-899f-4ed0-a59a-76a0a00732fd.png)

![image](https://user-images.githubusercontent.com/10795599/144505985-c6a4b3b5-0fb9-4cec-9282-c025d2c349c9.png)

![image](https://user-images.githubusercontent.com/10795599/144506080-31a06efb-ec5f-4580-ba70-c4abcf6c43cd.png)

![image](https://user-images.githubusercontent.com/10795599/144506185-ca7a33a1-908e-43ba-b2b3-5dcb4ac147f2.png)

This is the source (no input field):
<div class="mb-3">User name<span class="form-text text-danger field-validation-valid" data-valmsg-for="loginModel.Username" data-valmsg-replace="true"></span></div>

### Steps to reproduce

Please follow the standard procedure: creating the macro's with template, as part of the usual way to create a login/registration set of macro's and templates and place them in a rich text element (in this case the _Umbraco Grid lay-out_).

Nevertheless I didn't get it to work either in a _normal_ rich text field in a standard content page.

### Expected result / actual result

I would expect a login and registration possibility for a user/member in order to present extra menu elements and screens in a secured part of the website. All pretty much standard.

An example in _Umbraco **8**_: 
![image](https://user-images.githubusercontent.com/10795599/144504763-ef2af000-3341-4349-8741-5d093a7ea615.png)

**Comment by nul800sebastiaan** [comment]
Hi there @Cocklebiddy and sorry for the late reply. You've hit upon the problem where macros in the grid in the RTE don't render properly: https://github.com/umbraco/Umbraco-CMS/issues/6286

We don't recommend using the Grid in v9 and encourage the block list editor instead. However, if you do use the grid there's a few workaround for your template rendering in the linked issue (https://github.com/umbraco/Umbraco-CMS/issues/6286).
