### ISSUE TITLE
Block list item validation not firing for Umbraco.MediaPicker3

### ISSUE THREAD

**Issue by chrden** [umbraco/Umbraco-CMS#11732]
### Which *exact* Umbraco version are you using? For example: 9.0.1 - don't just write v9

8.16.0

### Bug summary

When adding a Block List Item to a page, if the Block List Item has a mandatory field using the Umbraco.MediaPicker3 datatype, the validation does not fire when the field is empty until the node is published.

![image](https://user-images.githubusercontent.com/22013176/144877555-b7379e40-12b9-418e-86f0-f06ca9ed89de.png)

If there is a nested Block List Editor (Block List Editor data type inside a Block List Editor) the same issue as above occurs, however there is no UI notification to inform the user what has caused the validation error. 

![image](https://user-images.githubusercontent.com/22013176/144877717-7f4b494c-e314-48c1-94b8-5460dd3caa54.png)

In both cases, the user is allowed to add the block to the Block List editor field BUT doesn't allow the node to be Saved or Saved and Published.

### Steps to reproduce

**Non-nested Block List Editor**
Add a Block List Item to a node with a mandatory field using the Umbraco.MediaPicker3 datatype to a page
Leave the image field empty
Click Save or Save and Publish

**Nested Block List Editor**
Add a Block List item with a Block List field data type to a page (that includes a Block List Item with a mandatory field using the Umbraco.MediaPicker3 datatype) to a page
Leave the image field empty
Click Save or Save and Publish

### Expected result / actual result

In both scenarios, I would expect the UI to provide a notification at the point at which the 'Confirm' button is pressed when then Block List item is saved, as per other fields, such as textstring datatype

![image](https://user-images.githubusercontent.com/22013176/144878513-b9658885-c689-4f96-b7cb-10be4cb63ef4.png)

**Comment by nul800sebastiaan** [comment]
Hey there @chrden I know that we have been busy fixing a lot of validation errors in the block list since version 8.16.0 - I would recommend you try again after an upgrade to 8.17.1, these things should now work properly. If you still have problems there then feel free to comment here again and we can have a look at re-opening this issue.
