### ISSUE TITLE
.TypedContent gets IPublishedContent with invalid child node

### ISSUE THREAD

**Issue by mjolicseven** [umbraco/Umbraco-CMS#11746]
### Which *exact* Umbraco version are you using? For example: 9.0.1 - don't just write v9

7.15.7

### Bug summary

Let me give a brief introduction on how our content is structured in the Umbraco CMS: We have an Episode node, that's parent node. Beneath that node we have a VideoAsset node (defined as UmbracoProperty), which is child node. We tracked the root cause of this issue and found out that the call to method ".TypedContent(int id);" (parameter ID was the episode's one) from "Umbraco.Web" assembly returned back a wrong child video asset. However, everything looks okay in the database.
![Screenshot_1](https://user-images.githubusercontent.com/95768004/145248328-75955204-1605-477c-809f-aefd8f716809.png)
![Screenshot_2](https://user-images.githubusercontent.com/95768004/145248347-22b26489-321c-4656-98b9-cd07e0be9f09.png)

.

### Steps to reproduce

We have an endpoint which is getting **Episode** (IPublishedContent) by Id from the CMS and sending SNS message to our other services.  In small period of time we're sending over a **1k requests** to this endpoint, picking up content and sending SNS message.

1. Umbraco api endpoint receives message with specific document id
2. typedPublishedContentQuery.TypedContent(Id); is being called
3. IPublishedContent for that specific item contains wrong property (that single child property is part of the other episode). We noticed that for a couple of episodes. (10 in 1000 lets say)

******UPDATE**: Meanwhile during the process we're casting IPublishedContent to specific Model using Ditto - **Ditto** might be the issue.

**Comment by meyntony** [comment]
https://github.com/umco/umbraco-ditto/issues

Sounds like this issue should be reported on the above issue tracker.

**Comment by mjolicseven** [comment]
Thanks Tony. I will report issue there.
