### ISSUE TITLE
Not possible to expand tree level in MNTP mini listview to select valid child node

### ISSUE THREAD

**Issue by bjarnef** [umbraco/Umbraco-CMS#11741]
### Which *exact* Umbraco version are you using? For example: 9.0.1 - don't just write v9

9.1.2

### Bug summary

With the following structure it seems it isn't possible to expand "group" level to select valid child items in listview. I think these should have an expand arrow like in media picker even though a folder isn't selectable.

- FAQ Archive (listview)
  - FAQ Group A
    - FAQ Item A.1
    - FAQ Item A.2
  - FAQ Group B
    - FAQ Item B.1
    - FAQ Item B.2

MNTP XPath: `$site/faqArchive` (but same result without any XPath expression).

Allow items of type: FAQ Item

### Steps to reproduce

Add the following content structure as described above and add a property to a document type using MNTP with the configuration above.

---
_This item has been added to our backlog [AB#25557](https://dev.azure.com/umbraco/243e7927-03b2-44e2-908f-d4ac7ea5daaa/_workitems/edit/25557)_

**Comment by emma-hq** [comment]
Hey Bjarne, thanks for reporting this. Yep! I have this too. Any thoughts around approaches to fix this?

Emma

**Comment by kjac** [comment]
Hi @bjarnef ... happy new year again 😆 

The scenario plays out a tad better in V10, but it's still somewhat unclear that one can actually expand the un-selectable items:

![11741-before](https://user-images.githubusercontent.com/7405322/211872999-4ecf44fb-7174-4bb8-baa5-51637d5fa6e3.gif)

I have created a PR to fix the styling - #13661
