### ISSUE TITLE
404 importDocumentType.html incorrect camelcasing

### ISSUE THREAD

**Issue by maartenmensink** [umbraco/Umbraco-CMS#11752]
### Which *exact* Umbraco version are you using? For example: 9.0.1 - don't just write v9

9.1.2

### Bug summary

When clicking Import Document Type a 4040 notfound error is shown get raised

![image](https://user-images.githubusercontent.com/339653/145546147-9338fd3e-e05a-417f-9fff-2a26d1cb110a.png)

### Specifics

Url: /umbraco#/settings
Docker: mcr.microsoft.com/dotnet/aspnet:5.0.7-alpine3.13

### Steps to reproduce

1. Run a default  umbraco installation on a linux container.
2. login to backend
3. go to settings
4. Right click Document types
5. Click Import Document Type

### Expected result / actual result

**Expected result**

The import document type template is loaded

**Actual result**

404 not found

---
_This item has been added to our backlog [AB#15629](https://dev.azure.com/umbraco/243e7927-03b2-44e2-908f-d4ac7ea5daaa/_workitems/edit/15629)_

**Comment by Zeegaan** [comment]
This should now be fixed in https://github.com/umbraco/Umbraco-CMS/pull/11753
