### ISSUE TITLE
Save and Publish is slow when adding more blocks

### ISSUE THREAD

**Issue by prjseal** [umbraco/Umbraco-CMS#11761]
### Which *exact* Umbraco version are you using? For example: 9.0.1 - don't just write v9

8.17.0

### Bug summary

When adding more rows to my content item using the block list editor, it gets slower to save and publish each time. 
Each new row adds on between 0.5 and 1 second to the save and publish time. This is even if I don't add any data to the block item.

### Specifics

This is when using the block list data type with custom defined blocks

### Steps to reproduce

Create a page that uses the block list editor.
Save and publish without adding any rows to the block list property. It shoud be around 1 second.
Start adding rows and saving and publishing. Notice the time from start to end save and publish gets slower.

### Expected result / actual result

The save and publish should not increase so much just because we are adding rows.

It should stay around the 1 second mark for a save and publish.

---
_This item has been added to our backlog [AB#15625](https://dev.azure.com/umbraco/243e7927-03b2-44e2-908f-d4ac7ea5daaa/_workitems/edit/15625)_

**Comment by Zeegaan** [comment]
Hey @prjseal , thank you for your issue report! 🐛 
I am having trouble reproducing this, can you maybe provide some more specific steps or a gif? 🕵️

Heres what I tried with attached gifs: 
- Save and publish, add a bunch of blocks then save and publish:
![SaveAndPublishFast](https://user-images.githubusercontent.com/70372949/147096962-50da73bb-6d9f-4ae4-8b5a-0e783176727f.gif)
- Save and publish, then add a block at a time and save and publish:
![SaveAndPublishOneAtATime](https://user-images.githubusercontent.com/70372949/147097002-f45090dd-cd0f-4bde-be58-5ad8330526c9.gif)

**Comment by prjseal** [comment]
Hi. Thanks for looking into this. I found the cause of the problem. It was a bug in uSync Complete. We can close this now.
