### ISSUE TITLE
Container validation (ValidateOnBuild) fails if backoffice controllers are added to IOC container (non standard setup).

### ISSUE THREAD

**Issue by DavePearcey** [umbraco/Umbraco-CMS#11764]
### Which *exact* Umbraco version are you using? For example: 9.0.1 - don't just write v9

9.1.2

### Bug summary

Had an issue with member passwords in 9.0.1 and was suggested I upgrade to latest version.

Upgraded from 9.0.1 to 9.1.2 via NuGet Package Manager, built the solution and run. 

get the following Error:

    An error occurred while starting the application.
    AggregateException: Some services are not able to be constructed (Error while validating the service descriptor 'ServiceType: Umbraco.Cms.Web.BackOffice.Controllers.CurrentUserController Lifetime: Transient ImplementationType: Umbraco.Cms.Web.BackOffice.Controllers.CurrentUserController': Unable to activate type 'Umbraco.Cms.Web.BackOffice.Controllers.CurrentUserController'. The following constructors are ambiguous:
    Void .ctor(Umbraco.Cms.Core.IO.MediaFileManager, Microsoft.Extensions.Options.IOptions`1[Umbraco.Cms.Core.Configuration.Models.ContentSettings], Umbraco.Cms.Core.Hosting.IHostingEnvironment, Umbraco.Cms.Core.Media.IImageUrlGenerator, Umbraco.Cms.Core.Security.IBackOfficeSecurityAccessor, Umbraco.Cms.Core.Services.IUserService, Umbraco.Cms.Core.Mapping.IUmbracoMapper, Umbraco.Cms.Core.Security.IBackOfficeUserManager, Umbraco.Cms.Core.Services.ILocalizedTextService, Umbraco.Cms.Core.Cache.AppCaches, Umbraco.Cms.Core.Strings.IShortStringHelper, Umbraco.Cms.Web.Common.Security.IPasswordChanger`1[Umbraco.Cms.Core.Security.BackOfficeIdentityUser], Umbraco.Cms.Core.Services.IUserDataService)
    Void .ctor(Umbraco.Cms.Core.IO.MediaFileManager, Microsoft.Extensions.Options.IOptions`1[Umbraco.Cms.Core.Configuration.Models.ContentSettings], Umbraco.Cms.Core.Hosting.IHostingEnvironment, Umbraco.Cms.Core.Media.IImageUrlGenerator, Umbraco.Cms.Core.Security.IBackOfficeSecurityAccessor, Umbraco.Cms.Core.Services.IUserService, Umbraco.Cms.Core.Mapping.IUmbracoMapper, Umbraco.Cms.Core.Security.IBackOfficeUserManager, Microsoft.Extensions.Logging.ILoggerFactory, Umbraco.Cms.Core.Services.ILocalizedTextService, Umbraco.Cms.Core.Cache.AppCaches, Umbraco.Cms.Core.Strings.IShortStringHelper, Umbraco.Cms.Web.Common.Security.IPasswordChanger`1[Umbraco.Cms.Core.Security.BackOfficeIdentityUser]))

    Microsoft.Extensions.DependencyInjection.ServiceProvider..ctor(IEnumerable<ServiceDescriptor> serviceDescriptors, IServiceProviderEngine engine, ServiceProviderOptions options)
    InvalidOperationException: Error while validating the service descriptor 'ServiceType: Umbraco.Cms.Web.BackOffice.Controllers.CurrentUserController Lifetime: Transient ImplementationType: Umbraco.Cms.Web.BackOffice.Controllers.CurrentUserController': Unable to activate type 'Umbraco.Cms.Web.BackOffice.Controllers.CurrentUserController'. The following constructors are ambiguous:
    Void .ctor(Umbraco.Cms.Core.IO.MediaFileManager, Microsoft.Extensions.Options.IOptions`1[Umbraco.Cms.Core.Configuration.Models.ContentSettings], Umbraco.Cms.Core.Hosting.IHostingEnvironment, Umbraco.Cms.Core.Media.IImageUrlGenerator, Umbraco.Cms.Core.Security.IBackOfficeSecurityAccessor, Umbraco.Cms.Core.Services.IUserService, Umbraco.Cms.Core.Mapping.IUmbracoMapper, Umbraco.Cms.Core.Security.IBackOfficeUserManager, Umbraco.Cms.Core.Services.ILocalizedTextService, Umbraco.Cms.Core.Cache.AppCaches, Umbraco.Cms.Core.Strings.IShortStringHelper, Umbraco.Cms.Web.Common.Security.IPasswordChanger`1[Umbraco.Cms.Core.Security.BackOfficeIdentityUser], Umbraco.Cms.Core.Services.IUserDataService)
    Void .ctor(Umbraco.Cms.Core.IO.MediaFileManager, Microsoft.Extensions.Options.IOptions`1[Umbraco.Cms.Core.Configuration.Models.ContentSettings], Umbraco.Cms.Core.Hosting.IHostingEnvironment, Umbraco.Cms.Core.Media.IImageUrlGenerator, Umbraco.Cms.Core.Security.IBackOfficeSecurityAccessor, Umbraco.Cms.Core.Services.IUserService, Umbraco.Cms.Core.Mapping.IUmbracoMapper, Umbraco.Cms.Core.Security.IBackOfficeUserManager, Microsoft.Extensions.Logging.ILoggerFactory, Umbraco.Cms.Core.Services.ILocalizedTextService, Umbraco.Cms.Core.Cache.AppCaches, Umbraco.Cms.Core.Strings.IShortStringHelper, Umbraco.Cms.Web.Common.Security.IPasswordChanger`1[Umbraco.Cms.Core.Security.BackOfficeIdentityUser])

    Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.ValidateService(ServiceDescriptor descriptor)

        AggregateException: Some services are not able to be constructed (Error while validating the service descriptor 'ServiceType: Umbraco.Cms.Web.BackOffice.Controllers.CurrentUserController Lifetime: Transient ImplementationType: Umbraco.Cms.Web.BackOffice.Controllers.CurrentUserController': Unable to activate type 'Umbraco.Cms.Web.BackOffice.Controllers.CurrentUserController'. The following constructors are ambiguous: Void .ctor(Umbraco.Cms.Core.IO.MediaFileManager, Microsoft.Extensions.Options.IOptions`1[Umbraco.Cms.Core.Configuration.Models.ContentSettings], Umbraco.Cms.Core.Hosting.IHostingEnvironment, Umbraco.Cms.Core.Media.IImageUrlGenerator, Umbraco.Cms.Core.Security.IBackOfficeSecurityAccessor, Umbraco.Cms.Core.Services.IUserService, Umbraco.Cms.Core.Mapping.IUmbracoMapper, Umbraco.Cms.Core.Security.IBackOfficeUserManager, Umbraco.Cms.Core.Services.ILocalizedTextService, Umbraco.Cms.Core.Cache.AppCaches, Umbraco.Cms.Core.Strings.IShortStringHelper, Umbraco.Cms.Web.Common.Security.IPasswordChanger`1[Umbraco.Cms.Core.Security.BackOfficeIdentityUser], Umbraco.Cms.Core.Services.IUserDataService) Void .ctor(Umbraco.Cms.Core.IO.MediaFileManager, Microsoft.Extensions.Options.IOptions`1[Umbraco.Cms.Core.Configuration.Models.ContentSettings], Umbraco.Cms.Core.Hosting.IHostingEnvironment, Umbraco.Cms.Core.Media.IImageUrlGenerator, Umbraco.Cms.Core.Security.IBackOfficeSecurityAccessor, Umbraco.Cms.Core.Services.IUserService, Umbraco.Cms.Core.Mapping.IUmbracoMapper, Umbraco.Cms.Core.Security.IBackOfficeUserManager, Microsoft.Extensions.Logging.ILoggerFactory, Umbraco.Cms.Core.Services.ILocalizedTextService, Umbraco.Cms.Core.Cache.AppCaches, Umbraco.Cms.Core.Strings.IShortStringHelper, Umbraco.Cms.Web.Common.Security.IPasswordChanger`1[Umbraco.Cms.Core.Security.BackOfficeIdentityUser]))
            Microsoft.Extensions.DependencyInjection.ServiceProvider..ctor(IEnumerable<ServiceDescriptor> serviceDescriptors, IServiceProviderEngine engine, ServiceProviderOptions options)
            Microsoft.Extensions.DependencyInjection.ServiceCollectionContainerBuilderExtensions.BuildServiceProvider(IServiceCollection services, ServiceProviderOptions options)
            Microsoft.Extensions.DependencyInjection.DefaultServiceProviderFactory.CreateServiceProvider(IServiceCollection containerBuilder)
            Microsoft.Extensions.Hosting.Internal.ServiceFactoryAdapter<TContainerBuilder>.CreateServiceProvider(object containerBuilder)
            Microsoft.Extensions.Hosting.HostBuilder.CreateServiceProvider()
            Microsoft.Extensions.Hosting.HostBuilder.Build()
            ValkyriesFall.Program.Main(string[] args) in Program.cs

                        => CreateHostBuilder(args)

    InvalidOperationException: Error while validating the service descriptor 'ServiceType: Umbraco.Cms.Web.BackOffice.Controllers.CurrentUserController Lifetime: Transient ImplementationType: Umbraco.Cms.Web.BackOffice.Controllers.CurrentUserController': Unable to activate type 'Umbraco.Cms.Web.BackOffice.Controllers.CurrentUserController'. The following constructors are ambiguous: Void .ctor(Umbraco.Cms.Core.IO.MediaFileManager, Microsoft.Extensions.Options.IOptions`1[Umbraco.Cms.Core.Configuration.Models.ContentSettings], Umbraco.Cms.Core.Hosting.IHostingEnvironment, Umbraco.Cms.Core.Media.IImageUrlGenerator, Umbraco.Cms.Core.Security.IBackOfficeSecurityAccessor, Umbraco.Cms.Core.Services.IUserService, Umbraco.Cms.Core.Mapping.IUmbracoMapper, Umbraco.Cms.Core.Security.IBackOfficeUserManager, Umbraco.Cms.Core.Services.ILocalizedTextService, Umbraco.Cms.Core.Cache.AppCaches, Umbraco.Cms.Core.Strings.IShortStringHelper, Umbraco.Cms.Web.Common.Security.IPasswordChanger`1[Umbraco.Cms.Core.Security.BackOfficeIdentityUser], Umbraco.Cms.Core.Services.IUserDataService) Void .ctor(Umbraco.Cms.Core.IO.MediaFileManager, Microsoft.Extensions.Options.IOptions`1[Umbraco.Cms.Core.Configuration.Models.ContentSettings], Umbraco.Cms.Core.Hosting.IHostingEnvironment, Umbraco.Cms.Core.Media.IImageUrlGenerator, Umbraco.Cms.Core.Security.IBackOfficeSecurityAccessor, Umbraco.Cms.Core.Services.IUserService, Umbraco.Cms.Core.Mapping.IUmbracoMapper, Umbraco.Cms.Core.Security.IBackOfficeUserManager, Microsoft.Extensions.Logging.ILoggerFactory, Umbraco.Cms.Core.Services.ILocalizedTextService, Umbraco.Cms.Core.Cache.AppCaches, Umbraco.Cms.Core.Strings.IShortStringHelper, Umbraco.Cms.Web.Common.Security.IPasswordChanger`1[Umbraco.Cms.Core.Security.BackOfficeIdentityUser])

        Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.ValidateService(ServiceDescriptor descriptor)
        Microsoft.Extensions.DependencyInjection.ServiceProvider..ctor(IEnumerable<ServiceDescriptor> serviceDescriptors, IServiceProviderEngine engine, ServiceProviderOptions options)

    .NET 5.0.10 X64 v5.0.0.0    |   Microsoft.AspNetCore.Hosting version 5.0.10+b92c9f50f0333ea661785ba849f303cde6a93844    |    Microsoft Windows 10.0.19042    |   Need help?

### Specifics

This solution was a v8 project before converting to to v9. Worked fine in 9.0.1.

Also tried going from 9.0.1 to 9.1.0 and same issue occured.

Have tried to clean the solution in the following way:

`$ dotnet clean # for project`
`$ dotnet nuget locals all --clear`

### Steps to reproduce

Was unable to be reproduced by someone else in the Discord server.

### Expected result / actual result

Expect the application to start and redirect to the umbraco upgrade install screen.

---
_This item has been added to our backlog [AB#15598](https://dev.azure.com/umbraco/243e7927-03b2-44e2-908f-d4ac7ea5daaa/_workitems/edit/15598)_

**Comment by p-m-j** [comment]
@DavePearcey hey, it looks like the CurrentUserController has found its way into the service registrations in your project, controllers shouldn't be registered for v9 but they used to be in v8.

**Comment by p-m-j** [comment]
Confirmed on discord this was the issue, whilst unexpected to have controllers registered we should still probably not break for sites that do.

Suggest we add controllers to container in web.ui project in a way that won't get shipped by project templates (e.g. a composer not Startup.cs) so we can ensure controller constructors wouldn't be ambiguous when registered.

Will require a fix for CurrentUserController which really is ambiguous (legacy and modern ctor both take 13 params) and perhaps others?

**Comment by nul800sebastiaan** [comment]
Fixed for 9.4.0 in https://github.com/umbraco/Umbraco-CMS/pull/11874
