### ISSUE TITLE
.HasValue always False with culture on non-varied property

### ISSUE THREAD

**Issue by patrickdemooij9** [umbraco/Umbraco-CMS#11815]
### Which *exact* Umbraco version are you using? For example: 9.0.1 - don't just write v9

9.0.1

### Bug summary

For some reason whenever you pass a culture through .HasValue, it will always return false even if the value actually exists.
I used the following code snippet:
`    <p>HasValue: @Model.HasValue("changeFrequency")</p>
    <p>HasValue with culture: @Model.HasValue("changeFrequency", "en-US")</p>
    <p>@_variationContextAccessor.VariationContext.Culture</p>`

And I get this as result:
![image](https://user-images.githubusercontent.com/11466511/147889881-5ab41c8f-749e-426f-9772-f71be041c32c.png)

Which is super strange as I assume that, if the culture isn't given as a parameter, it uses the culture of the variationcontext instead. But apparently there is still something else going on.

### Steps to reproduce

- New Umbraco 9 installation
- Add a new language
- Add a new document type with one property
- Set the document type to varied by culture, but not the property.
- Create the page on the website
- Use the snippet above with the property alias that you have set.

You should now see that the same issue occurs. If you now change the property to varied by culture, it does work correctly.

### Expected result / actual result

HasValue with culture should return true if a value is given.
The logic that drives .HasValue without culture and where the variationContext culture is en-US should be the same as if you would call .HasValue with culture en-US

**Comment by patrickdemooij9** [comment]
Just tried this in 8.11.1 as well and it seems to have the same issue. I guess it can make sense, but it makes this a lot more difficult if I am making an package. I would have to do a HasValue with culture and then a HasValue without culture as I wouldn't know if the website has multi-language or not

**Comment by nul800sebastiaan** [comment]
Sorry that you've been unlucky with all the quirks of Umbraco these past few weeks @patrickdemooij9 - based on the previous issues I've looked into today you can already guess what the answer is 🙈  - while certainly not optimal, we'll have to live with this for now, it's been like this for too long and changing it now would break everyone's existing websites when they've already worked around these quirks. So sadly, I'll have to close this one as well.

**Comment by patrickdemooij9** [comment]
@nul800sebastiaan, yeah I kinda expected that after figuring out that it also happens on v8 :(
Will see how I can work around this then
