### ISSUE TITLE
MultiNodeTreePicker (mntp) only shows nodes at first time

### ISSUE THREAD

**Issue by inetzo** [umbraco/Umbraco-CMS#11818]
### Which *exact* Umbraco version are you using? For example: 9.0.1 - don't just write v9

8.17.1 - 9.2RC

### Bug summary

When a documenttype has an MultiNodeTreePicker property editor, the nodes only shown when the overlay is opended the first time. When you close the overlay and open it again, the nodes are not shown anymore. 

### Specifics

There are no errors in the console. When the overlay it openend the second time, i do see that "umbraco/backoffice/umbracoapi/entity/GetChildren" is called and has results but they are not rendered.

### Steps to reproduce

Add a MultiNodeTreePicker to documenttype. 
Click on the "Add" button of the MNTP, the overlay shows the nodes.
Click the "Close" button of the overlay.
Click on the "Add" button of the MNTP again, the overlay shows no nodes.

**Comment by patrickdemooij9** [comment]
Might be related to this issue: https://github.com/umbraco/Umbraco-CMS/issues/11424

**Comment by inetzo** [comment]
This is the same issue. I applied the changes of https://github.com/umbraco/Umbraco-CMS/pull/11428/files and this fixes it for me.
Thanks @uppercuut  for investigating this!
Thanks @patrickdemooij9 for mentioning this open issue.
