### ISSUE TITLE
Login background image and logo are missing

### ISSUE THREAD

**Issue by argentini** [umbraco/Umbraco-CMS#11830]
### Which *exact* Umbraco version are you using? For example: 9.0.1 - don't just write v9

9.0 through 9.2

### Bug summary

The login page background image and corner logo are missing due to bad URLs.

<img width="1856" alt="Login-Images-Missing" src="https://user-images.githubusercontent.com/1504331/148428655-ea3f66fb-8ffb-4e38-848d-8c2d05959941.png">

### Specifics

The URLs use a tilde (e.g. "~/assets/img/application/umbraco_logo_white.svg") when trying to access content in "wwwroot/umbraco/...". The tilde is being rendered to the browser, so the URL is invalid.

### Steps to reproduce

View the Umbraco login page.

### Expected result / actual result

Background image and logo should render.

**Comment by emma-hq** [comment]
Thanks for this @argentini - I'll label as up for grabs so it can be fixed. 

Emma

**Comment by markadrake** [comment]
Wit the latest, all I see wrong now is that the logo doesn't have any width so it doesn't appear. I've gone ahead and submitted a PR to add back in a width so the Umbraco logo can show. 

Somebody else must have fixed the paths to the images!

![image](https://user-images.githubusercontent.com/713355/150901517-0c053e99-da35-4cfb-b052-6237ee87c201.png)

**Comment by argentini** [comment]
Hey Mark,

I'm not sure what you mean by "latest", so to be safe, I've attached a
screen shot of the latest release, 9.2.0, which shows that the URL for the
background image (and also the logo) contain a tilde which breaks the URL.
If I use the developer tools and change "~/assets..." to
"/umbraco/assets/..." the images work.

-- 

M.

**Comment by argentini** [comment]
<img width="1631" alt="Bad Umbraco Image Paths" src="https://user-images.githubusercontent.com/1504331/151017337-a4ea4443-7430-4d6b-aed7-64930f54c3c7.png">

**Comment by markadrake** [comment]
Thanks @argentini! I think there have been a few pull requests or commits by HQ to resolve some of the issues (like the ~ character). This was already taken care of prior to my commit(s) above. I'll double check, but the resulting screen looks good.

For reference, I'm using the **v9/contrib** branch. It's got a number of changes not included in version 9.2.0 now. 

I'll double check my end.

**Comment by argentini** [comment]
@markadrake I just upgraded to version 9.3.0 and the problem still exists.

<img width="1640" alt="Screen Shot 2022-02-10 at 5 52 04 PM" src="https://user-images.githubusercontent.com/1504331/153510362-50cd2020-ce8c-4281-803e-43e0613a9957.png">

**Comment by argentini** [comment]
@nathanwoulfe poking you to check my last post - problem still exists in 9.3.0

**Comment by markadrake** [comment]
Screenshot of the `v9/contrib` branch. Just in case, I cleared the folder and downloaded the project completely fresh. 

![image](https://user-images.githubusercontent.com/713355/153513665-3f6e1ff1-ff79-468a-8384-cf8d557010ba.png)

The `~` character is no longer present in the HTML source.

![image](https://user-images.githubusercontent.com/713355/153513791-7b20ddbb-2dca-4ac8-999d-39e1b2bebd78.png)

After updating templates, I created a new site using `dotnet new umbraco`, walked through installation, signed out, refreshed:

![image](https://user-images.githubusercontent.com/713355/153514630-36fd84e2-e1df-4234-b8b8-06ca547d008a.png)

@argentini is there anything unique about your environment? I'm at a loss of options. Running this in a linux / mac environment by chance?

**Comment by argentini** [comment]
@markadrake I am running this in macOS, but when deployed to Windows it still does it there as well.

I also deleted both umbraco folders, smidge, etc., then rebuilt and ran in an InPrivate/Incongnito Chroms window and it still does it. I'm at a loss. Can you try again with the released version of 9.3.0 from Nuget?

**Comment by argentini** [comment]
@markadrake please don't apologize, you've been extremely helpful. So helpful, in fact, that I figured it out!

I had copied the recommended appsettings from the Umbraco website, and they had those two image asset URLs specified with the tilde character! I removed the two lines and it worked. 

I'm not sure if you can handle this request, but if you look at [https://our.umbraco.com/documentation/reference/V9-Config/ContentSettings/](https://our.umbraco.com/documentation/reference/V9-Config/ContentSettings/) you'll see the incorrect values for LoginBackgroundImage and LoginLogoImage. Can you or someone else fix those items?

<img width="1312" alt="Screen Shot 2022-02-10 at 9 06 07 PM" src="https://user-images.githubusercontent.com/1504331/153527322-0b00352e-fad8-4676-a292-3678cd359b89.png">

**Comment by markadrake** [comment]
@argentini that's awesome mate! I was losing a little sleep last night trying to figure out what in the world this could be. I will follow up about the documentation. 

Thanks for the kind reply!
