### ISSUE TITLE
Notifications not being fired by Subscriber after slot swap on Azure

### ISSUE THREAD

**Issue by digbyswift** [umbraco/Umbraco-CMS#11831]
### Which *exact* Umbraco version are you using? For example: 9.0.1 - don't just write v9

9.0.1-9.1.2

### Bug summary

When a subscriber Umbraco instance is deployed to an Azure slot and then swapped into production, any notifications then fail to be triggered. If we restart the instance (e.g. by touching the config) then the notifications generally start firing again. There are no errors and nothing in the logs to indicate an issue.

### Specifics

We have a site hosted on Azure and set up as per the documentation here https://our.umbraco.com/Documentation/Fundamentals/Setup/Server-Setup/Load-Balancing/azure-web-apps. We deploy the backoffice to a "stopped" slot on a non-scaling app service and then swap it to production and then stop the deploy slot. We do the same for the public facing site the only difference being that this is automatically scaled to two instances. We have several notification handlers set up (e.g. for `ContentCacheRefresherNotification`, `ContentSavingNotification`) all of which have logging implemented so we can track when/if they fire.

Once deployed, the backoffice is always able to fire its notifications and log out the associated data. The public facing instances however, upon slot swap never fire their configured notifications and therefore never output to the logs. We always have to manually restart the front end instances for the instances to start firing the notifications.

I can confirm that the 3 separate instances are all registering in the [umbracoServer] table and the backoffice instance is marked correctly as active and the publisher. The backoffice also generating cache instruction records.

We have tried setting WEBSITE_DISABLE_OVERLAPPED_RECYCLING and WEBSITE_ADD_SITENAME_BINDINGS_IN_APPHOST_CONFIG in combination, separately and also neither in the application settings and these seem to make little difference.

Having stepped through the code I am _assuming_ that one of a couple of things is happening:

- The `InstructionProcessTask`/`RecurringHostedServiceBase` isn't being triggered
- The `EventAggregator` isn't being triggered

Although I'm not entirely sure, I'm wondering if this might be to do with locking and the fact that currently the `ServerRegistration.ServerIdentity` value would be identical for each slot in the same app service. If these were unique then maybe locking wouldn't be as much of an issue? 

### Steps to reproduce

We have reproduced the issue using an _almost_ clean install using the following set up:

1. Create two app services, A & B
2. Deploy master to app service A
3. Create a deploy slot in app service B
4. Deploy subscriber to both slots, ensuring that the subscriber has a notification handler for `ContentCacheRefresherNotification` for example.
5. Swap app service deploy and production slots, then stop deploy slot
6. Publish content in the backoffice
7. Restart deploy slot and swap again, then stop deploy slot.
8. Publish content in the backoffice
9. Restart app service B's production slot
10. Publish content in the backoffice

### Expected result / actual result

I would expect to be able to perform a vanilla slot swap and for notifications to "just work".

Instead, after steps 6 & 8 we find that notificatons aren't triggered in app service B's production slot. After step 10, notificatons are (more often than not) triggered in app service B's production slot.

---
_This item has been added to our backlog [AB#17572](https://dev.azure.com/umbraco/243e7927-03b2-44e2-908f-d4ac7ea5daaa/_workitems/edit/17572)_

**Comment by digbyswift** [comment]
I performed a deployment today to the production server and there was a useful delay before the deploy slots were stopped (as they should be in the process described above). So after the slot swaps completed but before the deploy slopts were stopped, I published a page of content in the backoffice to test the notifications and got the following logs:

```
Jan 07 16:53:30 --------0031M. ProductionCmsDeploy Content cache cleared on publish #cache
Jan 07 16:53:31 --------000CO. ProductionDeploy Content cache cleared on publish #cache
Jan 07 16:53:35 --------0031M. ProductionCmsDeploy Application is shutting down
Jan 07 16:53:35 --------0031M. ProductionCmsDeploy Shutting down #shutdown
Jan 07 16:53:41 --------000GB. ProductionDeploy Application is shutting down
Jan 07 16:53:41 --------000GB. ProductionDeploy Shutting down #shutdown
Jan 07 16:53:41 --------000CO. ProductionDeploy Application is shutting down
Jan 07 16:53:41 --------000CO. ProductionDeploy Shutting down #shutdown 
```

As part of the hosting architecture I have named each slot according to it's purpose and used this name in the logs so that I can filter based on the slot. In the logs above you can see that although the slots had swapped, performing a publish on the _production_ slot triggered notifications to occur on both the backoffice deploy slot and also one of the subscriber's deploy slot.

This indicates that Umbraco is able to _retain_ the ability send notification in an existing app after a slot swap but unable to activate the ability to fire notifications in a new app after a slot swap.

I hope this helps.

**Comment by digbyswift** [comment]
Looking at the code a little further, could it be the `SqlMainDomLock.MainDomKey`? If the slots of an app service have the same application path then applications in those slots will have the same `MainDomKey`.

**Comment by digbyswift** [comment]
I can also report that this is affecting the scheduled publishing on the CMS instance. A restart of the application fixes it.

**Comment by digbyswift** [comment]
@nzdev Yep, I was wondering whether this would be useful too. The additional variable would prbably need to be `Environment.GetEnvironmentVariable("WEBSITE_INSTANCE_ID");` as this would be the slot's ID.

However, I'm certain that this issue is tied to acquisition of the MainDom https://github.com/umbraco/Umbraco-CMS/issues/11935

**Comment by nzdev** [comment]
Makes sense to use WEBSITE_INSTANCE_ID where it's available

**Comment by nzdev** [comment]
@digbyswift Do you have any log files indicating any errors related to this issue? I've seen InstructionProcessTask log an error relating to the database scope being already disposed causing it to fail to process instructions from the database.

**Comment by digbyswift-oss** [comment]
@nzdev No, because essentially the instance doesn't know that it should be processing instructions.

**Comment by p-m-j** [comment]
@digbyswift was this resolved in the other issue? Is it OK to close this one?

**Comment by digbyswift** [comment]
@p-m-j Hi mate, yes I think so. We have v9.4.3 in a staging environment identical to production, have deployed several times and it's seeming fine.
