### ISSUE TITLE
Issue with Custom Index on v8 and Azure

### ISSUE THREAD

**Issue by poornimanayar** [umbraco/Umbraco-CMS#11843]
### Which *exact* Umbraco version are you using? For example: 9.0.1 - don't just write v9

8.16.0

### Bug summary

We have a v8 site where we upload a CSV to create a custom index. We had a case of site outage and noticed that the custom index got wiped out completely and the data was not showing up on the website. This happens when we restart the site too. This doesn't seem right but I know some others have experienced it too.

### Steps to reproduce

Create a custom index using a csv import, restart the site

**Comment by kjac** [comment]
Hi there @poornimanayar 👋

Thanks for reporting this... Sorry for the late response.

I'm afraid the issue description doesn't have a whole lot to go on in terms of replicating the issue. Is this still happening? And if so, could you share some more specifics and maybe even some code to help replicate it?

**Comment by Zeegaan** [comment]
Hi there! 👋 As we don't have a whole lot to go off here, and it's been a while since we've heard from you, even though that is our fault for getting back to you late.
I am going to go ahead and close this. 
Do feel free to re-open this if its still an issue and you find more information 😊
