### ISSUE TITLE
UseStatusCodePages should not be set by Umbraco

### ISSUE THREAD

**Issue by patrickdemooij9** [umbraco/Umbraco-CMS#11851]
### Which *exact* Umbraco version are you using? For example: 9.0.1 - don't just write v9

All v9 versions

### Bug summary

We are currently working on a v9 website and we are having an issue rewriting static files that are returning a 404. In v8 (and .net framework), this would be done with the following setting in web.config:
![image](https://user-images.githubusercontent.com/11466511/149139574-e3dce46b-13a8-44e5-918e-adac51bcdd00.png)

With .Net Core, we don't have this setting anymore, but we do have the UseStatusCodePages that can be used for this. According to https://docs.microsoft.com/en-us/aspnet/core/fundamentals/error-handling?view=aspnetcore-6.0, we can use something like `app.UseStatusCodePagesWithReExecute("/{0}");` to redirect every 404 error to /404. Now when we go to something like test.jpg (which doesn't exist), it'll show this screen:
![image](https://user-images.githubusercontent.com/11466511/149138979-6bb13250-cf39-4384-b743-cf44b7a8e33c.png)

However, this function doesn't work with the current Umbraco installation. This is because Umbraco already does UseStatusCodePages themselves: https://github.com/umbraco/Umbraco-CMS/blob/5bfab13dc5a268714aad2426a2b68ab5561a6407/src/Umbraco.Web.Common/ApplicationBuilder/UmbracoApplicationBuilder.cs#L88

There are two places where we can place the UseStatusCodePagesWithReExecute(). We can place it in front `app.UseUmbraco()`. However, then the UseStatusCodePages will be executed before UseStatusCodePagesWithReExecute (due to how middlewares flow back) and the UseStatusCodePagesWithReExecute logic inside will not be called.

We can also place it after the `app.UseUmbraco()`. This way the logic of UseStatusCodePagesWithReExecute does execute, but it doesn't work at all. This is because the function goes back into the middlewares to find the page with the given path. However, because it is placed after the `app.UseUmbraco()`, it will not be able to execute the Umbraco middleware to find the page.

So what is the ideal position here? We want the UseStatusCodePagesWithReExecute before the `UseUmbracoCoreMiddleware`, but after the `AppBuilder.UseStatusCodePages();` so that isn't really possible with the current situation.

### Steps to reproduce

Using the following code snippet:
```
AppBuilder.UseStatusCodePages(async context =>
            {
                var newPath = new PathString(
                    string.Format(CultureInfo.InvariantCulture, "/{0}", context.HttpContext.Response.StatusCode));
                string formatedQueryString = null;
                var newQueryString = QueryString.Empty;

                var originalPath = context.HttpContext.Request.Path;
                var originalQueryString = context.HttpContext.Request.QueryString;
                // Store the original paths so the app can check it.
                context.HttpContext.Features.Set<IStatusCodeReExecuteFeature>(new StatusCodeReExecuteFeature()
                {
                    OriginalPathBase = context.HttpContext.Request.PathBase.Value,
                    OriginalPath = originalPath.Value,
                    OriginalQueryString = originalQueryString.HasValue ? originalQueryString.Value : null,
                });

                // An endpoint may have already been set. Since we're going to re-invoke the middleware pipeline we need to reset
                // the endpoint and route values to ensure things are re-calculated.
                context.HttpContext.SetEndpoint(endpoint: null);
                var routeValuesFeature = context.HttpContext.Features.Get<IRouteValuesFeature>();
                routeValuesFeature?.RouteValues?.Clear();

                context.HttpContext.Request.Path = newPath;
                context.HttpContext.Request.QueryString = newQueryString;
                try
                {
                    await context.Next(context.HttpContext);
                }
                finally
                {
                    context.HttpContext.Request.QueryString = originalQueryString;
                    context.HttpContext.Request.Path = originalPath;
                    context.HttpContext.Features.Set<IStatusCodeReExecuteFeature>(null);
                }
            });
```

We can go through both scenarios. You do need to have a /404 page on your website

- Put the above snippet above `app.UseUmbraco()`.
- Add a breakpoint in the function. When going to "test.jpg", you'll see that the function isn't called

Second scenario:
- Put the above snippet below `app.UseUmbraco()`.
- Add a breakpoint in the function. When going to "test.jpg", it'll call the function, but it'll not rewrite your request to /404

We also checked this with the Umbraco source code. We removed the UseStatusCodePages from the Umbraco source code and placed the snippet above UseUmbracoCoreMiddleware. This way when you go to "test.jpg", it'll call the function and also rewrite your request to the /404 page.

### Expected result / actual result

Ideally UseStatusCodePages should not be set within Umbraco. The programmer should set this themselves in their startup. The documentation on https://docs.microsoft.com/en-us/aspnet/core/fundamentals/error-handling?view=aspnetcore-6.0 also states that this function should not be used on production websites.

This is quite a long and technical issue. We can also go through this on a Discord call if that is possible. This is something we would love to see fixed as we have to make a work around for it now.

**Comment by DennisOptii** [comment]
+1 I agree with Patrick, UseStatusCodePages shouldn't be set in the Umbraco Builder. The programmer should have control over it.

**Comment by hannakfoo** [comment]
+1

**Comment by DennisOptii** [comment]
Can someone from Umbraco please respond? Can we do anything to help?

**Comment by PerplexDaniel** [comment]
@bergmania Sorry to tag you directly but I think you may be able to influence this and probably agree with us that Umbraco should not force this StatusCodePages middleware for everyone. If that line could be removed from UmbracoApplicationBuilder that would be great. A PR can be provided of course, just let me know. It is really just the removal of 1 line.

**Comment by patrickdemooij9** [comment]
As there hasn't been any activity on this in the last 3 months, I've gone ahead and created the PR to hopefully get some more attention to this issue. (https://github.com/umbraco/Umbraco-CMS/pull/12223)

**Comment by bergmania** [comment]
Hi.. Sorry for the lack of response.. 

Are we sure it does not work if you use the pre-pipeline filter?

```cs

 public class MyComposer : IComposer
  {
      public void Compose(IUmbracoBuilder builder)
      {
          builder.Services.Configure<UmbracoPipelineOptions>(options =>
          {
              options.AddFilter(new UmbracoPipelineFilter(nameof(MyComposer))
              {
                  PrePipeline = applicationBuilder =>
                  {
                      // execute your pipeline before Umbracos default required pipeline, e.g.
                      applicationBuilder.UseStatusCodePagesWithReExecute("/{0}");
                  }
              });
          });
      }
  }
```

**Comment by PerplexDaniel** [comment]
@bergmania Thanks for your response! Unfortunately that code snippet does not work in my v9 project. I see the code is executed, the PrePipeline action is also called but I still get the plain text 404 response. I hope @patrickdemooij9 can also try this to get a second opinion.

However since it's middleware it should probably be added _after_ Umbraco runs `.UseStatusCodePages()`, since we want to handle any empty 404 response before the plain text version does. That is, in a vanilla project the order needs to be like below if both are added to the pipeline:
```csharp
app.UseStatusCodePages();
// Needs to below the plain text version, so we can handle any 404 before it does.
app.UseStatusCodePagesWithReExecute("/{0}");
```

If you turn it around, the plain text StatusCodePages will have already generated the response and the ReExecute one does not do anything. So with a PrePipeline filter we actually get the incorrect one. On the other hand, I tried as a PostPipeline filter but that also does not work, probably because we then end up adding it way too late, after all the other middleware including Umbraco/MVC itself (didn't check when you run PostPipeline but likely at the very end).

**Comment by patrickdemooij9** [comment]
> Hi.. Sorry for the lack of response..
> 
> Are we sure it does not work if you use the pre-pipeline filter?
> 
> ```cs
>  public class MyComposer : IComposer
>   {
>       public void Compose(IUmbracoBuilder builder)
>       {
>           builder.Services.Configure<UmbracoPipelineOptions>(options =>
>           {
>               options.AddFilter(new UmbracoPipelineFilter(nameof(MyComposer))
>               {
>                   PrePipeline = applicationBuilder =>
>                   {
>                       // execute your pipeline before Umbracos default required pipeline, e.g.
>                       applicationBuilder.UseStatusCodePagesWithReExecute("/{0}");
>                   }
>               });
>           });
>       }
>   }
> ```

Yes, @PerplexDaniel is correct here. When using it on a PrePipeline, it'll not get called because the current Status Code Page middleware will catch it and throw it back into the middleware flow.

If we add it in the PostPipeline, it'll be behind the Umbraco specific middleware so we won't be able to send it back through the middleware flow to resolve the rewrite.

What we are currently doing is this:
![image](https://user-images.githubusercontent.com/11466511/161747153-13382282-0b3c-41e7-aaaf-5d1ab10842cb.png)
to disable the Status Code Page middleware, however then you are also not able to use UseStatusCodePagesWithReExecute on other places.

**Comment by bergmania** [comment]
Hmm.. Thanks for checking.. Removing it will be breaking to introduce in V9. The only option left is to make it configurable to turn off.

I think we need to inject a new `IOptions<WhatEver>` in `UmbracoApplicationBuilder` and use a property on `WhatEver` to specify not to run the `UseStatusCodePages`.

I don't think it is necessary to make configurable in config files `IOptions` should be good enough I think,,

**Comment by PerplexDaniel** [comment]
> Removing it will be breaking to introduce in V9

In what sense is it breaking? Existing code will still compile and run fine. I suppose only if people somehow are dependent on this middleware it would be breaking for them if it suddenly disappears but I struggle to come up with a use case for that. Without this middleware the status code is still sent in the response header, it's only the plain text body that is not there so any response handlers would continue to work fine they only check the status code. 

It is entirely possible I'm overlooking something but this middleware seems borderline useless and removing it shouldn't break anything.

Actually, Umbraco releases updates with breaking changes regularly (below is 9.3.0). Not sure why these are considered breaking but removing this middleware does not seem any more breaking than these :-)
![image](https://user-images.githubusercontent.com/24297947/161750892-88167937-9a11-42f4-98b2-50192f455827.png)

**Comment by PerplexDaniel** [comment]
@patrickdemooij9 Thanks for your workaround code, I didn't know it could be disabled like that.
And actually I can then use `UseStatusCodePagesWithReExecute` without issues afterwards. 
I use this code in Startup.cs:

```csharp
app.UseStatusCodePagesWithReExecute("/{0}");

app.UseUmbraco()
    .WithMiddleware(...)
    .WithEndpoints(...);

app.Use(async (ctx, next) =>
{
    await next();
    if (ctx.Features.Get<IStatusCodePagesFeature>() is { } statusCodePages)
    {
        statusCodePages.Enabled = false;
    }
});
```

**Comment by patrickdemooij9** [comment]
@PerplexDaniel That actually is strange to me, as the `IStatusCodePagesFeature` should also disable your `UseStatusCodePagesWithReExecute` as it uses the same middleware as `UseStatusCodePages` and thereforce has the same check on the feature.
![image](https://user-images.githubusercontent.com/11466511/161757288-be62094a-a1aa-4bde-a082-b3f722c4b5a8.png)

Are you sure that it works because of the `UseStatusCodePagesWithReExecute` or that you maybe have something in your web.config to handle 404's for files?

**Comment by PerplexDaniel** [comment]
Yeah it is a bit confusing but if I remove only the line `app.UseStatusCodePagesWithReExecute("/{0}");` it no longer works and I get the default 404 of the browser (since indeed StatusCodePages is disabled). If i put that line back it returns the content of `/404` correctly when requesting some non existing file (e.g. `/notfound.txt`). There is no 404 handling configured in the web server (tested on Kestrel).

**Comment by bergmania** [comment]
> > Removing it will be breaking to introduce in V9
> 
> In what sense is it breaking? [...]

Cool, I looked a bit more into it and I think it is safe to remove from the pipeline. 

The `app.UseDeveloperExceptionPage();` should help people doing development anyway. And Umbraco ships with a custom 404 page. So 404 should also not be a problem. 

We have a couple of related issues we will look into in the same go.

**Comment by nul800sebastiaan** [comment]
Fixed in https://github.com/umbraco/Umbraco-CMS/pull/12223

**Comment by croban** [comment]
Did I understood correct with this fix I will be able to create custom 404? 
e.g.
app.UseStatusCodePagesWithReExecute("/Error/{0}");
Which magic I must do that this works, beside update to 9.5?
