### ISSUE TITLE
Wrong culture set for variation context when a macro is presented in backoffice

### ISSUE THREAD

**Issue by robgha01** [umbraco/Umbraco-CMS#11863]
### Which *exact* Umbraco version are you using? For example: 9.0.1 - don't just write v9

8.17.1

### Bug summary

The variation context uses the wrong culture when macro output is rendered in the backoffice using "GetMacroResultAsHtmlForEditor"

to fix this one need to set the VariationContext to the correct culture ex i added this in "PartialViewMacroPage.cs":

```
var umbCulture = Request.Headers["x-umb-culture"]; // This fixes the bug with umbraco not able to chose the correct culture in backoffice when rendered from a macro
if (!(Request.Url is null) && Request.Url.ToString().Contains("GetMacroResultAsHtmlForEditor") &&  string.IsNullOrWhiteSpace(umbCulture) == false)
{
 var variationContextAccessor = Current.Factory.GetInstance<IVariationContextAccessor>();
 variationContextAccessor.VariationContext = new VariationContext(umbCulture);
}
```

The above only works when the macro is presented normally, when a SplitView is used it fails because of this related bug: https://github.com/umbraco/Umbraco-CMS/issues/11862

### Steps to reproduce

1. Create a content type "A" with a grid property
2. Create a content type "B" with a regular text property
2. Create a macro with a Content Picker
3. Create both content types "A" and "B" in the tree make sure B has translations for two cultures
4. Place the macro and pick the content "B"
5. In the macro view read and get the content "B" using the macro property value from "Content Picker"
6. Use the content B.Value("TheProperty") and output it

### Expected result / actual result

What is expected is Content "B" TheProperty value should output the correct language variation value.
Actual result: It outputs the language variation of the first SplitView side.

---
_This item has been added to our backlog [AB#25506](https://dev.azure.com/umbraco/243e7927-03b2-44e2-908f-d4ac7ea5daaa/_workitems/edit/25506)_

**Comment by kjac** [comment]
Hi @robgha01,

Thank you for reporting 💪 I have reproduced and created a fix in #13653
