### ISSUE TITLE
Redirect URL Manager not using custom URL provider

### ISSUE THREAD

**Issue by leehowarth** [umbraco/Umbraco-CMS#11866]
### Which *exact* Umbraco version are you using? For example: 9.0.1 - don't just write v9

9.0.1

### Bug summary

Redirect URL Management for content is ignoring a custom Url Provider. 

### Specifics

We have created a custom URL Provider, Content Finder and Segment provider for a custom content type. These are all working  correctly and the content pages show as desired on the correct URL. However if you change some content that causes the URL to be recalculated to a new URL the redirect management will fail to use the custom URL provider and the URL generated for the redirect (stored in DB table - umbracoRedirectUrl) is incorrect for the previous URL.  It appears like its just using the standard DefaultUrlProvider and taking the standard segments. 

An example custom url we have here generated via a custom URL provider publishes and routes fine with the custom content finder. 
![image](https://user-images.githubusercontent.com/917718/149557569-d1a30ad3-ae90-4899-888d-6afd7c2a5c67.png)

However when this is changed so a new URL should be used the old url is incorrect calculated for the redirect and the custom format is not used. It does appear it picks up on the custom segment provider but not the custom url provider. 
![image](https://user-images.githubusercontent.com/917718/149557655-a57765cc-d396-4ecc-8f6a-23fbfe064735.png)

### Steps to reproduce

Create a custom url provider and attempt to have a custom url format for the old url redirects of a custom content type. 

### Expected result / actual result

Custom URL provider to be used when calculating redirects used for old redirect urls of a content item.

**Comment by kjac** [comment]
Hi @leehowarth,

Thanks for reporting this - and sorry for the late response.

The URL tracker only tracks URL segments, which means any custom URL provider is not in play when calculating redirect URLs. This is by design; redirect tracking only concerns itself with relative paths.

The default URL provider however applies custom segment providers when calculating content URL - at least if one makes sure to insert the custom segment providers before the default one.

For anyone stumbling upon this, here is some code for a custom segment provider and how to activate it:

```csharp
public class MyUrlSegmentProvider : IUrlSegmentProvider
{
    private readonly IShortStringHelper _shortStringHelper;

    public MyUrlSegmentProvider(IShortStringHelper shortStringHelper) => _shortStringHelper = shortStringHelper;

    public string? GetUrlSegment(IContentBase content, string? culture = null) =>
        GetUrlSegmentSource(content, culture)?.ToUrlSegment(_shortStringHelper, culture);

    private static string? GetUrlSegmentSource(IContentBase content, string? culture)
    {
        var source = content is IContent { Edited: true } document && document.GetPublishName(culture) != null
            ? document.GetPublishName(culture)
            : content.GetCultureName(culture);

        return $"{source}-my-segment";
    }
}

public static class MyUmbracoBuilderExtensions
{
    public static IUmbracoBuilder AddMyUrlSegmentProvider(this IUmbracoBuilder builder)
    {
        builder.UrlSegmentProviders().Clear();
        builder.UrlSegmentProviders().Append<MyUrlSegmentProvider>();
        return builder;
    }
}
// in Startup.cs:
public void ConfigureServices(IServiceCollection services)
{
    services.AddUmbraco(_env, _config)
        .AddBackOffice()
        .AddWebsite()
        .AddComposers()
        .AddMyUrlSegmentProvider()
        .Build();
}

```
