### ISSUE TITLE
RTE Toolbar hidden under Tabs when pane is scrolled

### ISSUE THREAD

**Issue by craigs100** [umbraco/Umbraco-CMS#11870]
### Which *exact* Umbraco version are you using? For example: 9.0.1 - don't just write v9

9.2.0

### Bug summary

Top ¾ of the RTE Toolbar is hidden behind Tabs when the editing pane is scrolled.

### Specifics

As can be seen in the screenshot, if Tabs are in use and the RTE is longer than the browser window the toolbar appears to "stick" at the top of the Tabs rather than the bottom when the page is scrolled. Causing ¾ of the toolbar to be hidden.

![20220115_umbraco_rte_screenshot](https://user-images.githubusercontent.com/1143883/149640224-457d9999-f955-48f3-80ec-1da384d3e936.png)

### Steps to reproduce

Create a DocType with a Tab (not a group) containing an RTE with it's height set to a value which would cause it to scroll in the editing pane. (Reduce the vertical size of your browser to simulate if necessary)

Create a page with the DocType and notice that when the pane is scrolled down while the RTE is in view, the RTE's toolbar sticks half behind the Tabs rather than completely below the Tabs making it unusable.

### Expected result / actual result

Expected the Toolbar to remain fully in view while any part of it's content pane was in view

Actually, ¾ of the Toolbar is hidden behind the Tabs.

I'm guessing that the original intention was to stick the toolbar at the top of the RTE while any part of the RTE content pane was in view. I might be wrong.

**Comment by markadrake** [comment]
I submitted a pull request (#11901) in an effort to fix this behavior. Would love a second or third set of eyes that the behavior is correct after my fix. Thanks!
