### ISSUE TITLE
Umbraco should ship with latest Examine versions

### ISSUE THREAD

**Issue by Shazwazza** [umbraco/Umbraco-CMS#11871]
### Which *exact* Umbraco version are you using? For example: 9.0.1 - don't just write v9

8.17.1

### Bug summary

The nuget package doesn't ship with the latest Examine which contains a few critical bug fixes. For example: https://github.com/Shazwazza/Examine/issues/266 (and others). It should ship with 1.2.2.

### Steps to reproduce

See 
* https://github.com/Shazwazza/Examine/issues/266
* https://github.com/Shazwazza/Examine/issues/245

**Comment by nul800sebastiaan** [comment]
Thanks @Shazwazza - done in 4382868f8248a3e7ce30619a68ab609d9f92dc8c

**Comment by MatsLimetta** [comment]
![image](https://user-images.githubusercontent.com/58428362/173412436-bad1a2de-045d-4cdd-ac07-a0399c9ba9a1.png)
The difference when looking  at the indexes in Luke. The one on the left is the 8.17 external index and the one on the right is the 8.18 external index. (the first word  on the left is "äta" that has been tokenized as "ata", while on the right you have "långsam" and "jämställdhet" tokenized with å and ä).

Both project are on Umbraco Cloud if that matters.

I noticed this when the search stopped working (I had a simple replace of åäö with aao to get the hits I wanted, but that stopped working after upgrading Umbraco.

**Comment by Shazwazza** [comment]
The default analyzer shipped with Umbraco is [CultureInvariantWhitespaceAnalyzer](https://github.com/Shazwazza/Examine/blob/dev/src/Examine.Lucene/Analyzers/CultureInvariantWhitespaceAnalyzer.cs) This decision was made years ago in order to allow content editors to search without having to worry about dialects. So someone can search on ata and not require äta. This is done by a process called Ascii folding. 

If you want to require searching using the original dialect, you can just change the default analyzer for the internal index to WhitespaceAnalyzer

**Comment by abjerner** [comment]
Prior to Examine being upgraded, it also depended on whether the index had been rebuild after restart. Something like this:

- Restart the site
  - Search for "rød". 0 results
  - Search for "rod" This returns the correct results.

- Rebuild the index
  - Search for "rød" This returns the correct results.
  - Search for "rod" This returns the correct results.

I think after the update it's no longer possible so search for "rod" - only "rød". This aligns with what @MatsLimetta is writing (we had our [own replace logic](https://github.com/skybrud/Skybrud.Umbraco.Search/blob/v3/latest/src/Skybrud.Umbraco.Search/SearchHelper.cs#L347)):

> I noticed this when the search stopped working (I had a simple replace of åäö with aao to get the hits I wanted, but that stopped working after upgrading Umbraco.

If I understand you correctly @Shazwazza, both "rød" and "rod" should now return results matching "rød", but this doesn't match what we're experiencing.

**Comment by Shazwazza** [comment]
No ascii folding "converts" chars, see https://lucene.apache.org/core/4_9_0/analyzers-common/org/apache/lucene/analysis/miscellaneous/ASCIIFoldingFilter.html

This is the filter used in [CultureInvariantWhitespaceAnalyzer](https://github.com/Shazwazza/Examine/blob/dev/src/Examine.Lucene/Analyzers/CultureInvariantWhitespaceAnalyzer.cs)

To maintain both sets of strings would require that PreserveOriginal is true - something I have not tried but is a very easy change. I didn't know this was an option until now so def worth investigating. I've also just realized there's a bug in the CultureInvariantStandardAnalyzer which isn't using the AsciiFoldingFilter at all which is it's main intention.

**Comment by Shazwazza** [comment]
Hi all, I've published Examine 3.0.1 with a fix to the CultureInvariantStandardAnalyzer here https://github.com/Shazwazza/Examine/releases/tag/v3.0.1

I didn't change the 'PreserveOriginal' value in the AsciiFoldingFilter but the tests show that searching on both "rod" and "rød" work, see https://github.com/Shazwazza/Examine/blob/release/3.0/src/Examine.Test/Examine.Lucene/Search/AnalyzerTests.cs

When rød is indexed, it is ascii folded, so it is indexed as "rod". When "rod" is searched for, it will return both records because both items in the index are not indexed as "rod". When "rød" is searched for, the search term is ascii folded into "rod" and therefore both results are returned since essentially it is searching with the term "rod".
