### ISSUE TITLE
Umbraco Cloud 9 user permissions in Media section

### ISSUE THREAD

**Issue by sandervandepas** [umbraco/Umbraco-CMS#11895]
### Which *exact* Umbraco version are you using? For example: 9.0.1 - don't just write v9

9.1.2

### Bug summary

Hi,

I've a question about the user permissions in Umbraco Cloud 9.

We have the following Site structure:

- Website A (main site)
- Website B
- Website C

And the following Media structure:
- Website A
- Website B
- Website C
- Shared Media

Each Website has it's own UserGroup with startnodes (content and media) to their own website.
The intention is that each user belongs to a website group AND has also the possibility to use Media data from the Shared Media folder.
So I've added the specifiic user to a Website group (with most of all the default permissions) AND added the Shared Media Group, but only with the "Browse Node" property so they can't add, change or delete these media items.

But when I login as one of these specific users, they have full rights to the Shared Media section which they shouldn't have.

Is this an Umbraco bug or do I need another setup for this?

I've attached some screenshot to declare a little bit more.

Hope to hear from you as soon as possible.

Thanks in advance.

Kind regards,

Sander van de Pas
iO

![1  Site structure](https://user-images.githubusercontent.com/75935291/150648252-916fd974-afd5-43a0-adcf-3833283f5caa.png)
![2  Media structure](https://user-images.githubusercontent.com/75935291/150648255-ebd8740d-0c6b-4b39-b52e-f9c3e1ab9968.png)
![3  User groups](https://user-images.githubusercontent.com/75935291/150648262-72dd3b11-2632-4492-8cb5-1b3e0f499d0a.png)
![4  Website user group](https://user-images.githubusercontent.com/75935291/150648264-beb3dbba-def4-4b04-a948-144d752be6f9.png)
![5  Shared media group](https://user-images.githubusercontent.com/75935291/150648269-e370d2f7-06cf-4a40-947c-8a751ba8bcf6.png)
![6  User](https://user-images.githubusercontent.com/75935291/150648273-828f8ab4-166e-4097-8be0-8100be612739.png)
![7  Logged in Website user in Media section](https://user-images.githubusercontent.com/75935291/150648277-7a75271b-a66c-4649-8a65-d837c7d1c3e1.png)

### Steps to reproduce

1. Create at least 2 sites - attachment 1
2. Create at least 2 website folder in the Media section and 1 Shared Media folder- attachment 2
3. Create at least 2 UserGroups (with most of all the default permissions), 1 for Website 1 and one for Website 2 and give them Content and Media startnodes to their own website- attachment 3 + 4
4. Create another UserGroup "Shared Media" (only with the "Browse Node" permission)- attachment 5
5. Add a different user to both Website UserGroups and also add them to the Shared Media group- attachment 6
6. Login as a user of Website 1 or 2
7. Go to the Shared Media Folder
8. See that you can Delete a Media item from the Shared Media folder what should not be possible due to your Shared Media User Group permissions.- attachment 7

### Expected result / actual result

Actually the user for Website 1 or 2 can Create, Move and Delete an image below the Shared Media folder, but due to the Shared Media UserGroup permissions (only Browse Node) they should not be able to do this.

**Comment by kjac** [comment]
Hi @sandervandepas,

Thank you for reaching out... apologies for the belated response.

Unfortunately what you're trying to do here is not supported by Umbraco. The group permission setup applies to content, not media, as it is subtly hinted by the small-ish headline:

![image](https://user-images.githubusercontent.com/7405322/211833012-508c0639-e549-488b-9eb5-ee77fce55927.png)

You can limit the media access for users using media start nodes as you have already figured out, but there are no additional options for tweaking permissions on a group basis. The users will have full access to everything below the media start nodes defined by their groups.
