### ISSUE TITLE
Delete Block Throws Exception

### ISSUE THREAD

**Issue by argentini** [umbraco/Umbraco-CMS#11905]
### Which *exact* Umbraco version are you using? For example: 9.0.1 - don't just write v9

9.2.0

### Bug summary

Deleting a block, even if not used on content, yields an exception tied to the foreign key in the new version cleanup policy table.

### Specifics

When deleting a block, even if unused, the following exception is thrown:

```
System.Data.SqlClient.SqlException (0x80131904): The DELETE statement conflicted with the REFERENCE constraint "FK_umbracoContentVersionCleanupPolicy_cmsContentType_nodeId". The conflict occurred in database "coursabi-website", table "dbo.umbracoContentVersionCleanupPolicy", column 'contentTypeId'.
The statement has been terminated.
   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString)
   at System.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean async, Int32 timeout, Task& task, Boolean asyncWrite, SqlDataReader ds)
   at System.Data.SqlClient.SqlCommand.InternalExecuteNonQuery(TaskCompletionSource`1 completion, Boolean sendToPipe, Int32 timeout, Boolean asyncWrite, String methodName)
   at System.Data.SqlClient.SqlCommand.ExecuteNonQuery()
   at Umbraco.Cms.Infrastructure.Persistence.FaultHandling.RetryPolicy.ExecuteAction[TResult](Func`1 func)
   at NPoco.Database.ExecuteNonQueryHelper(DbCommand cmd)
   at NPoco.Database.Execute(String sql, CommandType commandType, Object[] args)
ClientConnectionId:d3543050-deaf-4868-9bdc-a7edece8acea
Error Number:547,State:0,Class:16

```
<img width="1603" alt="Screen Shot 2022-01-25 at 1 53 19 PM" src="https://user-images.githubusercontent.com/1504331/151040660-461605f2-fb64-4409-976d-0aecf47ce30e.png">

### Steps to reproduce

Create a block, then delete the block

### Expected result / actual result

Block should be deleted if not used

**Comment by AndyButland** [comment]
I had a quick look at this and I wasn't able to replicate (at least with the latest code).  Checking the code we aren't explicitly deleting from that table, but I do see a "cascade delete" set up so that should remove the value in that related table.  And for me it does seem to.

I do notice that other than this in instance though, we do explicit deletes rather than relying on a cascade, so am wondering if this maybe isn't reliable for all databases (and hence that's why they've not been used before).

Would you mind updating @argentini please with the database type you are using (i.e. SQL Server, SQL CE or LocalDb)?  Thanks.

**Comment by argentini** [comment]
Hey Andy, thanks for the info. I'm using SQL Server 15.0.2080.9, and the user account is db owner.

**Comment by AndyButland** [comment]
Thanks, I'm running the same.  Can I just ask one more thing, that we have a look to see if the cascade option has been installed on your database?  It is on mine and looks like it should be automatically set by the migration.

If you expand the database in SQL Management Studio, then expand _Tables > umbracoContentVersionCleanupPolicy > Keys_ and right-click on `FK_umbracoContentVersionCleanupPolicy_cmsContentType_nodeId` and select _Script Key As..._  If I do that I get this result:

```
USE [UmbracoCMS]
GO

ALTER TABLE [dbo].[umbracoContentVersionCleanupPolicy]  WITH CHECK ADD  CONSTRAINT [FK_umbracoContentVersionCleanupPolicy_cmsContentType_nodeId] FOREIGN KEY([contentTypeId])
REFERENCES [dbo].[cmsContentType] ([nodeId])
ON DELETE CASCADE
GO

ALTER TABLE [dbo].[umbracoContentVersionCleanupPolicy] CHECK CONSTRAINT [FK_umbracoContentVersionCleanupPolicy_cmsContentType_nodeId]
GO
```

And I'm wondering if you see the same or if you are missing the `ON DELETE CASCADE` part.

**Comment by argentini** [comment]
Hey Andy, I get this:

```
ALTER TABLE [dbo].[umbracoContentVersionCleanupPolicy]  WITH NOCHECK ADD  CONSTRAINT [FK_umbracoContentVersionCleanupPolicy_cmsContentType_nodeId] FOREIGN KEY([contentTypeId])
REFERENCES [dbo].[cmsContentType] ([nodeId])
GO
ALTER TABLE [dbo].[umbracoContentVersionCleanupPolicy] CHECK CONSTRAINT [FK_umbracoContentVersionCleanupPolicy_cmsContentType_nodeId]
GO

```

**Comment by argentini** [comment]
I know why I don't have the constraint, and it's not an Umbraco issue after all. So this issue can be resolved. Thanks for the troubleshooting help! At least we confirmed that Umbraco isn't misbehaving in this regard :)

**Comment by AndyButland** [comment]
Glad to hear you've resolved it, but if you don't mind, could you share why you don't have the constraint and why you know it's not an Umbraco issue?  As I mentioned earlier, it should have been created via the migration from an older version or the initial database setup for a new one, so we'd like to make sure there are no issues there by understanding what's happened in your case.

**Comment by argentini** [comment]
It has to do with a third party database tool. I'm sure it isn't Umbraco.

-- 

M.

**Comment by AndyButland** [comment]
Thanks, hence will close this then.
