### ISSUE TITLE
ServerRegistrationService.TouchServer uses the DB instead of IServerRoleAccessor to determine IsSchedulingPublisher

### ISSUE THREAD

**Issue by digbyswift** [umbraco/Umbraco-CMS#11928]
### Which *exact* Umbraco version are you using? For example: 9.0.1 - don't just write v9

9.1.2

### Bug summary

When the IServerRoleAccessor of an application instance is set programmatically, (i.e. `using SetServerRegistrar()`) it should be used by `ServerRegistrationService.TouchServer` method call to determine whether the calling instance is the "SchedulingPublisher". However, the CurrentServerRole is not used and the DB is instead used to determine the server role. This results in the wrong data being written to the [umbracoServer] table.

### Specifics

We have an Azure-based load-balanced architecture where the CMS is hosted as a single instance and the front end (FE) is scaled out as multiple instances.

We have noticed that often the [umbracoServer].[isSchedulingPublisher] value for each of the instances is incorrect. For example, the CMS instance record will have [isSchedulingPublisher] = 0 and one of the FE instances will have [isSchedulingPublisher] = 1. This is even though `SetServerRegistrar` is used to define the `IServerRoleAccessor` programmatically for each instance at startup.

In `ServerRegistrationService.TouchServer()` the code checks the DB to see if any records exist in the [umbracoServer] table with [isSchedulingPublisher] = 1. If there aren't, then the current instance is set as the `ScheduledPublisher` which is obviously correct if the instance is the CMS. 

It therefore appears that the issue arises when a FE instance's `TouchServerTask` hosted service is initialized before the equivalent in the CMS instance and the FE is therefore recorded as the ScheduledPublisher incorrectly. This is quite common even though in our deployment pipelines the CMS instances are swapped before the FE instances get significantly more traffic than the CMS.

### Solution?

This would presumably be solved if the `IServerRoleAccessor` value is checked first and used if set, before the DB.

### Steps to reproduce

Using a clean install and following the Azure load balancing guidelines:

1. Deploy the install to an Azure App Service, making sure that `IUmbracoBuilder.SetServerRegistrar()` is used to register the instance as `ServerRole.Subscriber`.
2. Deploy the install to another Azure App Service, making sure that `IUmbracoBuilder.SetServerRegistrar()` is used to register the instance as `ServerRole.SchedulingPublisher`.
3. Check the data written to the [umbracoServer] table.

### Expected result / actual result

Regardless of the order in which the `TouchServerTask` on each instance initializes, I would expect the `ServerRegistrationService.TouchServer()` to honour the value set by `IUmbracoBuilder.SetServerRegistrar()`.

**Comment by nikolajlauridsen** [comment]
Hi, thanks for the very detailed report :) 

I looked in to this yesterday, and you're right, the touch server task does not respect the `IServerRoleAccessor`. However, that table is only used if the `ElectedServerRoleAccessor` is used, it becomes completely irrelevant once you replace that with your own `IServerRoleAccessor` implementation. 

I've done a fix in #11926 which disables the `TouchServerTask` when the role accessor has been replaced

**Comment by digbyswift** [comment]
@nikolajlauridsen That makes sense, thanks for confirming! Happy to close this.
