### ISSUE TITLE
In v9 you can no longer register a member without logging them in

### ISSUE THREAD

**Issue by sussexrick** [umbraco/Umbraco-CMS#11923]
### Which *exact* Umbraco version are you using? For example: 9.0.1 - don't just write v9

9.2.0

### Bug summary

In v8 using `UmbRegisterController.HandleRegisterMember` you could set `RegisterModel.LoginOnSuccess = false` to prevent the member being automatically logged in if registration is successful. This supports the common requirement to confirm registration with an activation email before allowing a login. In v9 this option is gone.

### Specifics

The code was lost in [this commit](https://github.com/umbraco/Umbraco-CMS/commit/8ea88a980a3e3ba590576dab5c7746117f2d9b9e#diff-a68f40250f629d9ec2de1105e5fbaeaf56c721b9ac053b551d2dfbd80ec6abc0):

* the `RegisterModel.LoginOnSuccess` property was removed in `RegisterModel.cs`
* the login behaviour was hard-coded to true on line 63 of `src/Umbraco.Web.Website/Controllers/UmbRegisterController.cs`

### Steps to reproduce

Create a surface controller than inherits from `Umbraco.Cms.Web.Website.Controllers.UmbRegisterController` and a method that accepts a `Umbraco.Cms.Web.Website.Models.RegisterModel`.

Try to set the `model.LoginOnSuccess` property - you can't.

Call the `HandleRegisterMember` method with the instance of `RegisterModel` populated with details of a new member. The member is logged in.

---
_This item has been added to our backlog [AB#25550](https://dev.azure.com/umbraco/243e7927-03b2-44e2-908f-d4ac7ea5daaa/_workitems/edit/25550)_

**Comment by kjac** [comment]
Hi @sussexrick,

Thanks a lot for reaching out. Sorry for the quite late response.

This is indeed annoying. I have submitted a fix in https://github.com/umbraco/Umbraco-CMS/pull/13659

**Comment by kjac** [comment]
Closed by https://github.com/umbraco/Umbraco-CMS/pull/13659
