### ISSUE TITLE
App_Plugins language files not picked up on linux envoronment

### ISSUE THREAD

**Issue by niekvanderreest** [umbraco/Umbraco-CMS#11929]
### Which *exact* Umbraco version are you using? For example: 9.0.1 - don't just write v9

9.1.2

### Bug summary

When publishing to a Linux environment the localization files aren't picked up by the LocalizationService. 
UNLESS the folder starts with a capital letter i.e "Lang" instead of "lang"

### Specifics

You can easily check which translations are picked up by navigating to endpoint: /umbraco/localizedText

### Steps to reproduce

Install a custom package (such as seo-checker) on your site and publish to a linux environment, in our case a linux app-service on Azure

### Expected result / actual result

Expected that translations from the specific localization files are present in /umbraco/localizedText result and visible inplace of placeholders in backoffice.
Actual, placeholders are still visible i.e. [seochecker]

**Comment by nul800sebastiaan** [comment]
This is correct! Unfortunately we didn't get the consistency for the `lang` / `Lang` directories quite right. However, this is not documented correctly, so I've asked for the docs to be updated to make a note of this requirement: https://github.com/umbraco/UmbracoDocs/pull/3767
