### ISSUE TITLE
MiniProfiler custom steps not showing in the log

### ISSUE THREAD

**Issue by Jay-umbr** [umbraco/Umbraco-CMS#11932]
### Which *exact* Umbraco version are you using? For example: 9.0.1 - don't just write v9

9.2.0

### Bug summary

When using MiniProfiler we used to be able to add custom steps to it, and these would show up in the log/UI.
That does not seem to be the case for v9, at least not when redirecting after a post method.

### Steps to reproduce

Code used in a submit method on a form (IProfiler injected into the SurfaceController):

```
public IActionResult Submit(BrokenFormModel model)
        {
            using (_profiler.Step("Time to sleep"))
            {
                System.Threading.Thread.Sleep(4000);
            }

            return RedirectToCurrentUmbracoPage();
        }
```

### Expected result / actual result

Expected result (taken with similar code from 8.17)
![image](https://user-images.githubusercontent.com/56038614/152321826-26c5a356-0df9-4eab-8606-921b64f4776d.png)

Actual result
![image](https://user-images.githubusercontent.com/56038614/152321948-b273f43a-50b5-4a33-87ee-528ae77e6df8.png)

**Comment by nikolajlauridsen** [comment]
Fixed in #11939 🎉
