### ISSUE TITLE
Member last login date not being set

### ISSUE THREAD

**Issue by antonysmith-mando** [umbraco/Umbraco-CMS#11931]
### Which *exact* Umbraco version are you using? For example: 9.0.1 - don't just write v9

8.15.3/8.17.1/9.2.0

### Bug summary

In Umbraco 8.1.5, our member login functionality used to set the last login property of the member. Since upgrading to 8.15.3, this no longer happens (unless the user has first had a failed login attempt).

I have been able to reproduce this behaviour on 8.17.1 and 9.2.0, though on 9.2.0 I can't get the last login date to be set even following a failed login attempt.

### Specifics

We have a login method for members that calls `Membership.ValidateUser()`. This results in a call to `UmbracoMembershipProvider.PerformValidateUser()`.

In [8.1.5](https://github.com/umbraco/Umbraco-CMS/blob/release-8.1.5/src/Umbraco.Web/Security/Providers/UmbracoMembershipProvider.cs#L599), this method would always result in a call to `MemberService.Save()` (where the version is >= 7.3.0.0).

In [8.15.3](https://github.com/umbraco/Umbraco-CMS/blob/release-8.15.3/src/Umbraco.Web/Security/Providers/UmbracoMembershipProvider.cs#L609), this only happens if a 'full save' is required. Otherwise, `MemberService.SetLastLogin()` is called instead.

It looks like this has been the case since v8.6.5, when the following PR was merged to resolve some perf issues in this area: https://github.com/umbraco/Umbraco-CMS/pull/8525

`MemberService.SetLastLogin()` calls `MemberRepository.SetLastLogin()`, in which a SQL query is run to retrieve the ID of the umbracoMemberLastLogin property for the user, which is then used to update its value. For members that don't have a value set for this property, no date is set.

If a 'full save' is forced (i.e. by providing an incorrect password during login) then the next login will cause the last login date to be set (in v8).

In v9, I see the same behaviour re: the last login date not being set on login, but can't set it via an unsuccessful login first either.

I've been able to work around the issue by explicitly setting a last login date on members when they're registered (via `MemberService.CreateMember()`), but wonder if it's something that should be fixed, particularly as it did work prior to 8.6.5.

I'm wondering if we can check whether the select query returns an ID before doing the update and, if not, inserting a row into cmsPropertyData. Though I'm not sure if that's a) possible or b) going to cause a big perf issue in an area that perf was originally an issue hence the change that was made!

### Steps to reproduce

- Install Umbraco 8.1.5
- Run installer and use starter site with SQL Server Compact db
- Create register/login forms. Register uses IMemberService.CreateMember(), login uses Membership.ValidateUser()
- Register as user
- Login as user
- Observe that last login date is set

- Run same steps as above for Umbraco 8.15.3/8.17.1
- After logging in as user, last login date is not set
- Last login date can be set by first providing an incorrect password, before then providing the correct password

- Install Umbraco 9.2.0 (with --SqlCE flag)
- Run installer and use SQL Server Compact db
- Install 'The Starter Kit' package
- Create register/login forms. Register uses IMemberService.CreateMember(), login uses IMemberSignInManager.PasswordSignInAsync()
- Register as user
- Login as user
- Observe that last login date is not set
- Unsuccessfully login as user
- Login as user
- Observe that last login date is still not set

### Expected result / actual result

**Expected**: Last login date is set when a member logs in, irrespective of whether they've already got a value set or not

**Actual**: Last login date is only set in v8 where a member first has a failed login attempt. Last login date is seemingly not set at all in v9.

---
_This item has been added to our backlog [AB#17125](https://dev.azure.com/umbraco/243e7927-03b2-44e2-908f-d4ac7ea5daaa/_workitems/edit/17125)_

**Comment by nul800sebastiaan** [comment]
Hi there, might be an unintentional change there which can be fixed in v9, for v8 we recommend using `MembershipHelper.Members.Login` which sets the last login data correctly.

I just had a look in v9 and there we seem to set it correctly as well. We end up in [`UmbracoSignInManager.HandleSigning`](https://github.com/umbraco/Umbraco-CMS/blob/v9/contrib/src/Umbraco.Web.Common/Security/UmbracoSignInManager.cs#L323) which updates the login date upon success. 

We're no longer fixing old regressions in v8 (meaning they were introduced before v8.15.0) I'm afraid. :-) Umbraco 8.18.0, out in RC now, is entering end of life (EOL) phase, where we only fix recent regressions, security issues and necessary dependency updates going forward. 

So I'll close this issue and encourage you to use [`Members.Login`](https://github.com/umbraco/Umbraco-CMS/blob/v8/contrib/src/Umbraco.Web/Security/MembershipHelper.cs#L304) in v8 or of course work around it by setting the date yourself but that causes an additional query to be sent to the database so it will be less performant.

**Comment by antonysmith-mando** [comment]
Thanks for getting back to me @nul800sebastiaan.

Completely understand re: no longer fixing old regressions in v8 and appreciate your guidance re: an alternative.

In terms of the MembershipHelper - were you referring to [this](https://our.umbraco.com/documentation/reference/querying/membershiphelper/)?

I have tried this in 8.17.1 and can still see the issue. I've injected `MembershipHelper` to the controller and called the `.Login()` method in place of `Membership.ValidateUser()` but on successful login I still don't see the last login date within the CMS. As with my description above, if I first force a login failure with an incorrect password then I am then able to see the last login date after a successful login.

Looking at `MembershipHelper.Login()`, it calls `MembershipProvider.ValidateUser()` which results in the same call to `UmbracoMembershipProvider.PerformValidateUser()` that I documented above.

My workaround of setting the last login date during registration works for us because we're setting a number of custom properties during registration and having to save the user anyway. However, it'd be good if I could get to the bottom of why I can't get the date to be set with the built in functionality if it should be working.

My updated code (in a clean install with only the Starter Kit installed) is now:

```
public class LoginFormSurfaceController : SurfaceController
{
    private readonly MembershipHelper _membershipHelper;

    public LoginFormSurfaceController(MembershipHelper membershipHelper)
    {
        _membershipHelper = membershipHelper;
    }

    [HttpPost]
    public ActionResult Login(LoginViewModel viewModel)
    {
        if (_membershipHelper.Login(viewModel.Email, viewModel.Password))
        {
            return Redirect("/");
        }

        return Redirect("/Error");
    }
}
```
In terms of v9, following through the code that you've pointed to, after the date is set there's a call to `UserManager.SaveAsync()` in which we call the `SetLastLogin()` method if the memberChangeType is LoginOnly: https://github.com/umbraco/Umbraco-CMS/blob/2abf455abf2e23f73cf3c51497bcfdcc4274e4cb/src/Umbraco.Infrastructure/Security/MemberUserStore.cs#L182

This is the SetLastLogin() method that I think will only work if the last login data already exists (due to the update being performed on the result of the select).

Sorry if I'm missing something in either case!

**Comment by antonysmith-mando** [comment]
A further update to this, I've been able to determine why I wasn't able to reproduce the v8 behaviour in v9 re: being able to see a last login date set after a failed login attempt.

I was calling `PasswordSignInAsync` with lockoutOnFailure = false. This meant that the number of failed password attempts was not being incremented. I've updated this to be true, and now the failed password attempt count increments following an unsuccessful login. This means that a subsequent successful login triggers a 'full save' and therefore sets the last login date.

So I'm now seeing consistent behaviour between v8 & v9, which is that the last login date will only be set on successful login if a previous unsuccessful login has occurred.

**Comment by nul800sebastiaan** [comment]
> In terms of the MembershipHelper - were you referring to this? 

Yes, which works for me. Weird since no full save is required, you will end up in the `else` which then sets the login date properly, so you'll probably need to debug the source to figure out why that doesn't work for you.

That said, to be honest, I didn't look at v9 and indeed it seems to be a problem, don't see it updating at all so we should fix that for sure. Video below is for 9.1.1 but I upgraded to 9.2.0 after and it also failed to update the date.


https://user-images.githubusercontent.com/304656/152160854-a52810df-72b0-4117-8d2c-65afd3d2afa0.mp4

**Comment by elit0451** [comment]
This issue should be fixed for both Umbraco 8 and 9
