### ISSUE TITLE
9.3.0-rc - Block List editor error when block removed

### ISSUE THREAD

**Issue by konius** [umbraco/Umbraco-CMS#11942]
### Which *exact* Umbraco version are you using? For example: 9.0.1 - don't just write v9

9.3.0-rc

### Bug summary

When a block gets removed from a Block list configuration all the properties using the datatype become broken due to error.

### Steps to reproduce

1. Create Block List data type
2. Add elements as options
3. Add datatype on a document type as a property
4. Add content using the elements
5. Remove the element from Block list data type
6. Block List editor is now broken for the property

![Screenshot 2022-02-05 114835](https://user-images.githubusercontent.com/3933562/152636824-413625d8-5bc0-438f-89d8-c777fef43883.jpg)
![Screenshot 2022-02-05 114943](https://user-images.githubusercontent.com/3933562/152636825-20b64d6e-5bb1-4216-9d8a-09023e4a3164.jpg)
![Screenshot 2022-02-05 115013](https://user-images.githubusercontent.com/3933562/152636826-837beecb-4876-479a-8d35-0ecf1ac6feb9.jpg)

### Expected result / actual result

Expected to see a friendly warning/error message for that block, but keep using the editor for other blocks.

**Comment by nikolajlauridsen** [comment]
Fixed in #11944, thanks for reporting 🐛 😄
