### ISSUE TITLE
TimeOut Setting not being respected in v9

### ISSUE THREAD

**Issue by poornimanayar** [umbraco/Umbraco-CMS#11965]
### Which *exact* Umbraco version are you using? For example: 9.0.1 - don't just write v9

v9.2.0

### Bug summary

TimeOut Setting not being respected in v9.2. I set the TimeOut in appSettings to 08:00:00 and backoffice logged me out in about 20mins

### Steps to reproduce

Set the TimeOut in appSettings to any value more than 20mins, the backoffice still logs you out closer to 20mins

---
_This item has been added to our backlog [AB#17350](https://dev.azure.com/umbraco/243e7927-03b2-44e2-908f-d4ac7ea5daaa/_workitems/edit/17350)_

**Comment by poornimanayar** [comment]
Related to #11350

**Comment by bergmania** [comment]
Fixed in https://github.com/umbraco/Umbraco-CMS/pull/12029
