### ISSUE TITLE
Indexes not registered after deployment on Azure

### ISSUE THREAD

**Issue by bjarnef** [umbraco/Umbraco-CMS#11962]
### Which *exact* Umbraco version are you using? For example: 9.0.1 - don't just write v9

8.10.2

### Bug summary

On a project on Umbraco v8.10.2 and Umbraco Forms v8.6.0 we sometimes experience the Umbraco Examine indexes are not registered after deployment / swap of slots.

We have the recommended Azure settings configured: https://our.umbraco.com/Documentation/Fundamentals/Setup/Server-Setup/azure-web-apps-v8

It seems some the Umbraco core indexes are not registred, but UmbracoFormsRecordsIndex always is.

![image](https://user-images.githubusercontent.com/2919859/153141528-5b18f771-4fd0-4d53-822b-976f50997509.png)

When we recycle everything works again. I wonder if this is a bug in Umbraco or in Umbraco Forms causing the core indexes not being registred?

![image](https://user-images.githubusercontent.com/2919859/153143033-751d0f5c-06a8-4481-b844-c7d68187dfb5.png)

### Steps to reproduce

Configure a Umbraco v8.10.2 with Umbraco Forms v8.6.0.
Deploy changes and swap slots.

**Comment by bjarnef** [comment]
I am not sure if this was an issue in Umbraco Forms v8.6.0 as well?
https://github.com/umbraco/Umbraco.Forms.Issues/issues/535

// cc @Shazwazza @AndyButland

**Comment by AndyButland** [comment]
Not sure if it's the same thing as you are running into @bjarnef, but can confirm that issue raised by Shannon was patched in a later version that you are running (8.7.2).

**Comment by bjarnef** [comment]
@AndyButland do you know if the fix was included in a patch of 8.6.0 as well? It seems it was only changes included in 8.7.2 (and newer versions).

**Comment by AndyButland** [comment]
It wasn't no.  As you say, it was fixed in 8.7.2.

**Comment by bjarnef** [comment]
I had a similar issue on a Umbraco Cloud project as well a few months ago after deployment.
Umbraco 8.13.1 and Umbraco Forms 8.7.6

But a recycle on the environment resolved the issue. It could possible be the same issue.

**Comment by NikRimington** [comment]
I've had this a fair number of times. I've also had sites getting stuck on a "shutting down" state as well. (Not trying to muddy the issue). When I had this issue I could see in the logs the site had received a "shutdown signal" in the middle of the boot process. This results in ExamineManager shutting down. I think, in this situation, this is happening before the indexes are all loaded.

How are you deploying the site?

**Comment by kjac** [comment]
Hi @bjarnef & co 👋 

I'm wondering if this issue still persists on the newer versions of Umbraco. Has anyone experienced this on V10+?

**Comment by Zeegaan** [comment]
Any news on this @bjarnef 😊

**Comment by bjarnef** [comment]
@Zeegaan I haven't noticed it on newer projects, but also not on our Azure setup - and the newest one on Umbraco 9 doesn't use Umbraco Forms. Let's close this for now and re-open if the issue still persists.
