### ISSUE TITLE
SQL Server 2019 Datacenter does not like some of the FK constraints

### ISSUE THREAD

**Issue by LennardF1989** [umbraco/Umbraco-CMS#11964]
### Which *exact* Umbraco version are you using? For example: 9.0.1 - don't just write v9

9.2.0

### Bug summary

This bug probably goes waaaaaay back, Umbraco 7 and older maybe and is most likely also not tied to SQL Server 2019 Datacenter on it's own.

We have a client that uses the Datacenter edition for its databases, for various reasons. If you try to install Umbraco on this, it will fail, complaining that certain FK relations are not allowed. Upon reviewing the complaints, I have to say I agree.

Apparantly, the Datacenter edition applies much stricter rules when it comes to using FK's. You can't just make a FK to a field that is not the PK or tagged as Unique. So currently, the following tables have issues:
- cmsContentType (nodeid)
- cmsDictionary (id)
- cmsTemplate (nodeid)

All of these columns are technically unique in their respective table, but do not actually contain a Unique index.

### Steps to reproduce

Install Umbraco on a SQL Server 2019 Datacenter, or move over an existing schema from say Azure (where this is valid) to a Datacenter edition. This last situation is what actually caused us to investigate.

### Expected result / actual result

All SQL editions accept the schema.

**Comment by p-m-j** [comment]
@LennardF1989 would you be able to confirm the SQL Server edition, assuming this is SQL Server Enterprise Edition (Datacenter name looks to have been dropped as of SQL Server 2012).

**Comment by p-m-j** [comment]
Are these very old projects that have been upgraded?

cmsContentType appears to have had a unique index on nodeid since 2012, https://github.com/umbraco/Umbraco-CMS/commit/5bd2059c#diff-cf9b00df30e198e767b64d1825a17efae47bd7c596aaf339172d169a70e117dc

**Comment by LennardF1989** [comment]
I'll ask my colleague tomorrow for more details. AFAIK it was a clean install of Umbraco 9.2.0, not an upgrade, because I specifically asked.

**Comment by p-m-j** [comment]
Would you be able to run the following query on the problematic database and share the results?

```sql
select
	T.name as table_name,
	I.name as index_name,
	AC.Name as column_name,
	I.is_unique,
	I.is_unique_constraint
from sys.tables as T inner join sys.indexes as I on T.[object_id] = I.[object_id]
   inner join sys.index_columns as IC on IC.[object_id] = I.[object_id] and IC.[index_id] = I.[index_id]
   inner join sys.all_columns as AC on IC.[object_id] = AC.[object_id] and IC.[column_id] = AC.[column_id]
   inner join sys.schemas as S on T.[schema_id] = S.[schema_id]
WHERE S.name = (SELECT SCHEMA_NAME())
and T.Name in ('cmsContentType', 'cmsDictionary', 'cmsTemplate')
```

**Comment by LennardF1989** [comment]
Hello @p-m-j,

My colleague confirmed it was indeed a clean install of 9.2.0 - not an existing database.

He sent me the following specs:
![image](https://user-images.githubusercontent.com/869973/157278606-574f4dcf-83a4-4b5f-80f8-38bf0e479cdf.png)

**Comment by p-m-j** [comment]
Note that this shows SQL Server 2019 Web edition so it's nothing to do with any stricter requirements in enterprise etc (and AFAIK the rules for FK's are consistent across all editions).

For some reason it looks like you have missing indexes that should be there (and I don't think it's just you as others have similar issues elsewhere).

**Comment by p-m-j** [comment]
Other folks with similar issues have somehow ended up with required indexes disabled for cmsContentType etc.

To find existing but disabled indexes you can run 

```sql
select 
	T.name as table_name, 
	I.name as index_name, 
	AC.Name as column_name,
	I.is_unique,
	I.is_unique_constraint,
	I.is_disabled
from sys.tables as T 
inner join sys.indexes as I on T.[object_id] = I.[object_id]
inner join sys.index_columns as IC on IC.[object_id] = I.[object_id] and IC.[index_id] = I.[index_id]
inner join sys.all_columns as AC on IC.[object_id] = AC.[object_id] and IC.[column_id] = AC.[column_id]
inner join sys.schemas as S on T.[schema_id] = S.[schema_id]
where S.name = schema_name()
and I.is_disabled = 1
```
If they are upstream indexes from the umbraco codebase please rebuild them to re-enable them for example

```sql
ALTER INDEX [IX_cmsContentType] ON [dbo].[cmsContentType] REBUILD
```

Closing for now.
