### ISSUE TITLE
Cannot delete stylesheets through the Backoffice when using a custom `FileSystem`

### ISSUE THREAD

**Issue by rasmusjp** [umbraco/Umbraco-CMS#11963]
### Which *exact* Umbraco version are you using? For example: 9.0.1 - don't just write v9

8.17.2

### Bug summary

When using a custom FileSystem for stylesheets you cannot delete the stylesheets through the Backoffice. When clicking delete the stylesheet gets removed from the UI but if you refresh it's back.

The issue seems to be this code block https://github.com/umbraco/Umbraco-CMS/blob/477697a70cd8b10703f6cf428ceb1da47bfad257/src/Umbraco.Web/Editors/CodeFileController.cs#L637-L645 that uses the local filesystem to check if the given path is a directory (which returns true if the file does not exist) and then proceeds to call `FileService.DeleteStyleSheetsFolder` which doesn't work since it's a file https://github.com/umbraco/Umbraco-CMS/blob/477697a70cd8b10703f6cf428ceb1da47bfad257/src/Umbraco.Web/Editors/CodeFileController.cs#L345-L355

### Specifics

Related issue: https://github.com/umbraco/Umbraco.Cloud.Issues/issues/531

### Steps to reproduce

Use a custom stylesheet `FileSystem` that is not local (e.g. in blob), create a stylesheet through the Backoffice and the try to delete it again.

It can easily be replicated on a Heartcore project

### Expected result / actual result

Being able to delete a stylesheet through the Backoffice when using a custom `FileSystem`

---
_This item has been added to our backlog [AB#17348](https://dev.azure.com/umbraco/243e7927-03b2-44e2-908f-d4ac7ea5daaa/_workitems/edit/17348)_

**Comment by nul800sebastiaan** [comment]
Fixed in https://github.com/umbraco/Umbraco-CMS/pull/11998
