### ISSUE TITLE
Redirect Url Management not working with Contenttypes(Allow vary by culture)

### ISSUE THREAD

**Issue by AnnePieter** [umbraco/Umbraco-CMS#11984]
### Which *exact* Umbraco version are you using? For example: 9.0.1 - don't just write v9

9.3

### Bug summary

See https://github.com/umbraco/Umbraco-CMS/issues/11695
Should be fixed in version 9.3 -> See https://our.umbraco.com/download/releases/930

Fix didn't work for documenttypes where 'Allow vary by culture' is checked!

### Steps to reproduce

https://user-images.githubusercontent.com/15004685/153610609-6568e979-2a3e-4c8e-9c2e-5f816a90d6b6.mp4

---
_This item has been added to our backlog [AB#17419](https://dev.azure.com/umbraco/243e7927-03b2-44e2-908f-d4ac7ea5daaa/_workitems/edit/17419)_

**Comment by BElluu** [comment]
Hello. I cannot repeat this bug on 9.4.0-rc.
![image](https://user-images.githubusercontent.com/11333925/155395849-b5f77ac4-b9d9-4855-9447-df655eec365e.png)
![image](https://user-images.githubusercontent.com/11333925/155395883-d2255522-6605-4744-88c6-52ca9f4cc334.png)

Maybe is something specific to repeat that?

**Comment by JHHessels** [comment]
I retested it and it seems to be working fine now. Thanks Bartlomie!

(I accidentally used the account of my colleague, Anne Pieter)

**Comment by Zeegaan** [comment]
This should now be fixed in https://github.com/umbraco/Umbraco-CMS/pull/12081
Thanks for reporting!
