### ISSUE TITLE
Plugin [lL]ang folder enhancements

### ISSUE THREAD

**Issue by p-m-j** [umbraco/Umbraco-CMS#11986]
### Which *exact* Umbraco version are you using? For example: 9.0.1 - don't just write v9

9.x

### Bug summary

~Two for the price of one.~

~Currently there are issues with the lang folder for plugins when used by an Umbraco instance running on a case sensitive file system, it should be possible to check both plugin/ lang and Lang when running on *nix to ensure that localization files are not missed.~

The lang folder is one of the few remaining blockers for library authors wishing to distribute razor class libraries, we should be able to inspect registered file providers looking for translations or at least provide an API to enable registration in code.

### Steps to reproduce

Write a plugin with translations at {plugin-name}/lang and check what happens on Linux/MacOS

---
_This item has been added to our backlog [AB#17421](https://dev.azure.com/umbraco/243e7927-03b2-44e2-908f-d4ac7ea5daaa/_workitems/edit/17421)_

**Comment by p-m-j** [comment]
Partially covered by https://github.com/umbraco/Umbraco-CMS/pull/11985 so focus on the RCL support.

**Comment by JasonElkin** [comment]
An API would be super helpful as using an xml file doesn't always make sense.

I've created C# only dashboards and trees before (there are APIs for that) but been a frustrated at then having to bundle xml files into what would otherwise have just been a single DLL.

**Comment by KevinJump** [comment]
Hi, 

been looking at this....  and static assets file code make the the file provider at the web root a combined provider, so using that you can get the /app_plugins folder contents when the files are actually being served from somewhere else. 

This also then works on publish - because these files are physically placed in wwwroot/app_plugins when a site is published.

and I think the code we need is something like this, which will then give us all the Lang files in any static web assets app_plugins folder. 

```cs
var webhostEnvironment = container.GetService<IWebHostEnvironment>();
var webRootFileProvider = webhostEnvironment.WebRootFileProvider;

// not we can't null check this, the folders in the root don't actually have all IFileInfo elements impliments
// eg. they return false for Exists when they do exist, and PhysicalPath is not implimented
//       once you are past the first level, it starts to behave properly again. 
var staticPluginLangFiles =
    webRootFileProvider.GetDirectoryContents(Constants.SystemDirectories.AppPlugins)
        .Where(x => x.IsDirectory)
        .SelectMany(x => webRootFileProvider.GetDirectoryContents(Constants.SystemDirectories.AppPlugins + "/" + x.Name))
        .Where(x => x.IsDirectory)
        .Select(x => new DirectoryInfo(x.PhysicalPath))
        .SelectMany(x => x.GetFiles("*.xml", SearchOption.TopDirectoryOnly))
        .Select(x => new LocalizedTextServiceSupplementaryFileSource(x, false));
```

However - when putting this into the SourcesFactory method, I can't seem to resolve `IWebHostEnvironment `?
so i am guessing that isn't referenced in this project 

 - does it need to go somewhere else ? 
 - is this possible here?
 - is the WebRootFileProvider something that needs adding to umbraco's the `IHostingEnvironment` ?

**Comment by KevinJump** [comment]
although i should also add, and API for this would be ace 👍 at the moment i've [got something hacky turning .resx entries into server variables](https://github.com/KevinJump/StyledTextbox/blob/v9/main/Jumoo.StyledTextbox/Localisation/LocalizedStrings.cs) - putting that into LocalizedText would be well better.

**Comment by KevinJump** [comment]
Hi, 

I really would make a PR for this if i knew where it actually should live. (re. the WebHostEnvironment reference problem).

I mean that might probably points to this not being the place for it, and looking into `LocalizedTextServiceFileSource`, you could certainly say the constructor is doing a lot of heavy lifting - and maybe that class needs a good old refactor ? 

So in the interest of trying to move this one forwards are there other methods/structures anyone thinks I should be looking into ? 

- maybe the way forward is a parser like `ServerVariables` parser, then it becomes Somebody Else's Problem (i.e. the package devs) ?
- We could add the lang folder path to the package manifest - then they get loaded from there ? 
- I have the code (from above hack) to read in the languages from the resource file, so it could go down the 'Microsoft' path and say language details come from there ? 

i think @JasonElkin is also right - someway of these being added code only would be also good, so does that lend itself to sorting out `LocalizedTextServiceFileSource` properly to give extension points ?

**Comment by p-m-j** [comment]
I’m on my phone so this isn’t an in depth response, will try be more useful next week, however for now…

moving the registration for localised text service to web.common or web.backoffice should fix the issue with being unable to import IWebHostEnvironment

**Comment by p-m-j** [comment]
@KevinJump something like this should work https://github.com/umbraco/Umbraco-CMS/commit/702099da66f6d07035a0a8af599128d285b4b871

**Comment by AndyButland** [comment]
Just commenting mostly so I get notified of further discussion... as I was looking at this yesterday for Umbraco Forms, considering whether a RCL is a good way to go for distributing the views and other static assets for that package in V10.  And I got to this point - all working apart from the language files not being picked up.

Thanks @KevinJump for your [styled text box](https://github.com/KevinJump/StyledTextbox/tree/v9/main/Jumoo.StyledTextbox) package by the way... that was useful to see how you handled the manifest file for ensuring the scripts and stylesheets are correctly available in the back-office.

**Comment by KevinJump** [comment]
:) i think RCL really is the way to go - i have a working uSync branch too 😄  

I have most of this PR locally now, i think i might have an order issue in terms of what gets initialized when but think that's fixable. mainly wanting to throw packages at my local version to see if it works.

**Comment by KevinJump** [comment]
Hi, 

I've created a PR (based mainly on your branch @p-m-j but based to v9/contrib) 

I've moved everything to using a FileProvider (including `config/lang` stuff)

but it just struck me, would we be better moving the `LocalizedTextServiceSupplementaryFileSource` items into a  Collection ?

the code in the PR could still be used to see the collection but then we would have the 'api' because anyone could add to the collection programmatically, and if they wanted load lang files from anywhere?

**Comment by p-m-j** [comment]
CollectionBuilder is a good idea.

I think there's a missing abrstraction - ILocalizedTextServiceSource as it'd be nice to have an inmemory implementation alongside the existing xml based implementation, this also allows others to customize for their own prefered serialization format json,yaml etc.

**Comment by KevinJump** [comment]
yeah -  that would take some unwiring though (unless i am missing a step?) 

The [LozalizedTextService](https://github.com/umbraco/Umbraco-CMS/blob/v9/contrib/src/Umbraco.Infrastructure/Services/Implement/LocalizedTextService.cs) appears to be dealing in native XDocument and XPath calling a lot. 

So I am guessing that would want to be changed, and the ILocalizedTextServiceSource would become something that represented that in memory ? (see below) - 

but would also need most of the ILocalizedTextService rewriting I would guess?

you thinking something like this ? 
```cs
  public interface ILocalizedTextServiceSource
  {
      CultureInfo Culture { get; set;  }
      IReadOnlyCollection<ILocalizedTextArea> Areas { get; set; }
  }

  public interface ILocalizedTextArea
  {
      IReadOnlyCollection<ILocalizedTextKey> Keys { get; }
  }

  public interface ILocalizedTextKey
  {
      string Key { get; }
      string Value { get; }
  }
```

**Comment by p-m-j** [comment]
Sorry @KevinJump i'm not familiar with the implementation details, honestly I've only lightly glanced at this area of the codebase.

The whole lot looks due for a spring clean but that is likely to occur as part of the new backoffice anyway so I think there is an argument to be made for doing as little refactoring as possible.

**Comment by KevinJump** [comment]
OK -  i think your right. I will just leave this PR as is then - doing the minimum but getting us RCL support 😄

**Comment by kjac** [comment]
Seems the PRs for this issue have all been merged for V10 so I'll go ahead and close it 😄 thanks everyone for chipping in!
