### ISSUE TITLE
Failed to rebuild empty indexes

### ISSUE THREAD

**Issue by RyuLindow** [umbraco/Umbraco-CMS#12005]
### Which *exact* Umbraco version are you using? For example: 9.0.1 - don't just write v9

8.17.1 but happens on all 8.17.x versions

### Bug summary

It seems to be this issue - https://github.com/umbraco/Umbraco-CMS/issues/10273 - which is marked as fixed in Examine 1.2.1, however, it happens on both the 1.2.1 and 1.2.2 versions.

I've also found this forum post on Our about a uCommerce site - https://our.umbraco.com/forum/using-umbraco-and-getting-started/108262-external-examine-index-empty-after-upgrade-to-v122

### Specifics

```								
Message:
Failed to rebuild empty indexes.

Exception:
System.InvalidOperationException: Queue empty.
   at System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
   at Examine.LuceneEngine.OpenReaderTracker.CloseStaleReaders(Directory dir, TimeSpan ts)
   at Examine.LuceneEngine.Providers.LuceneIndex.EnsureIndex(Boolean forceOverwrite)
   at Umbraco.Examine.IndexRebuilder.RebuildIndexes(Boolean onlyEmptyIndexes)
   at Umbraco.Web.Search.BackgroundIndexRebuilder.RebuildOnStartupTask.Run()
```

### Steps to reproduce

I don't have a surefire way to reproduce this.

First of all, it seems to require a larger number of indexes(we're talking around 1k+), and the smaller the project is the less likely it's to happen.

I've seen it happen after general use of a website where the schemas/content are edited in a standard way, so it looks like the issue simply builds up and results in this.

### Expected result / actual result

---
_This item has been added to our backlog [AB#17996](https://dev.azure.com/umbraco/243e7927-03b2-44e2-908f-d4ac7ea5daaa/_workitems/edit/17996)_

**Comment by nul800sebastiaan** [comment]
@RyuLindow is it fixed when you drop in a Examine.dll with version 1.2.0 ? Version 8.15 still shipped with the older version, would be good to test. If it is still a problem with Examine 1.2.0 then it's not due to the Examine upgrade but we'll have to look elsewhere.

**Comment by RyuLindow** [comment]
Hey @nul800sebastiaan 

I was only able to get this issue on a Heartcore project. Not on a standard Umbraco one, unfortunately, but I've seen others get it on them.

Can you tell me why you're interested in whether it works on 1.2.0 if it doesn't work on 1.2.2? Would just like to understand better why you're asking :)

**Comment by nul800sebastiaan** [comment]
@RyuLindow You're pointing to it breaking in #10273 and #10273 was fixed by upgrading to Examine 1.2.1. 
So if Examine 1.2.0 does not have the problem then surely it's an Examine bug. If Examine 1.2.0 also has the same problem, I suspect the bug to be either in Umbraco or in all older Examine versions.

**Comment by p-m-j** [comment]
@RyuLindow 

> I checked a 8.17.2 project which is using 1.2.0 of Examine and saw this error in the logs:
> 
> `System.UnauthorizedAccessException: Access to the path 'C:\home\site\wwwroot\App_Data\TEMP\ExamineIndexes\Internal\write.lock' is denied.`
> 
> I've seen this one of 1.2.1 and 1.2.2 too, though.

Was this also in a heartcore project?

**Comment by RyuLindow** [comment]
@p-m-j 
A Heartcore project

**Comment by p-m-j** [comment]
This one is fixed upstream by examine, other side effects were nucache related.
