### ISSUE TITLE
ContentType IsDirty() is false after changing a value in HistoryCleanup

### ISSUE THREAD

**Issue by KevinJump** [umbraco/Umbraco-CMS#12012]
### Which *exact* Umbraco version are you using? For example: 9.0.1 - don't just write v9

8.18.0-rc

### Bug summary

If you programmatically change a value in a ContentTypes `HistoryCleanup `object, this doesn't make the contenttype dirty (via `isDirty()` check). this means you can't rely on IsDirty if all you have changed is a `HistoryCleanup `value? 

### Specifics

For example if you set the `KeepAllVersionsNewerThanDays `value programatically.  then check `isDirty `it returns false. 

_i believe this should return true?_

 (test code hence the currents!)

```cs
var contentType = Current.Services.ContentTypeService.Get("blog");
var cleanup = contentType.HistoryCleanup;
cleanup.KeepAllVersionsNewerThanDays = 2;

if (contentType.IsDirty())
{
    Current.Logger.Info<ContentTypePropertiesThing>("Is dirty after direct change");
}
else
{
    Current.Logger.Info<ContentTypePropertiesThing>("Isn't dirty after direct change");
}
```

### Steps to reproduce

put some code in (like above) to set a value on a ContentType's HistoryCleanup setting. 

check `isDirty()` on the object to see if it's changed . 

### Expected result / actual result

`IsDirty()` should return true when an item within `HistoryCleanup` is changed for a ContentType.

---
_This item has been added to our backlog [AB#17522](https://dev.azure.com/umbraco/243e7927-03b2-44e2-908f-d4ac7ea5daaa/_workitems/edit/17522)_

**Comment by Zeegaan** [comment]
This should now be fixed in https://github.com/umbraco/Umbraco-CMS/pull/12058
Thanks for reporting ! 🙏
