### ISSUE TITLE
Type to filter doesn´t filter in select user pane, when adding users to a group.

### ISSUE THREAD

**Issue by AlubuArt** [umbraco/Umbraco-CMS#12023]
### Which *exact* Umbraco version are you using? For example: 9.0.1 - don't just write v9

8.17.1

### Bug summary

When adding users to a group, in the select user pane, the "type to filter" function doesnt work (it doesnt filter the users).

![Frame 29](https://user-images.githubusercontent.com/57637214/154735520-61906d5d-52e4-4795-b879-b43c1968181f.png)

### Specifics

Test on:
Chrome 98.0.4758.102
Edge  98.0.1108.55

### Steps to reproduce

1. Select a group
2. Click "add" user to the group.
3. Use the search/filter function to filter the users 

### Expected result / actual result

The expected outcome would be that the list of users is filterede trhough the input in the field.

**Comment by nul800sebastiaan** [comment]
Thanks @AlubuArt for the report, I can reproduce the problem in 8.17 but in the upcoming 8.18.0 this seems to have been fixed, so when it's released later this week it should be working again if you upgrade!

There's a release candidate ready to test if you want to try it out: https://our.umbraco.com/download/releases/8180 

I'll close this one as it should be fixed after an upgrade to 8.18.
