### ISSUE TITLE
UNC path in UmbracoMediaPhysicalRootPath

### ISSUE THREAD

**Issue by EricBrunoSublime** [umbraco/Umbraco-CMS#12027]
### Which *exact* Umbraco version are you using? For example: 9.0.1 - don't just write v9

9.3.0

### Bug summary

When using the new setting for UmbracoMediaPhysicalRootPath it seems UNC-paths are not supported. When using network drives a UNC path is common.

### Specifics

When using a UNC path for the setting "UmbracoMediaPhysicalRootPath" it fails to locate the actual network path, and instead interprets the value as relative to the web root.

### Steps to reproduce

Try to use the setting "UmbracoMediaPhysicalRootPath" with a UNC path instead of a mapped drive with a drive-letter. For instance "\\mediaserver\files\" instead of "X:\files".

### Expected result / actual result

The UNC-path should be resolved correctly and not interpreted as relative to the media root.

**Comment by p-m-j** [comment]
Hey, thanks for the report but this is no longer an issue in 9.3.1, was fixed in #11982
