### ISSUE TITLE
New images not displayed after publishing a page

### ISSUE THREAD

**Issue by stefanie27** [umbraco/Umbraco-CMS#12032]
### Which *exact* Umbraco version are you using? For example: 9.0.1 - don't just write v9

9.2.0

### Bug summary

In some instances when a new page is created and new image(s) uploaded via Media Picker and then published, the images aren't displayed on the published page. Only when the page is published again the images appear.

### Specifics

The data type for the images field (GalleryImages) is System.Collections.Generic.IEnumerable<global::Umbraco.Cms.Core.Models.MediaWithCrops>

It's used in the View of the page like Model.GalleryImages

After publishing and viewing the page for first time, images aren't displayed in some cases - the image section isn't rendered as the images are null.

We use Azure Blob Storage for media, but it might be unrelated because client reported the issue before we moved to Azure Blob Storage.

Note: We have a large amount of media. MediaStore contains 38400 items.

Assumptions is that the newly uploaded images haven't been cached at time of publishing and can't be accessed yet.

### Steps to reproduce

1. In Umbraco 9.2.0 create a content type with images using the Media Picker control. 
2. Create a corresponding View to display the images.
3. Create a new page of the content type, upload new images, click save and publish
4. View page (Not in preview) and check if images are displayed

### Expected result / actual result

Expected Result:
Images are displayed on the page.

Actual Result in some cases:
Images aren't displayed on the page.

**Comment by nul800sebastiaan** [comment]
Hi there @stefanie27 - this sounds like an excellent question for the forums where our friendly community can help you find the best solution for your requirements. 

Make sure to head on over to https://our.umbraco.com and ask follow up questions there! 👍
