### ISSUE TITLE
ContentSavingNotification - Cannot access content that is about to be saved.

### ISSUE THREAD

**Issue by uSkinned** [umbraco/Umbraco-CMS#12051]
### Which *exact* Umbraco version are you using? For example: 9.0.1 - don't just write v9

9.3.1

### Bug summary

Using the ContentSavingNotification you should be able to access the content that is about to be saved. This is not the case. What you get from SavedEntities is values before any changes have been saved.

### Specifics

```csharp
public class ContentSavingNotificationHandler : INotificationHandler<ContentSavingNotification>
    {

        private readonly IContentService _contentService;

        public ContentSavingNotificationHandler(IContentService contentService)
        {
            _contentService = contentService;
        }

        public void Handle(ContentSavingNotification notification)
        {
            foreach (var node in notification.SavedEntities)
            {
               //Say you have changed the name of the node.
               //node.Name contains the previous value and not the value that is about to be saved.
               //You therefore have no way of preventing a change to your node content that you may not want a user to make.
            }
        }
    }
```

### Steps to reproduce

You can test using the example code. Change the node name and you will see that SavedEntities does not contain the new value

### Expected result / actual result

Say you have changed the name of the node.
node.Name contains the previous value and not the value that is about to be saved.
You therefore have no way of preventing a change to your node content that you may not want a user to make.

---
_This item has been added to our backlog [AB#17631](https://dev.azure.com/umbraco/243e7927-03b2-44e2-908f-d4ac7ea5daaa/_workitems/edit/17631)_

**Comment by nul800sebastiaan** [comment]
I can indeed reproduce this, the Saving Eventhandler in v8 used to pass on the entity being saved, not the currently saved entity, so something broke along the way. 

![image](https://user-images.githubusercontent.com/304656/155535736-4596cae6-52de-4f1c-913b-653f3f6c6d5f.png)

**Comment by uSkinned** [comment]
Hi @nul800sebastiaan thanks for the swift response. I just tested this same feature with Umbraco 8.17.1 and can confirm that it is an issue there as well. 

`private void ContentService_Saving(IContentService sender, ContentSavingEventArgs e)`

**Comment by nul800sebastiaan** [comment]
Okay, I don't see that issue in v8.17 

![image](https://user-images.githubusercontent.com/304656/155538032-d47fbaeb-5ea8-4a04-9073-1efdaa24bea8.png)

**Comment by uSkinned** [comment]
If the item is already published and then you try and save. I am getting same behaviour as V9

![v8](https://user-images.githubusercontent.com/22817718/155541200-6971e2d4-c812-472d-b3ed-e03f7cbf9bc5.png)

**Comment by nul800sebastiaan** [comment]
Hmm.. Nope, can't repro that either


https://user-images.githubusercontent.com/304656/155559805-c03fc2f5-3c9f-40a7-851e-4f3efcae5351.mp4

**Comment by uSkinned** [comment]
Okay that's odd that you are not seeing the issue in 8.17.1. Can we confirm its definitely an issue in Umbraco 9.3.1?

**Comment by nul800sebastiaan** [comment]
Indeed! We're looking at it in our next sprint for v9.

**Comment by uSkinned** [comment]
Nice one, thanks Sebastiaan
