### ISSUE TITLE
Opening content node with listview in infinite editor gets wrong nodes in the listview

### ISSUE THREAD

**Issue by jemayn** [umbraco/Umbraco-CMS#12064]
### Which *exact* Umbraco version are you using? For example: 9.0.1 - don't just write v9

8.18.0

### Bug summary

When you open a node in an infinite editor it passes along the id of the node you are on, not the one you are opening in the infinite editor.

### Specifics

This has been tested on an 8.18.0 site with the starter kit installed.

### Steps to reproduce

To get started I've installed the starter kit for some test content, and I've added a contentpicker with the "open" option enabled to open the picked node in an infinite editor.

The node structure is the following:
![image](https://user-images.githubusercontent.com/79840720/155855348-4375c704-06e8-43c1-bfc3-e18fdfcceb1b.png)

The "People" node which is picker in the Call to Action Link editor on the home page has a listview of children.
When you click the open button it open an infinite editor window with the node, but all the "children" in the list view are the children of "home"

Note: Home has id 1104 - People has id 1114 on my site.

On the image below you can see the calls being made when the People node is open:
![image](https://user-images.githubusercontent.com/79840720/155855472-440bd914-a7ef-4af0-9317-1edc6754dd20.png)

As you can see the children shown in the listview come from the GetAllowedChildren call which passes in the home nodes id instead of the People node's.

### Expected result / actual result

The expected result would be the people node showing its own children in the listview.

**Comment by bjarnef** [comment]
I am pretty sure this in the same issue as fixed in https://github.com/umbraco/Umbraco-CMS/pull/12061
It was previously submitted for v8 but recently closed.
