### ISSUE TITLE
Random GUID in user detail view 

### ISSUE THREAD

**Issue by erikjanwestendorp** [umbraco/Umbraco-CMS#12068]
### Which *exact* Umbraco version are you using?
9.3.1

### Bug summary

In the user detail view a "random" guid is shown. The guid is different after every save action. 

![image](https://user-images.githubusercontent.com/7831614/155978386-08820b96-7136-4eee-968d-cdc01e139ced.png)

### Specifics

https://www.umbracodemo.nl/umbraco#/users/users/user/{userId} 

### Steps to reproduce

Navigate to the detail view of a user.

**Comment by nikolajlauridsen** [comment]
Fixed in #12080, thanks for reporting 👍
