### ISSUE TITLE
Services.ServerRegistrationService.GetCurrentServerRole() always returns Unknown when ServerRegistrar explicitly set

### ISSUE THREAD

**Issue by stevetemple** [umbraco/Umbraco-CMS#12086]
### Which *exact* Umbraco version are you using? For example: 9.0.1 - don't just write v9

8.17.1

### Bug summary

I'm trying to debug weird behaviour on a live site running LB servers, calling `Services.ServerRegistrationService.GetCurrentServerRole()` appears to always return Unknown when the server registrar has been explicitly set via `composition.SetServerRegistrar()`

This has caused some confusion and I would expect this to always return the correct role whether it's been explicitly set or self managed.

### Steps to reproduce

Run this in your own composer: 

`composition.SetServerRegistrar(new AdminServerRegistrar());`

With this class present in the project

```
public class AdminServerRegistrar : IServerRegistrar
{
	public IEnumerable<IServerAddress> Registrations => 
		Enumerable.Empty<IServerAddress>();

	public ServerRole GetCurrentServerRole()
		=> ServerRole.Master;

	public string GetCurrentServerUmbracoApplicationUrl()
		=> null;
}
```

Then call `Services.ServerRegistrationService.GetCurrentServerRole()` in a view and it'll return ServerRole.Unknown and not ServerRole.Master

### Expected result / actual result

I'd expect this to return ServerRole.Master (or whatever was explicitly set

**Comment by nul800sebastiaan** [comment]
I get the same in 8.14 @stevetemple - I have no idea if this is the way to do it. Did you debug into the custom composer to see if it gets hit at all?

**Comment by nul800sebastiaan** [comment]
My quick `App_Code` attempt:

```csharp
using Umbraco.Core;
using Umbraco.Core.Composing;
using Umbraco.Web;

namespace My.Website
{
    public class AdminServerRegistrar : IServerRegistrar
    {
        public IEnumerable<IServerAddress> Registrations =>
            Enumerable.Empty<IServerAddress>();

        public ServerRole GetCurrentServerRole()
            => ServerRole.Master;

        public string GetCurrentServerUmbracoApplicationUrl()
            => null;
    }
    public class MyComposer : IUserComposer
    {
        public void Compose(Composition composition)
        {
            composition.SetServerRegistrar(new AdminServerRegistrar());
        }
    }
}
```

**Comment by stevetemple** [comment]
It does, it's displays what you expect if you do `@(DependencyResolver.Current.GetService<IServerRegistrar>().GetCurrentServerRole())` in your view you get the correct role. So I assume it's actually working.

So I assume it's bypassing the ServerRegistrationService when set explicitly. Not major for me just a bit confusing.

If it swapped out the IServerRegistrarService for a FixedServerRegistrarService instance when SetServerRegistrar is used or similar then we could make it align.

**Comment by stevetemple** [comment]
I haven't had a chance yet to look but I think this may well be the same in v9

**Comment by nul800sebastiaan** [comment]
This code has been the same for 4 years, so I would have to assume it's meant to be this way. 
https://github.com/Jeavon)[](https://github.com/umbraco/Umbraco-CMS/blame/dc8d338ba4b18b629bf7ee425fddcd2a9e3974bf/src/Umbraco.Infrastructure/Services/Implement/ServerRegistrationService.cs)

From what I tell from this is that none if this will work until there is actually more than one server registered. Makes sense, right?

**Comment by kjac** [comment]
Hi @stevetemple,

Thank you for raising this, and sorry for the quite belated response.

As this thread already points out, you're not supposed to use the `IServerRegistrationService` to read the current server role. `IServerRegistrationService` has different responsibilities tied mainly to keeping track of servers and keeping them alive.

To read the current server role one should always use `IServerRoleAccessor`. 

```html
@inherits Umbraco.Cms.Web.Common.Views.UmbracoViewPage
@inject Umbraco.Cms.Core.Sync.IServerRoleAccessor ServerRoleAccessor;
@{
	Layout = null;
}
<html>
<body>
Server role is: @ServerRoleAccessor.CurrentServerRole
</body>
</html>
```

The easiest way to test this is to create various `IServerRoleAccessor` implementations:

```csharp
public class SingleServerRoleAccessor : IServerRoleAccessor
{
    public ServerRole CurrentServerRole => ServerRole.Single;
}

public class SchedulingPublisherServerRoleAccessor : IServerRoleAccessor
{
    public ServerRole CurrentServerRole => ServerRole.SchedulingPublisher;
}

public class SubscriberServerRoleAccessor : IServerRoleAccessor
{
    public ServerRole CurrentServerRole => ServerRole.Subscriber;
}
```

...and registering them in Startup:

```csharp
public void ConfigureServices(IServiceCollection services)
{
    services.AddUmbraco(_env, _config)
        .AddBackOffice()
        .AddWebsite()
        .AddComposers()
        .SetServerRegistrar<SubscriberServerRoleAccessor>()
        .Build();
}
```

![image](https://user-images.githubusercontent.com/7405322/211794155-01ab8668-d7a8-448d-9628-795c1efa70eb.png)


See also: https://docs.umbraco.com/umbraco-cms/reference/scheduling#using-serverroleaccessor
