### ISSUE TITLE
Error mapping a Custom MVC Route to a 'Client Request' - yes I know - even though I'm using UmbracoContextFactory

### ISSUE THREAD

**Issue by marcemarc** [umbraco/Umbraco-CMS#12083]
### Which *exact* Umbraco version are you using? For example: 9.0.1 - don't just write v9

v9.3.1

### Bug summary

I think this might be a bug but also I might be being stupid, so bear with me.

I'm using Custom MVC Routing to map a route to a custom Controller inheriting from UmbracoPageController and implementing IVirtualPageController.

Now I'm mapping this route to a file: sitemap.xml

And I'm fully aware that this .xml extensions means that Umbraco considers this to be a 'client-side' request and so doesn't make an UmbracoContext available via the IUmbracoContextAccessor.

There is a note to such an effect in the documentation on this subject:
![image](https://user-images.githubusercontent.com/260802/156184939-acce8913-8ee6-4ee7-814c-ca1febff6905.png)

So in my FindContent implementation, I'm using IUmbracoContextFactory to get hold of an UmbracoContext to find the IPublishedContent that I wish to associate with my sitemap routing....

... and it works! - huzzaah, I can associate the homepage IPublishedContent item with the sitemap.xml route.. I can see it assigned, on a breakpoint... 

![image](https://user-images.githubusercontent.com/260802/156192910-52928f23-0274-4c22-b8d9-1e021b63e899.png)

 but... but... boom!

The white screen of death

![image](https://user-images.githubusercontent.com/260802/156193386-369265bf-6eef-4e6c-9fe3-c9fe5618fa8e.png)

And the rather interesting error message

"Wasn't able to get an UmbracoContext"

But we had one! I saw it, I got the Homepage with it... what is going wrong???

(if I map the route without the .xml, to just /sitemap - all is fine - just thought I'd add that....)

So looking at the stack trace - you can see this is thrown in the Core of Umbraco inside a method called 'SetUmbracoRouteValues'

![image](https://user-images.githubusercontent.com/260802/156194073-76f120d0-adf8-4be8-95e5-73ce1eed2de9.png)

and if we have a look in the codebase you can see that's called in the UmbracoVirtualPageFilterAttribute:

https://github.com/umbraco/Umbraco-CMS/blob/5bfab13dc5a268714aad2426a2b68ab5561a6407/src/Umbraco.Web.Common/Filters/UmbracoVirtualPageFilterAttribute.cs#L25

In OnActionExecutingAsync for this attribute

The attribute first tries to see if the route has been mapped via 'ForUmbracoRoute()' method

and if not checks to see if the controller implements IVirtualPageController

In both cases it then calls SetUmbracoRouteValues, passing in the ActionExecutingContext and the method used to find the IPublishedContent for the route...

All as expected...

But here's the snag inside the SetUmbracoRouteValues method:

https://github.com/umbraco/Umbraco-CMS/blob/5bfab13dc5a268714aad2426a2b68ab5561a6407/src/Umbraco.Web.Common/Filters/UmbracoVirtualPageFilterAttribute.cs#L53

Although we have obtained the IPublishedContent for the route - we want to create a PublishedRequestBuilder object in order to be able to 'set' the PublishedContent we have onto the request.... and THIS needs an UmbracoContext in order to to be able to supply a 'CleanedUmbracoUrl' value... a property of UmbracoContext which calls a method on the UriUtility class lazily to retrieve it.

The UmbracoContext isn't used for anything else.

The problem, I think, is the way the UmbracoContext is accessed within SetUmbracoRouteValues, the implementation uses
IUmbracoContextAccessor like so:

`  var umbracoContext = umbracoContextAccessor.GetRequiredUmbracoContext();`

and if we look at the GetRequiredUmbracoContext() implementation:

https://github.com/umbraco/Umbraco-CMS/blob/5bfab13dc5a268714aad2426a2b68ab5561a6407/src/Umbraco.Core/Extensions/UmbracoContextAccessorExtensions.cs#L11

It tries to get the UmbracoContext from the accessor, and if it can't find one (which it won't it's a client request remember!) then it 'throws':

 throw new InvalidOperationException("Wasn't able to get an UmbracoContext");`
`
Which is our magical error message we are experiencing!
 

## Am I doing something wrong?

I'll put how to reproduce below.

## How to fix??

Naively, and remember I might be stupid - I wonder if it would be possible to just inject the UriUtility class into the  'UmbracoVirtualPageFilterAttribute' - to call UriToUmbraco on the HttpContext.Request.GetEncodedUrl() .... would that work? is that allowed? or does it need to be called via the UmbracoContext.... if that were possible it would mean you don't need to try to obtain an UmbracoContext during the SetUmbracoRoutesValue method...

... or if it needs to be called via an UmbracoContext - then I think SetUmbracoRoutesValue might need to face up to the fact that on a client side request, there is no UmbracoContext - and it would need to be prepared to use the IUmbracoContextFactory to retrieve one! 

### Specifics

Is the above not specific enough? :-)

### Steps to reproduce

Create a new instance of Umbraco using the very latest version 9.3.1.

Install the legendary Umbraco Starter Kit to give you some content of some form.

In your IDE of preferred choice, update your Startup.cs file to 'map a custom route' to sitemap.xml:

```
   public void Configure(IApplicationBuilder app, IWebHostEnvironment env)
        {
            if (env.IsDevelopment())
            {
                app.UseDeveloperExceptionPage();
            }

            app.UseUmbraco()
                .WithMiddleware(u =>
                {
                    u.UseBackOffice();
                    u.UseWebsite();
                })
                .WithEndpoints(u =>
                {
                    u.EndpointRouteBuilder.MapControllerRoute(
              "Sitemap Controller",
              "/sitemap.xml",
              new { Controller = "SiteMap", Action = "Index" });
                    u.UseInstallerEndpoints();
                    u.UseBackOfficeEndpoints();
                    u.UseWebsiteEndpoints();
                });
        }
```

Then create your SiteMap Controller like so:

```
public class SiteMapController : UmbracoPageController, IVirtualPageController
    {
        public SiteMapController(
            ILogger<UmbracoPageController> logger,
            ICompositeViewEngine compositeViewEngine)
            : base(logger, compositeViewEngine)
        { }

        [HttpGet]
        public IActionResult Index()
        {  
            return Content(CurrentPage.Name);
        }


        public IPublishedContent FindContent(ActionExecutingContext actionExecutingContext)
        {
            var _umbracoContextFactory = actionExecutingContext.HttpContext.RequestServices.GetRequiredService<IUmbracoContextFactory>();
            IPublishedContent content = default(IPublishedContent);
            using (UmbracoContextReference umbracoContextReference = _umbracoContextFactory.EnsureUmbracoContext())
            {
                var umbracoContext = umbracoContextReference.UmbracoContext;
                content = umbracoContext.Content.GetAtRoot().FirstOrDefault();
            }
            return content;
        }
    }
```

and then run your site and visit /sitemap.xml

if you are debugging, you should hit the breakpoint inside your SiteMap controller, if you pop one inside FindContent, and you'll see the content variable gets content successfully, and then you'll experience the disappointment of the total white out...

### Expected result / actual result

I'd expect it to write out the 'name' of the homepage (or sitemap if I'd implemented it)

but instead, we get the snowstorm of the .net core white error page:

![image](https://user-images.githubusercontent.com/260802/156199613-62b2b16d-6ed7-4e45-967f-3eebfedfa3a7.png)

**Comment by brentheimer** [comment]
@marcemarc  serendipity. Working on same type of issue. I'm using `Microsoft.AspNetCore.Mvc.RouteAttribute` for routing, and slightly different controller setup, but same issue. The `EnsureUmbracoContext()` works (most times), when fetching the root item. However some core properties, specifically 'Name' always appears as `null` even though other attributes; `Id`, `Key`, etc. are populated. Properties with nested content throws exceptions, etc.

Most reliably however anytime you go to look at `page.Url()` (extension method that internally called EnsureUmbracoContext()) it then fails or return '#' as url.

Yet when updating routing to point to `sitemap` instead of `sitemap.xml` it works fine.
Using version: `9.2.0`.

**Comment by marcemarc** [comment]
Hi @Zeegaan, thanks for taking a look at this issue so quickly!
I think what you propose would clearly 'work' for this situation, but I'm not sure it would be the core's 'best' solution - Umbraco has a history of trying not to introduce further configuration if sensible defaults will do instead... but check with @nul800sebastiaan on this.

My thinking was along the lines of either dropping the UmbracoContext from SetUmbracoRouteValues

```
using System;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Controllers;
using Microsoft.AspNetCore.Mvc.Filters;
using Microsoft.Extensions.DependencyInjection;
using Umbraco.Cms.Core.Models.PublishedContent;
using Umbraco.Cms.Core.Routing;
using Umbraco.Cms.Core.Web;
using Umbraco.Cms.Web.Common.Controllers;
using Umbraco.Cms.Web.Common.Routing;
using Umbraco.Extensions;

namespace Umbraco.Cms.Web.Common.Filters
{
    /// <summary>
    /// Used to set the <see cref="UmbracoRouteValues"/> request feature based on the <see cref="CustomRouteContentFinderDelegate"/> specified (if any)
    /// for the custom route.
    /// </summary>
    public class UmbracoVirtualPageFilterAttribute : Attribute, IAsyncActionFilter
    {
        /// <inheritdoc/>
        public async Task OnActionExecutionAsync(ActionExecutingContext context, ActionExecutionDelegate next)
        {
            Endpoint endpoint = context.HttpContext.GetEndpoint();

            // Check if there is any delegate in the metadata of the route, this
            // will occur when using the ForUmbraco method during routing.
            CustomRouteContentFinderDelegate contentFinder = endpoint.Metadata.OfType<CustomRouteContentFinderDelegate>().FirstOrDefault();

            if (contentFinder != null)
            {
                await SetUmbracoRouteValues(context, contentFinder.FindContent(context));
            }
            else
            {
                // Check if the controller is IVirtualPageController and then use that to FindContent
                if (context.Controller is IVirtualPageController ctrl)
                {
                    await SetUmbracoRouteValues(context, ctrl.FindContent(context));
                }
            }

            // if we've assigned not found, just exit
            if (!(context.Result is NotFoundResult))
            {
                await next();
            }
        }

        private async Task SetUmbracoRouteValues(ActionExecutingContext context, IPublishedContent content)
        {
            if (content != null)
            {
		UriUtility _uriUtility = context.HttpContext.RequestServices.GetRequiredService<UriUtility>();

		Uri _requestUrl = new Uri(context.HttpContext.Request.GetEncodedUrl());
		Uri _cleanedUrl = _uriUtility.UriToUmbraco(OriginalRequestUrl)
          
                IPublishedRouter router = context.HttpContext.RequestServices.GetRequiredService<IPublishedRouter>();

                IPublishedRequestBuilder requestBuilder = await router.CreateRequestAsync(_cleanedUrl);
                requestBuilder.SetPublishedContent(content);
                IPublishedRequest publishedRequest = requestBuilder.Build();

                var routeValues = new UmbracoRouteValues(
                    publishedRequest,
                    (ControllerActionDescriptor)context.ActionDescriptor);

                context.HttpContext.Features.Set(routeValues);
            }
            else
            {
                // if there is no content then it should be a not found
                context.Result = new NotFoundResult();
            }
        }
    }
}
```
Or not using the Extension Method 'GetRequiredUmbracoContext' As that can ONLY work when it's not a client request... so something like this:

```
using System;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Controllers;
using Microsoft.AspNetCore.Mvc.Filters;
using Microsoft.Extensions.DependencyInjection;
using Umbraco.Cms.Core.Models.PublishedContent;
using Umbraco.Cms.Core.Routing;
using Umbraco.Cms.Core.Web;
using Umbraco.Cms.Web.Common.Controllers;
using Umbraco.Cms.Web.Common.Routing;
using Umbraco.Extensions;

namespace Umbraco.Cms.Web.Common.Filters
{
    /// <summary>
    /// Used to set the <see cref="UmbracoRouteValues"/> request feature based on the <see cref="CustomRouteContentFinderDelegate"/> specified (if any)
    /// for the custom route.
    /// </summary>
    public class UmbracoVirtualPageFilterAttribute : Attribute, IAsyncActionFilter
    {
        /// <inheritdoc/>
        public async Task OnActionExecutionAsync(ActionExecutingContext context, ActionExecutionDelegate next)
        {
            Endpoint endpoint = context.HttpContext.GetEndpoint();

            // Check if there is any delegate in the metadata of the route, this
            // will occur when using the ForUmbraco method during routing.
            CustomRouteContentFinderDelegate contentFinder = endpoint.Metadata.OfType<CustomRouteContentFinderDelegate>().FirstOrDefault();

            if (contentFinder != null)
            {
                await SetUmbracoRouteValues(context, contentFinder.FindContent(context));
            }
            else
            {
                // Check if the controller is IVirtualPageController and then use that to FindContent
                if (context.Controller is IVirtualPageController ctrl)
                {
                    await SetUmbracoRouteValues(context, ctrl.FindContent(context));
                }
            }

            // if we've assigned not found, just exit
            if (!(context.Result is NotFoundResult))
            {
                await next();
            }
        }

        private async Task SetUmbracoRouteValues(ActionExecutingContext context, IPublishedContent content)
        {
            if (content != null)
            {
		IUmbracoContext umbracoContext;
                IUmbracoContextAccessor umbracoContextAccessor = context.HttpContext.RequestServices.GetRequiredService<IUmbracoContextAccessor>();

  		if (!_umbracoContextAccessor.TryGetUmbracoContext(out umbracoContext))
                {
		 	var _umbracoContextFactory = actionExecutingContext.HttpContext.RequestServices.GetRequiredService<IUmbracoContextFactory>();
			using (UmbracoContextReference umbracoContextReference = _umbracoContextFactory.EnsureUmbracoContext())
            		{
                		umbracoContext = umbracoContextReference.UmbracoContext;

            		}                  
                }

                IPublishedRouter router = context.HttpContext.RequestServices.GetRequiredService<IPublishedRouter>();

                var umbracoContext = umbracoContextAccessor.GetRequiredUmbracoContext();

                IPublishedRequestBuilder requestBuilder = await router.CreateRequestAsync(umbracoContext.CleanedUmbracoUrl);
                requestBuilder.SetPublishedContent(content);
                IPublishedRequest publishedRequest = requestBuilder.Build();

                var routeValues = new UmbracoRouteValues(
                    publishedRequest,
                    (ControllerActionDescriptor)context.ActionDescriptor);

                context.HttpContext.Features.Set(routeValues);
            }
            else
            {
                // if there is no content then it should be a not found
                context.Result = new NotFoundResult();
            }
        }
    }
}
```

Again what I'm suggesting might be crazy stupid :-P for lots of reasons, but if one of these approaches or a variation there of might be suitable - then you save people having to make extra configuration, when they have already configured the route!

thanks

marc

**Comment by Zeegaan** [comment]
Hey @marcemarc thanks for your suggestions! Your solution using the Uris and removing  the UmbracoContext is good 🎉 We want to remove that from UmbracoSetRouteValues, so i've made a bit of a combination in my PR. Now you can use the UmbracoContextFactory like in your example and it works! With my fix you can also inject umbracoContextAccessor into your controller and that way ensure that you only have 1 UmbracoContext during a request.

**Comment by marcemarc** [comment]
Yey! top bananas @Zeegaan 

Looking at your 'HandleAsClientSideRequest' additional solution...

is it just too early for me, have I misunderstood?

If a custom route is mapped via MapControllerRoute  and it doesn't have a file extension eg /mylovelypage/superstuff

Then the UmbracoContext is available BECAUSE IsClientSideRequest returns false:

![image](https://user-images.githubusercontent.com/260802/157841419-31f91b14-c425-4d19-985c-eaecf7a4027d.png)

if a custom route is mapped via MapControllerRoute to the sitemap.xml file then IsClientSideRequest returns true, and the UmbracoContext isn't there and it fails.

So would it be better to call your extra configuration HandleAsServerSideRequest ???

Because you want /sitemap.xml to be handled as if it were a server side request, not as a client side request determined by it's extension...

or do I need another coffee :-) ??

The other thought I had regarding your approach, is could it automatically look up in the endpoint routing table, for any custom routes that have been configured to a file extension - and then include them to be treated as 'ServerSide' automatically?

And then I thought, maybe Umbraco should just ship with sitemap.xml and robots.txt always considered as a serverside request, if the files exist on disk then they'll be served first anyway, but if someone maps a route to them, is that a common enough thing on most implementations for it to be anticipated and 'just work' by convention as a serverside request!

**Comment by Zeegaan** [comment]
Hey  @marcemarc, no you're totally right, HandleAsServerSideRequest is a much better name (naming is hard 😅) 
As for you suggestions, i think it would be cool to have it automatically look up the endpoint routing table for any custom configured file extension routes, but it's out of scope for now.
I think the idea that we could ship with sitemap.xml/robots.txt always considered as serverside request would be too "magical", i can see someone trying to do it with a 3rd file, but that doesn't just work, now they actually have to do the manual configuration, and being confused by that.

Thanks again for your feedback!

**Comment by Zeegaan** [comment]
Fixed in https://github.com/umbraco/Umbraco-CMS/pull/12088
Thanks again for all the feedback @marcemarc 🚀
