### ISSUE TITLE
If two images exisits with same name, save event adds number to name

### ISSUE THREAD

**Issue by DrKirk84** [umbraco/Umbraco-CMS#12098]
### Which *exact* Umbraco version are you using? For example: 9.0.1 - don't just write v9

v9.3

### Bug summary

The name of a media item changes if there is more than one item with the same name in the same directory.

### Steps to reproduce

1. Create a new Image in Media Library called "My Image"
2. Choose any file to upload and save the image
3. Create a second Image in the same folder and call it "My Image"
4. Choose any file to upload and save the image

The result should look like this:
![grafik](https://user-images.githubusercontent.com/84323988/156596477-b4d0c38b-c8eb-43a6-bcb0-16c8b38d0b65.png)

Now, select "My Image" and just save the image.
The former "My Image" is now "My Image (2)". You can save the image multiple times. It will always append "(1)".
If you go to "My Image (1)" and save the image without changes it also adds "(1)" to the name.

The result should look like this:
![grafik](https://user-images.githubusercontent.com/84323988/156597792-54355187-57e7-4dca-95ec-ddc3c46ef2dd.png)

### Expected result / actual result

The Name should not change, even if there are multiple items with the same name in the same directory

**Comment by nul800sebastiaan** [comment]
Thanks @DrKirk84 for the report with good reproduction steps! I can repro in 9.3 but not in the upcoming 9.4 release. Turns out this is already fixed, also for media, in this PR https://github.com/umbraco/Umbraco-CMS/pull/11996 

The RC of 9.4.0 will be out next week.
