### ISSUE TITLE
Media search does not search child items

### ISSUE THREAD

**Issue by V414** [umbraco/Umbraco-CMS#12102]
### Which *exact* Umbraco version are you using? For example: 9.0.1 - don't just write v9

8.17.2

### Bug summary

When using the search on the media tab, searching for a media item by name only searches the currently viewed folder, but not any of its descendants. 

This means on websites with a lot of media files there is no practical way to find a specific file except to make the same search in each individual media folder.

### Specifics

It also looks like this behaviour has been around for a while: [https://our.umbraco.com/forum/using-umbraco-and-getting-started/87008-media-search-not-searching-child-folders](https://our.umbraco.com/forum/using-umbraco-and-getting-started/87008-media-search-not-searching-child-folders)

### Steps to reproduce

To reproduce, create folder X within the media section. Then create a child folder Y. Then add some content to that child folder.

When you search the name of the content in folder Y, it will correctly filter the content. However, if you do this same search in the parent folder X, it does not find the content. 

These first two images show the behaviour when searching the folder that directly contains the content (so working as expected):

![Media Search Issue 1](https://user-images.githubusercontent.com/3150585/156806879-bcb1cfec-0f5f-4911-8367-abe559122181.png)
![Media Search Issue 2](https://user-images.githubusercontent.com/3150585/156806887-9946fc48-ee8a-4ede-ac2d-b87aa706f3a9.png)

However these two images show the same search, but in the parent folder of the folder previously shown (which does not show the child folders content, even with the same search values):

![Media Search Issue 3](https://user-images.githubusercontent.com/3150585/156806891-f2dddce1-7960-408a-9ba4-9abfb3b755bf.png)
![Media Search Issue 4](https://user-images.githubusercontent.com/3150585/156806895-c9652aed-2e5f-4051-9df6-b88ef4c278f4.png)

### Expected result / actual result

The media search should search all child folders of a folder so that a user can actually find the content as expected, at the very least showing folders that contain content with that search query in.

**Comment by BElluu** [comment]
@V414 I repeated that. I look at what's wrong :)

**Comment by kjac** [comment]
It is indeed intended behaviour - the search only applies to the current folder level. This is how list views work, and is consistent across the board; list views can span a great number of items (specially for content), in which case "deep search" would produce rather confusing results given the lack of structural context in the search results view.
