### ISSUE TITLE
Can't save / modify membertype (Member)

### ISSUE THREAD

**Issue by schlagerdk** [umbraco/Umbraco-CMS#12101]
### Which *exact* Umbraco version are you using? For example: 9.0.1 - don't just write v9

8.18.0

### Bug summary

After upgrading from 8.17.0 to 8.18.0

If you try to modify MemberType "Member" you'll get an error: "Validation: The Alias field is required." - You'll also get this error by simply clicking [Save] on the membertype. However, you can create a new membertype and modify and save that one, but the default "Member" gives an error.

### Steps to reproduce

- Install 8.17.0
- Upgrade to 8.18.0
- Login to Umbraco
- Click Settings
- Open Member Types
- Click on Member
- Click on [Save]

### Expected result / actual result

I would expect that membertype saves just as it did in 8.17.0 that I upgraded from.

**Comment by nul800sebastiaan** [comment]
Thanks @schlagerdk, yes I would expect that the member type saves as before as well. I've just tried this in a clean 8.18.0 install AND on an upgrade from 8.17.1 to 8.18.0 and it works, so I suspect your upgrade is not quite complete. 

My post here is pretty old but still applies when people have upgrade problems https://cultiv.nl/blog/how-to-diagnose-umbraco-upgrade-problems/

**Comment by schlagerdk** [comment]
Hi Sebastian... I just found out that the problem is in the DB... In the table: cmsPropertyType the propertyTypeGroupId was null on Password Question and Password Answer, by changing this to 11 and reloading, the problem was fixed.
