### ISSUE TITLE
Unable to rollback content to the published version

### ISSUE THREAD

**Issue by ronaldbarendse** [umbraco/Umbraco-CMS#12119]
### Which *exact* Umbraco version are you using? For example: 9.0.1 - don't just write v9

9.3.1

### Bug summary

If you save changes on a published content node, you can't reset/rollback to the current published version again. The only way seems to be to publish the saved changes/current draft version, after which the previous published version can be selected in the rollback dialog, do the rollback and publish the content again.

Besides unnecessarily updating the content cache (and all other side-effects of a publish, like re-indexing in Examine, etc.) and potentially having incorrect content published for a brief moment, this also creates an additional content version that you can't manually clean up as well.

It's also not possible to compare the current draft and published versions, so you also can't see what changes are being published if there are any pending.

### Steps to reproduce

- Publish a content node
- Make changes and only save
- Try to rollback those changes or find out what actually changed

### Expected result / actual result

If you only have a single published version and make some changes, the rollback dialog is basically useless, as you can't select the current draft or published version:
![Only draft and published version](https://user-images.githubusercontent.com/1051287/157538280-f6b10ba0-58e9-4333-bcbd-74bb37d7be89.png)

After publishing the changes, you can select the previously published version to rollback to:
![Rollback to previous published version](https://user-images.githubusercontent.com/1051287/157538401-611de2eb-30c8-47ff-893a-3478904ad9b0.png)

But publishing that again creates an additional version:
![Additional versions created](https://user-images.githubusercontent.com/1051287/157541485-db4ed07d-ac75-46d9-81f0-65d8f9dcda05.png)

Also, the text above the comparison says `This shows the differences between the current version and the selected version`, but what current version is used to compare to, the draft or published one?

I would expect the following:
- Do not show the current draft version in the list if it's the same as the published version (no pending changes)
- If there is a draft version, allow comparing it to the published version and when rolling back, disregard any pending changes (so you end up in the state of the previous item)
- Make it clear that you're comparing against the current draft version

In addition to this I found some other minor issues in the rollback dialog:
- Selecting different versions doesn't update the title of the compare box (deselecting and selecting another version does however)
- The `Current version` box only displays the node name and created date, not the updated date (and is useless anyway, as the node name is shown in the compare box and created date isn't really useful here - plus it doesn't account for culture variants that aren't created yet and have no name)
- There's no way to remove/delete specific versions (would be nice to have a delete/trashcan and pin/unpin button, instead of the verbose prevent cleanup/enable cleanup)

---
_This item has been added to our backlog [AB#24054](https://dev.azure.com/umbraco/243e7927-03b2-44e2-908f-d4ac7ea5daaa/_workitems/edit/24054)_

**Comment by c9mb** [comment]
I was just checking out this behavior on V10 and it seems still to be the same.
There should be the ability to compare saved (but unpublished) changes to the current published version, and the ability to abandon saved changes, reverting back to the current published version.

**Comment by hfloyd** [comment]
I just came across this same behavior on a v8.13.2 site today.

**Comment by lbras** [comment]
Same on 8.18.4. Completely agree, the rollback functionality is currently very confusing. The expected results proposed by @ronaldbarendse are the way to go!

**Comment by PotatoDotJar** [comment]
I would think this should be an essential feature.

**Comment by kjac** [comment]
@ronaldbarendse really good stuff here ❤️ 

I've addressed (I think?) all your points in #13452 except this one:

> - There's no way to remove/delete specific versions (would be nice to have a delete/trashcan and pin/unpin button, instead of the verbose prevent cleanup/enable cleanup)

That's a somewhat larger task. I reckon we can do without for the time being at least - maybe we should add it to the backlog for future consideration?

Quick demo of the improvements:
![rollback-improvements](https://user-images.githubusercontent.com/7405322/203146331-d5c84a81-02dc-45f3-bd32-30bf80faa1c2.gif)

**Comment by tenshi04** [comment]
I see this has been fixed in versions 10.4 and 11.1.0 but has this been fixed in the latest version of 8? Is there plan to?

thanks.
