### ISSUE TITLE
Duplicate doc type properties stored in NuCache

### ISSUE THREAD

**Issue by RyuLindow** [umbraco/Umbraco-CMS#12110]
### Which *exact* Umbraco version are you using? For example: 9.0.1 - don't just write v9

8.17.2

### Bug summary

https://user-images.githubusercontent.com/56826332/157254441-51443bc0-c0ec-4c76-9f9b-e4539a3c2625.mp4

I reproduced this issue in Heartcore on UC and never on a standard Cloud project.

### Steps to reproduce

1. Go to the document type.
2. Change the alias of a property and save the doc type

It only works sometimes.

### Expected result / actual result

It should only be there once.

---
_This item has been added to our backlog [AB#17997](https://dev.azure.com/umbraco/243e7927-03b2-44e2-908f-d4ac7ea5daaa/_workitems/edit/17997)_

**Comment by nul800sebastiaan** [comment]
Probably linked to https://github.com/umbraco/Umbraco-CMS/issues/12005

**Comment by p-m-j** [comment]
Re-opening will see if I can break the in memory side of things and make the rest API stop working.

**Comment by p-m-j** [comment]
Closed by https://github.com/umbraco/Umbraco-CMS/pull/12208
