### ISSUE TITLE
Cannot inject IFileSystem into RenderController or UmbracoApiController

### ISSUE THREAD

**Issue by chrden** [umbraco/Umbraco-CMS#12129]
### Which *exact* Umbraco version are you using? For example: 9.0.1 - don't just write v9

9.3.1

### Bug summary

When attempting to inject the IFileSystem dependency into a RenderController or UmbracoApiController (for a Web API) I receive an InvalidOperationException exception
_InvalidOperationException: Unable to resolve service for type 'Umbraco.Cms.Core.IO.IFileSystem' while attempting to activate MyController_

### Steps to reproduce

Create a RenderController to hijack route for existing document type/template
Attempt to add IFileSystem dependency (alongside dependencies required by RenderController)
Load URL with hijacked route
Page will display error (see Summary)

![image](https://user-images.githubusercontent.com/22013176/157880706-9c5e88db-1d6a-4976-835b-7e072067e173.png)

OR

Create an UmbracoApiController with HttpGet method
Call get method via Postman, for example
Returns 500 response

![image](https://user-images.githubusercontent.com/22013176/157882241-0c863093-8d5d-4f63-9f71-b2edc86d08c0.png)

### Expected result / actual result

No error appears and page loads as expected

**Comment by nul800sebastiaan** [comment]
From my colleagues I understand that `IFileSystem` is not supposed to be injected, based on what you need to do, it's recommended to use the `FileSystems` or `MediaFileManager` for injection.

The reason it's not directly injectible is because the returned implementation might change, sometimes you'll get `PhysicalFileSystem` and sometimes `ShadowFileSystem`, based on the specific need. 

Hope that makes sense!

**Comment by chrden** [comment]
Thanks @nul800sebastiaan. That makes sense.

I'm basically trying to programmatically insert an Umbraco Forms record which has a file upload field type so I'm trying to ensure that the file is stored in the correct location of media/forms/upload/form_<form_guid>/<guid>/filename and the field has the correct file path. We're also using Azure blob storage so as a workaround for now I have inserted the file using the Azure blob storage SDK 

If you can offer any advice on this, unless this can be achieved through your previous recommendations, that would be great.

Thanks!

**Comment by nul800sebastiaan** [comment]
@chrden Great, so the recommended route for that one is to inject `MediaFileManager` and there's a `.FileSystem` on that one, the `FileUpload` field type for Forms uses this `_mediaFileManager.FileSystem.AddFile(newPath, memoryStream)` for creating the file and `_mediaFileManager.FileSystem.GetUrl(path)` for getting the value to persist on the form.

**Comment by chrden** [comment]
Amazing! Cheers @nul800sebastiaan. I'll give this a go and feedback. Really appreciate that!
