### ISSUE TITLE
Content picker using xpath values fails if content is opened inside infinite editor.

### ISSUE THREAD

**Issue by KevinJump** [umbraco/Umbraco-CMS#12121]
### Which *exact* Umbraco version are you using? For example: 9.0.1 - don't just write v9

8.18.0 and v9.3.0

### Bug summary

When you have a content type with an Multi-Node Tree picker on it that is using XPATH syntax to query what nodes to show 
any content pages using this content type that are opened up inside an infinite editor ,then the user may see an error _(depends on the id in the url when the user opens the page)_

![image](https://user-images.githubusercontent.com/431231/157687511-f85e1496-d9a4-44be-a74b-43b74bbde5fd.png)

This is because the query for the xpath is picking up the Id from rootparams.id, when this may not be the id of the content item we are looking at. it should ideally use `editorState.getCurrent()` ??

### Specifics

The Content Picker controller is getting the ID for the query from the URL (using $routparams.id) if that ID isn't a content id or isn't infact an umbraco entity id (e.g in a custom section) the query returns the error. 

https://github.com/umbraco/Umbraco-CMS/blob/cade6cb68473c3e09b09a9d297be8efd9f986f92/src/Umbraco.Web.UI.Client/src/views/propertyeditors/contentpicker/contentpicker.controller.js#L245-L250

### Steps to reproduce

Add a MNTP to a document type that uses the XPATH syntax `$site` (as an example) 

![image](https://user-images.githubusercontent.com/431231/157687392-5c40e0ce-9389-465c-9a99-35a6377d084f.png)

You then need to open this content item in an infinite editor from a page that isn't a content node (not super easy to do - you need a custom section and tree ). - when you do the editor will fail because it will use the ID from the editing item in the custom tree to query the content and not the content id of the item open inside the infinite editor .

example from Translation Manager - opening a content node in an infinite editor from the job. 
![mntp-error](https://user-images.githubusercontent.com/431231/157689043-73f761e9-cf4b-4f56-9504-7484800a0576.gif)

the content query is then using the JobId to query the content not the id of the content item in the infinite editor. 

### Expected result / actual result

Content picker should use the current content item's id in the query to get the correct path .

i *think*

The Content  picker controller it should use `editorState.current.id` to get the id for the query and not the `$roouteparams.id` (but i am not 100% sure!)

---
_This item has been added to our backlog [AB#25529](https://dev.azure.com/umbraco/243e7927-03b2-44e2-908f-d4ac7ea5daaa/_workitems/edit/25529)_

**Comment by kjac** [comment]
Hi @KevinJump,

Thanks for reporting this 💪 and sorry for the rather belated response.

This is indeed an issue, and it can even be reproduced by using the MNTP in a normal/supported scenario. Your proposed fix works like a charm 😄 

I have created a PR in #13657 to mend this.

**Comment by kjac** [comment]
Closed by https://github.com/umbraco/Umbraco-CMS/pull/13657
