### ISSUE TITLE
Mismatch between culture ISO code case in IPublishedContent property and methods

### ISSUE THREAD

**Issue by aguyfromdenmark** [umbraco/Umbraco-CMS#12128]
### Which *exact* Umbraco version are you using? For example: 9.0.1 - don't just write v9

9.3.1

### Bug summary

We will use "dansk (Denmark)" culture as an example.
IPublishedCulture.Cultures returns a dictionary with culture info. They key of this dictionary is the ISO culture code for the culture. 
The IPublishedContent.Url() method takes a culture as a string argument. I some cases, this will return "#" because the key in the "Culture" dictionary will look like this: "da-dk", but the "Url()" expects it as "da-DK".

The first image shows the ISO code as seen in the backoffice. 
The second image, taken from a debug session, shows how to "Url()" method only works in the culture code is in the same case as seen in backoffice, but the "Culture" property returns it in lower case.

![image](https://user-images.githubusercontent.com/6904597/157843006-fde98268-8e3b-461a-855d-625759bb0102.png)
![image](https://user-images.githubusercontent.com/6904597/157843032-f6b44d3c-9d4a-4d19-9f09-c108bb632956.png)

### Steps to reproduce

1. Get the "Culture" dictionary of an IPublishedContent. 
2. Using one of the keys, call Url() on that IPublishedContent object, with the key as an argument. 
3. If the case of the key is different from the case seen in the backoffice, the result is "#", and not the expected URL.

### Expected result / actual result

Returning the actual URL of the IPublishedContentItem

**Comment by patrickdemooij9** [comment]
This should be fixed in 9.4.0 according to this issue (https://github.com/umbraco/Umbraco-CMS/issues/11687)

**Comment by nul800sebastiaan** [comment]
Thanks, yep, this one duplicates #11687 👍
