### ISSUE TITLE
Multiple nodes named originally same as document type name keep getting renamed to name with numbers "Name (2)(1)(1)"...

### ISSUE THREAD

**Issue by waldvmar** [umbraco/Umbraco-CMS#12137]
### Which *exact* Umbraco version are you using? For example: 9.0.1 - don't just write v9

9.3.1

### Bug summary

If you name two nodes (same document type) on same level exactly with the same name as the document type alias the renaming through umbraco doesn't stop after the first renaming to number but keeps getting renamed over and over again.

For example having a documenttype with the name "PageFront".

1. Create a node of this documenttype with the name "PageFront"
2. Create another node of this documenttype on same level as the first node and name it "PageFront" as well (Umbraco renames it to "PageFront (1)"
3. Save and publish the first of the nodes again and Umbraco will rename it to "PageFront (2)". Save an publish it again it will be renamed to  "PageFront (2) (1)". Save an publish it again it will be renamed to  "PageFront (2) (1) (1)"
4. Save and publish the second of the nodes again and Umbraco will rename it to "PageFront (1) (1)". Save an publish it again it will be renamed to  "PageFront (1) (1) (1)". Save an publish it again it will be renamed to  "PageFront (1) (1) (1) (1)"

The renaming of Umbraco should stop after step 2 and not keep renamed with numbers on and on. The only way to stop the renaming for a node is to name it different to document type name.

### Steps to reproduce

For example having a documenttype with the name "PageFront".

1. Create a node of this documenttype with the name "PageFront"
2. Create another node of this documenttype on same level as the first node and name it "PageFront" as well (Umbraco renames it to "PageFront (1)"
3. Save and publish the first of the nodes again and Umbraco will rename it to "PageFront (2)". Save an publish it again it will be renamed to  "PageFront (2) (1)". Save an publish it again it will be renamed to  "PageFront (2) (1) (1)"
4. Save and publish the second of the nodes again and Umbraco will rename it to "PageFront (1) (1)". Save an publish it again it will be renamed to  "PageFront (1) (1) (1)". Save an publish it again it will be renamed to  "PageFront (1) (1) (1) (1)"

### Expected result / actual result

**Expected result**
The renaming of Umbraco should stop after step 2 and not keep renamed with numbers on and on. So first node should have and keep the name "PageFront" (regardless of how often it's getting published). The second node shoud have and keep the name "PageFront (1)".

**Actual result**
After save and publish the first node 3 times the name will be "PageFront (2) (1)" instead of "PageFront".

**Comment by nul800sebastiaan** [comment]
Thanks for the extensive report, this has already been fixed in the upcoming v9.4.0 👍 the release candidate for that is out now if you need a quick fix or just want to try it out.

The PR for the fix is here: https://github.com/umbraco/Umbraco-CMS/pull/11996
