### ISSUE TITLE
Images uploaded by pasting in RTE is stored outside the users' media start node

### ISSUE THREAD

**Issue by kasperdyrvig** [umbraco/Umbraco-CMS#12133]
### Which *exact* Umbraco version are you using? For example: 9.0.1 - don't just write v9

8.17.2

### Bug summary

A user with a "Media start node" can't reach items created by pasting in RTE. These are created in the Media root, not the Media start node for that user.

### Steps to reproduce

1. A user with a "Media start node" set, edits a page.
2. He copies a picture from Word by pressing `CTRL+C`, or maybe uses `Print Screen`.
3. He then inserts the picture in RTE in Umbraco, using `CTRL+V`. The picture is uploaded an pasted in RTE, successfully. 
4. Notice, the image is created in the Media Root, not the Media start node for that user.

### Expected result / actual result

Media pasted in RTE should not just be stored in the Root, but obey Media start node

**Comment by LeeDalchow** [comment]
Tested on V9, not an issue as it seems to put the image directly into the HTML as base64 when copy-pasted into RTE.

**Comment by nul800sebastiaan** [comment]
Just came across this one again after fixing some things with that implementation on v10: https://github.com/umbraco/Umbraco-CMS/pull/13016

I'll close this one as indeed it's not an issue on v9/10 any more.
