### ISSUE TITLE
ModelsBuilder generated property gets overridden after each build

### ISSUE THREAD

**Issue by pikopiko15** [umbraco/Umbraco-CMS#12136]
### Which *exact* Umbraco version are you using? For example: 9.0.1 - don't just write v9

8.16.0

### Bug summary

I updated my block list editor component by adding a new property, but it gets overriden by ModelsBuilder after every build.
![bug](https://user-images.githubusercontent.com/37023297/158521914-3c38de7c-0e2f-4244-8c62-d8825ae6e918.jpg)

### Steps to reproduce

Open any block list editor component in Umbraco backoffice
Add a new property
Save

### Expected result / actual result

![image](https://user-images.githubusercontent.com/37023297/158522194-bffc6fdb-f6bd-4474-bdfe-5a476bd49f12.png)
![image](https://user-images.githubusercontent.com/37023297/158522221-ecc2ad1d-79d1-4a11-9d70-dcb41b373e93.png)

**Comment by nul800sebastiaan** [comment]
Hi @pikopiko15 that sounds weird, and doesn't seem like anyone else has that problem else we'd hear a lot more about it. I assume it's something in your setup somewhere that's a bit off.

This sounds like an excellent question for the forums where our friendly community can help you find the best solution for your requirements. 

Make sure to head on over to https://our.umbraco.com and ask follow up questions there! 👍
