### ISSUE TITLE
Can't get culture-agnostic siblings of root nodes

### ISSUE THREAD

**Issue by qubaji** [umbraco/Umbraco-CMS#12143]
### Which *exact* Umbraco version are you using? For example: 9.0.1 - don't just write v9

9.3.1

### Bug summary

In a multilingual, multisite context, the Siblings extension method on a site (root node) does not respect the culture code passed in and simply uses the current culture.

### Specifics

I have several sites in a single Umbraco installation. Each site is a root node with cultures and domains set up. Many of these are available in several languages, but these do not necessarily overlap (except en-GB which is available for every site). Each site needs to link to all others, regardless of whether the site is available in that language (if it's not, the link should be to the en-GB version).

I am trying to access the sites by getting the current node's root, and then looking for its siblings, like this:
`var sites = Model.Root<Site>().Siblings<Site>("en-GB");`

It looks like this is due to the implementation of Umbraco.Extensions.PublishedContentExtensions.SiblingsAndSelfOfType. Normally this works fine by getting the Parent and then Children, passing in the culture code. But when the parent is null it uses publishedSnapshot.Content.GetAtRoot() without passing the culture code. I think the solution may just be to pass the culture code in here. And indeed I can work around the problem that way - by using `publishedSnapshot.Content.GetAtRoot("en-GB")` instead of the extension method.

### Steps to reproduce

1. Set up a clean Umbraco install
2. Create a Site document type which is allowed at root and varies by culture
3. Create two instances of this in English (United Kingdom) and set up domains for both in that culture
4. Translate one into French (France) and set up a domain for that culture
5. Set up a view for the Site document type with the following code: `@Model.Siblings<Site>("en-GB").Count()`
6. View the page under the English (United Kingdom) domain. It will correctly show the number 2.
7. View the page under the French (France) domain. It will incorrectly show the number 1.

### Expected result / actual result

Expected result: the French (France) page shows the number 2
Actual result: the French (France) page shows the number 1

**Comment by patrickdemooij9** [comment]
Hi @qubaji,
I discussed this with @nul800sebastiaan and there is no breaking change to worry about. If you are up to it, it would be great if you could create a PR for this as you've already investigated where the issue lies and how to fix it.

If you need help to get started with the Umbraco source code, there is this video that helps you get set up: https://www.youtube.com/watch?v=IoFTTn8Pnfs. Let me know if you have any questions or are facing any issues.

**Comment by qubaji** [comment]
@patrickdemooij9 Thanks for checking that out. Yes, I'd be happy to look at creating a PR - will look forward to my first contribution to Umbraco!
