### ISSUE TITLE
Cold boot is too slow on Linux - priming nucache db

### ISSUE THREAD

**Issue by Ambertvu** [umbraco/Umbraco-CMS#12159]
### Which *exact* Umbraco version are you using? For example: 9.0.1 - don't just write v9

9.3.1

### Bug summary

When doing a cold boot on an Umbraco site, with a large amount of content items (1200 content, 10.000 media in my case), it causes extremely long memory cache build times. Currently my site takes about 25 minute in cold boot. (described my entire case here with logs : https://our.umbraco.com/forum/using-umbraco-and-getting-started/108501-very-long-cold-boot)

I on purposely put the 'memory cache' like that, because I'm not 100% sure that is really the issue. I only know when the memory cache is finally build, everything works like normal again, **unless** you click on the 'reload memory cache' button in the 'published status' screen. If you click that everything will time out again untill it's complete. So for it seems like that is the issue.
(just for clarification, I did a clean V9 install, and imported the 11.200 items using usync into a clean database)

This evening I did the **exact** same deploy to a Windows Azure App and the boot time is ~a minute.

### Steps to reproduce

- Get a database with lots of content on Azure (S1 for example, tried also with high performance tiers)
- Attach it to a clean website
- Deploy to a Linux Azure App (any performance level)
- Navigate to the website

### Expected result / actual result

Expected result:
Boot like normal ( ~a minute).

Actual result:
Boot in ~20 minutes. Frontend is not accessible, backend is accesible at first, but when doing ANY database call(save, view published status screen) it will time out.

---
_This item has been added to our backlog [AB#25527](https://dev.azure.com/umbraco/243e7927-03b2-44e2-908f-d4ac7ea5daaa/_workitems/edit/25527)_

**Comment by Ambertvu** [comment]
I did some experimenting today, and at first, when I put my site in a Linux docker container the same issue occurred.
But when removing the  "LocalTempStorageLocation": "EnvironmentTemp" setting from the appsettings.json, everything was back to normal!

I tried a deploy to a Linux App container again with the LocalTempStorageLocation removed, but the issue persisted.

However knowing that enabling LocalTempStorageLocation in a Linux docker container has the exact same issue as I currently have with LocalTempStorageLocation enabled in a Linux App, it seems likely it has something to do with this function.

Found a fairly recent issue regarding LocalTempStorageLocation, perhaps it is related? https://github.com/umbraco/Umbraco-CMS/issues/11389

**Comment by Ambertvu** [comment]
Update:

Ok so I've been trying to debug this some more:
- I've created a clean 9.4.1 DB/Project
- Deployed, connected to DB, refresh memcach, ~1 second
- Added 500 contentitems 
- Refresh memcache ~13 seconds
- Added 500 more  content items
- Refresh memcache ~ 26 seconds (seems to grow linear, so for my own site with 13.000 content items, it would be a 5 minute! bootup) 

At first I was unable to reproduce this locally in a Linux Docker container, but when I added the setting "LocalTempStorageLocation": "EnvironmentTemp" the issue would also appear in my Docker.

I hooked up the Umbraco 9.4 source to my database and did some debugging in a local docker with that setting enabled, I found out that the biggest (99%) time consumer is this:

ContentStore.CS line 203 
" _localDb[change.Key] = change.Value;" 

as it iterated over each item that's being added to the cache.
The _localDB is of type BPlusTree. I have no experienced with this.

Now I'm a bit stuck on how to proceed further, hope anyone has some tips or ideas on what to do/try next. Or perhaps a insight in how this actually works or could effect performance on a Linux App / Docker environment (perhaps due to the EnvironmentTemp cache thats different for Windows as compared to Linux?

**Comment by nul800sebastiaan** [comment]
Great digging there, thanks for all the efforts so far! 

Just going to link to the line of code: https://github.com/umbraco/Umbraco-CMS/blob/v9/contrib/src/Umbraco.PublishedCache.NuCache/ContentStore.cs#L203 

I've posted this before to the team at HQ but I'll give them the update as well, hoping this is the breakthrough clue 🤞

**Comment by p-m-j** [comment]
Definitely an issue, but upstream from us in CSharpTest.Net.Collections-NetStd2.

To demo the issue check https://gist.github.com/p-m-j/606a27877c26725b6058442f39a8fb64#file-nucacheslow-cs

### Windows

```bash
Wrote 5000 entries to C:\Users\Paul Johnson\AppData\Local\Temp\tmp8DF0.tmp in 8.4379227
```

### Linux

```bash
Wrote 5000 entries to /tmp/tmpd6FNXg.tmp in 95.3526502
```

**Comment by p-m-j** [comment]
The repo for the net standard port is https://github.com/mamift/CSharpTest.Net.Collections/ but this doesn't allow issues to be raised.

@mamift - tagging incase you're intrigued

**Comment by p-m-j** [comment]
@Ambertvu - as a workaround you can opt out of using the on disk cache with https://our.umbraco.com/documentation/Reference/V9-Config/NuCacheSettings/#additional-settings

**Comment by Ambertvu** [comment]
Glad you tested and reproduced! I just encounterd that post yesterday and
wanted to give it a try today in a test environment. Will let you know if I
encounter any other issues.

**Comment by mamift** [comment]
> The repo for the net standard port is https://github.com/mamift/CSharpTest.Net.Collections/ but this doesn't allow issues to be raised.
> 
> @mamift - tagging incase you're intrigued

Hello I’ve enabled issues on the repo now.

**Comment by Ambertvu** [comment]
Using the setting as described https://our.umbraco.com/documentation/Reference/V9-Config/NuCacheSettings/#additional-settings worked like a charm, no other issues noticed.

**Comment by Ambertvu** [comment]
Was hoping this would be fixed in v10, but sadly its still a thing. As Umbraco is more focusing on linux hosting and claiming full support on unix, wouldnt this be a breaking item?

**Comment by p-m-j** [comment]
> Was hoping this would be fixed in v10, but sadly its still a thing. As Umbraco is more focusing on linux hosting and claiming full support on unix, wouldnt this be a breaking item?

We can’t fix all upstream problems as well as our own, we have to sleep sometime :)

**Comment by Ambertvu** [comment]
> 

If you code as fast as you speak during presentations you could have fixed this by last week :-) Nice presentation about SQLite though!

**Comment by Ambertvu** [comment]
> > Was hoping this would be fixed in v10, but sadly its still a thing. As Umbraco is more focusing on linux hosting and claiming full support on unix, wouldnt this be a breaking item?
> 
> We can’t fix all upstream problems as well as our own, we have to sleep sometime :)

If you code as fast as you speak during presentations you could have fixed this by last week :-) Nice presentation about SQLite though!

**Comment by bielu** [comment]
@nul800sebastiaan This will be breaking change as you change dependency which someone might have no have direct dependency in code when using package and referencing Umbraco. It is not likely anyone used this library, but it should be flagged just in case if someone is using this dependency :) 
@bergmania I am surprised you didn't flag it as breaking.

**Comment by bergmania** [comment]
Hi @bielu.. 

I'm not sure why this is breaking?

The dependency update is a fork, where the dll's are keeping the original names. I have tested using `BPlusTree<int, string>` directly, in a package build with target on Umbraco 11.0.0. After merging this PR, I can still use the package, even that I expose `BPlusTree<int, string>` and is build before this update..

To my knowledge this should not be breaking, as the dll name and namespaces, are consistent with the old dependency.

Can you help me prove this is a binary breaking change, please.

**Comment by bielu** [comment]
@bergmania so you didn't change namespaces and assembly information? so it is not breaking change but namespace collision, my bad. I guess it is not that bad in this case, it shouldn't cause issues than, but it is bad practize, but I understand it was done as other package has really slow time to react with changes?

**Comment by bergmania** [comment]
But the old dependency is replaced with the new,  so there should only be one version of the dll? It have a new version number, patch updated, witch is correct according to our changes in that package.

**Comment by Nashuim** [comment]
Is there an ETA on when 10.4.1 with this fix will be released?

**Comment by bergmania** [comment]
Hi @wtct 

The comment in https://github.com/umbraco/Umbraco-CMS/commit/c496ff8a37a2431d4e3c3fd88115590f546c75de commit is not valid anymore.

IIRC some of the changes @nikcio did, before we forked his fork of the package, made the LogFileInCache mode cross-platform.

Making this yet another configuration is not desired from a maintenance point of view. NuCache issues is already extremely time-consuming to debug due to all the existing configuration options. 

Longer term, we plan to get rid of this package completely anyway.

**Comment by wtct** [comment]
Thanks @bergmania for clarification and fast response!

Now it sounds really good and it looks like we will achieve about 30x performance improvement when updating from 10.3.2 to 11.2.0 (10.4.1 is not ready yet). I calculated it by the rps ratio comparison of LogFileInCache and CommitToDisk :) 

Probably we will upgrade our project to 11.2.0 tomorrow, then I can share our feedback.

I keep finger crossed for your plans related to getting rid of this package! :)

Best!
