### ISSUE TITLE
Machine name in Master/Replica election is cropped 

### ISSUE THREAD

**Issue by gabador-mof** [umbraco/Umbraco-CMS#12158]
### Which *exact* Umbraco version are you using? For example: 9.0.1 - don't just write v9

8.17.1

### Bug summary

We are hosting Umbraco on Kubernetes, having two deployments. One is for content and one for admin. We have set the master server election registrars, but we noticed the cache is not being cleared on some content pods. 

There could be any number of content pods being spun up. 

When logging what machine is getting assigned which role, the following came up. 

![image](https://user-images.githubusercontent.com/64405523/159306341-ff9feea7-ef38-4da9-830c-4c3c146a3515.png)

I noticed that there are only two machine names. The actual pod names are: 

![image](https://user-images.githubusercontent.com/64405523/159306940-9a72eabe-0f91-4998-9909-c3b56d590d9d.png)

Umbraco is cropping the machine name somewhere. Can somebody shed some light how I can overwrite the machine name cropping? 

### Steps to reproduce

set up Kubernetes, assign a longer deployment name and allow k8s to assign machine names. 

### Expected result / actual result

The machine name is not cropped, but each pod can present itself for cache reload

**Comment by nul800sebastiaan** [comment]
We can't do anything about that it seems, we use `Environment.MachineName` for all the logging and apparently you can't have a machine name longer than 15 characters which is exactly what you're seeing in the logs. 

I'm afraid you're going to have to find a way to name your machines explicitly somehow to be able to get more informative logging.

**Comment by gabador-mof** [comment]
With hosting environments being declarative these days, we have to consider that the pod name that is generated will inevitably be longer than 15 characters. A deployment in kubernetes will always generate a longer name. Umbraco should be able to handle this somehow. I still consider this a bug, as syncing between the pods is not working due to the truncation of the machine name. Can something be done?

**Comment by nul800sebastiaan** [comment]
I did test this, I created a new VM on Azure with the long name of one out of your list, the name was truncated in exactly the same way. I don't think we can get Windows fixed for you 😉 I've googled around for it a bit and all the results indicate that windows doesn't like machine names longer than 15 chars.

Maybe it's something kubernetes can fix? A config option in kubernetes?

**Comment by nul800sebastiaan** [comment]
FYI, I know this doesn't help you on v8, but on v9 it looks like you could use the `MainDomKey` for this.

**Comment by nul800sebastiaan** [comment]
Oh forgot the link https://github.com/umbraco/Umbraco-CMS/pull/12037

**Comment by gabador-mof** [comment]
Thank you. For now, I have reduced the deployment name in Kubernetes, to a single character, which makes the auto-generated part of the machine name 13 characters. I cannot change the replica set name so the end result is: 

s-1234567890-xycbd - where xycbd is the unique part of the machine name... This is still a problem, as it means that machines presenting as: 
s-1234567890-xycbd
s-1234567890-xyapo will still be construed as the same machine and cache syncing will not happen... It would be good to abstract out the machine name to a class that can be overridden... 

Unfortunately upgrading to V9 is not yet an option for us...

**Comment by nul800sebastiaan** [comment]
It might be interesting to investigate Paul's last comment there though:

> Adding the functionality into v8 should be possible by registering your own `IMainDomLock` implementation which could take inspiration from changes made in v9.
