### ISSUE TITLE
CopyUmbracoFilesToWebRootForDeploy is missing _PackageTempDir in conditions

### ISSUE THREAD

**Issue by iqb-dawn** [umbraco/Umbraco-CMS#12163]
### Which *exact* Umbraco version are you using? For example: 9.0.1 - don't just write v9

8.12.2

### Bug summary

The `UmbracoCms.8.12.2` contains `UmbracoCms.targets` file in build folder. In this file we have CopyUmbracoFilesToWebRootForDeploy target,

```
  <Target Name="CopyUmbracoFilesToWebRootForDeploy" AfterTargets="CopyAllFilesToSingleFolderForMsdeploy">
    <PropertyGroup>
      <UmbracoFilesFolder>$(MSBuildThisFileDirectory)..\UmbracoFiles\</UmbracoFilesFolder>
    </PropertyGroup>
    <ItemGroup>
      <UmbracoFiles Include="$(UmbracoFilesFolder)**\*" />
    </ItemGroup>
    <Copy SourceFiles="%(UmbracoFiles.FullPath)" DestinationFiles="$(_PackageTempDir)\%(RecursiveDir)%(Filename)%(Extension)" Condition="!Exists('%(RecursiveDir)%(Filename)%(Extension)')" />
  </Target>
```

In the Condition, `$(_PackageTempDir)\` is missing. Why this is problematic? Because my below changes is overwritten,

```
  <Target Name="MyCopyUmbracoFilesToWebRootForDeploy" BeforeTargets="CopyUmbracoFilesToWebRootForDeploy">
    <Copy SourceFiles="MyWeb.config" DestinationFiles="$(_PackageTempDir)\Web.config" />
  </Target>
```

Here are the logs,

> MyCopyUmbracoFilesToWebRootForDeploy:
>   Copying file from "D:\a\1\s\MyCms.Umbraco\Web.config.template" to "D:\a\1\s\MyCms.Umbraco\obj\Release\Package\PackageTmp\Web.config".
> CopyUmbracoFilesToWebRootForDeploy:
>   ...............................................................
>   Copying file from "D:\a\1\s\packages\UmbracoCms.8.12.2\UmbracoFiles\Web.config" to "D:\a\1\s\MyCms.Umbraco\obj\Release\Package\PackageTmp\Web.config".
> PipelineCopyAllFilesToOneFolderForMsdeploy:

### Steps to reproduce

Create a new target like below,

```
  <Target Name="MyCopyUmbracoFilesToWebRootForDeploy" BeforeTargets="CopyUmbracoFilesToWebRootForDeploy">
    <Copy SourceFiles="MyWeb.config" DestinationFiles="$(_PackageTempDir)\Web.config" />
  </Target>
```

and see the logs.

### Expected result / actual result

The CopyUmbracoFilesToWebRootForDeploy target should avoid copy web.config as it was already exist but it does copy.

**Comment by nul800sebastiaan** [comment]
Hi there @iqb-dawn we do a lot of hacks in v8 to make it as easy as possible to get started with Umbraco, this is one of them. We have no plans to update the targets any more as v8 is now in the support phase, meaning it will only get fixes for regressions and security from now on. Sorry we can't help here.
