### ISSUE TITLE
Background tasks using RecurringHostedServiceBase using "legacy" constructor throw error on startup

### ISSUE THREAD

**Issue by KevinJump** [umbraco/Umbraco-CMS#12170]
### Which *exact* Umbraco version are you using? For example: 9.0.1 - don't just write v9

9.4

### Bug summary

Any custom background tasks inheriting from `RecurringHostedServiceBase` and using the existing (pre v9.4) constructor

```cs
        protected RecurringHostedServiceBase(TimeSpan period, TimeSpan delay)
```

will cause umbraco to throw an error on startup: 
```cs
Unhandled exception. System.ArgumentNullException: Value cannot be null. (Parameter 'provider')
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at Umbraco.Cms.Infrastructure.HostedServices.RecurringHostedServiceBase..ctor(TimeSpan period, TimeSpan delay)
   at Testing.TestBackgroundTaskHostService..ctor() in C:\Source\Testing\CaseSensitive\UmbNineFour\Code\testbackgroundtask.cs:line 23
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
```

### Specifics

The constructor method has been marked as legacy in v9.4

https://github.com/umbraco/Umbraco-CMS/blob/cde05c11970a7b95a424e07f8f6f66c67636ebb2/src/Umbraco.Infrastructure/HostedServices/RecurringHostedServiceBase.cs#L47-L53

but the method used for getting the logger was changed : 
https://github.com/umbraco/Umbraco-CMS/commit/10ae51273166978f410e49590091ad4727da840b

and this doesn't appear to work at startup.

**n.b : 
**There is no other constructor method pre v9.4 - so existing code cannot be fixed to work pre v9.4 by using a different constructor. meaning there is no workaround to have one code base work pre and post v9.4 ** 

### Steps to reproduce

add following code sample code - in a 9.4 website

```cs
using System;
using System.Threading.Tasks;

using Microsoft.Extensions.DependencyInjection;

using Umbraco.Cms.Core.Composing;
using Umbraco.Cms.Core.DependencyInjection;
using Umbraco.Cms.Infrastructure.HostedServices;

namespace Testing {

    public class TaskBackgroundComposer : IComposer
    {
        public void Compose(IUmbracoBuilder builder)
        {
            builder.Services.AddHostedService<TestBackgroundTaskHostService>();
        }
    }

    public class TestBackgroundTaskHostService : RecurringHostedServiceBase
    {
        public TestBackgroundTaskHostService()
            : base(TimeSpan.FromMinutes(1), TimeSpan.FromMinutes(4))
        { }

        public override async Task PerformExecuteAsync(object state)
        {
            // do something 
            var something = await Task.FromResult(9);
            return; 
        }
    }
}
```

### Expected result / actual result

Should boot.

**Comment by ronaldbarendse** [comment]
Thanks for reporting this so quick after the 9.4.0 release @KevinJump! We've reproduced the error, fixed it and are currently creating a 9.4.1 hotfix for this.

You can work-around this issue by manually setting the `StaticServiceProvider.Instance` before any of the hosted services are constructed, although that requires building a new service provider instance and possibly capturing the logger factory that's `IDisposable`, so use with caution:"

```c#
using Microsoft.Extensions.DependencyInjection;
using Umbraco.Cms.Core.Composing;
using Umbraco.Cms.Core.DependencyInjection;
using Umbraco.Cms.Web.Common.DependencyInjection;

public class RecurringHostedServiceWorkaround : IComposer
{
    public void Compose(IUmbracoBuilder builder)
    {
        StaticServiceProvider.Instance ??= new ServiceCollection().AddSingleton(builder.BuilderLoggerFactory).BuildServiceProvider();
    }
}
```
