### ISSUE TITLE
Pages with blocklist not showing unpublished blocklistcontent in the preview

### ISSUE THREAD

**Issue by GertyEngrie** [umbraco/Umbraco-CMS#12201]
### Which *exact* Umbraco version are you using? For example: 9.0.1 - don't just write v9

9.4.1

### Bug summary

When having a contentpage with a blocklist editor, the preview does not update when adding content in the blocklist that isn't published.

### Steps to reproduce

Create a doctype with a blocklist editor and render the content of the blocklist in the template. 
Create a page and add content. Save & publish this page. Add additional content to the blocklist and do a save & preview. Notice the additional content is not visible in the preview

### Expected result / actual result

The added (not published) content should be visible in the preview window, now it only show the published content.

**Comment by ustadstar** [comment]
We also have the same issue on a couple of projects, one running 9.3.1 and another 9.5.0. Both run in Umbraco Cloud, I have tried to reproduce this issue locally in the V9/contrib branch to see if I could find the issue and propose a fix, but it works locally like expected.

I would like to work on a fix if someone could guide me to reproduce the issue in the contrib branch.

**Comment by kjac** [comment]
Hi everyone.

I can't reproduce this - below you'll find a screencast from version 10.3.2.

@ustadstar mentions this may be related to the SEO Checker package - I haven't tested this, but anyone encountering this issue may need to have a look at their installed packages 😄 

![12201](https://user-images.githubusercontent.com/7405322/211251889-19e98ea5-03b9-4aff-a020-5d9e475b755a.gif)
