### ISSUE TITLE
Empty tag fields throws runtime error when using transfer from an enviroment to another in Umbraco Cloud.  

### ISSUE THREAD

**Issue by jpkeisala** [umbraco/Umbraco-CMS#12204]
### Which *exact* Umbraco version are you using? For example: 9.0.1 - don't just write v9

8.18.0

### Bug summary

Page or Form that has empty Tag -field gives runtime error when using Transfer from an enviroment to another in Umbraco Cloud

### Specifics

When transfering a page or form to Live we get runtime error with:

```
System.Web.HttpException (0x80004005): Error executing child request for handler 'System.Web.Mvc.HttpHandlerUtil+ServerExecuteHttpHandlerAsyncWrapper'. ---> System.NullReferenceException: Object reference not set to an instance of an object.
at
.....
```

I investigated this issue and found that the cause for this is a bug in the umbraco code. This bug causes tags fields to be saved incorrectly when transferred from dev to live, therefore causing an exception on rendering forms.
The workaround seems to be a republish of the transferred content on live, which repairs the tags fields.

Issue is here https://github.com/umbraco/Umbraco-CMS/blob/v8/8.18/src/Umbraco.Core/PropertyEditors/ValueConverters/TagsValueConverter.cs#L39
when tags property is empty string "", the line 39 throws NullReferenceException and after a transfer between environments tags property goes empty.

It looks like in v9 it's fixed.

### Steps to reproduce

1. Have a document type with tag field in it. 
2. Make a node with doctype that has tag field but don't add any tags to it.
3. Transfer it from Dev to Live in Umbraco Cloud
4. Try to load page in Live and it fails.

### Expected result / actual result

We should not get runtime error.

_The workaround seems to be a republish of the transferred content on live, which repairs the tags fields._

**Comment by nikolajlauridsen** [comment]
Hey @jpkeisala, first off sorry for the late answer. 

It looks like this is a duplicate [this](https://github.com/umbraco/Umbraco.Cloud.Issues/issues/571) cloud issue, and [this](https://github.com/umbraco/Umbraco.Deploy.Issues/issues/104) deploy issue, which seems to have been resolved.

Is this correct? If so we can just close this issue 😄

**Comment by elit0451** [comment]
Hi again @jpkeisala, 

Since we haven't heard from you in two weeks and it seems like the problem has been resolved, we would have to close this one. Feel free to reopen it if you are able to provide us with some more information 🙂
