### ISSUE TITLE
Member backoffice views missing Last Login Date

### ISSUE THREAD

**Issue by jattwood** [umbraco/Umbraco-CMS#12228]
### Which *exact* Umbraco version are you using? For example: 9.0.1 - don't just write v9

9.4.2

### Bug summary

It would seem that the Umbraco cmsMember table is missing a few expected columns and associated data. I am sure this is by design as I see that a lot of member data is stored in umbracoPropertyData but last login is not stored there and it's not in the cmsMember table either.

Similar to users, it would seem to me that the cmsMember table would include the following:
```
      [failedLoginAttempts]
      [lastLockoutDate]
      [lastPasswordChangeDate]
      [lastLoginDate]
      [createDate]
```

### Specifics

I noticed that last login is missing from the members info: 

![image](https://user-images.githubusercontent.com/6452616/161785076-840cbb6e-7666-4a45-a001-b2e93e7b6472.png)

### Steps to reproduce

Check out a backoffice view of an existing member known to have logged in in the past. Note the Last Login field will be blank. Also, entry is not present in the umbracoPropertyData table.

![image](https://user-images.githubusercontent.com/6452616/161786195-4cb09d29-654f-47ac-a47c-96ce7ddaca6e.png)

### Expected result / actual result

Expect last login date to be present in the back-office

**Comment by nul800sebastiaan** [comment]
Thanks, a fix is already in progress: https://github.com/umbraco/Umbraco-CMS/pull/12207

**Comment by kjmitch** [comment]
Should merging pull request #12207 have closed this issue automatically?

I'm still experiencing this bug, but I'm on v9.1.2; would I need to upgrade Umbraco to incorporate the change merged by that pull request? (Either way, I'm apprehensive to do so; the expansive changes to the code base made between major versions has me concerned I'll have to spend a lot of time on fixing stuff just to use version 9.2, let alone the latest in version 9.x.)

**Comment by nathanwoulfe** [comment]
@kjmitch yes, I'd expect that PR would resolve this issue too. 

Updating from 9.1 to 9.x should be smooth sailing - it's a minor version so should not contain any breaking changes. 

7-8 or 8-9 were painful, 9-10 is a breeze by comparison.
