### ISSUE TITLE
Umbraco forces StatusCodePages middleware - why?

### ISSUE THREAD

**Issue by PerplexDaniel** [umbraco/Umbraco-CMS#12222]
### Which *exact* Umbraco version are you using? For example: 9.0.1 - don't just write v9

9.4.1

### Bug summary

For every website Umbraco enables the [StatusCodePages middleware](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/error-handling?view=aspnetcore-6.0#usestatuscodepages) and there is no way to turn this off as it happens in [UmbracoApplicationBuilder](https://github.com/umbraco/Umbraco-CMS/blob/642c216f944b507a234ee8c09a9c8b5cdd180dbe/src/Umbraco.Web.Common/ApplicationBuilder/UmbracoApplicationBuilder.cs#L95). This is probably an oversight / mistake: developers should be able to customize the 404 handling and Umbraco should not force some random default that cannot be changed. Perhaps I am missing something obvious but it seems this middleware is simply enabled all the time and you cannot change it in any way.

I know we can customize regular 404 pages through Umbraco (via appSettings or a custom `ILastChanceContentFinder`) but if you request something like `/notfound.txt` you end up with the response from this StatusCodePages middleware which looks like this:
![image](https://user-images.githubusercontent.com/24297947/161718104-fc7ca49b-b90e-43a3-b527-98df63589c19.png)

Is there any reason this is set by default in Umbraco? Microsoft themselves say this normally is not used in Production for obvious reasons, but since Umbraco enables it all the time this will be the case for Umbraco 9 sites in production.
> UseStatusCodePages isn't typically used in production because it returns a message that isn't useful to users.

For example, perhaps we just want to serve a static `404.html` (and 400/403 etc). In a vanilla ASP.NET Core MVC website (`dotnet new mvc`) we could configure that like this:

```csharp
app.UseStatusCodePagesWithReExecute("/{0}.html");
```
This is now not possible with Umbraco because you already configured the default StatusCodePages that renders the plain text response showed earlier.

Umbraco should just remove that line from UmbracoApplicationBuilder.cs and let developers decide how they want to handle it, there is no need to set some default. 

### Steps to reproduce

Request `/notfound.txt` on any Umbraco 9 installation.

### Expected result / actual result

Observe plain text 404 response that a developer is unable to customize.

**Comment by patrickdemooij9** [comment]
Having the same issue ourselves. We were able to work around it, but should just not be set by Umbraco: https://github.com/umbraco/Umbraco-CMS/issues/11851

**Comment by PerplexDaniel** [comment]
@patrickdemooij9 Oh sorry I did not search for existing issues, your issue is indeed about the exact same thing. Well let's hope HQ will now have a look since the fix is literally just removing 1 line which shouldn't break anything either.
