### ISSUE TITLE
Member ConfirmEmailAsync() does not persist to the database

### ISSUE THREAD

**Issue by jattwood** [umbraco/Umbraco-CMS#12227]
### Which *exact* Umbraco version are you using? For example: 9.0.1 - don't just write v9

9.4.2

### Bug summary

When using MemberIdentityUser ConfirmEmailAsync(user, token) the task will complete during it's initial run through and report successful, however the database stamp for emailConfirmedDate in the [cmsMember] table is never set. Subsequent calls to user.EmailConfirmed or _memberManager.IsEmailConfirmedAsync both return false.

### Specifics

Consider the following View component. When provided with a valid email and token, this will pass all scenarios and return successful:

```
public async Task<IViewComponentResult> InvokeAsync()
        {
            var model = new ConfirmEmailViewModel();
            const string viewPath = "~/Views/Components/Account/ConfirmEmail/Index.cshtml";
            var token = HttpContext.Request.Query["token"].ToString() ?? string.Empty;
            var email = HttpContext.Request.Query["email"].ToString() ?? string.Empty;

            if (string.IsNullOrEmpty(token) || string.IsNullOrEmpty(email))
            {
                ModelState.AddModelError(string.Empty, "Invalid token or email");
                return await Task.FromResult(View(viewPath, model));
            }

            var user = await _memberManager.FindByEmailAsync(email);
            if (user == null)
            {
                ModelState.AddModelError(string.Empty, "Can't resolve member");
                return await Task.FromResult(View(viewPath, model));
            }
            
            var result = await _memberManager.ConfirmEmailAsync(user, token);
            if (!result.Succeeded)
            {
                foreach (var error in result.Errors)
                {
                    ModelState.TryAddModelError(error.Code, error.Description);
                }
                return await Task.FromResult(View(viewPath, model));
            }

            if (!user.EmailConfirmed)//test the umbraco way just to make sure...yeah this passes in memory but won't persist subsequently
            {
                ModelState.AddModelError(string.Empty, "User is actually not confirmed. What up G?");
            }
            TempData["Message"] = "Email is confirmed!";
            return await Task.FromResult(View(viewPath, model));
        }
```
Logging indicates that the tasks have completed:

![image](https://user-images.githubusercontent.com/6452616/161781398-d3946551-d1b5-4f1b-985e-61afa20306ca.png)

However, the emailConfirmedDate remains null:
![image](https://user-images.githubusercontent.com/6452616/161775916-eb385fd0-b9b3-4f36-becd-b110e30057fa.png)

Subsequent calls to user.EmailConfirmed or _memberManager.IsEmailConfirmedAsync both return false:

```
var isLoggedIn = _memberManager.IsLoggedIn();            
            var firstName = string.Empty;
            if (isLoggedIn)
            {
                var currentMemberIdentityUser = await _memberManager.GetCurrentMemberAsync();
                var isEmailConfirmed = currentMemberIdentityUser.EmailConfirmed;
                IPublishedContent member = _memberManager.AsPublishedMember(currentMemberIdentityUser);
                firstName = member.Value<string>("firstName") + "Email Confirmed:" + isEmailConfirmed;
            }
```

![image](https://user-images.githubusercontent.com/6452616/161776142-1abb6625-2c1f-4abf-a69a-d3181b42ca2e.png)

I have also tried to set the confirmed date manually using the IMemberservice. This does not work either:

```
            var member = _memberService.GetByKey(user.Key);
            member.EmailConfirmedDate = DateTime.Now;
           _memberService.Save(member);
```

### Steps to reproduce

1) Procure an email validation token and email from a valid MemberIdentityUser

`var emailConfirmationToken = await _memberManager.GenerateEmailConfirmationTokenAsync(identityMember);`

2) Attempt to validate token and email using the above view compontent snippit

3) Token will validate
4) Examine database member and observe no change to confirmed email date or any additional rows added to umbracoPropertyData
5) OR attempt to verify validation on-page via user.EmailConfirmed or _memberManager.IsEmailConfirmedAsync(). These will fail.

### Expected result / actual result

Following a correct implementation of Identity, I would expect the results of user.EmailConfirmed or _memberManager.IsEmailConfirmedAsync() to be true after passing through the correct validation sequence previously.

**Comment by jattwood** [comment]
Hey @nul800sebastiaan any thoughts on who might be able to look into the above? I think this might have something to do with the member store field not being flagged as dirty or some of the if statement logic when null in MemberUserStore.cs around line 622. Any help appreciated. My project is stuck on this little bit of member goodness.

**Comment by nul800sebastiaan** [comment]
This turns out to be because `emailConfirmedDate` is never added to the list of changed columns, only when the `Email` or `LoginName` changes (at which point `emailConfirmedDate` is set to `null` as we need to re-verify.

https://github.com/umbraco/Umbraco-CMS/blob/v9/dev/src/Umbraco.Infrastructure/Persistence/Repositories/Implement/MemberRepository.cs#L801

I would add an `else` like this after that `if` statement above:

```csharp
            else
            {
                // LoginName or Email hasn't changed, check if EmailConfirmedDate was updated, that would mean we're saving a confirmed email address
                if (entity.IsPropertyDirty("EmailConfirmedDate"))
                {
                    changedCols.Add("emailConfirmedDate");
                }
            }
```

Just need to check with the team if that's the way to go, then we can add it to v10, and maybe possibly to a 9.5.1.

**Comment by jattwood** [comment]
Ah! That looks like it for sure. Thanks for the potential solution. Look forward to this one! 
Cheers!

**Comment by gilbertaoe** [comment]
I've been waiting for this to get fixed for a few months now and was feeling impatient today :). My apologies if anyone else had been working on this... first time contributing to the project so I'm not 100% sure how the process works.

Made and verified the changes for both v9 and v10.

**Comment by jattwood** [comment]
@gilbertaoe thank you! I too have been waiting on this. I was literally thinking about this as you wrote - I just upgraded to 9.5.2 today and see that this is not in that build. I would have tackled this based on the suggestion by @nul800sebastiaan but I believe HQ was going to implement this. I'll let him direct you accordingly, but you would generally start with a PR.
