### ISSUE TITLE
Cropped images only return for the first crop size / URL

### ISSUE THREAD

**Issue by nzdev** [umbraco/Umbraco-CMS#12244]
### Which *exact* Umbraco version are you using? For example: 9.0.1 - don't just write v9

9.4.3

### Bug summary

Cropped images only return for the first crop size. If you crop an image using the crop url with a width and height set, then crop the same image again with different width and height, the first crop image is returned instead of the correct new dimensions.

### Specifics

1st crop
?rmode=crop&rnd=132894988621370000&height=50&width=50&quality=1&scale=both

2nd crop
?rmode=crop&rnd=132894988621370000&height=349&width=620&quality=95&scale=both

Using the Umbraco.StorageProviders.

### Steps to reproduce

Upload an image to the media section

Try these crops in order
1st crop
?rmode=crop&rnd=132894988621370000&height=50&width=50&quality=1&scale=both

2nd crop
?rmode=crop&rnd=132894988621370000&height=349&width=620&quality=95&scale=both

### Expected result / actual result

Expected, 2 different cropped image sizes
Actual: Only the first cropped image is returned.

**Comment by nikolajlauridsen** [comment]
Hey @nzdev, sorry for the late reply, but just had a look at this and unfortunately, I'm unable to reproduce in V10.3.2, can you confirm if this is still an issue in V10? 

With this code: 

```html
<img src="/media/1rlpsyo3/a-ghibli-art-study-by-me.jpg"/>


<img src="/media/1rlpsyo3/a-ghibli-art-study-by-me.jpg?rmode=crop&rnd=132894988621370000&height=50&width=50&quality=1&scale=both"/>


<img src="/media/1rlpsyo3/a-ghibli-art-study-by-me.jpg?rmode=crop&rnd=132894988621370000&height=349&width=620&quality=95&scale=both"/>

```

I get the following rendered 
![image](https://user-images.githubusercontent.com/16456704/210574416-283fd15e-9501-4e32-b1fa-2ccd27fc0b16.png)

Which has both the full size, the small on, and the mid-sized one, as expected.

I suspect this may have been fixed down the line, if I recall correctly we did quite a few cropping fixes in v10 😄

**Comment by elit0451** [comment]
Hi again @nzdev, 

Since we haven't heard from you in two weeks and we couldn't reproduce the problem in Umbraco 10, we would have to close this one. Feel free to reopen it if you are able to provide us with some more information 🙂
