### ISSUE TITLE
Problem updating/ editing a tab titled "Generic properties"

### ISSUE THREAD

**Issue by ewanexer** [umbraco/Umbraco-CMS#12240]
### Which *exact* Umbraco version are you using? For example: 9.0.1 - don't just write v9

Umbraco 7.15.3, Umbraco 8.17.1, Umbraco 9.0.0

### Bug summary

I have a few doc types with custom tabs called "Generic properties". This was an inheritance of Umbraco 6 where the tab with generic content properties was called like this - I wanted to add some properties to the same tab so I created a tab with exactly the same name as the generic tab.

In Umbraco 7 this generic tab was renamed to "Info" and the custom "Generic properties" tab was no a problem, it just existed as another tab.

### Specifics

After upgrading to Umbraco 8 and then Umbraco 9 I noticed that the tab called "Generic properties" no longer displays when editing the page using it. In Umbraco 8 the tab displays in the content but it has the name "Properties" (not "Generic properties").

I tried to rename the tab in doc type but that did not work (the update did not save): when trying to rename the tab in Umbraco 8 - I put the cursor in the tab name field and try to write a new name - the tab simply disappears from the doc type!

When editing the tab name in Umbraco 9 it appears to take long time to save, looks like saved and then the tab name does not change in the page content.

Also in Umbraco 7 I now noticed - it is not possible to change the tab name either from "Generic properties" to another name. Saving has the same effect like in Umbraco 8 - the doc type saves but when coming back to the doc type or the content - the tab name persists as "Generic properties".

### Steps to reproduce

The example screenshot show the effect in Umbraco 8
![Generic-tab-disappears](https://user-images.githubusercontent.com/94844597/162472155-f6b53cb4-2677-4386-8816-aa0ac2f4deaf.gif)

### Expected result / actual result

It should allow to rename a custom tab name no matter what the name is.

**Comment by ewanexer** [comment]
I further noticed that I am not able to delete the custom "Generic properties" tab from a doc tab on Umbraco 7.15.3

**Comment by JarnoVWA** [comment]
+1 for Umbraco v8.18.3, the exact same behaviour as shown in the gif/video. Unable to save the document type with error "Validation: The Alias field is required."
When trying to change the name it clears all properties and property-groups in the document type as shown in the gif/video.

In the database, table _cmsPropertyTypeGroup_ does not have an entry for the "Generic properties" tab.
The properties in this tab do exist in table _cmsPropertyType_ but with _propertyTypeGroupId = NULL_

**Comment by nikolajlauridsen** [comment]
Hey all, just had another look.

I can no longer reproduce this in V10+, so it has probably been fixed at some point, possibly as part of #11202

Since we no longer back-port fixes to V8 unless they concern critical security issues, I'm afraid I'll have to close down this issue, however, on the plus side it seems like @christianfredh has a great work around 😄
