### ISSUE TITLE
Umbraco Tags property does not suggest matches for tags within a tag group

### ISSUE THREAD

**Issue by bkclerke** [umbraco/Umbraco-CMS#12247]
### Which *exact* Umbraco version are you using? For example: 9.0.1 - don't just write v9

9.4.3

### Bug summary

Umbraco Tags property editor with the listing group configured does not suggest matching tags from tag group.

### Specifics

Using an Umbraco.Tags property with the tag group configured (ex: listingTags) on a doctype throws console errors in the browser for umbTagsEditorController.
![image (1)](https://user-images.githubusercontent.com/4968254/162845720-354eef5d-7346-42e1-a391-3ebcf06dbda3.png)
 

### Steps to reproduce

1. Configure Umbraco.Tags property editor with tag group. 
![Screen Shot 2022-04-11 at 3 45 34 PM](https://user-images.githubusercontent.com/4968254/162846432-b5500c15-a705-4461-a529-8cf63562fb3f.png)

2. Apply property to doctype
3. Create content with that doctype in the Content section
4. Type in tags into the tags property editor
5. Save and publish content
6. Create new content with that doctype in the Content section (so you have multiple tags in your tag group to match on)
7. Begin typing tags into tags property editor

**NOTICE:** No autocomplete functionality will match the tag as you are typing something similar to a previously used tag in the same tag group.

### Expected result / actual result

The expected action would be that the tag property configured with the same tag group would autocomplete or offer matches to previously used tags when typing.

**Comment by RSDevelopsUK** [comment]
I am also experiencing this issue.
