### ISSUE TITLE
RedirectToUmbracoPage fails if redirecting to a page with a domain defined

### ISSUE THREAD

**Issue by AndyButland** [umbraco/Umbraco-CMS#12258]
### Which *exact* Umbraco version are you using? For example: 9.0.1 - don't just write v9

9.5.0-rc

### Bug summary

When issuing a `RedirectToUmbracoPage` it will fail if a domain is defined on the page being redirected to, with an error of:

```
System.InvalidOperationException: The value <full URL to page> for parameter virtualPath must start with ~/ or /
```

### Steps to reproduce

Set up a simply contact form with model, controller and partial view as per the [documentation here](https://our.umbraco.com/documentation/Fundamentals/Code/Creating-Forms/).

Amend the final line of the controller's method to the following (where the Guid is the key for a page you want to redirect to:

```
return RedirectToUmbracoPage(Guid.Parse("f62a9934-0491-439c-9a04-f2562a597718"));
```

This should work fine until you define a domain on the page via the "Culture & Hostnames" setting.  Then you get the error.

### Expected result / actual result

Should redirect to resolved URL.

**Comment by nul800sebastiaan** [comment]
Fixed in https://github.com/umbraco/Umbraco-CMS/pull/12259
