### ISSUE TITLE
Unable to login to CMS after session kick out

### ISSUE THREAD

**Issue by nickornotto** [umbraco/Umbraco-CMS#12250]
### Which *exact* Umbraco version are you using? For example: 9.0.1 - don't just write v9

Umbraco 7.15.3

### Bug summary

I have been working in the CMS editing content and have been kicked out because of index lock.

I tried to log back again to the CMS and am unable to login - this happens on our public CMS domain.

Umbraco 7.15.3 on Windows Server 2016 Standard.

### Specifics

I have been working in the CMS editing content and have been kicked out because of index lock 

(the issue I described in multiple places: 

- https://github.com/umbraco/Umbraco-CMS/issues/7385
- https://our.umbraco.com/forum/using-umbraco-and-getting-started/100682-unhandled-exception-in-appdomain-read-past-eof-error-in-lucene-indexing
- https://stackoverflow.com/questions/59725408/unhandled-exception-in-appdomain-read-past-eof-error-in-lucene-indexing
- https://our.umbraco.com/forum/using-umbraco-and-getting-started/102097-whats-the-best-umbraco-websites-subdomains-and-indexes-configuration-to-avoid-lucene-errors

).

I tried to log back again to the CMS and am unable to login - this happens on our public CMS domain.

* No configuration has changed whatsoever for long time
* Cleared cookies
* Checked various browsers (even the ones that haven't been used previously for CMS)
* I checked CMS on test/ uat site (that are under the main domain aliases) and the effect is the same - I am unable to login to their respective CMSes

### Steps to reproduce

The error log pf the main domain reports:

>  2022-04-12 12:27:16,222 [P11060/D2/T29] INFO  Umbraco.Core.Security.BackOfficeSignInManager - Event Id: 0, state: Login attempt succeeded for username [username] from IP address [IP address]
>  2022-04-12 12:27:16,222 [P11060/D2/T29] INFO  Umbraco.Core.Security.BackOfficeSignInManager - Event Id: 0, state: User: [username] logged in from IP address [IP address]
>  2022-04-12 12:34:45,620 [P11060/D2/T63] INFO  Umbraco.Core.Security.BackOfficeSignInManager - Event Id: 0, state: Login attempt succeeded for username [username] from IP address [IP address]
>  2022-04-12 12:34:45,635 [P11060/D2/T63] INFO  Umbraco.Core.Security.BackOfficeSignInManager - Event Id: 0, state: User: [username] logged in from IP address [IP address]
>  2022-04-12 12:34:50,855 [P11060/D2/T63] INFO  Umbraco.Core.Security.BackOfficeSignInManager - Event Id: 0, state: Login attempt succeeded for username [username] from IP address [IP address]
>  2022-04-12 12:34:50,855 [P11060/D2/T63] INFO  Umbraco.Core.Security.BackOfficeSignInManager - Event Id: 0, state: User: [username] logged in from IP address [IP address]
>  2022-04-12 12:34:54,433 [P11060/D2/T63] INFO  Umbraco.Core.Security.BackOfficeSignInManager - Event Id: 0, state: Login attempt succeeded for username [username] from IP address [IP address]
>  2022-04-12 12:34:54,433 [P11060/D2/T63] INFO  Umbraco.Core.Security.BackOfficeSignInManager - Event Id: 0, state: User: [username] logged in from IP address [IP address]

The console log of the main site shows:

> Cookie “UMB_EXTLOGIN” has been rejected because it is already expired. [PostLogin](https://www.mydomain.com/umbraco/backoffice/UmbracoApi/Authentication/PostLogin)
> Cookie “UMB_UCONTEXT” has been rejected because it is already expired. [PostLogin](https://www.mydomain.com/umbraco/backoffice/UmbracoApi/Authentication/PostLogin)
> The script from “https://www.mydomain.com/business” was loaded even though its MIME type (“text/html”) is not a valid JavaScript MIME type.
> [umbraco](https://www.mydomain.com/umbraco/#/login)
> Uncaught SyntaxError: expected expression, got '<'
> [ServerVariables:2](https://www.mydomain.com/umbraco/ServerVariables?umb__rnd=d1119d646bc1f30db0c9d9b7bb9c272a)
> No url found for api name legacyTreeJs [DependencyHandler.axd:8:3152](https://www.mydomain.com/DependencyHandler.axd?s=L3VtYnJhY28vbGliL2pxdWVyeS9qcXVlcnkubWluLmpzOy91bWJyYWNvL2xpYi9hbmd1bGFyLzEuMS41L2FuZ3VsYXIubWluLmpzOy91bWJyYWNvL2xpYi91bmRlcnNjb3JlL3VuZGVyc2NvcmUtbWluLmpzOy91bWJyYWNvL2xpYi9tb21lbnQvbW9tZW50Lm1pbi5qczsvdW1icmFjby9saWIvanF1ZXJ5LXVpL2pxdWVyeS11aS5taW4uanM7L3VtYnJhY28vbGliL2pxdWVyeS11aS10b3VjaC1wdW5jaC9qcXVlcnkudWkudG91Y2gtcHVuY2guanM7L3VtYnJhY28vbGliL2FuZ3VsYXIvMS4xLjUvYW5ndWxhci1jb29raWVzLm1pbi5qczsvdW1icmFjby9saWIvYW5ndWxhci8xLjEuNS9hbmd1bGFyLW1vYmlsZS5qczsvdW1icmFjby9saWIvYW5ndWxhci8xLjEuNS9hbmd1bGFyLXNhbml0aXplLm1pbi5qczsvdW1icmFjby9saWIvYW5ndWxhci9hbmd1bGFyLXVpLXNvcnRhYmxlLmpzOy91bWJyYWNvL2xpYi9hbmd1bGFyLWR5bmFtaWMtbG9jYWxlL3RtaER5bmFtaWNMb2NhbGUubWluLmpzOy91bWJyYWNvL2xpYi9uZy1maWxlLXVwbG9hZC9uZy1maWxlLXVwbG9hZC5taW4uanM7L3VtYnJhY28vbGliL2FuZ3VsYXItbG9jYWwtc3RvcmFnZS9hbmd1bGFyLWxvY2FsLXN0b3JhZ2UubWluLmpzOy91bWJyYWNvL2xpYi9ib290c3RyYXAvanMvYm9vdHN0cmFwLjIuMy4yLm1pbi5qczsvdW1icmFjby9saWIvYm9vdHN0cmFwLXRhYmRyb3AvYm9vdHN0cmFwLXRhYmRyb3AuanM7L3VtYnJhY28vbGliL3VtYnJhY28vRXh0ZW5zaW9ucy5qczsvdW1icmFjby9saWIvdW1icmFjby9OYW1lc3BhY2VNYW5hZ2VyLmpzOy91bWJyYWNvL2xpYi91bWJyYWNvL0xlZ2FjeVVtYkNsaWVudE1nci5qczsvdW1icmFjby9saWIvdW1icmFjby9MZWdhY3lTcGVlY2hCdWJibGUuanM7L3VtYnJhY28vanMvYXBwLmpzOy91bWJyYWNvL2pzL3VtYnJhY28ucmVzb3VyY2VzLmpzOy91bWJyYWNvL2pzL3VtYnJhY28uZGlyZWN0aXZlcy5qczsvdW1icmFjby9qcy91bWJyYWNvLmZpbHRlcnMuanM7L3VtYnJhY28vanMvdW1icmFjby5zZXJ2aWNlcy5qczsvdW1icmFjby9qcy91bWJyYWNvLnNlY3VyaXR5LmpzOy91bWJyYWNvL2pzL3VtYnJhY28uY29udHJvbGxlcnMuanM7L3VtYnJhY28vanMvcm91dGVzLmpzOy91bWJyYWNvL2pzL2luaXQuanM7L0FwcF9QbHVnaW5zL01vZGVsc0J1aWxkZXIvbW9kZWxzYnVpbGRlci5jb250cm9sbGVyLmpzOy9BcHBfUGx1Z2lucy9Nb2RlbHNCdWlsZGVyL21vZGVsc2J1aWxkZXIucmVzb3VyY2UuanM7L0FwcF9QbHVnaW5zL05lc3RlZENvbnRlbnQvSnMvbmVzdGVkY29udGVudC5yZXNvdXJjZXMuanM7L0FwcF9QbHVnaW5zL05lc3RlZENvbnRlbnQvSnMvbmVzdGVkY29udGVudC5kaXJlY3RpdmVzLmpzOy9BcHBfUGx1Z2lucy9OZXN0ZWRDb250ZW50L0pzL25lc3RlZGNvbnRlbnQuY29udHJvbGxlcnMuanM7L0FwcF9QbHVnaW5zL3VTeW5jL3VTeW5jRGFzaGJvYXJkQ29udHJvbGxlci5qczs&t=Javascript&cdv=277059338)
> XHRGEThttps://www.mydomain.com/umbraco/backoffice/UmbracoApi/Authentication/GetRemainingTimeoutSeconds
> [[HTTP/2 401 Unauthorized 271ms]]()

The console of the uat site shows:

> No url found for api name backOfficeAssetsApiBaseUrl [DependencyHandler.axd:8:3152](https://uat.mydomain.com/DependencyHandler.axd?s=L3VtYnJhY28vbGliL2pxdWVyeS9qcXVlcnkubWluLmpzOy91bWJyYWNvL2xpYi9hbmd1bGFyLzEuMS41L2FuZ3VsYXIubWluLmpzOy91bWJyYWNvL2xpYi91bmRlcnNjb3JlL3VuZGVyc2NvcmUtbWluLmpzOy91bWJyYWNvL2xpYi9tb21lbnQvbW9tZW50Lm1pbi5qczsvdW1icmFjby9saWIvanF1ZXJ5LXVpL2pxdWVyeS11aS5taW4uanM7L3VtYnJhY28vbGliL2pxdWVyeS11aS10b3VjaC1wdW5jaC9qcXVlcnkudWkudG91Y2gtcHVuY2guanM7L3VtYnJhY28vbGliL2FuZ3VsYXIvMS4xLjUvYW5ndWxhci1jb29raWVzLm1pbi5qczsvdW1icmFjby9saWIvYW5ndWxhci8xLjEuNS9hbmd1bGFyLW1vYmlsZS5qczsvdW1icmFjby9saWIvYW5ndWxhci8xLjEuNS9hbmd1bGFyLXNhbml0aXplLm1pbi5qczsvdW1icmFjby9saWIvYW5ndWxhci9hbmd1bGFyLXVpLXNvcnRhYmxlLmpzOy91bWJyYWNvL2xpYi9hbmd1bGFyLWR5bmFtaWMtbG9jYWxlL3RtaER5bmFtaWNMb2NhbGUubWluLmpzOy91bWJyYWNvL2xpYi9uZy1maWxlLXVwbG9hZC9uZy1maWxlLXVwbG9hZC5taW4uanM7L3VtYnJhY28vbGliL2FuZ3VsYXItbG9jYWwtc3RvcmFnZS9hbmd1bGFyLWxvY2FsLXN0b3JhZ2UubWluLmpzOy91bWJyYWNvL2xpYi9ib290c3RyYXAvanMvYm9vdHN0cmFwLjIuMy4yLm1pbi5qczsvdW1icmFjby9saWIvYm9vdHN0cmFwLXRhYmRyb3AvYm9vdHN0cmFwLXRhYmRyb3AuanM7L3VtYnJhY28vbGliL3VtYnJhY28vRXh0ZW5zaW9ucy5qczsvdW1icmFjby9saWIvdW1icmFjby9OYW1lc3BhY2VNYW5hZ2VyLmpzOy91bWJyYWNvL2xpYi91bWJyYWNvL0xlZ2FjeVVtYkNsaWVudE1nci5qczsvdW1icmFjby9saWIvdW1icmFjby9MZWdhY3lTcGVlY2hCdWJibGUuanM7L3VtYnJhY28vanMvYXBwLmpzOy91bWJyYWNvL2pzL3VtYnJhY28ucmVzb3VyY2VzLmpzOy91bWJyYWNvL2pzL3VtYnJhY28uZGlyZWN0aXZlcy5qczsvdW1icmFjby9qcy91bWJyYWNvLmZpbHRlcnMuanM7L3VtYnJhY28vanMvdW1icmFjby5zZXJ2aWNlcy5qczsvdW1icmFjby9qcy91bWJyYWNvLnNlY3VyaXR5LmpzOy91bWJyYWNvL2pzL3VtYnJhY28uY29udHJvbGxlcnMuanM7L3VtYnJhY28vanMvcm91dGVzLmpzOy91bWJyYWNvL2pzL2luaXQuanM7L0FwcF9QbHVnaW5zL01vZGVsc0J1aWxkZXIvbW9kZWxzYnVpbGRlci5jb250cm9sbGVyLmpzOy9BcHBfUGx1Z2lucy9Nb2RlbHNCdWlsZGVyL21vZGVsc2J1aWxkZXIucmVzb3VyY2UuanM7L0FwcF9QbHVnaW5zL05lc3RlZENvbnRlbnQvSnMvbmVzdGVkY29udGVudC5yZXNvdXJjZXMuanM7L0FwcF9QbHVnaW5zL05lc3RlZENvbnRlbnQvSnMvbmVzdGVkY29udGVudC5kaXJlY3RpdmVzLmpzOy9BcHBfUGx1Z2lucy9OZXN0ZWRDb250ZW50L0pzL25lc3RlZGNvbnRlbnQuY29udHJvbGxlcnMuanM7L0FwcF9QbHVnaW5zL3VTeW5jL3VTeW5jRGFzaGJvYXJkQ29udHJvbGxlci5qczs&t=Javascript&cdv=277059338)
> Cookie “UMB_EXTLOGIN” has been rejected because it is already expired. [PostLogin](https://uat.mydomain.com/umbraco/backoffice/UmbracoApi/Authentication/PostLogin)
> Cookie “UMB_UCONTEXT” has been rejected because it is already expired. [PostLogin](https://uat.mydomain.com/umbraco/backoffice/UmbracoApi/Authentication/PostLogin)
> XHRGEThttps://uat.mydomain.com/umbraco/backoffice/UmbracoApi/Authentication/GetRemainingTimeoutSeconds
> [[HTTP/2 401 Unauthorized 259ms]]()

### Expected result / actual result

It looks like the login works just the session has beeing terminated just after the login.

**Comment by nul800sebastiaan** [comment]
Hi there @nickornotto - Umbraco 7 is currently in the security phase of it's end of life cycle, you can read more about this here: https://umbraco.com/products/knowledge-center/long-term-support-and-end-of-life/umbraco-7-end-of-life-eol/

As such we not longer offer support for usage problems. For any help requests, head out to the forums where our friendly community can help you find the best solution for your requirements. 

Make sure to head on over to https://our.umbraco.com and ask follow up questions there!
