### ISSUE TITLE
Unable to clear Date/Time in nested block list v9.3.1

### ISSUE THREAD

**Issue by DanStecherRetus** [umbraco/Umbraco-CMS#12268]
### Which *exact* Umbraco version are you using? For example: 9.0.1 - don't just write v9

9.3.1

### Bug summary

When using the date/time property editor on an element in a nested block list, its value can't be cleared. When clearing the field and publishing, the old value is passed in the publish request.

### Specifics

I have tested the ability to save and publish on page level, on block list, on nested block list and on element of the nested block list. 
On the page and first block list, Date Picker properties work as normal.
On the nested list and element, they can only be set, not cleared.

### Steps to reproduce

First, setup neccessary types and elements:
1. Create an Element E with a Date Picker (or other using Date/Time property editor)
2. Create two Block Lists: A and B
3. Make sure Block List B can contain elements of Block List A
4. Make sure Block List A can contain Element E
5. Make sure a page P can contain Block List B

Second, create the content:
1. Create a page P
2. Add instance of Block List B to it
3. Add instance of Block List A to Block List B
4. Add instance of Element E to Block List A

Third, reproduce the issue:
1. Pick a date with the Date Picker in Element E
2. Save and Publish
3. Check if the newly chosen date is saved and published
4. Clear the picked date (so the Date Picker is blank)
5. Save and Publish
6. Check if the Date Picker is still blank and if its output (published) is empty

### Expected result / actual result

No matter where a property using the Date/Time property editor is used, it should be clearable (passing an empty string in the save/publish request).

Actual result is the existing/previous value is passed if the property is on a nested block list.

**Comment by elit0451** [comment]
Hi again @DanStecherRetus, 

Since we haven't heard from you in two weeks and we couldn't reproduce the problem in Umbraco 10, we would have to close this one. Feel free to reopen it if you are able to provide us with some more information 🙂
