### ISSUE TITLE
Users password not updating when changing password through an admin account

### ISSUE THREAD

**Issue by jawood1** [umbraco/Umbraco-CMS#12266]
### Which *exact* Umbraco version are you using? For example: 9.0.1 - don't just write v9

Umbraco 8.18.1

### Bug summary

When logging in as an administrator I went to update the password for an editors account.

Once saved the notification came back as successful however the "Password last changed" date field hadn't updated.

I then went to login as the editor but it failed to login.

I then went to the database to check the hash. When I changed the password again with a I noticed the hash hadn't updated in the database.

### Specifics

I've checked this on the latest versions of Firefox and Chrome and I'm not getting any console errors along with nothing in the Umbraco logs.

I checked the release notes for 8.18.2/3 and I see nothing mentioned about any users fixes?

### Steps to reproduce

1. Login as an administrator
2. Go to the user i.e. an Editor account.
3. Click to change password and update it with a new value.
4. Click Save.
6. Attempt to login to the editor account with the password.
7. Failed to login

### Expected result / actual result

Users password updates correctly and can login with the new password.

**Comment by jawood1** [comment]
This has been resolved, turned out to be an issue with old Umbraco files conflicting in the CMS

**Comment by umbracocommunity** [comment]
This issue has been mentioned on **Umbraco community forum**. There might be relevant details there:

https://forum.umbraco.com/t/after-upgrading-from-13-13-0-to-17-2-2-backoffice-password-changes-silently-fail-to-persist/7694/1
