### ISSUE TITLE
Content Tree Node Not Greyed Out When Unpublished.

### ISSUE THREAD

**Issue by marcloveUSN** [umbraco/Umbraco-CMS#12279]
### Which *exact* Umbraco version are you using? For example: 9.0.1 - don't just write v9

8.18.3 - 9.4.3

### Bug summary

With our uSkinned Site Builder we like to predefine Document Types and fields that should vary by culture so that if a customer decides to have a multi-lingual website all they need to do is add their languages and define hostnames for the website.

If you have a Document Type that is set to vary by culture along with a field that is set to vary by culture, when you unpublish the node in the content tree it is NOT greyed out.

The file attached will install a Home node with the correct settings so that you can test this issue.
[Vary_by_culture_issue_1.0.0.zip](https://github.com/umbraco/Umbraco-CMS/files/8522968/Vary_by_culture_issue_1.0.0.zip)

### Steps to reproduce

Please install the attached package in Umbraco 8 to replicate this issue.

**Comment by marcloveUSN** [comment]
Hi Seb, thanks for taking a look. Any guidance on where to look in the source code?

**Comment by nul800sebastiaan** [comment]
The only sensible thing I could say about it was this: > seems to be something to do with the time that ( and ) is added around the home node

Not sure where that happens exactly though 🙈

**Comment by marcloveUSN** [comment]
Okay, if you get any further info on this, let me know. I will see if I can dig into the issue and figure out why its happening.

**Comment by bourpie** [comment]
Hello, I'm having this issue with Umbraco version 9.2.0.

Someone suggested on the Forum creating a class that hook into the tree render event (Umbraco 8)
https://our.umbraco.com/forum/using-umbraco-and-getting-started/109307-unpublished-status-unpublished-class-not-set-in-the-tree-view#comment-109307

**Comment by vlaellayug** [comment]
Hi @nul800sebastiaan, @marcloveUSN, @bourpie - I've created a [PR](https://github.com/umbraco/Umbraco-CMS/pull/13253) for this issue.

**Comment by bourpie** [comment]
That is great news. Thank you very much !
