### ISSUE TITLE
Umbraco 9 backoffice Media Folder Type doesn't contains permission for Vector Graphics Media Type

### ISSUE THREAD

**Issue by Borc92** [umbraco/Umbraco-CMS#12275]
### Umbraco version

9.4.3

### Bug summary

In the Umbraco backoffice the Folder Media Type type doesn't contain permission per Vector Graphics Media Type.

So when adding SVG in Media tab, we can only add it under the "root", when we enter a folder this is not possible anymore...

(the same applies for Video and Audio Media Types)

### Steps to reproduce

![image](https://user-images.githubusercontent.com/37801345/164218363-cce73baf-7406-444c-a8ab-e563e80797f9.png)

**Comment by nikolajlauridsen** [comment]
Hey @Borc92, first off, sorry for the late reply. 

Looking at it now it looks like this was fixed at some point down the line (the screenshot is from V10), so I'll go ahead and close this issue. Thanks for reporting, and sorry again that we didn't get to your issue sooner 😄 

![image](https://user-images.githubusercontent.com/16456704/210524772-d4ef80dd-608f-4cf7-a553-e961f111df88.png)

**Comment by Borc92** [comment]
Not a problem. I checked on newer versions and yes it is fixed.
