### ISSUE TITLE
GetPagedDescendantsInReferences query time makes unpublishing impossible

### ISSUE THREAD

**Issue by beliskner** [umbraco/Umbraco-CMS#12308]
### Which *exact* Umbraco version are you using? For example: 9.0.1 - don't just write v9

9.4.3

### Bug summary

In production currently it is impossible to unpublish a vast majority of documents due to the newly introduction TrackedReferencesController and eventually Repository. Attempting to unpublish an item creates the following query:
`SELECT DISTINCT [pn].[id] as nodeId, [pn].[uniqueId] as nodeKey, [pn].[text] as nodeName, [pn].[nodeObjectType] as nodeObjectType, [ct].[icon] as contentTypeIcon, [ct].[alias] as contentTypeAlias, [ctn].[text] as contentTypeName, [umbracoRelationType].[alias] as relationTypeAlias, [umbracoRelationType].[name] as relationTypeName, [umbracoRelationType].[isDependency] as relationTypeIsDependency, [umbracoRelationType].[dual] as relationTypeIsBidirectional
FROM [umbracoRelation] [r]
INNER JOIN [umbracoRelationType] [umbracoRelationType]
ON ([r].[relType] = [umbracoRelationType].[id])
INNER JOIN [umbracoNode] [cn]
ON (([umbracoRelationType].[dual] = 'FALSE' AND ([r].[parentId] = [cn].[id])) OR ([umbracoRelationType].[dual] = 'TRUE' AND (([r].[childId] = [cn].[id]) OR ([r].[parentId] = [cn].[id]))))
INNER JOIN [umbracoNode] [pn]
ON ((([pn].[id] = [r].[childId]) AND ([cn].[id] = [r].[parentId])) OR (([pn].[id] = [r].[parentId]) AND ([cn].[id] = [r].[childId])))
LEFT JOIN [umbracoContent] [c]
ON ([pn].[id] = [c].[nodeId])
LEFT JOIN [cmsContentType] [ct]
ON ([c].[contentTypeId] = [ct].[nodeId])
LEFT JOIN [umbracoNode] [ctn]
ON ([ct].[nodeId] = [ctn].[id])
WHERE ([pn].[id] IN (SELECT [umbracoNode].[id] AS [NodeId]
FROM [umbracoNode]
WHERE ([umbracoNode].[path] LIKE (SELECT concat([node].[path],',%')
FROM [umbracoNode] [node]
WHERE (([node].[id] = 7507))))))
AND ([umbracoRelationType].[isDependency] = 'TRUE')
ORDER BY ([umbracoRelationType].[alias])`

Which takes more than 5 minutes to complete (Unsure as to the exact time, I canceled the query after 5 min). This produces an error in the unpublish overlay stating the database timeout:
**System.Data.SqlClient.SqlException, System.Data.SqlClient, Version=4.6.1.3, Culture=neutral, PublicKeyToken=: Timeout expired. The timeout period elapsed prior to completion of the operation or the server is not responding.**

Whilst querying the relevant nodes in the database the unpublish event also calls GetPagedReferences from the controller. This call does produce a 200 retrieving
`"pageNumber":1,"pageSize":10,"totalPages":11,"totalItems":102`

A similar issue seems to be raised and resolved in https://github.com/umbraco/Umbraco-CMS/issues/12190 

### Specifics

https://localhost:44320/umbraco/backoffice/umbracoapi/trackedreferences/GetPagedDescendantsInReferences?parentId=7507&entityType=DOCUMENT&pageNumber=1&pageSize=10

### Steps to reproduce

Open a node in the CMS, open the dropdown that contains the unpublish button (the button that opens the confirmation overlay)
![image](https://user-images.githubusercontent.com/16354665/165332429-2c98802e-8080-4c5d-997a-e42afddb6fbe.png)
Click the button to unpublish the relevant document
![image](https://user-images.githubusercontent.com/16354665/165332610-2b1a4d67-a398-464b-b1d0-0c65a799291f.png)
Be met with a confirmation that there are indeed relevant nodes returned from the GetPagedReferences call whilst all nodes from the GetPagedDescendantsInReferences call are still being fetched
![image](https://user-images.githubusercontent.com/16354665/165333140-190d0d41-0c33-4cb5-a850-086d21d91121.png)
Be met with an error stating the database has timed out, in turn being unable to unpublish the relevant document.

### Expected result / actual result

Regardless of the outcome of the DB call the user should be able to unpublish an item if they desire to do so. As of right now the user is unable to unpublish documents in this state.

**Comment by beliskner** [comment]
It seems that adding
`.Where<NodeDto>(x => x.NodeId == parentId, "pn")

.Where<RelationDto>(x => x.ChildId == parentId || x.ParentId == parentId, "r");`
As was done in https://github.com/umbraco/Umbraco-CMS/issues/12190 resolves this issue. Unsure however if this produces the desired query results meant to be produced in the service function

**Comment by thomashdk** [comment]
> It seems that adding `.Where(x => x.NodeId == parentId, "pn")
> 
> .Where(x => x.ChildId == parentId || x.ParentId == parentId, "r");` As was done in #12190 resolves this issue. Unsure however if this produces the desired query results meant to be produced in the service function

Where do yo add this??

**Comment by bergmania** [comment]
@beliskner, feel free to try out the new implementation. You can replace the existing `ITrackedReferencesRepository` with a custom one and hopefully we can get it battle tested on your data. It's extremely hard to setup a realistic test data in this scenario.

**Comment by beliskner** [comment]
> @beliskner, feel free to try out the new implementation. You can replace the existing `ITrackedReferencesRepository` with a custom one and hopefully we can get it battle tested on your data. It's extremely hard to setup a realistic test data in this scenario.

Hi @bergmania the new query works like a charm. I do have some additions to this however, which is that the /umbracoapi/trackedreferences/GetPagedReferences?id={docId}&entityType=DOCUMENT&pageNumber=8&pageSize=10&filterMustBeIsDependency=true query is still quite slow (the pagination for item dependencies when trying to unpublish), but is not broken, so it is workable.


/umbracoapi/trackedreferences/GetPagedReferencedItems?entityType=undefined&pageNumber=undefined&pageSize=undefined this call when deleting a media item is unchanged, probably because your PR does not include a fix for this query. Would it be possible to include a union for this query as well? Otherwise we would still need to hijack the ITrackedReferencesRepository when 9.5.1 hits as deleting media is also essential.

**Comment by bergmania** [comment]
I can try to look into the other queries.. Not sure the same base query can be reused, but it can most likely be rewritten as well

**Comment by bergmania** [comment]
@beliskner, I have updated the other queries to use a similar technique. Are you able to verify a performance improvement? My data is a bit limited compared to real world scenarios.

**Comment by beliskner** [comment]
@bergmania I can now delete media with the new update, and the pagination of deleting items with /umbracoapi/trackedreferences/GetPagedReferences?id={docId}&entityType=DOCUMENT&pageNumber=8&pageSize=10&filterMustBeIsDependency=true feels faster, but I have no timer to verify that so it could be placebo.

Is it correct that the query for media only shows the media node that will be deleted, but not the places where this media node is being used?

**Comment by beliskner** [comment]
> Sounds incorrect, but not sure what scenario you are referring to.

That's my bad, I was deleting single selections from the media folder, so I got the multi deletion view portrayed in your situation 1. When I delete a media item through the actions menu when inside of the media node I do indeed get the dependencies listed.

Seems like a working solution to me! I've updated the hijacked repository we're using to reflect your PR and look forward to deleting this hijacked repository once 9.5.1 hits. Thanks for your time and fix @bergmania !

**Comment by beliskner** [comment]
And thank you for investigating a crucial bug! Teamwork makes the dream work!

**Comment by martinthogersen** [comment]
I'm encountering the same problem with Umbraco version 11.4.1.
The issue arises when I try to delete a page, as Umbraco initiates an API request to the following URL:

`/umbraco/backoffice/umbracoapi/trackedreferences/GetPagedDescendantsInReferences?parentId=261504&entityType=DOCUMENT&pageNumber=1&pageSize=10`

This URL takes 9 seconds or more to respond. Sometimes it leads to a timeout error.

Is there a solution available for this problem?
The problem started after upgrading to Umbraco 8.

**Comment by bergmania** [comment]
Hi @martinthogersen.

How much content do you have?

Maybe if you execute the query directly on you database you will have some better information.  Maybe some indexes the database suggest

**Comment by martinthogersen** [comment]
Hi @bergmania 

- Published content: 18,007 
- Users: 202,847

Is it recommended to add custom indexes?

**Comment by bergmania** [comment]
@martinthogersen,

Thanks.. 

No it is not recommended, but when I tested the queries it was not even near 9 seconds, even with 100.000 content nodes..

It sounds crazy with 200k+ users? Maybe you mean members?
That could potentially explain it as members is also content nodes.

**Comment by martinthogersen** [comment]
@bergmania Oops yes. Members.

**Comment by bergmania** [comment]
I don't think there is much we can do about it, when the amount of data is that massive.

I dream of introducing virtual members in the future, and that would help in this case.

For now, you should be able to replace the current implementation of `ITrackedReferencesService` with a no-op implementation, if you think that is a better solution.
