### ISSUE TITLE
Can't change members password through the CMS

### ISSUE THREAD

**Issue by jawood1** [umbraco/Umbraco-CMS#12306]
### Which *exact* Umbraco version are you using? For example: 9.0.1 - don't just write v9

8.18.3

### Bug summary

An issue was raised to us on one of our production sites currently on 8.18.1 that they were receiving an error when trying to manually reset a users password through the CMS.

On investigation I tested this locally to find the same issue. My first thought was to upgrade Umbraco to ensure if any fixes had been put in place so I upgrade to 8.18.3. On upgrade I re-tested and found the same issue. 

When changing the password the validation seems to fail with the error " Password cannot be changed without the old password".

![image](https://user-images.githubusercontent.com/47325234/165276300-15e958e5-c747-48d4-b1e5-fdbeb739897b.png)

### Specifics

Tested on chrome and firefox the same issue. looking in the console logs it's returning a bad request.
![image](https://user-images.githubusercontent.com/47325234/165276551-9761fd26-50ec-457f-bbe7-3a7c5ff5c530.png)

### Steps to reproduce

1. Go to a member
2. Change password
3. Attempt to save
4. Receive validation error.

### Expected result / actual result

Members password to update successfully.

**Comment by jawood1** [comment]
Update also when clicking reset password and clicking save nothing happens and the success message is some random code:
![image](https://user-images.githubusercontent.com/47325234/165278095-86f31e75-4945-49b4-8a95-3d6b0ac95248.png)

**Comment by nul800sebastiaan** [comment]
2 options: 

Check on `Reset password` checkbox and tap save, we'll generate a password for you to copy and give to the member, in this case `[rSrE$s;^Y`: 

![image](https://user-images.githubusercontent.com/304656/165287135-13519d55-acaa-45ee-a6d2-6902267dd272.png)

In Web.config change the `UmbracoMembershipProvider` to `allowManuallyChangingPassword="true"` and you can change the password for them from the backoffice without having to know the old password.

**Comment by nul800sebastiaan** [comment]
I just tested this last scenario and that indeed seems to have broken somewhere between 8.17 and 8.18. I'll mark as a regression and we'll work on getting it fixed.

**Comment by nul800sebastiaan** [comment]
The first scenario where we give you a new password for the member works though, as a workaround until then.

**Comment by nul800sebastiaan** [comment]
Update: when I revert this PR, it works as expected: 

https://github.com/umbraco/Umbraco-CMS/pull/11587

**Comment by elit0451** [comment]
Fixed in #12395

**Comment by CodeartIT** [comment]
This is again same issue in version 8.18.5

**Comment by huwred** [comment]
> This is again same issue in version 8.18.5

It works as expected for me in 8.18.5
