### ISSUE TITLE
Upgrade ImageSharp.Web to V2.0.0

### ISSUE THREAD

**Issue by andyfelton-equatedigital** [umbraco/Umbraco-CMS#12300]
### Which *exact* Umbraco version are you using? For example: 9.0.1 - don't just write v9

V9.4.3

### Bug summary

To be able to use AWS S3 for storage of image files ImageSharp.Web needs to be at version 2.0.0 to include https://github.com/SixLabors/ImageSharp.Web/pull/209.

### Specifics

The issue is to pull in code for the AWS S3 File Provider (see File Provider @ https://github.com/andyfelton-equatedigital/Umbraco.StorageProviders.AWSS3)

### Steps to reproduce

These details are from the Umbraco.StorageProviders.AWSS3.

Note to use on the current version (1.0.5) of ImageSharp.Web and Umbraco the following must be done:

Build Umbraco.Web.Common against the version of ImageSharp.Web on MyGet
ImageSharp.Web includes a breaking change, change CropWebProcessor.cs as shown here https://gist.github.com/andyfelton-equatedigital/9e5e02dd1ff53f3639e293ce911b7fba
Use your version of Umbraco.Web.Common on your project

### Expected result / actual result

Able to include https://github.com/andyfelton-equatedigital/Umbraco.StorageProviders.AWSS3 without having to rebuild Umbraco.

**Comment by nul800sebastiaan** [comment]
This is in the works: https://github.com/umbraco/Umbraco-CMS/pull/12185

**Comment by andyfelton-equatedigital** [comment]
@nul800sebastiaan Thanks for that I hadn't searched for Pull Requests only under issues - doh!

Am I reading this correctly that V2.0.0 will not be used on V9?

**Comment by nul800sebastiaan** [comment]
That's correct, due to breaking changes and the upcoming 9.5 being the last version of 9 we won't be able to include an updated version of ImageSharp in v9. v10RC is due out in a few weeks though, so you'll get your hands on it soon enough.

**Comment by nul800sebastiaan** [comment]
Closing this as it was fixed for v10.0.0
