### ISSUE TITLE
Dictionary item not working in block description

### ISSUE THREAD

**Issue by mrgiao** [umbraco/Umbraco-CMS#12310]
### Which *exact* Umbraco version are you using? For example: 9.0.1 - don't just write v9

9.4.3

### Description
Dictionary items can be accessed in backoffice by using the `#dictionaryName` syntax. This is possible for all fields, such as property labels, descriptions, tab names etc, except block descriptions. Block descriptions seem to be the only place where the field fails to access the dictionary correctly. See the following Hero example:

**1. Dictionary**

![image](https://user-images.githubusercontent.com/4223897/165368908-99d6471c-8cd8-411c-9b66-47c57ffdd00a.png)

**2. Doctype**
![image](https://user-images.githubusercontent.com/4223897/165369056-de4277a8-92c3-468b-8d2a-ad4f0c455d15.png)

**3. Block catalogue**
![image](https://user-images.githubusercontent.com/4223897/165369329-0bdc9d13-626a-454a-9555-5ad8582976fa.png)

**4. Block overlay editor**
![image](https://user-images.githubusercontent.com/4223897/165369918-55717b4e-8c6e-4e89-a724-306fd5e59629.png)

### Steps to reproduce

1. Create a dictionary item. eg. `dictionaryName`
2. Create a block list item.
3. Go to the block list item's document type view under `.../umbraco/settings/documentTypes/...`
4. Add the previously created dictionary item's name prefixed by `#`  to the block list item's `description` eg. `#dictionaryName`
5. Go to the Content tab and add content via the block catalogue.
6. Note how the block's description fails to access the dictionary item.

**Comment by rosrosros** [comment]
The same goes for Nested Content :-)
