### ISSUE TITLE
ContentTypeService.OnSaved & OnChanged not fired when copying document type

### ISSUE THREAD

**Issue by Fjellvang** [umbraco/Umbraco-CMS#12329]
### Which *exact* Umbraco version are you using? For example: 9.0.1 - don't just write v9

8.13.3

### Bug summary

The OnSaved & OnChanged Events Doesn't fire when copying MemberTypes, DocumentTypes & Media Types.

### Specifics

The reason is the events are never fired in the the overload defined here:

https://github.com/umbraco/Umbraco-CMS/blob/8a73bbb900075598b78c5f9edfaab2dbd4e53673/src/Umbraco.Core/Services/Implement/ContentTypeServiceBaseOfTRepositoryTItemTService.cs#L670

I'll submit a PR to fix it.

### Steps to reproduce

1. Listen on ContentTypeService.Saved or Changed.
2. Copy a document type.
3. See that no event is triggered

### Expected result / actual result

We expect a OnSaved Event to fire

**Comment by nul800sebastiaan** [comment]
Fixed in https://github.com/umbraco/Umbraco-CMS/pull/12330
