### ISSUE TITLE
Domains under "Culture and Hostnames" is ignored in Url Provider when publishing a node

### ISSUE THREAD

**Issue by DanielToft** [umbraco/Umbraco-CMS#12331]
### Which *exact* Umbraco version are you using?

9.4.3

### Bug summary

When publishing a node the umbraco DefaultUrlProvider is ignoring the domains configured under "Culture and Hostnames".

When debugging the DefaultUrlProvider, I can see that `umbracoContext.Content.GetRouteById(content.Id, culture);` is not returning a route with the domain id prefixed to the path.

This error only occurs on the node you publish. When you rebuild the cache or publish another node the error will disappear.

### Specifics

Video recording where you can see the bug:

https://sharing.clickup.com/clip/p/t2606201/739d77f1-cd50-4d0a-9d91-5d093717c504/screen-recording-2022-05-02-16%3A46.webm

### Steps to reproduce

Create 2 languages (da-DK and en-US)

Create 3 document types:
- Domain
- Language
- Page

Create a template for the "Page" Document type and output @Model.Url()

Create the following node structure:

Domain 1 (Doctype: Domain)
-- Danish (Doctype: Language + Add hostname "/" with language Danish)
---- Side 1  (Doctype: Page)
---- Side 2  (Doctype: Page)

Go to "Side 1". This node will now have the url "/side-1".

Now Save and Publish "Side 1" and reload the page "/side-1". You can now see that @Model.Url() is outputting "/danish/side-1"

---
_This item has been added to our backlog [AB#19320](https://dev.azure.com/umbraco/243e7927-03b2-44e2-908f-d4ac7ea5daaa/_workitems/edit/19320)_

**Comment by nul800sebastiaan** [comment]
I had a look. This scenario works in v9.3.1 but in 9.4.3 it is indeed broken as described in the repro steps (kudos for excellent minimal reproduction steps, very useful! 👍). 

As such, this is a regression that we should fix, I'll send it to the team.

**Comment by elit0451** [comment]
The issue has been fixed in #12404

**Comment by rolighed** [comment]
Wow. We need this fix released immediately!
