### ISSUE TITLE
v10.0.0-rc upgrade Error: Conflicting assets with the same target path 'umbraco/assets/css/canvasdesigner.min.css'. 

### ISSUE THREAD

**Issue by idseefeld** [umbraco/Umbraco-CMS#12359]
### Which *exact* Umbraco version are you using? For example: 9.0.1 - don't just write v9

10.0.0-rc

### Bug summary

I have upgrade a simple v9.4.3 or v9.5.0 site without any 3rd party packages to v10.0.0-rc.
Building the solution leads tor error: Conflicting assets with the same target path 'umbraco/assets/css/canvasdesigner.min.css'. ...

Having the new templates installed with `dotnet new -i Umbraco.Templates::10.0.0-rc1` I can not even build newly created v9.5.0 sites.
I get the erro: 
_CS0234	The type or namespace name 'Hosting' does not exist in the namespace 'Umbraco.Cms.Web.Common' (are you missing an assembly reference?)_
Restoring with `dotnet new -i Umbraco.Templates` fixes the second issue and I can again create and build v9.5.0.

### Steps to reproduce

1. Create a new version 9.5.0 Umbraco site
2. Update to 10.0.0-rc NuGet 
3. Build -> Error

**Comment by nathanwoulfe** [comment]
I think this is related to v10 changing to use embedded resources - I've found that deleting wwwroot/umbraco fixes the build.

**Comment by AndyButland** [comment]
Yes, I've found the same here.  An alternative I understand is to do a `dotnet clean` on your V9 install before upgrading to V10.

**Comment by nathanwoulfe** [comment]
That would be the more elegant way to do it 😁

Maybe worth adding it to the upgrade docs?

**Comment by bergmania** [comment]
I'll look into documenting what changes are recommended when upgrading

**Comment by bergmania** [comment]
### The main changes between v9 and v10 templates
## `Program.cs`
Updated to
```cs
 public class Program
    {
        public static void Main(string[] args)
            => CreateHostBuilder(args)
                .Build()
                .Run();

        public static IHostBuilder CreateHostBuilder(string[] args) =>
            Host.CreateDefaultBuilder(args)
                .ConfigureUmbracoDefaults()
                .ConfigureWebHostDefaults(webBuilder =>
                {
                    webBuilder.UseStaticWebAssets();
                    webBuilder.UseStartup<Startup>();
                });
    }
```

## `wwwroot/*`
Remove:
-  `wwwroot/umbraco` folder

## `umbraco/*`
Remove:
- `umbraco/PartialViewMacros`
- `umbraco/UmbracoBackOffice`
- `umbraco/UmbracoInstall`
- `umbraco/UmbracoWebsite`

**Comment by bergmania** [comment]
The Docs PR is here until it have been merged https://github.com/umbraco/UmbracoDocs/pull/3953/files

**Comment by bergmania** [comment]
The documentation is online https://our.umbraco.com/documentation/Fundamentals/Setup/Upgrading/version-specific#version-9-to-version-10

So I'll close this issue.

**Comment by bjarnef** [comment]
@bergmania following the steps in the guide, but when starting the application I noticed it creates a new SQLite database instead of using the existing LocalDB database. Is that expected?

![image](https://user-images.githubusercontent.com/2919859/175890510-9f9dcad3-13a3-4e6c-9c9a-ec03a6e72d73.png)

**Comment by bergmania** [comment]
@bjarnef, I guess this should only happen if you do not have a connectionstring in appsettings.

**Comment by bjarnef** [comment]
@bergmania yes, this it what I had in the existing v9 project running on LocalDB in /umbraco/Data folder. Apparently it was smart enough to use the database in this folder or because it is the default.

```
"ConnectionStrings": {
    "umbracoDbDSN": ""
}
```

**Comment by bergmania** [comment]
This is all handled in Umbraco Deploy, but you should be able to continue using the MDF file if you explicitly add a connectionstring to that file.

**Comment by AndyButland** [comment]
That's correct yes - see some notes [here](https://our.umbraco.com/documentation/Add-ons/Umbraco-Deploy/Upgrades/version-specific#database-initialization) in the upgrade to 10 details.

There's also a config setting you can use to "prefer LocalDb" - documented [here](https://our.umbraco.com/documentation/Add-ons/Umbraco-Deploy/Deploy-Settings/#preferlocaldbconnectionstring).

**Comment by bjarnef** [comment]
Thanks, specifying this connection string did the trick:

```
"ConnectionStrings": {
    "umbracoDbDSN": "Data Source=(localdb)\\MSSQLLocalDB;AttachDbFilename=|DataDirectory|\\Umbraco.mdf;Integrated Security=True"
  }
```

Worth mentioning if you already cloned the site and need to test changes. I this specific project mainly changes in Examine from v2 to v3.

**Comment by bjarnef** [comment]
@AndyButland thanks. Is `umbracoDbDSN_ProviderName` required or does it use `Microsoft.Data.SqlClient` by default if not specified?

**Comment by ronaldbarendse** [comment]
> Is `umbracoDbDSN_ProviderName` required or does it use `Microsoft.Data.SqlClient` by default if not specified?

If you omit this value, it indeed defaults to `Microsoft.Data.SqlClient` and therefore is only required when using SQLite right now (but it's still best practice to explicitly set it, so you're aware of this setting/value).

When using Umbraco Deploy using an empty connection string, it will default to using SQLite, even when you already have a LocalDB file in your data directory. As Andy mentioned you can either explicitly configure the connection string or enable the `PreferLocalDbConnectionString` setting. Using the setting has the benefit of being able to use the same settings for both Windows and Mac/Linux environments, as the explicitly configured LocalDB connection string won't work cross-platform.
