### ISSUE TITLE
v10 RC1: appsettings-schema.json is not part of the build anymore

### ISSUE THREAD

**Issue by bergmania** [umbraco/Umbraco-CMS#12362]
### Which *exact* Umbraco version are you using? For example: 9.0.1 - don't just write v9

10.0.0-rc1

### Bug summary

The `appsettings-schema.json` is missing.

### Steps to reproduce

Use 10.0.0-rc1 and the `appsettings-schema.json` file is missing, due to other files now served from RCL

### Expected result / actual result

Intellisense in appsettings needs to be restored :)

---
_This item has been added to our backlog [AB#19371](https://dev.azure.com/umbraco/243e7927-03b2-44e2-908f-d4ac7ea5daaa/_workitems/edit/19371)_

**Comment by nikolajlauridsen** [comment]
This has been fixed in #12416 🎉
