### ISSUE TITLE
Unable to log in to convert Umbraco 8 to Umbraco 9.5.0 - umbracoTwoFactorLogin

### ISSUE THREAD

**Issue by russellshome** [umbraco/Umbraco-CMS#12389]
### Which *exact* Umbraco version are you using? For example: 9.0.1 - don't just write v9

9.5.0

### Bug summary

After starting Umbraco 9.5.0 using an Umbraco 8 database, login fails even when correct login/password are entered.

### Specifics

I have a working Umbraco 8.17.1 website.
I attempted to connect to that database using a newly created Umbraco 9.5.0 website
Login failed.
Reset password and attempted again - failed to log in.

I downgraded to 9.4.3, connected to the same database and that works - I was able to log in and convert.

### Steps to reproduce

Take an existing working Umbraco8 website database.
Take note of the login/pass of the admin
Connect an Umbraco 9.5.0 website to that database & run
Attempt to log in
This will fail.

### Expected result / actual result

Login should work so that conversion of website from Umbraco8 to Umbraco 9 can proceed using >= 9.5.0.

**Comment by nathanwoulfe** [comment]
Hey @russellshome have you tried setting the unattended install options in appsettings.json?

Pretty sure this is required now (I did a database upgrade earlier this week, from 8.17 to 9.5, worked perfectly with those settings in place).

**Comment by russellshome** [comment]
Are you referring to https://our.umbraco.com/documentation/reference/V9-Config/UnattendedSettings/

"This is a feature that allows Umbraco to install without using the UI. If you don't intended to use this feature, you don't need to configure this."

It sounds like you are saying that the documentation is now incorrect since it says you don't need to configure this when using the UI.

**Comment by p-m-j** [comment]
Would you be able to supply the following.

1. The result of the sql query below (an integer)
2. The full value of UsersMembershipProvider from web.config
3. The values of the validation & decryption attributes on the MachineKey element in web.config (if present)

```sql
select len(userPassword) as hashLength
from umbracoUser 
where userEmai = '{{email of account which cannot login}}'
```
