### ISSUE TITLE
V9 When a Block List Editor is the last property on a tab, it's components properties have little to no spacing.

### ISSUE THREAD

**Issue by mennomout** [umbraco/Umbraco-CMS#12388]
### Which *exact* Umbraco version are you using? For example: 9.0.1 - don't just write v9

9.5.0

### Bug summary

When using a block list editor at the bottom of a tab the margins between properties inside selected components have: `margin-bottom: 0!important;` This causes them to collide or have little to no vertical spacing.

### Specifics

As seen in the image below there is no margin between the different properties inside the chosen components from the BLE with Inline Editing enabled. This issue will only occur if there are no other properties below it on the same tab. Adding any other property below it like a textString will fix the spacing.

![MarginIssueBLE](https://user-images.githubusercontent.com/77411834/167808969-c694a2ff-be00-41ec-8850-913841b17ce9.png)

### Steps to reproduce

Add a Block List Editor to a tab and make it the last property of said tab. 

### Expected result / actual result

Expected well spaced properties. Right now there is no or very little spacing between the different properties.

**Comment by mennomout** [comment]
@sebastian-claesson This issue has been around for a while and this post is stale. Are there any planned fixes for this issue?

**Comment by sebastian-claesson** [comment]
@mennomout wrong Sebastian 😁

**Comment by mennomout** [comment]
@sebastian-claesson My apologies! I've changed the mention.

**Comment by mennomout** [comment]
@nul800sebastiaan This issue persists in V10.2: 
![image](https://user-images.githubusercontent.com/77411834/202181686-52710441-9f39-44ab-aae7-cef6970db85b.png)

Sorry for tagging you again. Is there any information about if and when this is going to get fixed?

**Comment by markadrake** [comment]
The following rule:

```
umb-property:last-of-type .umb-control-group {
    margin-bottom: 0!important;
}
```

Can be made more specific:

```
umb-property:last-of-type > .umb-property > ng-form > .umb-control-group
```

To restore the bottom margin to nested property editors.

**Comment by Zeegaan** [comment]
@mennomout Sorry for the late answer here, but i am having trouble reproducing this 🤔 
Here is me with 2 properties and then a blocklist as the last property: 
![image](https://user-images.githubusercontent.com/70372949/210058938-bc80278c-11c6-44ae-ba6e-46710764000e.png)
Do i have something set up wrong here ? 😅

**Comment by mennomout** [comment]
@Zeegaan Thank you for the reply. It's about the blocks inside the the Block List Editor. So in your set up you could add some blocks to the Block List editor and the spacing between those would be wrong.

**Comment by nikolajlauridsen** [comment]
Hey @mennomout, I just had a look at reproducing this, and can indeed confirm that the blocks are missing vertical spacing. I'll go ahead and mark this as up for grabs for now 😄

**Comment by mennomout** [comment]
@markadrake Thank you for the input. Are you able to make a pull request for this fix?

**Comment by markadrake** [comment]
> @markadrake Thank you for the input. Are you able to make a pull request for this fix?

Sure thing @mennomout. I'll submit a PR early next week. Got it on my calendar.

**Comment by markadrake** [comment]
Hopefully with minimal changes to the LESS, there won't be any side effects. I've highlighted the spacing issues in yellow:

<img width="430" alt="image" src="https://user-images.githubusercontent.com/713355/231944345-8b60c924-3500-4a0e-9aa2-36514c6beaf7.png">


<img width="431" alt="image" src="https://user-images.githubusercontent.com/713355/231944145-bd1c6e2c-4437-4db2-a345-529a2cc41b46.png">
