### ISSUE TITLE
Umbraco TV references in the installation screen should be changed to Umbraco Learning Base

### ISSUE THREAD

**Issue by eshanrnh** [umbraco/Umbraco-CMS#12396]
### Which *exact* Umbraco version are you using? For example: 9.0.1 - don't just write v9

9.5.0

### Bug summary

While installing Umbraco version 9.5.0 locally, the installation screen containing Umbraco TV should be replaced with Umbraco Learning Base. Below are the screenshots.

![image](https://user-images.githubusercontent.com/82437098/168096088-743fec94-6fec-4bd0-a88f-b476c2825446.png)

![image](https://user-images.githubusercontent.com/82437098/168096052-0f6275ce-4553-4bf2-9e0a-acc22f4e21e8.png)

### Steps to reproduce

1. Install Umbraco Locally

### Expected result / actual result

1. Did You Know screen: _umbraco.tv is the premier source of Umbraco video tutorials to get you started_ should be replaced with "**Umbraco Learning Base is the  premier source of Umbraco product videos to get you started**"
2.  Open Umbraco screen: _Easy start with Umbraco.tv_ should be replaced with "**Easy start with Umbraco Learning Base**". Also the umbraco.tv link should be replaced with the [Umbraco Learning Base](https://www.youtube.com/channel/UCbGfwSAPflebnadyhEPw-wA).

**Comment by mikecp** [comment]
Closed by merge of PR #12399
