### ISSUE TITLE
HtmlStringUtilities.StripHtmlTags not working any more

### ISSUE THREAD

**Issue by Andrei-** [umbraco/Umbraco-CMS#12400]
### Which *exact* Umbraco version are you using? For example: 9.0.1 - don't just write v9

9.3.1

### Bug summary

HtmlStringUtilities.StripHtmlTags() is using HtmlAgilityPack, doing something like:
```
doc.LoadHtml("<p>" + html + "</p>");
...
var nodes = doc.DocumentNode.FirstChild.SelectNodes(".//*");
```
In the latest versions of HtmlAgilityPack the second line call from above returns null, killing the utility method.

### Steps to reproduce

Just try the following code in a razor view.
`@Html.StripHtml("<p>Some text<span>More text</span></p>", "p")`
The code above attempts to remove 'p' tags and is calling HtmlStringUtilities.StripHtmlTags() inside.

**Comment by LeeDalchow** [comment]
I was able to replicate this in my own environment.

This looks like a good first contribution, ok for me to pick this up?

Ok for

**Comment by Andrei-** [comment]
Hi Lee,

Not sure if it's me you're asking, but if you are, yes sure, no problem, go
ahead.

BR,
/Andrei

**Comment by LeeDalchow** [comment]
Hi Andrei, I deleted my original comment since I noticed the HQ devs usually add a label community/up-for-grabs so I thought I'd remove it and wait for them to review first.

**Comment by JarnoVWA** [comment]
+1 for umbraco v9.5.0-rc3
