### ISSUE TITLE
Bad page caching

### ISSUE THREAD

**Issue by petr-vojtech** [umbraco/Umbraco-CMS#12431]
### Which *exact* Umbraco version are you using? For example: 9.0.1 - don't just write v9

9.5.0

### Bug summary

I'm having trouble viewing product pages that differ in URL.
The URL does not match the content displayed in the browser.
I think Umbraco incorrectly caches content by URL.

Please help.
Thank you, Petr

### Steps to reproduce

I have both of the URLs below in my favorites.
So I only click on these links.

A. Showing the 1st product
https://test-cd.hennlich.cz/cs/tesneni/r002300-0200si70
The page content is OK
<img width="887" alt="Step1Product1" src="https://user-images.githubusercontent.com/81760128/169252988-2d4b28cd-e491-48e4-97b8-0233a8c64425.png">

B. Showing the 2nd product
https://test-cd.hennlich.cz/cs/tesneni/r004000-0200fp75f
The page content is OK
<img width="899" alt="Step2Product2" src="https://user-images.githubusercontent.com/81760128/169252993-dc21f228-b072-48c9-baad-43fe2858bc91.png">

C. Showing the 1st product again
https://test-cd.hennlich.cz/cs/tesneni/r002300-0200si70
Page content is incorrect, shows the 2nd product page!
<img width="894" alt="Step3ContentError" src="https://user-images.githubusercontent.com/81760128/169252994-8ea5b055-5829-4ae1-94ee-2a2fef12bafb.png">

**Comment by nul800sebastiaan** [comment]
Hi there @petr-vojtech  - this sounds like an excellent question for the forums where our friendly community can help you find the best solution for your requirements. 

Make sure to head on over to https://our.umbraco.com and ask follow up questions there! 👍

**Comment by petr-vojtech** [comment]
Thank you for your response. This is a custom caching error. I'm sorry, I didn't think of that right away.
