### ISSUE TITLE
Umbraco 10 -  ICU problem with userId (int) converted to string

### ISSUE THREAD

**Issue by alevak09** [umbraco/Umbraco-CMS#12450]
### Which *exact* Umbraco version are you using? For example: 9.0.1 - don't just write v9

10.0.0-rc1 & 10.0.0-rc2

### Bug summary

Just tested Umbraco 10.0.0-rc1 and rc2 for the same culture [error](https://github.com/umbraco/Umbraco-CMS/issues/12384) caused on the Umbraco  9.5.0
Here is the fix provided for the Umbraco 9.5.0 and this fix should be applied for the Umbraco 10 as well.

Link to fix: [https://github.com/umbraco/Umbraco-CMS/pull/12420](https://github.com/umbraco/Umbraco-CMS/pull/12420)

![error-icu](https://user-images.githubusercontent.com/73195407/169786389-1e59da92-69d0-4ff0-9f18-89ee29ec9233.PNG)

### Steps to reproduce

For the current user in the backoffice change language/culture to e.g. Swedish and hit CTRL+F5, the error will emerge.

**Comment by nikolajlauridsen** [comment]
Thanks for reporting, the fix for this has been merged to the 10 release branch, and should be fixed in the next RC 🎉
