### ISSUE TITLE
[v10] IScopeProvider.CreateScope should return Umbraco.Cms.Core.Scoping.IScope

### ISSUE THREAD

**Issue by mattbrailsford** [umbraco/Umbraco-CMS#12460]
### Which *exact* Umbraco version are you using? For example: 9.0.1 - don't just write v9

v10-rc4

### Bug summary

When using `IScopeProvider.CreateScope` in namespace `Umbraco.Cms.Core.Scoping`, this should return `Umbraco.Cms.Core.Scoping.IScope` however it is currently set to return `Umbraco.Cms.Infrastructure.Scoping.IScope`, this causes compilation errors when attempting to assign the result to an `IScope` variable.

### Steps to reproduce

* Resolve an `IScopeProvider` from the `Umbraco.Cms.Core.Scoping` namespace
* Create an `IScope` local variable and set it's value to `_scopeProvider.CreateScope()`
* Get a compilation error `Cannot implicitly convert type Umbraco.Cms.Infrastructure.Scoping.IScope to Umbraco.Cms.Core.Scoping.IScope

### Expected result / actual result

`IScopeProvider.CreateScope` in namespace `Umbraco.Cms.Core.Scoping` should return `Umbraco.Cms.Core.Scoping.IScope`

**Comment by p-m-j** [comment]
@mattbrailsford can you have a glance at #12465 to confirm it should resolve the issue?

**Comment by mattbrailsford** [comment]
@p-m-j looks like it should yea 👍

**Comment by p-m-j** [comment]
Closed by #12465
