### ISSUE TITLE
[v10] BackOfficeSecurity.GetUserId() un-depricated breaking change

### ISSUE THREAD

**Issue by mattbrailsford** [umbraco/Umbraco-CMS#12461]
### Which *exact* Umbraco version are you using? For example: 9.0.1 - don't just write v9

v10-rc4

### Bug summary

In Umbraco v9 `BackOfficeSecurity.GetUserId()` would return `Attempt<int>` however in v10 this has been changed to `Attempt<int?>` which is a breaking change with no deprication period provided.

### Steps to reproduce

n/a

### Expected result / actual result

It expect a new method should be created for the new implementation and the old metho depricated

**Comment by mattbrailsford** [comment]
I am wondering, is there a need for `GetUserId` to return `Attempt<int?>`? Given this is an Attempt object, shouldn't this be non-nullable anyway as when would it every be successfull and have a null value? Doesn't success denoate a value had to be returned?

**Comment by Zeegaan** [comment]
This should now be fixed in https://github.com/umbraco/Umbraco-CMS/pull/12468, thanks for reporting! 🐛
