### ISSUE TITLE
[v10] `ScopeContextualBase.Get` now only accepts `ICoreScopeProvider`

### ISSUE THREAD

**Issue by mattbrailsford** [umbraco/Umbraco-CMS#12478]
### Which *exact* Umbraco version are you using? For example: 9.0.1 - don't just write v9

10.1.0--alpha.1.preview.15.ge647920

### Bug summary

We previously used ScopeContextualBase to register a transaction aware callback where the method signature was previously 

````csharp
ScopeContextualBase.Get<T>(IScopeProvider scopeProvider, string key, Func<bool, T> ctor);
````

However this appears to now be only available with the signature

````csharp
ScopeContextualBase.Get<T>(ICoreScopeProvider scopeProvider, string key, Func<bool, T> ctor);
````

As `ScopeContextualBase` is public, this should be deemed a breaking change and as such there should be both implementations of this method availble with the original being marked as obsolete.

### Specifics

n/a

### Steps to reproduce

1. Resolve an `Umbraco.Cms.Core.Scoping.IScopeProvider` to a variable `_scopeProvider`
2. Attempt to call `ScopeContextualBase.Get<int>(_scopeProvider,  "test", (scoped) => 1);`
3. Receive warning `Cannot convert type Umbraco.Cms.Core.Scoping.IScopeProvider to Umbraco.Cms.Core.Scoping.ICoreScopeProvider`

### Expected result / actual result

Both methods should exist with the original being marked obsolete and so there should be no compile time error, but a warning to suggest to move to the new method.

**Comment by p-m-j** [comment]
Presumably this is since #12465 as before that `Umbraco.Cms.Core.Scoping.IScopeProvider` implemented ICoreScopeProvider (via Infrastructure.Scoping.IScopeProvider)

**Comment by p-m-j** [comment]
Closed via https://github.com/umbraco/Umbraco-CMS/pull/12465 rc4 should land today

**Comment by mattbrailsford** [comment]
I'm not sure this is closed. This was tested on this mornings nightly build and it is the fact `IScopeProvider` doesn't implemt `ICoreScopeProvider` and so the `ScopeContextualBase.Get` method now needs 2 implementations one for each provider type as neither are convertable.

**Comment by p-m-j** [comment]
@mattbrailsford oops that was "closed via https://github.com/umbraco/Umbraco-CMS/pull/12480"

**Comment by mattbrailsford** [comment]
@p-m-j ahh perfect. Will there be a new nightly later today? or will it be tomorrow now?

**Comment by p-m-j** [comment]
https://dev.azure.com/umbraco/Umbraco Cms/_build/results?buildId=93983 will stick in on myget on the [prereleases feed ](https://www.myget.org/F/umbracoprereleases/api/v3/index.json ) in about 20 minutes time, but this one is a bit of a pain to work with as we are blasting over 10.0.0-rc4 multiple times so local nuget caches can be a pain.

The real rc4 build should be on nuget later today.

I'd stick to testing the rc's instead of the nightlies as 10.1.0 is still some way off, 10.0.0 isn't out yet

**Comment by mattbrailsford** [comment]
No worries, I'm just trying to make sure I can re-test all these updates so as long as releases keep going out, I'm happy to test which ever 👍

**Comment by mattbrailsford** [comment]
Hmm, testing RC4 and #12465 seems to not be applied. Is this the one that got build today and what I should be testing against?

**Comment by p-m-j** [comment]
I just grabbed from nuget and it LGTM, have you got an old build from the prerelease feed cached?

![image](https://user-images.githubusercontent.com/2056399/170268313-5f16c39b-f872-4272-99ae-d57d2b4f6f30.png)

**Comment by mattbrailsford** [comment]
Let me purge my cache and check 👍

**Comment by mattbrailsford** [comment]
Yup, that was it 👍
