### ISSUE TITLE
Umbraco backoffice user is created with userDisabled = 1 after auto linking with external login provider

### ISSUE THREAD

**Issue by gunnim** [umbraco/Umbraco-CMS#12487]
### Which *exact* Umbraco version are you using? For example: 9.0.1 - don't just write v9

9.5.0

### Bug summary

Umbraco backoffice user is created with userDisabled = 1 (IsApproved false ?) after auto linking with external login provider.

### Specifics

We are using Azure AD as an external login provider for umbraco backoffice authentication, on initial login and auto-linking the user is greeted with a white Umbraco backoffice, red errors on bottom of page and in console, saying forbidden 403

Viewing the user in db shows the user has userDisabled=1 even though the login appeared to be successful
Stepping through the umbraco backoffice code, everything seems to go swimmingly but afaics it looks like the backoffice identity model currently has default property values that are incompatible with auto-linking ?

```
var extLoginOpts = new ExternalSignInAutoLinkOptions(
    autoLinkExternalAccount: true,
    defaultUserGroups: new[] { "admin" },
    defaultCulture: "en-US",
    allowManualLinking: true)
{
    OnAutoLinking = (user, loginInfo) =>
    {
        // The following line fixes the issue
        // user.IsApproved = true;
    },
}
```

```
return umbracoBuilder.AddBackOfficeExternalLogins(extLoginBuilder =>
    extLoginBuilder.AddBackOfficeLogin(
    auth =>
    {
        auth
            // https://github.com/umbraco/Umbraco-CMS/pull/9470
            .AddMicrosoftIdentityWebApp(options =>
            {
                options.CallbackPath = "/umbraco-signin-oidc/";
                options.Instance = "https://login.microsoftonline.com/";
                options.TenantId = azAdConfig["TenantId"] ?? _vettvangurTenantId;
                options.ClientId = azAdConfig["ClientId"] ?? _vettvangurClientId;
                options.SignedOutRedirectUri = "/umbraco";

                // https://github.com/AzureAD/microsoft-identity-web/issues/749
                //options.ClaimActions.MapJsonKey(ClaimTypes.Email, ClaimConstants.PreferredUserName);

                // Preferred over IClaimsTransformation which runs for every AuthenticateAsync
                options.Events.OnTokenValidated = ctx =>
                {
                    var username = ctx.Principal?.Claims.FirstOrDefault(c => c.Type == ClaimConstants.PreferredUserName);
                    if (username != null && ctx.Principal?.Identity is ClaimsIdentity claimsIdentity)
                    {
                        claimsIdentity.AddClaim(
                            new Claim(
                                ClaimTypes.Email,
                                username.Value
                            )
                        );
                    }

                    return Task.CompletedTask;
                };
            },
            openIdConnectScheme: auth.SchemeForBackOffice(Constants.AzureAd),
            cookieScheme: "Fake"
            );
    },
    loginProviderOptions =>
    {
        loginProviderOptions.ButtonStyle = "btn-microsoft";
        loginProviderOptions.Icon = "fa-windows";
        loginProviderOptions.AutoLinkOptions = extLoginOpts;
        loginProviderOptions.AutoRedirectLoginToExternalProvider = false;
    })
);
```

### Steps to reproduce

Use the code shown in specifics and login via the azure ad external login provider

### Expected result / actual result

with auto linking enabled for backoffice identities, after a successful login, the user should successfully arrive in the umbraco backoffice.

**Comment by w805756054** [comment]
Hi gunnim, I have the same problem, have you found a solution?

**Comment by gunnim** [comment]
@w805756054 the earlier code snippet has a line commented with "The following line fixes the issue". Try it out :)

**Comment by w805756054** [comment]
Thank you, have a nice day!

**Comment by Migaroez** [comment]
Hey @gunnim, this seems like expected behavior as Umbraco can not be sure that any account that exists on the external login provider is actually authorized to login to Umbraco. If you fully trust your external login provider and there is no way for an account outside of your control to autolink with Umbraco, then feel free to just set `user.IsApproved` to `true`. But if for example you would use github then it might be a good idea to check whether the external user is for example part of a specific organization before trusting them.

Hope this clarifies everything. Have a good day!
