### ISSUE TITLE
Logging out as a Member using 2FA throws an error

### ISSUE THREAD

**Issue by eshanrnh** [umbraco/Umbraco-CMS#12507]
### Which *exact* Umbraco version are you using? For example: 9.0.1 - don't just write v9

10.0.0-rc3 and 9.5.0

### Bug summary

Followed the [documentation](https://our.umbraco.com/documentation/Reference/Security/Two-factor-authentication/) to test 2FA for Members in Umbraco 10. While logging out as a member, the **Edit Profile** view throws the following error. It's the same issue for v9 as well.

![image](https://user-images.githubusercontent.com/82437098/171146128-c01798f8-cbfd-421a-841e-7d98bbc9eda6.png)

### Specifics

https://user-images.githubusercontent.com/82437098/171158432-0006ec6d-c78d-4583-973c-55492eb17a0a.mp4

### Steps to reproduce

1. Add Login/ Register Member partial view macros.
3. Create a document type using  a Richtext Editor and add the macros.
4. Implement 2FA for Members using the [documentation](https://our.umbraco.com/documentation/Reference/Security/Two-factor-authentication/).
5. Register as a Member on the frontend.
6. Login as a Member on the frontend.
7. Setup 2FA for the registered member.
8. Logout as a Member.

### Expected result / actual result

After logging out should land on the Home Page/Register Page.

**Comment by Zeegaan** [comment]
I can no longer reproduce this, as it has been a while (sorry about that 🙈) I will assume this has been fixed. Please let me know if you run into this issue, and we'll take a look 🙌 Thanks for reporting 🐛
