### ISSUE TITLE
Changing element in a nested blocklist, document in content will get stuck

### ISSUE THREAD

**Issue by vladdes** [umbraco/Umbraco-CMS#12504]
### Which *exact* Umbraco version are you using? For example: 9.0.1 - don't just write v9

9.2.2

### Bug summary

Removed an element from a nested blocklist, added a new element. Then went to Content and got an eternal loading three dots, checked console and got "TypeError: Cannot read properties of null (reading 'contentTypeName')"

### Specifics

![image](https://user-images.githubusercontent.com/7382715/170991126-4c63ecad-dbc2-4fe9-9f3b-e87ce106c087.png)
Event page has a blocklist which contains an element called Event Page Sidebar

![image](https://user-images.githubusercontent.com/7382715/170991045-ae191d94-bb39-4512-b93e-7b1ed9e97c6d.png)
Event Page Sidebar has a property called upcoming dates, here I switched to a new element

![image](https://user-images.githubusercontent.com/7382715/170990868-3e94c4fe-94ab-4f3d-8856-18d691bb8bff.png)
Content didn't respect that change.

### Steps to reproduce

Create a Document Type (page). 

Give it a Blocklist property

Add an Element that also holds a Blocklist property with an Element 

Create some content with that given structure

Go to Settings, in the Child Blocklist, remove the element and create a new one

save and go to your Document in Content, open the Parent Blocklist there, the Child will get a three dots loading forever, check console. 

### Expected result / actual result

Removal of an element should not cause an error.

**Comment by Zeegaan** [comment]
Hey @vladdes, so sorry about the late answer here!
This has now been fixed in 10, and following your steps here will now meet you with a helpful screen instead 👍 
![image](https://user-images.githubusercontent.com/70372949/209924245-6050e356-5525-4b24-9cae-e6d0930cbb03.png)
