### ISSUE TITLE
RTE distraction free mode cannot insert link in Chrome

### ISSUE THREAD

**Issue by nikcio** [umbraco/Umbraco-CMS#12508]
### Which *exact* Umbraco version are you using? For example: 9.0.1 - don't just write v9

8.18.2 & 10.0.0-rc3

### Bug summary

It seems that the link insertion function that the RTE has in distraction-free mode has stopped working on Chrome versions.

Chrome versions tested:
Version 102.0.5005.61 
Version 102.0.5005.63

![image](https://user-images.githubusercontent.com/24605285/171174101-e14d65b1-2e40-41ec-9464-567670a9dfe1.png)

### Steps to reproduce

1. Create a doctype with a Rich Text editor
2. Set the mode to distraction-free 
3. Try to insert a link to some text

**Comment by perspectivo-rs** [comment]
The same in Safari...

**Comment by elit0451** [comment]
Hi @nikcio 👋 
Appologies for the late response! I've made an attempt to test on the latest Umbraco 10 (_10.3.2_) on Chrome (_107.0.5304.122_) and it doesn't seem to be a problem anymore _(check the video below)_. Once inserted, the link is there, though I agree it can be a bit more visible when in Distraction Free mode 🤷 


https://user-images.githubusercontent.com/21998037/204492269-cc55cc61-30e3-4631-beb9-7d1dee3a5491.mp4

</br>

Regarding your comment, @perspectivo-rs, I had a chance to test once again Umbraco 10.3.2 (_current latest_) in Safari (MacOS Ventura). Same applies as my comment about Chrome ⬆️ - the links are there for me 🙂 


https://user-images.githubusercontent.com/21998037/204492198-0bdc9834-64c2-4180-8119-d4a2579b8089.mp4

</br>

Let me know if I am missing something! 😁

**Comment by nikcio** [comment]
Great! Seems not to be a problem anymore then. I'll close 😄
