### ISSUE TITLE
GetCropUrl method not working

### ISSUE THREAD

**Issue by ssplyuvrajsingh** [umbraco/Umbraco-CMS#12503]
### Which *exact* Umbraco version are you using? For example: 9.0.1 - don't just write v9

8.9.0

### Bug summary

This method does not work in Umbraco 8.9.0.

I try with this - <img  src="@(Url.GetCropUrl(ourProcessVideoPoster, height: 90, width: 800))" />

### Steps to reproduce

![image](https://user-images.githubusercontent.com/58556669/170957776-e87dbe8f-f7a2-472a-9e88-db973c3dd8ba.png)

**Comment by nul800sebastiaan** [comment]
Hi there @ssplyuvrajsingh, this sounds like an excellent question for the forums where our friendly community can help you find the best solution for your requirements. 

Make sure to head on over to https://our.umbraco.com and ask follow up questions there! 👍
