### ISSUE TITLE
v10: SQLite only supported via DTO based migrations

### ISSUE THREAD

**Issue by mattbrailsford** [umbraco/Umbraco-CMS#12506]
### Which *exact* Umbraco version are you using? For example: 9.0.1 - don't just write v9

v10.0.0-rc5

### Bug summary

Within Umbraco it's possible to write DB migrations in 2 ways. 

**1) DTO based migrations**
````csharp
// Table definition
[TableName("BlogComments")]
[PrimaryKey("Id", AutoIncrement = true)]
[ExplicitColumns]
public class BlogCommentSchema
{
    [PrimaryKeyColumn(AutoIncrement = true, IdentitySeed = 1)]
    [Column("Id")]
    public int Id { get; set; }

    [Column("BlogPostUmbracoId")]
    public int BlogPostUmbracoId { get; set; }

    [Column("Name")]
    public string Name { get; set; }

    [Column("Email")]
    public string Email { get; set; }

    [Column("Website")]
    public string Website { get; set; }

    [Column("Message")]
    [SpecialDbType(SpecialDbTypes.NTEXT)]
    public string Message { get; set; }
}

// Migration execution
Create.Table<BlogCommentSchema>().Do();
````

**2) Explicit migrations**
````csharp
Create.Table("BlogComments")
    .WithColumn("Id").AsInt().NotNullable().PrimaryKey()
    .WithColumn("BlogPostUmbracoId").AsInt().NotNullable()
    .WithColumn("Name").AsString(255).NotNullable()
    .WithColumn("Email").AsString(255).NotNullable()
    .WithColumn("Website").AsString(255).NotNullable()
    .WithColumn("Message").AsString(int.Max).NotNullable()
    .Do();
````

It appears that SQLite support has only been added for DTO migrations. Attempting to create a table with an explicit migration will fail as the default implementation executes PK/FKs as `ALTER TABLE` statements adding the constraints which is not supported by SQLite.

### Steps to reproduce

Create a migration with the following code

````csharp
Create.Table("TestTable")
    .WithColumn("Id").AsInt().NotNullable().PrimaryKey()
    .Do();
````

Migration will fail as PK is incorrectly added as an `ALTER TABLE` statement where it HAS to be part of the `CREATE TABLE` statement for SQLite.

### Expected result / actual result

I expected the migration to run and the relevant PK/FK constraints to be created.

**Comment by mattbrailsford** [comment]
The reason I believe this to be the case as this is the only place I can find where SQLite handles creating the table https://github.com/umbraco/Umbraco-CMS/blob/v10/contrib/src/Umbraco.Cms.Persistence.Sqlite/Services/SqliteSyntaxProvider.cs#L242 and this is only called here https://github.com/umbraco/Umbraco-CMS/blob/v10/contrib/src/Umbraco.Infrastructure/Migrations/Expressions/Create/Table/CreateTableOfDtoBuilder.cs#L36

But when using explicit migrations, constraints are added as additional expressions https://github.com/umbraco/Umbraco-CMS/blob/v10/contrib/src/Umbraco.Infrastructure/Migrations/Expressions/Create/Table/CreateTableBuilder.cs#L103 and then all executed independently https://github.com/umbraco/Umbraco-CMS/blob/d0a752248ec92ca0703a0439d1260cd81ba9dc2a/src/Umbraco.Infrastructure/Migrations/MigrationExpressionBase.cs#L82

**Comment by p-m-j** [comment]
Closed by https://github.com/umbraco/Umbraco-CMS/pull/12518, thanks for the report h5yr!

**Comment by mattbrailsford** [comment]
I can confirm #12518 solves my issue 👍
