### ISSUE TITLE
Install Screen after Visual Studio Deploy to Azure AppService

### ISSUE THREAD

**Issue by alandraper** [umbraco/Umbraco-CMS#12511]
### Which *exact* Umbraco version are you using? For example: 9.0.1 - don't just write v9

9.5.0

### Bug summary

After using web deploy to Azure, we're getting the install screen, even though Umbraco is already installed. 

### Specifics

https://www.shakespearetavern.com 

This seems to happen whether I deploy directly to the site, or deploy to an Azure App Service Slot and perform a "swap" to make it live. 

We have already upgraded both the test and live sites to 9.5, so I don't know what is triggering the install screen. 

I do know that the SQL connection string is correct and working. 

### Steps to reproduce

![image](https://user-images.githubusercontent.com/13674761/171217797-e18cefad-9eb2-490e-b088-aa2383f54faa.png)

### Expected result / actual result

This is not a new installation, nor is it an upgrade. I should be able to deploy changes from Visual Studio without seeing the install screen on the public-facing site.

**Comment by alandraper** [comment]
I should mention this behavior never happened before the update to 9.5

**Comment by alandraper** [comment]
I just did a command-line publish from Visual Studio Code and I get the same result.

**Comment by bergmania** [comment]
@alandraper.. The install screen should only ever show, when no DB is configured. Are you sure you publish the connection string, and if the connection string is in an appsettings.{environment}.json, it matches the correct environment, e.g. Production?

**Comment by alandraper** [comment]
I know, but I had a test page print out  ConfigurationRoot.
GetConnectionString("umbracoDbDSN") and I got the correct value before
getting the Umbraco installation screen. Then, heading to the home page, or
to Umbraco would bring up that install prompt. I would go through the
installation using that same connection string, and the install screen
would immediately finish and go to the "Restarting and redirecting you to
Umbraco" message. It would lag there for a while, and then the site would
be fine, until I had to publish any updates from Visual Studio.

Maybe there was some remnant from the previous Umbraco lurking? I spent a
day on Sunday rebuilding the site from scratch, and now I can publish
without re-installing, so I think you can close this.
