### ISSUE TITLE
v10: SQLite only supports 4 data types

### ISSUE THREAD

**Issue by mattbrailsford** [umbraco/Umbraco-CMS#12524]
### Which *exact* Umbraco version are you using? For example: 9.0.1 - don't just write v9

v10-rc5

### Bug summary

When running migrations against SQLite, columns are generated with non-standard data types. Columns should only realy be one of 4 types INTEGER, REAL, TEXT, and BLOB. This is as per the docs at https://docs.microsoft.com/en-us/dotnet/standard/data/sqlite/types

Whilst you can set these to anything and these can help with column affinity, Microsoft's recomendation is to stick to the 4 defaults

> We recommend only using the four primitive SQLite type names: INTEGER, REAL, TEXT, and BLOB.

### Steps to reproduce

Run a migration with various column types and see that other column types are used.

### Expected result / actual result

Should only use the 4 core column types

**Comment by p-m-j** [comment]
Is using the fluent syntax? Poco based? Both?

Would you be able to add an example migration to the issue?

Did you find any examples that would have questionable affinity according to the rules laid out in section 3.1 of https://www.sqlite.org/datatype3.html ?

**Comment by nikolajlauridsen** [comment]
Fixed in #12541
