### ISSUE TITLE
Unpublishing Content Node -> Inaccurate "dependent" nodes list

### ISSUE THREAD

**Issue by hfloyd** [umbraco/Umbraco-CMS#12538]
### Which *exact* Umbraco version are you using? For example: 9.0.1 - don't just write v9

9.5.1

### Bug summary

When Unpublishing a Content node, the dialog box that appears seems to list WAY too many "dependent" nodes:

![image](https://user-images.githubusercontent.com/1252593/171948126-deaf2110-bfa2-4dcc-b913-e746eb519172.png)

I am certain the node that I am unpublishing here should have only pulled up ONE dependent node.

I have noticed this odd behavior on two sites which were recently updated from 9.5 to 9.5.1.

Maybe related to this fix in 9.5.1? https://github.com/umbraco/Umbraco-CMS/issues/12308

### Steps to reproduce

In a v. 9.5.1 site, unpublish a node and observe the dialog box.

### Expected result / actual result

It should only show ACTUAL dependent nodes.

**Comment by bergmania** [comment]
Hi @hfloyd.. I see the problem.. Thanks for reporting

**Comment by Zeegaan** [comment]
This should now be fixed in https://github.com/umbraco/Umbraco-CMS/pull/12544, thanks again for reporting @hfloyd ! 🐛
