### ISSUE TITLE
v10 Can t create document type programmaticaly 

### ISSUE THREAD

**Issue by b-Joly** [umbraco/Umbraco-CMS#12547]
### Which *exact* Umbraco version are you using? For example: 9.0.1 - don't just write v9

V10.0.0-rc4

### Bug summary

Impossible to create document type programmatically. 

### Specifics

1
![code](https://user-images.githubusercontent.com/104818769/172411494-24cab2e1-66b7-4c04-ad36-33009a8cf531.PNG)
2
![Values](https://user-images.githubusercontent.com/104818769/172411506-b0579477-d7e3-4c07-bcdb-0924facfbca8.PNG)
3
![dataStore](https://user-images.githubusercontent.com/104818769/172412229-afffb41c-05a8-4b24-b138-aa5587652a68.PNG)
4
![dataId](https://user-images.githubusercontent.com/104818769/172412234-ca3595b7-c703-4519-a1dc-ea71a137c537.PNG)
5
![docType](https://user-images.githubusercontent.com/104818769/172412641-307f8905-35b7-40b7-b715-e29e00ce6846.PNG)
6
![AuthorizedNode](https://user-images.githubusercontent.com/104818769/172413549-c99b333d-86dd-472f-9c69-6c00dae27602.PNG)
7
![ObjectiveDocumentType](https://user-images.githubusercontent.com/104818769/172413561-50a7b964-d11c-40dd-9f0c-9b821e6901d0.PNG)

Hi 
i can't creat document type. with the code in the 1st picture. 
As we can see in the second picture. i got value in my object 'objective' in parameter
the value of "parentId" is referencing the good list in my dataStore picture 3-4.
I am referencing the good alias picture 5 - 6 -7.
i have tried the ContentService.SaveAndPublish(request) => no result. 
I have nothig in the logViewer and no error appear in debug mode.

I can creat content with the back office interface. 

My method createObjectif is called from a customDashboard where i upload an Excel.

Maybe i am missing something ?

```csharp
public void CreateObjectif(Objective objective)
        {
            var parentId = this.Content
                    .GetByXPath($"{Settings.XPath}/{DocumentTypes.Objectives}").Select(s => s.Id).FirstOrDefault();

            var request = this.ContentService.Create(objective.Title, parentId, DocumentTypes.Objective, 1);

            var lang = this.LocalizationService.GetAllLanguages();
            foreach (var culture in lang)
            {
                request.SetCultureName(objective.Title, culture.IsoCode);
                if (culture.IsoCode != "fr")
                {
                    request.SetValue("title", objective.Title + "_" + culture.IsoCode, culture.IsoCode);
                }
                else
                {
                    request.SetValue("title", objective.Title, culture.IsoCode);
                }
            }

            this.ContentService.Save(request);
        }
```

### Steps to reproduce

1) Create a list in the data store
2) a custom dashbord(angular js) with a action to a  web controller API 
3) create de document type in the code

**Comment by nul800sebastiaan** [comment]
Hi there @b-Joly this sounds like an excellent question for the forums where our friendly community can help you find the best solution for your requirements. 

Even in v10, people create doctypes programatically all the time in things like Umbraco Deploy, uSync and when starterkit packages. So I assume you might be doing something slightly wrong in your code somewhere. 

Make sure to head on over to https://our.umbraco.com and ask follow up questions there! 👍

**Comment by b-Joly** [comment]
Finally found the problem after 1 week. I was blocking the action in the notification system but the error message from the cancleoperation() didn't display.
