### ISSUE TITLE
Cannot translate document types 

### ISSUE THREAD

**Issue by Zerhar** [umbraco/Umbraco-CMS#12554]
### Which *exact* Umbraco version are you using? For example: 9.0.1 - don't just write v9

8.18.4

### Bug summary

I'm trying to translate my document types to different languages by adding the #-symbol before the name and description and then adding a translation in the translation file. However the result is that it does not get translated when you switch language. It only picks the same language all the time. 

### Steps to reproduce

- Create a document type.
- Add a #-symbol before the name. For example #RadioButton.
- Go to the Translation tab and create a translation with the name Radiobutton. 
- Go to the Content tab where you document type is used.
- The translation of the document type does not change despite switching languages. 

### Expected result / actual result

The document type should change according to the translations you have done when switching languages.

**Comment by kjac** [comment]
Hi @Zerhar,

Thank you for reaching out... apologies for the belated response.

The backoffice localization is tied to the user's language - not the language being edited: 

![image](https://user-images.githubusercontent.com/7405322/208144298-ea937849-4e07-4546-a403-7912cd9c0c36.png)

Consider this dictionary item:

![image](https://user-images.githubusercontent.com/7405322/208143246-2692ec81-e693-4534-aa47-6685dc76284b.png)

The dictionary item is applied to a property using the "#" notation:

![image](https://user-images.githubusercontent.com/7405322/208143363-9a611516-2f90-4280-b5ad-d38dc4329418.png)

When browsing as a user with English (US) locale, the en-US translation of the dictionary item used as the property label:

![image](https://user-images.githubusercontent.com/7405322/208142985-fbd78ef4-b9c1-4e7a-a6c5-953ce59f6b4a.png)

...while browsing as a user with Danish locale, the da-DK translation of the dictionary item used:

![image](https://user-images.githubusercontent.com/7405322/208142898-7363f498-ab19-4733-b711-7e959eef0d24.png)
