### ISSUE TITLE
Slider (noUiSlider) feature "Merging overlapping tooltips" not working

### ISSUE THREAD

**Issue by daandrnorlysdk** [umbraco/Umbraco-CMS#12558]
### Which *exact* Umbraco version are you using? For example: 9.0.1 - don't just write v9

8.18.4

### Bug summary

When using the Slider datatype - and having Range turned on - the box showing the range is misplaced CSS-wise.
An example looks like this in Chrome:
![image](https://user-images.githubusercontent.com/107189654/172840903-9f2a8153-7098-48cc-a017-1ffd4a0bb679.png)

Another example in Firefox:
![image](https://user-images.githubusercontent.com/107189654/172841790-70ed5593-22fb-4375-8d3a-ea671bc3373f.png)

The box should be in the middle above the ranges selected - but instead the more you move it, the further away it goes instead ending up overflowed out of the containing div element.

This has been re-tested on a clean 8.18.4 installation.

### Steps to reproduce

- Make a data type that uses the "Slider" property editor
- - Example:
- - Enable Range: true
- - Minimum value: -50
- - Maximum value: 50
- Put the data type on a document type
- View the document type property in the Content section on the document type you put it on
- Try to move the two ranges around

### Expected result / actual result

When moving the ranges around, you'll see that when it should be merged it will not stay in the middle, but instead move further and further from the middle until at some point it snaps back to being in the middle.

**Comment by bjarnef** [comment]
I can confirm this issue.
It is working in noUiSlider v15.4.0 but after this working the merged tooltip is off:
https://github.com/leongersen/noUiSlider/issues/1217
