### ISSUE TITLE
Uno deployment to local machine then to  Azure from clone

### ISSUE THREAD

**Issue by Z3nAg3ncy** [umbraco/Umbraco-CMS#12564]
### Which *exact* Umbraco version are you using? For example: 9.0.1 - don't just write v9

Uno deployment 

### Bug summary

following how  to clone and move onto local then deploy to AZURE

Migrate a site off Cloud
 When you are moving a project away from Umbraco Cloud, there are a few steps you need to take:
1.   Clone down the environment with the content and code you want, to your local machine
2.   Do a restore when you spin up the site locally - this will give you all the data/content/media. NOTE: If you wish to have the database in SQL Server instead of SQL CE you need to set the connection string before you spin the site up the first time.
3.   Remove deploy reference in web.config file:
 <umbraco.deploy>
 <environments configSource="config\UmbracoDeploy.config"/>
 <settings configSource="config\UmbracoDeploy.Settings.config"/>
 </umbraco.deploy>
4.   Now you have an exact copy of your Cloud project locally!
5.   The next step is to remove the Cloud specific files: All files related to Umbraco Deploy
Config/UmbracoDeploy.config
Config/UmbracoDeploy.Settings.config
bin/Umbraco.Deploy.Cloud.dll
bin/Umbraco.Deploy.Contrib.Connectors.dll
bin/Umbraco.Deploy.dll
bin/Umbraco.Deploy.Forms.dll
bin/Umbraco.Deploy.UI.dll
The /Deploy folder in App_Plugins
  You also need to remove the Deploy section for the Dashboard.config file
<section alias="Deploy">
 <areas>
 <area>content</area>
 </areas>
 <tab caption="Your workspace">
 <control>/App_Plugins/Deploy/views/dashboards/dashboard.html</control>
 </tab>
 </section>

**We now get errors** 

we working on my local machine. we've gone through the step they've outlined on cloning and , but as soon as I delete these files:
bin/Umbraco.Deploy.Cloud.dll
bin/Umbraco.Deploy.Contrib.Connectors.dll
bin/Umbraco.Deploy.dll
bin/Umbraco.Deploy.Forms.dll
bin/Umbraco.Deploy.UI.dll

I get the following error: System.IO.FileNotFoundException: Could not load file or assembly 'Umbraco.Deploy.Cloud, Version=4.4.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The system cannot find the file specified.

That means one of those files I've deleted is being referenced elsewhere.

has any tried running through these steps? and got it working  Also where the Dashboard.config is, because I can't find it
![image](https://user-images.githubusercontent.com/30283113/173045066-29ab451e-2717-47b3-8721-1576a2c16bf0.png)

### Steps to reproduce
Clone to local machine using URL from [umbraco.io](http://umbraco.io/) project page
Run on localhost
Restore website to local machine
Complete steps 1-5 above
clone run on local machine 

### Expected result / actual result
![image (3)](https://user-images.githubusercontent.com/30283113/173057734-5e8a62ab-a809-4a55-8b66-ffeb0015ec12.png)
![image (4)](https://user-images.githubusercontent.com/30283113/173057739-a8b14461-cddf-4fed-a59e-f692ed843985.png)

**Comment by nikolajlauridsen** [comment]
Hey @Z3nAg3ncy This seems more like a cloud question/issue than a problem with the CMS itself, so I'll go ahead and close this for now, please don't hesitate to reach out to our helpful community [on the forums](https://our.umbraco.com/forum/) or [in our discord](https://our.umbraco.com/forum/) with any questions you might have 😄 

But I think you're on the right track, it seems like those DLL are referenced, I'd take an extra look in the csproj file in your solution 😄
