### ISSUE TITLE
FilesystemMainDomLock throws on startup when LocalTempStorageLocation is EnvironmentTemp

### ISSUE THREAD

**Issue by p-m-j** [umbraco/Umbraco-CMS#12562]
### Which *exact* Umbraco version are you using? For example: 9.0.1 - don't just write v9

10.0.0-rcx and 9.4+

### Bug summary

DirectoryNotFoundException for /tmp/UmbracoData/{{hash}} thrown when trying to create lock / lock release files as the path doesn't exist yet.

### Workarounds:

+ Create the directory
+ Switch LocalTempStorageLocation to Default (not safe on azure)
+ Switch to `SqlMainDomLock` instead (see [Global Settings](https://our.umbraco.com/Documentation/Reference/Configuration/GlobalSettings/))

**Comment by p-m-j** [comment]
TODO: 

- [ ] Cherry pick into 9.5.2

**Comment by bergmania** [comment]
Cherry picked: https://github.com/umbraco/Umbraco-CMS/commit/e536f9fd10d75485fc64200101f964de324f28cc
