### ISSUE TITLE
This document is published but its URL would collide with content /Root/Content page

### ISSUE THREAD

**Issue by Frost117** [umbraco/Umbraco-CMS#12566]
### Which *exact* Umbraco version are you using? For example: 9.0.1 - don't just write v9

9.5.0 AND 8.18.4

### Bug summary

When you assign a hostname to Node that is not the Root node, then you'll be able to get the following behavior:
 ![image](https://user-images.githubusercontent.com/32164310/173082108-c33aca65-9943-49e3-931c-988f9505ba93.png)

### Specifics

This issue only happens when you are in the backoffice of the hostname provided.
For example on Umbraco Cloud, you won't be seeing this issue if you view this from the backoffice on umbraco.io.
![image](https://user-images.githubusercontent.com/32164310/173082807-d7dfd895-616e-434e-96ff-9b6a01602356.png)

### Steps to reproduce

1. Make a root node.
2. Make a child node on root node
3. Assign a hostname to the child node
4. save and publish
5. go to {hostname}.com/umbraco and visit the root node.
6. Profit -> You'll get the error

### Expected result / actual result

Expected to see the same behavior from the non-hostname domain as I would on the hostname domain.

**Comment by kjac** [comment]
Hi @Frost117,

Thank you for reaching out, and sorry for the late response on our end.

I must admit I am a little confused as to what you're trying to achieve here. Could you please elaborate on the use case, so we may better understand if this is a bug or a limitation in the routing system?

**Comment by nikolajlauridsen** [comment]
Hey @Frost117, we haven't heard back from you in 2 weeks, so I'll have to go ahead and close this issue down for now, feel free you reach out if the issue persists and you have more information.

**Comment by ctiwana** [comment]
I have a similar issue with 8.16.0. We have a multilingual website and we have a setup with a configuration node outside the primary home node. I am trying to publish translations but I keep getting an error even though they don't have the same name.
![image](https://user-images.githubusercontent.com/3189066/224842373-59bafdc9-e3ca-4c83-9af6-ad8f322c1f5f.png)
