### ISSUE TITLE
v10 RC5: AddBackOfficeLogin : Double escaping of returnPath paramater [login] 

### ISSUE THREAD

**Issue by olibos** [umbraco/Umbraco-CMS#12575]
### Which *exact* Umbraco version are you using? For example: 9.0.1 - don't just write v9

10.0.0-rc5

### Bug summary

When I logged in with: External login `BackOfficeAuthenticationBuilder.AddMicrosoftIdentityWebApp`, I'm redirected to 404 Page: https://localhost:44334/%2Fumbraco%23%2Fcontent

### Specifics

The problems occurs, on the login screen (https://localhost:44334/umbraco#/login/false?returnPath=%252Fumbraco%2523%252Fcontent)
Tested on :
* Chrome
* Edge
* Firefox

![image](https://user-images.githubusercontent.com/6031263/173304646-cc71c768-430e-43be-b957-d6154442de3c.png)

### Steps to reproduce

Scenario 1:
=======
* I navigate to: https://localhost:44334/umbraco
* System redirects me to: https://localhost:44334/umbraco#/login/false?returnPath=%252Fumbraco%2523%252Fcontent
* Click on AzureAD login
* Authenticate
* I'm redirected to: https://localhost:44334/%2Fumbraco%23%2Fcontent
* ❌ 404 due to invalid URL

If I manually change the URL to https://localhost:44334/umbraco, it works as expected.

Scenario 2:
=======
* I navigate to: https://localhost:44334/umbraco#/login/false
* Click on AzureAD login
* Authenticate
* I'm redirected to: https://localhost:44334/umbraco#/content?mculture=fr
* 👍I've access to the backoffice

### Expected result / actual result

After AzureAD authentication, I should be redirected to the backoffice.
Due to double escaping of returnPath, I'm redirected to a 404 page.

Note: The same code is correctly working on Umbraco 9.

**Comment by olibos** [comment]
On v9.x.x, the form action was always: `/umbraco/ExternalLogin`
Starting with this merge: https://github.com/umbraco/Umbraco-CMS/blame/v10/dev/src/Umbraco.Web.UI.Client/src/common/directives/components/application/umblogin.directive.js#L49
The form action is now computed like this:
```js
const tempUrl = new URL(Umbraco.Sys.ServerVariables.umbracoUrls.externalLoginsUrl, window.location.origin);
tempUrl.searchParams.append("redirectUrl", $location.search().returnPath ?? "")

vm.externalLoginFormAction = tempUrl.pathname + tempUrl.search;
```

That lead to a double escaping on my side.
@bergmania Do I do something wrong? Or is it a regression?

Thank you for your help.

**Comment by olibos** [comment]
Thank you ☺️

**Comment by bergmania** [comment]
Closed by https://github.com/umbraco/Umbraco-CMS/pull/12585
