### ISSUE TITLE
Umbraco 10 Publish creates physical wwwroot/umbraco and wwwroot/App_Plugins/UmbracoForms assets

### ISSUE THREAD

**Issue by argentini** [umbraco/Umbraco-CMS#12570]
### Which *exact* Umbraco version are you using? For example: 9.0.1 - don't just write v9

10.0.0-rc5

### Bug summary

When publishing the project using `dotnet publish` virtual assets are created as physical files, which conflicts with virtual file access.

### Specifics

When publishing the project using `dotnet publish` the virtual assets for `wwwroot/umbraco/*` are created as physical files, which conflict with the virtual files referenced by Umbraco's back office.

Additionally, Umbraco Forms 10.0.0-rc2 is creating physical files in `wwwroot/App_Plugins/UmbracoForms` which is incorrect behavior as mentioned above, but also the wrong path for `App_Plugins`.

### Steps to reproduce

Perform a `dotnet publish ProjectDir/Project.csproj -c Release -o publish /p:EnvironmentName=Release` command

### Expected result / actual result

Virtual file assets are not created as physical files in the publish output folder.

**Comment by p-m-j** [comment]
All of this sounds correct and intended, RCL should output the static files on publish.

However we also have an explicit call to UseStaticWebAssets in program.cs which I never really understood as that should happen by default for development environments.

Forms under wwwroot/app_plugins/ is also intentional.

It sounds like you may just need to remove the UseStaticWebAssets call from program.cs if you’re having issues with running the published output.

**Comment by argentini** [comment]
@p-m-j thanks for the info. Actually, it does run with the physical files. And I do comment out that call to UseStaticWebAssets() because in my StartUp I manually enable UseStaticAssets() and pass it some file mappings.

I am confused about the changes to Umbraco Forms. The form theme picker property editor still points to the Views/Partials/Forms path, yet Umbraco Forms does not put any default theme partials in there, nor does it add the default export partials. Are you aware of any documentation on the changes to forms?

**Comment by p-m-j** [comment]
UseStaticWebAssets is slightly different to UseStaticAssets

[UseStaticWebAssets](https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.hosting.webhostbuilderextensions.usestaticwebassets?view=aspnetcore-6.0)
> Configures the [WebRootFileProvider](https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.hosting.iwebhostenvironment.webrootfileprovider?view=aspnetcore-6.0#microsoft-aspnetcore-hosting-iwebhostenvironment-webrootfileprovider) to use static web assets defined by **referenced projects and packages.**

> The form theme picker property editor still points to the Views/Partials/Forms path, yet Umbraco Forms does not put any default theme partials in there, nor does it add the default export partials. Are you aware of any documentation on the changes to forms?

I'm not, this question might be better served on the https://github.com/umbraco/Umbraco.Forms.Issues repo

**Comment by argentini** [comment]
@p-m-j Thank you again. I think we are done here ;)

**Comment by p-m-j** [comment]
no problemo, hope you find your answers
