### ISSUE TITLE
V10 - Package view - Layout not showing correctly in respect to screen size

### ISSUE THREAD

**Issue by alevak09** [umbraco/Umbraco-CMS#12576]
### Which *exact* Umbraco version are you using? For example: 9.0.1 - don't just write v9

10.0.0-rc4

### Bug summary

Some package details in the package view breaks the layout not showing as expected in respect to screen size.

![packages](https://user-images.githubusercontent.com/73195407/173310733-b6778677-feb0-41df-a7bd-3e27eee557b0.PNG)

![packages-2](https://user-images.githubusercontent.com/73195407/173310750-fc273ad6-22cc-4e55-8f08-25380abd8daa.PNG)

### Steps to reproduce

1. Go to Package section
2. Open Contentment package view
3. You'll see layout not showing correctly in respect to screen size
4. Try to resize the window to see more problems as word-breaking not working and so on

### Expected result / actual result

Need some css polish to make this work as expected

**Comment by Migaroez** [comment]
Bug confirmed on dev/v9 (78af859) (10.2.0-preview.9)

Things seem to go wrong when the screen is below 517px wide
class `.umb-package-details__main-content` has `min-width: 480px;`, removing this fixes the main content not scaling well to the actual screen size on very narrow screens.

Second issue is in the install instructions where the nuget identifier can not be broken down onto multiple lines, adding `overflow-wrap: break-word;` `to umb-package-details__install-instructions` "fixes this issue"

@nul800sebastiaan  I am not a front end specialist nor ux master but I could make a PR with these changes if they seem right.

**Comment by nul800sebastiaan** [comment]
Sounds really good to me @Migaroez, proposed changes sound perfectly fine. 👍

**Comment by Migaroez** [comment]
Ill try and make the PR tonight.

**Comment by nathanwoulfe** [comment]
Fixed by #12719
