### ISSUE TITLE
v10. Database not being recreated

### ISSUE THREAD

**Issue by patrickdemooij9** [umbraco/Umbraco-CMS#12584]
### Which *exact* Umbraco version are you using? For example: 9.0.1 - don't just write v9

v10

### Bug summary

In v9, you are able to recreate your database by leaving your connectionstrings empty, but this doesn't seem to work with v10 anymore. It seems like this is caused by the telemetry task that is trying to make a connection with the database before the logic for the database creation runs.

Error:
![image](https://user-images.githubusercontent.com/11466511/174008511-87c55929-97d0-418d-9b9f-cf5dab3c4fa2.png)

### Steps to reproduce

- Create new website
- Run it as normal
- Leave the connectionstring empty
- Try to run again

### Expected result / actual result

Database should be created before the telemetry logic is running

**Comment by nikolajlauridsen** [comment]
Hey @patrickdemooij9 I'm unfortunately unable to recreate, for me everything works the same as V9 (see video below), I'm not sure I'm missing something? 


https://user-images.githubusercontent.com/16456704/175006623-b1f4b891-1104-4ee5-8eb3-7b88f5d34ef5.mp4


However, it's of course not optimal that our telemetry task errors out if you're too slow installing, so I've fixed this in #12600 😄

**Comment by patrickdemooij9** [comment]
Hi @nikolajlauridsen,

That is strange, but it was probably caused by the slow installing. I was doing this on the CodeGarden Wifi along with the upgrade from v9 to v10 (which probably causes the startup to be slower as well). I think the changes you made in the PR will fix it either way.

**Comment by nikolajlauridsen** [comment]
Ahh I see :) 

I'll go ahead and close this one then since it should be fixed now (in 10.0.1 :) )
