### ISSUE TITLE
Image media cropper doesn't work if filename contains å, ä or ö.

### ISSUE THREAD

**Issue by alice-gothberg** [umbraco/Umbraco-CMS#12598]
### Which *exact* Umbraco version are you using? For example: 9.0.1 - don't just write v9

9.4.3

### Bug summary

If I upload an image that has an å, ä or ö in the filename, the media cropper doesn't work at all and the image is displayed in its original size. When replacing these characters to a and/or o, the cropper works as intended.

### Specifics

I have created two pages to visualise the issue with media crops:

[Ignoring focal point/crops](https://dev-jobba-gr-nt.euwest01.umbraco.io/issues/ignoring-focal-point/)
The header uses global crops and on this I have only changed the focal point. The block has focal point nad user defined crop that is also ignored. Both images have å, ä and/or ö in the filename.

[Ignoring crops](https://dev-jobba-gr-nt.euwest01.umbraco.io/issues/ignoring-crops/)
The block uses localcrops and is not cropped at all.

### Steps to reproduce

Upload an image with å, ä and/or ö in the filename and try to modify the focal point/crop.

### Expected result / actual result

Desired result:
Image is cropped according to the defined crop and doesn't ignore focal point despite filename containing å, ä and/or ö.

Actual result:
Images without special characters are cropped as intended but those with these characters are not cropped at all.

---
_This item has been added to our backlog [AB#20465](https://dev.azure.com/umbraco/243e7927-03b2-44e2-908f-d4ac7ea5daaa/_workitems/edit/20465)_

**Comment by jrunestone** [comment]
I think ImageSharp 2.0.0 did something to break filenames with special characters, this works with ImageSharp 1.0.5. https://github.com/SixLabors/ImageSharp.Web/issues/278

**Comment by thomashdk** [comment]
> I think ImageSharp 2.0.0 did something to break filenames with special characters, this works with ImageSharp 1.0.5. [SixLabors/ImageSharp.Web#278](https://github.com/SixLabors/ImageSharp.Web/issues/278)

Hi 

Is it possible that I can add it to my 9.5.0 ? Can't update to 10 right now...

**Comment by nul800sebastiaan** [comment]
We can't bump dependencies in a patch release, it goes against SemVer and risks stability. 
In fact, this requires a new major version of ImageSharp with breaking changes and we can't update that one in v9 as it would require us to make breaking changes in v9.

The workaround would be to add a MediaService.Saving notificationhandler and renaming the files as they are being uploaded. Maybe ImageSharp is interested in implementing the same fix in v1, in which case you could update the NuGet packages in v9 when that gets released.

**Comment by thomashdk** [comment]
I found out that my issue was.

When using to store iamges outside wwwroot folder:

"UmbracoMediaPhysicalRootPath": "./../../TestMedia/media",

It for some reason won't allow medias with special charecters as æøå, but if it's  wwwroot/media then it works fine..

**Comment by thomashdk** [comment]
Created a new ticket for that issue:
https://github.com/umbraco/Umbraco-CMS/issues/12903
