### ISSUE TITLE
Create Date is January 1, 0001 12:00 AM when adding a node with no properties to the content tree

### ISSUE THREAD

**Issue by JordyDW** [umbraco/Umbraco-CMS#12596]
### Which *exact* Umbraco version are you using? For example: 9.0.1 - don't just write v9

v10.0.0

### Bug summary

If you add a new node/page to the content tree, the **Create Date** is **January 1, 0001 12:00 AM**. If you switch to another node and change back, or simply refresh, only then the correct date is shown.

This is on a clean v10 install.

### Specifics

![Screenshot 2022-06-20 223343](https://user-images.githubusercontent.com/7073858/174674293-938697be-48c8-4ab5-8306-9964fcd090e9.png)

### Steps to reproduce

1. Create a doc type
2. Add doc type to content tree

### Expected result / actual result

I expect the current date as soon as I create the node, not only after refreshing.

**Comment by nul800sebastiaan** [comment]
This is an interesting one, I tried to reproduce and could only get it to fail if there's no properties on the doctype!

I can reproduce this in v9.1.2 and even v8.17 as well so this has been a problem for a while. This would make for a great investigation if you or someone else wants to try their hand at helping out.

**Comment by jrunestone** [comment]
It's likely a client side/angular bug, because immediately after saving the createDate is populated correctly in the database (umbracoNode).

**Comment by nul800sebastiaan** [comment]
Fixed for 10.1.0 in PR https://github.com/umbraco/Umbraco-CMS/pull/12632
