### ISSUE TITLE
v10: DB Provider names should be case insensitive

### ISSUE THREAD

**Issue by mattbrailsford** [umbraco/Umbraco-CMS#12604]
### Which *exact* Umbraco version are you using? For example: 9.0.1 - don't just write v9

v10

### Bug summary

In the SQLite source code, the `ProviderName` constant is `Microsoft.Data.SQLite` however the correct casing of this when using the microsoft provider is `Microsoft.Data.Sqlite`. If you attempt to use the latter as the provider name in your connection string, it will throw an exception.

Resolution of services via their provider name should probably be case insensitive to prevent these errors.

### Steps to reproduce

Configure umbraco with a SQLite database then change the provider name to `Microsoft.Data.Sqlite`, you should then receive an exception.

### Expected result / actual result

It should probably work with either casing of the provider name.

**Comment by Zeegaan** [comment]
Fixed in https://github.com/umbraco/Umbraco-CMS/pull/12639, thanks again for reporting! 🐛

**Comment by ronaldbarendse** [comment]
We should also update the dotnet new template and documentation to use the new/correct casing:

https://github.com/umbraco/Umbraco-CMS/blob/8d8592092fc950a7f994bb60853db8f422312001/templates/UmbracoProject/.template.config/template.json#L157-L166

**Comment by bergmania** [comment]
Code updated in this commit :https://github.com/umbraco/Umbraco-CMS/commit/8de95acec669686d1421f6caaf18ad42cf00ce47
