### ISSUE TITLE
Umbraco 9.5.2 Bugged Compositions

### ISSUE THREAD

**Issue by TomCove** [umbraco/Umbraco-CMS#12628]
### Which *exact* Umbraco version are you using? For example: 9.0.1 - don't just write v9

9.5.2

### Bug summary

I have set up a composition which is used across multiple site blocks. 

It contains a dropdown data type called "Heading Class Name" alias is headingClassName this is to allow users to override the default styles of the heading.

It should return h1, h2, h3 etc.
Except in my partials it just returns an empty string (aka nothing).
ALL the other compositions I have used in the site work in exactly the same way and are working fine, I really can't get my head around this one.

I had this bug locally and rebuilt the composition and it started working again, but now we have this on a staging site and content population has started, I really can't start over.

Any help would be massively appreciated.

-----------
Code example in screenshot (I tried to paste it but it formats weirdly).
![Screenshot 2022-06-28 112630](https://user-images.githubusercontent.com/105212638/176157150-72d6b4d6-bd60-4688-a111-93eba31b0d4b.png)

Accessing the value like so:

    var content = (ContentModels.SimpleTextModule)Model.Content;
    
    @content.HeadingClassName (this is what is returning as empty)

### Steps to reproduce

Create a composition with a dropdown and see if it returns an empty string on the front end.

### Expected result / actual result

Output the value selected in the CMS

**Comment by kjac** [comment]
Hi @TomCove,

Thanks for reaching out. Sorry for the belated response.

I have tried to reproduce your issue without luck on V10.3.2. I do suspect this works just fine in V9.X as well 😄 

In my test I have a block list with a single block. The block is based on an element type, which in turn is composed by another content type:

![image](https://user-images.githubusercontent.com/7405322/207937441-11ff83eb-094f-47a1-bfb5-0c8c57081483.png)

On the Home page I've added a few elements with data entered in both the element type and the composition type fields:

![image](https://user-images.githubusercontent.com/7405322/207937503-4a51d121-c788-4a57-909b-b1e8e31df111.png)

I'm rendering the Home page with the following template:

```cshtml
@inherits Umbraco.Cms.Web.Common.Views.UmbracoViewPage<ContentModels.Home>
@using ContentModels = Umbraco.Cms.Web.Common.PublishedModels;
@using Umbraco.Cms.Core.Models.Blocks
@{
	Layout = null;
}
<html>
<body>
@foreach (var block in Model.Blocks.OfType<BlockListItem<MyElement>>())
{
	<fieldset>
		<ul>
			<li>Composition property value: @block.Content.PropertyOnMyComposition</li>
			<li>Element property value: @block.Content.PropertyOnMyElement</li>
		</ul>
	</fieldset>
}
</body>
</html>
```

This yields the expected output:

![image](https://user-images.githubusercontent.com/7405322/207937647-0a0b804b-047c-42fd-99dc-6cfbe2f68994.png)

Again - sorry for the late reply. I hope you've already managed to work your way around your issue at this point. If you still have problems I would encourage you to seek out assistance at the forum: https://our.umbraco.com/forum
