### ISSUE TITLE
One-click installs have been removed

### ISSUE THREAD

**Issue by Zeegaan** [umbraco/Umbraco-CMS#12623]
### Which *exact* Umbraco version are you using? For example: 9.0.1 - don't just write v9

v10.1.0 (v10/dev)

### Bug summary

You are no longer to one click install, as the "install" button has been removed

### Steps to reproduce

- Fill out your information
- Try and find the install button, it is no longer there 😅 

### Expected result / actual result

Expected an install button

**Comment by Zeegaan** [comment]
Also the UX for the telemetry slider is not good, it is hard to know intuitively to hover over the different levels to get more details.

I suggest a bit fat arrow pointing at it, telling you to hover for more information like so:
![image](https://user-images.githubusercontent.com/70372949/175888806-5e9ffbdd-96f8-4862-8bfe-f459c7928758.png)

**Comment by nathanwoulfe** [comment]
Is there any reason that was made a slider? Would be perfectly ok as a drop-down or radio buttons (if there are only three options, radio would be best)

**Comment by Zeegaan** [comment]
I personally am a fan of the slider, and imo gives an "instant" look on what the different levels are, IE. Minimal is the lowest level, and Detailed is the highest. I do think radio buttons could accomplish the same, but would probably be wierd if we added more options (which might happen).

**Comment by Zeegaan** [comment]
Fixed in https://github.com/umbraco/Umbraco-CMS/pull/12731
