### ISSUE TITLE
Cannot parse '__IndexType:content': Encountered error when getting examine search results

### ISSUE THREAD

**Issue by ewuski** [umbraco/Umbraco-CMS#12648]
### Which *exact* Umbraco version are you using? For example: 9.0.1 - don't just write v9

Umbraco 9.4.3, 10.0.0

### Bug summary

I am getting a strange error from a basic examine query, it looks like:

    {"Cannot parse '__IndexType:content': Encountered \"<EOF>\" at line 1, column 19.\r\nWas expecting one of:\r\n    <BAREOPER> ...\r\n    \"(\" ...\r\n    \"*\" ...\r\n    <QUOTED> ...\r\n    <TERM> ...\r\n    <PREFIXTERM> ...\r\n    <WILDTERM> ...\r\n    <REGEXPTERM> ...\r\n    \"[\" ...\r\n    \"{\" ...\r\n    <NUMBER> ...\r\n    "}

or like:

    {"Cannot parse '__IndexType:content': Encountered \"<EOF>\" at line 1,
    column 0.\r\nWas expecting one of:\r\n    <NOT> ...\r\n    \"+\"
    ...\r\n    \"+\" ...\r\n    \"-\" ...\r\n    \"-\" ...\r\n   
    <BAREOPER> ...\r\n    <BAREOPER> ...\r\n    \"(\" ...\r\n    \"(\"
    ...\r\n    \"*\" ...\r\n    <QUOTED> ...\r\n    \"*\" ...\r\n   
    <TERM> ...\r\n    <PREFIXTERM> ...\r\n    <QUOTED> ...\r\n   
    <WILDTERM> ...\r\n    <REGEXPTERM> ...\r\n    \"[\" ...\r\n   
    <WILDTERM> ...\r\n    <REGEXPTERM> ...\r\n    \"[\" ...\r\n    \"{\"
    ...\r\n    <NUMBER> ...\r\n    <TERM> ...\r\n    \"*\" ...\r\n   
    \"*\" ...\r\n    "}

The query is simple:

    Category: "content", LuceneQuery: {+__NodeTypeAlias:product
    +countryCode:ge -umbracoNaviHide:1}

The error happens on execution:

    searchResults = searchQuery.Execute();

Anyone knows what's going on and what this error means?

I had the same data in Umbraco 7 site and all worked well. I had never such or similar error returned by the searched content.

It usually happens on the first result search. I I reload the page the results are fetched with no issues.

### Specifics

Re-indexing does not make any difference.

It happens no matter the parameters of the search - it usually happens on the first results fetch, then - when the results are filtered or parameters of the search changed or the page simply reloaded and fresh search executed - it loads the results correctly as long as we stay on the same page.

If I move away and load the same results page in a new tab - again the error happens.
So it seems to be happening on every new page instance.

### Steps to reproduce

Add a search that uses the below query or similar - depending on your database and site doc types.

I am using built-in ExternalIndex for the query.

        ISearchResults searchResults = null;
        var index = GetExamineIndex(UmbracoIndexes.ExternalIndexName);
        var searcher = index.Searcher;
        var searchQuery = searcher.CreateQuery(searcherSettings.IndexingType)
                 .Field("__NodeTypeAlias", searcherSettings.ContentTypeToSearch.GetDescription());
        searchQuery = searchQuery.Not().Field("umbracoNaviHide", "1");
        
        // The resulting query is:
        // Category: "content", LuceneQuery: {+__NodeTypeAlias:product -umbracoNaviHide:1}
        
        searchResults = searchQuery.Execute();

        private IIndex GetExamineIndex(string indexName)
        {
            {
                if (!_examineManager.TryGetIndex(indexName, out var index) || !(index is IUmbracoIndex umbIndex))
                {
                    throw new InvalidOperationException($"No index found by name ExternalIndex or is not of type {typeof(IUmbracoIndex)}");
                }
                else
                {
                    return index;
                }
            }
        }

### Expected result / actual result

It should return results correctly for the first time.

**Comment by nul800sebastiaan** [comment]
Duplicates #12648

**Comment by nul800sebastiaan** [comment]
Oops, updated link to #12646
