### ISSUE TITLE
Lanuage ISO/ name cannot be null when upgrading from Umbraco 9

### ISSUE THREAD

**Issue by ewuski** [umbraco/Umbraco-CMS#12644]
### Which *exact* Umbraco version are you using? For example: 9.0.1 - don't just write v9

Umbraco 10

### Bug summary

I had a few languages added to my Umbraco 9, some dating from Umbraco 7.
The database table in Umbraco 9 handled it well despite two languges had _languagesCultureName_ as null in the _umbracoLanguage_ table.
However when upgrading to Umbraco 10 - at the end of the upgrade I got an error saying:

`Language culture ISO/ name cannot be null.`

The site was broken.

This got fixed when I added the missing values in the table.

### Specifics

Upgrade from Umbraco 9.4.3 to Umbraco 10.0.0

### Steps to reproduce

Follow the upgrade standard steps. Make sure you have some languages added and at least one has no _languagesCultureName_ as null in the _umbracoLanguage_ table.

### Expected result / actual result

It should upgrade without the error.
The upgrade should probably do a check and add values if any is missing.

---
_This item has been added to our backlog [AB#20470](https://dev.azure.com/umbraco/243e7927-03b2-44e2-908f-d4ac7ea5daaa/_workitems/edit/20470)_

**Comment by bergmania** [comment]
Fixed in https://github.com/umbraco/Umbraco-CMS/pull/12645

**Comment by bergmania** [comment]
Hi @ewuski.. Thanks for reporting this will be fixed in 10.1 :)

**Comment by ewuski** [comment]
Bril, thanks for quick action!
