### ISSUE TITLE
Error update from Umbraco 9 to 10

### ISSUE THREAD

**Issue by oskar-wise** [umbraco/Umbraco-CMS#12647]
### Which *exact* Umbraco version are you using? For example: 9.0.1 - don't just write v9

10.1.0

### Bug summary

I followed every step here https://our.umbraco.com/documentation/Fundamentals/Setup/Upgrading/version-specific?_ga=2.176702181.1149785445.1656325390-679722381.1624438915#version-9-to-version-10 but always fail.
First it is constantly redirected to /account/AccessDenied?RedirectUrl=%2FAccount%2FAAccessDenied%3FRedirectUrl=%2FAccount%2FAAccessDenied%3FRedirectUrl=%2FAccount%2FAAccessDenied%3F........... until the query string is too long
then after start and stop the project I get another error
Umbraco.Cms.Core.Exceptions.BootFailedException: The migration plan does not support migrating from state \"7a044d6d-93ff-4534-8f19-ed2daa05451d\".\n\n-> System.InvalidOperationException: The migration plan does not support migrating from state \"7a044d6d-93ff-4534-8f19-ed2daa05451d\

### Specifics

![2022-06-29_16-25-01](https://user-images.githubusercontent.com/108475411/176703331-0d186162-5163-4009-b239-8c29c6e79cf1.png)
![2022-06-30_13-24-37](https://user-images.githubusercontent.com/108475411/176703334-8c2e93d1-f07d-4f62-b245-411a99768475.png)
[UmbracoTraceLog.WISE-INTUNE_BQP.20220630.txt](https://github.com/umbraco/Umbraco-CMS/files/9020670/UmbracoTraceLog.WISE-INTUNE_BQP.20220630.txt)

### Steps to reproduce

Installation from 9 to 10

**Comment by jhenkes** [comment]
I had the same issue. I was able to work around the problem by updating to 9.5.0 first and then to 10.x.x.

**Comment by nul800sebastiaan** [comment]
Hi @oskar-wise - this seems to be a Forms migration Id, make sure to upgrade forms as well as Umbraco and then it should work 👍

**Comment by PerplexDaniel** [comment]
Just to add some information for future visitors; it seems Umbraco.Forms 10.0.0 does not recognize any migration states of Umbraco.Forms 9.x _except_ the final migration state of Umbraco.Forms 9.4.2 (`7c7bc5ee-4c5b-42dc-9576-5ce6dfbddb8e`). So if you try to upgrade from any other Umbraco.Forms 9 version it will crash.
Forms 9.5.0 also adds some new migrations but those are added to 10.1.0 as well so upgrading from 9.5.0 should work to 10.1.0, but probably not to 10.0.0.
