### ISSUE TITLE
SVG Link on Info Tab incorrect

### ISSUE THREAD

**Issue by AaronSadlerUK** [umbraco/Umbraco-CMS#12654]
### Which *exact* Umbraco version are you using? For example: 9.0.1 - don't just write v9

10.0.0

### Bug summary

When clicking on the Link for a SVG media item from the backoffice you get a url such as:

`https://DOMAIN.com/umbraco#/media/media/edit/1753?mculture=en-GB&list=1066&page=1&filter=&orderBy=updateDate&orderDirection=desc`

When it should be:

`https://DOMAIN.com/media/3fvalp2g/FILENAME.svg`

### Steps to reproduce

Upload an SVG to the media section
Click the Info tab
Click on the media Link

### Expected result / actual result

To link to the media file directly.

**Comment by nul800sebastiaan** [comment]
Closing for the reason explained in the linked PR https://github.com/umbraco/Umbraco-CMS/pull/12655

Ps. you don't need to create an issue if you're just going to create a PR at the same time anyway, there's no time to give feedback on the issue before you create the PR, so it's just extra work :-)
