### ISSUE TITLE
Behind reverse proxy Umbraco doesn't display original client IP address in logviewer

### ISSUE THREAD

**Issue by cstrijkert** [umbraco/Umbraco-CMS#12668]
### Which *exact* Umbraco version are you using?

8.6.4

### Bug summary

When logging in to Umbraco the Log Viewer shows an entry like this:

["Information"] Event Id: 0, State: "User: {mail} logged in from IP address {ip}"

Behind a reverse proxy it seems that the IP address is always the outgoing IP of the proxy, not the true client IP.
After some investigation I discovered that Umbraco is using the `_httpContextAccessor.HttpContext?.Connection.RemoteIpAddress` for getting the IP.

ASP.NET Core does have middleware to configure the app that the `RempoteIpAddress` should pick up the `X-Forwarded-For` header: https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/proxy-load-balancer?view=aspnetcore-6.0

I checked this behavior in in Umbraco 8.6.4, but even a search in Umbraco v10/contrib branch on `UseForwardedHeaders()` doesn't give me any results.

So, it would be nice if there is some way to configure Umbraco to use the X-Forwarded-For header.

### Steps to reproduce

- Open Umbraco instance behind reverse proxy, WAF, gateway, something like that
- Login to Umbraco
- Open the log viewer and notice that the login IP is the proxy IP, not the user client IP

**Comment by nul800sebastiaan** [comment]
I'll close this issue as we're not going to update v8 to support reverse proxies better, but if there's any v9/10 updates we could make then we can look into that. Thanks for the report!
