### ISSUE TITLE
TourFilters AddFilterByFile does not work in Umbraco 10

### ISSUE THREAD

**Issue by sofietoft** [umbraco/Umbraco-CMS#12667]
### Which *exact* Umbraco version are you using? For example: 9.0.1 - don't just write v9

10.0.0

### Bug summary

In our [Backoffice Tours documentation](https://our.umbraco.com/documentation/Extending/Backoffice-Tours/#how-to-filterdisable-tours-from-being-shown), we have a section on how to filter tours based on a set of different things.

The `AddFilterByFile` option does not work on Umbraco 10.

### Steps to reproduce

- Add a custom tour to your Umbraco 10 website following the [documentation](https://our.umbraco.com/documentation/Extending/Backoffice-Tours/).
- Ensure the new tour works in the backoffice
- Filter out the new tour:

```
using System.Text.RegularExpressions;
using Umbraco.Cms.Core.Composing;
using Umbraco.Cms.Core.DependencyInjection;
using Umbraco.Cms.Core.Tour;

namespace Umbraco.Docs.Samples.Web.BackofficeTours
{
    public class BackofficeComposer : IComposer
    {
        public void Compose(IUmbracoBuilder builder)
        {
            builder.TourFilters()
                .AddFilterByFile("custom-tours.json");
        }
    }
}
```
- Replace `custom-tours.json` with the file name of your custom tour
- Check if the tour shows up in the backoffice

### Expected result / actual result

The expected result would be that the tour does not show up in the backoffice.
However, the actual result is, that it actually does show up in the backoffice.

This has been tested multiple times in a v10 project.

---
_This item has been added to our backlog [AB#22248](https://dev.azure.com/umbraco/243e7927-03b2-44e2-908f-d4ac7ea5daaa/_workitems/edit/22248)_

**Comment by bergmania** [comment]
Thanks for reporting.. I see that, currently the `AddFilterByFile` does not expect the file extension. Ill figure out if this is the same in v8. If so, then I guess it is the documentation that is wrong. If it requires the extension in v8, then I'll fix in the codebase for v10

**Comment by bergmania** [comment]
Alright, In v8 this has been the same, at lest since 27/03/2018. So I think it is better to update the docs to not expect the file extension.

In your case, try this composer instead

using System.Text.RegularExpressions;
using Umbraco.Cms.Core.Composing;
using Umbraco.Cms.Core.DependencyInjection;
using Umbraco.Cms.Core.Tour;

```
namespace Umbraco.Docs.Samples.Web.BackofficeTours
{
    public class BackofficeComposer : IComposer
    {
        public void Compose(IUmbracoBuilder builder)
        {
            builder.TourFilters()
                .AddFilterByFile("custom-tours");
        }
    }
}
```

Please confirm this also works for you. If so, I recommend to update the docs for all 8+

**Comment by bergmania** [comment]
Ill close this, and follow up on docs

**Comment by bergmania** [comment]
Docs updated
