### ISSUE TITLE
AppSetting for Imaging => Resize => MaxWidth, MaxHeight does not work

### ISSUE THREAD

**Issue by argentini** [umbraco/Umbraco-CMS#12671]
### Which *exact* Umbraco version are you using? For example: 9.0.1 - don't just write v9

10.0.1

### Bug summary

The appsettings for image maxwidth and maxheight as per [the Umbraco documentation](https://our.umbraco.com/documentation/Reference/Configuration/ImagingSettings/) do not limit image resizing.

### Steps to reproduce

Set the appsettings.json for image maxwidth and maxheight as per [the Umbraco documentation](https://our.umbraco.com/documentation/Reference/Configuration/ImagingSettings/), you can still request images using URL parameters for larger sizes and images are generated at the requested sizes.

### Expected result / actual result

Generated images should not exceed the maxwidth/height settings.

**Comment by nul800sebastiaan** [comment]
Thanks @argentini! It works perfectly for me as you can see below, with ONE caveat:

https://user-images.githubusercontent.com/304656/177953271-9d55135f-9af4-4bf0-91ca-7722824b5149.mp4

As you can see, surprisingly, I can resize to 500.. but any other value just gave me the original image size.

I quickly realized what that was: I had already resized to 500 before I updated the config. So the cached version already existed for this image and it just served the pre-resized one. This is probably what you're seeing as well, I recommend clearing the cache to make sure you are seeing the correct results 👍

**Comment by argentini** [comment]
Hey @nul800sebastiaan I had already tried clearing the image cache prior to posting this issue. I had no MediaCache folder at all.

**Comment by nul800sebastiaan** [comment]
Alright! If you have better steps to reproduce the problem we can have a look, as of now we don't know where the problem could be as we can't reproduce.

**Comment by argentini** [comment]
@nul800sebastiaan sometimes this kind of issue happens due to overly aggressive app settings. I'll take a look at mine and see if I can find a cause and let you know.
