### ISSUE TITLE
Save package with Media throw an error

### ISSUE THREAD

**Issue by rubenberendsen** [umbraco/Umbraco-CMS#12672]
Umbraco 10.0.1

### Bug summary

I want to save Package content with some media but Umbraco gives an error:

`{"ExceptionMessage":"Value cannot be null. (Parameter 'value')","ExceptionType":null,"StackTrace":null}`

### Specifics

![image](https://user-images.githubusercontent.com/38040580/177925551-62a0a5b7-5b4e-4e1e-b7cd-11a6ccae3eb0.png)

### Steps to reproduce

1. Login in Umbraco 10.0.1
2. Go the media and add a folder with some files
3. Go to Packages
4. Create a package
5. Go to the package
6. Select the folder you just added to Media
7. Click on Save and you will see the error
8. You also get the error if you select some files or 'include all child nodes'

---
_This item has been added to our backlog [AB#20710](https://dev.azure.com/umbraco/243e7927-03b2-44e2-908f-d4ac7ea5daaa/_workitems/edit/20710)_

**Comment by nul800sebastiaan** [comment]
Thanks @rubenberendsen, I can indeed reproduce this. Just picking images is fine, but a folder not so much. 
This used to  work in v9.5.2 so I'll mark this as a regression and we'll get it fixed! 👍 

https://user-images.githubusercontent.com/304656/177949952-e6972afa-2ac3-4286-88b8-7c36afec0b62.mp4

**Comment by nul800sebastiaan** [comment]
Fixed in https://github.com/umbraco/Umbraco-CMS/pull/12685
