### ISSUE TITLE
v10: Segment variants are broken

### ISSUE THREAD

**Issue by PerplexDaniel** [umbraco/Umbraco-CMS#12679]
### Which *exact* Umbraco version are you using? For example: 9.0.1 - don't just write v9

10.0.1

### Bug summary

Variants that vary by segment are broken in Umbraco v10. Publishing variants in the backoffice that vary _only_ by segment no longer updates the value in the front-end when retrieving it with `Model.Value<T>("alias", segment: "segment_alias")`. 

I have debugged this extensively and traced it down to [line 294+295 of Property.cs](https://github.com/umbraco/Umbraco-CMS/blame/936dd38c554af53c64119743a3ac31bbfd62a149/src/Umbraco.Core/Models/Property.cs#L294) which were updated in commit 936dd38c554af53c64119743a3ac31bbfd62a149 which was merged as part of PR #12221.

Those lines were changed from

`s1.InvariantEquals(s2)` 
to
`s1?.InvariantEquals(s2) ?? false`

However, when both `s1` and `s2` are `null` the result is now `false` instead of `true`. In the past it returned `true` since `null.InvariantEquals(null)` == `true` because `InvariantEquals` calls `string.Equals(s1, s2, StringComparison.InvariantCultureIgnoreCase)` which is `true`.

Commit 936dd38c554af53c64119743a3ac31bbfd62a149 has mistakenly changed the result of this expression to `false` and that should be reverted.

This replacement pattern is likely used in other contexts too which may have introduced other bugs in other places too that have not been encountered yet.

I will add a PR shortly.

### Steps to reproduce

Note in order to test this you need to enable segmentation which is hidden in the UI by default.
To show the checkmark Permissions > Allow segmentation, add this code to your website:

<details>
<summary><strong>Code to enable segmentation UI</strong></summary>

```csharp
using System.Collections.Generic;
using Umbraco.Cms.Core.Composing;
using Umbraco.Cms.Core.DependencyInjection;
using Umbraco.Cms.Core.Events;
using Umbraco.Cms.Core.Notifications;

namespace Umb10Test
{
    public class EnableDocumentTypeSegmentationServerVariablesParsingNotificationHandler : INotificationHandler<ServerVariablesParsingNotification>
    {
        public void Handle(ServerVariablesParsingNotification notification)
        {
            if (notification.ServerVariables.TryGetValue("umbracoSettings", out var value) &&
                value is Dictionary<string, object> umbracoSettings)
            {
                umbracoSettings["showAllowSegmentationForDocumentTypes"] = true;
            }
        }
    }

    public class EnableDocumentTypeSegmentationServerVariablesParsingNotificationHandlerComposer : IComposer
    {
        public void Compose(IUmbracoBuilder builder)
        {
            builder.AddNotificationHandler<ServerVariablesParsingNotification, EnableDocumentTypeSegmentationServerVariablesParsingNotificationHandler>();
        }
    }
}
```

</details>

1. Create a doctype ("Home") that varies by segment (and *not* by culture)
    ![image](https://user-images.githubusercontent.com/24297947/178253378-fbf01aa4-7498-440c-8515-0a36fea5af8e.png)

2. Add a property ("title") that varies by segment
![image](https://user-images.githubusercontent.com/24297947/178253639-da9fd8c4-941a-4e47-b413-2bddd9d24c74.png)

3. Create a segment, that can only be done through code since there is no UI support for creating them. Execute this code somewhere, can be in the View (Home.cshtml), just do it 1 time. We simply set an empty value to create the segment.
```csharp
// Views/Home.cshtml:
@inject global::Umbraco.Cms.Core.Services.IContentService cs;
var content = cs.GetById(Model.Id);
content.SetValue("title", segment: "segment_alias", value: "");
cs.SaveAndPublish(content);
```
4. Go back to the backoffice and select the "segment_alias" variant from the dropdown, update the Title property and fill some value.
5. Save and publish the variant (in Umbraco)
6. Render the property value in the front-end:
    - Model.Value<T>("title", segment: "segment_alias")
7. Observe you do not see the value you just published in the backoffice.

### Expected result / actual result

Front-end should show the newly published segment value but it does not.

**Comment by Zeegaan** [comment]
Fixed in https://github.com/umbraco/Umbraco-CMS/pull/12680
