### ISSUE TITLE
Incorrect SDK assigned with new 10.0.1 templates

### ISSUE THREAD

**Issue by craigs100** [umbraco/Umbraco-CMS#12694]
### Which *exact* Umbraco version are you using? For example: 9.0.1 - don't just write v9

V10.0.1 on Linux Mint

### Bug summary

Creating a new solution in Rider using the Umbraco Project doesn't give SDK 6.0 for selection despite SDK 6.0.302 being installed on the machine. Causes V9.5.2 to be installed instead of V10.0.1.

### Specifics

Updating templates on machine using `dotnet new -i Umbraco.Templates` results in a dotnet new -all list of 
![image](https://user-images.githubusercontent.com/1143883/179037756-82a41794-ba20-41ed-9c34-81f8f96621c9.png)

There is no "Umbraco Solution" as shown here: https://our.umbraco.com/documentation/Fundamentals/Setup/Install/install-umbraco-with-templates

Also when attempting to create a new Umbraco Project, the dialogue doesn't allow selection of SDK 6.0 in the SDK dropdown:-

![image](https://user-images.githubusercontent.com/1143883/179039867-cf2af4aa-cad2-4e10-aa4e-d6af48dea22c.png)

### Steps to reproduce

Open a terminal
Execute: dotnet --version
Check version is 6.0.302 or higher
Execute: dotnet new -i Umbraco.Templates
Notice Umbraco Solution is not installed
Execute dotnet new --list
Notice notice Umbraco Solution does not exist
Open Rider and select "New Solution"
Note that you can select Framework: net6.0 but not SDK: 6.0
Fill in the dialogue as necessary and hit Create
Note the project installed is Umbraco V9.5.4

### Expected result / actual result

Expected to be able to select SDK 6.0 and install Umbraco V10.0.1

**Comment by nul800sebastiaan** [comment]
> notice Umbraco Solution does not exist

It's called Umbraco Project though, which you do have! 👍  

Everything is perfect on your machine but Rider is missing the dotnet 6 SDK. 
Are you up to date on the latest Rider? I had to update Ubuntu and Rider to the latest to get SDK 6.0.

**Comment by nul800sebastiaan** [comment]
Nobody uses Linux on a daily basis though, so I had to go dig out the Linux laptop ;-) but after updating both all of the Ubuntu package and Rider, and a reboot, I got SDK 6.0 in Rider.

Docs updated 👍

**Comment by rasmusjp** [comment]
> Nobody uses Linux on a daily basis though, so I had to go dig out the Linux laptop ;-)

Really? I've been running Arch on my desktop and laptop for the past ~10 years 😉

Sorry, had to reply to this 😄

**Comment by craigs100** [comment]
Plenty of people use Linux on a daily basis. I'm just one of many. Thanks for digging out your laptop. Jetbrains have now responded with some debugging.

**Comment by nul800sebastiaan** [comment]
Sigh 😅 

Nobody at Umbraco HQ who actively develops daily on Umbraco CMS core code 😛

**Comment by craigs100** [comment]
Just to wrap this up. JetBrains have acknowledged there is a problem in Rider and are addressing it:-

https://rider-support.jetbrains.com/hc/en-us/articles/360016096799/comments/6761008089874

https://youtrack.jetbrains.com/issue/RIDER-80135/Unknown-value-in-SDK-field-in-the-New-Project-window
