### ISSUE TITLE
Filters on users are forgotten between page views despite the UI still showing them as active

### ISSUE THREAD

**Issue by stevetemple** [umbraco/Umbraco-CMS#12705]
### Which *exact* Umbraco version are you using? For example: 9.0.1 - don't just write v9

10.0.1

### Bug summary

The filtering of users to just show active or disabled is remembered between page changes but the actual results shows the list unfiltered between page changes.

### Steps to reproduce

Filter users to show just active users, the view filters as expected, go to content section, then back to users.

The filter still shows active but all users are now displayed. To get active users only to display you have to unselect active and reselect it in the UI.

### Expected result / actual result

I'd expect the filter to be remembered and the results to actually return based on the filter selection

**Comment by nul800sebastiaan** [comment]
Thanks @stevetemple, guess nobody ever noticed (or bothered to report it), I can reproduce this and tried on v8.6.x as well, where it was a problem already. 

https://user-images.githubusercontent.com/304656/179523856-16ce1108-2581-474e-9d94-54128b025f2d.mp4

We'd love a little help getting this fixed!

**Comment by MayurDeore** [comment]
Working on this

**Comment by ustadstar** [comment]
I am working on this.
