### ISSUE TITLE
10.1RC: Information on telemetry settings in the installer

### ISSUE THREAD

**Issue by hemraker** [umbraco/Umbraco-CMS#12701]
### Which *exact* Umbraco version are you using? For example: 9.0.1 - don't just write v9

10.1.0-rc

### Bug summary

When you hover over each of the telemetry settings in the installer you get a description. This is great but it could be improved for discoverability and accessibility.

### Specifics

1. There is no indication you can get more information on the settings
2. Doesn't seem very accessible. Description only show on hover and seems to be injected into the DOM on hover, meaning it does not show when using keyboard navigation (and I assume it's not available for screen readers)
3. The description somewhat incorrectly states that this is where you can see any changes to what is send in the Detailed setting
![image](https://user-images.githubusercontent.com/3663619/179222670-7a79e0dd-0274-4829-a130-7f5d1bf5ef87.png)

### Steps to reproduce

Run the installer :)

**Comment by nul800sebastiaan** [comment]
I'll close this one as it has been greatly improved for the upcoming 10.2.0.

![image](https://user-images.githubusercontent.com/304656/187449169-c459fccf-e797-4a9e-9625-a3941282ab10.png)
