### ISSUE TITLE
Returning false in OnExternalLogin still logs the user in

### ISSUE THREAD

**Issue by Reaction77** [umbraco/Umbraco-CMS#12707]
### Which *exact* Umbraco version are you using? For example: 9.0.1 - don't just write v9

10.0.1

### Bug summary

When using a custom `BackOfficeExternalLoginProviderOptions` to log in via Azure AD, returning false in `OnExternalLogin` still appears to authenticate the user, resulting in a white screen. 

### Specifics

The error: `The AutoLinkOptions of the external authentication provider 'Umbraco.AzureAd' have refused the login based on the OnExternalLogin method. Affected user id: '1'` is recorded in the application log, but is not reflected in the browser.

![image](https://user-images.githubusercontent.com/13795754/179499619-c5764ba4-6917-4b37-9726-b063d907f8b6.png)

### Steps to reproduce

Create a custom back office login by following the documentation
https://our.umbraco.com/Documentation/Reference/Security/External-login-providers/
https://our.umbraco.com/Documentation/Reference/Security/auto-linking/
Attempt to log in, with OnExternalLogin set to return false
```
       public void Configure(BackOfficeExternalLoginProviderOptions options)
        {
            options.AutoLinkOptions = new ExternalSignInAutoLinkOptions(
                autoLinkExternalAccount: true,
                defaultUserGroups: new[] { Umbraco.Cms.Core.Constants.Security.EditorGroupAlias },
                defaultCulture: null,
                allowManualLinking: false
            )
            {
                // Optional callback
                OnAutoLinking = (autoLinkUser, loginInfo) =>
                {
                    // Ommited
                },
                OnExternalLogin = (user, loginInfo) =>
                {
                    // Code to check the roles and conditionally return true or false omitted in order to demonstrate bug
                    return false;
                }
            };
            options.DenyLocalLogin = true;
            options.AutoRedirectLoginToExternalProvider = false;
        }
```

### Expected result / actual result

The error message should be displayed on the log in page. 
![image](https://user-images.githubusercontent.com/13795754/179500460-9b689d9a-f948-469a-8c93-a4bfb490bc65.png)

**Comment by reholz** [comment]
I'm seeing this same issue on a fresh install of v10.3.2, using the OpenIdConnect configuration from the documentation linked above and Azure AD. Everything works as expected as long as `OnExternalLogin` returns true, but returning false redirects the user to /umbraco#/content with these errors:
 
![umbraco10_OnExternalLogin-false_errors](https://user-images.githubusercontent.com/19715468/202814615-3b4af3ed-b150-4b9d-a6a2-dfbfdce4a001.png)

I would expect `IsAuthenticated` to return false.

**Comment by elit0451** [comment]
Hi @Reaction77 👋 

Thank you very much for your patience until we got to this issue 🙏 I can confirm that this is a problem when setting up an external login provider! Setting the `OnExternalLogin` to return `false` causes this behaviour of showing a white page tricking the user to think that they passed the authentication step. But what you see in the log is `"The AutoLinkOptions of the external authentication provider '...' have refused the login based on the OnExternalLogin method. Affected user id: '1'"`, as you indicated. I also confirmed that "_everything works as expected as long as `OnExternalLogin` returns `true`_".

> **Note**:
> I kept `options.DenyLocalLogin = false;` so that I can still login into the backoffice and see the above warning ⬆️ 😅 

One thing that I noticed is that if you attempt to log in with the external provider, then get redirected to the white page BUT click to go back to the login screen, you will see the error that you indicated for the **"Expected result / actual result"** - like:
`The user X for the external provider ... has not been accepted and cannot sign in.` But I agree, you should get the error message right away.

And yes, @reholz, you have a point that one would expect "_IsAuthenticated to return false_".

**Comment by VilladsR** [comment]
Hi, I am experiencing this as well. Any news on this bug or a documented work-around?

**Comment by elit0451** [comment]
Hi all,

Apologies for the late response. It seems like we already have a duplicate issue (https://github.com/umbraco/Umbraco-CMS/issues/14226) that is marked as a `sprint-candidate` (something that we will look into fixing). Therefore, I will go ahead and close this one.

@VilladsR, the linked issue also mentions a workaround that can be used for now 🙂
