### ISSUE TITLE
"Enable URL tracker" button does not update appsettings.{ENV}.json file

### ISSUE THREAD

**Issue by Myster** [umbraco/Umbraco-CMS#12711]
### Which *exact* Umbraco version are you using? For example: 9.0.1 - don't just write v9

10.0.1

### Bug summary

On the Content dashboard for "Redirect URL Management" there is a button titled "Enable URL tracker"

If you have a `appsettings.{ENV}.json` that specifies a `Umbraco:CMS:WebRouting:DisableRedirectUrlTracking` value, then this button has no effect because the `appsettings.json` is modified, but the `appsettings.{ENV}.json` has precedence, and it is not modified.

### Steps to reproduce

Click the "Enable URL tracker" button when you have `DisableRedirectUrlTracking` values specified in both the root appsettings and an active environment appsettings json file.

### Expected result / actual result

The appsettings file with the highest precedence should be modified, not the root appsettings.

**Comment by kjac** [comment]
Hi @Myster,

I do believe the current behavior is the correct one. Any config manipulation performed by Umbraco should target the "main" appsettings file, to be carried across environments as standard configurations. Any environmental overrides of said standard configurations can then be performed in the environment specific config files.

I hope that makes sense?

**Comment by nikolajlauridsen** [comment]
Heya, I'll have to go ahead and close down this issue, since we haven't heard back in 14 days, please feel free to let us know if you have additional information and then we can open up the issue again.
