### ISSUE TITLE
Error overriding translation

### ISSUE THREAD

**Issue by amilcar-dev** [umbraco/Umbraco-CMS#12718]
### Which *exact* Umbraco version are you using? For example: 9.0.1 - don't just write v9

10.0.1

### Bug summary

Hello, I'm trying to override the default backoffice translations. I was following the steps on the documentation, but when I create a new file like en.user.xml it appears the following error: **Culture is not supported. (Parameter 'name') en.user is an invalid culture identifier**
![180014780-88c36361-a00e-422f-9cc7-e5beef1af15f](https://user-images.githubusercontent.com/47063404/180017536-e867a327-5af6-406d-b7c0-4d921865fab7.png)

This is my project structure
![180015130-4eb21ef5-8b00-49f3-868c-2760837c3637](https://user-images.githubusercontent.com/47063404/180017550-db4b970d-af36-475b-89b5-981b2f5ec20a.png)
.

### Steps to reproduce

Create a new translation file, en.user.xml, and add it to the directory umbraco/config/lang

![180015130-4eb21ef5-8b00-49f3-868c-2760837c3637](https://user-images.githubusercontent.com/47063404/180018080-3ddcb257-8928-4994-b350-3e6c655f7794.png)

**Comment by nul800sebastiaan** [comment]
I think you're putting it in the wrong directory, it should be in `config/lang` in the root of your project (see screenshot), the config directory should not be put in the umbraco directory, but one above that.

Other than that it works, here's an example `en_us.user.xml`:

```xml
<?xml version="1.0" encoding="utf-8" standalone="yes"?>
<language alias="en_us" intName="English (US)" localName="English (US)" lcid="" culture="en-US">
  <creator>
    <name>The Umbraco community</name>
    <link>https://our.umbraco.com/documentation/Extending-Umbraco/Language-Files</link>
  </creator>
  <area alias="login">
    <key alias="greeting0">Happy TESTING super Sunday</key>
    <key alias="greeting1">Happy TESTING manic Monday </key>
    <key alias="greeting2">Happy TESTING tubular Tuesday</key>
    <key alias="greeting3">Happy TESTING wonderful Wednesday</key>
    <key alias="greeting4">Happy TESTING thunderous Thursday</key>
    <key alias="greeting5">Happy TESTING funky Friday</key>
    <key alias="greeting6">Happy TESTING Caturday</key>
  </area>
</language>
```

![image](https://user-images.githubusercontent.com/304656/180154245-a8729c92-c9d8-4cb4-9bb6-e280ceb57572.png)

**Comment by amilcar-dev** [comment]
@nul800sebastiaan Thanks a lot for the help! It works now!

**Comment by amilcar-dev** [comment]
> I think you're putting it in the wrong directory, it should be in `config/lang` in the root of your project (see screenshot), the config directory should not be put in the umbraco directory, but one above that.
> 
> Other than that it works, here's an example `en_us.user.xml`:
> 
> ```
> <?xml version="1.0" encoding="utf-8" standalone="yes"?>
> <language alias="en_us" intName="English (US)" localName="English (US)" lcid="" culture="en-US">
>   <creator>
>     <name>The Umbraco community</name>
>     <link>https://our.umbraco.com/documentation/Extending-Umbraco/Language-Files</link>
>   </creator>
>   <area alias="login">
>     <key alias="greeting0">Happy TESTING super Sunday</key>
>     <key alias="greeting1">Happy TESTING manic Monday </key>
>     <key alias="greeting2">Happy TESTING tubular Tuesday</key>
>     <key alias="greeting3">Happy TESTING wonderful Wednesday</key>
>     <key alias="greeting4">Happy TESTING thunderous Thursday</key>
>     <key alias="greeting5">Happy TESTING funky Friday</key>
>     <key alias="greeting6">Happy TESTING Caturday</key>
>   </area>
> </language>
> ```
> 
> ![image](https://user-images.githubusercontent.com/304656/180154245-a8729c92-c9d8-4cb4-9bb6-e280ceb57572.png)

@nul800sebastiaan Thanks a lot for the help! It works now!
