### ISSUE TITLE
Infinite Editor creates each save action a new version of content when content is invalid

### ISSUE THREAD

**Issue by ealse** [umbraco/Umbraco-CMS#12713]
### Which *exact* Umbraco version are you using? For example: 9.0.1 - don't just write v9

10.0.1

### Bug summary

When the Infinite Editor is used and the save button is clicked while the content is not valid there is a content item saved.
Each time the user is clicking on the save button the content is saved with a new ID.

I'm not quite sure if the save action shouldn't happen at all like a save and publish. But the double nodes are not good in any case.

### Specifics

https://user-images.githubusercontent.com/50272817/179773073-9cf392c7-31c0-47fc-a733-1e1a4d83543d.mp4

### Steps to reproduce

- Create a clean Umbraco install following the guide (https://our.umbraco.com/documentation/Fundamentals/Setup/Install/)
- Create a documenttype with a listview that has enabled the Infinite Editor and add a new documenttype below it.
- Create in the Content section a new listview item.
- And click as many times you want on the save button.

### Expected result / actual result

No double items or no items at all.

**Comment by nul800sebastiaan** [comment]
Fixed in https://github.com/umbraco/Umbraco-CMS/pull/12874

**Comment by ClientiWeb** [comment]
I am experiencing the same problem as @thomashdk. I disabled "Infinite Editor" on my list view, and the problem went away. Using Umbraco CMS 13.3.2.

**Comment by aguyfromdenmark** [comment]
I am experiencing the same problem as @thomashdk. I disabled "Infinite Editor" on my list view, and the problem went away. Using Umbraco CMS 13.3.2.

**Comment by ebouma** [comment]
There is an open issue for this problem: https://github.com/umbraco/Umbraco-CMS/issues/15945
The mentioned issue is not only related to content that is invalid.

There is already a pull request available at: https://github.com/umbraco/Umbraco-CMS/pull/16280
hopefully it will be merged soon.
