### ISSUE TITLE
Column 'InvariantName' is constrained to be unique. Value 'Microsoft.Data.SQLite' is already present.

### ISSUE THREAD

**Issue by ironhawk911** [umbraco/Umbraco-CMS#12715]
### Which *exact* Umbraco version are you using? For example: 9.0.1 - don't just write v9

10.0.1

### Bug summary

Executing  a EF6 DBSet query is breaking with the following error:

` Column 'InvariantName' is constrained to be unique. Value 'Microsoft.Data.SQLite' is already present.`

Checking the NET 6 source code 
https://source.dot.net/#System.Data.Common/System/Data/Common/DbProviderFactories.cs,d0b01e77b0b167eb

The cause maybe Umbraco registered two DB Factory with the same name:

Microsoft.Data.SQLite
Microsoft.Data.Sqlite

### Specifics

ConstraintException: Column 'InvariantName' is constrained to be unique. Value 'Microsoft.Data.SQLite' is already present.

System.Data.UniqueConstraint.CheckConstraint(DataRow row, DataRowAction action)
System.Data.DataTable.RaiseRowChanging(DataRowChangeEventArgs args, DataRow eRow, DataRowAction eAction, bool fireEvent)
System.Data.DataTable.SetNewRecordWorker(DataRow row, int proposedRecord, DataRowAction action, bool isInMerge, bool suppressEnsurePropertyChanged, int position, bool fireEvent, out Exception deferredException)
System.Data.DataTable.InsertRow(DataRow row, long proposedID, int pos, bool fireEvent)
System.Data.Common.DbProviderFactories.GetFactoryClasses()
System.Data.Entity.Utilities.DbProviderFactoryExtensions.GetProviderInvariantName(DbProviderFactory factory)
System.Data.Entity.Infrastructure.DependencyResolution.DefaultInvariantNameResolver.GetService(Type type, object key)
System.Collections.Concurrent.ConcurrentDictionary<TKey, TValue>.GetOrAdd(TKey key, Func<TKey, TValue> valueFactory)
System.Linq.Enumerable+SelectArrayIterator<TSource, TResult>.MoveNext()
System.Linq.Enumerable.TryGetFirst<TSource>(IEnumerable<TSource> source, Func<TSource, bool> predicate, out bool found)
System.Data.Entity.Infrastructure.DependencyResolution.ResolverChain.GetService(Type type, object key)
System.Linq.Enumerable+SelectArrayIterator<TSource, TResult>.MoveNext()
System.Linq.Enumerable.TryGetFirst<TSource>(IEnumerable<TSource> source, Func<TSource, bool> predicate, out bool found)
System.Data.Entity.Infrastructure.DependencyResolution.ResolverChain.GetService(Type type, object key)
System.Data.Entity.Utilities.DbConnectionExtensions.GetProviderInvariantName(DbConnection connection)
System.Data.Entity.Internal.InternalConnection.get_ProviderName()
System.Data.Entity.Internal.DefaultModelCacheKeyFactory.Create(DbContext context)
System.Data.Entity.Internal.LazyInternalContext.InitializeContext()
System.Data.Entity.Internal.InternalContext.Initialize()
System.Data.Entity.Internal.InternalContext.GetEntitySetAndBaseTypeForType(Type entityType)
System.Data.Entity.Internal.Linq.InternalSet<TEntity>.Initialize()
System.Data.Entity.Internal.Linq.InternalSet<TEntity>.Include(string path)
System.Data.Entity.Infrastructure.DbQuery<TResult>.Include(string path)
System.Data.Entity.QueryableExtensions.Include<T, TProperty>(IQueryable<T> source, Expression<Func<T, TProperty>> path)
MyApps.Web.Infrastructure.DataAccess.Account.UserDa.GetUserProfileByEmail(string email) in UserDa.cs
```
UserProfileDto? result = null;
            using (var db = new MyDbContext())
            {
                var data = await db.UserProfiles;
```

### Steps to reproduce

Calling the following code will reproduce the error:

`System.Data.Common.DbProviderFactories.GetFactoryClasses();`

### Expected result / actual result

Should not break EF6 calls.

**Comment by nul800sebastiaan** [comment]
Yeah, seems like there's not much we can do here, we had to migrate the name to make sure it would work on MacOS if I read the related commits correctly. 

https://github.com/umbraco/Umbraco-CMS/blob/v10/contrib/src/Umbraco.Cms.Persistence.Sqlite/UmbracoBuilderExtensions.cs#L49

Maybe you can register EF6 after Umbraco has unregistered the duplicate name? FYI: I have absolutely no knowledge about EF6 at all so I may be saying something stupid.

What is it you want to use EF6 plus the Umbraco database for, out of curiosity?

**Comment by ironhawk911** [comment]
We have custom MVC forms / RenderController that accessing our database via Entity Framework 6. 
It used to work in Umbraco v9 but breaking after upgrading to v10. The error is inside System.Data namespace and nothing directly from Umbraco, it was really difficult to find out actual source of the problem.

As you’ve suggested, that was also the solution I thought of since we are using Sql server for our DB. I have unregistered the legacy SQLite name and that seems to work.  
I just hope there are no after effects within Umbraco for doing that.

**Comment by nul800sebastiaan** [comment]
For the next person who has this problem, can you please show how you unregistered it? 😄  

As I thought that we already did that for you with the code I linked to but maybe that doesn't quite work? 🤔 

Other than that, if you don't use SQLite (which you shouldn't for production sites) then there will be no after effects.

**Comment by ironhawk911** [comment]
It works now, thanks for the great work. Keep it up.

**Comment by kjac** [comment]
Hi everyone. Seems this issue has been resolved already?

I'll go ahead and close it now. Please feel free to reopen it if I missed something 🙈
