### ISSUE TITLE
Custom document type editor icons do not work in FireFox (macos/win)

### ISSUE THREAD

**Issue by argentini** [umbraco/Umbraco-CMS#12729]
### Which *exact* Umbraco version are you using? For example: 9.0.1 - don't just write v9

10.01

### Bug summary

When adding custom icons to the back office via App_Plugins, the document type icon picker only shows built-in icon choices in Firefox.

### Steps to reproduce

Add custom icons to Umbraco. Then in Firefox edit a document type and open the icon picker. Only the built-in types will be shown.

### Expected result / actual result

Should see all icons.

**Comment by nul800sebastiaan** [comment]
Strange! Works for me on Windows (Edge and Firefox).

![image](https://user-images.githubusercontent.com/304656/180721816-d3395657-88df-4078-a627-f0a1673913b0.png)

Make sure the icons are in `~/App_Plugins/MyPlugin/Backoffice/Icons`. 

If that's the case then please provide

**Comment by argentini** [comment]
@nul800sebastiaan I wasn't putting svg images there. I have a `package.manifest` that referenced css files in `App_Plugins/MyPlugin`. The font files are woff2 and are in `wwwroot/webfonts`.

**Comment by nul800sebastiaan** [comment]
Okay, sorry, but we only look for SVGs these days :)

**Comment by argentini** [comment]
Understood. I'll switch out my icons for SVG versions.
