### ISSUE TITLE
V10: Rollback feature not working

### ISSUE THREAD

**Issue by jonat123** [umbraco/Umbraco-CMS#12735]
### Which *exact* Umbraco version are you using? For example: 9.0.1 - don't just write v9

10.0.1

### Bug summary

Rolling back content on v10 is not working.

When choosing a version to rollback to, the change is not reflected on the content node and the node is not rolled back

![rollback](https://user-images.githubusercontent.com/54025331/180796505-e3b240c2-5b3c-4b99-a712-0c16044136fb.gif)

### Specifics

Checked the browser for errors, and none there and no errors in the backoffice

### Steps to reproduce

- Create document type with some properties
- Go to the content section and make some changes to a property
- Go to the info tab and click the rollback button
- rollback to a previous version
- Check the node and see if changes is reflected.

### Expected result / actual result

Expected result:

The node is rolled back to the previous version

actual result:

nothing happens, the content is not rolled back

---
_This item has been added to our backlog [AB#20894](https://dev.azure.com/umbraco/243e7927-03b2-44e2-908f-d4ac7ea5daaa/_workitems/edit/20894)_

**Comment by shearer3000** [comment]
hi - has this missed the cut for release 10.1?

**Comment by nul800sebastiaan** [comment]
Yes it has, also we haven't started on a fix yet in the 17 hours since this report. 😉

**Comment by nikolajlauridsen** [comment]
Fixed in #12808
