### ISSUE TITLE
WriterId returns 0 by default when I try to use MediaService Thrashed event

### ISSUE THREAD

**Issue by pikopiko15** [umbraco/Umbraco-CMS#12748]
### Which *exact* Umbraco version are you using? For example: 9.0.1 - don't just write v9

8.16.0

### Bug summary

Hello! 

I tried to log content editors' actions when they move an image or media folder to the recycle bin by using MediaService.Thrashed event. However, the WriterId returns 0 everytime.

`private void MediaService_Trashed(IMediaService sender, MoveEventArgs<IMedia> e)
        {
            var movedData = string.Join(";", e.MoveInfoCollection.Select(x => $"{x.Entity.Id}({x.Entity.Name})"));
            var editorData = e.MoveInfoCollection.FirstOrDefault();
            var editorId = editorData.Entity.WriterId;
            var user = this.userService.GetUserById(editorId);
            var thrashedCount = e.MoveInfoCollection.Count();
            Logger.Information("{someone}({email}) trashed {count} content. {movedData}", user?.Username, user?.Email, thrashedCount, movedData);
        }`

### Specifics

![image](https://user-images.githubusercontent.com/37023297/181690207-bfc89ea8-031e-4fde-8ff4-9d29c2cfaf46.png)
![image](https://user-images.githubusercontent.com/37023297/181690584-da29eedf-e290-44fc-812f-40c84b6fb079.png)
![image](https://user-images.githubusercontent.com/37023297/181690667-b8c65832-89b0-41d0-a4bb-834077b80db8.png)

### Steps to reproduce

Subscribe to a MediaService.Thrashed event
Move any media file to a bin
Try to get some useful data e.g. user name/email via WriterId

**Comment by kjac** [comment]
Hi @pikopiko15,

Thank you for reaching out. Apologies for the late response...

Unfortunately V8 is no longer applicable for these kinds of fixes. However there is a PR that fixes this for V11, so sooner or later this *will* be fixed 😆

**Comment by nul800sebastiaan** [comment]
Fixed in https://github.com/umbraco/Umbraco-CMS/pull/12843
