### ISSUE TITLE
Images in default dashboard has pointer cursor

### ISSUE THREAD

**Issue by bjarnef** [umbraco/Umbraco-CMS#12742]
### Which *exact* Umbraco version are you using? For example: 9.0.1 - don't just write v9

10.0.1

### Bug summary

When opening the default dashboard in content section with latest news, the images have pointer cursor although these are not clickable.

![image](https://user-images.githubusercontent.com/2919859/181190344-5515508b-00fb-47d9-96f9-e7f02ac512f2.png)

At first I thought the link was just broken, but then noticed it wasn't a link at all.

### Steps to reproduce

Open the default dashboard in content section and click any of the images.
Nothing happens.

Clicking the buttons/anchors below do work though.

**Comment by nul800sebastiaan** [comment]
Thanks I'll report it to the HQ team updating the dashboards.
