### ISSUE TITLE
SendingContentNotification is not firing in v10.0.1

### ISSUE THREAD

**Issue by teeto** [umbraco/Umbraco-CMS#12762]
### Which *exact* Umbraco version are you using? For example: 9.0.1 - don't just write v9

10.0.1

### Bug summary

I am suscribing to SendingContentNotification to set AllowPreview=false
It is not firing, Preview button shows and i have tried logging it and never logs.

```csharp
public class SubscribeToEditorModelEventsHandler : INotificationHandler<SendingContentNotification>
    {
        private readonly ILogger<SubscribeToEditorModelEventsHandler> _logger;

        public SubscribeToEditorModelEventsHandler(ILogger<SubscribeToEditorModelEventsHandler> logger)
        {
            _logger = logger;
        }
        public void Handle(SendingContentNotification notification)
        {
            _logger.LogInformation("{ContentId} is editing", notification.Content.Id);
            notification.Content.AllowPreview = false;

        }
    }
```

### Steps to reproduce

Create a class SubscribeToEditorModelEventsHandler like the code provided and test in Umbraco

**Comment by ealse** [comment]
I think you are missing the builder.AddNotificationHandler<SendingContentNotification, SubscribeToEditorModelEventsHandler>();
See [documentation](https://our.umbraco.com/documentation/Fundamentals/Code/Subscribing-To-Notifications/)

**Comment by teeto** [comment]
Yes, i was missing that!

**Comment by nikolajlauridsen** [comment]
Looks like this is all sorted, so I'll go ahead and close the issue 😄
