### ISSUE TITLE
Requests for Files in App_Plugins return 404 under Linux

### ISSUE THREAD

**Issue by mirkomaty** [umbraco/Umbraco-CMS#12763]
### Which *exact* Umbraco version are you using? For example: 9.0.1 - don't just write v9

10.0.1

### Bug summary

I wrote an Umbraco application with a custom section and tree. It works fine under Windows but under linux the editor window on the right side doesn't appear because of a 404. The error message is

_Request error: The URL returned a 404 (not found):
/App_Plugins/Laykit/backoffice/LaykitTree/edit.html_

Same problem with the dashboard view:

_/App_Plugins/Laykit/dashboard/LaykitStylesDashboard.html_

The files are definitely there. I wrote a controller, which returns the MapPathContentRoot. If I call it with the above path as parameter, it returns the following:

/app/App_Plugins/Laykit/backoffice/LaykitTree/edit.html

This is the correct path. If I open a console inside the app container, I can find the file under the correct case sensitive location. The name of the Section is Laykit, the name of the tree is LaykitTree.

The content section works fine under linux.

### Steps to reproduce

See [comment below](https://github.com/umbraco/Umbraco-CMS/issues/12763#issuecomment-1201483874), which contains a solution with the section and dashboard.

Build an Umbraco Instance with a custom section. Just define a dashboard for the section like that:
```
...
"dashboards": [ {
			"alias": "laykitStylesDashboard",
			"view": "~/App_Plugins/Laykit/dashboard/LaykitStylesDashboard.html",
			"sections": [ "laykit" ],
			"weight": 10
} ]
...

```
Under Windows in VS Umbraco shows the dashboard view, if it exists, under linux it doesn't show even if it exists.

### Expected result / actual result

Umbraco should find the files under App_Plugins and show the dashboard and edit windows.

**Comment by mirkomaty** [comment]
Attached is a zip file with a complete solution. It works under Windows. If you click at [laykit] in the menu, it shows the text "Some Content" in the dashboard. Under linux you can see the error message instead of the text.

Login with mirko@matytschak.de, password My$Umbraco4Password

In BuildWithDocker.zip you find a folder 'app' with a Readme.txt file. It describes, howto build a working container.

[Umbraco10Dashboard.zip](https://github.com/umbraco/Umbraco-CMS/files/9235831/Umbraco10Dashboard.zip)
[BuildWithDocker.zip](https://github.com/umbraco/Umbraco-CMS/files/9235864/BuildWithDocker.zip)

**Comment by mirkomaty** [comment]
Some more information about the problem. I changed the source code of UmbracoPluginPhysicalFileProvider to log the relative path and the PhysicalPath result of GetFileInfo(). The result seems to be reasonable.

`/Laykit/dashboard/LaykitStylesDasboard.html->/app/App_Plugins/Laykit/dashboard/LaykitStylesDasboard.html`

But it seems, as if this code in ApplicationBuilderExtensions.cs (line 137) causes the problem:

```
if (webHostEnvironment is not null)
{
    webHostEnvironment.WebRootFileProvider = webHostEnvironment.WebRootFileProvider.ConcatComposite(
        new PrependBasePathFileProvider(Constants.SystemDirectories.AppPlugins, pluginFileProvider));
}

```

Since the pluginFileProvider inserts the /App_Plugins prefix to the relative path, the PrependBasePathFileProvider is just not needed. Looking at the source of [PrependBasePathFileProvider](https://github.com/dazinator/Dazinator.Extensions.FileProviders/blob/develop/src/Dazinator.Extensions.FileProviders/PrependBasePath/PrependBasePathFileProvider.cs), if the prefix is already in the subPath, TryMapSubPath returns null. The logic of the whole system is a little bit confusing at this point.

**Comment by nul800sebastiaan** [comment]
I think `"view": "~/App_Plugins/Laykit/dashboard/LaykitStylesDashboard.html",` Should be `view": "/App_Plugins/Laykit/dashboard/LaykitStylesDashboard.html",`  (remove the `~`) and then it should work. Besides that make sure the exact casing is correct for all the files and path names.

Consider moving to RCLs, to make it easier to avoid casing issues on Linux as well: 
- https://dev.to/kevinjump/umbraco-10-razor-class-library-packages-pt3-40bb
- Video of UmbraCollab where we did this recently: https://www.youtube.com/watch?t=547&v=66W8nlLHWpQ&feature=youtu.be

I'm going to close this issue as we're not aware of any Linux-specific casing issues at this time, removing the `~` should help make everything work and if it doesn't, it would be a good idea to start a forum thread. Make sure to head on over to https://our.umbraco.com and ask follow up questions there.

**Comment by mirkomaty** [comment]
Just for the records, for somebody having the same issue. I checked, if the file /App_Plugins/Laykit/backoffice/LaykitTree/edit.html was there, but saw the file edit.js and confused the two file names. For the dashboard I didn't check, if the file was in the publish folder. The files were not in the Publish folder. Copying the files to the publish folder manually and building the container again solved the problem. ~/App_Plugins or /App_Plugins both work. But anyway starting a path with ~ under Linux doesn't make much sense.

But now the main reason, why I write this comment: Web Publishing in VS copies a bunch of files, but not all files of the App_Plugins folder. .js files will be copied, .html files not. You have to walk through all files in App_Plugins and choose "Copy to output directory" in the VS properties window. This will copy all needed files during publishing.

@nul800sebastiaan : Sorry for consuming your time. I'll definitely have a look at RCLs. Thanks for the tip.
