### ISSUE TITLE
Installer form should have a more descriptive name

### ISSUE THREAD

**Issue by iOvergaard** [umbraco/Umbraco-CMS#12771]
The form name should probably be updated to something meaningful instead of `myForm`, e.g. `installerForm`.

_Originally posted by @bjarnef in https://github.com/umbraco/Umbraco-CMS/issues/12739#issuecomment-1202370184_

**Comment by bjarnef** [comment]
Hi @iOvergaard 

I will comment on this as I can only open a bug report or new discussion.

It seems it is also possible to interact with pips, so maybe we should highlight the active pip?
https://refreshless.com/nouislider/examples/#section-pips

**Comment by iOvergaard** [comment]
Nice find, @bjarnef. You are right, this would be a nice addition.
