### ISSUE TITLE
Warning "FindTemplate: Could not find template with id null" should not occur when no template is configured

### ISSUE THREAD

**Issue by PerplexDaniel** [umbraco/Umbraco-CMS#12781]
### Which *exact* Umbraco version are you using? For example: 9.0.1 - don't just write v9

10.1.0

### Bug summary

A warning `FindTemplate: Could not find template with id null` is logged every time a page is requested that has no template configured. This is obviously useless as a template will never be found when the template id is `null` (or `0`). We do not use Umbraco templates in our websites at all - we use Route Hijacking with views in custom locations instead - so our log is spammed with these warnings:

![image](https://user-images.githubusercontent.com/24297947/182822590-b367c512-ba39-4d40-ad27-fb93b2728fef.png)

Our document types have no associated templates so all content nodes show something similar to this on their Info tab:
![image](https://user-images.githubusercontent.com/24297947/182824416-5656f0d4-6443-4925-8985-fde2487e010e.png)

I will add a PR shortly.

### Steps to reproduce

1. Create a doctype without a template.
2. Create a content node based on that doctype
3. Visit the page (if you did not add a `<doctype>.cshtml` file in Views/ it will crash but that's fine)
4. Check the log and observe the warning `FindTemplate: Could not find template with id null`.

### Expected result / actual result

This warning should not be logged for pages that have no template configured.

**Comment by glombek** [comment]
Fixed by #12782
