### ISSUE TITLE
Rename your Umbraco-folder Not working

### ISSUE THREAD

**Issue by Navorski** [umbraco/Umbraco-CMS#12780]
### Which *exact* Umbraco version are you using? For example: 9.0.1 - don't just write v9

v10.1.0

### Bug summary

When following the steps on 
[https://our.umbraco.com/documentation/Reference/Security/Security-hardening/](url)
to change the Umbraco folder, 
This is not working, the only thing i can see is a blank page.

### Specifics

Using VS2022 with the Umbraco Templates installed v10.1.0, Starting the website using IIS Express from within VS2022.

After the site spins up, the backend should be accessible from [localhost/my-secret-loginpanel](url)
But this is not the case, a blank page appears, no errors, nothing, just a blank page

### Steps to reproduce

Clean install Umbraco
Follow the steps to change the Umbraco Folder
Run the project,

### Expected result / actual result

I could use the Umbraco Login page into the backoffice on the new url, but instead this is not working
nor is the /umbraco anymore

**Comment by nul800sebastiaan** [comment]
Duplicates #12593 - we'll work on it for a future release soon.
