### ISSUE TITLE
Custom backoffice URL in v10 not working after migration from v9

### ISSUE THREAD

**Issue by petrsoudek** [umbraco/Umbraco-CMS#12795]
### Which *exact* Umbraco version are you using? For example: 9.0.1 - don't just write v9

10.0.1

### Bug summary

Backoffice could not be run on custom url after upgrading from v9 to v10. It loads just blank white screen.

### Steps to reproduce

Edit backoffice url on v10 installation. Follow this docs>

Rename your Umbraco-folder
https://our.umbraco.com/documentation/reference/security/Security-hardening/

**Comment by nul800sebastiaan** [comment]
Duplicates https://github.com/umbraco/Umbraco-CMS/issues/12593 - we'll work on it for a future release soon.
