### ISSUE TITLE
UmbracoApiController doesn't use JsonPropertyName

### ISSUE THREAD

**Issue by patrickdemooij9** [umbraco/Umbraco-CMS#12800]
### Which *exact* Umbraco version are you using? For example: 9.0.1 - don't just write v9

10.0.0

### Bug summary

According to the .Net Core documentation, you should be able to use JsonPropertyName for serialization of your POST models, but this doesn't seem to be working for UmbracoApiControllers. Maybe I am missing something or maybe there is a certain function to be called.

### Steps to reproduce

Given code:
```
public class TestApiController : UmbracoApiController
    {
        [HttpPost]
        public IActionResult Test2(TestPostModel postModel)
        {
            return Ok(postModel);
        }

        public class TestPostModel
        {
            [JsonPropertyName("Hallo")]
            public string Test { get; set; }
        }
    }
```

gives this on a request
![image](https://user-images.githubusercontent.com/11466511/183388538-30b776b7-61a8-4583-8ed8-f7f7127d2f7b.png)

This should return the value that I am sending, but it doesn't. It does use the correct deserialization on the Ok return, but not while serializing.

### Expected result / actual result

Above steps should return "Hallo": "Hello"

**Comment by nul800sebastiaan** [comment]
I can reproduce. As a workaround you can add `[JsonProperty["Hallo"]` from newtonsoft JSON on the model as well.

**Comment by bergmania** [comment]
I guess the issue here is that we most likely use MS Json when inputting and Newtonsoft when outputting.

**Comment by bergmania** [comment]
If I update to use newtonsoft on input it works in most ways using only `[JsonProperty("Hallo")]`.

I added `services.AddControllers().AddNewtonsoftJson();` in my startup, but Im unsure if this breaks something else.

**Comment by nul800sebastiaan** [comment]
By the way @patrickdemooij9 if you don't need anything from the Umbraco context then of course you could "just" use a regular ASP.NET controller like above and it will work.

One important thing to note in `TestPlainController` if I don't add `[FromBody]` then model doesn't bind at all, whether I input: `{ "Hallo":  "hey" }` or `{ "Test":  "hey" }`. For the `UmbracoApiController` it isn't necessary to add `[FromBody]`, though I added it in this example to make sure both controllers were the same.

**Comment by bergmania** [comment]
> Then it works as expected! Which is what @patrickdemooij9 was expecting. However in an UmbracoApiController it seems like something breaks that part, maybe it is indeed because Newtonsoft is somewhere in the middle there??

Interesting.. From what I can see quickly in the code base, our APIs uses `UmbracoJsonModelBinder` to modelbind from json. This uses `NewtonsoftJsonInputFormatter`. It make sense to use the same serializer both for input and output.

**Comment by kjac** [comment]
Hi @patrickdemooij9 (and everyone else) 👋 

I can reproduce this on V10.3.2 using the following code:

```csharp
public class MyApiController : UmbracoApiController
{
    [HttpGet]
    public IActionResult GetIt() => Ok(new MyApiModel {TheString = "Hello, world"});
    
    [HttpPost]
    public IActionResult PostIt(MyApiModel model) => Ok(model);
}


[ApiController]
public class MyOtherApiController : ControllerBase
{
    [HttpGet]
    [Route("/umbraco/api/myotherapi/getit")]
    public IActionResult GetIt() => Ok(new MyApiModel {TheString = "Hello, world"});
    
    [HttpPost]
    [Route("/umbraco/api/myotherapi/postit")]
    public IActionResult PostIt(MyApiModel model) => Ok(model);
}

public class MyApiModel
{
    [JsonPropertyName("RenamedProperty")]
    public string TheString { get; set; } = string.Empty;
}
```

When invoking the GET method on `MyApiController`, the property is serialized using the supplied `JsonPropertyName`, but when invoking the POST method, the POST'ed model does not deserialize using the supplied `JsonPropertyName`. When invoking `MyOtherApiController` it does serialize and deserialize just fine for both the GET and the POST.

As Bjarke mentions this has to do with how we do model binding for `UmbracoApiController`. Changing that to support System.Text.Json is quite the task and likely not something we'll want to do right away - also considering breakage here. We could however consider enforcing the same handling when serializing output models so the behavior is at least consistently applying Newtonsoft.Json (de)serialization.

I will bring this back to the team and we'll discuss a course of action here.

**Comment by kjac** [comment]
Hi @patrickdemooij9

We've been over this internally and we're somewhat reluctant to mend it. The only way to fix this is to enforce a `NewtonsoftJsonOutputFormatter` on the response body, and while this can be done without binary breakage, there is a rather large risk it'll result in behavioural breakage.

For V13 we are planning an application wide replacement of `Newtonsoft.Json` in favour of `System.Text.Json`, which will hopefully produce more predictable serialization results in these cases.

For anyone wanting to enfore a `NewtonsoftJsonOutputFormatter` on the API response body you can your API controllers with this attribute implementation:

```csharp
using System.Buffers;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Filters;
using Microsoft.AspNetCore.Mvc.Formatters;
using Microsoft.Extensions.Options;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Serialization;

namespace Umbraco.Cms.Web.Common.Attributes;

public class UmbracoJsonOutputAttribute : TypeFilterAttribute
{
    public UmbracoJsonOutputAttribute() : base(typeof(UmbracoJsonOutputAttributeFilter))
    {
    }

    private class UmbracoJsonOutputAttributeFilter : IResultFilter
    {
        private readonly ArrayPool<char> _arrayPool;
        private readonly MvcOptions _options;

        public UmbracoJsonOutputAttributeFilter(ArrayPool<char> arrayPool, IOptionsSnapshot<MvcOptions> options)
        {
            _arrayPool = arrayPool;
            _options = options.Value;
        }

        public void OnResultExecuting(ResultExecutingContext context)
        {
            if (context.Result is not ObjectResult { Formatters.Count: 0 } objectResult)
            {
                return;
            }

            var jsonOptions = new MvcNewtonsoftJsonOptions()
            {
                SerializerSettings =
                {
                    Converters = new List<JsonConverter> { new StringEnumConverter() },
                    Formatting = default,
                    NullValueHandling = default,
                    ContractResolver = new DefaultContractResolver()
                }
            };

            objectResult.Formatters.Clear();
            objectResult.Formatters.Add(new NewtonsoftJsonOutputFormatter(jsonOptions.SerializerSettings, _arrayPool, _options, jsonOptions));
        }

        public void OnResultExecuted(ResultExecutedContext context)
        {
        }
    }
}
```

**Comment by AdTarling** [comment]
Hi @kjac , not sure if this message will be picked up as this issue has been deemed closed, but I'm running into the same behaviour as described in the original post and this seems like an issue that Umbraco will need to fix as System.Text.Json slowly usurps Newtonsoft.Json.

In fact Umbraco even seem to be doing the same internally to implement 'an application wide replacement of Newtonsoft.Json in favour of System.Text.Json, which will hopefully produce more predictable serialization results in these cases'.

However, as things currently stand, an Umbraco API controller doesn't respect System.Text.Json on the way into the controller, but does on the way out, which is odd.

The final solution above infact reverses the purpose of the original post which was to integrate with System.Text.Json.  The attribute above implements a Newtonsoft based attribute, which would seem even more strange both in the context of the original post, but also Umbraco's gradual removal of Newtonsoft.

Context on my situation is that I've just upgraded our codebase to use Algolia 7, which has replaced Newtonsoft with System.Text.Json.  Upon assessment and consideration I also felt that this was a good idea for our Umbraco application, so as to modernise and receive the benefits of the faster data (de)serialization.

However, I'm now left with almost 100 percent System.Text.Json coverage across the codebase, with a few dto objects decorated with Newtonsoft attributes to comply with the Umbraco API controller System.Text.Json / Newtonsoft disconnect.  This could introduce bugs in the future, and, at the very least, now be confusing for new developers onto the project to understand why we have almost 100 percent System.Text.Json usage, plus a small amount of Newtonsoft in the API layer.

As I say, not sure if this will be read, but I would suggest that this needs fixing at some point.  Thanks.

**Comment by bjarnef** [comment]
@kjac it seems `UmbracoJsonOutputAttribute` doesn't exist in the repository, but just an example to implement in ourselves?
