### ISSUE TITLE
Partial view with snippets does not work in Umbraco 10 and 9

### ISSUE THREAD

**Issue by jonat123** [umbraco/Umbraco-CMS#12802]
### Which *exact* Umbraco version are you using? For example: 9.0.1 - don't just write v9

10.1.0 and 9.5.0

### Bug summary

When trying to create a partial view with a snippet (tested with the navigation snippet) the snippet returns an error out of the box and does not work:
![image](https://user-images.githubusercontent.com/54025331/183432469-933881d9-f2a3-49d1-834b-6210167bd9e9.png)

As soon as its created i can see that it already gives me some errors on the Model?.Content.Root() and Model?.Content).

### Specifics

it complains about a missing reference.

Just to test, I tried to create a partial view macro with the navigation snippet, and on that one there are no errors and it seems to work fine.

The only difference that I can see is that the partial view inherits from` Umbraco.Cms.Web.Common.Views.UmbracoViewPage `while the partial view macro file is inheriting from `Umbraco.Cms.Web.Common.Macros.PartialViewMacroPage`.

By changing the code example in the partial view snippet from `Model?.Content.Root()`  on line 15 to `Model.Root()` and change  `Model?.Content)` on line 22 to just `Model`, it seems that it works.

### Steps to reproduce

1 go to the settings section in the backoffice
2. create partial view  navigation from snippet
3. Go to the view in visual studio or similar and you can see that it gives errors for `Model?.Content.Root() and for Model?.Content)

### Expected result / actual result

Expected there to be no errors as it comes out-of-the-box in Umbraco and work without issues.

**Comment by nul800sebastiaan** [comment]
This seems to have broken when we switched to nullable reference types, the same snippet is used for macros and partial view, but for partials we replace `Model.Content` for `Model.`. Now that the snippets all have `Model?.Content` that doesn't work any more. 
Should be fixed here: https://github.com/umbraco/Umbraco-CMS/blob/v10/contrib/src/Umbraco.Core/Snippets/PartialViewSnippetCollection.cs#L66
