### ISSUE TITLE
Issue with downloading certain files from Media

### ISSUE THREAD

**Issue by Yoadd** [umbraco/Umbraco-CMS#12801]
### Which *exact* Umbraco version are you using? For example: 9.0.1 - don't just write v9

9.3.1

### Bug summary

Unable to download **certain** files after uploading them to Media.

### Specifics

After uploading a `.rvt` file to Media and clicking the generated link - `/media/x0dcaaju/1600.rvt`, a `Status Code: 404; Not Found` is shown.

![1600](https://user-images.githubusercontent.com/84516932/183427076-d5774d25-defb-4ba5-bed3-83792262007d.png)

Upon clicking the link:
![404](https://user-images.githubusercontent.com/84516932/183427234-07597432-ec39-47e7-807e-5400017dbe1d.png)

### Steps to reproduce

1. Upload an `.rvt` file to Media.
2. Click the generated link.

### Expected result / actual result

The intended outcome is for the file to be downloaded.

It works well with common file types such as pdf, doc, png, gif, but fails to work with files such as .rvt.

**Comment by RichardGrimshaw** [comment]
I'm having a similar issue with version 10.0.1.
In the Startup.cs file I've added lines 49-50, 59-64 to the Configure function so I can upload .dae files:
![image](https://user-images.githubusercontent.com/44813346/183438293-49bc1ded-de3c-4807-b530-129ea0586961.png)
That fixes the issue of being able to upload .dae files, however the image cropper feature then breaks because of that change. Does anyone know a solution, thanks

**Comment by RichardGrimshaw** [comment]
Think I've found a solution:
![image](https://user-images.githubusercontent.com/44813346/183600082-4d1d9d19-139a-4583-ab5a-6a0630b71eaa.png)

**Comment by Yoadd** [comment]
> Think I've found a solution: ![image](https://user-images.githubusercontent.com/44813346/183600082-4d1d9d19-139a-4583-ab5a-6a0630b71eaa.png)

This works but I now can't upload pdf files to Umbraco for some reason and adding 
`provider.Mappings[".pdf"] = "application/pdf"`
does not help either

**Comment by kjac** [comment]
Hi @Yoadd,

Thanks for reaching out. My apologies for the quite belated answer.

This is a .Net Core thing; the default static file middleware knows and handles about 400 different file formats (mime type mappings). However, you can indeed add your own with `app.UseStaticFiles`.

The following code adds "download" mapping for .dae-files:

```csharp
var provider = new FileExtensionContentTypeProvider();
provider.Mappings.Add(".dae", "application/x-msdownload");

app.UseStaticFiles(new StaticFileOptions
{
    ContentTypeProvider = provider
}); 
```

Try adding that at the very end of `public void Configure(IApplicationBuilder app, IWebHostEnvironment env)` in `Startup`. When tested on V10.3.2 this seems to work just fine, and does not clash with PDF uploads/downloads or other file/image serving.

I'm going to close this issue now. I would refer you to the forum (https://our.umbraco.com/forum) if you have anymore issues with this 😄
