### ISSUE TITLE
Not able to set password if content root is missing

### ISSUE THREAD

**Issue by TimoTielens** [umbraco/Umbraco-CMS#12809]
### Which *exact* Umbraco version are you using? For example: 9.0.1 - don't just write v9

8.18.4

### Bug summary

If I invite a new user with an group that does not contain a content root, the user cannot create a password. The User will receive an email to setup their account, however the page will be redirected to login/false

### Specifics

No good log to find :(

### Steps to reproduce

1. Create user group without content root
2. Create new user with this group
3. Reiceve email
4. Click on link from email
5. Get redirected to localhost:53579/umbraco#/login/false?returnPath=%252Fcontent

### Expected result / actual result

5. Get redirect to page to setup password

**Comment by nikolajlauridsen** [comment]
Hey all, I'll have to go ahead and close down this issue, since we can't reproduce it and haven't heard back in 14 days, please feel free to let us know if you have additional information and then we can open up the issue again.
