### ISSUE TITLE
Cannot move multiple properties to a new tab

### ISSUE THREAD

**Issue by arknu** [umbraco/Umbraco-CMS#12810]
### Which *exact* Umbraco version are you using? For example: 9.0.1 - don't just write v9

10.1.0

### Bug summary

I am reorganizing some properties in a document type. I click reorder. Then I can drag one property to a new tabs and drop it just fine. However, dragging the next property onto the tab doesn't change tabs and thus I cannot drop the property. It would seem that some kind of internal state doesn't get reset. 

I have to reload to get the drag and drop feature to work again.

### Steps to reproduce

- Click Reorder on a document type
- Move one property from one tab to a new tab. This should work fine.
- Now try moving a second property. The tab will not change.

### Expected result / actual result

I would expect the moving operation to work every time, not only the first time.

**Comment by kjac** [comment]
@arknu thanks for reporting this 😄 and apologies for the belated response.

This is indeed a bug. I have reproduced it on V10+ ... and submitted a fix here: #13579

**Comment by kjac** [comment]
Fixed in https://github.com/umbraco/Umbraco-CMS/pull/13579
