### ISSUE TITLE
Umbraco 10 installation window shows SQLite as database

### ISSUE THREAD

**Issue by SelwynEdelbroek** [umbraco/Umbraco-CMS#12824]
### Which *exact* Umbraco version are you using? For example: 9.0.1 - don't just write v9

10.1.0

### Bug summary

When deploying an Umbraco v10 website with the connection string already in the appsettings.json the database info shows SQLite. After filling in the user info and pressing the button install the connection string in the appsettings.json will be used and not the SQLite.

After filling in the user creating info and clicking on Install the setup of Umbraco uses the correct connection string and the database is filled with the Umbraco tables. So this is only visual on the installation page of Umbraco.

![2022-08-11 09_52_22-Clipboard](https://user-images.githubusercontent.com/92163864/184092666-ca2019d8-b009-477d-aa23-b7005cf201d8.png)

### Specifics

This issue occurs on my local machine and on the Azure web application.

### Steps to reproduce

- Create new database in SQL Server
- Put connection string inside the appsettings
- Deploy website or start website (we used azure web application)
- Installation window

### Expected result / actual result

Expected result:
The database info shows the settings from the connection string inside the appsettings.json

Actual result:
The database info always shows SQLite

**Comment by kjac** [comment]
Hi @SelwynEdelbroek,

Thank you so much for raising this issue. My apologies for getting back to you so late.

This is indeed a bug, and even if it does not cause any "functional harm" it is still a source of confusion. So - we need this fixed 😄 

I'll bring it back to the team for a quick chat on how to approach this best, then I'll get back to you here soon as possible.

**Comment by bsweb** [comment]
Still doing this in v11

**Comment by anth12** [comment]
Still present on 11.1.0 when deploying to Azure with an empty DB.

**Comment by kjac** [comment]
PR for V10+ in #13809

**Comment by nikolajlauridsen** [comment]
Fixed in https://github.com/umbraco/Umbraco-CMS/pull/13809, Thanks for reporting 😄
