### ISSUE TITLE
unattended install credentials not valid

### ISSUE THREAD

**Issue by EricOropezaelwood** [umbraco/Umbraco-CMS#12827]
### Which *exact* Umbraco version are you using? For example: 9.0.1 - don't just write v9

9.5.0

### Bug summary

Currently trying to use unattended install on a fresh sql database and finding I can't login with the credentials I provide in appsettings.json. The connection to the database appears to be fine, get no errors there. I can even see the user name and e-mail I provide in the database table [dbo].[umbracoUser]. The password shows up as "default" in that entry. When I try and use the e-mail and password I provide it says "login failed for user ..."

### Specifics

`  "ConnectionStrings": {
    "umbracoDbDSN": "<my-connection-string>"
  },
  "Umbraco": {
    "CMS": {
      "Unattended": {
        "InstallUnattended": true,
        "UnattendedUserName": "admin",
        "UnattendedUserEmail": "user@admin.com",
        "UnattendedUserPassword": "admin"
      }
    }
  }`

### Steps to reproduce

I'm running Umbraco locally in a container, pulling in the project

```
FROM mcr.microsoft.com/dotnet/aspnet:5.0-focal AS base
WORKDIR /app
EXPOSE 8081

ENV ASPNETCORE_URLS=http://+:8081

FROM mcr.microsoft.com/dotnet/sdk:5.0-focal AS build
WORKDIR /src
COPY ["umbraco-chl.csproj", "./"]
RUN dotnet restore "umbraco-chl.csproj"
COPY . .
WORKDIR "/src/."
RUN dotnet build "umbraco-chl.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "umbraco-chl.csproj" -c Release -o /app/publish /p:UseAppHost=false

FROM base AS final
WORKDIR /app
RUN apt update && apt install -y vim

COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "umbraco-chl.dll"]

```

Running
`docker build -t umbraco:1.0.0 .`
`docker run --rm -t -d -p 8081:8081 umbraco:1.0.0`

### Expected result / actual result

Expected the credentials I provided in appsettings.json to be my login credentials on the /umbraco login page

**Comment by nul800sebastiaan** [comment]
Your password needs to be at least 10 characters :-) 

![image](https://user-images.githubusercontent.com/304656/184361918-16f8eea1-93cf-4949-957c-810f302f300a.png)

**Comment by EricOropezaelwood** [comment]
Ha yes that was the problem, thanks for that
