### ISSUE TITLE
Member name discarded causing exception Services.MemberService.CreateMemberWithIdentity

### ISSUE THREAD

**Issue by meyntony** [umbraco/Umbraco-CMS#12822]
### Which *exact* Umbraco version are you using? For example: 9.0.1 - don't just write v9

v10.1.0

### Bug summary

```
Services.MemberService.CreateMemberWithIdentity(
						username: "someUsername",
						email: "some@email.com",
						name: "Mandatory name",
						memberTypeAlias: "Member");
```

Even though the name is passed in the above call, it seems to be discarded and an Exception is thrown saying "Cannot save member with empty name"
![image](https://user-images.githubusercontent.com/85172999/184007585-4b92c439-5c36-43ae-b575-dc4351405830.png)
"

### Steps to reproduce

```
Services.MemberService.CreateMemberWithIdentity(
						username: "someUsername",
						email: "some@email.com",
						name: "Mandatory name",
						memberTypeAlias: "Member");
```

The above code snippet should be enough to throw the error described.

### Expected result / actual result

**Expected result:** Member created successfully. 

**Actual result:** Seems like the member is semi created in the database but not visible in the umbraco Backoffice
 Exception is thrown saying "Cannot save member with empty name"

**Comment by kjac** [comment]
@meyntony thank you so much for raising this 👍 and sorry for the late response 😞 

It seems this was fixed in #13020 so I'm going to close this issue now. Please feel free to reopen if the problem still persists.
