### ISSUE TITLE
Outdated gitignore

### ISSUE THREAD

**Issue by jbreuer** [umbraco/Umbraco-CMS#12836]
### Which *exact* Umbraco version are you using? For example: 9.0.1 - don't just write v9

V9 and V10

### Bug summary

Not sure if I should report it here, but I don't know where else I should. 

I started a new repository on Github. There you have an option to select a gitignore file. I selected the Umbraco one, but it seems pretty outdated.

This is what is in the gitignore file:

```
## Ignore Umbraco files/folders generated for each instance
##
## Get latest from https://github.com/github/gitignore/blob/master/Umbraco.gitignore

# Note: VisualStudio gitignore rules may also be relevant

# Umbraco
# Ignore unimportant folders generated by Umbraco
**/App_Data/Logs/
**/App_Data/[Pp]review/
**/App_Data/TEMP/
**/App_Data/NuGetBackup/

# Ignore Umbraco content cache file
**/App_Data/umbraco.config

# Don't ignore Umbraco packages (VisualStudio.gitignore mistakes this for a NuGet packages folder)
# Make sure to include details from VisualStudio.gitignore BEFORE this
!**/App_Data/[Pp]ackages/*
!**/[Uu]mbraco/[Dd]eveloper/[Pp]ackages/*

# ImageProcessor DiskCache
**/App_Data/cache/

# Ignore the Models Builder models out of date flag
**/App_Data/Models/ood.flag

```
The link to `Get latest from` also doesn't work.

### Steps to reproduce

Start a new repository on Github and select the Umbraco gitignore file.

![image](https://user-images.githubusercontent.com/5444597/184604789-6120cd7b-699a-4610-9ea3-9e528069c9e5.png)

Once the repository is created you can see the outdated file.

### Expected result / actual result

It seems there already is an updated version here, but that is not the one which is used when you start a new repository: https://github.com/github/gitignore/blob/main/community/DotNet/Umbraco.gitignore

That one should be used with a working `Get latest from` link.

**Comment by nul800sebastiaan** [comment]
When you use `dotnet new umbraco` you get [our recommended ignore file](https://github.com/umbraco/Umbraco-CMS/blob/v10/contrib/templates/UmbracoProject/.gitignore), I don't really see a need for that centralized one but it's there and it works just fine (apart from missing out on ignoring the temp folder).

I've created a PR to fix the temp folder and the link. https://github.com/github/gitignore/pull/4128

**Comment by jbreuer** [comment]
Ah I just discovered I have 2 gitignore files. Here are the steps I did:

1. Created a repo on Github and added the Umbraco gitignore file.
2. Cloned the repo and in that folder I did `dotnet new umbraco`.

By doing step 2 in the cloned folder it creates another folder in there. So I have the gitignore from Github in the root folder and the correct one in a folder deeper.

Thanks for fix the the temp folder and link the link in https://github.com/github/gitignore/pull/4128, but that version is still not used when you create a new repo on Github.

Version I got from Github:

```
## Ignore Umbraco files/folders generated for each instance
##
## Get latest from https://github.com/github/gitignore/blob/master/Umbraco.gitignore

# Note: VisualStudio gitignore rules may also be relevant

# Umbraco
# Ignore unimportant folders generated by Umbraco
**/App_Data/Logs/
**/App_Data/[Pp]review/
**/App_Data/TEMP/
**/App_Data/NuGetBackup/

# Ignore Umbraco content cache file
**/App_Data/umbraco.config

# Don't ignore Umbraco packages (VisualStudio.gitignore mistakes this for a NuGet packages folder)
# Make sure to include details from VisualStudio.gitignore BEFORE this
!**/App_Data/[Pp]ackages/*
!**/[Uu]mbraco/[Dd]eveloper/[Pp]ackages/*

# ImageProcessor DiskCache
**/App_Data/cache/

# Ignore the Models Builder models out of date flag
**/App_Data/Models/ood.flag
```


Version on the [gitignore repo](https://github.com/github/gitignore/blob/main/community/DotNet/Umbraco.gitignore):

```
## Ignore Umbraco files/folders generated for each instance
##
## Get latest from https://github.com/github/gitignore/blob/main/Umbraco.gitignore

# Note: VisualStudio gitignore rules may also be relevant

# Umbraco
# Ignore unimportant folders generated by Umbraco
**/App_Data/Logs/
**/App_Data/[Pp]review/
**/App_Data/TEMP/
**/App_Data/NuGetBackup/

# Ignore Umbraco content cache file
**/App_Data/umbraco.config

## this [Uu]mbraco/ folder should be created by cmd like `Install-Package UmbracoCms -Version 8.5.3`
## you can find your Umbraco version in your Web.config. (i.e. <add key="Umbraco.Core.ConfigurationStatus" value="8.5.3" />)
## Uncomment this line if you think it fits the way you work on your project.
## **/[Uu]mbraco/

## The [Mm]edia/ folder contains content. Content may vary by environment and should therefore not be added to source control.
## Uncomment this line if you think it fits the way you work on your project.
## **/[Mm]edia/ 

# Don't ignore Umbraco packages (VisualStudio.gitignore mistakes this for a NuGet packages folder)
# Make sure to include details from VisualStudio.gitignore BEFORE this
!**/App_Data/[Pp]ackages/*
!**/[Uu]mbraco/[Dd]eveloper/[Pp]ackages/*
!**/[Uu]mbraco/[Vv]iews/[Pp]ackages/*

# ImageProcessor DiskCache
**/App_Data/cache/

# Ignore the Models Builder models out of date flag
**/ood.flag

# NEW for version 9 .Net 5 (Core)
#ignore umbraco backoffice assest from wwwroot
**/wwwroot/umbraco/

# SQLite files
*.sqlite.db*

#ignore umbraco data/views/settings
**/umbraco/

#include default location for modelsbuilder output
!**/umbraco/models

#include default location for packages
!**/umbraco/Data/packages
```
