### ISSUE TITLE
Clicking nodes doesn't update view

### ISSUE THREAD

**Issue by patrickdemooij9** [umbraco/Umbraco-CMS#12841]
### Which *exact* Umbraco version are you using? For example: 9.0.1 - don't just write v9

Latest v10/contrib branch

### Bug summary

Not quite sure if this is known already, but when clicking on the various nodes, it doesn't update the view. It does update the URL, just not the view
![Bug](https://user-images.githubusercontent.com/11466511/184694070-4bb15bd5-d098-4c22-9ba2-1be8e3edfb31.gif)
.

### Steps to reproduce

Make new project on latest contrib version.

### Expected result / actual result

Make navigation work as on previous versions

**Comment by bjarnef** [comment]
@patrickdemooij9 yes, it was affected by changes in this PR https://github.com/umbraco/Umbraco-CMS/pull/12730 (see my comments), but it doesn't seem anybody else has noticed it 😲🙈

**Comment by mikecp** [comment]
Indeed... @bjarnef has suggested some changes on the PR itself, so we'll either wait for the fix or we will revert it before releasing 10.2.

**Comment by kjac** [comment]
Indeed this seems to have been resolved along the way. Thank you all the same for reporting it @patrickdemooij9 👍
