### ISSUE TITLE
Datepicker with offset time enabled, behaves odd

### ISSUE THREAD

**Issue by soreng** [umbraco/Umbraco-CMS#12844]
### Which *exact* Umbraco version are you using? For example: 9.0.1 - don't just write v9

 8.18.3

### Bug summary

When using a datepicker with offset time enabled, it can be a bit hard to understand what is actually stored.

We have a picker that is used to set a date and time of when to show a message. On dev (local machine) it works as expected since the browser and server (running on same machine) is in the same offset from utc, the date stored and displayed is the same.

When deploying to azure, the site then runs on in UTC, and the offset is (currently) 120 minutes. 

The offset then defines that the date+time i work with, is offset 120 minutes when applying the value. This seems to not be handled well, and renders me with the following issue:
![image](https://user-images.githubusercontent.com/359492/184728516-8e03dcda-165c-41e3-af2e-6ebadbb311ea.png)
_The hours differ_

When the editor then picks 15:00, the offset is applied when a change is made. This means that 13:00 is stored.

When picking a new time, 13:00 will now be shown. Someting in the back/forth is off.

### Steps to reproduce

Setup a site, with a doc type using a datepicker setup with "time offset".

Run the site on a server that is on a different timezone than the browser, and pick a specifik time, and see that it is may be offset in the picker as seen in the picture.

### Expected result / actual result

The picker should be transparent that the date+time is offset when setting / getting the value.

**Comment by mikecp** [comment]
Closed as per merge of PR 12847
