### ISSUE TITLE
Make .Siblings() & .Children() not nullable

### ISSUE THREAD

**Issue by patrickdemooij9** [umbraco/Umbraco-CMS#12842]
### Which *exact* Umbraco version are you using? For example: 9.0.1 - don't just write v9

v10

### Bug summary

Currently .Siblings() and .Children() both have the possibility to return a NULL value instead of an IPublishedContent[].

I think it would be easier for programmers if it would return an Array.Empty<IPublishedContent>() instead of NULL, because I think that in most scenarios the NULL doesn't actually happen.

I tried taking a look at it, but I am not sure where to actually do this change or if there is a reason to return NULL there.

### Steps to reproduce

Use the `.Siblings(); ` method and see that it can return a NULL value

**Comment by DanDiplo** [comment]
I did start a PR for this, though was told it would be for v11. But I totally agree - nullable references haven't always been thought through in many methods.

https://github.com/umbraco/Umbraco-CMS/issues/12692

**Comment by kjac** [comment]
Hi @patrickdemooij9,

Thank you for reaching out. We certainly do appreciate feedback on the developer experience ❤️ 

This and more similar cases have been fixed for V11 in #12703 so I'm going to close this issue now 😄
