### ISSUE TITLE
Rename and Convert to tab not working when Group is called 'Generic properties' 

### ISSUE THREAD

**Issue by wvankesteren-ax** [umbraco/Umbraco-CMS#12857]
### Which *exact* Umbraco version are you using? For example: 9.0.1 - don't just write v9

8.18.4

### Bug summary

Get an error on saving any doctype: "Validation: The Alias field is required." even when no changes are made on that document.
Please note that the document types are converted from 7.15.3.

see:

- https://our.umbraco.com/forum/using-umbraco-and-getting-started/107470-can-no-longer-create-or-save-a-doctype-after-upgrade-to-v817-from-816
- https://github.com/umbraco/Umbraco-CMS/issues/11202

I've got the same (and more) issue in 8.18.4 when the section is named 'Generic properties'.

Trying to avoid the error message, I tried suggestions from the above forum article, but new problems arise.

### Specifics

Trying to avoid the error message, I tried suggestions from the above forum article, but new problems arise.

- The **Convert to tab** action is completed successfully, the newly created tab can be renamed (if you want to) and the document type can be saved, but after reopening the document type the action seems not saved (no longer a tab, but still a section.
- That section can't also be renamed: it will delete that section completely, but also all sections above it!

It doesn't matter whether the actions are performed on a child document type (hence, inherited section)  or the original document type!

![image](https://user-images.githubusercontent.com/93970302/185339966-463d652e-8cbb-41df-8801-d6d49f928250.png)

### Steps to reproduce

- The **Convert to tab** action is completed successfully, the newly created tab can be renamed (if you want to) and the document type can be saved, but after reopening the document type the action seems not saved.
- That section can't also be renamed: it will delete that section completely, but also all sections above it!

### Expected result / actual result

- Fix the error message, so be able to save the Document Type
- Remember the _Convert to tab_ action in case the section is named 'Generic properties'.
- Avoid deleting the section and all sections above it when trying to rename the section.

**Comment by kjac** [comment]
Hi @wvankesteren-ax,

Thank you for reporting this, and sorry for the belated response.

I can't reproduce this in V10+, so somewhere along the line this must have been fixed - perhaps as part of #11202 

We no longer back-port fixes to V8 unless they concern critical security issues, so I'm afraid I have to close this issue.

I hope you managed to resolve the issue already on your end.

**Comment by wvankesteren-ax** [comment]
Hi,

I'm very sorry to hear that this issue is closed, because we have a lot of customers that still needs upgrading to v8 and not ready to go directly to 10 (e.g. due to large code migration issues)
