### ISSUE TITLE
"Save and preview" bug for pages with and without content in different languages 

### ISSUE THREAD

**Issue by jloAwave** [umbraco/Umbraco-CMS#12884]
### Which *exact* Umbraco version are you using? For example: 9.0.1 - don't just write v9

9.3.0

### Bug summary

Save and Preview doesn't work in certain cases in that it's unable to load the correct culture (language).
Note that the attached video is from Umbraco 9.3.0 but the bug can be reproduced on Umbraco 8, 9 and 10.

### Specifics

https://user-images.githubusercontent.com/111577135/186182702-a4ae5f62-c6ec-4cde-91c2-59525abf9c33.mp4

https://umbraco9demo.a-demo.net/umbraco#/content/content/edit/1106?mculture=en-US

### Steps to reproduce

See the attached recording. You need at least two languages to be available to reproduce the issue. Make sure you have a page with some content in a language and no content in another language, in the recording, it's "test English version" under Root > Home.

1. On the language where you have content for the page, click "Save and preview" and see that the culture is correct in the URL
2. Switch to another language where you have no content for that page, click "Save and preview", see that there's no culture in the URL (but there's no content to preview here anyway)
3. Switch back to the original language with content and click "Save and preview" and see that the culture is missing from the URL, i.e. the preview fails to load

### Expected result / actual result

Expected result: the preview is loaded in and works regardless of switching between languages on pages with or without content

Actual result: if you switch between languages, the preview fails unless you refresh the page before trying to access the preview (see the video)

---
_This item has been added to our backlog [AB#24043](https://dev.azure.com/umbraco/243e7927-03b2-44e2-908f-d4ac7ea5daaa/_workitems/edit/24043)_

**Comment by Zeegaan** [comment]
Hey @jloAwave Thanks for reporting this! 
This is now fixed in https://github.com/umbraco/Umbraco-CMS/pull/13455
