### ISSUE TITLE
Package migration state is not correctly displayed/updated in the backoffice

### ISSUE THREAD

**Issue by sergiutesu** [umbraco/Umbraco-CMS#12883]
### Which *exact* Umbraco version are you using? For example: 9.0.1 - don't just write v9

10.1.0

### Bug summary

After running the package migration successfully, the button still shows as there are pending changes.

More about the Package Migration Settings here:
https://our.umbraco.com/documentation/Reference/Configuration/PackageMigrationSettings/

### Specifics

The default for `PackageMigrationsUnattended` is true and I don't have any other setting in my project to change it.

The setting doesn't have a default value in the schema: it's missing the `DefaultValue` attribute on the property: https://github.com/umbraco/Umbraco-CMS/blob/e626fca2432582f052cb13654eedd9e60ef8723f/src/Umbraco.Core/Configuration/Models/UnattendedSettings.cs#L38-L44

### Steps to reproduce

1. Install a completely new Umbraco v10.1.0 locally & spin it up
2. Install Forms (I used NuGet package manager for that)
3. Go to the packages section and click on "Run pending package migration"
![image](https://user-images.githubusercontent.com/83580347/186156116-75455444-6e34-48dd-8f81-ab03c3b2054c.png)

It will say it is successful.
![image](https://user-images.githubusercontent.com/83580347/186156224-a6335f69-f1a5-4db8-9978-b291a5b05b1f.png)

Going back to the packages section the button will still show as pending.
![image](https://user-images.githubusercontent.com/83580347/186156293-8413c5d8-59dc-41e6-8678-209fd2564bc9.png)

### Expected result / actual result

The button should be disabled or not there since there is nothing pending.

---
_This item has been added to our backlog [AB#24992](https://dev.azure.com/umbraco/243e7927-03b2-44e2-908f-d4ac7ea5daaa/_workitems/edit/24992)_

**Comment by PriceyCoder** [comment]
I have also had this issue since at least v10.0.1. 
It is still happening with Umbraco v10.2 and UmbracoForms 10.1.2
It occurred with both UmbracoForms and uSync.

**Comment by joshuacrittendenNFP** [comment]
I also see this for the packages I have installed, even in 10.3.2.

![image](https://user-images.githubusercontent.com/108086799/199249976-20f1babb-d155-4c46-b008-85c6411d5f4f.png)

**Comment by nikolajlauridsen** [comment]
Fixed in #13574, thanks for reporting 😄
