### ISSUE TITLE
Numeric input does not honour max value

### ISSUE THREAD

**Issue by octoro-software** [umbraco/Umbraco-CMS#12897]
### Which *exact* Umbraco version are you using? For example: 9.0.1 - don't just write v9

Heartcore V10

### Bug summary

When creating a numeric input data type and setting a min value of 0 and max of 12. The content editor still allows a value greater than 12 to be entered but when using the input accessibility arrows its limited to 12

### Steps to reproduce

Create numeric data type define a min and max value.

Use it in the content editor and observe the summary above

### Expected result / actual result

The value should never be greater than the max value defined in the data type configuration

**Comment by bjarnef** [comment]
I think this is default behavior in browsers, which mostly don't enforce a value typed to between min and max: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/number

Some browers display spinner, but not all, e.g. Chrome on Android.

However it should be possible in Angular to sjoe client validation based on min and max (if it isn't already added).

Most modern browsers support input type number, but actually number inputmode is often preferable nowadays unless you want the spinners, but could be archived with buttons and a bit javascript.

The input number have some benefits, but isn't really consistent between browsers and devices. Especially on Android and iOS devices combined with pattern attribute depending on the virtual keypad you want.

**Comment by octoro-software** [comment]
Umbraco should still handle this regardless of browser no ? Otherwise why bother with the min and max in the first place. Just to re iterate the problem is not with my app its Umbraco heartcore content editor

**Comment by bjarnef** [comment]
It doesn't have client side validation, but the value isn't saved if not within min and max value.

**Comment by octoro-software** [comment]
Ill switch to a drop down.
