### ISSUE TITLE
Umbraco Media files with æøå - UmbracoMediaPhysicalRootPath

### ISSUE THREAD

**Issue by thomashdk** [umbraco/Umbraco-CMS#12903]
### Which *exact* Umbraco version are you using? For example: 9.0.1 - don't just write v9

9.5.3

### Bug summary

Storing images outside wwwroot folder with `UmbracoMediaPhysicalRootPath` set in appsettings can't for some reason not handle files with special characters. Files with out special characters works fine.

ex. 
```json
"Umbraco": {
    "CMS": {
      "Global": {
        "UmbracoMediaPhysicalRootPath": "./../../TestMedia/media"
      }
    }
  }
```

### Specifics

I have check in clean Umbraco 9.5.3 installation and also our projects updated from 8.15.3.

### Steps to reproduce

- install a Umbraco 8.15.3
- Upload a file / image with special character ex. æøå.
- install a Umbraco 9.5.3
- Point the 9.5.3 project to the 8.15.3 database and update
- In the 9.5.3 project add `UmbracoMediaPhysicalRootPath`: `./../../TestMedia/media` to the appsettings
- copy media from the 8.15.3 to the TestMedia/media in the 9.5.3 project.
- Try load the image for media library
- Should give a 404 error

### Expected result / actual result

That images stored outside the wwwroot folder would not give a 404 error.

**Comment by kjac** [comment]
Hi @thomashdk - thank you for your detailed issue report 👏 

I have been digging a bit into this in order to reproduce, and just to clarify: 

1. If you upload an image in Umbraco 9.5.3 with å, ä og ö in the file name, does that also break the image cropper for you? Or is it "only" media from 8.x that are causing issues?
2. Does it work as expected if you serve the affected media from the default folder, i.e. not using `UmbracoMediaPhysicalRootPath`?
3. Is your site hosted on a Windows machine?

**Comment by thomashdk** [comment]
Hi @kjac 

1. It's from 8.15.3. If you upload image, it keeps the æ,ø,å in the file path. And then update to 9.5.3.

2. Works fine with default folder, but not with UmbracoMediaPhysicalRootPath

3. Yes

I have uploaded a project here with a media upload. There is a folder called TestMedia outside the project where the media also are.

user: admin@admin.dk
pass: 1234567890

https://drive.google.com/drive/folders/1KwHCgcu6IV6XHbOLZ7l-vShl96n6hPsh?usp=sharing

**Comment by kjac** [comment]
@thomashdk thank you. I can reproduce it on V10 too. I will make sure to investigate.

If you need a quick fix for now, you *may* be able to solve it by renaming the affected physical files on disk (copy the files and rename the copy as to retain the original). At least in V10 I can serve your file "struer-havn-anders-trærup-1024x683.jpg" by renaming it to "struer-havn-anders-tr%C3%A6rup-1024x683.jpg".

**Comment by Zeegaan** [comment]
Fixed in https://github.com/umbraco/Umbraco-CMS/pull/12936 🎉
