### ISSUE TITLE
UmbracoHelper.GetDictionaryValue defaults to en-US when used in non-front end code

### ISSUE THREAD

**Issue by philipdanielhayton** [umbraco/Umbraco-CMS#12904]
### Which *exact* Umbraco version are you using? For example: 9.0.1 - don't just write v9

10.1.0

### Bug summary

Calling `umbracoHelper.GetDictionaryValue('')` is always returning results from the en-US culture, even though that culture doesn't exist in my language settings. In my particular use case it manifests itself by returning empty strings. 

I am accessing umbracoHelper using `IUmbracoHelperAccessor` inside a service that is triggered by administrators in the Umbraco back end (specifically, sending emails using Vendr). This particular service is registered as a transient, but the issue also occurs if registerd as a singleton.

I have tried changing the default culture on the thread but that doesn't seem to do anything. 

It may be possible that I'm missing something obvious, however it also raises a potention enhancement - should there be an overload method that lets you pass in a specific culture, such as:

`umbracoHelper.GetDictionaryValue("MyKeyName", "en-GB")` ?

In any case I am exploring accessing the `ILocalizationService` as a work around, but this just feels like a bug.

### Steps to reproduce

Create a transient or singleton service and try accessing dictionary values other than en-US.

### Expected result / actual result

For example when:
- en-GB is the default language for the site
- The dictionary key "Greeting" has a value of "Hey there"

I would expect calling `umbracoHelper.GetDictionaryValue("Greeting")` to return "Hey there", but it actually returns an empty string.

**Comment by uppercuut** [comment]
i will check it

**Comment by uppercuut** [comment]
fixed at #12942
