### ISSUE TITLE
NUnit returns value cannot be null when running tests

### ISSUE THREAD

**Issue by RyuLindow** [umbraco/Umbraco-CMS#12911]
### Which *exact* Umbraco version are you using? For example: 9.0.1 - don't just write v9

10.1.0

### Bug summary

In short, inheriting from the `UmbracoIntegrationTest` will result in the following error when you try to run the test

```
Message: 
System.ArgumentNullException : Value cannot be null. (Parameter 'config')
TearDown : System.NullReferenceException : Object reference not set to an instance of an object.

Stack Trace: 
ChainedBuilderExtensions.AddConfiguration(IConfigurationBuilder configurationBuilder, IConfiguration config, Boolean shouldDisposeConfiguration)
ChainedBuilderExtensions.AddConfiguration(IConfigurationBuilder configurationBuilder, IConfiguration config)
UmbracoIntegrationTest.<CreateHostBuilder>b__27_0(HostBuilderContext context, IConfigurationBuilder configBuilder)
HostBuilder.BuildAppConfiguration()
HostBuilder.Build()
UmbracoHostBuilderDecorator.Build()
UmbracoIntegrationTest.Setup()
--TearDown
UmbracoIntegrationTest.TearDownAsync()
```

Following code works
```
using NUnit.Framework;
using Umbraco.Cms.Tests.Integration.Testing;

namespace intTest
{
    public class Tests 
    {
        [SetUp]
        public void Setup()
        {
        }

        [Test]
        public void Test1()
        {
            Assert.Pass();
        }
    }
}
```

Following code does not:

```
using NUnit.Framework;
using Umbraco.Cms.Tests.Integration.Testing;

namespace intTest
{
    public class Tests : UmbracoIntegrationTest
    {
        [SetUp]
        public void MySetup()
        {
        }

        [Test]
        public void Test1()
        {
            Assert.Pass();
        }
    }
}
```

### Steps to reproduce

https://user-images.githubusercontent.com/56826332/186732921-8790bc82-7985-4e04-a87c-81751f2fb614.mp4

1. Created a solution based on this template
![image](https://user-images.githubusercontent.com/56826332/186733729-8b7d6a8e-4151-433f-8bef-383cf469bc7f.png)
2. Installed https://www.nuget.org/packages/Umbraco.Cms.Tests.Integration/10.1.0?_src=template
3. Added the code mentioned above

I've also tried to use the same code on a Umbraco project after having installed https://www.nuget.org/packages/Umbraco.Cms.Tests.Integration/10.1.0?_src=template but then none of my tests run. Only build.
![image](https://user-images.githubusercontent.com/56826332/186734179-0866673a-972e-4767-97c8-4dbeb9040927.png)

Same result when I followed the documentation - https://our.umbraco.com/documentation/Implementation/Integration-Testing/#testing-with-a-schema and later also the video - https://www.youtube.com/watch?v=02mxZRIX2es

Based on when the docs were updated and the video it might be that this was never tested on v10.

---
_This item has been added to our backlog [AB#22125](https://dev.azure.com/umbraco/243e7927-03b2-44e2-908f-d4ac7ea5daaa/_workitems/edit/22125)_

**Comment by Zeegaan** [comment]
Fixed in https://github.com/umbraco/Umbraco-CMS/pull/12928
