### ISSUE TITLE
Media Picker creates duplicated folders 

### ISSUE THREAD

**Issue by davit20** [umbraco/Umbraco-CMS#12918]
### Which *exact* Umbraco version are you using? For example: 9.0.1 - don't just write v9

10.0.1

### Bug summary

When you create folder with media picker it creates duplicated folders

### Steps to reproduce

If you have Media picker on the page please create Folder from media picker.

### Expected result / actual result

There must be one folder instead two or three 
When you create folder from media picker with name "testFolder"  it creates three folders "testFolder" , "testFolder(1)" "testFolder(2)".

**Comment by gtd92** [comment]
> ### Which _exact_ Umbraco version are you using? For example: 9.0.1 - don't just write v9
> 10.0.1
> 
> ### Bug summary
> When you create folder with media picker it creates duplicated folders
> 
> ### Specifics
> _No response_
> 
> ### Steps to reproduce
> If you have Media picker on the page please create Folder from media picker.
> 
> ### Expected result / actual result
> There must be one folder instead two or three When you create folder from media picker with name "testFolder" it creates three folders "testFolder" , "testFolder(1)" "testFolder(2)".

This seems to be happening when multiple events are triggered("Enter" pressed or input is blurred) while the first one is still being processed. Umbraco sends parallel HTTP requests with each trigger.

**Comment by nul800sebastiaan** [comment]
I'm not sure what's wrong there but it maybe it's something that's specific to the project you're working on. As you can see below it creates a single folder for me. 

> This seems to be happening when multiple events are triggered("Enter" pressed or input is blurred) while the first one is still being processed. Umbraco sends parallel HTTP requests with each trigger.

How do I trigger this behavior? I can't press enter / click fast enough 😅 

https://user-images.githubusercontent.com/304656/187194428-51907ce4-6a68-4d0e-9416-e20ff17772e3.mp4

**Comment by gtd92** [comment]
> I'm not sure what's wrong there but it maybe it's something that's specific to the project you're working on. As you can see below it creates a single folder for me.
> 
> > This seems to be happening when multiple events are triggered("Enter" pressed or input is blurred) while the first one is still being processed. Umbraco sends parallel HTTP requests with each trigger.
> 
> How do I trigger this behavior? I can't press enter / click fast enough 😅
> 

It could be project specific - the create folder(`/PostAddFolder`) endpoint seems very slow(it takes several seconds to respond). But It does cause this issue. It might not appear on a clean umbraco instance, but I doubt that we are the only ones having this issue.

**Comment by gtd92** [comment]
https://user-images.githubusercontent.com/111847083/187375560-276fc3c7-a65f-473f-9163-3154ef7abafb.mp4

**Comment by nul800sebastiaan** [comment]
Yeah, I've been able to reproduce it now by simulating a slow network connection, after typing the name of the folder and tapping Enter a few times I am able to reproduce.

I guess we should stop accepting any more Enters and not respond to a click after the initial enter / click has happened. 

We'd love a little help getting this fixed! 👍

**Comment by nul800sebastiaan** [comment]
![image](https://user-images.githubusercontent.com/304656/187384578-22583398-dcc0-4476-be41-f05458e27a7c.png)

**Comment by MayurDeore** [comment]
Is anyone working on this?

**Comment by nul800sebastiaan** [comment]
@MayurDeore It was put up for grabs an hour ago, so I doubt someone is working on it yet 😅

**Comment by MayurDeore** [comment]
@nul800sebastiaan I did ask to make sure. So I'm going to start working on this issue.

**Comment by uppercuut** [comment]
anyone is on it yet ?

**Comment by matthewcare** [comment]
Hi @nul800sebastiaan 
I've actually been looking at working on an issue very similar to this for the past few weeks.
It's been a frustration to me that when you upload media, it processes one at a time, so I made some changes to the dropzone to a "bulk upload" kind of thing.
Without implementing a queuing strategy there are many race condidions that occur.
Firstly, you get the issue of duplicate folders (as this issue describes), but also if you send enough requests all at once, it actually causes SQL exceptions (using SQLite at least), and causes the entire site to hang and you have restart the application.

I'd imagine this would also be present if you had enough editors uploading files concurrently, though I haven't tested that.

Although the open PR fixes things from a front end perspective, something definitely need to be put in place in the back end to resolve the race conditions that occur.
