### ISSUE TITLE
Groups cannot be updated on members after they are created

### ISSUE THREAD

**Issue by RichezA** [umbraco/Umbraco-CMS#12938]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

10.2.0-rc

### Bug summary

After creating a member, groups cannot be changed.
You cannot delete one if you had previously assigned one while creating the member.
You cannot add another after you created him.

### Specifics

https://localhost:44301/umbraco#/member/member/edit/XXXXX?page=1&listName=Member

I have checked and no logs have been produced from the save.

### Steps to reproduce

1. Create a member group.
2. Create a member, and assign a group before creating it.
3. Try to remove the group after it has been created.

Alternative:
1. Create a member group.
2. Create a member without assigning a group to it.
3. Try to add the group after it has been created.

Demo (GIF)
![Umbraco-Bug-RC](https://user-images.githubusercontent.com/32996730/188100508-bd28785f-1663-4b51-9494-1108493d2d3d.gif)

### Expected result / actual result

The group should be added / removed as we like after the member has been created.

---
_This item has been added to our backlog [AB#22277](https://dev.azure.com/umbraco/243e7927-03b2-44e2-908f-d4ac7ea5daaa/_workitems/edit/22277)_

**Comment by nul800sebastiaan** [comment]
Thanks @RichezA - that's a new problem in 10.2.0 so we'll have to fix that before we release 10.2.0 final, thanks for testing! 👍

**Comment by nul800sebastiaan** [comment]
Turns out we found this in our testing as well and this was fixed in https://github.com/umbraco/Umbraco-CMS/pull/12905 

Thanks again for reporting, always good to know people are actually testing! 🎉

**Comment by RichezA** [comment]
You're welcome, always a pleasure if we can help !
