### ISSUE TITLE
High amounts of nested content nodes increases load time significantly when switching language.

### ISSUE THREAD

**Issue by jesperlange** [umbraco/Umbraco-CMS#12959]
### Issue description
High amounts of nested content nodes increases load time significantly when switching language.
Reproduced on a fresh v8 - having 120+ nested content nodes in a single content node leaves the secondary language with a +4-5 minute loading screen, while the default language loads fine.

Tested on following versions:
Umbraco 8.11.1 / Forms 8.11.0 / Deploy 4.5.0.0

Umbraco 8.18.4 / Forms 8.12.2 / Deploy 4.6.1.0

**The setup:**
Have 2 languages.
add around +100 nested content nodes in 1 content node (navigating to the default language of this node doesn't have a long load time)
Something along these lines
![image](https://user-images.githubusercontent.com/54025229/180433639-b3de63c2-e0f9-475a-9d75-0c00873741b5.png)
![image](https://user-images.githubusercontent.com/54025229/180435209-3619a7f5-494c-4335-aa6e-a575f5ded948.png)

And the doc type with nested content
![image](https://user-images.githubusercontent.com/54025229/180435540-75d4e24d-8420-4fbc-813d-df0f83986f4b.png)

Then switch the language, in my instance swedish - and the project is stuck loading for 4-5 minutes, after that it works fine. (have been tested waiting for 15-20 minutes as well)
![image](https://user-images.githubusercontent.com/54025229/180434414-4287d3ac-b446-48d7-a766-7cdba62b0894.png)

There is nothing in the network/console tab that would suggest why it loads for so long.

**Exact steps:**
- Create 2. language.
- Create 2 doc types, one root and one for the content that contains the nested content property
- Create 1 element type with culture varient as shown in the pictures above.
- I added 200 nested content nodes where approx. 120 of them contained nested content.
- Loads fine when just navigating to default language
- Switch to 2. langauage, now you are stuck loading.

What has been done to try and fix it
I noticed DependencyHandler errors, so I've tried to bump the clientdependency, did nothing.
I have rebuilt the external and internal indexes - which seems to have improved loading time, but still very long
The memory and database cache has been reloaded.

**As it is a bit time-consuming to reproduce, I have the project I reproduced it on myself, I can invite you to that project if needed**

**Comment by kjac** [comment]
Hi @jesperlange,

Try as I might I can't reproduce this at all 😞 

I've tried on 8.18 and 10.3.2 to no avail. I've tried a number of combinations of culture variant and non-variant elements. No luck; the UI works fine with 200 items in Nested Content across multiple languages.

Here's the element type I'm testing with:

**Comment by nikolajlauridsen** [comment]
Heya, I'll have to go ahead and close down this issue, since we can't reproduce it and haven't heard back in 14 days, please feel free to let us know if you have additional information and then we can open up the issue again.
