### ISSUE TITLE
Cannot Save a Template in Umbraco cms with certain codes.

### ISSUE THREAD

**Issue by angelogithub1** [umbraco/Umbraco-CMS#12970]
Cannot save a Template in umbraco 8.12 with a certain block of codes.

category/umbraco-cms.

https://user-images.githubusercontent.com/113172584/189312096-f53142fc-602a-48eb-b508-7c4101ac4ff0.mp4

**Comment by nul800sebastiaan** [comment]
This sounds like an excellent question for the forums where our friendly community can help you find the best solution for your requirements. 

Make sure to head on over to https://our.umbraco.com and ask follow up questions there.
