### ISSUE TITLE
Backoffice JS errors after upgrade to 10.2.0

### ISSUE THREAD

**Issue by bjarnef** [umbraco/Umbraco-CMS#12978]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

10.2.0

### Bug summary

After upgrade Umbraco from v10.1.1 to v10.2.0 on Umbraco Cloud I get JS error in backoffice and no properties are loaded in content app.

![image](https://user-images.githubusercontent.com/2919859/189481307-ff89624e-3b50-45d5-98c1-054df1e5fb69.png)

It seems `allowedActions` is undefined related to changes in this PR: https://github.com/umbraco/Umbraco-CMS/pull/12605

### Steps to reproduce

Upgrade to from v10.1.1 to v10.2.0

**Comment by bjarnef** [comment]
It seems restarting the Development environment fixed this, but for some reason it was throwing these JS errors after upgrade of development environment.

**Comment by elit0451** [comment]
Hey @bjarnef 👋 
Can we close this?

I've seen in your comment (https://github.com/umbraco/Umbraco-CMS/issues/13039#issuecomment-1253373697) that you managed to resolve the problem after a recycle and we are now on 10.3.2, so it's been a few versions in between since 10.2 🙂

**Comment by bjarnef** [comment]
Hi @elit0451 

Yeah, I guess it was some caching of the static assets or the recycle re-bundled the JS-assets 😁
