### ISSUE TITLE
Following update to 10.2 the <umb-overlay> directive no longer functions correctly.

### ISSUE THREAD

**Issue by AndyButland** [umbraco/Umbraco-CMS#12989]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

10.2

### Bug summary

It appears that something has changed in 10.2 that breaks the usage of the `<umb-overlay>` directive.  Specifically this has been found in Umbraco Forms, and details can be seen on [this issue](https://github.com/umbraco/Umbraco.Forms.Issues/issues/867).

There are no console errors - the overlay seems to load correctly and via DOM manipulation you can confirm that it's there, but it's not visible.  I suspected a CSS change but couldn't identify what was different to cause the issue.

`<umb-overlay>` is legacy, so we'll likely fix the issue for Forms by updating to use the `editorService`.  Having tested that, it doesn't seem to be affected and works as expected.

So the concern is really any other packages or solutions that might be relying on `<umb-overlay>` and run into the same problem.

### Steps to reproduce

Install CMS 10.2 and Forms 10.1
Create a document type containing a form picker
Attempt to select a form on a content item using the picker

---
_This item has been added to our backlog [AB#22591](https://dev.azure.com/umbraco/243e7927-03b2-44e2-908f-d4ac7ea5daaa/_workitems/edit/22591)_

**Comment by bjarnef** [comment]
@AndyButland @iOvergaard it is because of this addition in 10.2

![image](https://user-images.githubusercontent.com/2919859/189977725-6ab7b52d-6f97-4065-9912-3ddc1d816689.png)
