### ISSUE TITLE
Tree is empty after upgrading to v10.2, until restart

### ISSUE THREAD

**Issue by callumbwhyte** [umbraco/Umbraco-CMS#12997]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

v10.2

### Bug summary

When upgrading from Umbraco v10.0.1 to v10.2.0, the installer screen shows and runs through the process but after redirecting to the backoffice the tree is empty.

### Steps to reproduce

Update Umbraco via NuGet, in our case from v10.0.1 to v10.2.

Launch the application, you are presented with the authorize upgrade screen.

The upgrade completes successfully and redirects to the backoffice. No nodes are visible in the tree.

Refreshing the backoffice / clearing cache does not fix the issue.

Restarting the application resolves the issue.

https://user-images.githubusercontent.com/16511093/190151890-92b4b215-08e5-4486-9626-3c56c471cc3e.mov

**Comment by nul800sebastiaan** [comment]
Hmmm my install is fine, but I did need to login again after the upgrade, not sure why that was skipped on yours.. Customizations in `Program.cs` maybe getting in the way? 

https://user-images.githubusercontent.com/304656/190171784-72a67499-54c5-4d89-aeb8-367fc7f72070.mp4

**Comment by nul800sebastiaan** [comment]
Maybe this was once upgraded from v9 to v10 and `Startup.cs` wasn't updated (shouldn't be necessary but.. maybe). https://our.umbraco.com/documentation/Fundamentals/Setup/Upgrading/version-specific#version-9-to-version-10

**Comment by nul800sebastiaan** [comment]
No `app.UseHttpsRedirection()` for me and indeed, would be weird if that was the issue. I can try with the added headers, but not sure that would affect anything either. Interesting that I get logged out after upgrading and you don't.

**Comment by matthewcare** [comment]
@nul800sebastiaan 
I had this issue today when upgrading a site from 10.0.0 to 10.2.0.
In my case, I deleted the `Umbraco` folder and restarted the site and it all came back.

It's worth noting that it's only the `Content` tree that is missing items. The `Translation`  and `Settings` trees still work as expected.

**Comment by nul800sebastiaan** [comment]
@matthewcare From Callum's descriptions it seems like all you needed was a restart, no need to delete the Umbraco folder (not sure what you thought that would help with. just getting rid of the TEMP data?).

**Comment by matthewcare** [comment]
@nul800sebastiaan Yeah, since it was an issue with missing content only inside the CMS I thought maybe it was an issue with the internal index. Deleting the Umbraco (therefore TEMP) direcetory would have removed all index and NuCache so it would regenerate on next start up

**Comment by royberris** [comment]
Hi, I also noticed this bug after upgrade. Issue might be authorization, without restarting, but after logging out and logging in everything shows as expected. Maybe something went wrong with the log-in section from the installer?

**Comment by kjac** [comment]
I have been trying to reproduce this a few times now... and I can't. At least not locally.

In my tests I upgrade a 10.0.1 to 10.2.0
- The upgrade runs locally
- The site uses SQLite

I am not prompted to login after upgrade, and the content is readily available.

![12997](https://user-images.githubusercontent.com/7405322/207270238-5426f558-1583-4a4c-8241-47f32c28041b.gif)

Does anyone have anymore info to go on?

**Comment by nikolajlauridsen** [comment]
Hey all, I'll have to go ahead and close down this issue, since we can't reproduce it and haven't heard back in 14 days, please feel free to let us know if you have additional information and then we can open up the issue again.
