### ISSUE TITLE
Grid property editors not loading after Umbraco 10.2.0 update

### ISSUE THREAD

**Issue by RGV2ZWxvcGVy** [umbraco/Umbraco-CMS#12994]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

10.2.0.67

### Bug summary

After updating Umbraco from version 10.1.1 to version 10.2.0 I encountered an issue with some of the Grid editors.
In particular editors that use the Doc Type Grid Editor are not loading correctly anymore. I know this package has been marked as retired, but in Umbraco 10.1.1 it is still working properly.

### Specifics

I am using Umbraco Cloud version 10.2.0.67, and when creating a new page, there are now 2 buttons that lets you add content (in the previous version there was only one). When I choose a Grid component that uses the Doc Type Grid Editor to add content, a AngularJS error shows up in the console, and my property editors won't load.

This is the exact error message:
`TypeError: Cannot read properties of undefined (reading 'variants')
    at $scope.propertyEditorDisabled (umbraco.directives.min.js?d=637987433650000000:1:112602)
    at fn (eval at compile (angular.js:16548:15), <anonymous>:4:301)
    at angular.js:11489:57
    at r (angular.js:396:9)
    at Da (angular.js:11396:7)
    at p (angular.js:10613:30)
    at g (angular.js:9942:13)
    at angular.js:9807:30
    at angular.js:10221:16
    at d (angular.js:9985:16) '<div class="controls" ng-transclude="">'`

I guess it has to do with this [issue](https://github.com/umbraco/Umbraco-CMS/issues/12989). Umbraco Forms had a patch releases yesterday. But I guess Doc Type Grid Editor won't release a patch for this as it is deprecated. Maybe someone has a quick workaround for this?

### Steps to reproduce

1. Install Our.Umbraco.DocTypeGridEditor v10.0.0 from NuGet, and build your project (make sure your running version 10.2.0 of Umbraco).
2. Create a Document Type in the backoffice, so you can create a root node/page (make sure this Document Type has a property with the 'Grid layout' data type so you can use the Grid).
3. Create another Document Type as Element Type with some properties (data type doesn't matter).
4. Create a (root)page in the Content section, choose 'Headline' or 'Article'.
5. Two buttons should appear to add new content, click on one of the buttons, and choose 'Doc Type'.

Your Document Type marked as Element Type should appear without the actual property editors showing up.

### Expected result / actual result

After step 5 the expected result is the properties would correctly load the property editors of the corresponding data types.
The actual result is the property editors not loading correctly, and an error message in the console of the browser.

Below some screenshots of the issue:
![Screenshot_6](https://user-images.githubusercontent.com/105918931/190121521-ffdb0fc7-b981-450c-88ae-e22ce1d2bf80.png)
![Screenshot_7](https://user-images.githubusercontent.com/105918931/190121544-e1b941fa-92d3-4522-b7ce-0767ced27b42.png)
![Screenshot_8](https://user-images.githubusercontent.com/105918931/190121564-758c1d61-8e6a-4044-bec5-6dc1209d386e.png)

---
_This item has been added to our backlog [AB#22612](https://dev.azure.com/umbraco/243e7927-03b2-44e2-908f-d4ac7ea5daaa/_workitems/edit/22612)_

**Comment by nul800sebastiaan** [comment]
This seems more related, with the same error: https://github.com/leekelleher/umbraco-contentment/issues/250

**Comment by RGV2ZWxvcGVy** [comment]
I see that there is a new version of the package available: [https://our.umbraco.com/packages/backoffice-extensions/doc-type-grid-editor/](https://our.umbraco.com/packages/backoffice-extensions/doc-type-grid-editor/) :)
This fixes the issue, so I will close this ticket.

**Comment by iOvergaard** [comment]
Hey everyone, we are going to fix it on a more general level in the upcoming 10.2.1 patch: #13060
