### ISSUE TITLE
ContentLastChanceFinder gets executed one every request after upgrade to 10.2.0

### ISSUE THREAD

**Issue by charlesbubliesconstructit** [umbraco/Umbraco-CMS#13005]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

10.2.0

### Bug summary

I have muliple sites with a  custom ContentLastChanceFinder that is more or less the same as the on described in the documentation.

After upgrading Umbraco to 10.2.0, every request triggers ContentLastChanceFinder which results in redirecting the request to my 404 page.

At first i thought there was an issue with how i implemented my ContentLastChanceFinder, so i disabled it but the result is the same. The default "ContentFinderByConfigured404" is instead triggerd on every request.

I have also noticed that request to my UmbracoApi endpoints also triggers ContentLastChanceFinder or ContentFinderByConfigured404

### Steps to reproduce

Update Umbraco via NuGet, in our case from v10.1.1 to v10.2.

Launch the application, you are presented with the authorize upgrade screen.

The upgrade completes successfully and redirects to the backoffice.

Try to visit any page on my website, ContentLastChanceFinder is executed on every request and request is redirected to my 404

Disable my custom ContentLastChanceFinder and use the default ContentFinderByConfigured404

Try to visit any page on my website, ContentFinderByConfigured404 gets executed  an every request.

### Expected result / actual result

**Expected result**
Request is not redirected when visiting an exisitng site in cms. Redirect non existing request to 404 page

**Actual result**
Every request triggers ContentLastChanceFinder or ContentFinderByConfigured404 and redirects request to my 404 page

**Comment by enkelmedia** [comment]
Not really 100% sure but maybe it might be related to this issue?

https://github.com/umbraco/Umbraco-CMS/issues/12965

Did you make any changes to the "ReservedPaths" or "Reserved Urls" in your appSettings?

**Comment by charlesbubliesconstructit** [comment]
> Not really 100% sure but maybe it might be related to this issue?
> 
> #12965
> 
> Did you make any changes to the "ReservedPaths" or "Reserved Urls" in your appSettings?

@enkelmedia haven't touched those settings in any of my applications.

**Comment by nul800sebastiaan** [comment]
I think @enkelmedia is on to something. So I "accidentally" could reproduce exactly this on a 10.2.0 project where I had recently added a SignalR hub. I had NOT added the SignalR route to `ReservedPaths`, so there was 2 requests constantly going through the  `IContentLastChanceFinder`. As soon as I reserved the route, the breakpoints never got hit again.

To figure out what's causing this in your case you can inspect the `contentRequest` in `TryFindContent`. I'll close this for now but if this doesn't help and there's a different cause then we can of course look again.

**Comment by charlesbubliesconstructit** [comment]
@nul800sebastiaan in my case im not using SignalR
@enkelmedia 

I decied to create a blank app with 10.2.0 and i could reproduce the same error. What I discoverd  was that IContentLastChanceFinder is triggerd when you dont have a template specified to your doctype. This was never an issue in previous versions of 10,, 9 or 8 for us.

In our projects we have a custom defaultcontroller for returning all our views for each doctype so we dont use them template function in umbraco. If i add a template do a doctype but still use my custom defaultcontroller everyting works fine, the IContentLastChanceFinder is not triggerd and my custom view is displayed.

So my uneducated guess is that somewhere in the pipeline the code is looking for a template  and thorws and 404 when its not find before accessing my controller.
