### ISSUE TITLE
Toggling Approved for a member stops working after clicking Save

### ISSUE THREAD

**Issue by justin-nevitech** [umbraco/Umbraco-CMS#13027]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

10.2

### Bug summary

After clicking Approved to true on a member and clicking Save, you can then toggle Approved to false and click Save again but you can then no longer toggle Approved further without refreshing the browser.

### Specifics

When changing Approved to true on a member and clicking Save, you can then change Approved to false and click Save again but then you can no longer change Approved without refreshing the browser.  The config in the boolean editor which allows the state to change between true/false is lost after the Save has been completed and you can no longer change Approved without refreshing the browser.

The same happens on Edge, Chrome and Brave.

### Steps to reproduce

Steps to reproduce:

1. Create a new member and untick Approve
2. Once the member has been created, go to the member tab and click Approve to set it to true
3. Click Save but do not refresh the screen
4. Click Approve to set it to false
5. Click Save but do not refresh the screen
6. Try and click Approve again and you can no longer set it to true unless you refresh the page

See attached video.

https://user-images.githubusercontent.com/67802060/190912792-8859eedb-3ff4-4e17-b8b2-131fbf74de3c.mp4

### Expected result / actual result

You should be able to toggle Approved between true and false and click Save multiple times without refreshing the browser.

**Comment by nul800sebastiaan** [comment]
Thanks @justin-nevitech!

We'll have a look at this soon, in the mean time, I have two observations:

1. No need to create an issue before you create a PR, if you already know you've fixed it, only create a PR please, it saves everyone admin time.
2. If you DO have an issue for the PR, then please use the PR template you get when creating a new PR. When GitHub sees the text `this fixes #12345`, it will automatically link the issue and the PR together, again, less admin time for us 😃 

Thanks again, the team will look at this soon!

**Comment by justin-nevitech** [comment]
Ok, will bear this in mind for the next one @nul800sebastiaan .  Thanks for the feedback.
