### ISSUE TITLE
Can't upload webp through upload drawer

### ISSUE THREAD

**Issue by acbach** [umbraco/Umbraco-CMS#13041]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

Umbraco version 9.5.0

### Bug summary

- Uploading a webp file through the inline upload drawer menu throws an error "Cannot read properties of undefined (reading 'isFolder')"
- Have not tried other browsers than Edge Version 105.0.1343.42 (Official build) (64-bit)
- Uploading directly to media folder works fine as a workaround 🎉🙌

### Specifics

https://cms.dev-hessel.dk/umbraco/#/media?mculture=da-DK

`
favicon.ico:1 
        
      
        
        
      
        
      
       
        
       Failed to load resource: the server responded with a status of 404 (Not Found)
ejh-rte.css:1 
        
      
        
        
      
        
      
       
        
       Failed to load resource: the server responded with a status of 404 (Not Found)
angular.js:15635 
        
       TypeError: Cannot read properties of undefined (reading 'isFolder')
    at clickHandler (umbraco.controllers.min.js?d=637993458200000000:formatted:7351:19)
    at umbraco.controllers.min.js?d=637993458200000000:formatted:7197:25
    at angular.js:21661:28
    at Yg.completeTask (angular.js:21299:7)
    at angular.js:6879:7
(anonymous) @ angular.js:15635
ejh-rte.css:1 
        
      
        
        
      
        
      
       
        
       Failed to load resource: the server responded with a status of 404 (Not Found)
DevTools failed to load source map: Could not load content for https://cms.dev-hessel.dk/umbraco/lib/tinymce//skins/lightgray/skin.min.css.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
angular.js:15635 
        
       TypeError: Cannot read properties of undefined (reading 'isFolder')
    at clickHandler (umbraco.controllers.min.js?d=637993458200000000:formatted:7351:19)
    at umbraco.controllers.min.js?d=637993458200000000:formatted:7197:25
    at angular.js:21661:28
    at Yg.completeTask (angular.js:21299:7)
    at angular.js:6879:7

angular.js:15635 
        
       TypeError: Cannot read properties of undefined (reading 'isFolder')
    at clickHandler (umbraco.controllers.min.js?d=637993458200000000:formatted:7351:19)
    at umbraco.controllers.min.js?d=637993458200000000:formatted:7197:25
    at angular.js:21661:28
    at Yg.completeTask (angular.js:21299:7)
    at angular.js:6879:7 'Possibly unhandled rejection: {}'

angular.js:15635 
        
       Cannot resolve the file url from the mediaEntity, it does not contain the required metaData
`

### Steps to reproduce

<img width="1249" alt="Annotation 2022-09-21 103830" src="https://user-images.githubusercontent.com/43601099/191458039-57c666df-1071-46b3-9d48-a67bfc39ddb3.png">

<img width="1249" alt="image-2022-09-20-08-36-26-134" src="https://user-images.githubusercontent.com/43601099/191458054-7fbc924d-7fc4-434e-b86b-cb7a2aa61fbc.png">

### Expected result / actual result

Should upload the webp. Jpeg works fine.

**Comment by patrickdemooij9** [comment]
This might be caused by Webp not being supported on Umbraco 9. I think you are able to do this with Umbraco 10+

**Comment by kjac** [comment]
Hi @acbach - thank you for your very detailed error description, and sorry for the prolonged response time.

WebP is supported out of the box in V10+. We won't be back-porting it to V9 at this point - instead we recommend you upgrade to V10 or later.
