### ISSUE TITLE
X-XSS-Protection health check is not needed as this is not a recommended header

### ISSUE THREAD

**Issue by skartknet** [umbraco/Umbraco-CMS#13040]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

10.2.0

### Bug summary

Currently, there's a health check that checks if the X-XSS-Protection header is configured on the site. From the [Mozilla docs,](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-XSS-Protection) it says that the X-XSS-Protection header is not standard and in fact not recommended on production sites.

### Steps to reproduce

Go to the health checks setion.

**Comment by gilbertaoe** [comment]
@skartknet I made the changes and created a pull request for it.

**Comment by mikecp** [comment]
closing as the associated PR has been merged
