### ISSUE TITLE
Members who are linked to an external login can't be deleted

### ISSUE THREAD

**Issue by laurengore42** [umbraco/Umbraco-CMS#13049]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

9.5.4

### Bug summary

Members who have an ExternalLoginToken in the database cannot be deleted using the Delete button in the back office.

### Specifics

This issue is occurring on an Umbraco site which has an OIDC external login connection to an IDP. In the Umbraco site, members are created via auto-linking to the IDP.

If you create a member via auto-linking on external login, and then go into the back office, select that member, and press Delete, you get the following error message:

![image](https://user-images.githubusercontent.com/12659154/191698475-fafe27e1-f9cc-4202-a233-067322d5570c.png)

Judging by the error message I think this would probably happen with any external login method, but in case it's helpful in the reproduction, here's our external login setup:

            builder.AddMemberExternalLogins(logins =>
            {
                logins.AddMemberLogin(
                    memberAuthenticationBuilder =>
                    {
                        memberAuthenticationBuilder.AddOpenIdConnect(
                            memberAuthenticationBuilder.SchemeForMembers(OpenIdConnectDefaults.AuthenticationScheme),
                            options =>
                            {
                                config.Bind("IdentityServer:Client", options);
                            });
                    });
            });

### Steps to reproduce

- Set up OIDC external login to an IDP.
- Create a member on your IDP.
- Log in to the SP as the member, so that they get created in the SP via auto-linking.
- Go into the back office of your SP, go to Members, select that member, and click the Delete button.

### Expected result / actual result

Expected: The member is deleted, and this effect is cascaded to any other database rows that refer to the member via foreign key.
Actual result: The member is not deleted, and I get an error message.

---
_This item has been added to our backlog [AB#23093](https://dev.azure.com/umbraco/243e7927-03b2-44e2-908f-d4ac7ea5daaa/_workitems/edit/23093)_

**Comment by elit0451** [comment]
Thanks for reporting this @laurengore42. This problem has been fixed in Umbraco 10 - https://github.com/umbraco/Umbraco-CMS/pull/12872. Therefore, we suggest you to [upgrade](https://umbraco.com/products/umbraco-cms/umbraco-10/). Umbraco 9 is in its “Security” phase at the moment, which means we will only fix security issues.
