### ISSUE TITLE
Invalid DB Connection begins a  new build of Umbraco

### ISSUE THREAD

**Issue by deanleigh** [umbraco/Umbraco-CMS#13042]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

Umbraco version 10.1.0

### Bug summary

When an Azure SQL DB specified in appsettings.json does not connect for whatever reason a new build of Umbraco is triggered

### Steps to reproduce

Set firewall to block Azure SQL for the site

### Expected result / actual result

The Umbraco New Site sequence begins

**Comment by gilbertaoe** [comment]
@deanleigh I've made some changes and have opened a pull request for this bug.

**Comment by deanleigh** [comment]
Thank you, it was an odd issue to describe, great news if you have a solution.

**Comment by joepvtl** [comment]
Hi,

This is probably the same issue as: #12949

**Comment by bergmania** [comment]
Fixed in https://github.com/umbraco/Umbraco-CMS/pull/13118
