### ISSUE TITLE
app.UseExceptionHandler(path) fails when path is an Umbraco page

### ISSUE THREAD

**Issue by tormnator** [umbraco/Umbraco-CMS#13052]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

10.2.0

### Bug summary

In Umbraco 10 and .NET 6, using app.UseExceptionHandler(errorHandlingPath) to display application errors (thrown exceptions) only works when the path is to a static html page. If the path is to an Umbraco content page, the Umbraco end point is never reached.

The same scenario works in a pure .NET 6 MVC web application (where the error page is a Razor view).

### Specifics

The issue occurs because <a href="https://github.com/umbraco/Umbraco-CMS/blob/v10/contrib/src/Umbraco.Web.Website/Routing/UmbracoRouteValueTransformer.cs#L96" target="_blank">UmbracoRouteValueTransformer.TransformAsync()</a> fails to return a required `RouteValueDictionary` to the calling methods during the re-routing to our error page after an exception is thrown. The consequence of the Umbraco issue is that our error page is not displayed because .NET 6's `EndpointMiddleware.Invoke()` fails due to `HttpContext.GetEndpoint()` returning null.

The reason for the failure is that `UmbracoRouteValueTransformer.TransformAsync()` sees that there already is an `UmbracoRouteValues` instance in `HttpContext.Features`, but doesn't know that the reason for the instance being there is that we're in a re-execute of the middleware after a thrown exception. Instead it thinks "*someone else is dynamically routing and in which case we don't want to overwrite the routing work being done there*" (quote from the source code comment inside the TransformAsync() method).

The fix in Umbraco is for Umbraco's code to somehow clear the `UmbracoRouteValues` from the `HttpContext.Features` collection before the call stack reaches the `EndpointRoutingMiddleware`, or update the code in `UmbracoRouteValueTransformer.TransformAsync()` to detect that we're in an exception re-route/re-execution situation and return the correct `RouteValueDictionary`.

Middleware stack (irrelevant entries removed):

1. `ExceptionHandlerMiddleware` // Handles exceptions and updates/clears the HttpContext for re-routing to the error page
2. `EndpointRoutingMiddleware`  // Finds and assigns an Endpoint if the HttpContext.GetEndpoint() returns null
3. `EndpointMiddleware`         // If an Endpoint exists, re-processes the request for the endpoint

The `EndpointRoutingMiddleware` is responsible for re-assigning an `Endpoint` instance to the `IEndpointFeature` installed in `HttpContext.Features` after the original `Endpoint` was cleared by the `ExceptionHandlerMiddleware` (part of the re-routing to the error page). Inside the `EndpointRoutingMiddleware.Invoke()` method the following call stack is created:

1. <a href="https://github.com/dotnet/aspnetcore/blob/main/src/Http/Routing/src/EndpointRoutingMiddleware.cs#L49" target="_blank">EndpointRoutingMiddleware.Invoke()</a>
2. <a href="https://github.com/dotnet/aspnetcore/blob/53a126424ca4399ffd276b2cfe2b70db6bdde252/src/Http/Routing/src/Matching/DfaMatcher.cs#L29" target="_blank">DfaMatcher.MatchAsync()</a>
3. <a href="https://github.com/dotnet/aspnetcore/blob/53a126424ca4399ffd276b2cfe2b70db6bdde252/src/Http/Routing/src/Matching/DfaMatcher.cs#L304" target="_blank">DfaMatcher.SelectEndpointWithPoliciesAsync()</a>
4. <a href="https://github.com/dotnet/aspnetcore/blob/3ea008c80d5cc63de7f90ddfd6823b7b006251ff/src/Mvc/Mvc.Core/src/Routing/DynamicControllerEndpointMatcherPolicy.cs#L68" target="_blank">DynamicControllerEndpointMatcherPolicy.ApplyAsync()</a>
5. <a href="https://github.com/umbraco/Umbraco-CMS/blob/v10/contrib/src/Umbraco.Web.Website/Routing/UmbracoRouteValueTransformer.cs#L96" target="_blank">Routing.UmbracoRouteValueTransformer.TransformAsync()</a>

A work-around is to install a middleware callback (see below) right after the call to `app.UseExceptionHandler(ExceptionHandlingPath)` and--if it is inside an exception call--clear the `UmbracoRouteValues` from `HttpContext.Features`. This middleware will then be installed in between the ExceptionHandlerMiddleware and EndpointRoutingMiddleware entries.

```csharp
const string ExceptionHandlingPath = "/error";
app.UseExceptionHandler(ExceptionHandlingPath); // Installs the custom error page
app.Use(async (context, next) =>
{
    // Detect and work around issue causing the error page not to be displayed:
    if (context.Response.StatusCode == StatusCodes.Status500InternalServerError && context.Request.Path == ExceptionHandlerPath)
    {
        context.Features.Set<UmbracoRouteValues>(instance: null);
    }
    await next();
});
```

### Steps to reproduce

1. Create a new Umbraco 10 web app, e.g. using the auto-generated scripts created by https://psw.codeshare.co.uk/ as the starting point.
2. Add a home page, a test page, and an error page using the back office.
3. In the view template for the test page add a "throw new Exception(...)" statement which will trigger the exception handling process when you navigate to the page.
4. In Startup.Configure() remove any `if (env.IsDevelopment())` clause and the `app.UseDeveloperExceptionPage();` call. Instead add a call to `app.UseExceptionHandler("/error");` and replace "/error" with your error page's url.
5. Run the app, navigate explicitly to the error page to verify that it's reachable, and then navigate to the test page to trigger the exception.

### Expected result / actual result

Expected: the assigned error page (controller/view) should be reached and displayed in the browser when an exception is thrown in the application.

Actual: Status code 500 with no content is returned to the browser. In Chrome on Windows the browser displays the following:

![image](https://user-images.githubusercontent.com/15617453/191858605-0cdbcd32-1a71-4215-a2f6-838495a0343e.png)

**Comment by kjac** [comment]
@tormnator first of all - apologies for the late reply here.

Thank you so much for your very detailed issue report 💪 I can reproduce it. 

When a 500 error occurs, you can't necessarily rely on Umbraco being able to render a 500 page from the content tree; the 500 error might have been caused by a misconfiguration of or runtime error within Umbraco. Therefore I would always recommend for 500 error pages to be static files on disk - i.e. use `app.UseExceptionHandler("/error.html");`, where _error.html_ is a static file in _wwwroot_. 

Still... we'd love some help getting this fixed if at all possible, so I have added "up for grabs" to this issue. If you're up for it, go ahead 😄 

⚠️ **Anyone attempting to fix this issue, please notice!** ⚠️ 

Before taking on this issue, you should first remove the reference to the "Umbraco.Cms.ManagementApi" project from the "Umbraco.Web.UI" project, as the former interferes with this issue.

**Comment by kjac** [comment]
@tormnator noted 👍 good luck on the migration! We'll see if someone picks this up 😄 at least there is a workaround.
