### ISSUE TITLE
Version number not updated correctly in v7.15.9

### ISSUE THREAD

**Issue by dvandevliet** [umbraco/Umbraco-CMS#13053]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

7.15.9

### Bug summary

After installing update v7.15.9 in the web.config the version number is 7.15.8

Expected to see version bumped to 7.15.9 in the web.config

### Specifics

The following commit for release of 7.15.9 did not update version number in Umbraco.Core
https://github.com/umbraco/Umbraco-CMS/commit/da6bc2bdea4cad93cd7b07253a87093dd037bb3d

At least this file of 7.15.9 still contains the version number 7.15.8
https://github.com/umbraco/Umbraco-CMS/blob/v7/7.15.9/src/Umbraco.Core/Configuration/UmbracoVersion.cs

### Steps to reproduce

Install Umbraco v7.15.9

### Expected result / actual result

Expected: Umbraco version in web.config is 7.15.9 
Actual: Umbraco version in web.config is 7.15.8

**Comment by dvandevliet** [comment]
Hi, 

I understand that v7 is old and not high priority, but the current available release v7.15.9 is now broken. 
To fix the release no indepth coding is required except a correct bump to v7.15.10. 

I would greatly appreciate if you could find time to fix this as this is now blocking us in deploying the security update this patch was released for. 

Thank you,
David

**Comment by nul800sebastiaan** [comment]
Fixed in https://github.com/umbraco/Umbraco-CMS/pull/13076 - this was just released now. Apologies for the delay! And Thank you for your patience 🙏
