### ISSUE TITLE
New 'variant permissions' features missing / not visible?

### ISSUE THREAD

**Issue by creativesuspects** [umbraco/Umbraco-CMS#13067]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

10.2.1

### Bug summary

I've just installed a clean 10.2.1 project. But I'm not seeing the culture and invariant/shared labels on properties. And when I want to edit a shared property I only see a green 'Edit' button, no '{propertyname} is shared across all languages warning'.

![image](https://user-images.githubusercontent.com/161342/192618831-784117b8-138f-49bf-8ff0-5b295a2082be.png)

These new features were visible in the screenshots for PR #12605 in the [Unboxing Umbraco 10.2 video](https://www.youtube.com/watch?v=3Z4Quq82FDE).

### Steps to reproduce

- Install a clean 10.2.1 project without a starter kit
- Add an additional non-default language, e.g. Dutch (Netherlands)
- Add a document type with 'Allow vary by culture' and 'Allow as root'
- Add a Textstring property with 'Allow vary by culture' disabled
- Add a second Textstring property with 'Allow vary by culture' enabled
- Add a single content node based on the document type
- Configure Culture and Hostnames
- Add values to the default language
- Change Languages for 'Administrators' group, only allow the non-default language (e.g. Dutch)
- Go to content node and edit the Dutch variant
- No 'culture and invariant/shared labels' are being displayed, and no warning message when editing the shared property

### Expected result / actual result

I would expect to see these features:

_Pop over to "unlock" and edit the value. The Popover is visible when the property is hovered or has focus._
![image](https://user-images.githubusercontent.com/161342/192620249-7293ed3b-e341-46db-b8a3-0e94905fc8ed.png)

_A label for a variant property that shows the current culture. The label is visible when the Property Editor is hovered or has focus._
![image](https://user-images.githubusercontent.com/161342/192620330-9d9d8e2c-d92a-4b13-b5cb-adf728ced9fd.png)

_A label for an invariant property that shows it's shared. The label is visible when the Property Editor is hovered or has focus._
![image](https://user-images.githubusercontent.com/161342/192620384-1152e9c8-e995-4eb0-9e3c-2097be8e9de4.png)

---
_This item has been added to our backlog [AB#23092](https://dev.azure.com/umbraco/243e7927-03b2-44e2-908f-d4ac7ea5daaa/_workitems/edit/23092)_

**Comment by madsrasmussen** [comment]
Hi @creativesuspects 

I have followed the steps in your description with fresh install, and I can't seem to replicate the issue. Do you have more details about your setup. Operating system, browser etc.?

Can I also get you to do a fresh install and try again?

<img width="1279" alt="popover" src="https://user-images.githubusercontent.com/6078361/194824039-6b21c948-0e7c-46e1-b705-a4d2b8752504.png">

<img width="1280" alt="version" src="https://user-images.githubusercontent.com/6078361/194824082-59fefea1-76e1-4f6e-8e5b-d733231d2ebb.png">

**Comment by creativesuspects** [comment]
Hi @madsrasmussen 

I've deleted all the 10.2.1 package files from C:\Users\<Username>\.nuget to make sure it's not a caching issue. And I've created a screencast of the clean installation process:

https://somup.com/c366jMvhkC

**Comment by creativesuspects** [comment]
Awesome! I'm glad you were able to resolve the issue so swiftly.
