### ISSUE TITLE
Umbraco 10 custom index registering but index cannot be rebuilt because it has no assigned IIndexPopulator

### ISSUE THREAD

**Issue by Wiggee11** [umbraco/Umbraco-CMS#13070]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

10.1.1

### Bug summary

Following the documentation here https://our.umbraco.com/documentation/Reference/Searching/Examine/indexing/#creating-your-own-index to create a custom index.

The custom index is registered in the backoffice but the index is empty and you cannot rebuild the index because `This index cannot be rebuilt because it has no assigned IIndexPopulator`.

### Steps to reproduce

Copy the 5 required files from the documentation - https://our.umbraco.com/documentation/Reference/Searching/Examine/indexing/#creating-your-own-index

1. An UmbracoExamineIndex implementation that defines the index
2. An IConfigureNamedOptions implementation that configures the fields of the index
3. An IValueSetBuilder implementation that builds the value sets for the index
4. An IndexPopulator implementation that populates the index with the value sets
5. A composer that adds all these services to the runtime.

Run the application. Inspect the index in the backoffice > Settings > Examine Management.

Put some breakpoints in the `IndexPopulator` and `IValueSetBuilder` and you will see that code is triggered and expected data being processed, but the index remains empty. No temp examine data files are generated.

### Expected result / actual result

When following the documentation, registering a custom index with an `IndexPopulator`, the custom index should be populated, not remain empty.

---
_This item has been added to our backlog [AB#23090](https://dev.azure.com/umbraco/243e7927-03b2-44e2-908f-d4ac7ea5daaa/_workitems/edit/23090)_

**Comment by nul800sebastiaan** [comment]
@Wiggee11 your specific error indicates that you didn't add the following to your composer: `builder.Services.AddSingleton<IIndexPopulator, MyIndexPopulator>();` we are aware that there may be problems though as indicated in https://github.com/umbraco/UmbracoDocs/issues/4426

**Comment by Wiggee11** [comment]
I had this in my composer `builder.Services.AddSingleton<ProductIndexPopulator>();` and my `public class ProductIndexPopulator : IndexPopulator`.

**Comment by nul800sebastiaan** [comment]
I've added a long comment here: https://github.com/umbraco/UmbracoDocs/issues/4426#issuecomment-1274769934

It all kinda works but has plenty of bugs and things NEED to be in the right order in the composer.

**Comment by sofietoft** [comment]
Hi all 👋 

The docs for this have been updated: https://github.com/umbraco/UmbracoDocs/pull/4625, as per the comments in https://github.com/umbraco/UmbracoDocs/issues/4426.
Would be great to have it tested - something you'd be up for @Wiggee11 ? 🤞

**Comment by Zeegaan** [comment]
This has been fixed with the update of the documentation here: https://github.com/umbraco/UmbracoDocs/pull/4625
Please don't hesitate to re-open if this is still an issue 😊
