### ISSUE TITLE
Right click pasting bypasses character count validation in text area property

### ISSUE THREAD

**Issue by Bakersbakebread** [umbraco/Umbraco-CMS#13083]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

10.3.0

### Bug summary

Right click pasting text into a text area with an upper character limit is bypassed allowing content to be published

### Specifics

- Reproducible on all browsers

![chrome_YAYaPqKKlv](https://user-images.githubusercontent.com/29239704/193251298-cb5c2a6d-4839-4a8c-ae60-9529679135f5.gif)
![chrome_dU7J3j0KxI](https://user-images.githubusercontent.com/29239704/193251302-098db97d-f1e6-438c-a081-07d4ec6a5557.gif)

### Steps to reproduce

1. Add TextArea property to doctype with a character limit set
2. Get more characters than allowed in clipboard
3. Right click -> Paste
4. Save & Publish
5. Observe no error
6. Refresh
7. Observe error

### Expected result / actual result

Validation should not allow item to be saved

**Comment by mikecp** [comment]
Closed as per merge of PR 13084
