### ISSUE TITLE
Validation error is not shown when saving Macro.

### ISSUE THREAD

**Issue by andr317c** [umbraco/Umbraco-CMS#13099]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

latest (v10/dev)

### Bug summary

Validation error is not shown when trying to save a Macro. 
When you are in the Parameters content app in the macro, it shows that there is a validation error with the Macro settings. When you then go back to settings, there is no validation error, but you still cant save.

### Specifics

![UmbracoNoValidationErrorWhenSavingMacro](https://user-images.githubusercontent.com/73799582/193555498-7914a65b-cfdd-4176-8706-9c3754ffa4b9.gif)

### Steps to reproduce

1: Create a macro without a partial view
2: Change a macro setting.
3: Click save.

### Expected result / actual result

Expected: That a validation error is shown when im trying to save a macro without a partial view.

Actual: No validation error is shown, and im not able to save when trying to save a macro without a partial view.

---
_This item has been added to our backlog [AB#23089](https://dev.azure.com/umbraco/243e7927-03b2-44e2-908f-d4ac7ea5daaa/_workitems/edit/23089)_

**Comment by Zeegaan** [comment]
Fixed in https://github.com/umbraco/Umbraco-CMS/pull/13170
