### ISSUE TITLE
AspNetCoreRequestAccessor can leak memory

### ISSUE THREAD

**Issue by Nashuim** [umbraco/Umbraco-CMS#13098]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

10.2.0

### Bug summary

AspNetCoreRequestAccessor has an OnChange handler in the constructor that is never disposed. Normally this wouldn't have been an issue since AspNetCoreRequestAccessor is a singleton but it also contains event handler code for the UmbracoRequestBeginNotification notification. 

Every time this notification is published a new instance of AspNetCoreRequestAccessor is created and with it a new OnChange handler which will contain a reference to the instance of AspNetCoreRequestAccessor until the website is reset.

This is a very minor leak and memory graphs just show the memory usage very slowly moving upwards.
This is what dotMemory shows:
![image](https://user-images.githubusercontent.com/5592694/193539343-6fce8052-e65a-43a6-92ae-9e0c14170759.png)

The invocationList of the action `x => _webRoutingSettings = x` continually grows with each request.

### Steps to reproduce

1. Start a website running umbraco
2. Do multiple requests for time
3. Memory will go up due to an increase of `Action<WebRoutingSettings,String>`

---
_This item has been added to our backlog [AB#23075](https://dev.azure.com/umbraco/243e7927-03b2-44e2-908f-d4ac7ea5daaa/_workitems/edit/23075)_

**Comment by nikolajlauridsen** [comment]
Hey @Nashuim just popping in to say I've taken a look at it and made a PR which fixes it in #13152.

I just want to say thank you so much for your detailed description, it really made my job fixing it, so much easier, so thank you H5YR! 🎉

**Comment by nikolajlauridsen** [comment]
#13152  has been merged and cherry-picked for 10.3, so I'll go ahead and close this issue :) Thanks again
