### ISSUE TITLE
Implement fix for #12295 also in Umbraco v8

### ISSUE THREAD

**Issue by wjvankesteren** [umbraco/Umbraco-CMS#13102]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

8.18.5

### Bug summary

In bug report #12295 I aksed to port te fix also to version 8.
Since there was no reply on my request, I create this bug report to ask to port the fix to Umbraco v8 as well.

"Any change that this fix will be ported to Umbraco v8 ?
We have a lot of customers who wants to upgrade to Umbraco v8 and this will make the migration process much easier.

Perhaps the fix (by just continueing) is a bit bold - what if string is completely made of suggorate pairs?
I would suggest to replace it (e.g. '🎈') by something like '(U+1F388)'

Furthermore, it would help by logging which 'short string' (e.g. macro alias) is affected."

### Specifics

see #12295

### Steps to reproduce

see #1229

### Expected result / actual result

At least not throwing an assert

**Comment by bergmania** [comment]
Cherry picked for next 8 patch :)
