### ISSUE TITLE
Saving a `null` value in a property editor comes back as `"null"`

### ISSUE THREAD

**Issue by abjerner** [umbraco/Umbraco-CMS#13125]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

10.2.1

### Bug summary

If a property editor saves a null value, Umbraco will change that to a string containing the value null, which then has a different meaning.

### Steps to reproduce

The following three files make up an example property editor. `NullString.js` contains my hacks to mitigate the bad `"null"` value. If outcommented, the property editor will not work correctly.

In the past, I think null values were converted to an empty string, which we could then check for with `if (!$scope.model.value)`, but if the value is `"null"` instead of just `""`, this check won't work.

So if the user saves the page, and then after that tries to enter a value in the input field, it will cause an Angular error.

![image](https://user-images.githubusercontent.com/3634580/194042314-c0d19c87-dab9-46ff-92a9-fdd9964cd8bd.png)

**/App_Plugins/NullString/package.manifest**
```json
{
  "javascript": [
    "/App_Plugins/NullString/NullString.js"
  ],
  "propertyEditors": [
    {
      "alias": "NullString",
      "name": "NullString",
      "editor": {
        "view": "/App_Plugins/NullString/NullString.html",
        "valueType": "JSON"
      }
    }
  ]
}
```

**/App_Plugins/NullString/NullString.js**
```js
angular.module("umbraco").controller("NullString", function($scope) {

    // The property value will initially be an empty string, but we need it to be null
    if (!$scope.model.value) $scope.model.value = null;

    // If Umbraco saves a null value, and the page is reloaded, the value will be a string with the
    // value "null", which prevents us from binding an input field to "model.value"
    if (!$scope.model.value) $scope.model.value = null;
    
    // Hack to re-set the property value to null as Umbraco may change the value to a string with
    // the value "null"
    $scope.$watch("model.value", function () {
        if ($scope.model.value === "null") $scope.model.value = null;
        if ($scope.model.value && !$scope.model.value.source) $scope.model.value = null;
    });

});
```

**/App_Plugins/NullString/NullString.html**
```html
<div ng-controller="NullString">    
    <input type="text" ng-model="model.value.source" />    
    <pre>{{model.value | json}}</pre>
</div>
```

Null values seem to be saved correctly in the database, so the issue is around when the property editor is loaded with a value that is null.

### Expected result / actual result

As the property is saving a null value, I'd also expect a null value back when the page (property editor) is reloaded.

---
_This item has been added to our backlog [AB#23088](https://dev.azure.com/umbraco/243e7927-03b2-44e2-908f-d4ac7ea5daaa/_workitems/edit/23088)_

**Comment by elit0451** [comment]
Thanks for reporting this @abjerner! #13163 contains the fix for v11. Check [comment](https://github.com/umbraco/Umbraco-CMS/pull/13163#issuecomment-1280936448) about v10.
