### ISSUE TITLE
Media picker local crops - GetCropUrl returning empty value

### ISSUE THREAD

**Issue by jono-k** [umbraco/Umbraco-CMS#13138]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

10.2.1

### Bug summary

Appears to be an issue with local crops. The following code returns an empty image URL:

```
var imageUrl = "";
if(item.HasValue("image") && item.Value("image") != null) {
var mediaItem = item.Value<MediaWithCrops>("image");
imageUrl = mediaItem.GetCropUrl("listItem");
}
```

### Specifics

I have tried using various crop aliases, and tried uploading different images.

### Steps to reproduce

Add some local crops to the media picker datatype.

---
_This item has been added to our backlog [AB#23087](https://dev.azure.com/umbraco/243e7927-03b2-44e2-908f-d4ac7ea5daaa/_workitems/edit/23087)_

**Comment by V414** [comment]
I was actually trying to work out why my local crops weren't working on v.10.3.2 and ran into this ticket whilst seeing if anyone had reported something. After reading the above, I restarted the app just to check and they began working!

This piece of code:
var crops = content.BlockBackgroundImage.LocalCrops;

Had been returning something like before the restart:
{{"src":"/media/test/test.jpg","focalPoint":{"left":0.548,"top":0.7386666666666667},"crops":[]}}

And now it has all the crops registered!

No idea why adding local crops in would require a restart to be used by the website properly...
