### ISSUE TITLE
Drag n dropping media files into RTE results in it never being moved from /temp to /media after a save/publish

### ISSUE THREAD

**Issue by RyuLindow** [umbraco/Umbraco-CMS#13130]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

9.5.4 and 10.2.1

### Bug summary

Media files drag n dropped into an RTE are not linked properly in it.

The RTE source code editor has the image encoded in the base64 format and the image is never moved from the FileUploads to Media folder after the node is saved/published.

### Specifics

In v8 drag n dropping a media file results in the following:
1. The file is uploaded to a folder in `App_Data\TEMP\FileUploads\rte`
2. After saving/publishing the node the file is moved to its own folder in the /media folder
3. The file is linked in the RTE code as shown below
![image](https://user-images.githubusercontent.com/56826332/194181287-7171f35a-3640-479f-ada2-4745991f0dac.png)

In v9 and v10 drag n dropping a media file results in the following
1. The file is uploaded to a folder in `wwwroot\umbraco\Data\TEMP\FileUploads\rte`
2. After saving/publishing the node the file is never moved to the /media folder which results in it never getting a /media/folderName URL

2nd line is a media picker picked image.
4th is the drag n dropped one(It's only a fraction of the base64 encoded string but I believe that's just enough)
![image](https://user-images.githubusercontent.com/56826332/194183345-dd6258d8-7b71-403c-b367-c5ed432f0c87.png)

Also, this pop up never goes away unless you refresh the page but that's just a byproduct of the issue
![image](https://user-images.githubusercontent.com/56826332/194183992-24351640-252b-47c8-a176-eecf438f54e3.png)

Here's a [LINK](https://murica-numero-uno.useast01.umbraco.io/) to 10.2.1 project hosted on UC.

You can open the drag n dropped image in a new tab to see its URL.

### Steps to reproduce

1. create a doc type with an RTe
2. create a node
3. drag n drop an image into the RTE(just make sure that you're using the default config, as you need the `image` to be enabled in toolbar settings)
4. view the RTE source code editor or render the RTE on the frontend and try viewing the file in a new tab to see it's URL

**Comment by bergmania** [comment]
Fixed in https://github.com/umbraco/Umbraco-CMS/pull/13016
