### ISSUE TITLE
Multiple Tags getting combined into a single "Tag"

### ISSUE THREAD

**Issue by hfloyd** [umbraco/Umbraco-CMS#13132]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

10.2.1

### Bug summary

I have migrated a v7 site to v10. On a ContentType with a Tags property, which is configured with CSV storage (unchanged from v7), there is a strange issue with the tags. 

When I view the tags in the back-office, they are separated and look correct:
![image](https://user-images.githubusercontent.com/1252593/194208159-7b22ca4e-0310-48e1-a1e9-cf87be7595f8.png)

And when I pull the data via ModelsBuilder into a template for that Content Type to display, the Tags come across as an `IEnumerable<string>` with two separate items which I can render separately:
![image](https://user-images.githubusercontent.com/1252593/194208572-83a378b9-1d88-4e78-894f-ef1a2ad5be66.png)

but when I run something like `_tagQuery.GetAllContentTags("BlogTags");`, I get this:

![image](https://user-images.githubusercontent.com/1252593/194209343-72bf5eca-6d06-4f2a-a256-8cfe5f4b6d1b.png)

The two tags have been combined together into a single entry. The ID leads me to believe that for some reason when I have been re-saving these content nodes in the new version, it is saving the combination of tags all together to the database as a single tag entry.

This has happened for all the tags - here is another example:
![image](https://user-images.githubusercontent.com/1252593/194210751-b313e8e6-e36c-48aa-a2b6-988ff39d6202.png)

Also, these concatenated tags are showing up in the Tags UI as type-ahead options:
![image](https://user-images.githubusercontent.com/1252593/194360560-9740a271-e6f4-43b8-bf25-8b00731db067.png)
😣

### Steps to reproduce

1. Create a ContentType with a Tags property (configured with CSV storage)
2. Create a node and add a few tags
3. Save & Publish
4. Via code, run the `_tagQuery.GetAllContentTags()`, method and view the returned TagModels

### Expected result / actual result

I would assume that for the tags in my example the result would show a single entry for "announcements" with a NodeCount of 4+ and no entry for a concatenated version "announcements,code".

---
_This item has been added to our backlog [AB#23073](https://dev.azure.com/umbraco/243e7927-03b2-44e2-908f-d4ac7ea5daaa/_workitems/edit/23073)_

**Comment by nikolajlauridsen** [comment]
This has been fixed in #13188 and cherry-picked for the 10.3 release, so I'll go ahead and close this, thank you for reporting 🙏

**Comment by hfloyd** [comment]
Thanks for the quick fix, @nikolajlauridsen !
