### ISSUE TITLE
Appsettings.Local.json should be taken into account when running in debug, not only when running debug build of Umbraco

### ISSUE THREAD

**Issue by simonech** [umbraco/Umbraco-CMS#13140]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

10.2.1

### Bug summary

Appsettings.Local.json is taken in consideration only when "developing" Umbraco using the debug build, but not when build your own project (which uses the release build).

### Specifics

In the hostbuilderextension, there is a line of code that conditionally adds the Appsettings.Local.json to the list of config files.

https://github.com/umbraco/Umbraco-CMS/blob/release-10.3.0-rc/src/Umbraco.Web.Common/Hosting/HostBuilderExtensions.cs#L19 

But this is conditional to `#if DEBUG`, which means is only applied when running a debug build of Umbraco.

Not sure if this is intentional (so only an help for developers of Umbraco) or is a bug and was supposed to be available to "integrators" as well.

### Steps to reproduce

- Create a new project
- add an Appsettings.Local.json in the root

### Expected result / actual result

I'd expect the Appsettings.Local.json to be considered, while it's not

It would be cool if this preprocessors conditions would be replaced with runtime evaluation of whether the project using the Umbraco lib is in debug mode.

**Comment by bergmania** [comment]
Hi @simonech.

It's actually intended as it is. I wonder why you think this should leak outside of Umbraco? 

Personally, I never use it anymore, since we got the appsettings.*.json templates, that creates the files if missing.

**Comment by simonech** [comment]
Hi,
it' very convenient to have the possibility of running a local appsettings file, since our development server has different settings than the local dev box.
We ended up writing the same code in our `Program.cs` file anyway.
What do you mean with "appsettings.*.json templates"?

**Comment by bergmania** [comment]
> What do you mean with "appsettings.*.json templates"?

In the CMS project, originally `appsettings.Local.json` was a solution to avoid committing local stuff like connection strings.

Instead we have implemented someting similar to v8, where we have a template file that creates the `appsettings.Local.json` if missing, and then we ignore the `appsettings.Local.json` file from git. An example of the template file is here: https://github.com/umbraco/Umbraco-CMS/blob/v10/contrib/src/Umbraco.Web.UI/appsettings.template.json

**Comment by simonech** [comment]
Ok, thank you.
I don't think I understand how that works, since we'd still have the `appsettings.development.json`. But agreed, not a common scenario. 
Feel free to close it as you prefer
