### ISSUE TITLE
SendingContentNotification - Unable to set default value

### ISSUE THREAD

**Issue by leventefabry-mof** [umbraco/Umbraco-CMS#13169]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

version 10.2.1

### Bug summary

I tried to set up default value for dropdown (Umbraco.DropDown.Flexible) based on this article:

https://our.umbraco.com/documentation/reference/Notifications/EditorModel-Notifications/#usage

However, if I set the .Value property in the code like in the article above it doesn't have an affect on the property.
Other properties seemed to be working.

Thanks in advance for the help.

### Steps to reproduce

The code snippet that I use:

**The handler:**

```csharp
public class EditorSendingContentNotificationHandler : INotificationHandler<SendingContentNotification>
{
    public void Handle(SendingContentNotification notification)
    {
        if (notification.Content.ContentTypeAlias.Equals(FaqsModule.ModelTypeAlias))
        {
            foreach (var variant in notification.Content.Variants)
            {
                if (variant.State == ContentSavedState.NotCreated)
                {
                    var paddingSizeTop = variant.Tabs.SelectMany(f => f.Properties).FirstOrDefault(f => f.Alias.InvariantEquals("paddingSizeTop"));
                    if (paddingSizeTop is not null)
                    {
                        // set default value of the publish date property if it exists
                        paddingSizeTop.Value = "Small";
                        paddingSizeTop.Label = "LABEL";
                        paddingSizeTop.Description = "DESCRIPTION";
                    }
                }
            }
        }
    }
}
```

**The composer to register:**
```csharp
public class NotificationHandlerComposer : IComposer
{
    public void Compose(IUmbracoBuilder builder)
    {
        builder.AddNotificationHandler<SendingContentNotification, EditorSendingContentNotificationHandler>();
    }
}
```

**The datatype config:**
```xml
<?xml version="1.0" encoding="utf-8"?>
<DataType Key="9ffd583d-0e2b-4430-983b-6d7e43c16f65" Alias="Large-Small Toggle" Level="1">
  <Info>
    <Name>Large-Small Toggle</Name>
    <EditorAlias>Umbraco.DropDown.Flexible</EditorAlias>
    <DatabaseType>Nvarchar</DatabaseType>
  </Info>
  <Config><![CDATA[{
  "Items": [
    {
      "id": 1,
      "value": "Large"
    },
    {
      "id": 2,
      "value": "Small"
    }
  ],
  "Multiple": false
}]]></Config>
</DataType>
```

### Expected result / actual result

![image](https://user-images.githubusercontent.com/104758603/195085212-69a6417b-6082-4248-bdcc-35017954ad30.png)

Show the value from the code.

**Comment by patrickdemooij9** [comment]
Hi @leventefabry-mof 
The dropdown expects an string[] as value, not just a string. If you change your code to `paddingSizeTop.Value = new string[] {"Small"};`, it'll work as expected

**Comment by leventefabry-mof** [comment]
Hello @patrickdemooij9,

Thanks for the response, I tried your code but it's still not working correctly.
The code I tried:
`
public class EditorSendingContentNotificationHandler : INotificationHandler<SendingContentNotification>
{
    public void Handle(SendingContentNotification notification)
    {
        if (notification.Content.ContentTypeAlias.Equals(FaqsModule.ModelTypeAlias))
        {
            foreach (var variant in notification.Content.Variants)
            {
                if (variant.State == ContentSavedState.NotCreated)
                {
                    var paddingSizeTop = variant.Tabs.SelectMany(f => f.Properties).FirstOrDefault(f => f.Alias.InvariantEquals("paddingSizeTop"));
                    if (paddingSizeTop is not null)
                    {
                        paddingSizeTop.Value = new[] { "Small" };
                        paddingSizeTop.Label = "LABEL";
                        paddingSizeTop.Description = "DESCRIPTION";
                    }
                }
            }
        }
    }
}
`

The result is the same:
![image](https://user-images.githubusercontent.com/104758603/197142524-8505c39d-e130-4e4d-bd10-289bfa8bc36a.png)

**Comment by nikolajlauridsen** [comment]
Hey @leventefabry-mof I just tested this out in 10.3.2 and everything seems to work fine, so I don't think this is an issue in the CMS, I'd recommend asking [on the forums](https://our.umbraco.com/forum/) or maybe even [the discord channel)(https://community.umbraco.com/get-involved/community-discord-channel/), where I'm sure our awesome community would love to help out. 


For now, I'll leave you with the example I used to test this which works well on my end:

Given this picker configuration:

![image](https://user-images.githubusercontent.com/16456704/205937846-abfedcb0-d55b-477d-9422-6068ca4c9d16.png)

And a property with the alias `drop` this worked for me: 

```c#
    public void Handle(SendingContentNotification notification)
    {
        foreach(var variant in notification.Content.Variants)
        {
            if (variant.State == ContentSavedState.NotCreated)
            {
                var property = variant.Tabs.SelectMany(tab => tab.Properties).FirstOrDefault(x => x.Alias == "drop");
                property.Value = new[] { "Value 1" };
            }
        }
    }
```

For now, I'll close this issue 😄
