### ISSUE TITLE
10.3RC: Unable to drag and drop Image block type between block grid areas

### ISSUE THREAD

**Issue by sussexrick** [umbraco/Umbraco-CMS#13176]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

10.3.0 RC

### Bug summary

Documentation says "Blocks can be rearranged using the click and drag feature. Move them up or down to place them in the desired order." This doesn't work with the Image block type in the demo content.

### Specifics

I'm using Firefox Developer 106.0b9 (64-bit) on Windows.

### Steps to reproduce

Create a document type, and a property using a data type with the block grid editor. Use the sample content. Create a page based on that document type. Add an image block and a rich text block in that editor. You can drag and drop the rich text above or below the image, but you can't drag and drop the image above or below the text.

### Expected result / actual result

You can drag and drop the image similarly to the text, or click it to edit it.

**Comment by nul800sebastiaan** [comment]
Granted I'm not on Firefox beta, but I don't see a reason why the next version of firefox would not work either. Am I doing something different than you?

https://user-images.githubusercontent.com/304656/195329764-81152ff5-b624-4144-820b-5531b151351c.mp4

**Comment by sussexrick** [comment]
@nul800sebastiaan Yes I was, but your video actually shows the difference. I didn't realise you had to click and drag the little blue tab. On the rich text block you can click anywhere in the block and drag it to a new position. For an image it only works if you click and drag the tab.

**Comment by iOvergaard** [comment]
Thanks! A fix has been made which will end up in the final release of 10.3.0.
