### ISSUE TITLE
10.3RC: Inconsistent 'new block [list|grid]' layout

### ISSUE THREAD

**Issue by sussexrick** [umbraco/Umbraco-CMS#13174]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

10.3.0 RC

### Bug summary

An empty block grid editor has unwanted space above the 'Add content' button, which is inconsistent with an empty block list editor.

### Specifics

![image](https://user-images.githubusercontent.com/1260550/195205902-9dc678e9-6f12-422d-84b7-aae3500db4bf.png)

### Steps to reproduce

On a blank document type add a block list editor property and a block grid editor property with no further configuration. Create content based on that document type.

I'm using Firefox Developer 106.0b9 (64-bit) on Windows.

### Expected result / actual result

The empty block grid editor would look more like the empty block list editor, without empty space above the 'Add content' button.

**Comment by iOvergaard** [comment]
Thanks! A fix has been made which will end up in the final release of 10.3.0.
