### ISSUE TITLE
Deployments failing with NuCache.Content.db process lock

### ISSUE THREAD

**Issue by techcolin** [umbraco/Umbraco-CMS#13171]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

8.18.2

### Bug summary

Whenever we deploy from Azure DevOps to our Azure App Service, Umbraco is unresponsive for very long time to start (4-5 minutes spinup) and eventually returns a 500 error on all pages.  The error is as below, which we've seen many times in previous versions of Umbraco, but we understand should be resolved by this version.

This also happens during unattended restarts, i.e. when Azure migrates to a new host.  Umbraco is left erroring out during its first startup, but fixes itself after a second restart.

System.IO.IOException: The process cannot access the file 'C:\local\Temp\UmbracoData\49515cd99448dec57f0365b7dfdef5cd\NuCache\NuCache.Content.db' because it is being used by another process.

After we restart the site either by touching web.config or restarting via Azure, Umbraco starts in a sensible time (within 90 seconds) and is perfectly fine.

This is fairly consistent, but only about 90% of deployments.  Very occasionally it works fine.

We have tried to replicate on our staging server (another completely separate App Service), and also on a slot within the same App Service, under a variety of conditions, but were not able to replicate the issue.  We only see it on the production website.

We have read all the articles we can find around Nucache locking, and tried everything, but can't find any way forward.  We're hoping someone can provide us a new route to investigate.

### Specifics

The site is around 3000 pages, with low traffic.

It is hosted on a P1V2 against an S2 database.  

We have tried scaling up to a P2V2 and it makes no difference.  Both App Service and database are under no particular load, athough we do see the App Service go up to 80-90% during first deploy (on a P1V2), it doesn't ever seem to flatline in any way.  The P2V2 tests should very little CPU load at all.

We used to see Thread Timeout Panic Exceptions in a variety of modules during startup, but we increased the httpRuntime ExecutionTimeout to 300 (5 minutes) which seems to have changed the last logged Panic, but not resolved the issue itself.

We have Hangfire running some scheduled imports, however we have been killing any jobs before deploying to ensure no processes are running in the background.

We often see a period of several minutes where nothing is logged at all, after the initial boot sequence logs.  For example, today the following gap is present (the top error is the NuCache error)

<img width="1024" alt="Screenshot 2022-10-11 at 16 23 00" src="https://user-images.githubusercontent.com/40235909/195133357-e1a775f2-84a9-43c6-889c-0820c35a48ba.png">

Beyond this we're stuck.  There's nothing obvious to follow up on.  If anyone has any thoughts we'd be very keen to hear them!
 

### Steps to reproduce

Deploy changes, or redeploy last commit, from Azure DevOps

Restart from Azure (even unattended restart, i.e. host migration)

### Expected result / actual result

Umbraco starts reasonably quickly every time.

**Comment by techcolin** [comment]
We had a major outage on this site on Saturday night after an Azure host migration.  Again Umbraco started booting, but then stopped responding and threw the Nucache error right before the Fatal Panic Exception, then the site was left broken until we were alerted and restarted it.

This is a very unstable instance - can anyone offer us any help here?

<img width="1039" alt="image" src="https://user-images.githubusercontent.com/40235909/199225107-8f336f52-8157-4602-be24-4fefe9be77a7.png">

<img width="1039" alt="image" src="https://user-images.githubusercontent.com/40235909/199225236-bc96fef7-1de2-43db-ae2d-adc062a9c673.png">

**Comment by nikolajlauridsen** [comment]
Hey @techcolin, this sounds like a great discussion [for the forum](https://our.umbraco.com/forum/) but as a bug report, I'm not sure there's much we can do without clear reproduction steps, ideally for v10/11.

**Comment by elit0451** [comment]
Hi @techcolin,

It seems like we haven't heard from you in 14 days and since we were unable to reproduce the issue, I will have to close this bug report for now. Feel free to reopen it if you have more input on the case 😉
