### ISSUE TITLE
10.3RC: Overlapping UI in block grid editor

### ISSUE THREAD

**Issue by sussexrick** [umbraco/Umbraco-CMS#13173]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

10.3.0 RC

### Bug summary

Built-in UI can overlap when creating content in the back office using the block grid editor.

### Specifics

I'm using Firefox 106.0b9 (64-bit) on Windows.

### Steps to reproduce

I started playing with the sample blocks and, not really understanding it yet, I added areas to the Image type. Then I created some content based on my new block grid and ended up with this:

![image](https://user-images.githubusercontent.com/1260550/195204973-d44c7918-724d-4f64-b07c-03ced54527b4.png)

And also this:

![image](https://user-images.githubusercontent.com/1260550/195205040-e3a04c93-1dc9-4fcc-ba11-2dc4be37bc14.png)

The image was added at the root of the block grid. I think area 1 on the image required a headline block, but didn't have one. "Create button on editor" is custom text for the create button at the root of the block grid.

### Expected result / actual result

Built-in UI does not overlap.

---
_This item has been added to our backlog [AB#23297](https://dev.azure.com/umbraco/243e7927-03b2-44e2-908f-d4ac7ea5daaa/_workitems/edit/23297)_

**Comment by nul800sebastiaan** [comment]
Can reproduce similar problems 

![image](https://user-images.githubusercontent.com/304656/195334883-ca15c5cb-89d9-4962-87cb-45382f1427b4.png)

**Comment by nul800sebastiaan** [comment]
I also managed to get to this stage today:

![image](https://user-images.githubusercontent.com/304656/195542645-994c1ca2-96ea-438c-8ece-836ce9999582.png)

**Comment by iOvergaard** [comment]
Should be fixed now on the release branch and the fix will end up in the final version of 10.3.
