### ISSUE TITLE
10.3RC1: 'Show catalogue' and 'Show resize options' is odd UI

### ISSUE THREAD

**Issue by sussexrick** [umbraco/Umbraco-CMS#13177]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

10.3.1RC

### Bug summary

When configuring a block grid editor data type, and you configure a block, catalogue appearance and resize options are initially hidden.

### Specifics

Before clicks:
![image](https://user-images.githubusercontent.com/1260550/195210835-d09346db-78a7-461a-9162-782abf841f8e.png)

After clicks:
![image](https://user-images.githubusercontent.com/1260550/195211339-bade9b97-abfe-4b36-bfa5-987099963d6b.png)

### Steps to reproduce

Create a data type using the block grid editor. Use the demo content. Click on a block type.

Two buttons 'Show catalogue appearance' and 'Show resize options' hide some of the UI, which replaces the 'Show' link when it's clicked. There may be good reasons why it's done this way and this may not be categorised as a bug therefore, but it's very unusual UI. I can't think when I've seen a conditional reveal in a dialog that takes up only slightly more space than the trigger button.

### Expected result / actual result

The UI would display as soon as the dialog/overlay is displayed.

**Comment by bjarnef** [comment]
To me I also don't see the requirement to have an extra click to show these configuration. I think it would be tedious to configure blocks if one wanted to set icon and background colors (+1 click each time).

If there is a need to enable/disable these I feel a toggle would be simpler (eventually show/hide these "groups" or just a dimmed layer on top of these configuration options).

**Comment by nul800sebastiaan** [comment]
I think the initial idea was to not overload people with too much information, cluttering the interface with things they might not need yet. 

I'll ask for a bit of clarification of these choices though.

**Comment by bjarnef** [comment]
@nul800sebastiaan maybe the "Catalogue appearance" group should be moved "Advanced" tab then?

If the "Size options" isn't always relevant I would move the up "Allowance" group before this.

![image](https://user-images.githubusercontent.com/2919859/195334016-c26b51ff-6c3a-48fa-8108-7eefb1c89cfd.png)

**Comment by nielslyngsoe** [comment]
What @nul800sebastiaan mentions is the original intention. We are aware it's sort of odd UI, but will keep it for the size options to ensure not overwhelming users. The main reason is for users to be able to ignore and understand that they do not need to consider these options. This would not be the case for all users, but the users who tend to want to understand and consider everything will be able to ignore these options for a start.

So we will keep this for now, until a potentially better solution turns up.

The Catalouge Appearance has been moved to the Advanced tab and the hiding has been removed for this.
