### ISSUE TITLE
10.3.0-RC: Horizontal scroll in Block Grid configuration editor

### ISSUE THREAD

**Issue by bjarnef** [umbraco/Umbraco-CMS#13182]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

10.3.0-RC

### Bug summary

I noticed the configuration overlay in Block Grid editor has some horizontal scroll.

![image](https://user-images.githubusercontent.com/2919859/195298958-9f446123-2eaa-4544-91de-687fc3770d8e.png)

### Steps to reproduce

Notice the horizontal scroll when configuration areas in Block Grid editor.

**Comment by bjarnef** [comment]
@nielslyngsoe just to confirm. It's the scale label causing the overflow scroll.

![image](https://user-images.githubusercontent.com/2919859/196284470-f6f0fbd4-37d8-4319-aab3-a2eaa3a06b31.png)

![image](https://user-images.githubusercontent.com/2919859/196284517-b29f73e3-9471-454d-b4bc-7b84e60ff4c1.png)

A simply fix is to add some right margin (or max width of `.umb-block-grid-area-editor__grid-wrapper`

![image](https://user-images.githubusercontent.com/2919859/196285037-e65545c1-4e17-4bf5-a59a-f8c47f117983.png)

Alternatively it need to dynamically position the label to left, when there is not space enough to the right.

**Comment by nielslyngsoe** [comment]
Hi @bjarnef  Thanks for highlighting this, its been fixed here: https://github.com/umbraco/Umbraco-CMS/pull/13222
