### ISSUE TITLE
Block Grid Editor: Remove column span need a tooltip

### ISSUE THREAD

**Issue by bjarnef** [umbraco/Umbraco-CMS#13187]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

10.3.0-RC

### Bug summary

When configurating the columns in Block Grid editor, it is difficult to distinguish between adding a column span or removing if. Only a tiny white border indicate the column spans and clicking on that is a remove button, which is clear when looking into the DOM.

![image](https://user-images.githubusercontent.com/2919859/195327920-484bc4db-472b-4cae-8952-357d607612ab.png)

I think there should at least be a tooltip or similar to indicate click this remove the column span.

Furthermore when having a column span at 3 and 4 it is difficult to see which one is remove although the background color change, but not the border/divider. Maybe the active one (that is going to be removed on click) should either scale, change color to red or similar to make it clearer that this one the one you will remove on click.

### Steps to reproduce

Notice it is difficult to know how to remove a column span as there is no clear indication on this - as minimum we should have a tooltip.

**Comment by nielslyngsoe** [comment]
@bjarnef makes good sense, I have this on my list. But feel free to solve it if you like :-)

**Comment by iOvergaard** [comment]
Hi @bjarnef, thanks for the feedback. We've had to prioritize issues and have bumped this down the list. We'd love for someone in the community to look at it, so I marked it up-for-grabs!

**Comment by bjarnef** [comment]
@nul800sebastiaan seems the linked PR has been merged now, so I think we can close this one.

**Comment by nul800sebastiaan** [comment]
Yep, thank! Fixed in https://github.com/umbraco/Umbraco-CMS/pull/13939
