### ISSUE TITLE
10.3.0-RC: Areas are not sorted correct after save

### ISSUE THREAD

**Issue by bjarnef** [umbraco/Umbraco-CMS#13189]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

10.3.0-RC

### Bug summary

If I in a block configure the following area in Block Grid editor and save these changes:

![image](https://user-images.githubusercontent.com/2919859/195331042-945e2186-a9bf-4a0a-acfc-50df4321663d.png)

when I then opening the configuration of the block areas I get this:

![image](https://user-images.githubusercontent.com/2919859/195331418-c2c2a868-a958-498d-af35-e9da1381368e.png)

Furthermore I think it is fair to limit the "Grid Columns for Areas" property to e.g. 1000 or similar, because when entering a value like 1.000.000 it requires a lot on allocations in DOM and the browser is hanging.

and the UI isn't optimized for this anyway:

![image](https://user-images.githubusercontent.com/2919859/195333076-7e4f0ece-d415-4a2b-96ff-4c000b5c31f3.png)

### Steps to reproduce

Add areas to a block as shown above, click submit and save datatype. When reopening the areas are arranged different.

**Comment by nul800sebastiaan** [comment]
Hmmm, I've been trying to break this one but I'm having a tough time. I see some other weird behavior as to where new areas appear after I've dragged areas around but that's not an actual data loss problem.

Any steps I can do to get it to forget the layout you've built?

**Comment by bjarnef** [comment]
@nul800sebastiaan yeah, it doesn't seem to be a data loss, just the areas are arranged different after submit + save ... and then re-opening the overlay.

It tested in on 10.3.0-RC. so it may be better with recent changes :)

Furthermore could we limit the number in the input for "Grid Columns for Areas"? Any good reason we should enter more than 1000? I know we should be careful not to restrict too much (a typical example are regex validations limiting users to enter their name, a valid email etc), but in this case the UI doesn't work well with a large number and the browser it using a lot of memory to do the calculations 🥵

**Comment by nul800sebastiaan** [comment]
Yeah we have 2 issues in one here! But we'd be happy to see a quick PR to limit that to.. I don't know, even a 1000 seems to much? 500 columns, would you ever have that? Not sure what number makes sense here. I think it's to start "low", like 100 and then if people have good reasons to go higher we can always adjust the number later.

**Comment by bjarnef** [comment]
@nul800sebastiaan yeah, that's what I am thinking. Maybe @matthew-darby could look at this as part of https://github.com/umbraco/Umbraco-CMS/pull/13203

**Comment by nielslyngsoe** [comment]
Hi @bjarnef 
I tried to replicate, it but I didn't succeed.. this saved just fine:

![image](https://user-images.githubusercontent.com/6791648/196173257-74da7d68-dcc8-4db3-8a30-d5e012e20e04.png)

Could you try again, maybe describe in detail what you do to make it happen?

**Comment by bjarnef** [comment]
@nielslyngsoe I tested with latest changes in `v10/contrib` which now contain the Block Grid editor as well.

However I am seeing issues, where I can't drag areas, the console returns "Sortable is not defined".

![image](https://user-images.githubusercontent.com/2919859/196232017-d76859cf-3592-49bc-982a-2fa59bc4aaa4.png)

**Comment by nielslyngsoe** [comment]
@bjarnef okay, good. Thanks :-)

Then we can close this one, right?
