### ISSUE TITLE
10.3.0-RC: Change input for grid area columns to numeric input

### ISSUE THREAD

**Issue by bjarnef** [umbraco/Umbraco-CMS#13181]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

10.3.0-RC

### Bug summary

I noticed the input to specify number of grid area columns is a regular text input (default 12 columns), but since it expect a numeric value, why not use `<input "type="number" pattern="[0-9]*" min="1" />` or `<input type="text" inputmode="numeric" pattern="[0-9]*" />`

https://user-images.githubusercontent.com/2919859/195296124-a8e83fea-cc1a-4e2b-abc9-830fdd010a67.mp4

### Steps to reproduce

Notice the input for grid area columns is just a regular text input.

**Comment by matthew-darby** [comment]
Solved/merged by https://github.com/umbraco/Umbraco-CMS/pull/13203
