### ISSUE TITLE
10.3.0-RC: Block Grid configuration not possible to remove block navigating keyboard

### ISSUE THREAD

**Issue by bjarnef** [umbraco/Umbraco-CMS#13186]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

10.3.0-RC

### Bug summary

When it comes to accessibility it isn't possible to delete/remove blocks from Block Grid editor navigating the keyboard.

It is the same issue with blocks in Block List editor.

It is however fixed in this PR https://github.com/umbraco/Umbraco-CMS/pull/12851 so maybe we should consider this approach for Block Grid editor as well.

### Steps to reproduce

Notice one can't delete/remove blocks from Block Grid / Block List editor configuration navigating keyboard.

---
_This item has been added to our backlog [AB#24362](https://dev.azure.com/umbraco/243e7927-03b2-44e2-908f-d4ac7ea5daaa/_workitems/edit/24362)_

**Comment by bjarnef** [comment]
@nul800sebastiaan this is fixed in https://github.com/umbraco/Umbraco-CMS/pull/12851 (or similar approach for block grid editor configuration), but it would be great if HQ could review that or if the approach from @nathanwoulfe https://github.com/umbraco/Umbraco-CMS/pull/12851#issuecomment-1217908817 is better.

**Comment by nielslyngsoe** [comment]
This has been fixed as off, that was just not happening through that specific PR. So I will close this issue now.
https://github.com/umbraco/Umbraco-CMS/pull/12851
