### ISSUE TITLE
10.3.0-RC: Default layout looks odd when using demo blocks

### ISSUE THREAD

**Issue by bjarnef** [umbraco/Umbraco-CMS#13183]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

10.3.0-RC

### Bug summary

I tested the demo blocks but when I add Headline and Image it looks like this in backoffice.

![image](https://user-images.githubusercontent.com/2919859/195302263-7aa4cc40-32d3-4c58-a85a-48febcafa986.png)

If I drag the image above text block it looks like this:

![image](https://user-images.githubusercontent.com/2919859/195312206-046a8092-0c6d-4219-ac21-4099fe074dab.png)

### Steps to reproduce

Add Headline and Image to grid content.

**Comment by bjarnef** [comment]
@nielslyngsoe I tested in on 10.3.0-RC, but now I test it again I can't reproduce although it is the same version I test on.
Let's close this and I will raise a new issue if I can reproduce this later.

**Comment by nielslyngsoe** [comment]
@bjarnef super. Thanks. Let me know if you experience anything odd :-)
