### ISSUE TITLE
10.3.0-RC: Column spans not rendered as expected

### ISSUE THREAD

**Issue by bjarnef** [umbraco/Umbraco-CMS#13197]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

10.3.0-RC

### Bug summary

In Block Grid editor I inserted an image block spanning 12 columns, an image spanning 6 columns (force right) and text block spanning 6 columns (force left)

![image](https://user-images.githubusercontent.com/2919859/195518761-bbabb530-0d8e-4de2-88db-e698d89dcffe.png)

However the default block grid renderer return this output.

![image](https://user-images.githubusercontent.com/2919859/195519344-09600121-b142-40d2-913b-9ef815e12edb.png)

I would have expected the images to be rendered inside the container `<div>` elements.
Furthermore in frontend there is no difference in layout between the image spanning 12 columns and 6 columns, but in backoffice they looks different.

### Steps to reproduce

Add an image block spanning 12 columns, adjusted image block to span 6 columns and insert a new one. Furhermore insert rich text spanning 6 columns.

**Comment by iOvergaard** [comment]
@bjarnef Thanks for your report! Would you be so kind as to test it again on the latest release/10.3.0 branch?

**Comment by nielslyngsoe** [comment]
@bjarnef this should be fixed in the 10.3 branches, could you please verify?

Its should be fixed in this PR: https://github.com/umbraco/Umbraco-CMS/pull/13190

**Comment by nul800sebastiaan** [comment]
Looking good now indeed, I found the same problem the other day but it's fixed on the 10.3 branch now 👍 

![image](https://user-images.githubusercontent.com/304656/196132372-0b895ee1-8ef7-4811-aecb-e56fb5a24499.png)

![image](https://user-images.githubusercontent.com/304656/196132377-6dc17c9a-0c8b-4ccf-8ac8-61e65add9df5.png)

And indeed we now get the expected data elements in the markup as well:

![image](https://user-images.githubusercontent.com/304656/196132945-1e52f514-76cb-4f5c-ab55-6d502525bda2.png)

![image](https://user-images.githubusercontent.com/304656/196132947-98c24742-7646-4f28-b31e-c65d727b7735.png)
