### ISSUE TITLE
upgrading from 7.15.3 -> 7.15.9 but lists wrong version in CMS

### ISSUE THREAD

**Issue by ryan-webcoda** [umbraco/Umbraco-CMS#13196]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

7.15.3

### Bug summary

After upgrade to 7.15.9 was complete the CMS lists the Umbraco version in the cms as 7.15.8. Is this a bug?

### Steps to reproduce

install latest v7 packge from nuget and run site

### Expected result / actual result

expected site to list version as 7.15.9

**Comment by nul800sebastiaan** [comment]
This sounds like an excellent question for the forums where our friendly community can help you find the best solution for your requirements. 

Make sure to head on over to https://our.umbraco.com and ask follow up questions there.
