### ISSUE TITLE
10.3.0-RC: Block Grid - editing areas can affect existing content

### ISSUE THREAD

**Issue by nul800sebastiaan** [umbraco/Umbraco-CMS#13219]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

10.3.0 (current `release/10.3` branch)

### Bug summary

When you edit areas on a block element, I've seen content completely disappear or the content I was just editing just never gets saved. I assume this is because whatever is stored doesn't correspond to the new model any more and then we just discard whatever doesn't fit?

### Steps to reproduce

I've made 2 videos, one adding areas to an existing element and then I add new elements which never get saved:

https://user-images.githubusercontent.com/304656/196141970-7271c4a6-77da-4efd-ba44-64ac5ace1163.mp4

And one where I delete existing areas that are in use on existing content, some of the content disappears. I figured I'd do this one without the infinite editor, in case that caused problems, but it's definitely dropping my existing content also if I use the doctype editor independently.

https://user-images.githubusercontent.com/304656/196141981-58d7a04a-20cd-43db-9341-a1e8f33bcc6b.mp4

**Comment by nielslyngsoe** [comment]
(Summery from Slack conversation with Seb)

The second one is the expected result.

The first one I cant seem to replicate, I asked Seb to try again.

**Comment by nielslyngsoe** [comment]
From trying to replicate this I found this bug:
https://github.com/umbraco/Umbraco-CMS/issues/13226

@nul800sebastiaan could you let me know if you see these related?

**Comment by nul800sebastiaan** [comment]
> The second one is the expected result.

Indeed you do get a big red warning that existing blocks will be affected.

And yes infinite editor needs some work it seems to prevent data loss. We'll track on issue #13226 then.
