### ISSUE TITLE
Published pages aren't added to examine external index if one of their cultures is saved, but not published.

### ISSUE THREAD

**Issue by jaandrews** [umbraco/Umbraco-CMS#13240]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

10.2.1

### Bug summary

A published page is not being added to the external index.

### Specifics

It works if only one culture has any saved data or if both cultures are published. It only has issues when one is published and the other is saved, but not published.

### Steps to reproduce

1. Configure umbraco to support English and Spanish.
2. Create a new page named "About" and publish it in English.
3. Switch to the Spanish version and save it (don't publish it).
4. Go to the examine tab in the settings section and search for "about" on the external index.

### Expected result / actual result

My expectation is that the page would be in the external index, since it has been published for one variant. This does not happen though.

Do note that the internal index does behave as expected. It's only the external index that is having issues.

**Comment by nikolajlauridsen** [comment]
Thanks for reporting 🐛 😄 

This has been fixed in #12669
