### ISSUE TITLE
Page Not Found page does not work after installing Umbraco

### ISSUE THREAD

**Issue by nikolajlauridsen** [umbraco/Umbraco-CMS#13247]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

10.3.0/11.0.0-rc1

### Bug summary

The 404 page does not work after installing Umbraco until you restart the site. 

### Specifics

After you've just installed Umbraco you won't get redirected to the default 404 page if you try to go to a page that does not exist, instead, you get an `ERR_TOO_MANY_REDIRECTS` this does, however, go away and everything works as intended after you reboot the site, so in the grand scheme of things it's not too big an issue. 

![image](https://user-images.githubusercontent.com/16456704/196936899-953c2dcd-0be1-4864-ab21-41e94d83fce3.png)

Interestingly the "No Nodes Found" page still works, so to see the error you have to publish a piece of content, otherwise, you'll just get redirected to the "No Nodes Found" page.

### Steps to reproduce

1. Run a fresh site and install Umbraco but DON'T restart the site 
2. Create any piece of routed content
3. Try to go to a page that does not exist

### Expected result / actual result

Expected result: A 404 page should be shown 

Actual result: an `ERR_TOO_MANY_REDIRECTS` occurs

**Comment by bergmania** [comment]
Wonder if this is because the installer still kicks in somehow

**Comment by nikolajlauridsen** [comment]
Possibly related to #13309 which is marked as sprint candidate, so I'll hold off doing too much with this one

**Comment by nikolajlauridsen** [comment]
Fixed in #13551
