### ISSUE TITLE
Block List Editor textbox field validation issue

### ISSUE THREAD

**Issue by aldermore-seandooley** [umbraco/Umbraco-CMS#13258]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

10.2.0

### Bug summary

Possible issue with textbox fields with regular expression validation inside a Block List Editor, throwing validation errors even though the value entered is valid.

### Steps to reproduce

Add a URL slug regular expression `^[a-z0-9]+(?:-[a-z0-9]+)*$` to a textbox field being used in a Block List Editor.

<img width="245" alt="bug_validation_01" src="https://user-images.githubusercontent.com/110114365/197206147-83fdb931-621f-4d30-bc72-3094aa549552.png">

Edit a page which includes the Block List Editor and relevant field.

The below screenshot is a valid slug so should pass validation.

<img width="395" alt="bug_validation_02" src="https://user-images.githubusercontent.com/110114365/197206153-b901f979-ccb4-4783-b1b3-3738ec7e7eb5.png">

The below screenshot is a valid slug so should pass validation.

<img width="396" alt="bug_validation_03" src="https://user-images.githubusercontent.com/110114365/197206160-dbe20811-3a19-4eae-9a3a-48a81a52594e.png">

The below screenshot is an invalid slug so should fail validation.

<img width="395" alt="bug_validation_04" src="https://user-images.githubusercontent.com/110114365/197206162-8426b437-1b97-42da-b841-ef9f97a59f24.png">

Validation errors are being highlighted for all of the above fields.

<img width="776" alt="bug_validation_05" src="https://user-images.githubusercontent.com/110114365/197206166-7419f5f3-0895-471a-bacb-bcd1cba2530a.png">

<img width="397" alt="bug_validation_06" src="https://user-images.githubusercontent.com/110114365/197206171-5e040578-e8f1-4028-99c5-466ce83ead7e.png">

<img width="395" alt="bug_validation_07" src="https://user-images.githubusercontent.com/110114365/197206179-1d96137e-27f9-4dca-bbff-34be6675166f.png">

Adding the regular expression to a textbox field outside of a Block List Editor, and the validation works as expected.

<img width="502" alt="bug_validation_08" src="https://user-images.githubusercontent.com/110114365/197207923-cd96f811-2cf8-4782-b49e-c4386b346aeb.png">

<img width="502" alt="bug_validation_09" src="https://user-images.githubusercontent.com/110114365/197207929-20b2700b-e00e-4b84-b423-12af1c010cd7.png">

### Expected result / actual result

In the test scenario the regular expression `^[a-z0-9]+(?:-[a-z0-9]+)*$` should provide the following results

## Expected result

| Value                   | Status |
|--------------------|--------|
| tabs-residential   | Pass    |
| tabs-commercial | Pass    |
| tabs_buytolet      | Fail      |

## Actual result

| Value                   | Status |
|--------------------|--------|
| tabs-residential   | Fail    |
| tabs-commercial | Fail    |
| tabs_buytolet      | Fail    |

**Comment by nikolajlauridsen** [comment]
Hey @aldermore-seandooley I'm sorry, but I can't reproduce, it works just fine if I try and do the same thing, even if I use your Regex.

![image](https://user-images.githubusercontent.com/16456704/205650100-34a029d9-efaa-4bd7-a465-e6d94bf152d0.png)

**Comment by DeMaxOnline** [comment]
I have the same issue.

**Version**
 10.3.2

**Problem**
When adding a custom validation, I get my custom error back even though it is correct. When I tried to reproduce this bug myself, however this seems hard to as i tried it 2 times and in both times it worked fine.

<img width="241" alt="rgex" src="https://user-images.githubusercontent.com/46966668/208375263-1404eff0-d63c-47d2-81d5-fd24dcedad7f.PNG">

<img width="381" alt="Capture" src="https://user-images.githubusercontent.com/46966668/208375266-e93cbe91-2c11-4b30-88ff-f8609f175c83.PNG">

**Comment by DeMaxOnline** [comment]
Seems to be a problem with caching of some sort. 

**Steps**

1. Add regex that gives an error
2. Trigger an error
3. Change regex to allow all
4. Same error occurs again
5. Restart umbraco
6. Now it works

**Comment by elit0451** [comment]
Hi @aldermore-seandooley and @DeMaxOnline 👋 

I've tried to reproduce the validation issue on the current latest of Umbraco 10 (_10.3.2_) and as you can see in the video, the behaviour is as expected...

> **Note**:
> One thing to note: _Make sure you don't have a space after_ ❗ 😅 as adding a space after (from, for example, copying the text from this issue) will make it fail as the regex doesn't except a space


https://user-images.githubusercontent.com/21998037/208680052-880244d5-c0b9-460d-8dc1-ffce8ee0b05d.mp4

**Comment by nikolajlauridsen** [comment]
Hey all, unfortunately we've been unable to reproduce this, and haven't heard back in 14 days, so I'll have to close this for now, but do please let us know if you have any more information regarding how we may reproduce this, and we'll have another look 😄
