### ISSUE TITLE
Saving a custom Media Type errors in Umbraco 10

### ISSUE THREAD

**Issue by Wiggee11** [umbraco/Umbraco-CMS#13256]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

10.1.1

### Bug summary

Trying to save a custom Media Type throws javascripts errors and fails to populate the default umbraco values (width, height etc).

### Specifics

```
angular.js:13692          POST https://localhost:44319/umbraco/backoffice/umbracoapi/media/PostSave 500
(anonymous) @ angular.min.js?d=32d1d6c6515b1ade5100e8fc9c44a900c06f4f9d:114
s @ angular.min.js?d=32d1d6c6515b1ade5100e8fc9c44a900c06f4f9d:109
(anonymous) @ angular.min.js?d=32d1d6c6515b1ade5100e8fc9c44a900c06f4f9d:107
(anonymous) @ angular.min.js?d=32d1d6c6515b1ade5100e8fc9c44a900c06f4f9d:141
$digest @ angular.min.js?d=32d1d6c6515b1ade5100e8fc9c44a900c06f4f9d:153
$apply @ angular.min.js?d=32d1d6c6515b1ade5100e8fc9c44a900c06f4f9d:156
(anonymous) @ angular.min.js?d=32d1d6c6515b1ade5100e8fc9c44a900c06f4f9d:200
dispatch @ jquery.min.js?d=32d1d6c6515b1ade5100e8fc9c44a900c06f4f9d:2
v.handle @ jquery.min.js?d=32d1d6c6515b1ade5100e8fc9c44a900c06f4f9d:2
angular.js:15697 TypeError: Cannot read properties of undefined (reading 'length')
    at Object.getAllProps (umbraco.services.min.js?d=32d1d6c6515b1ade5100e8fc9c44a900c06f4f9d:formatted:558:65)
    at Object.reBindChangedProperties (umbraco.services.min.js?d=32d1d6c6515b1ade5100e8fc9c44a900c06f4f9d:formatted:663:99)
    at umbraco.controllers.min.js?d=32d1d6c6515b1ade5100e8fc9c44a900c06f4f9d:formatted:2583:58
    at angular.min.js?d=32d1d6c6515b1ade5100e8fc9c44a900c06f4f9d:141:454
    at m.$digest (angular.min.js?d=32d1d6c6515b1ade5100e8fc9c44a900c06f4f9d:153:67)
    at m.$apply (angular.min.js?d=32d1d6c6515b1ade5100e8fc9c44a900c06f4f9d:156:484)
    at k (angular.min.js?d=32d1d6c6515b1ade5100e8fc9c44a900c06f4f9d:107:445)
    at v (angular.min.js?d=32d1d6c6515b1ade5100e8fc9c44a900c06f4f9d:113:40)
    at y.onload (angular.min.js?d=32d1d6c6515b1ade5100e8fc9c44a900c06f4f9d:113:464) 'Possibly unhandled rejection: {}'
```
![umbraco 10 media type bug](https://user-images.githubusercontent.com/32468062/197178333-f17efa73-7c4e-4a5c-b29a-51945f2ebfcc.png)

### Steps to reproduce

1. Create a new Media Type which has a media picker property as well as the default properties as defined in the documentation - https://our.umbraco.com/documentation/Fundamentals/Data/Creating-Media/#creating-a-media-type
```
umbracoFile
umbracoWidth
umbracoHeight
umbracoBytes
umbracoExtension
```
The new Media Type is saved successfully.
2. Go to the Media section and create a new item based on the new Media Type.
3. Select an image for the `umbracoFile` property
4. Save
5. An error will be thrown in the console
6. The image value will be saved but the default properties (width, height, bytes, extension) are not populated and the media item has no link/URL
7. I have tried with the default properties in a separate tab, all properties in a single tab and all properties in a group, all of which result in the same error
8. Initially I also had an additional textarea property on the custom Media Type and that value saved also, just not the default image values/URL

### Expected result / actual result

When creating a new Media item based on a custom Media Type with the default Umbraco properties and additional properties (default Umbraco data types) should save all values correctly, but does not.

Media item is saved without default Umbraco properties populated or link/URL.

**Comment by Wiggee11** [comment]
Further to this, if I refresh the page and re-save, I get a "Media saved: Media saved without any errors" notification, not javascript error and the default Umbraco properties are still NOT populated.

**Comment by Wiggee11** [comment]
Anyone else experiencing this issue?

Anyone at HQ able to replicate/comment? We need a resolution for a live application.

**Comment by elit0451** [comment]
Hi @Wiggee11,

Since we haven't heard from you in more than 14 days and we were unable to reproduce the issue you described, we would have to close this issue. Feel free to reopen it if you are able to provide us with more details 🙂
