### ISSUE TITLE
Accessibility - CMS User Groups - 'Empty Button' Errors for the 'Default Permissions'

### ISSUE THREAD

**Issue by Truealex4** [umbraco/Umbraco-CMS#13251]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

8.18.2

### Bug summary

When I run the WAVE accessibility checker tool, powered by Webaim (https://wave.webaim.org/) on any of the User Group pages there are 15 multiple errors returned for 'Empty Buttons'. These errors relate to the radio buttons for the 'Default Permissions'.

![image](https://user-images.githubusercontent.com/98405431/196982027-cc5b80e9-1bec-4a6e-9b81-29f8ddb81db0.png)

### Specifics

What It Means
A button is empty or has no value text.
Why It Matters
When navigating to a button, descriptive text must be presented to screen reader users to indicate the function of the button.
How to Fix It
Place text content within the <button> element or give the <input> element a value attribute.

### Steps to reproduce

This is how to recreate the issue

1. Access the CMS
2. Select 'Users' from Nav
3. Select 'Groups' tab
4. Select any user group
5. Run the WAVE webaim accessibility checker

### Expected result / actual result

No errors returned on page

**Comment by Truealex4** [comment]
[like]  Alex Lovell reacted to your message:
________________________________

**Comment by mikecp** [comment]
Closed per merging of PR 14919.
