### ISSUE TITLE
SQL Lite error when user language is set to Swedish

### ISSUE THREAD

**Issue by SimonToxic** [umbraco/Umbraco-CMS#13260]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

10.4.0-rc.preview.18

### Bug summary

If you change the user backoffice language to swedish, you get an error when trying to create a new document type and when trying to save content.
If you change back to english it works again. Tried german as well to see if it affected other languages as well and that worked too. 

### Specifics

The error i get when trying to save a document type och content:
![image](https://user-images.githubusercontent.com/107621020/197228184-e3951894-aa4c-4e59-99e6-7a9751394a75.png)

### Steps to reproduce

1. Change user language in backoffice to swedish.
2. Try to create a new Document type.
3. Get SQL Error.

### Expected result / actual result

Change user language to swedish.
Be able to save document type.

Actual:
Change user language to swedish.
Get SQL Lite error when trying to save document type.

---
_This item has been added to our backlog [AB#23503](https://dev.azure.com/umbraco/243e7927-03b2-44e2-908f-d4ac7ea5daaa/_workitems/edit/23503)_

**Comment by bergmania** [comment]
Just a note. This could be related the the swedish "-" as we have seen so often.

**Comment by nikolajlauridsen** [comment]
Fixed in #13284, thanks for reporting 🙌
