### ISSUE TITLE
"Change database" button starts install

### ISSUE THREAD

**Issue by patrickdemooij9** [umbraco/Umbraco-CMS#13316]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

Latest v11/contrib branch

### Bug summary

Trying to create a new database, but every time that I click on the "Change database" button on the install screen, it'll just start installing on SQLLite without giving me the ability to change it.

![image](https://user-images.githubusercontent.com/11466511/198371251-c93ed9aa-aae5-482b-9108-aeda3ce630e3.png)

### Steps to reproduce

Latest v11/contrib branch and leave your connectstring empty to start a new install.

### Expected result / actual result

Should allow me to set up a different database instead of installing

**Comment by patrickdemooij9** [comment]
I think this might be caused by the button not having a type and therefore submitting the current install form. Making it a type=button doesn't submit, but does show an error in the console.

**Comment by Zeegaan** [comment]
@patrickdemooij9 I no longer can reproduce this, is it safe to assume this has been resolved? 😁

**Comment by elit0451** [comment]
@patrickdemooij9 since we haven't heard from you and we cannot reproduce this, I will close the issue. Feel free to reopen it if it is still a problem 🙂
