### ISSUE TITLE
Umbraco Getting Started Content Dashboard Page Not loading

### ISSUE THREAD

**Issue by stewart-southwell** [umbraco/Umbraco-CMS#13315]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

10.3.2

### Bug summary

I helped a client do an Umbraco 10 upgrade.   Everything was mostly fine except the Getting Started page on the Content Dashboard would not load.   I had him upgrade his Umbraco 10 to version 10.3.2.  After he did that the default dashboard for the page loads but he gets a 404 on the images.   In addition the API call to get the remote dashboard content returns a 200 OK  response but the JSON payload is invalid and not able to be parsed.

### Specifics

The API operation that is failing is the following:  
`umbraco/backoffice/umbracoapi/dashboard/GetRemoteDashboardContent?section=content`

After upgrading to 10.3.2 the call returns a 200 OK but the JSON was not able to be parsed as you can see from the screenshot below.

When I run the same codebase on my machine it works fine.  I can't create issue.  It is worth noting that we were both logged in as admin users with permissions to everything.

![image](https://user-images.githubusercontent.com/42212376/198364297-2905fca0-21a2-4e64-b032-f48d775505c8.png)

![image](https://user-images.githubusercontent.com/42212376/198364564-69778ba2-2742-4c83-98ae-42fda15e53ca.png)

### Steps to reproduce

I can't seem to reproduce it on my machine.  Just wondering if anyone has any insights on what the issue is.  

### Expected result / actual result

To figure out why it is not able to load the remote dashboard content (why is the JSON response broken up)

And if the remote dashboard content is not able to be loaded why does the fallback default dashboard  not able to find the images.

**Comment by Zeegaan** [comment]
I'll close this, for now, let us know if you have a good way to reproduce it, and then we can have another look! 
I do however suspect its a firewall blocking `dashboard.umbraco.com` or some other IP blocking 🤔
