### ISSUE TITLE
Erroneous characters returned by UmbracoAuthorizedApiController

### ISSUE THREAD

**Issue by alecd** [umbraco/Umbraco-CMS#13317]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

10.3.1

### Bug summary

Anything I returned from a method on a UmbracoAuthorizedApiController has a string of erroneous characters prepended to the response data.  For example, the following code...:

`return Ok(publishedUrlProvider.GetUrl(id));`

...returns this:

`)]}',
"/articles/example/"`

I have no idea where these characters come from.  It doesn't seem to matter what is returned, I can return `Ok("Hello, World!");` and still see the characters.

### Specifics

I'm testing with Edge browser but I doubt that's relevant.

### Steps to reproduce

Create a controller that inherits from UmbracoAuthorizedApiController in the usual manner.  Add an endpoint and have it return a value, for example, `Ok("Hello, World!");`.  The returned payload contains erroneous characters.

### Expected result / actual result

One would expect the payload to contain only what I asked it to, with no erroneous characters.

**Comment by KevinJump** [comment]
Hi, 

this is intended, it's part of the way AngularJs (and other frameworks) work to protect from Cross Site scripting attacks. 

when using AngularJs (which is what the Umbraco backoffice is using)- the $http service strips these characters before parsing the json. see (https://docs.angularjs.org/api/ng/service/$http#json-vulnerability-protection)

I am not 100% sure this is still needed in the api (and might well go when Umbraco move to a new framework in v13) - but i suspect its not going anywhere for now.

**Comment by alecd** [comment]
Thanks for this info.  I've 'worked around' this by using angular's $http service for the ajax call rather than jquery.  I'll dump the code here in case anyone else (like future me) needs it.  Note this requires that $http be injected into the controller.
`
angular.module('umbraco').controller('ApproveSubmittedRecipePluginController', function ($scope, $http) {
    $scope.getFoo = function () {
        if (confirm('Are you sure you want to Approve this Recipe?  This action does NOT save any changes.')) {

            var fooId = $scope.$parent.$parent.node.id;

            $http({
                method: 'GET',
                url: `/umbraco/backoffice/api/submittedrecipe/approve?id=${fooId}`
            }).then(function successCallback(response) {
                $scope.model.value = response.data;
            }, function errorCallback(response) {
                console.log(response);
            });
        }
    };
});
`

**Comment by Zeegaan** [comment]
I will close this for now, as @KevinJump mentions, this is intended behavior 👍 
And yes, it is going to be removed for v13 😊
