### ISSUE TITLE
Unable to get document Name and other properties if in a service based on RecurringHostedServiceBase and 'Allow vary by culture' is true 

### ISSUE THREAD

**Issue by milanio** [umbraco/Umbraco-CMS#13334]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

10.3.2

### Bug summary

When executing `PerformExecuteAsync` of a service based on `RecurringHostedServiceBase` you can resolve and use UmbracoContextReferrence and then use UmbracoContext.Content to query for content.
However, if content type you query for has '_Allow vary by culture_' set to true you will only be able to query for it via "*" language and `Name` property will still be `null`.

Example code:
```CSharp
public override async Task PerformExecuteAsync(object? state)
        {
            //Culture is the same as default language - in my case "en-GB"
            var culture = Thread.CurrentThread.CurrentCulture;
            //Ensuring UICulture is the same a Culture (on this machine I will get CurrentUICulture = en-US)
            Thread.CurrentThread.CurrentUICulture = culture;

            using var context = contextFactory.EnsureUmbracoContext();
            //if 'Allow vary by culture' is true then homepage will be null
            //if 'Allow vary by culture' is false then homepage will not be null and it will contain name & title etc.
            var homepageDefaultLanguage = context.UmbracoContext?.Content?.GetAtRoot().OfType<HomePage1>().FirstOrDefault();
            
            var homepage = context.UmbracoContext?.Content?.GetAtRoot("*").OfType<HomePage1>().FirstOrDefault(); 
            //if 'Allow vary by culture' is true you can get homepage!=null but it's name or title will be null
            var homepagName= homepage?.Name;
            var homepageTitle= homepage?.Title;

            //Content which does not have 'Allow vary by culture' works as expected
            var shared = context.UmbracoContext?.Content?.GetAtRoot().DescendantsOrSelf<IPublishedContent>().Select(a => a.Name).ToArray();
        }
```

The problem is exactly the same for a background thread started with Task.Run....

### Specifics

Debugging session showing incorrect values in `Locals` window

![image](https://user-images.githubusercontent.com/2590486/199111659-b4cf285b-bebd-4ff5-a810-78048ae4679a.png)
 

### Steps to reproduce

I've created a simple MRE inside this Repo: https://github.com/milanio/Umbraco-MRE-ContentQueryBackgroundThread 

If you want to build it from scratch then:
1. Create Umbraco project
2. Create at least 2 Document Types - 1 with 'Allow Vary by Culture' = true and 1 with 'Allow Vary by Culture' = false
3. Create a service based on RecurringHostedServiceBase and try to query for content inside `PerformExecuteAsync` 

### Expected result / actual result

I would expect 'Allow Vary By Culture' not to change the way ContentCache results are returned.

Examples:
A. `context.UmbracoContext?.Content?.GetAtRoot().OfType<HomePage1>().FirstOrDefault();` should return existing HomePage1 even if `Allow vary by culture` is set to true
and
B. `context.UmbracoContext?.Content?.GetAtRoot("*").OfType<HomePage1>().FirstOrDefault().Name != null;`

**Comment by milanio** [comment]
It seems there is a working workaround : 
If you set `VariationContext` before calling `EnsureUmbracoContext` in `RecurringHostedServiceBase` will be able to use default culture as in API controllers

```
variationContextAccessor.VariationContext = new VariationContext("en-GB");
using var ctx = umbracoContextFactory.EnsureUmbracoContext();
var rootPages = ctx.UmbracoContext.Content!.GetAtRoot().OfType<Homepage>().ToArray()

//rootPages[0].Name !=null 
```

**Comment by jfsaliba** [comment]
@milanio this issue was a life saver, the order of setting `VariationContext` to a culture _before_ calling `EnsureUmbracoContext` was the key. 

@Zeegaan even if HQ says this is supposedly intended behaviour, this needs to be better documented for both `RecurringHostedService`s and in docs about [Language Variants](https://docs.umbraco.com/umbraco-cms/10.latest/tutorials/creating-a-basic-website/adding-language-variants) and [Creating a Multilingual Site](https://docs.umbraco.com/umbraco-cms/10.latest/tutorials/multilanguage-setup). Nowhere does it mention the consequences of background hosted services and culture-varying contexts.

**Comment by Zeegaan** [comment]
@jfsaliba I agree, some more documentation would be really helpful 💪 
You can create an issue about some missing documentation on the official UmbraDocs here https://github.com/umbraco/UmbracoDocs/issues.
It would be a great helpt, so we can get some awareness around this missing documentation, and hopefully somebody can then pick it up 😁
