### ISSUE TITLE
Broken Nested Content on umbraco version 8.18.5

### ISSUE THREAD

**Issue by mitraganesh** [umbraco/Umbraco-CMS#13348]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

8.18.5

### Bug summary

After upgrade from v7.15.4 to v8.18.5, all nested content controls return 404 error as per screenshot. Even if created new element type and nested data type but still all controls under nested content return 404. No upgrade error. 
The error is on production server but working fine in my local host. The web server folder and file permissions are set correctly for Umbraco to run from health check. 

![Untitled](https://user-images.githubusercontent.com/42875097/199565636-ad4b351e-fc5d-4c2f-9b34-96974bc09c52.png)

### Steps to reproduce

N/A

**Comment by matthewcare** [comment]
Did you delete the Umbraco related folders from your production server and upload the new ones as part of the upgrade?

**Comment by mitraganesh** [comment]
@matthewcare - Thanks for you quick response.

We fixed that due caching issue on server
