### ISSUE TITLE
Tabs don't show without properties in the initial group

### ISSUE THREAD

**Issue by TRexStark** [umbraco/Umbraco-CMS#13342]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

10.3.2

### Bug summary

I'm not sure if this is intended or whether it's a bug, as it wasn't happening in previous minor versions.

If you create a document type and added a tab to it, you have the option to add properties into the initial (unnamed/untitled) group (not sure what you call that) and/or create a Group with its own name and title with properties under it.

Currently, if you have a tab with NO properties in that initial group, the tab does not show in the node in the content tree.

here's a test with screenshot.

I created a DocType with 2 Tabs; the first one has a Group of properties without having any properties in the first Tab Group

The second tab has a property in the tab's initial group.

<img width="1011" alt="Screenshot 2022-11-02 at 2 56 36 pm" src="https://user-images.githubusercontent.com/70106895/199392312-ce0171e0-9331-4e16-afba-92f9a6c5e8d9.png">

<img width="1017" alt="Screenshot 2022-11-02 at 2 56 46 pm" src="https://user-images.githubusercontent.com/70106895/199392542-f1478e92-d357-4700-bf9e-033fb051e4b9.png">

In the Content Tree you can only see the Second tab
<img width="853" alt="Screenshot 2022-11-02 at 2 56 59 pm" src="https://user-images.githubusercontent.com/70106895/199394549-e0cd3b7d-b2ef-40e9-93ca-6d758de8decc.png">

Now going back to DocType and doing a reorder by moving the property from the Group to that Tab's initial group, saving etc etc...
<img width="1014" alt="Screenshot 2022-11-02 at 3 17 46 pm" src="https://user-images.githubusercontent.com/70106895/199394715-abda0fd4-1eef-4e6e-a5f3-05aa20c78560.png">

Only now you can see the first tab
<img width="852" alt="Screenshot 2022-11-02 at 3 18 42 pm" src="https://user-images.githubusercontent.com/70106895/199394827-b07e69ae-bbdc-4cd4-b9c4-3fe2a5dfa19e.png">

### Steps to reproduce

Please see the summary

### Expected result / actual result

The tab should show regardless whether we have properties in that first group or not ... if this is intended as a feature, I don't think it's viable as it is dictating the structure of content in a specific way which may not always be desirable.

**Comment by Zeegaan** [comment]
Hey @TRexStark, thanks for reporting this! 
I am having trouble reproducing this issue, the tabs show just fine for me 🤔 
Here's my trying to set it up on a clean 10.3.2 install, please tell me if you spot something wrong 😅
![TabsDoesShowWithoutDefaultGroup](https://user-images.githubusercontent.com/70372949/203300064-3fa2a205-9234-4fc2-addb-07dafadbef2c.gif)

**Comment by nikolajlauridsen** [comment]
Hey @TRexStark I'll go ahead and close this issue for now, since we can't reproduce, and haven't heard back for 14 days. 

Please feel free to still comment here if you have more information, and then we can have a look, or create a new issue 😄

**Comment by TRexStark** [comment]
It seems that the issue may be related to a package issue https://github.com/LottePitcher/umbraco-admin-only-property/issues/14
