### ISSUE TITLE
Migrations timeout not adhering to setting in Connectionstring

### ISSUE THREAD

**Issue by niekvanderreest** [umbraco/Umbraco-CMS#13354]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

From 9.0.0 till 9.5.4

### Bug summary

During upgrade of an Umbraco 8.18.5 project to Umbraco 9.5.4 the updater times out after 30 seconds.
Eventouhg the connectionstring has setting "Connection timeout=36000" / "Connect Timeout=36000"

### Specifics

I've spend a lot of time investigating and managed to track the issue down to the migration class: https://github.com/umbraco/Umbraco-CMS/blob/v9/9.5/src/Umbraco.Infrastructure/Migrations/Upgrade/V_9_0_0/MigrateLogViewerQueriesFromFileToDb.cs 

This class calls: Database.InsertBulk(logQueriesInFile); 
The InsertBulk method is a base implementation from NPOCO 4.0.2, and here is actually where I suspect the real problem lies, as the commandTimeout is never set when running commands from the InsertBulk function.

I've build a version of Umbraco.Infrastructure with some extra logging and implementations of the base NPOCO implementation and this results in commands running with the default commandtimeout of 30 seconds. (this does not actually run the command but creates it only the way NPOCO does)

I've attached a screenshot of the logging results 
![npococmdtimeout](https://user-images.githubusercontent.com/28493458/199966629-dfc7d69b-6a17-4715-8c36-ef52151bcf20.png)

### Steps to reproduce

Migrate an Umbraco 8.18.5 database with an empty Umbraco 9 project (any version as of 9.0.0)
Make sure the server or machine running the migration is "slow", as in we need it to timeout on one of the individual insert statements.

### Expected result / actual result

Expected that all queries and commands run with the timeout specified in the connectionstring.
Actual result is that BulkInserts run with the default timeout of 30 seconds.

Als good to know, there is an easy fix:
Instead of using the NPOCO InsertBulk use the UmbracoDatabase.cs BulkInsertRecords.

Database.InsertBulk(logQueriesInFile); -> Database.BulkInsertRecords(logQueriesInFile);

**Comment by crixlis** [comment]
+1

**Comment by nikolajlauridsen** [comment]
Fixed in #13373 Thanks for the PR, H5YR 🎉
