### ISSUE TITLE
Wasn't possible to a get a valid Snapshot

### ISSUE THREAD

**Issue by bjarnef** [umbraco/Umbraco-CMS#13358]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

10.2.1

### Bug summary

On a Umbraco Cloud project we have a notification handler for `ContentCacheRefresherNotification`. However on restore from e.g. Development to Local environment this it hit and break on this line:

```
var propertyAlias = Category.GetModelPropertyType(_publishedSnapshotAccessor, x => x.CategoryCourses)?.Alias;
```

```
-- EXCEPTION ---------------------------------------------------
 (proper exception traces at the end of this log)
System.InvalidOperationException: Wasn't possible to a get a valid Snapshot
----------------------------------------------------------------
```

![image](https://user-images.githubusercontent.com/2919859/200257004-456c98e2-6251-4d57-a161-91af8cbb60a4.png)

![image](https://user-images.githubusercontent.com/2919859/200257233-de8a107c-0681-4fcc-a31f-e4bd340c6f47.png)

When I comment the notification handler in the composer the restore works.

### Steps to reproduce

Add a notification handler hooking into `ContentCacheRefresherNotification` notification.

Access any property using ModelsBuilder model and restore content where the property is used.

```
public class SiteComposer : IComposer
{
    public void Compose(IUmbracoBuilder builder)
    {
        builder.AddNotificationHandler<ContentCacheRefresherNotification, CourseRelationNotification>();
    }
}
```

```
public class CourseRelationNotification : INotificationHandler<ContentCacheRefresherNotification>
{
    private readonly IContentService _contentService;
    private readonly IPublishedSnapshotAccessor _publishedSnapshotAccessor;

    public CourseRelationNotification(
        IContentService contentService,
        IPublishedSnapshotAccessor publishedSnapshotAccessor)
    {
        _contentService = contentService;
        _publishedSnapshotAccessor = publishedSnapshotAccessor;
    }

    public void Handle(ContentCacheRefresherNotification notification)
    {
        foreach (var payload in (ContentCacheRefresher.JsonPayload[])notification.MessageObject)
        {
            if (payload.ChangeTypes.HasType(TreeChangeTypes.RefreshNode) ||
                payload.ChangeTypes.HasType(TreeChangeTypes.RefreshBranch))
            {
                var content = _contentService.GetById(payload.Id);
                if (content == null)
                    continue;

                if (content.ContentType.Alias != Category.ModelTypeAlias)
                    continue;

                // This breaks.
                var propertyAlias = Category.GetModelPropertyType(_publishedSnapshotAccessor, x => x.CategoryCourses)?.Alias;
                
                // Do something here ..
            }
        }
    }
}
```

**Comment by bjarnef** [comment]
Okay, it seems everything works when including this before accessing property value taking `IPublishedSnapshotAccessor` as parameter.

```
using var ctx = _umbracoContextFactory.EnsureUmbracoContext();

var propertyAlias = Category.GetModelPropertyType(_publishedSnapshotAccessor, x => x.CategoryCourses)?.Alias;
```

I guess this is because this is triggered from Deploy in background, while it isn't an issue when publishing from backoffice, which also trigger this notification. @AndyButland

**Comment by bergmania** [comment]
Exactly @bjarnef.. Background threads do not have an umbraco context or snapshot. So you will need to call `EnsureUmbracoContext`

**Comment by bjarnef** [comment]
@bergmania yeah, I guess to publishing didn't run in background or the Umbraco context is available, while the cache on the other hand is refreshed from background, when Deploy restores content.
