### ISSUE TITLE
Images slow at first load

### ISSUE THREAD

**Issue by TimoTielens** [umbraco/Umbraco-CMS#13375]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

10.3.1

### Bug summary

It seems that Umbraco 10 is very slow in rendering new images formats/sizes.

If I call https:/DOMAIN/media/diyjbkro/2387873.jpg?rxy=0.3145363405213034,0.7763157894736842&width=1920&height=859&format=webp&rnd=133119559710500000 Umbraco will serve me the image in 7.91S (174kb) the second time that I call the image it takes 59MS. As you can see it does cost quite some time to render the jpg image to webp version in. Once it's rendered it's pretty fast.

Almost 8 sec is way to much for us and not acceptable.

Media information is:
**Width in pixels** 5472
**Height in pixels** 3648
**Size in bytes** 3866456
**Type** jpg
First call: 7.91S Second call: 59ms

Sure 3.8 MB is maybe a bit bigger but nothing that fancy, but as an test I also used a image of 1.2 MB. This takes 5.9S (so still to long).

Media information is:
**Width in pixels** 2000
**Height in pixels** 1667
**Size in bytes** 1297880
**Type** jpg
First call: 5.9S Second call: 77ms

### Specifics

- Server OS Microsoft Windows 10.0.14393
- Server Framework .NET 6.0.9
- Umbraco Version 10.3.1

### Steps to reproduce

1. Have an image in Umbraco
2.  Call it with a specific focus point https:/DOMAIN/media/diyjbkro/2387873.jpg?rxy=0.3145363405213034,0.7763157894736842&width=1920&height=859&format=webp&rnd=133119559710500000  **Result: it's way to slow**
3. Recall the same URL. **Result: it's quick**
4. Change the focus point in the url https:/DOMAIN/media/diyjbkro/2387873.jpg?rxy=0.1145363405213034,0.7763157894736842&width=1920&height=859&format=webp&rnd=133119559710500000 **Result: it's slow again **
5. Recall the same URL. **Result: it's quick**

### Expected result / actual result

I expect that Umbraco is faster with the conversion. Ofcourse it can take some time but not this much.

**Comment by bergmania** [comment]
This is handled exclusively by ImageSharp, so there is not much Umbraco can do at the moment.

**Comment by Zeegaan** [comment]
As Bjarke mentions there is unfortunately not much we can do about this at the moment 😞 
I will close this for now, thanks for reporting 🐛
