### ISSUE TITLE
Media Picker - upload button disabled

### ISSUE THREAD

**Issue by rosspetev** [umbraco/Umbraco-CMS#13383]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

10.2.0

### Bug summary

The "Upload" button in the "Select media" UI is occasionally disabled for media pickers that have "Start node" set to a particular folder.
It seems to be to do with the fact the picker remembers the last location, which scenario I've used in the steps to reproduce.

![image](https://user-images.githubusercontent.com/12752581/201132030-9ad146dd-1ded-4da1-95ac-43e8a9f29313.png)

![image](https://user-images.githubusercontent.com/12752581/201132425-0e002f99-031f-400b-8baa-b460a576dd32.png)

### Specifics

This can also be reproduced on a fresh Umbraco 10.3.2 install.
For this set up I've also used the Starter kit.

### Steps to reproduce

- Create an Umbraco project 
- Ensure there are at least 2 media pickers set up. At least one of them needs to have a **Start node** set to a folder. For the starter kit I've changed the **Person - Photo - Media Picker** to have its Start node set to the "People" folder.
- Create or edit a page where a media picker **without a start node set** is used (Product, in the starter kit)
- Add / edit the image - this displays the  "Select media" UI. Ensure the location is not "Media/People". Can be "Media/Products" for example.
- Create or edit a page where a media picker **with a start node set** is used (Person, in the starter kit)
-  Add / edit the image - this displays the  "Select media" UI

### Expected result / actual result

Expected:
The UI to have its "Upload" button enabled.
The UI to have its "+" button (folder creation).

Actual:
Upload button is disabled, the "+" button is missing.

---
_This item has been added to our backlog [AB#24491](https://dev.azure.com/umbraco/243e7927-03b2-44e2-908f-d4ac7ea5daaa/_workitems/edit/24491)_

**Comment by Zeegaan** [comment]
Just hopping in here to say I had a go at reproducing this and I could definitely reproduce this!
We have added it to our backlog here [AB#24491](https://dev.azure.com/umbraco/243e7927-03b2-44e2-908f-d4ac7ea5daaa/_workitems/edit/24491)

**Comment by KCTHolman** [comment]
I have found a temporary solution to the issue. If you close the 'Select Media View' and then reopen it, the problem should be resolved. I'm glad to see it's already on the backlog for a permanent fix.

**Comment by amitch17** [comment]
Just encountered this (now on U11), commenting to watch the issue and hope someone picks it up soon.

**Comment by digbyswift-joe** [comment]
This has also been encountered on one of our projects. Umbraco 10.6.1.

**Comment by cheeseytoastie** [comment]
I can recreate this in v12 reliably. 

Took me a while to ensure it always happens (so I can attempt to debug).

Log out - log back in again and the media picker will do the blank out bug again (on first load).

**Comment by cheeseytoastie** [comment]
OK - working with Niels Lyngsø  we have a potential fix!

Issue is around how the folder path is "got" on the initialisation. 


The function gotoFolder(folder)

Has  entityResource.getAncestors that builds the folder path if it's not set (which it isn't on first init) but this isn't on a promise or awaited. 

Modified the code that follows so it can only run once this returns by moving it to a separate function performGotoFolder(folder)


I've tested the following scenarios and it seems to work (without breaking everything). 
1) Media picker with start node set.
2) Media picker without start node
3) User with limited media folders (e.g. can't see the start node). 

Seems to have resolved the issue.

**Comment by nul800sebastiaan** [comment]
Fixed in https://github.com/umbraco/Umbraco-CMS/pull/15115
