### ISSUE TITLE
Large Authentication Cookie breaks Preview functionality

### ISSUE THREAD

**Issue by sean-p-m** [umbraco/Umbraco-CMS#13402]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

10.3.2

### Bug summary

When a user is assigned to a large number of groups and then tries to use the Preview functionality, the functionality does not work as expected:

- When clicking the Preview button on a brand new page, a 404 page is displayed instead of the preview. Example URL: https://xxx.com/umbraco/preview/?id=3514#?culture=en
- When clicking the Preview button on an existing page the most recently published content is only ever displayed no matter what changes are made in the Umbraco back office.

The Preview functionality doesn't seem to recognise that the user is signed in to the backoffice.

### Specifics

There seems to be an issue with the way that Umbraco.Cms.Web.Common.Middleware.PreviewAuthenticationMiddleware handles chunked authentication cookies, i.e. it doesn't :-D

When an authentication ticket is large (for example has a large number of claims = assigned groups in the back office) then ASP.NET Identity automatically splits it up over a number of cookies. But PreviewAuthenticationMiddleware currently assumes the ticket is only in one cookie.

We can use ChunkingCookieManager in PreviewAuthenticationMiddleware to automatically reassemble the cookie for us like this:

`                    var chunkingCookieManager = new ChunkingCookieManager();

                    if (cookieOptions.Cookie.Name != null)
                    {
                        var cookie = chunkingCookieManager.GetRequestCookie(context, cookieOptions.Cookie.Name);

                        if (!string.IsNullOrEmpty(cookie))
                        {
                            AuthenticationTicket? unprotected = cookieOptions.TicketDataFormat.Unprotect(cookie);
                            ClaimsIdentity? backOfficeIdentity = unprotected?.Principal.GetUmbracoIdentity();

                            if (backOfficeIdentity != null)
                            {
                                // Ok, we've got a real ticket, now we can add this ticket's identity to the current
                                // Principal, this means we'll have 2 identities assigned to the principal which we can
                                // use to authorize the preview and allow for a back office User.
                                context.User.AddIdentity(backOfficeIdentity);
                            }
                        }
                    }`

### Steps to reproduce

1. Assign a backoffice user to a large number of groups (we found that 10 would trigger the issue).
2. Login to the backoffice as the user and verify that the authentication cookie is chunked. UMB_UCONTEXT will have a value of **chunks-2** (where 2 is the number of chunks).
3. Create a new page in the back office, Save the page and then click Save and Preview - a 404 page should be displayed instead of the preview.

### Expected result / actual result

- I should be able to Preview a new page and not receive a 404 when clicking the Preview button.
- I should be able to view Previews of draft content on existing pages, and not the last published content.

**Comment by sean-p-m** [comment]
I think I might have a go at pushing in a PR for this one...

**Comment by Zeegaan** [comment]
I think this is related to https://github.com/umbraco/Umbraco-CMS/issues/12315

**Comment by nikolajlauridsen** [comment]
Fixed in #13404, thanks again for the fix @sean-p-m

**Comment by fardeen-hash** [comment]
I am having a problem accessing the cookies in the umbraco preview page. is there any solutions to i was using along it with Signal R all other pages have no problem in getting context but in umbraco preview page it seems to the context to be null.
