### ISSUE TITLE
v11 RC3: Rich Text Editor dropdowns not working in overlay editor

### ISSUE THREAD

**Issue by BrionyMcKenz** [umbraco/Umbraco-CMS#13414]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

11.0.0-rc3

### Bug summary

I tried using the Rich Text Editor demo block on a Block Grid Editor property. The Formats dropdown, bullets dropdown and numbering dropdowns do not open. They also do not work when using a Rich Text Editor block on a Block List property.

### Specifics

Seems to happen only when using the RTE in an overlay editor.

### Steps to reproduce

Created a block grid editor datatype. 
Added it as a property to my homepage doc type. 
Went to the content and added the Rich Text demo block. 
The dropdowns in the RTE don't work (see circled sections in image). 
![image](https://user-images.githubusercontent.com/11334470/201944907-f67475b8-035e-4060-9174-ee34e9c213f7.png)

Added an RTE property on my homepage doc type and the dropdowns work fine.
![image](https://user-images.githubusercontent.com/11334470/201945080-d388ce9f-9882-4a2a-845e-bd3082fc0ca4.png)

The same thing happens when using the RTE in a block on a Block List property.

### Expected result / actual result

Expect the RTE dropdowns to work in the overlay editor as they do when the RTE is used as a standalone property on the doc type.

**Comment by iOvergaard** [comment]
Thanks for reporting. We are looking into it at HQ!

**Comment by iOvergaard** [comment]
We've made a fix for this which will be shipped in the next RC of V11.

H5YR, @BrionyMcKenz !
