### ISSUE TITLE
ContentMovingToRecycleBinNotification not triggering for childnodes

### ISSUE THREAD

**Issue by develoNiklas** [umbraco/Umbraco-CMS#13423]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

10.3.1

### Bug summary

When a node with children is moved to the Recycle Bin, only the entity of the parent node is sent to the ContentMovingToRecycleBinNotification. 

### Steps to reproduce

Create a notification that implements ContentMovingToRecycleBinNotification.

Create a node with children belonging to it.

Delete the parent node

inspect the MoveInfoCollection property of the notification object

Only the parrent node will be there

### Expected result / actual result

I would excpect all the child nodes to also be sent to the ContentMovingToRecycleBinNotification notification. But only the parent node is.

**Comment by NurhakKaya** [comment]
Hi,

I have started working on this issue.

Cheers,

Nurhak

**Comment by Zeegaan** [comment]
@NurhakKaya Any updates on this ? 😁

**Comment by Zeegaan** [comment]
Hey @develoNiklas, looking further into this, It doesn't make sense to pass children in the `ContentMovingToRecycleBinNotification`, as we don't know the children when sending the notification, and it will be a heavy operation to look them up and attach them.

I'd recommend using the IPublishedSnapshotAccessor instead to get the IPublishedContent, and then you can work with the children:

![image](https://user-images.githubusercontent.com/70372949/208912802-9240ee82-6b56-4f02-80ab-4f6dd4451999.png)

Here is my code snippet: 

```
using Umbraco.Cms.Core.Composing;
using Umbraco.Cms.Core.Events;
using Umbraco.Cms.Core.Notifications;
using Umbraco.Cms.Core.PublishedCache;

namespace Umbraco.Cms.Web.UI;

public class MyNotificationHandler : INotificationHandler<ContentMovingToRecycleBinNotification>
{
    private readonly IPublishedSnapshotAccessor _publishedSnapshotAccessor;

    public MyNotificationHandler(IPublishedSnapshotAccessor publishedSnapshotAccessor)
    {
        _publishedSnapshotAccessor = publishedSnapshotAccessor;
    }
    public void Handle(ContentMovingToRecycleBinNotification notification)
    {
        foreach (var content in notification.MoveInfoCollection)
        {
            _publishedSnapshotAccessor.TryGetPublishedSnapshot(out var publishedSnapshot);
            var publishedContent = publishedSnapshot!.Content!.GetById(content.Entity.Id);

        }
    }
}

public class MyComposer : IComposer
{
    public void Compose(IUmbracoBuilder builder) =>
        builder.AddNotificationHandler<ContentMovingToRecycleBinNotification, MyNotificationHandler>();
}

```
