### ISSUE TITLE
Can't delete member using actions when member details popup is open

### ISSUE THREAD

**Issue by Fabian-Hofman** [umbraco/Umbraco-CMS#13465]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

8.18.5

### Bug summary

I'm trying to delete a member by going to the details of the members, selecting actions and then trying to delete the member.
It looks like a popup opens but it is under another popup, so I can't confirm my deletion for this user.

### Steps to reproduce

1. Open Umbraco CMS and login
2. Go to the members section
3. Create a member if none already exists
4. Select the member to go to the details of the member
5. Select "Actions" in the top right corner and then select "Delete..."
6. A popup opens in which you can't delete the member
![image](https://user-images.githubusercontent.com/98958829/203558365-f0ba1dbb-a1c8-4f3e-a5ca-14cc325d35b8.png)

### Expected result / actual result

Popup opens and I can select "Delete" to delete the selected member

**Comment by elit0451** [comment]
Hi @Fabian-Hofman 
I've tried to see if I can reproduce your problem but for me, it works as expected. Here is a video of me trying to delete a member, perhaps you can spot what I am missing 🤷 


https://user-images.githubusercontent.com/21998037/203749562-3e09c03a-d5a5-44de-aba6-61acf92e7eb4.mp4

**Comment by Fabian-Hofman** [comment]
@elit0451 after digging a bit deeper the problem seems to show when we open a Umbraco popup over another sidebar popup creating the dark space over the delete button in the screenshot. It seems to come from a custom plugin within the company so it is on our behalf. Sorry for the misunderstanding and thanks for the quick response :)
