### ISSUE TITLE
Imaging appSetting values are not respected in Umbraco 10

### ISSUE THREAD

**Issue by Wiggee11** [umbraco/Umbraco-CMS#13466]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

10.1.1

### Bug summary

Setting the `BrowserMaxAge` or `Resize.MaxWidth` or `Resize.MaxHeight` appSettings different to default values and they are not respected.

This reproduces https://github.com/umbraco/Umbraco-CMS/issues/12671 as a confirmed issue in Umbraco 10.1.1.

### Steps to reproduce

Set the Umbraco.Imaging appSettings for BrowserMaxAge, MaxWidth and MaxHeight as per [the Umbraco documentation](https://our.umbraco.com/documentation/Reference/Configuration/ImagingSettings/) to `365.00:00:00`, `3000` and `3000` 
respectively.
![imaging app settings](https://user-images.githubusercontent.com/32468062/203566485-14a6d225-68e2-486a-bd2d-535df45972fc.png)

Umbraco Media served by ImageSharp has the default Cache-Control header value of `max-age=604800` which equates to 7 days instead of the 365 specified.
![network cache control](https://user-images.githubusercontent.com/32468062/203566559-ea148cd0-9bf2-448a-aafb-bd249b9ff3f0.png)

You can still request images using URL parameters for larger sizes and images are generated at the requested sizes.
![image 5000](https://user-images.githubusercontent.com/32468062/203566579-c64e9ef4-3113-45ff-a081-aaa7ed1c502d.png)

### Expected result / actual result

ImageSharp should be respecting the BrowserMaxAge appSetting value if specified, instead of always defaulting to the default value.

Generated images should not exceed the maxwidth/height settings.

**Comment by Wiggee11** [comment]
Interestingly, I have now deployed the same code to our Staging environment and it's all working as expected- 365 day cache control header and resizing images to exceed max width/height setting and images max size is returned.
![cache control](https://user-images.githubusercontent.com/32468062/203946499-88575b26-51b7-498a-a0fa-c667ba300184.png)

I would still expect the correct results to appear on localhost, so I don't know whether this is still a bug or an environment issue.

**Comment by Wiggee11** [comment]
Your appSettings and response look good to me...

Did you test the max resize?

**Comment by Zeegaan** [comment]
@Wiggee11 Yea, if i set my height to 3000 it was respected, but 3001 it just returned the normal image, so worked as expected 🤔

**Comment by Migaroez** [comment]
To keep the tracker tidy, I am closing this ticket due to inactivity. We will be happy to reopen it if new information becomes available.

**Comment by DavidArmitage** [comment]
Guys - Wasd looking ay this for hours.
You need to clear the \umbraco\Data\TEMP folder - Probably the MediaCache.
If you dont delete everything in this folder it will be looking in there for the cached file with the previous cache policy assigned to it.
