### ISSUE TITLE
Umbraco copy content with descendants does not preserve sorting order

### ISSUE THREAD

**Issue by denhaandrei** [umbraco/Umbraco-CMS#13464]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

10.3.2

### Bug summary

Hi, 
I'm using late Umbraco 10 and my content editors asked me if there's any possible way to copy nested content items with sorting preserved when they copy their parent item. 

For example, when I copy an item with the structure:

    Parent item
     Nested item A
      Nested Nested Item I
      Nested Nested Item II
      Nested Nested Item III
     Nested item B
     Nested item C

I will get a new item:

    Parent item
     Nested item B
      Nested Nested Item II
      Nested Nested Item I
      Nested Nested Item III
     Nested item A
     Nested item C

### Specifics

Please note, it reproduce for all Umbraco version 10

### Steps to reproduce

1. Create a new Content page: TestSort
2. Create a 3 section for TestSort(order is important!): 
>Nested item B
>Nested item A
>Nested item C
4. Create a 3 page for Nested item B(order is important!): 
>Nested Nested Item II
>Nested Nested Item I
>Nested Nested Item III
6. Sort in TestSort: 
>Nested item A
>Nested item B
>Nested item C
8. Sort in Nested item B: 
>Nested Nested Item I
>Nested Nested Item II
>Nested Nested Item III
10. Copy TestSort(Relate to original - uncheck, Include descendants - checked)

### Expected result / actual result

Actual Result:
The content copied as created without applying new sorting:
> 
    Parent item
     Nested item B
      Nested Nested Item II
      Nested Nested Item I
      Nested Nested Item III
     Nested item A
     Nested item C

Expected Result:
The content copied with the actual applying sorting:
> 
    Parent item
     Nested item A
      Nested Nested Item I
      Nested Nested Item II
      Nested Nested Item III
     Nested item B
     Nested item C

**Comment by ustadstar** [comment]
I am working on this

**Comment by cpolish** [comment]
Hi there, thank you so much for solving this issue in Umbraco 10+.

My team at work are currently using Umbraco 8 for an application we have inherited from another client, and have currently encountered this issue as well.

I was hoping to see if our team could backport this fix to Umbraco 8, but it appears the fix in the linked PR relies on some features introduced in Umbraco 9.

If we wanted to backport this to Umbraco 8, are there any pointers or suggestions on what we should look to do that you guys could suggest? (even a slightly hacky solution will work).
