### ISSUE TITLE
DataType info tab stuck in loading

### ISSUE THREAD

**Issue by SofusMunch** [umbraco/Umbraco-CMS#13479]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

11.0.0-rc5

### Bug summary

The loadRelations() function in DataTypeInfoController is never called, leaving the view stuck in loading. 

This is due to the change adding ng-if="subView.active" in umb-editor-sub-views.html in:

https://github.com/umbraco/Umbraco-CMS/commit/72bdebf419182ead5d48b97aa2a71beb66479555

This means that the "app.tabChange" eventlistener in DataTypeInfoController is never called, since the event has already fired.

### Steps to reproduce

Switch to the info tab on any datatype.

---
_This item has been added to our backlog [AB#24482](https://dev.azure.com/umbraco/243e7927-03b2-44e2-908f-d4ac7ea5daaa/_workitems/edit/24482)_

**Comment by iOvergaard** [comment]
Thanks for reporting. The fix will end up in the final release of v11.
