### ISSUE TITLE
It is not possible select the Language 'Norwegian'

### ISSUE THREAD

**Issue by drpeck** [umbraco/Umbraco-CMS#13471]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

10.2

### Bug summary

I'll be honest this might be a feature request rather than a bug. I'm going with the bug classification because it is a backwards compatibility issue admittedly between major versions.

There is no option to select 'Norwegian' as a language. 'no' is the recommended hreflang value by Google, when providing a single natural language for Norway. It was an option in Umbraco 8.

The cause of this is that 'Norwegian' is no longer a culture provided by CultureInfo since some point between Framework 4.8 and .NET 6. The only official workaround appears to be setting up the Culture on the OS, which isn't possible in Azure App Services.

This creates a backwards compatibility issue, and also an SEO issue.

Can we hard code the addition of Norwegian wherever `CultureInfo.GetCultures(CultureTypes.AllCultures)` is called, or provide an extension to add custom cultures?
For example:

```
 var allOfficial = CultureInfo.GetCultures(CultureTypes.AllCultures);
 var norwegian = new CultureInfo("NO");
 var custom = allOfficial.Concat(new[]{ norwegian });
 foreach(var language in custom.GroupBy(x => x.Name).Select(x => x.First()).OrderBy(x => x.EnglishName)){
 	Console.WriteLine($"{language.EnglishName} ({language})");
 }
```

### Steps to reproduce

Look at the list of available Languages. Norweign is no longer available.

![image](https://user-images.githubusercontent.com/1196047/203761431-1a177dd4-f6dd-44b1-9ef3-7922c4cbe235.png)

In LinqPad 5 (.Net Framework) this code will list 'Norwegian'. In LinqPad 7 (.NET 6/7) it does not.
```
 var allOfficial = CultureInfo.GetCultures(CultureTypes.AllCultures);
 foreach(var language in allOfficial .GroupBy(x => x.Name).Select(x => x.First()).OrderBy(x => x.EnglishName)){
 	Console.WriteLine($"{language.EnglishName} ({language})");
 }
```

### Expected result / actual result

Norweign should be available.

**Comment by drpeck** [comment]
If you'll accept my hardcoded workaround then I'm happy to supply a PR.

It should require additions to:
- https://github.com/umbraco/Umbraco-CMS/blob/b69afe81f3f6fcd37480b3b0295a62af44ede245/src/Umbraco.Cms.ManagementApi/Controllers/Culture/AllCultureController.cs#L25
 - https://github.com/umbraco/Umbraco-CMS/blob/b69afe81f3f6fcd37480b3b0295a62af44ede245/src/Umbraco.Web.BackOffice/Controllers/LanguageController.cs#L39
 
 From `CultureInfo.GetCultures(CultureTypes.AllCultures)` to `CultureInfo.GetCultures(CultureTypes.AllCultures).Concat(new[] { new CultureInfo("NO") })` (although I would do something DRY).

**Comment by elit0451** [comment]
Hi @drpeck 👋 
Since we're querying the cultures directly from the framework, I can confirm that things indeed have changed from .NET Framework to .NET 6/7 - according to this [dotnet issue](https://github.com/dotnet/runtime/issues/66379)
> .NET does not have a culture with code "no"

But this should be fixed in ICU 69 according to their discussion. 🤞 

One thing to note is that Umbraco allows for changing the language name, so if the display name is the problem, you can do something like this:

https://user-images.githubusercontent.com/21998037/203794400-17e8426f-3e56-4788-a617-30f97e77611c.mp4

Else, it seems like the .NET team just aliased `no` to `nb` so you can select `nb` and update to ICU 69 for the problem to be resolved.

**Comment by drpeck** [comment]
NICE @elit0451 ! I did look for a runtime ticket on this, but you found it where I did not. This sounds like the best solution possible at this time. Thank you.

**Comment by elit0451** [comment]
You are welcome 😊 
I am posting a bit more info I got from the team just in case someone else has a similar issue:

Once ICU 69 is out ([latest release page](https://github.com/microsoft/icu/releases)), you'd need to bump the version of the **Microsoft.ICU.ICU4C.Runtime** dependency and update the value of  <code><RuntimeHostConfigurationOption Include="System.Globalization.AppLocalIcu" <b>Value="68.2.0.9"</b> ...</code>

The change has been documented by Unicode, see https://cldr.unicode.org/index/downloads/cldr-39#h.4qzxh49npmc1
So it seems like the recommendation is to use `nb` for now
>_All of the data that was in nb was moved to no._
