### ISSUE TITLE
Block Grid Area nesting when "Allow in areas" is disabled

### ISSUE THREAD

**Issue by cornehoskam** [umbraco/Umbraco-CMS#13480]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

11.0.0-rc5

### Bug summary

The "Allowed block types" validation overwrites the "Allow in areas" permission on the Block Grid Editor.

### Specifics

See Steps to Reproduce

### Steps to reproduce

**Scenario**:
- When working with a Layout specific Block (So one like the Two Column Layout that ships as the Default option for the Block Grid Editor), 
- And the Allow in areas checkbox on the permissions for said block is **disabled**,
- And the 'Allowed block types' on one of the areas from within that Layout is specifically set to allow the the same area to be re-inserted
**Result**:
The disabled "Allow in areas" checkbox on step 2 gets overwritten by step 3, allowing you to nest the Area within an Area.
Not sure if this is intentional behavior to be able to overwrite the checkbox, or if this is unintentional/an edge-case situation, but worth reporting! 🙂

### Expected result / actual result

I would expect it to either:

- Explicitely yell at me for trying to add an area when the permission says it shouldn't be allowed
- Not be able to add the area, even when I added it in the Validation section.
- Have it specified somewhere that the Areas Validation overwrites the initial Permissions of said Block

**Comment by elit0451** [comment]
Hi @cornehoskam 👋 
I've just heard from the team that this is rather the intended behaviour. You are seeing a use case where some blocks are not generally available but only available in specific block areas. 

Perhaps a more explicit formulation would feel more comfortable within your setup? _Something like_:
<img src="https://user-images.githubusercontent.com/21998037/204242287-996239de-875a-4f4c-a2cf-31e8297819b7.PNG" width=60% />
</br>

_As opposed to the current_:
<img src="https://user-images.githubusercontent.com/21998037/204241144-a20dd7e6-5914-4c37-ba31-e3f3cd074ff9.png" width=60% />

**Comment by cornehoskam** [comment]
Hi @elit0451, thank you for the response! Glad to hear it's working as intended. I think making the Info tip something along the lines of your screenshot would be an excellent solution to make it clear what the expected results are! 🙂
Would you like me to make a Pullrequest to change the text to the one you are thinking of?

**Comment by elit0451** [comment]
It will be awesome Corné 💪
