### ISSUE TITLE
Property non-culture specific warning overlapping document culture select

### ISSUE THREAD

**Issue by anth12** [umbraco/Umbraco-CMS#13495]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

11.0.0-rc5

### Bug summary

When editing a document in a non-fallback language, properties that are not culture-specific show a warning "{PropertyName} is shared across all languages". This warning overlaps the document culture selector.

Fallback (EN) language view:
![image](https://user-images.githubusercontent.com/4281124/204495101-85646300-46fe-49ce-9135-54fdbc437730.png)

Non-fallback (FR) language view:
![image](https://user-images.githubusercontent.com/4281124/204495205-23eb87c3-6793-4848-860d-49ec87d83392.png)

### Steps to reproduce

- Add a primary language
- Add a secondary language with a fallback to the primary language
- Create a doc type that has vary by culture enabled
- Add a property in the first position that does **not** vary by culture
- Create an instance of the doc type in the primary lang
- Select the secondry language from the culture selector
- Expand the culture selector
- Hover of the area of the property that does not vary by culture

### Expected result / actual result

Expected:
"{PropertyName} is shared across all languages" alert should render behind the culture select.

Actual:
alert renders above culture select.

**Comment by elit0451** [comment]
Hi @anth12 👋 
Thanks for reporting this bug! I can confirm that when visiting the secondary language and you have more than 2 languages, the warning stands on the way (_as you can see on the video_):

https://user-images.githubusercontent.com/21998037/204501484-5d2b6779-183e-4907-8150-7c1dc6b65349.mp4

</br>
I will mark it as up for grabs for now and perhaps you or someone from the community can help us fix this 😊💪

**Comment by kjac** [comment]
Fix in #13583

**Comment by kjac** [comment]
Closed by https://github.com/umbraco/Umbraco-CMS/pull/13583
