### ISSUE TITLE
Content Picker - path for culture variant is missing

### ISSUE THREAD

**Issue by DrKirk84** [umbraco/Umbraco-CMS#13510]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

10.1.0

### Bug summary

Hello

In our Site with multiple cultures we have some global items, which can be picked with the content picker. The global item has no hostname defined. on the default culture the path is shown under the item name, in all other cultures the path is replaced by a hash "#". In Umbraco 8, the path was displayed for all culture variants. This also happens in the website content 

![Content-Picker-Default-Languag
![content-picker-umbraco-8](https://user-images.githubusercontent.com/84323988/205031021-dbb0a57e-88f9-4e4c-b923-7fe72546accd.jpg)
e](https://user-images.githubusercontent.com/84323988/205030971-10208943-35d6-4778-a917-fd41dcd39be6.jpg)
![Content-Picker-other-Language](https://user-images.githubusercontent.com/84323988/205030991-a319cc10-4af9-415b-a029-cd7e20250e6a.jpg)
Version 8
![content-picker-umbraco-8](https://user-images.githubusercontent.com/84323988/205034272-034c754e-e485-41fb-a8f7-eecde3cf1e16.jpg)

### Steps to reproduce

- use a installation with at least two different languages
- Create a Global Item without hostname, next to the website root/home
- Create any doctype under the global item with culture variants
- Use a content picker, to pick the created item on any doctype

### Expected result / actual result

the path for the picked item should be displayed in all culture variations

**Comment by Zeegaan** [comment]
@DrKirk84 I'm sorry if I'm misunderstanding here, but I think this is intended behavior.
When I pick this in the other language (Danish in my case) I get the behavior you describe.
I do however think this is intended behavior, or we would be routed to different content nodes to the same node.
I have no clue how this would have worked in v8 😅
