### ISSUE TITLE
Rename the title Marketplace to Packages

### ISSUE THREAD

**Issue by dalyUSN** [umbraco/Umbraco-CMS#13514]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

Umbraco 11

### Bug summary

The main navigation bar in the back office still says "Packages". However, when you click all of the wording has now changed to "Marketplace". 

### Specifics

<img width="1600" alt="Screenshot 2022-12-01 at 14 47 57" src="https://user-images.githubusercontent.com/24275922/205091091-4d7d4b51-1a37-4c1e-83ea-23996ee213e3.png">

### Steps to reproduce

Install the latest Umbraco version 11.

### Expected result / actual result

Should the link in the navigation not be changed to "Marketplace"?

**Comment by Zeegaan** [comment]
@dalyUSN The link packages because the marketplace is only 1 content app, whereas the other 2 have to do with strictly packages 👍

**Comment by dalyUSN** [comment]
Thanks for the reply!

However, I would suggest that the title on the left-hand side should be changed to "Packages" then. If you click through the other Context Apps within "Packages" the left-hand side title says "Marketplace" throughout. 

<img width="1600" alt="Screenshot 2022-12-02 at 11 36 32" src="https://user-images.githubusercontent.com/24275922/205284748-5514890e-374d-4c3b-8e8c-3d026dde2845.png">

**Comment by Zeegaan** [comment]
@dalyUSN Yep makes sense to me 👍 I'll reopen this 😁

**Comment by dalyUSN** [comment]
Nice one — cheers!

**Comment by ustadstar** [comment]
I have fixed this in https://github.com/umbraco/Umbraco-CMS/pull/13625

**Comment by Zeegaan** [comment]
Fixed in https://github.com/umbraco/Umbraco-CMS/pull/13625
