### ISSUE TITLE
Changing property readonly via `SendingContentNotification`

### ISSUE THREAD

**Issue by bjarnef** [umbraco/Umbraco-CMS#13545]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

10.3.2

### Bug summary

Via `SendingContentNotification` is it possible to hide tabs, proeperties, etc.

I tried setting the new `Readonly` property, but this doesn't seem to have any effect in the UI?

The picker is still editable:

![image](https://user-images.githubusercontent.com/2919859/206430366-0de964c9-8f60-4c96-a217-81ab5a313275.png)

![image](https://user-images.githubusercontent.com/2919859/206429944-fa8a9851-76ea-4e5d-803f-838affd61401.png)

```
public class EditorSendingContentNotificationHandler : INotificationHandler<SendingContentNotification>
{
    private readonly IBackOfficeSecurityAccessor _backOfficeSecurity;
    private readonly IPublishedContentQuery _publishedContentQuery;
    private readonly IPublishedSnapshotAccessor _publishedSnapshotAccessor;

    public EditorSendingContentNotificationHandler(
        IBackOfficeSecurityAccessor backOfficeSecurity,
        IPublishedContentQuery publishedContentQuery,
        IPublishedSnapshotAccessor publishedSnapshotAccessor)
    {
        _backOfficeSecurity = backOfficeSecurity;
        _publishedContentQuery = publishedContentQuery;
        _publishedSnapshotAccessor = publishedSnapshotAccessor;
    }

    public void Handle(SendingContentNotification notification)
    {
        if (notification.Content.ContentTypeAlias.Equals(CourseArchive.ModelTypeAlias))
        {
            // Hide default listview content app.
            notification.Content.ContentApps = notification.Content.ContentApps.Where(x => x.Alias != "umbListView");
        }

        if (notification.Content.ContentTypeAlias.Equals(Course.ModelTypeAlias))
        {
            var currentUser = _backOfficeSecurity?.BackOfficeSecurity?.CurrentUser;
            if (currentUser == null)
                return;

            if (currentUser?.Groups == null || currentUser?.StartContentIds.HasAny() == false)
                return;

            // ...

            bool found = false;

            // Hide tabs/properties depending on user access.
            if (!found)
            {
                var tabAliases = notification.Content.Variants.First().Tabs
                    .Where(x => x.Alias != "kursusdata")
                    .Select(x => x.Alias)
                    .WhereNotNull()
                    .ToList();

                ReadOnlyProperties(notification.Content, new List<string> { "test" });

                HideTabs(notification.Content, tabAliases);

                HideActions(notification.Content, new string[]
                {
                    $"{ActionUpdate.ActionLetter}",
                    $"{ActionUnpublish.ActionLetter}",
                    $"{ActionPublish.ActionLetter}",
                    $"{ActionToPublish.ActionLetter}",
                    $"{ActionRollback.ActionLetter}",
                    $"{ActionDelete.ActionLetter}"
                });
        }
    }

    private static void ReadOnlyProperties(ContentItemDisplay contentItemDisplay, List<string> propertyAliases)
    {
        if (propertyAliases.Any())
        {
            foreach (var tab in contentItemDisplay.Variants.First().Tabs)
            {
                List<ContentPropertyDisplay> properties = new();

                foreach (var prop in tab.Properties!)
                {
                    if (propertyAliases.Contains(prop.Alias))
                    {
                        prop.Readonly = true;
                    }

                    properties.Add(prop);
                }

                tab.Properties = properties;
            }
        }
    }

    private static void HideActions(ContentItemDisplay contentItemDisplay, string[] actions)
    {
        contentItemDisplay.AllowedActions = contentItemDisplay.AllowedActions?.Where(x => !actions.Contains(x));
    }

    private static void HideTabs(ContentItemDisplay contentItemDisplay, List<string> tabAliases)
    {
        if (tabAliases.Any())
        {
            contentItemDisplay.Variants.First().Tabs = contentItemDisplay.Variants.First().Tabs.Where(tab => !tabAliases.Contains(tab.Alias!) && tab.Properties.HasAny());
        }
    }

    private static void HideProperties(ContentItemDisplay contentItemDisplay, List<string> propertyAliases)
    {
        if (propertyAliases.Any())
        {
            foreach (var tab in contentItemDisplay.Variants.First().Tabs)
            {
                tab.Properties = tab.Properties?.Where(property => !propertyAliases.Contains(property.Alias));
            }
        }
    }

    private static void HideEmptyTabs(ContentItemDisplay contentItemDisplay)
    {
        contentItemDisplay.Variants.First().Tabs = contentItemDisplay.Variants.First().Tabs.Where(tab => tab.Properties.HasAny());
    }
}
```

### Steps to reproduce

Use code above to set `Readonly = true` for a property.

**Comment by dawoe** [comment]
I can confirm this one.

**Comment by bjarnef** [comment]
I noticed I can set the following, but this doesn't really show the existing values selected in MNTP.

```
prop.Editor = "Umbraco.Label";
prop.View = "readonlyvalue";
```

![image](https://user-images.githubusercontent.com/2919859/206443226-264e4fbf-34c2-42e5-8c75-60299860edfa.png)

**Comment by nikolajlauridsen** [comment]
Yep, this reproduces just fine for me as well 👍 I'll be honest, I'm not really well versed enough in the frontend to do more digging, I'm unsure how the readonly is really supposed to work in regards to this 😄

**Comment by bjarnef** [comment]
Maybe @madsrasmussen could help a bit here as I think he added much of the readonly support in property editors in this case Content Picker / MNTP.

**Comment by bjarnef** [comment]
@nikolajlauridsen could you check if the data delivered to frontend is as expected?
For example the button should be disabled: https://github.com/umbraco/Umbraco-CMS/blob/b69afe81f3f6fcd37480b3b0295a62af44ede245/src/Umbraco.Web.UI.Client/src/views/propertyeditors/contentpicker/contentpicker.html#L28

**Comment by bjarnef** [comment]
The open button should also be gone:
https://github.com/umbraco/Umbraco-CMS/blob/b69afe81f3f6fcd37480b3b0295a62af44ede245/src/Umbraco.Web.UI.Client/src/views/propertyeditors/contentpicker/contentpicker.html#L16

but not sure why it handle the logic in view instead of in controller like for `allowEditButton`, `allowRemove` and `allowAdd`.
https://github.com/umbraco/Umbraco-CMS/blob/b69afe81f3f6fcd37480b3b0295a62af44ede245/src/Umbraco.Web.UI.Client/src/views/propertyeditors/contentpicker/contentpicker.controller.js#L169

https://github.com/umbraco/Umbraco-CMS/blob/b69afe81f3f6fcd37480b3b0295a62af44ede245/src/Umbraco.Web.UI.Client/src/views/propertyeditors/contentpicker/contentpicker.controller.js#L168

**Comment by nikolajlauridsen** [comment]
Looking at the response to the request of the content (`GetById`), I can see that `readonly` is indeed set to true in the response, which is what leading me to believe that this is a frontend issue.

![image](https://user-images.githubusercontent.com/16456704/206664532-0c3008c9-1563-46b6-b33d-1e616bea6e44.png)

**Comment by bjarnef** [comment]
@nikolajlauridsen yeah, I also see that here, but the add button in the picker isn't disabled.

![image](https://user-images.githubusercontent.com/2919859/206668643-8acefc2c-c9ba-47b3-bc1e-94fcd851deb8.png)

**Comment by bjarnef** [comment]
@nikolajlauridsen I checked this in default starterkit with latest changes in `v11/contrib` where `$scope.readonly` is false.

```
Readonly: {{readonly}}<br />
Readonly (is true): {{readonly === true}}<br />
```

![image](https://user-images.githubusercontent.com/2919859/206681357-65d81bd9-f0ed-48a5-980f-ff47ae78814e.png)

but the data from `GetById` has `readonly: true`.

**Comment by bjarnef** [comment]
Here it observe `readonly` property but this log `undefined` for all properties here, so `scope.readonly` is set to false.
https://github.com/umbraco/Umbraco-CMS/blob/b69afe81f3f6fcd37480b3b0295a62af44ede245/src/Umbraco.Web.UI.Client/src/common/directives/components/property/umbpropertyeditor.directive.js#L70-L72

![image](https://user-images.githubusercontent.com/2919859/206700963-8e559184-02d3-49ce-8402-5d67b27132eb.png)

I would have expected the value was `true` for `authors` property, but I guess it is because it only set the property based on `!allowUpdate` otherwise `undefined`:
https://github.com/umbraco/Umbraco-CMS/blob/b69afe81f3f6fcd37480b3b0295a62af44ede245/src/Umbraco.Web.UI.Client/src/views/components/content/umb-tabbed-content.html#L24

**Comment by bjarnef** [comment]
@nikolajlauridsen this PR seems to fix it in my use-case https://github.com/umbraco/Umbraco-CMS/pull/13557
