### ISSUE TITLE
Failed to get cultures

### ISSUE THREAD

**Issue by biapar** [umbraco/Umbraco-CMS#13559]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

Umbraco version 10.2.1

### Bug summary

I've this error when I try to add a new language: Failed to get cultures
<img width="957" alt="image" src="https://user-images.githubusercontent.com/661517/206860706-da2a45ca-9237-4255-8b3b-3211d15de42c.png">

### Steps to reproduce

Add a new language

**Comment by kjac** [comment]
Hi @biapar.

I can't seem to replicate this. Do you have anymore info that might help me track down what's causing your error?

Here's what I see when adding a new language:

![add-language](https://user-images.githubusercontent.com/7405322/207047834-275bf89e-dc93-4e33-a68c-d94fabceb02e.gif)

**Comment by biapar** [comment]
I know but I've the error that I putted before.
I tried again and I've the same error.

**Comment by kjac** [comment]
Does the log give any insights?

**Comment by bergmania** [comment]
Please add in the information from "System Infoformation" in the help panel.

Cultures are delivered by the OS, so this can vary on platforms

**Comment by biapar** [comment]
Can be OS indipendent? I think that it’ not a good choice. If I need a language that there isn’t on the hosting????

**Comment by bergmania** [comment]
CultureInfo are by default OS dependent in dotnet. We currently just rely on dotnet. Otherwise we needed a lot of different information about the cultures, like numberformatting etc.

**Comment by biapar** [comment]
And how to solve the problem if on the hosting there is only English and I need the italian or other languages too?

**Comment by kjac** [comment]
@biapar we really need you to provide us more insights in order to help you.

1. Could you please see if any log messages appear in the Log Viewer (under Settings) when this happens?
![image](https://user-images.githubusercontent.com/7405322/208833498-741d981f-0a90-4e2d-aadf-1010e0241043.png)
2. Please copy your system information from the "Help" panel to this issue:
![image](https://user-images.githubusercontent.com/7405322/208833427-f3ab1102-e35f-45cb-bbc4-73c5ad9306ee.png)

**Comment by biapar** [comment]
Hi, I don't see any errors in the logs when this happen.

<html>
<body>


Category | Data
-- | --
Server OS | Microsoft Windows 6.3.9600
Server Framework | .NET 6.0.11
Default Language | en-US
Umbraco Version | 10.2.1
Current Culture | en-US
Current UI Culture | en-US
Current Webserver | IIS
Models Builder Mode | InMemoryAuto
Debug Mode | False
Database Provider | System.Data.SQLite
Current Server Role | Single
Browser | Safari 16.2
Browser OS | MacIntel


</body>
</html>

**Comment by kjac** [comment]
Hi @biapar,

Well that is weird. Nothing from your system specs suggest you should have any issues, and with no log messages to go on, we really have no clue as to what's happening.

The only way forward right now is to create a new install on your server, and see if your problem persists there. I would suggest the following approach:

1. Create a new project locally (https://docs.umbraco.com/umbraco-cms/fundamentals/setup/install/install-umbraco-with-templates) and run the install.
2. Deploy the project to your server (incl. the created SQLite DB).
3. Log in and test if you can create multiple languages.

If this works, then:
4. Copy the DB from your faulty (current) deployment to your new deployment, restart and re-test.

Could you try that and get back to us?

**Comment by biapar** [comment]
I'll try.

**Comment by kjac** [comment]
Hi @biapar,

We haven't heard from you in a while, I hope you managed to solve your issue.

I'm going to close this one as it's going stale. If the problem persists, I hope you can get back to us with your findings from the previous comments.

**Comment by biapar** [comment]
I haven't tried it yet, sorry.

**Comment by engern** [comment]
I am experiencing the same error. No error messages in log view... Umbraco version 11.1.0

**Comment by engern** [comment]
I just tried to run the same project on my dev machine, with the production connection string, and I get no error.

I suspect the problem is related to Windows Server 2012 R2 even if it should be supported according to [Requirements](https://docs.umbraco.com/umbraco-cms/fundamentals/setup/requirements/)..

**Comment by biapar** [comment]
The problem is still here also with Umbraco version 12.1.1

**Comment by bergmania** [comment]
Cultures are provided to .NET by the OS, so you are maybe using a culture that is not supported by the version of Windows 2012R2 you're using.

**Comment by engern** [comment]
Windows Server 2012R2 [reaching end of support in just 1 month](https://learn.microsoft.com/en-us/lifecycle/announcements/windows-server-2012-r2-end-of-support), so I just don't see any reason for anyone to spend much time fixing this error now...
