### ISSUE TITLE
Unpublished nodes not greyed out

### ISSUE THREAD

**Issue by jpinto3488** [umbraco/Umbraco-CMS#13558]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

10.2.1, 10.3.2

### Bug summary

Unpublished nodes are not greyed out in the backoffice the "not-published" class is missing on the LI html object.
See here:
![image](https://user-images.githubusercontent.com/48352698/206756101-e3b54930-1afa-484a-a50d-61294aab9ed0.png)

### Steps to reproduce

1 - Unpublish a node
2 - Look at the node icon in the content tree
3 - Icon is not greyed out

**Comment by jpinto3488** [comment]
Hey @kjac
I did more testing, looks like the problem occurs only when DocTypes have "Allow vary by culture" set as TRUE.
See here:

https://user-images.githubusercontent.com/48352698/207115188-80bd612e-a560-435a-a448-7893c7eb08d6.mp4

**Comment by kjac** [comment]
@jpinto3488 thanks! I can reproduce it now 👍 and I added a fix for it in #13570

**Comment by nikolajlauridsen** [comment]
Fixed in #13570 Thanks for reporting 🐛 🕵️
