### ISSUE TITLE
Multi Url picker links not working when using multiple languages and not allow language variant for links

### ISSUE THREAD

**Issue by kmai-universe** [umbraco/Umbraco-CMS#13576]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

10.3.2

### Bug summary

When adding a Multi Url picker to a document type that have multi language enabled, but the Multi url Picker has not, then links are not working properly.

So if i select a link to some page for the primary default language then it shows the correct link. If i then open the Multi Url picker for another language the link just shows "#". This is also what you get on your pages when showing them in any other language than the default language.

In Danish (default language):
![image](https://user-images.githubusercontent.com/23070515/207557172-d3bafc28-3975-463c-8372-6b9ce3947479.png)

In English:
![image](https://user-images.githubusercontent.com/23070515/207557337-01dd42f1-707f-4dfb-ae94-713a6cce17b3.png)

Then if i open the editor in english i get this:
![image](https://user-images.githubusercontent.com/23070515/207557492-52b7591d-c5bd-4ecc-b79a-5e2e616431d4.png)

So when i render the link in english in the front end the link becomes "#" instead of the proper one shown in image two.

### Steps to reproduce

1. Create a document type with multiple languages enabled
2. Add a Multi Url Picker and disable "Allow vary by culture"
3. Pick a link to a page or element.

### Expected result / actual result

Expected result is the proper language variant link to the content picked.

Ie.

Danish: "/parken/attraktioner/sky trail"
English: "/the park/attractions/sky trail"

**Comment by kmai-universe** [comment]
I now upgraded to Umbraco 11.0.0 and the problem is even worse now.

Now when i click the "shared a cross all languages" EDIT button i cannot click on the Add link button anymore for the primary language. Only if i select one of the other languages for my document type can i click on the Add button. However the problem is then the same as described in my initial post. The links become a "#".

**Comment by kmai-universe** [comment]
Does it have something todo with the following error that i always get when publishing content:

> "The root node {RootNodeName} was published in culture {Culture}, but there's no domain configured for it, this will cause routing and caching issues, please register a domain for it"

**Comment by kjac** [comment]
Hi @kmai-universe,

The "#" is very likely tied to the error you get when publishing. Try adding host names to your root node - i.e. something like this:

![image](https://user-images.githubusercontent.com/7405322/207599543-c71dcdef-2861-4584-8f29-7902a44b83c8.png)

**Comment by kmai-universe** [comment]
Hi kjac,

I have added the danish variant as "/" as this is our primary domain. But the problem persists with the Multi Url picker. When editing the page in danish, the "Add" button for the url picker does not react when clicking on it. When editing in another language it does react, but the url will always be "#" instead og the proper one.

**Comment by kjac** [comment]
Hi again @kmai-universe -- I think you've stumbled upon a bug in V11. It works perfectly fine in V10 (when host names are configured for all languages, so URLs are able to resolve).

I'll dig a little deeper into this today 👍

**Comment by kjac** [comment]
Alright... the multi URL picker quite simply doesn't play nice with the new invariant property editing feature of V11.

I have submitted a fix here: #13586

**Comment by nikolajlauridsen** [comment]
#13586 has now been merged, so I'll go ahead an close this, thanks for reporting 😄
