### ISSUE TITLE
Umbraco NestedContent unset MaxItems is limited to 1000 items

### ISSUE THREAD

**Issue by deenairn** [umbraco/Umbraco-CMS#13585]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

8.16.0

### Bug summary

Whenever a Nested Content has had 1,000 items added, the "Add Content" button is disabled. This does not match the description in the documentation where no limitation is provided.

https://our.umbraco.com/Documentation/Fundamentals/Backoffice/property-editors/built-in-property-editors/Nested-Content/

It can be seen by looking at the angular js code, that the limit is provided. I would suggest re-writing this to avoid the controller setting it to 1,000 and not check for max items if it's unset. It seems reasonable to set minItems to 0, but setting maxItems to a fixed value seems incorrect. See image below.

I can provide a fix if it is agreed it is a valid defect.

![MicrosoftTeams-image (4)](https://user-images.githubusercontent.com/3931242/207844606-681f1416-cc44-4bb1-bb61-f4120291b586.png)

### Steps to reproduce

1. Add a NestedContent to a Document Type
2. Create a new Document Type, do not set MaxItems to a value
3. Add 1000 items
4. Add Content control  is disabled

### Expected result / actual result

Add Content control continues to be enabled, as no limitation has been applied.

**Comment by nul800sebastiaan** [comment]
For reference, it's hardcoded here: https://github.com/umbraco/Umbraco-CMS/blob/v11/contrib/src/Umbraco.Web.UI.Client/src/views/propertyeditors/nestedcontent/nestedcontent.controller.js#L108

**Comment by kjac** [comment]
Hi @deenairn,

One thousand items in a single Nested Content property 🤯 honestly I'm surprised the browser can even handle that 😂 

I'm rather certain that the magic number 1000 was chosen for no other reason than nobody ever suspecting anyone would ever add 1000 items to a Nested Content property. In principle there is no reason why that number couldn't be 10000 or 100000 or anything that is high enough.

Now for the bad news: We do not currently have any plans to release a patch for V8. You are of course more than welcome to submit a fix to V8, but there is no saying how long it'll take to actually make it into a release.

I would recommend you to go a different path and figure out how to partition your Nested Content items across multiple nodes to work around the hardcoded upper limit.

You could of course also submit a fix for V10 (or V11) and plan for a migration from V8 whenever that fix makes it into a new release.

Thoughts?

**Comment by deenairn** [comment]
> Hi @deenairn,
> 
> One thousand items in a single Nested Content property 🤯 honestly I'm surprised the browser can even handle that 😂 
> 
> I'm rather certain that the magic number 1000 was chosen for no other reason than nobody ever suspecting anyone would ever add 1000 items to a Nested Content property. In principle there is no reason why that number couldn't be 10000 or 100000 or anything that is high enough.
> 
> Now for the bad news: We do not currently have any plans to release a patch for V8. You are of course more than welcome to submit a fix to V8, but there is no saying how long it'll take to actually make it into a release.
> 
> I would recommend you to go a different path and figure out how to partition your Nested Content items across multiple nodes to work around the hardcoded upper limit.
> 
> You could of course also submit a fix for V10 (or V11) and plan for a migration from V8 whenever that fix makes it into a new release.
> 
> Thoughts?

I've got a fix for the v11 branch on a fork and will raise a PR shortly for it. 

We're using it for managing settings, and yes, the browser is rather slow when I was doing local testing as well as in our production instance. Only had the patience to get up to 800 and realised I might have been quicker using a test automation tool. 😀

To be honest, I'm happy enough with this solution. It gives me an opportunity to contribute to the project, and there is a workaround (set max items to an even larger number), if a newer version of < 11 is planned the changes can be merged onto those branches at that point. I don't think it's worth a new version of 8 for this change alone. 

Does that sound reasonable?

**Comment by nul800sebastiaan** [comment]
@deenairn Sounds like a plan! I just learned about `Number.MAX_SAFE_INTEGER` (https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/MAX_SAFE_INTEGER), could be useful here!

**Comment by kjac** [comment]
@deenairn that sounds brilliant! Looking forward to your contribution ❤️

**Comment by deenairn** [comment]
@nul800sebastiaan @kjac - I have linked a PR that should fix this issue.

**Comment by kjac** [comment]
Thanks a lot @deenairn 🎉 that's awesome!
