### ISSUE TITLE
Upgrade 8.18.5 -> 11 Unable to login

### ISSUE THREAD

**Issue by PezCo** [umbraco/Umbraco-CMS#13581]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

11.0.0

### Bug summary

Stop me if this shouldn't be possible anyway. advise/links on the best upgrade path would be appreciated.

When trying to upgrade from version 8.18.5 to version 11.0.0 I am unable to login to the admin to preform the DB migration.
8.15.5 -> 10.3.2 does allow logging in and successfully migrated, as far as i am aware again i'm not sure if skipping a version is possible.

i ran the project against a local copy of Umbraco 11 CMS and the error i got was related to `hasAccessToAllLanguages` not existing.

### Steps to reproduce

Upgrade from 8.18.5 -> 11.0.0

**Comment by kjac** [comment]
Hi @PezCo,

That sounds annoying to say the least 😞 

You should "just" be able to upgrade a V8 database to V11. I'll look into this today and report my findings here.

**Comment by kjac** [comment]
Hi again @PezCo,

So... it isn't possible to upgrade directly 😢 you need to go through every major one at a time. This is sorta documented at https://docs.umbraco.com/umbraco-cms/fundamentals/setup/upgrading but not entirely crystal clear. Sorry about that.

The good news: I created a V8.18.5 site and performed upgrades all the way to V11.0 and had no issues logging in along the way 😄 

In your case (going from 8 to 10/11) I will recommend you use a completely barebone Umbraco install when upgrading your database - create a blank project in the next major version, point it at your current DB and let the installer run its course. 

Rinse and repeat until you reach the targeted major. This way you don't risk any custom code interfering with the upgrade process.

If you have any further issues in your upgrade, I will recommend you get in touch with the kind people at the forum: https://our.umbraco.com/forum

**Comment by PezCo** [comment]
@kjac 
> you need to go through every major one at a time.

Im not getting this from the link at all, but ill take your word.
One other question would be Do i need to from the last major version to first minor version each time too?
e.g 8.15.5 -> 9.0.0 -> 9.5.4 -> 10.0.0 -> 10.3.2 -> 11.0.0
in my case?
i ask this because when you get to the upgrade in the admin going from 8.15.5 -> 9.5.4 the report about which version your going from too doesn't seem to know that you are on a previous major version it assumes i'm on 9.0.0

**Comment by kjac** [comment]
Hi there 😄 

You can go straight to the latest major - so 8.15.5 -> 9.5.4 -> 10.3.2 -> 11.0.0

Be sure to check version specific upgrade instructions too: https://docs.umbraco.com/umbraco-cms/fundamentals/setup/upgrading/version-specific
