### ISSUE TITLE
Rich text editor: style_formats not working as intended (certain selectors gets ignored)

### ISSUE THREAD

**Issue by AlexanderWagner82** [umbraco/Umbraco-CMS#13598]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

11.0

### Bug summary

In appsettings.json, when settings RichTextEditor:CustomConfig:style_formats if you have certain selectors (I've noticed "a", ul and "img") that style-item will be ignored. 

### Steps to reproduce

Add this to RichTextEditor:CustomConfig:style_formats in appsettings.json

`"style_formats": "[{\"title\":\"Button\",\"selector\":\"a\",\"classes\":\"button--red\"}]",`

That style will be ignored. But by changing the selector to "p" or "*" the "Button"-style will be available in the styles-dropdown. If I change the selector to "a,p" it works as well (on anchor tags as well).

### Expected result / actual result

That the Button-style should be visible in the styles select-dropdown

**Comment by elit0451** [comment]
Hi @AlexanderWagner82 👋 

It is generally very difficult to set up the Rich Text Editor using the `CustomConfig` key. The key is present only for such a case where we do not support configuration out-of-the-box for TinyMCE. In your case, you could take great advantage of Rich Text Editor styles, which can be set up directly in the backoffice. 

[_Please see our documentation here_](https://docs.umbraco.com/umbraco-cms/fundamentals/backoffice/property-editors/built-in-umbraco-property-editors/rich-text-editor/rte-styles) and let me know if that works for you! 🙂

**Comment by AlexanderWagner82** [comment]
Hi @elit0451 

That's a shame, because setting up the styles-dropdown according to the link you provided is quite basic and you can't do nested sections (see image below). I just found it weird that it worked on Umbraco 9-10 but stopped working on 11. I know that you upgraded tinyMce from 4 to 6 but it's a weird bug that certain selectors work and other doesn't. I couldn't find any breaking changes regarding that in the tinyMce documentations either.

![image](https://user-images.githubusercontent.com/7590126/208670964-20297471-db22-4e78-b2bc-a02668eb3bc9.png)

**Comment by elit0451** [comment]
Alright,
After some investigation and help from a colleague 😁 it seems like setting `style_formats_autohide` to `false` will make it appear in the formats drop-down, like:

```json
  "Umbraco": {
    "CMS": {
      "RichTextEditor": {
        "CustomConfig": {
          "style_formats": "[{\"title\":\"Button\",\"selector\":\"a\",\"classes\":\"button--red\"}]",
          "style_formats_autohide": "false"
        }
      },
      . . .
```

Once you select an "a tag" (_according to your "selector"_) you will be able to pick the Button option 🙂

**Comment by AlexanderWagner82** [comment]
Great! Worked like a charm now!

Thank you for your time.

**Comment by elit0451** [comment]
Awesome 🥳 You are welcome, will go ahead and close this 💪
