### ISSUE TITLE
Child nodes stay in the index after parent node is unpublished 

### ISSUE THREAD

**Issue by Dexter255** [umbraco/Umbraco-CMS#13596]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

10.3.2, also I have added the latest changes for ContentValueSetValidator, and tested with that.
https://github.com/umbraco/Umbraco-CMS/pull/12669

### Bug summary

Child nodes stay in the index when the parent node is unpublished.

### Specifics

No response

### Steps to reproduce

Create a parent node with two language versions, for instance, English (World) and English (US), and Save & Publish both versions.
Create a child node with two language versions and Save & Publish both versions.
Unpublish the parent node, either of the versions.
After searching for the child node under the parent that is unpublished I'm getting that URL is equal to '#'.

### Expected result / actual result

Expected: Child node for the unpublished parent should not stay in the index
Actual: Child node for the unpublished parent stays in the index.

**Comment by dawoe** [comment]
Hi @Dexter255 

This has been fixed and will be part of the upcoming 10.4 release :
https://github.com/umbraco/Umbraco-CMS/pull/12669

**Comment by elit0451** [comment]
Thanks for the update @dawoe 💪 I will go ahead and close this duplicate issue then

**Comment by Dexter255** [comment]
Hi all, sorry for the late reply.
Thanks @dawoe, I'll try to reproduce this once more when 10.4 version is released.
