### ISSUE TITLE
Drag and drop auto-creation of custom media items not working

### ISSUE THREAD

**Issue by jgettrup-ng** [umbraco/Umbraco-CMS#13602]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

10.3.2

### Bug summary

Dragging and dropping an image file into a media folder with custom permissions raises an error message instead of automatically creating a custom image item.

### Specifics

Aim: To create a hierarchy of folders in Media that only allow a custom image type to be uploaded into them. Drag and drop of image files into these folders automatically creates a custom image item.

Issue: This used to work in Umbraco v7 and early versions of v8, but stopped working around v8.14, possibly with the introduction of Media Picker v3. The reason we noticed this issue is because we upgraded a working Media setup using this feature from v8.12 to v8.18 and it stopped working. We have since migrated to v10 and the issue remains.

### Steps to reproduce

• Start with a clean install of Umbraco 10.3.2.
• In Settings > Media Types create a copy of Image called "Custom Image" under Media Types.
• In Settings > Media Types create a copy of Folder called "Custom Folder" under Media Types. Add a group called Contents and a property called Contents with a "List View - Media" editor. (This is needed because the copy of Folder doesn't have the built-in, drag and drop UI of the standard Folder type.)
• Update the permissions on Custom Folder so that the only types it can contain are Custom Folder and Custom Image.
• In Media create an instance of Custom Folder.

• Drag and drop a JPEG image file into the custom folder.
    - Expected behaviour: An instance of Custom Image is created and the file is uploaded into it.
    - Actual behaviour: An error message is displayed saying "Failed: Cannot upload this file, the media type with alias 'Image' is not allowed here".
• While the error message is strictly correct, there is an alternative, permitted media type that would make a perfect substitute. I think that a Custom Image media item should be created automatically since there is only one permitted type (Custom Image) that is functionally equivalent to the built-in Image type, i.e. has an umbracoFile property that allows JPEG file uploads.

• Drag and drop a folder containing a JPEG image file into the custom folder.
    - Expected behaviour: An instance of Custom Folder is created, below that an instance of Custom Image is created and the file is uploaded into it.
    - Actual behaviour: An error message is displayed saying "Cancelled: This file is being uploaded as part of a folder, but creating a new folder is not allowed here".
• This partially worked in v8.12. A standard folder was created (which should not be allowed) and a custom image was created below that (expected behaviour). This could be trickier to fix, since our custom folder only has folder-like behaviour because of its "List View - Media" property, but maybe the presence of that property is enough to signal that this media type is a substitute for Folder.

• Note that I can create a Custom Image or a Custom Folder under a Custom Folder using the Create dropdown button or the Create slide out menu - it’s just drag and drop that doesn't work.

**Comment by elit0451** [comment]
Hi @jgettrup-ng 
Thanks for your detailed "steps to reproduce" 💪 I can indeed confirm that this is still an issue and as you said there is a workaround but the drag-and-drop functionality doesn't work in the described case with custom media items and their permissions!

**Comment by ServiceAtTheValley** [comment]
<bump> 
We encountered this issue as well, and although the workaround works for us too, it is a major annoyance for our (triple A) client. 
Having this on the roadmap would be very helpful.

**Comment by elit0451** [comment]
As mentioned in #14463, there isn't really a good way for us to detect a custom folder type currently.
So the workaround of manually creating the custom folder will be necessary for this case. Dragging and dropping custom types into it will be possible then (_what the PR is fixing_).

We will discuss and try to improve this workflow for the new Backoffice 🙂

**Comment by Zeegaan** [comment]
Fixed in https://github.com/umbraco/Umbraco-CMS/pull/14463
