### ISSUE TITLE
V11 Url.GetCropUrl missing some overloads that existed in V8

### ISSUE THREAD

**Issue by PezCo** [umbraco/Umbraco-CMS#13608]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

11.0.0

### Bug summary

You could use Url.GetCropUrl() like this before

```
var imageUrl = Model.Image.Url() ?? "/images/logos/fallback-image.png";
@Url.GetCropUrl(imageUrl, 600, 500, imageCropperValue: bannerCrop, cacheBusterValue: cacheKey)
```

The overload for using a string for the image is no longer there you can only use PublishedContent.
Funnily enough you can still do it the older way.

```
var imageUrl = Model.Image.Url() ?? "/images/logos/fallback-image.png";
@imageUrl.GetCropUrl(600, 500, imageCropperValue: bannerCrop, cacheBusterValue: cacheKey)
```

is this an oversight? or is one of them wrong.

### Steps to reproduce

Try to use Url.GetCropUrl() with a string rather than PublishedContent

`@Url.GetCropUrl("{string_path_to_image}", 600, 500, imageCropperValue: bannerCrop, cacheBusterValue: cacheKey)`

**Comment by Zeegaan** [comment]
@PezCo I think this is intended, all the method did was do the exact thing you describe, aka "the older way". 🤔 
I'll run it by the team once they get back from holiday just to double confirm, but I'll close this, for now, thanks for reporting 👍
