### ISSUE TITLE
Can't edit macro parameters

### ISSUE THREAD

**Issue by wicketbr** [umbraco/Umbraco-CMS#13603]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

11.0.0

### Bug summary

In Umbraco 11 I can insert a macro into the richedit control. However, once a macro is highlighted the macro button in the toolbar is now greyed out and there is no way to edit the parameters of that existing macro. Right now the only option is to delete the macro and re-insert a macro.

### Steps to reproduce

Add a macro to the richedit control. After the macro has been inserted when you click on the macro the toolbar icon for macros is greyed out and there does not appear to be a way to bring up the macro parameters.

---
_This item has been added to our backlog [AB#25608](https://dev.azure.com/umbraco/243e7927-03b2-44e2-908f-d4ac7ea5daaa/_workitems/edit/25608)_

**Comment by elit0451** [comment]
Hey @wicketbr 👋 

I've managed to quickly reproduce this using [_Umbraco's Starter Kit_](https://www.nuget.org/packages/Umbraco.TheStarterKit). As you can see in the video ⬇️ , this problem only occurs on Umbraco 11 (_in Umbraco 10, it works as expected_). This means it has something to do with the upgrade of the TinyMCE which the Rich Text Editor (RTE) is based on:
> In Umbraco 11 the TinyMCE version supported has been upgraded from version 4 to version 6. (_[link](https://docs.umbraco.com/umbraco-cms/fundamentals/backoffice/property-editors/built-in-umbraco-property-editors/rich-text-editor) for more details_)
</br>


I will mark it as up for grabs for now and see if someone gives it a try. 💪

**Comment by iOvergaard** [comment]
Thanks so much for reporting this. We have a fix ready for this and it will be shipped with Umbraco 11.2.0!

#h5yr
