### ISSUE TITLE
Overlay can't be closed using `esc` key when with interacted property actions

### ISSUE THREAD

**Issue by bjarnef** [umbraco/Umbraco-CMS#13601]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

10.3.2

### Bug summary

When opening an overlay, e.g. infinite editing the overlay can be closed using `esc` key.

However when interacting with property actions inside the overlay this dropdown can be closed using `esc` key, but even several hits on `esc` key it never close the overlay via keyboard.

### Steps to reproduce

Open an overlay with properties, e.g. listview opened in infinite mode and use keyboard to open property actions on a property like MTNP. Close the property action dropdown using `esc` key and furthermore try to close the overlay using `esc` key as well.

It only seems to be an issue as soon the property action dropdown has been opened.

**Comment by elit0451** [comment]
Hey @bjarnef 

I can reproduce the problem as it can be seen in the video 🙂 I'll mark it as up for grabs for now so you or someone else from the community can help us improve the keyboard shortcut flow in this particular case 💪 


https://user-images.githubusercontent.com/21998037/208639896-ee93d6b1-b418-4077-a6d0-c47a7619f443.mp4

**Comment by bjarnef** [comment]
Hi @elit0451 

Yes, it should unbind `esc` on close here, but it seems something is still bound to `esc` key event (or it need to rebind the `esc` key event on overlay).
https://github.com/umbraco/Umbraco-CMS/blob/60765b976c0ac49417c56821035cabae87454b78/src/Umbraco.Web.UI.Client/src/common/directives/components/property/umbpropertyactions.component.js#L52

**Comment by RyuLindow** [comment]
Looking at it during the Bristol hackathon.

**Comment by RyuLindow** [comment]
In my understanding, the [keyboardservice](https://github.com/umbraco/Umbraco-CMS/blob/33adbf41fa1f5c5d0759c70a7116114107addf56/src/Umbraco.Web.UI.Client/src/common/services/keyboard.service.js#L282) listens for every single key on every single element which uses this service making it a global service.

I would imagine that rewriting this is the ideal solution, as this would need to be scoped down but I don't have the experience to do it. Also, not sure how much sense it would make given that we'll be releasing a new backoffice.

I've also noticed that the `Close` button has the `hotkey="esc"` property but the `Remove all items` button doesn't.
![image](https://user-images.githubusercontent.com/56826332/224059169-7ecddb7a-196e-45af-93fd-6551c721737c.png)

This is the property actions dropdown - https://github.com/umbraco/Umbraco-CMS/blob/33adbf41fa1f5c5d0759c70a7116114107addf56/src/Umbraco.Web.UI.Client/src/views/components/property/umb-property-actions.html

By commenting out [this line](https://github.com/umbraco/Umbraco-CMS/blob/60765b976c0ac49417c56821035cabae87454b78/src/Umbraco.Web.UI.Client/src/common/directives/components/property/umbpropertyactions.component.js#L30) I was able to get it to close both the actions and the property editor overlay.

Vid - https://www.dropbox.com/s/ligimbol4vp6em1/brave_5l9D6lgDZT.mp4?dl=0

**Comment by bjarnef** [comment]
I also noticed this happens in Umbraco 12.3.3 if one opens e.g. Media Picker overlay in infinite editing.

It can be tested with the example dashboard in this PR https://github.com/umbraco/Umbraco-CMS/pull/15339 on on the content type opening add a media picker or Block Grid with an image block.

However I noticed if double hit `esc` it does seem to close both overlay - but if waiting a bit after closing the media picker overlay, one seems to be trapped in the infinite overlay, in this case content editor overlay.

**Comment by nielslyngsoe** [comment]
You can upgrade to latest version where this has been fixed.

Therefore and judging from the activity on this issue I will close it. Feel free to still provide a PR that solved this issue if you like, if so please re-open the issue to provide reference.

Thanks in advance
