### ISSUE TITLE
Package Migration - Propertytype is not updated

### ISSUE THREAD

**Issue by BartDM** [umbraco/Umbraco-CMS#13616]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

10.3.2 - 11.0.0

### Bug summary

When updating a propertytype on a documenttype in a package, during package migration the propertytype is not updated in the target Umbraco site

### Specifics

During PackageMigration there is a loop over all propertytypes in the package. When detected the propertytype allready exists, the `UpdateContentTypeProperties<T>` method  is executed. 

https://github.com/umbraco/Umbraco-CMS/blob/05a511a16c59d92d15e30f852973836415253553/src/Umbraco.Infrastructure/Packaging/PackageDataInstallation.cs#L1039

In the `UpdateContentTypeProperties<T>` method the propertytype attributes are replaced with the new values. On line 1148  the `AddPropertyType` method is called tot add the updated propertytype to the contenttype.

https://github.com/umbraco/Umbraco-CMS/blob/05a511a16c59d92d15e30f852973836415253553/src/Umbraco.Infrastructure/Packaging/PackageDataInstallation.cs#L1148

In the `ContentTypeCompositionBase` class  there is a check if the propertytype already exists (what is the case because it's an update) what will return with a false and the propertytype update will not be updated.

https://github.com/umbraco/Umbraco-CMS/blob/b69afe81f3f6fcd37480b3b0295a62af44ede245/src/Umbraco.Core/Models/ContentTypeCompositionBase.cs#L12

https://github.com/umbraco/Umbraco-CMS/blob/b69afe81f3f6fcd37480b3b0295a62af44ede245/src/Umbraco.Core/Models/ContentTypeCompositionBase.cs#L221-L227

The bool return type is not checked in the PackageDataInstallation.

### Steps to reproduce

- Create a documenttype with a propertytype textstring and Regex validation
- Create a Package
- Install the package in another Umbraco website
- Update the created documenttype (change the Regex validation)
- Update the package (updated regex is in the package.xml file)
- Update the package in the Umbraco website
- The Regex value is no updated

### Expected result / actual result

Property types should be updated when updating a package

**Comment by Zeegaan** [comment]
Hey @BartDM thanks for reporting! I can indeed reproduce this, but I question if this is not the correct behavior 🤔 
In our eyes we've already installed the packages, and have edited the value. Why would the package then overwrite the changes we've just made. In my opinion that could cause confusion 😅

**Comment by BartDM** [comment]
Hey @Zeegaan.
As the update logic in the migration is build to update the property types on the document type it seems that we can look at it as a bug.

For sure in our use case. We are building 25 sites on Umbraco. We are creating packages with 'components' the content editors can use to to build the different pages. We can rollout the packages on those 25 sites as they are not depending on each other. Otherwise we are going to have to copy paste every change on 25 different sites.

As last, not only in our use case, as someone builds a product and package it (for example something with a regex to check if the link is a specific link to a product). If they add a new page or new product, they should be able to update the Umbraco package with an updated regex. Otherwise they have to manual inform all customers of the package of the change and the different steps to alter the regex.

**Comment by Zeegaan** [comment]
@BartDM I agree that if adding new content / updating properties we should update.
But where I'm unsure about the UX is this scenario: 
1. I install your package, with a text box with the custom regex.
2. I change your regex because I need something else.
3. You update your regex and the package.
4. I update the package in my project, and it now overwrites my changes from step 2. 

I don't know if we should be overwriting changes already made 😅
Let me know your thoughts and I'll bring it up with the team after the holidays 👍

**Comment by BartDM** [comment]
In our case, the content editors don't have access to the settings and should all data be overwritten with the new data.
But i understand the concerns in other use cases. 

I think there are 2 options.
- A parameter in the PackageMigration where you can set to overwrite data or not -> responsibility with the package creator
- An option for the end user in the Installed Package view where they can choose to overwrite data or not. In that case maybe we could make it required for the package creator to add a Markdown file where he/she can write the changes that will happen if they choose to overwrite the data.  -> responsibility with the end user but more work to implement.

![image](https://user-images.githubusercontent.com/1378733/209784210-b2a5e11c-79f2-434c-b9d0-ac8c8ecdfa56.png)

Regards,

Bart

**Comment by Zeegaan** [comment]
Thanks for the input Bart 👍 I'll bring it up with the team 😄

**Comment by BartDM** [comment]
@Zeegaan did you find the time to discuss with the team?

**Comment by BartDM** [comment]
@Zeegaan did you find the time to discuss with the team?

**Comment by neilsemantic** [comment]
We are also having this issue.  We can work around it for now, but it'll severely limit future updates/rollouts to the sites depending on our packages in the future once we have more than a few actually live...

**Comment by Zeegaan** [comment]
Hi there! Sorry for the late answer, I just came back from vacation 😁 
We took it up internally, and this is by design. We really don't want to overwrite already existing datatype configurations.
So packages do not support your use case, unfortunately. 
However I think your use case could be solved using the package"uSync" instead, here's a link: https://our.umbraco.com/packages/developer-tools/usync/
Hope this helps 🙏

**Comment by neilsemantic** [comment]
Thanks Nikolaj, we use that on most projects, but isn't there a limitation
about not being about to use that on Umbraco Cloud...

Our use-case is -
 - Umbraco Cloud
 - Umbraco baselines project
 - Tens of child projects syncing code from the baseline project

Sorry, I'm not so techie, but I can get the devs to take another look later
on...

**Comment by BartDM** [comment]
Hi @Zeegaan 

I don't understand the "and this is by design". As the source code in the packagemigration has all the logic to update the propertytype, it seems to me that the design was to update the property type.

I can understand with the move to .NET core in V9 and exclusive use of NuGet package that there somewhere a bug got introduced. But to say now, its by design is more a shortcut to not resolve the issue.

In our use case, usync is not a solution. We are not syncing from one environment to another. We are creating package with some data in there, update the data and rolling out new version of the package on 25 different websites. 

You're now saying that you can create a package to reuse document types and content etc on different sites, but we can't rollout new versions because the package migration doesn't update all settings (like propertytypes)?

**Comment by Zeegaan** [comment]
@BartDM I've tried looking into the code, and as far as I'm aware we don't have the logic to update property types (we could overwrite data, thus this is not desirable).
As far as my understanding, the `UpdateContentTypesProperties` method, does that if you add new property types to your document in your packages, those will get added

**Comment by yiscaGi** [comment]
Do you have solution to this problem  that not including using usync?
We are facing the same problem and can not use usync as a solution.
I think that it should be some built in option for that .. every package needs the option to change data types .Our clients know that they shouldn't change our package (data types, document types etc) this is part of the "package" if they will want to change they wont take our updates. By the way most of the time we will add options to existing data type like adding optional block to blocks data type..
