### ISSUE TITLE
INotificationHandler<ContentPublishingNotification> on SetValue of Non varing by culture field

### ISSUE THREAD

**Issue by archimedecreativa** [umbraco/Umbraco-CMS#13610]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

10.2.1

### Bug summary

Using INotificationHandler<ContentPublishingNotification> on a content with permission varying by culture if I SetValue of a property without varying by culture the changes are not published and the content gets set  "Published with Pending Changes". If I publish the content a second time
doing the same thing on a property with varying by culture the Content is published without the problem described.

### Steps to reproduce

Create a document type with permission "varying by culture" and add a property to it without "varying by culture"
Create and register an INotificationHandler<ContentPublishingNotification> and set the value of the property of the content

### Expected result / actual result

When publishing I expect the content to be published with all the changes and I see the changes on the front end.
The actual result is content Published with pending changes and in the frontend, i do not see the changes made programmatically

**Comment by Zeegaan** [comment]
Hey @archimedecreativa I cannot reproduce this 🤔 
Here's my setup: 
- A document type with allow as root & allow vary by culture
- It has 1 property, a textstring, with allow vary by culture set to false
- Heres my notification handler code: 
```
using Umbraco.Cms.Core.Composing;
using Umbraco.Cms.Core.Events;
using Umbraco.Cms.Core.Notifications;

namespace Umbraco.Cms.Web.UI;

public class MyNotiHandler : INotificationHandler<ContentPublishingNotification>
{
    public void Handle(ContentPublishingNotification notification)
    {
        foreach (var content in notification.PublishedEntities)
        {
            foreach (var property in content.Properties)
            {
                if (property.Alias == "title")
                {
                    property.SetValue("Overwritten prop");
                }
            }
        }
    }
}

public class MyComposer : IComposer
{
    public void Compose(IUmbracoBuilder builder) => builder.AddNotificationHandler<ContentPublishingNotification, MyNotiHandler>();
}

```

**Comment by Zeegaan** [comment]
Hey @archimedecreativa As we haven't heard from you in a while, and I could not reproduce this, I will go ahead and close it for now! Don't hesitate to open this again, if you run into the issue again 👍
