### ISSUE TITLE
Infinite Editors and Dialogs conflict

### ISSUE THREAD

**Issue by robertjf** [umbraco/Umbraco-CMS#13623]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

11.0.0

### Bug summary

When editing a Member in infinite editor, then choosing an action for that Member that brings up a dialog, the dialog is unusable.

Case in point:
Selecting a Member that is associated with a content item brings it up in the Infinite editor.  If I try to delete the member using the Actions menu, the controls are obscured:

![delete-dialog-issue1](https://user-images.githubusercontent.com/818101/209931981-b646a87c-33ea-4c5f-91cb-d43975c8a060.gif)

This can also be tested by installing the MemberListView plugin (version 3.0.0 recently released):

![delete-dialog-issue2](https://user-images.githubusercontent.com/818101/209932101-cf9993ba-ef06-4197-934b-8706e4da932c.gif)

It's interesting to note that Members in the Infinite Editor have an Actions menu, while Content Items do not.  Perhaps it should be disabled if this issue can't be fixed?

### Specifics

This happens from Umbraco 8.8.15 right through to Umbraco 11.

### Steps to reproduce

1. Install MemberListView (https://www.nuget.org/packages/MemberListView/) into a new Umbaco installation.
2. Create a new member, then attempt to edit it via the MemberListView
3. Attempt to delete the member from the Actions menu on the top right.

### Expected result / actual result

Either the dialog should become fully interactive when it shows up on top of the infinite editor, or the actions menu for members should be hidden as it is for Content items.

**Comment by Zeegaan** [comment]
Can definitely reproduce this one, I've marked this as up for grabs for now, as we'd love some help with this 🙌
My setup:
- Create Document type with member picker
- Create Member
- Create content with aforementioned document type, and pick newly created member
- Add a content picker property to member type
- Pick the root content.
- Go the content and click the "info" tab
![image](https://user-images.githubusercontent.com/70372949/209955030-6a3c31ee-f85a-4af6-a0ca-0630fd3ff3ec.png)
- Click the member
- Click on actions -> delete

**Comment by robertjf** [comment]
For consistency with other areas of the Umbraco Backoffice, the above PR hides the Action Menu when a Member is being edited in the Infinite Editor.
