### ISSUE TITLE
On server restart, Umbraco wants to update, on click, admin is logged in

### ISSUE THREAD

**Issue by BlagoCuljak** [umbraco/Umbraco-CMS#13629]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

11.0

### Bug summary

I have Umbraco 11 running on Linux Ubuntu. 

After I restart the server, anyone can click to update Umbraco, and after that gets logged into admin page. This is a huge security issue.
![image](https://user-images.githubusercontent.com/34435929/210352918-ec4a07be-de3b-4ff1-ab72-cb9b669abcdc.png)

https://our.umbraco.com/forum/using-umbraco-and-getting-started/110295-on-restart-umbraco-wants-to-update-on-click-admin-is-logged-in

### Steps to reproduce

Restart server, the site display version unknown, and after that you can click and first visitor of your site has admin rights.
![image](https://user-images.githubusercontent.com/34435929/210353076-fc059103-08bf-4be4-a4c6-e48908dcf683.png)

### Expected result / actual result

Tried to have unattended upgrade, but same thing happens.

**Comment by nikolajlauridsen** [comment]
Hey @BlagoCuljak I've just looked at this, and unfortunately, I cannot reproduce it. 

I've tried both Windows and Linux, with no luck, in both cases I don't get prompted to keep upgrading my site, additionally, I've tried to force an update as well, and in this case, I'm still required to log in to be able to authorize the upgrade. 

I'm wondering though why your site is displaying the version as "unknown", and tried to force this as well, but I'm still forced to log in. 

Could it have something to do with how the site is deployed, what database are you using? And how are you deploying it?

**Comment by elit0451** [comment]
Hi again @BlagoCuljak, 

Since we need more information to try to reproduce the issue and we haven't heard from you in two weeks, we would have to close this one. Feel free to reopen it if you are able to provide us with some more information 🙂

**Comment by BlagoCuljak** [comment]
Hi @elit0451 and @nikolajlauridsen I really didn't receive any email from GitHub about mentioning me here, weird.

I still have this issue, database is MSSQL 2019 on Ubuntu 20.04. This keeps happening on entire server restart, and I can reproduce it anytime.

**Comment by elit0451** [comment]
It is good you reached out now then 😁 

Your setup seems alright, so we need to get more specific information to try to reproduce this, like:
> Could it have something to do with how the site is deployed? 
And how are you deploying it?

Also, have you customized the login?
Does it happen locally as well, or only when the site is published?

**Comment by elit0451** [comment]
Locally, you can get the upgrade prompt if you try to update the `Umbraco.Cms` package to 10.4.0 and 11.1.0, respectfully.

**Comment by BlagoCuljak** [comment]
This is my setup:

<html>
<body>


Category | Data
-- | --
Server OS | Linux 5.4.0-137-generic #154-Ubuntu SMP Thu Jan 5 17:03:22 UTC 2023
Server Framework | .NET 7.0.2
Default Language | en-US
Umbraco Version | 11.1.0
Current Culture | en-US
Current UI Culture | en-US
Current Webserver | Kestrel
Models Builder Mode | SourceCodeAuto
Runtime Mode | BackofficeDevelopment
Debug Mode | False
Database Provider | Microsoft.Data.SqlClient
Current Server Role | Unknown
Browser | Firefox 109.0
Browser OS | Win32


</body>
</html>

**Comment by nikolajlauridsen** [comment]
Hey @BlagoCuljak I had another try reproducing this, but unfortunately, with no luck, this time using a published site, but I'm getting the same, and everything works just fine, so I don't really think this is an issue in the CMS.

Maybe something is going wrong with your devops pipeline? perhaps not all artifacts are overridden properly? That might explain why you are getting an "unknown" status, or it might be a database setup thing? Regardless I'm unfortunately unable to reproduce at all. 

For now I'll go ahead and close this issue, but please don't hesitate to comment again if you find a way for use to reproduce, and then we can take a look at it 😄

**Comment by BlagoCuljak** [comment]
@nikolajlauridsen Where can I check Umbraco version in database?

**Comment by nikolajlauridsen** [comment]
The version number of Umbraco is not written to the database, so you can't see the Umbraco version in the database.

However, we do write down the migration state of the database, which you can read out and infer the version from. You can see this state in the `umbracoKeyValue` table in the column with the key 

However, currently (since there were no migrations in 11 or 11.1, the database state for both v10 and v11 are `{3F5D492A-A3DB-43F9-A73E-9FEE3B180E6C}`

**Comment by BlagoCuljak** [comment]
Yes, that's the one in my db also:
![image](https://user-images.githubusercontent.com/34435929/215503651-274fdd0b-0582-469e-a437-e16f4a942a70.png)

**Comment by BlagoCuljak** [comment]
@nikolajlauridsen how about you email me at blago.culjak@hotmail.com from your email, and I will send you artifacts and database?

**Comment by nikolajlauridsen** [comment]
That sounds like a great idea, I've sent you an email, so I'll go ahead and reopen this one for now, while I have a look 😄

**Comment by nikolajlauridsen** [comment]
I had a look at reproducing this today with the provided artifacts and database, but as far as I can tell it all works all right, so since we cannot reproduce I'll go ahead and close this one.


As always do please let us know if you find some reproduction steps, ideally from a fresh site, and then we can have another look at this 😄
