### ISSUE TITLE
TinyMCE strikethrough is not saved in rich text editor

### ISSUE THREAD

**Issue by BillyDigi** [umbraco/Umbraco-CMS#13637]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

11.0.0

### Bug summary

Saving a rich text editor with strikethrough styling does not work.

### Steps to reproduce

- Add rich text field to document type
- Enable strikethrough option
- Insert text and click strikethrough icon
![image](https://user-images.githubusercontent.com/28921505/210559503-ae782493-ae59-4163-9f21-5caf577ba657.png)
- Save document
- Reload document

---
_This item has been added to our backlog [AB#25612](https://dev.azure.com/umbraco/243e7927-03b2-44e2-908f-d4ac7ea5daaa/_workitems/edit/25612)_

**Comment by iOvergaard** [comment]
Thanks for reporting this. It will be patched in 11.2.0.
