### ISSUE TITLE
ASP.NET CORE with .net 7

### ISSUE THREAD

**Issue by Anwar-Thabit** [umbraco/Umbraco-CMS#13643]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

8

### Bug summary

I can't install the Umbraco.core to my ASP.NET CORE version NET v7

### Steps to reproduce

I created the project ASP.NET core with .NET7
Then I tried to install the umbraco.core 
finally I got the error

### Expected result / actual result

Severity Code Description Project File Line Suppression State Warning NU1701 Package 'LightInject.Web 2.0.0' was restored using '.NETFramework,Version=v4.6.1, .NETFramework,Version=v4.6.2, .NETFramework,Version=v4.7, .NETFramework,Version=v4.7.1, .NETFramework,Version=v4.7.2, .NETFramework,Version=v4.8, .NETFramework,Version=v4.8.1' instead of the project target framework 'net5.0'. This package may not be fully compatible with your project. UmbracoCms D:\Umbraco\UmbracoCms\UmbracoCms.csproj 1

**Comment by kjac** [comment]
Hi @Anwar-Thabit,

Umbraco 8 is built upon .NET Framework, it does not support .NET Core. 

Umbraco 9+ is built upon .NET Core:
- Umbraco 9 = .NET 5
- Umbraco 10 = .NET 6
- Umbraco 11 = .NET 7

**Comment by Anwar-Thabit** [comment]
Thanks @kjac
