### ISSUE TITLE
The multi-part identifier "cmsContentType.alias" could not be bound

### ISSUE THREAD

**Issue by wtct** [umbraco/Umbraco-CMS#13660]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

8,9,10

### Bug summary

Hi guys, 

I was trying to use a filter like this:

`var foldersFilter = new Query<IMedia>(_sqlContext).Where(m => m.ContentType.Alias.Equals(Conventions.MediaTypes.Folder));`

in **GetPagedDescendants** method of **MediaService**:

`IEnumerable<IMedia> GetPagedDescendants(int id, long pageIndex, int pageSize, out long totalChildren, IQuery<IMedia>? filter = null, Ordering? ordering = null)`

Unfortunately, this filter throws exception:

> The multi-part identifier "cmsContentType.alias" could not be bound

I have tested it in v8-v11 as a part of testing our [UmbraCare.DedicatedMediaFolder](https://marketplace.umbraco.com/package/umbracare.dedicatedmediafolde) package. 

The same error occurs in all tested versions.

### Steps to reproduce

Try to use the following filter:

`var foldersFilter = new Query<IMedia>(_sqlContext).Where(m => m.ContentType.Alias.Equals(Conventions.MediaTypes.Folder));`

as a filter parameter for **GetPagedDescendants** method available in the **MediaService**:

`IEnumerable<IMedia> GetPagedDescendants(int id, long pageIndex, int pageSize, out long totalChildren, IQuery<IMedia>? filter = null, Ordering? ordering = null)`

**Comment by kjac** [comment]
Hi @wtct,

Thank you for reaching out 😄 

The `GetPagedDescendants` query does not support querying related entities, because the query does not include those entity tables for optimization purposes. In your case you're trying to query the content type, and the SQL mapper tries to tells you that the `cmsContentType` table is not included in the query.

You can only query properties directly on `IMedia` - in your case you can use the `ContentTypeId` provided you fetch the media type first. Here's a working sample:

```csharp
public class MyApiController : UmbracoApiController
{
    private readonly IMediaService _mediaService;
    private readonly ISqlContext _sqlContext;
    private readonly IMediaTypeService _mediaTypeService;

    public MyApiController(IMediaService mediaService, IMediaTypeService mediaTypeService, ISqlContext sqlContext)
    {
        _mediaService = mediaService;
        _sqlContext = sqlContext;
        _mediaTypeService = mediaTypeService;
    }

    // GET /umbraco/api/myapi/getmedia
    [HttpGet]
    public IActionResult GetMedia()
    {
        const string mediaTypeAlias = Constants.Conventions.MediaTypes.Folder;
        const int rootId = Constants.System.Root;

        IMediaType? mediaType = _mediaTypeService.Get(mediaTypeAlias);
        if (mediaType == null)
        {
            return NotFound($"Could not find media type: {mediaTypeAlias}");
        }

        IQuery<IMedia> filter = new Query<IMedia>(_sqlContext).Where(m => m.ContentTypeId == mediaType.Id);
        IMedia[] result = _mediaService.GetPagedDescendants(rootId, 0, 10, out _, filter).ToArray();

        return Ok(result.Select(c => new
        {
            Name = c.Name,
            ContentTypeAlias = c.ContentType.Alias
        }));
    }
}
```

Alternatively you have create your own query repository from scratch, maybe using the `IMediaRepository` implementation as inspiration.

**Comment by wtct** [comment]
Thanks @kjac for clarifying. 

I have already had a workaround with ContentTypeId. However, I was trying to optimize a query and don't use the IMediaTypeService.
