### ISSUE TITLE
Can't upload large files in v10.3.2

### ISSUE THREAD

**Issue by TRexStark** [umbraco/Umbraco-CMS#13675]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

10.3.2

### Bug summary

I have a mp4 file that is 50MB and the PostAddFile request is returning "HTTP Error 413.1 - Request Entity Too Large".

The site is on IIS, but it's still on localhost.

I have done every possible change that I could find, but it's still not working.

### Specifics

1.  I updated the Runtime value in appSettings
2. I added the web.config file as stated here https://github.com/umbraco/Umbraco-CMS/issues/12239#issuecomment-1092774984
3. I changed the Filtering Request in IIS
4. I removed all Cache files Rebuilt and tried
5. I removed the obj and bin folder, rebuilt and tried.

I still get the same error.

### Steps to reproduce

Try uploading a large file in the Media Library

**Comment by bergmania** [comment]
Hi @TRexStark.

Maybe you will need to configure 

```cs
  builder.Services.Configure<IISServerOptions>(options =>
  {
      //options.MaxRequestBodySize = ???;
  });
```

If not, then I would try to eliminate one item at a time. Starting to get it to work without IIS.

**Comment by TRexStark** [comment]
Thanks @bergmania I'm not sure what you meant by "If not, then I would try to eliminate one item at a time. Starting to get it to work without IIS." but I will keep trying different solutions. I would expect that the appsettings value should just take over but it's not.

**Comment by bergmania** [comment]
What I meant was, if this configuration do not work, I would test it out using kestrel directly (Without IIS), and ensure I could upload large files here.

Then add IIS afterwards.

**Comment by TRexStark** [comment]
Thanks @bergmania I will give it a go.

**Comment by TRexStark** [comment]
@bergmania I tried with a 20MB file and it worked, and then I bumped the limit in the appSettings to 60MB and tried with a file of 57MB and it didn't work

**Comment by justin-nevitech** [comment]
Have you tried setting the MaxRequestLength in the appsettings.json, something like:

      "Runtime": {
        "MaxRequestLength": 50000
      },

See: https://docs.umbraco.com/umbraco-cms/reference/configuration/maximumuploadsizesettings

**Comment by justin-nevitech** [comment]
I also had to increase the maxAllowedContentLength in the web.config file when running under IIS.

    <system.webServer>
        <security>
            <requestFiltering>
                <requestLimits maxAllowedContentLength="629145600" />
            </requestFiltering>
        </security>
    </system.webServer>

**Comment by kjac** [comment]
Hi again @TRexStark,

I just had a stab at reproducing this on V10.4 - without luck.

The default install of Umbraco does not let me upload large files. This is expected. To allow large files (large request sizes), I followed [the guide](https://docs.umbraco.com/umbraco-cms/reference/configuration/maximumuploadsizesettings)

- On Kestrel I had to add the `Runtime:MaxRequestLength` configuration to appsettings.json (the value is in kb):
![image](https://user-images.githubusercontent.com/7405322/217191774-f60d812e-e2a1-48a7-8256-22a7331035e2.png)

- On IIS Express I had to create a web.config file next to appsettings.json and define `maxAllowedContentLength` (the value is in bytes):
![image](https://user-images.githubusercontent.com/7405322/217192075-86c721bc-b73c-4b12-88fe-55ef376a13fe.png)

Both configurations denote a max request length of 100 mb, which allowed me to upload large files (approx. 70 mb. each).

- On Kestrel:
![image](https://user-images.githubusercontent.com/7405322/217192377-9b8a42c1-801e-4829-bf57-941465b219db.png)

- On IIS Express:
![image](https://user-images.githubusercontent.com/7405322/217192483-e10b4541-9213-4aed-ba1c-90c4e2d36823.png)

I'm going to close this issue as this does not seem to be an Umbraco issue but rather a hosting configuration problem. If you are still stuck on this, perhaps the friendly faces at [the forum](https://our.umbraco.com/forum) can help you 😄
