### ISSUE TITLE
Examine search's RangeQuery<DateTime> not returning any results

### ISSUE THREAD

**Issue by ewuski** [umbraco/Umbraco-CMS#13683]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

Umbraco 10.0.0

### Bug summary

Using `RangeQuery<long>` or `RangeQuery<DateTime>` on a date picker field produces 0 results.

### Specifics

Using `RangeQuery<long>` or `RangeQuery<DateTime>` on a date picker field does not produce any results.

I am trying to return Examine search results limited by `DateTime `range. Either by using `DateTime ` field definition or long field definition using ticks as per below description.

### Steps to reproduce

I have added an additional configuration to the ExternalIndex for the `startDate` field

Composer:

```
public class ExamineComposer : IComposer
{
    public void Compose(IUmbracoBuilder builder)
    {
        builder.Services.ConfigureOptions<ConfigureExternalIndexOptions>();
    }
}
```

and index options configuration:

```
public class ConfigureExternalIndexOptions : IConfigureNamedOptions<LuceneDirectoryIndexOptions>
{
    public void Configure(string name, LuceneDirectoryIndexOptions options)
    {
        if (name.Equals(Constants.UmbracoIndexes.ExternalIndexName))
        {
            options.FieldDefinitions.AddOrUpdate(new FieldDefinition("startDate", FieldDefinitionTypes.Long));
        }
    }
}
```

I am then building the query:

```
searchQuery = searcher
                            .CreateQuery("content")
                            .NativeQuery($"+__IndexType:content +__NodeTypeAlias:booking ");
```

and adding RangeQuery:

                                searchQuery = searchQuery.And().RangeQuery<long>(
                                  new[] { "startDate" },
                                  item.StartDateTicks,
                                  item.EndDateTicks,
                                  minInclusive: true,
                                  maxInclusive: true);

or

                                searchQuery = searchQuery.And().RangeQuery<DateTime>(
                                  new[] { "startDate" },
                                  item.StartDate,
                                  item.EndDate,
                                  minInclusive: true,
                                  maxInclusive: true);

The resulting query is:

Category: "content", LuceneQuery: 
{+(+__IndexType:content +__NodeTypeAlias:booking) +(status:active status:confirmed) +(startDate:[637403040000000000 TO 638097696000000000])}

However I get 0 results.

If a drop `RangeQuery ` condition

Category: "content", LuceneQuery: 
{+(+__IndexType:content +__NodeTypeAlias:booking) +(status:active status:confirmed)}

and then limit the result with Linq:

                var bookings = results
                    .Select(r => (Booking)r)
                    .Where(b => b.StartDate <= endDate && b.StartDate > startDate)
                    .ToList();

 I get results correctly - 16 items in total and 3 items after the date range linq query.

Solution based on: https://docs.umbraco.com/v/10.x-lts/umbraco-cms/reference/searching/examine/indexing

### Expected result / actual result

`RangeQuery` with either `DateTime  type or `long` should not return 0 results. It should existing return results limited by date time range based on the requested field defined in the index configuration options.

**Comment by elit0451** [comment]
Hi @ewuski 👋 

When building the query, can you try to remove the `.Add()` (based on the **Date Range** section of https://shazwazza.github.io/Examine/searching) and instead have it like:

```
searchQuery = searcher
  .CreateQuery("content")
  .NativeQuery($"+__IndexType:content +__NodeTypeAlias:booking ");

searchQuery = searchQuery.RangeQuery<DateTime>(
  new[] { "startDate" },
  item.StartDate,
  item.EndDate,
  minInclusive: true,
  maxInclusive: true);
```

And remember to execute the query:

```
var results = searchQuery.Execute();
```

Let me know if ⬆️ changed anything in your output!

**Comment by elit0451** [comment]
Oops, sorry my bad. 🙈 

I've tried to reproduce this with _DateTime_ in the latest version of Umbraco 10 (_10.4.0_) - so in **ConfigureExternalIndexOptions** change to `options.FieldDefinitions.AddOrUpdate(new FieldDefinition("startDate", FieldDefinitionTypes.DateTime));`. The example you provided worked for me..

Can you check if your `startDate` property has a value when you inspect the fields of a search on the _ExternalIndex_ in the backoffice (_Settings > Examine Management > ExternalIndex_) and try to make a search that will show a node that has a `startDate` property (_i.e. by searching for the content node name_) and click on the fields? 

In my example, I've created 2 content nodes from a document type with 2 properties using a Date Picker (their aliases are `productStart` and `productEnd`). And I've set only the `productStart` FieldDefinition to be of type `FieldDefinitionTypes.DateTime`. In the video below, you will see the representation of `productStart` and `productEnd` is different as a result of the change:

https://user-images.githubusercontent.com/21998037/213381207-5deb3b5d-a330-415b-8463-080b3375abc5.mp4


The code for building the query is the following:

```c#
var indexName = "ExternalIndex";

if (!_examineManager.TryGetIndex(indexName, out IIndex? index))
{
    return NotFound($"No index found by name {indexName}");
}

var query = index.Searcher
   .CreateQuery("content")
   .NativeQuery($"+__IndexType:content +__NodeTypeAlias:product"); // I changed the NodeTypeAlias to the alias I was using in my doc type

query.And().RangeQuery<DateTime>(
    new[] { "productStart" },
    new DateTime(2023, 01, 01),
    new DateTime(2023, 01, 18),
    minInclusive: true,
    maxInclusive: true);

var results = query.Execute();
```

Hope the above helps and you can spot your mistake 🤞
I am going to close this as we clarified this isn't a real issue 🙂
