### ISSUE TITLE
Cannot add field type on Linux Opensuse

### ISSUE THREAD

**Issue by wpplumber** [umbraco/Umbraco-CMS#13682]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

version 11.1.0

### Bug summary

Error msg:

```
Request error: The URL returned a 404 (not found):
/umbraco/backoffice/umbracoapi/datatype/GetById
```

Preview:
![image](https://user-images.githubusercontent.com/52907282/212777141-4a189b22-67bc-439b-b676-d5613b20c94a.png)

### Steps to reproduce

Reproduce:

1. Fresh install.
2. Create a new doc type
3. Create new field but when choosing the type cannot.

**Comment by elit0451** [comment]
Hi @wpplumber,

Have you tried selecting another property editor to check if the error occurs just for the "Textarea"?

**Comment by wpplumber** [comment]
Welcome @elit0451, the same for other types i.e Textbox.

**Comment by wpplumber** [comment]
But using create new it works.

![image](https://user-images.githubusercontent.com/52907282/212887646-d14db345-d889-443f-b55b-b25fbb588f71.png)

**Comment by elit0451** [comment]
Good to know, thanks. We will have a look 👍

**Comment by nul800sebastiaan** [comment]
I thought this was caused by a custom package, or is this not the same Tarik as on the Discord thread here? 😅 https://discord.com/channels/869656431308189746/1059674867215126619

**Comment by wpplumber** [comment]
Not me Sebastiaan, I'm an old Umbraco developer back to it now.

![image](https://user-images.githubusercontent.com/52907282/212891245-0ab849fc-98c6-4ed1-8419-19d6be459cc8.png)

**Comment by nul800sebastiaan** [comment]
Ah okay! Well, what I talked about in the thread still holds true, if it was an issue with Umbraco it would also be an issue on Windows, we have plenty of people who run on Linux as well not encountering this problem so I will suggest that this most likely has something to do with custom code that you've implemented or a package you've installed.. :-) 

I do realize you're saying it's a fresh installation, so the only other thing I could think of is that maybe it's a permissions problem? But it looks more like a routing issue.

**Comment by nul800sebastiaan** [comment]
Alright, I made a clean install on Linux, creating an unattended install using [Package Script Writer](https://psw.codeshare.co.uk/?InstallUmbracoTemplate=true&UmbracoTemplateVersion=11.1.0&Packages=&UserEmail=test%40test.com&ProjectName=MyProject&CreateSolutionFile=true&SolutionName=MySolution&UseUnattendedInstall=true&DatabaseType=SQLite&UserPassword=test123456&UserFriendlyName=Test&IncludeStarterKit=true&StarterKitPackage=Umbraco.TheStarterKit&OnelinerOutput=true) (these commands will create an 11.1.0 install with a starter kit and the username `test@test.com`, password `test123456`) and that works for me: 


https://user-images.githubusercontent.com/304656/212902720-6fe0c245-9f5e-46ef-9f6b-e9587724471e.mp4


I also realize we have Playwright tests for this as well, which run both on Windows and Linux. So something is different on your machine, but not sure what!

**Comment by wpplumber** [comment]
@nul800sebastiaan , FYI I'm using SQLite.

**Comment by wpplumber** [comment]
Why other routes work but `https://localhost:44393/umbraco/backoffice/umbracoapi/datatype/GetById?id=-89` failed!

![image](https://user-images.githubusercontent.com/52907282/213150627-703ba74d-5b10-464d-bb95-3d3f44355333.png)

**Comment by elit0451** [comment]
Unfortunately, we still can't reproduce this 😞

**Comment by wpplumber** [comment]
Thank you for the update @elit0451, maybe I'm near from a fix.

I didn't go deep on the core architecture but seems as API data missing for that.

@nul800sebastiaan, what is the id of default textarea on Ubuntu ? possible to show the network log as mine ?

![image](https://user-images.githubusercontent.com/52907282/213811117-cbb81d0e-a3b6-437a-8e33-8759095b887a.png)

**Comment by nul800sebastiaan** [comment]
Same Id, `-89`. And you can see it's got a 200 response instead of an error response like yours. 

![image](https://user-images.githubusercontent.com/304656/214005339-50406aed-6316-417c-ab07-6dcfff81bda2.png)

In my `umbracoDataType` table the config is `null`, that might be a clue yes.

**Comment by wpplumber** [comment]
The same error I got using SQL server DB!

**Comment by kjac** [comment]
Hi @wpplumber,

Did you ever get any closer to a solution here?

I can't reproduce this either, not on V10 nor on V11. Something is definitively up with your environment. 

This may a little far fetched, but there are two major differences between the attempted reproductions and your environment, as far as I can tell from the screenshots; your localhost SSL certificate does not work, and you may be running on a different default locale than the reproductions have been trying.

Could you please try:
- to fix the localhost SSL certificate
- to run on an English locale of you're not already (there might be a problem interpreting the minus in the ID)

**Comment by wpplumber** [comment]
Welcome @kjac, not yet where I already added a question on [Discord](https://discordapp.com/channels/869656431308189746/882985025803530332/1067370493985951784) asking for a way to debug on Linux...

Related to SSL I already mentioned in this post that other requests work.

**Comment by nul800sebastiaan** [comment]
Does it work when you go into the database and set the textarea or textstring config column to `null` instead of `{}` - honestly I'm quite puzzled as to why mine defaults to `null` and yours to empty json.

**Comment by wpplumber** [comment]
The same error with default input and after  I changed it to `null`.

![image](https://user-images.githubusercontent.com/52907282/217492803-3fca568a-cca9-43a8-9c37-86baf513f8db.png)

**Comment by wpplumber** [comment]
Today I cannot add media folder too!

![image](https://user-images.githubusercontent.com/52907282/218711246-c2f8950a-0fb2-4230-8db9-c67f862b9297.png)

**Comment by wpplumber** [comment]
Other machine using the same Opensuse version working!

![image](https://user-images.githubusercontent.com/52907282/218727221-caed550e-8ffa-4f1d-81fe-0b7b96492bfa.png)

**Comment by wpplumber** [comment]
Also for Media section !

![image](https://user-images.githubusercontent.com/52907282/219058715-4391525c-9e14-4cb9-924d-668e60b63b39.png)

**Comment by wpplumber** [comment]
Fixed. :pick: 

After switching Opensuse language from Arabic to English it works!
