### ISSUE TITLE
Examine Sort Order - v10/11

### ISSUE THREAD

**Issue by wadrschall** [umbraco/Umbraco-CMS#13681]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

10.2.1

### Bug summary

When attempting to sort by an index property (string), it order isn't alpha at all. Sorting by other types works without issue. We attempted to create a new index as well (called "_title") and filled it the nodeName and sorted by that, same result. The same is true for ascending and descending.

Our order by code looks like this:
`            if (criteria.OrderBy?.Any() == true)
            {
                if (criteria.OrderDirection == OrderDirections.Ascending)
                {
                    query.OrderBy(criteria.OrderBy.ToArray());
                }
                else
                {
                    query.OrderByDescending(criteria.OrderBy.ToArray());
                }
            }`

When inspecting to ensure the value is getting set correctly:

![image](https://user-images.githubusercontent.com/50219294/212752277-8927a594-521a-4b9d-95fe-b45af3f615c7.png)

The code to run the search is very simple:
`results = query.Execute();`

This searches several hundred items and the results are all over the place. When we tell it to flip the order (asc vs desc), it does flip properly, but the overall order is still wrong.

I know in V8, you had to tell each field if it was "searchable". When we flipped to v9 (this wasn't necessary to our understanding), we know this code was working and sorting weas spot on. We've since been through a variety of upgrades and aren't certain when this stopped functioning. Since we primarily sort by a date field and that's still working, we are unclear what caused this issue.

This issue occurs in v 10.2.1 and 11.1.0 (on 2 different code bases).

### Steps to reproduce

Code snippets included above.

### Expected result / actual result

Alphabetical searching against string fields should sort as expected.

**Comment by bjarnef** [comment]
The field need to be `FullTextSortable` 😉

From the documentation: https://shazwazza.github.io/Examine/sorting

Custom sorting
Any field that is a [numerical or date based](https://shazwazza.github.io/Examine/configuration.html#default-value-types) is automatically sortable. To make text based fields sortable you need to explicitly opt-in for that behavior. By default all fields are [FieldDefinitionTypes.FullText](https://shazwazza.github.io/Examine/configuration.html#default-value-types) which are not sortable. To make a text field sortable it needs to be [FieldDefinitionTypes.FullTextSortable](https://shazwazza.github.io/Examine/configuration.html#default-value-types).

**Comment by wadrschall** [comment]
Thanks for the quick feedback. For clarity, as some of these are custom fields, we create them inside the IndexProviderTransformingIndexValues() where we get a copy of the indexes, insert our new fields and the set them with: e.SetValues(updatedValues.ToDictionary(x => x.Key, x => (IEnumerable<object>)x.Value));.

With the direction above, it sounds like we'd need to create them first, then we'd need to seperately use the IConfigureNameOptions to tell it the new fields are of the type "FullTextSortable". There isn't a way to create a new index field, set its value and tell it that it needs to be sortable all in the same set of calls?

**Comment by bjarnef** [comment]
The index options are responsible to e.g. define the field type during indexing, while the `TransformingIndexValues` event allow to modify the `ValueSet` by adding new fields or modifying existing.

For example:

```
private void UmbracoContextIndex_TransformingIndexValues(object? sender, IndexingItemEventArgs e)
{
    var values = e.ValueSet.Values.ToDictionary(x => x.Key, x => (IEnumerable<object>)x.Value);

    // Create searchable path
    if (e.ValueSet.Values.ContainsKey("path"))
    {
        var path = e.ValueSet.GetValue("path")?.ToString();

        if (!string.IsNullOrEmpty(path))
        {
            values.Add("searchPath", new[] { path.Replace(',', ' ') });
        }
    }

    // Update the value
    e.SetValues(values);
}
```

**Comment by elit0451** [comment]
Hi @wadrschall 👋 
Let us know if the suggestion that Bjarne provided fixed your problem, otherwise we'd need to investigate further if there is a bug🙂

**Comment by wadrschall** [comment]
It got us close to what we needed. Once we added his logic to set the node name, it appears our custom date field stopped working (we’re assuming there’s some auto-detection if a field has only numbers, etc). Not a huge deal, once we realized that our custom field was no longer searchable, we added a definition for that one too, rebuilt the index and it started to work as expected.

Does the team have all of these examples posted somewhere? It would be really helpful to see these newer examples (v9+), especially the recommended way to create custom indices and how to edit their values.

Thanks!
Rob

**Comment by elit0451** [comment]
Good to hear that your problem has been resolved 🎉 
</br>

Docs about Examine and indexing can be found here:
- Custom indexing: https://docs.umbraco.com/umbraco-cms/reference/searching/examine/indexing
- or directly in Examine's Documentation: https://shazwazza.github.io/Examine/sorting (_sorting in particular_)

Feel free to have a look at [our forum](https://our.umbraco.com/forum/) for helpful inputs from the community 🙂
