### ISSUE TITLE
Uploading files to Media Picker doesn't use "User Start Node"

### ISSUE THREAD

**Issue by sofietoft** [umbraco/Umbraco-CMS#13680]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

11.1.0

### Bug summary

Uploading files to Media Picker doesn't use "User Start Node" as it's stated in the [release blog post](https://umbraco.com/blog/umbraco-111-release/#media) and the associated [documentation](https://docs.umbraco.com/umbraco-cms/fundamentals/data/creating-media#add-media-through-the-content-section).

When uploading any Media files through a Media Picker property on a content node, the media is added through the Media root (or the Media node defined in the property editor config).

### Specifics

Media start node defined on User level:
![image](https://user-images.githubusercontent.com/24529086/212701327-5c32e9a9-f5ed-4497-b9d1-db9d96f1015e.png)

No Start node defined on the Media Picker Property Editor:
![image](https://user-images.githubusercontent.com/24529086/212701533-ff03c047-fc20-4cf6-a115-6278d6c63ec2.png)

Adding Media through the Content section, expected the files to be in the Start node set on my User:

https://user-images.githubusercontent.com/24529086/212704722-fd0679c6-1eee-4b74-b136-0edbfc0e632e.mp4

### Steps to reproduce

- Create a Document Type
- Add a Media Picker
- Create a Folder in the Media section
- Use that folder as the Media start node for your backoffice user
- Create a content using the Document Type from step 1
- Add media to the content node by following the drag and drop feature explaining in [this documentation](https://docs.umbraco.com/umbraco-cms/fundamentals/data/creating-media#add-media-through-the-content-section)
- Check where the Media items where added

### Expected result / actual result

The expected result would be that the media items are added to the folder selected as the Media start node for your user.

What actually happens, is that the media is added to the Media root.

**Comment by elit0451** [comment]
Hey @sofietoft 😊 

Thanks for reporting this bug! Super great documentation of how to easily spot the bug 😜 

You are right that selecting a User's Media start node "hides" the uploaded media in the Media section; you won't notice that the media items have been actually uploaded to the Media root until you remove the selected start node from the user. This is **not** the intended behaviour, since they should have been part of the folder you listed as a start node.

A few more things that I noticed:  
- Toggling on the "Ignore User Start Nodes" option will not fix the problem either;


_Note_: In your example, you've picked the Multiple Media Picker, which can save the set-up for uploading multiple images when testing this.

**Comment by sofietoft** [comment]
Thanks for the feedback 🙌 

I did actually pick the "Media Picker", but set it to allow picking multiple images - wasn't aware that could change things 😅 
.. I just did a quick test, and it doesn't look like disabling the "allow multiple" solves it 🙈

**Comment by mennomout** [comment]
@elit0451 @sofietoft I'm assuming this might be the reason it's not working:
![image](https://user-images.githubusercontent.com/77411834/213187897-8f71a946-58ce-44d2-93c1-263904e26eee.png)

I'm not sure what the comment about "backoffice auth" is referring to.

**Comment by elit0451** [comment]
Hey @mennomout 

Thanks for looking into this. 🙌  Unfortunately, using the commented-out implementation didn't solve the problem, so we need to figure out what exactly is going on

**Comment by elit0451** [comment]
Update @mennomout,

After talking to the team, it seems like the code you highlighted is meant for a future version of Umbraco and not Umbraco 11. So we still need to look into this bug in Umbraco 10 and 11.

I will mark this as up for grabs and see if anyone is up for spotting and fixing the problem 💪

**Comment by mennomout** [comment]
@elit0451 Thank you for the reply. 

After spending some more time with this issue I've been able to propose a fix (https://github.com/umbraco/Umbraco-CMS/pull/13737) that will place the image in one of the users Media start nodes.
