### ISSUE TITLE
Unable to run in runtime=production using nginx reverse proxy

### ISSUE THREAD

**Issue by mattinsp** [umbraco/Umbraco-CMS#13699]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

10.3.2

### Bug summary

When running behind an NGINX reverse proxy using standard .NET hosting configuration Umbraco fails to start using "runtime: production". 

### Specifics

This failure is because "usehttps: false" is set as the application runs in non-HTTPS using Kestrel. HTTPS is added by NGINX and not the .NET application running as a systemd service. Without "runtime: production" Umbraco runs as expected.

### Steps to reproduce

1. Run Umbraco using Kestrel, systemd and NGINX (https://learn.microsoft.com/en-us/aspnet/core/host-and-deploy/linux-nginx?view=aspnetcore-7.0&tabs=linux-ubuntu)
2. Set "usehttps: false" and "runtime: production"
3. Launch the website

### Expected result / actual result

Expected result: Umbraco loads
Actual result: Umbraco fails to load and reports an error. "Using HTTPS should be enforced in production mode."

"usehttps: false" should be possible for "runtime: production".

Code that prevents Umbraco running using NGINX as a reverse proxy:
https://github.com/umbraco/Umbraco-CMS/blob/v11/contrib/src/Umbraco.Infrastructure/Runtime/RuntimeModeValidators/UseHttpsValidator.cs

**Comment by nikolajlauridsen** [comment]
Hry @mattinsp that is indeed a bit of a problem if you're using NGINX, fortunately though, the runtime mode is extensible, so you can actually remove that specific validator that's giving you trouble.

There is an example of that [in the docs here](https://docs.umbraco.com/umbraco-cms/fundamentals/setup/server-setup/runtime-modes#customize-extend-runtime-mode-validation), so I'll go ahead and close down this issue 😄
