### ISSUE TITLE
Color picker: labels are not customizable

### ISSUE THREAD

**Issue by Jay-umbr** [umbraco/Umbraco-CMS#13694]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

11.1.0

### Bug summary

In 11.1.0 (and potentially earlier 11) it does not seem possible to customize labels on color pickers. That was possible in v10.
![image](https://user-images.githubusercontent.com/56038614/213166138-93b8e92b-becc-4e9b-a99d-c8eabfdd13bb.png)

The labels dont show in the editor settings in UI, and when they are eventually created the colors just seem to contain the HEX code as a label.

### Steps to reproduce

On any v11.1 installation add a new color picker configuration and check the Include Labels button. The labels will not show next to the colors.

### Expected result / actual result

The intended result would be to allow the user to customize the label for each color, as far as I can tell.

---
_This item has been added to our backlog [AB#25839](https://dev.azure.com/umbraco/243e7927-03b2-44e2-908f-d4ac7ea5daaa/_workitems/edit/25839)_

**Comment by elit0451** [comment]
Thanks for reporting this @Jay-umbr 💪 
I can confirm this became an issue only in 10.4 and 11.1

**Comment by elit0451** [comment]
Seems like PR https://github.com/umbraco/Umbraco-CMS/pull/13108 introduced this issue.

**Comment by iOvergaard** [comment]
I have found a potential fix with #13709

This goes pretty deep and is an exciting discovery. The logic requiring this actually only affects the color picker, so we are lucky on that, and Bjarne's fix in #13108 is still applied, so his stuff also works. This ensures that such a check added in #13108 will work regardless of where the view is being spun up (directly or inside infinite editors).

**Comment by elit0451** [comment]
Fixed in: #13709
