### ISSUE TITLE
Content Templates does not trigger generation of new Keys

### ISSUE THREAD

**Issue by nielslyngsoe** [umbraco/Umbraco-CMS#13698]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

10.4

### Bug summary

When a document containing a Block Grid Editor is created as a Content Template.
And this Content template is used to create documents. Then the Blocks does not get new keys, which it should. cause we use the key for some caching. So first cached data will affect the others.

See the original issue reported here:
https://github.com/umbraco/Umbraco.BlockGrid.Example.Website/issues/6

### Steps to reproduce

Setup something with Block Grid Editor, I would prefer something that is nested.
Make a Content Template from it.
Create two pages based on the content template.
View the first page, in backoffice, and inspect Network traffic.
Retrieve the ContentUDI of the first layout item, of the Property Value.
Verify that the other page created from the same Content Template got the exact same ContentUDI in their.

I would expect that every Document created from a Content Template got new ContentUDI.

Notice the ContentUDI is referenced between items of layout and data.

The same goes for SettingsUDI. but that is referenced between layout and settingsData.

Notice:
This does not happen then Copying documents, but to me the Create from Content Template feature should be using the same features as the Copy Feature.

### Expected result / actual result

I would expect that every Document created from a Content Template gets new ContentUDI and SettingsUDI, that has to happen for all Blocks and the data of them, no matter the amount of nesting.

**Comment by elit0451** [comment]
As Niels said, copying a document created from a content template updates the values correctly (even for the nested blocks - ex: each block from the Two Column Layout has a different `contentUdi` than the blocks in the original content node).
</br>

A few more notes:
- To see the `contentUdi` in the Network tab, check the response from `umbraco/backoffice/umbracoapi/content/GetById`:
  - inside `variants[]` > expand an element 
  - inside `tabs[]` > expand an element
  - inside `properties[]` > expand your block grid property (_where `editor: "Umbraco.BlockGrid"`_)
  - expand the value of `value`
  - expand the value of `layout`
  - and you will see the `contentUdi` of the element - those should be different for the different content nodes
</br>

- To check the `contentUdi` of the nested blocks (_ex: each block from the Two Column Layout_):
  - Continue from above ⬆️ 
  - inside `areas[]` of the element which contains the `contentUdi`  of the block grid > expand an element 
  - inside `items[]` > expand an element
  - and you will see the `contentUdi` for each nested block - those should also be different for each content node made from a content template
</br>

Most likely, fixing this issue would provide a guideline on how to fix https://github.com/umbraco/Umbraco-CMS/issues/13413

**Comment by jerpenol** [comment]
This issue is now tagged with affected/v11 and affected/v10, but as mentioned in #13901 this also occurs on 8.17.0

**Comment by nikolajlauridsen** [comment]
I've added the tag now, that's an oversight, sorry about that 😅

**Comment by jerpenol** [comment]
@nikolajlauridsen No problem at all! Thanks for adding the tag :)

**Comment by Zeegaan** [comment]
This should now be fixed in https://github.com/umbraco/Umbraco-CMS/pull/15541
