### ISSUE TITLE
Drag and drop media picker doesn't work in Block Grid Editor

### ISSUE THREAD

**Issue by erikjanwestendorp** [umbraco/Umbraco-CMS#13705]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

11.1.0

### Bug summary

Umbraco 11.1.0 introduced drag and drop support for media pickers (awesome!). It seems that the drag and drop feature doesn't work for media pickers inside a block grid editor.

### Specifics

After drag and drop an image the text 'waiting' appears:

![image](https://user-images.githubusercontent.com/7831614/213439124-7643c236-6565-4ddb-9875-b108545f71c0.png)

Console error: 
![image](https://user-images.githubusercontent.com/7831614/213439217-76ef433f-5737-478e-99a2-c7d503ec6467.png)

### Steps to reproduce

Create a Block Grid Editor 
Add a block to the editor (with a media picker property)
Add the Block Grid Editor to a DocType
Create a content item using the DocType 
Add a block (with the media picker property) 
Try to drag and drop an image 

### Expected result / actual result

Expected: 
Image will be uploaded 

Actual:
The text 'waiting' appears and also a console error.

---
_This item has been added to our backlog [AB#25930](https://dev.azure.com/umbraco/243e7927-03b2-44e2-908f-d4ac7ea5daaa/_workitems/edit/25930)_

**Comment by elit0451** [comment]
Thanks for reporting this @erikjanwestendorp 💪 

I can confirm this is a problem also in the latest Umbraco 10 (_10.4.0_). I get the same console errors.
The workaround is to click on the "_+ Add_" and drop the media into the open dialog.

**Comment by iOvergaard** [comment]
Hello @erikjanwestendorp 

A fix has now been made for this and will most likely end up in Umbraco 11.2.0.

Thanks again for reporting!
