### ISSUE TITLE
Rich text editor need some ui style fix in top left corner

### ISSUE THREAD

**Issue by alevak09** [umbraco/Umbraco-CMS#13718]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

11.0.1.

### Bug summary

![image](https://user-images.githubusercontent.com/73195407/214072082-14c17131-d337-42e8-ad82-0fbc7ec70562.png)

### Steps to reproduce

1. Create new document type
2. Add new rich text property editor
3. Save changes to document type
4. Go to content and create new node using this document type
5. You should see rich text property editor as on picture above

**Comment by bjarnef** [comment]
I think this is fixed by https://github.com/umbraco/Umbraco-CMS/pull/13012 as the textarea has some padding.

**Comment by Zeegaan** [comment]
Hey @alevak09 thanks for reporting 🐛 
I can definitely reproduce this, and as @bjarnef mentions, it will be fixed by #13012 💪
