### ISSUE TITLE
MNTP Console Error: '$scope.model.value.split is not a function"

### ISSUE THREAD

**Issue by hfloyd** [umbraco/Umbraco-CMS#13710]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

10.4.0

### Bug summary

I added an MultinodeTreePicker on an ElementType which is part of a Block List.

I get a Console error as soon as I open the Block List Item for editing. (The MNTP is on the "Selected Content" property.)

![image](https://user-images.githubusercontent.com/1252593/213518179-c4b1b22f-4045-4a57-bde6-46dbc559f386.png)

Console Error:
![image](https://user-images.githubusercontent.com/1252593/213518308-8f3b840e-caec-4410-9272-8f5315b30216.png)

```
TypeError: $scope.model.value.split is not a function
    at syncRenderModel (umbraco.controllers.min.js?d=638097464150000000:1:104499)
    at umbraco.controllers.min.js?d=638097464150000000:1:109415
    at angular.js:18075:37
    at m.$digest (angular.js:19242:15)
    at m.$apply (angular.js:19630:13)
    at k (angular.js:13473:36)
    at v (angular.js:13730:7)
    at y.onload (angular.js:13635:9) 'Possibly unhandled rejection: {}'
```

If I click "Add", the content tree is shown in the overlay, but if I select a content node, it won't allow me to "Submit", and shows an additional error:

![image](https://user-images.githubusercontent.com/1252593/213518623-077db00c-7cf8-4277-901e-6d93ccb67353.png)

```
angular.js:15697 TypeError: $scope.model.value.split is not a function
    at $scope.add (umbraco.controllers.min.js?d=638097464150000000:1:107813)
    at umbraco.controllers.min.js?d=638097464150000000:1:106715
    at Function.mr (underscore-min.js?d=638097464150000000:6:9283)
    at $scope.currentPicker.submit (umbraco.controllers.min.js?d=638097464150000000:1:106670)
    at Object.submit (umbraco.controllers.min.js?d=638097464150000000:1:251171)
    at fn (eval at compile (angular.js:16548:15), <anonymous>:4:232)
    at d.<computed> [as action] (angular.js:11517:22)
    at UmbButtonController.clickButton (umbraco.directives.min.js?d=638097464150000000:1:66004)
    at fn (eval at compile (angular.js:16548:15), <anonymous>:4:245)
    at e (angular.js:29123:13)
```

I get this error no matter how the MNTP is configured - it can use an XPath query, or a chosen Content node, or no options at all.

### Specifics

See also: https://our.umbraco.com/forum/using-umbraco-and-getting-started/108454-mntp-gives-typeerror-scopemodelvaluesplit-is-not-a-function-when-clicking-select-button#comment-343302

### Steps to reproduce

Add an MTP on an Element Type as part of a BlockList

**Comment by elit0451** [comment]
Hey @hfloyd 😊 

I've also tried to reproduce this in Umbraco 10.4.0 and I don't see any console errors. Check the video below though and l let me know if I missed something 🙂

https://user-images.githubusercontent.com/21998037/213686822-c279730d-492a-4cea-96d6-a27638ba2785.mp4

**Comment by hfloyd** [comment]
Maybe it is some random installation-specific thing? I don't know. The forum post's OP said it was resolved for him when he "deleted and re-created" the property editor, which seems odd. I thought maybe something was cached, and I rebuilt, hard-refreshed browser, etc, and nothing fixed it... but if you can't reproduce it, I guess it isn't a consistent bug... 🤷‍♀️ Thanks for looking into it for me. 😊

**Comment by c9mb** [comment]
I've seen this sort of thing happen when changing/adding a type which leaves a default value on an existing property as null - typically a null-check in the property-editor controller is required.

**Comment by kjac** [comment]
Hi @hfloyd 👋 

Do you have anymore info to go on here? We're kinda stuck, unable to reproduce it.

**Comment by hfloyd** [comment]
Sorry, @kjac I ended up creating a custom Contentment DataList to get around the issue because I'm under deadline. If I see it happen again I'd be happy to post more info. Maybe put this one on hold for now?

**Comment by kjac** [comment]
Sure 😄 glad you found a way around the issue 👍

**Comment by marciscaupjonoks** [comment]
Had this happen when changed property type from URL picker to Content picker (fixed it by recrating property)
