### ISSUE TITLE
Validation not working on Dropdown

### ISSUE THREAD

**Issue by bsweb** [umbraco/Umbraco-CMS#13712]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

11.1

### Bug summary

Selecting a value from a dropdown with prevalues added and mandatory selected returns an error.

### Steps to reproduce

Added prevalue to a dropdown list and then added to a element type with mandatory selected. When selecting the value from the dropdown and saving it it returns a "Value can not be null" error message
![image](https://user-images.githubusercontent.com/4737211/213668818-8ed5b57c-fb9e-477f-9eda-f05b9cedac1d.png)
![image](https://user-images.githubusercontent.com/4737211/213668851-cc0cef4a-da0d-46f0-81a4-b5e3625f48c9.png)
![image](https://user-images.githubusercontent.com/4737211/213668868-acf52401-e054-4dfc-8ac5-8ff96c0b163b.png)

### Expected result / actual result

Selected value is saved.

**Comment by elit0451** [comment]
Hi @bsweb 👋 

I've also tried to reproduce this in Umbraco 11.1 and there are no validation issues for me. Check the video below and l let me know if I missed something 🙂

Btw, I tested both cases when a dropdown with prevalues is part of an Element type and when it is part of a Document type.


https://user-images.githubusercontent.com/21998037/213675768-234cff0a-0822-4536-8d75-7d438bafb1c3.mp4

**Comment by kjac** [comment]
Hi @bsweb,

We haven't heard from you in a while, and as we can't reproduce this issue, we're going to assume it has gone stale. I'm going to close it now. 

Please feel free to reopen the issue with additional steps to reproduce if it is still a problem for you.
