### ISSUE TITLE
New Admin Invite skips Avatar Screen

### ISSUE THREAD

**Issue by TRexStark** [umbraco/Umbraco-CMS#13727]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

10.4.0

### Bug summary

This was happening in 10.3.2 as well.

When you invite a new user to the BackOffice, once they enter their password and go to the next step, the screen shows the Avatar view briefly and jumps directly to the BackOffice.

When you invite new user to a site's backoffice and they're not familiar with Umbraco, they see something that jumps, they just panic for no reason and this creates unnecessary support time.

### Specifics

Same as above

### Steps to reproduce

Invite a new User to the BackOffice and follow the steps to activate the access.

### Expected result / actual result

Should not skip the Avatar View or just remove that step altogether if that's the intention.

---
_This item has been added to our backlog [AB#30794](https://dev.azure.com/umbraco/243e7927-03b2-44e2-908f-d4ac7ea5daaa/_workitems/edit/30794)_

**Comment by Zeegaan** [comment]
Hi, @TRexStark I can definitely reproduce this 😁 It should really not skip the avatar step! 🤔

**Comment by Zeegaan** [comment]
Just posting this here for anyone who might not know, you have to set up SMTP in your global settings, set up mine in appsettings.Development.json: 

```
      "Global": {
        "Smtp": {
          "From": "your@email.com",
          "Host": "localhost",
           "Port": "25"
        }
      },
```

I then used papercut as local smtp server to catch the outgoing emails 👍

**Comment by TRexStark** [comment]
Thanks @Zeegaan for confirming.

**Comment by iOvergaard** [comment]
Thanks again for letting us know. We have chosen to remove the avatar step altogether. This will be released in the upcoming v10, v11, and v12 versions!
