### ISSUE TITLE
Umbraco.Cms.Infrastructure.Examine ContentValueSetValidator

### ISSUE THREAD

**Issue by hdanau** [umbraco/Umbraco-CMS#13729]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

10.4.0

### Bug summary

When trying to create a new ContentValueSetValidator instance. The constructor requests a "IScopeProvider" from Umbraco.Cms.Core.Scoping which is depricated. 

### Specifics

This issue is in the "ContentValueSetValidator" class of the Umbraco.Cms.Infrastructure.Examine namespace.

### Steps to reproduce

![Screenshot bug](https://user-images.githubusercontent.com/36898395/214511375-35c377e1-b7c1-42ff-8691-d6da835b1c3d.png)

### Expected result / actual result

Is it possible to have this changed? So that the "IScopeProvider" is used from Umbraco.Cms.Infrastructure.Scoping.

**Comment by Zeegaan** [comment]
Hey @hdanau, you are totally right, this should be changed to the Umbraco.Cms.Infrastructure.Scoping.IScopeProvider instead 👍I am putting this up for grabs as its a great first issue 👏
