### ISSUE TITLE
Use of `Descendants<T>()` is slow compared to `Children<T>()`

### ISSUE THREAD

**Issue by bjarnef** [umbraco/Umbraco-CMS#13730]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

10.4.0

### Bug summary

In an Umbraco Cloud project we hook into `TransformingIndexValues` event to modify External Index.

Inside this event we get some data from pickers and to query content cache for a few other content nodes in some archives.

However we noticed on the live environment after more data has been imported via Hangfire that indexing of External Index took **~1 hour**.

There are more the 10K course nodes, but only 17 committee nodes and 6 secretariats nodes.

I made a backup of the live db and restored in locally, where I could reproduce the issue.

I found that when I commented this part the indexing was very fast:

```
if (e.ValueSet.ItemType == Course.ModelTypeAlias)
{
    if (int.TryParse(e.ValueSet.Id, out int id))
    {
        if (cache?.GetById(id) is not Course content)
            return;

        if (content.Fkb.HasAny())
        {
            var fkbNodes = content.Fkb.OfType<Fkb>() ?? Enumerable.Empty<Fkb>();
        
            var fkbs = fkbNodes
                .WhereNotNull()
                .DistinctBy(x => x.Id)
                ?? Enumerable.Empty<Fkb>();
        
            var root = cache.GetAtRoot().OfType<HomePage>().FirstOrDefault();
        
            var committees = root?.Descendants<Committee>()
                .WhereNotNull()
                .Where(x => x.FkbList?.OfType<Fkb>().HasAny(y => fkbs.Contains(y)) == true)
                ?.DistinctBy(x => x.Id)
                ?? Enumerable.Empty<Committee>();
        
            var secretariats = root?.Descendants<Secretariat>()
                .WhereNotNull()
                .Where(x => x.Committees?.OfType<Committee>().HasAny(y => committees.Contains(y)) == true)
                ?.DistinctBy(x => x.Id)
                ?? Enumerable.Empty<Secretariat>();
        
            values.Add(Constants.Examine.Course.FieldNames.Fkbs, new object[] { string.Join(",", fkbs.Select(x => x.Name)) });
            values.Add(Constants.Examine.Course.FieldNames.Secretariats, new object[] { string.Join(",", secretariats.Select(x => x.Name)) });
            values.Add(Constants.Examine.Course.FieldNames.SecretariatsIds, new object[] { string.Join(" ", secretariats.Select(x => x.Id)) });
        }

    }
}
```

after some further investigation I modified this part of the code to:

```
if (e.ValueSet.ItemType == Course.ModelTypeAlias)
{
    if (int.TryParse(e.ValueSet.Id, out int id))
    {
        if (cache?.GetById(id) is not Course content)
            return;

        if (content.Fkb.HasAny())
        {
            var root = cache?.GetAtRoot().OfType<HomePage>().FirstOrDefault()
            var committeeArchive = root?.FirstChild<CommitteeArchive>();
            var secretariatArchive = root?.FirstChild<SecretariatArchive>();

            var fkbs = content.Fkb.OfType<Fkb>()
                .WhereNotNull()
                .DistinctBy(x => x.Id)
                ?? Enumerable.Empty<Fkb>();

          var fkbIds = fkbs.Select(x => x.Id).ToArray();

          var committees = committeeArchive?.Children<Committee>()
              ?.WhereNotNull()
              ?.Where(x => x.FkbList?.OfType<Fkb>().HasAny(y => fkbIds.Contains(y.Id)) == true)
              ?.DistinctBy(x => x.Id)
              ?? Enumerable.Empty<Committee>();

          var committeeIds = committees.Select(x => x.Id).ToArray();
      
          var secretariats = secretariatArchive?.Children<Secretariat>()
              ?.WhereNotNull()
              ?.Where(x => x.Committees?.OfType<Committee>().HasAny(y => committeeIds.Contains(y.Id)) == true)
              ?.DistinctBy(x => x.Id)
              ?? Enumerable.Empty<Secretariat>();
      
          values.Add(Constants.Examine.Course.FieldNames.Fkbs, new object[] { string.Join(",", fkbs.Select(x => x.Name)) });
          values.Add(Constants.Examine.Course.FieldNames.Secretariats, new object[] { string.Join(",", secretariats.Select(x => x.Name)) });
          values.Add(Constants.Examine.Course.FieldNames.SecretariatsIds, new object[] { string.Join(" ", secretariats.Select(x => x.Id)) });
      }
    }
}
```

Now the indexing is blazing fast in less than **1 minute**.

### Steps to reproduce

Compare timing of indexing in `TransformingIndexValues` modifying External Index using `Descendants<T>()` vs `Children<T>()`.

**Comment by bjarnef** [comment]
I think the issue with `Descendants<T>` from root here, is that it also iterate the course archive to check if there's any `Committee` or `Secretariat` nodes (although we know there shouldn't be).

So it may be fast enough when querying `Descendants<T>` from these archieves instead.

```
var committeeArchive = root?.FirstChild<CommitteeArchive>();
var secretariatArchive = root?.FirstChild<SecretariatArchive>();
```

**Comment by nikolajlauridsen** [comment]
Just popping in here to mention that I don't really think this is a bug, but just the nature of descendants, since as you mention yourself it will iterate over every single node in Umbraco really.

It's also mentioned in the common pitfalls document here: https://docs.umbraco.com/umbraco-cms/reference/common-pitfalls#querying-with-descendants-descendantsorself. Now of course I'm not entirely aware of your use case, but if you have all committees under a single node, then it would be much faster to call children on that.

**Comment by bjarnef** [comment]
Hi @nikolajlauridsen 

Yes, while indexing each course node it actually was querying for these nodes in the archives, but since it started from root and was querying descendants it also iterated all 10K+ course nodes each time it indexing a course node (or at least the ones with a value in the FKB property).

The FKB property is a MTNP, so these the resolved to `IEnumerable<Fkb>` ... from the ids of these, it query in another committee archive where each commiteee has a list of FKB's (the FkbList property).

Based on these unique commiteees it then query an archive of secretariats nodes, which each have a property "Committees".

Both using `Children<T>()` and `Descendants<T>() ` takes less than a minute... the main different is than in query the archive nodes directly and query from these instead.

```
var committeeArchive = root?.FirstChild<CommitteeArchive>();
var secretariatArchive = root?.FirstChild<SecretariatArchive>();
```

**Comment by nikolajlauridsen** [comment]
Yeah that makes good sense.

What you're proposing is a better way to do it for sure, and if that's sufficiently fast then all is happy days, now if your Root ended up having a lot of child nodes, then using `FirstChild<CommitteeArchive>();` may end up being slow too, all depending, and in that case, hardcoding the keys is actually a pretty valid solution, that's even mentioned in the [pitfalls documents here](https://docs.umbraco.com/umbraco-cms/reference/common-pitfalls#not-caching-expensive-lookups)

**Comment by bjarnef** [comment]
In that case we could eventually move the archive nodes under a parent node, so only this key of this parent node was hardcoded.

Furthermore I noticed there is a `IndexOperationComplete` event, where would could log when the indexing is finished, but isn't there a way to log when indexing is started? E.g. for measure the timing from indexing starts until it is completed. Umbraco logs a Done messsage, but this was logged shortly after although the indexing previous was running in background for an hour.

And property something else than log in start end end of `TransformingIndexValues` as this would fill the log with a lot on entries when have a lot of content nodes :)

**Comment by nikolajlauridsen** [comment]
This may be hard since it's actually not a part of Umbraco, but in Examine, we listen to the IndexOperationComplete When this fires we log the “Done” message, as you can see here: https://github.com/umbraco/Umbraco-CMS/blob/v11/contrib/src/Umbraco.Web.BackOffice/Controllers/ExamineManagementController.cs#L159

Although I must admit, I'm not really an expert in Examine 😄
