### ISSUE TITLE
IsBackOfficeRequest is extremely inefficient

### ISSUE THREAD

**Issue by Nuklon** [umbraco/Umbraco-CMS#13732]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

v9, v10, v11

### Bug summary

https://github.com/umbraco/Umbraco-CMS/blob/v11/contrib/src/Umbraco.Core/Routing/UmbracoRequestPaths.cs

This gets called a lot and does a lot of unnecessary things.
- It can optionally take the Path property from a Request instead of trimming the entire URL.
- _defaultUmbPaths is useless, this can just be a string.
- urlPath gets split by forward slash for PluginController, while this should just count slashes and avoid unnecessary allocations.

Created originally as a discussion here #11640 but this seems completely ignored.

### Steps to reproduce

Just run Umbraco.

### Expected result / actual result

Should be optimized.

**Comment by Zeegaan** [comment]
Hey @Nuklon, I agree it is inefficient, as you've already pointed out some good places to improve I will mark this as up for grabs, as we'd love some help with this 🙌

**Comment by Nuklon** [comment]
> Hey @Nuklon, I agree it is inefficient, as you've already pointed out some good places to improve I will mark this as up for grabs, as we'd love some help with this 🙌

I had already created a PR for v9 but nothing happened with it. I can recreate for v11 if wanted...

**Comment by Zeegaan** [comment]
@Nuklon Yep we would love that 🙌

**Comment by Nuklon** [comment]
> @Nuklon Yep we would love that 🙌
Great!
https://github.com/umbraco/Umbraco-CMS/pull/13743
