### ISSUE TITLE
Examine multi searcher in dashboard

### ISSUE THREAD

**Issue by bjarnef** [umbraco/Umbraco-CMS#13749]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

10.4.0

### Bug summary

When configuring a multi searcher in Examine, I can search using this from Examine dashboard.

However I noticed when changing page number, the request change where it use a different `searcher`, so if I go from page 1 to page 2 and back to page 1, there are shown different data than the initial search.

![image](https://user-images.githubusercontent.com/2919859/215067989-d82ebf8b-46e1-49fd-9a37-12a3b46ce060.png)

![image](https://user-images.githubusercontent.com/2919859/215068092-fd38f1d4-575e-45b4-88bf-c8f8cf8f4e78.png)

### Steps to reproduce

Register a multi searcher and search this from Examine dashboard.

```
public class SearchComposer : IComposer
{
    public void Compose(IUmbracoBuilder builder)
    {
        ...

        builder.Services.AddExamineLuceneMultiSearcher("CourseSearcher", new[] {
            "CourseInstanceIndex",
            "ExternalIndex"
        });
    }
```

The `CourseInstanceIndex` is the custom index name, so not sure why it requests this as `searcher` as the searcher name is "CourseSearcher".

It seems to be related to this: https://github.com/umbraco/Umbraco-CMS/blob/33adbf41fa1f5c5d0759c70a7116114107addf56/src/Umbraco.Web.UI.Client/src/views/dashboard/settings/examinemanagement.controller.js#L85-L93

I would expect to get same result on page on initial search and when switching page number and go back to page 1.

**Comment by Zeegaan** [comment]
Hmmm, I cannot reproduce this 🤔 
All my network calls use the proper multi searcher, this is me using your code example: 
![image](https://user-images.githubusercontent.com/70372949/215104963-0c398db8-6772-48b5-896c-ba1829be52d7.png)

**Comment by bjarnef** [comment]
@Zeegaan it doesn't happen if I expand the CourseSearcher group and search e.g. "Test" and go throgh the paging.

But it I expand "CourseInstanceIndex" group, then click back link at top and expand CourseSearcher group and make a search.

I guess this is because `vm.selectedIndex` now has value (which isn't reset when clicking back link), so it actually use that index as searcher: https://github.com/umbraco/Umbraco-CMS/blob/33adbf41fa1f5c5d0759c70a7116114107addf56/src/Umbraco.Web.UI.Client/src/views/dashboard/settings/examinemanagement.controller.js#L181

**Comment by Zeegaan** [comment]
Hmmm I still cannot seem to replicate this, this is me on the `contrib` branch: 
I'm trying to go into a index first, and then click the back-link and then to course searcher, still seems like when searching it has the correct searchername
![CorrectSearcherName](https://user-images.githubusercontent.com/70372949/220102215-782ec280-21e0-489f-a82b-16c46d882d94.gif)
 Am I doing something wrong here ? 🤔

**Comment by bjarnef** [comment]
@Zeegaan yes, I get the correct searcher on page 1, but then try to go to page 2.
Now the payload is `searcherName=CourseInstanceIndex&query=test&pageIndex=0`

https://user-images.githubusercontent.com/2919859/220112722-0c41ce8d-5f87-4127-a288-80924222860d.mp4

**Comment by Zeegaan** [comment]
Ah, yep was missing the pages! I can reproduce this! I am marking this up for grabs as you already have provided great insight as to where the error might originate from 🙌

**Comment by bjarnef** [comment]
@Zeegaan I think this should fix this issue, but haven't tested it yet 😄
https://github.com/umbraco/Umbraco-CMS/pull/13866
