### ISSUE TITLE
Azure AD Integration in backoffice

### ISSUE THREAD

**Issue by Brighty28** [umbraco/Umbraco-CMS#13745]
Sorry but I am on Umbraco version 10.3.2 / 10.4.0 and none of the above works for me at all have tried looking at the updated [readme](https://github.com/umbraco/UmbracoDocs/blob/main/umbraco-cms/reference/security/authenticate-with-active-directory.md) and adding this snippet of code 
` options.UserInformationEndpoint = "https://graph.microsoft.com/v1.0/me?$select=otherMails,displayName,givenName,surname,id";
                                options.ClaimActions.MapCustomJson(ClaimTypes.Email, x =>
                                {
                                    return x.GetProperty("otherMails").EnumerateArray().First().ToString();
                                });`
but no luck I have also tried various other options in respect to email so **email** **emailaddress** all with no luck am I missing something as I am in the early stages of a project and stuck on this.

**Edit**: With the "AzureB2CBackofficeExternalLoginProviderOptions" code above I link a Microsoft account by login in through Umbraco the normal with linking it here
![image](https://user-images.githubusercontent.com/6204366/214946038-b45efc74-7136-43af-88b8-812f56cbe852.png)
Then if I log out and click the sign-in with Microsoft button below
![image](https://user-images.githubusercontent.com/6204366/214946422-cc0d7dc0-035f-40c1-8f79-fd9b5aeade33.png)
Its fine however when logged in and unlinking my Microsoft account in Umbraco and then logging out back in via the sign-in with Microsoft I get the blank screen as mentioned above by others.

_Originally posted by @Brighty28 in https://github.com/umbraco/Umbraco-CMS/issues/13100#issuecomment-1405588253_

**Comment by Zeegaan** [comment]
Hi @Brighty28 thanks for reporting!
Its a hard requirement for Users to have an email, so unfortunately its not something we can do anything about on our end 😞 
If you want to use a custom AD setup, I recommend using OpenIDConnect as that works out of box.
Else maybe you can get help for your setup on our discord / forum 👍 
I can also recommend JBreuer's example on how he setup AzureB2c up with openIdConnect here: https://github.com/jbreuer/Umbraco-OpenIdConnect-Example
