### ISSUE TITLE
Unable to use internal Dtos

### ISSUE THREAD

**Issue by wtct** [umbraco/Umbraco-CMS#13771]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

10.4.0

### Bug summary

Hi,

It is possible to access IUmbracoDatabase : IDatabase (NPoco database) for example through IScopeProvider, however some Dtos in the Umbraco.Cms.Infrastructure.Persistence.Dtos namespace are internal and we are not able to build queries in the convenient way with the Umbraco CMS tables.

It's worth to mention that we can find examples of public Dtos in the same namespace.

Are those internal access modifiers set intentionally or by mistake?

### Steps to reproduce

Try to create query with DocumentTypeDto.

**Comment by kjac** [comment]
Hi @wtct,

The DTOs are meant to be marked as internal. The ones that are public are wrongfully so - but we can't change that now without introducing breaking changes 🙈 

As a general rule you're not supposed to query the database using these DTOs at all. They are considered an implementation detail for the database layer. 

The "lowest" layer you should be coding against is the service layer, using the services to access the domain types (i.e. `ContentType`, not `ContentTypeDto`). If you're finding yourself wanting to use the underlying DTOs, you are likely about to go down a wrong path. 

For further assistance I would advise you to get in touch with the friendly people in [the forum](https://our.umbraco.com/forum).

**Comment by wtct** [comment]
Thanks @kjac for your response.

I see your point of view. However, could you please consider situation when you have a custom table with foreign keys to Umbraco tables and you want to create query with joins?

Now, with internal Dtos, it is not possible to do it elegant way.. You have to write full, custom T-SQL with joins.

**Comment by kjac** [comment]
Hi @wtct

If that is your use case you can create your own DTO to query the Umbraco tables. I would advise against it, since the DB is an implementation detail in the grand scheme of things and the Umbraco tables might change over time, but nothing is preventing you from doing so.

**Comment by wtct** [comment]
Hi @kjac,

Yes, I know I can create own DTOs but it will be still weird, because I know that those DTOs exist in core. Moreover, I need to be aware of scheme changes.

Maybe built in DTOs could be public or protected with additional comment?

If some of the DTOs are public currently and no one noticed it earlier it's probably better to change them all to public instead of internal. There will be no breaking changes.

If any developer is using DTOs, he probably knows what he is doing and needs them. Do you agree?
