### ISSUE TITLE
UmbracoContext IsFrontEndUmbracoRequest() is returning true for requests in the backend

### ISSUE THREAD

**Issue by d-gibbs** [umbraco/Umbraco-CMS#13773]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

11.0.0

### Bug summary

I'm attempting to use `UmbracoContext.IsFrontEndUmbracoRequest()` within a Block grid item partial to determine whether the current browsing context is within the frontend or the backend of the site.

I'm finding that the method is returning `true` for both the frontend and the backend, specificially when browsing the `Content` app/tree.

### Specifics

The method seems to rely on a `PublishedRequest` being present to determine if the frontend is being browsed or not:

[IsFrontEndUmbracoRequest()](https://github.com/umbraco/Umbraco-CMS/blob/33adbf41fa1f5c5d0759c70a7116114107addf56/src/Umbraco.Core/Extensions/UmbracoContextExtensions.cs#L13)

Is checking the `PublishedRequest` here sufficient? I'm trying to think of cases where a published request would not exist when editing content pages in the backend?

### Steps to reproduce

Call the method from a partial view that get's rendered by the block grid, e.g:

```
@if (UmbracoContext is not null && UmbracoContext.IsFrontEndUmbracoRequest())
{
     <strong>Frontend</strong>
}
else
{
    <strong>Backend</strong>
}
```

### Expected result / actual result

**Expected**: 
Method to return true when the user is browsing the frontend and false when browsing the backend e.g. /umbraco

**Actual**: 
Method returns true in all cases

**Comment by kjac** [comment]
Hi there @d-gibbs,

I'm not entirely sure I follow... when is your partial view not rendered as part of a frontend rendering?

The logic is sane, though; `IUmbracoContext.PublishedRequest` is only ever _not_ null when a frontend rendering (a request to published content) is happening.

**Comment by d-gibbs** [comment]
@kjac "_when is your partial view not rendered as part of a frontend rendering_" - Sorry, that isn't what I'm suggesting here.

The partial is loaded for both frontend and backend requests. It's a block grid item view file.

For the backend, It gets loaded when browsing the `Content` section:

![image](https://user-images.githubusercontent.com/59481722/216967844-f32097bf-08ba-4f7d-a92a-0defd3207bb4.png)

We have some code in the partial which needs to behave differently if loaded whilst in the backend and we'd like to use this helper. Does that make sense?

If the helper isn't appropriate for this purpose, is there something that is?

Thank you

**Comment by kjac** [comment]
Hi again @d-gibbs,

I get what you're trying to do. However, I assume the backend rendering is simulating a frontend request in order to render the block grid item using the same partial view as is used to render the frontend - otherwise I'm quite sure things would be failing miserably, and `IUmbracoContext.PublishedRequest` would also be unset in the request. 

You can try to use `UmbracoRequestPaths.sBackOfficeRequest` instead but I doubt it will make any difference, if my assumption above is correct.

My best bet is that you need to create some sort of explicit state/context while rendering your views for backend (a querystring variable maybe?) that you can utilize in your view logic.

In either case, this really doesn't seem to be a bug in the block grid, so I'm closing this issue. I reckon the friendly people at [the forum](https://our.umbraco.com/forum) might be able to help you out more with this.

**Comment by d-gibbs** [comment]
@kjac - Thanks for getting back to me.

> I assume the backend rendering is simulating a frontend request in order to render the block grid item using the same partial view as is used to render the frontend - otherwise I'm quite sure things would be failing miserably, and IUmbracoContext.PublishedRequest would also be unset in the request.

I agree that's what most likely is happening but the CMS ultimately knows what context its currently rendering in and my point is the `IsFrontEndUmbracoRequest()` method should be clever enough to know this (since it's reusing a frontend partial) and not simply rely on there being a `PublishedRequest` item in context.

I don't believe there is a bug with block grid but I do think this method could be smarter about how to determines a frontend request since it does not work in certain contexts and I don't believe this is something the developer should have to implement themselves.

**Comment by markadrake** [comment]
Just came here to ditto on the above. I'm using the Block Previews project to render Razor in the backoffice (Block List and Block Grid). Something in Umbraco or this package always causes `IsFrontEndRequest()` to return true. I raised an issue over there too:

https://github.com/rickbutterfield/Umbraco.Community.BlockPreview/issues/56
