### ISSUE TITLE
BackOffice Preview fails when AddTrailingSlash is false due to pathing of lazyload

### ISSUE THREAD

**Issue by Nysosis** [umbraco/Umbraco-CMS#13785]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

10.4.0

### Bug summary

The path to lazy load in the https://github.com/umbraco/Umbraco-CMS/blob/release-10.4.0/src/Umbraco.Cms.StaticAssets/umbraco/UmbracoBackOffice/Preview.cshtml#L110 does not correctly resolve when a site is configured with AddTrailingSlash to false

This is because the lazyload URL is using parent pathing (`../lib/lazyload-js/LazyLoad.min.js`), and ends up being resolved to `~/lib/lazyload-js/LazyLoad.min.js` instead of `~/umbraco/lib/` when there is no slash at the end of `~/umbraco/preview`. 

https://github.com/umbraco/Umbraco-CMS/blob/release-10.4.0/src/Umbraco.Cms.StaticAssets/umbraco/UmbracoBackOffice/Default.cshtml#L131 handles this correctly by way of path combination of the backoffice root

### Specifics

I've only verified this in Mozilla browsers

### Steps to reproduce

1) Create a new Umbraco Installation
2) Update the appsettings.json to have CMS.RequestHandler.AddTrailingSlash to be false
3) Create a page and save & preview
4) View network tab

![image](https://user-images.githubusercontent.com/5476382/216813320-facf675f-d8a1-4b5f-89f6-9bc0874aadc7.png)

**Comment by kjac** [comment]
Hi @Nysosis 👋 

I can't replicate this on V10 nor V11. Preview still loads on `/umbraco/preview/?id={ID}` when `AddTrailingSlash` is set to `false`:

![image](https://user-images.githubusercontent.com/7405322/217454039-40efc3b7-de4b-4304-a122-9f3da592dfa3.png)

Are you doing something that might interfere with the default behavior? It could be:
- some SEO redirect rules that strips all trailing slashes? 
- a custom `ReservedPaths` setting that somehow breaks the preview?

**Comment by Zeegaan** [comment]
Hi there 👋 since is been a while that we haven't heard from you, and we cannot reproduce it. I'm going to go ahead and close this issue! 
Do not hesitate to re-open this if you find anymore information or reproduction steps 🙏

**Comment by awavevladimirmironov** [comment]
I have the similar problem at Linux server :Save and Preview" not look at umbraco/lib but check /lib/  . Can`t understand why. I checked all redirects and configurations on the server. and inside code. and can`t find the issue.
