### ISSUE TITLE
Key Storage on Shared Hosting

### ISSUE THREAD

**Issue by craigs100** [umbraco/Umbraco-CMS#13784]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

V11.1

### Bug summary

When deployed to production on shared hosting V11.1 sites produce errors such as "An exception was thrown while deserializing the token" & "The temp data cookie ".AspNetCore.Mvc.CookieTempDataProvider" could not be loaded". Due to the sites not having access to the root key storage facility in a multi-tenant environment.

### Specifics

When deployed to production on shared hosting the site produces errors such as:-

```
An exception was thrown while deserializing the token.
Microsoft.AspNetCore.Antiforgery.AntiforgeryValidationException: The antiforgery token could not be decrypted.
 ---> System.Security.Cryptography.CryptographicException: The key {097d70f4-4775-4957-bae9-fa22c0724e2d} was not found in the key ring. For more information go to http://aka.ms/dataprotectionwarning
   at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector.UnprotectCore(Byte[] protectedData, Boolean allowOperationsOnRevokedKeys, UnprotectStatus& status)
   at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector.Unprotect(Byte[] protectedData)
   at Microsoft.AspNetCore.Antiforgery.DefaultAntiforgeryTokenSerializer.Deserialize(String serializedToken)
   --- End of inner exception stack trace ---
   at Microsoft.AspNetCore.Antiforgery.DefaultAntiforgeryTokenSerializer.Deserialize(String serializedToken)
   at Microsoft.AspNetCore.Antiforgery.DefaultAntiforgery.GetCookieTokenDoesNotThrow(HttpContext httpContext)
```

And 

```
The temp data cookie ".AspNetCore.Mvc.CookieTempDataProvider" could not be loaded.
System.Security.Cryptography.CryptographicException: The key {097d70f4-4775-4957-bae9-fa22c0724e2d} was not found in the key ring. For more information go to http://aka.ms/dataprotectionwarning
   at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector.UnprotectCore(Byte[] protectedData, Boolean allowOperationsOnRevokedKeys, UnprotectStatus& status)
   at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector.Unprotect(Byte[] protectedData)
   at Microsoft.AspNetCore.Mvc.ViewFeatures.CookieTempDataProvider.LoadTempData(HttpContext context)
```
   
These are occurring on shared hosting, not on local dev machines. Several reports of same on Discord.

My particular hoster's knowledgebase article explains what's going on and suggests a remedy that I have so far failed to implement due to the way startup.cs is written / my own shortcomings:-
https://www.webwiz.net/kb/web-hosting/dotnet-core-key-storage.htm

While I consider this to be a bug as we can no longer safely deploy to shared hosting, it's also a feature request. Could we have the startup.cs written in such a way that _env is available in the ConfigureServices section, maybe have a section commented out, and with a var for the required path if needed?

We should be be able to run Umbraco on shared hosting and not just UCloud or a dedicated, single use machine as we have always been able to.

### Steps to reproduce

Deploy a working V11.1 site from your development machine to shared hosting.

### Expected result / actual result

Expected: Runs without exceptions
Actual: Runs with exceptions as detailed in Specifics above

**Comment by kjac** [comment]
Hi there @craigs100,

Thank you for reaching out.

If by `_env` you mean the private field in `Startup`, you can access that directly within the `Startup` methods:

![image](https://user-images.githubusercontent.com/7405322/216957715-a523e905-d3ec-454c-a4ed-1adb89399e3d.png)

![image](https://user-images.githubusercontent.com/7405322/216957604-c2864b59-1993-4f15-b831-652fbd1754b4.png)

I'm not sure what you need `_env` for, though. Following the guidelines from your shared hosting provider, it seems you should be able to change the key storage from within `ConfigureServices` like this:

```csharp
public void ConfigureServices(IServiceCollection services)
{
    services.AddDataProtection()
        .PersistKeysToFileSystem(new DirectoryInfo(@"D:\HostingSpaces\example\example.com\data\keys\"));

    services.AddUmbraco(_env, _config)
        .AddBackOffice()
        .AddWebsite()
        .AddComposers()
        .Build();
}
```

Remember to add `using Microsoft.AspNetCore.DataProtection;` to `Startup.cs`.

I'm going to close this issue now, as I don't really consider it a bug. If I have entirely misunderstood you, please feel free to reopen the issue with additional details 😄

**Comment by craigs100** [comment]
Hi @kjac,

Thanks for the response, you are absolutely right. I realised from a Discord chat about 15 mins ago that _env was already available via DI. So the code I'll be using is this:-

```
       public void ConfigureServices(IServiceCollection services)
        {
            if (_env.IsProduction()) {
                services.AddDataProtection()
                    .PersistKeysToFileSystem(new DirectoryInfo(@"D:\HostingSpaces\myuser\mysite.co.uk\data\keys\"));
            }
            .....rest of code here.
     } 
```
However, as it's going to be a common issue on shared hosting I might put forward a comment for the docs so it's there for others.

Thanks again :)

**Comment by kjac** [comment]
Thanks for getting back to me @craigs100 👍 

I love your instinct to put it in the docs ❤️ however, I think this concrete solution/workaround for key storage is very specific to that hosting provider; other providers may have other means of handling keys. So.. if you do make a docs PR, make sure it's not too tainted by this concrete hosting provider 😄

**Comment by craigs100** [comment]
Absolutely, the point is just that if you don't have access to the default .net keys location because you're on a multi-tenanted platform you might need to provide another one. I'll be sure to word it as generically as I can :)

**Comment by nul800sebastiaan** [comment]
For future readers, a bit of code that can be dropped into any project without touching `Startup.cs`

```csharp
using Microsoft.AspNetCore.DataProtection;
using Umbraco.Cms.Core.Composing;

namespace MyProject;

public class SharedHostingConfiguration : IComposer
{
    public void Compose(IUmbracoBuilder builder)
    {
        var environmentName = builder.Config.GetChildren()
            .First(x => x.Key is "ENVIRONMENT" or "ASPNETCORE_ENVIRONMENT").Value;

        if (environmentName != "Production") 
            return;
        
        var path = AppContext.BaseDirectory + "\\dataprotectionkeys";
        builder.Services.AddDataProtection().PersistKeysToFileSystem(new DirectoryInfo(path));
    }
}
```

Unfortunately we can't use dependency injection in an `IComposer` and it's the only place that runs early enough to actually be able to update this setting befor the app starts. 

So I had to rely on checking config files, a round of Googling tells me the environment name is either in `DOTNET_ENVIRONMENT`, of `ASPNETCORE_ENVIRONMENT` - but..! The `DOTNET_` prefix gets stripped, so that's why we're only looking for the key `ENVIRONMENT`.

Additionally, I had to use the `AppContext` to construct a directory to put the keys in.

**Comment by nul800sebastiaan** [comment]
> Anyway, what is the down-side of using startup.cs rather than going to the trouble of a whole new Composer? 

Easier to drop a .cs file in and not have to worry if we ever update `Startup.cs` that you will have to make sure that your customizations are still there, that's all. 

Composer just does the exact same thing but in a separate file. Not more nor less secure.

**Comment by nul800sebastiaan** [comment]
Please note that the default algorithms are the ones you set them to, so you shouldn't need to override them: https://learn.microsoft.com/en-us/aspnet/core/security/data-protection/configuration/overview?view=aspnetcore-7.0#changing-algorithms-with-usecryptographicalgorithms

You can see this in the generated file (`descriptor` node) as well, when you don't specify the algorithms at all:

```xml
<?xml version="1.0" encoding="utf-8"?>
<key id="9b49b04d-ffc2-4363-8df0-ea20d2265b6f" version="1">
  <creationDate>2023-02-28T09:52:36.4200642Z</creationDate>
  <activationDate>2023-02-28T09:52:36.4137251Z</activationDate>
  <expirationDate>2023-05-29T09:52:36.4137251Z</expirationDate>
  <descriptor deserializerType="Microsoft.AspNetCore.DataProtection.AuthenticatedEncryption.ConfigurationModel.AuthenticatedEncryptorDescriptorDeserializer, Microsoft.AspNetCore.DataProtection, Version=7.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60">
    <descriptor>
      <encryption algorithm="AES_256_CBC" />
      <validation algorithm="HMACSHA256" />
      <masterKey p4:requiresEncryption="true" xmlns:p4="http://schemas.asp.net/2015/03/dataProtection">
        <!-- Warning: the key below is in an unencrypted form. -->
        <value>w9FpQxyXCbZnwAakfdc0DpL9OD/osDLeFco+1Q2LIFTD/qiV463C3aMonxR9/CVUkWpaaZy75VzIg/UKqa5sow==</value>
      </masterKey>
    </descriptor>
  </descriptor>
</key>
```

Anyway  an updated Composer, if you really need to force a certain algorithm, would be: 

```csharp
using Microsoft.AspNetCore.DataProtection;
using Umbraco.Cms.Core.Composing;

namespace MyProject;

public class SharedHostingConfiguration : IComposer
{
    public void Compose(IUmbracoBuilder builder)
    {
        var environmentName = builder.Config.GetChildren()
            .First(x => x.Key is "ENVIRONMENT" or "ASPNETCORE_ENVIRONMENT").Value;

        if (environmentName != "Production") 
            return;
        
        var path = AppContext.BaseDirectory + "\\dataprotectionkeys";
        builder.Services
            .AddDataProtection()
            .PersistKeysToFileSystem(new DirectoryInfo(path))
            .UseCryptographicAlgorithms(new AuthenticatedEncryptorConfiguration
            {
                EncryptionAlgorithm = EncryptionAlgorithm.AES_256_CBC,
                ValidationAlgorithm = ValidationAlgorithm.HMACSHA256
            });
    }
}
```

Or shortened, if you just want to do the same on local machine: 


```csharp
using Microsoft.AspNetCore.DataProtection;
using Umbraco.Cms.Core.Composing;

namespace MyProject;

public class SharedHostingConfiguration : IComposer
{
    public void Compose(IUmbracoBuilder builder)
    {        
        var path = AppContext.BaseDirectory + "\\dataprotectionkeys";
        builder.Services
            .AddDataProtection()
            .PersistKeysToFileSystem(new DirectoryInfo(path))
            .UseCryptographicAlgorithms(new AuthenticatedEncryptorConfiguration
            {
                EncryptionAlgorithm = EncryptionAlgorithm.AES_256_CBC,
                ValidationAlgorithm = ValidationAlgorithm.HMACSHA256
            });
    }
}
```

**Comment by JasonElkin** [comment]
Just a note that this will blow up on non-windows environments.

Swap this:
```csharp
var path = AppContext.BaseDirectory + "\\dataprotectionkeys"
```
With this:
```csharp
var path = Path.Combine(AppContext.BaseDirectory, "dataprotectionkeys");
```
