### ISSUE TITLE
Blazor throws error "The list of component records is not valid" when a macro containing a blazor component is used with a layout that renders a blazor component

### ISSUE THREAD

**Issue by datvunguyen** [umbraco/Umbraco-CMS#13792]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

11.1.0

### Bug summary

I have a site layout that renders a blazor component for a search bar + results for each page. This blazor component in the layout works fine and the pages renders without issue, provided there is no macro in the page body that contains another blazor component. Once a macro that contains a blazor component is dropped into a page grid, the error "The list of component records is not valid" is thrown by blazor.server.js, seen in the browser console, and the page fails to render any elements.

### Specifics

The implementation of my site has a Blazor component in the layout code that displays a search input and the search results directly below it. Naturally, I need that search bar on every page. Many of the individual pages are intended to render another blazor component in the body area that carries out different functionality depending on the page. I created macros to contain the Blazor components and allow them to be dropped into the page grid, but when I place the macro on the page (with the search Blazor component in the layout), Blazor crashes. However, when I remove the search Blazor component from the layout code, the page and body Blazor component work just fine. Likewise, the search bar functionality has no errors and works when no macro containing a Blazor component is present in the body.

I did find a workaround. It was to build a separate Umbraco template for each page containing a Blazor component in the body. Obviously I would not need macros if the template is responsible for rendering all the elements in the body. This allowed me to use both the search and the body Blazor component together without problems. The templates are using the layout with the search Blazor component, and the template code is responsible for only rendering the body section which contains the page-specific Blazor components.

However, I had plans to develop re-useable Blazor components that can also be moved around in the page grid.  This is not possible because I can't render the Blazor components in  macros in this scenario.

Here's how I implement a Blazor component rendered within a macro:

1) Create a macro in Umbraco 

2) Implement the Blazor component in the code project (let's call it MyBlazorComponent.razor)

3) Render the Blazor component within the macro partial view with this line of code:

 `   @(await Html.RenderComponentAsync<MyBlazorComponent>(RenderMode.Server, new { someParameter=someValue }))`

4) Drop the macro into a page's grid and publish.

I am using Blazor Server because the business requirements dictates that the data operations be carried out centrally on the server.

I have tried to use RenderMode.ServerPrerendered on both the search component and body component, and this would solve the problem only if the body blazor component does not have child components. If there are child components, the same error occurs. I then thought I should set the render mode of the child components. However, within a Blazor component's code, there doesn't seem to be a way to set the render mode of the child component, as far as I know. It seems you can only do so in .cshtml files, not .razor files. I use the component's tag to render a child component within the parent component, like so:

`<ChildComponentName someParameter="someValue" />`

Unfortunately, most of the Blazor components I've developed have child components.

I have tried all the solutions offered by StackOverflow but none resolves the issue, so I figure it may be a problem specific to Umbraco.

My site is built in Umbraco 11.1.0, .NET 7. I've only tested in Chrome browser so far.

### Steps to reproduce

1. In an Umbraco .NET project, make sure everything is properly set up to use Blazor according to the documentation.
2. Create a Blazor component in the .NET project. This is to be the blazor component that is rendered by the layout code. In the blazor component, just display some static text.
3. Create another Blazor component in the .NET project. This is to be the blazor component that is rendered in a macro partial view. Just display some static text in the component.
4. Create a layout code file in the .NET project. In it, render the blazor component created in step 2 by using this code: `@(await Html.RenderComponentAsync<BlazorComponentName>(RenderMode.Server))`. Make sure the layout has a RenderBody() call. Make sure the layout (or its master layout) includes blazor.server.js.
5. Create a macro in Umbraco.
6. In the macro partial view code, render the blazor component created in step 3 using the Html.RenderComponentAsync method.
7. Create a template in Umbraco.
8. In the template view code, set the Layout to be the layout created in step 4, and then render the page grid: `@Html.GetGridHtml(Model, "layout")`
9. Create a document type that uses the template created in step 7.
10. In Umbraco, create a page with the document type created in step 9. Make sure the template created in step 7 is selected.
11. In the page grid, add the macro created in step 5.
12. Save and publish.
13. Open the page in a browser (open the browser console to see the error).
### 

### Expected result / actual result

Expected result: The entire page renders all page content and blazor components execute their functionality.

Actual result: An error is thrown by blazor.server.js, saying "The list of component records is not valid", and the page fails to render anything at all.

**Comment by kjac** [comment]
Hi @datvunguyen,

Thank you for your very thorough issue report 💪 

Umbraco is not build specifically for Blazor rendering, so I'm afraid we can't help you a whole lot here. 

My best advice is to generally avoid macros though. They very likely expect to be rendering in a web context, because that is what they were explicitly built for. The future of macros is also somewhat uncertain - they may be replaced with something else a few major versions from now.

Perhaps you can achieve the same functionality by building block grid elements instead of macros? The [docs article](https://docs.umbraco.com/umbraco-cms/fundamentals/backoffice/property-editors/built-in-umbraco-property-editors/block-editor/block-grid-editor) on the block grid should help get you started down that path 😄 

I'm going to close this issue, as I do reckon macro rendering work as it should (as best it can, assuming you're in a web context). If for some reason macros do not render correctly in a web context, please feel free to reopen this issue.
