### ISSUE TITLE
Missing Danish 2FA translations

### ISSUE THREAD

**Issue by AndersBrohus** [umbraco/Umbraco-CMS#13793]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

10.4.0 and 11.1.0

### Bug summary

In Umbraco 10.4.0 and 11.1.0 there are some 2FA translation that are missing like on the following screenshot,

![image](https://user-images.githubusercontent.com/9005889/217186269-011a7262-3318-4f3e-9900-cb4f0ae7f8ad.png)

### Steps to reproduce

Simply spin up a new site

### Expected result / actual result

A full Danish experience :)

But i'll create the missing translations now and create a PR. :)

**Comment by kjac** [comment]
Thank you so much @AndersBrohus ❤️
