### ISSUE TITLE
OData: not working with Umbraco Forms

### ISSUE THREAD

**Issue by merijng** [umbraco/Umbraco-CMS#13801]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

11.1.0 / 10.4.0

### Bug summary

Adding OData to Umbraco, does not work with the Umbraco Forms module. For example: sending a form will result in an error.

It did work in Umbraco version 10.3.2. I've looked into the Umbraco release notes: I think pull request [#13103](https://github.com/umbraco/Umbraco-CMS/pull/13103) is causing this bug.

### Specifics

The error is:
`InvalidOperationException: The following endpoints with a duplicate endpoint name were found.

Endpoints with endpoint name 'd006978a-2023-4550-9905-8f0ab1c0736b':
Microsoft.AspNetCore.OData.Routing.Controllers.MetadataController.GetMetadata (Microsoft.AspNetCore.OData)
Microsoft.AspNetCore.OData.Routing.Controllers.MetadataController.GetMetadata (Microsoft.AspNetCore.OData)

Endpoints with endpoint name '5f24343d-bbc7-439b-a31d-7e77987aee13':
Microsoft.AspNetCore.OData.Routing.Controllers.MetadataController.GetServiceDocument (Microsoft.AspNetCore.OData)
Microsoft.AspNetCore.OData.Routing.Controllers.MetadataController.GetServiceDocument (Microsoft.AspNetCore.OData)`

### Steps to reproduce

- Install a brand new Umbraco instance, if you haven't
  - dotnet new install Umbraco.Templates
  - dotnet new umbraco --name MyProject
  - Follow the Umbraco installation instructions
- Now install Umbraco Forms NuGet package, and the AspNetCore OData NuGet package 
  - (`Umbraco.Forms` and `Microsoft.AspNetCore.OData`)
- Create a content page including a form and see it working
- Now, add the following to your startup.cs
```CSHARP
public void ConfigureServices(IServiceCollection services)
        {
            services.AddControllers()
                .AddOData(options => options
                .Select()
                .Expand()
                .Filter()
                .OrderBy()
                .SetMaxTop(1000)
                .Count()
                .AddRouteComponents("dealermodule", GetEdmModel())
            );
        }

private static IEdmModel GetEdmModel()
        {
            ODataConventionModelBuilder builder = new ODataConventionModelBuilder();
            //builder.EntitySet<Book>("Books");
            //builder.EntitySet<Press>("Presses");
            return builder.GetEdmModel();
        }
```
- Submit the form once again, notice it doesn't work anymore
- Remove .AddRouteComponents from the ConfigureServices, and notice it works once again

Also tried to add Global => ReservedPaths to the Web.config, however [this doesn't seem to work](https://our.umbraco.com/forum/umbraco-9/106305-umbraco-9-reservedpaths)?

### Expected result / actual result

A working form, when OData is added to Umbraco

---
_This item has been added to our backlog [AB#26871](https://dev.azure.com/umbraco/243e7927-03b2-44e2-908f-d4ac7ea5daaa/_workitems/edit/26871)_

**Comment by merijng** [comment]
If anyone needs a workaround, remove the ODATA Metadatacontroller. For most generic occasions, this should not be an issue.

Add the ConfigureApplicationPartManager function, see below.

````CSHARP
builder.Services.AddControllers()
				.ConfigureApplicationPartManager(manager =>
				{
					manager.FeatureProviders.Remove(manager.FeatureProviders.OfType<ControllerFeatureProvider>().FirstOrDefault());
					manager.FeatureProviders.Add(new RemoveMetadataControllerFeatureProvider());
				})
				.AddOData(options => options
                .Select()
                .Expand()
                .Filter()
                .OrderBy()
                .SetMaxTop(1000)
                .Count()
				.AddRouteComponents("dealermodule", GetEdmModel());
```

```CSHARP
public class RemoveMetadataControllerFeatureProvider : ControllerFeatureProvider
{
  protected override bool IsController(TypeInfo typeInfo)
  {
    if (typeInfo.FullName == "Microsoft.AspNetCore.OData.Routing.Controllers.MetadataController")
    {
      return false;
    }
    
      return base.IsController(typeInfo);
  }
}
```

**Comment by bergmania** [comment]
I spend some time looking into this.. https://github.com/umbraco/Umbraco-CMS/pull/13103 definitely is the reason it does not work anymore, but that PR is not doing anything wrong. 

This error would have happened before, if one was using `LinkParser.ParsePathByEndpointName(name, path)`, which is a microsoft implementation. Adding `OData` seems to be the reason for duplicate route names, which makes this explode.

**Comment by bergmania** [comment]
I'll close this issue. I think your workaround is the best you can do, that will work in all cases.

Issue seems to be the same here, and it seems like an issue in OData 8, that the MetaDataController is using HttpMethodAttributes.
 https://stackoverflow.com/questions/69288969/duplicate-endpoint-route-on-same-controller-method-with-odata-8-x-and-route-attr

**Comment by merijng** [comment]
@bergmania The workaround is working for us. 

If you're sure that it is a bug on the OData side, then closing this issue seems legit.

Thanks!
