### ISSUE TITLE
SVG thumbnail not displaying in Umbraco.MediaPicker3 nested within Blocklist

### ISSUE THREAD

**Issue by digbyswift** [umbraco/Umbraco-CMS#13822]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

11.1.0

### Bug summary

We have created a blocklist datatype from which editors can build a list of a single element doc type. This element doc type has several text fields and a mediapicker which is resictred to SVG media types.

When building the list, the editor is able to select SVGs and it displays correctly. However, when the page is saved and/or published and revisited, when a blocklist element is opened, the SVG fails to display and continues to display the adjacent 3x loading dots.

![image](https://user-images.githubusercontent.com/1391597/218438042-56bc54d0-e2a0-47ac-82a7-9e724899973c.png)

### Specifics

Viewing the network tab of the browser, it is clear that a request for the SVG thumbnail is made and is completed, but for some reason isn't displayed.

We have found however that the SVG _does_ display under a couple of conditions:

 - When the 3x loading dots appear, if you change the focus by moving your mouse onto another element in the blocklist, or if you click on the missing SVG thumbnail itself, the SVG will load;
 - If the element doc type contains an RTE then the SVG loads fine.

Presumably these both indicate that there is a missing "loaded" step that the RTE has but that the media picker is missing for SVGs perhaps.

### Steps to reproduce

As described above, create a blocklist editor with a single element type containing an SVG-restricted media picker.

**Comment by elit0451** [comment]
Hi @digbyswift 👋 

Thanks for reaching out, I have tried to reproduce this but as you can see in the video below, the SVGs are successfully loaded when Saving, Saving & Publishing, etc. Let me know if I missed any steps 🙂 

https://user-images.githubusercontent.com/21998037/218702336-74deeb0c-1853-4161-8145-85d976946df7.mp4

**Comment by digbyswift** [comment]
> Hi @digbyswift 👋
> 
> Thanks for reaching out, I have tried to reproduce this but as you can see in the video below, the SVGs are successfully loaded when Saving, Saving & Publishing, etc. Let me know if I missed any steps 🙂

Thanks for the really quick reply. That's very thorough and also very odd. I don't believe you've missed any steps either. I'll review our implementation and update this ticket.

**Comment by elit0451** [comment]
Perfect! 💪

**Comment by elit0451** [comment]
Thanks for providing more information. I've tried again but unfortunately, I don't seem to be able to replicate the problem 🙁 



https://user-images.githubusercontent.com/21998037/218746462-5616ab47-582a-44b9-a04b-937676f8b274.mp4

**Comment by digbyswift** [comment]
Hi @elit0451 ok, I'm happy to close this. We'll reopen it if we can track down the specific issue affecting us but only if it is relevant. Thanks again.
