### ISSUE TITLE
Removing a currently used block from the Block Grid config bricks the backoffice

### ISSUE THREAD

**Issue by Nikkelmann** [umbraco/Umbraco-CMS#13834]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

11.1.0

### Bug summary

When a block is removed from the block grid configuration (either from the backoffice or programatically) the backoffice fails to load the page.

### Steps to reproduce

Using a clean install, setup a Block Grid with the default samples and add this editor to a doc type.
Add some content to the page.
![image](https://user-images.githubusercontent.com/3674690/219025719-c04feb2c-57a4-4055-98e6-1de16218d393.png)

Remove a block that was used on the page from the block grid config:
![image](https://user-images.githubusercontent.com/3674690/219025844-79ca244c-efd2-4213-b1c4-952f9d3d0b34.png)

### Expected result / actual result

The backoffice will no longer loads the grid:
![image](https://user-images.githubusercontent.com/3674690/219026184-13003232-940c-4713-8de9-4769bcdf44d1.png)

The expected behaviour was something along the lines of what the Block List does, when a block is removed from the config:
![image](https://user-images.githubusercontent.com/3674690/219027635-b372fb8b-29e8-4621-9ffa-23d82b21bf52.png)

![image](https://user-images.githubusercontent.com/3674690/219028106-f5bad52f-d570-4f4f-a537-7ba53f50da40.png)

![image](https://user-images.githubusercontent.com/3674690/219027810-0dbcd57e-545e-4834-bc45-40629a167e5e.png)

---
_This item has been added to our backlog [AB#26815](https://dev.azure.com/umbraco/243e7927-03b2-44e2-908f-d4ac7ea5daaa/_workitems/edit/26815)_

**Comment by elit0451** [comment]
Thank you for the detailed notes @Nikkelmann 💪 

The expected behaviour that you described is right on point. We will have a look at it 🙂

**Comment by nielslyngsoe** [comment]
Here is a fix in this PR: https://github.com/umbraco/Umbraco-CMS/pull/14148

**Comment by Zeegaan** [comment]
Cherre picked for v12
