### ISSUE TITLE
Label not working for Block Editors without AngularJS filter

### ISSUE THREAD

**Issue by LennardF1989** [umbraco/Umbraco-CMS#13833]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

11.1.0

### Bug summary

When I add a block to a Data Type of type "Umbraco.BlockGrid", setting the label of the Block has no effect on the actual name shown in the Content section.

### Steps to reproduce

0. Get project up and running with latest Umbraco from NuGet.
1. Add a Home doctype, set as root.
2. Add a Umbraco.BlockGrid data type it.
3. Add a "Block Test" doctype as an Element Type, set allow at root to true.
4. Go into datatype configuration and add the "Block Test", set the label to "Test123".
5. Go to the Content section, add the Home-node and add a block. Overlay will still say "Block Test" rather than "Test123". Adding the block will also display "Block Test" rather than "Test123".

### Expected result / actual result

The label that has been set is also respected.

**Comment by elit0451** [comment]
Thank you for reporting this @LennardF1989 💪 

I've tested it and you are right, a label composed of just text is overwritten by the element type name when a block is added to a content node. It seems like the label property "_[can use AngularJS template string syntax](https://docs.umbraco.com/umbraco-cms/fundamentals/backoffice/property-editors/built-in-umbraco-property-editors/block-editor/label-property-configuration)_", so I have managed to make it work in your example by setting the label as "_Test123 {{}}_".


I will mark this as up for grabs to see if you or someone else from the community wants to work on this 🙂

**Comment by Bakersbakebread** [comment]
working on this
