### ISSUE TITLE
SecuritySettings has null valeu for UserPassword and MemberPassword

### ISSUE THREAD

**Issue by niekvanderreest** [umbraco/Umbraco-CMS#13839]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

10.3.2

### Bug summary

After injecting SecuritySettings into my MemberController and adding a check om MemberPassword.RequiredLength causes an error because the field is NULL

### Specifics

I've tracked it down to the following lines of code in Umbraco.Cms.Core.Configuration.Models.SecuritySettings
Here you can see no default values are set for the 2 fields

```
/// <summary>
///     Gets or sets a value for the user password settings.
/// </summary>
public UserPasswordConfigurationSettings? UserPassword { get; set; }

/// <summary>
///     Gets or sets a value for the member password settings.
/// </summary>
public MemberPasswordConfigurationSettings? MemberPassword { get; set; }
```

### Steps to reproduce

Inject IOptions<SecuritySettings> intoany controller or class and observe NULL values for the 2 fields UserPassword and MemberPassword

### Expected result / actual result

I'd expect the results to be loaded in the SecuritySettings class and fallback to default settings for UserPassword and MemberPassword if not configured in appsetings.json

**Comment by bergmania** [comment]
Hi @niekvanderreest ..

Thanks for reporting..

Seems like those should just be removed from the SecuritySettings, as it is the intension to inject them directly using e.g. `IOptions<UserPasswordConfigurationSettings>`

**Comment by niekvanderreest** [comment]
Hi @bergmania, 

I had indeed found my way to the Member and User PasswordConfigurationSettings classes, the correctly return all info needed. Only other point is changing documentation to match, since the Member and User classes are not mentioned on the Configuration page: https://docs.umbraco.com/umbraco-cms/reference/configuration#managing-configuration

**Comment by Zeegaan** [comment]
This should hopefully be fixed by https://github.com/umbraco/Umbraco-CMS/pull/13859 as this adds obsolete messages 👍 
I've also made a docs issue here for the missing documentation: https://github.com/umbraco/UmbracoDocs/issues/4948

**Comment by elit0451** [comment]
Fixed in https://github.com/umbraco/Umbraco-CMS/pull/13859

I will close this since we created an additional issue for updating the documentation. 💪
