### ISSUE TITLE
ContentPickerValueConverter should be public

### ISSUE THREAD

**Issue by simonech** [umbraco/Umbraco-CMS#13858]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

11.0

### Bug summary

Why is `ContentPickerValueConverter` `internal` while all other value converters are `public`?

### Specifics

https://github.com/umbraco/Umbraco-CMS/blob/v11/dev/src/Umbraco.Core/PropertyEditors/ValueConverters/ContentPickerValueConverter.cs

See others:
https://github.com/umbraco/Umbraco-CMS/blob/v11/dev/src/Umbraco.Core/PropertyEditors/ValueConverters/MultipleTextStringValueConverter.cs
https://github.com/umbraco/Umbraco-CMS/blob/v11/dev/src/Umbraco.Core/PropertyEditors/ValueConverters/MediaPickerValueConverter.cs

### Steps to reproduce

Try writing an custom property editor that is just a content picker with some "preview" features, and try inheriting from that the core `ContentPickerValueConverter`.
You cannot.

### Expected result / actual result

While you should be able to do so, like you can for all other Value Converters

**Comment by simonech** [comment]
I mean, it's an easy fix that anyone can do as PR, but first would need to know if it was done on purpose or was just something forgotten by mistake

**Comment by Zeegaan** [comment]
@simonech Yep you are right, doesn't make sense to have it as the only internal one, seems like an error to me 👍 
I will mark this as up for grabs and as a great first issue 👍

**Comment by Zeegaan** [comment]
Fixed in https://github.com/umbraco/Umbraco-CMS/pull/13864 😁
