### ISSUE TITLE
Database install failing with custom default languages

### ISSUE THREAD

**Issue by WouterCeulemans** [umbraco/Umbraco-CMS#13852]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

10.4.0

### Bug summary

If you configure some languages in the `appsettings.json` which should be installed by default, when installing Umbraco with a SQL Server database, the installation fails.

### Specifics

Before installing Umbraco, you can configure some languages which should be installed by default.
Documentation: https://docs.umbraco.com/umbraco-cms/v/10.latest-lts/reference/configuration/installdefaultdatasettings
For example, add the following configuration to the `appsettings.json`.
```json
"Umbraco": {
  "CMS": {
    "InstallDefaultData": {
      "Languages": {
        "InstallData": "Values",
        "Values": [
          "nl-BE",
          "en-US",
          "fr-BE"
        ]
      }
    }
  }
}
```

When you install Umbraco with a SQL Server database the installation fails:
![Umbraco install failed](https://user-images.githubusercontent.com/6593444/219857783-5307f183-e8a8-487f-afa4-6cec0e799e40.png)

During install, the configured languages are inserted in the database without a specific id. The id should be generated and incremented automatically when inserting the language in the database.
https://github.com/umbraco/Umbraco-CMS/blob/daff9884a3d0ff0a90d0cde23b7565919647d5fe/src/Umbraco.Infrastructure/Migrations/Install/DatabaseDataCreator.cs#L1767-L1773

However, it looks like `IDENTITY_INSERT` is set to `ON` before the languages are inserted. Because of this, a value for the primary column `id` is required.
https://github.com/umbraco/Umbraco-CMS/blob/daff9884a3d0ff0a90d0cde23b7565919647d5fe/src/Umbraco.Infrastructure/Migrations/Install/DatabaseSchemaCreator.cs#L509-L513

For SQLite databases, this is not a problem because there is no such functionality.

### Steps to reproduce

- Configure some languages in the `appsettings.json` which should be installed by default. See above for an example.
- Install Umbraco with a SQL Server database

### Expected result / actual result

The database installation should be successful and the configured languages should be installed.

**Comment by Zeegaan** [comment]
Can definitely reproduce this, thanks for the great issue description 💪 
I am marking this as up for grabs, as we'd love some help with this issue 🙏
