### ISSUE TITLE
Rich text link picker not resolving correct variant when using .ValueFor()

### ISSUE THREAD

**Issue by joelmandell** [umbraco/Umbraco-CMS#13865]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

10.2.1

### Bug summary

Hi.
I have a server prerendered Blazor components and I'm experiencing some problems with fetching content based on different cultures. The problem seems to be with the IVariationContextAccessor that is in the PublishedValueFallback, that is passed on to this.Value() in the generated models.

Case: Page is starting out in swedish language (default/fallback). Switch to english and getting properties from content.

On subsequent calls the language of the VariationContext is changed from "en" to "sv", even if parameter "en" is passed as parameter to GetValue() on IPublishedContent prop. I am not sure why this occurs, but browsing around the code and debugging, it seems to be because of caching (IRequestCache) of VariationContext (HybridUmbracoContextAccessor) on the PublishedValueFallback object. To further specify the issue... it succeeds to fetch the content from a richtext-property according to CurrentCulture, but if it links to an english page it picks the swedish page instead.

In order to get away with that problem I am implementing my own "T? Value<T>", in the same namespace as the generated models (so that method is called instead of the one in PublishedElementExtensions). Using reflection I replace the VariationContext in PublishedValueFallback with a new one according to CultureInfo.CurrentCulture.TwoLetterIsoLanguage (that is changed by user selecting english instead of swedish) (and **only if it is different then CurrentCulture**)

I am available to respond to questions regarding this issue and clarifications. Without knowing for sure what the issue is, I am proposing an potential change: what if checking CurrentCulture against cached VariationContext. If they are not the same, update the cached VariationContext with a new one based on CurrentCulture? 

### Specifics

I might include an video at a later step here that take you through the steps (i.e. debugging and so on...).

### Steps to reproduce

You have to have content in multiple languages. Setup two languages (i.e. danish and english). Have danish as default/fallback.
A Settings-node with a Richtext (with links) property with vary by culture support.

Also add one Document Type as a page with vary by culture support (a simple view that prints out the richtext from settings-node).

Have a Server Prerendered Blazor Component that is rendered in the View for the simple start view/page.

Add content (with danish text) to the property on the settings node in danish first. Create a link to the danish page in that richtext. Set localization content for english on that property. Create a link to the english page in that richtext.

For example create a blazor component with two buttons, one for danish and one for english.
In the Blazor component have it render a string for example <div>@MyLocalizedSetting</div>.

In the callback for danish button
Set CurrentCulture to "da" and assign the settings property to MyLocalizedSetting. The text will be shown in danish and the link will be to the danish page.

In the callback for english button
Set CurrentCulture to "en" and assign the settings property to MyLocalizedSetting. The text will be shown in english but **the link will be to the danish page.**

### Expected result / actual result

Link in rendered text should be to the english page but is instead to the danish page (i.e. insert random language)...

**Comment by joelmandell** [comment]
I haven't delved deeper in the code base of Umbraco, but it seems to have with the sequence somewhere when picking {localLink:umb//document...}. Because the title of the a-tag is rendered according to the localization, but the link is pointed to the default/fallback-language. But it seems anyway to be connected with an cached VariationContextAccessor in the IRequestCache... 🤔

**Comment by joelmandell** [comment]
Here is a visual repro of the issue:

https://user-images.githubusercontent.com/109020/220210886-3b0f9e30-9656-4855-989e-7ebbcdc50090.mp4

**Comment by Zeegaan** [comment]
@joelmandell Great issue description, and love the video it really helped 💪 
This issue has already been reported here: https://github.com/umbraco/Umbraco-CMS/issues/12627
I will go ahead and close this for now, please feel free to re-open if you feel that is not the exact same issue 😁

**Comment by joelmandell** [comment]
Thank you @Zeegaan. The issue reported here seems to be of a different nature. The url that is picked (the generared localLink) is actually working and does not give 404. The issue is that it points to incorrect localized version.

If you have any hint where to start in the Umbraco codebase, I might debug and create a PR if so.

**Comment by Zeegaan** [comment]
@joelmandell I will have a quick look around then, I will report my findings 🕵️‍♂️

**Comment by Zeegaan** [comment]
@joelmandell I am having trouble reproducing this, I might need that blazor components of yours 🤔 
Can you send me the component 🙈 
![LocalizedLinksWorksWIthoutBlazor](https://user-images.githubusercontent.com/70372949/220281741-16ef845c-fdd4-44f7-9adf-6097905af3c8.gif)

**Comment by joelmandell** [comment]
Yes.
Here it is:

```
@using System.Globalization;
@using BlazorTest.Generated;
@using Umbraco.Cms.Core.Scoping;
@using Umbraco.Cms.Core.Web;
<h3>LanguageSwitcher</h3>

<button @onclick="SetSwedish" >Swedish</button>
<button @onclick="SetEnglish">English</button>
Content: @Content
<div>
	@((MarkupString)Content)
</div>
@code {
	[Inject]
	private IUmbracoContextFactory UmbracoContextFactory { get; set; }

	[Inject]
	private IScopeProvider ScopeProvider { get; set; }

	public string Content { get; set; }

	protected override void OnInitialized()
	{
		Content = "Initialized";	
	}

	private void SetSwedish()
	{
		Content = "Swedish";
		var sv = new CultureInfo("sv");
		CultureInfo.CurrentCulture = sv;
		CultureInfo.CurrentUICulture = sv;

		using (var scope = ScopeProvider.CreateScope(autoComplete: true))
		{
			using (var context = UmbracoContextFactory.EnsureUmbracoContext())
			{
				var settings = (Settings)context.UmbracoContext.Content.GetAtRoot().ElementAtOrDefault(1);
				Content = settings.Body.ToHtmlString();
			}
		}
	}


	private void SetEnglish()
	{
		Content = "English";
		var en = new CultureInfo("en");
		CultureInfo.CurrentCulture = en;
		CultureInfo.CurrentUICulture = en;

		using (var scope = ScopeProvider.CreateScope(autoComplete: true))
		{
			using (var context = UmbracoContextFactory.EnsureUmbracoContext())
			{
				var settings = (Settings)context.UmbracoContext.Content.GetAtRoot().ElementAtOrDefault(1);
				Content = settings.Body.ToHtmlString();
			}
		}
	}
}
```

**Comment by joelmandell** [comment]
@Zeegaan In your case (because I am "overriding" GetValue() that the generated models use accessing props) you might need to change settings.Body (or whatever your model prop are named) to use instead:
```Content = settings.ValueFor(x => x.Body, CultureInfo.CurrentCulture.TwoLetterISOLanguageName).ToHtmlString();```

**Comment by joelmandell** [comment]
@Zeegaan 👋
Here you have a full solution with a .bak-file of the db.
ConnectionString in appsettings is set to a dummy server.

Username for /umbraco is joel.mandell@sublime.se
Pw: !HowIsYourBlazorExp3rienceWellItDepends

[UmbracoWithBlazor.zip](https://github.com/umbraco/Umbraco-CMS/files/10813186/UmbracoWithBlazor.zip)

To add to my confusement. In the blazor component there is 4 buttons. If I click "English Umbraco Default" first and then click "English GetValue", my "fix" does not work. But If I first click "English GeValue" and then click "English Umbraco Default" it shows the correct href.

**Comment by Zeegaan** [comment]
@joelmandell Thanks for the details, I will start looking into this tomorrow 😁 
Just wondering, what .NET version are you running ? 🤔

**Comment by Zeegaan** [comment]
Alright so after looking into this, I was finally reproduce this issue, huge thanks @joelmandell for the details & the test project 💪 🎉 
The issue here is that the link picker for the rich text editor just stores the link as a document reference: 
![image](https://user-images.githubusercontent.com/70372949/221158225-45300c0d-b0e0-4a31-be1e-84382f7b4c77.png)
What then happens when we use `.ValueFor(x => x.VariantRichText, CultureInfo.CurrentCulture.TwoLetterISOLanguageName);`
Is that the link does not resolve to the correct culture, so that's where i would start debugging inside when looking for a fix 😁 

I will take the liberty to rename this issue, as its really a bug with the Rich text link picker, and doesn't have anything to do with blazor 😅 

# How to replicate this issue
- Enable ModelsBuilder by setting `Umbraco::CMS::ModelsBuilder::ModelsMode: SourceCodeAuto` in appsettings.json
- Setup your languages so that En-US is your default language, and create the danish language with culture `da`
- Create a document type called `Root` with allow root & allow vary by culture set to true
- Add a rich text property with allow vary by culture to said doc type
- Create content for both of the variants (leave rich text editor blank for now)
- Configure domains for both variants, `/` for english and `/da` for danish
- Use the link picker in the rich text editor and link to the same content (again for both variants)
- Save and publish
- Stop your site
- Add this NotificationHandler:
```
using System.Globalization;
using Umbraco.Cms.Core.Composing;
using Umbraco.Cms.Core.Events;
using Umbraco.Cms.Core.Notifications;
using Umbraco.Cms.Core.Web;
using Umbraco.Cms.Web.Common.PublishedModels;

namespace Umbraco.Cms.Web.UI;

public class MyNotificationHandler : INotificationHandler<ContentSavedNotification>
{
    private readonly IUmbracoContextFactory _umbracoContextFactory;

    public MyNotificationHandler(IUmbracoContextFactory umbracoContextFactory)
    {
        _umbracoContextFactory = umbracoContextFactory;
    }

    public void Handle(ContentSavedNotification notification)
    {
        using (var context = _umbracoContextFactory?.EnsureUmbracoContext())
        {
            var settings = (Root?)context?.UmbracoContext?.Content?.GetAtRoot().Last();
            var something = settings?.ValueFor(x => x.VariantRichText, "da");
        }
    }
}

public class Mycomposer : IComposer
{
    public void Compose(IUmbracoBuilder builder) => builder.AddNotificationHandler<ContentSavedNotification, MyNotificationHandler>();
}
```
- Set a breakpoint at `var something`
- Run the site, go save some content
- Hit the breakpoint and F10 once to populate the something variable
- See that the something variable contains a link to the "/" and not "/da"

**Comment by nul800sebastiaan** [comment]
Sorry about that extra prompt to say this is up for grabs, my bad! 🤦 Will look at your PR soon!

**Comment by Zeegaan** [comment]
Fixed in https://github.com/umbraco/Umbraco-CMS/pull/13889 🚀
