### ISSUE TITLE
Media preview doesn't show checkered background

### ISSUE THREAD

**Issue by bjarnef** [umbraco/Umbraco-CMS#13873]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

10.4.0

### Bug summary

When uploading white SVG files the preview isn't really useful, because it doesn't have a checkered background.

![image](https://user-images.githubusercontent.com/2919859/220583459-3b768b76-e7e7-4133-93fd-aadfcd437177.png)

It has previous been fixed, but maybe the newer `<umb-media-preview>` component added didn't take this into account.
https://github.com/umbraco/Umbraco-CMS/pull/10621 
https://github.com/umbraco/Umbraco-CMS/pull/10939

### Steps to reproduce

Upload a white SVG file and notice the preview shows white on white background.

**Comment by bjarnef** [comment]
Adding  `gravity-container` class to  class list with `umb-media-preview` seems to solve it, or we should copy style from the original `gravity-container` class.

![image](https://user-images.githubusercontent.com/2919859/220585295-c541d27a-4035-4f4a-8b39-bcd01d24fdb9.png)

@iOvergaard @nielslyngsoe

**Comment by iOvergaard** [comment]
Seems like a good solution to me. Do we just add that for all media types or maybe just for Vector Graphics?

Would you be up for building this yourself, @bjarnef? ☺️

**Comment by bjarnef** [comment]
I may also be an issue with a transparent gif or png with some white graphic like a logo.
Feel free to take a look or I can when I have some time, but currently a bit busy with a project.

**Comment by iOvergaard** [comment]
Yeah, I was wondering if it's safe to put on everything. I guess a JPG would cover the background at all times, but how can we make sure that it does not mess with any transparent media where the element matches the chequered color?

**Comment by bjarnef** [comment]
@iOvergaard there is always a change to color in an image could match the checkered background, just like it does with the white background, but since it is checkered there's a better change to see the image.

**Comment by bjarnef** [comment]
Just an example that it does use the checkered background in media picker.

![image](https://user-images.githubusercontent.com/2919859/222131500-18c66d81-fc77-402e-bbee-9ebfb51c81ce.png)

and in infinite editing, so I think this should be consistent.

![image](https://user-images.githubusercontent.com/2919859/222131591-b9184eb9-7150-430b-a8b1-e84f5b016874.png)

**Comment by tristanjthompson** [comment]
Thanks @glombek - reviewing/testing this now 👍

**Comment by bjarnef** [comment]
@nul800sebastiaan the latest bot message doesn't really make sense 😄
what should I help with? 😅 wasn't it completed last week?

**Comment by nul800sebastiaan** [comment]
😂 welll I was trying to REMOVE the `up-for-grabs` label, but it seems to have gotten confused there and re-added it. No action needed, all fixed and good! 👍
