### ISSUE TITLE
Bug when trying to use shortcut Ctrl + S in the content editor when saving an element in a block grid editor

### ISSUE THREAD

**Issue by andr317c** [umbraco/Umbraco-CMS#13883]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

11.2.0

### Bug summary

When you are trying to create content with a Block Grid Editor and you try to use the shortcut Ctrl + S in an element, it can sometimes save the Content and not the element itself. After the Content is saved you are not able to go away from the element.

### Specifics

I have only checked one Chrome

### Steps to reproduce

1. Create a Block Grid Editor with an element, and a document which has the Block Grid Editor.
2. Go to the content section and create content with the document.
3. Create Add the element in content 
4. Press Ctrl + S.

See gif for clarification

![UmbracoBugWhenUsingShorCutToSave](https://user-images.githubusercontent.com/73799582/220935025-2ec8a45e-73ab-4ee6-b7a1-e39dab22d5e0.gif)

**Comment by nikolajlauridsen** [comment]
I can indeed reproduce this.

Just for clarification, I was only able to reproduce this with a new content node, where I had not given it a name, etc.
