### ISSUE TITLE
Link Picker overlay is broken in Umbraco 10.4 when using .NET 7

### ISSUE THREAD

**Issue by abjerner** [umbraco/Umbraco-CMS#13880]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

10.4.0

### Bug summary

When changing the target framework of a project to .NET 7, the link picker overlay fails to determine the URL of the selected item, thus breaking the functionality.

@nzdev noted that [Umbraco 10's `Umbraco.Cms.Core.Models.Link` in combination with AutoMapper doesn't support .NET 7](https://discord.com/channels/869656431308189746/882984410432012360/1078285147130044498). Could be something similar that happens here 🤔 

### Specifics

In the link picker overlay, when selecting a content node, the URL is determined to be `#`:

![image](https://user-images.githubusercontent.com/3634580/220915368-79a2b8e4-2f0f-4b13-bd17-cf6f07fc73f9.png)

### Steps to reproduce

- Install Umbraco 10.4.0
- Add a content type with a Multi URL Picker property
- Add content of said content type
- Select content item (works as intended, URL is determined correctly)
- Upgrade target framework to .NET 7, rebuild etc.
- Select another content item (fails = 💥)

I've tested this in a few existing Umbraco 10.4 installs, as well as a couple of fresh installs that has no custom code or any packages installed.

I haven't tested in earlier versions of Umbraco 10.x, so not sure if those are affected as well.

### Expected result / actual result

The overlay should behave the same way as when running Umbraco with .NET 6.

**Comment by Zeegaan** [comment]
Hello there 👋 `.NET 7` is unfortunately not supported in V10, this is also due to other factors, such as the whole `InMemoryModelBuilder` not working either because of breaking changes in .NET.
This does however work great in V11 with `.NET 7` 🚀

**Comment by abjerner** [comment]
I wasn't aware that .NET 7 wasn't supported, but thanks for the info 👍
