### ISSUE TITLE
Umbraco 10.3.2 - MNTP startNode issue when using listview

### ISSUE THREAD

**Issue by RunnicFusion** [umbraco/Umbraco-CMS#13895]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

10.3.2

### Bug summary

Situation:

- Overview node has listview enabled
- Child node has MNTP
- When selecting nodes on child node you end up inside the listview; even when xpath/startnode is set

'Fix':
- Disable listview
- Everything is working as excpected

Looks like the startNode is also used when listview is enabled but the behaviour of Umbraco's listview prevents you from seeing the right nodes. Maybe this is related to 'select current node in node tree' which will end up in listview.

![image](https://user-images.githubusercontent.com/11329216/221793967-a7d825e5-b129-4235-8374-39b0e5ac404a.png)
_Description: 'Kerstwens 2023' it a child page with an MNTP. 'Meldingen' (inside the node picker pop-up) is the parent node._ 

Only happening when listview is enabled on parent of node containing MNTP

### Steps to reproduce

- Enable listview on parent node
- Create child node containing a MNTP (with startnode / xpath filter)

### Expected result / actual result

- When startNode is active MNTP doesn't need to start inside of parentNode listview but show nodes starting at startnode

**Comment by nikolajlauridsen** [comment]
This is fixed in #13657 😄 

Thanks for reporting 🐛

**Comment by RunnicFusion** [comment]
Could you please tell me what the current status is for this bugfix @nikolajlauridsen ?
