### ISSUE TITLE
Block list editor defaults to close content once clicked

### ISSUE THREAD

**Issue by bkclerke** [umbraco/Umbraco-CMS#13906]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

Umbraco V 11.2.0

### Bug summary

In Umbraco v10.2.1, When clicking **Add content** to the editor, the content opens once selected. 
In Umbraco v11.2.0, When clicking **Add content** to the editor, the content now adds an item selected but does not open it by default requiring the content editor to have more clicks to get into the same content.

### Specifics

In V10, when working with block list editor content to add a row, and then add a content item in another block list editor in the row, the user only had to click 4 times and was brought directly into the content after each click.

In V11, when performing the same actions, the user has to click 6 times and after every content item is added to the block list, the block list content item is closed so the editor has to click on the item they just clicked on to open it back up.

### Steps to reproduce

Here is a video reproducing the issue on V10 and V11 for comparison. The main issue noted here is that now in V11, we have a few more clicks to get to the same content we once were able to get to quicker, resulting in more time for entering content into the CMS.

https://user-images.githubusercontent.com/4968254/222494071-b961d5b0-4416-45f3-9c9c-3ab93180bc3d.mov

### Expected result / actual result

The expected result would be that the functionality remained the same as it was in V10, where the content that has been selected to add to the block list editor would open by default.

**Comment by nikolajlauridsen** [comment]
Heya, I had a look at this, but unfortunately, I cannot reproduce it, when I try it opens automatically (this is a 11.2 site), I've added a video, could you take a look and see if I'm misunderstanding something?

https://user-images.githubusercontent.com/16456704/222685002-18f48337-39ec-4d5a-8ded-91105e4c9b35.mp4

**Comment by bkclerke** [comment]
@nikolajlauridsen Thank you for the feedback. I just setup a v11.2 site and tried to re-create the issue and I cant from a clean install.

It appears this issue happened when the site was upgraded from v10.2.1 to v11.2.0 on two of our projects. I'll work with the team to try to figure out any more details and post back. Its happened twice now when upgrading our sites.

**Comment by elit0451** [comment]
Hi @bkclerke,

Unfortunately, we haven't heard from you in a while, so I will go ahead and close this one. Feel free to reopen it if you figure out those specific details that you mentioned 🙂

**Comment by kjac** [comment]
Hi everyone 👋 

We had the good fortune to be provided with a DB where we could reproduce this issue. We plan on releasing a fix for V11.4 (see PR).

**Comment by nikolajlauridsen** [comment]
Cherrypicked for v10 in b3a93ac86c3a80557f7c167fb440000a5f0ecb54
