### ISSUE TITLE
There is a possibility to create a media with corrupted image

### ISSUE THREAD

**Issue by PeterKvayt** [umbraco/Umbraco-CMS#13921]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

10.1.0

### Bug summary

There is a possibility to create a media with corrupted image.
![image](https://user-images.githubusercontent.com/45105665/223473533-61822417-0aa1-4086-a927-148e0d4d870b.png)

### Specifics

![image](https://user-images.githubusercontent.com/45105665/223471480-261e371e-67c2-4cbc-89bd-65c07d4005ea.png)

### Steps to reproduce

1. Create fake-image.txt file
2. Change it file extension from .txt to .png
3. Upload it in media
4. Check out logs

### Expected result / actual result

There is no possibility to save media if error occured while loading this media.

**Comment by kjac** [comment]
Hi @PeterKvayt,

We can't really do much about editors uploading corrupt image files. The editors can edit and replace the corrupt file after the upload, or delete the file if that's what they want, so they are not stuck with a corrupt file forever.
