### ISSUE TITLE
Creating a controller that inherits from UmbracoAuthorizedApiController can cause routing errors in the backoffice

### ISSUE THREAD

**Issue by mennomout** [umbraco/Umbraco-CMS#13929]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

9.0.1, 10.3.1 10.4.0

### Bug summary

In two of our projects we had an issue that when you click on one of the default folders in the "members" section the umbraco backoffice api could no longer find the right endpoint and display an error like this:

> Request error: The URL returned a 404 (not found):
/umbraco/backoffice/api/member/GetByKey

See this .gif below:
![backofficeapierror](https://user-images.githubusercontent.com/77411834/223724274-9ae30f81-5422-4bd9-a983-7d3799d41281.gif)

This was caused by a controller named: `MemberController `that inherits from the `UmbracoAuthorizedApiController`

After renaming the controller or making it inherit from the `UmbracoApiController` instead this issue would no longer occur.

### Specifics

Data below is specific for clicking on the "all members" folder/tab inside the "members" section. 

- Backoffice route: ~/umbraco#/member/member/list/all-members
- Backoffice API call: ~/umbraco/backoffice/api/member/GetByKey?area=UmbracoApiGetListNodeDisplay?listName=all-members
- Request payload: area: UmbracoApiGetListNodeDisplay?listName=all-members
- Request type: GET

Going to the "member" folder creates a different call that will also fail:
- Backoffice route: ~/umbraco#/member/member/list/Member
- Backoffice API call: ~/umbraco/backoffice/api/member/GetByKey?area=UmbracoApiGetListNodeDisplay?listName=Member
- Request payload: area: UmbracoApiGetListNodeDisplay?listName=Member
- Request type: GET

### Steps to reproduce

I've spend quiet a lot of time trying to reproduce this in a clean Umbraco installation but was unsuccessful in doing so. However in at least four different projects using three different Umbraco versions I was able to recreate the error by doing the following:

- Create a controller named "MemberController" that inherits from the UmbracoAuthorizedApiController.
- Navigate to the "members" section and click on one of the default folders like "all members"

### Expected result / actual result

- Expected: Creating a `MemberController` that inherits from `UmbracoAuthorizedApiController` should not interfere with the Umbraco backoffice "members" section.
- Actual: The backoffice "members" section stops functioning when creating a `MemberController` that inherits from `UmbracoAuthorizedApiController`

**Comment by kjac** [comment]
Hi @mennomout,

`UmbracoAuthorizedApiController` (and `UmbracoAuthorizedJsonController`) implementations are for backoffice use only; as such they tie into the same routing scheme as the core Umbraco controllers, and thus you can accidentally hijack the route of core controllers by naming your `UmbracoAuthorizedApiController` the same as the core controllers. Unfortunately there is not much we can do about that. It's up to you as an implementer to respect the naming of the core controllers.

Controllers implementing `UmbracoApiController` are meant for frontend use - e.g. public facing APIs. They follow their own route, so you *can* create a `MemberController` when implementing `UmbracoApiController`.

I'm not sure what you're trying to achieve, but for good measure ... you should *never* create public facing APIs using `UmbracoAuthorizedApiController` or `UmbracoAuthorizedJsonController`. Only ever use these base classes for usage within the Umbraco backoffice - i.e. for custom backoffice extensions.

**Comment by mennomout** [comment]
@kjac Thank you for the reply. I'll share this information internally. One thing that is not making sense though is that it doesn't cause conflicts consistently. I've not been able to reproduce the route hijack in a clean Umbraco v10.4.0 installation but our other applications do accidentally hijack the route. It's not a big deal so for now we will respect the core controller naming which fixes the issue.
