### ISSUE TITLE
UmbracoAuthorizedApiController seems to return unformatted JSON

### ISSUE THREAD

**Issue by CarlSargunar** [umbraco/Umbraco-CMS#13920]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

10.4.0

### Bug summary

Not sure if this is an actual bug or something to do with how dev tools displays the response, but I'm getting some weird characters before the response of my API controller. 

### Steps to reproduce

Steps to replicate (from a clean Umbraco 10 install. Also tested on 11, and had the same issue

Create a Controller

```
using Umbraco.Cms.Web.Common.Controllers;

public class ProductsController : UmbracoApiController
{
    public IEnumerable<string> GetAllProducts()
    {
        // URL: /Umbraco/Api/Products/GetAllProducts
        return new[] { "Table", "Chair", "Desk", "Computer" };
    }
}
```

Run the site, and log into the back office (to get past the authentication for the api controller) and then browse to the url : "/Umbraco/backoffice/Api/ProductsSecure/GetAllProducts"

The Raw response from the API controller is as follows : 

```
)]}',
["Table","Chair","Desk","Computer"]
```

The problem is the first 5 characters `)]}',`

### Expected result / actual result

I would expect the response to be 

`["Table","Chair","Desk","Computer"]`

**Comment by CarlSargunar** [comment]
Copy paste error earlier. In steps to replicate, the controller should be inheriting from UmbracoAuthorizedApiController

so :

```
public class ProductsSecureController : UmbracoAuthorizedApiController
{
    public IEnumerable<string> GetAllProducts()
    {
        // URL: /Umbraco/backoffice/Api/ProductsSecure/GetAllProducts
        return new[] { "Table", "Chair", "Desk", "Computer" };
    }
}
```

**Comment by nathanwoulfe** [comment]
Hey @CarlSargunar, this is expected behaviour - the additional characters are prefixed as JSON vulnerability protection and are automatically removed by AngularJs when processing the response. If you're inheriting from `UmbracoAuthorizedApiController` it's a fair assumption you're in the backoffice, so using AngularJs' `$http` service or Umbraco's `umbRequestHelper` will handle the extra characters.

**Comment by CarlSargunar** [comment]
Ah ok - good to know, thanks @nathanwoulfe 

Might be worth a PR to the docs, I'll jump on that

**Comment by CarlSargunar** [comment]
PR Submitted to the docs, but will close this issue

**Comment by nathanwoulfe** [comment]
All good @CarlSargunar, it's something that pops up from time to time because it looks wrong. Will be gone in NuBackoffice 😄
