### ISSUE TITLE
ArgumentOutOfRangeException when composing a schedule with a period timespan over 24,8 days.

### ISSUE THREAD

**Issue by Fliipzy** [umbraco/Umbraco-CMS#13931]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

11.2.0

### Bug summary

When you try to add a schedule (**RecurringHostedServiceBase**) to the service collection with the _period_ or _delay_ arguments set to over 24,8 days an ArgumentOutOfRangeException is thrown on startup:

> ArgumentOutOfRangeException: Number must be either non-negative and less than or equal to Int32.MaxValue or -1. (Parameter 'period')
> System.Threading.Timer..ctor(TimerCallback callback, object state, int dueTime, int period, bool flowExecutionContext)
> System.Threading.Timer..ctor(TimerCallback callback, object state, int dueTime, int period)
> Umbraco.Cms.Infrastructure.HostedServices.RecurringHostedServiceBase.StartAsync(CancellationToken cancellationToken)
> Microsoft.Extensions.Hosting.Internal.Host.StartAsync(CancellationToken cancellationToken)
> Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
> Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
> Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.Run(IHost host)

![image](https://user-images.githubusercontent.com/10576077/223750410-c88c662e-761d-450d-b66f-49218736ebe4.png)

As the stacktrace points out the exception occurs when a Timer is being constructed with the integer arguments. 
I suspect these integer values are the results from cast operations on the datetime's milliseconds as the exception is only thrown when it's over 24,8 days:

The Int32 max value is 2,147,483,647. That value in milliseconds is approximately 24,8 days. 

### Steps to reproduce

1. Start a new umbraco project.
2. Create a scheduler / hosted service class.
3. When calling the RecurringHostedServiceBase base constructor , pass in a delay or period with a TimeSpan value greater than 24,8 days.
4. Compose the new scheduler class.
5. Run the application

**Comment by AaronSadlerUK** [comment]
@nul800sebastiaan PR submitted #13935

**Comment by tristanjthompson** [comment]
Thanks @AaronSadlerUK - just picking this up to test now 👍

**Comment by nul800sebastiaan** [comment]
Fixed in https://github.com/umbraco/Umbraco-CMS/pull/13935

**Comment by nul800sebastiaan** [comment]
Sorry, ignore the bot 🙈 , issue is fixed as per https://github.com/umbraco/Umbraco-CMS/pull/13935
