### ISSUE TITLE
UmbracoMemberAuthorize attribute on API controller returns 404 when unauthorized

### ISSUE THREAD

**Issue by aguyfromdenmark** [umbraco/Umbraco-CMS#13946]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

10.3.2

### Bug summary

When using the [UmbracoMemberAuthorize attribute](https://docs.umbraco.com/umbraco-cms/reference/routing/umbraco-api-controllers/authorization#using-memberauthorizeattribute) on an `UmbracoApiController`, the status code of an unauthorized request is 404. This should be 401. 

### Specifics

Talked to support, who talked to the CMS team, who confirmed that this is not the intended behaviour. 

### Steps to reproduce

- Create an controller inheriting from `UmbracoApiController`.
- Use the `UmbracoMemberAuthorize `on the controller or on a method.
- Call the controller without being logged in as a member. 

### Expected result / actual result

An unauthorized call should return a response with a 401 statuscode. It returns a 404 status code.

---
_This item has been added to our backlog [AB#27645](https://dev.azure.com/umbraco/243e7927-03b2-44e2-908f-d4ac7ea5daaa/_workitems/edit/27645)_

**Comment by elit0451** [comment]
Thanks for reporting this @aguyfromdenmark 💪 

We will have a look at it 🙂

**Comment by elit0451** [comment]
Fixed in: #14036
