### ISSUE TITLE
$site token replacement no longer working in custom MNTP (for new documents)

### ISSUE THREAD

**Issue by paulomahony** [umbraco/Umbraco-CMS#13958]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

11.2.0

### Bug summary

`$site` token does not work in MNTP XPath queries for new documents, although it does work for existing documents. In Umbraco 10, it worked equally well for new and existing documents

### Specifics

We recently upgraded our application from Umbraco 10 to 11. We have a number of custom MNTPs in our application. All of these select a folder in the current site's dataRepository as a starting point using the `$site` token

Here is an example of one Xpath query we use, a combination of the `$site` token and a number of document aliases

`$site/dataRepository/taxonomyRoot/expertiseTaxonomy`

This worked fine in Umbraco 10, both for existing documents and new documents. However, since upgrading to Umbraco 11, the starting folder is set correctly in the MNTP for existing documents, but not for new documents. For new documents, the starting folder is set as the root folder which indicates, I think, that the Xpath query has failed to locate the start folder

Perhaps this is something to do with the transient nature of a new document, which of course has no id until it is saved. But as I mentioned before, it did work in Umbraco 10

Not sure if this new behaviour is intended, or a bug. 

### Steps to reproduce

- In the content tree, create a folder one or more levels deep
- Create a custom MNTP data type
- Use an Xpath query to select the starting folder for the new MNTP. The Xpath query should start with `$site` and be able to locate the folder created in step 1, 
- Create a new Document type and have one of its fields use the new custom MNTP
- In the Content tree, create an instance of the new Document Type
- Before saving the new document, click on the field with the custom MNTP to select one (or more) items

### Expected result / actual result

The popup for the MNTP should have as its start folder the folder created in step 1 above, as was the case in Umbraco 10

What actually happens is that the site root is the start folder

**Comment by elit0451** [comment]
Hi @paulomahony 👋 

Thanks for reaching out. I've managed to reproduce your issue on both **v10** and **v11** (as you can see in the video below). I will mark it as up for grabs as we would like some help with it 🙂 

The workaround is to just select the particular folder instead of using XPath.

https://user-images.githubusercontent.com/21998037/225542788-05dc1ce3-026e-4f8c-8d85-70e6941ae713.mov

**Comment by paulomahony** [comment]
@elit0451 thanks for your response! Was your your video filmed using version 11.x or version 10.x? 

To reiterate, the problem seems to have been introduced in version 11. I can't replicate the problem in version 10.1.0 (everything works fine) but can in version 11.2.0 (behaviour as in your video)

Thanks again
Paul

**Comment by elit0451** [comment]
It was filmed using the latest version of Umbraco 10 (10.4.0), so I just wanted to mention that the issue is also present in v10 🙂

**Comment by karlmacklin** [comment]
Hi, I'd just like to chime in and say that while a workaround was presented further up, it's not really a good workaround for us as we need to limit the choice of nodes to a certain parent node - BUT, we have multiple sites/domains in the same backoffice. Thus we need to write a working XPath query, and currently we can't write a single one working with the variables the MNTP hints at.

**Comment by karlmacklin** [comment]
I've been looking through the source code for a bit.

I believe the quirk is right here:
https://github.com/umbraco/Umbraco-CMS/blob/contrib/src/Umbraco.Core/Xml/UmbracoXPathPathSyntaxParser.cs#L88

`if (nodeContextId.HasValue)`

This is 0 when the node is new and unsaved, so naturally the following variable can't assign a proper id value from a parent or similar.

However, I don't understand how this has been working at all previously. I'm looking back at version 9 of Umbraco and it still has the same check.

Has this ever worked in an unsaved state of a node/document? Or has it always required that you first save the node?
That's tricky if your MNTP is a required field.

I've also tried to see if there's something, anything, that could give a hint as to what context/position/possible future parent node you are trying to create content from. But I don't know enough about Umbraco core files to come up with an idea there unfortunately.

**Comment by karlmacklin** [comment]
Looking at this version of the file from 2015:
https://github.com/umbraco/Umbraco-CMS/blob/ad8926668e1b470795246f27dede911cbe6d82f5/src/Umbraco.Core/Xml/UmbracoXPathPathSyntaxParser.cs

We can see the comment regarding this:
```
/// The current node id context of executing the query - null if there is no current node, in which case
/// some of the parameters like $current, $parent, $site will be disabled
```

So I guess this is how it has always worked?

**Comment by paulomahony** [comment]
Hi @karlmacklin thanks for piping in on this :) I had looked at the source code too and saw what you saw, i.e. that `nodeContextId` seemed to not have a value while the item being created was transient. Also like you I don't know the Umbraco Core codebase well enough to start making changes 

However, I know for sure that this worked in 10.1.0, and your post gave me an idea. `$site` should always evaluate the same in a content tree under a site node (to that site node). However `$parent` would evaluate differently depending on how deep in the content tree you are starting from.

So, I created a new MNTP data type with an xpath query of `$parent` to calculate the starting node, and added a field called "Random Page". I created a tree of content with 5 levels, each containing a single item. For each one of these, when selecting the random page field, no matter at what level of depth, the starting point would be its parent, and the only selection available would be the page itself

![image](https://user-images.githubusercontent.com/4222757/230021983-eae27126-5c7e-4853-b2d5-d40315c6c1c4.png)

However the behaviour is slightly different when creating a new item, while the new item is still transient. In this case `$parent` evaluates as the parent of the page _creating_ the new item. For example, following on from the previous image I now try to create a level 6 item. This is what it looks like selecting Random Page whilst Level 6 is still transient

![image](https://user-images.githubusercontent.com/4222757/230023111-dd8cbf66-fd06-4e21-b9bb-36bb591095f6.png)

When I save Level 6 and go to select Random page again this is what we see. Note that it has reverted to the standard behaviour

![image](https://user-images.githubusercontent.com/4222757/230023541-1b46146e-1c54-4ea6-b25e-3cebe5936b81.png)

What this tells us is that in Umbraco 10.1.0, whilst an item is transient, `nodeContextId` as passed to `UmbracoXPathPathSyntaxParser.ParseXPathQuery()` contains the id of the node from where the new item is being created. Somewhere after that this behaviour has changed so that `nodeContextId` is now null whilst an item is still transient. It seems that this change was made by v10.4.0 according to @elit0451 's video above

Thoughts @elit0451 ?

Cheers 
Paul

**Comment by karlmacklin** [comment]
@paulomahony 
Good explanation!

Perhaps you've googled your way to this blog post from 2016 explaining a strategy on how to write the Xpath queries to handle the ambigious behavior you just explained:
https://www.dot-see.com/blog/getting-the-right-starting-node-for-multinode-treepicker-with-xpath/

I've tried that approach naturally with no luck, but given the pre v10.4.0 that approach should work and makes sense.
So I guess the question is, what regressed in v10.4.0 and is it possible to revert that without breaking anything else?

Is there a way in github to diff two branches easily? That could give a smaller change subset to look at searching for clues.

**Comment by paulomahony** [comment]
@karlmacklin I had not seen that article! Interesting, wish I'd seen that earlier :) It's from 2016, pre v10, so obviously _something_ was being passed in `nodeContextId`. He would see the same problem we've been seeing if he were using v10.4.0 or later

Looking at the source code for v11.2.0, `UmbracoXPathPathSyntaxParser.ParseXPathQuery()` is called from `EntityController.GetByQuery()` and all looks good there. It's an API entry point so this suggests that the decision not to pass the parent id as `nodeContextId` for transient items is take at a higher level, i.e. Back office client-side (angular?)  code.

This side-effect of this decision is, as we've seen, a breaking change, so I'm sure it would have been documented as such had it been expected. 

So, I'm hoping it was unintentional and can be reverted in a future release :)

Until then we can not upgrade our multi-site instances beyond v10.1.0. As you say, the workaround suggested further up by @elit0451 is not satisfactory for multi-site instances

**Comment by karlmacklin** [comment]
`$routeParams` contains a property `create` which seems `true` during new node creation, in that case I guess you could instead send `$routeParams.id` into the function, and if it's not true, use the new approach with `editorState.current.id`?

**Comment by paulomahony** [comment]
Another possibilty would be to pass both the parent id (as int, always non-zero) _and_ the current id (either nullable int? or zeroable int). These would be calculated from `editorstate.current.id` and `editorstate.current.parentId` in the js example above

If the current Id is null or zero, we know we're creating. This would allow us to expand the variables with thte following rules:

$site: always expands, calculated from parentid parameter
$parent: always expands, calculated from parentId parameter
$current: only expands if currentId parameter is not null or zero

Granted this would involve changing both .net and javascript code, but it would ensure accuracy of $parent expansion and still keep $site available

The other place in Umbraco.Core where this is called is in `NotFoundHandlerHelper`. Not exactly sure how it would pass both parent and current id

**Comment by karlmacklin** [comment]
I like your idea better. The only thing I'm unsure of is the scenario(s) that breaking commit was handling. Infinite editing scoping. Perhaps it's covered already?

**Comment by paulomahony** [comment]
I don't know enough about infinite editing to say for sure, but I _think_ it would be  covered by my suggestion. I'm more concerned about the other use for `UmbracoXPathPathSyntaxParser.ParseXPathQuery()` in the `NotFoundHandlerHelper`. This seems to pass the current domain content id, if available, as the `nodeContextId` parameter. Not sure what we would pass as the `parentId` parameter there

**Comment by karlmacklin** [comment]
I have made a fork and a fix with what I deem a reasonable solution (still not pushed up).

However I fail at properly testing the functionality due to lacking understanding of how XPath works in general.

How can I properly test the functionality of the `$site` variable?
I have a node in the root of the tree which has a documenttype of `parentType` and I want to set the starting point of the nodepicker to this node. My XPath is defined as `$site/parentType`, and I've also tried `$site/parentType[1]` but no luck. Should it work with typing out the slug?

**Comment by karlmacklin** [comment]
I have done more testing now with good results and pushed a pull request, hopefully we can see this resolved.

**Comment by paulomahony** [comment]
@karlmacklin had a look at your PR and all looks good on the C# end, and also on the js controller. Can't really comment on the other js file as I'm not familiar.

re. your XPath query example, `$site/parentType` should locate the document of type `parentType` immediately beneath the current site node, _if_ there is one and only one document of that type at that level. If there is more than one document of that type at that level it will return a collection and I'm sure that will not play well with the content editor

Thanks for jumping in on this and, as you say, hopefully this will accepted and rolled in soon :)

**Comment by elit0451** [comment]
Apologies for coming back to this discussion just now, it's been a crazy few weeks. Great investigation work @paulomahony and @karlmacklin. Awesome thing that you have made a PR already @karlmacklin! I will mark this issue as regression and with your fix, we need to confirm that it would solve both this and the original issue (https://github.com/umbraco/Umbraco-CMS/issues/12121)
