### ISSUE TITLE
Preview mode stops working when backoffice auth cookie gets chunked

### ISSUE THREAD

**Issue by keithswright** [umbraco/Umbraco-CMS#13950]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

10.0.0

### Bug summary

When a backoffice users auth cookie is large enough to need to be chunked, preview mode stops working.

### Specifics

When an backoffice user wants to preview a page, a website request (not backoffice) is made to view the page. 
The website page request needs to check that there is a preview cookie and there is a backoffice user logged in, otherwise it wont show the preview version and will only show the published version.

This check is performed using the PreviewAuthenticationMiddleware class.

The backoffice user auth cookie is retrieved using: 

`request.Cookies.TryGetValue(cookieOptions.Cookie.Name, out var cookie)`

The problem is that the above method retrieves a string value, but the auth cookie can be "chunked" if the user has a large list of claims. When the cookie is chunked, the above method only gets the value of the main cookie and doesnt try to recombine the chunks and fails to authenticate the backoffice user.

The natural solution would be to change the above line of code to something like:

` var cookie = cookieOptions.CookieManager.GetRequestCookie(context, cookieOptions.Cookie.Name);`

The issue here is that the BackOfficeCookieManager overrides GetRequestCookie and will only return the cookie if the request is a backoffice request. But in preview mode, we need to get the cookie even though its a website request.

To fix this for myself, I wrote my own implementation of PreviewAuthenticationMiddleware that is able to deal with chunked cookies. I replaced the line above with this and it seemed to work for me, but it feels very flaky: 

```
var cookieManager = new ChunkingCookieManager(); 
var cookie = cookieManager.GetRequestCookie(context, cookieOptions.Cookie.Name);
```

I am not an expert on the umbraco source, so I am not sure of what side effects this might have, but I think the best solution would be to modify the BackOfficeCookieManager to allow the cookie to be retrieved if preview mode is enabled. Perhaps in the ShouldAuthenticateRequest method we could add:

```
        if (_umbracoContextAccessor.TryGetUmbracoContext(out IUmbracoContext umbracoContext))
        {
            if (umbracoContext.InPreviewMode)
            {
                return true;
            }
        }
```

and then to change the PreviewAuthenticationMiddleware to use: 

` var cookie = cookieOptions.CookieManager.GetRequestCookie(context, cookieOptions.Cookie.Name);`

### Steps to reproduce

Add a user to a large number of groups/apps to ensure they have a very large number of claims (enough to ensure the auth cookie is chunked)

Try to preview some unpublished changes with the user above

### Expected result / actual result

Expected: the user can see the unpublished changes in preview mode
Actual: the user can only see the published content

**Comment by Zeegaan** [comment]
Hey @keithswright Have you tested this on the latest release, I know we did some work similar to this in one of the earlier v10 releases (10.2 or 10.3 iirc) 
I am testing against the source code here, but Preview works just fine even with chunked cookies 🤔

**Comment by Zeegaan** [comment]
@keithswright Could you test this against the newly released RC ? 😁  https://www.nuget.org/packages/Umbraco.Cms/10.5.0-rc

**Comment by keithswright** [comment]
Hi @Zeegaan 

Thanks for looking at this. We will be upgrading our site to V11 in the next month or so. When we do, Ill remove the above hack and report back here whether it is working for me or not.
