### ISSUE TITLE
Approving member programmatically does not reflect in backoffice

### ISSUE THREAD

**Issue by aguyfromdenmark** [umbraco/Umbraco-CMS#13966]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

10.3.2 - 10.4.0

### Bug summary

If you programmatically approve a member, like this: 
![image](https://user-images.githubusercontent.com/6904597/224968585-a60e73b2-1cdb-4811-8f9d-51ea991a68c6.png)

The member will be approved, but this is no reflected in backoffice. 
![image](https://user-images.githubusercontent.com/6904597/224968703-5ca833de-b7da-46ed-a3e2-5120a9bd3c38.png)
![image](https://user-images.githubusercontent.com/6904597/224968899-25d50cbd-8f57-4188-a530-5390c655d2b2.png)
Even though the `GetByKey `request returns that the user is approved. 

If you toggle the "Is Approved" toggle to true, and saves, then reloads the page, the state will be reflected in the toggle element. 
![image](https://user-images.githubusercontent.com/6904597/224969182-29b3f1d0-b0ac-491c-943d-ca20ca4ec499.png)

### Steps to reproduce

- Create a member programmatically. 
- Approve that member programmatically. 
- Check the "Is Approved" prop in backoffice, is does not reflect the true value. 

### Expected result / actual result

The expected result is that the "Is Approved" property visually reflects the actual value.

**Comment by elit0451** [comment]
Hi @aguyfromdenmark 👋 

I've tried to reproduce your issue on Umbraco 10.4 with the following code:

```c#
var member = _memberService.CreateMember("test@test.com", "test@test.com", "Test", "member");

//Set them to be approved
member.IsApproved = true;

_memberService.Save(member);
```

And as you can see in the image below, the Approved toggle was set correctly and when I assigned it to `false`, it was turned off, so perhaps I am missing something. Can you point me in the right direction? 🙂 

![Screenshot](https://user-images.githubusercontent.com/21998037/225280133-c48d4695-6986-4ac7-a56b-259ba76df507.png)

**Comment by Zeegaan** [comment]
Also tried this via a NotificationHandler to update an already existing user with code: 
```
using Umbraco.Cms.Core.Composing;
using Umbraco.Cms.Core.Events;
using Umbraco.Cms.Core.Models;
using Umbraco.Cms.Core.Notifications;
using Umbraco.Cms.Core.Services;

namespace Sadge;

public class MyComposer : IComposer
{
    public void Compose(IUmbracoBuilder builder)
    {
        builder.AddNotificationHandler<ContentSavedNotification, MyNotiHandler>();
    }

}

public class MyNotiHandler : INotificationHandler<ContentSavedNotification>
{
    private readonly IMemberService _memberService;

    public MyNotiHandler(IMemberService memberService)
    {
        _memberService = memberService;
    }

    public void Handle(ContentSavedNotification notification)
    {
        IMember? member = _memberService.GetByKey(new Guid("c4feec5c-6a88-4400-8f13-b3eab4bac2ab"));

        member!.IsApproved = true;
        _memberService.Save(member);
    }
}
```
![CanApproveMemberViaCode](https://user-images.githubusercontent.com/70372949/226301785-96c1dfa3-79e9-4b81-ae26-9192f3f5bbb8.gif)

I will close this issue for now, but feel free to reproduce if you have reproduction steps 🙏
