### ISSUE TITLE
AuditType.Sort not tracked on sorted nodes

### ISSUE THREAD

**Issue by jesperweber** [umbraco/Umbraco-CMS#13977]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

11.2.0

### Bug summary

When looking at the audit history of a node, sorting is not reflected in the audit list.

![image](https://user-images.githubusercontent.com/2575817/225618449-95dc5a38-97a8-4cd7-8baa-184fdac33605.png)

Sorting can have and impact on what data are being showed in the website and it would be nice to see who and when sorting was made on a node, just like moving, saving and publish.

Looking at the Umbraco source code in the `ContentService` class a sort audit is being tracked, but it's tracked on the node id of 0 and not on each node id actually being sorted.

![image](https://user-images.githubusercontent.com/2575817/225620348-b7225fa0-7198-466b-a713-e2d4ce1819d8.png)

### Steps to reproduce

1. Create a node with two child nodes
2. Right click the parent node and click sort
3. See that node sort audit is visible on the child nodes audit history

### Expected result / actual result

I would expect sort audits to be visible to the editors in the history of the node.

**Comment by Zeegaan** [comment]
Alright after a deep rabbit-hole investigation, this does seem like a bug! 🐰 🕵️ 

Seems like it was changed to reflect on the parent in this commit: https://github.com/umbraco/Umbraco-CMS/commit/2e135d2006212df799765552bc0e916b9711cee9
But then the `Sort` method was refactored into a private method so it could be re-used. So I think the `items.First().ParentId` could probably just be used again! (Hopefully, will probably need some testing).
I will mark this as up for grabs 🙌

**Comment by jesperweber** [comment]
Hi @Zeegaan,

Thanks for your reply and for taking the deep dive into the rabbit-hole :-)

I know from a UI perspective you are right clicking the parent node and clicking Sort. But from a data perspective it's node the parent node that's being sorted, it's the child nodes (and maybe only some of the child nodes).

I would expect the sort audit to be registered on each child node that's being sorted and not on the parent node.

**Comment by jesperweber** [comment]
I've added a PR, but this is properly also an issue in V9 and V10?
