### ISSUE TITLE
Preview fails every second time when previewing content that has vary by culture enabled

### ISSUE THREAD

**Issue by mikaellindemann** [umbraco/Umbraco-CMS#13970]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

10.4.0

### Bug summary

When a document has "Allow vary by culture" enabled, the preview seems to only render every second time Save and preview is pressed, as long as the preview tab is open.

### Specifics

I have been able to reproduce this on a fresh Umbraco 10.4.0 installation (see repro steps) on Windows 11 (also happens on Azure App Services running on Windows).
The bug seems to be present both in Chrome and Firefox.

In the browser developer tools, there seems to be a race between the following URLs:

* https://localhost:44375/umbraco/preview/?init=true
* https://localhost:44375/umbraco/preview/?id=1057

In some cases, when the init=true one completes first, it seems to cancel the content-id specific one.

A workaround for now:
If preview is started once by pressing Save and preview, you can instruct the editors to use the Save button afterwards.

### Steps to reproduce

Commands run to spin up solution:

```cmd
dotnet new -i Umbraco.Templates::10.4.0
dotnet new umbraco
dotnet new sln
dotnet sln add .
```

Solution opened in IDE.

Can be reproduced in both default run configurations: `Umbraco 10: Umbraco.Web.UI` (using Kestrel) and `Umbraco 10: IIS Express`.

Install Umbraco by setting up user account.
I used the default settings for the rest of the installation (SQLite db, default telemetry).

Create language (e.g. Danish).
Create a new empty document type with template, allow as root document, and allow vary by culture (mine is called Root as can be seen in the template code below).
Change the created template to the following from within Umbraco (I have only added the bottom line):

```
@using Umbraco.Cms.Web.Common.PublishedModels;
@inherits Umbraco.Cms.Web.Common.Views.UmbracoViewPage<ContentModels.Root>
@using ContentModels = Umbraco.Cms.Web.Common.PublishedModels;
@{
	Layout = null;
}

@Model.Name
```

Create a new document in the root of the content tree.
Give it a name and save and publish the default language.
Create a new variant using the previously set up language.

Press Save and preview.
The preview should render.
Keep the tab open, but open the Umbraco tab and press Save and preview again.
The preview doesn't render.
Go back into Umbraco and press Save and preview again.
Now the preview renders again.

This seems to happen only for documents that has Vary by culture enabled.

### Expected result / actual result

Preview should load correctly every time Save and preview is used.

**Comment by elit0451** [comment]
Hey @mikaellindemann 👋 

Thanks for reporting this and for the detailed steps you provided 💪  I've managed to reproduce the problem, however, it is important to note that the issue happens for any node - it doesn't make a difference that the Vary by culture is enabled for its document type. 

The workaround is to simply close the additional window that the Save and Preview button opened before clicking to Preview the page again. Clicking it twice when the window is opened will result in the described issue.

I will mark this as up for grabs as we would love some help with this one 🙂

**Comment by dKumarmj** [comment]
[PR ](https://github.com/umbraco/Umbraco-CMS/pull/14094)for the same here https://github.com/umbraco/Umbraco-CMS/issues/14052

**Comment by nul800sebastiaan** [comment]
Fixed in https://github.com/umbraco/Umbraco-CMS/issues/14052
