### ISSUE TITLE
Umbraco 10 long load times in backoffice

### ISSUE THREAD

**Issue by shearer3000** [umbraco/Umbraco-CMS#13989]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

10.4, 10.3.2, 10.2

### Bug summary

We have a range of umrbaco 10.x websites that all exbibit this symptom.

Sporadically/randomly, backoffice requests seem to take approx. 19 seconds longer than expected. It isn’t limited to a single request or request type (doc, image, js, css etc) but can differ every time.

For example, a website on Umbraco 10.4 with a request taking 19.01 seconds:
![image](https://user-images.githubusercontent.com/2433680/226502152-3ea46f79-f17f-41cf-906b-fd2090e90203.png)

Has this issue being reported already?

### Steps to reproduce

logging into backoffice with browser dev tools open and observe request timings

### Expected result / actual result

expected: requests don't take approx 19 seconds longer that anticipated

**Comment by Zeegaan** [comment]
Thanks for reporting! THere is not much to go on here, unfortunately, is this just for the `GetDashboard` call every time, or is it different calls? 🤔

**Comment by kjac** [comment]
Hi @shearer3000,

We haven't heard from you in a while, so I'm closing this issue now. Feel free to reopen it with additional details to reproduce if the problem still persists.
