### ISSUE TITLE
Umbraco.MultiUrlPicker - Cannot deselect node that has been selected

### ISSUE THREAD

**Issue by Abdjulaziz** [umbraco/Umbraco-CMS#14006]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

Umbraco 11.2.1

### Bug summary

Not being able to deselect on the Umbraco.MultiUrlPicker if a content node is picked you have to cancel and then add the link again before being able to do what you want.

## Cannot deselect node that has been selected

![image](https://user-images.githubusercontent.com/60339265/227530571-33eb3f91-ff09-484e-b839-d870b55d8163.png)

## In the video below you can see that the only thing I can do is pick the node or pick another node I cannot deselect.

https://user-images.githubusercontent.com/60339265/227531728-641fcf7d-219b-4bef-96d6-1cc7475545f2.mp4

### Steps to reproduce

Make a project(tested on 10.4.1 & 11.2.1)

Make two Document types(in my cases I made two "Home" & "Page")

Document type "Home" is empty and has Allow as root and the Document type "page" as a child node.
Document type "Page" has two property editors Textstring and the Multi URL Picker.

created "Home" content node with preferred name(in my case it is called "Homepage")
created "Page" content node with preferred name(in my case it is called "Testing page")

On the "Testing page" content node you can test out the Multi Url Picker.
try to add a content node Homepage. 

↑
Here you can see that you cannot deselect the node you picked you can only pick other nodes - so if you accidentally clicked a node instead of linking to external links you then need to close this modal and then click add again before you can do what you wanted to do.

Also If you want to edit you can only edit it to another node - and not another external link.

### Expected result / actual result

Be able to deselect and put in an external link.

**Comment by nikolajlauridsen** [comment]
That does indeed seem to be a problem, unfortunately. 

We'd love some help looking at this, so I'll mark it as up for grabs. 

Thanks for reporting 🐛
