### ISSUE TITLE
Umbraco.UploadField - When configurations are added ass accepted file extenstions it breaks the manual upload of files

### ISSUE THREAD

**Issue by Abdjulaziz** [umbraco/Umbraco-CMS#14019]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

Version 10.2.1 & 11.2.2

### When you edit the configuration for the file upload (adding extensions) - Manually uploading breaks and gives an error.

![image](https://user-images.githubusercontent.com/60339265/228242481-5ee4265d-9ad9-4c81-9c9c-40098810a7f3.png)

### Having a clean slate will not break anything ↓

![image](https://user-images.githubusercontent.com/60339265/228246435-81c451fb-55ad-4ad6-a41d-851ac40035ad.png)

### Specifics

When having added the Configuration - Accepted file extensions shown below  something in the code breaks and you get an error: 
```
Authorization error: Unauthorized access to URL:
/umbraco/backoffice/umbracoapi/media/PostSave
Contact your administrator for information.
```

![image](https://user-images.githubusercontent.com/60339265/228242481-5ee4265d-9ad9-4c81-9c9c-40098810a7f3.png)

### Steps to reproduce

Please look at the video on how to reproduce

https://user-images.githubusercontent.com/60339265/228249677-11c12508-7f46-4931-8912-a6cdcedce904.mp4

### Expected result / actual result

When adding Configuration they should work

**Comment by nul800sebastiaan** [comment]
@Abdjulaziz  What happens if you remove the leading `.` of the file extensions? The file is not named `file..pdf` but `file.pdf` so the extension is not `.pdf` but just `pdf`.

**Comment by Abdjulaziz** [comment]
Did a quick test on my project and it worked with `pdf ` so that should be it. Thank you @nul800sebastiaan

**Comment by Abdjulaziz** [comment]
Quick questions. Tho this I solved is there a way we can terminate the fact users can add a `.` and it only should be valid types?
