### ISSUE TITLE
Using an IContentService in an IComponent won't allow Umbraco to boot if database is empty

### ISSUE THREAD

**Issue by LennardF1989** [umbraco/Umbraco-CMS#14022]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

11.2.2

### Bug summary

Learned this the hard way, but when you have an IComponent with an IContentService injected which you use in the Initialize method, this will crash Umbraco if no database is present yet. The reason for this is because the IContentService will try to contact the database and find out the ConnectionString is either not (yet) working or missing.

### Steps to reproduce

1. Create empty Umbraco project
2. Add this code:
```cs
    public class StartupComposer : IComposer
    {
        public void Compose(IUmbracoBuilder builder)
        {
            builder.Components().Append<StartupComponent>();
        }
    }

    public class StartupComponent : IComponent
    {
        private readonly IContentService _contentService;

        public StartupComponent(IContentService contentService)
        {
            _contentService = contentService;
        }

        public void Initialize()
        {
            _contentService.GetById(0);
        }

        public void Terminate()
        {
            
        }
    }
```
3. Start Umbraco

### Expected result / actual result

You get to the installer to prepare your database. After installation the Initialize should re-trigger based on the new RuntimeState (Installed) of Umbraco.

What actually happens is that Umbraco will just crash.

**Comment by nikolajlauridsen** [comment]
Hey @LennardF1989 

Thanks for reaching out, the components seem to work as expected, they are indeed run once before installing, and then again after the installation has succeeded. However, you do need to check the runtime manually like so: 

```C#
public class StartupComponent : IComponent
{
    private readonly IRuntimeState _runtimeState;
    private readonly IContentService _contentService;

    public StartupComponent(
        IRuntimeState runtimeState,
        IContentService contentService)
    {
        _runtimeState = runtimeState;
        _contentService = contentService;
    }

    public void Initialize()
    {
        // Only try and use the DB if we are in a running state
        if (_runtimeState.Level is not RuntimeLevel.Run)
        {
            return;
        }

        var getStuff = _contentService.GetById(0);
    }

    public void Terminate()
    {
    }
}
```

As a side note, components are really not recommended any longer, so I'd suggest using a notification handler instead, but the need to check the runtime state remains the same: 

```C#
public class StartupNotificationHandler: INotificationHandler<UmbracoApplicationStartedNotification>
{
    private readonly IRuntimeState _runtimeState;
    private readonly IContentService _contentService;

    public StartupNotificationHandler(
        IRuntimeState runtimeState,
        IContentService contentService)
    {
        _runtimeState = runtimeState;
        _contentService = contentService;
    }

    public void Handle(UmbracoApplicationStartedNotification notification)
    {
        if (_runtimeState.Level is not RuntimeLevel.Run)
        {
            return;
        }

        var getStuff = _contentService.GetById(0);
    }
}
```

**Comment by LennardF1989** [comment]
Thanks for getting back.

> As a side note, components are really not recommended any longer
Did I miss a memo somewhere? Where has this been stated? If that is the case, why aren't they tagged as obsolete? I also suppose we do still need composers to handle injections, so just the "components" are no longer recommended?

**Comment by nikolajlauridsen** [comment]
I'm not sure it has been specifically stated, and I'm honestly not sure why they're not obsoleted, that's of course our bad, I'll try and mention that to the team, to see if we can't get it marked as obsolete. 

But yes, composers are still very much needed, in particular for packages, if you're working within your own site it's recommended to create an UmbracoBuilder extension and call it directly in your `ConfigureServices` instead of relying on the composers. This is mostly a convention thing though, it's just nice to reduce the amount of magic and explicitly state what you're configuring in DI.
