### ISSUE TITLE
Can't drag-drop media files to upload them

### ISSUE THREAD

**Issue by jrunestone** [umbraco/Umbraco-CMS#14026]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

11.2.0

### Bug summary

When dragging a file (any file) to the media library to upload, the progress bar reaches 100% but the file is never uploaded/created. Creating and uploading the file "manually" with the create button works as expected.

### Specifics

The issue seems to be the call to `umbraco/backoffice/umbracoapi/media/PostAddFile` which never returns a response and eventually times out (see screenshot), or the client terminates the connection (HTTP/499).

We have checked the max file size limit and increased it but the problem occurs with very small files as well.

The site is hosted on Azure connected to a blob storage account, but this drag-drop feature has worked in the past. The solution is configured according to Umbraco's official docs on Azure hosting (file system based main dom lock etc). CMS is on a dedicated non-scaled instance.

No error logs (or any logs for that matter) are generated.

![image](https://user-images.githubusercontent.com/2293001/228466686-d0811494-4373-4978-b358-c45cc4d6c23b.png)

![image](https://user-images.githubusercontent.com/2293001/228470345-558336a9-3114-4359-874b-74626bc851d3.png)

NOTE: This was recently reported by another user in the Umbraco Discord and as far as I know he/she hasn't been able to resolve it (11.1.0):

![image](https://user-images.githubusercontent.com/2293001/228468155-af219a71-21e7-41bb-80d9-f0898399c26d.png)

### Steps to reproduce

Unfortunately I can't reproduce this in any of our test/stage/qa environments.
We don't have any custom code related to media uploads.

### Expected result / actual result

Dragging a file to the media library upload area should upload and create a file entry.
Instead it gets stuck at 100% and the call to PostAddFile times out, no error is given.

**Comment by jrunestone** [comment]
@Ambertvu thanks for the update, will check our notification handlers!

**Comment by tiagoalberto** [comment]
Hi guys. I'm having exacly the same issue in Umbraco version 11.2.2.
Steps to reproduce:
- Go to Media
- Upload an image by dragging into the canvas
- Remains at 100% forever. No error registered in console. 

As a workaround, I'm able to create new image and upload inside "Nem Image" form.

**Comment by jrunestone** [comment]
We have no content handlers that should affect this process, and it doesn't happen on local dev or stage, only in production. Additionally, it has stopped being an issue there too for some reason. (We haven't investigated further..)

However at least 3 people have now encountered this issue. I realize without repro steps it's practically impossible to do anything about it

**Comment by elit0451** [comment]
I have also tried to reproduce the issue locally on a fresh Umbraco 11.3.0 installation but as pointed out previously, the media file uploads correctly 🤷‍♀️ There is also a workaround in case the issue appears. I will close this one for now but we can easily reopen it if someone narrows down the problem 🙂
