### ISSUE TITLE
Setting ContentValueSetValidator in ConfigureProductIndexOptions do not seem to have any effect on indexing

### ISSUE THREAD

**Issue by ewuski** [umbraco/Umbraco-CMS#14029]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

10.0.0

### Bug summary

Used the custom index code exactly as it is in this documentation: https://docs.umbraco.com/umbraco-cms/v/10.latest-lts/reference/searching/examine/indexing

and created a custom index by the name of `ProductIndex` also supposedly locked to only _product_ document types (which we have in our solution).

In the `Configure(string name, LuceneDirectoryIndexOptions options)` method of the `ConfigureProductIndexOptions` a validator is being set:

`options.Validator = new ContentValueSetValidator(true, false, _publicAccessService, _scopeProvider, includeItemTypes: new[] { "product" });`

**The problem is that the validator settings do not seem to have any effect on the indexing.**

### Issue 1

In the given example it should index only published content of type _product_. However, it indexes all content types.

The indexed items includes content document types other than only _product_.

![custom-Index-issue-results](https://user-images.githubusercontent.com/104149844/228680368-2358d304-5d18-457b-a2ca-bbe77cee82da.gif)

(Not sure why ___NodeTypeAlias_ is missing but the pictured above content example is not a _product_ doc type)

### Issue 2

The `PublishedValuesOnly `property remains `false `despite it is passed as `true` to the validator constructor.

![custom-Index-issue](https://user-images.githubusercontent.com/104149844/228680622-7df1c5c6-7d6c-487b-a6fe-8df3cdcb2057.gif)

_PublishedValuesOnly_ is _false_ above ^

Also, after hitting the above line and then `ProductIndex`, the `Validator` property of options appears to be `null` and _PublishedValuesOnly_ remains _false_

        LuceneDirectoryIndexOptions namedOptions = indexOptions.Get(name); // < - namedOptions are not null
        if (namedOptions == null)
        {
            throw new InvalidOperationException($"No named {typeof(LuceneDirectoryIndexOptions)} options with name {name}");
        }

        if (namedOptions.Validator is IContentValueSetValidator contentValueSetValidator) // < - Validator is null
        {
            PublishedValuesOnly = contentValueSetValidator.PublishedValuesOnly;
        }

### Issue 3

When trying to limit the indexing to certain root node, eg.

`options.Validator = new ContentValueSetValidator(true, false, _publicAccessService, _scopeProvider, 1840, new[] { "product" });`

It also does not work - it indexes doc types from outside of that parent root.

### Steps to reproduce

1. Create custom _ProductIndex_ as described in the documentation: https://docs.umbraco.com/umbraco-cms/v/10.latest-lts/reference/searching/examine/indexing
2. Change the document type when creating `new ContentValueSetValidator` in `ConfigureBookingIndexOptions` to index other doc type if you don't have _product_ in your solution. Alternatively add a `parentId ` also as the validator parameter to check it is taken into account when indexing later (mentioned in Issue 3).
4. Put the breakpoint at the line where the validator is set (mentioned in Issue 1). The a breakpoint in `ProductIndex` constructor.
3. Start the solution and allow the index to create. Check whether Validator is not `null `in `ProductIndex`.
5. Go to _Settings_ in backoffice and rebuild created _ProductIndex_.
6. Check content and fields indexed.

### Expected result / actual result

My understanding is that the index `Validator` should disallow indexing of any item that is not in the `includeItemTypes`, is not within the root of the given `parentId `or unpublished nodes if `PublishedValuesOnly `is set to `true`.

**Comment by kjac** [comment]
Hi @ewuski,

Thank you for raising this 💪 I can understand why you're confused; so am I. The docs aren't terribly clear, and even worse - they are actually somewhat wrong. We clearly need to update the docs... I'll make sure to create a separate task for this in our backlog.

Generally speaking, custom indexes fall into one of two categories:

1. Content indexes like `ExternalIndex` but with only a subset of content (i.e. by using `ContentValueSetValidator` to filter by content type or scoped by parent ID).
   - These indexes contain the same data as `ExternalIndex`, and are automatically re-populated when content is published.
2. Indexes that contains custom data (possibly enriching content data with external sourced data).
   - These indexes require you to roll your own re-populate implementation.

For the first category, we do recommend you reuse the `ExternalIndex` and handle your filtering requirements at query time, but we also recognise that sometimes you do need a custom index. If this is what you're trying to achieve, here is some sample code that should get you started:

```csharp
using Examine;
using Examine.Lucene;
using Lucene.Net.Analysis.Standard;
using Lucene.Net.Index;
using Lucene.Net.Util;
using Microsoft.Extensions.Options;
using Umbraco.Cms.Core.Composing;
using Umbraco.Cms.Core.Configuration.Models;
using Umbraco.Cms.Core.Scoping;
using Umbraco.Cms.Core.Services;
using Umbraco.Cms.Infrastructure.Examine;
using Umbraco.Cms.Infrastructure.Persistence;
using IHostingEnvironment = Umbraco.Cms.Core.Hosting.IHostingEnvironment;

namespace Umbraco.Docs.Samples.Web.CustomIndexing;

public class ProductIndex : UmbracoExamineIndex, IUmbracoContentIndex
{
    public ProductIndex(ILoggerFactory loggerFactory, string name, IOptionsMonitor<LuceneDirectoryIndexOptions> indexOptions, IHostingEnvironment hostingEnvironment, IRuntimeState runtimeState)
        : base(loggerFactory, name, indexOptions, hostingEnvironment, runtimeState)
    {
    }
}

public class ProductIndexPopulator : ContentIndexPopulator
{
    public ProductIndexPopulator(ILogger<ContentIndexPopulator> logger, IContentService contentService, IUmbracoDatabaseFactory umbracoDatabaseFactory, IContentValueSetBuilder contentValueSetBuilder)
        : base(logger, contentService, umbracoDatabaseFactory, contentValueSetBuilder) =>
        RegisterIndex("ProductIndex");
}

public class ConfigureProductIndexOptions : IConfigureNamedOptions<LuceneDirectoryIndexOptions>
{
    private readonly IPublicAccessService _publicAccessService;
    private readonly IScopeProvider _scopeProvider;
    private readonly IOptions<IndexCreatorSettings> _settings;

    public ConfigureProductIndexOptions(IPublicAccessService publicAccessService, IScopeProvider scopeProvider, IOptions<IndexCreatorSettings> settings)
    {
        _settings = settings;
        _publicAccessService = publicAccessService;
        _scopeProvider = scopeProvider;
    }

    public void Configure(string name, LuceneDirectoryIndexOptions options)
    {
        if (name.Equals("ProductIndex") == false)
        {
            return;
        }

        options.Analyzer = new StandardAnalyzer(LuceneVersion.LUCENE_48);

        options.FieldDefinitions = new UmbracoFieldDefinitionCollection();

        options.UnlockIndex = true;

        options.Validator = new ContentValueSetValidator(true, false, _publicAccessService, _scopeProvider, includeItemTypes: new[] { "product" });

        if (_settings.Value.LuceneDirectoryFactory == LuceneDirectoryFactory.SyncedTempFileSystemDirectoryFactory)
        {
            // if this directory factory is enabled then a snapshot deletion policy is required
            options.IndexDeletionPolicy = new SnapshotDeletionPolicy(new KeepOnlyLastCommitDeletionPolicy());
        }
    }

    public void Configure(LuceneDirectoryIndexOptions options) => throw new NotImplementedException();
}

public class ProductIndexComposer : IComposer
{
    public void Compose(IUmbracoBuilder builder)
    {
        builder.Services.AddExamineLuceneIndex<ProductIndex, ConfigurationEnabledDirectoryFactory>("ProductIndex");

        builder.Services.ConfigureOptions<ConfigureProductIndexOptions>();

        builder.Services.AddSingleton<IIndexPopulator, ProductIndexPopulator>();
    }
}
```

Let me know if this works for you 😄

**Comment by nikolajlauridsen** [comment]
Hey @ewuski we haven't heard back from you for a while, so I'll go ahead and close this issue for now 👍
