### ISSUE TITLE
Colorpicker | "Include labels?"

### ISSUE THREAD

**Issue by Viktor-Abrahamsson** [umbraco/Umbraco-CMS#14039]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

10.4.2 

### Bug summary

When using or creating a new colorpicker and activating the "Include labels?", there are no option to add a label.

![image](https://user-images.githubusercontent.com/107833485/228897723-0bd4a12e-d225-45c5-b88b-77ff4474da06.png)

### Steps to reproduce

Create any colorpicker and try to activate "Include labels?".

**Comment by kjac** [comment]
Hi @Viktor-Abrahamsson,

That looks weird! It's supposed to do like this:

[14039.webm](https://user-images.githubusercontent.com/7405322/231125148-e467bfaa-e5a8-4470-96f2-813770f6e6c1.webm)

That screencast was recorded on v10.5-RC (latest v10/dev branch), but I have no reason to believe it shouldn't work on v10.4.x or v10.x for that matter.

Are there any errors in the JS console?

Could you try to force refresh your browser to ensure it's not a weird caching issue?

**Comment by Viktor-Abrahamsson** [comment]
Hello @kjac!

I forgot to mention it last time but there wasn't any errors in the console.

I've looked more into it and I've tried to use different browsers, clearing cache and in general trying to clear the backoffice (Sending a redeployment to cloud, clearing memory cache).

After all that and a restart of the environment it now seems to work.
