### ISSUE TITLE
v13: List of cultures contain invalid iso codes

### ISSUE THREAD

**Issue by iOvergaard** [umbraco/Umbraco-CMS#14049]
One thing I noticed is that some languages have an invalid iso code, so can't be created on the server, but we receive the list of cultures from the server, so would expect those to just work. Something for the backend to look at. "English (Albanian)" is one such example.

I'm on MacOS 13.2.1 running the v13/dev branch.

Here's a HAR file showing the error
[POSTLanguageAlbaniaError.har.zip](https://github.com/umbraco/Umbraco-CMS/files/11136800/POSTLanguageAlbaniaError.har.zip)

This payload:

![image](https://user-images.githubusercontent.com/752371/229470313-3f10b5ff-a708-4a4d-a92c-e8fc4ff235b1.png)

...leads to:

![image](https://user-images.githubusercontent.com/752371/229470247-5f5820df-8e6f-4ec9-bc87-044cd7db6c33.png)

_Originally posted by @iOvergaard in https://github.com/umbraco/Umbraco.CMS.Backoffice/pull/628#pullrequestreview-1368624779_

**Comment by iOvergaard** [comment]
Here's a HAR file showing the error
[POSTLanguageAlbaniaError.har.zip](https://github.com/umbraco/Umbraco-CMS/files/11136800/POSTLanguageAlbaniaError.har.zip)

This payload:

![image](https://user-images.githubusercontent.com/752371/229470313-3f10b5ff-a708-4a4d-a92c-e8fc4ff235b1.png)

...leads to:

![image](https://user-images.githubusercontent.com/752371/229470247-5f5820df-8e6f-4ec9-bc87-044cd7db6c33.png)

**Comment by andr317c** [comment]
Fixed in #14107
