### ISSUE TITLE
'Save and preview' not working for Safari

### ISSUE THREAD

**Issue by Pieter-vdh** [umbraco/Umbraco-CMS#14055]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

11.1.0

### Bug summary

When using Safari on Apple systems the 'Save and preview' does not open the preview window. It looks like the save function is working correctly, but not the preview.

### Specifics

Tested on **macOS Ventura 13.2.1 (Chip: M1)** with **Safari 16.3 (18614.4.6.1.6)**.
macbook Air gives the same issue.
Other browsers have no issue.

There is a javascript error given:
![image](https://user-images.githubusercontent.com/126693637/229755148-269031ce-b22f-421b-a5c3-614014ed196b.png)

### Steps to reproduce

While working with the Safari browser, click on the 'Save and preview' button when editing a content item.

### Expected result / actual result

Expected result:
The item is saved and a preview window opens.

Actual result:
The item is saved but no preview window opens.

**Comment by andrewmckaskill** [comment]
working on it

**Comment by andrewmckaskill** [comment]
Tried to reproduce on the following with no success:
- MacBook Pro M2 - Mac OS Ventura 13.3.1 - Safari 16.4 - Umbraco 12.0-rc3 (current contrib)
- MacBook Pro M2 - Mac OS Ventura 13.3.1 - Safari 16.4 - Umbraco 11.1 (reported Umbraco version)
- Browserstack (real device) - Mac OS Ventura - Safari 16.3 (reported OS/Browser) - Umbraco 11.1 (reported version)

Could

**Comment by nul800sebastiaan** [comment]
Maybe Apple fixed their browser in the mean time then. I'll close this for now but let us know if you can still reproduce it somehow!

**Comment by Pieter-vdh** [comment]
Thank you for checking, @andrewmckaskill . I'm not sure why it's not possible to reproduce. Unfortunately, the person who reported it to me is out of commission for a while, so I can't check with them.

As soon as I know more, I'll post it here.
