### ISSUE TITLE
Currently No Way To Enable Razor Components (Blazor) In Umbraco Back Office

### ISSUE THREAD

**Issue by YodasMyDad** [umbraco/Umbraco-CMS#14057]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

V12+

### Bug summary

As the title suggests, this .NET CMS currently has no way to enable part of the built-in .NET framework, Blazor in the back office. Currently, we have to sort of hack the scripts, by using a controller and a Route attribute to rewrite the default script/js path from the framework (As you can see here).

https://github.com/YodasMyDad/UmbracoBlazor/blob/master/BlazorExample.Site/Controllers/Api/UtilitiesApiController.cs#L33

As the back office is being completely rewritten to use web components, razor components (WASM/Custom Elements) can be used as web components. [See this link from the docs here](https://devblogs.microsoft.com/dotnet/asp-net-core-updates-in-net-6-rc-1/#blazor-custom-elements) and see [Steve Sanderson's demo here](https://youtu.be/Rn8psTi8FBk).

There is no reason why there shouldn't be a appSettings/Config option to enable Blazor support in the back office. You wouldn't build a platform on top of the latest version of .NET and then tell the .NET developers you can't use one of the most exciting advancements in .NET for years, a feature that is literally a built-in part of the framework. That just wouldn't make any sense.

It would be nice if this part of the framework was looked at now, tested, and not an afterthought. Especially considering the advancements that are currently being developed into .NET 8 with Blazor United

https://twitter.com/stevensanderson/status/1617951942873088001

### Specifics

See the summary above, can't be any more specific. The reason the scripts don't work out of the box currently is because of the base tag in the HTML, which is set to base='/umbraco/' in the current version, this is what breaks the Blazor scripts and what this rewrite/hack attempts to fix.

https://github.com/YodasMyDad/UmbracoBlazor/blob/master/BlazorExample.Site/Controllers/Api/UtilitiesApiController.cs#L33of 

However, as above, Razor Components are a core part of the framework, and HQ should be testing and looking at how they will work with the new back office. 

### Steps to reproduce

Just enable Blazor in a project and try to use it in the back office, then try and use the AngularJS services.

### Expected result / actual result

That Blazor worked in the project as Microsoft intended it to, and .NET developers can use .NET to develop and extend the .NET CMS Umbraco.

**Comment by kjac** [comment]
Hi @YodasMyDad,

Thank you very much for this detailed input 👍 

At this point we're not actively planning on bringing Blazor into the backoffice. For V12 it's highly unlikely that we will, as all effort is being put into rewriting the entire backoffice for V13.

For V13 we're currently focused on standardizing everything with native web components using the Umbraco UI library. This is taking up all available resources beyond what's already announced on the roadmap for V12, so adding Blazor as a backoffice extension tech is not in the cards right now. That's not to say it won't be, but for the time being we're not scoping it as part of the V13 backoffice rewrite.

We plan on prolonging the V13 RC time from the usual 6 weeks to about 6 months (so it won't really be RCs to begin with, more like early previews or alfas) to give everyone time to transition - specially of course package devs. It'd be interesting to see if the community could come up with clever approaches to using Blazor in the backoffice during that period, or of course later on.

I personally haven't followed Blazor that closely, so I'm not any kind of up to speed with Blazor or Blazor United for that matter. From what I do know though, there will likely be some interesting challenges to tackle in terms of both deployment (getting the WASM to a stand-alone client) and interaction with the entire Umbraco V13 client-side extension API. Of course, if Blazor is moving towards native web components, it stands to reason that these challenges will be easier to overcome. If/when the community picks up these challenges, we likely will have to do some close coordination with the FE team at HQ to ensure compatibility in registration and communication between Blazor and "normal" web components.

I'm going to close this issue for now. Please don't take that as a "No, we don't want Blazor in the backoffice". If the community wants to pick up Blazor support for the backoffice once V13 goes into preview, I believe a GitHub discussion would be a great place to start the task.

**Comment by YodasMyDad** [comment]
Looks like the community is looking to use Blazor, would be nice for HQ to help have a built in way to enable Blazor scripts and confirm whether the change in the base href ("/") will break things?

https://twitter.com/Reiters_uGarage/status/1695351043628945859

**Comment by kjac** [comment]
Hi @YodasMyDad,

We're currently not going to pursue Blazor as an backoffice extension model until we have V14 ready. See my previous comment.

That being said, we certainly welcome community investigations and findings on this.
