### ISSUE TITLE
Saving Datetime in code results in GMT date in content cache, but not DB.

### ISSUE THREAD

**Issue by Damien-Holley-Monkii** [umbraco/Umbraco-CMS#14053]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

8.18.6

### Bug summary

If you save a Datetime object to a node field and save it in code, the data will save correctly to the database but the date on the frontend will always be GMT.

### Specifics

If you save a Datetime object to a node field and save it in code, the data will save correctly to the database but the date on the frontend will always be GMT.

The date will appear correctly in the CMS, and no refreshing of the cache fixes the issue.

Saving the existing date on the node using the CMS save and publish button fixes the frontend, the data in the database does not change.

The same code was working fine on 8.7, unsure which update introduced the issue.

**Workaround**
Instead of using the code below and saving a datetime object, use the ToIsoString() extension on the datetime object.
`node.SetValue(propName, dateTimeObject.ToIsoString());`

### Steps to reproduce

`node.SetValue(propName, dateTimeObject);` results in the error.

I tried making sure the datetime was in our timezone, I also removed timezone from the datetime object and the error still occurs.
I also tried using a datetimeoffset object in the above configurations (at GMT, at local, etc).

### Expected result / actual result

I expected the datetime to be set correctly in the DB and FE, I expect the FE to match the DB data.

**eg:** Datetime is set to 8:26am 4/4/2023 AEST (2023-04-03T22:26:27Z) then the date should exist in the DB in either the GMT datetime or our local datetime and the FE should adjust to local (if the date is stored as GMT), or have no adjustment (if the date is stored as local), saving in the cms should not alter how the datetime works as long as the data in the DB is the same.

1. The datetime saved in the CMS and the Code is consistent, saving in local time.
2. Frontend does no adjustment to datetime when saved in the CMS
3. Frontend retrieves a GMT version of the datetime when it has been saved as a datetime object.

I supsect there is an 'extra step' occurring when the CMS saves the datetime, probably a conversion of somekind using JS.

**Comment by kjac** [comment]
Hi @Damien-Holley-Monkii,

Datetimes are tricky. I'm pretty sure the database expects and stores datatimes in UTC. Could you please try updating your code to use UTC explicitly when storing the datetime, and see if that makes the stored datetimes equal to the cached datetimes?

**Comment by Damien-Holley-Monkii** [comment]
I did that first thing, thinking that may have been the problem. One of the things we considered was that there may be another  property associated with it that was picking up the server offset and storing that, but not doing that when inputting  as an isostring.

Please note; Saving this way was working fine in 8.7 and only had the issue after updating to 8.18.

**Comment by kjac** [comment]
Hi @Damien-Holley-Monkii,

I tried testing this, and I still can't replicate it - neither on V8 latest, nor on V11 latest.

Here's my code:

```cs
using System;
using System.Web.Http;
using Umbraco.Core.Services;
using Umbraco.Web.WebApi;

namespace Umbraco.Web.UI.Custom;

public class MyApiController : UmbracoApiController
{
    private readonly IContentService _contentService;

    public MyApiController(IContentService contentService) => _contentService = contentService;

    [HttpGet]
    public IHttpActionResult DoStuff(int id)
    {
        var content = _contentService.GetById(id);
        if (content == null)
        {
            return NotFound();
        }

        content.SetValue("theDate", DateTime.UtcNow);
        _contentService.SaveAndPublish(content);
        return Ok(content.GetValue<DateTime>("theDate"));
    }
}
```

And here's a template rendering the published value:

```cshtml
@inherits Umbraco.Web.Mvc.UmbracoViewPage
@{
	Layout = null;
}
<html lang="en">
<head>
    <title>@Model.Name</title>
</head>
<body>
<h1>@(Model.Value<string>("theTitle"))</h1>
<h2>@(Model.Value<DateTime>("theDate"))</h2>
</body>
</html>
```

Given those, here's a screencast of me updating the datetime value programmatically, and how that update is reflected both in the published output and in the backoffice:

[14053.webm](https://user-images.githubusercontent.com/7405322/231682745-6925b537-a9f3-460c-a3d4-20f228120ec4.webm)

**Comment by Slipoch** [comment]
I was using strongly typed model output for the frontend partial. So `@Model.Param` not `@Model.Value<DateTime>("Param")`, possibly that is an issue?

As I said previously, this was working correctly previously. Nothing in that area was touched and we only discovered the issue after updating.

What timezone is your server set to in the example above?

**Comment by kjac** [comment]
> I was using strongly typed model output for the frontend partial. So `@Model.Param` not `@Model.Value<DateTime>("Param")`, possibly that is an issue?

That shouldn't matter 😄 

> As I said previously, this was working correctly previously. Nothing in that area was touched and we only discovered the issue after updating.

Things have likely changed between 7 and 8 to improve datetime handling. I honestly can't remember, it's been a while since 8 was built, and we weren't reporting breaking changes in the manner we do today.

> What timezone (or offset) is your server set to in the example above?

It's GMT + 1 (Denmark).
