### ISSUE TITLE
Block Editor Disabled if Block has Vary By Culture

### ISSUE THREAD

**Issue by alandraper** [umbraco/Umbraco-CMS#14065]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

11.2.2

### Bug summary

The block editor elements (e.g. RTE) appear disabled if the block element has "Vary by Culture" set. 

The editor element seems to have "preview" set which causes everything to be disabled. 

### Specifics

<img width="916" alt="image" src="https://user-images.githubusercontent.com/13674761/230429862-11132735-1387-49a3-9763-7c7375fc6268.png">

<img width="1214" alt="image" src="https://user-images.githubusercontent.com/13674761/230430536-da8e2378-2843-4145-b7aa-f807a811238a.png">

<img width="540" alt="image" src="https://user-images.githubusercontent.com/13674761/230431062-d7ced5dc-428c-4771-95ed-04058622132a.png">

### Steps to reproduce

1. Create new Umbraco site from 11.2.2 template
3. Create new Document Type "Page"; Allow at root
4. Add property "Demo Grid" with "Block Grid" editor
5. Install the demo "Umbraco Block Grid Demo" block grid
6. Verify everything works correctly
    a. Go to Content; 
    b. Create new Page at root; 
    c. Under "Demo Grid", add new "Rich Text" block. 
    d. Should appear correctly
    e. Discard changes
7. Go back to settings and add new Language
8. Go to Document Types / Umbraco Block Grid Demo / Rich Text 
9. Go to Permissions, and turn "Allow vary by culture" on
10. Save changes
11. Repeat process in (6) above, but notice that the editor is grayed out. 

### Expected result / actual result

Do not expect that allowing Vary by Culture would disable an editor control.

**Comment by alandraper** [comment]
I think the problem happens only if the Property "Demo Grid" _does not_ have Vary by Culture set, but the Block element _does_ have it set.

**Comment by kjac** [comment]
Hi @alandraper,

Thank you for reporting this 👍 I can reproduce on V11 latest.

As you correctly point out, the problem only occurs if the element type is configured as culture variant and the container property (block editor) is not.

This applies to both Block Grid and Block List.

The obvious workaround is to _not_ make element types vary by culture. In most scenarios this is also the preferable configuration, and it is also the default.

Still, the UI should not allow configuring something that yields a non-functional editing experience. I'll mark this as up for grabs if anyone would like to work on it.

**Comment by cf-marc** [comment]
Hi @kjac 

It seems this doesn't work in Version 10.5.0 too.
Thanks for fixing it. 

Best regards

![image](https://user-images.githubusercontent.com/128801863/232522750-1e22e64a-7100-4b07-8478-e0834451381b.png)

**Comment by JBoye** [comment]
> As you correctly point out, the problem only occurs if the element type is configured as culture variant and the container property (block editor) is not.

Is there a reason why this shouldn't be possible? 

I think it's a perfectly valid use-case to have the overall page structure fixed and the elements varying be culture.

**Comment by kjac** [comment]
@JBoye it's a perfectly valid use-case. We really want this feature, and it's already on the [roadmap](https://umbraco.com/products/knowledge-center/roadmap/) under Next ... it's called "Block Level Variations for Umbraco CMS" 😄

**Comment by mertglcan** [comment]
This issue still valid at v12.2 .But its fine with BlokGrid, but not working with Block List.

**Comment by peaxe** [comment]
Got the same error in Umbraco 13.4.1. The presented fix of not allowing "Vary by culture" for the element type fixed the issue.

**Comment by nielslyngsoe** [comment]
Having Culture Variant Blocks has never been supported, but a mistake that you could enable such in the UI.
This is not fixed and implemented as a feature as of v.15, therefor I will close this issue. Thanks for reporting it.
