### ISSUE TITLE
Unable to Upgrade to Umbraco 8.18.7 Due to "Broken composer dependency" Error

### ISSUE THREAD

**Issue by Nicholas-Westby** [umbraco/Umbraco-CMS#14066]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

8.18.7

### Bug summary

When upgrading from Umbraco 8.18.5 to EITHER Umbraco 8.18.6 or Umbraco 8.18.7 (the ones with the recent security patches), I get a "**Broken composer dependency**" error.

### Specifics

After I upgrade the Umbraco NuGet packages, I attempt to run the site but I get a YSOD with the following error shown on screen when I attempt to visit `/umbraco/` (probably all other URLs too, but I didn't try):

```
Server Error in '/' Application.
Boot failed: Umbraco cannot run. See Umbraco's log file for more details.

-> Umbraco.Core.Exceptions.BootFailedException: Boot failed.

-> System.Exception: Broken composer dependency: MyProject.UmbracoCms.Core.uSync.Publishers.SignalRFix.Composer -> uSync.Publisher.uSyncPublishComposer.
  at Umbraco.Core.Composing.Composers.GatherRequirementsFromAfterAttribute(Type type, ICollection`1 types, IDictionary`2 requirements, Boolean throwOnMissing) in D:\a\1\s\src\Umbraco.Core\Composing\Composers.cs:line 334
  at Umbraco.Core.Composing.Composers.GetRequirements(Boolean throwOnMissing) in D:\a\1\s\src\Umbraco.Core\Composing\Composers.cs:line 189
  at Umbraco.Core.Composing.Composers.PrepareComposerTypes() in D:\a\1\s\src\Umbraco.Core\Composing\Composers.cs:line 108
  at Umbraco.Core.Composing.Composers.Compose() in D:\a\1\s\src\Umbraco.Core\Composing\Composers.cs:line 86
  at Umbraco.Core.Runtime.CoreRuntime.Boot(IRegister register, DisposableTimer timer) in D:\a\1\s\src\Umbraco.Core\Runtime\CoreRuntime.cs:line 198
Description: An unhandled exception occurred during the execution of the current web request. Please review the stack trace for more information about the error and where it originated in the code.

Exception Details: Umbraco.Core.Exceptions.BootFailedException: Boot failed: Umbraco cannot run. See Umbraco's log file for more details.

-> Umbraco.Core.Exceptions.BootFailedException: Boot failed.

-> System.Exception: Broken composer dependency: MyProject.UmbracoCms.Core.uSync.Publishers.SignalRFix.Composer -> uSync.Publisher.uSyncPublishComposer.
  at Umbraco.Core.Composing.Composers.GatherRequirementsFromAfterAttribute(Type type, ICollection`1 types, IDictionary`2 requirements, Boolean throwOnMissing) in D:\a\1\s\src\Umbraco.Core\Composing\Composers.cs:line 334
  at Umbraco.Core.Composing.Composers.GetRequirements(Boolean throwOnMissing) in D:\a\1\s\src\Umbraco.Core\Composing\Composers.cs:line 189
  at Umbraco.Core.Composing.Composers.PrepareComposerTypes() in D:\a\1\s\src\Umbraco.Core\Composing\Composers.cs:line 108
  at Umbraco.Core.Composing.Composers.Compose() in D:\a\1\s\src\Umbraco.Core\Composing\Composers.cs:line 86
  at Umbraco.Core.Runtime.CoreRuntime.Boot(IRegister register, DisposableTimer timer) in D:\a\1\s\src\Umbraco.Core\Runtime\CoreRuntime.cs:line 198
```

Of note is that I recently upgraded to Umbraco 8.18.15 and I didn't encounter this issue then, so it seems like it was something introduced pretty recently (maybe even the security patches themselves).

FYI, the class from the top of the error details above looks like this:

```
using Umbraco.Core;
using Umbraco.Core.Composing;
using uSync.Publisher;
using uSync.Publisher.Publishers;

namespace MyProject.UmbracoCms.Core.uSync.Publishers.SignalRFix
{
    [ComposeAfter(typeof(uSyncPublishComposer))]
    public class Composer : IComposer
    {
        public void Compose(Composition composition)
        {
            composition.RegisterUnique<USyncServerHubConnectionFactory>();

            composition
                .WithCollectionBuilder<SyncStepPublisherCollectionBuilder>()
                .Exclude<SyncRealtimePublisher>();
        }
    }
}
```

The upgrade actually works if I change that `ComposeAfter` attribute to `[ComposeAfter(typeof(uSyncPublishComposer), true)]` (I don't actually fully understand the implications of this change). I can then revert that change after I run through the Umbraco upgrade process and the site works fine. However, I don't want to have to do this each time I upgrade Umbraco, so a long term fix would be ideal.

### Steps to reproduce

In theory, you should be able to create this issue by following these steps:

* Install Umbraco 8.18.5.
* Run through the install process to make sure it's fully installed.
* Install uSync 8.10.6 (see screenshot below for more potential uSync packages to install).
* Create the `Composer` class like below.
* Attempt to upgrade Umbraco 8.18.7 (or 8.18.6).
* You should see the YSOD with the "Broken composer dependency" error.

Here are all the uSync NuGet packages I have installed for reference:

<img width="425" alt="usync-dependencies" src="https://user-images.githubusercontent.com/5933222/230462201-1c709816-ef15-40cc-9b34-71e06abad2d7.png">

Here is the `Composer` class:

```
using Umbraco.Core;
using Umbraco.Core.Composing;
using uSync.Publisher;
using uSync.Publisher.Publishers;

namespace MyProject.UmbracoCms.Core.uSync.Publishers.SignalRFix
{
    [ComposeAfter(typeof(uSyncPublishComposer))]
    public class Composer : IComposer
    {
        public void Compose(Composition composition)
        {
            // Probably doesn't matter what's in this method.
        }
    }
}
```

### Expected result / actual result

I would expect that composers would not cause issues during an Umbraco upgrade, but the actual result is that this composer does cause an issue during an Umbraco upgrade (though, strangely, not outside of the upgrade process).

**Comment by kjac** [comment]
Hi @Nicholas-Westby,

By the looks of things, the `uSyncPublishComposer` is not active or loaded when your custom composer loads, which causes the broken dependency. I assume the `uSyncPublishComposer` still exists somewhere in the referenced uSync packages, since otherwise your code wouldn't compile 😃 and since things also seem to run outside the upgrade process, I'm going to venture a guess that this has to do with the runtime level.

You can annotate certain things (composers among that) with a required runtime level, in case they shouldn't be loaded i.e. during install. If you can inspect the `uSyncPublishComposer` definition, perhaps you'll find it decorated with a `RuntimeLevel` attribute?

In either case, try adding `[RuntimeLevel(MinLevel = RuntimeLevel.Run)]` to your custom composer and see if this solves your upgrade problem.

**Comment by Nicholas-Westby** [comment]
I do not see the uSyncPublishComposer decorated with a RuntimeLevel attribute:

<img width="612" alt="usyncpublishcomposer" src="https://user-images.githubusercontent.com/5933222/231819975-0dea3812-95f4-4e4d-8ec0-b1880468357a.png">

I also went to definition on each class with the `ComposeAfter` attribute to check the full ancestor list to see if they had a `RuntimeLevel` attribute, and none of them did. I went all the way to the root class, which was the following:

<img width="619" alt="usynccorecomposer" src="https://user-images.githubusercontent.com/5933222/231820220-5b043a68-9327-4ed9-a2bb-44c9c47d784d.png">

I will still try your recommendation since it sounds like that could circumvent the issue I'm experiencing. I'll let you know how it turns out.

**Comment by Nicholas-Westby** [comment]
Seems like that worked, thanks!

I am still curious why it was necessary, but I can bring that question to the forum if it doesn't seem like an Umbraco bug to you.

**Comment by kjac** [comment]
Awesome 👍 glad we figured out a solution. It seems curious that the uSync composers aren't marked with an explicit runtime, since it really does seem like they're utilizing one. Perhaps Kevin did some other registration magic somewhere. Or maybe `IUserComposer` is considered only for runtime level in V8, I truly don't remember 😄 

I'll go ahead and close this issue now. Thanks again for reporting 👏

**Comment by Nicholas-Westby** [comment]
For anyone curious, I have moved the discussion to the forum here: https://our.umbraco.com/packages/developer-tools/usync/usync/111669-unable-to-upgrade-to-umbraco-8187-due-to-broken-composer-dependency-error-from-usync-related-code

**Comment by KevinJump** [comment]
I think @kjac is right `IUserComposer` has a runtime level restriction on it, so the composers are only added when the level is run.
