### ISSUE TITLE
Shceduled Publish time changed with BST time change

### ISSUE THREAD

**Issue by gadgetfbi** [umbraco/Umbraco-CMS#14070]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

8.18.6

### Bug summary

Client had created a number of page edits prior to BST clocks changing by +1 hour, and scheduled to publish at a date and time after the UK clocks had changed (almost 1 week after 01/04/2023 00:59).

When we logged in to Umbraco after BST and the UK clocks going forward by 1 hour (EU hosted, which was now 1 hour behind BST), but before the scheduled publish date, it was found that all scheduled times had moved forward by 1 hour (01/04/2023 01:59)

### Steps to reproduce

Perhaps changing local machine time

### Expected result / actual result

I would have expected scheduled date and times not to have changed when local times change

**Comment by kjac** [comment]
Hi @gadgetfbi,

We haven't heard from you in a while so we're closing this issue now. Hope you managed to resolve the issue in the meantime 😄
