### ISSUE TITLE
GetProperty() with GetValue(culture) is using an cached VariationContext with incorrect culture, and shows wrong localized url from RichText link picker.

### ISSUE THREAD

**Issue by joelmandell** [umbraco/Umbraco-CMS#14071]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

10.2.1

### Bug summary

This seems to be kinda related to issue here: https://github.com/umbraco/Umbraco-CMS/issues/13865
If I understand it correctly, when accessing a property from content, without specifying anything, it will use the default language set in Umbraco. Doing a debug session with a NotificationHandler, and the call stack, the VariationContext seems to use a cached version...

If one at the same time, in the same context, try to GetProperty().GetValue("otherCulture"), the GetValue()-method will provide with link to the default-culture instead of the culture selected as parameter to GetValue()-method.

In case I haven't missed some other things... I have a PR ready that fixes this issue. It is esentially the same method that was in https://github.com/umbraco/Umbraco-CMS/commit/451d1cec6ab9ea3f1ea269fff3c4e95debfae5e7, but is added to internal Property-class.

### Steps to reproduce

You can reproduce it like in this comment: https://github.com/umbraco/Umbraco-CMS/issues/13865#issuecomment-1443475951

But with some slight modifications:

```
 public class MyNotificationHandler : INotificationHandler<ContentSavedNotification>
    {
        private readonly IUmbracoContextFactory _umbracoContextFactory;

        public MyNotificationHandler(IUmbracoContextFactory umbracoContextFactory)
        {
            _umbracoContextFactory = umbracoContextFactory;
        }

        public void Handle(ContentSavedNotification notification)
        {
            using (var context = _umbracoContextFactory?.EnsureUmbracoContext())
            {
                var settings = (Root?)context?.UmbracoContext?.Content?.GetAtRoot().Last();

                var variantRichTextDefaultCulture = settings?.VariantRichText;

                var variantRichTextOtherCulture = settings?.GetProperty("VariantRichText")?.GetValue("da");
            }
        }
    }
```

### Expected result / actual result

What is expected is the value (variantRichTextOtherCulture) to be a link to the localized page selected with url picker in rich text editor (i.e. "/da", but it will instead be "/").

**Comment by kjac** [comment]
Hi @joelmandell,

Thanks for reaching out. I can see from your PR that you're already on the right track 😄 

When you're working with variant content outside a published request context (i.e. in an API or a notification handler), it's your responsibility to supply the correct variation context to Umbraco before querying.

Here's some sample code that lets you work with culture variant content in a notification handler:

```cs
public class MyNotificationHandler : INotificationHandler<ContentSavedNotification>
{
    private readonly IPublishedSnapshotAccessor _publishedSnapshotAccessor;
    private readonly IVariationContextAccessor _variationContextAccessor;

    public MyNotificationHandler(IPublishedSnapshotAccessor publishedSnapshotAccessor, IVariationContextAccessor variationContextAccessor)
    {
        _publishedSnapshotAccessor = publishedSnapshotAccessor;
        _variationContextAccessor = variationContextAccessor;
    }

    public void Handle(ContentSavedNotification notification)
    {
        IPublishedSnapshot contentCache = _publishedSnapshotAccessor.GetRequiredPublishedSnapshot();
        IPublishedContent content = contentCache.Content!.GetAtRoot().First();

        _variationContextAccessor.VariationContext = new VariationContext("en-US");
        var englishTitle = content.Value<string>("title", "en-US");
        var englishRichText = content.Value<IHtmlEncodedString>("richText", "en-US")!.ToHtmlString();
        _variationContextAccessor.VariationContext = new VariationContext("da-DK");
        var danishTitle = content.Value<string>("title", "da-DK");
        var danishRichText = content.Value<IHtmlEncodedString>("richText", "da-DK")!.ToHtmlString();
    }
}
```

...and here's the same code wrapped in an API controller:

```cs
public class MyApiController : UmbracoApiController
{
    private readonly IPublishedSnapshotAccessor _publishedSnapshotAccessor;
    private readonly IVariationContextAccessor _variationContextAccessor;

    public MyApiController(IPublishedSnapshotAccessor publishedSnapshotAccessor, IVariationContextAccessor variationContextAccessor)
    {
        _publishedSnapshotAccessor = publishedSnapshotAccessor;
        _variationContextAccessor = variationContextAccessor;
    }

    // GET /umbraco/api/myapi/dostuff
    public IActionResult DoStuff()
    {
        IPublishedSnapshot contentCache = _publishedSnapshotAccessor.GetRequiredPublishedSnapshot();
        IPublishedContent content = contentCache.Content!.GetAtRoot().First();

        _variationContextAccessor.VariationContext = new VariationContext("en-US");
        var englishTitle = content.Value<string>("title", "en-US");
        var englishRichText = content.Value<IHtmlEncodedString>("richText", "en-US")!.ToHtmlString();
        _variationContextAccessor.VariationContext = new VariationContext("da-DK");
        var danishTitle = content.Value<string>("title", "da-DK");
        var danishRichText = content.Value<IHtmlEncodedString>("richText", "da-DK")!.ToHtmlString();

        return Ok(new { englishTitle, danishTitle, englishRichText, danishRichText });
    }
}
```

**Comment by joelmandell** [comment]
@kjac In this case it has to do with the GetProperty()-metod, not with using .Value.

In my case I ecountered this issue in a Blazor-component. 

I.E.
First I am getting a property by calling it from fetched content. This works well.

Secondly I am calling GetProperty and GetValue to fetch props based on some settings.

Is it not expected That passing culture to the GetValue method should pick content according to that culture?

**Comment by kjac** [comment]
Hi @joelmandell,

> Is it not expected That passing culture to the GetValue method should pick content according to that culture?

To a certain point it is. And it actually does... if you look closely, the link title will be a localized value. But when rendering links, Umbraco needs a context to get them right; i.e. relative URLs within the site scope of the current request context (provided the request host matches), absolute URLs for cross linkage between sites etc. etc. --- and for this, Umbraco needs context, which is what you're expected to define in `IVariationContextAccessor..VariationContext`.

Why do you need to set `IVariationContextAccessor..VariationContext`, you might ask? Because culture is only part of the puzzle. The current context could also be bound to a segment, i.e. for personalization.
