### ISSUE TITLE
Danish letters no longer are showns as thumbnails under Content

### ISSUE THREAD

**Issue by DimaKisiv** [umbraco/Umbraco-CMS#14093]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

We have Umbraco version 8.18.7

### Bug summary

If you upload a file to media picker that contains danish letters like æ ø å then thumbnails are not displayed in Content.
![image](https://user-images.githubusercontent.com/42111898/231790089-cf8c64ae-4711-45b2-b75d-d5e409568e8c.png)

### Steps to reproduce

Create document type with proeprty of type Media Picker. Craete a node of that document type. Try to upload jpg or png image file which name contains Danish letters like æ ø å and you will see that thumbnail is not displayed.

**Comment by Danish-Refugee-Council** [comment]
Same issue here, using Umbraco Cloud 8.18.7.
Adding to this: The issue tends to bloat the error log on umbraco.io with messages like this:
Unhandled controller exception occurred for request '"https://prof.euwest01.umbraco.io/umbraco/backoffice/UmbracoApi/Images/GetBigThumbnail?originalImagePath=%2Fmedia%2F0taiflpm%2Fmor-og-b%C3%B8rn-p%C3%A5-flugt-fra-ukraine_rum%C3%A6nien_4marts-22.jpg&rnd=0.010395527510403513"'
