### ISSUE TITLE
11.3 - content with compositions no longer gets indexed in Examine

### ISSUE THREAD

**Issue by Nuklon** [umbraco/Umbraco-CMS#14102]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

11.3

### Bug summary

Since 11.3, my content doesn't get indexed anymore. In Examine index, pageContent (this is my own property, see further down) is missing:

![image](https://user-images.githubusercontent.com/23340481/232233299-b080048c-ae25-4741-98de-6fcb68122efc.png)

The document type has a Page Content property of "Headered Contents", which it inherits from another document type. 
![image](https://user-images.githubusercontent.com/23340481/232233321-3c159e5e-17d7-4c1a-8fc2-637d700a9b33.png)
The headered content is a blocklist:
![image](https://user-images.githubusercontent.com/23340481/232233405-bfea8113-043f-44ee-9b7c-c30f43326bf9.png)
With the following settings:
![image](https://user-images.githubusercontent.com/23340481/232233423-3b8e54d6-22a0-4412-9349-c6f86a880af9.png)

The content model is this:
![image](https://user-images.githubusercontent.com/23340481/232233508-ac66455f-1d1c-4858-8a92-a8320a99eb5d.png)

In 11.2 this was indexed (as json I think), but in 11.3 it isn't indexed at all 😕 I tried rebuilding the index but it doesn't help.

### Steps to reproduce

See screenshots.

### Expected result / actual result

Index page content again.

**Comment by elit0451** [comment]
Hi @Nuklon 👋 

Thanks for reaching out! To reproduce your issue, I set up a fresh Umbraco 11.2.2 instance and then upgraded to 11.3.0, and in my case, the `pageContent` property appeared in the Examine index fields, _as you can see below_. I just had to rebuild the index to change from the JSON format to the new one:

## 11.2.2
<img src ="https://user-images.githubusercontent.com/21998037/232472503-5d567901-8bd9-4345-bdb8-ce59029c656f.png"/>

## 11.3.0
<img src ="https://user-images.githubusercontent.com/21998037/232472532-ea22d653-9504-4be8-a0e7-adaf4fb5b86a.png"/>
</br>

Could you provide some more details like if you are using a custom ValueSetBuilder or anything else about your indexing setup? 🙂

**Comment by Nuklon** [comment]
I'm not using a custom ValueSetBuilder or anything else for indexing. 

In 11.2.2:
![image](https://user-images.githubusercontent.com/23340481/232769568-4f2feedf-7fdb-483b-b20e-472fa18e0384.png)
See pageContentFaq is there correctly.

In 11.3 it's permanently missing, no matter how much I change, save, or rebuild.

![image](https://user-images.githubusercontent.com/23340481/232767242-5dd6acd5-3e3a-45e9-b3f6-bf458334bb0f.png)

I can reproduce this on a fresh install. To reproduce:
1. Create document type > Composition > Content Base. Add content like this:
![image](https://user-images.githubusercontent.com/23340481/232771715-25d70280-0496-4d16-abf5-cbcd9f756935.png)
2. Repeat 1. with this:
![image](https://user-images.githubusercontent.com/23340481/232771868-8a02749a-e04d-4f58-bded-094f4105a91c.png)
3. Create Headered Content element type like this (inherit from Content Base and Content Header Base):
![image](https://user-images.githubusercontent.com/23340481/232772134-ec2a72c3-2400-4744-9d39-0732db493a17.png)
4. Create new data type with the following settings (second screenshot is Headered Content block settings):
![image](https://user-images.githubusercontent.com/23340481/232772436-59295196-3e54-4300-841d-14f871abdf5e.png)
![image](https://user-images.githubusercontent.com/23340481/232772474-530c00e8-5711-4d84-9b5c-dfad0e970e59.png)
5. Create a document type with template and under "Content" group, add a Page content like this:
![image](https://user-images.githubusercontent.com/23340481/232772929-aca5edea-54a6-45c6-b549-a8cab80af4c7.png)
6. Add this document somewhere in "Content" and check Settings > Examine. It's not there.

Result from added "Test" document on a fresh install:
![image](https://user-images.githubusercontent.com/23340481/232774078-85fcfbc6-8f52-4fc7-bd1e-41924f8f2da1.png)

**It seems related to the inherited compositions. If I add a property directly to "Headered Content" it does get indexed:**

![image](https://user-images.githubusercontent.com/23340481/232774826-0e0aca9a-628d-4638-9ba9-1a247a2f7b92.png)

**Comment by Nuklon** [comment]
https://github.com/umbraco/Umbraco-CMS/blob/80f6bb404a36a1deba2cbc03f40800d93c3a61cb/src/Umbraco.Infrastructure/PropertyEditors/NestedPropertyIndexValueFactoryBase.cs#L41

This should be CompositionPropertyGroups. I will see if I can whip up a PR.

**Comment by elit0451** [comment]
The compositions part was missing in my initial attempt to reproduce this 😁 I can indeed confirm that this is an issue in the latest versions of Umbraco 10 and 11.

We would appreciate that @Nuklon! 🙌

**Comment by Zeegaan** [comment]
Fixed in https://github.com/umbraco/Umbraco-CMS/pull/14115
