### ISSUE TITLE
Member login skipping Two Factor Authentication checks 

### ISSUE THREAD

**Issue by OwainJ** [umbraco/Umbraco-CMS#14113]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

11.3.0

### Bug summary

When logging in a member, with the `IMemberSignInManager.PasswordSignInAsync()` method, the returned `SignInResult` object's `.Succeeded` property is always **True**, and the `.RequiresTwoFactor` property is always **False**. 
This then causes the member to be logged in without performing any 2FA checks.

### Specifics
Here's a video recording demonstrating the issue, using the example project that is linked below.
https://www.youtube.com/watch?v=eDwNLyT9NO8

I believe I've narrowed down the issue to the `IsTfaEnabled` method on the `UmbracoSignInManager` class, it appears that this is returning false due to the `GetValidTwoFactorProvidersAsync(...)` method returning with a count of 0.

### Steps to reproduce

1. Follow the  documentation to setup Member Two Factor Authentication: [https://docs.umbraco.com/umbraco-cms/reference/security/two-factor-authentication](https://docs.umbraco.com/umbraco-cms/reference/security/two-factor-authentication)
2. Enable 2FA on a Member
3. Attempt to sign in

I have set up an example project that exhibits the issue here: [https://github.com/OwainJ/MfaTestUmbraco11](https://github.com/OwainJ/MfaTestUmbraco11)
- This example project uses uSync to set up the necessary content nodes
- The back office sign-in details are on the example repo readme

### Expected Result
If a member has 2FA enabled, then the returned `SignInResult `object's `.Succeeded` property should be **False**, and the `.RequiresTwoFactor `property should be **True**.

### Actual Result
If a member has 2FA enabled, then the returned `SignInResult `object's `.Succeeded` property value is **True**, and the `.RequiresTwoFactor` property value is **False**.

**Comment by elit0451** [comment]
Hi @OwainJ 👋 

You have really impressed me with the effort you put into trying to share your findings 🙉 😁 👏 
Unfortunately, my attempts to reproduce the issue were unsuccessful... 

I followed our documentation as you suggested, on a fresh 11.3.0 install, with `GoogleAuthenticator` package installed (v3.0.0) - it worked right out (_with the `UmbLoginController`_) and I was prompted for the 2FA code. I even tried with a CustomLoginController as you did and debugged the `SignInResult` variable and the values were correct:
</br>

![Screenshot 2023-04-19 at 15 32 32](https://user-images.githubusercontent.com/21998037/233098263-9f5f532e-58c8-4533-b04d-85d28364b90d.png)

Here is the custom controller I used:
```c#
using Microsoft.AspNetCore.Mvc;
using Umbraco.Cms.Core.Cache;
using Umbraco.Cms.Core.Logging;
using Umbraco.Cms.Core.Routing;
using Umbraco.Cms.Core.Services;
using Umbraco.Cms.Core.Web;
using Umbraco.Cms.Infrastructure.Persistence;
using Umbraco.Cms.Web.Common.Models;
using Umbraco.Cms.Web.Common.Security;
using Umbraco.Cms.Web.Website.Controllers;
using SignInResult = Microsoft.AspNetCore.Identity.SignInResult;

namespace MyProject;

public class CustomLoginController : SurfaceController
{
    private readonly IMemberSignInManager _memberSignInManager;
    private readonly IMemberService _memberService;
    private readonly ITwoFactorLoginService _loginService;

    public CustomLoginController(IUmbracoContextAccessor umbracoContextAccessor,
        IUmbracoDatabaseFactory databaseFactory, ServiceContext services, AppCaches appCaches,
        IProfilingLogger profilingLogger, IPublishedUrlProvider publishedUrlProvider, IMemberSignInManager memberSignInManager, IMemberService memberService, ITwoFactorLoginService loginService) : base(umbracoContextAccessor,
        databaseFactory, services, appCaches, profilingLogger, publishedUrlProvider)
    {
        _memberSignInManager = memberSignInManager;
        _memberService = memberService;
        _loginService = loginService;
    }

    public async Task<IActionResult> HandleLogin([Bind(Prefix = "loginModel")] LoginModel loginModel)
    {
        if (ModelState.IsValid == false)
        {
            return CurrentUmbracoPage();
        }
        
        var member = _memberService.GetByEmail(loginModel.Username);
        
        SignInResult result = await _memberSignInManager.PasswordSignInAsync(
            loginModel.Username, loginModel.Password, loginModel.RememberMe, true);

        if (result.Succeeded)
        {
            TempData["LoginSuccess"] = true;
        }
        
        var mfaEnabled = await _loginService.IsTwoFactorEnabledAsync(member.Key);

        return Ok();
    }
}
```

I didn't run your code but I checked your `MemberAppAuthenticationProvider` which should correspond to the shown `UmbracoAppAuthenticator` example in the docs but all the changes you did were for fixing the null reference error, so nothings suspicious there. I am really not sure why it is not working for you. Perhaps you can try to replicate the problem on a plain Umbraco installation without the extra packages and get back to me?

**Comment by OwainJ** [comment]
Hi @elit0451,

Thanks for your reply 😊

I tried again on a new plain Umbraco installation, with just the App Auth provider in the docs, and it worked perfectly, so I then added my email 2fa provider using the extra packages, and that also worked perfectly! I then went line by line comparing my project that doesn't work to the plain one that does work and I finally spotted my mistake...

I mistakenly used the `BackOfficeIdentityBuilder` instead of the `MemberIdentityBuilder` when registering my Two Factor Providers in my composer... 😭 I got the issue to appear on the plain install when changing it to use `BackOfficeIdentityBuilder`.

Honestly, I can't believe I didn't notice that mistake before... Apologies for wasting your time with this.

Although it is interesting how `_twoFactorLoginService.GetEnabledTwoFactorProviderNamesAsync(...)` returns TwoFactorProviders registered via the `BackOfficeIdentityBuilder`, when called with a Member key, surely that should not be the case? Should a separate issue be opened for that? (or is that expected behavior?)

**Comment by elit0451** [comment]
Things like that happen so no worries 😁 

Please correct me if I misunderstood your question, but when you register your provider in your startup or a composer, the `ITwoFactorLoginService` will know about it no matter if it is meant for members or users. And since you used your `UmbracoAppAuthenticator` class as your provider on `BackOfficeIdentityBuilder`, it is still using the `IMemberService` to do all the two-factor set-up. So perhaps that's why you still managed to get your two-factor provider name when you requested it with the Member key.

```c#
var identityBuilder = new BackOfficeIdentityBuilder(builder.Services);
identityBuilder.AddTwoFactorProvider<UmbracoUserAppAuthenticator>(UmbracoUserAppAuthenticator.Name);
```

**Comment by OwainJ** [comment]
Ah yes, of course, that makes sense!

Thank's for looking at this for me 🙂
