### ISSUE TITLE
"Telemetry Data" tab doesn't work in Mozilla Firefox 

### ISSUE THREAD

**Issue by PeterKvayt** [umbraco/Umbraco-CMS#14128]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

11.3.0

### Bug summary

After clean install umbraco I opened "Settings" -> "Telemetry Data" tab and it was empty.

### Specifics

During installing I select minimal telemetry data level, use SqlLite default settings, Mozilla Firefox version 111.0.1

![image](https://user-images.githubusercontent.com/45105665/233293554-220b4790-d117-41f7-aa96-0a1e3e2cdbe5.png)
![image](https://user-images.githubusercontent.com/45105665/233294025-44b822f0-f2e4-4430-b4c3-533bc3b58759.png)

### Steps to reproduce

1. Clean install umbraco through wizard installer
2. Do not customize database settings
3. Select minimal telemetry data level
4. Open  "Settings" -> "Telemetry Data" tab

### Expected result / actual result

Expected result: works fine like in Chrome
![image](https://user-images.githubusercontent.com/45105665/233294958-2e04fccc-c6d6-41cd-8054-9333c7264331.png)
Actual result: Telemetry tab is empty
![image](https://user-images.githubusercontent.com/45105665/233295072-02f3ae65-059f-483e-8041-48b5a23abb64.png)

**Comment by PeterKvayt** [comment]
Hi @elit0451!

1. This behaviour only present with the Telemetry data dashboard
2. I did what you told - nothing changed (I dropped entier umbraco folder and `ConnectionStrings` section). Also I updated my Firefox version to the latest and I'm using windows 10
![изображение](https://user-images.githubusercontent.com/45105665/233333622-c743f795-af96-4149-8eea-c3e5ce6d204d.png)
Here is my newly created connection string:
![изображение](https://user-images.githubusercontent.com/45105665/233334704-4abe4a06-b32f-4d1c-98f8-a139e3a224ab.png)

**Comment by nul800sebastiaan** [comment]
Hmm, works for me on Windows too. I bet it's because of a Firefox extension, and if so: I assume it's an ad blocker that's hiding it 🙈 

![image](https://user-images.githubusercontent.com/304656/233342802-9911bfa7-46a7-4da5-8f9e-27468dd3fb50.png)

**Comment by PeterKvayt** [comment]
Hi @nul800sebastiaan!
You are right, ad blocker caused this issue. Disabling ad blocker extension for my site fix problem.
Thanks a lot!
