### ISSUE TITLE
v12 - EF Core Alternate Provider Support

### ISSUE THREAD

**Issue by mroberts91** [umbraco/Umbraco-CMS#14135]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

v12/feature/ef-core

### Bug summary

As seen in recent commits to the `v12/feature/ef-core` branch, there was a removal of code from the EF Core Context extension methods that drops support for exposing the `DbContextOptionsBuilder`, which would allow for the configuration of alternative EF Core Providers by consumers of the library.

We were under the assumption/hoping that the addition of EF Core to the Umbraco Platform would include the ability to use the rich ecosystem of data store providers that EF Core provides. It appears, looking at the current feature, that EF Core will be restricted to Sqlite and SQL Server.

``` csharp
private static void DefaultOptionsAction(DbContextOptionsBuilder options, string? providerName, string? connectionString)
{
    if (connectionString.IsNullOrWhiteSpace())
    {
        return;
    }

    switch (providerName)
    {
        case "Microsoft.Data.Sqlite":
            options.UseSqlite(connectionString);
            break;
        case "Microsoft.Data.SqlClient":
            options.UseSqlServer(connectionString);
            break;
    }
}
```
Exposing the `DbContextOptionsBuilder` would allow consumers to not be forced down the path of 2 data store providers as it currently sits with v11 and prior versions.

Our main use case for alternative providers would be using the NPGSQL EF Core Provider.

Can you confirm that the use case of EF Core in Umbraco v12 will be limited to just Sqlite and SQL Server?

### Steps to reproduce

Commit with the removal of `DbContextOptionsBuilder` [commit](https://github.com/umbraco/Umbraco-CMS/commit/38ad2860e59b613afa7981b7427493803171835e)

**Comment by CyberReiter** [comment]
I think Umbraco is missing a great opportunity if it is not giving the possibility to add different providers.
While Umbraco should itself only focus on the current 2 providers, the community should have the possibility to create packages offering support for different databases.

**Comment by Zeegaan** [comment]
Heyo! 👋 Not sure I'm understanding the use-case here 😁 
The extension method you're referring to that uses the `DefaultOptionsActions` method is the helper method to register your DbContext to use our scopes. The use case here is mainly to extend our database, and Umbraco only supports SQlite & SqlServer.
However, you can still create an entirely separate database, and register it using `.AddDbContext<>` in the `startup.cs` file. And here you can use whatever provider you want 👍

**Comment by Zeegaan** [comment]
I am closing this as hopefully my comment has cleared up any questions! 🙏 
Otherwise, any feedback you have are welcome on the PR for this feature: https://github.com/umbraco/Umbraco-CMS/pull/14109
