### ISSUE TITLE
appsettings : ImageFileTypes Schema Vs Docs is wrong

### ISSUE THREAD

**Issue by TRexStark** [umbraco/Umbraco-CMS#14131]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

10.5.0

### Bug summary

_I'm not sure if this has been raised before, but I think I've seen it somewhere and I have looked but could not find anything - so I apologise if it's a duplicate._

I wasn't sure if I should raise this here or in the Docs repo as they are both related and unsure which one is wrong (Docs Vs CMS).

It seems that the Imaging:ImageFileTypes is either using the wrong schema or the documentations may be wrong.

### Specifics

Both Documentation for [v10](https://docs.umbraco.com/umbraco-cms/v/10.latest-lts/reference/configuration/contentsettings) and [v11](https://docs.umbraco.com/umbraco-cms/reference/configuration/contentsettings) outline an example as **"ImageFileTypes": ["jpeg", "jpg", "gif", "bmp", "png", "tiff", "tif"]** which is an array.

When setting this configuration in appsettings.json as per the docs, intelliSense is returning a warning as "Value must be one of the following types: string".

When inspecting appseetings-schema.json > line 923, you can see that the type for "ImageFileTypes" is set to string.

### Steps to reproduce

- Using Visual Studio
- Make sure intelliSense is activated and properly setup
- Add the below configuration to appsettings.json.

`
"Umbraco": {
  "CMS": {
    "Content": {
...
      "Imaging": {
        "ImageFileTypes": ["jpeg", "jpg", "gif", "bmp", "png", "tiff", "tif"],
        ...
      },
...
    }
  }
}
`
- Notice that "ImageFileTypes" gets highlighted and check the warning message when you hover over it

**UPDATE:** The same goes for Plugins:properties:BrowsableFileExtensions

### Expected result / actual result

either the schema and implementation or documentations need to be updated so we know what we should do.

---
_This item has been added to our backlog [AB#32240](https://dev.azure.com/umbraco/243e7927-03b2-44e2-908f-d4ac7ea5daaa/_workitems/edit/32240)_

**Comment by nikolajlauridsen** [comment]
Hey @TRexStark it looks a bit like your schema may be a bit out of date, I'd recommend trying to delete it and rebuild, this should regenerate it, looking at my own test project the schema correctly specifies it as an array:

![image](https://user-images.githubusercontent.com/16456704/233396206-7eebdb14-b0a7-4e19-b5b8-9dc7ad5bb251.png)

**Comment by TRexStark** [comment]
Thanks @nikolajlauridsen.

Unfortunately, that didn't work for me.
Also that is not the reference that intelliSense is warning about, The issue for 'ImageFileTypes' is in line 923 under umbracoContent : properties : Imaging

I went to check the Generator in [v10/main](https://github.com/umbraco/Umbraco-CMS/blob/v10/main/src/JsonSchema/UmbracoJsonSchemaGenerator.cs) and the [client referenced](https://json.schemastore.org/appsettings.json) has the same issues outlined.

**Comment by elit0451** [comment]
I also experienced the same thing on VS, even though the IntelliSense suggest correctly the array type:

<img width="545" alt="Intellisense" src="https://user-images.githubusercontent.com/21998037/233633306-a3b7a5c3-c184-4fe6-810d-6e6e0f788908.png">
<img width="770" alt="warning" src="https://user-images.githubusercontent.com/21998037/233633301-ec000e2b-22f1-411a-8ee4-79b668e6a6cd.png">

I also tried regenerating the schema which worked until I reopened the project in VS again ..

It seems like in appsettings-schema.json we have defined `ImageFileTypes` twice:

```json
"ImageFileTypes": {
  "description": "Collection of accepted image file extensions",
  "type": [
    "string"
  ]
}
```

```json
"ImageFileTypes": {
  "type": "array",
  "description": "Gets or sets a value for the collection of accepted image file extensions.\n            ",
  "default": "jpeg,jpg,gif,bmp,png,tiff,tif,webp",
  "items": {
    "type": "string"
  }
},
```

**Comment by Zeegaan** [comment]
I can reproduce this! Even in rider 🤯 
![Uploading image.png…]()

## Reproduction stemps
- Install the Umbraco 10.5 template with this CLI command `dotnet new install Umbraco.Templates::10.5.0`
- Create a project `dotnet new umbraco -n "TestSchema"`
- Go into your `appsettings.json` file and add the following code snippet in the `Umbraco::Content` section
```
  "Imaging": {
    "ImageFileTypes": []
  },
```

**Comment by Zeegaan** [comment]
I looked into this, and there are 2 `ImageFileTypes`
![image](https://user-images.githubusercontent.com/70372949/233943972-ff493580-e9c8-47b4-bca5-9603640fc7aa.png)
So it should be a simple one to look into why the schema generates 2 different ones in v10, but not in v11, which is why this is marked as up for grabs  🙌

**Comment by miguelcrpinto** [comment]
This seems to happen as well in V10 for the RichTextEditor  Plugins"Umbraco": {
    "CMS": {
      "RichTextEditor": {
        "Plugins": [""]
      }
    }
  }

**Comment by miguelcrpinto** [comment]
I believe I figured out the issue. The appsettings-schema.json is saying that both the https://json.schemastore.org/appsettings.json and the appsettings-schema.Umbraco.Cms.json apply. In the case of appsettings-schema.Umbraco.Cms.json, both the Imaging:ImageFileTypes and the RichTextEditor:Plugins are of type string array. But in the https://json.schemastore.org/appsettings.json both these properties are declared as strings.

Who's in control of https://json.schemastore.org/appsettings.json? Is it needed?

If you remove the declaration of https://json.schemastore.org/appsettings.json from the appsettings-schema.json the issue is gone but I'm not sure if there's anything declared in the https://json.schemastore.org/appsettings.json that is not declared in the generated appsettings-schema.Umbraco.Cms.json

**Comment by miguelcrpinto** [comment]
Have you considered moving the Umbraco settings out of the appsettings.json into a separate file (something like UmbracoSettings.json) with it's own schema? 
This would keep the appsettings.json cleaner, would make it easier to find and maintain the umbraco settings in projects with lots of settings and you'd not need to maintain and ship the custom appsettings-schema.json anymore. The schema for this file (appsettings-schema.Umbraco.Cms.json) could either be included in the nuget or just published (versioned) in github.

A basic version of the file (with the schema available in the project) could look something like this:

`{
  "$schema": "./appsettings-schema.Umbraco.Cms.json",
  "Umbraco": {
    "CMS": {
      "Global": {
        "Id": "<project id>",
        "UseHttps": true,
        "SanitizeTinyMce": true
      },
      "Content": {
        "AllowEditInvariantFromNonDefault": true,
        "ContentVersionCleanupPolicy": {
          "EnableCleanup": true
        }
      }
    }
  }
}`

**Comment by elit0451** [comment]
Hi @miguelcrpinto,

Thanks for the extra effort to track this down 🙌 H5YR!  
We discussed this and we would make sure to remove `Imaging::ImageFileTypes`, `RichTextEditor::Plugins` and `Plugins::properties::BrowsableFileExtensions`, that were pointed out here, from the  https://json.schemastore.org/appsettings.json 🙂 and only keep their string array definitions

**Comment by miguelcrpinto** [comment]
@elit0451 considering that Umbraco is shipping with it's own schema (which depends on the CMS version) and including it in the appsettings-schema.json, shouldn't we just remove everything that is umbraco related from the https://json.schemastore.org/appsettings.json?

**Comment by elit0451** [comment]
Yes, that makes a good sense!

**Comment by miguelcrpinto** [comment]
I just created the Pull request to the schemastore: https://github.com/SchemaStore/schemastore/pull/3162

Once this is merged, we need to test again but the issue should be gone after refreshing the schema definition in Visual Studio (code)

**Comment by miguelcrpinto** [comment]
The [SchemaStore PR](https://github.com/SchemaStore/schemastore/pull/3162) has just been merged and it fixed the issue.

If you visit https://json.schemastore.org/appsettings.json there are no more references of Umbraco

You might need to force VS to reload the schemas (right click in the appsettings.json editor window):
![image](https://github.com/umbraco/Umbraco-CMS/assets/8625173/933fdd36-0942-4188-ab51-1b78ba81f3cf)

**Comment by Zeegaan** [comment]
@TRexStark could you confirm this is no longer an issue for you? Then we can go ahead and get this closed 🚀 😊

**Comment by TRexStark** [comment]
Hi @Zeegaan it seems that this is no longer an issue. Thank you. I'll close it.
