### ISSUE TITLE
Unable to migrate DB from v8.18.7 to v11.3

### ISSUE THREAD

**Issue by John-Blair** [umbraco/Umbraco-CMS#14141]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

11.3

### Bug summary

I am trying to migrate a DB from v8.18.7 to v11.3

I installed V11.3 of the Umbraco CMS using VS 2022 in a new project ok,  and then pointed the connection string in the appsettings.json file to the v8.18.7 DB and also set the appsettings.json file for upgradeunattended.

However, when I run the project I get the error "The migration plan does not support migrating from state "{03482BB0-CF13-475C-845E-ECB8319DBE3C}"". I can find no other info to help me out i.e. the UmbracoTraceLog file contains no other useful info.

I found the GUID in the error msg in the umbraco keyvalue table and also in the code file https://github.com/umbraco/Umbraco-CMS/blob/v9/contrib/src/Umbraco.Infrastructure/Migrations/Upgrade/UmbracoPlan.cs#L271 so I know it refers to 8.18.7 the latest version of umbraco 8.

I watched an Umbraco Video on how to upgrade from v8 to v10 and this is the process I followed. Video link here https://www.youtube.com/watch?v=wD9SGeRQR7o  but it does not seem to work going from v8 to v11.

How do I create an Umbraco v11 project and point it at the latest umbraco v8 database?

FYI I know you cannot migrate v8 code to v11 as .net framework code needs to be rewritten in .net core.

### Specifics

`"Umbraco": {
    "CMS": {
        "Global": {
            "Id": "9cc4adf9-618b-4c4c-88d1-42fa4207a790",
            "SanitizeTinyMce": true
        },
        "Unattended": {
            "UpgradeUnattended": true
        },
      "Content": {
        "AllowEditInvariantFromNonDefault": true,
        "ContentVersionCleanupPolicy": {
          "EnableCleanup": true
        }
      }
    }
  },
  "ConnectionStrings": {
    "umbracoDbDSN": "Server=.\\MSSQLSERVER01;Database=umbraco11-johnblair;User Id=umbraco;Password=xxx",
    "umbracoDbDSN_ProviderName": "Microsoft.Data.SqlClient"`

![image](https://user-images.githubusercontent.com/28809458/233658637-0eaf55af-009c-4c7c-8f44-800e3f576c43.png)

### Steps to reproduce

Copy a v8 db
install umbraco 11
udatate appsettings.json per Specifics settings above and run the project.

### Expected result / actual result

Expected result - upgrade completes with no errors.

**Comment by John-Blair** [comment]
Fixed issue.

Had to do an intermediate step:

Install v10.5.0 , point appsettings.json at v8.18.7 db and mark for unattended upgrade.

Install v11.3.0 point  appsettings.json at v8 db (now a v10.5.0 db)  and mark for unattended upgrade.

You are then able to log in to the back office and see current version is 11.3

**Comment by John-Blair** [comment]
Upgrade documentation could have at least mentioned the intermediate step.

**Comment by Myster** [comment]
Why were the 8-10 migrations dropped?
This file shows no migrations prior to v10
https://github.com/umbraco/Umbraco-CMS/blob/ce769ffff4613904bcc8c65103166a722db388a5/src/Umbraco.Infrastructure/Migrations/Upgrade/UmbracoPlan.cs
