### ISSUE TITLE
Examine MultiCharacterWildcard returns same scores for each time

### ISSUE THREAD

**Issue by Ambertvu** [umbraco/Umbraco-CMS#14159]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

11.3.0 (but also 11.2.x and 11.1.x)

### Bug summary

When making a simple search, and adding the MultiCharacterWildcard() on the searchterm, all results always have the same Score.

### Specifics

I encountered this on my own solutions a few versions ago, but thought it was an issue in my own code somewhere. Today I followed the Umbraco Searching & Indexing training, and we encountered the same.

As soon as you add a MultiCharacterWildcard() on your searchTerm, all scores have exact the same values.

### Steps to reproduce

Fairly simple search example (using the project from the training):

```
public IEnumerable<ISearchResult> GetSearchResults(string searchTerm, out long totalItemCount)
        {
            totalItemCount = 0;
            if (_examineManager.TryGetIndex(Constants.UmbracoIndexes.ExternalIndexName, out var index))
            {
                var searcher = index.Searcher;
                var fieldToSearch = "bodyText";
                var criteria = searcher.CreateQuery(IndexTypes.Content);
                var examineQuery = criteria.Field(fieldToSearch, searchTerm);
                var results = examineQuery.Execute();

                totalItemCount = results.TotalItemCount;

                if (results.Any())
                {
                    return results;
                }
                else
                {
                    Debug.WriteLine("No search items");
                }
            }
            return Enumerable.Empty<ISearchResult>();
        }
```

When searching on 'ipsum' I get this as result:
![image](https://user-images.githubusercontent.com/13347420/234280267-ed09008b-552e-4c6c-8b3c-9bf1eeda03a8.png)

When adding MultipleCharacterWildcard() these are the results:
![image](https://user-images.githubusercontent.com/13347420/234280429-60415c76-95a1-4cb3-9fab-f60e38f66e00.png)

### Expected result / actual result

Proper scoring for each item.

**Comment by nikolajlauridsen** [comment]
Hey @Ambertvu, just had a look and that does indeed seem to be the case, however, this functionality comes from Examine, and not the CMS itself, so there's not anything we can do about it from our side. 

I'd recommend instead creating an issue on the Examine issue tracker: https://github.com/Shazwazza/Examine/issues 😄
