### ISSUE TITLE
Umbraco Blockgrid - Delete blocks

### ISSUE THREAD

**Issue by thomashdk** [umbraco/Umbraco-CMS#14161]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

10.5.0

### Bug summary

I have a block in a BlockGrid datatype. The block has been used in a gridarea.
When deleting the block on the datatype, the blockgrid is not loading on the page where the datatype is used.

It breaks here:
`const contextColumns = getContextColumns(parentBlock, areaKey)
                          , relevantColumnSpanOptions = block.config.columnSpanOptions.filter(option=>option.columnSpan <= contextColumns);`
![image](https://user-images.githubusercontent.com/6445636/234288734-9460a938-140c-40ae-b5b6-1edd1d660d24.png)
![image](https://user-images.githubusercontent.com/6445636/234288877-336703e8-4fc2-4fdd-b472-cd4e46a06490.png)

And here:
```
if (null === block)
                            return null;
                        layoutEntry.$block = block,
                        null === (_block$config$areas = block.config.areas) || void 0 === _block$config$areas || _block$config$areas.forEach(areaConfig=>
```
                        
It's in the braco.directives.min.js.

### Steps to reproduce

- Create a Blockgrid
- Add a Block
- Add the blockgrid datatype to a doctype
- Create some content on the blockgrid with the block added.
- Save Publish
- Go to the datatype and delete the block from the blockgrid.
- Go to the content
- The blockgrid should not load

### Expected result / actual result

Be able to delete a block from the blockgrid without the node and content breaks.

**Comment by nikolajlauridsen** [comment]
Hey @thomashdk I can indeed replicate it, interestingly this issue seems to have already been fixed in V11, the changes should be in V10 as well, however, somewhere along the line the changes seem to have disappeared. 

I've created a PR which cherry-picks those changes back down to V10 which fixes the issue 🎉 

Thanks for reporting 🕵️👍

**Comment by Zeegaan** [comment]
Fixed in https://github.com/umbraco/Umbraco-CMS/pull/14194 😄
