### ISSUE TITLE
MultiUrlPicker JSON ends up in examine index as JSON

### ISSUE THREAD

**Issue by Nysosis** [umbraco/Umbraco-CMS#14162]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

11.3.0

### Bug summary

Similar to the changes made for https://github.com/umbraco/Umbraco-CMS/pull/13819 , if you've a property in the blockgrid/blocklist which has a property of `Umbraco.MultiUrlPicker` then I'm seeing the raw JSON in the index for the fields in the Examine Index, as opposed to just the the name of the node (which is what would be visible to someone using your site, so probably the only consideration for a search)

![image](https://user-images.githubusercontent.com/5476382/234307047-9e81efdc-1682-4443-a06b-abbcbd6bb7b9.png)

### Steps to reproduce

Create a new Umbraco 11.3 instance
Create a new block list / block grid element which has a property of MultiUrlPicker
Create a page with the element
Check the examine index for the site

---
_This item has been added to our backlog [AB#29317](https://dev.azure.com/umbraco/243e7927-03b2-44e2-908f-d4ac7ea5daaa/_workitems/edit/29317)_

**Comment by andr317c** [comment]
Hey, 

Thanks for the clear reproduction steps! I was able to reproduce this issue. And it will be set in as a sprint candidate

**Comment by nielslyngsoe** [comment]
Fixed by https://github.com/umbraco/Umbraco-CMS/pull/14416
