### ISSUE TITLE
I'm getting an error after downloading the project and building in VS2020

### ISSUE THREAD

**Issue by prosenba** [umbraco/Umbraco-CMS#14163]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

11.4.0

### Bug summary

After downloading the zip file and rebuilding in VS2020. I'm seeing error from build project.

Severity	Code	Description	Project	File	Line	Suppression State
Error	MSB4044	The "GetUmbracoBuildVersion" task was not given a value for the required parameter "GitCommitIdShort".	Umbraco.Core	C:\Users\Phill\.nuget\packages\umbraco.gitversioning.extensions\0.2.0\build\Umbraco.GitVersioning.Extensions.targets	5	

### Steps to reproduce

Download project, unzip it. open in VS2020 build project..

**Comment by nul800sebastiaan** [comment]
Hi @prosenba, first of all: we generally don't encourage building Umbraco from the source code unless you want to [contribute](https://github.com/umbraco/Umbraco-CMS/blob/contrib/.github/CONTRIBUTING.md).

But when you do, then the current requirement is to use the latest VS2022, as noted in the "[how to build Umbraco](https://github.com/umbraco/Umbraco-CMS/blob/contrib/.github/CONTRIBUTING.md)" documentation.

As a general heads up: we have many, many, many extension points for achieving anything you want to do with Umbraco without changing the source code. 
If you are indeed trying to contribute to Umbraco, for example to fix a bug then make sure to follow the contributing guidelines from the first link.

We'd also be very happy to talk to you about your scenario on our Discord - to give you us idea of what you want to work on, the Discord can be found at https://discord.umbraco.com 👍

**Comment by auroris** [comment]
I'm trying to diagnose a strange issue where GetPagedUsers takes 10 minutes to return any data, and GetCurrentUser also takes a very long time to return any data. This issue occurs on my web server, but not anywhere else. I have no idea why this is occurring. I'd like to sprinkle a bunch of debug statements all over the place to see if I can determine where the long waits are coming from, but I am also encountering error `The "GetUmbracoBuildVersion" task was not given a value for the required parameter "GitVersionHeight"` that I don't know how to get past.
