### ISSUE TITLE
KeepUserLoggedIn seems to be ignored

### ISSUE THREAD

**Issue by Behodar** [umbraco/Umbraco-CMS#14182]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

10.4.1

### Bug summary

appsettings.json has a setting called Umbraco.CMS.Security.KeepUserLoggedIn, which looks like it [stops users from being automatically logged out](https://docs.umbraco.com/umbraco-cms/reference/configuration/securitysettings) of the back office. It seems that this doesn't work in Umbraco 9/10/11.

There is some discussion of this issue at https://our.umbraco.com/forum/using-umbraco-and-getting-started/108929-keepuserloggedin-v9. The setting worked correctly in Umbraco 7 and 8 (although it was in umbracoSettings.config in those versions).

### Steps to reproduce

1. In appsettings.json, set Umbraco.CMS.Security.KeepUserLoggedIn to true.
2. Log into the back office.
3. Wait for the timeout (20 minutes?)
4. Notice that you get logged out.

An easy way of testing this is to log in, then close the browser. Come back later in the day and go to the back office, and it'll ask you to log in again.

### Expected result / actual result

I expected to remain logged in.

The documentation doesn't explicitly state what setting the value to true actually does (it only defines what setting it to false does), but it's fair to assume that it would work the same way as it did in Umbraco 7 and 8, i.e. keep the user logged in.

**Comment by Zeegaan** [comment]
I can certainly reproduce this! Interestingly enough, it does seem that the setting reflects back to the front-end
![image](https://user-images.githubusercontent.com/70372949/236796473-73cc6b15-776d-43bb-8200-116a74b28dca.png)

**Comment by DeadMonkeyX** [comment]
I'll be working on this :-)

**Comment by nul800sebastiaan** [comment]
We tried to reproduce this at the Codegarden hackathon, but it just worked. For now I'll close this issue but if we have more steps to reproduce we can have another look at it!

**Comment by Behodar** [comment]
I can confirm that this is still an issue in 10.5.1. There was also a comment from on this issue from @Zeegaan which seems to have vanished: "I can certainly reproduce this! Interestingly enough, it does seem that the setting reflects back to the front-end" with a screenshot of some JSON with "keepUserLoggedIn": true.

**Comment by Zeegaan** [comment]
Yea I thought I had reproduced it, but sadly not 😞
