### ISSUE TITLE
Danish translation typo

### ISSUE THREAD

**Issue by AndersBrohus** [umbraco/Umbraco-CMS#14183]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

10.5.1

### Bug summary

There is just some simple typos which has been fixed in the new translation :)

### Steps to reproduce

Open a Umbraco and find the "Block Grid" data type and select an element type.

**Comment by nul800sebastiaan** [comment]
Fixed in https://github.com/umbraco/Umbraco-CMS/pull/14184
