### ISSUE TITLE
Umbraco doesn't honor the "returnPath" after external login

### ISSUE THREAD

**Issue by jrunestone** [umbraco/Umbraco-CMS#14198]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

11.3.0

### Bug summary

If my backoffice session is outdated I am (transparently) redirected to my external login page (Azure AD in this case) and then back to the CMS start page - not to the URL specified in the `returnPath` of the query string.

### Specifics

![image](https://user-images.githubusercontent.com/2293001/235916846-a38b1a3c-e3d7-443a-8793-b0a2e19abb13.png)

### Steps to reproduce

* Setup an external login system for the backoffice (e.g. Azure AD)
* Make sure you are logged OUT of the backoffice
* Try to access an internal Umbraco page e.g. `https://cms-stage.lrf.se/umbraco#/settings`
* Notice you are asked to login, with the returnPath being the value of the URL you are trying to access
* Proceed to log in
* Notice you are being redirected back to the Umbraco start page, not the URL specified

### Expected result / actual result

I expect to be redirected to the value in the `returnPath` query parameter after logging in. Instead, I'm being redirected to the backoffice start page.

**Comment by justin-nevitech** [comment]
I did fix this in v10 so not sure if the fix didn't make it into v11 or if it has broken again.

Maybe worth someone checking?  I don't have time at the moment.

https://github.com/umbraco/Umbraco-CMS/pull/13026

**Comment by Zeegaan** [comment]
Hmm does seems like it's in v11, strange indeed

**Comment by jrunestone** [comment]
@justin-nevitech I remember, I even left a comment on your PR :) Your code is still there, something must have changed elsewhere. I'll have a look when I get the time..

**Comment by andr317c** [comment]
Hey!

Thanks for the reproduction steps! I was able to reproduce this issue on versions 11.3.0, 10.3.2, 10.3.0, and 10.1.0. I will mark this as an up for grabs!

**Comment by jrunestone** [comment]
I don't think @justin-nevitech PR ever solved the problem when an external authenticator was used, only the local login. The link for the "Sign in with Azure AD" button gets the correct `?returnUrl=` but somewhere it gets lost or the callback disregards it. I'm debugging between work projects..

![image](https://github.com/umbraco/Umbraco-CMS/assets/2293001/82bf1117-7e4a-4620-a921-3bbb6c982c14)
