### ISSUE TITLE
Incorrect audit log when sending approval for multiple languages 

### ISSUE THREAD

**Issue by kanalhui** [umbraco/Umbraco-CMS#14190]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

10.0.1

### Bug summary

I got a site with multiple languages.
When I updated English content and saved, then i updated Chinese content and "Send to approval" for both languages.
Only Chinese (the second language) is showing in the audit log.

![image](https://user-images.githubusercontent.com/132328472/235633816-fd630e81-5252-422b-a8d2-777f9c49d4b3.png)![image](https://user-images.githubusercontent.com/132328472/235633990-2ca2e113-8c32-4f36-b79b-22f85672e9fd.png)

### Steps to reproduce

•	Created a simple content node with two languages enabled
•	Created a writer user profile
•	Changed content on both languages with the writer profile (save on the first and send for approval on the second, but check marking both)
•	Only the second one shows up on the history dashboard, however, both of the changes are present when logging in with the admin user after.

### Expected result / actual result

If user select both languages, the audit log should show both language code like "Published" log.

**Comment by andr317c** [comment]
Hey! Thanks for the thorough reproduction steps. I can reproduce this issue on versions 10.0.1 and 11.4.0. 

I will mark this issue as up for grabs since we have good reproduction steps.
