### ISSUE TITLE
/umbraco/backoffice/umbracoapi/content/PostPublishById returns 404 error

### ISSUE THREAD

**Issue by BPadfield** [umbraco/Umbraco-CMS#14211]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

11.3.0/11.3.1

### Bug summary

When using the backoffice contentResource.publishById instead of publishing the content (as expected) I get a 404 error. This was working up to 11.2.2

### Specifics

/umbraco/backoffice/umbracoapi/content/PostPublishById

### Steps to reproduce

create a custom dashboard which has links to publish unpublished content using contentResource.publishById. Alternatively make a post request to publish by id using postman to /umbraco/backoffice/umbracoapi/content/PostPublishById 

### Expected result / actual result

I expect the item with posted id to be published, I just get a 404 error instead

**Comment by BPadfield** [comment]
This is the angular function which produces the 404 error for me:
$scope.doPublish = function (id) {
        contentResource.publishById(id).then(data => {
            console.log(data);
            loadLog();//This just refreshes the table which called this function
        })
    }
the id is the 4 digit content/node id.

When sending a request in postman with the body {"id":1192} I get the following response: {
"id": {
"ChildNodes": null,
"Children": null,
"Key": "id",
"SubKey": {
    "Buffer": "id",
    "Offset": 0,
    "Length": 2,
    "Value": "id",
    "HasValue": true
},
"IsContainerNode": false,
"RawValue": null,
"AttemptedValue": null,
"Errors": [
    {
        "Exception": null,
        "ErrorMessage": "content with id: 0 was not found"
    }
],
"ValidationState": "Invalid"
}
}

**Comment by netcamo** [comment]
Thank you  @BPadfield !

I have been able to reproduce the issue. As you said it works if you send body as x-ww-form-urlencoded and it doesn't work if it is raw. 

However there is another API that works in this case: `backoffice/umbracoapi/content/PostPublishByIdAndCulture`
In fact Umbraco itself publishes content with this API.


Payload should be  id and culture. 
In this case following payload: {"id":"1122", cultures: []} works perfectly. 



I hope it solves your problem and please let us know if this is the case!

**Comment by BPadfield** [comment]
Hi netcamo,

Yes, this solved my problem. After going back to the api documentation I realized the it does have publishbyid(id,cultures) although the example doesn't include a cultures array. Many thanks for your help.
