### ISSUE TITLE
sortCreateDate lang config keys appear to have the opposite values

### ISSUE THREAD

**Issue by ersc-git** [umbraco/Umbraco-CMS#14213]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

The bug is occurring on the latest v11

### Bug summary

The Newest and Oldest sort filters on the Users page of Umbraco appear to be sorting in reverse order. It is expected that Oldest users would be listed with the least recent CreateDate (Ascending order) first, and vice-versa for Newest users, but it appears to be the opposite. We believe this is caused by incorrectly defined keys within the language config files.

### Specifics

**umbraco.controllers.js** contains initialized data for the user sort filters. Here, Oldest is defined as having a sort direction of Ascending and Newest is defined as having a sort direction of Descending, as expected.

However, after this data is initialized, the labels are modified by the localization service to translate them into different languages as necessary. Using this lang config as an example (https://github.com/umbraco/Umbraco-CMS/blob/9a5e21702d8fb478e09c0040caaf787a4b1620f4/src/Umbraco.Core/EmbeddedResources/Lang/en_us.xml), it appears that sortCreateDateDescending is set to Oldest, and sortCreateDateAscending is set to Newest - the opposite of how it is defined in the code. As a result, the labels are being incorrectly swapped.

This is also true for other language configs beyond English (French and Italian are a couple other examples).

### Steps to reproduce

1) Go to the Umbraco backoffice site.
2) Click on the "Users" tab
3) Create a few sample users
4) Order by "Oldest" or "Newest"

### Expected result / actual result

Intended Result: "Oldest" create date user sort filter sorts in Ascending order, "Newest" create date user sort filter sorts in Descending order.

Actual Result: "Oldest" create date user sort filter sorts in Descending order, "Newest" create date user sort filter sorts in Ascending order.

**Comment by Zeegaan** [comment]
I can definetly reproduce this! sorting by oldest here, but my only active user is last?! 🤣 
![image](https://user-images.githubusercontent.com/70372949/236811814-7fa0a499-b6e0-4bd4-a345-20d6506a0fe5.png)

Should be a simple one to fix, so I'm marking this as up-for-grabs 🙌

**Comment by nul800sebastiaan** [comment]
Fixed in https://github.com/umbraco/Umbraco-CMS/pull/14315
