### ISSUE TITLE
NuCacheContentRepository.Rebuild can truncate the table without rebuilding the cache

### ISSUE THREAD

**Issue by ThomasSkyldahl** [umbraco/Umbraco-CMS#14253]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

11.3.1

### Bug summary

When calling: `NuCacheContentRepository.Rebuild(null, null, null)`
The `cmsContentNu` table gets truncated but no of the rebuild methods gets called leaving the  `cmsContentNu`  table empty.

### Steps to reproduce

1. call: `NuCacheContentRepository.Rebuild(null, null, null)`
2. see the table `cmsContentNu` is empty after the call

### Expected result / actual result

I would expect a method called Rebuild to actual perform a Rebuild and not just leave the cache empty.
in the `Rebuild*DbCache()` methods passing null or an empty array is treated equally but this is not the case in the `Rebuild()` method.

I would suggest changing the checks before the truncate to:
```
if ((contentTypeIds != null && !contentTypeIds.Any())
      && (mediaTypeIds != null && !mediaTypeIds.Any())
      && (memberTypeIds != null && !memberTypeIds.Any()))
{
    if (Database.DatabaseType == DatabaseType.SqlServer2012)
    {
        Database.Execute($"TRUNCATE TABLE cmsContentNu");
    }

    if (Database.DatabaseType == DatabaseType.SQLite)
    {
        Database.Execute($"DELETE FROM cmsContentNu");
    }
}
```
this ensures we don't truncate if null is passed

the other way would be to remove the `if` statements around the `Rebuild*DbCache()` method calls

**Comment by emmagarland** [comment]
Hi @ThomasSkyldahl, this should now be fixed by @DeadMonkeyX PR #14395. Thanks for raising it and your suggested resolution!
