### ISSUE TITLE
Media picker does not load until an event happens

### ISSUE THREAD

**Issue by vnv-dwarf** [umbraco/Umbraco-CMS#14250]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

11.1.0 and above

### Bug summary

When having a block list property that has the `Inline editing mode` enabled, and as available blocks has a document type that is marked as `Is an Element Type`, which has a property of type `Umbraco.MediaPicker3` that has the `Pick multiple items` property enabled, then the media does not load until an event happens (a click, a key input) or until the `GetRemainingTimeoutSeconds` request is called. After that, it will call the `GetById` request.

![image](https://github.com/umbraco/Umbraco-CMS/assets/130970849/cffbc5de-ccd1-4364-bbfe-d2bdd1c391f0)

Tested this on Umbraco 11.1.0, 11.3.1, where the bug is present, and also on Umbraco 11.0.0, where the bug is not present

### Specifics

![Animation](https://github.com/umbraco/Umbraco-CMS/assets/130970849/5fcd9aa6-7986-4d6f-812f-07d40beac981)

### Steps to reproduce

1. From settings, create a new document type, and call it `image test`
2. Add a group, and name it `image`
3. Add a property of type `Multi Image Media Picker` and name it `image`
4. From Permissions, set the `Is an Element Type` to true and click save
5. On an existing document type, or a new document type, add a property named `image` of type `Block List` where you enable the `Inline editing mode`, and for the `Available Blocks` you add the previously created block called `image test`.
6. From Content, create a new content of the document type where you added the property in step 5
7. Click on Add Image test
8. Add some media (at least one)
9. Collapse and then expand the `Image test` block and observe the loading animation, which will stay until an event happens (a click, a key input) or until the `GetRemainingTimeoutSeconds` request is called

### Expected result / actual result

The media should be loaded without the need of an event

**Comment by nikolajlauridsen** [comment]
Hey @vnv-dwarf I've had a look at reproducing this, and can indeed see that it is an issue. 

We would love to have some help to look at this, so I've gone ahead and marked it as up for grabs, thank you for reporting 👍

**Comment by MMasey** [comment]
Taking a look at the mo

**Comment by nul800sebastiaan** [comment]
Fixed in https://github.com/umbraco/Umbraco-CMS/commit/0ece94bf46ed880f42bb99e54b0740b7ffabd6e1
