### ISSUE TITLE
Cannot connect to SQL Server during install

### ISSUE THREAD

**Issue by idseefeld** [umbraco/Umbraco-CMS#14272]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

v12 rc

### Bug summary

In the install step "Configure your database" I cannot connect to SQL Server 2019 database neither with integrated authentication nor database user account. I use a a named instance "SQL2019":

![configure-your-database-install-step](https://github.com/umbraco/Umbraco-CMS/assets/866917/bec721c1-4dbe-4565-88ee-d6dc22eef1c1)

I have verified with SQL Server Management Studio, that connection with this settings is working and user has owner permissions.
The project works fine with SQLite.

### Steps to reproduce

Create a fresh v12 Umbraco project. Run and choose SQL Server instead of SQLite database.

---
_This item has been added to our backlog [AB#29662](https://dev.azure.com/umbraco/243e7927-03b2-44e2-908f-d4ac7ea5daaa/_workitems/edit/29662)_

**Comment by idseefeld** [comment]
I tried Paul Seals "Package Script Writer" and got an error message in the terminal window:
```bash
A connection was successfully established with the server, but then an error occurred during the login process. (provider: SSL Provider, error: 0 - Die Zertifikatkette wurde von einer nicht vertrauenswürdigen Zertifizierungsstelle ausgestellt.)
```
So I think the issue is caused by an issue on my machine.

**Comment by abjerner** [comment]
I'm getting the same issue, so might still be worth looking into.

When googling the error, it could seem that this might be due to a version of SQL server that is no longer supported by the SQL driver. In my case, I'm using SQL Express, and can't remember the last time that I updated it, so there could be some truth to that. But I haven't had the time to look into this yet.

**Comment by idseefeld** [comment]
I'm using a fairly recent SQL Server 2019 developer edition.

**Comment by abjerner** [comment]
I can see I'm not 12.0.2569.0, which should be SQL Server 2014. So I'm a bit more behind 😮 

The [release candidate blog post](https://umbraco.com/blog/umbraco-12-release-candidate/) doesn't seem to list any changes in supported versions of SQL Server, but I can see that the NPoco dependency was updated.

**Comment by idseefeld** [comment]
Looks like it is caused by an dependency update of Microsoft.Data.SqlClient to version 5.0.1.
I found a nice article which also gives a solution:
<https://weblog.west-wind.com/posts/2021/Dec/07/Connection-Failures-with-MicrosoftDataSqlClient-4-and-later>

The short clue is to add the following setting to the connection string: `;Encrypt=False`

Currently you can do this only with the CLI or unattended settings.  I have tried Paul Seals [Package Script Writer](https://psw.codeshare.co.uk/) and it worked.

**Comment by idseefeld** [comment]
@prjseal told me: 
`;TrustServerCertificate=true;` instead of `;Encrypt=false;` would be the preferred way to handle this.
I have tried this too and it works.

Btw. there is a quite long discussion about this at <https://github.com/dotnet/SqlClient/issues/1402>.

Microsoft documentation of TrustServerCertificate can be read here: <https://learn.microsoft.com/en-us/dotnet/api/system.data.sqlclient.sqlconnectionstringbuilder.trustservercertificate?view=dotnet-plat-ext-7.0>
and in more details at: <https://learn.microsoft.com/en-us/sql/relational-databases/native-client/features/using-encryption-without-validation?view=sql-server-ver16>.

My understanding is: 
You can use either `;TrustServerCertificate=true;` or `;Encrypt=false;` in development environments, but in production you should configure the SQL server with a valid certificate.

For the installer UI I think there should be a checkbox for this additional parameter and documentation should mention this issue or new requirement.

**Comment by prjseal** [comment]
I’ll add this to package script writer next week so it works with SQL Server

**Comment by kjac** [comment]
Hi everyone 👋 

Thank you all very much for digging into this. I do agree, we need to address this in the V12 installer somehow. I will bring it to the team Monday morning for an internal discussion.

How lucky we are to have people like you folk running the RC's through the paces! ❤️

**Comment by prjseal** [comment]
This has been added to Package Script Writer now.
[Example Here](https://psw.codeshare.co.uk/?InstallUmbracoTemplate=true&UmbracoTemplateVersion=&Packages=&UserEmail=admin%40example.com&ProjectName=MyProject&CreateSolutionFile=true&SolutionName=MySolution&UseUnattendedInstall=true&DatabaseType=SQLServer&UserPassword=1234567890&UserFriendlyName=Administrator&IncludeStarterKit=true&StarterKitPackage=clean&OnelinerOutput=false)

**Comment by Zeegaan** [comment]
This has been fixed in https://github.com/umbraco/Umbraco-CMS/pull/14361, sorry for the late update 🚀
