### ISSUE TITLE
Migration issue 9 => 10 / 11 on Members table

### ISSUE THREAD

**Issue by jbodt-Adver** [umbraco/Umbraco-CMS#14288]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

9.5.4

### Bug summary

Unable to upgrade from version 9 to 10 or up because of a migration error on the members table. 

### Specifics

Unable to upgrade from version 9 to 10 or up because of a migration error on the members table. Extra columns are added with a 'NotNULL' property but no default value which will result in a failure when members are present.

`"@t":"2023-05-08T08:05:55.8485375Z","@mt":"Exception ({InstanceId}).","@l":"Error","@x":"Microsoft.Data.SqlClient.SqlException (0x80131904): Cannot insert the value NULL into column 'isApproved', table '[db].dbo.cmsMember'; column does not allow nulls. UPDATE fails.\r\nThe statement has been terminated.\r\n`

### Steps to reproduce

Set up CMS version 9.5.4, add content, add Members then follow the upgrade procedure documented on https://docs.umbraco.com/umbraco-cloud/product-upgrades/major-upgrades

**Comment by ronaldbarendse** [comment]
@jbodt-Adver Thanks for reporting this, but I'm not able to replicate this when setting up an empty Umbraco 9 site that contains a couple members (using the default member type). The `AddMemberPropertiesAsColumns` successfully adds the new columns and migrates existing member properties to those columns:
```
[12:45:34 INF] Execute AddMemberPropertiesAsColumns
[12:45:34 INF] SQL [10]: ALTER TABLE [cmsMember] ADD [failedPasswordAttempts] INTEGER NULL
[12:45:34 INF] SQL [11]: ALTER TABLE [cmsMember] ADD [isLockedOut] BIT NULL CONSTRAINT [DF_cmsMember_isLockedOut] DEFAULT ('0')
[12:45:34 INF] SQL [12]: ALTER TABLE [cmsMember] ADD [isApproved] BIT NOT NULL CONSTRAINT [DF_cmsMember_isApproved] DEFAULT ('1')
[12:45:34 INF] SQL [13]: ALTER TABLE [cmsMember] ADD [lastLoginDate] DATETIME NULL
[12:45:34 INF] SQL [14]: ALTER TABLE [cmsMember] ADD [lastLockoutDate] DATETIME NULL
[12:45:34 INF] SQL [15]: ALTER TABLE [cmsMember] ADD [lastPasswordChangeDate] DATETIME NULL
```

The SQL query that migrates these values is quite verbose/complex (see [migration](https://github.com/umbraco/Umbraco-CMS/blob/contrib/src/Umbraco.Infrastructure/Migrations/Upgrade/V_10_0_0/AddMemberPropertiesAsColumns.cs)) and expects all previous member properties (like `umbracoMemberApproved` to exists (they were 'Locked' in previous versions, so couldn't be removed from the member type).

I suspect at least one of the member types doesn't have the `umbracoMemberApproved` property or at least one of the members doesn't have a value stored in the database for this property... Depending on whether this is the case and how that came to be, it's either a data corruption issue (which you should fix before upgrading) or the SQL query could be updated to use a default value when no value exists (and thereby avoid trying to set the NULL value).

**Comment by kjac** [comment]
What @ronaldbarendse said. I also just tried upgrading a 9.5.4 site with members to 10.5.1 with no problems.

![image](https://github.com/umbraco/Umbraco-CMS/assets/7405322/674a0590-cf53-4f20-adcb-0305532e9ef5)

In my test, one of the members was un-approved, but that made no difference to the upgrade process.

As the comment above hints, the new `isApproved` column has a default value in the table definition:

![image](https://github.com/umbraco/Umbraco-CMS/assets/7405322/dc17b8f5-5998-4ff2-b8b0-6c5baedcfb00)

Thus I come to the same conclusion; something is missing in your 9.5.4 database, likely one or more of the required member fields on one or more member types. How that has come to pass I cannot say.

The best way to fix this is to mend the members that are missing the `umbracoMemberApproved` property.

There is one possible workaround, but I must stress that this is **_absolutely_** not a supported workaround, and you should definitively have a backup of your DB on hand before attempting it. You can manually create and populate the new `cmsMember` columns and then upgrade the migration status to `{B7E0D53C-2B0E-418B-AB07-2DDE486E225F}` (in the `umbracoKeyValue` table) before continuing the migration onwards to V10+. This however can be quite the daunting task, particularly if you have a lot of members and need to reflect their membership status correctly. 

Once more, that workaround is **_not_** supported and might leave your database in a non-working state.

As neither @ronaldbarendse nor I can replicate this issue, I am going to close it as non-reproduceable. If you can supply additional steps on how to reproduce this from a clean 9.5.4 install being upgraded to V10, then please feel free to reopen this issue. For the time being, I urge you to get in touch with the good folk at [the forum](https://our.umbraco.com/forum) for further assistance in this matter.
