### ISSUE TITLE
Issue on Umbraco 12 RC2 with EF core in multiproject setup

### ISSUE THREAD

**Issue by rasmusfjord** [umbraco/Umbraco-CMS#14328]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

12.0.0-rc2

### Bug summary

I have a setup of 2 projects, both running 12Rc2:
- projectName.Web
- projectName.Code

All is running, ive spun up the solution using SQLite, have added a few document types etc.

In my code project I have my EF core entities and EF core contexts. In my web project, in startup, im adding the context like this:
`services.AddUmbracoEFCoreContext<StatusContext>(conString, providerName);`

Now i wanna execute and build my migration, normally I would go to my code project and run this 
`dotnet ef migrations add InitialCreate --context StatusContext`

But when I do this i get this error:
```
System.IO.FileLoadException: Could not load file or assembly 'System.Runtime, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The located assembly's manifest definition does not match the assembly reference. (0x80131040)
File name: 'System.Runtime, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
   at System.Reflection.RuntimeAssembly.GetType(QCallAssembly assembly, String name, Boolean throwOnError, Boolean ignoreCase, ObjectHandleOnStack type, ObjectHandleOnStack keepAlive, ObjectHandleOnStack assemblyLoadContext)
   at System.Reflection.RuntimeAssembly.GetType(String name, Boolean throwOnError, Boolean ignoreCase)
   at Microsoft.EntityFrameworkCore.Tools.ReflectionOperationExecutor..ctor(String assembly, String startupAssembly, String projectDir, String dataDirectory, String rootNamespace, String language, Boolean nullable, String[] remainingArguments)
   at Microsoft.EntityFrameworkCore.Tools.Commands.ProjectCommandBase.CreateExecutor(String[] remainingArguments)
   at Microsoft.EntityFrameworkCore.Tools.Commands.MigrationsAddCommand.Execute(String[] args)
   at Microsoft.EntityFrameworkCore.Tools.Commands.CommandBase.<>c__DisplayClass0_0.<Configure>b__0(String[] args)
   at Microsoft.DotNet.Cli.CommandLine.CommandLineApplication.Execute(String[] args)
   at Microsoft.EntityFrameworkCore.Tools.Program.Main(String[] args)
```

Then I was thinking, lets try it from the web project, couldnt hurt, though the migrations shouldnt be stored here of course, I get this error:
Your target project 'projectName.Web' doesn't match your migrations assembly 'projectName.Code'. Either change your target project or change your migrations assembly.
Change your migrations assembly by using DbContextOptionsBuilder. E.g. options.UseSqlServer(connection, b => b.MigrationsAssembly("projectName.Web")). By default, the migrations assembly is the assembly containing the DbContext.
Change your target project to the migrations project by using the Package Manager Console's Default project drop-down list, or by executing "dotnet ef" from the directory containing the migrations project.

Ive followed your guide here: https://docs.umbraco.com/umbraco-cms/v/12.latest/tutorials/getting-started-with-entity-framework-core and been setting multiple EF Core projects up so far.

### Steps to reproduce

setup 2 projects, a code that is being inherited into web, setup context and entity in code, setup context in startup in web, and run the migration script as mentioned

### Expected result / actual result

I just want the migration to run :)

**Comment by rasmusfjord** [comment]
If i take all my code parts and add to the web project it works.

**Comment by Zeegaan** [comment]
Heyo! 👋 Sorry for the late answer here.. 😢 

You can pass in a DefaultEFCoreOptionsAction Action in your `AddUmbracoEFCoreContext<StatusContext>`, to change this behavior! 

I was able to get it to work with this: 

```
    services.AddUmbracoEFCoreContext<BlogContext>("Data Source=|DataDirectory|/Umbraco.sqlite.db;Cache=Shared;Foreign Keys=True;Pooling=True", "Microsoft.Data.Sqlite",
                (options, name, connectionString) =>
                {
                    options.UseSqlite(connectionString, b => b.MigrationsAssembly("UmbracoWeb"));
                });
```

Maybe we should have some documentation about that 🤔
