### ISSUE TITLE
Media Picker in Rich Text Editor is misleading

### ISSUE THREAD

**Issue by russellshome** [umbraco/Umbraco-CMS#14320]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

10.5.1

### Bug summary

Media picker button in RichText editor is misleading because it can only pick images.

### Specifics

In the rich text editor there is a button called "Media Picker". One of my customers clicked that button and expected to be able to upload a PDF because a PDF is media. However the Media Picker is restricted to pick and upload only images.

### Steps to reproduce

Just look at the rich text editor

### Expected result / actual result

That "Media Picker" button should be changed to "Image Picker" to avoid this type of confusion.

**Comment by elit0451** [comment]
Hi @russellshome 👋 

Thanks for reaching out! You are right, this can be a bit misleading. Perhaps for your use case, you would like to use a link - check the following article for adding a "[Link to a Media File in Umbraco](https://docs.umbraco.com/umbraco-cms/tutorials/editors-manual/working-with-content#link-to-a-media-file-in-umbraco)" in your RTE. 🙂 

While for your request, it sounds like people will benefit from having the correct name for the picker, so we will encourage making a PR to change it. Additionally, we would have to change all articles in our documentation that mention "Media Picker" in the RTE to "Image Picker".

**Comment by russellshome** [comment]
Here is the realted pull request: https://github.com/umbraco/Umbraco-CMS/pull/14321
