### ISSUE TITLE
Richtext editor toolbar icons are missing in configuration

### ISSUE THREAD

**Issue by bjarnef** [umbraco/Umbraco-CMS#14324]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

11.4.0

### Bug summary

In configuration of richtext editor the options was previously showing icons.

![image](https://github.com/umbraco/Umbraco-CMS/assets/2919859/bc3d6623-5426-4653-acdf-33117a5a9187)

However after upgrade from TinyMCE v4 to v6, the fonts icons are no longer included, e.g. `mce-i-bold`.
Instead the toolbar icons are available as SVG icons, e.g. `bold.svg`: https://www.tiny.cloud/docs/advanced/editor-icon-identifiers/

### Steps to reproduce

Go to richtext editor configuration and noticed missing icons at toolbar options.

**Comment by bjarnef** [comment]
@iOvergaard any way we can import icons from `tinymce` in default `icons.js`?

![image](https://github.com/umbraco/Umbraco-CMS/assets/2919859/38b2bc4d-4d9e-4e67-a51d-0e9574fb5f4b)

![image](https://github.com/umbraco/Umbraco-CMS/assets/2919859/f45a9673-2770-4f4e-9d23-110198f9e55b)

I tried with `tinymce.IconManager.get("default").icons;` but seems to return empty.. I guess it need the instance.

**Comment by andr317c** [comment]
Hey!
Thanks for reporting this issue. 😃
I was able to reproduce this on a clean install of versions 11.4.0, 11.0.0, and 12.0.0-rc1.  All the icons are showing on version 10.5.4. I will mark this issue as up for grabs!

**Comment by iOvergaard** [comment]
Thanks for the issue report. The issue has been resolved and will be released in 12.0.0. It has also been picked for v11, so it will be included in the next version, which has not yet been announced.
