### ISSUE TITLE
Publish in Visual Studio doesn't publish all required files

### ISSUE THREAD

**Issue by SteveAndrews** [umbraco/Umbraco-CMS#14339]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

11.4.0

### Bug summary

When I set up Pubish to an Azure App Service (Windows), the process does not copy all the required files.

### Steps to reproduce

1. Create a new Umbraco site in Visual Studio using the Umbraco Project (Umbraco HQ) project template
2. Right-click the project and choose Publish...
3. Configure settings to deploy to an Azure App Service
4. Publish the site

### Expected result / actual result

All the necessary files should be published.

I believe this can be accomplished by updating the project template.

This is what I am using (note that some items are using `Content Update`):
```
<!-- INCLUDE IN PUBLISH -->
<Content Update="wwwroot\**" CopyToPublishDirectory="Always">
	<CopyToOutputDirectory>Always</CopyToOutputDirectory>
</Content>
<Content Include="App_Plugins\**" CopyToPublishDirectory="Always">
	<CopyToOutputDirectory>Always</CopyToOutputDirectory>
</Content>
<Content Update="Views\**" CopyToPublishDirectory="Always">
	<CopyToOutputDirectory>Always</CopyToOutputDirectory>
</Content>
<Content Update="appsettings.json">
	<CopyToOutputDirectory>Always</CopyToOutputDirectory>
</Content>
<Content Update="appsettings.Production.json">
	<CopyToOutputDirectory>Always</CopyToOutputDirectory>
</Content>
<Content Update="web.config">
	<CopyToOutputDirectory>Always</CopyToOutputDirectory>
</Content>
<Content Update="web.Release.config">
	<CopyToOutputDirectory>Always</CopyToOutputDirectory>
</Content>
<!-- EXCLUDE FROM PUBLISH -->
<Content Update="appsettings.Development.json">
	<CopyToOutputDirectory>Never</CopyToOutputDirectory>
</Content>
<Content Update="web.Debug.config">
	<CopyToOutputDirectory>Never</CopyToOutputDirectory>
</Content>
```

---
_This item has been added to our backlog [AB#32890](https://dev.azure.com/umbraco/243e7927-03b2-44e2-908f-d4ac7ea5daaa/_workitems/edit/32890)_

**Comment by Zeegaan** [comment]
What files are missing when you are publishing? 😁 
It would be great if you could come up with some reproduction steps, where you are publishing a type of file, and then it's missing 🤞

**Comment by SteveAndrews** [comment]
If I recall, the media folder in wwwroot is one example. I don't remember the rest. See the repro steps above.

**Comment by andr317c** [comment]
Hey!

Sorry for the late response, I just took a look at your issue, and I was able to reproduce it on v11.5.0 and v12.1.2. 

What I did was:
1. Create a Umbraco project using the template,
2. Run the project with a database on Azure.
3. Create media files.
4. Publish the project onto an Azure App Service (Windows).
5. Check if the published project contains the media files you created for your project.

When I followed these steps I ended up with an empty `wwwroot/media` folder. both on v11 and v12. 

I will mark this issue as a sprint candidate!😄 

Please let me know if I missed something.

**Comment by andr317c** [comment]
Hey again, We did some further investigation into this issue. And we found out that it is not actually an issue, your media folder contents are not supposed to be published with the rest of your project. I will go ahead and close this issue. Please write a comment if there is anything else!
