### ISSUE TITLE
Deleting a language causes all related content to be deleted permanently. No recycle bin option.

### ISSUE THREAD

**Issue by maartenmensink** [umbraco/Umbraco-CMS#14333]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

11.4.0

### Bug summary

Is this a functional bug or missing feature?

All content related to the language you delete is gone. No way to restore. One would expect a huge warning with this explicitly written in de popup dialog. Even better would be the ability to restore the language and content!

### Specifics

![image](https://github.com/umbraco/Umbraco-CMS/assets/339653/ad16d139-8ee7-4cd0-a04d-2179cd5060ae)

### Steps to reproduce

1. Go to <SITE URL>/umbraco/#/settings/languages/overview
2. Click delete on the language your are going to delete.
3. Watch all content disappear :octocat: 

### Expected result / actual result

**Expected result:**

Either have a option to restore the deleted content or have a major warning that this will delete all content related to the language with the explicit message there is no way to restore the content.

**Actual result**

All related content is gone!

**Comment by andr317c** [comment]
Hey!
Thanks for reporting💪 
All the content related to a language is indeed deleted when the language itself is deleted. 
You are correct about saying that the prompt for deleting a language should mention that all content related to the language will be deleted with the language.

I will mark this issue as up for grabs!

**Comment by prjseal** [comment]
I'm looking at this at the CG 23 hackathon

**Comment by emmagarland** [comment]
Thanks for raising this @maartenmensink.

This has now been resolved by @prjseal PR #14396 

Best wishes, 

Emma
