### ISSUE TITLE
Accented characters (e.g. Czech) fail to retrieve the file through Url in Azure Storage Blobs

### ISSUE THREAD

**Issue by HarrySpyrou** [umbraco/Umbraco-CMS#14346]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

10.1.0

### Bug summary

Using Azure storage blobs, when you create a file that includes a pdf with accented characters, the file is saved in azure storage correctly.

However, when trying to then retrieve it through the url (umbracoFile), then it cannot find the file. 

As an example, a file with accented characters from the Czech language will fail to be retrieved.

I did find that using the url from the storage account works just fine, so something inside Umbraco must be breaking that link.

### Specifics

It occurs every time you link to a file that contains an accented character pdf (maybe it affects images etc, not sure as of today)

### Steps to reproduce

Create file
Add pdf in czech language with accented characters and save
Link it to a document type with a picker of your choice (all you need is the url of it).
Try to click on the link in the frontend - you should get that the file is not found, even though it's saved in the storage account.

### Expected result / actual result

The file to be retrieved from the storage account based on its url.

**Comment by andr317c** [comment]
Hey! 

I was able to reproduce this issue on v10.1.0. 

I also tried to reproduce the issue on a clean install of v10.5.1, but it was working! So I would recommend that you'd upgrade to v10.5.1 to hopefully fix your issue 😄 

Just to make sure I also tried upgrading my v10.1.0 project to v10.5.1 to see if it fixed the problem, and it did!

I will go ahead and close this issue. Please comment if you still have any issues or questions! 👋
