### ISSUE TITLE
Unit test fails using NoopPublishedValueFallback

### ISSUE THREAD

**Issue by ane-dwarf** [umbraco/Umbraco-CMS#14342]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

11.3.0

### Bug summary

Unit test created with Xunit and Moq fails when using [`NoopPublishedValueFallback`](https://github.com/umbraco/Umbraco-CMS/blob/contrib/src/Umbraco.Core/Models/PublishedContent/NoopPublishedValueFallback.cs) after the introduction of [`EventuallyUpdateVariationContext`](https://github.com/umbraco/Umbraco-CMS/blob/9bafdbd992534c14d8ee8fad53c700258c15b3f3/src/Umbraco.Core/Extensions/PublishedElementExtensions.cs#L145) in [`Umbraco.Extensions.PublishedElementExtensions`](https://github.com/umbraco/Umbraco-CMS/blob/451d1cec6ab9ea3f1ea269fff3c4e95debfae5e7/src/Umbraco.Core/Extensions/PublishedElementExtensions.cs).

### Steps to reproduce

I am using [**Xunit** (v. 2.4.2)](https://www.nuget.org/packages/xunit/2.4.2) and [**Moq** (v. 4.18.4)](https://www.nuget.org/packages/Moq/4.18.4) to do the test but the issue should be independent of frameworks.

1. Create a new Element called `MyElementType`
2. Add a property to the type - let's call it `ElementName`
3. Generate models and make them available in your project
4. Create a test project and install Xunit and Moq
5. Create the following test:
```
[Fact]
public void Test()
{
    var publishedContent = new Mock<IPublishedElement>();
    var elementType = new MyElementType(publishedContent.Object, new NoopPublishedValueFallback());
    Assert.NotNull(elementType.ElementName);
}
```
6. Run the test

### Expected result / actual result

**Actual result**
Throws a NotImplementedException

**Expectation**
The test should not throw an exception and I would expect NoopPublishedValueFallback to handle initialization of VariationContextAccessor defined on IPublishedValueFallback without having to manually do it.

**My workaround**
Create a test VariationContextAccessor with an initialized VariationContext, mock the PublishedValueFallback and have it return TestVariationContextAccessor when VariationContextAccessor property is requested. This is then passed as parameter when the element type is created for the test.

**TestVariationContextAccessor**
```
public class TestVariationContextAccessor : IVariationContextAccessor
{
    public VariationContext? VariationContext { get; set; }
}
```

**PublishedValueFallback**
```
var publishedValueFallback = new Mock<IPublishedValueFallback>();

var variationContextAccessor = new TestVariationContextAccessor
{
    VariationContext = new VariationContext()
};

publishedValueFallback.Setup(x => x.VariationContextAccessor).Returns(variationContextAccessor);
```

**Comment by Zeegaan** [comment]
Heyo! 👋 I can see this issue has been resolved by: https://github.com/umbraco/Umbraco-CMS/pull/14227, unfortunately, this is not in a release yet, but will be in the next one 💪
