### ISSUE TITLE
Database Connection Issues - Website becomes unresponsive Connection Pool

### ISSUE THREAD

**Issue by JarFrank** [umbraco/Umbraco-CMS#14369]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

11.3.1

### Bug summary

Hi!

I'm encountering recurring issues with my database connections that are causing my website to become unresponsive for up to a minute at a time. Unfortunately I cannot reproduce it yet

```
Timeout expired. The timeout period elapsed prior to obtaining a connection from the pool. This may have occurred because all pooled connections were in use and max pool size was reached.
```
```
A connection was successfully established with the server, but then an error occurred during the login process. (provider: TCP Provider, error: 0 - An existing connection was forcibly closed by the remote host.)
```
```
The client was unable to establish a connection because of an error during connection initialization process before login. Possible causes include the following: the client tried to connect to an unsupported version of SQL Server; the server was too busy to accept new connections; or there was a resource limitation (insufficient memory or maximum allowed connections) on the server. (provider: TCP Provider, error: 0 - An existing connection was forcibly closed by the remote host.)
```
These issues seem to be associated with the NPoco.Database.OpenSharedConnectionImp method.
Any assistance with this issue would be greatly appreciated. I need to resolve this as it's causing significant disruptions to my website's functionality.

Thank you!

[provider.txt](https://github.com/umbraco/Umbraco-CMS/files/11705512/provider.txt)
[Connection pool.txt](https://github.com/umbraco/Umbraco-CMS/files/11705513/Connection.pool.txt)
[The client was unable to establish a connection.txt](https://github.com/umbraco/Umbraco-CMS/files/11705514/The.client.was.unable.to.establish.a.connection.txt)

### Steps to reproduce

I cannot reproduce it yet

**Comment by nikolajlauridsen** [comment]
Hey, @JarFrank I'm sorry to hear that you're having an issue, but without a way to reproduce, it or more concrete information about the issue I'll have to go ahead and close this one for now. I'd recommend asking our friendly community members over on the [Discord](https://community.umbraco.com/get-involved/community-discord-channel/) or reaching out to our support team 😄
