### ISSUE TITLE
An error was received from the server

### ISSUE THREAD

**Issue by SteveAndrews** [umbraco/Umbraco-CMS#14367]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

11.4.0

### Bug summary

Periodically I get a message in backoffice that is still templated.

![image](https://github.com/umbraco/Umbraco-CMS/assets/6685545/86f41bea-aec6-4a43-80d5-ac3134ecc600)

### Specifics

Update It appears to happen when the local web server (IIS Express) shuts down.

### Steps to reproduce

Unsure

### Expected result / actual result

I would expect to see the values of the tokens

**Comment by andr317c** [comment]
Hey!

Can you perhaps take a look at your logs to see if there are any errors?

Unfortunately without any reproduction steps, there is not really anything we can do.

**Comment by SteveAndrews** [comment]
It seems to happen when the local web server (IIS Express) shuts down. I am working in Visual Studio Community 2022 (17.6.2) and Ctrl+F5 to spin up IIS Express. Sometimes IIS Express shuts down (not an appliction error, it's just unreliable), and I believe that triggers this error. The placeholders aren't filled in because the web server isn't running. Perhaps the code could detect that the server-side no longer exists and show an appropriate message?

**Comment by nikolajlauridsen** [comment]
Hey @SteveAndrews is it correctly understood that this only happens when the web server shuts down? I think that's sort of to be expected, if the server is down it cannot actually send any error response and you'll see this.

**Comment by SteveAndrews** [comment]
Agreed, but perhaps there is a way to detect that and show an appropriate message instead? This is admittedly not high priority, but could also be encountered if someone loses Internet. It'd suck to be worrying the site has an error and not be able to reach it.

**Comment by andr317c** [comment]
Hey!

I would say this sounds more like a feature request than an issue. So I will go ahead and close the issue. 

The feature itself sounds like a nice thing to have. So If anyone is up to it, please go ahead and create a PR for the feature 😄.
