### ISSUE TITLE
Umbraco re-writes appsettings.json and sets the connection string to sqlite when it can't find the database

### ISSUE THREAD

**Issue by luisabreu** [umbraco/Umbraco-CMS#14366]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

Assembly file version: 10.0.0.51/AssemblyInformationalVersion: 10.0.0+e3f4b86

### Bug summary

Hello.

First, let me start by saying that I'm not an Umbraco user or developer, so I'm not sure if this description and log file is enough for debugging the issue. 

We've detected a really strange behavior in our website after our instrastructure went down. The site is using SQL Server as its database and when data center rebooted, the IIS site couldn't reach the database and was redirected to the installation page (I think that this is a known bug that has already been reported). When the support team looked at the logs, we've started seeing lots of unexpected sqlite exceptions which was weird because the app should be using SQL Server. After opening appsetings.json, sure enough, the connection string was pointing to the default sqlite connection string.

I've copied the web site to my machine and even though I've managed to reproduce the problem a couple of times (ie, when not reaching the db and being redirected to the installation page, submitting the form with some predefined conditions/state ends up updating the appsettings.json file). Unfortunately, I wasn't able to document the steps (or their order) required to do it (I've tried lots and lots of things and when it did happened, I wasn't able to reproduce it again with the last couple of steps I was documenting).  What I can say is that the appsetings.json file does get updated when umbraco returns the "already initialized exception" on the wizard's installation step 2 (most of the time, it will simply show an installation error saying that a  network-related or instance-specific error occurred while establishing a connection to SQL Server, which is the expected exception).

I'm attaching the logs of one of the last times I've ended up with an updated connection string. You won't see the sqlite exceptions because I've stopped trying to submit the installation wizard after getting that error (ie, I've notice that the date modified property on the appsettings.json file changed and after that I simply didn't submit the form again). The other entries on the file are there because I've tried to several times get the correct steps to reproduce the issue (without any success).

Here's the json log file from the site:

[UmbracoTraceLog.WS-WINDOWS1001.20230608.txt](https://github.com/umbraco/Umbraco-CMS/files/11693050/UmbracoTraceLog.WS-WINDOWS1001.20230608.txt)

### Steps to reproduce

Unfortunately, I wasn't able to get the list...I did reproduce it several times though and if you're insterested, I can send you the other logs I have.

**Comment by andr317c** [comment]
Hey!

We'd recommend that you upgrade to v10.5.1 to see if that fixes your error. If upgrading does not fix your error please write a comment so we can take another look 😄

**Comment by luisabreu** [comment]
Hello again.

I'll pass the message, but seems it's an edge case, I'm assuming it's still there.
