### ISSUE TITLE
Macro's PropertyTypePicker throws error in backoffice

### ISSUE THREAD

**Issue by ewuski** [umbraco/Umbraco-CMS#14371]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

Umbraco 10.0.0 (and 9.0.0)

### Bug summary

_PropertyTypePicker_ is one of the types available for macro parameters. Same _MultiplePropertyTypePicker_

It worked fine in v7.
However when upgraded to Umbraco 10 the macros that use them throw error in the backoffice. And the list of properties do not display in the macro property dropdown. (The selected property is fine and the macro works in the front-end if already populated)
It does the same when creating a fresh new macro with _PropertyTypePicker_ or _MultiplePropertyTypePicker_ in v10.

See related forum post: https://our.umbraco.com/forum/using-umbraco-and-getting-started/109195-macro-with-property-type-picker-throws-error-on-opening

### Specifics

![Umbraco-9-error](https://github.com/umbraco/Umbraco-CMS/assets/104149844/58272006-9a1c-487f-af38-23ccf5f36014)

### Steps to reproduce

Create a new macro with _PropertyTypePicker_ or _MultiplePropertyTypePicker_ as parameter. Try to add it into a page grid. Error will be thrown and the property dropdown will be empty.

The documentation says they are one of available data types in macros, yet they are not working: https://docs.umbraco.com/umbraco-cms/v/10.latest-lts/reference/templating/macros/managing-macros

### Expected result / actual result

It should not throw an error and the properties should display in the macro parameter dropdown.

**Comment by ewuski** [comment]
Great thanks!

**Comment by andr317c** [comment]
Hey @dunfe 
Sorry for the late reply, the fix for this issue will be in release 11.4.3.😄 The target release for 11.4.3 is next week.

**Comment by dunfe** [comment]
In case you can't upgrade the Umbraco, I have a solution for you.

`    public class HotfixDefinitionMapping : IMapDefinition
    {
        public void DefineMaps(IUmbracoMapper mapper)
        {
            mapper.Define<IPropertyType, EntityBasic>((source, context) => new EntityBasic(), Map);
        }

        private static void Map(IPropertyType source, EntityBasic target, MapperContext context)
        {
            target.Alias = source.Alias;
            target.Icon = "icon-box";
            target.Id = source.Id;
            target.Key = source.Key;
            target.Name = source.Name;
            target.ParentId = -1;
            target.Path = string.Empty;
        }
    }`

Then add to composer:
`            builder.WithCollectionBuilder<MapDefinitionCollectionBuilder>()
                .Add<HotfixDefinitionMapping>();`

**Comment by andr317c** [comment]
Hey,

The issue should be fixed in 10.6.0! Please let me know if it's still an issue
