### ISSUE TITLE
ContentDeletingNotification is not triggered when emptying the Recycle Bin

### ISSUE THREAD

**Issue by wtct** [umbraco/Umbraco-CMS#14380]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

11.4.0

### Bug summary

We have just noticed that the ContentDeletingNotification is not triggered when emptying the recycle bin.

cc: @piotrbach

### Steps to reproduce

1. Implement simple notification handler with composer like this:
```
public class TestComposer : IComposer
{
    public void Compose(IUmbracoBuilder builder)
    {
        builder.AddNotificationHandler<ContentDeletingNotification, ContentDeletingNotificationHandler>();
    }
}

public class ContentDeletingNotificationHandler : INotificationHandler<ContentDeletingNotification>
{
    public void Handle(ContentDeletingNotification notification)
    {
        notification.Cancel = true;
    }
}
```
3. Create a new node.
4. Delete a node (move to the Recycle Bin).
5. Empty the Recycle Bin.

### Expected result / actual result

Expected result:

The ContentDeletingNotification should be triggered, because emptying the Recycle Bin is only another way of deleting a node.

In this particular case node shouldn't be deleted.

Actual result:

The ContentDeletingNotification is not triggered and node is removed in this particular case. 

Everyone needs to be aware of this and handle another ContentEmptyingRecycleBinNotification to achieve expected result.

BTW, There are two cases of Deleting: 

1. Moving to the Recycle Bin.
2. Deleting from the Recycle Bin

When you cooperate with editors, it could be complicated sometimes to be on the same line.

Maybe there should be Remove and Delete verbs in the backoffice?

https://adnanpuzic.medium.com/the-difference-between-remove-and-delete-7f6c1771e40f

**Comment by JasonElkin** [comment]
Hey @wtct, I've created a PR that provides a technical fix for the notification.

I think your point about the "delete" language is a good one - it might be an idea to create a separate issue that addresses that specifically.

**Comment by wtct** [comment]
Thanks @JasonElkin for the PR.

I have created another issue related to deleting/removing:

https://github.com/umbraco/Umbraco-CMS/issues/14398
