### ISSUE TITLE
/delivery/api/v1/content/item returns 404 when Start-Item is provided

### ISSUE THREAD

**Issue by cf-marc** [umbraco/Umbraco-CMS#14387]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

12.0.0-rc3

### Bug summary

Hello

When I try to receive an item with the content delivery api call "/umbraco/delivery/api/v1/content/item/de" with the Start-Item in header, I receive a 404 error from the API. If I do the same request without the Start-Item I receive a valid response.

### Steps to reproduce

My initial setup for the content

- root (doctype root)
   - home (doctype home - hostname 'local.test.ch/de' culture 'german (switzerland)')

Send a get request to 'http://local.test.ch/umbraco/delivery/api/v1/content/item/de'
Headers 
- 'Start-Item' - 'path or Guid in my case 'root' or '5574d0fe-7c0a-4574-8857-f74413d9ce49'

### Expected result / actual result

actual result is

```json
{
    "type": "https://tools.ietf.org/html/rfc7231#section-6.5.4",
    "title": "Not Found",
    "status": 404,
    "traceId": "00-49d8b46a4ea20947cc958a3c2491279f-d34080be6d0c7b25-00"
}
```

expected result

```json
{
    "name": "Home",
    "route": {
        "path": "/de",
        "startItem": {
            "id": "5574d0fe-7c0a-4574-8857-f74413d9ce49",
            "path": "root"
        }
    },
    "id": "4bbf0b3e-7cc0-4dfc-8ba6-7d1e22b561aa",
    "contentType": "home",
    "properties": {
        ...
    },
    "cultures": {
        "de-ch": {
            "path": "/de",
            "startItem": {
                "id": "5574d0fe-7c0a-4574-8857-f74413d9ce49",
                "path": "root"
            }
        },
        "fr-ch": {
            "path": "/fr",
            "startItem": {
                "id": "5574d0fe-7c0a-4574-8857-f74413d9ce49",
                "path": "root"
            }
        }
    }
}
```

**Comment by andr317c** [comment]
Hey! 😃 

I'm a bit unsure of what you are trying to do with the Start-Item. As far as I understand you are trying to distinguish between the two languages you have set up. For that, I would use the Accept-Language header to specify which language you want to receive as output.  

Please let me know if I have misunderstood or if you have additional comments 😄

**Comment by cf-marc** [comment]
Hey @andr317c 

Sorry for the delay. In my case, I tested it in an multi site environment. It could be possible that you have two items with the path "/de" but for different sites. But I figured it out that it is possible to call the api with the different hostname of the site without passing the start-item in the header.

http://local.test.ch/ -> site1
http://local.test2.ch -> site2

http://local.test.ch/umbraco/delivery/api/v1/content/item/de
http://local.test2.ch/umbraco/delivery/api/v1/content/item/de
These calls will return the correct item per site, without adding the start-item in header.

Thanks for your help.

**Comment by andr317c** [comment]
Hey!
Sorry for the late response. I'm glad you found a solution that is working for you! Since this was not an issue, I will go ahead and close this😄

**Comment by cf-marc** [comment]
Hey @andr317c 
I apologize if I'm asking again. Currently, I am using Umbraco version 13.0.3. From my perspective, it should always be possible to include the start item with the header. When I send the API call '/umbraco/delivery/api/v1/content/item/{id}' with the start item, I receive a 200 status code. However, when I make the request with '/umbraco/delivery/api/v1/content/item/{path}', I get a 204 error. In my view, this seems a bit inconsistent. In what context can I include the start item with the call '/umbraco/delivery/api/v1/content/item/{path}'?
