### ISSUE TITLE
Is it possible to make Listview Search  by Id or Key ?

### ISSUE THREAD

**Issue by dKumarmj** [umbraco/Umbraco-CMS#14386]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

10.5

### Bug summary

Currently, in the Listview, we can't search an item by id or by key, only working by node name.

In the [code  ](https://github.com/umbraco/Umbraco-CMS/blob/contrib/src/Umbraco.Web.BackOffice/Controllers/ContentController.cs#L779)  it's just a lookup for nodeName, can we include a unique key & id, because in some cases, if we have more content then it's hard to search by its name?

This is very useful if we have lots of data in listview and these attributes [Key, Id] make the item unique, so it's easy to search by key or id!

### Steps to reproduce

https://github.com/umbraco/Umbraco-CMS/assets/58820887/c63b1deb-682b-42c8-a5a4-e28d9a45cb20

### Expected result / actual result

Need to show item by Key or Id.

**Comment by andr317c** [comment]
Hey, it sounds like a question that is perfect to ask on our Discord. Here is a link: https://community.umbraco.com/get-involved/community-discord-channel/

**Comment by dKumarmj** [comment]
@andr317c  as per the code implementation this is expected, but we are able to search by id & key in minilistiview, so the same functionality will also work in the Listview, right?


I think , we need to incorporate that logic in here https://github.com/umbraco/Umbraco-CMS/blob/contrib/src/Umbraco.Web.BackOffice/Controllers/ContentController.cs#L779 

It's very useful right?, if we have a large dataset!
