### ISSUE TITLE
Delivery API: behavior of redirection after renaming Node

### ISSUE THREAD

**Issue by cf-marc** [umbraco/Umbraco-CMS#14413]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

12.0.0-rc3

### Bug summary

If you rename an item in Umbraco e.g. from 'About' to 'About us' and try to get the Item with the old path '/umbraco/delivery/api/v1/content/item/about', you will be redirected to the path '/about-us'.

### Steps to reproduce

1. Create a Node in Umbraco e.g. 'About'
2. Save and publish
3. Rename created Node to 'About Us'
4. Call API with old path '/umbraco/delivery/api/v1/content/item/about'

### Expected result / actual result

Actual response:

<body>

	<section>
		<article>
			<div>
				<h1>Page Not Found</h1>
				<h3>No template exists to render the document at URL &#x27;/about-us&#x27;.</h3>
				<div class="cta"></div>
				<div class="row">
					<div class="col">
						<h2>This page can be replaced</h2>
						<p>
							Custom error handling might make your site look more on-brand and minimize the impact of
							errors on user experience - for example, a custom 404 with some helpful links (or a search
							function) could bring some value to the site.
						</p>

						<a href="https://umbra.co/custom-error-pages" target="_blank" rel="noopener">Implementing custom
							error pages &rarr;</a>
					</div>

					<div class="col">
						<h2>Be a part of the community</h2>
						<p>The Umbraco community is the best of its kind, be sure to visit, and if you have any
							questions, we're sure that you can get your answers from the community.</p>

						<a href="https://our.umbraco.com/" target="_blank" rel="noopener">our.Umbraco &rarr;</a>
					</div>
				</div>
			</div>
		</article>

	</section>

</body>

Expected result:

```json
{
    "name": "About Us",
    "route": {
        "path": "/about-us",
        "startItem": {
            "id": "5574d0fe-7c0a-4574-8857-f74413d9ce49",
            "path": "root"
        }
    },
    "id": "769e2d4c-6366-4db2-b4d4-e8301f56e3c7",
    "contentType": "content",
    "cultures": {
        "de-ch": {
            "path": "/about-us",
            "startItem": {
                "id": "5574d0fe-7c0a-4574-8857-f74413d9ce49",
                "path": "root"
            }
        }
    }
}

```

or at lead a valid json response:
```json
{
    "type": "https://tools.ietf.org/html/rfc7231#section-6.5.4",
    "title": "Not Found",
    "status": 404,
    "traceId": "00-8eb2e90c3c80cd055cca865c48aed1d1-f622785079defc70-00"
}
```

**Comment by kjac** [comment]
Hi @cf-marc 👋 

Thank you for reporting this 👍 

The API _should_ return a valid redirect response, but perhaps something broke. I'll dive into this today and get back to you 😄

**Comment by kjac** [comment]
Ok... I can't reproduce this 🙈 

I have a content item that was renamed from "Delete Me Too" to "Delete Me Too Too Shoo":

![image](https://github.com/umbraco/Umbraco-CMS/assets/7405322/3bf1ffa8-1041-4248-9b1f-f1defd5c142e)

When I request `/umbraco/delivery/api/v1.0/content/item/delete-me-too` I get a HTTP301 Moved Permanently response:

![image](https://github.com/umbraco/Umbraco-CMS/assets/7405322/32b56d66-e248-40f1-9c48-4943ef2273fc)

If you're testing this in Postman or a similar tool, it might be that the tool automatically follows redirects. Postman does so by default; you have to go to Settings to turn that off explicitly:

![image](https://github.com/umbraco/Umbraco-CMS/assets/7405322/8004add8-4a3a-4167-a7e2-ae8fe9a1d5a3)

Alternatively (provided you use Postman) you can open the Postman console and see the HTTP301:

![image](https://github.com/umbraco/Umbraco-CMS/assets/7405322/10576a32-54b7-478e-a4c6-80bdaec6ce26)

Could I ask you to test this again?

**Comment by cf-marc** [comment]
Hey @kjac 

Thanks for the input and sorry for that. I switched off this setting in postman and the response is absolutely fine.

**Comment by thebuilder** [comment]
Okay, it "kinda" makes sense, since it returns the actual URL for the page you requested.

I've set [redirect](https://developer.mozilla.org/en-US/docs/Web/API/Request/redirect) to `manual`, and if i get back a `301`, i perform a page redirect.

```tsx
export default async function Page({ params }: Props) {
  const result = await fetchUmbracoPath(params.slug);

  if (result.response.status === 301) {
    // Content was moved.
    redirect(result.response.headers.get("Location")!);
  }
  ...
}
```
