### ISSUE TITLE
Custom PropertyValueConverter value is cached even if PropertyCacheLevel is set to None

### ISSUE THREAD

**Issue by gregor-tusar-sowa** [umbraco/Umbraco-CMS#14436]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

12.0.0-RC4

### Bug summary

I have a custom `PropertyValueConverter` which has some product IDs saved in database and enriches the model with live prices of those products in `ConvertIntermediateToObject` method. 

When the property is rendered or requested by DeliveryAPI, the `ConvertIntermediateToObject` method is accessed only the first time. After that the property is served from cache. This causes product prices to be outdated.

The `GetPropertyCacheLevel` method is set to return `None`:
```
        public PropertyCacheLevel GetPropertyCacheLevel(IPublishedPropertyType propertyType)
        {
            return PropertyCacheLevel.None;
        }
```

### Steps to reproduce

- create custom `PropertyValueConverter`
- set `GetPropertyCacheLevel` to return `None`
- request page containing this property
- cached property model is returned

### Expected result / actual result

I expect that `ConvertIntermediateToObject` method is called on each request.

**Comment by kjac** [comment]
Hi @gregor-tusar-sowa,

Thank you for reaching out, and thank you so much for testing the new API ❤️ 

Indeed `ConvertIntermediateToObject()` should be called on each request, when the cache level is set to `None`.

I just created a value converter that returns `DateTime.Now.Ticks` and uses cache level `None`. It seems to work as expected in my 12-RC4 project - both when requesting the property through the API and when rendering with Razor:

[14436.webm](https://github.com/umbraco/Umbraco-CMS/assets/7405322/d565d65a-958e-4148-af03-05c94aa2cb96)

Here's the code for my value converter:

```cs
using Umbraco.Cms.Core.Models.PublishedContent;
using Umbraco.Cms.Core.PropertyEditors;

namespace My.Editors;

public class MyEditorValueConverter : PropertyValueConverterBase
{
    public override bool IsConverter(IPublishedPropertyType propertyType)
        => propertyType.EditorAlias.Equals("My.Editor");

    public override Type GetPropertyValueType(IPublishedPropertyType propertyType)
        => typeof(long);

    public override object? ConvertIntermediateToObject(
        IPublishedElement owner,
        IPublishedPropertyType propertyType,
        PropertyCacheLevel referenceCacheLevel,
        object? inter,
        bool preview)
        => DateTime.Now.Ticks;

    public override PropertyCacheLevel GetPropertyCacheLevel(IPublishedPropertyType propertyType)
        => PropertyCacheLevel.None;
}
```

Here is a ZIP with the property editor incl. UI and value converter, if you want to test it: [My.Editor.zip](https://github.com/umbraco/Umbraco-CMS/files/11863918/My.Editor.zip)

I'm going to close this as a non-issue. If you continue to see cached values for cache level `None`, please re-open the issue with additional steps to reproduce 😄

**Comment by kjac** [comment]
Hi @gregor-tusar-sowa,

That sounds reasonable. In this scenario, the Block Grid is _the_ property, and the element properties are "just" parts of the Block Grid property data - thus "inheriting" the Block Grid cache level.

You can't really disable the cache on a specific property.

You _can_ however replace the value converter for the Block Grid with your own custom value converter (see https://docs.umbraco.com/umbraco-cms/extending/property-editors/property-value-converters#registering-propertyvalueconverters).

I do **_not_** recommend using `None` as cache level for Block Grid, as it's quite expensive to render, and your performance will suffer as a result. But if you absolutely must, you can create your own Block Grid value converter by inheriting `BlockGridPropertyValueConverter`. Then you'll need to create a `new` implementation of the relevant cache levels - i.e. when targeting the Delivery API, add `public new PropertyCacheLevel GetDeliveryApiPropertyCacheLevel(IPublishedPropertyType propertyType) => PropertyCacheLevel.None;`
