### ISSUE TITLE
Switching property from Block Grid to Block List cause save errors

### ISSUE THREAD

**Issue by bjarnef** [umbraco/Umbraco-CMS#14433]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

11.4.0

### Bug summary

On a block element I had property "items" using Block Grid, where I added some items. 

![image](https://github.com/umbraco/Umbraco-CMS/assets/2919859/031efd95-fa26-49cd-85c2-75208ef39e5c)

Later I changed the property to a Block List instead and deleted the Block Grid datatype instance.

Now when trying to add items to the property using Block List and save content, it fails.

![chrome_4yquWg2oLc](https://github.com/umbraco/Umbraco-CMS/assets/2919859/98e723ae-514c-4cf7-b5a3-50bddcc183da)

If I renamed the property alias (using Block List) to something else than `items` it does save.
It seems the property with alias `items` somehow still reference the original Block Grid datatype, which was deleted.

### Steps to reproduce

- Add a Block Grid property
- Add a Block with property `items` using another Block Grid datatype instance.
- Add a block to grid content and some items the the grid on this block.
- Remove items from the block.
- Change the block `items` property to Block List instead and delete the "nested" Block Grid datatype.
- Add some items again and save should fail.

---
_This item has been added to our backlog [AB#31584](https://dev.azure.com/umbraco/243e7927-03b2-44e2-908f-d4ac7ea5daaa/_workitems/edit/31584)_

**Comment by bjarnef** [comment]
I also noticed when renaming the "nested" property alias using Block List, the existing items dissapears from UI.

I think it should be allowed to renamed property alias (as with other property editors) without data-loss. At least when not  changing property editor.

**Comment by kjac** [comment]
Hi @bjarnef,

Thank you for reporting 💪 unfortunately I'm having a hard time reproducing the issue on V12.

Here's a screencast of me trying:
- The content type is setup with a grid.
- The content item has two elements in the grid (and is published).
- The new list datatype has the same block type setup (but that shouldn't matter here).

[14433.webm](https://github.com/umbraco/Umbraco-CMS/assets/7405322/31dde0f6-78fa-439e-a53f-8b3099596034)

Does this test mimic the issue scenario you're experiencing on V11?

**Comment by bjarnef** [comment]
Hi @kjac 

Maybe I should elaborate that I didn't replace Block Grid to Block List directly on a property on the content type, but on an element type used in a Block Grid on the content type 😁

![image](https://github.com/umbraco/Umbraco-CMS/assets/2919859/dd44647f-0f4f-4460-8a25-21be40643d8d)

So the switch / replacement on Block Grid to Block List happened on the block element inserted on the Block Grid on the content node 😎

**Comment by kjac** [comment]
Hi again 😄 

...I still can't reproduce it 🙈 

[14433-2.webm](https://github.com/umbraco/Umbraco-CMS/assets/7405322/935cd958-9d80-44ac-bed2-625aa2955371)

**Comment by kjac** [comment]
Hi @bjarnef,

We haven't heard from you in a while on this one, so I'm closing it now. If the problem indeed still persists, please feel free to reopen the issue with additional steps to reproduce.

**Comment by bjarnef** [comment]
Hi @kjac 

I have tested with latest changes in `contrib` branch, but was still able to reproduce the issue when replacing "Items" property using "BG - Assets" with "BL - Assets", delete "BG - Assets" datatype and go back to content section where the "Items" are empty, but hitting save & publish throw an exception, because it somehow reference the "BG - Assets" datatype.

https://github.com/umbraco/Umbraco-CMS/assets/2919859/7f1ab602-4684-4b55-8062-4a4bd2206d5e

**Comment by bjarnef** [comment]
Switching the "items" property to textarea I get the existing stored data:

```
{"layout":{"Umbraco.BlockGrid":[{"contentUdi":"umb://element/c967d3a5395e4e8490f535fe6167df0d","areas":[],"columnSpan":12,"rowSpan":1},{"contentUdi":"umb://element/752978f7b2c446b5b7a77e9cfd927b3c","areas":[],"columnSpan":12,"rowSpan":1},{"contentUdi":"umb://element/1ec7b3bea25f4ec79863dc2c0a642a12","areas":[],"columnSpan":12,"rowSpan":1}]},"contentData":[{"contentTypeKey":"1b415b13-c8a5-4d09-af14-b63a9fc23a04","udi":"umb://element/c967d3a5395e4e8490f535fe6167df0d","title":"Test 1","link":"[{\"name\":\"#\",\"queryString\":\"#\"}]"},{"contentTypeKey":"1b415b13-c8a5-4d09-af14-b63a9fc23a04","udi":"umb://element/752978f7b2c446b5b7a77e9cfd927b3c","title":"Test 2","link":"[{\"name\":\"#\",\"queryString\":\"#\"}]"},{"contentTypeKey":"1b415b13-c8a5-4d09-af14-b63a9fc23a04","udi":"umb://element/1ec7b3bea25f4ec79863dc2c0a642a12","title":"Test 3","link":"[{\"name\":\"#\",\"queryString\":\"#\"}]"}],"settingsData":[]}
```

**Comment by kjac** [comment]
Thank you for the videos @bjarnef 😄 I will make sure we find time to dig into this in an upcoming sprint 👍

**Comment by bjarnef** [comment]
A workaround is to delete the property and add a new property with a different alias.

I also tried creating a new "BG - Asssets" (Block Grid) datatype instance (with a different id). When I went to content section again the items are shown again, because of the Block Grid data structure, but save & publish also seemed to work.
