### ISSUE TITLE
Preview ignores culture

### ISSUE THREAD

**Issue by benOnside** [umbraco/Umbraco-CMS#14440]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

11.4.0

### Bug summary

I am running umbraco self-hosted using SQL Server (I use SSMS to check it), currently only on my local machine before we deploy it for real soon. I have set up 3 cultures: NZ, AU, US. When I publish, they look distinctively different (which I want) but in preview, it always loads the NZ version of the page. I had some redirect code so I have made absolutely certain to remove that and I still always get the NZ version. US is the default language that I have set, and AU is my browser language. If I set no language explicitly, Umbraco.CultureDictionary.Culture.Name is en-NZ, I guess because this is the locale that the server is running on (my laptop windows is set to NZ).

### Specifics

https://localhost:44326/umbraco/preview/?id=1070&culture=en-US

### Steps to reproduce

1. Set up multiple cultures: NZ, US, AU on self-hosted umbraco
2. Make the root page vary by culture
3. Use the same root page document type for each culture, but with different content
4. Make a change to the US site and try to preview it "Save and Preview"

### Expected result / actual result

Expected:
- Views the US site
Actual
- Views the NZ site

**Comment by kjac** [comment]
Hi @benOnside,

Thank you for reaching out 😄 

I'm not quite able to reproduce this.

I have set up a site with a en-US and da-DK.
- Previewing from the backoffice works fine for both culture.
- Switching between cultures within the same preview session works fine too.

I did find a somewhat wonky thing: When switching cultures in a preview session, the `culture` query string parameter retains its original value, while the hash equivalent updates correctly. This yields a quirky looking URL like this: `/umbraco/preview/?id=1062&culture=en-US#?culture=da-DK` ... but the preview does pick up on the correct parameter (the hash one).

Here's a screencast of my test:

[14440.webm](https://github.com/umbraco/Umbraco-CMS/assets/7405322/342ee2d3-b00b-4c6b-9204-7332d443d742)

Could you please re-test on your end? Perhaps you could even try this out on a blank Umbraco site, to make sure there is no custom code interfering with your test?

**Comment by benOnside** [comment]
Hi Kenn, 

I actually can't reproduce it with a template project either. I tried remaking the document type for my home page and somehow that fixed the issue - I tried to make sure that I was copying it exactly but must have missed something. Since I've fixed the issue for myself I can't spare time to look further into the issue, so I'll close it.
