### ISSUE TITLE
Non-existing class referenced in DefaultPropertyValueConverter documentation

### ISSUE THREAD

**Issue by lars-erik** [umbraco/Umbraco-CMS#14458]
## What type of issue is it? (Choose one - delete the others)
Wrong documentation

## What article/section is this about?
[(link here)](https://github.com/umbraco/Umbraco-CMS/blob/fccbed125cebab8604d5832f32c8ee9ea1e12327/src/Umbraco.Core/PropertyEditors/DefaultPropertyValueConverterAttribute.cs#LL19C62-L19C94)

## Describe the issue
I was about to make a quick PR to fix the typo in RelatedLiksEditorValueConverter, but then I realized nor the wrongly or correctly spelled class exists. I'm not sure which it's supposed to be, so I'll just leave it here for someone who knows. 🙈

**Comment by Zeegaan** [comment]
Fixed in https://github.com/umbraco/Umbraco-CMS/pull/14818
