### ISSUE TITLE
Copying block items from newly created content overrides eachother

### ISSUE THREAD

**Issue by nikcio** [umbraco/Umbraco-CMS#14459]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

8.15.0 & 11.4.0

### Bug summary

When creating new content with block lists you can encounter that when trying to copy block list items the items will override each other so that you can only paste the last copied item.

**Note: This might also be the case with block grid. I haven't tested it.**

### Specifics

The error occurs in this piece of code where the first copied selection is overridden by the new one. This happens because `uniqueKey` here always will be `0`.
https://github.com/umbraco/Umbraco-CMS/blob/62f692e617a107c3aa80eee3e8ebea1a027b2c3a/src/Umbraco.Web.UI.Client/src/common/services/clipboard.service.js#L347-L352

### Steps to reproduce

Version 1
1. Create a content type with a block list
2. Create a new document where you add some item to the block list
3. Press the copy function (You now have a copy where the `uniqueKey` is `0`)

![image](https://github.com/umbraco/Umbraco-CMS/assets/24605285/849bd28e-9d29-49f3-b07e-7a5d79044447)
![image](https://github.com/umbraco/Umbraco-CMS/assets/24605285/ca466d7c-e0ff-4d4b-ae2e-336c5a44fcbb)

4. Close the document and discard the changes.
5. Create a new document where you add something else to the block list
6. Press the copy function (You have now overridden the previous copy)

![image](https://github.com/umbraco/Umbraco-CMS/assets/24605285/6ac0c973-6925-48a0-9ab1-ac4f03245533)
![image](https://github.com/umbraco/Umbraco-CMS/assets/24605285/ae309590-ced8-4dd1-924f-6fa26e901c86)

7. Try to paste your selection. You will now only have 1 option instead of the expected 2 you copied.

Version 2:
1. Create a content type with two block lists that can vary by culture (min. 2 languages)
2. Create a new document where you add some items to block list 1 and then copy
3. Add some items to block list 2 and then copy that
4. Switch to the other language and try to paste the values into the block lists. You'll find that you can only paste in one of the fields.

### Expected result / actual result

I expected that you could copy the block list values even when creating the document.

**Comment by kjac** [comment]
Hi @nikcio,

Thanks for reporting 👍 I can reproduce this.

Just to clarify - this does _not_ happen when copying individual blocks, only when copying all blocks using the property action (as illustrated in the original issue description). This also _only_ happens when copying blocks from new, unsaved content.

It should be possible to fix this by testing if `uniqueKey` has a value in the referenced code snippet.

I'm putting this up for grabs if anyone would like to have a crack at it 😄
