### ISSUE TITLE
IDictionaryTranslation.Language deprecated

### ISSUE THREAD

**Issue by bryansoo2503** [umbraco/Umbraco-CMS#14455]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

11.3.1

### Bug summary

Since IDictionaryTranslations.Language is going to be obsolete, I'd like to update my code with the ILanguageService, but I could not find much information about the ILanguageService that we are meant to use.

### Specifics

Currently using .NET 7.0 to develop a translation function for my build. While implementing this feature, I encountered a deprecated warning when I'm querying the ILanguage property of an IEnumerable of IDictionaryTranslations like below:

![deprecated warning](https://github.com/umbraco/Umbraco-CMS/assets/85857506/556de144-51d3-4571-8964-f473305b131d)

The warning says that: "This will be removed in V13. From V13 onwards you should get languages by ISO code from ILanguageService". But the ILanguageService that the warning refers to is ambiguous since there's no documentation on this ILanguageService, so I am not able to update my code to account for this warning.

![idictionary](https://github.com/umbraco/Umbraco-CMS/assets/85857506/5ba56027-3f6b-4e06-bc3f-b2a171774428)

### Steps to reproduce

Going into the IDictionaryTranslation model in Umbraco.Cms.Core.Models:

![idictionary](https://github.com/umbraco/Umbraco-CMS/assets/85857506/32b47f05-400e-4b70-a7d8-e545e9690557)

**During implementation:**

By calling ILocalizationService.GetDictionaryItemByKey(), and then querying the Translations property of the IDictionaryItem to get an IEnumerable of IDictionaryTranslations. Upon applying a LINQ to the Translations to search based on the Language property of the IDictionaryTranslation, a deprecated warning will show when referencing the obsolete properties of the IDictionaryTranslation object.

`

    public Dictionary<string, string?> GetTranslationByKeys(string? cultureCode = null, params string[] keys)
    { 
        if (string.IsNullOrEmpty(cultureCode))
            cultureCode = _localizationService.GetDefaultLanguageIsoCode();
            

        var dictionary = new Dictionary<string, string?>();
        foreach (var key in keys)
        {
            var dictionaryItem = _localizationService.GetDictionaryItemByKey(key);
            if (dictionaryItem != null)
            {

                var translation = dictionaryItem.Translations.FirstOrDefault(x => x.Language!.CultureInfo!.Name == cultureCode); //the culprit in question

                if (translation != null)
                {
                    dictionary.Add(key, translation.Value);
                }
                else
                {
                    dictionary.Add(key, "");
                }
            }
            else
            {
                dictionary.Add(key, "");
            }
        }
        return dictionary;
    }

`

### Expected result / actual result

The expected result is to have access to the ILanguageService that is meant to be used when querying the IDictionaryTranslation's Language property.

**Comment by kjac** [comment]
Hi @bryansoo2503,

Thank you so much for a very detailed report 💪 

This issue has been [raised previously](https://github.com/umbraco/Umbraco-CMS/pull/13753#issuecomment-1599091466). It is a residue deprecation from before we re-targeted the new backoffice for V14.

For the time being, please ignore this warning.

We'll make sure to include the replacement properties (ISO codes) in V12.x or at the very latest V13, so you have a chance to migrate your code, before the language IDs disappear in V14.

I'll cross link this issue report and close it for now. Once again, thank you _very_ much for putting in such detail ❤️
