### ISSUE TITLE
[v10+] Linux : Inconsistent ordering of package manifest resource loading

### ISSUE THREAD

**Issue by mattbrailsford** [umbraco/Umbraco-CMS#14462]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

10.5.1

### Bug summary

A customer reported a Vendr bug here https://github.com/vendrhub/vendr-checkout/issues/39 but it turns out it boils down to the way manifest files are loaded / JS resources loaded in the back office.

Essentially Vendr Checkout is designed to run after Vendr and this is how it works on Windows, but on Linux Vendr Checkout was loading it's scripts first and thus throwing an error.

### Specifics

Fundamentally it boils down to the `IManifestParser.GetManifestFiles` method which calls `Directory.GetFiles(_path, "package.manifest", SearchOption.AllDirectories);` to load all manifests. The order of this list is what dictates the order in which manifests assets are loaded in the back office. The issue being `GetFiles` does not give a guaranteed order and so on Linux it was loading Vendr Checkout first.

For consistency across platforms we should update `GetManifestFiles` and sort the paths returned from `GetFiles` before returning them. This ensures consistency over the order in which assets are loaded.

### Steps to reproduce

See steps in this issue https://github.com/vendrhub/vendr-checkout/issues/39

### Expected result / actual result

We expected Vendr Checkout to load it's scripts after Vendr

**Comment by kjac** [comment]
Hi @mattbrailsford 👋 makes good sense to me. And thank you for the PR ❤️
