### ISSUE TITLE
Search By Key Or ID is not working in ListView

### ISSUE THREAD

**Issue by dKumarmj** [umbraco/Umbraco-CMS#14468]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

10.5.1

### Bug summary

Currently, in the Listview, we can't search an item by id or by key, only working by node name.

But in the MiniListview, we can search by Key or Id.

This is very useful if we have lots of data in listview and these attributes [Key, Id] make the item unique, so it's easy to search by key or id!

See here : - 

https://github.com/umbraco/Umbraco-CMS/assets/58820887/68cdb232-0e80-4276-8de5-1e154b506c1e

### Steps to reproduce

https://github.com/umbraco/Umbraco-CMS/assets/58820887/e3a221ee-c692-40d4-b986-9cee9ed77081

### Expected result / actual result

Expected: Search By ID/Key needs to work as it's working in MiniListView
Actual: Not working in ListView

**Comment by kjac** [comment]
Hi @dKumarmj,

Thanks for reporting this 😄 I can confirm this is how the listview currently works. 

It makes good sense to add ID and key search capabilities to the listviews. I'm going to make this up for grabs, if someone wants to add that feature.

For anyone picking this up, please ensure that ID and key search works for both content and media list views (ideally also for members list views, but members do behave a bit differently).

The implementation is likely similar for content and media, but from my brief glance through the codebase it needs to be implemented separately for content and media in `ContentController.GetChildren(...)` and `MediaController.GetChildren(...)` respectively. 

Look to `EntityController.GetPagedChildren(...)` for inspiration on building the queries. This is the controller action that powers the mini listview (among other things).

**Comment by nul800sebastiaan** [comment]
PR https://github.com/umbraco/Umbraco-CMS/pull/14514 fixed this for the `ContentController` so now there's only the `MediaController` left to update.

**Comment by erikjanwestendorp** [comment]
@nul800sebastiaan I created a PR to update the `MediaController`  but I'm curious, is this something what you want for Members as well?

**Comment by dKumarmj** [comment]
Thanks @erikjanwestendorp   for the PR. I was little bit busy with couple of projects.


> For anyone picking this up, please ensure that ID and key search works for both content and media list views (ideally also for members list views, but members do behave a bit differently).

@erikjanwestendorp  yes, I think we need to implement the same behavior for the member view as @kjac  mentioned in the comment.

**Comment by nul800sebastiaan** [comment]
Oh yeah, didn't think of Members but would be great as well indeed!
