### ISSUE TITLE
Format querystring on SVG fails

### ISSUE THREAD

**Issue by bjarnef** [umbraco/Umbraco-CMS#14467]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

11.4.1

### Bug summary

Not sure if this is an issue in implementation on ImageSharp in Umbraco or in ImageSharp itself.

However I noticed some images which was broken using `GetCropUrl()` and `format` parameter.

E.g. the following, but only when image was an SVG file/image.
```
<picture>
    <source media="(min-width: 0px)" srcset="@image.GetCropUrl(0, 500, imageCropMode: ImageCropMode.Crop, furtherOptions: "&format=webp")">
    <source media="(min-width: 0px)" srcset="@image.GetCropUrl(0, 500, imageCropMode: ImageCropMode.Crop)">
    <img src="@image.GetCropUrl(0, 500, imageCropMode: ImageCropMode.Crop)" loading="lazy" alt="@image.GetAltText()" class="img-fluid d-block" style="object-fit:cover; width:100%; height:100%;" />
</picture>
```

But we don't need querystring, when image in a SVG though, so instead we have this:

```
@if (image.IsSVG())
{
    <img src="@image.MediaUrl()" loading="lazy" alt="@image.GetAltText()" class="img-fluid d-block" style="object-fit:cover; width:100%; height:100%;" />
}
else
{
    <picture>
        <source media="(min-width: 0px)" srcset="@image.GetCropUrl(0, 500, imageCropMode: ImageCropMode.Crop, furtherOptions: "&format=webp")">
        <source media="(min-width: 0px)" srcset="@image.GetCropUrl(0, 500, imageCropMode: ImageCropMode.Crop)">
        <img src="@image.GetCropUrl(0, 500, imageCropMode: ImageCropMode.Crop)" loading="lazy" alt="@image.GetAltText()" class="img-fluid d-block" style="object-fit:cover; width:100%; height:100%;" />
    </picture>
}
```

This generated URL is something like this:
`/media/pt2eqb2g/logo.svg?format=webp`

However I checked the same in a project on Umbraco 8, where it is just ignored and still render the image.

### Steps to reproduce

Add `format=jpg`, `format=png` or `format=webp` to any SVG file.

**Comment by kjac** [comment]
Hi there @bjarnef 👋 

ImageSharp does not support SVGs (see the [docs](https://docs.sixlabors.com/articles/imagesharp/imageformats.html)) out of the box. I believe there is an experimental project going on, but to my knowledge it is just that - experimental.

V8 uses [ImageProcessor](https://imageprocessor.org/) which may have a more graceful handling for unsupported formats than ImageSharp does.

If you try requesting a SVG as PNG locally (in development mode), you'll hopefully see something like this:

![image](https://github.com/umbraco/Umbraco-CMS/assets/7405322/ec73d679-9475-4c25-99b8-13042a7899f7)

**Comment by bjarnef** [comment]
Hi @kjac 
Okay, but should `GetCropUrl()` handle this instead if selected media is a SVG?

Even though upload of SVG to media section by default create media item using "Vector Graphics (SVG)" media type, it is still possible to upload SVG on a media item using "Image" media type.

So maybe `GetCropUrl()` shouldn't apply querystring on extensions not supported by ImageSharp?
