### ISSUE TITLE
App_Plugins folder not being created when installing new Nuget Packages

### ISSUE THREAD

**Issue by deanleigh** [umbraco/Umbraco-CMS#14487]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

Umbraco CMS 10.5.1

### Bug summary

App_Plugins folder not being created when installing new Nuget Packages
When installing using Visual Studio Nuget Package Manager

### Steps to reproduce

Install Nuget Package
App_Plugins folder not being created 
You can create it manually and build and then the package folder appears

**Comment by abjerner** [comment]
Hi @deanleigh 

Any specific packages that you're installing? I think most packages for Umbraco 10 and above are now Razor Class Libraries. When you install them locally in Visual Studio, their assets won't appear on disk and as such there will not be an `/App_Plugins/` folder like in the old days.

But if you do a `dotnet publish` or similar, there will be an `/App_Plugins/` with the assets.

**Comment by deanleigh** [comment]
I tried Contentment and Block Preview, both were not creating the folders. I then tried our own package Wholething text fall back editor which I know for sure is not an RCL. This also did not create the folders.

I then manually created the folder for app plugins and then excluded it from the project then ran build and all of the packages folders were created.

**Comment by abjerner** [comment]
I tried testing this a bit more.

Using `dotnet` it works like intended. Installing Contentment it self won't add the files, but they will be when running `dotnet run`:

```
# Ensure we have the latest Umbraco templates
dotnet new -i Umbraco.Templates::10.5.1

# Create solution/project
dotnet new sln --name "MySolution"
dotnet new umbraco --force -n "MyProject"
dotnet sln add "MyProject"

#Add Packages
dotnet add "MyProject" package Our.Umbraco.Community.Contentment

dotnet run --project "MyProject"
#Running
```

If I use the first part to install Umbraco, and then do the rest from Visual Studio, it also works fine after building the site:

```
# Ensure we have the latest Umbraco templates
dotnet new -i Umbraco.Templates::10.5.1

# Create solution/project
dotnet new sln --name "MySolution"
dotnet new umbraco --force -n "MyProject"
dotnet sln add "MyProject"
#Run
```

Install the package:

```
Install-Package Our.Umbraco.Community.Contentment
Restoring packages for D:\Testing\MyProject\MyProject.csproj...
Installing NuGet package Our.Umbraco.Community.Contentment 4.4.4.
Generating MSBuild file D:\Testing\MyProject\obj\MyProject.csproj.nuget.g.targets.
Writing assets file to disk. Path: D:\Testing\MyProject\obj\project.assets.json
Restored D:\Testing\MyProject\MyProject.csproj (in 599 ms).
Successfully installed 'Our.Umbraco.Community.Contentment 4.4.4' to MyProject
Successfully installed 'Our.Umbraco.Community.Contentment.Core 4.4.4' to MyProject
Executing nuget actions took 826 ms
Time Elapsed: 00:00:02.2928797
```

and first build:

```
Build started...
1>------ Build started: Project: MyProject, Configuration: Debug Any CPU ------
1>MyProject -> D:\Testing\MyProject\bin\Debug\net6.0\MyProject.dll
1>Copying appsettings.json schema file
1>Copying Contentment package files: C:\Users\abjerner\.nuget\packages\our.umbraco.community.contentment\4.4.4\buildTransitive\..\content\App_Plugins\Contentment\**\*.* - #65 files
========== Build: 1 succeeded, 0 failed, 0 up-to-date, 0 skipped ==========
========== Elapsed 00:06,076 ==========
```

After this, the `App_Plugins` folder exist in the project.

Do the files still not show up af a successful build in your case?

**Comment by deanleigh** [comment]
Thanks for looking into this @abjerner 
I will try on another machine when I have time but yes the App_Plugins folder is not getting created at all with either Contentment, Usync or Block Preview.
I will try again with Wholething Text Fallback which I know is not an RCL as we made it.
Again I can confirm that if I manually create the package and then build the installed packages then appear in the App_Plugins folder that I have created.

**Comment by elit0451** [comment]
Thank you for reaching out @deanleigh and thank you for investigating @abjerner 💪 

I have also tried installing **Our.Umbraco.Community.Contentment** package on a fresh Umbraco 10.5.1 using Visual Studio 2022's Nuget Package Manager and I can confirm that the `App_Plugins` folder gets added automatically when building the project. I get the same output as shown in the [comment above](https://github.com/umbraco/Umbraco-CMS/issues/14487#issuecomment-1614673102).

Not sure why you are not seeing the same behaviour @deanleigh 🤷‍♀️ Did you have time to try on another machine?

**Comment by deanleigh** [comment]
I will try again on another machine as you suggest

**Comment by kjac** [comment]
Hi everyone.

This issue seems to have gone stale. I'm going to close it now. If the issue persists, please feel free to re-open with additional steps to reproduce.
