### ISSUE TITLE
List Views aren't included in the data type references

### ISSUE THREAD

**Issue by emmagarland** [umbraco/Umbraco-CMS#14485]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

10.5.1

### Bug summary

List Views aren't included in the "References" section in the list view's Data Type Info section. This could mean someone accidentally deletes a list view thinking it isn't used. 

### Specifics

This is likely an implementation detail that is across all instances. 

### Steps to reproduce

1. Use a list view on a doctype
2. Navigate to the "Info" tab of that list view
3. The doctype isn't listed as a Reference

This image shows the list view doesn't list any doctypes as references:

![List view](https://github.com/umbraco/Umbraco-CMS/assets/1649855/ed6ca796-7151-4c2a-9390-93d9680fdd63)

However, it is used on a doctype:

![image](https://github.com/umbraco/Umbraco-CMS/assets/1649855/ad22bdf0-d131-47be-b4c5-feb3d1b0f8a2)

### Expected result / actual result

As a user, I would expect to be informed that the list view is in use as a reference on a doctype, so that I don't accidentally delete it

**Comment by elit0451** [comment]
Hey @emmagarland 👋 

Thanks for reaching out!
It seems like the relations between List View data types and document types are missing when a List View is configured through the "List view" app on a document type (_also shown in your example_):



<img width="1144" alt="ListViewApp" src="https://github.com/umbraco/Umbraco-CMS/assets/21998037/88d16583-0cc7-4cbc-b961-1ab002ba2edb">

<br>
<br>

I tried adding the same List View as a property on a different document type, and then the property reference shows up:<br>
<img width="1143" alt="ListViewProp" src="https://github.com/umbraco/Umbraco-CMS/assets/21998037/689b6879-a8a8-4993-beba-e2e880211994">

<img width="1150" alt="ListViewReference" src="https://github.com/umbraco/Umbraco-CMS/assets/21998037/103fc642-8571-4ccd-9e7c-92f32715cb42">


<br>
<br>
We only get a single reference, while there should be 2 - from Products and Content page doc types. So, you are right, we need to consider the Data type references when List Views are set through the "List view" app on a document type. <br><br>

I will mark this as up for grabs as we would like some help fixing this issue 🙂

**Comment by ustadstar** [comment]
I am working on this
