### ISSUE TITLE
`umbracoUrlName` not working when varying by culture with only one language

### ISSUE THREAD

**Issue by rickbutterfield** [umbraco/Umbraco-CMS#14489]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

12.0.0

### Bug summary

_Not entirely sure if this is a bug but it's definitely a regression from v11 -> v12!_

Enabling 'Allow vary by culture' on a document type whilst only having one language configured in the back office stops `umbracoUrlName` from working. Whilst this may be intended as you need to define multiple languages for varying by culture, I would have expected it to simply pull from the default language.

### Steps to reproduce

- Create a new blank v12 site
- Add a 'Home' doctype, allowed at root
- Add a 'Content' doctype, with a single 'textstring' property for `umbracoUrlName`
- Create a Home node
- Create a child Content node, and set `umbracoUrlName` to a value that differs to the page name
- Save and Publish, then confirm on the Info tab that `umbracoUrlName` has taken effect
- Edit the 'Content' doctype and turn 'Allow vary by culture' on, and confirm that there is only one language present within the site
- Go back to your Content page and change the `umbracoUrlName` property
- Save and Publish, then check the Info tab. The `umbracoUrlName` won't have taken effect

### Expected result / actual result

Expected:
Even with only one language in the site, the `umbracoUrlName` value should be saved against that culture and used to populate the UrlSegment.

Actual:
The `umbracoUrlName` isn't used to generate the UrlSegment.

This was previously working on a v11 site, but I can see why it potentially shouldn't have been working this way before as you haven't set multiple languages.

**Comment by andr317c** [comment]
Hey! 😄 

Thanks for posting this issue! I just took a at look your issue. And the behavior is acting as expected. For the UrlSegment to be updated when you update the umbracoUrlName, you will need to enable VaryByCulture on the property and not only the DocumentType. Otherwise, the umbracoUrlName value would be the same for all languages. Which would result in conflicting UrlSegments across languages for the ContentNode.

Please write a comment if you have any questions 😃

**Comment by rickbutterfield** [comment]
Got it! Thought that might be the case, looks like the bug was in v11 as this worked without varying the property, so the v12 functionality is working as intended. Thank you for confirming @andr317c!
