### ISSUE TITLE
"Select media type" prompt doesn't take effect when dragging and dropping a file that matches several media types

### ISSUE THREAD

**Issue by elit0451** [umbraco/Umbraco-CMS#14507]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

10.5.1

### Bug summary

The "Select media type" prompt doesn't take effect when 2 or more media types match the uploaded file's type.

<img width="813" alt="image" src="https://github.com/umbraco/Umbraco-CMS/assets/21998037/08806263-32b2-4f79-9233-46e8df1c1798">

<br>
<br>

Neither the "Auto pick" functionality works nor selecting a specific media type.

<br>

In the case of an image - the image will be uploaded after dragging and dropping it in the Upload area without taking into account the result from the "Select media type" prompt. The file will be of type "Image".

### Specifics

The `PostAddFile` action is invoked on the server immediately after dragging and dropping a media file in the Upload area of the Media section with the default or first selected Media type that satisfies the file format. This call should wait for the "Select media type" prompt result.

### Steps to reproduce

- In the Settings section > Media Trees - copy the **Image** media type and rename it to "**Custom image**"
  - Refreshing the Media Types tree is necessary
- Go to the **Folder** media type >  Permissions - add the **Custom image** media type as part of the _Allowed child node types_
- Go to the Media section
- Create a new media item of type **Folder**
- Using the drag-and-drop area - drop an image
- The image will be uploaded immediately (`PostAddFile` call will be made to the server)
- "Select media type" prompt doesn't allow you to click anything and you would have to close it, to find out that the image has been uploaded with the default **Image** media type

### Expected result / actual result

**Expected**: the `PostAddFile` call to the server is blocked until you select the media type that you prefer from the "Select media type" prompt.
**Actual**: the "Select media type" prompt doesn't do anything and the media file is uploaded immediately with an autoselected type.

**Comment by iOvergaard** [comment]
This is fixed in V11 and onwards.
