### ISSUE TITLE
Infinite connection to /umbraco/previewhub

### ISSUE THREAD

**Issue by sebastian-eksponent** [umbraco/Umbraco-CMS#14509]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

10.4.0

### Bug summary

We've observed that on one of our Umbraco 10 instances there's abnormal outgoing bandwith usage even with little to none incoming.
We believe this is cause by a infinite connection to `/umbraco/previewhub`

### Specifics

What are we running:

- Standard Umbraco CMS
- Hosted on Azure using the Azure VM images (Windows Server 2022)
- Running in IIS 10, Not managed, Integrated Pipeline
- One site
- No loadbalancer
- 4 Cores, 16 GB RAM
- S2 Azure SQL

Comparing environments, one thing stand out, which is a long running call to `/umbraco/previewhub` as seen on the image bellow.
![image](https://github.com/umbraco/Umbraco-CMS/assets/85179621/60075396-aa76-4abc-a85e-0960105a6d14)

The suspicion that this is the cause is backed by our usage metrics which clearly shows that with each IIS Recycle the usage drops.
See the image below, that shows our scheduled recycles each night at 3 AM over a period of 7 days.
<img width="1166" alt="image" src="https://github.com/umbraco/Umbraco-CMS/assets/85179621/34e2fdbc-1671-4749-a466-73748271cc32">

We've gone through the version comparer:
https://our.umbraco.com/download/releases/compare?from=10.4.0&to=10.5.1
Along with the info about V10.5.0:
https://our.umbraco.com/download/releases/1050
However, we can't find any note about issues with the PreviewHub, which is why we have yet to upgrade.

As mentioned previously, we have only observed this issue on 1 production instance, test and our other solutions does not have this issue.
The website in IIS has been configured with relatively default settings, only changing the URL Segment.
<img width="406" alt="image" src="https://github.com/umbraco/Umbraco-CMS/assets/85179621/1ef79803-d302-4dee-bcde-549cd84100ad">

Upgrading Umbraco is not out of the picture but is a rather long process involving multiple parties.
So feedback or ideas beside upgrading is appreciated.

### Steps to reproduce

We were not able to reproduce this behaviour on other solution.

### Expected result / actual result

Expected result:
All connections should be terminated gracefully within a reasonable timeframe.

Actual result:
Connections live forever or until the App Pool is Recycled.

**Comment by elit0451** [comment]
Thanks for reaching out @sebastian-eksponent 🙂 

Unfortunately, without anything concrete for us to reproduce, our actions are limited.. But I will try asking around and get back to you next week.

**Comment by sebastian-eksponent** [comment]
Hey @elit0451 🙂

Thanks for the quick response!

We've done some further testing and observed that the issue is present on multiple devices.
As of now we still haven't found a reliable way to recreate this issue.
Our testing shows that when initiating a preview in Umbraco the connection is opened.
However, the devices in our organisation correctly realeases the connection when the devices is put to sleep, rebooted or closes the window.

One theory is that some firewall rules are preventing the SignalR connection from properly closing.
Another is that some devices are left on, with preview and somehow are not timed out or unable to communicate a release of the connection to the Umbraco server.

Can you, or someone else, maybe shine some light on what determines when the connection should be closed or timed out?
We were looking for options in the appsettings which could be used to controll this, but it seems that no such options are exposed via the appsettings.

Another observation we made is that after a recent deployment the number of connections rose from 1 to 3.

**Comment by elit0451** [comment]
Hi again,

I've spoken to a few of my colleagues and we all agree that without a way for us to reproduce the issue, there isn't much we can do. The connection stays open as long as the JS file is running and the preview tab is open..
We don't see any changes related to this when we compare our release tags.

And to confirm, there is no possibility to manipulate the SignalR connection through configuration.
I am going to close this issue for now but feel free to reopen it if you come up with some reproduction steps 🙂
