### ISSUE TITLE
Important messages should not quickly disappear

### ISSUE THREAD

**Issue by plannero** [umbraco/Umbraco-CMS#14522]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

10.4.0

### Bug summary

When successfully saving, a "check" symbol replaces the save button's text for a short while. This is very nice if you notice it. But not all people are able to.

### Specifics

Confirmation after saving new sort order is shown for a short while by a check mark on the save button. However, this confirmation is not pronounced by a screen reader, and it disappears after just a few seconds, so people who are using magnification software may never see it, and even people who see the entire screen may remain unaware because of the message being visible for so short a time. 

An aria-live announcement would be nice for screen reader users, and for others it would be nice if the confirmation remained longer. Since it IS possible to verify what the current sort order is (eg by looking at the site) I would not say this is a very serious bug, but still an area for improvement. 
<img width="243" alt="check-moved" src="https://github.com/umbraco/Umbraco-CMS/assets/2157085/b6eb577b-f786-4c53-8b2b-0c86a6d2cc03">

### Steps to reproduce

Change sort order for a node. Save.

### Expected result / actual result

Confirmation being announced by screen reader and not disappearing too quickly.

**Comment by andr317c** [comment]
Hey,

Thanks for taking the time to post this issue. This is something we would like help with. I will mark the issue as up for grabs!

**Comment by nul800sebastiaan** [comment]
As guidance: I think the aria-live announcement is a good idea, but having the notification stay on screen for longer can hinder people when they want to do another operation, they will need to wait for the additional timeout. As far as I remember, there is a spinner and then a checkmark when the operation is finished so it is fine to block people from doing more operations while the current one is running but it would be frustrating to block them for any longer than that.

**Comment by glombek** [comment]
Working on this

**Comment by glombek** [comment]
Looking into this, the way other save success messages are communicated to the user is via notifications (which do correctly use `aria-live`. I suspect the most consistent way to fix this would be to make the sort function also trigger a notification, rather than adding an additional notification to the button.

Do we also need to announce the loading spinner-type behavior? This would likely need to be in the button itself, however.

I'm going to have to leave this issue for now, so someone else is free to pick this up. But HQ guidance on the above would be appreciated @nul800sebastiaan.

**Comment by nielslyngsoe** [comment]
This up-for-grabs issue have been stale for more than a year now. If you find interest in fixing this feel free to do so. But until then I will close of the issue.
