### ISSUE TITLE
Return focus when closing dialog

### ISSUE THREAD

**Issue by plannero** [umbraco/Umbraco-CMS#14523]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

10.4.0

### Bug summary

When closing a dialogue, focus should return to a logical position. This is especially important when using a screen reader.

### Specifics

If I select “Close” when in the "sort sub pages" dialogue, I’d like for focus to return to the page node in the content tree, or perhaps to the edit menu that opened the sorting dialogue (but that menu is no longer open). Instead, focus is still in the position of the now closed sorting dialogue, from where navigation back to the node can take quite some time and effort if you do not see.

Sort dialog with close button:
<img width="605" alt="sort dialog with close button" src="https://github.com/umbraco/Umbraco-CMS/assets/2157085/7b7a4b43-4834-4f94-a741-d47438f67515">

Position of focus after close:
<img width="587" alt="position of focus after close" src="https://github.com/umbraco/Umbraco-CMS/assets/2157085/51cb0021-05c7-4484-aed4-32a80e2847fe">

### Steps to reproduce

Use a screen reader. Go to the Sort... dialogue for a page node, as if you wanted to re-order the sub-nodes. But change your mind and press close. Then try to get back to the node. This can take a lot of time and energy.

### Expected result / actual result

Focus returned to the node in the content tree would make it easier for the user to continue where they were.

**Comment by elit0451** [comment]
Thank you for raising this concern @plannero 🙌 

I will mark this as up for grabs in case you or anyone else wants to help us fix this. 🙂
