### ISSUE TITLE
Notification state is lost when use "Publish with descendants"

### ISSUE THREAD

**Issue by PeterKvayt** [umbraco/Umbraco-CMS#14543]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

11.3.1

### Bug summary

I have two notification handlers: Published and Publishing. In Publishing I set notification state and in Published I use that state.
When I try to publish through "Save and publish" unpublished content I set notification state in Publishing notification and get it in Published notificaiton as expected. But when I try to publish through "Publish with descendants" unpublished content I set notification state in Publishing notification but I get empty state for Published notificaiton.

### Specifics

I tested it with async content notification handlers

### Steps to reproduce

1. Fresh umbraco 11.3.1 (default setup, telemetry minimal)
2. Create document type (Foo) with template
3. Register two notification handlers:
```c#
public class Published : INotificationAsyncHandler<ContentPublishedNotification>
{
  public Task HandleAsync(ContentPublishedNotification notification, CancellationToken cancellationToken)
  {
      notification.State.TryGetValue("test", out var value);

      return Task.CompletedTask;
  }
}
public class Publishing : INotificationAsyncHandler<ContentPublishingNotification>
{
    public Task HandleAsync(ContentPublishingNotification notification, CancellationToken cancellationToken)
    {
        notification.State.Add("test", notification.PublishedEntities.Select(x => x.Id).ToList());

        return Task.CompletedTask;
    }
}

// Starttup.cs
public void ConfigureServices(IServiceCollection services)
        {
            services.AddUmbraco(_env, _config)
                .AddBackOffice()
                .AddWebsite()
                .AddComposers()
                .AddNotificationAsyncHandler<ContentPublishingNotification, Publishing>()
                .AddNotificationAsyncHandler<ContentPublishedNotification, Published>()
                .Build();
        }
```
4. Create document "Test" in content tab (use "Foo" document type). Click "Save and publish".
5. Refresh page
6. Unpublish "Test" page.
7. Set breakpoints in handlers classes
8. Click "Publish with descendants"
9. In "Publishing" handler state is setted as expected
10. In "Published" handler state is `null`

### Expected result / actual result

Expected: state from Published was the same as in Publishing when triggered by "Publish with descendants".

Actual: state in Publishing is null when triggered by "Publish with descendants".

---
_This item has been added to our backlog [AB#31344](https://dev.azure.com/umbraco/243e7927-03b2-44e2-908f-d4ac7ea5daaa/_workitems/edit/31344)_

**Comment by andr317c** [comment]
Hey!

Thanks a lot for posting this issue and for the clear reproduction steps💪. I was able to reproduce it on v11.3.1 and v12.0.1.

I will go ahead and mark this issue as a sprint candidate!

**Comment by Migaroez** [comment]
Hey @PeterKvayt as you can see we have created a fix for this issue and are going trough the process of validating it. Would be awesome if you could test the fix as well and give us your feedback.

**Comment by Zeegaan** [comment]
Fixed in https://github.com/umbraco/Umbraco-CMS/pull/14763 🚀
