### ISSUE TITLE
Recursive function call breaks saving using Algolia Integration

### ISSUE THREAD

**Issue by rspencer-aimwa** [umbraco/Umbraco-CMS#14556]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

10.6.1

### Bug summary

As I have posted here: https://github.com/umbraco/Umbraco.Cms.Integrations/issues/119
In `Umbraco.Cms.Integrations` for `Umbraco.Cms.Integrations.Search.Algolia`

In the update to `Umbraco.Cms` version `10.6.0`
an Issue was introduced that has stopped us from being able to save any content items that are part of an Algolia index, or rebuild the Algolia index manually within Umbraco settings

As I found more recently, the issue seems to originate from `Umbraco.Cms`
And I wanted to post it here too, as it may cause issues for other things too

### Specifics

As posted in the other issue, I believe this is causing the issue:
https://github.com/umbraco/Umbraco-CMS/commit/6bcec26db3701999b502528a40c8eee17a806549#diff-d3af2728c87f1e8b06fcce301da39381569b9b773d1ee52e550cc261001374f0

`GetIndexValues` in `RichTextPropertyEditor.cs` seems to be recursively calling itself

### Steps to reproduce

- Web Project with:
  - `Umbraco.Cms` version `10.6.0` or greater
  - `Umbraco.Cms.Integrations.Search.Algolia` (tested using versions `1.3.2`, `1.3.3`, and `1.4.0`)
- Create content (may require RichContent)
- Navigate to Settings -> Algolia Search Management
- Add New Index Definition
- Select Document type used for content
- Save content item, or build Index (image below)
![image](https://github.com/umbraco/Umbraco-CMS/assets/134269042/eb525e8c-34d3-4695-8072-ec594c1ca078)

Umbraco PostSave/BuildIndex request will timeout and/or crash the application pool

### Expected result / actual result

The content should save, and the Algolia index should be rebuilt

---
_This item has been added to our backlog [AB#31396](https://dev.azure.com/umbraco/243e7927-03b2-44e2-908f-d4ac7ea5daaa/_workitems/edit/31396)_

**Comment by Zeegaan** [comment]
Thanks for reporting 🐛 
I can certainly reproduce this! Marking this as sprint-candidate, as we need to have a look at this regression 🧐

**Comment by kjac** [comment]
Oh my. This issue was resolved all the way back in July 24 😄 I'll go ahead and close it.
