### ISSUE TITLE
Possible context conflict between SurfaceController and Error404Collection in appsettings.json

### ISSUE THREAD

**Issue by jakob-bagterp** [umbraco/Umbraco-CMS#14569]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

12.0.1 (also observed in 11.x and 12.x)

### Bug summary

When trying to use a [SurfaceController](https://docs.umbraco.com/umbraco-cms/reference/routing/surface-controllers) in combination with a search page and the [Error404Collection](https://docs.umbraco.com/umbraco-cms/reference/configuration/contentsettings#error-404-collection) parameter defined in appsettings.json, this may cause the CurrentPage of the SurfaceController context to route to a 404 error page and not, as intended, stay on the search page.

This is temporarily fixed by either unpublishing the error page or removing the Error404Collection from appsettings.json, and so I suspect a conflict in how Umbraco handles the context.

### Steps to reproduce

Let's imagine a simple search page based on search page template and a `SurfaceController` to handle the form request.

<img width="373" alt="Screenshot 2023-07-17 at 18 57 39" src="https://github.com/umbraco/Umbraco-CMS/assets/25110864/e7666328-32da-4e5e-9ae0-d490228b0bc8">

If we try to type for any text and click the search button...

<img width="403" alt="Screenshot 2023-07-17 at 19 00 55" src="https://github.com/umbraco/Umbraco-CMS/assets/25110864/cb70e3b3-9b57-48df-9ffb-65a379659466">

... then you're redirected to an error page:

<img width="505" alt="Screenshot 2023-07-17 at 19 00 39" src="https://github.com/umbraco/Umbraco-CMS/assets/25110864/e6c48c75-6e60-476e-bffa-451cb7b03222">

If we either A) unpublish the error page or B) remove the Error404Collection parameter from appsettings.json...

```json
...
"Error404Collection": [
    {
        "Culture": "default",
        "ContentXPath": "//errorPage404"
    }
]
...
```

... and attempt the same search, the search results view is correctly given without redirection to another page: 

<img width="410" alt="Screenshot 2023-07-17 at 19 02 43" src="https://github.com/umbraco/Umbraco-CMS/assets/25110864/0b6f6411-04b4-48a8-b93d-a045df67b5f0">

### Expected result / actual result

The `SurfaceController` shouldn't pick up the error page – it can also be viewed by the CurrentPage local variable when debugging – but instead keep the current route `/search` as its context.

**Comment by Zeegaan** [comment]
@jakob-bagterp Could you send the search page template, and surface controller you're using for this example ? 🤞

**Comment by jakob-bagterp** [comment]
Thanks, @Zeegaan. My issue appears in private repository so allow me to try to recreate this in a clean project (eventually I may figure out what the cause is along the way). I'll revert soon.

**Comment by nielslyngsoe** [comment]
Hi @jakob-bagterp any news on this issue — did you discover the problem?

As this issue haven't had any activity for over a year, I will politely close it. But if you still find the issue relevant please let me know and re-open. Then we will have a closer look, but again we need more details to how to reproduce and thereby discover the actual problem.

Thanks for the understanding
