### ISSUE TITLE
Empty DocType folders hidden

### ISSUE THREAD

**Issue by craigs100** [umbraco/Umbraco-CMS#14565]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

10.6.1

### Bug summary

Empty DocType folders are hidden after restart.

### Specifics

Brand new installation. Prepping for development, created empty docType folders for Compositions, Elements & Pages.  Shutdown site. Restarted site, returned to Settings > Document Types to find it empty.  Unable to create a folder for Pages as get red error: "A container with the same name already exists."

Right-clicking on Document Types and selecting "Reload" shows the previously saved, but hidden, folders.

### Steps to reproduce

Brand new installation. Prepping for development, created empty docType folders for Compositions, Elements & Pages.  Shutdown site. Restarted site, returned to Settings > Document Types to find it empty.  Unable to create a folder for Pages as get red error: "A container with the same name already exists."

Right-clicking on Document Types and selecting "Reload" shows the previously saved, but hidden, folders.

### Expected result / actual result

Expected that once Document Types had anything under it then there would be the usual arrow indicator to the left of it.

Actually, there is no indicator if there are only empty folders beneath it.

**Comment by Zeegaan** [comment]
I can definitely reproduce this one, weird one! 🤷

**Comment by xrasod** [comment]
Seems current treecontroller implementation only checks if there are contentTypes (document types) saved, which then sets the hasChildren flag to false (The actual fetching occurs later when the 'Document Types' is expanded, which you would be unable to get to if the 'hasChildren' was false). I've submitted a PR here that should make sure that the hasChildren is set to true even if there are only entityContainers (folders) created.
