### ISSUE TITLE
V11.4.2 reports itself as V12.0.0

### ISSUE THREAD

**Issue by craigs100** [umbraco/Umbraco-CMS#14562]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

11.4.2

### Bug summary

Installed a fresh copy of Umbraco V11.4.2 into a new folder. Ran the empty site and logged into the back office.  Clicked on the U (Umbraco Info) icon to reveal version 12.0.0

### Specifics

Installed a fresh copy of Umbraco V11.4.2 into a new folder. Ran the empty site and logged into the back office.  Clicked on the U (Umbraco Info) icon to reveal version 12.0.0

Also installing uSyncForms 10.0.1.0 fails as it requires Umb 10 && 11 but sees the back office version as 12.0.0

### Steps to reproduce

Install a fresh copy of Umbraco V11.4.2 into a new folder. Run the empty site and log into the back office.  Click on the U (Umbraco Info) icon to reveal version.

### Expected result / actual result

Expected the info tab to reveal version 11.4.2 as that's what Nuget and the web.csproj says is installed and that's what had been installed in the first place via the Package Script Writer. Have done this three times to make absolutely sure.  As well as clearing caches, etc.

Actual result is that version 12.0.0 is reported instead.

**Comment by Zeegaan** [comment]
Hey @craigs100, do you have the right templates installed? 🤔 

This is me running `dotnet new install Umbraco.Templates::11.4.2` (we need the ::{version} as the newest is v12)
And it works as expected for me 🤔 
![image](https://github.com/umbraco/Umbraco-CMS/assets/70372949/6678ff48-e23c-4a02-aeb5-c8e3b4650697)

Have I done something wrong here ? 😁

**Comment by craigs100** [comment]
Hi @Zeegaan,

I just ran it with the line you gave and it reports the correct version. What's happening is if I use the following script, then it ends up as V12.0.0 (latest being V12.0.1)

```
# Ensure we have the latest Umbraco templates
dotnet new -i Umbraco.Templates::11.4.2

# Create solution/project
dotnet new sln --name "Test2023"
dotnet new umbraco --force -n "Web" --friendly-name "Craig" --email "craig@incrediblyuseful.net" --password "Test12345678" --development-database-type SQLite
dotnet sln add "Web"

#Add Packages
dotnet add "Web" package uSync
dotnet add "Web" package Skybrud.Umbraco.Redirects
dotnet add "Web" package Diplo.GodMode
dotnet add "Web" package Our.Umbraco.TheDashboard
dotnet add "Web" package tooorangey.uEditorNotes
dotnet add "Web" package Our.Umbraco.Community.Contentment
dotnet add "Web" package Our.Umbraco.BackOfficeThemes
dotnet add "Web" package HotChilli.Umbraco.PageNotFound

dotnet run --project "Web"
#Running
```

This has been generated from the Package Script Writer, but I suspect it's one of the packages doing it. It's a bit weird. I've done it twice this morning and have screen recorded it.  I'm not suggesting you to fix packages of course, but I'm just wondering if there's anything in the Umbraco installation reacting to them. If not then it's just something to note I guess.

**Comment by Zeegaan** [comment]
Yea must sadly be one of the packages doing it 😢 
I've tried the `dotnet new umbraco --force -n "Web" --friendly-name "Craig" --email "craig@incrediblyuseful.net" --password "Test12345678" --development-database-type SQLite` just do make sure its not on our end, and that runs fine aswell without auto-updating 🤷 

I will close this for now, feel free to re-open if you find new information 👍

**Comment by craigs100** [comment]
Thanks. At least I know it's not me, lol. I'll report it back to Package Writer. Maybe they can put a note about it.

**Comment by prjseal** [comment]
Hi Craig

Have you tried specifying the correct version of uSync? 
By not adding a version you are telling it you want the latest version for that package. But the latest for that package might have a dependency on 12. 

It looks like uSync is the one.

Tick the box and choose the latest v11 version

![image](https://github.com/umbraco/Umbraco-CMS/assets/9142936/dbd5350e-216e-4d0a-9e87-10711c279f6e)

That will create this

```cs
dotnet add "MyProject" package uSync --version 11.2.1
```

![image](https://github.com/umbraco/Umbraco-CMS/assets/9142936/08a10d9c-248c-4650-9676-efdd7c635222)

I hope that solves your issue.

Kind regards

Paul
