### ISSUE TITLE
Order of operations following scope completion has changed in Umbraco 12

### ISSUE THREAD

**Issue by AndyButland** [umbraco/Umbraco-CMS#14572]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

12.0.1

### Bug summary

This is more of a change in behaviour that maybe wasn't intentional rather than a bug in the CMS, but it's causing a bug in Deploy and possibly other cases where the order of operations following scope completion is important.

The specific case in Deploy is related to handling redirects, we have some logic that:

- If a content item has moved or has had it's name changed - leading to a change in the URL it's hosted at - we track the current route to the content item during processing when it's transferred to an another environment.
- We then enlist a function to run on the scope completion, which will process the redirect creation.  It'll get the new route, double check that it's different to the old one, and save a redirect record.
- In this way if the content is moved in a staging environment and deployed to live, it'll also be moved in live and a redirect record will be created.

The function that sets the redirects on scope completion relies on getting the new route, but in Umbraco 12 it still gets the old one.  As such we determine the content's path hasn't actually changed, and don't create a redirect.

### Specifics

The reason this is happening I believe is due to a change in order of operations when scopes complete, which has come about with the refactoring of `Scope` and `CoreScope` in Umbraco 12.

In Umbraco 11 we would have [this order of events](https://github.com/umbraco/Umbraco-CMS/blob/v11/dev/src/Umbraco.Infrastructure/Scoping/Scope.cs#L904):
- handle file systems
- handle scoped notifications
- handle scope context (including enlisted actions)
- handle detached scopes

But in Umbraco 12 it works like this:
- handle scope context (including enlisted actions)
- handle detached scopes
- handle file systems
- handle scoped notifications

This [first two are called in `Scope.cs`](https://github.com/umbraco/Umbraco-CMS/blob/v12/dev/src/Umbraco.Infrastructure/Scoping/Scope.cs#L561), the second via the [later call to the base functionality in `CoreScope.cs`](https://github.com/umbraco/Umbraco-CMS/blob/v12/dev/src/Umbraco.Infrastructure/Scoping/Scope.cs#L414).

This causes the Deploy issue because the scoped notifications haven't yet run when our enlisted action is called.  Which means we get back the older route.

Now I'm just thinking... perhaps we just skip this check and create the redirect anyway.  We only really need to know the old route.  However it's nice to have this check and perhaps this change in behaviour has other effects, so I'll still consider a fix in the CMS first.

### Steps to reproduce

Using for example an Umbraco 12 set up on Umbraco Cloud:

- Create a content item and deploy it to the upstream environment
- Change the name of that content item and deploy it to the upstream environment
- Note that no redirect has been created

### Expected result / actual result

Redirect should be created, but more relevant for the CMS is that perhaps we should restore/retain the order of these events in Umbraco 12.

**Comment by Zeegaan** [comment]
Fixed in https://github.com/umbraco/Umbraco-CMS/pull/14573
