### ISSUE TITLE
Block List Editor - opening a list item with 2 tabs highlights both first and second tabs

### ISSUE THREAD

**Issue by tristanjthompson** [umbraco/Umbraco-CMS#14575]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

11.4.2

### Bug summary

Block list editor - if a block list element content type has 2 or more tabs, when you open it in the infinite editor, the second tab is partially highlighted with blue text until you start interacting with the overlay, at which point it goes back to the default, unselected default dark-blue-grey.

### Specifics

e.g. 
### When first opening the infinite editor with 2 tabs
![image](https://github.com/umbraco/Umbraco-CMS/assets/13795483/96553cdd-2825-4032-8a4c-ec3db32e50c6)

### After interacting
![image](https://github.com/umbraco/Umbraco-CMS/assets/13795483/6122fdfd-74ff-46ed-8866-7f32d8911d6a)

### Same behaviour with more than 2 tabs
![image](https://github.com/umbraco/Umbraco-CMS/assets/13795483/2cdb21fa-1650-4dd4-ad82-d5ef4410ad28)

### Steps to reproduce

* Create an element content type with 2 or more tabs - e.g. "BlockListElement1"
* Create a Block List Editor which allows you to add "BlockListElement1" into the list - e.g. "BlockList1"
    * Call tab 1 "First Tab" and add a textstring property beneath it called "Text box 1"
    * Call tab 2 "Second Tab" and add a textstring property beneath it called "Text box 2"
* Create a page content type - e.g. "ContentPage1"
* Add a property to ContentPage1 called "MyList" using the "BlockList1" editor
* Go to the content tab and add a ContentPage 1
* Add a block to the "MyList" field and see the infinite editor overlay
* See that the tab called "Second Tab" is highlighted with blue text
    * **Expected result** - it is not highlighted and is the default dark-blue-grey colour
* Click anywhere in the infinite editor overlay
    * See that the the "Second Tab" is now in the default dark-blue-grey colour.

### Expected result / actual result

When the infinite editor/overlay is opened, the second tab should be the default dark-blue-grey

**Comment by Zeegaan** [comment]
I can reproduce this 🐛 

I will put this up for grabs as we'd love some help with this! 🙌

**Comment by bjarnef** [comment]
It seems the issues the second tab get focus when opened, although the list item doesn't have `umb-tab--active` class.

So the button get the blue text color from the focus selection.

![image](https://github.com/umbraco/Umbraco-CMS/assets/2919859/a5638f00-cd36-4580-8a58-f105d464abc8)
