### ISSUE TITLE
Unpublished content is displaying as published content within the 'select link window'.

### ISSUE THREAD

**Issue by Kdingle1** [umbraco/Umbraco-CMS#14590]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

Umbraco 11

### Bug summary

Unpublished content is displaying as published content within the 'select link window'. It should be greyed out or not there. 
This means a user can link to content that is not published and great a 502 error on the page.

### Specifics

All content types within Umbraco 11

Unpublished content is displaying as published content within the 'select link window'. It should be greyed out or not there. 
This means a user can link to content that is not published and great a 502 error on the page.

### Steps to reproduce

Video: https://www.dropbox.com/s/6v975fe15n4s4ha/2023-05-31%2013-55-09.mp4?dl=0

**Comment by kjac** [comment]
Hi @Kdingle1,

Thank you for reaching out 💪 

I can reproduce this. Fortunately this is "only" an issue when searching for items in the URL picker. In the following screenshot, the items marked are not published:

![image](https://github.com/umbraco/Umbraco-CMS/assets/7405322/79727aa6-94de-45f0-8df3-aef9219e79ec)

The default tree view does reflect the published state correctly:

![image](https://github.com/umbraco/Umbraco-CMS/assets/7405322/bae7cce4-fc51-4765-a375-265d31ac4ed6)

I'm putting this up for grabs. Hopefully someone will jump at fixing it 😄 

**Notes for fixing**

As shown in the screenshot, the effect is applied in the tree view by means of CSS (the `.not-published` class). The same effect is clearly not applied in the mini list view (the search results).

If I read the data correctly, the entity search controller (`/umbraco/backoffice/umbracoapi/entity/Search?query=en&type=Document&dataTypeKey={GUID}`) does not provide anything for the mini list view to react upon in terms of published state:

![image](https://github.com/umbraco/Umbraco-CMS/assets/7405322/736a6059-1bf0-4a91-a0d7-2a946bf0af70)

This means the task is two-fold:

1. Enrich the output from the entity search controller. I suggest adding the published state to the `metaData` collection.
2. Use the enriched output in the mini list view to apply an "unpublished" (greyed out) state.

**Comment by Kdingle1** [comment]
Thanks all for your work on this! Great to get it fixed :)
