### ISSUE TITLE
The AngularJS template string syntax for a Block Editor Label appears to be not running when used in a sidebar editor

### ISSUE THREAD

**Issue by JBotger** [umbraco/Umbraco-CMS#14603]
Bug

https://docs.umbraco.com/umbraco-cms/fundamentals/backoffice/property-editors/built-in-umbraco-property-editors/block-editor/label-property-configuration

The AngularJS template string syntax for a Block Editor Label appears to be not running when used in a sidebar editor but is does work when used in a Inline editing mode. Instead of the statement output I still see the AngularJS syntax as label. For example "{{ title}}" will outputted as "Example Title" when used in the Inline editor but will be outputted like "{{ title}}" when used in the sidebar editor.

**Comment by kjac** [comment]
Hi @JBotger,

Thank you for reaching out 😄 

I'm afraid I can't reproduce this. Here's a block list using the label template `{{title}}` in the latest V10:

![image](https://github.com/umbraco/Umbraco-CMS/assets/7405322/1f5a1b21-25ff-48a8-900c-fa6fa157e641)

I have tried various permutations of the template (added spacing here and there) but end up with the same result.

Can you offer some more steps to reproduce?

**Comment by JBotger** [comment]
It turns out I was using an older version of Umbraco (10.5.0) where the issue was present. I did an upgrade to 10.6.1 and the problem was gone.
