### ISSUE TITLE
State is lost between content unpublishing and unpublished notifications

### ISSUE THREAD

**Issue by lauraneto** [umbraco/Umbraco-CMS#14636]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

12.0.1 & 11.4.0

### Bug summary

The [documentation](https://docs.umbraco.com/umbraco-cms/reference/notifications#notification-handlers-lifetime) mentions that notification "pairs" are **stateful**, and therefore share the state dictionary.
While I've seen this work for some notification pairs, I noticed that it doesn't work for `ContentUnpublishingNotification` and `ContentUnpublishedNotification`.

### Steps to reproduce

1. Set up a fresh Umbraco 12.0.1 install
2. Create the notification handlers as follows
```csharp
public class NotificationTests : INotificationHandler<ContentUnpublishingNotification>, INotificationHandler<ContentUnpublishedNotification>
{
    public void Handle(ContentUnpublishingNotification notification)
    {
        notification.State["test"] = "Hello world!";
    }

    public void Handle(ContentUnpublishedNotification notification)
    {
        var test = notification.State["test"];
    }
}
```
3. Register the new notification handlers in the startup class
```csharp
public void ConfigureServices(IServiceCollection services)
{
    services.AddUmbraco(_env, _config)
        .AddBackOffice()
        .AddWebsite()
        .AddDeliveryApi()
        .AddComposers()
        .AddNotificationHandler<ContentUnpublishingNotification, NotificationTests>()
        .AddNotificationHandler<ContentUnpublishedNotification, NotificationTests>()
        .Build();
}
```
4. Create a document type that can be added in the root
5. Create a node using that document type
6. Publish the node
7. Unpublish the node
8. Verify that you get a `KeyNotFoundException` in the `ContentUnpublishedNotification` code due to the dictionary being empty.

### Expected result / actual result

The state would be kept between the `ContentUnpublishingNotification` and the `ContentUnpublishedNotification`.

**Comment by bergmania** [comment]
Hi @lauraneto..

Thanks for reporting. I can reproduce and have a fix ready
