### ISSUE TITLE
Block Grid - Block label value does not change

### ISSUE THREAD

**Issue by miljepetrovic** [umbraco/Umbraco-CMS#14649]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

v10.6.1

### Bug summary

I have a Block Grid Data Type where I added the Block and specify Content Model. When I try to change the configuration of that Block and update the Label value it does not change. It always displays the name of the Content Model.

 
https://prnt.sc/m5unMqkWoUuG
https://prnt.sc/eV7ztuKDjkYp

I did not specify any custom template or custom style.

I use this default gridblock.editor.html. 

https://github.com/umbraco/Umbraco-CMS/blob/v10/dev/src/Umbraco.Web.UI.Client/src/views/propertyeditors/blockgrid/blockgridentryeditors/gridblock/gridblock.editor.html

### Steps to reproduce

Create Block Grid Data Type 
Add Block and specify block label
Try to add new block in the block grid data type and Content Model Name will be displayed

---
_This item has been added to our backlog [AB#31901](https://dev.azure.com/umbraco/243e7927-03b2-44e2-908f-d4ac7ea5daaa/_workitems/edit/31901)_

**Comment by kjac** [comment]
Hi @miljepetrovic,

Thanks a lot for reporting this ❤️ 

I can reproduce this on V11 for both the Block List and the Block Grid. Seems it's a general issue for labels.

My findings so far:

1. "Pure" Angular templates work as expected - i.e. `{{title}}`
2. "Mixed" templates work as expected - i.e. `This is the title: {{title}}`
3. "Simple" labels do not work at all; they block title reverts to the element type name (as reported in this issue).

The only workaround for "simple" labels is to use an Angular expression to print out the label - i.e. `{{'This is the title'}}`. That's rather quirky to say the least 😄 

[The docs](https://docs.umbraco.com/umbraco-cms/fundamentals/backoffice/property-editors/built-in-umbraco-property-editors/block-editor/label-property-configuration) do not mention "simple" labels, but they do indicate that "simple" labels should be possible. At least that's how I read them 🤔 

We'll see if we can create a fix in an upcoming sprint.

**Comment by miljepetrovic** [comment]
You are welcome @kjac. 

I think that it would be helpful as well to be able to display value from the Settings Model by using the "Pure" template. You might consider that as well.

**Comment by bjarnef** [comment]
@kjac I wonder if this PR https://github.com/umbraco/Umbraco-CMS/pull/14143/files affected this as I think simple label also used to work in Block List / Block Grid.

It seems the PR removed this part `blockObject.config.label`.

**Comment by nielslyngsoe** [comment]
Hi @bjarnef Good catch, I've made a solution that should make everyone happy again.

So no flashing of AngularJS Template code but still rendering the 'simple' labels.

https://github.com/umbraco/Umbraco-CMS/pull/14700

**Comment by kjac** [comment]
Fixed in https://github.com/umbraco/Umbraco-CMS/pull/14700
