### ISSUE TITLE
Change description of Composition for Member types

### ISSUE THREAD

**Issue by alina-tincas** [umbraco/Umbraco-CMS#14654]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

12.1.0

### Bug summary

From 12.1.0 it is now possible to use compositions within member types, just like document types, as per the following PR #14060 

However, upon further testing, it seems that when trying to add a composition to a member type, the description that shows up is the following "Inherit tabs and properties from an existing Document Type. New tabs will be added to the current Document Type or merged if a tab with an identical name exists". So instead of mentioning **"Document Type"** it should be **"Member Type"** as it is the member types that can be used as compositions for other member types. 

![image](https://github.com/umbraco/Umbraco-CMS/assets/83591955/9a1800dc-776b-469d-a0c1-5ffab84fb048)

### Steps to reproduce

1. on a 12.1.0 version of CMS create a new member type
2. on the newly created member type click on "compositions" and there you will see the description of the composition

### Expected result / actual result

The description of the composition on the member types should be "Inherit tabs and properties from an existing Member Type. New tabs will be added to the current Member Type or merged if a tab with an identical name exists" or "Inherit tabs, groups, and properties from an existing Document Type. New tabs will be added to the current Document Type or merged if a tab with an identical name exists"

**Comment by kjac** [comment]
Definitively this 😄
