### ISSUE TITLE
Configure Application cookie options no longer work after upgrade from 11.2.2 to 11.4.2

### ISSUE THREAD

**Issue by RiaMang** [umbraco/Umbraco-CMS#14650]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

11.4.2

### Bug summary

There was a recent security update on July 13 and we upgraded our umbraco 11.2.2 site to 11.4.2. After that upgrade, the Configure application cookie options no longer work. Here is a snippet of the code:

services.ConfigureApplicationCookie(options => { options.LoginPath = "/login"; options.AccessDeniedPath = "/no-access"; });

The login path works fine but instead of redirecting to /no-access, when a user tries to navigate to a page where they do not have permissions, they see the IIS 403 page instead. 

![image](https://github.com/umbraco/Umbraco-CMS/assets/11724128/17ffed5d-5225-4f8e-bfa5-ee67c8785e1e)

Also the client's users have suddenly noticed that the cookie times out within 20 minutes which interferes with exams taken on the site and causes users to fail them. We tried extending that time here:

services.ConfigureApplicationCookie(options => { options.ExpireTimeSpan = TimeSpan.FromMinutes(480); options.LoginPath = "/login"; options.AccessDeniedPath = "/no-access"; });

That does not seem to work either. 

All these issues have started happening only after the upgrade on July 13.

### Steps to reproduce

![image](https://github.com/umbraco/Umbraco-CMS/assets/11724128/ff0681c3-57fc-4912-bf4f-55f32345ca80)
The above is the generic 403 message instead on the /no-access page.

The cookie expiring early, just causes the users to lose data and then they are kicked to the login page.

I will try to create a fresh umbraco install and update steps here if possible.

### Expected result / actual result

The users were bring to redirected to the /no-access page when they tried to access a page they did not have permissions for. And there were no complaints from users about being logged out in 15-20 mins. These issues have started only after the security fix was pushed i.e. when we upgraded from 11.2.2 to 11.4.2

**Comment by RiaMang** [comment]
We were able to fix the Access denied issue by updating the code like so:

services.ConfigureApplicationCookie(options =>
           {
                options.LoginPath = "/login";
                options.AccessDeniedPath = "/no-access";
                options.Events.OnRedirectToAccessDenied = ctx =>
                {
                    // Explicit redirect is required to prevent Umbraco from overriding this behaviour with empty 403 response
                    ctx.Response.Redirect(ctx.RedirectUri);
                    return Task.CompletedTask;
                };
            });
Not sure if we should do this step or if this needs to be fixed in umbraco.cms, so keeping this open for review.

Also figured that the users being logged out was due to the security stamp validator. We have users signed in through SSO and then we create a member cookie. The security stamp validator check was failing because no such member record existed in the db. We implemented a custom security stamp validator to resolve that issue.

**Comment by kjac** [comment]
Hi @RiaMang,

Thanks for reaching out 😄 and great job digging into the details of the issue 💪 

I believe this is caused by https://github.com/umbraco/Umbraco-CMS/pull/14036, which is fixed for 11.5 - see https://github.com/umbraco/Umbraco-CMS/pull/14399.

I'm going to close this issue for now. If 11.5 does not resolve it for you, please pretty please reopen this issue 🙏
