### ISSUE TITLE
Cannot update to latest `Microsoft.ICU.ICU4C.Runtime`

### ISSUE THREAD

**Issue by gregor-tusar-sowa** [umbraco/Umbraco-CMS#14661]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

12.1.0

### Bug summary

I tried to update solution's packages. After updating `Microsoft.ICU.ICU4C.Runtime` to `72.1.0.1` the solution did not start anymore.
<img width="537" alt="image" src="https://github.com/umbraco/Umbraco-CMS/assets/80673797/700a4429-c532-4ebf-a631-a314773260d7">

I saw that Umbraco still references `Microsoft.ICU.ICU4C.Runtime` version `68.2.0.9`
- [src/Umbraco.Web.UI/Umbraco.Web.UI.csproj](https://github.com/umbraco/Umbraco-CMS/blob/0edee82b0b92876ef336a04fa82eb48832302523/src/Umbraco.Web.UI/Umbraco.Web.UI.csproj#L16)
- [templates/UmbracoProject/UmbracoProject.csproj](https://github.com/umbraco/Umbraco-CMS/blob/0edee82b0b92876ef336a04fa82eb48832302523/templates/UmbracoProject/UmbracoProject.csproj#L15)

### Steps to reproduce

- update `Microsoft.ICU.ICU4C.Runtime` to version `72.1.0.1`
- run solution
- error will occur: `Failed to load app-local ICU: icuuc68.2.0.9.dll`

### Expected result / actual result

Umbraco would work with latest stable version of `Microsoft.ICU.ICU4C.Runtime`

**Comment by nul800sebastiaan** [comment]
I think you can update it if you also remember to change the version in the csproj file, this was discussed on Discord the other day: https://discord.com/channels/869656431308189746/1135846717858775040  (if you're not on Discord, read along here: https://www.linen.dev/d/umbraco/t/13549268/microsoft-icu-icu4c-runtime-72-1-0-1-breaks-stuff)

**Comment by nul800sebastiaan** [comment]
FYI: We haven't tried this version and not looked at the release notes, so can't guarantee it will work and we don't support this version yet.

**Comment by nul800sebastiaan** [comment]
No that version is definitely stable - https://www.nuget.org/packages/Microsoft.ICU.ICU4C.Runtime/72.1.0.1 

But we (Umbraco) does not support it yet. You can update it in your own projects and see how it goes.

**Comment by gregor-tusar-sowa** [comment]
I'm confused now :)
<img width="187" alt="image" src="https://github.com/umbraco/Umbraco-CMS/assets/80673797/f9b030b4-9879-45f8-a5cc-4e6993a8cf10">
<img width="168" alt="image" src="https://github.com/umbraco/Umbraco-CMS/assets/80673797/6ef10ca6-597f-48d3-9864-4b08ac2ec0c5">

I'll just wait to be updated by umbraco.


Thanks for clearing it up so quickly!
