### ISSUE TITLE
blockgrid editor block in the backoffice  is not displaying any of the icons - possibly because of a 404 to uui.min.js.map? 

### ISSUE THREAD

**Issue by juanlondonoforero** [umbraco/Umbraco-CMS#14680]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

11.3.1

### Bug summary

The blockgrid editor block in the backoffice  is not displaying any of the icons on the top right (edit/copy/delete).  I don't know if this is related but Umbraco makes a request to "GET /umbraco/lib/umbraco-ui/uui/dist/uui.min.js.map;;" (note the semicolons), which fails with a 404. The file /umbraco/lib/umbraco-ui/uui/dist/uui.min.js.map (without the semicolons) exists just fine.

### Steps to reproduce

![image](https://github.com/umbraco/Umbraco-CMS/assets/46343500/7636d30e-bc20-438f-a277-3699f9492b57)

![image](https://github.com/umbraco/Umbraco-CMS/assets/46343500/bc4c8f1d-6f42-486d-b0e0-d1cf6b296361)

### Expected result / actual result

Again, I don't know if the 404 to the file uu1.min.js.map is related but I would expect to see the copy/edit/delete icons displayed on the top right of the Block Editor

**Comment by elit0451** [comment]
Hi @juanlondonoforero 👋 

I don't seem to be able to reproduce on a fresh Umbraco v11.4.2 install. Anything I might be missing here?


https://github.com/umbraco/Umbraco-CMS/assets/21998037/4614f2da-aaa9-44e5-864d-176772c57b28

**Comment by juanlondonoforero** [comment]
Hi. yes. it doesn't happens for new projects; I'm not sure if it was something to do with new packages or what but I found out that I'm not the only one with this problem- different symptoms
Any ideas please?

[https://our.umbraco.com/forum/using-umbraco-and-getting-started/112317-umbraco-asks-for-a-map-file-appended-with-semicolons-putting-backoffice-in-a-fail-state](https://protect-eu.mimecast.com/s/pDh0CElY0cW4RVYFNxutW?domain=our.umbraco.com)

**Comment by elit0451** [comment]
You mean that it doesn't happen on fresh installs. I tried upgrading from a fresh v11.3.1 to the latest 11.4.2 to see if anything will go wrong with the upgrade but it still works as intended and I can see all the icons.

I am not sure how else to reproduce this issue. Perhaps keep an eye on the forum 🤷‍♀️

**Comment by elit0451** [comment]
As we cannot reproduce the issue on a fresh install, I am afraid there is not really anything we can do. Maybe join the forum discussion and hopefully, you can figure out what package is "breaking something".
