### ISSUE TITLE
Menu "Content" when type data choose button "Save..." warning data json color green" appear had created multi language

### ISSUE THREAD

**Issue by thanhhien063** [umbraco/Umbraco-CMS#14708]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

12.1.1

### Bug summary

Menu "Content" when type data choose button "save..." warning json data color green"

### Steps to reproduce

Install Project Umbraco version 12.1.1. Done after change created multi languages (more than 2 languages). Create an item under Content -> After type data for tab "Content" choose button "Save..." warning data json color green". Although it was still successful. Hope Umbraco team supports this bug. Thanks so much.

**Comment by nathanwoulfe** [comment]
Hey @thanhhien063, thanks for letting us know - we have a fix merged and ready to go (https://github.com/umbraco/Umbraco-CMS/commit/5dfb914e0f2a335c05629f38fbad2a6197a2f656). Since we're aware and have a solution, I'll close this issue. Thanks again 😄

**Comment by nathanwoulfe** [comment]
And just saw this was your first issue report (ever) - welcome to the Umbraco community 👋
