### ISSUE TITLE
Block Grid Backoffice custom View and Controller

### ISSUE THREAD

**Issue by stefanstankovic** [umbraco/Umbraco-CMS#14709]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

12.1.1

### Bug summary

Hi dear Umbraco team,
I've reported the issue on the forum: 
https://our.umbraco.com/forum/using-umbraco-and-getting-started/112488-block-grid-backoffice-custom-view-and-controller

I tried to figure out the problem in the Umbraco code. Unfortunately, it wasn't enough just to follow the code. 

### Steps to reproduce

How to reproduce the issue:
1. Create a layout (in my case full width).
2. Create a Block Grid model 
3. Create a Block Grid data type with the layout and model. 
The layout can be added in the root only, and the model can be added in the area only
4. Follow the instruction to create a Block Grid view. My structure:
![image](https://github.com/umbraco/Umbraco-CMS/assets/15331581/40e9c449-a3a5-4f03-9b97-be213b4245e8)
5. File contents are posted on the forum in the post above.
6. Add a variable to the controller. eg. `$scope.model.themeClass` = 'theme--blue' and try to use it in the view `ng-class="['talking-numbers', model.themeClass]"`
7. Create a Home Page Document type and add the Block Grid data type created in step 3.
8. Use the created document type to create a content page and add the layout and the model to it. 
10. Save and reload the page.

### Expected result / actual result

Variant 1:
Set settings property: Umbraco:CMS:Hosting:Debug to `true`

Expected result:
the model is rendered in the backoffice in the expected way.

Variant 2:
Set settings property: Umbraco:CMS:Hosting:Debug to `false`

Expected result:
Error occurs

**Comment by Zeegaan** [comment]
Hello there 👋 It is a hard to help here, as it works fine locally, so sadly I can't really do anything about it :( 
Could you come up with some reproduction step where it does not fail so I can reproduce this? 🙏

**Comment by stefanstankovic** [comment]
I found what was the problem with this error. If Hosting isn't set on Debug mode, Umbraco reads file content and creates one unified file to be able to minify it. A path with a version to the end can't be read by File.IO "~/App_Plugins/UmbracoBlockGrid/BlockControllers/talkingnumbers.controller.js?v=202308181926", so removing ?v=202308181926 fixed the problem.
