### ISSUE TITLE
Empty MultiUrlPicker being recognized as valid value

### ISSUE THREAD

**Issue by cornehoskam** [umbraco/Umbraco-CMS#14716]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

8.18.8

### Bug summary

Hi all!

While using the latest version of Umbraco 8, we've ran into an issue where we expected an empty MultiUrlPicker to use a fallback value instead, and we were suprised when this wasn't the case. After some further investigation I found out that in the Umbraco 8 MultiUrlPickerValueConverted the "IsValid" check users the following code:
`return value?.ToString() != "[]"`
This means however that a Null value is being accepted as a valid value returning true, and therefor won't trigger a fallback, which I would have expected. I managed to resolve this by create a custom ValueConverter myself with an additional Null check, but I wonder if this is intentional behavior or should be classified as a bug?

### Steps to reproduce

-Create a multi-culture/multi-segment document type.
-Add a MultiUrlPicker with no limits on it to said document type.
-Save and Publish a variant with values filled in, and one variant without values.
-Open the page with no values in it's variant.

### Expected result / actual result

I would expect it to have fallen back on the MultiUrlPicker of the page variant that does have one or more items selected, but instead it returns an empty list of items due to the behavior of null being parsed to an empty list of Links.

**Comment by andr317c** [comment]
Hey!

Thanks for reporting the issue 😄 I was able to reproduce this on 8.18.8 and 12.1.1. Fallback should also work for the MultipleUrlPicker, so it is a bug! I will go ahead and mark this as an up for grabs.

**Comment by cornehoskam** [comment]
Thank you @andr317c! I'll submit a pullrequest with the code I used to patch my own solution for thise soon! :)

**Comment by cornehoskam** [comment]
Well it appears as though there are two different issues depending on the Umbraco version!
-In Umbraco 8 there exists no null check on the MultiUrlPickerValueConverter's IsValue() property. Adding a null check fixes that issue.
-Umbraco 12 does have this nullcheck, but doesn't appear to be providing the correct fallback method when fetching a property... I'll submit a PR for the V8 version, but if someone has an idea for V10/V12, feel free!

**Comment by nul800sebastiaan** [comment]
I've explained on https://github.com/umbraco/Umbraco-CMS/pull/14718 why we're going to find it very hard to fix PVCs without breaking someone's workflow. I think we should look at all of them at the same time and fix all of them for a major release, marking the fix as breaking. I'll close this one for now.
