### ISSUE TITLE
Content Delivery API: How to retrieve protected data after member login ( JWT / OAUTH2 )?

### ISSUE THREAD

**Issue by biapar** [umbraco/Umbraco-CMS#14726]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

12.1

### Bug summary

Hi,
Today, the lack of the support that Delivery API does not support authentication for members is a problem and so we cannot use Umbraco as a very headless CMS like the others.
Until now, I'm using U10 LTS with an headless custom package Nikcio.UHeadless.
To retrieve the protected content of a member, I create before a group generic and a group for the member.
So I protect the node with generic + member or only member and the parent with the generic group.
In the request , I pass the member ID + email and check if the permission on the node is ok or not.

### Steps to reproduce

To retrieve the protected content of a member, I create before a group generic and a group for the member.
So I protect the node with generic + member or only member and the parent with the generic group.
In the request , I pass the member ID + email and check if the permission on the node is ok or not.

### Expected result / actual result

Get the protected data.

**Comment by andr317c** [comment]
Hey!

We are already working on adding member auth to the delivery API! #14730. I will go ahead and close this since this is not really an issue 😄
