### ISSUE TITLE
DateTime picker calendar does not get updated when custom date format

### ISSUE THREAD

**Issue by tomotrepo** [umbraco/Umbraco-CMS#14722]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

12.1.1.

### Bug summary

DateTime filed has custom date format set: DD.MM.YYYY. When saving everything is ok. Next time when editing - calendar not get updated with saved value.

### Specifics

DateTime field has custom date format eg. european: DD.MM.YYYY

### Steps to reproduce

See attacment
![Edit_ News - Content - firekitc localtest me (1)](https://github.com/umbraco/Umbraco-CMS/assets/7202849/cd2ede1a-3baa-4ff9-a832-9ff662cad693)

### Expected result / actual result

Expected calendar to be updated with saved value in given format.

**Comment by andr317c** [comment]
Hey! 
Thanks for posting your issue, I was able to reproduce it. The date-picker calendar always ends up being on the first of January of the year of the date you have entered. This issue occurs if you use another date-time format than `YYYY-MM-DD` or `YYYY-DD-MM`

If you change the date-time format to `YYYY-DD-MM` the date-picker calendar ends up showing the month as the day after you update.

![image](https://github.com/umbraco/Umbraco-CMS/assets/73799582/05acbe5e-36e1-455c-82eb-334aaf1ca2d7)


I will mark this issue as an up for grabs!
