### ISSUE TITLE
Hide link box via notification no longer work

### ISSUE THREAD

**Issue by bjarnef** [umbraco/Umbraco-CMS#14737]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

12.1.1

### Bug summary

In Umbraco 12.0.0 we had the following the hide link box on specific node types: https://docs.umbraco.com/umbraco-cms/reference/notifications/editormodel-notifications/customizing-the-links-box

However after upgrading to 12.1.0 or 12.1.1 it seems this no longer works.

![image](https://github.com/umbraco/Umbraco-CMS/assets/2919859/6a7c910d-3d23-432a-8077-361b213d1bb4)

### Steps to reproduce

Implement the example from the documentation https://docs.umbraco.com/umbraco-cms/reference/notifications/editormodel-notifications/customizing-the-links-box or something similar to the code below using ModelsBuilder.

```
public class EditorSendingContentNotificationHandler : INotificationHandler<SendingContentNotification>
{
    private readonly IPublishedSnapshotAccessor _publishedSnapshotAccessor;

    public EditorSendingContentNotificationHandler(
        IPublishedSnapshotAccessor publishedSnapshotAccessor)
    {
        _publishedSnapshotAccessor = publishedSnapshotAccessor;
    }

    public void Handle(SendingContentNotification notification)
    {
        if (notification.Content.ContentTypeAlias.Equals(EmployeeArchive.ModelTypeAlias) ||
            notification.Content.ContentTypeAlias.Equals(Employee.ModelTypeAlias) ||
            notification.Content.ContentTypeAlias.Equals(LocationArchive.ModelTypeAlias) ||
            notification.Content.ContentTypeAlias.Equals(Location.ModelTypeAlias) ||
            notification.Content.ContentTypeAlias.Equals(TopicsArchive.ModelTypeAlias) ||
            notification.Content.ContentTypeAlias.Equals(Topic.ModelTypeAlias))
        {
            notification.Content.Urls = null;
        }
    }
}
```

```
public class SiteComposer : IComposer
{
    public void Compose(IUmbracoBuilder builder)
    {
        builder.AddNotificationHandler<SendingContentNotification, EditorSendingContentNotificationHandler>();
    }
}
```

**Comment by andr317c** [comment]
Hey!

Thanks for posting the issue with clear reproduction steps💪! I was able to reproduce it on 12.1.1 and 12.0.0. 

I did not get the Link Box for the first ContentNode I created, but when I created a second or third node(while still having the first node). The Link Box appeared again, but only for the second and third. 

See GIF: 
![HideLinkBox](https://github.com/umbraco/Umbraco-CMS/assets/73799582/27a0f9a5-860a-483a-9bb3-939927e1d8ca)

From what I can see. the LinkBox gets the redirectUrls from this API call  `redirecturlmanagement/RedirectUrlsForContentItem`.

Response from the first ContentNode:  `{"searchResults":[],"totalCount":0,"pageCount":1,"currentPage":1}` .
Response from the second ContentNode: `{"searchResults":[{"redirectId":"b0e2410d-34e5-434e-9a6f-814836ef2231","originalUrl":"/newcontents/","destinationUrl":"/newcontentss/","createDateUtc":"2023-08-29T08:10:36.3288761","contentId":1060,"culture":""},{"redirectId":"fcd56d82-5043-4275-afca-60ef35c27ce6","originalUrl":"/newcontent/","destinationUrl":"/newcontentss/","createDateUtc":"2023-08-29T08:10:33.6393988","contentId":1060,"culture":""}],"totalCount":2,"pageCount":1,"currentPage":1}`

I will mark this issue as an up for grabs!

**Comment by bjarnef** [comment]
@andr317c I think we started the project on Umbraco 11, so it may be before upgrade to Umbraco 12, but I am pretty sure it worked at that time :)

**Comment by bjarnef** [comment]
Filtering of urls does work though, e.g.

```
notification.Content.Urls = notification.Content.Urls?.Where(x => x.IsUrl).ToArray();
```

Since this is a multi-site solutions and 8 languages configured, it was showing a lot of empty links.

![image](https://github.com/umbraco/Umbraco-CMS/assets/2919859/7cd540b7-9b87-4eae-b002-a6fe73a5a473)

with this change:

![image](https://github.com/umbraco/Umbraco-CMS/assets/2919859/af56e5dc-3eba-46a2-b339-79cfdd584286)
