### ISSUE TITLE
Expand all, not working on Multinode Treepicker (non members)

### ISSUE THREAD

**Issue by tuaz-nn** [umbraco/Umbraco-CMS#14748]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

12.1.2

### Bug summary

when calling 

`/umbraco/delivery/api/v1/content?fetch=descendants:f43a240e-xxxx-yyyy-zzzz-ee7dd85084b0&filter=contentType:deliverable&expand=all`

we get returned list of deliverables, some of them get all the properties expanded correctly, 

![image](https://github.com/umbraco/Umbraco-CMS/assets/107190652/6d865fed-70f7-43ac-9674-cbf7e5074993)

some of them dont, instead we get "$ref": "xzy" 

![image](https://github.com/umbraco/Umbraco-CMS/assets/107190652/cb020474-bab8-413a-b8e0-2df55362fa7e)

the above two screenshots are from the same response.

the content type 'deliverable' has property which is a Multinode Treepicker (which selects other content from the tree, not members) (we tried to rebuild, the delivery index)

### Steps to reproduce

Create document type A with multi node treepicker that picks different content (not members)
Create a document type B, allow A under B in permissions
Create B in the Content
Create multiple As under B
call 

`/umbraco/delivery/api/v1/content?fetch=descendants:B&filter=contentType:A&expand=all`

Observe the response, some of the As will have expanded multi node tree, some will simple say $ref = "xyz"

**Comment by kjac** [comment]
Hi @tuaz-nn,

Thank you for reaching out 👍 

Unfortunately I can't replicate this... From your screenshots I suspect you've got some custom JSON serialization options applied to your solution, yielding the `$ref` and `$id` properties. Could you have a look to see if this suspicion is valid?

**Comment by kjac** [comment]
This issue seems to have gone a bit stale, so I'm closing it now. Feel free to reopen if the issue persists with no apparent root cause.
