### ISSUE TITLE
Umbraco log-in with Azure Active Directory results in GetCurrentUser 401

### ISSUE THREAD

**Issue by jacksorjacksor** [umbraco/Umbraco-CMS#14741]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

10.4.2

### Bug summary

After [authenticating the Umbraco backoffice with Azure Active Directory credentials](https://docs.umbraco.com/umbraco-cms/v/10.latest-lts/reference/security/authenticate-with-active-directory) and logging into the backoffice via "Sign in with Microsoft", user is greeted with white screen.

Console gives GetCurrentUser 401 error.

### Specifics

YouTube video of error:
https://www.youtube.com/watch?v=x2MBnUfZN6U

Console log:
```
o538367.ingest.sentry.io/api/4505322960453632/envelope/?sentry_key=87212a480dd645bda0f7e356d7df08ae&sentry_version=7&sentry_client=sentry.javascript.browser%2F7.54.0:1 
        
        
        Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
ServerVariables:2  Uncaught SyntaxError: Unexpected token '<'
umbraco/backoffice/umbracoapi/authentication/GetCurrentUser:1 
        
        
        Failed to load resource: the server responded with a status of 401 ()
angular.js:15697  Possibly unhandled rejection: {"errorMsg":"Server call failed for getting current user","data":"","status":401,"xhrStatus":"complete"}
(anonymous) @ angular.js:15697
umbraco/backoffice/umbracoapi/authentication/GetCurrentUser:1 
        
        
        Failed to load resource: the server responded with a status of 401 ()
o538367.ingest.sentry.io/api/4505322960453632/envelope/?sentry_key=87212a480dd645bda0f7e356d7df08ae&sentry_version=7&sentry_client=sentry.javascript.browser%2F7.54.0:1 
        
        
        Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
umbraco#/content:1  The keyword 'searchfield-cancel-button' specified to an 'appearance' property is not standardized. It will be removed in the future.
contentScript.bundle.js:65 
        
        
        POST https://o538367.ingest.sentry.io/api/4505322960453632/envelope/?sentry_key=87212a480dd645bda0f7e356d7df08ae&sentry_version=7&sentry_client=sentry.javascript.browser%2F7.54.0 net::ERR_BLOCKED_BY_CLIENT
(anonymous) @ contentScript.bundle.js:65
(anonymous) @ contentScript.bundle.js:65
add @ contentScript.bundle.js:65
i @ contentScript.bundle.js:65
_sendEnvelope @ contentScript.bundle.js:65
_flushOutcomes @ contentScript.bundle.js:65
(anonymous) @ contentScript.bundle.js:65
```

### Steps to reproduce

* Create fresh Umbraco 10 install
* Follow MS Azure [Tutorial: Create an Azure Active Directory B2C tenant](https://learn.microsoft.com/en-us/azure/active-directory-b2c/tutorial-create-tenant)
* Follow [authenticating the Umbraco backoffice with Azure Active Directory credentials](https://docs.umbraco.com/umbraco-cms/v/10.latest-lts/reference/security/authenticate-with-active-directory) docs, including registering AAD application
* Load Umbraco 10
* Go to backoffice with `/umbraco`
* Use "Sign in with Microsoft" option
* Sign in using MS Azure Active Directory log-in details
* Go to any page in the backoffice (i.e. `/umbraco#/content`)

### Expected Result

View backoffice pages

### Actual Result

White screen (see "Specifics")

**Comment by nikolajlauridsen** [comment]
Hey @jacksorjacksor I just checked on both the latest v10 and the latest v12 with AzureB2C and OpenIdConnect and in both cases the feature works as expected, there could be something wrong with your setup that makes this not work, a common gotcha is that the name and email claims are required (found in `ClaimTypes.Email` and `ClaimTypes.Name`). 

However the white screen seems to be a bug, we have that as a sprint candidate here though https://github.com/umbraco/Umbraco-CMS/issues/14724

I'll go ahead and close this for now, feel free to comment if I've missed something.

**Comment by jacksorjacksor** [comment]
Ah ok, thank you - for my clarity, where should those ClaimTypes go? Not at my desk right now but if you could give me more specific direction I'd really appreciate it, cheers!

**Comment by nikolajlauridsen** [comment]
I'd recommend having a look at https://docs.umbraco.com/umbraco-cms/v/10.latest-lts/reference/security/auto-linking#example-for-users there's an example there, specifically the

```
options.TokenValidationParameters.NameClaimType = "name";
options.TokenValidationParameters.RoleClaimType = "role";
```

It can also be done in the `OnTokenValidated` event which can be accessed when adding the provider
