### ISSUE TITLE
Title attributes contain technical names

### ISSUE THREAD

**Issue by plannero** [umbraco/Umbraco-CMS#14743]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

10.4.0

### Bug summary

Labels in the editing panel are difficult to understand for screen reader users, since not only the visible (translated) text is pronounced, but also the title attribute, which contains a technical field name (such as “mainImage” in the following example image):
 
<img width="571" alt="image" src="https://github.com/umbraco/Umbraco-CMS/assets/2157085/ad51075f-ec42-4879-bc18-b757028b844c">

### Steps to reproduce

Edit a page using a screen reader. Listen to the labels of each field. You will hear first the visible text and then the title attribute, which makes things harder to understand. (At least in a translated instance of Umbraco.)

### Expected result / actual result

If title attributes are to be used at all, they should not contain CamelCase tech lingo but rather terms that contribute to user understanding.

**Comment by andr317c** [comment]
Hey 😄 

Thanks for posting this issue. This is something we would like some help with, I'll go ahead and set this issue as up for grabs 😄

**Comment by FabCodeDE** [comment]
I'm working on this

**Comment by Adals-01** [comment]
Working on this
