### ISSUE TITLE
Failed to get cultures

### ISSUE THREAD

**Issue by biapar** [umbraco/Umbraco-CMS#14762]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

Umbraco version 12.1.1

### Bug summary

Server error: Contact administrator, see log for full details.
Failed to get cultures

### Steps to reproduce

Follow https://github.com/umbraco/Umbraco-CMS/issues/13559

**Comment by bergmania** [comment]
Cultures are provided to .NET by the OS, so you are maybe using a culture that is not supported by the version of Windows 2012R2 you're using.

**Comment by kjac** [comment]
Hi @biapar,

Could you please check the logs to see if there are any entries that could point in the direction of finding the offending culture? Maybe something along the lines of what is mentioned on the original issue: https://github.com/umbraco/Umbraco-CMS/issues/13559#issuecomment-1434665733

If this does not yield anything, please try installing a blank Umbraco site on the same hosting setup. This blank install must _not_ have any custom culture defined as default culture. If that does not fail, I do reckon the failing site uses a culture that is not supported by the OS.
