### ISSUE TITLE
Culture is defaulting to en-us in event handler

### ISSUE THREAD

**Issue by philipdanielhayton** [umbraco/Umbraco-CMS#14785]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

12.0.1

### Bug summary

When getting the value of a property from an IContent in a NotificationHandler it doesn't seem to respect the culture of the node being edited, and I can't seem to find a way to access the culture of the current node being edited.

To give a concrete example, in my setup I replaced the default backend language from en-us to en-gb, so the en-us language doesn't exist at all.

However calling `content.GetValue("myPropertyAlias")` from within a notification handler returns null, I think this is because it defaults to the Thread.CurrentThread culture, which is "en-us". Manually setting the culture to "en-gb" like `content.GetValue("myPropertyAlias", culture: "en-gb")` returns the expected results.

I am wondering if this will affect multi culture setups too?

Anyway, I'm not sure if this is a bug or intended behaviour, in which case is there anyway to get the culture currently being edited in the back office?

### Steps to reproduce

1. Replace the default language in Umbraco, for example set it to 'en-gb' instead of 'en-us'
2. Create a notification handler (see example below)
3. Debug and inspect the value of rawValue
4. Change the value of the property being retrieved, it should be null
5. Replace the `GetValue` call with this one `content.GetValue<IEnumerable<Udi>>(RelatedContentPropertyAlias, culture: "en-gb")`
6. Re-run the debug, the value should now be correct

```
    public class RelateContentOnSave : INotificationHandler<ContentSavedNotification>
    {
        public void Handle(ContentSavedNotification notification)
        {
            foreach (var content in notification.SavedEntities)
            {
                var culture = Thread.CurrentThread.CurrentCulture;
                var rawValue = content.GetValue(myPropertyAlias);
            }
        }
    }
```

### Expected result / actual result

I would expect the value return to either match the current culture being edited in the back end, or to be able to access the culture somehow.

I have a feeling the latter may be possible, but I'm not sure how?

**Comment by bergmania** [comment]
You do not mention anything about the `Umbraco:CMS:Global:DefaultUILanguage` did you also change that to "en-gb"? It sounds like that value is still "en-us".

**Comment by elit0451** [comment]
Hi @philipdanielhayton 👋 

Thanks for reaching out. 

I tried to reproduce the issue _(without setting `Umbraco:CMS:Global:DefaultUILanguage`)_. But for invariant content, I was able to get the property value by `content.GetValue("myPropertyAlias")`. _(as you can see from the video)_


https://github.com/umbraco/Umbraco-CMS/assets/21998037/7bebf0f3-630d-482e-ab47-44cc00d5f418



Your suspicions about multilingual site and localized content - you need to use `content.GetValue("myPropertyAlias", culture: "x")` to get the property value in a specific culture. To get the currently edited culture, you can use `IContent.EditedCultures`.

Regarding `Thread.CurrentThread.CurrentCulture` - it has the value of the **User** language which you can change by going into the user profile.

Hope this helps, let me know if I misinterpreted something 🙂

**Comment by kjac** [comment]
This issue seems to have gone a bit stale. I'm closing it now. If the issue persists, please feel free to reopen it with additional steps to reproduce.
