### ISSUE TITLE
EnsureUmbracoContext not working in Multiculture website

### ISSUE THREAD

**Issue by merijng** [umbraco/Umbraco-CMS#14790]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

12.1.2

### Bug summary

`umbracoContextFactory.EnsureUmbracoContext()` is not working correctly, without actual HttpContext.

### Steps to reproduce

- Install Umbraco 12.1.2
- Install Cultiv.Hangfire
- Create a new service
```
public class TestService
{
    private readonly IUmbracoContextFactory _umbracoContextFactory;

    public TestService(
        CustomDbContext db,
        IUmbracoContextFactory umbracoContextFactory
        )
    {
        _umbracoContextFactory = umbracoContextFactory;
    }

    public string Test()
    {
        using var ucr = _umbracoContextFactory.EnsureUmbracoContext();
        var root = ucr.UmbracoContext.Content.GetAtRoot().FirstOrDefault();

        return "";
    }
}
```
[Also for reference, this issue is reported earlier](https://our.umbraco.com/forum/using-umbraco-and-getting-started/109778-ensureumbracocontext-gives-no-content)
- Couple it with hangfire
  - F.e. using `RecurringJob.AddOrUpdate<TestService>("ttt", (service) => service.Test(null), Cron.Daily);`
- Please note that root will be null, while running the Hangfire task

I also tried the example given in #10522 (using IPublishedContentQuery), which also doesn't work.

@nul800sebastiaan Do you know anything about this issue?

### Expected result / actual result

Content from the root.

**Documentation reference:** [Click here](https://docs.umbraco.com/umbraco-cms/implementation/services)

**Comment by nul800sebastiaan** [comment]
You need to also create a scope - have a read here: https://cultiv.nl/blog/using-hangfire-to-update-umbraco-content/

**Comment by merijng** [comment]
@nul800sebastiaan Thanks for the fast response.

I already tried that, as described in #10522.

**Comment by nul800sebastiaan** [comment]
Alright, I'm not sure what to tell you, the code from the first example in the blog post works for me, see below. The code you posted above does not use the `ServiceProvider` to create a scope, so I'm not sure what your actual new code is. 




![image](https://github.com/umbraco/Umbraco-CMS/assets/304656/438b0d36-a022-40ff-8fe1-445e7f76f73d)

**Comment by merijng** [comment]
@nul800sebastiaan In the screenshot below, you can see that I used your code, and the rootNode is null.

One difference:

The AddOrUpdate is inside the startup.cs, instead of the composer.

public void ConfigureServices(IServiceCollection services)
    {
      var umbracoBuilder = services.AddUmbraco(_env, _config)
          .AddBackOffice()
          .AddWebsite()
          .AddComposers()
          .ConfigureAuthentication();

      // ...

      services.AddScoped<IJobs, Jobs>();
      RecurringJob.AddOrUpdate<IJobs>(x => x.ManipulateContent(null), Cron.Hourly);

      umbracoBuilder.Build();
    }

![image](https://github.com/umbraco/Umbraco-CMS/assets/6886678/ab7dba0a-db21-4d46-9eea-937d1ce7981a)

**Comment by nul800sebastiaan** [comment]
I know that the order matters and the `AddOrUpdate` should probably after `umbracoBuilder.Build();`, but I'm actually not sure what exactly the order should be. Try it in a `Composer` I'd say and see how it goes. That way your code is also more portable and doesn't rely on people remembering to add something in `Startup.cs` in the next project.

**Comment by merijng** [comment]
@sebastian-claesson Thanks for the fast response.

I did this in startup.cs, because of [issue 21 of Cultiv.Hangfire](https://github.com/nul800sebastiaan/Cultiv.Hangfire/issues/21). As described there, I've integrated the composer once again as in your article. Root is still null. I also tried to add AddOrUpdate below umbracoBuilder.Build();

**Comment by nul800sebastiaan** [comment]
Note: when I used the script above I got an error:

```
2023-09-11 04:30:51 [ERROR] (Hangfire.Processing.BackgroundExecution) Execution BackgroundServerProcess is in the Failed state now due to an exception, execution will be retried no more than in 00:00:15
Microsoft.Data.SqlClient.SqlException
Invalid object name 'HangFire.Server'.
```

CTLR+C and doing a `dotnet run --project "MyProject"` fixed it. But the starter kit also didn't install so I had to make a new doctype and root node by hand. I was hoping to avoid that work! 😅 Oh well.

**Comment by merijng** [comment]
@nul800sebastiaan I've investigated why we get a different result.

While creating the document type, please enable `Allow vary by culture`. Now you won't get anything. Excuse me for not putting it in the reproduction steps.

**Comment by merijng** [comment]
Found a workaround, as mentioned in #13334

Set `VariationContext` on `VariationContextAccessor`, before executing `EnsureUmbracoContext()`.
```
variationContextAccessor.VariationContext = new VariationContext("en-US");
```

**Comment by nul800sebastiaan** [comment]
I was just about to look into this again, great that you found the fix and I'll add it to the blog post! 👍
