### ISSUE TITLE
Disable default file logging

### ISSUE THREAD

**Issue by noliver123** [umbraco/Umbraco-CMS#14801]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

12.1.2

### Bug summary

I would like to use an Azure Table Storage logging instead of the default file logging to the umbraco/Logs folder. The table storage logging works fine after configure it but still logging to the umbraco/Logs folder and there is no option to disable this.

### Steps to reproduce

Configure the Azure Table Storage logging in the appsettings.json according to this instruction: https://docs.umbraco.com/umbraco-cms/fundamentals/backoffice/logviewer/.

So we add the following sink to the array Serilog:WriteTo:

{
"Name": "AzureTableStorage",
"Args": {
  "storageTableName": "LogEventEntity",
  "formatter": "Serilog.Formatting.Compact.CompactJsonFormatter, Serilog.Formatting.Compact",
  "connectionString": "DefaultEndpointsProtocol=https;AccountName=ACCOUNT_NAME;AccountKey=KEY;EndpointSuffix=core.windows.net"}
}

### Expected result / actual result

The default file logging should be disabled or there should be an option to disable it.

**Comment by elit0451** [comment]
Hi @noliver123 👋 

Disabling logging to `umbraco/Logs` folder isn't supported. You can only configure the logging directory ([link](https://docs.umbraco.com/umbraco-cms/reference/configuration/loggingsettings#directory)) but as a workaround, you can set the `LogLevel` of the file logging to **Fatal** - [link](https://docs.umbraco.com/umbraco-cms/fundamentals/code/debugging/logging#log-levels).

Hope this helps. I will go ahead and close this 🙂
