### ISSUE TITLE
API examinemanagement/GetIndexerDetails throws 500 when an index is corrupt

### ISSUE THREAD

**Issue by LennardF1989** [umbraco/Umbraco-CMS#14805]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

12.1.0

### Bug summary

After a deployment, our MemberIndex got corrupted (one of the files went missing). Usually, not a problem as you just go to Examine Management and rebuild it.

Not sure if it recentely changed, or a regression, but now the GetIndexerDetails threw a 500 error, causing the whole UI to simply not load. We were forced to move into SCM to wipe the corrupted index and restart the site.

### Specifics

![image (1)](https://github.com/umbraco/Umbraco-CMS/assets/869973/dc8be072-b09b-4ebf-9e53-0d66b8d281e0)

### Steps to reproduce

1. Start site, add a few members (most likely)
2. Kill site, remove one of the Lucene files in the MembersIndex folder to cause corruption
3. Start site, go into Examine Management. Boom!

### Expected result / actual result

Things do not go boom and you get a chance to rebuild it without going into the server files.

---
_This item has been added to our backlog [AB#32858](https://dev.azure.com/umbraco/243e7927-03b2-44e2-908f-d4ac7ea5daaa/_workitems/edit/32858)_

**Comment by elit0451** [comment]
Hi @LennardF1989 👋 

Thanks for reaching out and for the clear steps to reproduce. 💪 

I managed to replicate and we are looking into it. Until we have a fix, you can delete the whole MembersIndex folder and that will allow you to rebuild the MemberIndex again through the Examine Management dashboard 😌

**Comment by Zeegaan** [comment]
Fixed in https://github.com/umbraco/Umbraco-CMS/pull/14889
