### ISSUE TITLE
Custom Property caching issue when content is created from template

### ISSUE THREAD

**Issue by gabador-mof** [umbraco/Umbraco-CMS#14800]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

11.4.2

### Bug summary

Custom property caching when element containing property created from content template is incorrect. 

### Specifics

just found an issue with custom properties. Basically, we have created a custom property that has a rich text field and a checkbox, to allow us to create headings with tags in the same property. This works really well, but for when we create a content template, and create two pages from that template. So I have the custom property on a module: 

new LargeHeroModuleModel
            {
                SubHeading = **_customHeadingBuilder.GetHeading(source.SubHeading),**
                HeadingTitle = **_customHeadingBuilder.GetHeading(source.HeadingTitle),**
                Description = source.Description,
                ShowLogo = source.ShowLogo,
                Background = _mediaBuilder.GetMediaFrom(source.Background),
                ApplyBlur = !source.TurnOffBlur,
            };

say I create page 123 and page 234. I set the headingTitle and Subheading the same:
123 on page 123 
and 234 on page 234

When I save page 234 and load both page 123 and 234, both subheading and headingTitle come back as 234. 

When I create new pages, this does not happen. I note that te Hero module element comes back with the same GUID ID in both cases. 

PropertyConverter caching level is set to element. I assume the bug is when we create a new page from a template, the element key is not created anew, and all instances of elements using this template will get the same key. 

### Steps to reproduce

Create a custom property: I would say have whatever fields, but ours is: 

```
public class RteHeading : BaseCustomClass
{
    public string Text { get; set; }
    public string HTag { get; set; }
}
```
```
Here is the converter code: 
using Newtonsoft.Json;
using Umbraco.Cms.Core.Models.PublishedContent;
using Umbraco.Cms.Core.PropertyEditors;
using UMOF.CustomProperties.CustomPropertyService.CustomProperties;

namespace UMOF.CustomProperties.CustomPropertyService;

public class PropertiesConverter : IPropertyValueConverter
{
    private static List<BaseCustomClass> CustomProperties => CustomPropertyRegistrar.GetCustomProperties();
    public Type MyObjectType { get; set; }

    public bool IsConverter(IPublishedPropertyType propertyType)
    {
        foreach (var prop in CustomProperties)
        {
            var myType = prop.GetType();
            if (propertyType.EditorAlias == $"DC.{myType.Name}" ||
                propertyType.EditorAlias == $"UMOF.{myType.Name}")
            {
                MyObjectType = myType;
                return true;
            }
        }
        return false;

    }

    public bool? IsValue(object value, PropertyValueLevel level)
    {
        if (level == PropertyValueLevel.Source)
        {
            return value is not string s || string.IsNullOrWhiteSpace(s) == false;
        }

        throw new NotSupportedException($"Invalid level: {level}.");
    }

    public Type GetPropertyValueType(IPublishedPropertyType propertyType) => MyObjectType;

    public PropertyCacheLevel GetPropertyCacheLevel(IPublishedPropertyType propertyType) => PropertyCacheLevel.Element
;

    public object ConvertSourceToIntermediate(IPublishedElement owner, IPublishedPropertyType propertyType, object source, bool preview)
    {
        if (source == null)
        {
            return null;
        }

        var myObject = CustomProperties
            .FirstOrDefault(x =>
                $"DC.{x.GetType().Name}".Equals(propertyType.EditorAlias, StringComparison.Ordinal) ||
                $"UMOF.{x.GetType().Name}".Equals(propertyType.EditorAlias, StringComparison.Ordinal));

        MyObjectType = myObject?.GetType() ?? MyObjectType;
        var myCustomModel = JsonConvert.DeserializeObject(source.ToString() ?? string.Empty, MyObjectType);
        return myCustomModel;

    }

    public object ConvertIntermediateToObject(IPublishedElement owner, IPublishedPropertyType propertyType,
        PropertyCacheLevel referenceCacheLevel, object inter, bool preview) => inter;


    public object ConvertIntermediateToXPath(IPublishedElement owner, IPublishedPropertyType propertyType,
        PropertyCacheLevel referenceCacheLevel, object inter, bool preview) => inter;

}
```

if you create a page, add a module using this property to the page, save as template, create two pages, load those pages, see that the property value is the same in both cases, equalling the last saved page.

**Comment by elit0451** [comment]
Hi @gabador-mof 👋 

Thanks for reaching out. I have a little bit of a hard time understanding how to reproduce the issue. Can you perhaps set up the test scenario in a fresh Umbraco install and record a video of how to reproduce the issue? 🙂

**Comment by gabador-mof** [comment]
Hi Elissa, 

Create a new custom property, and set its caching level to element. 

Make sure it converts into a C# object and add it to your project. 

Create a page with some elements that contain the custom property as fields added to a block list field. 

create a Content template from the Page.

Create two pages from this content template. 

Modify the custom property values in one. 

Check he returned value in the block list field elements. Both pages will return the last saved content value. 

Hope this helps. I'll record a video wen I get some time....

**Comment by elit0451** [comment]
Hi again,

I tried to replicate the issue by creating a custom property editor with 2 text fields (_"My Custom Heading Fields"_).
Set its caching level to `PropertyCacheLevel.Element;`
And then follow the rest of the steps as you described them in the comment above. ⬆️ 

As you can see from the video, I get the correct values, so there must be something in your custom code that is keeping the wrong value.


https://github.com/umbraco/Umbraco-CMS/assets/21998037/e1dee0b7-6b5c-4408-b5c7-4ef8ee73d708



For a reference, here is my custom Property Value Converter:

```c#
using Newtonsoft.Json;
using Umbraco.Cms.Core.Composing;
using Umbraco.Cms.Core.Models.PublishedContent;
using Umbraco.Cms.Core.PropertyEditors;

namespace MyProject_11_5_0.App_Plugins;

public class MyCustomHeadingFieldsValueConverter : PropertyValueConverterBase
{   
    public override bool IsConverter(IPublishedPropertyType propertyType)
        => propertyType.EditorAlias.Equals("My.Custom.Heading.Fields");

    public override Type GetPropertyValueType(IPublishedPropertyType propertyType)
        => typeof(Headings);

    public override PropertyCacheLevel GetPropertyCacheLevel(IPublishedPropertyType propertyType)
        => PropertyCacheLevel.Element;

    public override object? ConvertSourceToIntermediate(IPublishedElement owner, IPublishedPropertyType propertyType,
        object? source,
        bool preview) => source;

    public override object? ConvertIntermediateToObject(IPublishedElement owner, IPublishedPropertyType propertyType,
        PropertyCacheLevel referenceCacheLevel, object? inter, bool preview)
    {
        return JsonConvert.DeserializeObject<Headings>(inter.ToString() ?? string.Empty);
    }

    public override object? ConvertIntermediateToXPath(IPublishedElement owner, IPublishedPropertyType propertyType,
        PropertyCacheLevel referenceCacheLevel, object? inter, bool preview) => inter;
}

public class MyComposer : IComposer
{
    public void Compose(IUmbracoBuilder builder)
    {
        builder.PropertyValueConverters().Append<MyCustomHeadingFieldsValueConverter>();
    }
}

public class Headings
{
    public string Heading { get; set; }
    public string Subheading { get; set; }
}
```


I will close this as it doesn't seem to be an actual issue within Umbraco 🙂
