### ISSUE TITLE
Menu tab missing data-element="tab-{{tab.alias}}" in the dropdown list 

### ISSUE THREAD

**Issue by thomashdk** [umbraco/Umbraco-CMS#14820]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

11.4.2

### Bug summary

The menu items ind the tabs dropdown list are missing the data-element="tab-{{tab.alias}}"

![image](https://github.com/umbraco/Umbraco-CMS/assets/6445636/463d141a-e797-4626-b770-4f6142097595)

Tried th make a pull request, but I couldn't :)

### Specifics

The view for the tabs are here:

src/Umbraco.Web.UI.Client/src/views/components/tabs/umb-tabs-nav.html

### Steps to reproduce

Check tabs on a smaller screen to "create" the dropdown menu.

![image](https://github.com/umbraco/Umbraco-CMS/assets/6445636/96568529-5dd7-49f9-855d-45911dfaeaf8)

### Expected result / actual result

That the tabs has the same data-elemets as the items not in the dropdown.

**Comment by thomashdk** [comment]
> You are right 🙌 I have marked this as up for grabs for now, should also be a great first issue for someone to hopefully pick up 🤞😁

Yeah, tried to make a pull request but got and error. I will try again :)

**Comment by thomashdk** [comment]
I think I got it now :) Will try to make it and push it

**Comment by Zeegaan** [comment]
@thomashdk all good, I'm here to help! No it should still be there 🤔 
This is me on the the `contrib` branch: 
![image](https://github.com/umbraco/Umbraco-CMS/assets/70372949/182dc132-4a70-467b-b8f1-99e470190145)
Second last option is the Client project 📄

**Comment by thomashdk** [comment]
I think I did it :) !

**Comment by Zeegaan** [comment]
@thomashdk great to hear, I have taken the liberty to link to the issue from your PR, so we can closed this when it gets merged 🙌
