### ISSUE TITLE
Umbraco Site Error: Empty page

### ISSUE THREAD

**Issue by biapar** [umbraco/Umbraco-CMS#14850]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

Umbraco Site

### Bug summary

The progress page is empty into the Umbraco web site.

<img width="1223" alt="image" src="https://github.com/umbraco/Umbraco-CMS/assets/661517/7aaa01ec-3d9c-44ea-92a1-1021ab762a92">

### Steps to reproduce

The progress page is empty: https://our.umbraco.com/download/releases/progress

**Comment by Zeegaan** [comment]
Heyo, thanks for the heads up! But this is not the issue repository for the `our` website 😁 
I have added the new 12.3 release now, so it should show up there once the caches refresh 👍
