### ISSUE TITLE
[BUG]: Couldn't complete attended migration from Umbraco 12 to Umbraco 14.

### ISSUE THREAD

**Issue by AndyButland** [umbraco/Umbraco-CMS#14860]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

Umbraco 14 Preview 3

### Bug summary

I have an Umbraco 12 site and attempted to upgrade to Umbraco 14 using an attended migration.

On accessing the `/umbraco/` path I get this error: 

```
Invalid object name 'umbracoOpenIddictApplications'.
```

### Steps to reproduce

1. Create an Umbraco 14 site and connect it to a database from an Umbraco 12 site.
2. Browse to `/umbraco/`.
3. See error

### Expected result / actual result

I'm not sure I should expect this to work.  It looks like there's a catch-22 here - to login and run the migration we need some tables to exist, but these tables need to exist to login.

My guess is that this wouldn't be an issue if I had migrated through Umbraco 13, and when 14 is out, perhaps that'll be the recommended approach.  But in this preview phase it could be people will look to update direct from 12, so maybe it's an issue that can be resolved.

**Comment by elit0451** [comment]
Fixed in https://github.com/umbraco/Umbraco-CMS/pull/14945

**Comment by AndyButland** [comment]
I'm not sure the PR referenced addressed this issue @elit0451 / @Zeegaan.  It fixed the issue with unattended migrations, but don't think it would have had any effect on this one.

**Comment by Zeegaan** [comment]
@AndyButland are you using the new backoffice here? 😁 I might have missed something when testing then 🤔

**Comment by AndyButland** [comment]
It didn't get that far.  When trying to access `/umbraco/` I got the error above.  Then I configured to use unattended upgrades, and found the second issue - which you've fixed.

It might well be just that this is expected not to work yet, but I couldn't see anything in your fix that would have resolved this issue.

**Comment by Zeegaan** [comment]
Yes when migrating right now you have to manually navigate to the `/install` endpoint, atleast when using the old backoffice 🙈

**Comment by AndyButland** [comment]
OK, that was probably all it was then.   Thanks.
