### ISSUE TITLE
Umbraco V7.5.11 upgrade doesn't actually work

### ISSUE THREAD

**Issue by Attackmonkey** [umbraco/Umbraco-CMS#14873]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

7.15.11

### Bug summary

I have a client with EOL V7 support, and it states that they have to be on the latest version of V7 for the support to be valid. They are currently on 7.15.10 and we noticed that 7.15.11 was released recently. However, attempting to upgrade from v7.15.10 to v7.5.11 in visual studio via nuget fails with the error:

`Unable to find a version of 'Microsoft.CodeDom.Providers.DotNetCompilerPlatform' that is compatible with 'UmbracoCms 7.15.11 constraint: Microsoft.CodeDom.Providers.DotNetCompilerPlatform (>= 2.0.1 && < 3.0.0)'.`

### Specifics

We have tried this with four V7 websites, all at various versions, and none of them are able to apply the latest update via nuget in Visual Studio. We've also had various developers in various locations reproduce the same issue.

To confirm this was an issue with the package, we set up a brand new V7.5.10 website and attempted to apply the 7.5.11 update and got the same error, so it's definitely the update and not anything in our code.

Oddly, despite the error saying it can't find a compatible version, version 2.0.1 of the compiler is already installed on the site as a package from the original Umbraco install, and there are no other packages that come between 2.0.1 and 3 on nuget.

### Steps to reproduce

To replicate with a fresh install, do the following:

- Create an new web application project in VS2022
- Install Umbraco 7.15.10 via nuget
- Run the site and setup a local copy of umbraco
- In the nuget package manager in VS2022 attempt to upgrade the site to 7.15.11
- You will see the error in the package manager output window after it has attempted to gather the dependencies

**UPDATE:** I think the nuget package is fundamentally broken, if you try and do a fresh install of 7.15.11 you get the following error:

`Unable to find a version of 'LightInject' that is compatible with 'UmbracoCms.Core 8.5.0 constraint: LightInject (>= 5.4.0 && < 5.999999.0)'.	`			

Which we shouldn't get, because the package is targeting 7.X not 8.

### Expected result / actual result

Running the nuget upgrade should update the site to 7.15.11 successfully.

**Comment by bergmania** [comment]
Hi @Attackmonkey..

You are mentioning 7.5.10 and 7.5.11, but Im unsure if you really are talking about 7.15.11 that was released recently or the 7.5.11 that was released back end 2017.

Can you confirm both of these should be 7.15.*  or are you trying to update from 7.5.10 (Released February 21st 2017) to 7.15.11 (Released September 5th 2023)

**Comment by bergmania** [comment]
I can see in the message it says 7.15.11, but please confirm you are upgrading from 7.15.10 and not 7.5.10

**Comment by bergmania** [comment]
In general the error message looks completely weird. Why does it mention UmbracoCms.Core 8.5.0? Did you update part of the project to Umbraco 8?

**Comment by Attackmonkey** [comment]
@bergmania sorry, meant 7.15.10, will update my post! I get the V8 related error attempting to install 7.15.11 into an empty project. The other error about Roslyn is when you try and update from any version of V7 it looks like.

**Comment by bergmania** [comment]
The changes between 7.15.10 and 7.15.11 is here https://github.com/umbraco/Umbraco-CMS/compare/release-7.15.10...release-7.15.11

I can't see anything that relates to the error

**Comment by Attackmonkey** [comment]
Me neither, that's what's really odd. Have you tried creating a new V7.15.10 site and using nuget to update to 7.15.11?

**Comment by bergmania** [comment]
I just tested out installing 7.15.11 into an empty ASP.NET project. This works as expected. 

Will test out an umbraco fra 7.15.10 now

**Comment by Attackmonkey** [comment]
What version of .net does your working install of 7.15.11 target? Is it 4.5.2 or 4.7.2?

**Comment by bergmania** [comment]
Seems to be 4.6.1 that vs 2017 installed with it

**Comment by Attackmonkey** [comment]
Hmmm, OK the sites we're upgrading are all targeting 4.7.2. I've just done a fresh install of 7.15.11 in a blank project targeting 4.5.2 and worked as expected. It's odd that all the other upgrades we installed on the site worked OK targetting 4.7.2, but 7.15.11 doesn't. I'm going to try a few things, will report back!

**Comment by Attackmonkey** [comment]
When upgrading to 7.15.11, it doesn't seem to matter what .net version we target, even 4.5.2 which will let you install 7.15.11 from empty, won't let you upgrade to it from an earlier version!

**Comment by bergmania** [comment]
What version of MySql.Data do you project reference?

**Comment by Attackmonkey** [comment]
Was just about to post about that, it looks like CmsCore 7.15.11 wants exactly 6.9.9, which isn't on nuget any more. The other umbraco versions specify > 6.9.9 and less that 7.

**Comment by bergmania** [comment]
It's still on nuget, just unlisted. https://www.nuget.org/packages/MySql.Data/6.9.9

**Comment by bergmania** [comment]
I can confirm I get into troubles updating a 7.15.10 site to 7.15.11 if MySql.Data is 6.9.12. 

Works fine to update if MySql.Data is 6.9.9, before I do the update.

**Comment by bergmania** [comment]
What I did was not that complicated

* Installed 7.15.10
* Updated packages.config to have version 6.9.9 of MySql.Data instead of 6.9.12 
* Tested 7.15.10 still worked with this
* Updated to 7.15.11 (without any problems)

@nul800sebastiaan, can you point me to some insights about why that dependency was limited?

**Comment by Attackmonkey** [comment]
Yeah, I think all my steps were getting past the things masking the real issue of the MySQL.Data reference :)

**Comment by nul800sebastiaan** [comment]
_Note: I didn't read the discussion, looks like you did some of this already, scrolling through the comments_

**Comment by Migaroez** [comment]
> Yeah, I think all my steps were getting past the things masking the real issue of the MySQL.Data reference :)

Hey Tim, did you manage to get it all to work with the changes to Mysql.Data?

**Comment by Attackmonkey** [comment]
Yup, downgrading the MySQL version across all projects in the solution allowed the upgrade to run!
