### ISSUE TITLE
Issue Content delivery API v12.2.0 getting home node

### ISSUE THREAD

**Issue by WolfieIntracto** [umbraco/Umbraco-CMS#14875]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

12.2.0

### Bug summary

Hi,
We used to be able to request the homepage using the following url with the content delivery api;
"/umbraco/delivery/api/v1/content/item/" 
Culture and hostname is set too / in Umbraco on the homepage node.

Since upgrading to v12.2.0 this isn't working anymore. We get an empty array as response.

### Steps to reproduce

On Umbraco v12.1.2 go to "/umbraco/delivery/api/v1/content/item/"  this returns data. (If it is set in Umbraco)
On Umbraco v.12.2.0 go to "/umbraco/delivery/api/v1/content/item/" this returns no data

### Expected result / actual result

Same as above

---
_This item has been added to our backlog [AB#33245](https://dev.azure.com/umbraco/243e7927-03b2-44e2-908f-d4ac7ea5daaa/_workitems/edit/33245)_

**Comment by andr317c** [comment]
Hey! Thanks a lot for posting this issue 😄, I was able to reproduce it. I will mark this issue as a sprint candidate! 🐛

**Comment by elit0451** [comment]
Fixed in #14987
