### ISSUE TITLE
URL replacing doesn't work as expected

### ISSUE THREAD

**Issue by CimplexAB** [umbraco/Umbraco-CMS#14874]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

12.1.2

### Bug summary

When a node name contains a special character like '°' and ö, the URL replacing to ascii characters doesn't work as expected.  

### Steps to reproduce

In appsettings.config:

```
"Umbraco": {
  "CMS": {
      "RequestHandler": {
        "AddTrailingSlash": true,
        "ConvertUrlsToAscii": "try",
        "EnableDefaultCharReplacements": false
      }
  }
}
```

Create a node with name: Hörnbeslag 90°

### Expected result / actual result

The expected url would be /hornbeslag-90/

but the actual result is /hörnbeslag-90/

If I remove the special character "°" so that my node name is "Hörnbeslag 90" the URL transform correct to /hornbeslag-90/

**Comment by kjac** [comment]
Hi @CimplexAB,

I can reproduce this. Looks like the ASCII conversion gets confused by the trailing `°` char in this particular case.

I'll investigate further to see if this is a general issue with trailing non-ascii chars, or if this is a one-off fluke. In the mean time, here are some options for you:

### Enable `EnableDefaultCharReplacements`

You have `EnableDefaultCharReplacements` set explicitly to `false` in your config. When this is set to `true`, the URL is calculated correctly (in respect to the built-in rules, where `ö` is replaced with `oe`):

<img width="322" alt="image" src="https://github.com/umbraco/Umbraco-CMS/assets/7405322/d1a8fbc8-824b-4ca7-9242-79f549de042c">

### Remove the trailing `°` char

The URL is calculated correctly when the `°` char is removed from the node name:

<img width="287" alt="image" src="https://github.com/umbraco/Umbraco-CMS/assets/7405322/92991c65-cc02-46af-91ce-55c3a505308a">

### Use `UserDefinedCharCollection` 

If `EnableDefaultCharReplacements` is not an option (i.e. if you don't want `ö` is replaced with `oe`), you can define your own replacements in the `UserDefinedCharCollection`.

Given this config:

```json
  "RequestHandler": {
	"ConvertUrlsToAscii": "try",
	"AddTrailingSlash": true,
	"EnableDefaultCharReplacements": false,
	"UserDefinedCharCollection": [
	  {
		"Char": "ö",
		"Replacement": "o"
	  }
	]
  },
```

... the URL is calculated correctly:

<img width="259" alt="image" src="https://github.com/umbraco/Umbraco-CMS/assets/7405322/2aca0ced-7b64-407a-8e5d-17027371be93">

For reference, here are the built-in rules: https://github.com/umbraco/Umbraco-CMS/blob/contrib/src/Umbraco.Core/Configuration/Models/RequestHandlerSettings.cs#L20

**Comment by kjac** [comment]
Hi again.

We've had a talk about this issue on the team, and for the time being we're not going to solve it. Please refer to the provided workarounds.

We need to get rid of the Umbraco flavored ASCII replacement in favor of something else. This is a long term task, though, as it potentially breaks page URLs. We need to come up with a plan that does not reflect negatively on existing sites.
