### ISSUE TITLE
RTE toolbar jumps on top of the screen when out of view

### ISSUE THREAD

**Issue by ssougnez** [umbraco/Umbraco-CMS#14891]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

12.2.0

### Bug summary

I'm using an RTE inside a grid layout, and when I press enter while the toolbar is not visible (because of scrollbar), the toolbar jumps on the top of the screen.

### Steps to reproduce

* Configure a RTE inside a grid layout.
* Insert enough content in the RTE to overflow it for the toolbar to disappear (because outside of the viewport on the top)
* Save the page and reload it (just to be sure)
* Go into the RTE and scroll down enough for the toolbar to disappear
* Press Enter

### Expected result / actual result

Expected:

![image](https://github.com/umbraco/Umbraco-CMS/assets/10199821/27611a5b-f10f-4b9e-a743-fff3afe2c091)

Actual:

![image](https://github.com/umbraco/Umbraco-CMS/assets/10199821/393c4d6a-96f5-4f83-8cc4-cb140a63e236)

**Comment by netcamo** [comment]
Dear @ssougnez !

Thank you for your report. I have tried to reproduce but I was not successful. Could you please check out how I do and confirm?

1. I have a grid layout with RTE.
2. I copy text from https://loremipsum.io/generator/?n=20&t=p 
3. I paste it to the RTE and click save.
4. I reload and scroll down
5. I push enter  (At this step everything works as expected for me)

Also could please share "RichTextEditor": { ... }  from your appsetting.json  ? You are probably using some plugins etc. and one of them might cause this issue. 

Thank you in advance!

Sincerely,
Jey

**Comment by ssougnez** [comment]
Hello,

your reproduction step seems right to me. Note that I didn't try it with a fresh new install of Umbraco, maybe I should.
As for my configuration:

```
"RichTextEditor": {
        "Plugins": [
          "anchor",
          "charmap",
          "table",
          "lists",
          "advlist",
          "autolink",
          "directionality",
          "searchreplace",
          "fullscreen",
          "visualchars",
          "nonbreaking"
        ],
        "ValidElements": "*[*]",
        "InvalidElements": "font",
        "CustomConfig": {
          "entity_encoding": "raw",
          "visualchars_default_state": "false",
          "table_toolbar": "",
          "style_formats": "[ { \"title\": \"Headers\", \"items\": [ { \"title\": \"Header 1 (H1)\", \"block\": \"h1\" }, { \"title\": \"Header 2 (H2)\", \"block\": \"h2\" }, { \"title\": \"Header 3 (H3)\", \"block\": \"h3\" }, { \"title\": \"Header 4 (H4)\", \"block\": \"h4\" } ] }, { \"title\": \"Links\", \"items\": [ { \"title\": \"Call to action\", \"selector\":\"a\", \"classes\":\"call-to-action\", \"attributes\": { \"data-event\": \"CTA\", \"data-event-label-property\": \"href\" } } ] }, { \"title\": \"Panels\", \"items\": [ { \"title\":\"Success\", \"block\":\"div\", \"classes\": \"pnl pnl_success\" }, { \"title\":\"Information\", \"block\":\"div\", \"classes\": \"pnl pnl_info\" }, { \"title\":\"Warning\", \"block\":\"div\", \"classes\": \"pnl pnl_warning\" }, { \"title\":\"Error\", \"block\":\"div\", \"classes\": \"pnl pnl_error\" } ] }, { \"title\": \"Paragraphs\", \"items\": [ { \"title\": \"P\", \"block\": \"p\" }, { \"title\": \"DIV\", \"block\": \"div\" } ] }, { \"title\": \"Other\", \"items\": [ { \"title\": \"Table of content\", \"selector\": \"ul\", \"classes\": \"table-of-content\", \"attributes\": { \"data-event\": \"Table of content\", \"data-event-selector\": \"a\", \"data-event-label-property\": \"innerText\" } } ] }   ]"
        }
      }

```

**Comment by netcamo** [comment]
Hi @ssougnez  

Thank you! I have been able to reproduce it and we will need to investigate it further.
 
We will give you information about it as soon as possible.

Thank you again for bringing it to our attention!

Have a wonderful day!

**Comment by ssougnez** [comment]
Cool, thanks :-)

If it can help you, I noticed that sometimes, the toolbar jumps on the top during the loading. It's not very replicable but I feel that when I scroll the page while RTE are being initialized, there is a chance that the toolbar will jump.

**Comment by netcamo** [comment]
Dear @ssougnez 
I hope everything is going well for you!

I have new information about this issue:
The Grid Layout has been marked as obsolete and development on the property editor has been discontinued. It will be removed as a core property editor with the release of Umbraco 14 and it is already hided by default in the Umbraco 12. We recommend you using Block Grid instead which doesn't have this reported issue.


Thank you again for reporting this issue and I wish you a wonderful week ahead! 😄

**Comment by ssougnez** [comment]
Ah. I was not aware of the Grid layout replacement.

So I guess I'll add it to my long list of stuff that I have to migrate ^^

Is there already some information on the new Block grid thingy?

Thanks

**Comment by netcamo** [comment]
Dear @ssougnez,
You can find more information about Block grid by following [link](https://docs.umbraco.com/umbraco-cms/fundamentals/backoffice/property-editors/built-in-umbraco-property-editors/block-editor/block-grid-editor).

Additionally, check out [Deep Dive: Block Grid Editor Part 1](https://umbraco.com/blog/deep-dive-block-grid-editor-part-1/) at Umbraco blog.

**Comment by ssougnez** [comment]
One last question about that subject then you can close it.

Is there some kind of migration path from the old grid layout to the new one?
As the application I'm working one has been created with Umbraco 7 and all pages are composed of Grid layout, so if there is no migration path, it's like a major issue for me :-)

**Comment by netcamo** [comment]
Dear @ssougnez,

Unfortunately, there is not a migration path  from the old grid layout to the new one. Maybe there is some community package that can help with it but it is not provided by Umbraco.

I hope you get to solve the issue and in case you do, it would be awesome if you could also make a blog post about it! 

I wish you good luck and a wonderful week ahead! 😃

**Comment by ssougnez** [comment]
That's a shame.
It's a bit weird to propose a feature so widely use than the Grid Layout then decommission it without any official migration path...
Anyway, I'll guess I'll have to figure it out by myself.

Thanks for the answer

**Comment by ssougnez** [comment]
That's a really great news, I'll have a look at this.
