### ISSUE TITLE
Left menu above RTE in full screen

### ISSUE THREAD

**Issue by ssougnez** [umbraco/Umbraco-CMS#14890]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

12.2.0

### Bug summary

When using the full screen mode of the Rich text editor, the left menu overlaps.

### Specifics

I'm using the RTE inside a grid layout.

### Steps to reproduce

Simply use an RTE inside of a grid layout and pass in full screen.
For now, I managed to fix it with the following CSS:

```
#leftcolumn {
    z-index: 0;
}
```

However, this applies globally.
Note that the left menu behaves as expected, but I guess this z-index (1100) is defined for a reason.
Also note that the z-index of the RTE is well set on 1200 but still appears below.

### Expected result / actual result

**Expected:**

![image](https://github.com/umbraco/Umbraco-CMS/assets/10199821/e82ef1f0-47b9-46bc-a6ea-e49fb3eb344e)

**Actual:**

![image](https://github.com/umbraco/Umbraco-CMS/assets/10199821/d6597c64-3b8e-4a36-9969-227b9cce4d1e)

**Comment by ssougnez** [comment]
Well, I would be OK to write a PR for this, but I'm not sure that just removing the z-index of the leftcolumn element is a good idea. This scenario are very difficult to estimate as the z-index might be there for a specific case where the left-menu is needed to be on top on something else.

Can anyone with more experience than me with Umbraco tells me whether this z-index is required?

**Comment by netcamo** [comment]
Hi @ssougnez, Thank you for your report and initiative! I have been able to reproduce the issue. 

About the question you asked,  I am looking into it and will come back to you as soon as I have any answer to it. 

Have a wonderful day!

**Comment by netcamo** [comment]
Hi @ssougnez again, It would be wonderful if you could go ahead with making the PR for this. PR team will be happy to test the solution 😄 

Thank you and have an _um_bazing day!

**Comment by ssougnez** [comment]
Ok, I'll try to find time for this.

If anyone wants to do it instead, don't wait for me ;-)

**Comment by jannikanker** [comment]
@ssougnez if you haven't found the time yet, I'd like to have a look?

**Comment by ssougnez** [comment]
Go ahead, I really have a lot to do at work and I don't know when I'll be able to have a look at this.

Thanks a lot !

**Comment by jannikanker** [comment]
@ssougnez Ahem... Any tips on enabling the fullscreen option on the datatype? Can't seem to find it :-(

**Comment by jannikanker** [comment]
@netcamo Interestingly enough, the leftcolumn z-index was bumped from 20 to 1100 all the way back in 2017, with this commit message:

"U4-10225: Bumps z-index of #leftcolumn

http://issues.umbraco.org/issue/U4-10225

This bumps the z-index of #leftcolumn, so the notifications don't get in the way."

Did the old v7 notifications perhaps span the entire window width? Today notifications are contained within the contentcolumn, so... Yeah. I'm about to create a PR that adjusts leftcolumn z-index down to 0. My tests show no change in appearance nor functionality with z-index at 0, but a part of me wonders if allowing just a liiittle leeway would be smart. Like, setting it to 5. Then again, that would probably just be confusing for the next guy.

**Comment by nul800sebastiaan** [comment]
Fixed in https://github.com/umbraco/Umbraco-CMS/commit/6b599b641c3a9b5453eac7d3d49d0ba36861ce5b
