### ISSUE TITLE
Rich Text Editor - js error preventing the editor from showing up in the backoffice on server

### ISSUE THREAD

**Issue by solarrally** [umbraco/Umbraco-CMS#14902]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

11.5.0

### Bug summary

I have a problem with the RTE on v11.5. 

On local everything is fine, the editor works as expected. 
When deployed however, there is a javascript error in the theme.min.js file which is blocking the editor and it is not rendered

![image](https://github.com/umbraco/Umbraco-CMS/assets/63998498/accffbe4-2220-4b1c-9cf0-a3b54c276c33)

![image](https://github.com/umbraco/Umbraco-CMS/assets/63998498/3e3829dd-e541-4a3b-a895-2c632f440733)

### Specifics

Tried clearing browser cache, cookies, different browsers, redeploying - no difference.

### Steps to reproduce

![image](https://github.com/umbraco/Umbraco-CMS/assets/63998498/f89f8ecd-d4b5-4c94-9bc8-ce608bdf2661)

![image](https://github.com/umbraco/Umbraco-CMS/assets/63998498/1a51aff1-6cce-4908-93ac-265d43a84a41)

There are no customizations to the RTE.

**Comment by netcamo** [comment]
Hi @solarrally, Thank you for reporting the issue!

**Comment by solarrally** [comment]
Hi @netcamo, hope you are well too!

The project is deployed as self hosted to a Windows Server 2022 Standard, under IIS. 
I can't think of anything else specific, the project is rather simple.

Thank you for your time!

**Comment by netcamo** [comment]
Hi!
Unfortunately, we haven't received any response and information for more than 2 weeks so I will go ahead and close this issue.

You are welcome to reopen the issue if you have any updates on it.

I wish you a wonderful week ahead! 😄
