### ISSUE TITLE
Issue with URL in Multi URL Picker

### ISSUE THREAD

**Issue by JeroenRoos** [umbraco/Umbraco-CMS#14901]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

12.2.0

### Bug summary

When getting the URL from a Content Node from a Multi URL Picker, the value "https' is added twice. I see this issue both the local environment and the production environment.
This will be the URL: _https://https//localhost:44315/th/news/_, which will give an error because this isn't a valid URL. This happens on multiple places where we use Multi URL Picker. 

I think it's only an issue with the Multi URL Picker, because on other places, with normal Content Pickers, we have valid URL's. 

### Steps to reproduce

When choosing a Content Node through an Multi URL Picker, an additional https appears in the URL, making the URL invalid.

Also when debugging, I can see that the object that is given with the Multi URL Picker, already has this additional https in front. This is before we do anything with this object, so I'm sure it's not something we added ourself by accident:

![image](https://github.com/umbraco/Umbraco-CMS/assets/25620488/61a948f6-7909-4677-b279-be8b2ef6fc87)

**Comment by Migaroez** [comment]
Hey Jeroen

Thank you for raising this issue, after some investigation I cannot seem to reproduce this.
- I created a doctype with 1 property called `mup`, created a document and selected 2 nodes 
![image](https://github.com/umbraco/Umbraco-CMS/assets/6025797/94a98d9f-ebad-4562-be97-5dd33d5fbbd1)
- Added a template with the following code
```
@foreach (var link in Model.Mup)
{
    <p>@JsonConvert.SerializeObject(link)</p>
}
```
It renders as follows
![image](https://github.com/umbraco/Umbraco-CMS/assets/6025797/74013f1d-ae9d-4708-9880-63b3a71409e7)

Do you have any idea where we might be testing things differently?

Have a wonderful weekend!

**Comment by JeroenRoos** [comment]
Hi @Migaroez, I don't know where we might be testing differently. One thing I see is that you appear to be receiving relative links, where I'm getting absolute links. What I'm also seeing on our website, is that it is only happing for the following culture: Thai (Thailand) - th-TH.

**Comment by JeroenRoos** [comment]
I created a new issue for the comments above, since this issue is outdated now: 

#14946
