### ISSUE TITLE
Multiple scheduled content items do not publish simultaneously

### ISSUE THREAD

**Issue by scottmhallett** [umbraco/Umbraco-CMS#14909]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

10.6.1

### Bug summary

When using Schedule to schedule a publishing date and time for a content item, if more than one item is schedule for the same time, not all items will post.

For example 3 items at 8:00pm EST, only one item posts. 

### Specifics

Verified this in Umbraco 10.6.1 in several time zones. 

This was also verified in Umbraco 10.7 by the Umbraco Support team.

### Steps to reproduce

Create at least two content items scheduled to post at the same time (we tested three).

Observe which items were posted when the assigned post date and time has passed.

### Expected result / actual result

All items should post at the scheduled time.

**Comment by netcamo** [comment]
Hi @scottmhallett
I hope everything is going well for you!

Thank you for reporting the issue! 😄 

I have tried to reproduce it with the most basic setup but my attempt was not successful. 

- I have created Document type without any properties and made 3 content out of this document types. I scheduled - them to publish at the same time and they all have been published.
- I have also used v10.6.1


Could you please give me more information on Document type, Content tree etc. that could help me to reproduce the problem?

**Comment by scottmhallett** [comment]
Our example was using a uSkinned blog component. However, we also brought this issue to Umbraco support and confirmed they were able to replicate with 10.7.

Perhaps the content of a document type with no properties is too simplistic to trigger the issue?
