### ISSUE TITLE
EventState is not kept between SavingDictionaryItem and SavedDictionaryItem events

### ISSUE THREAD

**Issue by lauraneto** [umbraco/Umbraco-CMS#14907]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

8.18.9

### Bug summary

The `EventState` is lost between the `SavingDictionaryItem` and `SavedDictionaryItem` events.
This does not happen when the item is first created, it only happens when attempting to save after that.

Tried it in an Umbraco 12 install, using notifications, and there it worked correctly.

### Steps to reproduce

1. Set up a new Umbraco 8 install (default installation, no content required)
2. Create a new C# file in the project and add the following content:
```csharp
using Umbraco.Core;
using Umbraco.Core.Composing;
using Umbraco.Core.Events;
using Umbraco.Core.Models;
using Umbraco.Core.Services;
using Umbraco.Core.Services.Implement;

namespace Umbraco8.Web
{
    [RuntimeLevel(MinLevel = RuntimeLevel.Run)]
    public class TestComposer : ComponentComposer<TestComponent> { }

    public class TestComponent : IComponent
    {
        public void Initialize()
        {
            LocalizationService.SavingDictionaryItem += SavingDictionaryItem;
            LocalizationService.SavedDictionaryItem += SavedDictionaryItem;
        }

        private static void SavingDictionaryItem(ILocalizationService sender, SaveEventArgs<IDictionaryItem> e)
        {
            e.EventState["key"] = "This is a test!";
        }

        private static void SavedDictionaryItem(ILocalizationService sender, SaveEventArgs<IDictionaryItem> e)
        {
            var test = e.EventState["key"];
        }

        public void Terminate()
        {
            LocalizationService.SavingDictionaryItem -= SavingDictionaryItem;
            LocalizationService.SavedDictionaryItem -= SavedDictionaryItem;
        }
    }
}
```
3. Boot up the website
4. Create a new dictionary item (this one works as expected!)
5. Save the same dictionary item (again) 💥
Verify that you get a `System.Collections.Generic.KeyNotFoundException: 'The given key was not present in the dictionary.'` due to the `EventState` being empty.

### Expected result / actual result

Expected: The `EventState` is kept between the `SavingDictionaryItem` and `SavedDictionaryItem`
Actual: `EventState` is empty on `SavedDictionaryItem`

**Comment by kjac** [comment]
Hi @lauraneto,

Thanks for raising this - and with a PR to match, even 😍 

The Core Collabs team will review your PR and get back to you on this one.

**Comment by nul800sebastiaan** [comment]
Fixed in https://github.com/umbraco/Umbraco-CMS/pull/14912
