### ISSUE TITLE
Some media cards are very high

### ISSUE THREAD

**Issue by bjarnef** [umbraco/Umbraco-CMS#14917]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

12.2.0

### Bug summary

When uploading some media in portrait format, some media cards may be very high.

![image](https://github.com/umbraco/Umbraco-CMS/assets/2919859/597d6955-f8c4-4fb2-88b6-7da180173fb0)

I think we should strive for a maximum height.

![image](https://github.com/umbraco/Umbraco-CMS/assets/2919859/1f4aec42-c117-4e49-a816-afa750f8f3e4)
 

### Steps to reproduce

Uploading some images in portrait format with small with and large height.

**Comment by netcamo** [comment]
Hi @bjarnef  

Thank you very much for bringing it to our attention!

@nielslyngsoe do you have any concerns on the proposed way of solution?

**Comment by netcamo** [comment]
Hi @bjarnef, I hope everything is going well for you!


Thank you for reporting the issue!

I have tried to reproduce it and uploaded some images in portrait format but didn't have the same result as you. Could you please send the images that you have uploaded?

**Comment by netcamo** [comment]
Hi!
Unfortunately, we haven't received any response and information for more than 2 weeks so I will go ahead and close this issue.

You are welcome to reopen the issue if you have any updates on it.

I wish you a wonderful week ahead! 😄

**Comment by nielslyngsoe** [comment]
@bjarnef I think this makes good sense, feel free to go ahead and make a PR for such a correction :-)
