### ISSUE TITLE
Resend Invitation Fails, button shows "X"

### ISSUE THREAD

**Issue by Myster** [umbraco/Umbraco-CMS#14949]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

10.7.0, also reported in 10.5.0, and 10.3.2

### Bug summary

After sending an invite we cannot click "Resend Invitation"
I am not aware in our case what the user did in the interim, but [this forum post](https://our.umbraco.com/forum/using-umbraco-and-getting-started/110436-bug-in-backoffice-user-invites) says the bug occurs if the user starts but does not complete registration

### Specifics

URL: https://localhost:44310/umbraco#/users/users/user/33?orderBy=Name&orderDirection=Ascending&pageNumber=1
Image (this X shows up for a second or 2 after you click "Resend Invitation"): 
![image](https://github.com/umbraco/Umbraco-CMS/assets/354777/9a0bef8c-9cf2-4f15-835d-d11c774e6ae9)
API URL: https://localhost:44310/umbraco/backoffice/umbracoapi/users/PostInviteUser
API Payload (formatted): 
```
{
    "id": 73,
    "parentId": -1,
    "name": "__REDACTED__",
    "username": "admin@__REDACTED__",
    "culture": "en-US",
    "email": "admin@__REDACTED__",
    "startContentIds":
    [],
    "startMediaIds":
    [],
    "userGroups":
    [
        "__REDACTED__"
    ],
    "message": "Resending invitation...",
    "key": "00000049-0000-0000-0000-000000000000"
}
```
API Response Content:
```
)]}',
{"Message":"The request is invalid.","ModelState":{"Email":["A user with the email already exists"]}}
```
Note: there is only one user with the email address (the one I'm trying to resend)

### Steps to reproduce

In back office Invite User, Click invite link, but don't complete (not sure exactly here)
In back office Resend Invite.

### Expected result / actual result

The invite should be resent.

**Comment by Myster** [comment]
Note: a work-around is to delete and recreate the user, which you can do if they have never logged in but not after they've logged in.

**Comment by rammi987** [comment]
Also an issuse in 12.2.0.

**Comment by DanDiplo** [comment]
I've also seen this fail, but the reason may be different. In the Umbraco trace log I see:

`VerifyUserTokenAsync() failed with purpose: "EmailConfirmation" for user.`

This occurs on `Umbraco.Cms.Web.BackOffice.Controllers.BackOfficeController.VerifyInvite`

`Could not verify email, Error: "Invalid token", Token: "12%7CQ2ZESjhE.....etc."`

**Comment by emmagarland** [comment]
@DanDiplo I'm also currently trying to debug this issue on v10.8.2.

Emma
