### ISSUE TITLE
12.2.0 - Issue with getting Content URL, when in the th-TH culture

### ISSUE THREAD

**Issue by JeroenRoos** [umbraco/Umbraco-CMS#14946]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

Umbraco 12.2.0

### Bug summary

When getting an URL from a page, when in the culture _th-TH_, an invalid URL is returned.

For example:
![image](https://github.com/umbraco/Umbraco-CMS/assets/25620488/ef4b03ec-52c5-4466-b5ac-d4334a2b9c56)

When this is the result from the English page:
![image](https://github.com/umbraco/Umbraco-CMS/assets/25620488/14a8c969-4396-4e9a-b3b7-6cec0b0e9387)

Both the Absolute and the Relative URL are incorrect.

This issue is also raised in this issue I created earlier, but in the previous issue I though the issue was something else. In this old issue I also added a comment with basicaly the same information as this issue.

Old issue: #14901

### Steps to reproduce

I created a new clean Umbraco instance. And added only the following cultures:
![image](https://github.com/umbraco/Umbraco-CMS/assets/25620488/076d768a-2397-4833-bf85-70ba1d9ddcaf)

I created a single Document type with no properties, which is allowed as root, which is allowed to have itself as children, and which is allowed to vary by culture.

![image](https://github.com/umbraco/Umbraco-CMS/assets/25620488/01065a57-509b-4b56-ae47-23525daad9e7)

Then I created 2 content nodes in the English culture like this:

![image](https://github.com/umbraco/Umbraco-CMS/assets/25620488/a24c7bf2-784a-4f7a-8ef9-0e98a695ac48)

And I created 2 content nodes in the Thai culture like this:

![image](https://github.com/umbraco/Umbraco-CMS/assets/25620488/aab7f167-4636-410c-a692-ae723d6e33dd)

All I'm doing in the view is print both the absolute and relative URL of the current page, with no other changes:

```
@inherits Umbraco.Cms.Web.Common.Views.UmbracoViewPage<ContentModels.Content>
@using ContentModels = Umbraco.Cms.Web.Common.PublishedModels;
@{
    Layout = null;
}

<p>Absolute URL: @Model.Url(mode: UrlMode.Absolute)</p>
<p>Relative URL: @Model.Url(mode: UrlMode.Relative)</p>
```

This gives the following result on a English page:
![image](https://github.com/umbraco/Umbraco-CMS/assets/25620488/72c2451b-9fca-4519-96be-8156b3a7a419)

And the following result on a Thai page:
![image](https://github.com/umbraco/Umbraco-CMS/assets/25620488/7ddddd90-5176-4b66-be17-bd471babcbeb)

Could you let me know if you can reproduce this issue with the additional information I gave?

---
_This item has been added to our backlog AB#33666_

**Comment by andr317c** [comment]
Hey! Thanks a lot for posting this issue, I was able to reproduce the issue on 11.5.0 and 12.2.0. I tested with English(United States) en-US, Danish(Denmark) da-DK, and Thai(Thailand) th-TH.

I used this template for testing(I used a MultiUrlPicker):
```
@using Umbraco.Cms.Web.Common.PublishedModels;
@using Umbraco.Cms.Core.Models
@using Newtonsoft.Json;
@inherits Umbraco.Cms.Web.Common.Views.UmbracoViewPage<ContentModels.TestDocument>
@using ContentModels = Umbraco.Cms.Web.Common.PublishedModels;
@{
	Layout = null;
}

@{
    var links = Model.Value<IEnumerable<Link>>("multiPicker");
    if (links.Any())
    {
        <ul>
            @foreach (var link in links)
            {
                <h4> @link.Name </h4>
                <p>URL: @link.Url</p>
            }
        </ul>
    }
}

<h4>Current page urls:</h4> 
<p>Absolute URL: @Model.Url(mode: UrlMode.Absolute)</p>
<p>Relative URL: @Model.Url(mode: UrlMode.Relative)</p>
```

Here is what I found:

English:
![image](https://github.com/umbraco/Umbraco-CMS/assets/73799582/2648e410-5670-4fdc-955e-8f66a8d946b5)

Danish:
![image](https://github.com/umbraco/Umbraco-CMS/assets/73799582/c7093273-f3da-4bad-ab41-0af710321472)

Thai: 
![image](https://github.com/umbraco/Umbraco-CMS/assets/73799582/f0aac80d-b71e-4219-8fcb-44f5180adbcc)

As you can see, there is an issue with the URLs related to the Thai language

The issue occurs with iso-codes: 'th' and 'th-TH'

I will go ahead and set this as a sprint candidate.

**Comment by Matthew-Wise** [comment]
Working on this

**Comment by nul800sebastiaan** [comment]
Fixed in https://github.com/umbraco/Umbraco-CMS/pull/14976

**Comment by vlaellayug** [comment]
Hi @nul800sebastiaan - I can replicate the same issue with v10.8.5
Is there a chance it gets ported too?
