### ISSUE TITLE
Custom BlockEditors inheriting from BlockListPropertyEditorBase do not save

### ISSUE THREAD

**Issue by FullStackChef** [umbraco/Umbraco-CMS#14959]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

12.2.0

### Bug summary

`BlockListPropertyEditorBase` includes a nested internal class `BlockListEditorPropertyValueEditor` which implements the internal abstract class `BlockEditorPropertyValueEditor`. 

The constructor of BlockListEditorPropertyValueEditor Sets BlockEditorValues:
```csharp
BlockEditorValues = new BlockEditorValues(new BlockListEditorDataConverter(), contentTypeService, logger);
```
Where `BlockListEditorDataConverter` has a hard coded value of `Constants.PropertyEditors.Aliases.BlockList` (`Umbraco.Blocklist`) for the `BlockEditorDataConverter` data converter.

Because of this any custom property that inherits from `BlockListPropertyEditorBase` successfully completes the process of saving but does not actually save.

### Steps to reproduce

1. Create a new custom property editor that extends BlockListPropertyEditorBase

```csharp
[DataEditor(
 PropertyEditorType,
 EditorType.PropertyValue,
 "Block Dictionary Editor",
 "blocklist",
 ValueType = ValueTypes.Json,
 Group = Constants.PropertyEditors.Groups.Lists,
 Icon = "icon-list",
 HideLabel = true)]
public class BlockDictionaryEditor : BlockListPropertyEditorBase
{
    public const string PropertyEditorType = "MCF.BlockDictionaryEditor";
    private readonly IEditorConfigurationParser _editorConfigurationParser;
    private readonly IIOHelper _ioHelper;

    public BlockDictionaryEditor(
                                IIOHelper ioHelper,
                                IDataValueEditorFactory dataValueEditorFactory,
                                IEditorConfigurationParser editorConfigurationParser,
                                IBlockValuePropertyIndexValueFactory blockValuePropertyIndexValueFactory) :
        base(dataValueEditorFactory, blockValuePropertyIndexValueFactory)
    {
        _ioHelper = ioHelper;
        _editorConfigurationParser = editorConfigurationParser;
    }

    protected override IConfigurationEditor CreateConfigurationEditor() => new BlockDictionaryConfigurationEditor(_ioHelper, _editorConfigurationParser);
}
```
2. Install / configure in umbraco as per usual
3. Add Content, Click Save

### Expected result / actual result

Expected result:
- An error OR
- Content to be persisted

Actual result:

- No error
- Content Resets

**Comment by FullStackChef** [comment]
Note: I have a draft pull request #14960 with a fix for this.

**Comment by elit0451** [comment]
Hey @FullStackChef 👋 
Thanks for reaching out! Can you provide a bit more info about your document type structure? As well as your custom `BlockDictionaryConfigurationEditor` class? So we can try to reproduce the issue 🙂

**Comment by FullStackChef** [comment]
[ExtendedBlockListConfiguration.zip](https://github.com/umbraco/Umbraco-CMS/files/12879714/ExtendedBlockListConfiguration.zip)

Hey @elit0451 reproduction package attached. 
ExtendedBlockListEditor contains commented out code that fixes the issue using a rather large amount of duplicated code.

**Comment by FullStackChef** [comment]
Images showing usage:

![image](https://github.com/umbraco/Umbraco-CMS/assets/28607748/bd5f768a-11d7-411c-ae59-6660726f64c2)

![image](https://github.com/umbraco/Umbraco-CMS/assets/28607748/781badb8-cc6a-4c5b-920d-ad0e8aa43a87)

![image](https://github.com/umbraco/Umbraco-CMS/assets/28607748/2c842175-e952-40db-8927-b341f2ed7f97)

**Comment by netcamo** [comment]
Hi @FullStackChef 

Thank you for bringing up this issue to us!

We have been able to reproduce it and I will assign proper labels to the issue.

Thank you again and I wish you a wonderful rest of the week!

**Comment by nul800sebastiaan** [comment]
Fixed in https://github.com/umbraco/Umbraco-CMS/pull/14960
