### ISSUE TITLE
No OOD.flag is created when using SourceCodeManual and Development Runtime

### ISSUE THREAD

**Issue by splab** [umbraco/Umbraco-CMS#14965]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

11.4.2

### Bug summary

When using SourceCodeManual and Umbraco:CMS:Runtime is set to Development, notificationhandlers for generating ood.flag is never registered, which means ModelsBuilder wont detect changes to content models or types.

### Specifics

In src\Umbraco.Web.Common\ModelsBuilder\DependencyInjection\UmbracoBuilderDependencyInjectionExtensions.cs line 111 to 131 different notificationhandlers are registered. OutOfDateModelsStatus is only registered for BackofficeDevelopment, which means you can end up with a modelsbuilder (and developer) that think it's registered for SourceCodeManual  and OutOfDate flagging, but no changes are ever reported.

### Steps to reproduce

In appsettings, set:

    "Umbraco":  {
        "CMS": {
         ...
        "Runtime": "Development",

        "ModelsBuilder": {

             "FlagOutOfDateModels": true,

             "ModelsMode": "SourceCodeManual"

         }
    ....

When changing documents or types, no OOD.flag file will be generated and models builder will look like this:

![image](https://github.com/umbraco/Umbraco-CMS/assets/1687548/9afcaff7-6e1d-4d8a-93db-8d189bbd814d)

 

### Expected result / actual result

When chaning content type or data types, we expect to see:

![image](https://github.com/umbraco/Umbraco-CMS/assets/1687548/7667fcad-78a0-4301-96b5-63565faf7dbd)

and a ood.flag file created in the published models folder.

Adding:

            builder.AddNotificationHandler<ContentTypeCacheRefresherNotification, OutOfDateModelsStatus>();
            builder.AddNotificationHandler<DataTypeCacheRefresherNotification, OutOfDateModelsStatus>();

to:

        if (builder.Config.GetRuntimeMode() != RuntimeMode.Production)
        {
            // Configure service to allow models generation
            builder.AddNotificationHandler<ServerVariablesParsingNotification, ModelsBuilderNotificationHandler>();
            builder.AddNotificationHandler<TemplateSavingNotification, ModelsBuilderNotificationHandler>();

            builder.AddNotificationHandler<UmbracoApplicationStartingNotification, AutoModelsNotificationHandler>();
            builder.AddNotificationHandler<UmbracoRequestEndNotification, AutoModelsNotificationHandler>();
            builder.AddNotificationHandler<ContentTypeCacheRefresherNotification, AutoModelsNotificationHandler>();
            builder.AddNotificationHandler<DataTypeCacheRefresherNotification, AutoModelsNotificationHandler>();
        }

Will fix this issue.

**Comment by jannikanker** [comment]
Hm, looks weird. I'll gladly take a stab at it!

**Comment by jannikanker** [comment]
Draft PR ready, but I need to be sure that this is indeed a code bug and not a documentation error. It's pretty clear (to me, at least) that https://docs.umbraco.com/umbraco-cms/fundamentals/setup/server-setup/runtime-modes#development-mode says you should be able to do SourceCodeManual while in Development runtime mode... Anyone? :-D
