### ISSUE TITLE
Links are not inheriting the relative path for new domains when using Block List data types

### ISSUE THREAD

**Issue by Truealex4** [umbraco/Umbraco-CMS#14983]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

10.6.1

### Bug summary

I had configured a component (block) to have some optional links and these are selected via a link picker. However we then changed the domain of the site, but the existing links continued to point to the old domain.

### Specifics

Nothing specific, obviously applies to all browsers

### Steps to reproduce

1. Access Umbraco
2. Create a new block list data type that uses a link picker
3. Create some links using the picker
4. Save and publish
5. Ensure links work correctly by visiting respective page
6. Change the domain of the site
7. Revisit the page in the site in Step 5
8. Select links

### Expected result / actual result

EXPECTED RESULT - These links will inherit the new domain
ACTUAL RESULT - All links that use this need to be manually corrected as they are insted, hardstamped

**Comment by andr317c** [comment]
Hey! Thanks for posting this issue. I tried reproducing your issue, but I was unable to do it. 

Here is a gif showing what I did:
![LinksTest](https://github.com/umbraco/Umbraco-CMS/assets/73799582/1e966824-dc51-464c-9a52-accc1c9d512f)

Please let me know if I missed anything 😄

**Comment by Truealex4** [comment]
Happy to close, this looks like it has potentially been fixed in a subsequent release
