### ISSUE TITLE
Inaccurate messaging when a mandatory link has been omitted upon block list creation

### ISSUE THREAD

**Issue by Truealex4** [umbraco/Umbraco-CMS#14984]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

10.6.1

### Bug summary

I omitted the mandatory link that I was adding to my 'Image Promo Row' block list component and although I correctly received an error message and was unable to save, the message itself was inaccurate.

### Steps to reproduce

Access CMS
Go to Full Width Page Content tab on any page
Add Image Promo Row component
Add Image Promo item
Omit the link 
Attempt to Save

### Expected result / actual result

EXPECTED RESULT - Unable to save and accurate messaging.
ACTUAL RESULT - Unable to save and inaccurate messaging as it indicates to the user that they can add multiple urls when there can only be 1.

![image](https://github.com/umbraco/Umbraco-CMS/assets/98405431/a8a318fe-60b5-43fa-8084-fef6e4549d9c)

**Comment by netcamo** [comment]
Hi @Truealex4,
I hope everything is going well for you!
Thank you for bringing up this issue!

The way the error notification works is, it shows the _minimum_ amount of URLs needed which in this case 1. 

Unfortunately it is not easy to make it display 1 URL when minimum is 1 and 2 URL**s** when minimum number is 2. We think that it is clear enough for now and we will close the issue. However, if you would like to work on it then we will be very happy to reopen the issue as an "_up for grabs_". You can let us know by responding to my message.

Thank you again for informing us of this issue and I wish you a wonderful rest of the  week! 😄
