### ISSUE TITLE
failed to get logged user

### ISSUE THREAD

**Issue by fatmazayedsayed** [umbraco/Umbraco-CMS#14993]
### Which *exact* UI Library version are you using? For example: 1.0.1 - don't just write v1.

umbraco Version 12

### Bug summary

i created custom tab to be displayed in backoffice
i want to get current logged user but it always is null

### Steps to reproduce

1- i created custom tab to be displayed in backoffice
i want to get current logged user but it always is null
<img width="689" alt="image" src="https://github.com/umbraco/Umbraco.UI/assets/40010845/d1a7012b-09b3-4e38-8aba-fbf06b73a1be">

2- when i clicked to acution tab it goes to custom controller 
<img width="572" alt="image" src="https://github.com/umbraco/Umbraco.UI/assets/40010845/a3fb201f-da69-4150-8761-4acc10c38690">

i want to get current logged user data in index function but i failed

**Comment by elit0451** [comment]
Hi @fatmazayedsayed 

We haven't heard from you in 3 weeks, so I will go ahead and close this issue. Feel free to reopen it if your problem hasn't been resolved! 🙂
