### ISSUE TITLE
Error on build solution

### ISSUE THREAD

**Issue by bobhu1** [umbraco/Umbraco-CMS#15001]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

latest

### Bug summary

Using VS 2022 Clone the Umbraco-CMS from Github(Oct 18 2023), total 29 projects, then using build solution to build, got one error: 

MSB3073	The command "npm ci --no-fund --no-audit --prefer-offline" exited with code 9009.	Umbraco.Cms.StaticAssets, line 30

please let me the solution asap.

### Steps to reproduce

Just try to build total new solution.

**Comment by david0718** [comment]
same issue

**Comment by Zeegaan** [comment]
Not getting this issue sadly, what version of node & npm do you have installed ? 😁

**Comment by bobhu1** [comment]
Thanks a lot, after downloading the latest both node and nmp the project
worked.

BOB

**Comment by Zeegaan** [comment]
Great to hear 😁

**Comment by bobhu1** [comment]
Hi:

Downloaded the latest code  from Github and tried to run in VS 2022. The
solution can not load OurUmbraco.Site project. Error:
The imported project
"$(VSToolsPath)\WebApplications\Microsoft.WebApplication.targets" was not
found. Also, tried to find
"$(VSToolsPath)\WebApplications\Microsoft.WebApplication.targets" in the
fallback search path(s) for $(VSToolsPath) - "C:\Program Files
(x86)\MSBuild\Microsoft\VisualStudio\v17.0"

Please let me know the answer ASAP.


BOB

**Comment by Zeegaan** [comment]
@bobhu1 The solution doesn't containt a `OurUmbraco.Site` project, so I'm a bit confused here 🙈

**Comment by adelmurad24** [comment]
same issue ...

**Comment by nul800sebastiaan** [comment]
Please note: you typically won't need to build Umbraco from the source code unless your goal is to contribute to its development. Umbraco is designed to be [highly extensible and flexible](https://docs.umbraco.com/umbraco-cms/extending/), allowing you to build and customize it to your specific needs without accessing the core source code. Instead, we recommend [installing Umbraco as described in the documentation](https://docs.umbraco.com/umbraco-cms/fundamentals/setup), and then extending it through available tools and frameworks to suit your requirements.

However, if you're interested in contributing to Umbraco, we'd love to hear more! Let us know what you're trying to do, and we’ll be happy to help you get started.

I'm going to close this issue as one of them is about the Our Umbraco community site and @adelmurad24 if you'd like to contribute to Umbraco then please do join us on Discord - but I am assuming you're just trying to use Umbraco as a product and you can install it as noted above.
