### ISSUE TITLE
Long strings issue in Umbraco Backoffice

### ISSUE THREAD

**Issue by mateuszQA** [umbraco/Umbraco-CMS#15011]
version 11.3.1

### Bug summary

Hello, during destructive tests on our websites, I encountered problems such as the fact that many things in Umbraco do not have a "word-wrap" in CSS, which results in, for example, some elements hiding, text appearing behind blocks, etc. Could you please take a look at this? (Examples from below shows copied element with long string which goes outside the block, and the second example is hiding TAB "settings" by a long string. I think word-wrap could fix it)
![issue 1](https://github.com/umbraco/Umbraco-CMS/assets/119952850/75fc55c2-d785-49ec-bd22-def50173dbb9)
![issue 2](https://github.com/umbraco/Umbraco-CMS/assets/119952850/2da18a78-b48e-426a-bc15-299e9dda550c)

### Steps to reproduce

Just put one long string to any element

### Expected result / actual result

Text is word-wrap

**Comment by Zeegaan** [comment]
Seeing this also when just configuring a block list editor!
![image](https://github.com/umbraco/Umbraco-CMS/assets/70372949/3aa593e9-9189-4467-8dfa-117dec35751e)

Marking this one as up for grabs, as its a great first issue to get started with, and we'd love some help with this 🙌

**Comment by emmagarland** [comment]
Thanks for raising @mateuszQA, I have created PR #15014 for this specific example, but I expect there are other areas that need it too
