### ISSUE TITLE
Password Is Not Hidden During Installation

### ISSUE THREAD

**Issue by nagolucky18** [umbraco/Umbraco-CMS#15036]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

12.3.0-rc

### Bug summary

Admin user password is not hidden during admin credential setup step of Umbraco installation.

### Specifics

The new admin user password is not hidden during admin credential setup of Umbraco installation, which may lead to unintended sharing of administrator password and consequently, compromise of new admin account.

This is because the HTML input is of `text` type and not `password` type in "user.html". Unless there is a specific reason that the input is of `text` type, HTML `password` input type should be used to ensure password is hidden when user inputs a value into the textbox.

### Steps to reproduce

1. Install Umbraco for the first time.

### Expected result / actual result

The new admin user password should be hidden while the user inputs values into the textbox.

![admin_password_visible_during_install](https://github.com/umbraco/Umbraco-CMS/assets/50598649/bf589a9b-0ac0-4adc-944f-4e1a8b797489)

**Comment by mastrup** [comment]
There is some reasoning on this old PR #3555 on why not to do it.
In the end, the change was welcomed but never ported from v7 to v8.

**Comment by Migaroez** [comment]
Hey @mastrup thanks for the PR #h5yr!
