### ISSUE TITLE
v13: New login screen does not work with password managers

### ISSUE THREAD

**Issue by nul800sebastiaan** [umbraco/Umbraco-CMS#15041]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

13.0.0-pre

### Bug summary

Password managers have no access to the new text fields that are now web components. Apart from being a security problem (https://www.wired.com/2015/07/websites-please-stop-blocking-password-managers-2015/ - notes people reuse bad passwords if they can't auto-fill), an accessibility issue and an annoying UX problem.

https://github.com/umbraco/Umbraco-CMS/assets/304656/c2fca09d-7da9-43dd-a597-c2182f033a0e

### Specifics

The problem seems to be that password managers don't have access to the shadow DOM, there seems to be ways around this though: https://stackoverflow.com/a/67681100

### Steps to reproduce

Try using your password manager on the new login screen on the `v13/dev` branch.

**Comment by kjac** [comment]
Hi @nul800sebastiaan ... yeah we've seen this too. We're going to look at it in the upcoming sprint 😄
