### ISSUE TITLE
v13: New login screen has 2 icons for show password

### ISSUE THREAD

**Issue by nul800sebastiaan** [umbraco/Umbraco-CMS#15042]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

13.0.0-pre

### Bug summary

When logging in, my browser (Edge) adds an additional icon for showing the password:

![image](https://github.com/umbraco/Umbraco-CMS/assets/304656/a71595ce-9d8f-4c61-9e98-be2e22e510bd)

### Steps to reproduce

Try logging in to the v13 backoffice, note that the extra icon only appears if you press `[TAB]` from the email/login field to the password field and you start typing.

### Expected result / actual result

Only one "show password" icon to be shown.

**Comment by bjarnef** [comment]
Just want to mention it should be fixed in UI library :) 
https://uui.umbraco.com/?path=/docs/uui-input-password--docs

![image](https://github.com/umbraco/Umbraco-CMS/assets/2919859/6cac1bb4-d7f6-46e9-940f-fed97f28a28e)

but should be simple enough with a bit of styling:
https://stackoverflow.com/questions/61449079/how-to-hide-the-eye-from-a-password-input-in-ms-edge-and-ie

```
input::-ms-reveal,
input::-ms-clear {
    display: none;
}
```

**Comment by bjarnef** [comment]
It seems it has already been added here https://github.com/umbraco/Umbraco.UI/blob/875e75239ca4286d79645361d1aeb948cd572e15/packages/uui-input/lib/uui-input.element.ts#L435-L437 where `UUIInputPasswordElement` extends `UUIInputElement`.

So I guess it just need to update the UI library in v13 @iOvergaard

**Comment by iOvergaard** [comment]
Yes, it will be fixed when we get UUI updated.

**Comment by bjarnef** [comment]
@iOvergaard is there any specific reason `UUIInputElement` doesn't accept type `search`? :) 
https://github.com/umbraco/Umbraco.UI/blob/875e75239ca4286d79645361d1aeb948cd572e15/packages/uui-input/lib/uui-input.element.ts#L9-L21

![image](https://github.com/umbraco/Umbraco-CMS/assets/2919859/2c2900c0-320e-4c5f-9300-da9ff1074f77)

Although the eye icon only is shown in `UUIInputPasswordElement` I guess it was the intension also to hide browser specific password toggle icon in `UUIInputElement` password input.

**Comment by iOvergaard** [comment]
We have released UUI 1.5.0 and there is a pending PR to update it. Expect this issue to be resolved when that is merged: #15064
