### ISSUE TITLE
IMemberManager.VerifyUserTokenAsync() is not working

### ISSUE THREAD

**Issue by PMendesWebDev** [umbraco/Umbraco-CMS#15061]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

12.2.0

### Bug summary

Trying to verify a member's token that - was generated for a password reset - with `IMemberManager VerifyUserTokenAsync()` always returns `false` (not valid), no matter the `purpose` - `tokenProvider` combination used

### Specifics

I was trying to provide a "forgot password" mechanism to frontend members.

The user provides his email and a token, using `MemberManager.GeneratePasswordResetTokenAsync(member)`, is sent to his email.

I'll then use the `IMemberManager.VerifyUserTokenAsync()` to validate if the token is valid for that member (is active, is a member's token, etc).

The result of `VerifyUserTokenAsync()` is always `false` (invalid). I've tried ALL `porpose` `tokenProvider` combinations possible with no changes on the outcome.

### Steps to reproduce

Create a member;
Generate a token using GeneratePasswordResetTokenAsync();
Encode the token (so it will still work after sending in the email's reset-password url);
Use the provided token in VerifyUserTokenAsync()

### Expected result / actual result

Expected result:
- the VerifyUserTokenAsync returns false if the token is not valid 
- the VerifyUserTokenAsync returns true if the token is valid

Actual result:
- the VerifyUserTokenAsync always returns `false`

**Comment by bergmania** [comment]
Hi @PMendesWebDev.

I have a hard time reproducing.

Are you sure you decode the token correctly.

If I just test the services everything seems to work as expected. E.g. the following test

```cs
using NUnit.Framework;
using Umbraco.Cms.Core;
using Umbraco.Cms.Core.Services;
using Umbraco.Cms.Tests.Common.Testing;
using Umbraco.Cms.Tests.Integration.Testing;
using Umbraco.Cms.Web.Common.Security;

namespace Umbraco.Cms.Tests.Integration.Umbraco.Web.Website.Security
{
    [TestFixture]
    [UmbracoTest(Database = UmbracoTestOptions.Database.NewSchemaPerTest)]
    public class MemberManagerTests : UmbracoIntegrationTest
    {
        public MemberManager MemberManager => GetRequiredService<MemberManager>();
        public IMemberService MemberService => GetRequiredService<IMemberService>();

        [Test]
        public async Task TestName()
        {
            var email = "username@umbraco.com";
            var member = MemberService.CreateMember(email, email, "Real Name", Constants.Security.DefaultMemberTypeAlias);
            MemberService.Save(member);

            var identity = await MemberManager.FindByEmailAsync(email);
            var token = await MemberManager.GeneratePasswordResetTokenAsync(identity);
            var verify = await MemberManager.VerifyUserTokenAsync(identity, "Default", "ResetPassword", token);

            Assert.IsTrue(verify);
        }
    }

}

```

**Comment by PMendesWebDev** [comment]
Thank you for the info @bergmania! It helped me getting this sorted out. I was doing a new MemberIdentityUser(id) instead of getting from the IMemberManager when generating the code. So the member that I later used to verify the token and reset the password would never be the same xD

Long story short, it was a ID Ten T error :) 

I'm closing this, sorry and thank you!
