### ISSUE TITLE
V13: Duplicate ids in new login screen

### ISSUE THREAD

**Issue by erikjanwestendorp** [umbraco/Umbraco-CMS#15089]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

13.0.0-rc1

### Bug summary

In the new login screen, the `input` elements for the email address and password have the same id: 

![image](https://github.com/umbraco/Umbraco-CMS/assets/7831614/a7711ff0-f92d-43f2-a7cc-5976f2eab6e0)

![image](https://github.com/umbraco/Umbraco-CMS/assets/7831614/3956588c-8d8b-47bd-890f-d1e6baae1a7b)

### Steps to reproduce

Install Umbraco 13.0.0-rc1 and see the login screen.

**Comment by iOvergaard** [comment]
I seem to have found a workaround for this issue locally: #15111  

Eventually, it should be handled more thoroughly on the UI library, where I have created a bug report.

**Comment by iOvergaard** [comment]
The workaround has been merged and will be released either in the next RC of V13. Thank you again for reporting, @erikjanwestendorp #h5yr
