### ISSUE TITLE
 ConvertIntermediateToDeliveryApiObject not hit if value is null

### ISSUE THREAD

**Issue by RBerntsen** [umbraco/Umbraco-CMS#15083]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

12.2.0

### Bug summary

Not sure if this is by design or not but if I create a ValueConverter implementing the IDeliveryApiPropertyValueConverter, then my ConvertIntermediateToDeliveryApiObject is never hit if the value is null. I wanted to create a value converter that was returning a default value, if it was null.

### Specifics

I've made an ultra basic IDeliveryApiPropertyValueConverter like this (removed some code for clarity):

```
    public class TextStringApiValueConverter : PropertyValueConverterBase, IDeliveryApiPropertyValueConverter
    {
        public override bool IsConverter(IPublishedPropertyType propertyType)
        {
            return true;
        }

        public object? ConvertIntermediateToDeliveryApiObject(
            IPublishedElement owner,
            IPublishedPropertyType propertyType,
            PropertyCacheLevel referenceCacheLevel,
            object? inter,
            bool preview,
            bool expanding)
        {
            return "test";
        }
    }
```

Now if I go and call the content API, I can see that all values that are not null are returned as "test", but values that are null are still just null.

I've followed the documentation from here:
https://docs.umbraco.com/umbraco-cms/reference/content-delivery-api/custom-property-editors-support

Here we also have a null check in place for the ConvertIntermediateToDeliveryApiObject which for me never is hit:

```
        if (inter is null)
        {
            return null;
        }
```

### Steps to reproduce

1. Create a ValueConverter as above
2. Create a content page with properties that have values and some that are null
3. Call that page from the Content Delivery API
4. Observe that all values that are not null are replace by "test", while all properties that are null are returned as such

### Expected result / actual result

I would expect that all values would be returned as "test"

**Comment by kjac** [comment]
Hi @RBerntsen 👋 

To handle a `null` (or not yet configured) value, a value converter must implement `IsValue` to inform the core that it can handle the `null` value.

In your case you need to override [`IsValue` on `PropertyVlaueConverterBase`](https://github.com/umbraco/Umbraco-CMS/blob/contrib/src/Umbraco.Core/PropertyEditors/PropertyValueConverterBase.cs#L18) with something along these lines:

```
public override bool? IsValue(object? value, PropertyValueLevel level) => true;
```

I'm going to close this ticket as I don't believe it's an issue with the core. If for some reason the `IsValue` override does not work for `null` values in your setup, please feel free to reopen with additional steps 😄

**Comment by RBerntsen** [comment]
Thanks @kjac, I'll try this out and see if it works :)

**Comment by RBerntsen** [comment]
@kjac I can confirm this did the trick. I didn't understand from the documentation that this was needed, good to know.
