### ISSUE TITLE
V13 RC: Custom Webhooks - WebhookEventBase TEntity only supports IContentBase

### ISSUE THREAD

**Issue by warrenbuckley** [umbraco/Umbraco-CMS#15093]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

13.0.0-rc1

### Bug summary

Trying to add a custom Webhook event type, rather than just the ones it ships with.
The base class `WebhookEventBase<TNotificatipn, TEnitiy>` for the Entity type it only works if it can convert to `IContentBase`

It would be nice to support any type of Notification and its Entity such as

```csharp
public class MemberGroupSavedWebhookEvent : WebhookEventBase<MemberGroupSavingNotification, IMemberGroup>
{
    public MemberGroupSavedWebhookEvent(
        IWebhookFiringService webhookFiringService,
        IWebHookService webHookService,
        IOptionsMonitor<WebhookSettings> webhookSettings,
        IServerRoleAccessor serverRoleAccessor)
        : base(
            webhookFiringService,
            webHookService,
            webhookSettings,
            serverRoleAccessor,
            "MemberSaved")
    {
    }

    protected override IEnumerable<IMemberGroup> GetEntitiesFromNotification(MemberGroupSavingNotification notification) =>
        notification.SavedEntities;
}
```

Other scenario is that there are Notifications without a direct entity tied to it, for example the `UserLoginSuccessNotification` but again some people may want to listen/register webhook against this event to put audit information into some third party system.

### Steps to reproduce

Try to create a class that inherits from `WebhookEventBase` and use some of the other notifications that ship with Umbraco.
Ideal world is that it supports any notification, so if I had my own custom notification type in my package then I could then add a webhook event as part of my package.

**Comment by warrenbuckley** [comment]
The lovely @KevinJump has done some work in a repo here @bergmania & @nikolajlauridsen 

https://github.com/Jumoo/uSync.Webhooks/blob/master/uSync.Webhooks/Webhooks/uSyncItemWebHookBase.cs

https://github.com/Jumoo/uSync.Webhooks/blob/master/uSync.Webhooks/Webhooks/uSyncExportCompletedWebhook.cs

**Comment by Zeegaan** [comment]
@warrenbuckley This is intended (atleast IMO). As we need the entityKeys in our cases, and thus it has to be `IContentBase` to sort out the entities.

As you link to, this was the approach in mind, if you wanted to for example use `UserLoginSuccessNotification` for example (or you might not even want your webhook to be a notificationHandler). To use Kevins approach you linked to: https://github.com/Jumoo/uSync.Webhooks/blob/master/uSync.Webhooks/Webhooks/uSyncItemWebHookBase.cs

Where you instead implement your own `IWebhookEvent`, and thus you have control over all the logic.

I did consider a `WebhookEntityEventBase` and a `WebhookEventBase` class, with one not using the `IContenBase`, I did however not do this, as we have no current events that do not also have an entity, and thus it would purely be a DX class.

Let me know your thoughts on this approach, and what you would prefer 👍 
Maybe @KevinJump could also chime in here, as he has already done this approach, and might have some thoughts on how we could make it easier 😁

**Comment by KevinJump** [comment]
There is a bit of logic that i think would benifit from being in a base case, namely the checks to see if webhooks are enabled / and if the server role is right to run the webhooks. 

e.g 

```cs
public abstract class WebhookEventBase<TObject> : IWebhookEvent,
    INotificationAsyncHandler<TObject>
    where TObject : INotification
{
    protected readonly IWebhookFiringService _webhookFiringService;
    protected readonly IWebHookService _webHookService;
    protected readonly IServerRoleAccessor _serverRoleAccessor;
    protected WebhookSettings _webhookSettings;

    protected WebhookEventBase(
        IWebhookFiringService webhookFiringService,
        IWebHookService webHookService,
        IServerRoleAccessor serverRoleAccessor,
        WebhookSettings webhookSettings)
    {
        _webhookFiringService = webhookFiringService;
        _webHookService = webHookService;
        _serverRoleAccessor = serverRoleAccessor;
        _webhookSettings = webhookSettings;
    }

    public string EventName { get => throw new NotImplementedException(); set => throw new NotImplementedException(); }

    public virtual async Task ProcessWebhooks(TObject notification, IEnumerable<Webhook> webhooks, CancellationToken cancellationToken
    {
        foreach (var webhook in webhooks)
        {
            if (webhook.Enabled is false) continue;

            await _webhookFiringService.FireAsync(webhook, EventName, notification, , cancellationToken);
        }
    }

    public virtual bool FireWebhookForNotification(TObject notificationObject)
        => true;

    public async Task HandleAsync(TObject notification, CancellationToken cancellationToken)
    {
        if (_webhookSettings.Enabled is false)
        {
            return;
        }

        if (_serverRoleAccessor.CurrentServerRole is not ServerRole.Single
            && _serverRoleAccessor.CurrentServerRole is not ServerRole.SchedulingPublisher)
        {
            return;
        }

        if (FireWebhookForNotification(notification) is false)
        {
            return;
        }

        // fire the xml across the wire to something else. 
        var webhooks = await _webHookService.GetByEventNameAsync(EventName);
    }
}
```

this would at the basic level work with an empty class for any webhook ?? 

```cs

public class MyCustomWebhook : WebhookEventBase<UmbracoApplicationStartedNotification>
{
    public MyCustomWebhook(
        IWebhookFiringService webhookFiringService,
        IWebHookService webHookService,
        IServerRoleAccessor serverRoleAccessor,
        WebhookSettings webhookSettings)
            : base(webhookFiringService, webHookService, serverRoleAccessor, webhookSettings)
    {
        EventName = "Umbraco Started Webhook";
    }
}
```

and give people the option to override the webhook firing (to change the data etc). 

```cs
    public override async Task ProcessWebhooks(UmbracoApplicationStartedNotification notification, IEnumerable<Webhook> webhooks, CancellationToken cancellationToken)
    {
        var data = new Dictionary<string, object>();

        foreach (var webhook in webhooks)
        {
            if (webhook.Enabled is false) continue;
            
            await _webhookFiringService.FireAsync(webhook, EventName, notification, cancellationToken);

        }
    }
```

and check if the webhook is enabled globally if they overrode 

```cs
    public override bool FireWebhookForNotification(INotification notificationObject)
    {
        // check something in the notification. 
        return false;
    }
```

(i suppose this should have been a PR 😄 )

**Comment by Zeegaan** [comment]
@KevinJump I would love this as a PR if you're up for it 🤞 🙈

**Comment by KevinJump** [comment]
Yes, some meetings today but I will try to squeeze it in 🙂

**Comment by Zeegaan** [comment]
Fixed https://github.com/umbraco/Umbraco-CMS/pull/15129
