### ISSUE TITLE
V13 RC: Webhook - Content Type list defaults to MediaTypes for Custom Webhook.

### ISSUE THREAD

**Issue by KevinJump** [umbraco/Umbraco-CMS#15095]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

v13 rc1

### Bug summary

There appears to be no way to control the behavior of the 'ContentType' selector on the Edit Webhook dialog, when using it for Custom webhooks. 

If your webhook isn't for a Content item then the picking list defaults to the MediaTypes. - so even if you did want to use the ContentTypes you can't pick them. 

### Specifics

I wonder if the Content Type bit of the webhooks could be made a bit more generic, or something you can turn off for a webhook. 

Ideally some custom data thing that is Content Types for Content/media but can be something else if you want it to be. but i get that that is a BIG ask.

maybe for now the ability to either specify which type of ContentType (e.g contentType, mediaType, memberType) or none, where it wouldn't be shown ? 

ties in a bit with @warrenbuckley's base class issue https://github.com/umbraco/Umbraco-CMS/issues/15093

### Steps to reproduce

1. Create a custom IWebhookEvent, 
2. select your custom event
3. select add 'content type' 
only media types appear. 

---
_This item has been added to our backlog AB#34456_

**Comment by Zeegaan** [comment]
Fixed in https://github.com/umbraco/Umbraco-CMS/pull/15157
