### ISSUE TITLE
V13 RC: Dynamic Root FurthestDescendantOrSelf throws exception

### ISSUE THREAD

**Issue by erikjanwestendorp** [umbraco/Umbraco-CMS#15112]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

13.0.0-rc1

### Bug summary

When using the FurthestDescendantOrSelf query in a multinode tree picker an exception is thrown: 

```
An error occurred
Did not find any filteres that could handle FurthestDescendantOrSelf

Error details
System.NotSupportedException, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e: Did not find any filteres that could handle FurthestDescendantOrSelf
```

![image](https://github.com/umbraco/Umbraco-CMS/assets/7831614/23050218-2391-4030-9dec-579f6f5224ee)

### Steps to reproduce

Create a Multi node tree picker with this config: 

![image](https://github.com/umbraco/Umbraco-CMS/assets/7831614/704a8aab-459a-441b-a132-3dccf89a3110)
****

**Comment by kjac** [comment]
Hi @erikjanwestendorp,

Thanks for reporting and not least thanks for the PR 🚀 

We'll have a look at this ASAP and get back to you 👍
