### ISSUE TITLE
V12.3 / V13 RC - Values not populated for culture invariant properties

### ISSUE THREAD

**Issue by matthewcare** [umbraco/Umbraco-CMS#15117]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

*Edit* I initially found the issue in 13.0.0-rc1 though it is confirmed to also be an issue in 12.3.0

### Bug summary

Trying to access properties with `Model.TheProperty` or `Model.Value("theProperty")` returns default values (empty string / 0 for numeric, etc) if a content type is set to `Allow vary by culture` and a property on that content type is set to `Allow vary by culture = false`

### Steps to reproduce

Create a content type which is set to `Allow vary by culture` and add a property which has `Allow vary by culture` set to false.

Observe that when rendering the property in the view, that the value is a default (not what is in the cms) value.

My example has `aNumber`, and `aString` set to not vary by culture, and `aString2` to vary by culture
![image](https://github.com/umbraco/Umbraco-CMS/assets/1469061/06c0e000-e525-4758-963d-d852d7ad64ab)

My view contains
```
@foreach (var prop in Model.Properties)
{
    <p>@prop.Alias @prop.GetValue()</p>
}
```

which results in an output of
![image](https://github.com/umbraco/Umbraco-CMS/assets/1469061/7d0d19cf-6c57-403b-86bb-c82125597ac1)

### Expected result / actual result

Expected:
Values to be displayed for all properties

Actual:
Only properties which are set to `vary by culture = true` show a value

---
_This item has been added to our backlog AB#34519_

**Comment by renaldas** [comment]
Same here, installed from Nuget: Latest stable 12.3.0

Not able to get values from Culture invariant property which is off:

happening in the code, for example:

MultinodeTreePicker
 var person= contact.Value<IEnumerable<IPublishedContent>>("person");

**Comment by jerpenol** [comment]
Same here for 12.3.0.

We are experiencing the same behaviour with invariant properties on a content type that can vary by culture.

I can confirm this also occurs, when you use ModelsBuilder to fetch the content:
```Csharp
Country country;
var emptyCode = country.Code;
```

**Comment by matthewcare** [comment]
I'll update the title of the issue to reflect that you guys are finding this in 12.3. Maybe it gets more traction if it's a "live" issue

**Comment by kjac** [comment]
Hi everyone 👋 

Thank you for raising this, @matthewcare. I will make sure the team jumps on this one early next week. Sounds like we need something patched ASAP 🐛

**Comment by kjac** [comment]
Alright I can reproduce this 😢 the issue is in the published cache... and by the looks of it, this was introduced when fixing another cache issue (https://github.com/umbraco/Umbraco-CMS/pull/14824).

**Comment by madsoulswe** [comment]
Oh this explains a lot 😅 it seems to be a major regression, several of our sites are broken at the moment 😬

**Comment by smarshallsay** [comment]
Can confirm it was a partial cause for issues mentioned here too https://github.com/umbraco/Umbraco-CMS/issues/14997

**Comment by kjac** [comment]
Fix in https://github.com/umbraco/Umbraco-CMS/pull/15145 --- we're going to look at a patch release to 12.3 as soon as possible.

**Comment by bergmania** [comment]
Patch available on nuget now

**Comment by cornehoskam** [comment]
After some investigation this also seemed to break uMarketingSuite segment fallbacks, so glad to see it fixed in 12.3.1 😊

**Comment by lars-lindstrom** [comment]
The patch in 12.3.2 did the trick, but the issue does not appear to be solved in 13.0.0 RC4. Others who expierence the same?

**Comment by lars-lindstrom** [comment]
Unfortunately I do, but maybe the issue is constraint to invariant date only properties?

I use a document type to describe persons - names, birthdate, etc. The birthdate property is an invariant date only property.

For any persons, I can pick a date and view it on the sceen. Then I save and publish. 
![image](https://github.com/umbraco/Umbraco-CMS/assets/63322355/76cf871b-02fe-4ce6-8e1b-ee45537a7191)

To check if the value is saved, I switch to a different person and the reload the persons I changed. Now the data is gone.
![image](https://github.com/umbraco/Umbraco-CMS/assets/63322355/a4fdda19-33dc-44ed-802c-987ab7cecf2a)

I'm using CMS 13.0.0 RC4 build 140

**Comment by lars-lindstrom** [comment]
Strange. I tested changing the property to invariant textstring - it worked as expected. I then converted the property back to DateTime and the problem reapeared. I also tried to create an extra invariant date property - again the value is not shown in the backoffice.

**Comment by kjac** [comment]
Hmm. Two things come to mind:

1. Is this a vanilla install, or *could* there be some custom code interfering with the property?
2. Does the invariant property data render in the frontend (razor template)?

**Comment by lars-lindstrom** [comment]
@kjac
1. Yes, it is a Vanilla install. No changes made, only Views, Partial Views, document types, etc.
2. No, the frontend returns "{01.01.0001 00.00.00}"

Tried to update to RC5 this morning - no change.

**Comment by kjac** [comment]
That is so weird 😕 

If you're up for testing it, here's a zip of my test site --- backoffice login is admin@localhost / SuperSecret123

[Umbraco13RC.zip](https://github.com/umbraco/Umbraco-CMS/files/13661698/Umbraco13RC.zip)

**Comment by McGern** [comment]
I'm seeing this issue (or similar?) when using 11.5.0 (Umbraco cloud, don't know if that makes a difference). We are using the CMS headless so are accessing the content via APIs. If we use something like property.GetValue("en-US") only the properties with the variant content will display, whereas invariant properties will return null. Is this a case where we have to upgrade from 11.5.0 to 12.3.1?
