### ISSUE TITLE
MemberSavingNotification notification.CancelOperation does not prevent member from being created

### ISSUE THREAD

**Issue by PotatoDotJar** [umbraco/Umbraco-CMS#15152]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

12.1.1

### Bug summary

When using the MemberSavingNotification to validate custom business logic, I am unable to prevent the member from being saved. For new members, calling `notification.CancelOperation` will still save the new member, but not any of its properties. This becomes an issue when there are required properties that get saved without a value.

Typically, for document types, I am able to cancel the saving operation of content which will show a red bar with an error message in the BO. However, when I try to do the same thing with the MemberSavingNotification, I get both a green and red bar. 

![image](https://github.com/umbraco/Umbraco-CMS/assets/7833468/de877e67-a7dc-4a3f-91d2-196e3f090f5c)

### Steps to reproduce

1. Create a new `INotificationHandler<MemberSavingNotification>`. Within the `public void Handle` method, call `notification.CancelOperation(new EventMessage("Test", "Test", EventMessageType.Error));`
2. Register notification in Startup.cs: `umbracoBuilder.AddNotificationHandler<MemberSavingNotification, MemberSavingHandler>()`
3. Start project, navigate to members section and try to create and save a new/existing member.
4. For new members, a member is created without any properties. For existing members, no properties are saved but a misleading message is shown.

### Expected result / actual result

When `notification.CancelOperation` is called in the `MemberSavingNotification`, I would expect the saving operation to be stopped (like it does with saving content). When creating a new member, no new member should be created. No "Member saved: Member saved" message should be shown.

---
_This item has been added to our backlog AB#36153_

**Comment by Zeegaan** [comment]
I cannot reproduce this issue sadly, this is me on 12.1.1, let me know if I did anything wrong 🤞 

![MemberDoesntGetCreated](https://github.com/umbraco/Umbraco-CMS/assets/70372949/a6592cd7-6c12-4938-8429-bff6c07d2ff1)

Heres my notification handler:

```
using Umbraco.Cms.Core.Composing;
using Umbraco.Cms.Core.Events;
using Umbraco.Cms.Core.Notifications;

namespace MemberTest;

public class TestNoti : INotificationHandler<MemberSavingNotification>
{
    public void Handle(MemberSavingNotification notification)
    {
        notification.CancelOperation(new EventMessage("Test", "Test", EventMessageType.Error));
    }
}

public class MyComposer : IComposer
{
    public void Compose(IUmbracoBuilder builder)
    {
        builder.AddNotificationHandler<MemberSavingNotification, TestNoti>();
    }
}
```

**Comment by PotatoDotJar** [comment]
@Zeegaan Looking at your video, it looks like the invalid password stopped the saving operation. If you fix the password so it is successful, does it still stop the save?

**Comment by PotatoDotJar** [comment]
Update to this: I reviewed my code and realized that the reason it saves and then cancels is because the member saving fires twice. Once with no properties, and then saves the member, then fires again when saving the properties. I am unable to find a solution for preventing member saves based on member type properties so I still believe this is a bug. My Handle method is below:

```cs
public void Handle(MemberSavingNotification notification)
{
    foreach (var member in notification.SavedEntities)
    {
        // Ensure member's firstname + lastname are not already in the system
        if (member.ContentType.Alias.Equals(nameof(Member), StringComparison.InvariantCultureIgnoreCase))
        {
            var newFirstName = member.GetValue<string>(nameof(Member.FirstName).ToCamelCase());
            var newLastName = member.GetValue<string>(nameof(Member.LastName).ToCamelCase());
        
            var hasExistingMember = MemberService.GetAll(0, int.MaxValue, out _)
                .Any(x =>
                    (!member.HasIdentity || x.Id != member.Id)
                    && x.GetValue<string>(nameof(Member.FirstName).ToCamelCase())!.Equals(newFirstName,
                        StringComparison.InvariantCultureIgnoreCase)
                    && x.GetValue<string>(nameof(Member.LastName).ToCamelCase())!.Equals(newLastName,
                        StringComparison.InvariantCultureIgnoreCase));
            if (hasExistingMember)
            {
                notification.CancelOperation(new EventMessage("Duplicate Member Name", $"Member already exists with that first and last name", EventMessageType.Error));
                return;
            }
        }
    }
}
```

**Comment by PotatoDotJar** [comment]
@Zeegaan I have **exact** steps to reproduce the issue below using Umbraco v13.0.1 (this issue also exists in v12 and I would imagine earlier versions):

1. Create new project using the Umbraco dotnet template. `dotnet new umbraco --name MyProject`
2. Run project and setup Umbraco using SQLite data provider.
3. Login to the back office to ensure everything is working.
4. Add a new property to the member document type. In my case it is `firstName` and it is required.
5. Stop the project.
6. Create a new notification handler with the following code:
```
public class MyMemberSavingHandler : INotificationHandler<MemberSavingNotification>
{
    public void Handle(MemberSavingNotification notification)
    {
        foreach(var member in notification.SavedEntities)
        {
            // Only allow the member through if their firstName is not "test"
            var memberFirstName = member.GetValue<string>("firstName");
            if (memberFirstName != null && memberFirstName.ToLower() == "test")
            {
                notification.CancelOperation(new EventMessage("First Name", "A first name of \"Test\" is not allowed", EventMessageType.Error));
                return;
            }
        }
    }
}
```
7. Register the MyMemberSavingHandler in the Program.cs file.
8. Run the project.
9. Create a new member (other required fields can be anything valid)
10. When saving a member, you will get both the error message and a saving success message and the member will be created with the firstName required property blank. It looks like this issue only happens with custom member properties which I am guessing has to do with the two step member saving process where the member is created and then the properties for that member are saved. I still believe this is a bug though as this is not what you would expect to happen when canceling the save operation. I have not found a way to prevent a member from being saved based on their custom properties within the member doctype.

**Comment by andr317c** [comment]
Hey! 
I just took a look into this issue, and I was able to reproduce it on versions 10.0.0, 10.8.2, 12.3.5, and 13.0.1 I will go ahead and mark this issue as a sprint candidate. 😄

**Comment by umbracocommunity** [comment]
This issue has been mentioned on **Umbraco community forum**. There might be relevant details there:

https://forum.umbraco.com/t/umbraco-13-double-popup-saved-warning-when-canceling-operation-in-usergroupsavingnotification/8147/4
