### ISSUE TITLE
V13 RC: Error when webhook trigger and URL is https

### ISSUE THREAD

**Issue by bjarnef** [umbraco/Umbraco-CMS#15172]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

13.0.0-RC

### Bug summary

If setting up a webhook using e.g. URL `https://test.dk` it throws the following error on publish or unpublish. The publish state does seem to change though.

![image](https://github.com/umbraco/Umbraco-CMS/assets/2919859/63816071-cc99-41f5-9112-6cfe8312c385)

![image](https://github.com/umbraco/Umbraco-CMS/assets/2919859/8f584a75-a3da-4146-9789-88b9073c259a)

it doesn't happen on ``http://test.dk` though.

### Steps to reproduce

- Add a random URL connecting to SSL, e.g. ``https://test.dk` and trigger on event publish and unpublish.
- Publish/Unpublish a node or the specific node type if a content type was selected.

**Comment by bjarnef** [comment]
@Zeegaan it would be nice if it just logged an error instead.

**Comment by Zeegaan** [comment]
@bjarnef Agreed, I'm working on firing the webhook requests in a background job, so hopefully that should solve this. (Will probably also wrap in a try-catch). 👍

**Comment by Zeegaan** [comment]
Fixed in https://github.com/umbraco/Umbraco-CMS/pull/15176 🚀
