### ISSUE TITLE
Not all media items are loaded into the cache if there are more images then documents available

### ISSUE THREAD

**Issue by karl-sjogren** [umbraco/Umbraco-CMS#15195]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

12.3.1

### Bug summary

Since 12.3.0 the media cache isn't populated correctly if the are more media items then documents. In my case only the first 1000 of my 1600 media items were loaded into the cache.

There is a simple workaround for now by disabling cache, but it took me almost five hours to figure out what was the problem when some of my images stopped loading.

```json
  "Umbraco": {
    "CMS": {
      "NuCache": {
        "UsePagedSqlQuery" : false
      },
```

### Specifics

This code was changed in #14806 (released in 12.3.0) to improve performance as per #13525.

https://github.com/umbraco/Umbraco-CMS/blob/e5c8627abf7984f6939d17105f581304dcdf4553/src/Umbraco.PublishedCache.NuCache/Persistence/NuCacheContentRepository.cs#L993-L1010

This part of the code is called from `NuCacheContentRepository.GetAllMediaSources` (which is called from `PublishedSnapshotService.LoadMediaFromDatabaseLocked`) but on line 1003 `Constants.ObjectTypes.Document` is hard coded which in my cases returns a small count of only ~200 items. This of course messes up the pagingation of the media items (of which there are 1600) so that only the first page is returned.

### Steps to reproduce

Add more then 1000 media items and less then 1000 documents, only the first 1000 media items will be loaded into the cache.

### Expected result / actual result

All media items should be loaded into the cache no matter how many documents there are.

**Comment by bergmania** [comment]
I see the problem.. Thanks for reporting. We will look into a fix

**Comment by andersbrohall** [comment]
Hi, we encountered this problem too. 
The fix didn't solve it for us, but the workaround did. 

That said, its a site with this in the cache:
_Database cache is ok. ContentStore contains 782 items and has 1 generation and 0 snapshot. MediaStore contains 1000 items and has 1 generation and 0 snapshot._
... im thinking that **1000** isn't the correct number. I would say that it's capped - as far as i can tell we've got 1757 items in the DB.

**Comment by andersbrohall** [comment]
(are the notifications still working when the issue is closed?)
ping @bergmania

**Comment by karl-sjogren** [comment]
Just got 12.3.2 deployed to the problematic environment and if I enable `UsePagedSqlQuery` again my images are missing aswell.

**Comment by callumbwhyte** [comment]
Just jumping in here to say we also had this problem on a site today after upgrading to v12.3+. The patch version v12.3.2 also does not fix the issue.

The only solution was to roll back to v12.2.0, truncate the cmsContentNu table, delete the NuCache files, start the site again, and rebuild the cache via the "Published Status" dashboard

**Comment by andersbrohall** [comment]
> Just jumping in here to say we also had this problem on a site today after upgrading to v12.3+. The patch version v12.3.2 also does not fix the issue.
> 
> The only solution was to roll back to v12.2.0, truncate the cmsContentNu table, delete the NuCache files, start the site again, and rebuild the cache via the "Published Status" dashboard

@karl-sjogren's workaround in the report works for us.

**Comment by Mike-CurateCoders** [comment]
We have the same issue - v12.3.2 did not solve it, we have 1024 media items currently all images and still some images not showing after cache rebuild and restart.

**Comment by karl-sjogren** [comment]
@bergmania Do you want to reopen this our should we move it to a new issue? I did some more debugging and have my findings below but I could move this to a new issue if you want.

I took some time to debug this again with my project and the "Count" query just doesn't work for media items it seems. In my tests it always returns 0 items, but since the check is made after loading the first page at least some stuff still loaded.

I'm still something of a beginner with the low level Umbraco (and NPoco) stuff but the count query is waaay different then the actual select in this case.

This is the generated query to select all media items:

```sql
SELECT 
  [umbracoNode].[id] AS [Id], 
  [umbracoNode].[uniqueId] AS [Key], 
  [umbracoNode].[level] AS [Level], 
  [umbracoNode].[path] AS [Path], 
  [umbracoNode].[sortOrder] AS [SortOrder], 
  [umbracoNode].[parentId] AS [ParentId], 
  [umbracoNode].[createDate] AS [CreateDate], 
  [umbracoNode].[nodeUser] AS [CreatorId], 
  [umbracoContent].[contentTypeId] AS [ContentTypeId], 
  [umbracoContentVersion].[id] AS [VersionId], 
  [umbracoContentVersion].[text] AS [EditName], 
  [umbracoContentVersion].[versionDate] AS [EditVersionDate], 
  [umbracoContentVersion].[userId] AS [EditWriterId], 
  [nuEdit].[data] AS [EditData], 
  [nuEdit].[dataRaw] AS [EditDataRaw] 
FROM 
  [umbracoNode] 
  INNER JOIN [umbracoContent] ON (
    [umbracoNode].[id] = [umbracoContent].[nodeId]
  ) 
  INNER JOIN [umbracoContentVersion] ON (
    (
      [umbracoNode].[id] = [umbracoContentVersion].[nodeId]
    ) 
    AND [umbracoContentVersion].[current] = 1
  ) 
  LEFT JOIN [cmsContentNu] [nuEdit] ON (
    (
      [umbracoNode].[id] = [nuEdit].[nodeId]
    ) 
    AND [nuEdit].[published] = 0
  ) 
WHERE 
  (
    (
      (
        [umbracoNode].[nodeObjectType] = 'b796f64c-1f99-4ffb-b886-4bf4bc011a9c'
      ) 
      AND ([umbracoNode].[trashed] = 0)
    )
  ) 
ORDER BY 
  [umbracoNode].[level], 
  [umbracoNode].[parentId], 
  [umbracoNode].[sortOrder]
```

And this is the (supposedly optimized) query to count the items which returns 0.

```sql
SELECT 
  COUNT(*) 
FROM 
  (
    SELECT 
      [umbracoNode].[id] AS [Id] 
    FROM 
      [umbracoNode] 
      INNER JOIN [umbracoContent] ON (
        [umbracoNode].[id] = [umbracoContent].[nodeId]
      ) 
      INNER JOIN [umbracoDocument] ON (
        [umbracoNode].[id] = [umbracoDocument].[nodeId]
      ) 
      INNER JOIN [umbracoContentVersion] ON (
        (
          [umbracoNode].[id] = [umbracoContentVersion].[nodeId]
        ) 
        AND [umbracoContentVersion].[current] = 1
      ) 
      INNER JOIN [umbracoDocumentVersion] ON (
        [umbracoContentVersion].[id] = [umbracoDocumentVersion].[id]
      ) 
      LEFT JOIN [umbracoContentVersion] [pcver] 
      INNER JOIN [umbracoDocumentVersion] [pdver] ON (
        ([pcver].[id] = [pdver].[id]) 
        AND [pdver].[published] = 0
      ) ON (
        [umbracoNode].[id] = [pcver].[nodeId]
      ) 
    WHERE 
      (
        (
          (
            [umbracoNode].[nodeObjectType] = 'b796f64c-1f99-4ffb-b886-4bf4bc011a9c'
          ) 
          AND ([umbracoNode].[trashed] = 0)
        )
      )
  ) npoco_tbl
```

If we were to skip this optimized count query for Media the result is correct. Something like this.

```cs
    private IEnumerable<ContentSourceDto> GetContentNodeDtos(Sql<ISqlContext> sql, Guid nodeObjectType)
    {
        // We need to page here. We don't want to iterate over every single row in one connection cuz this can cause an SQL Timeout.
        // We also want to read with a db reader and not load everything into memory, QueryPaged lets us do that.
        // QueryPaged is very slow on large sites however, so use fetch if UsePagedSqlQuery is disabled.
        IEnumerable<ContentSourceDto> dtos;
        if (_nucacheSettings.Value.UsePagedSqlQuery)
        {
            Sql<ISqlContext>? sqlCount;

            if(nodeObjectType == Constants.ObjectTypes.Media) {
                // Use the default COUNT query
                sqlCount = null;
            } else {
                // Use a more efficient COUNT query
                Sql<ISqlContext>? sqlCountQuery = SqlContentSourcesCount()
                    .Append(SqlObjectTypeNotTrashed(SqlContext, nodeObjectType));

                 sqlCount = SqlContext.Sql("SELECT COUNT(*) FROM (").Append(sqlCountQuery).Append(") npoco_tbl");
            }

            dtos = Database.QueryPaged<ContentSourceDto>(_nucacheSettings.Value.SqlPageSize, sql, sqlCount);
        }
        else
        {
            dtos = Database.Fetch<ContentSourceDto>(sql);
        }

        return dtos;
    }
```

I have no idea if there are other types that needs to be handled here as well but this solved my images not loading. Since it is only for the count query I can't see that this affects the performance to badly, at least for short term fix.

**Comment by bergmania** [comment]
@karl-sjogren Thanks for the investigation.. A new issue is preferable.

**Comment by karl-sjogren** [comment]
@bergmania I've opened #15205 with my findings.
