### ISSUE TITLE
Media not being returned for certain nested modules

### ISSUE THREAD

**Issue by smarshallsay** [umbraco/Umbraco-CMS#15203]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

12.3.1

### Bug summary

Some properties still returning as null in varybyculture website

### Steps to reproduce

On our website pages can have a list of another document type 'module' within which can rest a 'submodule'.
12.3.1 fixed the issue for most properties it seems but I am having a specific problem with a module with a submodule inside it returning a null field for its 'media' property, which is just your standard media picker type. 
I've tried deleting the umbraco/data/temp folder, republishing and 'copying' the module, saving the page without it then re-adding it and none of those seem to fix the problem. The parent page property is marked as varybyculture, the module and submodule also had some varybyculture fields which I realise now didn't make sense so I disabled varybyculture for all of those fields and left it just on the top level, however even after re-publishing this didn't fix the issue.

What is strange is this isn't affecting all submodules, some are returning their existing images just fine and as far as I can see other fields such as text fields are returned just fine. Even stranger if I pick another image in the CMS for that submodule it will show up fine on the front-end, if I set the image back to the old one and publish once more it is returned as null, the only way I've found to fix it so far is to download and re-upload the same image as a new media item and then pick that new one and it will show in the front-end. 

May be related to https://github.com/umbraco/Umbraco-CMS/issues/15117

This is me inspecting the Model on the Master page on the first line (before anything has manipulated it), master just inherits the normal @Umbraco.Cms.Web.Common.Views.UmbracoViewPage

![image](https://github.com/umbraco/Umbraco-CMS/assets/5755133/35ce1fca-2669-4009-945f-29fa293dc4ff)

### Expected result / actual result

Media to be returned in all cases where it is saved against the node in the back end, even if in nested document types.

**Comment by smarshallsay** [comment]
We do, however setting UsePagedSqlQuery to false does not seem to help here. I've just realised that this did also happen in a carousel we have on our live site which is still running 11.2.2 because of a different issue we were having so it may be unrelated to 12.3.1, https://github.com/umbraco/Umbraco-CMS/issues/14997 which was related to https://github.com/umbraco/Umbraco-CMS/issues/15117 and I thought had been fixed by 12.3.1

**Comment by Zeegaan** [comment]
@smarshallsay Could you upgrade to https://www.nuget.org/packages/Umbraco.Cms/12.3.3 and tell me if the issue persists?
This will give us confirmation on if its related or not 🤞

**Comment by smarshallsay** [comment]
It... does seem to have fixed it! I'm confused how I also experienced the issue on 11.2.2 as well though as I thought this issue had only been around recently. Thanks guys!

**Comment by Zeegaan** [comment]
Good to hear! I will go ahead and close this issue for now then 😁
