### ISSUE TITLE
Media picker shows incorrect date

### ISSUE THREAD

**Issue by russellshome** [umbraco/Umbraco-CMS#15209]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

12.3.2

### Bug summary

When using the Media Picker the Last Updated date is incorrect. Occurs when using SQL Server database.

### Specifics

Media Picker using List View
![MediaFileView](https://github.com/umbraco/Umbraco-CMS/assets/8239408/9eadd73a-8950-4856-9649-5eb22b0373b1)
![MediaPickerView](https://github.com/umbraco/Umbraco-CMS/assets/8239408/e011508a-e935-4006-b375-24dd8045b12e)

### Steps to reproduce

Ensure SQL Server is Database (not SQL Lite)
Upload a file to Media
Create a  Document Type, Allow as Root, with a Media Picker property
In Content Create Item and click the Add button.
In the dialog choose List view

### Expected result / actual result

Expected - Last Updated date should be the same as Last edited date
Actual - Last Updated is different by the time zone (+13 for NZDST)

**Comment by andr317c** [comment]
Hey! 
Thanks for posting this issue. I was not able to reproduce it on version 12.3.2 🙁. I tried different time zones, but it worked as intended. Are you able to reproduce this on a clean install of Umbraco?

**Comment by russellshome** [comment]
The images above are from a clean install of Umbraco 12.3.2. The issue also exists in prior versions.

**Comment by russellshome** [comment]
Note that I used SQL Server database. 
The issue does not happen when using SQL Lite.

**Comment by andr317c** [comment]
Hey again! 
Thanks for clarifying 😄 I was able to reproduce this issue on versions 10.7.0, 12.3.3, and 13.0.0-rc2. I'll go ahead and mark this issue as an up for grabs.

I didn't get any issues when I was in the timezone UTC+00:00, but if I used another timezone, I ran into this issue

**Comment by nagolucky18** [comment]
I can look at this one.
