### ISSUE TITLE
EN and EN-US languages not in sync

### ISSUE THREAD

**Issue by SteveVaneeckhout** [umbraco/Umbraco-CMS#15213]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

12.3.1

### Bug summary

I noticed that [en.xml](https://github.com/umbraco/Umbraco-CMS/blob/contrib/src/Umbraco.Core/EmbeddedResources/Lang/en.xml) is missing a lot of translations compared to [en_us.xml](https://github.com/umbraco/Umbraco-CMS/blob/contrib/src/Umbraco.Core/EmbeddedResources/Lang/en_us.xml)

Do we really need to make a difference between these 2 _languages_? I think it's easiest to keep both files the same or even delete the US specific version (after updating en.xml since US is leading).

### Steps to reproduce

- Switch the language of your user profile to English.
- Save and Publish a content page.
- A notification shows message with a missing translation

### Expected result / actual result

The English dictionary in Umbraco should have all the words that the US English dictionary has.

**Comment by Zeegaan** [comment]
In short, yes we do need 2 translation files, this is IIRC because of inherent Dotnet cultures.

We should update the `en.xml` file with the missing translations though! 🙌

**Comment by Zeegaan** [comment]
- A notification shows message with a missing translation
I am not seeing a missing translation here, am I blind 🙈

**Comment by SteveVaneeckhout** [comment]
Sorry, my repro steps were not complete.
- Set your user profile to English (UK)
- Add another language in Settings
- Create a document type with variable cultures.
- Create a new document with 2 different cultures.
- Edit the title in 1 of the cultures and only save that culture.

![image](https://github.com/umbraco/Umbraco-CMS/assets/6131869/e60b584f-c45e-439d-ae57-cbf0beef4816)

Should I make a pull request where en.xml is a full clone of en_us.xml?

**Comment by Zeegaan** [comment]
@SteveVaneeckhout Shouldn't be a full clone, as stuff like color (US) & colour(UK) should differ, at least in an ideal world 🙈 
But yes I would love a PR with the missing translations 👍
