### ISSUE TITLE
Umbraco 13 - Webhook - Log overview - Datetime formatting incorrect

### ISSUE THREAD

**Issue by JeffreyPerplex** [umbraco/Umbraco-CMS#15229]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

13.0.0-rc2

### Bug summary

The formatting of the datetime in both the overview and detailed popup are not as I would expect. The date is formatted like "2023-11-16T13:39:54.7157563"

I would expect "November 16, 2023 2:38 PM" (like it is on the "Create date" or "Update date" in the content tree)

In the overview:

![afbeelding](https://github.com/umbraco/Umbraco-CMS/assets/12457148/2f2db5cf-ef82-4727-b1b5-31c507ca9eba)

In the detailed page:

![afbeelding](https://github.com/umbraco/Umbraco-CMS/assets/12457148/85f4966b-4669-4ba1-8343-0b5da92d5b76)

In the content tree (so how it's normally formatted):

![afbeelding](https://github.com/umbraco/Umbraco-CMS/assets/12457148/fa1a1338-79a1-43c3-9a2b-753ae62d1f60)

### Steps to reproduce

1. Install Umbraco 13-rc2
2. Create a new webhook
3. Trigger the webhook by publishing a page for example
4. Check the logs on /umbraco#/settings/webhooks/overview

### Expected result / actual result

Correct datetime format

**Comment by Zeegaan** [comment]
Ah yes good spot! We're missing some formatting there 🙈

**Comment by Zeegaan** [comment]
I would love some help with this if you're up for it @JeffreyPerplex 🤞

**Comment by bjarnef** [comment]
@Zeegaan I think this has been fixed now 😊

**Comment by Zeegaan** [comment]
Yep fixed in https://github.com/umbraco/Umbraco-CMS/pull/15246 🚀
