### ISSUE TITLE
Errors trying to get v14 working on macOS

### ISSUE THREAD

**Issue by TobyPerplex** [umbraco/Umbraco-CMS#15225]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

14.0.0--preview003

### Bug summary

Both me and my colleague are getting errors trying to get v14 working on macOS

### Steps to reproduce

- Installed SDK 8.0.100 for macOS Arm64 (have an M1 processor)
- Followed this guide: https://docs.umbraco.com/umbraco-backoffice/getting-started/installing-preview-builds

When running `dotnet --version` I get:
```
8.0.100
```

But when running `dotnet run` inside the MyAwesomeNightlySite folder I get:
`zsh: bus error  dotnet run` or `zsh: segmentation fault  dotnet run`

When running `sudo dotnet run` I get:
```
dotnet(2548,0x16e14f000) malloc: *** error for object 0x6000034379c0: pointer being freed was not allocated
dotnet(2548,0x16e40b000) malloc: *** error for object 0x60000340ae40: pointer being freed was not allocated
dotnet(2548,0x16e14f000) malloc: *** set a breakpoint in malloc_error_break to debug
dotnet(2548,0x16e40b000) malloc: *** set a breakpoint in malloc_error_break to debug
```

When running `dotnet restore` I get:
```
  Determining projects to restore...
dotnet(3055,0x16f6fb000) malloc: Double free of object 0x13897daa0
dotnet(3055,0x16f6fb000) malloc: *** set a breakpoint in malloc_error_break to debug
zsh: abort      dotnet restore
```

**Comment by Zeegaan** [comment]
Dotnet 8 final was not out when we released preview003, but we do have one colleague where its working fine on an m2 🤔 
Could you try installing the .NET 8 preview 7, as that's the one mentioned on the requirement page: https://docs.umbraco.com/umbraco-backoffice/getting-started/installing-preview-builds/alpha-release#local-development  🤞

**Comment by tobyperplex** [comment]
Using dotnet 8 preview 7 instead of dotnet 8 final is not the solution:
```
MyAwesomeNightlySite % dotnet --version
8.0.100-preview.7.23376.3
MyAwesomeNightlySite % dotnet run      
Building...
zsh: bus error  dotnet run
```

**Comment by tobyperplex** [comment]
@Migaroez then I get:
```
test % dotnet new webapp
The template "ASP.NET Core Web App (Razor Pages)" was created successfully.
This template contains technologies from parties other than Microsoft, see https://aka.ms/aspnetcore/8.0-third-party-notices for details.

Processing post-creation actions...
Restoring /Users/tobias/repos/umbraco-14/test/test.csproj:
  Determining projects to restore...
zsh: bus error  dotnet new webapp
```

**Comment by Migaroez** [comment]
Again at the restore stage, seems like a dotnet 8 bug to me as it is happening with a template they provide and before the actual build step. I advice you to log this on their [issue tracker](https://github.com/dotnet/runtime/issues) as we are sadly not able to do anything about this.
Feel free to add a to link the issue in the description of this one to keep us posted on the progress.

Hope it get's resolved soon and get to experiment with v14 on mac!

**Comment by tobyperplex** [comment]
Added a comment to https://github.com/dotnet/sdk/issues/38014
