### ISSUE TITLE
Umbraco 13 - Webhook - Log detailview - Random checkbox

### ISSUE THREAD

**Issue by JeffreyPerplex** [umbraco/Umbraco-CMS#15231]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

Umbraco 13.0.0-rc2

### Bug summary

In the detailview of log entry of webhooks there's a random big blue checkbox:

![afbeelding](https://github.com/umbraco/Umbraco-CMS/assets/12457148/1f7b214a-7e86-4c82-b0e3-c9b18eea41a9)

### Steps to reproduce

I did not expect that checkbox :)

**Comment by Zeegaan** [comment]
This is to indicate a success 🙈 
Maybe it could be clearer ? 🤔

**Comment by rasmusjp** [comment]
Maybe show the status code n ext to the checkbox like we do in Heartcore, I guess that would also solve #15230 
![image](https://github.com/umbraco/Umbraco-CMS/assets/379886/1e17a881-853f-4ab0-9124-602be74f7a0e)

**Comment by rasmusjp** [comment]
We also show it in the overview, so I guess that makes it a bit more obvious

![image](https://github.com/umbraco/Umbraco-CMS/assets/379886/2d4c9757-d49a-4c7e-ad12-92c68736a32d)

**Comment by Zeegaan** [comment]
Great idea 👍

**Comment by bjarnef** [comment]
I think the design of the `<umb-checkmark>` need to be re-designed a bit as it is too close to the look of `<umb-checkbox>`:
https://github.com/umbraco/Umbraco-CMS/discussions/15234

**Comment by elit0451** [comment]
Fixed in: https://github.com/umbraco/Umbraco-CMS/pull/15247
