### ISSUE TITLE
Umbraco 13 - Webhook - Statuscode is not a statuscode

### ISSUE THREAD

**Issue by JeffreyPerplex** [umbraco/Umbraco-CMS#15230]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

Umbraco 13.0.0-rc2

### Bug summary

The logging of the webhooks logs a status code as well. But instead of a statuscode (200, 500, 404, etcetera) a string is stored like "InternalServerError" or "Ok".

I would say that it should be the code:

![afbeelding](https://github.com/umbraco/Umbraco-CMS/assets/12457148/06c7d338-7460-4984-b21c-7eb9c8b4c77f)

### Steps to reproduce

1. Install Umbraco 13-rc2
2. Create a webhook
3. Publish a page (so that the webhook is triggered)
4. Check the statuscode

### Expected result / actual result

I expected that a statuscode (integer) was stored

**Comment by elit0451** [comment]
Fixed in: https://github.com/umbraco/Umbraco-CMS/pull/15247
