### ISSUE TITLE
13RC2 Webhook event selection with custom events isn't consistent

### ISSUE THREAD

**Issue by AndyButland** [umbraco/Umbraco-CMS#15249]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

13.0.0-rc2

### Bug summary

With some custom events registered, on selecting one, the "media" events disappear but the "content" ones don't.  Seems like it would be more consistent if they all disappeared, other than those of the same "type" (though quite how you find that type, I'm not sure - maybe using a convention of them being in the same namespace)?

### Steps to reproduce

Create a new webhook and click to select the events:

![image](https://github.com/umbraco/Umbraco-CMS/assets/1993459/bd0adfe6-043f-4d0f-9f28-b487688d645a)

Then when selecting one of the custom ones, the "media" ones only are removed.

![image](https://github.com/umbraco/Umbraco-CMS/assets/1993459/4e462064-b95c-4f4e-a444-9ebdfff3ba51)

I can select a "content" one as well as a custom one.

![image](https://github.com/umbraco/Umbraco-CMS/assets/1993459/51ef1d49-6c40-470f-8ef5-14932b2e6943)

### Expected result / actual result

If "media" are removed, should also not be able to select "content" events once a custom one has been picked.

**Comment by Zeegaan** [comment]
What do your events look like? 🤔

**Comment by AndyButland** [comment]
Ah... when teacher asks me to show them my work, I immediately see the problem.  As you've probably guessed, I have copied and pasted `Constants.WebhookEvents.Types.Content` set as the type.

**Comment by AndyButland** [comment]
Works fine when I fix that... thanks!
