### ISSUE TITLE
13RC2: Webhook dialog - make it bigger, and make the request json pretty

### ISSUE THREAD

**Issue by skttl** [umbraco/Umbraco-CMS#15241]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

13RC2

### Bug summary

![localhost_44375_umbraco](https://github.com/umbraco/Umbraco-CMS/assets/3726467/894bea1e-30cc-4e8f-82b4-490622dd3cd4)

When looking at the webhook dialog, I think there is room for improvements. Some has already been reported, but I think the dialog could be bigger, to make it easier to grasp whats in both the request and the response.

Also, if we could make the JSON prettier? Maybe even make it interactive like in https://jsonviewer.stack.hu/

I don't know if it's possible to recognize the response as eg. html or json, but it would be nice if that could be prettier too (syntax highlighting, interactive json or similar)

### Steps to reproduce

Create a webhook, trigger it, see the details dialog.

**Comment by bjarnef** [comment]
We could eventually use the following, which also add a copy button.

```
<umb-code-snippet language="'JSON'">{{value | json}}</umb-code-snippet>
```

If add `code` CSS class to `<pre>` element, which use a monospace font.

If we wanted to make it interactive we could use the existing ace editor, but probably readonly. However in new backoffice we have Monaco Editor instead, which I think has some benefits over Ace Editor.
Maybe the `<umb-code-snippet>` component (or a new component in the new backoffice) can allow the code snippet to be readonly or editable.

The datetime should probably be formatted as well, but that's a different issue.

**Comment by Zeegaan** [comment]
Agreed 👍 
Maybe one of you could help with this? 🤞
Lots of Webhooks stuff coming in, so it's kind of a priority game right now  💪

**Comment by skttl** [comment]
Definitely @Zeegaan - just needed some assurance :)

**Comment by bjarnef** [comment]
@skttl I have updated this in the related PR and looks like this:

![image](https://github.com/umbraco/Umbraco-CMS/assets/2919859/d65b3302-817e-4adf-bc0a-70177dcd1d18)

**Comment by skttl** [comment]
Looks good 👌

**Comment by Zeegaan** [comment]
Fixed in https://github.com/umbraco/Umbraco-CMS/pull/15246 💪
