### ISSUE TITLE
Custom dashboards in user-dialog no longer working

### ISSUE THREAD

**Issue by skttl** [umbraco/Umbraco-CMS#15240]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

13RC2

### Bug summary

Was going to see if my Impersonator package was working with 13RC2, but the dashboard wasn't loading.

Turns out there has been a change in the user-dialog where the dashboards are loaded like this now:

```html
      <div class="umb-control-group" ng-if="vm.dashboard.length > 0">
        <div ng-repeat="tab in vm.dashboard">
          <h5 ng-if="tab.label">{{tab.label}}</h5>
          <div ng-repeat="property in tab.options">
            <div ng-include="property.view"></div>
          </div>
        </div>
      </div>
```

Where before they where

```html
      <div class="umb-control-group" ng-if="vm.dashboard.length > 0">
        <div ng-repeat="tab in vm.dashboard">
          <h5 ng-if="tab.label">{{tab.label}}</h5>
          <div ng-repeat="property in tab.properties">
            <div ng-include="property.view"></div>
          </div>
        </div>
      </div>
```

Note the change from `<div ng-repeat="property in tab.properties">` to `<div ng-repeat="property in tab.options">`.

There is no `options` property in the output from `getDashboard`, but there is a properties.

What is the meaning here? Does properties need to be renamed to `options`, or should the user-dialog view have that line reverted?

### Specifics

When opening the user-dialog by clicking the avatar in the upper right corner, no custom dashboards are shown.

### Steps to reproduce

Install [Impersonator](https://marketplace.umbraco.com/package/our.umbraco.impersonator) or create your own user-dialog dashboard.

Note that the dashboards view doesn't load.

### Expected result / actual result

Expected the dashboards view to load.

**Comment by bjarnef** [comment]
It was changed with changes of the new login screen here: https://github.com/umbraco/Umbraco-CMS/pull/14780/files#diff-66bf35a5412c80c64bdf0ec15adbdd0e15e647053b8f44e0c142de410b7af47aR102

Maybe @iOvergaard know why it was changed?

**Comment by bjarnef** [comment]
I guess it is because it introduced as `options` property here: https://github.com/umbraco/Umbraco-CMS/pull/14780/files#diff-3ba395a8486bf101e6fce1d293d83ad1f5fcd6192c5e54441e177cab4cd8bee9R60-R70 ... but maybe it doesn't contain the data used in the user dashboard view, which `properties` do?

**Comment by skttl** [comment]
But that one is just for external login providers - not for dashboards. Maybe it's just an oversigt?

**Comment by iOvergaard** [comment]
> But that one is just for external login providers - not for dashboards. Maybe it's just an oversigt?

Good catch. This particular ng-repeat was not meant to be changed. I will revert the change for that line.

**Comment by iOvergaard** [comment]
A fix has been merged and will be released in the next RC !
