### ISSUE TITLE
Page Redirect after Logging in with Multifactor Authentication for Users

### ISSUE THREAD

**Issue by tekoscott** [umbraco/Umbraco-CMS#15259]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

12.3.3

### Bug summary

Umbraco MFA validation process when logging a user in into the backoffice is looking for api calls that apparently do not exist.

### Specifics

- Checked in all browsers - Chrome, Firefox, Edge
- Checked with clean install of umbraco 12.3.3
- Upgrading the site to the latest Umbraco 13 RC fixes the issue but I require this to be fixed on 12.
- When upgraded to the current Umbraco 13 RC site the issue no longer exists.
- As this occurs on a clean install of Umbraco 12.3.3 and not the latest Umbraco 13 RC, I believe it is an issue with Umbraco 12

### Steps to reproduce

- Setup Clean install of 12.3.3 Umbraco project
- Implement multifactor authentication as per instructions here [https://docs.umbraco.com/umbraco-cms/reference/security/two-factor-authentication](https://docs.umbraco.com/umbraco-cms/reference/security/two-factor-authentication)
- Add a test User
- Configure Mutlifactor authentication for that user using the QR code.
- Enable MFA for the user
- Log out of the site
- Log back in with the user that has MFA enabled
- On login screen add test users email and password
- On the MFA screen add the verificatiion code from Microsofts Authenticator App [https://play.google.com/store/apps/details?id=com.azure.authenticator&hl=en&gl=US](url) and click the Validate button
- The following is displayed in the browsers dev tools
![image](https://github.com/umbraco/Umbraco-CMS/assets/3155800/11fcafc8-efb5-448c-b8d3-0c1e5538a6f7)
- When validate clicked **'Invalid code entered'** error message displayed, but doing a page refresh in the browser allows access to the backoffice
![image](https://github.com/umbraco/Umbraco-CMS/assets/3155800/428cac1b-b4eb-4954-a998-ce085387047f)
- If the validate button clicked a second time the following message is displayed in the devtools console 
![image](https://github.com/umbraco/Umbraco-CMS/assets/3155800/584083b6-0d5a-44e2-977d-4e2a046fa984)

### Expected result / actual result

Expected to be redirected to backoffice upon successfull validaton of MFA verification code.

**Comment by Migaroez** [comment]
Hey @tekoscott 
Thank you so much for the detailed bug report. I have been able to reproduce this, and it seems like an oversight in the new login screen. I will flag this as a regression bug and we will do our best to fix this as soon as possible.

**Comment by kjac** [comment]
Hi again @tekoscott,

I'm on this - it is *not* related to the new login screen, as it is not part of V12 😆 but likely an unfortunate error from a well-meant contribution. I'll run some tests and get back when I have more info.

**Comment by kjac** [comment]
Fix in https://github.com/umbraco/Umbraco-CMS/pull/15317

**Comment by kjac** [comment]
Fixed with #15317 to be released in v12.3.4 👍
