### ISSUE TITLE
Strange image serving/caching behavior causes images of the wrong size to be served

### ISSUE THREAD

**Issue by jtaina** [umbraco/Umbraco-CMS#15275]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

10.7.0

### Bug summary

Using the same image with different crops on different pages does not result in images of the correct sizes to be served. Instead, when an image with a small crop is first loaded on page 1, that same crop will be served on page 2, even when page 2 uses a different crop.

### Specifics

We have been experiencing this issue with multiple Umbraco Cloud projects. When we use the same image in different pages, using different crops, whichever crop was first loaded will be served from then on. For instance, when first a thumbnail crop of 160x160 is loaded on page 1 and you then navigate to page 2 that requires a crop of 600x600, still that image is served with a crop of 160x160. Doing a hard refresh "fixes" the issue, but of course that's no real fix.

I have reproduced the issue with the repro repo (link below), in Windows 10 Enterprise, both on Firefox 119.0.1 and Chrome 119.0.6045.160. The repo was created such that I copied a client repo and then removed all client specific data, views. etc. So, where it matters, the settings in the repro project should be the same as in the client project.

I have also attempted to fix the issue by using MediaWithCrops & Local Crops but, alas, to no avail. Currently, in the client projects, we are circumventing the issue by having set the image caching duration to 1 second, so that crops will be respected in each page and images of correct sizes fetched. But this creates unnecessary bandwidth and makes the site sluggish.

Before Umbraco Cloud, the client sites in question were hosted in Azure (using Umbraco versions 7 & 8) and this kind of issue did not exist. So it seems that this has something to do with newer Umbraco versions or being an Umbraco Cloud project.

For about 2 months, I chatted about this with Umbraco Support, but we could not find a solution and in the end I was requested to submit an issue if the problem persists.

### Steps to reproduce

Here's a repro repo: https://github.com/jtaina/umbraco-10-image-cache-issue

The repository ships with a db and some media & pages so that you can easily reproduce the issue locally.

1. Run the project
2. Navigate to "Root Page", an image of size 160x160 will be served
3. Navigate to "Content Page With Large Image"
4. Witness a blurry image of size 160x160 being served, even when the page in question is using a larger crop of 600x600. You can check the img src property to see that the page is trying to get the dimensions 600x600.

If you hard refresh on a page, you will get the correct crop. If you then clear the browser cache and navigate to the root page  you can reproduce the issue again.

### Expected result / actual result

I would expect the crops to respected and the image of the correct size to be served, when actually whichever size was first loaded will be served subsequently.

**Comment by Migaroez** [comment]
This is a super weird bug.

- I was able to run the provided project and see the bug in action.
- Then I played around a bit with adding custom crops straight in the view to see if there was something wrong with how the url was generated. Everything looked fine, but still got the smallest image. Inspected the root image (without crop information) in chrome and still got the small one.
- Compared the rendered base image with the file in the media folder and there i could see the full image.
- Did a refresh with hard reload (in chrome) and suddenly everything worked.
- Cloned the repo again, ran it and everything just worked

**Comment by Migaroez** [comment]
After running it on another fresh pc, I can see that the second page doesn't actually make a new request to umbraco which makes me think something is adding outputcaching data to the files being serverd

I can also see that your Startup differs from a standard Umbraco install (default and cloud) with the following things, so I have a strong feeling your issue is because of these changes.

```
public void ConfigureServices(IServiceCollection services)
{
    services
        .AddResponseCaching()
        .AddHttpClient();
    ...
}
        
public void Configure(IApplicationBuilder app, IWebHostEnvironment env)
{
    ...
    app.UseResponseCaching();


    // var rewriteOptions = new RewriteOptions()
    // .AddIISUrlRewrite(env.ContentRootFileProvider, "IISUrlRewrite.xml");
    // app.UseRewriter(rewriteOptions);
    // UseStaticFiles is needed for rewrites to take effect. But it disables the ImageSharp cropper
    // so we exclude the media folder to retain the cropping functionality.
    // See: https://our.umbraco.com/forum/using-umbraco-and-getting-started/109573-getcropurl-doesnt-resize-the-image-on-umbraco-10
    app.UseWhen(
        context => !context.Request.Path.StartsWithSegments("/media"),
        appBuilder => appBuilder.UseStaticFiles()
    );
    ...
}
```

**Comment by jtaina** [comment]
@Migaroez 

Your strong feeling was exactly right! It turns out that the response caching that we had implemented for some controllers does affect how images get cached as well.

I added the following to Startup.cs to exclude images from getting cached by the middleware.

```
app.UseWhen(
        context => !context.Request.Path.StartsWithSegments("/media"),
        app => app.UseResponseCaching()
);
```

Thanks a lot! ☺️
