### ISSUE TITLE
Validation message inconsistency in the backoffice

### ISSUE THREAD

**Issue by Geri044** [umbraco/Umbraco-CMS#15270]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

12.3.1

### Bug summary

Umbraco required field validation is not consistent when a media picker property editor is present on the item.

### Specifics

- Checked browsers: Chrome, Firefox, Edge
- We have a composition which contains a Header (Textstring), Description (Textarea) and Image field (Media picker) all mandatory
- Every page type has this composition

### Steps to reproduce

- Create a new page
- If the editor only fills the image and tries to save the Header field gets highlighted and a validation message appears there (Notice that in the Description field there is a Required text but no highlighting like in the Header)

![image](https://github.com/umbraco/Umbraco-CMS/assets/11063384/cbedcbd2-90fc-4753-8dd0-79f840ac0e71)

- If the editor fills out all the fields and deletes the image and tries to save it correctly only the image fields gets highlighted:
![image](https://github.com/umbraco/Umbraco-CMS/assets/11063384/85b29e85-c54a-4e35-8953-eb445dc84216)

- If the user then deletes Header and Description as well still only the Image field is highlighted, but in this case all 3 fields should be highlighted and a validation message is also needed:
![image](https://github.com/umbraco/Umbraco-CMS/assets/11063384/c6e39468-860d-4e4d-8e4d-97756ae46388)

- If the user fills out the Header and chooses an Image the description fields doesn’t even get highlighted only a black “Required” text appears and the Image label is still red (even though is filled now)
![image](https://github.com/umbraco/Umbraco-CMS/assets/11063384/8f033650-fb83-4b30-a94e-bc5a94c33396)

- If the user only fills out the Header and tries to save then he gets a validation message for the filled Header and no validation for the Image:
![image](https://github.com/umbraco/Umbraco-CMS/assets/11063384/e098bacd-7694-4703-92ca-ce87b92ca469)

- If the user doesn’t fill out any of the field on a new content page, the Image field doesn’t have the validation message and the other two fields has only the black text instead of the red validation message.
![image](https://github.com/umbraco/Umbraco-CMS/assets/11063384/37aff624-3f10-4705-9cf0-a53c6c5bcc1c)

This issue can also be reproduced on a Block Grid Content element as well. Here we have similar fields. If I select an image (Media property is a block list editor where I can add an Image block) it still stays invalid until I fill out the Headline field as well:
![image](https://github.com/umbraco/Umbraco-CMS/assets/11063384/f4891271-3118-4dc9-8e10-68731e7e012a)
![image](https://github.com/umbraco/Umbraco-CMS/assets/11063384/a96a9b3d-167e-4fbf-b64e-09f7ef3d5b60)

Usually while editing a Block Grid Item, a validation prevents me from confirming the block if I miss some fields. But if I have a mandatory Image (newest media picker) than I can close the editor tab and onyl when I press Save & Publish then it displays that there is an error and the item can't be published.

### Expected result / actual result

The frontend validation in the backoffice should be always the same to not confuse editors while editing. If a validation message is highlighted then in every possible case it should be highlighted. Also if in a popup there is a validation error we should not be able to confirm it and currently for media picker property you can. (you can discard the changes of course if you like).

**Comment by Migaroez** [comment]
Hey @Geri044, Thank you so much for the detail and effort you put into this bug report.

I agree that we could give the validation system some love. We have actually been discussing this internally for the rework that should be coming in v14 and I will make sure the team pays attention to this report as it nicely outlines many of the shortcomings.

While everyone waits on the newest and greatest, it would probably be possible for the community to at least pick up some of the low hanging fruit that you have mentioned in this bug report, so I will be marking this one as up for grabs.

**Comment by Geri044** [comment]
Thanks for your response! Then we will see if anyone would like to help us out (or if not than we will have to wait for v14)  :)

**Comment by nielslyngsoe** [comment]
Hi @Geri044 

Thanks for reporting this, as a Graphic Designer I love when others pays attention to the details. (Some may say this is not just a detail, anyhow...)

I noticed this behaviour many years ago and spend some time investigating if we could align this, without it becoming a massive project or a breaking change, and as you can see I did not succeed. I wont dive into the technical reasons but it has to do with the difference between generic client validation, property specific validation and server validation.

But I can comfort you that this will not be the case in v.14

Since this issue has been open for quite sometime, and still haven't been picked up. Therefor I will close this issue for now, if anyone like to pick up the challenge then lets open the issue again.

Thanks
