### ISSUE TITLE
Large Url causes webhook to be triggered hundreds of times

### ISSUE THREAD

**Issue by rsoeteman** [umbraco/Umbraco-CMS#15321]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

v13.0.0-rc3

### Bug summary

Same issue as https://github.com/umbraco/Umbraco-CMS/issues/15320 but on umbracoWebhookLog table. The url field is to small and therefor the log entry fails and that causes a retry on the webhook

### Steps to reproduce

- Fix the issue in previous issue mannully by increasing the column width to 500
- Create a webhook that does something on publish
- publish a page

### Expected result / actual result

Expected one call to the webhook
Actual Webhook get's called until the webhook is deleted and log is filled with messages like "Unhandled exception in recurring background job."

**Comment by kjac** [comment]
Hi @rsoeteman 😄 

My, oh my. That's no good! We'll get on this ASAP. It indeed looks like it's rooted in the same cause as #15320 - but definitively something to test once #15320 is fixed.

**Comment by nielslyngsoe** [comment]
Fixed by https://github.com/umbraco/Umbraco-CMS/pull/15331
