### ISSUE TITLE
Webhook url column is too small for some webhookurls

### ISSUE THREAD

**Issue by rsoeteman** [umbraco/Umbraco-CMS#15320]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

13.0.0-rc3

### Bug summary

When adding the url below when creating a webhook a YSOD occurs on save.

https://youdontwanttoknowthisazureurl.com:443/workflows/a6dba66fe2d84e2bbfe6bd1868aa7768/triggers/Page_is_published_in_Umbraco/paths/invoke?api-version=2016-10-01&sp=%2Ftriggers%2FPage_is_published_in_Umbraco%2Frun&sv=1.0&sig=_AqqwUgCbOvuKy5iozb6gHUnlory-ggPvon1SDKetno

### Steps to reproduce

Create a webhook and add url below 

https://prod-25.eastus.logic.azure.com:443/workflows/a6dba66fe2d84e2bbfe6bd1868aa7768/triggers/Page_is_published_in_Umbraco/paths/invoke?api-version=2016-10-01&sp=%2Ftriggers%2FPage_is_published_in_Umbraco%2Frun&sv=1.0&sig=_AqqwUgCbOvuKy5iozb6gHUnlory-ggPvon1SDKetno

### Expected result / actual result

Expected, item is saved, actual you get a YSOD

**Comment by kjac** [comment]
Hi @rsoeteman 👋 

Thanks a lot for reporting this! We'll get right on it 👍

**Comment by kjac** [comment]
NOTE: This may be the root cause of #15321 as well. Please make sure to test #15321 once this is fixed.

**Comment by nielslyngsoe** [comment]
Fixed by https://github.com/umbraco/Umbraco-CMS/pull/15331
