### ISSUE TITLE
Delivery API does not expose query strings for content and media URLs

### ISSUE THREAD

**Issue by kjac** [umbraco/Umbraco-CMS#15322]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

V12+

### Bug summary

Query string values seem to be ignored by the Delivery API when outputting _content_ and _media_ links from the Multi URL Picker. It works fine with _external_ links.

### Steps to reproduce

1. Create a content type with a Multi URL Picker.
2. Create some content based on said content type.
3. Add both content, media and external links - all with query strings configured.
4. Request the content through the Delivery API
5. Observe how the query strings are omitted from the content and media links in the Delivery API output.

**Comment by kjac** [comment]
PR in https://github.com/umbraco/Umbraco-CMS/pull/15327

**Comment by elit0451** [comment]
Fixed in: https://github.com/umbraco/Umbraco-CMS/pull/15327
