### ISSUE TITLE
Publishing with Schedule doesn't work correctly

### ISSUE THREAD

**Issue by kpgphoenix** [umbraco/Umbraco-CMS#15340]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

12.3.3

### Bug summary

When node is schedule to be published in the future, it doesn't get published correctly. In the history there is an entry that the node has been published but at the same time in the Publish Menu on the bottom right corner the "Unpublish" option is missing and the node is not available on the content delivery API nor can't it get retrieved by the UmbracoContext.Content.GetById() method when preview is set to false. There is also no ContentPublishedNotification triggered.

<img width="1354" alt="image" src="https://github.com/umbraco/Umbraco-CMS/assets/5524962/baa2b3ed-7edb-42a2-a02a-295a71c4924e">

### Steps to reproduce

Create and save a node
Create a publish schedule for a future date and time
Try to retrieve the the node via UmbracoContext or Content Delivery API after the schedule date.

**Comment by kjac** [comment]
Hi @kpgphoenix,

Thanks a lot for reaching out 👍 

Unfortunately I can't reproduce this. Here's my test on v12.3.3:

### Step 1

I've created some variant content. The content is unpublished in all languages. I have set the Danish language version to be published at a specific time:

![image](https://github.com/umbraco/Umbraco-CMS/assets/7405322/c4d1b0ae-27e7-41d4-ac62-cbcc1cda7dad)

### Step 2

After the publish time, the Danish language variant is published, and the unpublish option appears:

![image](https://github.com/umbraco/Umbraco-CMS/assets/7405322/f2589a08-6d3e-4bab-a31c-867739edebdb)

### Step 3

Querying the specific item for the Danish culture in the Delivery API yields the Danish language variant:

![image](https://github.com/umbraco/Umbraco-CMS/assets/7405322/e284bb83-200c-4db9-a854-0daeeacdb9ca)

### Step 4

Querying all items for the Danish culture in the Delivery API yields the single published item in its Danish language variant:

![image](https://github.com/umbraco/Umbraco-CMS/assets/7405322/897cf18e-dbeb-4333-853e-3e4ee1679017)

If the issue still persists with you, could you please supply additional steps to reproduce?

Could this issue be tied to custom code executing in your site?

**Comment by elit0451** [comment]
Since we cannot reproduce the issue and we haven't heard from you, @kpgphoenix, in a while, I will go ahead and close it. Feel free to reopen it if you can share some more details 🙂 

Have a joyful new year! 🎊
