### ISSUE TITLE
Images picked with media picker are null

### ISSUE THREAD

**Issue by FrontisFrank** [umbraco/Umbraco-CMS#15347]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

10.8.0

### Bug summary

Recently we update the project from 10.7.0 to 10.8.0. Suddenly we notice images are not being displayed in the website while in the backoffice the image is correctly picked and present in the media library. The image is also available through its media link.
I found out I can temporarily find the image in the website if I go to the media library and resave the existing image. But the issue is back as soon the website is released again.

### Specifics

Our media library is structured using folder, the issue does not apply to images that are added to the media root folder or 1 sub folder:
* Images in root work 
* Images in sub folder work 
* Images in sub-sub (- and below) folder do not work 

### Steps to reproduce

I did not test this with a clean install, but as mentioned before we just updated to version 10.8.0

### Expected result / actual result

Actual result is that alot of the media used in the site is not displayed, we want all to be images displayed regardless of their position in the media folder tree

**Comment by FrontisFrank** [comment]
Update, in another Umbraco project we upgraded from version 10.7.0 to 10.8.0 we experienced the exact same issue. In this project we reverted the hotfix back to version 10.7.0 and the issue is gone. I believe the cause of this issue must be within version 10.8.0

**Comment by yawkale** [comment]
try rebuild database cache, it fixed the same issue for me

**Comment by russellshome** [comment]
I have also experienced this issue. Rebuild of database cache did not help. Most images are affected but not all images. In rich text editor an image will display as broken but click to select and click Image Picker and it will display in the dialog normally. When used in a property, the editor shows the image normally but the view acts as if the value is empty.

**Comment by russellshome** [comment]
I upgraded our DB to 10.8.0 and then successfully downgraded to 10.7.0 so it must be possible.
I also tried "UsePagedSqlQuery" : false 
And rebuilt the database cache.
However, this did not fix the problem. I am certain that there is a problem - I had upgraded two sites to version 10.7.0, found the issue, tried the various changes listed above and then decided to downgrade.

**Comment by NikRimington** [comment]
@elit0451 is there an eta for a v10 release to address this? Or is there a nightly build that contains it that we can use? We have a large site being hit by this issue after upgrading to 10.8 to fix another issue so rolling back isn't really an option.

@russellshome how did you downgrade as this isn't typically supported?

**Comment by elit0451** [comment]
No, until the fix is released, we recommend using the following workaround _(mentioned in https://github.com/umbraco/Umbraco-CMS/issues/15195)_ :
> There is a simple workaround for now by disabling cache, but it took me almost five hours to figure out what was the problem when some of my images stopped loading.
```
  "Umbraco": {
    "CMS": {
      "NuCache": {
        "UsePagedSqlQuery" : false
      },
```

**Comment by jdicker-dc** [comment]
We too had this issue. Resaving an image did bring it back until the Memory Cache was rebuild.

The eventual solution for us was indeed the suggested workaround by settings the UsePagedSqlQuery to false. After that manually deleting the cache and restarting the environments all images were indeed back.

**Comment by russellshome** [comment]
> @russellshome how did you downgrade as this isn't typically supported?
NuGet Package Manager - Updates - Choose Umbraco.Cms - Choose 10.7.0 from the list - Update

There doesn't seem to be any issues downgrading from 10.8.0 to 10.7.0

===========

Just to confuse matters, when I tested the same sites this morning that were having issues last week I found that there is now no evidence of a problem in either site after upgrading to 10.8.0. 

I tested a third site and that has no issues after upgrading to 10.8.0

**Comment by nielslyngsoe** [comment]
Since activity is stalled on this issue I assume it was fixed with the release of https://our.umbraco.com/download/releases/1081

Let me know if my assumption is wrong, until that I will close the issue. :-)
