### ISSUE TITLE
Changing the Approved State of a member give an error

### ISSUE THREAD

**Issue by Typad127** [umbraco/Umbraco-CMS#15341]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

13rc3

### Bug summary

Change the Approved variable of a member give an error
![Member approved variable](https://github.com/umbraco/Umbraco-CMS/assets/93042617/0bf71247-786a-4967-91c1-bf1b2ad726f2)

### Steps to reproduce

Create a new member
Change the Approved to false
Save

### Expected result / actual result

The approved variable can be changed and saved

---
_This item has been added to our backlog AB#35687_

**Comment by Zeegaan** [comment]
Fixed in https://github.com/umbraco/Umbraco-CMS/pull/15354
