### ISSUE TITLE
FailedPublishNothingToPublish error on publishing with List View

### ISSUE THREAD

**Issue by Steven4net** [umbraco/Umbraco-CMS#15352]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

12.3.1

### Bug summary

I got a page with List view enabled.
I click on child and select a language to publish for which a document has not been created. (in the case danish)
![image](https://github.com/umbraco/Umbraco-CMS/assets/20970824/362e7ad6-352f-4200-a262-d8c8fcc6c807)
After click publish in the popup i get the following error.
![image](https://github.com/umbraco/Umbraco-CMS/assets/20970824/24594acd-fe68-4494-85d2-103126404513)

The popup to publish a selected page should only include languages for which a document has been created.

### Steps to reproduce

1. Create a page with List view enabled.
2. Enable several languages in the settings section
3. Create a child page with "Allow vary by culture" set true. This page should only be created in one language.
4. Go back to the List view page.
5. Selected the created page.
6. Click publish in the top right.
7. Select a language in which the page has not been created.
8. Click publish in the popup
9. You should now get the error.

### Expected result / actual result

In the popup to publish a page I expect only the languages for which a document has been created.

The actual result is that I get all the language in the popup and when I click to publish for a language for which a document hasn't been created, I get an error.

**Comment by elit0451** [comment]
Here is a video of me reproducing the issue. By the end, I am also showing a workaround.

I will mark it as up for grabs as we would like some help fixing this 🙂 

https://github.com/umbraco/Umbraco-CMS/assets/21998037/0b39fb4a-ae84-4ff4-a37e-ff63894b3a8a

**Comment by nagolucky18** [comment]
I can look at this one.
