### ISSUE TITLE
Items in grid not saving for none of user groups except Administrator

### ISSUE THREAD

**Issue by pariashiri** [umbraco/Umbraco-CMS#15394]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

10.8.0

### Bug summary

I have some groups for members this image is their permissions I haven't changed any of that, but now **Editors** can't save anything inside _Grid_, but **Administrators** can.
![image](https://github.com/umbraco/Umbraco-CMS/assets/151855618/72d7194d-5428-4b62-8d06-a349618fe3ca)
![image](https://github.com/umbraco/Umbraco-CMS/assets/151855618/86f4eee7-160e-4d2d-b1ca-300f491fde86)

I can't see any error or warning not even in the console.
It's really urgent for me to fix, hundreds of users are complaining about

### Steps to reproduce

Log in as an editor and try to save something in Grid.

**Comment by andr317c** [comment]
Hey! Thanks for reporting this issue. I was not able to reproduce it. I tried saving/updating a BlockGridEditor and a GridLayout when I was logged in as an Editor, and I had no issues. Are you able to reproduce this on a clean install? 😄

**Comment by elit0451** [comment]
Since we cannot reproduce the issue and we haven't heard from you, @pariashiri, in a while, I will go ahead and close it. Feel free to reopen it if you can share some more details 🙂

Have a joyful new year! 🎊
