### ISSUE TITLE
IMPORTANT! Security patch breaks backoffice for non-Administrator users

### ISSUE THREAD

**Issue by creativesuspects** [umbraco/Umbraco-CMS#15435]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

8.18.10 and 10.8.1

### Bug summary

After upgrading to 8.18.10 and 10.8.1 the `/umbraco/backoffice/UmbracoApi/Language/GetAllLanguages` endpoint returns a 401 in Umbraco 8 and a 403 in Umbraco 10 for non-Adminstrator users. On 8.18.10 the user gets redirected to the login screen. On 10.8.1 the user sees the backoffice, but the content tree fails to load. Users in the Administrator group can log in without a problem.

https://umbraco.com/blog/security-advisory-security-patches-for-umbraco-8-10-11-and-12-now-available/

### Steps to reproduce

Upgrade Umbraco to version 8.18.10 or 10.8.1 and try to log in using a non-Administrator account.

### Expected result / actual result

Umbraco 8.18.10
![image](https://github.com/umbraco/Umbraco-CMS/assets/161342/b90af140-8298-4167-bd63-4d2545905ebd)

Umbraco 10.8.1
![image](https://github.com/umbraco/Umbraco-CMS/assets/161342/6d0520aa-4baa-4491-af01-2f43264a874f)

**Comment by benbracedigital** [comment]
I have also replicated this issue when trying to access the CSS file that is used for an RTE dropdown. Not sure if the fix will cover that?

Obviously a lot of people are upgrading websites in light of the security alert this morning so an idea of when the new version would be available would be appreciated.

**Comment by Zeegaan** [comment]
Yep that bug has been report here: https://github.com/umbraco/Umbraco-CMS/issues/15434
And will also be covered by the fix 👍

**Comment by AaronSadlerUK** [comment]
@benbracedigital Looks like its out

https://www.nuget.org/packages/Umbraco.Cms/10.8.2

**Comment by paulwoodland** [comment]
We had to downgrade from the security to fix this for our users, as it stopped all the editors from doing their work. I can see that patch to fix it has been released now, so we were going to re-upgrade to get the security patch put back in place, but the package "Umbraco.Cms.StaticAssets" doesn't have a 12.3.5 version, and "Umbraco.Cms" requires at least 12.3.5, so any attempt to upgrade fails. The 10.8.2 package is out, but not the one for v12.

**Comment by paulwoodland** [comment]
> We had to downgrade from the security to fix this for our users, as it stopped all the editors from doing their work. I can see that patch to fix it has been released now, so we were going to re-upgrade to get the security patch put back in place, but the package "Umbraco.Cms.StaticAssets" doesn't have a 12.3.5 version, and "Umbraco.Cms" requires at least 12.3.5, so any attempt to upgrade fails. The 10.8.2 package is out, but not the one for v12.

It looks like it has released now, I've been able to upgrade

**Comment by Zeegaan** [comment]
This should now be fixed in 10.8.2 🚀

**Comment by creativesuspects** [comment]
@bergmania @Zeegaan Might be a good idea to update the links in the security advisory to make sure people don't install the broken patch.

https://umbraco.com/blog/security-advisory-security-patches-for-umbraco-8-10-11-and-12-now-available/

**Comment by lukehook** [comment]
Does this impact v7 for those of us with XLTS?

**Comment by Zeegaan** [comment]
@lukehook V7 should not be affected to the best of my knowledge 😁

**Comment by MartinTiemens** [comment]
We have a few websites in Umbraco Cloud and the update was applied last night, super. The error from yesterday seems to be fixed. We do see a new thing, the bin from both content and media is gone for custom admin groups. We have to add the role 'editor' to get the bin back.

**Comment by Zeegaan** [comment]
@MartinTiemens which version is this on 😁 
If your group doesn't have a start node, that might be causing it.

**Comment by lukehook** [comment]
> @lukehook V7 should not be affected to the best of my knowledge 😁

Thanks, is it possible to get definite confirmation of that from HQ please? Also, is the start node issue noted above something that is likely to also need another patch? (thinking ahead to deployments we had planned today)

**Comment by MartinTiemens** [comment]
We are on the latest version 12.3.5.

The rootnode was set to the first node (homepage) and not to the content root. If I change the rootnode to the content root the bin is back. Now I'm not sure if this is by design and was already there before 12.3.4 or that this changed today.

**Comment by Zeegaan** [comment]
@lukehook there was an official update to the blogpost, and 7 is not included in the issues, so thats the confirmation 😁 https://umbraco.com/blog/security-advisory-security-patches-for-umbraco-8-10-11-and-12-now-available/

**Comment by Zeegaan** [comment]
@MartinTiemens Testing on earlyer versions of 12, you didn't have access to the recycle bin with that either, so luckily no more regeressions It seems (famous last words 🙈 )

**Comment by DORE-PD** [comment]
Famous last words indeed.
Issue still exists. What I did:

- New project with version 12.3.5 created and installed (SQLite as database).
- Creation of a new user group "Test". Selected "Members" for Sections and "Content root" for Content start node.
- New user "Test" created and added to the "Test" group.
- Added a new language in the settings, German (de).
- Created a new empty document type called "Test". Permissions: "Allow as root" and "Allow vary by culture". No property editor added.
- Created and published new content based on the document type "Test".
- Log in as test user -> Same error message as above.

**Comment by DORE-PD** [comment]
![image](https://github.com/umbraco/Umbraco-CMS/assets/141619760/0a3281d8-1a6c-4280-b169-f26175a04236)

**Comment by DORE-PD** [comment]
I will test it further, but I don't seem to have the problem on another machine.
Maybe it is fixed after all and I just have a caching problem here. If I can reproduce it on another machine, I'll let you know again.

**Comment by Reaction77** [comment]
I'm observing the same as DORE-PD, Users require access to the content section in order to view any section tree. This seems to be because the GetAllLanguages() endpoint has had a new authorisation policy added. `[Authorize(Policy = AuthorizationPolicies.SectionAccessContent)]`
https://github.com/umbraco/Umbraco-CMS/commit/73fab105d2314d4e284a46438eea69ff8fb27360#diff-8d8fbe3f2ff9e3c84d8ab1cf337de7e88d7708c41e69d99528bb6ca8f5ffd5f3

**Comment by brano** [comment]
Ufff, this is a fail... Testing team in HQ not having some kind of automated regression testing in place like Cypress, etc.?
Lucky that we were postponing this patch for 10+ on premise websites since we already had these kind of upgrade troubles with Umbraco.

**Comment by DORE-PD** [comment]
Well, I still have the problem.
@Reaction77, you're right. When I add content, everything works.
However, it also works for me without, but only with new projects.
I have now used one of my VMs and created a new Umbraco project there and went through the steps I mentioned above. In the end, everything works, even though the user has no authorisation for content. However, he can see the members and the section tree.
I then copied the project from my local machine (where I do have the problem) to the VM and started it, connected with the same database that I use locally. I made sure that both projects are on version 12.3.5. But I also have the problem on the VM. So it doesn't seem to be a caching problem as I had initially suspected. Obviously something must have gone wrong here during the upgrade?

**Comment by DORE-PD** [comment]
After Umbraco 13 was released today, I have now also updated the project to 13. But the problem still exists there too.

**Comment by Wolfkhan66** [comment]
Please reopen this. This issue still exists on 8.18.11.
Non admin users hit a 401 for umbraco/backoffice/UmbracoApi/Language/GetAllLanguages and get logged back out immediately.

**Comment by Zeegaan** [comment]
@DORE-PD a patch `13.0.1` has been released with a fix for this 🚀

**Comment by DORE-PD** [comment]
Hey @Zeegaan , thanks for the info.
I have now upgraded the project to version 13 again (13.0.1) and now it seems to work as it should.
Will there also be a hotfix for the other major versions (e.g. 12)?

**Comment by bergmania** [comment]
@DORE-PD, yes we will look into that. ETA next week

**Comment by DORE-PD** [comment]
@bergmania Good to hear, thank you!

**Comment by creativesuspects** [comment]
> Please reopen this. This issue still exists on 8.18.11. Non admin users hit a 401 for umbraco/backoffice/UmbracoApi/Language/GetAllLanguages and get logged back out immediately.

I'm also still seeing this issue for Users that only have access to a custom section. Setting 'Content start nodes' and 'Media start nodes' seems to fix this issue, even though these users don't have access to Content or Media.

![image](https://github.com/umbraco/Umbraco-CMS/assets/161342/bc665b35-5434-4130-8f46-d1628056ec1e)

**Comment by Zeegaan** [comment]
@creativesuspects patch 8.18.12 is just out, and should fix this 🚀

**Comment by creativesuspects** [comment]
@Zeegaan @Wolfkhan66 I can confirm that 8.18.12 fixes the issue. Thanks!
