### ISSUE TITLE
Authorization Error when adding stylesheet to Rich Text Editor

### ISSUE THREAD

**Issue by joshgosselin** [umbraco/Umbraco-CMS#15434]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

12.3.4 Cloud

### Bug summary

Umbraco cloud updated to 12.3.4 yesterday, assuming this is related

When an user with Editor permissions goes to a Content Node with Rich Text Editor they are getting and error and RTE doesnt load:

Authorization error: Unauthorized access to URL: /umbraco/backoffice/umbracoapi/stylesheet/GetRulesByName

### Steps to reproduce

As soon as I remove the style sheet from the RTE it loads without issue
If I add permissions to the Setting Tab on the users roles it loads without issue.
I've also tested with a new stylesheet without and styles and the issue remained, so its not anything on this specific style sheet.

### Expected result / actual result

Assuming it is due to this line being added in 12.3.4: 

https://github.com/umbraco/Umbraco-CMS/blob/9f375ede6591eacebc836f8f9cd6b789f9f30097/src/Umbraco.Web.BackOffice/Controllers/StylesheetController.cs#L17C59-L17C59

**Comment by Zeegaan** [comment]
This should now be fixed in 10.8.2 & 12.3.5🚀

**Comment by tenshi04** [comment]
When will this be fixed in 8.18.11 ?
