### ISSUE TITLE
Cannot rename content item in the backoffice, it works only if I click on the Info tab

### ISSUE THREAD

**Issue by MateBalint** [umbraco/Umbraco-CMS#15438]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

12.3.1

### Bug summary

When I create content of my custom document type, after creation the node cannot be renamed, unless I click on the Info tab of the element. I have the this problem with only a specific document type.
![tag](https://github.com/umbraco/Umbraco-CMS/assets/37828673/f6602213-0f57-48c9-af4e-2af63f84441a)

### Specifics

I have a document type called Local Tags Container which stores other document types called Local Tags.
![local-tag-container](https://github.com/umbraco/Umbraco-CMS/assets/37828673/c7ede161-fd90-41f8-b4a7-7abc75a8613d)

The Local Tags don't have any properties set, I only use their name.

### Steps to reproduce

# Document types

### Properties

- Header - Textstring
- Description - Textarea
- Image / Open graph  - Image Media Picker

### Properties

- Header - Textstring 
- Description - Textarea
- Image / Open graph - Image Media Picker
- Grid Content - Content Grid - Block Grid

### Properties

- Urls - Multi URL Picker

## Local Tags Container

- no properties, only used for storing the Local Tags
- Allowed child node types: Local Tag

## Local Tag

- no properties

# Steps to create the content

1. Create a Market Page node
2. Create a Home Page node under the Market Page node
3. Create Local Settings node under the Home Page node
4. Create a Local Tags Container node under the Local Settings node
5. Create a Local Tag node under the Local Tags Container node

The node tree structure should look like this:
![image](https://github.com/umbraco/Umbraco-CMS/assets/37828673/7b1107b4-7bfc-41f4-8138-482045335ac8)

When the Local Tag has been created it cannot be renamed just by clicking on the name field.
![image](https://github.com/umbraco/Umbraco-CMS/assets/37828673/b1a5bbd5-ae06-407a-803f-7612407503c7)

You need to first click on the Info tab next to the Translations and then you can rename the Local Tag.
![image](https://github.com/umbraco/Umbraco-CMS/assets/37828673/72d1bfd1-8054-4612-af65-46966e8d321d)

I haven't seen this problem with any other nodes.

### Expected result / actual result

The Local Tag can be renamed without clicking on the Info tab.

**Comment by Zeegaan** [comment]
Hmmm could you reproduce this on a fresh install ? 🙈 
I cannot reproduce this sadly 😢

**Comment by abjerner** [comment]
Doesn't this happen because the **Translations** content app is active by default, and the page is in readonly mode when a custom content apps is active.

Normally the **Content** content app from Umbraco will be the first one, so this won't be a problem. But if the content type doesn't have any properties, the **Content** content app won't be shown.

**Comment by Zeegaan** [comment]
@abjerner Never seen the translation content app before 🙈 
Is there a way to enable it or 😱

**Comment by abjerner** [comment]
My neither - I'd imagine is a custom content app - hence the readonly mode.

By "the Translations content app is active by default" I mean that it's the first content app shown. 

This for instance also happens with my **Redirects** content app if the content type has no properties:

https://github.com/skybrud/Skybrud.Umbraco.Redirects/issues/175

**Comment by MateBalint** [comment]
The Translation Manager package was added to the project and for the Local Tag document type no properties were added. In these times when you create a Tag element in the backoffice the default tab will be the Translations:
![image](https://github.com/umbraco/Umbraco-CMS/assets/37828673/d9e0639c-5dab-42e6-a820-8098f6d8f25c)
This makes the Tag element to be readonly.
The solution was to add a property to the Tag document type and in this case when you create a Tag element the Content tab will appear right next to the Translations tab and it will be the chosen by default:
![image](https://github.com/umbraco/Umbraco-CMS/assets/37828673/6d23b787-e0fa-4e3c-95e6-ac7c651b4c50)
