### ISSUE TITLE
Error accessing forms for user with Editor rol after updating to 12.3.5 from 12.3.3

### ISSUE THREAD

**Issue by teeto** [umbraco/Umbraco-CMS#15444]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

12.3.5

### Bug summary

![image](https://github.com/umbraco/Umbraco-CMS/assets/1017314/0e5b717a-a737-429d-96f6-4a0c58676ff0)

When editing a form after updating to 12.3.5 it shows a "GetRelations" error.
Only happens for non admin users.
Using Umbraco Forms v12.2.0

### Steps to reproduce

update an umbraco site with umbraco forms v12.2.0 to versioin 12.3.5
edit a form with a non admin user

**Comment by ronaldbarendse** [comment]
Hi @teeto, thanks for reporting this issue. This is actually an issue in Forms 12.2.0 and already reported in https://github.com/umbraco/Umbraco.Forms.Issues/issues/1128. We have a fix ready that will be included in the final 13.0.0 release of Forms and we'll prepare a patch for v12 after that as well.

**Comment by teeto** [comment]
ok, thanks so i have updated back to 12.3.3 until the v12 patch of Umbraco Forms is available
