### ISSUE TITLE
UmbracoAuthorizedController inherits from ControllerBase

### ISSUE THREAD

**Issue by nathangchay** [umbraco/Umbraco-CMS#15475]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

10.6.1

### Bug summary

`UmbracoAuthorizedController` is inheriting `ControllerBase`, when (I believe) it should be inheriting `UmbracoController`. `ControllerBase` (by design) lacks functionality for rendering views, such as the `View()` method and `TempData`.

### Specifics

In Umbraco v8, `UmbracoAuthorizedController` inherits `UmbracoController`, which inherits `Controller`. This allows `View()` and `TempData` to be used in the controller's methods. In v10, `UmbracoAuthorizedController` has been changed to inherit `ControllerBase`, which does not support `View()` or `TempData`. I believe this change was unintentional for a few reasons:

- [The original pull request for this change](https://github.com/umbraco/Umbraco-CMS/pull/10575) does not explain why it was changed or even that it was changed at all. 
- [The Umbraco v10 documentation](https://docs.umbraco.com/umbraco-cms/v/10.latest-lts/reference/routing/authorized#mvc-controllers-for-the-backoffice) says that "If you are using MVC in the backoffice then you would normally inherit from `Umbraco.Cms.Web.Common.Controllers.UmbracoAuthorizedController.`"
- [The author of this blog post](https://www.jondjones.com/learn-umbraco-cms/umbraco-9-tutorials/how-tos/create-a-custom-backend-dashboard-in-umbraco-v9/) encountered the same issue, and it seems like they are a lot more experienced with Umbraco than I am!

Please correct me if I'm wrong and the change was actually intentional! The required code change is very simple, I just wanted to clarify before opening a pull request. 

### Steps to reproduce

1. Create a new Umbraco 10.6.1 project
2. Create a new controller class that inherits `UmbracoAuthorizedController`
3. Add a method and attempt to return `View()` or access `TempData`

![image](https://github.com/umbraco/Umbraco-CMS/assets/46760843/4e90860d-5a24-49ff-9cf5-0ab32be30f10)

### Expected result
`View()` and `TempData` are accessible.
### Actual result
Error `CS0103`.

**Comment by andr317c** [comment]
Hey!
Thanks for creating this issue with really great information 💪!  You are correct about the change being unintentional, but sadly it's not worth fixing since it could be a potentially massive breaking change to implement. We will update the docs so they do not mention the usage of UmbracoAuthorizedController since it is not used.

You can do this "workaround" instead of using the UmbracoAuthorizedController:
```
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Umbraco.Cms.Web.Common.Authorization;
using Umbraco.Cms.Web.Common.Controllers;
using Umbraco.Cms.Web.Common.Filters;

namespace v1061;

[Authorize(Policy = AuthorizationPolicies.BackOfficeAccess)]
[DisableBrowserCache]
public class TestController : UmbracoController
{
    public ActionResult Test()
    {
        TempData["Test"] = "Test";
        return View();
    }
}
```

I will close this issue, please reopen it if you have any additional questions or if the workaround did not fix your issue. 😄
