### ISSUE TITLE
Autofill and tab focus not working in Umbraco 13 backend login via Safari on Mac

### ISSUE THREAD

**Issue by schlagerdk** [umbraco/Umbraco-CMS#15489]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

13.x.x

### Bug summary

These 2 tags (uui-form-layout-item and umb-login-input) in the new login html causes autofill in safari on mac not to work.

On first tab, focus is set on the border of the control, tab again and focus is on the control, but then "required" error message is the shown - Same for the password field

It does work in Chrome, Firefox and Edge.

If I inspect the site and change them to div autofill works and tab to focus on control works

### Steps to reproduce

**Autofill**
Open safari on a mac, go to any umbraco 13  solution /umbraco/login and try to use autofill to login

**Tab/Focus**
Open safari on a mac, go to any umbraco 13 solution /umbraco/login, hit tab on the keyboard and you'll see that border on email field is highlighted and there is no focus in the field, hit tab again and you'll see focus in the field and the required error message is now shown. Enter email and hit tab again, now the border on the password field is highlighted but no focus in the field, hit tab again and now there is focus on the field and again the required error message is shown.

**Comment by elit0451** [comment]
Thanks for reaching out @schlagerdk  👋

I was able to reproduce the issue. As we would like some help fixing this, I will mark it as up for grabs 🙂 

Have a joyful new year! 🎊

**Comment by schlagerdk** [comment]
This issue goes away after updating Safari to version 18
