### ISSUE TITLE
Umbraco 13, Block Grid > RTE > Embedded Block Editors Don't Always Render

### ISSUE THREAD

**Issue by asawyermarathon** [umbraco/Umbraco-CMS#15494]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

13.0.2

### Bug summary

1. RTE fields directly in a document type that have embedded blocks always render correctly
2. Block Grid fields that contain RTE fields that have embedded blocks sometimes render, and sometimes don't.

### Steps to reproduce

1. Start a new Umbraco 13.0.2 site
2. Create a new "Home" doctype with a Block Grid field of alias "content". Select the default "Demo" Block Editors, they will work. Also add a new RTE field, for example "richTextField"
3. Create the front end template view for the home doctype.
4. Create a simple element type to be used as a block editor ("testBlock"). Add a single textstring field of alias "content"
5. Update the datatype settings of the umbBlockGridDemoRichTextBlock rich text editor to accept embedded block editors, select your "testBlock" as an example.
6. Create an embedded RTE Block Editor view file in ~\Views\Partials\RichText\Components\testBlock.cshtml
7. Create a new Home node, populate both fields with an RTE, and embed a block in both. Save and Publish.
8. View the front end. The RTE field will work, the Block Grid > RTE field will not. After some time, after clearing caches and republishing, the Block Grid > RTE field will sometimes render, sometimes not. Try adding multiple RTE instances to the Blog Grid. Some render, others do not.

https://github.com/umbraco/Umbraco-CMS/assets/87725234/76eebdd7-d363-4746-8a31-e450aa6e1f76
https://github.com/umbraco/Umbraco-CMS/assets/87725234/a2d2e4d4-f2a7-48cf-a143-29f70fd1e5b3

![devenv_IPG7t9b3UA](https://github.com/umbraco/Umbraco-CMS/assets/87725234/5e7d3f01-57d0-4a83-b572-62b377f60099)
![devenv_cc2KK2plH1](https://github.com/umbraco/Umbraco-CMS/assets/87725234/eb510ca4-61c2-43b8-a339-f556c4fc094d)
![devenv_ObsTn1AcBg](https://github.com/umbraco/Umbraco-CMS/assets/87725234/25bed50a-b330-43de-b31f-078b3ea99af6)
![chrome_oAr5yMFC96](https://github.com/umbraco/Umbraco-CMS/assets/87725234/bcc03685-8b51-43b7-8b21-eeefe17a4cca)
![chrome_tcgDQe3g2W](https://github.com/umbraco/Umbraco-CMS/assets/87725234/4b06b32d-cbe5-454d-9f09-f0756f5b7b5f)
![chrome_yZof8H5Tif](https://github.com/umbraco/Umbraco-CMS/assets/87725234/66c42a04-2f7a-4562-9f41-521a35491b7f)

**Content:** 
![chrome_K1sLQrbscw](https://github.com/umbraco/Umbraco-CMS/assets/87725234/1561abbe-3b9c-44cf-a176-32e8b8af0c6d)

**Output:**
![chrome_0xY1MThaKT](https://github.com/umbraco/Umbraco-CMS/assets/87725234/f34a1d9e-9cab-4ca1-8c8e-26b77011ae12)

### Expected result / actual result

I expected RTE with an embedded Block Editor to be parsed and the block rendered when in a Block Grid field.

---
_This item has been added to our backlog AB#36554_

**Comment by elit0451** [comment]
Thanks for reaching out @asawyermarathon 👋 and for the detailed description of how to reproduce the issue

I was able to reproduce the issue, so we will take a look.

Have a joyful new year! 🎊

**Comment by nobledm** [comment]
I have discovered some potentially related info ^^

- If a Block is the last element in an RTE it does not render
- If there is any text inserted after the block it does render consistently

I did have a Block render once if it was the last element by editing out some text elsewhere in the rich text. But then it disappeared again after another save.

![image](https://github.com/umbraco/Umbraco-CMS/assets/40868595/3b2a729a-609f-474f-8dba-cb4ec54eeb9b)
![image](https://github.com/umbraco/Umbraco-CMS/assets/40868595/e6d502aa-7724-40e3-a0ec-f621792c3bbe)

**Comment by skttl** [comment]
I noticed that when the block is added, it's added with a class attribute (probably from AngularJS)
![image](https://github.com/umbraco/Umbraco-CMS/assets/3726467/e3cc045f-9415-47e3-9f7b-3e55248b88de)

This makes it not match the Regex found in https://github.com/umbraco/Umbraco-CMS/blob/contrib/src/Umbraco.Infrastructure/PropertyEditors/ValueConverters/RichTextParsingRegexes.cs

So I guess, either the regex should be updated to allow for the class attribute, or the class attribute should be removed somehow.

**Comment by Migaroez** [comment]
fixed in #15583
