### ISSUE TITLE
Backoffice user timeout ignored when using MFA

### ISSUE THREAD

**Issue by ian-cc** [umbraco/Umbraco-CMS#15496]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

13.0.2

### Bug summary

MFA set up exactly as per https://docs.umbraco.com/umbraco-cms/reference/security/two-factor-authentication#two-factor-authentication-for-users on a clean install of 13.0.2 and the user is logged out almost immediately.

### Steps to reproduce

1. Create fresh install of 13.0.2
2. Follow MFA setup for backoffice users from here
https://docs.umbraco.com/umbraco-cms/reference/security/two-factor-authentication#two-factor-authentication-for-users
3. Enable MFA for a user
4. Login to the backoffice using MFA
5. When watching the chrome devtools network view the first call to
/umbraco/backoffice/umbracoapi/authentication/GetRemainingTimeoutSeconds will return 0.00 and force log out
![image](https://github.com/umbraco/Umbraco-CMS/assets/41189870/011b7b32-31e6-4264-a394-e63d3fde8cd0)

### Expected result / actual result

Expected the backoffice timeout to honour the TimeOut value set in appsettings.json or the default 20 minutes which happens fine when MFA is not enabled.

**Comment by mpontin** [comment]
This is still an issue in 13.0.3

**Comment by bergmania** [comment]
I have been able to reproduce

**Comment by bergmania** [comment]
Easy workaround until a fix, is to set `AllowConcurrentLogins` to true.

**Comment by mpontin** [comment]
Thanks, according to the [docs ](https://docs.umbraco.com/umbraco-cms/reference/configuration/securitysettings) `AllowConcurrentLogins` is set to true be default, but looking at code that isn't the case. 

I've tested it though and can confirm that the user doesn't get logged out if it's set to true.

**Comment by Zeegaan** [comment]
Fixed in https://github.com/umbraco/Umbraco-CMS/pull/15562
