### ISSUE TITLE
Unable to link a content across various languages

### ISSUE THREAD

**Issue by wtct** [umbraco/Umbraco-CMS#15498]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

v8, v9, v10, v11, v12

### Bug summary

Hi everyone,

I have just noticed a strange issue with linking between content pages that are not published in all configured languages.

Let me explain this issue with an example.

Please take into account multilingual site designed for two languages: `en` and `de`.

The `en` language is set as default.
The `de` language is set as not mandatory.

Site contains several content pages (sections with children).

All sections use the same document type which varies by culture.
All children use another document type which also varies by culture.

Only some pages have been published for both languages.

Site has a main menu with links to that pages. Menu items are configured with URL picker.

All links work as expected for default language.

Unfortunately, when user change language to `de` by the language switcher, some links are broken in the main menu. Umbraco generates `#` instead of correct URL for pages which are published only in the default language. 

In my opinion, the URL of content in the default `en` language should be used instead. Otherwise, we are not able to link across different languages without providing content for all of them languages.

The same issue occurs for links placed in the Rich Text editor, so we are not able to link between articles written for specific languages only.

Of course, this issue could be solved by custom UrlProvider, but in my opinion it should be a default or configurable behavior.

### Steps to reproduce

Steps to reproduce could be found in the bug summary.

### Expected result / actual result

When generating a URL for any page which varies by culture, Umbraco should return URL of content published in fallback language, then URL of content published in the default language if the content is not published for current culture.

**Comment by Migaroez** [comment]
@wtct I presume the menu url picker is configured to not be variant?

**Comment by wtct** [comment]
Hi @Migaroez,

Happy new year too!

I'm not sure if I understand your argument correctly.

However, I'm satisfied that we are able to implement a CustomUrlProvider with appropriate logic to solve our issue.

You can find more detailed explanation and solution in the "[Problem with linking in Umbraco across pages in different cultures](https://umbracare.net/blog/problem-with-linking-in-umbraco-across-pages-in-different-cultures/)" article.

**Comment by nielslyngsoe** [comment]
Hi @wtct 

An update from here, we will do something about this in the near future. So it will become a possibility in a future version.
Properly 17.2 or 17.3, if it turns out to be a breaking change, then it will be part of 18.
