### ISSUE TITLE
v13 new login screen: Icon color/opacity is not correct

### ISSUE THREAD

**Issue by arknu** [umbraco/Umbraco-CMS#15504]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

13.0.3

### Bug summary

When configuring a custom login provider, the icon does not follow the text color:
<img width="96" alt="image" src="https://github.com/umbraco/Umbraco-CMS/assets/4654741/774290d9-bd37-4d93-858a-95e8027b43b3">

If I make the style Outline instead, the background is white, so the icons does show up:
<img width="104" alt="image" src="https://github.com/umbraco/Umbraco-CMS/assets/4654741/2068eb82-075f-4bca-ba25-77989d992570">

However, it appears to have a lowered opacity, making it gray instead of black. This also looks silly.

Also, previously you could specify a custom color for the button, now you're limited to the UUI primary/warning/danger colors, which is a clear regression, especially if you have multiple login providers and you want to use proper brand colors (eg. Microsoft, Google, Facebook).

### Steps to reproduce

Add a custom login provider
Configure the button to with these options:
```csharp
options.ButtonColor = Umbraco.Cms.Core.Models.UuiButtonColor.Default;
options.ButtonLook = Umbraco.Cms.Core.Models.UuiButtonLook.Primary;
options.Icon = "icon-user";
```

Notice that the icon is shown as black instead of the expected white, making it virtually invisible

### Expected result / actual result

The icon should follow the text color

**Comment by iOvergaard** [comment]
Hi and thanks for letting us know about this. This is fixed in #15534 and will end up in the upcoming 13.1.0 release.
