### ISSUE TITLE
ImageSharp version conflict blocks Umbraco 10 Upgrade

### ISSUE THREAD

**Issue by mirkomaty** [umbraco/Umbraco-CMS#15520]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

10.8.3

### Bug summary

I want to upgrade an older project from 10.8.2 to 10.8.3. But after upgrade the application doesn't run with the following error message:
```
FileNotFoundException: Could not load file or assembly 'SixLabors.ImageSharp,
 Version=2.1.3.0, Culture=neutral, PublicKeyToken=d998eea7b14cab13'. The System can't find the file.
```

### Specifics

This version (2.1.3) of the package is referenced by ImageSharp.Web v. 2.0.2. Umbraco itself adds a package reference to SixLabors.ImageSharp, Version 2.1.6. This is the dll version found in the bin folder.

The error occurs also, if you create a new Umbraco project with version 10.8.3.

Error message:

```
System.Reflection.RuntimeAssembly.InternalLoad(ObjectHandleOnStack assemblyName, ObjectHandleOnStack requestingAssembly, StackCrawlMarkHandle stackMark, bool throwOnFileNotFound, ObjectHandleOnStack assemblyLoadContext, ObjectHandleOnStack retAssembly)
System.Reflection.Assembly.Load(AssemblyName assemblyRef)
Umbraco.Cms.Core.Composing.ReferenceResolver.GetReferences(Assembly assembly)+MoveNext()
Umbraco.Cms.Core.Composing.ReferenceResolver.Resolve(Assembly assembly)
Umbraco.Cms.Core.Composing.ReferenceResolver.ResolveAssemblies()
Umbraco.Cms.Core.Composing.FindAssembliesWithReferencesTo.Find()
Umbraco.Cms.Core.Composing.DefaultUmbracoAssemblyProvider.get_Assemblies()
Umbraco.Cms.Core.Composing.TypeFinder.GetAllAssemblies()
Umbraco.Cms.Core.Composing.TypeFinder.GetFilteredAssemblies(IEnumerable<Assembly> excludeFromResults, string[] exclusionFilter)
Umbraco.Cms.Core.Composing.TypeFinder.get_AssembliesToScan()
Umbraco.Cms.Core.Composing.TypeLoader.get_AssembliesToScan()
Umbraco.Cms.Core.Composing.TypeLoader+<>c__DisplayClass21_0<T>.<GetTypes>b__0()
Umbraco.Cms.Core.Composing.TypeLoader.GetTypesInternalLocked(Type baseType, Type attributeType, Func<IEnumerable<Type>> finder, string action, bool cache)
Umbraco.Cms.Core.Composing.TypeLoader.GetTypesInternal(Type baseType, Type attributeType, Func<IEnumerable<Type>> finder, string action, bool cache)
Umbraco.Cms.Core.Composing.TypeLoader.GetTypes<T>(bool cache, IEnumerable<Assembly> specificAssemblies)
Umbraco.Cms.Core.DependencyInjection.UmbracoBuilderExtensions.AddAllCoreCollectionBuilders(IUmbracoBuilder builder)
Umbraco.Cms.Core.DependencyInjection.UmbracoBuilder.AddCoreServices()
Umbraco.Cms.Core.DependencyInjection.UmbracoBuilder..ctor(IServiceCollection services, IConfiguration config, TypeLoader typeLoader, ILoggerFactory loggerFactory, IProfiler profiler, AppCaches appCaches, IHostingEnvironment hostingEnvironment)
Umbraco.Extensions.UmbracoBuilderExtensions.AddUmbraco(IServiceCollection services, IWebHostEnvironment webHostEnvironment, IConfiguration config)
Umb10_8_3.Startup.ConfigureServices(IServiceCollection services) in Startup.cs

```

### Steps to reproduce

Install the templates for Umbraco 10.8.3:

`dotnet new install Umbraco.Templates::10.8.3`

Create a new Project:

`dotnet new umbraco --version 10.8.3`

Compile and run and you can see the error message instead of the install screen.

### Expected result / actual result

The error occurs while reflecting assemblies to find types. Reflecting the assemblies should support loading newer versions of dependencies.

**Comment by nul800sebastiaan** [comment]
Usually we see errors like this when you have multiple projects in your solution and not all of them use the same version of the dependency. As this is happening on only one machine I'd make sure all machines are in sync with the same codebase. If they are then I would suspect a problem on the specific machine (maybe nuget sources point to a myget feed, getting a wrong version or something like that, make sure to clear all nuget caches thoroughly after changing global feed sources and do a full rebuild of the solution).

**Comment by mirkomaty** [comment]
I did some more research. I added this code to Program.cs:

```
private static Assembly? CurrentDomain_AssemblyResolve( object? sender, ResolveEventArgs args )
{
    if ( args.Name == "SixLabors.ImageSharp, Version=2.1.3.0, Culture=neutral, PublicKeyToken=d998eea7b14cab13" )
    {
        var path = Path.Combine( AppDomain.CurrentDomain.BaseDirectory, "SixLabors.ImageSharp.dll" );
        var ass = Assembly.LoadFrom(path);
        return ass;
    }

    return null;
}
```

The first line in Main() is:

```
AppDomain.CurrentDomain.AssemblyResolve += CurrentDomain_AssemblyResolve;
```

Now the exception disappears and I can set a breakpoint in CurrentDomain_AssemblyResolve(). It turns out, that the assembly version of ImageSharp 2.1.6 is actually 2.0.0.0. This is the manifest in ILDasm:

```
.assembly SixLabors.ImageSharp
{
... lots of lines
  .ver 2:0:0:0
}
```
But the assembly ImageSharp.Web is compiled against version 2.1.3.0:

```
.assembly extern SixLabors.ImageSharp
{
  .publickeytoken = (D9 98 EE A7 B1 4C AB 13 )
  .ver 2:1:3:0
}
```
2.0.0.0 would be a downgrade, which results in the error. The version 2.0.0.0 in the ImageSharp.dll is definitely a bug. 

The question is not, why this reference doesn't work on my machine, the question is, why this reference works on other machines.

**Comment by Zeegaan** [comment]
Good to hear you found a solution, and thanks for the detailed information! 💪
