### ISSUE TITLE
Saving Data Type Removes Slash From Data Type Name

### ISSUE THREAD

**Issue by Nicholas-Westby** [umbraco/Umbraco-CMS#15529]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

13.0.3

### Bug summary

When I save a data type in Umbraco with a name of "True / False", it gets updated to instead be "True  False".

### Specifics

When I save a data type in Umbraco with a name of "True / False", it gets updated to instead be "True  False".

This caused me some problems when I was upgrading from an old install (some code was expecting the name of the data type to be exactly "True / False" like it was previously, but I had to make an edit to the data type, which caused the slash to disappear).

### Steps to reproduce

See steps here in this animation (note that the slash disappears on save):

![true-false-slash](https://github.com/umbraco/Umbraco-CMS/assets/5933222/f6f1b152-4665-4a7b-8156-d4eec08fc11e)

I reproduced this and created the animation in Umbraco 13.0.3, but it also happens in Umbraco 10.

### Expected result / actual result

When I name a data type, the name should be left intact when I save. Since this isn't an alias, I wouldn't expect the name to require any special sanitization.

**Comment by andr317c** [comment]
Hey!
Thanks a lot for reporting this issue! I was able to reproduce this on versions 13.0.3 and 10.0.0.
I will mark this issue as an up for grabs 😄
