### ISSUE TITLE
Telemetry Data Dashboard in backoffice is blank

### ISSUE THREAD

**Issue by alina-tincas** [umbraco/Umbraco-CMS#15538]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

Tested on latest v13: 13.0.3 and v12: 12.3.6

### Bug summary

When installing a new Umbraco CMS locally, in the settings section the telemetry data is not showing anything. 

![image](https://github.com/umbraco/Umbraco-CMS/assets/83591955/8512eac1-ca0e-4400-9d16-9e5db3d31143)

### Specifics

Some errors from telemetry data page:
- from console:
```
angular.js:13692                
       GET https://localhost:44369/umbraco/views/dashboard/settings/analytics.html?umb__rnd=907b19c159c4d9d1a23afeb12e04c1f25c02d4f7 net::ERR_BLOCKED_BY_CLIENT
```
![image](https://github.com/umbraco/Umbraco-CMS/assets/83591955/ecdf7e6f-2743-4fef-88d9-301657fe6be3)

- from Network:
![image](https://github.com/umbraco/Umbraco-CMS/assets/83591955/2839e093-7633-4d7c-a3bc-b0e1d8a773a9)

both pointing to an analytics URL.

### Steps to reproduce

1. Install a new CMS project locally: https://our.umbraco.com/download/releases/1303
2. Spin it up and then when going to settings -> telemetry data you will see it is blank

https://github.com/umbraco/Umbraco-CMS/assets/83591955/12447ced-c993-47a1-9835-ccbe7aa9ab36

### Expected result / actual result

When going to telemetry data in the settings sections you should be able to see more details of all telemetry types and change in between them:

![image](https://github.com/umbraco/Umbraco-CMS/assets/83591955/4436906c-e326-4f59-9077-dc40f7693686)

**Comment by alina-tincas** [comment]
looking further into this error from console: net::ERR_BLOCKED_BY_CLIENT I got upon [this article](https://www.keycdn.com/support/how-to-solve-err-blocked-by-client#:~:text=ERR_BLOCKED_BY_CLIENT%20is%20a%20common%20error,software%20installed%20on%20your%20computer.)

that is when I have tried to disable one of my Chrome extensions called [uBlock Origin](https://chromewebstore.google.com/detail/ublock-origin/cjpalhdlnbpafiamejdnhcphjbkeiagm?pli=1) and now the telemetry dashboard shows as expected 🙈

**Comment by Zeegaan** [comment]
There's not much we can do to fight the block lists, they will just keep updating them, so I will go ahead and close this for now 👍
