### ISSUE TITLE
QR Code icon displays incorrectly

### ISSUE THREAD

**Issue by rbottema** [umbraco/Umbraco-CMS#15539]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

13.0.3

### Bug summary

When selecting the QR Code icon as e.g. a document type icon, it doesn't show the full SVG but only a part of it. This is likely due to the icon having width and height attributes since #14609

### Specifics

![image](https://github.com/umbraco/Umbraco-CMS/assets/963169/4e8159b9-e702-4f3b-aab2-6eb74366ae70)

### Steps to reproduce

- Create new document type
- Select `icon-qr-code`

**Comment by andr317c** [comment]
Hey!
Thanks a lot for creating this issue, and also a PR to fix it 💪. I was able to reproduce this on versions 13.0.3 and 12.3.6

**Comment by nul800sebastiaan** [comment]
Fixed in https://github.com/umbraco/Umbraco-CMS/pull/15540
