### ISSUE TITLE
NotificationHandler doesn't work fine with BackgroundTaskQueue

### ISSUE THREAD

**Issue by jmc18** [umbraco/Umbraco-CMS#15532]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

13.0.3

### Bug summary

I created a NotificationHandler to process information of a CSV file but that file has thousands of records, then  I thought of using a background task so that the notification does not wait until all the records have been processed.

If we don't use the background task we don't have the error, but we cannot upload files because Media Section keeps waiting and when we try to upload the files, the save button stays with the loading indicator.

We have this error in the notification:

**Authorization error: Unauthorized access to URL: /umbraco/backoffice/umbracoapi/media/PostSave Contact your administrator for information.**

Here is the code that we have:

```
public class MediaSavedNotificationHandler(IBackgroundTaskQueue queue, IServiceProvider serviceProvider) 
    : INotificationAsyncHandler<MediaSavedNotification>
{
    public async Task HandleAsync(MediaSavedNotification notification, CancellationToken cancellationToken)
    {
        var mediaItems = notification.SavedEntities;
        foreach (var mediaItem in mediaItems)
        {
            if (mediaItem.Key == MediaNodeIdIdentifiers.MaintenanceProvidersFileNodeId)
            {
                queue.QueueBackgroundWorkItem(async cancellationToken =>
                {
                    using IServiceScope scope = serviceProvider.CreateScope();
                    var maintenanceProviderService = scope.ServiceProvider.GetRequiredService<IMaintenanceProviderService>();
                    await maintenanceProviderService.ImportProviders(mediaItem.Id);
                });
                notification.Messages.Add(new EventMessage("Maintenance Provider Notification",
                    "The Maintenance Providers import process has started and is running in the background.",
                    EventMessageType.Info));
                return;
            }
        }
    }
}
```

Here is the error that we have: 

![image](https://github.com/umbraco/Umbraco-CMS/assets/24300082/0684e704-c820-4e76-9c99-8f8ccdd68b0a)

The records are in the custom table:
![image](https://github.com/umbraco/Umbraco-CMS/assets/24300082/d117710c-a4b7-4939-880a-9641492d6a7c)

Note: Everything is still working and running in the background.

### Steps to reproduce

![image](https://github.com/umbraco/Umbraco-CMS/assets/24300082/43014a50-af45-4a8e-a27a-6b76c8e04854)

![image](https://github.com/umbraco/Umbraco-CMS/assets/24300082/87278075-fc64-4a1d-b03e-23374070ba3a)

**Comment by Zeegaan** [comment]
Setting up your notification handler I'm getting errors 😁 
![image](https://github.com/umbraco/Umbraco-CMS/assets/70372949/f3e77894-9bd6-41b9-b0ac-08193ee3375b)

Could you provide one that works and some steps to follow from a clean install, so I can reproduce this 🙏

**Comment by jmc18** [comment]
Hi @Zeegaan ,

I found the issue and that was my fault, I did not add the file extension to the **AllowedUploadedFileExtensions** settings, so I will close it. 

![image](https://github.com/umbraco/Umbraco-CMS/assets/24300082/e7d997b1-78ee-412e-950a-acba91c82e88)


I apologize

**Comment by Zeegaan** [comment]
All good, just glad you resolved this 💪
