### ISSUE TITLE
Grid editor not saving when CMS user has a start node assigned to them on Umbraco 10.8.2

### ISSUE THREAD

**Issue by borjanv** [umbraco/Umbraco-CMS#15537]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

10.8.2

### Bug summary

Grid editors are not saving if the user has a start node assigned to them in the settings. It happens on Admins as well as editors.
When I remove the start node for that user, the issue goes away.

This started happening after upgrading from 10.6.1 to 10.8.2.

### Specifics

When clicking on the "Save button" in the grid modal window editors get the following issue, and the modal window does not save or close.

![image](https://github.com/umbraco/Umbraco-CMS/assets/12177601/b64123a9-577e-43ad-96a0-04cc7c51c152)

### Steps to reproduce

1. Assign a user with a start node in the settings like the following:
![image](https://github.com/umbraco/Umbraco-CMS/assets/12177601/e9ae0df7-a37e-4658-a74a-b63b6a351e33)

2. Go to a content page that has a grid editor on it and try to add/edit a grid component. You should experience the issue described.

Screenshare of issue (sorry for the low quality but I think you can see the issue):
![Untitled-ezgif com-optimize](https://github.com/umbraco/Umbraco-CMS/assets/12177601/762a0280-5f3b-4a7a-b02e-89e5a65d5b60)

**Comment by Zeegaan** [comment]
Heyo! I'm not entirely quite sure what's meant by "grid modal window" and where that is 🙈 I've never really worked with the legacy grid 😅 
Could you provide me with some reproduction steps on a clean install?
(And maybe a gif would be helpful) 🙏

**Comment by borjanv** [comment]
> Heyo! I'm not entirely quite sure what's meant by "grid modal window" and where that is 🙈 I've never really worked with the legacy grid 😅 Could you provide me with some reproduction steps on a clean install? (And maybe a gif would be helpful) 🙏

@Zeegaan  I just added a gif in the description at the top of the ticket. You can see that clicking Save does not do anything and does not let the user save the grid :(

**Comment by Zeegaan** [comment]
Aha, but how are you getting this modal popped, what kind of grid item is it 🙈

**Comment by bielu** [comment]
@Zeegaan it is DTGE I am 99% sure.
so I am assuming it is related bug to this one:
https://github.com/umbraco/Umbraco-CMS/issues/15572

**Comment by bielu** [comment]
@Zeegaan it is not duplicate! they are related to each other, but they have different basis.
look on versions! :)
but yeah lets wait for Borjan to get back to you.

**Comment by Zeegaan** [comment]
Yea edited the comment 🙈

**Comment by nielslyngsoe** [comment]
I was following some traces here and from the comments on this PR(15572) it sounds like this is fixed. Especially cause the conclusion was that it is a DTGE issue and therefore I will close this one until further information arises.
https://github.com/umbraco/Umbraco-CMS/issues/15572

If you disagree please let me know and re-open this issue, thanks for the care and attention :-)
