### ISSUE TITLE
Error in the Delivery API while surfing in incognito and Google indexing

### ISSUE THREAD

**Issue by bjornnorlen** [umbraco/Umbraco-CMS#15542]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

12.3.5

### Bug summary

We've just built and released a new website which is built upon the Umbraco delivery API. We use fetch to retrieve the data from the API. Each time a visitor navigates to a page we have a method loadPage() that executes to retrieve the correct page and data (data contains the page data):

```
const loadPage = (path) => {
  //state.loaded = false;

  if (path === "/" && appStore.startPageId) {
    path = appStore.startPageId;
  }
  Api.loadPage(path, true)
    .then((response) => {
      console.log("response: ", response);
      if (response.ok) {
        return response.json();
      } else {
        let err = new Error("HTTP status code: " + response.status);
        err.response = response;
        err.status = response.status;
        throw err;
      }
    })
    .then((data) => {
      console.log("data: ", data);
      if (data == null) {
        console.log("data is null when surfing incognito")
      }
```

API is a class with the method loadPage where we are fetching the data:

```
 static loadPage(path, expandAll) {
        const url = `/umbraco/delivery/api/v1/content/item/${encodeURIComponent(path).toLowerCase()}${expandAll ? '?expand=all' : ''}`;
        return fetch(url)
    }
```

This is working fine when surfing normally but when surfing incognito in Edge (not Chrome or FireFox) we receive an error: 

![image](https://github.com/umbraco/Umbraco-CMS/assets/19406378/be935b20-9ee1-48b9-b998-22bd1d84de29)

This is because in the code above, data is null inside .then((data) => …

The meta description element thus has no content value which is a problem because it seems like Google crawls the web in a similar way so the text desription in the search result at Google only contains the text "Error. Cannot read properties of null (reading 'id')" for every page.

### Specifics

Umbraco: 12.3.5
Edge version: 120.0.2210.91 (Official build) (64-bit)
Occurs in incognito in Edge(not Chrome or Firefox) and possibly when Google crawls the web

### Steps to reproduce

1. Create a new Umbraco installation and enable the delivery API
2. Create document types with some content
3. Fetch the data from the delivery API
4. Surf the web in incognito

### Expected result / actual result

Data should not be null when surfing incognito but have the same value as when surfing normally.

**Comment by andr317c** [comment]
Hey!
Thanks for posting this issue. I tried reproducing this on my local Blazor project using the delivery API. Here is a gif:
![ScreenBlazor](https://github.com/umbraco/Umbraco-CMS/assets/73799582/ca6920a7-f8d7-4bce-9022-34f2db195d92)

I will go ahead and close this issue. But if you can reproduce this issue on a clean install or a simple project, please reopen this issue 😄
