### ISSUE TITLE
Crops in Media Picker / Image Cropper are blurry

### ISSUE THREAD

**Issue by bjarnef** [umbraco/Umbraco-CMS#15548]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

12.3.5

### Bug summary

We have a high quality image uploaded to media section.

![image](https://github.com/umbraco/Umbraco-CMS/assets/2919859/f40004eb-74ae-4b22-bf9d-d9ff1b7ac712)

In Media Picker with local crops I noticed crops are blurry, because it only use the thumbnail in cropper.

![image](https://github.com/umbraco/Umbraco-CMS/assets/2919859/c59c43a5-f4d1-4e70-a6f7-6fa744c3f011)

![image](https://github.com/umbraco/Umbraco-CMS/assets/2919859/16883de6-5d87-43e1-babe-714052aceef6)

![image](https://github.com/umbraco/Umbraco-CMS/assets/2919859/e0d02a3e-25aa-496c-a629-5c9bc7ea6885)

### Steps to reproduce

Upload an image to media section in high quality.
Define some crops on Media Picker or Image Cropper.

Noticed preview of image is shown at 500px and crops also used this thumbnail and it looks blurry because it stretch the image.

![image](https://github.com/umbraco/Umbraco-CMS/assets/2919859/a0acdfdb-97ea-48b7-9755-617ca8b81c6d)

### Expected result / actual result

It the Image Cropper use the original size it looks much better, but I think it at least could use an image within max 1000 px width / 1000 px height instead of based on thumbnail image. It would looks much better to content editors.

![image](https://github.com/umbraco/Umbraco-CMS/assets/2919859/8c9bea21-dbac-424a-a4dd-880fba1a3930)

**Comment by bjarnef** [comment]
Especially when zoom is used the difference it clear:

![image](https://github.com/umbraco/Umbraco-CMS/assets/2919859/b71dcdc4-1582-489c-bd1e-dfbe6468484d)

![image](https://github.com/umbraco/Umbraco-CMS/assets/2919859/04975333-36ac-402f-997c-d8f2ea76664d)

**Comment by andr317c** [comment]
Hey!
Thanks for posting this issue. I was able to reproduce it on version 12.3.6 for the Media Picker.
 And also, thanks a lot for creating a PR to fix this issue 😄
