### ISSUE TITLE
.NET 8 OutputCache middleware doesn't work

### ISSUE THREAD

**Issue by shaishavkarnani** [umbraco/Umbraco-CMS#15579]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

version 13

### Bug summary

We want to add Output Caching in Umbraco 13 and have added the code in program.cs

WebApplicationBuilder builder = WebApplication.CreateBuilder(args);

builder.Services.AddOutputCache(options =>
{
    options.AddBasePolicy(b =>
    {
        b.Expire(TimeSpan.FromHours(1));
    }) ;

    options.AddPolicy("Onehour", b =>
    {
        b.Expire(TimeSpan.FromHours(1));
    });
});

builder.CreateUmbracoBuilder()
    .AddBackOffice()
    .AddWebsite()
    .AddDeliveryApi()
    .AddComposers()
    .Build();

// Configure Umbraco Render Controller Type
builder.Services.Configure<UmbracoRenderingDefaultsOptions>(c =>
{
    c.DefaultControllerType = typeof(DefaultController);
});

builder.Services.Configure<UmbracoPipelineOptions>(options =>
{
    options.AddFilter(new UmbracoPipelineFilter("OutputCache")
    {
        PostPipeline = app => app.UseOutputCache()
    });
});

WebApplication app = builder.Build();

await app.BootUmbracoAsync();

app.UseUmbraco()
    .WithMiddleware(u =>
    {
        u.UseBackOffice();
        u.UseWebsite();
    })
    .WithEndpoints(u =>
    {
        u.UseInstallerEndpoints();
        u.UseBackOfficeEndpoints();
        u.UseWebsiteEndpoints();
    });

await app.RunAsync();

### Steps to reproduce

However, it seems when we run the code then it keeps on getting into the Method again and again. This has been working here
https://github.com/umbraco/Umbraco-CMS/issues/13384

Please can you suggest or is this feature no longer works in Umbraco 13

        [OutputCache(PolicyName = "Onehour")]
        public async new Task<IActionResult> Index()
        {
            var masterModel = await _modelLogic.CreateMasterModel(CurrentPage);
            return this.CurrentTemplate(masterModel);
        }

**Comment by elit0451** [comment]
Hi @shaishavkarnani 👋 

Thanks for reaching out! I tried to use the code from the issue you linked and it is working for me. I tried to adapt it so we are explicitly using the `PostPipeline` filter:

```c#
public class OutputCacheComposer : IComposer
{
    public void Compose(IUmbracoBuilder builder)
    {
        builder.Services.AddOutputCache(options =>
        {
            options.AddPolicy(RootController.CachePolicyName, b =>
            {
                b.Expire(TimeSpan.FromSeconds(10));
                b.Cache();
            });
        });

        builder.Services.Configure<UmbracoPipelineOptions>(options =>
        {
            options.AddFilter(new UmbracoPipelineFilter("OutputCache")
            {
                PostPipeline = postPipeline =>
                {
                    postPipeline.UseOutputCache();
                }
            });
        });
    }
}

public class RootController : RenderController
{
    public const string CachePolicyName = "Test";

    public RootController(
        ILogger<RenderController> logger,
        ICompositeViewEngine compositeViewEngine,
        IUmbracoContextAccessor umbracoContextAccessor)
        : base(logger, compositeViewEngine, umbracoContextAccessor)
    {
    }

    [OutputCache(PolicyName = CachePolicyName)]
    public override IActionResult Index()
    {
        return base.Index();
    }
}
``` 
</br>

I can see you are trying to modify the **Program.cs**, and we usually advise using a Composer instead _(as we are also demonstrating in the example)._ Perhaps you can try that?

</br>
Here is my content set-up for reference:

https://github.com/umbraco/Umbraco-CMS/assets/21998037/2bac9451-c5d5-454a-94dd-537b9e300c57

The time is cached correctly for 10s. I will go ahead and close this as we confirmed it is not an actual issue 🙂

**Comment by abhishekcbsm** [comment]
Hi Team,

We have tried eveything as mentioned in above sample but its not working when pushing changes to Cloud (DEV). It is working on local system. Umbraco version is 13.3.0.

**Comment by abhishekcbsm** [comment]
Hi Team,

We have tried eveything as mentioned in above sample but its not working when pushing changes to Cloud (DEV). It is working on local system. Umbraco version is 13.3.0.
