### ISSUE TITLE
Form Disappearing

### ISSUE THREAD

**Issue by ThomasGrant08** [umbraco/Umbraco-CMS#15587]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

13.0.3

### Bug summary

When you try and add some space between some rich text and an umbraco form macro, it removes the form on save.
 To resolve this, you have to leave the content node and re-enter.

### Steps to reproduce

Prerequisites: Utilise Umbraco Forms

1. Create a new form
2. Create a new page with a rich text editor
3. Write some filler text ("description")
4. Press enter to start a new line
5. Insert the form macro

### Expected result / actual result

Expected Result: The form macro saves as part of the rich text.
Actual Result: The form macro is removed from the rich text.

---
_This item has been added to our backlog AB#36972_

**Comment by andr317c** [comment]
Hey! 
Thanks a lot for taking the time to create this issue. I was able to reproduce this issue on version 13.0.3. The Classic editing mode for the RTE(Rich Text Editor) does not save the form macro if you add anything else to the RTE. It also happens to Embeds. But if you are using the Inline editing mode there are no issues adding forms or embeds. So this is an actual bug. I will go ahead and mark this issue as a sprint candidate. 😄

**Comment by palmem29** [comment]
@andr317c, where can I find updates on this issue?

**Comment by BjornFridal** [comment]
> @andr317c, where can I find updates on this issue?

For anyone who hasn't seen this announcement ["Macros will be removed in Umbraco 14"](https://github.com/umbraco/Announcements/issues/14) it may be worth considering replacing your current RTE macros with RTE block items.

**Comment by RachBreeze** [comment]
Hi @andr317c 

I can see this ticket has been accepted in sprint in January, do you have an update please on when there will be a fix? As we are still seeing the issue in Umbraco 13.3.2

Many thanks

Rachel
