### ISSUE TITLE
Implementing the v7 7.15.12 security patch

### ISSUE THREAD

**Issue by damion-daly** [umbraco/Umbraco-CMS#15594]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

7.15.5

### Bug summary

When trying to apply the patch using the zip file as per instructions [here](https://docs.umbraco.com/umbraco-cms/fundamentals/setup/upgrading/version-specific/minor-upgrades-for-umbraco-7#upgrade-manually-from-a-zip-file), on running the application, the installer runs but shows that I'm upgrading from 7.15.5 to 7.15.5.

I had also tried first upgrading to 7.15.11 then applying the patch, but again the installer says upgrading from 7.15.11 to 7.15.11.

The installer completes, but the version has not moved on.

### Steps to reproduce

following the instruction [here](https://docs.umbraco.com/umbraco-cms/fundamentals/setup/upgrading/version-specific/minor-upgrades-for-umbraco-7#upgrade-manually-from-a-zip-file) on a v7 project - copying all files from the bin, Umbraco and Umbraco-Client folders from the zip to the application, then merging config files as required.

### Expected result / actual result

I would expect the installer to inform that the version is moving from 7.15.5 to 7.15.12

**Comment by elit0451** [comment]
Hi @damion-daly 👋 

Thanks for reaching out! I tried an upgrade from both v7.15.5 and v7.15.11 to v7.15.12 (LTS) and I wasn't able to reproduce your issue. I just followed the guide in the documentation:
- Copied over these folders from the .zip file:
  - `/bin`
  - `/Umbraco`
  - `/Umbraco_Client`
- Merged:
  - `/Config` folder
  - updated the `web.config` file in the root of the site - and I did make sure to copy back the version number, and the connection string as they were
</br>

And the installer looked correct in my case:

![7 15 5](https://github.com/umbraco/Umbraco-CMS/assets/21998037/67d5cb4e-2723-4c91-be71-925766761b33)
![7 15 11](https://github.com/umbraco/Umbraco-CMS/assets/21998037/d9f637a4-aaa5-4fc1-b4ed-9b4fddd1b5f4)
![Version](https://github.com/umbraco/Umbraco-CMS/assets/21998037/9e7c4eb7-8b72-4f90-a2d5-cb4540c0d025)

</br>

I will go ahead and close this as we verified it is not an issue on a clean site upgrade. 🙂
