### ISSUE TITLE
Log Viewer CSS error with magnifying glass svg on saved searches

### ISSUE THREAD

**Issue by drummerboy46** [umbraco/Umbraco-CMS#15614]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

13.1 release candidate

### Bug summary

![Screenshot 2024-01-19 141131](https://github.com/umbraco/Umbraco-CMS/assets/6703035/c11d52bf-1da1-453f-9d8c-5fa647bd7242)

![Screenshot 2024-01-19 141312](https://github.com/umbraco/Umbraco-CMS/assets/6703035/5f632eea-8e0a-41e7-92b7-913ff54df4bc)

SVG has broken out of its inline position

### Specifics

Error with CSS

### Steps to reproduce

Go to log viewer

### Expected result / actual result

inline images missing with one giant magnifying glass appearing top right - see s/s

**Comment by drummerboy46** [comment]
I realised almost as quickly as I posted this that a DXP/plugin was the cause. I've posted the bug to the developer and you close this down

**Comment by andr317c** [comment]
Hey!
I'll go ahead and close this issue, since it was related to DXP
