### ISSUE TITLE
External login provider error messages no longer rendered from ViewDataExtensions.TokenExternalSignInError 

### ISSUE THREAD

**Issue by dataworking** [umbraco/Umbraco-CMS#15622]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

13.0.3

### Bug summary

We have a custom external login provider, when any error is encountered in there it returns a RemoteAuthenticationHandler failure response which gets caught in the asp.net middleware and is dealt with by exception handler middleware (ie, the last chance exception catcher) as there seems no way to return this to directly to Umbraco. From the exception handler we set a cookie with the error message as follows

context.Response.Cookies.Append(ViewDataExtensions.TokenExternalSignInError, Convert.ToBase64String(Encoding.UTF8.GetBytes(someerrormessage)), new CookieOptions() { HttpOnly = true, Secure = true }); 

and redirect to the Umbraco login screen.

This get processed and rendered automatically by Umbraco 11 on the login screen as an error using the Html.AngularValueExternalLoginInfoScriptAsync(externalLogins, ViewData.GetExternalSignInProviderErrors()!) by the builtin Umbraco.Cms.StaticAssets/umbraco/UmbracoBackOffice/Default.cshtml

In Umbraco 13 with the new login screen, there seems to be no way to render these error messages, so external provider login messages do not display.

### Steps to reproduce

Return a HandleRequestResult.Fail from any external login provider implementing RemoteAuthenticationHandler

### Expected result / actual result

Expect there to be some way to display errors from external providers in the login screen.

---
_This item has been added to our backlog AB#37110_

**Comment by iOvergaard** [comment]
Hey, thanks for taking the time to write this issue. It is much appreciated! I can confirm this does not work with the new login screen yet.

It seems to have something to do with a missing implementation detail around the handler in BackOfficeController.cs:

https://github.com/umbraco/Umbraco-CMS/blob/e04c4a89adcbe73d35290a993713a5faf4dc55ff/src/Umbraco.Web.BackOffice/Controllers/BackOfficeController.cs#L468

We will get this sorted and fixed.

**Comment by iOvergaard** [comment]
Hello again, we were able to figure out a solution with #15715 and the fix will be released in the upcoming 13.2 release.
