### ISSUE TITLE
Setting a lot of node restrictions on a user causes a browser error

### ISSUE THREAD

**Issue by seanrockster** [umbraco/Umbraco-CMS#15631]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

v10

### Bug summary

We've added a new user and selected the nodes and media nodes that are accessible. Possibly more than 20. It appears all that data is saved to a cookie, one massive cookie, and the browser cannot handle the size.

### Specifics

Can login, but then the site crashes, not a crash perse, its more a case of the browser cannot handle the cookie size.

### Steps to reproduce

create a new user
assign permissions to specific nodes and media folders (a lot, like >20 or > 30)
login, the backoffice will blank, i.e. no menu options
refresh your page and you will get a browser error.

### Expected result / actual result

backoffice with menu and content tree

**Comment by elit0451** [comment]
Hi @seanrockster 👋 

Thanks for reaching out! Just to clarify, you are setting granular permissions for more than 20/30 nodes on the user group of your newly created user? And you are also logging in with the new user when you see a blank backoffice?

**Comment by seanrockster** [comment]
Hi, I was adding under Content Start Nodes. I can login, I get the backoffice without a menu or content tree. If i refresh the browser I get a generic browser error but in the dev tools there is something about the cookie being too large.

**Comment by elit0451** [comment]
Hi again, thanks for clarifying!

I tried to reproduce and I am not getting any errors. Can you spot if I am doing something wrong?


https://github.com/umbraco/Umbraco-CMS/assets/21998037/355810f0-e36a-4bd0-866e-6a4c6253d51a

**Comment by seanrockster** [comment]
Hi

Yes this is what we were doing, its possible its content related, not sure. For now we've removed the configuration.
