### ISSUE TITLE
API path parameters with dots cause incorrect query results in controllers

### ISSUE THREAD

**Issue by scottbrightman** [umbraco/Umbraco-CMS#15640]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

13.0.3

### Bug summary

When using an UmbracoApiController class, the same Umbraco query returns invalid results if an action parameter is passed as a path parameter rather than a query parameter, and the parameter value contains a "." character. Specifically the problem was found when querying using a IPublishedContent.Name.

### Specifics

The following selects a content item by type and name:

```
 [HttpGet]
 [Route("/api/contexyhelp/{itemname}")]
 public IActionResult ContextHelpItemByName(
[Required] string itemname)
 {
     using (var contextReference = this.contextFactory.EnsureUmbracoContext())
{
    if (contextReference.UmbracoContext != null)
    {
        var contentCache = contextReference.UmbracoContext.Content;

        if (contentCache != null)
        {
            var contentItemList = contentCache.GetAtRoot().DescendantsOrSelfOfType("contextHelp", "en-gb").ToList();
            var contentItem = contentCache.GetAtRoot().DescendantsOrSelfOfType("contextHelp", "en-gb").Where(x => x.Name == itemname).FirstOrDefault();
        }
    }
}
```
If I have a document called "Tour.Dates" and call /api/contexyhelp/Tour.Dates
contentItemList  contains items with a missing Name property. 
contentItem will be NULL

Changing the Rout to:

[HttpGet]
[Route("/api/contexyhelp")]

calling /api/contexyhelp/?itemname=Tour.Dates

contentItemList  contains items with a correct Name property. 
contentItem will be the document named "Tour.Dates"

### Steps to reproduce

Create a new 13.0.3 CMS install. 
Create a test document in the tree with a Name containing a "." character like "Tour.Dates".
Add an UmbracoApiController and inject IUmbracoContextFactory.

```
public class TestController : UmbracoApiController
{
    private readonly IUmbracoContextFactory contextFactory;
    public TestController(IUmbracoContextFactory contextFactory)
    {
        this.contextFactory = contextFactory;
    }
```

Run the code specified in Specifics above using appropriate default culture and document type alias,

### Expected result / actual result

I expect parameters passed as path parameters to UmbracoApiController actions that query Umbraco content, to behave the same as if they were passed as query parameters, even when the parameter contains a "." character.

**Comment by Migaroez** [comment]
hey @scottbrightman, I was not able to reproduce this. I simplified the setup by putting the handling logic in a private function to isolate the difference between using the the FromRoute and Query parameters.

I created a home doctype with default template and no properties.
This is my content structure
![image](https://github.com/umbraco/Umbraco-CMS/assets/6025797/c0fcb0cb-770c-4232-b4eb-0265bcf2036b)

```
using System.ComponentModel.DataAnnotations;
using Microsoft.AspNetCore.Mvc;
using Umbraco.Cms.Core.Web;
using Umbraco.Cms.Web.Common.Controllers;

namespace Umbraco.Cms.Web.UI.Code;

public class TestController : UmbracoApiController
{
    private readonly IUmbracoContextFactory _contextFactory;

    public TestController(IUmbracoContextFactory contextFactory)
    {
        _contextFactory = contextFactory;
    }

    [HttpGet]
    [Route("/api/contexthelp/{itemname}")]
    public IActionResult ContextHelpItemByName(
        [Required] string itemname)
    {
        return Ok(ContentName(itemname));
    }

    [HttpGet]
    [Route("/api/contexthelp/")]
    public IActionResult ContextHelpItemByNameparam(
        [Required] string itemname)
    {
        return Ok(ContentName(itemname));
    }

    public string? ContentName(string itemName)
    {
        using (var contextReference = _contextFactory.EnsureUmbracoContext())
        {
            if (contextReference.UmbracoContext != null)
            {
                var contentCache = contextReference.UmbracoContext.Content;

                if (contentCache != null)
                {
                    var rootItems = contentCache.GetAtRoot();
                    var contentItem = rootItems.DescendantsOrSelfOfType("home", "en-us").Where(x => x.Name == itemName).FirstOrDefault();
                    return contentItem?.Name;
                }
            }

            return "ERROR"; // so we have a difference between a null contentItem and something else going wrong
        }
    }
}
```

Both of these results give me the content name
![image](https://github.com/umbraco/Umbraco-CMS/assets/6025797/198e5884-95eb-4087-b032-382a32642dc0)

**Comment by Migaroez** [comment]
Hey Scott, thank you for sending the little project. It seems the bug only appears when you have multiple languages setup and variation enabled, which I did not.

Looking into it further.

**Comment by Migaroez** [comment]
Today I learned: We do not invoke part of our request middleware when the MVC framework considers a request to be client side. Part of this is setting the the variationContext. Because this is not set, the name of the content item can not be resolved and is set to an empty string (which is peculiar)

Because you use a route template with paramater binding, the paramater becomes part of the route that mvc uses to determine whether it is a clientside request.

To fix this, you can either add a slash at the end of the route `[Route("/api/contexthelp/{itemname}/")]`.
Or implement a small function that we check to determine if we should ignore the ClientSide nature of a request: https://docs.umbraco.com/umbraco-cms/reference/routing/custom-routes#client-side-requests

Hope this clears things up!
