### ISSUE TITLE
RTE content is no longer indexed when used on an element in the block list editor

### ISSUE THREAD

**Issue by ptilsed** [umbraco/Umbraco-CMS#15654]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

13.0.3

### Bug summary

After upgrading a site to V13 we've noticed that the RTE content found in element types added to a content block list no longer seems to be added to the examine index correctly. 

### Specifics

This issue appears to be related to the RTE datatype now being stored in JSON format within the block list data where as previously it was stored as the raw HTML:

![image](https://github.com/umbraco/Umbraco-CMS/assets/1157593/94d118d6-6ce5-45e5-a0db-9f62c1901c56)
V12

![image](https://github.com/umbraco/Umbraco-CMS/assets/1157593/bc1cf39e-ff72-4ef0-9364-44076923797d)
V13

This change seems to result in the JsonPropertyIndexValueFactoryBase class being used to index the content which is returning an empty string when attempting to index the content of the RTE.

Other property types such as text areas and textbox's are being indexed correctly so this seemed limited to the RTE. This property normally contains most of the useful indexable content however so it's impact on the search is quite high. 

### Steps to reproduce

Spin up a new V13 install and create an element type that consists of a RTE property, enable it on a block list editor that is found on any published pages that should be indexed. Add some content and check if the RTE value is added to the any of the examine indexes. 

### Expected result / actual result

The content stored in an RTE used on an element type added to a block list should be indexed as it was in previous versions

**Comment by BillyDigi** [comment]
I'm also having this issue after upgrading a project to v13.
Asked around on the forums (https://our.umbraco.com/forum/using-umbraco-and-getting-started/113499-block-grid-not-indexing-rich-text-editors) but had no reply yet.

I'll keep an eye on this issue, hope the team picks it up asap.

**Comment by Migaroez** [comment]
Hey Paul, Thank you for bringing this to our attention. I have confirmed this is still the the case for 13.1.0 and it looks like a nasty regression bug, we will pick this up asap

**Comment by ptilsed** [comment]
@Migaroez Thanks for the update, it had us digging around for a while but glad it's been the tracked down and the fix looks pretty straight forward.

**Comment by Migaroez** [comment]
Thank you for pointing me in the right direction, which meant I could fix it easily!
