### ISSUE TITLE
Server election picks the wrong role in Azure App Service, or scheduled publish doesn't work with a Subscriber

### ISSUE THREAD

**Issue by jrunestone** [umbraco/Umbraco-CMS#15658]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

12.3.6

### Bug summary

When leaving the server role election process to Umbraco it is set to "Subscriber" when it should be set to "Single" when hosted in a (non-load balanced) Azure App Service (at least I think it's wrong).

### Specifics

The background here is that when the role is "Subscriber" our notification handlers for `ContentPublishedNotification` are not being processed while performing a *scheduled publish* in a non-load balanced environment.

They are processed however if I set the server role explicitly to "Single".
I don't know if it should matter but clearly it does :)

I haven't checked the source yet, but how is the automatic election performed? Why is it picking "Subscriber" over "Single" once we're in an Azure App Service environment?

This particular environment is not load balanced, and we're using non-load balanced app settings. I have yet to confirm whether this problem occurs in our load balanced apps but there we set the roles explicitly to Publisher/Subscriber. If it occurs there too, it would be a problem with the "Subscriber" role and scheduled publishing.

I found this thread describing the same issue: https://our.umbraco.com/forum/using-umbraco-and-getting-started/112633-why-does-scheduled-publishing-not-hit-any-of-the-publish-notifications

### Steps to reproduce

* Write a notification handler for `ContentPublishedNotification` and log something in the handler
* Write the currently assigned server role to the log somewhere in the startup of the site or in a controller
* Publish your site to an Azure App Service (single instance, non-load balanced app settings)
* Schedule a publish for a new page
* Check the logs for your log message after the scheduled time has passed

To make testing easier add some code to set the server role explicitly between "Single" and "Subscriber" depending on an app setting and run the test cases again, observing the difference.

### Expected result / actual result

* The handler is not triggered and the log message is not logged.
* The server role log message says "Subscriber"

I would like to assume that the role should be set to "Single" and the handlers are triggered.

**Comment by Migaroez** [comment]
Hey Johan, the hot swappable nature of webapps might be interfering with the detection of a load balanced setup as this can result in 2 application pools connecting to the same database.

**Comment by Migaroez** [comment]
Since the docs state that it is recommended to manually set server roles, I will close this ticket.

**Comment by dawoe** [comment]
Hi @jrunestone 

Notificationhandlers hooking into changing content, media, members, doctypes etc... are only fired on servers that are set to Single or Publisher.

If you want to hook into changes on a Subscriber server you should hook in to corresponding cache refresher events.
See https://docs.umbraco.com/umbraco-cms/reference/notifications/cacherefresher-notifications

I think the docs could be improved on this.

Dave

**Comment by jrunestone** [comment]
@dawoe OK if that's the case then I'm ok with closing this issue and instead opening an issue (or just a pr directly ofc) on the docs tracker. Thanks.

Just a side question since it might be related, my custom indexes aren't rebuilt automatically on the Subscriber when I tell the Publisher to rebuild them. Is this affecting this too? I have a separate ticket on that, just thought I should ask.

**Comment by dawoe** [comment]
@jrunestone I think that is related as well. The dashboard only rebuilds the index on the server you are currently on.

Dave

**Comment by jrunestone** [comment]
@dawoe Thanks a lot for your input, if you're right this explains a lot.
