### ISSUE TITLE
Nested Content Template Alias issue

### ISSUE THREAD

**Issue by deanleigh** [umbraco/Umbraco-CMS#15693]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

13.1.0

### Bug summary

Nested content alias where the property editor is used no longer display the correct output but instead display the full markup.
This appears due to the addition of Blocks in RTE

### Specifics

I have a site upgraded from v8 to v13 that uses Nested Content.
For some of the Element type we use `{{propertyAlias}}` and this works fine.
However, for some we use an another alias, in this case `{{wFtPropTitle}}` is the title of a feature using the RTE.
So instead oof returning 'Hello World' it returns 
`{"markup":"<p>Hello World</p>","blocks":{"layout":null,"contentData":[],"settingsData":[I]]`

### Steps to reproduce

Create a nested content item
Add an RTE as the element type
Test with {{propertyAlias}} - this should work fine
Then replace {{propertyAlias}} with the the contents of the RTE e.g.  {{rteText}}
This will display the text with all the markup rather than the desired text

### Expected result / actual result

I would expect the output of the RTE without the text
I actually get all the markup

**Comment by nul800sebastiaan** [comment]
Also see https://discord-chats.umbraco.com/t/16235701/resolved-umbraco-13-block-list-custom-view-breaking-change-r and the fix listed on https://github.com/umbraco/Umbraco-CMS/pull/15029#issuecomment-1878525293 

Note that this is one of the breaking changes listed on https://docs.umbraco.com/umbraco-cms/fundamentals/setup/upgrading/version-specific - so we'll close this one and refer people to issue #15029

**Comment by thomashdk** [comment]
Hi

Just saw this.. I getting this in may razor view ?

![image](https://github.com/umbraco/Umbraco-CMS/assets/6445636/59e9746f-762a-49af-9413-5210efcc245e)

The raw source looks like this:

![image](https://github.com/umbraco/Umbraco-CMS/assets/6445636/371ee898-465d-4ee1-b172-3612e5fb5c2f)


The issue happen after upgrade from 12.3.5 to 13.1.0.

I can see other Umbraco 13 sites has the same issue. Ex. if you google **","blocks":{"contentData":[],"settingsData":[]}}** 

If I add a new component with our nested content and fill out the rich text editor for som text, it prints this out:

![image](https://github.com/umbraco/Umbraco-CMS/assets/6445636/ebdc02f5-6861-4c6a-b52d-69627b33701d)


Not all rich text with text before upgrade are doing this...

**Comment by thomashdk** [comment]
I just checked our dev site and after upgrade the text in rich text are fine, until I republish nodes with rich text content..

Before publish:

![image](https://github.com/umbraco/Umbraco-CMS/assets/6445636/df7aeef3-96e5-4a2f-92ee-5d333e737e30)

After publish:

![image](https://github.com/umbraco/Umbraco-CMS/assets/6445636/e8d77c84-5123-42bb-a684-01adb8c47052)

Don't this is a to big of a issue .. :)

**Comment by thomashdk** [comment]
The index looks like this.

![image](https://github.com/umbraco/Umbraco-CMS/assets/6445636/8c3aa1f9-b870-43a5-9877-c6ba9b8ac711)

If I try to render the text using modelsbuilder. Then the text is null..

**Comment by thomashdk** [comment]
https://github.com/umbraco/Umbraco-CMS/issues/15701
