### ISSUE TITLE
v14: Allow `OperationIdSelector` to work for non CMS APIs

### ISSUE THREAD

**Issue by mattbrailsford** [umbraco/Umbraco-CMS#15716]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

v14

### Bug summary

The `OperationIdSelector` adds operation ID's to swagger specs via convention such that when generating OpenAPI client implementations in JS, the client method names are short and meaningful.

However the `OperationIdSelector` is tied to only work with API's in the `Umbraco.Cms.Api` namespace meaning all other Umbraco products that support headless API's do not benefit from this helper and so there client method names are extremely long.

### Steps to reproduce

Review any headless API spec for any other Umbraco product and it won't have the `operationId` entry in it's swagger spec. 

### Expected result / actual result

Other Umbraco products should be able to make use of this helper

---
_This item has been added to our backlog AB#38100_

**Comment by mattbrailsford** [comment]
Looks like it should do the trick for me yea 👍

**Comment by elit0451** [comment]
Fixed in https://github.com/umbraco/Umbraco-CMS/pull/15771
