### ISSUE TITLE
MemberDefaultLockoutTimeInMinutes doesn't seem to work (Umbraco 13.0.3)

### ISSUE THREAD

**Issue by JeroenRoos** [umbraco/Umbraco-CMS#15712]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

13.0.3

### Bug summary

When setting the "_MemberDefaultLockoutTimeInMinutes_" in the appsettings, the Member still can't login again after the time is elapsed, and the Member still appears locked in the Members section in Umbraco.

After setting this to 1 minute in the appsettings, it still doesn't seem to unlock the Member again. Is there something I'm missing, is this the intended functionality, or is this appsetting ignored when locking the Member?

### Steps to reproduce

Add the following to the appsettings.json:

`"Umbraco": {
  "CMS": {
    "Security": {
      "MemberPassword": {
        "MaxFailedAccessAttemptsBeforeLockout": 1
      },
      "MemberDefaultLockoutTimeInMinutes": 1
    }
  }
}`

Then try logging-in with an invalid password, and you will see in the Member section in Umbraco that it's locked-out, and the "Last lockout date" also has a value.

After waiting more than 1 minute, the Member is still locked-out, also when trying to login again, or when restarting the application, the Member is still locked-out.

### Expected result / actual result

I expected the Member to be unlocked again, after the time period has passed, either automatically, after trying a new login attempt, or at a restart. This doesn't seem to be the case.

**Comment by andr317c** [comment]
Hey!
Thanks for reporting this issue. I was able to reproduce this on version 13.1.1. I will go ahead and mark this issue as up for grabs 😄

**Comment by ideo2** [comment]
probably this is the issue:
![UserLockoutTime](https://github.com/umbraco/Umbraco-CMS/assets/127977482/95634830-d443-420f-915b-6de9503e124c)
![MemberLockoutTime](https://github.com/umbraco/Umbraco-CMS/assets/127977482/1be42253-e063-4ae6-b028-68f7fd1a8c50)

**Comment by nul800sebastiaan** [comment]
Fixed in https://github.com/umbraco/Umbraco-CMS/pull/16832
