### ISSUE TITLE
umbracoRedirect Requires Template

### ISSUE THREAD

**Issue by photogsy** [umbraco/Umbraco-CMS#15724]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

13.1.1

### Bug summary

In the past you could create a Doc Type with no template and give it an umbracoRedirect property, and this would work fine in the content tree.

I tried to do the same in 12.x and 13.x and it doesn't work - you get the page not found page, UNLESS you give the Doc Type a template.

### Steps to reproduce

1. Create a new document type _without_ a template
2. Give it a property named ```umbracoRedirect``` with a content picker editor.
3. Allow it wherever you need in the node tree.
4. Add a node of this type, save & publish.
5. Visit the node address and note that you are NOT redirected.

### Expected result / actual result

You should be redirected to the node in the tree that you selected.

**Comment by andr317c** [comment]
Hey! 
Thanks for reporting this issue! I was able to reproduce this on versions 10.8.4, 12.3.7, and 13.1.1. This is an actual issue and it should be able to redirect without a template. This worked on version 8. I will mark this issue as an up for grabs 😄

**Comment by CodeBunTes** [comment]
I can have a look at this one if no one else is already working on it.

**Comment by steroberts89** [comment]
@emmagarland is it possible to get this fix applied to v13?

**Comment by emmagarland** [comment]
@steroberts89 hi, I will see if @nul800sebastiaan is planning to cherry-pick it into v13 when he's available.

**Comment by nul800sebastiaan** [comment]
Have cherry-picked for 13.6.0.
