### ISSUE TITLE
Log Viewer randomly throws exception "Sequence contains no elements"

### ISSUE THREAD

**Issue by cor13on3** [umbraco/Umbraco-CMS#15720]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

8.18.11

### Sometimes Log Viewer throws an excpetion as at the screenshot below:

![obraz](https://github.com/umbraco/Umbraco-CMS/assets/25120042/f0e6790e-bad9-40db-8401-60de4918ac16)

"**Sequence contains no elements**" error message is thrown by `.Min()` method, which is called in `LogViewerSourceBase.GetLogLevel()` method. This method is responsible for providing minimum logging level from Serilog config line. It's used only in `LogViewerController`. 

### Specifics

For filtering log levels it uses `ILogger` interface provided by Serilog, but for some reason sometimes that `.Where()` clause returns no values and in consequence `.Min()` method throws exception.

![obraz](https://github.com/umbraco/Umbraco-CMS/assets/25120042/78910049-5a02-4263-ac0a-039a5c8cf1a6)

I can see that it's secured by our own in newer versions of Umbraco, by adding the `.DefaultIfEmpty` clause in this query. 
It has been implemented [in that commit](https://github.com/umbraco/Umbraco-CMS/commit/3e50333a3b26119adaa3daf2c90ef302fefe8af7).

### Steps to reproduce

1. Run Umbraco v. 8.18.11.

2. Go to Settings

![obraz](https://github.com/umbraco/Umbraco-CMS/assets/25120042/a6a8225a-dc14-4376-a04b-d4fc016ef4a4)

3. Go to Log Viewer

![obraz](https://github.com/umbraco/Umbraco-CMS/assets/25120042/1d2f0d55-06ca-4963-87b4-2a7805c990c6)

### Expected result / actual result

Now, I'd like to apply that change also for Umbraco 8 to fix the Log Viewer.

**Comment by nul800sebastiaan** [comment]
Closed through https://github.com/umbraco/Umbraco-CMS/pull/15722
