### ISSUE TITLE
Error Mesage when clicking on the three dots to access create menu for content item which doesn't allow child types and editor has access to the settings section and the site is running in Production Mode

### ISSUE THREAD

**Issue by marcemarc** [umbraco/Umbraco-CMS#15758]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

12.3.7

### Bug summary

This is super-obscure and only really raising it as it might be a good first-time issue for someone...

Here goes....

We are talking about what happens when you click the three dots, on a node to try to create something underneath:

![image](https://github.com/umbraco/Umbraco-CMS/assets/260802/5ad80104-b280-4d5f-ad7b-1f16899e7306)

In this example 'Guides' doesn't allow any document types to be created under it.

So Editors get a slidey out panel that says, you can't create anything here...

... but ...

if you are a super editor who has access to the 'Settings' section, then you'll get an option to 'Edit permissions for this Document Type'

![image](https://github.com/umbraco/Umbraco-CMS/assets/260802/c164eef4-d9ed-4251-88a6-a73d5391b837)

That's handy!

But not if your environment's runtime is set to be production Umbraco:CMS:Runtime:Mode (https://docs.umbraco.com/umbraco-cms/fundamentals/setup/server-setup/runtime-modes)

In this mode, backoffice editing things are disabled and instead of seeing this button to click to edit permissions (which you can't do in production runtime mode) - you get the following error

![image](https://github.com/umbraco/Umbraco-CMS/assets/260802/593888cd-25dc-408c-b959-52d6557714c3)

So I think in runtime production mode we just need to update this panel, so it doesn't try to request the API, and just says the same message as the editors you can't create things here... 

It's not a show stopper! - but might be interesting for someone to dig into etc

### Steps to reproduce

See steps above

### Expected result / actual result

Just a message to say you can't create things here

**Comment by Migaroez** [comment]
@marcemarc Nice find, I will mark it as up for grabs.

**Comment by prjseal** [comment]
Thanks for raising this @marcemarc, I'm gonna try and work on it at the hackathon today

**Comment by marcemarc** [comment]
yey good luck @prjseal gutted I can't be there this time to hack away too.

**Comment by prjseal** [comment]
@marcemarc PR raised, above. Fingers crossed.
