### ISSUE TITLE
There is no paste option for Grid Area if area has only one item

### ISSUE THREAD

**Issue by stefanstankovic** [umbraco/Umbraco-CMS#15755]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

13.1.1

### Bug summary

If you create a Grid model that has one or more Areas where each Area has the ability to add only one type, then you will not be prompted to choose an Item for that Area but you will immediately get a dialog to create an Item because it is the only one available for that Area.

![image](https://github.com/umbraco/Umbraco-CMS/assets/15331581/8185c7b3-6c19-47fe-baba-199671dd4565)

That's fine, but if you already have an Item in the Area, there is an option for Paste, but since the dialog where you can choose the Block is skipped, there are no paste options.

![image](https://github.com/umbraco/Umbraco-CMS/assets/15331581/d766fdad-3f88-4d11-8b76-18de524ea9ac)

The possibility of copying exists directly on the Item, so it would be good to have the option for paste as well.

![image](https://github.com/umbraco/Umbraco-CMS/assets/15331581/6f9b59bd-164b-45d5-8be5-227ecb3c9d43)

### Steps to reproduce

To successfully reproduce this bug, you need to create 2 Grid blocks. One block can be a simple block that can only have text, while the other block should have an area where only the first block can be added, from 0 to an infinite number of times.

On the page, add a Grid and add block number two, then in the area of ​​that block, add several block number ones.

Copy block number one from the list of blocks.

By clicking on adding a new block, you will get a dialog to create a block.
The option for Paste is not possible.

### Expected result / actual result

It would be good to have an additional check on [line 863 in the file umbBlockGridPropertyEditor.component.js](https://github.com/umbraco/Umbraco-CMS/blob/contrib/src/Umbraco.Web.UI.Client/src/views/propertyeditors/blockgrid/umbBlockGridPropertyEditor.component.js#L863) 
`if (availableTypes.length === 1 && vm.clipboardItems.length == 0)`
Show Add a new block only if there is nothing in the clipboard. If an item exists in the clipboard, show the create dialog so the editor can use the clipboard or choose to create a new module.

I could fix that, but I'm not sure if it would be good to check if the clipboard contains the exact block that we can add in the area.

**Comment by Migaroez** [comment]
Hey @stefanstankovic, thank you for the detailed bug report and some work towards a possible solution.
This seems to be an oversight that needs some love. I think you are on the right path and it would indeed be wise to check whether the clipboard holds items you can actually paste (if that is possible)

I presume the actual paste dialog filters this out already, so you might be able to look there for some inspiration. Feel free to start up a PR to address this issue and the community PR team will help you guide it into a good state.

Have a nice weekend!

**Comment by mikecp** [comment]
Closing as per merge of the associated PR.
