### ISSUE TITLE
V13 [NEW LOGIN UI] Customizing the 2FA login screen

### ISSUE THREAD

**Issue by MihailichenkoPavel** [umbraco/Umbraco-CMS#15781]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

13.1.1

### Bug summary

I'm trying to customize my 2FA login screen per the docs https://docs.umbraco.com/umbraco-cms/reference/security/two-factor-authentication#customizing-the-login-screen, but I see only the default view instead of my custom view

### Specifics

I'm trying to debug in the browser and I found it in **auth.repository.ts** returns only status and error in the login function, but **postlogin** endpoint returns other data as well
![login](https://github.com/umbraco/Umbraco-CMS/assets/30054370/30e0224f-05a2-47dc-879f-6d7efadd9208)
![image](https://github.com/umbraco/Umbraco-CMS/assets/30054370/b1809e38-57ff-4944-9164-88e402a479f8)

### Steps to reproduce

Just follow the docs. I'm using the code from there.
![image](https://github.com/umbraco/Umbraco-CMS/assets/30054370/9265bae1-e79f-403d-911f-4e8f80cfab48)
![image](https://github.com/umbraco/Umbraco-CMS/assets/30054370/8a1466f9-5360-4162-a43a-7a6f1a5a5c29)

### Expected result / actual result

The expected result is the custom 2FA login screen.

The actual result is the default 2FA login screen.

**Comment by MihailichenkoPavel** [comment]
I've created PR https://github.com/umbraco/Umbraco-CMS/pull/15798  to fix it.

**Comment by nul800sebastiaan** [comment]
Fixed in https://github.com/umbraco/Umbraco-CMS/pull/15798
