### ISSUE TITLE
Not possible to create content att content root level with Swedish as user language

### ISSUE THREAD

**Issue by jesperStoltDizparcHSTD** [umbraco/Umbraco-CMS#15833]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

13.1.0

### Bug summary

If the user has Swedish as user language and tries to create any new content at content root level, the save button turns to an `x` and the content does not get created.

### Specifics

The only errors it gives is the bellow two in the console log ant it seams to be connected to the `PostSave` method.
![image](https://github.com/umbraco/Umbraco-CMS/assets/156076450/018efb9d-431e-4bc0-b6fe-67981ca512e5)

### Steps to reproduce

1. Create a new Umbraco Project with `dotnet new umbraco --name MyProject`
2. Move inte to project and run `dotnet run`
3. Select SQL Server as Database, and configure a new database (Not sure if it is exclusive to SQL Server)
4. Create a new document type and set it to allow as root (it does not need any properties)
5. Set language for the logged in user to Sweidish
6. Create a node of the type you created
7. Give it a name and hit save

### Expected result / actual result

The node should be saved an exist in the content tree.

**Comment by nul800sebastiaan** [comment]
Fixed in https://github.com/umbraco/Umbraco-CMS/pull/15737
