### ISSUE TITLE
Cannot replace default RenderController with Generic controller type

### ISSUE THREAD

**Issue by mohsin-patel** [umbraco/Umbraco-CMS#15846]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

13.1.1

### Bug summary

Replacing the default `RenderController` with a generic version e.g. `FooRenderController<T>` results in an application error on startup:

```
InvalidOperationException: The controller type ProjectName.FooRenderController`1[T] does not follow conventions, MVC Controller class names must be suffixed with the term 'Controller'
```

### Steps to reproduce

Create a generic controller which inherits from `RenderController`, e.g:

`public abstract class FooRenderController<T> : RenderController {}`

Register the controller at startup:

```csharp
services.Configure<UmbracoRenderingDefaultsOptions>(c =>
{
     c.DefaultControllerType = typeof(FooRenderController<>);
});
```
Run the site

### Expected result / actual result

Expected:
To be able to register a generic `RenderController` type.

Actual:
An `InvalidOperationException` is thrown on application start.

**Comment by nielslyngsoe** [comment]
Hi @mohsin-patel as you haven't answered the question from @Migaroez I will assume you have found a solution, maybe the related issue fix has resolved your needs? Or maybe it is not as relevant any longer?

Anyhow, as I find it hard for us to continue fixing this without the intended use case that you like to solve. Then I will close the issue. If you still have the need for this, please let us know and re-open the issue.

Thanks in advance
