### ISSUE TITLE
Abstract keyword on Custom Renderer Controller not working

### ISSUE THREAD

**Issue by mohsin-patel** [umbraco/Umbraco-CMS#15851]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

13.1.1

### Bug summary

![aa](https://github.com/umbraco/Umbraco-CMS/assets/6478470/aa74b43d-327d-47e0-9cdc-52887c316989)

### Specifics

**If we Replace Umbraco's default RenderController with custom called "BaseRenderController"   and add "abstract" method defined  its stop working with following message** 

![error-5](https://github.com/umbraco/Umbraco-CMS/assets/6478470/45e25d28-494f-4023-9458-184d54078a21)

### Steps to reproduce

- Add abstract keyword to custom render class 

```
public abstract class MyRenderController : RenderController
     {
        public MyRenderController(ILogger<RenderController> logger, ICompositeViewEngine compositeViewEngine, IUmbracoContextAccessor umbracoContextAccessor)
            : base(logger, compositeViewEngine, umbracoContextAccessor)
        {
        }

        public abstract IActionResult Render();

        public override IActionResult Index()
        {
            // Add some custom logic here.
            return CurrentTemplate(CurrentPage);
        }
    }
```

### Expected result / actual result

it should render Index Method of custom base render controller. 

also, it should support generic BaseRenderControler Class

**Comment by Migaroez** [comment]
hey @mohsin-patel this is a duplicate issue raised by yourself. Please supply feedback on the question asked on the original issue.
https://github.com/umbraco/Umbraco-CMS/issues/15846
