### ISSUE TITLE
14.0.0-beta001: GetPagedRelationsForItem throws exception

### ISSUE THREAD

**Issue by AndyButland** [umbraco/Umbraco-CMS#15866]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

14.0.0-beta001

### Bug summary

Calling the method noted to retrieve relations for a page throws an exception of:

```
SqlException: Incorrect syntax near the keyword 'key'.
Incorrect syntax near the keyword 'key'.
Incorrect syntax near the keyword 'key'.
Invalid usage of the option NEXT in the FETCH statement.
```

### Specifics

I think the first two syntax issues are caused by the field `key` not being wrapped with `[key]` when the SQL is generated.  Possibly `UnionHelperDto.Key` needs an attribute of `[Column("[key]")]`?  But not sure, as can see we have other DTOs that don't seem to need these brackets.

### Steps to reproduce

The following code illustrates the issue (which I've put in a view):

```
@inject ITrackedReferencesRepository TrackedReferencesRepository
@inject IScopeProvider ScopeProvider

@{
    using (var scope = ScopeProvider.CreateScope())
    {
        var relations = TrackedReferencesRepository.GetPagedRelationsForItem(
            Guid.Parse("7af493ff-ed1c-4d37-96e3-78c261f93bbc"),
            0,
            1,
            true,
            out long totalRecords);
        <div>Total records: @totalRecords</div>
    }
}
```

I also see it pop up when browsing to the "Info" tab for content items in the tree.

### Expected result / actual result

Should return details of relations and not throw exception.

**Comment by bergmania** [comment]
Thanks for reporting. This is one of these annoying differences between SqlServer and Sqlite. `key` is a keyword in Sqlserver.
 
 I'll look into a fix

**Comment by Zeegaan** [comment]
Looks like we've forgotten to close this 😁 
FIxed in https://github.com/umbraco/Umbraco-CMS/pull/16020
