### ISSUE TITLE
Password Length Tooltip Mismatch After AppSettings Change in Umbraco 10.8.3

### ISSUE THREAD

**Issue by kometa333** [umbraco/Umbraco-CMS#15874]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

10.8.3

### Bug summary

After altering the appsettings.json to require a 16-character minimum for passwords as shown below:
"Security": {
        "UserPassword": {
          "RequiredLength": 16
        }
      }
I noticed that while the system's functionality and the error prompts on the CMS password update interfaces have reflected this change, the guidance tooltip "newPasswordFormatLengthTip" displayed on the page following a password reset link – which is sent via email – has not.  The text there still continues to advise a 10-character minimum.

### Steps to reproduce

1. Open the appsettings.json file located in the root directory of the Umbraco installation.
2. Navigate to the Security section and locate the UserPassword configuration.
    Modify the RequiredLength under UserPassword to 16, to enforce a 16-character minimum length for passwords. The modified section should look like this:
    json
    Copy code
    "Security": {
      "UserPassword": {
        "RequiredLength": 16
      }
    }
3. Save the changes to the appsettings.json file and ensure the Umbraco application is restarted to apply the changes.
4. Navigate to the CMS password update interface to trigger a password reset email.
5. Follow the password reset link sent via email to the password reset page.
6. Observe the guidance tooltip next to the password input field.

### Expected result / actual result

**Expected Result:**
The guidance tooltip, identified by the key newPasswordFormatLengthTip, should display information consistent with the appsettings.json configuration, advising users to enter a password with a minimum of 16 characters.

**Actual Result:**
Despite the appsettings.json file being updated to require a 16-character minimum for passwords, the guidance tooltip still advises users to enter a password with a minimum of 10 characters.

**Comment by NguyenThuyLan** [comment]
Thanks @kometa333 for reporting this issue. I can confirm this is a bug we want to fix. This is password length tooltip that is need to be fix. 
![image (1)](https://github.com/umbraco/Umbraco-CMS/assets/116753400/4f06af1f-e0c8-4247-a34c-1791e51206dc)

**Comment by NguyenThuyLan** [comment]
Sorry, I just checked the LTS & EOL status for Umbraco CMS. Umbraco 10 entered the security phase on June 16, 2024. 
The issue has been fixed in version 13.
You can upgrade to Umbraco 13.
Therefore, I will close this issue.
