### ISSUE TITLE
Security settings don't apply properly 

### ISSUE THREAD

**Issue by Aki-Gra** [umbraco/Umbraco-CMS#15876]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

version 13.1.1

### Bug summary

When trying to change the password validation fails to apply new settings. 

### Specifics

appsettings
![image](https://github.com/umbraco/Umbraco-CMS/assets/80265078/92807526-8ee6-4663-834f-05eb8dfd3d5a)
when we look at the member details we can already see that the length is incorrect 

![image](https://github.com/umbraco/Umbraco-CMS/assets/80265078/eddecdb6-39f6-4929-8fa6-d020502d07c3)
it does not recognise special chars.  
![image](https://github.com/umbraco/Umbraco-CMS/assets/80265078/3c34f337-b90c-4bf1-a869-46eb358b254b)
when we try to save it obviously fails. 
![image](https://github.com/umbraco/Umbraco-CMS/assets/80265078/7b6b756a-591f-449c-b46e-f237228751f1)

### Steps to reproduce

it also fails in front end website
a simple reset password form 
![image](https://github.com/umbraco/Umbraco-CMS/assets/80265078/30798454-50f5-4953-9be5-552503c5b95a)
![image](https://github.com/umbraco/Umbraco-CMS/assets/80265078/f91657e1-4d3f-4629-9402-e8fb2a0bf241)
returns too short (Ab112233*)
![New Bitmap image (3)](https://github.com/umbraco/Umbraco-CMS/assets/80265078/638e4d83-9c73-4afe-be17-13dd0496af79)

### Expected result / actual result

expected applies security settings. actual result visually applies the requirement for special char but does not validate it. ChangePasswordWithResetAsync works as expected. but not ChangePasswordAsync

**Comment by Aki-Gra** [comment]
Anyone?

**Comment by Migaroez** [comment]
Hey @Aki-Gra 
I tried to reproduce this with just 1 change to the settings (password length) and my test controller picks up the changes and the backoffice client seems to respect the value. I have zipped up the solution for you with the database included, username/pass is test@test.test

[MemberPasswordTest.zip](https://github.com/umbraco/Umbraco-CMS/files/15166479/MemberPasswordTest.zip)

Few things on the top of my head that might help you identify the issue
- Copy over the test controller I made into your solution and hit the endpoint `/api/memberpassword` Your configured changes should be in there, if not then the options pattern is not loading your changes
- Are you applying these settings in the right file? 
- Is this on your local machine, if not are you overwriting the settings during deployment?
- Did you change anything that has to do with the IOptions pattern?

On a side note for future reports: we greatly appreciate complete code examples in the reproduction steps where possible as print screens might cause the following issues
- Increases the time to reproduce from simply copy pasting
- Having to guess what else might be just off screen
- Mistyping of code you wrote correctly
- Accidently correcting things you might have written incorrectly
- ...

**Comment by Aki-Gra** [comment]
App settings had errors. closing issue thank you for the help.
