### ISSUE TITLE
Umbraco starts very slowly due to TypeLoader / TypeFinder

### ISSUE THREAD

**Issue by PerplexDaniel** [umbraco/Umbraco-CMS#15875]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

13.2.0

### Bug summary

The Umbraco startup time compared to a vanilla ASP.NET Core MVC app is unacceptably long -- a fresh Umbraco 13.2.0 needs roughly **16 seconds** to fully boot while a new MVC app is pretty much instant at 1-2 seconds. 

I recently discovered that 90%+ of Umbraco's startup time is spent by [`TypeLoader`](https://github.com/umbraco/Umbraco-CMS/blob/contrib/src/Umbraco.Core/Composing/TypeLoader.cs) + [`TypeFinder`](https://github.com/umbraco/Umbraco-CMS/blob/contrib/src/Umbraco.Core/Composing/TypeFinder.cs) which are used to find various types such as `IComposer` / `IPropertyValueConverter` / `SurfaceController` etc.

In my simple test, 15 out of the total 16 seconds is spent finding all the types in loaded assemblies which sounds completely insane:

![image](https://github.com/umbraco/Umbraco-CMS/assets/24297947/f501cb64-4758-480f-b9f8-de35c8b6603a)

It seems that it is faster when running repeated `dotnet run` commands. After a `dotnet clean`, however, it is always slow. Probably whenever any assembly has changed (so any new release of your website) it will be slow.

I suspect the complex logic in [`TypeFinder`](https://github.com/umbraco/Umbraco-CMS/blob/contrib/src/Umbraco.Core/Composing/TypeFinder.cs) is iterating through all assemblies way more times than necessary but have not debugged this yet. 

Note that 16 seconds is for an empty Umbraco installation. In a more serious website of ours it takes at least 25 seconds to find all types so unfortunately the delay gets only worse when more assemblies are being used in the site -- which makes sense since there are more assemblies to scan through.

I have seen this behavior in Umbraco 10 websites we have, but `TypeLoader` seems to be part of Umbraco since at least v7 so I am afraid Umbraco boot times have been unnecessarily slow for 10+ years already.

------------------

### Update

The slowdown is caused by [`ReferenceResolver.ResolveAssemblies`](https://github.com/umbraco/Umbraco-CMS/blob/contrib/src/Umbraco.Core/Composing/ReferenceResolver.cs#L69) which loads every single .dll file that is found in the bin folder, doing essentially this:

```csharp
foreach (var dll in Directory.EnumerateFiles(dir ?? string.Empty, "*.dll"))
{
    AssemblyName.GetAssemblyName(dll); // <- this takes 50-400ms PER DLL
}
```

I think it would make a lot of sense if the filters applied [later](https://github.com/umbraco/Umbraco-CMS/blob/contrib/src/Umbraco.Core/Composing/ReferenceResolver.cs#L90) would _also_ be applied to the file name of the DLL, in that way bypassing the slow `AssemblyName.GetAssemblyName(dll)` call.

That is, if a file is called `System.Linq.dll` (for example), we should already skip it since `System.` is part of `TypeFinder.KnownAssemblyExclusionFilter`. Currently we only apply the those filters _after_ the assembly has already been loaded which doesn't really make sense.

So these filters apply to assemblyName at the moment but should also be applied to the filename. I will probably make a PR for that which should improve performance on startup a lot.

```csharp
// don't include if this is excluded
if (TypeFinder.KnownAssemblyExclusionFilter.Any(f => assemblyName.FullName.StartsWith(f, StringComparison.InvariantCultureIgnoreCase)))
{
    continue;
}

// don't include this item if it's Umbraco Core
if (Constants.Composing.UmbracoCoreAssemblyNames.Any(x => assemblyName.FullName.StartsWith(x) || (assemblyName.Name?.EndsWith(".Views") ?? false)))
{
    continue;
}
```

### Steps to reproduce

1. `dotnet new install Umbraco.Templates::*`
    - To ensure you run this on the latest version of Umbraco (13.2.0 at this moment)
3. `dotnet new umbraco -n UmbracoBoot`
4. `cd UmbracoBoot`
5. Open `appsettings.Development.json`, change `Serilog:MinimumLevel:Default` to `Debug`:
```json
{
  "$schema": "appsettings-schema.json",
  "Serilog": {
    "MinimumLevel": {
      "Default": "Debug" // <- Set to Debug instead of Information
    }
}
```
6. `dotnet run`
7. Observe the first few lines of output in the log and see type loading takes insanely long.
    - Look for the difference in times between these 2 lines:
        - `[hh:mm:ss DBG] Getting Umbraco.Cms.Core.Dashboards.IDashboard: scanning assemblies.`
        - `[hh:mm:ss DBG] Got Umbraco.Cms.Core.Dashboards.IDashboard, caching (true).`
        - The time spent between these 2 lines makes up for 90%+ of the boot time.

### Expected result / actual result

Umbraco should boot in a few seconds similar to a vanilla ASP.NET Core MVC app but instead takes at least 15-20 seconds which is getting worse and worse the more assemblies are added to the project.

**Comment by dawoe** [comment]
Hi @PerplexDaniel 

I just looked in to this on a 12.3.7 website of ours. I don't see the slowness there

![image](https://github.com/umbraco/Umbraco-CMS/assets/1193822/c8dd9ed9-2f6f-46d5-9201-ee05e62214fb)

**Comment by PerplexDaniel** [comment]
Hi @dawoe this seems to occur only with "new" assemblies, i.e. after a rebuild / `dotnet clean`. Do you not see this when you first run `dotnet clean` followed by a `dotnet run`?

**Comment by PerplexDaniel** [comment]
I have added a PR that also applies the existing assembly filters defined in [`TypeFinder.KnownAssemblyExclusionFilter`](https://github.com/umbraco/Umbraco-CMS/blob/contrib/src/Umbraco.Core/Composing/TypeFinder.cs#L24) and [`Constants.UmbracoCoreAssemblyNames`](https://github.com/umbraco/Umbraco-CMS/blob/contrib/src/Umbraco.Core/Constants-Composing.cs#L13) to the DLL file names _before_ actually loading the assemblies. 99% of the time the file name (without extension) is exactly equal to the assembly name. The filter afterwards is kept so even if the file name is not equal the original filter will still catch it later, nothing should be impacted with this PR.

This already cuts down the time spent in [ReferenceResolver.ResolveAssemblies](https://github.com/umbraco/Umbraco-CMS/blob/contrib/src/Umbraco.Core/Composing/ReferenceResolver.cs#L69) by roughly 50% for me (16s -> 8s). 

This can be further improved by configuring `Umbraco:CMS:TypeFinder:AdditionalAssemblyExclusionEntries` in `appsettings.json`. This is an existing setting (**not** introduced by this PR) which allows specifying assemblies to skip. Previously this didn't do much since Umbraco loads all assemblies anyway so skipping them afterwards doesn't impact performance but now with this PR it will skip them before loading them, greatly improving startup speed.

With my PR and this list of additional exclusions the time spent in [ReferenceResolver.ResolveAssemblies](https://github.com/umbraco/Umbraco-CMS/blob/contrib/src/Umbraco.Core/Composing/ReferenceResolver.cs#L69) goes from 16 seconds to **1 second** 🎉

This list should probably be added to [`TypeFinder.KnownAssemblyExclusionFilter`](https://github.com/umbraco/Umbraco-CMS/blob/contrib/src/Umbraco.Core/Composing/TypeFinder.cs#L24)

```json
"Umbraco": {
  "CMS": {    
    "TypeFinder": {

      // Exclude Umbraco dependencies that will not contain any of the types Umbraco is scanning for anyway...

      "AdditionalAssemblyExclusionEntries": [
        "Asp.Versioning.",
        "Azure.Core,",
        "Azure.Identity,",
        "BouncyCastle.",
        "Dazinator.",
        "DotNet.Glob,",
        "J2N,",
        "K4os.Compression.LZ4,",
        "MailKit,",
        "MessagePack,",
        "MessagePack.",
        "MimeKit,",
        "NCrontab,",
        "NPoco.",
        "NUglify,",
        "OpenIddict.",
        "Polly,",
        "Polly.",
        "SixLabors.",
        "Smidge,",
        "Smidge.",
        "Swashbuckle."
      ]
    }
  }
}
```

**Comment by dawoe** [comment]
@dawoe I did a clean from visual studio. Made some changes in code and did a full rebuild.
I am running on IIS by the way.

But for me it was still fast

**Comment by PerplexDaniel** [comment]
@dawoe For me it also occurs on IIS on a beta server of ours:

![image](https://github.com/umbraco/Umbraco-CMS/assets/24297947/eaf83f1b-03fe-4b74-8aff-8fb600fbcad4)

When I kill the `w3wp.exe` process and restart the site it is again slow with otherwise unchanged DLLs:

![image](https://github.com/umbraco/Umbraco-CMS/assets/24297947/959ddd00-3208-46b3-98df-365c2b8d190a)

**Comment by nul800sebastiaan** [comment]
FYI: had to set this in appsettings.development.json to get the debug output as shown in this issue.

```json
  "Serilog": {
    "MinimumLevel": {
      "Default": "Debug"
    },
```

I am also having problems reproducing this, I have no IIS (nor IISexpress installed on the machine I'm testing on now, but also have never seen this delay in the past on other machines with various configurations (even after a clean/rebuild).
To be fair it is a very fast, new machine. 

![image](https://github.com/umbraco/Umbraco-CMS/assets/304656/08ae3644-ebef-4a97-9ab5-905ee8c64426)

So I tried the same on my old machine, which indeed does things a little slower for sure, but absolutely nowhere near a horrible 16 seconds. 

![image](https://github.com/umbraco/Umbraco-CMS/assets/304656/5ae9cd8e-2323-4531-b11d-149fc28461c4)

Are you sure that something else isn't interfering here? Virus scanners come to mind, they probably don't like it when you try to load dll metadata, they would like to make sure you're not trying to load harmful dlls. Company policy is to use windows defender and I do have an exception on some directories so it doesn't interfere with my dev files too much. 
When I try this on a site that is outside of the exceptions, then it takes a second longer to do that scan, but still pretty fast.

**Comment by nul800sebastiaan** [comment]
These were all v13 sites with a starter kit installed, so not quite clean, but no customizations either.

**Comment by PerplexDaniel** [comment]
My machine is also new so that should not be the issue. But I cannot rule out it's a virus scanner or something similar, although it also happens in our beta environment. 

I'll try to reproduce in Umbraco Cloud :-)

**Comment by dawoe** [comment]
@PerplexDaniel @nul800sebastiaan 

I just tried to reproduce on a clean 13.2.0 install.

![image](https://github.com/umbraco/Umbraco-CMS/assets/1193822/23ee5e93-32c4-4e6b-a4cd-f10047a77868)

I also tried this on various projects on my machine going from latest 10, latest 12 and latest 13.

I can't reproduce

**Comment by PerplexDaniel** [comment]
@dawoe Thanks for all your attempts. Very strange that in our office environment everyone seems to have it so that would point to some software related issue here. I will try to test in some other environments including Azure. The first Umbraco Cloud attempt is 3 seconds, quite slow but of course not 16-20 sec like we have here. Not sure if w3wp is getting completely killed when restarting the site from the Umbraco.io portal though.

![image](https://github.com/umbraco/Umbraco-CMS/assets/24297947/7a2e8fbf-2c89-486f-9e34-44ee5886b27e)

**Comment by nul800sebastiaan** [comment]
> Not sure if w3wp is getting completely killed when restarting the site from the Umbraco.io portal though.

Yes, that's exactly what it does, not just restart the site, it completely kills the process.

**Comment by PerplexDaniel** [comment]
I'll close this since it's not really caused by Umbraco directly but rather anti virus.
