### ISSUE TITLE
Upgrade v12 to v13 throws error

### ISSUE THREAD

**Issue by enkelmedia** [umbraco/Umbraco-CMS#15872]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

13.2.0

### Bug summary

After upgrading a v12 site to v13 there is an exception thrown on each start from the newly introduced `DataTypeSplitDataCollector`.

### Specifics

It seems like the error is related to some custom property editors that's installed. Looks like this:

```
System.AggregateException: One or more errors occurred. (An item with the same key has already been added. Key: NewsletterStudio.TransactionalEmailPicker)
 ---> System.ArgumentException: An item with the same key has already been added. Key: NewsletterStudio.TransactionalEmailPicker
   at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
   at System.Collections.Generic.Dictionary`2.Add(TKey key, TValue value)
   at System.Linq.Enumerable.ToDictionary[TSource,TKey](IEnumerable`1 source, Func`2 keySelector, IEqualityComparer`1 comparer)
   at Umbraco.Cms.Infrastructure.Migrations.PreMigration.DataTypeSplitDataCollector.Handle(UmbracoApplicationStartedNotification notification)
   at Umbraco.Cms.Core.Events.INotificationHandler`1.Handle(IEnumerable`1 notifications)
   at Umbraco.Cms.Core.Events.NotificationHandlerWrapperImpl`1.<>c__DisplayClass0_0`2.<Handle>b__2(IEnumerable`1 handlerNotifications)
   at Umbraco.Cms.Core.Events.EventAggregator.PublishCore[TNotification](IEnumerable`1 allHandlers, IEnumerable`1 notifications)
   at Umbraco.Cms.Core.Events.NotificationHandlerWrapperImpl`1.Handle[TNotification,TNotificationHandler](IEnumerable`1 notifications, ServiceFactory serviceFactory, Action`2 publish)
   at Umbraco.Cms.Core.Events.EventAggregator.PublishNotifications[TNotification,TNotificationHandler](IEnumerable`1 notifications)
   at Umbraco.Cms.Core.Events.EventAggregator.Publish[TNotification,TNotificationHandler](IEnumerable`1 notifications)
   at Umbraco.Cms.Core.Events.EventAggregator.Publish[TNotification](TNotification notification)
   at Umbraco.Cms.Infrastructure.Runtime.CoreRuntime.<StartAsync>b__22_1()
   at System.Threading.CancellationTokenSource.Invoke(Delegate d, Object state, CancellationTokenSource source)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.CancellationTokenSource.ExecuteCallbackHandlers(Boolean throwOnFirstException)
   --- End of inner exception stack trace ---
   at System.Threading.CancellationTokenSource.ExecuteCallbackHandlers(Boolean throwOnFirstException)
   at Microsoft.Extensions.Hosting.Internal.ApplicationLifetime.NotifyStarted()
```

I've tried to look at the `DataEditorCollection` with my own code and it looks like (in my solution) that it's the two pickers from my Newsletter Studio-package and `Umbraco.MultiNodeTreePicker` (which is filtered out int he collector-implementation) that is duplicated:

* NewsletterStudio.MailingListPicker
* NewsletterStudio.TransactionalEmailPicker
* Umbraco.MultiNodeTreePicker

I've not seen this issue before or had any problem with these pickers in the package before. Not sure if the problem is the fact that the data collector assumes that there are no duplicates (and use it as key in the dictionary) or if it's something wrong with the registration of the editors - but this has worked just fine since v9.

### Steps to reproduce

Tried this on my own solution to get the data editors:

```csharp
public class DataTypeSplitDataCollectorComposer : IComposer
{
    public void Compose(IUmbracoBuilder builder)
    {
        builder.AddNotificationHandler<UmbracoApplicationStartedNotification, TestingStartup>();
    }
}

public class TestingStartup : INotificationHandler<UmbracoApplicationStartedNotification>
{
    private readonly DataEditorCollection _dataEditors;

    public TestingStartup(DataEditorCollection dataEditors)
    {
        _dataEditors = dataEditors;
    }

    public void Handle(UmbracoApplicationStartedNotification notification)
    {
        var dataEditors = _dataEditors.Where(x => x != null).ToList();

        var group = dataEditors.GroupBy(x => x.Alias).Where(x => x.Count() > 1).ToList();

        var res = group;

    }
}
```

### Expected result / actual result

Probably filter out duplicates before adding to a dictionary OR take the MacroParameter vs PropertyValue into account when filtering (maybe both) =D

## Update:

I looked closer at this, it is because it's two "different" types of editors with the same alias. This is present in the core with "Umbraco.MultiNodeTreePicker".

If you look at this you can see that the same alias is used for the editors of type MacroParameter and the PropertyValue:

![image](https://github.com/umbraco/Umbraco-CMS/assets/1782524/cef68f65-467c-4193-be61-63729704ce8c)

I've done the same in my package since Umbraco 9 and everything else works just fine, I'm registering the editors like this:

```csharp
[DataEditor(
    NewsletterStudioConstants.Backoffice.PropertyEditors.TransactionalEmailPicker.Alias,
    EditorType.MacroParameter,
    "Transactional Email Picker",
    "~" + NewsletterStudioConstants.Paths.AppPluginsNewsletterStudio + "/backoffice/propertyEditors/transactionalEmailPicker/transactionalEmailPicker.html",
    Group = "Email",
    Icon = "icon-hand-pointer-alt",
    ValueType = "JSON"
)]
public class TransactionalEmailPickerMacroEditor : DataEditor
{
    public TransactionalEmailPickerMacroEditor(IDataValueEditorFactory dataValueEditorFactory, EditorType type = EditorType.PropertyValue) : base(dataValueEditorFactory, type)
    {
    }
}   

[DataEditor(
    NewsletterStudioConstants.Backoffice.PropertyEditors.TransactionalEmailPicker.Alias,
    EditorType.PropertyValue,
    "Transactional Email Picker",
    "~" + NewsletterStudioConstants.Paths.AppPluginsNewsletterStudio + "/backoffice/propertyEditors/transactionalEmailPicker/transactionalEmailPicker.html",
    Group = "Email",
    Icon = "icon-hand-pointer-alt",
    ValueType = "JSON"
)]
public class TransactionalEmailPickerPropertyEditor : DataEditor
{
   

    protected override IConfigurationEditor CreateConfigurationEditor()
    {
        return new TransactionalEmailPickerConfigurationEditor();
    }

    public TransactionalEmailPickerPropertyEditor(IDataValueEditorFactory dataValueEditorFactory, EditorType type = EditorType.PropertyValue) : base(dataValueEditorFactory, type)
    {
    }
}
```

And as you can see they are registered as two different items in the `DataEditorCollection` but the `Attribute.Type` is either `MacroParameter` or `PropertyValue`:

![image](https://github.com/umbraco/Umbraco-CMS/assets/1782524/f0ed7694-f9ec-44a5-8dd8-73e72745049a)

**Comment by enkelmedia** [comment]
I think that maybe the author @Migaroez is the right person to answer here? What do you think?

**Comment by enkelmedia** [comment]
In case anyone else have this problem, while waiting for this to be solved one could disable this telemetry-feature by adding a composer that disables it:

```csharp
[Disable(typeof(DataTypeSplitDataCollectorComposer))]
public class SiteComposer : IComposer
{
    public void Compose(IUmbracoBuilder builder)
    {
    }
}
```

**Comment by Migaroez** [comment]
Hey @enkelmedia, thanks for the bug report. This was a small oversight that snuck into the code, a PR has been raised that should get into the next patch in a few days.

Small comment: this is not a telemetry feature. 
To migrate your DataTypes (stored in the DB) from v13 to v14, we need to know information about the definition of the PropertyEditor behind them both in v13 and v14. Since the v13 part will not longer be available in v14, we are storing the information in the DB instead as a premigration, this is what this class does.
Nice sneaky way of disabling the feature though 😄 Another good reason for us to use composers ourselves 😉

**Comment by enkelmedia** [comment]
Thanks @Migaroez  =D

Ouups.. Better activate it again when the fix is releases then  =D Sorry for my assumptions, I'll adjust the text above to not confuse anyone else.

Thanks for the fix and the explanation =D

// m
