### ISSUE TITLE
UmbracoApiController does not respect configured MvcNewtonsoftJsonOptions

### ISSUE THREAD

**Issue by arknu** [umbraco/Umbraco-CMS#15882]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

13.2

### Bug summary

I was trying to configure Newtonsoft.JSON to use parse dates as DateTimeOffset rather than DateTime in my controllers derived from UmbracoApiController. This should be a simple matter of having this code on startup:
```
 services.PostConfigure<MvcNewtonsoftJsonOptions>(options =>
 {
     options.SerializerSettings.DateParseHandling = Newtonsoft.Json.DateParseHandling.DateTimeOffset;
 });
```

Much to my surprise this didn't work.

After some digging, I discovered that Umbraco has an `UmbracoJsonModelBinder` that is used for anything that is an UmbracoApiController. And this class simply creates a new `MvcNewtonsoftJsonOptions` rather than using the globally configured one: 
https://github.com/umbraco/Umbraco-CMS/blob/2fbda6e64ba4b2b2cfd84df92b253d1c8ede7cd5/src/Umbraco.Web.Common/ModelBinders/UmbracoJsonModelBinder.cs#L30-L32

This issue is present in at least v12 as well, and probably v11, v10 and v9 as well.

### Steps to reproduce

Try modifying the Newtonsoft JSON Options as above. Notice that they don't apply to an UmbracoApiController.

### Expected result / actual result

The globally configured options should be respected

**Comment by arknu** [comment]
PR here: https://github.com/umbraco/Umbraco-CMS/pull/15883

**Comment by nul800sebastiaan** [comment]
Closing this with explanation in the comments here: https://github.com/umbraco/Umbraco-CMS/pull/15883
