### ISSUE TITLE
The "GetUmbracoBuildVersion" task was not given a value for the required parameter "GitCommitIdShort".

### ISSUE THREAD

**Issue by 48117650** [umbraco/Umbraco-CMS#15904]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

13.2.0

### Bug summary

![L8)KJCCF 1H63J5VVW)SPNW](https://github.com/umbraco/Umbraco-CMS/assets/57940724/b3466e77-cc9c-4f49-997c-4e1faf835a7b)

### Steps to reproduce

Download 13.2.0 source code and follow the BUILD.md file operation

### Expected result / actual result

I followed
![1710814133724](https://github.com/umbraco/Umbraco-CMS/assets/57940724/706444b3-6a2d-454c-af38-b2bcf27b1de6)
step Error reporting
The "GetUmbracoBuildVersion" task was not given a value for the required parameter "GitCommitIdShort".

**Comment by nul800sebastiaan** [comment]
Hey there @48117650 - I see you're having trouble building Umbraco from the source. 

Just so you know: you do not ever need to build the Umbraco code from source if you just want to use Umbraco. Make sure to follow the setup documentation: https://docs.umbraco.com/umbraco-cms/fundamentals/setup

If you're trying to contribute a pull request back to Umbraco CMS then you're of course welcome to build it. In that case, make sure to reach out in the `#contributing` channel on [Discord](http://discord.umbraco.com).
