### ISSUE TITLE
'Save and Preview' action still visible when removed from AllowedActions

### ISSUE THREAD

**Issue by chrden** [umbraco/Umbraco-CMS#15914]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

12.3.9

### Bug summary

'Save and Preview' button is not hidden on first load of a content node when all `AllowedActions` are removed.

The button is only hidden when the tab is changed

### Specifics

I am trying to restrict the `AllowedActions` on a content node using a `SendingContentNotification` notification handler to remove the following actions:
- ActionPublish
- ActionToPublish
- ActionUpdate

If I do this, the 'Save and Publish' button is still visible on first load until I change tab.

The same outcome happens when **all** `AllowedActions` are removed

If a doc type has 0 or 1 tabs, 'Save and Publish' will always be displayed

### Steps to reproduce

1. Create document type with 2 or more tabs
2. Create `SendingContentNotification` notification handler
3. Set `notification.Content.AllowedActions` to restrict actions (see snippets below)
4. Build and run Umbraco, load node in 'Content' section
5. 'Save and publish' button still displaying
6. Change tab, 'Save and Publish' button no longer displays

Using both of the below snippets produces the same result:
```
notification.Content.AllowedActions = Enumerable.Empty<string>();
```
OR
```
notification.Content.AllowedActions =
    notification.Content.AllowedActions?
        .Where(action => 
            !action.Equals(ActionPublish.ActionLetter.ToString())
            && !action.Equals(ActionToPublish.ActionLetter.ToString())
            && !action.Equals(ActionUpdate.ActionLetter.ToString())
        );
```

### Expected result / actual result

Expected:
All buttons ('Save and Publish', 'Save' and 'Publish' (including 'Publish' button menu options e.g. 'Unpublish') should not be visible

Actual:
'Save and Publish' is still visible until tab is changed (if doc type has tabs)

**Comment by chrden** [comment]
EDIT: The 'Save and publish' button remains visible between switching tabs when testing the above steps on a clean 12.3.9 install

**Comment by NguyenThuyLan** [comment]
Hi @chrden , thank for reporting this issue.
I reproduced this on v13 and it no longer happens on v13, so I recommend you upgrade to v13 because v12 is end-of-life support 😊

**Comment by markadrake** [comment]
I followed the steps above. 

I set `AllowedActions` to nothing in my `SendingContentNotification` handler. 

This removed quite a few buttons, but not all of them!

![image](https://github.com/user-attachments/assets/f5261d88-a485-48af-9d53-0d98d38268c2)

![image](https://github.com/user-attachments/assets/c9c1ea7f-1a5a-4d92-a55d-fbbe4704887b)

**Comment by NguyenThuyLan** [comment]
Sure @markadrake

**Comment by markadrake** [comment]
@NguyenThuyLan, thanks so much for looking into this. 
Could you do one last step and open the content in the infinite editing experience? The infinite editing window may not respect these values (AllowPreview, AllowedActions). See the previous screenshot. 
All the best!

**Comment by NguyenThuyLan** [comment]
Hi @markadrake , could you provide clear steps to reproduce? A video could be awesome
