### ISSUE TITLE
Custom TwoFactorView IBackOfficeTwoFactorOptions not passed down correctly

### ISSUE THREAD

**Issue by pimpaard** [umbraco/Umbraco-CMS#15935]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

13.0.0

### Bug summary

In the docs it state you can create a different twoFacotrView which can be set with IBackOfficeTwoFactorOptions.
https://docs.umbraco.com/umbraco-cms/reference/security/two-factor-authentication

The problem is that when you login the handleSubmit is called:
![image](https://github.com/umbraco/Umbraco-CMS/assets/83830995/aee56585-1c31-4fbe-bda9-9ea11e2aeb58)

This calls umbAuthContext.login which calls a function in auth.repository.ts:
![image](https://github.com/umbraco/Umbraco-CMS/assets/83830995/697e7ebd-e577-4ef1-a880-cd5b00fe2d09)

In this only the twoFactorView gets passed down if the response is ok, but the response will be 402 which is not okay.
Then in the original login you check if status code is 402 which it is but now it does not contain the custom twoFactorView.

### Steps to reproduce

You can implement the twoFactorAuthentication with a custom view like explained in the documentation: https://docs.umbraco.com/umbraco-cms/reference/security/two-factor-authentication. 
And then see if the new view is returned.

### Expected result / actual result

Expect the custom twoFactorView to be used.

**Comment by NguyenThuyLan** [comment]
There is a bit of confusion here, are you using v14 docs for your project on v13? 🤔

**Comment by pimpaard** [comment]
I am using umbraco 13 and was also using umbraco 13 documentation. When I made this ticket umbraco 13 was the latest version, documentation of 14 did not exist. So the link just redirect to the latest.

**Comment by NguyenThuyLan** [comment]
Yes @pimpaard , I just wonder that I couldn't see any info about IBackOfficeTwoFactorOptions in v13 docs, it only has in v14 docs 🤔
