### ISSUE TITLE
v14 beta 002 does not work in Safari or Firefox on macOS

### ISSUE THREAD

**Issue by greystate** [umbraco/Umbraco-CMS#15937]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

14.0.0-beta002

### Bug summary

When hitting the /umbraco/ route I only see a blank screen.

There's an error in the Console:

> SyntaxError: Unexpected identifier 'assert'. Expected a ';' following a targeted import declaration.

— in the file `icon.registry.js`

### Specifics

I'm seeing this in Safari (17.2.1) on macOS Sonoma (14.2.1) and in Firefox (124.0.1) as well.

In Chrome (123.0.6312.59) I see the login screen and am able to log in. The Console does not output an error.

### Steps to reproduce

I followed the steps here: https://docs.umbraco.com/umbraco-cms/v/14.latest-beta/fundamentals/setup/install/preview-builds#installing-the-preview-build-template

- Install the latest preview build template
- Create a new website
- Run the website
- Open the /umbraco/ route

### Expected result / actual result

I expect to see the login screen and to be able to log in

**Comment by Zeegaan** [comment]
Hello there 👋 We are aware, and it is currently being tracked on the Backoffice repository here https://github.com/umbraco/Umbraco.CMS.Backoffice/issues/1400 😁 

Thanks for reporting! 🐛

**Comment by greystate** [comment]
Ah - thanks @Zeegaan (was not aware of the separate repo) 🙌
