### ISSUE TITLE
[BUG] Content Item duplicates when saving twice after create - Happens when `Enable list view` = `true`

### ISSUE THREAD

**Issue by r-Larch** [umbraco/Umbraco-CMS#15945]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

13.2.2 - *also happens in 13.1.1*

### Bug summary

When creating a child content item in a parent where `Enable list view = true` the item will be duplicated on second `Save` (not save and publish)

### Specifics

Happens in infinite editor.

### Steps to reproduce

- Have a content Item with `Vary by culture` and  `Enable list view = true`.
- Add a child content item using `Create {Child Page}` button. The child is also `Vary by culture`.
- Enter a name for the new item
- Hit Save - not save and publish
- Make another change to the item.
- Hit Save again.
-> You will see name has changed to `Name (1)` and the item exists twice in the list.

### Expected result / actual result

The item will not be duplicated.

### Details

It looks like a BUG in the backend.

First save: (node gets an id)
<img width="1336" alt="image" src="https://github.com/umbraco/Umbraco-CMS/assets/26417776/c421bb2f-d7e3-481a-8e8e-18068a94971c">

Second Save: (the node id gets sent to the backend)
<img width="1349" alt="image" src="https://github.com/umbraco/Umbraco-CMS/assets/26417776/1284daab-d9c2-4039-a123-d77411fcf55e">

Second Save Server response: (the backend responds with a **new id!**)
<img width="1323" alt="image" src="https://github.com/umbraco/Umbraco-CMS/assets/26417776/1f8b0ec4-b74b-47ec-ad90-23289bd2699e">

**Comment by Zeegaan** [comment]
I sadly cannot reproduce this, below is a GIF of me trying to reproduce, am I doing anything wrong here ? 🤔
