### ISSUE TITLE
Content with the same name (but special characters inside) causes URL collision

### ISSUE THREAD

**Issue by SigmundurMorkore** [umbraco/Umbraco-CMS#15943]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

13.2.2

### Bug summary

The issue in https://github.com/umbraco/Umbraco-CMS/issues/10909 is still relevant.

Tried reopening it with @umbracobot but didn't seem to work, so am opening a new issue, hopefully that is fine :)

### Steps to reproduce

1.     Create a new page named "Test page with URL"
2.     Create a new page named "Test page (with URL)"
3.     Check URL of these pages

### Expected result / actual result

Page should get unique name (the correct number behind it's name), so the URL is unique.

---
_This item has been added to our backlog AB#46571_

**Comment by NguyenThuyLan** [comment]
This bug is relevant to #15850.

**Comment by Zeegaan** [comment]
Fixed in https://github.com/umbraco/Umbraco-CMS/pull/17705 🚀
