### ISSUE TITLE
Editors returned to login screen aftering altering block in the Umbraco.Grid in v8

### ISSUE THREAD

**Issue by jawood1** [umbraco/Umbraco-CMS#15952]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

8.18.3

### Bug summary

When logged in as an editor role making an alteration to a grid item returns the editor to the login screen on save of the grid item.

We've also had reports that editors are also experiencing issues when accessing the preview menu, but I've not been able to re-create this issue.

https://github.com/umbraco/Umbraco-CMS/assets/47325234/9e38d6c2-e173-4684-8dd3-79971f08d1c7

### Specifics

I've checked this across the major browsers and have been able to re-create the issue.

This also seems to be occuring on 8.18.12.

### Steps to reproduce

1. Login as an editor
2. Go to a grid item and make a change
3. You'll be redirected to the login screen

### Expected result / actual result

Editor can make changes to a grid item without them being returned to the login screen.

**Comment by kasparboelkjeldsen** [comment]
@jawood1 I'm guessing you are using doctype grid editor plugin?
We are many who have had similar issues and ended up with an special final version of DTGE you can upgrade to to solve the issue. Pre-release available here https://www.nuget.org/packages/Our.Umbraco.DocTypeGridEditor/1.3.0-blackknight

Read more here https://github.com/umbraco/Umbraco-CMS/issues/15572

**Comment by jawood1** [comment]
Hi @kasparboelkjeldsen 

Thanks for commenting, yes we are using that package I'll take a look and update if this resolves our issue.

**Comment by jawood1** [comment]
Looks like upgrading DTGE has resolved the issue I'll close this now.

Thanks for your help @kasparboelkjeldsen !
