### ISSUE TITLE
Delivery routing locale issue

### ISSUE THREAD

**Issue by ava3a13** [umbraco/Umbraco-CMS#15962]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

12.3.3

### Bug summary

The current implementation of the URL handling logic does not correctly handle non-ASCII characters in the URL paths. When a URL contains non-ASCII characters, such as Georgian characters in this case, the system fails to properly process and route the request to the intended destination.

### Specifics

Possible solution is to  change handling of absolutePath and unescape it via `Uri.UnescapeDataString()` in the RoutingServiceBase class:

`    
                 protected static string GetContentRoute(DomainAndUri domainAndUri, Uri contentRoute)
        => $"{domainAndUri.ContentId}{DomainUtilities.PathRelativeToDomain(domainAndUri.Uri, Uri.UnescapeDataString(contentRoute.AbsolutePath))}";
`

### Steps to reproduce

Create any mixed language url and send request to content path retrieval in delivery api 

Expected Result:
The system should be able to handle URLs with non-ASCII characters in the path correctly. It should decode the URL-encoded characters, process the request, and route it to the appropriate destination based on the decoded path.

### Expected result / actual result

When a request is made to the following URL:

/en/team/%E1%83%A1%E1%83%A2%E1%83%98%E1%83%95-%E1%83%99%E1%83%98%E1%83%9C%E1%83%98-%E1%83%9B%E1%83%97%E1%83%90%E1%83%95%E1%83%90%E1%83%A0%E1%83%98-%E1%83%9B%E1%83%AC%E1%83%95%E1%83%A0%E1%83%97%E1%83%9C%E1%83%94%E1%83%9A%E1%83%98%E1%83%A1%E1%83%90-%E1%83%93%E1%83%90-%E1%83%A1%E1%83%9E%E1%83%9D%E1%83%A0%E1%83%A2%E1%83%A3%E1%83%9A%E1%83%98-%E1%83%93%E1%83%98%E1%83%A0%E1%83%94%E1%83%A5%E1%83%A2%E1%83%9D%E1%83%A0%E1%83%98%E1%83%A1-%E1%83%9E%E1%83%9D%E1%83%96%E1%83%98%E1%83%AA%E1%83%98%E1%83%90%E1%83%96%E1%83%94/

The system fails to handle the request correctly and does not route it to the intended page or resource.

Actual Result:
The system fails to handle URLs with non-ASCII characters in the path correctly. It returns 404

**Comment by NguyenThuyLan** [comment]
Hi @ava3a13 , thank you for reporting this issue. 😊
As I can see this issue is fixed in the newest version of v12 and above. You should upgrade your project to a newer version.

https://github.com/user-attachments/assets/1e7c89fe-1f7c-418c-885c-05b80c7e1bf2

I will close this issue because it is fixed.
