### ISSUE TITLE
uskinned builder breaks Umbraco 13 LTS

### ISSUE THREAD

**Issue by papyr** [umbraco/Umbraco-CMS#16001]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

13.2

### Bug summary

Both on local and IIS, and iis server with docker, uskinned builder broke a fresh clean site. 

To being, adding Uskinned builder prevented umbraco on local dev from coming up after a new install, it complained about license.
So after immediately uninstalling, it broke the site, since the nuget uninstall process seemed to be broken left remnants of uskinbuilder based classes and views in the installation.

Wasted a lot of time, I had to completely tear down the site and start from scratch

### Specifics

please have the package providers do a clean easy uninstall.

### Steps to reproduce

![image](https://github.com/umbraco/Umbraco-CMS/assets/12733414/a6b0925d-5086-4e56-adb0-a72f291888e5)

**Comment by Migaroez** [comment]
Hey @papyr, this seems like an issue with Uskinned. Because of the opensource and extendable nature of Umbraco, anyone can make a package. Umbraco can not guarantee the quality or compatibility of a package, please contact the supplier of the package to resolve your issue.
