### ISSUE TITLE
Saving a media-type with a rich-text property breaks the save media button

### ISSUE THREAD

**Issue by mdeslauriers-sigmund** [umbraco/Umbraco-CMS#16011]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

13.2.2

### Bug summary

Adding a property with the "Rich text" data-type to the "Image" media-type, cause a javascript error when the user create a new image in the media library. The save operation on the back-end seems successful, but the save button on the front-end keeps spinning and never return to its original state.

### Specifics

Reproduced in Chrome and Firefox

The error occurs in the Media library, in the "Create Image Form"
`/umbraco#/media/media/edit/-1?doctype=Image&create=true`

The spinner never resets: 

![image](https://github.com/umbraco/Umbraco-CMS/assets/43347638/dcdb9c33-9f2d-43f0-9d09-eb4c760a72e0)

The javascript console error is : `modelObject is undefined`:

![image](https://github.com/umbraco/Umbraco-CMS/assets/43347638/d848f64e-acf7-45b2-bb77-60d07ab91558)

**Note :** It also can be reproduced in the "Edit Image Form" **if the richtext property is empty on the initial load**.

### Steps to reproduce

**Modify de Media type**
- Go to the "Settings" section
- Expand "Media Types" and select "Image"
- Add a new property using the "Ricktext editor"
- Click the save button

**Create a new image**
- Go to the "Media" section
- Right click on the Media tree an select "Create" -> "Image"
  - ![image](https://github.com/umbraco/Umbraco-CMS/assets/43347638/5e7d3811-8e6b-4d06-a0d7-e66a004e2757)
- Enter a node name
- Select an image
- Click the save button

The error occurs here:
- The spinner on the save button is stuck
- A javascript error is visible in the console
- A full page refresh will show that the image was created

### Expected result / actual result

Actual result :
- The spinner on the button is stuck
- A javascript error is visible in the console

Expected result : 
- The save button should return to its initial state
- No javascript error shloud be visible in the console

**Comment by nhudinh0309** [comment]
Hi @mdeslauriers-sigmund,
Thanks for reporting this issue! I was able to reproduce it on version 13.2.2, 13.2.1 and 13.3.0. But for me, the JS console shown as below: 
![Screenshot 2024-05-03 182546](https://github.com/umbraco/Umbraco-CMS/assets/150406148/256ad96d-32f1-49d0-9be9-9b8da4365511)

I also tested on version 12.3.9 and the save function works without any problem. So this is a regression issue. I will go ahead and mark it as a sprint-candidate 😄

**Comment by kjac** [comment]
Fix in #17582 👍

**Comment by iOvergaard** [comment]
The fix has been merged and we expect to ship this with 13.6.

**Comment by devlopaag** [comment]
Here is the error in text form that it gets indexed by google, for other people having this issue:
angular.js:15697 TypeError: Cannot read properties of undefined (reading 'getLayout')
    at onLoaded (umbraco.directives.min.js?d=638981087300000000:1:615262)
    at Object.onServerValueChanged [as onValueChanged] (umbraco.directives.min.js?d=638981087300000000:1:614849)
    at Object.reBindChangedProperties (umbraco.services.min.js?d=638981087300000000:1:20710)
    at umbraco.controllers.min.js?d=638981087300000000:1:73481
    at angular.js:18075:37
    at m.$digest (angular.js:19242:15)
    at m.$apply (angular.js:19630:13)
    at k (angular.js:13473:36)
    at v (angular.js:13730:7)
    at y.onload (angular.js:13635:9) 'Possibly unhandled rejection: {}'
