### ISSUE TITLE
umbracoContextReference.UmbracoContext.Content.GetByContentType does not work with nodes that have VariByCulture set

### ISSUE THREAD

**Issue by gardarthorsteins** [umbraco/Umbraco-CMS#16014]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

12.3.9

### Bug summary

UmbracoContextReference.UmbracoContext.Content.GetByContentType does not work with nodes that have VariByCulture set, it will always return zero items back

### Steps to reproduce

Use this code to try to fetch any nodes with VariByCulture set on them.

```
using (var umbracoContextReference = _umbracoContextFactory.EnsureUmbracoContext())
{
    var contentType = umbracoContextReference.UmbracoContext.Content.GetContentType(alias);

    ArgumentNullException.ThrowIfNull(contentType);

    return umbracoContextReference.UmbracoContext.Content.GetByContentType(contentType);
}
```

### Expected result / actual result

Expected to get returned those nodes but instead we are getting zero nodes back.

**Comment by gardarthorsteins** [comment]
HI @NguyenThuyLan 

Thank you for taking your time to look into this.

My problem was that I'm trying to fetch nodes that are VariByCulture but they have a parent node that is not set as VariByCulture.

So in my set up it can be something like this:

-> Repository (VariByCulture: False) ->Article (VariByCulture: True)

Trying to fetch all articles by contentType will not return 0 results but I would except to be able to find them.

**Comment by gardarthorsteins** [comment]
@NguyenThuyLan Have you had any time to look into this again ?

**Comment by NguyenThuyLan** [comment]
Hi @gardarthorsteins , could you reproduce it on support versions as v13 - v15? 🤔
