### ISSUE TITLE
PostSave 403 Error on Save

### ISSUE THREAD

**Issue by rogermal** [umbraco/Umbraco-CMS#16036]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

13.1

### Bug summary

No errors logged in logs

### Steps to reproduce

Add firewall rules that stop an image being posted or similar

### Expected result / actual result

403 error with details added to the log viewer. Nothing found in logs.

**Comment by Zeegaan** [comment]
I am not entirely sure what the issue is here 🤔 

What are we saving? How are we saving it? Which configuration do we have ? 😁 
Why are we expecting the error to be logged 🤔 

It might just be my misunderstanding, but I need clarification here 😅
