### ISSUE TITLE
Save buttondisabled

### ISSUE THREAD

**Issue by itsliamprowse** [umbraco/Umbraco-CMS#16048]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

14 Beta 3

### Bug summary

When editing any existing items under the settings section (document type, data type, template), the save button is disabled on load, clearing cache and doing a hard reload allows the item to them be saved.

### Specifics

This only affects existing items, creating anything new the save button works as expected.
There are no errors logged to the console when this happens.
Inspecting the buttons I can see that they are loading in with the disabled attribute on them.
This does not happen if you have "Disable Cache (While DevTools is open)" enabled and navigate directly to the item (not navigating via the tree)
I have reproduced this on separate installs, using both Chrome and Edge.
Using Dev Tools to remove the "disabled" attribute from the save button allows the item to be saved.

### Steps to reproduce

Fresh install of Umbraco 14 beta 3, create a Document Type/Data Type/Template and save it, navigate away from the settings section. Navigate back to the settings section, open the item created and the save button will be disabled.

### Expected result / actual result

For the save button to be enabled on load of any items in the settings section.

**Comment by NguyenThuyLan** [comment]
Hi @itsliamprowse 👋, thanks for reporting this issue.
I tried to replicate your issue but the save button still works properly as below video:

https://github.com/umbraco/Umbraco-CMS/assets/116753400/22597b39-bd5f-40ce-807f-b8e3be82a535

I will close this issue as I wasn't able to reproduce but feel free to reopen it if you have any more specifics.
