### ISSUE TITLE
Block Editor Label Properties

### ISSUE THREAD

**Issue by marioamaraldecskill** [umbraco/Umbraco-CMS#16071]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

10.6.1

### Bug summary

In version 10.2.0 i have a this code in the label field: {{$settings.sectionLabel ? $settings.sectionLabel : $alias}} but the "alias" is never displayed.
If i just have $alias it does display the alias value.

### Specifics

The code {{$settings.sectionLabel ? $settings.sectionLabel : alias}} was working perfectly with version 10.2.0. After updating to version 10.6.1 it stopped working and always shows the label field

### Steps to reproduce

**In 10.6.2 when just using $alias**
![image](https://github.com/umbraco/Umbraco-CMS/assets/158591325/01177b0b-bb71-48eb-8d77-f92b844db1dc)

**Does show the alias independently of what is in the label field**
![image](https://github.com/umbraco/Umbraco-CMS/assets/158591325/0cf1a763-cad7-4dec-91f7-067f69570cf4)

**The label field**
![image](https://github.com/umbraco/Umbraco-CMS/assets/158591325/211840ef-0ef6-405d-be8d-648009f347d5)

**In 10.6.2 with {{$settings.sectionLabel ? $settings.sectionLabel  : $alias}} (that was working in 10.2.0)**
![image](https://github.com/umbraco/Umbraco-CMS/assets/158591325/76d77ef0-66df-4308-82ea-c364a083bfb1)

**It stopped showing the alias**
![image](https://github.com/umbraco/Umbraco-CMS/assets/158591325/f4c3858d-2384-4440-9014-6f20e0586999)

### Expected result / actual result

It should display the alias if the label field is empty

**Comment by glombek** [comment]
Came across your issue while looking for something else!

`$alias` isn't a documented variable.

https://docs.umbraco.com/umbraco-cms/fundamentals/backoffice/property-editors/built-in-umbraco-property-editors/block-editor/label-property-configuration#special-variables

Did you mean `$contentTypeName` or, to reference a property on the element type called `alias`, `alias`?

If `$alias` is meant to work, the docs need updating.

**Comment by marioamaraldecskill** [comment]
Changed to {{$settings.sectionLabel ? $settings.sectionLabel  : $contentTypeName}} it worked!

Thanks.



Obrigado e cumprimentos / Best regards

Mário Amaral
CTO
+351 968 120 589



[A blue and purple letters on a black background  Description automatically generated]



      Avenida José Malhoa 27 6º Piso - 1070-157 Lisboa

      www.decskill.com<http://www.decskill.com/>



[A blue background with white letters  Description automatically generated]



Uma empresa do Grupo New Anderthal<https://newanderthal.pt/>

[signature_1033006342]<https://www.facebook.com/Decskill/> [signature_1374556423] <https://www.instagram.com/decskill_/>  [signature_385770551] <https://www.linkedin.com/company/5102796/admin/>  [/Users/joanagoncalves/Library/Containers/com.microsoft.Outlook/Data/Library/Caches/Signatures/signature_247437601] <https://www.youtube.com/channel/UCbafHaCzLABxm2BpHsJA4tA>





________________________________
