### ISSUE TITLE
v14-rc1 - The Document Type tree does not refresh when creating a folder.

### ISSUE THREAD

**Issue by OwainJ** [umbraco/Umbraco-CMS#16088]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

v14-rc1

### Bug summary

The Document Type tree does not refresh when creating a folder.
- Only seems to happen when there is nothing else in the DocType tree.
- If there is another item (folder or a doctype) in the tree, it refreshes as expected.

![DocType folder creation](https://github.com/umbraco/Umbraco-CMS/assets/17008780/4ff8d078-9cdb-4c4a-aab6-6aa3a7eacabd)

### Steps to reproduce

1. Create a fresh v14-rc1 project and run it
2. Navigate to the Settings section
3. Create a Folder in the Document Type tree

### Expected result / actual result

The Document Type tree should refresh to show the newly created folder

**Comment by elit0451** [comment]
Hi there @OwainJ  👋

Thanks for reaching out! I can indeed reproduce this, we will have a look 🙂

**Comment by iOvergaard** [comment]
Thanks for testing. This has been fixed in RC4!
