### ISSUE TITLE
Block displays only the first repository when multiple repositories exist

### ISSUE THREAD

**Issue by mateuszQA** [umbraco/Umbraco-CMS#16095]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

13.1.1

### Bug summary

If I have a block that downloads a particular type of repository, only the first repository can be downloaded, even if there are multiple repositories.

(You can of course do this to display all available repositories, but this solution is quite unintuitive for the user)

### Specifics

![Screenshot 2024-04-18 at 13 32 43](https://github.com/umbraco/Umbraco-CMS/assets/119952850/acc256fd-de64-4011-acbb-02429a51140d)
![Screenshot 2024-04-18 at 13 34 28](https://github.com/umbraco/Umbraco-CMS/assets/119952850/a6ffb5dc-ff85-4604-a4ba-8ceadbbba9fd)

### Steps to reproduce

1. Log in to the Umbraco backoffice
2. Navigate to the section where repositories are managed.
3. Create multiple repositories of the same type
4. Open the block that downloads only a specific type of repository
5. Observe that only the first repository is displayed and available

### Expected result / actual result

With proper Umbraco configuration, all repositories of a given type should be available

**Note for devs**: Dynamic Root Query nor valid XPath doesn't work

**Comment by elit0451** [comment]
Hi there @mateuszQA  👋

Thanks for reaching out! Can you clarify a bit more your "Steps to reproduce" for me, please?
It would be great to show the document types set up and the property editor you use to select the **Disclaimer** item.

Perhaps you can set it up on a fresh v13.3.0 and screen record 🙂 It will really help to understand and reproduce the issue

**Comment by mateuszQA** [comment]
Hello @elit0451 Maybe it will be easier if I show you the video, generally my "disclaimer" block only downloads data from the first repository where I have created the 3 disclaimer repositories. I talked to the developer about this and he said that when he tried to do it using different methods and when debugging it returned 3 repositories, but Umbraco limits it to returning the first item.

https://github.com/umbraco/Umbraco-CMS/assets/119952850/751cb2e3-e21b-40f0-8563-05e690788b4d

**Comment by mateuszQA** [comment]
"query": "$root/repositories/disclaimerRepository",

![Screenshot 2024-04-19 at 14 26 48](https://github.com/umbraco/Umbraco-CMS/assets/119952850/e46e4651-5fd6-4a15-8058-60cf4298ddfc)

**Comment by elit0451** [comment]
Hi again @mateuszQA

Unfortunately, the Multinode Treepicker only renders a single tree:
> ref [our Docs](https://docs.umbraco.com/umbraco-cms/fundamentals/backoffice/property-editors/built-in-umbraco-property-editors/multinode-treepicker#settings): The Multinode Treepicker allows you to configure the type of tree to render and what part of the tree that should be rendered.

As a workaround, you can of course configure your Disclaimer picker to use a Dynamic Root Query of "Current" and then you will be able to see all disclaimer repositories. You can specify further the "Allow items of type" to make sure that you can only select the applicable type.
![MultinodeTreepicker](https://github.com/umbraco/Umbraco-CMS/assets/21998037/88187aa1-0f8c-4190-93e3-409c0aebaf2a)


</br>

It is not an ideal solution but if you'd like the Multinode Treepicker to support multiple trees, I would suggest you to create a feature request 🙂
