### ISSUE TITLE
v14-rc1 - Composition menu throws an error when creating a DocType

### ISSUE THREAD

**Issue by OwainJ** [umbraco/Umbraco-CMS#16091]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

v14-rc1

### Bug summary

When creating a new DocType, an error is thrown when you open the "Compositions" menu.

E.g:
![DocType creation composition menu](https://github.com/umbraco/Umbraco-CMS/assets/17008780/13bf814c-f9cc-4310-8b42-2da88fb7a74f)

Here is the request that fails:
![image](https://github.com/umbraco/Umbraco-CMS/assets/17008780/7fd2d9e9-5115-4acc-8a28-8c5f1947b658)
![image](https://github.com/umbraco/Umbraco-CMS/assets/17008780/545a80c2-6603-4937-947f-fe66c9344cd7)

I can see that it called the endpoint `https://localhost:44377/umbraco/management/api/v1/document-type/d94fa3e7-4ab1-4282-83ea-b01c6c156ce2/composition-references` when I open the Composition menu.

The key `d94fa3e7-4ab1-4282-83ea-b01c6c156ce2` matched the key of the DocType after I created it, therefore I'm guessing it's attempting to find any composition references that the DocType might already have, but because the DocType hasn't actually been saved yet, so it just fails. It probably shouldn't bother checking for references on the initial DocType creation.

No errors are thrown if we open the menu after we save the DocType.

### Steps to reproduce

1. Create a fresh v14-rc1 project and run it
2. Navigate to the Settings section
3. Select Create a Document Type
4. Open the Composition menu

### Expected result / actual result

I don't expect an error when opening the composition menu.

**Comment by elit0451** [comment]
Hi again @OwainJ 👋 

Great investigation skills 🕵️ 🙌  I can indeed reproduce this, we will have a look 🙂

**Comment by nielslyngsoe** [comment]
Thanks for the reporting, its begin fixed here:
Fixed here: https://github.com/umbraco/Umbraco.CMS.Backoffice/pull/1681
