### ISSUE TITLE
v14-rc1 - Duplicate content item - no errors if destination not picked

### ISSUE THREAD

**Issue by mjpraxis** [umbraco/Umbraco-CMS#16098]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

v14-rc2

### Bug summary

No errormessage or help when destination not picked when making duplicate of content item.

### Steps to reproduce

Create document type and content node.

Pick "Duplicate to" on content node

Click "Duplicate" in modal - DO NOT pick any items in content tree

![image](https://github.com/umbraco/Umbraco-CMS/assets/47383499/6edb043d-cdcd-4dfb-a166-bfdbf8e47389)

Nothing happens

### Expected result / actual result

There a kind of indication of error in the console
![image](https://github.com/umbraco/Umbraco-CMS/assets/47383499/80025560-c672-4044-b8de-bdc820e9894b)

Expected some kind of toastmessage or errormessage.

Or maybe even better - the "Duplicate" button is inactive until content tree item is picked in the modal.

Side note: If you in the modal pick an item and the un-select item. There is an error in the console that says that "Selection is required".
![image](https://github.com/umbraco/Umbraco-CMS/assets/47383499/0f3c8e4a-266a-4062-8d3f-81cd4db6d4c3)

**Comment by Migaroez** [comment]
Still an issue in RC5

https://github.com/umbraco/Umbraco-CMS/assets/6025797/976c74e4-7690-4c0e-bc86-c1e280b3c73c
