### ISSUE TITLE
v14-rc1: Language ISO code shows guid until culture is selected

### ISSUE THREAD

**Issue by bjarnef** [umbraco/Umbraco-CMS#16090]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

14.0.0-rc2

### Bug summary

When creating a new language I noticed it shows a guid in ISO code until a culture has been selected.
It used to be blank here until culture/language from dropdown was selected.

![image](https://github.com/umbraco/Umbraco-CMS/assets/2919859/44d71ba2-4520-4945-bac8-4382423da975)

### Steps to reproduce

Create a new language and noticed guid is shown in ISO code property.

**Comment by elit0451** [comment]
Hi there @bjarnef 👋

Thanks for reaching out! I can indeed reproduce this, we will have a look 🙂

**Comment by iOvergaard** [comment]
Thanks for testing. This has been fixed in RC4!
