### ISSUE TITLE
v14-rc1 MediaPicker - not able to add media item only pick existing items

### ISSUE THREAD

**Issue by mjpraxis** [umbraco/Umbraco-CMS#16097]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

v14-rc2

### Bug summary

When clicking on the media picker it is only possible to pick existing media items.
If it should look and behave like previous version - it should be a "bit" more advanced. 

### Specifics

Media Picker sidebar window

### Steps to reproduce

Add media picker to documenttype
Create node of docuementtype
Click media picker

### Expected result / actual result

Get this content in the picker
![image](https://github.com/umbraco/Umbraco-CMS/assets/47383499/ddbdd790-f420-4c84-ae87-684a6302acbd)

Side-note: The "Choose" button should be disabled if no items is "marked"

Previous versions 
![image](https://github.com/umbraco/Umbraco-CMS/assets/47383499/f4d40672-cc26-4e5f-9e59-6198df900737)

**Comment by elit0451** [comment]
Hi there @mjpraxis 👋

Thanks for reaching out! I can indeed reproduce this and it is a good point, so we will have a look 🙂
