### ISSUE TITLE
v14-rc1 - Unable to select a sibling root node with Dynamic Root

### ISSUE THREAD

**Issue by OwainJ** [umbraco/Umbraco-CMS#16093]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

v14-rc1

### Bug summary

I am trying to setup an "Author" Tree Picker, which will be limited to picking nodes from an "authorList" root node.
![image](https://github.com/umbraco/Umbraco-CMS/assets/17008780/f9df4199-5107-47d0-9010-49cd7d1cb800)

Previously, I would achieve this with XPath like so:
`$root/authorList`

But now, with Dynamic Root, I seem to be unable to select a root node, other than the current root: 
(in this case, that would be `Home`)
![image](https://github.com/umbraco/Umbraco-CMS/assets/17008780/362a2320-5647-4123-8e50-276f07c08e39)

And then I can only choose it's ancestors or descendants:
![image](https://github.com/umbraco/Umbraco-CMS/assets/17008780/4c0a4138-fb3d-4d40-b21c-a03ca5e2a971)

There doesn't seem to be any way to get a different root node, either via the Dynamic Root origin, or as a sibling query step.

### Steps to reproduce

1. Create a fresh v14-rc1 project and run it
2. Setup some nodes, make sure you have a Home root node with a blog or something similar and another root node to act as a list.
3. Create a Tree Picker, and try to setup Dynamic Root to reference the other root node.

### Expected result / actual result

Ideally, we should be able to reference any root node in a Dynamic Root query, like we could with XPath.

Also, it would be nice to have these options, or similar, available in Dynamic Root:
- Nearest Sibling or Self
- Furthest Sibling or Self

**Comment by elit0451** [comment]
Hi @OwainJ 👋 

Thanks for reaching out! I can indeed reproduce this, we will have a look 🙂

**Comment by leekelleher** [comment]
Hey @OwainJ, with 14.0.0-rc4 (out today) the Dynamic Root feature is wired up correctly, (we had a bug with MNTP start nodes in the previous RCs).

In regards to the issue you outline, about having a sibling step, the "Root" origin option would give you the top-most ancestor/root (e.g. one above "Home"), which isn't a content node as such, but it will enable you to navigate back downwards to the descendant of your choice.  Hopefully this would remove the need for a specific sibling selector step.

I'll close off this ticket, but feel free to re-open if there's an alternative use-case for a sibling selector.

**Comment by wiedikerli** [comment]
Hi everyone. i have the same issue in umbraco 13.10.1. Was this only fixed for 14+?

**Comment by bythewiseman** [comment]
Just adding that I have an issue with this too in 13.11.0.

Using Dynamic Root Query, I select "Current". What I then expect to see when I open up the Content Picker data type is the current node and that I am able to traverse the **child nodes only**.

However I see everything and all pages and nodes and settings. The current page is the one that is currently selected but this is incorrect from what I believe the logic reads.

To accomplish the task I required, I am having to use an xpath query "$current/" to make it work as I need it to.

This should be fixed please 👍
