### ISSUE TITLE
14-RC1 Restrict Public Access button does nothing in Content Tree

### ISSUE THREAD

**Issue by kasparboelkjeldsen** [umbraco/Umbraco-CMS#16105]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

14.0.0-rc2

### Bug summary

When opening the options for a content node in the content tree, and click "Restrict Public Access" nothing happens.
If you do I by using the "Actions" button to the right in the content editing area, it works as expected.

Also, both "Set Permissions" and "Notifications" spawn a JS alert with "Not implemented" in a release candidate.

### Specifics

[Video_2024_04_19-3.webm](https://github.com/umbraco/Umbraco-CMS/assets/137318845/b573fb02-8f64-4bca-a1f5-02120d326161)

Watch video for example

### Steps to reproduce

1. Create any content in the content tree
2. Right click or click the "..."
3. Click "Restrict Public Access"
4.Nothing happens - no errors in Console

### Expected result / actual result

I would expect the same "Restrict Public Access" window to slide out, that I get when using the Actions button to the right.

**Comment by elit0451** [comment]
Hi there @kasparboelkjeldsen 👋

Thanks for reaching out! I can indeed reproduce this, we will have a look 🙂

**Comment by leekelleher** [comment]
Fixed in https://github.com/umbraco/Umbraco.CMS.Backoffice/pull/1886.
