### ISSUE TITLE
v14-rc1 - Add tab on document type - input field disappear

### ISSUE THREAD

**Issue by mjpraxis** [umbraco/Umbraco-CMS#16102]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

v14-rc2

### Bug summary

The tab name input field disappear when removing text

### Specifics

Chrome 124.0.6367.61

### Steps to reproduce

In the documen type editor add a new tab (click "+ Add tab")

Enter some text in the tab name input field

Delete the text

### Expected result / actual result

The input field disappear

![image](https://github.com/umbraco/Umbraco-CMS/assets/47383499/56096439-add6-4922-a9ca-102bbcf2886f)

Excpected that the "unamed" placeholder text was visible.

If you click in the area again, the placeholder text becomes visible. But you have to click one more time to enter the input field.

![image](https://github.com/umbraco/Umbraco-CMS/assets/47383499/fb136423-0e97-4ea1-93f6-ac2eee28b7e7)

**Comment by elit0451** [comment]
Hi there @mjpraxis 👋

Thanks for reaching out! I can indeed reproduce this, we will have a look 🙂

**Comment by iOvergaard** [comment]
Thanks for testing. This has been fixed in RC4!
