### ISSUE TITLE
14.0.0-rc1: getAncestorsOf console error in member type tree

### ISSUE THREAD

**Issue by bjarnef** [umbraco/Umbraco-CMS#16118]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

14.0.0-rc2

### Bug summary

When accessing the member type tree it throws an error "Not supported for the member type tree" at `getAncestorsOf`.

![image](https://github.com/umbraco/Umbraco-CMS/assets/2919859/1c2485ec-2b10-4504-99e4-ad8ae63738c7)

perhaps because of this changing color on icon doesn't seem to show the icon like it does for document and media type.

![image](https://github.com/umbraco/Umbraco-CMS/assets/2919859/3bc4b8be-96eb-4525-af4a-ad5054d76b86)

### Steps to reproduce

Access member type tree and notice console error.
Try to change icon color of member type.

**Comment by elit0451** [comment]
Hi there @bjarnef 👋

Thanks for reaching out! I can indeed reproduce this, we will have a look 🙂

**Comment by iOvergaard** [comment]
This should be fixed in RC3. Thanks for reporting :)
