### ISSUE TITLE
v14-rc1 Block Grid elements is not editable - values do not get saved

### ISSUE THREAD

**Issue by mjpraxis** [umbraco/Umbraco-CMS#16112]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

v14-rc2

### Bug summary

Not able to add/edit values to properties on a element type in a Block Grid

You can enter values, but the changes is not saved on the document.

### Specifics

Have testet in several browsers

### Steps to reproduce

Create some very simple document-/element types and datatype

ElementType: with one property eg. "bodytext" (Textarea)
DataType: "Block Grid Property Editor UI" with the above Element Type added to the list of Blocks
DocumentType: With one property of the above DataType and allow in root

Create a document of the above DocumentType

"Add content" to the block grid.

NOTE: open browser console to se the errors popping up in next step

Pic the element type 

Enter some awesome test value in the property

Submit changes and save document.

reload page and check if the value got saved in the block grid element.

### Expected result / actual result

**Expected** that the entered value got saved in the document

**Actual result** the changes did not get saved.
There is several errors in the browser console. Right when the modal with the elementype edit view is opened.

![image](https://github.com/umbraco/Umbraco-CMS/assets/47383499/1bc36281-cf1f-46e1-894f-4956a3ef5222)

The same error appears when typing values in the input field.

**Comment by nul800sebastiaan** [comment]
Hey there @mjpraxis - sorry for the delay on this one. We're aware that the Block Grid and Block List don't yet work at the moment, we're working on it but it's quite a large task. So for now in RC1 and RC2 it is is a known issue that we've listed in our blog post about it (under "Known issues"): https://github.com/umbraco/Umbraco-CMS/issues/16112

FYI: RC2 is coming out very soon and will not have those two features ready yet either.

**Comment by elit0451** [comment]
Here is the correct link with the "Known issues" - https://umbraco.com/blog/umbraco-14-release-candidate/#known 😜

**Comment by mjpraxis** [comment]
@elit0451 @nul800sebastiaan 

Is there a roadmap for features in v14 or a list of features release/ready for test in each release candidate?

Just so we know when to expect to be able to test certain features?

**Comment by elit0451** [comment]
Hi again @mjpraxis,

That is a great question! Here are the release documents for the frontend and we are working on creating a similar one for the backend repo as they are currently kept in 2 different repositories:
- FE: https://github.com/umbraco/Umbraco.CMS.Backoffice/releases

There you will be able to follow what has changed between the release candidates. We appreciate your time for testing the releases 🙌 H5YR!

**Comment by elit0451** [comment]
Here is the link for the backend changes:
- https://github.com/umbraco/Umbraco-CMS/releases

**Comment by nul800sebastiaan** [comment]
In RC3, which was just released, values do get saved now, so I'll close this issue as fixed.
