### ISSUE TITLE
12.3.8+ performance degraded

### ISSUE THREAD

**Issue by matthewcare** [umbraco/Umbraco-CMS#16120]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

12.3.8 onwards

### Bug summary

The change from `LazyReaderLockInner` to `EagerReadLockInner` in `LockingMechanism` has had a severe performance impact in certain scenarios.

### Specifics

I was using the `PublicAccessServiceExtensions` method `HasAccess` to only render links for pages a user had access to.

`contentItems.Where(item => publicAccessService.HasAccess(item.Id, contentService, "NOT_REQUIRED", roles))`

The site ended up having 320 items that needed checking, and after upgrading to 12.3.8+ I noticed pages taking very long to load, and after profiling noticed hundreds of SQL calls.
![image](https://github.com/umbraco/Umbraco-CMS/assets/1469061/9a8b1b34-4e7f-4a4e-bd07-ac9f60b0e239)

Prior to 12.3.8 there were no DB calls for this, and I narrowed it down to the change to `EagerReadLockInner`

Fortunately changing to the other available method that doesn't require the content service is a suitable workaround, however I wonder which other areas of Umbraco are affected by this potential performance impact.

```
@foreach (var contentItem in contentItems)
{
    var path = contentItem.Path.EnsureEndsWith("," + contentItem.Id);
    var hasAccess = await PublicAccessService.HasAccessAsync(path, "NOT_REQUIRED", () => Task.FromResult(roles));
}
```

### Steps to reproduce

Create an Umbraco installation with a version prior to 12.3.8

Using this code in a view (replacing `contentItems` with whichever items you want to check from your installation)

```
@using Umbraco.Cms.Core.Services
@inject IPublicAccessService PublicAccessService
@inject IContentService ContentService
@inherits UmbracoViewPage<IPublishedContent>

@foreach (var contentItem in contentItems)
{
    var hasAccess = PublicAccessService.HasAccess(contentItem, ContentService, "NOT_REQUIRED", []);
}

@Html.RenderProfiler()
```

observe that there are no DB hits (don't forget the query string `?umbDebug=true` to see the MiniProfiler window).

Upgrade the project to 12.3.8 or later, and observe that the same code now has DB hits.

### Expected result / actual result

I'm not really sure what the expected result is, but having pages go from less than 100ms load time to more than 8 seconds after upgrading Umbraco certainly feels like something I would not expect, though maybe I'm not using the method in its intended way.

**Comment by bergmania** [comment]
Hi @matthewcare 

I sorry for this, but it is by design, because the lazy locks led to a lot of deadlocks..

I will recommend you to wrap it in a scope (Like I would for all your use cases), thereby it should ensure each lock is only requested once.

**Comment by matthewcare** [comment]
Hi @bergmania 
As long as it is known about. I wasn't sure if there would be some cases in the backoffice where this might have some affect, but since the change was intentional you'd probably know if there were any issues. It was just an unexpected behaviour change for me and took some time to resolve, it all worked out in the end though.
