### ISSUE TITLE
Custom list views are not shown as tracked references

### ISSUE THREAD

**Issue by bjarnef** [umbraco/Umbraco-CMS#16131]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

12.3.9

### Bug summary

I noticed on a few Umbraco Cloud projects that the created listview datatype instance from document type is used as custom list view, but doesn't track the reference even though it is in use.

![image](https://github.com/umbraco/Umbraco-CMS/assets/2919859/81c5151a-6a91-4425-9994-9af23b30f4f7)

![image](https://github.com/umbraco/Umbraco-CMS/assets/2919859/52fb9775-4e68-4cf2-aee6-4441fea311a9)

### Steps to reproduce

Create a custom list view for a  document type.

**Comment by NguyenThuyLan** [comment]
Thank you for reporting this issue. Please note that the version of Umbraco you are referring to is already end of life. We recommend upgrading to a newer version to benefit from the latest features and security updates. If you encounter this issue on a supported version, please feel free to reopen this ticket with details. Thank you for your understanding.

**Comment by bjarnef** [comment]
I can see is has been fixed in latest v13.

![image](https://github.com/umbraco/Umbraco-CMS/assets/2919859/0e91bf76-0b49-432e-84eb-f3c4ed614b91)

Although it doesn't seem to be handled for default listviews:

- List View - Content
- List View - Media
- List View - Members

E.g. "List View - Media" is used on "Folder" media type:

![image](https://github.com/umbraco/Umbraco-CMS/assets/2919859/ae2e38e9-e438-4e00-88c7-3446f60cef6f)
