### ISSUE TITLE
v14-rc2 - add custom view to a block in the settings of a Block Grid datatype

### ISSUE THREAD

**Issue by mjpraxis** [umbraco/Umbraco-CMS#16134]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

v14-rc2

### Bug summary

When adding a custom view to a block in a block grid data type it is not visible that there is a custom view selected.

### Specifics

Chrome Version 124.0.6367.61

### Steps to reproduce

Create some very simple document-/element types and datatype

ElementType: with one property eg. "bodytext" (Textarea)
DataType: "Block Grid Property Editor UI" with the above Element Type added to the list of Blocks
Add a .html to the "Custom view" list
![image](https://github.com/umbraco/Umbraco-CMS/assets/47383499/38836cde-2971-451e-acf3-83e23a6d5d31)
And finally save the datatype

### Expected result / actual result

Expected result:
To see the selected .html file in the list of Custome view.

Actual result:
The Custom view list is empty

Observations:
The PUT request made at the data type save. Has the selected file in the payload json.
![image](https://github.com/umbraco/Umbraco-CMS/assets/47383499/617ce435-e18d-49bd-8332-9cdf4aaab98a)

**Comment by Zeegaan** [comment]
I can definetly reproduce this, thanks for reporting 🐛

**Comment by nielslyngsoe** [comment]
This will be, sort of, fixed as part of this PR:
https://github.com/umbraco/Umbraco.CMS.Backoffice/pull/2065

As v.14 comes with a Extension Registry, this has allowed us to finally move Custom Views into code, making them a Backoffice extensions them selfs.

Therefor it will no longer possible to pick a file via UI, this is done in the same way s any other UI extension.

**Comment by firthy** [comment]
Yes I agree. How do you get a manifest for the block list? The docs need updating as how to create a custom view for a block list.
