### ISSUE TITLE
V14-RC2: Image cropper datatype - alias value doesn't autofill.

### ISSUE THREAD

**Issue by KevinJump** [umbraco/Umbraco-CMS#16159]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

v14-rc2

### Bug summary

When entering crop information on an image cropper datatype, the alias doesn't autofill when you enter the label 

### Specifics

when you add an image cropper crop value on Umbraco v13 the alias value autofills when you enter the label value. on v14 this doesn't happen and you have to enter the alias value manually. 

### Steps to reproduce

- create a new image cropper datatype
- enter a value in the "label" box for a new crop

observe that the alias value doesn't autofill 

(the above will autofill the label on v13)

**Comment by Zeegaan** [comment]
I can certainly reproduce this 😁 
Thanks for reporting 🐛
