### ISSUE TITLE
V14-RC2: Colour picker datatype : doesn't stay open while picking colour.

### ISSUE THREAD

**Issue by KevinJump** [umbraco/Umbraco-CMS#16157]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

v14-rc2

### Bug summary

When picking a colour for the values in the colour picker the 'swatch' window closes as soon as you click on it.

### Specifics

The swatch window closes as soon as you click on it, you can't drag and drop. 

for info the Eye Dropper colour picker on a content item behaves the "correct" way . it lets you pick and drag around as you select the color

### Steps to reproduce

- create a nwe colour picker datatype
- click on the colour box to open the colour picker
- attempt to drag the dropper to pick a colour (the window closes)

**Comment by Zeegaan** [comment]
I can reproduce this, thanks for reporting! 🐛

**Comment by leekelleher** [comment]
Client-side PR to fix this issue: https://github.com/umbraco/Umbraco.CMS.Backoffice/pull/1806
