### ISSUE TITLE
V14-RC2 : Enter doesn't add when enterting date in Radio, Checkbox, Dropdown Datatypes. 

### ISSUE THREAD

**Issue by KevinJump** [umbraco/Umbraco-CMS#16156]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

v14-rc2

### Bug summary

When entering data into a dropdown style (e.g dropdown, checkbox, radio button) data type, the items pressing enter doesn't add the item and move the user into a new box to enter the next item. 

### Specifics

on v13.  you would type
item one - [ENTER] - item two [ENTER] - item three [enter] item four 

![dropdownv13](https://github.com/umbraco/Umbraco-CMS/assets/431231/cc5092ca-92ee-4c96-bcd6-073cf9bb98c8)

and get four items. 

on v14, you have to click after each item to add it. 

### Steps to reproduce

- Create a new datatype of type checkbox
- enter items, 
- see that you have to use the mouse.

---
_This item has been added to our backlog AB#42512_

**Comment by Zeegaan** [comment]
I can certainly reproduce this, thanks for reporting 🐛
