### ISSUE TITLE
V14-RC2 : Document Types - Create folder, name isn't in focus

### ISSUE THREAD

**Issue by KevinJump** [umbraco/Umbraco-CMS#16167]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

v14-rc2

### Bug summary

When creating a new folder in the document types (or media types) tree, the dialog that opens up does not have the input box in focus. so you have to click on the folder name to create  a folder. 

### Steps to reproduce

- select 'create' on the document types menu
- select folder
- observe that the input box is not in focus.

**Comment by Zeegaan** [comment]
I can definitely reproduce this, thanks for reporting! 🐛
