### ISSUE TITLE
V14-RC2 - Image Upload field datatype doesn't add new row on return

### ISSUE THREAD

**Issue by KevinJump** [umbraco/Umbraco-CMS#16162]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

v14-rc2

### Bug summary

Adding a file extension type to an Upload field datatype and pressing return doesn't add a new row. (you shouldn't have to click add)

### Steps to reproduce

- create a new upload field datatype
- add new accepted file extension
- hit return after typing field.
a new row should appear so you can add a new one

---
_This item has been added to our backlog AB#42516_

**Comment by Zeegaan** [comment]
I can reproduce this, thanks for reporting 🐛
