### ISSUE TITLE
V14-RC2 : Document Types - can't reorder tabs.

### ISSUE THREAD

**Issue by KevinJump** [umbraco/Umbraco-CMS#16166]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

v14-rc2

### Bug summary

When managing a document type, you cannot re-order the tabs (re-order properties works).

clicking on re-order causes the number boxes to appear, but the boxes on tabs are not editable

![image](https://github.com/umbraco/Umbraco-CMS/assets/431231/2ce68708-85e1-4204-a154-6f531da1de66)

While you can drag and drop the tabs  when working with compositions it is common to want to set the values so you can re-order across multiple types (e.g set values to 10, 20, 30, so other compositions can set to 11, 12, etc...)

 

### Steps to reproduce

- creates a new document type
- add some properties and multiple tabs
- click on reorder
- attempt to set value for tab order

**Comment by Zeegaan** [comment]
Drag and drop works, but I see as described, you cannot enter the numbers 😢 
Thanks for reporting 🐛

**Comment by iOvergaard** [comment]
This has been fixed in 14.1!
