### ISSUE TITLE
V14-RC2 : Document Types - name box isn't in focus when you create a new type

### ISSUE THREAD

**Issue by KevinJump** [umbraco/Umbraco-CMS#16169]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

v14-rc2

### Bug summary

When creating a new document type the name box is not in focus so you can't enter a name without clicking on the name box.

in v13 when you create a new document type the name box is in focus, so you can just start typing. 

### Steps to reproduce

- create a new document type
- observe he name box isn't in focus.

**Comment by Zeegaan** [comment]
I am happy to report this has been fixed 🚀
