### ISSUE TITLE
V14-RC2 : Image cropper - Hitting return after adding a new crop doesn't return cursor to label box

### ISSUE THREAD

**Issue by KevinJump** [umbraco/Umbraco-CMS#16160]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

v14-rc2

### Bug summary

When entering crops on an image cropper datatype, you can hit return after entering all the values and a new row will be shown. but the cursor remains in the last box that was in focus, and not the label box at the beginning of the row.

### Specifics

when you enter crops you should be able to enter the values using the keyboard, and hitting return should (and does) create a new row so you can enter the next crop. 

except when you do this the focus will remain inthe last box you where in on the last row (usually height) and you you have to eaither use your mouse or tab backwards to label.

### Steps to reproduce

- create a new image cropper datatype
- enter a crop 
- hit return
- observe that focus stays in the height box, doesn't reset to label.

**Comment by Zeegaan** [comment]
I can definitely reproduce this, thanks for reporting! 🐛
