### ISSUE TITLE
V14-RC2: Content editing - Failure of one Property should not cause whole page to fail.

### ISSUE THREAD

**Issue by KevinJump** [umbraco/Umbraco-CMS#16165]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

v14-rc2

### Bug summary

When working with a content page and a property value is either corrupt or the datatype causes an error the whole content page should not fail, you should still be able to view and edit other properties.

### Specifics

With v14-rc2 there are some bugs with some datatypes (e.g dropdown lists) that mean when you select values you get an error while viewing the page. 

the problem is this error in one preoperty causes the whole content page not to load, so effectively if you currently select a drop down value on a page you loose all access to that page and have to delete it and start again.

there will always be bugs and issues and things gettng corrupted, so when a property is broken or corrupt the whole page shoudn't fail, you should at least be able to load the page and view and edit the other properties on the page

### Steps to reproduce

- create a document type  with some properties including a drop down list on it
- create a content page for that doctype
- pick a dropdown value
- save the page
- reload the site - the page is no inaccessible.

**Comment by elit0451** [comment]
Hi there @KevinJump 👋

Thanks for reaching out! Unfortunately, I wasn't able to reproduce this when I tried with a dropdown property editor. Did you experience such behaviour with any other property editor or can you see if I am missing something on the video?

https://github.com/umbraco/Umbraco-CMS/assets/21998037/25368c06-5f4e-4f4b-8fd8-64ca10c754d1

**Comment by KevinJump** [comment]
Hi, 

in this case you need to make the drop-down multi-picker (although this has been fixed post RC2 - so it might not break on a new branch, (checkbox also breaks it , again might be fixed in latest releases)

its not the breaking of the dropdown or checkbox that is the issue - so much that any broken property breaks the whole page.

**Comment by elit0451** [comment]
I understand, I will let the team know. 🙂  And if you encounter any other cases where you see such behaviour please add a comment to this issue as it might be easier to pinpoint the problem.

**Comment by iOvergaard** [comment]
This has been fixed along the way, presumably already in 14.0, which launched a month after this issue was created. I have tried to reproduce it in 14.1, but luckily I got no errors. I will chalk it up to being fixed in 14.0. Please do re-open it if you experience any issues!
