### ISSUE TITLE
Nested content doesn't load properly when used as a macro parameter

### ISSUE THREAD

**Issue by sandhuravinder** [umbraco/Umbraco-CMS#16175]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

13.3

### Bug summary

I got an accordion with two fields and a macro with one parameter. Macro parameter is a custom parameter that used nested content to load accordion. It's working fine in the 7.15.6 version of Umbraco. But as soon as I upgraded it to 13.3, it's failing as shown in the picture. The below example is on clean install of 13.3 

![image](https://github.com/umbraco/Umbraco-CMS/assets/137611160/4661b0cf-6a03-49c8-930f-249cdda8a25d)

![image](https://github.com/umbraco/Umbraco-CMS/assets/137611160/0d610313-8c42-4263-a539-2cdc288ad718)

![image](https://github.com/umbraco/Umbraco-CMS/assets/137611160/918de316-a0da-4bd2-8a41-3901343f4c73)

![image](https://github.com/umbraco/Umbraco-CMS/assets/137611160/129e8f35-e81f-4770-b79d-f37514d2c02b)

### Steps to reproduce

Macro is used via a RTE. When I click on the macro within RTE, it loads it properly  
![image](https://github.com/umbraco/Umbraco-CMS/assets/137611160/050a3996-6ae4-4061-8cdb-4efabf3bb445)

But as soon as I click on the Add content button, I get below 
![image](https://github.com/umbraco/Umbraco-CMS/assets/137611160/310860ff-a0bb-4208-a993-3a99405310a6)

along with an error in console
![image](https://github.com/umbraco/Umbraco-CMS/assets/137611160/39ac1a50-e52e-4a0e-8e24-8159160ff11c)

### Expected result / actual result

When clicked on **Add content** button in the macro parameter, it should load the accordion nested content properly

**Comment by ravindersinghsandhu** [comment]
@UmbracoHQ, any update on this issue?

**Comment by ravindersinghsandhu** [comment]
I have also tried Umbraco cloud's fresh install but got the same problem there as well

![image](https://github.com/umbraco/Umbraco-CMS/assets/137611160/0ac0ee7d-e52a-4242-8e1b-4adb5b976c3e)

![image](https://github.com/umbraco/Umbraco-CMS/assets/137611160/9d281dee-f199-4091-96f1-62d3b63775e4)

**Comment by sandhuravinder** [comment]
Migrated nested content to block list instead of waiting for resolution.
