### ISSUE TITLE
Values not populated for properties that vary by culture but not by segment

### ISSUE THREAD

**Issue by dawoe** [umbraco/Umbraco-CMS#16186]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

13.0.0-13.3.0

### Bug summary

We have a website running on Umbraco 10.8.5 with uMarketingSuite 2.2.0 for personalization.

We have setup our doctypes to "Allow vary by culture" and "Allow segmentation".
On our documenttypes almost all properties have "Allow vary by culture" enabled and some of them also have "Allow by segmentation" enabled.

On Umbraco 10.8.5 when we viewing a personalized variant, the properties that don't have "Allow by segmentation" enabled will fallback to the current culture value.

After a upgrade to 13.x these properties will return a empty value in that case, similar to this issue https://github.com/umbraco/Umbraco-CMS/issues/15117

### Specifics

I have setup a vanilla Umbraco website running 13.3.0 to see if the issue is reproducable on without uMarketingSuite involved. Unfortunately it is.

I have set up a simple website to reproduce this based on the code from this issue : https://github.com/umbraco/Umbraco-CMS/issues/15564

### Steps to reproduce

1. Download this [zip file](https://github.com/umbraco/Umbraco-CMS/files/15160501/SegmentIssue.Website.zip) and extract it.
2. Start the website project using dotnet run
3. Once setup log in to the backoffice with admin@dotcontrol.com / 1234567890
4. Go to the settings section and import settings using uSync. This will setup a doctype.
5. Create content for the english language and the customer and visitor segment.
6. View the content item on the website.
7. Then append a querystring ?s=customer or ?s=visitor to enable the segmented content and see that property that does not Allow segmentation does not return a value.

### Expected result / actual result

I would expect that properties that do not allow segmentation would return the the value from the culture like in Umbraco 10.8.5

No segment enabled while viewing content :
![image](https://github.com/umbraco/Umbraco-CMS/assets/1193822/61c00d3d-08a2-40b5-8f5d-3091707e81f2)

Customer segment enabled through querystring
![image](https://github.com/umbraco/Umbraco-CMS/assets/1193822/2be68515-ebaf-46ea-822a-a30b06f0fd31)

Visitor segment enabled through querystring
![image](https://github.com/umbraco/Umbraco-CMS/assets/1193822/8bc53d27-f50a-49b3-9070-45c1bd839b16)

**Comment by dawoe** [comment]
@umbraco/cms-group any update on this

**Comment by kjac** [comment]
Hi @dawoe - thanks for reaching out. I'll look into this today 👍

**Comment by kjac** [comment]
PR in #16270
