### ISSUE TITLE
V14-RC2: `Settings -> Welcome` community & support tabs have the same content

### ISSUE THREAD

**Issue by liamlaverty** [umbraco/Umbraco-CMS#16209]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

V14-RC2

### Bug summary

Support link should describe the Umbraco support package

![image](https://github.com/umbraco/Umbraco-CMS/assets/7046713/dcb75e3d-594d-4aa4-aeb3-015c4c88ec3c)

### Steps to reproduce

- Navigate to https://localhost:44320/umbraco/section/settings/dashboard/welcome

### Expected result / actual result

Text should be different for the two sections

**Comment by andr317c** [comment]
Hey!

I was able to reproduce this. Thanks for reporting the issue! 😄

**Comment by iOvergaard** [comment]
Will be fixed in RC3.
