### ISSUE TITLE
V14-RC2: Icon color selector has multiple inputs for `black`

### ISSUE THREAD

**Issue by liamlaverty** [umbraco/Umbraco-CMS#16205]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

V14-RC2

### Bug summary

See screenshot below. 

When creating a new document type, after opening the _Select Icon_ side panel, the user is presented with two black icon colours. 

![image](https://github.com/umbraco/Umbraco-CMS/assets/7046713/593e3217-cc38-47a1-934e-2f02db1dc063)

### Specifics

https://localhost:44320/umbraco/section/settings/workspace/document-type/create/document-type-root/null/null/view/design/root

The `background-color` for the two swatches are different, one is `--uui-swatch-color, text`, while the other is `--uui-swatch-color, black`

**First swatch:**
```html
<div class="color-swatch__color" style="background-color: var(--uui-swatch-color, text)"></div>
```

**Second swatch:**
```html
<div class="color-swatch__color" style="background-color: var(--uui-swatch-color, black)"></div>
```

### Steps to reproduce

- Open _Create Document Type_ journey
- Click the _Icon_ to the left of the _Title_ input
- See the two black coloured swatches

### Expected result / actual result

Only one black swatch.

**Comment by andr317c** [comment]
Hey!

Thanks for reporting this issue! I was able to reproduce this. 🐛
