### ISSUE TITLE
V14-RC2: Can select multiple icons at once

### ISSUE THREAD

**Issue by liamlaverty** [umbraco/Umbraco-CMS#16206]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

V14-RC2

### Bug summary

In the _Select Icon_ popout menu, I can select two icons at the same time. 

![image](https://github.com/umbraco/Umbraco-CMS/assets/7046713/e1c4182d-9058-4af9-9509-9a4a5667103c)

![image](https://github.com/umbraco/Umbraco-CMS/assets/7046713/41626333-b418-4c8f-ab52-8d14f9f9dfbb)

![select-icon-bug](https://github.com/umbraco/Umbraco-CMS/assets/7046713/31dbdc34-c7c5-4c5f-910c-2b68aefa579f)

### Specifics

In the _Icon Picker_ popout menu, I can select an icon, then click a second icon, and have it appear as if it is selected, even if it's not. 

### Steps to reproduce

- Open the icon selector menu
- Click any icon **on the SVG/picture part of the icon**
![image](https://github.com/umbraco/Umbraco-CMS/assets/7046713/83cbfe13-9040-4900-87d6-4cef04c04809)
- Click any icon off the SVG/picture part of the icon, **but within the boundaries of its wrapper**
![image](https://github.com/umbraco/Umbraco-CMS/assets/7046713/07ff998e-c322-4eab-a787-dd29dee02967)
- Both icons will appear as selected

### Expected result / actual result

Only one icon at a time is bordered

**Comment by andr317c** [comment]
Hey!

Thanks for reporting all these issues! We appreciate it 💪. I was able to reproduce the issue.
