### ISSUE TITLE
v14 - Examine Dashboard issues

### ISSUE THREAD

**Issue by Shazwazza** [umbraco/Umbraco-CMS#16213]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

14.0.0-rc2

### Bug summary

There's a few issues with the Examine dashboard. I'm sure some are known since when you click on some things it pops up with TODO, but there are others, here's the list:

* [ ] When the `IIndexDiagnostics` reports unhealthy, the dashboard not longer uses the `Attempt<string>` result to display the unhealthy error message. The string returned from this attempt should be displayed.
* [ ] When the `IndexDiagnostics` reports unhealthy, the search bar isn't shown. Even though the index reports unhealthy, the search bar should remain visible. There are different reasons for an index to report unhealthy - for example, in ExamineX if there are license issues.
* [ ] When clicking Rebuild index for Lucene based (default) indexes, the UI responds but the request doesn't really seem to do anything or wait for the index rebuild to actually complete. When clicking Rebuild when using a non Lucene index (i.e. ExamineX) the exact same HTTP request and response is done (the index rebuild does occur), but the UI doesn't respond and is just stuck on: 
![image](https://github.com/umbraco/Umbraco-CMS/assets/1742685/8ccd7d7c-c4a4-4bbe-a40c-69f88d0bd0b6)
![image](https://github.com/umbraco/Umbraco-CMS/assets/1742685/65f496cb-2002-4bd7-96df-7821ac4ff71e)
* [ ] When searching and then clicking on the fields button, a blank panel is shown:
![image](https://github.com/umbraco/Umbraco-CMS/assets/1742685/e4355713-78ce-450b-86c3-5474ec8fba0d)
![image](https://github.com/umbraco/Umbraco-CMS/assets/1742685/390c3b27-097f-46ee-8881-204031643e30)
* [ ] When clicking on the name of the document in search results, it pops up a TODO alert
![image](https://github.com/umbraco/Umbraco-CMS/assets/1742685/6eec6a47-30b0-4b0e-94f1-71e3a25a772c)
![image](https://github.com/umbraco/Umbraco-CMS/assets/1742685/398f8b10-c606-4619-80ba-b5a01d110f07)

### Steps to reproduce

See above.

### Expected result / actual result

Should function the same way that the dashboard did in Umbraco 13.

**Comment by elit0451** [comment]
Hey @Shazwazza 😊 

Hope things are well on your end! We will have a look 💪

**Comment by madsrasmussen** [comment]
@elit0451 and @loivsen 

Can we close this issue?

**Comment by elit0451** [comment]
Seems like we covered both frontend and backend 🙂
