### ISSUE TITLE
Mandatory empty RTE in composition is ignored on save and publish

### ISSUE THREAD

**Issue by SelwynEdelbroek** [umbraco/Umbraco-CMS#16229]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

13.2.2

### Bug summary

Since version 13.2.2 we've seen cases that the property RTE marked as mandatory can be saved and published while being empty in the backoffice. The property is added to an element type which is allowed vary by culture but the property is not allowed vary by culture. The created doctype is also allowed vary by culture.

When the property has the allow vary by culture = true setting the validation hits correctly and no save and publish event is triggered.
![image](https://github.com/umbraco/Umbraco-CMS/assets/92163864/5943db1d-b9d6-410b-9be6-6c42f829faef)

For now we have added custom code on the saving notification handler to validate the properties.

```
public class DisruptionSavingContentNotificationHandlers : INotificationAsyncHandler<ContentSavingNotification>
{
    public Task HandleAsync(ContentSavingNotification notification, CancellationToken cancellationToken)
    {
        foreach (var entity in notification.SavedEntities)
        {
            var emptyMandatoryProperties = entity.Properties.Where(x => x.PropertyType.Mandatory && x.Values.Any(v => string.IsNullOrWhiteSpace(v.EditedValue?.ToString())));

            if (emptyMandatoryProperties.Any())
            {
                foreach (var property in emptyMandatoryProperties)
                {
                    notification.Messages.Add(new EventMessage("Error", $"Veld '{property.PropertyType.Name}' is verplicht", EventMessageType.Error));
                }

                notification.CancelOperation(new EventMessage("Error", "Validatie mislukt op velden", EventMessageType.Error));
            }
        }

        return Task.CompletedTask;
    }
}
```

### Specifics

In the screenshot below is an example of the doctype with the composition added:
![2024-05-07 15_45_41-Edit_ Verstoring - Edit_ Verstoring (Geplanned) - Edit_ Test selwyn - Content - ](https://github.com/umbraco/Umbraco-CMS/assets/92163864/68d70e6a-8304-4983-8eb8-0f5d3dd93729)

Property added as mentioned (mandatory and allow vary by culture = false):
![2024-05-07 15_34_05-Edit_ Verstoring (Geplanned) - Settings - localhost](https://github.com/umbraco/Umbraco-CMS/assets/92163864/df96d6c8-7aa0-4c8c-b403-5326698b8bb1)

Debug session also shows that the value is null on save and publish while debugging the saving notification handler
![2024-05-07 15_28_02-htm (Debugging) - Microsoft Visual Studio](https://github.com/umbraco/Umbraco-CMS/assets/92163864/379ef31a-a072-49ce-97dd-ce12fd075efc)

Editor sees the succesfull published notification while value is empty:
![2024-05-07 15_38_19-Edit_ Test selwyn - Content - localhost](https://github.com/umbraco/Umbraco-CMS/assets/92163864/8a284d2d-1196-481e-be04-e16b13aaf474)

### Steps to reproduce

1. Create element type (allow vary by culture = true) in settings
2. Add mandatory RTE property (allow vary by culture = false) in settings
3. Add element type as composition on doctype (allow vary by culture = true) in settings
4. Save and publish node with value in RTE in content
5. Remove value from RTE save and publish again in content

### Expected result / actual result

The expected result would be a validation error that the RTE is empty. The actual result is an empty property while marked as mandatory.

**Comment by NguyenThuyLan** [comment]
Hi @SelwynEdelbroek , thanks for reporting this issue. 
Unfortunately 😥, I couldn't reproduce it. Please check the video below to see that I reproduced it on V13.2.2 and it ran as normal. If I missed something, please let me know 😁
https://github.com/user-attachments/assets/a38a9c05-207f-4694-9dd7-02d838866643
