### ISSUE TITLE
Delivery API Id-token is missing when "offiline_access" is part of the scope

### ISSUE THREAD

**Issue by mcl-sz** [umbraco/Umbraco-CMS#16221]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

13.3

### Bug summary

I am absolutely no expert in the field of OpenId, but I have encountered the following problem.
I want to create an app (Capacitor) where the user has to log in and then stays logged in using a refresh_token.
When I set the scope to "openid offline_access" in the client, only the "offline_access" scope is returned by the authentication API.

![afbeelding](https://github.com/umbraco/Umbraco-CMS/assets/18614643/a7f31165-b7fd-475e-8846-714ef9e34e27)

I created a PR  https://github.com/umbraco/Umbraco-CMS/pull/16220 that checks if both options are set in the scope but I don't know if this is technically correct, combining the offline_access scope with other options.

![afbeelding](https://github.com/umbraco/Umbraco-CMS/assets/18614643/72c442c7-79f8-4a2b-aef7-01f35e2753e8)

Would anyone from with knowledge of OpenId want to take a look at this?

### Steps to reproduce

See my PR how you can test this: https://github.com/umbraco/Umbraco-CMS/pull/16220

### Expected result / actual result

I would expect that both the OpenId and OfflineAccess tokens get returned when they are requested by the client.

**Comment by kjac** [comment]
Hi @mcl-sz,

Thanks for this! I'll give it a look soon 👍

**Comment by kjac** [comment]
Fixed in #16220
