### ISSUE TITLE
V14-RC3 - Long content names removes the save and preview button from the content workspace

### ISSUE THREAD

**Issue by nikcio** [umbraco/Umbraco-CMS#16235]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

14.0.0-rc3

### Bug summary

When having long content node names it's possible to completely remove the "save and publish" buttons from the screen.

https://github.com/umbraco/Umbraco-CMS/assets/24605285/055b308b-693f-4344-8cc7-22cd0fe7d257

### Steps to reproduce

1. Create multiple nodes with long names under each other

### Expected result / actual result

I would expect not to be able to remove the buttons from the screen. I think the right thing to do is just to make it scrollable and show the most recent breadcrumb.

**Comment by Zeegaan** [comment]
I can reproduce this 🐛 
Thanks for reporting, we will have a look 🕵️
