### ISSUE TITLE
V14-RC3 - Long content node names gets cropped

### ISSUE THREAD

**Issue by nikcio** [umbraco/Umbraco-CMS#16234]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

14.0.0-rc3

### Bug summary

When a content node has a very long name it gets cropped straight through the letter.

In v13 long content node names ended in `...` and it was possible to modify the width of the sidebar to allow longer names to be written out. This feature is also missing in v14.

![image](https://github.com/umbraco/Umbraco-CMS/assets/24605285/85ac337a-f878-41d4-a140-989f321a51ba)

https://github.com/umbraco/Umbraco-CMS/assets/24605285/84ce580e-f223-4bdc-8d98-9bdfd496cdf0

### Specifics

The problem with the sidebars width not being modifiable can also be seen here.

![image](https://github.com/umbraco/Umbraco-CMS/assets/24605285/5861be80-15c1-488e-92a5-04e8379c7e0c)

The more nested a page is the shorter a name is shown which makes it more difficult to make out which page is which.

Also more of the name can be seen when switching between trees which is also weird visually.

### Steps to reproduce

1. Create a node with a long name. Example: `Home-bb344519-50fc-4b5d-aa21-12b2ee9c8c0b`

### Expected result / actual result

1. I would expect the node name ending in `...` if too long to be shown
2. I would expect to be able to modify the width of the sidebar

**Comment by andr317c** [comment]
Thanks for reporting this issue! I was able to reproduce this. It also happens for the Media items and Users.

**Comment by madsrasmussen** [comment]
Hi @nikcio 

I just retested this issue and it is fixed now. I am not 100% sure what version this has been fixed in but at the time of writing, I have tested this in an early version of 14.3. I would think this is also fixed in 14.2.

<img width="609" alt="Screenshot 2024-08-19 at 11 22 40" src="https://github.com/user-attachments/assets/a6f3aef6-8799-4df4-a7c2-e3c91cb15a1e">

**Comment by nikcio** [comment]
@madsrasmussen is it now also possible to adjust the sidebar width?

Note: I'm not sure how much editors was using that feature but I can see i mentioned it in this issue also😅

**Comment by madsrasmussen** [comment]
@nikcio Oh, I don't know why I missed that. Yes, it is also possible to change the width of the sidebar via drag and drop 👍
