### ISSUE TITLE
V14-RC3 - When having many content nodes the URL preview in chrome hides the "Recycle bin"

### ISSUE THREAD

**Issue by nikcio** [umbraco/Umbraco-CMS#16236]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

14.0.0-rc3

### Bug summary

When having many content nodes the URL preview in chrome hides the "Recycle bin"

![image](https://github.com/umbraco/Umbraco-CMS/assets/24605285/fe46e31c-9bf5-4a0f-b84f-8bd3a7c5d0d1)

### Steps to reproduce

1. Create a lot of content nodes.
2. Hover a content node while having scrolled to the bottom of the list in the content tree.

Tip:
To quickly create a bunch of content nodes you can add a API endpoint in the `program.cs` like this:
```csharp
app.MapGet("/create-content/{number:int}", ([FromServices] IContentService contentService, int number) =>
{
    for (int i = 0; i < number; i++)
    {

        contentService.CreateAndSave($"Home-{Guid.NewGuid()}", -1, "home");
    }

    return Results.Ok("Done :)");
});
```

### Expected result / actual result

I would expect enough padding that I could clearly see the "Recycle bin"

**Comment by Zeegaan** [comment]
I can reproduce this, thanks for reporting 🐛
