### ISSUE TITLE
V14-RC3: Dark mode wrong color for font 

### ISSUE THREAD

**Issue by rammi987** [umbraco/Umbraco-CMS#16247]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

14.0.0-RC3

### Bug summary

When setting the Umbraco theme to dark mode, near all right overlays has font color of black on dark gray background, witch does it diffecult to read the text. 

The same is the text under document type/templates where the template name is also black.

The property editor on doctype is in correct color.

- [ ] Avatar menu
- [ ] Doctype/Media/data types/document blueprints/partials views/Stylesheets/scripts action menu
- [ ] Doctype composition overlay
- [ ] Doctype templates - template name 
- [ ] Templates Master template
- [ ] Templates insert overlay
- [ ] templates insert dropdown
- [ ] Template query builder 
- [ ] template sections
- [ ] Log viewer stacktrace
- [ ] Webhooks / create / overlays for events and header
- [ ] Menbers section, edit member action menu 
- [ ] Users section / user groups / assing section overlayer
- [ ] Users section / user grouos /Granular permissions overlayer 
- [ ] Users section / create user / user group overlay
- [ ] Users section / invite user / user group overlay
- [ ] User section / user overview / search facts dropdown
- [ ] USers section / user edit / UI culture, groups, content node, select media start node
- [ ] packages / create packages / all overlayers
- [ ] Media section / create media / select media type overlayer
- [ ] Media section / edit media / action menu
- [ ] Media section / edit media / Info app - the edit button overlayer
- [ ] Media section / move to
- [ ] Media Section / recucle bin / restore
- [ ] Content section / create node overlayer
- [ ] Content section / edit node / properties with overlayer
- [ ] Content section / edit node / action menu
- [ ] Content section / edit node / info app - the edit button overlayer
- [ ] Content section / edit node / the save and publish extra menu
- [ ] Content section / edit node / schedule
- [ ] content section / Create blueprint
- [ ] content section / move to
- [ ] Content section / unpublish pop up box
- [ ] Content section / Culture and hostname
- [ ] Content section / sort
- [ ] Content Section / recucle bin / restore
- [ ] Umbraco logo version infomation  
- [ ] Translations / import
- [ ] Translations / export
- [ ] translations / move to 
- [ ] 

### Steps to reproduce

Follow above checklist after set umbraco theme to dark mode

### Expected result / actual result

Readable by have the text color in white

---
_This item has been added to our backlog AB#42545_

**Comment by NguyenThuyLan** [comment]
Thanks @rammi987 for reporting this, I agree that the text color should be brighter
<img width="1123" alt="image" src="https://github.com/user-attachments/assets/38196114-ff8a-4660-adbb-578984fc087f">
