### ISSUE TITLE
Enter key does not submit umbraco login form

### ISSUE THREAD

**Issue by prjseal** [umbraco/Umbraco-CMS#16240]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

14 RC 3

### Bug summary

When logging in to the Umbraco backoffice the enter key doesn't submit the login form. 

It always has on the previous versions.

Please can you fix it so the form submits on enter.

### Specifics

![image](https://github.com/umbraco/Umbraco-CMS/assets/9142936/ab94386e-7d62-4ed4-a546-66ce7079f45d)

### Steps to reproduce

Install Umbraco v14 rc3 and try to login by pressing the enter key after you have entered your email and password.

You will not be able to login unless you press the Login button

### Expected result / actual result

I expected to be able to login when I pressed the enter key after having entered my email and password

But what actually happened was nothing.

**Comment by Zeegaan** [comment]
Heyo, this has been fixed in RC4! Thanks for reporting 🐛
