### ISSUE TITLE
V14-RC3: No option to sign in with local login after session timeout

### ISSUE THREAD

**Issue by bjarnef** [umbraco/Umbraco-CMS#16253]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

14.0.0-rc3

### Bug summary

I noticed after session timeout it shows the following page, but I have no option to signin with local login form:

![image](https://github.com/umbraco/Umbraco-CMS/assets/2919859/ee87fbbc-8c3c-4072-a5d0-6c1af4053ddc)

I have to access `/umbraco` in URL instead to show the normal login page.

### Steps to reproduce

Log into Umbraco backoffice and wait until session timeout.

**Comment by iOvergaard** [comment]
Hi @bjarnef 

I am not sure I understand completely. You click the "Sign in with Umbraco" and what happens then? Are you not allowed to log in?

**Comment by bjarnef** [comment]
I will check again, perhaps it just lokkede like signin with UmbracoID.
Any reason it can't show the local login form directly here?

**Comment by iOvergaard** [comment]
This is the timeout screen, which resides in the backoffice client. The local login screen is a page served from the server, which is used for any OpenID applications (Swagger, Postman, the backoffice, your own apps). You cannot log in locally before you have selected which login provider you want to use. In your case here, you only have one provider (Umbraco), so it looks a little funny. I have been working on a feature to make the experience feel more integrated. We will have to see if it makes the cut.

**Comment by iOvergaard** [comment]
It's on the roadmap to make the experience more seamless, but at least now for RC4, you will only see this screen if you time out. I'll go ahead and close this issue as you can log in by clicking the "Sign in with Umbraco" button.
