### ISSUE TITLE
Umbraco directives console error

### ISSUE THREAD

**Issue by vlaellayug** [umbraco/Umbraco-CMS#16256]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

13.3.0

### Bug summary

There's a console error when opening any block that have tabs.

### Steps to reproduce

1.) Create a block with tabs

![image](https://github.com/umbraco/Umbraco-CMS/assets/32614506/7b31b873-5a46-486d-8172-fbbe53d3d9f1)

2.) Use the block on any page, then the error can be replicated once you click that block

![chrome_KCaszGSdU7](https://github.com/umbraco/Umbraco-CMS/assets/32614506/8694d498-b2b8-4385-993c-d7f136a8c261)

**Comment by Matthew-Wise** [comment]
Fixed in #16257
