### ISSUE TITLE
14-rc3 Public Access by group only let you pick Member types instead of Member Groups

### ISSUE THREAD

**Issue by lindea** [umbraco/Umbraco-CMS#16259]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

14.0.0-rc3

### Bug summary

When selecting "Restrict Public Access" -> "Group based protection" -> "Select the groups who have access to the page <node-name>" I only get to select Member type (it seems) and not a member group.

### Specifics

<img width="1100" alt="image" src="https://github.com/umbraco/Umbraco-CMS/assets/317286/4c0f205a-aec1-432a-99b0-d60e6207769a">

### Steps to reproduce

1. Create some content
2. Select the content in the content tree
3. Select the "Actions ->"-button
4. Select "Restrict Public Access"
5. Select "Group based protection"
6. Select "Next"
7. Select the "Choose"-button under "Select the groups who have access to the page <name-of-content>"

### Expected result / actual result

A panel with an Member type-item appears /
Expected a panel with member groups items

**Comment by Zeegaan** [comment]
I can certainly reproduce this, thanks for reporting 🐛

**Comment by leekelleher** [comment]
Patch available on PR: https://github.com/umbraco/Umbraco.CMS.Backoffice/pull/1916.
