### ISSUE TITLE
V14-RC3: Avatar generated from name

### ISSUE THREAD

**Issue by bjarnef** [umbraco/Umbraco-CMS#16250]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

14.0.0-rc3

### Bug summary

I installed Umbraco 14-RC3 an entered my name "Bjarne Fyrstenborg" and email, which generate an avatar with initials "BD", which is strange, because there is no "D" at all 😅

![image](https://github.com/umbraco/Umbraco-CMS/assets/2919859/b3a1dd2b-e23d-42e6-8148-855eac8410b0)

### Steps to reproduce

Create a use with my name an noticed initials of avatar.
It used to show "BF" as initials.

Besides that I can see name of user anywhere. I think it was shows in previous RC versions.

**Comment by bjarnef** [comment]
I created another user using a different email, where the initials are "BF" as expected, so it may possible just be the initial user created from installation which doesn't set name of user.

I don't know how it ended up with "D" in the initials though 🙈

**Comment by Zeegaan** [comment]
Hmmm wierd, I am unable to reproduce this, it generates correctly for me 🙈 
![image](https://github.com/umbraco/Umbraco-CMS/assets/70372949/a4fe3823-da4f-4ab8-b63b-2b2d81aed2b1)

**Comment by bjarnef** [comment]
@Zeegaan did you create the user from backoffice or via installer?

I my test it works correct when created from backoffice, but the initially user created was via installer, which got an weird avatar.
I think it possible not passed in "name" as the name of the user in backoffice was also blank.

**Comment by Zeegaan** [comment]
From the installer 🤔

**Comment by bjarnef** [comment]
I didn't get the issue changing email on user, which also has the name. It was only the user created after filling the name, email from installer.

**Comment by Zeegaan** [comment]
Yea which is why this is so wierd, I have no idea how this could have even happened 🙈 It hasn't really changed since 13 😁

**Comment by bjarnef** [comment]
Then might guess would be it somehow didn't post the name value from frontend to server as it was empty/blank and it somehow pickup the `d` from email domain "bf + domain + .dk"

Otherwise I don't know where it got the `D` from 🤷‍♂️😆

**Comment by bjarnef** [comment]
How does the avatar looks if it fallback on username/email, e.g. "bf + domain + .dk"?

**Comment by Zeegaan** [comment]
Hmm name cannot be null, (tried with spaces also) 😢 
![image](https://github.com/umbraco/Umbraco-CMS/assets/70372949/b069c475-fa0b-4b95-b101-d37cd95b243d)

**Comment by bjarnef** [comment]
Can it be empty or whitespace perhaps?

**Comment by Zeegaan** [comment]
Nope tried that aswell 😢

**Comment by bjarnef** [comment]
I couldn't reproduce this installed v14-RC4, where it created the user with name, email and correct avatar from installer, so I will close this again.
