### ISSUE TITLE
v14-rc3 - Login view - "Enter" do not submit login-form

### ISSUE THREAD

**Issue by mjpraxis** [umbraco/Umbraco-CMS#16274]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

14-rc3

### Bug summary

Entering login credentials you have to click the "Login" button or "tab" + "space/enter" to submit login-form.
 

### Steps to reproduce

Make sure you are logged out

Get to the login form

Enter credentials

Try to submit form by using "Enter"

### Expected result / actual result

Expected: After "Enter" that the login-form would be submitted

Actual result: Nothing happens - you have to click the "Login" button with mouse or tab+enter

**Comment by iOvergaard** [comment]
Hey there and thanks for reporting! It looks this issue has already been reported in #16240 and it will be resolved in RC4 👍
