### ISSUE TITLE
Media Collection: No actions on selected items

### ISSUE THREAD

**Issue by mjpraxis** [umbraco/Umbraco-CMS#16272]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

v14-rc3

### Bug summary

There are no available actions after selecting one or more items in the list of medias

### Steps to reproduce

Make sure to have one or more items (file/image etc) in the media section.

Switch to table view (grid view has the same issue)

Select one or more items.

![image](https://github.com/umbraco/Umbraco-CMS/assets/47383499/efa71cdd-9c82-4a81-9491-b0e21a859510)

### Expected result / actual result

Expected that there would be some actions available to do on the selected items eg "move" or "delete" (trash)

In v13 there are these actions
![image](https://github.com/umbraco/Umbraco-CMS/assets/47383499/f0c9a42c-be9f-4ce4-ab2b-5e7c9de2f942)

---
_This item has been added to our backlog AB#45749_

**Comment by iOvergaard** [comment]
Thanks for testing, @mjpraxis. I can reproduce this in RC4 as well.

**Comment by iOvergaard** [comment]
This will be fixed for 14.2.

**Comment by tbolon** [comment]
Hi @iOvergaard, I am using Umbraco 14.3 and I can still reproduce it:

![image](https://github.com/user-attachments/assets/b20e550a-fa95-4d7a-a380-e81a6c1f9610)

Is it normal?

**Comment by iOvergaard** [comment]
We will take another look at it. Thanks for making us aware of this!

**Comment by leekelleher** [comment]
@mjpraxis @tbolon @MichaelNielsenDK To rule out any misconfiguration, may I ask you to clarify the **Bulk Action Permissions** in the Collection View configuration, (e.g. the "List View - Media" data type)?

Does your configuration have the "Allow bulk move" and "Allow bulk trash" enabled?
![Screenshot 2024-11-11 103530](https://github.com/user-attachments/assets/7a2a0c37-91c5-4d7c-b65f-a3d7b278295c)

**Comment by mjpraxis** [comment]
@leekelleher 

I can in v14.3.1 confirm that "Allow bulk move/trash" works and now the buttons "Trash" and/or "Move" is shown when media items are selected.

I was not aware that such settings existed.

The question is now why could I select items if I was not able to do anything with them 🤔 ?

**Comment by tbolon** [comment]
I can confirm it was the same problem here: I am using a default v14 install and this setting was not checked by default.

**Comment by leekelleher** [comment]
Thanks to all for the clarification, I appreciate it. 🙏 
I'll look into why those permissions are not set on a default/fresh install and get a fix in place.

re: @mjpraxis 
> The question is now why could I select items if I was not able to do anything with them 🤔 ?

That's a good point! Current answer is that the bulk actions on collection views are loaded in upon selection (e.g. when the selection menu bar appears, lazy-loaded). There isn't a pre-check to see if any exist (to enable/disable the selection UI). I'll investigate this scenario and see what we can do to remedy it.

**Comment by iOvergaard** [comment]
Will be fixed in 15.1 with #17593
