### ISSUE TITLE
v14-rc3 - Media section - switch between table/grid view - dropdown do not disappear

### ISSUE THREAD

**Issue by mjpraxis** [umbraco/Umbraco-CMS#16273]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

v14-rc3

### Bug summary

The dropdown with grid/table mode is not hidden after selection.

### Steps to reproduce

Click the button to choose grid/table

Make a choice

You have to click again somewhere beside the dropdown to make it disappear.

![chrome_8p2E66Hhj3](https://github.com/umbraco/Umbraco-CMS/assets/47383499/d230f71a-d852-421d-b713-7ed39446862f)

### Expected result / actual result

Expected the dropdown to disappear after selection of view type

---
_This item has been added to our backlog AB#42172_

**Comment by iOvergaard** [comment]
Thanks for testing, @mjpraxis. I can reproduce this on RC4, but I am not sure if it's intended or not. I will discuss it with the team.
