### ISSUE TITLE
Microsoft.EntityFrameworkCore.Design missing?

### ISSUE THREAD

**Issue by TRexStark** [umbraco/Umbraco-CMS#16278]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

13.3.0

### Bug summary

I wanted to take the leap and try out v13 as most of our sites are still on v10.
It's a fresh install with nothing in it at all, literally just the initial installation of Umbraco.
I published the site to Folder and tried to run in in a live production server but kept getting a 500.30 error.
The logs didn't provide any details besides the application shutting down.
Then I thought I'll just review the publish setting and found an error stating that the startup project doesn't reference the Microsoft.EntityFrameworkCore.Design.

I'm not sure if I'm missing something or if this is a bug.

### Steps to reproduce

Just initiate a clean install of Umbraco v13.3.0 and publish it to a production site.

### Expected result / actual result

Shouldn't all base Microsoft dependencies required be as part of the installation?

**Comment by ronaldbarendse** [comment]
The `Microsoft.EntityFrameworkCore.Design` dependency is a design-time service and shouldn't be deployed with your application, see: https://learn.microsoft.com/en-us/ef/core/cli/services.

Umbraco only references it in the `Umbraco.Web.UI` project (the example/test site used for local CMS development), but that project is not packaged/published:
https://github.com/umbraco/Umbraco-CMS/blob/b0b2b597403bb381c23ff47f2b1ffc8aeaab1dc0/src/Umbraco.Web.UI/Umbraco.Web.UI.csproj#L14-L17

If you add a custom EF Core context and have added this dependency to create your own initial migrations, make sure to add the `PrivateAssets="all"` to the package reference as well!

**Comment by TRexStark** [comment]
Thanks @ronaldbarendse I literally just finished troubleshooting the issue and found the info you provided and realised that I had something messing around with my local setup after all.
