### ISSUE TITLE
v14-RC3 - Can not get from content page to document type

### ISSUE THREAD

**Issue by mjpraxis** [umbraco/Umbraco-CMS#16283]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

14-rc3

### Bug summary

On a Content node the link to the Document Type is not working.

### Steps to reproduce

Create document type and a content node.

Click on the link to the document type on the content node [info] / [general] box.

![image](https://github.com/umbraco/Umbraco-CMS/assets/47383499/7351285e-ce6b-40b8-967c-830e6e249f0d)

### Expected result / actual result

Expected to get to the document type and able to edit the document type

But nothing happens. And there are no errors in the console.

The link to the Template works just fine

**Comment by iOvergaard** [comment]
Thanks for testing, @mjpraxis. I can reproduce this on RC4 as well.

**Comment by leekelleher** [comment]
We have a fix for this in PR https://github.com/umbraco/Umbraco.CMS.Backoffice/pull/1920.
