### ISSUE TITLE
V14-RC3: Recycle Bin updates only after full page reload

### ISSUE THREAD

**Issue by PerplexDaniel** [umbraco/Umbraco-CMS#16291]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

14.0.0-rc3

### Bug summary

When moving a node to the Recycle Bin, the Recycle Bin does not update. Only after a full page reload the Recycle Bin will show the node we just trashed.

### Steps to reproduce

1. Trash a node
![image](https://github.com/umbraco/Umbraco-CMS/assets/24297947/b3474bb0-52fc-4c28-b252-1783fede4be8)
![image](https://github.com/umbraco/Umbraco-CMS/assets/24297947/7a5d7e49-b68c-40b9-9633-a3cde905f1f2)

2. Observe Recycle Bin does not update, but node is removed from the Content tree.
![image](https://github.com/umbraco/Umbraco-CMS/assets/24297947/a42dbbf3-30b2-4df9-b55c-3c729839ac59)

3. Perform a full page reload (F5) and observe the Recycle Bin is now updated:
![image](https://github.com/umbraco/Umbraco-CMS/assets/24297947/8a5b6e27-9588-4f35-9019-f30af6f28c07)

### Expected result / actual result

Recycle Bin should be immediately updated.

**Comment by iOvergaard** [comment]
Thanks for testing, @PerplexDaniel. I can reproduce this in RC4 as well.
