### ISSUE TITLE
V14-RC3: Document Type > History cleanup: `TODO: this ui is not working..` 

### ISSUE THREAD

**Issue by PerplexDaniel** [umbraco/Umbraco-CMS#16295]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

14.0.0-rc3

### Bug summary

The History cleanup in Document Type Settings has a TODO that says 

> TODO: this ui is not working.. 

### Steps to reproduce

1. Go to Settings > Document Types > any document type > Tab Settings and look at the History cleanup group:
![image](https://github.com/umbraco/Umbraco-CMS/assets/24297947/0ba075c3-a2fd-4695-af8f-7b335ad069b6)

### Expected result / actual result

I do not expect any visible `TODO`s in a Release Candidate.

**Comment by iOvergaard** [comment]
Hi @PerplexDaniel, thanks for testing. I can reproduce this on RC4.

**Comment by leekelleher** [comment]
Wired up the UI in PR https://github.com/umbraco/Umbraco.CMS.Backoffice/pull/1915.
