### ISSUE TITLE
V14-RC3: BlockList inline editing mode does not work

### ISSUE THREAD

**Issue by PerplexDaniel** [umbraco/Umbraco-CMS#16298]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

14.0.0-rc3

### Bug summary

BlockList set to inline editing mode does not work at all, no editing UI appears when attempting to edit a block.

### Steps to reproduce

1. Create an Element Type `Block` with a single property `Title` (textstring):
![image](https://github.com/umbraco/Umbraco-CMS/assets/24297947/419c80e9-7436-4bec-866a-ef25dc46ecbc)
2. Create a BlockList for this element type and enable `inline editing mode`:
![image](https://github.com/umbraco/Umbraco-CMS/assets/24297947/5311789f-2f6b-434e-85e5-1d85c2200ea7)
3. Add this data type to your doctype, observe there is no way to edit the block content after adding it. Clicking it toggles the arrow direction but nothing else happens.
![image](https://github.com/umbraco/Umbraco-CMS/assets/24297947/1656b158-4e3d-4b14-bcb4-ac26ba8fbac2)
![image](https://github.com/umbraco/Umbraco-CMS/assets/24297947/301c81f5-7048-48a7-a970-09017e5ecf6b)

### Expected result / actual result

I expect the block opens and shows me the "title" property to edit. 

The only way to edit block content is to Add a new block, in which case a sidebar is opened where you can edit the content:
![image](https://github.com/umbraco/Umbraco-CMS/assets/24297947/ac9ba3a8-374a-43b8-9437-e764aa839d2b)

This is probably another bug though since we enabled "inline editing mode" so I'm not sure why a sidebar is opened. 
Also, is the title supposed to be "BLOCK EDITOR" in all caps there? 

---
_This item has been added to our backlog AB#41771_

**Comment by prjseal** [comment]
Still doesn’t work in RC4

**Comment by Nuklon** [comment]
Also not in final. Did anyone even bother to test V14? It's so buggy.

**Comment by PerplexDaniel** [comment]
I was very shocked to hear 14.0.0 final was released today in this state, not sure why. People unaware of the issues might just upgrade / use v14 since it's now officially the latest stable major.

**Comment by JBoye** [comment]
Still not working in 14.1

**Comment by StudioBravo** [comment]
This is still an issue in 14.2.0-rc2

**Comment by mdeslauriers-sigmund** [comment]
UFM components are rendered but not working
Also mentioned with a screen capture in https://github.com/umbraco/Umbraco.CMS.Backoffice/pull/2215#issuecomment-2407034500
