### ISSUE TITLE
Empty Settings model in configuration when deleting setting block

### ISSUE THREAD

**Issue by bjarnef** [umbraco/Umbraco-CMS#16303]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

13.3.0

### Bug summary

In a project we have a Hero block with a settings block for hero.
We didn't this in a new project, so removed it.

However after deletion, the label in empty in block configuration. In this case Block List, but I guess it is the same for Block Grid.
In would be great the fallback to a label similar to it content element type is deleted, which would show an error at entire block card though.

![image](https://github.com/umbraco/Umbraco-CMS/assets/2919859/c818af28-1730-44a1-b5d1-c96eb8a12abe)

It can just re-use the label "Unavailable ElementType" shown in modal on deletion.

![image](https://github.com/umbraco/Umbraco-CMS/assets/2919859/d28a1bcb-dc19-4718-9328-0f1d97801c36)

Also when settings block is deleted (not exists) there is no need to shown the edit button at settings block.

### Steps to reproduce

- Add a block to Block List or Block Grid with a settings element type.
- Delete settings element type afterwards.
- Notice no label is shown at element type in block configuration.

**Comment by nielslyngsoe** [comment]
Fixed in https://github.com/umbraco/Umbraco-CMS/pull/16328
