### ISSUE TITLE
V14-RC3: Markdown not rendered in field descriptions

### ISSUE THREAD

**Issue by JoJk0** [umbraco/Umbraco-CMS#16306]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

v14.0.0-rc-3

### Bug summary

Markdown is displayed raw in field descriptions instead of being rendered to html.

### Steps to reproduce

Create a property on any document type and choose `Block List` editor. Once the configuration of the editor is open, scroll down to `Single block mode` setting. Observe the description being a raw markdown.

### Expected result / actual result

In v14:
![image](https://github.com/umbraco/Umbraco-CMS/assets/10449993/fb4b8ffd-ea06-4681-8a84-8f09b1e14831)

Case in Umbraco 13:
![image](https://github.com/umbraco/Umbraco-CMS/assets/10449993/d49f6f4e-65a5-4cde-b945-ab9c2b1fbc39)

**Comment by iOvergaard** [comment]
Hello, and thanks for testing. This feature is currently being worked on and can be tracked in https://github.com/umbraco/Umbraco.CMS.Backoffice/pull/1844

It should be ready for either RC4 or RC5 depending on reviews.
