### ISSUE TITLE
Breaking changes from V13 to V14

### ISSUE THREAD

**Issue by cmwalolo** [umbraco/Umbraco-CMS#16316]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

13.1.1

### Bug summary

I'm trying to migrate 13.1.1 to 14. And I'm stuck as all breaking changes are not reported.

### Specifics

For instance one of the breaking functions is : 

`var url = Url.GetUmbracoApiService<CrolowFormApiController>(_controllers, "InsertComment");`

I don't find the correspondency of that function in V14 as some other functions. But I rolled back to V13, I fixed some compilation errors, but I still remained with a bunch of errors.

### Steps to reproduce

Just upgrade an umbraco V13 to V14 :-)

### Expected result / actual result

I have an application using V13.1.1 that compiles correctly, after upgrade and fixing the breaking changes as stated in the docs, I should be able to reuse my app as is !

**Comment by Zeegaan** [comment]
Hmm, this should be in v14, it was reintroduced in this PR: https://github.com/umbraco/Umbraco-CMS/pull/16263
And it's in the sourcecode at least;
![image](https://github.com/umbraco/Umbraco-CMS/assets/70372949/57bf66bc-3b42-460d-9e00-824fa240023e)

Is this on the 14.0.0? 🤔 
And where are you putting your `var url = Url.GetUmbracoApiService<CrolowFormApiController>(_controllers, "InsertComment");`,
is this in a view somewhere or ? 😁 

Some steps to reproduce this from scratch would be very helpful 🙏
