### ISSUE TITLE
Single Language Site - Language Selector shows indicator to select from dropdown but then... only one option

### ISSUE THREAD

**Issue by marcemarc** [umbraco/Umbraco-CMS#16318]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

V14 RC3

### Bug summary

With a site with a single language option
A language selector is presented to the editor - (https://github.com/umbraco/Umbraco-CMS/issues/16176)
The display of the language in this location is 'intentional' and part of the changes in the new Backoffice
I'm thinking from a UX perspective though it's odd to draw the editor to click the caret next to the current language, and then only have the same option to choose from?
![image](https://github.com/umbraco/Umbraco-CMS/assets/260802/c1052082-8337-449a-b338-282e578da44d)

### Steps to reproduce

Create a V14 RC3 site and have a single language
visit the content section
see there is a menu to switch languages and an option to click the dropdown
but when the menu appears there is only one option to choose from

### Expected result / actual result

Could hide the language switcher if there is no language switcher to switch too
or
don't show the dropdown caret? or have a hover on it that says 'this site is a single language site, add a new language to the settings section to enable multi language support?'

**Comment by iOvergaard** [comment]
Hello, we'll be tracking this issue further in #16176 as they seem to describe the same thing.

**Comment by marcemarc** [comment]
doh sorry for the dupe!
