### ISSUE TITLE
Unpublishing a document doesn't update the UI

### ISSUE THREAD

**Issue by marcemarc** [umbraco/Umbraco-CMS#16323]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

V14 RC3

### Bug summary

When you unpublish a published document, you get a big friendly green balloon to say the item has been unpublished, but the UI of the screen isn't updated

The Links section still contains a url to where the content was published (in earlier versions of Umbraco this would update to reflect the new unpublished status)

And in the content tree the tree isn't updated, the content item doesn't become greyed out.

![image](https://github.com/umbraco/Umbraco-CMS/assets/260802/68f69ace-b6a3-40e8-8c72-8b5e84b9a561)

If you then Refresh the browser

The links is updated but it says

The document is published but is not in the cache

so it looks like the 'unpublish instruction' has updated nucache but not updated it's status in the database layer.

Consequently the content item isn't greyed out in the tree.

![image](https://github.com/umbraco/Umbraco-CMS/assets/260802/aad3b451-d3f5-406f-b659-fcc2cfa8a609)

It doesn't look like the Tree shows the unpublished state as greyed out for content items? Here I've added another node and only saved it, so both Home 2 and Home 3 are 'unpublished' in this screenshot

![image](https://github.com/umbraco/Umbraco-CMS/assets/260802/2a166491-4115-46b9-8204-a6ce9266d156)

it's super useful to editors to be able to determine the published/unpublished status of an item from the content tree, without having to click on it, switch to info tab, and then read the message (which currently would also be misleading!)

### Steps to reproduce

Create a Content page at the root of a site and publish it
Create another content page at the root of a site and publish
Create a third content page at root of site but just press save (not publish)

Notice the status of the unpublished third item is not conveyed by the convention of greying out the icon

If you look at the Info tab for the Second Content page, you will see it has a published link
try unpublishing this second content item, you'll see that link remains, and the content item will not be greyed out in the tree
now refresh the browser or click onto your first page and back to the unpublished page
you'll see the message has been updated on the links tab, but it still says the item is published but not in the cache.

### Expected result / actual result

I would expect content items that are unpublished to have a greyed out state for their icons in the content tree
I'd expect when I unpublished a page the UI would be refreshed, and the links section would be updated to indicate the status of the page as unpublished
I'd expect the unpublish task to unpublish the item from nucache, but also update the state of the item in the database to be recorded as unpublished.

**Comment by iOvergaard** [comment]
Thanks for testing, @marcemarc. I can reproduce this in RC4 as well.

**Comment by leekelleher** [comment]
FYI, it was fixed in https://github.com/umbraco/Umbraco.CMS.Backoffice/pull/2492 for 15.1.
