### ISSUE TITLE
Custom Validation messages not displayed to editors

### ISSUE THREAD

**Issue by marcemarc** [umbraco/Umbraco-CMS#16322]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

V14 RC3

### Bug summary

When you create a new property on a composition
and you make it 'mandatory' and put a helpful message to display to the editors
and say you also make it 'validate to a pattern' eg email address, and put in a helpful message to editors...

![image](https://github.com/umbraco/Umbraco-CMS/assets/260802/e702294b-e6cd-439c-9cee-55352de7f5ba)

Then firstly there is no visual indication that the field is mandatory.

![image](https://github.com/umbraco/Umbraco-CMS/assets/260802/6ca05823-f157-4d6d-a75a-9f6f6320f340)

is there normally a little red asterisk?

Anyway, if you press save and publish without filling in the mandatory property then instead of the custom message you get

![image](https://github.com/umbraco/Umbraco-CMS/assets/260802/c4588861-60dd-43e5-8cc7-85be2204bc81)

#validation.invalidEmpty

Which does convey the problem but it would be good if the custom message was used to tailor the response to editors.

for the custom validation text for the regex pattern you get

![image](https://github.com/umbraco/Umbraco-CMS/assets/260802/181ab486-5dbb-48d5-8fa3-0b6c535fd5f9)

interestingly if I go back into the composition Doc Type a second time, and resave it

I do get the text on the validation

![image](https://github.com/umbraco/Umbraco-CMS/assets/260802/7cd9c083-efb8-4dad-935a-901a0d511595)

but not the custom text for the empty email

![image](https://github.com/umbraco/Umbraco-CMS/assets/260802/097dd491-59cb-49fd-8ab5-054d02d2d525)

### Steps to reproduce

Create a DocType Composition with a single text field
make it mandatory
add a custom regex to validate it as an email address
add custom messages to show to the editor when validation fails
Add the composition to a doc type
Go to create some content based on that doc type
leave the mandatory field empty, hit save and publish - see missing custom error message :-(
now part fill in the field with invalid format - see missing custom pattern mismatch error :-(

Now go back into the document type, and edit the property and update the custom text and save.
The mandatory empty situation still doesn't show custom message
but the custom format mis match error is displayed.

### Expected result / actual result

I'd expect on first save and publish of content after the custom messages had been set that they would be displayed to the editor when they didn't provide content for a mandatory field, or did but it didn't match the validation format

**Comment by iOvergaard** [comment]
Thanks for testing. This has been fixed in RC4!

![image](https://github.com/umbraco/Umbraco-CMS/assets/752371/fea87b41-11e6-49e0-ab44-a0dab6b92e95)


![image](https://github.com/umbraco/Umbraco-CMS/assets/752371/db1409fd-22a7-463c-9c1e-5c2a14473c60)
