### ISSUE TITLE
MediaPicker3: "Accepted Types" makes not accepted types act ac folder

### ISSUE THREAD

**Issue by enkelmedia** [umbraco/Umbraco-CMS#16334]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

13.3.1

### Bug summary

I've noticed that MediaPicker3 behaves strangely when limiting the `Accepted types`. A custom media type will start to act as a folder if not accepted for the current data type.

### Specifics

Here is a video that shows the behavior, after limiting the "Accepted types" for the data type the custom file type that we have define, starts to act as a folder. Clicking the icon will navigate "in to" the file as if it was a folder.

![umb13-allowed-media-type-issue](https://github.com/umbraco/Umbraco-CMS/assets/1782524/3dd37f8c-b1a8-4cc2-b29e-0edbf169ab44)

I'm guessing that this is because the `umb-media-grid` thinks that this is a folder, at least it looks like this in the markup:

![image](https://github.com/umbraco/Umbraco-CMS/assets/1782524/adaafc89-974e-4c8d-bf80-1394e7a0fb56)

### Steps to reproduce

Setup a new Umbraco site and:

* Create a new custom file type "My Custom Thing" with one property `Umbraco File` (alias: umbracoFile). Allow at root.
* Create a new custom file type "Custom Video" with one property `Umbraco File` (alias: umbracoFile). Allow at root.
* Go to media and create one of each of the new media types (no need to upload files).
* Add a document type called "Home" and add a property with data type MediaPicker3.
* Open the data type and add "Custom Video" in the "Accepted Types" list.
* Go to the content-section, create a home-document and try to pick the "My Custom Thing", notice that it does not show any "stop"-icon and that it allows to navigate "in to" the "Custom Video" as if it was a folder.

### Expected result / actual result

Media types not included in "Accepted Types" should probably not be clickable if they are not a folder.

Not sure what determines if a media type is a folder but it would probably make sense to either:

* Assume that anything that allows another media below (Allowed child node types) is a folder
* Add some kind of setting (like the "Is Element Type" for documents) but "Is Folder Type" in media.

**Comment by nhudinh0309** [comment]
Hi @enkelmedia 
Thanks for reporting this. I can reproduce it in v13.3.1.
And I am also happy to report this issue has been fixed in v15.1.1, it shows the stop icon for the not accepted types now (see the attachment)

https://github.com/user-attachments/assets/1d98ec10-015c-4572-bc0d-d9dbfb20df3c
