### ISSUE TITLE
V14-RC3 Exernal login providers not showing on login screen

### ISSUE THREAD

**Issue by jbppraxis** [umbraco/Umbraco-CMS#16333]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

V14-RC3

### Bug summary

We have added google as external login provider to V14-RC3 (followed this example https://docs.umbraco.com/umbraco-cms/tutorials/add-google-authentication), but the option is not showing on the login screen.
Tried the same implementation for Umbraco 13 and it works as expected.

### Steps to reproduce

Create umbraco solution 
added google authentication
start and run

**Comment by iOvergaard** [comment]
Hi, and thanks for testing. There are a few more steps to it in Umbraco 14 and the documentation is still being written.

To make the example in V13 work, you need to add a file called `App_Plugins/MyAuthPackage/umbraco-package.json` and let the contents be:

```json
{
  "name": "My Auth Package",
  "allowPublicAccess": true,
  "extensions": [
    {
      "type": "authProvider",
      "alias": "My.AuthProvider.Google",
      "name": "Google Auth Provider",
      "forProviderName": "Umbraco.Google",
      "meta": {
        "label": "Google",
        "defaultView": {
          "icon": "icon-google"
        },
        "linking": {
          "allowManualLinking": true
        }
      }
    }
  ]
}
```

It's important that you let the property `forProviderName` mirror what you have on the server. Then it should show on the login screen.

Manual link and un-link are not available in RC3 but will be available in RC4.
