### ISSUE TITLE
v14-rc4 - No placeholder text for custom validation fields

### ISSUE THREAD

**Issue by KevinJump** [umbraco/Umbraco-CMS#16356]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

v14-rc4

### Bug summary

When adding a new Property to a document type you can select custom validation as a validation option. but this doesn't contain any placeholder text ? 

![image](https://github.com/umbraco/Umbraco-CMS/assets/431231/4ee2e991-fa3b-4b6a-b93e-92260feb0a30)

in v13 this contains some prompts 

![image](https://github.com/umbraco/Umbraco-CMS/assets/431231/8055bcca-6aba-4ac1-a3d6-92510cb16717)

### Steps to reproduce

create a new document type
add a property
select custom validation

### Expected result / actual result

there should be some placeholder text to show the user what to enter.

**Comment by iOvergaard** [comment]
Thanks for testing, @KevinJump. I can confirm this is an issue.
