### ISSUE TITLE
v14-rc4 - Adding a document type composition doesn't refresh the view

### ISSUE THREAD

**Issue by KevinJump** [umbraco/Umbraco-CMS#16353]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

v14-rc4

### Bug summary

If you add a composition to a document type, then the view doesn't update, and you can't see the composition values you have added. 

### Steps to reproduce

- Create a document type with some properties.
- create a new document type 
- add the existing document type as a composition

the view should update so you can see what you have added
- instead, you have to save and reload to see the composition properties.

**Comment by iOvergaard** [comment]
Hi @KevinJump, this seems to have been fixed somewhere along the way in the releases, but we forgot to mark and close this issue. I'll go ahead and do that now, but please feel free to re-open if you still experience issues!
