### ISSUE TITLE
v14-rc4 - custom validation strings are not saved for document type properties

### ISSUE THREAD

**Issue by KevinJump** [umbraco/Umbraco-CMS#16357]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

v14-rc4

### Bug summary

You cannot save a custom reg-ex expression when entering custom validation for a property. 

you can enter a value, but if you save and refresh it's not saved. 

### Steps to reproduce

- create a document type
- add a property
- select custom validation
- add a regex expression and a error message
- save

- reload the page

### Expected result / actual result

the regex expression should be saved.

**Comment by iOvergaard** [comment]
Hi @KevinJump, thanks for testing! As far as I can tell, the value _is_ saved because I can see my validation starts failing afterward, however as you have discovered, the value is not reflected on the frontend upon reload. We will look into it.

**Comment by iOvergaard** [comment]
Hi @KevinJump, this seems to have been fixed somewhere along the way in the releases, but we forgot to mark and close this issue. I'll go ahead and do that now, but please feel free to re-open if you still experience issues!
