### ISSUE TITLE
v14-rc4 - clicking on link to composed document type doesn't work.

### ISSUE THREAD

**Issue by KevinJump** [umbraco/Umbraco-CMS#16354]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

v14-rc4

### Bug summary

When you have a document type that contains a compostion, you get a view showing you the properties

![image](https://github.com/umbraco/Umbraco-CMS/assets/431231/06e14b48-20eb-472b-97cb-b329566e5be2)

Clicking on the link *(Text based content)* doesn't open the composed document type.

### Steps to reproduce

- create a document type that has a composition
- click on the link to the "inherited from"  component.

### Expected result / actual result

this should open up a view of the other component ?

**Comment by iOvergaard** [comment]
Hi @KevinJump, this seems to have been fixed somewhere along the way in the releases, but we forgot to mark and close this issue. I'll go ahead and do that now, but please feel free to re-open if you still experience issues!
