### ISSUE TITLE
v14-rc4 - "Create New" button when in "allowed child nodes types" modal does nothing

### ISSUE THREAD

**Issue by KevinJump** [umbraco/Umbraco-CMS#16358]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

v14-rc4

### Bug summary

when you attempt to add allowed child node types to a document type, the modal has a 'create new' button at the bottom

![image](https://github.com/umbraco/Umbraco-CMS/assets/431231/14c5f040-0ced-45ec-a46b-47b6e3a18b82)

this button does nothing.

### Steps to reproduce

- create a new document type
- save it
- go to allowed child node types (structure)
- click 'choose'
- attempt to 'create new'

### Expected result / actual result

a new document type dialog should open?

**Comment by iOvergaard** [comment]
I believe this button may have been shown in error. In any case, it is not there in 14.1 anymore and I'm not sure it would ever make sense to have there to create a whole document type. There is a similar button on the block list/grid, which is used to create element types, however. That seems to work.

I'll go ahead and close this issue, but feel free to reopen if you believe there is missing functionality 👍
