### ISSUE TITLE
Create matching template missing from the templates section of document type

### ISSUE THREAD

**Issue by poornimanayar** [umbraco/Umbraco-CMS#16361]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

14 RC4

### Bug summary

<img width="941" alt="image" src="https://github.com/umbraco/Umbraco-CMS/assets/3941753/3e6ec5a6-2949-4066-b340-14b38e14b728">

### Steps to reproduce

As above

**Comment by elit0451** [comment]
Hi @poornimanayar 👋 

Thanks for reaching out! It seems like this is no longer an issue in Umbraco v14.1, so I will go ahead and close it 🙂 

![Template](https://github.com/user-attachments/assets/be5a081f-a112-44fb-bfb6-b725a15aa33b)
