### ISSUE TITLE
Tabs from compositions do not have the compositions icon

### ISSUE THREAD

**Issue by poornimanayar** [umbraco/Umbraco-CMS#16366]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

14 RC4

### Bug summary

Pre-v14 the tabs coming in from composition had a icon which was very helpful. Its missing in v14 

v13
<img width="314" alt="image" src="https://github.com/umbraco/Umbraco-CMS/assets/3941753/be6ec9d9-f358-4d57-a561-ad68f43dbaea">

v14
<img width="778" alt="image" src="https://github.com/umbraco/Umbraco-CMS/assets/3941753/38afc4d7-aad4-413d-be7a-835a92f9444e">

### Steps to reproduce

As above

**Comment by iOvergaard** [comment]
Hi @poornimanayar, this seems to have been fixed somewhere along the way in the releases, but we forgot to mark and close this issue. I'll go ahead and do that now, but please feel free to re-open if you still experience issues!
