### ISSUE TITLE
v14-RC4 - Selected validation option does not show on the dropdown correctly

### ISSUE THREAD

**Issue by poornimanayar** [umbraco/Umbraco-CMS#16360]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

14 RC4

### Bug summary

When selecting custom validation -> enter a custom validation as the option, the selected option is not selected in the dropdown

<img width="936" alt="image" src="https://github.com/umbraco/Umbraco-CMS/assets/3941753/bc42c8c4-8d4a-459c-acac-0938fcc1a95a">

### Steps to reproduce

As above

**Comment by elit0451** [comment]
Hi @poornimanayar 👋 

Thanks for reaching out! It seems like this is no longer an issue in Umbraco v14.1, so I will go ahead and close it 🙂 

![Template](https://github.com/user-attachments/assets/be5a081f-a112-44fb-bfb6-b725a15aa33b)

**Comment by elit0451** [comment]
Hi @poornimanayar 👋 

Thanks for reaching out! It seems like this is no longer an issue in Umbraco v14.1, so I will go ahead and close it 🙂 

![Validation](https://github.com/user-attachments/assets/03832d36-fead-47b2-b8df-86314b2d1c5f)
