### ISSUE TITLE
Trying to save a node without name gives "Bad Request" error

### ISSUE THREAD

**Issue by poornimanayar** [umbraco/Umbraco-CMS#16376]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

14 RC4

### Bug summary

There seems to be no client side validation!
v13
<img width="907" alt="image" src="https://github.com/umbraco/Umbraco-CMS/assets/3941753/45f23549-8e24-4605-aa33-3b341bc28e90">

v14
<img width="933" alt="image" src="https://github.com/umbraco/Umbraco-CMS/assets/3941753/124c6e51-5f10-44e7-8a8b-f2241513b873">

### Steps to reproduce

As above

**Comment by NguyenThuyLan** [comment]
Thanks @poornimanayar for reporting this.
I can confirm that this issue is still happening on 14.1.0 and needs to be fixed.
