### ISSUE TITLE
v14.0.0-rc4: Root collection view does not display children

### ISSUE THREAD

**Issue by JoJk0** [umbraco/Umbraco-CMS#16374]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

v14.0.0-rc4

### Bug summary

If a root document has children and is configured as a collection, after adding children it still does not display anything at all:

![image](https://github.com/umbraco/Umbraco-CMS/assets/10449993/ab3ab015-27e9-489c-b87b-c293d87b006e)

### Steps to reproduce

1. Create a document type that can be added from root
2. Set it up as a collection (with pre-defined collection view for content) and allow some other document type to be added as children
3. Create content of that root document type and add some children
4. Observe no children displayed in collection view but displayed on the side panel.

### Expected result / actual result

Have a list of added children

**Comment by iOvergaard** [comment]
Hello @JoJk0, thanks for testing. I can reproduce this and we'll try and get a fix in for RC5.

**Comment by leekelleher** [comment]
The client-side part of this is fixed in https://github.com/umbraco/Umbraco.CMS.Backoffice/pull/1894
_(Pending fix on the server-side for database installation, creation of the data types)._
