### ISSUE TITLE
Rollback button

### ISSUE THREAD

**Issue by poornimanayar** [umbraco/Umbraco-CMS#16370]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

14 RC4

### Bug summary

Its not clear that this is the rollback button
<img width="581" alt="image" src="https://github.com/umbraco/Umbraco-CMS/assets/3941753/6061d62a-4bb1-4e51-b6a3-6d7b21e84d9b">
 

### Steps to reproduce

As above

**Comment by NguyenThuyLan** [comment]
Hi @poornimanayar , I can see on v14.1.0-rc2, they updated rollback button like below.
<img width="1098" alt="image" src="https://github.com/user-attachments/assets/78b16185-e329-4c77-bb32-0ca16ca2ff34">
So I will close this issue 🙂
