### ISSUE TITLE
v14-RC4 Open /umbraco with window.open makes the login thinks it is in modal

### ISSUE THREAD

**Issue by mjpraxis** [umbraco/Umbraco-CMS#16373]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

14-rc4

### Bug summary

Open /umbraco with a javascript window.open to make the backend open in a new tab. Makes the login flow thinks it is in modal-mode.
And ends with 
![image](https://github.com/umbraco/Umbraco-CMS/assets/47383499/b516b72f-271d-4f2f-81b0-40a0572e5728)
But there is no modal window to close. You can close the tab, but then you are not in the Umbraco backend.

Every thing works fine if you after just goes to /umbraco

### Steps to reproduce

Make a button on a template 

<button onclick="window.open('/umbraco');">Backend</button>

Click the button

Enter credentials

### Expected result / actual result

Expected to get into the backend

Actual: got this message 
![image](https://github.com/umbraco/Umbraco-CMS/assets/47383499/b516b72f-271d-4f2f-81b0-40a0572e5728)

**Comment by iOvergaard** [comment]
Great find, @mjpraxis. I can reproduce it and I have proposed a fix that should end up in RC5!
