### ISSUE TITLE
v14.0.0-rc4: Block grid layout: not saving columns

### ISSUE THREAD

**Issue by JoJk0** [umbraco/Umbraco-CMS#16372]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

14.0.0-rc4

### Bug summary

Number of columns are not being saved in block grid editor.

### Steps to reproduce

1. Create Document type with property having block grid and some element types
2. Create some content and some content blocks inside block grid
3. Try to change the number of rows and columns of each block

### Example:

Starting with three blocks as such:

![image](https://github.com/umbraco/Umbraco-CMS/assets/10449993/40387737-928d-4f8b-bedd-bb4ceea22406)

Setting second and third block to have 2 rows and 6 columns:

![image](https://github.com/umbraco/Umbraco-CMS/assets/10449993/3a6e33f2-d1ee-43ec-bf7e-dd7472db969b)

After hitting `Save & Preview` and refreshing the page:

![image](https://github.com/umbraco/Umbraco-CMS/assets/10449993/6b3be382-316a-41a8-b7da-03a1e785a1ae)

Only number of rows are being saved and a change to the number of columns is ignored regardless of the setting.

### Expected result / actual result

Having the number of columns the block takes inside block grid to be saved

**Comment by nielslyngsoe** [comment]
Hi @JoJk0 

Thanks for reporting this, I have just checked your case and can inform that this issue is no longer present in latest version. tested in v.14.1, but I think was most likely already fixed in v.14.0. If not then 14.1 will soon be available. :-)
