### ISSUE TITLE
Label On Top does not work!

### ISSUE THREAD

**Issue by poornimanayar** [umbraco/Umbraco-CMS#16378]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

14 RC4

### Bug summary

A property with label on top selected still shows label by the left

<img width="760" alt="image" src="https://github.com/umbraco/Umbraco-CMS/assets/3941753/5eddae2e-57de-4a75-8995-e4ad8f442b4b">

<img width="191" alt="image" src="https://github.com/umbraco/Umbraco-CMS/assets/3941753/35259349-fad0-4d37-8eb6-c14da6df763c">

<img width="773" alt="image" src="https://github.com/umbraco/Umbraco-CMS/assets/3941753/ca08c07e-fb18-4596-b476-1c7c78210d61">

### Steps to reproduce

As above

**Comment by iOvergaard** [comment]
Hello @poornimanayar and thank you so much for testing. I can reproduce this and have prepared a fix that should end up in RC5.
