### ISSUE TITLE
Preview shows CultureNotFoundException error 

### ISSUE THREAD

**Issue by poornimanayar** [umbraco/Umbraco-CMS#16371]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

14 RC4

### Bug summary

<img width="784" alt="image" src="https://github.com/umbraco/Umbraco-CMS/assets/3941753/a7239298-5b38-4f47-b3de-7aec29fd2f2d">

### Steps to reproduce

as above

**Comment by NguyenThuyLan** [comment]
Yes, I can reproduce this issue.
The error happens on this API:
<img width="1280" alt="image" src="https://github.com/user-attachments/assets/fe210e7e-c252-4a4f-b2c0-9f8aafb48cc4">

**Comment by nielslyngsoe** [comment]
Fixed by https://github.com/umbraco/Umbraco.CMS.Backoffice/pull/2418
