### ISSUE TITLE
Misleading messaging when trying to create dictionary item

### ISSUE THREAD

**Issue by poornimanayar** [umbraco/Umbraco-CMS#16385]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

14 RC4

### Bug summary

<img width="935" alt="image" src="https://github.com/umbraco/Umbraco-CMS/assets/3941753/fdf93fa8-5b48-4189-8fb8-beff8efa6598">

### Steps to reproduce

as above

**Comment by detjonmataj** [comment]
Hi,

I've requested this pr (https://github.com/umbraco/Umbraco.CMS.Backoffice/pull/2257) to fix this issue. Please let me know if anything else is needed. Thanks!
