### ISSUE TITLE
Cannot sort media!

### ISSUE THREAD

**Issue by poornimanayar** [umbraco/Umbraco-CMS#16384]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

14 RC4

### Bug summary

<img width="286" alt="image" src="https://github.com/umbraco/Umbraco-CMS/assets/3941753/fa61578a-3985-40a9-8903-7d79a93b945d">

### Steps to reproduce

as above

**Comment by leekelleher** [comment]
Thanks @poornimanayar! 🙏 This has now been fixed in https://github.com/umbraco/Umbraco.CMS.Backoffice/pull/1901.
