### ISSUE TITLE
Webhook - No client side validation

### ISSUE THREAD

**Issue by poornimanayar** [umbraco/Umbraco-CMS#16388]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

14 RC4

### Bug summary

<img width="785" alt="image" src="https://github.com/umbraco/Umbraco-CMS/assets/3941753/2a0e9baa-e0a4-4ef2-bd20-37f10bbf9fd5">

### Steps to reproduce

as above

**Comment by leekelleher** [comment]
Fixed in https://github.com/umbraco/Umbraco.CMS.Backoffice/pull/2500 for Umbraco 15.0.0-rc3.
