### ISSUE TITLE
Block list - Settings content app shows up for block list types even when settings model is not configured

### ISSUE THREAD

**Issue by poornimanayar** [umbraco/Umbraco-CMS#16382]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

14 RC4

### Bug summary

<img width="934" alt="image" src="https://github.com/umbraco/Umbraco-CMS/assets/3941753/4a196c34-dd4a-4e04-b782-3cc3ec9ab233">

<img width="602" alt="image" src="https://github.com/umbraco/Umbraco-CMS/assets/3941753/4d5c4970-675b-40c5-916a-3825d62fdd19">

<img width="940" alt="image" src="https://github.com/umbraco/Umbraco-CMS/assets/3941753/0a8298b4-0c44-443a-b5aa-b2d56b727d92">

### Steps to reproduce

as above

**Comment by iOvergaard** [comment]
Thanks, @poornimanayar. I can reproduce this as well.
