### ISSUE TITLE
Cannot click the root Content to reveal the dashboards

### ISSUE THREAD

**Issue by poornimanayar** [umbraco/Umbraco-CMS#16387]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

14 RC4

### Bug summary

The root Content is no longer clickable, so I cannot get to the dashboard on the content section if I am on a node. I have to go to another section and come back to content again

<img width="932" alt="image" src="https://github.com/umbraco/Umbraco-CMS/assets/3941753/d7bb291b-9b28-4772-86af-f663aa52b208">

### Steps to reproduce

As above

**Comment by iOvergaard** [comment]
Thanks for testing, @poornimanayar! It looks like this has already been reported in #16232 so I'll go ahead and link this issue to the other. If you think there is more to it, feel free to reopen this issue! #h5yr
