### ISSUE TITLE
Wrong heading for block list Add Content dialog

### ISSUE THREAD

**Issue by poornimanayar** [umbraco/Umbraco-CMS#16381]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

14 RC4

### Bug summary

When trying to add content based on a type using block list , the heading shows " Block list", it used to be the name of the element type pre-v14

<img width="602" alt="image" src="https://github.com/umbraco/Umbraco-CMS/assets/3941753/2e06edb2-1dfd-4354-8b5b-734e0e67b231">

### Steps to reproduce

as above

---
_This item has been added to our backlog AB#43140_

**Comment by iOvergaard** [comment]
Thanks, @poornimanayar. I can reproduce this as well.
