### ISSUE TITLE
Media does not show the media type, id  etc in info content app

### ISSUE THREAD

**Issue by poornimanayar** [umbraco/Umbraco-CMS#16396]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

14 RC4

### Bug summary

<img width="786" alt="image" src="https://github.com/umbraco/Umbraco-CMS/assets/3941753/4fc5e22a-bbe1-4584-8a27-fae0f1852ff9">

### Steps to reproduce

As above

**Comment by leekelleher** [comment]
Thanks for raising this @poornimanayar, it's much appreciated. 🙏 

We've fixed it up in: https://github.com/umbraco/Umbraco.CMS.Backoffice/pull/1904
