### ISSUE TITLE
Misleading message for folder links in media

### ISSUE THREAD

**Issue by poornimanayar** [umbraco/Umbraco-CMS#16395]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

14 RC4

### Bug summary

Media folders used to show "This media item has no link" in the info content app

<img width="581" alt="image" src="https://github.com/umbraco/Umbraco-CMS/assets/3941753/422db3e0-81ca-4dab-86c2-ee6f00478a37">

Its a misleading message in 14
<img width="785" alt="image" src="https://github.com/umbraco/Umbraco-CMS/assets/3941753/c8058272-9ad9-4f0a-ace4-1661ad050a83">

### Steps to reproduce

As above

**Comment by leekelleher** [comment]
It turns out that the "no links" message was referencing the wrong localization key.
I have a patch to correct this: https://github.com/umbraco/Umbraco.CMS.Backoffice/pull/1914.
