### ISSUE TITLE
v14-rc4 Media reference links do not work

### ISSUE THREAD

**Issue by mjpraxis** [umbraco/Umbraco-CMS#16397]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

14-rc4

### Bug summary

References on a Media Item, there are links to nodes where the items is used.
But click on a reference opens a blank side panel with two red toast error messages.

### Steps to reproduce

One Document Type with a Image Media picker property

Add a image to the Media library

Create node in the Content section and select the image
Save the node

Open the image in the Media section

Find the block "Referenced by following items" under [Info]

Click the reference in the list.

![image](https://github.com/umbraco/Umbraco-CMS/assets/47383499/4408be68-0921-4d77-98f0-a4fd38b9705b)

### Expected result / actual result

Expected: The side panel with the node

Actual: Blank side panel with two error messages
![image](https://github.com/umbraco/Umbraco-CMS/assets/47383499/f22cc8ba-8219-44db-8407-9f8ae9ed9aa3)

**Comment by leekelleher** [comment]
Thanks for raising this @mjpraxis, it's much appreciated! 🙏 

We have a fix for this bug in PR https://github.com/umbraco/Umbraco.CMS.Backoffice/pull/1913.
