### ISSUE TITLE
Data types no longer shows references

### ISSUE THREAD

**Issue by poornimanayar** [umbraco/Umbraco-CMS#16390]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

14 RC4

### Bug summary

<img width="786" alt="image" src="https://github.com/umbraco/Umbraco-CMS/assets/3941753/406a336c-a8e2-42f8-ab59-e250c7a7504b">

### Steps to reproduce

As above

**Comment by leekelleher** [comment]
Thanks for raising this @poornimanayar! 🙏 

We have a work-in-progress PR for this: https://github.com/umbraco/Umbraco.CMS.Backoffice/pull/1911.
I'll give a status update in due course.
