### ISSUE TITLE
v14-rc4 - media picker - click on item name does not work correct

### ISSUE THREAD

**Issue by mjpraxis** [umbraco/Umbraco-CMS#16398]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

14-rc4

### Bug summary

In the Media Picker clicking on an item's name results with a strange message "There are no items to show in the list"
![image](https://github.com/umbraco/Umbraco-CMS/assets/47383499/ccd5f317-dc45-4362-8a5d-26eca499e444)

### Steps to reproduce

Create document type with a media picker property

Create a Media item

Create Content and try to pick a Media item by clicking the title/name of the item.

![chrome_cgMQGcRYV1](https://github.com/umbraco/Umbraco-CMS/assets/47383499/51ec9cde-b438-4ab5-aae1-78fb176bd285)

### Expected result / actual result

Expected the media item was selected

Actual: The Media Picker thinks the item is a Folder
Image shows that I click the "Test" item and now the breadcrumb shows that the picker tries to show content of a folder "Test".
![image](https://github.com/umbraco/Umbraco-CMS/assets/47383499/2e129477-487a-4cae-ad32-977d9c2ed03d)

**Comment by iOvergaard** [comment]
Hello, @mjpraxis, and thanks for testing. 

You wrote:

> The Media Picker thinks the item is a Folder

This is, in fact, a valid scenario as you can add media items below other media items if you give them a collection view. The mediapicker does not have any good options to detect this and so is forced to go "into" the item when you click the title.

It goes for all elements currently in the Mediapicker as well as the Media Library:

Clicking the image = Select
Clicking the title = Navigate

We want to eventually build an understanding into the Mediapicker to be able to analyze what counts as a folder and only allow to navigate to those, but for now we have to assume that anything could be a folder. That is obviously confusing!

How can we make that more obvious to the users?

**Comment by mjpraxis** [comment]
Hi @iOvergaard 

It is just because it works perfectly in v13 :-)

I have no solution at the moment how to make it more obvious to the user. It is just very strange that a user ends in this limbo mode.

I have never (in the 15 years using Umbraco) heard or thought of having items created under a image item 😊

**Comment by iOvergaard** [comment]
Good to hear you had a good experience with V13, but I am also sorry to report that V13 is riddled with bugs in that area, especially if you create Folder types of your own, as there are a lot of assumptions built into the system such as the default key for the default Folder type. Currently, we don't assume anything in V14 (for better or for worse) which leads to scenarios like these. We need better UX in this area.

**Comment by mjpraxis** [comment]
@iOvergaard follow up - I have just tested v13 media picker. And there is a problem picking items under for example an image item that allows sub items.

I can see that you have fixed that in v14. But introduced the issue that I have registered in this issue.

**Comment by enkelmedia** [comment]
We have a similar issue in v13 with a custom media type, one thing that came to my mind was:

If the current media type does not allow any other media types as children (in the structure type) than it would not be possible to put something as a child and hence should not be possible to "navigate into".

Or the other way around: If a media type allow other types as children it should probably work as a "folder".

https://github.com/umbraco/Umbraco-CMS/issues/16334

**Comment by madsrasmussen** [comment]
Hi all

We have done a bunch of fixes for the Media Picker for v 15.1 and also addressed the issue with selection. We now have a check that you can only navigate to "folders" or items with children.

You can see all the fixes in this PR: https://github.com/umbraco/Umbraco-CMS/pull/17617

**Comment by enkelmedia** [comment]
Great work @madsrasmussen and the team!
