### ISSUE TITLE
Block grid areas change size when you add another area

### ISSUE THREAD

**Issue by prjseal** [umbraco/Umbraco-CMS#16399]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

v14 rc4

### Bug summary

When you are defining areas in a block grid item, if you resize the areas and then click on add area, the existing areas get resized back to 6x1 like the new one is.

### Specifics

[Screencast from 24-05-24 12:46:34.webm](https://github.com/umbraco/Umbraco-CMS/assets/9142936/62ec126c-1739-498a-86b5-1753a2601ce1)

### Steps to reproduce

Add 2 areas in a block grid item, resize the first 2 to be something like 4x1 then click on add area

### Expected result / actual result

I expected the areas I had added before to stay the same size as what I set them.

Instead they get resized to 6x1 each time.

---
_This item has been added to our backlog AB#41938_

**Comment by iOvergaard** [comment]
Hi @prjseal, thanks for testing this. This has been fixed for 14.1, which will be released later this week.
