### ISSUE TITLE
V14.0.0-RC4: Create action at media tree root does nothing

### ISSUE THREAD

**Issue by bjarnef** [umbraco/Umbraco-CMS#16408]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

v14.0.0-rc4

### Bug summary

Clicking media create action in media root doesn't seem to do anything. I does open create action in content root though.

![image](https://github.com/umbraco/Umbraco-CMS/assets/2919859/15e7380e-5fea-47c1-8323-ef72afeae262)

However it does work via action button and next create action.

![image](https://github.com/umbraco/Umbraco-CMS/assets/2919859/8ac33bb2-7df4-40a2-9ee4-a54f01e21a0b)

![image](https://github.com/umbraco/Umbraco-CMS/assets/2919859/0f82c4eb-bf48-4838-be93-1d8c475ec37a)

### Steps to reproduce

Click create button in media tree root and notice nothing happens.

**Comment by iOvergaard** [comment]
Hi @bjarnef, this seems to have been fixed somewhere along the way in the releases, but we forgot to mark and close this issue. I'll go ahead and do that now, but please feel free to re-open if you still experience issues!
