### ISSUE TITLE
v14-rc4 Media "Folder" does not show list of items

### ISSUE THREAD

**Issue by mjpraxis** [umbraco/Umbraco-CMS#16404]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

v14-rc4

### Bug summary

A simple media tree of "Folders" with items. Should show items (images, folders etc) when clicked in the tree.
But the collection list is empty.
![chrome_ESYaSbdXry](https://github.com/umbraco/Umbraco-CMS/assets/47383499/9c597bda-5e58-44b1-9465-cf86bd306bdc)

I have tried to select "List View - Media" under [Presentation] on the MediaType "Folder" - but it does not have any visual effect.
![image](https://github.com/umbraco/Umbraco-CMS/assets/47383499/d942c22a-a142-4051-9575-ca18d18d1041)

### Steps to reproduce

Create some simple media structor of Folders and add some items.

### Expected result / actual result

Expected to see a list/grid of items in a "Folder"

Actual: Blank / no items.

**Comment by iOvergaard** [comment]
Nice find, @mjpraxis. I believe this is the same issue described in #16374 and we will have a fix ready for RC5. I'll go ahead and close this issue. Feel free to reopen if you believe there is more to it.
