### ISSUE TITLE
Block Grid size options not working properly, unable to select size options easily.

### ISSUE THREAD

**Issue by prjseal** [umbraco/Umbraco-CMS#16402]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

v14 rc4

### Bug summary

When using the size options for a block grid item, you can't select the sizes easily.

### Steps to reproduce

[Screencast from 24-05-24 13:07:58.webm](https://github.com/umbraco/Umbraco-CMS/assets/9142936/8bf9c056-01be-4f9e-813f-361a70a472de)

### Expected result / actual result

I expect to be able to click on the line or the number or the block. I can do neither it is random if it lets me select anything at all.

**Comment by NguyenThuyLan** [comment]
Hi @prjseal , thanks for reporting this issue.
Here is how I chose the size for the block grid. When you click on any number from 1 to 12, it will **pin** the size number in that column ( you can see a small white column below the column number). Therefore, when you are clicking on column 7 but then want to choose number 3, you should unpin column 7 and click to pin column 3.
![image](https://github.com/user-attachments/assets/d743323c-851e-4796-8e7b-e757f1e4f100)
Honestly, at first I found it a bit difficult to use. It should automatically unpin old columns when I want to pin another column.

**Comment by prjseal** [comment]
This seems to be fixed in v14.2.0-rc2

**Comment by nielslyngsoe** [comment]
Thanks @prjseal  Then I will close the issue, please report if there is other problems regarding this.
