### ISSUE TITLE
V14.0.0-RC4: Creating document or media type from tree root doesn't focus name input

### ISSUE THREAD

**Issue by bjarnef** [umbraco/Umbraco-CMS#16411]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

v14.0.0-rc4

### Bug summary

When creating a new document or media type from tree root it doesn't focus name input afterwards.

![image](https://github.com/umbraco/Umbraco-CMS/assets/2919859/8afd952d-a87c-41c3-b073-8530455b2ad4)

I does seem to focus most of the time using the via the actions menu in tree (not direct create action).

![image](https://github.com/umbraco/Umbraco-CMS/assets/2919859/ddda6342-e718-4d82-91bc-9a2d57a5db7e)

It does for member type because there is only one by default.

https://github.com/umbraco/Umbraco-CMS/assets/2919859/4e0720bc-db63-4b9f-8fe8-af595dd694cf

I also noticed I get `null` in URL, e.g. 

`/umbraco/section/settings/workspace/document-type/create/parent/document-type-root/null/null/view/design/root`

`/umbraco/section/settings/workspace/media-type/create/parent/media-type-root/null/view/design/root`

### Steps to reproduce

Create a new document or media type.

---
_This item has been added to our backlog AB#42465_

**Comment by iOvergaard** [comment]
I can reproduce this. It seems to work if you click on the secondary actions menu first and then select "Create" (tested on 14.1), but obviously it's not good enough. We'll look into it.

**Comment by nielslyngsoe** [comment]
I fixed this lately in v.14.2, so I will close this issue :-)
