### ISSUE TITLE
V14.0.0-RC4: Missing placeholder text in input field of new entities

### ISSUE THREAD

**Issue by bjarnef** [umbraco/Umbraco-CMS#16412]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

v14.0.0-rc4

### Bug summary

I think when creating a new entity (content type, data type etc.) it looks a bit empty.

![image](https://github.com/umbraco/Umbraco-CMS/assets/2919859/6919b38c-2096-4858-9c06-45b4e24f1ee6)

I think it would be great to show a placeholder text as in the current backoffice.

![image](https://github.com/umbraco/Umbraco-CMS/assets/2919859/2c2f9211-3b23-4bba-b7da-ad849f8b3ffd)

### Steps to reproduce

Create a new entity (content type, data type etc.) and notice empty placeholder text, which I think could be a help newbies to Umbraco at least.

**Comment by bjarnef** [comment]
I also miss the description field which was useful as it is used in block cards , but it has been reported here https://github.com/umbraco/Umbraco-CMS/issues/16391

**Comment by leekelleher** [comment]
Thanks @bjarnef, I'll close this ticket off, as PR https://github.com/umbraco/Umbraco.CMS.Backoffice/pull/1907 has now been merged in.
