### ISSUE TITLE
V14: Missing validation when creating a member through backoffice

### ISSUE THREAD

**Issue by nikolajlauridsen** [umbraco/Umbraco-CMS#16435]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

14.0-rc5

### Bug summary

When creating a member with a mandatory property the validation is missing.

### Specifics

You are allowed to create a member with a missing mandatory property, the validation is missing.

Ideally, this validation should exist in both the frontend and backend.

### Steps to reproduce

1. Create a custom member type with a mandatory property, for instance text string
2. Try and create the member but don't fill out the mandatory property

### Expected result / actual result

Expected: 
I would expect to get a validation error and not be allowed to create the member

Actual:
I get no validation error and am allowed to create the member.

**Comment by prjseal** [comment]
This is a duplicate. I already raised it a while ago here. #16079

**Comment by nikolajlauridsen** [comment]
Thanks, I must have missed it 🎉 I'll close this one as a dupe then 😄
