### ISSUE TITLE
Stylesheets not working in backoffice

### ISSUE THREAD

**Issue by prjseal** [umbraco/Umbraco-CMS#16431]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

v14 rc4

### Bug summary

When you go in the backoffice and click on one of the stylesheets in the tree view, there is an Api Error and it can't load the contents of the css file.

### Steps to reproduce

Go to Settings section
Scroll down to Templating
Open out the Stylesheets tree
![image](https://github.com/umbraco/Umbraco-CMS/assets/9142936/0efdb930-a5fc-444e-9223-c261faf2a577)
Click on one of the existing stylesheets
You will get an Api Error.
![image](https://github.com/umbraco/Umbraco-CMS/assets/9142936/2a08e4e9-8d4e-420b-a428-27fb316d1127)
You can try to create a stylesheet here too and you get the same error when it tries to load it

### Expected result / actual result

I expect to be able to see the contents of the stylesheet

Instead i get an Api Error.

**Comment by prjseal** [comment]
This may not be an issue, because it works on a fresh install, but on a site i upgraded it doesn't work. So I'm not sure what causes it.

**Comment by iOvergaard** [comment]
Thanks, confirmed. We will get a fix in for RC5.
