### ISSUE TITLE
Slider with range enabled throws JS error on load

### ISSUE THREAD

**Issue by kjac** [umbraco/Umbraco-CMS#16437]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

V14 RC5

### Bug summary

When using a slider datatype with range enabled, the client throws a JS error on load:

![image](https://github.com/umbraco/Umbraco-CMS/assets/7405322/efab27c6-0102-4662-aa35-b6e7d6857d9c)

The slider is fully functional and data saves flawlessly. Seems to be only an issue with the slider initialization at document load.

### Steps to reproduce

1. Create a doctype that contains a range enabled slider property.
2. Create a document based on said doctype.
3. Observe the error in the JS console.

**Comment by leekelleher** [comment]
Fixed in https://github.com/umbraco/Umbraco.CMS.Backoffice/pull/1954.
