### ISSUE TITLE
Mandatory properties do not have an indicator

### ISSUE THREAD

**Issue by kjac** [umbraco/Umbraco-CMS#16441]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

V14 RC5

### Bug summary

Setting "mandatory" for a property on a doctype:

![image](https://github.com/umbraco/Umbraco-CMS/assets/7405322/fdde81ed-38bf-49ce-a5d5-ce1bd7728a34)

...does not seem to yield any indication in the document editor:

![image](https://github.com/umbraco/Umbraco-CMS/assets/7405322/df081e02-29fd-4912-b07c-f71b503c660f)

...which makes it very hard to decipher why the document can't be published:

![image](https://github.com/umbraco/Umbraco-CMS/assets/7405322/936106e5-d40e-417b-b93b-31c9ee417b74)

### Steps to reproduce

1. Create a doctype with a mandatory property.
2. Create a document based on this doctype.
3. Observe missing asterisk or similiar indication of the property being mandatory.

**Comment by nielslyngsoe** [comment]
This is fixed now :-) in 14.2
