### ISSUE TITLE
Possible to delete templates with children

### ISSUE THREAD

**Issue by bergmania** [umbraco/Umbraco-CMS#16443]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

V14 RC5

### Bug summary

It is possible to delete (and I have the option in the client) a template that has children.

![image](https://github.com/umbraco/Umbraco-CMS/assets/1561480/6091333c-9e03-4678-b5d0-cccfe1ca4c2b)

### Steps to reproduce

1. Create a template
1. Create another template below the firstly created
1. Try to delete the template with children

### Expected result / actual result

It should not be possible in the management api and I should not have the option in the client

---
_This item has been added to our backlog AB#44595_

**Comment by leekelleher** [comment]
Fix for the frontend is available in PR: https://github.com/umbraco/Umbraco.CMS.Backoffice/pull/2479.

**Comment by bergmania** [comment]
Fixed in https://github.com/umbraco/Umbraco-CMS/pull/17539
