### ISSUE TITLE
V14: Console error when creating datatype

### ISSUE THREAD

**Issue by Zeegaan** [umbraco/Umbraco-CMS#16448]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

14.0.0

### Bug summary

When you click "Create datatype" it generates a console error: 
![image](https://github.com/umbraco/Umbraco-CMS/assets/70372949/ed46a555-caa1-443d-a5ec-d660b10fa398)

### Steps to reproduce

Click "New datatype" in the Create dataype menu.
It will generate a console error

### Expected result / actual result

To not get a console error 🐛

**Comment by madsrasmussen** [comment]
Fixed by https://github.com/umbraco/Umbraco.CMS.Backoffice/pull/1988
