### ISSUE TITLE
Media picker: "Reset focal point" is visible even if focal points are disabled

### ISSUE THREAD

**Issue by kjac** [umbraco/Umbraco-CMS#16454]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

V14 RC5

### Bug summary

The "Reset focal point" button is visible despite the media picker being configured to _not_ use focal point:

![image](https://github.com/umbraco/Umbraco-CMS/assets/7405322/bd58a844-136b-4de1-9ffe-3eb18e3bd06d)

Configuration:

![image](https://github.com/umbraco/Umbraco-CMS/assets/7405322/ef4bd167-4b6f-4b9e-b9dc-eb7efeaa3004)

### Steps to reproduce

1. Create a doctype with a media picker property where "Enable Focal Point" is not selected.
2. Pick an image.
3. Observe the "Reset focal point" being visible despite the configuration to not use focal point.

**Comment by loivsen** [comment]
Fixed today: https://github.com/umbraco/Umbraco.CMS.Backoffice/pull/1948#event-12969588012
