### ISSUE TITLE
Block Grid: "Allow in root" should be enabled by default

### ISSUE THREAD

**Issue by kjac** [umbraco/Umbraco-CMS#16466]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

V14 RC5

### Bug summary

When configuring a Block Grid, the elements are not allowed in the grid root by default:

![image](https://github.com/umbraco/Umbraco-CMS/assets/7405322/942a1708-26b4-4c7d-a1c8-d407ecbc3829)

This is quite subtle, and if it's not set, the grid won't allow anything at root. The toggle should be enabled by default in my opinion. 

Perhaps "Allow in areas" should be enabled by default too?

### Steps to reproduce

Create a block grid datatype and add some elements to it. Don't toggle anything on the element configuration.

Create a doctype with this datatype, and create a new document based on it. The grid does not allow for anything to be added to it 😢

**Comment by tormnator** [comment]
For what it's worth, in our case most block types are not (and should not be) allowed in root.
