### ISSUE TITLE
Block Grid: "Link to default layout stylesheet" doesn't work

### ISSUE THREAD

**Issue by kjac** [umbraco/Umbraco-CMS#16464]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

V14 RC5

### Bug summary

Clicking the "Link to default layout stylesheet" in the Block Grid configuration doesn't do anything:

![image](https://github.com/umbraco/Umbraco-CMS/assets/7405322/71d3c043-219b-4603-a2ff-786873caaf29)

The link URL is correct, though (`/umbraco/backoffice/assets/css/umbraco-blockgridlayout.css`), and the link can be opened in a new tab just fine.

### Steps to reproduce

1. Create a Block Grid datatype.
2. Click the "Link to default layout stylesheet" at the very bottom of the datatype configuration.
3. Nothing happens.

---
_This item has been added to our backlog AB#42574_

**Comment by nielslyngsoe** [comment]
Fixed by https://github.com/umbraco/Umbraco.CMS.Backoffice/pull/2149
