### ISSUE TITLE
Block List/Grid Issue when removing settingsModel

### ISSUE THREAD

**Issue by andr317c** [umbraco/Umbraco-CMS#16465]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

V14.0.0-rc5

### Bug summary

If I have content using a BlockGridEditor with a Content and Settings model. And then remove the Settingsmodel from the block list/grid I get this error when navigating to my content.

Error:
![image](https://github.com/umbraco/Umbraco-CMS/assets/73799582/592f5c36-66ad-4777-a011-f8e5b0c4a27f)
GIF:
![BlockGridList](https://github.com/umbraco/Umbraco-CMS/assets/73799582/9a892e98-6f8c-4980-a91a-d3a4851515b7)

### Steps to reproduce

1. Create a BlockList or Grid with a block that has both the Content and Settings model.
2. Create Content using this BlockList/Grid
3. Remove the settings model from the BlockList/Grid
4. Navigate to the created content

### Expected result / actual result

Expected: I expected no error

Actual: got an error

---
_This item has been added to our backlog AB#41887_

**Comment by Migaroez** [comment]
The reason for this is empty strings being send for a Guid? property on a serialized value.
When deserializing the configuration during validation, it fails because "" is not a valid notation for Guid?
