### ISSUE TITLE
Block Configuration: Folders can be selected as ElementTypes

### ISSUE THREAD

**Issue by lassefredslund** [umbraco/Umbraco-CMS#16461]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

V14 RC5

### Bug summary

When configuring a Block I can choose a folder. If a folder is chosen I end up with a block that I can't re-configure as the "choose"-button is removed.

### Steps to reproduce

[Bug_FolderSelectionOnBlocks.webm](https://github.com/umbraco/Umbraco-CMS/assets/101121881/dccefe1f-af97-47cc-bc5b-a45b907aef7d)

### Expected result / actual result

Folders should be greyed out and not be selectable from within the configuration of a block.

**Comment by iOvergaard** [comment]
This seems to have been fixed somewhere along the way and can no longer be reproduced :-)
