### ISSUE TITLE
V14: Missing “Compositions” button on Media Type and Member Type

### ISSUE THREAD

**Issue by elit0451** [umbraco/Umbraco-CMS#16473]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

14 RC5

### Bug summary

Only document types have "Compositions" button; It is missing on media and member types.

![Compositions btn](https://github.com/umbraco/Umbraco-CMS/assets/21998037/196898ce-4aec-4d7c-a731-b4bb32f63a64)

### Steps to reproduce

- Go to the Settings section and open a media/member type;
- The "Compositions" button; It is missing.

### Expected result / actual result

Expected: Have the option to add compositions to media types and member types as in v13.
Actual: this is only a possibility for document types.

---
_This item has been added to our backlog AB#41886_

**Comment by iOvergaard** [comment]
Just wanted to add this is the same issue as reported in #16248, but since this is a sprint candidate, I would suggest to close both issues when it is fixed.
