### ISSUE TITLE
V14-RC5: Missing localization for keys in Security health check

### ISSUE THREAD

**Issue by bjarnef** [umbraco/Umbraco-CMS#16479]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

14.0.0-rc5

### Bug summary

I noticed under Security health check it seems to be missing localization for keys, so it just show keys in brackets.

![image](https://github.com/umbraco/Umbraco-CMS/assets/2919859/27103de8-631f-401e-a283-0a7ba7018d4f)

### Steps to reproduce

Go the Settings > Health Check > Security and notice the keys shows instead of actual translations.

- `[clickJackingCheckHeaderNotFound]`
- `[noSniffCheckHeaderNotFound]`
- `[hSTSCheckHeaderNotFoundOnLocalhost]`
- `[xssProtectionCheckHeaderNotFound]`

**Comment by Zeegaan** [comment]
I can reproduce this, thanks for reporting 🐛

**Comment by loivsen** [comment]
As the frontend get these messages directly from the backend API and are not related to the frontend localizations, I changed the area label 😊

**Comment by Zeegaan** [comment]
@loivsen do you know what endpoint it gets these from? Then I will look into fixing this ASAP 👀

**Comment by nikolajlauridsen** [comment]
Fixed in #16612 thanks for reporting 😄
