### ISSUE TITLE
Removing a doctype composition does not update the UI

### ISSUE THREAD

**Issue by kjac** [umbraco/Umbraco-CMS#16470]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

V14 RC5

### Bug summary

When you remove a composition from a composed doctype, the UI does not reflect this change - not even when/after saving. However, a full reload reveals that the composition changes have indeed taken place:

[remove-composition.webm](https://github.com/umbraco/Umbraco-CMS/assets/7405322/c98f1aa6-3fac-4a30-acd7-4394a29ef5d3)

### Steps to reproduce

See video above.

---
_This item has been added to our backlog AB#42576_

**Comment by chris-goehrs** [comment]
Can confirm.  Using 14.0.0.
