### ISSUE TITLE
Strange behavior for composition tabs on doctypes

### ISSUE THREAD

**Issue by kjac** [umbraco/Umbraco-CMS#16471]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

V14 RC5

### Bug summary

Given a doctype which:
- Has a few properties of its own.
- Inherits a tab with a property from a composition.

...adding properties to the inherited tab seems to somehow join the "Generic" and the composition tab together into one:

[composition-tab-behavior.webm](https://github.com/umbraco/Umbraco-CMS/assets/7405322/5463cfc1-b05b-4706-89a0-337e148b32a0)

### Steps to reproduce

See video above.

---
_This item has been added to our backlog AB#42578_

**Comment by nielslyngsoe** [comment]
Fixed in 14.1 :-)
