### ISSUE TITLE
V14-RC5: Uploading folder with images/files doesn't work

### ISSUE THREAD

**Issue by bjarnef** [umbraco/Umbraco-CMS#16484]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

14.0.0-rc5

### Bug summary

In v13 and since v7 I think, it has been possible to upload a folder with images/files, which re-created the folder structure and images/files in media section.

This doesn't seem to work in v14 and nothing happens  when dragging the folder to media section.

### Steps to reproduce

Upload a folder with images/files to media section using drag & drop.

I can upload multiple images/files via drag & drop though and restructure in folder afterwards though. However it was a nice feature and a timesaver for content editors.

---
_This item has been added to our backlog AB#41882_

**Comment by Zeegaan** [comment]
Yep I can produce this, thanks for reporting 🐛

**Comment by iOvergaard** [comment]
Fixed by https://github.com/umbraco/Umbraco.CMS.Backoffice/pull/2116 and will be released in 15.1.
