### ISSUE TITLE
V14-RC5: Media shows 'Data Type' in references

### ISSUE THREAD

**Issue by bjarnef** [umbraco/Umbraco-CMS#16485]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

14.0.0-rc5

### Bug summary

Media shows "Data Type" in references.

![image](https://github.com/umbraco/Umbraco-CMS/assets/2919859/34acf1c0-60c8-40c9-98fe-a851a50b69ce)

In v13 it didn't show the references box if media item didn't have any references.

### Steps to reproduce

Go the a media item and notice "This Data Type" text in references.

**Comment by leekelleher** [comment]
Thanks @bjarnef, good spot! 🕵️ 

The component is using the wrong localization key, it's using `references_DataTypeNoReferences` when it should be using `references_itemHasNoReferences`.
https://github.com/umbraco/Umbraco.CMS.Backoffice/blob/v14.0.0/src/packages/media/media/workspace/views/info/media-workspace-view-info-reference.element.ts#L138
