### ISSUE TITLE
V14-RC5: Don't show language menu when no document types vary by culture

### ISSUE THREAD

**Issue by bjarnef** [umbraco/Umbraco-CMS#16480]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

14.0.0-rc5

### Bug summary

In the currently v13 the language menu isn't shown, when no document types vary by culture.

![image](https://github.com/umbraco/Umbraco-CMS/assets/2919859/d01c0a4d-dba8-449f-8d3e-20544a9d5e53)

![image](https://github.com/umbraco/Umbraco-CMS/assets/2919859/773ec21b-ca2b-44a6-b35e-4576317efb15)

In v14 is shows language menu although no document types vary by culture.

![image](https://github.com/umbraco/Umbraco-CMS/assets/2919859/3abfe552-2dff-45ce-9ea2-7e67ef016ffe)

![image](https://github.com/umbraco/Umbraco-CMS/assets/2919859/d92df1a0-639d-4332-9ab1-89a403069977)

### Steps to reproduce

Create document types which don't vary by culture.
Notice the language menu is shown anyway.

**Comment by iOvergaard** [comment]
Hi @bjarnef and thanks for testing. I believe this has already been reported in #16318 so I will close this issue. If you believe there is more to it, feel free to re-open it.
