### ISSUE TITLE
V14-RC5: Renaming partial view, stylesheet or javascript file shows undefined

### ISSUE THREAD

**Issue by bjarnef** [umbraco/Umbraco-CMS#16488]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

14.0.0-rc5

### Bug summary

When I rename either partial view, stylesheet or javascript file, which is current selected node, it shows undefined after rename.

![image](https://github.com/umbraco/Umbraco-CMS/assets/2919859/2bf82bb2-e9b4-4f4c-8166-d366af8a3193)

![image](https://github.com/umbraco/Umbraco-CMS/assets/2919859/c8bac2cb-5e25-4134-b0fb-9d89cddffefc)

![image](https://github.com/umbraco/Umbraco-CMS/assets/2919859/bfd7dd73-4c4c-4681-9922-53b9a2342f3e)

### Steps to reproduce

Rename a partial view, stylesheet or javascript file from backoffice.

---
_This item has been added to our backlog AB#41880_

**Comment by iOvergaard** [comment]
Thanks for testing this, @bjarnef. I can confirm this is buggy and we need to rectify this.

**Comment by iOvergaard** [comment]
Fix has been merged and will be released in 15.2.
