### ISSUE TITLE
V14-RC5: Accessing member type tree throw console error

### ISSUE THREAD

**Issue by bjarnef** [umbraco/Umbraco-CMS#16482]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

14.0.0-rc5

### Bug summary

When I access member type tree it throw an console error.

`Entity type is not available`

![image](https://github.com/umbraco/Umbraco-CMS/assets/2919859/293317a4-55ba-466b-9f3f-48a07c317be4)

Furthermore it seems the icon doesn't update in header, when I select a color although when I re-open icon picker it shows the color and icon as selected.
It works for document and media type though.

![image](https://github.com/umbraco/Umbraco-CMS/assets/2919859/120b3d8e-ff3d-4ff4-b8af-047a5b7baf8e)

### Steps to reproduce

- Notice console error when accessing member type tree
- Change icon and color of member type and notice it doesn't update in header

**Comment by Zeegaan** [comment]
Heyo 👋 I cannot reproduce this, so it seems like this is fixed 🤔 
Could you try this on 14.0.0? 🐛

**Comment by bjarnef** [comment]
@Zeegaan I will check with v14.0.0 release.. maybe it just sneaked into the RC5 👻🐜🤷‍♂️
