### ISSUE TITLE
Create new content item doesn't work if the current page is in the recycle bin

### ISSUE THREAD

**Issue by prjseal** [umbraco/Umbraco-CMS#16498]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

v14 rc5

### Bug summary

If you have deleted an item and found it in the recycle bin and clicked on it, then decide to create a new content item, the option to save and publish that item does not come up because it thinks you are creating a content item in the context of the recycle bin even though you click the plus next the the Content menu item.

See screen recording

![delete-page-select-it-create-new-page](https://github.com/umbraco/Umbraco-CMS/assets/9142936/f293aeac-f115-4e52-9248-aa95e58061c6)

### Specifics

See above

### Steps to reproduce

See screen recording

### Expected result / actual result

I expect to create a content item from using the plus next to content, regardless of where I am at the time.

With me being on an item that is in the recycle bin at the time, I am unable to save and publish the content item.

---
_This item has been added to our backlog AB#42584_

**Comment by nul800sebastiaan** [comment]
FYI, in v13 there is no create action 

![image](https://github.com/umbraco/Umbraco-CMS/assets/304656/f310aa2b-3efc-4983-9b81-0aab7bb87769)

Ps. @prjseal I know I've encouraged adding gifs for a while, but mp4s are a lot better since we get media controls and don't have to wait for the whole gif to loop to see the little thing that I missed. Screentogif (for example) can export as mp4 as well 💡

**Comment by prjseal** [comment]
@nul800sebastiaan 

> FYI, in v13 there is no create action

I know there is no create menu in the recycle bin in v13. I wasn't trying to create anything inside the recycle bin. 
My current view was a recycle bin item, i was just trying to use the + icon on the Content tree to create a new content item.

Thanks for letting me know about the preference for mp4, will do that from now on.

Paul

**Comment by nul800sebastiaan** [comment]
I know that you know, I'm just trying to clarify for the person who will work on this 😉

**Comment by leekelleher** [comment]
Fixed in https://github.com/umbraco/Umbraco.CMS.Backoffice/pull/2177, for 14.2.0
