### ISSUE TITLE
Nodes does not show as published in the tree

### ISSUE THREAD

**Issue by prjseal** [umbraco/Umbraco-CMS#16494]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

v14 rc5

### Bug summary

When you create a child page under a parent page and you name it and press save and publish, it doesn't update in the tree to show it is published. It looks like it is slightly greyed out, like unpublished.

![save-and-publish-new-page](https://github.com/umbraco/Umbraco-CMS/assets/9142936/af0c4af8-d506-48ef-824c-5160506f721a)

### Steps to reproduce

See above

### Expected result / actual result

The node in the tree should show with the darker text like it is for published items

You have to refresh the page to see it update correctly

---
_This item has been added to our backlog AB#42582_

**Comment by Zeegaan** [comment]
This also happens to parent-nodes, as noted in https://github.com/umbraco/Umbraco-CMS/issues/16494 😁

**Comment by madsrasmussen** [comment]
Fixed by https://github.com/umbraco/Umbraco.CMS.Backoffice/pull/2066
