### ISSUE TITLE
V14-RC5: Overflow in overlay when inserting field value

### ISSUE THREAD

**Issue by bjarnef** [umbraco/Umbraco-CMS#16491]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

14.0.0-rc5

### Bug summary

When inserting field value the code snippet may cause overflow.

![image](https://github.com/umbraco/Umbraco-CMS/assets/2919859/efce67b2-379c-43f8-a449-4e935026dbf6)

In v13 the code snippet component itself handled scrollbar on overflow.

### Steps to reproduce

Insert field value, select recursive and default value to make code snippet long enough.

**Comment by elit0451** [comment]
Thanks for reporting this @bjarnef! 

I was able to reproduce this in 14.0.0. We will have a look 🙂
