### ISSUE TITLE
Access nodes for an user are highlighed as links

### ISSUE THREAD

**Issue by andr317c** [umbraco/Umbraco-CMS#16490]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

V14.0.0-rc5

### Bug summary

The Access nodes for a user are highlighted as links, if I click the "link" for an access node, nothing happens. In version 13 the access nodes were not highlighted as links. 
See GIF:
![AccessNode](https://github.com/umbraco/Umbraco-CMS/assets/73799582/9a7dd065-4c8e-43f4-9d98-31861dc4446d)

### Steps to reproduce

1. Go into a user
2. Hover over the access nodes
3. Click a node, nothing happens

### Expected result / actual result

Expected: I would expect to be redirected to the specific node I clicked on since it is highlighted as a link. Otherwise, it should not be highlighted.

Actual: It is highlighted, but nothing happens when I click on an access node

**Comment by bjarnef** [comment]
Another example of this is member group selected on a member.

In  that specific case it could however open member group in infinite editing.

![image](https://github.com/umbraco/Umbraco-CMS/assets/2919859/bb7eb7ad-6a59-4371-bb24-1d367eda09b4)

**Comment by madsrasmussen** [comment]
Fixed by https://github.com/umbraco/Umbraco.CMS.Backoffice/pull/2000
