### ISSUE TITLE
Space bar doesn't open the option to select property editor

### ISSUE THREAD

**Issue by prjseal** [umbraco/Umbraco-CMS#16497]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

v14 rc5

### Bug summary

When adding properties to a document type we use tab and the space bar to go through and set the options. But in this version, when you press the space bar when the focus is on the `Select Property Editor` it does nothing. However the enter key does work. Yet the space bar can be used to turn on or off a toggle and it does open a dropdown and it does work on the close and save buttons so it should work on the Select Property Editor too.

![image](https://github.com/umbraco/Umbraco-CMS/assets/9142936/c19b2265-64fb-413d-9397-ca057e9c3d84)

### Steps to reproduce

Add a property to a document type, try to use the space bar to select a property editor

### Expected result / actual result

I expected to be able to use the space bar to select a property editor, but instead it does nothing.

**Comment by Zeegaan** [comment]
I can reproduce this, we will have a look! Thanks for reporting 🐛

**Comment by prjseal** [comment]
After discussing this with @nielslyngsoe and @madsrasmussen we have realised that the reason it doesn't work is because it is a link and not a button and you are supposed to use the enter key rather than a space bar. You can test this on any other website and see that you can't use space on a link.
