### ISSUE TITLE
Property description styling is broken

### ISSUE THREAD

**Issue by prjseal** [umbraco/Umbraco-CMS#16499]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

v14 rc5

### Bug summary

In Umbraco we are able to add some simple styling to the property description.

As per the [documentation](https://docs.umbraco.com/umbraco-cms/fundamentals/data/defining-content#property-descriptions) and this [YouTube video](https://www.youtube.com/watch?v=QAZ8ZZerbZQ)

If we add the following in the description of a property:

```md
This is **bold**
This is *italic*
[This is an absolute link](https://google.com)
[This is a relative link](/umbraco#/media)
--
![Image alt text](https://media.giphy.com/media/bezxCUK2D2TuBCJ7r5/giphy.gif)
```

It should come out looking like this, with the gif being revealed by a read more link and a close link.

![image](https://github.com/umbraco/Umbraco-CMS/assets/9142936/a2bccf5d-3407-45e1-9d47-92620ac894e1)

Instead it comes out looking like this where the font weight is incorrect, the read more doesn't work and the image overflows the width.

![image](https://github.com/umbraco/Umbraco-CMS/assets/9142936/e41efb31-084b-49b9-8147-d26935f24ffb)

### Specifics

See above

### Steps to reproduce

See above

### Expected result / actual result

I expect the styling to be similar and the read more functionality to work

**Comment by iOvergaard** [comment]
Hey @prjseal, thanks for testing. We wondered if we should set a max-width on all images within property descriptions, but it seemed dangerous to do so. It seems you would expect exactly that to happen here. I think we need to look more into it and see, as putting markdown into property descriptions is allowing for all sorts of things to be inserted. The old backoffice only allowed a subset of Markdown in this area, and apparently had some custom functionality such as "Read more".

**Comment by leekelleher** [comment]
To note the `--`, is Markdown syntax for a heading, ([albeit alternative syntax to `#`](https://www.markdownguide.org/basic-syntax/#alternate-syntax)), so technically it shouldn't have been used as the syntax to render a "read more" toggle in previous Umbraco versions. We'll look for an alternative syntax for a collapsible (read more) description, and update the docs accordingly.

In the meantime, it's now possible to have sanitized HTML inside the description, so markup like `<details><summary>` could be used.

**Comment by leekelleher** [comment]
I've added a fix for the image width, https://github.com/umbraco/Umbraco.CMS.Backoffice/pull/1961.

We'll be investigating whether we'll still support the "read more" feature, or if we encourage the use of `<details>` as an alternative.
