### ISSUE TITLE
V14-RC5: Adding a tab then removing it leaves broken UI in place to add properties

### ISSUE THREAD

**Issue by stevetemple** [umbraco/Umbraco-CMS#16501]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

14-RC5

### Bug summary

If you create a new doc type, then go to add tab, delete the new tab, the UI is left in place for adding properties to the tab. But it doesn't work because the tab has been deleted.

### Steps to reproduce

1. Create a new doc type
2. Add a tab
3. Delete the added tab
4. Click add property
5. Add property
6. The property isn't added and it shows 2 "Created" success styled messages despite this

https://github.com/umbraco/Umbraco-CMS/assets/113788/91825786-9b7f-4320-baf8-3284edaa48dd

### Expected result / actual result

I'd expect the Add Property UI that appeared when the tab was added to be removed when the tab is deleted

---
_This item has been added to our backlog AB#41879_

**Comment by nielslyngsoe** [comment]
Hi @stevetemple thanks for reporting this. This has already been fixed, as I cant replicate it, (in 14.1 if i'm not mistaken). Therefore I'm closing this issue :-)
