### ISSUE TITLE
V14-RC5: Properties with same alias as doctype fail to be created

### ISSUE THREAD

**Issue by stevetemple** [umbraco/Umbraco-CMS#16502]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

14-RC5

### Bug summary

You can't create a property on a doctype with the same alias as the doctype. 

I don't know if that is intentional, If so, the error message could be better at describing the issue. Took me a little while of experimentation to figure out what was invalid about my aliases.

### Steps to reproduce

I'm creating a new doctype with the name "test", It get's the alias "test", I tried to add a property to that doctype called "test" it also gets the alias "test". When I then try and save the doctype I get a message "Invalid property type alias, One or more property type aliases are invalid

https://github.com/umbraco/Umbraco-CMS/assets/113788/37f62157-c2f9-473a-8fd0-276bef8e02ef

### Expected result / actual result

I'd expect to be able to create a property with the same alias as a doctype. 

Of if that is not allowed to get an error message making it clear that's what the issue is

**Comment by Zeegaan** [comment]
Yea this is not an allowed use case either in v13:

**Comment by Zeegaan** [comment]
I've made a PR, adding a clearer error: 
![image](https://github.com/umbraco/Umbraco-CMS/assets/70372949/65c1a5d2-6055-4b1e-bb90-d1d2c5ef5130)

**Comment by nikolajlauridsen** [comment]
Fixed in #16530 😄
