### ISSUE TITLE
v14-RC5 errormessages showed in raw text format

### ISSUE THREAD

**Issue by mjpraxis** [umbraco/Umbraco-CMS#16504]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

14-rc5

### Bug summary

For example setting a minimum of blocks allowed in a grid area
![image](https://github.com/umbraco/Umbraco-CMS/assets/47383499/cceac109-50c2-4e73-aace-f5b7ed864414)

And if the user then only adds the layout in the content. But do not add any content in the area. And tries to publish the node. Then the errormessage is showed in raw text not rendered as HTML.
![image](https://github.com/umbraco/Umbraco-CMS/assets/47383499/96e4cf29-072d-4c3a-a41f-9e10dbb9b491)

### Steps to reproduce

Create a Block grid datatype and set the minimum required numbers of blocks to 1

Create content node and do NOT add any blocks to the content.

Publish node and see the errormessage.

### Expected result / actual result

Expected for example "Minimum 1 entries, requires **1** more."

Actual result: `"Minimum 1 entries, requires <strong>1</strong> more."`

---
_This item has been added to our backlog AB#41878_

**Comment by Zeegaan** [comment]
I can reproduce this 😁 Thanks for reporting 🐛
