### ISSUE TITLE
[v14] Client does not show time for user last login

### ISSUE THREAD

**Issue by Migaroez** [umbraco/Umbraco-CMS#16511]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

v14.0.0

### Bug summary

Should the Last login not also show the time
![image](https://github.com/umbraco/Umbraco-CMS/assets/6025797/d4a28cfa-2267-4094-b3cf-6c5afd96ec07)

### Specifics

Comment from @nielslyngsoe: it should ideally depend on how long time ago that login was, this component was described for this case
https://github.com/umbraco/Umbraco.UI/issues/143 

### Steps to reproduce

- Create a user
- Log in with the user
- Check the user card

### Expected result / actual result

Time to be shown on the user card

**Comment by EmanuelGustafzon** [comment]
I would like to work on this one!

**Comment by Migaroez** [comment]
Hey @EmanuelGustafzon, hope you enjoy the challenge and feel free to ask for help when needed #h5yr!

**Comment by EmanuelGustafzon** [comment]
Thank you @Migaroez!

**Comment by EmanuelGustafzon** [comment]
@Migaroez Hi, I just created a pull request, I hope I did it correctly, I got a bit confused because it's a sub-repository.

**Comment by nielslyngsoe** [comment]
This has been fixed as of https://github.com/umbraco/Umbraco.CMS.Backoffice/pull/2205
