### ISSUE TITLE
[V14] RTE in classic mode shouldn't hide the separator line in larger screens

### ISSUE THREAD

**Issue by Nuklon** [umbraco/Umbraco-CMS#16518]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

14

### Bug summary

This is OK:
![image](https://github.com/umbraco/Umbraco-CMS/assets/23340481/9c9920cf-87c4-445c-9144-54797a2c201b)
Now you can see where you can start editing.

With a large window size this line is missing:
![image](https://github.com/umbraco/Umbraco-CMS/assets/23340481/fe1b8ec8-1175-4b5f-be01-272c91b83d27)

### Steps to reproduce

Use RTE in classic mode.

**Comment by Zeegaan** [comment]
I can reproduce this 😁 even on smaller screen, the bottom line is still missing 😢 
![image](https://github.com/umbraco/Umbraco-CMS/assets/70372949/babc9dc4-27be-4dfb-b809-d45b50d0cc67)

**Comment by iOvergaard** [comment]
@Zeegaan The box-shadow is being hidden, but I fixed that with https://github.com/umbraco/Umbraco.CMS.Backoffice/pull/1979

@Nuklon Thanks for testing. TinyMCE is responsive and in my tests, I was able to set a max width in the data type configuration to prevent TinyMce from stretching its toolbar into one line. Would you verify that?

![image](https://github.com/umbraco/Umbraco-CMS/assets/752371/51b4626c-1a25-4e5d-8a69-1bbbd32df17c)

**Comment by iOvergaard** [comment]
@Nuklon Yes, the line appears if you make the screen smaller, but it also depends on how many items you have in the toolbar of course.
