### ISSUE TITLE
[V14] UI does not remember tree position when swapping sections

### ISSUE THREAD

**Issue by Migaroez** [umbraco/Umbraco-CMS#16513]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

14.0.0

### Bug summary

When jumping from one section to another, trees always start unfolded. Would be really nice, if it could “remember” how a section was left like in the old backoffice.

### Steps to reproduce

- Unfold a nested tree in a section
- Go to another section
- Come back

### Expected result / actual result

Tree is still unfolded after returning to a/the previous section.

**Comment by philipdanielhayton** [comment]
+1

**Comment by madsrasmussen** [comment]
Duplicate of https://github.com/umbraco/Umbraco-CMS/issues/17076
