### ISSUE TITLE
[V14] Checkbox list causes dots everywhere

### ISSUE THREAD

**Issue by Nuklon** [umbraco/Umbraco-CMS#16515]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

14

### Bug summary

Add a predefined checkbox list with say 6 values in them. There's are dots added on the page for each (fixed position):

![image](https://github.com/umbraco/Umbraco-CMS/assets/23340481/092393b5-9d4f-4568-964b-fb71bf6fd185)

### Steps to reproduce

See above.

### Expected result / actual result

NO DOTS

**Comment by madsrasmussen** [comment]
Hi @Nuklon 

Thanks for the bug report. I can't reproduce what you describe in the issue. I have attached a screenshot with a checkbox list with 6 options. 

Feel free to reopen the issue if you can provide more details on how to reproduce it.

<img width="1278" alt="Screenshot 2024-06-05 at 15 29 52" src="https://github.com/umbraco/Umbraco-CMS/assets/6078361/6c1be0c1-f943-41ef-8751-ca89e5be9037">

**Comment by Nuklon** [comment]
> Hi @Nuklon
> 
> Thanks for the bug report. I can't reproduce what you describe in the issue. I have attached a screenshot with a checkbox list with 6 options.
> 
> Feel free to reopen the issue if you can provide more details on how to reproduce it.
> 
> <img alt="Screenshot 2024-06-05 at 15 29 52" width="1278" src="https://private-user-images.githubusercontent.com/6078361/336857214-6c1be0c1-f943-41ef-8751-ca89e5be9037.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc2MTExNDYsIm5iZiI6MTcxNzYxMDg0NiwicGF0aCI6Ii82MDc4MzYxLzMzNjg1NzIxNC02YzFiZTBjMS1mOTQzLTQxZWYtODc1MS1jYTg5ZTViZTkwMzcucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDYwNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA2MDVUMTgwNzI2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YWYwNGZkOTg0YmYxNWQ3Yzg1YzU0YjNmNTVlMGRlZTM3Zjk0NjNmYWQ2YTI0Y2I1NTkzM2VhNGQxMzZiMzdjOSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.BIUEdywynlLav4Th2wo-sx-AXwhAyQwwYCuSEsRemig">

You need to add more elements to the document (I recommend adding several large elements before the checkbox list and after), and then scroll down. You can see the dots behind the other elements as on my screenshot. In Firefox they always show up.

**Comment by madsrasmussen** [comment]
Thanks for the extra details. For some reason, I can't reproduce in Chrome but I get the bug in Firefox.

I will reopen the issue.
