### ISSUE TITLE
Umbraco CMS Build Documentation has an issue with the command related to "git submodule update"

### ISSUE THREAD

**Issue by BuddhiEash** [umbraco/Umbraco-CMS#16526]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

contrib

### Bug summary

Tried to build from the source code of 'contrib' branch.

As per the build guide - [https://github.com/umbraco/Umbraco-CMS/blob/41dddee620bc7a7c5c26d15550ee5f11111bf45c/.github/BUILD.md#getting-started](url) tried `git submodule init` and then `git submodule update` commands.

Figured it out `git submodule update` command doesn't clone the submodule properly if an older version of git is installed.

If this is verified as an issue, I'm happy to contribute the change to the documentation.

### Specifics

Fix - `git submodule update --init` works with any of the git versions whether it's older or the latest version, and no need to run 2 commands such as `git submodule init` and then `git submodule update`. Just executing `git submodule update --init` will be fine.

Therefore, the documentation's "Getting Started:" section's following line should be updated from:

"Execute `git submodule init` and then `git submodule update` to get the files into Umbraco.Web.UI.Client project"

To:

"Execute `git submodule update --init` to get the files into Umbraco.Web.UI.Client project"

### Steps to reproduce

Try with an older git version. 
In my case, it was git version - 2.32.0.windows.2

### Expected result / actual result

Expected result - Submodule path 'src/Umbraco.Web.UI.Client' should be checked out successfully.

Actual result - 

![Screenshot 2024-05-31 115849](https://github.com/umbraco/Umbraco-CMS/assets/3594697/7a0441bc-865d-4238-8092-dcf88eff297c)

**Comment by iOvergaard** [comment]
Hello @BuddhiEash, thanks so much for testing this out. Feel free to update the documentation! #h5yr

**Comment by BuddhiEash** [comment]
Hi @iOvergaard no worries. Sure, I'll update the documentation and create a PR.
Thanks!

**Comment by nul800sebastiaan** [comment]
FYI @BuddhiEash there is no need to create an issue if you're creating a PR anyway. I recommend only creating an issue before if you need to discuss some things before you create a PR. 
Please also remember to link the PR to the issue if you do create both. That way, we know to close the issue when the PR is merged. 
In this case, I remembered so the PR is here and it was just merged: #16528

**Comment by BuddhiEash** [comment]
Hi @nul800sebastiaan - Duly noted with thanks
