### ISSUE TITLE
User Profile doesn't pick up Gravatar image

### ISSUE THREAD

**Issue by craigs100** [umbraco/Umbraco-CMS#16520]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

V14.0.0

### Bug summary

User profile is not picking up User's image automatically from gravatar.com as previous versions did.

### Specifics

When logging in or viewing a user profile the placeholder roundel is not being replaced with a gravatar image where possible.

### Steps to reproduce

Install Umbraco V14.0.0 and create a user with an email address that is registered with gravatar.com and has a photo on gravatar. 
Login to Umbraco with that user. Note the small roundel at the top right of the menu bar does not show the gravatar image, but merely a coloured circle with the users initials.

If you view the user profile, the "Photo" section is the same as the menu bar and does not show the gravatar image

### Expected result / actual result

Expected the gravatar image to replace the roundels in the menu bar and user profile.

**Comment by nul800sebastiaan** [comment]
I just want to chip in here and say that I love the feature that Gravatar provider, but it's also a privacy risk and had a massive leak of all of their data a few years ago. https://monitor.mozilla.org/breach-details/Gravatar 

If any code is added, for it, I would want it to be opt-in.

**Comment by craigs100** [comment]
A checkbox by the photo facility in the user profile then?  But if it's that much of a security risk maybe it should be taken out of the current LTS?  Personally I'm quite happy with it as it is in V13. Others may disagree.

**Comment by nul800sebastiaan** [comment]
I actually tend to agree, I didn't realize it was still in there! But that's a breaking change, which should be done in majors.
