### ISSUE TITLE
V14 Can't navigate from User to User Group

### ISSUE THREAD

**Issue by enkelmedia** [umbraco/Umbraco-CMS#16522]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

v14.0.0

### Bug summary

Clicking the User Group name will not navigate to the User Group

![image](https://github.com/umbraco/Umbraco-CMS/assets/1782524/6de71ab1-7f96-4874-9ee1-e3d8aff0447f)

### Steps to reproduce

Go to a user, click on a User Group

**Comment by nul800sebastiaan** [comment]
Just as a bit of additional info: today I learned... That we had an edit button for that in previous versions! (I didn't know haha) 

![image](https://github.com/umbraco/Umbraco-CMS/assets/304656/8a9b2b71-bd21-4d3e-9f32-5db6005615d4)

**Comment by Zeegaan** [comment]
Thanks for reporting this, I can reproduce 🐛 
As Sebastiaan mentions, you were not able to click it in previous versions, but there was an edit button.
I will leave it up to the frontend team on how to handle this 😁
