### ISSUE TITLE
[V14] Media upload to folder doesn't work

### ISSUE THREAD

**Issue by remkovb** [umbraco/Umbraco-CMS#16524]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

14.0.0

### Bug summary

When trying to upload a file directly to a folder, the file gets uploaded to media root instead. Also the media tree isn't refreshed after upload, so you should manually refresh to see this result.

### Steps to reproduce

1. Go to media section
2. Create a folder
3. Navigate to folder
4. Drag/drop a file to folder
5. Nothing seem to happen, so refresh browser and see the result

### Expected result / actual result

Expected result is file being uploaded to particular folder. Also it is expected that file to be shown in tree after upload so auto refresh of media tree. Instead of that the actual result is the file being uploaded to media root and no refresh of media tree.

**Comment by Zeegaan** [comment]
I can certainly reproduce this, thanks for reporting 🐛
