### ISSUE TITLE
[v14] Backoffice assets are not bundled and minified?

### ISSUE THREAD

**Issue by PerplexDaniel** [umbraco/Umbraco-CMS#16537]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

14.0.0

### Bug summary

I hope I am wrong but it looks like the v14 Backoffice assets (.js / .css files) are not bundled and minified like in earlier versions but are individually loaded instead. This results in 2000+ files being loaded, the vast majority of which are JavaScript files. Not only that, the files are not minified either so way more data is transferred than necessary.

![image](https://github.com/umbraco/Umbraco-CMS/assets/24297947/e3ca8c14-befa-4b1f-9c04-315b6e2161eb)

Note I have set Debug to `false` in appsettings.Development.json but this does not seem to have any effect unlike in < v14 versions. I have also tested setting `ASPNETCORE_ENVIRONMENT` to `Production` but this did not change the behavior either.

```json
"Umbraco": {
    "CMS": {
      "Hosting": {
        "Debug": false
      }
    }
  }
```

### Steps to reproduce

1. Open v14 Backoffice
2. Open Developer Tools > Network tab
3. Reload page
4. Observe 2k+ unminified files are loaded

### Expected result / actual result

I expected a minimal amount of bundled & minified JavaScript to be loaded but instead 2000 unminified JavaScript files are loaded.

**Comment by madsrasmussen** [comment]
Hi @PerplexDaniel 

Thanks for the report. This is on our TODO list to get fixed 👍
