### ISSUE TITLE
List view's move and copy don't respect a users content start nodes

### ISSUE THREAD

**Issue by merchant-jack** [umbraco/Umbraco-CMS#16541]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

13.3.2

### Bug summary

When logged in the CMS back office as a User with 'Content start nodes' set
and using the copy or move dialog on the ListView
the dialog will show nodes outside of their access

### Specifics

This seems to only be the case with the ListView. If you use the move and copy dialog from the right click menu or 'Actions' dropdown (when not in ListView mode) it will respect the user's permissions.

### Steps to reproduce

If you set up a basic tree of a simple doc type

![image](https://github.com/umbraco/Umbraco-CMS/assets/171557776/743f8ff9-4588-48f3-b2dc-a6c4c1d654e2)

And with a user, only allow access to one of the branches

![image](https://github.com/umbraco/Umbraco-CMS/assets/171557776/9f6df647-2d6c-4663-aea7-2a0f68b3f683)

That user can correctly see that branch correctly in the content tree

![image](https://github.com/umbraco/Umbraco-CMS/assets/171557776/c919e949-57af-4766-bf61-867bea36e385)

If they use the move or copy dialog it shows the correct nodes

![image](https://github.com/umbraco/Umbraco-CMS/assets/171557776/d0b51347-5457-4f06-bd10-7c8ecf50fcba)

But if I switch the doctype to use a ListView and try to use the move or copy dialog again, it will let me see other nodes in the tree outside of my permissions

![image](https://github.com/umbraco/Umbraco-CMS/assets/171557776/e18b5002-bd55-4ffc-b10d-df53aac9d00f)

If I press the 'back' link at the top

![image](https://github.com/umbraco/Umbraco-CMS/assets/171557776/60f08227-aae8-4ad7-9e7e-27a4528352cd)

It does then show the correct tree - so seems like it's opening in at the wrong place in the hierarchy

![image](https://github.com/umbraco/Umbraco-CMS/assets/171557776/4128ad6a-f723-406c-81f6-5d4030ff32a4)

### Expected result / actual result

It should only show the allowed nodes of a user 
when using the copy and move dialogs on a ListView

**Comment by elit0451** [comment]
Hi there @merchant-jack 👋 
Thanks for reaching out!

I could indeed reproduce this after I made the ListView switch on the document type. If I created the tree structure with ListView turned on from the beginning, I didn't see the same behaviour.

**Comment by bergmania** [comment]
Fixed by https://github.com/umbraco/Umbraco-CMS/pull/16722

**Comment by merchant-jack** [comment]
Thanks @elit0451 & @bergmania!
