### ISSUE TITLE
[Umbraco 8 & SQL Server 2022] Clean Umbraco 8 installation throws SqlException when trying to rollback content to a previous version

### ISSUE THREAD

**Issue by bifort** [umbraco/Umbraco-CMS#16543]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

8.18.14

### Bug summary

This happens only when you use Umbraco 8 with SQL Server 2022.
On Umbraco 8 with SQL Server 2019 works fine.

When trying to rollback your content to a previous version the following error is being thrown:
**System.Data.SqlClient.SqlException: Invalid column name 'id'.**
![image](https://github.com/umbraco/Umbraco-CMS/assets/25307835/3ec53741-e6f1-4170-9434-c8ce83f8543b)

### Specifics

Works fine on SQL Server 2019, but throws an exception on SQL Server 2022.

### Steps to reproduce

1) Install Umbraco 8 nuget package (were able to replicate this issue on 8.18.13 and 8.18.14)
2) Create any document type with any property
3) Create a content of this document type and fill in the property value. Save and publish the content. 
4) Modify the value of this property and save and publish it again.
5) Try to rollback this content to a previous version.

### Expected result / actual result

Expected result:
Rollback to a Previous Version window should open showing the 2 versions in it.

Actual result:
When the Rollback to a Previous Version window is opening the **System.Data.SqlClient.SqlException: Invalid column name 'id'.** is thrown.

**Comment by bifort** [comment]
I have tested a propsed fix for a similar issue described in here https://github.com/umbraco/Umbraco-CMS/pull/14173
but it didn't help.

**Comment by bifort** [comment]
The same issue has been reported few times on our: 
https://our.umbraco.com/forum/using-umbraco-and-getting-started/111984-issue-with-rollback-on-umbraco-8-after-move-from-azure
https://our.umbraco.com/forum/using-umbraco-and-getting-started/114096-invalid-column-name-id

**Comment by bergmania** [comment]
Hi.. Umbraco 8 is in security-phase and will not receive fixes that are not security related, so I'll close this issue.

If you wanna read more about the support phases you can take a look here: https://umbraco.com/products/knowledge-center/long-term-support-and-end-of-life/
