### ISSUE TITLE
Request culture not correctly set for custom routes with IVirtualPageController

### ISSUE THREAD

**Issue by WouterCeulemans** [umbraco/Umbraco-CMS#16555]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

13.3.2

### Bug summary

Since upgrading from 13.3.0 to 13.3.2, the request culture is not being set anymore based on the PublishedContent and domain. As a result, culture dependent services like the VariationContext and CultureDictionary are using the wrong culture.

### Specifics

We have a multilingual site. The domains are configured as follows:
![image](https://github.com/umbraco/Umbraco-CMS/assets/6593444/9a941324-ca05-4da9-ae30-acd0d3e8eb58)
We have configured some custom routes with IVirtualPageController based on [the documentation](https://docs.umbraco.com/umbraco-cms/v/13.latest-lts/reference/routing/custom-routes#custom-routes-within-the-umbraco-pipeline). All the routes follow the same pattern, like `/{lang}/custom-route`, where `lang` is a segment for the current language, to match the domains.

In 13.3.0 the request language was correctly set. After updating to 13.3.2, it is not. After some investigation, it seems like this worked because the request went through all content finders, including the IContentLastChanceFinder. The request language was then set by the `Umbraco.Cms.Web.Common.Localization.UmbracoPublishedContentCultureProvider`. This was changed in 13.3.2 with  #16015. Now the request culture is set by the `Microsoft.AspNetCore.Localization.AcceptLanguageHeaderRequestCultureProvider` and not based on the PublishedContent or domain.

### Steps to reproduce

- Set up a multilingual site and configure the domains like the screenshot above
- Add a custom 404 error page
- Add the 404 Collection to the appsettings or register a custom `IContentLastChanceFinder`
- Create a custom route, which has a segment for the language. The custom controller implements `IVirtualPageController`.
    ```csharp
    app.UseUmbraco()
    .WithMiddleware(u =>
    {
        u.UseBackOffice();
        u.UseWebsite();
    })
    .WithEndpoints(u =>
    {
        u.EndpointRouteBuilder.MapControllerRoute(
                "Custom Controller",
                "/{lang}/custom-route",
                new { Controller = "Custom", Action = "Index" });
        u.UseInstallerEndpoints();
        u.UseBackOfficeEndpoints();
        u.UseWebsiteEndpoints();
    });
- Navigate to for example /nl/custom-route and check the current request culture in the controller action.

### Expected result / actual result

I would expect that the request culture is still set based on the domain and PublishedContent from the IVirtualPageController.

**Comment by Zeegaan** [comment]
Fixed in https://github.com/umbraco/Umbraco-CMS/pull/16572 🚀
