### ISSUE TITLE
Tabs do not get saved in Element Types with no Properties

### ISSUE THREAD

**Issue by deanleigh** [umbraco/Umbraco-CMS#16567]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

14

### Bug summary

Tabs do not get saved in Element Types with no Properties

### Specifics

If you create an Element Type then add a Tab and then Save if you navigate away the Tab Title is empty on return

### Steps to reproduce

If you create an Element Type then add a Tab and then Save if you navigate away the Tab Title is empty on return

### Expected result / actual result

For the Tab to save

**Comment by Zeegaan** [comment]
Heyo 👋 
You cannot save "empty" tabs, as we at that point cannot differentiate if it's a group or a tab. 
This has been the behavior since tabs was reintroduced in 9, so I will go ahead and close this issue 😁 

Thanks for reporting, and please don't hesitate to report anything else you find 🙏

**Comment by deanleigh** [comment]
Just to be clear I am giving the tab a name just not adding any content within that tab.
Is that what you mean by "You cannot save "empty" tabs"?
