### ISSUE TITLE
Error when signing in to Umbraco Backoffice using Azure AD OIDC

### ISSUE THREAD

**Issue by cvagan** [umbraco/Umbraco-CMS#16565]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

14.0.0

### Bug summary

When attempting to sign in to Umbraco Backoffice using OIDC configured for Azure AD, an OpenIdConnectProtocolException is thrown saying that the OpenIdConnectProtocol requires the jwt token to have an 'iss' claim.

### Specifics

Full exception message and trace:

```
An unhandled exception occurred while processing the request.
OpenIdConnectProtocolException: IDX21314: OpenIdConnectProtocol requires the jwt token to have an 'iss' claim. The jwt did not contain an 'iss' claim, jwt: '[PII of type 'System.IdentityModel.Tokens.Jwt.JwtSecurityToken' is hidden. For more details, see https://aka.ms/IdentityModel/PII.]'.
Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectProtocolValidator.ValidateIdToken(OpenIdConnectProtocolValidationContext validationContext)

AuthenticationFailureException: An error was encountered while handling the remote login.
Microsoft.AspNetCore.Authentication.RemoteAuthenticationHandler<TOptions>.HandleRequestAsync()

Stack Query Cookies Headers Routing
OpenIdConnectProtocolException: IDX21314: OpenIdConnectProtocol requires the jwt token to have an 'iss' claim. The jwt did not contain an 'iss' claim, jwt: '[PII of type 'System.IdentityModel.Tokens.Jwt.JwtSecurityToken' is hidden. For more details, see https://aka.ms/IdentityModel/PII.]'.
Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectProtocolValidator.ValidateIdToken(OpenIdConnectProtocolValidationContext validationContext)
Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectProtocolValidator.ValidateTokenResponse(OpenIdConnectProtocolValidationContext validationContext)
Microsoft.AspNetCore.Authentication.OpenIdConnect.OpenIdConnectHandler.HandleRemoteAuthenticateAsync()

Show raw exception details
AuthenticationFailureException: An error was encountered while handling the remote login.
Microsoft.AspNetCore.Authentication.RemoteAuthenticationHandler<TOptions>.HandleRequestAsync()
Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
StackExchange.Profiling.MiniProfilerMiddleware.Invoke(HttpContext context) in MiniProfilerMiddleware.cs
Umbraco.Cms.Web.Common.Middleware.UmbracoRequestMiddleware.InvokeAsync(HttpContext context, RequestDelegate next)
Umbraco.Cms.Web.Common.Middleware.UmbracoRequestMiddleware.InvokeAsync(HttpContext context, RequestDelegate next)
Microsoft.AspNetCore.Builder.UseMiddlewareExtensions+InterfaceMiddlewareBinder+<>c__DisplayClass2_0+<<CreateMiddleware>b__0>d.MoveNext()
Umbraco.Cms.Web.Common.Middleware.PreviewAuthenticationMiddleware.InvokeAsync(HttpContext context, RequestDelegate next)
Microsoft.AspNetCore.Builder.UseMiddlewareExtensions+InterfaceMiddlewareBinder+<>c__DisplayClass2_0+<<CreateMiddleware>b__0>d.MoveNext()
Umbraco.Cms.Web.Common.Middleware.UmbracoRequestLoggingMiddleware.InvokeAsync(HttpContext context, RequestDelegate next)
Microsoft.AspNetCore.Builder.UseMiddlewareExtensions+InterfaceMiddlewareBinder+<>c__DisplayClass2_0+<<CreateMiddleware>b__0>d.MoveNext()
SixLabors.ImageSharp.Web.Middleware.ImageSharpMiddleware.Invoke(HttpContext httpContext, bool retry)
Umbraco.Cms.Api.Management.Middleware.BackOfficeAuthorizationInitializationMiddleware.InvokeAsync(HttpContext context, RequestDelegate next)
Microsoft.AspNetCore.Builder.UseMiddlewareExtensions+InterfaceMiddlewareBinder+<>c__DisplayClass2_0+<<CreateMiddleware>b__0>d.MoveNext()
Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddlewareImpl.Invoke(HttpContext context)
```

The external login is configured like this:
![image](https://github.com/umbraco/Umbraco-CMS/assets/35521784/f33c27ca-5b13-4162-a6f5-10c9f3d181b1)

Debugging the OnTokenValidated event shows that the claim is included in the token response from Azure:
![image](https://github.com/umbraco/Umbraco-CMS/assets/35521784/3b774392-09ef-45cf-a0f9-55e1fea79f66)

But the claim is not present in the validated SecurityToken, which leads me to believe that the iss claim (among others) is not being mapped properly:
![image](https://github.com/umbraco/Umbraco-CMS/assets/35521784/8f4cafa2-342d-4948-bf6b-1b194fd3b043)

This problem was first encountered on a project that was upgraded to v14.0.0 from v13.3.0, but was also replicated on a fresh v14.0.0 installation.

The project is using the Microsoft.AspNetCore.Authentication.OpenIdConnect package version 8.0.6. Downgrading to older versions such as 8.0.2 made did not solve the issue. Version 8.0.6 was also tested on Umbraco v13.3.0 was also found to be working as intended.

### Steps to reproduce

Install Nuget Package "Microsoft.AspNetCore.Authentication.OpenIdConnect" 8.0.6

Use the following configuration in Program.cs:

```
builder.CreateUmbracoBuilder()
    .AddBackOffice()
    .AddBackOfficeExternalLogins(loginsBuilder =>
                loginsBuilder.AddBackOfficeLogin(authBuilder =>
                    authBuilder.AddOpenIdConnect(BackOfficeAuthenticationBuilder.SchemeForBackOffice("oidc")!, "Azure AD", options =>
                    {
                        options.Authority = "https://login.microsoftonline.com/<tenantId>";
                        options.ClientId = "<clientId>";
                        options.ClientSecret = "<clientSecret>";
                        options.CallbackPath = "/signin-oidc";
                        options.ResponseType = "code";
                        options.ResponseMode = "query";
                        options.UsePkce = true;

                        options.Scope.Add("email");
                        options.GetClaimsFromUserInfoEndpoint = true;
                    }),
                    providerOptions =>
                    {
                        providerOptions.DenyLocalLogin = false;
                        providerOptions.AutoLinkOptions = new ExternalSignInAutoLinkOptions(
                            autoLinkExternalAccount: true,
                            defaultUserGroups: new[] { Constants.Security.AdminGroupAlias },
                            defaultCulture: "nb-NO")
                        {
                            OnAutoLinking = (autoLinkUser, loginInfo) =>
                            {
                                autoLinkUser.IsApproved = true;
                            }
                        };
                    }))
    .AddWebsite()
    .AddDeliveryApi()
    .AddComposers()
    .Build();
```

(This also requires an Enterprise app with the proper configuration in Azure.)

Add the following to /App_Plugins/ExternalLoginProviders/umbraco-package.json

```
{
  "$schema": "../../umbraco-package-schema.json",
  "name": "Company name",
  "allowPublicAccess": true,
  "extensions": [
    {
      "type": "authProvider",
      "alias": "My.AuthProvider.AzureAD",
      "name": "My Auth Provider",
      "forProviderName": "Umbraco.oidc",
      "meta": {
        "label": "Generic",
        "defaultView": {
          "icon": "icon-cloud"
        },
        "behavior": {
          "autoRedirect": false
        },
        "linking": {
          "allowManualLinking": true
        }
      }
    }
  ]
}
```

Run the solution, go to /umbraco and choose the external login option.

### Expected result / actual result

Expected result: User is authenticated and is granted access to Umbraco Backoffice

Actual result: OpenIdConnectProtocolException exception occurs saying that the jwt token is missing the required 'iss' claim.

**Comment by benedict-odonovan** [comment]
I'm having the same issue after upgrading to v14 - I suspect it may have something to do with a dependency being updated somewhere that causes the ConfigurationManager to not populate the OpenID configuration correctly. After migrating the AuthorizationEndpoint, Issuer, and SecurityTokenSignatureKey can no longer be found.

If it helps anyone to narrow it down, this code works in v13 to retrieve the AuthorizationEndpoint from a Keycloak instance but fails in v14

```
  var config = builder.Config;
  options.Authority = "...";
  options.MetadataAddress = ".../.well-known/openid-configuration";
  options.ClientId = "...";
  options.RequireHttpsMetadata = false;

  var documentRetriever = new HttpDocumentRetriever { RequireHttps = false };
  options.ConfigurationManager = new ConfigurationManager<OpenIdConnectConfiguration>(
      options.MetadataAddress,
      new OpenIdConnectConfigurationRetriever(),
      documentRetriever);
  options.Configuration = options.ConfigurationManager.GetConfigurationAsync(CancellationToken.None).Result;
```

**Comment by tobias-johansson-nltg** [comment]
> Potentially found the problem? My version of Microsoft.IdentityModel.Protocols.OpenIdConnect package was different to the other IdentityModel packages (7.5.1). This was causing the ConfigurationManager to not deserialize OpenID configurations correctly.
> 
> I managed to solve it by manually updating Microsoft.IdentityModel.Protocols.OpenIdConnect to 7.5.1.
> 
> See [here](https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/issues/2402) and the IdentityServer mention for another project having a similar issue.

I just want to say thank you for this. Explicitly installing a newer version of `Microsoft.IdentityModel.Protocols.OpenIdConnect` solved this problem for us! We had the same problem as in the original post (claims came back correctly, but were not mapped to the SecurityToken) and this solved the problem :)

**Comment by NguyenThuyLan** [comment]
Hi @cvagan , thanks for reporting this issue. I will let the team know.

**Comment by SlawekSkiba** [comment]
I found exactly the same issue after upgrading from **13.4.1** to **13.5.0**

**Comment by NguyenThuyLan** [comment]
I made a PR to update docs https://github.com/umbraco/UmbracoDocs/pull/6457
