### ISSUE TITLE
URGENT: mediacache not work properly after upgrade from 11.5.0 to 12.3.10

### ISSUE THREAD

**Issue by afabri73** [umbraco/Umbraco-CMS#16569]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

12.3.10

### Bug summary

After upgrade a website from v11.5.0 to 12.3.10, not all media are showed in media folders (grid view) and also when I try to select an image with mediapicker.
Other media folder, instead, display correctly all the images and other folders, display only some images.
Other problem is that if I upload a new image, this is loaded correctly but mediacache not update and I don't see it in grid view.

### Specifics

MEDIA FOLDER (GRID VIEW)
<img width="1327" alt="Screenshot 2024-06-06 at 22 53 08" src="https://github.com/umbraco/Umbraco-CMS/assets/6714121/6b23569c-ff5d-49c6-9542-9ed8a17d6b1b">

IMAGE SELECTION WITH MEDIA PICKER
<img width="399" alt="Screenshot 2024-06-06 at 23 09 08" src="https://github.com/umbraco/Umbraco-CMS/assets/6714121/c99f61cb-5d0d-4b69-9040-0947a5df5b73">

### Steps to reproduce

In a new installation I didn't encounter the error
With Umbraco v11.5.0 I had no problems

My actual configuration:
Umbraco v12.3.10
SixLabors.ImageSharp v3.1.4
SixLabors.ImageSharp.Web v3.0.1 (if I try to update it to v3.1.2, GetCropUrl() does not work anymore and throw an exception)

### Expected result / actual result

I must see all images correctly everywhere.
There is a way to force rebuild MediaCache?

**Comment by james-whittington1** [comment]
![image](https://github.com/umbraco/Umbraco-CMS/assets/37091895/8c796788-33e5-41e7-8073-7f7257a877a3)
What do you see here for media cache? 

try rebuilding the database cache and reloading memory cache

**Comment by bergmania** [comment]
Hi @afabri73.

i think first step to understand your issue is to figure out, what Paths do the images that are not served have?

Do they look correct in the URLs that return 404.
This can tell us, if it is an issue with Images or url generation.

You cannot upgrade Imagesharp due to breaking changes. If you wanna use a later version, please update to Umbraco 13.

**Comment by afabri73** [comment]
Hi to all,
first of all thanks for your support.

@james-whittington1: I tried several times to rebuild the memory cache and database cache, but unfortunately they didn't work.
I also deleted the MediaCache folder with the hope that it could be recreated automatically (solution found in the Forum and Github), but unfortunately this didn't work either.

@bergmania: all the images were present and I displayed them correctly (both image and crops) when I opened them individually from the media section.
Regarding the update of ImageSharp, I did it as a test to understand if the problem was the version installed.
I usually only update Umbraco and the packages

**FOR ALL:**
As you can see I'm speaking in the past tense because I finally found the solution this morning by performing the following steps:

- I uninstalled the ImageSharp update
- I republished the project with Visual Studio 2022
- I restored permissions to the entire site folder in the File System
- I reloaded the memory cache and rebuilt the database cache
- I refreshed the status
- I republished the entire site in the content section

I hope this post can help anyone who has encountered the same problem.

Thank you and see you at CodeGarden :-)
Adriano
