### ISSUE TITLE
Nested Block Lists/Many block elements with many languages slows down save+publish dramatically

### ISSUE THREAD

**Issue by marklonquist** [umbraco/Umbraco-CMS#16566]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

12, 13, 14

### Bug summary

We have a site with 50+ languages, which all heavily uses the Block List type, with nested Block Lists.
Just by adding 10 simple block elements (eg, just a block element with an text field), on all languages, makes it take 10+ seconds to save+publish.

We have made various tests, and it only happens once we start using the Block List.

On some pages, we wait upwards of 30 seconds for save+publish to finish.

### Steps to reproduce

1. Create a new Umbraco project
2. Add 50 languages
3. Setup a HomePage with a Block List property.
4. Setup a Block List Element with a Textbox property.
5. Add 10 Block Elements to each language
6. Observe, that the time to save+publish starts rising for each new language added

### Expected result / actual result

Should save+publish in less than 5 seconds (or faster), no matter how many languages is added.

**Comment by Zeegaan** [comment]
Heyo! 👋 We've just looked into to some performance optimizations, one of these was related to languages, so this might be alleviated. 

Could you test this out in the newest `13.4.0-rc` ? 😁

**Comment by marklonquist** [comment]
We will try it out and get back to you :)

**Comment by PeterRygeBestseller** [comment]
@Zeegaan 
Performance is a lot better when saving and publishing on `13.4.0-rc`. 
I've tested this on a node with:
- 50+ language
- Block list with 20 block elements
- Within the 20 block elements there's nested an additional block list with 1-10 elements.

Save and publish went from taking 4 minutes on Umbraco 12.0.0 to 20 seconds on Umbraco 13.4.0-rc

**Comment by Zeegaan** [comment]
@PeterRygeBestseller That's great to hear!
I will go ahead and close this issue as resolved for now, @marklonquist feel free to re-open if you find something 😁
