### ISSUE TITLE
Cannot log into /Umbraco when running it locally 

### ISSUE THREAD

**Issue by SSmale** [umbraco/Umbraco-CMS#16578]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

14.0.0

### Bug summary

Running Umbraco in a Developer container with mysql db and dotnet using the methods specified in the VSCode getting started. When trying to access via http I get a use HTTPS error, and with HTTPS I get a warning about redirect URLs. I did wipe the DB and restart it and got it working, it then didn't work when I restarted the app. Nothin had been changed from the template

### Specifics

```
error:invalid_request
error_description:The specified 'redirect_uri' is not valid for this client application.
error_uri:https://documentation.openiddict.com/errors/ID2043
```

### Steps to reproduce

MacOS intel

1. open VSCode 
2. start new dev container (.net and MSSQL)
3. follow the install instructions for the dotnet cli then the vscode launch instructions
4. try to go to /umbraco

### Expected result / actual result

the ability to login

**Comment by bergmania** [comment]
This is fixed by https://github.com/umbraco/Umbraco-CMS/pull/16614.

The reason is because you need to use Https with Umbraco 14.0, and when accessing /umbraco from http first, it will save that, and then you are stuck
