### ISSUE TITLE
Download package xml not working

### ISSUE THREAD

**Issue by huwred** [umbraco/Umbraco-CMS#16576]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

14.0.0

### Bug summary

After creating a package in the backoffice, attempts to download the package fail in Edge, downloads OK in Chrome

### Specifics

gps.js:1  Uncaught (in promise) DOMException: Failed to execute 'insertAdjacentHTML' on 'Element': The provided markup is invalid XML, and therefore cannot be inserted into an XML document.
    at new secureBlob (chrome-extension://fgddmllnllkalaagkghckoinaemmogpe/scripts/content/gps.js:1:3082)
    at blobDownload (https://localhost:44360/umbraco/backoffice/ddd050b33745d7e332ea8e1c23ebf37a1bc3de73/packages/core/utils/download/blob-download.function.js:15:18)
    at #download (https://localhost:44360/umbraco/backoffice/ddd050b33745d7e332ea8e1c23ebf37a1bc3de73/packages/packages/package-builder/workspace/workspace-package-builder.element.js:45:9)

### Steps to reproduce

Create a package in the back office, add some document types and datatypes.
Click Save (package is saved)
Click Download (receive the error above)

### Expected result / actual result

Expect the package to download as an xml file

**Comment by Zeegaan** [comment]
Hmmm I cannot reproduce this sadly, I can download the packages just fine in edge 🤔 

![image](https://github.com/umbraco/Umbraco-CMS/assets/70372949/c64de963-7b77-4074-8ecd-e4205c932c71)

Could you come up with some basic steps i can follow to reproduce this from a fresh install? 😁 
(creating the doctype, content, which datatypes you're picking etc.)

**Comment by huwred** [comment]
Ok, I will give it another try and see what happens 😁

**Comment by huwred** [comment]
TBH, it doesn't matter what I add to the package (just a single data type checkbox list) I still get the same error in Edge.

Microsoft Edge
Version 125.0.2535.92 (Official build) (64-bit)

**Comment by Zeegaan** [comment]
Heyo 👋 With some help from a colleague, it seems that you are using an extension that is causing this error.

Can you try disabling your ExpressVPN extension, then it should work 😁

**Comment by huwred** [comment]
Yes! that sorted it 😃 thanks.

**Comment by Zeegaan** [comment]
Great to hear! No problem 👍
