### ISSUE TITLE
File Upload Field data type prevents document publishing

### ISSUE THREAD

**Issue by CodeBunTes** [umbraco/Umbraco-CMS#16573]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

14.0.0

### Bug summary

In v14 if you include the direct file upload datatype ( Umb.PropertyEditorUi.UploadField ) within a doctype, it becomes impossible to publish the page as soon as this has been filled in with a file for the first time.

### Steps to reproduce

1. Install fresh Umbraco 14.0.0 instance.
2. Create a simple 'page' doctype with two fields. 'Textstring' for 'title' and an 'Upload file' datatype for 'attachment'. Allow this doctype at root.
3. In content tree, create a new 'page' node. Fill in name/title but leave attachment blank for now. Saving and publishing works fine with no upload present.
4. Now add an image file to the attachment field. The page can be saved, but save and publish will generate an error 'Could not parse editor value to a FileUploadValue object' message.
5. Any subsequent attempts to republish the node will generate this same error, and it is also impossible to remove the file completely leaving the node unpublishable.

![image](https://github.com/umbraco/Umbraco-CMS/assets/134947113/f9e30b0f-ae65-4280-9eea-5132847538ac)

Behaviour can be replicated across Chrome and Firefox based browsers.

**Comment by Zeegaan** [comment]
I am happy to report that this issue has been fixed in https://github.com/umbraco/Umbraco-CMS/pull/16429 🚀
