### ISSUE TITLE
TinyMCE Source Code Editor not displaying

### ISSUE THREAD

**Issue by deanleigh** [umbraco/Umbraco-CMS#16579]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

14

### Bug summary

![image](https://github.com/umbraco/Umbraco-CMS/assets/6745929/f3eb37bf-8142-43fa-b48b-35af0afec2d4)

### Specifics

Even though it is enabled the TinyMCE Source Code Editor is not displaying in the editor

### Steps to reproduce

Add an RTE to a page
Add text to the RTE
Attempt to view the source code

### Expected result / actual result

A source code button is avaialble

**Comment by deanleigh** [comment]
Yep that worked so thank you very much.
I guess it's still a bug that needs fixing.

**Comment by Zeegaan** [comment]
I can reproduce this, thanks for reporting! 🐛 
Wierd that it shows up after changing config as @Nuklon says 🤔 
This also happens on a clean install of v14, so it's not just upgrades 😁
