### ISSUE TITLE
2 columns block grid with contents is not saved correctly

### ISSUE THREAD

**Issue by amfh** [umbraco/Umbraco-CMS#16571]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

14.0.0

### Bug summary

A block grid with 2 contents taking 6 colums each is not saved correctly.
![image](https://github.com/umbraco/Umbraco-CMS/assets/10772909/e28bf3b5-f70d-475f-a8af-760d84e1badd)

### Specifics

Checked on Chrome and Firefox

### Steps to reproduce

1- Add 2 components to block grid.
2- Make each component take 6 cols out of 12 cols in the grid, each with available column span
![image](https://github.com/umbraco/Umbraco-CMS/assets/10772909/fee89fa9-528e-4b65-b720-7817b160c2a1)
![image](https://github.com/umbraco/Umbraco-CMS/assets/10772909/e28bf3b5-f70d-475f-a8af-760d84e1badd)
3- Save and publish the page in Umbraco
4- Refresh the page in Umbraco 
5- Each component takes now 12 cols in the grid, selected colum span i snot saved.
![image](https://github.com/umbraco/Umbraco-CMS/assets/10772909/c2ea4705-626c-403f-8fc0-869ea3c94bfa)

### Expected result / actual result

Selected column span should ba saved.

**Comment by Zeegaan** [comment]
Heyo 👋 This seems like the samme issue as https://github.com/umbraco/Umbraco-CMS/issues/16372 🤔 
Can you confirm this ? 😁

**Comment by amfh** [comment]
Yes, correct!
