### ISSUE TITLE
DeliveryApiContentIndex doesn't raise TransformingIndexValues event

### ISSUE THREAD

**Issue by Shazwazza** [umbraco/Umbraco-CMS#16589]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

13

### Bug summary

The DeliveryApiContentIndex  doesn't raise the TransformingIndexValues event. This is because the OnTransformingIndexValues is overridden and then no-ops. If a no-op is necessary, than a manual event raising is required like

```cs
TransformingIndexValues?.Invoke(this, e);
```

https://github.com/umbraco/Umbraco-CMS/blob/0bb46b9667182d57f4138f4f39f9fbebdd56cbac/src/Umbraco.Examine.Lucene/DeliveryApiContentIndex.cs#L138

### Steps to reproduce

Try to bind to TransformingIndexValues event for the content delivery index and it will not be executed.

---
_This item has been added to our backlog AB#41869_

**Comment by Shazwazza** [comment]
But... you can't do that because you cannot raise an event that is declared on the base class. Best thing to do would be change the logic of the UmbracoExamineIndex to not override OnTransformingIndexValues to transform values but instead bind to that event externally for the index types that need the custom logic for path, icon, etc... Prob just best to avoid overriding OnTransformingIndexValues entirely.

**Comment by elit0451** [comment]
Fixed in https://github.com/umbraco/Umbraco-CMS/pull/16756
