### ISSUE TITLE
Missing options for deleting and moving media items in Media section when items are selected

### ISSUE THREAD

**Issue by amfh** [umbraco/Umbraco-CMS#16584]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

14.0.0

### Bug summary

Missing options for deleting and moving media items in Media section when items are selected

### Steps to reproduce

- Go to a folder with items in Media section
- Select one or more items 
- Missing options for deleting and moving selected items

### Expected result / actual result

As previous versions, its should be possible to move or delete several items

**Comment by amfh** [comment]
![image](https://github.com/umbraco/Umbraco-CMS/assets/10772909/0f410538-3eb0-4a16-854a-14094e189c87)

**Comment by nikolajlauridsen** [comment]
Hey @amfh I can indeed reproduce, thanks for reporting 🐛🕵️

**Comment by iOvergaard** [comment]
Hey everyone, this looks to be the same issue as #16272 so I will close this as a duplicate. Please re-open if you feel there is more to it.
