### ISSUE TITLE
[V14] Cannot switch language in content on fresh v14 installation

### ISSUE THREAD

**Issue by RBerntsen** [umbraco/Umbraco-CMS#16580]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

14.0.0

### Bug summary

Having created two languages in Umbraco v14 (en-us and da), completely fresh installation. Nothing happens when I switch to the language that's not the default and I cannot create any new content for the new language.

Probably related to the issue below in some way:
[#16460](https://github.com/umbraco/Umbraco-CMS/issues/16460)

### Steps to reproduce

Install a fresh installation of v14
Start up the site
Add a new language, e.g. "da"
![image](https://github.com/umbraco/Umbraco-CMS/assets/1783382/6f7103cf-3860-457f-bbfe-edc291f3120e)

Create a new document type. Keep the default settings:
![image](https://github.com/umbraco/Umbraco-CMS/assets/1783382/91ecff5a-a6e4-42be-a4f6-fbd526f90867)

Allow at root:
![image](https://github.com/umbraco/Umbraco-CMS/assets/1783382/dd48ca08-2d7d-453c-b212-927ffeffb4e1)

Now go to the content.
Create a content page in en-us.

Afterwards try and change the content in the dropdown to Danish. Nothing happens. If you do create content afterwards the page will be created in en-us:

![image](https://github.com/umbraco/Umbraco-CMS/assets/1783382/b49eaac8-1222-4560-b07a-a761056cc480)

It does work if I enable the culture variation on the specific document type.

### Expected result / actual result

I would expect that I could create two separate pages in Danish and English that are not variations of each other.

**Comment by Zeegaan** [comment]
Yea I'd say this is a duplcate of https://github.com/umbraco/Umbraco-CMS/issues/16460 😁 
So we are aware and will be looking into it 👍 
Thanks for reporting, I will close this 🐛

**Comment by RBerntsen** [comment]
@Zeegaan Totally fine. Not sure if the two things were that close to each other so I thought I would highlight the issue. Thanks for looking into it. 👍

**Comment by Zeegaan** [comment]
All good, and please don't hesitate to report something else, we'd rather have 200 duplicate issues than 0 reports 😁
