### ISSUE TITLE
v14 feels like a BETA version

### ISSUE THREAD

**Issue by SSmale** [umbraco/Umbraco-CMS#16588]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

14.0.0

### Bug summary

I have had so many issues with the new version

- Can't log in locally
- Can't access the backend over HTTP
- BlockGrid showing blank lines, then corrupting itself if you don't wait for them to load (sometimes needing n refreshes)
- copy and paste BlockGrid items gone
- content and/or settings tab showing up when not configured for a BlockGrid item
- Deploy import page crashing
- back office going completely unresponsive 
- media items being able to be uploaded from the content page

### Steps to reproduce

start a fresh project and try to do some work

### Expected result / actual result

v13 but with some improvements

**Comment by iOvergaard** [comment]
Hi @SSmale and thanks for your report and for testing it out. Your list helps us evaluate which areas could be more important to look at first. I see that most, if not all of the issues mentioned, have been created as issue reports in their own right. I will therefore go ahead and close this issue. If you feel that some of it is unaddressed, feel free to open a new issue report targeting the issues individually ☺️
