### ISSUE TITLE
Block Grid does not render block editor thumbnails

### ISSUE THREAD

**Issue by asawyermarathon** [umbraco/Umbraco-CMS#16598]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

14.0.0

### Bug summary

Block Grid does not render block editor thumbnails.

### Specifics

Block Grid does not render block editor thumbnails.
I took a video.

https://github.com/umbraco/Umbraco-CMS/assets/87725234/11cc5a73-beaa-487c-8c67-c9f047fff4dd

### Steps to reproduce

1. In settings, create a block grid data type and add a block editor, specify a thumbnail
2. In content, when adding an item to the block grid content, no thumbnail is rendered

### Expected result / actual result

Block Editor thumbnails should be rendered

---
_This item has been added to our backlog AB#41791_

**Comment by elit0451** [comment]
Hi @asawyermarathon 👋 

Thanks for reaching out! I can indeed reproduce this. We will have a look 🙂

**Comment by iOvergaard** [comment]
A fix has been merged and will be released in 14.2.0 👍
