### ISSUE TITLE
Publish node with multiple languages throws error when properties are mandatory

### ISSUE THREAD

**Issue by oxioquadhenke** [umbraco/Umbraco-CMS#16592]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

14.0.0

### Bug summary

When you have a site with multiple languages and try to publish a node(with one or more  mandatoryfield) not created on all languages it fails. The node is saved but not published.

### Specifics

Tested in chrome and Edge

### Steps to reproduce

1. Create a site with at least 2 languages
2. Create a documenttype that hars a vary by culture set to true
3. Add a property that allow vary by culture
4. Create a node with the created doctype and create only on language variation, saveandpublish

### Expected result / actual result

The node will be saved and not published

![Screenshot 2024-06-12 154431](https://github.com/umbraco/Umbraco-CMS/assets/159765947/d0bfee09-7f78-4104-9062-2205957a5295)

![image](https://github.com/umbraco/Umbraco-CMS/assets/159765947/ef863afb-46ac-43ff-a97e-c0169cb7f7c5)

---
_This item has been added to our backlog AB#41876_

**Comment by iOvergaard** [comment]
Thanks for reporting this. We will look into it!

**Comment by corey-cb** [comment]
This is still occurring in 14.2.0

**Comment by oxioquadhenke** [comment]
@nielslyngsoe is this merged in14 or only 15?
