### ISSUE TITLE
Cannot reorder composition tabs by entering a custom integer

### ISSUE THREAD

**Issue by asawyermarathon** [umbraco/Umbraco-CMS#16597]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

14.0.0

### Bug summary

Cannot reorder composition tabs by entering a custom integer. This means there is no way of ordering multiple compositions.

### Specifics

I took a video.

https://github.com/umbraco/Umbraco-CMS/assets/87725234/7664282f-2e18-4031-841f-8c1cef154900

### Steps to reproduce

1. Create a document type (composition) with a single tab
2. Click the reorder button
3. Try to set the sort index

### Expected result / actual result

Users should be able to set the sort index of tabs.

**Comment by Zeegaan** [comment]
This is a duplicate of https://github.com/umbraco/Umbraco-CMS/issues/16597, so I will go ahead and close this 😁
