### ISSUE TITLE
Link node selection does not auto generate a link title in the backoffice.

### ISSUE THREAD

**Issue by asawyermarathon** [umbraco/Umbraco-CMS#16596]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

14.0.0

### Bug summary

Link selection does not auto generate a link title the backoffice.

### Specifics

I took a video.

https://github.com/umbraco/Umbraco-CMS/assets/87725234/00b7106f-6293-4dd4-a91e-bc06e6ee8873

### Steps to reproduce

1. Create a new MultiUrlPicker field
2. Select an Umbraco Node

### Expected result / actual result

I would expect link selection of a node to set the link title by default - not sure if not setting the link title is intended?

**Comment by asawyermarathon** [comment]
I just realized that the link picker does work, it just is not automatically populating the link title field - that's the only issue here.

**Comment by elit0451** [comment]
Hi @asawyermarathon 👋 

Thanks for reaching out! I tried to reproduce this in Umbraco 14.1.0 and the issue is partially resolved - when we pick an item, the key of the item is transformed to the node's path but if you edit the link, we still see the key of the node, instead of the link:
![Correct link](https://github.com/user-attachments/assets/5c04067b-ac10-409a-a60a-3584bf933f5d)



![Key as link](https://github.com/user-attachments/assets/769f9376-333c-4768-8d55-d40b86fb1761)



We will have a look 🙂

**Comment by Nicolas-Nmedia** [comment]
Yeah, happens too in 13.3.1. Not sure if this was changed at some point as some point people were also complaining about this exact behavior.
Maybe a configuration flag could be used to turn this on or off? I can see why it can be annoying but for me, in my current project, I need that field to be populated as it acts as a Block Label in a blocklist; now I have to manually enter every title(label) when I pick from the node tree.

**Comment by shearer3000** [comment]
confirming this issue in 14.2

**Comment by asawyermarathon** [comment]
yes, I'm not sure if there is a reason for changing this behavior. I know that for links embedded in RTEs, the link title should NOT be auto set, as that can cause unintended issues with SEO / ADA compliance. However, developers often use this picker as a stand alone field to store link, name, and open in new tab, so in that case the title could be auto set without issue, and could save a small bit of time for editors.

**Comment by shearer3000** [comment]
Yeah from a content editors perspective, there's a strong argument for it needing to work the same as prior to umbraco 14, but if there's a new use-case that it needs to support then being able to configure it to work that way too (but as an opt-in, not as the new default)

**Comment by leekelleher** [comment]
The link title and URL issues should be resolved with the fix in https://github.com/umbraco/Umbraco.CMS.Backoffice/pull/2477, scheduled for release in Umbraco 15.1.0.

**Comment by shearer3000** [comment]
hi - 15.0 sounds like a better release candidate than 15.1 given thats its not out yet. My recommendation would be to shift out the release date of 15 to incorporate fundamental tickets like this (there are other tickets too)
