### ISSUE TITLE
After publishing a new node, it sometimes shows as grayed out in the navigation tree.

### ISSUE THREAD

**Issue by asawyermarathon** [umbraco/Umbraco-CMS#16595]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

14.0.0

### Bug summary

After publishing a new node, it sometimes shows as grayed out in the navigation tree. If I reload, it displays correctly, so it is only a presentation / front end issue.

### Specifics

After publishing a new node, it sometimes shows as grayed out in the navigation tree. If I reload, it displays correctly, so it is only a presentation / front end issue. Also it only happens when the section of the tree that the new node was created in is already expanded.
![grayedOutPublish](https://github.com/umbraco/Umbraco-CMS/assets/87725234/09dbc045-16d2-4713-84db-71d05ef2be3a)

### Steps to reproduce

1. Create and publish a new node

### Expected result / actual result

Node should not be shown in an unpublished style

---
_This item has been added to our backlog AB#41875_

**Comment by iOvergaard** [comment]
Thanks for reporting this. I can confirm it is an issue and we want to fix it.
