### ISSUE TITLE
Shortcut keys not working in v14

### ISSUE THREAD

**Issue by BishalTimalsina12** [umbraco/Umbraco-CMS#16603]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

14.0.0

### Bug summary

The other day I was setting up content structure in Umbraco v14, and I encountered an issue with the shortcut keys. I have a habit of using Ctrl + S to save the document type, but it didn't work as expected. This is a very useful shortcut :)

### Steps to reproduce

Go to the settings section of Umbraco.
Create or edit a document type.
Press Ctrl + S to save the document type

### Expected result / actual result

Expected Result: The document type should be saved when Ctrl + S is pressed.
Actual Result: Pressing Ctrl + S does not save the document type.

**Comment by Zeegaan** [comment]
Heyo 👋 This is a known issue, you can see those on the release of v14 here: https://our.umbraco.com/download/releases/1400
So I will go ahead and close this 😁 
Don't hesitate to report anything else you find 🐛
