### ISSUE TITLE
Cannot run a clean V14 installation with http:// scheme

### ISSUE THREAD

**Issue by olatov** [umbraco/Umbraco-CMS#16605]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

14.0.0

### Bug summary

Attempts to run a clean v14 installation using the http:// scheme result in an `invalid_request` type error.

An exising v13->v14 upgrade is affected too (can't access the backoffice after the upgrade).

### Specifics

```
[15:10:03 INF] The request URI matched a server endpoint: Authorization.
[15:10:03 INF] The response was successfully returned as a plain-text document: {
  "error": "invalid_request",
  "error_description": "This server only accepts HTTPS requests.",
  "error_uri": "https://documentation.openiddict.com/errors/ID2083"
}.
```

### Steps to reproduce

1. Install the v14 templates
```
dotnet new install Umbraco.Templates::14.0.0
```
2. Create a new project
```
dotnet new umbraco --name mysite14
```
3. Run the app using the http protocol
```
cd mysite14
dotnet run --urls http://localhost:5000
```
4. The installation wizard works ok, click through the steps.
5. The error occurs once the installation is finished.
The app will work ok (despite the obviuous cert error) if served with https://.

### Expected result / actual result

This worked fine in v13, therefore it is a breaking change for many scenarios where https wouldn't be served directly from Kestrel. 

Please advise if there's a fix / workaround / configuration change available, otherwise document a breaking change stating the https is required.

Thanks.

**Comment by elit0451** [comment]
Fixed in https://github.com/umbraco/Umbraco-CMS/pull/16614
