### ISSUE TITLE
Installer failed to pass database setup because of bad user password length validation

### ISSUE THREAD

**Issue by mrflo** [umbraco/Umbraco-CMS#16601]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

14.1.0-rc.preview.3

### Bug summary

On front-end: you can go to the next step and got an "unknown error" on the db setup page

In the console got:
Failed CreateUserStep, with the message: Could not reset password: The password must be at least 10 characters long

### Specifics

Happen on a mac machine during selection of SQL lite setup

### Steps to reproduce

1. fresh install
2. Introduce a user with email and a password length of 9 charachters like 123456789
3. its validated and you arrive on the DB setup step which is failing with an unknow error

### Expected result / actual result

Should have a warning on frontend that the password length is incorrect and refuse to go to the next step

**Comment by CarlSargunar** [comment]
Working on this
