### ISSUE TITLE
Templates can still be editable when using runtime mode Production

### ISSUE THREAD

**Issue by NguyenThuyLan** [umbraco/Umbraco-CMS#16622]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

14.0.0

### Bug summary

Templates in the BackOffice can still be editable when using runtime mode Production

### Specifics

The template in BackOffice (live env) can still be editable when using runtime mode Production
<img width="752" alt="image" src="https://github.com/umbraco/Umbraco-CMS/assets/116753400/2e7f6d4e-8ef0-4917-b881-fea3a2b2fb2c">
Templates are not supposed to be editable on live env as runtime compilation is not enabled and is set to Production.

### Steps to reproduce

Configuring the runtime mode: Production
Follow these steps from https://docs.umbraco.com/umbraco-cms/fundamentals/setup/server-setup/runtime-modes.
1. Config runtime mode to enable Development mode
2. Remove 2 properties from csproj project file: RazorCompileOnBuild and RazorCompileOnPublish
3. Enable Production mode in appsettings.Production.json
4. Open one template file in BackOffice (Live Environment), templates can still be editable 

### Expected result / actual result

Templates cannot be edited on live environment as runtime compilation is not enabled and is set to Production.
<img width="451" alt="image" src="https://github.com/umbraco/Umbraco-CMS/assets/116753400/502be229-a060-4479-a45a-6d69ac954a86">

**Comment by nick-hoang** [comment]
This bug is happening on version 13.4.1, too

**Comment by nielslyngsoe** [comment]
I'm closing this issue as it was fixed in this PR:
https://github.com/umbraco/Umbraco-CMS/pull/16923
