### ISSUE TITLE
Umbraco 14 - Logout screen does not show custom LoginBackgroundImage

### ISSUE THREAD

**Issue by jovanzlatanovic** [umbraco/Umbraco-CMS#16636]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

14.0.0

### Bug summary

Custom login image shows when logging in the website, but when a user is logged out it shows the default image.

### Specifics

Have setup custom login background image as in the [documentation](https://docs.umbraco.com/umbraco-cms/fundamentals/backoffice/login#custom-background-image-and-logo): 
```
  "Umbraco": {
    "CMS": {
      "Content": {
        "LoginBackgroundImage": "../Images/Login.png"
        }
     }
  }
```

On the login screen the image is visible, but when the user gets logged out (or logs out manually) the image is the default one:

![image](https://github.com/umbraco/Umbraco-CMS/assets/99445204/3f1e2f79-fce7-40c3-aad8-f57b57841d29)

Have tried to manually set the CSS `--umbraco-login-image` property, but unable to do so since unsure how to set css in **umbraco-package.json**, like we did in **package.manifest**.

### Steps to reproduce

1. Set a custom image.
2. Log out.

### Expected result / actual result

**Expected** to see custom login image on both login and logout screens.

**Actual**ly seeing custom login image only on the login screen.

---
_This item has been added to our backlog AB#41790_

**Comment by jovanzlatanovic** [comment]
Have also tried setting a custom theme but this doesn't appear to work as well, might be related:
```
{
  "$schema": "../../umbraco-package-schema.json",
  "name": "Custom CSS",
  "version": "0.0.0",
  "extensions": [
      {
          "type": "theme",
          "alias": "CustomLoginScreen",
          "name": "Custom Login Screen",
          "css": "/App_Plugins/custom-login-screen/custom-login-screen.css"
      }
  ]
}
```

With the css file being:
```
:root {
    --umb-login-image: url("../../wwwroot/login.png");
}
```

**Comment by elit0451** [comment]
Hi @jovanzlatanovic 👋 

Thanks for reaching out! I can indeed reproduce this - as you say, it seems like `/umbraco/logout` shows the default image, while `/umbraco/login` shows the configured one. We will have a look 🙂

**Comment by bassemelkadeem** [comment]
Dear @jovanzlatanovic,

in the below article you can change the background for logout please read this
https://docs.umbraco.com/umbraco-cms/fundamentals/backoffice/login 

and to be honest the only thing that won't work with me is only the css for login is not working using the below extension 
{
      "type": "appEntryPoint",
      "alias": "MyCustomLoginScreenCss",
      "js": "/App_Plugins/Login2/my-custom-login-screen.js",
      "name": "My Custom Login Screen Css"
    }

but work with me in logout
