### ISSUE TITLE
Content Service - can't create a node then Save and Publish - have to Save first

### ISSUE THREAD

**Issue by cheeseytoastie** [umbraco/Umbraco-CMS#16637]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

14.0.0

### Bug summary

If you create a new node then just use SaveAndPublish it fails to save and publish. 

If you use Save() first then SaveAndPublish it works

Simple example in a Razor view below - 

```
@using Umbraco.Cms.Web.Common.PublishedModels;
@inherits Umbraco.Cms.Web.Common.Views.UmbracoViewPage<Umbraco.Cms.Web.Common.PublishedModels.GeneralPage>
@inject IContentService ContentService
@using Umbraco.Cms.Core.Services
@{
	Layout = null;

    // parent page  where you want to add a child item.
    var parentId = Guid.Parse("0c6ff066-e843-4518-b90b-dd75b61d9561");

    var testNewPageThatWorks = ContentService.Create("New Page Test", parentId, "generalPage", -1);

    testNewPageThatWorks.SetValue("pageTitle", "This is a test");

    // Save and publish the child item - but if we save first then it works!!
    ContentService.Save(testNewPageThatWorks);
    ContentService.SaveAndPublish(testNewPageThatWorks);

    var testNewPageThatDoesntWork = ContentService.Create("New Page Test That Fails", parentId, "generalPage", -1);

    // Save and publish the child item
    ContentService.SaveAndPublish(testNewPageThatDoesntWork);

}
```

### Steps to reproduce

Run the razor above in a clean Umbraco install (obviously need the corresponding generalPage doc type.

### Expected result / actual result

I would expect two nodes - one from the save -> save and publish route then the second (which isn't created) just using saveandpublish. 

Noted by Treefiddy in the Discord and can recreate.

---
_This item has been added to our backlog AB#41896_

**Comment by Zeegaan** [comment]
Heyo 👋 This is expected behavior from V14 and onwards 😁 
We have obsoleted the `SaveAndPublish` method on the content service, at it is now split into separate `Save` & `Publish` methods 😁 

Here is the message: 
![image](https://github.com/umbraco/Umbraco-CMS/assets/70372949/535b3607-8ff8-4057-99bc-72b2adf94ac8)

**Comment by cheeseytoastie** [comment]
The method is marked as Deprecated not obsolete so I'd expect old behaviour. 

The documentation also has this as the recommended way. Both should be updated before this ticket is just closed IMHO
https://docs.umbraco.com/umbraco-cms/reference/management/using-services/contentservice

**Comment by Zeegaan** [comment]
It is deprecated, but the warning message warns about it no longer saving 😁 
Good point about documentation, you can create an issue on the Docs repo, to make sure it is handled here: https://github.com/umbraco/UmbracoDocs/issues

Or I can open it for you if you prefer that 💪

**Comment by biapar** [comment]
I confirm what @cheeseytoastie  said on Umbraco 14+.
Umbraco don't create the node If you call only SaveAndPublish.
You have to call Save and after SaveAndPublish.

![image](https://github.com/user-attachments/assets/043a954d-2f32-4dd3-b67b-267cbb1ce99d)
