### ISSUE TITLE
Restrict Public Access feature settings are not saved

### ISSUE THREAD

**Issue by NguyenThuyLan** [umbraco/Umbraco-CMS#16647]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

V14.0.0

### Bug summary

The Restrict Public Access feature settings for Content Pages are not saved.

### Specifics

The Restrict Public Access feature settings for Content Pages are not saved, it still shows a resetting form instead of previous saved setting
<img width="1116" alt="image" src="https://github.com/umbraco/Umbraco-CMS/assets/116753400/8524fe98-4f1c-446f-9690-3dd0ff56be56">

### Steps to reproduce

Let's see the video below:

https://github.com/umbraco/Umbraco-CMS/assets/116753400/10d8f733-d05f-408b-a077-893070463443

### Expected result / actual result

After setting up Restrict Public Access, the setting should be saved

**Comment by iOvergaard** [comment]
Hi,
I am happy to report that this issue has already been fixed and will be available with the upcoming 14.1 release. You can already test it out on the RC later this week.

Issue for reference: #16548
