### ISSUE TITLE
Doc type descriptions aren't pulling through to block list cards

### ISSUE THREAD

**Issue by philipdanielhayton** [umbraco/Umbraco-CMS#16642]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

14.0.0

### Bug summary

Descriptions on doc types like this:

![image](https://github.com/umbraco/Umbraco-CMS/assets/19938510/f3b1dd52-b004-45af-8b00-f96bf49fc62a)

Are not pulling through on the block list editor like they did in previous versions. It's not a killer feature, but it's helpful for editors.

![image](https://github.com/umbraco/Umbraco-CMS/assets/19938510/9effa9b6-39be-4510-ad5d-a1bcb30a2161)

### Steps to reproduce

1. Create a new element doc type, give it a description
2. Add the block to a block list editor
3. When using the block list the description will not show

### Expected result / actual result

It'd be good if the descriptions came through on the card as they did in previous versions.

**Comment by elit0451** [comment]
Hi @philipdanielhayton 👋 

Thanks for reaching out! I can indeed reproduce this - the element description is not shown in either the "Available Blocks" 
 section in the block list's settings, or when using the blocks to create new content. We will have a look 🙂 

And as a small note to the "Steps to reproduce" you need at least 2 blocks to see the element's description.
