### ISSUE TITLE
Umbraco 14 - Block Grid Area size does not save

### ISSUE THREAD

**Issue by deanleigh** [umbraco/Umbraco-CMS#16640]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

14

### Bug summary

Block Grid Area sizes are lost on save

### Steps to reproduce

Create a block grid
Create a layout
Resize an area in that layout
Save it
the size is lost

### Expected result / actual result

Sizes of areas would stay as saved

---
_This item has been added to our backlog AB#41872_

**Comment by JoJk0** [comment]
Duplicate of #16372 ?

**Comment by deanleigh** [comment]
I think it is the same but I am seeing the columns at 6 columns by default.
So even changing a single column from 6 to 12 and save it goes back to 6.

**Comment by elit0451** [comment]
Hi both 👋 thanks for reaching out!

We are already working on the column issue with the block grid, so I will close this as duplicate 🙂

**Comment by iOvergaard** [comment]
Hi everyone, this issue is related to the configuration of the **area** sizes in the block grid configuration, whereas #16372 concerns saving content blocks with varying sizes. I would reopen this issue to address both problems, even though they might be overlapping.

**Comment by nielslyngsoe** [comment]
Hi @deanleigh

Thanks for reporting this, I have checked your case with latest code base, thats v.14.1. and here it is working.

Just to be sure my approach that is working is the following:

- **Create a Document Type**,
- Append a Property with a DataType of Block Grid Editor with two Block Types.
- Block Type A, is allowed in the root and has two areas.
- Block Type B, is allowed in areas and is configured for 4 different column spans, 3,6,9,12.
- **Create a Document of that type**
- Create Block Type A
- Create two Block Type Bs inside Block Type A.
- Resize the Blocks so they become ColumnSpan 3 and thereby fits next to eachother.
- Save it
- And verify that document was saved.

**Comment by deanleigh** [comment]
Hey @nielslyngsoe that sounds like the same steps so great news if that is fixed

**Comment by huwred** [comment]
I'm not sure this is fixed, or a different issue. but if you just add a block element and give it allow in root and two areas of say size 8 and 4, then save. The block element just defaults back to 2 6 column areas

**Comment by iOvergaard** [comment]
Ok, this one should now be fixed in RC2 released yesterday. Go and check it out 👍

**Comment by huwred** [comment]
looks good :)
