### ISSUE TITLE
[v14] Block level validation UI missing

### ISSUE THREAD

**Issue by PerplexDaniel** [umbraco/Umbraco-CMS#16656]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

14.0.0

### Bug summary

In Block List / Block Grid there is no block level validation UI. If any of the blocks are invalid only the parent property itself (Block List / Block Grid) will be marked as invalid but you have no idea which block is invalid so this is not very user friendly. In addition, required properties are not marked with an asterisk (`*`) like in the past, and when you open each block the field that is invalid is not marked at all so you still have no idea what is wrong.

![image](https://github.com/umbraco/Umbraco-CMS/assets/24297947/d7f2459f-8e80-4126-85ab-7634ee785beb)
![image](https://github.com/umbraco/Umbraco-CMS/assets/24297947/3f72c57a-dfc5-4292-a414-20ff075125fb)
![image](https://github.com/umbraco/Umbraco-CMS/assets/24297947/0df609a6-953e-4dcb-866b-974055f9b66a)

We are currently looking into migrating our custom block editor (Perplex.ContentBlocks) to v14 and it seems there is actually code for block level validation. You can pass in a `dataPath` to `<umb-property-type-based-property>` which seems to work somewhat although the error message does not work properly and just shows `#validation_invalidEmpty`. 

![image](https://github.com/umbraco/Umbraco-CMS/assets/24297947/ea1522df-aaf5-483c-a738-a6d42e0290f4)

### Steps to reproduce

1. Create an Element Type with at least 1 mandatory property
2. Create a Block List datatype that uses the element type from step 1
3. Add this Block List as a property on one of your regular doctypes
4. Create some blocks without entering any data
5. Save and Publish
6. Observe a result similar to this:

![image](https://github.com/umbraco/Umbraco-CMS/assets/24297947/e79efb18-aad8-4a92-b11a-e33f87e92feb)

When opening a block the invalid properties are not marked either so you really have no idea how to fix it and what to fix.

**Comment by NguyenThuyLan** [comment]
Thanks, @PerplexDaniel for reporting this issue. We are working on this.
