### ISSUE TITLE
UmbracoContext.PublishedRequest returns null

### ISSUE THREAD

**Issue by TheFogOfWar1** [umbraco/Umbraco-CMS#16662]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

13.3.2; 14.0.0

### Bug summary

When using the IUmbracoContextAccessor and getting the context the context.PublishedRequest is null. 

### Specifics

This problem occurs when using a Microsoft.AspNetCore.Mvc.Controller and SurfaceController, and possibly more places. 

### Steps to reproduce
Implement the mvc controller and the surfacecontroller. Test the endpoints. 

` 
public class ContextAccessorDomainNull : Controller
 {
     private readonly IUmbracoContextAccessor _umbracoContextAccessor;
     private readonly IUmbracoContextFactory _umbracoContextFactory;

     public ContextAccessorDomainNull(IUmbracoContextAccessor umbracoContextAccessor, IUmbracoContextFactory umbracoContextFactory)
     {
         _umbracoContextAccessor = umbracoContextAccessor;
         _umbracoContextFactory = umbracoContextFactory;
     }

     [HttpGet("Test")]
     public IActionResult ThrowsNull()
     {
         _umbracoContextAccessor.TryGetUmbracoContext(out var context);

         if (context?.PublishedRequest == null)
         {
             throw new Exception("no context");
         }

         return Ok();
     }

     [HttpGet("TestEnsure")]
     public IActionResult EnsureThrowsNull()
     {
         using var context = _umbracoContextFactory.EnsureUmbracoContext();

         _umbracoContextAccessor.TryGetUmbracoContext(out var umbracoContext);

         if (umbracoContext?.PublishedRequest == null)
         {
             throw new Exception("no context");
         }

         return Ok();
     }
 }
 `

Surfacecontroller 
` public class ContextSurfaceController : SurfaceController
 {
     private readonly IUmbracoContextAccessor _umbracoContextAccessor;
     private readonly IUmbracoContextFactory _umbracoContextFactory;

     public ContextSurfaceController(IUmbracoContextAccessor umbracoContextAccessor, IUmbracoDatabaseFactory databaseFactory, ServiceContext services, AppCaches appCaches, IProfilingLogger profilingLogger, IPublishedUrlProvider publishedUrlProvider, IUmbracoContextFactory umbracoContextFactory) : base(umbracoContextAccessor, databaseFactory, services, appCaches, profilingLogger, publishedUrlProvider)
     {
         _umbracoContextAccessor = umbracoContextAccessor;
         _umbracoContextFactory = umbracoContextFactory;
     }

     [HttpGet("surface/Test")]
     public IActionResult ThrowsNull()
     {
         _umbracoContextAccessor.TryGetUmbracoContext(out var context);

         if (context?.PublishedRequest == null)
         {
             throw new Exception("no context");
         }

         return Ok();
     }

     [HttpGet("surface/TestEnsure")]
     public IActionResult EnsureThrowsNull()
     {
         using var context = _umbracoContextFactory.EnsureUmbracoContext();

         _umbracoContextAccessor.TryGetUmbracoContext(out var umbracoContext);

         if (umbracoContext?.PublishedRequest == null)
         {
             throw new Exception("no context");
         }

         return Ok();
     }
 }
`

### Expected result / actual result

The expected result should be that the published request is not null and it can be used.

**Comment by bergmania** [comment]
Sounds related to what have been fixed in either 13.3.3 or 13.4 and 14.1

**Comment by bergmania** [comment]
@TheFogOfWar1  thanks for checking. The fixes from 13.4 is part of 14.1, so I'll close the issue
