### ISSUE TITLE
[BUG]: Include types for TinyMCE

### ISSUE THREAD

**Issue by enkelmedia** [umbraco/Umbraco-CMS#16678]
When building a `tinyMcePlugin` the editor complains about the return type:

![image](https://github.com/umbraco/Umbraco.CMS.Backoffice/assets/1782524/542eaf75-b1e1-40c4-b7bf-086fd4364c9b)

So I figured I'll provide strongly typed objects but it seems like the types are not included in the `@umbraco-cms/backoffice` package?

![image](https://github.com/umbraco/Umbraco.CMS.Backoffice/assets/1782524/a861ffa9-c05f-4cbf-b485-a72b3f4a3e00)

Is this by intension and what would be the right workaround?

**Comment by madsrasmussen** [comment]
Hi @enkelmedia 

Thanks for the report. I am glad to see you found a workaround. Since TinyMCE will be replaced by TipTap and will not be included in the core package from version 16, installing the additional dependency is a reasonable workaround.

Thanks!
