### ISSUE TITLE
[BUG]: Umbraco14.0..0-beta2 Save Media throws error WITHOUT a Media name 

### ISSUE THREAD

**Issue by rsoeteman** [umbraco/Umbraco-CMS#16675]
**Describe the bug**
When creating an image media type (WITHOUT a Media name )and click save the error is 

One or more validation errors occurred.
Bad Request instead of Media item name is required

**To Reproduce**
1. Create Image Media
2. Upload image
3. Click save

---
_This item has been added to our backlog AB#41937_

**Comment by nielslyngsoe** [comment]
Thanks @rsoeteman 
This will be fixed by https://github.com/umbraco/Umbraco-CMS/pull/17591 and will be released as part of 15.2
