### ISSUE TITLE
[BUG]: UmbVariantableWorkspaceContextInterface  is marked as obsolete but suggested interface `UmbVariantWorkspaceContextInterface`  does not exist

### ISSUE THREAD

**Issue by KevinJump** [umbraco/Umbraco-CMS#16689]
**Describe the bug**

`UmbVariantableWorkspaceContextInterface`   is marked as obsolete in RC1

https://github.com/umbraco/Umbraco.CMS.Backoffice/blob/683187c28a0f923f320b075f35b88cd9cd07c2bd/src/packages/core/workspace/contexts/tokens/variant-dataset-workspace-context.interface.ts#L33-L37

The deprecation notice says to Use `UmbVariantWorkspaceContextInterface` instead, but this does not exist in the code base. ? 

either: 
the notice is wrong and there is another interface somewhere? or this interface is missing ?

**Comment by iOvergaard** [comment]
The correct interface to replace it is called `UmbVariantDatasetWorkspaceContext` and that should already be exported. This is also the interface you get when consuming `UMB_VARIANT_WORKSPACE_CONTEXT` as @ksolberg points out. The deprecation notice is wrong.
