### ISSUE TITLE
[BUG]: Property can be created without an editor

### ISSUE THREAD

**Issue by sebpdev** [umbraco/Umbraco-CMS#16686]
**Describe the bug**
When adding a new property to a document type, there is no validation for adding an editor and thus the property can be saved without one.

**To Reproduce**
1. Go to your document type in Umbraco
2. Click on add property
3. Fill out the information, but skip selecting an editor.
4. Save anyway and there is validation to select an editor.

**Expected behavior**
Not to be able to create a property without and editor and get validation errors when trying to.

**Screenshots**
![image](https://github.com/umbraco/Umbraco.CMS.Backoffice/assets/118893112/8c17bf33-afcf-4ba8-b23f-01966cc12717)
![image](https://github.com/umbraco/Umbraco.CMS.Backoffice/assets/118893112/e5e1b8d3-a2bb-4753-9fbd-cf07250edbd5)
![image](https://github.com/umbraco/Umbraco.CMS.Backoffice/assets/118893112/b6b81cc6-c15f-4b1b-a2a9-d94b380c117a)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Brave
 - Version: 1.64.116 Chromium: 123.0.6312.105 (Official Build) (64-bit)

**Additional context**
For the record, there does not seem to be any validation for the name or the alias either (*yet*). And it's not possible to actually save the document type after adding an empty property.

---
_This item has been added to our backlog AB#42506_

**Comment by iOvergaard** [comment]
Related to #16168
