### ISSUE TITLE
[BUG]: Umb.PropertyEditorUi.DatePicker doesn't reset when the underlying model is reset

### ISSUE THREAD

**Issue by mattbrailsford** [umbraco/Umbraco-CMS#16693]
**Describe the bug**
If I have a `Umb.PropertyEditorUi.DatePicker` property rendering in a `umb-property-dataset`, and I reset the properties bound to that dataset, most property editors reset their value, but the date picker doesn't appear to do so.

This should also reset it's value back to the default if the model changes in this way.

**To Reproduce**
1. Create an editor UI that renders an `umb-property` that uses a `Umb.PropertyEditorUi.DatePicker` inside a `umb-property-dataset`
2. Setup a state to hold the property values
3. Bind the `umb-property-dataset` to the property values collection
4. Setup a button that when clicked, resets the property values collection to `[]`

**Expected behavior**
I would expect the date picker to reset

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Brave (Chromium)
 - Version [Version 1.65.123](https://brave.com/latest/)

**Comment by iOvergaard** [comment]
I just tested this on 14.1.1 and was able to clear the value through the `UMB_PROPERTY_DATASET_CONTEXT`. I believe it was fixed because of https://github.com/umbraco/Umbraco.CMS.Backoffice/pull/2115, which got released in 14.1.1, but it could have been something else. I'll mark this as completed.
