### ISSUE TITLE
[BUG]: Property descriptions and tabindex

### ISSUE THREAD

**Issue by iOvergaard** [umbraco/Umbraco-CMS#16695]
It seems this has a side-effect that it now focus every property description, e.g. in configuration of datatypes.

![image](https://github.com/umbraco/Umbraco.CMS.Backoffice/assets/2919859/2327d5c1-c8ac-4762-996e-4505b8d141fa)

But also in content and media. So if using descriptions or properties, it requires a lot on tabs to get to the input editors.

![image](https://github.com/umbraco/Umbraco.CMS.Backoffice/assets/2919859/fca0d420-8745-495e-996f-394da3e2f7b1)

It should possible only set `tabindex` when it need to focus - or `tabindex="-1"` when it shouldn't focus.

_Originally posted by @bjarnef in https://github.com/umbraco/Umbraco.CMS.Backoffice/issues/1879#issuecomment-2131283961_

**Comment by bjarnef** [comment]
@iOvergaard it seems this has been resolved with latest changes in backoffice repository?
