### ISSUE TITLE
[BUG]: Multi-url-picker component not showing when extending backoffice

### ISSUE THREAD

**Issue by BishalTimalsina12** [umbraco/Umbraco-CMS#16699]
**Describe the bug**
when extending umbraco backoffice, when  using multi url picker property editor component, its not showing 
**To Reproduce**
1.when extending backoffice, use 
 umb-input-multi-url
/umb-input-multi-url 

**Expected behavior**
it showld show choose field, and upon clicking i should be able to add link like its usage
**Screenshots**
![Screenshot 2024-06-25 152052](https://github.com/umbraco/Umbraco.CMS.Backoffice/assets/143370089/8df857a0-6b3f-46ca-84bb-a2fe1f549dd9)

**Desktop (please complete the following information):**
OS: windows
Browser: Microsoft Edge
Version : 126.0.2592.68 (Official build) (64-bit)
**Additional context**

**Comment by iOvergaard** [comment]
Hello @BishalTimalsina12, and thanks for testing!

We have implemented a fix for this, which will end up in version 14.2.

When the bug fix is released, you may need to import the module somewhere in your code to be able to use the input component from your custom section:

```js
import '@umbraco-cms/backoffice/multi-url-picker';
```

**Comment by BishalTimalsina12** [comment]
@loivsen @iOvergaard  great work!
