### ISSUE TITLE
[BUG]:  'The specified media type was not found' when uploading image after creating folder in Umbraco 14

### ISSUE THREAD

**Issue by SarojShresthaa** [umbraco/Umbraco-CMS#16701]
**Describe the bug**
When creating a new folder and uploading an image in Umbraco 14, the operation fails, and an error message is displayed: "The specified media type was not found." This prevents the image from being uploaded and stored in the  created folder.

1. Navigate to the Settings section in Umbraco 14.
2. Create a new document type.
3. Add an image media picker to the new document type.
4. Create a new content item using the created document type.
5. In the content editor, click on the image media picker and choose to upload an image.
6. Attempt to upload an image.
7. Observe the error message: "The specified media type was not found."

**Expected behavior**
The image should be successfully uploaded and selected without any errors.

Actual Behavior
The upload operation fails with the error message: "The specified media type was not found."

https://github.com/umbraco/Umbraco.CMS.Backoffice/assets/145342744/c9fd6795-9049-45e5-b704-486cecacf1df

**Desktop (please complete the following information):**
 - OS: [Windows 10]
 - Browser [chrome]
 - Version [126.0.6478.126 (Official Build) (64-bit)]

**Additional context**

---
_This item has been added to our backlog AB#42180_

**Comment by NguyenThuyLan** [comment]
Thanks, @SarojShresthaa for reporting this.
The error happens on this API: /umbraco/management/api/v1/media-type/{id}/allowed-children
<img width="1203" alt="image" src="https://github.com/umbraco/Umbraco-CMS/assets/116753400/550f2733-1b23-4dab-a377-96c6f232c686">
