### ISSUE TITLE
v14.1.0-rc backoffice doesn't ship with type declarations

### ISSUE THREAD

**Issue by rickbutterfield** [umbraco/Umbraco-CMS#16719]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

14.1.0-rc

### Bug summary

When upgrading a package project to use the new v14.1.0-rc package from npm, the built files in `node_modules` don't have associated type declarations.

### Specifics

Error as seen in VS Code when the npm package has been upgraded:

```
Could not find a declaration file for module '@umbraco-cms/backoffice/auth'. '/Users/rickbutterfield/Developer/Umbraco.Community.BlockPreview/src/Umbraco.Community.BlockPreview/assets/node_modules/@umbraco-cms/backoffice/dist-cms/packages/core/auth/index.js' implicitly has an 'any' type.
  If the '@umbraco-cms/backoffice' package actually exposes this module, try adding a new declaration (.d.ts) file containing `declare module '@umbraco-cms/backoffice/auth';`
```

### Steps to reproduce

Upgrade a project to use v14.1.0-rc on the front end, and confirm that none of the imports from `@umbraco-cms/backoffice` work.

**Comment by iOvergaard** [comment]
The fix has been merged and can be verified on the [MyGet NPM feed](https://www.myget.org/feed/umbracoprereleases/package/npm/@umbraco-cms/backoffice/14.1.0-rc2) at the moment. It will then land on npmjs.com later on when we release RC2.
