### ISSUE TITLE
[BUG] : RTE input component not showing

### ISSUE THREAD

**Issue by BishalTimalsina12** [umbraco/Umbraco-CMS#16717]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

14.0.0

### Bug summary

so im extending backoffice i used RTE component to show the text field, but its not loading as expected.

### Steps to reproduce

![Screenshot 2024-07-01 123719](https://github.com/umbraco/Umbraco-CMS/assets/143370089/f131de08-67c8-4806-86d7-efbdc7e05c11)

### Expected result / actual result

it should show a text area field with the editors.

its not showing anything, blank_

**Comment by nielslyngsoe** [comment]
Hi @BishalTimalsina12 

I assume what happens here is that the web component of `umb-input-tiny-mce` is not loaded. This can be used via importing it via a import map. (As our web components uses Shadow-DOM it can be seen via Devs Tools, discovering if a element got a shadow-dom. If not, then its not loaded)

But from looking at your screenshot, it seems more like you want to implement a few Property Editors, and not just the input component of such. Doing so will give you a way more uniform experience, aligned with the rest of Backoffice, including getting Property Actions for your Properties etc.

As an effect of this issue, I created a first version of a Documentation Article describing how to implement Property Editor UIs in your own UI. And I hope that was the answer you would be looking for:
https://github.com/umbraco/UmbracoDocs/pull/6229/files

Let me know how it goes, thanks in advance :-)

**Comment by BishalTimalsina12** [comment]
@nielslyngsoe 
but is using property dataset is a good way for sending string data to server?, see i have this form and this field which i want the UI to be as RTE, so suppose body content is that field which stores string or just <p> , i used property data set, and its using some sort of object, not what i was looking for.

**Comment by BishalTimalsina12** [comment]
a fix like this might solve the issue hence, i can use component: https://github.com/umbraco/Umbraco.CMS.Backoffice/pull/2048/files
