### ISSUE TITLE
Cancelling ContentTypeSavingNotification is not propagated to UI

### ISSUE THREAD

**Issue by PragmaticIT** [umbraco/Umbraco-CMS#16711]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

14.0.0

### Bug summary

I have created a set of notification handlers to catch the situation when user tries to delete/modify my content types. 
Following is the handler code:
```
public void Handle(ContentTypeSavingNotification notification)
{
    if(notification.SavedEntities.Any(x=>_protectedDocumentTypeAliases.Contains(x.Alias)))
        notification.CancelOperation(
            new EventMessage(
                "Error",
                "Operation not allowed. This document type is part of the package.",
                EventMessageType.Error));
}
```
then it is registered in a composer:
`            builder.AddNotificationHandler<ContentTypeSavingNotification, NotificationHandler>();
`
The saving operation is cancelled properly, however user does not receive the message (I'd expect error notification and the given message should be displayed). 

### Steps to reproduce

dotnet new install Umbraco.Templates
(downloads Umbraco version 14.0.0)
dotnet new umbraco --name MyProject
then open VS2022, run the project, provide initial values to the wizard and initialize new DB. Then create some document type. Stop the project and create a new NotificationHandler class add the the following method:
```
public void Handle(ContentTypeSavingNotification notification)
{
    notification.CancelOperation(
        new EventMessage(
            "Error",
            "Operation not allowed. This document type is part of the package.",
            EventMessageType.Error));
}
```
 then create a new Composer class and add the handler to Umbraco. 
When run, try to modify previously created document type (ie. name). The pop-up says "Success" but when you refresh the page changes are not applied

### Expected result / actual result

In proevious Umbraco versions (11) the above code signaled problem to User and message was displayed. I'd expect it to be the same in 14.

**Comment by nikolajlauridsen** [comment]
Hi @PragmaticIT there's a fix for the issue here #16714 which handles the backend part. 

After this change the UI correctly show the message if it's a new content type, however when updating existing content types, however when updating the document type it simply shows 'bad request':

![image](https://github.com/umbraco/Umbraco-CMS/assets/16456704/748aaafc-e69b-4271-ba75-b17a68a2f5e7)

This however is a frontend issue where the `Umb-Notifications` isn't displayed, so I'l go ahead and re-tag this so the frontend team can have a look 😄
