### ISSUE TITLE
Umbraco 14 - "The specified 'redirect_uri' is not valid for this client application." error when trying to login after a certain time period

### ISSUE THREAD

**Issue by jovanzlatanovic** [umbraco/Umbraco-CMS#16741]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

14.0.0

### Bug summary

Getting an `error:invalid_request` after leaving an Umbraco site running for a while when trying to login. Error appears for any login method (local and SSO).

### Specifics

Might be related to: https://github.com/umbraco/Umbraco-CMS/issues/16179; but I am not visiting the site behind a proxy.

Error image:
![image](https://github.com/umbraco/Umbraco-CMS/assets/99445204/11f0b7a1-d089-4adc-bb38-857fa5abe33e)

### Steps to reproduce

It appears to happen randomly after leaving the website running after a while.

Try to login after an unspecified amount of time.

### Expected result / actual result

Expecting to be able to login, actual is error returned in json format.

**Comment by AndersBrohus** [comment]
Try set the "BackOfficeHost" and "UmbracoApplicationUrl" - We do not experience it after those two where set :)

```
  "Umbraco": {
    "CMS": {
      "WebRouting": {
        "UmbracoApplicationUrl": "SET YOUR URL"
      },
      "Security": {
        "BackOfficeHost": "SET YOUR URL"
      }
    }
  },
```

**Comment by jovanzlatanovic** [comment]
Hi @AndersBrohus, that seems to have fixed it. Didn't get the error anymore since this morning so I'm guessing it's good (for now).

Thanks for the help! 👏 

I'll close the issue since there is a solution, but if anyone feels like this needs fixing feel free to reopen it. :)

**Comment by StudioBravo** [comment]
Hi all, we are still seeing this error even though we've set both BackOfficeHost and UmbracoApplicationUrl. 
We are running the latest 14.3.0

**Comment by jovanzlatanovic** [comment]
Hi @StudioBravo see if you're using an environment JSON (appsettings.Release.json) and if it is actually being applied to the `appsettings.json`.

In my case the issue came back but it was a fact of the appsettings.Release.json not being applied for some reason. 🤷‍♂️

**Comment by StudioBravo** [comment]
Hi @jovanzlatanovic, thank you for your message. We are not using appsettings.Release.json. We use config transformation during deployment. 

Our situation is that the site works fine for a while and all of a sudden the issue pops up. Only way to solve it is to restart.

**Comment by jovanzlatanovic** [comment]
The error appears to occur when multiple environments are hitting the same database, as the database saves the `redirect_url` for the first users login. Afterwhich if a person logs in from a different domain it saves that `redirect_url` which bricks the first one, after this point the first domain will stop working and will return the above mentioned error.

The resoution seems to be to **always use one database per environment**.

**Comment by dutchbreeze** [comment]
I doubt that this is the solution, but i'm happy to investigate. I'm wondering where is this redirect_url saved?

**Comment by jovanzlatanovic** [comment]
Hi @dutchbreeze, it would be in the `umbracoOpenIddictApplications` table.

Running an environment with a certain database sets the correct **RedirectUris** value.

After I try to run a different environment (on a different URL) the row with the `umbraco-back-office` value in the table gets the `RedirectUris` overwritten with the different environment.

I believe the resaon sites work again after restarting is due to the fact when we run an environment again the value will get overwritten again.

**Comment by Strike3Digital** [comment]
> The error appears to occur when multiple environments are hitting the same database, as the database saves the `redirect_url` for the first users login. Afterwhich if a person logs in from a different domain it saves that `redirect_url` which bricks the first one, after this point the first domain will stop working and will return the above mentioned error.
> 
> The resoution seems to be to **always use one database per environment**.
@jovanzlatanovic

That actually makes sense. But as this is on the dev server we are updating locally and want that to be reflected for everyone.
Also, I really don't think that is good because there are cases where I might want different URLs to access the backend even though there is one database.
Maybe this should be explicit if you should NEVER do this.

**Comment by dutchbreeze** [comment]
@Strike3Digital 
It seems that a reboot **does** affect the database. The redirect url seems to be reset after a reboot. However, this is our opinion at first glance and is not thoroughly tested.

**Comment by akarkaselis** [comment]
Any updates on this? 

As a workaround I tried overriding the OpenIddictApplicationManager's ValidateRedirectUriAsync method to return true in local and dev environments. Unfortunately, I haven't had success with this approach yet. I might have to manually set that redirect_uri in the database, but after that I'm afraid I'll be out of ideas.

**Comment by elkil** [comment]
this worked for me - I added an AFTER INSERT Trigger to the [umbracoOpenIddictApplications]  table
the trigger sets RedirectUris and PostLogoutRedirectUris to array with all env urls
WHERE ClientId = 'umbraco-back-office'

**Comment by dutchbreeze** [comment]
@elkil 
Thanks for sharing. How exactly do you apply your trigger environment dependent? Or do you set multiple URL's (is that possible)?

**Comment by elkil** [comment]
After some more testing seems like the trigger wasn't enough and I needed to add a job that runs every x time and run stored procudure with the follwing query for my dev env : (for every DB i put all domain accessing that DB, you can add as many urls to the array's) 
```
UPDATE [dbo].[umbracoOpenIddictApplications]
  SET RedirectUris = '["https://myDomain/umbraco/oauth_complete","https://localhost:44383/umbraco/oauth_complete"]',
      PostLogoutRedirectUris = '["https://myDomain/umbraco/oauth_complete","https://myDomain/umbraco/logout","https://localhost:44383/umbraco/oauth_complete","https://localhost:44383/umbraco/logout"]'
  WHERE ClientId = 'umbraco-back-office'
```

**Comment by dutchbreeze** [comment]
Thanks for sharing @elkil. Could be used as a fix. Somewhat typical that the UmbracoApplicationUrl property cannot be set to multiple url's, but read-back does read multiple url's. I did not check the source code on the why's and how's on that. Anyway, thanks again!

**Comment by dutchbreeze** [comment]
To get rid of timing or dependency issues, I've just created a composer that adds the uris. The functionality is tested, works, but the code is ment to be keep one going. The final uris should not be in code, and the code should be heavily tested and inspected before usage in production.

```
using Umbraco.Cms.Core.Composing;
using OpenIddict.Abstractions;
using Microsoft.Extensions.DependencyInjection;

namespace Core.Composers;

public class RegisterRedirectUrisFixComposer : ComponentComposer<RedirectUrisFixComposer> { }

public class RedirectUrisFixComposer(IServiceProvider serviceProvider) : IComponent
{
    public void Initialize()
    {
        FixRedirectUris();
    }

    public void Terminate()
    {
        //throw new NotImplementedException();
    }

    private async void FixRedirectUris(CancellationToken cancellationToken = default)
    {
        var domains = new List<string>
        {
            "https://localhost:57975",
            "https://dutchbreeze.com"
        };

        using (var scope = serviceProvider.CreateScope())
        {
            var applicationManager = scope.ServiceProvider.GetRequiredService<IOpenIddictApplicationManager>();
            
            //delete the client if present, otherwise error while adding
            var client = await applicationManager.FindByClientIdAsync(Umbraco.Cms.Core.Constants.OAuthClientIds.BackOffice, cancellationToken);

            if (client is not null)
            {
               await applicationManager.DeleteAsync(client, cancellationToken);
            }

            //add the clients
            await applicationManager.CreateAsync(BackofficeOpenIddictApplicationDescriptor(domains), cancellationToken);
        }
    }


    //The Umbraco BackofficeOpenIddictApplicationDescriptor method allows only a single URI
    public OpenIddictApplicationDescriptor BackofficeOpenIddictApplicationDescriptor(IEnumerable<string> domains)
    {
        if (domains == null || !domains.Any())
        {
            throw new ArgumentException("Domains cannot be null or empty.", nameof(domains));
        }

        var descriptor = new OpenIddictApplicationDescriptor
        {
            DisplayName = "Umbraco back-office access",
            ClientId = Umbraco.Cms.Core.Constants.OAuthClientIds.BackOffice,
            ClientType = OpenIddictConstants.ClientTypes.Public,
            Permissions =
        {
            OpenIddictConstants.Permissions.Endpoints.Authorization,
            OpenIddictConstants.Permissions.Endpoints.Token,
            OpenIddictConstants.Permissions.Endpoints.Revocation,
            OpenIddictConstants.Permissions.GrantTypes.AuthorizationCode,
            OpenIddictConstants.Permissions.GrantTypes.RefreshToken,
            OpenIddictConstants.Permissions.ResponseTypes.Code,
        }
        };

        // Add RedirectUris
        foreach (var domain in domains)
        {
            descriptor.RedirectUris.Add(new Uri($"{domain}/umbraco/oauth_complete"));
        }

        // Add PostLogoutRedirectUris
        foreach (var domain in domains)
        {
            descriptor.PostLogoutRedirectUris.Add(new Uri($"{domain}/umbraco/oauth_complete"));
            descriptor.PostLogoutRedirectUris.Add(new Uri($"{domain}/umbraco/logout"));
        }

        return descriptor;
    }

}
```

**Comment by akarkaselis** [comment]
I just decided to override the validation for local and dev environments until the site is in production. It's been a real headache having to restart the site every time we wanted to access the backoffice from localhost or dev. With 2-3 devs working on the site, it was downright impossible.

If you inherit from "OpenIddictApplicationManager<OpenIddictEntityFrameworkCoreApplication>" you can override the "ValidateRedirectUriAsync" (and "ValidatePostLogoutRedirectUriAsync"), check the environment and simply return true. 

Obviously, this needs to be taken out when the site will go into production.

**Comment by dutchbreeze** [comment]
@akarkaselis Sounds great! Are you willing to share this code, so we don't have to develop and test it ourselves? Cheers!

**Comment by akarkaselis** [comment]
@dutchbreeze 

So basically, if you put this in your startup.cs, you're able to use a custom OpenIddictApplicationManager

```
if (!environment.IsProduction())
{
  services.AddOpenIddict()
    .AddCore(options =>
    {
      options.ReplaceApplicationManager<CustomOpenIddictApplicationManager>();
    });
}
```
Just make sure to place it before services.AddUmbraco()

I also see in the PR that I added these two lines in the startup's configure:
```
application.UseAuthorization();
application.UseCertificateForwarding();
```

I don't remember if they truly had an impact.

And then the custom manager is pretty simple, check if the link is localhost or your dev environment and return true.

```
public class CustomOpenIddictApplicationManager : OpenIddictApplicationManager<OpenIddictEntityFrameworkCoreApplication>
{
  private readonly IWebHostEnvironment _environment;
  private readonly ILogger<OpenIddictApplicationManager<OpenIddictEntityFrameworkCoreApplication>> _logger;

  public CustomOpenIddictApplicationManager(
      IOpenIddictApplicationCache<OpenIddictEntityFrameworkCoreApplication> cache,
      ILogger<OpenIddictApplicationManager<OpenIddictEntityFrameworkCoreApplication>> logger,
      IOptionsMonitor<OpenIddictCoreOptions> options,
      IOpenIddictApplicationStoreResolver resolver,
      IWebHostEnvironment environment)
      : base(cache, logger, options, resolver)
  {
    _environment = environment;
    _logger = logger;
  }

  public override ValueTask<bool> ValidateRedirectUriAsync(OpenIddictEntityFrameworkCoreApplication application, string address, CancellationToken cancellationToken)
  {
    if (!_environment.IsProduction())
    {
      var uri = new Uri(address);
      if (uri.Host.Equals("localhost", StringComparison.OrdinalIgnoreCase) ||
        uri.Host.Equals("host.docker.internal", StringComparison.OrdinalIgnoreCase))
      {
        return ValueTask.FromResult(true);
      }

      if (address.StartsWith(<your-dev-environment-url>))
      {
        return ValueTask.FromResult(true);
      }
    }

    return base.ValidateRedirectUriAsync(application, address, cancellationToken);
  }

  public override ValueTask<bool> ValidatePostLogoutRedirectUriAsync(OpenIddictEntityFrameworkCoreApplication application, string address, CancellationToken cancellationToken)
  {
    if (!_environment.IsProduction())
    {
      var uri = new Uri(address);
      if (uri.Host.Equals("localhost", StringComparison.OrdinalIgnoreCase) ||
          uri.Host.Equals("host.docker.internal", StringComparison.OrdinalIgnoreCase))
      {
        return ValueTask.FromResult(true);
      }

      if (address.StartsWith(<your-dev-environment-url>))
      {
        return ValueTask.FromResult(true);
      }
    }

    return base.ValidatePostLogoutRedirectUriAsync(application, address, cancellationToken);
  }
}
```

I also noticed that I let this part in the appsettings while looking for a solution for appsetting.local.json and appsettings.dev.json 
I don't know if they're absolutely necessary, but I didn't feel like wasting more time testing it out.

```
"Umbraco": {
  "CMS": {
   _...other things_
    "Security": {
      "BackOfficeHost": "[url to your local or dev environment ]",
      "AllowConcurrentLogins": true
    },
    "WebRouting": {
      "UmbracoApplicationUrl": "[url to your local or dev environment]"
    }
  },
_...rest of the things_
```

Obviously this will be taken out when we deploy in production. I suggest everyone does the same. We have additional security measures to control access to our development environments.

**Comment by dutchbreeze** [comment]
@akarkaselis I did not have the change to test, but will in the next couple of days. I'll let you know the outcome. Thanks a lot for sharing!

**Comment by umbraco-dev** [comment]
@akarkaselis Just implemented this one, and at first glance it seems to work! Great! Thanks again for sharing!

Just to add up, I dont think these do anything:
application.UseAuthorization();
application.UseCertificateForwarding();

I'll let you know if I find anything while testing!

**Comment by dutchbreeze** [comment]
@akarkaselis  Just implemented this one, and at first glance it seems to work! Great! Thanks again for sharing!

Just to add up, I dont think these do anything:
application.UseAuthorization();
application.UseCertificateForwarding();

I'll let you know if I find anything while testing!

**Comment by bjornnorlen** [comment]
This is still an issue in Umbraco 15.2.1. Does anyone know if there is a solution in sight?

**Comment by umbraco-dev** [comment]
Yes, this is still an issue. I've seen no solutions within the official channels.

**Comment by dutchbreeze** [comment]
Yes, this is still an issue. I've seen no solutions within the official channels.

**Comment by dlidstrom** [comment]
I had this issue with a new Umbraco 15 project. Solution was two-fold:
- add app url as mentioned in this thread (two settings: `BackOfficeHost` and `UmbracoApplicationUrl`)
- visit the site using https while accessing the backoffice

This resolved the issue for me.

**Comment by dutchbreeze** [comment]
@dlidstrom registering that url only works after de application restarts. If you access from local/remote, only one will work.

**Comment by PMendesWebDev** [comment]
This is still an issue in v15.4.3. Didn't check v16.0.0 but comparing the release notes it seems this wasn't addressed.

Wouldn't the solution be, like most providers that follow OIDC protocol, to have the possibility to configure - in appSettings.json CMS:Secutiry or something like that - the application's allowed urls. If the settings is empty, use the current host.

**Comment by akarkaselis** [comment]
@PMendesWebDev if you need it to make it work until an official correction is provided, you can use the override I posted here:


> 
> So basically, if you put this in your startup.cs, you're able to use a custom OpenIddictApplicationManager
> 
> if (!environment.IsProduction())
> {
>   services.AddOpenIddict()
>     .AddCore(options =>
>     {
>       options.ReplaceApplicationManager<CustomOpenIddictApplicationManager>();
>     });
> }
> Just make sure to place it before services.AddUmbraco()
> 
> I also see in the PR that I added these two lines in the startup's configure:
> 
> application.UseAuthorization();
> application.UseCertificateForwarding();
> I don't remember if they truly had an impact.
> 
> And then the custom manager is pretty simple, check if the link is localhost or your dev environment and return true.
> 
> public class CustomOpenIddictApplicationManager : OpenIddictApplicationManager<OpenIddictEntityFrameworkCoreApplication>
> {
>   private readonly IWebHostEnvironment _environment;
>   private readonly ILogger<OpenIddictApplicationManager<OpenIddictEntityFrameworkCoreApplication>> _logger;
> 
>   public CustomOpenIddictApplicationManager(
>       IOpenIddictApplicationCache<OpenIddictEntityFrameworkCoreApplication> cache,
>       ILogger<OpenIddictApplicationManager<OpenIddictEntityFrameworkCoreApplication>> logger,
>       IOptionsMonitor<OpenIddictCoreOptions> options,
>       IOpenIddictApplicationStoreResolver resolver,
>       IWebHostEnvironment environment)
>       : base(cache, logger, options, resolver)
>   {
>     _environment = environment;
>     _logger = logger;
>   }
> 
>   public override ValueTask<bool> ValidateRedirectUriAsync(OpenIddictEntityFrameworkCoreApplication application, string address, CancellationToken cancellationToken)
>   {
>     if (!_environment.IsProduction())
>     {
>       var uri = new Uri(address);
>       if (uri.Host.Equals("localhost", StringComparison.OrdinalIgnoreCase) ||
>         uri.Host.Equals("host.docker.internal", StringComparison.OrdinalIgnoreCase))
>       {
>         return ValueTask.FromResult(true);
>       }
> 
>       if (address.StartsWith(<your-dev-environment-url>))
>       {
>         return ValueTask.FromResult(true);
>       }
>     }
> 
>     return base.ValidateRedirectUriAsync(application, address, cancellationToken);
>   }
> 
>   public override ValueTask<bool> ValidatePostLogoutRedirectUriAsync(OpenIddictEntityFrameworkCoreApplication application, string address, CancellationToken cancellationToken)
>   {
>     if (!_environment.IsProduction())
>     {
>       var uri = new Uri(address);
>       if (uri.Host.Equals("localhost", StringComparison.OrdinalIgnoreCase) ||
>           uri.Host.Equals("host.docker.internal", StringComparison.OrdinalIgnoreCase))
>       {
>         return ValueTask.FromResult(true);
>       }
> 
>       if (address.StartsWith(<your-dev-environment-url>))
>       {
>         return ValueTask.FromResult(true);
>       }
>     }
> 
>     return base.ValidatePostLogoutRedirectUriAsync(application, address, cancellationToken);
>   }
> }
> I also noticed that I let this part in the appsettings while looking for a solution for our local and dev appsettings I don't know if they're absolutely necessary, but I didn't feel like wasting more time testing it out.
> 
> "Umbraco": {
>   "CMS": {
>    _...other things_
>     "Security": {
>       "BackOfficeHost": "[url to your local or dev environment ]",
>       "AllowConcurrentLogins": true
>     },
>     "WebRouting": {
>       "UmbracoApplicationUrl": "[url to your local or dev environment]"
>     }
>   },
> _...rest of the things_
> Obviously this will be taken out when we deploy in production. **I strongly suggest everyone does the same.** Also a good idea to have additional security measures in place.

So far we haven't had any issues when connecting to the dev umbraco from both dev and local

**Comment by umbracocommunity** [comment]
This issue has been mentioned on **Umbraco community forum**. There might be relevant details there:

https://forum.umbraco.com/t/umbraco-16-invalid-request-error-when-logging-into-backoffice/4788/2

**Comment by HensorIn** [comment]
Thank you for the login fix @akarkaselis.

This works for me for login, but when trying to logout I get a the same error, but for the post_logout_redirect_uri.
If PostLogoutRedirectUris is set to the dev url, the ValidatePostLogoutRedirectUriAsync is not triggered locally.
Have you encountered this issue?


error:invalid_request
error_description:The specified 'post_logout_redirect_uri' is invalid.
error_uri:https://documentation.openiddict.com/errors/ID2052

**Comment by davidsantosshareit** [comment]
> Thank you for the login fix [@akarkaselis](https://github.com/akarkaselis).
> 
> This works for me for login, but when trying to logout I get a the same error, but for the post_logout_redirect_uri. If PostLogoutRedirectUris is set to the dev url, the ValidatePostLogoutRedirectUriAsync is not triggered locally. Have you encountered this issue?
> 
> error:invalid_request error_description:The specified 'post_logout_redirect_uri' is invalid. error_uri:https://documentation.openiddict.com/errors/ID2052

I'm having exactly the same issue. Did you found anything?

**Comment by HensorIn** [comment]
> > Thank you for the login fix [@akarkaselis](https://github.com/akarkaselis).
> > This works for me for login, but when trying to logout I get a the same error, but for the post_logout_redirect_uri. If PostLogoutRedirectUris is set to the dev url, the ValidatePostLogoutRedirectUriAsync is not triggered locally. Have you encountered this issue?
> > error:invalid_request error_description:The specified 'post_logout_redirect_uri' is invalid. error_uri:https://documentation.openiddict.com/errors/ID2052
> 
> I'm having exactly the same issue. Did you found anything?

I have not found a fix other than changing the post_logout_redirect_uri back to our stage url manually if it has been overwritten by localhost

**Comment by dlidstrom** [comment]
Here's what I've learnt just now. If this problem is happening it means `umbracoOpenIddictApplications` table has the wrong url's. Make sure you only use a database per environment, i.e. don't connect to prod database from your local system. Better to clone it first, then clear `umbracoOpenIddictApplications` (this is safe as Umbraco will add the `umbraco-back-office` client id on first attempt to logon).

Some things to check:

```json
"Umbraco": {
  "CMS": {
    "WebRouting": {
      "UmbracoApplicationUrl": "<desired url>"
    },
    "Security": {
      "BackOfficeHost": "<desired url>"
    }
}
```

Make sure these are applied correctly (i.e. if using `appsettings.<env>.json`). Also check if you have any environment overrides (i.e. `Umbraco__CMS__WebRouting__UmbracoApplicationUrl` as these will take effect), or command line parameters to `dotnet run`.

Here's how to test your setup:

- restart site and stay logged out
- `delete from umbracoOpenIddictApplications`
- logon to Umbraco
- check `umbracoOpenIddictApplications` to see if url's are as expected

```sql
select
	u.PostLogoutRedirectUris,
	u.RedirectUris
from
	umbracoOpenIddictApplications u;
```

**Comment by jaddie** [comment]
Updated as realiesd a PR has been merged that solves this problem thankfully for V15 for anyone that might benefit to know
https://github.com/umbraco/Umbraco-CMS/pull/18302

**Comment by AndersBrohus** [comment]
> Updated as realiesd a PR has been merged that solves this problem thankfully for V15 for anyone that might benefit to know [#18302](https://github.com/umbraco/Umbraco-CMS/pull/18302)

But it's still not fixed?
If you boot a staging site on a server and tries to run the website locally with the same database we are still locking one of the running backoffices.

**Comment by SC-EVS** [comment]
Hi all, just to let anyone interested know, this still persists on a blank Umbraco 16.3.2 instance.

**Comment by CodingDK** [comment]
@nielslyngsoe This should also have Label for v16 (still a issue) - and maybe also v17 ?

**Comment by petr-vojtech** [comment]
All versions from 14 to 17 are affected by the same bug.
OpenId addresses are initialized every time an Umbraco application is started.
The main problem is that each initialization overwrites addresses from the previous initialization, especially in a balanced environment where more than one address is needed to access the Umbraco backoffice.
This is a critical bug for a balanced environment.
Backoffice addresses must be collected, not overwritten.
I described it in this issue https://github.com/umbraco/Umbraco-CMS/issues/21138
I also prepared a solution for Umbraco there.
It is now up to the Umbraco team to fix the bug.

**Comment by ben-umble** [comment]
I'm seeing this on Umbraco 17 in Azure, possibly due to using a test slot. It's not really workable for me to have a separate database just to avoid this issue and I don't want to drop the test slot as it gives me a chance to warm it up before switching over.

**Comment by gregor-tusar** [comment]
We see this issue on v17 when we use multisite configuration, where we access the backoffice via 2 different domains. 

I think the setting `Umbraco.CMS.Security.BackOfficeHost` should've been an array.

As seen in [the code of BackOfficeApplicationManager](https://github.com/umbraco/Umbraco-CMS/blob/release-17.1.0/src/Umbraco.Cms.Api.Management/Security/BackOfficeApplicationManager.cs) it just adds one URL to the array and loops then though array of one. 

Edit/Update:
We have a real mess with this now. 2 different domains behind the loadbalancer where the Https is disabled (SSL termination on the loadbalancer/reverse proxy). We see both domains in the DB table `umbracoOpenIddictApplications`, but they have `http` scheme.
We've tried with updating the  `RedirectUris` and `PostLogoutRedirectUris` in the database directly as somebody mentioned this as a workaround but this quickly fails since the values are updating frequently and the manual changes are overeriden.

**Comment by stef4905** [comment]
@gregor-tusar I agree on the array idea. It would solve the problem.

**Comment by bythewiseman** [comment]
Sadly we are facing this too and when building a new site where you have:

3 localhost developers (2 frontend and 1 backend)
1 warmup slot to ensure the site starts
1 development/production slot that the client sees

means we have 3 domains and we absolutely all need to access umbraco backoffice from the 3 domains.

Is there anything from Umbraco to say there are investigating this officially with a view to fixing it for us developers that have worked this way for decades and are now moving U13s to U17 due to EOL?

**Comment by petr-vojtech** [comment]
Umbraco 17.2.0 will be released on 19.2.2026.
https://releases.umbraco.com/release/umbraco/Umbraco-CMS/17.2.0
There are many bug fixes, including my fix that solves your problem, see my bug description.
https://github.com/umbraco/Umbraco-CMS/issues/21138
I'm looking forward to it.

**Comment by Migaroez** [comment]
Hey y'all, has the 17.2 release fixed this issue?

**Comment by petr-vojtech** [comment]
The Umbraco developer made a few changes to my fix and to my surprise it didn't work.
I'll report this as a broken solution, I'm frustrated, I've been waiting for a fix for 2 months... a bit of a never-ending story

**Comment by Migaroez** [comment]
I am that Umbraco developer and am surprised by your response, do you mean it didn't fix this issue which seems related but was not the original target to solve and/or it also did not fix https://github.com/umbraco/Umbraco-CMS/issues/21138 ?

**Comment by matthewcare** [comment]
Hi, @Migaroez, really hoping to get a fix for this, since I'm manually restarting azure instances on a daily basis, and it seems that although this issue has many comments, we're not getting anywhere fast with a solution.

The 17.2.0 release did _not_ fix the problem.

The problem is very easy to replicate locally with a bit of set up, and affects all Umbraco installations where there are multiple instances sharing a single database.

1. Create a fresh Umbraco 17 project with `dotnet new umbraco -n InstanceOne`
2. Create a second fresh Umbraco 17 project with `dotnet new umbraco -n InstanceTwo`
3. Create a local database `SharedInstance` and use this database for both instances for example my connection string
```
  "ConnectionStrings": {
    "umbracoDbDSN": "Server=(localdb)\\MSSQLLocalDB;Database=SharedInstance;Integrated Security=true;TrustServerCertificate=true;",
    "umbracoDbDSN_ProviderName": "Microsoft.Data.SqlClient"
  }
```
4. Using ngrok or a similar service, proxy InstanceOne (in my case `https://67d5-62-181-206-98.ngrok-free.app/`)
5. Update InstanceOne's appsettings with your proxy url
```
"Security": {
  "BackOfficeHost": "https://67d5-62-181-206-98.ngrok-free.app/"
},
"WebRouting": {
  "UmbracoApplicationUrl": "https://67d5-62-181-206-98.ngrok-free.app/"
} 
```
6. Update InstanceTwo with whatever port that is running on
```
"Security": {
  "BackOfficeHost": "https://localhost:44304"
},
"WebRouting": {
  "UmbracoApplicationUrl": "https://localhost:44304"
} 
```
7. Log into InstanceTwo, and then log out again
8. Attempt to log into InstanceOne

You are presented with the error
```
error:invalid_request
error_description:The specified 'redirect_uri' is not valid for this client application.
error_uri:https://documentation.openiddict.com/errors/ID2043
```

From the console
```
[14:41:08 INF] Revoking active tokens for user with ID -1
[14:41:08 INF] The request URI matched a server endpoint: Authorization.
[14:41:08 INF] The authorization request was successfully extracted: {
  "redirect_uri": "https://67d5-62-181-206-98.ngrok-free.app/umbraco/oauth_complete",
  "client_id": "umbraco-back-office",
  "response_type": "code",
  "state": "0w8R7IhHIz",
  "scope": "offline_access",
  "prompt": "consent",
  "access_type": "offline",
  "code_challenge": "sp7BK7u5pdOx2z4MVscel9N3P-GA432DafIa7Q40FOU",
  "code_challenge_method": "S256"
}.
[14:41:08 INF] Client validation failed because 'https://67d5-62-181-206-98.ngrok-free.app/umbraco/oauth_complete' was not a valid redirect_uri for umbraco-back-office.
[14:41:08 INF] The authorization request was rejected because the redirect_uri was invalid: 'https://67d5-62-181-206-98.ngrok-free.app/umbraco/oauth_complete'.
[14:41:08 INF] The response was successfully returned as a plain-text document: {
  "error": "invalid_request",
  "error_description": "The specified 'redirect_uri' is not valid for this client application.",
  "error_uri": "https://documentation.openiddict.com/errors/ID2043"
}.
```

If you restart InstanceOne then you can log in fine, but then InstanceTwo experiences the problem until you restart InstanceTwo, and repeat indefinitely.

For my specific use case which is causing this problem, is that we have a shared database between local development and a testing environment. Whenever we do local development, the client is unable to log into the testing site until we restart the instance. However as soon as we log in locally again, the test environment is once again broken.

This is causing a lot of frustration, and as someone else in this thread mentioned, is breaking a workflow that I've been working with since Umbraco 7.

Given that there are now easy replication steps to follow, hopefully we can make some better progress.

**Comment by matthewcare** [comment]
Following up with my previous comment, I think the issue stems from this line if statement
https://github.com/umbraco/Umbraco-CMS/blob/897b6ccac65093f35ec7ea7eaf49c698eb7fbd89/src/Umbraco.Cms.Api.Management/Security/BackOfficeApplicationManager.cs#L228

Whereby the entire `backOfficeHosts` array is replaced entirely if you supply a back office host in appsettings.
I believe the fix should be something like this:
```
if (_backOfficeHost is not null && !backOfficeHosts.Contains(_backOfficeHost))
{
    backOfficeHosts = backOfficeHosts.Append(_backOfficeHost).ToArray();
}
```
where we instead _update_ the list of backOfficeHosts if it doesn't contain the value from appsettings.

A consideration we need to make here though, is that if you change the back office host in appsettings a lot, the database table could contain a lot of stale URIs, which could be a security problem if you genuinely change domains for some reason.

**Comment by AndyButland** [comment]
Fixed via https://github.com/umbraco/Umbraco-CMS/pull/22160 for 17.4.  Thanks for the comment and contribution of the fix @matthewcare.

**Comment by AndyButland** [comment]
We'll actually bring this one in for 17.3.  It didn't make 17.3.0-rc that was out today, but we'll include in a 17.3.0-rc2 next week.
