### ISSUE TITLE
Cannot insert the value of a named field as "Choose field" dropdown does not contain custom fields

### ISSUE THREAD

**Issue by Superhands89** [umbraco/Umbraco-CMS#16743]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

14.0.0

### Bug summary

Using the Umbraco UI to insert values into a page template. Custom fields added to document types do not show up.

### Steps to reproduce

Install 14.0.0 with SQLite,
create a "document type with page template" called Page, 
add a textbox/textstring field inside Page doc type called "test", 
edit the "Page" Template and use the Insert > Value option to insert the test string value,
![image](https://github.com/umbraco/Umbraco-CMS/assets/16403756/47a50cab-0d1e-44ac-ac3f-e97c43a1e0a2)

the test value is not available from the Choose field dropdown.
![image](https://github.com/umbraco/Umbraco-CMS/assets/16403756/fa055c42-19c1-40b3-86ba-a442432ac168)

**Comment by elit0451** [comment]
Hi @Superhands89 👋 

Thanks for reaching out! It seems like this has been fixed in Umbraco 14.1. Here is a video of the functionality working:


https://github.com/user-attachments/assets/9ca30165-104a-4323-ae57-2a088cb3a88a
