### ISSUE TITLE
V14 Logviewer, navigating to the search tab has the value for search as "undefined"

### ISSUE THREAD

**Issue by andr317c** [umbraco/Umbraco-CMS#16767]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

14.1.0-rc2

### Bug summary

When I am navigating to the Log Viewer and then click on the Search Tab, the searchValue is defined as undefined. 
See GIF:
![V14LogViewer](https://github.com/umbraco/Umbraco-CMS/assets/73799582/86953ac5-c75b-49dc-91c4-552e191226e5)

### Steps to reproduce

1. Go to the Log Viewer
2. Go to the Search tab in the Log Viewer
3. See that the value is undefined

### Expected result / actual result

Expected: For the value to be empty

Actual: Value is "undefined"

**Comment by iOvergaard** [comment]
I noticed this as well, so can definitely reproduce.
