### ISSUE TITLE
Error browsing media with more than 50 media/folder

### ISSUE THREAD

**Issue by 1179vn** [umbraco/Umbraco-CMS#16764]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

14.0.0

### Bug summary

I'm having problems with the Media module, the media file browsing functions are really problematic.
When browsing folders with less than 50 images, there is no problem, but with numbers over 50, an API ERROR error appears, leading to the inability to browse images for work.

### Steps to reproduce

![Screenshot 2024-07-09 094534](https://github.com/umbraco/Umbraco-CMS/assets/92634542/083019af-96cd-410d-ad05-3a6b353c9280)
![Screenshot 2024-07-09 094509](https://github.com/umbraco/Umbraco-CMS/assets/92634542/4e82dcd0-8aea-4854-a534-22aa5a47c27d)
![Screenshot 2024-07-09 094430](https://github.com/umbraco/Umbraco-CMS/assets/92634542/c58698ca-9f3d-4699-87f0-9f3772f5f53d)

**Comment by NguyenThuyLan** [comment]
Hi @1179vn , thanks for reporting this issue. It is the same as #16716 , so I will close this because it is duplicated.

**Comment by 1179vn** [comment]
> Hi @1179vn , thanks for reporting this issue. It is the same as #16716 , so I will close this because it is duplicated.

So has this problem been resolved in any version?

**Comment by NguyenThuyLan** [comment]
Hi @1179vn , well, this issue will be resolved when #16716  is closed. Please follow that issue 🙂. Thanks
