### ISSUE TITLE
v14 Slider Decimals input and increment validation error

### ISSUE THREAD

**Issue by ainokarita** [umbraco/Umbraco-CMS#16773]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

14.0.0

### Bug summary

The Slider is acting funky, when I make it go in 0,1 increments (v14 project). I have three points to this:
1. When setting it up, if I want to use larger increments than 1 (with decimals), I can't - the numbers just jump around (when using a comma) or go back to "0" (if using a dot). I get no error/instruction message to guide me otherwise. (on Chrome, works the opposite on Edge))
2. After setting the increment to 0,1 (or 0,2, but not with 0,5), in the Content section, when I move the slider, it gives me a looong decimal result.
3. After setting increments to 0,6 and max value to 5, the slider shows a value range of natural numbers 0,1,1,2,2,3,4,4,5 (see image).
The value boxes on the slider property setup turn red after inserting a decimal value, but don't prevent submitting the changes.

### Steps to reproduce

https://github.com/umbraco/Umbraco-CMS/assets/49212909/42bf4c23-9883-476e-b48e-0c28723d92fd

![Screenshot 2024-07-10 154503](https://github.com/umbraco/Umbraco-CMS/assets/49212909/bd31d4d4-7a6d-4a3f-9c74-e44309e539da)

### Expected result / actual result

1. I would expect to receive an error/instruction message if decimal numbers are not accepted.
2. I'd like to have information that I should use a comma as the decimal separator.
3. The value range on the slider should reflect the range set in the property settings, or at least have one value only once on the range.

**Comment by iOvergaard** [comment]
Hello, thanks for testing!

This was a bug in the UI library, [which got patched in 1.8.2](https://github.com/umbraco/Umbraco.UI/releases/tag/v1.8.2). The CMS ships with that version of the UI library in its own 14.1.0 released last week.

I will mark this issue as fixed. Please re-open if you experience it after upgrading to 14.1.0!
