### ISSUE TITLE
Umbraco 14 - Block List inline editing mode do not work

### ISSUE THREAD

**Issue by MrXtry** [umbraco/Umbraco-CMS#16777]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

14.1.0

### Bug summary

Block List "inline editing mode" do not work, only shows an arrow down when you try to edit the block content

### Steps to reproduce

1. Create a block list data type and select "Inline editing mode" to true
2. Add any random block to it
3. Go to the content section where the block list property is added to and add the random block which you added to it
4. When you click on the block in the block list, it only shows an arrow down but no content is shown

![image](https://github.com/user-attachments/assets/8813e567-8997-44ac-88da-277e3fdbdfc3)

### Expected result / actual result

Should be an inline edit mode

**Comment by iOvergaard** [comment]
Hi @MrXtry, thanks for testing! I think this report is saying the same as #16298 so I will close this as a duplicate. Please re-open if you think this is something new 👍
