### ISSUE TITLE
V14 - Custom validation message doesn't display correctly

### ISSUE THREAD

**Issue by elit0451** [umbraco/Umbraco-CMS#16785]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

v14.1.0

### Bug summary

Trying to save content with invalid property that has custom validation set, shows incorrectly formatted error under the property - `#validation_invalidPattern`. See the video for more details:

https://github.com/user-attachments/assets/f2e33076-d4cd-4cb1-a3c0-cba24034e18a

### Steps to reproduce

- Create a document type with a Textstring property;
- Set custom validation on that property - for example "Validate as an email address";
- Create a content node with that document type;
- Try to Publish with a value in that property that is not in an email format.

### Expected result / actual result

Expected - in v13 we show "Value is invalid, it does not match the correct pattern".
Actual - `#validation_invalidPattern`.

---
_This item has been added to our backlog AB#42628_

**Comment by umbracocommunity** [comment]
This issue has been mentioned on **Umbraco community forum**. There might be relevant details there:

https://forum.umbraco.com/t/properties-validation-message-localization-not-working/7650/5
