### ISSUE TITLE
Users with fixed content/media start nodes can't see more than 50 items

### ISSUE THREAD

**Issue by iOvergaard** [umbraco/Umbraco-CMS#16789]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

14.1.0

### Bug summary

If you give a user group a content or media start node that has more than 50 items underneath, then the users can only see the first 50 items **in the tree**.

### Specifics

This happens because the `total` field from the Management API postulates that there are only ever the same amount of items as your `take` value.

For example, this request will give you this payload:
```
GET /umbraco/management/api/v1/tree/media/children?parentId=f3c7082c-b232-46c0-b6df-34fa81d5b46d&skip=0&take=50

{
  items: [{mediaType: {id: "cc07b313-0843-4aa8-bbda-871c8da728c8", icon: "icon-picture", collection: null},…},…]
  total: 50
}
```

If you log in with an unrestricted user, the same request looks like this:
```
GET /umbraco/management/api/v1/tree/media/children?parentId=f3c7082c-b232-46c0-b6df-34fa81d5b46d&skip=0&take=50

{
  items: [{mediaType: {id: "cc07b313-0843-4aa8-bbda-871c8da728c8", icon: "icon-picture", collection: null},…},…]
  total: 121
}
```

### Steps to reproduce

1. Create a user group and limit that to one folder in the Media library
2. Upload more than 50 items to that folder
3. Log in with the new user
4. You should see only the first 50 items in the tree, but all of them should show up in the collection view
5. Log in with an unrestricted user (e.g. the admin user)
6. Verify that you can now see the "Load more" button which shows the rest of the items

### Expected result / actual result

The expectation is that the `total` is `121` in both cases so the UI knows it should show a "Load more" folder.

**Comment by Zeegaan** [comment]
Fixed in https://github.com/umbraco/Umbraco-CMS/pull/16799 🚀
