### ISSUE TITLE
Not possible to clear a Date Picker value once set

### ISSUE THREAD

**Issue by ksolberg** [umbraco/Umbraco-CMS#16793]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

14.1.1

### Bug summary

I have a DateTime property and if a date has been saved, I can clear it in the editor, but current date and time is persisted.

### Steps to reproduce

1. Add a Date Picker property to a document type
2. Create a content item of that document type, but without selecting a date in the Date Picker field
3. Verify that the value is still empty
4. Select a date and save
5. Verify that the value is saved
6. Click date picker and select 'Clear' and save
7. Verify that todays date is saved, which is wrong.

**Comment by NguyenThuyLan** [comment]
Hi @ksolberg , thank for reporting this issue.
Confirm that this is an issue we want to fix.
