### ISSUE TITLE
Unable to use the Date Picker inside of a block list

### ISSUE THREAD

**Issue by bbankert667** [umbraco/Umbraco-CMS#16795]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

14.1.1

### Bug summary

When trying to create a datepicker, either with time or not, it will always return an error message if the date value is not null.

### Specifics

![image](https://github.com/user-attachments/assets/aa7ac9a2-ad81-44e4-847b-fad102980753)

### Steps to reproduce

1. Setup a new site with 14.1.1.
2. Create a page with a block list data type. The elements selected have to have a datepicker data type, it does not matter if the date has time or not.
3. Add a block list element with a date.
4. Save

It will throw the error in the picture above after saving & publishing. Also, when leaving the page, the same error will prevent the page from loading, leading to a white screen.

### Expected result / actual result

Able to use datepickers of any kind with block lists

**Comment by NguyenThuyLan** [comment]
Thanks @bbankert667 , this is an issue we want to fix, will let's team know 😊

**Comment by kjac** [comment]
PR in #16841
