### ISSUE TITLE
Unable to Publish to Azure Web App

### ISSUE THREAD

**Issue by NguyenThuyLan** [umbraco/Umbraco-CMS#16797]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

14

### Bug summary

Unable to Publish to Azure Web App using Web Deploy or GitHub Actions.

### Specifics

Unable to Publish to Azure Web App using Web Deploy or GitHub Actions

I have enable long path names as they exceed the 260 chars and still cannot publish

```
Severity	Code	Description	Project	File	Line	Suppression State
Error		Unable to copy file "C:\Users\deanl\.nuget\packages\umbraco.cms.staticassets\14.0.0\staticwebassets\umbraco\backoffice\packages\core\workspace\components\workspace-breadcrumb\workspace-variant-menu-breadcrumb\workspace-variant-menu-breadcrumb.element.js" to "C:\Users\deanl\source\repos\xDotNetTemplate\UmBootstrap-V14-01\UmBootstrap-V14-01\obj\Release\net8.0\PubTmp\Out\wwwroot\umbraco\backoffice\packages\core\workspace\components\workspace-breadcrumb\workspace-variant-menu-breadcrumb\workspace-variant-menu-breadcrumb.element.js". Could not find a part of the path 'C:\Users\deanl\source\repos\xDotNetTemplate\UmBootstrap-V14-01\UmBootstrap-V14-01\obj\Release\net8.0\PubTmp\Out\wwwroot\umbraco\backoffice\packages\core\workspace\components\workspace-breadcrumb\workspace-variant-menu-breadcrumb\workspace-variant-menu-breadcrumb.element.js'.	UmBootstrap-V14-01		0
```

### Steps to reproduce

Publish to Azure Web App using Web Deploy
Publish to Azure Web App using CI/CD

### Expected result / actual result

Site is published to web app

(Originally reported  by @deanleigh [Original Issue](https://github.com/umbraco/Umbraco-Deploy/issues/946) )

**Comment by netcamo** [comment]
@deanleigh

**Comment by iOvergaard** [comment]
This has the same root cause as reported on #16763. We will eventually fix it with bundling. The files you mention here have already been bundled in 14.1, but there may still be other files that affect it.

Someone on Discord figured out a way to upgrade MSBuild on your local machine to prevent it from happening since that supports long path names. That could fix the issue for you at least.
