### ISSUE TITLE
Embeds in RTE are not included

### ISSUE THREAD

**Issue by jemayn** [umbraco/Umbraco-CMS#16806]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

13.4.1

### Bug summary

When I add an embed in an RTE it removes it on save.
I've found this issue which seems related but mentions it only being an issue specifically in an RTE in a grid: https://github.com/umbraco/Umbraco-CMS/issues/11755

It sometimes allows me to add the embed, then afterwards if I try to edit the width/height of the included embed it doesn't save that change either.

### Specifics

Initially found the issue on 13.3.2, tested on latest 13.4.1 and could reproduce (see below)

### Steps to reproduce

I've reproduced this on a fresh site:

1. Create site, here is the [PSW I used](https://psw.codeshare.co.uk/?TemplateName=Umbraco.Templates&TemplateVersion=LTS&Packages=&UserEmail=admin%40example.com&ProjectName=Embed&CreateSolutionFile=true&SolutionName=Embed&UseUnattendedInstall=true&DatabaseType=SQLite&UserPassword=1234567890&UserFriendlyName=Administrator&IncludeStarterKit=true&StarterKitPackage=clean&OnelinerOutput=false&RemoveComments=false)
2. Add a new RTE with default settings to a doc type directly (not in any nested editor)
3. Try to add an embedded link and save, I tested with https://www.youtube.com/watch?v=4BcTNW9LDws 

Here is what happened:

https://github.com/user-attachments/assets/bbab57f6-283d-424a-b4ed-fb975c311669

### Expected result / actual result

Expect it to save the embed properly, and also update it when I try to change it.

---
_This item has been added to our backlog AB#43610_

**Comment by elit0451** [comment]
Hey @jemayn 👋 

It is nice to hear from you! Thanks for reaching out. 🙂  I am able to reproduce the issue, and it seems like adding text before it makes it stay:


https://github.com/user-attachments/assets/e9caf6e2-4277-4c3d-ab52-5fd4e934fdbe

We would love some help fixing this 🙌 so I will mark it as up for grabs. Meanwhile, there is the workaround.

**Comment by iOvergaard** [comment]
This should have been fixed in V14+. I am not sure if there is an easy fix in older Umbraco versions, but if anyone is willing to confirm that it works or is still a problem, feel free to do so!

**Comment by jemayn** [comment]
Hey @iOvergaard 

I can no longer reproduce my original issue on 13.5.2. Seems like https://github.com/umbraco/Umbraco-CMS/pull/17008 has fixed it 🙂 

Thanks to the team!

I am closing this issue.
