### ISSUE TITLE
Partial view depth 2 Throws API Error - Not found

### ISSUE THREAD

**Issue by lars-lindstrom** [umbraco/Umbraco-CMS#16823]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

14.2.0--rc.preview.9.g7e444e5

### Bug summary

The problem is not isolated to version 14.2.0--rc.preview.9.g7e444e5, it also happend in v 14.0.0, 14.1.0 and 14.1.1

The problem locks similar to this bug in Umbraco Cloud
https://github.com/umbraco/Umbraco.Cloud.Issues/issues/806

### Specifics

The bug occurs on calls to the "/umbraco/management/api/v1/partial-view/{path}" endpoint

### Steps to reproduce

Opening any file at a depth of 2 or more in the partials folder results in an "API Error" 404.

![image](https://github.com/user-attachments/assets/1f1645ab-8411-413b-8d82-6e75cb2ba81f)

The underlying call to the Management API returns a 404
![image](https://github.com/user-attachments/assets/bf8db919-7215-4dcb-8ae0-2d8fbac65b58)

If a file is placed in the "Partials" folder depth 1, no error is produced

### Expected result / actual result

The selected file at depth 2 or more should be loaded for editing in the BackOffice

**Comment by elit0451** [comment]
Hi @lars-lindstrom 👋 

Thanks for reaching out! Unfortunately, I wasn't able to reproduce this in Umbraco 14.1.1. Here is a video of what I did, perhaps you can point me to what I'm missing:


https://github.com/user-attachments/assets/4695a033-bcf7-4664-bea3-9d5853ca342f

**Comment by Nicole-Buys** [comment]
I have also run into this issue still.
CMS v14.1.2

Steps to reproduce:
I have only been able to reproduce this error on Umbraco Cloud as it does not seem to happen locally.

1. create a fresh v14 project on cloud
2. go to partial views --> blockgrid
3. try to view or create any partial views

The error in the console refers to an authentication token that is missing
![image](https://github.com/user-attachments/assets/e0f2f93a-983f-4632-b34b-1025e302c340)

**Comment by matthew-covey-el** [comment]
We are experience the exact issue that Nicole describes above on Umbraco Cloud. CMS v14.2.0

**Comment by j9850s** [comment]
This is a host problem. For example Azure rewrites the "%2F" to "/"
https://learn.microsoft.com/en-us/answers/questions/2007707/azure-app-services-decodes-2f-in-a-inbound-request
https://learn.microsoft.com/nl-nl/aspnet/core/fundamentals/routing?view=aspnetcore-7.0#routing-with-special-characters

For fixing this you can add middleware to rewrite the original url.
https://github.com/LogOtter/log-otter/pull/188

If the Umbraco team is eager for fixing this in Umbraco.
is a possible fix to Base64 the path variable and decode it back in the controller.

repo: deploy umbraco to azure
See API results without authentication:
{site}/umbraco/management/api/v1/partial-view/%2FName.cshtml - 401 unauthourized as expected
{site}/umbraco/management/api/v1/partial-view/%2Fblockgrid%2Fdefault.cshtml - 404 not found, This is not expected

**Comment by j9850s** [comment]
https://github.com/umbraco/Umbraco.Cloud.Issues/issues/806#issuecomment-2404515470
