### ISSUE TITLE
Infinite Editing should not close when there is validation errors

### ISSUE THREAD

**Issue by enkelmedia** [umbraco/Umbraco-CMS#16826]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

14.1.1

### Bug summary

When editing a Content Type using the "Infinite Editing" feature has validation errors the modal is still closed and changes are lost. I have not tested this for e.g. content or media but for content types it looks like this:

![umb-issue-infinite-edit-validation](https://github.com/user-attachments/assets/facbad8f-862d-4a8b-a6e2-376493d285ff)

### Steps to reproduce

See video

### Expected result / actual result

If anything edited using "Infinite Editing" has validation errors the modal should stay opened so that editors has the chance to fix the issue and save without losing any changes.

---
_This item has been added to our backlog AB#42754_

**Comment by elit0451** [comment]
Hi @enkelmedia 👋 

Thanks for reaching out! I can indeed reproduce this and it happens for content type, media, media type. We will have a look 🙂
