### ISSUE TITLE
Small overlay is slim compared to old backoffice

### ISSUE THREAD

**Issue by bjarnef** [umbraco/Umbraco-CMS#16844]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

14.1.0

### Bug summary

I think the small overlay in v14 has become very slim compared to old backoffice, where it often was slim too and medium and large overlay fit better.

![image](https://github.com/user-attachments/assets/cc16cb7f-d790-4dfa-a84c-01410757bba1)

![image](https://github.com/user-attachments/assets/bc45d889-47d5-4c7b-b474-c53a5b47e661)

Before width was 500px, now only 400px.

It makes some of the content squeezed like link + anchor/querystring:
https://github.com/umbraco/Umbraco-CMS/issues/16838

or headings in blocks, which need to be truncated.

### Steps to reproduce

Open an overlay in small size, e.g. from Block Grid.

**Comment by elit0451** [comment]
Hi @bjarnef 👋 

Thanks for reaching out! We will have a look 🙂
