### ISSUE TITLE
Can't get value of numeric property

### ISSUE THREAD

**Issue by JessicaGUALTIERI** [umbraco/Umbraco-CMS#16842]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

14.1.1

### Bug summary

I can't get proper value of a property of type numeric. Program returns null and then convert it to 0.

### Specifics

I am trying to render the number of likes for an article. In Umbraco back office, the property appears to be 2 :
![image](https://github.com/user-attachments/assets/6fcdff89-565f-4a07-afdf-54b2277d8b19)

The property alias is 2numberOfLikes"  (property editor picked is numeric with no change) :
![image](https://github.com/user-attachments/assets/113e4dcf-fbda-4979-842b-a291f4a280b8)

My code is :
 -> Getting value :
`int? numberOfLikes = Model.Value<int>("numberOfLikes");`

 -> Trying to render it :
`@using (Html.BeginUmbracoForm<FavouriteController>(nameof(FavouriteController.Submit)))
                {
                    <input asp-for="@Model.Key" type="hidden">
                    <button type="submit" class="h-10 w-10 flex justify-center items-center relative">
                        @if (await _favouriteService.IsFavorite(Model.Key.ToString()))
                        {
                            <svg class="fill-red-500 w-6 h-6" viewBox="0 0 24 24">
                                <path d="M2 9.1371C2 14 6.01943 16.5914 8.96173 18.9109C10 19.7294 11 20.5 12 20.5C13 20.5 14 19.7294 15.0383 18.9109C17.9806 16.5914 22 14 22 9.1371C22 4.27416 16.4998 0.825464 12 5.50063C7.50016 0.825464 2 4.27416 2 9.1371Z"/>
                            </svg>
                        }
                        else
                        {
                            <svg class="fill-gray-300 w-6 h-6" viewBox="0 0 24 24">
                                <path d="M2 9.1371C2 14 6.01943 16.5914 8.96173 18.9109C10 19.7294 11 20.5 12 20.5C13 20.5 14 19.7294 15.0383 18.9109C17.9806 16.5914 22 14 22 9.1371C22 4.27416 16.4998 0.825464 12 5.50063C7.50016 0.825464 2 4.27416 2 9.1371Z"/>
                            </svg>
                        }
                        <span class="absolute -bottom-1 -right-1 bg-red-500 text-white rounded-full w-4 h-4 text-xs flex justify-center items-center">@numberOfLikes.ToString()</span>
                    </button>
                }`
                
But what is rendered is 0. While debugging, we can see that the value of numberOfLikes is null and then 0 :
![image](https://github.com/user-attachments/assets/dec12ff4-f248-4471-8a84-53186e8bba59)
![image](https://github.com/user-attachments/assets/082530c6-a854-43c7-a7a5-df00ac3c3a29)

### Steps to reproduce

1. Add a numeric property to a document type of type 'numeric'.
2. Work on it with code.
3. Value changes in Umbraco Backoffice as expected.
4. Try to get it with either : 
- int? numberOfLikes = Model.Value<int>("numberOfLikes");
- string? numerOfLikes = Model.Value("numberOfLikes")?.ToString();
5. Get null then 0.

### Expected result / actual result

Intended : get 2
Actually : get 0

**Comment by elit0451** [comment]
Hi @JessicaGUALTIERI 👋 

Thanks for reaching out! I was unfortunately unable to reproduce this in Umbraco 14.1.1. Can you please verify if I am missing something in the video below?

https://github.com/user-attachments/assets/c6d4ebb6-b812-4744-af57-2cbd990b977f

**Comment by JessicaGUALTIERI** [comment]
> Hi @JessicaGUALTIERI 👋
> 
> Thanks for reaching out! I was unfortunately unable to reproduce this in Umbraco 14.1.1. Can you please verify if I am missing something in the video below?
> 
>  Likes.mov

Hi @elit0451 !

Tysm for reaching out.

You have exactly the same things I do have but it doesn't work for me. I don't know what the problem is. I do have the same property name between umbraco and my code. I do have the same Numeric as you do since it's the default one, no modification. I do try to get it with either `int? numberOfLikes = Model.Value<int>("numberOfLikes")`; or  `string? numberOfLikesString = Model.Value("numberOfLikes")?.ToString();`... It still renders 0 or 0...

I don't know what to tell you more... All other property are working perfectly fine and their values are correctly rendered...

See more :
![image](https://github.com/user-attachments/assets/c7e63d59-e1e3-4e6f-a0b8-7cdbafaf0db5)

![image](https://github.com/user-attachments/assets/af8e9508-7e0a-46f4-864b-59e7beda7029)

![image](https://github.com/user-attachments/assets/d6deec57-4d15-4ba0-b296-219888882352)

![image](https://github.com/user-attachments/assets/94b0d6aa-13b4-4961-9395-788fe1b76126)

![image](https://github.com/user-attachments/assets/4f289294-8a9c-4c12-8f72-4770cdd1cada)

![image](https://github.com/user-attachments/assets/52ff294c-0ef3-436f-8121-0a97c03dce50)

**Comment by JessicaGUALTIERI** [comment]
Still tring today, still not working... :(

![image](https://github.com/user-attachments/assets/b97c61fb-3068-48bd-b17a-83f8e0235eff)

![image](https://github.com/user-attachments/assets/0e7722b1-45c9-4a8a-8783-0b1d0dbb340d)

![image](https://github.com/user-attachments/assets/a2cb6d36-4b7b-4384-aa5e-d5bd7c4ea43c)

**Comment by JessicaGUALTIERI** [comment]
Also, note that I have this property numberOfLikes on two different document types and it's not working on both of them...

**Comment by JessicaGUALTIERI** [comment]
> Hi @JessicaGUALTIERI 👋
> 
> Thanks for reaching out! I was unfortunately unable to reproduce this in Umbraco 14.1.1. Can you please verify if I am missing something in the video below?
> 
>  Likes.mov

Hey @elit0451 !

Thank you so much for reaching out. Sorry for wasting your time since I found out it was because I did changes on this value from a Service in code, effectiveloy Saved it but didn't publish the document. So no effective change in front...........

Thanks again, wish you the best. ☀

**Comment by elit0451** [comment]
Haha, you are really sweet 🤗 

No time was waisted, I am glad you figured it out 🙌
