### ISSUE TITLE
Cannot get variantId of property

### ISSUE THREAD

**Issue by jojo308** [umbraco/Umbraco-CMS#16859]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

14.1.1

### Bug summary

I have a property editor where I want to retrieve the `unique` and `variantId` of the node that is being edited. However, I am unable to retrieve the variantId/culture. In older versions of Umbraco I could use `editorState.variants.find(x => x.active)`, but this doesn't exist anymore and I can't find any alternatives. 
I've tried using some available contexts like `UMB_WORKSPACE_CONTEXT` and `UMB_PROPERTY_CONTEXT` but when I try to access the variant it returns `undefined`.

The following code snippet should return the variantId but it returns undefined instead.
```typescript
this.consumeContext(UMB_PROPERTY_CONTEXT, (ctx) => {
    this._propertyContext = ctx;

    this.observe(this._propertyContext.variantId, (id) => {
        console.log('UMB_PROPERTY_CONTEXT:variantId:', id)
        if (id && id.culture !== undefined) {           
            console.log(':UMB_PROPERTY_CONTEXT:culture:', id.culture)
        } else {
            console.log('UMB_PROPERTY_CONTEXT:culture is undefined')
        }
    })
})

override async connectedCallback() {
    super.connectedCallback();
    console.log('UMB_PROPERTY_CONTEXT:variantId:', this._propertyContext?.getVariantId())
}
```

My property editor is located in a block list item if that helps. When the property editor is located in a document directly instead of a block list item, I can actually get the variantId.

Data when the property editor is in a document:
![image](https://github.com/user-attachments/assets/35509d01-1a05-4e55-8f35-2817876464b9)
Data when the property editor is in a block list:
![image](https://github.com/user-attachments/assets/e67e5707-c59c-4656-984e-9097540e343b)

### Steps to reproduce

I've made a repo with my property editor: https://github.com/jojo308/Umbraco.Variant.Issue

1. Clone the repo
2. Run the site and go to the backoffice (credentials are in the README)
3. Go to the home node and open the block item of the Standard Header property.
4. Check the console in Developer Tools.

### Expected result / actual result

I expect the variant to have a value instead of undefined.

**Comment by nielslyngsoe** [comment]
Hi @jojo308 Very good case, thanks for reporting this. 🤩

I have made a fix for this, as we surely did miss the VariantID binding to Block Workspace.
Here: https://github.com/umbraco/Umbraco.CMS.Backoffice/pull/2214

I see that you got a pretty good understanding of the system, so please share your learning process with me, and let me know how it works for you. Both from a technical and from a learning experience perspective.

Then we can use that to improve code or improve Documentation.

Feel free to get in contact with me on one of these platforms:

Discord: nielslyngsoe
LinkedIn: https://www.linkedin.com/in/nielslyngsoe/

Thanks in advance
