### ISSUE TITLE
Unable to change User password in backoffice

### ISSUE THREAD

**Issue by huwred** [umbraco/Umbraco-CMS#16860]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

14.1.1

### Bug summary

Recieve an error when trying to change a User password.

"Old password required"

### Specifics

I am using Edge

### Steps to reproduce

Login to backoffice, navigate to user section.
Open User profile and select Change password

Enter your old password and new password (twice)
Click Confirm
Returns the "Old password required" error
![image](https://github.com/user-attachments/assets/2b916436-fb50-44e6-b5df-8adb41870131)

### Expected result / actual result

Confirmation that my password has changed

**Comment by elit0451** [comment]
Hi @huwred 👋 

Thanks for reaching out! It seems like the FE is not passing the old password when calling the `/change-password` endpoint:


https://github.com/user-attachments/assets/1faa6dcd-31c8-41d1-b25b-7a7d9240856d



We will have a look 🙂

**Comment by MrEssCee** [comment]
@elit0451 

I thought to try and help here (first time i have pulled the Umbraco repo)and pulled down the current repository (contrib). 

I can get to the controller `ChangePasswordUserController (ChangePassword)` in debug mode and can confirm the oldPassword isnt being sent from the FE (👍).

I then found the file `change-password-modal.element.js` under wwwroot and was able to make changes to the file which reflected in the backoffice change password form. 

Added some logging to this file and noticed the values are being sent from this page. Which file would need to be change to pass the value as i couldnt hit debug around the FE?

Thanks

**Comment by elit0451** [comment]
Thank you for your interest here @MrEssCee 🙌 It is great to see new contributors in the Umbraco repo. 

Our team has already started looking into this, so I would keep my eye on the `up-for-grabs` label _([link](https://github.com/umbraco/Umbraco-CMS/issues?q=is%3Aopen+is%3Aissue+label%3Acommunity%2Fup-for-grabs))_ or `good first issue` one _([link](https://github.com/umbraco/Umbraco-CMS/issues?q=is%3Aopen+is%3Aissue+label%3A%22good+first+issue%22))_ if I were you as they indicate places where the community can jump in and help us out 😊 💪

**Comment by madsrasmussen** [comment]
Fixed in: https://github.com/umbraco/Umbraco-CMS/issues/16882

**Comment by umbracocommunity** [comment]
This issue has been mentioned on **Umbraco community forum**. There might be relevant details there:

https://forum.umbraco.com/t/after-upgrading-from-13-13-0-to-17-2-2-backoffice-password-changes-silently-fail-to-persist/7694/1
