### ISSUE TITLE
Inactive Users showing up in the event log of a deleted Media item

### ISSUE THREAD

**Issue by stuff802** [umbraco/Umbraco-CMS#16876]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

14.1.1

### Bug summary

When an item has been deleted in the Media Library it shows the original user as the person who deleted it (even when it wasn't that user). It also shows even when the user is Inactive (see image):

![image](https://github.com/user-attachments/assets/33e39fd0-f2d3-4622-abe7-97a45d944184)

### Specifics

![image](https://github.com/user-attachments/assets/9c3cdf93-0616-4361-9e96-83c28c302a6c)

### Steps to reproduce

1. Get one user to create an item in the Media Library
2. Get another user to delete that item
3. View the timeline in the deleted items log:
![image](https://github.com/user-attachments/assets/abd3343d-ada6-4caf-bd9c-adbb65f5b88a)

### Expected result / actual result

The log should just show the current user deleting the Media Library item

**Comment by elit0451** [comment]
Fixed in #16903 🙂
