### ISSUE TITLE
Whitespace not trimmed on login screen

### ISSUE THREAD

**Issue by deMD** [umbraco/Umbraco-CMS#16878]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

13.4.1

### Bug summary

After upgrading a website from the latest U10 version to the latest U13 version logging into the backoffice didn't work anymore, returning a 400 response without any details. After looking around for way too long, I noticed a whitespace in front of the email address which came from my password manager, removing this whitespace resolved the issue.

This email address with whitespace worked fine in U10.

### Specifics

Umbraco 10
![U10logintrim](https://github.com/user-attachments/assets/87daeb5d-e945-4b27-a0be-55f739b72386)

Umbraco 13
![U13logintrim](https://github.com/user-attachments/assets/96eaa294-7342-4525-b5a2-5adcf3701a1e)

### Steps to reproduce

Install an umbraco 10 site using an emailaddress containing a whitespace
Login in U10
Upgrade to U13
Try to login

### Expected result / actual result

I should be able to log in regardless of whitespaces in front or behind email addresses.

**Comment by EmanuelGustafzon** [comment]
Hi, I am new to open source and Umbraco and want to get started, could this be a good first issue for me to work on?

**Comment by elit0451** [comment]
Hi @deMD and @EmanuelGustafzon  👋 

Thanks for reaching out! I am able to reproduce this and @EmanuelGustafzon, absolutely. Have a look at this line here:
https://github.com/umbraco/Umbraco-CMS/blob/9d94658372f9af21985e5579f1d0d21c1438e311/src/Umbraco.Web.Common/Security/UmbracoSignInManager.cs#L181
It might be a good place to trim the input from any unnecessary spaces 😌 I will mark this issue as up-for-grabs then

**Comment by EmanuelGustafzon** [comment]
Thank you @elit0451 I created a PR.

Please let me know if there are any other tasks I can work on.

**Comment by emmagarland** [comment]
This has been completed in the back-end by fix #16921, so I'll close this one, but there may be scope to create a new front-end issue to trim the username there too, as raised by @bjarnef in the PR.
