### ISSUE TITLE
Values are not fetching from Dictionary items for Multilingual Document types, Dropdown Prevalues etc.

### ISSUE THREAD

**Issue by diljithpeter11** [umbraco/Umbraco-CMS#16874]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

13.4.1

### Bug summary

![File 1](https://github.com/user-attachments/assets/745838f9-d4a8-4081-b7fe-271b76222ac0)
![File 2](https://github.com/user-attachments/assets/818f7693-a1f0-424f-83e8-9d45422f5d3e)
![File 3](https://github.com/user-attachments/assets/4195cbaf-d51a-482d-bab6-cad26f1d0a7d)
![File 4](https://github.com/user-attachments/assets/5ec0235b-f8c4-464d-ab89-d81b4b5aac97)

Values are not fetching from Dictionary items for Multilingual Document types, Dropdown Prevalues etc. I have created a document type which support multiple culture and created dictionary values for these fields. But they are not fetching from dictionary items and showing default language value for document properties and dictionary attribute for dropdown prevalues.

### Steps to reproduce

1. Install the Umbraco CMS latest version 13.4.1
2. Create Multilingual Doc types and Dictionary items for the properties.
3. Go to the Content and create the Umbraco node
4. Change the node variant using language dropdown from one language to another.

**Comment by NguyenThuyLan** [comment]
Hi @diljithpeter11 , thanks for reporting issue.
Please follow the docs below for translating multi-value property editors
https://docs.umbraco.com/umbraco-cms/tutorials/multilanguage-setup#translating-multi-value-property-editors
