### ISSUE TITLE
[v14] Active tree item Icon color should match text color

### ISSUE THREAD

**Issue by mattbrailsford** [umbraco/Umbraco-CMS#16882]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

v14

### Bug summary

It is currently possible to select pink for the icon color of a document type icon, however this is the color of the highlight when a content tree item is selected. As such, when highlighted the icon disappears.

If pink is the color for the highlight, we should prevent people from using it as an icon color.

### Specifics

![image](https://github.com/user-attachments/assets/aee8e700-08aa-4de1-9423-18481bf05c26)

### Steps to reproduce

* Create a doc type with an icon of color pink
* Create a content node with that icon on the content section
* Click to edit the new node making the menu item selected
* The icon now matches the selection color and so disapears

---
_This item has been added to our backlog AB#46448_

**Comment by bjarnef** [comment]
I think in pre v14 the icon of a highlighted tree node was always a specific color, black IIRC.

**Comment by nathanwoulfe** [comment]
I think @bjarnef is correct - icon color should match the text color in a selected menu item. Pretty sure that's how it was previously.

**Comment by bjarnef** [comment]
In v13 it looks like this:

![image](https://github.com/user-attachments/assets/85b4ae46-3ca6-466b-9527-9252bd93ba8f)

Some of the colors may not work in icon picker, e.g. light yellow and pink due the contrast on white background.
Previous the pink was darker, but was changed to a brighter color to avoid look to much as an error.
