### ISSUE TITLE
14.2.0-RC Unable to install/upgrade to NPM package

### ISSUE THREAD

**Issue by warrenbuckley** [umbraco/Umbraco-CMS#16892]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

14.2.0-rc

### Bug summary

I am trying to update to the latest NPM package to go with the version of Umbraco I have upgraded to with this command
`npm install @umbraco-cms/backoffice@14.2.0-rc --save-dev`

### Specifics

I get the following error when running
`npm install @umbraco-cms/backoffice@14.2.0-rc --save-dev`

```bash
npm error code 1
npm error path C:\Code\some-client-v14\src\SomeClient.Backoffice\node_modules\@umbraco-cms\backoffice
npm error command failed
npm error command C:\Windows\system32\cmd.exe /d /s /c npm run generate:tsconfig
npm error > @umbraco-cms/backoffice@14.2.0-rc generate:tsconfig
npm error > node ./devops/tsconfig/index.js
npm error node:internal/modules/cjs/loader:1148
npm error   throw err;
npm error   ^
npm error
npm error Error: Cannot find module 'C:\Code\some-client-v14\src\SomeClient.Backoffice\node_modules\@umbraco-cms\backoffice\devops\tsconfig\index.js'
npm error     at Module._load (node:internal/modules/cjs/loader:986:27)
npm error     at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:174:12)
npm error     at node:internal/main/run_main_module:28:49 {
npm error   code: 'MODULE_NOT_FOUND',
npm error   requireStack: []
npm error }
npm error
npm error Node.js v20.15.1
```

### Steps to reproduce

Try running the npm command
`npm install @umbraco-cms/backoffice@14.2.0-rc --save-dev`

### Expected result / actual result

For the NPM package to install without issues/errors

**Comment by madsrasmussen** [comment]
Hi @warrenbuckley 

Thanks for the report. We have a fix in place and we will ship an RC2 today. 

https://github.com/umbraco/Umbraco.CMS.Backoffice/pull/2201
