### ISSUE TITLE
Internal Index drops pages and will not rebuild.

### ISSUE THREAD

**Issue by Eaglef90** [umbraco/Umbraco-CMS#16896]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

13.4.1

### Bug summary

In my Umbraco 13.4.1 install on Umbraco Cloud my internal index will randomly loose pages it has index (i.e. I can find them in the index one day and then the next they are no longer index). This happens to both published and unpublished nodes. If I try to rebuild the index everything in the log says the rebuild started but it never says it compleased and the count will Document Count will be 0 even after 24 hours, it will only go up if I republish/save a document.

### Specifics

In my Umbraco 13.4.1 install on Umbraco Cloud my internal index will randomly loose pages it has index (i.e. I can find them in the index one day and then the next they are no longer index). This happens to both published and unpublished nodes. If I try to rebuild the index everything in the log says the rebuild started but it never says it compleased and the count will Document Count will be 0 even after 24 hours, it will only go up if I republish/save a document.

### Steps to reproduce

The documents are randomly droped and I can't pin-point any specific repo steps

### Expected result / actual result

I would expect the index to NOT drop documents and that if I rebuild it would complete or log some sort of error.

Actual: The index randomly drops data and can't be rebuilt with no indication as to why

**Comment by Eaglef90** [comment]
Talking with Umbraco Support bia my portal they say this is a known issue and there is an internal bug report on it but as I see nothing public I am opening this so others having the issue know about it and maybe someone can give us a work around or some idea of what is going on and expected time to fix. My site right now only has a few hundred documents and it is more of just an annoyance when my editors have to find pages but soon I will be importing over 65k documents and this issue will be a huge problem and cost when editors have to sort though documents to find what they are looking for instead of using the backoffic search.

**Comment by bergmania** [comment]
Hi @Eaglef90..

There has been released a new version of Examine that maybe fixes this issue. Please try to update Examine to 3.3 and check if it works, that will be helpful.

**Comment by Eaglef90** [comment]
I don't have an Examine package so I am assuming I need to install an explicite package. Searching Nuget for "Examine" comes back with a lot of resultes The top 3 (Examine, Examine.Lucene, and Examine.Core) are all 3.3.0 but there is also an Umbraco.CMS.Examine.Lucene. Can you please let me know which package you wanting me to instll.

**Comment by bergmania** [comment]
All three of them are referenced in version 3.2.1 by Umbraco. If you add an explicit dependency to version 3.3.0 it will use that everywhere, and verify if this is solved by the update or not.

**Comment by Eaglef90** [comment]
So I need all 3 packages then?

**Comment by bergmania** [comment]
Yes, that should be safe
```xml
      <PackageReference Include="Examine" Version="3.3.0" />
      <PackageReference Include="Examine.Core" Version="3.3.0" />
      <PackageReference Include="Examine.Lucene" Version="3.3.0" />
```

**Comment by Eaglef90** [comment]
I added the Exmaine 3.3.0 which auto instlled the .core and .Lucene 3.3.30 packages as well. Published to my production site and rand a rebuild so far it does not seem to have fixed any problems. The rebuild ran for a mit then got the message "The process is taking longer than expected, check the Umbraco log to see if there have been any errors during this operation" and it now knows about 0 documents and 0 fields. 

Checking the logs I see "Rebuilding index '"InternalIndex"'" and "Starting async background thread for rebuilding index "InternalIndex"." This is the same login I saw before the ugprade. I will check back after I sleep for the night but I am not expecting any change.

**Comment by Eaglef90** [comment]
So I just checked and the rebuild did not compleate. Once again nothing in the logs about it failing but the internal index has 0 document and 0 field count. Is there some work around for this, like can I index on my local machine and push that up?

**Comment by bergmania** [comment]
Without understanding what is going on, it is hard to give any workarounds.

Maybe it will help our understanding if you lower the log level of examine. You can do that in appsettings.json in the `Serilog:MinimumLevel:Override` section, you can add an string `"Examine": "Debug"`, next to the `Microsoft": "Warning",`

Alternatively try to change the default log level to something lower and try to rebuilt the index

**Comment by Eaglef90** [comment]
I added your line as well as set everything else to debug and these are the entries I see now:

Rebuilding index "InternalInmdex"
Starting async background thread for rebuilding index "InternalIndex".
Clearing existing index "InternalIndex"
"InternalIndex" committed
"ReplicationThread" - "DoUpdate(): handlerVersion=A61 session=id=1 version=A62 files={index=[fileName=segments_21u length=53]}"
"ReplicationThread" - "DoUpdate(): handlerVersion=A61 session=id=1 version=A62 files={index=[fileName=segments_21u length=53]}"
"InternalIndex" replication complete from "C:\local\Temp\ExamineIndexes\5d94a3a1b7219f070b77d43331d7e1ef\InternalIndex" to "C:\home\site\wwwroot\umbraco\Data\TEMP\ExamineIndexes\InternalIndex"

I still got the "The process is taking longer than expected, check the Umbraco log to see if there have been any errors during this operation" message on rebuild and my document/field count sits at 0

**Comment by Eaglef90** [comment]
Just checking in to see what next steps I can do to help provide more information. This has been an on going issue for a few months and it is costing me money so I would like to try  and resolve it. It seems to be unique to my cloud install as I can easly rebuild the index on my local dev machine with no issues.

**Comment by bergmania** [comment]
@Eaglef90 

I still dont have enough information to really get anyway. I think you need to reach out to support potentially, we can investigate further with access to your database. 

Does the the think happen on all environments? - Including local?

**Comment by Eaglef90** [comment]
I only have two environments, local and prod. It only hapoens in prod. I did reach out to support and was just told it is a known issue and they have an internal tracker foe it but thwn got no futher answers about it. I opened this uo since support has told me on other issues peoblems with the cms need to go to github. I will poke support again but don't have my hopes up.

**Comment by bergmania** [comment]
Do local have the exact same data as prod?

I would put a debugger on and see what is going on.

**Comment by Eaglef90** [comment]
Local is exact copy of prod. Not sire what debugfer you would want. No issue on local and set the logs to full debug in prod with apparently nothing. Curous do you work for Umbraco? If so supports says this is a known issue with an internal tracker. Maybe you can get the team working that to take a look at this thrrad?

**Comment by Eaglef90** [comment]
I have talked with Umbraco support and they are telling me they will not be providing support for this. They said the same thing as you, upgraded the Exmaine version. But beyond that, they can not provide support.

This is a hugly devistating issue for me. I am about to stat a very expensive project and do a huge (65k+ node) data import but if this can't be fixed then that means it is all wasted and everything I have done over the past 2 years on Umbraco needs to be moved to something else. This will quite possible kill my bussiness if I have to do such a major change, I don't have the time or money to do that.

Please I need help to get this fixed before I loose my life savings and my bussiness.

**Comment by Eaglef90** [comment]
@bergmania I have talked with Umbraco support and they are telling me they will not be providing support for this. They said the same thing as you, upgraded the Exmaine version. But beyond that, they can not provide support on my current plan. They have also stated they are not sure if it is a cloud platform issue or a CMS and I am supposed to ask here for help.

This is a hugly devistating issue for me. I am about to stat a very expensive project and do a huge (65k+ node) data import but if this can't be fixed then that means it is all wasted and everything I have done over the past 2 years on Umbraco needs to be moved to something else. This will quite possible kill my bussiness if I have to do such a major change, I don't have the time or money to do that.

Please I need help to get this fixed before I loose my life savings and my bussiness.

**Comment by Eaglef90** [comment]
After moving to a new host I am still having the problem of the index failing to build but I am now getting errors in my logs and they are pointing to a JSON token issues from a third-party package

`System.InvalidCastException: Cannot cast Newtonsoft.Json.Linq.JObject to Newtonsoft.Json.Linq.JToken.
   at Newtonsoft.Json.Linq.Extensions.Convert[T,U](T token)
   at Newtonsoft.Json.Linq.JToken.Value[T](Object key)
   at Limbo.Umbraco.Tables.PropertyEditors.TablePropertyIndexValueFactory.ProcessRow(JArray row)+MoveNext()
   at System.Linq.Enumerable.SelectManySingleSelectorIterator`2.MoveNext()
   at Umbraco.Cms.Core.PropertyEditors.NestedPropertyIndexValueFactoryBase`2.GetResumeFromAllContent(List`1 indexedContent)
   at Umbraco.Cms.Core.PropertyEditors.NestedPropertyIndexValueFactoryBase`2.HandleResume(List`1 indexedContent, IProperty property, String culture, String segment, Boolean published)+MoveNext()
   at Umbraco.Cms.Infrastructure.Examine.BaseValueSetBuilder`1.AddPropertyValue(IProperty property, String culture, String segment, IDictionary`2 values, IEnumerable`1 availableCultures, IDictionary`2 contentTypeDictionary)
   at Umbraco.Cms.Infrastructure.Examine.ContentValueSetBuilder.GetValueSetsEnumerable(IContent[] content, Dictionary`2 creatorIds, Dictionary`2 writerIds)+MoveNext()
   at System.Collections.Generic.LargeArrayBuilder`1.AddRange(IEnumerable`1 items)
   at System.Collections.Generic.EnumerableHelpers.ToArray[T](IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at Umbraco.Cms.Infrastructure.Examine.ContentIndexPopulator.IndexAllContent(Int32 contentParentId, Int32 pageIndex, Int32 pageSize, IReadOnlyList`1 indexes)
   at Umbraco.Cms.Infrastructure.Examine.ContentIndexPopulator.PopulateIndexes(IReadOnlyList`1 indexes)
   at Umbraco.Cms.Infrastructure.Examine.IndexPopulator.Populate(IIndex[] indexes)
   at Umbraco.Cms.Infrastructure.Examine.ExamineIndexRebuilder.RebuildIndexes(Boolean onlyEmptyIndexes, TimeSpan delay, CancellationToken cancellationToken)`
   
 I have heard that Umbraco is slowly moving off Newtonsoft and seeing how this broke during a minor patch of 13 I am betting that a small change that should not have been breaking ended up being breaking for me. I am going to open an issue report with the package creator and hope they can figure it out
