### ISSUE TITLE
[14.2.0-rc] Block Grid layout stylesheet not using correct URL

### ISSUE THREAD

**Issue by rickbutterfield** [umbraco/Umbraco-CMS#16897]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

14.2.0-rc

### Bug summary

When configuring a layout stylesheet against a Block Grid, the URL it is trying to be loaded from includes the backoffice path as part of the URL

### Specifics

Screenshot of the network requests failing, going to the incorrect URL
![image](https://github.com/user-attachments/assets/bfe949d1-f689-4a1e-9536-6483b9894e42)

Screenshot of the config returned from `/umbraco/management/api/v1/data-type` with the correct stylesheet URLs
![image](https://github.com/user-attachments/assets/540d1f22-ea0c-4e14-9dba-f5fdc649e423)

I think the culprit is this part of [`block-grid-manager.context.ts`](https://github.com/umbraco/Umbraco.CMS.Backoffice/blob/main/src/packages/block/block-grid/context/block-grid-manager.context.ts#L30C1-L33C4)

```ts
if (layoutStylesheet) {
    // Cause we await initAppUrl in setting the _editorConfiguration, we can trust the appUrl begin here.
    return this.#appUrl! + removeInitialSlashFromPath(transformServerPathToClientPath(layoutStylesheet));
}
```

When running the Backoffice project locally, `appUrl` will always resolve to `http://localhost:5173`, whereas when running within the context of a C# project, `appUrl` will resolve to the backoffice path.

A few lines down (L60-62) show where `#appUrl` is populated, and includes `getBackofficePath()`:
```ts
this.#initAppUrl = this.getContext(UMB_APP_CONTEXT).then((appContext) => {
    this.#appUrl = appContext.getServerUrl() + appContext.getBackofficePath();
});
```

### Steps to reproduce

- Blank v14.2.0-rc installation
- Create a test CSS file inside `/wwwroot`
- Configure a Block Grid datatype to have a layout stylesheet pointing to the above CSS file
- Check the browser console

### Expected result / actual result

**Expected result:**
If a stylesheet is configured from `/wwwroot/css/test.css`, the loaded file should be seen as `/css/test.css` in the Network tab of dev tool

**Actual result:**
Stylesheet tries to be loaded from `/umbracocss/test.css`

**Comment by rickbutterfield** [comment]
Resolved by https://github.com/umbraco/Umbraco.CMS.Backoffice/pull/2213

**Comment by rickbutterfield** [comment]
Hey @nielslyngsoe - this still appears to be an issue in 14.3.1. The layout stylesheets still include the `backofficeUrl` of `/umbraco` in the path.

![image](https://github.com/user-attachments/assets/c1b8fce0-ae89-4f9d-9b00-12ad43924f58)

Would you like me to open a new issue?

**Comment by nielslyngsoe** [comment]
Hi @rickbutterfield if you dont mind, then that would be perfect, thanks and sorry for the trouble.

**Comment by rickbutterfield** [comment]
@nielslyngsoe not a problem! Raised here https://github.com/umbraco/Umbraco.CMS.Backoffice/pull/2512
