### ISSUE TITLE
Document blueprints not working - blocks creation of new content nodes.

### ISSUE THREAD

**Issue by jonat123** [umbraco/Umbraco-CMS#16904]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

14.1.1

### Bug summary

Using the Document Blueprint feature does not work. After creating a blueprint based on a node, it is not possible to create new content nodes.

### Specifics

After creating a document blueprint based on a specific node, it is not possible to create new content nodes. When trying to click to create a new item nothing happens and no new node is created.

Looking in the console it seems there are some errors and warnings, which could be related:
![image](https://github.com/user-attachments/assets/334abc7f-9cb1-48d7-a604-7c23a2a9e4f6)E

Error 1: 
`UUI-BUTTON needs a `label` <uui-button look=​"secondary" color=​"default" pristine type=​"button">​#shadow-root (open)<!----><button id=​"button">​<!--?lit$803375614$--><!--?lit$803375614$--><!--?lit$803375614$--><slot class=​"label" style name>​↪ <uui-icon>reveal↪ #textreveal↪ #textreveal</slot>​<slot name=​"extra">​</slot>​</button>​<uui-icon name=​"icon-umb-deploy" aria-hidden=​"true">​slot#shadow-root (open)<!----><svg xmlns=​"http:​/​/​www.w3.org/​2000/​svg" viewBox=​"0 0 512 512" fill=​"currentColor">​<path d=​"M256.016 49.296c-117.152 0-212.112 94.96-212.112 212.096 0 80.32 44.656 150.192 110.496 186.192v-47.616c-42.656-31.344-70.496-81.712-70.496-138.576 0-94.896 77.2-172.096 172.112-172.096 94.896 0 172.08 77.2 172.08 172.096 0 56.88-27.84 107.248-70.496 138.592v47.6c65.84-36 110.496-105.872 110.496-186.192 0-117.136-94.944-212.096-212.08-212.096zm5.92 130.768a8 8 0 0 0-5.904-2.608 8 8 0 0 0-5.904 2.608l-82.288 90.128a7.981 7.981 0 0 0-1.408 8.624 7.978 7.978 0 0 0 7.312 4.768h34.688v171.12c0 4.416 3.584 8 8 8h79.136c4.416 0 8-3.584 8-8V283.6h34.672a7.978 7.978 0 0 0 7.312-4.768 7.991 7.991 0 0 0-1.408-8.624l-82.208-90.144z">​</path>​</svg>​</uui-icon>​" Open "<!--?lit$885253977$-->" on Umbraco.io "</uui-button>​`

Error 2: 
```
Uncaught (in promise) 
Object
type
: 
"close"
[[Prototype]]
: 
Object
constructor
: 
ƒ Object()
hasOwnProperty
: 
ƒ hasOwnProperty()
isPrototypeOf
: 
ƒ isPrototypeOf()
propertyIsEnumerable
: 
ƒ propertyIsEnumerable()
toLocaleString
: 
ƒ toLocaleString()
toString
: 
ƒ toString()
valueOf
: 
ƒ valueOf()
__defineGetter__
: 
ƒ __defineGetter__()
__defineSetter__
: 
ƒ __defineSetter__()
__lookupGetter__
: 
ƒ __lookupGetter__()
__lookupSetter__
: 
ƒ __lookupSetter__()
__proto__
: 
(...)
get __proto__
: 
ƒ __proto__()
length
: 
0
name
: 
"get __proto__"
arguments
: 
(...)
caller
: 
(...)
[[Prototype]]
: 
ƒ ()
[[Scopes]]
: 
Scopes[0]
set __proto__
: 
ƒ __proto__()
length
: 
1
name
: 
"set __proto__"
arguments
: 
(...)
caller
: 
(...)
[[Prototype]]
: 
ƒ ()
[[Scopes]]
: 
Scopes[0]
```

### Steps to reproduce

1. Create a document type and add it as root.
2. Allow the document type as a child node.
3. Create a new content node in the content section and give it a name.
4. Click on "..." after creating the new node
5. Select "Create Document blueprint" and give it a name.
6. Click the "..." next to the newly created content node
7. Click "Create"
8. Try and create a new content node with the Document blueprint 

### Expected result / actual result

I expected to be able to create a new content node based on my document blueprint under my content node.

The actual result of the above steps is that I am not able to create any new content nodes under the nodes I have used as my Document Blueprint.

**Comment by NguyenThuyLan** [comment]
Hi @jonat123 , I think this issue is related to https://github.com/umbraco/Umbraco-CMS/issues/16721, and It is fixed in release 14.2.0 by  this PR https://github.com/umbraco/Umbraco.CMS.Backoffice/pull/2147. So I will close this one and thank you
