### ISSUE TITLE
BuildModelsBuilderController should use IModelsGenerator instead of ModelsGenerator

### ISSUE THREAD

**Issue by kasparboelkjeldsen** [umbraco/Umbraco-CMS#16918]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

14 or newer

### Bug summary

I should be able to replace the ModelsGenerator used in the BuildModelsBuilderController (what happens when you click "Generate Models") by replacing the implementation of the ModelsGenerator in a Composer.

The Interface IModelsGenerator exists and is registered as a service, but it is not used in the controller.

### Specifics

By replacing the IModelsGenerator like so 

```csharp
public class ModelsBuilderComposer : IComposer
{
    public void Compose(IUmbracoBuilder builder)
    {
        var serviceDescriptor = ServiceDescriptor.Singleton<IModelsGenerator, MyModelsBuilder>();
        builder.Services.Replace(serviceDescriptor);
    }
}
```

I'd expect all generated models to use my implementation. This holds true if you use ModelsMode "SourceCodeAuto"

However if I use the "Generate Models" button in the ModelsBuilder tab, it will still use the Umbraco ModelsGenerator, as it's not injected with the interface but the concrete implementation.

A very small fix lin BuildModelsBuilderController.cs from this

```csharp
...
private readonly ModelsGenerator _modelGenerator;

public BuildModelsBuilderController(
    IOptionsMonitor<ModelsBuilderSettings> modelsBuilderSettings,
    ModelsGenerationError mbErrors,
    ModelsGenerator modelGenerator)
{
```

To this

```csharp
...
private readonly IModelsGenerator _modelGenerator;

public BuildModelsBuilderController(
    IOptionsMonitor<ModelsBuilderSettings> modelsBuilderSettings,
    ModelsGenerationError mbErrors,
    IModelsGenerator modelGenerator)
{
```

Will make it so the button also uses the registered implementation.

I will follow up with a pull request shortly.

### Steps to reproduce

1. Register your own IModelsGenerator replacing Umbracos implementation
2. Navigate to "Models Builder" tab in settings and hit "Generate Models"
3. Observe through debugging or other means that it uses Umbraco.Cms.Infrastructure.ModelsBuilder.Building.ModelsGenerator and not your implementation

### Expected result / actual result

I would expect the "Generate Models" button and controller to use the same IGenerateModels implementation as the "Auto Generate Models on Model Save" functionality.

**Comment by kjac** [comment]
Fixed in #16919 🥳
