### ISSUE TITLE
V14 - The name of the uploaded file in the Content section is not correct

### ISSUE THREAD

**Issue by nhudinh0309** [umbraco/Umbraco-CMS#16930]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

14.3.0-rc

### Bug summary

When you upload a file in the content section, the name of the file is not correct after saving. (see the image)
<img width="983" alt="image" src="https://github.com/user-attachments/assets/ef743215-aa20-42a2-9484-ce1e13f9ada4">

### Steps to reproduce

1. Create a content with Upload Article data type
2. Upload a file (ex: Article.pdf)
3. Save the changes
4. Reload the page

### Expected result / actual result

The name of the uploaded file is ".pdf". It should be "/media/tylbf3k3/article.pdf" as in V13

**Comment by iOvergaard** [comment]
This seems to have been fixed in v15, but unfortunately I have no pull request to link it to.
