### ISSUE TITLE
Property alias does not change or reflect correctly in new Backoffice

### ISSUE THREAD

**Issue by bassemelkadeem** [umbraco/Umbraco-CMS#16942]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

14.2.0-rc2

### Bug summary

When you try to change the property alias name it does not change and keep old value.

### Steps to reproduce

Create a document type and then create a property with text string called Page Title and try to change the alias for it to anther name and submit and save the old value keep shown.
![1](https://github.com/user-attachments/assets/ce0172aa-3c75-4907-847a-7b1590d04b70)
![2](https://github.com/user-attachments/assets/dada5e09-c94c-426b-bf64-8760f03f54b9)
![3](https://github.com/user-attachments/assets/2f21d4ac-f289-41fd-a018-2bff69a11a33)

### Expected result / actual result

Excepted result is to display new alias name for property

---
_This item has been added to our backlog AB#44590_

**Comment by NguyenThuyLan** [comment]
Hi @bassemelkadeem , thank for reporting this issue. 
I confirm that I can reproduce it on 14.3.0-rc.preview.7

**Comment by tmog** [comment]
Working on this... Appears to not be reproduceable on contrib anymore.

**Comment by tmog** [comment]
This is no longer reproduceable. 
Tested working in 
14.3.0-preview.62 
15.1.0-rc1.preview.16

**Comment by nul800sebastiaan** [comment]
I'll close this one then as it seems like it's been fixed in the mean time. @bassemelkadeem is you can still reproduce then let us know!
