### ISSUE TITLE
Clicking Insert Block In RTE redirects to frontpage of backoffice

### ISSUE THREAD

**Issue by kasparboelkjeldsen** [umbraco/Umbraco-CMS#16949]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

14.2

### Bug summary

Trying out blocks in the RTE to make support work in my preview plugin, I noticed I can't insert blocks anymore in 14.2

### Specifics

https://vimeo.com/1001620484

Would have embedded but video is 16 mb, so too big.

Otherwise see steps to reproduce.

### Steps to reproduce

Create element type and add to RTE on a document type

Try to insert block. Get redirected.

### Expected result / actual result

I would expect a block to be inserted in the RTE

**Comment by NguyenThuyLan** [comment]
I can still reproduce this on 14.3.0-rc.preview.22

**Comment by iOvergaard** [comment]
This issue seems to be caused by the same thing causing #17003. We have a fix ready and it is slated to go out with 14.3, which will see its first release candidate next week.
