### ISSUE TITLE
Large GIFs cause Umbraco on Azure Web App to restart when resizing in media section

### ISSUE THREAD

**Issue by karltynan** [umbraco/Umbraco-CMS#16940]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

13.4.1

### Bug summary

I have an Umbraco website running on Azure Web App (Linux). When I upload a large GIF image to the media section, the website crashes and restarts. I think this is because the media section resizes for previewing media items, as I do not allow GIFs to be resized on the front-end.

I have also tested this on Azure Web App (Windows) to see if it is Linux-specific or Umbraco-specific. I can confirm the issue is also on Windows.

1. Is there a known issue for this?
2. Perhaps there is a workaround to stop it resizing of GIFs in the media section? 
3. Can I restrict media image types allowed to upload?

### Specifics

- The Azure Web App (Linux) and database far exceed the minimum requirements needed to run Umbraco
- I have tried with 2mb GIFs and it struggles, but eventually got there with very high-priced Web App plan (not financially viable)
- I have tried with larger (10mb+ GIFs) and it kills the website
- May be specific to Linux, but currently trialling on Windows

### Steps to reproduce

1. Publish an Umbraco 13.4.1 website to an Azure Web App (Linux)
2. Try to upload a GIF that is quite large (or view a previously uploaded GIF that caused a restart) in media section
3. App crashes/restarts

### Expected result / actual result

The Umbraco website should not crash or restart when uploading large GIF images to the media section, or when previewing large GIFs in the media section.

**Comment by karltynan** [comment]
I have done a brief trial using Azure Web App (Windows) and it seems be the same issue. I have also compared using blob storage and media directory - both have the same issue.

**Comment by Migaroez** [comment]
Hey Karl, could you provide the 2 test images you used?

**Comment by karltynan** [comment]
[examples.zip](https://github.com/user-attachments/files/16814608/examples.zip)
Attached 2x images.

**Comment by karltynan** [comment]
The issue starts in the media section when the GIF is requested like such:
```/umbraco/backoffice/umbracoapi/images/GetBigThumbnail?originalImagePath=xxx```

**Comment by Migaroez** [comment]
Did some local testing

The memory allocation goes up to about 19GB for the biggest image you supplied (9MB) This seems to be solely from running the image trough ImageSharp when the cropUrl is resolved for the first time.

Regarding your questions
1. We know Imagesharp can have a large footprint I personally did not realize it would be this bad.
2. You could Copy the `ImageSharpImageUrlGenerator` class we provide and add a check inside the `GetImageUrl` method to return the raw url if it concerns a gif file. The unregister ours and register your `IImageUrlGenerator` in a composer.  I would not recommend this as you would then have to keep your implementation up to date with ours. But it is a workaround where you will still see the GIF inside the media preview just not resized.
3. Yup: https://docs.umbraco.com/umbraco-cms/reference/configuration/contentsettings
