### ISSUE TITLE
Can not customize CSS for login page 

### ISSUE THREAD

**Issue by bassemelkadeem** [umbraco/Umbraco-CMS#16957]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

14.2.0

### Bug summary

i try to follow the following article in Umbraco documentation to customize login page for Umbraco. but no work with me.
https://docs.umbraco.com/umbraco-cms/fundamentals/backoffice/login 

### Steps to reproduce

i create a css file and followed the article here 
https://docs.umbraco.com/umbraco-cms/fundamentals/backoffice/login

but the login page is still does not recognize the css file 

### Expected result / actual result

Expected result: is that the login page style must change by the new css file

**Comment by iOvergaard** [comment]
Hello, I can see the docs are wrong / has an old article. I have submitted a PR to reflect the changes here: https://github.com/umbraco/UmbracoDocs/pull/6381

However, there is another bug, which has been fixed with #16967 which can be expected for 14.3.0.
