### ISSUE TITLE
Umbraco 13.3.2 - Automatic redirect is not working

### ISSUE THREAD

**Issue by JeroenRoos** [umbraco/Umbraco-CMS#16966]
### Which Umbraco version are you using?

13.3.2

### Bug summary

When renaming a page Umbraco automatically creates a redirect. This redirect is visible in both the "umbracoRedirectUrl" database table, and the "Redirect URL Management" section in the backoffice.

Database:
![image](https://github.com/user-attachments/assets/b81cf0ce-0725-480c-bf5b-a7cb9617b6ee)

Backoffice:
![image](https://github.com/user-attachments/assets/8e56566e-b84e-4180-aa00-f5591b105c06)

When going to the URL which should be redirected, in this case "/redirect-test/", I get the default Umbraco Page Not Found error, instead of being redirected to the "/redirect-test-2/" URL.

### Steps to reproduce

In my case:
1. Create a content node. 
2. Rename the content node
3. Use the old URL to access the page
4. Get 404

**Comment by NguyenThuyLan** [comment]
Hi @JeroenRoos , thank you for reporting this issue. 
It seems was fixed on v13.4.1 like the video I tried to reproduce below

https://github.com/user-attachments/assets/b166893a-fc62-4696-b73c-e61d3503842f

So, I will close this issue.
