### ISSUE TITLE
Umbraco 14 Backoffice is not being logged in after logging in to Hangfire

### ISSUE THREAD

**Issue by SSPLGautam** [umbraco/Umbraco-CMS#16980]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

14.2.0

### Bug summary

I am trying to upgrade my project from 13 to 14. I have noticed some things that may be useful for me to solve this issue:

For the first instance when I run backoffice it authorizes it by sending Bearer token in the request. 
But when I run hangfire and authenticate it with Basic Authentication by configuring this :
![Screenshot_1](https://github.com/user-attachments/assets/3c9c05f8-0149-4e57-876c-e7c1f41256da)

```
  app.UseEndpoints(endpoints =>
  {
      endpoints.MapControllers();
      endpoints.MapHangfireDashboard("/hangfire", new DashboardOptions()
      {
          Authorization = [
            new HangfireCustomBasicAuthenticationFilter{
                   User = _config.GetSection("HangfireCredentials:UserName").Value,
                   Pass = _config.GetSection("HangfireCredentials:Password").Value
                                 }],
          IgnoreAntiforgeryToken = true
      });
  });
```
It sends Authorization header with Basic token to all requests on /Hangfire (which is okay): 
![Screenshot_2](https://github.com/user-attachments/assets/36ad5832-8ba8-4e44-aefe-f8f87d45a743)

But when I refresh umbraco backoffice again, it sends Basic token instead of Bearer which causes it not to be logged in to backoffice and asks to enter credentials via alter pop up box (which Umbraco never asks): 
![Screenshot_3](https://github.com/user-attachments/assets/c0d146de-6fed-4d0d-97fa-ccf42ec68c03)

If anyone can help me to solve this issue then please. Thanks in advance🙂

### Steps to reproduce

I'm trying to upgrade my umbraco 13 project to umbraco 14.2.0 and then this happens.

**Comment by nul800sebastiaan** [comment]
I suggest you take a look at how I set up Hangfire in my package for Umbraco to see how you can leverage Umbraco's existing authentication, so you won't have to use basic auth. 

You can either use the package (I recommend it, it's been properly secured for unauthorized access) or use parts of my code:

Code: https://github.com/nul800sebastiaan/Cultiv.Hangfire
Package: https://marketplace.umbraco.com/package/cultiv.hangfire

While I do not know why the basic auth option you've configured is causing problems for the Umbraco auth, I can tell you that this is not a scenario we can support, so in this case I'll close the issue. If you want to continue down the path you're trying to take then I would recommend asking on the forum at https://our.umbraco.com or on our Discord server in the `#help-with-umbraco` channel - https://discord.umbraco.com
