### ISSUE TITLE
Attended upgrade from v10 > v13 > v14 fails due to missing 'umbracoUser.key' column

### ISSUE THREAD

**Issue by CodeBunTes** [umbraco/Umbraco-CMS#16983]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

14.2.0

### Bug summary

If you attempt to use the attended upgrade mode to go from v13 to v14 on a site which has previously been upgraded from v10 to v13, the upgrade will fail to progress.

### Specifics

If you have a site which has been on v10, upgraded to latest v13 (as per version specific upgrade docs) and then attempt to go onwards to v14, all using attended upgrades, the final wizard to go to v14 will fail with an exception referencing lots of areas (SQLite, Umbraco Persistence and Umbraco Authorization). In the stored logs at this point it also records an error about SQLite Error 1: 'no such column: umbracoUser.key'.

![upgrade_error](https://github.com/user-attachments/assets/02414a42-dad6-4704-a5e0-56c1b1903bc2)

![upgrade_error_2](https://github.com/user-attachments/assets/087f7166-72ae-4e89-aa6a-1afe16bc9393)

### Steps to reproduce

1) Start a new project on v10.8.6 (currently the latest v10) using SQLite. Ensure it has been run through to a functional back office.
2) Stop the project and update the csproj file to reference .net8.0 and version 13.4.1 (latest v13). Run the project again and go through the attended upgrade process again.
3) Stop the project and update the csproj file again to reference 14.2.0 (latest v14). As per docs, you may also need to remove the UseInstallerEndpoints line from startup.cs here.
4) Attempt to run the upgrade process again to v14. After logging in, the upgrade wizard will immediately fail and the site will not be upgraded.

### Expected result / actual result

From this state, it is still possible to complete the v14 upgrade by enabling unattended upgrades in appsettings.json, after which everything will upgrade and then work fine. But as the current documentation recommendation is normally to go from v10 LTS to v13 LTS to v14, I would have expected both unattended and attended routes to allow this process. If not feasible to fix the attended route, then the use of unattended mode for older site databases could be included in the version specific upgrade steps documentation as mitigation.

**Comment by iOvergaard** [comment]
This will be fixed in the upcoming version 14.3, which is slated for release tomorrow. The issue arises because a migration needs to add a new column to the user table, but it cannot do so before being authorized, which it in turn cannot do without a functioning user table. It is fixed by marking the migration as a "pre-migration".
