### ISSUE TITLE
Block Grid block thumbnail not rendering, generated path incorrect

### ISSUE THREAD

**Issue by corey-cb** [umbraco/Umbraco-CMS#16985]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

14.2.0

### Bug summary

Thumbnail added to a block grid block does not render as the path is incorrect after setting.

### Specifics

On a Block Grid Property Editor, for any added Block that a thumbnail has been set, the image for the thumbnail does not render.
![image](https://github.com/user-attachments/assets/7868311a-a9c7-4021-933d-6cc893d97f51)
![image](https://github.com/user-attachments/assets/7175f91e-4cc2-405b-a84f-f783d0e28c61)

Upon inspecting the page, the URL being used for the thumbnail image incorrect and returning a 404 error.
![image](https://github.com/user-attachments/assets/11430b53-315e-44f8-9e9c-1842e43676f2)

The generated URL the backoffice is trying to use is https://localhost:44351/umbracoassets/thumbnails/rich-text.png

The URL would be correct without 'umbraco', so this is being incorrectly added to the URL. 

### Steps to reproduce

1. Create an Element doc type
2. Create a Block Grid data type
3. Add the element doc type as a block
4. Set a thumbnail for the block
5. See that no thumbnail is rendered in the block
6. Inspect the page to see the incorrect URL for the thumbnail being requested and returning a 404 error 

### Expected result / actual result

**Expected**: A URL such as `https://localhost:44351/assets/thumbnails/rich-text.png` to be generated for the thumbnail when choosing file with path `wwwroot/assets/thumbnails/rich-text.png.

**Actual**: Broken URL `https://localhost:44351/assets/thumbnails/rich-text.png` generated for the thumbnail.

---
_This item has been added to our backlog AB#45039_

**Comment by too-dark-park** [comment]
Is there any update on this? We are also experiencing the same issue. We are using CMS version 14.3.0

**Comment by iOvergaard** [comment]
I can confirm this is a regression. I have marked it as a sprint-candidate, which means we are including it in a development sprint.
