### ISSUE TITLE
Cannot change logged in user's password in Umbraco backoffice

### ISSUE THREAD

**Issue by stuff802** [umbraco/Umbraco-CMS#16989]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

14

### Bug summary

When logged in as an Administrator I can successfully change other backoffice user's passwords but not my own.

### Specifics

When logged into the backoffice there appears to be a bug where an Administrator can change other user's passwords but when trying to change the logged in user's password Umbraco throws an error saying the Old Password was not entered when in fact it was.

### Steps to reproduce

1. Select to change logged in user's password
2. Enter old password + new password in fields (see image)
![image](https://github.com/user-attachments/assets/dad878f0-f9fb-4ea6-b2ca-140f9ce8becb)

3. Click to Change password and receive error message that Old Password wasn't entered (when it was).
![image](https://github.com/user-attachments/assets/81f65e4e-4480-4525-984c-7eebd9d96d03)

### Expected result / actual result

I'd expect it to successfully change the password.

**Comment by madsrasmussen** [comment]
Hi @stuff802 

Thanks for the report. This issue has been fixed by this PR: https://github.com/umbraco/Umbraco.CMS.Backoffice/pull/2244 and will be part of 14.3
