### ISSUE TITLE
_auditService.GetLogs(_node.Id) - dates (Create and Update) are always 1/1/0001 12:00AM

### ISSUE THREAD

**Issue by ejbakqa** [umbraco/Umbraco-CMS#16998]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

13.4.1

### Bug summary

_auditService.GetLogs(_node.Id) - dates (Create and Update) are always 1/1/0001 12:00AM

### Steps to reproduce

        private readonly IAuditService _auditService;
        
_auditService.GetLogs(_node.Id) - dates (Create and Update) are always 1/1/0001 12:00AM

### Expected result / actual result

Given that t backoffice shows the correct dates I'd expect this information to show the same.

**Comment by NguyenThuyLan** [comment]
Logs get from umbracoLog table, SQL text doesn't have CreateDate and UpdateDate columns

**Comment by nikolajlauridsen** [comment]
Fixed in #17447 

Do note that this only sets the `CreateDate `, this is because the `CreateDate` is the timestamp when the audit log was created, and you cannot, and should not be, able to update an audit log item 😄, the value can also be seen in the database it's called `Datestamp` 😄
