### ISSUE TITLE
Insert AnchorLink in RTE bug

### ISSUE THREAD

**Issue by Gavin5656** [umbraco/Umbraco-CMS#17009]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

14.2.0

### Bug summary

Inserting an anchorlink into an RTE field inserts the incorrect markup in the A link

### Steps to reproduce

1. Ensure your Richtext Editor config has enabled the Anchor and Insert Link options under Data Types. 
2. On a page which contains a RTE create an anchor somewhere down the page.
3. At the top of the page, highlight some text and click the Insert/Edit Link icon to insert the link to your anchor.
4. In the Anchor / querystring input, enter the name of your anchor from step 2
5. Click the < > icon to view source
6. Note how the link has been set to /undefined/#youranchor e.g. 
`<a href="/undefined#cheese" title="Show me some cheese!" data-anchor="#cheese">Show me some cheese!</a>`

Additionally, if you manually refresh the current page by clicking at the end of the browser address bar url, hitting return to reload the page and then try the above, you'll find that instead of prefixing your anchor tag with /undefined, it pulls in the entire url from the current editor page beginning /umbraco.

### Expected result / actual result

Inserting an anchorlink should set the a link target to only the name specified in the anchor / querystring input  e.g.
`<a href="#cheese" title="Show me some cheese!" data-anchor="#cheese">Show me some cheese!</a>`

**Comment by iOvergaard** [comment]
I believe this has been fixed with 14.3, which is out now, but there is another issue related to anchored links (#17219) so I will keep this open for the time being.
