### ISSUE TITLE
Missing check for property editor in the sidebar modal when adding a new property

### ISSUE THREAD

**Issue by RasmusUmbraco** [umbraco/Umbraco-CMS#17004]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

14.2.0

### Bug summary

When adding a new property there's no check to confirm the selection of a property editor, which means I can have a property without a property editor, like this:
![image](https://github.com/user-attachments/assets/918b0bc3-fb79-4759-a798-42197a02dfa9)

I can't save the document type without the property editor, but it doesn't give me an error message - just shows like this:
![image](https://github.com/user-attachments/assets/193eeaeb-af78-4272-9d5a-f51a1d14ad0b)

### Steps to reproduce

1. Add a property to a document type
2. Don't select a property editor

**Comment by detjonmataj** [comment]
I noticed the same bug. When I built the standalone `backoffice` locally, it showed the expected errors if I tried to save without selecting an property editor. However, when I built the entire CMS, the issue persisted.

**Comment by nhudinh0309** [comment]
@RasmusUmbraco thanks for reporting this. I can reproduce it in v14.2.0.
I am also happy to tell you that it has been fixed in v15.1.1 (see the attachment)

https://github.com/user-attachments/assets/a74284ec-4a65-4e36-ad92-563a93de5553
