### ISSUE TITLE
v14 block editor not applying Overlay editor size

### ISSUE THREAD

**Issue by shearer3000** [umbraco/Umbraco-CMS#17000]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

14.2.0

### Bug summary

No matter what the Overlay editor size is set to on the individual block definitions on a Block Grid editor data type, the overlay/flyout is always the same size/width.
![image](https://github.com/user-attachments/assets/9a42b25e-15d9-4e35-b25a-739cb444d7ec)

### Steps to reproduce

Set the overlay editor size to Full, Large or Small and observe the flyout always being the same width/size:
![image](https://github.com/user-attachments/assets/029474e2-5392-400a-9a36-143b91897b39)

### Expected result / actual result

Expected: the flyout/overlay matches the preconfigured size (Small, Medium, Large, Full)
Actual: flyout/overlay is always the same size/width regardless (Medium size?)

---
_This item has been added to our backlog AB#43609_

**Comment by shearer3000** [comment]
will this target 14.3? thanks
https://our.umbraco.com/download/releases/1430

**Comment by mjpraxis** [comment]
@iOvergaard any chance this is something you are looking at in a near sprint?
I have tried to look at the Umbraco CMS code and I have no idea where to begin - even though it is a up-for-grab issue :-D

**Comment by iOvergaard** [comment]
@mjpraxis It is planned to be worked on very soon. I see that @nielslyngsoe has it on his board, so perhaps he has some insights?

**Comment by madsrasmussen** [comment]
Fixed by https://github.com/umbraco/Umbraco-CMS/issues/17324

**Comment by ProNotion** [comment]
Will this not also be backported to v13?

**Comment by nielslyngsoe** [comment]
@ProNotion to my knowledge this works fine in v.13? Are you experiencing this particular issue in v.13? If so then please report it as a new issue :-) Thanks

**Comment by nielslyngsoe** [comment]
Hi @shearer3000 you asked if this would target 14.3, but as you see the fix was released for 15.1.

I would recommend upgrading to latest 15. No reason to stay behind on v.14, it should be a light upgrade from 14 to 15. And things are working so much better in the latest version.

**Comment by shearer3000** [comment]
thanks for the update @nielslyngsoe - at the time i was asking about the target umbraco 15 wasn't out, but glad it has been fixed now :)
