### ISSUE TITLE
V13.5-RC Content fields to stay disabled when save and publishing

### ISSUE THREAD

**Issue by Yinzy00** [umbraco/Umbraco-CMS#17019]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

v13.5.0 RC

### Bug summary

We discovered that when attempting to save and publish with invalid fields, those fields remained disabled.

We tested this with text fields, media pickers, block lists

### Steps to reproduce

1. Add a mandatory text field to a doctype
2. Add a non mandatory text field to that doctype
3. Create an instance of that doctype
4. Save and publish without value
=> After validation text fields (and blocklist, mediapicker, ...) will stay disabled

### Expected result / actual result

Fields should be disabled while save and publishing but should be enabled after validation.

**Comment by Yinzy00** [comment]
Fixed in: #17018

**Comment by laimonas** [comment]
I have upgraded to latest
![image](https://github.com/user-attachments/assets/5431c4e0-b34b-439b-a9cf-d6d57e6f356f)
But still this is happening.

**Comment by laimonas** [comment]
Created new issue here
https://github.com/umbraco/Umbraco-CMS/issues/17054
I think one difference that our page can vary by culture
