### ISSUE TITLE
An issue with a custom Extension Condition in the Backoffice

### ISSUE THREAD

**Issue by AleksandrRogov** [umbraco/Umbraco-CMS#17014]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

14.2.0

### Bug summary

I am trying to apply a custom Extension Condition to a Workspace Context  manifest for it to be available only in a Content node of a specific Document Type. It generally works fine: it creates/destroys a context when the condition is fulfilled/unfulfilled. 

The problem arises when trying to navigate away from the Content node of a Document Type "A" (where the context should be available) to another Content node of Document Type "B" (where it should not be available) and then go back to "A". The context in this case cannot be resolved in the custom property editors, previews and etc., even though it is being created and it can be seen using the `umb-debug` helper tag.

### Specifics

I tried multiple things and created a project for you to try it out as well. But here are my findings:

- An Extension Condition works as expected: it creates or destroys a context when necessary.
- The context is being resolved correctly after a browser refresh or navigating away from the Content section somewhere else (for example to the Settings section)
- The issue arises when navigating away from a Content node of a Document Type "A" to another node of a Document Type "B" (where the condition is not fulfilled, which therefore destroys the workspace context) and then go back to "A" where the context can be seen being created (using the console log or by opening the `umb-debug` dialog) but, for some reason, this new context cannot be consumed by the element (the `consumeContext` is never being resolved).
- If to purposefully make the condition always truthful (which will make it so that the context is never being destroyed), and then try navigating away from "A" to "B" and then back to "A": it can be seen that the property editors and previews always consume the context that was created for the first time and all newly created contexts are not being consumed. Meanwhile, `umb-debug` always shows new context. (I've added an "id" property to the context to see this).

It almost feels like the elements try to consume the context from another host (that does not have the context anymore) but I am not sure.

Here's my condition:

```ts
import { UmbConditionBase } from "@umbraco-cms/backoffice/extension-registry";
import type { UmbControllerHost } from "@umbraco-cms/backoffice/controller-api";
import { UMB_DOCUMENT_WORKSPACE_CONTEXT } from "@umbraco-cms/backoffice/document";
import type {
    UmbConditionConfigBase,
    UmbConditionControllerArguments,
    UmbExtensionCondition,
} from "@umbraco-cms/backoffice/extension-api";

export type MyTestConditionConfig = UmbConditionConfigBase<"my.test.condition"> & {
    match: string[];
};

export class MyTestCondition extends UmbConditionBase<MyTestConditionConfig> implements UmbExtensionCondition {
    constructor(host: UmbControllerHost, args: UmbConditionControllerArguments<MyTestConditionConfig>) {
        super(host, args);

        //consuming document workspace context
        this.consumeContext(UMB_DOCUMENT_WORKSPACE_CONTEXT, (instance) => {
            this.observe(
                instance.structure.ownerContentType,
                (contentType) => {
                    if (!contentType) return;
                    this.permitted = this.config.match.includes(contentType.alias);

                    /* 
                        uncommenting this condition will make it so the context is not destroyed; it may seem to be a resolution to the problem 
                        - but in this case the context will still be available in the document type that it should not be available in and in some cases it will create duplicate contexts 
                        (for example when navigating away from the document type and back). 
                        so, this does not seem like a correct approach - the contexts must be cleaned up
                    */
                    // if (this.permitted) {
                    //     this.removeUmbControllerByAlias("ownerContentType");
                    // }
                },
                "ownerContentType"
            );
        });
    }
}
```

And here are the manifests for the condition and for my custom workspace context:
```ts
import type { ManifestCondition } from "@umbraco-cms/backoffice/extension-api";
import { MyTestCondition, type MyTestConditionConfig } from "./conditions/document-type-alias.condition";
import type { ManifestWorkspaceContext } from "@umbraco-cms/backoffice/extension-registry";

const conditionManifest: ManifestCondition = {
    type: "condition",
    name: "Test Document Type Alias Condition",
    alias: "my.test.condition",
    api: MyTestCondition,
};

const contextManifest: ManifestWorkspaceContext = {
    type: "workspaceContext",
    name: "Test Context",
    alias: `my.test.context`,
    api: () => import("./test.context.js"),
    conditions: [
        {
            alias: "my.test.condition",
            match: ["anotherPage", "regularPage"],
        } as MyTestConditionConfig,
    ],
};

export const contextManifests = [conditionManifest, contextManifest];
```

### Steps to reproduce

I created a test project for you to try it out. Sorry for the namings, had to create it quickly. I added multiple Document types (that you can import with uSync):

- Page ("page") - context should NOT be resolved.
- Another Page ("anotherPage") - context should be resolved (a page with a Block Grid)
- Regular Page ("regularPage") - context should be resolved

Steps:
1. Try to open one of the content nodes with a green icon
2. Open the one with a red icon
3. Go back to any of the nodes with a green icon. You will see either in a custom preview or a property editor a message that the context has not been resolved.
4. If you open a debug dialog and find MyTestContext, open its properties, you will see that the debug can resolve it. But for some reason, everything else on a page can't.
5. You can also open a browser console for additional information about the context (it will show when it is created/destroyed and etc.)

The code for the backoffice is in the `UmbBackofficeApp`, I hope the structure there is self explanatory, otherwise please let me know. And let me know if you have any other questions.

Here's a link to a project: [ExtensionConditionIssueSln.zip](https://github.com/user-attachments/files/16898422/ExtensionConditionIssueSln.zip)

### Expected result / actual result

Expected: property editors and/or previews should consume newly created context (the one that is being seen by the `umb-debug`).

Actual: property editors, previews cannot consume the context in a specific situation described above. Even though it's being visible in the `umb-debug`.

**Comment by nielslyngsoe** [comment]
Hi @AleksandrRogov 

We ship a condition doing exactly this as part of 14.3 — So I hope you are able to upgrade and use this. The Condition Alias is `Umb.Condition.WorkspaceContentTypeAlias`.

It came as part of this PR:
https://github.com/umbraco/Umbraco.CMS.Backoffice/pull/1550

So here you can see the code and maybe spot the difference?

**Comment by AleksandrRogov** [comment]
@nielslyngsoe thank you! it makes sense to me now.

**Comment by AleksandrRogov** [comment]
@nielslyngsoe sorry for coming back to this issue. Just now had time to get back to this. 

We upgraded the project to v15 and I also modified the condition in the manifest of the context to use the `Umb.Condition.WorkspaceContentTypeAlias` and I am hitting the same issue. The context does not get resolved between the document types. This might not have worked in v14.3 as well (since the code is mostly the same). 

The context is always resolved when the Backoffice App is loaded for the first time (after browser reload), but going back and forth in the same Workspace - it stops being resolved.

I upgraded my repro project I sent earlier to v15, I can send the zip folder if needed, so you can reproduce it easier.
Here's the manifest now for the Workspace Context:

```ts
const contextManifest: UmbExtensionManifest = {
    type: "workspaceContext",
    name: "Test Context",
    alias: `my.test.context`,
    api: () => import("./test.context.js"),
    conditions: [
        {
            alias: "Umb.Condition.WorkspaceContentTypeAlias",
            oneOf: ["anotherPage", "regularPage"],
        },
    ],
};

export const contextManifests = [contextManifest];
```

And as you can see in the gif lower, the context is not getting resolved in the preview, though it can be seen in the debug window.
![2024-12-03_18-17-58](https://github.com/user-attachments/assets/b9b88476-a86a-428e-af59-b5581c5c974a)
