### ISSUE TITLE
Deleted member is not logged out and cannot log out.

### ISSUE THREAD

**Issue by DORE-PD** [umbraco/Umbraco-CMS#17013]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

13.4.1

### Bug summary

If a logged-in member is deleted, “MemberManager.IsLoggedIn()” continues to return “true”.
This causes the “UmbLoginStatusController.HandleLogout()” method to return "AccessDenied". As a result, the logout link cannot be used. 
The member no longer has any authorizations (group assignment is no longer there, ...). But he cannot log out unless he deletes the cookies.

### Steps to reproduce

1. Create member
2. Log in as this member
3. Delete member
4. Reload page

### Expected result / actual result

The member should be logged out automatically if the member has been deleted.
Or at least they should be able to log out without an AccessDenied being returned.

---
_This item has been added to our backlog AB#46120_

**Comment by elit0451** [comment]
We addressed "_Or at least they should be able to log out without an AccessDenied being returned._" in #17807.

About "_The member should be logged out automatically_" - it will do so after the expiration of the [SecurityStampValidatorOptions.ValidationInterval](https://learn.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.identity.securitystampvalidatoroptions.validationinterval?view=aspnetcore-9.0) (which is set to 30 mins by default by ASP.NET Core) and then a page refresh. 🙂

**Comment by kjac** [comment]
Closed as fixed in #17807
