### ISSUE TITLE
UmbracoHelper does not contain a definition for RenderMacroAsync

### ISSUE THREAD

**Issue by s-ryan** [umbraco/Umbraco-CMS#17020]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

14.1.1

### Bug summary

UmbracoHelper does not contain a definition for RenderMacroAsync

// render pest treatment using the pest theme
if (_formGuid.ToString() == "50e1840c-a41b-4e02-84a7-508f2c7e4be2")
{
    await Umbraco.RenderMacroAsync("renderUmbracoForm", new { FormGuid = Model.Value("formGuid"), FormTheme = "pesttreatment", ExcludeScripts = "1" });
        
}

### Specifics

We are attempting to render a form using a specific theme. The documentation advises:

When you are rendering your form directly in your template, you need to specify your theme by filling out the FormTheme attribute:

@await Umbraco.RenderMacroAsync("renderUmbracoForm", new {FormGuid="1ec026cb-d4d3-496c-b8e8-90e0758c78d8", FormTheme="MyFormTheme", ExcludeScripts="0"})
If you do not pick and/or set a theme, the default theme will be used to render the form.

https://docs.umbraco.com/umbraco-forms/developer/themes

However the UmbracoHelper does not contain a definition for RenderMacroAsync

### Steps to reproduce

![image](https://github.com/user-attachments/assets/91bfd4a1-fb2d-471b-8b5d-4976b7968bd8)

### Expected result / actual result

Ability to render a form using a specified theme

**Comment by enkelmedia** [comment]
Macros was removed from Umbraco with the release of v14, I think you need to render your forms using a view component.

```
@await Component.InvokeAsync("RenderForm", new { formId = Guid.Parse("<form guid>"), theme = "default", includeScripts = false })
```

https://docs.umbraco.com/umbraco-forms/developer/rendering-forms

I think that issue here is that the docs has not been updated to reflect the fact that macros has been removed.

I submitted a issue in the docs-repo https://github.com/umbraco/UmbracoDocs/issues/6443

**Comment by iOvergaard** [comment]
Hello @s-ryan,

As @enkelmedia has stated, Macros were deprecated in Umbraco 13 and ultimately removed in Umbraco 14. There is something missing in the docs, so I appreciate your contribution, @enkelmedia.

I hope this helps you on your way, @s-ryan. I will proceed with closing this issue as it seems a documentation change is what is needed.
