### ISSUE TITLE
V13.4.0 ContentPublishingNotification behaviour broken, runs after the prepublishing validation instead of before

### ISSUE THREAD

**Issue by nzdev** [umbraco/Umbraco-CMS#17023]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

13.4.2

### Bug summary

Modifying content just before publishing by using ContentPublishingNotification now leaves content in Published (Pending Changes) state. There are no new versions created.

### Specifics

Prior to v13.4.0 the behaviour during publishing was:

1. Raises ContentPublishingNotification
2. Umbraco validates the content to be published
4. Publishes the content
5. Raises the ContentPublishingNotification
6. Content in Published State

As of https://github.com/umbraco/Umbraco-CMS/pull/16331  the behaviour is now:

1. Umbraco validates the content to be published
2. Raises ContentPublishingNotification
3. Publishes the content
4. Raises the ContentPublishingNotification
5. Content in Publishing (Pending Changes) state

The original behaviour, now broken, which used to work like ContentSavingNotification , but at actual publish time, was useful as you could modify the content to stamp the actual time the content was first published (which may be a significant delay between last updated and when content may be scheduled for publishing) as a property of the content, so you could distinguish between first published date and most recently published date as an example.

I'd suggest the breaking change from https://github.com/umbraco/Umbraco-CMS/pull/16331 be reverted, and if required add a new notification ContentPublishingCanPublishNotification to run after the validation to suit the original poster of the discussions usage.

### Steps to reproduce

1. Add a content type with a property called "firstPublishedDate" that is a date time property.
2. Add this composer / notification handler

```
using Umbraco.Cms.Core.Composing;
using Umbraco.Cms.Core.Events;

public class UpdateFirstPublishedTimeDuringPublishingComposer: IComposer
{
   public void Compose(IUmbracoBuilder composition) {
     composition.AddNotificationHandler<ContentCopyingNotification, UpdateFirstPublishedTimeNotificationHandler >();
  }
}

public class UpdateFirstPublishedTimeNotificationHandler : INotificationHandler<ContentPublishingNotification>
{
 public void Handle(ContentPublishingNotification notification)
 {
         foreach (var entity in notification.PublishedEntities)
         {
             var propValueOriginal = entity.GetValue<string>("firstPublishedDate");
             if (string.IsNullOrEmpty(propValueOriginal)){
                 content.SetValue("firstPublishedDate", DateTime.UtcNow);
            }
         }
 }
}
```

3. Create a new document of this content, set the name, and save and schedule publish for 5 mins from current time.
4. At this point, before the content is published, the "firstPublishedDate" should be empty.
5. After ~ 5 mins just before the content is published, the notification handler runs
6. The content is published.
7. The CMS shows the content as having only the published version, and the value of "firstPublishedDate" is set.
8. The state of the content in the cms is "Published (Pending Changes)" (undesirable)

### Expected result / actual result

1. Add a content type with a property called "firstPublishedDate" that is a date time property.
2. Add this composer / notification handler

```
using Umbraco.Cms.Core.Composing;
using Umbraco.Cms.Core.Events;

public class UpdateFirstPublishedTimeDuringPublishingComposer: IComposer
{
   public void Compose(IUmbracoBuilder composition) {
     composition.AddNotificationHandler<ContentCopyingNotification, UpdateFirstPublishedTimeNotificationHandler >();
  }
}

public class UpdateFirstPublishedTimeNotificationHandler : INotificationHandler<ContentPublishingNotification>
{
 public void Handle(ContentPublishingNotification notification)
 {
         foreach (var entity in notification.PublishedEntities)
         {
             var propValueOriginal = entity.GetValue<string>("firstPublishedDate");
             if (string.IsNullOrEmpty(propValueOriginal)){
                 content.SetValue("firstPublishedDate", DateTime.UtcNow);
            }
         }
 }
}
```

3. Create a new document of this content, set the name, and save and schedule publish for 5 mins from current time.
4. At this point, before the content is published, the "firstPublishedDate" should be empty.
5. After ~ 5 mins just before the content is published, the notification handler runs
6. The content is published.
7. The CMS shows the content as having only the published version, and the value of "firstPublishedDate" is set.
8. The state of the content in the cms is Published

**Comment by markadrake** [comment]
I'm experiencing this exact behavior on the latest v13.5.2.

![image](https://github.com/user-attachments/assets/39afc365-f887-4629-99a8-6950dff5b60c)

- I set some values during the `ContentPublishingNotification`.
- The page is saved, but the changes have not been published; they are created as a pending version.

**Comment by Zeegaan** [comment]
Sorry for the late response here, seems like this has entirely missed our radar 😓 
I've put this in my current sprint to take a look at 🕵️

**Comment by Zeegaan** [comment]
Hello there 👋 I've looked at your issue & use case, and discussed it with the team. 
While it's unfortunate, that this no longer works, it was working by accident ( a bug 🐛). 
We cannot recommend changing content in a `ContentPublishingNotification`, as the content as already been saved, and thus these changes will not get saved.

I've come up with an alternate solution, that solves your problem 💪 
By using a `ContentSavingNotification` and checking on the published state, we can achieve the same effect of only manipulating the date when we are publishing, hope that helps 🙏 


```
using Umbraco.Cms.Core.Composing;
using Umbraco.Cms.Core.Events;
using Umbraco.Cms.Core.Models;
using Umbraco.Cms.Core.Notifications;

public class UpdateFirstPublishedTimeDuringPublishingComposer : IComposer
{
    public void Compose(IUmbracoBuilder composition) => composition.AddNotificationHandler<ContentSavingNotification, UpdateFirstPublishedTimeNotificationHandler>();
}

public class UpdateFirstPublishedTimeNotificationHandler : INotificationHandler<ContentSavingNotification>
{
    public void Handle(ContentSavingNotification notification)
    {
        foreach (IContent entity in notification.SavedEntities)
        {
            if (entity.PublishedState is PublishedState.Publishing)
            {
                var propValueOriginal = entity.GetValue<string>("firstPublishedDate");
                if (string.IsNullOrEmpty(propValueOriginal))
                {
                    entity.SetValue("firstPublishedDate", DateTime.UtcNow);
                }
            }
        }
    }
}
```

**Comment by MarkMcDonald** [comment]
Sorry to hop on this here but I'm not sure where to ask this or if it's worth a new ticket, but am hitting a similar issue - but slightly different - and wondered if there was an approach we should be taking.

We're upgrading notification handlers and have a situation where we need to save the content - then run an operation to create a record in Dataverse - then update the content again with the GUID from Dataverse. 

In older versions of Umbraco with events, and I think some earlier versions with notifications we didn't have so much trouble doing this. I think in some earlier versions supressing events / notifications didn't prevent updating of the published content cache either, but seems to now. 

We obviously need to avoid a chain of notification handlers retriggering notification handlers but struggling to find and answer on the best approach.

Update: To clarify slight difference that causes us an issue in this particular case is that we need the IContent item to have and ID. At ContentSavingNotification it doesn't.

**Comment by AndyButland** [comment]
Would suggest a new issue @MarkMcDonald given this one is closed, but maybe first take the question to the forum and see if with the help there you can figure out a solution.  If you hit a wall then please create an issue, ideally with the simplest steps you can to illustrate what you are trying to do and the problem you are running into.

**Comment by ewuski** [comment]
I have the reported issue in 13.12.0 and can confirm Zeegaan's solution works perfectly. Thanks for sharing!
