### ISSUE TITLE
Deletion dialog shows incorrect block label

### ISSUE THREAD

**Issue by kumaheiyama** [umbraco/Umbraco-CMS#17030]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

14.2.0

### Bug summary

When deleting a block in a block list, where the block has a _custom_ name with UFM syntax, the dialog shows the label without injecting the references value.

### Specifics

Example below, the blocks have a property "anchor" which shows in the list, but in the dialog the label is shown as the block editor value "{=anchor} block"

![image](https://github.com/user-attachments/assets/2a78cfe5-43d9-487e-b2ef-91036412f719)

Error occurs in Firefox 130.0 and Chrome 128.0.6613.120

### Steps to reproduce

* Create document type "block" with an anchor property (textstring), element type. Set label to use UFM "{=anchor}".
* Create another document "doc" type with a block list with "block"
* Create document with document type "doc", add a few blocks to the list. Set anchor to something unique for each
* Delete a block from the list, should show the UFM label instead of the anchor value

### Expected result / actual result

Dialog shows block label same way as in block list, so the user can determine they are deleting the correct block

---
_This item has been added to our backlog AB#43833_

**Comment by iOvergaard** [comment]
Hello @kumaheiyama, thanks for testing. I can reproduce this and we are going to fix it.

**Comment by leekelleher** [comment]
Resolved in https://github.com/umbraco/Umbraco.CMS.Backoffice/pull/2423 for Umbraco 15.1.
