### ISSUE TITLE
Import Document type not possible

### ISSUE THREAD

**Issue by paulsoerensen** [umbraco/Umbraco-CMS#17058]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

14.2.0

### Bug summary

I'm trying to import a document type by the Import item isn't visible in the menu opened by clicking ... right to Document Type

### Specifics

![image](https://github.com/user-attachments/assets/b975bb55-c9c0-48e5-ac40-133d9987d4a6)

### Steps to reproduce

Create a new site with dotnet cli and go into settings and click --- right to document type

### Expected result / actual result

Possibility to Export Document Type - and export individual document which is also not possible

**Comment by iOvergaard** [comment]
Hi, thank you for reporting. This feature is being reintroduced in the upcoming [version 14.3](https://our.umbraco.com/download/releases/1430), which is slated for release next week. If you have the capacity for it, feel free to test the release candidate `14.3.0-rc` which is available on Nuget.

**Comment by paulsoerensen** [comment]
thx
