### ISSUE TITLE
[BUG] V13.5.0 Content fields to stay disabled when save and publishing

### ISSUE THREAD

**Issue by laimonas** [umbraco/Umbraco-CMS#17054]
### Which Umbraco version are you using?

13.5.0

### Bug summary

![validation](https://github.com/user-attachments/assets/0c5e698c-7c13-4956-b439-7128d38f1106)

We discovered that when attempting to save and publish with invalid fields, those fields remained disabled.
The same as closed issue, maybe one difference that our page can vary by culture
https://github.com/umbraco/Umbraco-CMS/issues/17019

### Steps to reproduce

Add a mandatory text field to a doctype
Add a non mandatory text field to that doctype
Create an instance of that doctype
Save and publish without value
=> After validation text fields (and blocklist, mediapicker, ...) will stay disabled

**Comment by laimonas** [comment]
I have look into last fixed introduced int 13.5.0 RC
https://github.com/umbraco/Umbraco-CMS/pull/17018/files#diff-e0285787f867b6af6e7475492117224e187b2d4297af96f98fcba2b9f5cfff10

In my case i'm hitting this place
![image](https://github.com/user-attachments/assets/14aae4d1-bb50-4b84-8a40-8c0d8d76aa4b)
And i think after `showValidationNotification();` `$scope.$broadcast("formSubmittedValidationFailed")` is missing.

**Comment by laimonas** [comment]
I Also tried with fresh 13.5.0 install.
Steps to reproduce.
1. Create document type with required field
2. Eanable "Allow vary by culture" on this document type
3. Create one any additional language
4. "Save and Publish"

I think this is really critical bug left with this release.

**Comment by nielslyngsoe** [comment]
Fixed by https://github.com/umbraco/Umbraco-CMS/pull/17077

**Comment by DempseySbaiz** [comment]
I still have this exact issue after upgrading to 13.5.1.

**Comment by Wolfkhan66** [comment]
We still have this same issue on 13.5.1.

**Comment by laimonas** [comment]
@DempseySbaiz @Wolfkhan66 Keep in mind i registered this bug for document types that vary by culture, and for me this fix is working. But prob with this fix they introduce bug for document that doesn't vary by culture.
https://github.com/umbraco/Umbraco-CMS/issues/17187

**Comment by Wolfkhan66** [comment]
Ah sorry, yes we have this issue for content that does not vary by culture.
