### ISSUE TITLE
Block item validation error with node type

### ISSUE THREAD

**Issue by kv-nifr** [umbraco/Umbraco-CMS#17061]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

14.2.0

### Bug summary

Hello

I have a simple block item, which only contains a content picker.

Unless I pick specific node under "node type" I get this error in a block grid using the block item.
![Skærmbillede 2024-09-16 082533](https://github.com/user-attachments/assets/80f7a6cf-9d5f-4585-b9f8-6109c407462b)

I can still pick something with my content picker I just get the root node instead of the content node I'm trying to target.

### Steps to reproduce

1. Get a fresh umbraco 14.2.0 installation 
2. Setup block item with content picker and chose something else than specific node under node type
3. Add a block grid to another document type with the block item created in step 2.

Here is an video with my setup and the error.
https://github.com/user-attachments/assets/36e8b8fa-9a55-4714-a22a-03f8d16ddd07

### Expected result / actual result

**Expected behaviour**: A list of all the available nodes under a node of a specific type.
**Actual behaviour**: An error and the content picker returns me the root node.

**Comment by authoritymikael** [comment]
Confirmed that we have the same error.

**Comment by nhudinh0309** [comment]
Thanks for reporting this issue @kv-nifr and @authoritymikael.
I was able to reproduce it in v14.2.0.  And I am also happy to report that it has been fixed in v14.3.1 (see the attachment)

https://github.com/user-attachments/assets/20b27cdc-4e21-481e-a5cc-6a38e9c1f0dd
