### ISSUE TITLE
v13.5.0 - Blocklist error - Block's selection in the clipboard, no longer works (after update from v13.4.1)

### ISSUE THREAD

**Issue by afabri73** [umbraco/Umbraco-CMS#17071]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

13.5.0

### Bug summary

When I try to duplicate a block, I can copy the block correctly, but I can't select it anymore and I see an error in the console log

**CLIPBOARD**

![Clipboard](https://github.com/user-attachments/assets/b05c353b-8359-443a-969b-e620069be671)

**ERROR**

![Error on select clipboard obj](https://github.com/user-attachments/assets/e5a39f25-2801-43a5-a4b9-9c60ed849283)

### Steps to reproduce

- Copy a block
- Click on paste
- Select block to paste from clipboard (here I cannot select any block)

### Expected result / actual result

After block selection, I must see the selected block marked and I can paste it as a duplicate

**Comment by bradleykronson** [comment]
Confirmed, we are seeing exactly the same.
