### ISSUE TITLE
"The authenticated user do not have access to this resource" for Editors on RTE with custom CSS linked

### ISSUE THREAD

**Issue by authoritymikael** [umbraco/Umbraco-CMS#17084]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

14.2.0

### Bug summary

On pagetypes where a RTE propery is added and a custom CSS-file is added in settings on that property. 

When logged on as a Editor we get this error message. Works when logged on as Administrator

![Screenshot 2024-09-17 at 14 53 06](https://github.com/user-attachments/assets/fcad041b-730b-4460-ab85-9f18c5f0acb9)

### Steps to reproduce

- Have a pagetype with an RTE-editor property
- Add an custom CSS file to the RTE 
- Log on as an Editor and create or just open a node from the pagetype, and the error message appear

---
_This item has been added to our backlog AB#45488_

**Comment by NguyenThuyLan** [comment]
The API to get the stylesheet file is Forbidden.
![image](https://github.com/user-attachments/assets/ea765b25-1689-43cb-a796-ebd726ff67d2)

**Comment by drcluc** [comment]
I also experience this in Umbraco v14.3

**Comment by nikolajlauridsen** [comment]
Fixed in #17442
