### ISSUE TITLE
ufm-label-value cannot handle nested content

### ISSUE THREAD

**Issue by kv-nifr** [umbraco/Umbraco-CMS#17082]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

14.2.0

### Bug summary

Hello,

I have a document type with a blockGrid "contributors" with 1 allowed Block type "byline".
"byline" has a Content Picker property "contributor" and a Text Box "postTitle".

I want to set the label of "byline" to be the name of the content from the content picker. So something like this:
{=contributor.name}

But since ufm-label-value is set to "contributor.name" the label is empty. 

### Steps to reproduce

- Create a document type with a blockGrid property. 
- Create a block type with a content picker property
- Allow the block type to be inserted and set the label {=propertyName.name}

### Expected result / actual result

**Expected**: Label is set to the name of the nested object from the content picker
**Actual**: Label is empty

**Comment by NguyenThuyLan** [comment]
Hi @kv-nifr , UFM (Umbraco Flavored Markdown) currently does not support getting the name of the selected Content Picker, but more features are planned for v15, this issue is one of them.

**Comment by AaronSadlerUK** [comment]
@NguyenThuyLan Is this supported now?

I have put a post on the forum, but it would be great to know how to do it

https://forum.umbraco.com/t/ufm-nested-properties/3256
