### ISSUE TITLE
Installation screen responsiveness 13 in

### ISSUE THREAD

**Issue by wpplumber** [umbraco/Umbraco-CMS#17105]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

14.2.0

### Bug summary

The installation screen with hidden Umbraco logo.

![image](https://github.com/user-attachments/assets/6c6b800c-aedf-4b8f-a49e-50abeb1d8387)

### Steps to reproduce

1. Install Umbraco 14.2.0 on Mac OS
2. Open website on MS edge with screen resolution 13.3-inch (1280 x 800)

### Expected result / actual result

Expected to get the screen with visible logo as in the [Umbraco 14](https://youtu.be/EzpFI77d-6U?t=180) features video here.

**Comment by iOvergaard** [comment]
Fixed with https://github.com/umbraco/Umbraco.CMS.Backoffice/pull/2413
