### ISSUE TITLE
v14.2.0 - Upload Field empty after save

### ISSUE THREAD

**Issue by CelenaLuna** [umbraco/Umbraco-CMS#17100]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

14.2.0

### Bug summary

When trying to upload video with Upload Field (including in Media), the video shown, can be view and you allow to click save/publish. However, when check the video in content/media again, it is empty

### Specifics

Upload Field seem to take time to cache the file but instead of wait for the cache process to finished and avaliable to upload, Umbraco allow to save then move on.
In further inspection, I saw the file indeed upload but stuck in cache folder. 
I suspect that it still try to upload in the background after save/publish content but Save/Publish phase already pass long ago
Techincally, you could wait few minutes for the file uploaded to the server before save/publish it. But there is no indication to show it was finished. End-User also didn't know that they have to wait for the file to upload

### Steps to reproduce

- Create a template with Upload Field
- Create a content with that template
- Upload a file (I tested with a 50 MB file)
- Save & Publish once the video shown and playable
- Check the content that just upload

2nd way
- Create a video in Media
- Upload the video
- Save 

### Expected result / actual result

Check the Video Media/Content that just save/publish, the Upload Field is empty

**Comment by iOvergaard** [comment]
Hello @CelenaLuna, thanks for reporting this. I can confirm it's an issue in 14.2. This issue will be fixed in 15.0, which is due for release soon. You can test out the Release Candidate, which was just released today on Nuget.
