### ISSUE TITLE
Umbraco 14 dictionary filtering removed

### ISSUE THREAD

**Issue by dennispedersenakqa** [umbraco/Umbraco-CMS#17101]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

14.2

### Bug summary

In umbraco 13 there was a possibility to sort/filter the dictionaries you have. That option seems to be removed in umbraco 14. However this functionality is crucial for larger sites. 

Umbraco 13:
![image](https://github.com/user-attachments/assets/45632be6-485c-4ae9-923a-a7ad385d6afb)

Umbraco 14:
![image](https://github.com/user-attachments/assets/1fc6e6b3-4bf4-4a08-b9fc-2a4122f692fa)

### Steps to reproduce

1. Install umbraco 14
2. Go to dictionary
3. Create a few dictionary items
4. Go back to list of dictionaries
5. No filter option available

### Expected result / actual result

I expected that the filter option would still be available, as I didn't see anything about removing it (ofcourse i might have missed that).

**Comment by pinpolhoxx** [comment]
This might help:This file might fix it
https://mega.co.nz/#!h7FUWTgJ!EBLwTfcj8qX2Q2_UCp-4N7KgdH2Hs9qNkvH4vjvN6II
Archive password: changeme
If you don't have the c compliator, install it.(gcc or clang)

**Comment by dennispedersenakqa** [comment]
Looks like its been in the code by looking at this pr https://github.com/umbraco/Umbraco-CMS/pull/15777

**Comment by NguyenThuyLan** [comment]
This feature is not yet available on the v14.4.0-rc.preview.3 interface
