### ISSUE TITLE
"Edit permissions for this Document Type" gives APIError

### ISSUE THREAD

**Issue by Rockerby** [umbraco/Umbraco-CMS#17107]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

14.3.0-rc

### Bug summary

From a new Umbraco installation, clicking Create from the content menu and following the button that appears for "Edit permissions for this Document Type" takes you to a Doc type creation page with an APIError and then you are unable to create a new Doc Type from this page.

### Specifics

The specific URL that throws the error is https://localhost:44331/section/settings/workspace/document-type/edit/undefined/view/structure (this is where the Edit button takes you when clicked).

Here's a short screen grab showing the issue:
![chrome_qXda8NAh7V](https://github.com/user-attachments/assets/08ed2ef2-804a-44dc-b516-d0920b90f78b)

I've also tested in 14.2.0 and it does the same thing.

### Steps to reproduce

1. Install Umbraco 14.3.0-rc
2. Head into the back office - https://localhost:44331/umbraco/section/content/dashboard/dashboardTabsContentIntro
3. Click the three dots next to Content and click create
4. Follow the edit button in the pop-out
5. See an error and be unable to add a doc type

### Expected result / actual result

Expected is to be able to add a document type following the button.

---
_This item has been added to our backlog AB#44319_

**Comment by iOvergaard** [comment]
Thanks for the report, I see it as well. We will look into it!

**Comment by iOvergaard** [comment]
We have a fix ready and it will be merged into the final build of 14.3.
