### ISSUE TITLE
V14 Doesn't respect the allowed language in the content editor

### ISSUE THREAD

**Issue by rsoeteman** [umbraco/Umbraco-CMS#17124]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

14.2.0

### Bug summary

Given an Editor that is allowed to edit the Dutch Language only

![image](https://github.com/user-attachments/assets/9a214298-a59f-44d1-859a-7115bb36ebaf)

I would not expect that this user can see and select the English version of the Content item. 

![image](https://github.com/user-attachments/assets/72e45d6f-0f76-4a97-981d-421ed299dd82)

### Specifics

See above

### Steps to reproduce

- Create the Duch Language
-  Ensure a document type can use this langiage
- Create the a usergroup and assign the Duch Language only
-  Create a user based on above group
- Login a s the user
- edit content and switch to the english version of the page

### Expected result / actual result

I would not expect to see the language where I don't have access to

**Comment by madsrasmussen** [comment]
Hi @rsoeteman 

Thanks for the report. The allow language setting gives write permission to a language. A user can still read the content for all languages, but not update, publish, etc. When it was introduced pre-14, it was decided to do it this way so a user could still read the language they should translate from. 

The read-only UI has been reintroduced in 14.3.
