### ISSUE TITLE
Issue with uploading images containing _[width]x[height] in the file name

### ISSUE THREAD

**Issue by AndriiDzendzia** [umbraco/Umbraco-CMS#17128]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

13.5.0

### Bug summary

When the editor uploads an image with _[width]x[height] at the end of the file name (e.g., image_1270x770.png), the image cannot be retrieved using IMediaService.GetMediaByPath.

### Specifics

- No error message is displayed; the image simply cannot be found via IMediaService.GetMediaByPath.
- Example file name: image_1270x770.png

### Steps to reproduce

1. Log in to the Umbraco back office.
2. Navigate to the media section and upload an image with a file name containing _[width]x[height], such as image_1270x770.png.
3. Try to retrieve the uploaded image using IMediaService.GetMediaByPath.
4. Notice that the image cannot be found.

### Expected result / actual result

Expected result (one of):

- The image should be uploaded and retrievable through IMediaService.GetMediaByPath, regardless of the naming pattern.
- The image shouldn`t be uploaded and the error message should be shown.

Actual result:

- The image is uploaded successfully, but it cannot be retrieved using IMediaService.GetMediaByPath when the file name contains _[width]x[height].

**Comment by NguyenThuyLan** [comment]
Hi @AndriiDzendzia , thank for reporting this issue.
I was able to reproduce this issue from v13.5.1, v14.3.0 to v15.
In GetMediaByPath method, mediaPath is removed some regex string include "_" and number so the real media path can not found in database
![image](https://github.com/user-attachments/assets/e1175412-5979-4ab8-9cf4-8614d5a6c20a)

**Comment by Zeegaan** [comment]
Fixed in https://github.com/umbraco/Umbraco-CMS/pull/17314, thanks for reporting 🐛
