### ISSUE TITLE
Delete option for Block grid item from the content

### ISSUE THREAD

**Issue by harikrishna43** [umbraco/Umbraco-CMS#17127]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

14.2.0

### Bug summary

I am trying to create a website using Umbraco CMS v14.2.0.
I am using a block grid. I have set up the content. When I was trying to delete content, getting a model with the Blockgrid label without a variable value.
1. Delete modal popup with invalid label value
![image](https://github.com/user-attachments/assets/c83c2852-2407-4616-8e2d-4be708a7b5d7)

2. URL picker
- when I tried to add link, I am getting GUID of the selected page, also it is not place Link title as older version works.
![image](https://github.com/user-attachments/assets/c6c5b962-646a-4b96-95cb-80cead9b2a10)
![image](https://github.com/user-attachments/assets/5a3b8a33-06d5-4a67-b0e7-6540a890d9bf)

### Steps to reproduce

Steps for delete/remove issue
1. Add element in block grid data type using a variable in Label.
![image](https://github.com/user-attachments/assets/a141dcfe-5c43-46cf-96b8-4cade22d5ecf)
2. Add content and then 
3. try to delete it

Steps for Url picker issue
1. add Url picker into any element
2. try to select the created page for the link and check

### Expected result / actual result

1. for deleting/removing the block grid, it should show the proper value of the variable of the block grid item label.
2. As per the previous feature for the URL picker, it should show the Link name and URL(currently showing the GUID of the selected page).

**Comment by iOvergaard** [comment]
Hello, thank you for the detailed report. This almost certainly looks like it's the same issue as described in #17030. I would like to track the problem in that issue instead, so please forgive me for closing this issue. If you think this was done in error, please feel free to reopen.

**Comment by harikrishna43** [comment]
Thanks @iOvergaard.  

I have also added another issue for the URL picker.
