### ISSUE TITLE
Block List in Inline Mode does not work when inside a Block Grid component

### ISSUE THREAD

**Issue by AndersBrohus** [umbraco/Umbraco-CMS#17134]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

14.2

### Bug summary

If you are using inline mode in a Block List inside a Block Grid component you can't open the element and edit the content.

### Steps to reproduce

Create an new element type with a textstring named "Text" - Use that element type in a Block List and turn "Inline mode" on, after that create a new element type which contains this block list and add the new element type to a block grid.

![msedge_Bwb6gsTZVK](https://github.com/user-attachments/assets/a9d218a9-7e94-40f9-aa31-24e8ec5e7ac8)

### Expected result / actual result

I would expect that my element would open so it could be edited.

---
_This item has been added to our backlog AB#44704_

**Comment by sekmenhuseyin** [comment]
I had the same issue and I tried to fix it for half a day until I figured it was an umbraco bug. So thank you for opening this issue
