### ISSUE TITLE
Block List in Inline Mode does not support custom labels

### ISSUE THREAD

**Issue by AndersBrohus** [umbraco/Umbraco-CMS#17133]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

14.2

### Bug summary

If you are using inline mode in a Block List there is no support for custom labels - I'll just get the specificed Umbraco Flavored Markdown shown instead of the label if i toggle inline mode off it works correctly

### Steps to reproduce

Create an new element type with a textstring named "Text" - Use that element type in a Block List and turn "Inline mode" on.

![image](https://github.com/user-attachments/assets/cf8e088c-630e-4fda-8aae-5e9a1eb080ed)

### Expected result / actual result

That my custom label is shown

---
_This item has been added to our backlog AB#44703_

**Comment by iOvergaard** [comment]
Hello, thank you for the report. This is certainly related to #17030 and #17143. We'd like to get it fixed.
