### ISSUE TITLE
Issue with Saving Changes in Umbraco Back Office After Switching Browser Tabs

### ISSUE THREAD

**Issue by 110percentdev** [umbraco/Umbraco-CMS#17153]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

10.8.6

### Bug summary

Hello, I've been having issues with bugs in the Umbraco back end, my site is hosted on Umbraco cloud.

I'm getting bugs with not being able to save changes in the back office after I browse any other tab on my browser, whether changing content, document types, scripts, stylesheets or changes to a template. When I make a change to anything for the first time it works all fine, it seems to be an issue when I click on any other tabs on my browser to view the content on the front end, then go back to the tab I'm editing, make a change and try to save it either comes up with validation errors or the save button just never saves and spinning icon never saves. This isn't ideal as it means I can only work with one tab or have to reload the page everytime.

Here is a video example of the problem: https://www.loom.com/share/ce32db37b10242ae9f235e4b12b6da24?sid=7ad6c2a9-1b79-4d39-94e9-0a74cdc5d866

I've updated to the latest version of Umbraco CMS. Current versions: CMS 10.8.6 - Forms 10.5.7 - Deploy 10.2.7

### Steps to reproduce

https://www.loom.com/share/ce32db37b10242ae9f235e4b12b6da24?sid=7ad6c2a9-1b79-4d39-94e9-0a74cdc5d866

**Comment by NguyenThuyLan** [comment]
Hi @110percentdev , sorry to say that v10 has entered the support security phase only. I tested your issue on v13 and v14. It did not happen. So I recommend you update to this new version to get support as well as the bug fix. I will close this issue and feel free to reopen if you have any further details.
