### ISSUE TITLE
Solution not buid in VS 2022

### ISSUE THREAD

**Issue by ednsinf** [umbraco/Umbraco-CMS#17155]
Solution not buid in VS 2022

### Bug summary

Severity	Code	Description	Project	File	Line	Suppression State
Error (active)	MSB4044	The "GetUmbracoBuildVersion" task was not given a value for the required parameter "GitCommitIdShort".	Umbraco.Cms, Umbraco.Cms.Api.Common, Umbraco.Cms.Api.Delivery, Umbraco.Cms.Api.Management, Umbraco.Cms.Imaging.ImageSharp, Umbraco.Cms.Imaging.ImageSharp2, Umbraco.Cms.Persistence.EFCore, Umbraco.Cms.Persistence.EFCore.Sqlite, Umbraco.Cms.Persistence.EFCore.SqlServer, Umbraco.Cms.Persistence.Sqlite, Umbraco.Cms.Persistence.SqlServer, Umbraco.Cms.StaticAssets, Umbraco.Cms.Targets, Umbraco.Core, Umbraco.Examine.Lucene, Umbraco.Infrastructure, Umbraco.JsonSchema, Umbraco.PublishedCache.NuCache, Umbraco.Templates, Umbraco.TestData, Umbraco.Tests.AcceptanceTest.UmbracoProject, Umbraco.Tests.Benchmarks, Umbraco.Tests.Common, Umbraco.Tests.Integration, Umbraco.Tests.UnitTests, Umbraco.Web.Common, Umbraco.Web.UI, Umbraco.Web.Website	C:\Users\e_dns\.nuget\packages\umbraco.gitversioning.extensions\0.2.0\build\Umbraco.GitVersioning.Extensions.targets	5	

### Specifics

Severity	Code	Description	Project	File	Line	Suppression State
Error (active)	MSB4044	The "GetUmbracoBuildVersion" task was not given a value for the required parameter "GitCommitIdShort".	Umbraco.Cms, Umbraco.Cms.Api.Common, Umbraco.Cms.Api.Delivery, Umbraco.Cms.Api.Management, Umbraco.Cms.Imaging.ImageSharp, Umbraco.Cms.Imaging.ImageSharp2, Umbraco.Cms.Persistence.EFCore, Umbraco.Cms.Persistence.EFCore.Sqlite, Umbraco.Cms.Persistence.EFCore.SqlServer, Umbraco.Cms.Persistence.Sqlite, Umbraco.Cms.Persistence.SqlServer, Umbraco.Cms.StaticAssets, Umbraco.Cms.Targets, Umbraco.Core, Umbraco.Examine.Lucene, Umbraco.Infrastructure, Umbraco.JsonSchema, Umbraco.PublishedCache.NuCache, Umbraco.Templates, Umbraco.TestData, Umbraco.Tests.AcceptanceTest.UmbracoProject, Umbraco.Tests.Benchmarks, Umbraco.Tests.Common, Umbraco.Tests.Integration, Umbraco.Tests.UnitTests, Umbraco.Web.Common, Umbraco.Web.UI, Umbraco.Web.Website	C:\Users\e_dns\.nuget\packages\umbraco.gitversioning.extensions\0.2.0\build\Umbraco.GitVersioning.Extensions.targets	5	

### Steps to reproduce

Open colution in VS 2022

### Expected result / actual result

Build

**Comment by iOvergaard** [comment]
Hello @ednsinf,
Your error log says that the MSBuild task "GetUmbracoBuildVersion" is failing. This issue arises from tools installed through Nuget. Please ensure you are on the latest .NET 9 Release Candidate as the main branch requires that. Please also ensure that you have restored all nuget packages after installing that. Let me know if that works for you!

**Comment by dawoe** [comment]
@iOvergaard could also be that @ednsinf just downloaded the source and not cloned it.
In that case you don't have a git repo and the git version tasks will fail.
See https://dev.to/dawoe/debugging-the-umbraco-source-code-for-specific-version-5ahk

**Comment by iOvergaard** [comment]
Oh, good point, @dawoe. That is perhaps something worth looking into to get the source to work without a git repository.

@ednsinf, when you get time, please report back if you are using the Git version or direct source code of Umbraco.

**Comment by nul800sebastiaan** [comment]
Hi @ednsinf! Please note: you typically won't need to build Umbraco from the source code unless your goal is to contribute to its development. Umbraco is designed to be [highly extensible and flexible](https://docs.umbraco.com/umbraco-cms/extending/), allowing you to build and customize it to your specific needs without accessing the core source code. Instead, we recommend [installing Umbraco as described in the documentation](https://docs.umbraco.com/umbraco-cms/fundamentals/setup), and then extending it through available tools and frameworks to suit your requirements.

However, if you're interested in contributing to Umbraco, we'd love to hear more! Let us know what you're trying to do, and we’ll be happy to help you get started.
