### ISSUE TITLE
Block grid Create Button Label doesn't do anything

### ISSUE THREAD

**Issue by abaker93** [umbraco/Umbraco-CMS#17179]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

14.2.0

### Bug summary

Adding a Custom Button Label doesn't change the "Add content" label in the content editor.

### Steps to reproduce

1. Type anything into a block grid Create Button Label field.
![Screenshot 2024-10-02 133932](https://github.com/user-attachments/assets/72ea8ce9-83f9-43b9-8e47-4e50df6e8d61)

2. Button label doesn't change in the content editor.
![Screenshot 2024-10-02 134809](https://github.com/user-attachments/assets/e93a0d9f-bbc1-4809-9aa3-9a3c2889a5eb)

---
_This item has been added to our backlog AB#44701_

**Comment by iOvergaard** [comment]
Hi, @abaker93, thanks for this report. I could reproduce it by adding areas to a block and inserting a custom button label. The label did not take precedence if there were only one or several blocks. The label of the block was shown (Add <block label>) if there was only one block available, and if there were more than one, it then showed "Add content".

We'd like to look into this, but I will add the up for grabs label just in case someone else would like to take a jab at this.

**Comment by iOvergaard** [comment]
This is being taken care of by @Bakersbakebread
