### ISSUE TITLE
v15RC1: Previews a broken

### ISSUE THREAD

**Issue by bergmania** [umbraco/Umbraco-CMS#17175]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

Umbraco 15.0.0-rc1

### Bug summary

Previews shows the published data

### Steps to reproduce

Enter preview mode and see the content

### Expected result / actual result

I expect to see the draft content

**Comment by Zeegaan** [comment]
Fixed in https://github.com/umbraco/Umbraco-CMS/pull/17181
