### ISSUE TITLE
[BUG] V13.5.1 The content fields become disabled after clicking "Save and Publish"

### ISSUE THREAD

**Issue by adavidovic92** [umbraco/Umbraco-CMS#17187]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

13.5.1

### Bug summary

https://github.com/user-attachments/assets/b88e1755-a455-44c2-ba3a-47196be4f02d

It was found that when trying to save and publish with invalid (i.e., required) fields, those fields remained disabled.

### Steps to reproduce

- Create a document type with mandatory fields.
- Create an instance of that document type.
- Click "Save and Publish" with the fields left empty.
- After validation, the fields will remain disabled.

### Expected result / actual result

After validation, the fields have to be active

**Comment by Zeegaan** [comment]
I can reproduce this, thanks for reporting 🐛

**Comment by Zeegaan** [comment]
Just for info, this worked in 13.5.0, so seems something in the patch has broken something 😁

**Comment by Zeegaan** [comment]
Fixed in https://github.com/umbraco/Umbraco-CMS/pull/17285 🚀
