### ISSUE TITLE
Upgrading Umbraco 13.5.1 to 14.3.0 fails

### ISSUE THREAD

**Issue by martinthogersen** [umbraco/Umbraco-CMS#17182]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

13.5.1

### Bug summary

While attempting to upgrade Umbraco from version 13.5.1 to 14.3.0, the process fails with the following error: "Invalid column name 'listView'." (Full error details below).

The error seems to stem from an issue in the migration plan, as indicated by the relevant code:
https://github.com/umbraco/Umbraco-CMS/blob/release-14.3.0/src/Umbraco.Infrastructure/Migrations/Upgrade/UmbracoPlan.cs

Here are the relevant log entries:

> [13:20:51 INF] Create Primary Key:
>  ALTER TABLE [umbracoUserGroup2GranularPermission] ADD CONSTRAINT [PK_umbracoUserGroup2GranularPermissionDto] PRIMARY KEY CLUSTERED ([id])
> [13:20:51 INF] Create Index:
>  CREATE NONCLUSTERED INDEX [IX_umbracoUserGroup2GranularPermissionDto_UserGroupKey_UniqueId] ON [umbracoUserGroup2GranularPermission] ([userGroupKey]) INCLUDE ([uniqueId])
> [13:20:51 INF] Create Index:
>  CREATE NONCLUSTERED INDEX [IX_umbracoUserGroup2GranularPermissionDto_UniqueId] ON [umbracoUserGroup2GranularPermission] ([uniqueId])
> [13:20:51 INF] Create Foreign Key:
>  ALTER TABLE [umbracoUserGroup2GranularPermission] ADD CONSTRAINT [FK_umbracoUserGroup2GranularPermission_umbracoUserGroup_key] FOREIGN KEY ([userGroupKey]) REFERENCES [umbracoUserGroup] ([key])
> [13:20:51 INF] Create Foreign Key:
>  ALTER TABLE [umbracoUserGroup2GranularPermission] ADD CONSTRAINT [FK_umbracoUserGroup2GranularPermission_umbracoNode_uniqueId] FOREIGN KEY ([uniqueId]) REFERENCES [umbracoNode] ([uniqueId])
> [13:20:51 WRN] No last synced Id found, this generally means this is a new server/install. A cold boot will be triggered.
> [13:20:52 INF] Registered with MainDom, localContentDbExists? True, localMediaDbExists? True
> [13:20:52 INF] Creating the content store, localContentDbExists? True
> [13:20:52 INF] Creating the media store, localMediaDbExists? True
> [13:20:52 ERR] Exception (e7a213eb).
> Microsoft.Data.SqlClient.SqlException (0x80131904): Invalid column name 'listView'.
>    at Microsoft.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action1 wrapCloseInAction)
>    at Microsoft.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action1 wrapCloseInAction)
>    at Microsoft.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
>    at Microsoft.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
>    at Microsoft.Data.SqlClient.SqlDataReader.TryConsumeMetaData()
>    at Microsoft.Data.SqlClient.SqlDataReader.get_MetaData()
>    at Microsoft.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString, Boolean isInternal, Boolean forDescribeParameterEncryption, Boolean shouldCacheForAlwaysEncrypted)
>    at Microsoft.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean isAsync, Int32 timeout, Task& task, Boolean asyncWrite, Boolean inRetry, SqlDataReader ds, Boolean describeParameterEncryptionRequest)
>    at Microsoft.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, TaskCompletionSource1 completion, Int32 timeout, Task& task, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry, String method)
>    at Microsoft.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method)
>    at Microsoft.Data.SqlClient.SqlCommand.ExecuteReader(CommandBehavior behavior)
>    at Microsoft.Data.SqlClient.SqlCommand.ExecuteDbDataReader(CommandBehavior behavior)
>    at StackExchange.Profiling.Data.ProfiledDbCommand.ExecuteDbDataReader(CommandBehavior behavior) in C:\projects\dotnet\src\MiniProfiler.Shared\Data\ProfiledDbCommand.cs:line 211
>    at Umbraco.Cms.Infrastructure.Persistence.FaultHandling.FaultHandlingDbCommand.<>c__DisplayClass35_0.<ExecuteDbDataReader>b__0()
>    at Umbraco.Cms.Infrastructure.Persistence.FaultHandling.FaultHandlingDbCommand.<>c__DisplayClass38_01.<Execute>b__0()
>    at Umbraco.Cms.Infrastructure.Persistence.FaultHandling.RetryPolicy.ExecuteAction[TResult](Func1 func)
>    at Umbraco.Cms.Infrastructure.Persistence.FaultHandling.FaultHandlingDbCommand.Execute[T](Func1 f)
>    at Umbraco.Cms.Infrastructure.Persistence.FaultHandling.FaultHandlingDbCommand.ExecuteDbDataReader(CommandBehavior behavior)
>    at NPoco.Database.<>c__DisplayClass298_0.<ExecuteReaderHelper>b__0()
>    at NPoco.Database.ExecutionHook[T](Func1 action)
>    at NPoco.Database.ExecuteReaderHelper(DbCommand cmd)
>    at NPoco.Database.ExecuteDataReader(DbCommand cmd, Boolean sync)
>    at NPoco.AsyncHelper.RunSync[T](Task1 task)
>    at NPoco.Database.QueryImp[T](T instance, Expression1 listExpression, Func2 idFunc, Sql Sql, PocoData pocoData)+MoveNext()
>    at System.Collections.Generic.List1..ctor(IEnumerable1 collection)
>    at System.Linq.Enumerable.ToList[TSource](IEnumerable1 source)
>    at NPoco.Database.Fetch[T](Sql sql)
>    at Umbraco.Cms.Infrastructure.Persistence.Repositories.Implement.ContentTypeCommonRepository.GetAllTypesInternal()
>    at Umbraco.Extensions.AppCacheExtensions.<>c__DisplayClass0_01.<GetCacheItem>b__0()
>    at Umbraco.Cms.Core.Cache.SafeLazy.<>c__DisplayClass1_0.<GetSafeLazy>b__0()
> --- End of stack trace from previous location ---
>    at Umbraco.Cms.Core.Cache.ObjectCacheAppCache.Get(String key, Func1 factory, Nullable1 timeout, Boolean isSliding)
>    at Umbraco.Cms.Core.Cache.DeepCloneAppCache.Get(String key, Func1 factory, Nullable1 timeout, Boolean isSliding)
>    at Umbraco.Extensions.AppCacheExtensions.GetCacheItem[T](IAppPolicyCache provider, String cacheKey, Func1 getCacheItem, Nullable1 timeout, Boolean isSliding)
>    at Umbraco.Cms.Infrastructure.Persistence.Repositories.Implement.ContentTypeCommonRepository.GetAllTypes()
>    at Umbraco.Cms.Infrastructure.Persistence.Repositories.Implement.ContentTypeRepository.GetAllWithFullCachePolicy()
>    at Umbraco.Cms.Infrastructure.Persistence.Repositories.Implement.ContentTypeRepositoryBase1.PerformGetAll(Int32[] ids)
>    at Umbraco.Cms.Core.Cache.FullDataSetRepositoryCachePolicy2.GetAllCached(Func2 performGetAll)
>    at Umbraco.Cms.Core.Cache.FullDataSetRepositoryCachePolicy2.GetAll(TId[] ids, Func2 performGetAll)
>    at Umbraco.Cms.Infrastructure.Persistence.Repositories.Implement.EntityRepositoryBase2.GetMany(TId[] ids)
>    at Umbraco.Cms.Core.Services.ContentTypeServiceBase2.GetAll(Int32[] ids)
>    at Umbraco.Cms.Infrastructure.PublishedCache.PublishedSnapshotService.LoadContentFromDatabaseLocked(Boolean onStartup)
>    at Umbraco.Cms.Infrastructure.PublishedCache.PublishedSnapshotService.<EnsureCaches>b__56_3()
>    at Umbraco.Cms.Infrastructure.PublishedCache.PublishedSnapshotService.LockAndLoadContent(Func1 action)
>    at Umbraco.Cms.Infrastructure.PublishedCache.PublishedSnapshotService.<EnsureCaches>b__56_0()
>    at System.Threading.LazyInitializer.EnsureInitializedCore[T](T& target, Boolean& initialized, Object& syncLock, Func1 valueFactory)
>    at System.Threading.LazyInitializer.EnsureInitialized[T](T& target, Boolean& initialized, Object& syncLock, Func1 valueFactory)
>    at Umbraco.Cms.Infrastructure.PublishedCache.PublishedSnapshotService.EnsureCaches()
>    at Umbraco.Cms.Infrastructure.PublishedCache.PublishedSnapshotService.GetDocumentUid(Int32 id)
>    at Umbraco.Extensions.UmbracoBuilderExtensions.<>c__DisplayClass0_0.<AddNuCache>b__5(Int32 id)
>    at Umbraco.Cms.Core.Services.IdKeyMap.GetKeyForId(Int32 id, UmbracoObjectTypes umbracoObjectType)
>    at Umbraco.Cms.Infrastructure.Migrations.Upgrade.V_14_0_0.MigrateCharPermissionsToStrings.<>c__DisplayClass5_2.<Migrate>b__5(String permission)
>    at System.Linq.Enumerable.SelectEnumerableIterator2.MoveNext()
>    at System.Linq.Enumerable.SelectManySingleSelectorIterator2.MoveNext()
>    at NPoco.SqlServer.SqlBulkCopyHelper.BuildBulkInsertDataTable[T](IDatabase db, IEnumerable1 list, SqlBulkCopy bulkCopy, SqlBulkCopyOptions sqlBulkCopyOptions, InsertBulkOptions insertBulkOptions)
>    at NPoco.SqlServer.SqlBulkCopyHelper.BulkInsert[T](IDatabase db, IEnumerable1 list, SqlBulkCopyOptions sqlBulkCopyOptions, InsertBulkOptions insertBulkOptions)
>    at NPoco.SqlServer.SqlBulkCopyHelper.BulkInsert[T](IDatabase db, IEnumerable1 list, InsertBulkOptions insertBulkOptions)
>    at NPoco.DatabaseTypes.SqlServerDatabaseType.InsertBulk[T](IDatabase db, IEnumerable1 pocos, InsertBulkOptions options)
>    at NPoco.Database.InsertBulk[T](IEnumerable1 pocos, InsertBulkOptions options)
>    at Umbraco.Cms.Infrastructure.Migrations.Upgrade.V_14_0_0.MigrateCharPermissionsToStrings.Migrate()
>    at Umbraco.Cms.Infrastructure.Migrations.MigrationBase.Run()
>    at Umbraco.Cms.Infrastructure.Migrations.MigrationPlanExecutor.RunMigration(Type migrationType, MigrationContext context)
>    at Umbraco.Cms.Infrastructure.Migrations.MigrationPlanExecutor.RunScopedMigration(Transition transition, MigrationPlan plan)
>    at Umbraco.Cms.Infrastructure.Migrations.MigrationPlanExecutor.RunMigrationPlan(MigrationPlan plan, String fromState)

### Steps to reproduce

1. Set up a website using Umbraco 13.5.1.
2. Attempt to upgrade the website to Umbraco 14.3.0.

---
_This item has been added to our backlog AB#44668_

**Comment by bergmania** [comment]
Hi @martinthogersen 

We are three people that have tried to reproduce without any luck.

Do you have any packages installed, that could interfear?  Alternatively can you describe your setup i more details.

**Comment by martinthogersen** [comment]
@bergmania I'll get back to you early next week. Thank you for looking into it!

**Comment by martinthogersen** [comment]
@bergmania 
It's quite strange. I attempted to set up a new project using version 13.5.1 with the same dependencies, and I was able to upgrade to version 14.3.0 without any issues.

I've compared the logs from both installations: the left side displays the output from a clean 13.5.1 install, while the right side shows the results from my upgrade attempt.

Before the error occurs, I see this message:

> No last synced Id found, this generally means this is a new server/install. A cold boot will be triggered.

However, this isn't a new server or installation - it's an existing website.
Do you have any suggestions?

![image](https://github.com/user-attachments/assets/c44801c1-8653-4d73-b956-bbd82082a2fb)

**Comment by bergmania** [comment]
@martinthogersen 

That log message should only occur, if the folder`/umbraco/Data/TEMP/DistCache` is missing or empty. I just tested when that file is removed, but I can still not reproduce, but I think I understand what is going on.

I'll look into a fix

**Comment by ewuski** [comment]
Hi, I got the same issue when upgrading from 13.13.0 to 14.3.4.
`cmsContentType` table was missing `listView `column.

I fixed it by executing on the DB:

```
ALTER TABLE dbo.cmsContentType
ADD listView UNIQUEIDENTIFIER NULL;
```

Not sure if it is the right thing to do, but it fixed the issue.

My solution was successively upgraded from Umbraco 7, so it was not a fresh 13 install if it makes any difference.
