### ISSUE TITLE
[V15-RC1] TipTap RTE Config Feedback - Disabling an extension does not remove from toolbar

### ISSUE THREAD

**Issue by warrenbuckley** [umbraco/Umbraco-CMS#17188]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

15.0.0-RC1

### Bug summary

When using the new TipTap editor I have disabled an extension in this case the `Underline` one, but still have it in the toolbar configuration.

Navigate to a content node with the editor, the Underline button is still in the toolbar and clicking on it does nothing.

### Specifics

<img width="1293" alt="image" src="https://github.com/user-attachments/assets/09ff2c09-48dc-429b-9d92-a06eede22609">

### Steps to reproduce

Configure the TipTap RTE editor defaults to disable the Underline extension and keep everything else as is.

### Expected result / actual result

I expected the Underline toolbar button to not appear when using the editor inside a content node.

---
_This item has been added to our backlog AB#44725_

**Comment by iOvergaard** [comment]
Yeah, still working on this one. There is currently no other property editor that reacts to changes from one configuration property to another. However, we have some ideas being tossed around how to do it. The 'underline' extension and button belongs together in a 1-1 relationship, however the 'Align' extension has 6 different actions, which may or may not have buttons. This is the issue we currently need to resolve.

Mr. @leekelleher is on the case and we hope to have something either in an upcoming RC or 15.1 depending on how it goes 👍

**Comment by warrenbuckley** [comment]
OK thanks for the update @iOvergaard 
Be curious to see/learn how you resolve this with code and UX
