### ISSUE TITLE
v14.3 - Components in Content view do not update after save/publish

### ISSUE THREAD

**Issue by mjpraxis** [umbraco/Umbraco-CMS#17183]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

14.3.0

### Bug summary

When saving or publishing a content node in the backoffce. The components (like "Links", "History") is not updated.
And the same problem are there with the property values if they has been changed during for example "ContentSavingNotification".

In version 13 it works like it should - save / publish updates the values in the view.

### Steps to reproduce

**Simple test of the Save&Publish update**
Create a simple DocumentType

Create a content node with name "abc"

Save&Publish

Make sure to be on the "Info" section

Change the name of the node to "123"

Save&Publish

The path in the "Links" box do not update to the new path.

**Test of the "ContentSavingNotification" update issue**
On the document type above add a simple label string property named testlabel

Register a simple ContentSavingNotification in the program.cs builder section

'builder.AddNotificationHandler<ContentSavingNotification, SavingNotification>()'

And implement it with
```public class SavingNotification() : INotificationHandler<ContentSavingNotification>
    {
        public void Handle(ContentSavingNotification notification)
        {
            var item = notification.SavedEntities.FirstOrDefault();
            var label = item.Properties.FirstOrDefault(x => x.Alias == "testlabel");
            label.SetValue("new value");
        }
    }
```

Now back to the backoffice and edit the content node.

Check that the label has no value

Click "Save"

Check if the label now has the value "new value". It should still be empty ""

Refresh the page or switch to another section like "Media" and back - this will update the label value.

### Expected result / actual result

Expected result from v13
![hTJrrqhKoe](https://github.com/user-attachments/assets/c75760e5-7c1b-4e08-abe2-c4ef12b0fb1f)

Actual result from v14.3
Update "Links"
![kfm9o9QEca](https://github.com/user-attachments/assets/6eed427f-cbda-45f5-ad94-48fdd9ee4167)

---
_This item has been added to our backlog AB#44699_

**Comment by iOvergaard** [comment]
Good point, @mjpraxis. Thanks for reporting this. I think we have been too focused on getting properties to update. We need all the other stuff as well.
