### ISSUE TITLE
Umbraco 13.5.1 does not refresh block list custom view html after publishing to production.

### ISSUE THREAD

**Issue by teeto** [umbraco/Umbraco-CMS#17184]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

13.5.1

### Bug summary

I am making changes on an html custom view of a Block list editor and after publishing the changes it does not refresh on production site. As always i increase the version on my appseettings.json. It was working fine until i updated to 13.5.1 from 13.4.1.
If i enter the html path in the browser it shows the html updated, so i guess it is not the browser cache but an umbraco cache issue after deployment. I have ftp the site and the file is copied after publishing. I have tried restarting the site too.

### Specifics

this is my RuntimeMinification conf
 "RuntimeMinification": {
   "CacheBuster": "Version",
   "Version": "87"
 }

### Steps to reproduce

make changes to a block list editor custom html view.
set cachebuster to "Version"
Increase version 
publish changes to production site from visual studio

---
_This item has been added to our backlog AB#44706_

**Comment by iOvergaard** [comment]
Thanks for reporting this. We'll look into it!

**Comment by kjac** [comment]
Hi there @teeto,

I've been trying to reproduce this, but I am failing 😢 

Below is a screencast of my Umbraco running locally with runtime minification enabled. Chrome DevTools are closed, so I'm not cheating 😉 

When I change the block custom view, it is immediately reflected in the backoffice, without changing anything in the minification settings:

[17184.webm](https://github.com/user-attachments/assets/2517ea25-162f-4779-a7ec-5b6f543744bb)

I believe this is how it _should_ work - if I recall correctly, custom block views are not handled by the runtime minification.

Can you see the view being requested from the backoffice, if you open up DevTools when editing?

**Comment by teeto** [comment]
thanks @kjac  for your response. In local it works well, it happens when publishing to production with the settings:
"RuntimeMinification": {
"CacheBuster": "Version",
"Version": "87"
}

**Comment by kjac** [comment]
Hi @teeto 👋 I'm running locally with the same runtime minification settings and still I don't see it happening.

Two questions come to mind:

1. Is your site running in ["Production Mode"](https://docs.umbraco.com/umbraco-cms/fundamentals/setup/server-setup/runtime-modes#production-mode) in your production deployments?
2. Can you see the view HTML files being requested in the Chrome network tab, when you view blocks in the production environment back-office?

**Comment by teeto** [comment]
yes, it is running in production mode.
In local i am running development mode with this settings:
"RuntimeMinification": {
  "UseInMemoryCache": true,
  "CacheBuster": "Timestamp"
},

And yes, i can see the html file being requested in Chrome. Note that after some hours the file gets updated in umbraco.

**Comment by kjac** [comment]
Hi @teeto,

Sorry for the belated response.

I've set this up with a site running in production mode, using the same runtime minification settings. I still cannot reproduce it 😕 

Here's a screencast of how custom view changes are reflected after restart:

[17184-2.webm](https://github.com/user-attachments/assets/b3fd3ad9-808e-4b19-a4ab-e299c0b52d7e)

> Note that after some hours the file gets updated in umbraco

Could this be a hint? Are there some custom cache headers being appended to your Umbraco client files by any chance?

**Comment by teeto** [comment]
Thanks @kjac , there is no custom cache headers. Anyway i updated to next 13 version and i think i havent this problem anymore. Its been some time since i dont work in that project. If i run into this again, i will update here. Thanks for your help.
