### ISSUE TITLE
[V15-RC1] TipTap RTE Config Feedback - Unable to remove toolbar button, redorder, delete group or row

### ISSUE THREAD

**Issue by warrenbuckley** [umbraco/Umbraco-CMS#17190]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

15.0.0-rc1

### Bug summary

Using the TipTap Config editor, I am unable to do the following things
* Move the toolbar item position in same group to reorder
* Move the toolbar item to another group
* Delete a single toolbar item from a group
* Delete an entire group
* Delete an entire row

### Specifics

https://github.com/user-attachments/assets/61bcfa9b-b6be-4d85-9759-8132880809aa

### Steps to reproduce

See attached video

### Expected result / actual result

That the operations to move, delete and reorder toolbar buttons

---
_This item has been added to our backlog AB#44726_

**Comment by iOvergaard** [comment]
Hi @warrenbuckley, the first item (sorting inside a toolbar group) is something I can reproduce, but not the others. I can't (yet) see your video, but do you not get a delete/trashbin button on each group and row?

**Comment by warrenbuckley** [comment]
@iOvergaard I do get a trash button on the group and row, but clicking them does nothing.

**Comment by iOvergaard** [comment]
Oh, interesting! Could you copy/paste your system information into the description, please?

https://github.com/user-attachments/assets/4221d162-8231-4607-bbce-ca22a441e2d5

**Comment by iOvergaard** [comment]
And do you get any error in the console, that you could share with us as well, please?

**Comment by warrenbuckley** [comment]
```
Umbraco system information
--------------------------------
Server OS: Microsoft Windows 10.0.22631
Server Framework: .NET 9.0.0-rc.1.24431.7
Default Language: en-US
Umbraco Version: 15.0.0-rc1
Current Culture: en-US
Current UI Culture: en-US
Current Webserver: IIS Express
Models Builder Mode: InMemoryAuto
Runtime Mode: BackofficeDevelopment
Debug Mode: True
Database Provider: System.Data.SQLite
Current Server Role: Single
Umbraco build version: 15.0.0-rc1+1180296
Server time offset: 00:00:00
Runtime mode: BackofficeDevelopment
Browser (user agent): Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36 Edg/129.0.0.0
Browser language: en-GB
Browser location: https://localhost:44339/umbraco/section/content/dashboard/dashboardTabsContentIntro
```


**Error when clicking button is in console**
`property-editor-ui-tiptap-toolbar-configuration.element.ts`
```bash
property-editor-ui-tiptap-toolbar-configuration.element.ts:151  Uncaught TypeError: Cannot assign to read only property '0' of object '[object Array]'
    at Array.splice (<anonymous>)
    at m.M (property-editor-ui-tiptap-toolbar-configuration.element.ts:151:42)
    at m.<anonymous> (property-editor-ui-tiptap-toolbar-configuration.element.ts:226:21)
    at wt.handleEvent (index.js:15:6103)
M @ property-editor-ui-tiptap-toolbar-configuration.element.ts:151
(anonymous) @ property-editor-ui-tiptap-toolbar-configuration.element.ts:226
handleEvent @ index.js:15
```
![image](https://github.com/user-attachments/assets/5e177471-871c-4530-bcc6-7f87804f33fd)

**Comment by warrenbuckley** [comment]
And clicking the delete for the row is this error/stack trace

```bash
property-editor-ui-tiptap-toolbar-configuration.element.ts:170  Uncaught TypeError: Cannot delete property '1' of [object Array]
    at Array.splice (<anonymous>)
    at m.S (property-editor-ui-tiptap-toolbar-configuration.element.ts:170:32)
    at m.<anonymous> (property-editor-ui-tiptap-toolbar-configuration.element.ts:206:21)
    at wt.handleEvent (index.js:15:6103)
S @ property-editor-ui-tiptap-toolbar-configuration.element.ts:170
(anonymous) @ property-editor-ui-tiptap-toolbar-configuration.element.ts:206
handleEvent @ index.js:15
```
