### ISSUE TITLE
14.3: composition link in documenttype not working

### ISSUE THREAD

**Issue by Ambertvu** [umbraco/Umbraco-CMS#17196]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

14.3

### Bug summary

When click on the `inherited from ....` on a document type based on compositions, the link is not correct

### Specifics

![image](https://github.com/user-attachments/assets/05d5602a-cd1b-419d-85d1-3062b03a55b3)

Link seems to have a wrong value in it:
/umbraco/**undefinededit**/8707bda1-a647-46b3-8541-6b7d692fd2bc

### Steps to reproduce

Create a document type
Create a composition
Add composition to document-type
Click composition link on document-type

### Expected result / actual result

To navigate correctly to the composition

**Comment by NguyenThuyLan** [comment]
Hi @Ambertvu , I wasn't able to reproduce this issue. Seems like it was fixed. I tried on v14.3.0 like this video below
https://github.com/user-attachments/assets/766a7d95-393a-4e01-8f53-d15065cf12ca

So I will close this issue and feel free to reopen if you have further infomations
