### ISSUE TITLE
v14.3 - RTE does not render links correctly if anchor or querystring is populated 

### ISSUE THREAD

**Issue by too-dark-park** [umbraco/Umbraco-CMS#17219]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

14.3

### Bug summary

When adding a 'link to page' in an RTE, the link URL doesn't render correctly if an anchor or querystring value has been added. The resulting link renders something like **https://localhost:44381/%7BlocalLink:9ba1b48b-71ce-4654-b783-2621077ff8ad%7D?examplequerystring**

### Specifics

![image](https://github.com/user-attachments/assets/0ab9277b-7457-4959-b835-0dfca7cdd8af)

**The rendered link**
![image](https://github.com/user-attachments/assets/df5ba4ab-9b2d-4fbf-ad59-3dacba2ef8d0)

**In a block grid RTE, when you try editing the link again the anchor HTML actually replaces the title and you lose the link value and anchor / querystring title.**
![image](https://github.com/user-attachments/assets/589cb974-ab92-44e3-b0ee-fa383633dd43)

### Steps to reproduce

1. Add an RTE to a doctype
2. In the RTE, add a link with a querystring or anchor
3. Select a page using 'link to page'
4. Save the link
5. Save and publish
6. View the rendered page and click the link
7. You will see the rendered link looks similar to https://localhost:44381/%7BlocalLink:efaa9445-2ab5-4b54-9fd8-95aef6af2770%7D#example-anchor

### Expected result / actual result

I would expect the rendered link to represent the URL of the node/document I selected with the anchor or querystring correctly appended. For example; https://localhost:44381/mypageurl#example-anchor.

Instead the link is currently being rendered as https://localhost:44381/%7BlocalLink:efaa9445-2ab5-4b54-9fd8-95aef6af2770%7D#example-anchor

---
_This item has been added to our backlog AB#45052_

**Comment by iOvergaard** [comment]
This has been fixed and will be included in 15.0.0-rc2, which should be released tomorrow
