### ISSUE TITLE
UmbracoContext.PublishedRequest is null, using UmbracoPageController

### ISSUE THREAD

**Issue by merijng** [umbraco/Umbraco-CMS#17217]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

14.3.0

### Bug summary

`IUmbracoContextFactory` in Umbraco is not functioning as expected in Umbraco versions 14.3.0 and 13.x.x. `PublishedRequest` is `null`. This issue does not occur in Umbraco version 12.3.10.

### Specifics

- **Affected versions**: Umbraco 13.x.x and Umbraco 14.3.0
- **Working version**: Umbraco 12.3.10
- **Environment**: `IUmbracoContextFactory` to access `PublishedRequest` in `UmbracoPageController`.

### Steps to reproduce

**Install Umbraco 12.3.10 using:**
```bash
   dotnet new install Umbraco.Templates::12.3.10
   dotnet new umbraco -n MyProject
```
- Run the application and add a controller similar to `TestController` (as below) using the `UmbracoPageController` and the `FindContent` method. 
- Also register the controller (as below) to `WithEndpoints`, within `Startup.cs`.
- Run the application and access the /test/{id} URL.
- The test should pass as expected.

**Install Umbraco 14.3.0 following the [Umbraco documentation](https://docs.umbraco.com/umbraco-cms/fundamentals/setup/install).**
- Add the same TestController implementation. Add the endpoint in `Program.cs`
- Run the application and access the /test/{id} URL.
- The test will fail with a null PublishedRequest.

```
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Filters;
using Microsoft.AspNetCore.Mvc.ViewEngines;
using Umbraco.Cms.Core.Models.PublishedContent;
using Umbraco.Cms.Core.Web;
using Umbraco.Cms.Web.Common.Controllers;

public class TestController : UmbracoPageController, IVirtualPageController
{
    private readonly IUmbracoContextFactory _umbracoContextFactory;

    public TestController(
        ILogger<UmbracoPageController> logger,
        ICompositeViewEngine compositeViewEngine,
        IUmbracoContextFactory umbracoContextFactory)
        : base(logger, compositeViewEngine)
    {
        _umbracoContextFactory = umbracoContextFactory;
    }

    public IPublishedContent FindContent(ActionExecutingContext actionExecutingContext)
    {
        using (var reference = _umbracoContextFactory.EnsureUmbracoContext())
        {
            if (reference.UmbracoContext.PublishedRequest == null)
                throw new Exception("Test failed");
            else
                throw new Exception("Test passed");
        }
    }

    [HttpGet]
    public async Task<IActionResult> Index(string id = null)
    {
        throw new Exception("Test passed");
    }
}
```

```
u.EndpointRouteBuilder.MapControllerRoute(
   nameof(TestController),
   "/test/{id?}",
   new { Controller = "Test", Action = "Index" });
```

### Expected result / actual result

- `PublishedRequest` not being `null`.

**Comment by firthy** [comment]
I have the same issue after follwing docs for Custom MVC Routes.
Currently using the work around outlined here
https://github.com/umbraco/Umbraco-CMS/issues/12834

**Comment by kjac** [comment]
I suspect it's a bug that `PublishedRequest` has a value for custom routes in V12. The whole point of custom routes is to route outside of the regular published content, so conceptually the `PublishedRequest` has little meaning.

The `IVirtualPageController.FindContent` method is there to provide the published content that should be rendered - i.e. as `CurrentPage` when rendering views.

Here's an example that uses the "id" route value to find content by key, assuming the "id" is the content key. A real-world scenario would of course use a slightly more refined way of mapping the "id" route value to the relevant content 😄 

```cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Filters;
using Microsoft.AspNetCore.Mvc.ViewEngines;
using Umbraco.Cms.Core.Models.PublishedContent;
using Umbraco.Cms.Core.Web;
using Umbraco.Cms.Web.Common.Controllers;

public class TestController : UmbracoPageController, IVirtualPageController
{
    private readonly IUmbracoContextAccessor _umbracoContextAccessor;

    public TestController(
        ILogger<UmbracoPageController> logger,
        ICompositeViewEngine compositeViewEngine,
        IUmbracoContextAccessor umbracoContextAccessor)
        : base(logger, compositeViewEngine)
        => _umbracoContextAccessor = umbracoContextAccessor;

    public IPublishedContent? FindContent(ActionExecutingContext actionExecutingContext)
    {
        if (actionExecutingContext.HttpContext.Request.RouteValues.TryGetValue("id", out var idRouteValue) is false)
        {
            // no "id" route value, return null (this results in a 404 response)
            return null;
        }

        // find the relevant content from the "id" route value - in this example, it's expected to be a GUID,
        // so we can get content based directly on its value
        if (idRouteValue is not string idValue || Guid.TryParse(idValue, out Guid key) is false)
        {
            // malformed "id", expected an integer (should probably log something here)
            return null;
        }

        return _umbracoContextAccessor.TryGetUmbracoContext(out IUmbracoContext? umbracoContext)
            ? umbracoContext.Content?.GetById(key)
            : null;
    }

    [HttpGet]
    public IActionResult Index()
        => CurrentPage is not null
            ? Content($"Test succeeded (got published content: {CurrentPage.Name})")
            : Content("Test failed");
}
```

**Comment by firthy** [comment]
Hi,

My issue was that in a ViewComponent the PublishedContent was null after the custom route implementation . The work around does fix this. 

        public async Task<IViewComponentResult> InvokeAsync()
        {
            var content = _context.GetRequiredUmbracoContext().PublishedRequest.PublishedContent;
            var metaData = new MetaDataViewModel
            {
                Title = content.Name
            };

            return View(metaData);
        }
cheers,
Mark

**Comment by kjac** [comment]
Thanks @firthy 😄 I'll go ahead and close this one now, then 👍
