### ISSUE TITLE
RTE Containers/Code style doesn't work

### ISSUE THREAD

**Issue by wwrobel** [umbraco/Umbraco-CMS#17225]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

13.5.1

### Bug summary

When you select the Code "Container" from the dropdown in the RTE (see screenshot), the styling is initially applied but removed again when saving.

![image](https://github.com/user-attachments/assets/8608cd1a-2cd0-422c-a19f-58e63f140d2b)

### Specifics

The code should be surrounded by the `<code></code>` block, but it isn't.
The cause is that `<code>` element isn't added as valid HTML element in [RTE configuration](https://github.com/umbraco/Umbraco-CMS/blob/2e068bb73eac2ca443a8fa6691cbe11f01b12b2c/src/Umbraco.Core/Configuration/Models/RichTextEditorSettings.cs#L11)

### Steps to reproduce

1. Go to RTE property and type some text.
2. Select the text and set the styling to `Containers/Code` as shown on the above screenshot.
3. (Optional) Take a look on RTE html generated, there will be only the text surrounded by `<p></p>` instead of `<p><code></code></p>`.
4. Save changes.
5. Code text in RTE will be surrounded only by `<p></p>`, so code style won't be applied.

### Expected result / actual result

Code text should be surrounded by `<p><code></code></p>`. To make it works we should add the `code` into valid elements [here](https://github.com/umbraco/Umbraco-CMS/blob/2e068bb73eac2ca443a8fa6691cbe11f01b12b2c/src/Umbraco.Core/Configuration/Models/RichTextEditorSettings.cs#L11).

There is a simple workaround for that issue. You can add the `<code>` html element as valid through the RTE custom configuration by extending appsettings.json:
```
"Umbraco": {
  "CMS": {
    "RichTextEditor": {
      "CustomConfig": {
        "extended_valid_elements": "code"
      }
    }
  }
}
```

**Comment by iOvergaard** [comment]
Fixed on the main branch. Will end up in the next release of V13, if there ever is one. I will transfer the fix to V14 and V15 as well.
