### ISSUE TITLE
RTE property editors loadtime increase after certain amount of RTEs

### ISSUE THREAD

**Issue by HamDerAndrew** [umbraco/Umbraco-CMS#17238]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

13.4.1

### Bug summary

A content node will load RTE editors slowly because it's waiting for the RTE stylesheet to load.
It's not an issue with few RTEs, but approaching around 80 RTEs you will start to notice it.
I know this is a lot of RTEs, but I've seen the issue on a large Umbraco site.
I found that the slow loading was due to the RTE stylesheets still loading.

A very similiar issue was raised about it here:
https://github.com/umbraco/Umbraco-CMS/issues/5720

### Specifics

Here's a video showcasing the loadtime with the network tab open:
https://github.com/user-attachments/assets/8205e632-69d1-4e20-a040-510a03550eea

I'm adding a screenshot so you can see parts of the requests to the stylesheet better:
![Screenshot 2024-10-10 at 14 20 56](https://github.com/user-attachments/assets/27b543db-8a93-414c-b574-7a79fb808d59)

### Steps to reproduce

- Create a document type
- Add 81 RTEs
- Create content node based on document type
- Save and Publish (no need to add content)
- Reload the page (preferebly without cache). Rendering the RTEs takes 3+ seconds.
- Open the network tab to see all the stylesheets getting loaded

### Expected result / actual result

Could we present the RTE while we wait for the stylesheet to load?
Else I know this is more of a "you have too many RTEs" issue :)

**Comment by iOvergaard** [comment]
This seems like an upstream issue from Tinymce that loads the stylesheet. Not sure if we can combine it somehow as it needs to be loaded inside the iframe that TinyMCE creates.

TinyMCE does not specify any special configuration to use on their guide on how to use multiple editors on the same page: https://www.tiny.cloud/docs/tinymce/latest/multiple-editors/

We are using the `content_css` option from TinyMCE as-is. I am open to any suggestions, but for the time being, I don't think it can be fixed, nor is there an upstream issue to point to. I would advise that you open an issue on TinyMCE's issue tracker for your use case!

**Comment by HamDerAndrew** [comment]
That's a fair point.
Appreciate the details @iOvergaard 😄 
Thanks!
