### ISSUE TITLE
Missing import/export content features?

### ISSUE THREAD

**Issue by tbolon** [umbraco/Umbraco-CMS#17237]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

14.3.0

### Bug summary

I am trying to export/import content, but I can't find the menu in the "Content" or "Media" section:

![image](https://github.com/user-attachments/assets/fed4127a-d451-48e1-8777-b6039bbc2f96)

No action are visible on the context menu on any content node:

![image](https://github.com/user-attachments/assets/4efbd913-64a7-4cf3-8bb5-67d5d29d2be6)

The documentation is always stating that there should be a "next" menu with import/export action but I couldn't found them.

Note: the Document Type node has a 'import' and 'export' menu item.

### Steps to reproduce

- run `dotnet new umbraco --name Umbraco1`
- `cd Umbraco1`
- run `dotnet watch`
- perform installation wizard
- right click the content or media node: there is no import menu

**Comment by iOvergaard** [comment]
Hello, @tbolon. Importing and exporting content and media is a feature of [Umbraco Deploy](https://docs.umbraco.com/umbraco-deploy/deployment-workflow/import-export), which you can install separately.

Can you link me to where the documentation says there should be a button as we might need to correct something, please?

**Comment by tbolon** [comment]
Ok, it seems I was lost in the Umbraco Cloud documentation and I didn't detect that. I also did not understand that the term "Umbraco Deploy core" in the welcome page was about a package which is optional in classic self-hosted project: https://docs.umbraco.com/umbraco-cloud/deployments/deployment

Anyway, it's on me. Sorry for creating an issue for that.

**Comment by iOvergaard** [comment]
No worries, @tbolon. The package is installed by default on Cloud sites, but self-hosted sites can also add it manually.
