### ISSUE TITLE
v15: Content Collection talks about "Content App"

### ISSUE THREAD

**Issue by enkelmedia** [umbraco/Umbraco-CMS#17230]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

v15-rc

### Bug summary

The configuration of "list views" talks about "content app" which (afaik) is not a thing anymore. I guess that "Workspace View" is the correct term but maybe better to talk about a "collection" in some way?

![image](https://github.com/user-attachments/assets/9e3f44cd-6616-4207-8fb5-af3d58b48088)

### Steps to reproduce

Create a Document Type, configure it to show a collection

**Comment by iOvergaard** [comment]
Thanks for reporting this. I agree, this needs to be changed to "The X of the workspace view".

**Comment by loranallensmith** [comment]
I think I'd like to take a crack this one for Hacktoberfest if that's okay with y'all @iOvergaard and @enkelmedia.  😄

**Comment by enkelmedia** [comment]
@loranallensmith nice! Yeh! Just go a head :)
