### ISSUE TITLE
Login screen Logo is not remain same for logout

### ISSUE THREAD

**Issue by harikrishna43** [umbraco/Umbraco-CMS#17232]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

14.2.0

### Bug summary

I am not sure if this is considered a bug or an improvement but create an Issue here.

This is not major but the logout screen should remain the same as the login screen.
I have changed the Umbraco Logo to a custom logo on the login screen.
When I logged out, it was the default logo on the screen.

https://github.com/user-attachments/assets/46ed9b19-34c5-481c-b5e3-ed0d5c38a897

### Steps to reproduce

- Set custom logo
- Login Umbraco backoffice 
- Logout backoffice
- you will find the default logo

### Expected result / actual result

It should be the same as the login screen

**Comment by iOvergaard** [comment]
Thanks for reporting. I believe this known issue has already been reported in #16636. I will go ahead and close this issue and we will continue tracking it in the other issue.
