### ISSUE TITLE
Create media dropdown action does nothing

### ISSUE THREAD

**Issue by jbppraxis** [umbraco/Umbraco-CMS#17250]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

14.3

### Bug summary

Go to media - push create, select in dropdown,  nothing happens
![image](https://github.com/user-attachments/assets/39808551-2e75-42e3-a4a1-bcc73928fb1f)

### Steps to reproduce

Start umbraco
God to media - e.g. https://localhost:44374/umbraco/section/media/view/media/collection
Push dropdown create and nothing happens.
![msedge_xL0Rjs9GOT](https://github.com/user-attachments/assets/3b2d6985-f64c-428e-bb22-6e430e65b152)

### Expected result / actual result

i would expect to to create a media as with the other create options

**Comment by Zeegaan** [comment]
I sadly cannot reproduce this, this works for me 🤔 
This is me on 14.3.1

![MediaCre](https://github.com/user-attachments/assets/68958a2e-af73-468a-a9ba-7a76ebf09f7a)

**Comment by jbppraxis** [comment]
> I sadly cannot reproduce this, this works for me 🤔 This is me on 14.3.1
> 
> ![MediaCre](https://private-user-images.githubusercontent.com/70372949/376161965-68958a2e-af73-468a-a9ba-7a76ebf09f7a.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg4OTc1ODIsIm5iZiI6MTcyODg5NzI4MiwicGF0aCI6Ii83MDM3Mjk0OS8zNzYxNjE5NjUtNjg5NThhMmUtYWY3My00NjhhLWE5YmEtN2E3NmViZjA5ZjdhLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDE0VDA5MTQ0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI0OGVlOGFlYTE5MmRhN2JkZWE3NGVhNDNiMmYwNTY1ODk2NjYxYzhiOWRjMzgxNTQ0YmNhMTc5OTFmZWI3YTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.aLBW9A0shh6jXLQa6869IYQkj712HPfihWeH2LhKwSI) [ ![MediaCre](https://private-user-images.githubusercontent.com/70372949/376161965-68958a2e-af73-468a-a9ba-7a76ebf09f7a.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg4OTc1ODIsIm5iZiI6MTcyODg5NzI4MiwicGF0aCI6Ii83MDM3Mjk0OS8zNzYxNjE5NjUtNjg5NThhMmUtYWY3My00NjhhLWE5YmEtN2E3NmViZjA5ZjdhLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDE0VDA5MTQ0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI0OGVlOGFlYTE5MmRhN2JkZWE3NGVhNDNiMmYwNTY1ODk2NjYxYzhiOWRjMzgxNTQ0YmNhMTc5OTFmZWI3YTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.aLBW9A0shh6jXLQa6869IYQkj712HPfihWeH2LhKwSI) ](https://private-user-images.githubusercontent.com/70372949/376161965-68958a2e-af73-468a-a9ba-7a76ebf09f7a.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg4OTc1ODIsIm5iZiI6MTcyODg5NzI4MiwicGF0aCI6Ii83MDM3Mjk0OS8zNzYxNjE5NjUtNjg5NThhMmUtYWY3My00NjhhLWE5YmEtN2E3NmViZjA5ZjdhLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDE0VDA5MTQ0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI0OGVlOGFlYTE5MmRhN2JkZWE3NGVhNDNiMmYwNTY1ODk2NjYxYzhiOWRjMzgxNTQ0YmNhMTc5OTFmZWI3YTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.aLBW9A0shh6jXLQa6869IYQkj712HPfihWeH2LhKwSI) [ ](https://private-user-images.githubusercontent.com/70372949/376161965-68958a2e-af73-468a-a9ba-7a76ebf09f7a.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg4OTc1ODIsIm5iZiI6MTcyODg5NzI4MiwicGF0aCI6Ii83MDM3Mjk0OS8zNzYxNjE5NjUtNjg5NThhMmUtYWY3My00NjhhLWE5YmEtN2E3NmViZjA5ZjdhLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDE0VDA5MTQ0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI0OGVlOGFlYTE5MmRhN2JkZWE3NGVhNDNiMmYwNTY1ODk2NjYxYzhiOWRjMzgxNTQ0YmNhMTc5OTFmZWI3YTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.aLBW9A0shh6jXLQa6869IYQkj712HPfihWeH2LhKwSI)

As I wrote in the report this was 14.3. If its working in 14.3.1 it might have been fixed :)

**Comment by Zeegaan** [comment]
Sorry, was testing on the dev branch 😁 
But this also works for me on 14.3.0
Which browser are you seeing this behavior on ? 🤔

**Comment by jbppraxis** [comment]
@Zeegaan I am seeing the behavior in chrome and firefox. If I inspect the link on the button I can see the following
`../umbraco/section/media/view/media/undefined/collection/modal/umb-modal-workspace/media/create/parent/media-root/null/a43e3414-9599-4230-a7d3-943a21b20122`

If i do it from the other create button that works the url looks like this
`/umbraco/section/media/workspace/media/create/parent/media-root/null/a43e3414-9599-4230-a7d3-943a21b20122/invariant`

**Comment by jbppraxis** [comment]
@Zeegaan it works now. 
We had some issue with usync and export / import of settings. 
So carry on

**Comment by Zeegaan** [comment]
@jbppraxis All good, just happy it's solved 😁
