### ISSUE TITLE
Missing export for UMB_CONTENT_SECTION_ALIAS

### ISSUE THREAD

**Issue by warrenbuckley** [umbraco/Umbraco-CMS#17254]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

14.x

### Bug summary

I am unable to use/consume UMB_CONTENT_SECTION_ALIAS to use in a manifest for a condition for a dashboard. 

### Steps to reproduce

Try to build a dashboard and import UMB_CONTENT_SECTION_ALIAS

**Comment by madsrasmussen** [comment]
Thanks @warrenbuckley 

Note: It might make sense to export this from the `@umbraco-cms/backoffice/content` module. I think it is currently located in the documents package but it should be moved.

**Comment by warrenbuckley** [comment]
One PR is here
https://github.com/umbraco/Umbraco.CMS.Backoffice/pull/2458
