### ISSUE TITLE
v15-RC1: RTE doesn't allow pasting in images

### ISSUE THREAD

**Issue by crgrieve** [umbraco/Umbraco-CMS#17258]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

v15 RC1

### Bug summary

At the moment with tinyMCE we can ctrl+v in screenshots/images. This doesn't appear to be working in the v15 RC.

### Steps to reproduce

Set up a doctype with a RTE(using new Tiptap RTE as default)
Take a screenshot
Try to past this into RTE

### Expected result / actual result

I'd expect it to work and create the image in the "Image Upload Folder" configured

---
_This item has been added to our backlog AB#45030_

**Comment by leekelleher** [comment]
Fixed in https://github.com/umbraco/Umbraco.CMS.Backoffice/pull/2465 for upcoming v15.0.0-rc2.
