### ISSUE TITLE
The New <IPublishedContentCache> NOT is refreshing cache for Subscriber servers on load balanced environment

### ISSUE THREAD

**Issue by IbrahimMNada** [umbraco/Umbraco-CMS#17263]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

15+

### Bug summary

When having multiple nodes ,  one is `SchedulingPublisher` and the others are `Subscriber` ,using the extension method `SetServerRegistrar` .

and when you change a nodes content at the Backoffice, there are no changes at the Subscriber nodes 
we need to reset the cache for it to be reflected. 

My config like follows : 

```
        "DatabaseServerMessenger": {
          "MaxProcessingInstructionCount": 1000,
          "TimeBetweenPruneOperations": "00:01:00",
          "TimeBetweenSyncOperations": "00:00:01",
          "TimeToRetainInstructions": "1.00:00:00"
        }
```

### Steps to reproduce

Having 2 nodes  , one is `SchedulingPublisher` and another is `Subscriber`. 

 change content at the `SchedulingPublisher` , 
 
 nothing is changed on the `Subscriber`

### Expected result / actual result

Expected result : changes should be reflected.

 actual result: No changes

---
_This item has been added to our backlog AB#45026_

**Comment by IbrahimMNada** [comment]
@Zeegaan 
please give us your thoughts on this ,I might be able to help

**Comment by IbrahimMNada** [comment]
After some investigations it turned out that the `HybridCache` when its in memory , there is no way for the subscribers to know that it changed , since in 15- the database was used as a single source of integrity.

We need to define a way to notify the subscribers that cache of the publisher has been changed in order to delete the current in memory cached keys I searched .dotnet core for any hints regarding the hybrid cache behind a load balancer and i didn't found much info. 

this is a pretty interesting topic I would gladly help you  

Hello ,@Zeegaan ,  this maybe interesting to you since you're who developed this in v15 

Regards

**Comment by Zeegaan** [comment]
Heyo 👋 Great to hear your thoughts on this 😁 
We've already been looking into a solution 🕵️ 
This will include using `CacheRefresher` so it aligns with the old behavior 👍 
When cache tags gets implemented for the `HybridCache` it will get a lot easier to evict stuff luckily 😁

**Comment by IbrahimMNada** [comment]
I worked around it with something similar to what you have said , this is my work for the time being

   ```csharp
   
   using Microsoft.Extensions.Caching.Hybrid;
using Umbraco.Cms.Core.Cache;
using Umbraco.Cms.Core.Events;
using Umbraco.Cms.Core.Notifications;
using Umbraco.Cms.Core.Services.Changes;
using Umbraco.Cms.Core.Sync;

namespace Tanmiah.External.Cms.Web.DeliveryApi.Composers
{
    public class ContentCacheRefresherNotificationHandler : INotificationAsyncHandler<ContentCacheRefresherNotification>
    {
        private readonly HybridCache _hybridCache;
        private readonly IServerRoleAccessor _serverRoleAccessor;
        public ContentCacheRefresherNotificationHandler(HybridCache hybridCache, IServerRoleAccessor serverRoleAccessor)
        {
            _hybridCache = hybridCache;
            _serverRoleAccessor = serverRoleAccessor;
        }
        public async Task HandleAsync(ContentCacheRefresherNotification notification, CancellationToken cancellationToken)
        {
            if (_serverRoleAccessor.CurrentServerRole == ServerRole.Subscriber)
                return;

            if (notification.MessageObject is not ContentCacheRefresher.JsonPayload[] payloads)
            {
                return;
            }
            foreach (ContentCacheRefresher.JsonPayload payload in payloads)
            {
                if (payload.ChangeTypes is not TreeChangeTypes.RefreshNode or TreeChangeTypes.RefreshBranch)
                {
                    return;
                }
                await _hybridCache.RemoveAsync(payload.Key.Value.ToString() + "+draft");
                await _hybridCache.RemoveAsync(payload.Key.Value.ToString());
            }
        }
    }
}

**Comment by IbrahimMNada** [comment]
Even this tags, I don't think it will be very helpful when it comes to in memory caching in hybrid caching. 

How will the first node get access to the other node ?
we need some sort of intercommunication between nodes in the context of hyper caching 

I have open this proposal on Dotnet extensions repo  https://github.com/dotnet/extensions/issues/5517
hope it will start shaking things up ,

**Comment by bergmania** [comment]
Fixed in https://github.com/umbraco/Umbraco-CMS/pull/17296

**Comment by jodydonetti** [comment]
Hi all, I don't know if it can still be useful or not, but now there's a production-ready [`HybridCache` implementation](https://github.com/ZiggyCreatures/FusionCache/blob/main/docs/MicrosoftHybridCache.md) with full multi-node support thanks to FusionCache [v2](https://github.com/ZiggyCreatures/FusionCache/releases/tag/v2.0.0).

Hope this helps.
