### ISSUE TITLE
Cannot delete MemberGroup from Umbraco Backoffice

### ISSUE THREAD

**Issue by gmanrodt** [umbraco/Umbraco-CMS#17276]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

14.3.0

### Bug summary

There is no way to delete a Member Group from the Umbraco Backoffice.

![image](https://github.com/user-attachments/assets/b159a90e-d875-4945-b4bf-66b2a30badd8)

### Steps to reproduce

In the Umbraco backoffice, create a new member group and click save.
Go back to the Member Group listing page (/umbraco/section/member-management/view/member-groups/collection/table)

There is no way to select a group to delete it.

Click on a Member Group, and notice there is no "Actions" menu and no other way to delete the group.

### Expected result / actual result

There should be a way to delete a Member Group from the backoffice, either from the List View or from the Member Group detail page's Action menu (or both).

---
_This item has been added to our backlog AB#45061_

**Comment by madsrasmussen** [comment]
Hi @gmanrodt 

It is now possible to delete a member group through the entity action menu.

<img width="1327" alt="Screenshot 2024-10-23 at 11 02 59" src="https://github.com/user-attachments/assets/b3eda0a7-2b14-4105-9dcb-85c47b425117">
