### ISSUE TITLE
The umbracoUser table is using the primary key name PK_user instead of PK_umbracoUser

### ISSUE THREAD

**Issue by pschwarzkopf** [umbraco/Umbraco-CMS#17302]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

14.3.0

### Bug summary

The table "umbracoUser" is using the primary key name "PK_user" instead of "PK_umbracoUser".
https://github.com/umbraco/Umbraco-CMS/blob/e4dbf4ce9ff9ca70ed7c82c0c735a4d576aad692/src/Umbraco.Infrastructure/Persistence/Dtos/UserDto.cs#L22

Other tables use a prefixed primary key (example: the table "umbracoUserGroup" is using the primary key name "PK_umbracoUserGroup").
https://github.com/umbraco/Umbraco-CMS/blob/e4dbf4ce9ff9ca70ed7c82c0c735a4d576aad692/src/Umbraco.Infrastructure/Persistence/Dtos/UserGroupDto.cs#L22

### Specifics

This caused an issue with an existing application (with a user table already existing), when adding Umbraco.

### Steps to reproduce

Create a user table with the primary key name PK_User, then try to add Umbraco to the application.

**Comment by NguyenThuyLan** [comment]
Hi @pschwarzkopf , thank you for reporting the issue.
I think you are not forced to use Umbraco in the same database as the rest of your application.
And you have another way to resolve it. 
Editing key name could have many affects so we don't consider to fix it now.
