### ISSUE TITLE
[v15 rc2] Backoffice Localization - What replaces ManifestLocalization?

### ISSUE THREAD

**Issue by jcdcdev** [umbraco/Umbraco-CMS#17317]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

15.0.0-rc2

### Bug summary

I'm working on porting all of my packages to Umbraco 15. The new Extension Manifest Type Architecture has been mostly easy to move over. However, I can't find the equivalent of `ManifestLocalization` with TypeScript.

### Steps to reproduce

- Create an array of `ManifestLocalization` [src/jcdcdev.Umbraco.ExtendedDropdownEditor.Client/src/lang/manifests.ts](https://github.com/jcdcdev/jcdcdev.Umbraco.ExtendedDropdownEditor/blob/dev/v15/src/jcdcdev.Umbraco.ExtendedDropdownEditor.Client/src/lang/manifests.ts#L3l)
- Attempt to build front end
```
Module '"@umbraco-cms/backoffice/extension-registry"' has no exported member 'ManifestLocalization'.

1 import { ManifestLocalization } from "@umbraco-cms/backoffice/extension-registry";
           ~~~~~~~~~~~~~~~~~~~~


Found 1 error in src/lang/manifests.ts:1
```
- This is expected but I cannot find the correct type I am supposed to use

### Expected result / actual result

- I expect `ManifestLocalization` or equivalent to be available when declaring manifests

**Comment by KevinJump** [comment]
Hi, 

for localizations you need to replace the manifest with `UmbExtensionManifest` which id delcared globally. 

there is a note about this in the release notes for v15 release candidate

https://umbraco.com/blog/umbraco-15-release-candidate/#manifest

but it is missing a point for localization, you currently also need to add to the 'types' setup in your tsconfig.json 

```json
"types": [
 "@umbraco-cms/backoffice/extension-registry",
 "@umbraco-cms/backoffice/icon",
 "@umbraco-cms/backoffice/localization",
]
```
and then it sort of works. 🤷
