### ISSUE TITLE
[v15 rc2] BlockEditorCustomView forContentTypeAlias property not working for block list

### ISSUE THREAD

**Issue by warrenbuckley** [umbraco/Umbraco-CMS#17316]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

15.0.0-rc2

### Bug summary

When following the tutorial for creating a BlockEditorCustomView that can be used in block list and block grid.
https://docs.umbraco.com/umbraco-cms/tutorials/creating-custom-views-for-blocklist

If you set the forContentTypeAlias property then block list does not load the custom element, as soon as you remove it then it will load. 

### Specifics

 
![IMG_0009](https://github.com/user-attachments/assets/bed8a235-0a33-423b-9c37-6d19e451a2be)

### Steps to reproduce

* Create two properties on a doctype
* One that is blocklist and the other a block grid
* Create two or more element types and configure them to be used in the above editors
* Follow documentation
* use the forContentTypeAlias property and target a single elementtype alias 
* Add example content that uses both blocks in block list and block grid
* Notice only the block grid will load the custom element
* Remove the property from the manifest and now **all** element types will get the custom element as you would expect based on the manifest
* This now includes the block list as well, so it does not work when you set the property to target an element type

### Expected result / actual result

That the forContentTypeAlias property works with block list 

---
_This item has been added to our backlog AB#45398_

**Comment by warrenbuckley** [comment]
I may take a look at hackathon, leaving these here to compare

https://github.com/umbraco/Umbraco.CMS.Backoffice/blob/main/src/packages/block/block-grid/components/block-grid-entry/block-grid-entry.element.ts

https://github.com/umbraco/Umbraco.CMS.Backoffice/blob/main/src/packages/block/block-list/components/block-list-entry/block-list-entry.element.ts

**Comment by nielslyngsoe** [comment]
Fixed by https://github.com/umbraco/Umbraco.CMS.Backoffice/pull/2515
