### ISSUE TITLE
[V15-RC2] URL to document types in settings occasionally gets stuck on /root and it won't show content

### ISSUE THREAD

**Issue by BernadetGoey** [umbraco/Umbraco-CMS#17326]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

15.0.0-rc2

### Bug summary

I'm reporting this buy for the 15.0.0 RC but I've noticed it's also the case in V14. 

This is probably a pretty obscure bug, but I've noticed that occasionally when I opened my document type, which entirely exists of compositions, that it wouldn't open the first available content tab and just show 'Add group', as if the document type had no fields. 

### Specifics

I've made a screen recording since it happens occasionally, but often enough that I'm able to replicate it. It appears that the URL to the document type occasionally changes to /root instead of /tab/content and then it won't show the expected results.

You'll notice in the screen recording that initially the 'Content' tab of the '_Content' composition doesn't open and at the end it doesn't open for the 'Example Document Type' either. 

https://github.com/user-attachments/assets/0a541787-a715-4665-af73-61acb55c90c2

### Steps to reproduce

1. Create a composition
2. Create a new document type
3. Add the composition to the document type
4. Switch between opening the document type and the composition, it'll eventually break

### Expected result / actual result

I would expect for the first available tab with content in it to be opened when I click a document type.

---
_This item has been added to our backlog AB#45479_

**Comment by nielslyngsoe** [comment]
Hi @BernadetGoey Thanks a lot for spotting this specific issue, and well described.
I have made a fix, it will be part of 15.2.
https://github.com/umbraco/Umbraco-CMS/pull/17716

Thanks
