### ISSUE TITLE
Users are unable to edit or create Members unless they have access to the Settings section

### ISSUE THREAD

**Issue by cvagan** [umbraco/Umbraco-CMS#17339]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

14.3.1

### Bug summary

Backoffice users that have access to the Member section and are in the "Sensitive data" group gets a "ApiError
The authenticated user do not have access to this resource" error when opening the Member section.

### Specifics

![image](https://github.com/user-attachments/assets/d0290bdd-9d19-412a-85c5-c03d3e19d7ab)
The user is able to see the list of members, but is unable to create any new members or view member properties. Clicking "Create member" shows the error message. Opening the edit member page on any member shows a blank page with the error message. The user is able to create new member groups without any issue. Giving the user access to the Settings section fixes the issue.

This was tested and reproduced on a migrated Umbraco 13.x solution and a fresh 14.3.1 installation.

### Steps to reproduce

1. Create new Backoffice user
2. Create new user group that has access to all sections except Settings
3. Add user to the created group and "Sensitive data" group
4. Log in with created user
5. Access member section

### Expected result / actual result

Expected result:
User is able to view and edit Members. It should be possible to grant Backoffice users access to the Members section without also giving them access to Settings.

Actual result:
User is met with the aforementioned error message unless they're granted access to the Settings section.

---
_This item has been added to our backlog AB#45473_

**Comment by nikolajlauridsen** [comment]
Fixed in #17440, thanks for reporting 😄
