### ISSUE TITLE
[v15-RC2] `node.Children` yields not results

### ISSUE THREAD

**Issue by mattbrailsford** [umbraco/Umbraco-CMS#17336]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

v15-RC2

### Bug summary

When trying to iterate the children of a `IPublishedContent` node no items are returned.

### Specifics

I came across this while upgrading the Umbraco Commerce demo store. This is therefore an upgrade project so could be to do with that. In addition, the install has 2 languages configured so I'm not sure if that has anything to do with it either.

### Steps to reproduce

- Create a node with children.
- In the template for the parent item, iterate over the `node.Chilren` collection
- Yields no results

### Expected result / actual result

I expect to be able to iterate a nodes children

**Comment by Zeegaan** [comment]
This works for me, both on upgrade and a clean install 🤔 
![image](https://github.com/user-attachments/assets/01b6819d-ffc4-4abc-85ae-d722a85bec63)

Tried with this code 

This in a view:

```
@{
	Layout = null;
	var selection = Umbraco.ContentAtRoot().FirstOrDefault().Children();
}

Number of items = @selection.Count()
<ul>
	@foreach (var item in selection)
	{
		<li>
			@item.Name()
		</li>
	}
</ul>
```

This in a notification handler
```
      var root = _publishedContentCache.GetById(new Guid("5ed8e9a0-c994-4368-b132-ecd469ab8dbc"));
        var children = root?.Children();
```

**Comment by Zeegaan** [comment]
I'd like to know why this happens to you, so if you figure out how to reproduce this, please let us know 🙏

**Comment by mattbrailsford** [comment]
Looks like this might have been my messed up 15-RC2 upgrade. Finally got it to upgrade fully and it now seems to get the results I expected.
