### ISSUE TITLE
Publish with decendants does't reflect on the nodes published in Back Office

### ISSUE THREAD

**Issue by StudioBravo** [umbraco/Umbraco-CMS#17345]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

14.3.1

### Bug summary

When the content editors use "Publish with decendants" option to publish a parent node on a node with unpublished child nodes, some of the child nodes still indicates unpublished status but it is actually published (browser referesh indicates the item is published). 

### Steps to reproduce

- Pick up a parent document with a list of unpublished children

![image](https://github.com/user-attachments/assets/50e5623e-dd68-4920-8a87-2baa6201291c)

- Select "Publish with decendants" and select "Include unpublished content items"

![image](https://github.com/user-attachments/assets/62266ae7-787a-4273-bc8c-3a92aba606cf)

- Click on Publish with decendants 
- The UI indicates some of the nodes are unpublished but when the browser is refreshed, the correct publish status is shown

![image](https://github.com/user-attachments/assets/294dcf34-ba40-484f-ac0a-d378af3921c7)

### Expected result / actual result

The UI should reflect the correct status (published) when "Publish with decendants" is applied on the parent.

**Comment by leekelleher** [comment]
Fixed in https://github.com/umbraco/Umbraco.CMS.Backoffice/pull/2486 for v15.0.0-rc3.
