### ISSUE TITLE
Blocklist search is not working 

### ISSUE THREAD

**Issue by StudioBravo** [umbraco/Umbraco-CMS#17342]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

14.3.1

### Bug summary

The search functionality on the dialog that allows users to add an element to a blocklist is not working. When you type text on the search, the list gets cleared even if the text matches an item.

### Steps to reproduce

- Navigate to a page with a blocklist
- Click on the button to add an item to a blocklist

![image](https://github.com/user-attachments/assets/2d762ddb-c74a-4418-819b-f123b7c98401)

- Start typing and the elements dissappear

![image](https://github.com/user-attachments/assets/c90fa83d-cac0-4e2c-bf57-8d28e9d240ed)

### Expected result / actual result

The user should be able to easily search for an element from large lists.

**Comment by NguyenThuyLan** [comment]
Hi @StudioBravo , Blocklist is currently not supporting the search. So I will close this issue here
