### ISSUE TITLE
Tags dropdown behind markdown buttons

### ISSUE THREAD

**Issue by bjarnef** [umbraco/Umbraco-CMS#17340]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

15.0.0

### Bug summary

When having tags property editor above markdown editor, the dropdown is behind markdown buttons.

![image](https://github.com/user-attachments/assets/a2a410df-d303-45ae-929a-3e8b58752399)

### Steps to reproduce

Place tags property editor above markdown editor and notice dropdown is behind markdown toolbar buttons.

**Comment by Zeegaan** [comment]
Yep can reproduce this one 😁 
Thanks for reporting 🐛
