### ISSUE TITLE
Save and preview directs to invariant culture and causes server error

### ISSUE THREAD

**Issue by oliemason** [umbraco/Umbraco-CMS#17356]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

14.3.1

### Bug summary

Attempting 'Save and preview' action results in server error.
`CultureNotFoundException: Culture is not supported. (Parameter 'name') invariant is an invalid culture identifier.`
URL ~ `/umbraco/preview?id=7200b756-60d7-4fc0-9ec0-6df6074e64f0&culture=invariant`

### Specifics

* Content section displays `English (United States)` above Content tree menu
* Settings Languages section only contains `English (United States)` and is set as default

### Steps to reproduce

* Install fresh Umbraco
* Create Document Type allowed at root with RTE field
* Update Template to output field
* Create content and publish
* Update content and Save and preview

### Expected result / actual result

Expect to see draft content, but presented server error.

Can remove `&culture=invariant` from URL which then displays draft content.

**Comment by madsrasmussen** [comment]
Hi @oliemason 

Thanks for your report. I am happy to tell that this issues has been fixed in v15: https://github.com/umbraco/Umbraco.CMS.Backoffice/pull/2418
