### ISSUE TITLE
When renaming a script file I am not redirected to the renamed file 

### ISSUE THREAD

**Issue by andr317c** [umbraco/Umbraco-CMS#17387]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

14.3.1

### Bug summary

After renaming a script file, I am not redirected to the renamed file. 

### Specifics

See GIF:
![ScriptRename](https://github.com/user-attachments/assets/125be150-054e-4ddd-b567-fde89caa09d0)

### Steps to reproduce

1. Create a script
2. Rename the script 

### Expected result / actual result

Expected:
I would expect to be redirected to the renamed file
Actual
I am not redirected which results in the script not being found

**Comment by nielslyngsoe** [comment]
Closed by this issue, will be part of 15.1
https://github.com/umbraco/Umbraco-CMS/pull/17663
