### ISSUE TITLE
Dependcy Resolver Issues after applying security patch 8.18.15

### ISSUE THREAD

**Issue by nicolaesebastianlaslo** [umbraco/Umbraco-CMS#17384]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

8.18.14

### Bug summary

Hello

We have failed to apply the security patch 8.18.15 on top of the existing 8.18.14

Some custom code no longer works and that blocks the upgrade

Thanks
Nicolae

### Specifics

Code using System.Web.Mvc.DependencyResolver.GetService() Service Locator not working anymore after applying security patch 8.18.15 on top of existing 8.18.14

This
`  var importAdlibSyncTask = DependencyResolver.Current.GetService<IImportAblibSyncTask>();
[ImportAdlibSyncTask.zip](https://github.com/user-attachments/files/17544165/ImportAdlibSyncTask.zip)
`
is null after the minor upgrade

Relavant files atatched

Any toughts are more than welcome

### Steps to reproduce

Run the upgrade

### Expected result / actual result

Upgrade succefully completed

**Comment by bergmania** [comment]
Hi.. 

I looked into the changes https://github.com/umbraco/Umbraco-CMS/compare/release-8.18.14...release-8.18.15

I cannot see anything that should be related to this issue, in the changes between 8.18.14 and 8.18.15.

**Comment by nicolaesebastianlaslo** [comment]
Thanks for your help @bergmania 
Indeed the problem was somehwere else and because you confirmed that its not what I have suspected force me to check other leads
