### ISSUE TITLE
V15 Link Picker - Possible to highlight multiple items

### ISSUE THREAD

**Issue by AaronSadlerUK** [umbraco/Umbraco-CMS#17417]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

15.0.0-rc2

### Bug summary

When you click on a media item, and then on a content item the media item remains highlighted / selected in addition to the content item

### Steps to reproduce

Open a link picker modal
Click on a media item
Click on a content item

### Expected result / actual result

The media item should no longer be highlighted / selected when a content item is selected instead.

**Comment by leekelleher** [comment]
@AaronSadlerUK Thanks for raising this.

As part of addressing several concerns in #16838, the Link Picker modal has been refactored for 15.1.0.
More info + video demo here: https://github.com/umbraco/Umbraco.CMS.Backoffice/pull/2477

I'll close this issue off, but feel free to re-open if there's more discuss.
