### ISSUE TITLE
Contexts missing from <umb-debug>

### ISSUE THREAD

**Issue by enkelmedia** [umbraco/Umbraco-CMS#17410]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

14.3.0

### Bug summary

I'm trying to debug an issue where `this.consumeContext(...)` never fires the callback, probably because I'm inside a modal where this context can't be consumed.

I figured that using `<umb-debug visiable></umb-debug>` would be a good idea so I gave it a try. It seems to work fine, but I also noticed that some contexts (most likely global once) does not show up.

![image](https://github.com/user-attachments/assets/c68401c3-bff9-4245-9134-7060c89d82c1)

Basically, in the same component as where I have the `<umb-debug>` element I'm able to consume these contexts which mean that they should probably be listed in the debug element. The screenshot from above is from inside a modal, but the same problem exists in a "regular" workspace view or dashboard.

Examples of context that does not show up:

* UMB_CURRENT_USER_CONTEXT (UmbCurrentUserContext)
* UMB_APP_CONTEXT (UmbAppContext)
* UMB_THEME_CONTEXT (umbThemeContext)
* UMB_APP_LANGUAGE_CONTEXT (UmbAppLanguageContext)
* UMB_DOCUMENT_CONFIGURATION_CONTEXT (UmbDocumentConfigurationContext)

Seems like the common thing with all of these are that they are all registered as `globalContext` and hosted by the `umb-app` element.

### Steps to reproduce

See above

**Comment by iOvergaard** [comment]
Thanks for reporting this. We have implemented a fix, which will be released in version 15.2
