### ISSUE TITLE
New data type created through a Document Type gives the error message 'Data type could not be found'

### ISSUE THREAD

**Issue by andr317c** [umbraco/Umbraco-CMS#17424]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

15.0.0-rc3

### Bug summary

I only get this error the first time I create a new data type, after that, I do not get the error anymore
![CreateDataType](https://github.com/user-attachments/assets/b8d106b3-5d7b-42e3-a29c-6140db2b589c)

### Steps to reproduce

1. Good idea to be on a clean install of Umbraco
2. Click create new Document Type
3. Add group
4. Add property
5. Select a property editor
6. Create new configuration of a property editor
7. Get error message

### Expected result / actual result

I would expect not to get any error messages

**Comment by nielslyngsoe** [comment]
Fixed in https://github.com/umbraco/Umbraco.CMS.Backoffice/pull/2520
