### ISSUE TITLE
UFM on block list element not working correctly

### ISSUE THREAD

**Issue by seanhudson39** [umbraco/Umbraco-CMS#17427]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

14.3.1

### Bug summary

Using the new syntax for dynamic labelling of block list components in the back office does not seem to be working correctly. The value I put is just being used verbatim as the label for each component

### Specifics

![image](https://github.com/user-attachments/assets/30b2ebcd-f9c8-4aa3-9e34-0b948ac105a7)

### Steps to reproduce

1. Create a new element and add this as an available block in a new data type using the block list property editor.
2. Set the label to one of the properties, one that is text, of the element using the appropriate UFM syntax.
3. Create a composition and add a property using this new data type as the type.
4. Add the composition to any available document type.
5. Rebuild the models if necessary.
6. Create new content using the new element type and see that the UFM is not displaying as it should.

### Expected result / actual result

That the textual content used for the property is displayed as the label for the block list content item.

**Comment by leekelleher** [comment]
@seanhudson39 Thank you for reporting this, however it's a duplicate issue of #17313, #17143 and #17420.
