### ISSUE TITLE
Management API for running Umbraco migrations is called using the package name, but should be using the ID

### ISSUE THREAD

**Issue by AndyButland** [umbraco/Umbraco-CMS#17437]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

14+

### Bug summary

When a package has migrations to run, it's trigger them based on the package name.  But the ID should be used.

![image](https://github.com/user-attachments/assets/85e8ea80-f8a1-420c-b302-ff759dd1edb4)

![image](https://github.com/user-attachments/assets/78c5193d-aea1-4435-be93-79c2271af1ba)

### Specifics

See also [this (internal) discussion](https://umbraco.slack.com/archives/C02JJQU9B/p1730806029980859).

### Steps to reproduce

Install or upgrade a package that has migrations without unattended package migrations configured.  The package also needs to have a different name from it's ID (e.g. `Umbraco Forms` v `Umbraco.Forms`).  Request to run the migrations from the backoffice.

### Expected result / actual result

Migrations should run.

**Comment by bergmania** [comment]
Backend part fixed in https://github.com/umbraco/Umbraco-CMS/pull/17423
