### ISSUE TITLE
Unattended migrations of CMS and packages require a restart for the package ones to run

### ISSUE THREAD

**Issue by AndyButland** [umbraco/Umbraco-CMS#17436]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

13+

### Bug summary

We've had a couple of reports of people looking to run both a CMS and a package unattended migration at the same time.  What's found is that on start-up the CMS migration runs, but the package migration doesn't.  When you restart the application, the package migrations run,

### Specifics

See [this issue on the Forms tracker](https://github.com/umbraco/Umbraco.Forms.Issues/issues/1176) that discusses the problem.

And specifically [this comment](https://github.com/umbraco/Umbraco.Forms.Issues/issues/1176#issuecomment-2249868576) where I've detailed a little digging I've done into the problem.

Also [this (internal) discussion](https://umbraco.slack.com/archives/C02JJQU9B/p1730806029980859).

### Steps to reproduce

Update your CMS and a package's dependency in your `.csproj` file such that both new versions will require database migrations.  Start Umbraco and you will see that only the CMS migrations have run.

### Expected result / actual result

Ideally both the CMS and package migrations would run in one step.

---
_This item has been added to our backlog AB#46066_

**Comment by mattbrailsford** [comment]
I can confirm that this is the case. Upgrading CMS and Umbraco Commerce (which depends on Umbraco.Licenses) fails to run the Umbraco.Licenses migrations, but once Umbraco is upgraded and the project is restarted the Umbrac.Licenses migrations run succesfully.

**Comment by rbottema** [comment]
@nikolajlauridsen Two questions on this:

- We're also seeing this in Umbraco 10 as part of our Umbraco 8 -> Umbraco 13 migrations, where Umbraco 10 is still an needed step. Are there any plans to backport it to version 10?
- Will this fix be included in the upcoming 13.6.0? I see neither this issue nor the PR has been tagged with a release yet.
