### ISSUE TITLE
Flash of oddly styled content on login

### ISSUE THREAD

**Issue by glombek** [umbraco/Umbraco-CMS#17453]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

15.0.0-rc3 

### Bug summary

Logging in is a little jarring as there's a blue screen that flashes up very briefly. It feels a little clunky when running at full speed.
![FOUC](https://github.com/user-attachments/assets/00498696-b8c6-44a7-a380-a53b6ec80a57)
![FOUC1-17](https://github.com/user-attachments/assets/5e6deb20-5e05-4d73-b927-7077b75c1ea8)
![FOUC2-18](https://github.com/user-attachments/assets/daebcb87-7485-4169-ae8f-fcc35454e666)

### Steps to reproduce

Run a v15 site
Disable caching in the Network panel of developer tools
Login
Look for the blue flash

### Expected result / actual result

The login flow should feel seamless and less jarring.

---
_This item has been added to our backlog AB#45837_

**Comment by iOvergaard** [comment]
Hi @glombek, I'm following up on this; as @Migaroez said, the OAuth flow has a landing page, which is shown only briefly if you have a fast connection or are on localhost, etc. I'm wondering if we really need this landing page in case of a normal login, but we had some issues with capturing the return code to exchange for a token, so what happens on the landing page is roughly

1. Get the `?code` parameter from the URL
2. Call the `token` endpoint to get an access_token
3. Store that in local storage and memory
4. Redirect to the backoffice app

Do you feel like having some other kind of loading screen would help as this process transpires in the background? Maybe a loader bar/circle instead?

**Comment by glombek** [comment]
Hi folks, thanks for the replies. I appreciate this is as designed but my issue is more that it feels incomplete than its actually a technical problem.
A loading screen would be the nicest experience, but even a if the landing page wasn't dark blue in contrast to the two white pages before and after, it'd be less jarring!

**Comment by JasonElkin** [comment]
I've noticed this too and yes, a loader instead while the redirects happen would be better.

As far as the user is concerned, logging in is a single operation - they don't need to see these steps.

**Comment by iOvergaard** [comment]
Hi all, I hope that #17618 will improve this experience.

**Comment by leekelleher** [comment]
Fixed in #17618 for Umbraco 15.1.
