### ISSUE TITLE
`LoginBackgroundImage` does not override the image on the logout page

### ISSUE THREAD

**Issue by glombek** [umbraco/Umbraco-CMS#17452]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

15.0.0-rc3

### Bug summary

`LoginBackgroundImage` does not override the image on the logout page:

![image](https://github.com/user-attachments/assets/bbf82371-ee5b-4464-a6bc-ccc83ae09b44)

### Steps to reproduce

Set LoginBackgroundImage to `""`
Log in
Log out

**Comment by Migaroez** [comment]
Hey Joe, this is indeed not the case nor do any of the other login settings have an effect on the logout page.

I will check with the team whether this is expected behavior or something that is still planned in the future. I will get back to you asap.

**Comment by iOvergaard** [comment]
Hi @glombek, this is something we still need to wire up. I hope you don't mind if I close this issue and refer you to #16636 where we are tracking this issue.

**Comment by glombek** [comment]
Thanks @iOvergaard, sorry I missed this was a duplicate! I foolishly filtered my search to v15!
