### ISSUE TITLE
V15: Unable to configure List View to order by Name as default

### ISSUE THREAD

**Issue by DanielToft** [umbraco/Umbraco-CMS#17461]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

15.0.0-rc3

### Bug summary

In Umbraco List View it's not possible to configure the default sort order as Name. The Name option is not available in the list of options.

![image](https://github.com/user-attachments/assets/daf4d384-6bc0-4838-af1a-01b6ff828c46)

### Steps to reproduce

Configure a custom list view

---
_This item has been added to our backlog AB#45741_

**Comment by leekelleher** [comment]
@DanielToft Thank you for reporting this. We have a fix ready in PR #17600 to resolve this.
