### ISSUE TITLE
V14 Html local link parser regex fails (RTE)

### ISSUE THREAD

**Issue by Dark0d3** [umbraco/Umbraco-CMS#17464]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

14.3.1

### Bug summary

While adding a link in RTE and making it target="_blank" or open in new tab, the regex seem to break.

The issue seems to be FindLocalLinkIds not able to get any links due to the wrong regex and the url is not picked up thus resulting in the rendering of RTE as href="/{localLink:dff7c2bc-4fb8-4fd1-af78-c826124cf0dc}"

Hope this is a small fix, I could do a pull request if that's easier.

### Steps to reproduce

Create a RTE and add to content and add url with open in new tab. 

Check frontend and the html renders as with the a tag href="/{localLink:dff7c2bc-4fb8-4fd1-af78-c826124cf0dc}"

### Expected result / actual result

It should get the urls from IPublishedUrlProvider and change the guid to document URL

**Comment by Migaroez** [comment]
Hey @Dark0d3, this has been fixed in v15 which will be coming out shortly. If still needed, we can apply PR #17288 to the next 14 release as well.

**Comment by Dark0d3** [comment]
Hi @Migaroez , I saw that fixed on v15, Could you please apply the PR to the next 14 release as well, so there won't be any confusion. 
Thanks

**Comment by Migaroez** [comment]
Fixed in cherry pick of https://github.com/umbraco/Umbraco-CMS/pull/17288, see https://github.com/umbraco/Umbraco-CMS/commit/1581eb61d37068365d910677d80d08b138c561fb0
