### ISSUE TITLE
Block Grid components are not fully clickable in Umbraco 14

### ISSUE THREAD

**Issue by petervangennip** [umbraco/Umbraco-CMS#17467]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

14.3.1

### Bug summary

In Umbraco 14, when using the Block Grid, only the small edit button or pencil icon within each block is clickable to access the editing interface. The entire block area should be clickable, as this limited clickable area restricts ease of use and productivity for content editors. Expanding the clickable area to the whole block would improve the editing workflow and make the interface more intuitive.

### Specifics

Umbraco Version: 14
Affected Area: Block Grid editor in the Umbraco backoffice
Browser: All supported browsers
Component: Block Grid editor (UI/UX issue)

### Steps to reproduce

1. Open an Umbraco 14 project with content in the Block Grid editor.
2. Navigate to a Block Grid editor instance containing one or more blocks.
3. Attempt to click on the body of a block (outside of the edit button/pencil icon) to open the edit interface.

### Expected result / actual result

**Expected Result**
Clicking anywhere within a Block Grid component should open the editing interface for that block. This provides an intuitive and faster editing experience, allowing content editors to click directly on any part of the block.

**Actual Result**
Only the small edit button or pencil icon within each block is clickable. Clicking outside of this icon, within the block, does not open the editing interface, which limits the user experience.

**Comment by nielslyngsoe** [comment]
Thanks for reporting this issue, I love the awareness on the user interaction in the software!

This will be fixed with updates from UI Library in version 15.1
