### ISSUE TITLE
Configured Background Image Missing on /umbraco/logout

### ISSUE THREAD

**Issue by martinthogersen** [umbraco/Umbraco-CMS#17494]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

14.3.1

### Bug summary

I’ve set a background image for the login page in the configuration file using the LoginBackgroundImage setting, as outlined in the [Umbraco documentation](https://docs.umbraco.com/umbraco-cms/fundamentals/backoffice/login). The image displays correctly on the /umbraco login path, but it does not apply to the /umbraco/logout path.

```json
"Umbraco": {
    "CMS": {
      "Content": {
        "LoginBackgroundImage": "/some/url/picture.jpg"
      }
   }
}
```

### Steps to reproduce

1. Configure the login background image in the LoginBackgroundImage setting as shown in the documentation.
2. Access the /umbraco path (login page) – the background image should be applied.
3. Access the /umbraco/logout path (logout page) – notice that the background image is not applied.

**Comment by iOvergaard** [comment]
Hi @martinthogersen, this is something we still need to wire up. I hope you don't mind if I close this issue and refer you to #16636 where we are tracking this issue.
