### ISSUE TITLE
V15 Tiptap: It renders a duplicate image when copying an image

### ISSUE THREAD

**Issue by nhudinh0309** [umbraco/Umbraco-CMS#17505]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

15.0.0-rc4

### Bug summary

When I copy an image into a content with Tiptap RTE, it renders a duplicate image.

### Steps to reproduce

1. Create a content with Tiptap RTE property
2. Copy an image into RTE

### Expected result / actual result

It should only render one image that I copied. Currently it renders a duplicate image with smaller size.

https://github.com/user-attachments/assets/f0bb0a34-e77b-42a0-9724-fc4e55797172

---
_This item has been added to our backlog AB#45839_

**Comment by leekelleher** [comment]
Fixed in #17518
