### ISSUE TITLE
V15 RC4 Tiptap: Toolbar item still displays when the extension is disabled

### ISSUE THREAD

**Issue by nhudinh0309** [umbraco/Umbraco-CMS#17504]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

15.0.0-rc4

### Bug summary

When I disable an extension in the Tiptap Rich Text Editor, the corresponding toolbar item is also disabled in the toolbar configuration. However, it still appears in the content using the RTE

### Steps to reproduce

1. Create a content with Tiptap Richtext editor property
2. Open Tiptap Richtext editor data type 
3. Disable a extension (ex: Image) and save
4. Go back to the content

### Expected result / actual result

The toolbar item "Image" should not displays in the toolbar. Currently it still displays and I can interact with it.

https://github.com/user-attachments/assets/01aa85b2-68d8-41a7-ac09-3ea5ca2b8eae

**Comment by leekelleher** [comment]
Thanks @nhudinh0309! By coincidence, I'd fixed this very issue today in #17502 (for 15.0.0-rc4). 😀
