### ISSUE TITLE
No validation when updating the email of an existing member 

### ISSUE THREAD

**Issue by andr317c** [umbraco/Umbraco-CMS#17512]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

15.0.0-rc4

### Bug summary

When creating a member, there is validation for the email. But If update an existing member I can insert an invalid email without any validation errors.

![Email](https://github.com/user-attachments/assets/e7d26d47-71ab-4135-9662-8d43c7721248)

### Steps to reproduce

1. Create a member with a valid email
2. Update member email to '4'
3. See no validation issues

### Expected result / actual result

I would expect that there is validation when I am updating the member email

**Comment by Zeegaan** [comment]
Fix for this here: https://github.com/umbraco/Umbraco-CMS/pull/17532
