### ISSUE TITLE
When removing a template from a document type I get a bad request error and the template is not removed

### ISSUE THREAD

**Issue by andr317c** [umbraco/Umbraco-CMS#17513]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

15.0.0-rc4

### Bug summary

I am unable to remove an Allowed Template from a document type

![Template](https://github.com/user-attachments/assets/0d1e2e85-2b2e-421e-903d-4ce8bf22b0c2)
remove

### Steps to reproduce

1. Create a DocumentType with a template
2. Try to remove template

### Expected result / actual result

I would expect that I was able to remove the template

**Comment by bergmania** [comment]
Error seems to be because the payload is wrong:
```json
{
...
   "defaultTemplate": {
      id: ""
   }
...
}
```

instead of the expected
```json
{
...
   "defaultTemplate": null
...
}
```
