### ISSUE TITLE
Nothing happens when click to "Create" button after creating a media folder

### ISSUE THREAD

**Issue by nhudinh0309** [umbraco/Umbraco-CMS#17529]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

15.0.0-rc4

### Bug summary

After I create a media folder, I try to create a media item by clicking the 'Create' button, but nothing happens

### Steps to reproduce

1. Go to Media section
2. Create a new media folder
3. Try to click "Create" button to create new media item

### Expected result / actual result

Nothing happens

https://github.com/user-attachments/assets/3fa0d140-a88c-4cb2-9266-0d43ebb0e24d

---
_This item has been added to our backlog AB#46085_

**Comment by madsrasmussen** [comment]
Fixed by https://github.com/umbraco/Umbraco-CMS/pull/17515
