### ISSUE TITLE
V15 - Splitview for variant blocks breaks when you move blocks around.

### ISSUE THREAD

**Issue by kasparboelkjeldsen** [umbraco/Umbraco-CMS#17533]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

15.0.0

### Bug summary

The split-view editing ends up in a completly broken state if you move a single block around.

### Steps to reproduce

Make a site with 2 or more languages.

Open a page with a block grid editor on it and move an invariant block.

![image](https://github.com/user-attachments/assets/5de80355-aace-42f7-85bc-d5012d3bb0b4)

You end up with this state.

### Expected result / actual result

I'd expect after being done moving blocks, that all blocks are rendered again and editable.

---
_This item has been added to our backlog AB#45934_

**Comment by madsrasmussen** [comment]
Fixed https://github.com/umbraco/Umbraco-CMS/pull/17579
