### ISSUE TITLE
Properties shared across cultures are not editable once populated

### ISSUE THREAD

**Issue by ewuski** [umbraco/Umbraco-CMS#17537]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

13.2.2

### Bug summary

With a multilingual setup (for example 3 languages) some properties of the content are shared (not varied by culture).
Once they become populated, it is not possible to edit them even in the default language.

The following message appears when hovering on the property editor:

`{property name} is shared across all languages.`

{property name} can be any property name over which I am hovering.

It happens to all shared (not varied by culture) properties of all observed doc type.

### Specifics

We have 3 languages setup as per the screenshot:

<img width="1059" alt="Zrzut ekranu 2024-11-14 o 17 52 44" src="https://github.com/user-attachments/assets/7bc835f8-00ff-4f57-a4d0-91ee9a9f34d2">

Then, we have a page with some properties varied by culture:

<img width="1021" alt="Zrzut ekranu 2024-11-14 o 17 57 52" src="https://github.com/user-attachments/assets/3ee03649-65e7-4db8-83df-8524b4887478">

For example, the last property above _Estimated time_, is shared across all cultures.

Once it is populated in more than one language version, it is impossible to edit it in any language - see below:

<img width="880" alt="Zrzut ekranu 2024-11-14 o 18 01 29" src="https://github.com/user-attachments/assets/648c1a0e-b41e-446c-b0e1-71e0e16a536b">

Polish:

<img width="849" alt="Zrzut ekranu 2024-11-14 o 18 01 23" src="https://github.com/user-attachments/assets/6bf09b7f-e195-41a8-ad39-2e9d88bd0ae9">

English (UK):

<img width="869" alt="Zrzut ekranu 2024-11-14 o 18 01 33" src="https://github.com/user-attachments/assets/74243ad2-1fbd-4250-b592-fb5c722a2d04">

French:

<img width="911" alt="Zrzut ekranu 2024-11-14 o 18 01 38" src="https://github.com/user-attachments/assets/4522ca8e-4f20-4a4d-a1f6-fac7754a6bcb">

We can still edit it if we only have one language version of the page added - see below:

<img width="897" alt="Zrzut ekranu 2024-11-14 o 18 02 05" src="https://github.com/user-attachments/assets/6f391c6b-4e93-48b8-870d-11b9a30ac54e">

_Estimated price_ is editable on the only language version of the page:

<img width="861" alt="Zrzut ekranu 2024-11-14 o 18 02 08" src="https://github.com/user-attachments/assets/42821026-0ab0-4424-912e-5633da0be331">

Checked Chrome 129.0.6668.91 & Firefox 132.0.2.

As far as I remember, this issue didn't happen before. Possibly in one of the previous versions of Umbraco as after migrating from version 7 we upgraded from 9 to 10 and then to version 13.

### Steps to reproduce

Add multiple languages to the site as per the above description.
Make a doc type varied by culture.
Make some properties varied by culture and others not.
Add a content page and populate the shared property.
Add another language version of the same page.
Observe the result.

### Expected result / actual result

The shared property should be editable in the default language content version.

---
_This item has been added to our backlog AB#46210_

**Comment by madsrasmussen** [comment]
Hi @ewuski, Thank you for your report. 

I have attempted to replicate your setup, and from what I can observe, the back office behaves as expected. 

In version 13, we have two modes for managing invariant properties across languages. This mode is controlled by the "AllowEditInvariantFromNonDefault" configuration. 
(https://docs.umbraco.com/umbraco-cms/reference/configuration/contentsettings) 

1. **AllowEditInvariantFromNonDefault = false:**   Editing of invariant properties is only permitted from the default language. The property will be disabled for any other language variants. 

2. **AllowEditInvariantFromNonDefault = true:**   It is possible to change invariant properties in all languages. As mentioned in the issue, a popup will appear indicating that it's a shared value. When the editor clicks the "edit" button, the property can be modified. This behavior is consistent across all languages, including the default language, to maintain a uniform user experience. 

Feel free to reopen the issue if I have misunderstood something.
