### ISSUE TITLE
V15 - Multiple hostnames per culture per node causes backoffice crash

### ISSUE THREAD

**Issue by asawyermarathon** [umbraco/Umbraco-CMS#17548]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

15.0.0

### Bug summary

In Umbraco 15, if you specify multiple hostnames per culture for a node, it will cause a backoffice crash and the message "An item with the same key has already been added. Key: [cultureCode]"

### Steps to reproduce

1. Create a new Umbraco 15 site
2. Create a home page doctype, create a node content item of this type
3. Specify multiple hostnames for the same culture
4. Refresh the page
5. Try clicking on the node instance, you will see the error

### Expected result / actual result

Umbraco needs to support multiple hostnames per culture. This isa requirement when using multiple hosting environments.

https://github.com/user-attachments/assets/fdb6ed40-66a8-47cc-9bbd-eae420623f6a

---
_This item has been added to our backlog AB#46064_

**Comment by nikolajlauridsen** [comment]
Fixed in #17572, thanks for reportin 😄
