### ISSUE TITLE
Slider property editor no longer supports decimal values

### ISSUE THREAD

**Issue by matthewcare** [umbraco/Umbraco-CMS#17546]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

15

### Bug summary

I've upgraded to v15, and am finding that my "slider" editor isn't working correctly, whereby I cannot save my document if I change the slider value as now it doesn't seem to support decimals.

### Specifics

Previously I was using this to set the sitemap XML `priority` value, which needs to be between 0 and 1.
![image](https://github.com/user-attachments/assets/882f0280-ca26-4fa2-b1c7-fe54a5bf0978)

Although the validation / tooltip says that the value should be a whole value, it doesn't actually prevent you from saving the data type. (In my case the data type already existed).

![image](https://github.com/user-attachments/assets/e7ba7678-eb2a-4480-968c-2ec41e501b9a)
![image](https://github.com/user-attachments/assets/0a6ef79e-6580-4279-80ef-52dc64df8921)

When viewing the data type on a page, it partially shows decimal values (values above the track are decimal, values below the track are rounded to the nearest whole)

Attempting to save the page results in this error
![image](https://github.com/user-attachments/assets/5bd9afeb-5a23-4189-b83f-0080b41bd9d0)

### Steps to reproduce

Create a slider data type with a decimal initial value and step (as shown in previous picture)
Add the data type to your document type, and try to save a page.

---
_This item has been added to our backlog AB#46062_

**Comment by nikolajlauridsen** [comment]
This turned out to be two issues 😄 The backend is fixed in #17568 and the frontend in UUI https://github.com/umbraco/Umbraco.UI/pull/959

Thanks for reporting 🐛🕵️
