### ISSUE TITLE
V15 - Model.AncestorOrSelf("home") does not work, yet Model.AncestorOrSelf<Home>() does

### ISSUE THREAD

**Issue by asawyermarathon** [umbraco/Umbraco-CMS#17549]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

15.0.0

### Bug summary

In Umbraco 15.0.0, calling `Model.AncestorOrSelf("home")` does not return the ancestor home page with doctype alias "home", yet `Model.AncestorOrSelf<Home>()` does. Is this intentional? I think it is not.

### Steps to reproduce

1. Create new Umbraco 15 site
2. Create two doctypes, home and subpage, allowing subpages to be created under the home doctype
3. Enable strongly typed models (I'm using "SourceCodeManual")
4. Create a node instance of Home with Subpage node underneath
5. In the subpage template, call `var homeNode = Model.AncestorOrSelf("home");` and output an attribute of the home node: `Home Node Name: <strong>@homeNode?.Name</strong>`
6. The data is incorrect, because the call returns the current node instead of the ancestor node.

![devenv_v89K4rZtzA](https://github.com/user-attachments/assets/3d6b7671-ea35-49d3-8392-1c3eb58770eb)

---
_This item has been added to our backlog AB#46060_

**Comment by elit0451** [comment]
Hi @asawyermarathon 👋 

Thanks for reaching out! I can no longer reproduce this when testing on Umbraco 15.1.0 RC. The final version will be available on December 12, so you can upgrade to it 😊
