### ISSUE TITLE
Content Editors Unable To Select Page Template

### ISSUE THREAD

**Issue by nackler** [umbraco/Umbraco-CMS#17571]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

14.3.0

### Bug summary

Content Editors without access to settings in the backoffice are unable to select one of several preconfigured page templates available for a page.

### Specifics

I would like to be able to set up several page templates for a given document type and let my content editors choose one of the templates.  I believe this functionality worked before the backoffice rewrite.  It is close to working except for a permissions error (403 Forbidden) that the content editors get when trying to select a template.

### Steps to reproduce

Set up multiple allowed templates for a "Page" document type.
![image](https://github.com/user-attachments/assets/55c83d5f-4fa4-4900-9665-f1659e83162e)

Then log in to the backoffice as a content editor who just has content and media rights.  Attempt to choose one of the available templates in the Info tab of the page
![image](https://github.com/user-attachments/assets/cb99e8c4-b8f7-4feb-a74e-4c709e59ee7d)

You will see that the template selector is empty and you will get pink errors in the bottom right hand corner
![image](https://github.com/user-attachments/assets/c364b096-efa5-407e-b521-24c3470d8216)

As the result of a request to the managment api
![image](https://github.com/user-attachments/assets/a8e6749b-2420-4695-852d-f6efe2ba0c6f)

### Expected result / actual result

Content editors should be able to choose which template a page uses, even though they do not have access to the 'settings' section of the backoffice.

---
_This item has been added to our backlog AB#46198_

**Comment by elit0451** [comment]
Fixed in #17694
