### ISSUE TITLE
RTE: Anchor gets stripped in UI when re-opening link

### ISSUE THREAD

**Issue by Frost117** [umbraco/Umbraco-CMS#17573]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

13.5.2

### Bug summary

When you add a # to a link in a RTE, you'll see that the link itself is being rendered with the anchor point like so:
![image](https://github.com/user-attachments/assets/78574015-2c8e-4822-871d-d6df6a9badf9)

Front end:
![image](https://github.com/user-attachments/assets/30a3fc31-ff38-4e0f-b36d-358f0ceefd47)

After clicking on link:
![image](https://github.com/user-attachments/assets/1678fe8e-7065-4337-8448-0447d6382a02)

It is only when you re-open the link in the RTE that the # is gone from the Anchor / querystring box:
![image](https://github.com/user-attachments/assets/77f92e44-8c8d-4fd7-ad92-491788de7417)

### Steps to reproduce

1. Create 2 doctypes -> Home Page and a Sub Page
2. In Home Page, add the datatype Richtext Editor.
3. In Home Page, under permission allow as root and add Sub Page as a child.
4. Create 2 Content nodes -> Home Node and a Sub Node.
5. In the Home Node, in the RTE field, write some dummy text.
6. In the RTE on the Home node, add a link to the Sub Node and in the Anchor / querystring box, add an anchor point like so: 
![image](https://github.com/user-attachments/assets/3a166c81-3898-4b17-a6d8-3c183db86bd3)

7. Save the content and view the page. 
8. After verifying the link on the front-end has an anchor point, go back to the backoffice and open the Home node.
9. Click on the link and open the dialog box to see the following:
![image](https://github.com/user-attachments/assets/89b1ca53-1de5-4c7d-a0c8-b361af3bf86d)

### Expected result / actual result

When I save the anchor point with a # then I expect to see that when I open up the dialog box again

---
_This item has been added to our backlog AB#46177_

**Comment by iOvergaard** [comment]
This issue turned out to be something completely different than what I originally thought in my previous comment. I have submitted a potential fix in #17667.
