### ISSUE TITLE
Element Types with no properties (only areas) do not render in Block Grid

### ISSUE THREAD

**Issue by liambeckett** [umbraco/Umbraco-CMS#17592]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

15.0.0

### Bug summary

Previously in Umbraco 14.3.1, I had a number of Element Types with areas but no properties (used in Block Grid to split columns, allow editors in different layouts). Similar to the 2 Column Layout in the Sample Configuration. This was working fine, with rich text editors across multiple columns, etc. After upgrading to 15.0, any NEW items of these element types do not render on frontend and appear greyed out in Umbraco - even if editors are added to one of the areas (see screenshot below). Old content (14.3.1) still renders properly.

![image](https://github.com/user-attachments/assets/86163b93-2d6e-45c2-9d63-d6551ac12c8f)

The only way to have content render is apparently to add an (unused) property and add some content here (see below). Even though this property is not rendered in the CSHTML anywhere. 

![image](https://github.com/user-attachments/assets/93ae7cb6-09b3-4e2d-b895-49158a5c8668)

This is not to do with variants but appears related to having an "area only" block with no properties.

### Steps to reproduce

1. Create a new Block Grid Data Type. Add (or create) a block here that contains only areas (ie. Two Column Layout) and no properties. 
2. Create a document type that includes this Block Grid Data Type. Add "Two Column Area" - notice the element title is "greyed out" in editor/property.
3. Add a property to an area (ie. Headline or Rich Text Editor) and Save & Publish. Block title still appears greyed out and this block/area will not render. Only adding a property to this block item (and giving some sort of value) will cause the block title to go dark and render front-end content. Behaviour differs greatly to 14.3.1.

**Comment by nielslyngsoe** [comment]
Hi @liambeckett thanks for noticing this, its a known bug for the moment which is fixed in 15.1, which is released tomorrow.
There is already another issue with a conversation similar to your own findings. https://github.com/umbraco/Umbraco-CMS/issues/17604
