### ISSUE TITLE
TipTap toolbar goes outside the window

### ISSUE THREAD

**Issue by PhyxionNL** [umbraco/Umbraco-CMS#17598]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

v15

### Bug summary

With a block in inline mode, this happens:
![image](https://github.com/user-attachments/assets/6c2bc6a9-5c18-471b-9a58-bbda383042b5)

### Steps to reproduce

Use Rich Text Editor inside an inline block.

### Expected result / actual result

Should wrap.

**Comment by leekelleher** [comment]
@PhyxionNL Thank you for reporting this and submitting a fix, it's very much appreciated! 🎉
