### ISSUE TITLE
RenderController doesn't support async Index

### ISSUE THREAD

**Issue by mattbrailsford** [umbraco/Umbraco-CMS#17608]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

15

### Bug summary

When using async services in a controller it's necessary for the action to need to return a `Task<IActionResult>` however the `RenderController` base implementation of `Index` only has the return type of `IActionResult`

### Steps to reproduce

Create a hijack controller and override the Index action and then try to access an async service

### Expected result / actual result

We should probably update the index method to be async by default

**Comment by bjarnef** [comment]
I haven't checked if there are changed in v15, but doesn't it overload to implement that in hidr default action?
https://github.com/umbraco/Umbraco-CMS/discussions/17562#discussioncomment-11290676

However without hiding default action it will throw an error about duplicate action with name `Index`.
Not sure if `RenderController` could both have sync/async method to override of the action should be async by default in future?

**Comment by bergmania** [comment]
@mattbrailsford, this is not a bug and it will be super breaking to change. For now I think the proposed solution from @bjarnef is the way to go.

If you still thing we should do something about it, please make a feature request in the discussions instead. Would be interesting to hear if people in general would like such a breaking change :)
