### ISSUE TITLE
v15 - Bellissima - settingsValues not observed in block-entry-context.ts 

### ISSUE THREAD

**Issue by InfiniteSpirals** [umbraco/Umbraco-CMS#17607]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

15.0.0

### Bug summary

When implementing a custom block list view controller (from the example implementation in Umbraco.Web.Ui.Client/examples/block-custom-view.ts) in a clean U15 install, with a block list editor setup with a block with a content model and settings model, the settings model is not observed and the properties are never passed through to the settings property in the ExampleBlockCustomView. 

Debugging source .ts for block-entry-context.ts  in chrome tools shows that at in the method 
public async settingsValues() on line 226 of Umbraco.Web.Ui.Client/packages/block/block/block-entry-context.ts - seems to never execute past the call to await this.#settingsStructurePromise; on line 227. 

### Steps to reproduce

Install a clean U15 install and implement the example "ExampleBlockCustomView" component from Umbraco.Web.Ui.Client/examples/block-custom-view.ts. 

Any changes made to settings are not observed, only content. Settings is always undefined within the ExampleBlockCustomView despite being set in the settings model. 

### Expected result / actual result

Settings should be observed and trigger updates when changed. this.settings should be populated on the ExampleBlockCustomView

**Comment by nielslyngsoe** [comment]
@InfiniteSpirals thanks for reporting this. As a user of the Block Editor you should look forward to 15.1, which in general corrects and fixes various things in these Property Editors.
This specific issue is also fixed in this version by this PR.
https://github.com/umbraco/Umbraco-CMS/pull/17578

Therefor I'm closing this issue :-)
