### ISSUE TITLE
Inserting Partial View name is wrongly formatted when inserted in a template

### ISSUE THREAD

**Issue by elit0451** [umbraco/Umbraco-CMS#17614]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

14.3.1; 15.0.0

### Bug summary

Inserting a Partial View in a template results in "An unhandled exception" when visiting the view of the published page, caused by a wrongly formatted Partial View name.

### Specifics

When a Partial View with the name `Empty.cshtml` is selected for insertion in a template, `@await Html.PartialAsync("%2FEmpty%25dot%25cshtml")` line is being added to the template which doesn't work. Instead, the Partial View name should be formatted correctly, like `@await Html.PartialAsync("Empty")`

### Steps to reproduce

- In the Settings section, create a Partial View from any snippet and give it a name of your choice;
- Create a content type **with template**;
- Visit the template and insert the Partial View you just created;
- Create and publish a content node from that content type;
- In the Info tab of the content node, access the link.

### Expected result / actual result

Expected: The partial view to be rendered correctly;
Actual: 
![Error](https://github.com/user-attachments/assets/5ce2984d-ccdc-44fa-8825-63cc155625f1)

---
_This item has been added to our backlog AB#46482_

**Comment by Migaroez** [comment]
Fixed in https://github.com/umbraco/Umbraco-CMS/pull/17687
