### ISSUE TITLE
.br & .gz files showing in the backoffice  for Javascript files & CSS files when upgrading to v15 from 14

### ISSUE THREAD

**Issue by Abdjulaziz** [umbraco/Umbraco-CMS#17615]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

15.0.0

### Bug summary

It seems like when you upgrade from 14 → 15 the original file gets a `.br` & `.gz` this has happened to js files and css files

![image](https://github.com/user-attachments/assets/eaba8d6a-a367-4274-8d36-77a8873ebd25)

### Specifics

Got suggested adding this to `.csproj`

`<CompressionEnabled>false</CompressionEnabled> <!-- Disable compression. E.g. for Umbraco backoffice files. These files should be precompressed by node and not let dotnet handle it --> `

That fixes the issue with the extra two files

It would make sense to group the generated .br and .gz files to their main/parent file 

### Steps to reproduce

Have a Javascript file or CSS file or both
Upgrade from v14 to v15
then you should the the below

![image](https://github.com/user-attachments/assets/eaba8d6a-a367-4274-8d36-77a8873ebd25)

### Expected result / actual result

The expected behavior would be to get one file and not 3 files.

Instead of getting e.g.
```
.js
.br
.gz
```

You get just a single file

`.js`

**Comment by iOvergaard** [comment]
Hey @Abdjulaziz and @nul800sebastiaan, this setting is already set for the built-in Umbraco.Cms.StaticAssets RCL so that our assets are not compressed. The default in .NET is to enable compression. People can define this directly in their .csproj files. Are you suggesting we set this option to `false` by default in our templates, or what exactly are you proposing?

**Comment by Abdjulaziz** [comment]
Hi @iOvergaard 
We have two options I guess. Adding the option `false` by default or having this in our upgrading guide.

**Comment by iOvergaard** [comment]
@Abdjulaziz I am afraid this has nothing to do with Umbraco, it is an ASP.NET Core setting enabled default in their version 9. It is mentioned in their [upgrade guide](https://learn.microsoft.com/en-us/aspnet/core/migration/80-90?view=aspnetcore-9.0&tabs=visual-studio#replace-usestaticfiles-with-mapstaticassets):

> ASP.NET Core automatically fingerprints and precompresses your static files at build and publish time, and then [MapStaticAssets](https://learn.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.builder.staticassetsendpointroutebuilderextensions.mapstaticassets) surfaces the optimized files as endpoints using endpoint routing with appropriate caching headers.

Unfortunately, they then make it a bit obscure to figure out how to turn it off, which is done by setting `<CompressionEnabled>false</CompressionEnabled>`.

Umbraco sets this to `false` as well if you use our templates `dotnet new umbraco`, but that is about the extent that we can do code-wise.

I am sure we could mention it in the version-specific upgrade guide on UmbracoDocs, although we would normally refer to the .NET migration guide from Microsoft. I would advise mentioning this to the [UmbracoDocs](https://github.com/umbraco/umbracodocs) team, or if anyone would like to create a PR with the mention, that would surely be appreciated as well.

I will go ahead and close this issue as it seems we cannot do more on this repository.
