### ISSUE TITLE
Drag and Drop Reordering properties From no-group to group doesn't work

### ISSUE THREAD

**Issue by nackler** [umbraco/Umbraco-CMS#17611]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

14.3.0

### Bug summary

When reordering properties on a document type using the drag and drop feature of the document type designer, I am unable to move properties from the root level (outside of any group) into a group.  It looks like it will work when you click 'I am done reordering' but when you save the document the change isn't saved.  Should also be able to move properties from a group up into the non-group section at the top.

### Specifics

Create a document with some properties that don't live inside any property group.  Create other properties inside a group.  Should be able to drag top-level properties into a group and vice-versa.  Unfortunately when you save the document the changes aren't persisted.

![image](https://github.com/user-attachments/assets/3f7aad99-be17-4198-91e0-4e4c2dbb773a)

I also can't drag/drop properties between tabs, but that should probably be a separate issue.

### Steps to reproduce

Create a document with some properties that don't live inside any property group.  Create other properties inside a group.  Drag some top-level properties into a group then click 'I am done reordering' then 'save'.  

### Expected result / actual result

After saving the reordered property list, the properties should be in the new order

**Comment by DanielToft** [comment]
This is also described in this issue #17462

**Comment by iOvergaard** [comment]
Hello, and thanks for the report. As @DanielToft said, issue #17462 should cover this scenario. Therefore, I would like to close this issue off and refer further discussion to the linked issue.
