### ISSUE TITLE
v15 - LoginBackgroundImage has no effect when external auth providers added

### ISSUE THREAD

**Issue by mjpraxis** [umbraco/Umbraco-CMS#17633]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

15.0.0

### Bug summary

Register "LoginBackgroundImage" in the settings under Umbraco->CMS->Content has does not work on the "choose" login provider page.

### Specifics

/umbraco
Shows the default login image
![image](https://github.com/user-attachments/assets/dbf7cbb8-b4d8-48cb-9704-7c59097f0f1f)

/umbraco/login
Shows the correct image from the settings in the "LoginBackgroundImage"

### Steps to reproduce

**Add image to wwwroot** eg. "/wwwroot/test.png"

**Add setting to appsettings.json**
Umbraco
   CMS
       Content
           "LoginBackgroundImage": "../test.png"

**Add a manifest file to App_Plugins**
![image](https://github.com/user-attachments/assets/98282b61-08ee-42bd-b2ac-cb0b11520355)

```
{
  "$schema": "../../umbraco-package-schema.json",
  "name": "My Auth Package",
  "allowPublicAccess": true,
  "extensions": [
    {
      "type": "authProvider",
      "alias": "My.AuthProvider.Generic",
      "name": "My Auth Provider",
      "forProviderName": "Umbraco.Generic",
      "meta": {
        "label": "Generic",
        "defaultView": {
          "icon": "icon-cloud"
        },
        "behavior": {
          "autoRedirect": false
        },
        "linking": {
          "allowManualLinking": true
        }
      }
    }
  ]
}
```

**Start Umbraco**

**/umbraco** will now show the default image and the two login providers (Umbraco and Generic)

**Click the "Sign in with Umbraco"**

**/umbraco/login** shows the "custom" login background image

**Comment by iOvergaard** [comment]
Hi @mjpraxis, thanks for reporting this. We already have a similar report at #17441, so forgive me for closing this. We will be tracking the issue over at the other report.
