### ISSUE TITLE
Existing content saved and published in block grid inline mode not saving

### ISSUE THREAD

**Issue by jbrisnehan-AMG** [umbraco/Umbraco-CMS#17634]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

15.0.0

### Bug summary

Existing content saved and published in block grid inline mode not saving

Switching "Inline Mode" off on the Block Editor, solves the issue and the new content is saved.

Creating new content/areas also works fine.  Just editing existing content is an issue.

### Specifics

Umbraco Cloud.  Checked/tested in multiple environments.

### Steps to reproduce

Upgraded to v15.  

1. Opening and edit an existing page/node that has a Block Grid editor. 
2. Edit a content area of the Block Grid editor on the page (i.e. RTE or Header)
3. Add new text (i.e. "test")
4. Click Save and Publish.
5. Save and Publish is successful.
6. However the frontend does not reflect the change
7. If you click away from the node and come back, the change is gone.

### Expected result / actual result

I would expect content to save properly in the Block Grid whether in "Inline Mode" or not.

---
_This item has been added to our backlog AB#46333_

**Comment by nielslyngsoe** [comment]
Hi @jbrisnehan-AMG 

Thanks for reporting this, we will be looking into wether we are able to replicate this migration problem.

**Comment by nielslyngsoe** [comment]
Hi @jbrisnehan-AMG may I ask if this is solved with the outcomes of the conversation in this issue?
https://github.com/umbraco/Umbraco-CMS/issues/17604

**Comment by jbrisnehan-AMG** [comment]
Hey Niels,
Just waiting for version 15.1 to confirm resolution.

Jeff Brisnehan
VP, Information Technology
American Marketing Group, Inc.
________________________________

**Comment by jbrisnehan-AMG** [comment]
I was able to test and confirm this issue is resolved in Umbraco version 15.1.0-rc; existing content saves properly in the block editor using inline mode.

**Comment by nielslyngsoe** [comment]
Thanks @jbrisnehan-AMG for letting me know, then I will close this issue. Thanks
