### ISSUE TITLE
v15 Auditservice GetLogs return items with an default Datetime as createdate

### ISSUE THREAD

**Issue by jbppraxis** [umbraco/Umbraco-CMS#17638]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

v15.0

### Bug summary

I needed to get auditlogs for a specific node. So i DI the IAuditservice and used the GetLogs() e.g.
` _auditService.GetLogs(rootContent.Id);` however alle the items which is returned has a default createdate.

I then tried the GetPageBy... instead `_auditService.GetPagedItemsByEntity(rootContent.Id, 0, 10, out var total, auditTypeFilter: [AuditType.Publish]);` This call returned items witn an createdate.

I took a look into github and found that there is an explicit mapping of createdate in GetPagedResultsByQuery
https://github.com/umbraco/Umbraco-CMS/blob/475faba5fd65303ab3101d4a011ca3154e649797/src/Umbraco.Infrastructure/Persistence/Repositories/Implement/AuditRepository.cs#L110
 which is not in Get. https://github.com/umbraco/Umbraco-CMS/blob/475faba5fd65303ab3101d4a011ca3154e649797/src/Umbraco.Infrastructure/Persistence/Repositories/Implement/AuditRepository.cs#L22

 It might be by design or it might not be related or it might be an bug :)

### Steps to reproduce

Denpendency inject the auditservice and try the getlogs method and see that the createdate is default

### Expected result / actual result

I would expect the createdate to have an value

**Comment by Zeegaan** [comment]
Heyo 👋 
I sadly cannot reproduce this, when i call `GetLogs`, I get a CreateDate out too:
![image](https://github.com/user-attachments/assets/9b978df4-a63f-44c8-9ba8-2106669c5a39)

The DateStamp also gets passed when getting it from the Database, but it might not have had a value for you in there 🤔 
![image](https://github.com/user-attachments/assets/0ef203ed-0136-485b-a49e-683f59216fa5)

Can you check your `UmbracoLogs` table, and see if theres a value in the DateStamp column? 🤔 
![image](https://github.com/user-attachments/assets/fd117ab9-6377-44b4-adf0-5045004bb682)

**Comment by jbppraxis** [comment]
@Zeegaan thanks for looking into it. I check my sql lite db everything has a datestamp. Screenshot from db and from debugger.
![image](https://github.com/user-attachments/assets/cd896c51-c3c8-4ed9-81c4-7bd4381a0fd1)
![image](https://github.com/user-attachments/assets/e270ae81-223c-46a3-b895-a8818ba294bc)

Am I missing something? :)
What version of umbraco did you use?
