### ISSUE TITLE
Markdown (in Property Descriptions) are not properly rendering if repeated. See example.

### ISSUE THREAD

**Issue by markadrake** [umbraco/Umbraco-CMS#17646]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

13.5.2

### Bug summary

Repeated use of "markdown" in your property descriptions
can cause strange effects.

### Steps to reproduce

- Given any property editor,
- Fill out the description with the text below.
- Save your changes.
- The bold text will instead span from the beginning of the first, to the end of the last.

```
Filter the list of suppliers by connecting a **type** of service record to one or more **categories**.
```

![image](https://github.com/user-attachments/assets/d6d6b79a-0a3a-433a-8f8d-98c2ee3dd5d5)

![image](https://github.com/user-attachments/assets/2c308345-a2a4-44ee-891b-e610ce4663da)

### Expected result / actual result

I expect only the words **type** and **categories** to be rendered boldly.

This is the result:

![image](https://github.com/user-attachments/assets/d6d6b79a-0a3a-433a-8f8d-98c2ee3dd5d5)

![image](https://github.com/user-attachments/assets/2c308345-a2a4-44ee-891b-e610ce4663da)

**Comment by iOvergaard** [comment]
Hello, thanks for reporting this. I am a bit unsure whether the markdown syntax was ever really supported in property descriptions in V13 and below. It seems the implementation is rather custom and not sanitized by any client-side library. "Real" Markdown is supported from V14 and up, so this particular issue is not present there at least. I can verify that the issue exists up to V13. I would like to mark this issue as up-for-grabs as we'd be happy to accept a pull request that fixes the issue.
