### ISSUE TITLE
Content page not updating correctly when navigation in the content tree

### ISSUE THREAD

**Issue by DanielToft** [umbraco/Umbraco-CMS#17650]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

15.0.0

### Bug summary

When navigating in the content tree, sometimes the content doesn't reflect the content I click on. The URL changes but the content is the same.

I think this also happens when I'm in the Media and Settings sections.

### Steps to reproduce

Click around in the node tree and you will eventually see that the document content does not change.

1. Create a document type with Block list/ Block grid inside
2. Create a content page by the document type created.
3. Go to the content page without changing anything and click to another tap (Media/Settings...) or other content page
4. A popup notification "You have unsaved changes" will appear

---
_This item has been added to our backlog AB#46922_

**Comment by NguyenThuyLan** [comment]
Hi @DanielToft , could you please give us more details on how to reproduce? it would be great if you have a video or something

**Comment by DanielToft** [comment]
Hi @NguyenThuyLan 

I can't find a systematic way to reproduce this issue it just happens randomly when you navigating in umbraco.

It happens very often on our dev machine with a remote sql connection to azure. So the database connection is a bit slow due to latency. I'm not sure it's related to this, because it also happens in production with a fast SQL connection.

I have a recording of the problem here. Note that the "Unsaved Changes" dialog has nothing to do with this problem. This is a new issue introduced in version 15.1.0-rc.

https://github.com/user-attachments/assets/b1db1dff-a7f6-41c1-b5ae-3b21b7ff8856

**Comment by DanielToft** [comment]
Hi @NguyenThuyLan, thanks for the update. But the Discard Changes dialog, still appear on my documents in version 15.1.0-rc2 :(

**Comment by NguyenThuyLan** [comment]
Hi @DanielToft , I noticed we still have "Discard Changes dialog" on content pages that have Block List or Block grid inside.
On your video, I'm sure that you are using Block editor or not, or maybe you are using other editor that could lead to this issue.
Anyway, I will change the title of this issue for more clear

**Comment by DanielToft** [comment]
Hi @NguyenThuyLan, Yes i'm using Block Grid.

But, this issue was not intended to be about the discard changes dialog. The video i have posted you can see that it's always the same page (Forside), shown when navigating in the tree.

**Comment by nielslyngsoe** [comment]
Fixed by https://github.com/umbraco/Umbraco-CMS/pull/17774 — will be released as part of the v.15.1.1

**Comment by DanielToft** [comment]
@nielslyngsoe You cannot close this issue. This issue is not about the Discard Changs Dialog!

**Comment by nielslyngsoe** [comment]
@DanielToft you are right, sorry for the mistake.

**Comment by Zeegaan** [comment]
Fixed in https://github.com/umbraco/Umbraco-CMS/pull/17783 🚀
