### ISSUE TITLE
v15.1-rc - ' UMB_DOCUMENT_TYPE_FOLDER_ENTITY_TYPE' export has moved - breaking change? 

### ISSUE THREAD

**Issue by KevinJump** [umbraco/Umbraco-CMS#17678]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

v15.1-rc

### Bug summary

It looks like the export of the 'UMB_DOCUMENT_TYPE_FOLDER_ENTITY_TYPE' has been moved 
and hence if you have extension code that imports the type it fails on v15.1 with the following :

```
'@umbraco-cms/backoffice/document-type' does not provide an export named 'UMB_DOCUMENT_TYPE_FOLDER_ENTITY_TYPE'
```

### Specifics

It looks like the export of the 'UMB_DOCUMENT_TYPE_FOLDER_ENTITY_TYPE' has been moved 
and hence if you have extension code that imports the type it fails on v15.1 with the folllowing :

```
'@umbraco-cms/backoffice/document-type' does not provide an export named 'UMB_DOCUMENT_TYPE_FOLDER_ENTITY_TYPE'
```

### Steps to reproduce

On v15 extension code can import the `UMB_DOCUMENT_TYPE_FOLDER_ENTITY_TYPE` using: 

```
import { UMB_DOCUMENT_TYPE_FOLDER_ENTITY_TYPE,} from '@umbraco-cms/backoffice/document-type';
```

this doesn't work from v15.1-rc as the import has moved. 

***N.B: I can't test what the new value as is there is no published v15.1-rc version of the backend client package on npm?***

existing client code built against v15 breaks because of this. 

### Expected result / actual result

client side extensions build against the v15 umbraco back office package should still work when running against v15.1 versions of Umbraco 

---
_This item has been added to our backlog AB#46666_

**Comment by bergmania** [comment]
Thanks for letting us know.. We'll look into it

**Comment by nielslyngsoe** [comment]
Hi @KevinJump Thanks for informing us about this one. To prevent this ever happening again I took the time to make a test that ensures consts starting by `UMB_` is exposed. So hopefully the last time you would have to repport an issue like this.

Thanks in advance.
