### ISSUE TITLE
V15: Multi URL Picker - Picking content node leaves link name blank

### ISSUE THREAD

**Issue by davidkosir2** [umbraco/Umbraco-CMS#17720]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

15.0.0

### Bug summary

When using Multi URL Picker, on selecting content node leaves link name blank. I found a workaround that uses UmbracoHelper to retrive content Name but it used to work without workarounds. Also in Umbraco, by default, URL name is blank.

Setup:
![image](https://github.com/user-attachments/assets/b886f58c-9e7c-4cbb-accc-b687710ab9cc)

Result on FE:
![image](https://github.com/user-attachments/assets/f018eeef-402c-4382-a9c6-547b4fd3b5fc)

### Steps to reproduce

- Install Umbraco v15.0.0
- Configure ModelsBuilder
- Create new document type with template (Allow as root)
- Add property "Links" and user Multi URL Picker
- Create new page
- Set page name
- Publish page
- Add new URL for property Links (select current page or any othr page)
- Render all links using foreach statement in template

### Expected result / actual result

Content name should be shown when rendering "Link.Name"

**Comment by NguyenThuyLan** [comment]
Hi @davidkosir2 ,I was not able to reproduce on v15.1.0-rc, it seems to be fixed, see the video below 😊
https://github.com/user-attachments/assets/1e9e2af4-a6a6-4a4c-aecd-bf09b5d3f8af
