### ISSUE TITLE
Rich Text Editor creates false alert "You have unsaved changes"

### ISSUE THREAD

**Issue by NguyenThuyLan** [umbraco/Umbraco-CMS#17733]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

15.1.0-rc

### Bug summary

Click out of the Content page with Rich Text Editor without changing anything, and the popup "You have unsaved changes" appears.

### Specifics

Happens on both Tiptap or TinyMCE RTE

### Steps to reproduce

1. Create a document type with RTE inside
2. Create a content page by the document type created.
3. Go to the content page without changing anything and click to another tap (Media/Settings...) or other content page
4. A popup notification "You have unsaved changes" will appear

### Expected result / actual result

Popup notification "You have unsaved changes" should not appear when click out of the content page without changing anything.

**Comment by nielslyngsoe** [comment]
Hi @NguyenThuyLan, Thanks, this will be fixed in the up coming rc-2 as of this PR:
https://github.com/umbraco/Umbraco-CMS/pull/17692
