### ISSUE TITLE
Add Click-Outside Close to Modals

### ISSUE THREAD

**Issue by martinthogersen** [umbraco/Umbraco-CMS#17734]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

14.3.1

### Bug summary

I'm not sure if this qualifies as a bug, but multiple users have reported perceiving it as such:

We’ve set up a modal using UmbModalBaseElement in Umbraco, which functions as expected. We also added a close button in the action slot, and it works correctly. However, users expect to be able to close the modal by clicking outside of it, which is currently not supported. See the image below:

![image](https://github.com/user-attachments/assets/40fd1541-4c32-4d2b-bf35-f1ff0795c32f)

Here’s the code we’re using for the modal:
```js
class CustomModalElement extends UmbModalBaseElement {
  constructor() {
    super()
  }

  connectedCallback() {
    super.connectedCallback()
  }

  #handleClose() {
    this.modalContext?.reject()
  }

  render() {
    return html`
      <umb-body-layout headline=${"Custom dialog"}>
        <uui-box>Example</uui-box>
        <div slot="actions">
          <uui-button id="cancel" label="Cancel" @click="${this.#handleClose}">Close</uui-button>
        </div>
      </umb-body-layout>
    `
  }
}
```

Would you consider implementing support for dismissing the modal when clicking outside it? It seems to align with user expectations and improve usability.

### Steps to reproduce

See above.

---
_This item has been added to our backlog AB#46777_

**Comment by nielslyngsoe** [comment]
Hi @martinthogersen Thanks for bringing UX feedback, just as important as issues. And I love these perspectives and ideas so bring more please.

I tend to agree — But from my current perspective it mainly relies on ensuring that modals, and custom once like yours, easily can implement a Discard Changes Dialog (which will be prevent the user from accidentally closing if there was any changes made within the dialog).
So we first need to ensure that we will not be creating an annoying feature — so users who accidentally click outside the modal lose their progress.
Maybe we even would need to enforce such implementation in some way, so we ensure that no dialogs can have accidental closes.

— With that perspective the prioritization of such will not be immediate, I would suggest that you write this up in a discussion, in this way more users can bring their perspectives. Such will also be helpful in terms of prioritization of such.

I hope you will be up for that, and then I will close this specific issue. :-)

Thanks
