### ISSUE TITLE
Item in Tree does not get selected after reloading the page or after entering a DeepLink

### ISSUE THREAD

**Issue by a-t-k** [umbraco/Umbraco-CMS#17746]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

15

### Bug summary

When a child item in Umbraco's tree is selected and then reloaded or a URL with parameters entered, the entire tree closes. The automatic opening of parents containing the selected item is no longer available.

### Specifics

-

### Steps to reproduce

Select a child item in the tree and reload the page. The tree is now closed, and the child item is no longer visible. However, when you open all parents without selecting them, the child item becomes marked as "Selected".

### Expected result / actual result

All parents of the child item remain open after reloading or entering a DeepLink.

**Comment by NguyenThuyLan** [comment]
Hi @a-t-k , thank you for reporting this issue. it seems to be duplicated with issue [#17076](https://github.com/umbraco/Umbraco-CMS/issues/17076), I will mark this issue as a duplicate and then we collect our thoughts in the same place.
