### ISSUE TITLE
RTEs within Grid Layout do not work after reordering

### ISSUE THREAD

**Issue by Wiggee11** [umbraco/Umbraco-CMS#17752]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

13.4.1

### Bug summary

If you create a Grid Layout with multiple RTEs in it, and reoder them, you cannot edit those RTEs afterwards.

If you save/publish and refresh the page, the ordering is retained and the RTEs are editable again.

This looks to be a long-standing issue from Umbraco 8, possibly regressed from the updates to Tiny MCE (a guess):
https://github.com/umbraco/Umbraco-CMS/issues/6947
https://github.com/umbraco/Umbraco-CMS/pull/6954
https://github.com/umbraco/Umbraco-CMS/issues/4752

### Steps to reproduce

https://github.com/user-attachments/assets/dc1b56ef-8953-4ca2-810b-f2bd1c9021e9

### Expected result / actual result

Reordering RTEs should retain the new order and the RTEs should be editable.

**Comment by NguyenThuyLan** [comment]
Hi @Wiggee11 , we highly recommend that you use the Block Grid instead.
The Grid Layout has been marked as obsolete and development on the property editor has been discontinued. It will be removed as a core property editor with the release of Umbraco 14, planned for Summer 2024.
