### ISSUE TITLE
The Published Content API has become significantly slower in 15.1.0-rc2

### ISSUE THREAD

**Issue by DanielToft** [umbraco/Umbraco-CMS#17768]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

15.1.0-rc2

### Bug summary

After upgrading from 15.1.0-rc to 15.1.0-rc2, I have noticed that the Published Content API has become significantly slower.

My API endpoint, where I run a query on about 500 child nodes, used to take 30-50ms and now takes 800ms-1sec to execute.

I'm querying on MultiNodeTreePicker, TrueFalse and Textstring properties.

```
IPublishedContent content = GetContent()

edition
    .Children() // 500 nodes
    .Where(x => ...)
    .Skip(0)
    .Take(30)
    .Select(x => ...)
    .ToArray()
```

I have testet with and without Redis Distributed cache and there is no difference.

### Steps to reproduce

- Create approximately 500 nodes 
- Create content on these nodes using MultiNodeTreePicker, TrueFalse and Textstring properties
- Query the nodes and properties and measure execution time

### Expected result / actual result

The execution time will be between 30ms - 70ms

**Comment by Zeegaan** [comment]
Fixed in https://github.com/umbraco/Umbraco-CMS/pull/17779 😁
