### ISSUE TITLE
BlockLists and BlockGrids detects changes while there are none

### ISSUE THREAD

**Issue by engern** [umbraco/Umbraco-CMS#17784]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

15.1.0

### Bug summary

When navigating between nodes which has a BlockList or BlockGrid you get the "Discard Changes"-dialogue. 

https://github.com/user-attachments/assets/9ddae119-b7b8-46d3-b622-d33a8a870918

### Specifics

I did a JSON.stringify(x) on both _persisted and _current element in getHasUnpersistedChanges() (entity-workspace-data-manager.ts) and see that the _persisted is missing the entire BlockGrid in the values-array. So I guess this must be why it always detect that the current node is different from the persisted.
![image](https://github.com/user-attachments/assets/60b896c6-0807-4a22-b0ad-985bbb5a0137)

### Steps to reproduce

1. Create a DocumentType with a BlockList
2. Create a content node/page with the document type in step 1
3. Open the conent node created in step 2 (the tab with the BlockList must be selected)
4. Navigate to another content node without doing any changes
5. The "Discard Changes"-dialogue appears

### Expected result / actual result

No "Discard Changes"-dialogue when navigating away from a node without doing any changes

**Comment by Zeegaan** [comment]
Fixed in https://github.com/umbraco/Umbraco-CMS/pull/17774 🚀
