### ISSUE TITLE
Unable to configure or delete block grid area in Umbraco 15.1.0

### ISSUE THREAD

**Issue by stephen-sherman** [umbraco/Umbraco-CMS#17788]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

15.1.0

### Bug summary

The `umb-block-area-config-entry` element does not render any contents, making users unable to customise the width of a block grid area or delete previously created block grid areas.

### Steps to reproduce

1. Install a new Umbraco 15.1.0 solution
2. Configure a block grid data type to include a block with an area of non-default width

### Expected result / actual result

**Expected result**
- When creating a block, be able to
  - Create an area
  - Set the width of an area (i.e.: 12 columns)
  - Be able to delete an area 

**Actual result**
- Areas can be created, but the user interface for setting the width of an area or deleting an area is missing. 

![Screenshot 2024-12-12 154233](https://github.com/user-attachments/assets/24a26b9c-eb74-4d09-988d-27be1d6ae810)

**Comment by nielslyngsoe** [comment]
Hi @stephen-sherman 

Thanks for spotting this, we did though already know about this and have it fixed, but there was an accidental too early release of 15.1. :-(

A Patch including this fix is on its way, it will then be versioned as 15.1.1. This will be out later today.

Sorry for the inconvenience
