### ISSUE TITLE
Timeout Error During Umbraco 14.3.1 to 15.1.0 Upgrade

### ISSUE THREAD

**Issue by martinthogersen** [umbraco/Umbraco-CMS#17810]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

14.3.1

### Bug summary

I'm trying to upgrade an Umbraco website with extensive content from version 14.3.1 to 15.1.0.

Following the recommendations in this article: https://docs.umbraco.com/umbraco-cms/fundamentals/setup/upgrading/version-specific/migrate-content-to-umbraco-15, I cleaned up the old content versions to prepare for the migration.

However, I'm encountering a timeout error during the upgrade process. The error occurs approximately 40 minutes into the upgrade.

Is there a way to migrate the content in batches or alternative methods to resolve this issue?

See the error output from my terminal below:

> [16:30:57 INF] Migration starting for all properties of type: Umbraco.BlockList
> [16:30:57 INF] - starting property type 1/20 : Page content (id: 52, alias: pageContent)...
> [17:09:54 ERR] Exception (e6e72235).
> Microsoft.Data.SqlClient.SqlException (0x80131904): Execution Timeout Expired.  The timeout period elapsed prior to completion of the operation or the server is not responding.
>  ---> System.ComponentModel.Win32Exception (258): Unknown error: 258
>    at Microsoft.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
>    at Microsoft.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
>    at Microsoft.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, SqlCommand command, Boolean callerHasConnectionLock, Boolean asyncClose)
>    at Microsoft.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
>    at Microsoft.Data.SqlClient.SqlDataReader.TryConsumeMetaData()
>    at Microsoft.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString, Boolean isInternal, Boolean forDescribeParameterEncryption, Boolean shouldCacheForAlwaysEncrypted)
>    at Microsoft.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean isAsync, Int32 timeout, Task& task, Boolean asyncWrite, Boolean inRetry, SqlDataReader ds, Boolean describeParameterEncryptionRequest)
>    at Microsoft.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry, String method)
>    at Microsoft.Data.SqlClient.SqlCommand.ExecuteReader(CommandBehavior behavior)
>    at Microsoft.Data.SqlClient.SqlCommand.ExecuteDbDataReader(CommandBehavior behavior)
>    at StackExchange.Profiling.Data.ProfiledDbCommand.ExecuteDbDataReader(CommandBehavior behavior) in C:\projects\dotnet\src\MiniProfiler.Shared\Data\ProfiledDbCommand.cs:line 204
>    at Umbraco.Cms.Infrastructure.Persistence.FaultHandling.RetryPolicy.ExecuteAction[TResult](Func`1 func)
>    at NPoco.Database.ExecuteReaderHelper(DbCommand cmd)
>    at NPoco.Database.ExecuteDataReader(DbCommand cmd, Boolean sync)
>    at NPoco.AsyncHelper.RunSync[T](Task`1 task)
>    at NPoco.Database.QueryImp[T](T instance, Expression`1 listExpression, Func`2 idFunc, Sql Sql, PocoData pocoData)+MoveNext()
>    at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
>    at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
>    at NPoco.Database.Fetch[T](Sql sql)
>    at System.Linq.Enumerable.IEnumerableSelectIterator`2.MoveNext()
>    at Umbraco.Extensions.EnumerableExtensions.SelectByGroups[TResult,TSource](IEnumerable`1 source, Func`2 selector, Int32 groupSize)+MoveNext()
>    at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
>    at Umbraco.Cms.Infrastructure.Persistence.Repositories.Implement.ContentRepositoryBase`3.GetPropertyCollections[T](List`1 temps)
>    at Umbraco.Cms.Infrastructure.Persistence.Repositories.Implement.DocumentRepository.MapDtoToContent(DocumentDto dto)
>    at Umbraco.Cms.Infrastructure.Persistence.Repositories.Implement.DocumentRepository.ContentByGuidReadRepository.PerformGet(Guid id)
>    at Umbraco.Cms.Core.Cache.DefaultRepositoryCachePolicy`2.Get(TId id, Func`2 performGet, Func`2 performGetAll)
>    at Umbraco.Cms.Core.Services.ContentService.GetById(Guid key)
>    at Umbraco.Cms.Core.PropertyEditors.MultiUrlPickerValueEditor.ToEditor(IProperty property, String culture, String segment)
> ClientConnectionId:366a038b-22b2-4a08-8da0-0bbd88914661
> Error Number:-2,State:0,Class:11

### Steps to reproduce

See above.

**Comment by kjac** [comment]
Hi @martinthogersen,

Interesting. The exception happens while reading content from the database - during migration, but not as a direct result of the migration. It seems to be fetching content picked in a Multi URL Picker.

Are you experiencing any load issues when running the DB in V14?

**Comment by martinthogersen** [comment]
@kjac

No load issues occur in Umbraco 14.3.1: The website functions as expected, and it boots without any problems.

**Comment by kjac** [comment]
Alrighto. Thanks. Can you try boosting the connection timeout in your SQL connection string? I known you're not having connection timeouts, but it implicitly also affects the command timeout in Umbraco 😄 so... something like `;Connect Timeout=300;` should bump the default 30 seconds to 5 minutes.

**Comment by martinthogersen** [comment]
@kjac 
I've tried using the following connection string:
`Server=localhost;Database=database_name;User Id=username;Password=password;TrustServerCertificate=True;Command Timeout=300;Connect Timeout=300;`

However, I’m still encountering the same error.

**Comment by martinthogersen** [comment]
@kjac The client has approved sharing the database with you. What is the best way to send it privately?

Can I contact you via email?

**Comment by Zeegaan** [comment]
Fixed in https://github.com/umbraco/Umbraco-CMS/pull/17827 🚀
