### ISSUE TITLE
Custom member propeties other then a string or number not available with GetValue()

### ISSUE THREAD

**Issue by Timvdburgt** [umbraco/Umbraco-CMS#17821]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

14.3.1

### Bug summary

I have added a toggle and a contentpicker as a custom property to my membertype. When I try to get the value from my members with `GetValue<bool>()` or `GetValue<IEnumerable<IPublishedContent>>()` there is no value available. When I use a number or text field this is not a problem with `GetValue<string>()` or `GetValue<int>()`.

### Specifics

` var currentMember = await _memberManager.GetCurrentMemberAsync();
 var member = _memberService.GetByKey(currentMember.Key);
 var value = member.GetValue<bool>("shippingAddressSameAsInvoiceAddress")
 `

### Steps to reproduce

Add a custom toggle or contentpicker field to a membertype. Then try to get the value from the member in code.

### Expected result / actual result

I expected en value returned in code with the toggle field and content picker field. Now I have to make all my custom fields a text or number field to make my custom code work.

**Comment by NguyenThuyLan** [comment]
Hi @Timvdburgt , I tested on both 14.3.1 and v15.1.1, I can still get value of member like this
<img width="677" alt="image" src="https://github.com/user-attachments/assets/418872a4-6ce9-4444-97d5-9a2ab55f90e9" />
I was not able to reproduce your case. Please give us more details

**Comment by NguyenThuyLan** [comment]
Hi @Timvdburgt , value of Content Picker stored is String type, not 
<img width="644" alt="image" src="https://github.com/user-attachments/assets/6e1c131d-eaa5-47cd-830d-d8159bae54ed" />
So you can not use IPublishcontent in this case

**Comment by Timvdburgt** [comment]
@NguyenThuyLan alright that explains a lot thanks!
