### ISSUE TITLE
V15.1.1 - MemberManager.AsPublishedMember can no longer map to custom PublishedContentModel using Models Builder

### ISSUE THREAD

**Issue by davidkosir2** [umbraco/Umbraco-CMS#17831]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

15.1.1

### Bug summary

I used to be able to automatically map member to generated class by using this code:

`if (_memberManager.AsPublishedMember(memberIdentity) is ModelsBuilderDirectory.Member member)
{
  //some code here
}`

but it no longer works, it only maps to Umbraco.Cms.Core.Models.Member.

I tried to change alias and generated new models but no luck.

### Steps to reproduce

- Create project with Models builder enabled
- Add custom properties to member in Umbraco
- Copy and paste upper snippet into View
- Adjust it to your code (models directory)
- See if models can map

### Expected result / actual result

Mmeber should be null and code inside if statement should not execute.

**Comment by davidkosir2** [comment]
Models now have constructors

**Comment by arknu** [comment]
> Models now have constructors

So what? The AsPublishedMember method should still return the proper model classes, as it did in v13. Can we please reopen this? It is still an issue in 16.3.
