### ISSUE TITLE
RTE Link to media with 'open in new window' option generates corrupt link

### ISSUE THREAD

**Issue by dutchbreeze** [umbraco/Umbraco-CMS#17836]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

14.3.1

### Bug summary

When adding a link in the rich text editor and selecting 'Opens the linked document in a new window or tab' generates a link that refers to 'Locallink:Guid'. When the option 'Opens...' is not used, the link is generated correctly.

### Steps to reproduce

In any given RTE, add a link to a media item and apply 'Opens the linked document in a new window or tab'. Then check the link in the frontend.

**Comment by iOvergaard** [comment]
Hello, thanks for the report. This is something that has been addressed in 15.0 with #17288. The fix has been merged back into the dev channel of V14 and will go out with 14.4.0, which does not yet have a set release date. Can you upgrade to the latest V15 (currently 15.1.1) and test it out?
