### ISSUE TITLE
Media Picker should not show deleted items

### ISSUE THREAD

**Issue by arknu** [umbraco/Umbraco-CMS#2886]
This is somewhat related to http://issues.umbraco.org/issue/U4-9616

I had a customer run into this problem: The media picker remembers the last folder used. However, if the folder is deleted and the media picker opened again, it still opens to the last folder - even though that folder is now deleted. You can still select items from the folder. In this case, the client was confused, as the folder (at a glance) was identical to a later uploaded folder.

In a broader sense, the media picker should not in any way (be it browsing or searching) show or allow selection of deleted media items.

### Reproduction

1. Create a folder and upload some images
2. Browse to the folder in a media picker and select a few. The media picker will remember the last-used folder.
3. Go the media section and delete the folder you created earlier
4. Create a new folder and upload the same images (plus a few others to tell them apart)
5. Go back and open the media picker again. Note that it still shows the now-deleted folder. You can select files from this folder without issues.

### Expected result
The media picker should go back to the root, since the previous item is no longer valid

Also, it should not be possible to find items via search

### Actual result
The deleted folder is still shown and items can be selected

**Comment by abjerner** [comment]
Congrats on being the first to open an issue on GitHub for Umbraco 🎉 

For the sake of the discussion, wouldn't showing an error - although not very helpful to the editor - be more correct? I would imagine falling back to the root folder would allow editors to select items that could break any custom code - eg. in the frontend - if an item of an wrong type is selected.

**Comment by arknu** [comment]
@abjerner What I meant was that it should just behave as if there was no stored previous folder. I.e. show the root folder, the user's start folder or whatever is configured for that particular media picker.

**Comment by abjerner** [comment]
@arknu ahh - I keep forgetting the difference between last used folder and start node. I think you're correct then ;)

#H5IS

**Comment by nul800sebastiaan** [comment]
Fixed with PR #2888 👍
