### ISSUE TITLE
Snapshot of the entire CMS

### ISSUE THREAD

**Issue by mridentity** [umbraco/Umbraco-CMS#2892]
I know I can backup the database and config files and there're also built-in versioning of CMS documents. Still, an all inclusive snapshot feature will just make everybody's life easier, starting with the developers. It will also make other features/bug fixes etc. happen quicker. Thanks!

How can you help?
-------------------------------

**Comment by nul800sebastiaan** [comment]
Hi @mridentity - in order for us to consider your feature request I think we need a lot more detail on what you're expecting, why exactly and how this should work.

I would therefore encourage you to start a discussion about what a possible feature like that should look like on the forum at https://our.umbraco.com/

If you choose the category "Contributing to Umbraco CMS" we'll follow along and comment where necessary.

**Comment by jaddie** [comment]
Just a heads up but this sounds kinda along the path that USync solves, have you looked at how this functions as it might help provide an example as a base for your suggestion :)

**Comment by mridentity** [comment]
That's cool. I can manage my revert needs using VM level snapshot. Just surprised to see this useful CMS feature isn't built in yet.
