### ISSUE TITLE
Settings (wrong place for doc types, templates and partial views etc.)

### ISSUE THREAD

**Issue by mridentity** [umbraco/Umbraco-CMS#2893]
Please consider putting these meta contents in the same section with other things found in the Developer section. Forcing frequent UI switches between sections is a bad UX. Besides, Settings could be where the users set or change their preferred navigational behavior, rather than a frequent navigation path itself. 

How can you help?
-------------------------------

**Comment by nul800sebastiaan** [comment]
Thanks @mridentity - we're working on making this much better in v8! I'll close this for now as it's on our list and we're well aware! 👍
