### ISSUE TITLE
Adding function to MemberService.Saved causes the function to be called twice.

### ISSUE THREAD

**Issue by DJOldskool** [umbraco/Umbraco-CMS#2904]
Also to make a change and save the member you have to set the property and save it the first time through and then set it again (no need to save) the second time through.

[https://stackoverflow.com/a/52099945/1948940]

**Comment by nul800sebastiaan** [comment]
Hi there @DJOldskool - I believe there is some ways to work around this, currently there is good reasons that eventhandlers still have to run through the event once more (I can't remember off the top of my head). 

If we were to change this behavior now, other things would start failing. 

Make sure to ask in [our friendly community at https://our.umbraco.com/](https://our.umbraco.com/) for the best way to work around it and make sure to show some code so people can help you better! 👍
