### ISSUE TITLE
Publish dates UX issues

### ISSUE THREAD

**Issue by chudders22** [umbraco/Umbraco-CMS#2905]
### Unpublish at
When creating a new content item with just an unpublish date, the default action of the "Save and publish" button becomes "Save and schedule". Which makes sense from a labeling point of view as a publishing rule has been attached.

However, in this circumstance, this seems slightly confusing to the user as the page isn't published with the "default" action, as per usual with content items. 

Personally, I feel that if creating an item and adding just an unpublish date, that by default the item should "Save and publish", and schedule the unpublish for the date set.

#### Reproduction
- Create a new content item
- Add an unpublish date
- Save and schedule
- At this point we have users leaving the page believing their job is done.
- Page is never published 

#### Desired
- Create a new content item
- Add an unpublish date
- Save and schedule publishes page and sets unpublish date
- Page is unpublished at unpublish date

#### Publish at
The "Save and schedule" button works as you would expect in this situation, because you wouldn't expect that item to be published until that date. 
However the notification in this situation feels slightly wrong: 

![image](https://user-images.githubusercontent.com/2007697/45024424-e0b9ec80-b030-11e8-8903-1b137581754d.png)

If a date is scheduled would this not be better to say something along the lines of "Content saved: 
 Changes have been saved and wil be published on 4 September 2018"

#### Unpublish at
If an unpublish date is scheduled it would be good if we could display "Content published: and visible on the website until 4 September 2018"

Experienced on Umbraco version 7.11.1

**Comment by hartvig** [comment]
Amazing feedback. Great ideas with big impact. Thank you!

**Comment by sussexrick** [comment]
We completely agree with @chudders22  here, and this change to the UI has so far prevented us from upgrading past Umbraco 7.7 because we felt it was too confusing for our users.

**Comment by kjac** [comment]
I'll have a look at this.

**Comment by kjac** [comment]
PR in #3507
