### ISSUE TITLE
Add .AsNText() to umbraco migration syntax

### ISSUE THREAD

**Issue by jontebackis4** [umbraco/Umbraco-CMS#2908]
This is a request that regards umbraco migrations which can be used to create custom database tables.

At the moment if you want to store long texts it is possible to create a column of type NText by using the following code:
```
var textType = SqlSyntax.GetSpecialDbType(SpecialDbTypes.NTEXT);
Create.Column("tourData").OnTable("umbracoUser").AsCustom(textType).Nullable();
```

However this is not that straight forward so instead a new type could be added in the [migrations syntax](https://github.com/umbraco/Umbraco-CMS/blob/1bb593d264a085f94a3ce3bd710392b350561430/src/Umbraco.Core/Persistence/Migrations/Syntax/ExpressionBuilder.cs#L142) so that you could use `AsNText()` to specify the column type.

**Comment by nul800sebastiaan** [comment]
Hi @jontebackis4 ! I am not sure if we have an AsNVarChar method instead? The problem with ntext is that it has been deprecated and I don't think we should encourage people to make ntext columns any more. Can you check if making an nvarchar field is easy enough?

Documentation about ntext deprecation: https://docs.microsoft.com/en-us/sql/t-sql/data-types/ntext-text-and-image-transact-sql?view=sql-server-2017

**Comment by jontebackis4** [comment]
Oh, I see. I didn't know about the ntext deprecation. 

As far as I can see the way to store texts is to use `AsString()` (or `AsAnsiString()`) which creates a column of type NVarChar. You can specify the length of the string by passing in a number, however the largest number you can pass is 4000. To store strings longer than 4000 characters you can normally use `nvarchar(max)` but I can't find a way to pass `max` into `AsString()`. I guess what I'm looking for is a way to use something like `AsString(max)` or `AsNvarChar(max)`.

**Comment by dawoe** [comment]
I think you need to use `AsCustom("nvarchar(MAX)") `for that

**Comment by jontebackis4** [comment]
Aha! I get it and it works, so then this issue is no issue. I just didn't understand how you could use `AsCustom()`.

Thank you very much!
