### ISSUE TITLE
7.2.0 Nightly - List view shows dimmed link for saved item

### ISSUE THREAD

**Issue by nul800sebastiaan** [umbraco/Umbraco-CMS#2910]
<p>If an item has previously been published and then been saved with some changes (only saved, not yet published). The item looks unpublished as it's dimmed.
For consistency, it should show the same green &quot;+&quot; overlay as in the content tree and not be dimmed.</p>
<p>Issue imported from old issue tracker: <a href="https://issues.umbraco.org/issue/U4-5534">U4-5534</a><p><strong>Note: This issue has attachments in the original issue</strong></p>

**Comment by readingdancer** [comment]
@abjerner & @rasmusfjord Your clients will hopefully be please to see this one has been fixed :)

**Comment by nul800sebastiaan** [comment]
Fixed in https://github.com/umbraco/Umbraco-CMS/pull/2947
