### ISSUE TITLE
Preview uses cached content

### ISSUE THREAD

**Issue by nul800sebastiaan** [umbraco/Umbraco-CMS#2911]
<p>If you preview a page in Umbraco, and the template it uses, has a Partial to display some of the properties pulled in using Html.CachedPartial...</p>
<p>eg:</p>
<p>@Html.CachedPartial(&quot;Person&quot;, Model, 8600, true, false)</p>
<p>Then the updated content the editor is trying to preview is not visibile until the cache expires.</p>
<p>Saving AND Publishing will break the cache, and then the editor can then preview the change, but it is too late at that point because they've published the page!!!</p>
<p>I'm wondering whether the HtmlHelperRenderExtensions CachedPartial extension could detect if it is executing in the context of preview and not return the cached version ?</p>
<p><a href="https://github.com/umbraco/Umbraco-CMS/blob/9e9c1ad0307fb0ceb49dbb6ea279e505a632ac44/src/Umbraco.Web/HtmlHelperRenderExtensions.cs">https://github.com/umbraco/Umbraco-CMS/blob/9e9c1ad0307fb0ceb49dbb6ea279e505a632ac44/src/Umbraco.Web/HtmlHelperRenderExtensions.cs</a></p>
<p>or if it's just wrong to use a Cached Partial to write out properties in a template in this context, it's sort of an anti-pattern, but I can see why the developer has done it here for performance (they are using uSiteBuilder) and pulling in content for the person as well as the bodyText property.</p>
<p>Anyway the Editor expects to see the content they have just changed and saved and not published, rather than any cache of the current live page.. which I think is the issue I am raising here, if that makes sense ?</p>
<p>Issue imported from old issue tracker: <a href="https://issues.umbraco.org/issue/U4-9022">U4-9022</a>

**Comment by kjac** [comment]
@nul800sebastiaan try as I might, I can't reproduce this.

I have tried:

1. A partial view without a model (based on `UmbracoTemplatePage`), that reads data directly from `Model.Content`.
2. A partial view with `Model.Content` passed as model.
3. A partial view with a `string` model (being a value read from `Model.Content`).

No matter what I do, the partial view rendered by `@Html.CachedPartial()` always render the latest saved content properties in preview mode (and the latest published ones out of preview mode).

**Comment by MrJackWilson** [comment]
I'm also experiencing this problem on version 7.15.3 in the cloud.

I have a page which pulls in child content of other nodes around the site and when you preview that page and then try to go to the live site as normal, all of the unpublished content that is under these other nodes appears on the live site.

**Comment by nul800sebastiaan** [comment]
@MrJackWilson 7.15+ has a new preview engine and I think what you're experiencing is being worked on soon: https://github.com/umbraco/Umbraco-CMS/issues/6629

I'll close this issue for the old preview engine for now since it seems like it can't be reproduced.
