### ISSUE TITLE
Media picker searches entire media archive

### ISSUE THREAD

**Issue by nul800sebastiaan** [umbraco/Umbraco-CMS#2916]
<p>Looks like the latest versions of Umbraco searches the entire media archive when a search is made from the media picker. See screenshot. Can this be changed in any way?</p>
<p>We have a website with almost 30K images. They have a good folder structure, but there's still 100's of media in every folder. Now they cannot find anything, because the search is done in everything, and not just the folder they navigated to.</p>
<p>What to do? The editors are lost in a task that used to be easy.</p>
<p>I have asked the same question on the forum hoping that someone knew of a setting somewhere, but with no luck.</p>
<p>Issue imported from old issue tracker: <a href="https://issues.umbraco.org/issue/U4-10612">U4-10612</a><p><strong>Note: This issue has attachments in the original issue</strong></p>

**Comment by KimHolzmann** [comment]
I have fixed the bug, 
but not implemented the sugested feature, for searching trough all folders.

My idea about that could bee, IF nothing found, a option links is shown too- 
Do you like to search in all folders ?

**Comment by KimHolzmann** [comment]
Agree - but is this not a two step task - 
one fix the error (Done )
two add a new feature (UX)
And the "extended" search has the startNodeId as the root, not just from mediafolder root.

I will look at this new search option today IF we can agree to this.

**Comment by KimHolzmann** [comment]
Just find out that the fix I provided, only fix, that we can't search folders over the startNodeId!
It's still search trough subfolders from the startNodeId.
Working on the UX search now.

**Comment by nul800sebastiaan** [comment]
Fixed in https://github.com/umbraco/Umbraco-CMS/pull/3061
