### ISSUE TITLE
User Experience for "subnodes"*

### ISSUE THREAD

**Issue by nul800sebastiaan** [umbraco/Umbraco-CMS#2923]
### _With Nested Content, The Grid and packages like Stacked Content, the concept of “subnodes” now exist in the back office. This presents a challenge as users will expect behavior from traditional nodes - such as publish/unpublish, audit trails, rollback, etc. to be present for “subnodes” as well._ 

# Why
The Umbraco back office touts itself as being Friendly, thus easy to use from a User Experience perspective. Heavily influenced by Steve Krug’s “Don’t make me think” and the quest for making every release simpler than the previous one, it means that special care and attention needs to go into new UX patterns, which is exactly what’s needed for “subnodes”.

Previously there’s been examples in the community of On/Off buttons in packages like Archetype and recently also as an extension to Nested Content. While the concept can be explained or taught to users, this doesn’t scale nor fulfills the quest for a “Don’t make me think approach”:
* What does On or Off mean? It’s not an approach nor a iconography used anywhere else in the Umbraco Back Office, at what point is an item “On” or “Off” (is it when the page is published? And when is something “On” or “Off” and when is something “Published”?)
* What about other tasks or information about “subnodes”. Scheduled Publishing, Rollbacks, Audit Trails, etc. While these aren’t current features supported, we need to think ahead as we introduce new UX Patterns in the core itself

# What
A UX Pattern for managing "subnodes" that can be applied to "subnodes" in general (such as Nested Content, Grid, Stacked Content, etc) and successfully can pass User Testing without any initial explanation. This means that the majority of the users should be able to discover and understand how to manage "subnodes".

The UX Pattern should be able to explain a state of a "subnode" (published, unpublished and scheduled publishing), 2-3 default tasks and also a way to present further information (such as audit trails, rollback and more).

Initially, we’re looking for mock-ups that can be used for testing. This could be screenshots alone and doesn’t have to be a working prototype.

# How
We’re looking for assistance in both creating the mock-up and would also love assistance for a great testing process.

# Remarks
* “Subnodes” is in quotes as it’s a working title and not intended to be the final name

**Comment by bjarnef** [comment]
Often these packages are using doctypes / "subnodes" as building blocks for its content, but maybe it doesn't need all the same stuff as traditional document types / nodes, e.g. does it need to have template and url the model of these "subnodes" will be of type `IPublishedContent` or does it need a completely different model for these "subnodes"?

In Nested Content and in the grid we often need some scheduled publishing, which we usually at the moment control by using a startdate and enddate datepicker on e.g. Nested Content items or Grid editors.

**Comment by tiffy74** [comment]
You know...

This has such potential for completely re-imagining the layout for editing in Umbraco into a really lovely smooth editing experience more akin to desktop based software rather than just an editing interface.

However it does have the potential to make it more complex or confusing for those that require simplicity or need the easiest possible set of tools in order to edit.

The conflict here - and I would be really interest in some views from people who do a lot of work on UX - is about how we can implement something that has the broadest appeal but doesn't necessarily sacrifice certain tools or forms of editing in favour of making it as easy to use as possible.

But really excited to see how this will develop.. I just hope it gets the attention it deserves :)

**Comment by nul800sebastiaan** [comment]
With the progress on the newly proposed Block Editor I'll close this one, please refer to: https://github.com/umbraco/rfcs/pull/12
