### ISSUE TITLE
Nested Content PropertyValueConverter is missing DefaultPropertyValueConverter attribute

### ISSUE THREAD

**Issue by ronaldbarendse** [umbraco/Umbraco-CMS#2925]
I've created this issue to surface and centrally discuss PRs #2918 and #2922.

Creating a custom `PropertyValueConverter` for the built-in `Umbraco.NestedContent` editor is not possible, because the built-in PVCs are not marked with a `DefaultPropertyValueConverter` attribute.

Reproduction
------------
Create a custom PVC for `Umbraco.NestedContent`: instead of overriding the default ones, an error is thrown indicating more than 1 PVC is registered.

### Specifics
This happens on all released versions of Umbraco 7.7+, when Nested Content was integrated. The exact exception is:

`InvalidOperationException: Type 'Umbraco.Web.PropertyEditors.ValueConverters.NestedContentManyValueConverter' cannot be an IPropertyValueConverter for property 'socialMedia' of content type 'home' because type 'TestProject.Web.Core.NestingContentlyManyValueConverter' has already been detected as a converter for that property, and only one converter can exist for a property.. This usually indicates that the content cache is corrupt; the content cache has been rebuilt in an attempt to self-fix the issue.`

**Comment by ronaldbarendse** [comment]
I've updated both PR #2918 and #2922 to fix an issue with the `JsonValueConverter` (as that converter automatically registers itself for all properties which store their value as JSON - and as both are now default converters, the same conflict happened as described in the issue).

Although PR #2922 changes public classes (by merging `NestedContentSingleValueConverter` and `NestedContentManyValueConverter` into a single `NestedContentValueConverter` class) and that should be marked as a breaking change, I think that it's justified and should be the real fix for this issue.

Having a single converter for a single property editor also makes more sense. And especially now we can override the default converter, it's way more convenient to do so. For example, if you'd like to filter out hidden/disabled nested content items (by adding a `umbracoNaviHide` checkbox or better yet, using https://github.com/nathanwoulfe/NestingContently), it's this simple:

```c#
public class IsVisibleNestedContentValueConverter : NestedContentValueConverter
{
    public override object ConvertDataToSource(PublishedPropertyType propertyType, object source, bool preview)
    {
        var obj = base.ConvertDataToSource(propertyType, source, preview);
        if (obj is IPublishedContent content && !content.IsVisible())
        {
            return null;
        }
        else if (obj is IEnumerable<IPublishedContent> contents)
        {
            return contents.Where(c => c.IsVisible());
        }

        return obj;
    }
}
```
I've tested this on a clean Umbraco install using the starter template: just add the `umbracoNaviHide` checkbox on the `feature` doctype and edit a product to hide a feature.

**Comment by ronaldbarendse** [comment]
@poornimanayar Any progress on this issue?

Because the current `NestedContentSingleValueConverter` and `NestedContentManyValueConverter` classes can't be inherited right now (because of this issue) and are dynamically registered, nobody _should_ have direct references to these. But strictly speaking: changing public classes is a breaking change, so PR #2922 could be merged into the next minor version as a 'breaking change'...

**Comment by ronaldbarendse** [comment]
I just found a work-around for this issue: manually remove the existing value converters using (in an `ApplicationStarting` event):

```c#
PropertyValueConvertersResolver.Current.RemoveType<NestedContentManyValueConverter>();
PropertyValueConvertersResolver.Current.RemoveType<NestedContentSingleValueConverter>();
```

So merging the converters should indeed be marked as a breaking change, as this code references the public classes. This breaking change is easily fixed by just removing these lines of code, as it won't be needed when the converter is marked as default...

Filtering hidden (`umbracoNaviHide = 0`) nested content could then be done using:
```c#
public class IsVisibleNestedContentManyValueConverter : NestedContentManyValueConverter
{
	public override object ConvertDataToSource(PublishedPropertyType propertyType, object source, bool preview)
	{
		if (base.ConvertDataToSource(propertyType, source, preview) is IEnumerable<IPublishedContent> nestedContents)
		{
			return nestedContents.Where(nc => nc.IsVisible());
		}

		return null;
	}
}

public class IsVisibleNestedContentSingleValueConverter : NestedContentSingleValueConverter
{
	public override object ConvertDataToSource(PublishedPropertyType propertyType, object source, bool preview)
	{
		if (base.ConvertDataToSource(propertyType, source, preview) is IPublishedContent nestedContent && nestedContent.IsVisible())
		{
			return nestedContent;
		}

		return null;
	}
}
```

**Comment by poornimanayar** [comment]
Hi @ronaldbarendse ,

Apologies for the very delayed reply. I am going to refer this to @nul800sebastiaan . We have had an internal chat and he thinks it needs further input from his side.

Regards,
Poornima

**Comment by ronaldbarendse** [comment]
@nul800sebastiaan Can you give your input on this issue, so the PR (perferrably #2922) can be merged?

**Comment by ronaldbarendse** [comment]
@nul800sebastiaan This issue still requires your input/review... I would argue merging PR #2922 for version 7.15.0, as it's a minor breaking change (2 public classes merged/renamed to 1), should suffice.

**Comment by ronaldbarendse** [comment]
This issue can be fixed for Umbraco 8 by merging PR https://github.com/umbraco/Umbraco-CMS/pull/7045. @poornimanayar can you take a look again? 😉

**Comment by poornimanayar** [comment]
PR for v8 in https://github.com/umbraco/Umbraco-CMS/pull/7045
