### ISSUE TITLE
ImageCropper treats crop as a resize if aspect ratio is same as source image

### ISSUE THREAD

**Issue by nul800sebastiaan** [umbraco/Umbraco-CMS#2928]
<p>I have discovered that the ImageCropper, in the backoffice, behaves like a resizer if the crop size is defined with the same aspect ratio as the original image.</p>
<p>Scenario:
I have three crops defined.</p>
<p id="first-200wx400h">first 200(w)x400(h)</p>
<p id="second-400wx400h">second 400(w)x400(h)</p>
<p id="third-400wx200h">third 400(w)x200(h)</p>
<p>If I view a Media image that was uploaded at 800x800, and move the focal point around, the first and last crop update their previews to reflect the new focal point--however, the 400x400 &quot;crop&quot; never changes, because it is actually shown as a scaled down resize of the original.  Since it contains the full image, scaled down, the focal point movement makes no difference.  This is not a crop; it is a resize.</p>
<p>I should be able to make a true ''crop'' of the original that happens to be the same aspect ratio.</p>
<p>Note in my example, that the &quot;half&quot; crop is a resize, not a crop.</p>
<p>In addition, when I click on the &quot;half&quot; &quot;crop&quot;, I cannot move the image within the cropper area unless I zoom in.  (see attached picture)</p>
<p>If I zoom in, I can move it, but I should not have to zoom in.  I'm trying to make a crop that is half the height and half the width of the original, which should give me plenty of image area to crop.</p>
<p>Issue imported from old issue tracker: <a href="https://issues.umbraco.org/issue/U4-11615">U4-11615</a><p><strong>Note: This issue has attachments in the original issue</strong></p>

**Comment by nul800sebastiaan** [comment]
I've marked as "Up for grabs" so that you or someone else coming along could create a pull request for it.

**Comment by soreng** [comment]
@nul800sebastiaan the way we use the focalpoint is that we "ensure the focalpoint is in view". By just resizing we get that behaviour.

Are you proposing that this should change, and when to focal point is set as A (below), the image should be "cropped" like B (below)?

A 
![image](https://user-images.githubusercontent.com/359492/45781430-382aa000-bc60-11e8-9654-ea50c5480b27.png)

B 
![image](https://user-images.githubusercontent.com/359492/45781456-47115280-bc60-11e8-8c3a-342d908a3d53.png)

**Comment by lcichanowicz** [comment]
@soreng, it seems to me, a crop should always be a crop, not a resize--at least until the content manager clicks on the crop and manipulates it.

If I upload an 800x800 image, and there is an existing 200x200 crop defined, I should be seeing a 200x200 crop of the center of the image for that pre-existing crop, because the focal point is centered by default.  Umbraco presently shows me a 200x200 resize, meaning the whole image area, not a crop.

**Comment by soreng** [comment]
So to recap: I see it as “show as much of the image, ensure to focalpoint is visible”, and you see it as “keep zoomlevel as close the 100% as possible and center on the focalpoint”?

**Comment by lcichanowicz** [comment]
I see it as: Umbraco calls it a cropper, not a resizer.  The cropper preview should provide an accurate thumbnail of what a true crop of the defined size would look like.

**Comment by soreng** [comment]
Well, to know if it is an error, we must first know what the intended behaviour is.

And yes, I see it as “show as much as you can, but make sure the focalpoint is in view”. 

If and image is 500x400 and the crop is 400x400, and the focalpoint is deadcenter, then 50px will be cut from left and right. If the crop is 200x200, then the same will happen, but the remaing is scaled to 50%. If the crop is 250x200, the full image is just resized.

We actually never use predefined crops, but rather “read” the crop just before loading the images in the frontend. This way we can scale images for different screen sizes and layouts.

**Comment by kjac** [comment]
I think we should be very careful about changing the current behavior of the image cropper. The way it's described here is the way it's always worked, and there are a LOT of sites out there depending on and expecting this behavior. I do agree that the name "crop" is probably not entirely correct - "resize-to-fit" might be more accurate (but not terribly meaningful)..

I tend to think of them as "sizes" more than "crops". As @soreng points out it's mostly about scaling images to different needs. With the nice addition that the editors can customize the crops, turning them from "just resizing" to actual crops.

Just my five cents 😄

**Comment by nul800sebastiaan** [comment]
Reflecting on this again, I have to agree. The current behavior is what it is and changing it would have many implications for backwards compatibility. I'll close this one.
