### ISSUE TITLE
Grid Editor Internet Explorer Scroll Issue

### ISSUE THREAD

**Issue by nul800sebastiaan** [umbraco/Umbraco-CMS#2929]
**What did you do?** 
Our clients are reporting, and we are reproducing, an error in the `umbraco.css` wherein editor panels docked to the right of the window consisting of `.umb-panel-body > .umb-form-settings` do not produce automatic scroll bars.  This is affecting many of our grid editors that include nested content areas, link types, etc. Keyboard input is about the only way we could discern to navigate these areas, without putting in a fixed width or min-width for the `.umb-form-settings` container elements.

**What did you expect to happen?** 
As in Firefox and Chrome, these areas should produce scroll bars allowing editors in other browsers to make changes and add content.

**What actually happened?** 
No scroll bars appeared, editors could not make changes.</p>

Issue imported from old issue tracker: [U4-11616](https://issues.umbraco.org/issue/U4-11616)

**Comment by trt** [comment]
I'm not able to reproduce this issue. If anyone is experiencing this behavior please add steps to reproduce, browser versions etc.

**Comment by nul800sebastiaan** [comment]
Closing as I also can't reproduce.
