### ISSUE TITLE
Make IPublishedContent expose ExpireDate

### ISSUE THREAD

**Issue by nul800sebastiaan** [umbraco/Umbraco-CMS#2930]
<p>As of current the scheduled ExpireDate (Unpublish date) is only exposed via IContent, meaning in order to display the ExpireDate on a page either the database needs to be hit on each request (ie using the content service to get an IContent to get the page's ExpireDate) or add a field to the doc type mirroring the ExpireDate value.</p>
<p>Neither of these solutions I believe are an acceptable alternative to having IPublishedContent expose ExpireDate.</p>
<p>There are valid reasons for needing to telegraph when a page will no longer be available, for example if a product is only available for a limited amount of time, transient pages, etc.</p>
<p>Related: <a href="https://our.umbraco.com/forum/umbraco-7/using-umbraco-7/75075-displaying-unpublish-at-date">https://our.umbraco.com/forum/umbraco-7/using-umbraco-7/75075-displaying-unpublish-at-date</a></p>
<p>Issue imported from old issue tracker: <a href="https://issues.umbraco.org/issue/U4-11612">U4-11612</a>

**Comment by AlphaDelta** [comment]
I believe most of the work necessary would take place in [Umbraco.Web.PublishedCache.XmlPublishedCache](https://github.com/umbraco/Umbraco-CMS/tree/1bb593d264a085f94a3ce3bd710392b350561430/src/Umbraco.Web/PublishedCache/XmlPublishedCache).

The method [XmlPublishedContent.InitializeNode](https://github.com/umbraco/Umbraco-CMS/blob/1bb593d264a085f94a3ce3bd710392b350561430/src/Umbraco.Web/PublishedCache/XmlPublishedCache/XmlPublishedContent.cs#L329-L335) appears to be used to deserialize pages from the cache.

Though I may be wrong, it's only a naive assessment based on a bit of dnspy debugging.

**Comment by nul800sebastiaan** [comment]
Closing the issue for the reasons mentioned on the PR here: https://github.com/umbraco/Umbraco-CMS/pull/3116#issuecomment-426689974
