### ISSUE TITLE
Backoffice image crop previews need visual indicator of "override"

### ISSUE THREAD

**Issue by lcichanowicz** [umbraco/Umbraco-CMS#2932]
When a content manager moves the focalpoint on the main image, they expect to see the crop thumbnails update to reflect the change when they release the focalpoint.  This is not always the behavior, by design.  If a content manager clicks a crop, and manipulates it directly, it is then "disconnected" from the main image's focalpoint.  This is fine except that on the main image page, showing all the crops, there is no way visually to tell which have been "overridden".  They should have a visual indicator: background, border, icon, or something.

**Comment by kjac** [comment]
V8 PR in #5626
