### ISSUE TITLE
Quick access to last accessed folder in media picker

### ISSUE THREAD

**Issue by ksolberg** [umbraco/Umbraco-CMS#2938]
I recently visited a customer and they had a pretty well organized media library in Umbraco. Some of the content pages listed numerous hand-picked images in a grid and more often than not, these images were located some levels deep in the media library and in the same folder. 

It would have saved the editors time if the editor had a way to quickly navigate to the last accessed media folder(s) when picking an image. This is a well known pattern from other systems.

**Comment by nul800sebastiaan** [comment]
@ksolberg Which version of Umbraco are you on? In 7.12 when you select a media item, then select another one, we drop you back into the previous folder you were in.

Also, if you have examples of how this works in other systems, a screenshot would help.

I'll close this one for now as I think the feature as described is already available! 👍

**Comment by ksolberg** [comment]
@nul800sebastiaan This was in 7.6.6. I should have tested in latest before requesting the feature. Good thing it's there!
