### ISSUE TITLE
Improve Automatic Media item naming based on the uploaded file name when adding media with drag/drop

### ISSUE THREAD

**Issue by nul800sebastiaan** [umbraco/Umbraco-CMS#2943]
<p>When dragging and dropping files for upload on the created media items are given the name of the file. It would be much nicer if a bit of simple sanitisation was applied to &quot;normalise&quot; the name eg. For the name you would:</p>
<ul>
<li>Strip the file extension</li>
<li>Replace underscores with spaces</li>
<li>Initial capitalise the name</li>
</ul>
<p>So if you uploaded a file called &quot;my_amazing_kitten.jpg&quot; it would be named &quot;My Amazing Kitten&quot;. If you uploaded a file called &quot;Some_AMAZING_dinosaurs-1.PDF&quot; it would be named &quot;Some Amazing Dinosaurs-1&quot; etc.</p>
<p><mark>Implementation Requirements</mark></p>
<p>Make the media item name &quot;nice&quot; since file names could be pretty ugly, we have
string extensions to do much of this but we'll need:</p>
<ul>
<li>Pascalcase the name (use string extensions)</li>
<li>strip the file extension</li>
<li>underscores to spaces</li>
<li>probably remove 'ugly' characters - let's discuss</li>
</ul>
<p>All of this logic should exist in a string extensions method and be unit tested</p>
<p>There's notes in the Core code here: 726bef1edf2ee36b8cdb560fa61548671a793f69</p>
<p>Issue imported from old issue tracker: <a href="https://issues.umbraco.org/issue/U4-5572">U4-5572</a>

**Comment by bsowa** [comment]
Hi @nul800sebastiaan ,

This is a nice feature, but unfortunately it is causing inconsistency in the existing builds. Imagine people already have some naming conventions in place and by introducing this feature you are breaking their naming conventions. Wouldn't it be better to make this available as an option in config file?

**Comment by nul800sebastiaan** [comment]
@bsowa If you want it to behave like it did before, you can drop in a small eventhandler like this, then you can customize the media name to your heart's content: https://gist.github.com/nul800sebastiaan/b9656341c19d254e68aabd3f0692b394

**Comment by bsowa** [comment]
@nul800sebastiaan thank you. Works as before 👍

**Comment by bsowa** [comment]
@nul800sebastiaan actually there is another issue with this. Upload works fine, but when you sort the media folder content to which the file has been uploaded, then the file name automagically changes to something like: 
banner-belize-mob.jpg", "crops": []}

**Comment by bsowa** [comment]
OK, I have found the solution for anyone that can came across similar problem.
Please replace the SetMediaNameToFilename method (from https://gist.github.com/nul800sebastiaan/b9656341c19d254e68aabd3f0692b394) with the following one:

```
private void SetMediaNameToFilename(IMediaService sender, SaveEventArgs<IMedia> e)
{
	foreach (var media in e.SavedEntities)
	{
		if(media.HasProperty("umbracoFile"))
		{
			string fileName;
			var path = media.GetValue<string>("umbracoFile");

			// Make sure it's not empty
			if (string.IsNullOrWhiteSpace(path))
			{
				return;
			}

			// This might happen after changing the data type of umbracoFile from 
			// Image Cropper back to Upload
			if (path.Contains("{"))
			{
				dynamic cropper = Json.Decode(path);
				string src = cropper.Src;
				if (!string.IsNullOrWhiteSpace(src))
				{
					path = src;
				}
				else
				{
					return;
				}
			}

			fileName = path.Substring(path.LastIndexOf("/", StringComparison.Ordinal) + 1);
			media.Name = fileName;
		}               
	}
}
```

**Comment by genckastrati** [comment]
Thank you @bsowa for the solution. We do rely on the file name nomenclature and this feature isn't helping :) glad there is a solution

**Comment by sschurig** [comment]
It works, but either you have to add two more Namespaces as Usings or you have to write `Umbraco.Core.Events.SaveEventArgs<Umbraco.Core.Models.IMedia> e` in the method's parameters.

And you have to add `using System.Web.Helpers` for `Json.Decode(path);` in order to work.

**Comment by thomashdk** [comment]
I know this is old.. :D
But why can't the name not stay as the filname uploaded? :)
ex. **borgmester Jens Hansen-17.jpg** -> **Borgmester Jens Hansen 17** ---> **instead of borgmester Jens Hansen-17**

This is in UMB13
