### ISSUE TITLE
Button don't display loading indicator in 7.12.2

### ISSUE THREAD

**Issue by ssougnez** [umbraco/Umbraco-CMS#2950]
Buttons don't display the loading indicator anymore in 7.12.2.

Reproduction
------------

Create some document type, add some property to them, buttons won't display the loading indicator while clicked giving the impression that nothing is happening and motivates the user to click more than once.

### Specifics

* Impacted version: Umbraco 7.12.2
* The bug was not previous in 7.11.4. I didn't test it with 7.12.0 nor 7.12.1.

### Steps to reproduce

* Just click on a button that is supposed to display the loading indicator.

### Expected result

* The loading indicator should be visible during the AJAX call.

### Actual result

* The loading indicator does not appear.

**Comment by nul800sebastiaan** [comment]
Hey @ssougnez - I think something went wrong with your upgrade, for me all the animations seem to work just fine on 7.12.2. 

I'll close this for now, let me know if I'm missing anything!

![2950](https://user-images.githubusercontent.com/304656/45302002-76aeb500-b512-11e8-8958-8c958b09c340.gif)
