### ISSUE TITLE
Don't use ng-show on the preview iframe

### ISSUE THREAD

**Issue by mattbrailsford** [umbraco/Umbraco-CMS#2952]
Currently the preview iframe shows a preloader whilst the preview page is loading which uses ngShow on the iframe. The problem here though is that a website may have js code that requires the page to be visible in order to do things like measuring elements (in my scenario I have a leaflet map that needs to calculate a zoom to bounds). When the ngShow's visibility is then set to display, the final page render is incorrect because the correct measurements were not calculated.

Reproduction
------------

Create a page that has a leaflet map on it that zooms to a specific boundary on load. Then preview the page and see that the zoom to bounds can't be calculated because the iframes display is set to hidden.

### Bug summary

ngShow hides the iframe by using display none, this prevents any JS from being able to calculate anything based on a DOM element. Maybe keep the iframe visible and instead, display a preloader overlay over the top with a white background colour and just remove that once the iframe is loaded.

**Comment by nul800sebastiaan** [comment]
Fixed in https://github.com/umbraco/Umbraco-CMS/pull/3172
