### ISSUE TITLE
Umbraco Forms 7.0.3 - FieldType.DataConsent breaking calendar field values

### ISSUE THREAD

**Issue by mcullen77** [umbraco/Umbraco-CMS#2955]
We recently installed Umbraco Forms 7.0.3 on one of our client sites, and the client reported back issues with the following
 
•	The FieldType.DataConsent does not perform any client side validation – we would expect this not to submit the form in the case where the user has selected to not allow the storage of their data.
•	As a result of this - when the FieldType.DataConsent server side validation causes the form to post back it is breaking preselected calendar field values. 

The steps to replicate are as follows
o	Create a simple form
o	Add a field with "Date" field type
o	Leave the data consent field type in the form and save the form
o	Add the form to some page
o	Preview the page
o	Populate the date field with a value
o	Pick "No" in the data consent field
o	Submit the form which should trigger a post back
o	Once the page reloads, you can now see an incorrect date being shown in the date field
This seems to be due to a discrepancy in how the Date picker expects the format of the string to be on postback. The date picker wants the date to be in “dd MMMM yyyy” format, the date is corrupted otherwise. There is nothing in the FieldType.DatePicker.cshtml to accommodate this.

I have escalated this to umbraco support who advised me to post here.

Their reply is below:

_Kristian Guld (Umbraco) 
Aug 23, 16:05 CEST 
Hi Mark,

Thanks for getting in touch, and thanks a lot for reporting the issue! 

I've replicated the issue on the exact same version of Forms and Umbraco 7.12.1, and I'm very sure that you have the correct explanation for it, or so, at least, it looks.  

You're more than welcome to report the forms issue to our developers here: http://issues.umbraco.org/issues/CON 

Thanks again for letting us know, and please let me know if you have further questions._

Kind regards
- Kristian

Thanks again for letting us know, and please let me know if you have further questions.

Thanks for looking at this issue, please let me know if any further clarification is required

**Comment by dawoe** [comment]
Hi @mcullen77 

Best is to report Umbraco Forms issues on their issue tracker : https://github.com/umbraco/Umbraco.Forms.Issues/issues

This is the issue tracker for Umbraco CMS

So I will close this one. It's best you create it again so you get notified when updates occurs. If I recreate it you won't get notified

Dave [Community Pull Request team](https://umbraco.com/blog/introducing-the-new-cpr-team/)
