### ISSUE TITLE
Notifications banner is inside an anchor tag

### ISSUE THREAD

**Issue by poornimanayar** [umbraco/Umbraco-CMS#2964]
The notifications in the backoffice is always rendered inside an anchor tag. The text has a hover state which underlines it.

**Comment by poornimanayar** [comment]
I have created a PR https://github.com/umbraco/Umbraco-CMS/pull/2965

**Comment by readingdancer** [comment]
Hi @poornimanayar The problem with your pull request is you have removed the ability for those notifications to be clickable. Perhaps it would be better to make this dynamic based on whether or not the notification.url exists?

**Comment by nul800sebastiaan** [comment]
Fixed in PR #2965
