### ISSUE TITLE
Allow Compositions to be Composed of Compositions (i.e., Pseudo-Inheritance)

### ISSUE THREAD

**Issue by AllanKirk** [umbraco/Umbraco-CMS#2966]
Copy of feature request from old system:
https://issues.umbraco.org/issue/U4-7596

Stephan said that this is allowed in code already, but blocked in UI.

**Comment by tcmorris** [comment]
Can confirm it works as I've tricked uSync into doing it for me before.

**Comment by nul800sebastiaan** [comment]
Hi there! While we do enjoy the idea and eventually it would be good to have, it is a major engineering effort to make it work in a safe way. The original issue already mentions the potential of making circular references etc. 

At HQ we currently don't have the time to work on it, it would be great if community would but I just want to warn that it is a large effort that needs careful building and testing.

I'm going to close it for now, but I'll put the `idea` label on it to remind us that we do want to work on this functionality one day when we get a chance.
