### ISSUE TITLE
Auth0 for membership "front-end" login

### ISSUE THREAD

**Issue by yarin12** [umbraco/Umbraco-CMS#2971]
Hi, 
I am trying to integrate Umbraco Cloud member login with Auth0. In addition, keep the back-office users to login via umbraco cloud. 
I was following this installation:
https://github.com/Shazwazza/UmbracoIdentity/wiki#installation
This worked fine until I was not able to deploy local changes to Umbraco Cloud environment. 
I wonder if anyone had similar issues or tried to integrate umbraco Cloud installation with third-part authentication providers?
Many thanks.

**Comment by nul800sebastiaan** [comment]
Hey there @yarin12 - make sure to ask questions about how to use Umbraco and our products on the forum. This issue tracker is available to describe bugs and feature requests! 👍
