### ISSUE TITLE
Site down

### ISSUE THREAD

**Issue by tranphuongyd** [umbraco/Umbraco-CMS#2977]
Hi everyone,

Our production site just have issue yesterday. It's down, all requests to this site will get time out. So we 
 was restart the application, then works fine now. But we need to know the reason and try to resolve it.
I just have check the logs at that moment and attached here, please see the image below.

Could you please help us check this issue.
Thanks,

![umbracodown](https://user-images.githubusercontent.com/7795756/45461308-95889380-b72c-11e8-9c00-cac3927ced5f.png)

**Comment by nul800sebastiaan** [comment]
Hey there @tranphuongyd  - make sure to ask questions about Umbraco and our other products on the forum at https://our.umbraco.com. This issue tracker is available to describe bugs and feature requests! 👍

If you have a support contract then please go to https://umbraco.com and log in to your account to find the support section in your profile.
