### ISSUE TITLE
Special Property Type aliases for routing

### ISSUE THREAD

**Issue by NikolayYeryomenko** [umbraco/Umbraco-CMS#2978]
From the list of Document Type properties: **umbracoRedirect**, **umbracoInternalRedirectId**,
**umbracoUrlName**, **umbracoUrlAlias** only **umbracoUrlName** works according to specification.

**umbracoUrlAlias** - only first url works, must be list of comma separated urls.

**umbracoRedirect**, **umbracoInternalRedirectId** does not work with content picker data type nor number id.

Umbraco 7.11.1

**Comment by nul800sebastiaan** [comment]
Hey there @NikolayYeryomenko  - make sure to ask questions about Umbraco and our other products on the forum at https://our.umbraco.com. This issue tracker is available to describe bugs and feature requests! 👍
