### ISSUE TITLE
Umbraco forms conditions not working

### ISSUE THREAD

**Issue by tashadecanha** [umbraco/Umbraco-CMS#2979]
Reproduction
------------

### Bug summary
When adding conditions to a field in umbraco forms the field will be hidden, but never shows when triggerd.

### Specifics
I just pulled the latest Umbraco version 7.12.2 with Umbraco Forms: "7.0.4" to see if the bug exists (yes it does)
Clean install - I made no changes to the code at all
Umbraco version 7.12.2
Umbraco Forms 7.0.4

### Steps to reproduce
1. In the Umbraco contact form I added a new property "Do you have a phone?" with single choice answers "yes" and "no".
2. In the existing phone numer property I enabled the conditons and added the following:
![2018-09-13 13_06_08-forms - localhost](https://user-images.githubusercontent.com/4497562/45484883-fa0c1880-b755-11e8-8985-9859703f49d9.png)

3. Submit and save
4. Result: 
![image](https://user-images.githubusercontent.com/4497562/45484920-1314c980-b756-11e8-8c6b-8ea2b988c845.png)
5. In the front-end:
![image](https://user-images.githubusercontent.com/4497562/45484975-3ccdf080-b756-11e8-8d79-033c93c69c19.png)
6. Phonenumber is hidden as expected
7. Check yes to the querstion "Do you have a phone?"
8. Phone number texbox does not show up
![image](https://user-images.githubusercontent.com/4497562/45484993-53744780-b756-11e8-8f3c-c80cb2f07675.png)

### Expected result
I expected the textbox to be displayed when I checked yes to the question of the condition.

### Actual result
The phonenumber texbox does not show up when I checked yes to the condition of the question

**Comment by nul800sebastiaan** [comment]
Hey there @tashadecanha - can you please [open this issue in the Forms issue tracker instead](https://github.com/umbraco/Forms.Issues/), this one is only for the CMS! 👍
