### ISSUE TITLE
Load specific locales for moment.js

### ISSUE THREAD

**Issue by bjarnef** [umbraco/Umbraco-CMS#2983]
At the moment in Umbraco backoffice it only loads the locale for moments.js, which match the current user backoffice language.
However sometimes you might use moment.js e.g. to format a date to a specific locale independently of the user language.

e.g. you might have a backoffice user which use Danish as language, but a custom dashboard only in English, it might be from a feed or similar, so you might prefer also to format dates shown in this feed (e.g. blogposts) in English date format.

without loading the other locales, then e.g. the following has no effect and fallback to English.

```
moment().locale("da").format("LL")
```

**Comment by steroberts89** [comment]
Just adding this for reference,This was introduced in PR #2507

**Comment by bjarnef** [comment]
@steroberts89 the PR you mention, changed the logic, so it only load the moment.js locale matching the language of the backoffice user. So that means at the moment I can't e.g. format a date in a dashboard in another locale format, than the current backoffice user language. I could use `assetsService` to load to the specific locale from the /Umbraco/lib/moment folder, but I think it would be better to have a function available for this since the logic for this already is present in core.

**Comment by nul800sebastiaan** [comment]
What's the conclusion between you two? We don't want to load all locales because they're causing waste but this PR loads all locales again? Or.. not?

**Comment by bjarnef** [comment]
@nul800sebastiaan by default it still only load the culture of the specific backoffice user :)
But the PR https://github.com/umbraco/Umbraco-CMS/pull/2984 gives the opportunity to load a specific culture and be able to format dates in that culture.

**Comment by bjarnef** [comment]
As an alternative can we add the path to moment.js locales to `Umbraco.Sys.ServerVariables` to avoid hardcoding the path if you need to load a specific locale via assetsService?
https://github.com/umbraco/Umbraco-CMS/blob/1bb593d264a085f94a3ce3bd710392b350561430/src/Umbraco.Web.UI.Client/src/common/services/user.service.js#L287

E.g. like `umbracoPath` https://github.com/umbraco/Umbraco-CMS/blob/2669a51fe1f4e70f602767e338b06e1efa78e123/src/Umbraco.Web.UI.Client/src/views/common/drawers/help/help.controller.js#L104

**Comment by nul800sebastiaan** [comment]
Fixed in #2984
