### ISSUE TITLE
Content Template throws error when saving multiple times

### ISSUE THREAD

**Issue by JeroenRoos** [umbraco/Umbraco-CMS#2985]
Saving mutliple times while adding a content template throws the following error:

![Error](https://downloads.intercomcdn.com/i/o/76337987/32ebf8d0c897e141b7c42d99/image.png)

This doesn't happen during the first save, but only at the second or third. I first encountered this problem in an Umbraco Cloud environment. The same issue also appears in all our other Cloud projects and also locally. 

We also found a workaround: 
It is possible to add and edit content templates when you refresh the page just after saving. You have to do this each time you edit something in the template. Because it's not possible to save multiple times in a row.

### Steps to reproduce
The step needed for reproduction are:

- Create a new Content Template

- Save the template once, to this point everything is going fine

- Save again once or twice and you will see the error

You don't have to edit the content template before saving again, it will give the same error if you do.

### Specifics

- Encountered first in a Umbraco Cloud environment, but also appears local

- Umbraco 7.11.1 

- Deploy 2.0.14

**Comment by nul800sebastiaan** [comment]
Looks.. red! 

I've marked as "Up for grabs" so that you or someone else coming along could create a pull request for it.

**Comment by ismailmayat** [comment]
I am going to tackle this today as part of hackathon in krakow.

**Comment by ismailmayat** [comment]
So with umbraco 7.13.0 running locally we cannot re create we also tried it on cloud with 7.8.3, we created new template and saved. Then saved again a couple of times all works fine?

**Comment by nul800sebastiaan** [comment]
@ismailmayat It's a content template (aka blueprint), not a normal template. This caught me out when I first saw this issue, maybe that's your problem too?

**Comment by ismailmayat** [comment]
On the initial create you have a model that is compatible with ContentController.PostSaveBlueprint after save after initial create you have model that is compatible however on subsequent save the model is no longer compatible and hence you get a page not found.  

I did some experimenting and in postsave I copied what initial create does see commit https://github.com/ismailmayat/Umbraco-CMS/commit/500c673240c957a39391fe08dda5bd62a9bf45cf that fixes the problem but only for existing items not newly created items.

**Comment by Nicholas-Westby** [comment]
Was about to recreate this issue too (I am getting this on 7.12.4 on Umbraco Cloud). Since I'm here, I'll just note the old ticket for this issue: https://issues.umbraco.org/issue/U4-10508

Awesome to see that it appears this will be fixed in 7.13.0.
