### ISSUE TITLE
A way to dynamically set tag groups

### ISSUE THREAD

**Issue by arknu** [umbraco/Umbraco-CMS#2988]
For a multilingual site I'm working on, I had the need to separate tags by language so that Danish tags don't show up in English, for instance. This should be easy to do with tag groups, but currently they are hardcoded as prevalues for the Tags property editor.

Now, thanks to EditorModelEventManager.SendingContentModel, I can easily change the tag group being used by the editor in the backoffice dynamically depending on the parent page. No problems there.

But - that won't help when saving the tags. Here, there seems to be no way to easily modify the group being used. You can't do it in ContentService.Saving because everything to do with tags is marked as internal.

So, I ended up doing something really nasty by using reflection to poke around and make the necessary changes. This is obviously a nasty hack with potential for future breakage, so I'd love to see an official way to do this. Either by opening up the tag-related properties or by adding an event for setting the tag group.

It would be cool if you only had to subscribe to one event to set the tag group, but two would work as well.

I'd like to work on a PR for this, if you can give some pointers on the preferred way to do this.

**Comment by nul800sebastiaan** [comment]
I think it's fine to open up some of the tags classes needed if you want to take a stab at it?

**Comment by arknu** [comment]
@nul800sebastiaan Great 😃 I'll have a look then later this week hopefully.

**Comment by arknu** [comment]
Ì have created a PR: https://github.com/umbraco/Umbraco-CMS/pull/3074

Sorry I didn't get to it last week.

**Comment by nul800sebastiaan** [comment]
Fixed in PR https://github.com/umbraco/Umbraco-CMS/pull/3074

**Comment by dawoe** [comment]
@nul800sebastiaan the PR is merged. Shouldn't this be closed then ?
