### ISSUE TITLE
RelatedLinks2 validation in Nested content

### ISSUE THREAD

**Issue by zaplvlad** [umbraco/Umbraco-CMS#2989]
User is able to save Nested content item without specifying required RelatedLinks2 property.

Reproduction
------------

### Steps to reproduce

* Create a doctype which will be used in Nested content data type. Doctype contains required RelatedLinks2 property.
![image](https://user-images.githubusercontent.com/43339104/45619246-440c3b80-ba81-11e8-84fc-d2c992e5ec4a.png)
* Create Nested content data type and use it as property in any other doctype.
![image](https://user-images.githubusercontent.com/43339104/45619290-6bfb9f00-ba81-11e8-9ecb-6fbb022ec7bf.png)
* Try to add item without filling any data in RelatedLinks2 property.
* Press "Save an publish" button

### Expected result

* Link is required, so validation message should appears.

### Actual result

* Document is saved and published with empty link.
![image](https://user-images.githubusercontent.com/43339104/45619359-ae24e080-ba81-11e8-8906-1ef4a6d70cad.png)

**Comment by nul800sebastiaan** [comment]
I can reproduce in some cases, but sometimes I am able to make it trigger the validation, very strange.

![image](https://user-images.githubusercontent.com/304656/45670094-365ac280-bb22-11e8-9386-de7b3f60d388.png)

That said, in this example it was empty for item 1, 2, 3 AND 5 so it should've validated all of those.

**Comment by zaplvlad** [comment]
You will see validation message if item is collapsed (so RelatedLinks2 editor is not rendered at all)

To reproduce it try to:
1) Create document.
2) Add few items and do not specify link
3) Save and publish document (you will not see validation messages)
4) Reload page (so all created items will be collapsed)
5) Save and publish document again (validation messages will appears)

**Comment by nul800sebastiaan** [comment]
Fixed in: https://github.com/umbraco/Umbraco-CMS/pull/3578
