### ISSUE TITLE
Moving content assigns default user (user-id 0) to the history audit. 

### ISSUE THREAD

**Issue by garpunkal** [umbraco/Umbraco-CMS#2990]
Moving content within the content tree assigns the userId of 0 to the history audit. 

### Specifics
What version of Umbraco are you using (down to the very last digit!):
Umbraco version 7.11.1

What browser and version you are using: 
69.0.3497.92 (Official Build) (64-bit)

Please mention if you've checked it in other browsers as well: 
Firefox 62.0 (64-bit)

### Steps to reproduce:

- Open the content section.
- Move a content item from one parent to a different parent. 
- click on the content item.
- click on the info tab
- the History, will show the default user (user=id 0). 

### Expected result

The correct user would have been registered as the owner of that action. 

### Actual result

The default user has been registered as the owner of that action.

**Comment by agrath** [comment]
Similar to https://issues.umbraco.org/issue/U4-10898 and https://issues.umbraco.org/issue/U4-9309 so these issues and PRs could provide context on how to fix this problem quickly

**Comment by nul800sebastiaan** [comment]
Yep seems like it's probably the same or a similar issue as when copying.

I've marked as "Up for grabs" so that you or someone else coming along could create a pull request for it.

**Comment by nul800sebastiaan** [comment]
Fixed in https://github.com/umbraco/Umbraco-CMS/pull/3150
