### ISSUE TITLE
Login fails for users if password has been updated by an admin

### ISSUE THREAD

**Issue by KamalTeta** [umbraco/Umbraco-CMS#2998]
I'm experiencing an issue with Umbraco 7.10.4, where users can't log in if their passwords have been reset by another user. 

I've been able to replicate this issue, by using an admin account to change the password of another user, whereafter they aren't able to log in. 

Edit: I think it's worth mentioning, that when the users can't log in, they're getting a 400 error

Hope you can help
Sincerely
Kamal Teta

**Comment by nul800sebastiaan** [comment]
That is not something that most people experience and I can not reproduce this problem. To make sure: you've told the other user the new password, right? 😉

Anyway, I would recommend you ask about this on the forum to see if the community can help you out, this is working in both 7.10.4 and the latest version, so I'm not sure what's going on in your website exactly.

**Comment by dawoe** [comment]
I saw a similar report earlier on the forum : https://our.umbraco.com/forum/using-umbraco-and-getting-started/91827-the-change-password-function-in-umbraco-admin-generates-invalid-password-hashes

**Comment by KamalTeta** [comment]
@nul800sebastiaan 
Yeah when I recreated it I confirmed it by using multiple user accounts. 😃 

@dawoe 
Thank you! I will check that out 😃

**Comment by nul800sebastiaan** [comment]
Okay @dawoe but it looks like people are switching password algorithms, which will lead to problems.

Please provide clear steps to reproduce before reopening an issue, we can't work on something that can't be reproduced! 👍

**Comment by mkyukov** [comment]
I'm experiencing the same issue. I've had that happen on a few projects so far. 

You can see a few more people having the same issue in this thread (Created on Apr 29, 2014), so I believe this is still an issue. May be hard to reproduce, but it is there.

**Comment by krusoleo** [comment]
I think it is this issue:
https://github.com/umbraco/Umbraco-CMS/issues/3015
