### ISSUE TITLE
7.11.1 Navigation of restricted media content with common ancestor

### ISSUE THREAD

**Issue by Icarium666** [umbraco/Umbraco-CMS#2999]
If we restrict users to two media nodes with common ancestor they are unable to navigate between them when using MediaPicker editors with start nodes set as ancestor, and media node.

### Steps to reproduce
- Create media tree with following structure:
```
- Folder
-- SubFolder1
-- SubFolder2
-- (other media)
```

- Create two user groups (permissions like the default Editor) with _SubFolder1_ and _SubFolder2_ selected as media roots, and assign both of them to the same user.
- Create Document Type with two MediaPicker editors with start nodes set as _Folder_ (_editor1_), and _SubFolder2_ (_editor2_).
- Create Content of our Document Type.

Now we can observe following scenario:
1. Log in to backoffice
2. Select media using _editor1_ - we are presented with MediaPicker showing _SubFolder1_ and _SubFolder2_.
3. Select media using _editor2_ - we are presented with content of _SubFolder2_.
4. Select media using _editor1_ - we are presented with content of _SubFolder2_.

After step 3 we are stuck in _SubFolder2_ for any MediaPicker that has its start node set to _Folder_ with no ability to navigate to _SubFolder1_ unless we log out and in again.

### Issue avoidance
Problem can be sidestepped by moving one of the restricted nodes out of common ancestor, hence creating media tree structure of:
```
- Folder
-- SubFolder1
-- (other media)
- SubFolder2
```

**Comment by nul800sebastiaan** [comment]
Hey @Icarium666 - this is now a feature we have since Umbraco 7.15.0, each media picker can be configured to ignore the start node - https://github.com/umbraco/Umbraco-CMS/pull/2441

I'll close this one!
