### ISSUE TITLE
Umbraco 8 - Split view issue with Markdown editor

### ISSUE THREAD

**Issue by readingdancer** [umbraco/Umbraco-CMS#3010]
The markdown editing menu is duplicated on the left content pane and it is not shown at all on the right one.

Reproduction
------------

### Bug summary

The markdown editor menu is duplicated as you can see in this screen shot:

![A screenshot of the issue](https://user-images.githubusercontent.com/4398217/45858376-19dda680-bd2b-11e8-96d8-c71f051a27e5.png)

### Specifics

Umbraco version 8.0.0-alpha.50 assembly: 8.0.0.0
Editing with one English and one Spanish panel

### Steps to reproduce

- Create a simple site with two languages ( I used US English & US Spanish )
- Create a document type with a Markdown Editor
- Add a new page to the content section based on this doc type
- Edit this new page
- Click on the drop down language selector above the content editing
- Click the small link 'Open in Split View'
- Close the split view
- Repeat the last three steps a few times. 

### Expected result

I would expect to see two Markdown editors with their respective editing menus.

### Actual result

As you can see in the screen shot above, each time you open the split view, an additional edit menu is added above the Markdown editor on the left and no edit menu is added to the new edit window on the right.

**Comment by kjac** [comment]
I'll fix this.

**Comment by kjac** [comment]
PR in #3592

**Comment by nul800sebastiaan** [comment]
Fixed in https://github.com/umbraco/Umbraco-CMS/pull/3592
