### ISSUE TITLE
Re-Ordering (Unsaved) Nested Content Removes Values

### ISSUE THREAD

**Issue by daniel-chenery** [umbraco/Umbraco-CMS#3014]
When adding a Nested Content item (2nd/3rd/4th etc), if you grab the 'move' handle without saving the page or closing the editor box, the content will be lost.

Reproduction
------------

### Steps to reproduce

These steps were tested on Umbraco 7.12.1

- Add a (second) nested content item.
- Fill out the fields
- Move this item to the first item
- Content will be lost

**Comment by nul800sebastiaan** [comment]
Fixed in https://github.com/umbraco/Umbraco-CMS/pull/3086
