### ISSUE TITLE
'Change password' function in 'Users' section does a password reset instead of setting the new password

### ISSUE THREAD

**Issue by arjan-pitcrew** [umbraco/Umbraco-CMS#3015]
Reproduction
------------

After creating a new user in the Umbraco backoffice I use the 'Change password' function in the 'Users' section to set an initial password. The hashed password is stored in the 'umbracoUser' database table, but when I try to log in to the backoffice using these credentials I get a 'Login failed for user <email>'.

When I manually copy/paste a working hashed password to the user in the database then I can log in without a problem. Also, when I use the 'Forgotten password?' function on the backoffice login screen to reset the password the password works fine afterwards.

So only the 'Change password' function in the 'Users' section appears to be generating invalid password hashes.

[https://our.umbraco.com/forum/using-umbraco-and-getting-started/91827-the-change-password-function-in-umbraco-admin-generates-invalid-password-hashes](https://our.umbraco.com/forum/using-umbraco-and-getting-started/91827-the-change-password-function-in-umbraco-admin-generates-invalid-password-hashes)

### Specifics

- Tested on Umbraco version 7.12.2 and 7.12.3
- It's a fresh installation of Umbraco, so legacyEncoding is not the issue
- I've added a machine key to the web.config during the initial setup
- The user is not locked out (userNoConsole = False)
- Tested on latest versions of Firefox and Chrome
- No errors, /umbraco/backoffice/UmbracoApi/Authentication/PostLogin just returns a '400 Bad Request' status which is default for not entering invalid credentials

These are the relevant web.config settings:

`<machineKey validationKey="[...]" decryptionKey="[...]" validation="HMACSHA256" decryption="AES" />`

```
<add name="UsersMembershipProvider" 
     type="Umbraco.Web.Security.Providers.UsersMembershipProvider, Umbraco"
     minRequiredNonalphanumericCharacters="1"
     minRequiredPasswordLength="12"
     useLegacyEncoding="false"
     enablePasswordRetrieval="false"
     enablePasswordReset="true"
     requiresQuestionAndAnswer="false"
     passwordFormat="Hashed"
     allowManuallyChangingPassword="true" />
```

### Steps to reproduce

1. Log in to the backoffice
2. Go to the 'Users' section
3. Right-click on 'Users' in the treeview and select 'Create'
4. Enter a name, email address and add a group
5. Click on 'Create user'
6. Click on 'Go to user profile'
7. Click on 'Change password'
8. Set a custom password that matches the requirements
9. Click on 'Save'
10. Logout
11. Try to log in using the new user's credentials
12. LOGIN FAILS

### Expected result

Setting a password through the 'Change password' function should store a valid hashed password in the database.

### Actual result

Using the 'Change password' function stores an invalid hashed password in the database.

**Comment by dawoe** [comment]
Hi arjan,

Are you sure this is a fresh install ?

I only have this in the web.config for the UsersMembershipProvider

` <add name="UsersMembershipProvider" type="Umbraco.Web.Security.Providers.UsersMembershipProvider, Umbraco"/>`

Your config looks modified.

**Comment by creativesuspects** [comment]
You are absolute right. I did modify the web.config to configure minimum password requirements. I will do an additional test with a genuine fresh install and report back in a bit.

**Comment by StephanThierry** [comment]
This is also a problem on v7.10.3 (Seemed to be working in 7.6.4.)

**Comment by creativesuspects** [comment]
@dawoe You we're right. The issue is caused due to the custom settings for the 'UsersMembershipProvider'.

When I use the default settings the 'Change password' function works fine: "

`<add name="UsersMembershipProvider" type="Umbraco.Web.Security.Providers.UsersMembershipProvider, Umbraco"/>`

But when I add the custom settings it breaks the 'Change password' function:

```
<add name="UsersMembershipProvider" 
     type="Umbraco.Web.Security.Providers.UsersMembershipProvider, Umbraco"
     minRequiredNonalphanumericCharacters="1"
     minRequiredPasswordLength="12"
     useLegacyEncoding="false"
     enablePasswordRetrieval="false"
     enablePasswordReset="true"
     requiresQuestionAndAnswer="false"
     passwordFormat="Hashed"
     allowManuallyChangingPassword="true" />
```

I've even managed to narrow it down to this setting:

`allowManuallyChangingPassword="true"`

When I leave that out, the 'Change password' function works fine.

**Comment by creativesuspects** [comment]
By the way, the `<machineKey />` setting in the web.config doesn't have any effect on the issue. The issue is only triggered when the 'allowManuallyChangingPassword' setting is set to 'true'.

**Comment by dawoe** [comment]
Why do you need that setting ?

Dave

**Comment by creativesuspects** [comment]
allowManuallyChangingPassword (default 'false'): Must be set to 'true' if you want to change passwords from code (e.g. calling the MemberService.SavePassword()-function)

**Comment by dawoe** [comment]
But MemberService is not using the UsersMembershipProvider provider

That is using UmbracoMembershipProvider

**Comment by creativesuspects** [comment]
@dawoe Duh! I feel like an idiot. :-) So, as far as I'm concerned this non-issue can be deleted. Unless @StephanThierry has some additional input?

**Comment by StephanThierry** [comment]
Nope. Removing allowManuallyChangingPassword="true" worked for me too - this is not something I would have guessed. 

I initially added it to solve an issue where no accounts where working so I could overwrite the admin password programmatically and get access to the system. I never imagined that it was this setting blocking the admin-change password function from working.

**Comment by creativesuspects** [comment]
@StephanThierry Yeah, I currently don't manage any projects where I have to be able to set a backoffice user's password from code, but it should be possible without breaking any other functions. So I guess it's still a small bug.

**Comment by MrCosmo** [comment]
I experienced the same issue. Problem was indeed with allowManuallyChangingPassword="true" in web.config.
Wierd thing is that if you create a new backoffice user, you can login with the generated password by Umbraco.
When you (as an administrator) change that password in the backoffice it's broken.
However, if the editor logs in (before you broke the password by changing it) he is able to reset his password to some personal password without braking it.

**Comment by StephanThierry** [comment]
@MrCosmo This is the exact behaviour I have experienced. I doubt it's by design - it must be a bug. 

It's a simple case of - a feature having an unintended side effect.
![](https://i.redd.it/mwdemhrww2az.jpg)

**Comment by creativesuspects** [comment]
I will try to dive into the code next week and hopefully create a PR to fix the issue. It should just be a matter of finding out how the 'Change password' implementation in the Users section differs from the 'Forgotten password?' implementation on the backoffice login screen.

**Comment by nul800sebastiaan** [comment]
See https://github.com/umbraco/Umbraco-CMS/issues/3067 - apparently it's doing a password reset instead of setting the new password.

**Comment by creativesuspects** [comment]
@nul800sebastiaan That explains the issue. I haven't had time to dive into the code yet. But knowing what the problem is it should be fairly easy to implement a fix.

**Comment by medarke** [comment]
Is this issue solved in Umbraco 8?

**Comment by Shazwazza** [comment]
@medarke would assume so, it's fixed in v7 and we merge to v8, why not give it a try?
