### ISSUE TITLE
Umbraco.Web.Routing.PublishedContentRequestEngine check for IsApproved property

### ISSUE THREAD

**Issue by vwa-software** [umbraco/Umbraco-CMS#3017]
Role based Member Protection of a content node.

When a member is loged in, and then is dis-approved by an administrator. The member has still access to restricted content nodes (Public access)

Reproduction
------------

* Use the Public access to restrict a page to some certain roles.
* Login as an Umbraco Member
* While loged in, Disable the user by unchecking the Is Approved property
* The Member has still access to the restricted page, unless they log-out.

Should there be a check in the EnsurePublishedContentAccess method?

**Comment by kjac** [comment]
I can reproduce this. I'm really surprised this hasn't been caught sooner 🤔 

I've got a fix for test now... will submit a PR soon as it's done. Thanks for reporting, @vwa-software 👍

**Comment by kjac** [comment]
PR in #3588

**Comment by nul800sebastiaan** [comment]
We'll need to discuss the proposed solution at HQ as it seems a bit much to add 3 database queries to each request. We'll get back to you!

**Comment by kjac** [comment]
@nul800sebastiaan one possible solution is to add something like `IsMemberValid(string username)` on `MemberService`. The backdraw of that solution (apart from the extra method) is that it'll explicitly perform an extra roundtrip to the DB, whereas the extra roundtrips in proposed solution are likely to happen anyway later on in the request.

**Comment by Shazwazza** [comment]
Important to note that this doesn't add 3 db queries to *every* request, only if the node is actually a protected node and only if the member is logged in and has access to it

**Comment by kjac** [comment]
@Shazwazza yep, good point.

**Comment by nul800sebastiaan** [comment]
Yeah, so imagine I run an intranet, with all pages being protected nodes.. 😉

**Comment by Shazwazza** [comment]
Perfect :) well then like you mentioned, it's generally not going to be extra overhead. I'd imagine the vast majority of protected pages that exist will lookup the current members info (i.e. to show logon info, avatar, profile, etc...)

**Comment by kjac** [comment]
My thoughts exactly. But it's that very assumption you guys at HQ need to give the thumbs up on for the proposed solution to work 😄

**Comment by nul800sebastiaan** [comment]
Ah, I missed that little detail. So we need to make sure the cached member data is invalidated once you change the member's data/status, but I assume that's done anyway.

In which case, this seems like a fine solution we can test and eventually merge!

**Comment by Shazwazza** [comment]
This is only a request based cache, just so that we don't double up on SQL in the same request, so the cache invalidation isn't an issue - it's been like this all along :)
