### ISSUE TITLE
Non-administrator users logged out when creating user groups

### ISSUE THREAD

**Issue by jamescoxhead** [umbraco/Umbraco-CMS#3018]
When a non-administrator user tries to create a new user group they are logged out of the back office when they click on the Save button.

Reproduction
------------

### Specifics
Umbraco 7.12.3 (I've reproduced the issue on a client site where it was first reported and on an empty installation)

### Steps to reproduce
1. Log into the back office as an administrator
2. Either add the Users section to the existing Editors user group, or create a new user group with access to the Users section
3. Create a new user. Add them to the Editors group (and the new user group created in the previous step if applicable)
4. Log out of Umbraco. Log in as the new user. Go to the Users section
5. Try to create a new user group with any combination of settings.

### Expected result
When the save button is clicked, the user group is created and users can be assigned to it.

### Actual result
When the save button is clicked, the user is redirected to the login screen. A 401 error is shown in Chrome's dev tools:
![image](https://user-images.githubusercontent.com/6759305/45888259-8dc49100-bdb5-11e8-99a8-90dab6073174.png)

**Comment by jannikanker** [comment]
Hmmm... Interesting. Unless I'm reading it totally wrong (and I misunderstood the data I saw while debugging) then: unless you are an admin you have to be a member of the group you are creating... That's tough. Even when I add "myself" (the non-admin logged in user) to the new group it still logs me out as - funnily enough - I can't possibly be a member of a group that isn't yet created.

This method: https://github.com/umbraco/Umbraco-CMS/blob/1bb593d264a085f94a3ce3bd710392b350561430/src/Umbraco.Web/Editors/UserGroupEditorAuthorizationHelper.cs#L51

Is called from here: https://github.com/umbraco/Umbraco-CMS/blob/1bb593d264a085f94a3ce3bd710392b350561430/src/Umbraco.Web/Editors/UserGroupsController.cs#L33

I'm not entirely sure where to go from here, though. One possible option would be to use the other overload for AuthorizeGroupAccess ( https://github.com/umbraco/Umbraco-CMS/blob/1bb593d264a085f94a3ce3bd710392b350561430/src/Umbraco.Web/Editors/UserGroupEditorAuthorizationHelper.cs#L31 ) and check for whether the group is brand new via the ID. And if it is, the creator will not have to be a member of that group.

Maybe @clausjensen or @Shazwazza can pitch in? Someone else? I *am* correct in assuming that access to the user section should allow you to create users and groups, right? Regardless of admin status?

**Comment by jannikanker** [comment]
Aaaaanyway, I'm going to give it a shot with a PR to fix this ;-)

**Comment by jannikanker** [comment]
PR here: https://github.com/umbraco/Umbraco-CMS/pull/3111
