### ISSUE TITLE
System.OutOfMemoryException

### ISSUE THREAD

**Issue by a-witkowski** [umbraco/Umbraco-CMS#3027]
Often the first time the site is launched on iis, an error occurs

Exception of type 'System.OutOfMemoryException' was thrown

[screenshot](https://ibb.co/iHsxu9)

Umbraco 7.12.2
Win10
.net 4.7

**Comment by nul800sebastiaan** [comment]
Hi @a-witkowski and many apologies for the late reply 🙈 

Luckily, this is not an error that most people run in to, it feels like it might be something on either your machine or in customizations you've made.

If this is still a problem, make sure to head over to [the forum](https://our.umbraco.com) to get some advise on how to debug this problem.
