### ISSUE TITLE
umb-tooltip returns console error

### ISSUE THREAD

**Issue by bjarnef** [umbraco/Umbraco-CMS#3041]
When using `umb-tooltip` component/directive from the example markup it throw this error in console for each tooltip. Furthermore it doesn't seem to work correct on `umb-button`.

![image](https://user-images.githubusercontent.com/2919859/46061506-29b01d00-c167-11e8-8dbe-f5a23645ddcf.png)

Reproduction
------------

If you're filing a bug, please describe how to reproduce it. Include as much
relevant information as possible, such as:

### Bug summary

The `umb-tooltip` component/directive seems to return a console error, because the `event` is null. It might trigger this on init and before the event is set in mouseOver function. Furthermore I had some issues with using it directly on `umb-button`, where I needed to add a wrapper and a transparent overlay to trigger to tooltip on this transparent overlay. The mouseover and mouseleave might be conflicting with other events on `umb-button`.

### Specifics

    * Umbraco version 7.7.13
    * Google Chrome Version 69.0.3497.100

### Steps to reproduce

Use the example snipppet documented in https://github.com/umbraco/Umbraco-CMS/blob/1bb593d264a085f94a3ce3bd710392b350561430/src/Umbraco.Web.UI.Client/src/common/directives/components/umbtooltip.directive.js

or add the following code:

View:
```
<div ng-mouseover="vm.mouseOver($event)"
    ng-mouseleave="vm.mouseLeave()"
    style="position: relative; margin-left:10px;">
    <span style="display: inline-block; position: absolute; left: 0; right: 0; top: 0; bottom: 0; z-index: 2; background: transparent;">
    </span>
    <umb-button type="button"
                button-style="info"
                label="Update"
                disabled="false"
                action="vm.doSomething()">
    </umb-button>
</div>
```

Controller:
```
var vm = this;

vm.mouseOver = mouseOver;
vm.mouseLeave = mouseLeave;
vm.doSomething= doSomething;

vm.tooltip = {
    show: true,
    event: null
};

function mouseOver($event) {
    vm.printTooltip = {
        show: true,
        event: $event
    };
}

function mouseLeave() {
    vm.tooltip = {
        show: false,
        event: null
    };
}

function doSomething() {
    alert('Hello World!');
}
```

Furthermore I have added the transparent `<span>` element overlay to make the tooltip trigger when using `umb-button`. Try compare this example with the same example which doesn't have the wrapping div and span element, but just `ng-mouseover` and `ng-mouseleave` on `umb-button`.

### Expected result

The `umb-tooltip` shouldn't return a console error and work on `umb-button` as well.

### Actual result

The `umb-tooltip` returns a console error and has some issues when used on `umb-button`.

**Comment by nul800sebastiaan** [comment]
Thanks for the report! 

I've marked this as "Up for grabs" so that you or someone else coming along could create a pull request for it.

**Comment by nul800sebastiaan** [comment]
This issue has been in the `up for grabs` state for quite a while now and it seems nobody is ready to pick this one up.

For now we'll close this issue to prevent the list of `up for grabs` from becoming very stale. We're happy to re-open it if someone still thinks it's good to work on this. 

If anyone is about to pick this issue up to fix it, make sure to test first if you can reproduce the problem in the latest version before you start to work on it.

Thanks!
Sebastiaan on behalf of Umbraco HQ.
