### ISSUE TITLE
Changing httpruntime targetFramework version forces Danish language in the backoffice

### ISSUE THREAD

**Issue by nul800sebastiaan** [umbraco/Umbraco-CMS#3042]
<p>What did you do?
Changed httpRuntime -&gt; targetFramework from 4.5 to eg. 4.6.2 in web.config</p>
<p>What did you expect to happen?
An English backoffice :P
umbracoDefaultUILanguage is set to en-US and the language for the logged in user is set to English (United States)</p>
<p>What actually happened?
Backoffice is being shown translated to Danish except a few places.
Changing the targetFramework back to 4.5 immediately switches the language back to English.</p>
<p>Issue imported from old issue tracker: <a href="https://issues.umbraco.org/issue/U4-11435">U4-11435</a>

**Comment by christophnz** [comment]
We had an issue where the backoffice was showing placeholders in square brackets for all the translated labels and buttons when changing the targetFramework to 4.7. I can confirm that upgrading to 7.13 fixes that issue.
