### ISSUE TITLE
Domin Name issue into Umbraco: Reset Password link into email

### ISSUE THREAD

**Issue by pkspinx** [umbraco/Umbraco-CMS#3044]
A brief description of the issue goes here.
Hello ,
I have faced issue into umbraco admin user reset password email template.

I have binding many host names into like xyz.com,abc.com but my actual domain is xxx.com.
Other domains are point out for redirection purpose.

when i am reset my admin user password at that time reset password link generate with xyz.com or abc.com domain not my actual domain.

Kindly help me on this.

Reproduction
------------

If you're filing a bug, please describe how to reproduce it. Include as much
relevant information as possible, such as:

**Comment by nul800sebastiaan** [comment]
Hey there @pkspinx - I can't reproduce this problem on the latest version of Umbraco:

1. I go to mysite.com/umbraco and use the "Forgotten password?" link and enter my email
2. The email I get has a link that starts with  mysite.com/umbraco/ValidatePasswordResetCode 
3. I go to myotherdomain.com/umbraco and use the "Forgotten password?" link and enter my email
4. The email I get has a link that starts with myotherdomain.com/umbraco/ValidatePasswordResetCode 

So it seems like you might be doing something differently. For some help with this make sure to [head to the forum](https://our.umbraco.com/) where our friendly community can help you further on this issue.
