### ISSUE TITLE
Update the Imageprocessor cache location

### ISSUE THREAD

**Issue by steroberts89** [umbraco/Umbraco-CMS#3047]
ImageProcessor by a default configuration value stores it's cached data in a folder within /App_Data/cache, I believe it is a DX issue where there is a folder within App_Data named cache, which is used exclusively by image processor. It should be descriptive as to what it is the cache for! (Especially seeing as Umbraco has many caches!)

I can't think of anything which this would negatively effect, upgrades would be unaffected i believe?

Any feedback?

I've submitted a PR at #3046

**Comment by leekelleher** [comment]
@steroberts89 I agree with changing the folder path.  I'm wondering whether the "TEMP" folder might be appropriate? e.g. `~/App_Data/TEMP/ImageProcessor`
Since that's where other Umbraco components store their caches.

**Comment by steroberts89** [comment]
@leekelleher Some conversation is happening over on the PR #3046

**Comment by nul800sebastiaan** [comment]
Sorry forgot to close this with the closing of the PR.
