### ISSUE TITLE
Show 301 url redirects on info tab too

### ISSUE THREAD

**Issue by nul800sebastiaan** [umbraco/Umbraco-CMS#3049]
<p>I would love to see that you see which 301's there are for that specific node on the new Info-tab. Currently the only way the find them is to go to the Content Dashboard and the tab &quot;Redirect URL Management&quot;. Most of the times this is an exploded list of changed urls.</p>
<p>I think it would make far more sense if you see them in context of the node. I think it's really crucial for users to see what happens if they change a node name, and could decide to delete some redirects themselves.</p>
<p>Issue imported from old issue tracker: <a href="https://issues.umbraco.org/issue/U4-10669">U4-10669</a><p><strong>Note: This issue has attachments in the original issue</strong></p>

**Comment by nul800sebastiaan** [comment]
Fixed in https://github.com/umbraco/Umbraco-CMS/pull/2452

**Comment by dawoe** [comment]
@nul800sebastiaan the PR is merged. Shouldn't this be closed then ?

**Comment by nul800sebastiaan** [comment]
Whoops, thanks @dawoe !
