### ISSUE TITLE
Visual issue: extra border on tabs when mouse-out (sometimes)

### ISSUE THREAD

**Issue by Myster** [umbraco/Umbraco-CMS#3051]
### Bug summary

When you change tab, then move the mouse off the tabs you sometimes get an extra bottom border like so:
![image](https://user-images.githubusercontent.com/354777/46110660-7879b780-c238-11e8-8e0d-c50deabba551.png)

### Specifics

Create fresh umbraco cloud instance (using starter kit)

### Steps to reproduce

- go to about us page.
- click info tab
- move mouse down.

### Expected result

no extra border should show

### Actual result

an extra border shows and the tabs "jiggle"

**Comment by nul800sebastiaan** [comment]
Yeah I've seen this too sometimes! 

I've marked as "Up for grabs" so that you or someone else coming along could create a pull request for it.

**Comment by markadrake** [comment]
There is a lot of strange things in the stylesheet mixing **positioning**, **negative margins**, and extra **borders** on the tab container. Extraneous styling can be really tough to troubleshoot and feel confident about the fix.

So after a change to the CSS and fixing this one instance of an issue, how / where do I verify that any other instance of the tabs isn't broken?

I'll have a `temp-3051` branch open soon.

**Comment by nul800sebastiaan** [comment]
Fixed in https://github.com/umbraco/Umbraco-CMS/pull/3060
