### ISSUE TITLE
U4-3659 - When popout/context menu shows, could we somehow show which node it relates to

### ISSUE THREAD

**Issue by markadrake** [umbraco/Umbraco-CMS#3055]
This is an older issue opened by Matt Brailsford, [please ref. the original context at the old Umbraco Issue Tracker](https://issues.umbraco.org/issue/U4-3659).

> When right clicking a node, there is no visual indicator to say which node the context menu relates to. This can be equally confusing if a different node is selected in the tree as it makes it look like that's the one it relates to (when it might not be).

> Maybe changing the "..." icon to something else would be enough, just to show "ahh, it's that node".

The easiest solution I could come up with is to simply keep the node highlighted, as it was when you hovered. [I've created a simple click through prototype with Adobe XD here](https://xd.adobe.com/view/13a80679-4bb5-46e6-4a9a-1603f8ddcfde-6599/). Page 3 shows the current behavior, and Page 4 shows the new behavior.

**Comment by nul800sebastiaan** [comment]
This is great! Care to send a PR for doing that in a simple way?

I've marked as "Up for grabs" so that you or someone else coming along could create a pull request for it.

**Comment by nul800sebastiaan** [comment]
Fixed in https://github.com/umbraco/Umbraco-CMS/pull/3056
