### ISSUE TITLE
Images in RTE inside Grid in Edge are impossible to select and resize

### ISSUE THREAD

**Issue by vladox** [umbraco/Umbraco-CMS#3057]
When trying to edit an image using an RTE grid editor on the Edge Browser the images are impossible to select after inserted.

Reproduction
------------

If you're filing a bug, please describe how to reproduce it. Include as much
relevant information as possible, such as:

### Bug summary 
 
An image in RTE grid editor on the Edge Browser is impossible to select or resize.   

### Specifics .  

- No specific URL.   
- Umbraco 7.10.4 . 
- MS Edge 17 . 
- Working on Chrome 69.  

### Steps to reproduce . 

- Log in to Umbraco 7.10.4 in Edge 17 . 
- Add RTE grid editor to a node . 
- Insert  JPG image  
- try to select it to resize it . 

### Expected result . 

Be able to select the image and resize it.  

### Actual result  

Image getting deselected as soon as it shows the selection border and corner dots.

**Comment by nul800sebastiaan** [comment]
Thanks @vladox - this seems to work these days so I'll close this issue.

![image](https://user-images.githubusercontent.com/304656/50155066-681f2900-02cb-11e9-8741-5b77c8a0f9a6.png)
