### ISSUE TITLE
RTE (TinyMCE) content can be deleted if a content item is saved before the RTE finishes loading

### ISSUE THREAD

**Issue by UEDevs** [umbraco/Umbraco-CMS#3058]
It's possible to wipe out the contents of the TinyMCE rich text editors if you save a content item while they're still being loaded.

This issue was logged on the old issue tracker as [U4-11302](https://issues.umbraco.org/issue/U4-11302) and PR #3023 has already been merged to partially fix this. That fix worked for fast connections but it's still possible to trigger the issue on a slow connection.

It looks like updating the RTEController to move the `$scope.isLoading = false;` check into the `editor.on('init')` function could fix this for good but I'm not sure if there are other situations to consider where the RTEs might be getting reset or updated. It would be good if someone who has more knowledge of this controller could take a look.

For reference, the original report from Michael Argentini was as follows:

> If the TinyMCE editors are slow to render their toolbars and content for some reason (JavaScript issues, slow network performance, etc.) and a content author saves/publishes changes, ALL RTE content editors get saved as EMPTY. ALL of the RTE content is effectively erased. This has been happening since early version 7 releases.

> One potential fix would be to disallow all editing until everything loads. Another would be to hide the all editor fields until they all load. Perhaps the underlying editor should first load a hidden textarea with the content. Even if the interface issues a red error bar when saved prior to a complete load it would at least save authors from losing content.

> This is an insidious bug that has bitten me and my clients countless times and really needs to be fixed.

Reproduction
------------

### Specifics

This has been observed in Firefox and Chrome on Umbraco version 7.10.4 but I would assume it's still an issue with the latest versions as well.

### Steps to reproduce

1. Create a document type with a required RTE field.
1. Create a content item from that document type.
1. Add some content to the RTE field and save the content item.
1. Reload the page and try to save the content item while the RTE is still loading (don't actually edit anything).
1. Keep reloading and saving until the content in the RTE field gets removed and you get the warning saying that the "Value cannot be empty".

### Expected result

The original content should always be saved in the RTE field.

### Actual result

(when the save is badly timed) The content gets removed from the RTE, the content item is saved and a roll back has to be performed to restore the content.

**Comment by markadrake** [comment]
Question - around line 380 of **rte.controller.js** I see a condition verifying tinyMce loaded correctly. If we add one more condition to check on `$scope.isLoading` we can simply ignore everything. TinyMce didn't load, so our users definitely did not edit or change content, so we can use the initialized value. 

After testing, I couldn't break it. I simulated a slow 3g connection in my browser and clicked the save and publish button (even before the button finished loading). I did not lose the content.

**Comment by nul800sebastiaan** [comment]
Fixed in https://github.com/umbraco/Umbraco-CMS/pull/3062

**Comment by allyen** [comment]
Unfortunately, we've forgotten to fix this issue for the grid RTE as well – see https://github.com/umbraco/Umbraco-CMS/blob/dev-v8/src/Umbraco.Web.UI.Client/src/common/directives/components/grid/grid.rte.directive.js#L138. Will put up a PR soon.
