### ISSUE TITLE
Umbraco high CPU

### ISSUE THREAD

**Issue by shearer3000** [umbraco/Umbraco-CMS#3063]
Hello

The server team monitoring our website are reporting that it (IIS worker process) is consuming 100% CPU over extended periods of time i.e. up to 24 hours plus.

Microsoft have been engaged to review thread dumps. Their analysis has determined that two threads (it is a dual CPU server) are getting into an infinite loop state within an umbraco core module (note: not our custom website code), and for the problematic code in question have made some suggestions to make it thread-safe.

The code line Microsoft have pinpointed is in “Umbraco.Web.PublishedCache.XmlPublishedCache.XmlPublishedContent.InitializeNode”:

`properties[propertyType.PropertyTypeAlias] = xmlPublishedProperty;             //Microsoft comment: this dictionary object will be accessed concurrently and modified concurrently as well. This is the reason why we see two threads stuck inside it and causes high CPU.`

Here is a summary of Microsoft’s Suggestions:

SUGGESTIONS
============
1. Please consider using*ConcurrentDictionary* class in umbraco module to replace Dictionary class. ConcurrentDictionary is thread-safe when multiple threads will access. Please refer tohttp://dotnetpattern.com/csharp-concurrentdictionary
2. Or in*umbraco!Umbraco.Web.PublishedCache.XmlPublishedCache.XmlPublishedContent.InitializeNode(…),please add a lock in front of **properties[propertyType.PropertyTypeAlias] = xmlPublishedProperty;*so that multiple threads won’t modify the dictionary object concurrently.

ADDITIONAL INFO
================
This blog also discusses about the same problem, it is nice to check.https://blogs.msdn.microsoft.com/tess/2009/12/21/high-cpu-in-net-app-using-a-static-generic-dictionary/

Environment:
Umbraco 7.7.8
VMs (two servers connected with a load balancer) are win server 2016, dual CPU, 8GB RAM, and are patched on a regular basis (currently up to date).

Thanks,
Andrew
Terabyte Interactive.

**Comment by Shazwazza** [comment]
Great find, thanks @shearer3000 ! 

In later versions of .NET framework/Core an exception will actually be thrown if this occurs. We'll fix up asap, should be very straight forward.

**Comment by charnaew** [comment]
That's great to hear! thanks Shannon. do you have an idea of how soon we can expect this in a release?

**Comment by clausjensen** [comment]
@shearer3000 @charnaew This is scheduled to be worked on in the next sprint (2 weeks) - so hopefully a fix should be done within the next couple of weeks.

**Comment by zpqrtbnk** [comment]
PR https://github.com/umbraco/Umbraco-CMS/pull/3136

Adds a lock around the `XmlPublishedContent` initialization. We did not have such a lock because *in theory* instances of the class are scoped to a request, and so should not be involved in multi-threaded operations. But then, if/when they are, we end up with the dictionary issue. So now, the concurrency problem on the dictionary should be fixed.

**Comment by RobertCopilau** [comment]
All looks good, merging.
