### ISSUE TITLE
Change password by admin is resetting passwords

### ISSUE THREAD

**Issue by clausjensen** [umbraco/Umbraco-CMS#3067]
When an admin user is using the 'change password' functionality through the backoffice, a ChangePassword object is sent to the server - specifying that the password should be reset.

This causes the user's password to simply be reset and the specified password is never used. As you aren't told what the password was set to (since you just specified yourself what it should be) - this would basically cause the user to no longer be able to access the backoffice.

Workaround is to use the 'forgot password' functionality to set the password since this will still work.

Changing your own password from the backoffice also still works as intended.

**Comment by nul800sebastiaan** [comment]
This duplicates https://github.com/umbraco/Umbraco-CMS/issues/3015 - I'll update that one.
