### ISSUE TITLE
DialogService with media file

### ISSUE THREAD

**Issue by danielmeyer-cn** [umbraco/Umbraco-CMS#3068]
I've created a custom controller with a link picker. I select a file and submits it. When I want to edit the link I get an error and the file isn't getting selected in the dialog. For pages it works great but it doesn't seem to be built for media.

Error:
`Request error: The URL returned a 404 (not found): /umbraco/backoffice/UmbracoApi/Entity/GetPath`

I use this code to populate the LinkPicker Dialog:
```
var mediaObject = { id:2457, isMedia: true, name: "logo.png", url: "/media/1008/logo.png"};
dialogService.linkPicker(mediaObject);
```

LinkPicker doesn't seem to support preselecting media:
https://github.com/umbraco/Umbraco-CMS/blob/master-v7/src/Umbraco.Web.UI.Client/src/views/common/dialogs/linkpicker.controller.js#L29-L35

Reproduction
------------

### Bug summary

Gets an error when trying to populate dialogService.linkPicker with a media-file.

### Specifics

* Umbraco version:  7.7.0
* https://github.com/umbraco/Umbraco-CMS/blob/master-v7/src/Umbraco.Web.UI.Client/src/views/common/dialogs/linkpicker.controller.js#L29-L35
Temporary solution to remove the error: 
```if ($scope.target.id && !$scope.target.isMedia || $scope.target.udi && !$scope.target.isMedia) {```

* Url called when opening Link Picker with 
`/umbraco/backoffice/UmbracoApi/Entity/GetPath?id=1204&type=Document`

### Steps to reproduce

1. Create a custom controller
2. Create an add link button (that using dialogService.linkPicker())
3. Create an edit button where you pass the object to the link picker
4. Click your add link button
5. Select a media file
5. Submit the dialog
6. Click your edit button

This should reproduce the error.

### Expected result
The link picker dialog should preselect the file

### Actual result
* Error: `Request error: The URL returned a 404 (not found): /umbraco/backoffice/UmbracoApi/Entity/GetPath`
* Media file doesn't get preselected

**Comment by abjerner** [comment]
I tried to reproduce this in 7.12.3, and the dialog no longer appear to trigger an error when trying to set the selected media - but the media still isn't preselected as expected.

The linkpicker dialog is however obsolete, as it was replaced by the linkpicker overlay (in 7.4 I think). The overlay has better UI/UX, and should generally be used instead. However, ironically the overlay is still affected by the same bug that you reported for the dialog.

Below screenshot is from a fresh installation of 7.12.3:

![image](https://user-images.githubusercontent.com/3634580/46260578-1fd04600-c4e8-11e8-93ae-12562775901e.png)

**Comment by nul800sebastiaan** [comment]
I've marked this as "Up for grabs" so that you or someone else coming along could create a pull request for it.

**Comment by kjac** [comment]
I can see a few other issues with the linkpicker overlay:

1. The selected node is only highlighted the first time the overlay opens. All subsequent displays of the overlay doesn't highlight the selected node:
![link-picker-overlay-1](https://user-images.githubusercontent.com/7405322/48732498-2bb2cb80-ec40-11e8-9bce-71a5e4d77fe2.gif)

2. The highlighted node remains highlighted when a media is selected:
![link-picker-overlay-2](https://user-images.githubusercontent.com/7405322/48732532-4127f580-ec40-11e8-8748-874bb06cdd7a.gif)

3. The "Close" link has no effect as the model is updated immediately upon node selection.

I have pinpointed all issues along with the original one and will submit a PR to fix them all.

**Comment by kjac** [comment]
PR in #3718
