### ISSUE TITLE
Current password field should be hidden when changing passwords and not applicable

### ISSUE THREAD

**Issue by clausjensen** [umbraco/Umbraco-CMS#3069]
If `allowManuallyChangingPassword` is set to true the user provider in web.config - the current password is not used for validation when setting a new password. In the avatar 'change password' dialog we have removed this field since it isn't used.

When changing the password of your own user in the users section, this field however still shows up. It is however not used in any validation so it should simply be removed from the UI like it is in the other 'change password' functionality.

**Comment by nul800sebastiaan** [comment]
# 🛑 ✋ Reserved - don't fix please

**Note:** Please don't pick this one up. It's reserved for the upcoming Hacktoberfest as it's a fairly easy issue for a new contributor to get a feel for their first ever contribution. 👍

**Comment by mptap** [comment]
@clausjensen @nul800sebastiaan I'm working on this :)

**Comment by mptap** [comment]
@clausjensen @nul800sebastiaan here's my PR https://github.com/umbraco/Umbraco-CMS/pull/3165
Let me know if any changes are needed. I'm happy to volunteer for Hacktoberfest 2018!

**Comment by nul800sebastiaan** [comment]
Thanks @mptap! 

Did you read the big warning above not to fix this issue yet? We're reserving it for a special event. 🙂

In any case, the fix is currently incorrect, we don't want to remove the whole input field, we want to make sure it is shown only when `allowManuallyChangingPassword` is set to `true` in the web.config at which point validation should also kick in.

**Comment by mptap** [comment]
@nul800sebastiaan I did, it said reserved for Hacktoberfest, which has started. I see the field is wrapped in `ng-if="$parent.showOldPass()"` which checks for`allowManuallyChangingPassword`. Closing PR for now.
