### ISSUE TITLE
User email address not loading and can't be changed in 7.12.3 in Internet Explorer

### ISSUE THREAD

**Issue by petersmith74** [umbraco/Umbraco-CMS#3071]
Hi, I recently upgraded a v7.6.5 install to 7.12.3 and now I can't edit User details because the email field is always flagged as invalid. I have tested this on a completely new 7.12.3 install and it is also the case. 

I am able to create a new user with an email address but when I go to edit that user the email address does not display. This only appears to be an issue in IE. Works as expected in Chrome.

When I do put in an email address and try to save, it is just flagged as invalid

I have checked the umbracoUser table and the email address is there so very strange that it is not loading? 

Reproduction
------------

Go to Users tab in Umbraco back office. Select a user and you will see no email address displays. If you try and enter an email address the changes will not save.

### Bug summary

I can't edit a User because the user email field is always flagged as invalid. 
I am able to create a new user with an email address but when I go to edit that user the email address does not display. 

When I do put in an email address and try to save, it is just flagged as invalid
### Steps to reproduce

Go to Users tab in Umbraco back office. 
Select a user and you will see no email address displays in the email field. 
If you try and enter an email address and then save the changes will not save and the email address is flagged as invalid.

### Expected result

I expect to be able to see the Users email address and to be able to add a valid email address for the user

### Actual result

The actual result is that the users email address does not load and I am unable to save a user with an email address since it is always flagged as invalid

![capture1](https://user-images.githubusercontent.com/43676551/46213327-cde0c200-c327-11e8-82a2-2f1b857d0b43.PNG)
![capture3](https://user-images.githubusercontent.com/43676551/46213328-cde0c200-c327-11e8-8d28-3fb71d67a7d6.PNG)

**Comment by petersmith74** [comment]
Hi Mark, I did get the same issue on a brand new 7.12.3 install but I was still using the same IE version to test this (v11.0.9600.19080).

It is positive to hear that you haven’t got the issue on a newer version of IE - I will see when we might be getting IE upgraded.

Thanks

Pete

**Comment by mariojsnunes** [comment]
Hello,

This is also happening on Edge and IE 11.345.17134.0

When I save an existing User, the email field always fails the validation.

This might help:
If I remove a letter and type it again on the email field, the validation is then successful and the user is saved.

Any updates on this?

**Comment by nul800sebastiaan** [comment]
Fixed in  https://github.com/umbraco/Umbraco-CMS/pull/3456
