### ISSUE TITLE
Black icons have the wrong color in the Nested Content item picker

### ISSUE THREAD

**Issue by kjac** [umbraco/Umbraco-CMS#3078]
When a doctype has a black icon, it appears correctly in the list of items in Nested Content property editor. But in the item picker it's green-ish. It's probably some leftover from the grid editor item picker, which is reused styling wise for Nested Content. 

![nc icon color before](https://user-images.githubusercontent.com/7405322/46269404-335bcb00-c541-11e8-8295-194a8b06d725.png)

It looks a bit inconsistent, specially when adding other icon colors to the items, which incidentally are displayed correctly.

I've got a fix for this, will submit a PR shortly.

**Comment by nul800sebastiaan** [comment]
Fixed in https://github.com/umbraco/Umbraco-CMS/pull/3082
