### ISSUE TITLE
Dragging Nested Content items throws them out of place

### ISSUE THREAD

**Issue by kjac** [umbraco/Umbraco-CMS#3079]
If you drag an item in the Nested Content property editor, it looks fine the first time. But if you drag the same item once more, it's thrown out of place.

![nc drag offset before](https://user-images.githubusercontent.com/7405322/46269429-63a36980-c541-11e8-9339-004a576ddce6.gif)

I've got a fix for this, will submit a PR shortly.

**Comment by nul800sebastiaan** [comment]
Fixed in https://github.com/umbraco/Umbraco-CMS/pull/3083
