### ISSUE TITLE
RTE "Loading..." label is stuck in Nested Content

### ISSUE THREAD

**Issue by kjac** [umbraco/Umbraco-CMS#3080]
When an RTE is put in a Nested Content item, the "Loading..." label doesn't hide even after the RTE has loaded. This leaves some editors a bit confused.

The label disappears if you click *outside* the editor, or if you start typing *inside* it - but not when setting focus in it.  

![nc rte before](https://user-images.githubusercontent.com/7405322/46269445-89c90980-c541-11e8-9a4f-a67427c2a7c2.gif)

I've got a fix for this, will submit a PR shortly.

**Comment by nul800sebastiaan** [comment]
Fixed in https://github.com/umbraco/Umbraco-CMS/pull/3084
