### ISSUE TITLE
Nested Content configuration should not allow duplicates

### ISSUE THREAD

**Issue by kjac** [umbraco/Umbraco-CMS#3081]
Unless I'm missing something here, it shouldn't be possible to select the same doctype more than once in the Nested Content configuration. 

![nc config before](https://user-images.githubusercontent.com/7405322/46269478-b3823080-c541-11e8-8844-5d2c6033dcd5.png)

I've got a fix for this, will submit a PR shortly.

**Comment by leekelleher** [comment]
A doctype with multiple tabs could be used more than once. It's the doctype + tab combo that should be unique.

**Comment by clausjensen** [comment]
What @leekelleher said 😄 
@kjac can you change this to validate uniqueness based on both doctype and tab?

**Comment by kjac** [comment]
@leekelleher @clausjensen anything can be done. But... while you're of course technically right, I really don't think the editors will agree with your point.

If you add the same doctype with different tabs to the same Nested Content configuration, the editors have absolutely no way of knowing which is which - all the item types look the same, and are called the same too:

![image](https://user-images.githubusercontent.com/7405322/46364290-b4b47a00-c675-11e8-968a-a680437a9d2f.png)

I really think we should help people from creating an editorial scenario like that.

Also, the latest codebase doesn't even work with multiple item types based on different tabs from the same doctype. It'll choose only one of the item types (apparently an arbitrarily one?) for all the items, regardless of which one you pick. 

![nc multiple tabs](https://user-images.githubusercontent.com/7405322/46364710-e712a700-c676-11e8-975b-204caff3f48c.gif)

Furthermore the label templates don't work with multiple item types based on different tabs; in the GIF above, the label should have been "Test" for all the items.

**Comment by leekelleher** [comment]
@kjac Touché, all good and valid points!

I'm trying to think back to when we originally designed that feature (of single doctype with multiple tabs). I suspect it was before you contributed the multiple doctype feature, where we would have a single doctype with many tabs (more as a repository for all our Nested Content schemas), _which feels archaic now._

Taking your points into account, I'm happy with your original suggestion (and PR).

**Comment by kjac** [comment]
@leekelleher makes sense 👍

**Comment by clausjensen** [comment]
@kjac tbh - I haven't had a scenario where I had to do something like this so I hadn't really thought about how this would work, except for assuming that it seemed like it should be possible to do.... My nested content setups have been fairly simple I guess ;)

I however see your point and it really doesn't make sense when you can't specify a name for each of the "configurations" so you can differentiate between them. Not allowing duplicates seems like a good solution so I'm good with your changes here!

I've reviewed the code but I'll let @nul800sebastiaan merge in when ready.

**Comment by nul800sebastiaan** [comment]
Additionally, I just tried using 2 different tabs of a single doctype and this doesn't actually work. No matter which doctype I choose in Nested Content, I only get the first tab I've defined, not the second one. So it's not even a breaking change, this seems to have never been possible in the first place.

![3081](https://user-images.githubusercontent.com/304656/46418170-86917180-c72b-11e8-82e1-d4ee5cd85a10.gif)

**Comment by leekelleher** [comment]
@nul800sebastiaan I have my suspicions that it may have stopped working when the "Generic Properties" tab was dropped, as it definitely did work as I was originally using it that way, (not these days though). Anyway, I'm cool with @kjac's PR, (FWIW).

**Comment by kjac** [comment]
@nul800sebastiaan I'm seeing that as well. If you try reloading a few times it might start creating the other one instead. But it won't let you create both.

**Comment by nul800sebastiaan** [comment]
Thanks @leekelleher ! Yeah I think it might have never or only for a very short time "worked" in the core version so it seems okay to change it to "behave" more properly now.

@kjac sounds like it was pretty unusable before then! 🙂

Fixed in https://github.com/umbraco/Umbraco-CMS/pull/3085
