### ISSUE TITLE
Dashboard updates

### ISSUE THREAD

**Issue by clausjensen** [umbraco/Umbraco-CMS#3088]
child of #3090

Merging developer dashboards into settings dashboard and disabling the packages section dashboard (if it's easy - if it is not easy don't do it)

**Comment by elit0451** [comment]
PR: https://github.com/umbraco/Umbraco-CMS/pull/3109

Way to test:
- Check if all the Developer's dashboards are moved into Settings section.
- Check if the Packages dashboard is disabled.
- Check if there are no JS errors.

**Comment by Shazwazza** [comment]
* Remove the `developerdashboardvideos` part of the settings dashboard and that file
* Need to update the Umbraco.Web.UI/Config/Dashboard.Release.config to be the same as the Umbraco.Web.UI/Config/Dashboard.config
* Add the code back to the PackagesTreeController.CreateRootNode

**Comment by warrenbuckley** [comment]
All tested & merged in :+1:
