### ISSUE TITLE
New packages section

### ISSUE THREAD

**Issue by clausjensen** [umbraco/Umbraco-CMS#3089]
child of #3090

It will contain just one tree. Copy functionality that was done in the users section so that when you click the package section it will open up the one default root tree node.

**Comment by elit0451** [comment]
PR: https://github.com/umbraco/Umbraco-CMS/pull/3171

Ways to test:
- Verify that the Packages section is on place.
- Check if everything is on spot even when the Developer section was entirely removed.

Remark: ModelsBuilder still works with the Developer section ->  set Umbraco.ModelsBuilder.Enable in Web.config to false for now.

**Comment by Shazwazza** [comment]
Looks great! 🎉
