### ISSUE TITLE
Moving trees to correct sections

### ISSUE THREAD

**Issue by clausjensen** [umbraco/Umbraco-CMS#3091]
child of #3090

Remove translation tree + editors entirely (we sort of have already done this in v7), translations need to be done with current standards.

Remove task database tables so we don’t have to support this task system/APIs anymore

Dictionary tree moves to translation section.

Member types tree moves to settings section.

Macros moves to settings section.

Relation types tree moves to settings section.

Partial view macros moves to settings section.

**Comment by elit0451** [comment]
PR: https://github.com/umbraco/Umbraco-CMS/pull/3197
