### ISSUE TITLE
Moving the save action to a separate button

### ISSUE THREAD

**Issue by clausjensen** [umbraco/Umbraco-CMS#3094]
Moving the save action to a separate button instead of having it as a combo button action on the publish button.

**Comment by madsrasmussen** [comment]
PR: https://github.com/umbraco/Umbraco-CMS/pull/3108

This PR moves the save button to a separate button.

How to test:
* Make sure the new save button works (both for variant and invariant content)
* Make sure the publish button works (both for variant and invariant content)
