### ISSUE TITLE
ID is used instead of UDI in Grid Styling Media Picker

### ISSUE THREAD

**Issue by JeroenRoos** [umbraco/Umbraco-CMS#3095]
## Using Media Picker (and other Pickers as well) in the Grid Styling used ID instead of UDI.

In the Styling of the Grid Editor you can use a Media Picker, by default this picker saved the ID of the chosen media item. This is a problem when working with Umbraco Cloud because ID's of items change when transferred to other environments.
Because of the changing ID's, the UDI should be used instead of the ID. 

Here is a screenshot of the code that used ID instead of UDI (umbraco.controller.js - line 10398):
![image](https://user-images.githubusercontent.com/25620488/46285107-83a34f00-c57a-11e8-9ff6-d9eb8696d892.png)

Because the IdType is set to 'int' instead of 'udi' the check on line 10432 fails and ID is used instead of UDI.

This isn't only a problem with the Media Picker, this also appears in the other pickers (Member, Content, etc).

### Specifics

- Umbraco Cloud 
- Umbraco 7.11.1
- Deploy 2.0.14

### Steps to reproduce
The steps you should take to reproduce this problem is creating an media picker in the styles option of a Grid, selecting a media item and transfering all the content/media to another Umbraco Cloud environment.

**Comment by nul800sebastiaan** [comment]
Hi @JeroenRoos - It is not necessary for Ids to be a UDI, in fact as you can see on line 10432, if it's not a UDI, it picks the id. Deploy is respsonsible for translating that Id to the correct on on the next enviroment and in my tests this seems to works just fine.

I'll close this issue for now and if you have steps to reproduce this problem it would probably be best to get in touch with Cloud support first to see what they think. 👍
