### ISSUE TITLE
Directives for tour steps are not documented

### ISSUE THREAD

**Issue by dawoe** [umbraco/Umbraco-CMS#3099]
Several directives in the used to display tour steps are not documented, and therefore not showing up in https://our.umbraco.com/apidocs/ui/#/api

I want to start documenting some more advanced topics relating to tours on our. So it would be usefull if this documentation is up to date

**Comment by nul800sebastiaan** [comment]
Fixed in https://github.com/umbraco/Umbraco-CMS/pull/3100
