### ISSUE TITLE
Preview causes Rich text field to lose value

### ISSUE THREAD

**Issue by mbulluck** [umbraco/Umbraco-CMS#3101]
In umbraco:
Navigate to an item that contains a Rich text field and click the preview button. The preview page opens fine. However the rich text loses its value to 'NULL'.**

It happens only if you click on the Preview button fast enough.

**Comment by markadrake** [comment]
This may be related to a recent PR #3062. @mbulluck do you have time to maybe test using this code fix, or I will try to find time this week to test appropriately. All the best!

**Comment by nul800sebastiaan** [comment]
Yeah this is the exact same issue, when you hit the preview button you're doing a Save. I'll close this for now but if you can still reproduce on the latest code @mbulluck feel free to reopen it! 👍
