### ISSUE TITLE
Unable to set a users password if they have been invited.

### ISSUE THREAD

**Issue by readingdancer** [umbraco/Umbraco-CMS#3105]
We had an issue recently where a new user was invited to use an Umbraco site. For whatever reason their email was not working and hence they were not able to receive any emails from the site.

I said "oh it's ok, I'll just setup a password for you".

However, it is not possible to set the password for someone who is in the "invited" state.

The only options are to delete a user or re-send the invitation.

I think the admin user should still be able to setup a password, as in this scenario the only option is to delete the invited user and re-create them using the "create user" option.

Reproduction
------------

### Bug summary

An admin user is unable to set the password of a user in the "invited" state.

### Specifics

Umbraco 7.12.3 ( and I believe all previous versions )

### Steps to reproduce

- Invite a new user to the back office of any Umbraco site
- Ignore the emails ( don't click any links etc )
- Now as an admin user, try and reset this new invited user's password ( you can't )

### Expected result

As an admin user, I would expect to be able to reset the users password from the back office of Umbraco.

### Actual result

There is no option to do this when the user is in the "invited state" but you can do it for a user who has been "created".

**Comment by nul800sebastiaan** [comment]
This issue has been in the `up for grabs` state for quite a while now and it seems nobody is ready to pick this one up.

For now we'll close this issue to prevent the list of `up for grabs` from becoming very stale. We're happy to re-open it if someone still thinks it's good to work on this. 

If anyone is about to pick this issue up to fix it, make sure to test first if you can reproduce the problem in the latest version before you start to work on it.

Thanks!
Sebastiaan on behalf of Umbraco HQ.

**Comment by markadrake** [comment]
Ran into this issue today and it was pretty frustrating to experience. Is it a technical, backend limitation or simply a frontend problem? If it's a frontend problem I may be able to assist.
