### ISSUE TITLE
Content is not updated to reflect change by infinite editing

### ISSUE THREAD

**Issue by clausjensen** [umbraco/Umbraco-CMS#3110]
When using infinite editing to change a document type from a content item, the content item in the background is not updated to reflect those changes.

**Comment by madsrasmussen** [comment]
PR: https://github.com/umbraco/Umbraco-CMS/pull/3783

The PR fixes the event when the doctype is saved so the content node now refreshes. 

I have also added a prompt if there are any changes on the node before opening the doc type editor so you won't accidentally lose any content changes.

How to test:
- [ ] Make sure you can open the doc type editor from a node's "info"-app
- [ ] Make sure the node refreshes when the doctype is updated
- [ ] Make a change on the node (update name or a property ) and make sure a prompt is shown to tell you about the unsaved changes before the doctype editor is opened.

**Comment by warrenbuckley** [comment]
All fixed & merged
