### ISSUE TITLE
Media thumbnails no longer visible

### ISSUE THREAD

**Issue by BatJan** [umbraco/Umbraco-CMS#3112]
It turns out that after the merge of https://github.com/umbraco/Umbraco-CMS/pull/3061 there is an issue where the media grid does no longer render in the media archive.

I have done some local research and testing and found a fix for the issue, which I will make a PR for now.

**Comment by BatJan** [comment]
PR has been made here https://github.com/umbraco/Umbraco-CMS/pull/3113

**Comment by nul800sebastiaan** [comment]
Fixed in https://github.com/umbraco/Umbraco-CMS/pull/3113
