### ISSUE TITLE
Datetimepicker widget appends to DOM when navigating

### ISSUE THREAD

**Issue by sniffdk** [umbraco/Umbraco-CMS#3118]
Original issue: [https://issues.umbraco.org/issue/U4-11229](https://issues.umbraco.org/issue/U4-11229)

Can confirm that this is still an issue on 7.12.2

**Comment by nul800sebastiaan** [comment]
Yikes, that looks.. interesting! 😅

I've marked this as "Up for grabs" so that you or someone else coming along could create a pull request for it.

**Comment by nul800sebastiaan** [comment]
This issue has been in the `up for grabs` state for quite a while now and it seems nobody is ready to pick this one up.

For now we'll close this issue to prevent the list of `up for grabs` from becoming very stale. We're happy to re-open it if someone still thinks it's good to work on this. 

If anyone is about to pick this issue up to fix it, make sure to test first if you can reproduce the problem in the latest version before you start to work on it.

Thanks!
Sebastiaan on behalf of Umbraco HQ.

**Comment by sniffdk** [comment]
Closing an issue doesn't make the bug go away.. ? 🙈 
I was kinda expecting HQ to fix it at some point ... 🤔

**Comment by nul800sebastiaan** [comment]
It doesn't make the bug go away, but leaving it open forever also doesn't. 

This bug has not been found important enough for us to fix and nobody in the community has tried to fix it either. If it's a big enough problem then surely it will resurface again.

**Comment by rasmusjp** [comment]
I remember the datepicker being replaced at some point, was that only in v8?
