### ISSUE TITLE
Ability to use external authentication providers to go through the upgrade process

### ISSUE THREAD

**Issue by mderriey** [umbraco/Umbraco-CMS#3119]
Hi,

We have an application where we expect everyone to log in to the backend through an external provider &mdash; AAD, in our case.

To prevent people from accidently using the local authentication mechanism and avoiding potential brute force attacks against the `admin` account, we have:

 - modified the login view to hide the local authentication form; and
 - added an IIS rewrite rule that hijacks requests to the `/backoffice/UmbracoApi/Authentication/PostLogin` endpoint

Not long ago, we've upgraded Umbraco to the latest `7.12.3` version.
That went well, and upon the first request after it was done, users got redirected to the `/umbraco/AuthorizeUpgrade` URL to complete the upgrade.

The problem we encountered was that trying to log in with AAD didn't work, as in, when being redirected back to Umbraco after logging in at the IdP, we were prompted with the same upgrade screen. The only way around this was to log in using the local `admin` account, which we'd like to avoid if possible.

Is there any chance we could handle the external login callback before detecting there's an upgrade pending?

**Comment by nul800sebastiaan** [comment]
Thanks for raising this, I've added this to the list of things to discuss at our next regular meeting about incoming issues.

**Comment by nul800sebastiaan** [comment]
Hi there @mderriey - had a chat with Shannon and this is unfortunately a known bug. In order to fix this, the `AuthorizeUpgrade` endpoint will need to borrow some code from the login endpoint to actually use the auth provider to get an auth ticket.

I've marked this as "Up for grabs" so that you or someone else coming along could create a pull request for it.

**Comment by nul800sebastiaan** [comment]
This issue has been in the `up for grabs` state for quite a while now and it seems nobody is ready to pick this one up.

For now we'll close this issue to prevent the list of `up for grabs` from becoming very stale. We're happy to re-open it if someone still thinks it's good to work on this. 

If anyone is about to pick this issue up to fix it, make sure to test first if you can reproduce the problem in the latest version before you start to work on it.

Thanks!
Sebastiaan on behalf of Umbraco HQ.
