### ISSUE TITLE
Add option to rename color picker labels

### ISSUE THREAD

**Issue by bjarnef** [umbraco/Umbraco-CMS#3120]
I would be great to be able to rename a label in color picker prevalues. At the moment you have to remove the color and add a new color with a different label.

![image](https://user-images.githubusercontent.com/2919859/46380572-150de080-c6a3-11e8-9d25-f82386f1ad34.png)

**Comment by bjarnef** [comment]
@nul800sebastiaan can you add labels to this issue and close it? 👍

**Comment by nul800sebastiaan** [comment]
Got distracted 🙈 , thanks @bjarnef !
