### ISSUE TITLE
Redirect URL Management creates wrong redirect when using custom IUrlProvider

### ISSUE THREAD

**Issue by Swimburger** [umbraco/Umbraco-CMS#3122]
I created a custom IUrlProvider that overrides the way URLS are generated for a specific content type. The Url for Content Type X is constructed using its parent URL + Category (Custom prop on Content Item) + UrlName. 
Next I created a Content Item of Content Type X which generates the Url `/blog/umbraco/just-another-blogpost`. Subsequently, I renamed the item to "Just Another Blogpost Renamed".

Browsing to the original URL results in a 404 instead of 301. Thus Google is currently listing a URL to my site that goes to a 404 page instead of the expected content.

* IUrlProvider Gist: https://gist.github.com/SNiels/866b92895bc81db7086c811b7a10033f
* Original issue: https://issues.umbraco.org/issue/U4-11564

Reproduction
------------

If you're filing a bug, please describe how to reproduce it. Include as much
relevant information as possible, such as:

### Bug summary
* Redirect URL Management creates incorrect redirect when a custom IUrlProvider is used.
* This results in 404's that should be 301's when renaming items.

### Specifics

* Tested on Umbraco 7.11.1 and 7.12.3

### Steps to reproduce
* Create a custom IUrlProvider that overrides the way Urls are generated based for Content Type X. 
FE: The Url for Content Type X is constructed using its parent URL + Category (Custom prop on Content Item) + UrlName. 
* Create a Content Item of Content Type X which generates the Url `/blog/umbraco/just-another-blogpost`.
* Renamed the item to "Just Another Blogpost Renamed".

### Expected result
A Redirect Url should be created from  `/blog/umbraco/just-another-blogpost` to  `/blog/umbraco/just-another-blogpost-renamed`.   
When browsing to  `/blog/umbraco/just-another-blogpost`, a 301 redirect to `/blog/umbraco/just-another-blogpost-renamed` should occur.

### Actual result
The following Redirect Url was created: `/blog/just-another-blogpost` => `/blog/umbraco/just-another-blogpost-renamed`
When browsing to  `/blog/umbraco/just-another-blogpost`, a 404 page is returned.

**Comment by dawoe** [comment]
Hi @Swimburger 

Sorry for the late reply on this one. It seems there is a similar issue being created since you created this one where a discussion is going on #3186 

So I will close this one as it is a duplicate

Dave [Community Pull Request team](https://umbraco.com/blog/introducing-the-new-cpr-team/)

**Comment by Swimburger** [comment]
No problem, great to see it's being looked at!
