### ISSUE TITLE
Deleting a form in Forms seemingly times out with no ux indication but apparently still deletes the form

### ISSUE THREAD

**Issue by sniffdk** [umbraco/Umbraco-CMS#3128]
When trying to delete a form with 280+ entries, Forms will hang and after close to 4 minutes throw a 500 error stating the the operation has timed out.
The ux does not reflect that, and there is no "deletion in progress" indication, so for normal users it just seems like nothing is happening, often aborting the request early.
Even though Forms throws a timeout exception, the form is still deleted from both disk and database, if the request is allowed to "complete".

At least, the ux for deleting forms and error handling, including logging, should be improved.

The site in question is running on Azure as a webapp with an Azure SQL database running S2 with 50 DTUs, just to give a performance indication.
Umbraco is running v 7.12.2 and Forms is running v. 7.0.3.

**Comment by nul800sebastiaan** [comment]
This issue was moved to umbraco/Umbraco.Forms.Issues#28

**Comment by sniffdk** [comment]
Of course, sorry, thanks for moving it 😃
