### ISSUE TITLE
Nodes with ListViews should be able to queue child nodes for transfer

### ISSUE THREAD

**Issue by jizepi** [umbraco/Umbraco-CMS#3131]
See original bug on previous tracker at https://issues.umbraco.org/issue/U4-11063

Nodes with ListViews should also offer the option to queue child nodes for transfer. No reason not to be able to send the children of a node with list view.

Currently having to open many nodes individually to queue them all for transfer, which is something of a pain point.

**Comment by nul800sebastiaan** [comment]
This issue was moved to umbraco/Umbraco.Cloud.Issues#10
