### ISSUE TITLE
"Do something else" option in context menus is broken

### ISSUE THREAD

**Issue by BatJan** [umbraco/Umbraco-CMS#3141]
**Description**

I accidentally discovered that the **_"Do something else"_** option in the context menu is currently broken in the 7.13 release (Still in progress of course). Whenever I click the option from either the content or media section nothing happens and the browser console says: **_"args.treeNode cannot be null"_**.

**Comment by dawoe** [comment]
@BatJan tracked it down as well. I came to same conclusion as he mentions on the referenced PR

**Comment by dawoe** [comment]
I create a PR for this one : #3154
