### ISSUE TITLE
Show more specific error message when trying to move a folder into itself

### ISSUE THREAD

**Issue by BatJan** [umbraco/Umbraco-CMS#3142]
Recently we had an editor being a bit confused why one could not move a folder into another folder - The error message by default just reads "Failed to move media".

I realize it in most situations make sense that the message is generic but maybe when we can figure out that the parent id and the id we're trying to move are identical show a more specific error message about the issue hinting the editor what the cause is so they know up front instead of being annoyed that the folder can't be moved. Depending how many levels deep a folder structure is it can be a bit hard to figure or easy to overlook sometimes :)

**Comment by arknu** [comment]
@nul800sebastiaan Shouldn't this issue be marked as closed?
