### ISSUE TITLE
Lecoati.uSky.Grid reference in ApprovedColorPickerController

### ISSUE THREAD

**Issue by LennardF1989** [umbraco/Umbraco-CMS#3147]
Why is there a reference to Lecoati.uSky.Grid in the ApprovedColorPickerController?

https://github.com/umbraco/Umbraco-CMS/blob/1bb593d264a085f94a3ce3bd710392b350561430/src/Umbraco.Web.UI.Client/src/views/common/dialogs/approvedcolorpicker.controller.js#L22

Looks like a mistake to me.

**Comment by nul800sebastiaan** [comment]
Haha, who knows, it's been there since the inital commit. Should be removed for sure!

**Comment by dawoe** [comment]
Hi Lennard,

Looks like a mistake to me as well. It's in there since the file was created more than 4 years ago.

But Is this dialog actually used. I seems to load colors from a css file. But I can't think of where I have seen this being used in the core

Dave

**Comment by LennardF1989** [comment]
It's an interesting piece of code regardless, I think I would actually prefer having a CSS file for the list of colors, rather than a datatype on its own (for portability reasons).

**Comment by jannikanker** [comment]
When I remove it, everything seems to still work. PR incoming.

**Comment by jannikanker** [comment]
Look at me, making a right mess with branches of branches. But the actual, proper PR should be there :-D

**Comment by nul800sebastiaan** [comment]
Fixed in https://github.com/umbraco/Umbraco-CMS/pull/3156
