### ISSUE TITLE
MultiNodeTreePickerPropertyConverter hitting the database

### ISSUE THREAD

**Issue by enkelmedia** [umbraco/Umbraco-CMS#3153]
The new MultiNodeTreePickerPropertyConverter that uses UDIs to fetch IPublishedContent-items is hitting the database to get the int-id for a node which is slow.

In our tests this slows done our startpage with about 140ms.

Reproduction
------------
Insert a Multinode Tree Picker and use models builder to fetch the strongly typed content items.

### Specifics

Under the hood this line 
https://github.com/umbraco/Umbraco-CMS/blob/7355ba4b235a2ec9ad3cd61262a56673e5cf9ac3/src/Umbraco.Web/PropertyEditors/ValueConverters/MultiNodeTreePickerPropertyConverter.cs#L217

Will call Umbraco.Web.PublishedCache.XmlPublishedCache.PublishedContentCache.GetById(UmbracoContext, Boolean, Guid)

This will call 
Umbraco.Core.Services.IdkMap.GetIdForKey(Guid, UmbracoObjectTypes)

Which is hitting the database

### Expected result

There should be a cached version of the IdkMap that we can use for this? This cache should also live longer than for just one page request.

I could help out with a pull request but I'm not sure where to start.

**Comment by dawoe** [comment]
Hi @enkelmedia 

I think this is fixed by by PR #3025 which will be in 7.13

This is the related issue #3024 

Could you try to reproduce it on the latest source ?

Dave [Community Pull Request team](https://umbraco.com/blog/introducing-the-new-cpr-team/)

**Comment by enkelmedia** [comment]
Sorry! I'm on 7.12.3 and look at the lasted source when trying to debug.... let's close this for now and I'll re invoke if the issue is still there.
