### ISSUE TITLE
Add border around the colors from the approved color picker

### ISSUE THREAD

**Issue by BatJan** [umbraco/Umbraco-CMS#3159]
If there is no border around the color it looks a bit weird if white has been selected. In the image below it's what it looks like when labels are used but it's the same when labels are not being used making it even harder to see the white color - Then it just looks like there's a big weird gap between the colors.

![color-picker-before](https://user-images.githubusercontent.com/1932158/46494965-77d2b980-c814-11e8-9c1d-66a7fabfc0ba.png)

**Comment by nul800sebastiaan** [comment]
Fixed in https://github.com/umbraco/Umbraco-CMS/pull/3161
