### ISSUE TITLE
Add sorting to the history audit

### ISSUE THREAD

**Issue by kjac** [umbraco/Umbraco-CMS#3160]
When working on #2990 I noticed that the sort action isn't logged to any visible audit. It's logged... but you can't see it because it's logged to ID 0.

The way I see it, the sort action should log an audit to the history on the item whose child items have been sorted.

I'll submit a PR for this momentarily.

**Comment by nul800sebastiaan** [comment]
Fixed in https://github.com/umbraco/Umbraco-CMS/pull/3162
