### ISSUE TITLE
Don't overwrite the label name even though labels are disabled in the color picker

### ISSUE THREAD

**Issue by BatJan** [umbraco/Umbraco-CMS#3163]
This is a little nitpick on my part but I don't think it makes sense to reset the label names in the colorpicker depending on whether labels have been enabled or not.

If for some reason one starts out by adding labels, for whatever reason get's told to disable them and them enable them again it's just annoying that you need to re-add the labels again instead of just keeping them. It also feels a bit confusing that the value changes when you enable / disable. It's a small detail I know that but if there are no big consequences of keeping the label then I don't see why not :)

**Comment by nul800sebastiaan** [comment]
Fixed in https://github.com/umbraco/Umbraco-CMS/pull/3164
