### ISSUE TITLE
Button styling on inactive user profile

### ISSUE THREAD

**Issue by poornimanayar** [umbraco/Umbraco-CMS#3169]
Noticed that on an inactive umbraco user profile the "delete" button does not have a margin at the top
![beforeinactive](https://user-images.githubusercontent.com/3941753/46525901-b86a1b80-c884-11e8-860d-7a8a1885ed31.PNG)

**Comment by nul800sebastiaan** [comment]
Fixed in https://github.com/umbraco/Umbraco-CMS/pull/3170
