### ISSUE TITLE
Grid edit row configuration missing Allow all editors and other settings

### ISSUE THREAD

**Issue by Mivaweb** [umbraco/Umbraco-CMS#3175]
We are on a vanilla installation of Umbraco 7.12.3 where we are creating a new Grid Layout datatype.
When we are adding a new Row configuration we can see the properties of width and checkbox allow all editors. When we save and close the dialog and edit the configuration, the properties width and allow all editors is missing and so can't be changed.

![image](https://user-images.githubusercontent.com/13479920/46546787-651abc00-c8ca-11e8-8f8f-6a56d4cdae6a.png)

**Comment by bdsoko** [comment]
After clicking the row configuration that you want to modify, you must then click the column to view the additional options.

![2018-10-05_11-41-02](https://user-images.githubusercontent.com/11299552/46548101-b065a800-c893-11e8-9071-ddaf3651a3fc.png)

**Comment by Mivaweb** [comment]
OMG! Didn't see that one! Thanks!
