### ISSUE TITLE
Border showing on first dropdown button in a button-group

### ISSUE THREAD

**Issue by skttl** [umbraco/Umbraco-CMS#3176]
In the media section, where the create button is inside a .btn-group, a dividing border is visible on the first (and only) button in the group.

Should'nt this divider only be visible on consecutive btns?

![image](https://user-images.githubusercontent.com/3726467/46554683-5095ee00-c8e1-11e8-9073-acfab0d0d2a4.png)

**Comment by skttl** [comment]
Ah, it's because the divider should be used in a split button, where you have a main function for the button, and then a dropdown.

**Comment by nul800sebastiaan** [comment]
Fixed in https://github.com/umbraco/Umbraco-CMS/pull/3177
