### ISSUE TITLE
Learn Umbraco help list styling needs fixing

### ISSUE THREAD

**Issue by prjseal** [umbraco/Umbraco-CMS#3183]
A brief description of the issue goes here.

The styling of the Learn Umbraco help list needs to be fixed. The icon is out of line with the text

Reproduction
------------

In the backoffice, click on the help icon and see the Learn Umbraco list

### Bug summary

The styling of the Learn Umbraco help list needs to be fixed. The icon is out of line with the text

### Specifics

The styling of the Learn Umbraco help list needs to be fixed. The icon is out of line with the text

### Steps to reproduce

In the backoffice, click on the help icon and see the Learn Umbraco list

### Expected result

Should be inline with the text and padded

### Actual result

Icon is above the text and no padding

**Comment by nul800sebastiaan** [comment]
Fixed in https://github.com/umbraco/Umbraco-CMS/pull/3184
