### ISSUE TITLE
Sort dialog: Confirmation message looks a bit weird

### ISSUE THREAD

**Issue by kjac** [umbraco/Umbraco-CMS#3191]
When sorting is complete in the content tree, the confirmation looks rather odd:

![sort before](https://user-images.githubusercontent.com/7405322/46586823-2c264700-ca84-11e8-9932-f421281ace6e.png)

I'd expect it to be a lot more green and in line with the move/copy confirmation messages.

I'll submit a PR for this shortly.

**Comment by nul800sebastiaan** [comment]
Fixed in https://github.com/umbraco/Umbraco-CMS/pull/3192
