### ISSUE TITLE
Public access dialog: Some styling needed

### ISSUE THREAD

**Issue by kjac** [umbraco/Umbraco-CMS#3193]
The Public access dialog could use some TLC. See the following screenshots:

## First step in the dialog
![protect before 1](https://user-images.githubusercontent.com/7405322/46586910-46acf000-ca85-11e8-9b2a-c253d9785d7d.png)

## Second step in the dialog
![protect before 2](https://user-images.githubusercontent.com/7405322/46586912-4876b380-ca85-11e8-85c1-c05c7b9090ca.png)

## Confirmation
![protect before 3](https://user-images.githubusercontent.com/7405322/46586914-4ad90d80-ca85-11e8-8b50-765fe5b30a68.png)

I'll submit a PR momentarily.

**Comment by abjerner** [comment]
@kjac thanks for another good PR 👍

I will give your changes a spin, and report back, As you might already know, we strive to do this within 14 days - but hopefully I can do this in one of the following days ;)
