### ISSUE TITLE
Data updates when changing default languages

### ISSUE THREAD

**Issue by Shazwazza** [umbraco/Umbraco-CMS#3196]
child of https://github.com/umbraco/Umbraco.Private/issues/14

A continuation of the work done in https://github.com/umbraco/Umbraco.Private/issues/222

When changing a content type from variant to invariant we don't have to update all of the invariant names because we keep the invariant names in sync with the default language names. But If the default language is changed, this means that all invariant name values stored for variant content will be in the wrong language. 

We will need to run a bulk update statement when a default language is changed to copy all "name" data for any variant doc type to the invariant storage. This means that the invariant names will still be in sync with the variant names of the default language. (don't worry about property data, this is taken care of when changing a doc type from invariant/variant)

Bulk SQL Updates don't work in SQL CE but they do work in SQL Server (and probably MySql). An example is here: https://github.com/umbraco/Umbraco-CMS/commit/304c874006f35634101b81e024ee08372237411a#diff-d367ba2cc01d9cb6029082d5bae70f1fL606 but for SQL CE we need to do this row by row.

**Comment by nul800sebastiaan** [comment]
Looking at related issues this seems all done at the moment.
