### ISSUE TITLE
Issue with "Select editor" modal on document type

### ISSUE THREAD

**Issue by poornimanayar** [umbraco/Umbraco-CMS#3207]
- Go to any document type
- Create a new property
- Click "Select editor" to open the modal
- Notice that there is some css issues with the Available/Reuse tabs. The border at the bottom looks out of place.

I have noticed this in v7.13

![image](https://user-images.githubusercontent.com/3941753/46636880-bb4d6080-cb51-11e8-8a82-611a1fc73b74.png)

**Comment by nul800sebastiaan** [comment]
Fixed in https://github.com/umbraco/Umbraco-CMS/pull/3208
