### ISSUE TITLE
Sort hostnames in Culture and Hostnames dialog

### ISSUE THREAD

**Issue by skttl** [umbraco/Umbraco-CMS#3210]
This issue: https://issues.umbraco.org/issue/U4-11558

I'm working on a PR, where the dialog is changed to use angular.

**Comment by abjerner** [comment]
While this would be great, I don't think it is possible with just Angular, as the domains are saved in no particular order in the database. So I think you'll have to find a solution for that as well.

**Comment by skttl** [comment]
I know, so a foray into schema changes too :)

**Comment by ronaldbarendse** [comment]
Lets continue the discussion about how to solve this issue in https://github.com/umbraco/Umbraco-CMS/issues/8299 and close this, as it hasn't had a comment since 2018 and all related PRs are closed.

**Comment by nul800sebastiaan** [comment]
Continued in #8299, I'll close this one.
