### ISSUE TITLE
Add colorpicker prevalue editor in grid editor

### ISSUE THREAD

**Issue by bjarnef** [umbraco/Umbraco-CMS#3211]
Issue from old issue tracker https://issues.umbraco.org/issue/U4-9034

It would be useful to allow the color picker to be used in grid editor, e.g. for setting a background color on a row or cell. Furthermore it can be used in prevalues for other property editors.

**Comment by nul800sebastiaan** [comment]
Fixed in: https://github.com/umbraco/Umbraco-CMS/pull/3212
