### ISSUE TITLE
Create template from Document Type Editor

### ISSUE THREAD

**Issue by skttl** [umbraco/Umbraco-CMS#3215]
Just tried using the new document type collections feature, and it doesn't add templates for the new document types.

This means I have to go to the template section, create my template and save it. Then go back to my doc type, click templates, click choose template, find my newly created template and click save.

What if the templates page in the doctype editor, had an option to create a template?

So next to "Choose default template", an option named "Create template for this doctype" appeared. When clicked, a new template gets created, and set as allowed on the doctype.

![image](https://user-images.githubusercontent.com/3726467/46660080-90e1be80-cbb6-11e8-8fe1-368694581474.png)

**Comment by nul800sebastiaan** [comment]
Fixed in: https://github.com/umbraco/Umbraco-CMS/pull/3366
