### ISSUE TITLE
Set allowed parent node types

### ISSUE THREAD

**Issue by skttl** [umbraco/Umbraco-CMS#3216]
I'm pretty sure this was up on the old issue tracker, but can't find it.

When you add a new doctype, you have to go to each of the desired parent doctypes, and allow the new type as a child. This can be quite cumbersome.

What if you had the ability, the set allowed parent types, like you can set child types?

This should of course not change anything on the current doctype, but update the allowed child node types on the selected parent types.

![image](https://user-images.githubusercontent.com/3726467/46660033-73145980-cbb6-11e8-87b2-00f5dba1dcd9.png)

**Comment by HistoricEnglandDigitalTeam** [comment]
That is a good idea - I am also coming up with that issue. Is anyone working in this?

Would also be useful to set the ability to create a new page / document type use by parent content node (in the site tree) as well as by parent document type.

**Comment by nul800sebastiaan** [comment]
Hi @skttl - we have definitely heard this idea before and I had to check with the team why we never added this workflow. There's two main reasons:

1. In UX terms, this gets confusing very quickly - okay, you have link children and you also have linked parents, it gets difficult to see what exactly is linked to what. We think, however, that this is a great oppertunity for making a package to get a good overview of linked document types and possibly being able to link them easily (warning: avoid cyclical dependencies).
2. The second complication was the number of extra queries we'd need to do, as far as we can remember looking up the parents was a lot harder.

We feel that now that it's possible to create document type collections, this makes it a lot easier to create a pair of linked document types.
