### ISSUE TITLE
Document Type Collection not respecting heirarchy

### ISSUE THREAD

**Issue by DavePearcey** [umbraco/Umbraco-CMS#3217]
Creating a Document Type Collection as a child of another document type adds the collection to the root of document types, not under the parent.

### Reproduction

Create a document type. For example I have a master doc type.
Create a document type collection beneath it as a child.
Document type collection gets added to root of document types.

### Expected result

I would expect for the collection to respect the heirarchy and be placed as children.

**Comment by nul800sebastiaan** [comment]
Ah yes, seems like an oversight!

I've marked as "Up for grabs" so that you or someone else coming along could create a pull request for it.

**Comment by kjac** [comment]
@nul800sebastiaan I think you can close this one 😉

**Comment by nul800sebastiaan** [comment]
Thanks @kjac - seems like I forgot ;)
