### ISSUE TITLE
Validation error on templates when clicking "save" 

### ISSUE THREAD

**Issue by dzordzs** [umbraco/Umbraco-CMS#3219]
Reproduction
------------

Umbraco will throw a validation error if you create any template and click on Save. 

### Steps to reproduce
    * Got to the setting section and create a template 
    * Name it "master" for example 
    * Click on save
    * Validation error will pop up in the bottom of the page 

This only happens if you click the save button. Using shortcut (CTRL+S) won't give you this error. 
This has been tested on latest version 7.12.3.

**Comment by caseydierking** [comment]
I’d like to take a look at this one. I’ll get working on it!

**Comment by KimHolzmann** [comment]
Fix pulled
