### ISSUE TITLE
Suggestion: Style the default browser radio button as a custom one to provide a nicer UI experience

### ISSUE THREAD

**Issue by BatJan** [umbraco/Umbraco-CMS#3225]
So this is not really a bug but it did not really feel like a feature either. It's more meant as a suggestion to style the radio button list to have a more custom look and feel that aligns better with the backoffice UI in general instead of the default good ol' standard browser radio button.

I'll do a PR shortly showcasing the idea and I'm of course open for feedback and suggestions if what I have come up with needs tweaking or is simply not of interest - I just thought it was worth giving it a shot 😃

**Comment by nul800sebastiaan** [comment]
Fixed in: https://github.com/umbraco/Umbraco-CMS/pull/3226

**Comment by BatJan** [comment]
@nul800sebastiaan Thank you for the official update on this PR :-)

Please let me know if I can provide further assistant when a decision has been made. My initial thoughts about styling the radio and checkboxes was that I find the default browser ones a bit dull and boring but I understand HQ's reasoning for postponing the suggested change. I can see how it can seem a bit big all of the sudden and my only reason for that was that I wanted to align the UI in general since we now have the toggle, which I tried to align the controls with.

But they should probably be made smaller at least and then the radio control should probably not be using the checkmark icon since that's not what browsers naturally use. But be aware that the behvaior when tabbing through the controls using a keyboard is the same with my suggested implementation as it is with the default UI. By default it's not possible to tab through a series of radio buttons. The first or the last can be tabbed to (depending on whether you tab forwards or backwards) and then the arrow key's should be used to move back and forth between the options.

I will see if I can find some time to do a codepen with some other suggestions that are not so dominant 🤗

**Comment by nul800sebastiaan** [comment]
@BatJan Maybe you can get some inspiration from Microsoft, in Azure DevOps we have this for checkboxes:

![image](https://user-images.githubusercontent.com/304656/49137958-362f2e00-f2ee-11e8-9122-1e53be0ac674.png)

And for radio buttons:

![image](https://user-images.githubusercontent.com/304656/49137972-3e876900-f2ee-11e8-9de7-76368febca47.png)

I like that when radio buttons are not selected, they are slightly dimmed.

**Comment by nul800sebastiaan** [comment]
Yep green is great! It's fine to update the original PR, we can just squash the changes. Note: I still have this open for discussion at HQ soon, so this is just me making up stuff, I haven't heard back if it's something wel actually want, but it helps to have examples and inspiration. :-)
