### ISSUE TITLE
- no videos on the Members Get Started Dashboard

### ISSUE THREAD

**Issue by prjseal** [umbraco/Umbraco-CMS#3228]
A brief description of the issue goes here.

There are no videos on the members dashboard, but it says 'Hours of Umbraco training videos are only a click away' some more text and then it says 'To get you started:' and then there is just white space.

![Members Getting Started Dashboard](https://i.imgur.com/zB3TCuo.png "Members Getting Started Dashboard")

Reproduction
------------

Log in to backoffice, click on Members, in the getting started dashboard there should be videos.

**Comment by kjac** [comment]
Same problem in the developers section. 

Looks like [this commit](https://github.com/umbraco/Umbraco-CMS/commit/23fda3a0edd12e33ea8e24098077db8a5fe4a2df) added the www subdomain to the feed loaded in the members section (which breaks the default feedproxy.config rules), while [this commit](https://github.com/umbraco/Umbraco-CMS/commit/a1224da5e16f948962600c975a90ff98f386da67) doesn't let the feedproxy read feeds over HTTPS.

I'm cooking up a fix now.

**Comment by nul800sebastiaan** [comment]
Fixed in https://github.com/umbraco/Umbraco-CMS/pull/3256
