### ISSUE TITLE
Enable email address as macro parameter editor

### ISSUE THREAD

**Issue by bjarnef** [umbraco/Umbraco-CMS#3229]
I noticed we have simple property editors as e.g. boolean, textbox, textarea, integer/numeric and decimal, but not email address property editor. At the moment the macro parameter editors have the limitation of not being configurable (except from the default config of the property editor), so not sure if e.g. Date and DateTime also make sense to enable as macro parameter editor.

**Comment by nul800sebastiaan** [comment]
Fixed in https://github.com/umbraco/Umbraco-CMS/pull/3230
