### ISSUE TITLE
Rollback modal css rules to be moved into a new stylesheet

### ISSUE THREAD

**Issue by poornimanayar** [umbraco/Umbraco-CMS#3233]
The rollback modal was using a lot of inline styles which have been moved into a stylesheet with the PR [3202](https://github.com/umbraco/Umbraco-CMS/pull/3202) . However there was a suggestion that since the rollback modal will be angularised soon its better to have these css rules in a new stylesheet which can then be get rid off when we get to that point

**Comment by nul800sebastiaan** [comment]
Fixed in https://github.com/umbraco/Umbraco-CMS/pull/3234
