### ISSUE TITLE
Too many sections will not show the last one

### ISSUE THREAD

**Issue by Shazwazza** [umbraco/Umbraco-CMS#3237]
This is a bug in v8 where if there are too many sections, it won't show the last section and it won't show the drop down showing extra sections.

This is easy to reproduce:

* Go to the adminsitrators group, add Translation so that all sections are selected
* Log out and back in and you won't see Translation, but if you resize the window so it's small the drop down of sections will show including translations

**Comment by kjac** [comment]
@Shazwazza something must have fixed this in the meantime... I can't reproduce it on the latest codebase - look here:

![sections dropdown](https://user-images.githubusercontent.com/7405322/47518000-14273380-d88a-11e8-9bbd-b0bcc393a06f.gif)

**Comment by Shazwazza** [comment]
I'll have a look today :)

**Comment by Shazwazza** [comment]
Yup that does seem to be magically fixed :) i'll close this, thanks!
