### ISSUE TITLE
Error copying document type, when no target folder is selected

### ISSUE THREAD

**Issue by soreng** [umbraco/Umbraco-CMS#3241]
When copying a document type, the "copy" button is always enabled. By just clicking the button, the action starts to load/submit, but an error occours, so the action never completes.

Reproduction
------------

### Bug summary

Specifics
* Umbraco version: v7.12.3

Copy-button should not be enabled until a folder is selected

### Steps to reproduce

Copy a document type, but don't select a folder

### Expected result

Either an error saying "no folder selected" or an inactive button until a folder is selected

**Comment by kjac** [comment]
This issue isn't limited to document types. It's a general thing, happens in content as well. And also on move operations. There are also minor related issues in media.

I'll have a look at a fix.

**Comment by kjac** [comment]
So far I've found it in:

- Content move/copy
- Media move (although not so bad)
- Document types move/copy
- Media types move/copy

**Comment by kjac** [comment]
Also found in:

- Data types move

**Comment by nul800sebastiaan** [comment]
Fixed in: https://github.com/umbraco/Umbraco-CMS/pull/3250
