### ISSUE TITLE
DialogService Mediapicker does not remember last used folder.

### ISSUE THREAD

**Issue by gardarthorsteins** [umbraco/Umbraco-CMS#3242]
When using the Angular DialogService Mediapicker in a custom datatype the picker does not have the same functionality as the one used by Umbraco.

My main issue with it is that it does not remember what folder it has last opened so if web editor needs to select 5 images from a folder many levels down in the media library they will have to go through all the folders 5 times.

There does not seem to be an option to have it select multiple images.

Reproduction
------------

### Bug summary

Does not remember last opened folder.

### Specifics

Umbraco: 7.12.3
Browser: Chrome

**Comment by abjerner** [comment]
@gardarthorsteins the dialog service is actually deprecated, as it has been replaced by the `umbOverlay` directive instead (which was introduced in Umbraco 7.4 if I remember correctly).

The mediapicker overlay has various improvements compared to the dialog - including remembering the last used folder. You can see some examples on how to use the directive here:

https://our.umbraco.com/apidocs/ui/#/api/umbraco.directives.directive:umbOverlay

Hope that helps ;)
