### ISSUE TITLE
Update buttons on macro page to ensure consistency

### ISSUE THREAD

**Issue by bjarnef** [umbraco/Umbraco-CMS#3246]
On the macro page and a few other of the legacy pages left  in backoffice, some of the styles are not consistent with the rest of the backoffice.

It will be replaced at some point, but not sure if they will be removed/replaced before v8, so for now we can make it a bit more consistent with the rest of the backoffice UI.

Fixed in https://github.com/umbraco/Umbraco-CMS/pull/3247

**Comment by nul800sebastiaan** [comment]
Fixed in: https://github.com/umbraco/Umbraco-CMS/pull/3247
