### ISSUE TITLE
Make all confirmations and alerts look alike

### ISSUE THREAD

**Issue by kjac** [umbraco/Umbraco-CMS#3251]
The confirmation and alert appearance differ across sections within Umbraco. Generally it looks like they were updated at some point in the content section but not in the developer and settings sections.

I'm a sucker for consistency... so I'll submit a PR to fix this 😄 

## Here's what it looks like today:

![move before](https://user-images.githubusercontent.com/7405322/46785348-c52dba00-cd31-11e8-99a0-c34783b080be.png)

![create before](https://user-images.githubusercontent.com/7405322/46785352-c7901400-cd31-11e8-8653-a55dd5fd0bab.png)

## Here's what it ought to look like:

![image](https://user-images.githubusercontent.com/7405322/46785391-e8f10000-cd31-11e8-9dfc-ff58252bbe38.png)

![image](https://user-images.githubusercontent.com/7405322/46785377-dbd41100-cd31-11e8-914c-31766bb99944.png)

**Comment by nul800sebastiaan** [comment]
Fixed in: https://github.com/umbraco/Umbraco-CMS/pull/3252
