### ISSUE TITLE
Reinstate Login Screen Autocomplete Off

### ISSUE THREAD

**Issue by moriyamathomas** [umbraco/Umbraco-CMS#3257]
Several different security scans have complained that autocomplete=off should be set on the Umbraco backoffice login screen. Despite this no longer being supported by Chrome (see https://issues.umbraco.org/issue/U4-11321) - removing this attribute still causes problems with passing security scans.

**Comment by SteveVaneeckhout** [comment]
What's the reason for adding `autocomplete="off"` to a login form?

**Comment by nul800sebastiaan** [comment]
See comment on the PR: https://github.com/umbraco/Umbraco-CMS/pull/3258#issuecomment-431314612
