### ISSUE TITLE
Umbraco Examine NuGet Wrapper for MS Office Documents

### ISSUE THREAD

**Issue by Dariatj** [umbraco/Umbraco-CMS#3259]
In my site, we have lots of MS Office documents that are stored in the media gallery.  However, NONE of them are available to us for search as there is no Umbraco Examine NuGet package for MS Office Documents.  
There is an Umbraco Examine NuGet package for PDF which works great!  
Can you please create on for MS Office documents?

Thanks
Tom

**Comment by dawoe** [comment]
Hi @Dariatj 

This already exists as a seperate Umbraco package : https://our.umbraco.com/packages/backoffice-extensions/examinefileindexer/

Because it exists as package I will close this issue.

**Comment by Dariatj** [comment]
dawoe:

Thank you very much.
Just to be sure.  Will this package support .doc, .docx, .xls and .xlsx?

Tom

**Comment by Dariatj** [comment]
dawoe:

Many thanks for the tip.  
I installed the NuGet Package and configured it to work with .xls, docx and xlsx files.

Many thanks

Tom

PS Is there another package or documentation/instructions on how to include PDF meta data in the search index?
And is there another package or documentation/instructions on how to control the outcome of the search results?
