### ISSUE TITLE
Duplicate "Move" action when disabling inherited document types

### ISSUE THREAD

**Issue by rasmusjp** [umbraco/Umbraco-CMS#3262]
When disabling inherited document types by adding `<EnableInheritedDocumentTypes>false</EnableInheritedDocumentTypes>` to the `<content>` section in `umbracoSettings.config` you end up with two move actions in the document type context menu

<img width="383" alt="screenshot_20181011_190328" src="https://user-images.githubusercontent.com/379886/46823471-9134b200-cd8e-11e8-9aa4-0156a85f16e1.png">

**Comment by nul800sebastiaan** [comment]
Fixed in https://github.com/umbraco/Umbraco-CMS/pull/3261
