### ISSUE TITLE
Show/hide toggle icons doesn't work as expected

### ISSUE THREAD

**Issue by rasmusjp** [umbraco/Umbraco-CMS#3263]
According to the [documentation](/umbraco/Umbraco-CMS/blob/dev-v7/src/Umbraco.Web.UI.Client/src/common/directives/components/buttons/umbtoggle.directive.js#L60) you should be able to set `hideIcons` to either `true` or `false` on the `<umb-toggle>` directive to show or hide the icons. That doesn't work as the icons are always hidden no matter what the value of `hideIcons` is.

It can be reproduced by adding adding a `Checkbox` property editor to a document type and adding `hide-icons="false"` to `<umb-toggle>` in the [boolean](/umbraco/Umbraco-CMS/blob/dev-v7/src/Umbraco.Web.UI.Client/src/views/propertyeditors/boolean/boolean.html) property editor.

<img width="258" alt="screenshot_20181011_203044" src="https://user-images.githubusercontent.com/379886/46825720-98f75500-cd94-11e8-94dd-2b8603ef0b23.png">

I expect the icons to still be shown when `hide-icons="false"`

<img width="272" alt="screenshot_20181011_203057" src="https://user-images.githubusercontent.com/379886/46825745-a6144400-cd94-11e8-966c-1bf84cf69eec.png">

**Comment by nul800sebastiaan** [comment]
Fixed in https://github.com/umbraco/Umbraco-CMS/pull/3264
