### ISSUE TITLE
When only unpublish date is set default button should be "Save and publish"

### ISSUE THREAD

**Issue by ZNS** [umbraco/Umbraco-CMS#3267]
If a user sets unpublish date for a node but does not set a publish date, the default save button should be "Save and publish" and not "Save and schedule".  The scheduled action in this case is to "remove" the node at a certain date, but until that date all changes should be published by default, and not just scheduled to be removed.

How can you help?
-------------------------------
I'm not sure :)

**Comment by kjac** [comment]
PR in #3507

**Comment by nul800sebastiaan** [comment]
Fixed in https://github.com/umbraco/Umbraco-CMS/pull/3507
