### ISSUE TITLE
Index/Search PDF Meta Data NuGet Package

### ISSUE THREAD

**Issue by Dariatj** [umbraco/Umbraco-CMS#3270]
Hello:

I am on Umbraco 7.11.1 and I have set up search indexer for PDF documents.
All is well.   All of the PDF content is being indexed and search results are fine.
But my users want me to extract the metadata from the PDF documents and add those artifacts to search index.  On the Description tab of any PDF document there are placeholders for Title, Author, Subject, Keywords, Created, modified and Application.

Can you add this a future feature NuGet package for indexing/searching PDF metadata?  

Thanks

Tom

**Comment by nul800sebastiaan** [comment]
We don't have any plans to unclude a PDF analyzer at this point, you can try using the following package: https://github.com/umbraco/UmbracoExamine.PDF
