### ISSUE TITLE
Set media start node in usergroup or on user results in logging out.

### ISSUE THREAD

**Issue by KimHolzmann** [umbraco/Umbraco-CMS#3272]
As a non administrator, it's not possible to set media start node.
On click Add in Media start node section, the mediapicker overlay shows and the going to login screen.

Reproduction
------------

If you're filing a bug, please describe how to reproduce it. Include as much
relevant information as possible, such as:

### Bug summary

Set media start node in usergroup or on user results in logging out.
### Specifics

Umbraco version 7.13.0 assembly: 1.0.6859.27231
### Steps to reproduce

Create a user group with all permissions on but only access to the users section. 
Assign a new user to only that group. 
Log into that user and create a new user or group from it. 
Add media start node.

![image](https://user-images.githubusercontent.com/8200579/46902073-fedffb80-cebe-11e8-9ce7-8aab721c29d2.png)

### Expected result

![image](https://user-images.githubusercontent.com/8200579/46902185-0bfdea00-cec1-11e8-95a3-03945e16851f.png)

### Actual result

![image](https://user-images.githubusercontent.com/8200579/46902083-25059b80-cebf-11e8-9131-4441da4f439e.png)

**Comment by nul800sebastiaan** [comment]
This could be related to https://github.com/umbraco/Umbraco-CMS/pull/3111 as well.

**Comment by nul800sebastiaan** [comment]
This was the same issue as was fixed in #3111 
Please note, you can't give a user access to only the users section and expect to be able to set start nodes. If they don't have access to something you shouldn't be able to create a user with a higher level of access, that would be a privilege elevation problem.
