### ISSUE TITLE
Id/guid no longer visible on members

### ISSUE THREAD

**Issue by bjarnef** [umbraco/Umbraco-CMS#3275]
I have noticed that id/guid no longer is visible on members in e.g. v7.12.3, which it previously was. 

In v7.7.13 we had these properties in backoffice.

![image](https://user-images.githubusercontent.com/2919859/46910684-ab19f480-cf48-11e8-8131-c8c78e012efd.png)

But from v7.8.0 it seems these properties have been removed/hidden.

![image](https://user-images.githubusercontent.com/2919859/46910693-d13f9480-cf48-11e8-863b-cd38c2cd598f.png)

Not sure if this part has been removed/hidden as a part of the GDPR update (v7.9), but I wonder why the id/guid is hidden. The guid/key is visible in the url anyway, and you could potientially guess the id of a member (or just try enter different ids in the url - instead of the guid - if it returns a matching member you know the id of this member).

Besides that some other properties are also hidden/removed: "Created by", "Created" and "Last edited". However it is still allowed to see some other properties like "Last Lockout Date", "Last Login Date" and "Last Password Change Date".

![image](https://user-images.githubusercontent.com/2919859/46910712-693d7e00-cf49-11e8-9d38-7e699d9709c1.png)

**Comment by nul800sebastiaan** [comment]
Fixed in https://github.com/umbraco/Umbraco-CMS/pull/3279
