### ISSUE TITLE
Get multiple members via TypedMember

### ISSUE THREAD

**Issue by bjarnef** [umbraco/Umbraco-CMS#3276]
Imported from old issue tracker: https://issues.umbraco.org/issue/U4-8806

With Umbraco.TypedContent and Umbraco.TypedMedia you can pass in an single or multiple ids, e.g. Umbraco.TypedContent(1234, 5678) which returns an IEnumerable.

However Umbraco.TypedMember doesn't have an overload for this, only three overloads to get a member by id (string, int or object).

Is there a reason why not having these overloads, e.g. when using MNTP (member picker) it would be handle to get these member by passing ids separated by comma.

```
var contents = Umbraco.TypedContent(1234, 5678);
var member = (MemberPublishedContent)Umbraco.TypedMember(1234);
```

It would be great if TypedMember had similar signature like TypedContent to get multiple member based on e.g. id's from a member picker or from relations.

```
public IEnumerable<IPublishedContent> TypedContent(params int[] ids)
public IEnumerable<IPublishedContent> TypedContent(params Guid[] ids)
public IEnumerable<IPublishedContent> TypedContent(params string[] ids)
public IEnumerable<IPublishedContent> TypedContent(IEnumerable<object> ids)
public IEnumerable<IPublishedContent> TypedContent(IEnumerable<string> ids)
public IEnumerable<IPublishedContent> TypedContent(IEnumerable<int> ids)
```

At the moment UmbracoHelper only contains methods to get a single member at the time.

```
public IPublishedContent TypedMember(object id)
public IPublishedContent TypedMember(int id)
public IPublishedContent TypedMember(string id)
```

**Comment by bjarnef** [comment]
Update:

In lastest v7 codebase UmbracoHelper has 5 overload methods for TypedMember.

```
public IPublishedContent TypedMember(object id)
public IPublishedContent TypedMember(int id)
public IPublishedContent TypedMember(string id)
public IPublishedContent TypedMember(Guid id)
public IPublishedContent TypedMember(Udi id)
```

**Comment by kjac** [comment]
@bjarnef it looks like there is no application level cache for members. 

The `TypedMember()` methods on `UmbracoHelper` all end up accessing the database via `MembershipHelper` (e.g. [GetById](https://github.com/umbraco/Umbraco-CMS/blob/fb6079d4e2af45b151d466441ee6f63ff677d185/src/Umbraco.Web/Security/MembershipHelper.cs#L317)). The results are cached per request but not shared between requests.

The lack of application level cache isn't terribly obvious as is. But adding `params` overloads might make it even less obvious and more tempting to fetch more stuff from the database... or what?

I have no idea if this has been reworked for V8. If it has it would certainly make sense to add the `params` overloads in V8.

**Comment by bjarnef** [comment]
@kjac I think members and been a bit different from content and media, but the API is now more consistent than in the past.

For members I think it can be improved futher, e.g. when you want to fetch multiple members.
It might be tempting to use `MemberService` in the view to fetch multiple members since the `MembershipHelper` haven't have had methods to fetch multiple members. I guess a Umbraco.MemberPicker2 and with property value converters return `IEnumerable<IPublishedContent>>` and you can probably create a loop for some member ids/guids to lookup each member, but it would execute multiple SQL queries instead of just a single query.

I would be great to have these overload methods when just want to fetch a few members at once.

Recently I also noticed `MemberService` now have a few other methods, which wasn't documented.
https://github.com/umbraco/UmbracoDocs/pull/975 
but at the momemt `MembershipHelper` doesn't seem to offer methods to fetch multiple members like `UmbracoHelper` does for content and media.

**Comment by nul800sebastiaan** [comment]
Thanks @bjarnef - I'll close this one as this is available in v8.

![image](https://user-images.githubusercontent.com/304656/63169625-98c08980-c037-11e9-9d67-240437277721.png)
