### ISSUE TITLE
Change password button not hidden V8

### ISSUE THREAD

**Issue by UnitStack** [umbraco/Umbraco-CMS#3282]
When clicking the change password button on the backoffice users area, the button does not hide.

![user1](https://user-images.githubusercontent.com/5080289/46917917-f45b5a00-cfc3-11e8-99e8-a1e345e06f30.PNG)
![user2](https://user-images.githubusercontent.com/5080289/46917918-f4f3f080-cfc3-11e8-80b9-3111d8c83df1.PNG)

**Comment by Diginari** [comment]
PR incoming

**Comment by emmagarland** [comment]
I think this issue is fixed now by @Diginari merged PR?

Chrome browser it is hidden for me on latest release

![image](https://user-images.githubusercontent.com/1649855/48491279-1cd2b000-e81f-11e8-8174-275c048642bb.png)

**Comment by nul800sebastiaan** [comment]
Yikes, forgot to close, thanks!
