### ISSUE TITLE
Move rollback to Info app

### ISSUE THREAD

**Issue by madsrasmussen** [umbraco/Umbraco-CMS#3298]
We want to move rollback from the context menu so we at some point end up with menu items only related to the tree structure.

This will be a simple MVP for this functionality. In this version, we will add the rollback as a link to the audit trail. They won't be "merged". The functionality will be the same as the current dialog.

**Comment by madsrasmussen** [comment]
PR: https://github.com/umbraco/Umbraco-CMS/pull/3312

This PR moves the rollback dialog from the context menu to a button on the audit trail on the info app. The server side still needs to be wired up for this dialog.

How to test:
* Make sure you can open the rollback dialog from the audit trail
* Make sure you see a language selector in the dialog for nodes with variants. The active language should be preselected in the dialog.

**Comment by warrenbuckley** [comment]
@madsrasmussen so we have a related task for the serverside - or does this need to be added into this PR directly as well?!

**Comment by warrenbuckley** [comment]
UI all looks fine and is now just waiting the serverside intergration

**Comment by warrenbuckley** [comment]
OK so I have worked on the following: 
* C# WebApi Controller
* C# ContentService Rollback method implementation
* Remove legacy .aspx WebForms Rollback Dialog

Big thanks to Stephan for the help & pointers :)

@zpqrtbnk can you take a look at this when your free/have time to do a review & thorough test on this for me, please

**Comment by madsrasmussen** [comment]
See PR for test notes: https://github.com/umbraco/Umbraco-CMS/pull/3312
