### ISSUE TITLE
IPublishedContent Linq & HasCulture

### ISSUE THREAD

**Issue by zpqrtbnk** [umbraco/Umbraco-CMS#3305]
child of https://github.com/umbraco/Umbraco-CMS/issues/3661

When getting a document from the content cache with eg `cache.GetById(1234)`, we get the document "for all cultures" _but_ that document may actually not be available for the current culture.
We have an `HasCulture` method for this, which checks whether the content is avail for the current (or explicitely specified) culture.
That method should probably be used in many places in our Linq navigation, such as `Children()` or `Descendant()`, so that we do not return non-available documents.
Or, maybe we *want to* but then, we have to document that ppl need to filter? And maybe create an extension method filter `.WhereHasCulture()`?

**Comment by bergmania** [comment]
PR: #4096

**Comment by zpqrtbnk** [comment]
tests green, looks good - have fixed/changed a few things and un-commented tons of tests that had been commented - still all green - liking it - merged
