### ISSUE TITLE
Add XML comments for ImageCropMode values

### ISSUE THREAD

**Issue by skttl** [umbraco/Umbraco-CMS#3309]
When using the ImageCropMode enum in the GetCropUrl method, I would love to have a short description of each mode available in intellisense.

This is a quick fix with XML comments. PR coming :)

![image](https://user-images.githubusercontent.com/3726467/47014686-4b3f6b80-d14b-11e8-8dc4-0ffdc1fbea91.png)

**Comment by nul800sebastiaan** [comment]
Fixed in https://github.com/umbraco/Umbraco-CMS/pull/3310
