### ISSUE TITLE
V8 - Remove trees.config & load types only

### ISSUE THREAD

**Issue by warrenbuckley** [umbraco/Umbraco-CMS#3315]
The /config/trees.config XML file feels very legacy and uneeded.

It was mainly allowing users to reorder the trees or change some icons via this XML file.

Currently, this is not so well supported and I personally do not think it makes sense to give this level of control.

Trees have to be registered as C# classes, so it makes sense to remove the trees.config file and just retrieve the trees via the TypeManager/Plugin approach that we do for most things in the Core.

**Comment by Shazwazza** [comment]
If we do this, then we won't need to do this one: https://github.com/umbraco/Umbraco-CMS/issues/3236

**Comment by Shazwazza** [comment]
The PR is here https://github.com/umbraco/Umbraco-CMS/pull/4111/files

* No more trees.config or applications.config file
* A package.manifest can register a section (i.e. Forms could do this: `"sections":  { "forms":  "Forms" }` )
* OR a section can be registered in c# in a composer by doing this `composition.WithCollectionBuilder<BackOfficeSectionCollectionBuilder>().Append<ContentBackOfficeSection>()`
* Trees are just discovered based on the tree controllers that exist along with the metadata that is declared in their attributes, these are converted on startup to a simple singleton class called `Tree` and these can all be resolved from the `TreeCollection`

With these changes, the amount of code to delete was insane (insanely good!) and things are much simpler.

As a develoepr, it is possible to modify these trees/sections collections on startup if needed (i.e. to change the order, or tree section, etc... )

To test, make sure the build & tests is passing on Azure Devops, load the back office and make sure all the sections and trees are there and working

**Comment by zpqrtbnk** [comment]
reviewed and tested and all was ok - tests, backoffice - looks way nicer!

could not resist tweaking things... have aligned the manifest to other declarations, so now its
```
"sections": [
  { "alias": "forms", "name": "Forms" }
]
```

thinking this format is more future-proof if we ever want to add stuff to sections

hopefully that's ok, else hate me and we'll revert
