### ISSUE TITLE
301 redirects don't keep the QueryString

### ISSUE THREAD

**Issue by enkelmedia** [umbraco/Umbraco-CMS#3317]
I had a client that uses Google Ads and creates text ads, they started to notice that the "Paid Search" traffic in Google Analytics was not in line with the reports from Google Ads and after some investigation we came to the consultation that this is because a 301 redirect with the built in 301 redirects does not keep the query strings that Google Ads uses, ie

mysite.com/landing-old-page/?gclid=yadayadayadya would redirect to mysite.com/landing-new-page/

The same problem occurs if they for example sends out a newsletter and include a link to a redirected page with UTM query strings.

I'm not really 100% sure if the query strings should be kept in these scenarios but I wanted to raise an issue to discuss this. I don't see a big downside with keeping the query strings but there might be one?

Let's say that we keep the current way of doing 301 and just pass what ever query strings that comes in.

So the configured redirect i the "Redirect URL Manager" would be

**Original URL:** /information/
**Redirects to:** /about-us/

And then what every query strings that comes with the request is added to the redirect.

**Incoming request:** /information/?foo=yadayada&bar=yada
**Redirects to:** /about-us/?foo=yadayada&bar=yada

or

Incoming request: /information/?utm_campaign=summer2019&utm_source=newsletter
Redirects to: /about-us/?utm_campaign=summer2019&utm_source=newsletter

Is this a behavior that is wanted? In that case I'm open to work on a pull request but I want to make sure that this is something that we want in the core.

###Reproduction

- Create a new node and give it a name, ie "Test", save and publish
- Rename the node to "Testing", save and publish (this creates a redirect from /Test/ to /Testing/
- Go to /Testing/?foo=yada&bar=yada, the browser redirects to /Test/ without the query strings.

### Bug summary

My idea here is to add/keep the query string when building up the redirect here
https://github.com/umbraco/Umbraco-CMS/blob/1bb593d264a085f94a3ce3bd710392b350561430/src/Umbraco.Web/Routing/ContentFinderByRedirectUrl.cs#L47

### Expected result

- Create a new node and give it a name, ie "Test", save and publish
- Rename the node to "Testing", save and publish (this creates a redirect from /Test/ to /Testing/
- Go to /Test/?foo=yada&bar=yada, the browser should redirect to /Testing/?foo=yada&bar=yada and keep the querystrings from the incomming request.

**Comment by enkelmedia** [comment]
I do understand the idea with the automatic redirects and that's a great feature. The current implementation works great but the only thing that I'm proposing is to pass the query strings to the redirected page. 

It's a simple one line fix to ContentFinderByRedirectUrl.cs that checks if the current request has any query strings and then append them to the new redirect.

`url = string.IsNullOrEmpty(contentRequest.Uri.Query) ? url : url + contentRequest.Uri.Query;`

At the moment I've implemented this as a custom IContentFinder which works great but having this supported out of the box would of course be better. The editors would still not have to think about anything regarding this, the only difference would be that the incoming query strings are passed from the old url to the new redirected url.

**Comment by nul800sebastiaan** [comment]
🤦‍♂️

I seem to have completely misunderstood your request, yest this seems like a fine feature to add!

I've marked this as "Up for grabs" so that you or someone else coming along could create a pull request for it.

**Comment by enkelmedia** [comment]
I already have the code and it's been tested "in the wild" since I posted this so let me just get back with a PR for this =D
