### ISSUE TITLE
SQL syntax for creating unique index does not create a unique index

### ISSUE THREAD

**Issue by dawoe** [umbraco/Umbraco-CMS#3319]
I'm using migrations in a project to create custom database tables. I wanted to create a unique index using the sql syntax builder. But it doesn't create a unique index.

### Steps to reproduce

Create a migration that creates a table with a unique index using this syntax

```
 this.Create.Table("MyTable")
                .WithColumn("Id").AsInt32().Identity().PrimaryKey($"PK_MyTable")
                .WithColumn("Key").AsGuid().NotNullable().Unique("UK_MyTable_Key")
                .WithColumn("Name").AsString(255).NotNullable();
```

The table is not created with a unique index. But a normal (nonclustered) index.

When I look in the logs (loglevel needs to be DEBUG) I also see a non unique index being created

```
2018-10-17 15:09:08,886 Umbraco.Core.Persistence.Migrations.MigrationRunner: Executing sql statement 1: CREATE TABLE [MyTable] ([Id] INTEGER NOT NULL IDENTITY(1,1),
[Key] UniqueIdentifier NOT NULL,
[Name] NVARCHAR(255) NOT NULL)

2018-10-17 15:09:08,887 Umbraco.Core.Persistence.Migrations.MigrationRunner: Executing sql statement 2: ALTER TABLE [MyTable] ADD CONSTRAINT [PK_MyTable] PRIMARY KEY ([Id])

2018-10-17 15:09:08,888 Umbraco.Core.Persistence.Migrations.MigrationRunner: Executing sql statement 3: CREATE NONCLUSTERED  INDEX [UK_MyTable_Key] ON [MyTable]([Key])

```

The last statement should be 

`CREATE UNIQUE NONCLUSTERED  INDEX [UK_MyTable_Key] ON [MyTable]([Key])`

**Comment by dawoe** [comment]
Hi @Shazwazza 

As far as I can see the core doesn't use this method. But the database has unique indexes. These are probably created in the initial database setup which uses the schemahelper to create tables from POCO's

I see in another project the devs scripted the unique index in a migration by using Exexute.Sql() method.
Probably because of the same issue. 

Will have a stab it this week. I also think it always creates the index as non clustered.

Dave

**Comment by Shazwazza** [comment]
yup so if we don't use it in core then it's probably one of those methods that isn't completed. normally they are easy to fix 🤞

**Comment by dawoe** [comment]
Yep..expect a PR coming in.

**Comment by dawoe** [comment]
Created a PR that fixes the issue

**Comment by nul800sebastiaan** [comment]
Fixed in: https://github.com/umbraco/Umbraco-CMS/pull/3363
