### ISSUE TITLE
Suggestion: Align image cropper property editor UI with color picker and checkbox lists

### ISSUE THREAD

**Issue by BatJan** [umbraco/Umbraco-CMS#3324]
I noticed that the UI for defining crops on the image cropper property editor is a bit out of sync with the general look and feel of the backoffice.

Therefore I suggest to align it a little more with what the rest of the experience looks like. For instance when setting up a color picker or checkbox list.

This is what it currently looks like

![crop-prop-editor-before](https://user-images.githubusercontent.com/1932158/47109181-e1f45100-d24d-11e8-843d-7e707003afd3.gif)

**Comment by nul800sebastiaan** [comment]
Fixed in https://github.com/umbraco/Umbraco-CMS/pull/3325
