### ISSUE TITLE
Update font awesome to 4.7

### ISSUE THREAD

**Issue by ssougnez** [umbraco/Umbraco-CMS#3326]
Hello,

I'm currently creating a plugin to add font awesome icon in the RTE and I noticed that Umbraco 7.x is using Font Awesome 4.2. However, this version does not contain a lot of icons, unlike the version 4.7 that contains a lot more and is retro compatible.

Therefore, I think it would be interesting to update Umbraco to use the version 4.7 of Font Awesome. This version only adds icons and does not break the ones of 4.2, so it would not be a big task.

How can you help?
-------------------------------

If the idea is accepted, I can do it if no one has time to do so.

**Comment by readingdancer** [comment]
@ssougnez It sounds like a good idea, as long as it doesn't create any breaking changes, I suggest you just make a pull request if you have time to do it :)

**Comment by ssougnez** [comment]
@readingdancer I'm doing it right now but out of curiosity, I made a research. It seems that font-awesome is actually not used by Umbraco, icomoon is. 

Therefore, I was wondering if it would not be better to remove font-awesome from Umbraco ? Indeed, upgrading it to 4.7 would only allow plugin such the one I'm creating to use the new version but it could be the responsibility of the plugin to inject Font Awesome in the Umbraco page.

But I'm curious. How come font-awesome is included in the umb default page if it's not used? Is it legacy? Can it be removed?

**Comment by abjerner** [comment]
@ssougnez I'm not sure why it is part of Umbraco. But since it is there, there may be third party packages and solutions depending on it, in which case it would be a breaking change to remove it.

I think it's totally fine to update it to the newest version 😉

**Comment by ssougnez** [comment]
If you see that the other way, it also forces packages and plugins to use the version of font awesome referenced by Umbraco even though it does not use it.

For example, I'm writing a plugin that allow the user to insert a FA icon in the RTE. So at some point in time, he sees a list of FA icons. A developer would probably like to be able to define the version of FA to use as at the end, the icon must be displayed on the front end site where the developer can chose the version of FA to use, but because Umbraco references a specific version, the plugin will only be able to display the list of icon of the version used by Umbraco.

As you said, I don't risk anything by upgrading FA to 4.7 but I think it would be worst thinking about why it is included and maybe remove it in v8 if it has no utility.

**Comment by abjerner** [comment]
@madsrasmussen do you remember why Font Awesome was included with Umbraco? So far I've only been able to find this commit:

https://github.com/umbraco/Umbraco-CMS/commit/631a9f92eaa1281a96942bca960cde481d1817bd#diff-dba37d0ebb23dde29dae14021962d1efR33

**Comment by madsrasmussen** [comment]
I think the only reason we have font-awesome in the back-office is that the package bootstrap-social is depending on them. The social buttons are used for the custom buttons you can extend the login screen with.

**Comment by arknu** [comment]
If Umbraco is shipping with Font-Awesome already, why not make the icons available for use as doctype icons? If they are being loaded anyway, we might as well use them...

**Comment by ssougnez** [comment]
It appears that the "official" library used by Umbraco (if I'm not wrong) is icomoon. It would be weird to mix both libraries. However, as apparently FA is required by bootstrap social, there are two solutions (in my opinion):

- Use something else than bootstrap social to get rid of the FA dependency and remove it rom Umbraco
- Switch from icomoon to FA but I don't think it's possible. Indeed, it means that all people who used [this](https://nicbell.github.io/ucreate/icons.html) to create their plugins/packages/other will have to update them. So basically, I think that the first option is a more viable one.

**Comment by abjerner** [comment]
In theory, you can actually use Font Awesome for document types already - you are just not able to choose the icons via the UI. Font Awesome icons have a few issues though, as they are not perfectly centered etc.

Anyways, as Font Awesome 4.x is no longer in active development, I think it's fine to update it to version 4.7 for Umbraco 7, but perhaps remove it from Umbraco 8.

**Comment by ssougnez** [comment]
Okay then. I made this [PR](https://github.com/umbraco/Umbraco-CMS/pull/3344).

About your comment for centered icon, by default they are not, but you can add the class "fa-fw" to set a fixed width for the icon and therefore center it in the fixed width container. As I don't know icomoon, I can't suggest which one Umbraco should use but what's for sure is that it shouldn't use two different icon libraries.
