### ISSUE TITLE
Ensure ContentService.SaveAndPublishBranch follows the correct bulk publishing rules

### ISSUE THREAD

**Issue by Shazwazza** [umbraco/Umbraco-CMS#3336]
child of #3335

It is possible that this method already does what is intended but we need to verify that and change it if not:

* If the item being published is Invariant and it has Variant descendants and we are NOT forcing publishing of anything not published - the result will be that the Variant cultures that are already published (but may contain a draft) are published. Any cultures that don't have a published version are not published.
* If the item being published is Invariant and it has Variant descendants and we ARE forcing publishing of anything not published - the result will be that all Variant cultures are published regardless of whether they don't have any current published versions
* If the item being published is Variant and it 
has Invariant descendants and we are NOT forcing publishing of anything not published - the result will be that all Invariant documents are published that already have a published versions, regardless of what cultures are selected to be published
* If the item being published is Variant and it has Invariant descendants and we ARE forcing publishing of anything not published - the result will be that all Invariant documents are published regardless of whether they have a published version or not and regardless of what cultures are selected to be published

**Comment by zpqrtbnk** [comment]
PR #3519

**Comment by Shazwazza** [comment]
The PR has been merged upstream in to the sched publishing branch, all tests are passing so will close this ticket. Further review and testing will be done when I do the angular integration of bulk publish.
