### ISSUE TITLE
Add an Edit Link helper method

### ISSUE THREAD

**Issue by prjseal** [umbraco/Umbraco-CMS#3350]
As we have a clean slate with Umbraco v8, I feel it could be a good time to add this.

It would be great to have a helper method in UmbracoHelper.cs which you could call like this in your view

```
@Umbraco.EditLink(Model.Id)
```

And as a result it would render an edit link on the front end, if you are logged into the backoffice.
If you are not logged into the backoffice, then the link will not render.

It would not be added to people's Views by default. They would need to add it. 
The styling of this link can be overridden completely.

How can you help?
-------------------------------

I have built such a helper method. 
PR to follow shortly.

**Comment by nul800sebastiaan** [comment]
Ah, forgot to close this one :-)
