### ISSUE TITLE
Better UI for configuring settings and styles in a grid data type

### ISSUE THREAD

**Issue by skttl** [umbraco/Umbraco-CMS#3353]
When adding settings and styles options to a grid data type, you need to maintain a JSON object in a textarea. This is cumbersome and errorprone.

What I would suggest, is to use the UI from Nested Content to handle these things.

Then you could have an "add option" button, and a simple UI for setting label, description, key etc.

You could even have different types for the builtin views (textstring, textarea, radiobuttonlist, mediapicker, etc.) so ie. a prevalues field only were available when needed.

**Comment by nul800sebastiaan** [comment]
Thanks for the feature request, we'll discuss it at HQ and get back to you!

**Comment by nul800sebastiaan** [comment]
Thanks for the idea @skttl - after a chat at HQ we concluded that yes, your concern is legitimate and the good news is that we've worked on easily providing any property editor as a grid editor. You can follow (or help) the progress in this branch for "The Grid v2". 

https://github.com/umbraco/Umbraco-CMS/tree/temp8-grid2

**Comment by nul800sebastiaan** [comment]
Yep, that was part of the Grid2 work too!
