### ISSUE TITLE
API controllers don't respect specified domain culture

### ISSUE THREAD

**Issue by kjac** [umbraco/Umbraco-CMS#3356]
In a multilingual setup with different cultures specified for different domains, the routable requests are executed in the correct culture. 

This isn't the case for requests to API controllers, even if they're based on `UmbracoApiController`.

Consider this example:

- There are three cultures defined in Umbraco: "en-US" (the default one), "en-GB" and "da-DK".
- The content tree has three sites (three root nodes):
  - Site 1 has "mydomain.dk" assigned with "da-DK" as specified culture.
  - Site 2 has "mydomain.co.uk" assigned with "en-GB" as specified culture.
  - Site 3 has "mydomain.com" assigned with "en-US" as specified culture.
- The solution includes an API controller called `MyController` with the action `MyAction`.

When I call `MyController` from a page under Site 1 (`//mydomain.dk/umbraco/api/mycontroller/myaction`), I'd expect the action to be executed in context of the "da-DK" culture. 

When I call `MyController` from a page under Site 2 (`//mydomain.co.uk/umbraco/api/mycontroller/myaction`), I'd expect the action to be executed in context of the "en-GB" culture. 

However, none of the above happens. No matter which domain I call my `MyController` from, the action is always executed in context of the "en-US" culture. I'm not sure if it's due to the default "en-US" culture being the first available language in Umbraco or it's the server culture that is applied.

My current workaround is to apply the correct culture explicitly on the current thread in a base API controller. It works fine, but I really think it's something that should be handled by the core.

I'll submit a PR for this in a minute.

**Comment by nul800sebastiaan** [comment]
Closing this, see comment on the PR. 🙂
