### ISSUE TITLE
V8 Angular doesn't filter out ($)-properties when send to the server

### ISSUE THREAD

**Issue by madsrasmussen** [umbraco/Umbraco-CMS#3358]
In v7 angular filters out all properties prefixed with a $ when send to the server. It doesn't happen in v8 anymore.

We need to figure out why.

How to reproduce.
Create a node with a grid property editor. Fill in some content and save the node. You can see in the request sent to the server that a lot of grid config data it send and saved in the database.

**Comment by nul800sebastiaan** [comment]
I think this has been resolved by now, don't see any properties prefixed with $ going to the server.
