### ISSUE TITLE
Send to publish needs to include culture and not data when used with variant content

### ISSUE THREAD

**Issue by clausjensen** [umbraco/Umbraco-CMS#3360]
child of https://github.com/umbraco/Umbraco.Private/issues/243

When sending a variant item to publish with a specific culture, we need to include the culture name in the notification email.

We should remove the "changes" table when sending a variant to publishing since it will currently just show the invariant data of the item.

If possible we should add a link directly to viewing the variant from the notification email.

**Comment by Shazwazza** [comment]
@clausjensen  this is a duplicate of https://github.com/umbraco/Umbraco.Private/issues/231

**Comment by Shazwazza** [comment]
@clausjensen  this is a duplicate of https://github.com/umbraco/Umbraco.Private/issues/231

**Comment by Shazwazza** [comment]
@clausjensen  this is a duplicate of https://github.com/umbraco/Umbraco.Private/issues/231
