### ISSUE TITLE
Suggestion: Make use of confirm action directive on repeatable textstring when deleting

### ISSUE THREAD

**Issue by BatJan** [umbraco/Umbraco-CMS#3364]
So I played around with some of the built-in property editors and I noticed that when using the "Repeatable textstrings" property editor a minus sign icon is being used for visualize the delete option + it does not give the user a warning before deletion.

Therefore I suggest to impement the "umb-confirm-action" directive instead making use of a trashcan icon as it's done many other places in the UI.

This is what it currently looks like

![repeat-text-before](https://user-images.githubusercontent.com/1932158/47242072-04bd6b80-d3ee-11e8-9529-3c798cc68803.gif)

**Comment by nul800sebastiaan** [comment]
Fixed in https://github.com/umbraco/Umbraco-CMS/pull/3365
