### ISSUE TITLE
There is no dirty check on the allowed templates selector

### ISSUE THREAD

**Issue by skttl** [umbraco/Umbraco-CMS#3368]
Working with #3366 I noticed that if you have unsaved changes in allowed templates on the doc type editor, you don't get the usual "You have unsaved changes" popup.

Screen recording is from an installation of 7.12.3

https://i.imgur.com/g4CfMLe.gifv

**Comment by kjac** [comment]
Apparently this also applies to "Enable list view", "Allow at root" and "Allowed child node types"; in other words everything on these buttons, except the actual list view configuration:

![image](https://user-images.githubusercontent.com/7405322/47265858-9d5b0500-d52e-11e8-9589-1a97fcda08ef.png)

I'm going to submit a PR for it shortly.

**Comment by skttl** [comment]
Thanks @kjac!

**Comment by nul800sebastiaan** [comment]
Fixed in https://github.com/umbraco/Umbraco-CMS/pull/3372
