### ISSUE TITLE
Adding CleanCSS to the Belle build process

### ISSUE THREAD

**Issue by readingdancer** [umbraco/Umbraco-CMS#3370]
We have been using CleanCSS as part of our build processes and it has always reduced the final size of the CSS, it does a lot of cleaver things, merging styles, removing duplications etc.

I have already implemented this and it seems to be working fine, I will submit a pull request shortly, as long as my battery doesn't die ;)

**Comment by nul800sebastiaan** [comment]
Fixed in https://github.com/umbraco/Umbraco-CMS/pull/3371
