### ISSUE TITLE
Forms tree reports error when Forms is not installed

### ISSUE THREAD

**Issue by kjac** [umbraco/Umbraco-CMS#3373]
On a blank install (7.13.0), the Forms tree reports a 404 in the UI if Forms is not installed. 

To reproduce, simply open the Forms section of Umbraco:

![forms tree error](https://user-images.githubusercontent.com/7405322/47266130-78689100-d532-11e8-8d20-87dcc77193fe.gif)

The obvious workaround is to remove Forms from `applications.config` - or to install Forms (I'm going to assume that it works fine if Forms is installed, but I haven't tested it 😄). This is an acceptable workaround and should be done either way if you don't use Forms. But the error kinda makes Forms look bad for first time users, so I figured you'd like to know.

**Comment by nul800sebastiaan** [comment]
Seems like an oversight, it's because the forms section has no tree until it is installed. We obviously would love for the forms dashboard to pop up and have no errors, but prompting people to install Forms. :-)

**Comment by dawoe** [comment]
I just saw this in V8 as well

**Comment by dawoe** [comment]
And justed test this on 7.12.2. There the issue does not exist

**Comment by dawoe** [comment]
Did some digging. Could be this PR that caused it : https://github.com/umbraco/Umbraco-CMS/pull/2315

I see this code in V8 as well

**Comment by Shazwazza** [comment]
I don't think that PR was applied? There was already a fix for it in the core 🤔

**Comment by dawoe** [comment]
@Shazwazza 

I have been playing just now with that code in V8 to see if I can fix : #3419

And changing the check in the first if statement fixes #3419 

Will need to do some testing to see if there are any side affects. otherwise expect my first V8 PR coming.

Dave

**Comment by dawoe** [comment]
I created a PR that fixes this one

**Comment by Shazwazza** [comment]
@dawoe Your PRs say WIP, so are they still WIP or no?

**Comment by dawoe** [comment]
PR #3422 for this issue is ready for review and testing.

**Comment by dawoe** [comment]
For V8 I fixed this issue as part PR #3420
