### ISSUE TITLE
Content Apps doesnt' make sense to set permissions in manifest 

### ISSUE THREAD

**Issue by TimGeyssens** [umbraco/Umbraco-CMS#3376]
I assume if a package dev release a content app he doesn't know abou the doc type aliases available on the end users system, so why not make it a UI configurable setting instead of shipping that in the manifest...

**Comment by nul800sebastiaan** [comment]
Ah, I see that Stephane created the same issue, I'll leave that one open as it's on our sprint board and I'll close this as a duplicate, thanks Tim!
