### ISSUE TITLE
Incorrect swedish translation

### ISSUE THREAD

**Issue by DavidSigemo** [umbraco/Umbraco-CMS#3380]
When using the swedish translation the "selected" word is incorrectly translated (to danish, I think?)

Reproduction
------------

### Specifics

Change this line to "valda"

https://github.com/umbraco/Umbraco-CMS/blob/4cefd355ecd47104937555a2a9d01e9fc55267c7/src/Umbraco.Web.UI/umbraco/config/lang/sv.xml#L440

### Steps to reproduce

To reproduce, set Umbraco to Swedish and select an item in a list. 

### Expected result

The number that lists amount of items selected should say "1 av 6 valda".

### Actual result

It says "1 av 6 valgt".

------------
Personal note: I would have sent in a pull request myself, but GitHub is currently not letting me fork.

**Comment by nul800sebastiaan** [comment]
I've marked as "Up for grabs" so that you or someone else coming along could create a pull request for it.

**Comment by soreng** [comment]
@skttl I was just about to do that ...
