### ISSUE TITLE
Video heading shows when no videos are on the page

### ISSUE THREAD

**Issue by emmaburstow** [umbraco/Umbraco-CMS#3386]
When you're on the Member section of the back office, the video dashboard for Umbraco tv shows a heading 'To get started:' even when no videos are actually there to view.

**Comment by emmaburstow** [comment]
I've created a PR for this issue [here](https://github.com/umbraco/Umbraco-CMS/pull/3384)

**Comment by nul800sebastiaan** [comment]
Just noticed we forgot to close this one :)
