### ISSUE TITLE
MoveEventArgs.CancelOperation not showing notification in backoffice while cancelling MediaService.Trashing event

### ISSUE THREAD

**Issue by bharanijayasuri** [umbraco/Umbraco-CMS#3387]
While cancelling a MediaService.Trashing event, the notification message passed to the EventMessage constructor is not shown in the backoffice to the user even though the event is cancelled. Seen this behaviour on Umbraco 7.6.1 which was later upgraded to Umbraco 7.11.1 but the issue still remains.

Reproduction
------------

Create a MediaService.Trashing event handler and cancel the event using either by setting 

```
e.Cancel = true;
e.Messages.Add(new Umbraco.Core.Events.EventMessage("Test", "Media item cannot be deleted", Umbraco.Core.Events.EventMessageType.Error));
```

or

`e.CancelOperation(new Umbraco.Core.Events.EventMessage("Test", "Media item cannot be deleted", Umbraco.Core.Events.EventMessageType.Error));`

### Bug summary

Cancelling the MediaService.Trashing event in code does not show the notification message passed to the CancelOperation function in the backoffice.

### Specifics

**Umbraco**: Error observed in 7.6.1, 7.11.1
**Browsers Tested**: Chrome - Version 70.0.3538.67 (Official Build) (64-bit), Firefox Developer Edition - 63.0b14 (64-bit)

### Steps to reproduce

After creating the event handler in code, try deleting a media item. The code will cancel the delete operation. But the notification message is never shown in the backoffice. 

### Expected result

A red notification banner with the error message should be shown in the backoffice when the MediaService.Trashing event is cancelled in code with a cancellation message.

`{"notifications":[{"header":"Test","message":"Test message","type":2}],"message":null}`

The above response is picked up for a **ContentService.Trashing** cancellation from Chrome's developer console as an example for the expected result where the array shows the message passed to the CancelOperation function.

### Actual result

No notification message is shown and the response for the post request for the item results in 

`{"notifications":[],"message":null}`

The above response is picked up for a **MediaService.Trashing** cancellation from Chrome's developer console where the array is empty even though as message is passed to the CancelOperation function.

**Comment by nul800sebastiaan** [comment]
Can confirm neither `MediaService.Trashing` nor `MediaService.Moving` work with adding a message to the event.

I've marked as "Up for grabs" so that you or someone else coming along could create a pull request for it.

**Comment by abjerner** [comment]
@nul800sebastiaan I'm pretty sure we had a long discussion about this on the old issue tracker somewhere, but I can't find it now. Last time I checked the content service is affected as well.

While not being the issue I was thinking of, these appear to be the same issue:

https://issues.umbraco.org/issue/U4-9627
https://issues.umbraco.org/issue/U4-7958
https://issues.umbraco.org/issue/U4-5962

**Comment by kjac** [comment]
I had a look at something similar when I dug into #3253. It wasn't terribly trivial to fix it properly right now. And from what I saw it involved refactoring some stuff marked for removal in V8.

**Comment by NiklasWebnuts** [comment]
For me (using Umbraco version 7.12.3 assembly: 1.0.6837.12334), the `ContentService.Moving` also does not show messages correctly. However, `ContentService.Saving` work as expected. Not sure if these have anything to do with each other.

Does anyone have a workaround for this?
