### ISSUE TITLE
LICENSE info missing from the README file

### ISSUE THREAD

**Issue by akshatnitd** [umbraco/Umbraco-CMS#3388]
A brief description of the issue goes here.

* LICENSE info missing from the README file

Reproduction
------------

If you're filing a bug, please describe how to reproduce it. Include as much
relevant information as possible, such as:

### Bug summary

* LICENSE info missing from the README file

### Steps to reproduce
NA

### Expected result
LICENSE info should be present in the README file

### Actual result
LICENSE info absent from the README

**Comment by nul800sebastiaan** [comment]
Thanks, we have a LICENSE.md file in the root of the repo though, which is what GItHub recommends :-)

**Comment by abjerner** [comment]
GitHub also automatically detects the LICENSE.md file and shows the type of license in the UI. Clicking **MIT** will lead to the license file.

![image](https://user-images.githubusercontent.com/3634580/47306522-f27d4080-d62c-11e8-9b85-2ff5b062bb92.png)
