### ISSUE TITLE
Hide "Notifications" option in menu if Umbraco can't send system mails

### ISSUE THREAD

**Issue by kjac** [umbraco/Umbraco-CMS#3390]
Continuing along the lines of #3307 here... seems to me the "Notifications" option makes little sense if Umbraco can't send system mails. 

It should probably be removed if SMTP is not configured.

![notifications](https://user-images.githubusercontent.com/7405322/47311283-979e1600-d639-11e8-88e7-bc287933cd93.png)

**Comment by nul800sebastiaan** [comment]
Fixed in https://github.com/umbraco/Umbraco-CMS/pull/3392

**Comment by kjac** [comment]
I'll close this then 😁

**Comment by nul800sebastiaan** [comment]
Haha whoops, forgot, thanks!
