### ISSUE TITLE
Field labels are unaligned in the change document type dialog

### ISSUE THREAD

**Issue by kjac** [umbraco/Umbraco-CMS#3393]
Just noticed that the field labels are all raised above the field values and inputs in the "change document type" dialog.

![change doctype before](https://user-images.githubusercontent.com/7405322/47312292-3c215780-d63c-11e8-94f5-7a7a950fde76.png)

Looks like some local styling, I'll submit a PR to correct it momentarily.

**Comment by nul800sebastiaan** [comment]
Fixed in https://github.com/umbraco/Umbraco-CMS/pull/3394
