### ISSUE TITLE
Unpublish last variant for a node gives wrong notification

### ISSUE THREAD

**Issue by madsrasmussen** [umbraco/Umbraco-CMS#3395]
child of https://github.com/umbraco/Umbraco-CMS/issues/3695

When unpublishing the last variant of a node you get a notification which says a mandatory language has been unpublished so all variants have been unpublished. It is a bit misleading and it should just show the regular "variant has been unpublished" notification.

**Comment by clausjensen** [comment]
This seems to work as expected now.
Unpublishing the last variation shows a notification telling which variant was unpublished. Unpublishing a mandatory variant (and thereby also all other variants) shows the content item has been unpublished.
