### ISSUE TITLE
Stylesheet editing needs to be added

### ISSUE THREAD

**Issue by clausjensen** [umbraco/Umbraco-CMS#3399]
Stylesheets should be editable via the stylesheet tree in the backoffice.

This is where you were able to create styles such as H1, H2, H3, .whatever which were then added to a .css file with some indication markers to support editing this via the backoffice.

We want to change the way this works at some point, but for a MVP we need to just support the old syntax and the old way this worked.

These styles being managed here, are also what is used to apply styling in rich text editors (RTE).

**Comment by kjac** [comment]
PR for this in #3503
