### ISSUE TITLE
V8: dirty check doesn't span all edited variants when saving

### ISSUE THREAD

**Issue by kjac** [umbraco/Umbraco-CMS#3403]
If I edit content in two variants and hit save, I'm only prompted to save one of them (the currently active one). The dirty check simply doesn't work for the variants.

Example: 
![unsaved changes before 1](https://user-images.githubusercontent.com/7405322/47365069-0c755c80-d6db-11e8-9391-4e780f48f44c.gif)

...and for split view editing:
![unsaved changes before 2](https://user-images.githubusercontent.com/7405322/47365087-126b3d80-d6db-11e8-9925-86d3023bad70.gif)

I have tracked the bug down to [this line](https://github.com/umbraco/Umbraco-CMS/blob/temp8/src/Umbraco.Web.UI.Client/src/common/directives/components/content/umbvariantcontenteditors.directive.js#L197). It performs a clone of the variant as viewModel for the editor, thus decoupling it from the data being validated on [save](https://github.com/umbraco/Umbraco-CMS/blob/temp8/src/Umbraco.Web.UI.Client/src/views/content/overlays/save.controller.js#L21). 

I'll submit a PR in a few.

**Comment by Shazwazza** [comment]
See notes in PR: https://github.com/umbraco/Umbraco-CMS/pull/3404#issuecomment-432579259
