### ISSUE TITLE
There are many coding errors in the project.

### ISSUE THREAD

**Issue by hyzx86** [umbraco/Umbraco-CMS#3406]
Like this:

https://github.com/umbraco/Umbraco-CMS/blob/3e14da5e9db70b9fdf7c61209f71c94194874671/src/Umbraco.Tests/Routing/ContentFinderByNiceUrlTests.cs#L128

I don't know why. 
I cann't build this version in my vs 2017

**Comment by nul800sebastiaan** [comment]
Hi @hyzx86 - I am not sure what you mean, this has worked well for years on all our machines and build servers. It seems to be something on your computer (sorry). 

I would recommend heading to the forum at https://our.umbraco.com and starting a topic with specific error messages etc.

Please note that you should ONLY build Umbraco if you're planning to contribute to it, you don't need to build Umbraco just to use it as a CMS. 🙂

**Comment by hyzx86** [comment]
Thank you for your  reply!
I'm going to learn the framework of Umbraco, so I hope can start learning it with source code.

On my computer out cloning code can not be run directly. maybe is charset or file coding problem,
But I get code from other project is no problem.
