### ISSUE TITLE
Improve accessibility of notifications

### ISSUE THREAD

**Issue by BatJan** [umbraco/Umbraco-CMS#3408]
I'm currently working on an internal presentation on the subject of accessibility and during my research I was reminded about the use of aria-live regions that let's a screen reader know about changes on a page like when a notification is being displayed upon publishing a node.

Therefore I suggest to add the aria-live region attribute to the ul, which will make the screen reader read the error message text. I also suggest changing the currently used <a> tag being used to call the remove method is refactored into a more appropiate <button> element as well as hiding the &times; entity for screen readers so it's not being read out loud at any time since it does not make sense in a non-visual content to have the screen reader start the message saying "times", "Publish: About this...". It should only read out the error message.

I got a PR coming up for this in a moment 😃

**Comment by nul800sebastiaan** [comment]
I'll close this one for now as the PR is closed, let me know if you're working on this for v8 then I can re-open this one again! 👍

**Comment by BatJan** [comment]
Yes, no problem - I will recreate this on for v8
