### ISSUE TITLE
Content type service doesn't support getting the content type containers at the root level

### ISSUE THREAD

**Issue by abjerner** [umbraco/Umbraco-CMS#3411]
**Disclaimer:** I'm not 100% certain that it's not currently possible - I just haven't found a proper way to do it. Incidentally I was trying to write some documentation for the content type service, as there isn't any.

The content type service has the `GetContentTypeContainers` method for either getting *all* containers or child containers of one or more specified parents.

Technically I could do something like as below:

    contentTypeService.GetContentTypeContainers(new int[0]).Where(x => x.ParentId == -1);

...but that feels a bit wrong. I also tried the following - but to no avail:

    contentTypeService.GetContentTypeContainers(new int[] {-1});

IMO there should be a method that returns all root level containers without the need for an additional `.Where` as shown in my example.

As the content type tree is listing root level containers, I had a look that, but the implementation here is using the entity service rather than the content type service:

https://github.com/umbraco/Umbraco-CMS/blob/dev-v7/src/Umbraco.Web/Trees/ContentTypeTreeController.cs#L34

**Comment by nul800sebastiaan** [comment]
It would be easy to write a convenience method for it `GetContentTypeContainersAtRoot` but I'm not entirely sure what the use case is, why would I only want the ones at root?

**Comment by abjerner** [comment]
Not sure. It just seems wrong that it isn't possible. I haven't had a use case for it though, as I was just writing documentation for the content type service ... but writing *getting content type containers at the root level is not possible* doesn't sound like the right solution.

**Comment by nul800sebastiaan** [comment]
Just writing nothing is easier then! ;-)

But in all seriousness, if there's anything that has a good usecase, I'd love to hear. Can't think of any either though. 🙂

Let's start with not adding it, see if people read the documentation and then request the need for a method like this! 

Closing for now, we can always re-open it if needed.
