### ISSUE TITLE
Rich Text Editor in grid sometimes fails to expand to display all of its text.

### ISSUE THREAD

**Issue by jaandrews** [umbraco/Umbraco-CMS#3413]
### Bug summary

Sometimes the rich text editor fails to display its content on the initial load in the back office. Clicking inside it to start editing causes the content to show, but the content can't be seen until doing so.

### Specifics

**Umbraco:** 7.12.3
**Browser:** Chrome 70

I'm not 100% sure of the cause, as the issue is erratic, but I did notice the following warning with a potential cause that originated from **/umbraco/lib/tinymce/tinymce.min.js?umb__rnd=837eebc9b1814ffc7f3dbfc537a63e8c** when I was able to reproduce it.

> Active resource loading counts reached to a per-frame limit while the tab is in background. Network requests will be delayed until a previous loading finishes, or the tab is foregrounded. See https://www.chromestatus.com/feature/5527160148197376 for more details

I assume this happens because a large number of rich text editors are used in the page, which is causing chrome to delay loading of some of the resources (the page I reproduced the issue on had 14 rich text editors in the grid).

### Steps to reproduce

To reproduce, I just refreshed the page until the problem occurred again. A larger number of rte instances would likely make this easier to reproduce.

### Expected result

A rich text editor in the grid with text that is visible without having to interact with it.

### Actual result

A rich text editor that appears empty at first. The content becomes visible after clicking inside it to start editing.

**Comment by nul800sebastiaan** [comment]
I think that was just fixed in https://github.com/umbraco/Umbraco-CMS/issues/3231 🙂

**Comment by jaandrews** [comment]
Yeah looks like it. Thanks for letting me know.
