### ISSUE TITLE
Macros - create/edit/delete needs to be angularized

### ISSUE THREAD

**Issue by clausjensen** [umbraco/Umbraco-CMS#3417]
As part of the task to get rid of webforms and legacy stuff was to simply delete things and then discover what was missing - the legacy views for macros are gone.

We need to reimplement the functionality in angular so you can create, edit and delete macros in v8.

**Comment by dawoe** [comment]
Can we rebuild this from the webforms still present in V7 ?

Than I would like to have a stab at it.

Dave

**Comment by clausjensen** [comment]
Hi @dawoe !

Yes - we are not looking to change any of this functionality currently, so basically it is a matter of making it work in angular instead - similar to how the functionality was in v7.

It would be awesome if you are willing to take a look at it!

**Comment by dawoe** [comment]
What is the timeframe this needs to be finished ?

**Comment by zpqrtbnk** [comment]
Support for these legacy macros has been deprecated. The XSLT engine, or the legacy Razor engine, have been entirely removed from the codebase. As in, they just cannot run anymore. So - to answer your question: no.

**Comment by dawoe** [comment]
Was hoping for that answer. Trying to finish up a package now and after that I will start on this one

**Comment by dawoe** [comment]
Just looking through to code I need to touch. I see there is already a MacroController in the Umbraco.Web.Editors namespace. https://github.com/umbraco/Umbraco-CMS/blob/temp8/src/Umbraco.Web/Editors/MacroController.cs

This is used for rendering macro's in the backend and requires session state. I would prefer to keep the api methods for editing macro's separate. Should I rename this controller ? This would need some refactoring in the angular components that already use this one.

Or should I created a new controller for the editing...eg MacroEditingController

My personal preferences would be to rename the existing controller to something like MacroRenderingController. And name the new one MacroController to be inline with other parts of the backoffice

@zpqrtbnk @clausjensen @Shazwazza would love some input

**Comment by clausjensen** [comment]
Hi @dawoe 

Sorry for the late response. As you mention yourself, I would also prefer we stick to the naming convention we have so the name should be `MacroController` for the controller actually allowing you to do CRUD for macros.

I also agree on separation of concerns, so having a separate controller for rendering as HTML, getting parameters and whatnot that isn't really part of the macro CRUD actions.

As for naming - I think we're okay with `MacroRenderingController` .. it seems appropriate for what it's used for 😃

**Comment by clausjensen** [comment]
@dawoe Hope you had a great Christmas holiday! - did you get around to looking at this one during the holidays or should we consider it open still?

**Comment by dawoe** [comment]
@bergmania why is this closed ? I'm almost done on the work
