### ISSUE TITLE
Document type collection labels are not placed correctly

### ISSUE THREAD

**Issue by BatJan** [umbraco/Umbraco-CMS#3421]
So I noticed that the labels for the toggle buttons when creating a document type collection are placed a little weird. So I'll create a PR to fix this in a minute 😃 

This is what it currently looks like
![labels-before](https://user-images.githubusercontent.com/1932158/47438567-0484ed80-d7ab-11e8-84d4-fd85c61e9c84.jpg)

**Comment by madsrasmussen** [comment]
Hi @BatJan,

In my opinion, we should swap these toggles to be checkboxes. I think that toggles should only be used for settings and for something that will "stay the same" when you return to it again. I think checkboxes should be used for selection and confirmations.

**Comment by BatJan** [comment]
Hi @madsrasmussen 

I actually think that you're right - I have been meaning to start a small discussion about when to use toggles and when to use checkboxes. Only created this issue because @nul800sebastiaan kindly asked if I would have a look at the labels looking a bit awkward currently.

So I would like to suggest that we make a checkbox that looks a bit prettier than the default browser checkbox and I will be happy to make an example of what I'm thinking and then help out doing checkboxes where it's more appropiate than toggles and vice versa.

I'll visualize what I have in mind with checkboxes shortly 😃

**Comment by BatJan** [comment]
@madsrasmussen - If you take a look at the "before" gif I inserted in this PR https://github.com/umbraco/Umbraco-CMS/pull/3464 you can see what I have in mind. Do you agree on this or should I tweak it a bit? 😃 

If you like what you see then I'll update this PR to reflect this change instead and then later on do a PR, which makes it easier to reuse the styled checkbox in the future by making a directive for it.

**Comment by BatJan** [comment]
@madsrasmussen Any thoughts on this one? 😃

**Comment by nul800sebastiaan** [comment]
Closed as it is no longer relevant (see #3485).
