### ISSUE TITLE
does umbraco support openid connect  hybrid flow

### ISSUE THREAD

**Issue by GSingha** [umbraco/Umbraco-CMS#3424]
Hi, 
I am implanting SSO for my Umbraco application by ForgeRock OpenId Connect(hybrid flow). I am using UmbracoDefaultOwinStartup. Already I had implement the SSO for the front-end with global custom authentication filter(I am note sure its the right way or not).  I was trying to implement the SSO for the back office by removing the from authentication, unfortunately after a long struggle I am not able implement this. So I just bypass the SSO authentication for back-office by some logic in my custom authentication filter and then for back-office running on from authentication.  Everything is working with this workaround but the preview is not working as in our master page we show logged in user details and in preview those information are not available (as we by pass the SSO authentication). So to fix this issue i have to implement the SSO in back office as well. I spend lot of time for this but did not get any solution.
Now my Question are
1. Can we implement SSO (openId connect hybrid flow) for back office and front office?

More details: https://our.umbraco.com/forum/umbraco-forms//94322-openid-connect-hybrid-flow-in-umbraco-front-and-back-office  
any suggestion/help  will be appreciated.  Ican share more details once require.

Thanks!

**Comment by Shazwazza** [comment]
I have replied on the forum
