### ISSUE TITLE
V8: You accidentally open split view editing when changing variant language

### ISSUE THREAD

**Issue by kjac** [umbraco/Umbraco-CMS#3427]
Let me just start by saying: Split view editing is so frikkin' awesome!

However. When you want to change variant language, you way too often click the "Open in split view" link by accident - simply because the link appears *right there* under the language dropdown. You explicitly have to move the cursor to the left, clear of the link, to change variant language.

Amazing feature or not, "Open in split view" is still a secondary action in the variant language selector (I assume, considering how it only appears on hover and to the far right).

![split view toggle before](https://user-images.githubusercontent.com/7405322/47453979-496e4b80-d7ce-11e8-84c5-ff97959cc184.gif)

Another issue is how the "Open in split view" link text only shows on hover. When you're on a touch device, you click it without even seeing the link text, and you end up in split view editing for no apparent reason.

![split view toggle before device](https://user-images.githubusercontent.com/7405322/47454171-d9ac9080-d7ce-11e8-860e-dbe519f99eb3.gif)

I've got a suggestion for a fix - will submit a PR momentarily.

**Comment by nul800sebastiaan** [comment]
Closed for now until we can figure out a really good solution for this, suggestions welcome but at the moment we can't think of anything better :-)

**Comment by markadrake** [comment]
First and foremost, I'm not a fan of links being hidden and I don't think that's an appropriate UI/UX pattern. Even if we don't iterate now, somebody should update the CSS so **"Open in split view** is always visible.

![image](https://user-images.githubusercontent.com/713355/56448501-b8d87a00-62dd-11e9-85c6-a2fd9d08e25b.png)

One way we might make this friendlier is by reducing the target area for the split view link. For instance – use an icon! The target area for mouse and touch could be 52 x 52 pixels. When it comes to the extra text "Split View" I consider a progressive enhancement approach - show on hover, don't show at all on touch devices. As an example:

![image](https://user-images.githubusercontent.com/713355/56449169-fb04ba00-62e3-11e9-8f4a-f61cbd39f837.png)

[Adobe XD Link](https://xd.adobe.com/view/59487143-8c0c-4f23-7667-2e4633f5f894-2f79/)
