### ISSUE TITLE
Cannot change password of user in backoffice using Edge

### ISSUE THREAD

**Issue by raulribeiro** [umbraco/Umbraco-CMS#3440]
Cannot change password of user in backoffice using Edge, email required
Umbraco version 7.12.3 assembly: 1.0.6837.12334

https://user-images.githubusercontent.com/6097393/47494686-2aad9a80-d84a-11e8-8933-20a030cda3ee.png

**Comment by nul800sebastiaan** [comment]
Seems related to this one? https://github.com/umbraco/Umbraco-CMS/issues/3071

**Comment by kjac** [comment]
I think I've found the cause of this... will submit a PR sometime later or this weekend.

Curious note: It works fine in V8. Maybe it's an angular version issue. But the fix I've found should work fine in V8 as well.

**Comment by kjac** [comment]
Fix in #3456

**Comment by nul800sebastiaan** [comment]
Fixed in https://github.com/umbraco/Umbraco-CMS/pull/3456
