### ISSUE TITLE
When resetting member password the web.config setting 'passwordStrengthRegularExpression' is not used.

### ISSUE THREAD

**Issue by ArnoldV** [umbraco/Umbraco-CMS#3442]
When setting a passwordStrengthRegularExpression on the 'UmbracoMembershipProvider' key in web.config the MembershipProviderBase.ResetPassword function does not use this to generate a password for the member, therefore the user is unable to reset a members password in the backend.

Reproduction
------------
### Specifics

- Umbraco 7.12.3

When setting a passwordStrengthRegularExpression on the 'UmbracoMembershipProvider' key in web.config the MembershipProviderBase.ResetPassword function does not use this to generate a password for the member (https://github.com/umbraco/Umbraco-CMS/blob/396b499e8134be75ae97e9a9da57ecf816e76c22/src/Umbraco.Core/Security/MembershipProviderBase.cs#L560). The ValidatePassword however does use this regularexpression for the validation (https://github.com/umbraco/Umbraco-CMS/blob/396b499e8134be75ae97e9a9da57ecf816e76c22/src/Umbraco.Core/Security/MembershipProviderBase.cs#L589), therefore you are unable to reset the member password via the backend.

The 'problem' is that the default .net Membership 'Membership.GeneratePassword' function simply does not have an overload for the regex. This can be fixed by overriding the create password functionality (    public override string GeneratePassword()).

Reproduction
### Steps to reproduce

- Set something like 'passwordStrengthRegularExpression="^(?=.*?[A-Z])(?=.*?[a-z])(?=.*?[0-9])(?=.*?[#?!@$%^&amp;*-]).{8,}$"' to 'UmbracoMembershipProvider' key-line in web.config

### Expected result

- Resets the member password using this regex

### Actual result

- Shows error that password cannot be changed

**Comment by nul800sebastiaan** [comment]
I haven't looked into this yet, but are you sure it's because of the regex? We also have this problem: https://github.com/umbraco/Umbraco-CMS/issues/3015

Personally, I'd recommend not setting complexity rules at all but make the password requirement to be 12+ character passwords. That prevents people from coming up with ways around the regex that are too easy: `PasswordAugust2018`. 

Regexes also often frustrate password managers (which generate pretty good passwords by default. hopefully). Anyway! Just some thoughts!

**Comment by ArnoldV** [comment]
> I haven't looked into this yet, but are you sure it's because of the regex? We also have this problem: #3015

That problem is Users, this is Members, but yes it's the regex: See my lines I reference in the issue, you can easily figure out why this breaks from them.
 
> Personally, I'd recommend not setting complexity rules at all but make the password requirement to be 12+ character passwords. That prevents people from coming up with ways around the regex that are too easy: `PasswordAugust2018`.
> 
> Regexes also often frustrate password managers (which generate pretty good passwords by default. hopefully). Anyway! Just some thoughts!

Agree on length instead of complexity, but then we should remove the regex check from the validation ;)

**Comment by nul800sebastiaan** [comment]
I'm a little pre-occupied (https://twitter.com/cultiv/status/1055438929162313734), so I'm sorry I didn't see it was members! ;-)



Cool, I'll have a proper look at this next week!

**Comment by nul800sebastiaan** [comment]
I agree, also, I would advise to not use all those `Require` ones, except for length. :-)

Thanks very much @Shazwazza for the explainer here (yay, legacy). I'll close this issue as the amount of work to be able to support this doesn't justify the benefits of using a regex for passwords at this point.
