### ISSUE TITLE
Add an option to keep the mini profiler active

### ISSUE THREAD

**Issue by kjac** [umbraco/Umbraco-CMS#3458]
The mini profiler is an excellent tool for catching performance issues during early development.

Unfortunately you need to invoke it explicitly for each request you make (by adding `umbDebug=true` in the query string). Personally I'm guilty at not doing that often enough, and I'm guessing I'm not the only one with a bad conscience here 😄 

Therefore I think it'd be awesome to have an option to keep the mini profiler active across all requests instead of having to explicitly invoke it. I'm sure it'll be helpful for devs to continuously be able to keep an eye on the performance.

PR incoming 😁

**Comment by nul800sebastiaan** [comment]
Whoops, not sure why this is still open? It was added to 8.1.0.
