### ISSUE TITLE
Suggestion: Make checkboxes look prettier in checkbox lists

### ISSUE THREAD

**Issue by BatJan** [umbraco/Umbraco-CMS#3463]
So I have been thinking about making the default browser styled checkboxes look a bit prettier like we did with the default radio buttons so improve the look and feel of the backoffice UI 😃 

I will create a PR for this shortly and if it's being well received I will be happy to implement the checkbox in other areas where checkboxes are being used as well.

**Comment by poornimanayar** [comment]
Hi @BatJan ,

Can you add some screenshots of the suggested change?

Poornima
