### ISSUE TITLE
List views bulk actions - confirmation dialog

### ISSUE THREAD

**Issue by Shazwazza** [umbraco/Umbraco-CMS#3469]
child of #3329

When selecting multiple items in the list view and choosing publish or unpublish:

* Launch a dialog
* If only invariant selected then no culture selection
* If only variant is selected then there will be a culture selection
* If both variant/invariant is selected then there will be a culture selection and any invariant items are just published

This also means that this dialog is used as a confirmation before performing the operations

**Comment by madsrasmussen** [comment]
See #3470 for test notes
