### ISSUE TITLE
Public access protection dialog rebuilt in angular

### ISSUE THREAD

**Issue by clausjensen** [umbraco/Umbraco-CMS#3474]

**Comment by kjac** [comment]
@clausjensen when you do this, would you pretty please reconsider the "Single user protection" option? It really works weird (borderlining broking) in V7.

**Comment by clausjensen** [comment]
@kjac Yep I agree it is a bit weird (and not the best implementation either). I don't really know how many actually use it, as most sites I've seen had requirements that fit better with role based protection anyways. It is prolly more a legacy thing that we have just kept there.

I'll keep it in mind when we spec out the tasks for this first bit - whether we could possibly get rid of that option or if it should stay until we look deeper into the whole public access part for V8.

Thanks for highlighting it though! 😃

**Comment by kjac** [comment]
PR in #3868
