### ISSUE TITLE
v8 ContentApp config beyond manifest

### ISSUE THREAD

**Issue by zpqrtbnk** [umbraco/Umbraco-CMS#3476]
At the moment content types & roles for content apps are configured via the package manifest - but these manifests are distributed with packages and should not change (else upgrading is a pain) - so we need to support another file (package.manifest.user?) which can override the original package manifest.

**Comment by zpqrtbnk** [comment]
(maybe duplicate of [#3376](https://github.com/umbraco/Umbraco-CMS/issues/3376))

**Comment by Shazwazza** [comment]
I don't think this task needs to be done because once we implement User Group permissions with Content Apps, then this would not need to be done at all, i don't think adding custom .user files is a good option.

**Comment by zpqrtbnk** [comment]
no need to implement if we think we won't need it eventually - happy to close

**Comment by nul800sebastiaan** [comment]
Remember to remove the release if something is not going to be in that release.
