### ISSUE TITLE
Cleanup & simplify migrations

### ISSUE THREAD

**Issue by zpqrtbnk** [umbraco/Umbraco-CMS#3482]
Someone (ahem zpqrtbnk) has refactored migrations so they are way more stable, clean and deterministic. Problem is, they seem to be quite hard for anyone to understand, so either we simplify or refactor or document or something.

**Comment by dawoe** [comment]
Add first glance it looks very complicated, but after spending some time in there I think i got.

This is my "reading" of the code :
- Migration attribute is gone
- Order and which migrations need to run is now determined by migration plan
- Chain adds a migration to the plan. The guid is to keep track of which migrations have been run
- Add will allow you to run a migration only if another one has previously been executed ? Not sure about this one.
- From just for keeping state ?

I think the all the guids make it confusing to me

**Comment by dawoe** [comment]
I think how it is now the UmbracoPlan can become quite messy when we have next versions of V8. Or should we just worry about the first V8 version for now 😸

**Comment by nul800sebastiaan** [comment]
Work on this has completed.
