### ISSUE TITLE
Localized naming of doctypes is not working in nested content doctype selector overlay 

### ISSUE THREAD

**Issue by frederikreher** [umbraco/Umbraco-CMS#3483]
A doctype name prefixed with # should be translated using the corresponding dictionary item. This is also the case in general, except in the nested content overlay. 

![Non translated doctype names](https://i.imgur.com/0RExXoK.jpg)

The error seems to be in this specific file: https://github.com/umbraco/Umbraco-CMS/blob/1bb593d264a085f94a3ce3bd710392b350561430/src/Umbraco.Web/PropertyEditors/NestedContentController.cs

In line 20 the name of the doctype is returned directly instead of attempting to translate. The NestedController should translate the names, similarly to the way the [ContentTypeController ](https://github.com/umbraco/Umbraco-CMS/blob/df1c4faeb96b5538ccae8cd8dbb6d2c7b14fad37/src/Umbraco.Web/Editors/ContentTypeController.cs) (e.g. line 360) translates them.

**Comment by frederikreher** [comment]
I've submitted a [pull request](https://github.com/umco/umbraco-inner-content/pull/41) for the same issue on the [inner-content](https://github.com/umco/umbraco-inner-content) repo.  The approach to fix this in core should be similar.

**Comment by nul800sebastiaan** [comment]
Thanks @frederikreher - I see you've introduced a new method there but I'm sure there's already methods in Umbraco for that somewhere, other things do this translation already. So if you can find those (sorry, I have no pointers at the moment) then we'd love to see a PR for this as well! 👍

**Comment by kjac** [comment]
@frederikreher I can fix this in the core if you're not up for it yourself.

**Comment by kjac** [comment]
I'll give this a go 😄

**Comment by kjac** [comment]
PR in #3696

**Comment by frederikreher** [comment]
@nul800sebastiaan Since its a method that libraries like [inner-content](https://github.com/umco/umbraco-inner-content)  could benefit from i think it would make sense to increase the visibility of the method. As now each plugin requiring doctype translation, should implement a similar method themselves.
