### ISSUE TITLE
UpdateSortOrder does not work and does not log any error.

### ISSUE THREAD

**Issue by cmwalolo** [umbraco/Umbraco-CMS#3484]
We have a persisting issue on a node with +/- 100 children items. We can't sort any more those children.
I tested on a fresh copy of Umbraco 7.12.3 without any customization and the sorting is working. 
But in our application it is not, there is no error message, and nothing in the logs that states an error.

**Comment by nul800sebastiaan** [comment]
Sorry @cmwalolo - I do this all the time on our.umbraco.com and it works (156 child nodes currently). So it seems there is something in your custom logic causing the failure.

If you have any steps to reproduce the problem on a fresh install of Umbraco then we'd be all ears!

**Comment by cmwalolo** [comment]
Hi @nul800sebastiaan ,

I'm sorry but if the sorting is failing, and doesn't give any error message, it doesn't log anything, it is an issue.  It even breaks after a few seconds of processing, so it has no time to do anything with the publishing as it could take much longer time, and even if the source could be in our publishing flow, It doesn't explain why it is working nicely when doing a publish node by node, or a publish with children.

So better logging is not an option :-)

Thank you

Laurent

**Comment by nul800sebastiaan** [comment]
I'm also sorry @cmwalolo - if I can't reproduce it and you can't reproduce it then we really need to find a way to make it fail. I don't know what is going on in that one site of yours so I also have no idea where to add better logging.

Additionally, I haven't seen any reports like this, so it seems to be a very isolated incident.

> So better logging is not an option :-)

I don't think I said anything about logging? I mentioned maybe reviewing your custom logic.

**Comment by cmwalolo** [comment]
The sorting in the back end is not custom code. If I apply some ordering, and I receive a message that my content has been sorted, and that nothing happened. We can assume that the function didn't worked as expected, and it should have been logged and reported as failing ! So even if the issue is on our custom logic, the Failure happens when sorting content, and nowhere else.

**Comment by nul800sebastiaan** [comment]
I understand but it seems related to your custom code since this can not be replicated. Maybe it's not, no idea. 

The point is: if it can't be reproduced, it can't be fixed. 🙂

I would encourage you to head on over to [the forum](https://our.umbraco.com) and see if someone can help you debug this further.
