### ISSUE TITLE
Possibility to delete users with content

### ISSUE THREAD

**Issue by ZNS** [umbraco/Umbraco-CMS#3490]
We have a production site where we recently got exceptions when viewing media nodes and content nodes in umbraco. Turned out there were references to non existing users in the "cmsDocument" and "umbracoNode"-tables. Somehow a user was able to delete an old user to whom the content referenced. The umbraco installation was created some years ago when umbraco 7 was just released, and the deleted user was a user that hadn't been active for several years either.

My guess is that the deleted user was a bit active in the beginning. Later as umbraco updated it made it possible to delete this user.

I have no idea how to reproduce this, just wanted to give you a heads up. I've fixed the issue by replacing the user reference in the tables mentioned above.

**Comment by nul800sebastiaan** [comment]
Hi @ZNS - this duplicates issue: https://github.com/umbraco/Umbraco-CMS/issues/2920
