### ISSUE TITLE
Add a new property "tooltip" to the tabs

### ISSUE THREAD

**Issue by poornimanayar** [umbraco/Umbraco-CMS#3492]
Create a property called "Tooltip" for tabs. This property can be set in the  EditorModelEventManager.SendingContentModel

**Comment by nul800sebastiaan** [comment]
Fixed in: https://github.com/umbraco/Umbraco-CMS/pull/3493

**Comment by nul800sebastiaan** [comment]
As discussed this change has been reverted after some HQ feedback, https://github.com/umbraco/Umbraco-CMS/commit/06db9d22237b35014c9b1c250e0634ad91314f12
