### ISSUE TITLE
Using dropdown.flexible on a member saves empty string when set on mandatory.

### ISSUE THREAD

**Issue by Frost117** [umbraco/Umbraco-CMS#3500]
### Bug summary

I was made aware that if you create a new member-type which uses the umbraco.dropdown.flexible, as a mandatory property, then you would be able to save this new member without selecting anything from the dropdown.

Here is what is happening: if anything hasn't been picked then it would save the member with an empty string in the dropdown property. This would satisfy the property, as it technically has a value saved on the member. 

### Specifics
Version of Umbraco: 7.12.3
Browser: Chrome, Firefox and Internet Edge.

Images:
![image](https://user-images.githubusercontent.com/32164310/47850777-affaf700-ddd6-11e8-8145-b8cf5f5024b2.png)
![image](https://user-images.githubusercontent.com/32164310/47850799-cc972f00-ddd6-11e8-8756-b15cfce76063.png)

### Steps to reproduce

1. Create a new member-type.
2. Assign it the property of the dropdown editor and make sure it is on mandatory.
3. Give the dropdown editor at least 1 prevalue.
4. Save the new membertype.
5. Create a new member using the newly created membertype.
6. Fill out the necessary information for this new member, except mandatory dropdown.
7. Save the member.
8. Find the new member in the membersection and see that the dropdown property is still on the empty string.

### Expected result

I would have expected that it gave me a validation error as the user who created the member has not picked anything in the dropdown property.

### Actual result

It saved the member just fine. 
There is no error messages that popups to help identify what is going on.

**Comment by kjac** [comment]
Bad news. This is a problem on documents as well. I'm looking into it now.

**Comment by cheeseytoastie** [comment]
Doh! Wish I'd spotted that. I've just tested your changes and they work a treat for this issue.
