### ISSUE TITLE
Flickering on the datatype selection screen

### ISSUE THREAD

**Issue by poornimanayar** [umbraco/Umbraco-CMS#3506]
Steps to reproduce

1.  Go to any doc type
2.  Add a property and try to set a datatype
3.  Try to select a dataype towards the bottom of the dialog.
4.   A flicker can be noticed where the ribbon which denotes the datatype you are hovering on overlaps with a datatype beneath it.

I have tried to capture this in a gif. 
![umbraco-datatypeselection-flicker](https://user-images.githubusercontent.com/3941753/47922271-8dd4a800-deae-11e8-851a-138d0d864f2c.gif)

Reproduction
------------

If you're filing a bug, please describe how to reproduce it. Include as much
relevant information as possible, such as:

**Comment by kjac** [comment]
@poornimanayar I've got at fix for this. I'll push a PR soon :)

**Comment by bjarnef** [comment]
I have noticed this happens as well in media  section when hover the info icon on a media item at bottom of the page in grid listview layout.
