### ISSUE TITLE
Slider Labels does not position correctly if not visible at init

### ISSUE THREAD

**Issue by nielslyngsoe** [umbraco/Umbraco-CMS#3512]
If you use a Umbraco.Slider in a tab, which is not the first tab. Labels will not be placed correctly until an interaction has been made.

![image](https://user-images.githubusercontent.com/6791648/48054888-94b13280-e1ae-11e8-8575-0513aed38595.png)

**Comment by kjac** [comment]
Seems to be a known issue with the slider component... see for example https://github.com/seiyria/bootstrap-slider/issues/396

**Comment by nul800sebastiaan** [comment]
Looks like we'll need to wait for a fix in the dependency.

**Comment by nul800sebastiaan** [comment]
I believe weve updated the Slide component since then AND in v8 we don't have tabs, closing for now. :)
