### ISSUE TITLE
View member group results in error

### ISSUE THREAD

**Issue by SkullcrusherNZ** [umbraco/Umbraco-CMS#3520]
Have upgraded from 7.10.4 to 7.12.4 and when I go to view member groups I receive a Server Error.

Not sure when this started as i don't go into that page very often so could have been from a previous upgrade.

It's not just happening on my existing member groups but also if I create new ones.

The detailed error including stack trace is below.

![membergrouperror](https://user-images.githubusercontent.com/25328682/48089470-73614c80-e269-11e8-962d-d1a37fb53819.png)

**Comment by nul800sebastiaan** [comment]
Hey @SkullcrusherNZ, unfortunately for you this is not the experience most people have. I would suspect something in your upgrade didn't complete.

I'd recommend you drop a question on the forum about it to see if someone can help you out with this: https://our.umbraco.com
