### ISSUE TITLE
Moving multiple media items not working

### ISSUE THREAD

**Issue by SergioMSCosta** [umbraco/Umbraco-CMS#3521]
When trying to move multiple selected media items into a folder, nothing happens.

Reproduction
------------

Select multiple media items, select Actions -> move and select a folder. Then try to move them. No message comes up and nothing happens.

**Comment by kjac** [comment]
@SergioMSCosta the items in the "Actions" menu apply to the currently selected item - in your case probably the folder containing the images. 

It does seem to work on the latest code base. But again, it isn't the selected media, that is being moved, it's the entire folder (the currently selected item):

![move media folder](https://user-images.githubusercontent.com/7405322/48117628-17e38e80-e26a-11e8-8f84-834fef3dcd43.gif)

**Comment by SergioMSCosta** [comment]
Got it. There's no way to move selected media then, I guess?

**Comment by kjac** [comment]
No, not as a bulk operation. You have to move them one by one in the tree, or from the "actions" menu on the individual media items.

**Comment by SergioMSCosta** [comment]
Thanks, man. I'll close this then.
