### ISSUE TITLE
Get Examine dashboard working with updated Examine lib + variants

### ISSUE THREAD

**Issue by Shazwazza** [umbraco/Umbraco-CMS#3533]
The Examine dashboard will need to be fixed to work with the new changes to Examine and how we will be indexing variants

Requires https://github.com/umbraco/Umbraco.Private/issues/194
child of https://github.com/umbraco/Umbraco-CMS/issues/3530

**Comment by zpqrtbnk** [comment]
did the same thing as the demo and... hitting two issues:

First, the External Index has `PublishedValuesOnly` set to `false`, whereas the Internal Index has it to `true`. Shouldn't it be the other way round? As a consequence, a draft document only shows in the External Index at the moment.

Second, draft documents don't show in the index until I rebuild it. Then, I can get them all right. But until I rebuild, nothing happens.

**Comment by zpqrtbnk** [comment]
has been fixed, second issue linked to 1st
