### ISSUE TITLE
Update search controller to deal with variant index data

### ISSUE THREAD

**Issue by Shazwazza** [umbraco/Umbraco-CMS#3534]
The search controller will need to be updated to support search/retrieval of that data. Since we are indexing all variant data into one document, we will need to do some interesting searches:

* determine all languages installed with content
* build a query to query all variant/invariant fields that we need to in the back office (currently it's really just name/id ... of course id is always invariant). This means we'll use the installed languages to build the query, for example: `+(name: hello en_US_name: hello es_ES_name: hello)`
* The search result will use the default language name value to be displayed or the invariant name value if it's invariant
* The link will link to the default language if the document is variant

requires https://github.com/umbraco/Umbraco-CMS/issues/3536
child of https://github.com/umbraco/Umbraco-CMS/issues/3530

**Comment by Shazwazza** [comment]
PR: https://github.com/umbraco/Umbraco-CMS/pull/3852

Testing notes:

* This PR is for  #3805 too
* There is also an angular routing fix in here which ensures that the required query strings are always there (i.e. when clicking on a search result, it would clear the mculture query string but it will be retained now)
* Review code and notes in code and notes in commits
* Create both variant/invariant content, make sure the variant content language names are different from each other for the same node (i.e. Home, Casa, Maison)
* Do a search on each name and results should be there for each (but note the above, the response will be the default language values)

**Comment by zpqrtbnk** [comment]
code review = ok
tested ok, can create both variant and invariant and query (but response is default lang)
merging PR
