### ISSUE TITLE
Ensuring search can be extended for specific languages by developers

### ISSUE THREAD

**Issue by clausjensen** [umbraco/Umbraco-CMS#3535]
We are indexing all variant data into one document and each column will contain different variant data. i.e. `en_US_name`. With this in place developers can use their own implementation of a `PerFieldAnalyzerWrapper`where they can define which analyzer to use for which field/culture.

This would be the most basic/rudimentary way that a developer can extend this functionality so it might be best if we can have our own implementation of `PerFieldAnalyzerWrapper` that can be modified on startup to include different analyzers.

Ideally, the indexes that we ship with are not config based and instead codebased and if developers want to extend them they would do so via startup code.

**don't review until #3534 is reviewed and merged**

depends on #3534
child of https://github.com/umbraco/Umbraco-CMS/issues/3530

**Comment by Shazwazza** [comment]
To extend a developer can do this:

_NOTE: The syntax for components may be changing shortly so this might not be exact at the time of release_

```cs
public class MyComponent : UmbracoComponentBase 
{
    public void Initialize(IExamineManager examineManager)
    {
    	CustomizeIndexFields(examineManager);
    }

    private void CustomizeIndexFields(IExamineManager examineManager)
    {
        //This will update ALL indexes that are Lucene based, if you only want to update
        // a single index, then get the index with examineManager.TryGetIndex
        
        foreach(var umbIndex in examineManager.Indexes.OfType<LuceneIndex>())
        {
            //Add value type (IIndexValueType) - there are several built in but it's possible to create any custom one 
            // it's responsible for several indexing and searching operations
            //In this example we'll re-use the FullTextType which is the standard type to do full text searches.
            //Create a value type called "BrazilianFullText" of type FullTextType with whatever analyzer you choose, 
            // such as the "BrazilianAnalyzer" in this example.
            umbIndex.FieldValueTypeCollection.ValueTypeFactories.TryAdd("BrazilianFullText", 
            	fieldName => new FullTextType(fieldName, new BrazilianAnalyzer()));
            
            //Add a field definition for the "title" field for the brazilian variant with a value type of "BrazilianFullText"
            umbIndex.FieldDefinitionCollection.TryAdd(new FieldDefinition("title_pt-br", "BrazilianFullText"));
        }
    }
}
```

**Comment by Shazwazza** [comment]
Have added the ability to configure a DirectoryFactory for all Lucene based indexes created via code as an appSetting which will need to be used on Cloud, example:

```xml
<add key="Umbraco.Examine.LuceneDirectoryFactory" value="Examine.LuceneEngine.Directories.SyncTempEnvDirectoryFactory" />
```
