### ISSUE TITLE
The template saves when I click outside the name field

### ISSUE THREAD

**Issue by RobertCopilau** [umbraco/Umbraco-CMS#3537]
When creating a new template, if the user were to click in the editor before saving the template the intended way (save button or shortcut), a save call will be triggered.

How to reproduce:
* Create a new template
* Click anywhere the template editor 

Affected versions 7.11.x -> latest

**Comment by nul800sebastiaan** [comment]
I don't think this is an actual bug, when you don't enter a name, a save doesn't get triggered and everyone is happy. Closing this one 👍
