### ISSUE TITLE
Remove ITemplate reference from IContent

### ISSUE THREAD

**Issue by Shazwazza** [umbraco/Umbraco-CMS#3544]
child of #3543

We have a direct reference on `IContent` to `ITemplate`, instead we should just have `int TemplateId`. This will help reduce the object graph size of `IContent`

This means that if a developer needs the `ITemplate` reference they will need to use the `IFileService` to lookup the `ITemplate`

**Comment by StefanoChiodino** [comment]
I've worked on this during the UK fest hackathon, PR incoming.

**Comment by zpqrtbnk** [comment]
Is PR https://github.com/umbraco/Umbraco-CMS/pull/3583

**Comment by bergmania** [comment]
@zpqrtbnk, Yes

**Comment by zpqrtbnk** [comment]
All tests green. Something weird in `ContentController` - reviewing.

**Comment by zpqrtbnk** [comment]
happy, merged
