### ISSUE TITLE
Remove IContentType reference from IContent (REOPENED)

### ISSUE THREAD

**Issue by Shazwazza** [umbraco/Umbraco-CMS#3545]
child of #3543

We have a direct reference on `IContent` to `IConentType`, instead we should just have `int ContentTypeId` (this already exists on IContentBase IIRC). This will help reduce the object graph size of `IContent`. 

This means that if a developer needs the `IContentType` reference they will need to use the `IContentTypeService` to lookup the `IContentType`

This is going to be quite a huge change because there are LOTS of usages of `Content.ContentType` in the codebase

see notes in #3543 for why this could help alot

**Comment by bergmania** [comment]
@Shazwazza, what do you think we should do about (un)publishing content. Here the `Content `class itself uses the `ContentType` model.

We could refactoring all this into a `IContentPublishingService` and let that inject the `IContentTypeService `.
Otherwise we have to inject the IContentTypeService into `Content` in some way.

**Comment by Shazwazza** [comment]
@bergmania can you link to the line of code you are referring too? We defo don't want to inject any services into models. If we can try to keep logic out of models we should so this might be a case of refactoring what is happening within the model to be moved to the service

**Comment by bergmania** [comment]
https://github.com/umbraco/Umbraco-CMS/blob/temp8/src/Umbraco.Core/Models/Content.cs#L354-L425

**Comment by Shazwazza** [comment]
aha! Yup this is going to make for some interesting refactoring. One way to work around this for now - as a 1st step - is to pass in the IContentService to this method and use that to lookup the content type.

These APIs that work with culture/variants/publishing/unpublishing are part of a review that will be taking place with @zpqrtbnk, @clausjensen and myself (and you! since you're actively looking at this stuff).

**Comment by zpqrtbnk** [comment]
PR is https://github.com/umbraco/Umbraco-CMS/pull/3638

**Comment by bergmania** [comment]
New PR with a class with more informaiton than just the Id.
PR: https://github.com/umbraco/Umbraco-CMS/pull/3945

**Comment by zpqrtbnk** [comment]
reviewing PR #3945... tests all green, site works, code review... has issues.

v8 has a `ContentTypeService` and a `MediaTypeService` meaning that depending on whether an `IContentBase` is an `IContent` or an `IMedia` we should get `contentTypeService.Get(item.ContentTypeId)` or `mediaTypeService.Get(item.ContentTypeId)`.

And it's the same for members and member types.

And, for instance in `PublishedSnapshotService`, `content.GetContentType()` was getting the proper one - now it only relies on `_contentTypeService` and therefore NuCache will fail on media items.

Similarly in many other places we inject the content type service, but not the media type service, in places (properties...) which can be used by content, member or media.

Thoughts?

**Comment by bergmania** [comment]
@zpqrtbnk I have created a new `IContentTypeBaseServiceFactory` to create the correct `IContentTypeBaseService` based on the type of `IContentBase`. Such that `Content` gets the `IContentTypeService`, `IMediaType` gets a `IMediaTypeService`, etc.

Hopefully everything works now.

**Comment by zpqrtbnk** [comment]
cleaned up, refactored, merged
