### ISSUE TITLE
Examine corruption, Umbraco 7.12.3

### ISSUE THREAD

**Issue by jmvivas** [umbraco/Umbraco-CMS#3546]
We have been experiencing Examine corruption issues on an Azure hosted Umb 7.12.3 site. This was ocurring initially on a 7.7.6 site upgraded from 6.1.1 a while ago.

Reproduction
------------

If you're filing a bug, please describe how to reproduce it. Include as much
relevant information as possible, such as:

### Bug summary

Umbraco 7.12.3 site hosted in Azure, originally upgraded from 6.1.1.

The site crashes with the following message

ERROR Umbraco.Core.UmbracoApplicationBase - An unhandled exception occurred
System.Exception: Exception while creating a value. ---> System.IO.IOException: An unexpected network error occurred.

As well as upgrading to 7.12.3 We have implemented the configuration changes listed here
https://stackoverflow.com/questions/43629446/umbraco-an-unexpected-network-error-on-azure-web-apps
https://issues.umbraco.org/issue/U4-7614

But the issue is still happening roughly at 2 week intervals

**Comment by nul800sebastiaan** [comment]
Hey there @jmvivas - that sounds like an annoying issue! Luckily that's not a problem for most people so I'm assuming it's something in your setup that's not quite right. Make sure to read the docs for Examine 0.1.80+ here: https://our.umbraco.com/Documentation/Getting-Started/Setup/Server-Setup/Load-Balancing/flexible#luceneexamine-configuration

If that doesn't help, head on over to the forum to see if you can get some help with your specific setup!
