### ISSUE TITLE
Cannot delete property from doc type in v8

### ISSUE THREAD

**Issue by andyneil** [umbraco/Umbraco-CMS#3550]
It is not possible to delete properties on doc types.

Reproduction
------------

### Steps to reproduce

- Fresh install
- Create a new doc type with a simple property
- Save the doc type
- Delete the new simple property
- You are shown the success message
- Reload the doc type and the property is still there.

### Expected result

The property should no longer be there

### Actual result

The property is not removed

**Comment by nul800sebastiaan** [comment]
Fixed in https://github.com/umbraco/Umbraco-CMS/pull/3574
