### ISSUE TITLE
Wrong package version is listed in Developer -> Packages in Backoffice

### ISSUE THREAD

**Issue by Harvzor** [umbraco/Umbraco-CMS#3552]
I have recently released a new version of my package and submitted it to Our Umbraco. However, when searching for my package in the backoffice Umbraco, it still lists the old version with no option to select the new version.

This issue may have been reported before, there's a note at the bottom of [U4-7391](https://issues.umbraco.org/issue/U4-7391):

> see CON-928 as well, sometimes the very newest version doesn't always show up in the package name/version.

However, I'm not sure what CON-928 is and I cannot find it.

Reproduction
------------

### Bug summary

Umbraco incorrectly retrieves the wrong version for install in the backoffice when viewing a package.

### Specifics

My package is https://our.umbraco.com/packages/backoffice-extensions/iconator/
Bug reproduced in Umbraco 7.12.3
Tested in FF and Chrome

Go to `/umbraco/#/developer/packager/overview` and search for "Iconator" and click on the first result:

![dq_gxiyx4aufwwe jpg large](https://user-images.githubusercontent.com/7733459/48199407-d7f8d600-e353-11e8-802a-69b004a17284.jpg)

Above, we can see that the correct version is listed (1.1.2).

Click "Install package"

![dq_gxnzwwaewb-a jpg large](https://user-images.githubusercontent.com/7733459/48199453-f4950e00-e353-11e8-91d4-fdd36bb2e7d2.jpg)

The wrong version is now listed.

I have tested the install and it installs 1.1.1 rather than 1.1.2.

I have left it about a week and the wrong version is still returned so I assume it's not some caching issue on the Umbraco API.

**Comment by nul800sebastiaan** [comment]
That's annoying! I can confirm this a problem and we'll have to have a look at this soon, thanks for reporting.

**Comment by nul800sebastiaan** [comment]
@HarveyWilliams You seem to have the same problem as Lee here, your latest package file no longer has a strict requirement: https://twitter.com/cultiv/status/1064870298720313350

**Comment by HarveyWilliams** [comment]
I specifically chose my version number in Umbraco, and it's added the `type="strict"` param:

```
<requirements type="strict">
  <major>7</major>
  <minor>4</minor>
  <patch>0</patch>
</requirements>
```

However, when I go to install the package, it's still listing version 1.1.1 as the installable version. Is this a caching issue?

You can download the latest version (1.1.3) here: https://our.umbraco.com/packages/backoffice-extensions/iconator/

**Comment by nul800sebastiaan** [comment]
@Harvzor We've recently made some improvements in this area, I am getting 1.1.3 now so I feel this is resolved. Let me know if it happens again! 👍

**Comment by Harvzor** [comment]
@nul800sebastiaan I've tested too and the right version is coming up. Thanks.
