### ISSUE TITLE
Remove duplicate "?" on emptying recycle bins

### ISSUE THREAD

**Issue by karltynan** [umbraco/Umbraco-CMS#3554]
When you empty the recycle bin (in any language) it will ask "Are you sure??" - we want to make sure it only has a single "?".

It turns out there is a "?" after the localized string element, and needs to be moved inside the string element. All languages have their own "?" in the appropriate place already, thus causing the duplicate.

**Before: (English example)** 

![image](https://user-images.githubusercontent.com/800136/48201399-f82b9380-e359-11e8-91f9-b86745fd8518.png)

**Before: (French example)**

![image](https://user-images.githubusercontent.com/800136/48201524-522c5900-e35a-11e8-804f-48aaf20da8f0.png)

Reproduction
------------

Right click the recycle bin and click "Empty recycle bin" - you will see duplicate "??".

**Comment by nul800sebastiaan** [comment]
Fixed in https://github.com/umbraco/Umbraco-CMS/pull/3556
