### ISSUE TITLE
V8: Content picker returns to home page instead of picking content

### ISSUE THREAD

**Issue by emmagarland** [umbraco/Umbraco-CMS#3558]
Content picker fails in v8 due to error in Angular error.

Error is thrown in console: "Validate is not a function". Content is not picked. User is returned to home-screen. This is due to the parameter variable being called "validate" as well as the function.

**Comment by nul800sebastiaan** [comment]
Fixed in: https://github.com/umbraco/Umbraco-CMS/pull/3559
