### ISSUE TITLE
Turning off Autocomplete on initial install screen for password field

### ISSUE THREAD

**Issue by OwainWilliams** [umbraco/Umbraco-CMS#3569]
Reproduction
------------

If you're filing a bug, please describe how to reproduce it. Include as much
relevant information as possible, such as:

### Bug summary

On the initial install screen screen, the password field keeps previous passwords in plain text. 
This field should have autocomplete disabled

![image](https://user-images.githubusercontent.com/9438758/48208182-2913c480-e36a-11e8-9a0b-a156754ab4ec.png)

### Specifics
Umbraco-CMS\src\Umbraco.Web.UI.Client\src\installer\steps\user.html

### Steps to reproduce

Do a fresh install of Umbraco after already setting up another installation. The password you entered on the previous install will be visible in plain text. 
 
### Expected result
You shouldn't be able to see the previously entered password.

### Actual result

Password visible in a dropdown in plain text.

**Comment by nul800sebastiaan** [comment]
Fixed in: https://github.com/umbraco/Umbraco-CMS/pull/3573
