### ISSUE TITLE
🐛 Default click events in list views

### ISSUE THREAD

**Issue by mattycare** [umbraco/Umbraco-CMS#3575]
In list views, default click behaviour is not maintained.

![image](https://user-images.githubusercontent.com/1469061/48210072-8c9ff100-e36e-11e8-8b53-3580440355f2.png)

## Expected behaviour
Middle clicking / Ctrl+click should open the link in a new tab.

## Actual behaviour
Ctrl+click opens the link in the current page
Middle click opens a new page, but at the root

**Comment by nul800sebastiaan** [comment]
Thanks @mattycare - I had to ask at HQ if there was a specific reason this functionality didn't work as expected but it seems to be just an oversight. 

I've marked this as "Up for grabs" so that you or someone else coming along could create a pull request for it.

**Comment by mattycare** [comment]
Hi @nul800sebastiaan I've actually already created a [pull request for this one](https://github.com/umbraco/Umbraco-CMS/pull/3580).
Sorry, I completely forgot to comment here to say I'd picked it up - was quite a rush at the end of the London meetup.

**Comment by mattycare** [comment]
Looks like this has just been fixed as part of [this pull request](https://github.com/umbraco/Umbraco-CMS/pull/4948). Tested on 8.1, and all seems good. Closing the issue.
