### ISSUE TITLE
On some releases a manual upgrade is not required, if so, skip the installer

### ISSUE THREAD

**Issue by stevetemple** [umbraco/Umbraco-CMS#3589]
When deploying a site from source control via something like CI, there are occasions where Umbraco has been upgraded and all the files, versions numbers etc have already been done. Often there is no DB upgrade to be done so the installer runs, finds 0 migrations to be completed and essentially just completes immediately. 

On these occasions it would be nicer if there was a check if any migrations have to be run and if there are none just load the site. This would make working on and releasing security fixes and patch releases quicker and easier.

**Comment by stevetemple** [comment]
I've been having a look at this, so we could ask each installer step whether it has anything it actually needs to do before deciding to run the full installer. Certain steps like MajorVersion7UpgradeReport, Version73FileCleanup are always going to say they need to run if there is major version change or is an upgrade from prior to 7.3. Whilst SetUmbracoVersionStep will say if the web.config version is out.

However there will be times where every step will return false and in those we could skip the install and just load the site. 

This will be apart from the DatabaseUpgradeStep which will need to write an entry into the DB to say it's upgraded.

**Comment by Shazwazza** [comment]
The `DatabaseUpgradeStep` also runs migrations, it will always need to run in order for necessary migrations to be executed and to update the DB to indicate it's upgraded. If this is pursued, then this step will need to check if there are migrations that should be running for the target version or not and avoiding the installer could only be done if there are no DB migrations to execute. A problem with running migrations/upgrades silently in the background on startup is if anything goes wrong, there's no way to know and your site may end up just being dead. The other thing is whether a site should upgrade itself with a non-authenticated request?

**Comment by stevetemple** [comment]
Yeah I saw that, so I was checking in that step if there are any actual migrations to run, if not and all other steps are satisfied that there is nothing to do. We could do a quick silent install which is essentially adding a row to the umbracoMigrations table. If there is anything at all other than that to run it goes to standard install. That should eliminate issues with authentication and failures as it essentially only happens if there is nothing to do. 

I've got a rough prototype of this running and whilst it works, it's not anywhere near ideal and would have a lot of issues with LB servers as all servers will try and upgrade themselves... 

This is essentially to make patch releases quicker to deploy, but I'm now wondering if I could create a way to run DB migrations from command line so in a CI scenario, where all the files have been updated etc and it's just the DB changes that are left to deploy we could have a deployment step in the CI tool which handles migrations. Now that I've seen first hand how this all works, I think this sounds like a better approach so will have a look at that if I can bootstrap enough of Umbraco from a command line to get hold of, and subsequently run the migrations.

**Comment by Shazwazza** [comment]
You should look at https://aaronpowell.github.io/Chauffeur/ since it has command line utilities to install umbraco, it also bootstaps from the command line. The LinqPad provider also bootstraps from the command line: https://github.com/Shazwazza/UmbracoLinqPadDriver ... might be possible to just use LinqPad automation to do what you want :)

**Comment by stevetemple** [comment]
Thanks for the pointers, never seen Chauffeur before. Have contributed an upgrade step to that project instead: https://github.com/aaronpowell/Chauffeur/pull/85

Will close this ticket
