### ISSUE TITLE
When creating Document Type Collection no option to create templates at same time

### ISSUE THREAD

**Issue by pgregorynz** [umbraco/Umbraco-CMS#3590]
When creating a document type collection in the settings section, it creates the document types as expected, however there is no option to create the templates at the same time. 

Reproduction
------------

1. Go to settings
2. Create document type collection
3. Set Parent and Child type names and click create
4. Types are created as expected however, no templates are created as per standard document type creation.

### Expected result

I would expect an option to create the templates at the same time.  What should be a time saving feature now requires manual template creation and association, making a feature that should make things quicker take longer.

### Actual result

No templates are created and associated.

**Comment by dawoe** [comment]
@pgregorynz  this is already fixed : https://github.com/umbraco/Umbraco-CMS/pull/2882

I can't find the issue from the old tracker mentioned in the pr in the release notes of 7.12.x so I think it will be in 7.13.0

@nul800sebastiaan can you check this ?

Dave [Community Pull Request team](https://umbraco.com/blog/introducing-the-new-cpr-team/)

**Comment by nul800sebastiaan** [comment]
Thanks guys! I've marked #2882 to be included in the release notes for 7.13.0 indeed 👍
