### ISSUE TITLE
Users are still given create options when users have only browser option

### ISSUE THREAD

**Issue by nicklite** [umbraco/Umbraco-CMS#3601]
Summary:
Users are still given create doc type options when users have only browser option

Steps to reproduce:
1, Created a new user group with the following settings:
 - Set "Sections" to "Content" in "Assign Access" section
 - Content start node to the "content root" node in "Assign Access" section.
 - only enable "Browse Node" on default permission.
- save new group

2, Assign a user the group and log in as the user.
3, Click on the ellipse of a node which can create children nodes.

Expected Results:
Nothing should appear

Actual Results:
Displays the potential nodes that can be created. If you select a doc type then it will display the create page but no save button is displayed.

**Comment by kjac** [comment]
I can confirm this. There may be a few more issues with this scenario as well. 

I've got a fix for it - will submit a PR once I've had time to test it some more.
