### ISSUE TITLE
Change date picker property editor to use flatpickr

### ISSUE THREAD

**Issue by madsrasmussen** [umbraco/Umbraco-CMS#3610]
We have changed the bootstrap date picker in core to use a new library called flatpickr. It doesn't have any dependencies compared to bootstrap datepicker.

We need to update the date picker property editor to use the new flatpickr library and remove all bootstrap date picker files.

**Comment by clausjensen** [comment]
duplicate of https://github.com/umbraco/Umbraco-CMS/issues/3439
