### ISSUE TITLE
Refactor "current" UmbracoContext & others

### ISSUE THREAD

**Issue by zpqrtbnk** [umbraco/Umbraco-CMS#3620]
The way UmbracoContext.Current is managed is super weird, there are tons of notes about it in UmbracoContext.Current - and see also SchedulePublishing, for more oddities regarding the batched messenger and, again, the concept of "current". Better clean this up.

**Comment by Shazwazza** [comment]
@zpqrtbnk I'm pretty sure we can close this right?

**Comment by zpqrtbnk** [comment]
Yes
