### ISSUE TITLE
Allow "dialogService.contentPicker" to display the "Content" node

### ISSUE THREAD

**Issue by ssougnez** [umbraco/Umbraco-CMS#3628]
Hello,

when using "dialogService.contentPicker", it is possible to pass some options to leverage the appearance of the "umb-tree" directive. However, it is currently not possible to modify the variable "hideHeader" that defines whether the "Content" node is displayed or not.

This "issue" (it's not really an issue but it's not a feature request either) proposes to make this property configurable.

I already did some tests and I already know the code to modify, so I would do the PR.

An example of the motivation of this issue is described here: https://github.com/DanDiplo/Diplo.LinkChecker/issues/7. This plugin allows the user to analyze content in order to find dead links. However, the "Content" node is not selectable, meaning that if the site contains several nodes under "Content", he can't select the root.

### Specifics

    * This applies to Umbraco 7.12.4 and below.

**Comment by nul800sebastiaan** [comment]
Sounds good to me!
