### ISSUE TITLE
Invite another user form not clearing

### ISSUE THREAD

**Issue by ThomasAdams2** [umbraco/Umbraco-CMS#3631]
On the invite user page, fill out the form and send the invite, then clicking on the invite another user button takes you back to the invite user page and the form is already filled with the details of the user that was just invited.

This form should be cleared when inviting another user so that it can be filled in with another users details without having to clear the fields manually.

**Comment by nul800sebastiaan** [comment]
Thanks Thomas, I can reproduce that.

![3631](https://user-images.githubusercontent.com/304656/48554747-89ad7f00-e8df-11e8-9a54-8175a5521752.gif)

I've marked as "Up for grabs" so that you or someone else coming along could create a pull request for it.

**Comment by ThomasAdams2** [comment]
Hi Sebastiaan,

I've opened a PR for it here https://github.com/umbraco/Umbraco-CMS/pull/3632

Cheers, Thomas

**Comment by melvinvanrookhuizen** [comment]
@nul800sebastiaan think I working in sync with @hartviglarsen . This is no longer a bug

**Comment by nul800sebastiaan** [comment]
That was a little bit of an accident on @hartviglarsen's part 😅 but good to hear! I'll close this one.
