### ISSUE TITLE
Improve contribution guidance

### ISSUE THREAD

**Issue by tiffy74** [umbraco/Umbraco-CMS#3636]
## What type of issue is it? (Choose one - delete the others)

Missing documentation

## What article/section is this about? 
https://github.com/umbraco/Umbraco-CMS/blob/dev-v7/docs/CONTRIBUTING_DETAILED.md

## Describe the issue:
The contribution guide is great and very well written however to make it easier to understand as a reference please separate out the section on **What should I know before I get started?**.  Most users / devs who have not worked with Umbraco before will want to begin with this section so it makes little sense in placing it halfway down a page within a section on contributing in detail.

**Comment by nul800sebastiaan** [comment]
Hey @tiffy74 - it's been a while on this one! We'd still love any help if you think it's necessary, but feel free to just submit a PR for that, we don't need an issue to track this. I'll close this one for now! 👍
