### ISSUE TITLE
Beautify Text/Html when users click inside TinyMCE Source Code link

### ISSUE THREAD

**Issue by Dariatj** [umbraco/Umbraco-CMS#3647]
As you know Umbraco 7.11.1 comes with TinyMCE.  I'm not sure of the version of TinyMCE.

When my users login to Umbraco and click inside any TinyMCE Rich Text Editor located inside our pages, they can type in text, add links, drop in pictures, etc.   Some use the "Source Code" link to review the html. 
In all cases, when my users click the "Source Code" link all of the content shows in one big gigantic string with no spaces and no indentation.

Is there a plug in or a way to configure Umbraco/TinyMCE so that when my users click inside the TinyMCE Rich Text Editor, the text and html tags are "beautified".  Meaning there is indentations for all tags so my users can navigate through the text and html easier?

If not, can you add this request as a feature request.

Thanks

Tom

**Comment by nul800sebastiaan** [comment]
I would encourage you to use the Code Mirror button instead of the regular Code button:

![image](https://user-images.githubusercontent.com/304656/48554196-05a6c780-e8de-11e8-9f74-b6fc549c4743.png)

This looks much better: 

![image](https://user-images.githubusercontent.com/304656/48554210-11928980-e8de-11e8-87ec-3572ac6305b8.png)

**Comment by nul800sebastiaan** [comment]
Fair enough. I don't think what you need currently exists and I would question your need for editor to do very precise HTML editing, a task for which a CMS comes in handy. :-)

**Comment by Dariatj** [comment]
Well, our editors are very savvy and have the need to insert tables, etc.  Sometimes, the rendered HTML is not quite as it seems in the editor when we preview it.  Not sure why and can't put our finger on it.  But the solution has always been to click the "Code Mirror" icon and then copy out to Notepad++ where we have installed XML tools.  From here we beautify the text (including indents, etc) and then copy it back to Rich Text Editor.

So can you add this an enhancement please?

Thanks

Tom

**Comment by nul800sebastiaan** [comment]
Hi Tom, we don't have plans to add anything for that but if you want to attempt it and send a PR we can have a look at it! 👍

But really we'd rather "put our finger" on what's actually wrong with the html, seems strange. Sounds like it's difficult to reproduce though.

**Comment by Dariatj** [comment]
Can you send me the link where I can create a PR for this as that's what I thought I was doing.
Thanks

Tom

**Comment by nul800sebastiaan** [comment]
Ah! A PR in this case means that you have a look at fixing the issue in code and send us your solution so we can include it in a future version of Umbraco. A guide on contributing to Umbraco can be found here: https://github.com/umbraco/Umbraco-CMS/blob/dev-v7/.github/CONTRIBUTING.md

**Comment by Dariatj** [comment]
Sebastiaan:
I don't have a solution, only a workaround.  I don't know how to modify TinyMCE's code.
However, do you want me to use the link to write up my workaround?
Also,I asked TinyMCE if they had a solution and they have a paid solution, which we can't afford.
Perhaps you could look into incorporating their paid solution into the next version of Umbraco?
See here 
https://community.tiny.cloud/communityQuestion?id=90661000000kAK8AAM
Please advise.

Thanks
Tom

**Comment by nul800sebastiaan** [comment]
Umbraco can't ship with a paid plugin, then we'd have to pay them for each download of Umbraco.

For your information: In the upcoming v8 we have upgraded TinyMCE and are using the Ace editor which does do formatting nicely.

**Comment by Dariatj** [comment]
Thank You Sebasstiaan.  Can't wait for v8 so they have a better user experience editing the HTML using the "SOURCE CODE" link.

Tom
