### ISSUE TITLE
Navigating using the breadcrumb clears the culture from the query string

### ISSUE THREAD

**Issue by RobertCopilau** [umbraco/Umbraco-CMS#3648]
How to reproduce:
* Have a variant parent with a child node
* Navigate to the child node
* Attempt to go back one level by using the breadcrumb
* The culture has been removed from the query string

**Comment by bergmania** [comment]
PR: https://github.com/umbraco/Umbraco-CMS/pull/4335

**Comment by warrenbuckley** [comment]
All tested & merged
