### ISSUE TITLE
SPIKE: Handle tree when using infinite editing

### ISSUE THREAD

**Issue by madsrasmussen** [umbraco/Umbraco-CMS#3651]
child of https://github.com/umbraco/Umbraco-CMS/issues/3649

How do we handle the tree when infinite editing is open? You don’t really need the tree when you are in an infinite flow so we could add a black overlay so it matches the editor.

Another solution would be to warn the user if they change the node. I think we already implemented a warning on route change but it doens't seem to work anymore. We need to look into that.

**Comment by madsrasmussen** [comment]
PR: https://github.com/umbraco/Umbraco-CMS/pull/3786

I have added an overlay to the tree which dims it the same way as the rest of the editor. It gives more focus to dialog that just opened.

How to test:
- [ ] Test a functionality that opens an infinite editing window and make sure the tree is dimmed the same way as the editor. (add property to doc type, add media to media picker, change doc type on content node, etc. Just pick one :-) ).

**Comment by warrenbuckley** [comment]
ALl looks good & tested with Mads on a call
