### ISSUE TITLE
Content info app should show info based on selected language

### ISSUE THREAD

**Issue by madsrasmussen** [umbraco/Umbraco-CMS#3658]
child of https://github.com/umbraco/Umbraco-CMS/issues/3657

To follow the best practices for content apps the content info app should only show the info related to the currently selected variant.

**Comment by clausjensen** [comment]
Currently the info tab on content is showing URLs for all variant, publish status for all variants.
It needs to be clear if data in this tab is related to a variant or if it is node related. Right now it is one big mess. It could also be context related - which means you will only see "one version of the data" which is the one of the current context of the UI.

**Comment by madsrasmussen** [comment]
PR: https://github.com/umbraco/Umbraco-CMS/pull/3861

The PR makes the content app contextual so it shows create Date, Status and URLs based on the selected language. I have also added a label for the History so it tells that is shows updates for all variants.

**How to test:**
* Make a node with variants and an invariant node
* Make sure the URL, status and create date  is shown correctly for the invariant node
* Make sure the URL, status and create date updates correctly when changing languages for a node with variants.

**Comment by zpqrtbnk** [comment]
merged
