### ISSUE TITLE
Remove Serilog dependency in UmbracoModule

### ISSUE THREAD

**Issue by zpqrtbnk** [umbraco/Umbraco-CMS#3659]
At the moment `UmbracoModule` assumes that the `ILogger` is Serilog's to retrieve a unique request ID, that needs to be reverted, our module should decide the request ID and Serilog's enricher should use it - so that it's still possible to replace the `ILogger` Serilog implementation.

**Comment by bergmania** [comment]
Can we consider this done, if we just remove the two unused using statements?

```
...
using Umbraco.Core.Configuration;
...
using Umbraco.Core.Logging.Serilog.Enrichers;
```

**Comment by clausjensen** [comment]
Think so - I don't really see any references to serilog apart from that. I've removed the usings - closing this task.
