### ISSUE TITLE
Proper fallback

### ISSUE THREAD

**Issue by clausjensen** [umbraco/Umbraco-CMS#3663]
Implement proper fallback in `content.Value<T>()` methods. Should be able to fallback on language, or walk up the tree, or anything - should be extensible.

child of https://github.com/umbraco/Umbraco-CMS/issues/3661

**Comment by jvtroyen** [comment]
#3661 seems missing?

**Comment by jvtroyen** [comment]
@clausjensen, unless I'm missing something glaringly obvious, the link to #3661 yields an error (or I don't have access?). I was looking for existing issues/bugs/fixes in regards to Language Fallback in v8.

**Comment by zpqrtbnk** [comment]
I am pretty sure that one is done entirely, and all we need is verify and close.
