### ISSUE TITLE
Cleanup all the Value() overloads

### ISSUE THREAD

**Issue by clausjensen** [umbraco/Umbraco-CMS#3664]
There are different `Value()` overloads but really we need a clean approach for dealing with fallbacks, cultures, etc.

child of https://github.com/umbraco/Umbraco-CMS/issues/3661

**Comment by zpqrtbnk** [comment]
I think it's done already and that is mostly, verifying that I'm not wrong.

**Comment by zpqrtbnk** [comment]
all good (enough) for me now
