### ISSUE TITLE
Query-builder needs to be updated to generate the correct snippets

### ISSUE THREAD

**Issue by clausjensen** [umbraco/Umbraco-CMS#3668]
When `Value()` methods + navigation have all been updated, we need to update the query builder (in the template editor) to generate proper code. 

child of https://github.com/umbraco/Umbraco-CMS/issues/3661

NOTE: this task is ONLY to get the snippets working, currently all execution, reporting and timing cannot be done in v8, there is a separate task for this: https://github.com/umbraco/Umbraco-CMS/issues/3908

**Comment by bergmania** [comment]
PR: https://github.com/umbraco/Umbraco-CMS/pull/4040

**Comment by zpqrtbnk** [comment]
reviewed code changes, have fix how `IPublishedValueFallback` works and deals with missing properties in recurse fallback, have created a few tests around it, happy with it all, merged

**Comment by zpqrtbnk** [comment]
OTOH having issues when running the code in the backoffice - investigating

**Comment by zpqrtbnk** [comment]
query builder would crash on empty site, fixed + query builder was ... odd ... have refactored the code, hopefully cleaner now - closing this task
