### ISSUE TITLE
Open Template via Content Info App - Changing assigned template opens incorrect template

### ISSUE THREAD

**Issue by warrenbuckley** [umbraco/Umbraco-CMS#3670]
When doing a review of https://github.com/umbraco/Umbraco.Private/issues/92 with @madsrasmussen we discovered a bug where if you have more than one available template assigned to a doctype, change the template assigned to a content node and then click open for the new template editor to show it will show the incorrect template.

The serverside response of JSON for `allowedTemplates` is a string array of template aliases and does not include the template ID that is needed to be updated to open the correct template.

This was a PR for V7 that was merged up into V8 so it will need to be fixed in both places.

**Comment by nul800sebastiaan** [comment]
Seems to work fine at the moment, will close this.
