### ISSUE TITLE
Issue with the Backoffice side bar appearing twice when you close the Dev tools.

### ISSUE THREAD

**Issue by elit0451** [umbraco/Umbraco-CMS#3671]
When you go to the Backoffice and you open the Developer tools the side bar size is being adjusted due to the new size of the browser. If you want to see all of the sections you would click on the arrow that will make the rest of the sections appear as a second side bar. If you close the Developer tools after, all the sections will appear on the first side bar but the second side bar won't disappear unless you click on a section.

**Comment by nul800sebastiaan** [comment]
I don't think this is an issue any more. Closing for now!
