### ISSUE TITLE
Content/Media picker picked details should be contextual to the variant language

### ISSUE THREAD

**Issue by Shazwazza** [umbraco/Umbraco-CMS#3673]
As an example, lets say there are 3 languages installed and English is the default.

If i have a content picker that is variant and I am editing the Danish language. When I choose a content item in the tree, the content picker displays some details including the "Name", "Url" and "Icon" ... but the "Name" and "Url" are both going to be displaying the default language information.

Also I think the 'edit' button to edit that particular content item will default to editing the default language.

Similarly this will be a problem for the media picker too, and since a different image can be picked between variants that will need to be update too.

**Comment by kjac** [comment]
#4507 fixes this, if nothing else then as a temporary solution.

**Comment by nul800sebastiaan** [comment]
Fixed in https://github.com/umbraco/Umbraco-CMS/pull/4507
