### ISSUE TITLE
Un-publish button not showing

### ISSUE THREAD

**Issue by RobertCopilau** [umbraco/Umbraco-CMS#3684]
Unpublish button definition will not be added because the `publishDate` from the content will always be undefined as it has been moved to the variant object.

Code at: `contenteditinghelper.service.js`
![Capture.PNG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5b151a952d7cd20011c4533d/125516c66e82c728ace21e0d46cb958a379791accda5fd53b652fa912a5265296b51a17a25d4e22bed177f055d5c4aac41590a44aff9dd2da6a42062c80d55b98e30063e937f03a6aa8318b500bf23884884bfb8894dc4ef3f37aa.PNG)

**Comment by Shazwazza** [comment]
Closing this issue since the unpublishing all works now.
