### ISSUE TITLE
Slave Server Fails to Process Cache Instructions following certain user actions

### ISSUE THREAD

**Issue by ProNotion** [umbraco/Umbraco-CMS#3691]
We have a multi-site install of significant size and moderate activity, there are two servers in the setup one master and one slave however following certain editor events the two get out of sync on an increasingly regular basis and it seems to be somehow related to actions such as unpublish/delete. 

### Summary

The slave server seems unable to process the next instruction and so never actually catches back up unless I set the value to zero in the last-sync file in `~/App_Data/Temp/DistCache/` triggering a cold reboot of the site. This is costly in time and resources and it requires the slave server to be removed from the Load Balancer to avoid the impact of the cold boot on the front end of the site.

####
This is the last cache instruction to be processed on the slave server:

```
[{
		"RefreshType": 3,
		"RefresherId": "55698352-dfc5-4dbe-96bd-a4a0f6f77145",
		"GuidId": "00000000-0000-0000-0000-000000000000",
		"IntId": 0,
		"JsonIds": "[65964,65240,65838,65642,64562,65644,65495,65241,64561,64563,64564]",
		"JsonIdCount": 11,
		"JsonPayload": null
	}, {
		"RefreshType": 3,
		"RefresherId": "27ab3022-3dfa-47b6-9119-5945bc88fd66",
		"GuidId": "00000000-0000-0000-0000-000000000000",
		"IntId": 0,
		"JsonIds": "[65240,65838,65642,64562,65644,65495]",
		"JsonIdCount": 6,
		"JsonPayload": null
	}
]
```

This is the next cache instruction in the queue:

```
[{
		"RefreshType": 5,
		"RefresherId": "27ab3022-3dfa-47b6-9119-5945bc88fd66",
		"GuidId": "00000000-0000-0000-0000-000000000000",
		"IntId": 65642,
		"JsonIds": null,
		"JsonIdCount": 1,
		"JsonPayload": null
	}
]
```

I have a hunch that this issue is due to a collision of actions on a node and when this has happened historically the nodes involved have generally been either deleted or unpublished shortly before/after the last processed cache instruction.

I have observed that the same node id of `65642` exists in both cache instructions

### Specifics

Umbraco version is currently 7.10.4.
Flexible Load Balancing

**Comment by nul800sebastiaan** [comment]
Hey Simon, good seeing you at the UK festival last week.

I know you don't want to hear this, but .. have you tried upgrading?
Specifically this fix comes to mind that we made recently in 7.12.2: https://issues.umbraco.org/issue/U4-11599

**Comment by ProNotion** [comment]
Good to see you too, if only in passing.

You're right not something I want to hear right now but we did hit that issue as well a few days back and if it is fixed in a later version it kind of forces my hand on the upgrade. But, at the same time, I'm not convinced yet that they are one and the same issue (at least not due to lack of database connectivity but certainly could be due to the fact that when it fails it never attempts to try and process the instruction again.

**Comment by nul800sebastiaan** [comment]
Yeah tough one, I'll ask @Shazwazza and @zpqrtbnk to have a look at this as well but it might be the same cause for some reason. If you have any logs (set log level to `DEBUG` possibly) then that might help identify the issue as well. If you've deviated in some way from the LB documentation that might point to a source of the problem as well.

**Comment by ProNotion** [comment]
> If you've deviated in some way from the LB documentation that might point to a source of the problem as well.

:open_mouth: :hand: I don't think I've been devient at all 

Before enabling debug logging on the production site I will see if I can in anyway reproduce this issue.

**Comment by nul800sebastiaan** [comment]
Haven't heard back for 2 years, so I'm assuming you've moved on! 😅
