### ISSUE TITLE
Link picker overlay let's you submit before the URL has been fetched

### ISSUE THREAD

**Issue by abjerner** [umbraco/Umbraco-CMS#3698]
With some of the recent changes to the link picker overlay, it seems that a bug was introduced along the way.

For instance, if you select a content node and press *Submit*, the returned `model.target` object representing the link may not always contain the `url` property, as the URL is fetched via a request to the server. The `url` property of the object will be populated eventually when the request completes, but this may be too late as it then may be after the overlay callback has been executed.

Specifically this scenario affects some of our packages utilizing the link picker overlay, as we're handling and parsing the link directly in the overlay's callback, and thus we don't get the URL once it's later populated by the overlay - eg. as here:

https://github.com/skybrud/Skybrud.Umbraco.Redirects/blob/master/src/Skybrud.Umbraco.Redirects/App_Plugins/Skybrud.Umbraco.Redirects/Scripts/Controllers/Dialogs/AddRedirectDialog.js#L73

The overall issue with the `url` property can be broken down into two parts:

1. A request via `contentResource.getById(id)` is made to the server to ensure that we get the current URL of the selected node. If the server is (momentarily) slow (or the user is just really click to press *Submit* :zap:). The time it takes to make the request may also have been increased when `contentResource.getNiceUrl(id)` was replaced with `contentResource.getById(id)` ([in this commit](https://github.com/umbraco/Umbraco-CMS/commit/3fecd55c49f5078212ccf3e18f0c5c3315c2e023)).

2. The callback for the request also handles getting a list of anchor elements on the selected node. This logic is called right before the `url` property is populated - the latter therefore being unnecessarily delayed. I've submitted a fix for that here: https://github.com/umbraco/Umbraco-CMS/pull/3697

As a result of both **1)** and **2)**, we can't really rely on `model.target` in the callback. Ideally the overlay should have some kind of loading state so that a user can't click *Submit* before all necessary data about the selected node has been retrieved.

As mentioned, this affects some of our packages, and I'd therefore be happy to look further into the issue, and implementing a fix. But some thoughts on how to best accomplish this are more than welcome ;)

**Comment by nul800sebastiaan** [comment]
I think the related PR fixed enough of the issue didn't it @abjerner ? I don't really have indications that people are experiencing problems any more.

I'll close this for now, let me know if there's something else that still needs to REALLY be fixed (if it can be reproduced it can hopefully be fixed).
