### ISSUE TITLE
Additional bulk functions on media folders and content list-views

### ISSUE THREAD

**Issue by drummerboy46** [umbraco/Umbraco-CMS#3701]
The "multi select" functions from media folders are limited to delete only and in content list views you can only publish and un-publish. Can we have other bulk actions on multi-selected items?

Move needs to be added for media. For content could you add copy, move and delete. 

It would be extra awesome if you could bulk change document type too , but I understand there are additional complexities when documents of varying doctypes are selected which would make the UI/UX difficult. Maybe a check before you get to the property mapping UI to ensure all items selected are of a single doctype would work to keep things simple.

**Comment by kjac** [comment]
@drummerboy46 it's already there - but you need to turn it on explicitly.

List view bulk actions are configured on the list view data types:

![image](https://user-images.githubusercontent.com/7405322/48757429-0011fe80-ec9d-11e8-9c48-2c6b13b04d28.png)

**Comment by nul800sebastiaan** [comment]
Yep indeed. Thanks for the help @kjac !
