### ISSUE TITLE
Dialogs should have better label for "Submit"-button

### ISSUE THREAD

**Issue by enkelmedia** [umbraco/Umbraco-CMS#3704]
No really a bug, more some kind of improvement for the UX.

In some dialogs (ie media picker and content picker) the label of the "Submit"-button could be improved. I'm thinking that ie when you've picked media or content the text "Select" (lang key: buttons_select) would probably make more sence?

I'm thinking that I could add some submitButtonLabelKey-settings for dialogs in places where it makes sence for example:

- contentpicker.controller.js
- mediapicker.controller.js
- membergrouppicker.controller
- mediapicker.controller

And also maybe change the "Submit" text when editing properties on document types to "Save"?

Should I create a PR for this?

**Comment by nul800sebastiaan** [comment]
Thanks @enkelmedia ! Good suggestions. 

1. Yes, "Select" for pickers makes sense 👍 
2. It would be really nice to show either "Add" or "Update" based on if you're adding a new property or editing an existing one.

I've marked this as "Up for grabs" so that you or someone else coming along could create a pull request for it.

**Comment by abjerner** [comment]
@enkelmedia I've been meaning to look into this for a while now, but feel free to go ahead and create a PR for this 👍 I'd be happy to review and test it 😉 

**Submit** is translated to the **Indsend** in Danish, which to me (or our clients) doesn't make any sense.

Perhaps rather than **Select**, the default label should just be **Continue**, and then it can be overwritten in the individual overlays if needed?

**Comment by enkelmedia** [comment]
I did work on the PR for some time during the weekend, and in cases where there is an "update" possible the text is different.

@abjerner Might be a good idea to change the default in the overlay-directive as well. What do you say @nul800sebastiaan ?

**Comment by nul800sebastiaan** [comment]
As said: we agree that "Select" should be used for all pickers. Any language files can use what they think is appropriate.

**Comment by abjerner** [comment]
@nul800sebastiaan The problem with **Submit** is that is correctly translates to **Indsend**, but it may still give an incorrect meaning depending on the context, which was why I thought **Continue** would be better suitable in more contexts.

But if most overlays are updated with a custom button text, the default term may not matter that much anyways.

**Comment by enkelmedia** [comment]
I've inlcuded a change to the "defualt" text for umbOverlays and I would agree with @abjerner that "Continue" makes more sense over "Select" since the umbOverlay might be used in 3rd party packages or other senarios where "Select" as fallback would not make sense.

**Comment by enkelmedia** [comment]
@nul800sebastiaan Well your example is fixed by the PR that I've sent since it would change the label of the button to "Insert" or "Update" for a links and "Select" for a content/media-picker. 

For me personally I don't have a super strong opinion reg. if the default should be "Submit", "Continue" or "Select". My only concern is that the umb-overlay might be used in packages and scenarios where the developer have not bothered to set the label and maybe the "correct" label in some senarios would be "Save", but the fallback thats there today would be to "Submit", changing "Submit" to "Select" in that case would not make sense at all - but "Continue" (Or maybe just "OK") might make more sense.

Otherwise we could just keep the "Submit"-fallback in the umb-overlay as it is today and apply the context-specific changed for dialog's in the core - that's really the main purpose of the PR.

**Comment by nul800sebastiaan** [comment]
I don't have a super strong opinion either, but as I don't have an example of where this might be a problem, I am unable to form an opinion.. ;-)

Hope @abjerner has a good usecase.

**Comment by nul800sebastiaan** [comment]
No opinions have come in since the last comment. I'll close this for now, if there's something that really needs to be fixed then make sure to open a new issue.
