### ISSUE TITLE
Dictionary items sorted at random in 7.12.3

### ISSUE THREAD

**Issue by cryothic** [umbraco/Umbraco-CMS#3705]
I noticed the Dictionary isn't sorted alphabeticly anymore in 7.12.3 (maybe earlier?).
There also isn't a sorting-option.

Items are getting randomly placed. I've created the same list of items on 2 umbraco instances, and they are sorted (seemingly) random.

**Reproduction:**
I made a list of the following items like this:
create -> enter alias -> next, so I didn't enter a value at first
-option_1
-option_2
-option_3
-option_4
-option_5

it ended up like this:
-option_2
-option_1
-option_3
-option_5
-option_4

And in a different order the second time I tried

This is annoying to me as a developer, but even more for our content-department, who now need to search through the dictionary-items (normaly named with words ofcourse).

**Comment by kjac** [comment]
Oh... I fixed this for V8. I didn't notice it was a problem in V7, but clearly it is:

![image](https://user-images.githubusercontent.com/7405322/48672201-01271c80-eb33-11e8-966f-5ee30ee9fc88.png)

I'll see if I can apply the V8 fix to V7.

**Comment by kjac** [comment]
PR in #3706

**Comment by cryothic** [comment]
Nice job, thanks!
