### ISSUE TITLE
[v8] Decoupling UmbracoApplicationBase from runtimes

### ISSUE THREAD

**Issue by aaronpowell** [umbraco/Umbraco-CMS#3713]
While digging around in the `CoreRuntime` I found a comment about removing [`UmbracoApplicationBase` from it](https://github.com/umbraco/Umbraco-CMS/blob/temp8/src/Umbraco.Core/Runtime/CoreRuntime.cs#L48-L51).

So I figured I could do that clean up.

**Comment by zpqrtbnk** [comment]
Happy, merged the PR. Thanks!!
