### ISSUE TITLE
Can't sort image cropper data type defined crops

### ISSUE THREAD

**Issue by Shazwazza** [umbraco/Umbraco-CMS#3719]
in v8  (maybe v7, not sure) the defined crops cannot be sorted. In the UI it's possible but on saving it doesn't persist the new sort.

**Comment by kjac** [comment]
@Shazwazza looks like a V7 issue:

![imagecropper-crop-sorting-before](https://user-images.githubusercontent.com/7405322/48758319-f0e08000-ec9f-11e8-9f16-31062ccc3dbc.gif)

I'll take a look at it if you want.

**Comment by Shazwazza** [comment]
If you have time, sure thing! ill update the title

**Comment by kjac** [comment]
Will do 😄

**Comment by nul800sebastiaan** [comment]
Note: this will also be fixed in v8 once it's merged up.
