### ISSUE TITLE
NullReferenceException when accessing properties from IPublishedContent made by UmbracoHelper.TypedContent in Examine Events

### ISSUE THREAD

**Issue by nielslyngsoe** [umbraco/Umbraco-CMS#3720]
In a GatheringNodeData context, the GetPropertyValue on IPublishedContent created by umbracoHelper.TypedContent(Id) results in a NullReferenceException.

Reproduction
------------

### Bug summary

`        protected UmbracoHelper umbracoHelper;

        protected override void ApplicationStarted(UmbracoApplicationBase umbracoApplication, ApplicationContext applicationContext) {
            base.ApplicationStarted(umbracoApplication, applicationContext);

            umbracoHelper = new UmbracoHelper(UmbracoContext.Current);

            var PeopleIndexer = (UmbracoContentIndexer)ExamineManager.Instance.IndexProviderCollection["PeopleIndexer"];
            PeopleIndexer.GatheringNodeData += GatheringCountry;

        }
        
        private void GatheringCountry(object sender, IndexingNodeDataEventArgs Event) {

            if (Event.IndexType == IndexTypes.Content) {

                try {

                    var fields = Event.Fields;

                    string CountryField = fields["country"];
                    if (CountryField != null) {
                        
                        GuidUdi RealUdi = GuidUdi.Parse(CountryField);
                        int CountryId = umbracoHelper.GetIdForUdi(RealUdi);

                        Debug.WriteLine("CountryId : " + CountryId );
                        
                        if(CountryId != 0) {
                            IPublishedContent Country = umbracoHelper.TypedContent(CountryId);

                            if (Country != null) {

                                Debug.WriteLine("Country.Id : " + Country.Id);
                                Debug.WriteLine("Country.Name : " + Country.Name);
                                Debug.WriteLine("HasProperty : " + Country.HasProperty("code"));

                                string Code = Country.GetPropertyValue<string>("code");
                                Debug.WriteLine("Got value: " + Code));

                                if (Code != null) {
                                    Event.Fields.Add("countryCode", Code );
                                }
                            }
                        }
                    }

                } catch (Exception ex) {
                    LogHelper.Error<Exception>("Error munging fields for " + Event.NodeId, ex);
                }
            }
        }`

### Expected result

No error? getting the value?...

### Actual result

Got: 
![errorlog](https://user-images.githubusercontent.com/6791648/48761355-b7604280-eca8-11e8-8062-9c758f7ebf30.JPG)

Exception thrown: 'System.NullReferenceException' in umbraco.dll

**Comment by Shazwazza** [comment]
There's a few issues here:

* UmbracoHelper is a Request based object, it absolutely should not be tied to a singleton or static reference because it requires an HttpContext to create it (which is of course a Request based object). If you do this you will have a memory leak
* All indexing runs on a background thread including GatheringNodeData, there is no HttpContext so there is not UmbracoContext. You can either use the Umbraco Services to get the data directly from the database (beware this can cause N+1 performance problems!), or you can hack together a fake HttpContext/UmbracoContext to access the content cache. There are a few posts on our.umbraco.com and google about doing this so would urge you to have a look there, see https://www.google.com.au/search?q=gatheringnodedata+umbracocontext

**Comment by nielslyngsoe** [comment]
Hi @Shazwazza 

Thanks for the fast feedback.

If someone finds this issue, the solution for me is:

`
                    string Country = fields["country"];
                    if (Country != null) {
                        var contentService = ApplicationContext.Current.Services.ContentService;

                        GuidUdi realUdi = GuidUdi.Parse(Country);
                        int countryId = umbracoHelper.GetIdForUdi(realUdi);
                        if (countryId != 0) {
                            IContent Country = contentService.GetById(countryId);
                            var code = Country.Properties["code"].Value;
                            if (code != null) {
                                Debug.WriteLine("code : " + code);
                                e.Fields.Add("actCountryCode", code.ToString());
                            }
                        }
                        
                   }`
