### ISSUE TITLE
Default Content in List View

### ISSUE THREAD

**Issue by jacklawry** [umbraco/Umbraco-CMS#3722]
Why isn’t there the option to just show the actual image or dropdown value etc in a List view… What use is the ability to list the GUID to any editor? A small little thumbnail however would be very useful for them. 

![image guid](https://user-images.githubusercontent.com/3786136/48767092-d01f2700-ecad-11e8-8451-ad620392a1e4.png)

Dropdown choices and pickers would also be much better if it showed the selected value instead of a GUID.

**Comment by kjac** [comment]
@jacklawry I'm not entirely sure how you managed that? My default (media) list view looks like this:

![image](https://user-images.githubusercontent.com/7405322/48839360-899ffa00-ed8b-11e8-8d01-084afa017db3.png)

**Comment by jacklawry** [comment]
Sorry this is a custom list for nodes (not media) but there is the option to show the image in the list (in addition to the name and sort order etc) but selecting the image just displays its GUID. I can’t think of a single use for displaying a GUID to any user?

The only way to display the actual image is to build a custom view. Surely it would be friendlier to have the ability to display the image (a small thumbnail for example)

**Comment by kjac** [comment]
@jacklawry ah... makes sense. Your "image" must be a custom property then.

![image](https://user-images.githubusercontent.com/7405322/48842767-6c702900-ed95-11e8-9415-8f757180f80d.png)

The list view simply displays the content of the properties you select. It doesn't interpret them. An image picker saves an Umbraco UID, so the list view displays just that. 

The same goes for all other property types. Consider this screenshot, where I have selected a Nested Content property for my list view - the list view renders the JSON stored by Nested Content:

![image](https://user-images.githubusercontent.com/7405322/48842681-2915ba80-ed95-11e8-96d9-95421a65ae75.png)

**Comment by nul800sebastiaan** [comment]
Hi @jacklawry - It's difficult to come up with a great experience out of the box for everything, especially custom properties. The defaults list views are fairly simple but you can make your own layouts as well with a bit of code.

For getting a better view on custom properties, we would recommend looking into building a custom list view, a good blog post of this can be found here: https://24days.in/umbraco-cms/2016/custom-list-view-layouts/
