### ISSUE TITLE
Remove Bootstrap Datepicker

### ISSUE THREAD

**Issue by madsrasmussen** [umbraco/Umbraco-CMS#3724]
Bootstrap datepicker needs to be changed to a datepicker with no dependecy on bootsrap or jquery. We have chosen Flatpickr (https://flatpickr.js.org/) as the new date picker for Umbraco.

We need to update the date picker property editor + anywhere else in the back office where the date picker is used.

**Comment by madsrasmussen** [comment]
PR: https://github.com/umbraco/Umbraco-CMS/pull/3723

The PR removes all files related to bootstrap date picker and changes the two places where it was used. The date picker property editor and in the query builder. Flatpickr is already included in v8 because we use it for scheduled publishing.

The PR also removes the last places where we use the bootstrap dropdown menu and implements our own dropdown menu in those places.

**How to test:**
Before checking out the branch
- [ ] Set up a doc type with a couple of different date pickers. One normal, one date picker with time and one date picker with a custom format.
- [ ] Add a node where you select dates for all date pickers.

Check out new branch
- [ ] Make sure all dates are shown correctly in the new date pickers.
- [ ] Make sure you can change the date for a normal date picker.
- [ ] Make sure you can change date and time for a date picker with time.
- [ ] Make sure you can change the date for a date picker with a custom format. Make sure the format is correct when the date picker is closed and the node is saved.

Testing dropdown changes.
- [ ] Make sure the actions menu can still open and close (top right corner of a content node)
- [ ] Make sure the dropdown in the content permissions dialog still works.
- [ ] Make sure the dropdowns + datepicker in the query builder (template editor) still works. The query builder gives a ysod when a date is chosen in the date picker. We have a task to get the query builder updated: https://github.com/umbraco/Umbraco-CMS/issues/3668

**Comment by RobertCopilau** [comment]
Everything works just fine.

My only gripe is that the empty drop-down selection has a squashed button in the query builder overlay.
![squashed empty dropdown.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5b151a952d7cd20011c4533d/125516c66e82c728ace21e0d46fb858f22918bac8ba9ba4eb449e9d42d5428632d0bb42532c9a138ad4d71040c1b5ca6535d0d11fead8e28a3e26a7489590bedd06c5a71933445fabd9003ad43eb7edf10d8eff6df0ed2e22f24ee818e4a3a1d071b81fc5c31a69a48da15.jpg)

Will merge this and we can look at the squashed dropdown selection at a later date.
