### ISSUE TITLE
Enabling FIPS prevents logging in to the back-office

### ISSUE THREAD

**Issue by benjaminc** [umbraco/Umbraco-CMS#3727]
Reproduction
------------
### Bug summary

After enabling FIPS on the server where Umbraco is running, users are no longer able to log into the back-office.  Trace logging shows that it is trying to use an MD5 hash while getting user Avatar URLs.

### Specifics

Windows Server 2016 with all updates as of 20-Nov-2018

Umbraco 7.12.4 vanilla, downloaded straight from https://our.umbraco.com/contribute/releases/7124?fromdownload=true

Single DLL added to enable FIPS compliance in Lucene.NET
Contains single class file extending ApplicationEventHandler, which has the following line of code in the OnApplicationInitialized method:
`SupportClass.Cryptography.FIPSCompliant = System.Security.Cryptography.CryptoConfig.AllowOnlyFipsAlgorithms`

In Local Security Policy on the server, in the Local Policies / Security Options folder, the "System cryptography: Use FIPS 140 compliant cryptographic algorithms, including encryption, hashing and signing algorithms" setting is set to Enabled

Logging into the back-office results in the following response to the PostLogin API call:
{"Message":"An error has occurred.","ExceptionMessage":"\r\n\r\nMapping types:\r\nUser -> String[]\r\nUmbraco.Core.Models.Membership.User -> System.String[]\r\n\r\nDestination path:\r\nUserDetail.Avatars.Avatars\r\n\r\nSource value:\r\nUmbraco.Core.Models.Membership.User","ExceptionType":"AutoMapper.AutoMapperMappingException","StackTrace":"   at Umbraco.Web.Editors.AuthenticationController.SetPrincipalAndReturnUserDetail(IUser user, IPrincipal principal)\r\n   at Umbraco.Web.Editors.AuthenticationController.<PostLogin>d__13.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Threading.Tasks.TaskHelpersExtensions.<CastToObject>d__3`1.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Controllers.ApiControllerActionInvoker.<InvokeActionAsyncCore>d__0.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__5.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__5.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Filters.ActionFilterAttribute.<ExecuteActionFilterAsyncCore>d__0.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__5.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__5.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Filters.ActionFilterAttribute.<ExecuteActionFilterAsyncCore>d__0.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Controllers.ActionFilterResult.<ExecuteAsync>d__2.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Filters.AuthorizationFilterAttribute.<ExecuteAuthorizationFilterAsyncCore>d__2.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Dispatcher.HttpControllerDispatcher.<SendAsync>d__1.MoveNext()","InnerException":{"Message":"An error has occurred.","ExceptionMessage":"Exception has been thrown by the target of an invocation.","ExceptionType":"System.Reflection.TargetInvocationException","StackTrace":"   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)\r\n   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)\r\n   at System.Security.Cryptography.CryptoConfig.CreateFromName(String name, Object[] args)\r\n   at Umbraco.Core.StringExtensions.GenerateHash(String str, String hashType)\r\n   at Umbraco.Core.Models.UserExtensions.GetUserAvatarUrls(IUser user, ICacheProvider staticCache)\r\n   at AutoMapper.DelegateBasedResolver`2.Resolve(ResolutionResult source)\r\n   at AutoMapper.NullReferenceExceptionSwallowingResolver.Resolve(ResolutionResult source)\r\n   at System.Linq.Enumerable.Aggregate[TSource,TAccumulate](IEnumerable`1 source, TAccumulate seed, Func`3 func)\r\n   at AutoMapper.Mappers.TypeMapObjectMapperRegistry.PropertyMapMappingStrategy.MapPropertyValue(ResolutionContext context, IMappingEngineRunner mapper, Object mappedObject, PropertyMap propertyMap)","InnerException":{"Message":"An error has occurred.","ExceptionMessage":"This implementation is not part of the Windows Platform FIPS validated cryptographic algorithms.","ExceptionType":"System.InvalidOperationException","StackTrace":"   at System.Security.Cryptography.MD5CryptoServiceProvider..ctor()"}}}

### Steps to reproduce

1. Install Umbraco 7.12.4 using directions at https://our.umbraco.com/documentation/Getting-Started/Setup/Install/install-umbraco-manually
2. Start the site, follow setup, ensure you can access both the front-office and back-office
3. Turn on FIPS, as shown at https://our.umbraco.com/documentation/Reference/Security/Setup-Umbraco-for-a-Fips-Server/
4. Restart the site, and attempt to browse the front-office (this step results in an error related to a Lucene.NET class)
5. Add library to set Lucene.NET FIPS support
6. Restart the site and verify that you can browse the front-office
7. Attempt to log in to the back-office

### Expected result

I expect that at the end of those steps, I would be logged in to the back-office and able to browse around

### Actual result

The system stays at the login screen with no indication of an error.  Using Chrome's Developer Tools, on the Network tab, you can see that the PostLogin method resulted in an error, which is shown in the Specifics section above.

**Comment by Shazwazza** [comment]
What's odd is that there was some work involved with making it all FIPS compliant including the gravatar stuff, i guess at some point a change was made to undo that :( good catch and thanks!
