### ISSUE TITLE
[v8] Nightly doesn't bump version number on MyGet

### ISSUE THREAD

**Issue by aaronpowell** [umbraco/Umbraco-CMS#3730]
Starting a new issue on the back of https://github.com/umbraco/Umbraco-CMS/pull/3711#issuecomment-440579741

It seems that the MyGet feed for v8 keeps having the same version re-deployed.

I'm using the feed https://www.myget.org/F/umbracocore/api/v3/index.json and it seems that `alpha52` keeps getting updated.

Just makes it a bit of a pain to test against.

**Comment by zpqrtbnk** [comment]
Azure DevOps CI sets the version of Umbraco to `8.0.0-alpha.52.1234` where `1234` is Azure DevOps build number. Azure DevOps logs rightfully indicate _"Building: 8.0.0-alpha.52.1234"_ and the value shows in `Umbraco.Core` dll's attributes eg `ProductVersion`.

The idea was that ... that would be the NuGet package version too, hence you would get "updates" of `alpha.52.xxx`. And everything would be fine.

In fact... running our Powershell build script locally _does_ produce file `UmbracoCms.Core.8.0.0-alpha.52.1234.nupkg` which [NuGet Package Explorer](https://github.com/NuGetPackageExplorer/NuGetPackageExplorer) understands as being version `8.0.0-alpha.52.1234` indeed.

Now clearly the NuGet package metadata contains `8.0.0-alpha.52` and if I download the package from MyGet, it's missing the `.1234` part of the version. Something's wrong.

**Comment by zpqrtbnk** [comment]
Point is, our build script explicitely pass a `-Version` arg to NuGet `pack` command. Whereas Azure DevOps use the build-in NuGet task, using environment variable `UMBRACO_VERSION` for the version. That variable is set in our _Prepare Build_ task. Which runs... aha! Before our _Set Umbraco Version_ task. So when the variable is set, version is still `alpha.52`.

Don't think anything prevents us from running _Prepare Build_ after _Set Umbraco Version_. Going to test.

**Comment by zpqrtbnk** [comment]
Tests seem conclusive: Visual Studio sees `alpha.52.124` as an update to `alpha.52.125` and our nightly builds should now have the proper version. Moving issue to review. Can you let me know if it looks good to you?

**Comment by aaronpowell** [comment]
Just saw that the MyGet feed now includes the bumped build number, so I'd expect it'll allow an upgrade (previously it wasn't including the build suffix).

Given you're using Azure DevOps, would it be possible to make the pipeline public (https://docs.microsoft.com/en-us/azure/devops/organizations/public/about-public-projects?view=vsts)?

I've just done this with Chauffeur (https://aaronpowell.visualstudio.com/Chauffeur/_build?definitionId=14) and I use it to push to NuGet too (using a Release step) 😁.

**Comment by warrenbuckley** [comment]
Hi @aaronpowell 
After speaking with @nul800sebastiaan he tells me this

>Unfortunately can't make it public. Each build for a PR fails because the "contributor" is not allowed to output the artifacts on the server, it's some kind of security issue

Will close this now as we have the builds updating with a build version and Nuget is all hapy.

**Comment by aaronpowell** [comment]
@warrenbuckley sounds like I need to open another issue for that then 😜.
