### ISSUE TITLE
Angular implementation of public access dialogs

### ISSUE THREAD

**Issue by clausjensen** [umbraco/Umbraco-CMS#3738]
child of https://github.com/umbraco/Umbraco-CMS/issues/3474

We need to make sure public access can be assigned to a node, using updated views and dialogs with angular instead of the old webforms dialog.

It should be 1:1 based on the functionality of the old public access dialog, as rethinking this is not part of the scope for this task at the moment.

**Comment by kjac** [comment]
@clausjensen poke me if you want some help on this one. Even if it means I'll have to reimplement the "Single user protection" feature too 😉

**Comment by clausjensen** [comment]
@kjac Help is always appreciated as it allows us to work on some of the many other things we have to do 😄

For 8.0 we want to go for a 1:1 conversion of what the current functionality is even though we know it is broken. We simply want something to work - without having to resort to webforms as it was before. Redoing the single user protection thing would be after the initial release .. I agree it really needs to be done - but we'd like to put a little more time towards actually considering what the best solution is. We just can't "afford" to do that right now 🙈

**Comment by clausjensen** [comment]
There's btw a task for the C# parts of this issue as it will require some endpoints to do this in angular instead of the old stuff that worked via webforms:
https://github.com/umbraco/Umbraco-CMS/issues/3737

**Comment by kjac** [comment]
@clausjensen I'll have a look at both - they kinda go together.

**Comment by kjac** [comment]
@clausjensen OK I've got role based public access working 😄 and I've got an idea for user based access that might turn it into a really useful feature. I'll get back to you on that. In the mean time, here are some demos of the functionality so far:

### Add protection

![public-access-angular-1](https://user-images.githubusercontent.com/7405322/48977874-57e8a500-f0a3-11e8-8f83-30a6f50af6e3.gif)

### Remove protection

![public-access-angular-2](https://user-images.githubusercontent.com/7405322/48977875-5c14c280-f0a3-11e8-8ef5-6189714028d7.gif)

**Comment by madsrasmussen** [comment]
Hi @kjac, 

First of all, that looks amazing! A couple of smaller changes I would like to suggest.
- We shouldn't use toggles for selection. I think they should be swapped with regular checkboxes.
- I think we should put the label and add button on separate lines, so they aren't horizontally aligned.
- The tree picker still feels weird opening up on the other side of the screen, but I think that is OK for now. It was the same in the old dialog.

**Comment by kjac** [comment]
@madsrasmussen although I understand your point, I'm not entirely sure checkboxes are as visually pleasing in this case.

Also, moving the "Add" button to a separate line potentially introduces a pretty big distance between the node name and the "Remove" link when a page is chosen?

![image](https://user-images.githubusercontent.com/7405322/49107244-7b6b4580-f285-11e8-8844-85c8acfb112b.png)

**Comment by madsrasmussen** [comment]
I think the checkboxes work a lot better. I would position them on the left side of the label and make the label normal font weight though.

The problem with the remove button is a general problem throughout the back office. We will need to think of a solution that will work everywhere so I am not super duper concerned about that one right now (even though you are right).

**Comment by kjac** [comment]
@madsrasmussen 👍 I'll have a look at it. Once we're satisfied with the groups/roles dialog, we can address the single user dialog.

**Comment by madsrasmussen** [comment]
I am pretty happy with that 👍 🎉 Keep on rolling!

**Comment by kjac** [comment]
@madsrasmussen cool 😄 As for the "single user protection" dialog... wouldn't it be nicer to use a member picker instead of entering username/password of a new user? 

It'd be much more transparent and in line with the rest of the UX. Not to mention preventing a myriad of bugs and less-than-optimal scenarios. And if/when infinite editing includes members, it'll be possible to create a new user that way anyway.

**Comment by kjac** [comment]
PR in #3868
