### ISSUE TITLE
Umbraco does not update created data type for preview in LeBlender item.

### ISSUE THREAD

**Issue by Dafeg** [umbraco/Umbraco-CMS#3739]
Reproduction
------------

1. Create custom data type in Umbraco.
2. Create LeBlender with created data type in grid editor.
3. Create page and put LeBlender into this page like a new tab.
4. Create this page in tab "Content" and put to LeBlender some data.
5. Save and Publish created page.
6. Delete data type which has been created in step 1.
7. Create same data type according data type which has been created in step 1.
8.  Add new data type to LeBlender.
9. Go to created page in "Content" tab.

Now information(alias and Guid key) about data type which not exist in Umbraco comes to partial view which connected(It should be connected in step when LeBlender is created) to LeBlender.

If you try to get data type for rendering in preview, NullReferenceException occurs.  

### Expected result
Receiving of updated information to partial view about new data type was expected.

Umbraco version - 7.11.1
Thanks!

**Comment by Dafeg** [comment]
Umbraco version - 7.11.1
Thanks!

**Comment by dawoe** [comment]
Hi @Dafeg 

Thanks for the creating the issue. But I think it is not Umbraco cms related but to Leblender.
So it's better to create a post at their support forum on our : https://our.umbraco.com/packages/backoffice-extensions/leblender/bug-reports/

So I will close this issue. Feel free to re-open it if your discussion on our results in it being a Umbraco 
bug.

Dave [Community Pull Request team](https://umbraco.com/blog/introducing-the-new-cpr-team/)
