### ISSUE TITLE
Map AutoCorrection at time of Registration in Umbraco.

### ISSUE THREAD

**Issue by KajalSawant07** [umbraco/Umbraco-CMS#3749]
At time of Registration new User in Umbarco Site. Map AutoCorrection is not working may be you need to add google api which is paid api now. 

![image](https://user-images.githubusercontent.com/45280192/48930180-ca774a80-ef14-11e8-886c-1a5bfbf6564b.png)

**Comment by dawoe** [comment]
Hi @KajalSawant07 

Thanks for reporting this issue. But I see it is a issue related to the our.umbraco.com site. There is a seperate repository where you can create issues specific for this site : https://github.com/umbraco/OurUmbraco/issues

So could you create the issue there ? This issue will be closed.

Dave [Community Pull Request team](https://umbraco.com/blog/introducing-the-new-cpr-team/)
