### ISSUE TITLE
When defaultRenderingEngine is WebForms, template editor is broken

### ISSUE THREAD

**Issue by arknu** [umbraco/Umbraco-CMS#3750]
On Umbraco 7.12.4 we have a site that still has WebForms templates (yes, I know, but it has some rather complex usercontrols that we can't get rid of yet). I believe this is still supported in v7.

However, it seems that when the template editor was moved over to Angular, this was only done for Mvc templates. Indeed, the template controller returns paths to the old, WebForms-based template editor when defaultRenderingEngine is set to WebForms in umbracoSettings.config.

Unfortunately, the old WebForms-based template editor has been deleted from Umbraco. So the template editor is totally broken in this configuration, since the new template editor is hardcoded to use only Mvc templates.

Switching defaultRenderingEngine to Mvc show templates in the tree, but clicking on one displays a blank editor, since it is trying to load from ~/Views instead of ~/Masterpages. Saving produces a blank file in ~/Views.

### Steps to reproduce

1. Take an Umbraco site and switch defaultRenderingMode to WebForms.
2. Try editing a template.

### Expected result

Template is displayed for editing. As long as Umbraco still supports WebForms templates, the backoffice template editor needs to do so as well.

### Actual result

YSOD noting (correctly) that the WebForms template editor cannot be found.

**Comment by dawoe** [comment]
Hi @arknu 

Thanks for reporting this issue.  Will try to see if I can reproduce and see if we can fix it for one of the next versions of Umbraco

Dave [Community Pull Request team](https://umbraco.com/blog/introducing-the-new-cpr-team/)

**Comment by nul800sebastiaan** [comment]
Hi @arknu - Unfortunately, we don't plan to support editing WebForms templates from the backoffice any more. The amount of work to fix this doesn't weigh up to the few people still using Webforms. I posted a workaround in the issue here: https://issues.umbraco.org/issue/U4-9930

**Comment by arknu** [comment]
@nul800sebastiaan I understand. However, it should at least show some kind of meaningful error rather than a YSOD, which makes you think something is broken.

**Comment by nul800sebastiaan** [comment]
For us it makes no sense to spend any time on that though :)
