### ISSUE TITLE
Update editorconfig to not add curly braces around one-liners automatically

### ISSUE THREAD

**Issue by ssougnez** [umbraco/Umbraco-CMS#3752]
Hello,

people are using different coding styles. For example, some people prefer:

```
if (...)
    do();
```

When others prefer 

```
if (...)
{
    do();
}
```

Meaning that when someone edit an Umbraco file for a PR, autoformatting the code could lead to overriding one style with another. The main issue with that is it makes merges complicated. Indeed, the comparison screen will spot way more modifications than there actually are when all the one-liner blocks are surrounded by brackets.

Therefore, I think it would be a good idea to use an .editorconfig file to "force" coding style and maybe naming conventions. This would harmonize user contributions and ease the work of people who merge PR.

How can you help?
-------------------------------

I could create such a file but I don't think I'm the best candidate for this. Indeed, this file should be created by Umbraco HQ after a discussion between their members to define correct rules.

**Comment by dawoe** [comment]
Hi @ssougnez 

Thanks for reporting this issue. There is already a editorconfig file present : https://github.com/umbraco/Umbraco-CMS/blob/dev-v7/.editorconfig

It's only configured for whitespaces and tabs as far as I can see.

I think this will need HQ input so I will label it like that.

Dave [Community Pull Request team](https://umbraco.com/blog/introducing-the-new-cpr-team/)

**Comment by ssougnez** [comment]
Wow, really sorry for that. Indeed, while I was editing a file, I auto-formatted it and a bunch of brackets got added making the GIT compare more difficult.

Anyway, the post stays valid, maybe this file should be a bit improved to avoid this because when I look at it, it looks like the bare minimum configuration.

**Comment by nul800sebastiaan** [comment]
Hey @ssougnez - the reason we don't have an elaborate editorconfig file is that we don't want to "force" all that many things, to make it easier to contribute. I am more than happy to revert some changes people's Visual Studio makes. 

However, if there's a rule that says: when auto-formatting, don't auto-add curlies everywhere then that would be great. 

Is that possible? Can you create a PR for that? I want to take these changes on a case-by-case basis. So far it has not happened before and I didn't know there was even a VS option that would do this. Other than that we've not had many other issues with code styles so no need to be a.. style cop  👮‍♂️.. 😉

**Comment by ssougnez** [comment]
Yep, there is a setting for that. I'll make a PR in the upcoming days with that and I'll have a look at other settings to see if it makes sense to apply them. I agree with the fact of not being a stylecop, which is why I mainly took the curly brackets as an example ;-)

**Comment by Shazwazza** [comment]
Hi all, 

please know that in v8 this config file contains far more settings so please be mindful of that since we'll need to merge any changes from v7 -> v8 , see https://github.com/umbraco/Umbraco-CMS/blob/temp8/.editorconfig

**Comment by ssougnez** [comment]
Hi,

Just had a look at it and the diff is just about one new line (not contained in the v8 one) so the merge should not be a problem ;-)

**Comment by JimBobSquarePants** [comment]
>Hey @ssougnez - the reason we don't have an elaborate editorconfig file is that we don't want to "force" all that many things, to make it easier to contribute. I am more than happy to revert some changes people's Visual Studio makes.

This actually harms contribution. If styles are not enforced this decreases the readability and discoverability of the codebase as a whole.

**Comment by rustybox** [comment]
> This actually harms contribution. If styles are not enforced this decreases the readability and discoverability of the codebase as a whole.

Can also go the other way, I can't say I'd be jumping to contribute to a project with enforced GNU code style.
