### ISSUE TITLE
AuditRepository GetPagedResultsByQuery returns LogEntry Primary Key ID Instead of EntityId 

### ISSUE THREAD

**Issue by marcemarc** [umbraco/Umbraco-CMS#3758]
The AuditRepository's GetPagedResultsByQuery returns an IEnumerable of IAuditItems without referencing correctly the entity they are referencing.

Have a look at these lines from the method:

    // Get page of results and total count
            var pagedResult = Database.Page<LogDto>(pageIndex + 1, pageSize, translatedQuery);
            totalRecords = pagedResult.TotalItems;

            var pages = pagedResult.Items.Select(
                dto => new AuditItem(dto.Id, dto.Comment, Enum<AuditType>.ParseOrNull(dto.Header) ?? AuditType.Custom, dto.UserId)).ToArray();

You can see the pagedResults contains a paged set of LogDto items via PetaPoco

If you have a look at the LogDto object that maps to the database table

    internal class LogDto
    {
        [Column("id")]
        [PrimaryKeyColumn]
        public int Id { get; set; }

        [Column("userId")]
        public int UserId { get; set; }

        [Column("NodeId")]
        [Index(IndexTypes.NonClustered, Name = "IX_umbracoLog")]
        public int NodeId { get; set; }

You can see Id column represents the unique **id** of the log entry, but **NodeId** represents the object about which the entry is being made...

However when the new AuditItem is created for each result it is the Id and not NodeId that is passed into the constructor for AuditItem, but the constructor is expecting the ObjectId and not the Id of the log entry:

     public AuditItem(int **objectId**, string comment, AuditType type, int userId)
        {

This isn't noticeable in the AuditTrail as you select directly from the db for the content item you are on, and so it doesn't matter that the entity ids are mapped incorrectly however it is a problem when using the logResource's getPagedUserLog, as you can't get back the ids of the entities the user has interacted with!!

Reproduction
------------

In an angularJS controller, perhaps on a dashboard, make a request for the user log

    var userLogoptions = {
        pageSize: 10,
        pageNumber: 1,
        orderDirection: "Descending",
        sinceDate: new Date(2018, 0, 1)
    };

 logResource.getPagedUserLog(userLogoptions)
        .then(function (response) {
            console.log(response);
}

you'll see the nodeIds for the logged items, aren't actually entities that the log entry was triggered for! they are the ids of the audit log (save a new item) and refresh and you'll see the nodeid increments by 1!

### Bug summary
GetPagedResultsByQuery in AuditRepository doesn't return log entries with references to the entities that triggered the entry.

### How to fix

Update line 90 of AuditRepository.cs to be:
 var pages = pagedResult.Items.Select(
                dto => new AuditItem(dto.NodeId, dto.Comment, Enum<AuditType>.ParseOrNull(dto.Header) ?? AuditType.Custom, dto.UserId)).ToArray();

### Specifics

![image](https://user-images.githubusercontent.com/260802/48986489-a03cad00-f10d-11e8-8a7a-90b3067f93e9.png)

**Comment by RobertCopilau** [comment]
Hey @marcemarc, thanks for the great issue report :D. 
The issue has been fixed here -> https://github.com/umbraco/Umbraco-CMS/pull/3759, therefore, I will be closing this.
