### ISSUE TITLE
Squashed drop-down empty selection in template query builder

### ISSUE THREAD

**Issue by RobertCopilau** [umbraco/Umbraco-CMS#3765]
It seems that when there is nothing selected on the dropdown, the empty selection is squashed, which looks out of place.
It would be nice to have the same height as other dropdowns that have an item selected :).
![squashed empty dropdown.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5b151a952d7cd20011c4533d/125516c66e82c728ace21e0d46fb858f22918bac8ba9ba4eb449e9d42d5428632d0bb42532c9a138ad4d71040c1b5ca6535d0d11fead8e28a3e26a7489590bedd06c5a71933445fabd9003ad43eb7edf10d8eff6df0ed2e22f24e0818e4a3a1d071b81f85436a69b4bda15.jpg)

**Comment by kjac** [comment]
@RobertCopilau must be some browser specific issue? It looks fine to me on both Chrome and Firefox:

![image](https://user-images.githubusercontent.com/7405322/49037805-835eb300-f1bb-11e8-92c8-6a584f87b87d.png)

**Comment by nul800sebastiaan** [comment]
@RobertCopilau I think you mentioned our own Kenneth instead of @kjac there! 😉

**Comment by RobertCopilau** [comment]
Oops :D

**Comment by nul800sebastiaan** [comment]
Fixed in #3784
