### ISSUE TITLE
Remove bootstrap slider

### ISSUE THREAD

**Issue by madsrasmussen** [umbraco/Umbraco-CMS#3767]
Bootstrap slider needs to be changed to a slider with no dependency on bootstrap or jquery. We have chosen nouislider (https://refreshless.com/nouislider/) as the new slider for Umbraco.

We need to update the slider property editor to use the new slider instead.

**Comment by madsrasmussen** [comment]
PR: https://github.com/umbraco/Umbraco-CMS/pull/3723

The PR removes all files related to bootstrap slider and updates the property editor to use the new slider plugin instead. The PR also cleans up the slider prevalues and tries to add some best practices for sliders so configuration isn't overwhelming when you open the configuration and so the UX is as good a possible for the build in slider. If more advanced configuration is needed the new plugin is made as a component and documentation has been added so it is easy to build a custom property editor based on that.

The PR removes the following prevalues from the slider property editor. 
* Orientation
* Precision
* Handle
* Tooltip
* Tooltip split
* Tooltip format
* Tooltip position
* Reversed
* Ticks
* Ticks positions
* Ticks labels
* Ticks snap bounds

Prevalues still existing on the slider property editor¨
* Enable range
* Initial value
* Initial value 2
* Minimum value
* Maximum value
* Step increments

The goal is that the new slider wont break with the old configuration/values. Some of them just won't apply because they can't be edited.

The new slider will always show a label with the selected value. The new slider will always show a tick for the minimum value and for the maximum value so you always can see the scale of the slider. When a range is allowed the new slider will always show a label for both handles.

![Screenshot 2018-11-26 15.38.42.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5b1e362dcaef300011086a3e/125516c66e82c728ace21e0d46db978826878dba87e6ab03f60da1cc6417763e7b52e37a25cbb070f1162943434d0eee1e020a17b8eb8339a3e46972de5b08e8853b5b77c33d11adb9871aea08ee768e5d99a4fedb1294b7607caddecd5d340c041f83fe5831a39b4fcb59f148e24e52b65e.png)


**How to test:**
Before checking out the branch
- [ ] Set up a doc type with a couple of different slider configurations so we can make sure the new sliders still works with the old configs.
- [ ] Add a node where you select different values for the sliders.

Check out new branch
- [ ] Make sure config is handled correctly in the new sliders (range, min value, max value, init values etc.)
- [ ] Make sure you can use the sliders.

**Comment by RobertCopilau** [comment]
It works!
Merging.
