### ISSUE TITLE
HTTP links/URIs in EmbeddedMedia.config files

### ISSUE THREAD

**Issue by emanuelb** [umbraco/Umbraco-CMS#3775]
The _EmbeddedMedia.Release.config_ and _EmbeddedMedia.config_ files in: Umbraco-CMS/src/Umbraco.Web.UI/config/
https://github.com/umbraco/Umbraco-CMS/blob/master/src/Umbraco.Web.UI/config/EmbeddedMedia.Release.config
https://github.com/umbraco/Umbraco-CMS/blob/master/src/Umbraco.Web.UI/config/EmbeddedMedia.config

Contain the below HTTP links that are located on servers that support HTTPS as well:
http://www.flickr.com/services/oembed/
http://www.slideshare.net/api/oembed/2
http://www.kickstarter.com/services/oembed
http://embed.gettyimages.com/oembed
http://www.polleverywhere.com/services/oembed/
http://polldaddy.com/oembed/
http://www.ifttt.com/oembed/
http://api.instagram.com/oembed
http://soundcloud.com/oembed
http://www.dailymotion.com/services/oembed
http://www.hulu.com/api/oembed.xml
http://vimeo.com/api/oembed.xml
http://www.ted.com/talks/oembed.xml

all the above used URLs except the following support HTTPS:
        https://stream.umbraco.org/oembed (invalid CN)
        https://www.rdio.com/api/oembed/ (connection fail)
        https://www.screenr.com/api/oembed.xml (connection fail)

Fix:

1. replace 'http' with 'https' when possible.
2. ensure the links are valid (some return 404, update if needed)
3. fix invalid CN issue in SSL cert used on https://stream.umbraco.org/

**Comment by nul800sebastiaan** [comment]
I've marked this as "Up for grabs" so that you or someone else coming along could create a pull request for it.

**Comment by bielu** [comment]
@nul800sebastiaan as I didn't see any activity on that bug, I notice few things:
rdio.com and screenr.com are closed, it means only https://stream.umbraco.org should be fixed for https and we could clean and replace everything to https :)

**Comment by nul800sebastiaan** [comment]
This issue has been in the `up for grabs` state for quite a while now and it seems nobody is ready to pick this one up.

For now we'll close this issue to prevent the list of `up for grabs` from becoming very stale. We're happy to re-open it if someone still thinks it's good to work on this. 

If anyone is about to pick this issue up to fix it, make sure to test first if you can reproduce the problem in the latest version before you start to work on it.

Thanks!
Sebastiaan on behalf of Umbraco HQ.
