### ISSUE TITLE
Extra configuration parameter for date property editor: UseCurrent

### ISSUE THREAD

**Issue by dsbaiz** [umbraco/Umbraco-CMS#3776]
Is it possible to add an extra configuration parameter to the Date Property editor: UseCurrent.
Currently the UseCurrent parameter of the bootstrap datepicker is always set to true in code.
It would be nice if the user had the choice to automatically fill the current date on click, or keep the date editor empty on click so they can start typing the current date manually.

**Comment by nul800sebastiaan** [comment]
I've marked this as "Up for grabs" so that you or someone else coming along could create a pull request for it.

**Comment by kjac** [comment]
PR in #3794
