### ISSUE TITLE
When a node is opened through content picker don't allow editing doc type and template

### ISSUE THREAD

**Issue by madsrasmussen** [umbraco/Umbraco-CMS#3777]
To keep every simple and focused we want to prevent editing the doctype and template when a node is opened through a content picker. 

The main actions, in this case, will often be to verify/update content.

**Comment by madsrasmussen** [comment]
PR: https://github.com/umbraco/Umbraco-CMS/pull/3778

How to test:
- Create a node with a content picker. Make sure to enable the "Allow open" feature on the content picker. Go to the node and select a couple of other nodes.
- [ ]  Click on the open button on the selected node. Make sure you can't edit the doctype and template on the "info"-app.
- [ ] Make sure you can still edit the doctype and template on a regular node on the "info"-app.

**Comment by RobertCopilau** [comment]
Code looks good and it works.
Merging.
