### ISSUE TITLE
Add dirty tracking for slider and dateTime picker

### ISSUE THREAD

**Issue by RobertCopilau** [umbraco/Umbraco-CMS#3779]
Currently, the slider and DateTime properties do not mark the form as dirty when their values change.
That, however, should change.

<h4>How to reproduce</h4>

* Create a document type and add only sliders and date time editors
* Create a node based on that doc type and add some content to the properties
* Without saving, click away from the current editor, no "Discard change" pop-up will be presented

**Comment by kjac** [comment]
I've got this working for the slider... will have a look at the datetime picker later.

![slider-set-dirty](https://user-images.githubusercontent.com/7405322/49136705-c4a1b080-f2ea-11e8-8988-5e3873d0aaa7.gif)

**Comment by kjac** [comment]
PR in #3788

**Comment by nul800sebastiaan** [comment]
Fixed in https://github.com/umbraco/Umbraco-CMS/pull/3788
