### ISSUE TITLE
no Item added to the history on the first action on a content

### ISSUE THREAD

**Issue by nikola187erz** [umbraco/Umbraco-CMS#3785]
When doing an action e.g. a "save and publish" on the content for the first time, no item is added to the history under the info tab. 

### Bug summary
When doing a action e.g a "save and publish" on a item for the first time on a content, no publish date is generated neither added to the "history" under the "info" tab. If you look at the audit of a post with the e.g. 

`var auditItems = ApplicationContext.Services.AuditService.GetPagedItemsByEntity(item.Id, 0, int.MaxValue, out totalRecords, Direction.Ascending);` 

there is no item inside "auditItems" on the first action. After the first action, all the following actions get written correctly and also added to the history. 

### Specifics
Umbraco version: 7.12.3 assembly: 1.0.6837.12334
Browser: Opera version 53
Tested inside chrome too. Same behavior like in Opera.
Picture of the empty audit when debugging: ![Gif of the empty audit](https://i.imgur.com/wGwVtze.png)

### Steps to reproduce
1. Under the content area inside the Umbraco CMS, create a new item
2. Publish the newly created item
3. Click on the item
4. Direct to the "info" tab
5. Inside the history, no item is added for the first publish

Gif of the issue:
![Gif of the issue](https://our.umbraco.com/media/upload/322c40d6-9168-44c4-85ec-2542dd5e7189/repron.gif)

### Expected result
On the first action on a content, a date is added to the audit and to the history of the content.

### Actual result
No date is added to the history neither to the audit. No error message occurred.

**Comment by nul800sebastiaan** [comment]
Ah, strange.. I can reproduce this.

I've marked this as "Up for grabs" so that you or someone else coming along could create a pull request for it.

**Comment by nul800sebastiaan** [comment]
Fixed in: https://github.com/umbraco/Umbraco-CMS/pull/3789
