### ISSUE TITLE
Macro partial snippets shouldn't rely on javascript libraries used for the back office

### ISSUE THREAD

**Issue by madsrasmussen** [umbraco/Umbraco-CMS#3787]
Currently, we have Macro partial snippets that include jquery, jquery-validation, and jquery-validation-unobtrusive loaded from the Umbraco/Lib/ folder.

We shouldn't have any dependencies from MVC views on files from the back office. We should instead add code recommendations to include the validation libraries the developer wants.

With the current solution, we can't upgrade back office libraries without risking to break websites.

We also only ship, jquery-validation and jquery-validation-unobtrusive because of these snippets. They are not used in the back office.

Macro partials where this is used:
- edit profile
- login
- login status
- register member

**Comment by kjac** [comment]
PR in #3810

**Comment by nul800sebastiaan** [comment]
Fixed in https://github.com/umbraco/Umbraco-CMS/pull/3810
