### ISSUE TITLE
Upgrade jquery to latest

### ISSUE THREAD

**Issue by madsrasmussen** [umbraco/Umbraco-CMS#3793]

**Comment by madsrasmussen** [comment]
PR: https://github.com/umbraco/Umbraco-CMS/pull/3792

I have upgraded jquery to latest version. My approach was to install jquery migrate and check for any broken stuff. Everything seemed to still work fine after the upgrade but we got a bunch of depricated api's that they recommended moving away from. I have updated the code so we no longer use these in our own code. We still have plugins using these but it is not a problem before jQuery 4.

***How to test:**
I don't think a whole lot of testing is needed for this one. We will catch if any bugs should have slipped through the cracks when moving forward. Jquery-migrate didn't find anything so I think we should be fine.

* Sanity check code for updates.
* Make sure the back office still runs. Do a couple of tests you think is needed based on the code changes. It could be:
-- Add a couple of doc types
-- Edit a bit of content
-- Upload some images
-- Edit a template

**Comment by dawoe** [comment]
Hi @madsrasmussen 

Where is jQuery being used  in the backoffice ?. And the question is do we still need it ? Most things can be done with plain javascript nowadays.

Dave

**Comment by madsrasmussen** [comment]
We still use it quite a lot and we still use a couple of libraries that are dependant on jQuery. We are working towards getting it removed but it won't be today 😃Now it is the latest version at least.

**Comment by dawoe** [comment]
Would be nice to have some clean  up done.

Will keep an eye out if I work on something that uses jQuery and can be replaced by vanilla js I will update it

**Comment by warrenbuckley** [comment]
Tested & all happy. If we run into any problems then we will fix them along the way
