### ISSUE TITLE
Add optional sender name in umbracoSettings.config email settings

### ISSUE THREAD

**Issue by danbramall** [umbraco/Umbraco-CMS#3797]
In umbracoSettings.config it's possible to add an email address which acts as the sending email for transactional notifications (password reminder etc).  I can't see a way currently to specify a sender name along with the email though.  It looks as if the sender name is just taken as the first part of the email address (e.g. everything before @).

It would be great to be able to specify both email address and sender name in the config, perhaps falling back to the current behaviour if no sender name is supplied, for backwards compatibility.

**Comment by kjac** [comment]
Hey @danbramall. You can do that already with the current config. It works just like the `from` attribute on the `smtp` configuration in `web.config`; you just need to specify the sender name first, followed by the email in XML-encoded `<>` - like so:

```xml
<notifications>
  <!-- the email that should be used as from mail when umbraco sends a notification -->
  <email>Notifications from my site &lt;no-reply@mysite.com&gt;</email>
</notifications>
```

This should give you an email looking something like this:

![image](https://user-images.githubusercontent.com/7405322/49246490-57d70500-f415-11e8-967c-6ef0f7da229f.png)

Having said that it's not really terribly obvious how to do it, so I'll prepare a PR with an instruction in the comment above the `<email/>` element.

Thanks for pointing it out 😄

**Comment by kjac** [comment]
PR in #3804

**Comment by danbramall** [comment]
@kjac Awesome, thanks! :)
