### ISSUE TITLE
Upgrade client dependencies

### ISSUE THREAD

**Issue by madsrasmussen** [umbraco/Umbraco-CMS#3799]
We need to get the last client side dependecies upgraded that has been yet.

**Comment by madsrasmussen** [comment]
Review and merge PR for #3793 before this PR. This PR is build on top of that one.

PR: https://github.com/umbraco/Umbraco-CMS/pull/3798

I have upgraded the following packages to the latest version
* ace-builds
* angular-ui-sortable
* bootstrap-social
* clipboard
* diff
* moment
* signalr
* spectrum-colorpicker
* tinymce
* typeahead.js

The PR also removes the moment libraries which include locales. We don’t need to ship with those because we lazy load the user languages from a language file instead. The PR also removes Bootstrap 2 javascript files.

How to test:
- [ ] Make sure ace editor still works (You can find one in template, scripts, etc editors)
- [ ] Make sure you can copy the password when creating a new user
- [ ] Make sure you can change the user language and dates will be formatted correctly. (Check audit trail on info-app)
- [ ] Make sure you can that drag and drop sorting still works. (You can find one in content picker, doc type editor, etc).
- [ ] We can’t test bootstrap-social upgrade because the functionality using it is currently not implemented so we will test when it gets reimplemented.
- [ ] Typeahead can’t be tested as tags don’t work. But it breaks in the same way so that is good 😄
- [ ] Make sure the rich text editor still works and both modes can be used.

**Comment by warrenbuckley** [comment]
All tested & happy :)
