### ISSUE TITLE
V8 - Event stream 3.3.6 

### ISSUE THREAD

**Issue by janvanhelvoort** [umbraco/Umbraco-CMS#3811]
Event-stream 3.3.6 is removed from NPM, something due crypto mining. [Link](https://github.com/dominictarr/event-stream/issues/116)
But inside the package-lock.json from `Umbraco.Web.UI.Client` there is a reference to this package.

Reproduction
------------

inside the `Umbraco.Web.UI.Client` project folder: command: `npm install`

`404 Not Found: event-stream@https://registry.npmjs.org/event-stream/-/event-stream-3.3.6.tgz`

### Expected result

Successfully install all dependencies.

### Actual result

Didn't install any dependencies,

**Comment by janvanhelvoort** [comment]
possible solutions:

- Temporary remove `package-lock.json` from repository and re-add it when v8 is ready?
- Remove `package-lock.json` local, run `npm install` and check in the new generates `package-lock.json`, but there are a lot more changed dependencies?

Workaround local for now, remove `package-lock.json` local for now and run `npm i`

**Comment by karankrizz** [comment]
[210](https://github.com/creativetimofficial/ct-material-dashboard-pro/issues/210) This resolved my issue

**Comment by nul800sebastiaan** [comment]
I'll need to re-run the trial and error stuff I did for v7.. it's a bit of a pain and I have no idea why it at some point finally worked..

![image](https://user-images.githubusercontent.com/304656/49444574-d1814100-f7cf-11e8-8699-ebdb4a80dd96.png)

**Comment by nul800sebastiaan** [comment]
Got this all fixed up in `temp8` now as well! 👍
