### ISSUE TITLE
Upgrade dev-dependencies

### ISSUE THREAD

**Issue by madsrasmussen** [umbraco/Umbraco-CMS#3816]
Upgrade all dev-dependencies to the latest version.

I haven't upgraded gulp to v4. It broke our docs build so I have left it out for now.

PR: https://github.com/umbraco/Umbraco-CMS/pull/3815

**Comment by warrenbuckley** [comment]
`gulp build` `gulp dev` and gulp docserve` all work fine and the Powershell build script is still happy.

All good :)
