### ISSUE TITLE
Include grid render template for Bootstrap 4

### ISSUE THREAD

**Issue by bjarnef** [umbraco/Umbraco-CMS#3817]
In Umbraco v7 it has been shipped with a grid render template for Bootstrap v2 and v3. Since Boostrap 4 now is available, should we add a grid render for Boostrap 4?
https://github.com/umbraco/Umbraco-CMS/tree/temp8/src/Umbraco.Web.UI/Views/Partials/Grid

Also consider it we still need to ship Umbraco with Bootstrap v2 template.

**Comment by nul800sebastiaan** [comment]
Thanks @bjarnef - makes sense! 👍 

In v7 we don't want to remove anything, but adding a Bootstrap 4 template is great.

In v8 we can remove v2 and v3 of Bootstrap and make the default grid template Bootstrap 4.

I've marked this as "Up for grabs" so that you or someone else coming along could create a pull request for it.

**Comment by nul800sebastiaan** [comment]
Just noticed that in the Grid2 branch there is a Bootstrap4 template included: https://github.com/umbraco/Umbraco-CMS/tree/temp8-grid2

https://github.com/umbraco/Umbraco-CMS/tree/temp8-grid2/src/Umbraco.Web.UI/Views/Partials/Grid2

**Comment by bjarnef** [comment]
Cool 😊😎 Not sure if Grid2 will be part og v8 or v8.1? Otherwise this could be copied and included in latest `dev-v7` and `temp8`. I noticed it has the class `umb-grid2` - I think this should just be `umb-grid`.

**Comment by bjarnef** [comment]
I am not sure if we both need a Bootstrap4 and Bootstrap4-Fluid since the fluid layout can be controlled by a settings property.

**Comment by nul800sebastiaan** [comment]
Grid2 won't make it to v8.0.0 yet, so yes, it would be great to include just the BS4 templates at least!

**Comment by nul800sebastiaan** [comment]
This issue has been in the `up for grabs` state for quite a while now and it seems nobody is ready to pick this one up.

For now we'll close this issue to prevent the list of `up for grabs` from becoming very stale. We're happy to re-open it if someone still thinks it's good to work on this. 

If anyone is about to pick this issue up to fix it, make sure to test first if you can reproduce the problem in the latest version before you start to work on it.

Thanks!
Sebastiaan on behalf of Umbraco HQ.
