### ISSUE TITLE
Tags are Completely Broken (TM)

### ISSUE THREAD

**Issue by zpqrtbnk** [umbraco/Umbraco-CMS#3821]
child of #3674

Tags... have issues. The property value part is good, but the database (tags and relations) is not. When changing from/to in/variant, it's not always properly updated - and goes out of sync with the property value. Also, when un/publishing branches, or un/trashing branches, it's not properly updated.

We need to *not* delete tags when they are trashed/unpublished. This is expensive and there's no non-extra expensive way to get the tags back when branches are untrashed/unpublished. Instead we'll keep the tag references in the db table and then filter on published in the tag queries.

Currently because we only store published tags in the tags table it also means that the lookahead is broken because it can only prompt you for published values which isn't good.

* The lookahead also needs to do a refresh to `GetTags` whenever a content item is saved, else it's cached values will already be stale
* Also there's no way to get a *page* of tagged items, etc.

also see https://issues.umbraco.org/issue/U4-8442

**Comment by Shazwazza** [comment]
I have that various methods in Articulate for getting content by tags and vice versa, thought i had ported most to core by now but maybe not.

**Comment by clausjensen** [comment]
Talked to @zpqrtbnk and we think tags are done. If there's any specific issues still remaining we should open up new issues for those.
