### ISSUE TITLE
There is no current PublishedContentRequest, it must be initialized before the RenderRouteHandler executes

### ISSUE THREAD

**Issue by ronaldbarendse** [umbraco/Umbraco-CMS#3826]
We're getting the following exception multiple times a day on multiple sites:
```
System.NullReferenceException: There is no current PublishedContentRequest, it must be initialized before the RenderRouteHandler executes
   at Umbraco.Web.Mvc.RenderRouteHandler.GetHttpHandler(RequestContext requestContext)
   at System.Web.Routing.UrlRoutingModule.PostResolveRequestCache(HttpContextBase context)
   at System.Web.Routing.UrlRoutingModule.OnApplicationPostResolveRequestCache(Object sender, EventArgs e)
   at System.Web.HttpApplication.SyncEventExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute()
   at System.Web.HttpApplication.ExecuteStepImpl(IExecutionStep step)
   at System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously)
```

Reproduction
------------

### Bug summary
Apparently the request URL does trigger the `UriRoutingModule`, but somewhere in the routing pipeline, there is an assumption the `PublishedContentRequest` is set before getting the HttpHandler...

### Specifics/steps to reproduce
The requested URLs all look like `/index.php/Home/AppUpload/commentUpload`. Using the latest Umbraco 7.12.4 and can be easily tested using https://umbraco.com/index.php/Home/AppUpload/commentUpload.

### Expected result
Not routing the request, but returning a 404 page as there's no content on that URL.

### Actual result
Unhandled exception thrown, causing a 500 error page.

**Comment by ronaldbarendse** [comment]
@nul800sebastiaan IIS Express doesn't have the same handlers configured as IIS (running on Azure or hosting providers), in this case probably regarding PHP support. This is also why I've added the example for umbraco.com, as that's also returning the error.

So please test it again on a real hosting scenario or install IIS using Web PIs 'Recommended Server Configuration for Web Hosting Providers'.

**Comment by Vrijdagonline** [comment]
@ronaldbarendse Did you find anything? I'm having the same issue. With lots of errors. You are probably right that it seems to be related to the PHP extension as I can see, that in my case, calls to for example "index.php/guestbook/entry/add" is the reason for lots of errors.

Interesting...

**Comment by ronaldbarendse** [comment]
@nul800sebastiaan Can you reopen this issue? Please try this on a clean Umbraco Cloud solution (with debug on), as that does throw the exception from Umbraco code.

**Comment by nul800sebastiaan** [comment]
This issue has been in the `up for grabs` state for quite a while now and it seems nobody is ready to pick this one up.

For now we'll close this issue to prevent the list of `up for grabs` from becoming very stale. We're happy to re-open it if someone still thinks it's good to work on this. 

If anyone is about to pick this issue up to fix it, make sure to test first if you can reproduce the problem in the latest version before you start to work on it.

Thanks!
Sebastiaan on behalf of Umbraco HQ.

**Comment by priteshtechark** [comment]
This is randomly generating every day. Logs is also not enough to find exact location of the issue. It is very difficult to simulate.

**Comment by Slipoch** [comment]
+1 this needs fixing.

**Comment by ronaldbarendse** [comment]
@Slipoch This issue has been `up for grabs` for a very long time and no one has picked it up... If you think it still needs fixing, you're welcome to submit a PR or add more information to this issue to help others get started on one!
