### ISSUE TITLE
IPublishedContentQuery.Search needs to support culture

### ISSUE THREAD

**Issue by Shazwazza** [umbraco/Umbraco-CMS#3828]
child of #3530
requires #3535

**Be sure to review #3535 first!**

IPublishedContentQuery.Search needs to support culture so that searching can be contextual to a language automatically

PR: https://github.com/umbraco/Umbraco-CMS/pull/3892 

... see notes below

**Comment by Shazwazza** [comment]
Have updated the first 2 methods to accept a culture:

```cs
IEnumerable<PublishedSearchResult> Search(string term, string culture = null, string indexName = null);

IEnumerable<PublishedSearchResult> Search(string term, int skip, int take, out long totalRecords, string culture = null, string indexName = null);
```

When a culture is specified it will go find all culture specific names for the culture specified (i.e. `myField_en-us` if the culture was `en-us` or `en-US`), then it will perform a managed search across all of these culture fields for the term specified, it will also add a mandatory query argument for "varies by culture" since if the user is searching on a culture, the document must have this flag.

The 2 methods accepting `IQueryExecutor` cannot have  culture specified, since these methods are based on the fluent search API which the developer builds up themselves.

**Comment by zpqrtbnk** [comment]
code review is ok

Testing, having issues. I have a content item which is variant, has different names on two cultures. A `Search("Home")` or `Search("Maison")`, with `en-US` being the default lang, works. But a `Search("Home", "en-US")` does not. And `Search("Maison", "fr-FR")` does not either.

Checking the index, I can see that Name, Name_en-us, etc are all set correctly. Querying the External Index from the dashboard, works. Have republished the content item.

I... have tried to look into `PublishedContentQuery` but cannot figure out what's wrong.

I have tried to rebuild the index but then it becomes weirder. I can instantly rebuild the Internal Index, but the External Index rebuild never completes (keeps doing PostCheckRebuildIndex forever).

**Comment by zpqrtbnk** [comment]
more details: I have physically deleted the indexes, and restarted the site - indexes are rebuilt, but it does not change a thing (search fails, cannot rebuild external index)

**Comment by zpqrtbnk** [comment]
Problem with search is now issue https://github.com/umbraco/Umbraco-CMS/issues/3920

Rest is OK, merging the PR now
