### ISSUE TITLE
ExamineIndex configuration...

### ISSUE THREAD

**Issue by claudiomorandi** [umbraco/Umbraco-CMS#3829]
I'd need to know the best configuration for ExamineIndex to avoid write locks.
It's a multiple websites (actually 8 websites) project hosted on a load balancing environment (Azure infrastructure but not as WebApp - just normal virtual servers with load balancer - 2 reverse proxies - 2 web servers).
It could be that many iis processes try to access the examineindex files at same time.
Can you help me to configure it?
P.S.
I actualy see some types of error in logs:
- ERROR Umbraco.Core.UmbracoApplicationBase - Unhandled exception in AppDomain (terminating)
System.IO.FileNotFoundException: Could not find file 'D:\xxx\xxx\xxx\App_Data\TEMP\ExamineIndexes\External\Index\_201.fnm'.
- ERROR UmbracoExamine.DataServices.UmbracoLogService - Provider=ExternalIndexer, NodeId=-1
System.Exception: Error indexing queue items,System.IO.IOException: Cannot overwrite: D:\xxx\xxx\xxx\App_Data\TEMP\ExamineIndexes\External\Index\_21p.tvx
- ERROR Umbraco.Web.Editors.MediaController - Unhandled controller exception occurred
System.AggregateException: Exceptions were thrown by listed actions. ---> Lucene.Net.Store.LockObtainFailedException: Lock obtain timed out: SimpleFSLock@D:\xxx\xxx\xxx\App_Data\TEMP\ExamineIndexes\External\Index\write.lock
   at Lucene.Net.Store.Lock.Obtain(Int64 lockWaitTimeout)

**Comment by nul800sebastiaan** [comment]
Hey there @claudiomorandi - that would be a great question for the forums: https://our.umbraco.com/

Also make sure to review the documentation for your appropriate Examine version: https://our.umbraco.com/Documentation/Getting-Started/Setup/Server-Setup/Load-Balancing/flexible#luceneexamine-configuration

**Comment by skartknet** [comment]
This keeps happening with Umbraco 8. We have followed the recommended settings for webapps on the docs.

**Comment by Shazwazza** [comment]
I have just set this up last week along with 8.6.5 along with staging slots & always on, and I have no issues with publishing, slot swapping, etc... . If you have steps to replicate from a vanilla install - and be sure to be using 8.6.5+ please open a new issue with those steps.
