### ISSUE TITLE
RTE editor in grid collapsed/disappears after reordering

### ISSUE THREAD

**Issue by perplexErik** [umbraco/Umbraco-CMS#3835]
Hi,

Some of our customers are reporting the loss of RTE content in the grid.
What ( i think) they mean is that the RTE elements in the grid 'disappear'.

Reproduction
------------
If you're filing a bug, please describe how to reproduce it. Include as much
relevant information as possible, such as:

### Bug summary

RTE elements in the grid often get hidden after sorting the grid elements

### Specifics
**Umbraco version 7.10.4 assembly: 1.0.6684.15725**

Reproduced in browsers:
Chrome Version 71.0.3578.80 (Officiële build) (64-bits)
FireFox 63.0.3 (32-bits)

### Steps to reproduce

My reproduction path is: 
- I edit a page which has a grid element with 3 columns 
- Add 3 RTE editors with some text (1 in each column) 
- Select "Reorder" and start shuffling the RTE's between the columns. 
- Select "i am done reordering".

Additional information can be found in this support ticket:
https://support.umbraco.com/hc/en-us/requests/39612

### Expected result

All RTE's (including content) that were visible before sorting, are also visible after reordering.

### Actual result

 1 or more RTE editors are no longer visible after reordering

### Additional info
Additional information can be found in this support ticket:
https://support.umbraco.com/hc/en-us/requests/39612
including:
- screenshots, 
- screen capture,
- URL for standalone Umbraco installation
 (with logon credentials)

**Comment by nul800sebastiaan** [comment]
Hi @perplexErik ! I think we've already fixed this issue in the upcoming 7.13.0: https://github.com/umbraco/Umbraco-CMS/pull/2876

Additionally, we've got a few other fixes in for rich text editors:
https://github.com/umbraco/Umbraco-CMS/issues/3231
https://github.com/umbraco/Umbraco-CMS/issues/3058

If you can still reproduce the problem in a nightly build of v7.13 (just try out one of the latest ZIP files here: http://nightly.umbraco.org/?container=umbraco-continuous ) then feel free to re-open this issue with reproduction steps.

**Comment by Ghost1026** [comment]
We experience the problem in version Umbraco 7.15.3

and also in generel when we open a page under layouts..
