### ISSUE TITLE
MemberService saving twice from BackOffice - v7.12.4

### ISSUE THREAD

**Issue by voltaek** [umbraco/Umbraco-CMS#3838]
### Bug summary

When I update some properties for a Member via the BackOffice, the the record is saved twice. As a side effect, this results in the `Saving` and `Saved` events of the MemberService being fired twice, also. Both the `Email` and `Comments` properties cause multiple saves, while others like the `Username` field does not.

### Specifics

Using Umbraco v7.12.4, duplicate saves occur when the fields for properties of a Member (at minimum `Email` and `Comments`) are updated and Save is clicked in the BackOffice. When `Username` is updated, duplicate saves do not occur. It appears the same data is saved each time.

I have a custom member type I'm using, but this issue is occurring with the default properties of a member, so I don't think it's related to that at all.

I came across this when wiring up event handlers for keeping the Username and Email property values the same, but A) even without any code in the handlers, the record is still saved twice, and B) When I do have my code in the event handlers and I call `MemberService.Save()` (with `raiseEvents` set to `false`), when updating `Username` from the BackOffice, the save happens only once (as expected), and my code that does member value updates without raising events works as expected.

### Example Code

There isn't really any code to show for the save happening multiple times, as that is being done by the BackOffice itself, but here is how I have my event handlers wired up:

```
protected override void ApplicationInitialized(UmbracoApplicationBase umbracoApplication, ApplicationContext applicationContext)
{
	base.ApplicationInitialized(umbracoApplication, applicationContext);
	Umbraco.Core.Services.MemberService.Saving += MemberService_Saving;
	Umbraco.Core.Services.MemberService.Saved += MemberService_Saved;
}

internal void MemberService_Saving(IMemberService sender, Umbraco.Core.Events.SaveEventArgs<IMember> e)
{
    /* code looking at what's being saved here */
}

internal void MemberService_Saved(IMemberService sender, Umbraco.Core.Events.SaveEventArgs<IMember> e)
{
    /* code looking at what was saved here */
}
```

**Comment by voltaek** [comment]
For anyone looking to work around this bug until it is fixed, I placed the changes to the record I wanted to perform during in the `Saved` event (which I calculated during the first `Saving` event occurrence) into an entry in `HttpContext.Current.Items`. These entries only persists for the current request, so I can apply the same change to the record inside my `Saved` event handler after each save. The duplicate saves of the record were undoing my changes the I was making in `Saved` after the first save, so instead I just make my changes each time `Saved` is called from what I placed using that entry. Be sure to call `MemberService.Save()` with the `raiseEvents` param set to `false`.

**Comment by Shazwazza** [comment]
You shouldn't ever save the same entity inside of it's own "Saved" event, that is what "Saving" is for. You can update the value in the model you want in "Saving" and it will be Saved, you shouldn't use any services, etc.. during "Saving"

Members get saved twice because 2 different things need to manipulate the data: the service and the membership provider since the membership provider is responsible for updating and managing password security.

**Comment by nul800sebastiaan** [comment]
Thank Shannon, for the explanation, I will close this issue as the implementation works as expected and you've found the correct way to work with it now! 👍

**Comment by voltaek** [comment]
@nul800sebastiaan Please don't close this issue, yet, it's not that cut and dry.

@Shazwazza 
First, nowhere in documentation is it stated that Members need to be handled as a special case where - only sometimes - the same Member record can save multiple times, so this is at the very least undocumented behavior.

Second, how can anyone be expected to be able to make changes to a record in the process of saving based on what was changed on the record compared to its values before the save, when during the events of the second save, the first save will have already updated the record, meaning we can't pull the 'before' record to reference against.

If we don't somehow know to apply the same changes to the record again during the second save, then our changes are just undone by it. This breaks being able to reliably handle changes to records in these events unless you know to program around it. Hence my second comment earlier about having to workaround this issue by reapplying the same changes to the record during the same request, which is a hack workaround and should not be required to be part of any implementation.

Third, I am aware you can simply modify the entities in `Saving` and have them save without calling `Save()` myself, but I prefer to be sure the save was actually successful before making my changes to the record. Doing it that way doesn't alleviate the issues here, though, so I'm not sure how that is relevant to this issue.

Lastly, you didn't address why some Member fields cause duplicate saves, while others do not. In neither case am I updating the password, so I'm not sure why both `Email`, and even `Comments` of all fields, cause duplicate saves, whereas the `Username` field does not. I would think if anything the `Username` field would be causing the duplicate save if the membership provider is what is causing this issue like you stated.

**Comment by voltaek** [comment]
@Shazwazza I've updated my code to not save with services during the save events. Here is what I have currently to work around the inconsistent duplicate saves occurring.

```
public class CustomApplicationEventHandler : Umbraco.Core.ApplicationEventHandler
{
	protected override void ApplicationInitialized(UmbracoApplicationBase umbracoApplication, ApplicationContext applicationContext)
	{
		base.ApplicationInitialized(umbracoApplication, applicationContext);
		Umbraco.Core.Services.MemberService.Saving += MemberService_Saving;
	}

	// Before a member is saved
	internal void MemberService_Saving(IMemberService sender, Umbraco.Core.Events.SaveEventArgs<IMember> e)
	{
		if (HttpContext.Current.Items["newMemberEmailThisRequestByID"] == null)
		{
			HttpContext.Current.Items["newMemberEmailThisRequestByID"] = new Dictionary<int, string>();
		}

		Dictionary<int, string> newMemberEmailThisRequestByID = HttpContext.Current.Items["newMemberEmailThisRequestByID"] as Dictionary<int, string>;

		foreach (IMember savingMember in e.SavedEntities)
		{
			// Pull the member from the member service before updated this save
			IMember beforeMemberRecord = ApplicationContext.Current.Services.MemberService.GetById(savingMember.Id);

			if (beforeMemberRecord == null)
			{
				continue;
			}

			// If the Username or Email being saved don't match, then we'll sync them up
			if (savingMember.Username != savingMember.Email)
			{
				string newEmail;

				// If we already grabbed the email address to use to sync up Email and Username this request (gets around Umbraco's duplicate save events)
				if (newMemberEmailThisRequestByID.ContainsKey(savingMember.Id))
				{
					// Pull the email to apply again during this duplicate save since we can't compare against the before record anymore
					newEmail = newMemberEmailThisRequestByID[savingMember.Id];
				}
				else
				{
					// Figure out which field changed and hold onto the new email address
					newEmail = beforeMemberRecord.Email != savingMember.Email ? savingMember.Email : savingMember.Username;

					// Store so we can handle duplicate saves that Umbraco does
					newMemberEmailThisRequestByID.Add(savingMember.Id, newEmail);
				}
			
				// Sync up the fields
				savingMember.Username = newEmail;
				savingMember.Email = newEmail;
			}
		}
	}
}
```
