### ISSUE TITLE
Deleting single items in recycle bin tries to load -20 instead of recyclebin resulting in a 404 error

### ISSUE THREAD

**Issue by sniffdk** [umbraco/Umbraco-CMS#3841]
When deleting a node from the recycle bin, Umbraco will try to load the recycle bin root node by going to -20 -> /umbraco#/content/content/edit/-20
That returns a 404 though, as in newer versions the node id apparently needs to be recyclebin -> /umbraco/#/content/content/recyclebin

Tested on version 7.10.4 and 7.12.2

**Comment by kjac** [comment]
@sniffdk well spotted!

PR in #3843.

**Comment by emmaburstow** [comment]
Thanks Mads! And thanks Kenn for creating the PR to go with this. 👍
