### ISSUE TITLE
Umbraco.slider initial value is always 0

### ISSUE THREAD

**Issue by Deltids** [umbraco/Umbraco-CMS#3855]
Reproduction
------------

### Bug summary

The initial value of the slider is 0 even though the UI shows a positive number and initial value setting is set to a positive number . 

Orientation: Horizontal
Initial value: 15
Minimum value: 1
Maximum value: 30
Precision: 0
Tooltip: show

When I debug the application the property is initally set to 0.
If I go into the backoffice and change the slider to e.g. 14 and save and publish, it works, but up until that point its value is 0.

There is nothing in our application that interfer with this property in any way, so it looks to me as a bug in umbraco somewhere.

### Specifics
This is umbraco 7.12.3

### Steps to reproduce
- Create a Document Type with a slider property. 
- Get the document content in a custom controller
`var myDocType = content.Children.OfType<MyDocType>.FirstOrDefault()`
- Check the slider value on first page load MyDocType or saving it to a variable:
`sliderCnt = Convert.ToInt32(myDocType?.sliderCntProperty);`

### Expected result

Expected result is that the initial value of the slider value is initial value defined in settings.

### Actual result

The value is 0

**Comment by nul800sebastiaan** [comment]
Hmm, unfortunately I can't reproduce in 7.12.3. Any javascript errors maybe?
If you have any more details then feel free to re-open the issue!

![3855](https://user-images.githubusercontent.com/304656/49806304-ac547b80-fd57-11e8-896c-2716899a8a90.gif)

**Comment by nul800sebastiaan** [comment]
Ah, I just noticed the code you added above. Please note that the slider value will not be in the published content until you publish the document. So if you add a slider property the contact page of your site you need to go into the contact page and publish that page with the default value, otherwise the default value will just be the default value of `int`, which is 0.

**Comment by Deltids** [comment]
So every time the site gets re-deployed, I have to manually go to the page and "Save and publish"? The page is in published state in the backoffice. 

![image](https://user-images.githubusercontent.com/20363682/49924942-d7ee7780-feb7-11e8-835f-56dedf18cee8.png)

**Comment by nul800sebastiaan** [comment]
I'm not sure what re-deploying has to do with it but I encourage you to try to get some [help on the forums](https://our.umbraco.com) as the functionality works as expected.

**Comment by Deltids** [comment]
Ok, I'll try.

It will still be my understanding that it is not working as expected, as the page with the slider is published, but the value is not available in published content. I would understand if the page status was unpublished. 

Thanks for the answers.

**Comment by nul800sebastiaan** [comment]
That's the part I can't reproduce though, if I publish the value then it's available in published content as expected.

**Comment by claushingebjerg** [comment]
This is still a problem in 8.14 (the site im working on.)

If a initial value is untouched by the editor it returns 0.
I use the slider for defining padding. The bottom row has a initila value of 3 set - it renders 0
The top row has an initial valu of 3 set, which has been moved to another value and back to 3 and saved.

![Skærmbillede 2021-09-23 kl  12 49 24](https://user-images.githubusercontent.com/1854789/134494870-c568770d-4aa6-4666-986c-86e0ec33fb20.png)
![Skærmbillede 2021-09-23 kl  12 49 40](https://user-images.githubusercontent.com/1854789/134494885-e596fa81-3046-42af-a3d1-8c22ec5ea532.png)

**Comment by thenexus00** [comment]
Even in Umbraco 15 this is still an issue.
You have sliders with an initial value this is simply not coming through and is always 0.
You have to physically edit the slider to be able to get any value out of it.

This was a thing back in 7 and still there in 15 :/
