### ISSUE TITLE
Implement document property bag

### ISSUE THREAD

**Issue by ssougnez** [umbraco/Umbraco-CMS#3857]
Hi,

it would be cool to have some kind of property bag attached to a a document. Basically, the idea would be that every document would have a common property call "propertyBag" or something that could store arbitrary JSON data. The goal would be to be able to store data related to the document that a user can't edit/see.

For example, I'm working on a feature allowing content editors to create stores with complex schedules. A requirement is to be able to display the 3 next days when each store is opened, so I have to calculate these dates somehow. My first implementation was to retrieve all the stores when the app starts, calculate the date and put them in the cache. However, as there are a lot of stores and as schedules are **really** complex, it took a long time to be calculated.

Therefore, my final solution was to create a property editor that hides itself on the edition page. Therefore, I could override the "Saving" handler for that document, calculate the next opening dates for the whole year and store them in this property. This is nice because now, when I retrieve the stores using "TypedContent", I get the opening dates as well. 

I think that the application of such a feature would be even wider. Basically, it would allow developers to store data and attach them to a document while being sure that content editors won't be able to edit it.

How can you help?
-------------------------------

If it gets accepted, I could have a look at it by myself.

**Comment by nul800sebastiaan** [comment]
Hi @ssougnez - I've discussed this with Shannon and while the idea sounds interesting, this is not something we'd want to support in CMS.

He also questioned storing this type of data in the content cache, it might be necessary in this case but it seems like this could be "abused" to drop in loads of unrelated data that will never appear on the frontend. 
Remember also that each publish will duplicate this data again, it sounds better suited for storage in a separate table.

Additionally, when v8 comes out, we have the Content Apps feature that could be used for this purpose.

**Comment by ssougnez** [comment]
I'll wait for v8 then :+1:
