### ISSUE TITLE
Silent publishing

### ISSUE THREAD

**Issue by ssougnez** [umbraco/Umbraco-CMS#3863]
Hello,

it would be great to add a overload to the "save/publish" methods to specify that the action should not be audited. Indeed, it could happen that a schedule task updates a document property for whatever reason and in that case, it would be interesting not to audit it (it would be the choice of the developer). Indeed, if this task is executed often, the audit log could be polluted.

How can you help?
-------------------------------

I had a look at the "ContentService" and it would not require too much change to add this functionality, so I could take it up ;-)

**Comment by nul800sebastiaan** [comment]
We'll discuss it in our next regular meeting but my first reaction would be: that doesn't sound like something we want. 
You'd mess with the rollback mechanism, with accountability ("oh, it wasn't me, it was the system that did it.. but we will never be able find out when or why") and it also makes debugging issues harder for you and for us at HQ. 

The less convenient way right now is to delete the audits during the same scheduled task, if you really would want to do something like this.

**Comment by nul800sebastiaan** [comment]
@ssougnez - as I expected, Shannon agrees with the above and this is not something we'd want to implement in the CMS. Thanks for the suggestion! 👍
