### ISSUE TITLE
[v8] DatabaseBuilder has useful methods set to internal

### ISSUE THREAD

**Issue by aaronpowell** [umbraco/Umbraco-CMS#3866]
In v7 I was relying on the [`DatabaseSchemaHelper`](https://github.com/umbraco/Umbraco-CMS/blob/dev-v7/src/Umbraco.Core/Persistence/DatabaseSchemaHelper.cs) class to expose some functionality to create the database in Chauffeur, in particular, this method: https://github.com/umbraco/Umbraco-CMS/blob/dev-v7/src/Umbraco.Core/Persistence/DatabaseSchemaHelper.cs#L113

The `DatabaseSchemaHelper` has been removed in v8 and replaced with [`DatabaseBuilder`](https://github.com/umbraco/Umbraco-CMS/blob/temp8/src/Umbraco.Core/Migrations/Install/DatabaseBuilder.cs) (or so it seems).

Unfortunately, the method I need, [`CreateSchemaAndData`](https://github.com/umbraco/Umbraco-CMS/blob/temp8/src/Umbraco.Core/Migrations/Install/DatabaseBuilder.cs#L445) is marked as `internal`, along with its return type.

Because of this, it's pretty much impossible (without some dodgy reflection) Chauffeur is unable to bootstrap an Umbraco database in a simple manner. The only workaround I'm able to find is to pull in the `InstallStep<T>` for the database install, which feels really ugly and also won't give me the control I need in the process.

**Comment by zpqrtbnk** [comment]
These methods could be public really... it's only the `CreateSchemaAndData` one?

Out of curiosity... so Chauffeur manages the complete install? Thus bypassing the Umbraco installer? Do you also manage upgrades (ie would you also need `UpgradeSchemaAndData`)?

**Comment by aaronpowell** [comment]
Here's what the code _might_ look like: https://github.com/aaronpowell/Chauffeur/blob/umbraco-v8/src/Chauffeur/Deliverables/InstallDeliverable.fs

**Comment by zpqrtbnk** [comment]
Can you get something from DI there? Assuming you can inject the `IScopeProvider`, `ILogger` and `IUmbracoDatabaseFactory`, the following code should get your a database with schema and data:
```
databaseFactory.Configure(connectionString, Constants.DbProviderNames.SqlCe);

using (var scope = scopeProvider.CreateScope())
{
    var creator = new DatabaseSchemaCreator(scope.Database, logger);
    creator.InitializeDatabaseSchema();
    scope.Complete();
}
```
We would then "just" make `DatabaseSchemaCreator` and its `InitializeDatabaseSchema` (maybe renamed to `CreateSchemaWithData` or something) public. Thoughts?

**Comment by aaronpowell** [comment]
Looks like the `DatabaseSchemaCreator` would do the trick, so I've created an alternative PR that does that.

I'd expect you'd want to use _either_ #3867 or #3899, not both, but they are just a compare/contrast approach.

**Comment by zpqrtbnk** [comment]
Reviewing now - trying to reduce the number of things we expose and might want to refactor at some point - do you need methods from the `#region Configure ConnectionString` to be public?

**Comment by zpqrtbnk** [comment]
Same question with `ValidateSchema()` - this method does weird things, and reports weird data structures, that I really would rather keep internal so we can refactor them. Let me know if we could keep them internal for now.

**Comment by aaronpowell** [comment]
From a Chauffeur stand point then I don't really need to be able to save the connection string, I don't expose the ability to edit that (it's a bit tricky due to the way Chauffeur hosts Umbraco).

`ValidateSchema` could be useful, I'd potentially use it from a test standpoint.

Being able to run the upgrade would also be good, Chauffeur supports [running migrations](https://github.com/aaronpowell/Chauffeur/blob/master/Chauffeur/Deliverables/UpgradeDeliverable.cs) which I'd assume the upgrade in `DatabaseBuilder` does.

**Comment by zpqrtbnk** [comment]
ok - going to merge + do a few changes, and then feel free to complain ;-)

**Comment by zpqrtbnk** [comment]
Have merged. Keeping this issue open while you review.

**Comment by aaronpowell** [comment]
Awesome, I'll pick up a build tomorrow with it and test

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by aaronpowell** [comment]
Bugger, looks like a build hasn't been published to MyGet for a week ☹.

**Comment by nul800sebastiaan** [comment]
☹ Looks like the unit tests are failing: 

```
2018-12-19T12:52:05.9413785Z Failed   Create_Cached_Plugin_File
2018-12-19T12:52:05.9414099Z Error Message:
2018-12-19T12:52:05.9414794Z  TearDown : System.IO.DirectoryNotFoundException : Could not find a part of the path 'D:\a\1\s\build.tmp\tests\TypeLoader'.
```

**Comment by aaronpowell** [comment]
That's a bit of a bugger ☹️

**Comment by zpqrtbnk** [comment]
On it now

**Comment by zpqrtbnk** [comment]
Fixed, should be good tonight.

**Comment by aaronpowell** [comment]
@zpqrtbnk Just wanted to revisit this as I'd like to pick up working on Chauffeur for v8

**Comment by zpqrtbnk** [comment]
The public `DatabaseSchemaCreator` class now has a public `InitializeDatabaseSchema()` method that is meant to be used for this (as the database builder is doing more, unnecessary things). You end up doing something alike:
```
private void InitializeDatabase(IUmbracoDatabase database)
{
    database.BeginTransaction();
    var creator = new DatabaseSchemaCreator(database, _logger);
    creator.InitializeDatabaseSchema();
    database.CompleteTransaction();
}
```

Now that requires an `IUmbracoDatabase` - discussing this on #3935

**Comment by aaronpowell** [comment]
Dumb question on using `IUmbracoDatabase`, I found that that isn't in the container, so how do you get an instance of it?

**Comment by zpqrtbnk** [comment]
The normal way, which we use everywhere, is via a scope:
```
using (var scope = scopeProvider.CreateScope())
{
  var database = scope.Database;
  // do stuff
  scope.Complete();
}
```

where `scopeProvider` is an `IScopeProvider` that can be injected.

Then, there is an `IUmbracoDatabaseFactory` which can be injected too and can be used to create an `IUmbracoDatabase` directly - but without scoping, transaction, anything *and* it really really must be disposed after being used.

**Comment by aaronpowell** [comment]
Ah cool, didn't know that that was the best way to get it, was thinking I'd have to use the `IUmbracoDatabaseFactory` or something.

All sorted now!
