### ISSUE TITLE
[Discussion] Would Umbraco benefit from a RFC process?

### ISSUE THREAD

**Issue by aaronpowell** [umbraco/Umbraco-CMS#3871]
A **Request for Comments/Contribution** (RFC) process is something that's been popping up in more and more large Open Source projects.

Projects like [React](https://github.com/reactjs/rfcs), [F# Language](https://github.com/fsharp/fslang-design/blob/master/README.md) and [C# Language](https://github.com/dotnet/csharplang) are examples of where an RFC (or similar) are used. Generally, these are for large/complex changes to the _thing_ in question, not for every single change that would be made.

An RFC process allows anyone to start a discussion on something to be done, whether they are a core contributor or external contributor, before getting too 'deep in the weeds'. It can also be a good way for core contributors to validate ideas and approaches with the community before cutting too much code.

Why do I think this could be a valuable thing for Umbraco? With the v8 rewrite, there's a lot of really large breaking changes that are happening, some of which can either be difficult to follow how they work or have unintended side-effects on consumers. A couple of examples of this that I've noticed are [the approach to DI](https://github.com/umbraco/Umbraco-CMS/pull/2690), the [design of the bootloader/runtime/components](https://github.com/umbraco/Umbraco-CMS/pull/3733), [overhaul of migrations](https://www.zpqrtbnk.net/posts/migrations-in-v8) and [disabling nested content](https://github.com/umbraco/Umbraco-CMS/issues/2887).

Using an RFC process you can flip the conversation from "Here's some changes I've made, please review them" to "I want to change X to be like Y, please review the idea".

The examples I used above are fairly deep in the internals, but an RFC process could be useful for many higher level features. Take the idea of overhauling a property editor, upgrading a major dependency (like Angular) or sunsetting a feature; being able to have a discussion about these before the work is undertaken can help catch problems before they land.

Now, I'm aware that the contribution guide has a [suggesting enhancements](https://github.com/umbraco/Umbraco-CMS/blob/dev-v7/.github/CONTRIBUTING_DETAILED.md#suggesting-enhancements) part to it, but it feels a bit light on and more for the community to propose changes than the core contributes to request feedback. It also helps put some structure around how long something can be in consideration for. Waiting for comments doesn't mean someone couldn't be starting work, it just helps prevent work being done multiple times.

Ultimately, my hope is to have less "we're already working on that" or "surprise! _something_ has had a major change" that then results in diving through git commits, branches, PR's and issues to understand something (using migrations as an example, I actually can't find threads on how the changes came about, why the approach was taken, etc. only [this one](https://github.com/umbraco/Umbraco-CMS/issues/3482)). It's all about transparency and ensuring that everyone feels like they understand the direction of Umbraco 😊.

**Comment by hartvig** [comment]
Such as this: https://umbraco.com/blog/a-second-take-on-umbraco-issue-tracker-hello-github-issues/

**Comment by aaronpowell** [comment]
@hartvig Thanks Niels, I hadn't seen that post (or maybe I had but had forgotten about it). I'll propose an update to contributing to refer to the information it clarifies in the post, since it's a bit opaque following the contributing info as it stands.

I still feel that it looks at one part of the equation, the community to HQ, do you see potential for something on the HQ to community direction?

**Comment by aaronpowell** [comment]
@dawoe I don't want this thread to focus on any particular change. I'm aware of the post that @zpqrtbnk wrote, I just mentioned migrations because it was something that I'd seen discussed on twitter today.

**Comment by dawoe** [comment]
@aaronpowell 

I just took this one, because it is a good example that could have benefited from what you are proposing.

Dave

**Comment by hartvig** [comment]
@aaronpowell Good point. The v8 process suffered from being architected before any processes was in place (2018 has been an implementation year as most groundwork has already been done). It would be interesting to find a way to run a more open process in the future with respect for our organization not being a match for those of Microsoft (c# and f#) or Facebook (react).

**Comment by aaronpowell** [comment]
The reason I highlighted those three as they are examples of OSS projects where the bulk of the engineering effort is undertaken by a corporate entity but there is an active community behind them. In fact it was the [React Hooks](https://reactjs.org/docs/hooks-intro.html) ([rfc](https://github.com/reactjs/rfcs/pull/68)) that got me thinking about this.

> It would be interesting to find a way to run a more open process in the future with respect for our organization

Would it be possible for HQ to use the GitHub issue register for their backlog (obviously only Umbraco CMS, not Cloud or any closed source products!)? Alternatively if you're using Azure DevOps boards could they be made [public](https://docs.microsoft.com/en-us/azure/devops/organizations/public/view-filter-work-items-public?view=vsts&tabs=new-nav)? I'd like to see the CI/CD pipeline also public so it's possible to see what work is going into a build.

**Comment by aaronpowell** [comment]
https://opensource.com/article/17/9/6-lessons-rfcs is a good look at the value an RFC process has in an engineering team.

**Comment by nul800sebastiaan** [comment]
I guess we can close this now. :-)

https://github.com/umbraco/rfcs
