### ISSUE TITLE
RelatedLinks HtmlHelper extension

### ISSUE THREAD

**Issue by christophnz** [umbraco/Umbraco-CMS#3875]
I've always found the frontend for RelatedLinks a bit cumbersome (although it has gotten a lot better with value converters):
```
var linkTarget = (item.NewWindow) ? "_blank" : null;
<a href="@item.Link" target="@linkTarget">@item.Caption</a>
```
In most cases, I just want to render a simple anchor tag, maybe sometimes with a class added. So I have written an HtmlHelper extension that does just that:
```
@Html.GetRelatedLinkHtml(item)
```
and an override that accepts HtmlAttributes:
```
@Html.GetRelatedLinkHtml(item, new {@class = "button"})
```
I'd like to contribute this back to the Core if you think this will be useful for others. I will submit a pull request shortly.

**Comment by christophnz** [comment]
Pull request: https://github.com/umbraco/Umbraco-CMS/pull/3876

**Comment by nul800sebastiaan** [comment]
Fixed in https://github.com/umbraco/Umbraco-CMS/pull/3876

**Comment by christophnz** [comment]
Great to see HQ liked this addition and it is making it into 7.14.
I will try to remember to submit a pull request for the documentation once 7.14 is released.
