### ISSUE TITLE
Allow all editors - Not saving when selected 

### ISSUE THREAD

**Issue by PSinke** [umbraco/Umbraco-CMS#3883]
The checkbox for 'Allow all editors' is not saving the state correctly. When trying to switch from a couple of selected editors to 'allow all editors', the check box is not saved correctly, and therefore doesn't function correctly in the grid layout. 

This can be reproduced by creating a new grid layout datatype, then select one of the default rows. Click on a column. By default 'allow all editors' is selected. Un-check the checkbox, select a random editor. Submit and save. Refresh the page, then click on the row again, click on the column again, and now check the 'allow all editors' checkbox. Submit + save and refresh the page. For me this results in the checkbox not being checked. But the list of possible editors is also empty.
I checked this in multiple different browsers. No javascript errors are shown in the developer console.

I expect the checkbox to stay checked when checking it and saving the page.

Umbraco 7.12.4
Browsers: latest Chrome, latest Firefox

![umbracobug](https://user-images.githubusercontent.com/2011552/50008409-5e887f00-ffb4-11e8-9564-a2c5a9b771ec.png)

**Comment by kjac** [comment]
I have observed the same with layout configurations... and I have located the issue. I'll submit PRs soon as I can, hopefully tonight.
