### ISSUE TITLE
Front end server does not get the published content when there is server side validation error on backoffice server

### ISSUE THREAD

**Issue by harsheet** [umbraco/Umbraco-CMS#3893]
When we publish a content after fixing the server side mandatory validation errors (postSave api error), it shows up on backoffice server immediately, but not on the front end server.

We have to publish twice in order to display it on the front end server. 

And we believe that this is caused by published content index not getting synced over to the front end server, the first time we publish it. 

Or the postSave api error blocks the content index sync over to the front end server.

**Expected result**

The content should be displayed on both front end and backoffice server at the same time on publishing it for the first time.

We have already followed the load balancing setup from here
https://our.umbraco.com/Documentation/Getting-Started/Setup/Server-Setup/Load-Balancing/

**Comment by nul800sebastiaan** [comment]
Hi @harsheet - as advises before, make sure to ask your support questions on the forum so that our community can try to help you.
