### ISSUE TITLE
Adding compositions to doctypes from the composition.

### ISSUE THREAD

**Issue by g-dove** [umbraco/Umbraco-CMS#3898]
When you create a new composition on a site and need to apply it to a lot of different document types it is quite a time-consuming process.

Therefore the idea is to have a doctypes button on the composition that shows a list of all the doctypes that you can add the compositions to. An exact mirror of the compositions button currently used on the doctypes editor to add compositions to the doctype.

Something to consider is that it would need to be updated on both ends of the editor (on the doctype and the compositions) whenever it is changed.

**Comment by nul800sebastiaan** [comment]
Hi @g-dove - thanks for the suggestion! 

We are currently not planning to support this, the reasons and workarounds are much the same as listed on https://github.com/umbraco/Umbraco-CMS/issues/3216
