### ISSUE TITLE
Remove configuration based index/searchers and index sets

### ISSUE THREAD

**Issue by Shazwazza** [umbraco/Umbraco-CMS#3901]
child of #3530
requires #3535

Examine no longer ships with configuration based indexes and searchers since configuration is not flexible, it's archaic/legacy and it's actually less simple than code. 

Umbraco already creates and configures the indexes it ships with via code, however Umbraco still has it's own configuration based index features like IndexSet (which was moved from Examine to Umbraco since Examine no longer supports config).

So all configuration based index code needs to be removed

**Comment by Shazwazza** [comment]
PR https://github.com/umbraco/Umbraco-CMS/pull/3902

**Be sure to review #3535 first!**

**Comment by zpqrtbnk** [comment]
Have merged latest `temp8`. Cannot merge the PR for now: tests failing in `PublishMediaCacheTests` and `PublishMediaTests` because "No index found by name InternalIndex" - assuming that's because the tests don't configure the indexes anymore? How should they do it?

**Comment by Shazwazza** [comment]
@zpqrtbnk tests are fixed, was a simple change, see e20e570dc86511591aa245123e510eb6239b49d8

**Comment by Shazwazza** [comment]
@zpqrtbnk have also pushed fixes for the issue of rebuilding indexes seeming to timeout.

**Comment by zpqrtbnk** [comment]
tests green, site runs, merged
