### ISSUE TITLE
Hide properties for specific user groups

### ISSUE THREAD

**Issue by janvanhelvoort** [umbraco/Umbraco-CMS#3903]
Sometimes we misuse properties voor setting and / or config. It would be nice if we can specify per property if a property will be visible or be hidden for a specific group(s).

How can you help?
-------------------------------
I will make a discussion topic on Our, if we have a suitable solution, I want try it to make it possible.
Link: [Hide properties for specific user groups](https://our.umbraco.com/forum/contributing-to-umbraco-cms//95053-hide-properties-for-specific-user-groups)

**Comment by nul800sebastiaan** [comment]
Hi @janvanhelvoort - thanks for the suggestion1

We don't plan to support this in Umbraco. It is however already possible to remove properties using the `EditorModelEventManager.SendingContentModel` event and we encourage you to use that if you have  specific needs like this.

**Comment by janvanhelvoort** [comment]
I have created a first package version. You can create and manage rules (not delete yet). This monday I will continue and build options to delete rules and toggle active state. Also to export and import rules between environments.

https://www.myget.org/feed/janvanhelvoort/package/nuget/Our.Umbraco.HideProperties

![hide-properties 1](https://user-images.githubusercontent.com/5024929/50374069-8ac18280-05e8-11e9-9618-4f187f71c6a1.png)

![hide-properties 2](https://user-images.githubusercontent.com/5024929/50374068-8ac18280-05e8-11e9-838c-547f32e73a83.png)

**Comment by janvanhelvoort** [comment]
Version 0.2.0 is ready: https://github.com/janvanhelvoort/Umbraco-hide-properties/releases/tag/0.2.0
