### ISSUE TITLE
Build script dies when using npm prefix.

### ISSUE THREAD

**Issue by aaronpowell** [umbraco/Umbraco-CMS#3905]
If you're using a tool to manage multiple versions of node.js on a machine (like [ps-nvm](https://github.com/aaronpowell/ps-nvm), [nodist](https://github.com/nullivex/nodist) or [nvm-windows](https://github.com/coreybutler/nvm-windows)) it's likely that the `build.ps1` script will blow up when trying to run `gulp`.

The problem is because while the script attempts to create a sandboxed environment to run node.js it doesn't cater to the [npm folder prefix](https://docs.npmjs.com/files/folders#prefix-configuration).

Instead of doing a global install of `gulp` it would be better to use [`npx`](https://blog.npmjs.org/post/162869356040/introducing-npx-an-npm-package-runner) to run it from the `node_modules` folder of Belle.

_Expect a PR soon._

**Comment by aaronpowell** [comment]
Alright, pretty much sorted, but a few things:

* I've had to roll `gulp-imagemin` back, otherwise it raises an error (as described above)
* The version of node.js used in the build script is really quite old and will be going into [maintenance old mode 1st Jan 2019](https://github.com/nodejs/Release#release-schedule). This is a problem because the `npx` version shipped with it has a bug (https://github.com/zkat/npx/issues/144) that writes our a message that PowerShell thinks is an error
  * I'd like to upgrade `Umbraco.Build`'s scripts to use a current Node.js version (10.x), but I can't find the source of that

Because of the 2nd issue I've _not_ created a PR yet, but I have a working branch with my changes, that can be found https://github.com/umbraco/Umbraco-CMS/compare/temp8...aaronpowell:temp8-3905?expand=1

**Comment by dawoe** [comment]
Hi @aaronpowell 

First of all thanks for raising this issue. 

In V7 the node is downloaded by this powershell script : https://github.com/umbraco/Umbraco-CMS/blob/dev-v7/build/Modules/Umbraco.Build/Get-UmbracoBuildEnv.ps1#L97

Is that what you are after ?

Dave [Community Pull Request team](https://umbraco.com/blog/introducing-the-new-cpr-team/)

**Comment by aaronpowell** [comment]
I haven't looked at v7, only V8 (which is where my branch is from).

Is that script published to the NuGet package V8 uses? If so I'll PR that too.

**Comment by aaronpowell** [comment]
Just had a look at that file @dawoe and no, it's not the same as is used in v8, v8 using the NuGet package `Umbraco.Build` which is on the MyGet feed (https://www.myget.org/F/umbracocore/api/v3/index.json), but I can't find the source code for it anywhere. @nul800sebastiaan @zpqrtbnk @Shazwazza do you know where the source of that package is?

**Comment by zpqrtbnk** [comment]
Hint: don't look at v7, the build script is entirely different in v8.

The build tooling is at https://github.com/umbraco/Umbraco-Build but private at the moment - no idea why, looking at opening it today.

As for the versions of Node etc, I remember dealing with them when creating the script but I know little of Node so can totally have messed things up. Welcoming fixes.

**Comment by zpqrtbnk** [comment]
https://github.com/umbraco/Umbraco-Build is now public - happy hacking!

**Comment by aaronpowell** [comment]
Thanks @zpqrtbnk I'll get on that when I'm sober 😂

**Comment by zpqrtbnk** [comment]
Umbraco.Build 0.2.0 with latest Node (from your PR) has been pushed to MyGet. Happy to see a PR to `build.ps1` that fixes the Node path issue.

**Comment by aaronpowell** [comment]
Ace - I'll test it locally and then send through a PR.

**Comment by aaronpowell** [comment]
PR linked, tested locally using the new `Umbraco.Build` and it seems all good 😄;

**Comment by nul800sebastiaan** [comment]
Fixed in https://github.com/umbraco/Umbraco-CMS/pull/3938
