### ISSUE TITLE
Query-builder needs to be updated to support executing the query

### ISSUE THREAD

**Issue by Shazwazza** [umbraco/Umbraco-CMS#3908]
requires #3668 
child of #3661

The Query Builder functionality does the following:

1. Based on user input it generates a razor query to be inserted into a view
2. It executes this query on the server side to inform the user of which nodes are in the result
3. It times the execution of this query

The 3rd point is sort of broken already in v7 since the timing of the execution is not actually timing the the code that is generated, it's sort of pseudo timing some individual operations. 

The 2nd point is currently done by executing dynamic Linq statements when there is a where clause like `.Where(x => x.Name.Contains("Hello"))` however in v8 we've removed all the dynamic support so this can no longer happen.

If we want to support points 2 + 3 in v8 then we will need to do some work, we have a few options:

* Add back in the dynamic linq library support https://github.com/kahanu/System.Linq.Dynamic .. this is ugly at best and is a lot of code/dependency to just execute this single feature
* Build up an expression tree given the query parameters ... this would be nice but will take some time
* Dynamically execute the razor code in a razor host ... since we are running in a web context this should be reasonable 'easy' and i'm not sure we need external dependencies, else there are some very easy razor host dependencies we could use (see https://www.codemag.com/article/1103081/Leveraging-Razor-Templates-Outside-of-ASP.NET-They%E2%80%99re-Not-Just-for-HTML-Anymore! or https://west-wind.com/files/tools/razorhosting/docs/) 

We can then make Option 3 a true representation of timing.

**Comment by bergmania** [comment]
PR: #4040 
Part of other task.

I use Expression trees to create the clauses to the where, most of the existing code can still be used then. 
The new timing is fairly correct IMO, due to the fact that calls on children are yield returned.

**Comment by zpqrtbnk** [comment]
reviewed as part of the PR review - and it works fine, the expression thing is nice! closing
