### ISSUE TITLE
V8: When a plugin adds a tree to the user section, there is a JS error

### ISSUE THREAD

**Issue by bergmania** [umbraco/Umbraco-CMS#3915]
When a plugin (e.g. Forms) adds a tree to the user section there is a "10 $digest() iterations reached. Aborting!" error in the console. This is probably due to the User section no more have a tree.

![image](https://user-images.githubusercontent.com/1561480/50279408-ddb10380-0449-11e9-90e0-19581c4d8b43.png)

`
Error: [$rootScope:infdig] 10 $digest() iterations reached. Aborting!
Watchers fired in the last 5 iterations: [[{"msg":"fn: interceptedExpression","newVal":[{"name":"Users","icon":"icon-user","view":"views/users/views/users/users.html","active":true,"alias":"users"},{"name":"Groups","icon":"icon-users","view":null,"active":false,"alias":"userGroups"}]},{"msg":"fn: interceptedExpression","newVal":4},{"msg":"fn: interceptedExpression","newVal":"more"},{"msg":"fn: constantInterpolateWatch","newVal":""},{"msg":"fn: interceptedExpression","newVal":"More"},{"msg":"fn: interceptedExpression","newVal":""},{"msg":"showMoreButton","newVal":false},{"msg":"showNavigation","newVal":true},{"msg":"showDropdown","newVal":false},{"msg":"fn: interceptedExpression","newVal":1},{"msg":"fn: interceptedExpression","newVal":"users"},{"msg":"fn: constantInterpolateWatch","newVal":""},{"msg":"fn: interceptedExpression","newVal":"1"},{"msg":"fn: interceptedExpression","newVal":"icon-user"},{"msg":"fn: interceptedExpression","newVal":"Users"},{"msg":"fn: interceptedExpression","newVal":"is-active"},{"msg":"item.alias !== 'more'","newVal":true},{"msg":"fn: interceptedExpression"},{"msg":"fn: interceptedExpression","newVal":"userGroups"},{"msg":"fn: constantInterpolateWatch","newVal":""},{"msg":"fn: interceptedExpression","newVal":"2"},{"msg":"fn: interceptedExpression","newVal":"icon-users"},{"msg":"fn: interceptedExpression","newVal":"Groups"},{"msg":"fn: interceptedExpression","newVal":""},{"msg":"item.alias !== 'more'","newVal":true},{"msg":"fn: interceptedExpression"},{"msg":"subView.active === true","newVal":true},{"msg":"vm.usersViewState === 'overview'","newVal":true},{"msg":"vm.usersViewState === 'inviteUser' || vm.usersViewState === 'createUser'","newVal":false},{"msg":"vm.usersViewState === 'createUserSuccess'","newVal":false},{"msg":"vm.usersViewState === 'inviteUserSuccess'","newVal":false},{"msg":"fn: interceptedExpression"},{"msg":"vm.usersOptions.totalItems"},{"msg":"vm.userStatesFilter.length > 0","newVal":false},{"msg":"fn: constantInterpolateWatch","newVal":""},{"msg":"fn: interceptedExpression"},{"msg":"fn: interceptedExpression","newVal":"All"},{"msg":"vm.page.showGroupFilter"},{"msg":"fn: constantInterpolateWatch","newVal":""},{"msg":"fn: interceptedExpression"},{"msg":"fn: interceptedExpression","newVal":"Name (A-Z)"},{"msg":"vm.page.showOrderByFilter"},{"msg":"!vm.users && vm.usersOptions.filter.length > 0","newVal":false},{"msg":"vm.activeLayout.path === '1' && vm.loading === false","newVal":false},{"msg":"vm.activeLayout.path === '2'","newVal":false},{"msg":"!vm.loading","newVal":false}],[{"msg":"vm.loading","newVal":true},{"msg":"vm.selection.length === 0","newVal":true},{"msg":"vm.selection.length === 0","newVal":true},{"msg":"vm.selection.length > 0","newVal":false},{"msg":"vm.selection.length > 0","newVal":false}],[{"msg":"vm.defaultButton","newVal":{"labelKey":"user_createUser"}},{"msg":"vm.layouts","newVal":[{"icon":"icon-thumbnails-small","path":"1","selected":true,"active":true},{"icon":"icon-list","path":"2","selected":true}]},{"msg":"fn: ngModelWatch"}],[{"msg":"fn: interceptedExpression","newVal":"..."},{"msg":"fn: interceptedExpression"},{"msg":"defaultButton","newVal":"..."},{"msg":"subButtons.length > 0","newVal":false},{"msg":"subButtons.length > 0 && dropdown.isOpen","newVal":false},{"msg":"fn: interceptedExpression","newVal":""},{"msg":"fn: fn","newVal":"..."},{"msg":"fn: fn","newVal":{"icon":"icon-thumbnails-small","path":"1","selected":true}},{"msg":"fn: interceptedExpression","newVal":"icon-thumbnails-small"},{"msg":"vm.layoutDropDownIsOpen","newVal":false},{"msg":"vm.showLayoutSelector","newVal":true}],[{"msg":"fn: fn"},{"msg":"fn: interceptedExpression","newVal":"groupPrimary"},{"msg":"fn: interceptedExpression","newVal":"success"},{"msg":"fn: interceptedExpression","newVal":"user_createUser"},{"msg":"fn: interceptedExpression","newVal":"user_createUser"},{"msg":"fn: interceptedExpression","newVal":""},{"msg":"fn: interceptedExpression","newVal":""},{"msg":"fn: interceptedExpression","newVal":""},{"msg":"fn: interceptedExpression","newVal":""},{"msg":"fn: interceptedExpression","newVal":""},{"msg":"fn: interceptedExpression","newVal":"button-groupPrimary"},{"msg":"vm.innerState","newVal":"init"},{"msg":"vm.type === 'link'","newVal":false},{"msg":"vm.type === 'button'","newVal":true},{"msg":"vm.type === 'submit'","newVal":false},{"msg":"fn: interceptedExpression","newVal":""},{"msg":"fn: interceptedExpression","newVal":"-hidden -white"},{"msg":"fn: interceptedExpression","newVal":"-hidden -white"},{"msg":"fn: interceptedExpression","newVal":"-hidden -white"},{"msg":"vm.innerState !== 'init'","newVal":false},{"msg":"fn: interceptedExpression","newVal":"btn-success"},{"msg":"fn: interceptedExpression","newVal":""},{"msg":"fn: interceptedExpression","newVal":""},{"msg":"fn: interceptedExpression","newVal":""},{"msg":"vm.icon","newVal":""},{"msg":"fn: interceptedExpression","newVal":"Create user"},{"msg":"vm.showCaret"},{"msg":"fn: interceptedExpression","newVal":""},{"msg":"vm.disabled"}]]
`

Reproduction
------------

1. Open Forms UI in V8
1. Go to user section
1. Open developer console in browser
1. Click the "Forms Security"

**Comment by Shazwazza** [comment]
That angular error is due to having too many watchers, or watchers that fire other watchers (like an infinite loop). They are hard to track down but essentially it means there's too many digest loops. 

Theres an SO topic on it here https://stackoverflow.com/questions/17116114/how-to-troubleshoot-angular-10-digest-iterations-reached-error

There's actually quite a lot of blog posts out there with tips on debugging this but I agree with the SO one, need to remove html and start adding it back in to see where the problem is. The error also helps since you can see which vars are being watched and changed, if you copy/paste the json into a pretty format, it will have blocks of digests that you can see.

Here are my tips that have worked for me in v8:

* Don't use `ng-if` if you are just hiding some HTML, this creates a child scope and watchers, it is expensive. In a few cases this has been the underlying problem.
* Use one way binding wherever possible, this include things in view like `{::: myProperty}` instead of just `{myProperty}`
* Use one way binding in directives wherever possible - and switch to the correct components structure

I can have a look when I'm back from holidays but essentially this just means that there is too much to process at one time for this screen for some reason. I've had to solve this about 10 times already and it's just due to poor angular code/implementation.

**Comment by Shazwazza** [comment]
@bergmania do you know if this can still be replicated somehow?

**Comment by bergmania** [comment]
@Shazwazza, can't replicate anymore, so just closing
