### ISSUE TITLE
v8 - Add "Move" option for deleted items in the content tree

### ISSUE THREAD

**Issue by Shazwazza** [umbraco/Umbraco-CMS#3919]
This PR https://github.com/umbraco/Umbraco-CMS/pull/3772 will need to be manually applied to v8

**Comment by kjac** [comment]
I'll get on this soon 👍

**Comment by kjac** [comment]
PR in #3931

**Comment by nul800sebastiaan** [comment]
Fixed in https://github.com/umbraco/Umbraco-CMS/pull/3931
