### ISSUE TITLE
Need to have Examine's field definitions as dynamic

### ISSUE THREAD

**Issue by Shazwazza** [umbraco/Umbraco-CMS#3920]
child of #3530
requires #3901

Since field definitions change at runtime, these definitions need to be able to support being dynamic in Examine/Umbraco

Currently the IContentQuery.Search doesn't work because it doesn't know about all of the fields to search.

**Comment by Shazwazza** [comment]
PR: https://github.com/umbraco/Umbraco-CMS/pull/3987

This basically fixes the issues mentioned here https://github.com/umbraco/Umbraco-CMS/issues/3828#issuecomment-448966635

When searching by culture we need to match the culture fields, before it was using the 'field definitions' to determine which fields were in the index which is not correct, instead we just need to ask the index what fields it has and then determine which ones need to be searched. This is because field definitions need to be 'dynamic', for example, we have a field of `urlName` defined as `InvariantCultureIgnoreCase` and we don't want to have to create a different definition eagerly for every culture installed (i.e. urlName_en-us, urlName-fr-fr, etc...) because then we'd also have to listen for when languages are added/removed, etc... which is ugly. So instead we check if the field being requested is a culture field and if there is a field definition assigned to the base name and then we create/store/use a cloned definition. 

So now field defs are dynamic and we don't use these to determine which fields to search on and now it all works.

The other thing this fixes is making sure that the `IPublishedContent` returned from the search results from the IPublishedContentQuery are contextualized to the correct culture. For example, if you are using the search overload that specifies a specific culture, then the results will need to be contextualized to that culture so that the `.Name` value corresponds with the searched culture.

## testing

do a few different searches using the IPublishedContentQuery, like in a razor view do

```
var search1 = Umbraco.ContentQuery.Search("about");
var search2 = Umbraco.ContentQuery.Search("sommes", string.Empty);
var search3 = Umbraco.ContentQuery.Search("about", "en-us");
var search4 = Umbraco.ContentQuery.Search("sommes", "fr-fr");
```

Then you can list the results like:

```html
<hr/>
<ul>
    @foreach(var c in search1) 
    {
        <li>
            Id: @c.Content.Id Name: @c.Content.Name
        </li>
    }
</ul>
```

Of course do this for each search so you can make sure it's working and of course make sure that you have variant data in there that is going to match what you are searching on :)

**Comment by zpqrtbnk** [comment]
Reviewing... working fine but having questions:
* I notice we treat fields that contain patterns such as "_de-DE" in a special way - what would happen if my site does not have variant, but has multiple cultures, and I *do* have such fields (as some ppl did in the past)?
* Can the "contextualized" search results be... confusing? When enumerating the results, things are contextualized, but if... I get `var c = search1.First()` and display its name, it's not contextualized anymore?

For that second question, wouldn't it be better to say that `content.Name` always returns the "current culture" name, but we have a way to change that culture...
```
using (UmbracoHelper.WithCurrentCulture("fr-FR"))
{
  // ...
}
```
or something equivalent?

**Comment by Shazwazza** [comment]
Some answers:

> I notice we treat fields that contain patterns such as "_de-DE" in a special way - what would happen if my site does not have variant, but has multiple cultures, and I do have such fields (as some ppl did in the past)?

I don't really understand the question, if you don't have variants why would you have multiple cultures? Do you mean if a developer manually adds fields to the index with this pattern? If that happens, then it doesn't affect anything. These patterns are used specifically for searching for values for particular cultures. If the developer is manually adding fields like this then they will be manually searching fields like this.

> Can the "contextualized" search results be... confusing? When enumerating the results, things are contextualized, but if... I get var c = search1.First() and display its name, it's not contextualized anymore?

In that case yes - but your second question - it does return the "current" culture always apart from the one work around when you pass in the culture to the Search method. I think your proposed work around is a good one though even for other usages ! Could we consider that another task so we can close this one?

**Comment by zpqrtbnk** [comment]
First question: it's a common pattern on some v7 multi-lingual sites to use fields such as `title_fr-FR` and `title-da-DK` so ppl migrating these sites would end up having such fields. Just wanted to make sure... these non-variant sites would still work ok. Re-looked at the code and I think they would. Happy.

Yup we can always add the workaround I proposed later. So I think we just need to properly document that during the enumeration of the search results, the "current" culture switches to the searched culture. Will do.

And then think it's ok to merge. On it.
