### ISSUE TITLE
Legacy custom sections crashes in v.7.12.4

### ISSUE THREAD

**Issue by pavelshibanov** [umbraco/Umbraco-CMS#3922]
Legacy custom sections give Null Reference exception

Reproduction
------------

Use/define custom section using legacy method.
Open Umbraco admin. Section not loaded, Umbraco reports an error.
Null Reference exception in log.

### Bug summary
Error happens in 
\src\Umbraco.Web\Trees\LegacyTreeDataConverter.cs
Method:
internal static TreeNode ConvertFromLegacy(string parentId, XmlTreeNode xmlTreeNode, UrlHelper urlHelper, string currentSection, FormDataCollection currentQueryStrings, bool isRoot = false)

Line:
foreach (var i in currentQueryStrings.Where(x => menuQueryStrings.Keys.Contains(x.Key) == false))

Method parameter currentQueryStrings is always null for legacy custom sections.
If insert 
if (currentQueryStrings != null)
one line upper sections become working

### Specifics
URL: /umbraco

### Expected result
Legacy custom sections loaded

### Actual result

Legacy custom sections not loaded, errors in log

**Comment by emmaburstow** [comment]
Hey @pavelshibanov 

Thanks for posting this issue. 

Just wanted to check what you meant by "Use/define custom section using legacy method." Are you able to explain in a little more detail?

Thanks,

Emma

**Comment by nul800sebastiaan** [comment]
Hey @pavelshibanov if you have some example code we'd love to see it so we can repro, I'm also not sure what a "legacy custom section" is exactly. :-)

For now I'll close this until we get some steps to reproduce the issue.
