### ISSUE TITLE
Icon names spelling mistakes

### ISSUE THREAD

**Issue by callumbwhyte** [umbraco/Umbraco-CMS#3923]
As reported by a user on Twitter (https://twitter.com/welshfruit/status/1076177728750137344), when browsing the icon picker the label for the "thief" icon has a spelling mistake "theif" in the CMS.

Reproduction
------------

### Steps to reproduce

1. Go to the Document Type editor and select a doctype.
2. Click on the icon picker (top left beside name) - the icon picker dialog will appear.
3. Search for "thief", no results are found.
4. Search for the misspelled "theif" and it will return the icon.

### Expected result

The spelling should be "thief" not "theif".

**Comment by abjerner** [comment]
Just to link to the issue with your PR: https://github.com/umbraco/Umbraco-CMS/pull/3924 (and again, thanks a lot 👍)

**Comment by nul800sebastiaan** [comment]
Fixed in https://github.com/umbraco/Umbraco-CMS/pull/3924
