### ISSUE TITLE
User Profile Edit Issue

### ISSUE THREAD

**Issue by fengfuyun52** [umbraco/Umbraco-CMS#3934]
A brief description of the issue goes here.

Reproduction
------------

If you're filing a bug, please describe how to reproduce it. Include as much
relevant information as possible, such as:

### Bug summary

V7.12.4
I want edit user's profile, but the system warning mandatory，please see below shot.Thanks!
### Actual result

![image](https://user-images.githubusercontent.com/1414906/50497173-60e8df80-0a70-11e9-8fb6-86d3745ded5a.png)

**Comment by emmaburstow** [comment]
Hi there @fengfuyun52 

Could you tell me a little more about what you are trying to achieve? The user email is mandatory but as long as there is a value in there, it should submit. Are you trying to save a user without having an email value?

Thanks,

Emma

**Comment by nul800sebastiaan** [comment]
Hi @fengfuyun52 ! I've tried to reproduce but with that exact email address and setting my main language to Chinese, I do not see the same error.

If you can still reproduce then please explain in detail how to reproduce the error so we can try to figure it out. Thanks!

**Comment by fengfuyun52** [comment]
It works on chrome, but not works on IE 11.
I also don't know why.

**Comment by nul800sebastiaan** [comment]
Hi @fengfuyun52 - the problem has been found and fixed for v7.13 - see the related PR for more info: https://github.com/umbraco/Umbraco-CMS/pull/3456
