### ISSUE TITLE
Public access - single user protection throwing exceptions

### ISSUE THREAD

**Issue by clausjensen** [umbraco/Umbraco-CMS#3941]
child of https://github.com/umbraco/Umbraco-CMS/issues/3474

When trying to use single user protection (member picker) in public access, I'm getting exceptions thrown in the backoffice.

It *can* actually select a member if you close the errors and then search for a member, so something is working. It however needs to be fixed up to work as expected without errors.

**Comment by kjac** [comment]
I'll take a look at this.

**Comment by kjac** [comment]
Ok. This is not an error in public access. It's the member picker that's failing. I can reproduce it on a content type with a member picker property.

I'll submit a fix for it shortly.

**Comment by kjac** [comment]
PR in #3944

**Comment by nul800sebastiaan** [comment]
Fixed in https://github.com/umbraco/Umbraco-CMS/pull/3944
