### ISSUE TITLE
Clicking outside the actions dropdown does not close it

### ISSUE THREAD

**Issue by clausjensen** [umbraco/Umbraco-CMS#3951]
When having the 'Actions' dropdown shown while browsing a content item, clicking outside the dropdown should cause it to close.

This doesn't work so currently the only way to get rid of it is to either click the 'Actions' button again or use one of the actions in the dropdown or simply navigate somewhere else in the backoffice.

**Comment by kjac** [comment]
Found the bug... Will submit a PR soon as I have tested it a bit more.

**Comment by kjac** [comment]
PR in #3956

**Comment by nul800sebastiaan** [comment]
Fixed in https://github.com/umbraco/Umbraco-CMS/pull/3956
