### ISSUE TITLE
Opening help panel on content info mess up layout of history

### ISSUE THREAD

**Issue by bjarnef** [umbraco/Umbraco-CMS#3958]
When opening help panel from e.g. content info tab, the layout of history is a bit messed up.

![image](https://user-images.githubusercontent.com/2919859/50738109-d2dbca00-11d0-11e9-802a-1cadfa927306.png)

![image](https://user-images.githubusercontent.com/2919859/50738049-1255e680-11d0-11e9-9dc5-bc748a6db58d.png)

Adding `flex-flow: wrap;` on `.history-item` improves this a bit.

![image](https://user-images.githubusercontent.com/2919859/50738094-a162fe80-11d0-11e9-9546-2a758783285e.png)

Alternatively the publish status should be wrapped inside a container with the text, so it can be aligned vertically on narrow screens and with some distance to the avatar.

**Comment by kjac** [comment]
This also applies to several other elements, e.g. the language selector for variant content and a lot of property editors:

![image](https://user-images.githubusercontent.com/7405322/50753663-e3348900-1252-11e9-88ad-17b16c44dbb9.png)

The quickest and probably also safest way to fix this is to turn the help panel into an overlay like the user profile:

![image](https://user-images.githubusercontent.com/7405322/50753552-820cb580-1252-11e9-9a21-2941cd96807d.png)

A side note: The user profile and the help panel don't play nice together:

![image](https://user-images.githubusercontent.com/7405322/50753692-0bbc8300-1253-11e9-8ce2-8f0891b29370.png)

**Comment by bjarnef** [comment]
@kjac alternatively it could push the entire page content to the left something like this example.
https://imperavi.com/kube/docs/modules/offcanvas/

**Comment by nul800sebastiaan** [comment]
I think the purpose of the help panel was that you could have it open while working in the backoffice, you will get contextual links as well. So whenever the help panel is open, the rest of the backoffice should react in a responsive way.

**Comment by clausjensen** [comment]
@nielslyngsoe Will need some assistance from you on this one on what we should do!

**Comment by nielslyngsoe** [comment]
PR https://github.com/umbraco/Umbraco-CMS/pull/4809

I will though create another issue regarding the language picker situation that @bjarnef describes in his comment.
