### ISSUE TITLE
Saving media from info tab highlight both tabs

### ISSUE THREAD

**Issue by bjarnef** [umbraco/Umbraco-CMS#3959]
When saving an media item from the "Info" tab, it seems to jump the "Content" and highlight both after save.

![image](https://user-images.githubusercontent.com/2919859/50738348-30711600-11d3-11e9-9318-fcab9d30e7ce.png)

![image](https://user-images.githubusercontent.com/2919859/50738366-539bc580-11d3-11e9-8588-68e0a4109661.png)

In content section, when using save or publish button it seems to stay on the "Info" tab.

**Comment by bjarnef** [comment]
The same happens when saving a folder media type, when both tabs are highlighted.

![image](https://user-images.githubusercontent.com/2919859/50738426-feac7f00-11d3-11e9-871b-f0cead04a11b.png)

**Comment by kjac** [comment]
Hmm... I fixed a similar issue for content at some point. I'll dig into this.

**Comment by kjac** [comment]
PR in #3972

**Comment by nul800sebastiaan** [comment]
Fixed in https://github.com/umbraco/Umbraco-CMS/pull/3972
