### ISSUE TITLE
Set a maximum width of text in tabs

### ISSUE THREAD

**Issue by bjarnef** [umbraco/Umbraco-CMS#3960]
In v7 a new feature was added the rename listview "child items" tab name to something else. If the text of this (or the name of a content app) is very long, should we limit this to a maximum? Eventually add a tooltip with the full name.

![image](https://user-images.githubusercontent.com/2919859/50738714-965f9c80-11d7-11e9-8ac4-b8bf239060bd.png)

![image](https://user-images.githubusercontent.com/2919859/50738718-a37c8b80-11d7-11e9-811b-cc2ce64edaa7.png)

e.g. by extending this part of the css:

```
.umb-sub-views-nav-item-text {
    font-size: 12px;
    line-height: 1em;
    max-height: 1em;
    max-width: 10em;
    overflow: hidden;
    text-overflow: ellipsis;
    white-space: nowrap;
}
```

![image](https://user-images.githubusercontent.com/2919859/50738753-e0488280-11d7-11e9-948a-02eefe523f67.png)

**Comment by nul800sebastiaan** [comment]
Upon further reflection yesterday: let's just set a maximum number of characters instead. Sorry for the mixed messages 😊

**Comment by nul800sebastiaan** [comment]
This issue has been in the `up for grabs` state for quite a while now and it seems nobody is ready to pick this one up.

For now we'll close this issue to prevent the list of `up for grabs` from becoming very stale. We're happy to re-open it if someone still thinks it's good to work on this. 

If anyone is about to pick this issue up to fix it, make sure to test first if you can reproduce the problem in the latest version before you start to work on it.

Thanks!
Sebastiaan on behalf of Umbraco HQ.
