### ISSUE TITLE
Adjust disabled toggle

### ISSUE THREAD

**Issue by bjarnef** [umbraco/Umbraco-CMS#3962]
In languages view in v8 the default language toggle looks disabled because of the following css:

```
.umb-permission--disabled {
    opacity: .8;
}
```

![image](https://user-images.githubusercontent.com/2919859/50739602-4686d280-11e3-11e9-857f-7c6691f40e9c.png)

I think the `umb-toggle` (button element) should have a disabled state, where browsers doesn't focus on disabled elements (as with a diabled checkbox) when using keyboard tab key and it doesn't have the box shadow in disabled state as in active and focus state.

Browsers also have a default cursor style on disabled elements, but we can also control this using something like this:

```
.umb-toggle:disabled, .umb-toggle:disabled .umb-toggle__toggle {
    cursor: not-allowed;
}
```
Furthermore it seems the checkmark or cross icons needs to adjusted so they are centered vertically.

**Comment by bjarnef** [comment]
@nul800sebastiaan I think the PR can be cherry picked to `dev-v7` except commit https://github.com/umbraco/Umbraco-CMS/pull/3967/commits/0d8450ef45aa74182c562564abf0f506b6bdf8f6

**Comment by nul800sebastiaan** [comment]
Fixed in https://github.com/umbraco/Umbraco-CMS/pull/3967

**Comment by nul800sebastiaan** [comment]
Cherry picked for v7: https://github.com/umbraco/Umbraco-CMS/commit/d53d0b4271110d49dfc5bcaadff1c68ef6506385
