### ISSUE TITLE
Starter Kit - updated to support v8

### ISSUE THREAD

**Issue by clausjensen** [umbraco/Umbraco-CMS#3964]
child of https://github.com/umbraco/Umbraco-CMS/issues/3966

The starterkit needs to be updated to support V8.
No new functionality is to be added in this task.
requires #4254
requires #4255

**Comment by RobertCopilau** [comment]
We have some issue upgrading to latest build (the build that contains the fix for macros).
When the issue is fixed and macros are working again, we can start packaging the starter kit.
