### ISSUE TITLE
Add nicer confirm dialog when deleting language

### ISSUE THREAD

**Issue by bjarnef** [umbraco/Umbraco-CMS#3968]
When deleting a language in v8 it use a traditional browser confirm, but it is a bit inconsistent with the rest of the backoffice UI.

![image](https://user-images.githubusercontent.com/2919859/50740597-f7479e80-11f0-11e9-8810-a5366db4df1b.png)

E.g. in media section is use `umb-confirm` directive/component.

![image](https://user-images.githubusercontent.com/2919859/50740605-1e05d500-11f1-11e9-8e78-9679a0ab5f08.png)

Other parts of the UI, e.g. repeatable textstrings are using the `umb-confirm-action` directive.

![image](https://user-images.githubusercontent.com/2919859/50740644-d3d12380-11f1-11e9-9729-82e1d100d3ce.png)

It would be great if it used one of these components 👍

**Comment by nul800sebastiaan** [comment]
Yep, I think `umb-confirm` makes sense here to stick with the pattern of a delete button triggering it.

I've marked this as "Up for grabs" so that you or someone else coming along could create a pull request for it.

**Comment by bjarnef** [comment]
@nul800sebastiaan great! 👍 I am also thinking if it would make more sense the to make the button red for delete/critical actions?

**Comment by nul800sebastiaan** [comment]
Dunno, will ask around!

**Comment by bjarnef** [comment]
@nul800sebastiaan PR is ready. Much better right?  :wink: :hand:

**Comment by nul800sebastiaan** [comment]
Very nice indeed, thanks @bjarnef  !

Fixed in  https://github.com/umbraco/Umbraco-CMS/pull/4108
