### ISSUE TITLE
Umbraco Deploy tends to import UDA's automatically

### ISSUE THREAD

**Issue by LennardF1989** [umbraco/Umbraco-CMS#3970]
I have seen this particular issue a few times over the last year, but it pestered me three times in a row on a single day few weeks back. So I figured it's time to report it.

When we have a local Umbraco project running, multiple developers are usually working on it at the same time, both code and DB-wise (we have a shared Azure DB instance). It's not uncommon for me to regularly switch branches to review and merge code of my co-workers.

When Umbraco Deploy is installed on a project, as such that it keeps track of UDA-files, I have noticed that if you switch between branches with different versions of the UDA-files, it can happen that when the AppPool spins up Umbraco Deploy decides to import those by itself (as in: without making a deploy marker file to do so). 

This behavior, regardless if it's intended or a bug, is really annoying and has caused me to lose all my properties thee times on the same day. After import, not only does it wipe properties that do not exist anymore, it will also wipe all data associated to it. So re-importing the UDA's that contain the now-deleted properties from a different branch, does not recover the data that had been set on the content.

Aside from it begin annoying, it would be really great if we can have a Web.config option to completely disable Umbraco Deploy during development,. Then whenever we want to prepare a build for the Dev-environment, we switch it on, "deploy-export" and push that to our deployment pipeline. This last stap we already do every time we want to deploy anyway.

**Comment by nul800sebastiaan** [comment]
At the moment, our recommended setup is to use a single database per developer, that's the only way the Cloud workflow will work properly and avoids the issues you've encountered.

For more info, read this answer in the FAQ: https://our.umbraco.com/documentation/Umbraco-Cloud/Frequently-Asked-Questions/#umbraco-cloud-creates-a-sql-ce--localdb-database-for-me-can-i-use-a-shared-sql-server-for-my-development-team-instead

Ps. There's a dedicated issue tracker for Cloud here: https://github.com/umbraco/Umbraco.Cloud.Issues
