### ISSUE TITLE
Fix Google maps integration in starterkit

### ISSUE THREAD

**Issue by clausjensen** [umbraco/Umbraco-CMS#3975]
child of https://github.com/umbraco/Umbraco-CMS/issues/3966

Starterkit currently contains TerraType.GoogleMapsV3.dll. Will this work in V8 - if not - what can we do as an alternative?
If nothing - see if we can remove whatever functionality was supported by this 3rd party plugin.

**Comment by Shazwazza** [comment]
This will not work with v8 because there is no v8 package and it's not a package owned by us

So we'd want to either replicate all the functionality, update their package to v8 to work, or exclude maps from the starter kit.

**Comment by clausjensen** [comment]
Agree - we'll exclude the functionality for now as it isn't a crucial feature or anything.
