### ISSUE TITLE
v8 - Search in Redirect URL Management is not consistent with rest of UI

### ISSUE THREAD

**Issue by bjarnef** [umbraco/Umbraco-CMS#3982]
In v8 the search icon is not placed inside the search input as it is in v7.

![image](https://user-images.githubusercontent.com/2919859/50796767-0141ce00-12d3-11e9-9cf6-98733d4deb57.png)

Furthermore this is a bit inconsistent with listview search for content, media and member.

![image](https://user-images.githubusercontent.com/2919859/50796897-5da4ed80-12d3-11e9-85af-760756b66996.png)

![image](https://user-images.githubusercontent.com/2919859/50796910-685f8280-12d3-11e9-9a4b-af4d98064d95.png)

**Comment by nul800sebastiaan** [comment]
Seems like a nice improvement that could be made there yep!

I've marked this as "Up for grabs" so that you or someone else coming along could create a pull request for it.

**Comment by bjarnef** [comment]
@nul800sebastiaan it seems it has the correct markup in the redirects dashboard

```
<umb-editor-sub-header>

        <umb-editor-sub-header-content-right>

            <umb-editor-sub-header-section ng-if="vm.dashboard.userIsAdmin === true">

                <umb-button
                    ng-if="vm.dashboard.urlTrackerDisabled === false"
                    type="button"
                    size="s"
                    action="vm.disableUrlTracker()"
                    label-key="redirectUrls_disableUrlTracker">
                </umb-button>

                <umb-button
                    ng-if="vm.dashboard.urlTrackerDisabled === true"
                    type="button"
                    size="s"
                    button-style="success"
                    action="vm.enableUrlTracker()"
                    label-key="redirectUrls_enableUrlTracker">
                </umb-button>

            </umb-editor-sub-header-section>

            <umb-editor-sub-header-section ng-if="vm.dashboard.urlTrackerDisabled === false">

                <form class="form-search -no-margin-bottom pull-right" novalidate>
                    <div class="inner-addon left-addon">
                        <i class="icon icon-search"></i>
                        <input
                            class="form-control search-input"
                            type="text"
                            localize="placeholder"
                            placeholder="@general_typeToSearch"
                            ng-model="vm.dashboard.searchTerm"
                            ng-change="vm.filter()"
                            prevent-enter-submit
                            no-dirty-check>
                    </div>
                </form>

            </umb-editor-sub-header-section>

        </umb-editor-sub-header-content-right>

    </umb-editor-sub-header>
```

For some reason the form with class `form-search` is removed from DOM at least in Chrome.

If I manipulate the DOM from the console the wrap the `inner-addon` with a div with the class `form-search` it loooks like the following. If I try use a form instead of a div (as in the view file) it seems Chrome ignore this, because there is already the parent form.

![image](https://user-images.githubusercontent.com/2919859/50936387-cb861c00-146f-11e9-973a-6521d32eb708.png)

Could it be because it already is inside another `form` which is invalid.

![image](https://user-images.githubusercontent.com/2919859/50936350-9c6faa80-146f-11e9-8096-f8227f2a7daa.png)

In v7 it seems we didn't had the parent `<form name="dashboardForm">`

Isn't this a problem if we want to place a form inside a dashboard?

**Comment by bjarnef** [comment]
In v7 it seems it also has the parent form as child element in `Umbraco.DashboardController`

```
<div ng-controller="Umbraco.DashboardController" class="ng-scope">
   <form ng-show="!page.loading" class="umb-dashboard">
      ...
   </form>
</div>
```

in v8 it has `name="dashboardForm"` added to the form, which cause this styling issue.

```
<div ng-controller="Umbraco.DashboardController" class="ng-scope">
   <form ng-show="!page.loading" class="umb-dashboard">
      ...
   </form>
</div>
```

but added empty name attribute or name attribute with a random value also cause thie styling issue.

**Comment by kjac** [comment]
Blimey @bjarnef you've added a lot here since I saw the issue last. Looks like you came to the same conclusions as I did, though.

Changing `<form` to `<ng-form` makes Chrome happy, and Angular doesn't have a problem with nesting those.

PR in #4070
