### ISSUE TITLE
v8 - Hide file extension when media item has file

### ISSUE THREAD

**Issue by bjarnef** [umbraco/Umbraco-CMS#3983]
When you create a file media item and save this, it looks like this in the media section in grid listview layout in v8.

![image](https://user-images.githubusercontent.com/2919859/50797103-ee7bc900-12d3-11e9-9e00-47d80e794956.png)

When the media item doesn't have any file uploaded or it has been removed, there is no file extension. In this case we should probably hide the extension or something else to visualize the media item doesn't have any file.

![image](https://user-images.githubusercontent.com/2919859/50797233-6649f380-12d4-11e9-9fd0-cb95fb2a1529.png)

**Comment by nul800sebastiaan** [comment]
This might also be a problem for v7.

**Comment by nul800sebastiaan** [comment]
Fixed in: https://github.com/umbraco/Umbraco-CMS/pull/3984

And cherry-picked the file extension part to v7 https://github.com/umbraco/Umbraco-CMS/commit/1213551ca951db86acc0fda3f40b0a1d4efad4a5
