### ISSUE TITLE
v8 - Update slider in image cropper

### ISSUE THREAD

**Issue by bjarnef** [umbraco/Umbraco-CMS#3985]
In v8 we now have a new slider based on noUiSlider: https://refreshless.com/nouislider/

![image](https://user-images.githubusercontent.com/2919859/50800696-951a9680-12e1-11e9-84a0-263607daa154.png)

I think we can benefit from this and use it as a bit cleaner slider in image cropper instead of a regular HTML5 `input[type=range]` and make it a bit more consistent.

![image](https://user-images.githubusercontent.com/2919859/50800979-1b83a800-12e3-11e9-9189-831fc220b6df.png)

At the moment I think we can style the existing range input a bit, but it might vary how much control we have on styling this, but here is an example.
https://css-tricks.com/styling-cross-browser-compatible-range-inputs-css/

Some of the features from noUiSlider like tooltip, markers etc. could maybe also be useful.
What do you think?

Should we go we the approach of styling the `input[type=range]` via css or use noUiSlider to extend the underlying range input, e.g. something like this: https://codepen.io/OlibeCPG/pen/RQEyJW

**Comment by bjarnef** [comment]
We could maybe also re-use the `umb-range-slider` component in this case: https://github.com/umbraco/Umbraco-CMS/blob/temp8/src/Umbraco.Web.UI.Client/src/common/directives/components/umbrangeslider.directive.js

**Comment by bjarnef** [comment]
I gave it a try with `umb-range-slider` component used for this image cropper slider component and now I have something this. with some a basic configuration.

![image](https://user-images.githubusercontent.com/2919859/50861444-fea9ac00-1398-11e9-9bbd-8535631c8cd4.png)

**Comment by nul800sebastiaan** [comment]
This one is a "go!" - good idea and we'd love to get that done.

I've marked this as "Up for grabs" so that you or someone else coming along could create a pull request for it.

**Comment by bjarnef** [comment]
@nul800sebastiaan I have submitted a PR https://github.com/umbraco/Umbraco-CMS/pull/4487
It might need a bit adjustments, but almost there.
