### ISSUE TITLE
When saving only one content variant, changes on other dirty variants are cleared

### ISSUE THREAD

**Issue by bergmania** [umbraco/Umbraco-CMS#3988]
Child of https://github.com/umbraco/Umbraco-CMS/issues/3695

**Comment by bergmania** [comment]
Turned out to be only on RTE properties

**Comment by bergmania** [comment]
Relates: https://github.com/umbraco/Umbraco-CMS/issues/3988

**Comment by bergmania** [comment]
PR: https://github.com/umbraco/Umbraco-CMS/pull/3995

**Comment by warrenbuckley** [comment]
After a quick chat with @Shazwazza this has already been code reviewed.
I have re-tested this and RTE in the grid now works again for V8 :)
