### ISSUE TITLE
.eslintignore present in zip package

### ISSUE THREAD

**Issue by uSkinned** [umbraco/Umbraco-CMS#3989]
.eslintignore present in zip package 7.13.0

**Comment by uSkinned** [comment]
.eslintignore present in zip package

**Comment by nul800sebastiaan** [comment]
I've reverted #3563 in commit https://github.com/umbraco/Umbraco-CMS/commit/ff085c97ce4f8c7d7abb0510401ad0ddb17f2ae7 as I didn't realize fully what this file was for, I thought it was only used when working on the Umbraco-CMS actual source code, didn't realize it was for meant to be for when you were actually building Umbraco websites.

As with a `.gitignore` file, we shouldn't prescribe what the `.eslintignore` file looks like for individual developers trying to use Umbraco.
