### ISSUE TITLE
Can't change variant after closing main view in split view

### ISSUE THREAD

**Issue by bergmania** [umbraco/Umbraco-CMS#3991]
After closing the main variant in a splitview, we cant change the variant in the dropdown anymore:

![image](https://user-images.githubusercontent.com/1561480/50832928-f8dba880-134f-11e9-816f-0e036b9aa6d6.png)

![image](https://user-images.githubusercontent.com/1561480/50832985-24f72980-1350-11e9-9661-3bb8e39a25f0.png)

**Prerequisites**
- Have two cultures
- Have a variant document type

**Comment by kjac** [comment]
PR in #4069

**Comment by nul800sebastiaan** [comment]
Fixed in https://github.com/umbraco/Umbraco-CMS/pull/4069
