### ISSUE TITLE
GetPreValuesCollectionByDataTypeGuid()?

### ISSUE THREAD

**Issue by Raskens** [umbraco/Umbraco-CMS#3992]
Hi,

Right now we only have access to ApplicationContext.Services.DataTypeService.GetPreValuesCollectionByDataTypeId() and the data types ID:s differs localhost vs Live site.
My suggestion is to use the guid instead of id because they stay the same regardless localhost/staging/live site --> Something like: ApplicationContext.Services.DataTypeService.**GetPreValuesCollectionByDataTypeGuid**()

**Comment by nul800sebastiaan** [comment]
Sure, that seems like a good addition!

I've marked this as "Up for grabs" so that you or someone else coming along could create a pull request for it.

**Comment by nul800sebastiaan** [comment]
This issue has been in the `up for grabs` state for quite a while now and it seems nobody is ready to pick this one up.

For now we'll close this issue to prevent the list of `up for grabs` from becoming very stale. We're happy to re-open it if someone still thinks it's good to work on this. 

If anyone is about to pick this issue up to fix it, make sure to test first if you can reproduce the problem in the latest version before you start to work on it.

Thanks!
Sebastiaan on behalf of Umbraco HQ.
