### ISSUE TITLE
Related links table breaks out of nested content box when links are very long

### ISSUE THREAD

**Issue by drummerboy46** [umbraco/Umbraco-CMS#3994]
Can we add something along the lines of

.umb-nested-content__content .col-link {
    word-break: break-all;
}

To fix this?

**Comment by nul800sebastiaan** [comment]
If you have an example screenshot then that would be very helpful to reproduce the issue, which I'm sure exists.

I've marked this as "Up for grabs" so that you or someone else coming along could create a pull request for it.

**Comment by drummerboy46** [comment]
Here's whats's happening:

![related links bust out](https://user-images.githubusercontent.com/6703035/50892061-8c1ae980-13f5-11e9-8ba5-f36edaa6824f.jpg)

**Comment by drummerboy46** [comment]
Its actually worse than this screenshot, if you scale the width of the browser, the table makes no accommodation for the narrowing container and starts to bust out again.

Some responsive CSS required for this table

**Comment by robeades** [comment]
Just thought I'd add that it's actually even worse if you happen to be using this construct within a grid editor.  It becomes pretty unusable then as you can see from the screenshot below.

![related links issue](https://user-images.githubusercontent.com/32463611/51614382-73deba80-1f1d-11e9-8bec-3969d1aee7eb.png)

**Comment by nul800sebastiaan** [comment]
Just FYI: I haven't tested this yet, but hopefully [RJP Multi URL Picker](https://our.umbraco.com/packages/backoffice-extensions/multi-url-picker/) should work a lot better in both scenarios.

This URL picker will be added to the upcoming 7.14 release as the default and RelatedLinks will be deprecated. Existing RelatedLinks datatypes will remain though. If you're currently building a site it might be good to start using RJP now. I haven't checked if you can switch from the plugin to the built-in version when 7.14 comes out.

With that said, I'll remove the "up for grabs" tag as RelatedLinks is now deprecated and should no longer be updated. I will close this issue with the advise to check out Multi URL Picker instead.
