### ISSUE TITLE
V8 - Package Post Install Control. Remove ASCX and use Angular View

### ISSUE THREAD

**Issue by warrenbuckley** [umbraco/Umbraco-CMS#3996]
Requires #4010

Currently the Umbraco packager has an option to set an .ascx usercontrol to load in once the package has finished installing.

Some packages in the community use this functionality to give users a way to configure the package they have just installed.

Instead of loading an .ASCX usercontrol after install - it should work with an Angular view

**Comment by Shazwazza** [comment]
I thought this functionality was already built in 🤔

**Comment by warrenbuckley** [comment]
@shazwazza let me test this morning & triple check, it may just be some legacy code that may have given me a red herring

**Comment by Shazwazza** [comment]
Nah just checked the code, the code for that is in `PackageInstallController.CleanUp`, should be pretty easy to do, currently it still assumes an ascx in the 'Control` value

**Comment by Shazwazza** [comment]
See PR https://github.com/umbraco/Umbraco-CMS/pull/4101

**Make sure that #4010 is reviewed and merged first!!**

**Comment by zpqrtbnk** [comment]
tests green, code review ok, site runs, merging
