### ISSUE TITLE
upgraded 7.12.4 to 7.13 causes unsaved changes prompt on browsing tree

### ISSUE THREAD

**Issue by drummerboy46** [umbraco/Umbraco-CMS#3997]
After upgrading a project from 7.12.4 to 7.13 I'm now prompted to commit unsaved changes every time I click on an item in the content tree.

You need to wait a second or two to be sure all properties have loaded before selecting another item in the tree.

**Comment by madsoulswe** [comment]
I can confirm that this is happening.  But it feels "random" and hard to replicate

**Comment by madsoulswe** [comment]
@drummerboy46 have you tried clearing the browser cache? I tried to replicate it with the developer console open (with "disable cache" enabled) in chrome and now I can't replicate it.

**Comment by nul800sebastiaan** [comment]
When you see this, can you please try to figure out which datatypes are on the document type of the content item you're moving away from @drummerboy46 ?

**Comment by drummerboy46** [comment]
Yep, its the MNTP/MNTP2 with no entries.

**Comment by nul800sebastiaan** [comment]
Workaround posted here: https://our.umbraco.com/forum/using-umbraco-and-getting-started/95232-713-issues#301100

**Comment by drummerboy46** [comment]
The same problem exists when there's an MNTP inside a nested content. If it contains items and is expanded, but no modified it kicks off an unsaved changes prompt.

**Comment by nul800sebastiaan** [comment]
@drummerboy46 Not in the upcoming 7.13.1 ☺
