### ISSUE TITLE
Feature Request V8: Installed Packages List - Allow Packages to have Config views

### ISSUE THREAD

**Issue by warrenbuckley** [umbraco/Umbraco-CMS#3998]
A nice to have would be that the list of installed packages, that you could have a new button next to uninstall to take you back to the angular view to modify any user settings/configuration of the package if needed.

This would be separate/different from the post-install control. As maybe not all things would need to be reconfigured or changed.

This would help to remove the clutter of dashboards being added to the Settings section in order for package developers to allow some configuration.

**Comment by skttl** [comment]
#3911 has some discussion too.

**Comment by warrenbuckley** [comment]
Closed fixed in this PR - https://github.com/umbraco/Umbraco-CMS/pull/4101
