### ISSUE TITLE
Allowing 1 media type that has an imagecropper, breaks the pick a media type functionality in the media listview

### ISSUE THREAD

**Issue by Migaroez** [umbraco/Umbraco-CMS#3999]
When you create extra mediatypes and allow multiple of them on another mediatype, you get the option of picking what type of file you are uploading when using the bulk upload functionality.

However, if you add exactly 1 mediatype that has an image cropper, this mediatype selector does not show and (a random) filetype is chosen for you.

### Specifics

- Version 7.12.4 (haven't tested on older versions)
- Any browser, its in the angular functions, see below
- No errors, just unwanted behaviour.

### Steps to reproduce

1. Create 2 new mediatypes (can inherit from file, doesn't matter, as long as they don't have an image cropper)
2. Create 2 new mediatypes as a container (can inherit from folder, doesn't matter)
3. In permissions for container 1, add both new mediatypes
4. In permissions for container 2, add both new mediatypes and the default image type
5. (make sure that in both containers, only the types mentioned are present)
6. Create a new container of type 1 in the media, and drop files (1 or more) in the dropzone, you should get a mediatype picker dialog
7. Do the same for type 2 and it should upload them immediately without giving you the dialog

### Expected result

I would expect the bulk upload to only immediately upload if there is only 1 file type possible
Or there is exactly 1 match between with or without image cropper.
Example 1.txt 2.txt 3.img 4.jpeg + 1 file type with cropper and 1 without => 1,2 = without + 3,4 = with.

### Actual result

See description and reproduction steps

### Related sourcefiles
https://github.com/umbraco/Umbraco-CMS/blob/dd6e764588d22ef2b7bce01fd504ece89834f181/src/Umbraco.Web.UI.Client/src/common/directives/components/upload/umbfiledropzone.directive.js
lines 84 to 105
line 38 gets its value from 
https://github.com/umbraco/Umbraco-CMS/blob/1bb593d264a085f94a3ce3bd710392b350561430/src/Umbraco.Web.UI.Client/src/views/propertyeditors/listview/layouts/list/list.listviewlayout.controller.js
on line 21 (skipping the view)
which is set on line 38

Notice that the function called to populate the bound property is called mediaTypeHelper.getAllowedImagetypes => getAllowed**IMAGE**types
This function mostly does what it says it does, but is not the correct function to call in my opinion and its default else clause is a bit fishy compared to the comment directly above it.
https://github.com/umbraco/Umbraco-CMS/blob/1bb593d264a085f94a3ce3bd710392b350561430/src/Umbraco.Web.UI.Client/src/common/services/mediatypehelper.service.js line 23

**Comment by nul800sebastiaan** [comment]
@Migaroez What does this mean?

> Create 2 new mediatypes as a container (can inherit from folder, doesn't matter)

As a container, how?

**Comment by Migaroez** [comment]
> @Migaroez What does this mean?
> 
> > Create 2 new mediatypes as a container (can inherit from folder, doesn't matter)
> 
> As a container, how?

I mean a media type without any properties that is used as a container for other media nodes. Like a folder, sorry for the bad wording.

I have a demo repo if want to see it in action.

**Comment by nul800sebastiaan** [comment]
I would like to see it, I seem to be unable to make a new mediatype that would give me the dropzone.. :)

**Comment by nul800sebastiaan** [comment]
Ah thanks for the link.. any chance the login is not dangerous to share publicly? 😉

**Comment by Migaroez** [comment]
> Ah thanks for the link.. any chance the login is not dangerous to share publicly? 😉

We never ever ever use a typed password for non public sites, so its ok and its a local test db.

**Comment by Migaroez** [comment]
> I would like to see it, I seem to be unable to make a new mediatype that would give me the dropzone.. :)

The problem is an image picker on a mediatype, the dropzone gets its allowed media types from the listview it is present in, its the controller of the listview that calls the ?wrong? function.

**Comment by nul800sebastiaan** [comment]
> We never ever ever use a typed password for non public sites, so its ok and its a local test db. 

Care to tell me the username / password for this one then, since.. I'd need to log in to see the problem 😛

**Comment by Migaroez** [comment]
> > We never ever ever use a typed password for non public sites, so its ok and its a local test db.
> 
> Care to tell me the username / password for this one then, since.. I'd need to log in to see the problem 😛

Its in the description of the repo 😄  => team@umbrace.be (both username and pass)

**Comment by nul800sebastiaan** [comment]
Duh.. I was looking for a readme.md or something, didn't see the description under the repo name. 🤦‍♂️

I see the problem now, if you'd like to submit a PR for it then please do that makes it much easier than trying to describe in text which line to look at and why it's wrong. Looking at proposed changes is much easier.

Sidenote: I am ashamed to admit - I have absolutely no idea how to  create a media type that will add a drop zone like you did with `Drivers` and `Drivers and images`, any hints?

**Comment by Migaroez** [comment]
I don't know how to fix it, only where the offending code is present. And honestly i don't have the time to look into it further. I just wanted to check the code to see what I could do to have a workaround for the current project I'm working on and since i had the files open, i put them in the issue as a reference for anyone who would be willing to fix it.

For the dropdzone, that is a property (named Contents) with "List View - Media" as the datatype. Or you know, you can copy the "Folder" Media type.

**Comment by nul800sebastiaan** [comment]
This issue has been in the `up for grabs` state for quite a while now and it seems nobody is ready to pick this one up.

For now we'll close this issue to prevent the list of `up for grabs` from becoming very stale. We're happy to re-open it if someone still thinks it's good to work on this. 

If anyone is about to pick this issue up to fix it, make sure to test first if you can reproduce the problem in the latest version before you start to work on it.

Thanks!
Sebastiaan on behalf of Umbraco HQ.
