### ISSUE TITLE
v8 - Changing tag values don't track dirty changes on the form

### ISSUE THREAD

**Issue by Shazwazza** [umbraco/Umbraco-CMS#4006]
Reproduction
------------

Add a tag property type,  create some content with that property, remove some tags, don't save and navigate away, you will not be prompted that you have pending changes.

**Comment by kjac** [comment]
I can reproduce - will figure out a fix :)

**Comment by kjac** [comment]
PR in #4015

**Comment by clausjensen** [comment]
Fixed in https://github.com/umbraco/Umbraco-CMS/pull/4015
