### ISSUE TITLE
@ character error in attribute

### ISSUE THREAD

**Issue by bariskrdrl** [umbraco/Umbraco-CMS#4013]
I'm using uk-parallax = "media: @l" in html.

Example:
<div uk-parallax="media: @l"></div>

However, when I run it, it has an error because of the character.
What should I do. Thanks

**Comment by nul800sebastiaan** [comment]
Hey there @bariskrdrl - I would recommend you ask you question on the forum where our friendly community can try to help you out: https://our.umbraco.com/
