### ISSUE TITLE
ClientDependency breaks CSS added for issue #2910

### ISSUE THREAD

**Issue by stevemegson** [umbraco/Umbraco-CMS#4016]
The fix for issue #2910 modified the styling of unpublished items in list view, but ClientDependency breaks the new CSS when minifying it, so that unpublished items are not dimmed as expected.

umb-table.less contains the selector
`.-content :not(.with-unpublished-version).-unpublished`

ClientDependency assumes that it is safe to remove a space before a colon, producing the selector
`.-content:not(.with-unpublished-version).-unpublished`, which doesn't match the target elements.

While the underlying bug is in ClientDependency, the problem can be avoided by reordering the selector as `.-content .-unpublished:not(.with-unpublished-version)`

**Comment by nul800sebastiaan** [comment]
Interesting workaround! 👍 

I've marked this as "Up for grabs" so that you or someone else coming along could create a pull request for it.
