### ISSUE TITLE
[Minor] canvasdesigner.panel.js not found in preview mode

### ISSUE THREAD

**Issue by ssougnez** [umbraco/Umbraco-CMS#4018]
Hello,

I noticed that when I'm in preview mode, I have the following error in the Google developer console:

> lazyload.js:260 GET http://localhost:11773/umbraco/js/canvasdesigner.panel.js net::ERR_ABORTED 404 (Not Found)

As I don't really know what this file is supposed to do, I don't know the severity of the issue but I guess it's minor as the preview mode seems to be working. I guess Umbraco should stop trying to load this file if it's not necessary or include it if it is.

**Comment by nul800sebastiaan** [comment]
Seems like an old left-over, should be able to simply delete it from `src\Umbraco.Web.UI.Client\src\canvasdesigner.loader.js`

I've marked this as "Up for grabs" so that you or someone else coming along could create a pull request for it.

**Comment by sebastian-claesson** [comment]
I have created a PR for this now. I also checked that there are no other references to canvasdesigner.panel.js in the solution.

**Comment by nul800sebastiaan** [comment]
Fixed in https://github.com/umbraco/Umbraco-CMS/pull/4022
