### ISSUE TITLE
Add GUIDs to internal index for debugging

### ISSUE THREAD

**Issue by jmayntzhusen** [umbraco/Umbraco-CMS#4019]
When debugging deployment errors on Umbraco Cloud you sometimes get an error message with a content nodes GUID, this is currently not in the internal index, so you have to either search through all content nodes or search in the database. An error can look like this:

```
The source environment has thrown a Umbraco.Deploy.Exceptions.RemoteApiException with message: The remote API has thrown an exception. It might have been caused by an inner System.NotSupportedException with message: Invalid prefix ‘D’.

The following artifacts might be involved:

umb://document/ee804d7a5b774e15ae741e7fb686225c
```

It would be great if we could simply take that guid and search either in the examine index through the developer section, or simply search for it in the search field from the content page.

**Comment by Shazwazza** [comment]
closing this since __Key is in the indexes

**Comment by jmayntzhusen** [comment]
For anyone wondering, @Shazwazza has a fix for the original issue lined up here: https://github.com/umbraco/Umbraco-CMS/pull/6530
