### ISSUE TITLE
Install hook for Deploy

### ISSUE THREAD

**Issue by zpqrtbnk** [umbraco/Umbraco-CMS#4025]
When Umbraco starts and finds a connection string, we assume we should be able to connect to the database, else fail (BootFailed).

Deploy used to work around this with a pre-execute method that cannot really work anymore.

We need a hook in Core to take control of the situation.

**Comment by zpqrtbnk** [comment]
PR: https://github.com/umbraco/Umbraco-CMS/pull/4080

what it does:
* add a `MaxLevel` property to `RuntimeLevelAttribute` so we can have composers that run *only* if installing (and won't run when just running)
* refator `RuntimeState` so that it give more details about the reason why it decided to run in a given state (run, install, etc)
* refactor `RuntimeState` so that, depending on some appSettings, it can treat a missing or empty database as a need to install instead of a boot failed

with this in place, the work that's currently done by Deploy in its `LocalInitializer`, which is installed via a `PreApplicationStartMethod`, can be done in a proper component - and should then work

Hasn't been tested by Deploy for now, but I *think* this PR makes sense regardless and can be merged. We'll make more changes if required. Also, it will be tested to some extend for Chauffeur.

**Comment by zpqrtbnk** [comment]
Testing: take a running site (with a version + a connection string in web.config) and remove the database sdf file, and restart the site (touch web.config). You should get a boot failed exception.

Then add the following appsetting:

```
<add key="Umbraco.Core.RuntimeState.InstallMissingDatabase" value="true" />
```

And restart the site - now you should be taken to the installer.

*no idea what the installer will do, though, haven't tested that*

**Comment by Shazwazza** [comment]
tested and merged, i made some updates: new RuntimeStateOptions where you can set these flags via code on PreAppStartup or via appsettings, also had to fix a quirk with the installer and error.html which needs to be pre-loaded, else the call to the error.html file results in a ysod and you don't see the error in the ui.
