### ISSUE TITLE
Doctype alias placeholder sometimes stays at Generating Alias...

### ISSUE THREAD

**Issue by bjarnef** [umbraco/Umbraco-CMS#4027]
When creating a document type the default value of alias input placeholder text is "Enter alias...", but when the name of the document type is entered the placeholder text change to "Generating Alias...".

If you then go to the alias input and clear the generated alias, the placeholder text is still "Generating Alias...". It should only be "Generating Alias..." while entering a document type name and when document type name is empty or alias text is empty, the placeholder text should be "Enter alias...".

Tested on Umbraco v.7.12.4

![image](https://user-images.githubusercontent.com/2919859/50972256-6d485000-14e6-11e9-8200-bd415df3cbc0.png)

Furthermore I think the alias input should have a max-width and maybe some truncate in "locked" mode using `text-overflow: elipsis;` so it doesn't overlap document type name (in case of very long alias) and/or long document type name.

Here it check for `undefined`, `null` and empty string.
https://github.com/umbraco/Umbraco-CMS/blob/dd6e764588d22ef2b7bce01fd504ece89834f181/src/Umbraco.Web.UI.Client/src/common/directives/components/umbGenerateAlias.directive.js#L92

but here it only check on `null` and empty string.
https://github.com/umbraco/Umbraco-CMS/blob/dd6e764588d22ef2b7bce01fd504ece89834f181/src/Umbraco.Web.UI.Client/src/common/directives/components/umbGenerateAlias.directive.js#L124

**Comment by nul800sebastiaan** [comment]
Nice catch! Agreed.

I've marked this as "Up for grabs" so that you or someone else coming along could create a pull request for it.

**Comment by nul800sebastiaan** [comment]
Cherry-picked to v7 - https://github.com/umbraco/Umbraco-CMS/commit/2ebd7a077cc5e71bd476f3f71d18d6ab16723e0c
