### ISSUE TITLE
Cleanup Filesystems registrations

### ISSUE THREAD

**Issue by zpqrtbnk** [umbraco/Umbraco-CMS#4028]
Current filesystems registrations (via DI) in v8 is clumsy and not practical to be used by packages etc - to replace inner filesystems - need to clean it up

**Comment by zpqrtbnk** [comment]
Review = code review for changes - notes in `FileSystemsComposer` re how to compose filesystems - one replaces the media fs with

```
composition.RegisterUniqueFor<IFileSystem, IMediaFileSystem>(
    _ => new MyCustomFs(args));
```

and can get the inner fs by injecting `SupportingFileSystems` and then

```
var innerFs = supportingFileSystems.For<IMediaFileSystem>();
```

Test = everything should still work, especially the filesystems

**Comment by warrenbuckley** [comment]
I suggested a friendly extension method name that's now been added
`composition.SetMediaFileSystem(() => new PhysicalFileSystem("~/media"));`

As opposed to the more generic `RegisterUniqueFor` just o make it a bit more Umbraco friendly & discoverable
