### ISSUE TITLE
Add contributors to package

### ISSUE THREAD

**Issue by bjarnef** [umbraco/Umbraco-CMS#4036]
At the moment when creating a package from package UI in backoffice one can add a author and author url, but often packages have more contributors e.g. as listed on the Analytics package page.
https://our.umbraco.com/packages/backoffice-extensions/analytics/

For now package developers either just enter the package owner as author and add some credits the contributors in e.g. readme or add the contributors as comma delimited string in author property.

I think it would make sense to add a list/array property for contributors, maybe in the branch `temp8-packages-ui` where it seems the package installer UI get some love ❤️ 

In the UI it could probably re-use e.g. textstring multiple property editor og multivalues prevalue editor.

**Comment by nul800sebastiaan** [comment]
It's a lovely idea but doesn't fit into our schedule right now, once the `packages-ui` branch is merged, feel free to help out and send us a PR! There's many more things we could probably do to that UI as well. :-)

I've marked this as "Up for grabs" so that you or someone else coming along could create a pull request for it.

**Comment by bjarnef** [comment]
@clausjensen I was hoping we could have this in v8.0 so we don't need to add contributors in Author property and then later a hack or a different package version to use Contributors property in v8.1 (where it only has a single name in Author property unless you only want to set one Author for the package, but it seems many packages set multiple names in Author property because it has contributors 🙂

**Comment by nul800sebastiaan** [comment]
Fixed in https://github.com/umbraco/Umbraco-CMS/pull/4385
