### ISSUE TITLE
MNTP - Could not convert string to integer + #4039, #4055

### ISSUE THREAD

**Issue by RobertCopilau** [umbraco/Umbraco-CMS#4037]
![Annotation 2019-01-11 090809.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5b151a952d7cd20011c4533d/125516c66e82c728ace21e0d46c99a942c9682bd86e6b103f60da1cd6416763e7855e37b29d5bb78e60037431f1d11f6140b1b56f6eb8c79f3b4687789595fbbd56e5a74c63c10a9bdd716eb57bf32975dc7e7e2de139db17770a599855d3f190f198cfb5a34a99d4ac85df548e35f18.jpg)

**Comment by RobertCopilau** [comment]
PR:https://github.com/umbraco/Umbraco-CMS/pull/4057

This also fixes MNTP unable to change Node type in the Configuration.
Content was always set no matter the choice.
https://github.com/umbraco/Umbraco-CMS/pull/4057/commits/8f41fe8d3840cccb5235ba632a6d69a2f8efbcc4

**Comment by RobertCopilau** [comment]
Found some more issues with the MNTP so I decided to push the fixes on this branch since they depended on it.

Fix for #4055 https://github.com/umbraco/Umbraco-CMS/pull/4057/commits/2ce3249c5e99fc27656f2af84b014bec937ea412

**Comment by RobertCopilau** [comment]
What to test:

*[] Create a doc type with three versions of MNTP - content, media and member type.
*[] Make sure that you can pick and remove selected items
*[] Make sure that you can save/publish nodes with selected items

**Comment by bergmania** [comment]
I can't remove selected item, when they are saved:
![4037-1](https://user-images.githubusercontent.com/1561480/51247116-70cb5380-198c-11e9-83d5-841b3138460a.gif)

**Comment by RobertCopilau** [comment]
@bergmania, did you get any console errors by any change?
I can't seem to be able to replicate.
I will look more into it tomorrow.

**Comment by bergmania** [comment]
@RobertCopilau , no there is no errors in the console. Are you sure the model.value is updated when remove is clicked.

**Comment by RobertCopilau** [comment]
This seems to be a separate issue, have been able to replicate on brand new site.
Created issue here -> https://waffle.io/umbraco/Umbraco-CMS/cards/5c4076b6db83d702e172c311
