### ISSUE TITLE
MNTP- xPath $current or setting a start node, does not return its children if is list view enabled

### ISSUE THREAD

**Issue by RobertCopilau** [umbraco/Umbraco-CMS#4039]
* Create a parent node with some children 
* Parent node should have a MNTP and list view on
* Make sure MNTP has the "$current" xPath query in the Editor settings
Now try to add a node using the MNTP
![Current.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5b151a952d7cd20011c4533d/125516c66e82c728ace21e0d46cb818831878dbdcda5fd53b652fa912a5265296b51a12e2281b47bea467d555c5a4eac40595a41a9f0dd7da3a42062c80d55b98e30063e937f03a6aa801eb500bf248c4d85b5be8949c1ed3437aa.jpg)
![Result.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5b151a952d7cd20011c4533d/125516c66e82c728ace21e0d46da9189368e97ebc3abaf51ab57f5973d047d317c06a67974d2b07dbb442f525a5f4ead405d5a11f5addf2eb4aa2e32db025fb28c341521842f1bbeb98a15be04be27894f86b4b88b44c2e92f68.jpg)
It works ok if the list view is set to off.

requires #4037

**Comment by RobertCopilau** [comment]
Update:
This is also the case if you select a start node with a content/media picker.

**Comment by Shazwazza** [comment]
@RobertCopilau we really don't want to use the content service, it's WAY less performant. The IEntitySlim already contains IsContainer, so you should easily be able to map that over

**Comment by Shazwazza** [comment]
@RobertCopilau you could just map it in the AfterMap logic of the EntityMapperProfile

**Comment by RobertCopilau** [comment]
Great! Thanks will do that :)

**Comment by RobertCopilau** [comment]
https://github.com/umbraco/Umbraco-CMS/pull/4057/commits/2e782a4f114c44184f5076a07fbe3c94b5104524
