### ISSUE TITLE
V8 Split view should open the content-tab/app or open the same app.

### ISSUE THREAD

**Issue by madsoulswe** [umbraco/Umbraco-CMS#4042]
1. Open content
2. Go to info tab
3. Then open another language and in split-view

![content-app](https://user-images.githubusercontent.com/7071187/51032666-24a19d00-15a1-11e9-8534-5f7dac9c89e5.JPG)

**Comment by nul800sebastiaan** [comment]
Yeah, you won't be editing the info in split-view, we should switch both back to the Content app when opening split view, good find! 👍

**Comment by kjac** [comment]
Actually the code is already trying to... just not in the right order. I have tracked down the issue and will push a PR soon.

**Comment by kjac** [comment]
PR in #4074

**Comment by nul800sebastiaan** [comment]
Fixed in #4074
