### ISSUE TITLE
Add 3 more icon colors

### ISSUE THREAD

**Issue by skttl** [umbraco/Umbraco-CMS#4043]
My OCD is killing me on this.

I love the new colour picker, it is so intuitive and easy to use (and you can even recolor the existing icon 👌)

But, the colors isn't filling up the space completely.

So could we find 3 more colours to add?
![image](https://user-images.githubusercontent.com/3726467/51032821-ad203d80-15a1-11e9-9129-9d63207c3b19.png)

I would suggest the following colours:

![image](https://user-images.githubusercontent.com/3726467/51033030-4cddcb80-15a2-11e9-94a9-6ef4556d8471.png)

![image](https://user-images.githubusercontent.com/3726467/51033042-5bc47e00-15a2-11e9-87c9-cf1e893ec72c.png)

![image](https://user-images.githubusercontent.com/3726467/51033010-3df71900-15a2-11e9-800a-bae862c63c20.png)

**Comment by jannikanker** [comment]
I suck at color theory, but am also slighty OCD prone so I agree that three more colors would fit VERY nicely :-) But where would your suggested colors fit in (orderwise)?

**Comment by skttl** [comment]
I don't know where they would fit, but I feel a real red color could be useful (I think the existing is more orange). Dark teal and pink is not available already, so they got the last places.

But I'm in know way attached to which colors are getting in. Mostly just having the last 3 spots filled :)

**Comment by jannikanker** [comment]
Maybe the incredibly detail oriented brain of @bjarnef would like to pitch in? :-)

**Comment by nathanwoulfe** [comment]
Would it make sense to include the Umbraco teal/purple/grey palette?

**Comment by nul800sebastiaan** [comment]
I love the OCD comment 😂

We had a bit of a talk about this one and the feedback is: we never really wanted all these different colors. They're hard to distinguish form each other and making doctypes with all the colors in the rainbow is not great for the end users. In v8 we'll switch back to having only a few (about 5) colors available to use with good contrast (it's almost impossible to distinguish the different oranges and yellows from each other).

We won't be changing this list for v7 though, sorry about your OCD! 😉

**Comment by abjerner** [comment]
@nul800sebastiaan so customized colors are still something that is out of the picture? The colors from the Umbraco branding may not mean much to editors, so I'd prefer being able to use a color that actually means something to the editor. I can't really do this now - at least not through the UI.

**Comment by nul800sebastiaan** [comment]
No customizable colors either. From our discussion I understand that colors CAN be useful if used sparingly. Contrast becomes a concern easily and when the tree looks like a rainbow then it stops adding value. Initially in v7 we didn't use to have colored icons at all but after seeing some larger sites it became clear that some sparingly used colors could be useful.

Could make for a nice simple package if people really want to use the exact colors of their favorite football team :-)
