### ISSUE TITLE
v8: Not possible to change color doctype icon without selecting icon

### ISSUE THREAD

**Issue by bjarnef** [umbraco/Umbraco-CMS#4052]
In v8 it seems it is no longer possible to change color of an existing document type icon without having to re-select to icon too.

In v7 as a part of the changes to `umb-color-swatches` it was possible just selecting another icon color and hit submit. In v8 one have to select another icon color, but also select the icon again (which then submit the form).

![image](https://user-images.githubusercontent.com/2919859/51089255-882af680-176a-11e9-9d8a-cbbacaaf70a3.png)

![image](https://user-images.githubusercontent.com/2919859/51089259-9711a900-176a-11e9-9694-0015ad96ff82.png)

It seems it is because the submit button now is hidden/remove, so you can't just change the color icon value of submit with the existing icon.

**Comment by bjarnef** [comment]
It have update this PR so it actually use the `on-select` callback is previously have added/prepared on `umb-color-swatches` so I can just update `$scope.model.color` here instead.

I had some issues with getting the callback working, where I got an console error: `TypeError: Cannot use 'in' operator to search for 'vm' in color-light-blue` 

![image](https://user-images.githubusercontent.com/2919859/51090275-cc71c300-1779-11e9-9d52-088fb96693f1.png)

but I then saw this: https://stackoverflow.com/a/48484100/1693918

After changing `onSelect: '&'` to `onSelect: '<'` it seems to work, but I am not sure why :)

**Comment by nul800sebastiaan** [comment]
Fixed in https://github.com/umbraco/Umbraco-CMS/pull/4053
