### ISSUE TITLE
v8 Create Template button shows 

### ISSUE THREAD

**Issue by mikeallen222** [umbraco/Umbraco-CMS#4054]
### Bug summary

When adding a template to a doc type that doesn't have a template, the button text reads, "[settings_createMatchingTemplate]"

### Specifics

Urls: 
/umbraco#/settings/documenttypes/edit/-1?create=true&notemplate=true
or
/umbraco#/settings/documenttypes/edit/1062 (obviously your ID will be different)

version of Umbraco: 8.0.0-alpha.58

Browsers: Chrome 71.0.3578.98 and FireFox 64.0. 

### Steps to reproduce

1) Create a new doc type and choose "doctype without template" as the type.
2) Click on the "Templates" link in the top right.

![image](https://user-images.githubusercontent.com/3188003/51094456-b44a7580-1772-11e9-8615-1bfe1c0cb3f0.png)

### Expected result

The button would have a friendly label.

### Actual result

The button label is "[settings_createMatchingTemplate]"

**Comment by nul800sebastiaan** [comment]
Thanks @mikeallen222 - fixed in https://github.com/umbraco/Umbraco-CMS/commit/92c278c593353aaa4af3011f68242734cc4e66b4

![image](https://user-images.githubusercontent.com/304656/51098605-c99fbe00-17cb-11e9-861d-df5749d08e97.png)
