### ISSUE TITLE
relateParentDocumentOnDelete not working

### ISSUE THREAD

**Issue by Ron-Brouwer** [umbraco/Umbraco-CMS#4058]
Hi Guys,

During restore from bin in content and media the following request is made:

/umbraco/backoffice/UmbracoApi/Relation/GetByChildId?childId=10580

The request to this API does not include the **alias** "relateParentDocumentOnDelete" of the relation requested. This results in a list of relations that most likely have nothing to do with the restore and results in errors or moves to a different website when the node is a copy of relation 'relateDocumentOnCopy' for example.

Also when looking at the source it seems that media is using the wrong relation where it should use 'relateParentMediaFolderOnDelete', however that also does not get posted to the API as wel resulting in the same undesired behavoir..

I havent been able to locate the issue yet

Kind Regards,
Ron

**Comment by dawoe** [comment]
Hi @Ron-Brouwer 

Thanks for reporting this. I will see if I can reproduce this. 

On what Umbraco version is this happening ?

Dave

**Comment by dawoe** [comment]
I just tested this on 7.13 and I confirm this is a issue. When a media item has more than one relation restoring fails because the alias is not passed to the api call.
