### ISSUE TITLE
V8: Rename Seperator to Separator

### ISSUE THREAD

**Issue by readingdancer** [umbraco/Umbraco-CMS#4060]
In the source code, probably forever, there have always been some reasonably obvious typos in the names of properties, this is one of the most obvious ones and I think it would be great if it was fixed in the V8 branch before the product is in its final release, or it would end up being a breaking change in the future, which I assume is one of the reasons it has never been fixed in the past.

Reproduction
------------

there are multiple instances of the word being miss spelt throughout the solution.

### Expected result

All miss spellings should be re-named to "Separator"

I will submit a pull request shortly :)

**Comment by nul800sebastiaan** [comment]
Fixed in https://github.com/umbraco/UmbracoDocs/pull/1304

**Comment by readingdancer** [comment]
Your welcome, great to see it merged in, thanks 😃
