### ISSUE TITLE
v8 template wysiwyg editor created items as Umbraco.Field() instead of Model.Value()

### ISSUE THREAD

**Issue by mikeallen222** [umbraco/Umbraco-CMS#4062]
### Bug summary

When using the wysiwyg editor for templates, using the "insert..." drop down to add a value creates the code @Umbraco.Field() which no longer works in v8.

### Specifics

Pretty much the summary ^^

### Steps to reproduce

1) Create a template
2) Navigate to Settings > Templates > [name of tempalte]
![image](https://user-images.githubusercontent.com/3188003/51129251-95d68f80-17ef-11e9-9fe5-43622b8b5eed.png)

3) In the editor screen, click on insert > "value > and choose a field from the drop down
![image](https://user-images.githubusercontent.com/3188003/51129267-a38c1500-17ef-11e9-9695-21f9d77b4604.png)

\
### Expected result

The editor would output @Model.Value("content")
It is my understanding that this is the correct way to display a field on the page.

### Actual result

The editor output @Umbraco.Field("content")
As far as I know this is left over from V7. When I try to run this in V8 I get the exception:
"Compiler Error Message: CS1061: 'UmbracoHelper' does not contain a definition for 'Field' and no accessible extension method 'Field' accepting a first argument of type 'UmbracoHelper' could be found (are you missing a using directive or an assembly reference?)"

![image](https://user-images.githubusercontent.com/3188003/51129330-cf0eff80-17ef-11e9-9dbf-224bd2fc6f73.png)

**Comment by nul800sebastiaan** [comment]
I'll close this one as we're working on it already at HQ, thanks for reporting! For PR, see: https://github.com/umbraco/Umbraco-CMS/pull/4040
