### ISSUE TITLE
Value of a price field cannot be used in a view

### ISSUE THREAD

**Issue by elit0451** [umbraco/Umbraco-CMS#4064]
When you add a property for price (decimal), and we do SavePost() it reads the property value, but when we use the property into the view it equates the value to 0. 

* Create a document type.
* Add property for price.
* Create a content item from this document type.
* Give value to the price field.
* Use the value of the price property in a view.
-> value is 0

**Comment by kjac** [comment]
I can reproduce this. PR in #4160

**Comment by nul800sebastiaan** [comment]
Fixed in https://github.com/umbraco/Umbraco-CMS/pull/4160
