### ISSUE TITLE
Images added by a Media Picker editor cannot be used in a view

### ISSUE THREAD

**Issue by elit0451** [umbraco/Umbraco-CMS#4065]
When you add pictures by a Media Picker editor (i.e. for a photos property), if you attempt to reference them in the view, an error that they are null appears.

* Create a document type.
* Add property for photos (Media Picker editor).
* Create a content item from this document type.
* Select several images.
* Use the images in a view.
-> value is null

**Comment by kjac** [comment]
@elit0451 I can't reproduce this.

Given a doctype with two media picker properties:

- `mediaPickerMultiple` configured with "Pick multiple items" enabled
- `mediaPickerSingle` configured with "Pick multiple items" disabled

On a page with images picked in both properties:

![image](https://user-images.githubusercontent.com/7405322/51321403-f6213780-1a62-11e9-99fc-532df428d0f9.png)

...rendered by this template:

```cshtml
@inherits Umbraco.Web.Mvc.UmbracoViewPage
@{
	Layout = null;
	var mediaPickerMultipleValue = Model.Value<IEnumerable<IPublishedContent>>("mediaPickerMultiple");
	var mediaPickerSingleValue = Model.Value<IPublishedContent>("mediaPickerSingle");
}

<html>
    <body>
        <h1>@Model.Name</h1>
        <h2>Media picker multiple</h2>
        @if(mediaPickerMultipleValue != null) {
            foreach(var media in mediaPickerMultipleValue) {
                <img src="@media.Url" title="@media.Name" height="200px" />
            }
        }
        else {
            <p>Media picker multiple has no value</p>
        }
        
        <h2>Media picker single</h2>
        @if(mediaPickerSingleValue != null) {
            <img src="@mediaPickerSingleValue.Url" title="@mediaPickerSingleValue.Name" height="200px" />
        }
        else {
            <p>Media picker single has no value</p>
        }
    </body>
</html>
```

...yields this beautiful result:

![image](https://user-images.githubusercontent.com/7405322/51321561-5dd78280-1a63-11e9-9983-ed409c3d9383.png)

**Comment by elit0451** [comment]
@kjac you were right! Thanks 🙂 
My problem was that I couldn't do `Model.MediaPickerMultipleValue.FirstOrDefault().Url`
