### ISSUE TITLE
Cannot select a Start node for a Media Picker editor

### ISSUE THREAD

**Issue by elit0451** [umbraco/Umbraco-CMS#4066]
When you add a property and its editor is a Media Picker, if you go to the settings of the editor and select a Start node and then press Save, the Start node won't be saved.

* In the Media tab add a couple of folders with some images inside. 
* Create a document type.
* Add property for photos (Media Picker editor).
* Go to the cogwheel and set a start node to be one of the folders previously added in the Media section.
* Save.
* Access again the settings of this editor.
-> no start node is selected

![StartNode.PNG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5b631124103d580013dcf6a4/125516c66e82c728ace21e0d46db809b3196ada68becfd0fe64de29b234324676b5ee17e7280b12ce8112e05095b4da941585e45f9fcdc22f2e03962964e49bc8f3900299f7744eeaa880dbe06b0218e4b82b3bc8a44c2eb3e26e099c2.PNG)

**Comment by kjac** [comment]
Seems I've found the error; will submit a PR when I have tested it.

**Comment by kjac** [comment]
PR in #4098

**Comment by nul800sebastiaan** [comment]
Fixed in https://github.com/umbraco/Umbraco-CMS/pull/4098
