### ISSUE TITLE
Mandatory fields with inserted information complain that there are errors or that the value of a property is empty

### ISSUE THREAD

**Issue by elit0451** [umbraco/Umbraco-CMS#4067]
When you insert information in the fight format into mandatory fields, validation messages that the value is empty or that the property has errors will occur. 

* Create a document type.
* Add both mandatory and nor required fields.
* Create a content item from this document type.
* Insert information into the fields.
* Save.
-> validation errors occur

![Required fields.PNG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5b631124103d580013dcf6a4/125516c66e82c728ace21e0d46da918b368b91ac8ba9b94aa151f4876b0a65633b0ba92e7391a172fd1779045d0b49af440c0940fffc892ba7b73975df555fbbd47f4366846c4ff8e7df46f554f832815d84b1b68b49c4ef3825e78c864a3d1c0d0ac4.PNG)

When you unmark them as mandatory  you will be able to save the content and after that you can make them again as required.

**Comment by kjac** [comment]
I can't reproduce this error:

![save-document-with-validation](https://user-images.githubusercontent.com/7405322/51231823-1965bd00-1965-11e9-9de8-8464c4794d79.gif)

I've tried:
- variant content
- invariant content
- mandatory validations
- regex/pattern validations

**Comment by elit0451** [comment]
Hi @kjac

The problem was the tags -> the PR in this [issue](https://github.com/umbraco/Umbraco-CMS/issues/4012) fixes it. You have probably tried when it was already merged 😊

Thank you for checking it up. I am closing this issue.
