### ISSUE TITLE
Headline doesn't save as headline but as normal text

### ISSUE THREAD

**Issue by elit0451** [umbraco/Umbraco-CMS#4068]
* Create a document type.
* Add a property Content with a Grid layout editor.
* Make sure Headline is enabled for a row configuration.
* Create a content item from this document type.
* Select a row configuration for the grid layout.
* Choose a Headline and insert some text.
* Save.
-> the styling will be defaulted to normal text

**Before**
![Headline before.PNG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5b631124103d580013dcf6a4/125516c66e82c728ace21e0d46c0919b278e8aa78aa9bd46a252e2916b0a65633b0ba92e7391a172fd1779045d0b49af440c0940fffc892ba7b73975df555fbbd47f4366846c4ff8e7df46f554f832815d84b1b68b49c4ef3825e688864e391f000ac4.PNG)
**After**
![Headline.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5b631124103d580013dcf6a4/125516c66e82c728ace21e0d46c0919b278e8aa78aabf301b44fff9e2c4533317346f62975d7e77fec177f075b5c4bac41595e41f9ac807ff0b32e6c981e5ab38532022d8c6853beb2901eb80bbb258f4880b6bd884bc7ed3823f5c6.png)

**Comment by bergmania** [comment]
PR: https://github.com/umbraco/Umbraco-CMS/pull/4347

**Comment by warrenbuckley** [comment]
@clausjensen has checked the code & I have done the testing all good. Merged in  :)
