### ISSUE TITLE
Link to an image is not being generated

### ISSUE THREAD

**Issue by elit0451** [umbraco/Umbraco-CMS#4072]
* Add a folder in the Media section 
* Add some images -> give them a name and then Save 
* Navigate to the Info tab of the Image 
-> no link is generated 
`This media item has no link`

![Image.PNG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5b631124103d580013dcf6a4/125516c66e82c728ace21e0d46c1999b2487c1e5cdf9ad4cae58f3806b1c65262b01f12f27d6b62cb91628545f5f4fad445d0a4da8af8c39baa47e21d40854b088270a36d43703adbf881eba05bd258f4e85b5bd8f4ac8fa70.PNG)

**Result**
![Result.PNG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5b631124103d580013dcf6a4/125516c66e82c728ace21e0d46da9189368e97ebc3abaf51ab57f5973d047d317c06a67974d2b07dbb442f525a5f4ead405d5a11f5addf2eb4aa2e32db025fb28c341521842f1bbeb98515be04be278e4b84b6b88f48c1ea2f68.PNG)

**Current**
![Current.PNG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5b631124103d580013dcf6a4/125516c66e82c728ace21e0d46cb818831878dbdcda5fd53b652fa912a5265296b51a12e2281b47bea467d555c5a4eac40595a41a9f0dd7da3a42062c80d55b98e30063e937f03a6aa8317b500bf248c4a81b7bc824dc5eb3c37aa.PNG)

**Comment by kjac** [comment]
PR in #4105

**Comment by nul800sebastiaan** [comment]
Fixed in https://github.com/umbraco/Umbraco-CMS/pull/4105
