### ISSUE TITLE
Adjust media item name on fileupload

### ISSUE THREAD

**Issue by bjarnef** [umbraco/Umbraco-CMS#4077]
In v7.13.0 a feature was introduced to make the media item name prettier, when uploading files.

However part of this might be related to the language, e.g. compare this sentence in Danish vs. English.
Danish: "Jeg taler dansk".
English: "I speak Danish".

In English it would use a capital letter for "Danish", but not in Danish.

E.g. when uploading these file names:
"Nye-patienter.jpg" -> "Nye Patienter"
"Facaden i 40erne.jpg" -> "Facaden i 40Erne"

For the term "40erne" og "40'erne" it would be great to keep the casing used in the filename.

**Comment by kjac** [comment]
@bjarnef it's not quite feasible to make the feature content aware (i.e. recognizing "danish" as a language).

I suggest we change the feature so it only uppercases the first letter of the file name, not every single word in the file name. How does that sound?

**Comment by bjarnef** [comment]
@kjac yes and in that case I think it would be better the leave the casing as in the uploaded file name :)

**Comment by nul800sebastiaan** [comment]
Hi guys, we've chosen to go with upper-casing each letter for now in the knowledge that this is imperfect and will never be perfect for every scenario, it works well for most scenario's though. 

I would encourage your to write your own eventhandlers that, during the saving of the node makes the node name look any way you want it to.

**Comment by bjarnef** [comment]
@nul800sebastiaan I totally understand this can't be perfect, but I think the upper casing makes more sense in English, while it cause issues in other languages/cultures.

Wouldn't it be better to leave the casing as in the original file name (it is okay to make the first character uppercase) and then add documentation on how to extend this?

**Comment by nul800sebastiaan** [comment]
@bjarnef Right now we've chosen to go with the scenario that makes sense for the majority.
