### ISSUE TITLE
v8: Disable LastPass on page heading

### ISSUE THREAD

**Issue by bjarnef** [umbraco/Umbraco-CMS#4089]
I think it is a bit annoying that LastPass wants to add the "autofill" icon on heading input in e.g. doctypes, which then cover the alias input.

![image](https://user-images.githubusercontent.com/2919859/51208746-c7924800-190e-11e9-8a47-8ad421dc5249.png)

To fix this we can add `data-lpignore="true"` to the input in `/views/components/editor/`

```
<div id="nameField" style="flex: 1 1 auto;">
    <div class="umb-editor-header__name-wrapper">
        <ng-form name="headerNameForm">
            <input data-element="editor-name-field"
                    data-lpignore="true"
                    title="{{key}}"
                    type="text"
                    class="umb-editor-header__name-input"
                    localize="placeholder"
                    placeholder="@placeholders_entername"
                    name="headerName"
                    ng-show="!nameLocked"
                    ng-model="name"
                    ng-class="{'name-is-empty': $parent.name===null || $parent.name===''}"
                    umb-auto-focus
                    val-server-field="Name"
                    required
                    autocomplete="off" />
        </ng-form>

        <umb-generate-alias data-element="editor-alias"
                            class="umb-panel-header-alias"
                            ng-if="!hideAlias"
                            alias="$parent.alias"
                            alias-from="$parent.name"
                            enable-lock="true"
                            server-validation-field="Alias">
        </umb-generate-alias>

    </div>

    <div class="umb-panel-header-name" ng-if="nameLocked" title="{{key}}">{{ name }}</div>

    <input data-element="editor-description"
            type="text"
            class="umb-panel-header-description"
            localize="placeholder"
            placeholder="@placeholders_enterDescription"
            ng-if="!hideDescription && !descriptionLocked"
            ng-model="$parent.description" />

    <div class="umb-panel-header-locked-description" ng-if="descriptionLocked">{{ description }}</div>

</div>
```

Apparently it also need to be added to "description" input otherwise it is shown at description input as well.

![image](https://user-images.githubusercontent.com/2919859/51208920-41c2cc80-190f-11e9-97e8-c8929e20b3d9.png)

```
<input data-element="editor-description"
        data-lpignore="true"
        type="text"
        class="umb-panel-header-description"
        localize="placeholder"
        placeholder="@placeholders_enterDescription"
        ng-if="!hideDescription && !descriptionLocked"
        ng-model="$parent.description" />
```

![image](https://user-images.githubusercontent.com/2919859/51209039-923a2a00-190f-11e9-8688-a440ba2346f5.png)

Alternatively it could be added as a directive which add the data attribute, which also could handle other password managers if there are similar issues with these and a way to disable them like LastPass.

**Comment by nul800sebastiaan** [comment]
I think this is fine, but I'm also a bit scared that we'll then have to start doing this dozens of other form-fill plugins..

Anyway, we'll see if it gets to that, let's start with LastPass! 👍

I've marked this as "Up for grabs" so that you or someone else coming along could create a pull request for it.

**Comment by bjarnef** [comment]
@nul800sebastiaan yes, there might be issues with other Password Managers as well. :)

**Comment by nul800sebastiaan** [comment]
Fixed in https://github.com/umbraco/Umbraco-CMS/pull/4153
