### ISSUE TITLE
v8: Richtext editor is missing icons in settings

### ISSUE THREAD

**Issue by bjarnef** [umbraco/Umbraco-CMS#4093]
In **v8** it seems that Richtext editor no longer list the icons next to the checkboxes in settings as it did in v7. Only a few of the icons are available.

![image](https://user-images.githubusercontent.com/2919859/51212884-e518df00-1919-11e9-8d60-564ee618049c.png)

![image](https://user-images.githubusercontent.com/2919859/51212903-f82baf00-1919-11e9-8037-4a3d58a64a43.png)

In **v7** it looks like this:

![image](https://user-images.githubusercontent.com/2919859/51212947-18f40480-191a-11e9-9135-e1c5eecb9e15.png)

![image](https://user-images.githubusercontent.com/2919859/51213016-3fb23b00-191a-11e9-8355-24254d56f70d.png)

**Comment by dawoe** [comment]
Hi @bjarnef 

Thanks for reporting this issue. Seems like a bug to me

Dave [Community Pull Request team](https://umbraco.com/blog/introducing-the-new-cpr-team/)

**Comment by bjarnef** [comment]
Hi @dawoe 

Then font icons was added here.
https://github.com/umbraco/Umbraco-CMS/commit/0bfc5f1272edeef0a19b608823ac8c6f04a8312a#diff-6fd9275921c82d47dedaa5e34ebb1fbe

Maybe the image icons also should be removed in v8 (if these haven't been removed). It doesn't seems TinyMCE use image icons anymore only font icons in the skin file.

As I remember the icons are based on the value of `frontendCommand` attribute value in the config.
https://github.com/umbraco/Umbraco-CMS/blob/0bfc5f1272edeef0a19b608823ac8c6f04a8312a/src/Umbraco.Web.UI/config/tinyMceConfig.Release.config#L10

https://github.com/umbraco/Umbraco-CMS/blob/0bfc5f1272edeef0a19b608823ac8c6f04a8312a/src/Umbraco.Web.UI.Client/src/views/propertyeditors/rte/rte.prevalues.controller.js#L27-L33

**Comment by bjarnef** [comment]
Ooh, the `tinyMceConfig.config` is a lot different in v8.
I guess there is some part of the javascript which might need to be changed then.
https://github.com/umbraco/Umbraco-CMS/blob/temp8/src/Umbraco.Web.UI/config/tinyMceConfig.config

**Comment by bjarnef** [comment]
Yes, it still use the same approach
https://github.com/umbraco/Umbraco-CMS/blob/temp8/src/Umbraco.Web.UI.Client/src/views/propertyeditors/rte/rte.prevalues.controller.js#L30-L36

It should probably just use value of `alias` attribute on `<command>` element instead.

**Comment by nul800sebastiaan** [comment]
Fixed in https://github.com/umbraco/Umbraco-CMS/pull/4152
