### ISSUE TITLE
v8 Macro picker is broken because EntityController no longer supports dynamic post filtering

### ISSUE THREAD

**Issue by Shazwazza** [umbraco/Umbraco-CMS#4095]
Reproduction
------------

Try to use the Macro picker in v8

### Specifics

There is a couple of  //fixme in the EntityController which currently throws NotImplementedException because it was relying on dynamic linq which we no longer support. This is the only place where that logic is required, so instead, we should have the macro picker use a new endpoint for it's own needs, or similar.

**Comment by bergmania** [comment]
PR: https://github.com/umbraco/Umbraco-CMS/pull/4210
