### ISSUE TITLE
v8 - Variant Content picker doesn't pick correct variant

### ISSUE THREAD

**Issue by mclausen** [umbraco/Umbraco-CMS#4103]
Reproduction
------------
1. Create a document type with a content picker and enable variants
2. Create Document and Add content to both variants

3. Selecting Danish variation
![1](https://user-images.githubusercontent.com/3600782/51259801-2c03e480-19ad-11e9-9925-cd02c68cbd37.PNG)

4. With English content
![2](https://user-images.githubusercontent.com/3600782/51259926-6c636280-19ad-11e9-907a-29aa0efeefb1.PNG)

5. And i end up with the following result.
![3](https://user-images.githubusercontent.com/3600782/51259996-9157d580-19ad-11e9-8cee-2c75eb5f2628.PNG)

I get the same result if i select my English version for the English variant.

Expectation
------------
I expected to have the content that i selected

**Comment by mclausen** [comment]
Good point @zpqrtbnk, though it can lead to some confusion for the uninitiated. 

The confusion part lies in that is not the same document that you pick on the list that gets displayed on the content, and the list you get has a language selection dropbox in the top as well, thus making it perceived to be able to choose a variation :neutral_face:

I am obvious a bit out of my element here :innocent: 

A possible solution could be, to remove the language variation drop down, and have the picker say  
"<Title in the default language>"?

**Comment by zpqrtbnk** [comment]
the picker lets you browse the tree and as such, lets you see the tree in different languages

it can indeed lead to confusion - but generally speaking, ppl will have to understand the concept that there is only 1 unique document (with different cultures) and not a "thing" per culture - this impacts various other areas of the CMS.

**Comment by mclausen** [comment]
Gotcha. I think that the issue can be closed, and the idea put in the drawer for now 😄
