### ISSUE TITLE
Editors cannot create any type of content (any docType)

### ISSUE THREAD

**Issue by vonbv** [umbraco/Umbraco-CMS#4110]
After upgrading to **v7.13.0** all our editors cannot create any content. Our editors only have access to sections "Content" and "Media". The only way they can edit content is if we grant them access to the Settings section. 

We thought it could be a caching issue of some sort, so we grant them admin access (to all sections). Editors, as expected, were able to create content. We then removed the admin access and the issue occur again.

We add the Settings section to their access and editors were able to create content again. When we remove the Settings section from their access, they are not able to create content (of any type).

**Comment by kjac** [comment]
Hi 😊 this and a few other things were fixed in 7.13.1 - see https://our.umbraco.com/download/releases//7131

**Comment by vonbv** [comment]
Thank you @kjac

**Comment by dawoe** [comment]
Hi @vonbv 

As @kjac already mentioned this is already fixed in 7.13.1. So a upgrade will fix the issue.

So I will close this issue.

Dave [Community Pull Request team](https://umbraco.com/blog/introducing-the-new-cpr-team/)

**Comment by vonbv** [comment]
This is to confirm that the issue is fixed on 7.13.1.
