### ISSUE TITLE
V7 Media Service Save method not updating with new value of properties

### ISSUE THREAD

**Issue by bielu** [umbraco/Umbraco-CMS#4118]
I am hitting the same problem, which someone already describes on Umbraco forum:
https://our.umbraco.com/forum/extending-umbraco-and-using-the-api/86958-media-service-save-method-not-updating-with-new-image-cropper-sizes I can reproduce that on clean Umbraco 7.13. When  I am using the save button in backoffice, it is working fine.

Reproduction
------------
Example Code:
		
		public static void RegenerateTags()
        {
            var contentService = UmbracoContext.Current.Application.Services.ContentService;
            var mediaService = UmbracoContext.Current.Application.Services.MediaService;

            var umbracoHelper = new UmbracoHelper(UmbracoContext.Current);
            var items =  umbracoHelper.TypedContentAtRoot().SelectMany(x => x.DescendantsOrSelf());
            foreach (var item in items)
            {
                IContent content = contentService.GetById(item.Id);
                if (content.ContentType.Alias == InstallationServices.ModelTypeAlias )
                {
                    continue;
                }
                var homeIpublishedContent = umbracoHelper.TypedContent(content.Id).Site();
                var guidHome = homeIpublishedContent.GetKey();
                content.AssignTagsToSite(guidHome.ToString());
                contentService.SaveAndPublishWithStatus(content);
            }
            var mediaItems =  umbracoHelper.TypedMediaAtRoot().SelectMany(x => x.DescendantsOrSelf());
            foreach (var item in mediaItems)
            {
                IMedia content = mediaService.GetById(item.Id);
                var path = content.Path.Split(new string[] { "," }, StringSplitOptions.RemoveEmptyEntries);
                var mediaGuid =   umbracoHelper.TypedMedia(path[1]).GetKey();
                content.AssignTagsToSite(mediaGuid.ToString());
                mediaService.Save(content);
                mediaService.RebuildXmlStructures(content.Id);
                contentService.Publish((IContent) content);

            }
           
    
        }

		public static void AssignTagsToSite(this IContentBase content, string guidHome)
        {
            var tagsproperty =
                content.Properties.FirstOrDefault(x => x.PropertyType.PropertyEditorAlias == "Umbraco.Tags");

            if (tagsproperty != null)
            {
                var tagssupport = tagsproperty.TagSupport;
                if (tagssupport != null)
                {
                    var tags = tagssupport.Tags;

                    var newvalue = new List<Tuple<string, string>>();
                    if (tags != null)
                    {

                        foreach (var t in tags)
                        {
                            //Don't modify if we already have a group with culture appended (events)
                            if (t.Item2.Contains("-"))
                            {
                                continue;
                            }

                            newvalue.Add(new Tuple<string, string>(t.Item1, t.Item2 + "-" + guidHome));
                        }

                        tagssupport.Tags = newvalue;

                        content.SetValue(() => tagssupport);

                    }
                }

            }
        }
    }

### Bug summary

I think the different behaviour of the save button and save method from Media Service is a bug, especially when touching way of changing dynamic values in properties.

### Specifics
Umbraco 7.13.0
Browser: Chrome Version 71.0.3578.98 (Official Build) (64-bit)
I didn't check different browser, a bug is not browser related.

### Steps to reproduce

1) Choose Media Item
2) Change Media Item property from code
3) Save Media item using MediaService
### Expected result

After that 3 steps I would Expect updated when I am getting media item after save I will have access to changed earlier value of property.

### Actual result

For now, Umbraco returns the previous value of Media property, which is that before a change from code.

**Comment by nul800sebastiaan** [comment]
I've been able to sort-of reproduce, at first I couldn't reproduce it, I made a template:

```
@inherits UmbracoTemplatePage
@{
    Layout = null;
    
    if (Request.QueryString["updateContent"] == "1")
    {
        var mediaService = UmbracoContext.Current.Application.Services.MediaService;
        var mediaItem = mediaService.GetById(1165);
        mediaItem.SetValue("someText", Request.QueryString["content"]);
        mediaService.Save(mediaItem);
    }

    var umbracoHelper = new UmbracoHelper(UmbracoContext.Current);
    var updatedMediaItem = umbracoHelper.TypedMedia(1165);

    var test = updatedMediaItem.GetPropertyValue<string>("someText");
}

<h1>Updated Item: @test</h1>
```

And the result:

![4118](https://user-images.githubusercontent.com/304656/51548099-ebeaa900-1e67-11e9-947f-a15eca2fd855.gif)


However, when I put similar code in a `ApplicationEventHandler` it doesn't work, probably because not all the event handlers have been wired up yet. I would bet that you're firing your code from a `ApplicationEventHandler`?

If so, then this is a big anti-pattern, you shouldn't do intensive processing on startup, I would recommend you look into using Hangfire as a task scheduler that can do these things for you in the background, on a timer.

For further questions make sure to post on the forum.

**Comment by hemraker** [comment]
PING! @nul800sebastiaan taking the above comment in to account, do you still see this as a big anti pattern? The method is executed on the .Saving event and not processed at startup.
Not really sure Hangfire or similar would help in this case 😏

**Comment by nul800sebastiaan** [comment]
I am not overly familiar with the technicalities of startup handlers and how they hook into stuff and when things then run exactly. What I can tell you is that the code I showed above works, so I would expect the invocation of a method (that wasn't registered in a startup handler) through something like HangFire would also work.

**Comment by hemraker** [comment]
Ok, are there any examples of how to do this with an event fired in Umbraco?

Still not sure how hangfire would solve that 🤔

MediaService.Saving event -> Hangfire -> Umbraco Surface/Api Controller ?

**Comment by nul800sebastiaan** [comment]
Duh.. I see what you mean! 

I'll have to look into it, will report back.

**Comment by nul800sebastiaan** [comment]
Right-o, I think I see what's going on now and the bad news is: I don't think there's a solution for this. You might be able to hack it but you are going to run into circular issues (Saving causes a Publish causes a Save, etc.). 

I used the following code sample and my first `var test` returns an empty string. I can't remember exactly why this happens (I'll ask) but AFAIK there's a limitation when using startup eventhandlers.

```
        protected override void ApplicationStarted(UmbracoApplicationBase umbracoApplication, ApplicationContext applicationContext)
        {
            MediaService.Saving += MediaService_Saving;
        }

        private void MediaService_Saving(IMediaService sender, Umbraco.Core.Events.SaveEventArgs<Umbraco.Core.Models.IMedia> e)
        {
            var mediaService = UmbracoContext.Current.Application.Services.MediaService;
            var mediaItem = mediaService.GetById(75475);
            mediaItem.SetValue("someText", DateTime.Now.ToString());

            mediaService.Save(mediaItem, raiseEvents: false);
            var umbracoHelper = new UmbracoHelper(UmbracoContext.Current);

            var updatedMediaItem = umbracoHelper.TypedMedia(75475);
            var test = updatedMediaItem.GetPropertyValue<string>("someText");
            
            // But why do this, you still have access to the media item:
            var test2 = mediaItem.GetValue<string>("someText");
	}
```

I don't understand your code very well, so maybe it's just an option to store the values you set on the media item in a local variable and also set the same values on the content item, or the other way around?

Alternatively, if you don't require the tags to be perfectly correct the second you hit "Save" maybe run a scheduled task every minute. Maybe in the EventHandler store the Ids of the items that need processing? The added benefit is that you don't slow down the saving/publishing process, the scheduled tasks can happen on the background.

**Comment by nul800sebastiaan** [comment]
Yep, so I asked: 

> the publishing cache refreshes only when events are raised, and events are not raised until the scope completes, ie the saving is completed - the Saving event trigger too soon, nothing has been saved yet, the cache is not aware of any change

In other words, what you're trying to do is not supported and you'll need to find a different way to achieve your goals.
