### ISSUE TITLE
Saved content overridden by published content

### ISSUE THREAD

**Issue by RobertCopilau** [umbraco/Umbraco-CMS#4119]
Replicate:
Create a node with some properties, fill them up and publish.
Update the node and save it
Refresh page, saved content will be replaced with the previous published content
https://www.useloom.com/share/a09793f0bcc5420b9e9c655ba9086cfd

**Comment by bergmania** [comment]
PR: https://github.com/umbraco/Umbraco-CMS/pull/4137

**Comment by zpqrtbnk** [comment]
reviewing - i'd rather we understand why null is not properly handled as that may indicate other issues - looking into it

**Comment by bergmania** [comment]
@zpqrtbnk, I think it is because numbers etc. are saved in a textbox in html, and we can't handle "" as a int.
