### ISSUE TITLE
Variants - "This document is published but its url cannot be routed"

### ISSUE THREAD

**Issue by RobertCopilau** [umbraco/Umbraco-CMS#4121]
|── Home/
│   ├── Page Eng -> has link
│   ├── Page Dk -> This document is published but its url cannot be routed

**Comment by madsoulswe** [comment]
I asked @zpqrtbnk about this and you need to bind domains for it to work. 
Will this be "fixed"/solved? =)

**Comment by RobertCopilau** [comment]
Hey Dennis, I also had a chat with Stephan and that's the intended behavior.
It was a mistake on my part so I will be closing this issue as there is nothing to fix.
