### ISSUE TITLE
v8 - Spelling mistakes in Umbraco.Core

### ISSUE THREAD

**Issue by readingdancer** [umbraco/Umbraco-CMS#4125]
There are a lot of spelling mistakes throughout the Umbraco source code ( the majority are just mistakes in the code comments ) these can make the code harder to read and also means that Intelisense used in Visual Studio often returns help information with spelling mistakes which doesn't look great.

This ticket is purely related to the Umbraco.Core project, I intend to raise further tickets for the other projects when I have had the time to go through them.

**Comment by readingdancer** [comment]
Please use look at this pull request: https://github.com/umbraco/Umbraco-CMS/pull/4130

**Comment by nul800sebastiaan** [comment]
Fixed in https://github.com/umbraco/Umbraco-CMS/pull/4130
