### ISSUE TITLE
Integrate RJP Multi URL Picker into backoffice

### ISSUE THREAD

**Issue by nul800sebastiaan** [umbraco/Umbraco-CMS#4126]
<p>Issue imported from old issue tracker: <a href="https://issues.umbraco.org/issue/U4-8930">U4-8930</a>

**Comment by nul800sebastiaan** [comment]
PR: https://github.com/umbraco/Umbraco-CMS/pull/2323

**Comment by rasmusjp** [comment]
Duplicate of #2967 :-)

BTW. I also have a (rather old) branch where the package is upgraded to v8 https://github.com/rasmusjp/umbraco-multi-url-picker/tree/dev-v3, should make it easier to migrate it.

**Comment by nul800sebastiaan** [comment]
Ah cool, I'll update that one instead.

Sweet, I was trying to merge it to 8 but that was a bit harder than anticipated. I can have a look at that branch too, cool.

**Comment by nul800sebastiaan** [comment]
The v8 branch definitely won't work, `PropertyEditor`s don't exists any more, it's all `DataEditor`s now :-)

**Comment by rasmusjp** [comment]
Yeah, should be updated to `DataEditor`s in my repo (see https://github.com/rasmusjp/umbraco-multi-url-picker/blob/dev-v3/src/RJP.MultiUrlPicker/PropertyEditors/MultiUrlPickerDataEditor.cs).

Let me know if I should have a look at it with the latest v8 code.

BTW. you've added the wrong release tag in #2967 :-)

**Comment by nul800sebastiaan** [comment]
Whoops, thanks!

Yes, if you have some time it would be great if you could give a v8 version a retry!

**Comment by rasmusjp** [comment]
np.

I'll give it a go with the latest v8
