### ISSUE TITLE
TypedContent method doesn't support Udi[]

### ISSUE THREAD

**Issue by skartknet** [umbraco/Umbraco-CMS#4131]
The TypedContent(params object[] ids) doesn't work with Udi[] not there's an overload that supports Udi[];

Reproduction
------------

Pass an array of Uids to retrieve the PublishedContent:
`var selectedNodes =  helper.TypedContent(nodeIds.Select(id=> Udi.Parse(id)).ToArray());`

nodeIds is an array of Udi as strings.

### Expected result

Array of IPublishedContent

### Actual result

Empty Array

I have digged into the source code and I haven't found an overload that accepts Udi[]. The TypedContent(params object[] ids) overload uses a `ConvertIdsObjectToGuids` method that could be used to implement this functionality but it looks like it only works for Guids.

Can that overload be improved allowing Uids? Or even better, could we have a TypedContent(params Uid[] ids) method?

I can do a PR myself but I'd like to know which approach would be the right one.

**Comment by nul800sebastiaan** [comment]
If you call it Udi and not Uid then we'd be happy to have an overload accepting Udi[] 😁 

I've marked this as "Up for grabs" so that you or someone else coming along could create a pull request for it.

**Comment by nul800sebastiaan** [comment]
Fixed in https://github.com/umbraco/Umbraco-CMS/pull/4135
