### ISSUE TITLE
Richtext Editor never dirty again after saving

### ISSUE THREAD

**Issue by marcinbigoraj** [umbraco/Umbraco-CMS#4140]
### Bug summary

When content contains Richtext Editor, after clicking save, whole form becomes pristine, but any further changes in RTE won't make the form dirty anymore.

### Specifics

Umbraco version: 7.13.1
Browser:  Chrome 71.0.3578.98, but bug should occur on all browsers

### Steps to reproduce

1. Create _Document Type_ containing _Richtext Editor_
2. Create _Content_ of this _Document Type_ (save with empty value)
3. Make any change in RTE (e.g. type "a")
4. Save the _Content_
5. Make second change in RTE (e.g. add another "a")
6. Navigate to any other page/content

### Expected result

Warning "You have unsaved changes" should be displayed.

### Actual result

No warning is present and user is instantly navigated to other page/content. User loses unsaved changes.

**Comment by nul800sebastiaan** [comment]
Fixed in https://github.com/umbraco/Umbraco-CMS/pull/4141 and then a little differently in 
https://github.com/umbraco/Umbraco-CMS/pull/4492
