### ISSUE TITLE
Only allow moving items from recycle bin to parents that allow children of this type

### ISSUE THREAD

**Issue by bjarnef** [umbraco/Umbraco-CMS#4142]
Edit: note, this turned into a feature request with this comment: https://github.com/umbraco/Umbraco-CMS/issues/4142#issuecomment-455871431

In this PR https://github.com/umbraco/Umbraco-CMS/pull/2687 it added the "Restore" action to nodes in recycle bin.

However if I move a node to recycle bin in default starter kit, e.g. an blog post it wants to restore under "Blog" node, but if the blog node also is allowed under home node, am I not able to move this to child node of home node. Instead I would have to restore (under blog node) and then move the node under home node.
Furthermore if the paren node "Blog" node also is recycle bin it can't restore.

However it seems that you can move the nodes from the recycle bin listview with bulk actions.

I think it still should be possible to move nodes from recycle bin to nodes where these are allowed as child node.

**Comment by kjac** [comment]
Pretty sure I did a lot of fixing in this area. What version are you running?

**Comment by kjac** [comment]
@bjarnef for content it should be in 7.13:

![image](https://user-images.githubusercontent.com/7405322/51426486-dbc69580-1beb-11e9-99e1-c1ec8e77f61a.png)

See also #3772.

I'm pretty sure it was already there for media before 7.13, but 7.14 brings some improvements to it. See #3914.

**Comment by bjarnef** [comment]
@kjac ahh sorry, I was checking new features and bug fixes in different minor version from v7.10 to v7.13 .. but was looking at v7.11 where the restore action was added and move action removed.
https://our.umbraco.com/download/releases//7110

I just checked in v7.13.1 and the move action is back! 😁 

One thing that would be great for move action for a deleted node (or move in general) that you only can select the parent node (or root) under which the node are allowed to be created, e.g. here I can select any node in the tree, but the "My Blog Post" node is only allowed to be created under "Blog" node.

![image](https://user-images.githubusercontent.com/2919859/51440572-e73bbe80-1cc8-11e9-9afb-136757f50f6b.png)

**Comment by nul800sebastiaan** [comment]
That's a rather large feature request, but it could be cool if the move would show you faded tree items and a "stop sign" icon when you're not allowed to move things to that parent. I don't know how much work that would be and if it's worth it. It's a good one to investigate the feasibility of though.

I've marked this as "Up for grabs" so that you or someone else coming along could create a pull request for it.

**Comment by nul800sebastiaan** [comment]
This issue has been in the `up for grabs` state for quite a while now and it seems nobody is ready to pick this one up.

For now we'll close this issue to prevent the list of `up for grabs` from becoming very stale. We're happy to re-open it if someone still thinks it's good to work on this.

If anyone is about to pick this issue up to fix it, make sure to test first if you can reproduce the problem in the latest version before you start to work on it.

Thanks!
Sebastiaan on behalf of Umbraco HQ.
