### ISSUE TITLE
Copy document type improvement

### ISSUE THREAD

**Issue by drummerboy46** [umbraco/Umbraco-CMS#4145]
This has been a particular annoyance to me...

When you select "copy" from the document type tree menu it only provides the options to copy the type to the root or a sub-folder.

Can this be changed for the copy to appear by default in the same place within a doctype parent/child relationship rather than just the root or a sub-folder?

My workaround for this so far has been to modify the subsequent output from uSync and then re-importing the doctype....a pretty sub-optimal experience!

**Comment by drummerboy46** [comment]
Here's what i'm experiencing in pics...
![capture2](https://user-images.githubusercontent.com/6703035/51480641-6bee1180-1d89-11e9-8ce7-e35032a8827f.PNG)
![capture3](https://user-images.githubusercontent.com/6703035/51480643-6db7d500-1d89-11e9-8ad2-9119ba9c96b2.PNG)
![capture4](https://user-images.githubusercontent.com/6703035/51480644-6ee90200-1d89-11e9-8f71-4e37924741b3.PNG)

I have two choices click on 'document types' or a pre-defined folder. If I don't want it in the folder the other choice would be for it to appear in the same parent/child relationship as the item I copied. But when I click on 'document types' the item ALWAYS ends up in the root of the tree.

**Comment by kjac** [comment]
Hi again. You can't copy a document type underneath another document type. Too many things can go wrong with that... Duplicate properties and tabs, circular references, ...

I can see it's a bit late to tell you this, but you should consider using compositions instead of inheritance. It's much more powerful and does not rely on structure.

**Comment by drummerboy46** [comment]
This is our main site, agency built originally. They used a mixture of inheritance and compositions.  I understand there's been a lot talk over dumping inheritance altogether, but it has remained.

I've not had any issues with re-importing the doctype into the same place in a hierarchy as long as the name is different and it has a new unique GUID. This is something I do manually using uSync.

Maybe in our next build we can insist on compositions only!

**Comment by kjac** [comment]
@drummerboy46 so long as you keep on the straight and narrow path you can do what you're doing with little or no risk 👍 but soon as you move off said path, there are all kinds of things that can go horribly wrong. 

If the document types you're copying aren't terribly complex you could also opt for creating them explicitly as children to save yourself the hassle of "uSync'ing" them into place.

**Comment by nul800sebastiaan** [comment]
Hey @drummerboy46 - as Kenn noted this operation is dangerous and as such we have no plans to build in support for this at this time. :)
