### ISSUE TITLE
v8 - Spelling, typos and general cleanup in the Umbraco.Web project

### ISSUE THREAD

**Issue by readingdancer** [umbraco/Umbraco-CMS#4147]
There are spelling mistakes, typos and ambiguous abbreviations throughout the solution, this ticket is just for the Umbraco.Web project.

This will improve:
- the code readability 
- the intellisense used by all developers within Visual Studio
- Error messages
- Log messages
- Make the TODO comments consistent so they show up within the Visual Studio Task List. e.g. 
`// TODO:`

**Comment by nul800sebastiaan** [comment]
Fixed in https://github.com/umbraco/Umbraco-CMS/pull/4148
