### ISSUE TITLE
v8: Rich text editor styles preview should use normal line height

### ISSUE THREAD

**Issue by bjarnef** [umbraco/Umbraco-CMS#4149]
In v8 when creating a rich text editor stylesheets, e.g. the following:

Name: Heading
Selector: h2
Styles: font-size: 40px;

Then it looks like this, because it inherits the line-height: 20px; from body.

![image](https://user-images.githubusercontent.com/2919859/51417748-cfa4ee80-1b7f-11e9-868c-b8529df7ae17.png)

It should probably have a default line-height here. E.g. add a class `umb-rte-styles-preview`:
```
.umb-rte-styles-preview {
     line-height: normal;
}
```
It then looks much nicer. Of course it the developer add a line-height in the styles, it is added as inline styles and overwrite this default style.

![image](https://user-images.githubusercontent.com/2919859/51417835-4a6e0980-1b80-11e9-8bad-c8b10db47a22.png)

![image](https://user-images.githubusercontent.com/2919859/51418046-8190ea80-1b81-11e9-9ec0-e88a3ceacf51.png)

Alternatively it can use line-height `100%` or `1`, but I think `normal` is preferred since it is default in browser, where the line-height is a bit greater than the font-size, but it probably vary between browsers somewhere between 100% / 1.0 and 150% / 1.5

**Comment by kjac** [comment]
@bjarnef good catch! Are you creating a PR for it or shall I whip one up?

**Comment by bjarnef** [comment]
@kjac you are welcome to have a look at it.
I think this would be a great basic style to ensure it doesn`t inherit styles from body etc.

```
.umb-rte-styles-preview {
     line-height: normal;
}
```

**Comment by kjac** [comment]
👍 

I agree, `normal` works just fine. I'll have a look at it.

**Comment by nul800sebastiaan** [comment]
Fixed in https://github.com/umbraco/Umbraco-CMS/pull/4161
