### ISSUE TITLE
v8: Create folder under stylesheets

### ISSUE THREAD

**Issue by bjarnef** [umbraco/Umbraco-CMS#4150]
There changes made in v8 under stylesheets are really cool and I noticed it now also are able to show subfolders created on file system.

![image](https://user-images.githubusercontent.com/2919859/51418257-c8cbab00-1b82-11e9-86a8-20cf8bf5a1e2.png)

However one feature I think is missing is the option to create a folder under stylesheets from backoffice, just like you can under scripts folder.

![image](https://user-images.githubusercontent.com/2919859/51418298-f9abe000-1b82-11e9-98c3-5f0c471a4984.png)

![image](https://user-images.githubusercontent.com/2919859/51418308-0597a200-1b83-11e9-8d8d-5f4a0b031a08.png)

**Comment by bjarnef** [comment]
If I remember correct it is also possible from backoffice to rename folders in scripts folders, but I am not sure if it is possible to rename folders under stylesheets (I haven't checked).

**Comment by kjac** [comment]
@bjarnef gotcha. I guess I just figured the stylesheets tree was largely unused for anything but adding styles to the RTE.

V7 doesn't have folders in the stylesheets tree. I have no idea if there has ever been a request for them. @nul800sebastiaan might be able to answer that part. If not... then maybe we shouldn't do this until it's requested for a concrete need?

**Comment by bjarnef** [comment]
@kjac what I always have loved about Umbraco is its flexibility and it doesn't limit the developer. Furthermore it is great for both newbies and experts. When I learned about Umbraco ~10 years ago I liked I could create the website from backoffice without opening Visual Studio or other code editors.
One thing I was missing though was the ability to structure stylesheets into folders. Previously I think og you structured CSS files into folders, it only listed CSS files on root level in backoffice. But for javascript files it also listed files in subfolders in backoffice. Later it was also possible to create folders under scripts from backoffice. Furthermore CSS files in subfolders are loaded in backoffice at least in v8. However I still feel we need to be able to create subfolders under stylesheets from backoffice - both for consistency and not limiting the developer to put all css files at root level.

Off topic it would also be great if developers could manage editors from backoffice similar to LeBlender (maybe a light/basic version of something like LeBlender). At the moment developers have to open a code editor to mangage grid editors which is basic stuff og many Umbraco websites nowadays with "The Grid". Might be a task for Umbraco v8.1?
Mostly thinking on newbies here.

**Comment by kjac** [comment]
Well as you mention it's already there for scripts, so adding it for stylesheets shouldn't be too much of a hurdle really. I think it's something HQ should weigh in on before we start hacking though...

**Comment by nul800sebastiaan** [comment]
I think it's a great idea, however we don't want to add any more legacy code to v7 (the create dialog for stylesheets in v7 is still webforms) so it would have to go in v8 instead. 👍

**Comment by bjarnef** [comment]
@nul800sebastiaan it's fine with me that it only is available in v8, where the stylesheets have got an UX overhaul anyway 😁

**Comment by kjac** [comment]
Cool. I can have a look at it one of these days 😄

**Comment by kjac** [comment]
PR in #4170

**Comment by nul800sebastiaan** [comment]
Fixed in https://github.com/umbraco/Umbraco-CMS/pull/4170
