### ISSUE TITLE
Unused language file dictionary keys in V8

### ISSUE THREAD

**Issue by callumbwhyte** [umbraco/Umbraco-CMS#4151]
While looking through the V8 codebase I found a handful of language file dictionary items that seemed to be unused / not references. I figured there may be more instances of this, including keys that exist in some files but not others, so set about find a way to identify all of them.

I have written a Powershell script that checks over the Umbraco source code for unused dictionary items. For reference I have created a Github Gist https://gist.github.com/callumbwhyte/583d56705e8ed10dd9413970b83e6b47. In short, the script does this:

1. Loads the XML language files
2. Builds a list of all dictionary key paths from the files
3. Searches over the codebase for instances of the key paths in various formats:
   - `area/key` <- used in C# code
   - `area_key` <- used in front-end code
   - If the area is "general" it also does some more detailed checks because the front-end services default to looking in the "general" area for a value if a key is provided without an area.
     - `@key` <- inline translation of specific properties on the front-end
     - `localize("key")` <- calls to the `localizationService` on the front-end
     - `localization key="key"` <- `<localization>` directive on the front-end

As of the current state in the `temp8` branch I have identified **117** keys that are not referenced in the codebase and can be removed.

This is also likely an issue present in V7, but deleting keys does make this a potential _(albeit minor)_ breaking change – while keys aren't currently being used in the Umbraco Core they may be used by packages...

V8 seems the perfect opportunity to clear these out, I'd be interested to get opinions on doing this for V7 too.

**Comment by nul800sebastiaan** [comment]
Hey @callumbwhyte - we're working on a (even more advanced) de-duplicator at the moment, our very own @elit0451 is working on this and we'll use that project once the time is right. Thanks for the suggestion!
