### ISSUE TITLE
v8: Remove text decoration on node icons in listview

### ISSUE THREAD

**Issue by bjarnef** [umbraco/Umbraco-CMS#4157]
In v8 it seems the node icons in listview grid layout also has text decoration on hover.

![image](https://user-images.githubusercontent.com/2919859/51440830-469ace00-1ccb-11e9-92cc-da4485309cd3.png)

Maybe the heading (node name) should be wrapped inside a span, so only this element get the text decoration.

**Comment by nul800sebastiaan** [comment]
Good point, thanks! 

I've marked this as "Up for grabs" so that you or someone else coming along could create a pull request for it.

**Comment by kjac** [comment]
Well if no-one else is fixing it, I am 😄 PR in #4247

**Comment by nul800sebastiaan** [comment]
Fixed in https://github.com/umbraco/Umbraco-CMS/pull/4247
