### ISSUE TITLE
v8: Fix deleting created package

### ISSUE THREAD

**Issue by bjarnef** [umbraco/Umbraco-CMS#4162]
In the new package in v8 it list created packages similar to language, so the created packages are not listed as tree nodes.

The delete confirm dialog is similar to the language confirm dialog, but unlike languages delete is doesn't set the delete button state https://github.com/umbraco/Umbraco-CMS/pull/4108.

Furthermore the legacy dialog on tree node action still exists.

**Comment by nul800sebastiaan** [comment]
Fixed in https://github.com/umbraco/Umbraco-CMS/pull/4163
