### ISSUE TITLE
Add some ids to the disabled health checks

### ISSUE THREAD

**Issue by prjseal** [umbraco/Umbraco-CMS#4174]
Now that we have our first health check which is being promoted from Our.Umbraco.HealthChecks to Umbraco core see #4173 , it would be good to add the id of the one in the community project to the disabled health checks list in the HealtChecks.config file that ships with core. This will prevent the check being duplicated. 

Our.Umbraco.HealthChecks supports versions 7.5 to latest, but some checks don't get introduced to Umbraco core until 7.13, such as the Hsts Check. 

So by adding the ids of any of these duplicated checks it means people can use the core checks and community checks together without any duplication.

As the ids of these checks never change, it is safe to leave them in the config file and it is also useful to see as an example of disabling checks.

PR to follow

**Comment by ronaldbarendse** [comment]
As commented on PR #4175, this can (and should) be handled in the community packages by conditionally removing health checks from the `HealthCheckResolver`.

The only downside would be that updating Umbraco (and introducing new checks copied from the community package) without updating the community package itself would still show duplicated checks.  I don't think this will be a big issue, as it's always possible to disable the duplicate checks with a simple configuration change (in `config\HealthChecks.config`).

**Comment by nul800sebastiaan** [comment]
Fixed in https://github.com/umbraco/Umbraco-CMS/pull/4175

**Comment by ronaldbarendse** [comment]
Just to give this issue some context: the duplicated health checks (moved from a community package to core) are now removed by Umbraco within the `WebBootManager` based on the full name of the type, e.g. `Our.Umbraco.HealthChecks.Checks.Security.HstsCheck`.

This way, only updating Umbraco to a newer version (including the new checks) automatically disables any duplicate (assuming the community package is installed). Updating the package or manually adding IDs to disable in the config file is therefore not needed.
