### ISSUE TITLE
v8: Edit embed grid editor

### ISSUE THREAD

**Issue by bjarnef** [umbraco/Umbraco-CMS#4178]
It would be great if it was possible to edit the embed grid editor. I the moment you have to remove it and insert it again. Often the embed preview is a video or something else interactive, e.g. YouTube and Issuu.
So it should probably have an overlay which is clickable similar to this implemented here:
https://github.com/umbraco/Umbraco-CMS/pull/1621

@madsrasmussen suggested in the original issue https://issues.umbraco.org/issue/U4-8507 that is should store an object with all the entered information and the embed iframe, e.g. so you can adjust width/height or other parameters.

**Comment by nul800sebastiaan** [comment]
Unfortunately we're in the wrap-up phase of v8 and we can't do any more changes to the Grid data model. We'll have to reconsider this feature request when working on the elusive "Grid v2" that's coming up for the future. I've put it on the list of ideas to consider for the future!

**Comment by nul800sebastiaan** [comment]
Fixed in https://github.com/umbraco/Umbraco-CMS/pull/4899
