### ISSUE TITLE
Folder icons in media picker contain file type indicator

### ISSUE THREAD

**Issue by jamescoxhead** [umbraco/Umbraco-CMS#4180]
When browsing through the media picker in 7.13, the folder icons attempt to show the file type indicator:

![media picker](https://user-images.githubusercontent.com/6759305/51527224-f0916c00-1e2b-11e9-81e2-989faf496e3f.png)

Reproduction
------------

### Specifics
I've reproduced this in 7.13.0 and 7.13.1 (clean install and upgrade). The folders appear fine in versions prior to 7.13.

### Steps to reproduce

1. Change the icon colour for the default folder media type to something other than grey - the file type indicator is the same shade of grey as the icon.
2. Add folders to the media library
3. Add a media picker to a document type
4. Browse through the media picker - the file type indicator should appear over the folders.

### Expected result

Folders shouldn't show a file type indicator.

**Comment by bjarnef** [comment]
I believe this was fixed in this commit https://github.com/umbraco/Umbraco-CMS/commit/1213551ca951db86acc0fda3f40b0a1d4efad4a5

**Comment by kjac** [comment]
@bjarnef looks about right 👍

**Comment by nul800sebastiaan** [comment]
It was :) Will be available in 7.14 (or 7.13.2, not sure yet).
