### ISSUE TITLE
V8: Loosing context after editing DocType from content

### ISSUE THREAD

**Issue by sofietoft** [umbraco/Umbraco-CMS#4181]
When editing a Document Type from the _Info_ tab on a content node, no tab i selected one I click 'Save and close' on the Document Type.
I'm still on the content node, but none of the tabs are selected, and I'm just seeing a "blank" page:

![loosing-context](https://user-images.githubusercontent.com/24529086/51528929-fdb45800-1e37-11e9-91fb-a994ee8b6624.png)

In order to move on, I need to re-select the tab I want to continue editing.

Reproduce:
* Open a content node in the Content section
* Go to the _Info_ tab
* Click 'Open' to edit Document Type
* Make a small change to anything
* Click 'Save and close'

I expect to be 'sent' back to the _Info_ of _Content_ tab, so I can continue my work.
Instead I'm just presented with a blank page.

**Comment by kjac** [comment]
Ah. I may possibly have had something to do with this. I'll have a look 👍

**Comment by kjac** [comment]
PR in #4186

**Comment by nul800sebastiaan** [comment]
Fixed in #4188
