### ISSUE TITLE
V8: Editing links from Multi URL Picker and Content Picker broken

### ISSUE THREAD

**Issue by nul800sebastiaan** [umbraco/Umbraco-CMS#4187]
While testing https://github.com/umbraco/Umbraco-CMS/pull/4171 I noticed that the edit button doesn't work. This seems to be a problem in Core though since if I add `allow-edit="allowEditButton"` on line 16 of `src\Umbraco.Web.UI.Client\src\views\propertyeditors\contentpicker\contentpicker.html` I get the same problem.

~~Further, I noticed that when I edit a link in the RTE, it doesn't quite know how to find the node URL, which seems related. The previously selected node is highlighted (but not selected with a checkmark) and the URL gives an error:~~

**Comment by kjac** [comment]
@nul800sebastiaan it's supposed to be highlighted, I think... but yes, the link picker is a bit broken. 

Sort of duplicate of #4083

**Comment by nul800sebastiaan** [comment]
@kjac Ah cool, the RTE part is a total duplicate of yours then yep!!

Cool, then it seems unrelated to the Multi URL / Content picker not being able to edit a picked link.

**Comment by nul800sebastiaan** [comment]
Fixed in https://github.com/umbraco/Umbraco-CMS/pull/4235
