### ISSUE TITLE
🚀 Sorting nodes is slow

### ISSUE THREAD

**Issue by uniquelau** [umbraco/Umbraco-CMS#4190]
Sorting nodes in Umbraco has been quite slow, for quite a while!
It is something that content editors often mention to me.

+ Sorting 10 nodes can take around 5 seconds
+ Sorting 100+ nodes often times out / or takes so long people give up

### Specifics

The issue is more apparent with slow SQL servers.
It seems to be an issue in more Azure SQL instances.
We experience issues with a Elastic instance that has 50 DTU's.

### Notes

Once the nodes are sorted, the page has to be refreshed, for the new order to take effect in the List data type.

**Comment by nul800sebastiaan** [comment]
Thanks @uniquelau this has been reported before and we really can't reproduce, 50 DTU is what we run on Cloud and sites there can sort just fine. I'd encourage you to investigate your implementation and setup.
