### ISSUE TITLE
v8: LogViewer doesn't sync tree

### ISSUE THREAD

**Issue by bjarnef** [umbraco/Umbraco-CMS#4191]
When selecting Log Viewer node it doesn't sync tree, e.g. when browsing to this node from "Languages" tree node, it doesn't update the hightlight of the active node.

![image](https://user-images.githubusercontent.com/2919859/51558271-50653280-1e7f-11e9-8e8f-af40c65175d3.png)

**Comment by nul800sebastiaan** [comment]
Fixed in https://github.com/umbraco/Umbraco-CMS/pull/4192
