### ISSUE TITLE
v8: Update log viewer box heading

### ISSUE THREAD

**Issue by bjarnef** [umbraco/Umbraco-CMS#4194]
In log viewer overview the box headings are right aligned, but I don't think it match the v8 UI, e.g. accordions in content and media and box heading in panels in users section.

![image](https://user-images.githubusercontent.com/2919859/51560092-e13e0d00-1e83-11e9-8143-51194b6d5032.png)

![image](https://user-images.githubusercontent.com/2919859/51559833-4d6c4100-1e83-11e9-9e75-4d07e9e36316.png)

**Comment by nul800sebastiaan** [comment]
Fixed in https://github.com/umbraco/Umbraco-CMS/pull/4195
