### ISSUE TITLE
v8: Localization of date picker

### ISSUE THREAD

**Issue by bjarnef** [umbraco/Umbraco-CMS#4201]
It seems the date picker needs some localization in v8, e.g. for Danish backoffice language it looks like this.

![image](https://user-images.githubusercontent.com/2919859/51564529-d5f0de80-1e8f-11e9-8030-b56809e9123f.png)

**Comment by bjarnef** [comment]
I am not sure the datepicker component/directive using flatpickr in v8 handle localization, but here it seems the config doesn't set the locale:
https://github.com/umbraco/Umbraco-CMS/blob/temp8/src/Umbraco.Web.UI.Client/src/views/content/overlays/schedule.controller.js#L85-L92

and here is an example for localization of flatpickr.
https://flatpickr.js.org/localization/

**Comment by kjac** [comment]
Whoa... this wasn't as easy as I thought! But there's a PR in #4223 now.

**Comment by bjarnef** [comment]
@nul800sebastiaan I guess this can be closed now?
