### ISSUE TITLE
Image link exceeding its space

### ISSUE THREAD

**Issue by elit0451** [umbraco/Umbraco-CMS#4209]
When uploading images in the Media section, if you check their `Info` tab you'd see that the link exceeded the box that is dedicated to it.

![imageURL.PNG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5b631124103d580013dcf6a4/125516c66e82c728ace21e0d46e1999b2487b69ba3abf301b44fff9e2c4533317346f62975d7e77fec177f075b5c4bac41595e41f9ac807ff0b32e6c981e5ab38532022d8c6853beb2901eb60bbb258f4787b5be8848c5e13f22f5c6.PNG)

**Comment by kjac** [comment]
PR in #4233

**Comment by nul800sebastiaan** [comment]
Fixed in https://github.com/umbraco/Umbraco-CMS/pull/4233
