### ISSUE TITLE
V8: Issue with editor-footer when chaning to splitview from listview

### ISSUE THREAD

**Issue by nielslyngsoe** [umbraco/Umbraco-CMS#4214]
When navigating from a content-node with listview to splitview the editor-footer-buttons does not update, and therefor you cant see the save or publish button.

see this screenshot:

![image](https://user-images.githubusercontent.com/6791648/51610131-48a79b80-1f1c-11e9-8d22-829d6273acab.png)

**Comment by kjac** [comment]
Nice catch @nielslyngsoe - PR in #4264

**Comment by nul800sebastiaan** [comment]
Fixed in https://github.com/umbraco/Umbraco-CMS/pull/4264
