### ISSUE TITLE
changes of DataTypes are not reflected when edited in infinite editing

### ISSUE THREAD

**Issue by nielslyngsoe** [umbraco/Umbraco-CMS#4217]
When using infinite editing to change a data-type from a content item using this data-type, the content item in the background is not updated to reflect those changes.

**Comment by RobertCopilau** [comment]
@nielslyngsoe, I can't replicate, can you confirm that this is still an issue?

**Comment by nielslyngsoe** [comment]
@RobertCopilau yes, its still a problem. See the PR for better test notes.
