### ISSUE TITLE
Temp8 - Clean up TODO comments in Umbraco.Core

### ISSUE THREAD

**Issue by readingdancer** [umbraco/Umbraco-CMS#4219]
This is not technically a Bug or a Feature, it's just trying to improve the readability of the code base.

In Visual Studio, the Task List automatically populates with various keywords, see: https://docs.microsoft.com/en-us/visualstudio/ide/using-the-task-list?view=vs-2017

For readability it makes sense for these all to be written in a consistent way, by using upper case letters they stand out when skim reading through a page of code. ( In C++ they have to be uppercase, although this is optional in other languages it does make sense to follow this standard for the reasons I just mentioned )

I have made the same changes in another pull request for the Umbraco.Web project and assuming they are both merged in, I will update the remaining projects.

I have noticed there are a hand full of comments with "fixme" at the front, IMHO these should be changed to TODO, unless this is a custom keyword used by Umbraco HQ, please confirm @nul800sebastiaan

**Comment by zpqrtbnk** [comment]
there should be way less `// fixme` comments now - we had a cleaning session earlier this week and now, `// fixme` identifies critical problems that need to be fixed before 8 ships. and, we should have a corresponding issue in our tracker. everything else should be `// todo` now.

as for `// todo` vs `// TODO` - we have both, so we keep adding both - happy if you normalize

**Comment by readingdancer** [comment]
@zpqrtbnk Thank you for the feedback, the other pull request that updates both spelling and TODO comments is here: https://github.com/umbraco/Umbraco-CMS/pull/4148 it normalizes all of the comments in the Umbraco.Web project.

**Comment by nul800sebastiaan** [comment]
Fixed in https://github.com/umbraco/Umbraco-CMS/pull/4220
