### ISSUE TITLE
v8 default datatypes - label (bigint) + label(time)

### ISSUE THREAD

**Issue by soreng** [umbraco/Umbraco-CMS#4226]
In v8 (using the nighlty build) there are two default datatypes (label (bigint) + label(time)), that uses an unkown prevalue for the value type, resulting in the dropdown being empty instead of having the value type selected

![image](https://user-images.githubusercontent.com/359492/51654824-f4db9780-1f99-11e9-855b-2484cef8198f.png)

Should these label datatypes be present?

**Comment by kjac** [comment]
That surely looks like an oversight when the new label types were added. PR in #4242

**Comment by nul800sebastiaan** [comment]
Fixed in https://github.com/umbraco/Umbraco-CMS/pull/4242
