### ISSUE TITLE
V8: Validations from main-variant does not prevent publishing of a secondary language.

### ISSUE THREAD

**Issue by nielslyngsoe** [umbraco/Umbraco-CMS#4229]
For this scenario you'll need:

A DocType that has a property that does **not allow to vary by culture**. But should be **mandatory**.

I have two languages, English and Danish. Danish inherits from English.

To replicate:

Change the main-language-selector to Danish.

Create a instance of the DocType, and do only enter the node-name. (leaving the mandatory field empty)

When publishing everything goes fine, and first afterwards you will see the validation-error in the view.

**Comment by bergmania** [comment]
PR: https://github.com/umbraco/Umbraco-CMS/pull/4327

**Comment by warrenbuckley** [comment]
@bergmania 3 failing tests that need fixing up please before I can merge this in
