### ISSUE TITLE
Sort out IContent vs Content

### ISSUE THREAD

**Issue by bergmania** [umbraco/Umbraco-CMS#4234]
In almost all our repositories we are casting `IContent` to `Content`

We need to resolve this correct instead of casting!

**Comment by Shazwazza** [comment]
A lot of sorting out of this has been done in https://github.com/umbraco/Umbraco-CMS/pull/4393 but not all

**Comment by bergmania** [comment]
We still have to clean up `DocumentRepository` 

Maybe we also should make a `IContentFactory`, instead of using the constructor to create `Content` in ContentService.

**Comment by kjac** [comment]
`DocumentRepository` is *so* close though... PR in #4611
