### ISSUE TITLE
[v8] Update Partial View Snippets to use the new v8 API

### ISSUE THREAD

**Issue by protherj** [umbraco/Umbraco-CMS#4244]
Hello,

I'm testing out the latest Editor Preview version of v8 on Nuget and when I created a "New Partial View from snippet..." in the Settings > Templating area of the Back-Office, I see that some/many of them are using the old API for v7.

The specific issue is that the Model no longer has a Content property.  The fix on the Navigation snippet was to simple change:

Model.Content.*

to:

Model.*

The other API traversal calls seemed to be the same.

### Expected result

When I create a Partial View from the Snippets, the code is best practice and using the v8 API.

Thanks,
Jason

**Comment by nul800sebastiaan** [comment]
Ah yes, they should definitely be updated! 👍

**Comment by warrenbuckley** [comment]
Done some init research
https://github.com/umbraco/Umbraco-CMS/blob/temp8/src/Umbraco.Core/Services/Implement/FileService.cs#L998-L1033

We have a switch case that will update/replace the using/inherits of the MacroPartialView template to be used for PartialView.

However, we either need to update the logic in this switch case to deal with updating `Model.Content.` to be `Model.` when used as a PartialView.

Or do we add a new templates folder that is used specifically for Partial View templates instead?

**Comment by Shazwazza** [comment]
works!
