### ISSUE TITLE
[v8] Cannot view/edit files in the "Files" section in Settings > Templating

### ISSUE THREAD

**Issue by protherj** [umbraco/Umbraco-CMS#4245]
Hello,

I'm testing out the latest Editor Preview version of v8 on Nuget and when I navigate to the Files section of the Settings > Templating area, I get an error when I select a file to view.  

The red alert bar appears on the bottom of the UI with the message:

> Request error: The URL returned a 404 (not found): 
> views/files/edit.html

I can confirm that I don't have that view in my /umbraco directory in the site, but the nuget doesn't appear to have it in it either.

### Expected result

A read-only or editable view of the file I selected

### Actual result

A 404 error and blank page

**Comment by kjac** [comment]
I'm on it... the tree shouldn't be visible in the first place. It's intended for usage elsewhere.

**Comment by zpqrtbnk** [comment]
Yup - don't waste time on it, it's fixed in a branch. See https://github.com/umbraco/Umbraco-CMS/pull/4184

**Comment by zpqrtbnk** [comment]
(I see you said you were on it 8 hours ago, hopefully you haven't spent too much time on it)

**Comment by clausjensen** [comment]
Closing this one as it will be fixed when the other branch is merged in :)
