### ISSUE TITLE
ExamineIndex configuration changed

### ISSUE THREAD

**Issue by clausjensen** [umbraco/Umbraco-CMS#4252]
child of https://github.com/umbraco/Umbraco-CMS/issues/4250

`/Config/ExamineIndex.config` is gone:

- We used to ensure the `IndexPath` in the file, via a config transform - Is there a way of doing so now? Where are they stored now / how is it configured - and how can Cloud customize?

- We used to set `directoryFactory` on the providers to ensure they were using indexes in the fast local temp storage - Is there a way of doing so now? - where are they stored now?

**Comment by Shazwazza** [comment]
## IndexPath

This doesn't need to be set or manipulated, i think we used to do this for legacy reasons anyways. The directoryFactory is what controls where the lucene "directory" is stored in terms of 'temp/local' storage. The default index path is just wherever the index defines which is `~/App_Data/TEMP/ExamineIndexes/[IndexName]`. This is currently not configurable (and doesn't really need to be). For any custom user based Lucene indexes, the user will inherit from `LuceneIndexCreator` which will define these paths anyways so as long as they create custom indexes the right way, they will all be stored in the same place. (this process has yet to be documented)

The index path is what is used to control the sub folders of where the `directoryFactory` puts them. For example, if my index path is `~/App_Data/TEMP/ExamineIndexes/MyIndex`, this is converted to a valid DirectoryInfo object and then is passed to the directoryFactory which then stores the index in the directoryFactory's root + has of the index path.

## directoryFactory

`directoryFactory` is set with an appSetting now and controls the lucene directory for any Lucene based in index created that inherits from `LuceneIndexCreator` (which should be all lucene based indexes, even custom user ones ... though none of this is documented)

So Cloud should do this appSettting transform:

`Umbraco.Examine.LuceneDirectoryFactory="Examine.LuceneEngine.Directories.TempEnvDirectoryFactory"` or 
`Umbraco.Examine.LuceneDirectoryFactory="Examine.LuceneEngine.Directories.SyncTempEnvDirectoryFactory"` 

(I can't remember which one Cloud uses, it's either Sync or not sync)

**Comment by Shazwazza** [comment]
Can i close this now?

**Comment by mikkelhm** [comment]
Yes please do, I've implemented the appsetting for v8 projects. Thanks

Få Outlook til iOS<https://aka.ms/o0ukef>

________________________________
Fra: Shannon Deminick <notifications@github.com>
Sendt: onsdag, februar 6, 2019 7:10 AM
Til: umbraco/Umbraco-CMS
Cc: Mikkel Holck Madsen; Mention
Emne: Re: [umbraco/Umbraco-CMS] ExamineIndex configuration changed (#4252)


Can i close this now?
