### ISSUE TITLE
V8: Dashboard Styling (Models Builder & PublishedContent)

### ISSUE THREAD

**Issue by warrenbuckley** [umbraco/Umbraco-CMS#4253]
The following dashboards in the Settings section look a bit inconsistent next to the other dashboards in the Settings section.

* Models Builder `src\Umbraco.Web.UI\App_Plugins\ModelsBuilder\modelsbuilder.htm`
* Published Content `src\Umbraco.Web.UI.Client\src\views\dashboard\settings\publishedstatus.html`

Maybe you can pick this up please @nielslyngsoe

**Comment by warrenbuckley** [comment]
## Models Builder
![image](https://user-images.githubusercontent.com/1389894/51751263-5855ea00-20ac-11e9-8253-f03e5f2416e6.png)

## Published Status
![image](https://user-images.githubusercontent.com/1389894/51751311-79b6d600-20ac-11e9-9bdb-527cc37475db.png)

**Comment by bergmania** [comment]
My UI eyes can only see that the ModelBuilders dashboard looks inconsistent to the rest.

@warrenbuckley , What do you think is inconsistent in the Published Content ?

**Comment by nul800sebastiaan** [comment]
Fixed in https://github.com/umbraco/Umbraco-CMS/pull/6225
