### ISSUE TITLE
Infinite editor almost hides submit button

### ISSUE THREAD

**Issue by RobertCopilau** [umbraco/Umbraco-CMS#4257]
How to replicate:
*See video
https://www.useloom.com/share/44bda41ef760429fad0b154634491d5e

Is really annoying as if you were to keep pressing the submit button, you would eventually reach the "broken" editor and instead of pressing submit, you press close which makes you lose all configs that you might have made on the editor.

**Comment by warrenbuckley** [comment]
OK I can reproduce

* Create Doctype
* Add property such as Date
* Property Editor Config opens
* Submit (Will close 2 editors - which causes this problem)
** views/common/infiniteeditors/datatypesettings/datatypesettings.html
** views/common/infiniteeditors/datatypepicker/datatypepicker.html

However if you use the close button or the `esc` key, then you will not run into this problem, as we only then remove one editor from the collection.

It seems the animation library and JS calls miscalculates the width & left

The culprit file to look into & debug with is 
`src\common\directives\components\editor\umbeditors.directive.js`

**Comment by warrenbuckley** [comment]
Paging @nielslyngsoe for help on this please - once your done with some colours :smile:

**Comment by readingdancer** [comment]
I just came across the same issue, here's a screen shot with the new colour scheme :)

![infinite editing button issue](https://user-images.githubusercontent.com/4398217/52107103-199bc480-25c3-11e9-87df-7b176536ac87.jpg)

**Comment by nielslyngsoe** [comment]
PR https://github.com/umbraco/Umbraco-CMS/pull/4352

**Comment by warrenbuckley** [comment]
All tested & reviewed. Merged in
