### ISSUE TITLE
Consolidate the remaining TODO comments and the FIXME comments.

### ISSUE THREAD

**Issue by readingdancer** [umbraco/Umbraco-CMS#4267]
I have already consolidated the TODO comments in the .Core & .Web projects, this issue is to do the same across the rest of the solution so they are all formatted:

`// TODO: `

It will also update all the FIXME & HACK comments to use the same format for consistency, i.e.:

`// FIXME:`
`// HACK: `

FYI there are current:
- 5 HACK comments
- 82 FIXME comments
- 685 TODO comments

Also for those who don't know or use the task list in Visual Studio, if you go into Visual Studio options you can add the FIXME as a recognized task list token, if you set it to important it shows the little red exclamation mark as seen in the attached screen grab.

![screenshot 21](https://user-images.githubusercontent.com/4398217/51797386-cc89ae00-21d0-11e9-8aab-62c1dbea7613.png)

Of course a lot of these comments are not really very helpful, that's something that everyone should probably try harder to ensure they are actual good comments. For example, you can see in the screen shot about  "FIXME: Wrong!" is not a very helpful comment out of context, so you would need to follow the link to find out what it's all about.

**Comment by nul800sebastiaan** [comment]
Fixed in https://github.com/umbraco/Umbraco-CMS/pull/4268
