### ISSUE TITLE
v8: Validate invalid characters in folder name

### ISSUE THREAD

**Issue by bjarnef** [umbraco/Umbraco-CMS#4272]
When trying to create a new folder under e.g. stylesheets or scripts with name `<` you get an ugly exception like the following. It could probably be handle better and show a  nicer error message to the editor/developer.

![image](https://user-images.githubusercontent.com/2919859/51801851-6a1dc580-2243-11e9-8bd3-dbadc3669747.png)

**Comment by nul800sebastiaan** [comment]
Fixed in https://github.com/umbraco/Umbraco-CMS/pull/4276
