### ISSUE TITLE
v8: Remove menuDialogTitle tooltip

### ISSUE THREAD

**Issue by bjarnef** [umbraco/Umbraco-CMS#4273]
When hovering the right-click actions overlay, I have noticed it often has an tooltip `menuDialogTitle`. Maybe this is also and issue in latest `dev-v7` branch.

![image](https://user-images.githubusercontent.com/2919859/51801895-ed3f1b80-2243-11e9-8624-3684e76c672d.png)

Not sure what this is used for, but at least it should only show the tooltip if an value it set then.

References in `dev-v7` branch:
https://github.com/umbraco/Umbraco-CMS/search?q=menuDialogTitle&unscoped_q=menuDialogTitle

**Comment by kjac** [comment]
@bjarnef thank you for remembering to report this! It's been annoying me for so long but I never got around to digging into it. 

PR in #4275.

**Comment by nul800sebastiaan** [comment]
Fixed in https://github.com/umbraco/Umbraco-CMS/pull/4275
