### ISSUE TITLE
V8 - ValueListConfigurationEditor.FromConfigurationEditor does not transform editorvalues correct

### ISSUE THREAD

**Issue by mclausen** [umbraco/Umbraco-CMS#4281]
Hi Core team,

We found an error in the `ValueListConfigurationEditor`, when transferring content from an artifact to a ConfigurationEditor.
In this case we are trying get the configuration for a checkbox list. The artifact is parsed to the appropriate ConfigurationConnector and is executing the following logic

```
public virtual object FromArtifact(IDataType dataType, IDictionary<string, object> configuration)
{
       var currentConfiguration = dataType.Configuration;
       var dataTypeConfigurationEditor = dataType.Editor.GetConfigurationEditor();
       return dataTypeConfigurationEditor.FromConfigurationEditor(configuration, currentConfiguration);
}
```
The dictionary coming from the artifact contains a string key `"items"`, with the following `JObject` value:
```
{
      "1": {
        "value": "A",
        "sortOrder": 1
      },
      "2": {
        "value": "B",
        "sortOrder": 2
      },
      "3": {
        "value": "C",
        "sortOrder": 3
      }
}
```
The data type editor is `ValueListConfigurationEditor`.

### Expectation
When calling FromConfigurationEditor we'd expect a `ValueListConfigurationEditor` with the three values listed, but we get an empty list. If we take a look we can see that we are expected to have a JArray, but there is no way that we'd be able to provide that, given the `ToConfigurationEditor`'s serialized result.

### Bonus info
In `MultiValuePropertyEditorTests` there is a test  that asserts the json result of `ToConfigurationEditor`, however there is a missing test for the corresponding `FromConfigurationEditor` scenario.

**Comment by zpqrtbnk** [comment]
So... while working on all this I realized that configuration editors already had a mechanism to serialize to/from string in a nice way: the mechanism that we use to store them in database. So, no point using the convoluted serialization used by the UI editors, way better to use the other one. Have made changes to Core, will update Deploy and if it's OK, close this... stay tuned...

**Comment by zpqrtbnk** [comment]
have pushed to temp-prevalues, moving this task to review, please kill if ok
