### ISSUE TITLE
The preview functionality in Backoffice is extremely slow

### ISSUE THREAD

**Issue by zaplvlad** [umbraco/Umbraco-CMS#4282]
Preview page loading takes a lot of time. Sometimes it's even falls by timeout. 

This request takes most of time: /umbraco/dialogs/Preview.aspx?id=####.

![image](https://user-images.githubusercontent.com/43339104/51840197-17600e80-2314-11e9-975a-562a63868adb.png)

![image](https://user-images.githubusercontent.com/43339104/51840240-3199ec80-2314-11e9-94a3-2b806338fc4a.png)

Azure server configuration:
* Web App Service Plan: S3
* Sql Database Edition: S2
* DTU quota: 50
* umbraco.config file size: ~200 MB

**Comment by nul800sebastiaan** [comment]
Hey there @zaplvlad - how annoying that this is so slow for you! Most people don't have this experience however, so it could be something in your specific site. Make sure to get some help on this on the forum at https://our.umbraco.com/

I'll close this for now, if you have good steps to reproduce the problem on a clean install of Umbraco 7.13 then we're happy to have a look. Currently, I don't have this problem on a clean install.

**Comment by zaplvlad** [comment]
Hi @nul800sebastiaan, I did deeper investigation regarding this issue and found that it could be reproduced even on vanilla Umbraco installation without custom backend code, scripts etc. On the local machine everything works properly, the thing is that application is deployed to Azure. You could find solution sources and database backup here: [https://www.dropbox.com/s/5gk55kn4pkwj59z/SlowPreviewSrc.zip?dl=0](https://www.dropbox.com/s/5gk55kn4pkwj59z/SlowPreviewSrc.zip?dl=0) (couldn't add it to attachments because of it's size).

Database size: 2,93 GB. 
Preview XML file size: 425 Mb.
Azure App Service: S2, DB: S2 50 DTU.

![image](https://user-images.githubusercontent.com/43339104/53104913-e2bd2c80-3538-11e9-9603-e78edeeede0e.png)

Preview attempts:

![image](https://user-images.githubusercontent.com/43339104/53104996-008a9180-3539-11e9-84b4-4730ba2ca25e.png)
![image](https://user-images.githubusercontent.com/43339104/53105000-041e1880-3539-11e9-8674-0dcf89ed0a26.png)
![image](https://user-images.githubusercontent.com/43339104/53105009-07190900-3539-11e9-9408-a10e193787ca.png)
![image](https://user-images.githubusercontent.com/43339104/53105021-097b6300-3539-11e9-9d43-1e1b04fe253a.png)
![image](https://user-images.githubusercontent.com/43339104/53105032-0c765380-3539-11e9-8e32-ce496b33c172.png)
![image](https://user-images.githubusercontent.com/43339104/53105042-0f714400-3539-11e9-8c15-2820d4a8f8e5.png)


By default preview .config file stored in App_Data, which is network drive for Azure App Service.
I have found in Umbraco sources that setting “umbracoPreviewPath” (as key in web.config) to a temp directory, like a “D:\local\Temp\preview” speedup preview for a several seconds. But, unfortunately I didn't found any documentation regarding this key.

Preview attempts with “umbracoPreviewPath” pointed to temp directory:

![image](https://user-images.githubusercontent.com/43339104/53111287-7c8ad680-3545-11e9-9afe-7912ec644a78.png)
![image](https://user-images.githubusercontent.com/43339104/53111298-80b6f400-3545-11e9-9a62-3147f8642d9f.png)
![image](https://user-images.githubusercontent.com/43339104/53111304-8280b780-3545-11e9-86be-cfb16b10097b.png)
![image](https://user-images.githubusercontent.com/43339104/53111310-844a7b00-3545-11e9-8e31-e9ac95a85f68.png)

So, my questions are:

1. Could we continue use “umbracoPreviewPath” key to speedup preview for now? Or there are some hidden issues with it?
2. Are there any chance that you will look into this preview issue and it will be fixed in future?

**Comment by nul800sebastiaan** [comment]
@zaplvlad The `umbracoPreviewPath` is used to store and retrieve any required files for previews so that should not be a problem. It's unlikely that you'll have a really great experience with a 425 meg XML file, but it's great that it's much faster for you already.

Currently we are concentrating most efforts into v8, where previewing is completely rewritten. I understand that is not super helpful for you right now though. The best thing I can offer you is: it's possible for you to make a preview.aspx file that has your own codebehind, you might be able to speed it up for your specific purposes.
