### ISSUE TITLE
v8: Creating template isn't using casing in name

### ISSUE THREAD

**Issue by bjarnef** [umbraco/Umbraco-CMS#4289]
In v8 when creating a template, it doesn't seems to respect the casing as previously in Umbraco v7.

E.g. when creating an template with the name "Sample Template" the generated alias is "sampleTemplate", but the physical template name also becomes "sampleTemplate" (sampleTemplate.cshtml). In v7 it would be "SampleTemplate.cshtml".

![image](https://user-images.githubusercontent.com/2919859/51861951-ce24b480-233d-11e9-95c7-1b93691b06d6.png)

However if you create an document type with a template, e.g. "Blog Post" it creates and template with name "Blog Post" (BlogPost.cshtml).

![image](https://user-images.githubusercontent.com/2919859/51862055-0cba6f00-233e-11e9-9227-6f0a6217a36b.png)

It seems a bit inconsistent and maybe something has changed in the "Create Template" action?

**Comment by nul800sebastiaan** [comment]
👍 

I've marked this as "Up for grabs" so that you or someone else coming along could create a pull request for it.

**Comment by kjac** [comment]
Got this 👍 PR incoming.
