### ISSUE TITLE
v8: Macro partial view picker

### ISSUE THREAD

**Issue by bjarnef** [umbraco/Umbraco-CMS#4290]
I noticed the new Angular + re-design of creating macros in v8 and that selecting the macro partial view is using a traditional dropdown.

![image](https://user-images.githubusercontent.com/2919859/51865309-2f508600-2346-11e9-9a19-4c5ade9976f8.png)

Maybe this should instead use the overlay as when selecting a template in document types or when selecting a master template from template editor.. or an overlay with a tree to select the view.

I would prefer one of the first two approaches to be most consistent with the rest of the UI.

![image](https://user-images.githubusercontent.com/2919859/51865352-455e4680-2346-11e9-9d82-01592780b728.png)

![image](https://user-images.githubusercontent.com/2919859/51865379-5909ad00-2346-11e9-88d9-680d379ab888.png)

**Comment by nul800sebastiaan** [comment]
It's not quite as "easy" as templates. I think it should be a tree picker that can pick files nested in the `~/views` folder. I think it's a great feature request though!

I've marked this as "Up for grabs" so that you or someone else coming along could create a pull request for it.

**Comment by bjarnef** [comment]
The template picker also has a flat stucture of the nested template, but yes in might be better with a file picker in this case since there can be several nested folders and to visualize the folder structure when picking the file.

**Comment by nul800sebastiaan** [comment]
Fixed in https://github.com/umbraco/Umbraco-CMS/pull/4412
