### ISSUE TITLE
v8 Color picker is not styled correctly

### ISSUE THREAD

**Issue by nul800sebastiaan** [umbraco/Umbraco-CMS#4294]
The color picker in v8 is not showing the swatches correctly, this is the default state:

![image](https://user-images.githubusercontent.com/304656/51893453-35c21a80-23a5-11e9-916f-52fd7650f4c8.png)

And this is the state when you select a color:

![image](https://user-images.githubusercontent.com/304656/51893469-3e1a5580-23a5-11e9-845a-c922486781be.png)

It should have looked like this, default state:

![image](https://user-images.githubusercontent.com/304656/51893586-a2d5b000-23a5-11e9-980c-56f5360c207b.png)

Color selected: 

![image](https://user-images.githubusercontent.com/304656/51893594-a79a6400-23a5-11e9-9fde-9be331c54f40.png)

**Comment by kjac** [comment]
PR in #4303

**Comment by clausjensen** [comment]
fixed in https://github.com/umbraco/Umbraco-CMS/pull/4303
