### ISSUE TITLE
True/False doesn't trigger $dirty (unsaved changes dialog)

### ISSUE THREAD

**Issue by drummerboy46** [umbraco/Umbraco-CMS#4301]
**What did I do:**

Set True/False item then navigated away from page.

**What did I expect to happen:**

Unsaved changes prompt.

**What actually happened:**

No prompt to save changes.

**Tested in:**

7.11.1 & 7.13.1

**Comment by nul800sebastiaan** [comment]
Oh no!

I've marked this as "Up for grabs" so that you or someone else coming along could create a pull request for it.

**Comment by kjac** [comment]
Nice one. PR in #4305
