### ISSUE TITLE
V8: Its not mandatory to upload a file when creating a media

### ISSUE THREAD

**Issue by nielslyngsoe** [umbraco/Umbraco-CMS#4302]
I would like it to be mandatory to upload a file when creating a media.

Reproduction
------------

Go to the media section, click create and select Media. Give it a name and click "Save"

**Comment by bergmania** [comment]
In theory it should just be to make it mandatory in the File-Media type and Image-media type. But there seems to be a bug in V8

**Comment by bergmania** [comment]
PR: https://github.com/umbraco/Umbraco-CMS/pull/4437

**Comment by warrenbuckley** [comment]
Tested & merged in
