### ISSUE TITLE
v8: Switch between media listview layouts break image previews

### ISSUE THREAD

**Issue by bjarnef** [umbraco/Umbraco-CMS#4306]
In the latest changes in `temp8` it seems the image previews in media listview layouts are broken, e.g. when switching from grid to list and back to grid layout.

![2019-01-29_18-18-36](https://user-images.githubusercontent.com/2919859/51926861-8a3fb700-23f2-11e9-9377-88094d6c7b9c.gif)

**Comment by nul800sebastiaan** [comment]
Uh oh! That seems like a bug we should fix, I'll make sure it gets on the list.

**Comment by kjac** [comment]
I've found the issue... PR incoming.

**Comment by kjac** [comment]
PR in #4336

**Comment by RobertCopilau** [comment]
Fixed and merged! 🌵
