### ISSUE TITLE
v8: Property editor preview needs a dimmed overlay

### ISSUE THREAD

**Issue by bjarnef** [umbraco/Umbraco-CMS#4308]
In v8 (maybe also in latest v7) I think the property editor preview needs andimmed overlay or similar to visualize that it is only a preview - not actually interactive inputs, sliders, pickers etc.

I think it is a bit messy at the moment and e.g. pickers looks like "real" pickers.
Furthermore often preview only show a part of the property editors.

![image](https://user-images.githubusercontent.com/2919859/51927508-fec72580-23f3-11e9-8e3a-3b87364cf562.png)

**Comment by nul800sebastiaan** [comment]
I think @nielslyngsoe is experimenting with this at the moment, otherwise we'll have a chat about it at our next regular meeting. We'll keep you posted.
