### ISSUE TITLE
v8: Log Viewer is broken

### ISSUE THREAD

**Issue by bjarnef** [umbraco/Umbraco-CMS#4309]
In latest changes in `temp8` branch, it now seems Log Viewer is broken.

![image](https://user-images.githubusercontent.com/2919859/51927949-10f59380-23f5-11e9-8d99-8bb53190e8e0.png)

**Comment by Shazwazza** [comment]
thanks for reporting it's a regression issue, fixed in temp8 branch rev: 6ff787046b595c9b19e4d18fd588f039766173e9
