### ISSUE TITLE
v8: Media listview grid no longer has checkmark on selection

### ISSUE THREAD

**Issue by bjarnef** [umbraco/Umbraco-CMS#4310]
It seems the Mmdia listview grid no longer has checkmark on selection - only a box shadow.

![image](https://user-images.githubusercontent.com/2919859/51928160-895c5480-23f5-11e9-8fe0-dde5eae129e8.png)

It is inconsistent with selection on content listview grid layout.

![image](https://user-images.githubusercontent.com/2919859/51928209-a6912300-23f5-11e9-87fc-4acea0063423.png)

**Comment by nul800sebastiaan** [comment]
Thanks @bjarnef we're experimenting with this one at the moment, @nielslyngsoe can update on progress for this one!

**Comment by nielslyngsoe** [comment]
Hi @bjarnef 

I have corrected this, please have a look if you want — always open for feedback.

Thanks
