### ISSUE TITLE
v8: Member listviews return error

### ISSUE THREAD

**Issue by bjarnef** [umbraco/Umbraco-CMS#4311]
In latest changes in `temp8` branch, the member listview now returns an error.

![image](https://user-images.githubusercontent.com/2919859/51928338-01c31580-23f6-11e9-8006-380bd69376eb.png)

![image](https://user-images.githubusercontent.com/2919859/51928349-07206000-23f6-11e9-91cf-76330cca04c2.png)

**Comment by Shazwazza** [comment]
thanks for reporting it's a regression issue, fixed in temp8 branch rev: 6c0321ce72959877e611ced85a1cff8ca41dec33
