### ISSUE TITLE
v8: Replace confirm in redirects dashboard with overlay

### ISSUE THREAD

**Issue by bjarnef** [umbraco/Umbraco-CMS#4312]
In redirects management dashboard, when disabling URL tracker, I think the traditional the new overlay as used several places in v8: media delete, language delete, schedule publishing etc.

![image](https://user-images.githubusercontent.com/2919859/51928677-bb21eb00-23f6-11e9-911b-4b24256f3370.png)

**Comment by bjarnef** [comment]
@kjac yes it would. At the moment it use `overlayService` in several parts of the UI. It would be great to replace this with `overlayService` for now and then enhance it later. Just to make it "pretty" for v8 release 😁

**Comment by nul800sebastiaan** [comment]
All good for now!
