### ISSUE TITLE
v8: Users layout switcher is empty

### ISSUE THREAD

**Issue by bjarnef** [umbraco/Umbraco-CMS#4313]
In v8 the layout switcher seems to be empty. I have also noticed this in v7.

![image](https://user-images.githubusercontent.com/2919859/51928980-78144780-23f7-11e9-90b3-da67772d8b07.png)

It used to have a listview layout similar to members listview list layout.

**Comment by nul800sebastiaan** [comment]
Ah, I am not sure what the intention is, might be that we just don't need the switcher any more. We'll discuss at our next regular meeting and let you know.

**Comment by bjarnef** [comment]
@nul800sebastiaan when the new user section was re-designed, it used to have the listview list layout, which seem to exists in latest v7.

![image](https://user-images.githubusercontent.com/2919859/52351624-6b14db00-2a2b-11e9-8aa7-2b7208fe63f1.png)

**Comment by bjarnef** [comment]
Okay, the reason this is empty is it now have `track by` name, which it didn't have in v7: https://github.com/umbraco/Umbraco-CMS/blob/dd6e764588d22ef2b7bce01fd504ece89834f181/src/Umbraco.Web.UI.Client/src/views/components/umb-layout-selector.html

```
<div ng-repeat="layout in vm.layouts | filter:{selected:true} track by layout.name"
            class="umb-layout-selector__dropdown-item"
            ng-click="vm.pickLayout(layout)"
            ng-class="{'-active': layout.active }"
            ng-attr-title="{{layout.name}}">

           <i class="{{ layout.icon }} umb-layout-selector__dropdown-item-icon"></i>
</div>
```

but in users sections the layouts doesn't have a name property.
```
[ { "icon": "icon-thumbnails-small", "path": "1", "selected": true, "active": true }, { "icon": "icon-list", "path": "2", "selected": true } ] 
```
Furthermore I am not sure if `name` is a safe property. If used in a custom section or similar `name` might not be unique.

Maybe it would be better to use `track by $id(layout)`.

**Comment by bjarnef** [comment]
@nul800sebastiaan I have fixed this in https://github.com/umbraco/Umbraco-CMS/pull/4458
