### ISSUE TITLE
v8: Macro editor property picker

### ISSUE THREAD

**Issue by bjarnef** [umbraco/Umbraco-CMS#4318]
In macro parameters the editor is a traditional dropdown. It would be great to change this to a property picker similar to when selecting data type on document types or selecting field types in Umbraco Forms.

![image](https://user-images.githubusercontent.com/2919859/51942910-7c9d2800-2418-11e9-90ec-848f0243d623.png)

**Comment by nul800sebastiaan** [comment]
To me it seems like a good idea, but let me get some feedback first. I'll let you know after our next regular meeting.

**Comment by nul800sebastiaan** [comment]
We had a chat about this recently and @nielslyngsoe indicated he would get back at you with some feedback! 👍

**Comment by bjarnef** [comment]
@nul800sebastiaan I tried a quick prototype for this and keep the UI consistent as much as possible with selecting datatypes on document types.

The top part in the overlay is the new stuff (consistent with datatypes on document types) and the bottom part is the current stuff (should be removed if we go with this stuff).

![2019-10-02_22-50-22](https://user-images.githubusercontent.com/2919859/66080834-295f1480-e567-11e9-9a16-dbd807537281.gif)

**Comment by nul800sebastiaan** [comment]
Looks great @bjarnef! I assume this will not show all editor, but only the ones that are available as a macro parameter editor?

**Comment by nielslyngsoe** [comment]
@bjarnef looks good, looking forward to the PR, and as Sebastian is asking; I guess the options are the same as before, its just the UI you will be changing, right?

Looks very good to me!

**Comment by bjarnef** [comment]
@nul800sebastiaan it only get the same parameter editors as listed in the current dropdown.
I have a branch for it here https://github.com/bjarnef/Umbraco-CMS/tree/dev-v8-temp-macro-parameter-editor

but I can create a PR for this in a few days.

The existing dropdown has a method `GetParameterEditors` and I have added a new method `GetGroupedParameterEditors`.
https://github.com/bjarnef/Umbraco-CMS/commit/c302d59067b0f42a22d383871f8f69f72998fd1a

Maybe these should return `IDictionary<string, IEnumerable<T>>` similar to `GetGroupedDataTypes` instead of `HttpResponseMessage`, but would can always change this later.

https://github.com/umbraco/Umbraco-CMS/blob/9c06ef83e217affbce51c1d6682f10914be2b400/src/Umbraco.Web/Editors/DataTypeController.cs#L311-L335

As this moment when browsing to a macro it also create to requests to partial views and macro parameter editors (where parameter editors are passed in to the overlay in the current setup). Not sure this is necessary and it instead only request parameter editors in the overlay. We might change the same for partial views, so it only create the request when opening the overlay.

**Comment by bjarnef** [comment]
At the moment there is this inifinite editor.
https://github.com/umbraco/Umbraco-CMS/tree/v8/dev/src/Umbraco.Web.UI.Client/src/views/macros/infiniteeditors

I have added a new one is this folder https://github.com/umbraco/Umbraco-CMS/tree/v8/dev/src/Umbraco.Web.UI.Client/src/views/common/infiniteeditors for "macro parameter editor picker" (similar to how datatypepicker).
This can be re-used (but not sure if there is a use-case where package developers would use this?).

This existing one in macros/infiniteeditors might be specific to macros, so I guess it is fine it is located here for now?
