### ISSUE TITLE
v8: Default Dropdown and Dropdown multiple data types are opposites

### ISSUE THREAD

**Issue by jmayntzhusen** [umbraco/Umbraco-CMS#4322]
"Dropdown" is set to be able to select multiple values while "Dropdown multiple" is not

In short in the current v8 nightly build there are these built-in property editors, but it seems that they have the opposite names of their configuration, see the images below:

![2019-01-30_0914](https://user-images.githubusercontent.com/36075913/51967728-64f18e00-2470-11e9-9308-e557c23c32b9.png)
![2019-01-30_0914_001](https://user-images.githubusercontent.com/36075913/51967730-64f18e00-2470-11e9-9efa-ca0622dda4cd.png)

**Comment by clausjensen** [comment]
Need to make sure these are switched around. Please be aware not to switch them around incorrectly - check out which one (according to guid) is supposed to be the multiple one (based on what it was in v7)

**Comment by kjac** [comment]
PR in #4370
