### ISSUE TITLE
V8: Can't create templates from backoffice

### ISSUE THREAD

**Issue by jmayntzhusen** [umbraco/Umbraco-CMS#4328]
In the current V8 nightly (1958) you can't create templates in the backoffice.

Reproduction
------------

If you're filing a bug, please describe how to reproduce it. Include as much
relevant information as possible, such as:

### Bug summary

In the current V8 nightly (1958) you can't create templates in the backoffice.

### Specifics

URL: http://localhost:xxxx/umbraco#/settings 
Version: 8.0.0-alpha.58.1958
Browser: Chrome, haven't checked elsewhere
### Steps to reproduce

1. Go to settings and click the create template button: 
![2019-01-30_1437](https://user-images.githubusercontent.com/36075913/51984977-07c00180-249d-11e9-91d5-26ab4b5f7c5e.png)
2. You are redirected to this page (note the url):
![2019-01-30_1437_001](https://user-images.githubusercontent.com/36075913/51985020-20c8b280-249d-11e9-95e7-a4a958fde4d1.png)

**Comment by bergmania** [comment]
Are fixed in the next nightly, so I'm closing
