### ISSUE TITLE
Icon size in modal overlay

### ISSUE THREAD

**Issue by bjarnef** [umbraco/Umbraco-CMS#4333]
At this line it set font-size of all `<i>` elements to 20px, which affect existing layout, so you would have to overwrite it again.
https://github.com/umbraco/Umbraco-CMS/blob/dd6e764588d22ef2b7bce01fd504ece89834f181/src/Umbraco.Web.UI.Client/src/less/modals.less#L183-L185

E.g. in the search bar the icon size too large.

![image](https://user-images.githubusercontent.com/2919859/52041008-7783ca00-2539-11e9-84b5-2061f9839a3c.png)

The change was made in this commit https://github.com/umbraco/Umbraco-CMS/commit/a927d5fb84439488de60a6784ae13d4a8ea87fd4#diff-6d4ea2b45e5db688264f1df960ff147b and this PR https://github.com/umbraco/Umbraco-CMS/pull/2459

to fix this original issue https://issues.umbraco.org/issue/U4-10702, but I think this should be changed in the component `umb-node-preview` since the global change for `.umb-modal i` affect many property editors, e.g. search bar, toggle button, etc.

It isn't an issue in the new overlay component `umb-overlay` because this doesn't use `umb-modal` class, but the old dialogService used it, e.g. LeBlender package.

We should ensure `umb-modal i` has same base font size and it the new `umb-overlay` component.

**Comment by clausjensen** [comment]
Thanks for reporting 😄
Marking as up for grabs - I think you're right about this needing to be fixed elsewhere

**Comment by nul800sebastiaan** [comment]
This issue has been in the `up for grabs` state for quite a while now and it seems nobody is ready to pick this one up.

For now we'll close this issue to prevent the list of `up for grabs` from becoming very stale. We're happy to re-open it if someone still thinks it's good to work on this. 

If anyone is about to pick this issue up to fix it, make sure to test first if you can reproduce the problem in the latest version before you start to work on it.

Thanks!
Sebastiaan on behalf of Umbraco HQ.
