### ISSUE TITLE
V8: Opening a list-view item should open as an infinity editor

### ISSUE THREAD

**Issue by nielslyngsoe** [umbraco/Umbraco-CMS#4334]
I want content-nodes from a listview to open as infinity editors

**Comment by warrenbuckley** [comment]
@nielslyngsoe I can't easily find your PR for this. Can you point me to it please mate

**Comment by nielslyngsoe** [comment]
PR
https://github.com/umbraco/Umbraco-CMS/pull/4562

**Comment by RobertCopilau** [comment]
Merge conflict dealt with, testing again for good measure.
