### ISSUE TITLE
v8 - No membergroups are available

### ISSUE THREAD

**Issue by mclausen** [umbraco/Umbraco-CMS#4338]
Hi Core team

Given i have created two member groups
Test 1, Test 2

When I create a new Content
And I select "Add"

Then i expect to see a list of my member groups

The following screenshot appears
![no-member-group-available](https://user-images.githubusercontent.com/3600782/52055988-428b6d80-2561-11e9-8c34-75dccd6b2e38.PNG)

**Comment by kjac** [comment]
Hi @mclausen 😄  

Whatever the issue was, it looks like it's fixed in the latest `temp8` source:

![member-group-picker](https://user-images.githubusercontent.com/7405322/52078932-c0b53780-2594-11e9-91d6-b84c12f79028.gif)

**Comment by mclausen** [comment]
Awesome Thank you 👍
