### ISSUE TITLE
v8 - Unable to find all-members.html and Members.html

### ISSUE THREAD

**Issue by mclausen** [umbraco/Umbraco-CMS#4339]
In the Members sections.

When clicking on "All Members" and "Members" the following image appears.

![cant-find-list-all-members](https://user-images.githubusercontent.com/3600782/52056639-107b0b00-2563-11e9-9bda-26b42ba15156.PNG)

**Comment by kjac** [comment]
@mclausen looks like it works in the latest `temp8` source:

![image](https://user-images.githubusercontent.com/7405322/52078775-556b6580-2594-11e9-9768-4569beb1eb2a.png)

**Comment by bjarnef** [comment]
@mclausen the issue is already fixed here :)
https://github.com/umbraco/Umbraco-CMS/issues/4311

**Comment by mclausen** [comment]
Awesome Thank you 👍
