### ISSUE TITLE
v8 - Database consistency => Rename umbracoDomains to umbracoDomain

### ISSUE THREAD

**Issue by JeffreyPerplex** [umbraco/Umbraco-CMS#4348]
If you look at the current tables in the database you'll see that only the table umbracoDomains is in plural form. All other tables have singular name.

We once got audited by an external party and one of their checks for code quality was consistency, and we failed because of this table :)

Stupid, but true, and maybe v8 is a good time to remove this inconsistency. Rename umbracoDomains to umbracoDomain

Cheerio, Jeffrey

**Comment by clausjensen** [comment]
Thanks for reporting @JeffreyPerplex  :)
Yep .. might as well get it done now.

Note: would need a migration added for this

**Comment by kjac** [comment]
Oh that's a sad way to flunk a code audit 😆 

Seems simple enough. I'll get right on it.

**Comment by kjac** [comment]
PR in #4432

**Comment by Shazwazza** [comment]
Works! thanks :)
