### ISSUE TITLE
v8 - A description on the default mediaType

### ISSUE THREAD

**Issue by JeffreyPerplex** [umbraco/Umbraco-CMS#4349]
When testing v8 with some editors who were new to Umbraco we got the comment about what "size", "width" and "height" were. Especially with the size they were wondering if it were megabytes or kilobytes. 

Of course, from a developer perspective totally clear, but a little description would help these editors for sure.

- Add description to "Media type" => Property "width" => "in pixels"
- Add description to "Media type" => Property "height" => "in pixels"
- Add description to "Media type" => Property "size" => "in bytes"

Small change, big difference for newbies.

![before](https://user-images.githubusercontent.com/12457148/52110308-82edf880-2600-11e9-8c74-bf24ff68cd41.png)
![after](https://user-images.githubusercontent.com/12457148/52110309-84b7bc00-2600-11e9-9ed9-420547df5ce7.png)

**Comment by kjac** [comment]
Yes! A thousand times yes! 🥇 

I'll toss a PR at this shortly. 

I think we only need to apply this to new installs. It seems pretty much like overkill to add a migration that applies these labels to upgraded installs, no?

**Comment by clausjensen** [comment]
Yes please! 😃 
And yep - No migration needed. If anyone has had this as an issue, they have most likely just added the description and fixed it up themselves. This is just a nice to have addition moving ahead.

**Comment by kjac** [comment]
PR in #4361

**Comment by JeffreyPerplex** [comment]
Wow, that is amazingly quick! Thanks!

And good to see in the PR where these things happen. Next time I will create the PR myself :)

**Comment by clausjensen** [comment]
@JeffreyPerplex if you're quick you can make one for V7 as well .. it would be fine to have this in new V7 sites as well ;)

**Comment by nul800sebastiaan** [comment]
Forgot to close, this was added to 8.0.0 - https://github.com/umbraco/Umbraco-CMS/pull/4361
