### ISSUE TITLE
v8 - Umbraco.MediaPicker datatype - Upload button doesn't work

### ISSUE THREAD

**Issue by JeffreyPerplex** [umbraco/Umbraco-CMS#4351]
If you add an Umbraco.Mediapicker datatype to your doctype the "Upload"-button (top-right, the purple one) doesn't work. The only way to add files / images is by drag-and-dropping them in the pane.

Tested it in Firefox &
![upload button](https://user-images.githubusercontent.com/12457148/52110893-5c30c180-2602-11e9-9c46-e669eb00b1bc.png)
 Chrome

**Comment by kjac** [comment]
Good catch! This is particularly annoying on folders that aren't empty, because the dropzone is hidden in those folders...!

PR in #4357

**Comment by RobertCopilau** [comment]
Merged.
