### ISSUE TITLE
V8: Cant save & publish changes from another language than the selected language when clicking "publish..."

### ISSUE THREAD

**Issue by nielslyngsoe** [umbraco/Umbraco-CMS#4354]
Create a DocType that allows for variants, write some content for English, change to another language. Click "Publish..." then you are not able to select English.

**Comment by bergmania** [comment]
PR: https://github.com/umbraco/Umbraco-CMS/pull/4355

**Comment by warrenbuckley** [comment]
Already been merged in by @nielslyngsoe
