### ISSUE TITLE
V8: Multiple actions relies on $scope.currentNode, but its not always set.

### ISSUE THREAD

**Issue by nielslyngsoe** [umbraco/Umbraco-CMS#4358]
Multiple of the actions in the top-right corner dropdown uses the $scope.currentNode. But currentNode is not set if the user haven't interacted with the tree. Like if the user have opened a link to a content-node.

**Comment by kjac** [comment]
Wouldn't the editor automatically tree sync to the current node and thus make its actions available?

**Comment by kjac** [comment]
There are more issues with this: https://github.com/umbraco/Umbraco-CMS/issues/4369

Did this happen when the action button was redone? I could have sworn it worked just fine not so long ago.

**Comment by kjac** [comment]
PR in #4384

**Comment by clausjensen** [comment]
Assuming this is fixed as well in the merged PR - otherwise please reopen! :)
