### ISSUE TITLE
V8: The ability to navigate between property groups

### ISSUE THREAD

**Issue by hartvig** [umbraco/Umbraco-CMS#4360]
As an editor, I should quickly be able to navigate between property groups so that I don't have to resort to scrolling but also so that I can always get an overview of the available groups on the page. 

For Property Editors that support this, the first editor from the group should get focus, so that the editor can immediately start working without any further navigation.

See attached mockup.
![navigate-mockup](https://user-images.githubusercontent.com/1315899/52125631-63b99000-262d-11e9-8837-8214d10ab1fe.png)

**Comment by warrenbuckley** [comment]
All merged in
