### ISSUE TITLE
ArgumentNullException on BackOfficeCookieAuthenticationProvider.ValidateIdentity(context) invocation after cloning site

### ISSUE THREAD

**Issue by matthew-hair** [umbraco/Umbraco-CMS#4365]
After cloning my site, and trying to run the clone and authenticate to the back office using an existing authentication cookie, I sometimes get a YSOD, which can only be resolved by clearing cookies for the domain. The error message is "System.ArgumentNullException: Value cannot be null.", "Parameter name: identity". The full stack trace is available below.

Reproduction
------------

I clone my production site to my local machine (see footnotes) and login. Some time passes, and I want to test out a new Umbraco release's upgrade process, so I clone the production site again, and try to run the clone. My browser still has the authentication cookie from the previous login, and Umbraco tries to reuse it for a new authentication to the back office. I receive a YSOD with an `ArgumentNullException`, and it says the "identity" parameter is null. The exception is only thrown in some cases, and I haven't yet figured out why the code works sometimes, and fails at other times, so reproduction is difficult. The full stack trace is below.

The issue affects Umbraco 7.13.1, and has affected it at least as far back as 7.6.0, which is about the time I started cloning and noticing the issue.

### Expected result

I would expect to be presented with the back office login screen if I have an existing authentication cookie that is in any way invalid.

### Proposed solution

The exception surfaces in the [`BackOfficeCookieAuthenticationProvider.ValidateIdentity(context)`](https://github.com/umbraco/Umbraco-CMS/blob/4dd51f645a715b76c669f0d93070cdbdbd404d8e/src/Umbraco.Core/Security/BackOfficeCookieAuthenticationProvider.cs#L103) method, when it calls `base.ValidateIdentity(context)`:

```cs
public override async Task ValidateIdentity(CookieValidateIdentityContext context)
{
	//ensure the thread culture is set
	context?.Identity?.EnsureCulture();

	await EnsureValidSessionId(context);

	await base.ValidateIdentity(context);
}
```

Since the null argument is actually the `context.Identity`, I suggest adding a null check for `context.Identity` before calling `base.ValidateIdentity(context)`:

```cs
public override async Task ValidateIdentity(CookieValidateIdentityContext context)
{
	//ensure the thread culture is set
	context?.Identity?.EnsureCulture();

	await EnsureValidSessionId(context);

	if (context?.Identity == null)
	{
		context?.OwinContext.Authentication.SignOut(context.Options.AuthenticationType);
		return;
	}
	await base.ValidateIdentity(context);
}
```
This fix does work in my testing.

### Stack Trace

`[ArgumentNullException: Value cannot be null.
Parameter name: identity]
   Microsoft.AspNet.Identity.IdentityExtensions.GetUserId(IIdentity identity) +144
   Umbraco.Web.Security.Identity.<>c.<UseUmbracoBackOfficeCookieAuthentication>b__7_1(ClaimsIdentity identity) +6
   Microsoft.AspNet.Identity.Owin.<<OnValidateIdentity>b__0>d.MoveNext() +495
   System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) +99
   System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) +58
   Umbraco.Core.Security.<ValidateIdentity>d__6.MoveNext() +287
   System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) +99
   System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) +58
   System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task) +25
   Microsoft.Owin.Security.Cookies.<AuthenticateCoreAsync>d__2.MoveNext() +2160
   System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) +99
   System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) +58
   Microsoft.Owin.Security.Infrastructure.<BaseInitializeAsync>d__0.MoveNext() +571
   System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) +99
   System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) +58
   Microsoft.Owin.Security.Infrastructure.<Invoke>d__0.MoveNext() +255
   System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) +99
   System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) +58
   Microsoft.AspNet.Identity.Owin.<Invoke>d__5.MoveNext() +383
   System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) +99
   System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) +58
   Microsoft.AspNet.Identity.Owin.<Invoke>d__5.MoveNext() +383
   System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) +99
   System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) +58
   Microsoft.Owin.Host.SystemWeb.IntegratedPipeline.<RunApp>d__5.MoveNext() +182
   System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) +99
   System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) +58
   Microsoft.Owin.Host.SystemWeb.IntegratedPipeline.<DoFinalWork>d__2.MoveNext() +180
   Microsoft.Owin.Host.SystemWeb.IntegratedPipeline.StageAsyncResult.End(IAsyncResult ar) +69
   Microsoft.Owin.Host.SystemWeb.IntegratedPipeline.IntegratedPipelineContext.EndFinalWork(IAsyncResult ar) +64
   System.Web.AsyncEventExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute() +483
   System.Web.HttpApplication.ExecuteStepImpl(IExecutionStep step) +132
   System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously) +163`

Notes
------------

At a high level, my cloning process involves these steps and runs from a PowerShell script:

1. Clone the production database to a copy on my local machine's (localdb)\MSSQLLocalDB instance using SQL bulk copy.
2. Clone the production site code and assets to a local workstation folder using an msdeploy -sync command.
3. Reconfigure connection strings and other resource paths in .config files to utilize the local clones.
4. Invoke the cloned site in IIS Express using a unique port number, and open it in a browser.

**Comment by Nicholas-Westby** [comment]
I'm glad to see this error is handled a bit better now. I just had this issue and had it a while back as well: https://issues.umbraco.org/issue/U4-11331

I imagine there is some good reason that the login can't continue to work, and so you must show the login screen rather than allow the login to continue to work. Still, this is better than a confusing error and having to clear my cookies. Thanks for this.
