### ISSUE TITLE
v8 nightly (alpha.58.2029): unable to load culture and hostnames when invoked from "action"-menu

### ISSUE THREAD

**Issue by soreng** [umbraco/Umbraco-CMS#4369]
When I click on "culture and hostnames" in the "actions"-menu, I get an error

![image](https://user-images.githubusercontent.com/359492/52158548-a4e78980-2699-11e9-970a-57588371ecc9.png)

it seem to not be able to find the currentnode:
![image](https://user-images.githubusercontent.com/359492/52158562-c9436600-2699-11e9-9d84-61d5e4528ecc.png)
![image](https://user-images.githubusercontent.com/359492/52158569-de1ff980-2699-11e9-828a-29cc764e5ef2.png)

Using the context-menu from the content-tree, culture and hostnames loads as expected.

**Comment by soreng** [comment]
It seems that more items in the "actions"-menu are not able to access $scope.currentNode

**Comment by kjac** [comment]
PR in #4384

**Comment by clausjensen** [comment]
Closing this - PR was merged in.
