### ISSUE TITLE
v8: Support 2 letter and 5 letter lang files in App_Plugins dir

### ISSUE THREAD

**Issue by mattbrailsford** [umbraco/Umbraco-CMS#4371]
Currently in v8 when it tries to resolve lang files in the `App_Plugins` folder, it only looks for 5 letter culture names such as "en_us" or "en_gb". It used to be that we could also support the two letter culture codes such as just "en" to handle all English languages.

Maybe we should support both 2 and 5, but 5 should take precedence over the 2 letter.

https://github.com/umbraco/Umbraco-CMS/blob/temp8/src/Umbraco.Core/Composing/Composers/ServicesComposer.cs#L102

**Comment by Shazwazza** [comment]
But in fact 5 letters isn't enough either ;) it can actually be xx-XXXX where XXXX can include numbers too 😱 examples `zh-Hant` and there's a bunch of other odd ones too (like a new one for International English but i can't remember what it is)

**Comment by mattbrailsford** [comment]
Lol, in that case it's even "wronger" than I though :joy:

Either way, I think we get the gist

**Comment by kjac** [comment]
I've got this one 👍

**Comment by kjac** [comment]
PR in #4454

**Comment by clausjensen** [comment]
connects to https://github.com/umbraco/Umbraco-CMS/pull/4454

**Comment by nul800sebastiaan** [comment]
Fixed in https://github.com/umbraco/Umbraco-CMS/pull/4454
