### ISSUE TITLE
v8: LocalizedTextServiceFileSources incorrectly resolving lang files

### ISSUE THREAD

**Issue by mattbrailsford** [umbraco/Umbraco-CMS#4372]
When the LocalizedTextServiceFileSources service merges lang files located in the App_Plugin folder, when looking for files to merge based on resolved filenames, it is incorrectly looking for files by the culture name, which is formatted as "en-US" rather than the documented file naming format of "en_us".

Culture name should be reformatted before the lookup is attempted to ensure it's using the right filename format.

https://github.com/umbraco/Umbraco-CMS/blob/temp8/src/Umbraco.Core/Services/Implement/LocalizedTextServiceFileSources.cs#L188

**Comment by nul800sebastiaan** [comment]
@mattbrailsford Thanks for the report, as far as I remember we at some point in v7 went: "oh my.. the language files in `Umbraco/config/Lang` are all named wrong and inconsistent.. but(!) now that we're building a new feature to let people drop files into `App_Plugins`, let's make sure we use a nice, real Locale identifier for each of them".
So, for plugins, it's  `en-UK.xml`, `dk-DK.xml`, `nl-NL.xml`, etc.
Does that make sense? The docs need to be updated if you have a link though?

**Comment by nul800sebastiaan** [comment]
Unless I'm missing something I think the code works as expected, so I'll close this one. Drop me a link to the faulty docs though so we can get them fixed! 👍
