### ISSUE TITLE
v8: Login screen should ask for email not username

### ISSUE THREAD

**Issue by mattbrailsford** [umbraco/Umbraco-CMS#4373]
In v8 users appear to no longer have a username, instead they log in using their email.

With that in mind, the login screen should be updated so it asks for email + password, rather than username + password.

![image](https://user-images.githubusercontent.com/527305/52165677-bf524f00-26fb-11e9-8ed7-780386ff45d5.png)

**Comment by kjac** [comment]
@mattbrailsford you can change this in `usernameIsEmail` in `umbracoSettings.config`:

![image](https://user-images.githubusercontent.com/7405322/52169809-8a1b2080-273e-11e9-8b22-81bb54ff2fc1.png)

When it's `false` the user editor looks like this:

![image](https://user-images.githubusercontent.com/7405322/52169792-6061f980-273e-11e9-8be3-74b805cd4bf9.png)

That being said it would probably make sense to change *Username* to *Email* if it's set to `true` (default), even if there are slight (tiny) security implications of doing so. I'll have a look at a PR soon.

**Comment by mattbrailsford** [comment]
Ahh, didn't know about the config option. PR #4383 looks a good solution. 👍

**Comment by nul800sebastiaan** [comment]
Problem is.. this config option might have been switched from true to false along the way, so now we have old users with a non-email username and new users that use their email as their username. The default has been email for new installs for over a year now and people seem to have gotten used to this and find the placeholder text acceptable. The email is still a username, albeit in an email format.

Anyway, all this to say: I don't know if this needs changing, I'll have to discuss with the team soon, will get back to you!

**Comment by kjac** [comment]
It's not a critical change for sure 😊 but it goes nicely with the whole "don't make me think" strategy.

**Comment by nul800sebastiaan** [comment]
Also what if the username that you've set up IS already an email address. Then you'd "make me think" about whether I forgot to create a username.. ;)

**Comment by nathanwoulfe** [comment]
Why not both? Plenty of services allow logging in via email or username, and removes the burden from the user to remember whether the email was their username and vice-versa.

**Comment by kjac** [comment]
@nathanwoulfe @nul800sebastiaan I think what @mattbrailsford is getting at here is ... if Umbraco is configured to use email as username, you *can't* use anything else. The email property is set on the user, separately from the username, and setting `usernameIsEmail` to `true` efficiently disregards the username property.

As is the login screen shows "Username" and "Your username is usually your email" in an attempt to help the user. #4383 changes that to "Email" and "Enter your email" if you really can't log in with anything but your email.

**Comment by nul800sebastiaan** [comment]
Fixed in https://github.com/umbraco/Umbraco-CMS/pull/4383
