### ISSUE TITLE
v8: Move back office sections out of trees namespace

### ISSUE THREAD

**Issue by mattbrailsford** [umbraco/Umbraco-CMS#4376]
Currently, all BackOfficeSection related classes are all held in the Umbraco.Web.Trees namespace. Given sections aren't really trees, I think these should be moved to a Umbraco.Web.Sections namespace.

**Comment by nul800sebastiaan** [comment]
Sounds like a good idea, I'll have to discuss with the team soon, will get back to you!

**Comment by zpqrtbnk** [comment]
Considering that we need to do these changes.... now-ish, moving to "in-progress"

**Comment by zpqrtbnk** [comment]
PR is #4630 ready for review (test that backoffice works) - might have impact on Forms/Deploy
