### ISSUE TITLE
v8: Improvements to the trees api

### ISSUE THREAD

**Issue by mattbrailsford** [umbraco/Umbraco-CMS#4377]
Currently when developing a custom tree, you return a list of child nodes by implementing the `GetTreeNodes` method. This method in tern gets called for each sub level when the tree is expanded in the UI.

In order to know which level of items to return, the `GetTreeNodes` method is passed an ID of the parent node. Unfortunately this assumes that every node on the tree is dynamic and all from the same repository. However, this is not always the case and you may end up having some hard coded nodes. Take for example an ecommerce package I'm developing. At the root level we have a list of stores, and within each store we have a series of sub setting nodes which are fixed / hard coded.

![image](https://user-images.githubusercontent.com/527305/52175538-43104800-279d-11e9-9cbd-5f388f466f66.png)

In this example, the sub container nodes have child items which are stored in their own DB tables and so each has it's own ID numbering sequence and repository. What this means though when implementing `GetTreeNodes` is that we need to know which sub container the request is for. In order to handle this type of setup, we end up having to create some kind of amalgamated ID such as `store__1` or `currency__10` which is parsed inside the `GetTreeNodes` method in order to give it context so we know from which repository the lookup should be performed against.

It would be good if we could handle this type of thing out of the box and have a means of providing more context beyond the ID parameter such that we don't have to "fudge" the ID system to pass additional info.

I'm not sure if it could be a nice idea to be able to have nested tree controllers (this is kind of like how hive would have worked in v5) where you could say "from this node on, use this tree controller". Failing this, just some means of providing the additional context would suffice,

**Comment by Shazwazza** [comment]
You can do that already, have a look at the `TreeNode` properties, there is one called `ChildNodesUrl` which is what you are talking about. For sake of simplicity, when creating TreeNodes you generally just give it a few simple parameters and all of the underlying properties are wired up but you have full control of setting any and all properties of TreeNode directly. The `ChildNodesUrl` property is normally set with `Url.GetTreeUrl(GetType(), id, queryStrings)`, have a look at the `TreeControllerBase` methods for overloads of `CreateTreeNode`
