### ISSUE TITLE
v8: TreeControllerBase GetRootNode should use icon defined in TreeAttribute

### ISSUE THREAD

**Issue by mattbrailsford** [umbraco/Umbraco-CMS#4380]
When you define a tree you use the `TreeAttribute` to define meta data about the tree. Two of those meta data items are `IconOpen` and `IconClosed`, however these appear to be ignored / unused. Really, when `GetRootNode` is called, it should set the root nodes icon to be that defined in the attribute. Right now, you currently have to override `GetRootNode` and explicitly set the icon.

**Comment by Shazwazza** [comment]
Aha, those properties should have been removed but this was overlooked thanks for pointing that out.

Setting this property in GetRootNode is how it is supposed to work.
