### ISSUE TITLE
v8: Tree groups should be able to have their own dashboards

### ISSUE THREAD

**Issue by mattbrailsford** [umbraco/Umbraco-CMS#4381]
With the introduction of tree groups, it could be nice for them to be able to have their own specific dashboards. For example, I'm working on an ecommerce plugin and have created an ecommerce tree group. I have some general settings that would work well on a dashboard but rather than merge it in with the root level dashboards that have no context, it would be nice if this could be displayed on "commerce" tree group instead.

**Comment by nul800sebastiaan** [comment]
Sounds like a good idea, I'll have to discuss with the team soon, will get back to you!

**Comment by nul800sebastiaan** [comment]
Took a little bit longer than expected but we've discussed this and it sounds like a good idea to us! 👍 

I've marked this as "Up for grabs" so that you or someone else coming along could create a pull request for it.

**Comment by abjerner** [comment]
If someone were to make a PR for this, what would be the best way to set the configuration of a tree group?

Right now a tree group only exists as long as at least one tree controller has specified the group.

**Comment by nul800sebastiaan** [comment]
This issue has been in the `up for grabs` state for quite a while now and it seems nobody is ready to pick this one up.

For now we'll close this issue to prevent the list of `up for grabs` from becoming very stale. We're happy to re-open it if someone still thinks it's good to work on this.

If anyone is about to pick this issue up to fix it, make sure to test first if you can reproduce the problem in the latest version before you start to work on it.

Thanks!
Sebastiaan on behalf of Umbraco HQ.
