### ISSUE TITLE
v8: Update navigation icons in package section

### ISSUE THREAD

**Issue by bjarnef** [umbraco/Umbraco-CMS#4387]
Should we updated the navigation icons in package section to something else instead of two "add" icons?

![image](https://user-images.githubusercontent.com/2919859/52178496-a0bd8800-27cf-11e9-8dae-35318d9b67f6.png)

E.g. `icon-cloud-upload` for local package install and `icon-categories`, `icon-inbox-full`, `icon-inbox`, `icon-utilities` or another icon for created packages.
https://nicbell.github.io/ucreate/icons.html

![image](https://user-images.githubusercontent.com/2919859/52178549-67d1e300-27d0-11e9-94b1-a4a9658f29c5.png)

**Comment by nul800sebastiaan** [comment]
Sounds like a good idea, I'll have to discuss with the team soon, will get back to you!

**Comment by nul800sebastiaan** [comment]
@bjarnef Sorry for the late reply, this is all good, go for it! 👍

**Comment by nul800sebastiaan** [comment]
Fixed in https://github.com/umbraco/Umbraco-CMS/pull/4588
