### ISSUE TITLE
V8: A few issues with dashboards

### ISSUE THREAD

**Issue by abjerner** [umbraco/Umbraco-CMS#4390]
I love the work being done recently with dashboards, and the ability to create them from either code or `package.manifest` files. I know the work may still be work in progress, but I've stumbled upon a few issues.

### Localization
According to [the package.manifest specification](http://json.schemastore.org/package.manifest), the `name` property of a dashboard is mandatory. But I can't find anywhere in the code this value is actually used.

On the other hand, when adding a dashboard from C#, neither the `IDashboard` or `IDashboardSlim` interfaces describes a `Name` property.

The `GetDashboards` in the `DashboardService` class specifically uses the alias of the dashboard to look up the translation of said alias in the `dashboardTabs` group.

**Proposal:**
- the `package.manifest` specification should be updated so the `name` property is no longer mandatory.
- the `GetDashboards` method should be updated so the name of a dashboard is used directly if specified, but attempts to find a translation for the alias if the name isn't specified.

### Weight

When creating a dashboard from C#, we can decorate the class with an attribute like `[Weight(10)]` to control the order of the tabs that should make up the dashboard.

The same is possible with by specifying a `weight` property in `package.manifest` files - but the `package.manifest` specification hasn't been updated to support this.

**Solution:**
- update `package.manifest` to include the `weight` property - I've created a PR for this here: https://github.com/SchemaStore/schemastore/pull/629

### EditorModelEventManager

The event for when the dashboards of a section is sent to the backoffice is not triggered. I've made a PR for that here: https://github.com/umbraco/Umbraco-CMS/pull/4364

The PR should fix so that the event is now triggered, but the event has another problem, as the model is just a collection of the tabs that should make up the dashboard. As such, the model doesn't expose which section is being returned. I believe information about the section (primary the alias) being rendered would be useful.

**Comment by warrenbuckley** [comment]
@abjerner thanks for the feedback

## Localization
Originally when I done this I was porting the existing logic over from the XML and `name` made sense. But I forgot to update/remove the shcmea so it matches.

To me specifying a `name` property to a dashboard does not make sense and counterintutive to omit the property in order for localization to work. It then gets people to try to get into good habits and use localization in my opinion.

I have documenation on Dashboards done yesterday thats live and ready to go
https://our.umbraco.com/Documentation/Extending/Dashboards/index-v8

If you still disagree then lets see if we can figure something out.

## Weight
I see the `Weight` attribute in the JSON SchemaStore has been merged in so good stuff 👍 

## EditorModelEventManager
I will look into this PR #4364 next & test it to get it merged in. Think it was an oversight when some changes was made to dashboards when SlimModel was introduced.

**Comment by warrenbuckley** [comment]
@bjarnef I have added a PR to SchemaStore to remove name and add in a missing propery for the access array to grant or deny specific user groups.

**Comment by warrenbuckley** [comment]
@bjarnef also left a comment on the PR #4364 but will close this issue up as the other bits are done

**Comment by bjarnef** [comment]
@warrenbuckley I guess you wanted to mention/tag @abjerner 😁

**Comment by abjerner** [comment]
@warrenbuckley I still think the option for specifying a name could make sense.

IMO there are plenty of use cases, where you as a developer won't need to localize the tab name. Say I have a package where the tab name is also the package name, so it will be the same regardless of the selected language. Or when developing a custom dashboard for a client, it may also not be necessary to localize the name.

As things are right now, I'll have to add a language file with a translation. To me, it would be a lot simpler if I could just specify the tab name via `package.manifest` or via C#. If I actually do need to localize the tab name, I could omit specifying the name, and Umbraco will automatically lookup the translation based on the alias as it is now.

The same applies to trees, and perhaps other areas of Umbraco as well.
