### ISSUE TITLE
Grid Layout - row configs with more than 12 rows, will spill over the enclosing property group

### ISSUE THREAD

**Issue by RobertCopilau** [umbraco/Umbraco-CMS#4398]
![{E066A9A1-729D-4D3C-9C83-1DB2C41DE6E4}.png.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5b151a952d7cd20011c4533d/125516c66e82c728ace21e0d46f3b1ca75d4a2f0aeb8f214f604d4d97d627450645d807323c8b20c9d1058555e2b3baa345c125abca7de39baa47c32d5065ebe957f5566c36f44aeec851cba55ec24884a85b6bd8b49c5bd3471b18e9d532c5c5446dda0006ceacc09da52e449e14754a1173f61ee77347943931e703e26.jpg)

**Comment by RobertCopilau** [comment]
![{E066A9A1-729D-4D3C-9C83-1DB2C41DE6E4}.png.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5b151a952d7cd20011c4533d/125516c66e82c728ace21e0d46f3b1ca75d4a2f0aeb8f214f604d4d97d627450645d807323c8b20c9d1058555e2b3baa345c125abca7de39baa47c32d5065ebe957f5566c36f44aeec851cba55ec24884a85b6bd8b49c5bd3471b18e9d532c5c5446dda0006ceacc09da52e44ae94754a1173f61ee7734784791177c3e26.jpg)

**Comment by bergmania** [comment]
PR: https://github.com/umbraco/Umbraco-CMS/pull/4429

**Comment by warrenbuckley** [comment]
All merged in
