### ISSUE TITLE
On a new page save and preview action, page acts as published if you just close a preview tab in a browser

### ISSUE THREAD

**Issue by bsubasic** [umbraco/Umbraco-CMS#4399]
Reproduction
------------

If you create a new page in Umbraco, fills some data and just save a page, you can preview it by clicking on the preview button and that is fine. If you don't exit the preview screen on the left sidebar close button, but just close the preview tab in a browser you will end up with a page acting as published (it will appear on the frontend where it shouldn't be listed, as it is not published yet).

I found the problem is with the UMB_PREVIEW cookie which stores the value of preview_xxxxx.config file name, created in the App_Data/preview folder during the preview process. This file stores the data for the preview. My routine is just to close a tab after previewing instead of clicking on the exit preview button in the left sidebar. Here is the problem, as there are additional functionality bound to this button which is deleting the preview_xxxxx.config file and the UMB_PREVIEW cookie. If someone doesn't leave the preview page on the exit button as I do, the cookie stays active and preview.config files accumulate in the preview folder without deletion on each next preview. Unpublished page starts to act as published and it is displayed on the frontend but it shouldn't be.

### Bug summary

A previewed page will acts as a published page only on the computer/browser which has initialized previewing as it is controlled by UMB_PREVIEW cookie existence. But App_Data/preview folder which is on the server will be affected by the accumulation of the preview data files not deleted on a regular preview exit.

### Specifics

Umbraco 7.13.1 assembly 1.0.6949.28284
Chrome Version 71.0.3578.98 (Official Build) (64-bit)

### Steps to reproduce

1. Create a new page of any type (page type with template)
2. Fill some required fields and save it.
3. Click on the preview button and verify your page with a new input data.
4. Now close that preview tab in a browser and don't exit on a close button in the left sidebar
5. Verify that your page isn't published on the info tag
6. That page now acts as published (you can access it directly with the page URL). A better example is if you have a blog landing page which loads child blog article pages and displays them on the page. This previewed page would be included as it is published, with a regular resolved URL which can be visited.

### Expected result

I would expect if I close my preview page/tab, no matter which way, that a page stays saved and unpublished, and not to be displayed on the frontend as it is a regular published page.

### Actual result

A saved page has been loaded as IPublishedContent, but it wasn't published.

**Comment by nul800sebastiaan** [comment]
Hey there @bsubasic - I understand the problem and I think this relates to the preview badge being hidden due to something in your templates. 

When you're in preview mode, Umbraco injects some HTML into all of your pages to show that you're still previewing, you can find this HTML in `umbracoSettings.config`: 

```
    <PreviewBadge>
      <![CDATA[
      <a id="umbracoPreviewBadge" style="z-index:99999; position: absolute; top: 0; right: 0; border: 0; width: 149px; height: 149px; background: url('{0}/assets/img/preview-mode-badge.png') no-repeat;" href="#" OnClick="javascript:window.top.location.href = '{0}/preview/end?redir={1}'"><span style="display:none;">In Preview Mode - click to end</span></a>
    ]]></PreviewBadge>
```

I would recommend you adjust if for your site so it shows up properly.

**Comment by bsubasic** [comment]
Thanks, I didn't know that option exists.

**Comment by bsubasic** [comment]
Hi @nul800sebastiaan, I found this extension method in the source code

 ```/// <summary>
        /// Will render the preview badge when in preview mode which is not required ever
        /// unless the MVC page you are using does not inherit from UmbracoTemplatePage        
        /// </summary>
        /// <param name="helper"></param>
        /// <returns></returns>
        /// <remarks>
        /// See: http://issues.umbraco.org/issue/U4-1614
        /// </remarks>
        public static MvcHtmlString PreviewBadge(this HtmlHelper helper)
```
I'm not using `UmbracoTemplatePage` but `UmbracoViewPage` in my view templates, so I suppose I need to use this HtmlHelper explicitly on a layout page. Why this option doesn't exist on the `UmbracoViewPage` as well?

 It's not intuitive that we have to do this for every project if we use `UmbracoViewPage`.

Thanks

**Comment by nul800sebastiaan** [comment]
That should also work just fine:

![image](https://user-images.githubusercontent.com/304656/52268974-2d398900-293d-11e9-99f3-ecd1ea8c041d.png)

**Comment by bsubasic** [comment]
Yes, it works.

**Comment by bythewiseman** [comment]
Apologies for adding a comment here, as I couldn't find another report of this and not for Umbraco 13.

This issue is still persistent with Umbraco 13. Both myself and client did not see the new blue banner at the bottom of the page, and the "End" button is seriously hidden bottom right.

This led to the issue that when my client closed their tab, but didn't close the browser window, the UMB_PREVIEW session cookie persisted and kept the site in preview mode despite being the live Urls and not preview Urls..

Maybe a change to the preview code would be to make sure the Url contains "/umbraco/preview/?id=" or to have the cookie an array of Ids for the pages the user wanted to preview but no other pages?

**Comment by marcloveUSN** [comment]
I have just reported this again for Umbraco 17:

https://github.com/umbraco/Umbraco-CMS/issues/23505

So some of my questions still remain:

Has this been removed by mistake or removed for a reason?

Would you recommend that we implement this ourselves to detect the "UMB_PREVIEW" cookie and indicate that the site could be showing unpublished content?
