### ISSUE TITLE
Umbraco Logs : Illegal characters in the path error is reported but character or the path is not logged.

### ISSUE THREAD

**Issue by rohitcbms** [umbraco/Umbraco-CMS#4400]
At many occasions we have observed problem reported with illegal characters in the path. But neither the character nor the path is reported in the logs. 
Both the character and the path should be reported when this error is logged.

**Comment by nul800sebastiaan** [comment]
Hey @rohitcbms - make sure to start a topic on the forum at https://our.umbraco.com to get some help with your problem!

Thanks.

**Comment by rohitcbms** [comment]
@nul800sebastiaan : This issue has already been discussed a lot. Can you please discuss about this issue with : Jesper Mayntzhusen?

**Comment by netaddicts** [comment]
Hi @nul800sebastiaan, I agree with OP, suggesting to re-open this issue, we've seen this also happening in our production site (load balanced, on version 7.12.3), and with no extra information to provide to the core team as nothing gets logged extra
Happy to provide a log file of that specific day we've encountered zillions of these errors in the log file if that would help

**Comment by netaddicts** [comment]
For reference, here's the thread on our: https://our.umbraco.com/forum/using-umbraco-and-getting-started/94945-failed-to-determine-if-request-was-client-side

**Comment by nul800sebastiaan** [comment]
Happy to re-open. If someone could investigate where the error comes from and figure out where in the code it was introduced (7.10 seems a candidate, looking at the forum post) then that would be awesome.\
Maybe increasing the log level to `Info` would help, not sure? The string `Failed to determine if request was client side` could be coming from our code base so that might be a good starting point.

I've marked this as "Up for grabs" so that you or someone else coming along could create a pull request for it.

**Comment by jmayntzhusen** [comment]
It fails in this one: https://github.com/umbraco/Umbraco-CMS/blob/dev-v7/src/Umbraco.Core/UriExtensions.cs#L144 

Seems the only reason it logs this error in later versions is that it simply wasn't aware of it failing before:
https://github.com/umbraco/Umbraco-CMS/compare/release-7.7.13...dev-v7#diff-3219a95da4fccaf596fecf4308a183a3

Still don't know what kind of url triggers the error though, but hopefully if someone has this issue they can debug the above 🙂

**Comment by nul800sebastiaan** [comment]
Thanks @jmayntzhusen - I would suggest updating the log message there to add the URL / path so that we can figure out what is "illegal". 

Would be really happy to merge a PR for that!

**Comment by nul800sebastiaan** [comment]
This issue has been in the `up for grabs` state for quite a while now and it seems nobody is ready to pick this one up.

For now we'll close this issue to prevent the list of `up for grabs` from becoming very stale. We're happy to re-open it if someone still thinks it's good to work on this. 

If anyone is about to pick this issue up to fix it, make sure to test first if you can reproduce the problem in the latest version before you start to work on it.

Thanks!
Sebastiaan on behalf of Umbraco HQ.

**Comment by jpinto3488** [comment]
issue still occurring on our website. running umbraco 7.12.4 on umbraco cloud pro plan. It is very problematic as it is actually filling our logs with something like 100 logs every 10 seconds.

**Comment by stevemegson** [comment]
This appears to have been fixed in 7.15.0 (see #5019). The fix changes the logging level to Debug and adds the URL to the message in case you do want to see the problem URLs.
