### ISSUE TITLE
v8: Redirect management is not working

### ISSUE THREAD

**Issue by nul800sebastiaan** [umbraco/Umbraco-CMS#4402]
When renaming pages in v8, I would expect a redirect to be created from the old URL to the new one. This is currently not working. 

It seems that the `RedirectTrackingComponent.Initialize()` method currently doesn't fire so the event handlers are not hooked up to do URL tracking.

**Comment by kjac** [comment]
Oh my. `RedirectTrackingComposer` is registering `RelateOnCopyComponent` instead of `RedirectTrackingComponent`. That took me way too long to track down for such a silly error.

I'll submit a PR soon.

**Comment by kjac** [comment]
PR in #4411
