### ISSUE TITLE
v8 alpha.58.2029 : after doing a rollback, history is blank

### ISSUE THREAD

**Issue by soreng** [umbraco/Umbraco-CMS#4405]
![image](https://user-images.githubusercontent.com/359492/52216812-6a4b4000-2897-11e9-8381-b8d53ec1eb2b.png)

I have to reload the backoffice to see the history. There don't seem to be any (javascript) errors.

**Comment by bergmania** [comment]
PR: https://github.com/umbraco/Umbraco-CMS/pull/4421

**Comment by bjarnef** [comment]
@bergmania does the PR also fix the console error when selecting a rollback version from the dropdown, where the repeater seems to have a duplicate and before actually trigger rollback?

**Comment by bergmania** [comment]
@bjarnef, I don't think so, but have not tested for that issue.

**Comment by warrenbuckley** [comment]
All tested & code reads fine - merged in
