### ISSUE TITLE
v8: OrderedCollectionBuilderBase<> AppendAfter should be InsertAfter

### ISSUE THREAD

**Issue by mattbrailsford** [umbraco/Umbraco-CMS#4406]
After looking to insert an item to a Collection, I could find Insert and InsertBefore but I could't find an InsertAfter. After digging into the code, it appears InsertAfter is name AppendAfter. I think this should be InsertAfter for consistency. Append should only be used to append an item on to the very end.

**Comment by nul800sebastiaan** [comment]
Sounds like a good idea, I'll have to discuss with the team soon, will get back to you!

**Comment by zpqrtbnk** [comment]
team approves ;-)

**Comment by zpqrtbnk** [comment]
commit 7863cd3ab7 - done, closing
