### ISSUE TITLE
v8: Updated WebCompositionExtensions to expose TreeCollectionBuilder

### ISSUE THREAD

**Issue by mattbrailsford** [umbraco/Umbraco-CMS#4408]
It would be nice to have a `Trees()` extension on the `WebCompositionExtensions` class to be able to programatically add a tree. This is required for Fluidity.

**Comment by mattbrailsford** [comment]
See #4394 for some additional context

**Comment by Shazwazza** [comment]
Those extension methods are really syntactic sugar, you can always access the collection builders with the longer syntax like:

`composition.WithCollectionBuilder<TreeCollectionBuilder>()`

I've added the `Trees()` shorthand method though.

See PR https://github.com/umbraco/Umbraco-CMS/pull/4568, that should solve this

**Comment by warrenbuckley** [comment]
All good & merged in :)
