### ISSUE TITLE
v8: Don't allow folder select in package options view

### ISSUE THREAD

**Issue by bjarnef** [umbraco/Umbraco-CMS#4409]
In Package options view it shouldn't allow to select folders (which also seems to use wrong folder icon in node preview). Maybe it should also only allow to select file(s) of specific extensions (.cs, .cshtml, .dll)?

![image](https://user-images.githubusercontent.com/2919859/52228253-2ade1d00-28b2-11e9-96bf-4049915b7f65.png)

**Comment by kjac** [comment]
@bjarnef why shouldn't it be allowed? Doesn't it work when the package is generated or..?

**Comment by bjarnef** [comment]
@kjac as the description text says, this could be a `.cshtml` (maybe also `.vbhtml` file), so og doesn't seem it should be possible to select folders and e.g. file types as `.css` and `.js`.

**Comment by nul800sebastiaan** [comment]
Fixed in https://github.com/umbraco/Umbraco-CMS/pull/4424/files
