### ISSUE TITLE
v8: Path to file in packager use wrong icon for folders

### ISSUE THREAD

**Issue by bjarnef** [umbraco/Umbraco-CMS#4410]
In the package section when creating a package, one can select multiple files or folders to include, but it seems both folders and files use same icon in node preview. At the selected folders should use the folder icon.

![image](https://user-images.githubusercontent.com/2919859/52228477-bfe11600-28b2-11e9-8deb-d0c8f2123796.png)

**Comment by bjarnef** [comment]
It seems when icon attribute is set it use the one and since the file picker submit only set the push the id (path to view file) to the array - not the node obj which include icon and other properties.

https://github.com/umbraco/Umbraco-CMS/blob/temp8/src/Umbraco.Web.UI.Client/src/views/packages/edit.controller.js#L208-L214

```
<umb-node-preview
    ng-if="vm.package.files"
    ng-repeat="file in vm.package.files"
    icon="'icon-document'"
    name="file"
    allow-remove="true"
    on-remove="vm.removeFile($index)">
</umb-node-preview>
```

In e.g. insertcodesnippet it submit node object:
https://github.com/umbraco/Umbraco-CMS/blob/temp8/src/Umbraco.Web.UI.Client/src/views/common/infiniteeditors/insertcodesnippet/insertcodesnippet.controller.js#L123-L127

**Comment by bjarnef** [comment]
Furthermore e.g. partial views use `icon-article` so I think this icon should be reflected in the node preview instead of the generic `icon-document`.

**Comment by Shazwazza** [comment]
added to up for grabs

**Comment by nul800sebastiaan** [comment]
This issue has been in the `up for grabs` state for quite a while now and it seems nobody is ready to pick this one up.

For now we'll close this issue to prevent the list of `up for grabs` from becoming very stale. We're happy to re-open it if someone still thinks it's good to work on this.

If anyone is about to pick this issue up to fix it, make sure to test first if you can reproduce the problem in the latest version before you start to work on it.

Thanks!
Sebastiaan on behalf of Umbraco HQ.
