### ISSUE TITLE
v8: Allow creation of all types of content in root if unset

### ISSUE THREAD

**Issue by clausjensen** [umbraco/Umbraco-CMS#4414]
If no content types have been defined with the 'Allow in root' setting - all content types should be allowed when creating root content.

It makes very little sense for new developers that they cannot create content of the content type they just created if they did not see and set the 'Allow in root' setting while creating it.

As soon as this setting has been used on at least one document type, it should however be enforced to only allow selected types as root content.

**Comment by kjac** [comment]
I've got this. I'm assuming this should also be extended to moving/copying/restoring content.

Fun fact: This is already the case for media (although it doesn't work for move/copy).

**Comment by kjac** [comment]
PR in #4418

**Comment by clausjensen** [comment]
@kjac Thanks for the PR!! 😄 haha I somehow just _knew_ you would pick this up .. actually thought about pinging you, but figured you would snatch it up anyways 😃

**Comment by kjac** [comment]
Hahaha! I'm all in it for the editor experience 😆

**Comment by warrenbuckley** [comment]
All tested & fixed. Thanks @kjac
