### ISSUE TITLE
v8: Set root node name in file picker

### ISSUE THREAD

**Issue by bjarnef** [umbraco/Umbraco-CMS#4417]
When specifying e.g. `treeAlias` in file picker and the tree nodes are limited, maybe it should show this root node or be an option to set this?

```
function openViewPicker() {
    const controlPicker = {
        title: "Select view",
        section: "settings",
        treeAlias: "partialViewMacros",
        entityType: "partialView",
        onlyInitialized: false,
        filter: function (i) {
            if (i.name.indexOf(".cshtml") === -1 && i.name.indexOf(".vbhtml") === -1) {
                return true;
            }
        },
        filterCssClass: "not-allowed",
        select: function (node) {
            const id = unescape(node.id);

            //vm.macro.view = id;
            $scope.model.macro.view = "~/Views/MacroPartials/" + id;

            $scope.model.macro.node = {
                icon: node.icon,
                name: $scope.model.macro.view
            };

            //$scope.model.submit($scope.model); 

            editorService.close();
        },
        close: function () {
            editorService.close();
        }
    };
    editorService.treePicker(controlPicker);
}
```

![image](https://user-images.githubusercontent.com/2919859/52246786-5d563d00-28e7-11e9-9325-d23346861ea0.png)

**Comment by kjac** [comment]
Isn't that what the heading is for? The one that says "Select view" right now?

**Comment by nul800sebastiaan** [comment]
We had a chat about it and the conclusion was: where is says "Select view" now should be "Select partial view macro file". So instead of adding yet another heading, let's make the generic heading be actually useful. 

I've marked this as "Up for grabs" so that you or someone else coming along could create a pull request for it.

**Comment by kjac** [comment]
PR in #5064
