### ISSUE TITLE
Split IContent and IContentType

### ISSUE THREAD

**Issue by zpqrtbnk** [umbraco/Umbraco-CMS#4425]
ContentBase is still caching ContentTypeBase, so... need to split for real

**Comment by zpqrtbnk** [comment]
Work in progress, in branch `temp8-contentAndType`

**Comment by bergmania** [comment]
Looks good so far, but why not just add the method in `ContentTypeBaseServiceProviderExtensions` on the class itself instead of making a extension method?

**Comment by zpqrtbnk** [comment]
'cos the implementation of the method does not depend on the interface implementation? and we don't have default interface method implementation in c# 7

**Comment by zpqrtbnk** [comment]
PR #4445 now ready for review. All tests green, UI seems to work. Using `Current` in some places where... injecting would not work (extension methods etc) or would be quite painful.

**Comment by zpqrtbnk** [comment]
did a bit of cleanup as per Shan suggestion and merged, closing
