### ISSUE TITLE
V8: TextString limitation

### ISSUE THREAD

**Issue by nielslyngsoe** [umbraco/Umbraco-CMS#4427]
When entering more characters than the defined limit for a TextString the characters gets removed automatically.

This is a bad approach since you as an editor expects it to accept what you have entered/pasted.

Instead of removing characters i want it to give a validation error when the number of characters exceed the allowed number of characters.

As well I dont want to see the "characters lefts"-indication before it gets relevant.
A proposal would be to only show the character indication when there is more than limit-100 characters represented in the given input-field. When it exceeds the limit it should be highlighted, but not limit the user-input.

**Comment by zpqrtbnk** [comment]
tested ok, merged
