### ISSUE TITLE
This document is published but its url would collide with content (error)

### ISSUE THREAD

**Issue by harsheet** [umbraco/Umbraco-CMS#4436]
Whenever we **create a new content**, we are getting this error intermittently on **Links**, but it just goes away on refreshing the page.

I am using Version 7.11.1

Reproduction
------------

Create a content, click save and publish, check the link url.

### Expected result

After saving the content, it should give the correct url.

### Actual result

After saving the content, it is giving the following error - 

This document is published but its url would collide with content (error)

On refreshing the page, it shows the correct url.

**Comment by nul800sebastiaan** [comment]
Hi @harsheet, if you can reproduce this reliably somehow on a fresh 7.13 install then we'd love to know. We don't see this behavior so there must be something different in your setup that would help us find the problem if you can point it out.
