### ISSUE TITLE
v8 Content picker has `((` and `))` around my node name in content picker

### ISSUE THREAD

**Issue by nul800sebastiaan** [umbraco/Umbraco-CMS#4441]
When I have multiple languages configured a content picker where I've picked the `Blog` node. The node name is displayed as `((Blog))` instead of `Blog`.

![image](https://user-images.githubusercontent.com/304656/52333802-68e85780-29fe-11e9-9b79-8891617eb28f.png)

**Comment by nul800sebastiaan** [comment]
Note: when I have only 1 language configured, this looks fine, it just shows `Blog`, as soon as I add another language it changes to `((Blog))` again.

**Comment by kjac** [comment]
Anything that calls the entity or content API is prone to this kind of errors. 

I wrote up a prototype last night for a fix that might just turn out quite neat. I'll polish it over the weekend and get back to you.

**Comment by kjac** [comment]
PR in #4507

**Comment by warrenbuckley** [comment]
@nul800sebastiaan I think there was some reasoning behind this for the double `{{ }}` that I vaguely remember @zpqrtbnk told me about - would just get some clarification or background on this first.

**Comment by kjac** [comment]
It happens when the content and entity mappers can't figure out what culture to map.

**Comment by Shazwazza** [comment]
Have added comments/etc... to the PR so we can discuss more there.
