### ISSUE TITLE
V8: Unable to select which content types shouldn't show content apps

### ISSUE THREAD

**Issue by sofietoft** [umbraco/Umbraco-CMS#4444]
I've created a fairly simple Content App.
Everything is working fine.

But, when I try to use **hide** the Content App on Content Type `homePage` (alias of my home page Document type), nothing happens.

Reproduction
------------
This is the Content App package.manifest:
```
{
    // define the content apps you want to create
    "contentApps": [
      {
        "name": "Word Counter", // required - the name that appears under the icon
        "alias": "wordCounter", // required - unique alias for your app
        "weight": 0, // optional, default is 0, use values between -99 and +99 to appear between the existing Content (-100) and Info (100) apps
        "icon": "icon-calculator", // required - the icon to use
        "view": "~/App_Plugins/WordCounter/wordcounter.html", // required - the location of the view file
        "show": [
          "-content/homePage" // hide for content type 'homePage'
        ]
      }
    ],
    // array of files we want to inject into the application on app_start
    "javascript": [
        "~/App_Plugins/WordCounter/wordcounter.controller.js"
    ]
}
```

The **show** part of the JSON file, is where I try to "exclude" the homePage content type, as per the Documentation here: https://our.umbraco.com/Documentation/Extending/Content-Apps/index-v8#limiting-according-to-content-type 

I expected that after re-building my site, the Content App, WordCounter would only show on content that's NOT using the homePage document type.

What did happen, is that the Content App is still visible on all my content.

Is the Documentation out-of-date? 
Has something changes, and this now needs to be done in a different way?

**Comment by bergmania** [comment]
@sofietoft, I can't reproduce.
I can't see the content app on any content using the specified `json`
If i change the show section to the following, it works as expected

```
...
        "show": [
                "-content/homePage", // hide for content type 'homePage'
                "+content/*"
            ]
....
```

**Comment by sofietoft** [comment]
@bergmania 
I know. Just realized I needed to add the second line `"+content/*"`.

Sorry for the trouble.
