### ISSUE TITLE
v8 Services like ContentService and MediaService default to user 0, but -1 is now the default

### ISSUE THREAD

**Issue by nul800sebastiaan** [umbraco/Umbraco-CMS#4446]
Trying to do something like 

```
var imageMedia = _mediaService.CreateMedia(fileName, new Guid("c5259303-ca36-467c-8b16-7082e283e6d0"), "Image");
imageMedia.SetValue(_contentTypeBaseServiceProvider, "umbracoFile", fileName, imageStream);
_mediaService.Save(imageMedia);
```

Results in a null reference error when `MediaValueSetBuilder.GetValueSets` tries to do `m.GetCreatorProfile(_userService).Name.Yield()` - since the media creator doesn't exist.

**Comment by Shazwazza** [comment]
Yup, but that's just my own crappy code not null checking, general rule is that you always need to null check the result of a method which this is not doing. Like i said in the core channel, there's lots of things that are not being null checked in this method.

**Comment by kjac** [comment]
Still... would make sense either to remove the default user ID or replace it with `Core.Constants.Security.SuperUserId`?

**Comment by Shazwazza** [comment]
Null checks have been added in case there is some odd data coming in  ed5023e4319fd8b0119937bfd62e89562721d12d, pretty sure @warrenbuckley has a PR to resolve all of the 0 or -1 values with constants

**Comment by clausjensen** [comment]
@warrenbuckley could you confirm?

**Comment by warrenbuckley** [comment]
Yeh this has been done in this PR & merged in @clausjensen so believe this can be closed then?

https://github.com/umbraco/Umbraco-CMS/pull/4448
