### ISSUE TITLE
v8: Missing icons in users sections

### ISSUE THREAD

**Issue by bjarnef** [umbraco/Umbraco-CMS#4450]
In latest changes in `temp8` branch it seems some icons are missing in users section. Icons are both missing at user sections and in overlay.

![image](https://user-images.githubusercontent.com/2919859/52351011-1886ef00-2a2a-11e9-8f7f-af36c96215fe.png)

![image](https://user-images.githubusercontent.com/2919859/52351061-3e13f880-2a2a-11e9-8eb0-aa5b78466db3.png)

Furthermore when clicking edit media start node, the listview icon is not relative to the listview tree node as it used to be.

![image](https://user-images.githubusercontent.com/2919859/52351208-8cc19280-2a2a-11e9-9021-f16ab6612678.png)

**Comment by bjarnef** [comment]
In the overlay it repeat sections:

```
<ul class="umb-tree">
    <li ng-repeat="section in vm.sections" class="umb-tree-item">

        {{section | json}}

        <div style="padding: 5px 10px;" ng-class="{'umb-tree-node-checked': section.selected }">
            <a href="" ng-click="vm.selectSection(section)">
                <i class="icon umb-tree-icon {{section.icon}}"></i>
                <span>{{ section.name }}</span>
            </a>
        </div>
    </li>
</ul>
```

But for some reason all icon property of each object now returns `icon-section null`:

```
{ "name": "Indhold", "cssclass": null, "alias": "content", "routePath": null, "icon": "icon-section null", "selected": true }
```

**Comment by bjarnef** [comment]
It seems the mapping only handle mapping of Name and Alias for `IBackOfficeSection`.

https://github.com/umbraco/Umbraco-CMS/blob/temp8/src/Umbraco.Web/Models/Mapping/SectionMapperProfile.cs#L11-L18

so in section picker it never has a value for `cssclass`:

https://github.com/umbraco/Umbraco-CMS/blob/temp8/src/Umbraco.Web.UI.Client/src/views/common/infiniteeditors/sectionpicker/sectionpicker.controller.js#L79-L83

**Comment by kjac** [comment]
Or maybe just remove `umb-node-preview` from the section list? Since the sections have no icons, does it make sense to cook some up for this?

**Comment by bjarnef** [comment]
@kjac it is just to make the section picker consistent with other pickers, which also have icons.

So not only here:

![image](https://user-images.githubusercontent.com/2919859/52374262-1d18cb00-2a5d-11e9-80c5-768a3ec9f1eb.png)

also here:

![image](https://user-images.githubusercontent.com/2919859/52374300-3588e580-2a5d-11e9-87e1-be30a3f1ef8d.png)

if this shouldn't icons anymore, it need something else when sections are not selected.

But again more or less every parts of the UI with selection (mostly trees) use node/tree icons and a checkmark when selected.

**Comment by kjac** [comment]
@bjarnef I agree with the consistency argument. However, as sections no longer have any icons, there's no additional information conveyed adding section icons here; adding them would be purely for consistency with the rest of the UI - which isn't a bad reason at all. 

Since the icons won't add any meaningful information to the users, there's no reason why the sections should have distinct icons. Given that I will add a generic icon for sections and do the necessary clean-up to remove the remnants of custom icon sections. I'm thinking `icon-application-window`. Thoughts?

![image](https://user-images.githubusercontent.com/7405322/52395314-f20a9780-2aad-11e9-96ad-f10894b9ad68.png)

**Comment by kjac** [comment]
PR in #4470

**Comment by kjac** [comment]
Also PR for the tree item annotations (listview etc.) in #4497
