### ISSUE TITLE
Upgrade from v7.10.4 to v7.13.2 causing publish error

### ISSUE THREAD

**Issue by jennyferhubac** [umbraco/Umbraco-CMS#4461]
Upgrade the Umbraco CMS in Visual Studio 2017 to latest (v.7.13.2) by typing "Update-Package UmbracoCms" in Package Manager Console.

Build is ok and was able to launch UI normally, but when trying to publish
getting a "Could not load type '**umbraco.dialogs.notifications**'" error.
I tired to exclude notifications.aspx in Umbraco/Dialogs but had another issue with
Umbraco/Settings/EditDictionaryItem.aspx : "Could not load '**umbraco.settings.EditDictionary'**"
I exclude that aspx and the project successfully publish.

Any issue with me excluding the 2 files?

I am pretty sure the error was caused by the upgrade because prior to doing it, I was still able to publish the Umbraco web app successfully.

Please let me know how to resolve this.  This is my first time upgrading an Umbraco project.

Thank you very much in advance.

**Comment by nul800sebastiaan** [comment]
Hi there @jennyferhubac - make sure to get some help on the forum for this problem: https://our.umbraco.com

Thanks!

**Comment by jennyferhubac** [comment]
@nul800sebastiaan ok thank you.
