### ISSUE TITLE
V8 enabling WebApi attribute routing breaks PostSave endpoint

### ISSUE THREAD

**Issue by nathanwoulfe** [umbraco/Umbraco-CMS#4464]
If attribute routing is enabled, posting to /UmbracoApi/Content/PostSave (ie attempting to save/publish a content item) fails. According to the trace, the request fails due to user being null in a call to Umbraco.Core.Security.ContentPermissionsHelper.CheckPermissions.

[Full trace](https://gist.github.com/nathanwoulfe/26f58d630cfa81fcb9d134780ec2e100)

Stepping back through the trace it appears the missing user parameter is from WebSecurity, referenced [here](https://github.com/umbraco/Umbraco-CMS/blob/8329097974b56da85d16549e09b9b92ba85539db/src/Umbraco.Web/Editors/Filters/ContentSaveValidationAttribute.cs#L197)

From what I can tell, this only happens on the PostSave call, I can successfully save media, for example, with no issues.

Reproduction
------------

- To reproduce, create a composer/component combo, and in the component's Initialize method, call             GlobalConfiguration.Configuration.MapHttpAttributeRoutes();
- In the backoffice, attempt to save a content node
- Get an error

- Remove the GlobalConfiguration line
- In the backoffice, attempt to save a content node
- No more error

**Comment by Shazwazza** [comment]
Something funky is definitely going on:

![image](https://user-images.githubusercontent.com/1742685/52753455-cad23e00-304a-11e9-8bf1-5167c0fd5340.png)

Investigating now

**Comment by Shazwazza** [comment]
Yikes that was sort of a critical issue, have fixed in rev: f814a80ab7fb1451d7b2abbd274ac6ace1338691

The ContentSaveValidationAttribute (which is a singleton) was being created with a request based object, thus capturing an old HttpContext :( not sure how this problem didn't rear it's head before. Great find! all fixed

**Comment by nathanwoulfe** [comment]
Sweet, thanks Shan! 👍
