### ISSUE TITLE
V8: RenderMacro doesnt work?

### ISSUE THREAD

**Issue by sofietoft** [umbraco/Umbraco-CMS#4466]
I've been testing Umbraco 8 with the [Creating a Basic site](https://our.umbraco.com/documentation/Tutorials/Creating-Basic-Site/Articles-Parent-and-Article-Items) tutorial in the Docs.

When I need to create a **Partial view Macro File** and render it in my template, I run into issues.

Reproduction
------------
Following this section from the Docs article:
> Click on the Settings menu from the top menu and then hover over the Partial View Macros Files node to get the more menu ... then click New partial view macro from snippet. Select the "List Child Pages Ordered By Date" and then name it "listArticles" and save.

![2019-02-07_1036](https://user-images.githubusercontent.com/24529086/52402329-4ae52a80-2ac4-11e9-84b0-057de487c259.png)

This generates the following Macro:
```
@inherits Umbraco.Web.Macros.PartialViewMacroPage
@using Umbraco.Web

@*
    This snippet makes a list of links to the of children of the current page using an unordered HTML list.

    How it works:
    - It uses the Children method to get all child pages
    - It then uses the OrderByDescending() method, which takes the property to sort. In this case the page's creation date.
    - It then generates links so the visitor can go to each page
*@

@{ var selection = Model.Content.Children.Where(x => x.IsVisible()).OrderByDescending(x => x.CreateDate).ToArray(); }

@if (selection.Length > 0)
{
    <ul>
        @foreach (var item in selection)
        {
            <li><a href="@item.Url">@item.Name</a></li>
        }
    </ul>
}
```

Going back to my template, following these intructions:
> click the Insert Macro button, choose the ListArticles macro we just created 

![2019-02-07_1035](https://user-images.githubusercontent.com/24529086/52402321-46b90d00-2ac4-11e9-9672-6faeb7350743.png)

the following snippet is added: `@Umbraco.RenderMacro("listArticles")`

### Result

When I view the frontend now, I hit this YSOD:
![2019-02-07_1015](https://user-images.githubusercontent.com/24529086/52402112-b5e23180-2ac3-11e9-9b0f-037a33ce8d81.png)

So, either Macros do not work, or the auto-generated snippets don't work 🤔

**Comment by clausjensen** [comment]
I'm seeing that this works in my site... Sofie can't make it work. Seems like we're doing exactly the same and on same build.

Someone needs to confirm whether this issue exists or not!

**Comment by warrenbuckley** [comment]
@clausjensen I can repro this problem with commit hash `f7ee8c08998cb4d71ca7d12031ee334e2ecb98e7`

**Comment by bergmania** [comment]
PR: https://github.com/umbraco/Umbraco-CMS/pull/4511
