### ISSUE TITLE
V8: Switch language on content TREE vs on content WINDOW

### ISSUE THREAD

**Issue by sofietoft** [umbraco/Umbraco-CMS#4468]
When working with Language Variants in Umbraco 8, you can switch between languages two different places: In the Content Tree (`mculture`) and on the content itself (`cculture`).

Reproduction
------------

### Scenario 1:

**English** selected in the Content Tree.
Nothing selected in the Content Window (e.g. haven't touched the dropdown in the Content Window).
URL: `?mculture=en-US`
When I switch to another language in the Content Tree, the language in the Content Window is changed accordingly - the URL is updated accordingly: `?mculture=da`

### Scenario 2:

**English** selected in the Content Tree.
**English** selected in the Content Window.
URL: `?mculture=en-US&cculture=en-US`
Switching to another language in the Content Tree, ONLY changes the language in the Content Tree - the language int he Content Window remains the same: `?mculture=da&cculture=en-US`

When clicking through content nodes on this URL `?mculture=da&cculture=en-US`, the content nodes it shows me in the window are the English ones, even though the ones I click in the tree are the Danish ones.

As this is a bit hard to explained, I've made a gif, that hopefully gives a better picture of what is happening:

![language-not-changing-correctly](https://user-images.githubusercontent.com/24529086/52414343-534d5d80-2ae4-11e9-9de6-4a23fbe021b5.gif)

In the first part, no language have been selected in the content window.
Half way through, I change language in the content window, and that's when it becomes a bit confusing.

### Expected result

Having a language selected in the Content Tree (e.g. English), I would expect, that when I click the content nodes for that language, I am shown the content in the correct language (e.g. English).

This is ONLY the case, once no language has been selected in the Content Window at any time.

### Actual result

Instead, when I have English selected in the content tree, and danish selected in the content window, I will always be shown the Danish content, even though I am clicking on the English content nodes.

**Comment by kjac** [comment]
Good catch @sofietoft! 

This gets even more confusing when you mix culture variant and invariant content in the same tree - the content editor then changes between the default language for the culture invariant content and the chosen "cculture" for the culture variant content:

![dont-retain-cculture-before](https://user-images.githubusercontent.com/7405322/52429713-e7c7b800-2b04-11e9-9a2a-43d92117b602.gif)

Fortunately it's super simple to fix. I'll push a PR momentarily.

**Comment by kjac** [comment]
PR in #4472
