### ISSUE TITLE
v8: Selection and bulk actions need to be consistent

### ISSUE THREAD

**Issue by bjarnef** [umbraco/Umbraco-CMS#4476]
In users section the selection doesn't match the updated selection styles in e.g. listview in content and media. The same applies to the bulk action buttons in the sub header.

![image](https://user-images.githubusercontent.com/2919859/52449841-0051c580-2b39-11e9-9462-d66ed0896121.png)

![image](https://user-images.githubusercontent.com/2919859/52449934-4d359c00-2b39-11e9-99d1-a84f0c8fe5ac.png)

![image](https://user-images.githubusercontent.com/2919859/52449948-5a528b00-2b39-11e9-84d0-0b8bddffe793.png)

Also note that the users section has both a list and grid layout mode, but at the moment the layout selector in users section is broken, so only the grid/card layout is available, but it is fixed in this PR https://github.com/umbraco/Umbraco-CMS/pull/4458

Furthermore the "groups" might also need some adjustments.
Eg. "create group" button is green, "create user" button is purple and "create member" + "create" in content and media listview is white. Besides that the "create package" and "add language" buttons also have the green/success state. I think these need to be same color.

![image](https://user-images.githubusercontent.com/2919859/52450076-dfd63b00-2b39-11e9-8ee0-1f5b5b224b48.png)

Also note the different colors of "clear selection" and "delete" button if mainly content/media/member listview, users views and user groups. I think this need to be more consistent throughout the UI.

![image](https://user-images.githubusercontent.com/2919859/52450185-40fe0e80-2b3a-11e9-967b-608fa1b14cf0.png)

![image](https://user-images.githubusercontent.com/2919859/52450236-799de800-2b3a-11e9-8cd5-7710529cfc8f.png)

At the moment there are three different selection styles: content/media/member listview (which doesn't use checkboxes, except "select all"), checkmark icon in users layout (where it doesn't use a checkbox for "select all" in list layout mode) and then checkboxes in user groups.

In e.g. users grid/card layout mode the entire box (except the checkmark) navigate to the page (user profile), while in content/media/member listview only the name navigate to the page and then rest of the box toggle the selection.

**Comment by kjac** [comment]
I think (hope?) @nielslyngsoe is working hard on rolling out the latest UX overhaul to the entire backoffice?

**Comment by bjarnef** [comment]
I guess the "create" buttons incl.  "add language" and "create package" need to use `btn-action` instead of `btn-white` and `btn-success`?

**Comment by warrenbuckley** [comment]
All done & merged in
