### ISSUE TITLE
v8 Packages section loads to a blank screen after a local package is installed

### ISSUE THREAD

**Issue by Shazwazza** [umbraco/Umbraco-CMS#4478]
v8 Packages section loads to a blank screen after a local package is installed

also after you uninstall the package section loads without any buttons 

![image](https://user-images.githubusercontent.com/1742685/52462364-e19a1000-2bc6-11e9-8002-94e451c0c6ea.png)

**Comment by bjarnef** [comment]
I have also noticed this sometimes happens when just accessing packages section, but in that case it seems to help by refreshing browser window.

It might be related to localization of the navigation items.

**Comment by Shazwazza** [comment]
The problem is actually an intermittent problem, it doesn't just occur after package install. It occurs about 50% of the time when you just refresh the browser on the package section.

The issue is something to do with animation changes. I've screen captured the issue: 

This shows the issue and the selector that is hiding this section is something to do with animations

![image](https://user-images.githubusercontent.com/1742685/52768308-4d75f000-3081-11e9-9b20-c1a23eea68b2.png)

This shows what happens when you toggle that selector

![image](https://user-images.githubusercontent.com/1742685/52768347-6383b080-3081-11e9-81ae-96e93bd690c4.png)

This shows how it's supposed to be:

![image](https://user-images.githubusercontent.com/1742685/52768385-79917100-3081-11e9-9aa4-a2d192e60050.png)

**Comment by bjarnef** [comment]
@Shazwazza from your screenshots it seems to be an issue because it has the class `ng-hide` and not `ng-hide-animate`, which trigger this rule as it is highlighted.

I guess the `ng-hide:not(.ng-hide-animate)` is an addition in v8.

I guess it is an issue if using `ng-hide` (or maybe also `ng-show`) which add the class `ng-hide` based on the condition. I guess it has this rule is for e.g. inifinite editing to hide the dialog and first show it while animating?

**Comment by Shazwazza** [comment]
I changed it to an ng-if="showNavigation" to see what would happen, so the problem is actually an issue with the $scope.navigation.length, meaning that the navigation isn't being passed into this component correctly ... investigating.

aha, its because the umbeditornavigation directive sets showNavigation to false when there aren't any nav items on init, but init can occur before nav items are passed to the directive, so the directive isn't really listening for object changes being passed to it. basically the whole 'showNavigation' property is silly - it can either be set based on a watch or we replace the showNavigation check simply with `navigation.length > 1` ... .which i think is correct. 

will fix

**Comment by Shazwazza** [comment]
Actually, it turns out there are other problems with this directive, not only is the showNavigation like this but also the showMoreButton based on this, neither of these will work correctly if the nav items are changed or added later.  Would be nicer to change this to an actual component, but for now we'll need to put a watch on the nav items length.

**Comment by Shazwazza** [comment]
PR here, my tests work https://github.com/umbraco/Umbraco-CMS/pull/4599

**Comment by Shazwazza** [comment]
Well my PR did fix part of the problem, but not the entire problem, after installing a package it still loads to a blank screen - though at least the menu items are there now. Will investigate.

**Comment by ttngocthao** [comment]
My issue is  there is nothing on the left corner. Console log is 'Possibly unhandled rejection: The user object is invalid, the remainingAuthSeconds is required.'
<img width="960" alt="issue" src="https://i.ibb.co/71G8wJg/issue.png">
Could anyone please advise me how to fix this?
Many thanks
