### ISSUE TITLE
v8: Image cropper slider does not work appropriate

### ISSUE THREAD

**Issue by bjarnef** [umbraco/Umbraco-CMS#4483]
It seems there are some issues with image cropper slider in crop mode in v8 (maybe also in v7).

When dragging the slider all to the left, the image is not allways zoomed out, but it seems to update when start dragging the image.

![2019-02-08_12-01-04](https://user-images.githubusercontent.com/2919859/52474709-856cc700-2b99-11e9-8474-8924e25e5f0d.gif)

It would also be great to update the slider to be consistent with the new slider using `umb-range-slider` component. I had a play with that which work, but it had a few issues, which might be some issues with calculation.
https://github.com/umbraco/Umbraco-CMS/issues/3985

**Comment by kjac** [comment]
I did some fixing for the slider zoom thing for V7 in #4270. I'll have a look at this later and see what's going on.

**Comment by kjac** [comment]
What you're experiencing is in part a problem with the initial zoom, in part due to the low update frequency of the slider.

PRs for those in #4593 and #4594 respectively.

**Comment by nul800sebastiaan** [comment]
Awesome it all works again now and it actually works in Firefox now 🔥
