### ISSUE TITLE
v8: Missing localization of content apps

### ISSUE THREAD

**Issue by bjarnef** [umbraco/Umbraco-CMS#4485]
It seems the content apps is missing to be localized, e.g. "Content" -> "Indhold" in Danish.

![image](https://user-images.githubusercontent.com/2919859/52475186-11cbb980-2b9b-11e9-8c20-3c1aa1d5db6f.png)

![image](https://user-images.githubusercontent.com/2919859/52475221-2c059780-2b9b-11e9-84b4-726b72093bbc.png)

**Comment by kjac** [comment]
PR in #4549
