### ISSUE TITLE
v8: Missing localization users status label

### ISSUE THREAD

**Issue by bjarnef** [umbraco/Umbraco-CMS#4486]
It seems the status labels in users sections needs to be localized, e.g. "Inactive" and "Active".

![image](https://user-images.githubusercontent.com/2919859/52475304-6707cb00-2b9b-11e9-87e7-0a941bde964b.png)

![image](https://user-images.githubusercontent.com/2919859/52475332-7dae2200-2b9b-11e9-9d6a-36bd16acabbf.png)

Furthermore the values in the sort filter can be localized and in status filter incl. "All".
For groups it is probably not easy to localize since these values are dynamic, but it could translate the default values: "Administrators", "Editors", "Writers", "Translators" and maybe also "Sensitive data".

**Comment by kjac** [comment]
Got most of this working, PR imminent 👍

**Comment by kjac** [comment]
PR in #4510

**Comment by kjac** [comment]
@clausjensen I've got a feeling this can be closed now 😄

**Comment by nul800sebastiaan** [comment]
Whoops, forgot to close, thanks!

Fixed in https://github.com/umbraco/Umbraco-CMS/pull/4510
