### ISSUE TITLE
V8: Default Tour

### ISSUE THREAD

**Issue by warrenbuckley** [umbraco/Umbraco-CMS#4490]
From the latest temp8 - the tour no longer displays after a fresh install.

Additionally, the help drawer (found by clicking the help icon) no longer list tour items.

**Comment by bergmania** [comment]
PR: https://github.com/umbraco/Umbraco-CMS/pull/4535

**Comment by warrenbuckley** [comment]
Yep all good & well done for fixing the textarea stuff too
