### ISSUE TITLE
v8: Media picker doesn't show Folder names, so it's pretty difficult to find the folder I need

### ISSUE THREAD

**Issue by nul800sebastiaan** [umbraco/Umbraco-CMS#4494]
I have ~50 folders in my media library and wanted to pick something from a specific folder. In order to figure out which folders there are I need to hover over each one of them one by one since the default view hides the titles, see screenshots

![2019-02-09_122136](https://user-images.githubusercontent.com/304656/52523380-0ce93180-2c91-11e9-9175-6908e8be2b1a.png)

**Comment by kjac** [comment]
PR in #4504

**Comment by alicia123456** [comment]
I'm seeing the same issue with files ... In Media Picker, I can't see the file name until I hover over the icon. I'm working in the 8.0.1 Sample Site on a local PC.
![Filenames_not_Visible](https://user-images.githubusercontent.com/49405580/55734374-6f3e8400-59ed-11e9-9b64-cdb0bf03f0aa.png)
