### ISSUE TITLE
v8: Content App dropdown and Actions dropdown partially disappear behind list view bar

### ISSUE THREAD

**Issue by nul800sebastiaan** [umbraco/Umbraco-CMS#4495]
When you're on a list view and have scrolled down, there's a sticky bar at the top, this one hides the new Content App dropdown and also the Actions dropdown as can be seen in the following screenshots.

![image](https://user-images.githubusercontent.com/304656/52523857-54be8780-2c96-11e9-99b6-b96e6225c5b9.png)

![image](https://user-images.githubusercontent.com/304656/52523859-55efb480-2c96-11e9-8aa9-a55186c5e340.png)

**Comment by kjac** [comment]
PR in #4503
