### ISSUE TITLE
v8: Remove ie7 related CSS hacks

### ISSUE THREAD

**Issue by BatJan** [umbraco/Umbraco-CMS#4499]
A brief description of your feature request goes here.

While poking around the codebase I noticed that there are still some IE7 related hacks in some of the files, so I'll suggest we remove these.

How can you help?
-------------------------------

~~I'll do~~ I have made a PR removing the IE7 related hacks in #4500

**Comment by bjarnef** [comment]
@nul800sebastiaan I guess this one can be closed? :)
