### ISSUE TITLE
v8: Remove uneeded CSS vendor prefixes

### ISSUE THREAD

**Issue by BatJan** [umbraco/Umbraco-CMS#4501]
A brief description of your feature request goes here.

Having a look at the belle codebase I stumbled upon quite a few places where vendor prefixes are being used, which is no longer needed.

How can you help?
-------------------------------

I'll help out by doing the cleanup and submit a PR for it.

**Comment by nul800sebastiaan** [comment]
Fixed in https://github.com/umbraco/Umbraco-CMS/pull/4502
