### ISSUE TITLE
Field "template" is listed multiple times in the index set "InternalIndexSet". Please ensure all names are unique, Provider=InternalIndexer

### ISSUE THREAD

**Issue by vonbv** [umbraco/Umbraco-CMS#4512]
Using Umbraco 7.12.3

Every time we save a content, we get the error as stated in the title. The error is not limited to the InternalIndexSet but to other index set as well . So we get multiple similar errors when saving a content. I checked for duplicate property field (alias) and we only have one "template". I'm sure of this as I checked the **cmsPropertyType** table. 

I thought the "template" is a reserved word, there's no documentation about it. So I renamed the alias to something else and the error went away.

Is this a bug or an intended behavior (with a reserved word)?
 
I found this related issue: https://github.com/umbraco/Umbraco-CMS/pull/2347/commits/e1b6997ef7bb836d56ac8be0ce0c4fde3cf6f3e9

**Comment by nul800sebastiaan** [comment]
Yep. Reserved keywords are: `id`, ` isPublished`, ` key`, ` level`, ` nodeName`, ` nodeType`, ` nodeTypeAlias`, ` pageTitle`, ` parentID`, ` path`, ` sortOrder`, ` template`, ` updateDate`, ` urlName`, ` writerID`, ` writerName`

**Comment by Swimburger** [comment]
@nul800sebastiaan I just ran into the same issue with 'key', can we have the Umbraco interface prevent us from using those alias's? 
I currently have a conflicting alias but I'm afraid to change it since we already have content using the field.
