### ISSUE TITLE
V8 - overlay options gone?

### ISSUE THREAD

**Issue by nathanwoulfe** [umbraco/Umbraco-CMS#4517]
Maybe not a bug but an architecture change? Previously have been able to trigger different overlays by setting the 'view' property of the overlay model (the one passed into the umb-overlay directive) to the appropriate value - [refer to current docs for examples](https://our.umbraco.com/apidocs/ui/#/api/umbraco.directives.directive:umbOverlay)

These options don't seem to exist in v8? What's the alternative? Should they still exist?

Can't find when they were removed either, git history isn't showing anything...

**Comment by nul800sebastiaan** [comment]
@nathanwoulfe It's a bit difficult for me to determine what you're missing, maybe you can explain the specific use-case you're looking for so I can ask around and see where stuff has moved to. I suspect it has to do with infinite editing where things have moved around a lot.

**Comment by bjarnef** [comment]
@nathanwoulfe it doesn't seem the `umb-overlay` component has changed from v7 to v8, except that it in v8 now has a `parentScope` property.

https://github.com/umbraco/Umbraco-CMS/blob/dev-v7/src/Umbraco.Web.UI.Client/src/common/directives/components/overlays/umboverlay.directive.js

https://github.com/umbraco/Umbraco-CMS/blob/temp8/src/Umbraco.Web.UI.Client/src/common/directives/components/overlays/umboverlay.directive.js

**Comment by nathanwoulfe** [comment]
That was a pretty weak effort on my part, that's what happens when I create issues at bed time.

In v7, the umb-overlay directive works like this:

```html
<umb-directive ng-model="vm.overlay" ng-view="vm.overlay.view" ng-show="vm.overlay.show">
</umb-directive>
```
```js
this.myAction = () => {
  this.overlay = {
    // lots of properties
    view: 'contentpicker' // or mediapicker, userpicker etc
  }
}
```

This opens a content picker overlay, using the html found at /views/common/overlays/contentpicker/contentpicker.html, where the path is constructed in the overlay directive.

In v8, the same example errors out as the contentpicker view cannot be found, because it not longer exists. Compare the two:
https://github.com/umbraco/Umbraco-CMS/tree/dev-v7/src/Umbraco.Web.UI.Client/src/views/common/overlays

https://github.com/umbraco/Umbraco-CMS/tree/temp8/src/Umbraco.Web.UI.Client/src/views/common/overlays

I'm sure it's still possible to launch a picker overlay (or hopefully it is!), and it's just the approach has changed. Still find it a bit odd that I can't find anything in the history responsible for removing the views.

**Comment by rasmusjp** [comment]
@nathanwoulfe there's a new `editorService` (https://github.com/umbraco/Umbraco-CMS/blob/temp8/src/Umbraco.Web.UI.Client/src/common/services/editor.service.js) in V8 that is used to open the infinite editors.

E.g. you can open the media picker by calling

https://github.com/umbraco/Umbraco-CMS/blob/21d1b7c5997cac3b6c64ae01ce443736b8b87d83/src/Umbraco.Web.UI.Client/src/common/services/editor.service.js#L31-L40

or a custom editor

https://github.com/umbraco/Umbraco-CMS/blob/21d1b7c5997cac3b6c64ae01ce443736b8b87d83/src/Umbraco.Web.UI.Client/src/common/services/editor.service.js#L68-L78

**Comment by nathanwoulfe** [comment]
That's the one! Looks like that also removes the need for using umb-overlay in the markup, which is excellent.
