### ISSUE TITLE
v7: User history showing even if it's empty

### ISSUE THREAD

**Issue by BatJan** [umbraco/Umbraco-CMS#4523]
A brief description of the issue goes here.

Under the user profile it says "Your recent history" even though there are no entries yet.

### Bug summary

So when one clicks the "user avatar" it currently looks like this

![user-before](https://user-images.githubusercontent.com/1932158/52588232-5033d380-2e3c-11e9-8a57-097425304dd9.png)

I suggest it's either removed until there are some relevant entries that will be rendered or perhaps we need to add a text saying "You have not made any changes yet" or something like that.

I will add a PR for this shortly.

**Comment by nul800sebastiaan** [comment]
Fixed in https://github.com/umbraco/Umbraco-CMS/pull/4524
