### ISSUE TITLE
v8: Sub header actions in infinite editing need adjustments

### ISSUE THREAD

**Issue by bjarnef** [umbraco/Umbraco-CMS#4529]
It seems when opening inifinite editing the actions in the sub header need some adjustments.

It seems to look okay in English, but in Danish it is more an issue, because of longer action buttons for "Compositions" and "Reorder".

However to reproduce with English as backoffice language:
- On a content node with a media picker (with a selected image) click "edit"
- On media node go to info tab and open media type

![image](https://user-images.githubusercontent.com/2919859/52598264-86318180-2e55-11e9-998f-fab7d37f7cd5.png)

Furthermore when clicking "edit data type" it seems the sub header has a higher z-index than the backdrop.

![image](https://user-images.githubusercontent.com/2919859/52598369-c98bf000-2e55-11e9-9db0-8ddd916da315.png)

In "reorder mode" the sub header" then cover the first tab/group order.

![image](https://user-images.githubusercontent.com/2919859/52598478-225b8880-2e56-11e9-8532-c778264a7a52.png)

**Comment by kjac** [comment]
#4503 might fix the second issue listed here with the z-index.

**Comment by nul800sebastiaan** [comment]
This issue has been in the `up for grabs` state for quite a while now and it seems nobody is ready to pick this one up.

For now we'll close this issue to prevent the list of `up for grabs` from becoming very stale. We're happy to re-open it if someone still thinks it's good to work on this. 

If anyone is about to pick this issue up to fix it, make sure to test first if you can reproduce the problem in the latest version before you start to work on it.

Thanks!
Sebastiaan on behalf of Umbraco HQ.
