### ISSUE TITLE
v8: Header input need right margin

### ISSUE THREAD

**Issue by bjarnef** [umbraco/Umbraco-CMS#4530]
It seems the header input in e.g. translation section and in package section needs a bit right margin.

![image](https://user-images.githubusercontent.com/2919859/52598665-c7766100-2e56-11e9-8102-92fab41edec5.png)

![image](https://user-images.githubusercontent.com/2919859/52598682-dd842180-2e56-11e9-986b-2732edd6142b.png)

**Comment by kjac** [comment]
PR in #4567

**Comment by nul800sebastiaan** [comment]
Fixed in https://github.com/umbraco/Umbraco-CMS/pull/4567
