### ISSUE TITLE
Tags remain $dirty after save and publish

### ISSUE THREAD

**Issue by drummerboy46** [umbraco/Umbraco-CMS#4544]
Add and removing tags from the tags property and then saving and publishing should result in the ability to move away from the page without being prompted of unsaved changes.

What did I expect?
To be able to move away from page.

What happened?
Prompted of unsaved changes.

**Comment by nul800sebastiaan** [comment]
Version please?

**Comment by drummerboy46** [comment]
7.13.2

**Comment by agrath** [comment]
I can't reproduce this issue in the latest 8.7.0

**Comment by agrath** [comment]
Also tested in 7.15.4 and can't reproduce there either

**Comment by drummerboy46** [comment]
The problem was happening on any page that contained a macro. It was the macro that was causing $dirty to remain. I fixed this in a contribution to 7.15.5. https://github.com/umbraco/Umbraco-CMS/issues/6366
