### ISSUE TITLE
V8: "User Profile" panel doesn't close when you open Help panel.

### ISSUE THREAD

**Issue by PeteDuncanson** [umbraco/Umbraco-CMS#4545]
Back office of V8, click on the user profile on the right hand side and it opens the "users" panel.

Then click the "Help" button in the top right and it opens the Help panel under the user panel. Looks like the logic for shutting any that are open before opening another isn't setup. 

Ideally any of those three buttons in the top right should close the others I guess.

![image](https://user-images.githubusercontent.com/1674590/52646754-3dbca700-2edb-11e9-830f-8c3a123e52b4.png)

**Comment by nul800sebastiaan** [comment]
Thanks, we'll lump that in with the other issues of the help panel: https://github.com/umbraco/Umbraco-CMS/issues/3958
