### ISSUE TITLE
V8: Convert the accordian to use HTML Details element

### ISSUE THREAD

**Issue by PeteDuncanson** [umbraco/Umbraco-CMS#4546]
Seems a shame that the new "Details" element which would give standardised accordian functionality built into the browser hasn't been used in the new accordian. 

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/details

A good polyfill for it is available here: https://github.com/rstacruz/details-polyfill

Other polyfills are listed at the bottom of that page if needed.

Would need some rework of the classes etc. used on the current accordian but doable as a swap out I believe. Not sure how that component is built and if its all AngularJS tastic but it should be doable to swap it out.

**Comment by nul800sebastiaan** [comment]
Thanks Pete, should've be easy enough to swap out. 

However, things are moving fast. We no longer have collapsible elements for the past few days, instead there's additional navigation between different property groups.

**Comment by MMasey** [comment]
I realise that this is now closed, but if there is an eventuality where the HTML details element is taken advantage I've done some work with it in projects and have found the polyfills to be lacking a little bit in terms of accessibility. That said, I do have some code that can help with that so feel free to shout it my direction if you'd like another set of eyes.
