### ISSUE TITLE
V8 backoffice notification positioning still allows for vertical nav

### ISSUE THREAD

**Issue by nathanwoulfe** [umbraco/Umbraco-CMS#4548]
Backoffice notifications sit 80px off the left side of the browser on screens < 1101px wide - pretty sure that's a hangover from v7's vertical nav (obviously not a real notification):

![not a real notification](https://user-images.githubusercontent.com/3248070/52690525-b38f4400-2fa9-11e9-8842-2036243ddb5e.png)

I'm assuming that's not intentional, and notifications should be full-width on small screens - I'll fix this up, and anything other notification-related quick wins I find at the time.

**Comment by clausjensen** [comment]
Thanks @nathanwoulfe 😃 looking forward to a PR!

**Comment by nathanwoulfe** [comment]
@clausjensen there's one ready and waiting.  👍

**Comment by clausjensen** [comment]
fixed in https://github.com/umbraco/Umbraco-CMS/pull/4550
