### ISSUE TITLE
V8: TinyMCE does not sync data to angular store when dragged away in grid-editor

### ISSUE THREAD

**Issue by nielslyngsoe** [umbraco/Umbraco-CMS#4559]
if you enter data into a TinyMCE(RTE-editor) inside a Grid-Editor and moves the TinyMCE to another location (without blurring it first) it does not transfer the latest data to the Angular data store.

**Comment by RobertCopilau** [comment]
PR:https://github.com/umbraco/Umbraco-CMS/pull/5048

**Test Notes**
* Create a doc type with a grid
* Create a node based on that doc type
* Create a few RTE's and move them around and make sure the editable part of the RTE does not disappear.
