### ISSUE TITLE
V8: Component / Composers mixing namespaces

### ISSUE THREAD

**Issue by mattbrailsford** [umbraco/Umbraco-CMS#4566]
In the V8 source there are namespaces for `Composing` and `Components` however there appears to be crossover in the classes in these namespaces. ie, the 'IComposer` and `IUserComposer` interfaces are in the `Components` namespace. I think these need going through and making sure they are in the correct namespaces.

**Comment by zpqrtbnk** [comment]
Yes - will clean up.

**Comment by zpqrtbnk** [comment]
PR #4573 - what do you think @mattbrailsford ?

**Comment by mattbrailsford** [comment]
Replied in PR #453 but overall, much better.

**Comment by mattbrailsford** [comment]
Just gonna reference #4376 is kind of a linked issue (more mixed namespaces)

**Comment by zpqrtbnk** [comment]
the PR for this issue has been merged - closing
