### ISSUE TITLE
v8 TinyMce property editor alias has "v3" hard coded which is incorrect

### ISSUE THREAD

**Issue by Shazwazza** [umbraco/Umbraco-CMS#4569]
This is a legacy thing but the tinymce property editor alias is "Umbraco.TinyMCEv3" which isn't right since we are on v4.x.

We can make this change in v8.0 if we have time but we'll also have to make a data migration for this too.

**Comment by bergmania** [comment]
v5 is available, so maybe we should to it, when we upgrade to v5?

**Comment by Shazwazza** [comment]
v5 was only in preview a very short time ago, i tried the to implement it but it had far too many changes to try to be ready for v8. Would rather not ship umbraco again with 2x tinymce implementations - thats an insane amount of files :)

**Comment by bergmania** [comment]
@Shazwazza , what to you think is the solution. Just to rename to `Umbraco.TinyMCE`?

**Comment by nul800sebastiaan** [comment]
Yeah, `Umbraco.TinyMCE` should be fine! 👍 

I think we only had the v3 version so we could run v2 and v3 side-by-side.

**Comment by bergmania** [comment]
PR: https://github.com/umbraco/Umbraco-CMS/pull/4604

**Comment by nul800sebastiaan** [comment]
Fixed in https://github.com/umbraco/Umbraco-CMS/pull/4604
