### ISSUE TITLE
Preview state lingers to the live site

### ISSUE THREAD

**Issue by RobertCopilau** [umbraco/Umbraco-CMS#4579]
If you preview a page and exit the preview by closing the window, your site is now in preview mode with the preview badge (top right corner) until you either click the badge or preview a page and exit the preview mode the "right way" by clicking the X on the left bar of the preview window.

https://www.useloom.com/share/5fac918d62044d5884053687815a5f5d

**Comment by bergmania** [comment]
Is this not the intention. That's why we have the badge I think?

**Comment by nul800sebastiaan** [comment]
Correct, this is intentional! :)
