### ISSUE TITLE
Redirects management is broken

### ISSUE THREAD

**Issue by clausjensen** [umbraco/Umbraco-CMS#4580]
Redirect management dashboard seems to show only # and no links to destinations.
The redirects are actually working fine behind the scenes - it's just this dashboard where they are broken.

**Comment by nul800sebastiaan** [comment]
There's two issues here it seems, looks like the response from SearchRedirectUrls is wrong.

![image](https://user-images.githubusercontent.com/304656/52793285-afc4f580-306d-11e9-829a-09330f886baa.png)

Then I started with a clean database, added a doctype and allowed a child doctype, that all made redirects work until.. I added a language (only had one) and made my doctype variant. 

At that point renaming pages doesn't add anything to the redirect urls, so I made it not variant again, then all the redirect urls disappeared.

Now it's making new redirects again as long as I'm working with an invariant site.

**Comment by nul800sebastiaan** [comment]
Oh hang on, seems like there's a PR for this already: https://github.com/umbraco/Umbraco-CMS/pull/4413

**Comment by mvanhelmont** [comment]
@nul800sebastiaan On todays release the issue still exists. But having a look at the commits on file https://github.com/umbraco/Umbraco-CMS/blob/7b55d2f1b2fce1a3bb8eadbd32028598785658e3/src/Umbraco.Web/Models/Mapping/RedirectUrlMapperProfile.cs

you can see that there was a small mistake by using Id instead of ContentId.

**Comment by clausjensen** [comment]
fixed in: https://github.com/umbraco/Umbraco-CMS/pull/4753

**Comment by Shazwazza** [comment]
Have merged and tested, all good now

**Comment by Shazwazza** [comment]
(and cherry picked to 8.0.1)
