### ISSUE TITLE
Image Cropper doesn't appear in V8 if configured under Media Type

### ISSUE THREAD

**Issue by dzordzs** [umbraco/Umbraco-CMS#4581]
### Bug summary
If you define crops in Media Type for Image, they won't show up in the Media Section. 

**Steps to reproduce:**
1. Open Image media type and edit umbracoFile property 
2. Add any crop to the property 
3. Go to any image in media section and you'll see that the crops are not there.

**Comment by clausjensen** [comment]
It seems that when viewing an existing cropper - the crops are not shown next to the image as expected.

When uploading a new image via the cropper - it works as expected.

**Comment by clausjensen** [comment]
Scratch that ... it may actually be that images created before adding crops to the image cropper datatype - will not have any cropping options.
An image uploaded _after_ I added in some crops on the datatype, has crops - and also gets any new crops I add.

**Comment by kjac** [comment]
@clausjensen that is exactly what I found too. There's a PR incoming 😄

**Comment by kjac** [comment]
PR in #4596

**Comment by nul800sebastiaan** [comment]
Fixed in https://github.com/umbraco/Umbraco-CMS/pull/4596
