### ISSUE TITLE
Image cropper cant switch between crops

### ISSUE THREAD

**Issue by clausjensen** [umbraco/Umbraco-CMS#4582]
If you define two crops on your image cropper, go to an image and set both crops.

Clicking from "no crops" to a crop - it will show the crop. Clicking back and then clicking the other crop - it will show that crop.

Clicking one crop - and then clicking the other crop - it doesn't show the second crop, but instead shows something broken that isn't either one of the crops.

![image](https://user-images.githubusercontent.com/1645360/52793061-23b2ce00-306d-11e9-99eb-bce6d48c8c85.png)

![image](https://user-images.githubusercontent.com/1645360/52793104-36c59e00-306d-11e9-8e67-995ce94b8728.png)

**Comment by kjac** [comment]
I've got this... PR incoming.

**Comment by kjac** [comment]
PR in #4595
