### ISSUE TITLE
v8 Setting usernameIsEmail to false doesn't work

### ISSUE THREAD

**Issue by nul800sebastiaan** [umbraco/Umbraco-CMS#4585]
I added `usernameIsEmail` to my `umbracoSettings.config` and set it to false, but it's still returning `true`. I touched the web.config and global.asax to force a reload but it keeps being `true`.

```
  <security>
    <!-- set to true to auto update login interval (and there by disabling the lock screen -->
    <keepUserLoggedIn>true</keepUserLoggedIn>

    <usernameIsEmail>false</usernameIsEmail>

    <!-- change in 4.8: Disabled users are now showed dimmed and last in the tree. If you prefer not to display them set this to true -->
    <hideDisabledUsersInBackoffice>false</hideDisabledUsersInBackoffice>

    <!-- set to true to enable the UI and API to allow back-office users to reset their passwords -->
    <allowPasswordReset>true</allowPasswordReset>
      
  </security>
```

**Comment by kjac** [comment]
Funny thing is it worked when I created #4383 😭 I'll have a look.

**Comment by kjac** [comment]
...still seems to work on the login screen. How have you been testing it, @nul800sebastiaan?

![username-is-email](https://user-images.githubusercontent.com/7405322/52867104-75785880-3140-11e9-8fa3-7cf49deb4cc0.gif)

**Comment by nul800sebastiaan** [comment]
what the... I must be stupid, I'll test again! I just tested with the config above, which looks identical to yours..

**Comment by nul800sebastiaan** [comment]
Works great now 🤦‍♂️  I must have been mixing up a few running sites or something. Thanks for fact-checking me @kjac !

**Comment by kjac** [comment]
No fair calling yourself stupid. How you manage all the stuff you do is beyond me.

You rock 👍

**Comment by nul800sebastiaan** [comment]
Haha thanks! I tried for at least 10 minutes to switch between true and false, I have no idea what I did wrong 😅
