### ISSUE TITLE
v8: Forms dashboard has minimum height

### ISSUE THREAD

**Issue by bjarnef** [umbraco/Umbraco-CMS#4587]
The Umbraco Forms installer dashboard has minimum height 800px, so on laptop you get some scrollbar, but it doesn't seem to be necessary.

![image](https://user-images.githubusercontent.com/2919859/52804356-51efd800-3084-11e9-83dc-2f890beefaf5.png)

Removing `min-height: 800px` from the inline styles.

```
max-width: 800px;
text-align: center;
margin: auto;
padding: 20px;
/* min-height: 800px; */
```

and then add `display: flex` or just class `flex` to parent which is the `ng-controller="Umbraco.Dashboard.FormsDashboardController" class="umb-dashboards-forms-install">`

and consider the put the inline style to the forms dashboard less file.

I think with this small change it looks much nicer.

![image](https://user-images.githubusercontent.com/2919859/52804754-4fda4900-3085-11e9-8c69-f0bda461cc4e.png)

**Comment by nul800sebastiaan** [comment]
Fixed in https://github.com/umbraco/Umbraco-CMS/pull/4589
