### ISSUE TITLE
Table Cell Highlighting with Umbraco 7

### ISSUE THREAD

**Issue by TomDaria** [umbraco/Umbraco-CMS#4591]
We are on v7.11.1. 
My users are reporting to me that since we upgraded from 7.5.9 to 7.11.1, while using the RTE, when they select multiple table cells, the cursor jumps around all over the place.
Cell highlighting is all over the place too and they don't know what they have or have not selected.

This issue is very easy to reproduce.
Launch Umbraco 7.11.1 and login to the Umbraco with a user who has Editor permissions or greater.
Add a table (ie 4x4) to an existing page and fill each cell with data.
Save and publish the page.
Now come back to the page and higlight all cell in column 1 and watch and see how cell highlighting is all over the place and cursor jumps all around.

Tom

**Comment by nul800sebastiaan** [comment]
That's annoying! I can repdroduce in 7.13.2 as well, but only in Chrome, Firefox seems to work fine.

I've marked this as "Up for grabs" so that you or someone else coming along could create a pull request for it.

**Comment by nul800sebastiaan** [comment]
FYI: I've just had a look in v8 and it works well there, so it seems like we should upgrade TinyMCE in v7, seems like a bug in the version of tiny included in v7.

**Comment by TomDaria** [comment]
Thank you Sebastiaan.

Have a fantastic weekend.

**Comment by ssougnez** [comment]
Hello,

I was about to create a new issue as I also have another problem with tinymce. However, I see that Sebastiaan proposed to update the version of tinyMce to 4.9.2. 

Therefore, could this issue related to the upgrade of tinymce instead of just fixing the CSS issue ? If yes, I could make a PR to update the version of tinymce.

For the record, my issue is that tinymce keeps adding non breaking spaces everywhere. Basically, when I type text normally in the RTE, there is no issue but if I make a tiny pause (like 300ms), a non breaking space is added. I noticed that with 4.9.3, the behavior is the same but when I resume typings, the non breaking space is replaced by a regular one. This seems pretty problematic to me. 

If someones types text slowly, he could end up with text full of "nbsp;" screwing up design.

**Comment by ssougnez** [comment]
Hello,

I've been looking in this issue for two reasons:

* I have a very annoying bug in tinymce, when I press space and wait for less than a second, the space becomes a "&nbsp;" but when I resume typing, the "&nbsp;" stays and is not converted back in a regular space. That could mess up a lot of layouts... (for me, it's a critical issue).
* When I try to select a table cell, I have no visual feedback.

For the first issue, I checked with version 4.9.3 of tinymce and I don't have the issue anymore, so I'll create a PR soon to update tinymce version.

For the second issue, it's weird that you don't have it in v8. Maybe you are using a different skin? Indeed, the skin used in Umbraco 7 has the following lines:

```
td.mce-item-selected, th.mce-item-selected {
    background-color: #39f!important;
}
```

However, when a cell is selected, no additional class is applied to it. However, an attribute called "data-mce-selected" is. The solution would then be to add:

`td[data-mce-selected="1"]`

As a rule but as the skin is delivered by tinymce, I don't think updating it directly is a good idea, we would probably lose it in case of upgrade.

Therefore, the solution I used in my project is to create a CSS with the aforementioned class and apply this CSS to my RTE data type. Works like a charm ;-) It's not the best but it's the less invasive one (I guess).

**Comment by nul800sebastiaan** [comment]
This issue has been in the `up for grabs` state for quite a while now and it seems nobody is ready to pick this one up.

For now we'll close this issue to prevent the list of `up for grabs` from becoming very stale. We're happy to re-open it if someone still thinks it's good to work on this. 

If anyone is about to pick this issue up to fix it, make sure to test first if you can reproduce the problem in the latest version before you start to work on it.

Thanks!
Sebastiaan on behalf of Umbraco HQ.
