### ISSUE TITLE
Table Cell Highlighting with Umbraco 7.11.1

### ISSUE THREAD

**Issue by TomDaria** [umbraco/Umbraco-CMS#4592]
We are on v7.11.1. 
My users are reporting to me that since we upgraded from 7.5.9 to 7.11.1, while using the RTE, when they select multiple table cells, the cursor jumps around all over the place.
Cell highlighting is all over the place too and they don't know what they have or have not selected.

This issue is very easy to reproduce.
Launch Umbraco 7.11.1 and login to the Umbraco with a user who has Editor permissions or greater.
Add a table (ie 4x4) to an existing page and fill each cell with data.
Save and publish the page.
Now come back to the page and higlight all cell in column 1 and watch and see how cell highlighting is all over the place and cursor jumps all around.

Tom

**Comment by nul800sebastiaan** [comment]
Duplicates https://github.com/umbraco/Umbraco-CMS/issues/4591
