### ISSUE TITLE
v8: Sticky bar with no content

### ISSUE THREAD

**Issue by bjarnef** [umbraco/Umbraco-CMS#4597]
In latest changes in `temp8` branch I noticed when scrolling a bit down the page it show the sticky bar, but it doesn't have any content on e.g. home node in default starter kit.

![image](https://user-images.githubusercontent.com/2919859/52823224-7499e500-30b4-11e9-9815-092879a92812.png)

![image](https://user-images.githubusercontent.com/2919859/52823247-867b8800-30b4-11e9-866f-29023afb6c5e.png)

**Comment by kjac** [comment]
@bjarnef I can't see that on the latest... is it's still an issue on the latest `temp8`?

![content-scrolling](https://user-images.githubusercontent.com/7405322/52851207-c9ba1300-3115-11e9-86da-519d3e132d43.gif)

**Comment by bjarnef** [comment]
@kjac does it makes a difference if the document type doesn't allow variant by culture?

**Comment by nul800sebastiaan** [comment]
I also don't see it when it's not a variant. I'll check out an install the starter kit though.

**Comment by nul800sebastiaan** [comment]
Comes into view when I scroll on Home to the grid: 

![image](https://user-images.githubusercontent.com/304656/52852161-1ef72400-3118-11e9-887e-b5bd8cecedd0.png)


Note: the starter kit doesn't install completely on the latest at the moment but it will install the content, it ends with an error after which you can delete the `Umbraco.SampleSite.dll` and you can at least see the tree has been populated.

**Comment by nielslyngsoe** [comment]
hi @bjarnef, I dont know the history for this one. But the bar you are seeing comes from the Grid-PropertyEditor. I think its suppose to have a "Order"-button in the right side. Can you describe your DocType and grid setup for us? Thanks

**Comment by bjarnef** [comment]
@nielslyngsoe it is just the default starterkit in v8 :)

**Comment by nielslyngsoe** [comment]
@bjarnef your right, sorry. Didn't spot that at first.

**Comment by kjac** [comment]
Pretty sure this is a the same as #4706 which has a PR in #4822

**Comment by nielslyngsoe** [comment]
linking with PR #4822
