### ISSUE TITLE
When saving values in a checkbox list they are reset!

### ISSUE THREAD

**Issue by KennethJakobsen** [umbraco/Umbraco-CMS#4601]
When saving values in a checkbox list they are reset!

Reproduction
------------

1. Create a doctype with a checkboxlist
2. Create doc using doctype
3. Check some items in the list
4. Save
5. Recheck list (Whoa no values are persisted)

### Bug summary

When saving values in a checkbox list they are reset!
![6299a88b-560c-479a-9196-49a0ef85ee51](https://user-images.githubusercontent.com/17765492/52847807-8491e300-310d-11e9-966c-61eb8a4679ff.GIF)

**Comment by bergmania** [comment]
@KennethJakobsen , can you specify version?

**Comment by KennethJakobsen** [comment]
@bergmania of course Umbraco 8.0.0-alpha.58.2258

**Comment by bergmania** [comment]
I have reproduced and fixed. We where saving wrong variable name

**Comment by KennethJakobsen** [comment]
![image](https://user-images.githubusercontent.com/17765492/52849983-afcb0100-3112-11e9-95c3-78bd42307177.png)
