### ISSUE TITLE
Image cropper positions image incorrectly

### ISSUE THREAD

**Issue by martinthogersen** [umbraco/Umbraco-CMS#4610]
We experience that images uploaded to Umbraco are positioned slightly to the right for some crops. Please see the attached screenshot. The cropsize is 367x229px, and the image is positioned slightly outside of the box to the right.

![image](https://user-images.githubusercontent.com/239008/52863896-3c88b580-3139-11e9-8034-95a43ca92207.png)

Reproduction
------------

We're able to reproduce this problem by uploading images and adding them to crops where the image has to be cropped by width. If it's cropped by height, everything works as it should.

This is tested in Umbraco version 7.31.1

**Comment by kjac** [comment]
This is fixed in #4270 for 7.14

**Comment by nul800sebastiaan** [comment]
Thank @kjac - indeed should be working nicely in 7.14 @martinthogersen ! 👍
