### ISSUE TITLE
v8: Remove OpenSans font

### ISSUE THREAD

**Issue by BatJan** [umbraco/Umbraco-CMS#4612]
A brief description of your feature request goes here.

Sebastiaan mentioned that it would make sense to get rid of the Open Sans font here https://github.com/umbraco/Umbraco-CMS/issues/4474#issuecomment-463696759 so that's what it's all about.

How can you help?
-------------------------------

I'll do a PR in which I remove the open sans font and reference the Lato font family where OpenSans was previously being used.

**Comment by BatJan** [comment]
@nul800sebastiaan This one is ready for review 😉

**Comment by nul800sebastiaan** [comment]
Fixed in https://github.com/umbraco/Umbraco-CMS/pull/4613
