### ISSUE TITLE
v8: Remove canvasdesigner.loader.js

### ISSUE THREAD

**Issue by BatJan** [umbraco/Umbraco-CMS#4614]
A brief description of your feature request goes here.

@nul800sebastiaan and I had a chat about the canvasdesigner.loader.js seemed to be legacy file, which is not in use so I suggest we get rid of them.

How can you help?
-------------------------------

I'll do a PR removing the file in question.

**Comment by nul800sebastiaan** [comment]
Fixed in https://github.com/umbraco/Umbraco-CMS/pull/4615
