### ISSUE TITLE
editor submit button won't work

### ISSUE THREAD

**Issue by gib65** [umbraco/Umbraco-CMS#4616]
Hello,

Please see the issue I reporter at the link below:

https://our.umbraco.com/forum/using-umbraco-and-getting-started//95779-submit-button-on-property-editor-doesnt-work

**Comment by nul800sebastiaan** [comment]
Hey @gib65 - that's annoying! Unfortunately it's a problem in your website and not what most people experience. If you've recently upgraded your website maybe something went wrong, I'd advice you to check out this blog post: https://cultiv.nl/blog/how-to-diagnose-umbraco-upgrade-problems/

Make sure to post back on the forum again if the problem persists so you can get some help with it. 

Ps, I just made sure that I can't reproduce the problem on 7.13.1 either:
![image](https://user-images.githubusercontent.com/304656/53948248-b2909480-40c7-11e9-9c4b-a8f444c91d55.png)
