### ISSUE TITLE
Allow crop image on user image upload

### ISSUE THREAD

**Issue by bjarnef** [umbraco/Umbraco-CMS#4618]
When uploading a new image for a user it would be great to be able to be able to crop the image Before upload, e.g. when the person is not in center of the image.

E.g. something like this.
https://shareurcodes.com/blog/create-a-jquery-image-upload-widget-with-preview-and-image-cropping-in-laravel

Here is a great demo which also allow to rotate image before upload.
https://shareurcodes.com/demos/jquery-image-upload

Furthermore I have thought about if there should be more options. At the moment you can remove the the gravatar image, but not refetch the image from gravatar.
So an option could also be that the link says "Select image" or "Select photo" which show an overlay with multiple options: Manual upload, Gravatar.. maybe in future options to select from Google, Twitter, Facebook or custom defined service.

**Comment by bjarnef** [comment]
I tried in v8 using `overlayService` prototyping this, instead of opening file upload when clicking "change avatar" it opens an overlay, where the editor can upload an image and afterwards change crop before submitting changes.

At the moment this is just some hardcoded values and using `<umb-image-crop>` inside the overlay. Furhtermore the white bordered circle is just some static styles for `.viewport:before`.

![image](https://user-images.githubusercontent.com/2919859/52915703-827b8000-32d7-11e9-9047-566c1e607055.png)

**Comment by bjarnef** [comment]
I made a bit more prototyping, where it uploads an image, which you would like to adjust the cropping before saving the avatar. At the moment it just upload the image after selecting, but doesn't actually not save the new cropping.

Not sure if is still should upload to avatar on upload or maybe first on submit - or if submit ust should update the cropping.

![2019-02-17_21-03-36](https://user-images.githubusercontent.com/2919859/52918469-97680b80-32f7-11e9-8b07-4a97eea771a9.gif)

**Comment by nul800sebastiaan** [comment]
It's a nice idea and the experiment looks good to me.

You've posted a lot of links and if you think any of them give a better experience then make sure to write your recommendation and why it is the best so we can give you some feedback on whether we agree. Otherwise, let's go with the prototype you've got.

I've marked this as "Up for grabs" so that you or someone else coming along could create a pull request for it.

**Comment by bjarnef** [comment]
@nul800sebastiaan the links were mostly to give some inspiration on how we can change this and make it possible to crop the avatar.

I am thinking of two approaches:
- Upload and auto crop like now and the option to crop the avatar afterwards like this example:
https://pqina.nl/slim/#form-post

- Upload image and show the image cropper in an overlay (like shown in the screenshots on this issue), where the default crop is set and the option to change cropping before save). Also this allow to open/edit the crop in an overlay later if needed like this example https://shareurcodes.com/demos/jquery-image-upload

In addition to the previous mentioned it could also allow to rotate the image as in this demo https://shareurcodes.com/demos/jquery-image-upload but it is a different feature and can always be implemented later.

**Comment by nul800sebastiaan** [comment]
If you can make this work then that would be awesome:

https://user-images.githubusercontent.com/2919859/52915703-827b8000-32d7-11e9-9047-566c1e607055.png

Otherwise the second option is a good start. 

I know the links are for inspiration but it would be really nice to not introduce any new dependencies on jQuery if we can avoid it.

**Comment by bjarnef** [comment]
@nul800sebastiaan yes, I shouldn't use jQuery, just Angular and traditional javascript.

Opening an overlay like this would be great.
https://shareurcodes.com/demos/jquery-image-upload

But I also like these examples, where it upload and crop on upload (like we have today) and then the option to remove image or edit the crop, but not necessarily in fullscreen mode - it could just be an overlay (using overlayService) for now.
https://pqina.nl/slim/#form-post
https://pqina.nl/doka/#0

**Comment by nul800sebastiaan** [comment]
Alright, pick one, try it out, show us that it works and we can evaluate.

**Comment by bjarnef** [comment]
I will, but I would like to make this work first 😁 
https://github.com/umbraco/Umbraco-CMS/pull/4487

**Comment by nul800sebastiaan** [comment]
This issue has been in the `up for grabs` state for quite a while now and it seems nobody is ready to pick this one up.

For now we'll close this issue to prevent the list of `up for grabs` from becoming very stale. We're happy to re-open it if someone still thinks it's good to work on this.

If anyone is about to pick this issue up to fix it, make sure to test first if you can reproduce the problem in the latest version before you start to work on it.

Thanks!
Sebastiaan on behalf of Umbraco HQ.
