### ISSUE TITLE
If Attribute Routing is enabled and a named route is used the backoffice breaks

### ISSUE THREAD

**Issue by martina-1995** [umbraco/Umbraco-CMS#4620]
If Attribute Routing is enabled 

        public void OnApplicationStarted(UmbracoApplicationBase umbracoApplication, ApplicationContext applicationContext)
        {
 		GlobalConfiguration.Configuration.MapHttpAttributeRoutes();
        }

And a named route is used (webapi)
[Route("votephoto", Name = "votephotoroute")]

The backoffice breaks with:
" System.ArgumentException: A route named 'votephotoroute' is already in the route collection. Route names must be unique.
Parameter name: name "

I've tried different names and deleted the bin/obj (just in case) but without success.
The only fix was to remove the Named Route and use an hardcoded link in the chstml.
I've asked on slack for this problem and the good Mads Krohn advised me to open an issue as it's a known bug.

Umbraco version: 7.11.1

**Comment by zpqrtbnk** [comment]
See https://github.com/umbraco/Umbraco-CMS/issues/4464 ?

**Comment by zpqrtbnk** [comment]
Ah - that's a v8 issue, and looks like the same thing happens on v7?

**Comment by martina-1995** [comment]
> Ah - that's a v8 issue, and looks like the same thing happens on v7?

Yes Stephan I'm having the problem on v7

**Comment by CodeCheetah** [comment]
Yes, same problem using v7.14.0

**Comment by Matthew-Wise** [comment]
Will this get fixed for 7.15?

**Comment by Myster** [comment]
still broken in 7.15.1

**Comment by angelomiguelsantos** [comment]
Hello still broken in 7.15.3 ...any knews on this ...anyone solved this question ? 

thank you 

Angelo

**Comment by nul800sebastiaan** [comment]
Just happened to click on this very old issue. 😮 

If anyone is still interested in getting this fixed then we'll happily look at a pull request, but for now I'll close this. Feel free to refer to this issue in a PR though if someone wants to work on it.
