### ISSUE TITLE
v8: Fix text decoration on info icons in media listview

### ISSUE THREAD

**Issue by bjarnef** [umbraco/Umbraco-CMS#4623]
In media listview grid layout when hover the items it has both text decoration on the info icon and the text.
It should probably only have text decoration on the text.

![image](https://user-images.githubusercontent.com/2919859/52914448-9bc90000-32c8-11e9-8b84-7301efcd251b.png)

**Comment by kjac** [comment]
PR in #4824

**Comment by nielslyngsoe** [comment]
Already fixed
