### ISSUE TITLE
v8: Media picker doesn't show items in listview from infinite editing

### ISSUE THREAD

**Issue by bjarnef** [umbraco/Umbraco-CMS#4624]
When clicking "add" in media picker and then in dialog select edit on a folder it doesn't seem to list any child items in the listview as it does when browsing to media section and selecting the folder.

![2019-02-17_15-36-13](https://user-images.githubusercontent.com/2919859/52914570-5c9bae80-32ca-11e9-86c2-5deedb2fd9af.gif)

**Comment by nul800sebastiaan** [comment]
Thanks @bjarnef - we decided not to have list views open in infinite editing mode for the moment as it had too many problems. So this is no longer an issue right now.
