### ISSUE TITLE
v8: Image cropper zoom to top left

### ISSUE THREAD

**Issue by bjarnef** [umbraco/Umbraco-CMS#4625]
In image cropper when zooming/scaling the image, it seems to zoom to top/left corner of image. I think it would be better to zoom to center of image (or position of focal point).

E.g. compare with this demo https://shareurcodes.com/demos/jquery-image-upload which is based on https://foliotek.github.io/Croppie/

**Comment by nul800sebastiaan** [comment]
This issue has been in the `up for grabs` state for quite a while now and it seems nobody is ready to pick this one up.

For now we'll close this issue to prevent the list of `up for grabs` from becoming very stale. We're happy to re-open it if someone still thinks it's good to work on this.

If anyone is about to pick this issue up to fix it, make sure to test first if you can reproduce the problem in the latest version before you start to work on it.

Thanks!
Sebastiaan on behalf of Umbraco HQ.
