### ISSUE TITLE
v8 - validation UI is broken between the accordion items

### ISSUE THREAD

**Issue by Shazwazza** [umbraco/Umbraco-CMS#4627]
This must be a regression at some stage but the validation of each property is no longer working properly. 

See this Gif:

![2019-02-18_16-54-26](https://user-images.githubusercontent.com/1742685/52930816-144dc080-339e-11e9-9b38-1e5c34d34eb4.gif)

The way it is supposed to work is that when each property no longer has any errors in it, the property level validation warning should disappear, for some reason at the moment they don't disappear until all errors are gone

**Comment by mattbrailsford** [comment]
Dunno if this would be classes as a separate issue, but I wonder if something better than the big red bar could be implemented as it's making input fields jump around as errors are cleared.

**Comment by Shazwazza** [comment]
Yeah, there's quite a few issues with validation at the moment:

* The colors don't seem right
* The big red bar is pretty ugly and now that the accordion is there it does make things jump
* The validation indicators at the "content app" level are not clear at all, making it very confusing when validation fails (i.e. see video which shows this issue along with another bug i'm fixing https://www.screencast.com/t/z1a5Jl9SHX). For the interim, I've created a PR to fix this which also makes it consistent with the doc type editor: https://github.com/umbraco/Umbraco-CMS/pull/4643

**Comment by nielslyngsoe** [comment]
@Shazwazza plus, in Nested Content validation errors are not re-evaluated at first. So if you had an error, corrected it, click Save & Publish again. You will see a warning, though clicking Save & Publish an extra time will make it succeed.

![ScreenRecording20190312at1](https://user-images.githubusercontent.com/6791648/54204314-4b624e00-44d4-11e9-8e59-6032e314e62a.gif)

**Comment by nielslyngsoe** [comment]
PR https://github.com/umbraco/Umbraco-CMS/pull/4978
