### ISSUE TITLE
Implement a non generic PagedResult base class

### ISSUE THREAD

**Issue by mattbrailsford** [umbraco/Umbraco-CMS#4636]
Maybe PagedResult<T> isn't meant to be used outside Umbraco, but it is really useful when doing pagniated things.

However, the one thing I wish it had was either a base class or an interface that doesn't have a generic type param. Quite often when this is used on the front end, you just want to implement a generic pagination control and all this really needs to know is the current page + total pages (so it doesn't need the Items property). Unfortunately, as PagedResult always requires a Type argument, it's not possible to make this generic control. In reality though, that Type param is only needed for the Items collection so it definately could be updated to the following:

    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;

    namespace Umbraco.Core.Models
    {
        /// <summary>
        /// Represents a paged result for a model collection
        /// </summary>
        /// <typeparam name="T"></typeparam>
        [DataContract(Name = "pagedCollection", Namespace = "")]
        public abstract class PagedResult
        {
            public PagedResult(long totalItems, long pageNumber, long pageSize)
            {
                TotalItems = totalItems;
                PageNumber = pageNumber;
                PageSize = pageSize;

                if (pageSize > 0)
                {
                    TotalPages = (long)Math.Ceiling(totalItems / (Decimal)pageSize);
                }
                else
                {
                    TotalPages = 1;
                }
            }

            [DataMember(Name = "pageNumber")]
            public long PageNumber { get; private set; }

            [DataMember(Name = "pageSize")]
            public long PageSize { get; private set; }

            [DataMember(Name = "totalPages")]
            public long TotalPages { get; private set; }

            [DataMember(Name = "totalItems")]
            public long TotalItems { get; private set; }

            /// <summary>
            /// Calculates the skip size based on the paged parameters specified
            /// </summary>
            /// <remarks>
            /// Returns 0 if the page number or page size is zero
            /// </remarks>
            public int GetSkipSize()
            {
                if (PageNumber > 0 && PageSize > 0)
                {
                    return Convert.ToInt32((PageNumber - 1) * PageSize);
                }
                return 0;
            }
        }

        /// <summary>
        /// Represents a paged result for a model collection
        /// </summary>
        /// <typeparam name="T"></typeparam>
        [DataContract(Name = "pagedCollection", Namespace = "")]
        public class PagedResult<T>  : PagedResult
        {
            [DataMember(Name = "items")]
            public IEnumerable<T> Items { get; set; }
        }
    }

**Comment by nul800sebastiaan** [comment]
Makes sense to me, would be great! 👍 

I've marked this as "Up for grabs" so that you or someone else coming along could create a pull request for it.

**Comment by ajsmith27** [comment]
@mattbrailsford what's the sample usage for this? Would you not want to instantiate a PagedResult?

**Comment by mattbrailsford** [comment]
@ajsmith27 the use case for it is to act as a base class to the typed PagedResult. It's abstract because you wouldn't want a base PagedResult object without any actual results, but by having a base class, you can for example create a generic pagniation control that accepts the base PagedResult as it's model and renders pagination controls. By only having the typed PagedResult you'd have to create a pagination control per PagedResult<T>, ie, it wouldn't be reusable.

Essentially there are times when you only need to know about the pagination details, not the actual items themselves, this just allows you to access that information by a common base class.

**Comment by nul800sebastiaan** [comment]
This issue has been in the `up for grabs` state for quite a while now and it seems nobody is ready to pick this one up.

For now we'll close this issue to prevent the list of `up for grabs` from becoming very stale. We're happy to re-open it if someone still thinks it's good to work on this.

If anyone is about to pick this issue up to fix it, make sure to test first if you can reproduce the problem in the latest version before you start to work on it.

Thanks!
Sebastiaan on behalf of Umbraco HQ.

**Comment by nul800sebastiaan** [comment]
Fixed in https://github.com/umbraco/Umbraco-CMS/pull/6871
