### ISSUE TITLE
v8 - validation colors are not consistent

### ISSUE THREAD

**Issue by Shazwazza** [umbraco/Umbraco-CMS#4645]
I've added a note to the colors in the variables .less file about the validation red color: https://github.com/umbraco/Umbraco-CMS/blob/temp8/src/Umbraco.Web.UI.Client/src/less/variables.less#L44

There are 2 different 'red' colors being used for validation actively, see image: 

![image](https://user-images.githubusercontent.com/1742685/52983927-5da31c00-3441-11e9-9f3c-b72b9867d407.png)

The old red color is still being used in 99% of places apart from the .umb-validation-label (that's the only validation place i can see the new color), see

![image](https://user-images.githubusercontent.com/1742685/52984003-aa86f280-3441-11e9-862f-91006533ed19.png)

It should be relatively easy to replace the usages of `@red-d1` in the less files with the `@red` for the validation bits, BUT there are hard coded values of the `@red-d1` color within the HTML files that need to be cleaned up first.

**Comment by kjac** [comment]
PR in #4825
