### ISSUE TITLE
V8: umbracoUrlName doesn't work

### ISSUE THREAD

**Issue by Facius** [umbraco/Umbraco-CMS#4649]
umbracoUrlName property doesn't seem to work in v 8.0.0-alpha.58.2423

Reproduction
------------
 ![capture](https://user-images.githubusercontent.com/318881/53005068-c040eb80-3432-11e9-919b-1459aa098455.PNG)
![capture1](https://user-images.githubusercontent.com/318881/53005070-c0d98200-3432-11e9-93fb-f63337f10a2d.PNG)
![capture2](https://user-images.githubusercontent.com/318881/53005071-c0d98200-3432-11e9-815f-fdab148a08b8.PNG)

the information tab is not updated with /new-url and the page cannot be accessed via /new-url. only test

**Comment by zpqrtbnk** [comment]
Confirmed. Due to NuCache basically ... ignoring `IUrlSegmentProvider` entirely ;-(

**Comment by zpqrtbnk** [comment]
Turns out NuCache was indeed not handling `IUrlSegmentProvider`... at all.

PR: https://github.com/umbraco/Umbraco-CMS/pull/4857

Note: Since we change the NuCache JSON structure, we need to trigger a full rebuild (via a migration).

Test: Simply upgrade, and all should work.

**Comment by OAOVLD** [comment]
Hello 
Please fix this bug in version 8.0.1 on March 12.  we cannot use umbraco 8 in production because of this error

**Comment by OAOVLD** [comment]
thank!

EN: Will you enable this fix in version 8.0.1 on March 12?

(Rus: Вы включите это исправление в версии 8.0.1 12 марта?)

**Comment by OAOVLD** [comment]
thank!

**Comment by miackers** [comment]
One quick thing to note to those that also land on this page - mine wasn't working (Umbraco v8.0.2), and the cause was that the page (content type) had language variants enabled, but the umbracoUrlName didn't (had a look at the source to figure this one out)

**Comment by stefankip** [comment]
@miackers thank you! Was wondering why it didn't work and making it variant is a good thing ofcourse.
