### ISSUE TITLE
v8: Angular routing should be case insensitive

### ISSUE THREAD

**Issue by mattbrailsford** [umbraco/Umbraco-CMS#4654]
I'm currently building a custom tree and as part of this, I'm generating the RoutePath for the tree nodes myself. The route follows the expected URL structure of `/app_alias/tree_alias/method/:id`, however as part of this, I'm lowercasing the whole route.

The problem is that when Umbraco attempts to load the relevant angular view for the route, it fails to identify the section and/or tree it belongs to and so falls back to looking for the routes view in `/umbraco/views` folder. I believe this is because when the tree is looked up via the alias, it is failing because it's doing so in a case sensitive manor. To prove this, if I don't lowercase the route, then the correct angualr view is found in `/app_plugins/my_plugin/backoffice/tree_alias/method.html`.

Url / route structures should never be case sensitive and so the app / tree lookup should be performed in a case insensitive manor.

**Comment by nul800sebastiaan** [comment]
This is a good point! At least you know how to work around it for now.

I've marked this as "Up for grabs" so that you or someone else coming along could create a pull request for it.

**Comment by skartknet** [comment]
PR in https://github.com/umbraco/Umbraco-CMS/pull/5540
