### ISSUE TITLE
v8: Example searches position in Log Viewer

### ISSUE THREAD

**Issue by bjarnef** [umbraco/Umbraco-CMS#4656]
It seems the position of example searches dropdown in latest v8 changes, `dev-v8` branch, has been moved which add too much right padding in input. Not sure if it is intended to move the example searches dropdown.

![image](https://user-images.githubusercontent.com/2919859/53047858-a71c5700-3493-11e9-9427-58b4b5412cef.png)

E.g. compare with this issue https://github.com/umbraco/Umbraco-CMS/issues/4343

Furthermore the search button style should probably be consistent with search button in e.g. Examine dashboard.

**Comment by nul800sebastiaan** [comment]
Oops, that does look like it's off!

I've marked this as "Up for grabs" so that you or someone else coming along could create a pull request for it.

**Comment by matthew-darby** [comment]
PR: https://github.com/umbraco/Umbraco-CMS/pull/4938

**Comment by nul800sebastiaan** [comment]
Looks like this one was fixed along the way, I'll close this.
