### ISSUE TITLE
v8: TinyMCE source overlay doesn't animate from right

### ISSUE THREAD

**Issue by bjarnef** [umbraco/Umbraco-CMS#4657]
When opning TinyMCE source overlay it doesn't seem to animate in from right as e.g. inifinite editing and other overlays from TinyMCE: media picker, macro picker, embed, link picker.

![2019-02-19_22-27-06](https://user-images.githubusercontent.com/2919859/53048872-0bd8b100-3496-11e9-9c9d-d36b7548cf97.gif)

**Comment by nul800sebastiaan** [comment]
Ah sure.. not sure what's going on there 🤔

I've marked this as "Up for grabs" so that you or someone else coming along could create a pull request for it.

**Comment by nul800sebastiaan** [comment]
Fixed in https://github.com/umbraco/Umbraco-CMS/pull/5480
