### ISSUE TITLE
v8: Slider config - show/hide Initial value 2

### ISSUE THREAD

**Issue by bjarnef** [umbraco/Umbraco-CMS#4658]
It would be great to show/hide "Initial value 2" it slider config, when enable/disable range slider.

![image](https://user-images.githubusercontent.com/2919859/53052544-4e52bb80-349f-11e9-9d5e-b1ab7d2f02f1.png)

@nul800sebastiaan did something similar in this PR https://github.com/umbraco/Umbraco-CMS/pull/2775#issuecomment-407206731

https://github.com/bjarnef/Umbraco-CMS/blob/e0b15070569d58d4c6532c90e0c26d6fb0b5fe1a/src/Umbraco.Web.UI.Client/src/common/directives/components/buttons/umbtoggle.directive.js#L103

If having multiple toggles on a page (in this config) I guess both of these would toggle show/hide of the field.

**Comment by kjac** [comment]
@bjarnef the configuration property editors (previously known as prevalues) are rendered isolated from each other; it's all handled generically based on the list of configuration properties (in this case from [`SliderConfiguration`](https://github.com/umbraco/Umbraco-CMS/blob/dev-v8/src/Umbraco.Core/PropertyEditors/SliderConfiguration.cs)). 

When it's all generically handled we can't create any connectivity between the configuration property editors. To do that we need to create a custom configuration property editor with a controller logic that handles the two properties. And *that* does seem like a bit of overkill, specially considering how we'll most likely need to add migrations to deal with old configs.

**Comment by nul800sebastiaan** [comment]
While I agree with @kjac that we should go nuts and change the configuration I would imagine that a good-old `getElementById` could help here. Then the specific range fields can be wrapped in a div to hide when ranges are disabled?

Might be a bit of a hack, but it's pretty friendly.

I'll put this in up for grabs, but if my hack won't work then I think we'll close it and move on. :)

**Comment by nul800sebastiaan** [comment]
This issue has been in the `up for grabs` state for quite a while now and it seems nobody is ready to pick this one up.

For now we'll close this issue to prevent the list of `up for grabs` from becoming very stale. We're happy to re-open it if someone still thinks it's good to work on this.

If anyone is about to pick this issue up to fix it, make sure to test first if you can reproduce the problem in the latest version before you start to work on it.

Thanks!
Sebastiaan on behalf of Umbraco HQ.
