### ISSUE TITLE
v8: TinyMCE link picker should filter recycle bin

### ISSUE THREAD

**Issue by bjarnef** [umbraco/Umbraco-CMS#4659]
In TinyMCE link picker (or maybe it is a general issue in link picker) it show recycle bin in tree, which doesn't make sense to select.
If you select recycle bin node and submit, when you then edit the link it throw an error.

![2019-02-20_00-06-02](https://user-images.githubusercontent.com/2919859/53054162-c91dd580-34a3-11e9-973a-955e46e6eaaa.gif)

I noticed a similar issue in package section when creating a package, where you also are able to select recycle bin to include in package.

**Comment by kjac** [comment]
This is a general issue with the tree picker in dialogs. I'm on it.

**Comment by kjac** [comment]
PR in #4960
