### ISSUE TITLE
v8: TinyMCE - image is flickering when dragging focal point in overlay

### ISSUE THREAD

**Issue by bjarnef** [umbraco/Umbraco-CMS#4660]
When inserting an image in TinyMCE and dragging to focal point in the overlay, the image seems to be flickering.

![2019-02-20_00-20-07](https://user-images.githubusercontent.com/2919859/53054696-7d6c2b80-34a5-11e9-92b6-875715302464.gif)

It would also be great to ensure both Url and Alternative text clear the line before showing the value on the next line.

**Comment by nul800sebastiaan** [comment]
Ha, nice catch! 

I've marked this as "Up for grabs" so that you or someone else coming along could create a pull request for it.

**Comment by nul800sebastiaan** [comment]
This issue has been in the `up for grabs` state for quite a while now and it seems nobody is ready to pick this one up.

For now we'll close this issue to prevent the list of `up for grabs` from becoming very stale. We're happy to re-open it if someone still thinks it's good to work on this.

If anyone is about to pick this issue up to fix it, make sure to test first if you can reproduce the problem in the latest version before you start to work on it.

Thanks!
Sebastiaan on behalf of Umbraco HQ.
