### ISSUE TITLE
umbracoUserLogin table not pruned

### ISSUE THREAD

**Issue by matthew-hair** [umbraco/Umbraco-CMS#4661]
Inactive logins should be pruned from the umbracoUserLogin table, but they are not being pruned.

Reproduction
------------

### Bug summary

Logins that are inactive for more than 15 days are supposed to be pruned from the umbracoUserLogin table, but they do not get pruned, and this causes unnecessary rows to build up in the table.

### Steps to reproduce

Log in to the backoffice and then close the browser without explicitly logging out. Do not try to log in again for 15 or more days, then restart the application pool and try logging in again, using any account.

### Expected result

Inactive logins should be pruned from umbracoUserLogin after 15 days.

### Actual result

Inactive logins are not pruned from umbracoUserLogin after 15 days.

**Comment by nul800sebastiaan** [comment]
Fixed in https://github.com/umbraco/Umbraco-CMS/pull/4662
