### ISSUE TITLE
V8: When validation error on another content-app than current opened, it does not show.

### ISSUE THREAD

**Issue by nielslyngsoe** [umbraco/Umbraco-CMS#4673]
V8: When validation error happens on another content-app than the currently opened, it does not show, only marking the content-app icon as red.

![image](https://user-images.githubusercontent.com/6791648/53098123-43416f00-3523-11e9-9d0b-dd3de34c663a.png)

**Comment by nul800sebastiaan** [comment]
Currently, it shows a red notification at the bottom as well, I think that should suffice.
