### ISSUE TITLE
Cannot update published properties in event handlers

### ISSUE THREAD

**Issue by zpqrtbnk** [umbraco/Umbraco-CMS#4677]
Shan on Slack:

Unfortunately I I've discovered another major hiccup - We currently cannot use the `Saving` or `Publishgin` events on the `ContentService` to set property values and have them be published during SaveAndPublish. If you do something like `content.SetValue("myProperty", someValue)` inside of the these events, their value will be persisted as part of the Draft of the content instance but they will not be included in the published result! Worse, it's impossible currently with our APIs to make it publish. The way this is currently done is that `content.PublishCulture(...)` internal method is called from within the ContentService during the SaveAndPublish operation and before the events are raised, so any `content.SetValue` calls done after `content.PublishCulture(...)` will just be setting data on the Draft. The underlying `property.PublishValues(...)` that is called within this is internal too.

**Comment by Shazwazza** [comment]
Fixed in PR https://github.com/umbraco/Umbraco-CMS/pull/4684 which also contains notes

**Comment by RobertCopilau** [comment]
Tested and can confirm that `Publishing` and `Saving` events are working again, variant and invariant "mode".
