### ISSUE TITLE
v8: Old password is not highlighted in validation

### ISSUE THREAD

**Issue by bjarnef** [umbraco/Umbraco-CMS#4678]
When opening change password in user overlay and hit "change password" with blank fields, the validation is shown for each field. However for "old password" this isn't hightlighted.

![image](https://user-images.githubusercontent.com/2919859/53124574-f8901900-355b-11e9-840a-95a0213b319a.png)

The `control-group` seems to be missing the `error` class, which would make the validation looks like this:

![image](https://user-images.githubusercontent.com/2919859/53124646-31c88900-355c-11e9-8ab6-7f8e3d2d4b10.png)

**Comment by nul800sebastiaan** [comment]
I've marked this as "Up for grabs" so that you or someone else coming along could create a pull request for it.

**Comment by SoerenDeger** [comment]
It seems there is already fixed in dev-v8 branch?

![image](https://user-images.githubusercontent.com/7769446/54983044-52955b80-4fac-11e9-99d0-14bb08582943.png)

**Comment by Shazwazza** [comment]
@bjarnef can you confirm?

**Comment by bjarnef** [comment]
@Shazwazza yes, it seems this has been fixed in latest changes in `dev-v8` branch.

![image](https://user-images.githubusercontent.com/2919859/54998411-5b972480-4fce-11e9-92aa-17b415438ef5.png)

It is also fixes in Umbraco v8.0.1 release.

**Comment by bjarnef** [comment]
However entering a value in "old password" doesn't remove the error validation on the label, but it is removed from the field.

![image](https://user-images.githubusercontent.com/2919859/54998566-bfb9e880-4fce-11e9-88f0-1ab9b4884f57.png)

**Comment by bjarnef** [comment]
Oh, if I open the user dialog and hit "change password" with empty fields it show the validation error.

![image](https://user-images.githubusercontent.com/2919859/54998940-99e11380-4fcf-11e9-8c85-7140c509452f.png)

if I then close the dialog using the link "close" or using esc key and open the user dialog again, the validation of the form has been reset, but when now hitting "change password", it shows these validation errors.

![image](https://user-images.githubusercontent.com/2919859/54999169-f6443300-4fcf-11e9-9140-2da9aa783c17.png)

**Comment by bjarnef** [comment]
I guess it has something to do for `formValid()` function which doesn't set the error class on subsequent validations of the form.

```
<div class="control-group umb-control-group" ng-class="{error: !formValid(), hidelabel:hideLabel=='true'}">
```

**Comment by nul800sebastiaan** [comment]
This issue has been in the `up for grabs` state for quite a while now and it seems nobody is ready to pick this one up.

For now we'll close this issue to prevent the list of `up for grabs` from becoming very stale. We're happy to re-open it if someone still thinks it's good to work on this.

If anyone is about to pick this issue up to fix it, make sure to test first if you can reproduce the problem in the latest version before you start to work on it.

Thanks!
Sebastiaan on behalf of Umbraco HQ.

**Comment by nul800sebastiaan** [comment]
Fixed in https://github.com/umbraco/Umbraco-CMS/pull/6274

Cherry picked for 8.1.5 in 468cd96846fa3d5eb033148842c524a33448ea56
