### ISSUE TITLE
v8: Update routing of pages

### ISSUE THREAD

**Issue by bjarnef** [umbraco/Umbraco-CMS#4679]
In v8 some pages have confusing urls and not consistent between sections.

**Users**
```
/umbraco/#/users/users/users
/umbraco/#/users/users/groups
```

**Members** (why not `/members/members/..` in url so it match section + tree?)
```
/umbraco/#/member/member/list/all-members
/umbraco/#/member/member/list/employee
```

**Comment by nul800sebastiaan** [comment]
I can't find it any more but I saw Shannon replying to this somewhere else too. His conclusion basically was: it is what it is (for good reasons) and we don't intend to make changes to the routing at this time.
