### ISSUE TITLE
v8: Indicate hover on user box link vs selection

### ISSUE THREAD

**Issue by bjarnef** [umbraco/Umbraco-CMS#4680]
In users overview it is possible to go to a user profile by clicking the link/anchor in a user box or select the user by clicking the other part of the box. However it is not clear what happens when clicking the box. In fact the only visual difference is that the user name get a underline text decoration, when you hover the link/anchor in the box.

It should probably in some way hightlight the box if the click will select the box or go to the user profile. Also note when hover e.g. super user box it show hand cursor style, but the box can't be selected, so it should probably have a not-allowed cursor style or similar.

![image](https://user-images.githubusercontent.com/2919859/53125491-69d0cb80-355e-11e9-96f9-384550c0a8c8.png)

**Comment by nul800sebastiaan** [comment]
Sounds good!

I've marked this as "Up for grabs" so that you or someone else coming along could create a pull request for it.

**Comment by nul800sebastiaan** [comment]
This issue has been in the `up for grabs` state for quite a while now and it seems nobody is ready to pick this one up.

For now we'll close this issue to prevent the list of `up for grabs` from becoming very stale. We're happy to re-open it if someone still thinks it's good to work on this.

If anyone is about to pick this issue up to fix it, make sure to test first if you can reproduce the problem in the latest version before you start to work on it.

Thanks!
Sebastiaan on behalf of Umbraco HQ.
