### ISSUE TITLE
v8: Layout jumps a few pixels when selecting user

### ISSUE THREAD

**Issue by bjarnef** [umbraco/Umbraco-CMS#4681]
This is just a minor issue, but when selecting a user in users section the layout jumps a few pixels.

Also when hover the rows in users listview list layout the columns jumps a bit.

![2019-02-20_22-37-36](https://user-images.githubusercontent.com/2919859/53126760-288deb00-3561-11e9-9b55-44bd50e206f6.gif)

**Comment by nul800sebastiaan** [comment]
Oh no! :) 

I've marked this as "Up for grabs" so that you or someone else coming along could create a pull request for it.

**Comment by bjarnef** [comment]
Yeah I know, a very annoying bug! 😁

**Comment by matthew-darby** [comment]
PR: https://github.com/umbraco/Umbraco-CMS/pull/4939
