### ISSUE TITLE
v8: Selection of users and groups are not consistent with rest of UI

### ISSUE THREAD

**Issue by bjarnef** [umbraco/Umbraco-CMS#4682]
The selection of users in list layout mode and in user groups view doesn't seem to be consistent with selection in e.g. content, media and member listviews.

![image](https://user-images.githubusercontent.com/2919859/53126570-b917fb80-3560-11e9-8676-5d7f55afe315.png)

![image](https://user-images.githubusercontent.com/2919859/53126586-c0d7a000-3560-11e9-8e49-6cff3fc768d2.png)

![image](https://user-images.githubusercontent.com/2919859/53126622-d64cca00-3560-11e9-9bc4-0d8e1f8e8da1.png)

Also notice the difference usage of checkboxes vs checkmark icon.

**Comment by nul800sebastiaan** [comment]
YES to consistency. We had a good chat about making this more consistent and more intuitive. @nielslyngsoe will pick it up from here, and we talked about starting a "style guide" for this to adhere to for lists. Which then could expand to other elements in the backoffice.

**Comment by nielslyngsoe** [comment]
Working on a PR: https://github.com/umbraco/Umbraco-CMS/pull/5120

**Comment by Shazwazza** [comment]
@nielslyngsoe why is this closed when the PR is not merged? What release is this going to be in? Where is the release tag? etc...

**Comment by zpqrtbnk** [comment]
Just don't understand, this is really messy, the PR is still there, reopening the issue
