### ISSUE TITLE
V8 Multilanguage as folders and variants

### ISSUE THREAD

**Issue by AllanKirk** [umbraco/Umbraco-CMS#4683]
I am trying to setup a multilanguage website as variants, and I want to follow the recommendations in the backoffice. One of those recommendations is: "One-level paths in domains are supported, eg. "example.com/en". However, they should be avoided."
Okay, fair enough. I guess I will just setup a root-node with the actual domain, and a sub-node with the languages as variants. Now here is my problem; the only way I am able to add variants to the sub-node is to setup different hostnames, and I am back to breaking the recommendation above.
If that is the way it is supposed to be done, fair enough, but then that description should be changed.

Goal.
Setup this variants without breaking the recommendation.
domain.com/en
domain.com/da

**Comment by zpqrtbnk** [comment]
Note: situation is indeed not very clear - must clarify - moving to sprint backlog

**Comment by bergmania** [comment]
Notes: 
This is how it works:

| Domain                          | Language | Match Hostnames | Match Path prefix | Notes |
|-------------------------------- |----------|------------------    |     ----   |--------------------------------------|
| http://localhost:8100/en        | en-US    | `http://localhost:8100`  |`/en`   | Match the specific host and path prefix |
| http://localhost:8100/da        | da-DK    | `http://localhost:8100` |`/da`   | Match the specific host and path prefix |
| https://localhost:44319/eng     | en-US    | `https://localhost:44319` |`/eng`| Match the specific host and path prefix |
| https://localhost:44319/dan     | da-DK    | `https://localhost:44319` |`/dan`| Match the specific host and path prefix |
| localhost                       | da-DK    | `*://localhost:*` | `/`          | Match the domain `localhost` on all ports and schema and path prefix `/` |
| /en                             | en-US    | `*://*:*`|`/en`                 | Match on all domains on all ports and schema with the path prefix `/da` |
| /da                             | da-DK    | `*://*:*`|`/da`                 | Match on all domains on all ports and schema with the path prefix `/da` |

Futhermore:
http://localhost:8100 and https://localhost:44319/ shows default langauge (en-US)

I thing the code works as expected, but we need to update the texts.

**Comment by bergmania** [comment]
Suggestion:

> Valid domain names are: "example.com", "www.example.com", "example.com:8080", "https://www.example.com/". Furthermore also one-level paths in domains are supported, eg. "example.com/en".

**Comment by bergmania** [comment]
PR: https://github.com/umbraco/Umbraco-CMS/pull/5045

**Comment by ronaldbarendse** [comment]
@AllanKirk You can also change the app setting `Umbraco.Core.HideTopLevelNodeFromPath` to `false`, so root nodes will generate URL segments (and you don't need to add a site node/domains)...

@bergmania Having duplicate content on the domain root is a major SEO problem, so we've created a custom `IContentFinder` that redirects to the preferred (`Accept-Language` header, default language) node (currently only for internal use). As Umbraco 7 just uses the first language as default, it's not even possible to change what language is displayed on the root!
