### ISSUE TITLE
V8: Saving a new Nested Content Data-Type with no Element-Types on a DocType fails

### ISSUE THREAD

**Issue by nielslyngsoe** [umbraco/Umbraco-CMS#4685]
Saving a new Nested Content Data-Type with no Element-Types defined on a DocType fails.

To reproduce:
Add a new Nested Content DataType with no configuration directly from a Document Type.

![image](https://user-images.githubusercontent.com/6791648/53160370-1c894400-35c8-11e9-9908-5258cfd1c2db.png)

Preferred solution would be if Nested Content would work with no ElementTypes defined. Cause sometimes it makes sense to create the Data-Type before the ElementTypes that its going to use.

**Comment by kjac** [comment]
Shouldn't be possible to create that config in the first place due to validation; but clearly the validation doesn't kick in when using infinite editing. PR for that in #4776

**Comment by kjac** [comment]
And there's a PR for being able to remove the default NC blueprint in #4777
