### ISSUE TITLE
Adjust naming in Nested Content configuration to fit ElementType

### ISSUE THREAD

**Issue by nielslyngsoe** [umbraco/Umbraco-CMS#4686]
We should rename "Document Types" to "Element Types" (above the dropdown where you can only choose element types)

And as Bjarne mentions, we should change "tab" to "property group" or just "group"

![image](https://user-images.githubusercontent.com/6791648/53161325-16946280-35ca-11e9-8922-1108ba1b20c6.png)

**Comment by bjarnef** [comment]
@nielslyngsoe maybe "Tab" should also be renamed to "Group" by using a different language key.

**Comment by matthew-darby** [comment]
PR: https://github.com/umbraco/Umbraco-CMS/pull/4946/
