### ISSUE TITLE
Multinode TreePicker doesn't fail when the amount validation doesn't meet the requirement

### ISSUE THREAD

**Issue by nielslyngsoe** [umbraco/Umbraco-CMS#4687]
If you have a Multinode TreePicker with a minimum requirement for nodes to be selected, and it's set to be mandatory. It does not fail when the requirements aren't meet.

Validation should fail on publishing if the amount requirements aren't meet.

![image](https://user-images.githubusercontent.com/6791648/53161992-5f98e680-35cb-11e9-9c0a-6303d63ec3c6.png)

**Comment by kjac** [comment]
PR in #5343

**Comment by tom-ingeniuus** [comment]
Does this also validate against the maximum allowed items?
