### ISSUE TITLE
Save button saving states should be corrected to match colors

### ISSUE THREAD

**Issue by nielslyngsoe** [umbraco/Umbraco-CMS#4690]
When saving an item, the save-button changes into a save-state and later to a save-complete-state. Those state er presented with white colors, which are hard to see on top of the grey color.
Lets change them to the same color as the button-label.

![image](https://user-images.githubusercontent.com/6791648/53163145-bf908c80-35cd-11e9-8cad-08a035dcf6e9.png)

**Comment by kjac** [comment]
Looks like the inner button state misinterprets the `info` button style. I've got a fix, will push a PR soon as I can.

**Comment by kjac** [comment]
PR in #4736
