### ISSUE TITLE
v8: Update RenderModel comments

### ISSUE THREAD

**Issue by bjarnef** [umbraco/Umbraco-CMS#4691]
In v8 the `RenderModel` class has been removed and instead of `Model.Content` we just write `Model` in our views.

It seems there are a few comments still mentioning RenderModel.
https://github.com/umbraco/Umbraco-CMS/blob/91c52cffc8b7c70dc956f6c6610460be2d1adc51/src/Umbraco.Web/Mvc/RenderIndexActionSelectorAttribute.cs#L9-L12

https://github.com/umbraco/Umbraco-CMS/blob/91c52cffc8b7c70dc956f6c6610460be2d1adc51/src/Umbraco.Web/Mvc/RouteDefinition.cs#L22

**Comment by kjac** [comment]
PR in #4814

**Comment by nul800sebastiaan** [comment]
Fixed in https://github.com/umbraco/Umbraco-CMS/pull/4814
