### ISSUE TITLE
In publishing dialog the variant options should be clickable and not selectable

### ISSUE THREAD

**Issue by nielslyngsoe** [umbraco/Umbraco-CMS#4694]
In publishing dialog the variant options should be clickable and not selectable

![image](https://user-images.githubusercontent.com/6791648/53167477-55c9b000-35d8-11e9-8890-a94ae5f4daac.png)

**Comment by kjac** [comment]
PR in #4760

**Comment by kjac** [comment]
Note that this applies to a bunch of dialogs, see #4760 for details.
