### ISSUE TITLE
v8 Adding hostname and creating member dialog boxes do not close after saving

### ISSUE THREAD

**Issue by rhealefever** [umbraco/Umbraco-CMS#4699]
Local install of Umbraco version `8.0.0-alpha.2482`

When adding a new domain to a content node, clicking save does not close the dialog box automatically. User must manually click 'Close' to return to the content/info pages.
![2019-02-21_1535_001](https://user-images.githubusercontent.com/47108275/53176883-4570ff80-35ef-11e9-9eab-84b32b971c37.png)

The same thing happens in the Members section when creating a new member. The create member dialog closes automatically the first time the user makes a new member, but any further visits to the create dialog remain open and the user must click away from the dialog to close it. This is only reset by restarting the environment.
![2019-02-21_1536](https://user-images.githubusercontent.com/47108275/53176884-4570ff80-35ef-11e9-86bf-42f0cc91c893.png)

**Comment by kjac** [comment]
@rhealefever it's pretty common for dialogs to remain open after the primary action button is clicked. See for example the permissions and the sort dialogs. Or for that matter the move and copy dialogs.

The issue you've found in the members section is a whole other matter 😄 PR #4815 fixes it.

**Comment by nul800sebastiaan** [comment]
@kjac While that's true, it does close in v7 and I see no reason for it not to close here :-)

**Comment by kjac** [comment]
@nul800sebastiaan fair point. Fortunately it's super simple to fix... PR in #4996 😄
