### ISSUE TITLE
Update TinyMce to latest v4 version

### ISSUE THREAD

**Issue by ssougnez** [umbraco/Umbraco-CMS#4702]
### Bug summary

tinymce adds unwanted non breaking spaces ("& nbsp;") in the HTML. This is pretty critical to me as it could mess up layouts.

### Steps to reproduce

* Create a document type with a "Rich text editor" property
* Start typing some text
* Add a space at the end of line and stop typing for a short duration (around 500ms)
* Resume typing

### Result

If you look at the HTML code, an unwanted non breaking space has been added when the pause has been made. Indeed, regular spaces are converted into non-breaking space to ensure that if the line ends up with one, it does not get lost. However, this non breaking space should be reverted to a regular one once the typing resumes or the HTML would end up cluttered with non breaking spaces.

### Solution

Upgrade tinymce version from 4.7.1 to 4.9.3. 

I tested this behavior with this version and non breaking spaces are reverted to regular ones if the typing resumes.

PR: https://github.com/umbraco/Umbraco-CMS/pull/4703

**Comment by drbldgtl** [comment]
This has been the only issue blocking the release of 7.15 for weeks as far as I can tell - is there something blocking it?

**Comment by nul800sebastiaan** [comment]
It's not blocking the release, we're just not ready to release 7.15 in general at this point due to other priorities. Unfortunately, we don't yet have a release date for 7.15.

**Comment by nul800sebastiaan** [comment]
Fixed in https://github.com/umbraco/Umbraco-CMS/pull/4703

**Comment by HistoricEnglandDigitalTeam** [comment]
How can I tell if TinyMCE version 4.9.3 is installed in Umbraco v 7.15.2? I'm looking at Data Type Richtext editor - and the Property editor alias = Umbraco.TinyMCE**v3**.
If the v3 is correct, do we have to manually upgrade the TinyMCE?

**Comment by stevemegson** [comment]
You'll find the version number in `Umbraco\lib\tinymce\tinymce.min.js`. The property editor alias is a legacy of a time when the `TinyMCE` alias was used by version 2.

**Comment by HistoricEnglandDigitalTeam** [comment]
thanks :)
