### ISSUE TITLE
V8: Search functionality "include subfolders in search" is not very clear or understandable.

### ISSUE THREAD

**Issue by nielslyngsoe** [umbraco/Umbraco-CMS#4707]
The wording "include subfolders in search" is hard to read at first sight. Not very clear or understandable.

I would like the feature to be reverted, meaning that the checkbox should be changed to "Search only in this folder".

This also means that you by default will search the full media library, which i would say is the expected behaviour of a search by default.

![image](https://user-images.githubusercontent.com/6791648/53232461-6d15a580-368b-11e9-9b9f-40f96352fd75.png)

**Comment by kjac** [comment]
PR in #4720
