### ISSUE TITLE
shortcut for creating a folder in Media-Picker should return to non-active-state

### ISSUE THREAD

**Issue by nielslyngsoe** [umbraco/Umbraco-CMS#4709]
In the media-picker you can easily create a folder by clicking the little plus in the breadcrumb. Nice — but it should return to the original state after a folder has been created. Meaning if you want to create another folder you should click the plus again.

![2019-02-22 10 27 54](https://user-images.githubusercontent.com/6791648/53233041-adc1ee80-368c-11e9-9222-4c18c855619a.gif)

**Comment by kjac** [comment]
PR in #4722
