### ISSUE TITLE
V8 Update assemblyBinndings in web.config.install.xdt for nuget upgrades

### ISSUE THREAD

**Issue by mikkelhm** [umbraco/Umbraco-CMS#4711]
I know this is a little early.. but we will need it at some point.

I'm currently testing some upgrades to 8.1, and for that purpose we are using the nuget package. The package includes a `web.config.install.xdt` that will be applied to web.config, when upgrading a site. 

The `runtime/assemblyBindings` element hasnt been updated with versions for the latest v8 dependencies. This would mean that when applying the transformation file, the site would try to use old dependencies.

The dependencies should at least just be updated to the same versions as the core CMS is using.

**Comment by bergmania** [comment]
PR: https://github.com/umbraco/Umbraco-CMS/pull/4767
