### ISSUE TITLE
V8 - IE11: section name underline not in correct position

### ISSUE THREAD

**Issue by MMasey** [umbraco/Umbraco-CMS#4715]
This is a pretty minor bug that effect IE11. The alignment of the section name underline isn't positioned correctly.

![image](https://user-images.githubusercontent.com/6573613/53287991-15eefe00-377b-11e9-8be1-f7a24b1d4c77.png)

I'll be submitting a PR to fix soon

Reproduction
------------

To reproduce, log into the backoffice on IE11 and you'll see the problem.

### Bug summary

The issue is being caused due to a lack of `left: 0` with the absolutely position section name underline.

**Comment by MMasey** [comment]
PR #4716 fixes this issue.

**Comment by nul800sebastiaan** [comment]
Note: while we don't actively support IE for v8 any more, this seems like a fine fix that should work for all browsers. We won't be taking any "extreme measures" to support IE11 in other ways though (for example: #4805).

**Comment by MMasey** [comment]
Yeah that makes sense. I created the issue & PR before i found out about the drop of IE11 support 😜

**Comment by nul800sebastiaan** [comment]
Fixed in https://github.com/umbraco/Umbraco-CMS/pull/4716
