### ISSUE TITLE
Add reCatptcha to login page 

### ISSUE THREAD

**Issue by liranp1** [umbraco/Umbraco-CMS#4717]
hi, 
i would like to ask to add reCaptcha to the login page /UMBRACO/.
this will improve security.

i new to this so if i will find how to add this to the code i will commit it.

thanks

**Comment by soreng** [comment]
Hi,

I don't think that is a very good idea, or would add anything security-wise.

If you want to improve the security, you should use two factor authentication instead, or use an external login provider, that you trust (Azure AD for instance).

**Comment by liranp1** [comment]
ok, thank you.
