### ISSUE TITLE
Content synchronization stop working 

### ISSUE THREAD

**Issue by vitalynaumenko** [umbraco/Umbraco-CMS#4725]
Hi all,

Our web site is running on Umbraco 7.12.3, in Azure. We are following https://our.umbraco.com/documentation/Getting-Started/Setup/Server-Setup/load-balancing/flexible setup and have one Web App for master instance, and one Web App for front instances with scale-out to 3 instances.
Sometimes, we face a situation when one of front instances stop receiving content updates from master/DB. We can see that newly published page not appeared on issues instance, or content updates not reflected on it. Future content updates in backoffice gives no results on instance with such issue. The only way we know to solve issue - is force cold boot on issued instance. 
We are getting know about problem when editors mention about it. As other instances works as expected issue could be invisible for a some period of time. So we don't have exact scenario to reproduce it or log message with error. 
Have you faced such cases earlier? It would be nice if you can share ideas about possible reasons.
The server is production, and logs severity limited with WARN level. I don't think we can turn on DEBUG level for entire web site. However, we can consider to enabling some specific loggers with DEBUG level to find cause. If this is makes sense - could you please advice what loggers/classes we should pay attention on?

Thanks,
Vitalii

**Comment by nul800sebastiaan** [comment]
Sounds like a weird problem, unfortunately we haven't seen this one before. It sounds like it could be related to your specific setup. 

I would recommend you post a question on the forum for some help with this. https://our.umbraco.com
