### ISSUE TITLE
Confusing state when trying to publish content where a mandatory language haven't been created.

### ISSUE THREAD

**Issue by nielslyngsoe** [umbraco/Umbraco-CMS#4728]
You will need a site with two or more mandatory languages, and a doc-type that allows for varying, and with at least one mandatory fields that allows for varying.

Create a node and fill out the required fields for one of the mandatory languages.

Click "Save & publish..." and then you will see this screen:

<img width="620" alt="screenshot 2019-02-25 at 09 53 44" src="https://user-images.githubusercontent.com/6791648/53325284-418cf800-38e3-11e9-8db2-2d24d95b5fb7.png">

This causes great confusion, cause its not very easy to see that there is a mandatory language that has not jet been created.

A solution could be to show that the language is mandatory, as we do in the save-dialog. and make it very clear that its required before the publish action can be carried out.

**Comment by nielslyngsoe** [comment]
PR: https://github.com/umbraco/Umbraco-CMS/pull/4891

**Comment by Shazwazza** [comment]
I'm re-opening this as i was in the middle of reviewing this, there is another issue that needs to be resolved first.
