### ISSUE TITLE
V8: Mediapicker properties not loaded correct into cache after recycle

### ISSUE THREAD

**Issue by bergmania** [umbraco/Umbraco-CMS#4729]
After recycle the media is not in the cache

Steps to reproduce:
- Set `<add key="Umbraco.ModelsBuilder.ModelsMode" value="LiveDll" />` in `web-config`
- Have a page with `MediaPicker` types and show the page correct in the website
- Save a doc type.  (Wait for the recycle)
- Reload the website (The media is not correct in cache)
- Reload the cache from the dashbord
- Reload the website (The media is now correct in cache)

![cache-issue](https://user-images.githubusercontent.com/1561480/53332042-a865dd80-38f2-11e9-9f22-feded4d5f446.gif)

**Comment by clausjensen** [comment]
Could be related to https://github.com/umbraco/Umbraco-CMS/issues/4751

**Comment by bergmania** [comment]
Debug log on first startup after clone, where the images are missing
[UmbracoTraceLog.DESKTOP-B5FI4JU.20190304.json](https://github.com/umbraco/Umbraco-CMS/files/2925899/UmbracoTraceLog.DESKTOP-B5FI4JU.20190304.json.txt)

**Comment by zpqrtbnk** [comment]
Have done:
* Configure models to `LiveDll`
* Create a document type with a media picker
* Create a document of that type, pick a media
* Create a template that renders `@Umbraco.Media(1055).Url`

And it does render the url.

Then:
* Edit a random document type, add a property type and save
* Refresh the page

And it does render the url, again.

So... cannot repro. Can you check my steps? Give me more details? Or share the site?

**Comment by bergmania** [comment]
Solved together with: https://github.com/umbraco/Umbraco-CMS/issues/4751

**Comment by nul800sebastiaan** [comment]
Fixed in 
https://github.com/umbraco/Umbraco-CMS/issues/4751
