### ISSUE TITLE
V8: Name-field is disabled but not in splitview.

### ISSUE THREAD

**Issue by madsoulswe** [umbraco/Umbraco-CMS#4730]
The name filed is disabled but not in splitview.

![image](https://user-images.githubusercontent.com/7071187/53338927-3054e300-3905-11e9-8444-451d638a3a5a.png)

![image](https://user-images.githubusercontent.com/7071187/53338953-406cc280-3905-11e9-8909-a8fa4298a1ba.png)

Reproduction
------------

Install umbraco with the default starterkit.
Add secondary language
Change doctypes to "Variant/Multilingual"
Switch to the secondary language.
Click on a node-name-field is disabled.

Open splitview then the you can change the name.

### Expected result

Not sure, but be able to set the nodename for the secondary-language-variant.

**Comment by madsoulswe** [comment]
Ah it's when "umbListView" is active. I'm not sure if it is a "bug", but it was confusing at first =)

https://github.com/umbraco/Umbraco-CMS/blob/dev-v8/src/Umbraco.Web.UI.Client/src/common/directives/components/content/umbvariantcontent.directive.js#L49

**Comment by kjac** [comment]
@madsoulswe It's by design; the name is always disabled on list views. Opening split view forces the active view over to content, where name is of course enabled 😄

**Comment by madsoulswe** [comment]
@kjac I noticed that, it's very logical. =D

**Comment by nul800sebastiaan** [comment]
Thanks, it's functioning as intended right now! 👍
