### ISSUE TITLE
Editor roles are logged out when viewing pages that use a PE which calls GetPreValues

### ISSUE THREAD

**Issue by kgiszewski** [umbraco/Umbraco-CMS#4734]
If a doctype includes a dropdown PE or anything that uses the following path, the user will be logged out if they are not role == admin.

To replicate:

1) Create a dropdown data type.
2) Add to a doctype.
3) Create content based on the above doctype.
4) Create an 'editor' role user.
5) Login as an editor, visit the page in the backoffice.
6) The user will be logged out.
7) Adding the user to `admin` role resolves the issue.

Path that involved:
`/umbraco/backoffice/UmbracoApi/DataType/GetPreValues?editorAlias=Umbraco.DropDown.Flexible&dataTypeId=1152`

![image](https://user-images.githubusercontent.com/4653907/53343393-51560d80-38de-11e9-8ddb-5798bf01df48.png)

Likely suspect for causing the 401:
https://github.com/umbraco/Umbraco-CMS/blob/91c52cffc8b7c70dc956f6c6610460be2d1adc51/src/Umbraco.Web/Editors/DataTypeController.cs#L36

Core version `7.10.4`

**Comment by nul800sebastiaan** [comment]
I can't reproduce this problem with the provided steps in a clean 7.13.2 install so it's probably been fixed along the way. 

There's no request to `GetPreValues` at all in 7.13.

![image](https://user-images.githubusercontent.com/304656/53349893-5b97fc00-391e-11e9-9d21-bc35e29e4eb6.png)


If you can still repro in a 7.13 install then feel free to re-open with updated steps. 👍

**Comment by kgiszewski** [comment]
No worries thx. A client is unable to upgrade at this time and you are likely correct.
