### ISSUE TITLE
v8: Accordion collapse still available in media and member section

### ISSUE THREAD

**Issue by bjarnef** [umbraco/Umbraco-CMS#4740]
The collapsing on accordions in content section was removed, but it seems the accordions in media section still is collapsible. Shouldn't this also be removed/disabled in media and member section, to make this consitent?

**Comment by nielslyngsoe** [comment]
Makes total sense to me. Lets get them away. :-D

**Comment by kjac** [comment]
PRs in #4928 and #4929
