### ISSUE TITLE
V8: Can't pick items in Multinode Tree Picker after filtering

### ISSUE THREAD

**Issue by bergmania** [umbraco/Umbraco-CMS#4743]
Can't pick items in Multinode Tree Picker after filtering

There is no errors in the javascript console.

Steps to reproduce:
![mntp-issue](https://user-images.githubusercontent.com/1561480/53394776-8aef4d00-39a0-11e9-93ca-b6aa044483e4.gif)

**Comment by kjac** [comment]
As it turns out it actually does select the items - the CSS just doesn't really show it 😄 

I'll push a fix shortly.

**Comment by kjac** [comment]
PR in #4744
