### ISSUE TITLE
v8: Content fly-out nav is behind Actions nav

### ISSUE THREAD

**Issue by skttl** [umbraco/Umbraco-CMS#4745]
If you have the actions nav open, the content fly-out nav is semi-hidden behind the actions.

Should the actions close when hovering content? Or should the actions dropdown be activated (and deactivated) on hover in stead?

![billede](https://user-images.githubusercontent.com/3726467/53401712-a1050980-39b0-11e9-9833-dacfb6085207.png)

**Comment by nul800sebastiaan** [comment]
I've put this one on the list for our periodic meetings at HQ and will let you know what the outcome is.

**Comment by nul800sebastiaan** [comment]
Whoops! Yeah that's is a bit of an oversight. We talked about it and the conclusion was: when the actions menu is open, the content app dropdown should not open (and vice versa). 

I've marked this as "Up for grabs" so that you or someone else coming along could create a pull request for it.

**Comment by nul800sebastiaan** [comment]
This issue has been in the `up for grabs` state for quite a while now and it seems nobody is ready to pick this one up.

For now we'll close this issue to prevent the list of `up for grabs` from becoming very stale. We're happy to re-open it if someone still thinks it's good to work on this.

If anyone is about to pick this issue up to fix it, make sure to test first if you can reproduce the problem in the latest version before you start to work on it.

Thanks!
Sebastiaan on behalf of Umbraco HQ.
