### ISSUE TITLE
V8: Ability to set icon for list view content app

### ISSUE THREAD

**Issue by skttl** [umbraco/Umbraco-CMS#4747]
It would be nice, if we could set the icon of the list view content app (just like we can set the name).

**Comment by nul800sebastiaan** [comment]
I've put this one on the list for our periodic meetings at HQ and will let you know what the outcome is.

**Comment by nul800sebastiaan** [comment]
Great idea!

I've marked this as "Up for grabs" so that you or someone else coming along could create a pull request for it.

**Comment by kjac** [comment]
Absolutely love this idea! PR in #5074

**Comment by nul800sebastiaan** [comment]
Whoops., PR #5074 fixes #4746 instead of this one ;-)
