### ISSUE TITLE
Get logged out after installing

### ISSUE THREAD

**Issue by prjseal** [umbraco/Umbraco-CMS#4748]
I installed v8 using NuGet
I built the site
I ran the site using Ctrl + F5 in VS
I went through the installer
Entered user details
Installed a website
Got to the backoffice
Clicked on 'Do not show this tour again' and it took me to the login screen
I expected to stay logged in

**Comment by nul800sebastiaan** [comment]
Seen this a few times, you probably have another v7 website running in the same browser for which you still have a cookie.
