### ISSUE TITLE
Wording of HTTPS configuration message in Health Check is misleading (and doesn't offer to fix it)

### ISSUE THREAD

**Issue by tom-d8** [umbraco/Umbraco-CMS#4749]
I ran a Health Check with the site running under HTTPS, but the error message was
"You are currently not viewing the site using the HTTPS scheme"

I solved the issue by setting Umbraco.Core.UseHttps to true

I think this message should be removed. The warning below it states:
"The appSetting 'umbracoUseSSL' is set to false etc."

This setting is now called "Umbraco.Core.UseHttps"
I think it would be nice if there was a "Fix" button like there are for other config issues.

![image](https://user-images.githubusercontent.com/13945979/53404812-55e9f700-39ae-11e9-9d6e-af5d5b801d9b.png)

**Comment by robertjf** [comment]
@Shazwazza could you please review this? :)

**Comment by robertjf** [comment]
I believe the reason the "Fix" button isn't present is because the site is running in HTTP unsecured.  It should show the fix button if the site is in Secure HTTPS.
