### ISSUE TITLE
v8: Reorder bar for grid get's stuck to top when no longer required

### ISSUE THREAD

**Issue by MMasey** [umbraco/Umbraco-CMS#4750]
If you have a doctype that has multiple sections, and one of them makes use of the `<umb-sticky-bar>`, if you scroll past that section, the sticky bar remains.

Reproduction
------------

1. Install Umbraco 8.0
2. Install the starter kit package
3. Go to the home page
4. Scroll past the "Content" sections

### Expected result

When you scroll past the content section containing the grid, the "reorder" bar should no long appear.

### Specifics

This bug looks like it could be fixed by adding a scroll limit to the `umb-sticky-bar` directive. Maybe updating the parent element selector functionality to that it uses the section as opposed to the whole window height, then we height of the section can be calculated to the `offsetTop` to determine when the sticky bar should no longer be active.

**Comment by nathanwoulfe** [comment]
PR #5573 fixes this - swapped out the existing umb-sticky-bar directive to use css position:sticky and IntersectionObserver to track scroll/intersection.
