### ISSUE TITLE
V8 Reorder grid row content won't reorder - cannot read property area of undefined

### ISSUE THREAD

**Issue by RobinHoody** [umbraco/Umbraco-CMS#4752]
When I reorder content (in a grid full width row) I get the following Javascript error - "Uncaught TypeError: Cannot read property 'area' of undefined" and the item won't reorder.

In the picture below, I have tried to drag headline above macro but it ends up in the state below:
![image](https://user-images.githubusercontent.com/4989076/53405028-d7418980-39ae-11e9-8baa-d95b8d61a715.png)

Reproduction
------------
### Bug summary
Reorder issue, reordering causes an error to be thrown in the JS Console. Looks like an issue with the plugin used to reorder.

### Specifics
I've created an umbraco 8 trial to test out the new features. It's just the small business site example content, then in the content section beneath the blog macro I've added a headline when I then tried to reorder the headline, I get the bug above and the reorder doesn't work. 

It's worth noting if I add another full width grid row and reorder the rows, that works as expected.

It's also worth noting I'm using language variants (english us & uk) to test the variants feature out so this was a variant but not the default and not in split mode.

### Steps to reproduce

1. Install a new umbraco 8 site on umbraco cloud.
2. Select template content - small business site.
3. Add language variants, English UK & US (this step may not be required to reproduce but this is what I did before seeing the bug).
4. Edit the home document type, allow language variants and edit the content property, allow content to vary by language.
5. On the home node, add a headline beneath the grid, in the full width row that already exists. Then click reorder, try to drag and reorder, you'll get a JS console error.

### Expected result

I expected the content items within the grid row to reorder.

### Actual result

The grid items won't reorder and throw a JS exception, you need to refresh the page to get back to a workable state.

**Comment by kjac** [comment]
@RobinHoody does this happen on newly created content as well or only on the content that was part of your template site? I can't reproduce it locally (on content created from scratch).

**Comment by nul800sebastiaan** [comment]
Same, I can't reproduce it with the starter kit, but I'm not sure what kind of starter kit is on Cloud, I would assume it's the default starter kit?

Ah, shoot.. Just found it, ClientDependency. When you set `debug="false"` in web.config I can also reproduce!

**Comment by RobinHoody** [comment]
> @RobinHoody does this happen on newly created content as well or only on the content that was part of your template site? I can't reproduce it locally (on content created from scratch).

I think it could be just the starter kit, I just used the default starter kit with cloud. @nul800sebastiaan did you reproduce with the starter kit or from scratch?

**Comment by nul800sebastiaan** [comment]
Yeah this was using the default starter kit. Setting `debug="false"` is making it fail, so it's something to do with CDF that's making it fail.

**Comment by nielslyngsoe** [comment]
PR: https://github.com/umbraco/Umbraco-CMS/pull/4803

**Comment by RobinHoody** [comment]
Thanks for looking at this so quickly guys!
