### ISSUE TITLE
V8: Selecting a proposed option when creating a user takes you away.

### ISSUE THREAD

**Issue by nielslyngsoe** [umbraco/Umbraco-CMS#4757]
When creating a user, and selecting a Email from the proposed options. The system tried to navigate away.

Seen on OSX, Chrome.

![image](https://user-images.githubusercontent.com/6791648/53414777-c6edd680-39cf-11e9-8f41-76e44e213836.png)

![image](https://user-images.githubusercontent.com/6791648/53414721-a160cd00-39cf-11e9-8815-644a563a54c6.png)

**Comment by emmanueltissera** [comment]
Issue replicated on Windows 10 - Google Chorme - Version 72.0.3626.109 (Official Build) (64-bit)
