### ISSUE TITLE
Change format of LocalizedText file to reduce page weight

### ISSUE THREAD

**Issue by PeteDuncanson** [umbraco/Umbraco-CMS#4759]
The back office gets a JSON object of all the translations a user needs for the labels etc. The format of this works but could be compressed somewhat to same some bytes.

Currently its all done like this:

```
...
actions_toInTheTreeStructureBelow: "In the tree structure below"
actions_translate: "Translate"
actions_unlock: "Unlock"
actions_unpublish: "Unpublish"
actions_update: "Update"
assignDomain_addNew: "Add new Domain"
assignDomain_domain: "Domain"
assignDomain_domainCreated: "New domain '%0%' has been created"
assignDomain_domainDeleted: "Domain '%0%' is deleted"
assignDomain_domainExists: "Domain '%0%' has already been assigned"
...

```

However if we nested translations by area in a JSON object then I think we would save quite a bit, something like this:

```
...
actions: {
	toInTheTreeStructureBelow: "In the tree structure below"
	translate: "Translate"
	unlock: "Unlock"
	unpublish: "Unpublish"
	update: "Update"
},
assignDomain {
	addNew: "Add new Domain"
	domain: "Domain"
	domainCreated: "New domain '%0%' has been created"
	domainDeleted: "Domain '%0%' is deleted"
	domainExists: "Domain '%0%' has already been assigned"
}
...
```

Doing a quick bit of cut and paste testing in a text editor I think I can get my 130kb file down to about 115kb file. Not a massive saving but every little helps and should be quite easy to do as only two points to touch to do it.

First you need to change the "shape" of the data we generate here:

https://github.com/umbraco/Umbraco-CMS/blob/91c52cffc8b7c70dc956f6c6610460be2d1adc51/src/Umbraco.Web/Editors/BackOfficeController.cs#L177

And then either change where/how we get it here:

https://github.com/umbraco/Umbraco-CMS/blob/dev-v8/src/Umbraco.Web.UI.Client/src/common/services/localization.service.js#L39

So that we take the new shape into account.

Or change the shape of the data back into a dictionary (ie flatten the object) so the existing code "just works". To do that you would need to loop over the objects after we've loaded the file here:

https://github.com/umbraco/Umbraco-CMS/blob/dev-v8/src/Umbraco.Web.UI.Client/src/common/services/localization.service.js#L85

**Comment by nul800sebastiaan** [comment]
Seems fine to me, not sure how many people would be relying on the `BackOfficeController.LocalizedText` method directly but they really shouldn't. At the same time, flattening it seems unnecessary - people should be using the `localizationService` for this anyway, I can't see a good reason to take the raw data and use it when we have a nice service for it.

Flattening would impact browser performance in a different way (ie: doesn't require bandwith but CPU). I don't know if the bandwith vs CPU tax outweigh each other, what do you think?

**Comment by nul800sebastiaan** [comment]
I've marked this as "Up for grabs" so that you or someone else coming along could create a pull request for it.

**Comment by PeteDuncanson** [comment]
@nul800sebastiaan thanks for flagging it as up for grabs. Its a small change but I fancied having a go at it.

BTW the localizationService gets its value from the LocalizedText file, see: 
https://github.com/umbraco/Umbraco-CMS/blob/dev-v8/src/Umbraco.Web.UI.Client/src/common/services/localization.service.js#L28

and

https://github.com/umbraco/Umbraco-CMS/blob/dev-v8/src/Umbraco.Web.UI.Client/src/common/services/localization.service.js#L82

So you are right no one should hit it directly however they are using those values via the service. Hence it being hopefully a minor change as its only touched in two places.

**Comment by nul800sebastiaan** [comment]
Fixed in https://github.com/umbraco/Umbraco-CMS/pull/5712

I've marked as breaking because there's a small possibility that a package might be relying on a removed property, I doubt it but.. just to be sure.
