### ISSUE TITLE
VS.2017 New UmbracoV8 - Error: Typen 'Umbraco.Web.UmbracoApplication' kunne ikke indlæses.

### ISSUE THREAD

**Issue by janborup** [umbraco/Umbraco-CMS#4761]
Greeting on the new Umbraco V8 release.

I have tried made a new clean Umbraco V8 from scratch.

Reproduction
------------
Visual Studio 2017.
- New Project - Blank C# Webproject
- Nuget PackageManager: "Install-Package UmbracoCms"
- Nuget update: "Microsoft.CodeDom.Providers.DotNetCompilerPlatform v.2.0.1"
Build project.
Run 

This produces the error:
----------------

Linje 1:  <%@ Application Inherits="Umbraco.Web.UmbracoApplication" Language="C#" %>

![umbracov8](https://user-images.githubusercontent.com/6866443/53426387-2c998d00-39e7-11e9-89f6-1ec6175eda65.png)

Parser error: Typen 'Umbraco.Web.UmbracoApplication' kunne ikke indlæses.

**Comment by nul800sebastiaan** [comment]
We've typically seen this error when VS2017 is not up-to-date. Can you check your exact version, from test results it seems like 15.9.7 is required:

![image](https://user-images.githubusercontent.com/304656/53429077-3376ce80-39ec-11e9-8a3a-de58970e1d7e.png)


Also make sure to double-check that you're creating a new project on .NET 4.7.2. 

I'll close this for now but make sure to update this if you still have trouble with that combination!

**Comment by janborup** [comment]
Weee... It's alive, @nul800sebastiaan Sebastian,

I got at VS.2017 ver. 15.8.8 so a VS update fix the problem.  H5YR 👍 

![vs_version_15 8 8](https://user-images.githubusercontent.com/6866443/53447347-36d28000-3a15-11e9-96ce-0d45c485f7c5.png)

**Comment by hannakfoo** [comment]
@nul800sebastiaan Its seems this issue is back with the latest version(s) of Visual Studio 2017 15.9.10 and for UmbracoV8 and 8.0.1 ... same steps to reproduce.
