### ISSUE TITLE
v8: Adding properties on the Folder media type, doesn't update the folder view

### ISSUE THREAD

**Issue by skttl** [umbraco/Umbraco-CMS#4764]
I tried adding some properties to the default Folder type, but they don't show when I go to a folder in the media section.

![billede](https://user-images.githubusercontent.com/3726467/53444434-70ec5380-3a0e-11e9-9ff5-c13fa869f044.png)

I was expecting either a content app for editing, or having the property shown on the list view. But nothing shows.

![billede](https://user-images.githubusercontent.com/3726467/53444476-8b263180-3a0e-11e9-9dca-c9a8b16d99c5.png)

**Comment by kjac** [comment]
Nice catch! PR in #4785
