### ISSUE TITLE
V8: DocType ReOrder - Error master.cshtml

### ISSUE THREAD

**Issue by janborup** [umbraco/Umbraco-CMS#4765]
Hi

I was trying to ReOrder the document type (Blogpost), to get "Content" first, "Navigation & SEO" second.

When looking in the DocumentType the order is correct, but even reorder, "Content" to bottom, and return, thows an exeption in the Master.cshtml line 5 :  
`    var home = (Home)Model.Root();
` 

![doctype_reorder_ 1](https://user-images.githubusercontent.com/6866443/53449735-d1818d80-3a1a-11e9-92c5-5c81b4cba362.png)

![doctype_reorder_ 2](https://user-images.githubusercontent.com/6866443/53449751-dd6d4f80-3a1a-11e9-8a53-b64b1dcf5383.png)

![doctype_reorder error](https://user-images.githubusercontent.com/6866443/53449757-e1996d00-3a1a-11e9-93be-6aace25965cf.png)

**Comment by nul800sebastiaan** [comment]
Hi @janborup - we currently don't support directly re-ordering compositions for the simple reason that it's impossible to tell where compositions are being used, re-ordering them on one document type might have the opposite effect on other document types. 

You can manually set the sort order on the composition itself, so update the number on the top right:

![image](https://user-images.githubusercontent.com/304656/54372721-358f8d00-467c-11e9-802f-a864a206199e.png)

and:

![image](https://user-images.githubusercontent.com/304656/54372746-48a25d00-467c-11e9-835b-cc8d1ebdfe17.png)

This will lead to the order you were hoping for: 

![image](https://user-images.githubusercontent.com/304656/54372802-67085880-467c-11e9-8c1e-62349ed7df10.png)


The error you're getting I can't reproduce, it seems unrelated.
