### ISSUE TITLE
V8: Creating a content template appears to fail

### ISSUE THREAD

**Issue by NikRimington** [umbraco/Umbraco-CMS#4774]
When attempting to create a content template a server side error is thrown:

    Exception Details
    System.InvalidOperationException: Cannot run a repository without an ambient scope.

Reproduction
------------

- Opened Visual Studio 2017 - version 15.9.7
- Installed Umbraco v8.0 via nuget
- Ran the installer - going "Custom" and installing the starter kit (using chrome at this point)

- Created an editor only user
- Logged in with FireFox into editor account

- Went to the blog node and attempted to create a content template of it, named it "blog-example" 
- Pressed return after giving it a name to try and save
- Got the error mentioned above.

- Went back to administrator account in Chrome
- Repeated process to try and create a content template
- Got same error

_Please note, I was meaning to make a content template of a blog post but accidentally selected blog without realising._

Hopefully that is enough steps to reproduce :-)

**Comment by kjac** [comment]
PR in #4782 (see remarks on the PR)
