### ISSUE TITLE
V8: Property Editor Slider Step Increments

### ISSUE THREAD

**Issue by uSkinned** [umbraco/Umbraco-CMS#4778]
The Property Editor "Slider" in Umbraco V8 no longer allows step increments of point values. Only whole numbers are permitted.

**Comment by kjac** [comment]
@uSkinned the new slider in V8 does not support point value step increments. 

Docs reference: https://refreshless.com/nouislider/

**Comment by uSkinned** [comment]
This is surely an issue, we use the slider for sitemap priority which should be in point values from 0.1 - 1

**Comment by kjac** [comment]
Looks like I'm wrong on this one. I'll update the PR.

**Comment by nul800sebastiaan** [comment]
Fixed in https://github.com/umbraco/Umbraco-CMS/pull/4821
