### ISSUE TITLE
V8: Change Property settings on Document Type

### ISSUE THREAD

**Issue by uSkinned** [umbraco/Umbraco-CMS#4781]
On an existing document type I changed the property editor of an existing property from one data type to another. Although the data type being used is updated. You do not see this change until you save the update and then refresh the page manually so it looks as if you havent made an update.

**Comment by nul800sebastiaan** [comment]
Hi @uSkinned - I can't reproduce this at the moment, what did you change into what exactly? Changing from Textbox to  Textarea worked just fine.

**Comment by uSkinned** [comment]
Hi Seb,

Just tested again and its not doing it now. Sorry to waste your time on this one.

Cheers,

Marc

**Comment by tom-ingeniuus** [comment]
I had this when changing from a textstring to a checkbox in v8.0.2 as shown in the attached screenshot interestGC hasn't updated
![property type icon doesnt update until reloading the page](https://user-images.githubusercontent.com/49899682/59063739-a8398e80-88a0-11e9-8947-5a5eff087b4f.PNG)
