### ISSUE TITLE
V8: Mediapicker errors

### ISSUE THREAD

**Issue by mcl-sz** [umbraco/Umbraco-CMS#4786]
In umbraco 8.0 when i choose an image using the Mediapicker, I'll get errors:
 Request error: The URL returned a 404 (not found):
/umbraco/backoffice/UmbracoApi/Entity/GetById  

and
 Request error: The URL returned a 404 (not found):
/umbraco/backoffice/UmbracoApi/MediaType/GetAllowedChildren 

For example this occures in the startkit in the "Products"-node selecting an image for the field "Photos".

**Comment by kjac** [comment]
@mcl-sz I don't see this on a fresh install. Which browser are you using? And could you maybe post a screencast to show how the issue unfolds?

**Comment by chrno1209** [comment]
Been using media-picker for a while on v8 with no issue like this.

**Comment by nul800sebastiaan** [comment]
This was a problem with the starter kit which is now fixed for fresh installs. The problem was that we set the wrong startnode on some of the media pickers.

Sorry for the inconvenience!

**Comment by jonicabrown** [comment]
I'm getting this exact issue on a fresh install of Umbraco version 10.3.2 (Umbraco Cloud, cloned and running locally). The master branch in the cloud seems to work though. Any idea how I can resolve this for my local environment?

**Comment by wpplumber** [comment]
>Request error: The URL returned a 404 (not found):
/umbraco/backoffice/UmbracoApi/MediaType/GetAllowedChildren

Seems like a related issue to what I [posted](https://github.com/umbraco/Umbraco-CMS/issues/13682)!
