### ISSUE TITLE
V8 UDUF - Content App Badges not being displayed

### ISSUE THREAD

**Issue by robertjf** [umbraco/Umbraco-CMS#4787]
Content App Badges are no longer being displayed even though they are present in the HTML when triggered.

**Comment by SoerenDeger** [comment]
@nul800sebastiaan I have updated to v8.0.1, but I don't see the badge in my content App. In the class is an "ng-hide":

![image](https://user-images.githubusercontent.com/7769446/54675521-0d31e380-4aff-11e9-8fb7-5a2abb7bddff.png)

And this is my code:

![image](https://user-images.githubusercontent.com/7769446/54675577-1f138680-4aff-11e9-8d8d-e22c100f4adf.png)

Is there another issue with this?

**Comment by nul800sebastiaan** [comment]
Not sure @SoerenDeger - works on the attached sample in issue #4791

![4787](https://user-images.githubusercontent.com/304656/54676578-423f3580-4b01-11e9-9cf4-117a157bef64.gif)

**Comment by SoerenDeger** [comment]
@nul800sebastiaan Ok, thank you. The badge from the attached sample doesn't work by me if I upgrade umbraco with nuget from 8.0.0 to 8.0.1. But, if install umbraco 8.0.1 in a new solution, it works like expected :-) I think it was a locally problem by me or trough the update process.
