### ISSUE TITLE
v8 - uduf - Some of the files in .github folder of dev-v8 still refer to dev-7

### ISSUE THREAD

**Issue by simonech** [umbraco/Umbraco-CMS#4800]
Not a real bug per se, but some files still have leftovers from the merge from dev-v7.

- CONTRIBUTING.md - has on the top the link to dev-8 (implying you are on dev-7 branch)
- CONTRIBUTING_DETAILED.md - refers to dev-7 as default branch and as branch to use to keep one's fork up to date
 - V8_GETTING_STARTED.md - links still to the zip release from CG18 and links to list of tasks for v8.0.0 (should be v8.1.0)

I'll send a PR asap

**Comment by AndersBrohus** [comment]
I saw the getting started so i made a PR here ... :)

https://github.com/umbraco/Umbraco-CMS/pull/4762

**Comment by simonech** [comment]
> I saw the getting started so i made a PR here ... :)
> 
> #4762

Yeah, still at CG18 it was 😄 
I fixes some other leftovers too

**Comment by AndersBrohus** [comment]
But what about the readme?
It's still says V8 is under development? :)

**Comment by simonech** [comment]
Yeah, I had noticed, but I leave it to people in HQ to update it. No real idea of the status. Editors track might be done indeed, definitely not the other 2

**Comment by nul800sebastiaan** [comment]
We've restructured and updated everything since then, I'll close this one.
