### ISSUE TITLE
V8: IE11 Image \ link picker doesn't work

### ISSUE THREAD

**Issue by JHHessels** [umbraco/Umbraco-CMS#4805]
The image picker and link picker doesn't work in Internet Explorer 11.

Javascript error:  TypeError: Object doesn't support property or method 'entries'. 
(It needs a  a polyfill.)

**Comment by Matthew-Wise** [comment]
Looking at the documentation IE11 is no longer supported:

> The Umbraco UI should work in all modern browsers:
> 
> Firefox (Latest)
> Chrome (Latest)
> Safari (Latest)
> Edge

https://our.umbraco.com/Documentation/Getting-Started/Setup/Requirements/

Hope this helps

Matt

**Comment by nul800sebastiaan** [comment]
Thanks @Matthew-Wise - indeed, we currently have no plans to support IE11 and put polyfills in for it. V8 will focus on modern browsers instead. Thanks for the report though @JHHessels !
