### ISSUE TITLE
Files in the Content folder from nuget package not copied/transformed on rebuild

### ISSUE THREAD

**Issue by drummerboy46** [umbraco/Umbraco-CMS#4808]
I've noticed that a number of folders and files do not get copied back to the working project directories when you pull a project back from TFS and kick off a rebuild in Visual Studio 2017.

Looking through the package folder it looks like the "Content" folder which contains...

Config/*
Media/*
Views/*
default.aspx
global.asax

Isn't being copied back and as necessary transforms performed.

Everything else seems to work OK on rebuild. This is very annoying when you're trying to give another developer access to an existing project and then having to instruct them to manually copy back some files before they can get started.

**Comment by nul800sebastiaan** [comment]
Sounds very annoying indeed, make sure to commit those files to source control though.

Make sure to read up on how the `.targets` file works as well, there's a mention in the docs at the end here: https://our.umbraco.com/documentation/Getting-Started/Setup/Install/install-umbraco-with-nuget#post-installation

Other than that, please head on over to the forum to get more help with this. :)
