### ISSUE TITLE
V8: Switch only return false in nested content

### ISSUE THREAD

**Issue by vonbarnekowa** [umbraco/Umbraco-CMS#4812]
When you have a switch in a nested content, it only returns false. We tested it on several installations and also in the nightly from last week and it doesn't work.

## how to reproduce
1. create a document type that contains a true/false field and tick the "is an Element type" box in the permissions.
2. create another document type that contains a nested content of the first document you created.
3. Create the second document type in the content tree and add some children to the nested content. You can check one child and uncheck another to see the result.
4. Show the true/false value of your nested content childs on the front-end of your site. The only value you will get is false even if some nested content's true/false are ticked.

Umbraco version: 8.0.0

**Comment by nul800sebastiaan** [comment]
Hi @vonbarnekowa - Unfortunately, this is not enough information for us to understand your problem. Can you please describe in detail:

* What are you trying to do (please describe all steps to reproduce the issue)
* What did you expect to happen?
* What actually happened?

**Comment by vonbarnekowa** [comment]
> Hi @vonbarnekowa - Unfortunately, this is not enough information for us to understand your problem. Can you please describe in detail:
> 
> * What are you trying to do (please describe all steps to reproduce the issue)
> * What did you expect to happen?
> * What actually happened?

Better?

**Comment by nul800sebastiaan** [comment]
👍

**Comment by nul800sebastiaan** [comment]
Whoops, closed the wrong issue, sorry!

**Comment by kjac** [comment]
PR in #4819

**Comment by tonyhtp** [comment]
Having the same issue in 8.0.0 - was just about to start issue when I found this!

**Comment by madsoulswe** [comment]
I hope this will be included in 8.0.1 =)

And maybe create a test site/page with all datatypes/valueconverters and test them =)

**Comment by rcasimiro** [comment]
Yes please! Include this in 8.01 👍
