### ISSUE TITLE
Bug/Error. Ошибка. Нельзя получить значение из checkbox

### ISSUE THREAD

**Issue by OAOVLD** [umbraco/Umbraco-CMS#4816]
Здравствуйте,

Bug/Error Нельзя получить значение из checkbox, когда он находится в Nested Content. Всегда получает false.

**Comment by dawoe** [comment]
Hi @OAOVLD

Unfortunatly most of us can't read or speak Russian. Could you create your bug report in English ?

Dave

**Comment by OAOVLD** [comment]
V8.0.0. Bug/Error. 

Hello,

You cannot get the value from a checkbox (True/False) when it is in Nested Content. Always returns false

**Comment by PerplexDaniel** [comment]
Seems to be a duplicate of #4812, probably better to close this one and continue in the other.

**Comment by nul800sebastiaan** [comment]
👍

**Comment by OAOVLD** [comment]
yes, thank
