### ISSUE TITLE
Bug/Error. Ошибка. Нельзя установить высоту для Rich Text Box

### ISSUE THREAD

**Issue by OAOVLD** [umbraco/Umbraco-CMS#4817]
Здравствуйте,
Bug/Error. Ошибка. Нельзя установить высоту для Rich Text Box (очень сильно раздражает контент-менеджеров, т.к. приходится прокручивать постоянно вверх если контента много). И новый тип Rich Text Box тоже работает с багами, при выделении текста невозможно выбрать формат (заголовок это или параграф), только на новой строке можно выбирать формат - это не удобно.
Решили это ошибку временно дописав свои стили для Rich Text Box для админки.

**Comment by dawoe** [comment]
Hi @OAOVLD 

Unfortunatly most of us can't read or speak Russian. Could you create your bug report in English ?

Dave

**Comment by nul800sebastiaan** [comment]
Hi there @OAOVLD - unfortunately we can not accept issues in Russian since none of us speak Russian, could you try it in English please?

**Comment by OAOVLD** [comment]
V8.0.0. Bug/Error.

Hello,

You can not set the height for RichTextBox (very annoying content managers, because you have to scroll constantly up if there is a lot of content). 

And the new type Rich Text Box (Distraction Free) also works with bugs, when you select the text you can not choose the format (h1 or p), only on a new line you can choose the format - it is not convenient.

We Solved this error temporarily adding their styles for RichTextBox for admin Umbraco :(

**Comment by skttl** [comment]
@OAOVLD can you share how you solved it?

I have the same problem - love the distraction free mode, but missing my formats selector :)

**Comment by skttl** [comment]
I found out :)

You need to set styleselect to mode=all in tinymceConfig.config
`<command alias="styleselect" name="Style select" mode="All" />`

@nul800sebastiaan what is HQs opinion on this? Shouldn't style select be available for selection? Or maybe have it configurable by the prevalue editor?

**Comment by nul800sebastiaan** [comment]
@skttl Yeah, it should be available in distraction-free mode too. Care to send a PR? Remember there's the tinyMceConfig.config and tinyMceConfig.Release.config to update. 

The original issue reported here (not being able to set the height) has since been fixed in 8.1.0, so I'll close this issue.
