### ISSUE TITLE
v8: Selection in copy and move dialog doesn't look right

### ISSUE THREAD

**Issue by bjarnef** [umbraco/Umbraco-CMS#4826]
In the copy dialog on a content node the selection doesn't look right.

On init the current node is selected/highlighted, but when selecting other nodes, it set checkmark icon on these tree node, while the current node keep its highlight.
Furthermore this doesn't seem to be consistent with how selection looks like in e.g. content listview and other tree pickers.

This same seems to be an issue in move dialog.

![2019-03-03_16-15-23](https://user-images.githubusercontent.com/2919859/53697269-326ce500-3dd0-11e9-8473-1b44f5dd1706.gif)

**Comment by nul800sebastiaan** [comment]
Good one! 

I've marked this as "Up for grabs" so that you or someone else coming along could create a pull request for it.

**Comment by nul800sebastiaan** [comment]
This issue has been in the `up for grabs` state for quite a while now and it seems nobody is ready to pick this one up.

For now we'll close this issue to prevent the list of `up for grabs` from becoming very stale. We're happy to re-open it if someone still thinks it's good to work on this.

If anyone is about to pick this issue up to fix it, make sure to test first if you can reproduce the problem in the latest version before you start to work on it.

Thanks!
Sebastiaan on behalf of Umbraco HQ.
