### ISSUE TITLE
v8: Multiple media picker always return null

### ISSUE THREAD

**Issue by chrno1209** [umbraco/Umbraco-CMS#4827]
### Steps to reproduce
Having a document type with a property of media picker with configuration:
Pick multiple items: true
Pick only images: true
Disable folder select: true or false

By using models builder, model property returns IEnumerable<Image>

### Expected result
On view, property returns `IEnumerable<Image>`

### Actual result
Always return null

### Workaround
The model tries to cast property's value to `IEnumerable<Image>` but fails, trying with `List<IPublishedContent>` is successful.

**Comment by bergmania** [comment]
PR: https://github.com/umbraco/Umbraco-CMS/pull/4844
