### ISSUE TITLE
v8: Public access doesn't show overlay behind backdrop

### ISSUE THREAD

**Issue by bjarnef** [umbraco/Umbraco-CMS#4828]
When opening public access and using either specific members protection or group based protection and then opening the pickers, it doesn't hide this left overlay behind to backdrop, when the picker overlay (right) is opening and it is possible to open several overlays.

![image](https://user-images.githubusercontent.com/2919859/53697423-2cc3cf00-3dd1-11e9-844d-419678773ca5.png)

So the editor can actually go crazy to open overlays and clicking close in the left dialog/overlay, doesn't close all these right dialog/overlay.

![image](https://user-images.githubusercontent.com/2919859/53697513-271ab900-3dd2-11e9-8611-7818a294faac.png)

![2019-03-03_16-30-20](https://user-images.githubusercontent.com/2919859/53697527-46b1e180-3dd2-11e9-854c-0785d0549e94.gif)

**Comment by nul800sebastiaan** [comment]
Wow, that's a lot of layers! 😂

**Comment by bjarnef** [comment]
I guess that's inifinite editing 😂

**Comment by nielslyngsoe** [comment]
PR https://github.com/umbraco/Umbraco-CMS/pull/5079
