### ISSUE TITLE
v8: Slider with mandatory checked and initial value fails validation

### ISSUE THREAD

**Issue by chrno1209** [umbraco/Umbraco-CMS#4830]
### Steps to reproduce
Slider with:
- Mandatory checked
- Initial value

### Expected result
Passes validation when save/publish as it already had a value

### Actual result
Fails validation

**Comment by nul800sebastiaan** [comment]
What if the initial value is the value you wanted to set? Then you'd need to change to a different value first and then change it back to the initial value.

**Comment by chrno1209** [comment]
@nul800sebastiaan that's just a workaround and I am doing it to pass validation, but when you have initial value, that means the slider has value even when you haven't done anything yet.

**Comment by nul800sebastiaan** [comment]
Yes, I understand but what I'm saying is:

- If you set an initial value then.. surely this could be the CORRECT value that the editor wants to set
- So the editor naively goes: thanks, I don't need to do anything, I can just publish this straight away
- Then Umbraco will go: not so fast buddy, your slider is at the initial value, but you're required to change it
- Which then is impossible for the editor to figure out

So your proposed fix would cause more friction than the current version, it doesn't seem like something we would want.
