### ISSUE TITLE
In doctype editor number navigation is not working

### ISSUE THREAD

**Issue by rasmusfjord** [umbraco/Umbraco-CMS#4833]
In doctype editor number navigation is not working with the numbers to shift the panels.

Tested in latest Chrome, on umbraco 8.

**Comment by Shazwazza** [comment]
yup this is a duplicate, will be in an upcoming 8.x release

https://github.com/umbraco/Umbraco-CMS/pull/4798
https://github.com/umbraco/Umbraco-CMS/issues/4757

**Comment by rasmusfjord** [comment]
#speedyGonsales ;)
