### ISSUE TITLE
V8: Uaas.cmd tool gives error on Umbraco 8

### ISSUE THREAD

**Issue by Aaen** [umbraco/Umbraco-CMS#4836]
When you are using the UaaS.cmd tool from https://our.umbraco.com/documentation/Umbraco-Cloud/Set-Up/Working-With-Visual-Studio/ with an Umbraco 8 project you are getting an error in the tool.

Reproduction
------------

Download the tool from https://our.umbraco.com/documentation/Umbraco-Cloud/Set-Up/Working-With-Visual-Studio/ and start the tool. Add in the URL for the project and then you will see the error

**Comment by Aaen** [comment]
![image](https://user-images.githubusercontent.com/2038482/53727719-29802000-3e71-11e9-99d7-1f183a2756ff.png)

**Comment by bergmania** [comment]
I'm using it with my v8 cloud project without issues. Maybe this is project specific?

**Comment by Aaen** [comment]
@bergmania I have two customers and myself as well that are seen this. I will send you the project that I have tested with.

**Comment by hartviglarsen** [comment]
This worked fine for me.. I did have to manually change the .gitignore and change the target framework for my .Core project.

**Comment by KennethJakobsen** [comment]
Workaround for v8:
This however means that you need to manage your dependencies manually.

1. Copy git-url from portal.
2. Open UaaS.cmd
3. Change *.Core project framework from 4.5 to 4.7.2
4. Install-Package UmbracoCms.Core in core project
5. Git init in root project folder
6. Add *.Web project folder to root folder .gitignore 

This works pretty well for me - albeit a workaround.
I'm probably missing something but this works fine for the needs I had so far.

**Comment by Frost117** [comment]
@Aaen Could you allow the Waasp to have access to your network? 

I had a customer who had the same issue and when he ran it as a administrator it worked for him

**Comment by nul800sebastiaan** [comment]
This error is caused by the fact that Forms no longer has a version file on disk in v8.

Work has started on a newer version of this tool, which is in testing now. Save the text below as `UaaS.cmd` and give it a go.

Note: this new version ONLY works with VS2017 and higher.

```
@ECHO OFF
ECHO One second...
ECHO Downloading helper executable (Waasp.exe)
powershell -ExecutionPolicy Bypass -Command "(New-Object Net.WebClient).DownloadFile('https://umbracoreleases.blob.core.windows.net/download/Waasp2.exe', 'Waasp.exe')"
SET /P url="Clone URL: " 
SET /P alias="Namespace: "
SET uaasguid=%url:~-40%
SET uaasguid=%uaasguid:.git=%
IF NOT EXIST %alias%.Web (
    git clone %url%
)
IF EXIST %uaasguid% REN %uaasguid% %alias%.Web
Waasp.exe "%CD%" %alias% %url%
DEL Waasp.exe /Q
```
