### ISSUE TITLE
Support getting multiple members by id

### ISSUE THREAD

**Issue by bjarnef** [umbraco/Umbraco-CMS#4837]
Umbraco.Member() has 5 overloads, but only to fetch a single member by int id, object id, string id, Guid id or Udi id.

There are no methods to fetch multiple member like `Umbraco.Content` and `Umbraco.Media` have overload methods to fetch multiple `IPublishedContent` nodes.

There is another issue to fetch members by type. https://github.com/umbraco/Umbraco-CMS/issues/4835

**Comment by kjac** [comment]
PR in #4877
