### ISSUE TITLE
v8 - if you publish an unpublished content item with the "Content" content app visible the new URL will not display

### ISSUE THREAD

**Issue by Shazwazza** [umbraco/Umbraco-CMS#4855]
This video should show the problem https://www.screencast.com/t/cHvCXfFD

But basically, if you publish an unpublished item (in this case invariant) when you have the "Content" app visible, and then move to the "Info" app, the URL will not be shown, but if you refresh the item, the URL is there so it's some angular wiring problem.

If however, you publish the item when the Info app is visible, the URL will show up

**Comment by NikRimington** [comment]
I'm assuming directly relate (or even the same issue) but the URL on info doesn't update if you change the name of the page and publish when "content" app is visible.

**Comment by kjac** [comment]
PR in #4876
