### ISSUE TITLE
V7 - Umbraco automatic redirects don't always get generated

### ISSUE THREAD

**Issue by NikRimington** [umbraco/Umbraco-CMS#4860]
When renaming a node in Umbraco, the common behaviour is that a redirect gets put into the redirect table mean visitors are automatically redirected to the updated URL. However, it is possible for this redirect not to be generated.

## Steps to reproduce

1. Install a clean version of Umbraco (at time of writing only tested on v7 but will update with v8 test results)
2. Run through the installer and let the starter kit install
3. Goto the biker-jacket page in the back office
4. Visit the current URL for the biker-jacket page and confirm the page works (do not close this page we need it later)
5. In the back office, change the name of the page from "Biker Jacket" to "Biker Jacket Changed"
6. **Click SAVE - NOT Save and Publish**
7. Confirm original URL still works (from step 4)
8. Click Save and Publish
9. Refresh original URL (from step 4 or step 7)
10. Get 404 Page not found error because no redirect is in place.
11. Confirm that the new URL is a valid URL by getting it from the info tab of the page.

### Expected result

I would expect the site to put the redirect in place from the old URL to the new URL

### Actual result

404 error occurs due to how the code on lines 180 - 184 on the RedirectTrackingEventHandler.cs file checks if a redirect is needed.

**Comment by NikRimington** [comment]
V8 update - My initial tests indicate that this issue has been resolved for v8

**Comment by nul800sebastiaan** [comment]
@nathanwoulfe Aha! That sounds correct.. and so easy! Might just be it. :-)

Care to create a PR for it?

**Comment by nathanwoulfe** [comment]
Yup, will do - I've put a fix in on our site, will verify that works correctly before creating a PR.

**Comment by nul800sebastiaan** [comment]
Fixed in https://github.com/umbraco/Umbraco-CMS/pull/5036
