### ISSUE TITLE
V8: Build is failing with Gulp issue

### ISSUE THREAD

**Issue by PeteDuncanson** [umbraco/Umbraco-CMS#4861]
I've been trying to get V8 up and running locally now for the best part of a day. As its been nearly a year since I did it I'm hitting a lot of issues as my machine is just not setup/installed with whats needed it seems.

I've posted some of my finding here:

https://our.umbraco.com/forum/umbraco-8//96052-error-with-microsoftcodedomproviders-when-trying-to-run-compiled-v8-source

But this is more of a heads up about issues that could/should be fixable.

The current /build/build.ps1 script file makes the assumption that you have right version of gulp install when it builds. Out of the box you won't and I couldn't find anything to say I needed to. I've found a /src/Umbraco.Web.UI.Client/setupgulp.bat file which seems to install Gulp but it still complainswill fix this if run first. Could the build script not run this bat file for us or check the gulp version number or something to ensure its installed? 

I'm confused as to why this bat file exists, isn't this what the package.json file is for? Shouldn't this just be "done" via a "npm install"? 

Worst case we can just add it to the "Quick start" guide (https://github.com/umbraco/Umbraco-CMS/blob/dev-v8/.github/V8_GETTING_STARTED.md) as something that is needed to be done as a one off manually.

**Comment by nul800sebastiaan** [comment]
That sucks. We try to install all the correct versions of everything for you locally. We'll delete setupgulp.bat soon, build.ps1 needs to be the only one. So what is the problem with build.ps1? Error messages?

Also, this is not significantly different from v7, I assume that also doesn't work on your machine?

**Comment by PeteDuncanson** [comment]
Error message:

`PS C:\work\Umbraco-CMS-V8\Umbraco-CMS\build> .\build.ps1
Umbraco Cms Build
Umbraco.Build v0.2.2
Found already existing web.config.temp-build
(will be restored after build)
Create clean web.config
Set environment
Restore NuGet
Logging to C:\work\Umbraco-CMS-V8\Umbraco-CMS\build.tmp\nuget.restore.log
Compile Belle
Logging to C:\work\Umbraco-CMS-V8\Umbraco-CMS\build.tmp\belle.log
Exception calling "Build" with "0" argument(s): "Exception calling "CompileBelle" with "0" argument(s): "Failed to
build""
At C:\work\Umbraco-CMS-V8\Umbraco-CMS\build\build.ps1:478 char:5
+     $ubuild.Build()
+     ~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : ScriptMethodRuntimeException

Error!

MethodInvocationException: Exception calling "Build" with "0" argument(s): "Exception calling "CompileBelle" with "0" argument(s): "Failed to build""
At C:\work\Umbraco-CMS-V8\Umbraco-CMS\build\build.ps1:478:5
+ $ubuild.Build()

MethodInvocationException: Exception calling "CompileBelle" with "0" argument(s): "Failed to build"
At C:\work\Umbraco-CMS-V8\Umbraco-CMS\build\build.ps1:431:5
+ $this.CompileBelle()

RuntimeException: Failed to build
At C:\work\Umbraco-CMS-V8\Umbraco-CMS\build\build.ps1:119:24
+ if (-not $?) { throw "Failed to build" } # that one is expected to work

RemoteException:     throw err;
    ^

AssertionError [ERR_ASSERTION]: Task function must be specified
    at Gulp.set [as _setTask] (C:\work\Umbraco-CMS-V8\Umbraco-CMS\src\Umbraco.Web.UI.Client\node_modules\undertaker\lib\set-task.js:10:3)
    at Gulp.task (C:\work\Umbraco-CMS-V8\Umbraco-CMS\src\Umbraco.Web.UI.Client\node_modules\undertaker\lib\task.js:13:8)    at Object.<anonymous> (C:\work\Umbraco-CMS-V8\Umbraco-CMS\src\Umbraco.Web.UI.Client\gulp\tasks\docs.js:13:6)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)

At C:\work\Umbraco-CMS-V8\Umbraco-CMS\build\build.ps1:118:9
+ npx gulp build --buildversion=$this.Version.Release >> $log 2>&1`

**Comment by NikRimington** [comment]
Having just compiled the v8 source I had to go through the following steps to get it to work:

1. Clone the v8 branch
2. Open the VS project
3. Get the Nuget Packages to all restore (this was tricky and I ended up having to completely clear my Nuget Cache else it said they were restored by they weren't) - See comment below which I believe could be part related to it.
4. Build the project in Visual Studio - Note: build.ps1 failed when doing this saying that \build\build.ps1 was an invalid commandlet
5. Run build.ps1 from powershell
6. Finally everything seemed to work.

When I first cloned it, I did try just running build.ps1 but got a bunch of errors mainly relating to Nuget and some feeds not being available - I'm assuming this is due to my machine having a couple of legacy local nuget feeds that are no longer available still being configured.

(Not sure if any of this helps but thought it worth sharing on here)

**Comment by zpqrtbnk** [comment]
Quick note: the build script is supposed to install node, gulp, whatever - and do everything by itself - if that's not the case then something has been broken - there should be no bat file to run - dunno where this is coming from - will look into it

**Comment by zpqrtbnk** [comment]
just for info - I freshly cloned from GitHub and fired Powershell, making sure I had no node, npm, nothing in my path - then launched `build/build.ps1` - and it builds without errors

I'm still reviewing the errors reported above to understand what's going on - we might be too sensitive to the environment or something

**Comment by PeteDuncanson** [comment]
Had a good play around withe Seb on a screen share (happy to do the same with you if it would help) and found that I had Gulp v4 installed and not v3 which Seb had installed. Seems they changed the format of the gulp files in v4 which is blowing up somewhere. I'm going to revert back to v3 and see if that works. If it does I'm going to look into a PR to upgrade the gulp file to be in v4 format if I can.

**Comment by zpqrtbnk** [comment]
nice - what I don't get is ... it's `build.ps1` that should download and install node and npm and gulp and everything - how did you end up having the wrong gulp? did you manually upgrade it?

**Comment by nul800sebastiaan** [comment]
The failure was a result of this commit still being present in Pete's clone: https://github.com/umbraco/Umbraco-CMS/pull/4847

I expect rolling that back would work so I'll close this for now.

**Comment by PeteDuncanson** [comment]
Ahhh that makes sense!
