### ISSUE TITLE
Element types should not inherit from non-element types

### ISSUE THREAD

**Issue by zpqrtbnk** [umbraco/Umbraco-CMS#4863]
Apart from making no sense, an element type inheriting from a non-element type breaks Models Builder. See Models Builder [issue 188](https://github.com/zpqrtbnk/Zbu.ModelsBuilder/issues/188).

It should not be possible for an element type to inherit from a non-element type. Which means that, when picking compositions for an element type, it should only be possible to pick element types - and then, it should not be possible to flip an element type back to non-element if it is involved in a composition.

**Comment by nul800sebastiaan** [comment]
While https://github.com/umbraco/Umbraco-CMS/pull/6136 doesn't fully fix the issue, I think we should have new issues created for the remaining parts. Closing this for now.
