### ISSUE TITLE
v8: Grid settings/styles dialog doesn't animate

### ISSUE THREAD

**Issue by bjarnef** [umbraco/Umbraco-CMS#4867]
When opening settings/styles from grid, it doesn't animate in from right and doesn't have the dark backdrop as most other dialog/overlays in v8, e.g. in infinite editing.

![image](https://user-images.githubusercontent.com/2919859/53806654-cb753a80-3f4d-11e9-8641-6c1ddceae273.png)

![image](https://user-images.githubusercontent.com/2919859/53806663-d203b200-3f4d-11e9-989f-bc8701dab630.png)

![image](https://user-images.githubusercontent.com/2919859/53806671-dd56dd80-3f4d-11e9-9d20-4bae224400b2.png)

![image](https://user-images.githubusercontent.com/2919859/53806699-f3649e00-3f4d-11e9-951d-31498d10125e.png)

**Comment by bjarnef** [comment]
It also seems the media picker overlay doesn't have the title as it used to have?

**Comment by bjarnef** [comment]
It seems to be related to `umbOverlay`, when using this with e.g. `position="right"`, the dialog is by default `show="false"` and then change `show="true"` e.g. after clicking a button, then it looks like this, which doesn't have same backdrop color and doesn't animate from right.

![image](https://user-images.githubusercontent.com/2919859/53963495-ba632f80-40ed-11e9-802d-2c1ac7dc7531.png)

Note the `umbOverlay` supports four different positions, so if animating from right, it should probably only use this with position `right`. Maybe position `left` should also animate (from left), not sure about whether `center` and `target` should animate.
https://github.com/umbraco/Umbraco-CMS/blob/91c52cffc8b7c70dc956f6c6610460be2d1adc51/src/Umbraco.Web.UI.Client/src/common/directives/components/overlays/umboverlay.directive.js#L193

**Comment by bjarnef** [comment]
This issue is fixed in https://github.com/umbraco/Umbraco-CMS/pull/4971 where it change grid settings/styles to infinite editing.

**Comment by bjarnef** [comment]
@nul800sebastiaan I think you can close this one.

**Comment by nul800sebastiaan** [comment]
Thanks @bjarnef just saw this now, a bit late 🙈
