### ISSUE TITLE
Upgrade Gulp file to support Gulp v4 file format

### ISSUE THREAD

**Issue by PeteDuncanson** [umbraco/Umbraco-CMS#4869]
Gulp v4 is out and the current gulp file fails if run with it. Would be nice if possible to upgrade to the newer versions file format which should make for some performance improvements in the build times and remove the need for "run-sequence" module. 

It also means this fix can be merged in #4847 too as that needs Gulp v4.

Should be aware of the comment about the docs task here #3816 from Mads.

**Comment by PeteDuncanson** [comment]
Good explainer of the issue I think we are having with the format changes here: https://fettblog.eu/gulp-4-parallel-and-series/

**Comment by nul800sebastiaan** [comment]
I'll merge this issue with #4846 as they both need to be fixed at the same time.
