### ISSUE TITLE
v8: Adjust new styles of checkboxes/radiobuttons

### ISSUE THREAD

**Issue by bjarnef** [umbraco/Umbraco-CMS#4887]
In noticed the updated/custom styles of checkboxes/radiobuttons in latest v8.

I think the `umb-form-check` should use `display: inline-flex` or similar fix, so the checkbox/radiobutton labels isn't stretched to full width.

```
.umb-form-check {
    display: flex;
    flex-wrap: wrap;
    align-items: center;
    position: relative;
    padding: 0;
    margin: 0;
    min-height: 22px;
    cursor: pointer!important;
}
```

Furthermore it seems to top position can just be set to 0 and add `margin-top: 1px;` for `umb-form-check__state`.

```
.umb-form-check__state {
    height: 17px;
    position: absolute;
    top: 2px;
    left: 0;
}
.umb-form-check__text {
    margin: 0 0 0 26px;
    position: relative;
    top: -1px;
    line-height: 20px;
}
```

**Chrome**
![image](https://user-images.githubusercontent.com/2919859/53880965-b7474100-4012-11e9-95db-873ae623619c.png)

**IE11**
![image](https://user-images.githubusercontent.com/2919859/53881011-cfb75b80-4012-11e9-9983-3b39981723f0.png)

With this change it also looks nicer in IE with this change + `line-height: 22px;` .

![image](https://user-images.githubusercontent.com/2919859/53881075-01302700-4013-11e9-8882-b2fd323dcca5.png)

```
.umb-form-check {
    display: flex;
    flex-wrap: wrap;
    align-items: center;
    position: relative;
    padding: 0;
    margin: 0;
    min-height: 22px;
    line-height: 22px;
    cursor: pointer!important;
}
.umb-form-check__state {
    height: 17px;
    position: absolute;
    top: 0;
    left: 0;
}
.umb-form-check__text {
    margin: 0 0 0 26px;
    position: relative;
    top: 0;
    line-height: 20px;
}
.umb-form-check__icon:before {
    position: absolute;
    top: 0;
    right: 0;
    left: 0;
    bottom: 0;
    margin: auto;
    display: flex;
    justify-content: center;
    align-items: center;
}
```

**IE**
![image](https://user-images.githubusercontent.com/2919859/53881282-929f9900-4013-11e9-914f-10e0852ae0b2.png)

**Comment by nul800sebastiaan** [comment]
Note: we don't support IE on v8 :)

**Comment by bjarnef** [comment]
Maybe also consider if the color in checkboxes should be reverted like this.

![image](https://user-images.githubusercontent.com/2919859/53881685-91bb3700-4014-11e9-883d-05fbfdc395e0.png)

In this example the icon font is changed to:

```
font-size: 12px;
font-weight: bold;
```

**Comment by bjarnef** [comment]
@nul800sebastiaan I know, but also in Chrome the labels are not aligned with the checkbox/radiobutton.
Also in Edge the checkmark icon is not exactly in center, which the mentioned css change fix :)

![image](https://user-images.githubusercontent.com/2919859/53881851-fd9d9f80-4014-11e9-870f-8d9f9429115d.png)

**Comment by nul800sebastiaan** [comment]
Sure, @nielslyngsoe says it's all good but he  doesn't think the colors should be inverted. We're happy to look at a PR!

**Comment by bjarnef** [comment]
In it current styling it is a bit hard to see when checkboxes are focused using tab key,
Here "Citrus" is focused.

![image](https://user-images.githubusercontent.com/2919859/53882091-a3510e80-4015-11e9-98df-de31b6351466.png)

![image](https://user-images.githubusercontent.com/2919859/53882165-d98e8e00-4015-11e9-80a1-3a2c94061aeb.png)

**Comment by bjarnef** [comment]
Maybe the checkbox/radiobutton should also have a background color, so they don't seem to be disabled in e.g. Nested Content.

![image](https://user-images.githubusercontent.com/2919859/53882835-a9e08580-4017-11e9-9331-81e1bbb0598d.png)

Maybe also consider how the disable style look. At the moment it doesn't seem to directives support this, but they probably should using `ng-disabled`.

**Comment by bjarnef** [comment]
I guess @nielslyngsoe also can use to `disabled` state here https://github.com/umbraco/Umbraco-CMS/pull/4891 where mandatory languages are auto selected (I guess these could just be selected and disabled?).

**Comment by nielslyngsoe** [comment]
Defenetly, would be useful with disabled state. And I as well have a error-state in mind. But let’s take them individually as separate tasks :-D

**Comment by bjarnef** [comment]
@nielslyngsoe I can send a PR for the disable state.
The checkbox and radiobutton should probably also have some kind of hover style, e.g. like these https://www.w3schools.com/howto/howto_css_custom_checkbox.asp

**Comment by bjarnef** [comment]
Furtermore I don't think it is valid to have `<div>` nested inside `<label>` and should therefore be changed to `<span>` instead.

```
<label class="checkbox umb-form-check umb-form-check--checkbox">
    <input type="checkbox" name="{{name}}"
           value="{{value}}"
           ng-model="model.checked"
           class="umb-form-check__input"
           ng-required="required"
           ng-change="onChange(model)"/>

    <div class="umb-form-check__state umb-form-check__state" aria-hidden="true">
        <div class="umb-form-check__check">
            <i class="umb-form-check__icon icon-check"></i>
        </div>
    </div>
    <span class="umb-form-check__text">{{text}}</span>
</label>
```

**Comment by bjarnef** [comment]
PR here https://github.com/umbraco/Umbraco-CMS/pull/4902
