### ISSUE TITLE
v8: Bug speed for "public interface IContentService : IContentServiceBase, IService". saving 500 items lasts 10 minutes!

### ISSUE THREAD

**Issue by OAOVLD** [umbraco/Umbraco-CMS#4893]
Hello!
v8: Bug speed for "public interface IContentService : IContentServiceBase, IService". saving 500 items lasts 10 minutes!

RUS: Не хватает следующих методов (т.к. удаление/добавление по одному занимает очень долгое время):
EN: The following methods are missing (because deleting / adding one by one takes a very long time):

OperationResult Delete(IEnumerable<IContent> contents, int userId = -1);
PublishResult SaveAndPublish(IEnumerable<IContent> contents, string[] cultures, int userId = -1, bool raiseEvents = true);
PublishResult SaveAndPublish(IEnumerable<IContent> contents, string culture = "*", int userId = -1, bool raiseEvents = true);

RUS: Не хватает оптимизации по скорости для следующих методов (т.к. сохранение 500 страниц занимает очень долгое время):
EN: Speed optimization is not enough for the following methods (because saving 500 pages takes a very long time):
OperationResult Save(IEnumerable<IContent> contents, int userId = -1, bool raiseEvents = true);

Example: 

foreach(var elem in list){

// ....
// code (list.Count = 500 elements)
// ....

IContent document = Services.ContentService.Create(name: $"{elem_Region} - {elem_Name}", parentId: this.Doc_XXXXX_Code, documentTypeAlias: this.Doc_XXXXX_Child);
document.SetValue("Content_Region", elem_Region);
document.SetValue("Content_Name", elem_Name);
document.SetValue("Content_FIO", elem_FIO);
document.SetValue("Content_Adress", elem_Adress);
document.SetValue("Content_Phone", elem_Phone);
document.SetValue("Content_Email", elem_Email);
if (!string.IsNullOrWhiteSpace(elem_Site_JSON))
{
	document.SetValue(propertyTypeAlias: "Content_Site", value: elem_Site_JSON);
}
//Services.ContentService.SaveAndPublish(document); // TODO: to correct speed, a very long time for 500 elements. 10 min !!!
document_List.Add(document);
}

Services.ContentService.Save(contents: document_List); // TODO: to correct speed, a very long time for 500 elements. 10 min !!!

// -------------------
// RUS: Если есть решение этой проблемы, то сообщите пожалуйста
// EN: If there is a solution to this problem, please let us know

**Comment by nul800sebastiaan** [comment]
If you have concrete suggestions as to how to make these operations faster then we look forward to seeing a pull request with code updates. 

For now I'll close this issue. SaveAndPublish is an expensive operation and we're happy with the current performance which works well for publishing a small to medium amount of content. 

On a sidenote: this operation (creating and publishing 500 nodes) took about 4 minutes on my machine on a slow database connection, I think part of your problem might be your system setup.

First page, published on 4:35
![image](https://user-images.githubusercontent.com/304656/53893548-b6240d00-402e-11e9-88cb-a75876be75d4.png)

Last page, published on 4:39
![image](https://user-images.githubusercontent.com/304656/53893605-cc31cd80-402e-11e9-88c0-50a36af63018.png)

**Comment by OAOVLD** [comment]
thank
