### ISSUE TITLE
V8: Strengthen Babel's browser targets to only include supported browsers

### ISSUE THREAD

**Issue by PeteDuncanson** [umbraco/Umbraco-CMS#4894]
Short version: Setup Babel via a small config change to only support the browsers that Umbraco offically supports.

Long version: In the current tool chain we have Babel included for transpiling our javascript from ES6 down to ES5 syntax. Currently I can't see where we are using any ES6 but I suspect its in there to make us future proof and its something that we should be looking to move towards.

With the release of V8 there is a new list of supported browsers here:

https://our.umbraco.com/documentation/Getting-Started/Setup/Requirements/

Babel when it converts js code to run on older browsers will include polyfills and shims if needed to get the code to work. This can lead to bloated bundles if you don't tell Babel which browsers you want to support. Umbracos new browser support list is really modern (no IE11! Woot!) so we can tell Babel which browsers to include and this should great reduce the amount of boiler plate it would inject in.

As I can't see which files we would need Babel for as is (ie I've not come across any ES6 features as yet) this change wont make much of a difference as yet (Babel will only inject in the features you use so if we aren't using any ES6 then it won't inject anything in, no shims are required) but should set us up for the future should we move that way.

Using Babel also gets around the issue that we think Client Dependency doesn't support ES6 code either natively (only if its transpiled by the likes of Babel).

**Comment by nul800sebastiaan** [comment]
Note: ClientDependency is not yet ES6 aware, which is why we need ES5 syntax.

**Comment by PeteDuncanson** [comment]
Issue regarding Client Dependancy ES6 support (or lack of it) is here: https://github.com/Shazwazza/ClientDependency/issues/160

Docs on browser targeting for Babel are here: https://babeljs.io/docs/en/babel-preset-env
