### ISSUE TITLE
Schema health check returns SQLException error - Invalid object name 'dbo.umbracoUserType'

### ISSUE THREAD

**Issue by Geckex** [umbraco/Umbraco-CMS#4896]
Running Schema health check returns SQLException error - Invalid object name 'dbo.umbracoUserType'
Would it be possible to rename this database table

**Comment by Geckex** [comment]
Running Schema health check returns SQLException error - Invalid object name 'dbo.umbracoUserType'
Would it be possible to rename this database table

**Comment by nul800sebastiaan** [comment]
@Geckex Which Umbraco version are we talking about please? And why would we rename that table?

**Comment by pwasik** [comment]
Hi,
sorry to get back to this query so late.
We're on 7.12.4. The table is not present in the database, but have been in previous versions of Umbraco. Had it been removed or renamed to another by any chance?

**Comment by nul800sebastiaan** [comment]
I see, this table was deleted in v7.7.0 - you should not have it in your database and you can just delete it, this is why the health check tells you about it, the table is invalid :-)
