### ISSUE TITLE
Update picker in Multi Node TreePicker to match other pickers

### ISSUE THREAD

**Issue by bjarnef** [umbraco/Umbraco-CMS#4905]
In MNTP config the styling should match the "add" and "preview" in other pickers, e.g. in content picker.

![image](https://user-images.githubusercontent.com/2919859/53944138-0d71be00-40bf-11e9-801c-9b06f6b05a69.png)

**Comment by nul800sebastiaan** [comment]
👍

I've marked this as "Up for grabs" so that you or someone else coming along could create a pull request for it.

**Comment by kjac** [comment]
Yes! This has annoyed me too... PR in #4930
