### ISSUE TITLE
Site Tree shows the green bar on page preview, even though nothing has changed

### ISSUE THREAD

**Issue by HistoricEnglandDigitalTeam** [umbraco/Umbraco-CMS#4917]
This is a long standing issue which is still present in Umbraco v7.13.2. (U4-9912 in pre-GitHub threads). Thought it had been fixed, but does not look as though it has.

If you preview a page, without having made any changes, then the green + bar displays on the item in the Content site tree.
![image](https://user-images.githubusercontent.com/22772250/54034380-9ae00b80-41ae-11e9-8698-96a5183b860f.png)

To reproduce:
- Go to (any) page.
- Do not make any edits. 
- Click 'Preview' button. Look at site tree - green bar displays.
- If you then 'save and publish' the page - green bar disappears.

Expected results:
- No green bar displays on preview, when no edits have been made.
- Should not have to (re-)publish a page (which has not had any changes made to it) in order to remove the green bar.

regards Fiona

**Comment by nathanwoulfe** [comment]
I'm speculating, but it's probably because preview saves the page first

**Comment by nul800sebastiaan** [comment]
Yikes! We never merged the PR for that: https://github.com/umbraco/Umbraco-CMS/pull/1943

Seems to work. :-)

**Comment by HistoricEnglandDigitalTeam** [comment]
Lol - so does that mean that the PR will be merged into a subsequent release, 
.... or that it works for you now anyway? ('cos it's still a problem for us!)
Fiona

**Comment by nul800sebastiaan** [comment]
Yeah, we'll get it in for 7.15 :)

**Comment by HistoricEnglandDigitalTeam** [comment]
Look forward to it, thanks.
Fiona

**Comment by nul800sebastiaan** [comment]
🙈 well that never happened! We'll have to

**Comment by HistoricEnglandDigitalTeam** [comment]
Yes please. And here is me thinking that it was our own code base that was the issue. Thanks for following this up and re-opening the request.
regards Fiona

**Comment by nul800sebastiaan** [comment]
Fixed in https://github.com/umbraco/Umbraco-CMS/pull/1943
Cherry picked for 7.15.4 - 8c46984a2fbe34c9beb903919be1be421ffa539d
