### ISSUE TITLE
Show document type alias when you hover the document type name on info tab.

### ISSUE THREAD

**Issue by madsrasmussen** [umbraco/Umbraco-CMS#4920]
When developing you often need to use the document type alias. A quick way to get this is to go to the info tab and click on the document type. An even faster way would be to reuse the convention from the properties and show the alias when the hovering over the document type on the info tab.

**Comment by kjac** [comment]
Pretty sure it's already shown 😄 

![image](https://user-images.githubusercontent.com/7405322/54075735-fee3fc00-42a2-11e9-8d09-41aa80386766.png)

One could argue that these hover titles shouldn't be shown for non-admins, as they really make little sense for editors?

**Comment by madsrasmussen** [comment]
That looks very much like V8. The same functionality in V7 would be awesome 😄

**Comment by kjac** [comment]
Oops looks like I let this one slip. PR in #5118
