### ISSUE TITLE
Reordering of “allowed child nodes” in doc type editor. Reflect when creating a new node.

### ISSUE THREAD

**Issue by madsrasmussen** [umbraco/Umbraco-CMS#4923]
When adding allowed child nodes to a document type, they are listed in alphabetical order. It would be a great feature if it were possible to set the order of the doctypes. Many times you have doctypes that are more used than others, and it would be great if it were possible to be able to have these first when creating new content.

I imagine it should be possible to drag and drop the allowed doctypes in the doctype editor and that order would be respected when creating new content nodes.

**Comment by kjac** [comment]
Great idea! I'll see if I can cook up a fix for this 👍

**Comment by kjac** [comment]
Whoa... that was a bit more cumbersome than expected. But totally worth it. PR in #4927

**Comment by madsrasmussen** [comment]
Awesome! It would have been a wonderful feature in V7 too ;)

**Comment by kjac** [comment]
Pretty sure I could be persuaded to backport the PR to V7 😆

**Comment by kjac** [comment]
V7 PR in #4937

**Comment by madsrasmussen** [comment]
You are a champion. Fingers crossed it gets merged 😃
