### ISSUE TITLE
MNTP - when using "Allow items of type" show a tooltip on hover which types are allowed to be selected.

### ISSUE THREAD

**Issue by madsrasmussen** [umbraco/Umbraco-CMS#4924]
When using "Allow items of type" in the MNTP, all types that are not allowed are dimmed with a not allowed cursor on them. From an editors point of view, it is not always obvious why a node can't be selected. A tooltip with a text like "Nodes with the type Blog Post can only be selected" would make it more clear why some nodes can't be selected and where to go look for the right ones.

**Comment by kjac** [comment]
V8 PR in #4964 - if it passes approval I'll backport it to V7.
