### ISSUE TITLE
V8 Backoffice RTE has bad paths to style files in nesteed folders

### ISSUE THREAD

**Issue by NaMonitoru** [umbraco/Umbraco-CMS#4932]
In back office RTE does not offer defined styles in the drop down element.

Reproduction
------------
Insert the style file for RTE into the subfolder "css".
Example: <strong>/css/namo/rte.css</strong>
rte.css contains blocks / ** umb_name: * /
RTE element drop down in backoffice does not offer choices.

&lt;link rel=&quot;stylesheet&quot; type=&quot;text/css&quot; id=&quot;u1&quot; href=&quot;http:&frasl;&frasl;localhost:1111<strong>/css/rte.css</strong>?umb__rnd=0202575321a7f1703becb4c52cc796d0&quot;&gt;

checkbox of styles for the data type are displayed correctly and are selected
### **Picture-1**
![image](https://user-images.githubusercontent.com/48405977/54949134-a9644c00-4f3e-11e9-9d0c-fd289fac8bd6.png)
### **Picture-2**
![image](https://user-images.githubusercontent.com/48405977/54949477-72426a80-4f3f-11e9-9ab4-f05cf80d18f2.png)
### **Picture-3**
![image](https://user-images.githubusercontent.com/48405977/54949730-07456380-4f40-11e9-9684-517f2c1d3467.png)

**Comment by NaMonitoru** [comment]
In the Chrome Context Menu - Explore tag IFRAME of rte elements tag head and links

**Comment by nul800sebastiaan** [comment]
Thanks, it looks like that's a bug (also in v7).

I've marked this as "Up for grabs" so that you or someone else coming along could create a pull request for it.

**Comment by NaMonitoru** [comment]
I'm not sure but in V7 there was no possibility in the backoffice to create sub folders for css and skripts.
The discrepancy is that in RTE parameters, CSS is offered correctly from sub folders, but when using RTE in context filling, they are not shown because the paths are invalid.

**Comment by kjac** [comment]
Yeah this shouldn't be a problem in V7. PR in #5068

**Comment by NaMonitoru** [comment]
I have this problem in Umbraco version 8.0.1 
Base of the problem is on picture-1.
I modified this issue for better understand.

**Comment by kjac** [comment]
@NaMonitoru thanks.. PR #5068 should fix the issue.

**Comment by NaMonitoru** [comment]
Ah sorry I didn't understand that PR contains a fix. I've already found it. Will this fix be applied in a future release?

**Comment by NaMonitoru** [comment]
Thank you very much
