### ISSUE TITLE
v8 - The language <language>-<culture> already exists when added the <language> already

### ISSUE THREAD

**Issue by JeffreyPerplex** [umbraco/Umbraco-CMS#4935]
Using Umbraco v8.0.0 and setting up a multilingual website.

As my first language I've added "Dutch" to use on my Dutch website:

![before](https://user-images.githubusercontent.com/12457148/54087653-36ab7c00-4355-11e9-804f-4aee685efc11.png)

As a second language I want to added "Dutch (Belgium)" (Flemish) to use on my Belgian website.

But as soon as I want to add that one I get the error message:

"The language nl-BE already exists"

![nl-BE](https://user-images.githubusercontent.com/12457148/54087655-3ca15d00-4355-11e9-8e83-6ef6eb24b068.png)

This is quite confusing, because I haven't "nl-BE" yet, but only "nl". It has of course something to do with the fact that one is the generic language, and the other one with a specific culture.

I have no clue whether both these languages (generic and specific culture) could be added from a technical perspective. If so, this looks like a bug.

If not the error message could be a bit more specific: "Because you've added the generic language already, you cannot add a specific culture as well". Or something like that :)

Jeffrey

**Comment by kjac** [comment]
PR in #4957

**Comment by rasmuseeg** [comment]
This is not fixed yet. Just installed the lastest version of UmbracoCms v8.0.2 using nuget.

**Comment by kjac** [comment]
8.0.1 and 8.0.2 only contain cherry picked fixes. The fix for this is probably part of 8.1
