### ISSUE TITLE
v8 - Selecting "true/false" editor during document type generation

### ISSUE THREAD

**Issue by JeffreyPerplex** [umbraco/Umbraco-CMS#4936]
I am creating a new property on a doctype and want to select the checkbox which is called "True/false" by default. 

![truefalse - 1](https://user-images.githubusercontent.com/12457148/54087807-3a400280-4357-11e9-8ae7-1af5cae97e7f.png)

Normally if you start typing it looks for the filterstring within the names of the doctype. So if you type "text" you only get a textstring and textarea:

![truefalse - 1 1](https://user-images.githubusercontent.com/12457148/54087817-6065a280-4357-11e9-9576-40763a9f8cac.png)

But if you type "true" you still get all options:

![truefalse - 2](https://user-images.githubusercontent.com/12457148/54087821-69ef0a80-4357-11e9-9868-15664bbca8dc.png)

As soon as you add a "/" (so "true/") it finally filters:

![truefalse - 3](https://user-images.githubusercontent.com/12457148/54087826-75dacc80-4357-11e9-8ec0-c17e24b5f72c.png)

**Comment by skttl** [comment]
Wasn't that one renamed to checkbox in 7.13?

**Comment by nul800sebastiaan** [comment]
It was indeed @skttl - I'll close this as it shouldn't be a problem in the future any more. Thanks @JeffreyPerplex ! :)

**Comment by JeffreyPerplex** [comment]
Hi both,

this was a fresh v8 installation!

**Comment by nul800sebastiaan** [comment]
Duh.. Of course it was, I can see it from the color scheme :-)

And after a bit of looking around: the Checkbox datatype turned into a big toggle, and we renamed it in v8 to True/False. So yep, still an issue, probably something with some regex. 

I've marked this as "Up for grabs" so that you or someone else coming along could create a pull request for it.

**Comment by kjac** [comment]
As it turns out, the current solution searches through the entire datatype object. This leads to some rather unpredictable search results.

PR to fix it in #5004
