### ISSUE TITLE
Save a media reference in RTE instead of media URL in property editors

### ISSUE THREAD

**Issue by Shazwazza** [umbraco/Umbraco-CMS#4940]
We need to do a similar thing as we do with links in the RTE as we do with media. For example, when picking a link in the RTE we store an UDI so it's resolved dynamically via property value converters, however for media we currently store the media path which means when the media is updated the RTE image is not, we need to change the local media link to store an entity identifier instead.

There are other reasons we need to do this and it's probably not just the RTE that needs adjusting since we always want to resolve a media path dynamically since in the future we will have media URL providers.

Part of this task is determining which property editors and property value converters need updating. The RTE is one, the grid with the RTE is another (i 'think' that's it, but maybe have a look at the spike outcome: https://github.com/umbraco/Umbraco.Private/issues/289). Creating the property value converters will be another task.

The Image Cropper and Upload editors will be treated differently as part of another task. (see https://github.com/umbraco/Umbraco-CMS/issues/4943)

We would probably want to also do a migration of all of this data so that any hard coded media paths are changed to media references.

(original task https://issues.umbraco.org/issue/U4-6108)

**Comment by rasmusjp** [comment]
PR https://github.com/umbraco/Umbraco-CMS/pull/5209

**Comment by Shazwazza** [comment]
_Notes from PR:_

Links to media is now stored as localLink in  the RTE and Grid RTE and the URL is resolved when rendering, img tags are already handled (see https://github.com/umbraco/Umbraco-CMS/commit/99b80e0f569ce24623eb331fd683b5255a64c672)

The migration looks for all links that starts with `/media/`  and if it can be looked up in the DB the value is replaced with the UDI

### Breaking changes:

RTE and RTE in Grid now stores localLink for media like it does for content.

Before:
```html
<p><a data-udi="umb://media/662af6ca411a4c93a6c722c4845698e7" href="/media/662af6ca411a4c93a6c722c4845698e7/00000006000000000000000000000000/16403439029_f500be349b_o.jpg" title="Umbraco Campari Meeting Room">Umbraco Campari Meeting Room</a></p>
```
After:
```html
<p><a data-udi="umb://media/662af6ca411a4c93a6c722c4845698e7" href="/{localLink:umb://media/662af6ca411a4c93a6c722c4845698e7}" title="Umbraco Campari Meeting Room">Umbraco Campari Meeting Room</a></p>
```
The url's are resolved when rendering using TemplateUtilities.ParseInternalLinks which the RTE value converter calls and it's used in the default Grid/Editors/Rte.cshtml file.
