### ISSUE TITLE
Create media Url provider

### ISSUE THREAD

**Issue by Shazwazza** [umbraco/Umbraco-CMS#4942]
Relates to #4941 
Relates to #4940

Just like we have for content, we need to have a media URL provider which can be replaces (just like content url providers). This is an important step towards being able to properly support CDNs and things like Blob media providers. 

If media is stored in blob storage and is pushed to a CDN, we need to be able to return the CDN media URL from a media URL provider.

This will be a bit more tricky than the content url provider because media can exist on both content and on media and can exist multiple times per content or media item.

**Comment by rasmusjp** [comment]
PR https://github.com/umbraco/Umbraco-CMS/pull/5282

**Comment by zpqrtbnk** [comment]
Have tested OK, created my own provider and it works, etc - merged the PR
