### ISSUE TITLE
SPIKE - Determine how we deal with Media URL providers and the media path stored with Property editors

### ISSUE THREAD

**Issue by Shazwazza** [umbraco/Umbraco-CMS#4943]
For RTE/Grid/etc... we'll store a media reference instead of a media path (i.e. #4940) , however we need to figure exactly how to do this. For example we store "local links" for links but we need to store "local media" for media. Then we need to figure out which property editors we need to do this for and how to do it. For example, the rte currently stores a `data-udi` attribute on it's img tag, do we 'just' use that or something else?

Does this affect deploy? (if we use udis we should be ok but need to think about it)

BUT! then we need to figure out what we do about the upload and image cropper property types. Both of these property types can exist on media and content and can exist multiple times on each. However, it will the new media Url Provider (yet to be designed) that will be responsible for returning media URLs. The trick here is to figure out what we should be storing for a value in these editors and how we convert this value with property value converters to the true media URL. This is because a media url provider might change or the media path might change (i.e. a CDN is changed). As an example, say we have a media URL provider that tells us the media path is `https://mycdn.com/media/12345` and if we were to store this path in the upload property editor value and then later change the media url provider which now would return `https://YOURcdn.com/media/12345`, how should we handle this? We might not even have to do anything here since the property value converter should just replace this value at runtime with the correct one.

an example of how the media url provider might return a url - and the property value converter should know all of this data.
`MediaUrlProvider.GetUrl(mediaId, propertyId, culture, segment);`

**Comment by kjac** [comment]
Storing the relative path is definitely flexible. In a CDN setup, all you need to do is prefix with your CDN host and presto!

Also consider scenarios where a seeded DB is moved/promoted to production. The production CDN is likely to differ from the previous environment - much like your "what if the host changes" scenario.

**Comment by warrenbuckley** [comment]
# Spike Research Notes 📝🔬

## Current Editors storing media references
The following property editors in Umbraco use media paths as the data that they store

### Umbraco.Web.PropertyEditors
* ⚠️**RichTextPropertyEditor.cs**
This stores a raw HTML string which contains an `<img>` element which has a reference to a physical media path. See LocalLink & Rich Text Editor for further notes.

* ❓ **FileUploadPropertyEditor.cs**
TODO

* ❓ **ImageCropperPropertyEditor.cs**
TODO

* ✔️ **MultiUrlPickerPropertyEditor.cs**
Stores references to media items as UDIs. No changes needed.

* ✔️ **MediaPickerPropertyEditor**
Stores references to media items as UDIs. No changes needed.


## LocalLink & Rich Text Editor
Currently in the RTE we have the concept of LocalLinks where we store a reference to the linked page in the `<a>` tag. It makes sense for us to have/use the same concept for Media, but the `<img>` tag will still need to show the image path resolved by the yet to be designed Media Url Provider in order for the image to be displaed as a preview in the RTE. So it makes sense for us to add a HTML data attribute to the img element.

In the codebase today we add a `data-udi` attribute to the `<img>` tag and this can be used for our `LocalMedia` reference like we do for LocalLink.

The `Umbraco.Web.UI.Client/src/common/services/tinymce.service.js` contains some functions for inserting media:

* `createMediaPicker()`
This adds the toolbar button into TinyMCE and on click grabs the `alt`, `src` and `data-udi` attributes.

* `insertMediaInEditor()`
This updates the RTE content with the picked image from the dialog/infinite editor that passes down a JSON object of UDI, alt & src properties from the chosen image in the dialog/infinite editor.

My initial thoughts is that we may not need to do anything apart from implement the Media Url Provider & thus when selecting or re-chosing an image it will get the URL to the image via the Media Url Provider for us & update the HTML. We already have a concept of MediaLink like locallink as all img elements use the data attribute `data-udi`


## Deploy
Umbraco Deploy (Cloud) but not Courier will use the following Connectors for media:

### Umbraco.Deploy/Connectors/ValueConnectors
* ⚠️**RichtextValueConnector.cs**
This reads the contents of the RTE in the grid cell & uses a class called `ImageSourceParser` to do some string work.

* ✔️ **MediaPickerValueConnector.cs**
This just converts the picked int IDs into UDIs & adds them as artifacts

* ✔️ **ImageCropperValueConnector.cs & FileUploadValueConnector.cs**
This will look up the file path stored in the value in the `mediaFileSystem` to see if the `FileExists()` and if it does it adds a UDI artifact to the physical file **NOT** a media node/item. I think this should be OK

### Umbraco.Deploy/Connectors/GridCellValueConnectors/
* ✔️ **MediaGridCellValueConnector.cs**
 This should all be OK as this deals with converting the integer ID in the JSON object to a UDI & is added as artifact dependancy.

* ⚠️ **RichtextGridCellValueConnector.cs**
This reads the contents of the RTE in the grid cell & uses a class called `ImageSourceParser` to do some string work.

### ImageSourceParser.cs
`ImageSourceParser` when converting `ToArtifact` finds all `<img src="/path/to/file">` and replaces the `src` attribute with a UDI reference to the media item & **not** the physical file UDI. As the RTE does not currently store any UDI reference to the picked media file, it has to look up the media item by its file path with `mediaService.GetMediaByPath()` to get the UDI of the media item to replace in the `src` attribute. In addition to the src attribute it will find any attributes on the image tag that contain the integer ID of the media item to be replaced with the UDI.

When we go the other way and expanding the value store in a Deploy Artifact back to an img tag with a correct file by looking up the media item by its UDI & calling `media.GetUrl("umbracoFile")`

## Outcome/tasks/suggestions

For deploy it seems most of this will continue to work just fine as far as I can tell, but the `ImageSourceParser` class will still work but could be improved to avoid having to look up the file path stored in the src attribute of the image tag and trust that the data attributes will always contain the correct UDI reference & avoid this lookup step in this class.
