### ISSUE TITLE
SPIKE - determine how to utilize the umbracoServer table to store lastsynced.txt info

### ISSUE THREAD

**Issue by Shazwazza** [umbraco/Umbraco-CMS#4944]
Currently we store a text file locally: `App_Data/DistCache/lastsycned.txt` which stores an INT id of the last cache instruction read from the database which allows for flexible load balancing to work along with ensuring the in-memory cache is robust even between appdomain restarts and overlapping appdomains during restarts.

It would however be better if we stored this value in the database directly instead of on disk. For LB and Azure scenarios, this file is normally located on the local fast drive or local %temp% drive. This is because this value is specific to the server/IIS site running the website, not the website itself. In some cases if the local fast drive is not available, it means this file cannot be read and a cold boot will take place which is not ideal. Another problem with storing as a file is that you cannot easily force a cold boot on a particular server without accessing the server's files directly and removing this file whereas if it were in the db you could centrally control this.

This task is determine the sub tasks it will take in order to achieve this. We would need to store a website identifier in the database that is unique to the IIS website, normally we would do this as a hash of the MachineName + AppDomainAppId which i think would be sufficient in all cases. The value stored in the `umbracoServer` table is this combination IIRC, the value looks like `TEAMCANADA3//LM/W3SVC/18/ROOT` so I think we are already storing this unique identifier correctly.

**Comment by Jeavon** [comment]
You would need to consider scenarios where the DatabaseServerRegistrar has been replaced and so the umbracoServer table isn't in use. Slave servers also may have readonly access to the database.

**Comment by bergmania** [comment]
I suggest to move the part of `DatabaseServerMessenger` that actual makes the file sync into it's own class behind an interface. e.g.
```
    public interface IServerMessengerSyncRepository
    {
        /// <summary>
        ///     Gets the incremental value.
        /// </summary>
        int Value { get; }

        /// <summary>
        ///     Updates the in-memory last-synced id and persists it to file.
        /// </summary>
        /// <param name="value">The incremental value.</param>
        void Save(int value);

        /// <summary>
        ///     Reads the last-synced id from file into memory.
        /// </summary>
        void Read();

        /// <summary>
        ///     Resets the value to its initial value.
        /// </summary>
        void Reset();
    }
```

Then we could implement multiple versions of this interface. 
One with the current implementation using a file in the local temp folder and another which uses the `KeyValue`-table in the database.

This will require to change the constructor of `DatabaseServerMessenger`, to inject the interface. 😨

**Comment by Shazwazza** [comment]
Side note - Currently we recommend doing this on replica servers which affects how server info gets into that table: https://our.umbraco.com/documentation/Getting-Started/Setup/Server-Setup/Load-Balancing/flexible-advanced#explicit-master-scheduling-server

however, if/when we make this change i'd like to modify this best practice for v8 to make sure that replica servers still ping to the database even though they are explicitly configured as replica/slave.

As for breaking the ctor, i think this is probably acceptable in some way, else maybe we make DatabaseServerMessenger2 or something crazy

**Comment by bergmania** [comment]
I have added a draft PR, on how I see this could be done.

- We need a new task for updating the Load Balancing documentation for V8, including new recommendation to how to use explicit master scheduling.

**Comment by Shazwazza** [comment]
Good effort, have created sub tasks for those items.
