### ISSUE TITLE
Skype link ("sip:name@domain") is automatically converted to "mailto"

### ISSUE THREAD

**Issue by facingdigital** [umbraco/Umbraco-CMS#4947]
When we insert a skype link inside the RichText editor with the syntax : "sip:name@domain", the URL is automatically transformed to "mailto:sip:name@domain" causing a bad link.

More details about Skype link : 
http://skype4businessinsider.com/voip/3-ways-start-conversations-skype-business-auto-contact-links/

Reproduction
------------

Insert a link from the RichText editor and enter a skype link : "sip:name@domain". You edit again the link, it will be automatically transformed to "mailto:sip:name@domain".

### Bug summary

skype link inside the HTML editor with the syntax : "sip:name@domain", the URL is automatically transformed to "mailto:sip:name@domain" causing a bad link.

### Specifics

Umbraco 7.12.4, RichText editor

### Actual result
The URL is automatically transformed to "mailto:sip:name@domain" causing a bad link.

**Comment by nul800sebastiaan** [comment]
Oh no.. Seems like a bug! :-)

I've marked this as "Up for grabs" so that you or someone else coming along could create a pull request for it.

**Comment by kjac** [comment]
Found it... PR imminent.

**Comment by kjac** [comment]
PR in #4997

**Comment by facingdigital** [comment]
Yeah ! Thank you for your reactivity ! 👍
________________________________

**Comment by nul800sebastiaan** [comment]
Fixed in https://github.com/umbraco/Umbraco-CMS/pull/4997
