### ISSUE TITLE
Grid Settings Row configuration missing Save button

### ISSUE THREAD

**Issue by marcoteodoro** [umbraco/Umbraco-CMS#4949]
While adding or editing an Grid row i can't see the option to save changes. 

1) To replicate the issue just create a new doctype property of type grid. 
2) Edit the grid layout
3) click on add row configuration or edit an existing one
4) look at the bottom of the dialog and you can't see the save or submit button. Just the close button is available. 

![image](https://user-images.githubusercontent.com/3866444/54137945-7be3b280-4416-11e9-9a9a-8c85f75abf52.png)

**Comment by abjerner** [comment]
Hi @marcoteodoro and thanks for reporting 👍 

While it is not entirely obvious, it appears the close button actually does what you would expect the submit button to do.

But for consistency, I believe there should be a submit button to continue with the changes, while the close button would discard the changes. That's also how it works in Umbraco 7.

**Comment by nul800sebastiaan** [comment]
A real button to save and a close link to dismiss changes would be good yes!

I've marked this as "Up for grabs" so that you or someone else coming along could create a pull request for it.

**Comment by Flaeng** [comment]
I think I've solved this, but Github wont let me create a pull request atm. I'll try again tomorrow.
https://github.com/Flaeng/Umbraco-CMS/commit/162547e6b0daf1489c4f7d9276520166c7ff6dd7

**Comment by nul800sebastiaan** [comment]
Fixed in https://github.com/umbraco/Umbraco-CMS/pull/5136
