### ISSUE TITLE
Move umb-loader to separate component

### ISSUE THREAD

**Issue by bjarnef** [umbraco/Umbraco-CMS#4958]
In most places in backoffice UI, it now use `umb-load-indicator` directive, but a few places, mainly at trees it use `umb-loader` + `umb-loader-wrapper` https://github.com/umbraco/Umbraco-CMS/search?q=umb-loader&unscoped_q=umb-loader

I think is would make sense to put this in another component e.g. umb-loader so the markup is only maintained from a single file. Furthermore it is wrapper umb-loader-wrapper is missing, which it was original in Umbraco, it got some annoying horizontal scrollbar on/off while umb-loader was animating.

Furthermore its styling can be moved to a separate less file.

**Comment by nul800sebastiaan** [comment]
Retargeted for 8.1.4 - https://github.com/umbraco/Umbraco-CMS/pull/6169#issuecomment-527117568
Cherry picked in 087122868557f28d1f5d0b6f2a372eaf52e3ab22
