### ISSUE TITLE
Local link in rich text editor doesn't render correctly

### ISSUE THREAD

**Issue by tranphuongyd** [umbraco/Umbraco-CMS#4959]
Hi everyone,

Currently, I'm using the Umbraco CMS 7.13.1 . So I'm still get error when display the local link that included in the Rich text editor. For now, just work around by using the `ParseInternalLinks` function.
`Umbraco.Web.Templates.TemplateUtilities.ParseInternalLinks(strValue)`

Can someone tell me this issue can be fixed in the latest version or not?

Thanks,
Phuong Tran

**Comment by nul800sebastiaan** [comment]
Hi @tranphuongyd - at this time we don't have plans to fix this, sorry.
