### ISSUE TITLE
v8: Package download doesn't handle special characters

### ISSUE THREAD

**Issue by bjarnef** [umbraco/Umbraco-CMS#4965]
In v8 when using e.g. danish characters `æøå` or `ÆØÅ` in package name and clicking "download" at the saved package, it doesn't seem to use correct UTF-8 encoding of the `.zip` file.

E.g. we have a package called "Ørskov Opstartspakke". In v7 the generated zip file was named `Ørskov_Opstartspakke_1.0.0.zip`, in v8 this is generated as `Ã_rskov_Opstartspakke_1.0.0.zip`.

**Comment by bjarnef** [comment]
It seems it need to handle the encoding correct here: https://github.com/umbraco/Umbraco-CMS/blob/91c52cffc8b7c70dc956f6c6610460be2d1adc51/src/Umbraco.Web/Editors/PackageController.cs#L97-L110

**Comment by bjarnef** [comment]
It seems the headers `x-filename` isn't url encoded and it is shown like this in the header.

![image](https://user-images.githubusercontent.com/2919859/54236947-24783c00-4515-11e9-99be-915c36082efc.png)

and the value is directly used as filename in `umbRequestHelper.downloadFile`:

```
// Get the filename from the x-filename header or default to "download.bin"
var filename = headers['x-filename'] || 'download.bin';
```

**Comment by bjarnef** [comment]
When using one of the following:

```
response.Headers.Add("x-filename", HttpUtility.UrlEncode(fileName));
```


```
response.Headers.Add("x-filename", Uri.EscapeDataString(fileName));
```

![image](https://user-images.githubusercontent.com/2919859/54237573-93a26000-4516-11e9-9830-c551778d9e5c.png)

**Comment by nul800sebastiaan** [comment]
Fixed in https://github.com/umbraco/Umbraco-CMS/pull/4968
