### ISSUE TITLE
V8: List View - Unable to sort on "Is Published", when language variants is used

### ISSUE THREAD

**Issue by DanielToft** [umbraco/Umbraco-CMS#4967]
Hi

In a List View with Language Variants, the sorting functionality on the built In "Is Published" property, does not sort correctly.  

It seems that sorting functionality is disabled on the "Status" field. Why is that the case? The best option will definitely be to allow sorting on the Status field, since nodes with languages variants can have 3 states. Published, Draft and Not Created.

Reproduction
------------

### Specifics
Umbraco Version: 8.0.0

### Steps to reproduce

1. Create a container document type with a List View and enable "Allow varying by culture". In the list view add the built in property "published" to the columns,

2.  Create a document type that is allowed under the container document type. Enable "Allow varying by culture".

3. Create nodes under the list view. Ensure you have nodes in multiple languages and some of them is published and in a Draft and Not Created State.

4. Try sort on the "Is published" field.

### Expected result

The list is sorted correctly by the "Is published" field

### Actual result

The list seems to be randomly sorted.

**Comment by bergmania** [comment]
The issue seems to be the calculation of whether the item is published, used in the ordering.

```
 // when invariant, ie 'variations' does not have the culture flag (value 1), use the global 'published' flag on pcv.id,
 // otherwise check if there's a version culture variation for the lang, via ccv.id
 ", (CASE WHEN (ctype.variations & 1) = 0 THEN (CASE WHEN pcv.id IS NULL THEN 0 ELSE 1 END) ELSE (CASE WHEN ccv.id IS NULL THEN 0 ELSE 1 END) END) AS ordering "); // trailing space is important!
```
https://github.com/umbraco/Umbraco-CMS/blob/dev-v8/src/Umbraco.Core/Persistence/Repositories/Implement/DocumentRepository.cs#L994-L996

I have these:
![image](https://user-images.githubusercontent.com/1561480/54529863-66740880-4981-11e9-9a4b-c673f9353d9f.png)

But the ordering in SQL are comparing the value `1` for each item.
My `ccv` table looks like this:
![image](https://user-images.githubusercontent.com/1561480/54529926-8c99a880-4981-11e9-800d-690a7fc786f6.png)

@zpqrtbnk , is the solution to change `ccv.id IS NULL` to `ccv.id IS NULL OR pcv.id IS NULL` in the outer else-case? It fixes my case, but not sure if there are anything I don't know about.

**Comment by zpqrtbnk** [comment]
So... when it's a variant content type ie `(ctype.variations & 1) = 0` we determine (line 996) the "published" status with `(CASE WHEN ccv.id IS NULL THEN 0 ELSE 1 END)`.... and here, `pcv` is `ContentVersionDto` for the published document version (line129), and `ccv` is `ContentVersionCultureVariationDto` for the culture (line 157) *and for the current version* (line 158).

When checking for `ccv.id` - we check for a culture variation on the *current* version not the published one. That ... is bad? 

Quick suggestion, if you think I'm ok:

Change the join block just above (line 985) as:
~~~~
var joins = Sql()
  .InnerJoin<ContentTypeDto>("ctype").On<ContentDto, ContentTypeDto>((content, contentType) => content.ContentTypeId == contentType.NodeId, aliasRight: "ctype")
  // left join on optional culture variation
  //the magic "[[[ISOCODE]]]" parameter value will be replaced in ContentRepositoryBase.GetPage() by the actual ISO code
  .LeftJoin<ContentVersionCultureVariationDto>(nested =>
    nested.InnerJoin<LanguageDto>("langp").On<ContentVersionCultureVariationDto, LanguageDto>((ccv, lang) => ccv.LanguageId == lang.Id && lang.IsoCode == "[[[ISOCODE]]]", "ccvp", "langp"), "ccvp")
  .On<ContentVersionDto, ContentVersionCultureVariationDto>((version, ccv) => version.Id == ccv.VersionId, aliasLeft: "pcv", aliasRight: "ccv");
~~~~

then change the filter as `(CASE WHEN ccvp.id IS NULL THEN 0 ELSE 1 END)`

Making sense?
