### ISSUE TITLE
V8: Unable to get all content of a certain type using GetPagedOfType()

### ISSUE THREAD

**Issue by hartviglarsen** [umbraco/Umbraco-CMS#4973]
I was playing around with getting all content of a certain type. In V7 the ContentService had **GetContentOfContentType()**, however that does not exist in V8. Therefore I decided to try and be creative with **GetPagedOfType()**. Unfortunately the collection returned does not contain any items.

Reproduction
------------
```C#
var productTypeId = Product.GetModelContentType().Id;
var products = _contentService.GetPagedOfType(productTypeId, 1, 9999, out var size, null);
```

### Expected result

I expect that `products` contains a collection of products (if there are any) and that `size` contains the amount of records.

### Actual result

While `size` does show the correct amount of records, the collection does not contain any products.

![image](https://user-images.githubusercontent.com/4366314/54271188-57f0b000-4581-11e9-9088-4b8e7f40680b.png)

**Comment by Shazwazza** [comment]
It's because you are passing in `1` for the `pageIndex` parameter. Being an `index` it is zero based. So you are asking for page #2 by passing in `1` and you only have 2 records.

pass in `0` for the page index and it should work

**Comment by bergmania** [comment]
Could have been nice to just request using something like 
`var products = _contentService.GetPagedOfType(productTypeId, PagingInfo.AllItems, out var size, null);`
