### ISSUE TITLE
V8: Bug while selecting Culture and Hostname

### ISSUE THREAD

**Issue by Malthebp** [umbraco/Umbraco-CMS#4975]
Reproduction
------------

### Bug summary

When selecting a Culture and Hostname in Umbraco v8.0.0 it doesn't get selected. I can attach domains with the culture, but I cannot select an overall language for the node. 

It seems like the language is being selected, but once closed and opened again, it is default: "Inherit". 

I am not sure whether this changes anything, but in the "Links" section for the content, I get 2 urls (example: danish and english) even though I only have one domain. 

Also when the IContent model Umbraco gives you on ContentService.Published/Saved does not have any of the culture information it is supposed to. I think this is side effect from the bug above.  
 
### Specifics

Defining the culture and domains.
When setting the language:
![umbraco-culture-set](https://user-images.githubusercontent.com/18698439/54276847-99d42300-458e-11e9-893f-28ae2d29aacf.JPG)

When checking it again after saving and close/open the modal.
![image](https://user-images.githubusercontent.com/18698439/54277274-b4f36280-458f-11e9-8c97-74dfd2ed7c4a.png)

The links: 
![image](https://user-images.githubusercontent.com/18698439/54277050-0e0ec680-458f-11e9-9a7b-59434e15ca04.png)
![image](https://user-images.githubusercontent.com/18698439/54277076-18c95b80-458f-11e9-8fb7-5388925e84b5.png)

### Steps to reproduce

1. Install a fresh Umbraco 8 and install the starter template. 
2. Create a new language (for example Danish(Denmark))
3. Create a new home 
4. Set the culture and host name for the new home with the correct matching domain.

### Expected result

I expected one url per. domain, per. language.

### Actual result

I get cultures and urls inherited, even though there is nothing to inherit from (probably just the default).

**Comment by Stick97** [comment]
I'm seeing the same issue. I'm having trouble with the GetCulture() method on IPublishedContent returning null as well. I'm assuming it's also a side effect.

**Comment by nul800sebastiaan** [comment]
That looks like a bug and we should also fix https://github.com/umbraco/Umbraco-CMS/issues/4699 where the dialog doesn't close after saving.

**Comment by kjac** [comment]
PR in #5001

**Comment by monais** [comment]
I'm facing issue with Umbraco Multi language website English & Arabic. English (en-US) is working fine as default language. Arabic (ar-SA) secondary language is not working, showing 404 error.
Domains setting with Culture and Hostnames
http://localhost:4865
http://localhost:4865/ar

I did followed all steps in the below link:
https://www.youtube.com/watch?v=-vzxCdjq4FM&ab_channel=UmbracoHQ
