### ISSUE TITLE
v8: Dropup is behind grid hover overlay

### ISSUE THREAD

**Issue by bjarnef** [umbraco/Umbraco-CMS#4979]
In grid it seems the grid overlay overlap the dropup button in footer.

I seems to be because this overlay has `z-index: 5;` while `.umb-editor-footer` only has `z-index: 1;`

When changing `.umb-editor-footer` to e.g. `z-index: 10;` it seems to fix it in this scenario.

![2019-03-13_15-36-19](https://user-images.githubusercontent.com/2919859/54287724-8339c600-45a6-11e9-8107-97dc2077f887.gif)

![image](https://user-images.githubusercontent.com/2919859/54287815-ac5a5680-45a6-11e9-95a9-8f081971aa54.png)

**Comment by bjarnef** [comment]
When using ModelsBuilder and having the "Save and generate models" action, it can also be reproduced on document types.

![image](https://user-images.githubusercontent.com/2919859/54287897-d14ec980-45a6-11e9-91a2-c3ca93621627.png)

**Comment by nul800sebastiaan** [comment]
Fixed in https://github.com/umbraco/Umbraco-CMS/pull/4980
