### ISSUE TITLE
v8 - overlays after creating new content (redirect) reference a stale controller

### ISSUE THREAD

**Issue by Shazwazza** [umbraco/Umbraco-CMS#4988]
This is an interesting issue and i'm not sure how we work around this.

Here's the situation:

* Create a variant doc type with a text field property called 'title' that has validation enabled to be a Number (this causes server validation to occur)
* Create a new content item of this doc type, fill in the 'title' on language 1 to be correct like '1234' and fill in the 'title' on language 2 to be incorrect like 'abc', go back to language 1 and then do the save and publish which launches the dialog, select both languages and choose to publish
* Since this is newly created content, this will redirect to the created content's route with it's new ID
* The dialog will remain open because there was a validation problem with language 2 and it will display that message. The save/publish button is still available to be clicked with both languages selected, if you click the button you will get a JS error:
	```
            TypeError: Cannot read property '$getControls' of undefined
		at checkValidility (umbraco.directives.js?cdv=1407701632:2491)
		at performSave (umbraco.directives.js?cdv=1407701632:2565)
		at Object.submit (umbraco.directives.js?cdv=1407701632:2785)
		at ChildScope.scope.submitForm (umbraco.directives.js?cdv=1407701632:7808)
		at fn (eval at compile (angular.js?cdv=1407701632:16387), <anonymous>:4:220)
		at UmbButtonController.destination.(:8100/umbraco/anonymous function) [as action] (http://localhost:8100/umbraco/lib/angular/angular.js?cdv=1407701632:11376:22)
		at UmbButtonController.clickButton (umbraco.directives.js?cdv=1407701632:2028)
		at fn (eval at compile (angular.js?cdv=1407701632:16387), <anonymous>:4:245)
		at callback (angular.js?cdv=1407701632:28815)
		at ChildScope.$eval (angular.js?cdv=1407701632:19356)
	```
* This is because the overlay is 'global' and it hasn't actually been removed and re-created when the redirect occurred and because the redirect occurred, the previous content form and it's $scope no longer exist but this global overlay still has a reference to this old stale editor for which it's going to try to call back to

How to solve this? A 'quick' fix would be to disable the save and publish button on the dialog from being clicked (or hide it) and only allow the user to close the dialog if it was a newly created item. The longer term fix would be to:

a) Close the dialog if it's a newly created item before redirecting
b) When the content editor loads again we will know if it's a newly created item and we can check if there are pending server validation messages in the `serverValidationManager` and we can check if the item is variant. If all 3 of these things are true, then we re-launch the dialog into it's previous state and wire up the server validation bits (which might work automatically)

**Comment by nielslyngsoe** [comment]
Hi @Shazwazza 

I just tested this scenario, and I dont experience the issue you describe, I tested both with mandatory and not mandatory languages.

I do though experience an UX-issue, which also could be the solution to what you describe, (though it's not happening here).

As you suggest, I propose that we disable the "Save & Publish"-button in the dialog, when there is an error. For each language that has an error we should show a button saying: "Open to correct" (maybe someone can come up with a better naming) And the button, as it says, would close the dialog and open the language.

**Comment by Shazwazza** [comment]
The issue with disabling the Save/Publish button if there is a validation error is that if you have 2 or more languages, you've only selected one language to save/publish, a validation error occurs for that language, the user should still be able to select a different language to save/publish from that point so I'm not sure if disabling the full ability to do that is a perfect solution.

Here's a video showing the issue and how you can reproduce. You can reproduce it in various ways, doesn't have to be with the empty name. https://www.screencast.com/t/Y1KyvrzvUzJ6

We will need to solve this with option b) (mentioned above) regardless of what sort of ux work arounds we come up with

**Comment by nielslyngsoe** [comment]
Hi @shazwazza, I agree, the error should be fixed.

For UX, it should only be disabled when the selected languages has validation errors. Meaning if the user deselects a language that had a validation error(and the selection now only has valid languages) the “save & publish” button should be enabled again. So it should be evaluated on that. As well the validation error should determine wether the “open to correct”-button should appear next to the language. — we don’t want those buttons on languages that doesn’t have validation errors. Hope it makes sense, when the error is fixed I would love to give the UX a go.

**Comment by Shazwazza** [comment]
while continuing to fix aspects of this https://github.com/umbraco/Umbraco-CMS/issues/4884 I've found some other issues with this redirect with variants that we haven't taken into account. I'm working on a bunch of this together with the #4884 so no need to do anything at this stage but just needed to write this here :) 
... the problem is that currently we are relying on this `notifications` array that is passed back from the server on each variant to display a message for each variant in the dialog if the dialog remains open. These notifications are generally 'success' messages when not all variants were successful (if they were all successful, the dialog would close). The issue is that when creating new content we do the redirect which means we re-build the editor on it's new route with the model from the DB, not the model that was returned from the POST that created the item which is the model that contains these notifications. So these notifications are lost. Combining that problem with this stale overlay problem when creating and we've got a double whammy problem where we can't correctly report messages back to the user during creation of variant data.
I'll continue to work through this as part of #4884

**Comment by Shazwazza** [comment]
Here's what we'll need to do:

## ModelState updates

Right now, we are passing 'warnings' back for cultures in the form of 'notifications' which are part of the content model. This isn't ideal and is part of the problem because a 'warning' notification for these cultures was just a quick hack to make it work but in reality this is a validation error which we always use ModelState for. We also already have a mechanism for re-wiring up ModelState to the UI on redirects which is the serverValidationManager. There's no reason to re-invent the wheel and we should maintain consistency with how we deal with validation messaging.

Before 8.1 we were actually showing 'warning' messages in the culture save dialog differently from an 'error' but that is no longer the case and it probably shouldn't be. This also simplifies the solution and means we can 'just' use ModelState the way we currently are using it.

If however, we do want to display a different UI for warnings vs errors (though i don't really see why we would do this), we would need to modify our ModelState keys to be potentially prefixed with "warning." or "error." (something along those lines) but that complicates things a little and we don't have to worry about that right now.

So moving forward, any culture 'warnings' will just be errors as part of ModelState which will be rewired back up automatically with serverValidationManager.

### Stale dialog

We will need to close this dialog when we redirect, then after redirecting we will know if there are culture ModelState errors and if the content is variant, in this case, we will re-launch the dialog to make it in the same state as it previously was. Potentially we might not even have to close the dialog, but instead just refresh it with the non-stale content model.
