### ISSUE TITLE
Custom listview datepicker shows time 00:00

### ISSUE THREAD

**Issue by claushingebjerg** [umbraco/Umbraco-CMS#4989]
When making a custom listview and adding a Date picker datatype - (not date picker with time) - time is shown in the listview as 00:00 anyway

### Expected result
2019-03-17

### Actual result
2019-03-17 00:00

![Skærmbillede 2019-03-14 kl  11 41 54](https://user-images.githubusercontent.com/1854789/54350724-3a3d4c80-464e-11e9-88fe-09fd0208d466.png)

**Comment by nul800sebastiaan** [comment]
I've marked this as "Up for grabs" so that you or someone else coming along could create a pull request for it.

**Comment by nul800sebastiaan** [comment]
This issue has been in the `up for grabs` state for quite a while now and it seems nobody is ready to pick this one up.

For now we'll close this issue to prevent the list of `up for grabs` from becoming very stale. We're happy to re-open it if someone still thinks it's good to work on this.

If anyone is about to pick this issue up to fix it, make sure to test first if you can reproduce the problem in the latest version before you start to work on it.

Thanks!
Sebastiaan on behalf of Umbraco HQ.
