### ISSUE TITLE
V8: .gitignore issue?

### ISSUE THREAD

**Issue by senneclaeskens** [umbraco/Umbraco-CMS#4991]
I've cloned Umbraco-CMS from the dev-v8 branch. Running this project works correctly.
When I add this project (no modifications) to a different git service and I do a clean checkout (to a different folder), I receive errors when building:

**Invalid Resx file. Could not find file '\src\umbraco.web.ui\views\web.config'. Line 123, position 5.	Umbraco.Web	\Umbraco.Web\Mvc\Strings.resx**

**Invalid Resx file. Could not find file '\src\Umbraco.Tests\UmbracoExamine\testfiles\umbraco.config'. Line 126, position 5.	Umbraco.Tests	\src\Umbraco.Tests\UmbracoExamine\TestFiles.resx**

When I add these files, I get additional errors for other configuration files.

Is there anything misconfigured in gitignore or am I doing something wrong?

Initially this was for a test for CI. That's why I want to replicate the issue locally.

**Comment by nul800sebastiaan** [comment]
I am not sure what you're trying to do, but I'm pretty sure you shouldn't need to do it.

Please use the downloads / nuget packages of Umbraco to use Umbraco.

You will only need to deal with the Umbraco source code if you wish to contribute to the Umbraco codebase.
