### ISSUE TITLE
Cannot view preview link url in IE or Firefox

### ISSUE THREAD

**Issue by HistoricEnglandDigitalTeam** [umbraco/Umbraco-CMS#4993]
Hi - Can only preview a page using a preview link sent by email in Chrome browser 

Does not work in IE11 or Firefox browsers.

Umbraco v7.13.2

Reproduction
------------
- Click on Preview in back office.
- Copy the preview url for that page preview
- paste the preview url into IE of Firefox browser
 - results >just bet a blank page
- if do the same in Chrome - preview of page displays

Expected result:
- preview url is not browser specific

**Comment by nul800sebastiaan** [comment]
Preview ONLY works if you have an active session in the backoffice. Previews can not be viewed by anonymous users, this is why it doesn't work. 

This is how previewing works and we don't have plans to allow anonymous users to preview a page.

**Comment by HistoricEnglandDigitalTeam** [comment]
Hi - ok thanks Sebastian.

Do you know what happened to the fix mentioned in: https://github.com/umbraco/Umbraco-CMS/pull/2532?

Release 7.10.0 https://issues.umbraco.org/issue/U4-11134

The process was to:
•	log out (of the back office)
•	Go to /umbraco/preview, you will get redirected to the login page
•	log in, go and preview something and it should work

When you do this in 7.13.2, there is no redirect to the login page.
We have a complex web of editors and approvers across our organisation, and this sort of functionality would make the workflow process sooooo much easier to use  - especially for non-technical managers.

regards Fiona

**Comment by nul800sebastiaan** [comment]
Hi Fiona, that scenario works fine for me in a 7.13.2 install, so I suspect there's something somewhere in you setup preventing it to work. Unfortunately I have no clue as to what exactly that could be :(

Maybe try to ask for input on the forum: https://our.umbraco.com
