### ISSUE TITLE
V7 - Umbraco Installer doesn't honour ConfigSource for Connection strings

### ISSUE THREAD

**Issue by NikRimington** [umbraco/Umbraco-CMS#5003]
I believe this issue got fixed in the past but it has resurfaced (or at least a very similar issue).

If you change the connection strings section of web.config to use configSource setup before running the Umbraco Installer it results in the external source file getting broken.

It appears that the external source file becomes a full copy of web.config.

Reproduction
------------
(This occurred on a v7.12.4 site but reproduced on a 7.14.0 site)

1. Open visual studio
2. Create new project
3. install Umbraco via nuget (`install-package UmbracoCms -version 7.14.0`)
4. Open web.config and replace `connectionStrings` section with `<connectionStrings configSource="connstrings.config" />`
5. Create `connstrings.config` and populate with the following:
```
<?xml version="1.0" encoding="utf-8"?>
<connectionStrings>
        <remove name="umbracoDbDSN" />
        <add name="umbracoDbDSN" connectionString="" providerName="" />
    </connectionStrings>
```
6. Run project and go through installer (I did custom process and didn't bother with a starter kit)
7. Get installer error:
![image](https://user-images.githubusercontent.com/13313745/54523220-e2148c00-4966-11e9-8feb-b25dd951f8df.png)
8. Look at `connstrings.config` file and see it looks like a web.config file

Expected result
------------

I'd expect just to see the connectionStrings section in there with the populated connection string.

Umbraco 8:
------------
Umbraco v8 is not affected by this issue according to my testing.

**Comment by nul800sebastiaan** [comment]
Note: this has never been supported and due to the way we update the querystring (by reading the web.config file, not by using the .NET provider for that) it probably will not be supported. I can't remember the technical reason behind this but for now, upgrading would be a manual process (as you've discovered).

I'll put this into the list to discuss at HQ as to why exactly it works like it does now.

**Comment by nul800sebastiaan** [comment]
Hi @NikRimington - as it stands I don't ave the feedback on why this was not an option in v7, however updating it now would be too much effort (think testing upgrades, backwards compatibility, Cloud, etc) to make it worth the effort in v7. We're focusing our efforts on v8 instead where this is indeed already supported.

I'll close this issue, thanks for reporting and apologies that we can't be much more help here!
