### ISSUE TITLE
Putting in a content title > 255 characters causes "String or binary data would be truncated. The statement has been terminated." exception.

### ISSUE THREAD

**Issue by kgiszewski** [umbraco/Umbraco-CMS#5007]
## The Issue
Whilst not a "bug" per se, editors were alarmed when they copy\pasted a long name for a node into the content name field (see images).

## To Replicate
To replicate, type something greater than 255 characters into any node field title. Save\Publish.

## Version
v7.14.0

## Proposed Solution
Proposed solution is to limit the title via the UI to 255 so that the user cannot type any further. Maybe some wording that appears when the limit is encountered.

## Images
![image](https://user-images.githubusercontent.com/4653907/54531395-8e507580-495b-11e9-9017-ce910fbbf850.png)

![image](https://user-images.githubusercontent.com/4653907/54531449-b3dd7f00-495b-11e9-9ad5-f8ba58a56be9.png)

**Comment by Shazwazza** [comment]
Hi sorry for the delay but i think the referenced PR didn't reference this correctly, it is here and is merged https://github.com/umbraco/Umbraco-CMS/pull/5033 so i believe this is fixed and due out in 8.1

**Comment by Shazwazza** [comment]
Doh! actually sorry my mistake, it's this PR (the other one was closed) https://github.com/umbraco/Umbraco-CMS/pull/5034

**Comment by nul800sebastiaan** [comment]
Fixed in https://github.com/umbraco/Umbraco-CMS/pull/5374
