### ISSUE TITLE
V8: minor usability corrections for users section

### ISSUE THREAD

**Issue by nielslyngsoe** [umbraco/Umbraco-CMS#5008]
I have a few small correction to the user section that I would like:

1. Users that cannot be selected(like current user), should not display a hand-cursor when hovering the selectable-part of item in grid or list view.

2. The username should contain a href-link so you can open in a new tab, see latest correction for list-views where a solution for this have been implemented.

**Comment by kjac** [comment]
PR in #5015

**Comment by bergmania** [comment]
Fixed as part of https://github.com/umbraco/Umbraco-CMS/pull/4948
