### ISSUE TITLE
Preview becomes unusable with ~2000 nodes when under load of just 30 visitors

### ISSUE THREAD

**Issue by drbldgtl** [umbraco/Umbraco-CMS#5010]
I've been advised by Umbraco Support that this is a known issue. I'm creating this bug here at their request. In Zendesk these are tickets 34299 and 40555.

We are seeing preview times of over a minute in some circumstances with a site under load. This does not seem to happen when running locally but once hosted in Azure (this particular project doesn't use Umbraco Cloud). The issue only occurs the first time previewing a page following a save (obviously this is the most common use case).

The site was running on a single server, but we load balanced it as well so that the backoffice was running on seperate server and domain and the difference was marginal.

We did find that the issue was heavily affected by load on the site (5-fold), whether load balancing had been set up or not. When testing under a load balanced configuration, traffic was obviously only hitting the front-end site but it significantly affected the preview times when previews were being performed on the backoffice url/server.

Note that we are using relatively high-end Azure resources (P1 database at $450/m etc).

We can't release the code/database for reproduction unfortunately, but it should be reproducible by creating a basic site, creating a script to generate several thousand nodes. Once deployed somewhere, apply some load to the site and test the preview functionality.

The site is on 7.13.1 but we've had this issue for some time, I would guess at least since we were on 7.7.x.

I have been advised that this issue has been resolved in Umbraco 8 but this option is not available to us at this time.

**Comment by drbldgtl** [comment]
Is there any information you need from me to progress this issue?

**Comment by zpqrtbnk** [comment]
See #5059

**Comment by Shazwazza** [comment]
Should be fixed with #5059
