### ISSUE TITLE
UmbracoHelper and search

### ISSUE THREAD

**Issue by peracine** [umbraco/Umbraco-CMS#5017]
It seems the documentation regarding Searching (https://our.umbraco.com/documentation/Reference/Searching/Examine/quick-start) is obsolete. TypedSearch was deleted in this commit https://github.com/umbraco/Umbraco-CMS/commit/b48a7fa4a967f32dc9c11fc42336343eec666fa1#diff-9bf4e570832ca36f5d6f698ec365be4f
and everything concerning searching too: https://github.com/umbraco/Umbraco-CMS/commit/4976782247f613dea5a769dbc4073644996a3088#diff-9bf4e570832ca36f5d6f698ec365be4f
Is it possible to have a working example for searching? Should we still use this class?

**Comment by nul800sebastiaan** [comment]
Hi @peracine - v8 is a big change from v7 and we're working on getting the documentation updated, make sure to follow the Documentation status page: https://our.umbraco.com/documentation/v8documentation

`TypedSearch` hasn't been deleted but renamed to `Search`. If you need more help, make sure to post on the forum: https://our.umbraco.com 👍

**Comment by peracine** [comment]
Hi Sebastiaan,
AFAIK all search functionalities have been removed by @Shazwazza in this commit https://github.com/umbraco/Umbraco-CMS/commit/4976782247f613dea5a769dbc4073644996a3088 last year.
I Cannot see any search methods in this class. Did you mean ContentQuery?

**Comment by nul800sebastiaan** [comment]
Yeah, it's on ContentQuery, more info here: https://our.umbraco.com/forum/umbraco-8/96004-simple-search-in-v8
