### ISSUE TITLE
v8: Toggle more tab opens both apps + dropdown

### ISSUE THREAD

**Issue by bjarnef** [umbraco/Umbraco-CMS#5018]
When you toggle the more tab, which is shown when having several tabs/apps or on narrow screens, it seems to also open the tab dropdown.

![image](https://user-images.githubusercontent.com/2919859/54595557-2705f480-4a33-11e9-87c3-6eff82adc728.png)

Furthermore consider to remove the breadcrumb menu on narrow screen sizes or re-design how breadcrumbs are show on narrow screen sizes.

Besides that I think when opening sections or tabs/apps "more" menu, it should close the other one.

![image](https://user-images.githubusercontent.com/2919859/54595741-8532d780-4a33-11e9-911a-bfe4d8ef71c5.png)

**Comment by nul800sebastiaan** [comment]
This issue has been in the `up for grabs` state for quite a while now and it seems nobody is ready to pick this one up.

For now we'll close this issue to prevent the list of `up for grabs` from becoming very stale. We're happy to re-open it if someone still thinks it's good to work on this.

If anyone is about to pick this issue up to fix it, make sure to test first if you can reproduce the problem in the latest version before you start to work on it.

Thanks!
Sebastiaan on behalf of Umbraco HQ.
