### ISSUE TITLE
UriExtensions.IsClientSideRequest() throws unnecessary exception

### ISSUE THREAD

**Issue by ronaldbarendse** [umbraco/Umbraco-CMS#5019]
The `UriExtensions.IsClientSideRequest()` method is hit on every request and throws unnecessary exceptions when the URL contains invalid path characters:

```
System.ArgumentException: Illegal characters in path.
   at System.IO.Path.CheckInvalidPathChars(String path, Boolean checkAdditional)
   at System.IO.Path.GetExtension(String path)
   at Umbraco.Core.UriExtensions.IsClientSideRequest(Uri url)
```

These exceptions are also logged as errors, which can flood the log. As the comments of the method also indicate this is done for performance reasons, throwing/catching exceptions should be avoided.

The fix should be quite easy to implement by adding this check before the call to `Path.GetExtension`:
```c#
if (url.LocalPath.IndexOfAny(Path.GetInvalidPathChars()) >= 0) return false;
```

Reproduction
------------
### Steps to reproduce
Request an URL with invalid path characters, e.g. https://example.com/test|.aspx.

### Expected result
Not throw the exception and don't log it (and probably very slightly better performance :wink:).

### Actual result
An exception is thrown and an ERROR log entry is added containing 'Failed to determine if request was client side'.

**Comment by bergmania** [comment]
Hi @ronaldbarendse..

I'm a bit afraid of just inserting this. This leads to better performance when there are illegal characters, but worse performance if not. 

I executed the method before and after this fix. Timings are for 100.000 iterations

|Request|Result|Time with the fix| Time before|
|---|--|---|---|
| / | False |00:00:00.0315486|00:00:00.0119914|
|/base/somebasehandler|False|00:00:00.0404884|00:00:00.0198092|
|/favicon.ico|True|00:00:00.1135668|00:00:00.0743742|
|/home.aspx|False|00:00:00.0511477|00:00:00.0329900|
|/home\|.aspx|False|00:00:00.0221157|00:00:02.2644391|
|/umbraco_client/Tree/Themes/umbraco/style.css?cdv=37|True|00:00:00.0946528|00:00:00.0695493|
|/umbraco_client/Tree/treeIcons.css|True|00:00:00.0910480|00:00:00.0674269|

As you can see this is a huge benefit for the requests with illegal characters, but a disadvantage for the other requests.

I totally agree this should not spam the error-log, but I suggest to special handle this in the catch-block. As this already is a performance fix and the number of requests with illegal characters should be way less then request without  illegal characters.

**Comment by bergmania** [comment]
Ohh, as far as I can see the we only hit this catch block if there is illegal characters.  Either we do have to not log that, otherwise do we have to use another log level.

**Comment by bergmania** [comment]
PR to change the log level: https://github.com/umbraco/Umbraco-CMS/pull/5066

**Comment by ronaldbarendse** [comment]
@bergmania Performance for valid request shouldn't suffer indeed! As `Path.GetExtension()` also does the invalid characters check (and throws the `ArgumentException` if it contains any), that would be checked twice now and result in lower performance...

Is there any reason why this should be logged at all? It's not something you can fix or result in weird errors down line, right?

**Comment by bergmania** [comment]
@ronaldbarendse , I think it is nice to log such that we know what happens, when some requests are slow. As long as the level is as low as debug, it will never be a real problem in production environments under normal usage.

**Comment by ronaldbarendse** [comment]
Agreed: if it logs anything, it should be as low as DEBUG. Just curious why it's logged at all 😉

Also the performance difference is negligible at best, as 100.000 iterations differ 25ms at most (at a quick glance), so thats 0.0002ms per call: not something I would consider [slow](https://blog.codinghorror.com/the-sad-tragedy-of-micro-optimization-theater/).
