### ISSUE TITLE
v8: Sections are collapsed too early

### ISSUE THREAD

**Issue by bjarnef** [umbraco/Umbraco-CMS#5020]
At some responsive breakspoints it seems the sections are collapsed too early, e.g. here the "Media" section could have been visible.

![image](https://user-images.githubusercontent.com/2919859/54596002-16a24980-4a34-11e9-9e51-ed8a57b02aa9.png)

Does the sections need to collapse at 820px here?
![image](https://user-images.githubusercontent.com/2919859/54596199-726cd280-4a34-11e9-926d-49f00a0bbddd.png)

It would look like this:
![image](https://user-images.githubusercontent.com/2919859/54596361-c4adf380-4a34-11e9-8ad9-b6c18eb1e5df.png)

I agree there should be some distance to the search icon.

**Comment by FransdeJong** [comment]
I've created a pull request: https://github.com/umbraco/Umbraco-CMS/pull/5519
I could't use more space than 50 extra pixels in the current format but it makes a difference. This makes the menuitems vissible a little sooner but still maintains sepperation with the search, help and profile buttons.

**Comment by nul800sebastiaan** [comment]
Fixed in https://github.com/umbraco/Umbraco-CMS/pull/5519
