### ISSUE TITLE
UX: List view configuration should open as an infinite editor.

### ISSUE THREAD

**Issue by nielslyngsoe** [umbraco/Umbraco-CMS#5021]
I would like the List View-configuration (in DocType-configuration) to open as an infinite editor.

Today it looks like:
![image](https://user-images.githubusercontent.com/6791648/54744586-b0e6c680-4bc7-11e9-9d8a-a8b2fd1c57d1.png)

The reason for this is to ensure a better scope for the current editing phase. Today the "Save & publish"-button is placed in a way where it invites the user to confirm their changes by clicking it. But the save-feature of the list-view-configuration is an inline button further down the page. So we need to create a focus so the user doesn't see the "Save & Publish"-button.

By implementing this as infinite editing we will ensure that the users focus is only on the configuration of the list view and we will be able to make the "save"-button stay visible in bottom right corner always.

When implemented I would like Listview configuration to be visible in the "Permissions"-tab. Which I then want renamed to "Configurations".

All question and suggestions are very welcome.

**Comment by nathanwoulfe** [comment]
Looking at this one now, should be reasonably straight forward...

**Comment by nathanwoulfe** [comment]
![list-view](https://user-images.githubusercontent.com/3248070/62177648-0a86ab00-b389-11e9-9790-7bbaa1fa79ef.gif)

**Comment by nielslyngsoe** [comment]
Hi @nathanwoulfe 

I love what I see, could you make this as a PR?

**Comment by nathanwoulfe** [comment]
@nielslyngsoe, PR is in #6028 :smiley:

**Comment by nul800sebastiaan** [comment]
Fixed in https://github.com/umbraco/Umbraco-CMS/pull/6028
