### ISSUE TITLE
V8: Bring ping.aspx back

### ISSUE THREAD

**Issue by vonbarnekowa** [umbraco/Umbraco-CMS#5022]
In the new version of Umbraco, there is no way (I didn't found in the doc) to simply verify that the site is alive. It was possible on Umbraco 7, we only had to request `/umbraco/ping.aspx`.

**Comment by nul800sebastiaan** [comment]
Hi @vonbarnekowa - we encourage you to add your own way of checking this, for example here's a little bit of code you can drop into App_Code:

```
using Umbraco.Web.WebApi;

namespace My.Namespace
{
    public class AliveController : UmbracoApiController
    {
        public string GetResponse()
        {
            return "It's alive";
        }
    }
}
```

The route will be `/umbraco/api/alive/getresponse`

**Comment by snerpton** [comment]
I have an install of version 8.6.4 that Application Insights reports a constant stream of 404s for `/umbraco/ping.aspx`.

I could create a controller to handle this request, but surely if the core application is pinging this URL then the core application should provide an endpoint for it. It's no biggie, but it feels as though the endpoint was removed in v7 to v8 and the pinger was forgotten about, or is there a use case that I'm missing?

Cheers, C

**Comment by Shazwazza** [comment]
ping.aspx is webforms (obsolete). This was migrated to the `KeepAliveController` quite some time ago https://github.com/umbraco/Umbraco-CMS/blob/v8/contrib/src/Umbraco.Web/Editors/KeepAliveController.cs

**Comment by snerpton** [comment]
Hey @Shazwazza thanks for the reply. Then I guess my questions are:

- What is the purpose of pinging the obsolete ping.asp?
- If it doesn't server a purpose anymore because it has been replaced by the newer /keepalive/ping, might it be a candidate for removal by a community pull request?

Cheers, C

**Comment by Shazwazza** [comment]
Nowhere in the code is ping.aspx called. The KeepAliveController is called from here https://github.com/umbraco/Umbraco-CMS/blob/v8/contrib/src/Umbraco.Web/Scheduling/KeepAlive.cs#L53 the default value is set here https://github.com/umbraco/Umbraco-CMS/blob/v8/contrib/src/Umbraco.Core/Configuration/UmbracoSettings/KeepAliveElement.cs#L10 so unless you have specifically set this to ping.aspx it won't be calling that. There's a reasonable chance that someone has setup an external health check or ping (like pingdom) on the site that is trying to send to ping.aspx.

**Comment by snerpton** [comment]
> Nowhere in the code is ping.aspx called. The KeepAliveController is called from here https://github.com/umbraco/Umbraco-CMS/blob/v8/contrib/src/Umbraco.Web/Scheduling/KeepAlive.cs#L53 the default value is set here https://github.com/umbraco/Umbraco-CMS/blob/v8/contrib/src/Umbraco.Core/Configuration/UmbracoSettings/KeepAliveElement.cs#L10 so unless you have specifically set this to ping.aspx it won't be calling that. There's a reasonable chance that someone has setup an external health check or ping (like pingdom) on the site that is trying to send to ping.aspx.

Just to wrap this up, obviously @Shazwazza was right, and it turns out a third party was pinging the old endpoint (`/umbraco/ping.aspx`).
