### ISSUE TITLE
V8 : Query Builder code error returning child items of type

### ISSUE THREAD

**Issue by scottleslie** [umbraco/Umbraco-CMS#5024]
When using Query Builder in backoffice, I wish to return ( in example below) only blog posts, however all child items are returned.

Reproduction
------------

CONTENT TREE:

-BlogHome (bloghome)
-----Blog1 (blogpost)
-----Blog2 (blogpost)
-----Blog3 (blogpost)
-----Page1 (page)

@{
var selection = Umbraco.Content(Guid.Parse("1d770f10-d1ca-4a26-9d68-071e2c9f7ac1"))
    .Children("blogpost")
    .Where(x => x.IsVisible());
}

### Bug summary

Was expecting only 3 items to be returned (Blog1,Blog2,Blog3); However 4 items return (Blog1,Blog2,Blog3,Page1)

### Specifics

Tested in 8.01

### Steps to reproduce

In Umbraco backoffice, use "Query Builder"  

"I want Content of type "BlogPost" from Blog"

### Expected result

Was expecting only 3 items to be returned (Blog1,Blog2,Blog3);

### Actual result

However 4 items return (Blog1,Blog2,Blog3,Page1)

**Comment by bergmania** [comment]
Bug confirmed.

Workaround, change:
```
var selection = Umbraco.Content(Guid.Parse("1d770f10-d1ca-4a26-9d68-071e2c9f7ac1"))
.Children("blogpost")
.Where(x => x.IsVisible());
```
to
```
var selection = Umbraco.Content(Guid.Parse("1d770f10-d1ca-4a26-9d68-071e2c9f7ac1"))
.ChildrenOfType("blogpost")
.Where(x => x.IsVisible());
```

**Comment by bergmania** [comment]
Fixed in https://github.com/umbraco/Umbraco-CMS/commit/c589ef199517803796bd26095ed0ed8fad4385ea
