### ISSUE TITLE
Display focal point coordinates

### ISSUE THREAD

**Issue by TheBeardedLlama** [umbraco/Umbraco-CMS#5027]
AFAIK there is no way to view the focal point coordinates for an image in the back office.

This feature could also be augmented so that the focal point coordinates could be manually entered in the GUI

I'd be happy to work on a PR for this if people think it's a valuable feature.

**Comment by nul800sebastiaan** [comment]
Can you explain what that would do and who it would help, a usecase would be handy.

**Comment by nul800sebastiaan** [comment]
I'll close this one for now due to lack of activity. I would still love to hear more about the use case when you have a moment though!

**Comment by TheBeardedLlama** [comment]
Hey @nul800sebastiaan 
apologies for the delay in replying, life's been interesting...

I'm not on that contract anymore. However, the requirement was to verify that the coordinates matched the requirement without having to go into the db.

Displaying information that is already on the client side should be straightforward, so I'm not sure why a case has to be made?

**Comment by TheBeardedLlama** [comment]
context: I was migrating a site from Sitecore and needed to make sure things were the same
