### ISSUE TITLE
V8 VariantsMigration.cs ADD COLUMN error

### ISSUE THREAD

**Issue by ksingercoffey** [umbraco/Umbraco-CMS#5032]
The SQL syntax to add the versionId2 column is invalid.

Reproduction
------------

Upgrading from a 7.11.0 database seems to do the trick.

### Bug summary

When upgrading from 7.11.0 the Umbraco.Core/Migrations/Upgrade/V_8_0_0/VariantsMigration.cs code tries to add a column using this syntax on line 85:

    $"ALTER TABLE {PreTables.PropertyData} ADD COLUMN versionId2 INT NULL;"

SQL Server complains about the COLUMN keyword.
### Specifics

I believe the syntax should be:

    $"ALTER TABLE {PreTables.PropertyData} ADD versionId2 INT NULL;"

### Steps to reproduce

Start with an Umbraco 7.11.0 install and try to upgrade.

### Expected result

The upgrade succeeds.

### Actual result

Exception:

    System.Data.SqlClient.SqlException (0x80131904): Incorrect syntax near the keyword 'COLUMN'.

**Comment by nul800sebastiaan** [comment]
Sorry about that, we're not yet ready with the upgrade path to v8, it's coming in 8.1.0. I'll see what we can do to disable the upgrade installer for now in 8.0.x.

**Comment by ksingercoffey** [comment]
No worries! Is there anything we can do to help out? I pulled down the latest code to fix the syntax, but noticed things were still a bit broken after that.
