### ISSUE TITLE
Radio button list is wrongly positioned in narrow viewports

### ISSUE THREAD

**Issue by nielslyngsoe** [umbraco/Umbraco-CMS#5038]
The radio button list items jumps to the right side of the page in a narrow viewport.

![image](https://user-images.githubusercontent.com/6791648/54745586-2784c380-4bca-11e9-8d61-96eb9244e2a3.png)

**Comment by FransdeJong** [comment]
Fixed in PR https://github.com/umbraco/Umbraco-CMS/pull/5521

**Comment by nul800sebastiaan** [comment]
Fixed in https://github.com/umbraco/Umbraco-CMS/pull/5521
