### ISSUE TITLE
v8: Add IsVisible extension method on IPublishedElement

### ISSUE THREAD

**Issue by bjarnef** [umbraco/Umbraco-CMS#5039]
Previously in Umbraco 7 Nested elements used in Nested Content was `IEnumerable<IPublishedContent>` and now in v8 we have `IEnumerable<IPublishedElement>`

In v7 it you added a property with alias `umbracoNaviHide` to Nested Content document type, you were able to use the `.IsVisible()` extension method.

It seems we can't use this in v8, e.g.
```
var elements = Model.Value<IEnumerable<IPublishedElement>>("elements").Where(x => x.IsVisble());
```

instead you should use one of the following, where the property in Nested Content is a True/False (toggle) property.
```
var elements = Model.Value<IEnumerable<IPublishedElement>>("elements").Where(x => x.Value<bool>("umbracoNaviHide") == false)

var elements = Model.Value<IEnumerable<IPublishedElement>>("elements").Where(x => x.Value<bool>("disabled") == false)
```

However it seems this always return false, even the toggle is cheked/selected.

```
var elements = Model.Value<IEnumerable<IPublishedElement>>("elements")
var items = elements.ToList();
var first = items.First();
var prop = first.Value<bool>("umbracoNaviHide"); // returns false no matter the toggle is checked/selected or not.
```

![image](https://user-images.githubusercontent.com/2919859/54745774-ae39a080-4bca-11e9-9407-952e17dd856c.png)

**Comment by bjarnef** [comment]
`.IsVisible()` extension method:
https://github.com/umbraco/Umbraco-CMS/blob/735d7592089838d546717f1191536412109dc895/src/Umbraco.Web/PublishedContentExtensions.cs#L305-L313

I guess it also should exists in `PublishedElementExtensions.cs` similar to `.IsComposedOf()` extension.
https://github.com/umbraco/Umbraco-CMS/blob/91c52cffc8b7c70dc956f6c6610460be2d1adc51/src/Umbraco.Web/PublishedElementExtensions.cs#L37-L40

https://github.com/umbraco/Umbraco-CMS/blob/735d7592089838d546717f1191536412109dc895/src/Umbraco.Web/PublishedContentExtensions.cs#L116-L119

**Comment by kjac** [comment]
PR in #5041
