### ISSUE TITLE
Windows Defender removes dlls

### ISSUE THREAD

**Issue by NathalieLarsson** [umbraco/Umbraco-CMS#5042]
Microsoft Defender removes Examine.dll, Umbraco.Web.UI.dll, Umbraco.Web.dll files both when I unzip the Umbraco source code downloaded from Github and/or when I try to install UmbracoCms via Nuget. 

Problem occurred after threat definition update.

- Windows 10 (build 17134)
- Umbraco 8.0.1
- Visual Studio 2017

![image](https://user-images.githubusercontent.com/475458/54769647-e6100a80-4c01-11e9-816a-7cd796515101.png)

![image](https://user-images.githubusercontent.com/475458/54769959-9716a500-4c02-11e9-973e-8a805dceb3f6.png)

![image](https://user-images.githubusercontent.com/475458/54770154-fb396900-4c02-11e9-9c61-168e7a357074.png)

**Comment by dawoe** [comment]
Hi @NathalieLarsson 

Thanks for reporting this. It seems the second report of this today : https://github.com/umbraco/Umbraco-CMS/issues/5040

Not sure what is going on. Needs investigation.

Dave
Dave [Community Pull Request team](https://umbraco.com/blog/introducing-the-new-cpr-team/)

**Comment by Shazwazza** [comment]
This can be tracked via the examine repo https://github.com/Shazwazza/Examine/issues/117 ... though the screenshot seems to indicate that Umbraco.Web DLLs are affected too 🤔
