### ISSUE TITLE
v8: TinyMCE image tools

### ISSUE THREAD

**Issue by bjarnef** [umbraco/Umbraco-CMS#5046]
At the moment in seems Umbraco v8 is using TinyMCE v4.9.2
https://github.com/umbraco/Umbraco-CMS/blob/91c52cffc8b7c70dc956f6c6610460be2d1adc51/src/Umbraco.Web.UI.Client/package.json#L42

However when selecting or right-clicking an image, it doesn't seem to have the image tools as in this demo https://www.tiny.cloud/docs/demo/basic-example/ (TinyMCE v5).

Umbraco is using a custom toolbar action to open media picker, but some of the features in the default image plugin to set width/height + Constrain proportions and set image description (alternative text). Maybe these additonal options should be added to the RTE media picker?

![image](https://user-images.githubusercontent.com/2919859/54816429-7e56cf80-4c94-11e9-93e0-8b04bdff56ac.png)

![image](https://user-images.githubusercontent.com/2919859/54816497-a5150600-4c94-11e9-8cef-4c52715caf7c.png)

![image](https://user-images.githubusercontent.com/2919859/54816505-ae9e6e00-4c94-11e9-82dc-68bf198b2ac9.png)

These right-click actions could trigger the link and media picker.

For tables it has the options to configurate properties, although the right-click action menu is not enabled.

![image](https://user-images.githubusercontent.com/2919859/54819067-1952a800-4c9b-11e9-9d4f-3a2dddde01ab.png)

**Comment by nul800sebastiaan** [comment]
I've marked this as "Up for grabs" so that you or someone else coming along could create a pull request for it.

**Comment by nul800sebastiaan** [comment]
This issue has been in the `up for grabs` state for quite a while now and it seems nobody is ready to pick this one up.

For now we'll close this issue to prevent the list of `up for grabs` from becoming very stale. We're happy to re-open it if someone still thinks it's good to work on this.

If anyone is about to pick this issue up to fix it, make sure to test first if you can reproduce the problem in the latest version before you start to work on it.

Thanks!
Sebastiaan on behalf of Umbraco HQ.
