### ISSUE TITLE
Moving node doesn't create redirect. 

### ISSUE THREAD

**Issue by dzordzs** [umbraco/Umbraco-CMS#5050]
When you move the node to another level, URL redirect is not created. 
How to reproduce? 

1. Install standard Starter Kit 
2. Move About Us under People
3. Check Redirects and you will see they haven't been created. 

Tested this on latest CMS - 8.0.1

**Comment by jmayntzhusen** [comment]
This has been tested on 8.1.3 to still be an issue.

**Comment by nul800sebastiaan** [comment]
Fixed in https://github.com/umbraco/Umbraco-CMS/pull/6344
