### ISSUE TITLE
V8: TinyMCE does not respec validElements configuration in tinyMCEConfig.config

### ISSUE THREAD

**Issue by yaplex** [umbraco/Umbraco-CMS#5052]
I want to use my own HTML code inside of Rich text editor, but when inserting a text inside of **div** tag and saving it, the data actually not updated and after reloading I have the same text as it was before

Documentation suggests than editing
\config\tinyMceConfig.config
and updating it to the following should solve the issue, but it does not work
```
<validElements>
    <![CDATA[*[*]]]>
  </validElements>
```
This was working in version 7, but in version 8 it does not work.

To reproduce modify the tinyMceConfig file and try to save text like this (use "edit HTML" feature of rich text editor):
`<div>hello</div>
`
This looks like a client-side issue, because when examining post request to the server, I do not see text which I entered, but instead I see my old text.

**Comment by nul800sebastiaan** [comment]
Works for me, before saving, after saving and after resfreshing the page I get:

![image](https://user-images.githubusercontent.com/304656/54863967-bf5fea00-4d4f-11e9-9dc0-b1d39aa2e957.png)

What I did after changing the config: 
- Update the version in ClientDependency.config
- Touched the Web.config so a restart of the site would happen
- Hard refresh of the browser cache

Maybe that will help for you too.

**Comment by yaplex** [comment]
@nul800sebastiaan thanks for verifying this, but I did the same steps as you mentioned, it still does not work for me (updated tinymceconfig file, changed the version in ClientDependence, updated web.config and resaved, do iisreset, and tried new incognito chrome window). What would be the best way to debug this? where should I look to find why it does not work? It is clearly a client-side issue as my new entered HTML code not passed to the server. I looked in javascript, it is all minified, so it is not easy to find where exactly TinyMCE doing validation for my input.

**Comment by yaplex** [comment]
trying a different browser (Mozilla Firefox) also did not help

**Comment by sotirisf** [comment]
I can confirm that it won't work for me as well, trying all the steps described above. Umbraco version 8.9.1.

**Comment by jason-delaplain** [comment]
Is this still an issue in Umbraco 12+?  I can't get the backoffice to use the updated ValidElements on this version either.
