### ISSUE TITLE
dashboard.umbraco.org shouldn't be able to crash the backoffice

### ISSUE THREAD

**Issue by abjerner** [umbraco/Umbraco-CMS#5057]
As `dashboard.umbraco.org` is currently down, it causes the backoffice to be unresponsive, without the user being able to continue. From what I can tell, it seems to be when the following criteria are met:

- Running 7.14 and V8 (or latest code from GitHub). It may also affect older versions.
- Default *Get Started* dashboard hasn't been removed under *Content*
- User hasn't dismissed the default tour yet

The error message in the browser console is `Cannot read property 'element' of undefined`, and seems to come from this line:

https://github.com/umbraco/Umbraco-CMS/blob/dev-v7/src/Umbraco.Web.UI.Client/src/common/directives/components/application/umbtour.directive.js#L320

I'm not sure why `dashboard.umbraco.org` being down is able to crash the tour directive though.

Another user also reported the error on Our: https://our.umbraco.com/forum/using-umbraco-and-getting-started/96460-umbraco-7132

**Comment by javafun** [comment]
I am on 7.12.4, the same issue here.

**Comment by abjerner** [comment]
@javafun You can disable the dashboard by going to `/Config/Dashboard.config` and then remove or outcomment the following lines:

```xml
<tab caption="Get Started">
  <access>
    <grant>admin</grant>
  </access>
  <control showOnce="true" addPanel="true" panelCaption="">
    views/dashboard/default/startupdashboardintro.html
  </control>
</tab>
```

**Comment by javafun** [comment]
Thanks for your tips. If I changed this file, will future upgrade override it?

**Comment by abjerner** [comment]
@javafun It depends a bit on how you update your Umbraco. If you have installed via NuGet and try to update, Visual Studio will ask you whether you wish to overwrite the file.

I'm using Git, so my own approach for updating is normally just to let the updater overwrite config files, but then use a Git diff tool to check what has changed, and discard changes that I don't wish to keep - for instance if these lines were added again by the update.

**Comment by Shazwazza** [comment]
Thanks for reporting, have marked up for grabs to see if we can get some help from the community. I suspect we prob just need a try/catch when making the request to get the dashboard to make sure the request doesn't fail, or by checking the response correctly.

**Comment by nul800sebastiaan** [comment]
This issue has been in the `up for grabs` state for quite a while now and it seems nobody is ready to pick this one up.

For now we'll close this issue to prevent the list of `up for grabs` from becoming very stale. We're happy to re-open it if someone still thinks it's good to work on this.

If anyone is about to pick this issue up to fix it, make sure to test first if you can reproduce the problem in the latest version before you start to work on it.

Thanks!
Sebastiaan on behalf of Umbraco HQ.
