### ISSUE TITLE
BackOffice won't load when installing from UmbracoCms 8.01 Nuget Package

### ISSUE THREAD

**Issue by groogiam** [umbraco/Umbraco-CMS#5058]
I am attempting to setup Umbraco using the 8.0.1 Nuget Package using these instructions.
https://our.umbraco.com/documentation/getting-started/setup/install/install-umbraco-with-nuget

Reproduction
------------
Using Visual Studio 15.9.9 I followed the procedure in the guide above exactly. After using the default installation parameters I attempted to login to the BackOffice but the application just hangs with the loading indicator/overlay. See image below.

![image](https://user-images.githubusercontent.com/1992395/54890005-cf75e780-4e7d-11e9-92a6-5dfdeeaf6334.png)

**Comment by groogiam** [comment]
Looks like this is the same as https://github.com/umbraco/Umbraco-CMS/issues/5057

**Comment by nul800sebastiaan** [comment]
Closing in favor of #5057  - thanks!
