### ISSUE TITLE
Alternate Media Cache for v7

### ISSUE THREAD

**Issue by zpqrtbnk** [umbraco/Umbraco-CMS#5060]
depends on https://github.com/umbraco/Umbraco.Private/issues/290

which is determining pros/cons/viability of moving media cache out of lucene and what options are available to us.

**Comment by zpqrtbnk** [comment]
Move the Media Cache out of Examine / Lucene, as it's one of the biggest (?) problem with startup times (??)

**Comment by nul800sebastiaan** [comment]
See #5115 :)
