### ISSUE TITLE
Merge v7 to v8

### ISSUE THREAD

**Issue by zpqrtbnk** [umbraco/Umbraco-CMS#5061]

**Comment by zpqrtbnk** [comment]
Beware of #2441

**Comment by warrenbuckley** [comment]
I have done the merge in it's own PR here https://github.com/umbraco/Umbraco-CMS/pull/5223

@Shazwazza or @zpqrtbnk please can you tripple check this as I am not 100% confident in this mege :S

**Comment by nul800sebastiaan** [comment]
Just pushed the merge to `v8/dev`.
