### ISSUE TITLE
Umbraco 8.0.1 PluginController attribute does not work on Rootnode

### ISSUE THREAD

**Issue by deMD** [umbraco/Umbraco-CMS#5069]
When creating a plugin with the PluginController attribute no path is generated for the root node when overriding CreateRootNode. Setting root.RoutePath will results in an Url in the umbraco/views folder instead of the expected App_Plugins/[pluginalias]/... and without setting root.RoutePath a path is not generated at all.

### Steps to reproduce:
- Create a new Umbraco application
- Create a Custom tree controller
- Override the required methods
- Override CreateRootNode:
```TreeNode root = base.CreateRootNode(queryStrings);
            // Without this setter a path is also not generated in umbraco/views 
            //// root.RoutePath = $"{Constants.Applications.Settings}/scheduledjobs/overview";
            root.Icon = "icon-page";
            root.HasChildren = false;
            root.MenuUrl = null;

            return root;
```

### Specifics
- Umbraco v8.0.1
- Tested in both Chrome 73.0.3683.86 and Edge 44.17763.1.0

![image](https://user-images.githubusercontent.com/22070292/54925268-3e9b1c80-4f0e-11e9-8e6c-213d1417653e.png)

Controller:
[ScheduledJobsTreeController.zip](https://github.com/umbraco/Umbraco-CMS/files/3003587/ScheduledJobsTreeController.zip)

![image](https://user-images.githubusercontent.com/22070292/54925581-dd277d80-4f0e-11e9-9434-fed79bbdf1c8.png)

As far as I can tell I have implemented the controller as per documentation found here: [Single Node Trees](https://our.umbraco.com/documentation/extending/section-trees/trees#single-node-trees--customising-the-root-node-action)

**Comment by Shazwazza** [comment]
Is this because your folder name is `scheduledjobsAlias` with a suffixed `Alias` string whereas your actual route path is just `scheduledjobs` ?

**Comment by deMD** [comment]
No, if I enable the RoutePath it resolves the url to the Umbraco/Views/scheduledjobs/overview.html while I would expect it to resolve to /App_Plugins/scheduledjobs/backoffice/scheduledjobs/overview.html with RoutePath enabled, even if the view or folder would not exist.

But just to make sure I tested it and removed the Suffix Alias from the tree alias, and sadly I still get an error with the wrong path:

![image](https://user-images.githubusercontent.com/22070292/54980823-16133100-4fa7-11e9-8089-2a502e95f8ad.png)
![image](https://user-images.githubusercontent.com/22070292/54980849-24614d00-4fa7-11e9-9d31-1dbace71848b.png)

**Comment by Shazwazza** [comment]
It's a casing issue. This should be taken care of by the core but that's not currently the case. 

for all references of `scheduledJobs`, make sure the casing is the same including in your `root.RoutePath = $"{Constants.Applications.Settings}/scheduledJobs/overview";`

The fix should be in the JS `treeService.getTreePackageFolder` where it compares `return item.alias === treeAlias;`, instead this should to an invariant compare with `localCompare` preferably (see https://stackoverflow.com/questions/2140627/javascript-case-insensitive-string-comparison)

Do you think you might have time to submit a PR?

**Comment by deMD** [comment]
I'll look into it :)

**Comment by nul800sebastiaan** [comment]
Fixed in https://github.com/umbraco/Umbraco-CMS/pull/5090
