### ISSUE TITLE
V8: Text modified in HTML editor not saving to Umbraco

### ISSUE THREAD

**Issue by yaplex** [umbraco/Umbraco-CMS#5075]
This is an addition to defect #5052 which was closed, but defect still exists. I just providing more information on how to reproduce. 
I recorded a video with my steps. 
https://youtu.be/fQoBoHLYpmY
CC: @nul800sebastiaan

**Comment by kjac** [comment]
Must be an issue specific to using RTE in the grid; it works perfectly fine when the RTE is used as a stand-alone property.

**Comment by mathewknott** [comment]
I'm having the same issue. The way I reproduce is..

1. I open the page. 
2. Swtich to code view. 
3. Make the change.
4. Close the code view and press "save and publish".
5. Result: No change gets saved.

If I make the change directly in the RTE view, it will detect the change and save correctly.

**Comment by kjac** [comment]
@mathewknott are you using an RTE in the grid or directly on the content as a stand-alone editor?

**Comment by mathewknott** [comment]
> @mathewknott are you using an RTE in the grid or directly on the content as a stand-alone editor?

Its the RTE in the grid.

**Comment by nielslyngsoe** [comment]
PR https://github.com/umbraco/Umbraco-CMS/pull/5318
