### ISSUE TITLE
v8: Make Permission angular component more generic

### ISSUE THREAD

**Issue by mattbrailsford** [umbraco/Umbraco-CMS#5077]
In the user groups editor, there is a list of toggle switches for toggling on and off permissions. In the angular js code, this has been coded as a Permission component for this exact purpose. Given it's just a list of toggle switches with text next to them, I think this should be made more generic so that it can be reused elswhere.

Case in point, if you look in the languages editor view, this also has a list of toggle switches and this has reused the permissions css classes which in this context makes this harder to understand as the list has nothing to do with permissions.

**Comment by Shazwazza** [comment]
makes sense, I've marked this as "Up for grabs" so that you or someone else coming along could create a pull request for it.

**Comment by kjac** [comment]
Super great idea! I'll throw something together 👍

**Comment by kjac** [comment]
PR in #5096
