### ISSUE TITLE
V8: Member-group member-listviews are not available

### ISSUE THREAD

**Issue by nielslyngsoe** [umbraco/Umbraco-CMS#5078]
Member-Groups member-overviews does not appear next to 'Members' and 'All Members'.

I think they are suppose to do, at least when you have added members to them.

See this example:

I expected 'another member group' to appear together with 'Members' and 'All Members'.

![image](https://user-images.githubusercontent.com/6791648/54996486-bb3f0100-4fc9-11e9-974c-90709a983e06.png)

**Comment by Shazwazza** [comment]
@nielslyngsoe those are not the same thing. Member Groups are **not** Member Types.

Member Types are like Content Types and Media Types. They are 'schema' and should not be edited by people who are just editing members (i.e. content).

Member Groups are just groups that members can be added to.

**Comment by Shazwazza** [comment]
You can find Member Types in the Settings section, along with Content Types and Media Types.

**Comment by nielslyngsoe** [comment]
Whoops, second time misunderstanding something about Members. But good to get that clarified. This just underlines that we need to visually rearrange something for this to become logic. So this then became a task for my self then.
Thanks
