### ISSUE TITLE
Content Service - Updating a culture varying property throws SqlException (Cannot insert duplicate key row)

### ISSUE THREAD

**Issue by homemdasneves** [umbraco/Umbraco-CMS#5083]
I'm developing a method to create or update some content in my project. I got stuck in a situation where the creation runs fine but the updates always fail with the following SqlException: 
`Cannot insert duplicate key row in object 'dbo.umbracoPropertyData' with unique index 'IX_umbracoPropertyData_VersionId'. The duplicate key value is (2437, 145, 2, <NULL>).\r\nThe statement has been terminated.`
I narrowed it down to a simple update of a culture varying property, using the content service.

Reproduction
------------
I have a _TestVariant_ culture variant document type, with a culture varying _bio_ property.

```csharp
var docType = Services.ContentTypeService.Get(TestVariant.ModelTypeAlias);

// create a new content
IContent newContent = new Content("My Content", -1, docType, "en-US");
newContent.SetCultureName("My Content", "pt-PT");
newContent.SetValue("bio", "original", "en-US");
newContent.SetValue("bio", "original", "pt-PT");
Services.ContentService.SaveAndPublish(newContent);

// update a culture varying property
var contentToUpdate = CS.GetById(newContent.Key);
contentToUpdate.SetValue("bio", "updated", "en-US");
contentToUpdate.SetValue("bio", "updated", "pt-PT");


// Following line will throw exception: 
// Message: Cannot insert duplicate key row in object 'dbo.umbracoPropertyData' with unique index 'IX_umbracoPropertyData_VersionId'. The duplicate key value is (2414, 51, 2, <NULL>)
Services.ContentService.SaveAndPublish(contentToUpdate);
```

### Specifics
- I'm running Umbraco 8.0.1 and running the above code in a UmbracoApiController

**Comment by homemdasneves** [comment]
Got it: I should be using the culture ISO code _pt_ and not _pt-PT_

**Comment by zpqrtbnk** [comment]
Hey - can you confirm that the mistake "you" made was setting a value for culture *pt* instead of *pt-PT*, and *pt* is not a valid culture (not a configured language) but *pt-PT* is? It annoys me that all you get in that case is a Sql exception, and not something more meaningful.

**Comment by homemdasneves** [comment]
That's exactly what happened.
