### ISSUE TITLE
v8: Make templates based on file structure instead of database

### ISSUE THREAD

**Issue by yaplex** [umbraco/Umbraco-CMS#5084]
Currently, when you want to create a new template you have to create it in Umbraco Settings first. 
If you try to create a template using Visual studio Umbraco does not know about this template. 

Partial views work correct, if I create a new partial view in Visual Studio and refresh Umbraco, I see my new view there, but this is not working with regular pages. 
Could you please make a config setting or something to read templates from disk instead of managing them in a database.

**Comment by Shazwazza** [comment]
Hi thanks for getting in touch. Templates are required to be in the database for a couple of reasons - templates can have a name, not just a file name and then templates are associated in the database to many different entities by their IDs. Partial views are simply files, whereas templates are not.

You can create template views in VS and then if you create a corresponding template in the back office with the same name, it will not overwrite your view, it will use the existing view found by name.

**Comment by yaplex** [comment]
Ok, thanks for explanation @shazwazza
