### ISSUE TITLE
v8: Inconsistant spacing between umb-box and umb-group-panel elements

### ISSUE THREAD

**Issue by mattbrailsford** [umbraco/Umbraco-CMS#5094]
Currently in v8, in the content section, the page is broken up into groups using elements with a css class of `umb-group-panel`. These groups are spaced with 20px margin between them.

However, in other areas of the system, the editor is broken up into groups using an element with a css class of `umb-box` which for the most part is the same, but these groups are spaced out with 8px between them.

Apart from the fact I think these should probably be reusing the same angular component in order to be standardised, at the very least, I think these should have consistant spacing. My personal preference is 20px margin between items.

**Comment by Shazwazza** [comment]
thanks for reporting, will mark up-for-grabs and see if someone can come along to help out on this one.

**Comment by kjac** [comment]
Additionally a few places are using multiple `umb-expansion-panel` containers which are spaced by 16px bottom margin.

I'm compiling a list of affected UI parts, then I'll push a PR.

**Comment by kjac** [comment]
PR in #5104
