### ISSUE TITLE
V8: Charlimit of textstring (textbox) DataType appears when swithing on listview

### ISSUE THREAD

**Issue by ReVoid** [umbraco/Umbraco-CMS#5098]
Swithing to splitview forcing charlimit appearing in textstring property editor, even if there is no limitation 

### Specifics

Umbraco v8.0.1

### Steps to reproduce

1. Make a textstring property in a page with no char limitation
2. Switch to splitview several times
![my2](https://user-images.githubusercontent.com/12345710/55146172-1e10d380-5155-11e9-959a-9ef48b67badf.gif)

### Expected result

No charlimits appearing, just clean textbox without any anotations

### Actual result

unnecessary charlimit appears

**Comment by nul800sebastiaan** [comment]
Thanks, that's a weird one! I've just tried to reproduce on the latest code and I can't make it fail at this point, loads has been fixed since 8.0.1 so I am assuming we already fixed this along the way.
Be on the lookout for the 8.1.0 release coming up!

Thanks for reporting!
