### ISSUE TITLE
VS.2017 New UmbracoV8 - Error: Type 'Umbraco.Web.UmbracoApplication' Parser Error

### ISSUE THREAD

**Issue by hannakfoo** [umbraco/Umbraco-CMS#5100]
Visual Studio 2017.

New Project - Blank C# Webproject
Nuget PackageManager: "Install-Package UmbracoCms" V 8.0.1
Nuget update: "Microsoft.CodeDom.Providers.DotNetCompilerPlatform v.2.0.1"
Build project.
Run
This produces the error:
Line 1: <%@ Application Inherits="Umbraco.Web.UmbracoApplication" Language="C#" %>

![image](https://user-images.githubusercontent.com/3263156/55156774-194f1e00-515b-11e9-8de8-7bdfbb479940.png)

I am using the latest Visual Studio update 14.9.10

![image](https://user-images.githubusercontent.com/3263156/55156831-3ab00a00-515b-11e9-853f-1ca9ccc81635.png)

**Comment by dampee** [comment]
Have you selected framework 4.7.2 during creation of the new project?
(as described in the [documentation](https://our.umbraco.com/documentation/Getting-Started/Setup/Install/install-umbraco-with-nuget))

**Comment by hannakfoo** [comment]
@dampee thank you for your response. My bad ... i hadnt selected 4.7.2.
