### ISSUE TITLE
Some SetValue methods are missing for files

### ISSUE THREAD

**Issue by zpqrtbnk** [umbraco/Umbraco-CMS#5102]
From mhl:
>Are you no longer able to set an `HttpPostedFileBase` object in the `SetValue` method on a content item? We do it in the V7 MVC training, where we need to handle image upload from the frontend. However when I am trying it using V8 I get ...

also see

https://github.com/umbraco/Training.MvcCourse/blob/master/src/complete/MvcCourse/Controllers/DocumentationFormController.cs#L61
https://github.com/umbraco/Training.MvcCourse/blob/master/src/complete/MvcCourse/Models/DocumenationFormModel.cs#L21

This worked just fine as V7 allowed for `HttpPostedFileBase` on `SetValue`

What is the right way to do it on 8? see `MediaController.PostAddFile()`... this is not _super_ convenient ;-(

**Comment by Shazwazza** [comment]
FYI HttpPostedFileBase is an old System.Web thing, prob used in MVC too maybe, the media controller is WebApi and doesn't know about this type. Should be reasonably easy to convert HttpPostedFileBase into a stream to use in the IMedia.SetValue. It exposes an `InputStream` so can probably just use that.

**Comment by Shazwazza** [comment]
The extension method `SetValue` that accepts a stream that is used in the MediaController is in the namespaces `Umbraco.Core` so having `using Umbraco.Core;` is important.

The extension method signature is this:

```cs
void SetValue(this IContentBase content, IContentTypeBaseServiceProvider contentTypeBaseServiceProvider, string propertyTypeAlias, string filename, Stream filestream, string culture = null, string segment = null)
```

So the tricky part here is that it needs this special `IContentTypeBaseServiceProvider`, but that is available on the `ServiceContext. So here's an example on a `SurfaceController`: 

```cs
using Umbraco.Core; //important since this contains the ext method

public class Test : SurfaceController
{
    public ActionResult Upload(HttpPostedFileBase file)
    {
        var media = Services.MediaService.GetById(123);
        media.SetValue(Services.ContentTypeBaseServices, "myFile", file.FileName, file.InputStream);
        return View();
    }
}
```

It would be possible and slightly nicer to add another extension method to accept `HttpPostedFileBase` which would result in the usage looking like:

```cs
media.SetValue(Services.ContentTypeBaseServices, "myFile", file);
```

We could make that but it will just be a wrapper to the above example.

**Comment by zpqrtbnk** [comment]
FWIW I have created the overload and pushed to `dev-v8` - will be in an upcoming release.
