### ISSUE TITLE
V8: Can't use dialogService in backoffice angular controller

### ISSUE THREAD

**Issue by Questo** [umbraco/Umbraco-CMS#5103]
So I'm building a custom grid editor to be able to select a node in the content tree and have it be displayed as a clickable button that will redirect to user to the selected node.

However, I've barely gotten started, and it's already crashing. It doesn't seem like I can inject the "dialogService" into my angular-controller. At first I didn't think I could inject any service, but I tried the "assetsService" and that works fine!

Reproduction
------------

Create a custom grid editor plugin, complete with an angular controller and try to inject the dialogService the normal way.

### Console error

```
Error: "[$injector:unpr] Unknown provider: dialogServiceProvider <- dialogService <- rexel.grid.contentcontroller
https://errors.angularjs.org/1.7.5/$injector/unpr?p0=dialogServiceProvider%20%3C-%20dialogService%20%3C-%20rexel.grid.contentcontroller"
```

Have you guys removed the dialogService or what?

**Comment by abjerner** [comment]
Hi @Questo,

The `dialogService` was deprecated in Umbraco 7.4, and has been removed completely from V8. You should instead use the `editorService`, which is a new thing in V8.

Unfortunately the Umbraco Angular documentation hasn't yet been updated for V8, but you should be able to pull down the Umbraco source code, and follow the instructions on the page below to generate the documentation locally:

https://our.umbraco.com/apidocs/ui/#/api

Hopefully the online documentation will be updated soon.

**Comment by Shazwazza** [comment]
Thanks for responding @abjerner. Yes much has changed in v8, we are still working towards getting documentation updated and rolled out. There's also the overlayService in v8 which is probably what you want, i think editorService is more to manage infinite editors (IIRC). I might suggest having a look at the code in the v8 source code to see how we are doing certain things, that's probably the easiest way currently to figure out how everything is put together. Thanks for your patience!

**Comment by Shazwazza** [comment]
For further information, please reach out to the community on https://our.umbraco.com/ for assistance

**Comment by Questo** [comment]
Thanks for the help @Shazwazza and @abjerner . I had already made posts about this at our.umbraco but got nothing.

I'll use the overlayservice instead, I downloaded the source code and will look at that for the time being.
If you ask me, this should get a bump in prio, it's annoying having to scour the internet only to find out you have to download the source code to check. 

To clarify, I don't mind looking at the source code, but the very least you can do is add something on the official docs that lets people know that they should look at the source code instead.

Sorry if I sound bitter!

Have a nice day!

**Comment by Shazwazza** [comment]
I totally understand, we are working on it! There's a very large amount of documentation that needs writing/updating/etc... we will be rolling out new api docs hopefully within the next few weeks.
