### ISSUE TITLE
Healthchecks that allow you to provide a value to fix the issue only allow values in the form of email addresses

### ISSUE THREAD

**Issue by alanmac** [umbraco/Umbraco-CMS#5110]
Bringing this across from the [old issue tracker](https://issues.umbraco.org/issue/U4-10004) where a PR was already logged against it: https://github.com/umbraco/Umbraco-CMS/pull/1994

If you look [here](https://github.com/umbraco/Umbraco-CMS/blob/91c52cffc8b7c70dc956f6c6610460be2d1adc51/src/Umbraco.Web.UI.Client/src/views/dashboard/settings/healthcheck.html#L119) you can see the field where you enter the correct value in has a val-email attribute. Which is correct for the core health check for "Notification Email Settings", as that should be an email. But validation for an email should only be for that check, not for all.

Expect it's not been noted before as I believe the "Notification Email Settings" check is the only one in core that allows you to provide a "fix" value.

See https://our.umbraco.org/forum/extending-umbraco-and-using-the-api/86270-health-check-fix-button-is-disabled# for more details.

### Bug summary

The current custom value input for a healthcheck only validates against an input being an email address.

### Specifics

Umbraco Version: 7.14

### Steps to reproduce

Try creating a healthcheck that allows setting a custom value. 

### Expected result

That I would be able to set a custom value

### Actual result

The current codebase validates against any custom value needing to be an email address.

**Comment by Shazwazza** [comment]
PR https://github.com/umbraco/Umbraco-CMS/pull/1994

**Comment by AndyButland** [comment]
Created a new PR for this targeting V8: #5557
