### ISSUE TITLE
Implement an alt. media cache for v7

### ISSUE THREAD

**Issue by zpqrtbnk** [umbraco/Umbraco-CMS#5115]
See conclusions of spike 290:
* Create a new media cache that utilizes cmsContentXml table which means for media items, a DB hit will be incurred, but we can cache this single hit which means that media is cached only for what is requested. We could also have a sliding expiration for it too as to try to keep mem consumption down.
* We should make this the default implementation but have a config switched to revert back to the old Lucene way just in case.

And comments: maybe we want to also background-load all media to avoid tons of SQL queries

This should be implemented and benchkmarked...

**Comment by nul800sebastiaan** [comment]
I'll close this one as we're not putting any new features into v7 any more.
