### ISSUE TITLE
V8: Bulk move members don't make sense

### ISSUE THREAD

**Issue by bergmania** [umbraco/Umbraco-CMS#5124]
Right now, it seems to be possible to move members in the list view of members.

![image](https://user-images.githubusercontent.com/1561480/55404611-93ffab00-5558-11e9-925d-1e01fa8de94e.png)

The functionality doesn't work, but the reel issue is that the move functionality is visible in the list view selection.

**Comment by kjac** [comment]
@bergmania true! The obvious workaround of course is to disable bulk move on the list view datatype, but... it shouldn't be possible in the first place!

PR incoming 😄

**Comment by kjac** [comment]
PR in #5125

**Comment by zpqrtbnk** [comment]
note: code merged into `v8/dev` and picked into `v8/8.0`
