### ISSUE TITLE
V8: Value is null when using a Single Media Picker

### ISSUE THREAD

**Issue by DanielToft** [umbraco/Umbraco-CMS#5127]
When having a content type with a Single Media Picker, the value is null when trying to receive it from the cache.

Reproduction
------------

Having a Umbraco.MediaPicker with the configuration:
"Pick multiple items": false
"Pick only images": true
"Disable folder select": true

### Expected result
Returning Image/IPublishedContent from the cache

### Actual result
Null is returned

**Comment by Shazwazza** [comment]
I'm assuming you have picked an image ? Or is it just returning null since there's nothing picked? (sorry for the naive question but just want to make sure)

**Comment by DanielToft** [comment]
Hi @Shazwazza 

Yes, I had picked an image. 

I found out, I was doing it wrong. I was trying to get a single image with  Model.Value<IEnumerable<IPublishedContent>>("image") and not  Model.Value<IPublishedContent>("image").

Sorry for the inconvenience!
