### ISSUE TITLE
V8: Improve visibility of focus states for the main section header 

### ISSUE THREAD

**Issue by MMasey** [umbraco/Umbraco-CMS#5129]
At the moment the current focus state when tabbing through the main section header is quite hard to see unless you are really looking for it.

![image](https://user-images.githubusercontent.com/6573613/55427366-c2907c80-557e-11e9-8a5e-693f81ab9e4d.png)

I suggest that the focus state is update to look something like so to help give a stronger visual representation from an accessibility point of view, and as an improvement for keyboard power users.

![image](https://user-images.githubusercontent.com/6573613/55427591-36cb2000-557f-11e9-8d6a-17f5214a6db5.png)

And additional improvement could be made to the way underline is displayed on the active section. The current css animated the `top` property. Changing this to use `transform: translateY(xx)` could improve the performance of this.

**Comment by nielslyngsoe** [comment]
PR https://github.com/umbraco/Umbraco-CMS/pull/5157

**Comment by MMasey** [comment]
Nice one @nielslyngsoe. Shall I close this PR in preference to yours? #5139 🙂
