### ISSUE TITLE
V8: Return to starting focus when closing the search using the ESC key

### ISSUE THREAD

**Issue by MMasey** [umbraco/Umbraco-CMS#5131]
At the moment, when the toggle search button (found in the top navigation bar) is clicked the search overlay appears, but when it is then closed using the `ESC` key, the persons focus state is sent back to the top of the DOM, meaning they have to tab back through the initial navigation to get back to the point of opening the search.

![image](https://user-images.githubusercontent.com/6573613/55432085-f1602000-5589-11e9-9fd0-549021cc0a5d.png)

Would it be a better experience if this took the person either back to the toggle search overlay button so they don't have to repeat a load of steps to get back to where they were?

**Comment by nielslyngsoe** [comment]
Thanks for notifying us.
I think this makes very good sense, feel free to implement if you have a solution up your sleeves. :-)

**Comment by nielslyngsoe** [comment]
I'm making a PR for this now.

**Comment by MMasey** [comment]
> I'm making a PR for this now.

Awesome, thanks @nielslyngsoe, my bank holiday weekend plans left me to busy to jump in on this so I appreciate it 😄

**Comment by nielslyngsoe** [comment]
No worries, not your responsibility ;-) but always very appreciated.

Its was a bit more tricky that I though, but captured a few other things in the making.

PR https://github.com/umbraco/Umbraco-CMS/pull/5412
