### ISSUE TITLE
UmbracoMultiUrlPicker: dialog closes abruptly 

### ISSUE THREAD

**Issue by shearer3000** [umbraco/Umbraco-CMS#5132]
A pre-existing bug with RJP.UmbracoMultiUrlPicker (version 2.2.1, umbraco 7.13.2) :

Action: Open RJP dialog window, then right-click and drag the mouse (from right to left) to select text within field.

Result: entire dialog window closes. 

Expected result: dialog stays open and the text within a field highlights for selection.

NB Multi Url Picker is available as a built-in property editor in Umbraco 7.14+ and 8.0+, this ticket is to fix this issue in these cores.

**Comment by Shazwazza** [comment]
Thanks for reporting, for now I've marked up for grabs to see if anyone from the community can assist

**Comment by Myster** [comment]
I have noticed this too, it is not limited to RJP picker.
It appears the determining factor is where the mouse-up occurs.
If it is within the pane then it is ok, if it's outside the pane it closes.

My suggestion is mousedown (or mouse click) outside the pane should close it, not mouse up.

**Comment by kjac** [comment]
Isn't this a duplicate of #4934?

**Comment by shearer3000** [comment]
hi - yes it reads very much that way.

**Comment by Shazwazza** [comment]
So shall i close this one then? (just want to be sure!)

**Comment by shearer3000** [comment]
yes please (sorry for dup)
I'll add this as a test case on the existing ticket.

**Comment by mjbarlow** [comment]
Can this be reopened, as far as I can see they are separate issues.
