### ISSUE TITLE
V7.14 - MNTP filter by document type not working

### ISSUE THREAD

**Issue by RicCareyBrace** [umbraco/Umbraco-CMS#5137]
Hi,

I have added two document type alias' into the multi-node tree picker data-type on Umbraco 7.14.0, and from the content section, an editor can still select nodes which are not of the specified type. The editor can then save and publish the document without issue. 

Please see below config:

![image](https://user-images.githubusercontent.com/48764967/55469571-ac75d100-55fd-11e9-942f-325faaeef823.png)

The data-type is then used within a document within Nested Content.

Expected outcome, validation should stop the user from selecting items, not of the desired type. 

Thanks
Ric

**Comment by RicCareyBrace** [comment]
Further to this - I have noticed the actual issue. 

When the MNTP is opened and it sometimes expands to the current page, the validation does not kick in. However, if you then close all expanded nodes within the fly out menu, and then rexpand them - the validation kicks in.

**Comment by RicCareyBrace** [comment]
Sorry, further again - if you select a node as the "start node" say the homepage - then the validation will kick in as expected.

**Comment by Shazwazza** [comment]
Sound like an an annoying issue! For now have marked up for grabs to see if any community members might be able to assist with this one. Thanks for reporting!

**Comment by RicCareyBrace** [comment]
Cheers @Shazwazza

**Comment by kjac** [comment]
I've tracked this one down to the changes made in 66b0d4e3 ... will submit a fix.

**Comment by kjac** [comment]
PR in #5199
