### ISSUE TITLE
Hide grid reorder when scrolling to end of grid content

### ISSUE THREAD

**Issue by bjarnef** [umbraco/Umbraco-CMS#5147]
By default the grid reorder is positioned static, but get sticky (fixed) when its position reach the bottom of the header. However you can have several properties after the grid content and when scrolling futher down the page the reorder bar remain sticky. Instead it should be hidden when the bottom of the grid content reach the bottom of header.

![image](https://user-images.githubusercontent.com/2919859/55513027-f80f9580-5664-11e9-9098-ad5b8a417100.png)

![image](https://user-images.githubusercontent.com/2919859/55513032-02ca2a80-5665-11e9-87df-6956a60fae21.png)

Here is an example where the sticky element (in this case a sidebar) moves up, when it reach the footer. https://abouolia.github.io/sticky-sidebar/

**Comment by nathanwoulfe** [comment]
I'm looking at this now - can't see any reason (yet) why this still needs to be implemented as a javascript solution, when browsers now happily support position:sticky...

**Comment by bjarnef** [comment]
@nathanwoulfe support for `position:sticky` is still a bit limited and only partial supported in some browsers. https://caniuse.com/#feat=css-sticky

**Comment by nathanwoulfe** [comment]
@bjarnef true, but v8 browser requirement is FF/Chrome/Safari/Edge latest, so should be fine to use position:sticky. Pinging @nielslyngsoe for his thoughts.

**Comment by bjarnef** [comment]
@nathanwoulfe yes, and I think Umbraco v8 has dropped support for IE11.

**Comment by nielslyngsoe** [comment]
@nathanwoulfe @bjarnef as long as you are still able to somehow do your work in IE11, then I think it's fine. We do not need to deliver a good experience on IE11.

I guess the consequence here is that the bar doesn't get sticky, but you can still scroll up to use the reorder button. Fine with me!
