### ISSUE TITLE
V8: templates created through "Create matching template" does not use ModelsBuilder

### ISSUE THREAD

**Issue by nielslyngsoe** [umbraco/Umbraco-CMS#5152]
Reproduce:
Create a documentType without a template and then choose to "Create matching template" in the template tab.

The template generated will not be using models builder.

DocumentTypes created with a template does get ModelBuilder.

Screenshot of "Create matching template"-button.
![image](https://user-images.githubusercontent.com/6791648/55544323-1dcf8580-56cb-11e9-8589-412364660a4d.png)

**Comment by kjac** [comment]
I've done a bit of digging on this one. Seems doable with a bit of a rewrite... I'll push a PR later today, if all goes according to plan.

**Comment by kjac** [comment]
PR in #5178
