### ISSUE TITLE
V8: Editing a DataType in infinity editing does not layout correctly

### ISSUE THREAD

**Issue by nielslyngsoe** [umbraco/Umbraco-CMS#5154]
Editing a DataType in infinity editing does not layout the same way as editing directly under settings.

I would like the Label and Description to stay in a left column, making the inputs top align with the label.

Infinity editing:
![image](https://user-images.githubusercontent.com/6791648/55550001-760c8480-56d7-11e9-9f5c-b6a47c906768.png)

How it should look and how it looks when editing a DataType from settings:
![image](https://user-images.githubusercontent.com/6791648/55550064-a6542300-56d7-11e9-87f1-9bd5d0eebf6d.png)

**Comment by kjac** [comment]
PR in #5194
