### ISSUE TITLE
Model.Content should be Model

### ISSUE THREAD

**Issue by VilladsClaes** [umbraco/Umbraco-CMS#5155]
When inserting a partial view from snippet and choosing Navigation, the Model.Content should be edited to Model

@*Menuen*@
<ul>
    
        
    <li class='@Model.Id == root.Id ? "active" : null'>
        <a  href="@root.Url">Link til @root.Name</a>
    </li>
    @foreach(var side in root.Children.Where(x => x.IsVisible()).ToArray())
    {
        <li class='@(side.IsAncestorOrSelf(Model) ? "active" : null)'>
            <a href="@side.Url">@side.Name</a>
        </li>
    }
</ul>

**Comment by Shazwazza** [comment]
That should be an easy fix! I'll mark up for grabs and see if anyone picks it up

**Comment by Shazwazza** [comment]
I assume we're talking about v8 here :)

**Comment by kjac** [comment]
Nice one... PR in #5164
