### ISSUE TITLE
v8: DoNotCloneAttribute should be public

### ISSUE THREAD

**Issue by mattbrailsford** [umbraco/Umbraco-CMS#5160]
With Umbraco there is an interface `IDeepCloneable` to handle deep cloning objects. In addition, there is a useful helper `DeepCloneHelper` which can help deep clone all reference properties of an object without having to handle each one explicitly. 

In order to have finer control of what actually gets deep cloned, within the `DeepCloneHelper` it does a few checks and one of those is to look for a `DoNotCloneAttribute` which can be used to mark a property as non cloneable. Unfortunately, the `DoNotCloneAttribute` is marked as internal and so 3rd parties, whilst they can use the `DeepCloneHelper` (as it's public) they can't use the `DoNotCloneAttribute` which is needed to control the helper further.

I believe `DoNotCloneAttribute` should be made public.

**Comment by Shazwazza** [comment]
have marked up for grabs if you or anyone else wants to create a PR

**Comment by kjac** [comment]
Right... might as well strike this one off the issue list 😄 PR in #5193
