### ISSUE TITLE
Trying to access Permissions on a node throws an exception

### ISSUE THREAD

**Issue by clausjensen** [umbraco/Umbraco-CMS#5171]
When trying to access the permissions dialog on a node, an exception is thrown.

**Comment by kjac** [comment]
Nice one 👍 it's a mapping issue; I'll push a fix momentarily.

**Comment by kjac** [comment]
PR in #5176

**Comment by zpqrtbnk** [comment]
I have merged the PR in `v8/dev` but need to change a comment (see comment in the PR) + merge it into `v8/8.0` as it targets 8.0.2. Hence, have reopened the issue.

**Comment by zpqrtbnk** [comment]
Silly me, this cannot target 8.0.2 since mappings are 8.1.0 ;-) closing.
