### ISSUE TITLE
V8 .Registerfor<TService,TTarget>(); Registers Service as target

### ISSUE THREAD

**Issue by Repulp** [umbraco/Umbraco-CMS#5179]
Description:
composition.RegisterFor<TService, TTarget>(); registers the service as target. 
Seems to be a bug in .Core.LightinjectContainer.cs on line 182. where typeof(TService) is sent in as implementationType.
 
https://github.com/umbraco/Umbraco-CMS/blob/853087a75044b814df458457dc9a1f778cc89749/src/Umbraco.Core/Composing/LightInject/LightInjectContainer.cs

Resulting in TService is trying to resolve for itself.

Reproduction:

New solution with UmbracoCms nuget installed (verision 8.0.1).
Create a service to be resolved.
Create class implementing IUserComposer.

use composition.RegisterFor<YourServiceInterface,YourServiceImplementation>();

### Expected result

When resolving for "YourServiceInterface" i get a instance of "YourServiceImplementation" to use.

### Actual result

It fails and you get nothing. 
Complains about not having a public constructor.

**Comment by zpqrtbnk** [comment]
`RegisterFor` is meant to be used with `GetInstanceFor`. So if I `RegisterFor<TService, TTarget>(type)`, then `GetInstanceFor<TService, TTarget>()` will get me an instance of `type`. The idea is that I could
~~~~
RegisterFor<TService, TTarget1>(type1);
RegisterFor<TService, TTarget2>(type2);
~~~~
and each target class could get an implementation of `TService`, and one would get a `type1` instance while the other would get a `type2` instance. This is somehow explained in the comments in [IRegister](https://github.com/umbraco/Umbraco-CMS/blob/v8/dev/src/Umbraco.Core/Composing/IRegister.cs).

When you write
~~~~
composition.RegisterFor<YourServiceInterface,YourServiceImplementation>();
~~~~
I don't think that's what you want. Registering an implementation of a service is done via:
~~~~
composition.Register<YourServiceInterface, YourServiceImplementation>();
~~~~
Which is defined as an extension method in [RegisterExtensions](https://github.com/umbraco/Umbraco-CMS/blob/v8/dev/src/Umbraco.Core/RegisterExtensions.cs).

Unless you *really* want targeted services, I believe you don't want to use `RegisterFor` at all.

Making sense?

**Comment by Repulp** [comment]
Oh.. yes, it seems ive made a fool out of myself. 
Sorry for the trouble and thanks for the help :).

**Comment by zpqrtbnk** [comment]
You haven't made a fool out of yourself, you've identified a point where we should be clearer + have more documentation. Many thanks!
