### ISSUE TITLE
V8: Content doesn't save

### ISSUE THREAD

**Issue by kjac** [umbraco/Umbraco-CMS#5183]
Likely connected to the mapper redo... on vLatest content simply doesn't save. This affects both variant and invariant content:

![nothing-is-saving](https://user-images.githubusercontent.com/7405322/55682745-d7329300-5937-11e9-8136-0836a0a9c763.gif)

I'll dig into it later and report my findings here.

**Comment by kjac** [comment]
I have identified the problem... will test some more tonight and hopefully push a fix.

**Comment by kjac** [comment]
PR in #5186

**Comment by zpqrtbnk** [comment]
My feeling is... mapping with `source.Properties.Select(context.Map<T>(...))` is to error-prone if you forget to `.ToArray()` - should be `context.Map<IEnumerable<T>>(source.Properties)` - which our mapper already supports - working on it now

**Comment by kjac** [comment]
Oh awesome 👍

**Comment by zpqrtbnk** [comment]
OK, should be even more explicit with 
~~~~
List<TTargetElement> content.MapEnumerable<TSourceElement, TTargetElement>(IEnumerable<TSourceElement> source)
~~~~

Now considering whether the mapper should keep infering `IEnumerable<T>` mapping, or just require that one uses `MapEnumerable`...

**Comment by kjac** [comment]
I think people will look to existing mapping profiles for inspiration/examples on how to do a new one. So if the existing profiles all use `MapEnumerable`, chances are new ones will too.

**Comment by zpqrtbnk** [comment]
Want to have a look at #5192 and tell me what you think? I think it is more explicit, less risk of confusion.

Now I am wondering whether I should unplug magic-enumerable support from the mapper (ie, if your define a map from A to B, it knows how to map from IEnumerable<A> to IEnumerable<B>) - it's just... I need to figure out whether we depend on it ;-)

**Comment by kjac** [comment]
I like the stuff in #5192 😄 

I think it's a sweet touch that the mapper can figure out how to map IEnumerables on its own. As long as it evaluates the result immediately with `ToList()` or similiar I see no reason to remove it... As long as it stays there in future versions, of course - we definitively don't want backwards compatibility issues in the mapping layer.

**Comment by zpqrtbnk** [comment]
Yes when mapping enumerables, the mapper already did the equivalent of `ToList`  ...  so ok, going to leave the feature there. Will review again and merged later on today. Meaning I'm not going to merge #5186 - but thanks anyways !!

**Comment by kjac** [comment]
Of course 😀 anytime!

**Comment by zpqrtbnk** [comment]
review: everything should work

**Comment by kjac** [comment]
If it's merged I'll test it tonight 👍
