### ISSUE TITLE
v7: Replace the old checkbox markup with the new umb-checkbox directive

### ISSUE THREAD

**Issue by BatJan** [umbraco/Umbraco-CMS#5185]
There are multiple places where the old default browser checkbox is being used - To align the UI and make the checkboxes appear nicer looking I suggest to replace the old checkboxes using the new and shiny umb-checkbox directive.

I'll create a PR for this shortly.

**Comment by Shazwazza** [comment]
Sounds good!

**Comment by nul800sebastiaan** [comment]
I'll close this one in favor of the v8 issues linked above. 👍
