### ISSUE TITLE
v8 - Server side validation is not cleared on invariant properties on non default lang

### ISSUE THREAD

**Issue by Shazwazza** [umbraco/Umbraco-CMS#5190]
Server side validation is not cleared on invariant properties on non-default languages even when the invariant property is changed on the default language which means that the user won't be able to submit the non-default language again

relates to #4884 (see comment Server side validation is not cleared on invariant properties on non-default languages even when the invariant property is changed on the default language which means that the user won't be able to submit the non-default language again)

The problem will boil down to val-property (IIRC). 

To replicate the issue:

* Have 2x languages (neither are mandatory)
* Have 1x variant doc type 
* Have 1x invariant property of type "text field" (not "textbox" aka. textstring) that is mandatory
* Have 1x variant property of type "text field" (not "textbox" aka. textstring) that is mandatory
* Create and publish a new/valid content item (enter data in all fields)
* Edit this content item's invariant property on the default lang, remove the value, switch to the non-default language, Save and publish both languages
* ... now you will end up with a property error for the invariant property which you cannot edit on the non-default language
* Switch to the default language, add a value for the field, this will remove the property validation warning
* Switch to the non-default language, the property validation warning will remain there and you cannot edit the field, so it cannot be removed.

**Comment by nielslyngsoe** [comment]
Hi @Shazwazza 

My immediate solution is to make sure that we only validate fields that are enabled or in other words and in the scenario that would be: "if a field is invariant then only validate it on the default language".

Seems like the way to go for me, but the server does validate all fields on server-side. Which seems wrong to me, maybe there is something I'm not seeing?

I hoped you could help me out disabling server-side-validation for invariant properties on other languages than the default one.

I even guess that we wouldn't be saving invariant properties on non-default-languages, thereby it wouldn't make sense to validate... let me know if I'm mistaken.

Draft PR: https://github.com/umbraco/Umbraco-CMS/pull/5208

**Comment by Shazwazza** [comment]
@nielslyngsoe I'll have a look tomorrow for you but just to give you some context on what might be happening (if i remember all of these silly rules correctly):

* Invariant properties are validated on the server side for the default language
* Invariant properties are validated on the server side for a non-default language IF there is currently no published version of the content (i.e. If you have 2x non mandatory languages and you have a content item that has never been published, and then you save and publish the non-default language ... we must validate the invariant property)

There could certainly be a situation that is overlooked or not behaving correctly so lets sync up tomorrow.

**Comment by nielslyngsoe** [comment]
@Shazwazza 

First one sounds correct to me, but I´m not sure thats whats happening...

The Second one sounds interesting, I think it makes sense, but then we might have a problem with the way the validation-feedback is served.

It would be nice if the feedback could correspond to the properties on the default-language, so the feedback doesn't get display on the non-default-language, cause here you cant change/type it in....

**Comment by Shazwazza** [comment]
We do have a problem with the way validation feedback is served, especially for creating new content - but that's a different issue (already logged). Lets chat through some of this today.

**Comment by Shazwazza** [comment]
oops, didn't mean to close this

**Comment by Shazwazza** [comment]
When we fix this, we'll then have to look into this other issue which has to do with creating content with validation messages and redirects: https://github.com/umbraco/Umbraco-CMS/issues/5156 
will see if we can add this next sprint
