### ISSUE TITLE
v8: Multinode Treepicker with filter - Angular error "Cannot read property 'toLowerCase'"

### ISSUE THREAD

**Issue by pralthom** [umbraco/Umbraco-CMS#5191]
Hi,

When using the mutlinode Treepicker, I'm getting an error in the browser console

```
angular.js?cdv=667444188:15536 TypeError: Cannot read property 'toLowerCase' of undefined
    at umbraco.controllers.js?cdv=667444188:3552
    at Object.forEach (angular.js?cdv=667444188:387)
    at performFiltering (umbraco.controllers.js?cdv=667444188:3551)
    at nodeExpandedHandler (umbraco.controllers.js?cdv=667444188:3422)
    at umbraco.directives.js?cdv=667444188:8400
    at Function.h.each.h.forEach (underscore-min.js?cdv=667444188:5)
    at emitEvent (umbraco.directives.js?cdv=667444188:8399)
    at umbraco.directives.js?cdv=667444188:8541
    at processQueue (angular.js?cdv=667444188:17914)
    at angular.js?cdv=667444188:17962 "Possibly unhandled rejection: {}"
```

Reproduction
------------

Add a multinode treepicker to a document type with the following options:
 - Node type: Content
 - Allow item of type: AliasOfADocumentType
 - Minimum number of items: 0
 - Maximum number of items: 0
 - Show open button: false

Then go to a node with this document type, click on the "Add" button and open the browser debug console.

### Bug summary

The error seems to happen in the umbraco.controllers.js file at the line 3552.

`value.metaData.contentType` is null when the node is not matching the content type we defined earlier in the multinode treepicker options.

### Expected result

No angular error in the debug console

**Comment by kjac** [comment]
I can reproduce this.. I'll have a look at it.

**Comment by kjac** [comment]
Oh shoot... I thought it felt familiar 😄 it's already fixed in #4960

**Comment by pralthom** [comment]
Great, thanks for the quick answer.
Do you know when the fix will be released in production?

**Comment by kjac** [comment]
@pralthom it may be in 8.0.1 already, not really sure about that.

**Comment by pralthom** [comment]
I'm running 8.0.1 and the bug it still there. I guess I'll have to wait for 8.0.2

**Comment by Shazwazza** [comment]
#4960 hasn't been merged or marked as fixed so there's no release for it yet. We are hoping to release 8.0.2 next week, there might be a chance that #4960 makes it into the build as I've moved it into the current sprint, else it may need to wait until 8.0.3

**Comment by pralthom** [comment]
Thank you @Shazwazza for your detailed answer.
I hope it's going to make it into the build for the 8.0.2 as I use the Multinode Treepicker in a property editor I developed and it's crashing when the code is build for release.

Have a great day!
