### ISSUE TITLE
Uploaded image height / width is incorrectly set to 200 px

### ISSUE THREAD

**Issue by Luksor** [umbraco/Umbraco-CMS#5195]
When uploading certain images the width and height is incorrectly set to 200px.

Reproduction
------------

### Bug summary

The resolution of certain images is incorrectly set after the image is uploaded. Related issue: #3990

### Specifics

Tested using Umbraco 7.14.0.
I'm using this image to reproduce the issue:
https://user-images.githubusercontent.com/5837521/52138261-915e0380-2644-11e9-927e-fe05ef73fa1e.jpg

### Steps to reproduce

Upload the attached image to the media library.

### Expected result

The image resolution should be set as 1920px x 1296px.

### Actual result

The image resolution is set to 200px x 200px.

**Comment by kjac** [comment]
PR in #5200

**Comment by nul800sebastiaan** [comment]
Fixed in https://github.com/umbraco/Umbraco-CMS/pull/5200 and https://github.com/umbraco/Umbraco-CMS/pull/5201
