### ISSUE TITLE
V8: Media picker does not show file names

### ISSUE THREAD

**Issue by alicia123456** [umbraco/Umbraco-CMS#5198]
A brief description of the issue goes here.

When adding a document with the Media picker, only the file icons show ... not the filenames. I have to hover over each icon to see the filename to find the one I want. 

Reproduction
------------

If you're filing a bug, please describe how to reproduce it. Include as much
relevant information as possible, such as:

### Bug summary
 Media file names do not appear in Media Picker until you hover over the icon

### Specifics

I'm working in the v8.0.1 Sample Site on my local PC. Windows 10. Chrome.
This is similar to 
[https://github.com/umbraco/Umbraco-CMS/issues/4494](url)
only it's for the actual files, not the folders.

### Steps to reproduce

- Create a document type "Resources"
- Add a property - Media picker - configure for "Pick multiple items"
- Create a page using document type "Resources"
- Click the + sign to add a document
- Navigate folders to the correct one
- pdf icons display, but not the actual file names

### Expected result

- An alphabetical list of file names, or at least a file name immediately viewable on each icon

### Actual result

Filenames can't be seen until I hover over EACH file, individually, making it very tedious to find the file that I want.
![Filenames_not_Visible](https://user-images.githubusercontent.com/49405580/55736949-54224300-59f2-11e9-87fd-827dbf016c79.png)

**Comment by kjac** [comment]
This is making so much sense. I did the fix for #4504, I'll have a look at this one as well.

**Comment by kjac** [comment]
The issue also applied to the folder view in the media library... PR in #5203

**Comment by kjac** [comment]
Oh and thanks for reporting, @alicia123456 👍

**Comment by nul800sebastiaan** [comment]
Not sure why this was closed already, anyway: fixed in https://github.com/umbraco/Umbraco-CMS/pull/5203 - great feedback ! 👍
