### ISSUE TITLE
v8: Add varchar(max) support

### ISSUE THREAD

**Issue by mattbrailsford** [umbraco/Umbraco-CMS#5204]
We need to be able to support NvarcharMax for SQL server in Umbraco. Currently there isn't any support for this in the code, only NText which is deprecated. 

We need to somehow support NvarcharMax but also keeping in mind that however this works would need to fallback to NText for SqlCe. 

The migration syntax would need to support NvarcharMax along with DTO attributes.

## Original post:

In v8 there is an ability to create DB tables using a builder interface. As part of this you can do things like define columns and their types. These then get built into a SQL statement to run on the various database types.

There is currently an ability to define columns as strings and provide an int size, such as

    Create.Table("myTable").WithColumn("myColumn").AsString(255)

This will then get converted into a SQL statement that creates a column of type `nvarchar(255)`. 

Ones thing missing though is an ability to create a string column of type `nvarchar(max)` as max is clearly not an int value which the .AsString method requires.

We could really do with an additional means of defining a string value with it's size set to `max`

**Comment by mattbrailsford** [comment]
If I'm understanding the code right, I think there is a workaround for now and that is to use the `.AsCustom` method with a value of `.AsCustom("nvarchar(max)")`

**Comment by Shazwazza** [comment]
In v8, seeing as though we've dropped support for MySql it means we only need to have some hacks in place for SqlCe. SqlCe does not support NVarchar max and NText is deprecated on SQL server. 

Ideally we would use nvarchar max columns in Sqlserver and only use ntext columns in sqlce

https://stackoverflow.com/questions/2133946/nvarcharmax-vs-ntext

ntext will actually be removed from sql server at some stage https://docs.microsoft.com/en-us/sql/t-sql/data-types/ntext-text-and-image-transact-sql?view=sql-server-2017

**Comment by Shazwazza** [comment]
So keep in mind if you are using nvarchar max - you will need to support ntext as well if you are doing this from a package perspective else it won't work with sqlce

**Comment by mattbrailsford** [comment]
@Shazwazza good to know. Thanks for the extra info :+1:

**Comment by JoseMarcenaro** [comment]
@Shazwazza - considering your previous comment about varchar(max)

How can we specify a nvarchar(max) in the table schema for a Migration?
Would it be possible to add a "NVarcharMax" to the SpecialDbType enum? Or there is a different way to do it?

I tried [Length(-1)] but it throws a SQL exception.

**Comment by Shazwazza** [comment]
I have no idea if it is possible to make this work as it is today, i doubt it since there is literally no code in Umbraco regarding NVarcharMax. I don't know if matt's suggestion of .AsCustom("nvarchar(max)") works, but i doubt it since we would still be missing DTO attributes to support this. 

This task needs to be extended to simply: Add NVarcharMax support , i'll change the title.

**Comment by nul800sebastiaan** [comment]
Fixed in https://github.com/umbraco/Umbraco-CMS/pull/8031
