### ISSUE TITLE
Getting runtime error when calling GetGridHtml outside view

### ISSUE THREAD

**Issue by GarriHov** [umbraco/Umbraco-CMS#5205]
Hi,

In order to access grid html content outside razor view have tried following workaround to create fake view based HttpHelper:

```
private static HtmlHelper CreateHtmlHelper(object model)
        {
            var cc = new ControllerContext
            {
                RequestContext = UmbracoContext.Current.HttpContext.Request.RequestContext
            };
            var viewContext = new ViewContext(cc, new FakeView(), new ViewDataDictionary(model), new TempDataDictionary(), new StringWriter());
            var htmlHelper = new HtmlHelper(viewContext, new ViewPage());
            return htmlHelper;
        }
```
Now, I'm getting this error "The RouteData must contain an item named 'controller' with a non-empty string value".

I've also tried to add controller routedata in view context, but still getting same error.

Basically, this issue is related to the following topics:
https://issues.umbraco.org/issue/U4-6209
https://our.umbraco.com/forum/developers/api-questions/74546-how-to-call-getgridhtml-with-htmlhelper

Could you please advise how to resolve exception or maybe there are others way to retrieve grid control value? 

Thanks!

**Comment by nul800sebastiaan** [comment]
Currently this is not supported.

I've marked this as "Up for grabs" so that you or someone else coming along could create a pull request for it.

**Comment by nul800sebastiaan** [comment]
This issue has been in the `up for grabs` state for quite a while now and it seems nobody is ready to pick this one up.

For now we'll close this issue to prevent the list of `up for grabs` from becoming very stale. We're happy to re-open it if someone still thinks it's good to work on this.

If anyone is about to pick this issue up to fix it, make sure to test first if you can reproduce the problem in the latest version before you start to work on it.

Thanks!
Sebastiaan on behalf of Umbraco HQ.
