### ISSUE TITLE
V8: Umbraco support for AzureAD

### ISSUE THREAD

**Issue by tta-appstract** [umbraco/Umbraco-CMS#5207]
UmbracoCms.IdentityExtensions.AzureActiveDirectory is currently not supported by Umbraco v8.

`Severity	Code	Description	Project	File	Line	Suppression State
Error		Unable to resolve dependencies. 'UmbracoCms.Core 8.0.1' is not compatible with 'UmbracoCms.IdentityExtensions 1.0.1 constraint: UmbracoCms.Core (>= 7.3.0 && < 8.0.0)'.				
`

Will this be supported soon? 

Thank you

**Comment by Shazwazza** [comment]
Hi! The repository you are looking for is here https://github.com/umbraco/UmbracoIdentityExtensions and you can follow along with the currently logged issue here https://github.com/umbraco/UmbracoIdentityExtensions/issues/31
