### ISSUE TITLE
v8 - Remove IsVisible from IPublishedContent

### ISSUE THREAD

**Issue by zpqrtbnk** [umbraco/Umbraco-CMS#5212]
We can remove it from `IPublishedContent` now that we have it on `IPublishedElement` but that is breaking = 8.1 only

**Comment by zpqrtbnk** [comment]
Done with commit e540a4ac2309bfb669ca5982f2ac0ce0e0d19423.

**Comment by dawoe** [comment]
Hi @ReVoid 

You can still use it from IPublishedContent. The IPublishedContent interface implements the IPublishedElement interface.

Dave [Community Pull Request team](https://umbraco.com/blog/introducing-the-new-cpr-team/)

**Comment by ReVoid** [comment]
@dawoe Oh, it is clear now, thanks 😎
