### ISSUE TITLE
Migrate data from Umbraco 7 to Umbraco 8. 

### ISSUE THREAD

**Issue by FyinInc** [umbraco/Umbraco-CMS#5217]
Migrate data from Umbraco 7 to Umbraco 8. 

Reproduction
------------

### Specifics

* Umbraco 7.14.0
* Umbraco 8.0.1
* Base install

### Steps to reproduce

- Install latest Umbraco 7
- Point latest Umbraco 8 to Umbraco 7 database

### Expected result

Database is migrate to Umbraco 8

### Actual result

Installer fails to upgrade the database
[UmbracoTraceLog.DESKTOP-KBCNE0R.20190409.json.txt](https://github.com/umbraco/Umbraco-CMS/files/3061316/UmbracoTraceLog.DESKTOP-KBCNE0R.20190409.json.txt)
![picturemessage_a23vfkdc dqu](https://user-images.githubusercontent.com/6144847/55841380-2cafa100-5aec-11e9-89b1-d2476d2e9f3d.png)
![picturemessage_fblztle2 mrf](https://user-images.githubusercontent.com/6144847/55841388-31745500-5aec-11e9-83d7-f669122964de.png)

**Comment by Shazwazza** [comment]
I think you probably need the version in there, have you tried?

You are not installing a brand new Umbraco site which is when this value is empty. You are upgrading a site so that value will not be empty. I am not sure if that value should be 8.0.0 or if it should be 7.14.0 (or maybe it doesn't even matter). Please try and see what happens.

I'll close this issue for now but feel free to reopen if you have additional info.

**Comment by FyinInc** [comment]
[Umbraco 7 to Umbraco 8 upgrade failure.pdf](https://github.com/umbraco/Umbraco-CMS/files/3109459/Umbraco.7.to.Umbraco.8.upgrade.failure.pdf)

@Shazwazza we did try that before posting. Here are the steps we have tried.

**Comment by FyinInc** [comment]
[Umbraco 7 to Umbraco 8 upgrade failure.pdf](https://github.com/umbraco/Umbraco-CMS/files/3109467/Umbraco.7.to.Umbraco.8.upgrade.failure.pdf)

We had tried that. No luck.

**Comment by zpqrtbnk** [comment]
I am not sure I fully understand what you are trying to do - to upgrade a database from v7 to v8... well yes, you *do* need to configure a connection string in `web.config`, pointing to a v7 database, and you *do* need to configure a version in `web.config`, indicating the v7 site version.

Then, migrating from v7 does not fully work at the moment. First, migrating from 7.14 is not supported, only 7.13 IIRC. And even then, some odd things may happen. We are aware of the situation and plan to fix in a near future.
