### ISSUE TITLE
V8: No linebreaks, invisible completing paragraph tag in "View Source Code" bar in Richtext editor (RTE) in Backcoffice

### ISSUE THREAD

**Issue by ReVoid** [umbraco/Umbraco-CMS#5220]
When you try to view a souce code in richtext editor (RTE), there is no linebreaks depended of current sidebar container size. And, for some reason completing `</p>` tags are invisible while you don't select any text.

![error](https://user-images.githubusercontent.com/12345710/55868311-e1010400-5b8c-11e9-9660-23c1541f695b.gif)

Reproduction
------------

### Specifics

Umbraco 8.0.1

### Steps to reproduce

1. Insert or type a lot of text in RTE, separete it to several paragraps
2. Press "View Source Code"
3. Select whatever text with mouse, you'll see the missing `</p>` tags

### Expected result

1. When sidebar is opens, markup fits the sidebar current width
2. There are completing `</p>` tags in the end of each paragraph.

### Actual result

You see, there are no linebreaks and no completing `</p>` tags

**Comment by nul800sebastiaan** [comment]
That's certainly annoying! It should definitely just only be as wide as the editing panel and not have a horizontal scroll bar. 

I've marked this as "Up for grabs" so that you or someone else coming along could create a pull request for it.

**Comment by kjac** [comment]
PR #5398 covers this

**Comment by nul800sebastiaan** [comment]
Fixed in #5398
