### ISSUE TITLE
NuCache Vanishing Content

### ISSUE THREAD

**Issue by zpqrtbnk** [umbraco/Umbraco-CMS#5222]
There have been reports of NuCache missing some content after a site restart. It had already been reported as #5121, we confirmed an issue with media, fixed it, assumed that was all, and closed. However, some users are reporting issues with *content* too.

**_How can you help?_**

We need to be able to reproduce the issue, in an as simple and small situation as possible. What can help too is:
* the Umbraco logs (ideally, in Debug mode)
* memory dump of the w3wp process while content is missing
* copies of the NuCache db files (in App_Data)

Also, some have reported that they need to hit *Reload* in the NuCache dashboard to fix the situations - and others *Rebuild* - can you always please try *Reload* first? It *should* be enough - and depending on which one is required, the issue would be in totally different places.

**Comment by madsoulswe** [comment]
Replicate it by
1. Install umbraco with startkit.
2. Added a content picker property to the home doctype
2. Go to home and pick something.
3. Go back to settings and rename the property.

Then children of home will be empty. =)

**Comment by FransdeJong** [comment]
I have the problem consistent now for the latest few pushes to live.
I have it narrowed down to adding documenttypes and templates and or changing existing ones.

This is a live site so I can't test to much but I will make a reliable reproduction scenario with a test cloud project this weekend.

@zpqrtbnk Does nucache take the cloud environment into account? The content issue only presents itself on the live environment thus far...

**Comment by zpqrtbnk** [comment]
@madsoulswe Reproduced - excellent, now debugging.

@FransdeJong Don't thing Cloud environments have an impact - more... it could be that documents have not created exactly in the same order on each environment (ie Deploy has its own order). Will know more when I find out what's going on

**Comment by zpqrtbnk** [comment]
Silly issue with cache refresh - PR on its way.

**Comment by zpqrtbnk** [comment]
PR #5240

_**NOTE TO REVIEWERS this is an 8.0.2 fix, please merge the PR and THEN cherry-pick the fix in `v8/8.0`**_

**Comment by FransdeJong** [comment]
@zpqrtbnk do you still want me to check it in a cloud deploy? Or is it the same issue?

**Comment by zpqrtbnk** [comment]
Don't think it is cloud related - OTOH it is related to "making changes to document types" be it via the user interface or deploying - if you can confirm that you were seeing the problem when making changes or deploying, but not in "normal" operations, that'd be great.

**Comment by FransdeJong** [comment]
Yeah, it only happens when I'm changing something on a documenttype so this should be fixed to.

**Comment by zpqrtbnk** [comment]
Cool. Note for reviewers: can close the issue after merging!

**Comment by zpqrtbnk** [comment]
Duh. Let's discuss in #5431.
