### ISSUE TITLE
v8: No way to get culture of node that doesn't vary by culture

### ISSUE THREAD

**Issue by abjerner** [umbraco/Umbraco-CMS#5227]
### Specifics

In both `v8.0.0` and `v8.0.1`, if a given `IPublishedContent` varies by variant, we can get the variants (cultures) via `node.Cultures`. This part works like it should 😄 

However, on the other hand, if I have another `IPublishedContent` that doesn't vary by culture, `node.Cultures` is empty. I haven't found a way to then determine the culture (eg. `CultureInfo` or just the ISO code) from code for an `IPublishedContent` that doesn't vary be culture.

### Steps to reproduce

1. Create a new root node of a type that doesn't vary by culture

2.  Add a domain/hostname to said node and specify a culture (eg. `en-US`)

3. Check the culture in the frontend - eg. by using the snippet below:
  ```
  @inherits Umbraco.Web.Mvc.UmbracoViewPage<IPublishedContent>
  @{

      Layout = null;

      <pre>@Model.Cultures</pre>

      <pre>@Model.Cultures.Count</pre>

      foreach (var culture in Model.Cultures) {
          
          <pre>@culture.Key => @culture.Value.Name => @culture.Value.Date => @culture.Value.Culture => @culture.Value.UrlSegment</pre>

      }

  }
  ```

### Expected result

`node.Cultures` should return a list of `PublishedCultureInfo` matching the culture or cultures of the node, as specified by the configured cultures and host names.

If there are more than one culture, the first one should ideally be the one matching the current `CultureInfo` - as the first one would then be similar to what we got from the `GetCulture` method in Umbraco 7. `GetCulture` in Umbraco 7 seems to fall back to `en-US` if nothing else configured in the node's path.

### Actual result

`node.Cultures` is empty 😱

**Comment by Shazwazza** [comment]
I think this is more just confusion about the APIs. If an `IPublishedContent` object is invariant (does not vary), then it has no cultures. That is expected.

You've assigned a culture to that branch in the back office, but that is the culture the page is being rendered in, it's not the culture of the content item. This is the same as how v7 works (i.e. there is no culture assigned to the content item).

In v8, an invariant node has zero cultures, it doesn't reference a language and it's values don't reference a language, think of it as a 'null' language. A variant node has 1 or more cultures assigned which depends on the languages assigned to the branch. Values are saved against a language reference and not against a 'null' reference. 

I'll close this issue for now but feel free to ask more questions here. Will also tag @zpqrtbnk here to make sure what I'm saying is correct :) and to potentially think of less confusing ways to name or deal with assigned culture values in IPublishedContent.

**Comment by abjerner** [comment]
@Shazwazza thanks for the answer. I figured there was a reason for why it works like it does in Umbraco 8.

However in Umbraco 7, the `GetCulture` method actually does reflect the culture in some way. If the current node I'm calling the method on doesn't have a culture (via cultures and host names), the method will traverse up the path of the node. This also works outside the Umbraco request pipeline - for instance via an API controller.

Say we have an invariant site like this:

- **My Site** (configured with a domain and `da-DK` as culture)
  - **da** (inherits culture from parent node)
  - **en** (configured with `en-US` as culture)

In Umbraco 7 I can call `GetCulture` of any descendant of either **da** or **en**, and it will return the correct `CultureInfo`. I haven't been able to find something similar in Umbraco 8.

Here is a few relevant links to the V7 code base:

- https://github.com/umbraco/Umbraco-CMS/blob/v7/dev/src/Umbraco.Web/PublishedContentExtensions.cs#L2055

- https://github.com/umbraco/Umbraco-CMS/blob/v7/dev/src/Umbraco.Web/Models/ContentExtensions.cs

I've tried to replicate the logic from the `ContentExtensions` class to V8, but it relies heavily on internal code, so I haven't been able to get it to work yet.

**Comment by Shazwazza** [comment]
Hi @abjerner there would be a couple ways to achieve the same thing IIRC. Firstly the thread culture should be set to the culture detected for the route. So like any .NET app you can do either:

` Thread.CurrentThread.CurrentCulture` or `CultureInfo.CurrentCulture`

In v8 we then also have something called a `IVariationContextAccessor` which is the thing that returns the current variation context. This can be injected anywhere and is exposed on `UmbracoContext.VariationContextAccessor` or can be resolved from the singleton pattern (if you need that for some reason) by `Current.VariationContextAccessor`.
