### ISSUE TITLE
V8: Rethink the UX of Media-Picker

### ISSUE THREAD

**Issue by nielslyngsoe** [umbraco/Umbraco-CMS#5228]
We need to re-think the UX of the Media-Picker, in order to provide a simple and intuitive UI.

I think we need to remove the option to open and edit a media-item from the selection-dialog. Instead we should provide a dedicated option to edit the selected-media(s).

This would mean that you need to pick a media-item before you can choose to edit it.

We also need to be aware about media-folders, in situations where you can pick/select a folder, cause then you both need to be able to open the folder and to select it.

Idea and insights are very welcome.

**Comment by PerplexDaniel** [comment]
Probably a bit too radical, but I would love it if Umbraco would unify the media cropper and media picker into 1 editor. Then we can finally have the best of both worlds; re-use images and crops across multiple pages if we want (= media picker), while also being able to finetune the crops for a specific page on the page itself with a nice interface (= media cropper). 

Whether or not an image is saved to the media library could just be a checkbox too, so people could just use it as the current media cropper if they wish to keep it out of the library. It's just not cool we currently have to choose between a nice cropper UI (= media cropper) or reusability / management features (= media picker) when it seems to me they could be integrated and everybody would love it :-)

**Comment by skttl** [comment]
@PerplexDaniel I already did some of that: https://github.com/umbraco/Umbraco-CMS/pull/2946

**Comment by PerplexDaniel** [comment]
@skttl Very nice! Was not aware of that one, though it seems to be targeted at v7 rather than v8. In any event it's cool that there's already work done on this one.

**Comment by skttl** [comment]
I think the ideas outlined by @JeffreyPerplex at Codegarden was great. A combination between Cropper / Media Picker, with the ability to move uploaded images to the media library.

And extensible, so you could add your own mediaproviders like Skyfish, Dropbox etc.

**Comment by johnsonp57** [comment]
It would also be nice if the media picker could be configured to use a custom field as alt text.  When adding a media item through the RTE, it offers the possibility to add alt text, but it would be nice if this field defaulted to a value entered on the media item itself - there aren't too many times when you would want to override this

**Comment by nul800sebastiaan** [comment]
Fixed in https://github.com/umbraco/Umbraco-CMS/pull/5241
