### ISSUE TITLE
v8: ICreateBuilder PrimaryKey should allow non clustered config

### ISSUE THREAD

**Issue by mattbrailsford** [umbraco/Umbraco-CMS#5229]
Currently in the ICreateBuilder if you define a PrimaryKey column it is assumed that it should be clustered if the database supports it, however if you are using GUIDs for your primary key, it's advantageous to set these as non clustered as by their nature, GUIDs are random and so clustering doesn't really help. With that in mind, if you are defining a GUID primary key, it should be possible to configure it as non clustered.

**Comment by kjac** [comment]
Well that was fun! PR in #5261. 

@mattbrailsford could I bother you to test it in your particular scenario?

**Comment by nul800sebastiaan** [comment]
Fixed in https://github.com/umbraco/Umbraco-CMS/pull/5261
