### ISSUE TITLE
v8: Log message should wrap inside container

### ISSUE THREAD

**Issue by bjarnef** [umbraco/Umbraco-CMS#5230]
In Log Viewer the log message doesn't wrap inside the container, e.g. for long media url.

![image](https://user-images.githubusercontent.com/2919859/55901486-b71a0280-5bc9-11e9-9d2b-4d92d304c5d5.png)

**Comment by kjac** [comment]
Tables are terrible with long lines 😆 PR in #5274

**Comment by nul800sebastiaan** [comment]
Fixed in https://github.com/umbraco/Umbraco-CMS/pull/5274
