### ISSUE TITLE
v8: Carets in Tiny MCE toolbar are not vertical center aligned

### ISSUE THREAD

**Issue by bjarnef** [umbraco/Umbraco-CMS#5231]
It seems carets in Tiny MCE toolbar are not vertical center aligned.

![image](https://user-images.githubusercontent.com/2919859/55902709-6bb52380-5bcc-11e9-84b6-6406d39758e7.png)

The skin.min.css sets the following, but `margin-top: 6px;` looks more to be in center.

```
.mce-btn .mce-caret {
    margin-top: 8px;
    margin-left: 0;
}
```

**Comment by Shazwazza** [comment]
Thanks, have marked up for grabs in case you or someone else in the community can help by submitting a PR

**Comment by kjac** [comment]
The carets look fine in the regular RTE; this is a problem isolated in the grid.

![image](https://user-images.githubusercontent.com/7405322/56988428-4c3c6580-6b90-11e9-83f1-d0c9ac56efc0.png)

I've got a fix ready, will submit a PR shortly.

**Comment by kjac** [comment]
PR in #5367
