### ISSUE TITLE
v8: Make tree item annotations clearer

### ISSUE THREAD

**Issue by bjarnef** [umbraco/Umbraco-CMS#5232]
A the moment it is a bit difficult to see the tree item annotations, e.g. when a node is using listview or saved, but not published.

I think it for example could have a background color on these icons to make it clearer.

```
.is-container>.umb-tree-item__inner>.umb-tree-item__annotation:before {
    content: "\e04e";
    color: #2152a3;
    font-size: 10px;
    margin-left: -20px;
    background: #fff;
    line-height: 1;
    border-radius: 50%;
    padding: 2px;
}
```

![image](https://user-images.githubusercontent.com/2919859/55903651-7670b800-5bce-11e9-9a0f-36373b545434.png)

**Comment by Shazwazza** [comment]
Thanks, have marked up for grabs in case you or someone else in the community can help by submitting a PR

**Comment by kjac** [comment]
Well... this wasn't the easiest of styling tasks! Would've been easier if the icons where all the same size 😆 PR in #5271
