### ISSUE TITLE
Error in Backoffice when selecting Order By Document Type in Custom List View

### ISSUE THREAD

**Issue by danEdmonds** [umbraco/Umbraco-CMS#5233]
The following error message is displayed when viewing the page with the list view applied in Umbraco:

> An error occured
> Invalid column name 'contentTypeAlias'.
> Exception Details
> System.Data.SqlClient.SqlException: Invalid column name 'contentTypeAlias'.

![UmbracoListViewErrorMessage](https://user-images.githubusercontent.com/997000/55904411-c1260c00-5b9d-11e9-919b-a8f080196b2a.jpg)

To reproduce this error, add a custom list view to the document type, select the "Document Type" option in the "Columns Displayed" property and then in the "Order By" property. (The page may need to be refreshed between selecting the option in the properties.)

![UmbracoListViewSetup](https://user-images.githubusercontent.com/997000/55904422-c5eac000-5b9d-11e9-9ec5-0113444cf9c2.jpg)

I'm using Umbraco version 7.12.3 in the latest version of Google Chrome and Firefox.

**Comment by Shazwazza** [comment]
Hi, any chance you can test with the latest v7 version to check if it's already been fixed?

**Comment by kjac** [comment]
This is a problem on the latest V7 and also V8. I'm on it 👍

**Comment by kjac** [comment]
PR in #5245

**Comment by kjac** [comment]
PR for V8 in #5250

**Comment by kjac** [comment]
And another V7 PR for media in #5251
