### ISSUE TITLE
V8: Saving a document type in Infinite Editing on a non-created content node results in 404

### ISSUE THREAD

**Issue by hartviglarsen** [umbraco/Umbraco-CMS#5238]
If you open your document type in Infinite Editing on a non-created content node and **Save and Close** you will encounter 404s.

Reproduction
------------
1: Create a document type
2: Create a new node based on that
3: Open the document type in Infinite Editing
4: Save and Close the Infinite Editing overlay

![j6dLDmgCFn](https://user-images.githubusercontent.com/4366314/55959790-c6518c80-5c6b-11e9-9630-0521473aa8bc.gif)

**Comment by kjac** [comment]
I just ran into this as well in vLatest. It's really annoying when constructing new content types.

PR in #6397

**Comment by nul800sebastiaan** [comment]
Fixed in https://github.com/umbraco/Umbraco-CMS/pull/6397
