### ISSUE TITLE
Media library reports image dimensions incorrectly in some cases

### ISSUE THREAD

**Issue by opr** [umbraco/Umbraco-CMS#5239]
If you upload a 1200x800px image at 300dpi, the media library reports the image dimensions as 5072x3620

Reproduction
------------

Upload [this image](http://darwindigital.co/129.jpg) which is 1200x800 and observe the dimensions in the media library.

When changed to 72dpi it is correct, and also at 144dpi the dimensions are also reported correctly.

Can't seem to reproduce this with any other images though!

Thanks

**Comment by kjac** [comment]
Basically this happens because Umbraco manages to read the width and height from the image EXIF metadata. For this particular image, I think the EXIF metadata is wrong... I have tried reproducing with other 300 DPI JPEG images with valid EXIF metadata and I their dimensions are correctly read.

**Comment by opr** [comment]
Thanks Kjac, I suppose saving it as 72dpi re-wrote the EXIF data. I'll let our client know. Thanks again
