### ISSUE TITLE
Format styling does not render in Rich Text Editor

### ISSUE THREAD

**Issue by ckobel-hbside** [umbraco/Umbraco-CMS#5242]
I have created a stylesheet, added it to a data type (rich text editor), and I am able to select it and apply it to text within a rich text editor, but the style does not render within the rich text editor. Example: I have an h1 style, I can apply it to text in the RTE, view the source code and the style is in fact wrapping the text I intended to format, and it displays properly formatted when published, but the style does not render within the rich text editor itself. 

This makes it very confusing for people posting content, because it is not obvious whether they have applied the proper formatting to certain text until after publishing.

[stylesheet](https://imgur.com/a/BXNfnnx) (the styles in this stylesheet are defined within another stylesheet, the implementation is exactly the same as many other umbraco sites (v7 and below, and this implementation works fine))
[datatype](https://imgur.com/a/Rw36Dmy)

This occurs using umbraco v8, on Chrome, Edge, and Safari.
[Here is an example of applying this style and nothing changing within the RTE](https://streamable.com/v1jys)

Notice that the style does not even appear properly within the dropdown.
[See this example of how I believe it should appear and function](https://www.youtube.com/watch?v=0pkKz6YA7aI&feature=youtu.be&t=248)

If I were to publish the above example page, the text I applied the format to would be properly styled, however the style not rendering within an RTE makes it very difficult for those who are posting content regularly to know whether or not they have styled the text properly until after it is published.

**Comment by kjac** [comment]
Hi @ckobel-hbside,

You'll need to add styles to the classes in your stylesheet. Otherwise the RTE has nothing to apply.

The styles are purely for editorial reference and won't be used in your frontend rendering (unless of course you explicitly include the stylesheet in your markup).

**Comment by nul800sebastiaan** [comment]
Yep, as @kjac said, make sure to put the styles in your frontend stylesheet as well. If you have more questions around this @ckobel-hbside them make sure to head on over to the forum at https://our.umbraco.com for some help! 👍
