### ISSUE TITLE
V8: Improve focus states present for the top menu icons (top right hand side)

### ISSUE THREAD

**Issue by MMasey** [umbraco/Umbraco-CMS#5243]
Similar to issue #5129, the focus states for the icons on the top right hand menu are either not clear, or in the case of the user icon, not present.

![image](https://user-images.githubusercontent.com/6573613/56021277-ee3eff80-5d00-11e9-9a6f-32f459d475cd.png)

I order to achieve conformance with Level AA : 2.4.7 accessibility standards, there should be a clear focus area. I think @nielslyngsoe focus state solution in #5157 is probably a good fix for this.

Thanks

**Comment by umbracolegion** [comment]
We're working on it now! Stay tuned.

**Comment by nul800sebastiaan** [comment]
The related PR was closed with a reply from @nielslyngsoe - if you have more / better suggestions then let us know! For now I'll close this one. :)
