### ISSUE TITLE
V8: Chrome with downloads bar present causing images to move in editor pane

### ISSUE THREAD

**Issue by mjbarlow** [umbraco/Umbraco-CMS#5253]
On Google Chrome - Windows - with downloads bar at bottom of screen.  Open the media picker with images in the preview pane that are a certain width. Then moving the mouse - this causes the overflow auto to kick in and out quickly - this flicks the images between rows. This is only occurring when the downloads bar is present at the bottom of the browser window.

Reproduction
------------

### Bug summary

![The issue](https://github.com/mjbarlow/img/blob/master/umbraco-editor-pane-error.gif?raw=true)

- Use the images that I have linked below in my public repo - add them to your media folder. 
- Download something, so that the downloads bar is present at the bottom of your browser window.
- Then use a media picker on a content node  - this opens the editor pane and you can see the issue.

[Images to reproduce](https://github.com/mjbarlow/img)

### Specifics
- Umbraco v8.0.1
- Chrome Version 73.0.3683.103 (Official Build) (64-bit) (with downloads bar at bottom)

**Comment by kjac** [comment]
Really weird looking issue! I can't reproduce it, though:

![media-issue-5253](https://user-images.githubusercontent.com/7405322/56200528-45194180-603f-11e9-87df-5836fed8ef5c.gif)

I can't entirely figure out what should cause the CSS to shift things around like that with random mouse movements. Any chance you have some Chrome extensions running that could cause this? Or in other words, does it happen if you open Umbraco in Incognito?

Could of course also be that something unintentionally fixed it for vLatest 🤔

**Comment by mjbarlow** [comment]
Ok, will look again and see if I can figure out what is causing the issue.

**Comment by nul800sebastiaan** [comment]
I also can't repro, let us know if you have more info!
