### ISSUE TITLE
V8: Copying images in media section between folders doesn't update after completion, images should be removed from current view.

### ISSUE THREAD

**Issue by mjbarlow** [umbraco/Umbraco-CMS#5254]
Copying media in media section between folders doesn't update after completion, images should be removed from current view.

Reproduction
------------

### Bug summary

![Copy image issue](https://raw.githubusercontent.com/mjbarlow/img/master/image-copy-issue.gif)

See above, when moving media between folders, once the operation is complete then the current view should be updated and the images should be removed. Also the selection bar should update with the new state.

**Comment by kjac** [comment]
Thanks for reporting 😀 this was fixed just recently in #5117

**Comment by nul800sebastiaan** [comment]
Duplicated #5117
