### ISSUE TITLE
u 8.0.1 minRequiredPasswordLength in UmbracoMembershipProvider has no effect

### ISSUE THREAD

**Issue by teusch** [umbraco/Umbraco-CMS#5267]
### Bug summary

For our development environment we want a simple small password(less then 10 chars) to login as admin. 
But if I change the minRequiredPasswordLength in te UmbracoMembershipProvider in the web.config  I still get the "Minumum 10 characters" when I try to change the password in the user section. I tried more then 10 and less then 10 , rebuild the site  and stop/started the app_pool  but the message stayed the same
![image](https://user-images.githubusercontent.com/5502583/56120123-d0c29d80-5f6d-11e9-99d3-ecb09a970dde.png)

**Comment by nul800sebastiaan** [comment]
Make sure to add the attribute (`minRequiredPasswordLength="16"`) to the `UsersMembershipProvider`, currently you've only updated the password length for members, not backoffice users.

![image](https://user-images.githubusercontent.com/304656/56120851-4f6c0a80-5f6f-11e9-8183-100007df3179.png)
