### ISSUE TITLE
V8 Missing methods of PublishedCultureInfo (CultureInfo)

### ISSUE THREAD

**Issue by ReVoid** [umbraco/Umbraco-CMS#5269]
In Umbraco V7 `IPublishedContent` has an extension method `GetCulture()` that returns an `CultureInfo` instance, but now in V8 it returns an `PublishedCultureInfo` instance. In current case, developers can't just intantly use `System.Globalization.CultureInfo` [methods](https://docs.microsoft.com/en-us/dotnet/api/system.globalization.cultureinfo?view=netframework-4.7.2#methods) that can't be used in many cases like get value for `lang` html attribute, or get values for language swither element, etc.

May be, `PublishedCultureInfo` should just inherits `CultureInfo`?

Reproduction
------------

### Specifics

Umbraco v8.0.1

### Steps to reproduce

1. Get any instance of `IPublishedContent`
2. Use GetCulture() method
3. Try to use `System.Globalization.CultureInfo` methods or properties eg `TwoLetterISOLanguageName`

**Comment by zpqrtbnk** [comment]
This is related to #5170 - some additions to `IPublishedContent` for variants (1:1 multilingual) see to collide with older methods & we need to sort this out.

**Comment by Shazwazza** [comment]
Also related to #5227 (have some notes in there too https://github.com/umbraco/Umbraco-CMS/issues/5227#issuecomment-483073323)

**Comment by zpqrtbnk** [comment]
Is going to be fixed as part of #5170, introducing `content.GetCultureFromDomains()` which returns a `string` - the ISO code of the culture. Closing this issue, please check #5170 for details + comment.
