### ISSUE TITLE
[V7] Incorrect string value \xE9 for tags

### ISSUE THREAD

**Issue by ssougnez** [umbraco/Umbraco-CMS#5283]
Hello,

we are using Umbraco with mysql and when we try to save a page with some tags that contains diacritics (in french), we get the error:

> MySql.Data.MySqlClient.MySqlException (0x80004005): Incorrect string value: '\xE9' for column 'Tag' at row 1

Clearly, the issue comes from the fact that the Tag column of the cmsTags table is using utf8_general_ci.

While the source of the error is obvious, the resolution is not that obvious to me. What am I supposed to do to fix it?

Do I have to change something in the database of Umbraco (doesn't sound like a best practice) or is it an up to Umbraco to fix this?

Note that I don't have the issue with the content of the page as the xml column of cmscontentxml is using latin1_swedish_ci (maybe the infra team where I work changed it, I don't know).

**Comment by ssougnez** [comment]
Hi,

any news about this? Our content editor are starting to get impatient not to be able to insert diacritics in theit tag :-D

Can you at least tell me if it's an issue in Umbraco or something wrong we did in the database setup ?

**Comment by nul800sebastiaan** [comment]
Sorry for the delay, unfortunately this seems to have never have been a problem before, I can't find similar errors relating to Umbraco. No idea what's going on but let us know if you figure out what causes this.

**Comment by ssougnez** [comment]
Well, the issue is that utf8_general_ci (in MySql) cannot store character encoded on 4 bytes like the one that correspond to an "é" and other accentuated characters. 

I can investigate this but first, I have a question for you. I noticed that the xml column of the table cmscontentxml is set on latin1_swedish_ci. Is it Umbraco that does that? (I'm not aware of all actions taken by the infrastructure team in here, so maybe it's coming from them). If it's Umbraco, I'm wondering whether it would be an option (or not) to apply the same charset to the tag column.

I'm thinking out loud here but I don't think it's up to the user to define the charset of the db used by Umbraco, is it?

**Comment by nul800sebastiaan** [comment]
Your guess is as good as mine mate, I'd have to investigate the same thing. I'd recommend reproducing on a test environment first and see how it goes.

**Comment by ssougnez** [comment]
Mmmmh, don't waste time on that for now. I just did a new installation with a mysql db and I don't have the issue. Maybe our infra team did something wrong. I'll close the issue if it's not Umbraco related.

**Comment by nul800sebastiaan** [comment]
This issue has been in the `up for grabs` state for quite a while now and it seems nobody is ready to pick this one up.

For now we'll close this issue to prevent the list of `up for grabs` from becoming very stale. We're happy to re-open it if someone still thinks it's good to work on this.

If anyone is about to pick this issue up to fix it, make sure to test first if you can reproduce the problem in the latest version before you start to work on it.

Thanks!
Sebastiaan on behalf of Umbraco HQ.
