### ISSUE TITLE
V7 - Preview button publishing un-published content.

### ISSUE THREAD

**Issue by jattwood** [umbraco/Umbraco-CMS#5289]
There are bug reports of the same occurring on V8 that are now closed. This is happening on Umbraco version 7.12.4 assembly: 1.0.6879.21982.

Steps to reproduce:

1) Create new content node
2) Click Save, not Save and publish
3) Next, click preview. Preview page and close window.
4) Go back to umbraco window, click on another node and then return back to the newly created node.
5) Go to the info tab, the un-published page will have a URL and history indicates Saved and Published....

Expected result is that the node is not published.

**Comment by nul800sebastiaan** [comment]
I can't reproduce in 7.14.0 with those steps, let me know if you can reproduce in that version!

**Comment by jattwood** [comment]
I can't duplicate this on 7.14. Any suggestions for a quick fix on 7.12.4 without having to do a complete upgrade? Many thanks for getting back so fast.

**Comment by nul800sebastiaan** [comment]
Should be a fairly straight-forward upgrade :)

Sorry, don't know how/where/when this was fixed, no workarounds that I know of.

**Comment by jattwood** [comment]
Roger that – thank-you Sebastiaan.

Jamie
