### ISSUE TITLE
V8: Moving Member Types

### ISSUE THREAD

**Issue by bmargevicius** [umbraco/Umbraco-CMS#5291]
### Bug summary
When trying to move a member of one type to another type the backoffice hangs.

### Specifics
Umbraco 8.01
Chrome 73.0.3683

### Steps to reproduce
Create a member type
Create a member of type "member" (The default)
Select the new member (put a green check next to it) 
The top menu bar will change and add a button labeled move.
Click the move button 
The right pane slides open with the tree of members and member groups. 
Expand the member tree
Select your member type in the first step
Click submit
Backoffice will hang.

![image](https://user-images.githubusercontent.com/24920023/56308626-c7743500-6115-11e9-8d1b-ccce9839184a.png)

### Expected result
Member moved to new member type.

### Actual result
Infinite spinning progress bar. 

### Side question
What is the method to do this programmatically? Meaning, when you push the button mentioned above what is the order of member service function calls to accomplish this?

**Comment by kjac** [comment]
Whoa. I'm pretty sure it's not supposed to be possible! I'll have a look.

**Comment by kjac** [comment]
The "Move" action doesn't seem available on vLatest:

![image](https://user-images.githubusercontent.com/7405322/56314109-7172b200-6154-11e9-890d-401e45ec15f2.png)

**Comment by nul800sebastiaan** [comment]
You should definitely not be able to "Move" members. Since a member type is basically a document type, you would need to map the properties from one membertype to the next. So yeah, that option should not have been there and is now unavailable 👍
