### ISSUE TITLE
Umbraco 8 HSTS Default Setting

### ISSUE THREAD

**Issue by ahwm** [umbraco/Umbraco-CMS#5292]
I just started up a new, empty copy of Umbraco 8.0.1. While exploring the backoffice, it recommended adding the HSTS header. However, there are a couple of issues with the implementation.

As per https://hstspreload.org/:
> If you maintain a project that provides HTTPS configuration advice or provides an option to enable HSTS, **do not include the `preload` directive by default.**

The HSTS health check does add the `preload` directive by default. It's not a huge deal for me as my domain is preloaded already, but this will cause problems for other users down the road for sure.

As an addition to that, the implementation doesn't conform to the RFC https://tools.ietf.org/html/rfc6797:

> **Section 7.2 HTTP Request Type**
> An HSTS Host MUST NOT include the STS header field in HTTP responses conveyed over non-secure transport.

In order to conform, the header should be set in the URL Rewrite instead with the `HTTPS == on` or `HTTPS != off` condition.

A valid rewrite rule that conforms to the RFC:

```xml
  <outboundRules>
	<rule name="HTTP Strict Transport Security">
	  <match serverVariable="RESPONSE_Strict_Transport_Security" pattern=".*" />
	  <conditions>
		<add input="{HTTPS}" pattern="on" />
	  </conditions>
	  <action type="Rewrite" value="max-age=63072000" />
	</rule>
  </outboundRules>
```

And a full example with the redirect also described in Section 7.2:

```xml
    <rewrite>
      <rules>
        <rule name="Require HTTPS" stopProcessing="true">
          <match url=".*" />
          <conditions>
            <add input="{HTTPS}" pattern="on" negate="true" />
            <add input="{HTTP_HOST}" pattern="localhost" negate="true" />
            <!-- Below to allow Let's Encrypt to validate, sometimes it doesn't play well -->
            <add input="{REQUEST_URI}" pattern="^/?.well-known" negate="true" />
          </conditions>
          <action type="Redirect" url="https://{HTTP_HOST}{REQUEST_URI}" appendQueryString="false" />
        </rule>
      </rules>
      <outboundRules>
        <rule name="HTTP Strict Transport Security">
          <match serverVariable="RESPONSE_Strict_Transport_Security" pattern=".*" />
          <conditions>
            <add input="{HTTPS}" pattern="on" />
          </conditions>
          <action type="Rewrite" value="max-age=63072000;includeSubDomains;preload" />
        </rule>
      </outboundRules>
    </rewrite>
```

**Comment by nul800sebastiaan** [comment]
Maybe we should remove preload, that makes sense. We have other health checks to check for the correct HTTPS configuration though, which will make sure you redirect from HTTP to HTTPS as well, so that's covered there. 

I've marked this as "Up for grabs" so that you or someone else coming along could create a pull request for it.

**Comment by ahwm** [comment]
Except for one thing - the current configuration sets IIS to send the HSTS header. That means it's getting sent by the server before the application (Umbraco) can perform any checks. So it's still non-conforming.

**Comment by nul800sebastiaan** [comment]
Not sure what you mean.. if you follow the health checks recommendations then you'll get a http to https redirect. It doesn't all happen in 1 go, for sure, but not having a redirect for 1 minute doesn't hurt anyone.

**Comment by nul800sebastiaan** [comment]
Fixed in https://github.com/umbraco/Umbraco-CMS/pull/5424
