### ISSUE TITLE
setting just an hash link is ignored by RTE

### ISSUE THREAD

**Issue by croban** [umbraco/Umbraco-CMS#5295]
Settings just hash link just with the hash is ignored by RTE 
Umbraco version 7.12.4 assembly: 1.0.6879.21982

Reproduction
------------
![image](https://user-images.githubusercontent.com/7048578/56369991-b4876080-61fa-11e9-956e-12e33a439ffa.png)

1) Select text inside RTE 
2) Klick at RTE link icon
3) Set just hash link
4) Save and Close
5) look at HTML, nothing have changed

**Comment by nul800sebastiaan** [comment]
Hey @croban - that's what the "Anchor" button is for, make sure to use that one instead 👍

![image](https://user-images.githubusercontent.com/304656/56373238-d71c7800-6200-11e9-9fde-5a181ad5b924.png)

**Comment by croban** [comment]
This "Anchor" icon adds A Tag with specified ID, but how would you link to that hash tag?
This should not be closed

**Comment by nul800sebastiaan** [comment]
Ah sorry, I wasn't paying close enough attention to what you're trying to do. You need to link to the current page, with the anchor you want.

![image](https://user-images.githubusercontent.com/304656/56415897-6e301100-628f-11e9-8d56-3bee88512d8c.png)

**Comment by nul800sebastiaan** [comment]
This used to be a bit easier in v7, we should fix the pre-population of the anchors in v8, see: https://github.com/umbraco/Umbraco-CMS/issues/5297

**Comment by croban** [comment]
Okay, that is fair solution, just that internal link must be selected also, even if the anchor is on the same site. That is one or n clicks away (depends on where internal link reside in tree). My problem is also that I use RTE for some newsletter content (jumping around in email client), means those links will have absolute url+hash which on click leave email client. For those kind of links I have to remove internal link in front of hash :(...

**Comment by nul800sebastiaan** [comment]
Make sure to ask around on [the forum](https://our.umbraco.com), sounds be too hard to come up with something that can help strip the URL off the anchor tags before sending it as an email.

**Comment by croban** [comment]
I know how to do that by using ValueConvert, but I need to invest time for doing that and just because because "Link" field ignores values like "#....". That is why I think "Link" field should allow "#hashtag" values.

**Comment by DontPanic345** [comment]
Hi @croban, @nul800sebastiaan 
I have the same issue exactly as described, we don't use Umbraco for serving the site at all, only content management so having to provide .

It really does seem like you should be able to set "#someid" in the Link field, as to produce html like
`href="#someid"` without having to modify source code.

Also when you do enter "#someid" into the Link field and press submit, there is no feed back saying that it was actually invalid and that nothing has changed.

Are there any other issues related to this? Can we get this one reopened please?

**Comment by nul800sebastiaan** [comment]
We'll have a chat at HQ about it soon to see how this feature would make the most sense.

**Comment by nul800sebastiaan** [comment]
As noted in #5433 this is apparently a bug in both v7 and v8 at the moment. We'll fix.

**Comment by DontPanic345** [comment]
Hi @nul800sebastiaan 

Has there been any progress on this bug?

**Comment by kjac** [comment]
@nul800sebastiaan PR for V8 is in #5608 - I'll backport to V7 soon as I can.

**Comment by kjac** [comment]
...and the V7 backport is in #5610

**Comment by Shazwazza** [comment]
Have merged in the v7 PR and merged up to v8, Thanks!
