### ISSUE TITLE
Document Type alias filter in List View

### ISSUE THREAD

**Issue by ksolberg** [umbraco/Umbraco-CMS#5296]
Ability to configure a document type alias filter in a List View. This is useful in scenarios where you have a mixed set of children and want grouped lists without an intermediate grouping node.

F.ex

Instead of this:

* Fruits
  * Apples
    * Apple
  * Bananas
    * Banana

You can have this:

* Fruits
  * Apple
  * Banana

Where Fruits have two list views with Apple and Banana document type filters configured respectively:

Fruits
/Apples\\/Bananas\\/Content\\/Info\\____

**Comment by nul800sebastiaan** [comment]
Gut feeling says: if we do this then we should enable all search boxes to allow filter by doctype, which might be a good thing or complete overkill. This seems like a scenario where it's only occasionally useful for some people, which is typically what we try to avoid.

I'll have to discuss this in our next regular meeting at HQ, I'll let you know the outcome.

**Comment by ksolberg** [comment]
I was thinking in a List View data type configuration.

**Comment by skttl** [comment]
I like this.

I think you should be able to configure different list views on your container doctypes, for each doctypes.

Say you have the following doctypes.
- FruitList
- Apple
- Banana

On your fruitlist, you would then add a listview for children of the Apple type, and a listview for children of the Banana type.

You might even then have children of other types, who will be visible in the tree instead (this is probably a can of worms, but have been suggested earlier IIRC).

We have just created a site, where we made a small productcatalogue. In this one we would have loved to be able to seperate each producttype to it's own list view, on the productcatalogue node (we ended up creating Books, T-shirts, etc. as children of the Products node instead).

Also, when we create news sections, we tend to have a structure like this:

- News section
 - News archive
  - News item
  - News item
  - News item
 - Text page (info on newsletters)
 - Text page (other information regarding news).

In this example, we need a listview for the news items, but would love to be able to skip the news archive type.

**Comment by nul800sebastiaan** [comment]
Taking a step back, list view was created to make sure that you didn't have endless items in the tree when expanding nodes and to help you find the last few items you've edited quickly so you could make some more edits to them. I don't think they were ever intended as a library to organize content in.

I think it should already be possible to create custom list views that do the things you're imagining though, so you should be able to switch around list views to only show current news items or archived news items.

Here's some more background info on custom list views: https://24days.in/umbraco-cms/2016/custom-list-view-layouts/ 
And you can imagine filtering out the correct document type can be done there, 

Will let you know what comes out of discussing this at HQ though :-)

**Comment by nul800sebastiaan** [comment]
Thanks for the feature request @ksolberg and the additional feedback @skttl !

While we certainly understand this functionality, it is not something we think is suitable to support in the core list viewer. As mentioned above, we'd encourage you to create custom list view layouts where you could create this type of filtering.
