### ISSUE TITLE
v8: Linking to an anchor doesn't give the handy anchor dropdown any more in v8

### ISSUE THREAD

**Issue by nul800sebastiaan** [umbraco/Umbraco-CMS#5297]
When you are in a rich text editor linking to a page, in v7 the properties on that page would get parsed to find possible anchor tags to pre-populate the link picker with. This now longer works on v8.

![image](https://user-images.githubusercontent.com/304656/56417122-35923680-6293-11e9-8b50-3cc998b5a4cc.png)

I've traced it down to https://github.com/umbraco/Umbraco-CMS/blob/v8/dev/src/Umbraco.Web.UI.Client/src/common/services/tinymce.service.js#L1170

`current.properties` is null here and I am not sure how to get the properties on a content item in v8, if at all possible.

**Comment by kjac** [comment]
PR in #5379

**Comment by nul800sebastiaan** [comment]
Fixed in https://github.com/umbraco/Umbraco-CMS/pull/5379

**Comment by ssougnez** [comment]
Hello,

I'm currently using Umbraco 8.18.3 and when I add a link to a document that contains an anchor, the dropdown menu does not appear.

This is the article:

![image](https://user-images.githubusercontent.com/10199821/162978729-0bc22f1a-d63e-48f2-a21a-71d95e9454b6.png)

And when I make a link to it, the menu does not appear

![image](https://user-images.githubusercontent.com/10199821/162978924-98915be7-4dca-4417-bc71-5f0f0c8513db.png)

Is it better to create a new issue for this or is this one enough?

Cheers
