### ISSUE TITLE
Boolean property editor uses labelOn value for the Off label

### ISSUE THREAD

**Issue by flobadea** [umbraco/Umbraco-CMS#5299]
In Umbraco 7.13.2, the boolean property editor has a feature to display the on/off label. When this feature is enabled, the editor displays the on label in both on and off states. The current implementation is below.

...
        label-on="{{model.config.labelOn}}"
        label-off="{{model.config.labelOn}}"
...

**Comment by abjerner** [comment]
@flobadea thanks for creating this issue 👍 

In the prevalue options, it's only possible to specify `labelOn`, which to the user is just presented as a general label - not specifically shown for either state:

https://github.com/umbraco/Umbraco-CMS/blob/v7/dev/src/Umbraco.Web/PropertyEditors/TrueFalsePropertyEditor.cs#L24

This is also the same for Umbraco 8:

https://github.com/umbraco/Umbraco-CMS/blob/853087a75044b814df458457dc9a1f778cc89749/src/Umbraco.Web/PropertyEditors/TrueFalseConfiguration.cs#L13

I'm not sure what the intent has been, but given the current prevalue options, I'd that this is working as it should.

But on the other hand, one could very well make the argument that it should also be possible to specify an *off* label. @nul800sebastiaan any thoughts on this?

And just for the record, this appears to work in the same way in both 7.14.0 and 8.0.1.

**Comment by nul800sebastiaan** [comment]
It was intentional. The variable naming seems a bit weird but the point was to have a label for the toggle not a label for each state of the toggle.

See the discussion on this issue - https://github.com/umbraco/Umbraco-CMS/pull/3179#issuecomment-427751640
