### ISSUE TITLE
Feature Request: 'unpublish' something within the Umbraco.NestedContent editor

### ISSUE THREAD

**Issue by shearer3000** [umbraco/Umbraco-CMS#5310]
Would it be possible for a Umbraco.NestedContent editor to allow the content editor to unpublish a particular item.

We have certain situations where a content editor has a page with various content constructed using a NestedContent editor and wish to temporality unpublish a specific piece of content without removing it entirely from the editor/page i.e. just to “hide” it on the website. Is there a use case for this to be core functionality?

An alternative could be for the content editor to remove the content from the editor and then reinstate it later using the “rollback” version, but that is more complicated for them.

Thanks

**Comment by nul800sebastiaan** [comment]
Hey there @shearer3000 - we currently don't have plans to implement this as an added feature, I would encourage you to read the discussion here as well https://github.com/umbraco/Umbraco-CMS/issues/2887 and you'll also find a package there that could help you out with the implementation you're looking for. 👍
