### ISSUE TITLE
Bug in RebuildContentDbCacheLocked

### ISSUE THREAD

**Issue by zpqrtbnk** [umbraco/Umbraco-CMS#5315]
As reported in https://our.umbraco.com/forum/umbraco-8/96924-bug-in-rebuildcontentdbcachelocked-not-paging-correctly paging is totally wrong

**Comment by zpqrtbnk** [comment]
PR #5316

**_Note to reviewer: this is an 8.0.2 fix. Merge into `v8/dev` and then make sure to cherry-pick in `v8/8.0`!_**

**Comment by zpqrtbnk** [comment]
oops

**Comment by zpqrtbnk** [comment]
oops

**Comment by nul800sebastiaan** [comment]
Merged and cherry picked into `v8/8.0` https://github.com/umbraco/Umbraco-CMS/commit/57c567c57099d54c36ad8393bfc52627da84045d.
