### ISSUE TITLE
V8: Nested Content should have a 'no blueprint'-state

### ISSUE THREAD

**Issue by nielslyngsoe** [umbraco/Umbraco-CMS#5319]
After making it possible to configure Nested Content with no blueprints, I would like the UI to be clear if a Nested-Content property is in that state.

Meaning in a state where no blueprints have been allowed for the Nested Content, then we should remove the Add-button and display the text: "No content is allowed for this property".

Idea and suggestions are very welcome.

**Comment by kjac** [comment]
Makes sense, @nielslyngsoe 👍 PR in #5342
