### ISSUE TITLE
V8: I would like to use the umbraco confirm dialog for deleting a nested content entry

### ISSUE THREAD

**Issue by nielslyngsoe** [umbraco/Umbraco-CMS#5327]
I would like to use the umbraco confirm dialog for deleting a nested content entry.

like this (just with a red-button aka. warning button style):
![image](https://user-images.githubusercontent.com/6791648/56640184-a742f980-6672-11e9-81a7-a88fe597e001.png)

**Comment by kjac** [comment]
Wouldn't it be nice to add a generic confirm dialog directive to handle these things - and do it as part of solving this issue instead of adding yet another custom delete overlay for NC? 

I'd be happy to build it - in fact I think I might already have promised @nul800sebastiaan to do it at some point 🤔

**Comment by abjerner** [comment]
I'm not sure how a directive would work in this case, but we could add a `delete` function to the `overlayService`. Even if there is a directive, I think a function like this would be a good idea - it could also be used by said directive.

For one of my packages, I currently have this:

```javascript
$scope.deleteEditor = function (index, editor) {
    overlayService.open({
        view: "/App_Plugins/Skybrud.PackageManifests/Views/Overlays/Delete.html",
        content: `Are you sure you wish to delete the property editor <strong>${editor.name}</strong>? Changes are not saved to the disk before you click the <strong>Save</strong> button.`,
        submitButtonLabel: "Confirm",
        closeButtonLabel: "Cancel",
        submit: function () {
            $scope.model.value.splice(index, 1);
            overlayService.close();
        },
        close: function () {
            overlayService.close();
        }
    });
};
```

which looks like:

![image](https://user-images.githubusercontent.com/3634580/56855896-21fc6500-6950-11e9-9ad6-151231c580fd.png)

If `overlayService` has a `delete` function, the same code could be reduced to (the properties for the view and the buttons labels are gone):

```javascript
$scope.deleteEditor = function (index, editor) {
    overlayService.delete({
        content: `Are you sure you wish to delete the property editor <strong>${editor.name}</strong>? Changes are not saved to the disk before you click the <strong>Save</strong> button.`,
        submit: function () {
            $scope.model.value.splice(index, 1);
            overlayService.close();
        }
    });
};
```

The view for the overlay can be quite simple:

```html
<div ng-bind-html="model.content"></div>
```

and the function inside the overlay service could look something like:

```javascript
function delete(overlay) {

    overlay.view = "views/common/overlays/delete/delete.html";

    if (!overlay.close) {
        overlay.close = function() {
            close();
        }
    }    

    open(overlay);

}
```

In my case, I need `content` to be HTML - but the delete overlay could have `content` for non-HTML content (regular `ng-bind`) and `contentHtml` for actual HTML (using `ng-bind-html`). That way it's more clear for developers when they're showing raw HTML.

Per @nielslyngsoe's example, there could be a `title` property as well. I'm not sure a red button is necessary, although is does imply danger.

**Comment by kjac** [comment]
As it turns out, `overlayService` can't have a generic delete dialog with default texts because it causes circular references on `localizationService`. 

If we're to do this, another component/service must be introduced. For the time being I think it's wiser to stick with the default `overlayService` handling for this issue. I'll submit a PR momentarily.

**Comment by kjac** [comment]
PR in #5357

**Comment by kjac** [comment]
Turns out @bjarnef also did a PR for this in #4831 🤔
