### ISSUE TITLE
RTE editor in grid collapsed/disappears after reordering

### ISSUE THREAD

**Issue by sumedhashyam** [umbraco/Umbraco-CMS#5345]
Hello Support,

When we reorder RTE editors in Grid, it collapsed. The client thinks he lost the data. 

Reproduction

We can easily reproduce this error by reordering RTE editors in Grid.

Bug summary

RTE elements in the grid often get hidden after sorting the grid elements

Specifics

Umbraco version 8.0.1

Reproduced in browsers:
Chrome Version 74.0.3729.108
Safari Version 11.1.2 (13605.3.8)

Steps to reproduce

My reproduction path is:

I edit a page which has a grid element with 3 Rows
Add 3 RTE editors with some text (1 in each Row)
Select "Reorder" and start shuffling the RTE's between the rows.
Select "I am done reordering".

Expected result

All RTE's (including content) that were visible before sorting, are also visible after reordering.

Actual result

1 or more RTE editors are no longer visible after reordering

Additional info

http://cloud.webvision.dk/3dce959c337d

Related bug : https://github.com/umbraco/Umbraco-CMS/issues/3835

**Comment by nielslyngsoe** [comment]
PR https://github.com/umbraco/Umbraco-CMS/pull/5536

**Comment by warrenbuckley** [comment]
All tested & merged in the PR with the fix in #5536
