### ISSUE TITLE
V8: contentService.Save doesn't save nested content

### ISSUE THREAD

**Issue by bmargevicius** [umbraco/Umbraco-CMS#5348]
Nested content is saved through the content service as a json string. Traditionally this json string is serialized from a List of Dictionary<string, object>. Where the string is the nested content type alias, and the object is the value. You can see it demonstrated here https://our.umbraco.com/packages/backoffice-extensions/nested-content/nested-content-feedback/88895-creating-nested-content-programatically

This no longer appears to work in Umbraco 8. You can set the value, save and the backoffice does not update. 

I suspect it's because nested content is treated differently as a IPublishedElement, versus content.

Reproduction
------------

### Bug summary

Create a nested content type. Assign something simple like a textbox. Try to set the value of this textbox and nothing happens. 

### Specifics

Umbraco 8.01

### Expected result

Something to appear in a textbox in the backoffice. Perhaps a validation error on contentService.Save when trying to save something to a nested type.

### Actual result

contentService.Save saves other content as expected. Nested content is not saved.

**Comment by zpqrtbnk** [comment]
The serialized format of Nested Content property values has quite probably changed in v8. Here is what I have in database for a Nested Content property with only 1 TextBox:
~~~~
[
{"key":"04a6dba8-813c-4144-8aca-86a3f24ebf08","name":"Item 1","ncContentTypeAlias":"nested","text":"woot"},
{"key":"d8e214d8-c5a5-4b45-9b51-4050dd47f5fa","name":"Item 2","ncContentTypeAlias":"nested","text":"zoot"}
]
~~~~
You will therefore need to adjust how you set the value.

I have also commented on the Our thread and suggest this is discussed there, as it is not really an "issue" that we can "fix". Closing this issue, if you don't mind?

**Comment by bmargevicius** [comment]
No problem. I, and probably others, need a documented answer somewhere. I'm going to try to code this out and report back later so others can use this to import/create nested content.

**Comment by bmargevicius** [comment]
Thanks for updating the forum to look here. Here is what I did to make it work. 

I have a piece of nested content with two properties. it's alias is cardConfigurations

advertiser - a member picker type - you need to convert this to the member udi to save
number - a numeric type - this gets saved as an int..

In your models folder create a class. I called mine AdvertiserConfig. I added an INestedContent interface for the top three properties: key, name and ncContentTypeAlias. The bottom two properties are the aliases of my property editors. We'll be serializing this object to json later.

I am not sure what key, and name is or does. It looks like key is requires and not autogenerated. Name looks like the label you see when the nested content accordion is collapsed. I left name = null. In my nested content type I have a Template that looks like 
{{number}} - {{ advertiser | ncNodeName }}. This will output something like '1 - Some Advertiser Member Name'. Which I think is overriding the name property. Experiment and post results here. 

public class AdvertiserConfig : INestedContent
{
public Guid key => Guid.NewGuid();
public string name { get; set; }
public string ncContentTypeAlias => "cardConfigurations";
public string advertiser { get; set; }
public int number { get; set; }
}

In my import service I create a list of AdvertiserConfig and Serialize that object to json using Newtonsoft.
`
List<AdvertiserConfig> nestedcontent = new List<AdvertiserConfig>();
            var cardconfigs = //an enumbeable of cardconfigs
            if (cardconfigs != null)
            {
                foreach (var config in cardconfigs)
                {
					//query our umbraco members for advertisers, find the one that matches config.advertiserid
					//advertiser = umbraco.member.advertiser //dummy code.  
					
					var advertiserudi = Udi.Create(Constants.UdiEntityType.Member, advertiser.Key);
					
					AdvertiserConfig c = new AdvertiserConfig();
					c.advertiser = advertiserudi.ToString();
					c.number = config.number;
					nestedcontent.Add(c);
                }
                return JsonConvert.SerializeObject(nestedcontent);
        }            
`

After this we can create our content from the contentService, get the json string, and set it to the nested content property type alias, and save our content 

var promotion = contentService.Create(); 
var advertiserConfig = AdvertiserConfigGenerator(); //return json from above
promotion.SetValue("advertiserConfig", advertiserConfig); //set the property alias of the nested content type to be the json string
contentService.Save(promotion);

That should do it. Sorry about the code blocks the markdown editor and formatting code isn't the greatest.

**Comment by stherm** [comment]
Where is the InestedContent interface? I can't find it in the code to include in my project

**Comment by bmargevicius** [comment]
INestedContent is something I wrote (I don't work for Umbraco). Nested Content requires two properties.. (I am not sure what name does):
Guid key, string name, string ncContentTypeAlias.. So if you had other models that are nested content. The INestedContent Interface guarantees you have the properties needed to serialize and save nested content correctly. 

Everything you need is written in the narrative above. If you have any questions I am listening.. 👂

**Comment by stherm** [comment]
Thank you, everything is working fine!
