### ISSUE TITLE
v8: Make TypeCollectionBuilderBase chainable

### ISSUE THREAD

**Issue by mattbrailsford** [umbraco/Umbraco-CMS#5350]
When composing collections, most of the CollectionBuilderBase classes are chainable such that you can chain add / remove commands in a fluent manor. For some reason though this doesn't appear to be possible with the TypeCollectionBuilderBase. I think this should be made consistent with the other base classes and allow a similar API.

**Comment by zpqrtbnk** [comment]
would totally make sense indeed. Would it be a breaking change? Guess yes... 8.1 then?

**Comment by mattbrailsford** [comment]
I don't think so as all Add / Remove methods are currently return `void` so those can continue to function as before, then just now return a instance of the collection to allow chaining.

**Comment by mattbrailsford** [comment]
ie, yes the signature is changing, but because they didn't return anything before, I think it's ok to now make them return something.

**Comment by zpqrtbnk** [comment]
fancy a PR? :-)

**Comment by mattbrailsford** [comment]
@zpqrtbnk would love to if I wasn't spending all my time v8-ifying TC 😁

**Comment by zpqrtbnk** [comment]
PR #5354

**Comment by Shazwazza** [comment]
Have merged, it's marked as breaking (since the generic signature changes) but expect this will affect a very very tiny amount of people

**Comment by JHHessels** [comment]
I did an umbraco 8.0.2 upgrade to Umbraco 8.1.1 in the cloude and locally. But after upgrading the database I get the following exception such as https://our.umbraco.com/forum/umbraco-8/98064-umbraco-8-typecollectionbuilderbase-issue. It may have to do with this fix. If so, can I fix this?
