### ISSUE TITLE
v8: Richtext editor view source code editor should get focus

### ISSUE THREAD

**Issue by christophnz** [umbraco/Umbraco-CMS#5363]
### Bug summary

After clicking the `View Source Code` icon in the Richtext editor, the code editor opens, but doesn't get focus, so if I start typing or paste, the content still goes into whatever field last had focus.

### Specifics

Umbraco v8.0.1
Reproduced in Firefox 66 and Chrome 73

### Steps to reproduce

* Put the focus (cursor) in any text field or the richtext editor
* Click the `View Source Code` button
* Type or paste some content
* Click `Close`
* The typed/pasted content is in the text field or richtext editor that last had focus

### Expected result

The code editor should get the focus to avoid accidentally editing content that is hidden behind the code editor

### Actual result

I accidentally pasted HTML code into a text field that was hidden behind the code editor and still had focus.

**Comment by nul800sebastiaan** [comment]
Yeah, that seems annoying 🙈 

I've marked this as "Up for grabs" so that you or someone else coming along could create a pull request for it. 

Relates to https://github.com/umbraco/Umbraco-CMS/issues/5220 as well.

**Comment by kjac** [comment]
That indeed is annoying! Nice catch! 

PR in #5398

**Comment by nul800sebastiaan** [comment]
Fixed in #5398
