### ISSUE TITLE
Multiple Media Picker Not working

### ISSUE THREAD

**Issue by mathewknott** [umbraco/Umbraco-CMS#5368]
I've tested this for a "Multiple" Media Picker. It could be for single items too. I'm note sure of the behaviour in that case

This is for both 8.01 and 8.0.2. I upgraded my project thinking bug fixes around the Media Picker may have resolved this.

Steps to recreate. 

1. In Data Types area, I create a Data Type called "Multiple Image Picker". It uses the following settings

Property Editor: Media Picker
Pick Multiple Items: true
Pick Only Images: true
Disable Folder Select: True
Start Node: A sub folder I created under the Media called "Images"

2. I create a doc type and add a property with this doc type.

3. Add a content page

4. The template code to render is as follow. Note my comments

@if (Model.HasValue("pageGalleryImages"))
{
	//this gets hit
	var galleryImages = Model.Value<IEnumerable<IPublishedContent>>("pageGalleryImages");
	if(galleryImages != null) {
		//this DOES NOT get hit
		foreach (var galleryImage in galleryImages)
		{
			@galleryImage.Url
		}
	}
}

Other things I've tried to verify..

1. I changed the property to a previously created "Multiple Media Picker". That seems to work 

2. I "saved" the new "Multiple Image Picker" Data Type and reloaded and it seemed to make the images render. 

3. I go to the content page and "publish" and the property content disappears when I reload the front end. I then return to the Data Type and press save and go back to the front end again and refresh the page and it loads. Interesting to note here is that if I save either my new custom Image Media Picker Type or the previously created Multiple Media Picker then this result is the same. If I save a data type of a different Property Editor it doesn't have this "refreshing" effect. I guess that's by design.

So it seems like re-saving a Data Type that uses the "Media Picker" type may fix the Cache up? But Publishing content breaks it again. 

Or maybe there's an issue with a Second Multiple Media Picker as the first one seems to function OK. It's only an issue when a second one is created.

I hope this makes sense. FYI, I replicated the same behaviour on a separate 8.0.1 site created.

My workaround: Just use the first generic "Multiple Media Picker" rather than the second specific Image one.

**Comment by kjac** [comment]
@mathewknott sounds annoying! Thanks for reporting 😄 

A few clarifying questions...

1. Is your media picker part of a composition by any chance? There's a known issue with property changes on compositions.
2. Is the problem resolved if you restart the site?

**Comment by mathewknott** [comment]
Its not a part of a composition. I'm current not using compositions on the site
I haven't tried restarting the site.

**Comment by nul800sebastiaan** [comment]
A quick test shows it works fine: 

```
@foreach(var item in Model.Value<List<IPublishedContent>>("gallery")) {
    @item.Name
}
```

Make sure to get some more help on the forum at https://our.umbraco.com/ where our friendly community can show you better ways of querying these kinds of things! 👍

**Comment by mathewknott** [comment]
Did you go through my steps to try and replicate?

**Comment by mathewknott** [comment]
@nul800sebastiaan You seem pretty quick to dismiss this as a non-issue. Can you please explain why this was closed?

**Comment by nul800sebastiaan** [comment]
I went through your steps to replicate and used the code above, not your code. The code above seems to work. Make sure to get some more advise on the forum! 

It is entirely possible that I'm overlooking something obvious but I am able to do what you're trying to do so it seems to work. Apart from that if the picker did not actually work then we very likely would have had more bug reports, which I haven't seen.

**Comment by mathewknott** [comment]
Ok thanks for clarifying.
