### ISSUE TITLE
V8 Settings - Remove old 'Editors Manual' link from the 'Start Here' dashboard message

### ISSUE THREAD

**Issue by marcemarc** [umbraco/Umbraco-CMS#5370]
On a fresh install of Umbraco V8, if you switch to settings section there is a Start here dashboard, that points people to 'find out more'

There is a link here to an 'Editors Manual' - but the link is to a V7 manual circa  v7.1

I can't find a more up to date version online, so was wondering out loud whether it's helpful to include the link here at all? or should we update the text to say V7 Editor's Manual, just thinking to avoid confusion? maybe it's fine, but raising it here stops me thinking about it!

![image](https://user-images.githubusercontent.com/260802/57015194-5b142e00-6c0b-11e9-81d0-84eed995b87e.png)

**Comment by nul800sebastiaan** [comment]
I think that link should just be removed until there's an editor's manual that is maintained by HQ. For now the best thing to do would be to point at documentation it seems. 

And as an idea for docs: editor's documentation?

I've marked this as "Up for grabs" so that you or someone else coming along could create a pull request for it.

**Comment by marcemarc** [comment]
@nul800sebastiaan done! - yes there is an issue open in the UmbracoDocs repo: https://github.com/umbraco/UmbracoDocs/issues/877 it's a bit blocked, need to understand overlap with the new content course, but also having an editor focused Tour, might be a quick win too! (also this dashboard is on the settings section, so not sure how relevant the editor manual link was)

**Comment by nul800sebastiaan** [comment]
> also this dashboard is on the settings section, so not sure how relevant the editor manual link was

Oh yes. One could argue the admins would know about the manual and pass it on to their editors, which turns out not to be very useful. :)

**Comment by nul800sebastiaan** [comment]
Fixed in https://github.com/umbraco/Umbraco-CMS/pull/5378
