### ISSUE TITLE
v8: DB TableBuilder can't handle Currency field types

### ISSUE THREAD

**Issue by mattbrailsford** [umbraco/Umbraco-CMS#5376]
I've created a migration plan that attempts to create some DB tables using the TableBuilder helpers and for one of the columns I need it to be a currency field. Now, I can do the following:

    Create.Table("myTableName")
        .WithColumn("price").AsCurrency().NoNullable()
        .Do()

And all of this is valid code (it compiles). However, when the `Do()` is executed it throws an exception. The exeception is a bit vague, but I've ultimately narrowed it down to the TableBuilder being unable to find a type for `DbType.Currency` in the SqlSyntaxProviders DbTypeMap collection.

Ultimately then, the SqlSyntaxProvider.DbTypeMap collection needs updating to hold a type map for the `DbType.Currency` type.

**Comment by nul800sebastiaan** [comment]
Hehe, nice one. Who would need a currency column in a CMS! ;-)

For now you can work around it with a full SQL query instead `base.Context.SqlContext.Sql("CREATE TABLE ... ");`

I've marked this as "Up for grabs" so that you or someone else coming along could create a pull request for it.

**Comment by dampee** [comment]
Do you mean money SQL server column type? 
What is wrong with decimals?

**Comment by mattbrailsford** [comment]
@dampee decimal is fine, I've done a workaround for now using `.AsDecimal(19, 4)` which seems to be the common accuracy for money. The point of this issue is that if you use `.AsCurrency()` you'll get an error because there is no mapping for it. I don't mind what it maps to, it just needs to map to something 😁

**Comment by nul800sebastiaan** [comment]
I've just noticed that other types also seem to not be wired up (the dimmed ones). I don't know why they're there if we don't intend to wire them up. 🤔

![image](https://user-images.githubusercontent.com/304656/57140124-4c6a7a00-6db7-11e9-8b10-1750e3f89809.png)

**Comment by dawoe** [comment]
Hi @nul800sebastiaan 

I was just looking at this as well. But I found these methods implemented in this class : https://github.com/umbraco/Umbraco-CMS/blob/v8/dev/src/Umbraco.Core/Migrations/Expressions/ExpressionBuilderBaseOfNext.cs

**Comment by nul800sebastiaan** [comment]
This issue has been in the `up for grabs` state for quite a while now and it seems nobody is ready to pick this one up.

For now we'll close this issue to prevent the list of `up for grabs` from becoming very stale. We're happy to re-open it if someone still thinks it's good to work on this.

If anyone is about to pick this issue up to fix it, make sure to test first if you can reproduce the problem in the latest version before you start to work on it.

Thanks!
Sebastiaan on behalf of Umbraco HQ.
