### ISSUE TITLE
v8: Changing icon color in listview layout break icon

### ISSUE THREAD

**Issue by bjarnef** [umbraco/Umbraco-CMS#5380]
In config of listviews (custom or extending existing ones) it is possible to add custom listview layouts and set an icon for these.

![image](https://user-images.githubusercontent.com/2919859/57044760-e6251080-6c6b-11e9-9b01-c420a18b9c98.png)

Howeever when changing color of the icon, e.g. selecting green `color-green`, the icon is broken, because the icon get the class `undefined color-green` instead of in this case `icon-truck color-green`.

![image](https://user-images.githubusercontent.com/2919859/57044817-19679f80-6c6c-11e9-8e0d-78bb8e52a327.png)

![image](https://user-images.githubusercontent.com/2919859/57044863-41570300-6c6c-11e9-8bab-498dbee15938.png)

**Comment by nul800sebastiaan** [comment]
Oh that's unfortunate! 

I'm sure @nielslyngsoe has an opinion on this as he doesn't seem to like people throwing loads of colors on everything. So I'm not sure he wants this fixed at all. :-)

**Comment by bjarnef** [comment]
In that case we might need to re-consider which colors should be available from icon picker, but in any case it would be great to have an option to disable selection colors in icon picker via a property/parameter in icon picker and e.g. in this case not allow picking colors, while it still could be available on document, media and member types.

**Comment by nul800sebastiaan** [comment]
Yep, it's on Niels' todo list to start limiting the number of color choices in the icon picker for doc/media/member types in the future. :)

**Comment by bjarnef** [comment]
Fixed in https://github.com/umbraco/Umbraco-CMS/pull/5405

We can look further into hiding colors in icon picker via a property and limiting the number of colors.

**Comment by bjarnef** [comment]
@nul800sebastiaan can you mark this with "community/pr"? :)

**Comment by nul800sebastiaan** [comment]
Fixed in https://github.com/umbraco/Umbraco-CMS/pull/5405
