### ISSUE TITLE
v8: Toggle color picker labels squeeze spectrum color picker

### ISSUE THREAD

**Issue by bjarnef** [umbraco/Umbraco-CMS#5381]
When toggling color picker labels in configuration, it seems to squeeze spectrum color picker.

![image](https://user-images.githubusercontent.com/2919859/57045638-8a0fbb80-6c6e-11e9-9d05-f81eb5e1c163.png)

![image](https://user-images.githubusercontent.com/2919859/57045645-909e3300-6c6e-11e9-80d5-7d56a31b3065.png)

**Comment by nul800sebastiaan** [comment]
Whoops, that seems like an oversight!

I've marked this as "Up for grabs" so that you or someone else coming along could create a pull request for it.
