### ISSUE TITLE
Content is not allowed between the opening and closing tags for element 'Macro'

### ISSUE THREAD

**Issue by srikesavanj** [umbraco/Umbraco-CMS#5383]
![image](https://user-images.githubusercontent.com/39899582/57060386-de4e8600-6cd6-11e9-9d4b-d2e36dcf4f2d.png)

**Comment by abjerner** [comment]
Hi @srikesavanj 

Isn't this the same as your other issue: https://github.com/umbraco/Umbraco-CMS/issues/5384 ?

**Comment by srikesavanj** [comment]
#5384 - How to get admin properties in Master. (**Asking the options**)
#5383 - Content is not allowed between the opening and closing tags for element 'Macro'. 
(**I tried one option. But isn't working**)

**Comment by nul800sebastiaan** [comment]
This is correct, content is not allowed there and we don't plan to support that. :-)
