### ISSUE TITLE
How to get admin properties in Master

### ISSUE THREAD

**Issue by srikesavanj** [umbraco/Umbraco-CMS#5384]
I tried to below code

<umbraco:Macro runat="server" language="cshtml">
@Helper.getPropertyWithoutRootLookup(ref homepageID, "mENU-", selectedLanguage);
@Umbraco.Field("Id")
</umbraco:Macro>

But facing content is not allowed between the opening and closing tags for element 'Macro'
![issue](https://user-images.githubusercontent.com/39899582/57060513-54eb8380-6cd7-11e9-8c0d-f948b6a81bb7.jpg)

**Comment by nul800sebastiaan** [comment]
As you've figured out, this syntax is not supported.

Hey @srikesavanj - Make sure to ask your questions on how to use Umbraco on the forum at https://our.umbraco.com please! 👍

**Comment by srikesavanj** [comment]
Thanks @nul800sebastiaan
