### ISSUE TITLE
Object Automatic naming

### ISSUE THREAD

**Issue by GionataAladinoCanova** [umbraco/Umbraco-CMS#5388]
I have "Work" document type.

When I make a new property, like "Title", the automatic name given is "title".

Better is concat Document Type with Property Name es "workTitle"

**Comment by nul800sebastiaan** [comment]
Hey @GionataAladinoCanova this is more of a support question,  make sure to ask your questions on how to use Umbraco on the forum at https://our.umbraco.com

Thanks!

**Comment by GionataAladinoCanova** [comment]
My english is very bad! I suggest to modificate Umbraco.

Now: umbraco suggest "**title**" as property alias.
Tomorrow: umbraco suggest "**workTitle**" as property alias  (Document Type Name + Property Name)

Sample:
![workTitle](https://user-images.githubusercontent.com/50195729/57072783-338e9580-6cdf-11e9-9f6d-4834a254437a.jpg)

**Comment by nul800sebastiaan** [comment]
I understand, and this can be done! You just need to click on the little "lock" icon next to the title to give it a better name. 

I am recommending you ask your questions on the forum so people can help you there, the issue tracker here is not suitable for questions on how to use Umbraco. :-)

**Comment by GionataAladinoCanova** [comment]
Yes, MANUALLY I just need to click etc. I mean "AUTOMATICALLY" :)

**Comment by nul800sebastiaan** [comment]
@GionataAladinoCanova I understand what you mean. Unfortunately for you, this is not a feature we plan to implement.
