### ISSUE TITLE
Umbraco.Core.dll - Assembly version not updated for patches

### ISSUE THREAD

**Issue by Gansted** [umbraco/Umbraco-CMS#5392]
### Description
The assembly version for Umbraco.Core.dll has not been updated for the 8.0.1 and 8.0.2. Both have assembly version 8.0.0.0. 

This is particularly problematic when working with Umbraco Cloud in Visual Studio as described in https://our.umbraco.com/documentation/Umbraco-Cloud/Set-Up/Working-With-Visual-Studio/. In this setup there is a need to automaticly check if the web project has had assemblies updated by the autoupdate feature such that the core project NuGet references can be updated accordingly.

As a temporary workaround I am checking on file version but the assembly version should match.

Reproduction
------------
### Steps to reproduce

Check the assembly version of Umbraco.Core.dll for Umbraco 8.0.1 and 8.0.2, e.g using ``[System.Reflection.AssemblyName]::GetAssemblyName("AssemblyPath").Version`` in Powershell

### Expected result

Assemblies for version 8.0.1 and 8.0.2 of Umbraco have different assembly versions

### Actual result

Assemblies for version 8.0.1 and 8.0.2 of Umbraco have the same assembly version, i.e. 8.0.0.0

**Comment by Gansted** [comment]
I imagine that the fix for this is automating assembly versioning in your release pipelines.

**Comment by nul800sebastiaan** [comment]
If you need to know that info, we update the File Version and Product Version.

![image](https://user-images.githubusercontent.com/304656/57077994-aacb2600-6ced-11e9-8681-4372866f7862.png)

**Comment by zpqrtbnk** [comment]
And, we cannot really change the assembly version. If anything is built against, say, 8.0.0, it would fail to run against 8.0.1 (or require a binding redirect). To keep things simple and not force ppl to use binding redirects, we do not change the assembly version.

**Comment by uli-weltersbach** [comment]
For anyone else looking for a thorough explanation: https://stackoverflow.com/a/3905443/1764844
