### ISSUE TITLE
Issue with colorpicker

### ISSUE THREAD

**Issue by poornimanayar** [umbraco/Umbraco-CMS#5393]
**Steps to reproduce**

1. Create a datatype of type "color picker"
2. Toggle to include labels, the input  for label should show
3. Save the datatype
4. The input field for label disappears with the toggle for label still on

![image](https://user-images.githubusercontent.com/3941753/57079094-8cfac280-6ce7-11e9-816a-2cb3aa87aad5.png)

**Comment by kjac** [comment]
Heh... that was a funky root cause. PR in #5396
