### ISSUE TITLE
Modelsbuilder custom tool stuck in 8.0.2

### ISSUE THREAD

**Issue by FransdeJong** [umbraco/Umbraco-CMS#5399]
Modelsbuilder custom tool is broken in 8.0.2.
If you run it it keeps running and the only way to stop it is by force closing Visual Studio.
This hapens in VS2017 and VS2019

Since Cloud auto updated this patch on all my V8 projects I'm stuck right now for all of them...

Reproduction
------------
Start a cloud project,
Clone the project using Uaas
Get the Modelsbuilder and API packages from nuget.
Run the custom tool.

### Expected result

All default models get rendered.

### Actual result
Only one model is rendered and the custom tool is stuck.

**Comment by nul800sebastiaan** [comment]
Sorry to be a bit of a "stickler for the rules" here, but can you kindly report this at https://github.com/zpqrtbnk/Zbu.ModelsBuilder instead please? Umbraco doesn't make the custom tool 😄  👍 

Thanks!

**Comment by FransdeJong** [comment]
No problem. I thought it was part of Umbraco now.

**Comment by dawoe** [comment]
@nul800sebastiaan 

Does that mean that API models are not officially supported by Umbraco. Because you need this tool to use that mode to generate your models in visual studio. We use it on all our projects that way.

I am not a fan of the live or dll modes

Dave

**Comment by nul800sebastiaan** [comment]
We're talking about the custom tool here... 

The Modelsbuilder part that ships with Umbraco is supported by Umbraco.

**Comment by FransdeJong** [comment]
Feels a bit strange that a tool that makes one of the modelsbuilder modes work falls outside the scope, but maybe that's a discussion for the future ;-)

**Comment by dawoe** [comment]
Yes feels very strange to me as well.

So you can use Models Builder in 5 different modes...but one is not officially supported because it needs a tool ?

Dave

**Comment by nul800sebastiaan** [comment]
We're giving as much support as we can. 😊

I'm just putting issues in the correct repositories so they relate to the actual code. 👍
