### ISSUE TITLE
v8: Avatar should use hand cursor

### ISSUE THREAD

**Issue by bjarnef** [umbraco/Umbraco-CMS#5404]
The avatar in top right corner in backoffice used to use a hand cursor style, because it is clickable.

Furthermore I think previously elements with `ng-click` elements get the hand cursor style, but it doesn't seem to be the case anymore.

![image](https://user-images.githubusercontent.com/2919859/57194874-478aff00-6f4c-11e9-860c-25f57561b8c0.png)

**Comment by nul800sebastiaan** [comment]
👍 Let's start with the avatar and figure out where else we need to fix the ng-clicks.

I've marked this as "Up for grabs" so that you or someone else coming along could create a pull request for it.

**Comment by bjarnef** [comment]
I wonder if this approach to style `ng-click`, `data-ng-click` with cursor hand style has been removed.
https://stackoverflow.com/a/18896948/1693918

```
[ng-click],
[data-ng-click],
[x-ng-click] {
    cursor: pointer;
}
```

This PR https://github.com/umbraco/Umbraco-CMS/pull/5414 fix it in this case, but there are other places as well where only `ng-click` is used.

https://github.com/umbraco/Umbraco-CMS/blob/853087a75044b814df458457dc9a1f778cc89749/src/Umbraco.Web.UI.Client/src/views/propertyeditors/grid/grid.prevalues.html#L14

https://github.com/umbraco/Umbraco-CMS/blob/853087a75044b814df458457dc9a1f778cc89749/src/Umbraco.Web.UI.Client/src/views/propertyeditors/grid/grid.prevalues.html#L40

https://github.com/umbraco/Umbraco-CMS/blob/853087a75044b814df458457dc9a1f778cc89749/src/Umbraco.Web.UI.Client/src/views/propertyeditors/grid/grid.prevalues.html#L59

**Comment by nul800sebastiaan** [comment]
Fixed in https://github.com/umbraco/Umbraco-CMS/pull/5553
