### ISSUE TITLE
v8: Add empty state in user layout views

### ISSUE THREAD

**Issue by bjarnef** [umbraco/Umbraco-CMS#5406]
In user section when filtering users and user groups and there are no match, it should show an empty state message, similar to listviews in content section.

![image](https://user-images.githubusercontent.com/2919859/57195225-77d49c80-6f50-11e9-8a8b-744e98a39753.png)

![image](https://user-images.githubusercontent.com/2919859/57195270-db5eca00-6f50-11e9-9e53-5e496348a0a1.png)

![image](https://user-images.githubusercontent.com/2919859/57195250-a6eb0e00-6f50-11e9-9f7c-3dd70291a40f.png)

![image](https://user-images.githubusercontent.com/2919859/57195255-b407fd00-6f50-11e9-939f-e566be5fb061.png)

**Comment by kjac** [comment]
Nice one! PR in #5407
