### ISSUE TITLE
V8: ListView should accept an item click handler

### ISSUE THREAD

**Issue by mattbrailsford** [umbraco/Umbraco-CMS#5413]
Currently the ListView assumes that when an item is clicked, it should perform a navigation to 

    $location.path($scope.entityType + '/' + $scope.entityType + '/edit/' + (item.id === 2147483647 ? item.key : item.id));

The problem with this is this is that it assumes a very specific route path structure that is unlikely to match anything outside of umbraco. Because of this, the list view is completely unusable by 3rd parties wishing to reuse functionality with some level of hacking.

The simplest option would be to allow passing in to the list view layout directive an item click handler such that a third party can provide custom functionality on what should happen when an item is clicked.

**Comment by nul800sebastiaan** [comment]
Sounds like a good idea! 👍

I've marked this as "Up for grabs" so that you or someone else coming along could create a pull request for it.

**Comment by nul800sebastiaan** [comment]
This issue has been in the `up for grabs` state for quite a while now and it seems nobody is ready to pick this one up.

For now we'll close this issue to prevent the list of `up for grabs` from becoming very stale. We're happy to re-open it if someone still thinks it's good to work on this.

If anyone is about to pick this issue up to fix it, make sure to test first if you can reproduce the problem in the latest version before you start to work on it.

Thanks!
Sebastiaan on behalf of Umbraco HQ.
