### ISSUE TITLE
Media file location

### ISSUE THREAD

**Issue by MortenL** [umbraco/Umbraco-CMS#5415]
When changing the physical location of the media folder, Umbraco still thinks that the physical files are located inside the root directory.

to reproduce, create a simple class like this:

```csharp
public class Class1 : IUserComposer
{
        public void Compose(Composition composition)
        {
            var rootPath = "c:/MyMediaFiles";
            var rootUrl = "/MyMediaPath";
            composition.SetMediaFileSystem(() => new PhysicalFileSystem(rootPath, rootUrl));
        }
}
```

next upload an image. It'll be stored in the right folder, but umbraco won't serve the file from the virtual directory (in this case /MyMediaPath).

**Comment by nul800sebastiaan** [comment]
Hey @MortenL - thanks for reporting. I have a few questions:

1. What version of Umbraco are we talking about
2. How did you change the physical location of the media folder?
 
I am not sure how this works currently, in v8, in v7 you needed to update a config file, did you do that?

**Comment by MortenL** [comment]
Hi @nul800sebastiaan 
1. 8.0.2
2. In U8, /config/FileSystemProviders.config is no longer present

**Comment by RachBreeze** [comment]
Hi @nul800sebastiaan  we are also seeing this in 7.15.2 and 7.15.3 and the rootUrl in filesystem providers is being ignored.  We are using blobstorage for the media.  Have just upgraded from 7.14

**Comment by nul800sebastiaan** [comment]
@MortenL I apologize for the late reply, this one seems to have slipped through the cracks. Maybe you will have more luck in v8.1, and can draw some inspiration from: https://github.com/umbraco-community/UmbracoFileSystemProviders.Azure/

I will quote an important part from the readme, which I think is still valid for v8:

> Also add this configuration to the web.config inside the Media folder

```xml
<?xml version="1.0" encoding="UTF-8"?>
<configuration>
	<system.webServer>
		<handlers>
			<clear />
			<add name="StaticFileHandler" path="*" verb="*" preCondition="integratedMode" type="System.Web.StaticFileHandler" />
			<add name="StaticFile" path="*" verb="*" modules="StaticFileModule,DefaultDocumentModule,DirectoryListingModule" resourceType="Either" requireAccess="Read" />
		</handlers>
	</system.webServer>
</configuration>
```

It seems to have helped someone else! I'll close this issue for now, please feel free to comment if this is not the solution for you!
