### ISSUE TITLE
V8: navigationService.executeMenuAction doesn't appear to set $scope.currentNode for dialog

### ISSUE THREAD

**Issue by mattbrailsford** [umbraco/Umbraco-CMS#5416]
When a tree menu action that opens a dialog is executed from the tree menu, the related dialogs scope contains a `currentNode` object such that it has context as to the node that created it, however it appears that triggering a menu action via `navigationService.executeMenuAction`, although you pass it the action and a node, it doesn't appear to pass through the node as the dialogs `currentNode` like the action opened via the tree would do.

`navigationService.executeMenuAction` should execute consistant with the tree menu execution workflow and so a curentNode property should be set in the dialogs scope.

**Comment by mattbrailsford** [comment]
On further investigation, it appears you have to call `appState.setMenuState("currentNode", node);` before calling `navigationService.executeMenuAction`. I don't think this is overly intuitive though. If you are calling `executeMenuAction` and you are providing it with a node context, would it not therefore dictate that the passed in node should be set as the appState current node? (if it potentially causes problems, could `executeMenuAction` at least grab the current value, set to the supplied node, execute the menu action, and then set the appState currentNode back to what it was just in case?)

**Comment by Shazwazza** [comment]
it's probably a case do to a mashing together of code from a very long time ago. If you have time for a PR i'd be happy to review. have marked up for grabs. Cheers!

**Comment by nul800sebastiaan** [comment]
This issue has been in the `up for grabs` state for quite a while now and it seems nobody is ready to pick this one up.

For now we'll close this issue to prevent the list of `up for grabs` from becoming very stale. We're happy to re-open it if someone still thinks it's good to work on this.

If anyone is about to pick this issue up to fix it, make sure to test first if you can reproduce the problem in the latest version before you start to work on it.

Thanks!
Sebastiaan on behalf of Umbraco HQ.
