### ISSUE TITLE
v8 Invited user keeps showing as "has not logged in yet"

### ISSUE THREAD

**Issue by ArnoldV** [umbraco/Umbraco-CMS#5420]
Reproduction
------------

Invite a new user to your Umbraco Backoffice, they accept the invite, login an even publish a page, but the Userview still says "Person has not logged in yet".

![umbraco-bug-invite-contentview](https://user-images.githubusercontent.com/4798968/57357974-974c0f00-7174-11e9-9ff4-6e7b1a0af6f4.PNG)
![umbraco-bug-invite-userview](https://user-images.githubusercontent.com/4798968/57357982-99ae6900-7174-11e9-86a6-894f0c4e9308.PNG)

**Comment by nul800sebastiaan** [comment]
Turns out that when they get invited and set their password, that doesn't count as a "login" but as soon as you log out and in again, the "first" login gets recorded.

I've marked this as "Up for grabs" so that you or someone else coming along could create a pull request for it.

**Comment by ArnoldV** [comment]
@nul800sebastiaan awesome, will try to fix this, should no be that hard.

**Comment by nul800sebastiaan** [comment]
Fixed in https://github.com/umbraco/Umbraco-CMS/pull/5435
