### ISSUE TITLE
V8: Selecting doc type for nested content field

### ISSUE THREAD

**Issue by mhughes4** [umbraco/Umbraco-CMS#5427]
I have created a nested content field, in single item mode, with multiple document types. When it came to adding the content, I would have expected it to have given me a choice between one of the multiple document types. Instead, it has served me an instance of the first document type. It should give me an option to choose between one of the multiple doctypes.

**Comment by kjac** [comment]
@mhughes4 Thanks for reporting 😄  

As you have no doubt gathered, Nested Content automatically adds the minimum required items using the first available item type. 

Your best bet here (at least on the short term) is to set minimum number of items to 0. That will allow your editors to pick the applicable item type. I'm looking into the problem, time will tell if it's fixable.

**Comment by kjac** [comment]
PR in #5429

**Comment by emmaburstow** [comment]
Fixed in #5429
