### ISSUE TITLE
Changes made in property settings are applied instantly

### ISSUE THREAD

**Issue by nielslyngsoe** [umbraco/Umbraco-CMS#5428]
Changes made in property settings should not be applied before "submit" has been clicked. (Would love as well to rename to 'save')
Meaning that if a change has been made and the user click "close" we should ask the user if they are sure that they dont want to save their changes.

Screenshot from the crime scene:
![image](https://user-images.githubusercontent.com/6791648/57378308-c37f8400-71a4-11e9-9743-84b6e3839ca0.png)

**Comment by kjac** [comment]
@nielslyngsoe the first part is fairly straightforward within the bounds of the current implementation:

![property-editing-v1](https://user-images.githubusercontent.com/7405322/57581348-7bb77000-74b6-11e9-956e-90f27eec0a71.gif)

Adding the confirm dialog on "Close" however means adding a whole lot of hard coded property/data validation, which is likely to be an annoyance down the road as property editing is changed or extended. It's simple to do it, it's just not nice 😄 

Thoughts?

**Comment by kjac** [comment]
As it turns out there's a really easy way around the whole thing 🤦‍♂️

Will submit a PR soon as I'm back at the keys!

**Comment by kjac** [comment]
PR in #5522
