### ISSUE TITLE
NuCache Vanishing Content (2)

### ISSUE THREAD

**Issue by zpqrtbnk** [umbraco/Umbraco-CMS#5431]
See #5222 - happening again?

**Comment by zpqrtbnk** [comment]
According to Frans:
>The same as I discussed in slack with Stephan.
>Deploy a doctype change to live and it breaks. I think Stephan still has access to this project.
restart the application locally does it to
>It seems like the update had no effect after auto updating, at least not on this site.
The DLL Stephan send me to test prior to the 8.0.2 patch worked great so I don't get it

I don't get it either. The fixes that were in that DLL are in 8.0.2. Need to look into it.

**Comment by FransdeJong** [comment]
Could it be that the temporary dll has messed up this project in any way?

**Comment by FransdeJong** [comment]
I found the problem.
If you use modelsbuilder api and use the constructor to set a property based on a variant it will break the cache.

I think it would be wise to disable the functionality of overwriting the constructor? Or at least have a warning in there? 

https://our.umbraco.com/forum/umbraco-8/97190-ancestorsorselft-returns-wrong-culture

**Comment by zpqrtbnk** [comment]
Some details from the Our thread:

If one captures a property value in a variable... what is captured is the value of the property *for the current culture*. So...

    var label = content.Label;

captures the value of the "label" property for the current culture. Because that property value is contextual. Read the Our thread for more details. To make it short: do *not* capture contextual stuff.

I think it is fine to overwrite the constructors if you have specific things to do there - just remember to be careful with what you capture.

Also... capturing another document... what happens if that document is re-published? The thing you have captured will not get refreshed, so you will have obsolete content. In v7 that was working because everything (every model) was re-created on every request. But not on v8.

So... you would want to capture the *identifier* of that other document, not the document itself.

Making sense?

**Comment by zpqrtbnk** [comment]
As per our discussions - this is not an issue anymore really. Closing.
(Blame me and reopen if needed ;-)
