### ISSUE TITLE
Umbraco.Dropdown.Flexible remains $dirty after save and publish

### ISSUE THREAD

**Issue by martinjgriffiths** [umbraco/Umbraco-CMS#5436]
Saved and Published item after changing something in the dopdown and navigated away.

Prompted of unsaved changes.

Version 7.13.2

**Comment by kjac** [comment]
I'm quite unable to reproduce this on 7.14 or 8.x ... I'm guessing it's been fixed since 7.13. @martinjgriffiths can you verify?

**Comment by nul800sebastiaan** [comment]
I also can't repro on 7.14. I'll close this for now but feel free to re-open if you have reproduction steps on 7.14.
