### ISSUE TITLE
V8: Dictionary intro paragraph needs updating

### ISSUE THREAD

**Issue by mattbrailsford** [umbraco/Umbraco-CMS#5441]
In v8 the dictionary tree has moved to the translations section, however on the edit view for a dictionary item it has an intro paragraph of:

> Edit the different language versions for the dictionary item 'vendr_store1_emailtemplate_confirmation_templateview' below
You can add additional languages under the 'languages' in the menu on the left

The bit about adding additional languages is incorrect as I think this is left over from when dictionary was in settings and shared the same tree as the languages tree. 

Anywho, this probably needs updating (given the translator may not have access to the settings section, it would probably be best to remove any reference to adding new languages)

**Comment by nul800sebastiaan** [comment]
👍 
I've marked this as "Up for grabs" so that you or someone else coming along could create a pull request for it.

**Comment by nul800sebastiaan** [comment]
Fixed in https://github.com/umbraco/Umbraco-CMS/pull/5457
