### ISSUE TITLE
Update the template after changing the document type model in U8

### ISSUE THREAD

**Issue by Baracuda011** [umbraco/Umbraco-CMS#5442]
Dear all,

Is it possible to update the template allocated to a document type after changing the name and the alias of the document type? To put it simply:

From this:
@inherits Umbraco.Web.Mvc.UmbracoViewPage<ContentModels.OldDocumentTypeModelName> 

To this: 
@inherits Umbraco.Web.Mvc.UmbracoViewPage<ContentModels.NewDocumentTypeModelName>

Thanks.

Cheers,
Nemanja.

**Comment by soreng** [comment]
well... the template assigned, could be something shared (think of an "article" template, used by "NewsStory" and "BlogPost"). There would definetly need to be some checks in place for this to make sense.

It's a nice idea, but maybe it could be "handled" by building the views of your website?

**Comment by Baracuda011** [comment]
@soreng in my case it was a home page document type/template combo which I had to change when the client decided to introduce another language. And the request was specific so it was better for me to split this to two than to introduce a lot of conditions.

**Comment by nul800sebastiaan** [comment]
I understand and appreciate the feature request @Baracuda011 but as @soreng already mentions, there's not a well-controlled link between templates and doctypes. We'll run into issues having to do regex replacing, not knowing for sure if the template inherits something, maybe you're using an alternative template, and so on. There's too many variables in play which we don't control. 

So yep, you'll have to manually correct these things unfortunately.
