### ISSUE TITLE
V8: Issue with registering auto mapper profile with same name as a core mapper profile class

### ISSUE THREAD

**Issue by mattbrailsford** [umbraco/Umbraco-CMS#5451]
In TC for v8, I have my own entity base classes and so, when it comes to mapping these to view models, I created a mapper profile class called `EntityMapperProfile` and registered this with the DI container. Everything worked, but then I noticed things like the media pickers started to break.

After looking into this, I noticed that the core also had an `EntityMapperProfile` class and so I wondered if by the fact they were named the same if this was causing a conflict. I renamed mine, and indeed this fixed the issue and the core mapper started working again.

Really then, I think there needs to be a way to register mapper profiles with the same name and have them differentiated by the namespace. Or, if this isn't possible, it should at least error and say you can't override the core mappers.

**Comment by kjac** [comment]
Hey! AutoMapper will be gone in 8.1 so that's one worry less for you 😊

**Comment by mattbrailsford** [comment]
@kjac will it? How come? What's replacing it?

**Comment by kjac** [comment]
In an effort to boost startup time it's being replaced with UmbracoMapper

**Comment by mattbrailsford** [comment]
@kjac hmm, I'm not familiar with it that much. Is it usable outside of en Umbraco context?

**Comment by kjac** [comment]
@mattbrailsford it's publicly available (`Umbraco.Core.Mapping.UmbracoMapper`). As for bootstrapping and usage I'd advise you to have a look at the source for vLatest and maybe also poke @zpqrtbnk for details.

Or you could simply choose to bundle AutoMapper with TC, that's entirely feasible too.

**Comment by leekelleher** [comment]
Cross-linking with #5087 for reference.

**Comment by mattbrailsford** [comment]
@kjac is this based on Andy Butlands UmbracoMapper? or is it a HQ developed thing?

**Comment by kjac** [comment]
@mattbrailsford it's homegrown from HQ 😄

**Comment by zpqrtbnk** [comment]
"UmbracoMapper" is a very basic mapping system where mappings have to be explicitely coded. In fact, "UmbracoMapper" is just the plumbing giving access to the custom mapping functions that people need to write. It is convenient and fast for some use cases, but in other cases people may want to use AutoMapper. This is still totally possible - only, AutoMapper does not come with Umbraco, so you would have to include it as your own dependency, and manage it.

I am going to document UmbracoMapper asap.

As for the original issue (name collision):

IIIC if you create your own `Matts.EntityMapperProfile` class and register it with
~~~~
composition.Register<Profile, Matts.EntityMapperProfile>();
~~~~

Then it collides with our own `EntityMapperProfile`, right?

What is annoying is that we merely register profiles with AutoMapper with:
~~~~
Mapper.Initialize(configuration =>
{
    foreach (var profile in _mapperProfiles)
        configuration.AddProfile(profile);
});
~~~~
Where `_mapperProfiles` is the `IEnumerable<Profile>` coming from DI. And then we use AutoMapper to map... there is no Umbraco code that I am aware of that toys with mappings.

Mmmm... need to think about this...

**Comment by nul800sebastiaan** [comment]
Thanks for the responses everyone, I saw a tweet from Matt reworking his stuff (thank you for your patience!) to not include automapper any more. I'll close this one as I don't think we'll need to spend any more time on it.

**Comment by mattbrailsford** [comment]
@nul800sebastiaan that's correct. I've completely stripped out the use of a mapper now and am doing everything manually so it's no longer an issue for me now. There is an interesting question about what this does for package devs though, given then now all either need to go manual or import they own mapper framework so could result in more issue, but I guess that's a different issue to discuss 😁
