### ISSUE TITLE
Add ability to resolve Health Checks with property types other than a text input

### ISSUE THREAD

**Issue by alanmac** [umbraco/Umbraco-CMS#5452]
Currently Health Checks only allow using one property type in the form of a text input to resolve an issue.

I would like Health Checks to allow for using a property type other than a text input to resolve a Health Check issue.

How can you help?
-------------------------------

I am working on a PR to extend resolving Health Checks to other property types, starting with a Content Picker.

This will build on another issue #5110 with an existing PR  [#1994](https://github.com/umbraco/Umbraco-CMS/pull/1994) that allows for using the Health Check text input proprety for more than just email validation.

**Comment by nul800sebastiaan** [comment]
Hey @alanmac - it's cool that you want to work on something, but can you first explain why it is you want this, what will this solve? Then we can provide some HQ feedback on your proposal to see if it's something we also want in core.

**Comment by nul800sebastiaan** [comment]
It's mostly this part I don't understand, examples would be very helpful:

> I would like Health Checks to allow for using a property type other than a text input to resolve a Health Check issue.

**Comment by alanmac** [comment]
Hi @nul800sebastiaan,

Giving some context would help for sure :smile:

I want to create a health check that prompts the user to verify that a piece of content exists for the website (e.g. a Privacy Policy). This needs a content picker to give a good experience of resolving the health check.

At the moment there is a 'Notification Email Settings' Health Check that accepts user input into a texbox. This is hardcoded in the core healthcheck dashboard as a text input that validates an email address.

@AndyButland 's PR [1994](https://github.com/umbraco/Umbraco-CMS/pull/1994) extends that default textbox to be able to be validated against any regex which makes the text input more flexible and I am building on that work to allow for another property type to be used (still defaulted to text input), if needed in the form of a Content Picker.

See attached prototype for an example of it in action.

![umbraco-privacy-health-check](https://user-images.githubusercontent.com/1780374/57628970-dfaf6680-7592-11e9-8542-83348ce9737f.gif)

**Comment by nul800sebastiaan** [comment]
Ah that is super cool! Go forth and PR! 👍

**Comment by nul800sebastiaan** [comment]
By the way, I see you're already doing this for now, but it would be best to target the PR at v8 instead of v7.

**Comment by alanmac** [comment]
Awesome, with regards to v8 - if I target it at v8 will it also get merged into a v7 release? It should merge into both fine (I've tested it with v8 also) but I need it in v7 as I plan to release a healthcheck into the Community Health Checks package that is only compatable with v7 at the moment. So I need v7 to have this Core change.

**Comment by alanmac** [comment]
@nul800sebastiaan do your [comments here](https://github.com/umbraco/Umbraco-CMS/pull/1994#issuecomment-497359327) also apply to this feature. Should I only target it for v8?

**Comment by alanmac** [comment]
I've created a V8 PR for this [#5652](https://github.com/umbraco/Umbraco-CMS/pull/5652)

**Comment by nul800sebastiaan** [comment]
Hi again @alanmac and sorry for the loooong delay. Right now, we're in the process of building v9 and we're soon shifting our focus to exclusively look at new features only for v9. 
Health checks will work quite differently for v9 and we are unfortunately currently not planning on updating the v8 health checks system any more. So I'll close this one and the related PR. Sorry we couldn't get it merged before!
