### ISSUE TITLE
Saving Members with custom properties to a different database.

### ISSUE THREAD

**Issue by ashx1** [umbraco/Umbraco-CMS#5453]
At the moment I can implement a Custom Membership Provider which can cater for saving Members to a separate database than that of the Umbraco database.

Only the default properties can be saved to a separate database using the Custom Membership Provider.

Is it possible to also save extra added properties to a separate database using the custom membership provider?

Thanks.

**Comment by nul800sebastiaan** [comment]
Hey there @ashx1 - we don't have plans to support storing custom properties in a separate database through custom membership providers. We do support the properties that are default for membership providers, as you have noticed.
You'll need to build your own membership provider and editing UI for it.
