### ISSUE TITLE
Exception running build/ps1 on v8/dev branch

### ISSUE THREAD

**Issue by deMD** [umbraco/Umbraco-CMS#5455]
When trying to build the source on my local machine I get an exception running the build.ps1 script refering to compile belle:
``` 
Exception calling "RunMethod" with "1" argument(s): "Exception calling "Build" with "0" argument(s): "Exception calling "CompileBelle" with "0"
argument(s): "Failed to build"""
At C:\Git\Umbraco-CMS\build\build.ps1:541 char:5
+     $ubuild.RunMethod($command);
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : ScriptMethodRuntimeException
```

### Steps to reproduce

- Fork the repository,
- check out the v8/dev branch
- run build.ps1 from the source folder as described in build,md

I also added the belle.log but I can't find anything specific in it.
[belle.log](https://github.com/umbraco/Umbraco-CMS/files/3176798/belle.log)

**Comment by nul800sebastiaan** [comment]
Weird stuff.. I've put a new `devDependency` in there now, see the related commit. Can you try again please @deMD ?

**Comment by deMD** [comment]
Perfect. script ran fine now. I even got more output ;)
