### ISSUE TITLE
ContentService.Saving event redirects when saving is cancelled.

### ISSUE THREAD

**Issue by CodeCheetah** [umbraco/Umbraco-CMS#5459]
Hi,

When trying to limit a number of children allowed per parent during ContentService.Saving cancel event Umbraco v7.14 tries to redirect to a non existent node with Id: 0

To reproduce I have added a delegate to ContentService.Saving event in my custom ApplicationEventHandler.

`protected override void ApplicationStarted(UmbracoApplicationBase umbracoApplication, ApplicationContext applicationContext) {
            base.ApplicationStarted(umbracoApplication, applicationContext);

            ContentService.Saving += delegate (IContentService sender, Events.SaveEventArgs<IContent> args)
            {
                foreach (var entity in args.SavedEntities)
                {
                    if (entity.Parent().Children().Where(x => x.ContentType.Alias == entity.ContentType.Alias).Any())
                    {
                        args.CancelOperation(new Events.EventMessage("Error", "User friendly error message", Events.EventMessageType.Error));
                    }
                }
            };
}`

Not sure if this has been fixed or manifested again, this has been reported in https://issues.umbraco.org/issue/U4-8147.

Any ideas?

**Comment by nul800sebastiaan** [comment]
It just doesn't look like U4-8147 was never fixed. We're happy to see a PR if you would like to work on this though! 

I've marked this as "Up for grabs" so that you or someone else coming along could create a pull request for it.

**Comment by nul800sebastiaan** [comment]
This issue has been in the `up for grabs` state for quite a while now and it seems nobody is ready to pick this one up.

For now we'll close this issue to prevent the list of `up for grabs` from becoming very stale. We're happy to re-open it if someone still thinks it's good to work on this.

If anyone is about to pick this issue up to fix it, make sure to test first if you can reproduce the problem in the latest version before you start to work on it.

Thanks!
Sebastiaan on behalf of Umbraco HQ.
