### ISSUE TITLE
v8: Use overlay as confirm when deleting user

### ISSUE THREAD

**Issue by bjarnef** [umbraco/Umbraco-CMS#5464]
When deleting a user from backoffice it shows a traditional javascript confirm, but it would be great to replace this with an overlay to keep it consistent with rest of the UI.

![image](https://user-images.githubusercontent.com/2919859/57735811-2772e280-76a6-11e9-9d52-ec7d71697dde.png)

similar to when deleting a member from listview.

![image](https://user-images.githubusercontent.com/2919859/57735948-905a5a80-76a6-11e9-91ca-d7d4fe242ec2.png)

**Comment by bjarnef** [comment]
I think it is fine to use `overlayService`, but instead of we need to define a custom view each time for the simple overlays with a title, description and button text (maybe also button style), can we then instead pass these in as parameter similar to view re-using infinite editors, e.g. "mediapicker".

e.g. 
```
var dialog = {
     view: "general",
     title: "Delete",
     buttonText: "Yes, delete",
     buttonStyle: "btn-danger",
     description: "Are you sure you want to delete?",
     submit: function (model) {
     },
     close: function() {
     }
};
```

or 

```
var dialog = {
     view: "delete",
     title: "Delete",
     description: "Are you sure you want to delete?",
     submit: function (model) {
     },
     close: function() {
     }
};
```

@nielslyngsoe maybe you have any thoughts on this?

**Comment by nul800sebastiaan** [comment]
Sound like a good idea!

I've marked this as "Up for grabs" so that you or someone else coming along could create a pull request for it.

**Comment by kjac** [comment]
I'll have a look at it 👍

**Comment by kjac** [comment]
PR in #5482

**Comment by bjarnef** [comment]
I have submitted a PR https://github.com/umbraco/Umbraco-CMS/pull/5487 which use a different approach to solve this and which I think is a bit simpler and doesn't introduce a new service. It is also possible just the omit  view or specify `view: "default"` which use default overlay, which basically just output `model.content` in the overlay.
