### ISSUE TITLE
v8: Log Viewer can Break

### ISSUE THREAD

**Issue by zpqrtbnk** [umbraco/Umbraco-CMS#5470]
As reported in [this blog post](http://tooorangey.co.uk/posts/go-figure-8/),

In some (unspecified) situations the logs can get corrupted, and then the log viewer will not display the log overview, but instead some error messages (see image). Need to understand how logs can get corrupted + in any case, should they get corrupted, return better error messages.

![image](https://user-images.githubusercontent.com/2846429/57833597-9d686e00-77ba-11e9-98f8-b682e5d74739.png)

**Comment by nul800sebastiaan** [comment]
This has been fixed already in v8.1.

This should make sure logs don't get corrupt any more: https://github.com/umbraco/Umbraco-CMS/pull/5375
And this one ignores lines it can't read: https://github.com/umbraco/Umbraco-CMS/pull/4858/

**Comment by marcemarc** [comment]
this was the error in the log file on disk that I think was causing the issue with the logs not loading:

{"@t":"2019-05-14T10:03:52.3403572Z","@mt":"Unhandled controller exception occurred for request '{RequestUrl}'","@l":"Error","@x":"Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: W. Path '', line 0, position 0.\r\n   at Newtonsoft.Json.JsonTextReader.ParseValue() in /_/Src/Newtonsoft.Json/JsonTextReader.cs:line 1706\r\n   at Newtonsoft.Json.JsonTextReader.Read() in /_/Src/Newtonsoft.Json/JsonTextReader.cs:line 419\r\n   at Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter) in /_/Src/Newtonsoft.Json/JsonReader.cs:line 1195\r\n   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent) in /_/Src/Newtonsoft.Json/Serialization/JsonSerializerInternalReader.cs:line 196\r\n   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType) in /_/Src/Newtonsoft.Json/JsonSerializer.cs:line 907\r\n   at Serilog.Formatting.Compact.Reader.LogEventReader.TryRead(LogEvent& evt)\r\n   at Umbraco.Core.Logging.Viewer.JsonLogViewer.GetLogs(DateTimeOffset startDate, DateTimeOffset endDate, ILogFilter filter, Int32 skip, Int32 take)\r\n   at Umbraco.Core.Logging.Viewer.LogViewerSourceBase.GetLogs(DateTimeOffset startDate, DateTimeOffset endDate, Int32 pageNumber, Int32 pageSize, Direction orderDirection, String 

not sure what the unexpected character was
