### ISSUE TITLE
v8: Using keyboard to cancel in modal triggers primary action

### ISSUE THREAD

**Issue by electricsheep** [umbraco/Umbraco-CMS#5478]
### Bug summary

If you have a one of the _Save and publish_ option modals open (i.e. Schedule/Publish with descendants/Unpublish) and tab so that the _Close_ button is focused, hitting Enter will trigger the primary action rather than closing the modal.

### Specifics
- Umbraco v8.1.0
- Chrome 74

![umbraco4](https://user-images.githubusercontent.com/686835/57845723-79ad2400-77ca-11e9-8661-8e3a61548df2.gif)

### Steps to reproduce

1. Open a page in the CMS
2. Expand the menu next to _Save and publish_
3. Click _Unpublish_
4. Tab to the _Close_ button on the modal
5. Hit Enter key

### Expected result

The modal is closed without unpublishing

### Actual result

The page is unpublished

**Comment by kjac** [comment]
Yeah... this is annoying. PR #5463 aims to solve it.

**Comment by kjac** [comment]
And also #5461 which fixes the unintentional triggering of the secondary action in "Unsaved changes"

**Comment by nul800sebastiaan** [comment]
Ah looks like these are both fixed now, just forgot to close the issue! :)
