### ISSUE TITLE
U8 Macros alphabetical order

### ISSUE THREAD

**Issue by Baracuda011** [umbraco/Umbraco-CMS#5485]
Dear all,

Can you please update the list of macros in the dashboard to be displayed alphabetically? It would also be very useful and would improve overall UX if you can group macros into folders.

Thank you.

Regards,
Nemanja.

**Comment by nul800sebastiaan** [comment]
Hey there @Baracuda011 - can you be a bit more specific where you see this list of macros? And where in the interface do you want them to be grouped in folders? Screenshots would help.

FYI: macros are a bit old-fashioned these days and are mostly only useful when putting blocks of functionality in  rich text editors. I'd recommend you think about why you need many macros and if there's not a better / easier way to achieve what you're trying to do. Make sure to look for some advise for this on the forum at https://our.umbraco.com as well.

**Comment by kjac** [comment]
@nul800sebastiaan looks like it's the macros tree:

![image](https://user-images.githubusercontent.com/7405322/58366808-1e6ce700-7ed8-11e9-96bb-e3da73866549.png)

I'll get right on it.

**Comment by kjac** [comment]
PR in #5520

**Comment by nul800sebastiaan** [comment]
@Baracuda011 I think grouping them into folders is currently a step too far but getting them organized alphabetically is a good update. I am still quite curious for a good use-case where you have so many macros that you need folders for them though.

**Comment by Baracuda011** [comment]
@nul800sebastiaan it might not be the case of having that many macros. I am currently working on an enterprise level eCommerce website and would like to organize my macros ie. related to users, products, content elements, etc. Just to have them grouped. I think this will improve overall UX from both development and content management perspective.
