### ISSUE TITLE
v8: Gap left to actions button

### ISSUE THREAD

**Issue by bjarnef** [umbraco/Umbraco-CMS#5489]
After some of the latest changed the actions menu button now have a gap left to button, which one will notice when the button and pushed (active state).

![image](https://user-images.githubusercontent.com/2919859/57969095-262a0a00-7973-11e9-8bda-818c6047f660.png)

**Comment by bjarnef** [comment]
Not sure if `.umb-button` be default should have margin-left.

Maybe it is enough adding `.umb-editor-footer .umb-button { margin-left: 5px; }`

**Comment by nul800sebastiaan** [comment]
Oh no! Maybe @nielslyngsoe can give some guidance, but it would be great if you could create a quick PR when you have a moment? :-D

**Comment by nielslyngsoe** [comment]
Hi @bjarnef 

I would love to see your take on this one, if you have time to present a solution it would be nice. Cause as your issue states, there is definitely a problem with the usage of margin-left.

Thanks

**Comment by rolsendk** [comment]
PR https://github.com/umbraco/Umbraco-CMS/pull/5718
