### ISSUE TITLE
Retreat: Hot topic slack integration test

### ISSUE THREAD

**Issue by emmaburstow** [umbraco/Umbraco-CMS#5496]
Test for hot topic slack integration

**Comment by lssweatherhead** [comment]
This is going to be a hot topic

**Comment by lssweatherhead** [comment]
Everyone will be talking about it

**Comment by LottePitcher** [comment]
I have some pretty strong views about this topic

**Comment by lssweatherhead** [comment]
I don't know... I think mine and stronger

**Comment by LottePitcher** [comment]
> 
> 
> Everyone will be talking about it

You're probably right

**Comment by LottePitcher** [comment]
@lssweatherhead you know, the more I think about it, I think we both have a valid view point

**Comment by lssweatherhead** [comment]
I'm glad that we agree. Very hot!

**Comment by LottePitcher** [comment]
Agreed!  Hot all round

**Comment by LottePitcher** [comment]
#cgrumours this is going to make the keynote

**Comment by LottePitcher** [comment]
we should really ask the rabbit for its feedback

**Comment by LottePitcher** [comment]
one more for good measure ;-)

**Comment by poornimanayar** [comment]
may be we should get cgtrump to talk about it
