### ISSUE TITLE
Make it possible to do sorting on a mobile device (touch)

### ISSUE THREAD

**Issue by mzajkowski** [umbraco/Umbraco-CMS#5499]
Sorting of the content nodes is not possible on the mobile devices.

It's currently tested only on 7.7.13.

Reproduction
------------

Open Umbraco backoffice on a mobile device (Android Smartphone tested so far) and try to sort content nodes for the specific parent page.

Touch events are not handled? Sorting is not possible.

**Comment by nul800sebastiaan** [comment]
This has never been a feature to be honest. We won't be fixing this in v7 since that code is pretty old webforms stuff. In v8 this is nicely Angularized so we could have it fixed there.

I've marked this as "Up for grabs" so that you or someone else coming along could create a pull request for it.

**Comment by kjac** [comment]
@mzajkowski seems sorting works in V8 on a device - at least when emulating it:

![device-sort](https://user-images.githubusercontent.com/7405322/58756886-e92c4e80-8500-11e9-9bb3-52cf41e059d2.gif)

**Comment by nul800sebastiaan** [comment]
Seems to work on my (android) device as well. I'll close this for now.
