### ISSUE TITLE
Member Edit - Member Groups - Ordered Alphabetically v7

### ISSUE THREAD

**Issue by Geckex** [umbraco/Umbraco-CMS#5507]
Editing a member - Properties tabs - 
"Not a member of group(s)" and "Member of group(s)" - both lists are in order of node sort order.
More helpful for users to have in alphabetical order.
Saw related issue: U4-10027 - but appears not fixed (version 7.12.4)

**Comment by nul800sebastiaan** [comment]
Fixed in #5508
