### ISSUE TITLE
Content Cache stale after Publishing

### ISSUE THREAD

**Issue by jsmilovic** [umbraco/Umbraco-CMS#5510]
I'm hooking into the Published Event and having to publish content twice in order to get the data due to the content cache being stale.

Reproduction
------------

To reproduce this bug you should 
1.  Create an ApplicationEventHandler
2.  Subscribe to the Published Event
3.  Add some code to pull the content from the content cache e.g.                  ```IPublishedContent content= umbHelper.TypedContent(item.Id); ```
5.  Publish some sample content.
6.  Add a breakpoint to your handler so that you can examine the properties
7.  Make a change to your content 
8. Observe when your breakpoint fires you get back the old content
9.  Publish again and observe this time your content is updated.

This is happening for Umbraco 7.13.1.

Some sample code

```
    public class onPublishFinishedEventHandler : ApplicationEventHandler
    {
        ICMSPublishedService handlePublishService;

        public onPublishFinishedEventHandler()
        {
            // Register the onPublish event
            ContentService.Published += published;
        }

        private void published(IPublishingStrategy sender, PublishEventArgs<IContent> args)
        {
            //umbraco.content.Instance.RefreshContentFromDatabase();

            var umbHelper = new UmbracoHelper(UmbracoContext.Current);

            foreach (var item in args.PublishedEntities) {
                IPublishedContent content= umbHelper.TypedContent(item.Id);
            }
        }
```
I did try adding ```umbraco.content.Instance.RefreshContentFromDatabase();``` and I feel like this worked in the past, however it is definitely not working now, I am still getting stale content from the previous version.

**Comment by nul800sebastiaan** [comment]
Please don't use `umbraco.content.Instance.RefreshContentFromDatabase();` 🙏  :-)

You can't get the content like that yet, instead make sure to get the new property values from the `item` object, for example to get the `bodyText` property:

`var body = item.Properties.Where(x => x.Alias == "bodyText");`

For more help with specific usecases, make sure to head on over to [the forum](https://our.umbraco.com/) where our friendly community can help you out!
