### ISSUE TITLE
v8: misleading documentation of editorService.open

### ISSUE THREAD

**Issue by JoseMarcenaro** [umbraco/Umbraco-CMS#5514]
v8 API documentation when describing the editorService.open() service incorrectly states:

`@param {String} editor.size Sets the size of the editor ("Small"). If nothing is set it will use full width.`

when actually "Small" does nothing, but "small" (lowercase) does.

This should be fixed in umbraco.services.js - near line 2207
Thanks!

**Comment by AndyButland** [comment]
This should already be fixed I think - from [this PR](url).

**Comment by nul800sebastiaan** [comment]
Your link is quite.. blank @AndyButland 😅

I think you meant to link here: https://github.com/umbraco/Umbraco-CMS/pull/4926

So yep, this is fixed in the upcoming 8.1.0 @JoseMarcenaro - thanks for reporting! 👍
