### ISSUE TITLE
Allow passing editorData (aka dialogData) to editorService.open

### ISSUE THREAD

**Issue by JoseMarcenaro** [umbraco/Umbraco-CMS#5515]
The v8 editorService is a great replacement for dialogService, built from scratch to be used all over the backoffice and allowing infinite editing.

There is one feature, though, that seems to have been lost in the trade: the option to pass custom data (formerly 'dialogData') to the overlay controller.

Unless there is a way to do this (I didn't found it) and **if you find this feature useful** I can gladly submit a PR - it only requires adding one line in umbraco.controller.js:

Before:
```
// event for infinite editors
evts.push(eventsService.on('appState.editors.open', function (name, args) {
    $scope.infiniteMode = args && args.editors.length > 0 ? true : false;
}));
```

After:
```
// event for infinite editors
evts.push(eventsService.on('appState.editors.open', function (name, args) {
    $scope.infiniteMode = args && args.editors.length > 0 ? true : false;
    $scope.editorData = args && args.editor ? args.editor.editorData: null;
}));
```

**Comment by nul800sebastiaan** [comment]
Sounds like it could be useful, do you have a simple example (without mentioning code, just a "when I click this wouldn't it be great if "X" happened)? I'm not personally very familiar with the editorService, so I am not sure how it's used, paint me a picture :-)

I'll put this on the list to discuss with the team at HQ soon to see if this a feature we indeed want, I'll let you know what came out of that.

**Comment by JoseMarcenaro** [comment]
The use case is the following:
When developing a backoffice plugin or custom property editor, you sometimes need to open a custom dialog to show some detail information or perform a selection.

In v7, the dialogService is very useful for doing that. It allows you to pass  to the target controller a **model** of what you need to show or select using the `.dialogData` property in the dialogService service.

In v8 the dialogService is gone and we welcome the powerful editorService, which is great ... but lacks that specific feature. There is no way (or I couldn't find one) to pass a custom model to the target controller.

NOTE: a different way of showing the dialog would be using an  `umb-overlay` directive... but it requires more code and it doesn't play nice with the infinite editing. In particular: if you call the editorService inside your overlay, closing the editor dialog closes the overlay as well.

**Comment by abjerner** [comment]
@JoseMarcenaro the entire object you pass along to the `editorService.open` method is accessible through the controller via `$scope.model`.

Eg. with

```js
editorService.open({
    size: "small",
    view: "/App_Plugins/Skybrud.Umbraco.Redirects/Views/Dialogs/Add.html",
    example: { test: true },
    submit: function (value) {
        editorService.close();
    }
});
```

you'll be able to call `$scope.model.example.test` to get my example boolean value.

Isn't this what you're looking for, or are you describing something else?

**Comment by JoseMarcenaro** [comment]
@abjerner - That is exactly what I was looking for!   Thanks a lot.

@nul800sebastiaan - please disregard this proposed feature. It makes no sense if the functionality is already there.

**Comment by John-Blair** [comment]
Glad you raised this issue....i was wondering the exact same thing about dialogData.
