### ISSUE TITLE
V8 - Configurable editorService width

### ISSUE THREAD

**Issue by jerpenol** [umbraco/Umbraco-CMS#5516]
Hi,

I have a custom grid and my gridcontrols make use of infinite-editing. It works perfectly except for one thing: I can only open new overlays "full-width" or "small" and nothing in between. 

I would expect to be able to configure the width of a new overlay myself. I see multiple ways to solve this problem (neither of which are currently possible):
1. Add a 'medium' CSS class (or even more variants like 'large'), instead of only small
2. Use what the umb-editor directive is doing and allow us to set the ng-style. 
3. Allow us to inject CSS classes

The pros and cons are:
- **For solution 1**: The pros are that this is relatively easy to achieve and it creates a standardized set of sizes (large, medium and small). The con is that there is no "one size fits all", everyone expects these sizes to be different.
- **For solution 2**: The pros are that this is relatively easy aswell (only a small angular change in the directive template) and very flexible. The con is that it breaks the separation of styling and code/html.
- **For solution 3**: The pro in this case is that it gives us alot of flexibility in styling (even better so than _solution 2_).  There's not really a con here, but there are multiple ways of implementing this solution, for example: single string V.S. string array.

I would love a fix for this. My opinion is that a combination of all would be the solution to this problem, so it's suitable for every usecase. 

I'd like to get everyone's opinion on this, so we can create a PR for this.

**Comment by nul800sebastiaan** [comment]
Hey @jerpenol - thanks for the feature request, I understand where it's coming from but I believe this was a conscious choice we made so as not to make things jump around too randomly. I've not personally been involved in those talks though but I expect the current behavior to stay the way it is.

However, I will have a chat with the team at HQ and see what they think and get you some more feedback on this issue. I'll update when I know more! 👍

**Comment by jerpenol** [comment]
Hi @nul800sebastiaan.
Supertak! I'll await their feedback.

**Comment by nul800sebastiaan** [comment]
Hi again @jerpenol - we had a little chat about this and we need some extra detail on what the problem is that this would solve for you. There's a few solutions in your feature request but we're not sure what problems they are solving?

**Comment by jerpenol** [comment]
Hi @nul800sebastiaan , 

My problem is that I want to have overlays for my custom gridcontrol, but they don't need to be full-width all the time. 

When I know that I am not going to have more than 2 overlays stacked unto eachother, I do not want them to be full-width or both small. In this case I would like an option to open a medium overlay and a small one, so the user still has the "infinite editing feel" without covering my whole page with overlays. 

In addition, I think that not all overlays require the same amount of space, for example when an overlay only has a title-field it is a completely different world compared to a grid. When I have 3 overlays with only a title-field, stacked unto eachother I do not want 3 "small" overlays, because I want the infinite editing feel. In that case the only other option (now) is full-width, which is quite an exaggerated width for only a title-field.

For these reasons I would like to be able to customize the width of these overlays in any or all of the above-mentioned ways.

I hope this explanation does suffice.

**Comment by nul800sebastiaan** [comment]
We've just accepted a contribution for v8.3.0 which will allow you to open a medium panel! https://github.com/umbraco/Umbraco-CMS/pull/6808

**Comment by jerpenol** [comment]
Awesome! @nul800sebastiaan
