### ISSUE TITLE
v8 - can't create member in 8.1

### ISSUE THREAD

**Issue by AndyButland** [umbraco/Umbraco-CMS#5518]
Working with the latest in `v8/dev` branch, so targeting 8.1, found I can't create a member record.  Looks to be because member properties are indicated as supporting variation by culture.

I.e. the `Variations` field in `cmsPropertyType` for all properties with alias starting with `umbracoMember...` is 1.

Looking at `PropertyTypeDto` this value is set to be the default - but the comment seems to indicate that it should actually be 0:

```
    [Column("variations")]
    [Constraint(Default = "1" /*ContentVariation.InvariantNeutral*/)]
    public byte Variations { get; set; }
```
(`ContentVariation.InvariantNeutral` doesn't actually exist, but I suspect that's just a comment getting out of date which is now renamed to `ContentVariation.Neutral`).

So seems to me either:

1. These fields should be non-varying, and needs a migration to fix up the data, or
2. When these properties are saved - e.g. in the setter or `Umbraco.Core.Models.Member.IsApproved`, a culture - "en-US"? - needs to be passed.

**Comment by kjac** [comment]
@AndyButland I can't reproduce 😕 how does the error manifest on your end?

This is me creating a member on the latest v8/dev:

![create-member](https://user-images.githubusercontent.com/7405322/58366770-94248300-7ed7-11e9-9b68-b842a7241943.gif)

**Comment by AndyButland** [comment]
Like this - immediately on clicking the "Create" link (I don't get the form come up at all).

![image](https://user-images.githubusercontent.com/1993459/58366955-6b04f200-7ed9-11e9-9795-a6cfefd7439b.png)

Maybe something up with my local installation though if it's OK for you.

**Comment by kjac** [comment]
Crikey! That looks bad 😞 

Did you add custom properties to the member type?

**Comment by AndyButland** [comment]
No, just using the default "Member" member type.

I think I'll try with a clean clone.  Been updating this installation for years and perhaps something has got out of sync.  Will report back if it still seems to be an issue.

**Comment by AndyButland** [comment]
Will close this.  It's fine with a new install and the `variations` fields is 0 as expected.  Not sure what happened with my local copy - _maybe_ there's an issue somewhere around migrations but probably just something specific to the changes I've made locally.

Sorry for disturbing your Saturday morning @kjac!

**Comment by kjac** [comment]
Whoo 🎉

No worries I was bored on the train anyway 😀
