### ISSUE TITLE
V8 - Add Culture as a param in the contentpicker

### ISSUE THREAD

**Issue by Mivaweb** [umbraco/Umbraco-CMS#5527]
A brief description of your feature request goes here.

I am using the editorservice => contentpicker in another section then the content ( eg Members section ) for a package. Now when I open the contentpicker, it is displayed in the current selected culture. Can we add a possibility to open the contentpicker in another culture then the selected one by passing it as a param? Or can we do this in another way?

**Comment by nul800sebastiaan** [comment]
It's an interesting feature request! I'll have to discuss it at HQ soon, I'll let you know when I have an update.

**Comment by Mivaweb** [comment]
Some info on this as documentation when looking into the source code. The editorservice has a **Contentpicker** which uses the **Treepicker** view.

Steps to do:

1. Create a new Param on the editorservice to pass to the treepicker
2. Create a new Param on the treepicker to set the passed in culture language
3. Inside the treepicker we need to check if we are on the **Content** section before we do anything with the passed culture. Other sections aren't culture specific I guess?
4. We need to lookup and validate the passed in culture to see if it exists and its active in the umbraco backoffice

Will test this out and make a PR already as a reference for this feature.

**Comment by Mivaweb** [comment]
PR can be found here: https://github.com/umbraco/Umbraco-CMS/pull/5570

**Comment by rsoeteman** [comment]
Hope this can be added to the core. For my extension I want to pick a locale specific 404 page. The user expects it to be in Dutch but can only pick the English version and can only hope the Dutch version exists.

**Comment by nul800sebastiaan** [comment]
Just stumbled upon this older issue, this works as expected now, if the node is available also in the language you're working in, you will pick the localized node.
