### ISSUE TITLE
V8 - Install local package gives error: incorrect version

### ISSUE THREAD

**Issue by Mivaweb** [umbraco/Umbraco-CMS#5528]
When you create a package in V8 and set a version in the format: **v2.0.0** you will get an error when trying to install this package because of invalid version.

You need to use the format **2.0.0**.

In V7 this was valid, so no problem to change to the new way but maybe you can set a placeholder with an example of the correct format for the version field on the create package page?

**Comment by nul800sebastiaan** [comment]
It would be awesome to have a restriction / validation on the version number you can type in that box. 
Maybe a simple regex for the format `1.2.3` would be enough?

I've marked this as "Up for grabs" so that you or someone else coming along could create a pull request for it.

**Comment by Mivaweb** [comment]
Yes that will do. Setting a Regex for both **Version** and **UmbracoVersion** properties using regex: `^(\d+\.)?(\d+\.)?(\*|\d+)$`. PR will follow.

**Comment by Mivaweb** [comment]
PR can be found here: https://github.com/umbraco/Umbraco-CMS/pull/5559

**Comment by nul800sebastiaan** [comment]
Fixed in https://github.com/umbraco/Umbraco-CMS/pull/5559
