### ISSUE TITLE
Latest 7.x version on Azure Web App

### ISSUE THREAD

**Issue by cfelicio** [umbraco/Umbraco-CMS#5529]
Hi There,

On https://github.com/umbraco/Umbraco-Azure-Gallery

The latest release available is 7.12. Are there any plans to release 7.14? 

Thanks,
Carlos

**Comment by nul800sebastiaan** [comment]
Hi @cfelicio - no plans at the moment, we're planning to release version 8.1.0 there soon instead. :)
