### ISSUE TITLE
v8: Saving a user with no groups fails validation, but no message is displayed

### ISSUE THREAD

**Issue by AndyButland** [umbraco/Umbraco-CMS#5534]
When saving a user in the back-office, if all groups are removed, the save correctly fails validation, but no message is displayed (a 400 error is visible in dev tools with the appropriate error information).

**Comment by AndyButland** [comment]
PR [here](https://github.com/umbraco/Umbraco-CMS/pull/5535).

**Comment by nul800sebastiaan** [comment]
Fixed in: https://github.com/umbraco/Umbraco-CMS/pull/5535
