### ISSUE TITLE
V 7.14.0 - MemberService is not saving any custom member properties

### ISSUE THREAD

**Issue by SaraFantinato** [umbraco/Umbraco-CMS#5537]
It seems that only when you fill the additional custom fields of a member from the back-end (section Member), the changes are saved correctly.
Instead, when you try to fill the fields form the front-end (Partial View created from the snippet), and then click on the button to submit the form, the changes are not saved at all.

Reproduction
------------

### Specifics

* Using Umbraco 7.14.0
* Using either Mozilla Firefox (67.0) or Google Chrome (74.0.3729.169)

#### Member Section
* Create a **new MemberType** called e.g. "MemberWebsite"
* add another tab (e.g. "Extra infos")
* add a **new property** (e.g. "company") with simple "Textstring" Editor
* mark both Options "Show on member profile" and "Member can edit"
* Save the new MemberType
#### Settings Section
* Create a new Template (e.g. "registration page")
* Create a new Partial View from snippet, choose "Register Member" snippet, and call it e.g. "member sign up"
* Specify the custom member type alias "MemberType" in the constructor:
```
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage


@using System.Web.Mvc.Html
@using ClientDependency.Core.Mvc
@using Umbraco.Web
@using Umbraco.Web.Controllers

@{
    @*
        You can specify a custom member type alias in the constructor, the default is 'Member'    
        for example, to use 'Custom Member' you'd use this syntax:
    
        var registerModel = Members.CreateRegistrationModel("Custom Member");
    *@
    
    var registerModel = Members.CreateRegistrationModel("MemberWebsite");
    
    @*
        Configurable here:           
    
        registerModel.RedirectUrl       - Optional. What path to redirect to if registration is successful. 
                                          By default the member will be redirected to the current umbraco page 
                                          unless this is specified.
    
        registerModel.UsernameIsEmail   - the default is true
                                          if you want the username to be different from the email
                                          address, set this to true and add a new Username field in
                                          the form below
    
                                          @Html.LabelFor(m => registerModel.Username)
                                          @Html.TextBoxFor(m => registerModel.Username)
                                          @Html.ValidationMessageFor(m => registerModel.Username)
    *@
  
    Html.EnableClientValidation();
    Html.EnableUnobtrusiveJavaScript();
    Html.RequiresJs("/umbraco_client/ui/jquery.js");
    Html.RequiresJs("/umbraco_client/Application/JQuery/jquery.validate.min.js");
    Html.RequiresJs("/umbraco_client/Application/JQuery/jquery.validate.unobtrusive.min.js");
    
    var success = TempData["FormSuccess"] != null;
}

@*NOTE: This RenderJsHere code should be put on your main template page where the rest of your script tags are placed*@
@Html.RenderJsHere()

@if (success) 
{ 
    @* This message will show if RedirectOnSucces is set to false (default) *@
    <p>Registration succeeded.</p>
}
else
{
    using (Html.BeginUmbracoForm<UmbRegisterController>("HandleRegisterMember"))
    {
        <fieldset>
            <legend>Register Member</legend>

            @Html.ValidationSummary("registerModel", true)

            @Html.LabelFor(m => registerModel.Name)
            @Html.TextBoxFor(m => registerModel.Name)
            @Html.ValidationMessageFor(m => registerModel.Name)
            <br />

            @Html.LabelFor(m => registerModel.Email)
            @Html.TextBoxFor(m => registerModel.Email)
            @Html.ValidationMessageFor(m => registerModel.Email)
            <br />

            @Html.LabelFor(m => registerModel.Password)
            @Html.PasswordFor(m => registerModel.Password)
            @Html.ValidationMessageFor(m => registerModel.Password)
            <br />

            @if (registerModel.MemberProperties != null)
            {
                @*
                    It will only displays properties marked as "Member can edit" on the "Info" tab of the Member Type.
                *@
                for (var i = 0; i < registerModel.MemberProperties.Count; i++)
                {
                    @Html.LabelFor(m => registerModel.MemberProperties[i].Value, registerModel.MemberProperties[i].Name)
                    @*
                        By default this will render a textbox but if you want to change the editor template for this property you can
                        easily change it. For example, if you wanted to render a custom editor for this field called "MyEditor" you would
                        create a file at ~/Views/Shared/EditorTemplates/MyEditor.cshtml", then you will change the next line of code to
                        render your specific editor template like:
                        @Html.EditorFor(m => profileModel.MemberProperties[i].Value, "MyEditor")
                    *@
                    @Html.EditorFor(m => registerModel.MemberProperties[i].Value)
                    @Html.HiddenFor(m => registerModel.MemberProperties[i].Alias)
                    <br />
                }
            }

            @Html.HiddenFor(m => registerModel.MemberTypeAlias)
            @Html.HiddenFor(m => registerModel.RedirectUrl)
            @Html.HiddenFor(m => registerModel.UsernameIsEmail)

            <button>Register</button>
        </fieldset>
    }
}
```
* Insert the new Partial View "member sign up" in the body of the Template "registration page"
#### Content Section
* Create a new node/page, with the template "registration page" assigned
* save and publish the node

### Steps to reproduce - front-end
* Navigate the website to the new sign up page
* fill all the standard fields:
  - Name
  - Email
  - Password
* and the custom field:
  - company (e.g. "GreenCompany")
* Click on "Register" button

#### Member Section
The new member created has the "company" field filled with the value "GreenCompany". 

#### Member Section
The new member created has the "company" field that is empty. The value was not saved correctly. 

## Notes
- only the standard fields (Name, Email, Password) are saved correctly
- this happens also with the "Edit Profile" snippet

**Comment by skartknet** [comment]
Hi @SaraFantinato , I have followed your instructions and I couldn't replicate the issue. I get my company populated properly. Are you getting any error messages when you submit?

**Comment by SaraFantinato** [comment]
Hi @skartknet, thanks for responding so quickly.
Unfortunately I don't get any kind of error, therefore I don't know what's wrong.

I tried on a clean installation of Umbraco 7.14.0.

### Steps
- navigate to the registration page (just created like I explained on my previous post, but set as root page this time)
- delete all txt files in the /App_Data/Logs folder
- fill in all the fields on the registration page, and click on register button

### Results
- the message "Registration succeeded." appears
- the new member is created, but again with "company" field blank 

On the browser Web Developer Console (using Mozilla Firefox), in the network tab I see that the company field value is passed correctly like the other parameters (see screenshot here below)

![MemberWebsite](https://user-images.githubusercontent.com/51127049/58541408-c0a00e00-81fb-11e9-8931-018c4608481a.JPG)

Also, there's no new txt log file in the /App_Data/Logs folder.

I've done everything by the book and I really don't know what to do to get this working 😞

**Comment by skartknet** [comment]
This is the method that handles the submission:

 ```
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult HandleRegisterMember([Bind(Prefix = "registerModel")]RegisterModel model)
        {
            if (ModelState.IsValid == false)
            {
                return CurrentUmbracoPage();
            }

            // U4-10762 Server error with "Register Member" snippet (Cannot save member with empty name)
            // If name field is empty, add the email address instead
            if (string.IsNullOrEmpty(model.Name) && string.IsNullOrEmpty(model.Email) == false)
            {
                model.Name = model.Email;
            }

            MembershipCreateStatus status;
            var member = Members.RegisterMember(model, out status, model.LoginOnSuccess);
            
            switch (status)
            {
               //check the different status
            }
        }
```

You could try to create your own SurfaceController and include that method then submit to that and check if everything is correct.

I have copied your code so everything in the form is correct. You must be missing something.

**Comment by SaraFantinato** [comment]
This is very strange. I only used the snippet code provided by default. 
I just changed the type of the registerModel, as suggested:
```
@*
     You can specify a custom member type alias in the constructor, the default is 'Member'    
     for example, to use 'Custom Member' you'd use this syntax:
    
     var registerModel = Members.CreateRegistrationModel("Custom Member");
*@
    
var registerModel = Members.CreateRegistrationModel("MemberWebsite");
```
Thanks for the tip of creating my own SurfaceController, but I rather avoid doing that and I would like to use the standard features of Umbraco. So when I'll want to upgrade Umbraco to the latest version, I'll be able to do it, without losing any changes made of the source code.

What I don't understand is why these Umbraco standard features aren't working for me.
I'm using a live version of Umbraco 7.14.0, installed on a website hosted on a Windows Server. But this problem of failed saving member properties was happening also in previous Umbraco versions e.g. 7.13.2, or 7.10.4. I was hoping that in the latest version it would have been fixed.

How did you manage to get this done? 

> 
> 
> Hi @SaraFantinato , I have followed your instructions and I couldn't replicate the issue. I get my company populated properly. Are you getting any error messages when you submit?

**Comment by skartknet** [comment]
The idea of creating the surface controller is only for testing to figure out what's wrong.  Once you find the problem you can go back to using the other controller. 
I don't think the wrong in using your own controller though. 
Anyways, I think you should close this ticket,  because it doesn't look an issue with Umbraco, and ask for the in the forum instead.

**Comment by SaraFantinato** [comment]
Ok @skartknet, thanks for your replies. I'll try to figure it out with a new surface controller to see it I can find and fix the problem.
Since I was using only the standard snippets I thought it was some kind of Umbraco bug, so I opened this ticket. If you are able to correctly save the custom properties, the problem seems to be presenting only to me, unfortunately.
I already written a post on the forum, let's see if someone has encountered the same problem and can help me.
Thanks again.

**Comment by akeilox** [comment]
@SaraFantinato it has been a while but I am wondering if you eventually figured out a solution? Experiencing similar issue.
