### ISSUE TITLE
v8: IAuditService.GetLogs() throws SQL exception

### ISSUE THREAD

**Issue by PerplexDaniel** [umbraco/Umbraco-CMS#5542]
### Description
`IAuditService.GetLogs()` throws an SQL exception

### Steps to reproduce

1. Run this code:

```cs
// Inject IAuditService
IAuditService auditService;

var logs = auditService.GetLogs(AuditType.Publish).ToList();
```

### Expected result

Get list of Publish log items.

### Actual result

Throws exception:

> Conversion failed when converting the nvarchar value 'Save' to data type int.

### Umbraco version
Umbraco 8.0.2

**Comment by skartknet** [comment]
The `LogHeader` property has an incorrect value of `nvarchar` in the table, it should be int. Same for the property in the `LogDto`. I have created a PR but it will still need some job as the `umbracoLog` table needs to change. Some advise from HQ will be needed.

**Comment by PerplexDaniel** [comment]
Related to #5268

**Comment by nul800sebastiaan** [comment]
Cool, thanks @skartknet !

I see we have this one on our backlog as well, but not sure what state it is in. I'll have a chat at HQ to see what we plan to do here and will let you know what came out of that.

**Comment by nul800sebastiaan** [comment]
The update as proposed in https://github.com/umbraco/Umbraco-CMS/issues/5268 should fix this, so I'll close this issue as a duplicate. Thanks!
