### ISSUE TITLE
Number of active installs

### ISSUE THREAD

**Issue by soreng** [umbraco/Umbraco-CMS#5543]
Umbraco.com says that the number of active installs is 502,567, but the github says "used by more than 400.000 websites". While it is correct (502.567 is more than 400.000), couldn't we get is changed to "more than 500.000 websites" now?

**Comment by nul800sebastiaan** [comment]
Definitely! 

Care to create a quick PR for that one to the readme? 👍

I've marked this as "Up for grabs" so that you or someone else coming along could create a pull request for it.

**Comment by soreng** [comment]
I would love to Seb, but this is not part of the repo, but settings in github :-)

(There is an edit button next to the text for ppl with access)

**Comment by nul800sebastiaan** [comment]
Gotcha! I was thinking about the readme. In that case.. all fixed now! ;-)

**Comment by nul800sebastiaan** [comment]
![image](https://user-images.githubusercontent.com/304656/58782336-945f0580-85de-11e9-91b7-30b28d897093.png)
