### ISSUE TITLE
Feature - UDIs in list views should be converted to something more logical

### ISSUE THREAD

**Issue by pcharb** [umbraco/Umbraco-CMS#5545]
When adding a custom property to a listview, In this case a node picker, the displayed text is the umbId - > umb://document/e853bf611ba243bfb23fa2105d119614. 

The error occurs on line 17978 in Umbraco.Controller.js.

```
if (typeof value === 'undefined') {
     value = getCustomPropertyValue(alias, result.properties);
 }
```

The function does its work, but that type of information (umbId) is errelevant for the user. 

REndering example : 
![image](https://user-images.githubusercontent.com/1386693/58590176-85b8cd00-8231-11e9-874d-975c3bc82a75.png)

**Comment by skartknet** [comment]
This might help: https://stackoverflow.com/questions/35683461/display-content-picker-property-in-listview-umbraco-v-7-4

**Comment by stherm** [comment]
@skartknet I'm not sure that i unerstand the solution, i did not found the "GatheringNodeData" method in V8. Do you know if there is an angular method to get a node name from uid?

**Comment by skartknet** [comment]
You're right, sorry, that link is not relevant to this. I have looked into the code and the property values are just the raw ones so that's what is stored, it would be good to return the name of the page or the media instead if the value is a UID.

**Comment by nul800sebastiaan** [comment]
For now, you'd have to create a custom listview layout to show exactly what you need in the list. 

It would be really good if `getCustomPropertyValue` would convert a UDI to at least the node name.

I've marked this as "Up for grabs" so that you or someone else coming along could create a pull request for it.

**Comment by stherm** [comment]
Thank you. For now I've done it with a custom layout. Gonna try to fix it when I have some free time :).

**Comment by nul800sebastiaan** [comment]
Additionally, as mentioned in #6385 - it would be good to have UDIs for media items show a thumbnail, (or the media item title depending on the chosen view!).

**Comment by hfloyd** [comment]
So, I noticed that Listviews now have a Template option:

![image](https://user-images.githubusercontent.com/1252593/71370939-84f4d900-257d-11ea-8f06-a05de25b8668.png)

Does anyone know what the syntax would be to show the name for a linked content node or media node?

**Comment by skttl** [comment]
You can use the same filters as in Nested Content, so for UDI to name conversions, you can use ncNodeName

**Comment by Shazwazza** [comment]
Just be aware that doing that will cause an http request for every row displayed in the list view.

**Comment by fbenyah** [comment]
This is awesome @skttl really helpful.

I have tried as suggested with ncNodeName but didn't seem to work in the list view. Must this still be merged into 8.5.4?

I am assuming for MNTP one will have to select the item say [0] to show so not to fussed about that but CP should be exactly as NC template right

![ListView Template](https://user-images.githubusercontent.com/4104988/76060406-e37d0100-5f89-11ea-89d6-64facbb38fea.JPG)

**Comment by skttl** [comment]
Hi @fbenyah 

Your templates should read `{{ value | ncNodeName }}`

**Comment by fbenyah** [comment]
Thanks for getting back to me @skttl 

I might be missing something but 'contentPicker' is the property holding the value for the content picker and 'multinodePicker' is the property holding the value for MNTP

![image](https://user-images.githubusercontent.com/4104988/76089517-789bec00-5fc2-11ea-966f-3d28aad15738.png)


This works for NC when the property holding the value of the picker is piped to ncNodeName

How is this different? Thanks for assisting.

**Comment by skttl** [comment]
Hi @fbenyah, this is because in Nested Content you need to specify which property on the node you want to transform.

In list views you only have the property on the column you are transforming, so its value is put in the `value` variable.

**Comment by fbenyah** [comment]
Thanks @skttl much appreciated

**Comment by ronaldbarendse** [comment]
This can be closed, as PR https://github.com/umbraco/Umbraco-CMS/pull/6597 added the possibility to convert the UDI into the node name using the template `{{ value | ncNodeName }}`.

**Comment by Rizen-Kris** [comment]
![image](https://user-images.githubusercontent.com/38988891/95778625-bf9f3d80-0c85-11eb-8731-5d7ff1399aa3.png)
When I use "{{ value | ncNodeName }}" in 8.8 and I get "loading..." as shown in the screen shot

**Comment by emma-hq** [comment]
Hey people,

I'm going to close this one. As @ronaldbarendse pointed out, #6597 added the chance to convert the UDI. I'm not sure why the issue flagged by @Rizen-Kris has arisen but if you'd like to create a new issue for that, please go ahead.

Emma
