### ISSUE TITLE
Not possible to create a DocType without any properties

### ISSUE THREAD

**Issue by skartknet** [umbraco/Umbraco-CMS#5547]
Many times I have created DocTypes are just just a container for other doctypes. That way I can create something like Blog->Posts. In V8 that doesn't work. I can create the DocType but when I add a new page using it I get a black window without the possibility of adding the title of the page. If I click Save I get a 'Validation: Required' error.

Reproduction
------------

### Bug summary
I can't create a page that uses a DocType without properties.

### Steps to reproduce

- Create a DocType without any properties. Allow it in root.
- Create a page based on this DocType on the root.

### Expected result

I expect to get only the title bar to enter a name for my page.

### Actual result

A blank window appears with just the Save and Save And Publish buttons.

**Comment by kjac** [comment]
Hmmm... I'm pretty sure I submitted a fix for this at some point. I'll dig into it later 👍

**Comment by idseefeld** [comment]
I have just done this in a fresh 8.0.2 version. It work as expected.

**Comment by kjac** [comment]
I was about to add the same finding 👍

**Comment by skartknet** [comment]
Yes it's working now. Sorry, I think I was using the `dev-v8` branch instead the `dev/v8`.
