### ISSUE TITLE
v8: Unpublished multilingual page has PublishedState of Published

### ISSUE THREAD

**Issue by PerplexDaniel** [umbraco/Umbraco-CMS#5554]
### Bug summary

A page that has "Allow varying by culture" set to true and is unpublished for all cultures has a `PublishedState` of Published on its IContent object.

Is this intended, and are we then supposed to check the `PublishedCultures` property instead in this case? 

It is really confusing that this is different between document types based on the vary by culture checkmark. That is, if the checkmark is not set the page will properly have a `PublishedState` of Unpublished when it is unpublished.

### Steps to reproduce

1. Create a Document Type with Permissions > "Allow varying by culture" checked
2. Create a new page based on that document type.
3. Publish it for 1 language.
4. Unpublish it.
5. Check the `PublishedState` of the IContent:
```csharp
// Inject
IContentService cs;

// Check pageId in Umbraco
int pageId = 1234;

// Check state -- should be false but is true.
var publishedState = cs.GetById(pageId).PublishedState;
```

### Expected result

The `PublishedState` is `false`.

### Actual result

The `PublishedState` is `true`.

### Version
Umbraco 8.0.2

---
_This item has been added to our backlog [AB#1718](https://umbraco.visualstudio.com/243e7927-03b2-44e2-908f-d4ac7ea5daaa/_workitems/edit/1718)_

**Comment by nul800sebastiaan** [comment]
I think it's intentional yeah and you'd need to add a check for `PublishedCultures` to get the full picture of what the state of the node is. I'll have a chat at HQ and get some more feedback on this.

**Comment by nul800sebastiaan** [comment]
We had a chat about this at HQ and it turns out I misunderstood what was going on, this seems like a bug that we need to fix.

**Comment by tom-ingeniuus** [comment]
Just to add that, (tested in v8.1) the resulting node is in the ExternalIndex until that index is rebuilt, then it is removed from the index.

**Comment by Shazwazza** [comment]
I created a unit test to show the problem in rev 5d92c8ac6ba8e5991791d313b50bebffebf21e35

Publishing and unpublishing isn't just black/white when it comes to variants. We first have a "document" - which is the same idea as in v7 - it can be published/unpublished. When it is unpublished it is not routable, etc... Then in v8 we have variants which are part of the document but they are not the "document". In the APIs we have a term for a variant's state which is available/unavailable which is basically it's own equivalent of published/unpublished. It is certainly possible and a common scenario where there can be many variant's that are available but the document is not published. In this case, nothing can be routed to but the variant's state hasn't change when the document was unpublished. When the document is re-published, the variant's state still will not change but now all variants that were available are not routable. When 'unpublishing' a variant in the UI, we are really just making this variant unavailable and re-publishing the document with a new version which lists the newly available variants. 

The confusion here is that if the last available variant is made unavailable, we aren't explicitly unpublishing the document which means the document's status remains Published. In this state, another variant could be made available (published in the UI) and it would be routable and the document's own published state would not have changed.

To make it a little less confusing, we can explicitly unpublish the document when the last culture is made unavailable. Then we will have to do the opposite for when the first variant is made available and should be published. 

Will report back with fixes.
