### ISSUE TITLE
V8: Make more helpful message than "there are no allowed document types available"

### ISSUE THREAD

**Issue by AndyButland** [umbraco/Umbraco-CMS#5561]
_Porting over [issue U4-9734](https://issues.umbraco.org/issue/U4-9734) from old tracker in order to associate a PR resurrected for V8._

Fresh install, no starter kit, no doctypes
Attempt to create a new content page.
You'll get the message that there are no allowed document types available.
It would be helpful to change the message based on the capabilities of the person logged in.

A content editor with no access to the Document Types section should get a more 'human' message that the selected page in the content tree doesn't allow any pages below it. Don't include any instructions about how to enable them with doctypes.

For users with access to Document Types, the text should be the same but also include more info that the relevant doctype (list it by name, based on the doctype of the content item currently selected) doesn't allow any child pages below it. And if they'd like to change that then provide a link/button to go directly to the appropriate doctype and the Permissions section instantly.

**Comment by kjac** [comment]
Yeah! Pretty sure @OwainWilliams was working on this for #3947 ?

**Comment by AndyButland** [comment]
Ah, OK @OwainWilliams @kjac, hadn't realised someone else had tackled this.  I had done in a PR to V7 some time back, that was recently closed, but figured it was still a useful addition.

Have resurrected [here](https://github.com/umbraco/Umbraco-CMS/pull/5562) - but if there's a better alternative in progress, then all good...

**Comment by kjac** [comment]
Awesome 😀

**Comment by OwainWilliams** [comment]
Nice. I've not had a chance to finish my pr so if there is something else that's been done then that's great.

**Comment by nul800sebastiaan** [comment]
Fixed in https://github.com/umbraco/Umbraco-CMS/pull/5562
