### ISSUE TITLE
Application of User Groups to a user is buggy

### ISSUE THREAD

**Issue by martinjgriffiths** [umbraco/Umbraco-CMS#5569]
Scenario...

I needed to be able to create a "Super User" for our business development manager so that they can manage all content aspects view/save and publish etc. and be able to manage users & groups. But NOT have access to the developer & settings sections.

At first simply creating the Group "super user" seemed to work and after giving them access to the various sections all seemed good. Until they tried to manage a user....The super user could ONLY apply super user group settings to another user, all other groups were greyed out. To fix this I added Writer & Editor groups to the super user account and they could then change other users groups accordingly. 

But once this was done, they started getting a weird error when trying to publish content on any node.

2019-06-03 10:04:24,757 [P5920/D2/T501] ERROR Umbraco.Web.Editors.ContentController - Unhandled controller exception occurred
Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: S. Path '', line 0, position 0.

So for now I've had no choice but to revert them back to an Administrator. Something which is overkill for that type of user.

Thoughts?

Currently happening on version 7.13.2

**Comment by nul800sebastiaan** [comment]
Hey @martinjgriffiths - I can't reproduce this on 7.14.0 so either this has been fixed since 7.13 or something else is going on, not sure since I don't remember this being a problem that we actively fixed. 

FYI, these are my settings for the user group:

![image](https://user-images.githubusercontent.com/304656/59267784-59e31180-8c4b-11e9-97e2-ba5f15169bee.png)

**Comment by martinjgriffiths** [comment]
Hi Sebastiaan

So when you're logged in as that user can you...

Apply other groups to other users (other than super user) and can you publish without the error mentioned?

I had to also apply, writer and editor to the users "groups" so that the "super user" could assign those groups to other users. It was at this point the publishing error mentioned started happening.

**Comment by nul800sebastiaan** [comment]
Not a clue :-)

You'll probably need to dig into logs and server logs for that.

From your edited comment: 

> can you... Apply other groups to other users (other than super user) 

No and that will not be possible, we wouldn't want to give people the ability to do some kind of privilege escalation.
