### ISSUE TITLE
Privacy-friendly statistics showing page visits

### ISSUE THREAD

**Issue by bardurc** [umbraco/Umbraco-CMS#5571]
I would like to be able to view simple statistics over page visits:

- Which page on my site has been visited

- When has a given page been visited

- How often has a given page been visited

No need to collect user-agent, referrer, IP-address or anything else.

Google Analytics collects way too much, and I would rather not collect any more data than necessary on my visitors.

**Comment by nul800sebastiaan** [comment]
Hey there @bardurc - this is not functionality we plan to build into Umbraco. We'd encourage you to look for plugins that can do this or build you own tracker. 

You can look for plugins (packages) or ask for advise on how to build your own at our community site: https://our.umbraco.com/
