### ISSUE TITLE
Doc type as child of itself is not persisted on create

### ISSUE THREAD

**Issue by bergmania** [umbraco/Umbraco-CMS#5574]
When creating a new doctype, and choose itself under "Allowed child node types". The information is not persisted, when creating the doc type.

![Before](https://user-images.githubusercontent.com/1561480/58862994-2edc4900-86b2-11e9-807d-b8f0124d656f.gif)

Tested on v7.14 + v8.0.2

PR incoming for v7.

**Comment by nul800sebastiaan** [comment]
That's weird! But only when you start with a new doctype, right? I can assign the allowed child node to be the same doctype after a refresh.

**Comment by bergmania** [comment]
It's only when we create the doc type. This is all handled as a special case where the frontend sends id `0` to the backend. But apparently this does not work.

It works when you update the doc type

**Comment by nul800sebastiaan** [comment]
Fixed in https://github.com/umbraco/Umbraco-CMS/pull/5575

**Comment by nul800sebastiaan** [comment]
Fix has been merged up to 8.1.0 as well now.
