### ISSUE TITLE
V8: Trix Property Editor

### ISSUE THREAD

**Issue by nielslyngsoe** [umbraco/Umbraco-CMS#5577]
I'm doing a test implementation of the Trix RTE as a Property Editor in Umbraco v.8.?

This implementation is an investigation of the features of the Trix editor. Used to review if Trix supports the needs we have in Umbraco.

In relation to this RFC: https://github.com/umbraco/rfcs/pull/5

Draft PR: https://github.com/umbraco/Umbraco-CMS/pull/5578

Feel free to comment or make suggestions.

**Comment by kjac** [comment]
Hi! While I applaud the initiative, shouldn't this wait until the RFC process is complete @ https://github.com/umbraco/rfcs/pull/5 ?

**Comment by clausjensen** [comment]
@kjac Sorry for the delay 😃 You're absolutely right... and don't worry - we're not skipping the entire RFC process that we defined ourselves. We however need a bit of maturing on the Trix implementation in order to compare it to the alternatives we have (since that editor.js suggestion that is now in play, was not really considered at all initially).
So @nielslyngsoe is doing some work on this - but we're still far from "finishing" the RFC process and making decisions and then doing the final implementation of whatever is decided.

**Comment by clausjensen** [comment]
@kjac can also add that we're still working on integrating that whole RFC process with our workflows and planning .. which has some challenges - especially now that we're basically starting from scratch and need some review/feedback period, while we're also eager to get started on the features.
The plan for the next cycle is mostly to get some of these RFCs to a state where we feel comfortable moving forward with them.

**Comment by nielslyngsoe** [comment]
Hi @kjac as Claus just mentioned we are just digging into some of the specifics of implementing the Trix-editor, to see if the Trix editor is the right choice and test wether it can handle our needs.

**Comment by kjac** [comment]
Super cool 😀

**Comment by marcemarc** [comment]
I thought the same as you @kjac , but also consider, with the RFC process, it needed some good examples of what would go into an RFC to demonstrate the idea at CG, if some work was already in progress at HQ before the RFC approach was definitely decided upon.. then it would look weird if that work in progress was then later released without there being an RFC! - but also this work makes great examples of the type of things to discuss in an RFC - so in the early days of getting these RFCs going we might see similar examples of this, but hopefully moving forwards RFCs provie better early input/embedding into HQ process to coordinate how things take shape... of course there needed to be an RFC for the RFC process!

**Comment by Shazwazza** [comment]
... well, the RFC process was borrowed and iterated on based on a number of different OSS projects so we didn't just make it up ourselves ;) see: https://github.com/umbraco/rfcs#credits

**Comment by nul800sebastiaan** [comment]
Closing now as we took a different route.
