### ISSUE TITLE
V8:Changing Data Type Loses Data

### ISSUE THREAD

**Issue by UnsungHeros** [umbraco/Umbraco-CMS#5579]
Is there a way to safely change a Property Editor on a document type property without losing the data?

This is an issue that happened in V7 at a higher level[#2958](cannot change DocumentTypes in V8 currently[#5070]). When changing a datatype, the information is lost. In my case, I changed a textbox field which held a link, to a multinode URL picker so that the UX was better for our users. This issue will most likely happen ANY time changes to a model is made. The only way that I can currently retain the data is by creating a new field and having both present in the interim until the data is transferred to the new type,which is fine for our smaller scale pages. Only problem is, on a larger scale it becomes cumbersome from a maintenance perspective...

Because we are unable to change document types currently, I am assuming if that is the behavior that it will true for property editors as well, or is it intended that we are able to change Document Types and there is just a bug in both places?

**Comment by nul800sebastiaan** [comment]
This will indeed happen at the moment, make sure to keep track of https://github.com/umbraco/Umbraco-CMS/issues/5070 for updates on this.
