### ISSUE TITLE
V8: GetPagedDescendants not working

### ISSUE THREAD

**Issue by UnsungHeros** [umbraco/Umbraco-CMS#5583]
I've written a health check to check for content that is older than 1 day and it will give me a count of the content, but it will not give me any paged results.  

Reproduction
------------

Use the attached code to set up a health check and put a breakpoint on the CheckForStaleContent() function.

### Specifics
When I expand the z,results it exapnds that the enumeration contains no results.
![Screen1](https://user-images.githubusercontent.com/47826788/58909963-fe100a00-86d9-11e9-9d02-9cf7333e09c9.JPG)

### Steps to reproduce
[GetPagedDescendants.txt](https://github.com/umbraco/Umbraco-CMS/files/3254298/GetPagedDescendants.txt)

Run the GetStale content Health check in the admin that is under services.

### Expected result
Total sales should have the number of stale content items.  I should be able to get the name of the content from z.First().Name or similar

### Actual result
The totalSales is populating with a number(724 in my case).  But the variable z does not allow me to obtain any content name or ids.  The debugger indicates there are no results.  z.First() indicates there are no results.
Screenshot as attached.

**Comment by nul800sebastiaan** [comment]
Paging starts at 0 though, so make sure to set your pageIndex accordingly. :-)

![image](https://user-images.githubusercontent.com/304656/58911784-e73cd800-8718-11e9-8996-1333043f4029.png)

**Comment by cogworks-infrastructure** [comment]
Hello Great Developers of Umbraco,

I'm writing to request that you update the documentation for the **pageIndex** parameter of the **GetPagedDescendants** method. Could you please add a clear explanation that index starts from **0**

Thank you for your time and consideration.
