### ISSUE TITLE
V8: Datepicker doesn't allow copy and paste

### ISSUE THREAD

**Issue by bmargevicius** [umbraco/Umbraco-CMS#5584]
The new datepicker (flatpickr) doesn't handle the blur event which doesn't allow for copy paste (even if the formatting is correct). Kicking the 🐴 you can't manually type in dates either.

Reproduction
------------

### Steps to reproduce
1) Create a doctype
2) Add a Date property type
3) Goto add content, paste in a date matching the format 
4) Save and publish. 
5) Navigate away from that content
6) Go Back to that content. 
7) Observe the date picker is now blank. 

It seems there is no way to handle the blur event within flatpickr. 

That being said. Should there be an automatic validator to match the format given in the property editor?

**Comment by nul800sebastiaan** [comment]
That's a great feature request! 

I've marked this as "Up for grabs" so that you or someone else coming along could create a pull request for it.

**Comment by bmargevicius** [comment]
Either this or the other way around. We should disable the ability to paste dates in.

**Comment by bmargevicius** [comment]
Looking at https://flatpickr.js.org/options/
allowInput option allows the user to enter a date directly input the input field. By default, direct entry is disabled.

**Comment by bmargevicius** [comment]
Given that the default is disabled. I think I would leave this up for discussion before doing anything. For some reason you can type in the textbox in the backoffice. In the flatpickr demos you can't do this... So something is awry with the implementation of flatpickr in umbraco..

**Comment by kjac** [comment]
I think work was at some point partially done in an attempt to support manual entry. However it doesn't seem to have been finished (or at least, tested). 

I have created a PR in #5657 that allows manual entry (and copy/paste) of date/time properties.
