### ISSUE TITLE
Wrong location xml documentation files in NuGet packages

### ISSUE THREAD

**Issue by MvdDonk** [umbraco/Umbraco-CMS#5588]
After adding UmbracoCms.Core or UmbracoCms.Web (both version 8) to my project the xml documentation files aren't copied to the bin folder resulting in documentation not working in Visual Studio, as shown on this screenshot: 
![Documentation not working](https://user-images.githubusercontent.com/2156402/58944065-53532680-8781-11e9-9e02-66f9ea7ed3a0.png)
This problem is happening because the xml files aren't in the correct directory in the NuGet package. They are in the /lib directory but should be placed inside /lib/net472.
After adding them manually, rebuilding the solution and restarting Visual Studio the documentation is showing like it's supposed to do:
![Documentation working](https://user-images.githubusercontent.com/2156402/58944172-8d242d00-8781-11e9-9ce6-5b53c7d4c1d3.png)

**Comment by nul800sebastiaan** [comment]
Good find! Would you be able to make a PR to fix that?

I've marked this as "Up for grabs" so that you or someone else coming along could create a pull request for it.

**Comment by MvdDonk** [comment]
I've added a pull request with the fix.
