### ISSUE TITLE
U8: Property groups ordering

### ISSUE THREAD

**Issue by Baracuda011** [umbraco/Umbraco-CMS#5590]
Dear all,

Is it possible to enable reordering of property groups when a document type has a combination of its own properties and compositions? Currently, it's not possible to organize properties "logically".

It is not a showstopper in any way but would add to overall customer experience.

I am working on 8.0.2 cloud version.

Thanks.

**Comment by nathanwoulfe** [comment]
I'll usually set sort orders manually on the composition - tabs might be increments of 10, properties increments of 5, then when they are composed into other types you can set the tab/property sort orders to sit in between.

**Comment by nul800sebastiaan** [comment]
As Nathan mentions you can do this by updating the tab order and leave room for other tabs in between.

Make sure to ask further questions on the forums at https://our.umbraco.com where our friendly community can help you along!

**Comment by Baracuda011** [comment]
Thanks @nathanwoulfe and @nul800sebastiaan I will try with this approach.

**Comment by Baracuda011** [comment]
Brilliant idea, thank you @nathanwoulfe. It works perfectly!
