### ISSUE TITLE
Allow custom filters on columns in list view

### ISSUE THREAD

**Issue by skttl** [umbraco/Umbraco-CMS#5591]
Similar to how you can modify the label of nested content items, it could be nice if you could make javascript filters for the display of property values in columns of the list view.

For non-simple editors the result today is like this:
![billede](https://user-images.githubusercontent.com/3726467/58952952-65d75b00-8795-11e9-9cc4-d92c54c62674.png)

Adding a simple filter like `{{ this[0].value }}` could make this one write Dunlop.

Or if you are having a large textarea as a column in the listview, you could do like `{{ this.substring(0,20) + '...' }}`

(assuming `this` is the value of the column)

**Comment by nul800sebastiaan** [comment]
Feedback from HQ: yep, that would sure be nice!

I've marked this as "Up for grabs" so that you or someone else coming along could create a pull request for it.

**Comment by elit0451** [comment]
Fixed in #6597

**Comment by nul800sebastiaan** [comment]
@skttl Thanks again for adding this! Any chance you could write some documentation for this as well, so people know what they can do with this template field?

**Comment by skttl** [comment]
I'd love to, but is there any documentation on the listview already?
