### ISSUE TITLE
U8: umbracoUrlAlias inheritance

### ISSUE THREAD

**Issue by Baracuda011** [umbraco/Umbraco-CMS#5593]
Dear all,

Is it possible to introduce umbracoUrlAlias inheritance to child nodes? I have a parent page with defined umbracoUrlAlias, but all the child pages have their own default URLs and are not considering parent's custom URL.

I think this can be a very useful feature for both SEO and user experience.

I am working on 8.0.2 cloud version.

Thanks.

**Comment by abjerner** [comment]
Hi @Baracuda011,

It sounds like you're looking for `umbracoUrlName` instead?

https://our.umbraco.com/Documentation/Reference/Routing/routing-properties#umbracourlname

**Comment by Baracuda011** [comment]
Hi @abjerner, not exactly.

Let me describe in bit more details. I am replicating a structure from the old version of a website and footer navigation contains a huge number of pages which are all under the home node. When I look at old Umbraco tree it is very "unpleasant" to look at and time-consuming to navigate and manage.

I created container nodes so I can organize my footer pages. And now each footer page has a default URL like: /container-1/page-1/ , /container-1/page-2/ , /container-1/page-3/ etc. The end result is much better organized and manageable content tree. On rare occasions, in the old structure, there was a container, here and there, as an actual page with its subpages.

My client wants to keep old URLs structure without introducing 301 redirects. So I have defined umbracoUrlAlias where I needed to add a custom (old) URL to my new structure.  So we can have the identical URL structure to the old website.

My suggestion was related to a case where the container isn't a page and I need my page URL to be without the container part. So instead of /container-1/page-1/ to be only /page-1/

Hope this clarifies things more.

**Comment by nathanwoulfe** [comment]
Better option here would be to use contentfinder and urlprovider to drop the container-n segment out of the URL. 

Try https://our.umbraco.com/Documentation/Reference/Routing/Request-Pipeline/IContentFinder and https://our.umbraco.com/Documentation/Reference/Routing/Request-Pipeline/outbound-pipeline#urls for starting points

**Comment by nul800sebastiaan** [comment]
Hi there @Baracuda011 - this sounds like an excellent question for the forums where our friendly community can help you find the best solution for your requirements. 
Make sure to head on over to https://our.umbraco.com and ask follow up questions there! 👍

**Comment by Baracuda011** [comment]
Hi @nul800sebastiaan the initial question was a feature/update suggestion and I see that this entire discussion went into a too complex direction, which wasn't my idea at all :)

I still stand by my initial observation that the inheritance of umbracoUrlAlias property to child nodes could be a very cool feature.

Thanks.
