### ISSUE TITLE
V8: Content tree blocks TinyMCE in fullscreen

### ISSUE THREAD

**Issue by Frost117** [umbraco/Umbraco-CMS#5600]
A brief description of the issue goes here.

If you want to run tinyMCE in a fullscreen to have focus on the content you are writing with no disturbing elements from the backoffice, then you will find that the content tree blocks the left side of your fullscreened TinyMCE.

Reproduction
------------

### Bug summary
When you go into fullscreen with the TinyMCE function you are met with this:
![image](https://user-images.githubusercontent.com/32164310/59018935-557fb880-8847-11e9-91bf-a7e7378acbe4.png)

That is because the Content tree is blocking you to see the actual content that you are making.

The reason for the blockage is because the #leftcolumn has a z-index of 1100 and if you remove this, you are then greeted with this lovely view:
![image](https://user-images.githubusercontent.com/32164310/59019120-b3140500-8847-11e9-890b-f5011e1165dc.png)

With Z-index of:
![image](https://user-images.githubusercontent.com/32164310/59019132-bb6c4000-8847-11e9-9be5-8b5c64598672.png)

I navigated around in the backoffice with the z-index off and I didn't spot anything that was causing issues with the content tree.

### Specifics

Version 8.0.1
Chrome Version 74.0.3729.169
Firefox Version 66.0.3

### Steps to reproduce

Step 1:
Apply the following config changes to the tinyMceConfig.config in their respective places:

```
<commands> 
<command alias="fullscreen" name="Full Screen" mode="All" /> 
</commands> 
<plugins> 
<plugin>fullscreen</plugin> 
</plugins>
```

Save the file.

Step 2:
Enable the new function in the property editor like so:
![image](https://user-images.githubusercontent.com/32164310/59018577-7bf12400-8846-11e9-8d62-db93dcc777ac.png)

Step 3:
Navigate to a content node that uses a RTE editor and click on the fullscreen button:
![image](https://user-images.githubusercontent.com/32164310/59020109-9ed10780-8849-11e9-972b-b3f0ce9aab35.png)

### Expected result

I expected to see a fullscreen of the TMCE, that allows me to write content.

### Actual result
The left view is blocked by the content making it very difficult of knowing what you are doing.

**Comment by UnsungHeros** [comment]
This is also happening on 8.0.2.

**Comment by Shazwazza** [comment]
PR is here https://github.com/umbraco/Umbraco-CMS/pull/5683

Have added the full screen command/plugin by default so people can discover it. Side note however is that full screen plugin doesn't work in distraction free mode.

The fix simply ensures that mce-fullscreen class has position:absolute which is needed since the tree is that same position type (in v8 it's only zindex 100)

**Comment by warrenbuckley** [comment]
All tested & merged in :)
