### ISSUE TITLE
V8 Emptying the Recycle bin with a protected page and associated login page throws a SQL error

### ISSUE THREAD

**Issue by tom-ingeniuus** [umbraco/Umbraco-CMS#5605]
Umbraco 8.0.2

STR:
Assign Role based protection to a page/node and select login and error pages
Delete the protected page and the associated login and error pages
Empty the wastebasket
A SQL error is thrown as shown in the attached screenshot

Workaround
Move the pages out of the wastebasket, remove the protection, then delete the pages and empty the wastebasket without error.
![empty umb bin with protected page setup results in error](https://user-images.githubusercontent.com/49899682/59067928-c6a48780-88aa-11e9-8c27-ea6e3cd11204.PNG)

**Comment by AndyButland** [comment]
PR [here](https://github.com/umbraco/Umbraco-CMS/pull/5625).

**Comment by nul800sebastiaan** [comment]
Fixed in https://github.com/umbraco/Umbraco-CMS/pull/5625
