### ISSUE TITLE
V7.12.4-7.14.0 Textstring Validation as number, no error info.

### ISSUE THREAD

**Issue by zharonar** [umbraco/Umbraco-CMS#5611]
As the title states, when we set textstring to validate as a number, and when we press "Save and Publish", there is only "X" sign on button, server throws bad request (headers response "Validation error"), but texstring input doesn't get highlighted red, no floating error...

Also someone reported the same issue: https://our.umbraco.com/forum/umbraco-cloud/97429-doc-type-validation-no-error-message

**Comment by nul800sebastiaan** [comment]
I would recommend you use the `Numeric` datatype instead.

**Comment by zharonar** [comment]
So, how to validate phone number now? That is the case here. Number has limited amount of length, so it's not of any use. The case what I am talking about is that user should get a visual notification it entered wrong input.

I.E. +1 333 555 999 should be entered as 1333555999. By using validation as number, user can't get visual that first input is wrong...

**Comment by nul800sebastiaan** [comment]
That's exactly what the numeric input does, it let's you know when you don't enter a number that it's not a valid value :-)

**Comment by croban** [comment]
Same problem here, just i'm using custom validator and if the value is not valid, there is no notification or something similar for on empty required field.
