### ISSUE TITLE
Users with access to the user section can edit the Initial User account by typing it's ID in the url.

### ISSUE THREAD

**Issue by deMD** [umbraco/Umbraco-CMS#5613]
When logged in as a user with access to the Users section, I can edit the Initial Users account by changing the URL even though the account is hidden is the UI. Currently it seems I can only edit the avatar, disable the account and change groups and nodes, changing password or email address doesn't work

Reproduction
1. Create a new instance of Umbraco
2. Add a new user group with access to the Users Section
3. Add the role to a user that has no previous access to Users (f.e. a new account)
4. Log in with the user that have the Users section group
5. Go to a user profile
6. Change the ID from the url to -1 (/umbraco#/users/users/user/-1)
7. Edit any info on the Super User and save.
(8. Changing the avatar seems to do a forced logout, but the avatar is processed.)

**Comment by nul800sebastiaan** [comment]
Thanks, this has been fixed recently and the fix will be available in 7.15.0.

**Comment by deMD** [comment]
I forgot to add the Umbraco version, this issue also occurs in Umbraco V8.0.2
