### ISSUE TITLE
Spelling mistake IContentFinder function

### ISSUE THREAD

**Issue by patrickdemooij9** [umbraco/Umbraco-CMS#5614]
Don't know if this is supposed to be a Documentation issue or another sort of issue, but I couldn't find anything that I could use for this issue.

It's a really small issue. In the IContentFinder interface, the parameter is named frequest. I believe that this is wrong and that it should be changed to request. Sorry, just had to make an issue for it, will add the PR too.

**Comment by nul800sebastiaan** [comment]
Fixed in https://github.com/umbraco/Umbraco-CMS/pull/5616

**Comment by marcemarc** [comment]
@nul800sebastiaan Just wondering when we make changes like this - should there be some kind of automatic trigger to update the documentation
eg:

Updated pages for V8 docs refer to frequest
https://our.umbraco.com/documentation/Getting-Started/Code/Debugging/Logging/

and the autogenerated documentation from the comments, refers to a frequest

https://our.umbraco.com/apidocs/v8/csharp/api/Umbraco.Web.Routing.IContentFinder.html

I'm keen to try and keep the docs in sync with changes, I'm wondering if it's at the point of 'merge' that the consequences on the docs are considered? This seemed like a good example!

**Comment by nul800sebastiaan** [comment]
@marcemarc Yes.

As you might know Jesper is working on docs updates and they should be quite automated.

Also, I wouldn't want to update the docs now, nobody can use this new parameter yet, 8.1.0 is not yet released.

**Comment by marcemarc** [comment]
@nul800sebastiaan will pick up on doc team chats, but my thinking was to have a branch of the docs mimicking the major release eg 8.1, so documentation changes for the release could be merged into 8.1 branch of docs, and the same time as them being merged into the core release branch, - and it'd be used as a bit of a reference, eg have we docc'ed all the changes for the release!, then merged into docs at same point in time as release is released?
