### ISSUE TITLE
Can't log in with user that only has access to the users section

### ISSUE THREAD

**Issue by deMD** [umbraco/Umbraco-CMS#5617]
When creating a user with a group that only grants access to the Users Section, that user can log in into the CMS. in the browser console I see the following error:
![image](https://user-images.githubusercontent.com/22070292/59112815-0ff4e580-8944-11e9-8102-a0ca72592167.png)

Reproduction:
1. Create a group with only access the the Users Section
2. Add the group to a user with no other groups
3. Try to log in with that user.

**Comment by nul800sebastiaan** [comment]
Thanks, this has been fixed recently and the fix will be available in 7.15.0.

**Comment by deMD** [comment]
I forgot to add the Umbraco version, this issue also occurs in Umbraco V8.0.2
