### ISSUE TITLE
umb-button shows progress status forever after Save and Publish when creating a new content that is invalid

### ISSUE THREAD

**Issue by davidardoin** [umbraco/Umbraco-CMS#5621]
umb-button shows progress status forever after Save and Publish when creating a new content that is invalid

Reproduction
------------

I have have a culture variant content type with a mandatory property. 
When I enter a new content of this type (omitting the mandatory prop but still documenting names in both languages) and hit Save and Publish, the validation kicks in and shows the errors in the popup window. That is correct.
If I click again Save and Publish, the button stays in progress status forever.

### Specifics

![image](https://user-images.githubusercontent.com/51491633/59125287-d5814d80-892f-11e9-8a88-55aec10c1e73.png)

**Comment by nul800sebastiaan** [comment]
Thanks, this has been fixed in the upcoming version 8.1.0! 👍 

![5611](https://user-images.githubusercontent.com/304656/59266518-120ebb00-8c48-11e9-9b3d-581474e926b0.gif)
