### ISSUE TITLE
Problem with upgrade to 7.13 and above: Invalid column name 'controlId'

### ISSUE THREAD

**Issue by jono-k** [umbraco/Umbraco-CMS#5622]
Attempting to upgrade to 7.14 on a client's production server, and when upgrading I receive the error (on the installation page) "Invalid column name 'controlId'". I have tried incrementally upgrading by version numbers and the error occurs when upgrading from 7.12.4 to 7.13

### Bug summary

I haven't been able to reproduce this locally, so I'm not sure what is different on the production server. There is modified users and security on the prod database, but the users have been given sufficient permissions. There is some posts on the Umbraco forums with a similar issue, some people have mentioned the database schema/user being an issue:

https://our.umbraco.com/forum/using-umbraco-and-getting-started/96773-problem-with-upgrade-7124-to-713-invalid-column-name-controlid

https://our.umbraco.com/forum/using-umbraco-and-getting-started/95549-invalid-column-name-controlid-on-upgrade

### Specifics

Could possibly be an issue with database users and schemas, but I'm not sure.

**Comment by nul800sebastiaan** [comment]
Hey there @jono-k - it's unfortunate that this is happening to you. Unfortunately for you, most people don't actually have this problem and we've been unable to pinpoint where the problem might be.

Therefore, we have to assume it has something to do with your particular configuration. If you have any more clues as to what we can fix in Umbraco feel free to report back but at the moment, we wouldn't know how to fix this specific issue.

I'm going to close the issue, make sure to discuss workarounds on the forum.

I have 2 articles here that might help (especially the last one) to get your site upgraded properly:

https://cultiv.nl/blog/how-to-diagnose-umbraco-upgrade-problems/
https://cultiv.nl/blog/an-umbraco-database-upgrade-tip-from-the-trenches/

**Comment by jono-k** [comment]
All good mate - I know it's a bit of an edge case. I thought I'd submit it as an issue as I found a couple of others with the same problem. I'm quite sure it's schema/permissions related but can't seem to crack it. Anyway, if anything pops into your head in the next few months then let me know.

**Comment by nul800sebastiaan** [comment]
Sure thing! I'd definitely try to upgrade your database against a clean install as mentioned in the second blog post I listed, might just do the trick.

**Comment by mov3nforward** [comment]
I am getting the same error. 
Invalid column name 'controlId'.

Upgrading Umbraco is just a horrible experience. 

Now I need to waste hours trying to figure out why a basic install is not working. I have issues upgrading Umbraco on EVERY SINGLE SITE I HAVE.

**Comment by mov3nforward** [comment]
If anyone needs this, our issue was that the scheme in the db was dbo and we needed it to be our db username. After we updated the db table schemes to our db user name we were able to upgrade.

**Comment by prosperva** [comment]
> Hey there @jono-k - it's unfortunate that this is happening to you. Unfortunately for you, most people don't actually have this problem and we've been unable to pinpoint where the problem might be.
> 
> Therefore, we have to assume it has something to do with your particular configuration. If you have any more clues as to what we can fix in Umbraco feel free to report back but at the moment, we wouldn't know how to fix this specific issue.
> 
> I'm going to close the issue, make sure to discuss workarounds on the forum.
> 
> I have 2 articles here that might help (especially the last one) to get your site upgraded properly:
> 
> https://cultiv.nl/blog/how-to-diagnose-umbraco-upgrade-problems/
> https://cultiv.nl/blog/an-umbraco-database-upgrade-tip-from-the-trenches/

I tried this and it does not work. I still got the same error.

**Comment by prosperva** [comment]
> If anyone needs this, our issue was that the scheme in the db was dbo and we needed it to be our db username. After we updated the db table schemes to our db user name we were able to upgrade.

This worked for me. Thanks @mov3nforward
