### ISSUE TITLE
DotNetCore Preparation - Abstract Bundling

### ISSUE THREAD

**Issue by anthonydotnet** [umbraco/Umbraco-CMS#5627]
As discussed at Codegarden 2019, to transition to dotnet core, Umbraco requires significant refactoring.

This task is to abstract the bundling functionality.

@Shazwazza

**Comment by nul800sebastiaan** [comment]
For closing reason, please see: https://github.com/umbraco/Umbraco-CMS/issues/5628#issuecomment-500693504
