### ISSUE TITLE
DotNetCore Preparation - Abstract SMTP

### ISSUE THREAD

**Issue by anthonydotnet** [umbraco/Umbraco-CMS#5629]
As discussed at Codegarden 2019, to transition to dotnet core, Umbraco requires significant refactoring.

This task is to abstract and decouple SMTP.

@Shazwazza

**Comment by nul800sebastiaan** [comment]
For closing reason, please see: https://github.com/umbraco/Umbraco-CMS/issues/5628#issuecomment-500693504

**Comment by Shazwazza** [comment]
But interestingly, it's already being worked on for 8.x https://github.com/umbraco/Umbraco-CMS/issues/5512, https://github.com/umbraco/Umbraco-CMS/pull/2029
