### ISSUE TITLE
DotNetCore Preparation - Remove members membership provider

### ISSUE THREAD

**Issue by anthonydotnet** [umbraco/Umbraco-CMS#5630]
As discussed at Codegarden 2019, to transition to dotnet core, Umbraco requires significant refactoring.

This task is to completely remove the members membership provider.

It was discussed that this will break backoffice due to reliance of the membership functionality. This breakage was deemed as acceptable for now as the new identity functionality will replace the membership provider.

@Shazwazza

**Comment by nul800sebastiaan** [comment]
For closing reason, please see: https://github.com/umbraco/Umbraco-CMS/issues/5628#issuecomment-500693504
