### ISSUE TITLE
DotNetCore Preparation - Remove Users Membership Provider

### ISSUE THREAD

**Issue by anthonydotnet** [umbraco/Umbraco-CMS#5631]
As discussed at Codegarden 2019, to transition to dotnet core, Umbraco requires significant refactoring.

This task is to completely remove the users membership provider. 

Note: There might be a dependency here on the new identity functionality.

@Shazwazza

**Comment by nul800sebastiaan** [comment]
For closing reason, please see: https://github.com/umbraco/Umbraco-CMS/issues/5628#issuecomment-500693504
