### ISSUE TITLE
v8: Extend the umb-checkbox component to handle localization

### ISSUE THREAD

**Issue by BatJan** [umbraco/Umbraco-CMS#5633]
I noticed a few changes to the component has been made since I last had a look at it on the v7 branch, which is great and it's been used many places in the UI ❤️ 

However it bothers me that those places now have multiple `<label>` elements since it's already a part of the component - What we need to do is to extend the component so it's able to handle localizations instead so we only need to use `<umb-checkbox>` with some attributes and don't need to rely on remembering adding an additional `<label>` 😃

**Comment by nul800sebastiaan** [comment]
Fixed in https://github.com/umbraco/Umbraco-CMS/pull/5635
