### ISSUE TITLE
V7 Media Picker's 'Select media' 'upload' button is useless

### ISSUE THREAD

**Issue by lcichanowicz** [umbraco/Umbraco-CMS#5643]
Umbraco 7.14.0

I try to use the Media Picker on the property of node, in the backoffice.  I choose 'Upload' from 'Select media'.  I am not allowed to upload a PDF, a PNG, ….  Am I allowed to upload anything at all?  Why do I have to edit a config just to upload a PNG?

**Comment by nul800sebastiaan** [comment]
Hi there @lcichanowicz  - that should definitely work just fine.

This sounds like an excellent question for the forums where our friendly community can help you find the best solution for your requirements. 
Make sure to head on over to https://our.umbraco.com and ask follow up questions there! 👍
