### ISSUE TITLE
Upgrade from 8.0.1 to 8.0.2 fails

### ISSUE THREAD

**Issue by mirkomaty** [umbraco/Umbraco-CMS#5649]
I did an upgrade from 8.0.1 to 8.0.2 using NuGet update-package UmbracoCms. Umbraco detects the old and the new version but stops upgrading with the message

_Error during installation
See the log for full details (logs can typically be found in the App_Data\Logs folder)._

But there is absolutely nothing in the log, which could help. The message appears without any delay after pressing the button "Continue".

What makes me wondering is the following: 

The "Upgrading Umbraco" dialog has the following text:

`Detected current version 8.0.1 (80c0a0cb), which needs to be upgraded to 8.0.2 (80c0a0cb). To compare versions and read a report of changes between versions, use the View Report button below. `

80c0a0cb corresponds to the following log entry:

`"@mt": "Final upgrade state is {FinalMigrationState}, database contains {DatabaseState}",
	"@l": "Debug",
	"FinalMigrationState": "{80C0A0CB-0DD5-4573-B000-C4B7C313C70D}",
	"DatabaseState": "{80C0A0CB-0DD5-4573-B000-C4B7C313C70D}",`

I'm using SqlCe.

Log File: [Log.txt](https://github.com/umbraco/Umbraco-CMS/files/3280563/Log.txt)

**Comment by nul800sebastiaan** [comment]
Hey there @mirkomaty - odd, most people's upgrades work just fine. Make sure to check out errors in the browser console as well.

Other than that, here's a few blog post to help guide you through upgrade problems:

https://cultiv.nl/blog/how-to-diagnose-umbraco-upgrade-problems/
https://cultiv.nl/blog/an-umbraco-database-upgrade-tip-from-the-trenches/

Make sure to get some help on the forums at https://our.umbraco.com/ 👍

**Comment by presencewebdesign** [comment]
Looks at the console log, it doesn't support http method GET 

{"Message":"The requested resource does not support http method 'GET'."}

**Comment by mirkomaty** [comment]
For anybody having the same or similar problems, here the solution for the records: We had a rewrite rule which rewrites the request url to all lower case characters and makes a 301 redirect. This redirect turns the POST into a GET. That's what causes the message "The request resource does not support http method 'GET'". 

Umbraco requests are not all lower case, so the POST fails. We turned off the rule for any request starting with "umbraco", "install" and "mini-profiler-resources". These are the request routes, Umbraco uses for it's own purposes.

```
<rule name="SEO - ToLower" stopProcessing="false">
  <match url="^_*(.*)" ignoreCase="false" />
  <conditions logicalGrouping="MatchAll" trackAllCaptures="false">
	<add input="{R:1}" pattern="[A-Z]" ignoreCase="false" />
...
	<add input="{R:1}" pattern="umbraco/.*" negate="true" ignoreCase="true" />
	<add input="{R:1}" pattern="install/.*" negate="true" ignoreCase="true" />
	<add input="{R:1}" pattern="mini-profiler-resources/.*" negate="true" ignoreCase="true" />
  </conditions>
  <action type="Rewrite" url="_{ToLower:{R:1}}" appendQueryString="true" />
</rule>
```
