### ISSUE TITLE
V8: Richtext Editor Dimensions no longer required

### ISSUE THREAD

**Issue by uSkinned** [umbraco/Umbraco-CMS#5650]
The Data Type Richtext Editor has dimension settings. These settings are no longer applied due to the new styling of the editor in V8 where it expands in height to the amount of text being entered. 

The Dimensions settings should be removed from this Data Type.

**Comment by nul800sebastiaan** [comment]
Thanks, they will be applied again in v8.1.0: https://github.com/umbraco/Umbraco-CMS/pull/5568

**Comment by uSkinned** [comment]
cool.
