### ISSUE TITLE
V8: Issues with linking to media in the Rich Text editor

### ISSUE THREAD

**Issue by john-mckillip** [umbraco/Umbraco-CMS#5659]
When editing content in the rich text editor, if you click insert/edit link then click Select media. If you search for a media item, then click on it and click the Select button, it does not add the url (the field stays empty and does not allow you to edit).

![rte-link-bug](https://user-images.githubusercontent.com/7633040/59438913-f5929000-8db9-11e9-8881-e16889bba06a.gif)

If you select a file without doing a search first, it works as expected.

**Comment by kjac** [comment]
I can reproduce; will have a look asap.

**Comment by nul800sebastiaan** [comment]
@kjac Also in the latest code? I seem to recall this was recently fixed 🤔

**Comment by kjac** [comment]
Yeah. I'm on it now.

**Comment by kjac** [comment]
PR in #5666

**Comment by nul800sebastiaan** [comment]
Fixed in https://github.com/umbraco/Umbraco-CMS/pull/5666
