### ISSUE TITLE
V8: No filenames are displaying in list of media items when adding a link through the Rich Text Editor

### ISSUE THREAD

**Issue by john-mckillip** [umbraco/Umbraco-CMS#5660]
When adding a link to a document in the rich text editor, there are no filenames shown on any of the items unless you hover over them. This makes scanning the list for the item you want very cumbersome, especially if you have a large list of files.

![No_filenames_in_media_picker](https://user-images.githubusercontent.com/7633040/59441181-cb42d180-8dbd-11e9-8720-f0227f410006.png)

To reproduce, click insert/edit link in the rich text editor, click Select media and navigate to a folder of media items. In my case, it was a folder containing a bunch of pdf files. I am running the latest version of Umbraco 8.0.2.

**Comment by kjac** [comment]
Hi @john-mckillip, thanks for reporting 👍 

This issue has already been addressed in #5203 ... I'm guessing it'll be part of 8.1

**Comment by nul800sebastiaan** [comment]
It will be part of 8.1.0 yep. 👍

**Comment by john-mckillip** [comment]
Awesome. Thanks everybody 👍
