### ISSUE TITLE
Examine dashboard showing "Index cannot be read and will need to be rebuilt"

### ISSUE THREAD

**Issue by dalemccutcheon** [umbraco/Umbraco-CMS#5661]
I have recently upgraded my Umbraco solution to 7.13.2 however have came across an issue with Examine indexes i have been unable to fix.

Currently the examine dashboard is showing "The index cannot be read and will need to rebuilt" for every indexer.

I am unable to manually rebuild the index because of this message, even if i delete the generated examine files in the App_data folder these get rebuilt but i still get the error message on the dashboard. 

Like this, I have used Luke to view the indexes and they are fine, i can see all the documents and properties within the index fine.

There are no console errors and both the GetIndexerDetails and GetSearcher calls return with a 200 and no noticable issues in either of those responses.

    * Umbraco version 7.12.3
    * Examine 0.1.90
    * Chrome,Firefox and Edge

**Comment by nul800sebastiaan** [comment]
Hey there @dalemccutcheon - Sorry to hear you're having some problems. I would recommend you upgrade to 7.14.0 first of all. Then make sure you head out to the forum at https://our.umbraco.com so that our friendly community can help you get this problem fixed.

Thanks! 👍
