### ISSUE TITLE
Integration with Office 365 authentication

### ISSUE THREAD

**Issue by Cavillac** [umbraco/Umbraco-CMS#5680]
I'm looking for a package that allow me to integrate umbraco 8 with office 365 authentication but haven't found any. Does anyone know where can I find one or how to do this?

**Comment by abjerner** [comment]
Hi @Cavillac - if such a package exists, the [package section](https://our.umbraco.com/packages/) of the community forum would be the place to look for it. If you're unable to find a package for this, it might help to ask in the forum instead 😉

The issues section here on GitHub is for reporting problems with Umbraco CMS as a product - hence I'm closing this issue.

**Comment by Shazwazza** [comment]
@Cavillac if you are referring to the back office login, then you can implement your own logic that would extend the identity extensions package - but you will need to wait for that to become compatible with v8 https://github.com/umbraco/UmbracoIdentityExtensions or if you are referering to front-end members then you can extend my UmbracoIdentity package https://github.com/Shazwazza/UmbracoIdentity ... but also, you will need to wait till that becomes compatible with v8
