### ISSUE TITLE
When using IE11, in an Intranet Zone, Preview Fails

### ISSUE THREAD

**Issue by Myster** [umbraco/Umbraco-CMS#5682]
Update:
A combination of factors seems to cause this issue:
* Use IE11
* The site must be in the 'zone' called 'Local intranet' in the 'internet options' of the user's PC
* I've tested another Umbraco site without AD integration and the same issue occurs, so that isn't a factor.

To reproduce:
- Use IE11, 
- Ensure the site is in the intranet zone. (internet options)
- Login to the back office.
- Preview a page. url: http://example.com/umbraco/preview/?id=1105
- You will see javascript errors (if your site isn't in the intranet zone it will work fine)

I found the same issue reported here: https://our.umbraco.com/forum/using-umbraco-and-getting-started/88669-preview-not-working-in-internet-explorer-11
but no solution.

**Comment by nul800sebastiaan** [comment]
I am not sure how to reproduce this issue, I've tried to force everything into the "Local Intranet" zone but it just works (both 7.14 and 8.0.2). If you're working with another version of Umbraco you might need to upgrade. 

![image](https://user-images.githubusercontent.com/304656/59762916-9f7d8b00-9298-11e9-92a2-da0e03e2a301.png)

Maybe I'm doing something wrong  but I can't see a problem on this end. Make sure to update if I'm missing something.
