### ISSUE TITLE
v8: LinkPicker does not work when using the search box

### ISSUE THREAD

**Issue by pralthom** [umbraco/Umbraco-CMS#5689]
Hi,

I cannot find if this issue has already been raised.
When I use the link picker, search for a note inside the picker, after selecting the node I get a JS error:
![image](https://user-images.githubusercontent.com/44721265/59756499-22e3b000-928a-11e9-9d19-b0e4e429398c.png)

Reproduction
------------

Insert some text in a RTE. Then select some text and click on the "insert link" button.
![image](https://user-images.githubusercontent.com/44721265/59756587-4d356d80-928a-11e9-9d47-d49f283f0c52.png)

The select link dialog appears
Type something in the search box:
![image](https://user-images.githubusercontent.com/44721265/59756675-85d54700-928a-11e9-9a95-ad7530350ca6.png)

Then when you click on the node you want to select you get the JS error described above.

If you click the "submit" button you get another JS error and the dialog does not close:
![image](https://user-images.githubusercontent.com/44721265/59756787-ba490300-928a-11e9-9a7e-cf0103406ab9.png)

**Comment by pralthom** [comment]
This problem is caused by a modification I've made few weeks ago:
https://github.com/umbraco/Umbraco-CMS/pull/5408

I found where the issue stands and I will make another PR to fix this.

**Comment by nul800sebastiaan** [comment]
Thanks! I was about to ask if it wasn't you that changed this! Thanks for looking into it. I don't know how I missed this during testing. :-)

**Comment by pralthom** [comment]
Hi, thank you for the quick answer. 
I've just made a PR. 
As you can see it's not perfect because the search box of the link picker is not displayed in the right language.

**Comment by nul800sebastiaan** [comment]
Closing this one, see comment in the PR :-) https://github.com/umbraco/Umbraco-CMS/pull/5693
