### ISSUE TITLE
Saving a member causes page hanging

### ISSUE THREAD

**Issue by elit0451** [umbraco/Umbraco-CMS#5691]
When you add a member in the back-Office with the required information and save the changes, the second time the **Save** button is pressed the page will just start hanging. 

Umbraco V7.14

### Steps to reproduce
1 - Go to the **Members** section
2 - Under the **Members** tree select **Member**
3 - Create a member by filling in all the required fields
4 - Click **Save**
5 - Clicking the **Save** button again will make the page hanging

### Expected result
Get a message that the member is saved - ex: "Member saved: Member saved" - as it happens for a Content item

### Actual result
The **Save** button indicates hanging (loading circle appears) and the error ` Cannot read property 'reset' of null` is caused in the `MemberEditController`

**Comment by kjac** [comment]
Turns out this is a bit more critical than initially reported; you can't save a member at all without resetting the member password! This applies to both V7 and V8.

PRs for fixing it in #5798 (V8) and #5799 (V7).

**Comment by nul800sebastiaan** [comment]
Thanks very much once again for all the help @kjac !
