### ISSUE TITLE
V8: Ability to add a custom validation feedback

### ISSUE THREAD

**Issue by nielslyngsoe** [umbraco/Umbraco-CMS#5702]
I would like to be able to write a custom validation feedback message. To help content creators move forward in this scenario: 

![image](https://user-images.githubusercontent.com/6791648/59912366-33289600-9416-11e9-9f84-6b10e585f005.png)

I think it's fine to just provide one formulation of the feedback-message, written in the language the developer decides.

---
_This item has been added to our backlog [AB#3606](https://umbraco.visualstudio.com/243e7927-03b2-44e2-908f-d4ac7ea5daaa/_workitems/edit/3606)_

**Comment by AndyButland** [comment]
I had [this PR](https://github.com/umbraco/Umbraco-CMS/pull/1479) open for a while that was intended for this same issue.  It's closed now, as was targeting V7, and haven't re-done as it didn't get much response previously - but could look to recreate if it looks to do what you are looking for here and it was felt it would get more traction now.

**Comment by nielslyngsoe** [comment]
Hi @AndyButland, I'm sorry that you have been given the feeling of this feature not begin relevant. I personally think this feature is super important. Super important to help provide a friendly validation.

From my point of view it was though only important to enable the possibility to write a custom 'validationRegExpMessage'. But since you'r PR also was able to set a custom 'mandatoryMessage' I would like to be enlighten with the case for this possibility? Can I ask you to elaborate, maybe share the scenario that you want to accomplish?

And just to be clear, the 'validationRegExpMessage' is a must have in my opinion, so please feel free to make a new PR with it. I will make sure to let @nul800sebastiaan know that we would like this, so it can be approved and merged when ready.

Thanks

**Comment by AndyButland** [comment]
No problem, it was speculative at the time I believe, but when I saw you'd posted an issue that looked to be the same it was looking to solve, so seemed relevant to note.  I'll have a look at resurrecting for V8, or if anyone else wants to, there might be some work in there that can be reused.

**Comment by AndyButland** [comment]
New PR targetting V8 is [here](https://github.com/umbraco/Umbraco-CMS/pull/5738/).

**Comment by nul800sebastiaan** [comment]
Thanks @AndyButland - as @nielslyngsoe already mentioned, I'm also trying to figure out the use-case for adding a custom `mandatoryMessage`, can you elaborate on that one please? 🙂

**Comment by AndyButland** [comment]
Just seemed "friendlier" I thought - so rather than just saying "Required" under a field, you could have "Please enter a title for the article" or similar.

In the same way that with an MVC application you'd likely use the attributes with a custom message: `[Required(ErrorMessage = "Title is required.")]`.
