### ISSUE TITLE
Umbraco 8 doesn't honour umbracoCssDirectory

### ISSUE THREAD

**Issue by andersbrohall** [umbraco/Umbraco-CMS#5707]
web.config/appsettings/add[key=umbracoCssDirectory] values aren't honoured in the Umbraco 8 Backoffice (When creating a Stylesheet, when trying to link Stylesheets to a RTE). 

Reproduction
------------
Try create a Stylesheet in umb 8.02, below the input for Name the pats is printed out, /css/. Even though web.config/appsettings/add[key=umbracoCssDirectory] is set to "~/Styles"

**Comment by nul800sebastiaan** [comment]
It's `umbracoCssPath` you should be using. Looks like the documentation has a mistake in it, maybe (if this works for you) you can send a PR to get that fixed? https://our.umbraco.com/documentation/Reference/Config/webconfig/#umbracocssdirectory

**Comment by nul800sebastiaan** [comment]
A few more things have changed in those docs actually, `umbracoUseSSL` is replaced with `Umbraco.Core.UseHttps` and maybe there's more.

Reference: https://github.com/umbraco/Umbraco-CMS/blob/v8/dev/src/Umbraco.Core/Constants-AppSettings.cs#L89

And: https://github.com/umbraco/Umbraco-CMS/blob/v8/dev/src/Umbraco.Core/IO/SystemDirectories.cs
