### ISSUE TITLE
Dashboards not obeying c# access rules

### ISSUE THREAD

**Issue by Slipoch** [umbraco/Umbraco-CMS#5708]
When using multiple access rules, Umbraco allows access to a dashboard even when deny is logged against that group.

Reproduction
------------
 ```
var rules = new IAccessRule[] {
                    new AccessRule() { Type = AccessRuleType.Deny,  Value = "aBRIManager" },
                    new AccessRule() { Type = AccessRuleType.Grant, Value = Umbraco.Core.Constants.Security.AdminGroupAlias },
                    new AccessRule() { Type = AccessRuleType.Deny,  Value = Umbraco.Core.Constants.Security.SensitiveDataGroupAlias },
                    new AccessRule() { Type = AccessRuleType.Deny,  Value = Umbraco.Core.Constants.Security.TranslatorGroupAlias },
                    new AccessRule() { Type = AccessRuleType.Deny,  Value = "editor" },
                    new AccessRule() { Type = AccessRuleType.Grant, Value = "hrAdmin" } };
```

relevant information as possible, such as:

### Specifics

Umbraco version: 8.0.2
browser etc. N/A

### Steps to reproduce

Create a dashboard, add more than one rule in C#.

### Expected result

I expected rules to be followed eg: aBRIManager does not see the tab for the dashboard and cannot see the page for it.

### Actual result

All logins that have access to the section see the dashboard tab and can access the page.

**Comment by nul800sebastiaan** [comment]
I can reproduce, this is a bug which should be fixed in https://github.com/umbraco/Umbraco-CMS/pull/5717

Thanks for reporting! 👍
