### ISSUE TITLE
Markdown editor link picker 

### ISSUE THREAD

**Issue by Matthew-Wise** [umbraco/Umbraco-CMS#5714]
Umbraco v8.0.2:

The Markdown editor link picker throws a console error when clicked.

Reproduction
------------

### Steps to reproduce

- Create a new doc type
- Add a markdown editor property
- Edit the property value on a content node
- Click the link picker

### Expected result
- Link modal / dialogue will show, allowing the user to pick the link location

### Actual result
console error is throw.

```
$(dialog).modal()
"TypeError: $(...).modal is not a function"
```
/umbraco/lib/markdown/markdown.editor.js line 1133

**Comment by nul800sebastiaan** [comment]
I can reproduce, also still a problem in 8.1.0.

I've marked this as "Up for grabs" so that you or someone else coming along could create a pull request for it.

**Comment by kjac** [comment]
I've got this; might as well make use of the built-in link picker while we're at it.

**Comment by kjac** [comment]
PR in #5745

**Comment by nul800sebastiaan** [comment]
Fixed in https://github.com/umbraco/Umbraco-CMS/pull/5745
