### ISSUE TITLE
v8: Custom Listview embedded editor is not saved when saving DocType

### ISSUE THREAD

**Issue by robmaas** [umbraco/Umbraco-CMS#5723]
When editing a custom listview directly from a DocType it is unclear that the embedded listview editor has it's own Save button (it requires quite a bit of scrolling down to see it).
Users are very likely to use the DocType's Save button instead (since it is fixed to the bottom of the page).
However, when using the DocType Save button the custom listview's properties are not persisted, nor a Discard-changes popup is shown.

Reproduction
------------

### Steps to reproduce
- Edit a custom listview directly from a DocType by using the List View app and the Gear icon.
- Change a property of the custom listview (for example pagesize).
- Press the DocType Save button

### Expected result
Either the custom listview is saved as well or a Discard-changes popup is shown to alert the user that the changes to the listview will be discarded.

### Actual result
The DocType is saved, but changes to the listview are discarded without notification.

**Comment by nul800sebastiaan** [comment]
You're absolutely right, we want to go a step further and open the configuration of a list view as an infinite editor, see this issue: https://github.com/umbraco/Umbraco-CMS/issues/5021
