### ISSUE TITLE
V8.1 - create folder not working in several places

### ISSUE THREAD

**Issue by dawoe** [umbraco/Umbraco-CMS#5750]
A brief description of the issue goes here.

In several places in the settings section several actions from the create dialogue are not working anymore. If you click on the action the dialogoue will be close.

This is on the latest v8.1 source.

![folder create](https://user-images.githubusercontent.com/1193822/60418809-29f0b380-9be4-11e9-9606-b28928abb430.gif)

I discovered following actions that are not working : 

### Settings section

**Documenttypes** 

- Documenttype collection
- Folder

**Media types**
- Folder

**Datatypes**
- Folder

**Partial views**
- New Partial view from snippet
- Folder

**Partial view macro files**
- New Partial view macro from snippet
- Folder

** Stylesheets ** 
- Folder

** Javacript ** 
- Folder

There are no errors logged in the console when this happens. Probably all these are cause by the same issue. There maybe other places in the backend where this occurs.

Dave

**Comment by dawoe** [comment]
It seems to work again if I revert the changes from PR #5609 

@kjac any idea how to fix ?

Dave

**Comment by kjac** [comment]
Geez. I'll have a look later today. Something to do with preventing default I reckon.

**Comment by dawoe** [comment]
PR is incoming

Maybe you could check it to see everything you fixed still works

**Comment by dawoe** [comment]
PR is created

**Comment by kjac** [comment]
Cool I'll have a look at it later 😀
