### ISSUE TITLE
V8: Mandatory colour picker can't be saved

### ISSUE THREAD

**Issue by AndyButland** [umbraco/Umbraco-CMS#5761]
To replicate:

- Create a data type based on the "Color Picker"
- Add a few colours
- Create a property on a document type using the new data type
- Make it mandatory
- Try entering content based on the document type
- Even if a colour value is selected, the property is marked as invalid

![image](https://user-images.githubusercontent.com/1993459/60488195-a1d0e380-9ca1-11e9-927f-441284a6a1ab.png)

Why?  Not quite figured it out, but having added a few `console.log()`s it seems that the `val-property-validator` referenced in `colorpicker.html` is firing only when the content is loaded, and not re-firing when the value is changed or the save & publish button it clicked.  So doesn't seem that this is working as intended.

**Comment by kjac** [comment]
By the looks of it the color picker needs a bit of cleaning and redo. I can replicate and I _think_ I have a solution.

**Comment by kjac** [comment]
PR in #5765

**Comment by nul800sebastiaan** [comment]
Fixed in https://github.com/umbraco/Umbraco-CMS/pull/5765

Cherry picked for 8.1.5 32941370065fcbea6857ad9c68a16a93c839812a
