### ISSUE TITLE
V8: Mandatory check-box list isn't validated

### ISSUE THREAD

**Issue by AndyButland** [umbraco/Umbraco-CMS#5762]
To replicate:

- Create a data type based on the "Checkbox list"
- Add a few options
- Create a property on a document type using the new data type
- Make it mandatory
- Try entering content based on the document type
- Whether or not a check box is checked, the property isn't marked as invalid.  I'd expect it should be if no value is checked.

![image](https://user-images.githubusercontent.com/1993459/60488569-9a5e0a00-9ca2-11e9-9449-f0eefa556e21.png)

This does look like a bug rather than something not implemented for this property editor, as the `mandatory` property is referenced in the `checkboxlist.html` file.

**Comment by kjac** [comment]
I believe this is a simple view error; I'll submit a fix shortly.

Rather unfortunate that the property editor isn't validated server side, though... 😨

**Comment by kjac** [comment]
PR in #5780

**Comment by nul800sebastiaan** [comment]
Fixed in https://github.com/umbraco/Umbraco-CMS/pull/5780
Cherry picked for 8.1.5 - 9c12b4ee40cc9d51adcc78fa47dd3d072024244f
