### ISSUE TITLE
Nested content dialog does not follow specified sort order

### ISSUE THREAD

**Issue by dnwhte** [umbraco/Umbraco-CMS#5769]
### Bug summary

Nested content dialog does not follow specified sort order.

### Specifics

Umbraco 7.14

### Steps to reproduce

Create a nested content data type with at least two doc types selected. Order them in a non-alphanumeric order. Create some content with the new data type. Selected doc types will not follow specified order. 

### Expected result

Nested content dialog will order doc types as specified in the data type configuration.

### Actual result

Nested content dialog orders doc types alphanumerically regardless of configuration.

--- 

![1](https://user-images.githubusercontent.com/636470/60541336-3c431e00-9cc6-11e9-9686-baab3cf5aba3.PNG)
![2](https://user-images.githubusercontent.com/636470/60541339-3ea57800-9cc6-11e9-8450-7fe1b700288e.PNG)

**Comment by kjac** [comment]
I fixed this for V8, will be part of V8.1 ... I can look into a fix for V7 as well, if it's not too late to submit fixes?

**Comment by nul800sebastiaan** [comment]
@kjac We're still doing patch releases for 7.15. This is a bug and not a new feature, so it's fine to fix for v7 :)

**Comment by kjac** [comment]
@nul800sebastiaan roger that! PR in #5777

**Comment by nul800sebastiaan** [comment]
Fixed in #5777 
Cherry picked for 7.15.3 4c5365de1c60178f44bf132872cd54d883fb8c50
