### ISSUE TITLE
MNTP "Allow items of type" doesn't work at root

### ISSUE THREAD

**Issue by dnwhte** [umbraco/Umbraco-CMS#5770]
### Bug summary

Editors can select an item of any type, at the root, regardless of data type configuration. 

### Specifics

Umbraco 7.14

### Steps to reproduce

Create a MNTP data type and specify a type in "Allow items of type". Test the data type to see which node types are selectable.

### Expected result

Only types specified in "Allow items of type" should be selectable at all levels of the tree.

### Actual result

Editors can select an item of any type at the root of the tree.

---
![3](https://user-images.githubusercontent.com/636470/60541818-3d287f80-9cc7-11e9-9dd0-c4ff2111b609.PNG)
![4](https://user-images.githubusercontent.com/636470/60541822-3f8ad980-9cc7-11e9-9edd-0425705d9803.PNG)

**Comment by nul800sebastiaan** [comment]
Thanks @dnwhte, this was fixed for 7.15 already! 👍 

https://github.com/umbraco/Umbraco-CMS/issues/5137

I can only pick Files

![image](https://user-images.githubusercontent.com/304656/60612484-00dd4800-9dc9-11e9-8479-c15a86243a74.png)
