### ISSUE TITLE
V8 Client Dependency - Automated Incrementing

### ISSUE THREAD

**Issue by tristolliday** [umbraco/Umbraco-CMS#5775]
A simple way to increment client dependency version number automatically on deployment to a production server.

Problem:
Front end developers update CSS & JS, commit and are happy with the changes. Back end developers deploy, but forget to increment client dependencies, front end of solution breaks on live.

**Comment by nul800sebastiaan** [comment]
Hey there, this is up to you on deploy, make sure to commit the increment to your source control or trigger it on the build server. For example on our build server for Our Umbraco we execute the following powershell script: 

```
$cdconfig = Join-Path (pwd) ClientDependency.config
[xml]$config = Get-Content $cdconfig
$config.clientDependency.SetAttribute("version", "$(Build.BuildNumber)")
$config.Save($cdconfig)
```

**Comment by tristolliday** [comment]
@nul800sebastiaan how does this apply to users of the Umbraco SaaS platform, as we do not have access to the build script as we flow between dev/staging/live?
