### ISSUE TITLE
In language file en_us.xml & en.xml "content type" is used instead of "document type" in several places.

### ISSUE THREAD

**Issue by idseefeld** [umbraco/Umbraco-CMS#5779]
Especially section `<area alias="contentTypeEditor">` needs to be reviewed. 
The current usage of content, document, content type and document type is somehow confusing or misleading.

I'll start working on this and submit a PR when done!

Yours
Dirk

**Comment by bjarnef** [comment]
Content type is a more general term for both document types, media types and member types.
So many of these keys are also using for media types and member types.
https://github.com/umbraco/Umbraco-CMS/blob/b98812b119aafa54d33edbace62bd5e387f0e6a0/src/Umbraco.Web.UI/Umbraco/config/lang/en.xml#L1548-L1604

But some of it are specific to document, media or member types.
https://github.com/umbraco/Umbraco-CMS/blob/b98812b119aafa54d33edbace62bd5e387f0e6a0/src/Umbraco.Web.UI/Umbraco/config/lang/en.xml#L1578-L1580

**Comment by nul800sebastiaan** [comment]
As Bjarne mentions, this is on purpose so we can easily share things between Member Types, Media Types and Document Types. We should not need to change this though. I'll close this issue as we're happy with the current translation keys.
