### ISSUE TITLE
Padding for nested content in split view (multiple languages) unusable

### ISSUE THREAD

**Issue by Derds** [umbraco/Umbraco-CMS#5781]
When adding nested content in split language view the layout becomes almost unusable - just wanted to add this as a bug.

I know that custom CSS can be added to the back-office but not sure where to start with this so that the styling is still usable on this page but doesn't negatively affect every other content page.

![image](https://user-images.githubusercontent.com/22679551/60602885-96b6aa00-9dac-11e9-9ce4-a0544584b1aa.png)

Reproduction
------------

### Bug summary

Padding for nested content in split view is quite unusuable

### Specifics

Using Umbraco 8.0.2
Using chrome - but also doesnt work in firefox and ie

### Steps to reproduce

    * Create a multi-language site
    * Create a nested content node
    * Try to edit nested content with the split view screen open

### Expected result

    The padding should be such that the links to the other parts of the site are readable 
and functionality is usable on most normal browser sizes

### Actual result

>difficult to see all the inputs
>textboxes falling off edge of containers
>difficult to add and remove nodes

**Comment by nul800sebastiaan** [comment]
Thanks for the report @Derds! 

The good news is that it looks like this issue is already fixed for the upcoming version 8.1.0 (coming next week).

This is what it looks like on 8.1.0, much better :-)

![image](https://user-images.githubusercontent.com/304656/60620977-dac1a300-9ddc-11e9-8f45-625ee8c11d2f.png)
