### ISSUE TITLE
U8: umbracoUrlName hypenates forward slashes. 

### ISSUE THREAD

**Issue by bmargevicius** [umbraco/Umbraco-CMS#5782]
Trying to set the umbracoUrlName on a custom route. I don't know if this is the key or not. But setting the umbracoUrlName text string property with '/' gets changed into hyphens. Googling around makes it seem that you can set / in the umbracoUrlName property. 
![UmbracoUrlNameHypheningWeirdness](https://user-images.githubusercontent.com/24920023/60618189-85b56b00-9da3-11e9-9db1-5d0bebda0251.gif)

**Comment by zpqrtbnk** [comment]
The umbracoUrlName property can be used to change the _url segment_ of a document, ie the part that goes _between_ slashes. If your document is named "Foo", its url segment is going to be "foo" and the url... "/path/to/foo" - you may use the umbracoUrlName to indicate that the segment should be "bar", and the url would become "/path/to/bar" - but a _segment_ cannot contain slashes - hence, slashes are indeed replaced with dashes.

In other word: umbracoUrlName does not support what you are trying to do.

**Comment by Shazwazza** [comment]
IIRC I think `umbracoUrlAlias` is what you might want where you can specify any full URL (i.e. 'slug')

**Comment by bmargevicius** [comment]
How does this happen then and how to I make it happen programatically?

![image](https://user-images.githubusercontent.com/24920023/60815846-78fb9300-a166-11e9-8f73-16b6f18c1cda.png)

**Comment by abjerner** [comment]
@bmargevicius given the information provided in your last screenshot, the `food-and-drink` most likely comes from the parent page. That's how Umbraco determines the URL out of the box.

**Comment by bmargevicius** [comment]
I figured 🤷‍♂. So my workaround is to use the urlAlias and determine the route from there. =

🎆 🎆 🎆 Thanks @all for taking the time to look into this. 🎆 🎆 🎆
