### ISSUE TITLE
V8 Umbraco.ContentQuery.Search returns no results

### ISSUE THREAD

**Issue by cleversolutions** [umbraco/Umbraco-CMS#5789]
### Bug summary
Using SK, executing Umbraco.ContentQuery.Search("Products", "ExternalIndex") returns no results, while using the ExaminManagement search in the backoffice returns 4 results. The simple ContentQuery.Search should return the same results as the backoffice search.

### Specifics
- Starter Kit (or any site, but the SK is consistent for everybody)
- V8/dev (also 8.0.2)
- Chrome (but this isn't a browser bug)
- Didn't check it in other browsers
- No error message, this is a delta between what is expected and what occurs

### Steps to reproduce

1.  Create new V8/dev site with SK
2.  Add to the Home.cshtml view the following:
```
    @{
        var easySearch = Umbraco.ContentQuery.Search("Products", "ExternalIndex");
        <div>Found @easySearch.Count() results the easy way.</div>
    }
```
3. Run and check out the site, it lists 0 results the easy way,

### Expected result
Search results are rendered when you perform the easy search using the simple one line method. I think a lot of devs will expect the simple 1 liner way of searching to just work as it did in V7.

### Actual result
No results are found

### Work around
Use the following code in your view for a simple Examine search instead:
```
        ExamineManager.Instance.TryGetIndex("ExternalIndex", out var index);
        var searcher = index.GetSearcher();
        var results = searcher.Search("Products", 100);
        <div>Found @results.Count() results the longer way</div>
```

### A little further digging
In PublishedContentQuery stick a break point on `if (culture.IsNullOrWhiteSpace())` and force execution of line `results = searcher.Search(term, count);` and you get 4 results (as expected). Normal execution runs down the else block which produces a radically different Lucene search. 
It seems that `culture = culture ?? _variationContextAccessor.VariationContext.Culture;` always returns a default culture (in my case en-US), so execution always flows into the else block.

---
_This item has been added to our backlog [AB#1697](https://umbraco.visualstudio.com/243e7927-03b2-44e2-908f-d4ac7ea5daaa/_workitems/edit/1697)_

**Comment by Zwaai** [comment]
I'm having the same problem with multiple Umbraco websites without configured cultures. 
Websites which **do** have cultures configured don't seem to be having this problem. Just as you describe.

Currently working with version 8.0.2

**Comment by Shazwazza** [comment]
The problem seems that you are calling the methods with incorrect parameters. The method signatures for IPublishedQuery.Search in v8 are:

```cs
IEnumerable<PublishedSearchResult> Search(string term, string culture = null, string indexName = null);

IEnumerable<PublishedSearchResult> Search(string term, int skip, int take, out long totalRecords, string culture = null, string indexName = null);

IEnumerable<PublishedSearchResult> Search(IQueryExecutor query);

IEnumerable<PublishedSearchResult> Search(IQueryExecutor query, int skip, int take, out long totalRecords);
```

The syntax you are using is 

```cs
var easySearch = Umbraco.ContentQuery.Search("Products", "ExternalIndex");
```

Which means you are passing in the string "ExternalIndex" to the `culture` parameter. 

Your options are to change your method call to one of these:

* `var easySearch = Umbraco.ContentQuery.Search("Products");` - which by default will query the ExternalIndex
* `var easySearch = Umbraco.ContentQuery.Search("Products", indexName: "ExternalIndex");` - to explicitly pass the string "Externalndex" to the right parameter
* `var easySearch = Umbraco.ContentQuery.Search("Products", null, "ExternalIndex");` - to pass all parameter values in the correct order

**Comment by Shazwazza** [comment]
aha, but i see that's not the only issue... working on it.

**Comment by Shazwazza** [comment]
PR https://github.com/umbraco/Umbraco-CMS/pull/5862
