### ISSUE TITLE
v8: Change password from user dialog doesn't work

### ISSUE THREAD

**Issue by bjarnef** [umbraco/Umbraco-CMS#5808]
I just tried the latest release Umbraco v8.1.0 and it seems the "change password" from user dialog doesn't work.

Reproduction
------------

### Bug summary
Open the user dialog/overlay via the avatar and click the "change password" button.
The dialog close and the change password form as previous is not shown.

### Specifics

Umbraco v8.1.0
Google Chrome Version 75.0.3770.100

### Expected result
Clicking the "change password" button in the user dialog/overlay should show the change password form.

### Actual result
This dialog is just closing.

![image](https://user-images.githubusercontent.com/2919859/60875942-35bf2400-a23b-11e9-9c85-7a4c02d986f9.png)

**Comment by Shazwazza** [comment]
The problem with several all of these types of bugs was with this PR https://github.com/umbraco/Umbraco-CMS/pull/5609

I have reverted these changes https://github.com/umbraco/Umbraco-CMS/pull/5609#issuecomment-510709482

So all of these things work again.
