### ISSUE TITLE
v8: Overlays have horizontal scrollbar

### ISSUE THREAD

**Issue by bjarnef** [umbraco/Umbraco-CMS#5809]
In Umbraco v8.1.0 it seems the overlays have some horizontal scrollbar, e.g. right-click document types -> create.

Furthermore the "footer" of the overlay cover the bottom part of the "body" of the overlay, so the scrollbar isn't selectable.

![image](https://user-images.githubusercontent.com/2919859/60876169-a8300400-a23b-11e9-8396-ab71970d665a.png)

**Comment by kjac** [comment]
This has already been fixed, see https://github.com/umbraco/Umbraco-CMS/pull/5754

**Comment by nul800sebastiaan** [comment]
Fixed in https://github.com/umbraco/Umbraco-CMS/pull/5754
