### ISSUE TITLE
v8.1: Custom routes - content cache

### ISSUE THREAD

**Issue by pralthom** [umbraco/Umbraco-CMS#5812]
Hi,

I've just upgraded to V 8.1 and I've a problem with my code.
I have a custom route composer file which looks like this:

```
public class RegisterCustomRouteComposer : ComponentComposer<RegisterCustomRouteComponent>
    {

    }

    public class RegisterCustomRouteComponent : IComponent
    {
        private readonly IUmbracoContextFactory _context;
        
        public RegisterCustomRouteComponent(IUmbracoContextFactory context)
        {
            _context = context;
        }
        
        public void Initialize()
        {
            // usage of the umbraco context
            using (var cref = _context.EnsureUmbracoContext())
            {
                // Find all nodes of TDFormation and create a new route for them
                var cache = cref.UmbracoContext.Content;
                var formationsNodes = cache.GetByXPath("//TDFormation").ToArray();

                foreach (var node in formationsNodes)
                {
                  //build the routes
```

Umbraco crashes because of the following line:
`var cache = cref.UmbracoContext.Content;`

After debugging I can see the UmbracoContext has no Content
![image](https://user-images.githubusercontent.com/44721265/60878575-42924680-a240-11e9-9213-404c1e1b517e.png)

The error message:
`The published snapshot service has not properly initialized.`

Does anybody know what I'm doing wrong? Do I have to initialize the snapshot service manually?

Thank you in advance for the help!

**Comment by Shazwazza** [comment]
It's because you are using `IComposer` and not `IUserComposer` so you are executing code before Umbraco is ready, see https://our.umbraco.com/Documentation/Implementation/Composing/

**Comment by pralthom** [comment]
> It's because you are using `IComposer` and not `IUserComposer` so you are executing code before Umbraco is ready, see https://our.umbraco.com/Documentation/Implementation/Composing/

Thank you for the explanation!
I'll try with the IUserComposer
