### ISSUE TITLE
v8: Add space between label and value in grid layout

### ISSUE THREAD

**Issue by bjarnef** [umbraco/Umbraco-CMS#5813]
In listview grid layout, e.g. with in default starterkit and Umbraco v8.1.0

There should be a bit space between the label and value.

![image](https://user-images.githubusercontent.com/2919859/60881145-57bda400-a245-11e9-86af-843e9989b820.png)

![image](https://user-images.githubusercontent.com/2919859/60881227-876cac00-a245-11e9-81df-663a8832bed5.png)

**Comment by nul800sebastiaan** [comment]
Fixed in https://github.com/umbraco/Umbraco-CMS/pull/5824

Cherry picked for 8.1.5 105dd989de3d3271c38de3174f27cbfb1d3e7655
