### ISSUE TITLE
V7: MNTP XPath allowing disabled DocTypes when nodes are missing or unpublished

### ISSUE THREAD

**Issue by ReVoid** [umbraco/Umbraco-CMS#5814]
Hello, Umbraco. 

Multi-Node Treepicker allow disabled DocTypes nodes (some of them) when it can't find target nodes of allowed types

Reproduction
------------

### Specifics

Umbraco 7.14

### Steps to reproduce

1. Create a property editor of Multi-node Treepicker
2. Set some XPath query, like in my case: `$current/ancestor-or-self::homePage//catalogPage`, where `homePage` is your root node alias and `catalogPage` - any descendant alias you want to search in, then set `Allow items of type` field as your target type you want to be selected, (`productPage` in my case).
3. Add the property editor in any of your root node descendants, publish your targer nodes (`productPage` in my case)
4. Try to select target nodes with your picker, everthing must be well
5. Unpublish your `catalogPage` nodes
6. Try to pick it again with your picker, now others node allowed too.
7. Try to collapse root node and then expand it again, now all nodes are dissabled except allowed
![mltp bug](https://user-images.githubusercontent.com/12345710/60883227-4fb83100-a252-11e9-9349-98e44570eba5.gif)

### Expected result

No nodes shown as query result, impossible not select dissabled nodes

### Actual result

Whole content tree shown as query result, almost every node are allowed

**Comment by nul800sebastiaan** [comment]
We fixed something similar in 7.15.0, can you reproduce this on a 7.15.0 install?

FYI: 7.15 was released today: https://umbraco.com/blog/umbraco-715-release/

**Comment by ReVoid** [comment]
@nul800sebastiaan Great, the fastest bugfix I've ever seen =) 
Yep, I can not reproduce it in 7.15!

For now, I checked only with `$$current/ancestor-or-self::homePage` axis, I'll check other cases today, don't close issue right now, please.

Thanks! Now we can count on MNTP in compicated cases =)

**Comment by nul800sebastiaan** [comment]
I'll be mean and close it for now, else I'll forget. Just let me know if an upgrade doesn't fix it! ;-)

**Comment by ReVoid** [comment]
@nul800sebastiaan No problem :)
