### ISSUE TITLE
Impossible to remove assigned hostname

### ISSUE THREAD

**Issue by mzajkowski** [umbraco/Umbraco-CMS#5815]
Version 8.1.0.

When editing content nodes and after the hostname is assigned to the node, it's not possible to remove it. When recycle bin icon is clicked -> modal window dissapear and selection / assignement stay as it is.

Reproduction
------------

### Steps to reproduce

1. Create content node (e.g. on the root level).
2. Assign domain / hostname to it.
3. Save.
4. Try to remove any of the assigned domain / hostname.

### Expected result

Removed domain / hostname from node.

### Actual result

Modal window closed = no action.

**Comment by nul800sebastiaan** [comment]
Uh oh! This looks familiar to something else @kjac has worked on before, can't remember exactly what it was though? 🤔

**Comment by kjac** [comment]
Uh ouh! Sounds vaguely familiar, although I'm sure that goes for just about anything by now.

I can give it a look when I'm home from holiday on Friday.

**Comment by Shazwazza** [comment]
The problem with several all of these types of bugs was with this PR https://github.com/umbraco/Umbraco-CMS/pull/5609

I have reverted these changes https://github.com/umbraco/Umbraco-CMS/pull/5609#issuecomment-510709482

So all of these things work again.
