### ISSUE TITLE
Bug report on a bug report ;-)

### ISSUE THREAD

**Issue by RachBreeze** [umbraco/Umbraco-CMS#5825]
The instructions for a bug report say:

> See: https://github.com/umbraco/Umbraco-CMS/blob/dev-v7/.github/CONTRIBUTING.md

This is returning a 404 for me

**Comment by bjarnef** [comment]
Yes, it should be changed to this:
https://github.com/umbraco/Umbraco-CMS/blob/v7/dev/.github/CONTRIBUTING.md

or for v8:
https://github.com/umbraco/Umbraco-CMS/blob/v8/dev/.github/CONTRIBUTING.md

**Comment by RachBreeze** [comment]
Hi 
It looks like it is something that HQ have to change as it's on the bug reporting template.

**Comment by bjarnef** [comment]
Ahh yes, it is the bug report templates on GitHub under settings, not in the source code.
@nul800sebastiaan

**Comment by nul800sebastiaan** [comment]
Thanks 👍 fixed in : https://github.com/umbraco/Umbraco-CMS/commit/943b54dcf7713617c529c10edd115d65e0078f1b
