### ISSUE TITLE
[8.1] selecting a dropdown value, closes the dialog

### ISSUE THREAD

**Issue by skttl** [umbraco/Umbraco-CMS#5830]
![gif](https://i.imgur.com/qhPm9NH.gif)

This is maybe a dupe of #4934 or #3391 (the dropdownitems is `<a>`s with a ng-click directive attached. They should probably be `<button>`s instead.

**Comment by bjarnef** [comment]
It mi

**Comment by nul800sebastiaan** [comment]
Oh that is annoying, we'll need to fix this in Deploy.

**Comment by Shazwazza** [comment]
The problem with several all of these types of bugs was with this PR https://github.com/umbraco/Umbraco-CMS/pull/5609

I have reverted these changes https://github.com/umbraco/Umbraco-CMS/pull/5609#issuecomment-510709482

So all of these things work again.
