### ISSUE TITLE
umbDateTimePickerDirective doesn't have a dependency on moment.js

### ISSUE THREAD

**Issue by cmwalolo** [umbraco/Umbraco-CMS#5832]
umbDateTimePickerDirective doesn't have a dependency on moment.js. The scheduled publication and unpublication does not work if no datepicker has been loaded in front

The assetService should ensure that the moment.js is loaded. For now only the datetimepicker.css and .js are loaded.

Version of umbraco 7.12.3

**Comment by nul800sebastiaan** [comment]
Hey @cmwalolo - I'm going to ask you to try and reproduce this in the latest version. If it's still a problem in 7.15.0 then we can have it looked at and fix it! 

Let me know if you can reproduce in 7.15.0 :-)

**Comment by netaddicts** [comment]
@nul800sebastiaan Hi Seb, just a heads up, wasn't able to repro in 7.15. Clean install, single doc type with no props, scheduled publish/unpublish working properly!
