### ISSUE TITLE
Issue with dialogService.linkpicker after 7.15 upgrade

### ISSUE THREAD

**Issue by pauldequant** [umbraco/Umbraco-CMS#5835]
Hello,

After upgrading Umbraco from 7.14 to 7.15, we have encountered an issue where by anything that uses a **dialogService.linkpicker** doesn't work i.e the content tree doesn't load (shows as {{tree.name}}).

The browser console shows the following error:-

_Cannot read property 'dataTypeId' of undefined_

Which we've tracked down it down to this file:-

/umbraco/js/umbraco.controller.js

The code below was from 7.14

`        $scope.searchInfo = {
            searchFromId: null,
            searchFromName: null,
            showSearch: false,
            results: [],
            selectedSearchResults: []
        };
`

And the code from 7.15

`        $scope.searchInfo = {
            searchFromId: null,
            searchFromName: null,
            showSearch: false,
            dataTypeId: $scope.model.dataTypeId,
            results: [],
            selectedSearchResults: []
        };`

If we remove the extra line : dataTypeId: $scope.model.dataTypeId it works again.

---
_This item has been added to our backlog [AB#1693](https://umbraco.visualstudio.com/243e7927-03b2-44e2-908f-d4ac7ea5daaa/_workitems/edit/1693)_

**Comment by nul800sebastiaan** [comment]
I need some more context here, how the error `Cannot read property 'dataTypeId' of undefined` indicates that `$scope.model` is undefined, can you explain how that might have happened? 

How are you using `dialogService.linkpicker`, do you have example code for us to try out?

**Comment by pauldequant** [comment]
We're using it in a $scope.overlay, so when you click the browse button to pick the URL (and the side panel comes in from the right) you get the error.

Here's a snippet of the code:-

`                    setLinkSrc: function () {

                        dialogService.linkPicker({
                            callback: function (data) {
                                $scope.control.value.linkObj = {
                                    id: data.id,
                                    udi: data.udi,
                                    name: data.name,
                                    url: data.url
                                };
                            }
                        });`
