### ISSUE TITLE
[U8] Unable to set Permissions on Content Nodes

### ISSUE THREAD

**Issue by hfloyd** [umbraco/Umbraco-CMS#5838]
Observed in Umbraco 8.1.0 (local environment for Cloud site)

When I attempt to set permissions via group on a Content node, the initial dialog displays, but nothing happens when I choose the group I'd like to set the permissions for. 

See video demo: 
[https://screencast-o-matic.com/watch/cqi6FDO2kZ](https://screencast-o-matic.com/watch/cqi6FDO2kZ)

**Comment by nul800sebastiaan** [comment]
Thanks @hfloyd, that's not quite the user experience we were going for. We'll fix!

**Comment by Shazwazza** [comment]
The problem with several all of these types of bugs was with this PR https://github.com/umbraco/Umbraco-CMS/pull/5609

I have reverted these changes https://github.com/umbraco/Umbraco-CMS/pull/5609#issuecomment-510709482

So all of these things work again.
