### ISSUE TITLE
V8: RelatedLinks error - migration from V7.15 - V8.1

### ISSUE THREAD

**Issue by dinc5150** [umbraco/Umbraco-CMS#5840]
When I upgraded from V7.15.0 to V8.1.0 I got a null reference exception error during the migration process. 

Reproduction
------------

If you're filing a bug, please describe how to reproduce it. Include as much
relevant information as possible, such as:

### Bug summary

I upgraded a website from V7.15.0 to V8.1.0 with existing content. Some of the pages had no related links picked in the RelatedLinks Property

### Steps to reproduce
Create content with a related Links Picker and dont pick any links. Then Upgrade to V8+

### Expected result

Migrated Content!

### Actual result

Error during Install Step:
```
The database failed to upgrade. ERROR: The database configuration failed with the following message: Object reference not set to an instance of an object. Please check log file for additional information (can be found in '/App_Data/Logs/')
```

## Note:
I have a pull request on its way

**Comment by Shazwazza** [comment]
Duplicate https://github.com/umbraco/Umbraco-CMS/issues/5903#issuecomment-513113360
