### ISSUE TITLE
upgrade from 8.0.2 to 8.1.0 in public access the dialog you have unsaved changes is showing with every click

### ISSUE THREAD

**Issue by krgy** [umbraco/Umbraco-CMS#5844]
I get with every click in "public access" the popup "you have unsaved changes" 

Reproduction
------------
When you want to add "public access" to a page and select "group based protection"
You need to select the group , login page and error page.
After i select a member group i get the popup " you have unsaved changes" i click "stay"
Then i want to select my login page and every time i click on a tree item to navigate to the login page it ask me  "you have unsaved changes" i always click "stay"
same behavior  for error page selection

### Bug summary

the popup " you have unsaved changes" is coming every time and it should not be displayed here

### Specifics
Umbraco 8.1.0 after upgrading from Umbraco 8.0.2

### Expected result
the popup " you have unsaved changes" should not be showed every time.

**Comment by nul800sebastiaan** [comment]
I can reproduce, that's annoying, sorry about that! :)

**Comment by kjac** [comment]
Yeah this was caused by #5740 ... PR to fix in #5872 

Just to clarify, this issue can be reproduced by:

1. Make a change to either member, group or login/error page.
2. Open any of the pickers (member, group or login/error page) 
3. Click outside the picker, e.g. on the overlay.
