### ISSUE TITLE
Unpublish menu option doesn't get added or removed without a page refresh

### ISSUE THREAD

**Issue by tom-ingeniuus** [umbraco/Umbraco-CMS#5845]
When you publish an unpublished content node, the Publish menu button doesn't have the Unpublish option added until you refresh the page. Conversely, when you Unpublish a content node, the Unpublish option does not get removed from the Publish menu button until you refresh the page.

This was checked in version 8.1 in latest Chrome browser on Windows 10

**Comment by nul800sebastiaan** [comment]
That's very annoying, I can reproduce!

**Comment by kjac** [comment]
That is indeed annoying. I'm testing a fix now, will submit it later 👍

**Comment by kjac** [comment]
PR in #5874
