### ISSUE TITLE
RTE link picker throw error after upgrade to 7.15.0

### ISSUE THREAD

**Issue by bjarnef** [umbraco/Umbraco-CMS#5849]
After upgrading af site on Umbraco Cloud from 7.12.4 to 7.15.0 to RTE link picker seems to throw an `417 (Missing token)` error.

- Select some text in RTE
- Select a node in content tree, e.g. `My Page`. Previously the link picker then showed `/my-page` under `Link`, but now it shows something like this `/{localLink:umb://document/afcc3d4df40d4d1eb8f2c43fdc592b58}`
- Submit with the selected node
- When you then set the cursor at the link in the RTE and click link picker (edit), then it show the following error. `/umbraco/backoffice/UmbracoApi/Entity/GetUrlAndAnchors?id=umb://document/afcc3d4df40d4d1eb8f2c43fdc592b58` - status code: 417 Missing token

The link does however seems to work on frontend.

![image](https://user-images.githubusercontent.com/2919859/61053650-3e0b9080-a3ee-11e9-999f-73c1014ac353.png)

**Comment by bjarnef** [comment]
I guess this method should have an overload for `Udi` and maybe `Guid` as well?
https://github.com/umbraco/Umbraco-CMS/blob/v7/dev/src/Umbraco.Web/Editors/EntityController.cs#L286-L291

or in Angular it need to convert it to an `int` id?

**Comment by bjarnef** [comment]
It seems in only hit this method first time where it send a request like this: `/umbraco/backoffice/UmbracoApi/Entity/GetUrlAndAnchors?id=1129`

When your afterwards edit the link it send this request:
`/umbraco/backoffice/UmbracoApi/Entity/GetUrlAndAnchors?id=umb://document/afcc3d4df40d4d1eb8f2c43fdc592b58` which return the 417 (Missing token) error.

https://github.com/umbraco/Umbraco-CMS/blob/v7/dev/src/Umbraco.Web/Editors/EntityController.cs#L285-L291

I guess it is also an issue in v8:
https://github.com/umbraco/Umbraco-CMS/blob/v8/dev/src/Umbraco.Web/Editors/EntityController.cs#L290-L296

**Comment by bjarnef** [comment]
In media picker there is something similar to use `udi` or `id`.
https://github.com/umbraco/Umbraco-CMS/blob/4733256ca1bfb49d4fe946110e734db1351f81d9/src/Umbraco.Web.UI.Client/src/views/common/infiniteeditors/mediapicker/mediapicker.controller.js#L97

The `GetById` overload methods doesn't have the attribute `[HttpGet]` and the parameter attribute `[FromUri]`:
https://github.com/umbraco/Umbraco-CMS/blob/853087a75044b814df458457dc9a1f778cc89749/src/Umbraco.Web/Editors/EntityController.cs#L285-L321

Furthermore it seems to have something special to handle the different parameter types:
https://github.com/umbraco/Umbraco-CMS/blob/853087a75044b814df458457dc9a1f778cc89749/src/Umbraco.Web/Editors/EntityController.cs#L72

**Comment by bjarnef** [comment]
The issue also exists in v8, but a bit different console error and status code. I will have a look at it.

![image](https://user-images.githubusercontent.com/2919859/61198196-114ec600-a6d9-11e9-93c7-d76824f6864d.png)

**Comment by bjarnef** [comment]
Ahh, it seems you also have applied the changes in v8. Great, thanks @Shazwazza 👍

**Comment by stefanoberetta** [comment]
Sorry for bothering, is this issue resolved for 7.15.x versions?
My 7.15.3 applications still have this behaviour.

Thank you
S

**Comment by drangus** [comment]
Have had to manually apply PR #5881 at 7.15.3 !
A

**Comment by callumbwhyte** [comment]
Also still causing us problems in latest v7...

It seems this never actually got released, as it was reverted (I'm guessing accidentally) in [`f0fb371`](https://github.com/umbraco/Umbraco-CMS/commit/f0fb371b2c6e2048042e884da6b059403aa805c7)

Only way around now is to patch yourself :-(

**Comment by nul800sebastiaan** [comment]
Ah that is very unfortunate.. sorry about that, have removed the v7 label now. Unfortunately we're currently only providing security fixes for v7, so this will be a known issue for the rest of the duration for v7.

**Comment by callumbwhyte** [comment]
Thanks @nul800sebastiaan! At least it's clear now :-)
