### ISSUE TITLE
TablesForScheduledPublishing fails when migrating from 7.15.0 to 8.1.0

### ISSUE THREAD

**Issue by stevemegson** [umbraco/Umbraco-CMS#5852]
The migration fails with the message

> The database failed to upgrade. ERROR: The database configuration failed with the following message: Invalid cast from 'System.DateTime' to 'System.ValueTuple\`2[[System.Nullable\`1[[System.DateTime, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]], mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089],[System.Nullable\`1[[System.DateTime, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]], mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]]'. Please check log file for additional information (can be found in '/App_Data/Logs/')

from the following line:

> `var schedules = Database.Dictionary<int, (DateTime? releaseDate, DateTime? expireDate)> (scheduleSql);`

It looks like a simple fix would be retrieving the release and expiry dates in two separate queries.

**Comment by nickh364** [comment]
I am having the same problem with one of our sites.

**Comment by nul800sebastiaan** [comment]
This one was supposed to be part of v8.1.1 but unfortunately a .cs files was not included in the solution, that has now been fixed and this will be in 8.1.2. 

Apologies for the inconvenience!
