### ISSUE TITLE
Text alignment in the create node dialog 8.1.0

### ISSUE THREAD

**Issue by limpa123** [umbraco/Umbraco-CMS#5853]
If the node has a description the name is centered above

![Screenshot 2019-07-11 at 16 33 36](https://user-images.githubusercontent.com/2033070/61059798-eb37d600-a3f9-11e9-9ad2-cf3a7472819f.png)

**Comment by nul800sebastiaan** [comment]
Oh yeah that seems like a bit of a bug! 

I've marked this as "Up for grabs" so that you or someone else coming along could create a pull request for it.

**Comment by kjac** [comment]
This was already fixed. See https://github.com/umbraco/Umbraco-CMS/pull/5752
