### ISSUE TITLE
v8: Media picker doesn't show preview of svg

### ISSUE THREAD

**Issue by bjarnef** [umbraco/Umbraco-CMS#5857]
It seems media picker no longer show preview of selected svg as it did previous. Tested on Umbraco v8.1.0

![image](https://user-images.githubusercontent.com/2919859/61078391-cdca3280-a420-11e9-95c5-b5b814839ca1.png)

![image](https://user-images.githubusercontent.com/2919859/61078402-d4f14080-a420-11e9-8035-82ca63743f3b.png)

![image](https://user-images.githubusercontent.com/2919859/61078442-e9353d80-a420-11e9-9f70-0976037ac82c.png)

**Comment by bjarnef** [comment]
For some reason the media url is rendered in the alt attribute for SVG files.

![image](https://user-images.githubusercontent.com/2919859/61078555-2994bb80-a421-11e9-8611-4695713ab8ec.png)

**Comment by bjarnef** [comment]
On the media edit page, where it show the media properties incl. the fileupload, it has the following json for the `vm.files`:
```
[ { "fileName": "/media/rs4hln03/cherry-svgrepo-com.svg", "isImage": false, "extension": "svg", "fileSrc": null } ]
```

However it doesn't render the image because `fileSrc` is `null`.
https://github.com/umbraco/Umbraco-CMS/blob/d328a53590ec4ad4f532ce056795e16be132a86f/src/Umbraco.Web.UI.Client/src/views/components/upload/umb-property-file-upload.html#L21

**Comment by bjarnef** [comment]
It seems `media` from this part in media picker property editor no longer returns meta data for extension as previous.

https://github.com/umbraco/Umbraco-CMS/blob/853087a75044b814df458457dc9a1f778cc89749/src/Umbraco.Web.UI.Client/src/views/propertyeditors/mediapicker/mediapicker.controller.js#L29

![image](https://user-images.githubusercontent.com/2919859/61089096-5d300f80-a43a-11e9-8e44-97745d8ad712.png)

**Comment by bjarnef** [comment]
@Shazwazza @nul800sebastiaan do you know if there is a difference in the `metaData`. returned if the media item is file vs image?

It would also be great if these meta data properties was returned as camel case for consistency (but it would require where used in angular to be updated and probably a breaking change if people already use these properties in their own code.

**Comment by bjarnef** [comment]
I also noticed when selecting e.g. a `txt` file the media picker preview was blank.

**Comment by drbldgtl** [comment]
Also seeing this in 7.15.2

**Comment by nul800sebastiaan** [comment]
Fixed in https://github.com/umbraco/Umbraco-CMS/pull/5883

Cherry picked for 8.1.5 046516972776fa81a27988a550aa87871796d229
