### ISSUE TITLE
v7.15 to v8.1 database error: insufficient disk space

### ISSUE THREAD

**Issue by cerdts** [umbraco/Umbraco-CMS#5858]
v7.15 to v8.1 INSTALLATION ERROR
The database failed to upgrade. ERROR: The database configuration failed with the following message: There is insufficient disk space to complete operation. Please check log file for additional information (can be found in '/App_Data/Logs/')

I have 296 GB free on the disk, the 7.15 CE database is 184,576 KB in size

**Comment by cerdts** [comment]
Here is my connection string:
   <add name="umbracoDbDSN" connectionString="Data Source=|DataDirectory|\Umbraco.sdf;Flush Interval=1;" providerName="System.Data.SqlServerCe.4.0" />

**Comment by nul800sebastiaan** [comment]
Can you post your log file please?

**Comment by sitereactor** [comment]
Keep in mind that the maximum size of a sql ce database is by default 128 MB (some docs mention 128MB for devices and 256MB for desktop). Override this by using the following connection string.

`Data Source=MyData.sdf;Max Database Size=256;Persist Security Info=False;`
(from: http://www.connectionstrings.com/sql-server-2005-ce) and (from: 
http://msdn.microsoft.com/en-us/library/system.data.sqlserverce.sqlceconnection.connectionstring%28VS.80%29.aspx )


The absolute maximum size of the database is 4gb.

**Comment by ronaldbarendse** [comment]
@cerdts It's probably also a good idea to convert you SQL CE database to a SQL Express LocalDb, as described by @zpqrtbnk: https://www.zpqrtbnk.net/posts/a-database-for-umbraco/.

**Comment by cerdts** [comment]
I will also try to post this on GitHub

- Dan, KI7DAN

**Comment by cerdts** [comment]
[UmbracoTraceLog.HC2220.20190711.json.txt](https://github.com/umbraco/Umbraco-CMS/files/3386854/UmbracoTraceLog.HC2220.20190711.json.txt)
Here is my Log file

**Comment by cerdts** [comment]
I changed the connection string to include "Max Database Size=256" and still get the insufficient disk space error.
![image](https://user-images.githubusercontent.com/38465705/61138100-094a1880-a484-11e9-9349-d283cc2653f8.png)
connection string currently: 
<add name="umbracoDbDSN" connectionString="Data Source=|DataDirectory|\Umbraco.sdf;Max Database Size=256;Flush Interval=1;" providerName="System.Data.SqlServerCe.4.0" />

**Comment by cerdts** [comment]
[UmbracoTraceLog.HC2220.20190712.json.txt](https://github.com/umbraco/Umbraco-CMS/files/3386911/UmbracoTraceLog.HC2220.20190712.json.txt)
Log file after making connection string change to add "Max Database Size=256"

**Comment by nul800sebastiaan** [comment]
@cerdts As Morten mentions you can go higher than 256, but at max 4 gigabytes, so try with a higher max size.

I'm afraid you'll soon run into the limitations of what SQL CE can do for you and it's time to convert to either LocalDb, like Ronald mentioned or migrate to SQL server. 

This could help to move to SQL server: https://codeshare.co.uk/blog/how-to-convert-sql-server-compact-edition-sdf-to-full-sql-and-speed-up-umbraco/

Meanwhile I'll close this issue, if it doesn't work with the max database size you're going to have to move to  a different type of database.
