### ISSUE TITLE
Upgraded 8.0.2 to 8.1.0, menu items now all have brackets instead of normal labels

### ISSUE THREAD

**Issue by schrepel** [umbraco/Umbraco-CMS#5860]
See my question in https://our.umbraco.com/packages/backoffice-extensions/analytics/help-issues/67686-property-names-enclosed-in-hardbrackets#309448 

Basically, all BackOffice menu items are square-bracketed fieldnames instead of the normal labels, which suggest a language issue but we haven't changed anything language-wise (single-language site, all /lang/*.xml files present, web.config correctly has EN-US as our default language...).
![brackets](https://user-images.githubusercontent.com/1033561/61092987-6484f800-a3fd-11e9-8b52-6d9b331fb076.jpg)

**Comment by Shazwazza** [comment]
I've seen this before and in those cases its because the incorrect files were being used in the installation. I'm unsure how you upgraded but you should double check that all of the files for the 8.1 install have been applied correctly, namely all of the files in the /Umbraco folder.

You can also test a vanilla install of 8.1 to verify that the problem doesn't exist in 8.1.

**Comment by schrepel** [comment]
Had just upgraded it via NuGet in VS, then Build, Publish. We don't usually check "delete all files before publishing", don't know if that would matter. Lastly, the folders we include in our publish profile: App_Plugins, App_Start, config, Umbraco, and of course web.config. This has been our normal process for all other upgrades thus far, but maybe we're missing something.

**Comment by Shazwazza** [comment]
Sounds correct, possibly to verify - download the 8.1 zip and unzip the /umbraco folder over yours, ensure that you browser cache is cleared and you bump the CDF version. If that works, it means something is odd with the upgrade. If it doesn't then ... well something else is odd ;)

**Comment by Shazwazza** [comment]
It also might be that CDF isn't cleared, there is a known issue that these files don't clear on upgrade but the version should still be bumped so that should clear the server cache https://github.com/umbraco/Umbraco-CMS/pull/5861

**Comment by schrepel** [comment]
Those steps worked great: 1) copied /umbraco from newest 8.1 release ZIP, 2) updated version in clientdependency.config, 3) cleared site-specific cache in Chrome. Thanks very much.

**Comment by opr** [comment]
The clientdependency.config bump is important to do - I omitted this step and the styling got messed up. Follow @schrepel 's steps exactly and it works fine :)

Cheers both!

**Comment by Shazwazza** [comment]
CDF should auto bump the version number when the installer runs, it seems strange that this wasn't done automatically for you. Regarding the upgrade though, not sure what might have happened to not have all of the correct files in place for you. We'll run more tests with the nuget upgrade from 8.0.2 -> 8.1 for this. I did this a few times before release and things seemed to work but will try again.

Thanks for reporting, will close this now and see how the tests go.
