### ISSUE TITLE
V8.1 dB Upgrade not mapping Prevalues for Umbraco.DropDown.Flexible

### ISSUE THREAD

**Issue by infoyoyocms** [umbraco/Umbraco-CMS#5864]
No prevalues are migrated in the dB migration script with V8.1.

Reproduction
------------

### Bug summary
No dropdown prevalues are migrated when running the V8.1 upgrade against a V7 database.

### Specifics
See attached image - the top 3 queries show the site prior to V8.1, the bottom part of the screenshot shows it after upgrade.

### Steps to reproduce
I had a V7.15 website installed. 
I created a new V8.1 empty website, manually updated the dB connection string to point to the V7 database, changed the Version in the web.config.
I then ran the site up and the upgrade process commenced and completed successfully.
I then tried to access content but received errors when trying to access nodes that had a property of Umbraco.DropDown.Flexible withun their document type.
From investigations I discovered none of the previously loaded "prevalues" were migrated in the dB migration.

### Expected result
Prevalues were listed in datatypes section, content nodes loaded OK

### Actual result
No prevalues evident under datatypes rendering content tree unusable.
![Annotation 2019-07-12 163007](https://user-images.githubusercontent.com/6537417/61102731-3833af00-a4c3-11e9-9546-a0452b3d4711.jpg)

**Comment by nul800sebastiaan** [comment]
This one was supposed to be part of v8.1.1 but unfortunately a .cs files was not included in the solution, that has now been fixed and this will be in 8.1.2. 

Apologies for the inconvenience!
