### ISSUE TITLE
8.1 Can't tab to property alias when defining properties in a doctype

### ISSUE THREAD

**Issue by skttl** [umbraco/Umbraco-CMS#5867]
When defining a property in a doctype you used to be able to tab from the property label field to the alias field. Now it skips the alias field and goes to the description.

To reproduce:
Add a property to a doctype, set the label, then tab to the next field.

Expected result:
I expected the alias field to gain focus, as it did before.

Actual result:
The description field got focus, and I had to use my mouse (OH NO! :)) to get to the alias field.

**Comment by nul800sebastiaan** [comment]
Uh oh, that seems like an oversight! 

I've marked this as "Up for grabs" so that you or someone else coming along could create a pull request for it.

**Comment by nul800sebastiaan** [comment]
Fixed in https://github.com/umbraco/Umbraco-CMS/pull/5876
