### ISSUE TITLE
Searech Write-lock

### ISSUE THREAD

**Issue by TomDaria** [umbraco/Umbraco-CMS#5871]
Good morning.
We are on Umbraco version 7.11.1.
When our application starts up from a reboot or if we exclusively initiate a full search every 24 hours, why do we see write.lock files in our ExamineIndexes folder?

As such, in our opinion, the index never completes.

Eventually, we see an error recorded in the Umbraco logs about the 
System.TimeoutException: Failed to enter the lock within timeout.
followed by Application shutdown.

Does anyone have a fix for this?

**Comment by nul800sebastiaan** [comment]
Hi @TomDaria - the same answer goes [for your previous question](https://github.com/umbraco/Umbraco-CMS/issues/5870), make sure to post on the forums for help and try the latest version of Umbraco. I know we improved Examine in the latest few versions.
