### ISSUE TITLE
Sticky header shows in "scrolled down" state before scrolling

### ISSUE THREAD

**Issue by kjac** [umbraco/Umbraco-CMS#5878]
A lot of the time I see the sticky header in its "scrolled down" state even if I haven't started scrolling yet:

![image](https://user-images.githubusercontent.com/7405322/61171481-5f988380-a578-11e9-8a69-b82b937501e8.png)

It happens on load. If I scroll down and up again, the "scrolled down" state disappears.

**Comment by kjac** [comment]
By the looks of it this is caused by the changes introduced by 68656290. Simplest way to reproduce is to open the groups list and reload it until the problem manifests:

![groups-sticky-header](https://user-images.githubusercontent.com/7405322/61242034-07fb4300-a745-11e9-88ca-b6ae0212d341.gif)

From what I can gather it happens when `observeFooter` fires *after* `observeHeader`. 

/cc @nathanwoulfe

**Comment by nathanwoulfe** [comment]
Yup that would be it - thought I'd resolved that... I think it's happening when the observer fires before the content has fully loaded, so the injected sentinel element is higher in the viewport and triggers the active state. 

I'll fix this today, just needs a flag set when the header interceptor fires, to check when running the footer, I think. Will sort it out regardless.

**Comment by kjac** [comment]
Thanks mate. It's been doing my head in 😀

**Comment by nathanwoulfe** [comment]
Likewise. There are a few different places using the umb-sticky-bar directive, and all are slightly different contexts so behave slightly differently. Pretty sure I have it sorted now, but have another PR with pending changes that I'd like to pull down first to verify it all plays nice.

**Comment by nathanwoulfe** [comment]
I've closed 5834 because I borked my branch, #5918 now has the fix for this.
