### ISSUE TITLE
Sticky header doesn't stick to the top in the media section

### ISSUE THREAD

**Issue by kjac** [umbraco/Umbraco-CMS#5879]
The sticky header usually slides up and sticks to the top of the view when scrolling begins. This doesn't seem to be the case in the media section no more:

![image](https://user-images.githubusercontent.com/7405322/61171512-cddd4600-a578-11e9-97d7-75c8395796d3.png)

The result is that the scrolled content is visible behind the sticky header, as shown above.

**Comment by nathanwoulfe** [comment]
I've closed 5834 because I borked my branch, #5918 now has the fix for this.
