### ISSUE TITLE
Sticky header throws a JS console error 

### ISSUE THREAD

**Issue by kjac** [umbraco/Umbraco-CMS#5880]
The following error logs to the JS console pretty often when browsing through folders in the media section:

![image](https://user-images.githubusercontent.com/7405322/61171541-21e82a80-a579-11e9-8a8d-38a838663396.png)

Might be related to #5879

**Comment by bjarnef** [comment]
Yes, it seem `rootBounds` in some cases is null and it affected the media section a little.
https://github.com/umbraco/Umbraco-CMS/pull/5732#issuecomment-509607334

I think this PR might fix this issue https://github.com/umbraco/Umbraco-CMS/pull/5834

**Comment by nathanwoulfe** [comment]
I've closed 5834 because I borked my branch, #5918 now has the fix for this.
