### ISSUE TITLE
Upgrade DB from v8.0.2 to v8.1.0 crashes

### ISSUE THREAD

**Issue by pralthom** [umbraco/Umbraco-CMS#5896]
Hi,

I'm having an issue upgrading my Umbraco v8.0.2 to the new v8.1.0 version.
When upgrading the DB, I get the following error:

`Error during installation
The database failed to upgrade. ERROR: The database configuration failed with the following message: There are no primary or candidate keys in the referenced table 'umbracoContent' that match the referencing column list in the foreign key 'FK_cmsContentNu_umbracoContent_nodeId'.
 Could not create constraint or index. See previous errors. Please check log file for additional information (can be found in '/App_Data/Logs/')

See the log for full details (logs can typically be found in the App_Data\Logs folder).`

Below the installation logs:

{
  "@t": "2019-07-15T09:20:07.0368982Z",
  "@mt": "At {OrigState}",
  "OrigState": "{B69B6E8C-A769-4044-A27E-4A4E18D1645A}",
  "SourceContext": "Umbraco.Core.Migrations.MigrationPlan",
  "ProcessId": 11092,
  "ProcessName": "iisexpress",
  "ThreadId":9,"AppDomainId":5,"AppDomainAppId":"LMW3SVC1ROOT","MachineName":"EIFRWSE01309","Log4NetLevel":"INFO ","HttpRequestNumber":6,"HttpRequestId":"6a047595-d0c6-4095-827e-8d6711783b1e"}
{
  "@t": "2019-07-15T09:20:07.0368982Z",
  "@mt": "Execute {MigrationType}",
  "MigrationType": "RenameUserLoginDtoDateIndex",
  "SourceContext": "Umbraco.Core.Migrations.MigrationPlan",
  "ProcessId": 11092,
  "ProcessName": "iisexpress",
  "ThreadId": 9,
  "AppDomainId": 5,
  "AppDomainAppId": "LMW3SVC1ROOT",
  "MachineName": "EIFRWSE01309",
  "Log4NetLevel": "INFO ",
  "HttpRequestNumber": 6,
  "HttpRequestId":"6a047595-d0c6-4095-827e-8d6711783b1e"}
{
  "@t": "2019-07-15T09:20:07.0448868Z",
  "@mt": "SQL [{ContextIndex}]: {Sql}",
  "ContextIndex": 0,
  "Sql": "CREATE NONCLUSTERED INDEX [IX_umbracoUserLogin_lastValidatedUtc] ON [umbracoUserLogin] ([lastValidatedUtc])",
  "SourceContext": "Umbraco.Core.Migrations.Expressions.Common.Expressions.CreateIndexExpression",
  "ProcessId": 11092,
  "ProcessName": "iisexpress",
  "ThreadId": 9,
  "AppDomainId": 5,
  "AppDomainAppId": "LMW3SVC1ROOT",
  "MachineName":"EIFRWSE01309","Log4NetLevel":"INFO ","HttpRequestNumber":6,"HttpRequestId":"6a047595-d0c6-4095-827e-8d6711783b1e"}
{
  "@t": "2019-07-15T09:20:07.0519020Z",
  "@mt": "At {OrigState}",
  "OrigState": "{0372A42B-DECF-498D-B4D1-6379E907EB94}",
  "SourceContext": "Umbraco.Core.Migrations.MigrationPlan",
  "ProcessId": 11092,
  "ProcessName": "iisexpress",
  "ThreadId": 9,
  "AppDomainId": 5,
  "AppDomainAppId":"LMW3SVC1ROOT","MachineName":"EIFRWSE01309","Log4NetLevel":"INFO ","HttpRequestNumber":6,"HttpRequestId":"6a047595-d0c6-4095-827e-8d6711783b1e"}
{
  "@t": "2019-07-15T09:20:07.0519020Z",
  "@mt": "Execute {MigrationType}",
  "MigrationType": "FixContentNuCascade",
  "SourceContext": "Umbraco.Core.Migrations.MigrationPlan",
  "ProcessId": 11092,
  "ProcessName": "iisexpress",
  "ThreadId": 9,
  "AppDomainId": 5,
  "AppDomainAppId": "LMW3SVC1ROOT",
  "MachineName": "EIFRWSE01309",
  "Log4NetLevel":"INFO ","HttpRequestNumber":6,"HttpRequestId":"6a047595-d0c6-4095-827e-8d6711783b1e"}
{
  "@t": "2019-07-15T09:20:07.1088817Z",
  "@mt": "SQL [{ContextIndex}]: {Sql}",
  "ContextIndex": 1,
  "Sql": "ALTER TABLE [cmsContentNu] ADD CONSTRAINT [PK_cmsContentNu] PRIMARY KEY CLUSTERED ([nodeId], [published])",
  "SourceContext": "Umbraco.Core.Migrations.Expressions.Execute.Expressions.ExecuteSqlStatementExpression",
  "ProcessId": 11092,
  "ProcessName": "iisexpress",
  "ThreadId": 9,
  "AppDomainId": 5,
  "AppDomainAppId": "LMW3SVC1ROOT",
  "MachineName": "EIFRWSE01309",
  "Log4NetLevel":"INFO ","HttpRequestNumber":6,"HttpRequestId":"6a047595-d0c6-4095-827e-8d6711783b1e"}
{
  "@t": "2019-07-15T09:20:07.1198814Z",
  "@mt": "SQL [{ContextIndex}]: {Sql}",
  "ContextIndex": 2,
  "Sql": "ALTER TABLE [cmsContentNu] ADD CONSTRAINT [FK_cmsContentNu_umbracoContent_nodeId] FOREIGN KEY ([nodeId]) REFERENCES [umbracoContent] ([nodeId]) ON DELETE CASCADE",
  "SourceContext": "Umbraco.Core.Migrations.Expressions.Execute.Expressions.ExecuteSqlStatementExpression",
  "ProcessId": 11092,
  "ProcessName": "iisexpress",
  "ThreadId": 9,
  "AppDomainId": 5,
  "AppDomainAppId": "LMW3SVC1ROOT",
  "MachineName": "EIFRWSE01309",
  "Log4NetLevel": "INFO ",
  "HttpRequestNumber": 6,
  "HttpRequestId":"6a047595-d0c6-4095-827e-8d6711783b1e"}
{
  "@t": "2019-07-15T09:20:08.2941886Z",
  "@mt": "Exception ({InstanceId}).",
  "@l": "Error",
  "@x": "System.Data.SqlClient.SqlException (0x80131904): There are no primary or candidate keys in the referenced table 'umbracoContent' that match the referencing column list in the foreign key 'FK_cmsContentNu_umbracoContent_nodeId'.\r\nCould not create constraint or index. See previous errors.\r\n   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)\r\n   at System.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)\r\n   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)\r\n   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)\r\n   at System.Data.SqlClient.SqlCommand.RunExecuteNonQueryTds(String methodName, Boolean async, Int32 timeout, Boolean asyncWrite)\r\n   at System.Data.SqlClient.SqlCommand.InternalExecuteNonQuery(TaskCompletionSource`1 completion, String methodName, Boolean sendToPipe, Int32 timeout, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry)\r\n   at System.Data.SqlClient.SqlCommand.ExecuteNonQuery()\r\n   at StackExchange.Profiling.Data.ProfiledDbCommand.ExecuteNonQuery() in C:\\projects\\dotnet\\src\\MiniProfiler.Shared\\Data\\ProfiledDbCommand.cs:line 272\r\n   at Umbraco.Core.Persistence.FaultHandling.FaultHandlingDbCommand.<ExecuteNonQuery>b__31_0() in d:\\a\\1\\s\\src\\Umbraco.Core\\Persistence\\FaultHandling\\RetryDbConnection.cs:line 209\r\n   at Umbraco.Core.Persistence.FaultHandling.FaultHandlingDbCommand.<>c__DisplayClass33_0`1.<Execute>b__0() in d:\\a\\1\\s\\src\\Umbraco.Core\\Persistence\\FaultHandling\\RetryDbConnection.cs:line 222\r\n   at Umbraco.Core.Persistence.FaultHandling.RetryPolicy.ExecuteAction[TResult](Func`1 func) in d:\\a\\1\\s\\src\\Umbraco.Core\\Persistence\\FaultHandling\\RetryPolicy.cs:line 172\r\n   at Umbraco.Core.Persistence.FaultHandling.FaultHandlingDbCommand.Execute[T](Func`1 f) in d:\\a\\1\\s\\src\\Umbraco.Core\\Persistence\\FaultHandling\\RetryDbConnection.cs:line 219\r\n   at Umbraco.Core.Persistence.FaultHandling.FaultHandlingDbCommand.ExecuteNonQuery() in d:\\a\\1\\s\\src\\Umbraco.Core\\Persistence\\FaultHandling\\RetryDbConnection.cs:line 209\r\n   at NPoco.Database.ExecuteNonQueryHelper(DbCommand cmd)\r\n   at NPoco.Database.NPoco.IDatabaseHelpers.ExecuteNonQueryHelper(DbCommand cmd)\r\n   at NPoco.Database.Execute(String sql, CommandType commandType, Object[] args)\r\nClientConnectionId:74ced1c8-c0a6-4d43-ac97-fdd920234d74\r\nError Number:1776,State:0,Class:16",
  "InstanceId": "4e5dd53e",
  "SourceContext": "Umbraco.Core.Persistence.UmbracoDatabase",
  "ProcessId": 11092,
  "ProcessName": "iisexpress",
  "ThreadId": 9,
  "AppDomainId": 5,
  "AppDomainAppId": "LMW3SVC1ROOT",
  "MachineName": "EIFRWSE01309",
  "Log4NetLevel": "ERROR",
  "HttpRequestNumber": 6,
  "HttpRequestId":"6a047595-d0c6-4095-827e-8d6711783b1e"}
{
  "@t": "2019-07-15T09:20:08.3091896Z",
  "@mt": "Database configuration failed",
  "@l": "Error",
  "@x": "System.Data.SqlClient.SqlException (0x80131904): There are no primary or candidate keys in the referenced table 'umbracoContent' that match the referencing column list in the foreign key 'FK_cmsContentNu_umbracoContent_nodeId'.\r\nCould not create constraint or index. See previous errors.\r\n   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)\r\n   at System.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)\r\n   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)\r\n   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)\r\n   at System.Data.SqlClient.SqlCommand.RunExecuteNonQueryTds(String methodName, Boolean async, Int32 timeout, Boolean asyncWrite)\r\n   at System.Data.SqlClient.SqlCommand.InternalExecuteNonQuery(TaskCompletionSource`1 completion, String methodName, Boolean sendToPipe, Int32 timeout, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry)\r\n   at System.Data.SqlClient.SqlCommand.ExecuteNonQuery()\r\n   at StackExchange.Profiling.Data.ProfiledDbCommand.ExecuteNonQuery() in C:\\projects\\dotnet\\src\\MiniProfiler.Shared\\Data\\ProfiledDbCommand.cs:line 272\r\n   at Umbraco.Core.Persistence.FaultHandling.FaultHandlingDbCommand.<ExecuteNonQuery>b__31_0() in d:\\a\\1\\s\\src\\Umbraco.Core\\Persistence\\FaultHandling\\RetryDbConnection.cs:line 209\r\n   at Umbraco.Core.Persistence.FaultHandling.FaultHandlingDbCommand.<>c__DisplayClass33_0`1.<Execute>b__0() in d:\\a\\1\\s\\src\\Umbraco.Core\\Persistence\\FaultHandling\\RetryDbConnection.cs:line 222\r\n   at Umbraco.Core.Persistence.FaultHandling.RetryPolicy.ExecuteAction[TResult](Func`1 func) in d:\\a\\1\\s\\src\\Umbraco.Core\\Persistence\\FaultHandling\\RetryPolicy.cs:line 172\r\n   at Umbraco.Core.Persistence.FaultHandling.FaultHandlingDbCommand.Execute[T](Func`1 f) in d:\\a\\1\\s\\src\\Umbraco.Core\\Persistence\\FaultHandling\\RetryDbConnection.cs:line 219\r\n   at Umbraco.Core.Persistence.FaultHandling.FaultHandlingDbCommand.ExecuteNonQuery() in d:\\a\\1\\s\\src\\Umbraco.Core\\Persistence\\FaultHandling\\RetryDbConnection.cs:line 209\r\n   at NPoco.Database.ExecuteNonQueryHelper(DbCommand cmd)\r\n   at NPoco.Database.NPoco.IDatabaseHelpers.ExecuteNonQueryHelper(DbCommand cmd)\r\n   at NPoco.Database.Execute(String sql, CommandType commandType, Object[] args)\r\n   at NPoco.Database.Execute(Sql Sql)\r\n   at NPoco.Database.Execute(String sql, Object[] args)\r\n   at Umbraco.Core.Migrations.MigrationExpressionBase.ExecuteStatement(StringBuilder stmtBuilder) in d:\\a\\1\\s\\src\\Umbraco.Core\\Migrations\\MigrationExpressionBase.cs:line 118\r\n   at Umbraco.Core.Migrations.MigrationExpressionBase.Execute() in d:\\a\\1\\s\\src\\Umbraco.Core\\Migrations\\MigrationExpressionBase.cs:line 77\r\n   at Umbraco.Core.Migrations.Expressions.Create.KeysAndIndexes.CreateKeysAndIndexesBuilder.ExecuteSql(String sql) in d:\\a\\1\\s\\src\\Umbraco.Core\\Migrations\\Expressions\\Create\\KeysAndIndexes\\CreateKeysAndIndexesBuilder.cs:line 51\r\n   at Umbraco.Core.Migrations.Expressions.Create.KeysAndIndexes.CreateKeysAndIndexesBuilder.Do() in d:\\a\\1\\s\\src\\Umbraco.Core\\Migrations\\Expressions\\Create\\KeysAndIndexes\\CreateKeysAndIndexesBuilder.cs:line 36\r\n   at Umbraco.Core.Migrations.Upgrade.V_8_1_0.FixContentNuCascade.Migrate() in d:\\a\\1\\s\\src\\Umbraco.Core\\Migrations\\Upgrade\\V_8_1_0\\FixContentNuCascade.cs:line 13\r\n   at Umbraco.Core.Migrations.MigrationBase.Umbraco.Core.Migrations.IMigration.Migrate() in d:\\a\\1\\s\\src\\Umbraco.Core\\Migrations\\MigrationBase.cs:line 73\r\n   at Umbraco.Core.Migrations.MigrationPlan.Execute(IScope scope, String fromState, IMigrationBuilder migrationBuilder, ILogger logger) in d:\\a\\1\\s\\src\\Umbraco.Core\\Migrations\\MigrationPlan.cs:line 309\r\n   at Umbraco.Core.Migrations.Upgrade.Upgrader.Execute(IScopeProvider scopeProvider, IMigrationBuilder migrationBuilder, IKeyValueService keyValueService, ILogger logger) in d:\\a\\1\\s\\src\\Umbraco.Core\\Migrations\\Upgrade\\Upgrader.cs:line 67\r\n   at Umbraco.Core.Migrations.Install.DatabaseBuilder.UpgradeSchemaAndData(MigrationPlan plan) in d:\\a\\1\\s\\src\\Umbraco.Core\\Migrations\\Install\\DatabaseBuilder.cs:line 498\r\nClientConnectionId:74ced1c8-c0a6-4d43-ac97-fdd920234d74\r\nError Number:1776,State:0,Class:16",
  "SourceContext": "Umbraco.Core.Migrations.Install.DatabaseBuilder",
  "ProcessId": 11092,
  "ProcessName": "iisexpress",
  "ThreadId": 9,
  "AppDomainId": 5,
  "AppDomainAppId": "LMW3SVC1ROOT",
  "MachineName": "EIFRWSE01309",
  "Log4NetLevel": "ERROR",
  "HttpRequestNumber": 6,
  "HttpRequestId":"6a047595-d0c6-4095-827e-8d6711783b1e"}
{
  "@t": "2019-07-15T09:20:08.3132108Z",
  "@mt": "The database schema validation produced the following summary: {DbSchemaSummary}",
  "DbSchemaSummary": "The following tables were found in the database, but are not in the current schema:\r\nSkybrudRedirects,UFRecordDataBit,UFRecordDataDateTime,UFRecordDataInteger,UFRecordDataLongString,UFRecordDataString,UFRecordFields,UFRecords,UFUserFormSecurity,UFUserSecurity\r\n \r\nThe following columns were found in the database, but are not in the current schema:\r\nSkybrudRedirects,Key,SkybrudRedirects,RootKey,SkybrudRedirects,DestinationKey,UFRecordDataBit,Key,UFRecordDataDateTime,Key,UFRecordDataInteger,Key,UFRecordDataLongString,Key,UFRecordDataString,Key,UFRecordFields,Key,UFRecordFields,FieldId,UFRecords,Form,UFRecords,CurrentPage,UFRecords,UniqueId,UFUserFormSecurity,Form,UFUserFormSecurity,SecurityType,UFUserFormSecurity,Id,UFRecords,UmbracoPageId,UFRecordDataString,Id,UFRecords,Id,UFRecordFields,Record,UFRecordDataInteger,Value,UFRecordDataLongString,Id,UFRecordDataDateTime,Id,UFRecordDataInteger,Id,SkybrudRedirects,DestinationId,UFRecordDataBit,Id,SkybrudRedirects,RootId,SkybrudRedirects,Id,SkybrudRedirects,Created,SkybrudRedirects,Updated,UFRecordDataDateTime,Value,UFRecords,Created,UFRecords,Updated,UFRecords,RecordData,UFRecordDataLongString,Value,UFUserSecurity,ManageDataSources,UFUserSecurity,ManagePreValueSources,UFUserSecurity,ManageWorkflows,UFUserSecurity,ManageForms,UFUserFormSecurity,HasAccess,UFUserFormSecurity,AllowInEditor,UFRecordDataBit,Value,SkybrudRedirects,IsPermanent,SkybrudRedirects,IsRegex,SkybrudRedirects,ForwardQueryString,SkybrudRedirects,DestinationUrl,SkybrudRedirects,Url,SkybrudRedirects,QueryString,SkybrudRedirects,DestinationType,UFUserSecurity,User,UFUserFormSecurity,User,UFRecords,State,UFRecordDataString,Value,UFRecordFields,Alias,UFRecordFields,DataType,UFRecords,IP,UFRecords,MemberKey\r\n \r\nThe following constraints (Primary Keys, Foreign Keys and Indexes) were found in the database, but are not in the current schema:\r\nFK_umbracoNode_umbracoNode_id,FK_umbracoNode_umbracoUser_id,FK_cmsContentType_umbracoNode_id,FK_cmsTemplate_umbracoNode,FK_umbracoContent_umbracoNode_id,FK_umbracoContent_cmsContentType_NodeId,FK_umbracoContentVersion_umbracoContent_nodeId,FK_umbracoContentVersion_umbracoUser_id,FK_umbracoMediaVersion_umbracoContentVersion_id,FK_umbracoDocument_umbracoContent_nodeId,FK_cmsDocumentType_cmsContentType_nodeId,FK_cmsDocumentType_umbracoNode_id,FK_cmsDocumentType_cmsTemplate_nodeId,FK_umbracoDataType_umbracoNode_id,FK_cmsDictionary_cmsDictionary_id,FK_umbracoLanguage_umbracoLanguage_id,FK_cmsLanguageText_umbracoLanguage_id,FK_cmsLanguageText_cmsDictionary_id,FK_umbracoDomain_umbracoNode_id,FK_umbracoLog_umbracoUser_id,FK_cmsMacroProperty_cmsMacro_id,FK_cmsMemberType_umbracoNode_id,FK_cmsMemberType_cmsContentType_nodeId,FK_cmsMember_umbracoContent_nodeId,FK_cmsMember2MemberGroup_cmsMember_nodeId,FK_cmsMember2MemberGroup_umbracoNode_id,FK_cmsPropertyTypeGroup_cmsContentType_nodeId,FK_cmsPropertyType_umbracoDataType_nodeId,FK_cmsPropertyType_cmsContentType_nodeId,FK_cmsPropertyType_cmsPropertyTypeGroup_id,FK_umbracoPropertyData_umbracoContentVersion_id,FK_umbracoPropertyData_cmsPropertyType_id,FK_umbracoPropertyData_umbracoLanguage_id,FK_umbracoRelation_umbracoNode,FK_umbracoRelation_umbracoNode1,FK_umbracoRelation_umbracoRelationType_id,FK_cmsTags_umbracoLanguage_id,FK_cmsTagRelationship_cmsContent,FK_cmsTagRelationship_cmsTags_id,FK_cmsTagRelationship_cmsPropertyType,FK_cmsContentType2ContentType_umbracoNode_parent,FK_cmsContentType2ContentType_umbracoNode_child,FK_cmsContentTypeAllowedContentType_cmsContentType,FK_cmsContentTypeAllowedContentType_cmsContentType1,FK_umbracoUser2NodeNotify_umbracoUser_id,FK_umbracoUser2NodeNotify_umbracoNode_id,FK_umbracoAccess_umbracoNode_id,FK_umbracoAccess_umbracoNode_id1,FK_umbracoAccess_umbracoNode_id2,FK_umbracoAccessRule_umbracoAccess_id,FK_umbracoRedirectUrl_umbracoNode_uniqueID,FK_startContentId_umbracoNode_id,FK_startMediaId_umbracoNode_id,FK_umbracoUser2UserGroup_umbracoUser_id,FK_umbracoUser2UserGroup_umbracoUserGroup_id,FK_umbracoUserGroup2NodePermission_umbracoUserGroup_id,FK_umbracoUserGroup2NodePermission_umbracoNode_id,FK_umbracoUserGroup2App_umbracoUserGroup_id,FK_umbracoUserStartNode_umbracoUser_id,FK_umbracoUserStartNode_umbracoNode_id,FK_cmsContentNu_umbracoContent_nodeId,FK_umbracoDocumentVersion_umbracoContentVersion_id,FK_umbracoDocumentVersion_cmsTemplate_nodeId,FK_umbracoUserLogin_umbracoUser_id,FK_umbracoContentVersionCultureVariation_umbracoContentVersion_id,FK_umbracoContentVersionCultureVariation_umbracoLanguage_id,FK_umbracoContentVersionCultureVariation_umbracoUser_id,FK_umbracoDocumentCultureVariation_umbracoNode_id,FK_umbracoDocumentCultureVariation_umbracoLanguage_id,FK_umbracoContentSchedule_umbracoContent_nodeId,FK_umbracoContentSchedule_umbracoLanguage_id,PK_user,PK_umbracoNode,PK_cmsContentType,PK_cmsTemplate,PK_umbracoContent,PK_umbracoContentVersion,PK_umbracoMediaVersion,PK_umbracoDocument,PK_cmsDocumentType,PK_umbracoDataType,PK_cmsDictionary,PK_umbracoLanguage,PK_cmsLanguageText,PK_umbracoDomain,PK_umbracoLog,PK_cmsMacro,PK_cmsMacroProperty,PK_cmsMemberType,PK_cmsMember,PK_cmsMember2MemberGroup,PK_cmsPropertyTypeGroup,PK_cmsPropertyType,PK_umbracoPropertyData,PK_umbracoRelationType,PK_umbracoRelation,PK_cmsTags,PK_cmsTagRelationship,PK_cmsContentType2ContentType,PK_cmsContentTypeAllowedContentType,PK_umbracoUser2NodeNotify,PK_umbracoServer,PK_umbracoAccess,PK_umbracoAccessRule,PK_umbracoCacheInstruction,PK_umbracoExternalLogin,PK_umbracoRedirectUrl,PK_umbracoLock,PK_umbracoUserGroup,PK_user2userGroup,PK_umbracoUserGroup2NodePermission,PK_userGroup2App,PK_userStartNode,PK_cmsContentNu,PK_umbracoDocumentVersion,PK_umbracoKeyValue,PK_umbracoUserLogin,PK_umbracoConsent,PK_umbracoAudit,PK_umbracoContentVersionCultureVariation,PK_umbracoDocumentCultureVariation,PK_umbracoContentSchedule\r\n \r\nThe following indexes were found in the database, but are not in the current schema:\r\nIX_umbracoUser_userLogin,IX_umbracoNode_UniqueId,IX_umbracoNode_ParentId,IX_umbracoNode_Path,IX_umbracoNode_Trashed,IX_umbracoNode_ObjectType,IX_cmsContentType,IX_cmsContentType_icon,IX_cmsTemplate_nodeId,IX_umbracoMediaVersion,IX_umbracoDocument_Published,IX_cmsDictionary_id,IX_cmsDictionary_key,IX_umbracoLanguage_languageISOCode,IX_umbracoLanguage_fallbackLanguageId,IX_umbracoLog,IX_cmsMacro_UniqueId,IX_cmsMacroPropertyAlias,IX_cmsMacroProperty_UniquePropertyId,IX_cmsMacroProperty_Alias,IX_cmsMember_LoginName,IX_cmsPropertyTypeGroupUniqueID,IX_cmsPropertyTypeAlias,IX_cmsPropertyTypeUniqueID,IX_umbracoPropertyData_VersionId,IX_umbracoPropertyData_PropertyTypeId,IX_umbracoPropertyData_LanguageId,IX_umbracoPropertyData_Segment,IX_umbracoRelationType_UniqueId,IX_umbracoRelationType_name,IX_umbracoRelationType_alias,IX_umbracoRelation_parentChildType,IX_cmsTags_LanguageId,IX_cmsTags,IX_computerName,IX_umbracoServer_isActive,IX_umbracoAccess_nodeId,IX_umbracoAccessRule,IX_umbracoRedirectUrl,IX_umbracoUserGroup_userGroupAlias,IX_umbracoUserGroup_userGroupName,IX_umbracoUser2NodePermission_nodeId,IX_umbracoUserStartNode_startNodeType,IX_umbracoUserLogin_lastValidatedUtc,IX_umbracoContentVersionCultureVariation_VersionId,IX_umbracoContentVersionCultureVariation_LanguageId,IX_umbracoDocumentCultureVariation_NodeId,IX_umbracoDocumentCultureVariation_LanguageId\r\n \r\n",
  "SourceContext": "Umbraco.Core.Migrations.Install.DatabaseBuilder",
  "ProcessId": 11092,
  "ProcessName": "iisexpress",
  "ThreadId": 9,
  "AppDomainId": 5,
  "AppDomainAppId": "LMW3SVC1ROOT",
  "MachineName": "EIFRWSE01309",
  "Log4NetLevel": "INFO ",
  "HttpRequestNumber": 6,
  "HttpRequestId":"6a047595-d0c6-4095-827e-8d6711783b1e"}
{
  "@t": "2019-07-15T09:20:08.3151987Z",
  "@mt": "Installation step {Step} failed.",
  "@l": "Error",
  "@x": "System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> Umbraco.Web.Install.InstallException: The database failed to upgrade. ERROR: The database configuration failed with the following message: There are no primary or candidate keys in the referenced table 'umbracoContent' that match the referencing column list in the foreign key 'FK_cmsContentNu_umbracoContent_nodeId'.\r\nCould not create constraint or index. See previous errors.\n Please check log file for additional information (can be found in '/App_Data/Logs/')\r\n   at Umbraco.Web.Install.InstallSteps.DatabaseUpgradeStep.ExecuteAsync(Object model) in d:\\a\\1\\s\\src\\Umbraco.Web\\Install\\InstallSteps\\DatabaseUpgradeStep.cs:line 47\r\n   --- End of inner exception stack trace ---\r\n   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)\r\n   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)\r\n   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)\r\n   at Umbraco.Web.Install.Controllers.InstallApiController.<ExecuteStepAsync>d__14.MoveNext() in d:\\a\\1\\s\\src\\Umbraco.Web\\Install\\Controllers\\InstallApiController.cs:line 236\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)\r\n   at Umbraco.Web.Install.Controllers.InstallApiController.<PostPerformInstall>d__11.MoveNext() in d:\\a\\1\\s\\src\\Umbraco.Web\\Install\\Controllers\\InstallApiController.cs:line 104",
  "Step": "DatabaseUpgrade",
  "SourceContext": "Umbraco.Web.Install.Controllers.InstallApiController",
  "ProcessId": 11092,
  "ProcessName": "iisexpress",
  "ThreadId": 9,
  "AppDomainId": 5,
  "AppDomainAppId": "LMW3SVC1ROOT",
  "MachineName": "EIFRWSE01309",
  "Log4NetLevel": "ERROR",
  "HttpRequestNumber": 6,
  "HttpRequestId":"6a047595-d0c6-4095-827e-8d6711783b1e"}
{
  "@t": "2019-07-15T09:20:08.3151987Z",
  "@mt": "{EndMessage} ({Duration}ms) [Timing {TimingId}]",
  "EndMessage": "Step completed",
  "Duration": 413724,
  "TimingId": "97bb271",
  "SourceContext": "Umbraco.Web.Install.Controllers.InstallApiController",
  "ProcessId": 11092,
  "ProcessName": "iisexpress",
  "ThreadId": 9,
  "AppDomainId": 5,
  "AppDomainAppId": "LMW3SVC1ROOT",
  "MachineName": "EIFRWSE01309",
  "Log4NetLevel": "INFO ",
  "HttpRequestNumber": 6,
  "HttpRequestId":"6a047595-d0c6-4095-827e-8d6711783b1e"}
{
  "@t": "2019-07-15T09:20:08.3151987Z",
  "@mt": "An error occurred during installation step {Step}",
  "@l": "Error",
  "@x": "System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> Umbraco.Web.Install.InstallException: The database failed to upgrade. ERROR: The database configuration failed with the following message: There are no primary or candidate keys in the referenced table 'umbracoContent' that match the referencing column list in the foreign key 'FK_cmsContentNu_umbracoContent_nodeId'.\r\nCould not create constraint or index. See previous errors.\n Please check log file for additional information (can be found in '/App_Data/Logs/')\r\n   at Umbraco.Web.Install.InstallSteps.DatabaseUpgradeStep.ExecuteAsync(Object model) in d:\\a\\1\\s\\src\\Umbraco.Web\\Install\\InstallSteps\\DatabaseUpgradeStep.cs:line 47\r\n   --- End of inner exception stack trace ---\r\n   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)\r\n   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)\r\n   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)\r\n   at Umbraco.Web.Install.Controllers.InstallApiController.<ExecuteStepAsync>d__14.MoveNext() in d:\\a\\1\\s\\src\\Umbraco.Web\\Install\\Controllers\\InstallApiController.cs:line 236\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)\r\n   at Umbraco.Web.Install.Controllers.InstallApiController.<PostPerformInstall>d__11.MoveNext() in d:\\a\\1\\s\\src\\Umbraco.Web\\Install\\Controllers\\InstallApiController.cs:line 104",
  "Step": "DatabaseUpgrade",
  "SourceContext": "Umbraco.Web.Install.Controllers.InstallApiController",
  "ProcessId": 11092,
  "ProcessName": "iisexpress",
  "ThreadId": 9,
  "AppDomainId": 5,
  "AppDomainAppId": "LMW3SVC1ROOT",
  "MachineName": "EIFRWSE01309",
  "Log4NetLevel": "ERROR",
  "HttpRequestNumber": 6,
  "HttpRequestId":"6a047595-d0c6-4095-827e-8d6711783b1e"}

**Comment by pralthom** [comment]
I've tried to add the missing PK manually:
`ALTER TABLE [umbracoContent] ADD CONSTRAINT [PK_umbracoContent] PRIMARY KEY ([nodeId])`

Then I run the installation and it works. Any thoughts?
Obviously I cannot do that on the production environment... 

After upgrading the buttons and labels are not all loaded correctly:
![image](https://user-images.githubusercontent.com/44721265/61219255-1e3cdb00-a714-11e9-8b36-ffcf760fe8c4.png)

**Comment by clausjensen** [comment]
Closing this issue as per request in other issue. If you're still seeing problems please let us know how to replicate.
