### ISSUE TITLE
Save media type crashes

### ISSUE THREAD

**Issue by buttermilklemon** [umbraco/Umbraco-CMS#5899]
We found an error when saving the media type. When we try to save a media type, we get an error message "System.NullReferenceException: Object reference not set to an instance of an object". 
This also happens with media types that have not been changed.

Reproduction
------------

- Get fresh umbraco installation 8.1
- Go to media types section
- Save file shows error

**Comment by kjac** [comment]
Hi @buttermilklemon, thanks for reporting. This looks like a duplicate of #5894?

**Comment by esn303** [comment]
Hey @kjac it looks like it is, but this also occures even if you don't change a thing. Just open the mediatype definition and click save. Does your PR account for this?

**Comment by kjac** [comment]
I do believe it does 😀

**Comment by esn303** [comment]
I was unable to build with your fix, so I couldn't test (not blaming you, but my inability!) 😬 Hence the stupid question. 😉

**Comment by Shazwazza** [comment]
will close as a duplicate
