### ISSUE TITLE
Create a Starter Kit Gallery

### ISSUE THREAD

**Issue by Zweben** [umbraco/Umbraco-CMS#5901]
I just thought to do a search for starter kits in the Umbraco package search, and was surprised to see a decent collection of kits that I was unaware of. In my opinion, it's a shame how little visibility these are given. For instance, the current install process doesn't even mention starter kits to you, it simply installs the default one without asking. If you do go into the settings, the only other option you're given is to skip installing a starter kit entirely. This gives the false impression that Umbraco does not have much to offer in this regard.

Instead, I would like to see the installation process present a gallery of starter kits from which to choose during installation. This would not only make the install process friendlier, and improve the image of Umbraco (from 'nearly deserted' to 'active community') but would also do a lot to highlight the work of the starter kit creators, and encourage the creation of more starter kits.

**Comment by nul800sebastiaan** [comment]
I understand the idea, to explain: we want to be in full control over the starter kits available during install so we can keep them up to date with the latest version and make sure they use best practices (I know, the current starter kits needs updates regarding that). The other kits are probably great but we don't have the resources to vet them for inclusion in the installer.
