### ISSUE TITLE
v8.1 DB upgrade not mapping several property editor aliases

### ISSUE THREAD

**Issue by Zweben** [umbraco/Umbraco-CMS#5902]
Several Umbraco 7 property editor aliases are not being mapped to their new aliases during v8.1's database upgrade process.

Reproduction
------------

### Bug summary

Upon trying to upgrade an Umbraco 7.14 database to 8.1 via Umbraco 8.1's upgrade process, the upgrade fails, and the log indicates that the CMS could not find property editors with certain aliases.

### Specifics
I receive many instances of the following message in the log, for the property editor aliases listed below:
> Skipping validation of configuration for data type {NodeId} : {NewEditorAlias} (was: {EditorAlias}) because no property editor with that alias was found. Please ensure that the configuration is valid. The site may fail to start and / or load data types and run.

- Umbraco.MultiNodeTreePicker2
- Umbraco.Textbox
- Umbraco.Date
- Umbraco.TextboxMultiple
- Umbraco.RelatedLinks2
- Terratype
- Spectrum.Color.Picker

In all cases, the string listed for NewEditorAlias is the same as the one listed for EditorAlias.

For the following property aliases, I receive a slightly different error message:

> Skipping validation of configuration for data type {NodeId} : {EditorAlias}. Please ensure that the configuration is valid. The site may fail to start and / or load data types and run.

- Umbraco.ContentPicker2
- Umbraco.RadioButtonList

### Steps to reproduce

1. I made a local copy of my Umbraco 8.0.2 Cloud project, upgraded it to 8.1.0 via NuGet, and removed all database files, media, UDA files, temp files, scripts, CSS, and templates.
2. I dragged the .MDF and .LDF files from my v7.14 project over to the v8.1 project and updated the Umbraco.Core.ConfigurationStatus version to 7.14.
3. I ran the site and started the upgrade

### Expected result

Aliases of built-in property editors are mapped automatically when trying to validate data type configuration, and the user is given a way to manually map the property aliases of 3rd-party property editors.

### Actual result

Upgrade fails to map property editor aliases during data type validation, causing a cascading failure that prevents the database from upgrading at all.

---
_This item has been added to our backlog [AB#1796](https://umbraco.visualstudio.com/243e7927-03b2-44e2-908f-d4ac7ea5daaa/_workitems/edit/1796)_

**Comment by stevemegson** [comment]
Do you get any errors later in the log? Despite the dire warnings about the site possibly not starting, these warnings alone shouldn't cause the upgrade to fail, because the property editor aliases are updated in a later step of the upgrade (at least the built-in ones).

**Comment by bergmania** [comment]
PR: https://github.com/umbraco/Umbraco-CMS/pull/5923

**Comment by Zweben** [comment]
> Do you get any errors later in the log? Despite the dire warnings about the site possibly not starting, these warnings alone shouldn't cause the upgrade to fail, because the property editor aliases are updated in a later step of the upgrade (at least the built-in ones).

I do. Right after the 'skipping validation' warnings, I get thousands of warnings as follows:

`Could not find PropertyData {PropertyDataId} value '{PropertyValue}' in the datatype configuration: {Values}.`

The PropertyDataIds and PropertyValues vary, but the Value is always an empty string.

Right after those finish, the upgrade process halts with this trio of errors:

```
17 Jul 2019 10:21:16 | Error | Database configuration failed
System.NullReferenceException: Object reference not set to an instance of an object.
 
17 Jul 2019 10:21:16 | Error | Installation step "DatabaseUpgrade" failed.
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> Umbraco.Web.Install.InstallException: The database failed to upgrade. ERROR: The database configuration failed with the following message: Object reference not set to an instance of an object.

17 Jul 2019 10:21:16 | Error | An error occurred during installation step "DatabaseUpgrade"
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> Umbraco.Web.Install.InstallException: The database failed to upgrade. ERROR: The database configuration failed with the following message: Object reference not set to an instance of an object.
```

**Comment by stevemegson** [comment]
Since you had the warning about Umbraco.RelatedLinks2, I'd guess that the NullReferenceException that finally kills the upgrade is the one in #5903, failing when no links are selected (though of course that may not be the only problem).

Since you're not getting warnings about the old DropDown aliases, you're probably using Umbraco.DropDown.Flexible and the "Could not find PropertyData value" warnings would be from #5864. I think Umbraco.CheckBoxList could cause a similar problem if you're using that. Unfortunately, getting a complete list of affected data types would be a pain if you've got thousands of warnings - you'd need to look up the PropertyValue in cmsDataTypePreValues.
