### ISSUE TITLE
REFERENCE constraint on IContentService.deleteVerions

### ISSUE THREAD

**Issue by hynekk** [umbraco/Umbraco-CMS#5919]
Hello,

version 8.0.2

on contentService_Saved (ContentService.Saved += ContentService_Saved) to prevent saving huge amount of versions in future I call

```
private void ContentService_Saved(Umbraco.Core.Services.IContentService sender, Umbraco.Core.Events.ContentSavedEventArgs e)
        {
            foreach (var node in e.SavedEntities)
            {
                sender.DeleteVersions(node.Id, DateTime.Now.AddDays(-60));
            }
        }
```

getting

> Server error: Contact administrator, see log for full details. The DELETE statement conflicted with the REFERENCE constraint "FK_umbracoDocumentVersion_umbracoContentVersion_id". The conflict occurred in database "DBNAME", table "dbo.umbracoDocumentVersion", column 'id'. The statement has been terminated.

---
_This item has been added to our backlog [AB#2208](https://umbraco.visualstudio.com/243e7927-03b2-44e2-908f-d4ac7ea5daaa/_workitems/edit/2208)_

**Comment by nul800sebastiaan** [comment]
I can reproduce this one on 8.1.1 as well.

**Comment by nul800sebastiaan** [comment]
Fixed in https://github.com/umbraco/Umbraco-CMS/issues/6259
