### ISSUE TITLE
v7.15.0 Preview does not work

### ISSUE THREAD

**Issue by mariojsnunes** [umbraco/Umbraco-CMS#5921]
Upgraded from 7.13.2 to 7.15.0 and the preview stopped working.
Downgraded to 7.14 and it is now working again.

Reproduction
------------

Just click on the preview button on an instance of v7.15.0

I did some debugging and found that this method returns null:
![image](https://user-images.githubusercontent.com/8073622/61368268-68919980-a885-11e9-933b-e23fb32d6457.png)

Which caused this exception to be thrown:
![image](https://user-images.githubusercontent.com/8073622/61368354-970f7480-a885-11e9-870e-db01e4c5cc77.png)

I obviously did run the health check which was successful, but the problem persisted.
Note that I tried upgrading and downgrading multiple times. Preview never works on v7.15.0, but works on previous versions.

---
_This item has been added to our backlog [AB#1794](https://umbraco.visualstudio.com/243e7927-03b2-44e2-908f-d4ac7ea5daaa/_workitems/edit/1794)_

**Comment by stevemegson** [comment]
Ah, so that's where that exception comes from.

At least for the site I'm seeing it on, it's being caused by deleted items being returned by the SQL in `ContentRepository.BuildPreviewXmlCache`. That confuses the code that finds the parent for each item, and it calls `AppendChild` on a null `parent`.

**Comment by bergmania** [comment]
Hi @mariojsnunes..

I have a hard time reproducing this.

`7.15` has a new preview engine. I assume you run with the default value of `Umbraco.Preview.Mode` in app settings (If not specified)? - Can you please check that it works if you use the old preview engine, by setting the value to `Legacy`.

Do you have the problem on all content items or only on some of them - If so, can you show how the document type looks?

**Comment by svanleusden** [comment]
We were having the same issue on multiple 7.15.0 sites (upgrade from 7.13.2). I've noticed it's an issue with larger sites (2000+ nodes).

Adding this in the web.config made the preview modus working again (like @bergmania mentioned): 
`<add key="Umbraco.Preview.Mode" value="Legacy" />`

**Comment by mariojsnunes** [comment]
Yeah I can confirm. It works with that config.
Is this documented anywhere?
Thanks for the help!

**Comment by Shazwazza** [comment]
Both modes should work, if they do not then there is a bug. The Legacy mode is called "Legacy" for a reason and ideally it is not used anymore. Looks like there is a PR for this so will review.
