### ISSUE TITLE
[8.1] NuCache taking a long time to reload memory cache on large websites

### ISSUE THREAD

**Issue by DMCK96** [umbraco/Umbraco-CMS#5925]
**Description
------------**

Reloading the memory cache on large sites takes an extremely long time when reaching large numbers. This issue does not occur for the content store, only the media store.

Content Store (119K items) took approximately 3-5 minutes to reload.
Media Store (189K items) took approximately 5-6 hours to reload. 

We've noticed the media store is falling over quite frequently and returning media items as null and the only fix we've found is to reload the memory cache although this takes a very long time to complete. This is causing 5 hours of daily downtime to our site.

We narrowed down the issue to the 'AddNodeLocked' method in the NuCache ContentStore. The items cached per minute progressively gets slower. We measured about 5-7K items being cached per minute up to around 70K items at which it had been reduced to about 10% of this speed and continued to slow down as the size of the cache got larger and larger.

_Note for the above: This only occurs on the media store._ 

**Reproduction
------------**

1. Start site with 119K content nodes and 189K media items.
2. Have media items all within a single parent folder
3. Trigger a reload of the memory cache from within 'Settings -> Published Status'

**Specifics
------------**

This issue only began occurring in 8.1, in 8.0 whilst the NuCache was still falling over frequently we could complete a reload of both content and media store in ~5-10 minutes.

No errors are produced in the log during this time. We ran a profiler and followed the source code to determine the cause of the issue. 

**Expected Result
------------**

Full NuCache reload should complete in less than 10 minutes.

**Actual Result
------------**

Full NuCache reload takes over 5 hours to complete.

---
_This item has been added to our backlog [AB#1844](https://umbraco.visualstudio.com/243e7927-03b2-44e2-908f-d4ac7ea5daaa/_workitems/edit/1844)_

**Comment by zpqrtbnk** [comment]
Discussed with OP, and all media items are under root. Meaning root has all media items as children. From 8.0 to 8.1, children went from being managed as arrays of ints, to linked lists, to reduce memory usage. Linked lists are fast when sorted, but slow when inserting and sorting at the same time. Inserting 190K ordered items is slow. Does not happen with content items because they have a tree structure, not all at the same level.

OK to keep linked list for snapshotted lists of children, but need an extra balanced tree for only the live snapshot, for fast inserting. Plus when reloading all, no need to sort during insert as things are coming already sorted.

**Comment by opr** [comment]
So would moving all of the media items into a more "tree-like" structure (similar to how the content is set up) resolve this? Furthermore the media are not under root, but indeed under a single folder one level down from root.

**Comment by zpqrtbnk** [comment]
Reorganizing media items would kinda help, but not completely. It's the children list structures that need to be fixed.

**Comment by RaminMT** [comment]
We also has this problem with same amount of data with Umbraco 8.1
We moved to Umbraco 8.1 as a replace to U8 caching problems but this time we hitted by startup time!

**Comment by Shazwazza** [comment]
We are looking to start investigate this in the next week or two, i'll post updates/findings when i have them.

**Comment by Shazwazza** [comment]
So some notes from investigation...

There's no 'quick wins' based on the perf analysis and the major drain really comes down to just iterating a lot of a ton of querying against the concurrent dictionary to build up the graph. The main bottleneck (as noted) in this method is the AddNodeLocked method which is used in SetAll. SetAll does a lot of stuff while ensuring sort orders, generations, etc... but the thing is, when the site is starting up and we use SetAll based on reading from the nucache files, we can already sort it by level and sort order so most of this overhead can be avoided entirely, we just have to iterate over a sorted set and set the 2 properties that this whole thing is doing: FirstChildContentId, NextSiblingContentId. So I've rewritten a new method: `SetAllFastSorted` which does just that it's a fast forward only iteration and my local benchmarks show that it is a 75% performance improvement.

I've also improve looking up parent nodes, though this didn't happen very often it was querying the dictionary twice per node when this only needed to be done once.

The draft PR is here https://github.com/umbraco/Umbraco-CMS/pull/6131

I will upload a nightly build once i know all tests are passing, etc... 

Would love for @zpqrtbnk to have a peek if he has time as well. Hopefully I'm not overlooking something obvious :)

**Comment by Shazwazza** [comment]
@zpqrtbnk  I've also added a TODO here https://github.com/umbraco/Umbraco-CMS/pull/6131/files#diff-b3bc5e82b4179038edbe4e61342d49ffR44 ... since it seems to me if we 'just' persisted the `FirstChildContentId` + `NextSiblingContentId` values to the btree file we wouldn't need to manually populate these values which means we wouldn't need to sort the whole thing on startup either?

**Comment by zpqrtbnk** [comment]
_have a few comments - let's discuss on Monday_

**Comment by Shazwazza** [comment]
@RaminMT , @DMCK96 here's a nightly build of the binaries with a possible solution. This won't be the final solution but would love to see what the results are with this. Just drop the DLLs in your bin (take a backup first of course!)

[UmbracoCms.AllBinaries.8.1.2-alpha.4521.zip](https://github.com/umbraco/Umbraco-CMS/files/3505737/UmbracoCms.AllBinaries.8.1.2-alpha.4521.zip)

**Comment by RaminMT** [comment]
Hi again @Shazwazza 
I replaced them It started up very soon for the upgrade It also upgraded soon but creating NuCache files took a lot time.
Content cache created in 5 mins but now it's 50 mins waiting to create Media caches and nothing still.
We used to have problem with cache since U8.0, it takes too much time, I tested and find that the "GetPaged" method on NPoco is very slow on U8.0.

**Comment by opr** [comment]
So the site starts up nice and fast now, (previously it would hang while building the NuCache.media.db file) - however the NuCache.Media.db file is now only 4096kb and doesn't look to be growing, furthermore trying to do something like so:

```csharp
var backgroundImage = Model.Value<IPublishedContent>("backgroundImage");
var lowResImageUrl = backgroundImage.GetCropUrl(188, 320);
```

causes a null reference exception.

**Comment by Shazwazza** [comment]
@RaminMT + @opr Sorry i should have been clear, the fix i put in for this DLL is loading from the nucache file, not loading from the DB to create the nucache files. Sounds like you are both starting the website without these local files at all.

There's some unit tests failing that i'll need to fix before i push a diff zip to test, i just wanted to see the difference startup made on your sites when loading from the cache files (when they already exist).

There's also a secondary fix we're investigating. The good news is that we know how it can be resolved, it's just going to take some testing, feedback, etc....

**Comment by Shazwazza** [comment]
I've attached another test fix for you, this fixes a couple of issues and also includes an update for loading the cache in via the db if the nucache files don't exist. In theory this fix should solve the issue though it's still not in it's most ideal format. We do plan on improving this even more for when it's released which i cannot currently provide a date for but please give the attached a try and let me know the results. Thanks!

[UmbracoCms.AllBinaries.8.1.3-alpha.4553.zip](https://github.com/umbraco/Umbraco-CMS/files/3514825/UmbracoCms.AllBinaries.8.1.3-alpha.4553.zip)

**Comment by opr** [comment]
Ooh wow yes this is super quick now! The rebuild takes about four or five minutes with 200k+ nodes (including media and content) and the reload takes about 30 seconds, I think for a site with this much content these times are 100% acceptable! Thanks for investigating this, looking forward to the release, please let me know if I can help any more.

**Comment by Shazwazza** [comment]
Great news :) it might actually get a little faster but we'll see. When items are created or updated, the cache updating will be faster with the next iteration of enhancements (not including in these DLLs).

**Comment by RaminMT** [comment]
Wow!!!
I deleted all the folders in App_Data and that was amazing, It started up very quickly.
I really hope that we can use this build or something better than this on our production site.
Currently we have a mini database (I made a copy with much less data on it) so we could have get our site back working again

**Comment by Shazwazza** [comment]
Here's a newer zip with binaries, this is basically what we will release. If this works for you please feel free to use it until it's available in an upcoming release. Not sure yet if that will be a patch release or a minor.
[UmbracoCms.AllBinaries.8.1.3-alpha.4573.zip](https://github.com/umbraco/Umbraco-CMS/files/3518411/UmbracoCms.AllBinaries.8.1.3-alpha.4573.zip)

**Comment by RaminMT** [comment]
Thanks dear Shannon
I made multiple test on the final release you supplied, it started up in about 1 min on a site with 240K records in umbracoNode table, also it reads and writes to NuCache files so fast event it loads the data from database quickly.
But I found some other problems:
1. Rebuilding database cache will fail with sql connection timeout.
2. Modifying root nodes previously caused rebuilding child items caches, I don't know what happens now but again publish on root nodes or parent nodes will fail with sql connection timeout.
3. Our site has 3 root/home node (each for a language), then there is categories and each category has their child items as news, now opening a category (to see the child items) will fail again with sql connection timeout.
I don't know is it a good idea to increase the connection timeout or not? or how much it should be?

**Comment by opr** [comment]
Ramin, I think the timeout is just a product of running queries that take a long time, I guess you'll have to change the timeout and test what works for you.

Furthermore I know point 2 was addressed here https://github.com/umbraco/Umbraco-CMS/pull/5439 - but a fix wasn't put in place (The PR was rejected because of an oversight) so perhaps something that's being looked at at HQ?

FYI our timeout is set to 36000 this is probably rather on the high side but we don't seem to have any issues with it. Perhaps I could reduce it but I don't really know if there's any point 🤷🏼‍♂️
