### ISSUE TITLE
v7 Breadcrumb doesn't display for new content

### ISSUE THREAD

**Issue by mattbrailsford** [umbraco/Umbraco-CMS#5931]
When editing content in Umbraco, a breadcrumb is displayed along the bottom for context. In earlier versions of Umbraco, this would display on edit and on create, however it seems that it has been disabled from the create view in more recent releases. 

I've fixed this in my build for the client by modifying the `init` method within the `ContentEditController` for the content-editor directive, removing:

````javascript
if (!$scope.page.isNew) {
    if (content.parentId && content.parentId !== -1) {
        entityResource.getAncestors(content.id, 'document').then(function (anc) {
            $scope.ancestors = anc;
        });
    }
}
````
and replacing it with:
````javascript
if (content.parentId && content.parentId !== -1) {
    var ancestorIds = content.path.split(',');
    ancestorIds.shift(); // Remove -1
    if ($scope.page.isNew) {
        ancestorIds.pop(); // Remove 0
     }
    entityResource.getByIds(ancestorIds, 'document').then(function (anc) {
        $scope.ancestors = anc;
        if ($scope.page.isNew) {
            $scope.ancestors.push({ name: "Untitled" })
        }
   });
}
`````

**Comment by emmaburstow** [comment]
Ditto. #CanYouSeeWhatIDidThere? 😂 

We'll prod you if we need you.

Em

**Comment by nul800sebastiaan** [comment]
Fixed in https://github.com/umbraco/Umbraco-CMS/pull/5933
Cherry picked in 7.15.2 802e6d7979b521b2f6fc9ed78090fc1f348b4e31

**Comment by nul800sebastiaan** [comment]
Also fixed in v8 through https://github.com/umbraco/Umbraco-CMS/pull/6128
