### ISSUE TITLE
v7 Return to list view doesn't display for new content

### ISSUE THREAD

**Issue by mattbrailsford** [umbraco/Umbraco-CMS#5932]
When creating a new node as a child of a listview parent, the "return to list view" button is not displayed in the footer. Given we know the context of the parent, this should be displayed.

This can be fixed by updating the `ContentEditController` such that on load of the scaffold, include the following code:

````javascript
if (data.isChildOfListView && data.trashed === false) {
    $scope.page.listViewPath = $routeParams.page ? '/content/content/edit/' + data.parentId + '?page=' + $routeParams.page : '/content/content/edit/' + data.parentId;
}
````

**Comment by nul800sebastiaan** [comment]
Fixed in https://github.com/umbraco/Umbraco-CMS/pull/5934
Cherry picked for 7.15.2 ea591c87a257d0b80c18d5d20336baaa79106f1f
