### ISSUE TITLE
Migration issue from 7.14.0 to 8.1

### ISSUE THREAD

**Issue by SorenHjelmLarsen** [umbraco/Umbraco-CMS#5935]
Hi,
I am trying to migrate a customers db from 7.14.0 to 8.1, the upgrade process starts and runs for 5 hours before hitting VariantsMigration exception "Migration failed: duplicate 'published' document versions.".

After correspondance with Umbraco Support, I was asked to raise a ticket here posting the findings from my logs:
[UmbracoTraceLog.L540.20190716.zip](https://github.com/umbraco/Umbraco-CMS/files/3406103/UmbracoTraceLog.L540.20190716.zip)

The following columns were found in the database, but are not in the current schema:
cmsTags,ParentId,auditEntries,Id,auditEntries,CorrelationId,auditEntries,Username,auditEntries,ActionType,auditEntries,NodeType,auditEntries,NodeId,auditEntries,NodeName,auditEntries,PropAlias,auditEntries,PropNewValue,auditEntries,PropOldValue,auditEntries,AuditDate,cmsTaskType,id,cmsTaskType,alias,cmsTask,closed,cmsTask,id,cmsTask,taskTypeId,cmsTask,nodeId,cmsTask,parentUserId,cmsTask,userId,cmsTask,DateTime,cmsTask,Comment,CMSImportState,Id,CMSImportState,UniqueIdentifier,CMSImportState,Name,CMSImportState,ImportState,CMSImportState,Parent,CMSImportState,ImportProvider,cmsTemplate,design,CMSImportScheduledTask,ScheduleId,CMSImportScheduledTask,ScheduleGUID,CMSImportScheduledTask,ImportStateGUID,CMSImportScheduledTask,ScheduledTaskName,CMSImportScheduledTask,NotifyEmailAddress,CMSImportScheduledTask,ExecuteEvery,CMSImportScheduledTask,ExecuteDays,CMSImportScheduledTask,ExecuteHour,CMSImportScheduledTask,ExecuteMinute,CMSImportScheduledTask,ImportAsUser,cmsContent,pk,cmsContent,nodeId,cmsContent,contentType,CMSImportRelation,Id,CMSImportRelation,UmbracoID,CMSImportRelation,DataSourceKey,CMSImportRelation,ImportProvider,CMSImportRelation,Updated,CMSImportRelation,CustomId,CMSImportMediaRelation,Id,CMSImportMediaRelation,UmbracoMediaId,CMSImportMediaRelation,SourceUrl,CMSImportMediaRelation,ByteSize,cmsContentVersion,id,cmsContentVersion,ContentId,cmsContentVersion,VersionId,cmsContentVersion,VersionDate,CMSImportScheduledItems,ScheduledItemId,CMSImportScheduledItems,ScheduleldTaskId,CMSImportScheduledItems,ScheduledOn,CMSImportScheduledItems,ExecutedOn,CMSImportScheduledItems,InProgress,cmsDocument,nodeId,cmsDocument,published,cmsDocument,documentUser,cmsDocument,versionId,cmsDocument,text,cmsDocument,releaseDate,cmsDocument,expireDate,cmsDocument,updateDate,cmsDocument,templateId,cmsDocument,newest,marketport_category_lookup,pcCategoryId,marketport_category_lookup,pcCategoryIdentifier,marketport_category_lookup,mpCategoryIdentifier,marketport_category_lookup,mpCategoryId,marketport_product_lookup,pcGlobalProductNumber,marketport_product_lookup,mpItemId,marketport_product_lookup,mpObjectTypeId,convatec_searches,Id,convatec_searches,SiteIdentifier,convatec_searches,Query,convatec_searches,CreatedDateTime,cmsDataType,pk,cmsDataType,nodeId,cmsDataType,propertyEditorAlias,cmsDataType,dbType,cmsDataTypePreValues,id,cmsDataTypePreValues,datatypeNodeId,cmsDataTypePreValues,value,cmsDataTypePreValues,sortorder,cmsDataTypePreValues,alias,umbracoDomains,id,umbracoDomains,domainDefaultLanguage,umbracoDomains,domainRootStructureID,umbracoDomains,domainName,umbracoMigration,id,umbracoMigration,name,umbracoMigration,createDate,umbracoMigration,version,cmsMacro,macroScriptType,cmsMacro,macroScriptAssembly,cmsMacro,macroXSLT,cmsMacro,macroPython,passwordtokens,Id,passwordtokens,TokenId,passwordtokens,Username,passwordtokens,UtcDateExpire,cmsMedia,nodeId,cmsMedia,versionId,cmsMedia,mediaPath,cmsContentXml,nodeId,cmsContentXml,xml,cmsPreviewXml,nodeId,cmsPreviewXml,versionId,cmsPreviewXml,timestamp,cmsPreviewXml,xml,cmsPropertyData,id,cmsPropertyData,contentNodeId,cmsPropertyData,versionId,cmsPropertyData,propertytypeid,cmsPropertyData,dataInt,cmsPropertyData,dataDate,cmsPropertyData,dataNvarchar,cmsPropertyData,dataNtext,cmsPropertyData,dataDecimal,toolbox_urlredirects,UrlRedirectId,toolbox_urlredirects,Active,toolbox_urlredirects,RedirectFrom,toolbox_urlredirects,RedirectTo,toolbox_urlredirects,Validated,toolbox_urlredirects,Created,toolbox_urlredirects,Updated,toolbox_urlredirects,ValidatedAt,toolbox_urlredirects,UmbracoDomain,marketport_mediasync,Id,marketport_mediasync,SyncedOn,cmsContentType,isElement,cmsContentType,variations,umbracoContent,nodeId,umbracoContent,contentTypeId,umbracoContentVersion,id,umbracoContentVersion,nodeId,umbracoContentVersion,versionDate,umbracoContentVersion,userId,umbracoContentVersion,current,umbracoContentVersion,text,umbracoMediaVersion,id,umbracoMediaVersion,path,umbracoDocument,nodeId,umbracoDocument,published,umbracoDocument,edited,umbracoDataType,nodeId,umbracoDataType,propertyEditorAlias,umbracoDataType,dbType,umbracoDataType,config,umbracoLanguage,isDefaultVariantLang,umbracoLanguage,mandatory,umbracoLanguage,fallbackLanguageId,umbracoDomain,id,umbracoDomain,domainDefaultLanguage,umbracoDomain,domainRootStructureID,umbracoDomain,domainName,umbracoLog,entityType,umbracoLog,parameters,cmsMacro,macroSource,cmsMacro,macroType,cmsPropertyType,variations,umbracoPropertyData,id,umbracoPropertyData,versionId,umbracoPropertyData,propertyTypeId,umbracoPropertyData,languageId,umbracoPropertyData,segment,umbracoPropertyData,intValue,umbracoPropertyData,decimalValue,umbracoPropertyData,dateValue,umbracoPropertyData,varcharValue,umbracoPropertyData,textValue,cmsTags,languageId,umbracoRedirectUrl,culture,cmsContentNu,nodeId,cmsContentNu,published,cmsContentNu,data,cmsContentNu,rv,umbracoDocumentVersion,id,umbracoDocumentVersion,templateId,umbracoDocumentVersion,published,umbracoKeyValue,key,umbracoKeyValue,value,umbracoKeyValue,updated,umbracoContentVersionCultureVariation,id,umbracoContentVersionCultureVariation,versionId,umbracoContentVersionCultureVariation,languageId,umbracoContentVersionCultureVariation,name,umbracoContentVersionCultureVariation,date,umbracoContentVersionCultureVariation,availableUserId,umbracoDocumentCultureVariation,id,umbracoDocumentCultureVariation,nodeId,umbracoDocumentCultureVariation,languageId,umbracoDocumentCultureVariation,edited,umbracoDocumentCultureVariation,available,umbracoDocumentCultureVariation,published,umbracoDocumentCultureVariation,name,umbracoContentSchedule,id,umbracoContentSchedule,nodeId,umbracoContentSchedule,languageId,umbracoContentSchedule,date,umbracoContentSchedule,action

The following constraints (Primary Keys, Foreign Keys and Indexes) were found in the database, but are not in the current schema:
FK_cmsContent_cmsContentType_nodeId,FK_cmsContent_umbracoNode_id,FK_cmsContentVersion_cmsContent_nodeId,FK_cmsContentXml_cmsContent_nodeId,FK_cmsDataType_umbracoNode_id,FK_cmsDataTypePreValues_cmsDataType_nodeId,FK_cmsDocument_cmsContent_nodeId,FK_cmsDocument_cmsTemplate_nodeId,FK_cmsDocument_umbracoNode_id,FK_cmsMedia_cmsContent_nodeId,FK_cmsMedia_umbracoNode_id,FK_cmsMember_cmsContent_nodeId,FK_cmsMember_umbracoNode_id,FK_cmsPreviewXml_cmsContent_nodeId,FK_cmsPreviewXml_cmsContentVersion_VersionId,FK_cmsPropertyData_cmsPropertyType_id,FK_cmsPropertyData_umbracoNode_id,FK_cmsPropertyType_cmsDataType_nodeId,FK_cmsTags_cmsTags,FK_cmsTask_cmsTaskType_id,FK_cmsTask_umbracoNode_id,FK_cmsTask_umbracoUser,FK_cmsTask_umbracoUser1,FK_umbracoDomains_umbracoNode_id,FK_umbracoRedirectUrl,FK_umbracoNode_umbracoUser_id,FK_umbracoContent_umbracoNode_id,FK_umbracoContent_cmsContentType_NodeId,FK_umbracoContentVersion_umbracoContent_nodeId,FK_umbracoContentVersion_umbracoUser_id,FK_umbracoMediaVersion_umbracoContentVersion_id,FK_umbracoDocument_umbracoContent_nodeId,FK_umbracoDataType_umbracoNode_id,FK_umbracoLanguage_umbracoLanguage_id,FK_umbracoDomain_umbracoNode_id,FK_umbracoLog_umbracoUser_id,FK_cmsMember_umbracoContent_nodeId,FK_cmsPropertyType_umbracoDataType_nodeId,FK_umbracoPropertyData_umbracoContentVersion_id,FK_umbracoPropertyData_cmsPropertyType_id,FK_umbracoPropertyData_umbracoLanguage_id,FK_cmsTags_umbracoLanguage_id,FK_umbracoRedirectUrl_umbracoNode_uniqueID,FK_cmsContentNu_umbracoContent_nodeId,FK_umbracoDocumentVersion_umbracoContentVersion_id,FK_umbracoDocumentVersion_cmsTemplate_nodeId,FK_umbracoContentVersionCultureVariation_umbracoContentVersion_id,FK_umbracoContentVersionCultureVariation_umbracoLanguage_id,FK_umbracoContentVersionCultureVariation_umbracoUser_id,FK_umbracoDocumentCultureVariation_umbracoNode_id,FK_umbracoDocumentCultureVariation_umbracoLanguage_id,FK_umbracoContentSchedule_umbracoContent_nodeId,FK_umbracoContentSchedule_umbracoLanguage_id,PK_auditEntries,PK_cmsContent,PK_cmsContentPreviewXml,PK_cmsContentVersion,PK_cmsContentXml,PK_cmsDataType,PK_cmsDataTypePreValues,PK_cmsDocument,PK_CMSImportMediaRelation,PK_CMSImportRelation,PK_CMSImportScheduledItems,PK_CMSImportScheduledTask,PK_CMSImportState,PK_cmsMedia,PK_cmsPropertyData,PK_cmsTask,PK_cmsTaskType,PK_convatec_searches,PK_marketport_mediasync,PK_OldPC_CategoryLookup,PK_OldPC_ProductLookup,PK_passwordtokens,PK_structure,PK_toolbox_urlredirects,PK_umbracoDomains,PK_umbracoMigration,PK_umbracoNode,PK_umbracoContent,PK_umbracoContentVersion,PK_umbracoMediaVersion,PK_umbracoDocument,PK_umbracoDataType,PK_umbracoDomain,PK_umbracoPropertyData,PK_cmsContentNu,PK_umbracoDocumentVersion,PK_umbracoKeyValue,PK_umbracoContentVersionCultureVariation,PK_umbracoDocumentCultureVariation,PK_umbracoContentSchedule

Hope you can help.
Best Regards,
Søren

---
_This item has been added to our backlog [AB#1838](https://umbraco.visualstudio.com/243e7927-03b2-44e2-908f-d4ac7ea5daaa/_workitems/edit/1838)_

**Comment by stevemegson** [comment]
Running this query on your original database should show which documents have more than one version claiming to be published:

    SELECT cmsContentVersion.ContentId, COUNT(cmsContentVersion.id)
    FROM cmsContentVersion
    JOIN cmsDocument ON cmsContentVersion.versionid=cmsDocument.versionid
    WHERE cmsDocument.published=1
    GROUP BY cmsContentVersion.ContentId
    HAVING COUNT(cmsContentVersion.id) > 1

At least, assuming that the duplicates are already present and aren't being caused by something weird during the migration.

**Comment by SorenHjelmLarsen** [comment]
Hi Steve,

Thank you for that query I was able to locate the corrupted data, and remove it, which fixed the issue :)

Cheers,
Søren
