### ISSUE TITLE
v7 Bulk publish / unpublish on listview doesn't update listview styles

### ISSUE THREAD

**Issue by mattbrailsford** [umbraco/Umbraco-CMS#5936]
When bulk publishing / unpublished items in a list view the action itself does occur, however the listview doesn't update it's styles, so items that were unpublished (alpha .4) are still faded out untill the list is releaded.

Should probably add code to reload the contents in the same way the delete bulk action does.

**Comment by kjac** [comment]
Possible duplicate of #5907

**Comment by mattbrailsford** [comment]
Closing as duplicate
