### ISSUE TITLE
V8.1 Document type importing doesn't work

### ISSUE THREAD

**Issue by ReVoid** [umbraco/Umbraco-CMS#5937]
Importing document types doesn't work at all, nothing happens on uploading: no exceptions, no error messages, just nothing.

There was an similar issue at Umbraco 8.0 #4788 and It closed with 8.1 release.

Reproduction
------------

### Specifics

Umbraco 8.1 clean install

### Steps to reproduce

> 1 Create a new document type and add at least one property of any datatype.
> 2 Export document type. It will generate a file with .udt extension
> 3 Delete the document type from umbraco.
> 4 Import document type (Settings > Docuemnt type > click on three dots and click "Do Something Else" button and select Import document type)
> 5 Select .udt file which you exported in step 2

### Expected result

Document type appears in settings tree

### Actual result

Nothing happens

**Comment by stevemegson** [comment]
It looks like the issue in 8.0 was fixed, but then #5563 caused a new problem.

When you click the Import button to select the file, a click is generated on a hidden file input. Since that hidden element is outside the Import Document Type dialog, the dialog closes. Then when you finish picking the file, nothing happens because the dialog that was supposed to be waiting for the result has gone.

Before #5563, a click on any input element was not treated as an outside click, so the click on the hidden element was ignored.

**Comment by ReVoid** [comment]
@stevemegson Most likely you are right. Do you know how to push that button manualy even if bar is closed?

**Comment by stevemegson** [comment]
My temporary hack to test it was just removing the on-outside-click attribute from the dialog so that it wouldn't close. I guess the real solution would be another check in on-outside-click to ignore the hidden element, though I'm not sure what the best test would be.

**Comment by stevemegson** [comment]
This has been fixed by reverting PR #5609.

**Comment by nul800sebastiaan** [comment]
Indeed that fixed it.

**Comment by stixoffire** [comment]
I am seeing this issue on v8.3 but only with one particular document . I am trying to transfer it from one base install into a different installation. I have successfully transferred other .udt files just not the people, person udts ..

**Comment by ReVoid** [comment]
> I am seeing this issue on v8.3 but only with one particular document . I am trying to transfer it from one base install into a different installation. I have successfully transferred other .udt files just not the people, person udts ..
> 
> Ok I found out the issue. If the content is derived from a base object the base object must be imported first - make sure you don't miss any base objects ..

@stixoffire If an error was thrown or nothing clear happened, maybe you should add a feature request or issue.
