### ISSUE TITLE
Cannot login to authorize upgrade from 7.15.0 to 8.1.0

### ISSUE THREAD

**Issue by MichaelNielsenDK** [umbraco/Umbraco-CMS#5953]
I'm following the migration guide here
https://our.umbraco.com/documentation/Umbraco-Cloud/Upgrades/Migrating-from-7-to-8/ 

After following all the steps in "Step 1: Content migration", I run the v8.1 project locally, and have to login to authorize the upgrade. 

I however cannot login with the Umbraco Cloud credentials, it just says "Login failed". 

I've tried it 3 times now, with the same result. 

I've also attached the .mdf file in SQL Server Management, and the user is in the DB, active with an encrypted password.

I have no problem logging in with the same credentials on the v7.15 locally.

**Comment by MichaelNielsenDK** [comment]
Further investigation shows this is not a bug in itself, but something to be aware of when your 7.15 was born on a much lower version of 7.x, and then upgraded.

Previous versions of Umbraco had several properties on the UsersMembershipProvider in web.config that are now omitted. 

After copying those properties from the v7.15 project to the v8.1 project, the login works.

**Comment by mecograph** [comment]
Could you elaborate a bit more on which properties you mean? I've stumbled upon the same issue.

**Comment by stevemegson** [comment]
@mecograph the key ones are `passwordFormat` and `useLegacyEncoding`, which tell Umbraco how to interpret the passwords stored in the database. I believe the defaults changed in 7.6.0.

**Comment by MichaelNielsenDK** [comment]
@mecograph I'm not sure exactly which properties were the issue, I just copied all on UsersMembershipProvider from the 7.15 project to the 8 project, and then everything worked fine.

**Comment by mecograph** [comment]
thanks for the response, did the same and it resolved the issue
