### ISSUE TITLE
Non default/mandatory language variants dissapearing

### ISSUE THREAD

**Issue by deMD** [umbraco/Umbraco-CMS#5957]
After some days all our content seems to have dissapeared from the non default/mandatory language variant. On top of that the error log also seems to be corrupt and can't be viewed in Umbraco.

Currently I have no clue what happened, but I can't even find any data in the database.

I have attached the umbraco log file with this issue hoping someone might be able to see something. Any questions are ofcourse welcome.
[Umbracolog.log](https://github.com/umbraco/Umbraco-CMS/files/3411606/Umbracolog.log)

Umbraco 8.0.2

**Comment by deMD** [comment]
After republishing a single English article to check if the table 'umbracoDocumentCultureVariation' is the table that should store all languages, we can confirm all data was removed from the database somehow. We are currently unable to see any reason why. We can confirm that the database did not roll back to an earlier version, as mandatory language content is all intact up until today.

**Comment by deMD** [comment]
After digging a lot more we did find a change in the database for which we have no explanation:
![image](https://user-images.githubusercontent.com/22070292/61548201-6c701800-aa4d-11e9-86aa-b9c4a370a1fb.png)
The ID of the English language changed. And it seems that with that change all content related to the old ID was removed.

**Comment by KevinJump** [comment]
I would suggest this is happening because uSync is being used, and issue #5959 (LocalizationService.GetLanguageByIsoCode my return language different to the one requested) is causing uSync to think it has found a language and delete it when in fact it has found the parent on (en) in this case. 

this issue can probibly be closed ?

**Comment by nul800sebastiaan** [comment]
Thanks @KevinJump  I'll close this one and #5959 will be worked on. I'm sorry for the trouble we caused @deMD ! 🙈
