### ISSUE TITLE
Cannot delete user groups in 8.1

### ISSUE THREAD

**Issue by bkclerke** [umbraco/Umbraco-CMS#5958]
In v8.1 I am not able to delete user groups in the backoffice. I receive an error. I am receiving this error on a site that I upgraded from 8.0.1 and I was able to replicate this issue on a clean install of 8.1. 

All I did was navigate to the backoffice and try to delete existing default groups when I received the error. Either deleting one, or multiple, I still received an error. I also tried deleting a custom group I was able to make and still got an error.

The error I received:
![Screen Shot 2019-07-19 at 8 06 13 AM](https://user-images.githubusercontent.com/4968254/61545642-c5fc2680-a9fc-11e9-96bd-8c5db223daa3.png)

I can copy and paste the error if needed as well.

**Comment by kjac** [comment]
@bkclerke thanks for reporting 👍 there's already a PR for this in #5912. Leave this issue open, I'll cross link to the PR.

**Comment by bkclerke** [comment]
@kjac sorry for the duplicate! I did just a quick search and didn't see that one but thank you for referencing it! I'm glad a fix is in works! :)

**Comment by kjac** [comment]
It's no duplicate, I submitted a fix without reporting the but 😀 and no matter what... Rather have duplicate reports than missing ones 👍

**Comment by nul800sebastiaan** [comment]
Fixed in https://github.com/umbraco/Umbraco-CMS/pull/5912
Cherry picked for 8.1.3 3b60815e5304d39cc8fa5dc686fcd0656b68b5ca
