### ISSUE TITLE
LocalizationService.GetLanguageByIsoCode my return language different to the one requested

### ISSUE THREAD

**Issue by KevinJump** [umbraco/Umbraco-CMS#5959]
Calling the LocalizationService GetLanguageByIsoCode may return a 'parent' language to the one requested if it can't find it. 

e.g GetLanguageByIsoCode("en-US") will return the "en" language if the en-US language is missing. 

this may or may not be a bug but the method should be at least annotated to tell you that you might not get what you asked for - maybe there should be a fallback option exposed? 

ultimately it happens in the repo: https://github.com/umbraco/Umbraco-CMS/blob/e5956e4955474694c12ed6da7a4d5600acd0af8c/src/Umbraco.Core/Persistence/Repositories/Implement/LanguageRepository.cs#L240

**Comment by kjac** [comment]
For reference: The reason for doing so is described in #4519 

The new option to localize the backoffice using the language files (#5358) may also weigh in on any decision to undo #4519 😄

**Comment by ronaldbarendse** [comment]
Ouch, that's not a change you would add to a repository, especially without opt-in! 😮

And PR https://github.com/umbraco/Umbraco-CMS/pull/4519 doesn't correctly get the parent culture for cultures that contain multiple dashes or just different names (e.g. `zh-Hans-HK`, which parents are `zh-CHS` > `zh-Hans` > `zh`).

**Comment by kjac** [comment]
I'll pick this one up 👍

**Comment by kjac** [comment]
OK so... we can't solve this with an opt-in/overload on the affected method(s) without causing a breaking change on `ILanguageRepository`. 

Given how #5358 now allows us to localize the backoffice independently of the dictionary and the active languages, perhaps the best approach here is to simply revert #4519 and no longer (attempt to) support fallbacks to culture invariant translations in the dictionary? Unless there is some Cloud implication I am unaware of here - can you have user defined language overrides on Cloud?

**Comment by nul800sebastiaan** [comment]
Thanks @kjac - I know you slept on it and had some more clever ideas, look forward to seeing those!

**Comment by kjac** [comment]
@nul800sebastiaan you got it 😆 new PR in #6090 reverts the changes from #4519 and adds the same feature by other means.

**Comment by nul800sebastiaan** [comment]
Fixed in https://github.com/umbraco/Umbraco-CMS/pull/6090

Cherry picked to 8.1.3 in 87845ee907c65a5ba09c62803b98c34649fde6ba
