### ISSUE TITLE
v8.1.0 Blank screen after sign in

### ISSUE THREAD

**Issue by erikjanwestendorp** [umbraco/Umbraco-CMS#5974]
Umbrac 8.1.0. Blank screen after creating a new user group and assign permissions to the member section only. Related to a question on our: 
https://our.umbraco.com/forum/using-umbraco-and-getting-started/98260-user-access 

Steps to reproduce
------------

- Create a new user group e.g. members.
- Assign access to the member section only. 
- Create a user and assign access to the member group
- Sign in and a blank screen will appear. 

![image](https://user-images.githubusercontent.com/7831614/61637741-5dc97100-ac98-11e9-9654-abd26c536b14.png)

![image](https://user-images.githubusercontent.com/7831614/61637835-88b3c500-ac98-11e9-84dd-1875c3331e11.png)
![image](https://user-images.githubusercontent.com/7831614/61637960-c0bb0800-ac98-11e9-9689-d15c804b1586.png)

### Specifics

Umbraco V8.1.0 (Migrated from v7.14.0)

### Expected result

I expected to see the member section after sign in. 

### Actual result

A blank screen with some console errors, see image below. 

![image](https://user-images.githubusercontent.com/7831614/61638461-be0ce280-ac99-11e9-9dd4-ad8305c880d4.png)

**Comment by kjac** [comment]
Hi! I believe this is a duplicate of #5641?

**Comment by erikjanwestendorp** [comment]
You are absolutely right, I will close this one.
