### ISSUE TITLE
8.1: Random SerializationException crashes site

### ISSUE THREAD

**Issue by Zweben** [umbraco/Umbraco-CMS#5977]
I recently created a brand-new Umbraco Cloud environment that started on 8.1. As this project is being used as the destination for a v8 migration, and I have been unable to get a v7 to v8 database upgrade to complete, I re-created all of the data types, document types and media types manually on a local environment. After doing this, at seemingly random intervals, the site keeps crashing with the following error, when trying to initialize the website or simply while navigating through the backoffice:

`System.Runtime.Serialization.SerializationException: 'Type 'Umbraco.Core.Models.PublishedContent.VariationContext' in assembly 'Umbraco.Core, Version=8.0.0.0, Culture=neutral, PublicKeyToken=null' is not marked as serializable.'`

As soon as I hit "Continue" to proceed past that error message, the site stops running.

The site has no content or media on it, only database schema that Deploy imported from UDA files, which were created from the configuration I input into the empty CMS by hand.

Reproduction
------------

### Steps to reproduce

- Create a new Umbraco Cloud v8.1 site
- Clone locally
- Run in VS 2017 via LocalDB
- Add data types and document types
- Navigate through the backoffice

**Comment by nul800sebastiaan** [comment]
Hi @Zweben - very strange, can't say we heard about this before. Of course that class is not currently marked as Serializable, but I also don't know if it should be. Do you have logs with a stack trace maybe? We could have a look as to why it's trying to serialize this class.

**Comment by Zweben** [comment]
> Hi @Zweben - very strange, can't say we heard about this before. Of course that class is not currently marked as Serializable, but I also don't know if it should be. Do you have logs with a stack trace maybe? We could have a look as to why it's trying to serialize this class.

@nul800sebastiaan - Fortunately/unfortunately, I am no longer able to reproduce the issue. This and other stability issues in v8.1.0 seemed to resolve themselves after importing content onto the site. I believe when the error occurred, there was no content on the site, only settings.

**Comment by nul800sebastiaan** [comment]
Fortunately/unfortunately! I'll close this for now and hope for the best :-)
