### ISSUE TITLE
V8.1: Error publishing content varying by culture with parent that doesn't vary by culture

### ISSUE THREAD

**Issue by Appstract-fjellvang** [umbraco/Umbraco-CMS#5981]
After updating our site to version 8.1 from version 8.0.1 we're having issues with content varying by culture which parent is not varying by culture.

Reproduction
------------

1. Create a home node which is varying by culture. Publish it for a given language, IE English.
2. Create a child of said home node which is NOT varying by culture. Publish it.
3. Create a child of 2. which is varying by culture, and publish it.

The node created in step 3 will publish fine, but will state the following in the info tab:

![image](https://user-images.githubusercontent.com/46595925/61700532-2234b280-ad3d-11e9-9f92-d48cc7be6af1.png)

likewise for nodes created before the upgrade the links section in the info tab will state: "This item is not published" republishing will for the most case not throw any errors, but reloading the page will again state that the item is not published.

For a few cases on our site publishing a node which was failing threw an exception related to the NuCache - I've described that here: https://our.umbraco.com/forum/umbraco-8/98275-umbraco-81-content-issues-post-upgrade

Anyone else experiencing similar issues?

**Comment by Appstract-fjellvang** [comment]
Note: also tested it with a completely fresh installation of umbraco 8.1 - Same issue

**Comment by Shazwazza** [comment]
This is a duplicate, see https://github.com/umbraco/Umbraco-CMS/issues/5886#issuecomment-513080455 and https://github.com/umbraco/Umbraco-CMS/issues/5973
