### ISSUE TITLE
Umbraco 8 caching CurrentUmbracoPage

### ISSUE THREAD

**Issue by KirilRupasov** [umbraco/Umbraco-CMS#5984]
Hi,
We have recently upgraded from Umbraco 6 to 8. One of the big changes in Umbraco is caching. There is an issue with displaying validation errors on some of our pages.

Reproduction
------------

### Bug summary

When having a form in a macro and with required fields, it is expected to see the required fields highlighted if they wee left out blank when submitting a form. However, probably because of caching, I am seeing the same page with no validation feedback when submitting an incomplete form.

### Steps to reproduce

1) Create a controller with `[HttpPost]` method that receives form that follows the standard pattern:

```
if (ModelState.IsValid == false)
{
      return CurrentUmbracoPage();
}
```

2) Create a macroPartial form that will have form fields with validation, e.g.:

```
<div class="input-group">
        @Html.LabelFor(m => model.Name)
        @Html.EditorFor(m => model.Name)
        @Html.ValidationMessageFor(m => model.Name)
    </div>
```

3) Create a corresponding model with `Required` fields.

4) Run the example, try to partially fill in the form and submit it.

### Expected result

Umbraco displaying the same form and indicating which fields have not been filled\validated.

### Actual result

Same form, with no validation feedback.

### Additional context

I believe it is strongly connected to caching, because once I Reload Memory Cache in Umbraco backoffice, and refresh the page, it highlights the fields that have not been filled.

There is a link, which might be related:

https://our.umbraco.com/forum/umbraco-8/92359-how-will-the-nucache-influence-model-alteration-in-the-pipeline

It states that, " I am talking about retrieving a model from cache, and adding stuff to it - that will not work anymore."; which might be the case in this situation.

Thanks!

**Comment by Shazwazza** [comment]
Validation responses is purely do to ModelState in MVC, no changes or anything are made to models. If you just refresh the page (not reload memory cache) does it still highlight the fields that have not been filled in?

**Comment by KirilRupasov** [comment]
No, the fields that have not been filled in are still not being highlighted when the page is refreshed.

**Comment by KirilRupasov** [comment]
Also, I need to mention  that the macro is included via the Body Text on a content page and we suspect that the Body Text value is cached when it's included in the template: 
```
@Model.Value("bodyText")
```

**Comment by Shazwazza** [comment]
I think that's more likely the issue which is not related to the posted our thread above. Will need to investigate.

**Comment by JannesMeyer** [comment]
I think this "our" thread is more relevant: https://our.umbraco.com/forum/templates-partial-views-and-macros/96748-macro-parial-view-always-cached-even-if-caching-disabled

It seems that Enny is having the same problem in that thread. It's unclear whether he/she ended up filing that bug report.

**Comment by G1itcher** [comment]
Having the same issue as described by the person in the thread @JannesMeyer posted. Macros with dynamic data are being cached.

**Comment by nul800sebastiaan** [comment]
Fixed in https://github.com/umbraco/Umbraco-CMS/pull/6010
Cherry picked to 8.1.4 703092c12c979a8902afe7676c18beade4005f99
