### ISSUE TITLE
ExamineManagementController expects LuceneIndex on IndexOperationComplete

### ISSUE THREAD

**Issue by ksingercoffey** [umbraco/Umbraco-CMS#5986]
I'm writing a custom IIndex that inherits from BaseIndexProvider. I notice that, while rebuilding does work, the UI fails to report that it's done.

Reproduction
------------

Create an index inherited from BaseIndexProvider and try to rebuild from the UI.

### Bug summary

In ExamineManagementController.Indexer_IndexOperationComplete() it casts to LuceneIndex. I believe this could be cast to BaseIndexProvider instead?

### Expected result

UI updates when rebuilding the index is done.

### Actual result

UI throws a javascript error and the load indicator never goes away.

**Comment by Shazwazza** [comment]
Please always provide version information in bug reports, what Umbraco version are you referring to?

If this is v8 it's probably a duplicate of https://github.com/umbraco/Umbraco-CMS/pull/5801

**Comment by ksingercoffey** [comment]
Oh shoot I didn't even think to search pull requests first. That's the exact problem, and it was in 8.1.0. I'll close. Thank you!
