### ISSUE TITLE
Property type Byte becomes integer when using Create.Table or Alter.Table

### ISSUE THREAD

**Issue by danieland** [umbraco/Umbraco-CMS#5988]
Could be related to #5376

--

When creating a custom database, the DbType seems to not be optimal. 

Using
`Alter.Table(tableName).AddColumn("ThisBecomesInt").AsByte().NotNullable().Do();`
or
`[ColumnType(typeof(Byte))]`
`public Byte Level { get; set; }`
will result in the SQL column being the type "int" instead of expected "tinyint".

I was unsure if this was a support question (intended) or bug report - I think it's probably a bug report since there are some pretty big performance implications of forcing use of 4 bytes instead of 1.

I could also be terribly misinformed and maybe there's a good reason for this like some SQL CE related or similar - would be interesting to find out !

**Comment by nul800sebastiaan** [comment]
That's indeed the "same" issue as https://github.com/umbraco/Umbraco-CMS/issues/5376 indeed, I'll close this one, the other one is up for grabs if you want to look at helping to implement the functionality.

I had a quick google and I can't figure out if SQL CE supports `Byte`, if it does not then there would need to be some extra code to make sure SQL CE uses a different type for storing that kind of data.
