### ISSUE TITLE
v8 no focal point in media model in mediaPicker

### ISSUE THREAD

**Issue by Malthebp** [umbraco/Umbraco-CMS#5989]
The focal point is missing in the mediaPicker model/target from the infinite editor. 
As far as I am concerned Umbraco is also trying to use the focal point, but it is undefined.

Reproduction
------------

### Steps to reproduce

1. create a custom grid editor.
2. use the editorService.mediaPicker(config)
3. see the model in the submit - no focal point is added to the model even though you can select one.

### Expected result

A model with the focal point.

### Actual result

A model without focal point.

**Comment by nul800sebastiaan** [comment]
Fixed in https://github.com/umbraco/Umbraco-CMS/pull/5991
