### ISSUE TITLE
Copy grid layout from [other language] button

### ISSUE THREAD

**Issue by FrontisBV** [umbraco/Umbraco-CMS#5990]
Hi,

We often use the grid view and when filling the second language version, these pages cost the most time. 

The default fields (template) are already present on the page in the second language, but the blocks that are placed in the grid view are not. This means that you have to manually re-add and fill all these blocks. The split view option helps, but still this is a lot of work.

It could save us (and our customers) a lot of time when there was a '**copy grid layout from [other language] button'**. 

When clicking this button, the user should be able to copy all blocks from the grid layout of (the same page on) a different language version.

So, hereby I send you the request to develop this function in Umbraco.
Hope you guys will pick this up and make our life a bit easier ;-)

Regards,
Frontis 
(Lieke)

**Comment by nul800sebastiaan** [comment]
Thanks @FrontisBV - this is being worked on for the future, see the following issue: https://github.com/umbraco/Umbraco-CMS/issues/5551
