### ISSUE TITLE
Unable to remove start nodes

### ISSUE THREAD

**Issue by Luksor** [umbraco/Umbraco-CMS#5995]
Reproduction
------------

### Bug summary

![image](https://user-images.githubusercontent.com/5837521/61802410-491be300-ae28-11e9-9c6a-607af71fe8ef.png)

There is no way of removing a content / media start node from a user.

### Specifics

* Umbraco version: 8.1.0

### Steps to reproduce

* Assign a start node to a user.
* The option to unassign the node is missing.

### Expected result

There should be a way of removing a node assignment.

### Actual result

There is no option allowing removal of node assignment.

**Comment by kjac** [comment]
Oh nice one! Thanks @Luksor, looks like it was half way implemented but never completed. I'll submit a PR shortly 👍

**Comment by kjac** [comment]
PR in #5999

**Comment by nul800sebastiaan** [comment]
Fixed in https://github.com/umbraco/Umbraco-CMS/pull/5999 and cherry picked for 8.1.2 in https://github.com/umbraco/Umbraco-CMS/commit/a9a5d00916d2ce1129a2963619167eb48eba2a8a
