### ISSUE TITLE
8.1: GetPagedCurrentUserLog returns NodeId which is just the database ID for the Log table not related to any nodes.

### ISSUE THREAD

**Issue by jmayntzhusen** [umbraco/Umbraco-CMS#6000]
Reproduction
------------

If you're filing a bug, please describe how to reproduce it. Include as much
relevant information as possible, such as:

### Bug summary
This issue comes from using the Angular `logResource.getPagedUserLog` which returns a `nodeId`.

However for the same node that value seemed to auto increment, I then found that the logResource calls the `GetPagedCurrentUserLog` method which maps the result to this `nodeId`. 

It gets it from the database as just dto.id though, which is not really useable in the backoffice for nodes.

### Specifics
Testing on v8.1, found this based on a v7 article, which leads me to believe this has worked differently in the past, but I haven't confirmed.

### Steps to reproduce

Make a call to `GetPagedCurrentUserLog` - check the returned `nodeId`, it will correspond to ids for entries in the [umbracoLog] table, not nodes.

### Expected result
Expected a nodeId that would correspond to some kind of content or media node.

### Actual result
Got the id of the row in the audit table from the database.

**Comment by marcemarc** [comment]
@jmayntzhusen we had a similar fix applied in V7 https://github.com/umbraco/Umbraco-CMS/pull/3759

**Comment by jmayntzhusen** [comment]
Thanks @marcemarc 

This made me realize it is not the Audit table rather the Log table it is getting the info from 😁

Then I guess the same fix should do it for v8 as well!

**Comment by nul800sebastiaan** [comment]
Fixed in: https://github.com/umbraco/Umbraco-CMS/pull/6052

Cherry picked for 8.1.4 cec4376d199e617546292d726829c0a456c75655
