### ISSUE TITLE
Database Error v7.15 to v8.1 PK_umbracoLock constraint

### ISSUE THREAD

**Issue by cerdts** [umbraco/Umbraco-CMS#6007]
The database failed to upgrade. ERROR: The database configuration failed with the following message: 'PK_umbracoLock' is not a constraint.
 Could not drop constraint. See previous errors. Please check log file for additional information (can be found in '/App_Data/Logs/')
[UmbracoTraceLog.HC2220.20190726.json.txt](https://github.com/umbraco/Umbraco-CMS/files/3437197/UmbracoTraceLog.HC2220.20190726.json.txt)

**Comment by nul800sebastiaan** [comment]
Hey @cerdts - apologies for the delay. Seems like your database is in some kind of inconsistent state. We expect PK_umbracoLock to exist. 

Try creating it like so:

```
ALTER TABLE umbracoLock ADD  CONSTRAINT [PK_umbracoLock] PRIMARY KEY CLUSTERED 
(
	[id] ASC
) ON [PRIMARY]
```

After that you should be able to continue the migration.
