### ISSUE TITLE
8.1: Grid umb-overlay is offset in infinite editor

### ISSUE THREAD

**Issue by AlphaDelta** [umbraco/Umbraco-CMS#6011]
When the 'Add content' button in a grid in an infinite editor is clicked the umb-overlay is offset greatly from where the mouse was clicked

The expected result is the umb-overlay is positioned where the center of the umb-overlay is the exact position of where the mouse clicked when it was opened.

I believe the issue resides in the `setTargetPosition()` function in the umbOverlay directive: https://github.com/umbraco/Umbraco-CMS/blob/faef449750a41dc0142aedd6faa6017e4b9d7f42/src/Umbraco.Web.UI.Client/src/common/directives/components/overlays/umboverlay.directive.js#L380-L444

I have observed this occurring both when using my own custom infinite editor and in the multi-treenode picker content infinite editor.

See below where the umb-overlay is offset enough that it overflows the view port
![image](https://user-images.githubusercontent.com/2088238/62021425-44d23a00-b21b-11e9-90d3-2594878ad90d.png)

Reproduction
------------

**1.** Create a document type with a grid and a multi tree node picker with the 'Show open button' option checked.
![image](https://user-images.githubusercontent.com/2088238/62021574-0f7a1c00-b21c-11e9-9ba8-5b014d5bf221.png)

**2.** Create a page in the content section with the same document type

**3.** Save

**4.** Click 'Add' on the multi-treenode picker property

**5.** Select the page you just created, or alternatively any page that has a grid property

**6.** Click the 'open' button
![image](https://user-images.githubusercontent.com/2088238/62021711-b3fc5e00-b21c-11e9-81ba-13097a9c77a8.png)

**7.** Select any row configuration

**8.** Click 'Add Content' and observe the umb-overlay is offset from the position you clicked

**Comment by nul800sebastiaan** [comment]
I think this duplicates #6032 so I'll close this one.
