### ISSUE TITLE
Content not being saved for Nested content field of Element Type when 'Allow varying by Culture' = false

### ISSUE THREAD

**Issue by tomasforde** [umbraco/Umbraco-CMS#6015]
Umbraco 8.1

Field with 'Allow Varying By culture' = false on Element type  with 'Allow varying by culture' = true not being saved to the database when element type is being used in Nested content control.

Reproduction
------------
### Steps to reproduce

* Create new Document type `NestedElementType1`
  * Is Element Type = true
  * Allow varying by Culture = true
  * Add one field:
    * name=`title` and Allow varying by Culture = true
* Create Data type for `NestedElementType1` and add to a document type (i.e. `DocType1`)
* Add `DocType1` node, and add a few sample `NestedElementType1` rows. 
  * Save/Publish
  * Reload `DocType1` node in backend. Note that all `title` values supplied are displayed. Note also that nested content row headers are the same as `title` values
* Modify `NestedElementType1`
  * Set Allow varying by Culture = true for `title` field
*  Reload `DocType1` page in 'Content' section of Umbraco backend
  * Click on any `NestedElementType1` row header. Note that value in all headers change from `title` value to 'Item n'
* Save/Publish `DocType1` page
* Reload `DocType1` page in 'Content' section of Umbraco backend
* Note all `title` values are set to blank

### Expected result

Fields where 'Allow varying by Culture'=false in non-nested content are read-only in non-default language. I don't see a valid reason why can be a field with 'Allow varying by Culture'=false on a nested element type where 'Allow varying by Culture'=true. However, I do not expect to see the `title` fields entered earlier being removed (or set to blank).

**Comment by kjac** [comment]
Hi! Thanks for your detailed issue description 👍

I believe this issue has been reported already and is fixed in https://github.com/umbraco/Umbraco-CMS/pull/5952 ?

**Comment by tomasforde** [comment]
@kjac This is the same issue. Thanks for linking me to it 👍
