### ISSUE TITLE
Umbraco v8 - language on content tree and on content window

### ISSUE THREAD

**Issue by kw-jeremic** [umbraco/Umbraco-CMS#6022]
Hello Umbraco team.

I have strange situation when working with language drop-downs, on tree window and on content window.
**Main problem** is that when switching to some other site language and then selecting some content node in tree structure, language drop-down for content is always selected on default language.

We got a client which has 10 languages for site, and their content editors noticed and reported this situation, which makes them a problem in the way that they can easily mix languages.
Strange thing is that in version 8.0.2 it's working as expected, and in 8.1.0 and 8.1.1 it has different behavior.

### Scenario ( v 8.0.2)
  1. Some language (not default language) one is selected and nothing is selected on content tree
  2. Click on any content node in tree structure
  3. Page content is opening, language drop-down is selected to the language which was selected in step 1

See, video in zip file -> Umbraco 8.0.2.mp4

### Scenario (v 8.1.1, 8.1.0)
  1. Some language (not default language) one is selected and nothing is selected on content tree
  2. Click on any content node in tree structure
  3. Page content is opening, language drop-down is selected to the default language, not to the one which I previously selected in step 1

See, video in zip file ->Umbraco8.1.1.mp4

I uploaded 2 videos in zip file.
[Videos - Umbraco Variants.zip](https://github.com/umbraco/Umbraco-CMS/files/3447262/Videos.-.Umbraco.Variants.zip)

### Question
Is this change by purpose in version 8.1.0 and 8.1.1 or it's bug ?

**Comment by kjac** [comment]
Uh ouh. I can reproduce this in 8.1.1 - it's definitively a bug. The editor language should conform to `mculture` unless `cculture` is specified, but it doesn't.

I'll have a look into this.

**Comment by kjac** [comment]
PR in #6026

**Comment by nul800sebastiaan** [comment]
Fixed in https://github.com/umbraco/Umbraco-CMS/pull/6026

Cherry picked for 8.1.3 - c87a22f3475bc14f51a42690dc91afa0fabcb63b

**Comment by kw-jeremic** [comment]
I manually applied the fix :) All good from our side, it works now as charm.
General question, fix should be included in version 8.1.3, right?

**Comment by nul800sebastiaan** [comment]
Great to hear!

That's what `release/8.1.3` means yeah! ;-)
