### ISSUE TITLE
ApplicationEventHandler default weight of -100 not set on Umbraco.Web ApplicationEventHandlers

### ISSUE THREAD

**Issue by bowserm** [umbraco/Umbraco-CMS#6024]
All of the ApplicationEventHandlers in the `Umbraco.Web` project are being assigned a default weight of 100 instead of -100. The problem is happening when the `ApplicationEventsResolver` tries to determine the weight of  ApplicationEventHandlers using the `GetObjectWeight` method. The `ApplicationEventsResolver` does not consider the `umbraco.dll` a core assembly because the FullName of that assembly does not have the `.` at the end.

### Steps to reproduce

1. Check out fresh copy of UmbracoCms repository (I used version 7.15.1)
1. Open the `.sln` in VS and add a breakpoint to the `GetObjectWeight` method in `/Umbraco.Core/ObjectResolution/ApplicationEventsResolver.cs`
1. Set the `Umbraco.Web.UI` as the startup project
1. Run the project through IIS Express through VS

### Expected result

When the breakpoint is hit for ApplicationEventHandlers in the `Umbraco.Web` project (the `umbraco.dll`), those ApplicationEventHandlers should be flagged as core ApplicationEventHandlers and given the -100 default weight.

### Actual result

Because the `.FullName` of the `umbraco.dll` assembly is `umbraco, Version=1.0.7150.17328, Culture=neutral, PublicKeyToken=null`, it is not recognized as a core assembly. ApplicationEventHandlers in the `Umbraco.Web` project are assigned a default weight of 100.

**Comment by Shazwazza** [comment]
Yes i can see the problem on this line of code:

```cs
// we should really attribute all our Core handlers, so this is temp
var core = name.InvariantStartsWith("Umbraco.") || name.InvariantStartsWith("Concorde.");
```

It is definitely not checking for the `umbraco` assembly (which is the Umbraco.Web project)

I've submitted a PR for review

**Comment by Shazwazza** [comment]
Ah, sorry i didn't recognize there was already a PR for it, i'll comment on the existing PR but i don't think all of those changes are necessary.

**Comment by warrenbuckley** [comment]
This got fixed by this PR
https://github.com/umbraco/Umbraco-CMS/pull/6331

**Comment by nul800sebastiaan** [comment]
Marked as breaking because technically people could've been relying on the old behavior somehow.
