### ISSUE TITLE
Multiple Media Picker property editor does not have sortable items

### ISSUE THREAD

**Issue by whatwasmyusername** [umbraco/Umbraco-CMS#6035]
I'm running Umbraco 8.1.1 and properties with the grid editor alias of Umbraco.MediaPicker are no longer sortable.

Reproduction
------------

### Bug summary

Sorting of the media in a media picker property are not sortable even when the media picker is setup to allow multiple items.

### Specifics
* Running on Umbraco 8.1.1
* $scope.sortableOptions is initialized before the setupViewModel() call where the property $scope.isMultiPicker is initialized, so $scope.sortableOptions.disabled is always **true**.
* Source file: https://github.com/umbraco/Umbraco-CMS/blob/v8/dev/src/Umbraco.Web.UI.Client/src/views/propertyeditors/mediapicker/mediapicker.controller.js

### Steps to reproduce

* Create a media picker property with the "Pick multiple items" enabled
* Attempt to edit a content item with that field
* Images are not sortable

### Expected result
Media should be able to be dragged and dropped into desired order.

### Actual result
Media items are not sortable.

**Comment by kjac** [comment]
I can reproduce this. The sorting is also a bit buggy when it's forced enabled, so I'll have a look at both.

**Comment by kjac** [comment]
PR in #6037

**Comment by nul800sebastiaan** [comment]
Fixed in https://github.com/umbraco/Umbraco-CMS/pull/6037

Cherry picked for 8.1.5 089e450e09bd5d9e40ead8af2edc88658671e534
