### ISSUE TITLE
Umbraco V8: Media section, visible path to images

### ISSUE THREAD

**Issue by uSkinned** [umbraco/Umbraco-CMS#6042]
Not sure if this is by design however in Umbraco 7 you could see the full path to images. In Umbraco 8 you only see the file name when on the info tab when viewing an image in the media section.

![Screenshot (3)](https://user-images.githubusercontent.com/22817718/62362220-70ec0480-b514-11e9-91ab-3a208a736b55.png)

**Comment by kjac** [comment]
This is deliberate from a time where the image URLs in v8 were very long. That precondition may no longer be applicable.

**Comment by nul800sebastiaan** [comment]
Hey there @uSkinned - At the moment you can click / copy the link to the file and get the full path from there.
I'm curious to hear what kind of useful information it would add to have the full path displayed in the backoffice?

**Comment by uSkinned** [comment]
Hi Sebastiaan,

Its just what we are used to. Always helpful to know where a file is located on the server at a quick glance. Not a huge deal however just wanted to check if this was intentional.

Cheers,

Marc

**Comment by nul800sebastiaan** [comment]
Alright, I'll file this under "who moved my cheese?" for now! 🧀 😉

If there's good reasons to expose the path again then we're all ears!

**Comment by uSkinned** [comment]
cool.
