### ISSUE TITLE
Creating a new MediaType beneath a parent, doesn't set the parent as a composition

### ISSUE THREAD

**Issue by tompipe** [umbraco/Umbraco-CMS#6047]
When creating a new MediaType beneath an existing MediaType, the composition is not set correctly, and any properties from the parent MediaType are not inherited by the child MediaType.

**Actual**
![image](https://user-images.githubusercontent.com/629719/62375521-60e51c80-b536-11e9-9632-45fec0d03a74.png)

Confirmed in latest v7/dev and v8/dev branches

**Expected**
![image](https://user-images.githubusercontent.com/629719/62375753-df41be80-b536-11e9-9579-dd9c7f088d0a.png)

PRs incoming :)

**Comment by nul800sebastiaan** [comment]
Fixed in v7 - https://github.com/umbraco/Umbraco-CMS/pull/6050\
Cherry picked for 7.15.2 f829ac4e6cfc9c20af70f0ce90e6c7a44e0111e8

Fixed in v8 - https://github.com/umbraco/Umbraco-CMS/pull/6049
Cherry picked for 8.1.3 ece7178ef544cd5f359d9f9c695c675616776dc3
