### ISSUE TITLE
The "Edit permissions for this document type" button does not work

### ISSUE THREAD

**Issue by tom-ingeniuus** [umbraco/Umbraco-CMS#6048]
Tested in Umbraco 8.1.0 and 8.1.1 on latest Chrome browser on Windows 10 Professional

If you go to create a child node on a document type which doesn't have any allowed child document types you get a message and a button to let you click to edit the document type. 

Clicking this button does nothing. No errors appear in the console. The popout menu closes and nothing else, I would expect to be taken to the screen where I can edit the specific document type permissions.

I have shown this button here.

![edit permissions button](https://user-images.githubusercontent.com/49899682/62375864-2d56c200-b537-11e9-960a-7b192ee77fbd.PNG)

**Comment by kjac** [comment]
That's bizarre... I just posted a fix for this a couple of hours ago 😛

https://github.com/umbraco/Umbraco-CMS/pull/6041

Thanks for reporting! I'll crosslink this issue and the fix.

**Comment by nul800sebastiaan** [comment]
Fixed in https://github.com/umbraco/Umbraco-CMS/pull/6041
