### ISSUE TITLE
The v8 Log Viewer should display the current log level

### ISSUE THREAD

**Issue by tom-ingeniuus** [umbraco/Umbraco-CMS#6055]
As far as I can tell there is no way the check the current log level without looking at the serilog.config file.

I would be handy if the current log level was shown on the home screen of the log viewer.

applies to v8.1.1

I think it would also be useful if the log level was added to the Health Check so that a minimum level of Warning is recommended for live sites (I will create a separate issue for this, but mention it here to save someone else adding this.)

t

**Comment by nul800sebastiaan** [comment]
Fiuxed in: https://github.com/umbraco/Umbraco-CMS/pull/6059
