### ISSUE TITLE
Health Check in v8 should warn you if the log level is not at least set to Warning

### ISSUE THREAD

**Issue by tom-ingeniuus** [umbraco/Umbraco-CMS#6056]
I believe it is recommended practice that the log level on live sites should not be the default level setup on installing Umbraco, therefore, I think that the log level should be added to the Health Check dashboard so that a minimum level of Warning is recommended for live sites.

This applies to v8.1.1

**Comment by nul800sebastiaan** [comment]
Hey @tom-ingeniuus - thanks for the feature request. Had a little chat at HQ and we believe this is too subjective at the moment. We think that Info is perfectly fine for most people and will allow you to more easily debug issues if they seem to happen at random times.

Maybe this is a candidate health check for this project? https://our.umbraco.com/packages/backoffice-extensions/ourumbracohealthchecks/
