### ISSUE TITLE
V8: infiniteMode or infinityMode - typo?

### ISSUE THREAD

**Issue by leekelleher** [umbraco/Umbraco-CMS#6058]
Whilst developing a custom property-editor, I'd noticed in the angularjs controller `model` there are properties for both **`infiniteMode`** and **`infinityMode`**.  I can't help but think that the latter is a typo.

I've searched over the latest (v8.1.1) source code and found the following references...

- https://github.com/umbraco/Umbraco-CMS/blob/release-8.1.1/src/Umbraco.Web.UI.Client/src/views/components/editor/umb-editors.html#L8
- https://github.com/umbraco/Umbraco-CMS/blob/release-8.1.1/src/Umbraco.Web.UI.Client/src/common/directives/components/editor/umbeditors.directive.js#L20
- https://github.com/umbraco/Umbraco-CMS/blob/release-8.1.1/src/Umbraco.Web.UI.Client/src/less/components/editor/umb-editor.less#L20-L27
- https://github.com/umbraco/Umbraco-CMS/blob/release-8.1.1/src/Umbraco.Web.UI.Client/src/less/components/editor/subheader/umb-editor-sub-header.less#L42-L44

Is this a typo? Should we correct it? _(I'm not sure what this means in terms of a breaking-change)_

**Comment by Shazwazza** [comment]
it should be infinite :/ I'm sure there's some magic way to make it not breaking but it probably won't be pretty.

**Comment by kjac** [comment]
How about just implementing infiniteMode everywhere and keep infinityMode supported as deprecated until say 8.3? Obvs this would need to be mentioned in the release notes for 8.2 then and maybe also in the next patch release.

I'm sure I can pick this task up if need be.

**Comment by kjac** [comment]
Ah. Turns out we can safely remove the typo. "infinityMode" is not used in any directive specifications or similar. It is solely used for inner workings (and wrongly so, see PR description in #6084), so we're not breaking anything by removing it.

**Comment by leekelleher** [comment]
![buzz_lightyear_to_infinity_and_beyond](https://user-images.githubusercontent.com/209066/62756157-9de96b80-ba6e-11e9-8853-306f74bcf1a7.jpg)

**Comment by soreng** [comment]
"infinie" was also in use until recently

https://github.com/umbraco/Umbraco-CMS/pull/6054/commits/4d91f6b3d7341df99c4bd32f3cee3bf7febd361e

**Comment by nul800sebastiaan** [comment]
Fixed in https://github.com/umbraco/Umbraco-CMS/pull/6084

Cherry-picked for 8.1.3 in https://github.com/umbraco/Umbraco-CMS/commit/a0cd542ba30a1c93022cd8f55ff2c3917900f103
