### ISSUE TITLE
DB Configuration failed when migrating from 7.15.1 to 8.1.1

### ISSUE THREAD

**Issue by SorenHjelmLarsen** [umbraco/Umbraco-CMS#6060]
Hi, when i try upgradeing existing Umbraco 7.15.1 to 8.1.1, i am getting hit with  the following error in the logs:

`{"@t":"2019-08-05T15:54:23.9290820Z","@mt":"Database configuration failed","@l":"Error","@x":"System.NullReferenceException: Object reference not set to an instance of an object.\r\n   ved Umbraco.Core.Migrations.Upgrade.V_8_1_0.ConvertTinyMceAndGridMediaUrlsToLocalLink.Migrate() i E:\\dev v8\\src\\Umbraco.Core\\Migrations\\Upgrade\\V_8_1_0\\ConvertTinyMceAndGridMediaUrlsToLocalLink.cs:linje 56\r\n   ved Umbraco.Core.Migrations.MigrationBase.Umbraco.Core.Migrations.IMigration.Migrate() i E:\\dev v8\\src\\Umbraco.Core\\Migrations\\MigrationBase.cs:linje 73\r\n   ved Umbraco.Core.Migrations.MigrationPlan.Execute(IScope scope, String fromState, IMigrationBuilder migrationBuilder, ILogger logger) i E:\\dev v8\\src\\Umbraco.Core\\Migrations\\MigrationPlan.cs:linje 310\r\n   ved Umbraco.Core.Migrations.Upgrade.Upgrader.Execute(IScopeProvider scopeProvider, IMigrationBuilder migrationBuilder, IKeyValueService keyValueService, ILogger logger) i E:\\dev v8\\src\\Umbraco.Core\\Migrations\\Upgrade\\Upgrader.cs:linje 67\r\n   ved Umbraco.Core.Migrations.Install.DatabaseBuilder.UpgradeSchemaAndData(MigrationPlan plan) i E:\\dev v8\\src\\Umbraco.Core\\Migrations\\Install\\DatabaseBuilder.cs:linje 498","SourceContext":"Umbraco.Core.Migrations.Install.DatabaseBuilder","ProcessId":11288,"ProcessName":"iisexpress","ThreadId":16,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"L540","Log4NetLevel":"ERROR","HttpRequestNumber":7,"HttpRequestId":"c8e6736e-b0cc-4e14-ba01-d64c473c5cb0"}
`
I am currently debuging the Upgrade process to see if i can figure out which object it is failing on.

Any pointers or hints would be greatly appreciated :)
Best Regards,
Søren

---
_This item has been added to our backlog [AB#2237](https://umbraco.visualstudio.com/243e7927-03b2-44e2-908f-d4ac7ea5daaa/_workitems/edit/2237)_

**Comment by stevemegson** [comment]
It looks like you have a grid value where one of the cells has no value in the JSON. That is, no `value` property at all rather than `"value": null`.

Tracking down the offending content may be a bit awkward, though.

**Comment by SorenHjelmLarsen** [comment]
Hi Steve,

Thank you for that, I found 200 occurences.

I have cleaned them out and are running the Upgrade process again.

I will post the result, once it is done.

Cheers,
Søren

**Comment by SorenHjelmLarsen** [comment]
Hi Steve,

Unfortunately my re-try resulted in the same error.
Am I correct to assume that any null values will throw this error?
So that if my Custom Grid Editor, eg. have a property called "video" and the value is "null" I will get this error?

**Comment by SorenHjelmLarsen** [comment]
I am not sure if it is the same issue as this: [#5846 ](5846)

**Comment by stevemegson** [comment]
Yes, `"value": null` should be fine. Did you check everything in cmsPropertyData, or only current versions?

It's closely related to #5846, but the fix for that issue doesn't help us. It's handling cases where a grid property has non-JSON data stored (probably because the property used to be some other data type), but we have valid JSON data that's not in the expected format.

There's a straightforward fix to the migration to stop it failing on the unexpected data (I'll do a PR when I get chance), but that doesn't help you with the current upgrade.

**Comment by SorenHjelmLarsen** [comment]
I only checked current versions, will go through cmsPropertyData.
I have downloaded a copy of dev/8 repo, and put breakpoints in the Migrate method, to see if I can track any pointers.

**Comment by stevemegson** [comment]
If you're using a local build, you could change the offending line and test the fix that I have in mind. It should be as simple as adding a question mark to line 56:

    if (controlValue?.Type == JTokenType.String)

Maybe we should be taking the opportunity to add in `"value": null` where the value is missing, but I think the Grid editor can deal with the missing property anyway.

**Comment by SorenHjelmLarsen** [comment]
I will test it out, without adding in `"value": null` first.

**Comment by SorenHjelmLarsen** [comment]
`if (controlValue?.Type == JTokenType.String)`

Resulted in:

`{"@t":"2019-08-07T11:52:52.7074430Z","@mt":"Database configuration failed","@l":"Error","@x":"System.InvalidOperationException: Cannot access child value on Newtonsoft.Json.Linq.JValue.\r\n   ved Newtonsoft.Json.Linq.JToken.get_Item(Object key) i /_/Src/Newtonsoft.Json/Linq/JToken.cs:linje 321\r\n   ved Umbraco.Core.Migrations.Upgrade.V_8_1_0.ConvertTinyMceAndGridMediaUrlsToLocalLink.Migrate() i E:\\dev v8\\src\\Umbraco.Core\\Migrations\\Upgrade\\V_8_1_0\\ConvertTinyMceAndGridMediaUrlsToLocalLink.cs:linje 55\r\n   ved Umbraco.Core.Migrations.MigrationBase.Umbraco.Core.Migrations.IMigration.Migrate() i E:\\dev v8\\src\\Umbraco.Core\\Migrations\\MigrationBase.cs:linje 73\r\n   ved Umbraco.Core.Migrations.MigrationPlan.Execute(IScope scope, String fromState, IMigrationBuilder migrationBuilder, ILogger logger) i E:\\dev v8\\src\\Umbraco.Core\\Migrations\\MigrationPlan.cs:linje 310\r\n   ved Umbraco.Core.Migrations.Upgrade.Upgrader.Execute(IScopeProvider scopeProvider, IMigrationBuilder migrationBuilder, IKeyValueService keyValueService, ILogger logger) i E:\\dev v8\\src\\Umbraco.Core\\Migrations\\Upgrade\\Upgrader.cs:linje 67\r\n   ved Umbraco.Core.Migrations.Install.DatabaseBuilder.UpgradeSchemaAndData(MigrationPlan plan) i E:\\dev v8\\src\\Umbraco.Core\\Migrations\\Install\\DatabaseBuilder.cs:linje 498","SourceContext":"Umbraco.Core.Migrations.Install.DatabaseBuilder","ProcessId":16816,"ProcessName":"iisexpress","ThreadId":7,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"L540","Log4NetLevel":"ERROR","HttpRequestNumber":7,"HttpRequestId":"f12a7a8c-d711-4c31-a37e-f6ab24aa23f3"}
`
I will try and test a solution where `"value": null` is being set.

**Comment by stevemegson** [comment]
It was never going to be that easy, was it?

I suspect that the new error is coming from a different grid value, where the "controls" array contains a string or number instead of the expected JSON object. Something like

     "controls": ["oops", "not an object", { "value":"", "editor":{ ... } }]

So rather than getting `null` when we try to read `control["value"]`, it complains that reading a property from a string makes no sense.

I've no idea how that would happen or what the grid editor will do with it, but I guess we just want to check that `control` is a `JObject` before we try to read the value.

**Comment by SorenHjelmLarsen** [comment]
`if(control is JObject)
                            {
                                var controlValue = control["value"];
                                if (controlValue?.Type == JTokenType.String)
                                {
                                    control["value"] = UpdateMediaUrls(mediaLinkPattern, controlValue.Value<string>());
                                }
                            }   `
worked like a charm to go around Non JObjects, I do not know if there are any other object types that will be excluded by this.

During GridPropertyIndexValueFactory.cs GetIndexValues() method:

A control in row.areas is being found with `value = null` inserting check on value not being null should solve this

**Comment by nul800sebastiaan** [comment]
I love the conversation you two have going here, thanks for helping each other out! I am a bit lost on what is actually going on but that's alright. Have you gotten any further now @SorenHjelmLarsen or are you stuck? 

The changes so far as suggested by @stevemegson seem to help, maybe it's time to start a PR for them?

**Comment by SorenHjelmLarsen** [comment]
> `if(control is JObject) { var controlValue = control["value"]; if (controlValue?.Type == JTokenType.String) { control["value"] = UpdateMediaUrls(mediaLinkPattern, controlValue.Value<string>()); } } `
> worked like a charm to go around Non JObjects, I do not know if there are any other object types that will be excluded by this.
> 
> During GridPropertyIndexValueFactory.cs GetIndexValues() method:
> 
> A control in row.areas is being found with `value = null` inserting check on value not being null should solve this

The `if(control is JObject)` led to Installation Completed message and the solution I have is indeed now running on 8.1.1 @nul800sebastiaan 

It did show a error during retrieving the Index values, which was caused by a null refference, it may have been the exact same data set that caused the original error. A simple check for `if(control.Value != null)` will avoid that.
