### ISSUE TITLE
v8: Action button in tree is not visible for longer tree name

### ISSUE THREAD

**Issue by bjarnef** [umbraco/Umbraco-CMS#6063]
When the tree node name has a long name (or the width of the tree area is decreased) the action button is not visible, because the text push the button to the right.

For now you can either use the right-click on the node to open the actions menu or increase the width of the tree area).

![2019-08-07_08-42-04](https://user-images.githubusercontent.com/2919859/62600789-0958ff00-b8f0-11e9-988a-2d804a7235a1.gif)

The issue was previously fixed in IE in this PR https://github.com/umbraco/Umbraco-CMS/pull/2207 .. but it seems either some other changes have re-introduced this issue or an browser update.

It also seems when the action button in the tree is partly visible the tree node "jumps" a bit.

Tested on Umbraco v8.1.0 and v8.1.1 and in Firefox v68.0.1 and Chrome v75.0.3770.142

**Comment by bjarnef** [comment]
It seems the tree item doesn't allow to shrink on hover as previously.
This seems to fix is partly, although the tree node still "jumps" a bit. Furthermore it seems the added `sr-only` class override some of the styling on `umb-options` class.

![image](https://user-images.githubusercontent.com/2919859/62601597-065f0e00-b8f2-11e9-9dd8-a177de7df1ed.png)

**Comment by bjarnef** [comment]
The "jump" effect seems to be caused by `sr-only` having `margin: -1px;`
This class is added to both the tree node name and the action button menu, where it on hover in some cases move the tree node by 1px.

It is actually even worse, when using tab key to focus the tree nodes, e.g. by clicking the Data Types folder and then start enter tab key.

![2019-08-07_09-48-53](https://user-images.githubusercontent.com/2919859/62604599-b172c600-b8f8-11e9-8799-95f48a12009e.gif)

**Comment by nul800sebastiaan** [comment]
Good investigation @bjarnef - do your solutions grouped together work now? Could be good if they could be combined in a PR maybe?

**Comment by bjarnef** [comment]
@nul800sebastiaan I will have a look at this and submit a PR. It would also be nice if we could have this loader in core, so we could re-use this like `umb-load-indicator` and e.g. use this in the tree loader. https://github.com/umbraco/Umbraco-CMS/pull/4987
At the moment this is a div inside the tree, but much if the styling for `umb-loader` is redundant several places in backoffice UI.

**Comment by bjarnef** [comment]
PR submitted https://github.com/umbraco/Umbraco-CMS/pull/6094

**Comment by nul800sebastiaan** [comment]
Fixed in https://github.com/umbraco/Umbraco-CMS/pull/6094
Cherry picked to 8.1.3 d5d213cd44a264606e3139bc5bc3df7af92cb429
