### ISSUE TITLE
Comments for entity.resource.js have incorrect method name, defiling documentation

### ISSUE THREAD

**Issue by amitch17** [umbraco/Umbraco-CMS#6068]
The documentation generated from the javascript comments is wrong for https://our.umbraco.com/apidocs/v8/ui/#/api/umbraco.resources.entityResource

The method name is getById, but the example code is entityResource.getEntityById

Similar issue for getByIds.

Newbies or Lazies (like me) who cut and paste get unnecessary errors.

**Comment by nul800sebastiaan** [comment]
Thanks for the PR @amitch17 - it will take a little while to roll the documentation out since it's not entirely automated right now but rest assured it will pop up on Our soon enough. 👍
