### ISSUE TITLE
Missing dirty check in document type editor

### ISSUE THREAD

**Issue by clausjensen** [umbraco/Umbraco-CMS#6098]
When using the doctype editor, there seems to be no dirty check happening when trying to navigate away.

Reproduction
------------

### Specifics

Tested in latest Umbraco 8.

### Steps to reproduce

- Navigate to a document type.
- Add or remove a property.
- Navigate to a different document type.

### Expected result

I would expect to get the "you have unsaved changes" warning.

### Actual result

I am taken to the other document type and my changes on the current one are discarded.

**Comment by kjac** [comment]
I could've sworn I fixed this once. Maybe that was in V7... or maybe my memory is playing tricks on me 😆 anyway.... PR in #6108
