### ISSUE TITLE
8.1.1 Element type Invariant By Culture Property will have messed up alias.

### ISSUE THREAD

**Issue by Appstract-fjellvang** [umbraco/Umbraco-CMS#6101]
As of umbraco 8.1.1 if you have an Document type, maked as element type, being variant by culture, any of its invariant properties will have a messed up alias.

Reproduction
------------

1. Create a document type, mark it as varying by culture.
2. Create one property, call it variant, mark it as varying by culture.
3. Create another property, call it invariant, mark it it as not varying by culture.
4. Create a nested content picker using the newly created element type.
5. Use this nested content property on a document type.
6. Inspect it in the content tree:
Invariant alias:
![image](https://user-images.githubusercontent.com/46595925/62862577-82988d80-bd06-11e9-91e3-50a529809040.png)
Variant alias:
![image](https://user-images.githubusercontent.com/46595925/62862608-980db780-bd06-11e9-963a-253f74d016a3.png)
7. Notice how the invariant property type has an extra __variantNested appended.

This has caused us some errors saving content on a production website.

The error doesnt occur on umbraco 8.0.2.
Our solution has been to mark all properties as variant by culture, then no alias's are messed up.

**Discussion:**
------------

I guess an element type varying by culture doesn't make much sense with the current functionality.

It seems right now that if i have a nested content on a document type, i set it to invariant by culture, then i can only publish it on the main culture. Trying to inspect it on a different culture, it will be greyed out with the status that it's inherited by the main culture. In short, the element types properties will always be invariant by culture.

My assumption of a nested content picker which is invariant by culture but with element types that has variant by culture properties is that: If a list is defined on the main culture the other cultures should be able to inspect that list, and only modify the properties of the element types which are varying by culture.

In turn if my assumption is wrong, and if element types are not used by something else which i'm forgetting, maybe the option to set element types to be varying by culture, should be removed?

**Comment by kjac** [comment]
Hi @Appstract-fjellvang, thanks for reporting 😄 

I do believe this is a duplicate of #5817 - specifically https://github.com/umbraco/Umbraco-CMS/issues/5817#issuecomment-511808227 - which has a PR in #5952

**Comment by Appstract-fjellvang** [comment]
@kjac Yeah that seems right. Thank you!
