### ISSUE TITLE
V8: Cannot edit dates in custom (en-GB) formats with date picker (flatpickr)

### ISSUE THREAD

**Issue by amitch17** [umbraco/Umbraco-CMS#6102]
If a data type is set to use the date picker (Flatpickr) with a custom date format, it is not handled correctly when editing content. 

Dates may be parsed as invalid and blanked, or dates and months get switched around.

### Specifics

This occurs when editing content in the back office.
Umbraco 8.1.1 (cloud)
Observed in Chrome.

### Steps to reproduce

* Create a data type using the Date Picker property editor.
* Set the Date format to be "DD-MM-YYYY" This is valid according to momentjs rules.

![DateDataType](https://user-images.githubusercontent.com/18399155/62875763-7ec33600-bd1b-11e9-862c-94ffea4f6ccf.PNG)

* Save data type
* Create a document type, and a field that uses this Date type
* Create an instance of this document in the content tree
* edit the date field, select a date, e.g. 10th August, the date picker closes and displays 10-08-2019
* click elsewhere on the document (to blur the control)
* the date value switches over the digits to become 08-10-2019.  (it tries to parse the date in MM-DD-YYYY format?)

![datepicker-toggling digits](https://user-images.githubusercontent.com/18399155/62876869-c9de4880-bd1d-11e9-80c4-1a23953fcf66.gif)

Alternative:
* If a date is selected that is not valid in the original format, it is cleared.  e.g. Select 20th August, blur the control, and the value is cleared because 20/08/2019 is not valid in MM-DD-YYYY format.

![datepicker-invalid-date](https://user-images.githubusercontent.com/18399155/62876882-ce0a6600-bd1d-11e9-96b8-bd565ff877c4.gif)

It looks like the date is still selected in the dropdown calendar but there is no option to clear the value (the cross) in this case.

### Expected result

* When blurring the date control, the value in the date field should be unchanged.

Same problem occurs with date time picker.

**Comment by nul800sebastiaan** [comment]
I think this is a duplicate of https://github.com/umbraco/Umbraco-CMS/pull/6001? Can you confirm please @amitch17?

**Comment by amitch17** [comment]
Yes, this is a duplicate of that issue, well spotted mr @nul800sebastiaan  

I did search for flatpickr but didn't find this report. Sorry for the noise.

Haven't tested the fix myself but it looks to be doing the right things - can the PR by @stevemegson 
 get some attention please?
