### ISSUE TITLE
Macro Content Picker start node configuration

### ISSUE THREAD

**Issue by elliottjb7** [umbraco/Umbraco-CMS#6104]
When setting up macro's it'd be fantastic if macro content pickers could be configured to have a start node. It's cumbersome to navigate to a particular node from the beginning of the content tree. I'm just beginning to add new Authors to our instance of Umbraco and this would be a really handy feature!

**Comment by nul800sebastiaan** [comment]
Hi again @elliottjb7 - it is a lovely feature request but unfortunately not something that we are going to work on. Currently there is no way for any macro parameter editor to be configured, that would be a large change.

I'll refer to #6105 as well for this one and mention the new block editor which should hopefully make things a lot easier for you.

For now, you can definitely do this yourself, you already know how to make a custom parameter editor which would be a content picker that you pass a start node in to. 👍
