### ISSUE TITLE
Media Picker: Custom Media Types Being Treated As Folders

### ISSUE THREAD

**Issue by JamesSherborne** [umbraco/Umbraco-CMS#6106]
Hi,

I think I have a new issue and was hoping someone could help or advise as to a workaround.

Background:
- I have recently upgraded a solution from 7.12.4 to 7.15.1.
- I have a number of custom Media types, all using the Image Cropper for the file upload.
- Images are stored in Azure Blob Storage.
- The images show on the front end.
- The images show in the media section and I can edit the crops.

The problem I am seeing since upgrading is that when I try to assign an image to some content, the Media Picker is treating the images as folders. Instead of a thumbnail, I am getting the "icon-picture" placeholder. This placeholder cannot be selected, instead clicking on it drills down, as if the item is a folder.

If I revert back to my previous 7.12.4 version, the image thumbnails return and are selectable.

**Comment by nul800sebastiaan** [comment]
Hmm, that is strange, I just gave this a spin on 7.15.1 and it works fine. However, I am not using the any Azure Blob Storage plugins, could it be that this is the issue, are you using version 1.0.3 of this one? https://our.umbraco.com/packages/collaboration/umbracofilesystemprovidersazure/

**Comment by JamesSherborne** [comment]
Hi @nul800sebastiaan. Yes we are using version 1.0.3 of UmbracoFileSystemProviders.Azure Its strange that only the Media Picker seems to have trouble. Displaying images on the front end and the in the Media section works fine. It looks like the media picker thinks the images are folders.

For now, we are having to roll back to 7.12.4 but I am conscious of the security vulnerability that 7.15.1 was designed to fix.

**Comment by nul800sebastiaan** [comment]
Make sure to use the workaround for the security issue for now! I'll see what I can find out about this problem.

**Comment by stevemegson** [comment]
Can you check whether the `mediaPath` column of the `cmsMedia` table is populated? I suspect that the Azure plugin stops that column being populated, leading to something like #5847. That would explain the missing thumbnails, though I don't think it should stop you selecting the images.

**Comment by JamesSherborne** [comment]
@stevemegson we have around 23,000 images and 17,000 do not have a media path. Could this be the cause?

**Comment by nul800sebastiaan** [comment]
I'm afraid I don't know how this is caused? Could it be an older version of the Azure FileSystem Provider that didn't set the media path correctly? I have done a full end-to-end test with a custom media type in v7.12.4, using the Azure FileSystem Provider, then upgrading to 7.15.1 and uploading a new image there. All works great. 

I think it's best to continue the conversation on #5847 then and see if we can figure out why this data is missing.

**Comment by andersbrohall** [comment]
Im having the same issue. 
But not with Azure Blob Storage plugins.

In my case i created a Media Type called Video. 
It contains all the properties from an out-of-the-box Image Media Type, with the addition of an Embed Video Url of the type String. 

However it does turn out that you can replicate it by having the Disable Folder Select = true on the Data Type. When that is set, you cannot select the Media Item at all (apart from Image). 100% wrong :( 

The other way around, having the Disable Folder Select = false you CAN select the Media Item by clicking the Icon - but NOT the label. Clicking the Label will browse you inte the 'folder', just like having the Disable Folder Select = true. 50% right :)


Ping @nul800sebastiaan  @JamesSherborne

**Comment by andersbrohall** [comment]
(Wrote in this issue, since the linked one doesn't describe the problem with selecting Non Image-Media Types, right or wrong?)

**Comment by nul800sebastiaan** [comment]
@andersbrohall is this the same issue as https://github.com/umbraco/Umbraco-CMS/issues/6441 ?

**Comment by andersbrohall** [comment]
> @andersbrohall is this the same issue as #6441 ?

Yes!
