### ISSUE TITLE
Permissions for users in multiple user groups are incorrect

### ISSUE THREAD

**Issue by aaronshelbySBA** [umbraco/Umbraco-CMS#6126]
It looks like users assigned to more than one user group are being assigned incorrect permissions. 

Assuming that you have a basic navigational structure of:
Home
-Menu1
--Menu1sub1
--Menu1sub2
-Menu2
--Menu2sub1
-Menu3

And user groups consisting of: 
a group named Menu2Group that has publish permissions for Menu2 (with Menu2 as its start node), 
and another Group (ReadOnlyGroup) that has read-only permissions for Home (with Home as its start node).

If I create a user and assign the user to both Menu2Group and ReadOnlyGroup, the user ends up with publish permissions for the Home node and all its descendants.

**Comment by stevemegson** [comment]
It looks like this happens when Menu2Group has default permissions, rather than permissions explicitly set on Menu2. Default permissions on a group are applied to any content that the user can see, not only to that group's start node and its descendants.

**Comment by aaronshelbySBA** [comment]
Yes, that does appear to be the case. I tried a few additional tests and came up with expected behavior when treating the granular permissions as the primary permission source (essentially ignoring default permissions). The prominent display of the default permissions, combined with the collapsed view of the granular permissions is counter intuitive. But at least I understand how it works now.

**Comment by nul800sebastiaan** [comment]
Good to hear it's working now, I'll close this one. :)
