### ISSUE TITLE
V8: Can't navigate to another node when the editor is in "create" state

### ISSUE THREAD

**Issue by kjac** [umbraco/Umbraco-CMS#6127]
If you start creating a new node and then want to open another node instead, you're kind of stuck in the editor "create" state; whatever other node you attempt to open simply won't open. Only the next node you click actually opens. This all sounds very convoluted so here's a GIF:

![navigation-issue-1](https://user-images.githubusercontent.com/7405322/63047470-cd680000-bed4-11e9-892c-03cb73362a29.gif)

To make matters slightly worse, if you try to get out of the "create" state by saving your work (after the first attempt to leave "create state"), you'll get a server error:

![navigation-issue-2](https://user-images.githubusercontent.com/7405322/63047570-030ce900-bed5-11e9-8487-3abfe268710f.gif)

If I'm not entirely mistaken, 88d9e332 is the cause of this issue. [This line](https://github.com/umbraco/Umbraco-CMS/blob/4ed746e4ef1d01174db393c363ca522db093351c/src/Umbraco.Web.UI.Client/src/common/services/navigation.service.js#L144) is the culprit.

**Comment by nul800sebastiaan** [comment]
We'll have a chat about this at HQ, interesting/strange issue 🙈

**Comment by Shazwazza** [comment]
There's certainly something odd going on, it's a regression issue because this issue doesn't exist in v7 and not sure when the issue started in v8. Also, it's not always 'stuck', if you start clicking on other child nodes, it will route and the ?create query string is cleared. 

I'll see what i can find.
