### ISSUE TITLE
Existing Views Are Overwritten When Creating a New Template

### ISSUE THREAD

**Issue by 0Neji** [umbraco/Umbraco-CMS#6135]
Linked to #3494

This issue was closed at the time and haven't been able to re-open so just raising the issue again here (and have updated for Umbraco 8).

### Bug summary

When creating a new template via code, if a view exists with the same name, it is overwritten. I believe there should be a check in place that if the view exists, it's left alone but the template is added to the database regardless. If the file doesn't exist, only then should it create a new, blank one.

### Specifics

Umbraco version: 8.1.2

### Steps to reproduce

Create a new view in ~\Views called Test.cshtml (*not through the CMS*). Enter some content, for example:

```
@{
    Layout = null;
}

<h2>Homepage</h2>
```

Create a component that creates a new template:

```
using Umbraco.Core;
using Umbraco.Core.Composing;
using Umbraco.Core.Models;
using Umbraco.Core.Services;

namespace UmbracoTemplateTest.Components
{
    [RuntimeLevel(MinLevel = RuntimeLevel.Run)]
    public class ContentTypeComposer : IUserComposer
    {
        public void Compose(Composition composition)
        {
            composition.Components().Append<ContentTypeComponent>();
        }
    }

    public class ContentTypeComponent : IComponent
    {
        private readonly IFileService _fileService;

        public ContentTypeComponent(IFileService fileService)
        {
            _fileService = fileService;
        }

        public void Initialize()
        {
            ITemplate template = _fileService.GetTemplate("test");

            if (template == null)
            {
                template = new Template("Test", "test");

                _fileService.SaveTemplate(template);
            }
        }

        public void Terminate() { }
    }
}
```

See that Test.cshtml has been overwritten by a basic Umbraco template view:

```
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage

@{
    Layout = null;
}
```

### Expected result

When the template is saved, existing views with the same name aren't overwritten.

### Actual result

A blank/basic view is written into the contents of the view in the place of already existing content.

This was fixed when creating the template through the CMS but, if you create the file then create a template using code, the file is overwritten.

Thanks,

Ben

**Comment by nul800sebastiaan** [comment]
You're doing an explicit `_fileService.SaveTemplate(template);` though, there's really no way we could tell that this is not intentional.. Don't you think it would be weird if that method just did nothing?

We're explicitly setting the template content because you asked for it: 

https://github.com/umbraco/Umbraco-CMS/blob/853087a75044b814df458457dc9a1f778cc89749/src/Umbraco.Core/Persistence/Repositories/Implement/TemplateRepository.cs#L253

Maybe I just don't understand what the purpose is of creating the file on disk before creating it in the CMS? 

Maybe you need to be aware of this in your code instead, where you check if the file exist and load it's content and decide if you want to use that or the default content.

**Comment by 0Neji** [comment]
Hi @nul800sebastiaan,

I have a package (to be hosted by both NuGet and the package repository) that creates content types and templates through code. The package comes with some views so they are always on disk by the point Umbraco is installed. During start up, `SaveTemplate` is called because it then needs adding to the database (so it's available to set as a template in the content types created further down the line). The only way I've found to do this is through this file service method.

So actually what I'm trying to do is *only* add it to the database, but to do so, I have to (as far as I can tell) call this method. Is there a method I've missed that allows me to only save to the database?

I don't think it would be that weird if the method didn't do anything based on, "is this file already here?" because if it is, why would you overwrite the file contents with a basic template that does almost nothing? I believe this is how it works when creating a new template from the CMS so even from a consistency point of view, I'm not sure that makes sense. As above though, I could quite simply have missed a more appropriate method for doing this!

Thanks for the quick response!

Thanks,

Ben

**Comment by jaddie** [comment]
It would be odd for the method to indeed do nothing in its current state, however there should be either a result returned with nothing done but showing the reason being the file exists already, after which you could then call the method and over-write it.

Alternatively the method to save could have arguments which allow for more control such as switching the database saving aspect on & off, and another for the saving of the file, and finally another for setting an overwrite flag etc.

To destroy content in files at any point is not good behaviour at all, unless there is another method which allows for adding the template entry to the database only without creating the file in which case I could partially understand the expectation of the person using the code to check for the file contents etc.

**Comment by nul800sebastiaan** [comment]
I am not sure if the FileService should be responsible for that, but I can ask around.

For convenience it would be nice, but for now you could load the file contents yourself;

```csharp
            var templateAlias = "test";
            ITemplate template = _fileService.GetTemplate(templateAlias);

            if (template == null)
            {
                template = new Template("Test", templateAlias);
                var existingFilePath = HostingEnvironment.MapPath($"~/Views/{templateAlias}.cshtml");
                if (System.IO.File.Exists(existingFilePath))
                {
                    var existingFile = System.IO.File.ReadAllText(existingFilePath);
                    template.Content = existingFile;
                }
                
                _fileService.SaveTemplate(template);
            }
```

**Comment by Shazwazza** [comment]
This has been fixed at various levels a few times but I guess for just specific circumstance, for example, in the implementation of `IFileService`, in the methods: `CreateTemplateForContentType`, `CreateTemplateWithIdentity` any existing view will *not* be overwritten with checks to `GetViewContent`. 

You can utilize the `CreateTemplateWithIdentity` instead of doing

```cs
 template = new Template("Test", "test");
_fileService.SaveTemplate(template);
```

and that should solve your problem.
