### ISSUE TITLE
Notify the editor if an unpublished node is picked in a content picker

### ISSUE THREAD

**Issue by hartviglarsen** [umbraco/Umbraco-CMS#6143]
Currently an editor will see a message at a node's content picker if the picked node is unavailable (deleted/recycle bin) - which is sweet!

However, there's no feedback if the node has been unpublished. That means editor A can open node X and think that everything is OK, even though editor B has unpublished node Y, which is picked on node X.

![contentpicker](https://user-images.githubusercontent.com/4366314/63245397-6c3b8600-c260-11e9-824f-da203deff8e0.png)

Providing a warning message when a picked node is unpublished would be awesome. :-)

**Comment by nul800sebastiaan** [comment]
Fixed in https://github.com/umbraco/Umbraco-CMS/pull/6151
