### ISSUE TITLE
Multi url picker doesn't return culture variant url

### ISSUE THREAD

**Issue by deMD** [umbraco/Umbraco-CMS#6145]
When picking a content url in the multi url picker in a multi language website, the default language url is returned and saved instead of the culture variant url:
![image](https://user-images.githubusercontent.com/22070292/63262157-83d93580-c285-11e9-8ecb-54b028779e96.png)

This might be fixed in #6100 

If so, is there a possibility that that issue gets released as soon as possible (possibly 8.1.3 instead of 8.1.4) as this is a pretty nasty bug causing problems on a live environment for us currently.

**Comment by nul800sebastiaan** [comment]
The fix in #6100 is merged into 8.1.4 and will be released in the next few weeks.
