### ISSUE TITLE
Migration from v7.15.1 to 8.1.2 causes error ERROR: The database configuration failed with the following message: Value cannot be null.  Parameter name: text

### ISSUE THREAD

**Issue by vishalno** [umbraco/Umbraco-CMS#6146]
I am trying to migrate from v7 to v8 and i get an issue and i am unable to resolve.

Initially i had issues with unique indexes, and also with obsolete mediapicker and memberpicker. But this issue i am not having any clues what can be wrong.

Error during installation
The database failed to upgrade. ERROR: The database configuration failed with the following message: Value cannot be null.
 Parameter name: text Please check log file for additional information (can be found in '/App_Data/Logs/')

See the log for full details (logs can typically be found in the App_Data\Logs folder).

Stack trace:
{
  "@t": "2019-08-19T12:04:43.6338659Z",
  "@mt": "An error occurred during installation step {Step}",
  "@l": "Error",
  "@x": "System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> Umbraco.Web.Install.InstallException: The database failed to upgrade. ERROR: The database configuration failed with the following message: Value cannot be null.\r\nParameter name: text\n Please check log file for additional information (can be found in '/App_Data/Logs/')\r\n   at Umbraco.Web.Install.InstallSteps.DatabaseUpgradeStep.ExecuteAsync(Object model)\r\n   --- End of inner exception stack trace ---\r\n   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)\r\n   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)\r\n   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)\r\n   at Umbraco.Web.Install.Controllers.InstallApiController.<ExecuteStepAsync>d__14.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Umbraco.Web.Install.Controllers.InstallApiController.<PostPerformInstall>d__11.MoveNext()",
  "Step": "DatabaseUpgrade",
  "SourceContext": "Umbraco.Web.Install.Controllers.InstallApiController",
  "ProcessId": 15960,
  "ProcessName": "w3wp",
  "ThreadId": 13,
  "AppDomainId": 2,
  "AppDomainAppId": "LMW3SVC3ROOT",
  "MachineName": "LAPTOP-68N355PI",
  "Log4NetLevel": "ERROR",
  "HttpRequestNumber": 3,
  "HttpRequestId": "90d721cd-b596-421f-8664-c7d018dd7f71"
}

Any hint what may be causing this issue?

**Comment by nul800sebastiaan** [comment]
Hmm, It's really not possible to see anything from this log file, are you running with `debug="true"` in your web.config? Do you have more log messages near this one that have more info in them maybe.

Please always add the Umbraco version that you're using.

**Comment by vishalno** [comment]
Thanks for the prompt reply. Site was initially running 7.12.4 which i upgraded to 7.15.1. Now running the migration to 8.1.2

I have now set debug true. 

{"@t":"2019-08-19T12:46:25.6733394Z","@mt":"SQL [{ContextIndex}]: {Sql}","ContextIndex":1533,"Sql":"ALTER TABLE [cmsContentNu] ADD CONSTRAINT [FK_cmsContentNu_umbracoContent_nodeId] FOREIGN KEY ([nodeId]) REFERENCES [umbracoContent] ([nodeId]) ON DELETE CASCADE","SourceContext":"Umbraco.Core.Migrations.Expressions.Execute.Expressions.ExecuteSqlStatementExpression","ProcessId":18304,"ProcessName":"w3wp","ThreadId":6,"AppDomainId":2,"AppDomainAppId":"LMW3SVC3ROOT","MachineName":"LAPTOP-68N355PI","Log4NetLevel":"INFO ","HttpRequestNumber":2,"HttpRequestId":"8f975614-2dfb-4581-b00e-72701273fdcb"}

{"@t":"2019-08-19T12:46:25.9833141Z","@mt":"At {OrigState}","OrigState":"{5B1E0D93-F5A3-449B-84BA-65366B84E2D4}","SourceContext":"Umbraco.Core.Migrations.MigrationPlan","ProcessId":18304,"ProcessName":"w3wp","ThreadId":6,"AppDomainId":2,"AppDomainAppId":"LMW3SVC3ROOT","MachineName":"LAPTOP-68N355PI","Log4NetLevel":"INFO ","HttpRequestNumber":2,"HttpRequestId":"8f975614-2dfb-4581-b00e-72701273fdcb"}
{"@t":"2019-08-19T12:46:25.9843433Z","@mt":"PostMigration: Umbraco.Web.Migrations.PostMigrations.ClearCsrfCookies.","SourceContext":"Umbraco.Core.Migrations.MigrationPlan","ProcessId":18304,"ProcessName":"w3wp","ThreadId":6,"AppDomainId":2,"AppDomainAppId":"LMW3SVC3ROOT","MachineName":"LAPTOP-68N355PI","Log4NetLevel":"INFO ","HttpRequestNumber":2,"HttpRequestId":"8f975614-2dfb-4581-b00e-72701273fdcb"}

{"@t":"2019-08-19T12:46:25.9903280Z","@mt":"PostMigration: Umbraco.Core.Migrations.PostMigrations.RebuildPublishedSnapshot.","SourceContext":"Umbraco.Core.Migrations.MigrationPlan","ProcessId":18304,"ProcessName":"w3wp","ThreadId":6,"AppDomainId":2,"AppDomainAppId":"LMW3SVC3ROOT","MachineName":"LAPTOP-68N355PI","Log4NetLevel":"INFO ","HttpRequestNumber":2,"HttpRequestId":"8f975614-2dfb-4581-b00e-72701273fdcb"}

{"@t":"2019-08-19T12:46:40.0903302Z","@mt":"Database configuration failed","@l":"Error","@x":"Umbraco.Core.Exceptions.ArgumentNullOrEmptyException: Value cannot be null.\r\nParameter name: text\r\n   at Umbraco.Core.StringExtensions.ToUrlSegment(String text, String culture)\r\n   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()\r\n   at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)\r\n   at Umbraco.Core.Strings.ContentBaseExtensions.GetUrlSegment(IContentBase content, IEnumerable`1 urlSegmentProviders, String culture)\r\n   at Umbraco.Web.PublishedCache.NuCache.PublishedSnapshotService.GetDto(IContentBase content, Boolean published)\r\n   at System.Linq.Enumerable.WhereSelectArrayIterator`2.MoveNext()\r\n   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)\r\n   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)\r\n   at Umbraco.Web.PublishedCache.NuCache.PublishedSnapshotService.RebuildMemberDbCacheLocked(IScope scope, Int32 groupSize, IEnumerable`1 contentTypeIds)\r\n   at Umbraco.Web.PublishedCache.NuCache.PublishedSnapshotService.Rebuild()\r\n   at Umbraco.Web.Migrations.PostMigrations.PublishedSnapshotRebuilder.Rebuild()\r\n   at Umbraco.Core.Migrations.MigrationPlan.Execute(IScope scope, String fromState, IMigrationBuilder migrationBuilder, ILogger logger)\r\n   at Umbraco.Core.Migrations.Upgrade.Upgrader.Execute(IScopeProvider scopeProvider, IMigrationBuilder migrationBuilder, IKeyValueService keyValueService, ILogger logger)\r\n   at Umbraco.Core.Migrations.Install.DatabaseBuilder.UpgradeSchemaAndData(MigrationPlan plan)","SourceContext":"Umbraco.Core.Migrations.Install.DatabaseBuilder","ProcessId":18304,"ProcessName":"w3wp","ThreadId":6,"AppDomainId":2,"AppDomainAppId":"LMW3SVC3ROOT","MachineName":"LAPTOP-68N355PI","Log4NetLevel":"ERROR","HttpRequestNumber":2,"HttpRequestId":"8f975614-2dfb-4581-b00e-72701273fdcb"}

{"@t":"2019-08-19T12:46:40.0953114Z","@mt":"The database schema validation produced the following summary: {DbSchemaSummary}","DbSchemaSummary":"The following tables were found in the database, but are not in the current ...

**Comment by nul800sebastiaan** [comment]
Alright, it looks like this is happening for members (`RebuildMemberDbCacheLocked`) is it possible that one or more of your members does not have a node name for some reason? 

If you can query the database for: `SELECT * FROM umbracoNode WHERE nodeObjectType = '39eb0f98-b348-42a1-8662-e7eb18487560' AND (text IS NULL OR text = '')` does this give you any results?

**Comment by vishalno** [comment]
Yups i get 1 record and i also checked an old hosted site and can see the member without a name. I will update the text and try again.

Also one weird thing i see is that some members have same usernames, that may cause some issue i guess.

**Comment by nul800sebastiaan** [comment]
Yep that could cause some trouble too, but maybe not in migrating the members.. not sure! 

Anyway, good that we've identified the bug now!

**Comment by vishalno** [comment]
The migration works. I will now work with the template changes. Thanks @nul800sebastiaan for your help on this.
