### ISSUE TITLE
NestedContent - Missing data-attribute on property editors.

### ISSUE THREAD

**Issue by bgunnarsson** [umbraco/Umbraco-CMS#6148]
### Bug summary
***
If someone has a better idea for a fix then I'm all ears.
***

NestedContent items are missing a data-attribute (data-element) which is added by default when not using NestedContent.

This is stopping a package I'm using from working properly when I'm using it with NestedContent since it relies on that data-attribute.

### Specifics
Currently using version 7.15.1 - I'm fairly certain that it's like this ever since NestedContent was incorporated into the core.

### Steps to reproduce
Create a NestedContent setup, create a property editor and inspect it. Create a normal tab, add a property editor and inspect it. Compare them (attached image)

### Expected result
data-element="property-alias"

### Actual result
Nothing.

![nc-missing-attributes](https://user-images.githubusercontent.com/2563119/63271457-b6852d00-c289-11e9-8385-b89819b592b9.jpg)

**Comment by bgunnarsson** [comment]
I'm currently working on a fix for this.

**Comment by bgunnarsson** [comment]
[Pull Request #6150](https://github.com/umbraco/Umbraco-CMS/pull/6150)

**Comment by bgunnarsson** [comment]
Currently adding this to v8 as well.

**Comment by nul800sebastiaan** [comment]
Cherry picked for 7.15.3 d2649e935489bb0a6a0395323c3254082f786c25
Cherry picked for 8.1.4 88145d70fc1cd919cebd0245ecc8ed0b0e1d967f
