### ISSUE TITLE
Added logic for copying data types

### ISSUE THREAD

**Issue by jamiepollock** [umbraco/Umbraco-CMS#6159]
Adding the underlying business logic for copying a data type in Umbraco v8.

This would only include the business logic. If this feature is accepted I will then I'll add the tree actions in a separate PR.

How can you help?
-------------------------------

I'll be submitting a PR within the next week for this feature.

**Comment by jamiepollock** [comment]
Updated the title to make it clear at a glance this a v8 PR.

**Comment by nul800sebastiaan** [comment]
Thanks for the feature request. What is the use case for this please? Who will it benefit and how?

**Comment by jamiepollock** [comment]
Hi Sebastiaan,
Thanks for the quick response to clarify the need for this feature request.

In my mind, copying a data type would have been a useful feature to have in v7 and assumedly in v8 too. It would be most useful to developers who are creating data types that are similar but need minor configuration changes between variants.

The types of data type that come to mind are;

 - RTE
 - Nested Content

These data types have a lot of configuration which can take a while to setup and when the copy only needs a couple of configuration changes this would be a real time saver.

**Comment by nul800sebastiaan** [comment]
Hi Jamie! We had a bit of a discussion about this at HQ and we believe it is an interesting feature but not something many people are going to use. We believe that we should keep making Umbraco as a simple tool where the options are limited so as not to confuse people. 

Surely, it is a bit of work setting up a new datatype with a new configuration but we don't believe it deserves an extra option to save that 30 seconds of extra clicking you would need to do. 

It might make for a good package though, you are able to add extra items to the tree from a package, so if you think this is going to make you a lot more productive then it might be a good idea to look into that.

**Comment by jamiepollock** [comment]
Hey Sebastiaan,
Thank you for getting back to me. I of course respect the discussion you’ve had at HQ.

I Initially reached out as I thought such a feature would require modifications to the core to achieve this. I’ll look into possibly adding it in as a package.

Either way I guess we’re clear to close this issue as it won’t be something we’re introducing to the core at this time.

Thanks again for discussing this,
Jamie

**Comment by mcsagittarius** [comment]
> 
> 
> Hi Jamie! We had a bit of a discussion about this at HQ and we believe it is an interesting feature but not something many people are going to use. We believe that we should keep making Umbraco as a simple tool where the options are limited so as not to confuse people.
> 
> Surely, it is a bit of work setting up a new datatype with a new configuration but we don't believe it deserves an extra option to save that 30 seconds of extra clicking you would need to do.
> 
> It might make for a good package though, you are able to add extra items to the tree from a package, so if you think this is going to make you a lot more productive then it might be a good idea to look into that.

Uhh... except some data types take a very long time to set up. Doing a block list with thumbnails and then having to do a slightly different version for a new page type is really painful. It just seems like such a simple thing to be able to do. You can copy document types... why not data types?

**Comment by bjarnef** [comment]
@jamiepollock I noticed you submitted this PR https://github.com/umbraco/Umbraco-CMS/pull/1696 a long time ago.

I noticed in Umbraco 8.14 we still don't have a feature to copy datatypes.
With datatype having more complex configuration like Grid editor, Block list editor and maybe third party packages like Contentment, it would be really useful to make a copy of the datatype with same configuration and just tweak the configuration in the copied datatype instance.

**Comment by skartknet** [comment]
I guess there hasn't been any progress on this? I agree that some datatypes take a long time to configure. Way more than 30 seconds ;)

**Comment by bjarnef** [comment]
@skartknet it has been implemented since Umbraco v10.3.0 😉
https://github.com/umbraco/Umbraco-CMS/pull/11867

**Comment by skartknet** [comment]
Ah cool! I didn't realise. thanks!
