### ISSUE TITLE
Nested content copy choice label is just one letter

### ISSUE THREAD

**Issue by runegronkjaer** [umbraco/Umbraco-CMS#6162]
When copying and then inserting content in the nested content data type, the label with the content name is just one letter and some dots. E.g. "C...". See screenshot from Chrome.

Umbraco v 8.1.3

Reproduction
------------
1. Make a nested content data type and add it to a documenttype
2. Create some content
3. Copy the content
4. Click "Add Content" again and see how the content is named

### Expected result
The label should be a text describing the item I have copied

### Actual result
The label shows one letter and some dots. See screenshot
![2019-08-21 10_01_05-Window](https://user-images.githubusercontent.com/3272628/63413779-b35d7e80-c3fa-11e9-986b-9696f21951ba.png)

---
_This item has been added to our backlog [AB#2347](https://umbraco.visualstudio.com/243e7927-03b2-44e2-908f-d4ac7ea5daaa/_workitems/edit/2347)_

**Comment by nul800sebastiaan** [comment]
That seems to be a problem in your particular site, I can't reproduce this problem in a fresh 8.1.3 install.

Let us know if when you have more info to reproduce!

![image](https://user-images.githubusercontent.com/304656/63416813-6f6d7800-c400-11e9-81d7-31db4b3b7429.png)

**Comment by runegronkjaer** [comment]
Are you sure? Your screenshot is not of the copy feature.
This is where the issue is:
![copy label](https://user-images.githubusercontent.com/3272628/63418066-c1170200-c402-11e9-8939-9fd50ea933ad.png)

**Comment by nul800sebastiaan** [comment]
My screenshot was supposed to be an animated gif, oops!

![6162](https://user-images.githubusercontent.com/304656/63418173-eefc4680-c402-11e9-98c2-32658ee0fdb3.gif)

**Comment by runegronkjaer** [comment]
Ok. I have got news on this. After many tests I have found out that the problem disappears if I delete the "UmbracoForms" folder in \App_Plugins. So I guess I'll have to move the issue to Umbraco Forms instead? It's most likely overwriting a truncate filter or something like that.

**Comment by nul800sebastiaan** [comment]
Yikes!

**Comment by nul800sebastiaan** [comment]
No, no need to move it.. this just means that we need to anticipate other people doing things that might affect core as well.. Great find! Really unfortunate.. we'll have to have a look how to avoid this problem.

**Comment by nielslyngsoe** [comment]
PR: https://github.com/umbraco/Umbraco-CMS/pull/6338
