### ISSUE TITLE
Login using Azure AD redirects always to my login page

### ISSUE THREAD

**Issue by abellisai** [umbraco/Umbraco-CMS#6163]
I'm working on a project that use Azure AD for login the Users and Members using Umbraco Identity Extension.

Some times when i try to login an User on Azure AD i'll always redirect to umbraco login page.

Reproduction
------------

### Bug summary

Some times when I try to login an User on Azure AD i'll always redirect to umbraco login page.

### Specifics

I've replicate this problem on Umbraco 7.13.2

### Steps to reproduce

1) Open one tab of Chrome to frontend umbraco application 
2) Login in the member with Azure AD
3) Open one tab of Chrome to backend umbraco application (../umbraco)
4) Login in the User with Azure AD
5) Logout member
6) Logout user
7) Press F12 on the first tab of Chrome (frontend website)
8) On Application Tab clear all Cookies
9) Press F12 on the second tab of Chrome (umbraco)
10) On Application Tab clear all Cookies
11) On second tab try to login on Umbraco with Azure AD, and the you will redirect forever to umbraco page

Solution
------------
This post on Stakoverflow (https://stackoverflow.com/questions/20180562/mvc5-null-reference-with-facebook-login/20948631#20948631) inspire me the following solution:

Modify the `BackOfficeController.cs` of `Umbraco .Web` solution adding `ControllerContext.HttpContext.Session.RemoveAll()` on `ExternalLogin` and `LinkLogin `action

Following the code of ExternalLogin Action modified:

```
[HttpPost]
public ActionResult ExternalLogin(string provider, string redirectUrl = null)
{
    if (redirectUrl == null)
    {
        redirectUrl = Url.Action("Default", "BackOffice");
    }

    ControllerContext.HttpContext.Session.RemoveAll();

    // Request a redirect to the external login provider
    return new ChallengeResult(provider, redirectUrl);
}
```
Following the code of LinkLogin Action modified:

```
    [UmbracoAuthorize]
    [HttpPost]
    public ActionResult LinkLogin(string provider)
    {
        ControllerContext.HttpContext.Session.RemoveAll();

        // Request a redirect to the external login provider to link a login for the current user
        return new ChallengeResult(provider,
            Url.Action("ExternalLinkLoginCallback", "BackOffice"),
            User.Identity.GetUserId());
    }
```
Hoping ths help.

**Comment by nul800sebastiaan** [comment]
I am not sure if removing all sessions is a good idea, doesn't that also mean you can no longer work in the backoffice and on the frontend at the same time, since you can only be logged in in *one* of those environments?

**Comment by abellisai** [comment]
Hi Sebastian
In this hours i'm trying this solution, and I'm able to use the same AZ AD account both as a member and as a user, at the same time without side effect.

The wired thing is that without removing all session on `ExternalLogin` action, then on `RenderDefaultOrProcessExternalLoginAsync` method, the `loginInfo` variable returned by the invocation of `await OwinContext.Authentication.GetExternalLoginInfoAsync(   Constants.Security.BackOfficeExternalAuthenticationType)
`
always return null.

**Comment by nul800sebastiaan** [comment]
Thanks @abellisai - I honestly have no idea if this is intended behavior or if we want to fix this behavior. Currently the person able to answer this the best is on holiday, so please know that it will take a while before we have a further update for you on this.

**Comment by abellisai** [comment]
Hi Sebastiaan
No problem for the timing and the luky guy on holyday, good for him ;-)

I would like to add a note that could be helpful for digging in to the problem (maybe OWIN bug???):

The strange behavior (without removing all  session) persist also if session contains no variable at all.
It's start to work if i add the removeAll session code also in a session with no keys.

Thanks to you!
HFYR

**Comment by Shazwazza** [comment]
@abellisai Off the top of my head, perhaps you are seeing this issue: https://github.com/umbraco/UmbracoIdentityExtensions/issues/20, for the solution, see here and below https://github.com/umbraco/UmbracoIdentityExtensions/issues/20#issuecomment-460999371

You should definitely not need to be mucking around with sessions or anything like that. 

There are several people using both IdentityExtensions (for back office AAD login) and UmbracoIdentity (for front-end AAD login) without issue, though everyone seems to encounter new/strange issues. 

I'd suggest trying that solution first to see if that gets you any further.

Can you also confirm that you are using both IdentityExtensions and UmbracoIdentity to perform your AAD login on back office and front-end ?

**Comment by abellisai** [comment]
Hi Shannon

Thanks a lot for you suggestion, i'll try it and i let you know.

I confirm you that i use IdentityExtensions and UmbracoIdentity  to login on AAD for Backend and front end.

**Comment by abellisai** [comment]
@Shazwazza thanks for the suggestion, https://github.com/umbraco/UmbracoIdentityExtensions/issues/20#issuecomment-460999371
It works great!

Thanks again

**Comment by Shazwazza** [comment]
great to hear! Seems like it will be worth adding this to some official docs on integrating Azure AD
