### ISSUE TITLE
Nested content copy/paste problem when having a nested content in a nested content

### ISSUE THREAD

**Issue by runegronkjaer** [umbraco/Umbraco-CMS#6165]
When having a nested content datatype on on some content that can be created in another nested content something is not being updated on the inner nested content.

Reproduction
------------
### Bug summary
The problem is that the new copy of the content keeps the same id's as the one that has been copied. This results in changes on the copied version not being applied.
I specifically have a nested content i which I can create columns. In each column there's a nested content which allows us to create a number of content. 
An example is a column and in that column we create an image content which makes it possible to select an image from the media archive and a link. When copying one of these and then changing the image and the link on the copy, the frontend will not display the changes. In the frontend the copy will have the same link and image as the original.
Furthermore, if you change the image on the original the image in the frontend will then change on both the original and the copy, displaying the originals new image.

Sounds like a caching issue combined with the copied nested contents, nested content not getting new id's.

### Specifics
Umbraco v8.1.3 with standard starter kit
Newest Chrome browser

### Steps to reproduce
1. Create two nested content data types. One "Inner" with a doc type with an image property. The other, "Outer", with a doc type with the "Inner" nested content
2. Add the Outer nested content to a page doc type
3. Loop the two nested contents in the template, one within the other and write the url of the image
4. Now create content and create an Outer with an Inner and select an image
5. Copy the Outer and instert it again
6. Change the image of the copy
7. Now both image url's are the same in the looped markup
8. Change the first Outer's image
9. Now both image url's change to the first Outers new image

### Expected result
Copying a nested content should result in new unique content, that can be changed afterwards.

### Actual result
The copy will retain the id's in the Inner nested content. That must mean the cache will only store the first IPublishedElement with that "unique" id and not be able to get the other. When the frontend loads the copy, in reality it will load the original.

Screenshots of the steps:
####Step 1
![Step 1](https://user-images.githubusercontent.com/3272628/63430455-e6b10500-c41c-11e9-9d53-60da197d8876.png)
####Step 1 - Frontend
![Step 1 - Frontend](https://user-images.githubusercontent.com/3272628/63430460-e9abf580-c41c-11e9-9d46-bc0150a4e1ac.png)
####Step 2
![Step 2](https://user-images.githubusercontent.com/3272628/63430466-edd81300-c41c-11e9-9bd1-34bdde6e9608.png)
####Step 2 - Frontend
![Step 2 - Frontend](https://user-images.githubusercontent.com/3272628/63430467-edd81300-c41c-11e9-8aac-9229d3448728.png)
####Step 3
![Step 3](https://user-images.githubusercontent.com/3272628/63430468-ee70a980-c41c-11e9-989f-b609bb13d3a4.png)
####Step 3 - Frontend
![Step 3 - Frontend](https://user-images.githubusercontent.com/3272628/63430469-ee70a980-c41c-11e9-980c-cac715f2ebed.png)
####Step 4
![Step 4](https://user-images.githubusercontent.com/3272628/63430470-ee70a980-c41c-11e9-8e3b-d03f8913bcc9.png)
####Step 4 - Frontend
![Step 4 - Frontend](https://user-images.githubusercontent.com/3272628/63430471-ef094000-c41c-11e9-8fe7-e7fdbc91c60c.png)

**Comment by nul800sebastiaan** [comment]
Thanks for the extensive report! This has been reported before and we'll look at a PR for this soon: https://github.com/umbraco/Umbraco-CMS/issues/5913
