### ISSUE TITLE
📮 Set defaults for "create new package"

### ISSUE THREAD

**Issue by skttl** [umbraco/Umbraco-CMS#6166]
When creating packages from the backoffice (I often do that, to export different schema data from one install to another), you have to type in a few fields.

I would love for these (especially the mandatory ones) to be prefilled, so all I had to do, was to input a name and the contents.

Could we extend umbracoSettings.config, with some keys for this?
Like

```
  <packages>
    <name>My Default Package Name</name> <!-- defaults to '' -->
    <url>https://skttl.dk</url> <!-- defaults to '' -->
    <version>1.0.0</version> <!-- defaults to '1.0.0' -->
    <umbracoVersion>8.1.1</umbracoVersion> <!-- defaults to current Umbraco version -->
    <author>Søren Kottal</author> <!-- defaults to '' -->
    <authorUrl>https://skttl.dk</authorUrl> <!-- defaults to '' -->
    <contributors>  <!-- empty by default -->
      <contributor>Name of contributor</contributor>
      <contributor>Name of other contributor</contributor>
    </contributors>
    <license>MIT License</license> <!-- defaults to 'MIT License' -->
    <licenseUrl>http://opensource.org/licenses/MIT</licenseUrl> <!-- defaults to 'http://opensource.org/licenses/MIT' -->
    <readme><![CDATA[The readme]]></readme><!-- defaults to '' -->
    <icon></icon><!-- defaults to '' -->
  </packages>
```

**Comment by nul800sebastiaan** [comment]
We don't want to add any more configuration than what is strictly necessary, so I would say we're almost definitely not going to create more config keys for this scenario.

Also, please remember you are a (wonderful) outlier here, not many people make packages very often. I understand the pain in having to fill in all the details every time though and we should look into making this easier somehow. There's plenty of fields that are a "dumb" textbox at the moment that could be smarter, like a version picker for the versions, the Author could maybe use the logged in user's name, the licence could be pre-filled to be MIT and we could have an icon picker for icons.

We should also make it more clear that the Umbraco Version is the minimum version on which the package will work, currently that's not very clear.

Anyway, I'll put it in our HQ chat and will get back to you.

**Comment by skttl** [comment]
I could hack it in too - just thought it would be useful :)

The required fields are (IIRC) package url, package version (pre-filled at 1.0.0), author name and author url.

I would be equally happy, if the url fields got the current site url, and author name got the current user.

I only wan't to not have to fill out a lot of fields :)

**Comment by nul800sebastiaan** [comment]
I just realized.. you can get exactly what you want already! Just update createdPackages.config with your defaults and you're good to go, reload created packages in the backoffice after you do that and edit the parts that need updating!

I'll close this issue! :-)

**Comment by skttl** [comment]
Awesome - but there is no createdPackages.config in a blank site, it doesn't show up until you create a package, and then it contains the package you created.

How do you do it?
