### ISSUE TITLE
umb8.1.2 ContentService unable to retrieve the enumeration of an umbraco.tags datatype property

### ISSUE THREAD

**Issue by mistyn8** [umbraco/Umbraco-CMS#6168]
_Umbraco 8.1.2, dataType Umbraco.Tags (Json storage)_

Using the content service, I don't seem to be able to get tags other than as a plain string.
I can use the extension methods AssignTags() and RemoveTags()  but there doesn't seem to be a way to get the enumeration?

Reproduction
------------
```
var cs = Services.ContentService;
IContent node = cs.GetById(1179);
node.GetValue("tileTopics"); //returns plain string "[\"hi\",\"and\",\"me\"]"
node.GetValue<string>("tileTopics"); // returns plain string "[\"hi\",\"and\",\"me\"]"
node.GetValue<string[]>("tileTopics"); //return null
node.GetValue<IEnumerable<string>>("tileTopics"); //returns null
```

I did see in the source code some references to a GetTagsValue() but these are private/internal methods so not accessible?
[src/Umbraco.Core/Models/PropertyTagsExtensions.cs](https://github.com/umbraco/Umbraco-CMS/blob/853087a75044b814df458457dc9a1f778cc89749/src/Umbraco.Core/Models/ContentTagsExtensions.cs)

and these are referenced in the tags tests
[src/Umbraco.Tests/Services/ContentServiceTagsTests.cs](https://github.com/umbraco/Umbraco-CMS/blob/9c06ef83e217affbce51c1d6682f10914be2b400/src/Umbraco.Tests/Services/ContentServiceTagsTests.cs) 
`var enTags = content1.Properties["tags"].GetTagsValue().ToArray();`

So not sure if this is a property value converter issue, or that getTagsValue() should be public?

Any advice appreciated.

**Comment by nul800sebastiaan** [comment]
I hope you have a really good reason for not using the cached version of these values, you really only want to use the contentservice is you must manipulate the data. As such, we don't provide convenient conversions.

```
var tags = node.GetValue<string>("tileTopics");
var tagsList = JsonConvert.DeserializeObject<List<string>>(tags);
```

Make sure to discuss in the forum if you need more help with this! 👍

**Comment by mistyn8** [comment]
Thanks for the response, so this is in the back office for a daily import of content, where another property is reliant on the existence of a specific tag. 
So are you saying that any custom property will be returned as a string, no matter the underlying datatype, and that node.GetValue<TYPE> has no use? When using the contentService?

**Comment by nul800sebastiaan** [comment]
> So are you saying that any custom property will be returned as a string, no matter the underlying datatype, and that node.GetValue has no use? When using the contentService?

Honestly, I have no idea, there might be converters for things. But.. it's not something we encourage to use. If at all possible, I would recommend you look at the published content for tags, that will be cached and avoid all the database overhead.

**Comment by mistyn8** [comment]
But some of the content we are importing and consolidating may not be published?

**Comment by nul800sebastiaan** [comment]
>  If at all possible,

So not at all possible :-)

I'll refer to the working code sample above!
