### ISSUE TITLE
v8 - Link Picker errors upon re-opening when only a Query String / Anchor is provided.

### ISSUE THREAD

**Issue by NikRimington** [umbraco/Umbraco-CMS#6172]
When only adding a Query String or Anchor value to the Multi-Url Picker, if you go back in to edit the value it will throw an exception and not load the editor. This only seems to occur if you've not saved the page you are editing, however saving it seems to allow the editor to work.

I've been unable to identify where the error is being thrown but it relates to the URL being empty.

Umbraco version: 8.1.2

**Comment by nul800sebastiaan** [comment]
Hmmm, pinging @kjac - he did fix this but I guess not when you haven't saved the page? I guess it can't find the anchor anywhere because the page does not exist, so we need to just ignore that we can't find it.. or something? 🤔

**Comment by kjac** [comment]
I have been pinged 😂 will dive into it.

**Comment by kjac** [comment]
Fixed in #6178

**Comment by nul800sebastiaan** [comment]
Cherry picked to 8.1.4 a2899b21b66b1bca9be193a03644596d6c94dc90
