### ISSUE TITLE
'allow items of type' in the multinode treepicker doesn't show media types when the 'node type' is set to media

### ISSUE THREAD

**Issue by ribsdigital** [umbraco/Umbraco-CMS#6173]
when setting the 'node type' of a new datatype based on the 'multinode treepicker' to 'media' the 'allow items of type' selection doesn't show media types.

Reproduction
------------
create a new data type with a property editor of 'multinode treepicker', select 'media' as the node type and click 'add'. the resulting list of content types are doctype based rather than media types.

![v8-mntp](https://user-images.githubusercontent.com/22835873/63506181-56f08100-c518-11e9-857c-1511d390cf82.png)

### Expected result
the content type selection be based on media types.

### Actual result
the content type selection is based on document types.

**Comment by nul800sebastiaan** [comment]
Thanks, this has been reported in https://github.com/umbraco/Umbraco-CMS/issues/5983 

Apparently, something was overlooked in all v8 versions where filtering by member and media types doesn't work.
