### ISSUE TITLE
Saving ContentType with Segment variation throws NotSupportedException

### ISSUE THREAD

**Issue by PerplexDaniel** [umbraco/Umbraco-CMS#6174]
### Bug summary
When saving a ContentType with Variations set to ContentVariation.Segment, a NotSupportException is thrown. This also happens for PropertyType Variations.

### Steps to reproduce
Execute the following code in the Starter Kit. 

```csharp
var services = global::Umbraco.Core.Composing.Current.Services;
// Or inject...
IContentService contentService = services.ContentService;
IContentTypeService contentTypeService = services.ContentTypeService;

using (var scope = _scopeProvider.CreateScope())
{
    // Homepage of Starter Kit
    IContent homepage = contentService.GetById(1104);

    IContentType contentType = contentTypeService.Get(homepage.ContentTypeId);

    // Set contentType as varied by segment
    contentType.Variations = ContentVariation.Segment;

    foreach (var propertyType in contentType.PropertyTypes)
    {
        // Set propertyType as varied by segment
        propertyType.Variations = ContentVariation.Segment;
    }

    // Throws NotSupportedException
    contentTypeService.Save(contentType);

    scope.Complete();
}
```
### Expected result
ContentType is saved successfully and the database column "variations" is updated correctly in the cmsContentType table. Similarly the "variations" columns of the relevant cmsPropertyType rows are updated.

### Actual result
A NotSupportException is thrown.

Note: setting the variations columns of cmsContentType and cmsPropertyType can be done manually with the following SQL statements:

```sql
-- Enable Segment variations for Home content type and heroHeader property in Starter Kit.

UPDATE cmsContentType
SET variations = 2
WHERE pk = 541

UPDATE cmsPropertyType
SET variations = 2
WHERE alias = 'heroHeader'
```

These exceptions originate from these source files:
* https://github.com/umbraco/Umbraco-CMS/blob/release/8.1.3/src/Umbraco.Core/Persistence/Repositories/Implement/ContentTypeRepositoryBase.cs#L767
* https://github.com/umbraco/Umbraco-CMS/blob/release/8.1.3/src/Umbraco.Core/Persistence/Repositories/Implement/ContentTypeRepositoryBase.cs#L684

**Comment by nul800sebastiaan** [comment]
That's a nice feature request! 🙂

**Comment by nul800sebastiaan** [comment]
This might serve as some inspiration, possibly: https://github.com/umbraco/Umbraco-CMS/issues/5148
