### ISSUE TITLE
Content properties are empty when current segment is null on segmented content type

### ISSUE THREAD

**Issue by PerplexDaniel** [umbraco/Umbraco-CMS#6180]
### Summary
When a content type is set to ContentVariation.Segment, property values of the IPublishedContent are all empty when the current segment is null. In this case it is possible to read segmented property values, using `@Model.Value("heroHeader", segment: "s1")`. It appears when ContentVariation.Segment is set, you can *only* read segment values, and not the unsegmented values, i.e. 
`@Model.Value("heroHeader", segment: null)`.

We would have expected it to be possible to read both non-segmented data as well as the segmented data. It appears this is not currently supported by Umbraco, segmented data and non-segmented data appear to be mutually exclusive by design. 

### Steps to reproduce
Using the Starter Kit, enable segment variation for the Home content type and the "heroHeader" property type (see #6179). 

Refresh content cache  (Settings > Published Status > Rebuild Database Cache + Reload Memory Cache).

In a the Views/home.cshtml file, put this code:
```cshtml
@Model.Value("heroHeader", segment: null)
```

### Expected result
The value "Umbraco Demo" will be shown.

### Actual result
Nothing is shown, the property value is empty.

**Comment by Shazwazza** [comment]
Fixed with https://github.com/umbraco/Umbraco-CMS/pull/6209
