### ISSUE TITLE
Feature - Reduce the number of "content" pickers down to only Multi-Node Tree Picker

### ISSUE THREAD

**Issue by NikRimington** [umbraco/Umbraco-CMS#6181]
So I've been thinking about whether it is worth having the following 3 pickers:

- Content Picker
- Media Picker
- Multi-Node Tree Picker

The functionality of both the content picker and the media picker are present in the Multi-Node Tree Picker and it would make sense if we removed the Content and Media pickers. MNTP is a much more flexible picker and with a few tweaks to it (for example enabling media preview) it could be a direct replacement for both of them. It has better support for defining pickable content types / media types, start nodes (e.g. use of xpath).

MNTP could also have its Property Value Converter enhanced to work in a similar way to Nested Content where if only a single type is available to it then it strongly types the return object. At the minute it always returns IPublishedContent.

I was wondering what peoples thoughts were on this?

**Comment by nul800sebastiaan** [comment]
Initial thoughts: maybe in the future.. 

- Currently MNTP can not filter out media/member types, which is a bug that needs fixing. 
- Then we need to make sure MNTP has the best user experience. In the past it used to be less elegant than the separate pickers (but I haven't compared them side-by-side recently)
- Phasing out the old ones can be done quite easily, we did this in v7 as well, Legacy datatypes would not be available in fresh installs but people who upgraded would still keep their existing datatypes
- We can not mess with PVCs at all, if the result is different than it is today, it will break the frontend of any site that is using the current PVCs.

I am looking forward to community comments as well as we'll have a chat about this at HQ!

**Comment by Matthew-Wise** [comment]
Have to say I cant recall the last time  I used a Content Picker. Like this idea of one picker to rule them all!

**Comment by mzajkowski** [comment]
The only reason why I sometimes used a single one, was a need for strongly casting it into a single object rather than collection of objects. Of course it might be sorted using the value converter, but might be also worth to adjust the MNTP "global" converter to return single object when settings assumes to select only 1 item. Just an idea.

+1 for the unification!

**Comment by ronaldbarendse** [comment]
Just like the `Umbraco.MultiUrlPicker`, this should be added as new data editor with a new value converter (the other editors can then optionally be marked as depreciated). The same features could also be added to the Multi URL Picker: https://github.com/umbraco/Umbraco-CMS/pull/2323#pullrequestreview-194926635 and https://github.com/umbraco/Umbraco-CMS/pull/5449 (this PR got closed as v7 won't include any new features anymore).

As content, media and members are all `IPublishedContent`, naming it `Umbraco.MultiContentPicker` might be a good one. Functionality could be almost idential to the Multi URL Picker (but without the URL and link title).

**Comment by alikazai** [comment]
Its a cool idea but would like to have a switch in the new multi node tree picker to be able to select media only, so editors don't try and put links where and image is suppose to go. 😄

**Comment by kjac** [comment]
From a maintenance perspective this makes a lot of sense. 

However, from a developer perspective (and specially a newcomer's perspective) it would probably be much better to get rid of MNTP and implement all MNTP features in Content Picker, Media Picker and a new Member Picker. It is just a lot more intuitive to create properties designated to picking specific types than it is creating MNTP properties. 

Don't get me wrong, I love MNTP and I use it almost exclusively. My concern here is solely about making Umbraco more intuitive and newcomer friendly.

**Comment by nathanwoulfe** [comment]
I agree with @kjac on this one - mntp isn't the most intuitive. There's a tipping point too where while it might make sense to combine everything, we'd end up with one monolith picker responsible for everything and harder to maintain, update and modify. 

Do agree though that multiple content pickers is a bit messy and could be cleaned up.

**Comment by leekelleher** [comment]
I'm with @kjac on this one too. In terms of simplicity, having a separate Content, Media and Member Pick would be much more intuitive.

_[insert some clever comment about "cognitive load" here]_ 😝 

As much as I love and use MNTP _(and that I was its steward back in its uComponents days)_, I now feel that it does too much for a single property-editor. I can't recall ever using MNTP for picking Media or Members, my typical use-case is picking multiple Content only.

So adding multiple-selection and filtering on the Content Picker (e.g. `Umbraco.ContentPicker`) would solve my use-case.

To note about the Media Picker (i.e. `Umbraco.MediaPicker`), this has its own nuances, e.g. media preview, and "Pick only images", "Disable folder select" options. Of course, these could be added into a unified MNTP, but would feel shoehorned (to me).

**Comment by BatJan** [comment]
I agree with @kjac and @leekelleher on this one too - I don't ever recall having used MNTP for selecting anything but content nodes. Having specific pickers will allow for more specific user experiences when picking content, media or members as Lee also mentions.

**Comment by abjerner** [comment]
As already mentioned a few times now, individual pickers seems to be the right way to go. And for the reasons already mentioned 👍

However whatever the outcome is, I hope that the logic for this will be isolated into directives rather than live in a regular controller. For instance the content picker property editor could simply use the `<umb-content-picker />` directive. Using directives would allow for greater re-use both within the Umbraco source code and for custom integrations.

I've tried to copy the implementation of the MNTP property editor for a grid element a few times, which isn't exactly pretty - and the build-in MNTP may change it's implementation between releases. Having the option to use a directive instead would mean that my MNTP grid element (or similar) would look the same as Umbraco's, and it will reflect any improvements and bug fixes made by Umbraco.

**Comment by hemraker** [comment]
Hey all, great discussion! Just to give some insight in to our discussions at HQ: We don't currently have anything planned for updating pickers. If there is need for one or more new pickers these would have to be packages atm. 

IMO sticking to separate pickers does seem like the right way to go as pointed out above. Initially I really liked the idea of consolidating the pickers but I can see the configuration and maintenance becoming quite complex. 

I think we can close this for now as the original request is not going to be fulfilled (New consolidated MNTP). If there are improvements that can be made to the existing pickers I think these should be made in separate issues/PRs. We can then either pick these up for development in the Core team or add them as up-for-grabs, depending on the priority/severity.

So please, if you have suggestions or issues to raise, create them for the picker they relate to and we can continue the discussion there :)
