### ISSUE TITLE
Multi Url Picker causes deserialization issue when Maximum is set in Multi Url Picker

### ISSUE THREAD

**Issue by vishalno** [umbraco/Umbraco-CMS#6184]
Hi,

I have a multi url picker and when i set a maximum of 1 to it, i am not able to read the value. For now i have removed the maximum (set it to 0)

Error:
Newtonsoft.Json.JsonSerializationException: 'Cannot deserialize the current JSON object (e.g. {"name":"value"}) into type 'System.Collections.Generic.IEnumerable`1[Umbraco.Web.PropertyEditors.MultiUrlPickerValueEditor+LinkDto]' because the type requires a JSON array (e.g. [1,2,3]) to deserialize correctly.
To fix this error either change the JSON to a JSON array (e.g. [1,2,3]) or change the deserialized type so that it is a normal .NET type (e.g. not a primitive type like integer, not a collection type like an array or List<T>) that can be deserialized from a JSON object. JsonObjectAttribute can also be added to the type to force it to deserialize from a JSON object.
Path 'id', line 2, position 7.'

After some investigation i see this error occurs when i put a maximum in the links settings.

**Comment by nul800sebastiaan** [comment]
Hey there @vishalno - many people use the Multi URL Picker successfully in this way, so I'm assuming there's something going wrong in your setup.

Make sure to follow the code samples in the documentation: https://our.umbraco.com/documentation/getting-started/backoffice/property-editors/built-in-property-editors/Multi-Url-Picker/ and note there is a specific code snippet for when you configure a maximum of 1.

If you have any further questions, make sure to ask on [the forums on Our Umbraco](https://our.umbraco.com) where our friendly community can help you along.
