### ISSUE TITLE
Search an element from its GUID with the backoffice

### ISSUE THREAD

**Issue by facingdigital** [umbraco/Umbraco-CMS#6185]
When an error occurs during the restore caused by a mismatch structure, or the status of a document, the message indicates always the GUID et not always the ID.
Therefore, we must use the database to find quickly the item causing the problem...

It could be very cool to use the main search engine to find a document, a media, a content type, a form etc... from the GUID... (with or without "-")

Thank you !

**Comment by nul800sebastiaan** [comment]
Thanks, I think this duplicates this issue, and agreed that is a good idea! https://github.com/umbraco/Umbraco-CMS/issues/4019

**Comment by Shazwazza** [comment]
Reopening since it's not quite the same issue and PR. I'm working on this now.
