### ISSUE TITLE
Clicking any <button> element triggers 'save' action in 8.1.3

### ISSUE THREAD

**Issue by Zweben** [umbraco/Umbraco-CMS#6187]
Clicking any `<button>` element on a backoffice page with a 'save' button triggers that save button in Umbraco 8.1.3.

Reproduction
------------

### Bug summary

Clicking any `<button>` element on a content, media, document type, data type, template, page, or any other backoffice page with a 'save' button, triggers a 'save' action.

### Steps to reproduce

Option A: Add a `<button>` element to a custom property editor and click it. No other code is needed.

Option B: In the browser's developer tools, add a `<button>` element anywhere in the HTML of a backoffice page with a save button, and click it.

### Expected result

Button does not trigger any actions.

### Actual result

Button triggers the 'save' action on the current  page.

**Comment by stevemegson** [comment]
This seems to be the correct result, albeit a bit surprising. A `<button>` with no `type` attribute specified acts as a submit button, and the custom property editor is inside a form that triggers Save when submitted. A `<button type="button">` gives a button that does nothing when clicked.

**Comment by nul800sebastiaan** [comment]
Indeed! I will re-open #6157 instead so we can that the tree can have a `type="button"` on each `<button>` element. That should help with your custom property editor.

**Comment by Zweben** [comment]
> This seems to be the correct result, albeit a bit surprising. A `<button>` with no `type` attribute specified acts as a submit button, and the custom property editor is inside a form that triggers Save when submitted. A `<button type="button">` gives a button that does nothing when clicked.

Ah, wow, I would've never thought of that, but it makes sense. Thanks for pointing it out.
