### ISSUE TITLE
HealthChecks problem after Umbraco upgrade umbraco from v7.5.8 to v7.14

### ISSUE THREAD

**Issue by Dannisgaard** [umbraco/Umbraco-CMS#6188]
Hi
I have a problem after Umbraco upgrade umbraco from v7.5.8 to v7.14

After IIS is restarted i get this error page: 
"Could not load the Umbraco.Core.Configuration.HealthChecks.IHealthChecks from config file, ensure the web.config and healthchecks.config files are formatted correctly"

healthchecks.config looks fine
and there is no erros in web.config.

Any sugestitons?

Reproduction
------------

The error comes every time IIS has bin restarted

### Expected result

My site frontpage

### Actual result

![24-08-2019 08-21-33](https://user-images.githubusercontent.com/5064674/63633396-57883500-c648-11e9-8f1f-d0ae0f9bdfbd.png)

**Comment by abjerner** [comment]
Hi @Dannisgaard,

How did you upgrade your Umbraco site? Did you do this manually, or via NuGet?

Umbraco 7.5.8 didn't have have a separate config file for health checks. Starting from line 11 in the main `Web.config`, a fresh install via NuGet has the following block:

```xml
		<sectionGroup name="umbracoConfiguration">
			<section name="settings" type="Umbraco.Core.Configuration.UmbracoSettings.UmbracoSettingsSection, Umbraco.Core" requirePermission="false" />
			<section name="BaseRestExtensions" type="Umbraco.Core.Configuration.BaseRest.BaseRestSection, Umbraco.Core" requirePermission="false" />
			<section name="FileSystemProviders" type="Umbraco.Core.Configuration.FileSystemProvidersSection, Umbraco.Core" requirePermission="false" />
			<section name="dashBoard" type="Umbraco.Core.Configuration.Dashboard.DashboardSection, Umbraco.Core" requirePermission="false" />
		</sectionGroup>
```

The separate config file was introduced some time before 7.14. If I do a fresh NuGet install of 7.14 looks like this (now starting from line 10):

```xml
        <sectionGroup name="umbracoConfiguration">
            <section name="settings" type="Umbraco.Core.Configuration.UmbracoSettings.UmbracoSettingsSection, Umbraco.Core" requirePermission="false" />
            <section name="BaseRestExtensions" type="Umbraco.Core.Configuration.BaseRest.BaseRestSection, Umbraco.Core" requirePermission="false" />
            <section name="FileSystemProviders" type="Umbraco.Core.Configuration.FileSystemProvidersSection, Umbraco.Core" requirePermission="false" />
            <section name="dashBoard" type="Umbraco.Core.Configuration.Dashboard.DashboardSection, Umbraco.Core" requirePermission="false" />
            <section name="HealthChecks" type="Umbraco.Core.Configuration.HealthChecks.HealthChecksSection, Umbraco.Core" requirePermission="false" />
        </sectionGroup>
```

Notice the reference to the health checks section at the bottom. It would seem that your `Web.config` doesn't have this, does it work if you add the line?

Upgrading via NuGet would normally take care of this, so I'm not sure it is a bug in the Umbraco upgrade process, but most likely something that went wrong if you upgraded manually. But feel free to prove me wrong, and we can have another look at it 😉

**Comment by Dannisgaard** [comment]
Hi abjerner
Thanks for your input.
I have upgraded  manually, and there was something a have missed in web.config.
Now it is working :-)

Thanks

**Comment by abjerner** [comment]
Great to hear it works 👍
