### ISSUE TITLE
MediaFactory - MediaPathPattern hardcoded to media

### ISSUE THREAD

**Issue by codyb11989** [umbraco/Umbraco-CMS#6202]
I changed the umbracoMediaPath config variable and the mediaPath column in cmsMedia table is always NULL.

Reproduction
------------

I changed the default media folder. Adding new media gives me NULL value in cmsMedia table column mediaPath

#### MediaFactory.cs - Regex MediaPathPattern
 - Doesn't take the config variable into account for the Regex

### Specifics

v.7.15.1

`private static readonly Regex MediaPathPattern = new Regex(@"(/media/.+?)(?:['""]|$)", RegexOptions.Compiled);`

![image](https://user-images.githubusercontent.com/20603773/63700059-0450e680-c7f0-11e9-9b01-427b08fd1136.png)

### Steps to reproduce

Change default media path to anything else

### Expected result

mediaPath added to cmsMedia table

### Actual result

NULL mediaPath in cmsMedia table

**Comment by nul800sebastiaan** [comment]
Fixed in https://github.com/umbraco/Umbraco-CMS/pull/6205
Cherry picked for 7.15.3 f5a445101d88c632965c17d1e8b0b68e181696ed
