### ISSUE TITLE
Properties in nested contents are displayed as json in default listview layout

### ISSUE THREAD

**Issue by AlexandreLocas** [umbraco/Umbraco-CMS#6207]
The default listview layout does not display properties inside nested contents. Instead they are displayed as json wich is unusable for end users. If these properties are made available when customizing the listview they should render correctly.

![2019-08-26 13_52_02-GuichetUnique CMS - Microsoft Visual Studio  (Administrator)](https://user-images.githubusercontent.com/29312983/63770629-9b2aab00-c8a3-11e9-92c3-17590d381330.png)

**Comment by nul800sebastiaan** [comment]
True, but the solution needs to be similar to #5545, there probably needs to be some kind of conversion from custom datatypes to list views, if possible. Looks like it's not easy and I personally doubt it will happen any time soon. :)
