### ISSUE TITLE
Preview not working with remove trailing slash

### ISSUE THREAD

**Issue by jveer** [umbraco/Umbraco-CMS#6217]
Preview not working when removing trailing slashes via web.config:
```
<rule name="Remove trailing slash" stopProcessing="true">
	<match url="(.*)/$"/>
	<conditions>
		<add input="{REQUEST_FILENAME}" matchType="IsFile" negate="true"/>
		<add input="{REQUEST_FILENAME}" matchType="IsDirectory" negate="true"/>
	</conditions>
	<action type="Redirect" redirectType="Permanent" url="{R:1}"/>
</rule>
```

PR incoming

**Comment by nul800sebastiaan** [comment]
Thanks for the PR, I left a comment. Also, you do know about the `<addTrailingSlash>true</addTrailingSlash>` setting in umbracoSettings.config? If you change the default to false, Umbraco shouldn't add any trailing slashes by default.

**Comment by kjac** [comment]
If this is V8 related, I beg to differ. If you remove trailing slashes by means of Umbraco config, preview works just fine. At least that's my experience 🙂

**Comment by patrickdemooij9** [comment]
@kjac But shouldn't the preview functionality work with the iis rule aswell? I assume not everyone knows about the trailing slash option in the umbraco config.

**Comment by kjac** [comment]
@patrickdemooij9 oh by all means, if you can fix it so it works in all permutations; that is

- forced *removal* of trailing slash via umbraco config
- forced *addition* of trailing slash via umbraco config
- forced *removal* of trailing slash via IIS rewrite rules
- forced *addition* of trailing slash via IIS rewrite rules

**Comment by patrickdemooij9** [comment]
@kjac I didn't mean to be offensive with my message. So sorry if it was. I was just trying to share my opinion on the matter :). 

I was just saying that I, as an user that doesn't know about addTrailingSlash, would expect the preview to work if I use the IIS rewrite rule to remove the trailing slash. The rest of the Umbraco CMS seems to work fine with it. It might be nice to avoid the confusion for the user by either a warning or by making the preview work in this scenario. I don't know how much work this would take as I don't claim to be a professional with the Umbraco code, but I think it would be a nice addition to the Umbraco CMS.

**Comment by jveer** [comment]
@kjac I've just checked for all options you've listed, however:
- Forced _removal_ and _addition_ through the umbraco config doesn't have any effect on the backoffice, so works in either scenario.
- Forced _removal_ via IIS rewrite rules works as expected (after change)
- Forced _addition_ via IIS rewrite rules breaks the backoffice completely, but that's not related to this PR. As the JavaScript and CSS are all loaded through relative paths, all JS and CSS can't be found with the force _addition_ of a trailing slash.

**Comment by kjac** [comment]
@patrickdemooij9 no offense taken, I'm sorry if my reply came out that way. That wasn't intended 😄 

@jveer I am happy as long as the built-in solution via umbraco config remains unaffected by this 😆 as for forced *addition* via IIS rewrite rules, perhaps the rule needs to exclude requests to the backoffice to work? I mean all rewrite rules should really exclude request to the backoffice; you'll only want them to target the frontend anyway, right?

**Comment by jveer** [comment]
@kjac I agree, but I just wanted to make sure it didn't break in case someone, for some reason, would like to add a trailing slash. But it already did 😞
And if you exclude requests to the backoffice from the rule, it won't impact this change in any way. So I think the PR should be an addition to fix potential bugs from users using the IIS rewrite rule for removing trailing slash instead of the umbracoSettings, agreed?

**Comment by kjac** [comment]
@jveer Disclaimer: I haven't tested the PR, I just wanted to add some context to it. 

If it works it's all good 👍 but it's not up to me to decide if it should be merged or not, that's up to @nul800sebastiaan and the PR team.

For future reference, here's how one *could* do a rewrite rule that doesn't affect the backoffice:

```xml
<rule name="RemoveTrailingSlashRule" stopProcessing="true">
  <match url="(.*)/$" />
  <conditions logicalGrouping="MatchAll" trackAllCaptures="false">
    <add input="{URL}" pattern="^/(?:layout|umbraco|install|template)(?:/.*)?$" negate="true" />
    <add input="{REQUEST_FILENAME}" matchType="IsDirectory" negate="true" />
    <add input="{REQUEST_FILENAME}" matchType="IsFile" negate="true" />
  </conditions>
  <action type="Redirect" url="{ToLower:{R:1}}" redirectType="Permanent" />
</rule>

```

**Comment by nul800sebastiaan** [comment]
Sorry for the delay on this one, I've been meaning to get back to it. 

Seeing as though this is an issue that seems to only affect @jveer for now, and there's a good workaround (maybe even multiple workarounds) I would recommend using the workarounds, which is probably the best way to avoid other problems with Umbraco routes. 

I will close this issue and the related PR for now and we can always revisit if this becomes an issue that affects many people.

Thanks for the feedback everybody! 👍

**Comment by nul800sebastiaan** [comment]
Additional note, if this is going to get traction in the future: this also needs testing with Umbraco being installed in a virtual directory, not sure if that affects anything in the related PR, but it is something that would need to be added to the test matrix.
