### ISSUE TITLE
Upgrading to 8.1.3 adds an extra dependentAssembly to web.config

### ISSUE THREAD

**Issue by torerikk** [umbraco/Umbraco-CMS#6229]
When installing 8.1.3 on top of 8.1.2 an additional

      <dependentAssembly>
        <assemblyIdentity name="System.Collections.Immutable" publicKeyToken="b03f5f7f11d50a3a" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-1.2.3.0" newVersion="1.2.3.0" />
      </dependentAssembly>

is added to web.config if one is already present.

https://github.com/umbraco/Umbraco-CMS/blob/v8/dev/build/NuSpecs/tools/Web.config.install.xdt is missing an 
    
      <dependentAssembly xdt:Locator="Condition(./_defaultNamespace:assemblyIdentity/@name='System.Collections.Immutable')" xdt:Transform="Remove" />

**Comment by nul800sebastiaan** [comment]
Thanks! Fixed for 8.1.5 https://github.com/umbraco/Umbraco-CMS/commit/303d709a7398014050824ea5c245d9a5fb796556
