### ISSUE TITLE
Unable to create members in the members section using the create option in the overlay

### ISSUE THREAD

**Issue by poornimanayar** [umbraco/Umbraco-CMS#6237]
Unable to create members in the members section using the create option in the overlay. This can be reproduced in v8.1.3 as well as the latest dev branch.

### Steps to reproduce

- Go to members section
- Click Members 
- On the Create a new member overlay, try to select a member type to create a member
- Nothing happens

### Expected result
When you click on a member type on the Create a new member overlay the right hand panel should present you with the edit member panel.

![member](https://user-images.githubusercontent.com/3941753/63979366-9424b800-cab0-11e9-92d3-3b35620c797a.gif)

**Comment by nul800sebastiaan** [comment]
Fixed in https://github.com/umbraco/Umbraco-CMS/pull/6238
Cherry picked for 8.1.5 f9319079c7fbb0f99cdc59c5cf670dd36a950922
