### ISSUE TITLE
v8: IPublishedContent.Siblings<T>() should return IEnumerable<T>

### ISSUE THREAD

**Issue by christophnz** [umbraco/Umbraco-CMS#6240]
### Bug summary

The extension method `IPublishedContent.Siblings<T>()` (in `PublishedContentExtensions.cs`) returns IEnumerable\<IPublishedContent>, but should return IEnumerable\<T> like other similar extension methods (eg `SiblingsAndSelf<T>()`, `Children<T>()` etc).

I will submit a pull request. I'm aware that this will be a breaking change, so I'm guessing this would not be merged in until the next minor version.

### Specifics

v 8.1.3

### Steps to reproduce

From an IPublishedContent object `x`, get siblings of a specific type `Y` by using `x.Siblings<Y>()`

### Expected result

As the type is passed in, I would expect the return type to be of type IEnumerable\<Y>

### Actual result

Returned collection is of type IEnumerable\<IPublishedContent>, so one has to use .OfType\<Y>() to convert the items to the type.

**Comment by christophnz** [comment]
Pull request: https://github.com/umbraco/Umbraco-CMS/pull/6242

**Comment by nul800sebastiaan** [comment]
Marked as breaking as some people may be using this method in their custom code. Most people will be using it in their views though so they won't notice the difference. For people using it in their code, a quick recompile should be sufficient.
