### ISSUE TITLE
Content Apps More dropdown doesn't show

### ISSUE THREAD

**Issue by KevinJump** [umbraco/Umbraco-CMS#6245]
When the browser window is narrow the "content apps" section will collapse down to a 'more' link. 

in Umbraco 8.1.x this dropdown doesn't open when you click more.

![image](https://user-images.githubusercontent.com/431231/64017587-db975c80-cb21-11e9-89d7-cbb171a6d9d7.png)

this is true where ever this navigation is used - Content, Media, Document Types, users section, packages section - in-fact any  pages using `umb-editor-header navigation `

---
_This item has been added to our backlog [AB#2477](https://umbraco.visualstudio.com/243e7927-03b2-44e2-908f-d4ac7ea5daaa/_workitems/edit/2477)_

**Comment by elit0451** [comment]
@KevinJump I can no longer reproduce the issue. Can you confirm that the problem has been fixed?

**Comment by KevinJump** [comment]
yes it appears to work in the latest release.

**Comment by elit0451** [comment]
Great! So, I will be closing the issue 🙂
