### ISSUE TITLE
v8: When calling MapUmbracoRoute, doesn't automatically exclude /Umbraco paths

### ISSUE THREAD

**Issue by mattbrailsford** [umbraco/Umbraco-CMS#6253]
In HeadRest, we use MapUmbracoRoute to map a custom route that intercepts all requests and points them to a custom controller that returns JSON. 

In a default config, we intercept the whole site URLs to create a completely headless API.

In converting this to v8 however, I've noticed an issue. By intercepting all routes, it's also intercepting the /umbraco/ route, where in v7, I'm pretty sure that no custom umbraco route could intercept the /umbraco/ route.

I've gotten around it for now by forcing the use of a IRouteConstraint which ensures the route doesn't start with /umbraco/, but I thought I'd report it anyways as this should really work the same way as v7.

**Comment by stevemegson** [comment]
This sounds like the same problem as #6045. There's a different workaround suggested there, though I don't think it's any better or worse than using an IRouteConstraint.

**Comment by nul800sebastiaan** [comment]
Yep, I think that's correct, it is the same issue as #6045 - you might want to rework the headrest package for 8.2.0 when it comes out.

**Comment by mattbrailsford** [comment]
@nul800sebastiaan cool. Looking at the issue I don't think I'd need to change anything that I've currently written as it should just mean my constraint wouldn't get hit anyways so all good. Solution in #6045 sounds fair to me 👍
