### ISSUE TITLE
umbraco does not exist in the current context using umbraco V8

### ISSUE THREAD

**Issue by noorsre** [umbraco/Umbraco-CMS#6254]
umbraco does not exist in the current context.
Umbraco 8
Umbraco 8
using System; using System.Collections.Generic; using System.Xml.XPath; using System.Web.Mvc; using System.Web.Configuration; using Umbraco.Core; using Umbraco.Core.Models; using Umbraco.Core.Services;

namespace umbracodemo2.Helpers { public class PreValueHelper { private const string APPSETTINGERROR_MESSAGE = "Invalid or missing appSetting, ";

    public List<SelectListItem> GetPreValuesFromDataTypeId(int dataTypeId)
    {
        List<SelectListItem> preValueSelectorList = new List<SelectListItem>();

        XPathNodeIterator iterator = umbraco.library.GetPreValues(dataTypeId);
        iterator.MoveNext();
        XPathNodeIterator preValues = iterator.Current.SelectChildren("preValue", "");

        while (preValues.MoveNext())
        {
            string preValueIdAsString = preValues.Current.GetAttribute("id", "");
            int preValueId = 0;
            int.TryParse(preValueIdAsString, out preValueId);
            string preValue = preValues.Current.Value;
            preValueSelectorList.Add(new SelectListItem { Value = preValue, Text = preValue });
        }

        return preValueSelectorList;
    }

    public List<SelectListItem> GetPreValuesFromAppSettingName(string appSettingName)
    {
        int dataTypeId = GetIntFromAppSetting(appSettingName);
        List<SelectListItem> preValues = GetPreValuesFromDataTypeId(dataTypeId);
        return preValues;
    }

    private int GetIntFromAppSetting(string appSettingName)
    {
        int intValue = 0;
        string setting = GetStringFromAppSetting(appSettingName);
        if (!int.TryParse(setting, out intValue))
        {
            throw new Exception(APP_SETTING_ERROR_MESSAGE + appSettingName);
        }
        return intValue;
    }

    private string GetStringFromAppSetting(string appSettingName)
    {
        string setting = WebConfigurationManager.AppSettings[appSettingName] as string;
        if (String.IsNullOrEmpty(setting))
        {
            throw new Exception(APP_SETTING_ERROR_MESSAGE + appSettingName);
        }
        return setting;
    }

}
}

=======================================================

In above Prehelper file for dropdown list, I am getting error "The name 'umbraco' does not exist in the current context." Please check below code line

XPathNodeIterator iterator = umbraco.library.GetPreValues(dataTypeId);

Since I am using umbraco V8 Please suggest.

**Comment by kjac** [comment]
Hi!

`umbraco.library` has been deprecated for a long long time, and in V8 it is no more. You'll probably want to have a look at the [services layer](https://our.umbraco.com/documentation/Reference/Management/Services/).

If you need help implementing things on top of Umbraco, please consult all the friendly people over at the [Our forum](https://our.umbraco.com/forum/),

**Comment by nul800sebastiaan** [comment]
Yep, as @kjac said, make sure to get some help on the forum! 👍
