### ISSUE TITLE
v8: UmbracoMapper forgets maps

### ISSUE THREAD

**Issue by mattbrailsford** [umbraco/Umbraco-CMS#6255]
I can't seem to be able to fully determine the conditions under which this occurs, but I'm seeing the UmbracoMapper forget some maps.

I'll compile my dll, and run a map for a registered type, which works, but then after a couple of refreshes or navigating some place else, and coming back, the map gets lost and I get an exception that no map is defined.

I thought initially it was because there were multiple maps defined for the same source type, but I'm not sure that is the case.

**Comment by mattbrailsford** [comment]
Ok, I think the problem seems to be if you call Map from within a mapping function, the mapper in the mappers collection seems to get replaced. For example:

    // BlogPostPage
    mapper.Define<BlogPostPage, BlogPostPageViewModel>(
        (src, ctx) => new BlogPostPageViewModel(),
        (src, dst, ctx) =>
        {
            // Run base mappers
            ctx.Map<Page, BasePageViewModel>(src, dst);

            // Custom maps
            dst.Excerpt = src.Excerpt;
            dst.Body = src.Body.ToString();
            dst.PublishDate = src.PublishDate; 
            dst.Author = src.WriterName;
        }
    );

Here I'm trying to trigger a base mapper to do a map, then map the extra properties manually. The mapper doesn't seem to like this and the inner `Map` call messes up the mappers cache.

**Comment by mattbrailsford** [comment]
Gah, looking in core, it looks like you have to create some extra classes and use inheritance to do this https://github.com/umbraco/Umbraco-CMS/blob/ade9bb73246caf25a7073f2b9e5262641a201863/src/Umbraco.Web/Models/Mapping/ContentPropertyDtoMapper.cs 🤦‍♂️

If this is not meant to be possible, I really don't understand why the MappingContext has a Map method on it?

**Comment by mattbrailsford** [comment]
Ok, so I've looked into this a bit further and even the using the alternative classes doesn't help.

So the issue is as follows. I have a couple of maps defined for the likes of `<HomePage, InitViewModel>` and `<HomePage, SitemapViewModel>` which are explicit maps for Homepage, but I also have a generic map `<Page, BasicNodeViewModel>` where Page is a master doc type, and thus a shared base class by all models builder models. Now, whilst every I'm calling the explicit maps, everything all runs smooth, but if I then ask to map a model of type `HomePage` using the base class based map, this overwrites all the maps for the explicit model maps.

I believe the source cause of this is within `UmbracoMapper.GetMap` https://github.com/umbraco/Umbraco-CMS/blob/db6714d3b8f8e04dceb607c3a25117331f6b525d/src/Umbraco.Core/Mapping/UmbracoMapper.cs#L350 In here, it looks up a best qualifying map, and when it finds one, it replaces all maps within the _maps collection with the map it found. I believe what this should do is to see if there is a key for the given source type, and if one is found, add to it's maps collection, rather than replacing them entirely.

**Comment by mattbrailsford** [comment]
PR submitted #6257

**Comment by zpqrtbnk** [comment]
Doh. Silly me. Good catch.

**Comment by nul800sebastiaan** [comment]
Fixed in https://github.com/umbraco/Umbraco-CMS/pull/6257

Cherry picked for 8.1.5 d01a5dcd8ee598281c1b394b0d19d0b1e3eb0415
