### ISSUE TITLE
Removing old versions of node results in SQL exception

### ISSUE THREAD

**Issue by remkovb** [umbraco/Umbraco-CMS#6259]
When wanting to remove old versions of a certain node, it results in a SQL exceptio:

```
System.Data.SqlClient.SqlException (0x80131904): The DELETE statement conflicted with the REFERENCE constraint "FK_umbracoDocumentVersion_umbracoContentVersion_id". The conflict occurred in database "korzo_nl", table "dbo.umbracoDocumentVersion", column 'id'.
The statement has been terminated.
```

Reproduction
------------
### Steps to reproduce
Just by doing this in code:
```
var cs = Current.Services.ContentService;
cs?.DeleteVersions(id, DateTime.Now);
```
the actual exception occures.

In Umbraco 8.0 to 8.1.3

### Expected result
Expecting the method just to execute without any errors/exceptions and the versions being removed from database.

### Actual result
Versions are not removed, exception occures and is shown in log.

**Comment by nul800sebastiaan** [comment]
Thanks, this duplicates https://github.com/umbraco/Umbraco-CMS/issues/5919
