### ISSUE TITLE
preview of a new saved content type (before publish) 

### ISSUE THREAD

**Issue by rimonr** [umbraco/Umbraco-CMS#6263]
umbraco version 8.1.3
preview page is not working with new saved pages before publishing the first time.

the steps that cause the problem:
1. creating document type with template
2. creating new content from this document type
3. after successful save, preview button appears 
4. clicking the preview button will open a new window (http://mydomain/umbraco/preview/?id=1073)
this url is not exists, the page shows the message
---------------------------------------------------
Page not found
No umbraco document matches the url '/1073.aspx'.
This page can be replaced with a custom 404. Check the documentation for "custom 404".
This page is intentionally left ugly ;-)
-------------------------------------------------

after publishing, the preview page is working as expected

**Comment by nul800sebastiaan** [comment]
I'm afraid I can't reproduce this problem. Maybe I'm doing something different than you are but it all seems to work as expected.

![6263](https://user-images.githubusercontent.com/304656/64181005-02c59500-ce66-11e9-837e-9af6fb68002f.gif)

**Comment by cleversolutions** [comment]
I have 2 U8 sites that can't preview pages until they have been published. Both started as 8.0 sites, and have been upgraded along the way. If I create a new 8.6 site, publish works as expected. I wonder if a problem was picked up along the way with upgrades. I'll do some investigation on our sites and see if I can't figure out what is going on. Attached is a gif that shows it not working as expected. I realize that doesn't help you if it can't be reproduced.

![I6mv4bS0jq](https://user-images.githubusercontent.com/23444011/75565838-af02c580-5a1c-11ea-8dea-72442e0c4c69.gif)

**Comment by nul800sebastiaan** [comment]
It's an old post, but this still holds up: https://cultiv.nl/blog/how-to-diagnose-umbraco-upgrade-problems/

Try to do a compare between the 8.5.3 zip from Our and your site and see what's different. Of course if you're not on 8.5.3 yet then choose the version you're on. 
I'd be curious what you find!

**Comment by cleversolutions** [comment]
Thanks @nul800sebastiaan I'll take a look at the link and find an answer. P.S. what program do you use for your screen captures?

**Comment by cleversolutions** [comment]
Luckily, this turns out not to be an upgrade problem. Using UmbracoCMS.IdentityExtensions and enabling `app.UseUmbracoBackOfficeTokenAuth(new BackOfficeAuthServerProviderOptions());` causes the problem. I should open an issue in the IdentityExtensions repo.
