### ISSUE TITLE
Codegarden link in installer doesn't go to current codegarden website

### ISSUE THREAD

**Issue by liamlaverty** [umbraco/Umbraco-CMS#6271]
Link in the installer `facts` goes here to `https://umbra.co/codegarden`, which redirects to codegarden18 instead of codegarden20's site

Reproduction
------------
1. Install a fresh instance of Umbraco, 
2. wait for the codegarden `fact`
3. click the link
4. See codegarden18 site

### Expected result
CG19 (current year) or CG20 (upcoming year) site

### Actual result
CG18 site

------------

File can be found here, not sure if it should be changed to codegarden20.com or left at the current address, but have that website updated to redirect to cg20's website. 

https://github.com/umbraco/Umbraco-CMS/blob/v8/dev/src/Umbraco.Web.UI.Client/src/installer/installer.service.js#L34

**Comment by nul800sebastiaan** [comment]
Thanks, we should just change the bit.ly link. I'll get someone to do that! 👍
