### ISSUE TITLE
Sticky bar is often active with no scroll

### ISSUE THREAD

**Issue by bjarnef** [umbraco/Umbraco-CMS#6273]
I have noticed the `umb-sticky-bar` often has the `umb-sticky-bar--active` class although there is no scroll on page or when scroll position is at top.

Reproduction
------------

If you're filing a bug, please describe how to reproduce it. Include as much
relevant information as possible, such as:

### Specifics
    * Umbraco 8.2.0 (latest changes on github `v8/dev` branch.
    * Google Chrome Version 76.0.3809.132
    * Firefox Version 69.0
    * Microsoft Edge Version 42.17134.1.0
    * Tested on a laptop with a browser viewport size on 1536 × 754px

### Steps to reproduce
* Go to page like recycle bin in content/media section and see the sticky bar is active (shadow) at top. Sometimes when clicking the recycle bin node again or refreshing page the shadow is gone.

![image](https://user-images.githubusercontent.com/2919859/64194180-c94d5380-ce7e-11e9-8755-c83de3da7d64.png)

![image](https://user-images.githubusercontent.com/2919859/64193855-0402bc00-ce7e-11e9-9f3b-544633206f3a.png)

* Go to a page with listview and see the sticky bar is active (shadow), altough no scroll on page.

![image](https://user-images.githubusercontent.com/2919859/64194447-6e682c00-ce7f-11e9-86b3-699fb8627dc9.png)

![image](https://user-images.githubusercontent.com/2919859/64194467-8049cf00-ce7f-11e9-83a9-25158a96b3ed.png)

### Expected result

The sticky bar should only have the class  `umb-sticky-bar--active` (with shadow) when there is scroll on page and the `umb-sticky-bar` is sticky at top of the page.

### Actual result

The `umb-sticky-bar` has sometimes `umb-sticky-bar--active` (with shadow) when there is scroll on page and with a grid on a document type it seem to be the reverted, so it has shadow when it is not at top of the page and then no shadow when it is at top of the page (sticky).

![image](https://user-images.githubusercontent.com/2919859/64194226-e08c4100-ce7e-11e9-87a4-7dca0126b863.png)

![image](https://user-images.githubusercontent.com/2919859/64194341-2ea14480-ce7f-11e9-8c5e-9a16d64e9d3b.png)

**Comment by bjarnef** [comment]
@nathanwoulfe maybe something you want to have a look at? 😃

**Comment by kjac** [comment]
This is soooo annoying. Fortunately Mr. @nathanwoulfe already did: https://github.com/umbraco/Umbraco-CMS/pull/5918

**Comment by bjarnef** [comment]
That's great @kjac. Hopefully the PR will be reviewed soon and merged.

**Comment by nathanwoulfe** [comment]
Ah! sticky bar! My favourite enemy!

**Comment by nul800sebastiaan** [comment]
I'll close this as a duplicate for the issues mentioned in the PR :)
