### ISSUE TITLE
RTE Embed dialog does not have focus on dialog open

### ISSUE THREAD

**Issue by bowserm** [umbraco/Umbraco-CMS#6276]
I have reproduced this on Umbraco 7.15.2.

When Umbraco's RTE `Embed` dialog is opened, the `URL` input does not automatically get focus. If a user tries to paste an embed url without first clicking on the `URL` input, they will unknowingly be pasting the embed url into the RTE behind the dialog. This could result in the url being rendered directly on the front end next to the embed iframe.

### Steps to reproduce

1. Ensure that the `Richtext editor` datatype has the `Embed` toolbar option enabled
1. Open a content node with the `Richtext editor` datatype on it.
1. Copy a youtube url into your clipboard
1. Click on the `Embed` icon in the RTE's toolbar. When the dialog opens, do not click anywhere.
1. Paste from your clipboard.

### Expected result

When you open the dialog, the `URL` field should automatically get focus. When you paste, you should see the youtube url in your clipboard pasted into the `URL` input. You should be able to successfully retrieve the embed iframe and submit it.

### Actual result

When you open the embed dialog, the `URL` field does not have focus. When you paste, it looks like nothing happens. If you click on the `URL` to give it focus before pasting, you should see the youtube url in your clipboard pasted into the `URL` input. You should then be able to successfully retrieve the embed iframe and submit it. When you do, you should see the raw embed url from your original and failed paste in the rich text editor.

**Comment by bowserm** [comment]
Here are some screenshots of the RTE embed I am trying to fix:

This is is the RTE embed with the problem:
![rte_embed_toolbar](https://user-images.githubusercontent.com/1404230/64215191-69e44900-ce68-11e9-919f-b4f85ac3efda.png)

This is a screenshot of the `URL` input that should automatically get focus when the overlay is opened:
![rte_embed_overlay_dialog](https://user-images.githubusercontent.com/1404230/64215197-6c46a300-ce68-11e9-9e01-2cab8bfd3692.png)

**Comment by nul800sebastiaan** [comment]
Fixed in https://github.com/umbraco/Umbraco-CMS/issues/6276

Cherry picked for 7.15.4 39972049bb7c1c3297f556beaaa9811763bcf1bc
Cherry picked for 8.1.5 9de47d1f320110f15b4c2044174955a6b0fd10d4
