### ISSUE TITLE
V8 Multinode Treepicker "Allow items of type" - Can't pick media types

### ISSUE THREAD

**Issue by HefinJ** [umbraco/Umbraco-CMS#6278]
When creating a new data type of "Multinode Treepicker" and selecting "Media" as node type, when clicking "Add" for Allow items of type - the dialog only shows Document types for content - it is not possible to select Media types even though you choose "Media" as the node type.

**Comment by nul800sebastiaan** [comment]
Thanks, apparently this has never worked properly. We're working on a fix to make this possible in the future, make sure to follow the progress here: https://github.com/umbraco/Umbraco-CMS/pull/6177
