### ISSUE TITLE
v8: Can't delete host in Culture and Hostnames

### ISSUE THREAD

**Issue by Jojov11** [umbraco/Umbraco-CMS#6279]
Hi,

in **Umbraco backend** / admin I **can't delete hostname** on content item under "**Culture and Hostnames**".
If i click on delete button (red btn with white trash) then "Culture and Hostnames" menu hide and hostname still exist ( don't delete it ).

There are no errors in the console and no requests are made after click on delete btn.

This bug is minimal in current version and previous.

OS: Windows 7
Browse: Chrome ( latest version), IE 11

**Comment by nul800sebastiaan** [comment]
Hi @Jojov11 - which version of Umbraco are you using?

**Comment by Jojov11** [comment]
@nul800sebastiaan 
Latest version 8.1.4

**Comment by nul800sebastiaan** [comment]
Thanks! As you can see in the GIF below, I am having no problems. Maybe something went wrong in one of your upgrades or something? We fixed this issue in 8.1.1 https://github.com/umbraco/Umbraco-CMS/issues/5815

Here's some help in identifying upgrade issues: https://cultiv.nl/blog/how-to-diagnose-umbraco-upgrade-problems/


![6279](https://user-images.githubusercontent.com/304656/64241833-bc734300-cf04-11e9-8a79-aac415d45914.gif)

**Comment by Jojov11** [comment]
Okay.
 I didn't see errors during updating ( any time ) but I downloaded latest .zip file, extract and replace folder Umbraco ( assets, js ... ). Now btn for deleting is work.

THX.
