### ISSUE TITLE
V8: Migration fails if the superuser has notifications

### ISSUE THREAD

**Issue by stevemegson** [umbraco/Umbraco-CMS#6280]
The `SuperZero` migration moves the superuser from ID 0 to -1, but it doesn't update `umbracoUser2NodeNotify`. If there are any notifications configured for user ID 0, the migration fails with a foreign key violation.

**Comment by nul800sebastiaan** [comment]
Thanks @stevemegson ! 

Just as a note, it's absolutely fine to only submit a PR without an associated issue, we used to need an issue on the old tracker as that was where the release notes were generated from but we generate them from GitHub now and use either the issue or the PR  👍

**Comment by nul800sebastiaan** [comment]
Fixed in https://github.com/umbraco/Umbraco-CMS/pull/6281

Cherry picked for 8.1,5 7b0b0f94957df059694c237998eb5d063d9bd29b
