### ISSUE TITLE
V8: Sections tray dropdown uses old colours

### ISSUE THREAD

**Issue by nathanwoulfe** [umbraco/Umbraco-CMS#6287]
On a small screen, when the top nav collapses and hides overflowing section links in the dropdown tray, the background on said tray is purple. 

Reproduction
------------

- Fire up a browser, shrink the window until the ... button appears. 
- Click that button
- Be horrified at the purple background in the otherwise consistent blue+pink v8 world

![purple tray](https://user-images.githubusercontent.com/3248070/64403714-f6874500-d0bc-11e9-9403-620435b70bbc.gif)

This is a quick CSS fix, which I'll provide shortly.

**Comment by nul800sebastiaan** [comment]
Just as an FYI: the old requirement of having to create an issue before you create a PR is no longer necessary, we now generate the release note from either PRs or issues, so just a PR is more than enough! 👍 

Cherry picked for 8.1.5 1723c39e009322b737c6195a9462a3484369a4b8

**Comment by nathanwoulfe** [comment]
Nice! It's always felt redundant creating an issue just to submit the PR, a good change 👍
