### ISSUE TITLE
Umbraco 8 - Users Groups and Permissions

### ISSUE THREAD

**Issue by milance-feelgood** [umbraco/Umbraco-CMS#6289]
Hello Umbraco team,

I have problem with users and groups in our multi language website developed in Umbraco 8 (Umbraco version 8.1.2).

We created next groups:
1) **Admin** - full access of Umbraco back office
1) **News Repository - Read And Copy** - this group of users can browse and copy news from one specific node News Repository
2) **Common Data - Admins** - users of this group can Browse, Rollback, Delete, Create, Publish, Unpublis, Copy, Move, Sort nodes under specific node Common Data
2) **Common Data - Read only** - users of this group can only browse content node of this specific node Common Data
3) Domain editors - each of country (each home page node has assigned specific culture and domain) has it's own group which allows users to have full access inside node of that appropriate (assigned) culture and media folder for specific culture. So, there are next several groups :
**Domain IT** - full access only for nodes under home page with cultre it-IT and media folder for IT, 
**Domain AT** - full access only for nodes under home page with culture de-AT and media folder for AT, 
**Domain DE** - full access only for nodes under home page with culture de-DE and media folder for DE, 
**Domain CZ** - full access only for nodes under home page with culture cs-CZ and media folder for CZ

We need to allow user to:

1) browse News Repository node and copy children node under specific home node
2) browse Common Data node - read only access
3) full access to specific home node (node with specific culture assigned)
4) browse all home nodes from another culture.

For example, 
website for Italy will be maintained by user who can:
create everything inside home page node (assigned culture on home node is: it-it)
browse all nodes from Common Data node
browse and copy news items from News Repository into this home page node for Italy
browse all the other home nodes which aren't of selected culture (ex. AT, DE, CZ)

We tried to achieve this goal by assigned next groups to the single user:
**Domain IT** 
**Common Data - Read only** 
**News Repository - Read And Copy** 

But, we have problem that our user has default permissions from which has max permissions (from Domain IT) reflected to all the other nodes. From Domain-IT group we have full access and all rest nodes have the same permissions even they have own group permission set (for instance, just copy and browse content from News Repository). 

Also, we tried with one group which has Content root as content start node, only Browse node permission and in granular permissions we added for each of nodes News Repository, Common Data and Domain IT specific permissions. Results in this case are that we only have default permissions from start content node (in this case from Content root) for all nodes inside and only selected nodes from granular permissions has their own permissions (children inside have default permissions which is not what we need).

![Domain-AT-permissions](https://user-images.githubusercontent.com/54978926/64413908-b612d180-d092-11e9-949a-9a0b9fd815c2.jpg)

Can you help us and give us solution how we can setup user groups in order to achieve our needs?

Thank you in advance!

**Comment by nul800sebastiaan** [comment]
Hi there @milance-feelgood - thanks for your inquiry. The issue tracker on GitHub is commonly used to report bugs and not feature requests. For questions on how to use Umbraco I would point you to our forums at https://our.umbraco.com

**Comment by milance-feelgood** [comment]
Hi @nul800sebastiaan Thank you for your answer. Just to check is it possible to achieve granular permissions inheritance so that all children inherit granular permission from parent node?
Currently, I made an example but granular permissions are not applied on children nodes. Is this by design possible or not?
