### ISSUE TITLE
UI: Spacing the left and right side of the nested content item header-bar is too little

### ISSUE THREAD

**Issue by nielslyngsoe** [umbraco/Umbraco-CMS#6312]
The white space amount in each side of the header-bar of nested content items is too narrow.

Should be visually equivalent to the space between the Element-Type-Icon and the name, and the spacing between the action icons.

Thanks

![image](https://user-images.githubusercontent.com/6791648/64530811-4a3c9d00-d30e-11e9-961d-6c6ecb613884.png)

**Comment by kjac** [comment]
@nielslyngsoe the padding was removed to make NC a bit more consistent with other icon-and-name style property editors like MNTP. See #5594 (specifically https://github.com/umbraco/Umbraco-CMS/pull/5594#issuecomment-500202690) for details.

I don't mind reverting it, but I just wanted to give you some context to this 😄

**Comment by nielslyngsoe** [comment]
@kjac Aha! is properly the best word to describe my reaction ;-)

Thanks for remembering this! My 2,5 months of paternity leave left me without this memory. But I clearly see the argument, and my own comment...

Seen from a visual perspective both things are right and would in a perfect world become true... #1 they should align, #2 there should be equivalent spacing around the icons.

So the task escalated a bit, I will return when I have investigated the consequence of increasing the space on all lists items.
