### ISSUE TITLE
V7.15.3 after delete confirmation dialog remains on-screen.

### ISSUE THREAD

**Issue by martinjgriffiths** [umbraco/Umbraco-CMS#6313]
Right click on content item, select delete.
Press OK.
Item removes from tree but the confirmation dialog remains on-screen and doesn't close with item deleted confirmation message.

**Comment by kjac** [comment]
@martinjgriffiths it should work something like this: https://github.com/umbraco/Umbraco-CMS/pull/6004 - is that not what you see?

**Comment by martinjgriffiths** [comment]
> @martinjgriffiths it should work something like this: #6004 - is that not what you see?

This is what I see after delete.... I am using Nexu (latest version)

![image](https://user-images.githubusercontent.com/883638/64605112-4dda2d80-d3bb-11e9-975b-e5eb6b1dcf05.png)

**Comment by kjac** [comment]
When I delete content in 7.15.3 (vLatest from git) I see this:

![delete-confirmation](https://user-images.githubusercontent.com/7405322/64608426-e62bde80-d3ca-11e9-91f9-fb3c0fd0d987.gif)

**Comment by martinjgriffiths** [comment]
> When I delete content in 7.15.3 (vLatest from git) I see this:
> 
> ![delete-confirmation](https://user-images.githubusercontent.com/7405322/64608426-e62bde80-d3ca-11e9-91f9-fb3c0fd0d987.gif)

Ok, could be an interaction issue with Nexu? I'll try a starter install with the plug-in added.

**Comment by kjac** [comment]
If you could try a default install without any extra plugins installed and see if the behavior is as expected that would be great 🙂

**Comment by nul800sebastiaan** [comment]
Sounds like an upgrade issue indeed. :-) 

I will close this for now, let us know if you have more info on how to repro @martinjgriffiths

**Comment by martinjgriffiths** [comment]
> Sounds like an upgrade issue indeed. :-)
> 
> I will close this for now, let us know if you have more info on how to repro @martinjgriffiths

I disagree, not an upgrade issue an issue with a third party extension. I'll take a deep dive into this today and see if I can uncover the problem
