### ISSUE TITLE
logResource.getLog(type, since) not found

### ISSUE THREAD

**Issue by kasperskov909** [umbraco/Umbraco-CMS#6320]
The [documentation](https://our.umbraco.com/apidocs/v8/ui/#/api/umbraco.resources.logResource) clearly states that the `logResource` service has a function `getLog` which tries to get "/umbraco/backoffice/UmbracoApi/Log/GetLog". The result is a 404.

I've searched the source code and I could not find a service for this purpose. The closest thing is the interface [IAuditService](https://github.com/umbraco/Umbraco-CMS/blob/853087a75044b814df458457dc9a1f778cc89749/src/Umbraco.Core/Services/IAuditService.cs) which has a method called GetLogs with somewhat the same params. It's not implemented in any service though.

The question is, is this a flaw in the documentation with an obsolete or deprecated function or a missing method or implementation? 

I did find that `getPagedUserLog(options)` from the angular `logResource` works. As far as I can tell it points to [LogController](https://github.com/umbraco/Umbraco-CMS/blob/f55e05da79ca827b192a03d6d1271501bced0b66/src/Umbraco.Web/Editors/LogController.cs). Is this were the method is missing? The reason for my confusion and why it's not clear for me, is that the above `LogController` is located in "Editors" folder.

Reproduction
------------

When authorized in backoffice execute "/umbraco/backoffice/UmbracoApi/Log/GetLog?logtype=save&sinceDate=2019-10-06T22%3A00%3A00.000Z" / `logResource.getLog("save", new Date(2019, 9, 7))`.

### Bug summary

Flaw in [logResource documentation](https://our.umbraco.com/apidocs/v8/ui/#/api/umbraco.resources.logResource) as "getLog" function is deprecated OR method for gettings logs from log type is not implemented.

### Specifics

Tested on a custom dashboard (/umbraco#/content) in a custom angular controller with logResource injected.
v. 8.1.4
Chrome 76

angular.js?cdv=1:13531 GET http://localhost:64164/umbraco/backoffice/UmbracoApi/Log/GetLog?logtype=save&sinceDate=2019-10-06T22%3A00%3A00.000Z 404 (Not Found)

Possibly unhandled rejection: {"errorMsg":"Failed to retrieve log data of type save since Mon Oct 07 2019 00:00:00 GMT+0200 (Central European Summer Time)","data":{"Message":"No HTTP resource was found that matches the request URI 'http://localhost:64164/umbraco/backoffice/UmbracoApi/Log/GetLog?logtype=save&sinceDate=2019-10-06T22%3A00%3A00.000Z'.","MessageDetail":"No action was found on the controller 'Log' that matches the name 'GetLog'."},"status":404}

**Comment by nul800sebastiaan** [comment]
The linked documentation reads: 

> `getEntityLog(id)`
> `[OBSOLETE] use getPagedEntityLog instead` 

Does it help to use `getPagedEntityLog`?

**Comment by kasperskov909** [comment]
@nul800sebastiaan sorry wrong method. I'm talking about `getLog`

**Comment by nul800sebastiaan** [comment]
Ah ok! I am completely unfamiliar with any of this, so let me instead ask: what exactly are you trying to accomplish? I see you have a custom dashboard, what kind of data are you trying to display in it?

**Comment by kasperskov909** [comment]
Basically I wish to display recently saved nodes... when, where and by who.

**Comment by nul800sebastiaan** [comment]
Ah, I don't think we really have good things for that available in the javascript implementation.

This `getLog` method looks like it is unused in our codebase so it's likely something left behind from v7. 

I would recommend you get some advise on the forums on the best way to achieve your goals of getting a good overview of recently saved nodes, I'm sure it's possible but I don't know off the top of my head how.

**Comment by nul800sebastiaan** [comment]
I forgot to mention: I think the best way to get this type of info might be available from the `AuditRepository`.

**Comment by kasperskov909** [comment]
@nul800sebastiaan alright. Should I leave an issue on the documentation?

**Comment by stevemegson** [comment]
@kasperskov909 the documentation is being auto-generated from the code. The problem is that the obsolete methods have been removed from `LogController` at some point, but the code that calls them hasn't been removed from `logResource`.

However, I wonder whether `GetLog` was an unintended victim of code cleanup. It's no longer marked obsolete in the latest v7 code, and the message said "Use GetPagedLog instead" but there's no such method.

**Comment by kasperskov909** [comment]
@stevemegson I see. Could the obsolete mark simply be missing? A cleanup gone rouge sounds very likely.

@nul800sebastiaan what's your thoughts on this?
