### ISSUE TITLE
V8: Bug with permissions when a user is in multiple groups

### ISSUE THREAD

**Issue by Baasker** [umbraco/Umbraco-CMS#6340]
**Problem:**
A user can be assigned to multiple groups. Based on these groups, the user can get permissions in the CMS. When a user is assigned to one group, this is working fine. But when a user is assigned to multiple groups, a user gets the group with the most power.

**Example:** 
for one of our clients we use groups and some of the users have access to multiple groups. In these groups we set the permissions of some pages and disable some of the pages to edit. When I add one of the groups to this user, the permissions work fine. When I add this user to multiple groups, the permissions doesn't seem to work.. All of a sudden the user can also edit the content where he shouldn't have acces to.

**Comment by nul800sebastiaan** [comment]
Thanks for reporting, this is how it works, you give them more power and they get more power. 

This sounds like a rather specialized requirement so I would suggest that you start investigating the ContentService events in which you can figure out the type of user and if they should be able to Save a node, if not you can cancel saving the node.

If you need more help, I  would recommend you discuss the requirements on [our forums and see if people have some good alternative suggestions](https://our.umbraco.com/)!
