### ISSUE TITLE
Document types Tour freezes after the 11th step

### ISSUE THREAD

**Issue by MrPedja96** [umbraco/Umbraco-CMS#6351]
I'm getting started with Umbraco CMS and I've run into a problem while doing the Document types tour - it can't be finished. When I get to 11th step (Property) and click Next, it always freezes and I must refresh the page.

Reproduction
------------

If you're filing a bug, please describe how to reproduce it. Include as much
relevant information as possible, such as:

### Bug summary

Document types tour (under Data structure) can't be finished. It freezes after clicking Next on the 11th step.

### Specifics

I'm using version 8.1.4 of Umbraco CMS on Google Chrome (Version 77.0.3865.75). Tried it on Mozilla Firefox (Version 69.0) and result was same. Here's how it looks when it freezes:

![image](https://user-images.githubusercontent.com/40575731/64966853-d49d7780-d89f-11e9-82e2-25272d19b99a.png)

### Steps to reproduce

Click Help button in the upper right corner. Under Tours click on Data structure and then Start next to Document types. Start tour and pass the steps 1 through 11. Click Next on the 11th step.

### Expected result

It was logical that the 12th step would show up so that I could continue the tour.

### Actual result

The page freezes and you must refresh it to continue using Umbraco.

**Comment by stevemegson** [comment]
It's trying to highlight the 'Add Property' button in the Content group, but it's out of view off the bottom of the screen and the overlay means that you can't scroll down to see it. Since you can't see the element you're supposed to click on, you're stuck on this step of the tour.

The tour should scroll the highlighted element into view, but in this case it's confused by CSS positioning.

**Comment by nul800sebastiaan** [comment]
Thanks, this is the same issue as https://github.com/umbraco/Umbraco-CMS/issues/5954 

I would be nice if we could somehow scroll the element in view.

**Comment by MrPedja96** [comment]
Yes! I zoomed it out and it really is down there. Thank you!
