### ISSUE TITLE
Nested content not rendering correctly when only one document-type is configured

### ISSUE THREAD

**Issue by rensknoors** [umbraco/Umbraco-CMS#6358]
We noticed that some of our nested content data-types suddenly caused the error _'Object reference not set to an instance of an object.'_ when trying to get the data of the nested content. After looking into this issue we noticed that it happens when only 1 document-type is configured. When a second one is added, it works as intended.

This issue is already discussed with Umbraco Support and they also seem to think that this is probably a bug.

Reproduction
------------

### Bug summary

Nested content doesn't render correctly when only 1 document-type is configured.

### Specifics

**Version:** 8.1.4
**Deploy:** 3.1.1

**Data-type configuration:**
![image](https://user-images.githubusercontent.com/14264313/65037405-e89fb280-d94d-11e9-87ec-7417260ac65c.png)

**Code used to render the nested content:**
```csharp
// Nested content has alias "statistics"
var statistics = Model.Value<IEnumerable<IPublishedElement>>("statistics");
foreach (var statistic in statistics)
{
  ...
}
```

### Expected result

I expect to be able to loop through the nested content data-type and render everything.

### Actual result

I get an error and am not able to render the data inside the nested content
![image](https://user-images.githubusercontent.com/14264313/65038339-0a9a3480-d950-11e9-9204-5c29fc3a5127.png)

### Workaround
Adding a second document-type to the nested content fixes the rendering.
![image](https://user-images.githubusercontent.com/14264313/65039100-c445d500-d951-11e9-826c-e9002cbd2956.png)

**Comment by nul800sebastiaan** [comment]
Interesting but unfortunately I can't reproduce this in a clean 8.1.4 install. 

![image](https://user-images.githubusercontent.com/304656/65040208-27d10200-d954-11e9-8be8-686ee2dc3c83.png)

![image](https://user-images.githubusercontent.com/304656/65040228-315a6a00-d954-11e9-81c1-1084a55a6611.png)

No null ref errors when doing this. I must assume it's some configuration problem, custom propertyvalueconverters or something else, not sure.

If you can get more steps to repro then we're all ears.

**Comment by martindotcontrol** [comment]
@nul800sebastiaan in the end we where able to figure out what the issue was. It's important that the setting 'is an element type' is enabled when using in compositions on nested content. The null reference error was there because the modelsbuilder was unable to build.

![image](https://user-images.githubusercontent.com/5165350/65224123-d98e4100-dac2-11e9-89a8-43a66f4640a9.png)

Shouldn't the backoffice give a warning in cases like these?

**Comment by alexserdyuk** [comment]
The same problem occurs when migrating nested content from Umbraco 7.x to Umbraco 8. There is no 'Is an Element type' property in Umbraco 7

I enabled 'Is an Element type' for all nested document types after migration, but it didn't help.

The workaround described above (adding one more document type) helps.

**Comment by davit20** [comment]
hi guys here is my fix

1. Install **Umbraco.ModelsBuilder** from  Nuget
2. In web.config you should have next values for  **Umbraco.ModelsBuilder**

    <add key="Umbraco.ModelsBuilder.Enable" value="**true**" />
    <add key="Umbraco.ModelsBuilder.ModelsMode" value="**LiveDll**" />
