### ISSUE TITLE
Blank screen in Umbraco 7 backoffice

### ISSUE THREAD

**Issue by addisonlynch** [umbraco/Umbraco-CMS#6362]
Umbraco BackOffice is displaying blank screen after login

Reproduction
------------

* Login to umbraco backoffice

### Bug summary

On a local build of my website I was unable to access the umbraco backoffice. Instead a blank screen was displayed. This is umbraco 7.7.8.

![image](https://user-images.githubusercontent.com/21162161/65056652-3eb92980-d93f-11e9-831a-db91bfe41eac.png)

### Specifics

I tried to create a fresh Umbraco build, but after changing my application's project URI the same error appears. I have tried in different browsers / clear cache / restart IIS /etc.

With the fresh build, the backoffice will *sometimes* display in an incognito/private tab, but with the original build it will not display in any case. Same error messages.

### Expected result

Umbraco backoffice

**Comment by nul800sebastiaan** [comment]
It seems like something is broken in your specific install, of course this doesn't happen for everybody using Umbraco.

I would recommend you get [some help on the forum from our friendly community](https://our.umbraco.com) who can give you more pointers on how to debug the problem.
