### ISSUE TITLE
V8:Umbraco casting to LuceneIndex

### ISSUE THREAD

**Issue by bielu** [umbraco/Umbraco-CMS#6364]
Hi Guys, 
I just notice with trying installation of my package on Umbraco 8.1.2 exactly the same issue, which I already fixed:
https://github.com/umbraco/Umbraco-CMS/pull/5801
Could you check if it was added to release 8.1.1 : 
https://our.umbraco.com/download/releases//811
as here I could see that issue but not in code of the release.

**Comment by nul800sebastiaan** [comment]
Ah... I think someone forgot to cherry pick this to 8.1.x. I've added it to the upcoming 8.1.5 instead (see #5801).

Sorry about that!
