### ISSUE TITLE
hide settings when reordering DocType

### ISSUE THREAD

**Issue by nielslyngsoe** [umbraco/Umbraco-CMS#6374]
We should hide the settings-icon when re-ordering a DocumentType.

Because it makes the re-order elements too high.

![image](https://user-images.githubusercontent.com/6791648/65239361-1b2ce500-dadf-11e9-8243-5e856c87f859.png)

**Comment by nul800sebastiaan** [comment]
Fixed in https://github.com/umbraco/Umbraco-CMS/pull/6403
