### ISSUE TITLE
Delete member confirm button uses the wrong color

### ISSUE THREAD

**Issue by rasmusjp** [umbraco/Umbraco-CMS#6376]
When deleting a member the action button is green, this should be red like in the other confirm overlays as it's a destructive action.

![image](https://user-images.githubusercontent.com/379886/65243243-48ca5c00-dae8-11e9-8f69-bba3aff49c1c.png)

**Comment by bjarnef** [comment]
PR submitted https://github.com/umbraco/Umbraco-CMS/pull/6429

**Comment by nul800sebastiaan** [comment]
Fixed in https://github.com/umbraco/Umbraco-CMS/pull/6429
