### ISSUE TITLE
Tags fragmentation after upgrade from 7.11.1 to 7.15.3

### ISSUE THREAD

**Issue by jacktric** [umbraco/Umbraco-CMS#6378]
After the upgrade from version 7.11.1 to version 7.15.3 the values in Tags properties have been fragmented letter by letter.

See attached images to look at the differences between production (7.11.1) and dev (7.15.3) environments. 

Production (7.11.1)
![image](https://user-images.githubusercontent.com/8735590/65244419-c3947680-daea-11e9-8369-b65fc1eaa361.png)

Dev (7.15.3):
![image](https://user-images.githubusercontent.com/8735590/65244347-9942b900-daea-11e9-88b2-abae009ec6c8.png)

Reproduction
------------

Upgrade Umbraco via NuGet.

**Comment by nul800sebastiaan** [comment]
Hmm, I haven't seen this before, but tag storage options switched around a bit in 7.12.0 https://github.com/umbraco/Umbraco-CMS/issues/6378

Are you sure you didn't switch the tags config from JSON to CSV on your datatype?

**Comment by nul800sebastiaan** [comment]
Also please run through these upgrade diagnosis steps, especially the ClientDependency version update and the compare of files : https://cultiv.nl/blog/how-to-diagnose-umbraco-upgrade-problems/

**Comment by jacktric** [comment]
> Are you sure you didn't switch the tags config from JSON to CSV on your datatype?

I haven't changed nothing manually yet after the upgrade but your tip could be valid.
For Tags datatype in prod I see Storage Type set on CSV while in dev is on Json.
Is this a breaking change? I didn't read about it.

Setting the value back to CSV (legacy) fix the issue.
Anything else to check or to be aware of?

**Comment by jacktric** [comment]
Now I noticed it is reported as a new feature in version 7.12.0: https://issues.umbraco.org/issue/U4-11497
Maybe deleting the current values in tags properties, switch to Json and insert the values again could be a good idea in order to avoid the same problem on future upgrades.
What do you think?

**Comment by nul800sebastiaan** [comment]
Just to confirm: your issue is fixed after changing the storage type? 

I think you had some kind of random accident in that case, since other upgraders didn't have this problem. For now I'd say case closed if your site is working perfectly again. I'll close this for now!

**Comment by jacktric** [comment]
Yes, issue fixed after changing the storage type. Thank you.

**Comment by filipesousa** [comment]
We had this same issue on a website running 7.12.4. We solved it by changing the storage type from json to csv.
