### ISSUE TITLE
Disable renaming alias of built in user groups

### ISSUE THREAD

**Issue by rasmusjp** [umbraco/Umbraco-CMS#6379]
This kinda relates to https://github.com/umbraco/Umbraco-CMS/issues/6377

I think we should disable renaming the alias of built in user groups since they are referenced multiple places in the code base and if you rename `admin` the backoffice explodes.

![image](https://user-images.githubusercontent.com/379886/65244961-fb4fee00-daeb-11e9-859a-5972ec9de6e9.png)

After renaming the alias of the `Administrator` group

![image](https://user-images.githubusercontent.com/379886/65244987-086cdd00-daec-11e9-8756-cb1dc03acd6b.png)

**Comment by nul800sebastiaan** [comment]
Oh yes! 🙈
