### ISSUE TITLE
Add language button uses the wrong color

### ISSUE THREAD

**Issue by rasmusjp** [umbraco/Umbraco-CMS#6380]
The `Add language` button is using the `success` style it should use the `action` style like other create buttons does

![image](https://user-images.githubusercontent.com/379886/65248695-e1fe7000-daf2-11e9-8914-bfc8485975ad.png)

![image](https://user-images.githubusercontent.com/379886/65248816-17a35900-daf3-11e9-97eb-d9f3a00a32d7.png)

**Comment by nul800sebastiaan** [comment]
Fixed in https://github.com/umbraco/Umbraco-CMS/pull/6398
