### ISSUE TITLE
Accessibility: the button to customize the installation is an anchor tag

### ISSUE THREAD

**Issue by lynnewritescode** [umbraco/Umbraco-CMS#6381]
Reproduction
------------

### Bug summary

In the first screen, the button to customize the installation is a link (anchor tag). This is confusing as links and buttons do different things and a user hopping from button to button will outright miss this control.

Issue taken from: [https://gist.github.com/zersiax/b6ab5b37cf52c8d1a6a371bf2250a872](https://gist.github.com/zersiax/b6ab5b37cf52c8d1a6a371bf2250a872)

### Steps to reproduce

- Create a new Umbraco 8 project
- Run the project from Visual Studio
- On the first install screen the customize button (on the right) uses an anchor tag instead of a button

![image](https://user-images.githubusercontent.com/4159464/65261882-19741900-db01-11e9-9d79-d853a3ec8d20.png)

### Expected result

The customize button should use a <button> element instead of an anchor tag.

**Comment by nul800sebastiaan** [comment]
Fixed in https://github.com/umbraco/Umbraco-CMS/pull/6382

**Comment by nul800sebastiaan** [comment]
Just a tip 💡 - you're not required to create an issue before you open a PR, for small changes like this it's fine to fire off a PR without creating the issue first.

**Comment by lynnewritescode** [comment]
> 
> 
> Just a tip 💡 - you're not required to create an issue before you open a PR, for small changes like this it's fine to fire off a PR without creating the issue first.

Thanks for this! I was just following along with the guidelines. Will keep in mind.
