### ISSUE TITLE
Feature: Show Thumbnail instead of UDI for Media properties in Listview

### ISSUE THREAD

**Issue by hfloyd** [umbraco/Umbraco-CMS#6385]
Customized Listviews on Content nodes can have Media Picker properties included, but in the Listview - whether viewed in "List" or "Grid" format, the Media property data is displayed as a UDI url (ex: umb://media/c186fd98c0d74a95ac61be1d8f051fa9). It would be great if it was instead shown as a thumbnail of the actual image.

**Comment by hfloyd** [comment]
Perhaps related somewhat to https://github.com/umbraco/Umbraco-CMS/issues/5545

**Comment by skttl** [comment]
Maybe you could be able to add a template for the column here:
![billede](https://user-images.githubusercontent.com/3726467/65267435-43373b00-db15-11e9-8871-ccf50a8d9345.png)

Like the name templates in Nested Content.

**Comment by hfloyd** [comment]
Hi @skttl . I'm not familiar with how to do that... Do you have an example or reference? Thanks!

**Comment by skttl** [comment]
@hfloyd from the docs:
```
...as well as a template for generating list item labels using the syntax {{propertyAlias}}.

    If you would like to include the index position in the label, you can use {{$index}}.
    If your property links to a content, media or member node, you can use the Angular filter {{ pickerAlias | ncNodeName }} to show the node name rather than the node ID.
    If your property is a rich text editor, you can use the Angular filter {{ pickerAlias | ncRichText }} to show the unformatted text.

```

https://our.umbraco.com/Documentation/Getting-Started/Backoffice/Property-Editors/Built-in-Property-Editors/Nested-Content/

The benefits of this, is that it could also be used to manipulate other values, like large text areas, content pickers etc.

**Comment by nul800sebastiaan** [comment]
Thanks @hfloyd - I think it's not just somewhat related to #5545 - it's the same issue, there's a UDI and something clever needs to be done with it, we know already if it's a media or a content item from the UDI. I'll close this and update the other issue with some more info.

**Comment by hfloyd** [comment]
@skttl Thanks for the reference... But that is for the NestedConent - I have used data templates for that... I am talking about ListViews... The config for which doesn't include a "Template" option. It seems that I'd perhaps have to look into creating a custom Layout (as per https://24days.in/umbraco-cms/2016/custom-list-view-layouts/) Unless I am missing something here?

**Comment by skttl** [comment]
@hfloyd  I was thinking list views too - but as a feature request. I hope I can get it working myself, then I'll submit a PR.

**Comment by hfloyd** [comment]
Ah, yes, that would be awesome!

~Heather

Sent from my phone

________________________________
