### ISSUE TITLE
Only load in media thumbnails when the media item is in in the view port - else CPU Spike

### ISSUE THREAD

**Issue by Shazwazza** [umbraco/Umbraco-CMS#6389]
If you have a lot of images in a single folder and then you browse to that folder, or you want to choose one of these images with the media picker, Umbraco will try to load in **all** thumbnails eagerly. This means that you'll see an immense amount of requests for `GetBigThumbnail` ... which is actually going to go resize your original images (if it hasn't done this already) which means your server is going to have an enormous CPU spike until all requests are processed, these requests will keep trying to load even if you manage to navigate away from the media picker or trying to view the folder.

Reproduction
------------

### Steps to reproduce

Create a lot of media items in a single folder. One way to do this is to have another folder with a bunch of images (like 50) and then just keep copying these into another folder until that other folder has a substantial amount of images. 

In theory, even 50 is too many to load in all thumbnails eagerly but the problem gets much worse the more images you have. 

### Expected result

Ideally when browsing to this folder, or when trying to select one of these images with the media picker, it would only try to load the thumbnail for these images when the user scrolls them into view so that resize requests are only made when necessary.

### Actual result

**All** thumbnails for the folder are loaded eagerly. This will heavily impact the performance of the server, this will also mean that the UI is in a slow/stalled state until all of these requests are processed and the user can't really pick or see anything. Even if you manage to close the media picker or navigate away, the resize requests will continue since they've already been initiated.

**Comment by kjac** [comment]
I may have a simple solution for this... I'll give it a go at today's hackaton 👨‍💻👩‍💻

**Comment by kjac** [comment]
PR in #6510
