### ISSUE TITLE
[v8] Bug when publishing the HomePage

### ISSUE THREAD

**Issue by bv-it** [umbraco/Umbraco-CMS#6399]
Hello
(Здравствуйте)

If the site contains more than 1000 pages, the publication of the main page takes 1-2 minutes. SQL version. Umbraco 8.1.4.
(Если сайт содержит более 1000 страниц, то публикация главной страницы выполняется 1-2 минуты. SQL версия. Umbraco 8.1.4.)

guess: the publishing process starts not only for the HomePage
(догадка: начинается процесс публикации не только для главной страницы)

Note: "Save" operation is fast 1-2 seconds
Замечание: операция "Сохранить" происходит быстро 1-2 секунды

**Example:**
![image](https://user-images.githubusercontent.com/16698614/65344993-c6be5e00-dbe1-11e9-8351-03f6c90f5131.png)

**Sometimes received an exception before updating Umbraco to 8.1.4 (Umbraco 8.0.2):**
(Иногда получали исключение до обновления Umbraco до 8.1.4 (Umbraco 8.0.2))

Exception Umbraco 8.0.2:
[InvalidOperationException: Unable to resolve type: Umbraco.Web.Cache.DistributedCache, service name: ]
   System.Web.HttpApplication.RegisterEventSubscriptionsWithIIS(IntPtr appContext, HttpContext context, MethodInfo[] handlers) +838
   System.Web.HttpApplication.InitSpecial(HttpApplicationState state, MethodInfo[] handlers, IntPtr appContext, HttpContext context) +168
   System.Web.HttpApplicationFactory.GetSpecialApplicationInstance(IntPtr appContext, HttpContext context) +277
   System.Web.Hosting.PipelineRuntime.InitializeApplication(IntPtr appContext) +369

[HttpException (0x80004005): Unable to resolve type: Umbraco.Web.Cache.DistributedCache, service name: ]
   System.Web.HttpRuntime.FirstRequestInit(HttpContext context) +532
   System.Web.HttpRuntime.EnsureFirstRequestInit(HttpContext context) +111
   System.Web.HttpRuntime.ProcessRequestNotificationPrivate(IIS7WorkerRequest wr, HttpContext context) +724

![image](https://user-images.githubusercontent.com/16698614/65345267-827f8d80-dbe2-11e9-9943-c05c8846eaa0.png)

**Comment by saifobeidat** [comment]
I have faced this issue, and there is a workaround for it 
[https://our.umbraco.com/forum/umbraco-8/98737-saving-and-publishing-the-website-root-takes-a-long-time-to-finish-umbraco-8#comment-311619](url)

Another quick solution, if you have content in the home page and you need to update it, you can make the home page as a child of the root then make the root's template take the needed data from that new home page.

**Comment by bv-it** [comment]
Thanks. We did that a few days ago (temporary solution). It works. :)
(Спасибо. Мы сделали это несколько дней назад (временное решение). Все работает :) )

Now we are waiting for an official decision from the developers Umbraco.
(Теперь мы ждем официального решения от разработчиков Umbraco)

![image](https://user-images.githubusercontent.com/16698614/65431141-a977d280-de21-11e9-91cf-0219c25d3af9.png)

**Comment by Shazwazza** [comment]
I believe this is fixed in 8.2 with this fix https://github.com/umbraco/Umbraco-CMS/issues/5362, https://github.com/umbraco/Umbraco-CMS/pull/5439

there could be more optimizations probably with this https://github.com/umbraco/Umbraco-CMS/issues/5474 but i believe the main cause is already fixd in #5362

**Comment by nul800sebastiaan** [comment]
@bv-it - As Shannon mentions, this should be fixed in version 8.2.0 which will be out next week. You can try out the release candidate of 8.2.0 now if you want to test that the performance has improved: https://our.umbraco.com/download/releases/820/
