### ISSUE TITLE
Culture and host names will not accept two level domain name

### ISSUE THREAD

**Issue by bachicool** [umbraco/Umbraco-CMS#6405]
When assigning domains from the backoffice URL with two levels javascript give error as "invalid domain format"  
This is error in the regex of '\Umbraco_Client\Dialogs\AssignDomain2.js' 
```
$.validator.addMethod("domain", function (value, element, param) {
                // beware! encode('test') == 'test-'
                // read eg https://rt.cpan.org/Public/Bug/Display.html?id=94347
                value = punycode.encode(value);
                // that regex is best-effort and certainly not exact
                var re = /^(http[s]?:\/\/)?([-\w]+(\.[-\w]+)*)(:\d+)?(\/[-\w]*|-)?$/gi;
                var isopt = this.optional(element);
                var retest = re.test(value);
                var ret = isopt || retest;
                return ret;
            }, self._opts.invalidDomain);
```
When the same domain is added in the SQL table 'umbracoDomains' URL's are generated as anticipated.  

![image](https://user-images.githubusercontent.com/574356/65386754-dde88180-dd82-11e9-9009-ae256fec8e45.png)

Reproduction
------------
 * Add Domain name  http://exampledomain.com/level1/level2 from 'Culture and hostnames' in the back office.
* Gives as a 'Invalid domain format' 

### Expected result
Able to add domains with more than one level. 

### Actual result
Not able to add domains more than two levels.

**Comment by nul800sebastiaan** [comment]
As you can read in the description above this field: 

> One-level paths in domains are supported, eg. "example.com/en". However, they should be avoided. Better use the culture setting above.

If you are changing this in the database then please be aware that this is completely unsupported and might give unexpected results in the future.

We recommend you set up a good node structures with the names you need to build the URLs properly.
