### ISSUE TITLE
[v8] Bug. Default Value for DateTimePicker.

### ISSUE THREAD

**Issue by bv-it** [umbraco/Umbraco-CMS#6407]
Hello
(Здравствуйте)

Umbraco 8.1.4 does not allow you to set a default value for the DateTimePicker (when is this required field).
(Umbraco 8.1.4 не позволяет установить значения по умолчанию для DateTimePicker (когда это обязательное поле))

"Default Value for DateTimePicker" - used frequently. For example, when publishing news.
(Значение по умолчанию для выбора даты - используется часто. Например, когда публикуются новости)

![1](https://user-images.githubusercontent.com/16698614/65410501-35263a80-ddf3-11e9-9f17-2b72f10d605d.png)

or you can add an extension for the DateTimePicker (Example from C1 CMS):
(или можно добавить расширение для DateTimePicker. Пример из C1 CMS)

![image](https://user-images.githubusercontent.com/16698614/65410929-3e63d700-ddf4-11e9-9571-6d00c969e77d.png)

**Comment by nul800sebastiaan** [comment]
We recommend using `EditorModelEventManager` for that. Here's some documentation: https://our.umbraco.com/documentation/reference/events/EditorModel-Events/

**Comment by bv-it** [comment]
thanks, it works. But it is difficult for a simple "Set Default Value" operation :)
(Спасибо, работает. Но это немного сложно для простой операции "Добавить значение по умолчанию". :))
