### ISSUE TITLE
V8: "panic: no more children" on Save and Publish

### ISSUE THREAD

**Issue by stevemegson** [umbraco/Umbraco-CMS#6419]
In the latest v8 code, I see a "panic: no more children" exception when publishing a document which is a "middle child" of its parent.

The problem appears to be the handling of generations in `ContentStore.AddTreeNodeLocked`. The code steps through the linked list of the siblings looking for the right place in the sort order to insert `content`. However, in the generation we're looking at this linked list contains a version of `content` which has had its `PreviousSiblingContentId` and `NextSiblingContentId` set to -1. This makes the loop end before finding the right place to insert `content`, leading to the "we should never get here" situation.

Rather than using the current generation of the parent node, I think we need to use the current generation of `content`, so that we get the generation in which `content` has been removed from the tree. Can we always assume that some current generation of `content` exists, or do we need to check and possibly to fallback to `parentLink.Gen`?

Although they're not directly causing this exception, while investigating I found a couple of other bits which I think need to change:
- In `ContentStore.Set`, we set `kit.Node.NextSiblingContentId` but not `kit.Node.PreviousSiblingContentId`.
- In `RemoveTreeNodeLocked`, I'm not sure that we should be resetting `content.NextSiblingContentId` and `content.PreviousSiblingContentId` to -1. We're modifying the existing generation here, not setting up the new version.

---
_This item has been added to our backlog [AB#2848](https://umbraco.visualstudio.com/243e7927-03b2-44e2-908f-d4ac7ea5daaa/_workitems/edit/2848)_

**Comment by Shazwazza** [comment]
I had planned to work on this tomorrow, thanks for reporting 🎉 there's been some changes in vlatest in the last couple months with this code so have had a regression. Will add some unit tests for it.

**Comment by Shazwazza** [comment]
PR is here https://github.com/umbraco/Umbraco-CMS/pull/6422
