### ISSUE TITLE
Images can be added even though they are not allowed (RTE Copy/Paste/Drag and drop)

### ISSUE THREAD

**Issue by hemraker** [umbraco/Umbraco-CMS#6424]
### Bug summary
Images can be inserted and uploaded to the media library with "Insert Image" functionality disabled. 

### Specifics
Umbraco Version: 8.2 pre-release (https://github.com/umbraco/Umbraco-CMS/tree/aafa314f0e1d5097c9beec3a7fab970da5e9c31e)

### Steps to reproduce
1. Disable the "Insert Image" functionality on a Rich Text Editor Data Type
2. Go to a content node where the Data Type is used
3. Drag/Drop or Copy/Paste an image file into the RTE

### Expected result
Image is not inserted

### Actual result
Image is inserted and uploaded to the Media Library on Save/Publish

---
_This item has been added to our backlog [AB#2881](https://umbraco.visualstudio.com/243e7927-03b2-44e2-908f-d4ac7ea5daaa/_workitems/edit/2881)_

**Comment by warrenbuckley** [comment]
Will be fixed in this PR #6446
