### ISSUE TITLE
Difficult to change listview layout in content section

### ISSUE THREAD

**Issue by bjarnef** [umbraco/Umbraco-CMS#6430]
In content section it is difficult to change listview layout, because it open the "Content" navigation dropdown even you don't hover this button.

Reproduction
------------

### Bug summary

In starterkit on Blog node try change listview layout from grid to list layout. It open the dropdown for "Content" navigation before you are able to click the listview layout selector.

### Specifics

Umbraco v8.2.0 (latest codebase in `v8/dev` branch.
Chrome Version 77.0.3865.90

### Steps to reproduce

In starterkit on Blog node try change listview layout from grid to list layout. It open the dropdown for "Content" navigation before you are able to click the listview layout selector.

### Expected result

It should be possible to click the listview layout selector to change listview layout - just like in media and member section.
The dropdown for "Content" navigation item, should only open when hover the actual navigation item.

### Actual result

The dropdown menu for "Content" navigation open before you are able to click the listview layout selector.

![2019-09-25_21-48-15](https://user-images.githubusercontent.com/2919859/65634370-60b94880-dfde-11e9-80c0-3bd994c0f0b3.gif)

**Comment by bjarnef** [comment]
It seems the dropdown is shown when hover this highligted area.

![image](https://user-images.githubusercontent.com/2919859/65634463-8e9e8d00-dfde-11e9-888b-e3d1afbc2de1.png)

**Comment by nathanwoulfe** [comment]
Problem is due to the hidden list being hidden via opacity, so the element is still present in the DOM and taking up space in the flow - even though the :hover state is applied by hovering the Content button, the list, as a descendant node, can still be hovered.

**Comment by nul800sebastiaan** [comment]
Fixed in https://github.com/umbraco/Umbraco-CMS/pull/6433
