### ISSUE TITLE
Remove the leftover code from the legacy MacoContainer datatype

### ISSUE THREAD

**Issue by nul800sebastiaan** [umbraco/Umbraco-CMS#6467]
As discovered through PR https://github.com/umbraco/Umbraco-CMS/pull/6350 - we didn't intend to ship with code for the MacroContainer datatype.

The old code supporting this datatype needs to be removed, it quite broken at the moment anyway. 

We'd love some help with this.

**Comment by Kerl1310** [comment]
I'm happy to pick this up

**Comment by Kerl1310** [comment]
@nul800sebastiaan Opened a PR for this

**Comment by nul800sebastiaan** [comment]
Fixed in https://github.com/umbraco/Umbraco-CMS/pull/6518
