### ISSUE TITLE
V8: current node variant has no language when content is invariant (backoffice)

### ISSUE THREAD

**Issue by nathanwoulfe** [umbraco/Umbraco-CMS#6469]
The model for a content node in the backoffice includes an array of content variants - one per language, even if the node is invariant. Each of those variants has a language property, which contains useful info about that variant - things like culture, fallback language, is default and is mandatory flags, and a friendly display name.

That's good - it's a consistent and predictable pattern.

If however the content node is invariant, we still have the array of variants (this time though length === 1), but the language property is null on that single variant. 

That's not good if we've assumed the model will be consistent.

I'd expect the invariant node would return the default language information to maintain that consistent, predictable pattern - node has n variants, variants have 1 language. The variant absolutely still has a language, so the property should not be null.

I'm currently working around that gap by adding the default culture to the ServerVariables collection (would be nice if it was here by default too), but feel like it should be returned as part of the variant object.

Reproduction
------------

To reproduce, create a variant and invariant node in a v8.1.x install.

- visit the variant node, smash that F12 button
- inspect the GetById?=n request
- expand the variants property, expand the first object, verify has a language object. Happy devs!
- visit the invariant node, smash that F12 button again
- inspect the GetById?=n request
- expand the variants property, expand the first (and only) object, verify language is null. Weep.

**Comment by nul800sebastiaan** [comment]
I am guessing either it's an oversight or the thinking was: you haven't actually explicitly set a language, you're just using the default.
I'll ask around!

I wonder how big of a breaking change it would be to change it now.. 🤔 I guess not many people are actually using this info now, so shouldn't be too bad. What would you like to use it for?

Does it help to set the culture on the root node ("Culture and Hostnames"), to make it explicit?

**Comment by nathanwoulfe** [comment]
Alternative too is that there is a very good reason that it is null...

Even if I'm using the default, it would be good for it to be populated, so I know what the default is. Can probably grab it from the query string mculture, assuming that is always available, but still need to check the variant object first. 

I need it for some UI stuff in Plumber - I'm supporting variant workflows, so need to access the culture for the current active variant to kick off the correct workflow. 

It's not a huge issue, probably more interested in if there was a conscious design decision to leave it null...

**Comment by nul800sebastiaan** [comment]
Ah, you're right, Shannon says from the top of his head it's because it clearly indicates an invariant node. And I see the problem now: a node can be variant, but there's possibly only 1 language set up.
In that case there is no other distinction between it being variant or not.

I will close this for now and would advise you to get the installed languages from `LocalizationService.GetAllLanguages` if the language for your node is null.

**Comment by nathanwoulfe** [comment]
That makes sense - I might still work something up to include the default language in the umbracoSettings object on ServerVariables, just for convenience...

**Comment by nul800sebastiaan** [comment]
Hmm, I guess it's already ALMOST in the server variables, I don't think we'd want to add anything else, this is already available: 

```
                            "languageApiBaseUrl", _urlHelper.GetUmbracoApiServiceBaseUrl<LanguageController>(
                                controller => controller.GetAllLanguages())
```
