### ISSUE TITLE
Preview mode unable to retrieve other pages from cache

### ISSUE THREAD

**Issue by SteveVaneeckhout** [umbraco/Umbraco-CMS#6472]
### Bug summary

Since Umbraco 7.15.0 we are unable to use the preview function in at least 3 of our websites. While loading the previewed page I try to retrieve other pages using `content.AncestorOrSelf()` or `content.Siblings()` and I receive null or unexpected results (see screenshots).

### Specifics

- 7.15.0 up to 7.15.3
- The bug disappears when `Umbraco.Preview.Mode` is set to `Legacy`

![RenderModel](https://user-images.githubusercontent.com/6131869/65882899-442e5f00-e396-11e9-97cb-04fccb10e6c3.png)

![Siblings](https://user-images.githubusercontent.com/6131869/65882898-442e5f00-e396-11e9-874c-1d11b53abcb9.png)

This is interesting, only previously previewed pages are showing up in the list but the page with ID 1050 should **not** be a sibling.

![db-cmsPreviewXml](https://user-images.githubusercontent.com/6131869/65882897-4395c880-e396-11e9-9ef3-02ed7df0acd4.png)

### Expected result

A webpage that loads in successfully without exceptions.

### Actual result

NullReferenceException in the code that runs fine outside the preview mode.

**Comment by nul800sebastiaan** [comment]
I'm not sure how the new preview functionality works, but I'll talk to the team and see how it is intended to work.

**Comment by stevemegson** [comment]
There should be a row in cmsPreviewXml for every page, and the new preview builds its XML cache entirely from that table. With only those three rows available. it looks like it ends up placing all three nodes as siblings under the root element because it can't make sense of the parentID values.

The legacy preview starts from the published XML cache and looks in cmsPreviewXml for just the previewed node and its descendants, so it will behave reasonably even if the previewed node is the only row in cmsPreviewXml. If the descendants aren't there, you'll just see their published versions in preview.

@SteveVaneeckhout, I'd guess that at some point you've set up some process to periodically clear cmsPreviewXml to save space in the database. Until 7.15, this would have been (mostly) safe.

Unfortunately I don't think there's a nice way to rebuild cmsPreviewXml. We could perhaps add a health check to the Data Integrity group.

**Comment by SteveVaneeckhout** [comment]
I've only cleared out the cmsPreviewXml table after we started to have issues. How does the table get filled up correctly? Websites that were created before 7.15 don't have a complete cmsPreviewXml table AFAIK.

**Comment by stevemegson** [comment]
cmsPreviewXml should be updated whenever content is saved. I believe that's been true for as long as cmsPreviewXml has existed.

There's some old code to rebuild cmsPreviewXml lurking in `/umbraco/dialogs/republish.aspx?previews=true`. It's using code which is deprecated in V7, and I doubt it'll be fast, but it should do the job.

**Comment by warrenbuckley** [comment]
Hello @SteveVaneeckhout 
I am trying to reproduce your error with a clean Umbraco 7.15.0 site with the Starter Kit installed through the next, next, next install wizard process.

As you can see from my screenshot and code snippet I am unable to reproduce with a Null.

![image](https://user-images.githubusercontent.com/1389894/72610316-ef036280-391e-11ea-9b96-ba54b9d3d38f.png)

## My Repro
I have used the example code below with the default starter kit in Umbraco 7.15.0 and I have not set or added the AppSetting key `Umbraco.Preview.Mode` to override the out of the box value

```cs
using System.Globalization;
using System.Web.Mvc;
using Umbraco.Core.Models;
using Umbraco.Web.Models;
using Umbraco.Web.Mvc;

namespace Umbraco.Web.UI
{
    public class ContentPageController : RenderMvcController
    {
        public override ActionResult Index(RenderModel model)
        {
            // we will create a custom model
            var myCustomModel = new BaseRenderModel(model.Content, model.CurrentCulture);

            //return CurrentTemplate(myCustomModel);
            return base.Index(myCustomModel);
        }
    }

    public class BaseRenderModel : RenderModel
    {
        public IPublishedContent HomePage { get; set; }
        public string HomeName { get; set; }

        public BaseRenderModel(IPublishedContent content, CultureInfo culture) : base(content, culture)
        {
            // HomePage from AncestorOrSelf does not give me a null
            HomePage = content.AncestorOrSelf("home");
            HomeName = HomePage.Name;
        }
    }
}
```
### ContentPage.cshtml
```razor
@inherits Umbraco.Web.Mvc.UmbracoViewPage<Umbraco.Web.UI.BaseRenderModel>
@{
    Layout = "Master.cshtml";    
}

@Html.Partial("~/Views/Partials/SectionHeader.cshtml")

<h2>@Model.HomeName</h2>
<h3>@Model.HomePage.NiceUrlWithDomain()</h3>

<section class="section">

    <div class="container">

        <div class="col-md-3">
            <nav class="nav-bar nav-bar--list">
                @Html.Partial("~/Views/Partials/Navigation/SubNavigation.cshtml")
            </nav>
        </div>

        <div class="col-md-9">
            <article>
                @Html.GetGridHtml(Model.Content, "bodyText", "bootstrap3-fluid")
            </article>
        </div>
    </div>

</section>

```

## Questions
Are you able to give me exact steps on how to reproduce this @SteveVaneeckhout please
Have you tried on a clean 7.15.0 site for comparison to see if this is specific to an individual site?

**Comment by stevemegson** [comment]
@warrenbuckley I don't think you'll reproduce these specific errors without manually clearing the `cmsPreviewXml` table. I suspect that the original problems may have been related to #6629 incorrectly removing items from the XML cache. Then clearing out `cmsPreviewXml` in an attempt to fix those problems has led to the even weirder problems like nodes appearing as siblings when they shouldn't be.

**Comment by SteveVaneeckhout** [comment]
@stevemegson No, we were able to recreate the issue with a new project (no starterkit) and creating 2 very simple doctypes. I'll try to dig up the code or recreate the project. But the source of the issue is definitely not because of manually clearing the cmsPreviewXml.

**Comment by SteveVaneeckhout** [comment]
I've attached the project in this post. The error happens when previewing the same page for a second time after other pages have been added. These are the instructions for a repro:

1. Open the solution in Visual Studio (If you get missing Roslyn errors: Build -> Clean Solution -> Rebuild Solution)
2. Start debugging
3. Install Umbraco, custom install, SQL Server Compact, NO starter kit.
4. Install local package Bugtester.zip. This creates 1 data type for MNTP, 2 document types and 3 templates
5. Create node under root of type "website" and name it "Website", then Save & Publish
6. Create a subnode "A", of type "ContentPage", then Save & Publish
7. Create a subnode "B", of type "ContentPage", then Save & Publish
8. On Website add A & B to the menuList control, then Save & Publish
9. Now preview subnode B
10. A & B will be listed as expected
11. Create subnode C & D
12. Update Website and add C & D to the MenuList
13. Preview subnode B again
14. Notice only A, B will be listed while A, B, C & D would be expected

[PreviewExample.zip](https://github.com/umbraco/Umbraco-CMS/files/4090469/PreviewExample.zip)

**Comment by warrenbuckley** [comment]
@SteveVaneeckhout in our latest V7 branch I am unable to reproduce this - see attached screenshot
![image](https://user-images.githubusercontent.com/1389894/74018522-f7831200-498d-11ea-8d6c-eb4fd708545b.png)

**Comment by SteveVaneeckhout** [comment]
In that case, I could repro by doing:
- Add another 2 subpages: E, F
- Add E and F links on website
- Preview E

**Comment by warrenbuckley** [comment]
I really can't repro this @SteveVaneeckhout 

![image](https://user-images.githubusercontent.com/1389894/74918316-d1636600-53c0-11ea-8a1c-ac1409a50719.png)

![image](https://user-images.githubusercontent.com/1389894/74918566-28693b00-53c1-11ea-8237-2943202fd29b.png)

Nodes E & F are saved (not published)
Website node picked E & F and that is saved (not published)
Preview E - Get 6 nodes listed

I have zipped up my copy of the solution where this is working _(Link lasts a week)_
https://we.tl/t-FDWzxMhGe2

**Comment by SteveVaneeckhout** [comment]
I've made a video: https://youtu.be/Cd7RUP6Xvrs

Unexpected to me, the first time I use the preview it already fails to display A.

**Comment by stevemegson** [comment]
I can reproduce this now. The problem seems to be that Save and Publish doesn't update the in-memory preview cache. `UnpublishedPageCacheRefresher.Refresh` calls `content.Instance.UpdatePreviewXmlContent`, but `PageCacheRefresher.Refresh` does not.

It'll work as expected if the preview cache doesn't exist when the page is published, or if the cache expires before previewing the other page. `cmsPreviewXml` is updated properly, so reloading the cache from the database will include the missing pages.

**Comment by dawoe** [comment]
I was able to reproduce this as well. I created a PR that fixes this behavior.

**Comment by nul800sebastiaan** [comment]
Fixed in https://github.com/umbraco/Umbraco-CMS/issues/6472

**Comment by Nicholas-Westby** [comment]
@nul800sebastiaan Did you mean to link to a pull request (rather than linking back to this issue)?

**Comment by Nicholas-Westby** [comment]
Perhaps this one? https://github.com/umbraco/Umbraco-CMS/pull/8636

**Comment by nul800sebastiaan** [comment]
Haha! Thank you, yes, meant to say fixed in https://github.com/umbraco/Umbraco-CMS/pull/8636 😅

**Comment by AafaanJii0** [comment]
hi,

preview does not work (umbraco 13) in my live env deployed on azure with front door ( 2 app services) and waf. Tried on edge browser it worked for me 4-5 times but after that again does not display the latest content rather the old one. However on my staging env(also deployed on azure) it works fine where my stage does not use any Front door and waf.
