### ISSUE TITLE
Use a Regex match to test for blob images in SetContent in TinyMCE

### ISSUE THREAD

**Issue by nielslyngsoe** [umbraco/Umbraco-CMS#6476]
I would like us to stop using indexOf in the TinyMCE service(on line 1290 in tinymce.service.js), when testing content for images with Blob data in the 'src'-attribute.
The current is potentially is sensitive to casing, white-space characters and to the fact that the src attribute is the first attribute of a IMG-element.

We need to avoid potential errors by replacing this with a Regex match test.

**Comment by nul800sebastiaan** [comment]
Fixed in https://github.com/umbraco/Umbraco-CMS/pull/6548
