### ISSUE TITLE
Umbraco 8.2-rc Publish Menu underneath reorder

### ISSUE THREAD

**Issue by KevinJump** [umbraco/Umbraco-CMS#6478]
Umbraco 8.2.0-rc install (via nuget)

Publish Menu is hidden beneath the re-order menu of grid property control. 

![image](https://user-images.githubusercontent.com/431231/65903715-d5acc980-e3b4-11e9-8c49-f2c71205ce06.png)

**Comment by KevinJump** [comment]
already fixed ? https://github.com/umbraco/Umbraco-CMS/commit/885f0f0caec8cf77e2fd57c173033ea2d586ffcb 
(just not in the RC branch?)

**Comment by nul800sebastiaan** [comment]
Correct, that one didn't make it for 8.2, fixed indeed :)
