### ISSUE TITLE
Umbraco 8.2.0-rc group dropdown appears over list view buttons

### ISSUE THREAD

**Issue by KevinJump** [umbraco/Umbraco-CMS#6479]
In Umbraco 8.2.0-rc The content group drop-down appears when you hover near it 

this means it appears over buttons such as those in the list view, meaning you can accidentally click the menu when you are trying to click a button 

![menuhover](https://user-images.githubusercontent.com/431231/65904001-6d121c80-e3b5-11e9-9503-c3ed82ec70d6.gif)

_checked - this is not an issue in 8.1.5_

**Comment by nul800sebastiaan** [comment]
This one is also (https://github.com/umbraco/Umbraco-CMS/issues/6478) already fixed after 8.2.0 but I can't find the issue any more 🙈 

Thank you kindly for the report though! 👍 ⭐

![6479](https://user-images.githubusercontent.com/304656/65916777-37c9f680-e3d6-11e9-926a-8c9bd08ba256.gif)

**Comment by ronaldbarendse** [comment]
This is the same as issue https://github.com/umbraco/Umbraco-CMS/issues/6430 and is fixed in PR https://github.com/umbraco/Umbraco-CMS/pull/6433 (tagged for 8.3.0). Would be nice if this can also be merged into the next 8.2 patch release!

**Comment by nul800sebastiaan** [comment]
This will be available in 8.2.1 indeed. See #6433 👍
