### ISSUE TITLE
Issue naming a project!

### ISSUE THREAD

**Issue by Chewbacca222222** [umbraco/Umbraco-CMS#6494]
Bit of a weird one here, not sure if anyone has had this issue before!

Reproduction
------------
### Bug summary
If you name a new Visual Studio project "imageProcessor" Umbraco will build but errors as soon as you open it in a browser!

### Steps to reproduce
1. Create a new Visual Studio Asp.net Web Application (.net 4.7.2) and name it "imageProcessor"
2. Leave the project empty and navigate to Nuget, install Umbraco CMS (8.1.5) - To note this seems to take longer than usual?
3. Clean & build or dont the error occours in both cases!
4. Now Run the project using IIS Express - I use Google Chrome
5. Yellow screen of death

### Thoughts
Im not entierly sure why it fails to run, but my best guess is that because the project is named "imageProcessor" it clashes at some point with the package "imageProcessor". I did get in contact with someone at Umbraco and they had similar issues but their project didnt even build, they advised me to post it here!

Hope I can help ❤️

**Comment by nul800sebastiaan** [comment]
Hi there @Chewbacca222222 ! 

Yep, unfortunately you will have the same trouble if you name your project `Umbraco` or `NetwonSoft.Json`. These project names will produce dlls that already exist in the bin folder and create a conflict. This is a Visual Studio limitation and not something we can do anything about I'm afraid, the only advice I have is to not name your project after an existing dll in your bin folder! 👍
