### ISSUE TITLE
v7 Bulk move / copy on listview doesn't update listview styles

### ISSUE THREAD

**Issue by netaddicts** [umbraco/Umbraco-CMS#6499]
Related to #5936 and #5907, same behaviour can be found (list view not updating) after performing bulk copy or move.

Still an issue in v7.15.3

### Bug summary

List view doesn't update after performing a bulk copy or bulk move.

### Specifics

Happens on latest v7 v7.15.3

### Steps to reproduce

Create a doc type A with any textstring property. Create another document type B and configure as list view and allow to be created at root. Allow doc type A as child node type of doc B.

Create node of type doc type B, create multiple nodes of type doc type A.

Select one or more doc type A instances in list view, and click on 'Move' or 'Copy'. For 'Move' to be available, you need to configure the list view settings on doc type B.

### Expected result

After 'Copy' was completed, you should see the new nodes in the list view
After 'Move' was completed, you should no longer see the selected nodes in the list view.

### Actual result

List view hasn"t refreshed, for 'Copy' you can't see the new nodes in list view, for 'Move' you can still see the nodes in the list view

**Comment by hfloyd** [comment]
I just noticed this is also a UX issue with version 8.1.5 as well.

**Comment by nul800sebastiaan** [comment]
Fixed for v7 in https://github.com/umbraco/Umbraco-CMS/pull/6500
Cherry picked for 7.15.4 b05ef082fdb76e923b50461cad42d668b4ed5448
