### ISSUE TITLE
 UI: Option to put Label on top of property editor

### ISSUE THREAD

**Issue by nielslyngsoe** [umbraco/Umbraco-CMS#6502]
In order to be able to use full width for properties and keeping the Property Editor Label, Description and Property-Actions visible, we should create the ability to put the label on top.
This feature will accommodate the need for full width for the property editor, but still keeping the Label, Description and Property-actions available.

This will work as a great alternative to the "hide label" option we have today.

---
_This item has been added to our backlog [AB#6525](https://dev.azure.com/umbraco/243e7927-03b2-44e2-908f-d4ac7ea5daaa/_workitems/edit/6525)_

**Comment by skttl** [comment]
Yes please - but keep the Hide Label option, it has its uses :)

**Comment by ronaldbarendse** [comment]
I already commented on this earlier in PR https://github.com/umbraco/Umbraco-CMS/pull/6593 and agree with @skttl: keep the hide label option! Maybe the property editor should indicate whether this option should be exposed, but there are too many uses to remove it completely.

**Comment by nielslyngsoe** [comment]
@ronaldbarendse we do not remove a feature from one day to the other, in general, we don't. But a change starts by providing an alternative and then we will take it from there. :-)

**Comment by teeto** [comment]
What happened with this feature, any plans to include this on a future release?

**Comment by emma-hq** [comment]
Hey peeps - yep this is now a feature in latest releases. Check it out - 

![image](https://user-images.githubusercontent.com/78740801/110489149-0f741a80-80e7-11eb-8e54-0101036c91d6.png)


Enjoy!

Emma
