### ISSUE TITLE
Allow changing the language culture

### ISSUE THREAD

**Issue by rasmusjp** [umbraco/Umbraco-CMS#6503]
When you've added a Language under settings it's not possible to change the assigned culture, this could be problematic if for example you have built your website with `English (United States)` (which is the default language), but later realising it should have been `English` or `English (United Kingdom).

Right now you'd have to either write a migration script or go to the database and manually changing the culture, then rebuilding the database cache and the memory cache.

It would be nice if this was supported directly in the Backoffice

---
_This item has been added to our backlog [AB#3057](https://umbraco.visualstudio.com/243e7927-03b2-44e2-908f-d4ac7ea5daaa/_workitems/edit/3057)_

**Comment by ronaldbarendse** [comment]
This would be really nice indeed, but I already see at least 1 problem: how do we migrate cultures stored in property data, such as the JSON created by nested content or the grid editor?

**Comment by stevemegson** [comment]
Do nested content or the grid store culture details within their JSON? Won't each value be for a single culture, identified by the `languageId` column in the normal way?

**Comment by ronaldbarendse** [comment]
@stevemegson Indeed it does 😇 And although NC elements can be culture variant themselves, the UI currently doesn't support that (e.g. to keep the structure/items in sync between cultures and only make a property of the element culture variant)... This might change in the future, as it's also listed as a long term goal in https://github.com/umbraco/rfcs/blob/17be95b54b6b791fccfcf2b7a71d3f2290c26594/cms/0000-proteus-block-editor.md.

Anyway: if this feature gets implemented, it should work as expected (for all property editors) and be supported in the future.

An alternative approach would be to document how to change an existing language/culture, including the required rebuilding of the NuCache and Examine indexes, and add a warning about all the caveats (e.g. test before applying to a live/production website, etc.).
