### ISSUE TITLE
Pressing '1' or '2' inside a Tiny MCE Rich Text Area running in 'distraction free' mode causes the page to jump up to the top and 'focus' on  'Content' and 'Info' Content Apps

### ISSUE THREAD

**Issue by marcemarc** [umbraco/Umbraco-CMS#6508]
Using Umbraco 8.2RC

Create a Property based upon a Rich Text Area data type.
Set the data type to run in 'distraction free' mode
Type some text, and press the '1' key or the '2' key, the focus is removed from the rich text area (and if your editor is a little bit down the page the page will scroll up) and passed onto either the 'Content' or the 'Info' Content App Icon...

This is probably a recent accessibility change to allow you to toggle between the two using access keys, and probably something is added to tiny mce to prevent this happening when the numbers are entered into the rich text area, but the same workaround is not applied in 'distraction free mode'...

... but I am guessing...

I would expect the number 1 or the number 2 to appear inside the rich text area instead...

![image](https://user-images.githubusercontent.com/260802/65978093-fa637880-e46a-11e9-98f6-4a2a86462e65.png)

**Comment by nul800sebastiaan** [comment]
That is super weird, is it only in "distraction-free mode"? I did not realize we added hotkeys for the content apps and it is weird that both 1 and 2 trigger the switch to the info tab. Definitely something we need to fix soon!

**Comment by marcemarc** [comment]
yes distraction free mode only, it does not occur in classic mode..

**Comment by kjac** [comment]
Fixed in #7186
