### ISSUE TITLE
Tiny MCE Rich Text Editor doesn't appear on a page until you press ctrl-F5

### ISSUE THREAD

**Issue by marcemarc** [umbraco/Umbraco-CMS#6511]
Using Umbraco 8.2RC

If I add a Rich Text Area, either in Classic or Distraction Free Mode, to an existing page eg the 'Blog Post' Document type in the starter kit, then when I first visit that page, the Rich Text Area doesn't appear to load... and there isn't an error in the console either

![image](https://user-images.githubusercontent.com/260802/65978572-d81e2a80-e46b-11e9-8185-056f36387695.png)

if I press Ctrl-F5 on the page... the whole page loads again the 'Welcome to Umbraco Tour' popup appears, dismissing this,

![image](https://user-images.githubusercontent.com/260802/65979182-c38e6200-e46c-11e9-825f-498c8206a120.png)

 the Rich Text Area is displayed as expected...

![image](https://user-images.githubusercontent.com/260802/65979237-db65e600-e46c-11e9-9c41-e2948391ebca.png)

If I click to a different blog post, the same issue occurs again... so it is everytime the rich text editor is attempted to be loaded on the page.

If I create a brand new blog post, (eg no other content) same issue occurs.

If I create a new document type with only a single rich text editor field on same issue occurs...

Have toggled settings on the Rich Text Area, eg Image Upload Folder picked, not picked - Mode Classic or Distraction Free,  stylesheet, no stylesheet, and different Toolbar options, but always it fails on first load... I am running locally via Visual Studio though...
... 

---
_This item has been added to our backlog [AB#2995](https://umbraco.visualstudio.com/243e7927-03b2-44e2-908f-d4ac7ea5daaa/_workitems/edit/2995)_

**Comment by hemraker** [comment]
Thanks for reporting Marc 🙌 

This has been fixed in  #6496
