### ISSUE TITLE
Minor UI issue when choosing 'Image Upload Folder' for Rich Text Editor

### ISSUE THREAD

**Issue by marcemarc** [umbraco/Umbraco-CMS#6513]
When using Umbraco 8.2.RC

and choosing the Image Upload Folder for images to be saved in for a rich text area... it looks like you can select multiple folders, but only the first is selected.. just a minor UI thing... 

![image](https://user-images.githubusercontent.com/260802/65979981-2e8c6880-e46e-11e9-957d-3d9aeed3d641.png)

not sure if this is the sort of thing you want to know about! apologies if it feels picky (no pun intended)

---
_This item has been added to our backlog [AB#2996](https://umbraco.visualstudio.com/243e7927-03b2-44e2-908f-d4ac7ea5daaa/_workitems/edit/2996)_

**Comment by Shazwazza** [comment]
Thanks @marcemarc!

**Comment by Regicollis** [comment]
umbaco.controllers.js:2130 - dialogOptions.multiPicker is set to true. The value comes from $scope.model. We don't know where it is being set.
