### ISSUE TITLE
Dragging an image into the Rich Text Area, highlighting, then pressing 'Insert Image' toolbar icon triggers error

### ISSUE THREAD

**Issue by marcemarc** [umbraco/Umbraco-CMS#6516]
Using Umbraco 8.2RC

If as an editor you drag an image into a Rich Text Area, you might think you want to add 'alternate text' to your image.. straight after dragging and you are probably used to doing this, by highlighting the image, and pressing the 'insert image' icon on the rich text editor toolbar in order to bring up the 'alt text' option...

![image](https://user-images.githubusercontent.com/260802/65981753-b2941f80-e471-11e9-8efb-c8bf6377b287.png)

however if the page hasn't been saved then the 'image dragged into the rich text editor' isn't saved.. and triggers an error.

![image](https://user-images.githubusercontent.com/260802/65981884-f38c3400-e471-11e9-8a2d-c5298b9195bb.png)

perhaps the Insert Image toolbar icon should be disabled if the image that is currently highlighted is one that has been dragged in and hasn't been saved yet.... or the editor pressing the insert icon with the dragged image highlighted triggers the save and creation of the item in the media section? or at least there is a message explaining the page needs to be saved before the alt text can be entered to avoid the error?

---
_This item has been added to our backlog [AB#2997](https://umbraco.visualstudio.com/243e7927-03b2-44e2-908f-d4ac7ea5daaa/_workitems/edit/2997)_

**Comment by Shazwazza** [comment]
I think this YSOD might be caused by a merge issue, we'll need to check
