### ISSUE TITLE
Triggering of the 'Content' Content App 'quick link' menu rollover when you try to click a toolbar icon

### ISSUE THREAD

**Issue by marcemarc** [umbraco/Umbraco-CMS#6520]
When Using Umbraco 8.2RC and possibly earlier Umbraco 8's

If you are editing content in a rich text editor, and you move the mouse to select a toolbar item, eg to insert an image (why would you now right? - just drag it in granddad) ... then depending where the rich text editor is on the screen, instead of selecting your toolbar icon, you can trigger the 'Content Contant App' ribbon 'quick link' menu instead of the toolbar you are after!

![image](https://user-images.githubusercontent.com/260802/65982579-91343300-e473-11e9-97a2-8bc1b144d9b5.png)

which you'd sort of expect, but if it were positioned 'very close' to the ribbon, but the screenshot has quite a big gap and it still triggers...

![image](https://user-images.githubusercontent.com/260802/65982697-d3f60b00-e473-11e9-95ca-a33d7c0bc61b.png)

(is it clear in this second image, my mouse is trying to click the insert image toolbar, I'm not hovering over the Content Content App icon)

Would it be possible to stop the triggering of the 'quick link' menu if the mouse was also hovering over a toolbar icon of the rich text editor?

it's a pain to have to reposition the scroll in order to click the toolbar icon

or perhaps just reducing the 'target' area that triggers the 'quick link' menu will do the trick.

**Comment by nul800sebastiaan** [comment]
Thanks, this duplicates https://github.com/umbraco/Umbraco-CMS/issues/6479 and has been fixed a;ready! 👍
