### ISSUE TITLE
Missing Icons in Rich Text Editor Data Type Configuration

### ISSUE THREAD

**Issue by marcemarc** [umbraco/Umbraco-CMS#6521]
Using Umbraco 8.2.RC

The following three icons are missing from the Data Type Configuration pre value editor for the Rich Text Editor: (grid and datatype)

Image, Macro and 'Style Select'

![image](https://user-images.githubusercontent.com/260802/65983364-3a2f5d80-e475-11e9-9d60-fee2146a6a06.png)

does 8.2 include the switching out of font icons for SVGs? if so it might be these three were missed.

**Comment by nul800sebastiaan** [comment]
We haven't switched to SVG yet, so something weird is going on here! Thanks for reporting!

**Comment by nul800sebastiaan** [comment]
Fixed in https://github.com/umbraco/Umbraco-CMS/pull/6529
