### ISSUE TITLE
Default content dashboards loads 15mb image

### ISSUE THREAD

**Issue by skttl** [umbraco/Umbraco-CMS#6540]
At least use imagecropper to resize the image, please :)

![billede](https://user-images.githubusercontent.com/3726467/65998958-b6896700-e49c-11e9-9941-1ce97a64fb0f.png)

**Comment by nul800sebastiaan** [comment]
Yikes! We've reported it to the team who work on the dashboard, should be fixed soon.. Sorry about that! 🙈
