### ISSUE TITLE
 Umbraco.Core.UseHttps: true setting not honoured for HTTPS site.

### ISSUE THREAD

**Issue by John-Blair** [umbraco/Umbraco-CMS#6553]
The above setting is not honoured on my https site on Azure.
When you login using Chrome and look at the cookies, you will see that the default authentication cookie "yourAuthCookie" is only mar
[Umbraco does not honour Umbraco.Core.UseHttps true.pdf](https://github.com/umbraco/Umbraco-CMS/files/3680884/Umbraco.does.not.honour.Umbraco.Core.UseHttps.true.pdf)
ked as HttpOnly - but the Secure flag is not checked.
I display the value of this setting on one of my page so I am sure it it set to true - see screenshot attached.

**Comment by stevemegson** [comment]
@John-Blair Am I right in thinking that this is the cookie for member login? Are you seeing the correct behaviour for the `UMB_UCONTEXT` cookie when logging in to the backoffice?

**Comment by John-Blair** [comment]
@stevemegson , yes that is the one for member login. I am indeed seeing the correct behaviour for the UMB_UCONTEXT cookie when logging in to the backoffice.

Have i misunderstood its purpose - is it only meant to affect teh backoffice user and not the front end member? Thanks.

![image](https://user-images.githubusercontent.com/28809458/66062972-5943f300-e53a-11e9-93a7-58a8d3ea6982.png)

**Comment by stevemegson** [comment]
I think it should affect both, I was just checking that I'd understood which cookies were ignoring the setting. I think the member cookie has just been overlooked because it's not created in the same way as the other cookies, it should be a straightforward fix.

**Comment by John-Blair** [comment]
Yes, I think it would make sense to treat all login credentials with the Secure flag. Thanks.
FYI This would avoid man-in-the-middle attacks where the member cookie would be sent to an umbraco site if the user inadvertently used http:// in the address bar and relied on the server to redirect to https.

**Comment by nul800sebastiaan** [comment]
Yeah that would make sense, how are you logging in members?

**Comment by John-Blair** [comment]
v8.1.2:   Umbraco.Web.Security.Login

 This is a wrapper around forms authentication and uses the cookie name from the form element in the web.config
  <forms name="yourAuthCookie" loginUrl="login.aspx" protection="All" path="/" />

Thanks.

**Comment by stevemegson** [comment]
PR #6566 updates MembershipHelper, which solves the problem for the standard login form macro.

**Comment by nul800sebastiaan** [comment]
As mentioned in https://github.com/umbraco/Umbraco-CMS/pull/6566 - we will keep the default FormsAuthentication behavior, there are no changes necessary except for a web.config update on your part.

**Comment by John-Blair** [comment]
Ok. Although I'm thinking we should only have one setting to ensure secure cookies either the forms element requireSSL or the Umbraco.Core.UseHttps - having to set 2 items to achieve 1 thing is error prone and I'm sure lots of sites won't get it right. But you've made your decision so I'll code accordingly. Thanks.
