### ISSUE TITLE
ChildrenOfType (and related methods) look(s) at substring of the alias

### ISSUE THREAD

**Issue by rbottema** [umbraco/Umbraco-CMS#6571]
When using the method `ChildrenOfType`, I expect only children to be matched whenever the alias of the page matches exactly with the requested alias. Instead, the code also returns matches where the alias of the page is a substring of the requested alias.

### Steps to reproduce

* Make the following structure in Umbraco:
- Home (PageHome)
    - About Us (PageContent)
    - Some News (PageContentNews)
* On the PageHome template, call `var newsPage = Model.FirstChildOfType("PageContentNews")`
* Expected: 'Some News' is returned.
* Actual: 'About Us' is returned.

### Expected result
Page 'Some News' is returned.

### Actual result
Page 'About Us' is returned.

### Specifics

The bug is caused by the fact that the code calls `contentTypeAlias.InvariantContains(x.ContentType.Alias)`, instead of simply `contentTypeAlias == x.ContextType.Alias`. This bug exists in the newest version of the v8/dev branch, and affects at least all 8.1.x and 8.2.x versions:

https://github.com/umbraco/Umbraco-CMS/blob/1d94c4b9bbf026cc313bb04a561862ffe53fb033/src/Umbraco.Web/PublishedContentExtensions.cs#L886-L896

I suspect the bug was introduced because the signature of the method changed somewhere, as `string alias` was `params string[] alias` before. Both a string and an array have a `Contains` method, but they obviously mean something different.. If you confirm that this is indeed a bug, I will try to see if I can put a PR together.

**Comment by bjarnef** [comment]
As I remember there is a `InvariantEquals` extension method as well. I think it would be okay it not strict match on casing.

**Comment by nul800sebastiaan** [comment]
Yikes! Yep that seems like a bug, and great suggestion on `InvariantEquals` to fix it! 👍

**Comment by bjarnef** [comment]
We should also check if other of the extension methods use `InvariantContains` instead of `InvariantEquals` of if it only is specific to `FirstChildOfType`.

**Comment by rbottema** [comment]
I put together a quick PR in #6577.

**Comment by bjarnef** [comment]
It seems this affect some of this other extension methods as well since they rely on `ChildrenOfType`, e.g. `SiblingsAndSelfOfType`.

For some of the other extension methods we should
