### ISSUE TITLE
Sort hostnames in Culture and hostnames dialog

### ISSUE THREAD

**Issue by skttl** [umbraco/Umbraco-CMS#6591]
https://issues.umbraco.org/issue/U4-11558 - #3210
Last year I did a PR for this in v7 (#3295) and I would like to have this feature in v8. But it would be a breaking change, so before doing the work I would like to hear HQs opinion on this :)

**Comment by nul800sebastiaan** [comment]
I would say if you can do it without making it a breaking change then that would be great, You could remove the existing domain names and re-insert them in the correct order. Make sure to do the whole delete+insert in a transaction.

I do not know what the impact will be for Deploy though, but I'm guessing people do this manually now anyway (deleting them and then re-adding in the correct order) so it should hopefully not be a problem.

**Comment by skttl** [comment]
Sounds great, I'll see what I can do. My v7 PR had breaking changes though :)

**Comment by skttl** [comment]
By trying to fix this, I noticed that the urls are ordered before being returned to the ContentController here: https://github.com/umbraco/Umbraco-CMS/blob/3bfd9b71e290354744d677440983ecd06c5c0788/src/Umbraco.Web/Routing/DomainUtilities.cs#L282

Can that ordering be removed and have the list ordered by its original order?

**Comment by zpqrtbnk** [comment]
Quick note, ordering of the urls is important *in some places* so that if you define both "example.com/en" and "example.com" as hostnames, we try the longer one first when matching the current request - not sure it's relevant here, but just be careful.

**Comment by skttl** [comment]
I don't think that would be a problem, as the sorting is used to generate the url. All the hostnames should be able to match anyway.

**Comment by nul800sebastiaan** [comment]
As noted in PR https://github.com/umbraco/Umbraco-CMS/pull/6611#issuecomment-573586582 - we'll put this one on the list of ideas to implement in the future, we unfortunately can't do it now.
