### ISSUE TITLE
Images not rendering

### ISSUE THREAD

**Issue by kcflyhigh** [umbraco/Umbraco-CMS#6594]
I have upgraded to 7.15.2 from 7.1.4 and now have the following issue with images not rendering
 
image...
 
https://stage.www.boyerplanning.co.uk/media/112085/tough-mudder.jpg
 
thumbnail...
 
https://stage.www.boyerplanning.co.uk/283jpg/media/112085/tough-mudder.jpg
 
What’s the 283jpg in the url? The url generates a 404 with that in there!

The url above has the images dimension, i.e. 283, and mime type, i.e. jpg, in it’s path, i.e 283jpg, which is bizarre to me and is causing the url to be invalid and therefore 404, it should just be https://stage.www.boyerplanning.co.uk/media/112085/tough-mudder.jpg

Does anyone understand this, or had the same issue?

I'm new to Umbraco so apologies!

Kirsty

**Comment by nul800sebastiaan** [comment]
Hey there @kcflyhigh - this is not a URL that umbraco would generate out of the box, maybe you have some kind of filesystemprovider running or an eventhandler is doing something for you? 

I would recommend you try to get some further help on the forums where our friendly community can help you find the best solution for your requirements. 
Make sure to head on over to https://our.umbraco.com and ask follow up questions there! 👍

**Comment by kcflyhigh** [comment]
Hi,



FYI I finally got to the bottom of this issue…



Our Umbraco site has macros that are implemented as ‘user controls’, i.e. written in an ASP.NET project, imported in to Umbraco as .aspx and .dll files in \UserControls and \bin and then referenced as usercontrol files in Umbraco Macro Properties.



http://www.tothenew.com/blog/how-to-integrate-asp-net-custom-user-control-with-umbraco-cms/



Regards,



Kirsty



Kirsty Cameron
Developer

        [cid:image3e457f.JPG@b9364bb1.43a13d64] <https://www.lrg.co.uk/>
leaders.co.uk<http://www.leaders.co.uk> | romans.co.uk<http://www.romans.co.uk> | boyerplanning.co.uk<http://www.boyerplanning.co.uk>
qwerty1234567
[cid:image629703.JPG@931cb37e.4692b839]<http://www.lrg.co.uk>

Correspondence Address: Crowthorne House,
Nine Mile Ride, Wokingham, Berkshire, RG40 3GZ - Registered Address: Crowthorne House, Nine Mile Ride, Wokingham, Berkshire, RG40 3GZ. Registered in England 2161874. | At the Leaders Romans Group we take your data privacy seriously and invite you to view our privacy notice<http://www.lrg.co.uk/privacy>. | To see full disclaimer that applies to this email please click here<http://leadersromans.co.uk/email-disclaimer.htm>
