### ISSUE TITLE
ContentService.Deleting and ContentService.Deleted not raised when deleting a node in the backoffice UI

### ISSUE THREAD

**Issue by hartviglarsen** [umbraco/Umbraco-CMS#6606]
I expect to be able to run a piece of code when a node is deleted/about to be deleted in the Backoffice by subscribing to **ContentService.Deleting** and/or **.Deleted**. However, they do not appear to be raised when doing so (deleting from the Backoffice).

The events are raised when you delete content manually via **IContentService.Delete()**, though.

![bGOyCPg7cg](https://user-images.githubusercontent.com/4366314/66393609-4cf4e580-e9d3-11e9-9c3a-bc7b85412664.gif)

### Steps to reproduce

1. Create and register a component
2. Register to the events
3. Delete a (content) node from the backoffice
4. .... Nothing happens
5. Delete a node manually via the service API
6. Stuff happens

Tested with Umbraco 8.1.5.

**Comment by rasmusjp** [comment]
I think that's expected, when you "delete" in the content tree you are actually not deleting the content, you're moving it to the Recycle Bin and the `ContentService.Trashing` and `ContentService.Trashed` events are raised (it's calling `MoveToRecycleBin` when the item is not trashed).

If you delete the item from the Recycle Bin, both `ContentService.Deleting` and `ContentService.Deleted` should be raised.

**Comment by hartviglarsen** [comment]
Doh... You're correct. Guess I had a brain fart.. :-)
