### ISSUE TITLE
Remove usage of obsolete string extension method ToSHA1

### ISSUE THREAD

**Issue by prjseal** [umbraco/Umbraco-CMS#6620]
In the StringExtensions class, it says that the string extension method `.ToSHA1()` is now obsolete and may be removed in future versions. It advises the developer to use `.GenerateHash()` instead.

However, there are still usages of `.ToSHA1()` in the code base and they show up in the output window as warnings.

These need to be updated to use GenerateHash()

I have created a PR for this already.

**Comment by Shazwazza** [comment]
@nul800sebastiaan shouldn't this be marked as breaking?

**Comment by Shazwazza** [comment]
And marked for some release?
