### ISSUE TITLE
Pass in user id when using EmptyRecycleBin method

### ISSUE THREAD

**Issue by prjseal** [umbraco/Umbraco-CMS#6622]
When you build the core project you get warnings about needing to pass in the userId to the EmptyRecycleBin method as the method without userId in it is obsolete and marked as so.

There are 3 tests which use this method without passing the user in. If we update these then the messages will go away.

**Comment by nul800sebastiaan** [comment]
Thanks @prjseal !

Note: there's is no requirement any more to first create an issue and then add a PR, only a PR is just as good. 👍

**Comment by prjseal** [comment]
Thanks for letting me know about not needing to create the issue first.
