### ISSUE TITLE
EnableComposer and DisableComposer attributes only work for assemblies containing IComposer

### ISSUE THREAD

**Issue by ronaldbarendse** [umbraco/Umbraco-CMS#6624]
Following the [documentation](https://our.umbraco.com/documentation/implementation/composing/#disablecomposer--disable), you should be able to add a `DisableComposer` attribute to any assembly to disable a composer.

Going through the composing code, this attribute is only retrieved from assemblies containing at least one `IComposer`:

https://github.com/umbraco/Umbraco-CMS/blob/747a8cba2ef22a66c0f73cf7396a0ec50e5211e1/src/Umbraco.Core/Composing/Composers.cs#L243-L257

So this attribute might not always be 'seen' by the composing code (and thus not disable the composer)!

Reproduction
------------
### Bug summary
Disabling a composer using the `DisableComposer` assembly attribute does not work when used in an assembly that doesn't contain an `IComposer`.

### Specifics
Umbraco 8.1.5

### Steps to reproduce
If Umbraco is installed in a clean website project, add the following code:

```c#
[assembly: DisableComposer(typeof(Umbraco.Web.Runtime.WebInitialComposer))]

public class TestComposer : IComposer
{
	public void Compose(Composition composition)
	{ }
}
```

You should see a `BootFailedException`, as the `WebInitialComposer` isn't run.

Now comment out the `TestComposer`, rebuild and Umbraco should start up without the exception, as the `DisableComposer` attribute is not 'seen' anymore.

### Expected result
All `EnableComposer` and `DisableComposer` attributes should be considered while composing and not require adding an empty/dummy composer within the same assembly (which is the current work-around).

### Actual result
The attributes are not considered at all, thus not enabling/disabling any of the requested composers.

**Comment by zpqrtbnk** [comment]
Yes - it's considering assemblies of those types that implement `IComposer` instead of considering all assemblies where we looked for `IComposer` in the first place - even those that do not contain any `IComposer`. Confirmed bug.

**Comment by zpqrtbnk** [comment]
Fix implies not passing only the types to the `Composers` ctor but also the assemblies... in fact, it'd be better to just pass assemblies to `Composers` ctor and let it do what the `TypeLoader` does, in a proper way.
