### ISSUE TITLE
Media item url is updated when replacing file with new file

### ISSUE THREAD

**Issue by mariehoeg** [umbraco/Umbraco-CMS#6626]
Since the upgrade from 7.xx.xx to 7.15.1 we have had a problem when exchanging the file associated with a media item. The link for the file gets updated i.e. http://siteurl/media/1003/test.pdf to http://siteurl/media/1004/test.pdf. Before the upgrade the number in the path was not incremented when clicking "remove file" and uploading a new file, but it does now. Bug or feature 😊?

### Specifics

Location: media section of umbraco backoffice
Tested on Umbraco version 7.15.1, 7.15.2 and 7.15.3
In Chrome browser v. 77.0.3865.90 (not tested in other browsers)

### Steps to reproduce

- Go to the media library in Umbraco backoffice
- Upload a file for instance test.pdf
- Open the newly created media content item
- Note the direct link on the "info"-tab (i.e. http://siteurl/media/1003/test.pdf)
- Click the "Choose file"-button and upload another file with the same filename and fileextension
- Save
- Check the direct link again and see if the number in the url has changed. 

### Expected result

I expected the direct link/absolute url to be the same for the file when exchanging the file associated with the media item. 

### Actual result

Direct link for the media item is not the same after exchanging the file.

**Comment by abjerner** [comment]
Hi @mariehoeg,

Do you by any chance use Azure Blob Storage and the [UmbracoFileSystemProviders.Azure](https://our.umbraco.com/packages/collaboration/umbracofilesystemprovidersazure/) package? We've encountered similar issues with version 1.0.2, but upgrading to 1.0.3 fixed the issues in our case.

I'm not sure whether the issue in the package only affects certain versions of Umbraco, but it could be worth a try 😉

**Comment by mariehoeg** [comment]
Hi @abjerner 

We do indeed use blob storage. And upgrading fixed my issue! 
Thank you so much, this saves my customer (and me) a great deal of trouble. 🍾 😃
