### ISSUE TITLE
Can't configure alias for Media Type "Folder", dialogs not working.

### ISSUE THREAD

**Issue by enkelmedia** [umbraco/Umbraco-CMS#6632]
We wanted to prefix all our models generated by Models Builder with "Cms" and currently the only way to do this was to change the alias of the doc-types, media-types etc.

It looks like it all worked but when creating a new folder in the "Selected Media"-dialog. We're getting an error that there is no media type with the alias "Folder". 

![image](https://user-images.githubusercontent.com/1782524/66497822-5c505d80-eabd-11e9-8ec0-2f25b41e73b8.png)

Looking at the code in the "PostAddFolder"-method we can see that this is because the alias "Folder" is hardcoded as a constant.

Controller:
https://github.com/umbraco/Umbraco-CMS/blob/56545ad7f1fdee3c2b27e725c89378ccb947f65a/src/Umbraco.Web/Editors/MediaController.cs#L602

Constant:
https://github.com/umbraco/Umbraco-CMS/blob/6f5665f6a547881f85b393b7865723152c51a21e/src/Umbraco.Core/Constants-Conventions.cs#L114

Other types of "conventions" like the default alias of a member is something that we can configured but as far as I can understand it the default alias for a Folder (file,image) can't be configured?

**Comment by nul800sebastiaan** [comment]
Hey @enkelmedia - I am having a really hard time understand what you're trying to accomplish and why? Do you have some background info for me please?

**Comment by enkelmedia** [comment]
Well, the stuff about Models Builder was maybe just making it more confusing =D

Basiclly, if I change the alias of the media type "Folder" to something else, the built in views will blow up since the alias "Folder" is hard coded as a constant. What I'm saying is that there should be a way to configure what the defualt alias for a Folder, File or Image should be.

**Comment by stevemegson** [comment]
Rather than add settings to change the media types that we try to create, could we come up with sensible rules to pick a media type from those allowed under the parent? Perhaps File would use the first type with an upload property, Image would use the first type with an image cropper property, and Folder would use the first type with neither.

**Comment by enkelmedia** [comment]
That would also be a good option, I ended up reverting the changes but I still think that it would be good to be able to have a custom alias for a media type.

**Comment by ronaldbarendse** [comment]
As https://github.com/umbraco/Umbraco-CMS/pull/6943 protects renaming these media types from the back-office (it's still possible using the services), this probably won't be an issue anymore.

If this restriction gets lifted, it should probably be a simple configuration setting (optional, as we can fallback to the constants), as having rules might result in different types when the media types differ on environments.

**Comment by nul800sebastiaan** [comment]
Fixed in https://github.com/umbraco/Umbraco-CMS/pull/6943
