### ISSUE TITLE
Allow name templates for grid editors

### ISSUE THREAD

**Issue by skttl** [umbraco/Umbraco-CMS#6633]
Similar to Nested Content items, it would be helpful if grid editors could have nametemplates.

When sorting, you have almost no idea of which block you need to move, see screenshot as example:
![billede](https://user-images.githubusercontent.com/3726467/66514752-1657c180-eade-11e9-9617-0a87bd68d593.png)

**Comment by skttl** [comment]
I couldn't help it... PR is in #6634 :)

**Comment by elit0451** [comment]
Fixed in #6634
