### ISSUE TITLE
V8: MultipleTextstring validation failure

### ISSUE THREAD

**Issue by michielDB** [umbraco/Umbraco-CMS#6648]
When creating a MultipleTextstring property with minimum 0 items, which are not mandatory but have validation (email address), Umbraco tries to validate and fails.

![image](https://user-images.githubusercontent.com/11921909/66578470-6df83a80-eb7b-11e9-8899-f7b06f26af99.png)
![image](https://user-images.githubusercontent.com/11921909/66578510-810b0a80-eb7b-11e9-8f3b-c5e3f15acc4e.png)

**Comment by nul800sebastiaan** [comment]
Fixed in https://github.com/umbraco/Umbraco-CMS/pull/6677
