### ISSUE TITLE
ContentIndexPopulator not getting publishedQuery

### ISSUE THREAD

**Issue by hkooikerspeak** [umbraco/Umbraco-CMS#6655]
`private static IQuery<IContent> _publishedQuery;`

`if (_publishedQuery != null)`
                `_publishedQuery = sqlContext.Query<IContent>().Where(x => x.Published);`

the _publishedQuery property is never set. 

`if (_publishedQuery != null)` should be `if (_publishedQuery == null)` is guess.

**Comment by Shazwazza** [comment]
ack! good spot, i have merged this in
