### ISSUE TITLE
Consider removing css classnames starting with two hyphens to support IE11

### ISSUE THREAD

**Issue by robmaas** [umbraco/Umbraco-CMS#6669]
In a couple of places classnames starting with two hyphens (--) are used.

The specs only allow this since the introduction of CSS Custom Properties.

This is not supported in (amongst others) IE11 and could be fairly easily fixed by changing the classnames or coming up with a new naming convention. Even though IE11 is not officially supported it would be good to fix it.

For example:
The class --notInFront causes the umb-editor__overlay to be ignored in IE11 after PR #6668 

Right now there only seem to be a handful of those classes:
--error
--notInFront
--disabled
--selected
--initialized
--not-allowed
--current
--state-selection

**Proposal for new names:**
has--error
is--notInFront
is--disabled
is--selected
is--initialized
is--not-allowed
is--current
is--state-selection

**Comment by nul800sebastiaan** [comment]
As detailed on https://github.com/umbraco/Umbraco-CMS/pull/6671, we don't plan to support IE11 at all any more in v8.
