### ISSUE TITLE
V8 - "Is an Element type"

### ISSUE THREAD

**Issue by Ric-Carey** [umbraco/Umbraco-CMS#6673]
The new "Is an Element type?" tickbox on document types is great as it helps to limit the visibility of content types which are not needed in certain areas. However, there is a use-case where you need to add the document type to a nested content datatype and within the content tree. Which now is not possible. 

Can we either have an additional tickbox when the IsElement flag is set to true to then "Allow use in content tree?" or something similar please? Which when ticked would then allow it to be used in the content tree as well. 

The use case is as follows:

You create a module component which lives in nested content, but you then want to have "global" versions, which the editor can define and then pick from various other places, to save having to recreate multiple times. Currently, you would create under a container node. 

I appreciate this then could open a can of worms of "do we need content templates for nested content modules" etc - but for the sake of getting V8 websites off the ground, could the original suggestion be actioned first, please? 

Many thanks,
Ric

**Comment by nul800sebastiaan** [comment]
For a bit of background, read here: https://github.com/umbraco/Umbraco-CMS/issues/4168

We do not plan to support elements types to be in the tree and we've actively implemented code so they are not in the tree. They are purely meant to be used as elements and not as nodes.

**Comment by Ric-Carey** [comment]
Hi @nul800sebastiaan,

Thanks for showing the reference - which I totally understand from an architecture point of view why Umbraco wants to go down that route - I agree. 

However, for my use-case and I would presume a lot of other developers may use - I am now going to have to duplicate all of my document types which are used for nested content to create content tree versions. This doesn't lend itself well to DRY principles for if in the future I will need to change it in two places in Umbraco and then likely other areas of C# based on the generated models for something which is always going to be exactly the same.

I know this isn't the forum for debate, but I wanted to highlight the use-case and scenario as it doesn’t look like its been thought about. 

Happy to discuss further, wherever is best?

Cheers
Ric

**Comment by nul800sebastiaan** [comment]
Maybe give inheritance a go? Add the properties to a composition doctype that you compose in both your element type and your doctype. Should work.

**Comment by Ric-Carey** [comment]
Yeah that would work, good call. Cheers
