### ISSUE TITLE
V8 - "Is Element" on Document Type - On then Off

### ISSUE THREAD

**Issue by Ric-Carey** [umbraco/Umbraco-CMS#6674]
Further to https://github.com/umbraco/Umbraco-CMS/issues/6673 If you create a document type with the Is Element flag set to true, then turn it off as you decide to use it in the content tree - when you attempt to save the node you are presented with an error:

Factory returned model of type MODELSBUILDERNAMESPACE.CLASS which does not implement IPublishedContent.

Many thanks,
Ric

**Comment by nul800sebastiaan** [comment]
I can't reproduce this in the latest version of the codebase, so I'm going to assume it's been fixed already along the way! 👍

**Comment by Ric-Carey** [comment]
Cheers @nul800sebastiaan :)
