### ISSUE TITLE
V8 - Adding new Crop Alias requires save of media before showing front end

### ISSUE THREAD

**Issue by Ric-Carey** [umbraco/Umbraco-CMS#6681]
If you add a new crop alias to the image cropper. And the editor then selects a pre-existing media item. The resulting Image.GetCropUrl("alias") will be blank until the editor goes into the media item and presses save.

Expected result - the image should be shown cropped to the crop alias width and height based on the current/default crop position.

**Comment by nul800sebastiaan** [comment]
Thanks! This duplicates issue https://github.com/umbraco/Umbraco-CMS/issues/5737
