### ISSUE TITLE
Editor unable to sort nodes in content tree

### ISSUE THREAD

**Issue by bjornnorlen** [umbraco/Umbraco-CMS#6682]
A content editor is unable to sort the order of the nodes directly under the content start node in the content tree. 

Reproduction
------------

### Bug summary

We have several user groups where the editors only have access to one page and its subpages in the content tree. When an editor tries to sort the level directly underneath the content start node (right clicking on the content start node and choosing sort) Umbraco gives an error message.  
For example, we have a user group called ”Kommun och Politik” with access to content and media, content start node is a page with the same name as the group (Kommun och Politik) and all the default permissions are set to true. In the content tree, when an editor right clicks on ”Kommun och Politik” and chooses sort, Umbraco will give an error message when the editor clicks ”save”. However, if the editor right clicks on a subpage to Kommun och Politik and chooses sort, that’ll workout fine. 
The error appears when trying to change sort order on the content start node. It doesn’t matter if the user clicks on ”Name” to change the sort order or tries to change sort order for only one of the nodes, the error message still appears. I also tried to recreate the issue on an Umbraco 7.15.2 installation but there the sorting worked as expected which make be believe this is bug in Umbraco 8. 

### Specifics

Umbraco version 8.1.3
Chrome 77.0.3865.120
Also checked in Firefox 69.0.1

![Img1](https://user-images.githubusercontent.com/19406378/66745596-b5364200-ee7f-11e9-94b1-5d7229824c3b.JPG)
![Img2](https://user-images.githubusercontent.com/19406378/66745598-b5364200-ee7f-11e9-95f3-f253ff6ec8bc.JPG)
![Img4](https://user-images.githubusercontent.com/19406378/66745671-ed3d8500-ee7f-11e9-8ea6-33f4edc3b1c2.JPG)
![Img3](https://user-images.githubusercontent.com/19406378/66745601-b5ced880-ee7f-11e9-8eff-ef7b504f5160.JPG)

### Steps to reproduce

- Create a new user group
 - Give the group access to content and media
 - Set content start node to a specific page
 - Set media start node to root
 - Set all default permissions to true
 - Add a user to the group
 - Make sure the user isn’t a member of any other groups
 - Sign in with the new user
 - Right click on the content start node and click ”Sort”
 - Change the sort order in any way
 - Click ”Save”
 - The error message appears

### Expected result
That the pages are sorted in the order the editor chooses

### Actual result
The editor is presented with an error message:

Authorization error: Unauthorized access to URL:
/umbraco/backoffice/UmbracoApi/Content/PostSort
Contact your administrator for information.

**Comment by kjac** [comment]
I can reproduce this. I'll have a look.

**Comment by kjac** [comment]
PR in #6686
