### ISSUE TITLE
8.2: Full screen options in RTE doesn't work correctly

### ISSUE THREAD

**Issue by sofietoft** [umbraco/Umbraco-CMS#6701]
I've added the "Full screen" option to an RTE.
When I try to use it in the content section, it doesn't go full screen, but instead gives me this:

![RTE-fullscreen](https://user-images.githubusercontent.com/24529086/66832839-fbac9f00-ef5a-11e9-8e44-03599d433769.png)

Reproduction
------------

### Bug summary

The full screen option of RTE's doesn't work properly.
It worked fine in Umbraco 8.1.5

### Specifics

* Umbraco 8.2
* Google Chrome, 77.0.3865.120
* Checked Edge (44.18362.387.0) - doesn't work there either

### Steps to reproduce

* Create a Document Type
* Add an RTE to the Document Type
* Make sure that the "Full screen" option is enabled on the RTE
* Create a content node
* Click the full screen option in the RTE

### Expected result

I expected that the editor would go into full screen mode.

### Actual result

![RTE-fullscreen](https://user-images.githubusercontent.com/24529086/66832839-fbac9f00-ef5a-11e9-8e44-03599d433769.png)

**Comment by kjac** [comment]
I can reproduce this... and I think I have a fix. Will test and submit tomorrow 👍

**Comment by kjac** [comment]
PR in #6715
