### ISSUE TITLE
ContentPopulators are using UmbracoContentIndex

### ISSUE THREAD

**Issue by bielu** [umbraco/Umbraco-CMS#6705]
@Shazwazza 
Actually, I look into the source code of Umbraco and I am trying to figure out why IndexPopulators are using UmbracoContentIndex as the type to discover instead of some Interface which could be inherited by external indexes with a different type than Lucene index? As UmbracoContentIndex inherits from  UmbracoExamineIndex, which is based on LuceneIndex, IUmbracoIndex, IIndexDiagnostics. Actually I would probably propose to create IUmbracoContentIndex which will allow using build-in Content Populators instead of push to create own. It will make easier for future developers which want to create custom Examine Provider for Umbraco.

**Comment by Shazwazza** [comment]
Yep i think that makes sense and a similar change would be needed for MemberIndexPopulator

Alternatively ... these index populators don't inherit from the `IndexPopulator<T>` and instead just register themselves based on the index name then we don't need to worry about more types. Perhaps the idea of `IndexPopulator<T>` was not the best idea.

**Comment by bielu** [comment]
@Shazwazza actually the idea of IndexPopulator<T> is not bad, because of solving the problem with filtering of indexes based on type (Member/Content). Actually I think it is a quite good idea to stay with that, only abstract type to be not assigned to Lucene Indexes. I am going to prepare PR based on IndexPopulator<T> if we will figure out something better in the meantime I will be happy to create new PR :)

**Comment by Shazwazza** [comment]
What I meant was that populators are defo a good idea, but maybe not the generic type which assigns itself to indexed based on their index types. The non generic type assigns itself based on index names which we could use instead. The non generic version means you don't have to introduce another interface.

**Comment by bielu** [comment]
@Shazwazza I understand but actually, if someone wants to register custom index we are not forcing them to override the list of registered indexes? As actually in my head, I have vision of hardcoded list of indexes per populator. Maybe I am wrong here because I am not catching something :)

**Comment by Shazwazza** [comment]
@bielu aha! sorry you are certainly correct, if we hard code aliases than any other umbraco based index wouldn't be populated since that list would need to be updated which is ugly. So yeah, i think IUmbracoContextIndex is a fine solution
