### ISSUE TITLE
V8.2 RTE image dialog doesn't display title

### ISSUE THREAD

**Issue by skartknet** [umbraco/Umbraco-CMS#6712]
The image dialog in the RTE misses some styling and the title. It feels like it's not a finished dialog.

![image](https://user-images.githubusercontent.com/1685262/66872869-b50a8380-eff2-11e9-90ac-3ca1384eecf9.png)

![image](https://user-images.githubusercontent.com/1685262/66872971-04e94a80-eff3-11e9-9c47-27be439ef223.png)

### Bug summary
* Modal dialog misses Title
* Not sure if it also misses some styling, like some padding below the title box.
* Missing some labels?

### Steps to reproduce
I have inserted an image in the RTE using the drag and drop functionality. Then I select the image in the RTE and click in the Media Picker button and a dialog opens on the right which is a bit confusing as it doesn't says what it's for and misses some styling I think:

### Expected result
A more clear meaning of what that dialog is for.

### Actual result
Confusing, the first time it opened I didn't know what that was for.

**Comment by kjac** [comment]
Yeah... I saw this one too yesterday. It's on my to-do list.

**Comment by nul800sebastiaan** [comment]
Funnily enough, this is what that dialog looks like in 8.1.5 

![image](https://user-images.githubusercontent.com/304656/66898426-7926ec80-eff9-11e9-95e3-9d6c3613b5c9.png)

I'm not sure we should not even be showing that URL.. there's nothing you can do with it? Or at least then it should be a clickable link or something. 

But you've never been able to update the name of the file from this dialog, what would the use case for that be?

**Comment by kjac** [comment]
I think the whole thing needs a bit of a makeover. There are several issues with it, specially when editing existing images from the rte. I'll be having a look later.

**Comment by skartknet** [comment]
I'd say it should probably display the picker to replace the image.

**Comment by kjac** [comment]
Yeah so this was a can of worms... PR in #6722

**Comment by nul800sebastiaan** [comment]
Fixed in https://github.com/umbraco/Umbraco-CMS/pull/6722
