### ISSUE TITLE
V7: Media uploader in RTE doesn't select uploaded image

### ISSUE THREAD

**Issue by KirschnerMatt** [umbraco/Umbraco-CMS#6720]
This is a repost of the following issue: https://github.com/umbraco/Umbraco-CMS/issues/3022

While the issue might have been fixed before, it seems to have come back for one reason or another. This may be reproduced by uploading images to an RTE in a fresh install of V7.15.3

The original comment by JorickDJ is still relevant:

> This issue was already submitted on 12th of September 2017 and we are still having problems with this issue in Umbraco version 7.10.5.
> 
> The previous bug submission can be found here:
> https://issues.umbraco.org/issue/U4-10408
> 
> When I want to add a new image to the RTE I click on the Image Picker and upload a new image. The Image Picker indicates that the image is selected and when you click "Submit" it adds a "nothing.jpg" to the RTE.
> 
> If you upload a new image in the RTE Image Picker and then scroll to the uploaded image and select it again, then it will be added correctly.

**Comment by elit0451** [comment]
Fixed in #6739 

Cherry picked for 7.15.4 in commit 38d241952047f00b8c11ef0662d2b60093dc41f0

**Comment by jmvivas** [comment]
I have replicated this on 7.15.3 but only when using FileSystemProviders.Azure.AzureBlobFileSystem

Sometimes I get a "nothing.jpg" but mostly the actual image gets inserted with width and height = 0 which confuses the editors a great deal.

7.15.3 using local media files works OK
