### ISSUE TITLE
Saving a document type never ends when we have many nodes of that document type in v8.2.0

### ISSUE THREAD

**Issue by saifobeidat** [umbraco/Umbraco-CMS#6735]
### Bug summary
We have about 2000 nodes that have been created of the same document type, after a while we decided to change something on that document type, and we tried to save that change but it didn't finish, the saving button it kept loading.

### Specifics
Umbraco 8.2.0
Chrome 7.7 (No errors on the console)

### Steps to reproduce
1: Create a document type
2: Create around 2000 nodes based on that document type
3: Open that document type and try to change anything, for example try to add a new child under it from the permission section.
4: Save

![screengifnew](https://user-images.githubusercontent.com/24841143/66988399-20278900-f0cb-11e9-9e14-8f37fd445771.gif)

### Expected result
Saving a document type should finish

### Actual result
Saving a document type never ends

**Comment by nul800sebastiaan** [comment]
You mention 8.2.0 specifically, did this used to work for you in 8.1.5?

**Comment by nul800sebastiaan** [comment]
This may be solved with the work we're doing here, not sure: https://github.com/umbraco/Umbraco-CMS/pull/6688

**Comment by saifobeidat** [comment]
> You mention 8.2.0 specifically, did this used to work for you in 8.1.5?
I have faced the same issue in 8.1.5 and it didn't work.

**Comment by erwintres** [comment]
Is there an update on this issue?

**Comment by nul800sebastiaan** [comment]
Ah, I didn't realize this was still open, sorry about that. We're working on investigating this in the current sprint. There's another issue that we're tracking for that, so I'll close this one, make sure to follow the other issue for updates: 

https://github.com/umbraco/Umbraco-CMS/issues/7756

@erwintres - you must have a good reason to ask, can you add some specifics of your problem on the #7756 issue please? How many nodes do you have, how slow is it, what version are you using, etc.
