### ISSUE TITLE
Rollback issue in 8.2.0

### ISSUE THREAD

**Issue by kometa333** [umbraco/Umbraco-CMS#6738]
Hi,

There is a bug in the rollback feature in umbraco v 8.2.0. The time in the rollback drop-down is not in sync with the history time details. There is a 2 hours time difference between them.

Reproduction
------------

* go to the "Info" tab of any content page which has been saved and published multiple times
* in the "History" section click the "Rollback" button
* expand the "Rollback to" drop down
* the time mentioned in the drop down is different to the time listed in the History section, there is 2 hours time difference between them

**Comment by nul800sebastiaan** [comment]
I assume that your site is running on a server that's in a different timezone? It is basically the same as this issue then: https://github.com/umbraco/Umbraco-CMS/issues/6357
