### ISSUE TITLE
8.2 - Image thumbnails within content 404.

### ISSUE THREAD

**Issue by Ric-Carey** [umbraco/Umbraco-CMS#6744]
Hey,

Not sure if this is local to my project, (started on 8.1.5, upgraded yesterday to 8.2) I have a series of media pickers within Nested Content and they are referancing a thumbnail URL  - /umbraco/backoffice/UmbracoApi/Images/GetBigThumbnail?originalImagePath=MEDIAPATH which is 404ing. If the Image picked is an SVG then it uses the original Media.Url source and renders.

Cheers
Ric

**Comment by kjac** [comment]
Hmmm... How weird! Are these properties based on multinode treepicker or the dedicated media picker datatype?

**Comment by Ric-Carey** [comment]
Its just the normal media picker datatype. Equally the thumbnails in the slide out sidebar when you go to pick an image are 404ing too as they point to the same place. However, if you go into the folder view of the media section - those thumbnails work because they are referencing the straight media url.

Yes it wasn't working in v8.1.5 either

**Comment by emmaburstow** [comment]
Ah ok. Thanks Ric.

**Comment by kjac** [comment]
For the life of me I can't reproduce this.... neither on 8.2 (vLatest) nor 8.1.5. I've even tried installing a release build of 8.1.5 from nuget without luck - here's what I see:

![media-picker-404](https://user-images.githubusercontent.com/7405322/67038547-e9c82900-f11f-11e9-8c20-c282aa822d38.gif)

**Comment by rasmusjp** [comment]
@Ric-Carey do your `umbracoSettings.config' have a `content/imaging/imageFileTypes` section? If it does can you check if the extension requested is present in the value? If not is the file extension present in this list https://github.com/umbraco/Umbraco-CMS/blob/aeecc119cc65b2c220ba8e7c911d78d1a58950b8/src/Umbraco.Core/Configuration/UmbracoSettings/ContentImagingElement.cs#L17 ?

@kjac IMO the `ImagesController` should be deprecated and references to `/umbraco/backoffice/UmbracoApi/Images/GetBigThumbnail` and `/umbraco/backoffice/UmbracoApi/Images/GetResized` should be replaced with direct calls to the image processor instead

**Comment by Ric-Carey** [comment]
Thanks for everyone's help on this. Sorry this was completely my fault. 

The issue actually stemmed from a URL Rewrite i had put in place to rewrite /images/ to another directory. Which if i put a negate rule in for the /Umbraco/ directory, solved the issue. Lessons learnt!

I discovered it when I was comparing to a fresh install of v8.2 from the zip file to check what the differences where, as I didn't have the section you described @rasmusjp . I agree with him that, this has highlighted there are two different ways of getting thumbnails in the back office - via this API method and by directly hitting the image processor (like in the media section)

@kjac  - thanks for trying to recreate, that put me in the right direction as i could localise it to my install. 

Sorry for wasting time. My apologies.

**Comment by nul800sebastiaan** [comment]
No worries @Ric-Carey - I'm just happy you found the problem! 👍
