### ISSUE TITLE
V8: Examine store trashed items without flagging them

### ISSUE THREAD

**Issue by bielu** [umbraco/Umbraco-CMS#6747]
One of our clients report that issue:
When the node is moved to the bin, examine still returns that item without flagging that as trashed or anything. 
Umbraco version: 8.1.5

Steps to reproduce:
1) Move any indexed node to bin
2) go to examine management
3) Choose ExternalIndex
4) Search for a trashed node

Expected Result:
The node will be flagged as trashed or will be not found.
Actual Result:
A node could be found and is not flagged as trashed.

**Comment by nul800sebastiaan** [comment]
Unfortunately I can't reproduce this is in a clean install of neither 8.1.5 nor 8.2.0. Might be some custom code?

**Comment by bielu** [comment]
Hmm, even weirder it is not happening on all my 8.1.5 clear installation 0.o
