### ISSUE TITLE
Statuscode attribute on BackOfficeController is preventing upgrade from running in Cloud

### ISSUE THREAD

**Issue by clausjensen** [umbraco/Umbraco-CMS#6754]
Recently a statuscode attribute was added to `BackOfficeController` and `InstallController`:
https://github.com/umbraco/Umbraco-CMS/commit/62ee1899ad3d2d884f89eb38e38913f72700b20e#diff-a5b1cc6444908fb196d9da7a84626d01R148

Unfortunately this causes a site on Cloud in a pending upgrade state, to simply return a 503 status code with no content result - not enabling the upgrader to actually render. I am not completely sure why this happens, as it seems to run just fine when the exact same site is copied to my local machine.

~I have an idea that it might be because all requests in Cloud are proxied in front of the actual webworkers and something in this proxy may be reading this status code and simply override and return a standard 503 content response whenever a 503 statuscode is asked to be returned by the webworker.~

I have confirmed this behavior in Cloud by trying to return content from a working site, not in an upgrading state. As soon as I set the statuscode of my response to 503, Cloud will override my content with a standard response. When I do this on a local non-proxied website, it will return the specified content with a response code of 503.

Reproduction
------------

See above. A site in a pending upgrade state on Cloud will cause this issue to show up.

### Bug summary

Returning a 503 statuscode on Cloud will override the content of the response, causing an upgrade to be impossible since the upgrader will never be shown.

~It may be due to Cloud using proxy - if that is the case then this could also apply to other non-Cloud sites using proxy.~

---
_This item has been added to our backlog [AB#3248](https://umbraco.visualstudio.com/243e7927-03b2-44e2-908f-d4ac7ea5daaa/_workitems/edit/3248)_

**Comment by clausjensen** [comment]
@ronaldbarendse Setting `TrySkipIisCustomErrors` seems to work! 😃
(just tested this with my _other_ test .. haven't verified the actual upgrade but it should apply for that as well)

Regarding the additional property to make this optional; Would there ever be a case where you would want to use this attribute and *not* ensure that it just skips custom errors by default? .. to me it seems like in situations where you would use this attribute on a controller action, you would always expect to have the content response output- with the statuscode... regardless of how the server is configured (to avoid causing confusion on how this behaves with the same code on different environments).

**Comment by ronaldbarendse** [comment]
Well, I totally agree, but that's also the case for the custom 404 responses within Umbraco... Especially if you read this description:

https://github.com/umbraco/Umbraco-CMS/blob/853087a75044b814df458457dc9a1f778cc89749/src/Umbraco.Web.UI/config/umbracoSettings.config#L77-L82

Umbraco 8 has changed the default value to `true`, so it would make sense to honor this setting and add this after setting the status code:
```c#
filterContext.HttpContext.Response.TrySkipIisCustomErrors = Current.Configs.Settings().WebRouting.TrySkipIisCustomErrors;
```

**Comment by Shazwazza** [comment]
PR is here https://github.com/umbraco/Umbraco-CMS/compare/v8/bugfix/6754-StatusCode-Skip-CustomErrors

Code looks fine and is inline with what is mentioned above. Sine this has already been tested i'm happy to merge.
