### ISSUE TITLE
Calling RemoveTreeNodeLocked removes the root node of the current gen

### ISSUE THREAD

**Issue by clausjensen** [umbraco/Umbraco-CMS#6758]
Follow up for: https://github.com/umbraco/Umbraco-CMS/issues/6698

>What I find a bit strange is that in the ContentStore.SetBranch method, it first clears the branch with ClearBranchLocked which is fine, this essentially zero's out the new Gen for the branch since it's going to fill in these null values after that ... but it then calls RemoveTreeNodeLocked which is going to actually remove the root node of this particular branch for the current Gen (not the new one that is being created) which seems odd since this branch shouldn't be modified for the current Gen, only for the new Gen but this effectively makes this branch disapear for the current Gen. 🤔 I'm still investigating what changes are needed to fix this correctly.

---
_This item has been added to our backlog [AB#3252](https://umbraco.visualstudio.com/243e7927-03b2-44e2-908f-d4ac7ea5daaa/_workitems/edit/3252)_

**Comment by nul800sebastiaan** [comment]
Was fixed in #7233
