### ISSUE TITLE
User Group with start node - User login fails

### ISSUE THREAD

**Issue by thomashdk** [umbraco/Umbraco-CMS#6803]
I created a new user group, that have a Start node and no Media start node.

Then the login fails:
![image](https://user-images.githubusercontent.com/6445636/67242448-dab1e580-f455-11e9-82f8-3049c90e9d40.png)

Test on: 

Umbraco 8.2 Cloud - Local and Live environment.  
Umbraco 8.1.5 - Local environment

Same result on every site.

**Comment by nul800sebastiaan** [comment]
Thanks, this overlaps with issue https://github.com/umbraco/Umbraco-CMS/issues/5641 - I'll close this one and you should probably have a read at what's been going on to try to fix this, it's apparently a bit of a can of worms.

Of course the advice for now is: make sure to set a media start node for those users :)
