### ISSUE TITLE
Umbraco Cloud 8.2 - Root node with a different hostname main solution shows as unpublished

### ISSUE THREAD

**Issue by thomashdk** [umbraco/Umbraco-CMS#6818]
I have noted that on a Umbraco Cloud 8.2 solution on a url ### "mainurl.dk".

If I have Multiple root nodes with a different Hostname ex. on a subdomain ### "x.mainurl.dk", 
then this root node on ### "mainurl.dk" shows as the item now are published:
![image](https://user-images.githubusercontent.com/6445636/67395393-33909380-f5a6-11e9-9bd8-345ddc84c5d6.png)

But when I on the sub domain ### "x.mainurl.dk" looks at the same root node it shows as it's published as it is. 
![image](https://user-images.githubusercontent.com/6445636/67395537-794d5c00-f5a6-11e9-9c28-8289de3cb558.png)

The same is with all the other root nodes.

**Comment by emmaburstow** [comment]
Hey @thomashdk,

Thanks for submitting the issue here. I'm going to try and label it but I just need a little more explanation. What exactly are you trying to do? Can you provide steps to reproduce? 

Thanks,

Emma

**Comment by thomashdk** [comment]
Hey, 

I have an Umbraco Cloud 8.2 solution with multiple Root nodes. 
Each node has a hostname.

Let's call them
![image](https://user-images.githubusercontent.com/6445636/67626676-17fbe600-f84f-11e9-9d22-d6924d2ce9ce.png)

- www.a.dk
- www.b.dk
- www.c.dk

When i'm on www.a.dk, then it shows root node www.b.dk and www.c.dk as not published by not showing the url link.
![image](https://user-images.githubusercontent.com/6445636/67626698-5db8ae80-f84f-11e9-98c8-f647172d2b6e.png)

if I then are on www.b.dk then it shows it correctly
![image](https://user-images.githubusercontent.com/6445636/67626711-a708fe00-f84f-11e9-831c-098eb8828c58.png)

But then it shows www.a.dk and www.b.dk like this.
![image](https://user-images.githubusercontent.com/6445636/67626698-5db8ae80-f84f-11e9-98c8-f647172d2b6e.png)

Makes sense ??

**Comment by nul800sebastiaan** [comment]
I stumbled upon this old issue, I think this must have been fixed along the way as I get perfectly good URLs for each root node with domain names now. Thanks for reporting though and sorry for the very late reply 🙈
