### ISSUE TITLE
Watch task in Gulp setup fails when editing views

### ISSUE THREAD

**Issue by kjac** [umbraco/Umbraco-CMS#6819]
I haven't got at clue what's going on here, but the Gulp watch task has started failing when editing views... and I can see that the Gulp setup has changed today, so I'm guessing it's related to that.

Here's a screenshot of the error:

![image](https://user-images.githubusercontent.com/7405322/67397679-d72f7300-f5a9-11e9-80b7-7fc43e521b95.png)

And yes... I did run "npm install" first 😄 

/cc @nielslyngsoe

**Comment by nielslyngsoe** [comment]
Hi @kjac, We are looking into this at this moment, just a stupid mistake. And we are making a fix right now.

**Comment by kjac** [comment]
Awesome!
