### ISSUE TITLE
V8: Extending the Tags property editor

### ISSUE THREAD

**Issue by nielsodgaard** [umbraco/Umbraco-CMS#6825]
With the current Tags property editor it doesn't seem easy to setup some predefined tags the editors can choose from.

I think it would be great if we could extend the Tags with a field for an xpath query (like MultiNodeTreePicker2) and an option to enable/disable the possibilty to add tags on the fly.

By doing this we could add predefined tags from content nodes and that would make tags usable for many more things like search filters and relating content and it would also give translateable tags.

**Comment by nul800sebastiaan** [comment]
Hi @nielsodgaard - that is certainly a nice request, currently I would use a dropdown/checkbox/radiobutton list for this unless it's a long list. 

The current tags editor is not really built with this purpose though and we don't have plans to change it to a limited list for the moment. 

This actually seems to me like it would be an excellent idea for making it into a nice package! If you (or someone else) is up for trying to build this as a package then I am sure [the new Package Team](https://umbraco.com/blog/umbraco-package-program/) would find this an interesting test case. What do you think?

**Comment by nielsodgaard** [comment]
Hi @nul800sebastiaan, 

I think making this into a package is a good alternative :-)
I will work on that, since this is a feature which would be useful for many of my projects.
Thank you 👍
