### ISSUE TITLE
Idea: use more space for Media Picker

### ISSUE THREAD

**Issue by nielslyngsoe** [umbraco/Umbraco-CMS#6845]
I think it would make a lot of sense to use more space for the MediaPicker. We offen use the MediaPicker to explorer images, so why not have a bigger visual space for exploring.

I'm thinking Infinity Editing wide overlay for the MediaPicker.

Let me know if you have any thoughts regarding this or wether you like the idea.

Thanks

BTW. this idea came out of discussions in regards to enabling ListView for Media Picker https://github.com/umbraco/Umbraco-CMS/issues/5259

**Comment by skttl** [comment]
Should it be full width as a default?

**Comment by nielslyngsoe** [comment]
Hi @skttl, good question. My idea is that the Media-Picker property editor would always open in full-width (not possible to configure to do anything else from a user perspective). But wether it's possible for a package to use the Media Picker in the width we know today, might be an option in code.

**Comment by nathanwoulfe** [comment]
Can meet in the middle - I added a medium variant for infinite editors last week...

**Comment by nielslyngsoe** [comment]
@nathanwoulfe interesting 👀, so how do that work? is it a fixed size or just half the screen? Can you link to the PR? Thanks

**Comment by nathanwoulfe** [comment]
@nielslyngsoe max width 800px, so 60% wider than the small variant. Thought about making it a percentage of screen width, but went with a sensible increase on the default

#6808 is the PR

**Comment by kjac** [comment]
Well this is such a great idea and since no-one seems to be picking it up... here's a PR: #7741

**Comment by nul800sebastiaan** [comment]
Fixed in https://github.com/umbraco/Umbraco-CMS/pull/7741
