### ISSUE TITLE
Save & Publish shortcut - backend

### ISSUE THREAD

**Issue by RyuLindow** [umbraco/Umbraco-CMS#6856]
Ctrl + S saves the changes. It would be nice to have a shortcut that Saves and Publishes them.

I propose Ctrl + Shift + S as the shortcut.

**Comment by kjac** [comment]
Hi @RyuLindow 🙂

There is one already. If I'm not mistaken it's Ctrl+P

**Comment by emmaburstow** [comment]
Hey @RyuLindow - @kjac has it right. Thanks!

**Comment by RyuLindow** [comment]
Thanks for the info.

I didn't know about that shortcut because it's not on the shortcut list under the settings tab and you can't really open a shortcut list under the content tab.

Adding this shortcut to the shortcut tab and eventually also adding the shortcut tab under the content tab would be a nice QoL change.
