### ISSUE TITLE
v8 - Installation of Machine Key Fails if web.config has multiple system.web sections

### ISSUE THREAD

**Issue by KevinJump** [umbraco/Umbraco-CMS#6869]
If you run the Umbraco Installation on a site where the web.config has multiple system.web sections (if for example there is one in a `<location>` element, then the installation fails.

Reproduction
------------

on a new Umbraco project before installation add a system.web section to the config file inside a `<location>` element e.g

```
    <location path="some/path">
        <!-- Up the file upload limit for this path only -->
        <system.web>
            <httpRuntime maxRequestLength="512000" />
        </system.web>
    </location>

```
Run the installation and you will get a failure, 

### Bug summary

The installation process should look for the system.web under the root Configuration element and not any descendants as there may be many.

**Comment by nul800sebastiaan** [comment]
Fixed in https://github.com/umbraco/Umbraco-CMS/pull/6870
