### ISSUE TITLE
Multinode treepicker value not being restored when syncing content in Umbraco Cloud

### ISSUE THREAD

**Issue by nojaf** [umbraco/Umbraco-CMS#6872]
When restoring the content from my live environment to my local environment I noticed that the value of a Multinode Treepicker is not being restored.

Reproduction
------------

### Specifics

* Umbraco 8.2 on Umbraco Cloud
* Windows 10

### Steps to reproduce

Create a new Umbraco Cloud project with the starter kit.
Clone the repository, run and open localhost.
View the products node in the content tab.

![image](https://user-images.githubusercontent.com/2621499/67623774-8c239300-f829-11e9-8c81-656ac5bf18f7.png)

On my live environment, there are nodes selected.

![image](https://user-images.githubusercontent.com/2621499/67623797-c1c87c00-f829-11e9-87bd-4882847b29cc.png)
### Expected result

Selected nodes would also appear locally.

### Actual result

There are no featured products selected after syncing from the live environment.

**Comment by nul800sebastiaan** [comment]
Hmm, I can't reproduce the problem, restore on local is working well:

![image](https://user-images.githubusercontent.com/304656/67718822-d98e3480-f9d0-11e9-943a-6109e983cb86.png)

Maybe try to manually save all of the related document types again on Cloud and then publish the pages again that you want the MNTP items to be on. Finally pull the changes from cloud to local (did the document types actually change when you saved them? they'll end up in git) and in the data folder add a deploy marker (add an empty file named `deploy` in your `~/data` folder) and finally, when you see a `deploy-complete` file appear, try the restore from cloud again.

If that doesn't help, make sure to reach out to Cloud support in the umbraco.io portal so they can assist you further.
