### ISSUE TITLE
Opening Help Panel Without Connection to Internet Throws Exception

### ISSUE THREAD

**Issue by idseefeld** [umbraco/Umbraco-CMS#6894]
Within a customers intranet solution, where the server has no internet access due to security policies, opening the help panel throws an exception and a red error message is shown.

Reproduction
------------
1. Install an Umbraco version 8.
2. Disable your network adaptors or unplug
3. Goto back office and open the help panel

### Bug summary

I located a server side HttpClient calling: https://our.umbraco.com/Umbraco/Documentation/Lessons/GetContextHelpDocs?sectionAlias=...
 
The frontend API call was:
http://localhost:52341/umbraco/BackOffice/Api/Help/GetContextHelpForPage?section=...

**Comment by idseefeld** [comment]
There are more issues in other sections. 
I think all HttpClient use cases should be checked.

**Comment by kjac** [comment]
Fixed in #7163
