### ISSUE TITLE
Show notification when domains are updated

### ISSUE THREAD

**Issue by nielsodgaard** [umbraco/Umbraco-CMS#6896]
When saving Cultures and Hostnames you don't get a status notification like you do when editing most other things in Umbraco.
I've sometimes been in doubt if I also have to 'Save and publish' the content node to also save the domains. 
Would be great with a little notification to let the editor know the domains have been updated without any errors 👍

**Comment by nielsodgaard** [comment]
I've got an upcoming PR for this one just in case :-)

**Comment by kjac** [comment]
Fixed in #6899
