### ISSUE TITLE
"Return to List" button in back office media fails.

### ISSUE THREAD

**Issue by OwainJ** [umbraco/Umbraco-CMS#6924]
Brief description

When navigating a List view of Media items in the back office, clicking the "Return to List" button seems to do nothing.

Reproduction
------------
### Bug summary

On our Umbraco project we have a custom media folder media type (extends folder) with List view enabled, which has only two allowed child nodes: itself and a custom PDF media type that extends the File media type.

The folder is structured like this: (dates are examples)

─── Inspection Reports - [_Type_] _(folder)_
..........├──  2010 _(folder)_
.......... |.......... ├── Report 1 _(pdf)_
.......... | ..........└── Report 2 _(pdf)_
..........├──  2011 _(folder)_
.......... | ..........└── Report 2 _(pdf)_
..........└──  2012 _(folder)_
........................└── Report 2 _(pdf)_

If we navigate down the folder tree, and then click the "Return to List" button at the bottom of the page, the page refreshes and stays on the current page _(even though the URL changes to the correct one)_, it is then impossible to navigate back via the browser, forcing the user to either refresh the page or re-select the top level folder from the media list..

This is demonstrated in the gif below, I navigate down a folder, click the "Return to List"  button, the URL changes but the page doesn't actually go back. Upon refreshing the page the correct page is shown.

### Specifics

- Umbraco 8.2.0
- Doesn't seem to be browser specific, happens on:
     - Version 78.0.3904.70 (64bit)
     - Firefox 70.0 (64-bit)
     - Microsoft Edge 44.18362.387.0
- Nothing shows up in the Umbraco log, and chrome dev tools console shows no errors.

### Steps to reproduce

- Create a custom folder data type. (Test Folder)
- Create a custom media type. (Test Item)
- Set the 'Test Folder' data type to have "Enable list view" as true.
- Set the 'Test Folder' data type's permissions to have "Allow as root" as true and for it's only "Allowed child node types" to be itself and the custom media type.
- Create a new 'Test Folder' at media root.
- Create a new 'Test Folder' inside of the first 'Test Folder'.
- Add a 'Test Item' inside of the inner 'Test Folder'.
- Navigate to media root.
- Navigate into the 'Test Folder' and into it's sub folder.
- Try clicking on the "Return to List" button.
- Observe result.

### Expected result

- The expected result is for when the user clicks "Return to List" button, that the user gets navigated back up the folder structure to the prior list.

### Actual result

- Upon clicking the "Return to List" button, the user remains in the folder they where in. Even though the URL seems to get changed to the correct location.
- This also seems to disable the "Back" arrow button that's located at the top of the page next to the current folders name.
- Pressing the refresh button in the browser loads the correct page.

![return to list demo](https://user-images.githubusercontent.com/17008780/67699302-dd579200-f9a3-11e9-88d8-68a805f2206d.gif)

**Comment by nul800sebastiaan** [comment]
Hmm, unfortunately that all seems to work just fine for me, don't think I'm doing anything differently.

![6924](https://user-images.githubusercontent.com/304656/67720293-d2b4f100-f9d3-11e9-8684-32b4b8ced719.gif)

**Comment by OwainJ** [comment]
Hi @nul800sebastiaan, this issue can be recreated in a fresh install of Umbraco 8.3 by following the repro steps in issue: #7182 . I believe these two issues (search and return to list) are related.

**Comment by kjac** [comment]
There are (have been) several incarnations of the same root problem i.e. not being able to navigate to a content type template from the content type itself. 

I think all of these are handled by the fix in #6333 😄

**Comment by OwainJ** [comment]
@kjac was #6333 included in the v8.2.0 release? As I and a colleague can both recreate this issue and #7182 in a new vanilla installation of v8.3.0, by applying "vary by culture" to the doc types and then restarting the solution.

**Updated repro steps for this issue:**
- Install Umbraco 8.3 with the example site.
- Navigate to the settings tab.
- Add a new language. (I added "Welsh" with "English" as the fallback)
- Enable _"Vary by Culture"_ on all of the doc types.
- Enable _"list view"_ on the "Folder" media type.
- Restart the solution.
- Navigate to the Media tab.
- Select the "People" folder and select an image.
- Try clicking the "Return to List" button.

I've just tested and can recreate this on Chrome, Edge Beta, Edge Stable and Firefox.

This gif shows the issue in a vanilla v8.3.0 installation on chrome:
![return to list 8-3](https://user-images.githubusercontent.com/17008780/69227000-091c0100-0b79-11ea-983a-d3b7a3a2de78.gif)

**Comment by kjac** [comment]
@OwainJ #6333 was included in 8.2.1. But you're right, something fishy is going on when cultures are enabled. I can reproduce ##7182 to some extend, will need to dig further into that. 

This one however I can't reproduce on 8.3 - here's my GIF of the same operation:

![media-list-view-back](https://user-images.githubusercontent.com/7405322/69232819-0c6cb800-0b8c-11ea-9507-7cdfe0af4582.gif)

**Comment by OwainJ** [comment]
@kjac Thanks for looking into it! The back arrow that you're clicking in the gif works fine for me too on my 8.3 install, but it's the _"Return to list"_ button on the bottom right (next to save) that's failing for me. (although the url changes just like in #7182).

This issue does seem the hardest to reproduce though, as on one of our projects it occurs inconsistently, but on my vanilla 8.3 install it fails every time.

Gif showing that the back arrow works fine, whilst the _"Return to list"_ button fails:
![return to list 8-3 2](https://user-images.githubusercontent.com/17008780/69237737-42ab3700-0b8e-11ea-9aad-85b726a89e39.gif)

**Comment by kjac** [comment]
@OwainJ I see 😄 well I have good news: "Return to list" seems to work in vLatest as well:

![return-to-list](https://user-images.githubusercontent.com/7405322/69372128-6a3ef400-0ca1-11ea-950a-03b507d44c12.gif)

**Comment by OwainJ** [comment]
@kjac Awesome 😄 thanks for looking into this!
