### ISSUE TITLE
UX: Actions Menu Delete Option on Media Folder Confusion with Selected Child Items Delete

### ISSUE THREAD

**Issue by marcemarc** [umbraco/Umbraco-CMS#6930]
I have had two editors report this as a problem in the last month, so it's not necessarily an overwhelming concern for all Umbraco users that is effecting 'lots of people', but thought I'd document the issue in case people felt somehow the UX for this could be improved.

How to recreate the confusion.

Install the starter kit

Go to the Products folder in the media section

Select several media items to be deleted, they'll have a pink border, and a pink action menu will appear.

Go to delete - but accidentally go the 'Actions' Menu and choose the Delete option...

you'll be prompted with a message asking if you want to delete 'products'... you are deleting some products so click ok...

... the entire folder has been deleted!

If this is a top level folder - it can contain a ton of images, 

![accidentalfolderdelete](https://user-images.githubusercontent.com/260802/67717004-caa18500-f9c4-11e9-88e2-a0632713eb5d.png)

I think it is something to do with the eye being used to where the Actions menu is, because it is permanent and so looks past the temporary contextual Delete that they should obviously be selecting...

![image](https://user-images.githubusercontent.com/260802/67717112-00df0480-f9c5-11e9-9a51-f682f8dd5613.png)

I'm wondering two things:

1) could we disable the delete option on the Action menu - if items are selected to be deleted in the child items listview?
2) should top level folders be allowed to be deleted if they contain tons of images? - or should the warning be more dramatic? eg display the number of items that will be sent to the recycle bin?

**Comment by emma-hq** [comment]
Hey @marcemarc 

The good news is, we have disabled that actions menu now when child items in a list view are selected. The bad news is, we didn't say 'Yuh huh' to your issue here earlier. 

I'm closing it as it's all good and fixed. I like writing those words. 

Emma
