### ISSUE TITLE
V8 : Need ability to search images and files by their real names

### ISSUE THREAD

**Issue by saifobeidat** [umbraco/Umbraco-CMS#6937]
It would be a great idea if we could search images and files by their real name not only by their nodes' names.

I have a website with a large amount of media, and one day I wanted to compress the size of an image, I took its name from its URL and I searched for it in the media section but I didn't get any result, and I was saying how could that happen that I get no results while the image is exist on the website and I see it ?

Then I gave up and I decided to enter each folder to find it from hundred images, after I found it, I noticed that its name (image node name ) is different than it's name in the URL, and Umbraco is only able to search by image node name that's was the reason I couldn't find it.

**Comment by nul800sebastiaan** [comment]
We don't have this at the moment and I can't remember exactly why, for now you could implement `ISearchableTree` (https://our.umbraco.com/documentation/extending/section-trees/Searchable-Trees/)

I will ask around to see if searching on filename is something we want to have in there too.

**Comment by nul800sebastiaan** [comment]
I totally forgot, this is currently being worked on: https://github.com/umbraco/Umbraco-CMS/pull/6579

Make sure to follow the progress on that PR, I'll close this issue! 👍
