### ISSUE TITLE
Auto select Content-Group when configuring Nested Content if only one is present

### ISSUE THREAD

**Issue by nielslyngsoe** [umbraco/Umbraco-CMS#6945]
When configuring the Nested Content DataType. It would be nice if we could auto select the Content Group of ElementTypes if only one exists.

![image](https://user-images.githubusercontent.com/6791648/67771681-0dad3800-fa59-11e9-8fc9-450e1e04e4d5.png)

**Comment by kjac** [comment]
Yes! I'll have a look. If I'm not mistaken, NC will default to the first group if none is specified (at least it used to), but there's no reason not to preselect it.

**Comment by kjac** [comment]
Fixed in #6982
