### ISSUE TITLE
v8: Preview mode cannot open external URLs in same tab

### ISSUE THREAD

**Issue by rbottema** [umbraco/Umbraco-CMS#6960]
See title. Opening external links in the preview mode (only when they would open in the same tab) gives a browser error.

### Specifics

Tested with Umbraco 8.2.1 and Chrome 77.

### Steps to reproduce

- Add an external link on a page (e.g.: external link in a RTE)
- Open preview mode
- Click the external link

### Expected result

The link is opened, either within or outside the preview mode. Outside is acceptable, as the user can click 'back' in their browser anyway.

### Actual result

In Chrome, a gray page is shown with the test 'www.google.com refused to connect.'. Console shows the following: `Refused to display 'https://www.google.com/' in a frame because it set 'X-Frame-Options' to 'sameorigin'.`

**Comment by nul800sebastiaan** [comment]
Yeah, this is kind of inherent to using an iframe for the preview functionality. Browsers have started to lock down iframes by default and this is a really good thing. This also means that if someone linked to something by accident, they won't be giving a malicious actor full control over the active backoffice session either.

I've tried to fiddle with the `X-Frame-Options` header but I don't see any way to fix this at the moment. If you have any suggestions (apart from a complete rewrite of how the preview feature works, which seems necessary at some point anyway) then we're all ears.

**Comment by dawoe** [comment]
Hi @nul800sebastiaan 

Maybe the sandbox attribute on the iframe can help on this one : https://www.w3schools.com/tags/att_iframe_sandbox.asp

I think you can use the allow-popups value to allow target blank.

Dave

**Comment by nul800sebastiaan** [comment]
@dawoe that would just completely break the preview right? Adding `sandbox` will:

> treat the content as being from a unique origin
block form submission
block script execution
disable APIs
prevent links from targeting other browsing contexts
prevent content from using plugins (through `<embed>`, `<object>`, `<applet>`, or other)
prevent the content to navigate its top-level browsing context
block automatically triggered features (such as automatically playing a video or automatically focusing a form control)

**Comment by dawoe** [comment]
yep...but you can then open up things with sandbox attribute..like allow script, form submission. etc...

**Comment by nul800sebastiaan** [comment]
Aah yes, I didn't read further. Seems that you can only set 1 of these at a time though, which kinda makes it worse, I added `sandbox="allow-same-origin"` and then clicked the external link, which then gave me this:

![image](https://user-images.githubusercontent.com/304656/67862091-cc348f80-fb21-11e9-9e36-d67034b1683d.png)

Unfortunately adding multiple values to the `sandbox` attribute didn't work, or maybe I am doing it wrong (tried separating them by a space, comma and semicolon - browser tells me that comma and semicolon are invalid though).

**Comment by dawoe** [comment]
it should work space seperated https://developer.mozilla.org/en-US/docs/Web/HTML/Element/iframe

**Comment by stevemegson** [comment]
I think that the values for `sandbox` will only allow things that were blocked by adding the `sandbox` attribute. Hopefully there is nothing we can do to allow the external site to appear within the iframe. If we can, then the `X-Frame-Options` header is broken.

We could perhaps use the iframe's load event to attach a click handler to any external links inside the iframe, setting `target='_top'` to escape the iframe. That would only handle simple links to external URLs, and we might have to assume that any absolute URL is to be treated as external, but it could be a step in the right direction.

**Comment by nul800sebastiaan** [comment]
> it should work space seperated developer.mozilla.org/en-US/docs/Web/HTML/Element/iframe

I tried, it doesn't :-)

> We could perhaps use the iframe's load event to attach a click handler to any external links inside the iframe, setting target='_top' to escape the iframe.

That seems to work at least. For now, that might be the only solution.

Ultimately, I think we need to get away from using an iframe to do previews in, but that's a larger discussion on how that can work.

**Comment by umbracocommunity** [comment]
This issue has been mentioned on **Umbraco community forum**. There might be relevant details there:

https://forum.umbraco.com/t/how-to-integrate-the-same-external-login-provider-to-the-backoffice-and-the-frontend-site/7676/9
