### ISSUE TITLE
Caching issue after sorting childnodes -  Umbraco 8.2

### ISSUE THREAD

**Issue by ralphvanvugt** [umbraco/Umbraco-CMS#6971]
When sorting childnodes, the items disappear from the node above it in the view.

Reproduction
------------

Following situation:

Overview
- Child 1
- Child 2
- Child 3

The overview page shows an overview of the child nodes below. Normally, it wil show three items e.g. Child 1, Child 2 and Child 3.

When sorting the children in a different order, the overview only 1 child, sometimes 2, but not all three as expected.

A restart fixes the issue.

### Bug summary

Seems like sorting doesn't update the cache completely.

### Steps to reproduce

Overview
- Child 1
- Child 2
- Child 3

1. Sort the pages different like Child 3, Child 1, Child 2
2. Go to the front-end of the website and view the overview page
3. Only 1 item appears.

### Expected result

All child items should appear on the overview page in the correct order.

**Comment by nul800sebastiaan** [comment]
This is probably this exact problem: https://github.com/umbraco/Umbraco-CMS/issues/6698

Can you confirm that you're trying this on 8.2.0 please @ralphvanvugt ?

**Comment by ralphvanvugt** [comment]
Yes, it is Umbraco 8.2.0

**Comment by ralphvanvugt** [comment]
@nul800sebastiaan It seems to be fixed in 8.2.1

**Comment by nul800sebastiaan** [comment]
That's what I was meant to say yes! ;-) Thanks!
