### ISSUE TITLE
V8 Backoffice Info tab not fully responsive

### ISSUE THREAD

**Issue by kieronbos** [umbraco/Umbraco-CMS#6977]
I made a GIF animating this, https://gyazo.com/1679383c7075dac12b2aa48797117ad6

Its only a couple of styles that allow at-least the links and history sections to be fully responsive down to around 210 pixels, (lower than it ever needs to go).

Im submitting just incase someone has already tackled it, if not, id love to try it.

Reproduction
------------

Simply open the backoffice and navigate to the Info section of a content item, resize your browser down, and you will find some `min-width` styles that stop the sections from shrinking, along with an image class that needs tweaking to allow auto width.

--

Im going to check its not going to adversely affect anything else in the back office also, but first trying to find if someones handled this already :-)

**Comment by abjerner** [comment]
Hi @kieronbos,

Thanks for taking the time to create this issue 👍 

Mobile viewports are not something that is supported - neither in V7 or V8. Supporting this would require a lot of extra work, so it hasn't been an area of focus.

Starting to add partial support for mobile viewports (eg. through a PR) would also create an extra step for Umbraco to test - eg. to make sure it doesn't break between releases. And as Umbraco doesn't have any plans for support this in near future, a PR that fixes the issue you've described will most likely not be accepted.

I hope that makes sense 😉

**Comment by nul800sebastiaan** [comment]
Just to confirm from HQ: we're not planning support for mobile devices, Umbraco works relatively well on tablets and we'll look at fixing tablet issues if they occur but mobile viewports are not our focus.
