### ISSUE TITLE
Gulp watcher slightly broken

### ISSUE THREAD

**Issue by BatJan** [umbraco/Umbraco-CMS#6981]
It appears to me that there is still an issue with the watch task - I'll try to describe it as best as I can since it's a bit tricky.

So I worked on a #6979 and I noticed that whenever I made changes in the rte.prevalues the changes took effect immediately. However when I made changes to the umb-checkbox.html view the changes did not take effect until I saved the umbcheckbox.directive.js - Then I could see the changes from the view as well.

I hope my brief explanation makes sense and is enough for you to experiment with - I'll update this issue if I figure out what's going on or have further clues.

**Comment by nul800sebastiaan** [comment]
Whoops, I should've captured a smaller screen area, sorry for the huge gif! But .. it seems to work for me. Which gulp task did you run? I tried with `fastdev` and `watch` and both worked.

![6981](https://user-images.githubusercontent.com/304656/67877341-af0bbb00-fb39-11e9-91b2-3775fb1cfec2.gif)
