### ISSUE TITLE
TextBox and TextArea limits are not enforced by validation

### ISSUE THREAD

**Issue by nielslyngsoe** [umbraco/Umbraco-CMS#7005]
TextBox and TextArea DataType limits(minimum and maximum amount of characters) are not preventing Save or Save & Publishing. Said in other words they are not begin validated.
We have a great indication of whether the limit is met, but we need to ensure that the validation kicks in.
![image](https://user-images.githubusercontent.com/6791648/67929151-ecfdf300-fbbc-11e9-8e53-83fb61ebd741.png)
For similar code/solution see how validation is done for Nested Content in PR https://github.com/umbraco/Umbraco-CMS/pull/6823

**Comment by kjac** [comment]
@rosrosros tackled this yesterday - see https://github.com/umbraco/Umbraco-CMS/pull/6989

**Comment by kjac** [comment]
Also cross linking to #5914

**Comment by nielslyngsoe** [comment]
@kjac thanks for linking these

**Comment by kjac** [comment]
Fixed by #6989
