### ISSUE TITLE
Change password on users should open a dialog

### ISSUE THREAD

**Issue by nielslyngsoe** [umbraco/Umbraco-CMS#7013]
The current user experience when changing the password on a User in the User Section is not optimal.
My 50 cents on what's wrong with the current solution:
— The inputs appear in the existing context leaving a lot of noise around the simple task of changing the password.
— We only show a cancel button, leaving the user with doubt if they want to save the change.

Here a GIF of the current experience:
![BwMcW4Tx7p](https://user-images.githubusercontent.com/6791648/67951290-8217e080-fbeb-11e9-91ee-95a3f994aa53.gif)

Instead, I propose that the form for changing the password appears in a dialog/overlay, looking something like this:
![image](https://user-images.githubusercontent.com/6791648/67951212-5eed3100-fbeb-11e9-956f-70a582241f39.png)

The confirm password, should save the password on the user, so your not relying on pressing Save for the user.

**Comment by bjarnef** [comment]
@nielslyngsoe maybe this should also be changed on "change password" for members as well, so it is a bit more consistent?

**Comment by nathanwoulfe** [comment]
Moving discussion back here rather than on the PR - with regard to making the dialog change for members, I think it needs further consideration.

On the member view, the password fields present as standard property editor inputs, so the current behaviour aligns with editing a content node - make changes, then save the entire object. I'm wondering if using the dialog here is a departure from the expected UI behaviour, and might introduce rather than reduce complexity?

There's also the reset password checkbox to consider - it would be in the dialog, but would display the new password back in the main view.

Maybe password fields for member should be managed separate to the rest of the view, more like they are in the user views?

@bjarnef @nielslyngsoe appreciate your thoughts...

**Comment by nielslyngsoe** [comment]
@nathanwoulfe Good thoughts, I agree. This is a bigger change.

And I think your right, the right way to deal with the password would be to separate it from the member-content-view.

The user would expect everything inside the member-content-view to first be saved when clicking save.

That is slightly different for the info tab I would say, I think it could be slightly natural to change password from a button in the info-tab, but I'm not sure it's such a great improvement. It would make it less obvious that you can change the password, it would be distant from the content for a member, I'm not sure that feels correct. But feel free to provide a Draft on this, if you don't feel its right I think we should keep it as it is. It might require a bigger UX change where these properties get another space to live.

![image](https://user-images.githubusercontent.com/6791648/72413467-2384ec00-3770-11ea-9c28-8f3914a4333c.png)


@bjarnef how do you feel about it, is there another opportunity that we should concider?

**Comment by nathanwoulfe** [comment]
@nielslyngsoe, @bjarnef Is the question here whether members should be presented similar to content or similar to users? Would it be useful for members to display info like last login, created date etc as we do for users?

**Comment by bjarnef** [comment]
@nielslyngsoe @nathanwoulfe content, media and member have many similar features, but only member has the password functionality, which at the moment doesn't look great in the edit page. Not sure if change password is the primary task on member, but an important task. Maybe it should be placed in a separate tab under e.g. info tab and open a password overlay by clicking a button.

**Comment by nielslyngsoe** [comment]
> Would it be useful for members to display info like last login, created date etc as we do for users?
@nathanwoulfe which we actually have moved to the info tab in the latest version. 8.4 I think. :-) (Since Content-Apps for Members have been enabled.)

@bjarnef I think it could be moved to Info, but we need to be aware that the credentials(Login, email, password) should be somehow placed together, so we would have to move those to the info-tab as well? Which could work, but it doesn't feel totally right for me currently. But feel free to provide a Draft PR or sketches then we have something to show and hear what people think about it.

It could also be that all credentials should go somewhere else, what works great for the Users Section is that they have the Info-column, in this way the password-change button doesn't get too far from the e-mail.
![image](https://user-images.githubusercontent.com/6791648/72501303-c011c180-3836-11ea-86f9-b2d0b0b6d7fc.png)
But it wouldn't make sense to have a Info-tab and an Info-column, so that's not directly adaptable.
