### ISSUE TITLE
umbraco 8 UX suggestion: context highlight background colour

### ISSUE THREAD

**Issue by shearer3000** [umbraco/Umbraco-CMS#7026]
hello

The pale red colour (#f5c1bc) used as the background in various places to highlight context is too similar to validation styling (required/invalid field). This can cause slight confusion for content editors.

Is it possible to use a different colour? 

Thanks

ref: original forum topic
https://our.umbraco.com/forum/using-umbraco-and-getting-started//99611-umbraco-8-ux-suggestion-context-highlight-background-colour

**Comment by nul800sebastiaan** [comment]
From what I understand from my colleague is that we deliberately chose a lighter pink color so as not to make it confusing with the red validation color. 

Can you elaborate more on the confusion for content editors? What problems do they run into and where? How often does this break their workflow approximately? 

We'll have a chat at HQ about this and remember that, for now, you could make a App_Plugin that includes a stylesheet that could override any colors you want.
