### ISSUE TITLE
Install Umbraco > Configure your database screen language discrepancies

### ISSUE THREAD

**Issue by lssweatherhead** [umbraco/Umbraco-CMS#7033]
On the Install Umbraco > Configure your database screen, there are a few discrepancies in the use of English. Please see screenshots below...

Reproduction
------------

![image](https://user-images.githubusercontent.com/6873029/67986884-ff5f4780-fc23-11e9-983a-a62917eb3e88.png)

Problematic phrasing on "Great!, no need to configure..."

![image](https://user-images.githubusercontent.com/6873029/67986939-2289f700-fc24-11e9-86e8-e3bd718fa05b.png)

"databaseuser" all one word and inconsistent - why not "umbraco-database-user" or similar inline with the other placeholders?

![image](https://user-images.githubusercontent.com/6873029/67987129-93c9aa00-fc24-11e9-91bd-e6a2ed967791.png)

"connectionstring" all one word

**Comment by kjac** [comment]
Fixed by #7034
