### ISSUE TITLE
Content "Content App" drop down menu opens when hovering over too large an area

### ISSUE THREAD

**Issue by carbonsixdigitalpbm** [umbraco/Umbraco-CMS#7043]
Reproduction
------------
Hovering the mouse near the Content "Content App" menu drop down on a content node causes the menu top open, even though you may not be hovering over the Content button itself.  The effect of this is to stop users from clicking on anything that is under that menu e.g. if you have a list view you can't switch between grid and list view, because the buttons are under, and become obscured by the Content drop down menu.

### Bug summary

AFAIK it only affects pages with multiple sections, but then it affects every documenttype and page.

### Specifics

URL: /umbraco#/content/content/edit/{{NODE ID}}
Version of Umbraco 8.2.0
Browser: Chome on Windows 77.0.3865.120. 

The problem doesn't affect Edge, but then the Content Sections Drop Down Menu doens't appear at all on Edge (which is probably a different problem) :) .

### Steps to reproduce

Add multiple sections to a document type.  hover in the vicinity of Content Drop Down menu (not over the button), and you'll see the menu appear.

Screenshot 1) Shows what I tried to click on 
![image](https://user-images.githubusercontent.com/8429659/68031608-eb632680-fcb3-11e9-9da1-553a8ab02a4c.png)

Screenshot 2) Shows the menu that appears.  ![image](https://snipboard.io/dRGFmw.jpg)  Note if i hover anywhere within the red bounding box in my sketch the menu appears, therefore I can never get to the menu underneath.

### Expected result

I'd expect the drop down menu to only show when I hover over the Content button.

### Actual result

See screenshots in Steps to reproduce.

**Comment by nul800sebastiaan** [comment]
Thanks @carbonsixdigitalpbm and suuuuper annoying, we agree. Hence, it's been fixed for 8.2.1 - https://github.com/umbraco/Umbraco-CMS/issues/6430

Only a few small changes in 8.2.1 so it's a quick upgrade. https://our.umbraco.com/download/releases/821

If you are using the Grid you might want to wait until Tuesday's release of 8.2.2, which fixes another annoying issue when re-ordering items in the Grid: https://our.umbraco.com/download/releases/822

**Comment by carbonsixdigitalpbm** [comment]
I should have updated before raising it.  I just did the update and it did resolve.  Thanks Seb.
