### ISSUE TITLE
Free-text filtering users when on page 2+ doesn't show results

### ISSUE THREAD

**Issue by stevetemple** [umbraco/Umbraco-CMS#7047]
If you have 2 pages of users, go to page 2 and then start filtering. It will say there are several results but they won't show. Presumably because it's trying to show page 2 of the filtered results and there are less than 1 page worth of results.

Filtering should reset the page back to page 1 so that it shows the first page of the filtered results.

## Umbraco version

I am seeing this issue on Umbraco version: 8.1.5

### Steps to reproduce

Create more than 1 page of users.
Go to users list
Switch to page 2
Enter text to filter users so that less than 1 page of results are shown

### Expected result

I expected to see the users that matched the filter

### Actual result

I see no results but I do get the correct "Users (2)" in the top left

**Comment by kjac** [comment]
I can reproduce this, PR incoming.

**Comment by stevetemple** [comment]
Hi Kenn, I also have a PR incoming!

**Comment by kjac** [comment]
...oh. That was silly. 

The second PR (#7049) also solves the related issue for filtering.

**Comment by stevetemple** [comment]
I'd only created the issue to submit the PR, anyway looks like you also cover the filter dropdowns with that?

**Comment by kjac** [comment]
@stevetemple yep I found (and fixed) the filtering issue while testing your issue report 😄
