### ISSUE TITLE
Examine Search Range Query error on Date Time

### ISSUE THREAD

**Issue by MosabAbuzaid** [umbraco/Umbraco-CMS#7050]
Hi
I want to write an examine search that return files between tow dates come from property value so i tried to use range query and here is my code :

```csharp
var searcher = indx.GetSearcher();
ISearchResults results = null;
results = searcher.CreateQuery()
.Field("path", Umbraco.Media(124111).Path.MultipleCharacterWildcard()).And()
.Field("__NodeTypeAlias", "File").And()
.RangeQuery<DateTime>("fileDate".Split(','),Convert.ToDateTime("04/06/2017"),DateTime.Now)
.Execute();
```

but i faced this error :

![image](https://user-images.githubusercontent.com/38281155/68134120-51f17a00-ff2a-11e9-95ce-45ae5da5b472.png)

**Comment by nul800sebastiaan** [comment]
Hey @MosabAbuzaid, I think your `fileDate` field is indexed as a text field and not as a date field, you might need to update that.

I would recommend you head to the forums where our friendly community can help you find the best solution for your requirements. 
Make sure to head on over to https://our.umbraco.com and ask follow up questions there! 👍
