### ISSUE TITLE
Don't use ">>" in dashboard content

### ISSUE THREAD

**Issue by BatJan** [umbraco/Umbraco-CMS#7055]
I am filing this issue since the people working on improving accessibility within the Umbraco backoffice have discovered that the dashboard in the "Content" section is using ">>" text arrows in the content and since the content is served from another Umbraco instance we can't fix this. 

In his reply to @MMasey tweet about the notes from the accessibility online meeting yesterday @jmoumbraco mentioned that we should feel free to file these issues on the issue tracker - So here it is 😃 

Specifically the "arrows" come from the "buttonText" in this JSON feed https://dashboard.umbraco.org/content?section=content&allowed=content,forms,media,member,packages,settings,translation,users&lang=en-US&version=8.1.0

Please stop using them since they will be announced by screen readers - Not a big issue but I can imagine it must be a bit annoying hearing it being announced. So instead it would be better to have an icon implemented for making an arrow in the markup. That will also look much prettier 😉 

Make sure to hide the icon adding `aria-hidden="true"` to the element containing the icon ensuring that no screen reader will try to announce the icon.

![arrows](https://user-images.githubusercontent.com/1932158/68187253-830f9000-ffa6-11e9-8730-52adfb67e498.png)

**Comment by nul800sebastiaan** [comment]
Thanks @BatJan, I'll need to get someone from our team to look at it!

**Comment by nul800sebastiaan** [comment]
Thanks @BatJan - after a bit of a delay this has now been fixed! 👍
