### ISSUE TITLE
Include Prism for code snippets

### ISSUE THREAD

**Issue by bjarnef** [umbraco/Umbraco-CMS#7060]
I wonder if it would be useful to include Prism for code snippets, e.g. to create a code snippet component, which could be used in query builder: https://github.com/umbraco/Umbraco-CMS/pull/6584

It could also be useful in packager view after installation to show code snippets (sometimes developers need to insert a few code snippets in e.g. views after installation of a package.

This could also be useful in TinyMCE editor, which support Prism be default to allow inserting code samples: https://www.tiny.cloud/docs-4x/plugins/codesample/

**Comment by bjarnef** [comment]
@nielslyngsoe any thoughts on this?

**Comment by nielslyngsoe** [comment]
@bjarnef interesting, I see that Sebastiaan already put it in for our talk on monday, so after that you will hear from us. :-)

**Comment by bjarnef** [comment]
@nielslyngsoe I agree using the code samples in TinyMCE is mostly for developers/geeks, but it might also be useful in the new block editor, e.g. for blog posts https://shazwazza.com/post/how-to-register-mvc-controllers-shipped-with-a-class-library-in-aspnet-core/

**Comment by nul800sebastiaan** [comment]
Hi @bjarnef - we're a little reluctant to add another library, although this is a small one, but we're considering it as an option. Unfortunately Razor support has been a feature request for 2 years (https://github.com/PrismJS/prism/issues/1225), which is quite limiting in the context of Umbraco.

The other option we thought of, and this would probably be preferred, is to look at re-using Ace in read-only mode. Could you play with that first and see if it makes sense to use that?

As for the block editor, I would think it's very often used, only few people use Umbraco to publish code snippets in their content, so I would see that as a plugin for Umbraco.

**Comment by emma-hq** [comment]
Hey folks,

The fix for this was merged in #7294 so I'm going to close this one. Thanks for your work @bjarnef 

Emma
