### ISSUE TITLE
Multiple select on tree for setting permissions for groups or users is not working

### ISSUE THREAD

**Issue by goldshteinavi** [umbraco/Umbraco-CMS#7063]
In Umbraco user management there is an option of multi select for several child nodes but at the end there is no Submit button. see attached screen shot.
I've opened a case at Umbraco support #47350.
This is the answer of the supporter Jakob Nawrocki:
Hello Avi and thank you for reaching out to us!
I was able to reproduce this just now on a new Cloud v8 installation. It seems to be a bug with the user management - thank you so much for finding this!
Would you mind filing it on our Issue Tracker at https://github.com/umbraco/Umbraco-CMS/issues ?
Unfortunately, at the moment I cannot offer you a workaround other than adding nodes one by one.

## Umbraco version: Umbraco version 7.14.0 assembly: 1.0.7009.26199

I am seeing this issue on Umbraco version: 

Reproduction
------------

If you're filing a bug, please describe how to reproduce it. Include as much
relevant information as possible, such as:

### Steps to reproduce

    Steps to reproduce:
1. click on Add at Granular permissions
2. mark child node
3. Click on cancel
4. mark other child node
5. click sumbit then only the last node will be added to the Granular permissions but the other checked child nodes are not added
![Capture](https://user-images.githubusercontent.com/57407986/68225435-1671b100-fff9-11e9-8f88-59d40634e98f.JPG)

**Comment by nul800sebastiaan** [comment]
Thanks, I would recommend you update to the latest v7 (7.15.3) where this dialog has been improved, you can only choose one node at a time, after which you need to provide the granular permissions you need for that node. This is expected behavior.

![7063](https://user-images.githubusercontent.com/304656/68369827-7b352480-013b-11ea-8a4a-796d01541fc3.gif)
