### ISSUE TITLE
Media items disappear from Memory Cache

### ISSUE THREAD

**Issue by Zweben** [umbraco/Umbraco-CMS#7064]
I have noticed on several occasions on my Umbraco Cloud Development environment, and possibly on my Umbraco Cloud Live environment (harder to tell due to debug off) that the media items have entirely disappeared from the memory cache after performing certain actions.

I can provide logs upon request. Unfortunately I wasn't able to download a memory dump (nothing happened when I clicked the button in Kudu) or access the Dev database to download the NuCache tables (firewall error, even though my IP is whitelisted and Live works.)

## Umbraco version

I am seeing this issue on Umbraco version 8.2.1

Reproduction
------------

### Bug summary

- All media items disappear from the memory cache (status says "MediaStore contains 0 items and has 1 generation and 1 snapshot.")
- Reloading the memory cache from the DB cache in the backoffice restores the missing cache content.

### Specifics

- I have observed this most recently after doing a partial content restore from Umbraco Cloud Live to Dev, but I believe it has happened after deployment in the Cloud portal as well.

### Steps to reproduce

- Restore content, or do something else that causes the cache to update.

**Comment by nul800sebastiaan** [comment]
Hi @Zweben, we released 8.2.2 two days ago with a NuCache fix that sounds like it might help for you: #7002

Can you give that a spin please?

**Comment by Zweben** [comment]
@nul800sebastiaan Thanks. I don't see any mention of 8.2.2 in the project's Cloud portal, though. Is it a staged or delayed roll-out to Cloud? Was it just held back if our environments were out of sync? Any way to trigger the upgrade without doing it manually on a local machine?
