### ISSUE TITLE
Setting up instance of Umbraco site with custom migrations

### ISSUE THREAD

**Issue by antonysmith-mando** [umbraco/Umbraco-CMS#7065]
Since adding custom migrations to an Umbraco site I can no longer re-run the installer in order to set the site up on a new development machine. This may well be known/expected behaviour but I thought I'd raise it in case it wasn't!

## Umbraco version

I am seeing this issue on Umbraco version: 8.1.5

Reproduction
------------

If you're filing a bug, please describe how to reproduce it. Include as much
relevant information as possible, such as:

### Bug summary

I'm currently working on an Umbraco site in a multi-developer environment and I'm working through the process of setting up a new local development environment from source control. We're using SQL Server as the database provider so the database is not included in the source. 

At the start of the project, the instructions stated that users, after cloning, should clear the value of the Umbraco.Core.ConfigurationStatus appSetting and clear the configured connection string in order to run the installer (which I believe is the correct way to do so). However, this no longer works. 

### Specifics

As part of the build, we've added custom migrations via Components. When I run the project with debugging, it's in the Initialize method of a Component that I get a System.InvalidOperationException with the message The factory has not been configured with a proper connection string.

That led me to believe that I needed a database already in place to run the migrations on so I created a database and configured my connection string but now I get a System.Data.SqlClient.SqlException with the message Cannot find the object "umbracoLock" because it does not exist or you do not have permissions.

### Steps to reproduce

1. Create an Umbraco website using v8.1.5
2. Add custom migrations to the site via Components
3. Attempt to re-run the installer (as if another developer was attempting to create an instance of the site on their local machine)

### Expected result

Database can be set up by running the installer rather than having to restore a backup

### Actual result

Database backup is required in order for a database to be created containing custom migrations

**Comment by antonysmith-mando** [comment]
I've just tried scripting the schema from the existing database and running it in the new database. I thought I could at least check that in and have users update their database using it (though it would be a pain remembering to update it after any further migrations).

However, that doesn't work because Umbraco.Core.Migrations.Upgrade.Upgrader.Execute updates records in the umbracoLock table which don't exist in an empty database.

**Comment by nul800sebastiaan** [comment]
Hi there @antonysmith-mando - that's definitely not the right way to do it, but I understand this might have worked in v7.

Migrations run exactly once and then their state is stored in the database, in the `UmbracoKeyValue` table.

For more inspiration on how to achieve what you're trying to do I would refer you to the forums where our friendly community can help you find the best solution for your requirements. 
Make sure to head on over to https://our.umbraco.com and ask follow up questions there! 👍

**Comment by antonysmith-mando** [comment]
Hi @nul800sebastiaan, thanks for getting back to me.

I took your advice and started a [topic](https://our.umbraco.com/forum/using-umbraco-and-getting-started/99887-re-creating-an-umbraco-sites-database-with-custom-migrations) on the forum but I haven't had any responses as yet.

I appreciate and understand your response but I'm not sure it answers my question. I understand that migrations are only ran once and are then stored in the database.

However, my question is how that migration can then be run against a new database, that therefore doesn't have any state stored in it.

I would expect that Umbraco would do its normal checks to see if a database exists, run the installer if not and **then** run the migrations. However, the behaviour that I'm seeing suggests that the migrations are being run first which doesn't work because the database is not yet there.

Is my expectation completely wrong, unreasonable and unfeasible? Is there a way to make Umbraco behave as I expect?

I'd be very grateful for any advice.

Thanks

**Comment by antonysmith-mando** [comment]
The fantastic Kevin Jump helped me get this sorted. My issue was not implementing IUserComposer, being lazy and using the ComponentComposer<> base class instead! Lesson learned...
