### ISSUE TITLE
Values with comma in Dropdown (Umbraco.DropDown.Flexible) are corrupted

### ISSUE THREAD

**Issue by titarenkoev** [umbraco/Umbraco-CMS#7069]
I create a new DataType. Choose Dropdown (Umbraco.DropDown.Flexible)  in Property Editor. Add some prevalues with comma (","), for example "One, two and three". But in my code I see only "One" as value.

It worked fine for "Umbraco.DropDown" alias type, but after Umbraco updating I can't choose this data type in Property Editor.

Umbraco version 7.14.0

**Comment by nul800sebastiaan** [comment]
Hey there @titarenkoev - make sure to upgrade to 7.15.3 (the latest v7 version) and try again. If you can reproduce the problem in that version as well then let us now. For now I'll close this issue 👍

**Comment by stevemegson** [comment]
It'll be true in 7.15.3 too. We just do a String.Join with commas and later a String.Split on commas, so any commas in the values will be treated as delimiters. I'm not sure there's a nice non-breaking solution, though. For single-valued properties we could not do the Split. I guess that's technically breaking if the property used to allow multiple selections and you're now relying on the Split to return only the first value.
