### ISSUE TITLE
Umbraco future versions?

### ISSUE THREAD

**Issue by bielu** [umbraco/Umbraco-CMS#7070]
Last week when I was looking into:
https://our.umbraco.com/download/releases/830
I was able to see around 100 fixed issues, now I am seeing only 3, as most of the issues tagged with 8.3 were change to 8.4. Is it something that is correct or it is just done by mistake?
I am asking as some of the changes were quite important for external packages.

**Comment by dawoe** [comment]
Hi @bielu 

8.3 will be a intermediate release. The merged hacktober fest PR's will be part of 8.4 which is aimed at early december 

https://umbraco.com/blog/umbraco-product-update-november-5th-2019

Dave

**Comment by bielu** [comment]
Hi @dawoe,
I don't think so three small issues should be called Minor version. I think it should be just moved the date of release of 8.3 as listed changes IMHO should be only patch version.
I know it is not our decision bust still, it doesn't make sense to release 8.3 with only three changes...
