### ISSUE TITLE
NuCache

### ISSUE THREAD

**Issue by Ric-Carey** [umbraco/Umbraco-CMS#7073]
Hello all,

Little hard to describe this one, but thought I would raise.

We have a project running on Umbraco Cloud. Began life on V8.1.5 I then upgraded to 8.2. 

The client/editors have reported quite a few occasions where content isn't displaying correctly or functions within the CMS are not working. Having worked in Umbraco for along time, and seen these types of issues across versions, the first thing I do is rebuild the cache - using the new Memory Cache and Database Cache reload buttons. Which then fixes the issue. 

I am a little concerned in the amount of times I have had to do this, it is not a big project but the cache seems to be getting itself "muddled up" quite alot. I am not sure if this is occurring when the site has been inactive or recently deployed to? Or what is actually causing the issue. Naturally the bug isn't really able to be recreated, it is just one of those "its happened" sort of issues. 

The most recent example was an editor moved a number of articles from one node to another, which led to on the front end them appearing in the wrong place (using Model.Children) but the correct place in the back office. Rebuild cache and it was resolved. This is fine to fix before the site has gone live, but not ideal for when it launches.

I also had a series of bugs reported by the client which I couldn't reproduce which were all functions in the CMS (such as bulk media uploads failing), I had put this down to user error or the browser using too much RAM and failing after a long session of editing, but I am starting to think this could be connected internally with the cache etc?

Have any other similar reports been made on V8?  Naturally, I have seen these types of issues in V6/V7 with examining and V4 with the XML cache.

Cheers
Ric

**Comment by nul800sebastiaan** [comment]
Hi there @Ric-Carey! I understand your concern. You didn't specify which version of Umbraco you're running but we released 8.2.2 two days ago with a NuCache fix that sounds like it might help for you: https://github.com/umbraco/Umbraco-CMS/pull/7002

Can you give that a spin please?

I'm going to close this for now, but make sure to update this issue if the problems continue.
