### ISSUE TITLE
umbraco 8 UX suggestion: search icon location

### ISSUE THREAD

**Issue by shearer3000** [umbraco/Umbraco-CMS#7076]
Hi - The current location on the far right is slightly disassociated from everything else, and a more prominent location for content editors who frequently search could be before the content menu (see screenshot).

![search-icon](https://user-images.githubusercontent.com/2433680/68325158-c0525a00-012d-11ea-8047-bf4003f14d6e.png)

:)

**Comment by nul800sebastiaan** [comment]
I do believe the top menu is supposed to be sorted by the most common actions people would use and that would not really be the search for most people. We'll have a chat about it at our next HQ meeting though and will provide some more feedback.

**Comment by emma-hq** [comment]
Hey @shearer3000,

I'm going to close this issue as the search has now been moved to the right hand side, alongside the help and about icons. 

Emma
