### ISSUE TITLE
The copy of a the media folder lose his functionality.

### ISSUE THREAD

**Issue by cmwalolo** [umbraco/Umbraco-CMS#7077]
I wanted to use different crop settings for images on a multisite instance. To achieve this I copied the default media folder and image, changed the permissions of the new media folder to accept the new image mediatype. Everything is working, but now I see that the new media folder does not behaves has the original one : 

- There is no multiple upload control
- There is no listview

The original media folder has no listview settings, and I don't find anything that can configure the original behavior of a media folder.

Original Media Folder 
![image](https://user-images.githubusercontent.com/8546171/68329798-58baf100-00d2-11ea-9e38-cec3a5a6a715.png)

Copied Media Folder

![image](https://user-images.githubusercontent.com/8546171/68329832-6bcdc100-00d2-11ea-96fd-689f5fd6e96f.png)

**Comment by nul800sebastiaan** [comment]
I am not sure how you've copied that folder but there is nothing in the UI that will allow you to do that. Maybe you've done it through code? In which case.. something went wrong, as you've noticed! 😉

This sounds like an excellent question for the forums where our friendly community can help you find the best solution for your requirements. 
Make sure to head on over to https://our.umbraco.com and ask follow up questions there! 👍

**Comment by cmwalolo** [comment]
The original media folder does not have the listview activated, but it shows the listview and the multiple upload component, while you can still navigate through the treevizw.
When you copy that image folder , we don't have the listview anymore. If found out that if you acvtivate the listview it will show the children and the, multiple upload component. But at that time you lose the possibility to navigate through the treeview.

**Comment by stevemegson** [comment]
@cmwalolo I think you're talking about copying the `Folder` media type rather than copying the root folder in the Media tree, right?
