### ISSUE TITLE
Unseal MemberAuthorizeAttribute

### ISSUE THREAD

**Issue by Domitnator** [umbraco/Umbraco-CMS#7079]
Hi Guys,

I have connected Umbraco 8.2 with Azure B2C so that members can login with their Azure B2C Account. We used the the UmbracoIdentity NuGet package for that (https://github.com/Shazwazza/UmbracoIdentity).

I needed to create my own AuthorizeAttribute to do a proper redirect to Azure B2C when someone is not logged in and is accessing a route which is requiring authentication (in our case the portal part of the website).

I wanted my custom AuthorizeAttribute to inherit from MemberAuthorizeAttribute but this is not possible because that class is sealed:

[https://github.com/umbraco/Umbraco-CMS/blob/853087a75044b814df458457dc9a1f778cc89749/src/Umbraco.Web/Mvc/MemberAuthorizeAttribute.cs](https://github.com/umbraco/Umbraco-CMS/blob/853087a75044b814df458457dc9a1f778cc89749/src/Umbraco.Web/Mvc/MemberAuthorizeAttribute.cs)

I was wondering why this class is sealed? Would it be a good idea to remove the sealed modifier and let people inherit from it? Now i basically copied and pasted the whole MemberAuthorizeAttribute.cs code into my custom AuthorizeAttribute and made the change i wanted in the "HandleUnauthorizedRequest" method.

Would love to hear your thoughts. If more people would agree i will be happy to create a PR.

Kind Regards,

Alfred

**Comment by nul800sebastiaan** [comment]
Thanks @Domitnator, it is common practice to seal attributes:

https://stackoverflow.com/questions/7868218/why-is-net-best-practice-to-design-custom-attributes-as-sealed

https://docs.microsoft.com/visualstudio/code-quality/ca1813-avoid-unsealed-attributes

>  Attributes are simply metadata discovered at runtime. As it is quoted, if someone else derives from your custom attribute class, by default .NET will find them too, which may imply a security risk if the derived attribute class is modifying the behavior of your original attribute in a way to you never intended to.

From my conversation at HQ I understand you could wrap our custom attribute without having to copy all of it's code.

I'll close this issue for now as we don't plan to unseal the attribute.
