### ISSUE TITLE
Error when upgrading from umbraco 7.14 to 7.15

### ISSUE THREAD

**Issue by raoshilpa11** [umbraco/Umbraco-CMS#7110]
I am trying to upgrade umbraco from 7.14 to 7.15 but when i do that, the solution builds well but I am unable to run the application. Shows the below error

Description: An error occurred during the processing of a configuration file required to service this request. Please review the specific error details below and modify your configuration file appropriately.

Parser Error Message: Could not load file or assembly 'System.Web.Http, Version=5.2.3.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)

Assembly Load Trace: The following information can be helpful to determine why the assembly 'System.Web.Http, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' could not be loaded.

WRN: Assembly binding logging is turned OFF.
To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.
Note: There is some performance penalty associated with assembly bind failure logging.
To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].

Any help would be appreciated!

**Comment by nul800sebastiaan** [comment]
Hi there @raoshilpa11 Luckily this is not the experience most people have, it seems like there is something wrong with your specific setup. This is an excellent question for the forums where our friendly community can help you find the best solution for your requirements. 
Make sure to head on over to https://our.umbraco.com and ask follow up questions there! 👍
