### ISSUE TITLE
Nested Content w/ Min & Max Items

### ISSUE THREAD

**Issue by antonysmith-mando** [umbraco/Umbraco-CMS#7117]
## Umbraco version

I am seeing this issue on Umbraco version: 8.1.5

Reproduction
------------

### Bug summary

When creating a Nested Content data type, with multiple allowed Document Types, only one of those Document Types can be used if the Min Items and Max Items values both have the same (non-zero) value.

### Steps to reproduce

1. Create a new Data Type of type Nested Content
2. Add more than 1 Document Type
3. Set the Min Items and Max Items to 3
4. Add the Data Type to a Document Type
5. Create a content page using the Document Type
6. See that 3 items have been automatically added to the data type and are all of 1 of the 2 allowed Document Types. It is not possible to add/remove any of the items in order to add items of the other allowed Document Type

### Expected result

I expected that I would be able to add items of either of the two allowed Document Types and that validation would prevent me saving the page until I had added 3 items,

### Actual result

3 items of one of the two allowed Document Types were pre-added and couldn't be modified in any way to allow me to add items of the other allowed Document Type

**Comment by kjac** [comment]
Hi @antonysmith-mando ... this sounds strangely familiar. I think #5429 might solve it?

**Comment by antonysmith-mando** [comment]
Hi @kjac, thanks for that! Sorry, I did search but obviously not well enough. I'll keep an eye out for when this is included in a release (unless you tell me that my searching has been rubbish again and it has actually already been released!).
