### ISSUE TITLE
[Discussion] Kill Umbraco Package Format

### ISSUE THREAD

**Issue by bielu** [umbraco/Umbraco-CMS#7118]
As most of the creators of the package are actually forced to do packages in 2 formats: Umbraco and Nuget. I thinks it should be considered to kill Umbraco Package Feed as actually it is quite often out of date as it is required to upload packages by hand (I know Niels show way of doing that from cmd, but it is not changing anything). I think we should use one source of packages and it is should be NuGet. When I am speaking with developers most of the people are not using Umbraco Packages, but most of the arguments to stay with Umbraco packages is: 

- Possibility of install packages from back-office:
  It is possible to install NuGet packages from software and manage them in the same way as Umbraco Packages
- Umbraco Packages allows for import content (used in Starter Kits and some content packages):
  It could be easily reimplemented to works with NuGet Packages as we have a tool called migrations
- Umbraco Packages could be created from Backoffice:
  It is possible to create a NuGet package from c# code(I know it is outdated but it is just example): https://stackoverflow.com/questions/6808868/how-to-create-a-nuget-package-using-nuget-core

I think that change could improve the experience of packages creators and developers.:

- For packages creators, it is only one format to support. 
- for a developer which are using CI/CD, it is easier to manage packages as they will be always available on NuGet feed (what will remove the requirement of include packages files into source code as they will resolve directly from NuGet)

**Comment by Shazwazza** [comment]
see https://github.com/umbraco/Umbraco.Packages/issues/19

**Comment by bielu** [comment]
@Shazwazza almost everything is contained in that issue which you linked excluding using one feed for packages, I am going to close that issue and move my comment to linked issue.
