### ISSUE TITLE
Search component has hardcoded (non-translatable) placeholder and clear-text.

### ISSUE THREAD

**Issue by Adolfi** [umbraco/Umbraco-CMS#7121]
## Bug summary
Search component has hardcoded (non-translatable) placeholder and clear-text.

### Umbraco version
I am seeing this issue on Umbraco version: 8.3.0

### Specifics
Hardcoded file: https://github.com/umbraco/Umbraco-CMS/blob/v8/dev/src/Umbraco.Web.UI.Client/src/views/components/application/umb-search.html.
Input placeholder ‘Search..’ (Line: 12) and also input clear button text ‘Clear’ (Line: 14) is hardcoded in the view (English) and not translatable.

### Steps to reproduce
1. Switch language on your back office user to anything other than English. 
2. Click the search icon in the top right corner.

### Expected result
Search + Clear translation in selected language.

### Actual result
Search and Clear is always English.

I’ve prepared a Pull Request fixing this and will submit it in a second.

**Comment by Adolfi** [comment]
**Screenshots:**
![before_clear](https://user-images.githubusercontent.com/6122154/68568343-9bc2ee80-045b-11ea-9439-63a8238b5e96.png)
![before_placeholder](https://user-images.githubusercontent.com/6122154/68568344-9c5b8500-045b-11ea-90f0-dace9873617d.png)

**Comment by kjac** [comment]
Fixed in #7122
