### ISSUE TITLE
Umbraco 8.2+ nuget dependencies not reflected in the 8.2.0+ builds..

### ISSUE THREAD

**Issue by mistyn8** [umbraco/Umbraco-CMS#7125]
Umbraco nuget dependencies not reflected in the 8.2.0+ builds..

**Comment by mistyn8** [comment]
https://www.nuget.org/packages/UmbracoCms.Web/8.2.0

dependencies indicate:
```
examine 1.0.1
clientdependency 1.9.8
clientdependency-mvc5 1.9.3
```

However, 
https://github.com/umbraco/Umbraco-CMS/blob/release-8.2.0/src/Umbraco.Web.UI/Umbraco.Web.UI.csproj
upto the current
https://github.com/umbraco/Umbraco-CMS/blob/release-8.3.0/src/Umbraco.Web.UI/Umbraco.Web.UI.csproj

only refer to
```
examine 1.0.0
clientdependency 1.9.7
clientdependency-mvc5 1.8.0 
```

```
<PackageReference Include="ClientDependency" Version="1.9.7" />
    <PackageReference Include="ClientDependency-Mvc5" Version="1.8.0.0" />
    <PackageReference Include="Examine" Version="1.0.0" />
```

Causing reversion issues and failed updates when minor update performed on umbraco cloud.
Should also be fixed here, so manual install gives the latest dll's?

**Comment by nul800sebastiaan** [comment]
That's annoying, we should definitely fix those references :-)

**Comment by bergmania** [comment]
PR: https://github.com/umbraco/Umbraco-CMS/pull/7131
