### ISSUE TITLE
Dates being blanked out when leaving that date text box if not the default Date format is selected

### ISSUE THREAD

**Issue by crick3t** [umbraco/Umbraco-CMS#7134]
Currently we have the same issue in Umbraco version 8.2.1, as the one on #6102 the second animation. 
Which was apparently fixed here https://github.com/umbraco/Umbraco-CMS/pull/6138

We have set the date picker to show the date in UK format (DD/MM/YYYY). 
After selecting the date if the focus is on the text box, the date is cleared out when it loses the focus.

As a work around, we have set it to the default format YYYY-MM-DD and with that one it is working.

**Comment by nul800sebastiaan** [comment]
Hi @crick3t, there's additional fixes needed in v8 it looks like. There's a PR and and issue reported for this, see: https://github.com/umbraco/Umbraco-CMS/pull/6001

I'll close this one and recommend you follow the progress of this PR.
