### ISSUE TITLE
Sort order by date is not working

### ISSUE THREAD

**Issue by CodeartIT** [umbraco/Umbraco-CMS#7136]
Sort order by "last edited"is not working in member section

I am seeing this issue on Umbraco version: 8.2.1

### Expected result

Members should be sorted by date when is the last time they are edited

### Actual result

Nothing is happening when I click on Last edited

**Comment by nul800sebastiaan** [comment]
Thanks, this will be fixed in 8.4.0: https://github.com/umbraco/Umbraco-CMS/issues/6477
