### ISSUE TITLE
UI error when relation has more than 2000 items

### ISSUE THREAD

**Issue by inetzo** [umbraco/Umbraco-CMS#7151]
When a relation (Document -> Member) has more than 2000 items, the interfaces gives an error:

![afbeelding](https://user-images.githubusercontent.com/18665536/68804328-c7172a80-0661-11ea-829b-9391c8298332.png)

## Umbraco version

I am seeing this issue on Umbraco version: 8.2.1

Reproduction
------------

Create a relation Document -> Member and create more than 2000 items.

**Comment by nul800sebastiaan** [comment]
Hey there @inetzo - sorry for the late reply! This is an unfortunate problem. We're working on some new features right now and have fixed this page in development already. The fix will be part of the upcoming 8.6 release, so that will be a few more weeks of waiting. Thanks for reporting this!
