### ISSUE TITLE
Suddenly can't login to backend - Possibly unhandled rejection: The user object is invalid, the remainingAuthSeconds is required.

### ISSUE THREAD

**Issue by katie366** [umbraco/Umbraco-CMS#7156]
I rebooted my machine, and since I can no longer login to the back end of umbraco which is running locally on my machine. I am using version 8.3.
I am getting an error - 
angular.js?cdv=1353968160:15536 Possibly unhandled rejection: The user object is invalid, the remainingAuthSeconds is required.
I am also getting a 500 error - /umbraco/backoffice/UmbracoApi/Authentication/PostLogin - The requested resource does not support http method 'GET'.

**Comment by nul800sebastiaan** [comment]
Luckily, this is not the experience most people have. It sounds like this might be a problem on your machine somewhere.

Make sure to head on out to the forums where our friendly community can help you find the best solution for your requirements. 
Make sure to head on over to https://our.umbraco.com and ask follow up questions there! 👍
