### ISSUE TITLE
Reorder button for grid properties may hide publish options

### ISSUE THREAD

**Issue by idseefeld** [umbraco/Umbraco-CMS#7159]
Create a grid editor property on a document type. 
Either put enough other properties above the grid property or resize the browser window to low height and you may get the following:

![image](https://user-images.githubusercontent.com/866917/68944303-d2776c80-07ad-11ea-9440-679a951d631c.png)

Looks like the z-index css property of the reorder button is to high:
```
<!-- ngIf: showReorderButton() -->
<div class="...

```
/umbraco/assets/css/umbraco.css?cdv=746635727
```
[umb-sticky-bar] {
    transition: box-shadow .24s;
    position: -webkit-sticky;
    position: sticky;
    z-index: 99;
}
```
I changed z-index: 99 to 1 just in browser and it seems to work.

Yours
Dirk

**Comment by nul800sebastiaan** [comment]
Thanks @idseefeld - this is fixed for the upcoming 7.4.0 release: https://github.com/umbraco/Umbraco-CMS/issues/6299
