### ISSUE TITLE
Distributed cache issues - No sync between the back-office & the front end

### ISSUE THREAD

**Issue by jebastin-jeyaraj** [umbraco/Umbraco-CMS#7161]
We are facing issues with the sync between the back-office & the front-end in distributed environments. The sync id in Kudu in the Azure portal keeps on changing without any external action.

As a temporary solution, we cleared the UmbracoData folder in both the environments & restarted them. Then the sync ids are being the same for some time & again it's getting changed without any reason.

## Umbraco version

I am seeing this issue on Umbraco version: v7.7.8

### Expected result

* Sync ID should be the same in both the back-office & front-end environments (Load balancing)

### Actual result

* Different sync IDs in both the back-office & front-end environments.

**Comment by nul800sebastiaan** [comment]
Hey there @jebastin-jeyaraj, we have greatly improved load balanced setups in later versions of v7 and would recommend you upgrade to the latest version to benefit from those improvements.

Also make sure to follow the documentation on this subject:
https://our.umbraco.com/Documentation/Getting-Started/Setup/Server-Setup/Load-Balancing/flexible-v7
https://our.umbraco.com/Documentation/Getting-Started/Setup/Server-Setup/Load-Balancing/flexible-advanced-v7

For additional question I'd recommend you head over to our forums where our friendly community can help you find the best solution for your requirements. 
Make sure to head on over to https://our.umbraco.com and ask follow up questions there! 👍
