### ISSUE TITLE
.Net Core transition: Inject IUmbracoVersion wherever possible

### ISSUE THREAD

**Issue by bergmania** [umbraco/Umbraco-CMS#7173]
**This task is up for grabs, for contributing to the .Net Core transition project**

On the development branch of the .net core transition project [`netcore/dev`](https://github.com/umbraco/Umbraco-CMS/tree/netcore/dev), we have already abstracted the static `UmbracoVersion`, into an interface (`IUmbracoVersion`) and an instance class (`UmbracoVersion `).

This was required to unblock some other tasks. To finish that task as fast as possible, we just added a new static property on the static helper `Current` (`Current.UmbracoVersion`). This new static property is used all over the system, instead of the original static `UmbracoVersion`.

This task is about eliminating the usage of `Current.UmbracoVersion`, by replacing it with a constructor injection of `IUmbracoVersion`.

Be aware, `Current` exists in both `Umbraco.Core.Composing` and `Umbraco.Web.Composing`.

Expected Procedure:
- Find an instance class that uses `Current.UmbracoVersion`.
- Add `IUmbracoVersion umbracoVersion` to the constructor.
- Save the umbracoVersion in a `private readonly IUmbracoVersion _umbracoVersion;` field.
- Replace the usages of `Current.UmbracoVersion.*` with `_umbracoVersion.*`.
- Make sure the project builds
- Ensure unit tests all pass
- Repeat the process

If any questions, feel free to ask :)

___
Related: [AB#3865](https://umbraco.visualstudio.com/D-Team%20Tracker/_workitems/edit/3865)

**Comment by crgrieve** [comment]
Hello @bergmania,

I am happy to help on this one if it's still up for grabs? If so, I have done one instance of it as an example to make sure I am understanding ok: https://github.com/crgrieve/Umbraco-CMS/commit/015d5882184b0ae43d9745cc42dc54c614941b3e

Is this what you are looking for? If so, I am happy to work through the other instances of Current.UmbracoVersion

Also, on your description, I assume you mean _umbracoVersion.* rather than _ioHelper.*?

Thanks,
Carole

**Comment by bergmania** [comment]
Hi @crgrieve,
Yep, it should have been `_umbracoVersion.*`, good catch. Note to self always triple check when you copy/paste 😄 

Yes, it is still up-for-grabs.
Your example is exactly what to do - Good work 😃 

Feel free to split the task in multiple PRs, if you think that make sense.

**Comment by crgrieve** [comment]
Thanks @bergmania 😊

I have done a PR for the first batch of "easy" ones: 
https://github.com/umbraco/Umbraco-CMS/pull/7190

The remaining ones may need a bit more discussion on approach:

![image](https://user-images.githubusercontent.com/9353655/69221009-28f9f780-0b6e-11ea-9bfd-40da57dc9e08.png)


Thanks,
Carole

**Comment by bergmania** [comment]
Hi @crgrieve..

You almost took all the necessary ones -I updated with a few missing..

Now, all that is back is in `PackageDefinistion` and the membership providers..

I know the one in `PackageDefinistion` is handled in https://github.com/umbraco/Umbraco-CMS/pull/7179

The ones in Membership providers is okay for now because these classes will probably be removed when we need to implement a Member stuff that is compatible with netstandard.

Thanks again!

**Comment by crgrieve** [comment]
Awesome, thanks @bergmania! Happy to help, I will look out for more up for grabs issues :)
