### ISSUE TITLE
V8: Preview badge should have backoffice editor page link

### ISSUE THREAD

**Issue by ReVoid** [umbraco/Umbraco-CMS#7177]
After brand new look of preview badge was created in #6585 , I think there is an feature that might extend the preview badge functionality.

Sometimes, user opens page in preview mode, but without umbraco left sidebar. In that case, user don't have a possibility to open the page fast in backoffice or make sidebar appear, he forced to login in backoffice and search the page.

**Feature:**

1. Add "Go to backoffice" button right before "close" button (just a link, nothing special)
2. Click on "Preview mode" title returns user to preview mode with sidebar (we already have an explicit close button, right?). Just a link, nothing special too.

![image](https://user-images.githubusercontent.com/12345710/69141198-462eb780-0ad5-11ea-9c03-5f9c5d104f5e.png)

**Comment by nul800sebastiaan** [comment]
I am not so sure we want to add new features into this badge.. by this logic, I could also say: 

"The preview badge should have the option to resize to different viewport sizes. Just a link, nothing special too." 😊

We'll talk about it with some colleagues at HQ though and will let you know what we think! 👍

**Comment by ReVoid** [comment]
@nul800sebastiaan 
Sorry, I didn't mean that is a piece of cake 🤭
I meant that is a link in a special format like `https://unicorns.com/umbraco#/content/content/edit/6666` without any service call. But I assume, it will require prior service calls to find an ID of current page and insert it into the badge.

> We'll talk about it with some colleagues at HQ though and will let you know what we think!
👍 👍 👍

**Comment by emma-hq** [comment]
Hey @ReVoid,

We've had a discussion at HQ around the preview mode UI and decided not to run with this suggestion for the time being. The preview mode has been given a bit of love since this issue was raised so please take a look and of course, we're always open to more suggestions. Thank you for submitting the issue, I'll close this one for now. 

Emma
