### ISSUE TITLE
Unable to edit the user that already created, even If having Admin role

### ISSUE THREAD

**Issue by SankuPradeep** [umbraco/Umbraco-CMS#7180]
A brief description of the issue goes here.

## Umbraco version

I am seeing this issue on Umbraco version: 7.5.3

Reproduction
------------

If you're filing a bug, please describe how to reproduce it. Include as much
relevant information as possible, such as:

**Comment by nul800sebastiaan** [comment]
Thanks @SankuPradeep, you're reporting an issue on a pretty old version of Umbraco. If you can reproduce this on the a clean install of the latest v7 version (7.15.3) then let us know with some good steps to reproduce the issue so it can be looked at.
