### ISSUE TITLE
Mandate.ParameterNotNullOrEmpty in v8

### ISSUE THREAD

**Issue by zharonar** [umbraco/Umbraco-CMS#7204]
Does alternative exist for this method ```Mandate.ParameterNotNullOrEmpty```, or should I implement my own?

**Comment by Shazwazza** [comment]
just use the standard .net exception handling:

```cs
if (string.IsNullOrWhiteSpace(blah))
                throw new ArgumentException($"{nameof(blah)} cannot be null or empty", nameof(blah));
```

Visual Studio generates these for you, just use `ctrl + .` or `ctrl + space` on the parameter and choose to generate null checks.
