### ISSUE TITLE
Filter in User Management not keeping state

### ISSUE THREAD

**Issue by rpjengaard** [umbraco/Umbraco-CMS#7209]
Under the section User Management, the Status filter is not keeping its state when going back to list.

## Umbraco version

I am seeing this issue on Umbraco version: 7.15.2

Reproduction
------------

### Bug summary

![filter-bug-7152](https://user-images.githubusercontent.com/3634592/69420378-da3f8f80-0d1e-11ea-81ba-2c5801130b4a.gif)

When i first do the filtering, the "GetPagedUsers" endpoint is called like this: `/umbraco/backoffice/UmbracoApi/Users/GetPagedUsers?pageNumber=1&pageSize=25&orderBy=Name&orderDirection=Ascending&filter=&userStates=Active`

When i come back from to the list from a user, the call look lige this: `/umbraco/backoffice/UmbracoApi/Users/GetPagedUsers?pageNumber=1&pageSize=25&orderBy=Name&orderDirection=Ascending&filter=`

So this means that `&userStates=Active` is missing in the 2nd call.

**Comment by kjac** [comment]
Fixed in #7216
