### ISSUE TITLE
Nested Content configuration wording

### ISSUE THREAD

**Issue by nielslyngsoe** [umbraco/Umbraco-CMS#7218]
We should stop saying Document Types and start using Element Type, and thereby it shouldn't be needed to say only Element Types. Also, the word 'Blueprint' could be misleading, I think it's better without it.

Feel welcome to provide a new formulation for this Description.

![image](https://user-images.githubusercontent.com/6791648/69527350-62ff3b00-0f6c-11ea-9657-29eace7a750a.png)

**Comment by kjac** [comment]
Couldn't agree more. I've been wanting to change this since V8 alpha, but I felt like the term "Element type" had to settle a bit first.

I'll throw in a suggestion shortly.

**Comment by kjac** [comment]
PR in #7224
