### ISSUE TITLE
Inherit granular permissions for child nodes

### ISSUE THREAD

**Issue by bkclerke** [umbraco/Umbraco-CMS#7230]
_I'll start off by saying I'm not 100% sure if this is a 'bug' or a 'feature request' but I'll try to explain to see where this goes--_

**The setup:**
I have a permissions group in Umbraco 8 that has NO default permissions set. The content and media sections are allowed. The start node for for content and media is set to the root item in the tree (to allow everything to be viewed). 

The granular permissions for this group are setup on ONE child page (which also has multiple child pages) to allow a couple items including create, sort, publish, move, delete and copy. 

**What I think should happen:**
With this setup, I would expect to login as a user in the permissions group explained above and see all the content in the content tree. I have no permissions for any of these nodes except for the one page where I had granular permissions assigned.

**What I need to happen:**
What I need to happen is for the granular permissions that I set, to be inherited by the child pages of that node as well. I believe this was an option in the past with umbraco granular permissions. Can we have this feature implemented again? I do not see how this something that can be done in Umbraco 8.

This gives me the blanket ability to have granular permissions setup on the child pages to match the one parent area and any new child pages that are created will also inherit these permissions. 

This also insures that while the user can see the entire website, they only have permissions on their own granular level. They have no default permissions set for the rest of the website.

**What currently happens:**
When logged in as a user in this group, the user can see the content tree structure and edit the one node they have permissions for, even create a new child node, but none of the child pages they have the same editable permissions. The permissions are not able to be inherited to the child pages, and when the user creates a new child page, the current usability requires an admin with user permissions to go in and add all the child pages individually to the granular permissions in order to allow them the ability to edit the child nodes. This makes the process a bit cumbersome and time consuming for content editors to manage their individual areas.

It appears that currently the publish button functionality does reflect publish on the child pages so this area (bottom right publish button) may already reflect the inherited ability. It appears that the action menu (that is available on right click of a content item) does not reflect the inherited permissions for child pages. _This makes me wonder if there is a bug in inherited permissions somewhere or if I am not understanding the granular permission functionality here._

**The reasoning / end goal:**
The client has multiple users in various groups logging into the website to manage different areas that they have permissions for. 

They will also need the ability to select content from other parts of the website that they will not have permissions to manage. They want the users in groups to be able to see the entire website content structure, but not be able to manage it. They only have permissions for their granular permission areas.

**Comment by Shazwazza** [comment]
I'm unsure if this is the same issue (sorry i haven't had time to read both of these in detail or test) https://github.com/umbraco/Umbraco-CMS/issues/7210

But granular permissions certainly inherit. 

We'll need to review both of these reports.

**Comment by bkclerke** [comment]
Hey @Shazwazza ! It sounds like #7210 is the same issue, the child nodes are not reflecting the granular level permissions in the content tree. This may be an issue then and not necessarily a feature request if I am understanding how the granular permissions work correctly.

**Comment by nul800sebastiaan** [comment]
I've just given this a test and it's definitely a regression that appeared in 8.2, your expected behavior should've worked. I'll close this in favor of #7210 so make sure to monitor progress there.
