### ISSUE TITLE
8.4RC: Property Actions in infinite editor needs TLC

### ISSUE THREAD

**Issue by skttl** [umbraco/Umbraco-CMS#7236]
When editing content in an infinite editor, the Property Actions menu doesn't look very good.

Any suggestions on how to present it a bit prettier?

![billede](https://user-images.githubusercontent.com/3726467/69756400-c51d9300-115a-11ea-812d-0632d05c2cf0.png)

---
_This item has been added to our backlog [AB#4002](https://umbraco.visualstudio.com/243e7927-03b2-44e2-908f-d4ac7ea5daaa/_workitems/edit/4002)_

**Comment by nielslyngsoe** [comment]
Hi @skttl 

Good catch, how did you get to this state, can you share how to replicate it?

From a visual standpoint, the Property Action Menu-Toggle is supposed to appear on the right side of the Label, with a little spacing in between...

**Comment by skttl** [comment]
This is from DTGE, I'll see if I can make a test opening a page in IE from a content picker.

**Comment by nielslyngsoe** [comment]
I will install DTGE and do a test on my own. 🤞

**Comment by nielslyngsoe** [comment]
PR https://github.com/umbraco/Umbraco-CMS/pull/7243

**Comment by skttl** [comment]
Sweet. thanks 👍

**Comment by warrenbuckley** [comment]
Fixed in this PR #7266
