### ISSUE TITLE
cannot return the check box value until save && publish all nodes 

### ISSUE THREAD

**Issue by MosabAbuzaid** [umbraco/Umbraco-CMS#7244]
Hi 

when i working on cms creating nodes and add then a check box to the document type later 
i cant get the value of check box until i save & publish the node so i have to save & publish all nodes 
and i have a lot of them so sorry but i have to write this issue as a bug here to fix it 
best regard

**Comment by emmaburstow** [comment]
Hi @MosabAbuzaid 

I'm sorry to tell you that this isn't a bug - it's the way Umbraco is designed to work. It would be incredibly expensive if we updated datatype values in real-time; it would badly effect performance. 

Thanks for reporting anyhow,

Emma, [Pull Request team](https://our.umbraco.com/get-involved/the-core-collaborators/)

**Comment by emmaburstow** [comment]
Just a thought @MosabAbuzaid - if you want to ask the community how they might get around this problem, pop over to our very friendly forum at Our.Umbraco.com/forum/ and someone might be able to tell you how they did it.

All the best!

Em
