### ISSUE TITLE
8.4RC - missing doctype alias, no way view to edit it after creation

### ISSUE THREAD

**Issue by TwoMoreThings** [umbraco/Umbraco-CMS#7247]
In a fresh install of 8.4RC the doctype alias is missing

This is in the latest Chrome on Windows 10 Pro

The padlock shows (and you can click on it), but the alias does not show, so there's no way to edit it. See attached screenshot.

![image](https://user-images.githubusercontent.com/13945979/69815508-5c7ff600-11ee-11ea-8585-b21fceb620ec.png)

---
_This item has been added to our backlog [AB#4000](https://umbraco.visualstudio.com/243e7927-03b2-44e2-908f-d4ac7ea5daaa/_workitems/edit/4000)_

**Comment by nul800sebastiaan** [comment]
I can reproduce this, it populates the alias when first creating the document type but after it's been saved, the alias disappears. Thanks @TwoMoreThings - we'll have a look at it!

**Comment by nielslyngsoe** [comment]
New PR: https://github.com/umbraco/Umbraco-CMS/pull/7267
