### ISSUE TITLE
Duplication of Issue U4-10822 in Umbraco 8.3

### ISSUE THREAD

**Issue by csharpforevermore** [umbraco/Umbraco-CMS#7255]
There is a problem with Umbraco 8.3.0. I am using a uSkinned template and the Master template calls a Partial View which starts 

@inherits UmbracoViewPage<USN.Models.USNBaseViewModel>

When I load a page though, I get the following ModelBindingException as follows

Cannot bind source content type Umbraco.Web.PublishedModels.USNHomepage to model type USN.Models.USNBaseViewModel.

Nothing seems to fix it.

**Comment by kjac** [comment]
Sounds like you're passing the wrong model type to the view. Perhaps some inheritance has been broken.

I suggest you take this to the forum at https://our.umbraco.com/ or have a chat with uskinned about it 🙂

**Comment by nul800sebastiaan** [comment]
Hey @csharpforevermore - indeed, this sounds more like a problem where you need some help getting is fixed. 

Make sure to head to the forums at https://our.umbraco.com where our friendly community can help you find the best solution for your requirements.
