### ISSUE TITLE
Richtext editor macro incurs sql hit in umbraco 8

### ISSUE THREAD

**Issue by shearer3000** [umbraco/Umbraco-CMS#7256]
In umbraco 8, a page rendering a Rich Text editor a macro will perform a sql query like so:
```
exec sp_executesql N'SELECT *
FROM [cmsMacro]
LEFT JOIN [cmsMacroProperty]
ON [cmsMacro].[id] = [cmsMacroProperty].[macro]
WHERE (([cmsMacro].[macroAlias] = @0))',N'@0 nvarchar(4000)',@0=N'MyMacroName'
```

Umbraco 7 didn’t perform this query. Is there any way to avoid this sql query in umbraco 8?

Thanks

**Comment by stevemegson** [comment]
This should be fixed in 8.4.0. The result of the SQL query will be cached, so you should see it only once per macro.

**Comment by nul800sebastiaan** [comment]
Thanks @stevemegson - as a reference, this is fixed in this PR: https://github.com/umbraco/Umbraco-CMS/pull/6782

**Comment by shearer3000** [comment]
thanks guys :)
