### ISSUE TITLE
8.4RC - issue with styling of Richtext configuration

### ISSUE THREAD

**Issue by bjarnef** [umbraco/Umbraco-CMS#7258]
I noticed in 8.4-RC the layout of the configuration in Richtext Editor is a bit broken.

![image](https://user-images.githubusercontent.com/2919859/69945914-d82dbb80-14ea-11ea-96ac-63170ae5aec2.png)

## Umbraco version

I am seeing this issue on Umbraco version: 8.4-RC and latest changes in branch `dev/v8`

Reproduction
------------

### Specifics

* Umbraco 8.4-RC
* Google Chrome Version 78.0.3904.108

### Steps to reproduce

Go to data types under settings and select a data types based on TinyMCE, e.g. Richtext Editor or create a new based on this property editor.

### Expected result

The configuration should be aligned vertically as previous.

### Actual result

The toolbar configuration is pushed to the right. It seems that recently a "control-header" has been added.

![image](https://user-images.githubusercontent.com/2919859/69946163-673ad380-14eb-11ea-9c1d-6678db64790a.png)

Looks like an issue when "hide label" is true where the label inside "control-label" is hidden, but the wrapping "control-label" keep the with on 160px.

---
_This item has been added to our backlog [AB#4033](https://umbraco.visualstudio.com/243e7927-03b2-44e2-908f-d4ac7ea5daaa/_workitems/edit/4033)_

**Comment by bjarnef** [comment]
It seems the issue was introduced here.
https://github.com/umbraco/Umbraco-CMS/commit/548bb48f38b5f965d925be2cbc5000f1882c1965#diff-5d264656544cc4d5610b60a0c84dc428R9-R27

@nielslyngsoe I think at least the `ng-hide="property.hideLabel"` should stay on the wrapping "control-label" to not break layout, where "hide label" is set to true in core or in custom property editors.

**Comment by nielslyngsoe** [comment]
@bjarnef yep, that should definitely be corrected.

I do see the error already back in 8.0.2, the HideLabel was never set to True. But I have made this PR to fix it: https://github.com/umbraco/Umbraco-CMS/pull/7264

**Comment by bjarnef** [comment]
@nielslyngsoe okay, not sure if it was an issue previous, but apparently it was aligned in the latest minor versions of v8.
