### ISSUE TITLE
umbClipboardDirective doesn't support 'text' function

### ISSUE THREAD

**Issue by mattbrailsford** [umbraco/Umbraco-CMS#7261]
In umbClipboardDirective, which uses ClipboardJS it assumes the text for the umb-clipboard-text is a known constant string however it should allow binding a function such that the text can be dynamically created.

From what I can tell, ClipboardJS should allow a function to be passed as a param to the text option, but because of how the umbClipboardDirective is built, it will only ever treat the umb-clipboard-text as a constant string and so won't evaluate it.

**Comment by nul800sebastiaan** [comment]
Thanks @mattbrailsford. I didn't quite get what you meant (okay, I admit, I didn't get any of it) but the analogy @nielslyngsoe gave was insightful: 

> Imagine you copy an image, lets say image.jpg, Then you open the image in photoshop and make it Black & white and save it (same file). Without redoing the copy-action, you would be pasting the black & white image. That's how files work in the OS.

This makes sense to me, in a single-user system. But I would imagine it easily gets completely confusing when I copy something, paste it 3 minutes later and another editor in the system has replaced my beautifully crafted text and butchered it into an unreadable mess. 

So the question is: do you have a scenario in which this would make total sense (preferably in the context of something that's not a plugin for Umbraco)? I just have a hard time imagining where we would use this type of feature.

**Comment by mattbrailsford** [comment]
@nul800sebastiaan I must admit, I resolved my issue but I think the issue still holds value.

The biggest thing is if you have a value that you want copying but it's dynamically generated. Right now, all the copy options require the value to exist at time of render (to a degree, as you can render into an element that could be reactive).

I could only give you an example that would fit in my scenario. In my case, I wanted to copy some address details but the address it dynamically constructed. I currently have it copying from a HTML element, but there is potential that I would want to copy the address in a different way to what is rendered, say to ease with pasting into a CSV or the likes. In this case, I'd need a way to provide the address dynamically, right now my only option would be to render that into a hidden HTML element.

**Comment by nul800sebastiaan** [comment]
Thanks Matt! Currently I don't think we'll have a need for this in Umbraco yet. So for now, we'd not want to build a feature that will then need support and maintenance. Of course if we can come up with great scenario's to do this in CMS itself we're more than happy to have another look at this. 

For now, I'll close this one but leave it open for feedback since we like the idea, but don't see a use case for it (yet).
