### ISSUE TITLE
Unable to retrieve values from Multinode Tree Picker (MNTP2) from IMember

### ISSUE THREAD

**Issue by jattwood** [umbraco/Umbraco-CMS#7262]
In Umbraco 7.15.3, I have a MNTP2 storing a list of related members on a member profile. I call the property "memberReferrals".

I am trying to query the value, update it and save it using through the memberservice:

```
Guid referringMemberGuid = new Guid(model.ReferringMemberGuid);
var referringMember = memberService.GetByProviderKey(referringMemberGuid);
var myValues = referringMember.GetValue<IEnumerable<IPublishedContent>>("memberReferrals");
```

In the case above, myValues returns empty, even though there is an entry in the profile and the property returns not null.

I can do this by using the Umbraco helpers and the values return as expected...but not when using the memberservice.

```
    Guid referringMemberGuid = new Guid(model.ReferringMemberGuid);
    var referringMemberHelper= Members.GetByProviderKey(referringMemberGuid);

    if (referringMemberHelper.HasValue("memberReferrals"))
    {
        var pastReferrals = referringMemberHelper.GetPropertyValue<IEnumerable<IPublishedContent>>("memberReferrals");
    }
```
Any ideas why you cant get MNTP values returned from MemberService? Seems a little excessive to have to use both the IMember service plus the IPublished content just to query and update a value. I would expect to be able to do both through memberservice.

Thanks!

**Comment by nul800sebastiaan** [comment]
Hi @jattwood - probably a bad idea to use the services in your frontend code, they are not made for performance and will make your site slow, especially when used a lot. 

The notable exception here is the relationservice, which sounds like it is exactly what you need: relate an umbraco entity to other umbraco entities (member entities).

This blog post is a bit old but the concept and the code is still the same: https://umbraco.com/blog/getting-to-know-umbraco-relations/

Docs for the relationservice: https://our.umbraco.com/Documentation/Reference/Management/Services/RelationService/index-v7

As for your actual problem: you can't map stuff from the MemberService directly to an IPublishedContent, you will get "raw" database values from the MemberService, and will need to update them like that as well. 
So `referringMember.GetValue("memberReferrals")` will probably give you a string, not sure how you're storing these values but most likely a comma-separated string of identifiers. You will need to set the value to that string of id's as well when saving. Referrals sounds dangerous as a referral might happen a lot so really look into the much more performant RelationService instead.

Make sure to head on over to https://our.umbraco.com and ask follow up questions so our friendly community can help you find the best solution for your requirements! 👍

**Comment by jattwood** [comment]
Thanks @nul800sebastiaan for the detailed response. Relationships would be idea, but I need admin access to edit these on a member by member basis. In my case, I need to create this referral during member registration/creation, so I need to use member service in order to add the referral to the list of current referrals stored in a members profile. These relationships are limited to a total of 5 and only queried during the registration process. Also, they need to be editable from the back office so hence the use of the MNTP.

Cheers,

Jamie
