### ISSUE TITLE
Problem migrating from 7.15.3 to 8.3.0

### ISSUE THREAD

**Issue by PezCo** [umbraco/Umbraco-CMS#7268]
Hi i have got a site im trying to migrate to v8. the site is fairly large and makes heavy use of Archetype and a few other plugins that dont have a v8 counterpart.

But im not even able to get the migration to complete without errors.

the last working "info" that seems related to actually updating was

`{"@t":"2019-12-03T10:32:26.4012947Z","@mt":"SQL [2630]: UPDATE [umbracoDataType] SET\n [umbracoDataType].[propertyEditorAlias]=@0\n \nWHERE (([umbracoDataType].[propertyEditorAlias] = @1))\r\n -- @0:Umbraco.ColorPicker @1:Umbraco.ColorPickerAlias\r\n","SourceContext":"Umbraco.Core.Migrations.Expressions.Execute.Expressions.ExecuteSqlStatementExpression","ProcessId":5220,"ProcessName":"iisexpress","ThreadId":16,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"DESKTOP-5GL5A2R","Log4NetLevel":"INFO ","HttpRequestNumber":6,"HttpRequestId":"afeacddc-b11d-4257-9a9a-9da2df1de7c0"}`

The first error i get in the log is as follows

`{"@t":"2019-12-03T10:32:31.3143700Z","@mt":"Database configuration failed","@l":"Error","@x":"System.ArgumentNullException: Value cannot be null.\r\nParameter name: key\r\n   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)\r\n   at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)\r\n   at Umbraco.Core.Migrations.Upgrade.V_8_0_0.DataTypeMigration.Migrate() in D:\\a\\1\\s\\src\\Umbraco.Core\\Migrations\\Upgrade\\V_8_0_0\\DataTypeMigration.cs:line 79\r\n   at Umbraco.Core.Migrations.MigrationBase.Umbraco.Core.Migrations.IMigration.Migrate() in D:\\a\\1\\s\\src\\Umbraco.Core\\Migrations\\MigrationBase.cs:line 73\r\n   at Umbraco.Core.Migrations.MigrationPlan.Execute(IScope scope, String fromState, IMigrationBuilder migrationBuilder, ILogger logger) in D:\\a\\1\\s\\src\\Umbraco.Core\\Migrations\\MigrationPlan.cs:line 309\r\n   at Umbraco.Core.Migrations.Upgrade.Upgrader.Execute(IScopeProvider scopeProvider, IMigrationBuilder migrationBuilder, IKeyValueService keyValueService, ILogger logger) in D:\\a\\1\\s\\src\\Umbraco.Core\\Migrations\\Upgrade\\Upgrader.cs:line 67\r\n   at Umbraco.Core.Migrations.Install.DatabaseBuilder.UpgradeSchemaAndData(MigrationPlan plan) in D:\\a\\1\\s\\src\\Umbraco.Core\\Migrations\\Install\\DatabaseBuilder.cs:line 498","SourceContext":"Umbraco.Core.Migrations.Install.DatabaseBuilder","ProcessId":5220,"ProcessName":"iisexpress","ThreadId":16,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"DESKTOP-5GL5A2R","Log4NetLevel":"ERROR","HttpRequestNumber":6,"HttpRequestId":"afeacddc-b11d-4257-9a9a-9da2df1de7c0"}`

this happens imediately after a bunch of warns related to non supported datatypes e.g

`{"@t":"2019-12-03T10:32:27.8233113Z","@mt":"Skipping validation of configuration for data type {NodeId} : {NewEditorAlias} (was: {EditorAlias}) because no property editor with that alias was found. Please ensure that the configuration is valid. The site may fail to start and / or load data types and run.","@l":"Warning","NodeId":1622,"NewEditorAlias":"Imulus.Archetype","EditorAlias":"Imulus.Archetype","SourceContext":"Umbraco.Core.Migrations.Upgrade.V_8_0_0.DataTypeMigration","ProcessId":5220,"ProcessName":"iisexpress","ThreadId":16,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"DESKTOP-5GL5A2R","Log4NetLevel":"WARN ","HttpRequestNumber":6,"HttpRequestId":"afeacddc-b11d-4257-9a9a-9da2df1de7c0"}
{"@t":"2019-12-03T10:32:27.8513121Z","@mt":"Skipping validation of configuration for data type {NodeId} : {NewEditorAlias} (was: {EditorAlias}) because no property editor with that alias was found. Please ensure that the configuration is valid. The site may fail to start and / or load data types and run.","@l":"Warning","NodeId":1628,"NewEditorAlias":"Imulus.Archetype","EditorAlias":"Imulus.Archetype","SourceContext":"Umbraco.Core.Migrations.Upgrade.V_8_0_0.DataTypeMigration","ProcessId":5220,"ProcessName":"iisexpress","ThreadId":16,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"DESKTOP-5GL5A2R","Log4NetLevel":"WARN ","HttpRequestNumber":6,"HttpRequestId":"afeacddc-b11d-4257-9a9a-9da2df1de7c0"}`

then get another error with the following content 
`{"@t":"2019-12-03T10:32:31.3183541Z","@mt":"The database schema validation produced the following summary: {DbSchemaSummary}","DbSchemaSummary":"The following tables were found in the database, but are not in the current schema:\r\ncmsTaskType,icUrlTracker,Redirects,UFRecordDataBit ...(etc)... The following unknown constraints (Primary Keys, Foreign Keys and Indexes) were found in the database, but are not in the current schema:\r\nId\r\n \r\n","SourceContext":"Umbraco.Core.Migrations.Install.DatabaseBuilder","ProcessId":5220,"ProcessName":"iisexpress","ThreadId":16,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"DESKTOP-5GL5A2R","Log4NetLevel":"INFO ","HttpRequestNumber":6,"HttpRequestId":"afeacddc-b11d-4257-9a9a-9da2df1de7c0"}`

Ive looked at every table i could think of and am unsure what "paramater name: Key" is so struggling to find what im supposed to fix

**Comment by nul800sebastiaan** [comment]
I believe this problem will be fixed in 8.4.0, see more info here: https://github.com/umbraco/Umbraco-CMS/issues/6588

I'll close this for now, we're releasing 8.4.0 soon, but there is a release candidate out now if you would like to do some testing: https://our.umbraco.com/download/releases/840

**Comment by PezCo** [comment]
RC 8.4 got it through thanks.
Now for the hard part.

**Comment by AnandAsir** [comment]
{"@t":"2020-05-13T18:19:34.6664008Z","@mt":"An error occurred during installation step {Step}","@l":"Error","@x":"System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> Umbraco.Web.Install.InstallException: The database failed to upgrade. ERROR: The database configuration failed with the following message: Invalid property identifier character: {. Path '', line 1, position 1.\n Please check log file for additional information (can be found in '/App_Data/Logs/')\r\n   at Umbraco.Web.Install.InstallSteps.DatabaseUpgradeStep.ExecuteAsync(Object model) in d:\\a\\1\\s\\src\\Umbraco.Web\\Install\\InstallSteps\\DatabaseUpgradeStep.cs:line 47\r\n   --- End of inner exception stack trace ---\r\n   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)\r\n   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)\r\n   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)\r\n   at Umbraco.Web.Install.Controllers.InstallApiController.<ExecuteStepAsync>d__14.MoveNext() in d:\\a\\1\\s\\src\\Umbraco.Web\\Install\\Controllers\\InstallApiController.cs:line 236\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)\r\n   at Umbraco.Web.Install.Controllers.InstallApiController.<PostPerformInstall>d__11.MoveNext() in d:\\a\\1\\s\\src\\Umbraco.Web\\Install\\Controllers\\InstallApiController.cs:line 104","Step":"DatabaseUpgrade","SourceContext":"Umbraco.Web.Install.Controllers.InstallApiController","ProcessId":12508,"ProcessName":"iisexpress","ThreadId":9,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"xxx-xx-19-201-x","Log4NetLevel":"ERROR","HttpRequestNumber":7,"HttpRequestId":"23657524-40de-48d8-a26d-e5c2524d8928"}

Trying to upgrate from 7.15.2 to 8.6.1 Did anyone faced this issue please help me
