### ISSUE TITLE
Sensitive data cannot be set on member type properties

### ISSUE THREAD

**Issue by Shazwazza** [umbraco/Umbraco-CMS#7270]
I'm unsure when this bug was introduced but I know this bug exists in 8.2.2+ and possibly earlier versions. 

The issue is that you cannot turn on 'sensitive data' options for member type properties. The issue seems to be an angular problem since when you toggle this on for a property and click submit, then re-open that property type's settings, the flag will be cleared.

---
_This item has been added to our backlog [AB#4067](https://umbraco.visualstudio.com/243e7927-03b2-44e2-908f-d4ac7ea5daaa/_workitems/edit/4067)_

**Comment by nul800sebastiaan** [comment]
Note: seems to have broken in 8.1, I can repro on 8.1.5 but not it works in 8.0.2.

**Comment by liamlaverty** [comment]
I've made a PR which I think addresses this issue. The umbgroupsbuilder.directive.js file was only mapping isSensitiveValue, but isSensitiveData was being read in the Save method.

After making this change I can update the isSensitive property. Then when I signed in as a member who didn't have sensitive data privileges, the field said "this value is hidden... etc"

**Comment by kjac** [comment]
Fixed in #7273
