### ISSUE TITLE
No image source in output through RTE

### ISSUE THREAD

**Issue by PvanGeffen** [umbraco/Umbraco-CMS#7275]
**The problem:**
If i put an image into the Rich Text Editor (Grid) and view it on the front-end, no image appears because the path is completely missing.

**Detailed:**
I put an image into the RTE (I know there are other options, but we need this right now) and it looks like this:
![img_problem_cms-01](https://user-images.githubusercontent.com/57631848/70149543-9d718200-16a8-11ea-98d4-99fc195aaf16.png)

And the code of it looks like this:
![img_problem_cms-02](https://user-images.githubusercontent.com/57631848/70149567-af532500-16a8-11ea-909d-c1351569bc88.png)

But if want to check it on the front-end it shows no image, because of a missing path, as the image below shows:
![img_problem_output-01](https://user-images.githubusercontent.com/57631848/70149638-d3166b00-16a8-11ea-85dd-7e06fa843903.png)

## Umbraco version

I am seeing this issue on Umbraco version: **8.3.0**

Reproduction
------------

### Specifics

    * URL is not available due a site in progress
    * Umbraco version 8.3.0
    * Google Chrome version 78.0.3904.108
    * No other browsers checked

### Steps to reproduce

    * Mentioned above.

### Expected result

    * I would like to see an image.

### Actual result

    * No image is shown
    * The path is missing
    * Just the extra variables are there

**Comment by nul800sebastiaan** [comment]
Thanks for the detailed report! 

This problem will be fixed in 8.4.0 - https://github.com/umbraco/Umbraco-CMS/issues/6763 and there's workarounds mentioned in that issue too.
