### ISSUE TITLE
Umbraco is using alias of Image Cropper to define Image URL

### ISSUE THREAD

**Issue by bielu** [umbraco/Umbraco-CMS#7279]
Umbraco is using alias of editor in URL Provider
![image (4)](https://user-images.githubusercontent.com/2244074/70233991-935a8c80-1757-11ea-8c6c-4ac5173a8ec4.png)
This generates an issue when someone is trying to build custom ImageCropper which is using same ImageCropperValueConverter as Umbraco will return empty URL.

**Comment by rasmusjp** [comment]
Hi @bielu 

There are multiple places in the source code that assume it's only ImageCropper and Upload that stores files and have url's. 

There's an open PR in https://github.com/umbraco/Umbraco-CMS/pull/7075 that changes how this works

For now you can create your own `IMediaUrlProvider` that resolves the url for your property editor and add it to the media url provider collection `composition.MediaUrlProviders().Insert<MyMediaUrlProvider>();`.

**Comment by emmaburstow** [comment]
Hey all,

Thanks for responding, Rasmus :) I'll close this issue as there's a community PR that addresses it. 

Emma

**Comment by nul800sebastiaan** [comment]
Let's keep it open, the PR will resolve this issue, at which point it can be closed! 👍

**Comment by emmaburstow** [comment]
Thanks Seb - my mistake 🙈

**Comment by rasmusjp** [comment]
@nul800sebastiaan #7075 has been merged so I think this can be closed now?

**Comment by nul800sebastiaan** [comment]
Thanks @rasmusjp! 👍
