### ISSUE TITLE
V8 - Setting nested node access on User creates 'ghost nodes'

### ISSUE THREAD

**Issue by CimplexAB** [umbraco/Umbraco-CMS#7280]
If you create a User, give him a user group, editor for example and set the content start node on the user (or on the group) to a node that is below the root node - ghost nodes will appear. The ghost nodes is a exact copy of the nodes the user have access to but look unpublished.

## Umbraco version

I am seeing this issue on Umbraco version: 8.1.3 - 8.2.2 

Reproduction
------------

1. Create a user
2. Assign a user group
3. Set start node to a node that is below the root, like level 2
4. Login to the user and ghost nodes will appear

**Comment by kjac** [comment]
@CimplexAB this is by design; however the current implementation has a few bugs. See #6815 😄
