### ISSUE TITLE
Refactor class names for layout in info tab

### ISSUE THREAD

**Issue by bjarnef** [umbraco/Umbraco-CMS#7295]
I have noticed a few places in the backoffice UI where class names like `umb-package-details`, `umb-package-details__main-content`, `umb-package-details__sidebar`.

Originally this was added in the new packager, but has now been used several places in backoffice like in info tab for media, member group and data type.

![image](https://user-images.githubusercontent.com/2919859/70395514-ce7ee900-19ff-11ea-9e83-aa75848a90d3.png)

![image](https://user-images.githubusercontent.com/2919859/70395532-f706e300-19ff-11ea-89ca-323bc04e40b4.png)

![image](https://user-images.githubusercontent.com/2919859/70395550-1e5db000-1a00-11ea-90d0-be8f869b0cb9.png)

it was also used in log viewer, but changed in this PR https://github.com/umbraco/Umbraco-CMS/pull/4970

I'll suggest to add a general class name that can be re-used, since the current ones with `package` is confusing when searching through the codebase.

**Comment by bjarnef** [comment]
@nielslyngsoe do you have a suggetion for a better and more generic class name to use?

**Comment by nielslyngsoe** [comment]
@bjarnef I agree, its a mess.

I do think it would be good to rename, I though do not know how widely this is used by packages, so we cant remove existing classes. But we can create new ones with a better name.

I do not have a good name up my sleeve, but I would go for something describing what it does from a visual standpoint.

Without having investigated whether it's compatible I would try to go for modifier classes of umb-box? Since I would see this as modifications/additions to the umb-box, setting width and aligning it...

Example:
<div class="umb-box --medium --left" ...

Or:

<div class="umb-box --small --right" ...


As said I haven't investigated, so it might still need to be a wrapper for umb-box as today. Meaning that we would have to come up with a new name, which is hard cause there are already so many names.. but something like umb-layout-... could work for me?

**Comment by bjarnef** [comment]
@nielslyngsoe yes there could be packages using these classes now, so we probably need to keep these for now. These could maybe extend the new css classes or just comma seperated where these selectors are specified.

I think it would be great to have the wrapping div with e.g. a class `umb-layout-` and inside these the `umb-box` just fill the "column" width.

Maybe something like this? It could be based on 12 columns or something else, but with the following it would be each the reverse it so left "column" (sidebar) fill 4 and right "column" (main content) fill 8.

`umb-layout-wrapper`
-- `umb-layout-content`
---- `umb-layout-content__col8`
---- `umb-layout-content__col4`

**Comment by nielslyngsoe** [comment]
@bjarnef naming looks good, but I think its best if we keep the current styling and just provide better names.

Re-inventing or enabling further options on how we layout would be very cool, but I think its better if that's another PR?

Today the layout has a main part and a sidebar, and the sidebar has a fixed size so turning this into columns would also change the layout, as well having a specific styling for this layout enables us to do the responsiveness tailored to this specific layout.

Instead, I think we should ensure that our choice of names opens up for several layouts to exists. Meaning we should be specific towards this begin one layout type and thereby enable other layouts to exists.

So I would suggest naming this specific layout with a postfix like: "main-plus-sidebar" and provide two child-classes? Something like:

```
<div class="umb-layout-wrapper-main-plus-sidebar"
	<div class="umb-layout-content--main">
		<umb-box ...
	<div class="umb-layout-content--sidebar"
		<umb-box ...
```

In LESS it could look something like this, to ensure that 'umb-layout-content--...' is only used as descendants of this layout:

.umb-layout-wrapper-main-plus-sidebar {

	...

    > .umb-layout-content--main {
		...
    }
	> .umb-layout-content--sidebar {
		...
    }
}

Let me know how you feel about that? 😊

**Comment by bjarnef** [comment]
@nielslyngsoe we can keep the `main` and `sidebar` syntax for now, but not sure how flexible it is compared to "columns". E.g. we might want to have a view in half/half, so two columns with equal width, but we can of course that later.

Regarding the layout I think this would be better.

```
.umb-layout-wrapper .-with-sidebar {

	...

    > .umb-layout-content--main {
		...
    }
	> .umb-layout-content--sidebar {
		...
    }
}
```

Then we can add general styles to `umb-layout-wrapper` and also specific styles with `-with-sidebar` class is added. I think we already does something like this on other components.

Some examples on this:
https://github.com/umbraco/Umbraco-CMS/blob/2948d506eacfc30ba83757b81fa82a831e7a9773/src/Umbraco.Web.UI.Client/src/less/components/editor/subheader/umb-editor-sub-header.less#L13-L17

https://github.com/umbraco/Umbraco-CMS/blob/2948d506eacfc30ba83757b81fa82a831e7a9773/src/Umbraco.Web.UI.Client/src/less/components/editor/subheader/umb-editor-sub-header.less#L37-L39

**Comment by nielslyngsoe** [comment]
@bjarnef looks good to me. 🤩 I think its the right approach.

**Comment by nathanwoulfe** [comment]
I'd lean into something more generic, using a single wrapper element and modifiers to set child widths (almost like a simple CSS grid system ala Bootstrap/Tailwind etc). Less markup is better, assuming it can achieve the end goal.

Flexbox makes this relatively straightforward.

ping @nielslyngsoe @bjarnef

**Comment by nul800sebastiaan** [comment]
Looks like this was fixed in https://github.com/umbraco/Umbraco-CMS/pull/9657 ? I'll close for now, if any other issues are still there, feel free to send a fresh PR! 😁

**Comment by bjarnef** [comment]
@nul800sebastiaan actually the https://github.com/umbraco/Umbraco-CMS/pull/9657 just added a sidebar column to relation type with some general details.

This feature request was more about renaming or add a new class name instead of `umb-package-details` classes. It started with packages section, but is added to more areas. Should probably have been named something related to `layout` instead of the specific to the content.

**Comment by nul800sebastiaan** [comment]
@bjarnef any PRs you would like to work on will be welcome for this!
