### ISSUE TITLE
Scheduling a node makes it published but not in the cache - Umbraco 8.3.0

### ISSUE THREAD

**Issue by MosabAbuzaid** [umbraco/Umbraco-CMS#7296]
I tried using the schedule feature to publish a node in a specific time it got published but it went outside the cache. 

## Umbraco 8.3.0

I am seeing this issue on Umbraco version: 8.3

### Steps to reproduce

1.  Create a new node and go to schedule button to set a publish time for it.

![scheduale](https://user-images.githubusercontent.com/38281155/70420871-505b2a80-1a71-11ea-9bad-7f8ad445b0b2.png)

2. After creating the node wait for time to pass.

![Untitled](https://user-images.githubusercontent.com/38281155/70421107-d24b5380-1a71-11ea-9a66-f518d93d6e31.png)

3.  After the time get passed go to check the node you will face this statement: 
(This document is published but is not in the cache).

![final](https://user-images.githubusercontent.com/38281155/70421783-36224c00-1a73-11ea-8ed4-bfd3f7197366.png)

### Expected result
Getting the node published and in the cache

when you using the schedule and set a time for node to publish it at you have to see it published when the time is pass 

### Actual result
Node was not in the cache

**Comment by nul800sebastiaan** [comment]
I'm afraid we can not reproduce this problem on a clean Umbraco 8.3 install. Maybe it's some custom code that you have that is causing this? 

This sounds like an excellent question for the forums where our friendly community can help you find the best solution for your requirements. 
Make sure to head on over to https://our.umbraco.com and ask follow up questions there! 👍
