### ISSUE TITLE
Incorrect message in the links zone when a culture is published but not routed

### ISSUE THREAD

**Issue by davidardoin** [umbraco/Umbraco-CMS#7299]
On a culture variant page that has no domain, when a culture is published, the message in the links zone of the other culture (which was already published) says that it is not published. It should state that the culture is published but not routed.

I am seeing this issue on Umbraco version: 8.2.1

Reproduction
------------

1- 2 cultures : one of them (english) not the default and not mandatory, and the other one (french) default and mandatory.

2- One page at root that is culture variant and doesn't have any domain set up (not yet). The french culture is published and the english one is still not created. Therefore, there is a link for french and none for english.
![image](https://user-images.githubusercontent.com/51491633/70443024-5f3be000-1a65-11ea-998f-c568cab7d310.png)
![image](https://user-images.githubusercontent.com/51491633/70443075-7bd81800-1a65-11ea-9e96-16d6e651bf41.png)

3- Publish the english culture. It takes over the link of the french culture, and the french version of the page is still published but no more accessible. 
![image](https://user-images.githubusercontent.com/51491633/70443155-a924c600-1a65-11ea-9947-acd30d170de6.png)
![image](https://user-images.githubusercontent.com/51491633/70443206-bfcb1d00-1a65-11ea-9aaa-d9a57c45ab27.png)

- I expected the message to be the same as when publishing the english culture using a different name.
![image](https://user-images.githubusercontent.com/51491633/70443552-5992ca00-1a66-11ea-81f0-458f55159efe.png)

- Publish again the french culture. The message still says that it is not published. I have to unpublish the english culture to get the link back in the french culture.

**Comment by poornimanayar** [comment]
Glad that this has got logged. I can reproduce this in v8.3.

**Comment by nul800sebastiaan** [comment]
Wow, old issue, sorry for the long delay on this one! 
I think this is entirely expected, the root node should have some domain / route attached to it to be able to make a URL. The other problems I could no longer reproduce, so I think everything is working as expected now.
