### ISSUE TITLE
V8: Using enter in text inputs opens the template for editing and saves content

### ISSUE THREAD

**Issue by kjac** [umbraco/Umbraco-CMS#7304]
If you hit enter in any text input when editing content (including the content name), the content template opens up in infinite editing and the content is saved:

![content-save-template-on-enter](https://user-images.githubusercontent.com/7405322/70527331-f54a3600-1b4b-11ea-93b1-520b1de03159.gif)

The changes added in PR #7257 fixes this issue, so this issue is mostly for future reference and to ensure that we test #7257 accordingly.

**Comment by garpunkal** [comment]
I'm seeing the same issue: Umbraco version 8.4.0.

**Comment by nul800sebastiaan** [comment]
Fixed in https://github.com/umbraco/Umbraco-CMS/pull/7257
