### ISSUE TITLE
Nested content with max set to one shows add button

### ISSUE THREAD

**Issue by FransdeJong** [umbraco/Umbraco-CMS#7323]
When using Nested content as a dataset (min 1, max 1) it shows the add content button in 8.4.
This button should be hidden when min is 1 and max is 1.

![Screenshot Capture - 2019-12-12 - 08-27-17](https://user-images.githubusercontent.com/29602162/70691374-39a71480-1cb9-11ea-89a4-fba0590fba10.png)

**Comment by DanDiplo** [comment]
I can confirm this - had it happen to me, too.

**Comment by kjac** [comment]
Happens on vLatest as well... NC was subject to a bit of refactoring for 8.4, guess this is a side effect. 

I'll fix it right up.

**Comment by kjac** [comment]
PR in #7327

**Comment by FransdeJong** [comment]
Great work and so fast aswelll. Do you even have a job?

**Comment by kjac** [comment]
@FransdeJong I do, I do - contrary to popular belief 😛

**Comment by laura-san-martin** [comment]
![image](https://user-images.githubusercontent.com/14986428/77343771-01c85800-6d11-11ea-9ffe-95b8bf24bf5a.png)
![image](https://user-images.githubusercontent.com/14986428/77343844-1b699f80-6d11-11ea-8b22-5ece278e7d90.png)

Happening in 8.5.5 again :/

**Comment by FransdeJong** [comment]
Yep, the workaround isn't working anymore.

**Comment by nul800sebastiaan** [comment]
This issue is labeled as fixed in `release/8.6.0`, which is due out next week.
