### ISSUE TITLE
V8: Clean up language selectors in the treepicker

### ISSUE THREAD

**Issue by kjac** [umbraco/Umbraco-CMS#7326]
In the early days of V8 we could switch between languages in the treepicker when selecting content e.g. from MNTP. This just wasn't terribly useful nor user friendly, so it was changed into always displaying the content nodes in the language currently being edited (`cculture`/`mculture`).

However... the code for the treepicker language selector still lingers, and has most recently caused the issue described in #7313.

I would really like to remove the whole thing from the treepicker. It isn't used anywhere in the core anymore, it won't get regression tested and is bound to stop working at some point (as a matter of fact I don't even know if it works now).

But... removing it is a breaking change on the clientside, as 3rd party packages *could* be using the feature.

Paging @nul800sebastiaan and @nielslyngsoe for some thoughts on this.

**Comment by nul800sebastiaan** [comment]
Thanks @kjac - we had a chat about this and I learned that we're looking into re-introducing the language picker at some point (you might have very good reasons to link to a Spanish page from the English site). So we'll leave the code for now for when we are ready to start using it again! 👍
