### ISSUE TITLE
Multinode Treepicker (MNTP) allow items of type not persisted on save

### ISSUE THREAD

**Issue by DanDiplo** [umbraco/Umbraco-CMS#7328]
When creating a multinode treepicker (MNTP) datatype in 8.4 you are able to select one or more document types via the "Allow items of type" selector. This works. However, if you set a "start node" by picking a node then as soon as you save the datatype the allowed items disappear and are not saved.

## Umbraco version

I am seeing this issue on Umbraco version: 8.4

Reproduction
------------

### Bug summary

The MNTP "Allow items of type" picker doesn't persist selected items upon saving when a start-node is present.

### Specifics

Think this is an 8.4 regression. I have language variants enabled (if that is relevant).

### Steps to reproduce

* Create an MNTP
* Select a start node via the "choose" picker dialogue
* Use the "Allow items of type" selector to select any document type
* Save

As mentioned, language variants are enabled on the site, if that has any bearing. So the start node can be varied by culture.

### Expected result

The items of type selected are persisted.

### Actual result

The items are not persisted.

**Comment by kjac** [comment]
Goodness... it looks like the values are actually persisted but not shown on subsequent page reloads. I'll investigate!

**Comment by kjac** [comment]
PR in #7344

**Comment by nul800sebastiaan** [comment]
Fixed in https://github.com/umbraco/Umbraco-CMS/pull/7344
