### ISSUE TITLE
[v8] Bug. A page with a single field starts to work slower when the site is enlarged

### ISSUE THREAD

**Issue by bv-it** [umbraco/Umbraco-CMS#7329]
Hello

EN: A page with a single field starts to work slower when the site is enlarged
RU: Страница с одним полем начинает работать медленнее при увеличении сайта

Examples (Umbraco 8.2.2 + SQL Server 2019):
**1. The site contains 10 pages (10-50 ms)**
![1](https://user-images.githubusercontent.com/16698614/70744503-de196d00-1d32-11ea-9510-197366c6df56.jpg)

**2. The site contains 50-100 pages (150-250 ms)** 
![2](https://user-images.githubusercontent.com/16698614/70744517-e40f4e00-1d32-11ea-9d2b-f4d99efa8550.jpg)

**3. The site contains 500-1000 pages (350-700 ms)** 
**4. etc.** 

EN: The site is very fast at first, but slows down with the growth of pages. (he functionality of the page does not change, but slows down over time)
RU: Сайт сначала очень быстрый, но замедляется с ростом страниц. (Функционал страницы не меняется, но со временем замедляется)

**Comment by nul800sebastiaan** [comment]
Hi there @bv-it, it will be hard to pinpoint this, luckily, most people don't seem to have this problem so I am going to have to assume something in your specific implementation is not quite right.

This sounds like an excellent question for the forums where our friendly community can help you find the best solution for your requirements. 
Make sure to head on over to https://our.umbraco.com and ask follow up questions there! 👍

**Comment by bv-it** [comment]
https://our.umbraco.com/forum/using-umbraco-and-getting-started//100405-v8-bug-a-page-with-a-single-field-starts-to-work-slower-when-the-site-is-enlarged

**Comment by nul800sebastiaan** [comment]
@bv-it I would recommend you add more detail about what is in your template, maybe some querying going on that is inefficient? Any code to get navigation that's not using the cache, etc. You did not provide a lot of information to work with right now.

Also have a look at the documentation about things you should not do: https://our.umbraco.com/documentation/Reference/Common-Pitfalls/

**Comment by bv-it** [comment]
Ok, thanks.
