### ISSUE TITLE
Need ability to schedule removing time of nodes in MNTP in V8

### ISSUE THREAD

**Issue by saifobeidat** [umbraco/Umbraco-CMS#7334]
It would be amazing if we can schedule a removing time of nodes in the MNTP, which means I can choose a time to make a node removed from the MNTP

![image](https://user-images.githubusercontent.com/24841143/70860483-edfba180-1f2a-11ea-8f42-ced3932f9a11.png)

**Comment by kjac** [comment]
@saifobeidat I would argue this isn't a responsibility for MNTP?

But you can achieve the same using Nested Content or perhaps scheduled unpublishing of the picked nodes (depending on your scenario).

**Comment by saifobeidat** [comment]
@kjac  I think it's just an extra capability to have more control on the picked nodes. since the schedule feature on the node level won't work in my scenario work because I want to keep that node published always even it's not in the MNTP. 

Anyway, can you tell me how to achieve this in Nested Content?

**Comment by kjac** [comment]
@saifobeidat you could create a Nested Content configuration with a content picker and a date/time picker, something along the lines of this?

![image](https://user-images.githubusercontent.com/7405322/70867134-2a9ebb80-1f72-11ea-8321-c2ada39ceb88.png)

**Comment by nul800sebastiaan** [comment]
Hi @saifobeidat - this is not a feature we'll be adding at this point. I would encourage you to have a look at @kjac's suggestion and if you need more inspiration to head on over to the forum to ask other people how they would do this. 
For specialized needs like this, it is also possible to implement a custom property editor but that would be a bit more work.
