### ISSUE TITLE
Action Menu and Node Action Menu should be option to show only in one of them

### ISSUE THREAD

**Issue by bielu** [umbraco/Umbraco-CMS#7337]
Actually I am seeing a few cases where this two menu should be separate:
![image](https://user-images.githubusercontent.com/2244074/70894167-6a9e8680-1fe4-11ea-8dc7-e23d7e5f1b79.png)
For example if any action is called on actually display node (i.e Show Raw Value[Which I would implement]).
I am really often hitten issue when switching not compatible editors on the node but I want still stay with same alias, Umbraco will not clear value of picker. Why I would implement a feature to show Raw Value of editors.  And I was thinking to add that only to right menu, but actually, when I attached custom Action it will appear in both menus. Even if in my opinion it doesn't make any sense to be displayed on tree open from Node on Tree. As my action is just reloading of view on the actual node.

**Comment by nul800sebastiaan** [comment]
Unfortunately this is not and option right now, we are thinking of how the Actions menus can work better in general and will consider your feature request.

For now, your best option will be to create a Content App for what you need.

**Comment by bielu** [comment]
@nul800sebastiaan Actually I don't think a content app is fitting my needs, as I want to change values in editors without resave them and reload to Raw View option, and opposite direction. 
In case of a content app I am not seeing a way to not resave everything on every toggle, or maybe I am wrong :)?

**Comment by nul800sebastiaan** [comment]
Anything can be built the way you need it. I didn't say it was going to be easy! 😅 

For now, unfortunately we're not ready to change up the actions menus.
