### ISSUE TITLE
Html.AngularValueTinyMceAssets() - Upgrading from 8.1.5 to 8.4 gets me an error

### ISSUE THREAD

**Issue by gormmo** [umbraco/Umbraco-CMS#7352]
Hi. 
I just updated from 8.1.5 to 8.4 and receives this error -

CS1061: 'HtmlHelper<BackOfficeModel>' does not contain a definition for 'AngularValueTinyMceAssets' 

I updated through package manager. I have bumped the cdf version and also downloaded the zipped package and overwritten the Umbraco folder with the zipped content. Still no luck. 

Anyone recognizes the error and can help?

H5YR :-) 

Best regards,
Gorm.

**Comment by nul800sebastiaan** [comment]
Hi there @gormmo, this sounds like an excellent question for the forums where our friendly community can help you find the best solution for your requirements. 
Make sure to head on over to https://our.umbraco.com and ask follow up questions there! 👍
