### ISSUE TITLE
Issue on getting ApplicationContext 

### ISSUE THREAD

**Issue by manojsukumarvajra** [umbraco/Umbraco-CMS#7353]
After Upgrading to umbraco v8 from v7 , ApplicationContext runs out to be an error, it is mentioned like in documentation as 

"Also if you need an ApplicationContext you should
        ///        //pass this in via a ctor instead of using the ApplicationContext.Current singleton."
kindly explain me this process

**Comment by nul800sebastiaan** [comment]
Hi there @manojsukumarvajra, this sounds like an excellent question for the forums where our friendly community can help you find the best solution for your requirements. 
Make sure to head on over to https://our.umbraco.com and ask follow up questions there! 👍
