### ISSUE TITLE
Use umb-checkbox in installer

### ISSUE THREAD

**Issue by bjarnef** [umbraco/Umbraco-CMS#7354]
At the moment most part of backoffice UI use `umb-checkbox` instead of traditional `<input type="checkbox" />`

However the installer still use a traditional checkbox a few places. It would be great if this could re-use `umb-checkbox` component instead and we don't need to create a copy of this (and need to maintain it two places). The `umb-checkbox` does use `localizationService` so it need to have this available as well, but this one is registered on `umbraco.services` module, so it might be tricky to include this in installer without adding too much new dependencies.

**Comment by bjarnef** [comment]
@nielslyngsoe do you have some thought on how to re-use the `umb-checkbox` here?

**Comment by nul800sebastiaan** [comment]
I don't think we can start adding too much to the installer, especially `localizationService` can't be used since we don't yet have a logged in user.

The installer is not something that regular "editor" type users will see and it's okay if it's not super polished, as long as the install/upgrade procedure is clear enough. I'll close this for now. Thanks for the suggestion though!

**Comment by bjarnef** [comment]
@nul800sebastiaan we could add some basic styles without using the `umb-checkbox` component to make it a bit consistent. 
https://www.w3schools.com/howto/howto_css_custom_checkbox.asp

Not sure if is possible in the angular component/directive only to use `localizationService` if available - in the case we don't need the service just a static text.

**Comment by nul800sebastiaan** [comment]
I don't think it's a great idea to create a style that might change everywhere else and then is inconsistent again at some point. If we can re-use the styles that we already have for umb-checkbox then that's great, otherwise I wouldn't think it's worth the trouble.

**Comment by bjarnef** [comment]
We can re-use the styling from here:
https://github.com/umbraco/Umbraco-CMS/blob/v8/dev/src/Umbraco.Web.UI.Client/src/less/components/umb-form-check.less

but part of the markup is dynamic (which also might change).
https://github.com/umbraco/Umbraco-CMS/blob/v8/dev/src/Umbraco.Web.UI.Client/src/views/components/forms/umb-checkbox.html

It would be ideal to re-use the component, but we can't since `localizationService` is used here (and not available in installer).

https://github.com/umbraco/Umbraco-CMS/blob/v8/dev/src/Umbraco.Web.UI.Client/src/common/directives/components/forms/umbcheckbox.directive.js#L41
