### ISSUE TITLE
Ability to select custom media type when bulk uploading images.

### ISSUE THREAD

**Issue by Luksor** [umbraco/Umbraco-CMS#7355]
Hi :)

I've created a custom media type that uses a modified image cropper. Unfortunately there is no way of bulk uploading images with that new media type. All images are by default uploaded as an "Image" media type.

**Comment by nul800sebastiaan** [comment]
Hmm, when I try this I get asked what I'm uploading:

![image](https://user-images.githubusercontent.com/304656/71086889-3d480900-219b-11ea-9ade-6f4275a0e71f.png)


Could be something wrong in your setup. This sounds like an excellent question for the forums where our friendly community can help you find the best solution for your requirements. 
Make sure to head on over to https://our.umbraco.com and ask follow up questions there! 👍
