### ISSUE TITLE
NullReferenceException: Nested Content

### ISSUE THREAD

**Issue by addisonlynch** [umbraco/Umbraco-CMS#7364]
A ``NullReferenceException`` is thrown following a ``HasValue`` null check using nested content. The nested content is correctly set and accessed as ``IPublishedElement``.

See below. Thanks!

![error](https://user-images.githubusercontent.com/21162161/71117466-2a860200-21a4-11ea-9e91-73e00a34bb41.jpg)

## Umbraco version

I am seeing this issue on Umbraco version: 8.0.1

### Bug summary

If the nested content is null, shouldn't ``HasValue`` return false?

### Specifics

``_sourceValue`` is not ``null``: 

```
"[{\"key\":\"450a7ae1-66e0-4193-9d28-b21c53532626\",\"name\":\"Item 1\",\"ncContentTypeAlias\":\"issueCollector\",\"cTAColor\":\"[\\\"Blue\\\"]\",\"cTAText\":\"Request Support\",\"issueCollectorID\":\"c157ef16\"}]" | object {string}
```

### Steps to reproduce

Attempt to access nested content when not null.

### Expected result

Access nested content

### Actual result

``NullReferenceException``

**Comment by nul800sebastiaan** [comment]
Hi @addisonlynch, I think there might be some confusion here as to how to query NestedContent. 

I would recommend you post this as a question on the forums where our friendly community can help you find the best solution for your requirements. 
Make sure to head on over to https://our.umbraco.com and ask follow up questions there! 👍

**Comment by DegerSolutions** [comment]
Hi @nul800sebastiaan, 
I have the same issue in Umbraco v8.18.1 today:

https://our.umbraco.com/forum/using-umbraco-and-getting-started//108740-nullreferenceexception-with-nestedcontent-no-value-but-existing-sourcevalue

Best, Sören
