### ISSUE TITLE
.NET Core transition: Introduce configuration of IUserPasswordConfiguration and IMemberPasswordConfiguration

### ISSUE THREAD

**Issue by bergmania** [umbraco/Umbraco-CMS#7367]
**This task is up for grabs, for contributing to the .NET Core transition project**

On the development branch of the .net core transition project [`netcore/dev`](https://github.com/umbraco/Umbraco-CMS/tree/netcore/dev), we introduced new interfaces for password configuration, These interfaces is left with just a default hard coded implementation `DefaultPasswordConfig`.

This task is about introducing configuration values from a config file. Such that these values can be changed without a recompile of the binaries.

It is important that the actual implementation is located in the `Umbraco.Configuration` project

If any questions, feel free to ask :)

**Comment by JimBobSquarePants** [comment]
https://docs.microsoft.com/en-us/dotnet/api/microsoft.extensions.configuration.iconfiguration?view=dotnet-plat-ext-3.1

You're literally reinventing the wheel.

**Comment by Shazwazza** [comment]
Yep we're fully aware how configuration is supposed to be handled in .net core. We aren't there yet, this is still all transition phase of splitting up projects, making as much net standard as possible before getting the runtimes working with net core. During the transition, the net framework web app needs to continue to work as expected. 
Eventually there will be a new implementation of the configuration project and config interfaces using the desired techniques.
