### ISSUE TITLE
.NET Core transition: Clean up obsoletes

### ISSUE THREAD

**Issue by bergmania** [umbraco/Umbraco-CMS#7368]
**This task is up for grabs, for contributing to the .NET Core transition project**

On the development branch of the .net core transition project [`netcore/dev`](https://github.com/umbraco/Umbraco-CMS/tree/netcore/dev), we have a lot of classes, methods and properties that are marked with the `ObsoleteAttribute`

Some of these are very easy to remove because there are no internal usages. Others are still in use internal, and will need some more refactor, to be able to remove.

If any questions, feel free to ask :)

Feel free to resolve this task in multiple smaller PRs, Due to the fact that long running feature branch most likely have end up having merge conflict with [`netcore/dev`](https://github.com/umbraco/Umbraco-CMS/tree/netcore/dev)

**Comment by hishamco** [comment]
If not one will pick this one, I will add it to my list :)

**Comment by benjaminc** [comment]
I'll start working on this.

**Comment by benjaminc** [comment]
I was able to get most of the obsolete items removed cleanly, however there was one I had questions about.  The Umbraco.Core.Constants.ObjectTypes.Strings.Stylesheet constant in Umbraco.Abstractions is marked as obsolete with the note "This no longer exists in the database".  It is used only one place, in the UmbracoObjectTypeAttribute on the Umbraco.Core.Models.UmbracoObjectTypes.Stylesheet enum value.  That enum value is used for UDI type lookups, audit entries, and relation object types.  Can all of these be deleted, or should I take a different approach here?

**Comment by bergmania** [comment]
@Shazwazza, do you know the history of this `Umbraco.Core.Constants.ObjectTypes.Strings.Stylesheet`

**Comment by Shazwazza** [comment]
These can be deleted, Stylesheet data (believe it or not) used to be stored in the database 😱 many many moons ago, i'm amazed that we still have references to that, please remove :)

**Comment by benjaminc** [comment]
I've submitted pull request #7491 to remove them.
