### ISSUE TITLE
.NET Core transition: Inject config interfaces wherever possible

### ISSUE THREAD

**Issue by bergmania** [umbraco/Umbraco-CMS#7370]
**This task is up for grabs, for contributing to the .NET Core transition project**

On the development branch of the .net core transition project [`netcore/dev`](https://github.com/umbraco/Umbraco-CMS/tree/netcore/dev), we have used `Current.Configs` a lot.

When this is used, we cannot move the class into Umbraco.Abstractions or Umbraco.Infrastructure.

This task is about eliminating the usage of `Current.Configs.*` in general and specially `Current.Configs.Global()` and `Current.Configs.Settings()`, by replacing it with a constructor injection of `IGlobalSettings` and `IUmbracoSettingsSection` respectively.

Expected Procedure:
- Find an instance class that uses `Current.Configs.*`.
- Add `IGlobalSettings globalSettings` or `IUmbracoSettingsSection umbracoSettingsSection` to the constructor.
- Save the variable in a private readonly field.
- Replace the usages of `Current.Configs.*` with the field.
- Make sure the project builds
  - Often you will need to inject this into classes that uses this specific class
- Ensure unit tests all pass
- Repeat the process

If any questions, feel free to ask :)

Feel free to resolve this task in multiple smaller PRs, Due to the fact long running feature branch most likely have merge conflict with [`netcore/dev`](https://github.com/umbraco/Umbraco-CMS/tree/netcore/dev)

**Comment by crgrieve** [comment]
Hello, I will pick this one up :)

**Comment by benjaminc** [comment]
I'll take a stab at this

**Comment by benjaminc** [comment]
I've gotten the ones that matched your above criteria out.  There are still 52 uses, listed below.  They mainly consist of attributes, extensions, and Umbraco.Web fundamental classes that couldn't be moved out anyway (`UmbracoDefaultOwinStartup`, `UmbracoModule`, and `UmbracoWebService`).  I could refactor most any of these to use `Current.Factory`, but that doesn't really get rid of the dependency.  Let me know if you want me to look at any of these further.  I'll be submitting a pull request for what I have shortly.

```
Umbraco.Web.UI
	Umbraco
		Views
			Default.cshtml:42
			Default.cshtml:113
			Preview
				Index.cshtml:22
Umbraco.Web
	Editors
		UpdateCheckController.cs:76
		UpdateCheckController.cs:78
	HtmlHelperRenderExtensions.cs:64
	HtmlHelperRenderExtensions.cs:65
	Install
		FilePermissionHelper.cs:15
		FilePermissionHelper.cs:16
		FilePermissionHelper.cs:39
		InstallAuthorizeAttribute.cs:69
	Models
		ContentEditing
			UserInvite.cs:36
	Models
		Trees
			TreeNode.cs:115
	Mvc
		StatusCodeFilterAttribute.cs:25
		UmbracoAuthorizeAttribute.cs:60
		UmbracoRequireHttpsAttribute.cs:19
		UmbracoRequireHttpsAttribute.cs:32
	PublishedContentExtensions.cs:67
	PublishedContentExtensions.cs:70
	Security
		AppBuilderExtensions.cs:242
		AppBuilderExtensions.cs:243
		AppBuilderExtensions.cs:349
		AppBuilderExtensions.cs:397
		AuthenticationExtensions.cs:147
		AuthenticationExtensions.cs:217
		AuthenticationExtensions.cs:229
		ExternalSignInAutoLinkOptions.cs:28
	UmbracoDefaultOwinStartup.cs:29
	UmbracoDefaultOwinStartup.cs:30
	UmbracoDefaultOwinStartup.cs:31
	UmbracoModule.cs:78
	UmbracoWebService.cs:35
	WebApi
		Filters
			CheckIfUserTicketDataIsStaleAttribute.cs:82
			SetAngularAntiForgeryTokensAttribute.cs:46
			SetAngularAntiForgeryTokensAttribute.cs:53
			UmbracoWebApiRequireHttpsAttribute.cs:27
Umbraco.Tests
	Routing
		ContentFinderByUrlTests.cs:39
		ContentFinderByUrlTests.cs:74
		GetContentUrlsTests.cs:73
		GetContentUrlsTests.cs:105
		UrlProviderTests.cs:47
		UrlProviderTests.cs:110
		UrlProviderTests.cs:138
		UrlProviderTests.cs:158
		UrlProviderTests.cs:204
		UrlProviderTests.cs:258
		UrlProviderTests.cs:308
		UrlProviderTests.cs:327
	TestHelpers
		TestObjects.cs:125
		TestObjects.cs:252
Umbraco.Abstractions
	Configuration
		Configs.cs:12
```

**Comment by bergmania** [comment]
I close the issue for now.. 

As you say the remaining usages is a bit more complex to get rid of.
