### ISSUE TITLE
.NET Core transition: Inject IShortStringHelper wherever possible

### ISSUE THREAD

**Issue by bergmania** [umbraco/Umbraco-CMS#7371]
**This task is up for grabs, for contributing to the .NET Core transition project**

On the development branch of the .net core transition project [`netcore/dev`](https://github.com/umbraco/Umbraco-CMS/tree/netcore/dev), we have used `Current.ShortStringHelper` a lot.

When this is used, we cannot move the class into Umbraco.Abstractions or Umbraco.Infrastructure.

This task is about eliminating the usage of `Current.ShortStringHelper`, by replacing it with a constructor injection of `IShortStringHelper`.

Expected Procedure:
- Find an instance class that uses `Current.ShortStringHelper`.
- Add `IShortStringHelper shortStringHelper` to the constructor.
- Save the shortStringHelper in a `private readonly IShortStringHelper _shortStringHelper;` field.
- Replace the usages of `Current.ShortStringHelper.*` with `_shortStringHelper.*`.
- Make sure the project builds
- Ensure unit tests all pass
- Repeat the process

If any questions, feel free to ask :)

Feel free to resolve this task in multiple smaller PRs, Due to the fact long running feature branch most likely have merge conflict with [`netcore/dev`](https://github.com/umbraco/Umbraco-CMS/tree/netcore/dev)

**Comment by AndyButland** [comment]
Got a bit of spare time, so am starting to have a look at this (noting just in case anyone else is planning the same).
