### ISSUE TITLE
Add default id to checkboxes and radiobuttons

### ISSUE THREAD

**Issue by bjarnef** [umbraco/Umbraco-CMS#7374]
At the moment checkboxes and radiobuttons rendered the `id` attribute with an empty value if not a value `input-id` value is set, where e.g. Chrome warn about this:

![image](https://user-images.githubusercontent.com/2919859/71247459-216a7180-2319-11ea-9f5a-7c03046d0987.png)

https://github.com/umbraco/Umbraco-CMS/blob/bfe359bd1e22856f4560e41056033157e7357c78/src/Umbraco.Web.UI.Client/src/views/components/forms/umb-checkbox.html#L3

Could we add a default value for `id` if `input-id` is empty?
In tags editor it seems we does domething like this:

https://github.com/umbraco/Umbraco-CMS/blob/990d14e7919b9e802c804f1b6eea1417dc6a39a2/src/Umbraco.Web.UI.Client/src/common/directives/components/tags/umbtagseditor.directive.js#L53

**Comment by bjarnef** [comment]
@nielslyngsoe any thoughts on this? Maybe with a Umbraco prefix and also in tags editor, e.g. `umb_check_{guid}`, `umb_radio_{guid}`, `umb_tag_{guid}`?

**Comment by nielslyngsoe** [comment]
@bjarnef I think it makes sense to create a new GUID if input-id is empty.
We do not need to prefix the GUID, collisions shouldn't be possible (The clever .Net guys say so...)

**Comment by bjarnef** [comment]
It would just make it more clear that it is an internal generated GUID. Furthermore the tags editor has prefix "t", it would be great to have something consistent here. It not already we have another compoent named something with "t", we might have this in future, so "tag" might be better (or "umb_tag" as prefix), but it is a breaking change.

**Comment by bjarnef** [comment]
@nielslyngsoe I have submitted a PR https://github.com/umbraco/Umbraco-CMS/pull/7375

**Comment by kjac** [comment]
Fixed by #7375
