### ISSUE TITLE
MemberService giving null reference

### ISSUE THREAD

**Issue by sulmbrant** [umbraco/Umbraco-CMS#7394]
After upgrading from 8.1.3 to 8.4.0 the MemberService start throwing null reference exception no matter what methods I'm trying to use. Checked the breaking changes but can't find anything related to this and it doesn't matter if I use it through Umbraco.Core.Composing or with dependency injection. Is it a bug?

**Comment by sulmbrant** [comment]
Looks like it only happens i UmbracoApiControllers

**Comment by abjerner** [comment]
Hi @sulmbrant,

Thanks for taking the time to report this. I did some quick testing in a fresh 8.4 installation, but so far I haven't been able to reproduce the issue you're describing.

Could you perhaps share some of the code that triggers the null reference exception as well as the stack trace of the exception? Both could be helpful in determining the cause. Of course remember to blank out any sensitive information should either the code or stack trace contain that 😉

**Comment by sulmbrant** [comment]
Investigated this even more and it looks like the problem exists when a method is called in an ajax request.

`public class ApiDataController : UmbracoApiController
    {
        private readonly IMemberService _memberService;

        public ApiDataController(IMemberService memberService)
        {
            _memberService = memberService;
        }

public HttpResponseMessage PostInsertData(ApiData data)
        {
               var member = _memberService.GetById(2074) //gives null reference
var member2 = _memberService.GetByEmail(data.Email) //gives null reference
}
}
`

**Comment by sulmbrant** [comment]
`{Message: "An error has occurred.",…}
Message: "An error has occurred."
ExceptionMessage: "Objektreferensen har inte angetts till en instans av ett objekt."
ExceptionType: "System.NullReferenceException"
StackTrace: "   vid Umbraco.Core.Persistence.SqlSyntax.SqlServerSyntaxProvider.ReadLock(IDatabase db, Int32[] lockIds) i D:\a\1\s\src\Umbraco.Core\Persistence\SqlSyntax\SqlServerSyntaxProvider.cs:rad 275
↵   vid Umbraco.Core.Services.Implement.MemberService.GetById(Int32 id) i D:\a\1\s\src\Umbraco.Core\Services\Implement\MemberService.cs:rad 354
↵   vid BeautifulBody.Core.API.BookingExternalDataController.PostInsertEvent(BookingItem data) i C:\Users\Simon\Music\Projects\BeautifulBody.Web\BeautifulBody.Core\API\BookingExternalData.cs:rad 1693
↵   vid lambda_method(Closure , Object , Object[] )
↵   vid System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.<>c__DisplayClass6_2.<GetExecutor>b__2(Object instance, Object[] methodParameters)
↵   vid System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ExecuteAsync(HttpControllerContext controllerContext, IDictionary`2 arguments, CancellationToken cancellationToken)
↵--- Slut på stackspårningen från föregående plats där ett undantag utlöstes ---
↵   vid System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
↵   vid System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
↵   vid System.Web.Http.Controllers.ApiControllerActionInvoker.<InvokeActionAsyncCore>d__1.MoveNext()
↵--- Slut på stackspårningen från föregående plats där ett undantag utlöstes ---
↵   vid System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
↵   vid System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
↵   vid System.Web.Http.Controllers.ActionFilterResult.<ExecuteAsync>d__5.MoveNext()
↵--- Slut på stackspårningen från föregående plats där ett undantag utlöstes ---
↵   vid System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
↵   vid System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
↵   vid System.Web.Http.Filters.AuthorizationFilterAttribute.<ExecuteAuthorizationFilterAsyncCore>d__3.MoveNext()
↵--- Slut på stackspårningen från föregående plats där ett undantag utlöstes ---
↵   vid System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
↵   vid System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
↵   vid System.Web.Http.Dispatcher.HttpControllerDispatcher.<SendAsync>d__15.MoveNext()"`

**Comment by abjerner** [comment]
@sulmbrant thanks for the code and stack trace. Your code works fine in my installation - both with dependency injection and when calling `Current.Services.MemberService`. Are you able to reproduce the issue in a fresh 8.4 installation?

I haven't tested the code in an installation upgraded from 8.1.3. I'll see if I can get around to doing that later today.

According to the stack trace, the exception seems to happen at the database level. What kind of database are you using in your installation?

**Comment by sulmbrant** [comment]
I'm using a MSSQL database

**Comment by sulmbrant** [comment]
Pretty weird, after hours and hours trying to fix this I think I found something. When other methods are called before the MemberService it looks like the context is lost making the MemberService return null reference. It's a guess so I'm not really sure but the service works if it is the first thing I do in the called method when the call if made in javascript with ajax

**Comment by abjerner** [comment]
@sulmbrant I haven't been able to reproduce the issue in an upgraded solution either.

If the order of which the methods are called seem to mean something, could you perhaps share a bit more of your code?

**Comment by nul800sebastiaan** [comment]
Hi there @sulmbrant  - this sounds like an excellent question for the forums where our friendly community can help you find the best solution for your requirements. 
Make sure to head on over to https://our.umbraco.com and ask follow up questions there! 👍
