### ISSUE TITLE
(Special) characters in macro textarea

### ISSUE THREAD

**Issue by PvanGeffen** [umbraco/Umbraco-CMS#7417]
If i put some basic (special) characters like a single quote ('), double qoute (") or an ampersand (&) it doesn't get rendered correct on the front end.

## Umbraco version

I am seeing this issue on Umbraco version: 8.3.0

Reproduction
------------

### Bug summary

    * If i put some basic (special) characters like a single quote ('), double qoute (") or an ampersand (&) it doesn't get rendered correct on the front end.
    * Like this: `&#x27;Single quote&#x27; --- &quot;Double quote&quot; --- &amp; - Ampersand`
    * HTML looks like this: `@if (!string.IsNullOrEmpty(Model.MacroParameters["tekst"].ToString())){
    <p>
    @Model.MacroParameters["tekst"].ToString()
    </p>
}`

### Specifics

    * Umbraco Version 8.3.0
    * Google Chrome V79.0.3945.88

**Comment by kjac** [comment]
Hi @PvanGeffen 😄 

The characters aren't encoded in the backoffice macro textarea after saving and reloading the content, so I do not believe this is an Umbraco issue.

It is more likely a matter of how Razor prints out certain HTML entities during rendering. You'll need to tell Razor to stop encoding them, if you indeed need them unencoded.

If this doesn't help you, you can try looking for help on [the forum](https://our.umbraco.com/forum/).

**Comment by stevemegson** [comment]
I think this is the same problem as #6286. The macro parameters are HTML-encoded when stored within the HTML in the RTE, and they're not decoded before populating `Model.MacroParameters` to render the macro.

As discussed on the other issue, it would be easy to fix but would probably be a breaking change.

**Comment by kjac** [comment]
@stevemegson thanks a bunch for cross linking 👍
