### ISSUE TITLE
Media Picker: 404 errors for images when running Umbraco in a Virtual Directory

### ISSUE THREAD

**Issue by skidmow** [umbraco/Umbraco-CMS#7420]
The Umbraco Media Picker is no longer working for applications that are setup as a virtual application in IIS, rather than as a website. The media will no longer be found and will 404 error.

## Umbraco version

I am seeing this issue on Umbraco version: 7.15.3

Reproduction
------------

### Bug summary

Could be related to this change: https://github.com/umbraco/Umbraco-CMS/pull/6205

### Specifics

The FileSystemProviders.config has this entry:
`<add key="virtualRoot" value="~/media/" />`

If the website runs in a Virtual Directory named `cms`,  all Umbraco pages and media should be served with a `/cms/` prefix.

Media paths are no longer being served from `/cms/media/`, but instead `/media/`, which doesn't exist and will therefore 404 error.

You cannot resolve this issue by changing to the value below, as that results in an error stating that media cannot live outside of the application root.
`<add key="virtualRoot" value="~/cms/media/" />`

### Steps to reproduce

- Setup Umbraco 7.15.3 under a Virtual Directory in IIS. E.g. Create a Website in IIS and then a Virtual Application, where you will install Umbraco. Name it something like `cms`.
- Add media to the back-office. The media will be uploaded fine and you should see the thumbnail.
- Add the media to a page via the Media Picker. The media picker will throw a 404 in the console as the image cannot be found.
- Inspect source in the browser and you will see the media picker is trying to serve the thumbnail from `/media/`, rather than `/cms/media/`.

### Expected result

The media picker should respect the application root (~) path and serve the images from `/cms/media/`.

### Actual result

Images are being served from `/media/`, which doesn't exist in this context.

**Comment by nul800sebastiaan** [comment]
Link to the PR: https://github.com/umbraco/Umbraco-CMS/pull/7424

**Comment by nul800sebastiaan** [comment]
I didn't manage to get a 404 like you, but you do get a 500 error with the wrong path for resizing the image:  

![image](https://user-images.githubusercontent.com/304656/71927967-e7adbd80-3196-11ea-8668-e5bb11446d65.png)

To fix, I had to add this to my web.config:

`<add key="umbracoMediaPath" value="~/cms/media" />` after which I could upload a new media item and that would work. Items uploaded before this change won't work because they've stored the wrong path to begin with, there's updates you can do for that, for example: https://shazwazza.com/post/sql-script-for-changing-media-paths-or-virtual-directories-in-umbraco/

**Comment by skidmow** [comment]
I have tested the above as described and I no longer get the error (yes it was a 500, but it is serving an image with a path that doesn't exist, hence the 404).

However this now introduces a new error:
When new images are uploaded, the mediaPath is left empty in the cmsMedia table. As a result, the media picker does not display the media thumbnails, it just displays an image icon. I know there are SQL scripts available to fix this issue for existing media, but it is affecting me on new items added to media as well as old ones. Any thoughts?
