### ISSUE TITLE
Custom tree active node Issue when more than one tree exists in a given section

### ISSUE THREAD

**Issue by mikeleitzel** [umbraco/Umbraco-CMS#7423]
Custom trees that use an external datasource may share IDs with Umbraco Nodes. In the case that there is more than one tree in a given section where a node in more than one tree has the same id, then both nodes are marked 'active'.

## Umbraco version

I am seeing this issue on Umbraco version:  8.1+

Reproduction
------------

If you're filing a bug, please describe how to reproduce it. Include as much
relevant information as possible, such as:

### Bug summary

If you have more than one tree per section, and each tree is using an auto incrementing id from custom table, it is possible to have the same id in different trees of the same section. When that happens the directive sets the active flag for all nodes with that ID.

### Specifics

We put a fix in the umbraco.directives.js to check for the tree alias as well as the id.

/umbraco/js/umbraco.directives.js:

This code with our comments is where the problem exists.
```
                    if (actionNode) {
//Nogle 20200106 - conditional -  Prevents nodes with the same id from being actvie
                       if (actionNode.id === node.id && String(node.id) !== '-1' && actionNode.metaData.treeAlias === node.metaData.treeAlias) {
                       //if (actionNode.id === node.id && String(node.id) !== '-1' ) {
                           css.push('active');
                       }
                       // special handling of root nodes with id -1
                       // as there can be many nodes with id -1 in a tree we need to check the treeAlias instead
                       if (String(node.id) === '-1' && actionNode.metaData.treeAlias === node.metaData.treeAlias) {
css.push('active');
                       }
                   }
```

### Steps to reproduce

Steps are difficult to reproduce as it requires a custom tree within the same section using a tree that could possibly share IDs

### Expected result

We expect the active node of the active tree to be only 'active' node.

### Actual result

Nodes with the same ID show as active within several trees of the same section.

**Comment by mikeleitzel** [comment]
We are going to submit this as a pull request soon.  Please note that we are relative rookies when it comes to contributing, so give us a moment.

**Comment by nul800sebastiaan** [comment]
Link to the PR: https://github.com/umbraco/Umbraco-CMS/pull/7424

**Comment by nul800sebastiaan** [comment]
As mentioned on the PR, I can't reproduce this at the moment but let me know what we need to do and we can have another look!
