### ISSUE TITLE
Copy content with nested content properties 

### ISSUE THREAD

**Issue by cmwalolo** [umbraco/Umbraco-CMS#7431]
I copied 100 price tables and edited them directly. I noticed that values are not reflected a bit late (#{^[##{[{! Apparently nested content have some id, which are not renewed when we copy content, or something like this. 

When copying and pasting values back in the nested content editor, the issue is solved, and my new values are well exposed through the model builder

I am seeing this issue on Umbraco version 8.0 to 8.4

**Comment by nul800sebastiaan** [comment]
Thanks @cmwalolo, we're aware of the issue and have proposed a solution for the community to work on, make sure to follow this issue for updates: https://github.com/umbraco/Umbraco-CMS/issues/5913
