### ISSUE TITLE
Make CSS/LESS more DRY

### ISSUE THREAD

**Issue by nathanwoulfe** [umbraco/Umbraco-CMS#7441]
Looking through the backoffice front-end project, we have a lot of repeated CSS rules (box-shadows being the one that started me on this issue). I'd like to spend some time refactoring existing CSS to use mixins/variables instead of repeating property values, which becomes error prone and harder to maintain.

As an example, I've refactored the healthchecks dashboard LESS file (purely because it appeared in a particular box-shadow search). Changes improve the structure of the file to namespace the component with sensible nesting, and uses a couple of class mixins to apply box-shadow (including hover state and transitions).

Will create a PR with the changes, for discussion before I rip through any others. Color and type are already pretty good, but there's lots of room for improvement by replacing repetition with generated styles. Happy to chip away at this

**Comment by nul800sebastiaan** [comment]
Sounds great to me! I would suggest you make multiple focused PRs, so one for shadows, one for ?? whatever else area you find, etc. That will make it a lot easier to review and isolate changes! Thanks! 👍

**Comment by nul800sebastiaan** [comment]
@nathanwoulfe just closing this as an issue, if you want to make PRs then feel free.
