### ISSUE TITLE
If picking no icon color for DocumentTypes it should save the default color

### ISSUE THREAD

**Issue by nielslyngsoe** [umbraco/Umbraco-CMS#7445]
If the color of a DocumentType is removed it should be set to the default color.
Currently, if you de-select your current color and save, you will still have the same color as before.

![image](https://user-images.githubusercontent.com/6791648/72144007-0b8c2180-3398-11ea-9d78-0f60644fbee9.png)

**Comment by nathanwoulfe** [comment]
GOT IT BEFORE @kjac! It's a belated Christmas miracle!

**Comment by kjac** [comment]
🤯

**Comment by emmaburstow** [comment]
Fixed in #7448
