### ISSUE TITLE
Scheduled Publishing not working with multiple cultures

### ISSUE THREAD

**Issue by Serder** [umbraco/Umbraco-CMS#7452]
## Umbraco version

I am seeing this issue on Umbraco version: 8.4

Reproduction
------------
### Bug summary
I have an Umbraco site that has two cultures: French and English. I have a ListView of Articles (document type) and I want to use the Scheduled Publishing feature for these articles. However I get the following error when I try to do it.

{Message: "No variants flagged for saving"}
Message: "No variants flagged for saving"
![image](https://user-images.githubusercontent.com/8854467/72290476-536eab00-361b-11ea-9fb2-82de5fc3d4b4.png)

![image](https://user-images.githubusercontent.com/8854467/72290528-6e411f80-361b-11ea-9bb5-85ae100788d7.png)

this happen on this URL on chrome: http://localhost:50896/Umbraco#/content/content/edit/2739?mculture=fr-CA

### Steps to reproduce

1. Have a document type that has culture sharing enabled
![image](https://user-images.githubusercontent.com/8854467/72290578-8dd84800-361b-11ea-8096-b027dca9cca7.png)

2. Create some content with this document type and fill in the content fields
3. Click Scheduled Publishing and try to publish in the future
4. Get the error 

I discovered this last week and investigated. I found no reference to that bug in the 8.4 version. I tested with a document type in which the "Allow varying by culture" is not checked and the scheduled publishing worked. However, for our project, we need that Varied cultures to be enabled.

We have another project using Umbraco 8.2 in which the scheduled publishing works with the varied cultures enabled.

### Expected result
The element is set to be published in the future date
### Actual result
Error as shown before.

**Comment by stevemegson** [comment]
`ContentSaveValidationAttribute` is checking that at least one variant has the `save` property set, which isn't true when scheduling content which varies by culture.

We have this code to deal with invariant content before the schedule dialog is opened:

```javascript
if (!isContentCultureVariant()) {
    //ensure the flags are set
    $scope.content.variants[0].save = true;
}
```

When the dialog is submitted we copy the dates over from `model` to `$scope.content`. I guess we need to check here which variants have changed and set the `save` property accordingly. Or would it be safe to just set `save` on all variants even if we're just re-saving the existing dates?

**Comment by dawoe** [comment]
I stumbled on this my self today in 8.4. It is definitly a bug. The website I saw this is on is also a multilingual website

Dave

**Comment by dawoe** [comment]
Just had quick dive in the source code to see what was going on and made a PR for this #7456

**Comment by stevemegson** [comment]
@dawoe ah, if `save` is actually being set properly on `model.variants` then that explains why it worked in 8.2. We used to pass `$scope.content.variants` straight to the dialog, rather than passing a copy and then copying the changes back.

**Comment by nul800sebastiaan** [comment]
Fixed in https://github.com/umbraco/Umbraco-CMS/pull/7456

**Comment by Jay-umbr** [comment]
This still happens on 8.5.4 - possibly a regression?

**Comment by Jay-umbr** [comment]
@nul800sebastiaan Could we reopen this?

**Comment by nul800sebastiaan** [comment]
@Jay-umbr the label says `release/8.6.0`, so the fix will be available in the soon to be released 8.6.0 👍

**Comment by Jay-umbr** [comment]
🤦‍♂ 
Thanks, i should pay more attention :)

**Comment by Serder** [comment]
I downloaded the 8.6.0 rc nuget package and I can confirm the scheduled publishing didn't crash anymore on a page with multiple languages.

**Comment by Corjaantje** [comment]
Currently on Umbraco 8.6.0 and the issue seems to still be relevant. Anyone else experiencing the same?

**Comment by remkovb** [comment]
Yes, we are still experiencing same error in 8.6.0: "No variants flagged for saving"

**Comment by Sophiehillebrant** [comment]
Experiencing the same issue still, currently on 8.6.4
