### ISSUE TITLE
Preview breaks with http redirect when behind https load balancer and trailing slash enabled.

### ISSUE THREAD

**Issue by neilgaietto** [umbraco/Umbraco-CMS#7453]
The problem
------------
Edit: I am still evaluating what exactly is going on here. But it seems like the preview redirect is fine, but its the preview redirecting with the forced '/' causing the problem. Sorry if this is a little messy while I update.

For some reason the redirect to add a trailing slash on the preview url "{nodeid}.aspx" is pre-pending the wrong protocol. This seems to work fine with every other url.

Preview is redirecting to an http url when viewed on a load-balanced https url. This causes a "Mixed Content" error because browsers will not let you load http iframe content on an https page.

We host an umbraco site behind an aws load balancer. As many load balancers work, it takes in https requests but forwards the request as http to the web server. 

## Umbraco version

I am seeing this issue on Umbraco version: 7.15.3. We just upgrade from 7.4.3, where it used to work.

Reproduction
------------

### Specifics

The core of the problem when using a load-balancer and forcing the trailing slash. Seems to be an issue only with the node preview urls (those with the {nodeid}.aspx)
The request: https://domain/umbraco/dialogs/Preview.aspx?id=180668
Redirects to: /180668.aspx (fine)
Then Redirects to: http://domain/180668.aspx/ (breaks after proto://hostname is added)

### Request workflow
1. User Loads Preview at https://domain/umbraco/preview/?id=180668
2. This page makes a request to: https://domain/umbraco/dialogs/Preview.aspx?id=180668
3. Load balancer accepts https request
4. Load balancer forwards request to http://domain-server/umbraco/dialogs/Preview.aspx?id=180668
5. Preview.aspx uses request protocol to generate url
6. Preview.aspx responds with redirects user to: /180668.aspx
7. /180668.aspx sees that it requires a trailing slash so it redirects the user to: https://domain/180668.aspx/
8. Initial Preview page is stuck unable to load the http redirect on the https page.

### Steps to reproduce
1. Enable:     <addTrailingSlash>true</addTrailingSlash>   
2. Run site behind an https load balancer that directs traffic to an http umbraco web server.
3. Preview a page

### Expected result

The preview should be show, keeping the same protocol as the initial request.

### Actual result

Mixed Content Error - No Preview Displayed

Solution?
------------

Give devs a way to override which header is used to detect protocol. In this case we just need umbraco to detect the `X-Forwarded-Proto` header instead of checking for the HTTPS header.

Or,  It seems like the easiest solution would be to not include the protocol & domain in the trailing slash redirect. Maybe this is how the older version worked?

### Additional Notes
As it stands now, I haven't come up with a good work around.
The preview page loads in Preview.aspx over https, but then the response is a 301 to an http page. Once the iframe gets to the http content its over. I cant redirect back to https to fix the issue.

**Comment by neilgaietto** [comment]
This is my own fault. Disregard.

**Comment by MknNM** [comment]
@neilgaietto could you explain what you did to resolve this?

**Comment by neilgaietto** [comment]
@MknNM Kind of a specific case for our app, but just in case.

We have a custom event on request that forces a trailing slash. So if a page request comes in like `/some/page` then it gets redirect to `/some/page/`.

The problem was that the preview page is actually an `.aspx` page. We did not expect this, because we disable this extension for umbraco pages. We actually use MVC, so it is very unexpected to see an .aspx page.

So basically what was happening is `/preview.aspx` was getting redirect to `/preview.aspx/` which breaks the page.

To fix: I just added an exception so that it does not force trailing slashes if it has an `.aspx` extension.

Here is my code for reference:

        public void OnApplicationStarted(UmbracoApplicationBase umbracoApplication, ApplicationContext applicationContext)
        {
            // Add trailing slash check
            PublishedContentRequest.Prepared += PublishedContentRequest_Prepared_CheckTrailingSlash;
        }

        private void PublishedContentRequest_Prepared_CheckTrailingSlash(object sender, EventArgs e)
        {
            PublishedContentRequest request = sender as PublishedContentRequest;

            if (request == null || request.HasPublishedContent == false) return;

            if (!HttpContext.Current.Request.Url.AbsolutePath.EndsWith("/") 
                        && !HttpContext.Current.Request.Url.AbsolutePath.Contains(".aspx"))//<-- Fix here
            {
                var newPath = HttpContext.Current.Request.Url.EndPathWithSlash();
                request.SetRedirectPermanent(newPath.PathAndQuery);
            }
        }
