### ISSUE TITLE
Can't create or save document types in 8.5 with full ModelsBuilder installed

### ISSUE THREAD

**Issue by sniffdk** [umbraco/Umbraco-CMS#7457]
Just upgraded from 8.3 to 8.5 with the full ModelsBuilder installed. I now can't create or update document types.
I get the following error:
![image](https://user-images.githubusercontent.com/1074004/72351081-f688f880-36df-11ea-88fa-7a021dac0588.png)

I also tried to install an empty 8.5 from nuget. When full ModelsBuilder is installed, the same error is shown. 
If I uninstall ModelsBuilder creating and saving document types works again.

**Comment by nul800sebastiaan** [comment]
😱
We're working on it!

**Comment by nul800sebastiaan** [comment]
Thanks for the report, can reproduce unfortunately, working on a PR now. Sorry about this, we did test this scenario of course, I'm not sure what went wrong during testing! 😰

**Comment by sniffdk** [comment]
No worries, just glad you are working on a quick fix 😄
