### ISSUE TITLE
Moving the Media folder causes the Media picker to stop recognizing images as images

### ISSUE THREAD

**Issue by MatsStam** [umbraco/Umbraco-CMS#7462]
## Umbraco version

I am seeing this issue on Umbraco version: 8.1.4 and 8.4.0

Reproduction
------------

If you're filing a bug, please describe how to reproduce it. Include as much
relevant information as possible, such as:

### Bug summary
When specifying another location for the "media folder" with a composer.
`public class MediaComposer : IUserComposer
    {
        public void Compose(Composition composition)
        {
            var siteConfig = DependencyResolver.Current.GetService<ISiteConfig>();
            var rootPath = siteConfig.UmbracoUploadRootPath;
			composition.SetMediaFileSystem(() => new PhysicalFileSystem(rootPath, "/upload"));
        }
    }`

Where siteConfig.UmbracoUploadRootPath is the equivalent of (IE c:\here\it\goes or \\networklocation\here\it\goes\again).

It becomes impossible to select images in the WYSIWYG insert media plugin or the normal media picker if you set the option "Only images" to true. They act more like folders then images...

### Steps to reproduce

1. Create a composer which moves the media folder:
`public class MediaComposer : IUserComposer
    {
        public void Compose(Composition composition)
        {
            var siteConfig = DependencyResolver.Current.GetService<ISiteConfig>();
            var rootPath = siteConfig.UmbracoUploadRootPath;
			composition.SetMediaFileSystem(() => new PhysicalFileSystem(rootPath, "/upload"));
        }
    }`

2. Add a richtext property
3. Click the Media Picker in the WYSIWYG
![media picker](https://user-images.githubusercontent.com/5585159/72441168-7c717600-37aa-11ea-9ab8-1c7b1d91faec.png)

4. Select an image from the media picker window to the right.
![selected image](https://user-images.githubusercontent.com/5585159/72441187-83988400-37aa-11ea-9fe1-7904b63269ab.png)

### Expected result

I expect to be able to insert an image from the Media library

### Actual result

Now you cannot select an image in the media picker from the right. They act like folders when clicked.

**Comment by nul800sebastiaan** [comment]
You don't have to create a composer for this though, you can configure the media path by configuring it in your appSettings:

`<add key="umbracoMediaPath" value="~/upload" />`

Just remember that already uploaded files have stored the `/media` path already. There's a SQL script you can update a little to replace `/media` with `/upload`. Come to think of it that might also be the solution for your current situation.

If you have additional questions make sure to head on over to https://our.umbraco.com and ask follow up questions there! 👍

**Comment by MatsStam** [comment]
So... I removed the composer, and added the appsetting just like you posted. It uploads the image and saves it as expected in /upload under the web. But it still has the exact same behaviour, when trying to select the image  

Also that path apparently need to start with a ~/ and must be a virtual path. I want to place the media folder outside of the web-folder and preferably on a network path (ie. \\myServer\RuntimeFiles\project\UmbracoUploads\upload)

This does nothing to solve my problem :/

**Comment by nul800sebastiaan** [comment]
I think you will need to do something with the `FileSystemProvider.config` then, make sure to get some help on the [forum](https://our.umbraco.com)!

**Comment by MatsStam** [comment]
Well... I contacted the Umbraco support, and they tried helping me, said I found a bug, and asked me to register it here... So I did 😛

**Comment by nul800sebastiaan** [comment]
A right, that's unfortunate, I don't mean to give you the runaround, but I'm sure there's a way to make this work. 

Looks like `FileSystemProvider.config` is not a thing any more on v8, sorry about that.

This comes to mind - https://our.umbraco.com/Documentation/Reference/Config/fileSystemProviders/#physical-path

And it looks like you will need to map a virtual directory in IIS for the second argument, so if you set it to `/upload`, you will need to map a vdir `upload` to what you set in the first argument (`c:\\here\\it\\goes or\\networklocation\\here\\it\\goes\\again`).
