### ISSUE TITLE
Umbraco exposes attribute for creating an installation step, but doesn't allow for customization of installation

### ISSUE THREAD

**Issue by bielu** [umbraco/Umbraco-CMS#7464]
Hi all,

I was looking into a way to unregister default installation starter kit with v8 installation, but actually I noticed a few things:
`InstallSetupStep<T>` is public
`InstallSetupStepAttribute` is public and sealed
Which is fine, but here we could notice, something that in my opinion is weird:
`InstallStepCollection` is public and sealed
`public static class Installer` is a static helper class

And from my perspective, I don't really understand why:

1. InstallStepCollection is sealed and not written in a way where we could add/remove steps, which are safe to remove, as they are not required for successful installation (I.e. Starter kit installation)?
2. Installer class: why it was done as a static helper, instead of smaller Components/ Composer to allow to remove not needed parts?

Thanks,
Arkadiusz

**Comment by Shazwazza** [comment]
The installer itself is/was never meant to be publicly modified, the installer code is also old and wasn't updated very much in v8. There are some internal concepts that rely on the installer being the way that it is without being modified. I'm unsure if it will be changed to support being altered but would need to ask internally.

**Comment by nul800sebastiaan** [comment]
At the moment we don't have active plans to enable customization of the installer. 
It is something we want to look at in the future but it's not on the roadmap right now.

I'll note this issue with `status/idea` which means it goes on the list of items to review in the future when we need inspiration for making changes to certain areas of Umbraco. We welcome people to add their own ideas about customizing the installer to this discussion so we can review them in the future when we do start working on this feature. 

Issues with the `status/idea` label will automatically be closed after a 100 days. This doesn't mean we will never do it, but that we haven't found space on the roadmap yet. We regularly review the list of closed issues with the `status/idea` label to put on the roadmap in the future.

**Comment by bielu** [comment]
Guys, maybe I should point that in the first post, but actually it is still possible to override half Umbraco (in a supported way) and replace installer. However, we are in a situation where you are giving tools, but not allow to use them. This is almost like you bought a new toy for children but glued that to the floor to avoid breaking that by a child. 

Actually I am seeing a few ways how it could be exposed and secured at the same time, but actually, in my opinion, if it is not going to be change it should definition of InstallSetupStepAttribute and InstallSetupStep<T> to internal as it is no point to expose them if you are not allowed to use them.

And going again into code we are welcomed by that comment 

>  // TODO: this is ugly but I have a branch where it's nicely refactored - for now we just want to manage ordering

added by Houston 1 year ago
I could understand Umbraco doesn't have the capacity to solve all issues, but that type of comment is not something that should be here at all, as it was here more than 12 months here... 
I am happy to make PR to change how the installer works but the points:

1. At the moment we don't have active plans to enable customization of the installer.
2. It is something we want to look at in the future but it's not on the roadmap right now

Putting into a situation when I have felt even if I would make PR it would be not reviewed for next years.

**Comment by nul800sebastiaan** [comment]
@bielu Sorry, we didn't give you toys on purpose. Allowing you to override the installer steps is great, but we also need to be able to support that properly, people will have questions, people will do things we didn't foresee. This doesn't have our focus right now and is not something we will be prioritizing.

The refactor from a year ago was for the v8 release, you can see the history here: https://github.com/umbraco/Umbraco-CMS/commits/v8/dev/src/Umbraco.Web/Install/InstallStepCollection.cs

Chris Houston only updated a comment to add a space between `//` and `TODO` - https://github.com/umbraco/Umbraco-CMS/commit/193e24afd256b2994a0900c0e9739f3f3466c036#diff-e854655c0a44127b46298b6f647920acR34

**Comment by bielu** [comment]
@nul800sebastiaan ok my mistake I looked which line was added by who, but even worse if that is more than one year here :C 

I am happy to prepare changes, but it should be at least option to disable the installation of starter kit by default.

**Comment by nul800sebastiaan** [comment]
Just remember that right now, I don't know what the implications are of that so we might not be able to approve your PR.

**Comment by ronaldbarendse** [comment]
There's already an open issue for this: https://github.com/umbraco/Umbraco-CMS/issues/6421.

**Comment by bielu** [comment]
@ronaldbarendse actually they are quite related with each other as my issue was mostly about removing steps, #6421 was related to adding steps :)
