### ISSUE TITLE
V8.5.1: Ambiguous extension method signature between embedded and external ModelsBuilder

### ISSUE THREAD

**Issue by sniffdk** [umbraco/Umbraco-CMS#7469]
The IPublishedContent .Value extension method that takes an Expression<Func<TModel, TValue>> parameter is duplicated in the new embedded ModelsBuilder.
Due to them being in the same namespace, there is an ambiguous call between the two, as the method signatures are identical.
Screenshots below:
![image](https://user-images.githubusercontent.com/1074004/72601047-f6257300-3914-11ea-9f52-8d3fe89d1621.png)

![image](https://user-images.githubusercontent.com/1074004/72601066-fd4c8100-3914-11ea-9029-666eaa6fb0d9.png)

**Comment by nul800sebastiaan** [comment]
Thanks again Mads, we're looking into it!

**Comment by ronaldbarendse** [comment]
This issue is now fixed in PR #7470 by renaming the Umbraco.ModelsBuilder.Embedded version of `Value(...)` to `ValueFor(...)`:

https://github.com/umbraco/Umbraco-CMS/blob/41dc8d915bdcadb628e6dde9422586310ac66a1b/src/Umbraco.ModelsBuilder.Embedded/PublishedElementExtensions.cs#L20

**Comment by clausjensen** [comment]
Closing this one - fixed (final fix) in 8.5.3 😄

**Comment by bielu** [comment]
@nul800sebastiaan This one should be flagged as braking change name of Extension method was changed, which means we break code which was using that.

**Comment by nul800sebastiaan** [comment]
Okay, done.
