### ISSUE TITLE
8.5.2 still seeing roslyn compiler included...

### ISSUE THREAD

**Issue by mistyn8** [umbraco/Umbraco-CMS#7492]
lifted from the blog for 8.5
"ZBU Modelsbuilder is an amazing tool that does a whole lot of different things. We have decided not to include some of the more advanced functionality such as the ability to automatically generate DLLs (this means we don’t have to ship with the entire Roslyn compiler) and the ability to customize Modelsbuilder models with attributes."

I'm still seeing the roslyn compiler in the bin folder for a brand new 8.5.2 nuget build... is it still used for template compilation? 
If so is this moot to remove Dll mode?

**Comment by nul800sebastiaan** [comment]
Yes, I asked about this in the team as well, the answer: 

> We DO ship part of the rosyln compiler because that is what MVC ships and that is how views are compiled.
> This is the roslyn razor view compiler, this has nothing to do with MB, this is shipped as part of a default MVC site and we added this when we finally fixed how we compile views.

The `<compilers>` section in web.config is what help compile views faster.

**Comment by mistyn8** [comment]
Hmm.. I can see that dll is removed, but I don't see any difference in the roslyn bin folder between a site with full modelsbuilder and embedded models builder.
If that's the case could we reintroduce dll mode?

**Comment by nul800sebastiaan** [comment]
Here's the list of differences between a clean NuGet install of 8.4.0 (left) and a clean NuGet install of 8.5.2 (right). On both sites I ran the installer and made sure I could log into Umbraco.

The blue items on the left (8.4.0) are not found in the right side (8.5.2). Red items are files that exist on both side and have differences between both sides. Blue items on the right side (8.5.2) could not be found on the left side (8.4.0)

![image](https://user-images.githubusercontent.com/304656/72909602-9295ae00-3d37-11ea-8efa-7e9b85f9cf80.png)

Dll mode is only available in the "Zbu version" of models builder, which you are free to install in your 8.5+ projects if you need it.

**Comment by mistyn8** [comment]
hmm.. why would 8.4.0 on the left have a version of Models.Builder.Embedded.dll?
And presumably that means the roslyn folder is identical on both sides, hence removing dll mode isn't necessary as we already have the full roslyn compiler ;-) Unless of course there are other reasons for removing dll mode other than not shipping roslyn?

**Comment by nul800sebastiaan** [comment]
Sorry, that was me testing what would happen if I dropped it into an older site 😅 

The Roslyn folder matches. There are a lot of other libraries missing that make up the FULL roslyn compiler. 

We don't plan to support Dll mode - you've presumably read the explanation of the choices here: https://umbraco.com/blog/umbraco-85-release/

> A larger feature-set is great, but unfortunately, it also comes with an added layer of complexity that needs to be maintained over time. We feel that if you have the need for these advanced features, you are better off using the external package where these features are maintained by the people who created them in the first place.
>
> The “new” core Umbraco Modelsbuilder contains the features that are required for Umbraco 8 to run: PureLive mode to generate models at runtime and also AppData mode to create partial classes if you want to work with these in your VS solution.
