### ISSUE TITLE
v8.5.2 ImplementPropertyType not working as expected with Partial classes in ModelsBuilder

### ISSUE THREAD

**Issue by JasonElkin** [umbraco/Umbraco-CMS#7495]
Adding the `ImplementPropertyType` attribute to a property in a partial class does not prevent ModelsBuilder from generating the property.

## Umbraco version

I am seeing this issue on Umbraco version: 8.5.1 & 8.5.2

Reproduction
------------

### Bug summary

Adding the `ImplementPropertyType` attribute to a property in a partial class (in the same directory as the ModelsBuilder models does not prevent ModelsBuilder from generating the property in the generated file.

I first assumed that this functionality was removed in 8.5 with ModelsBuiler.Embedded however the problem persists after installing the full version Umbraco.ModelsBuilder.

### Specifics

This is a problem in a clean install using either Umbraco.ModelsBuiler.Embedded or  Umbraco.ModelsBuilder Using the following App Settings:

```
<add key="Umbraco.ModelsBuilder.Enable" value="true" />
<add key="Umbraco.ModelsBuilder.ModelsMode" value="LiveAppData" />
<add key="Umbraco.ModelsBuilder.ModelsDirectory" value="~/Models/ContentModels" />
<add key="Umbraco.ModelsBuilder.ModelsNamespace" value="UmbracoMbTest.Models.ContentModels" />
```

### Steps to reproduce

1. Using the cofig above, add a partial class in "~/Models/ContentModels"
2. Install `Umbraco.ModelsBuilder`

```
namespace UmbracoMbTest.Models.ContentModels
{
    public partial class SomeDoc
    {
        [ImplementPropertyType("myProperty")]
        public string MyProperty => "Ahoy!";
    }
}
```
3. Create a doc-type called "SomeDoc", with a property called "MyProperty"
4. Generate Models

### Expected result

SomeDoc.Generated.cs should not contain "MyProperty".

### Actual result
It does ([screenshot](https://drive.google.com/file/d/1Uw_b7jwXlkOVYlgh58NV70zJYer7dZrd/view?usp=sharing)).

**Comment by dawoe** [comment]
Hi @JasonElkin 

As I understood this is one of the features of ModelsBuilder that is not in the core version.

I don't think this is clearly documented. I just got it from this PR : https://github.com/umbraco/Umbraco-CMS/pull/6795

Dave

**Comment by JasonElkin** [comment]
Hi @dawoe ah good point, I missed out a step! I do in fact have the "full" Umbraco.ModelsBuilder package installed.

**Comment by JasonElkin** [comment]
Not a bug, my mistake - I was using the wrong namespace for `ImplementPropertyType` 🤦‍♂️

I was using `Umbraco.ModelsBuilder.Embedded.ImplementPropertyType` when I should have been using `Umbraco.ModelsBuilder.ImplementPropertyType`.

**Comment by nul800sebastiaan** [comment]
We'll not close this one yet, I'll have to ask around but if we really can't use this attribute in the embedded version, it should not be available.

**Comment by JasonElkin** [comment]
@nul800sebastiaan sure.  ModelsBuilder.Embedded doesn't include [the parser that actually uses it](https://github.com/zpqrtbnk/Zbu.ModelsBuilder/blob/4e0aeebaec6ec1dbfd43be69fe7e07a1085ce33c/src/Umbraco.ModelsBuilder/Building/CodeParser.cs#L120). So I guess [the attribute](https://github.com/umbraco/Umbraco-CMS/blob/ad53b7630837de8db7bc7871dacea9af2a51e4f4/src/Umbraco.ModelsBuilder.Embedded/ImplementPropertyTypeAttribute.cs#L8) is redundant.

**Comment by nul800sebastiaan** [comment]
Sorry for the delay on this one. We currently have no plans to work more on the core Modelsbuilder implementation and recommend using the community package instead.

I'll put this on the list of ideas for when we're looking to work on new features around core Modelsbuilder again.

**Comment by nul800sebastiaan** [comment]
I'll close this in favor of https://github.com/umbraco/Umbraco-CMS/issues/7734 - now that I better understand the issue, I realize this is the same problem.
