### ISSUE TITLE
Tinymce - Why this not take this color, font (styles)

### ISSUE THREAD

**Issue by JesperPetersenDk** [umbraco/Umbraco-CMS#7501]
This is the case when, for example, I need to copy a text from A to B. Which has the color red and a specific font. When I have to overwrite it from A to B, it does not include font and style.

Here you can see code.

What stands first. It is what I have tried but what is at the bottom is what I want to achieve.

It used to work in Umbraco 7 but in Umbraco 8 it won't do anything. So it will not bring style over.

[See code here.](https://our.umbraco.com/forum/using-umbraco-and-getting-started//100820-tinymce-why-this-not-take-this-color-font-styles)

i want to hear about what goes wrong since i can in no way copy text but it doesn't get style or anything?

**Comment by nul800sebastiaan** [comment]
Thanks, I see you've already posted this question to the forum which is the right place to ask questions. 👍 
 
I'll close this one and I'm sure our friendly community can help you along with this question.
