### ISSUE TITLE
PartialViewMacroModel should implement IContentModel

### ISSUE THREAD

**Issue by tompipe** [umbraco/Umbraco-CMS#7504]
## Umbraco version

I am seeing this issue on Umbraco version: 8.4.0

Reproduction
------------

### Bug summary

Within the UmbracoViewPage, when first requesting the current UmbracoHelper, there's some logic to create one from the ViewData.Model.

If the Model implements IContentModel, it sets up the umbraco helper with the AssignedContentItem from the Model.

https://github.com/umbraco/Umbraco-CMS/blob/0b6f1f6e117d1cb475230073699c725ea7b2dd4a/src/Umbraco.Web/Mvc/UmbracoViewPageOfTModel.cs#L82-L100

However, PartialViewMacroModel doesn't implement IContentModel, so the UmbracoHelper in a PartialViewMacroPage doesn't have an AssignedContentItem set correctly, resulting in the following error:

![image](https://user-images.githubusercontent.com/629719/73086881-60b45100-3ec9-11ea-876f-c38b45a006b5.png)

### Steps to reproduce

1. Create a new partial view macro (with macro)
2. Enable use in RTE & grid
3. Enable render in RTE & grid
4. Add `@Umbraco.AssignedContentItem.Name` to the macro partial
5. Configure a grid layout on a page, and allow macro editor.
6. Add the macro to the grid cell
7. Observe the error

### Expected result

The UmbracoHelper correctly initialised with the current content item.

### Actual result

The UmbracoHelper is not correctly configured, resulting in an error

**Comment by nul800sebastiaan** [comment]
Fixed in https://github.com/umbraco/Umbraco-CMS/pull/7505
