### ISSUE TITLE
V8: Child items don't appear when opening a list view node from MNTP

### ISSUE THREAD

**Issue by saifobeidat** [umbraco/Umbraco-CMS#7509]
I got the below message, when I use "open" option in the MNTP to open a list view a node:
> No child items have been added

## Umbraco version

I am seeing this issue on Umbraco version: 8.4 

### Steps to reproduce
1- Create a container node, and add children underneath it, enable list view option to this container.
2- In another node, create a MNTP property and then enable "open" option.
3- Add that container node to the MNTP, then try to open it, you won't see its children.

See below GIF:

![2020-01-25_18-22-25](https://user-images.githubusercontent.com/24841143/73124106-f6221480-3f9f-11ea-8c5d-c4ebe5850cd3.gif)

### Expected result
See the child items of the picked container

### Actual result
Got no child items have been added

**Comment by nul800sebastiaan** [comment]
Hey there @saifobeidat, I've tried to reproduce the problem but I can't seem to, even with some different configurations. 
Have a look:

![7509](https://user-images.githubusercontent.com/304656/73262526-ad03d780-41ce-11ea-8a23-b7c740b6e4e0.gif)


Let us know if you have more steps to reproduce, I might just be missing something.

**Comment by saifobeidat** [comment]
Hi @nul800sebastiaan , I could reproduce a similar issue on v8.6 .

I noticed on your GIF, you didn't open the List-View node using the `Open` option in the MNTP.
![image](https://user-images.githubusercontent.com/24841143/78502343-6223b480-7769-11ea-8f81-c6f96d907b21.png)


If you notice below, `Ads Group1` node has 3 children `Ad1, Ad2, Ad3` and when I open `Ads Group1` using the `Open` option I should see its children : `Ad1, Ad2, Ad3`, but that doesn't happen because I see the direct parents of the children. 
![2020-04-05_14-39-43](https://user-images.githubusercontent.com/24841143/78473748-9daf8600-774b-11ea-89f7-a8a07f05a798.gif)

Please try to open the node in MNTP using the "Open" option
