### ISSUE TITLE
List search should be updated accordingly to other list search inputs.

### ISSUE THREAD

**Issue by nielslyngsoe** [umbraco/Umbraco-CMS#7517]
User search should be updated accordingly to other list's search inputs.

In Content-listview and Media the search input have recently been updated to use <umb-mini-search>. Accordingly the users-section should be updated to use the same.

User-section today:
![image](https://user-images.githubusercontent.com/6791648/73156217-6aae9d80-40dd-11ea-9120-38fe2bc575f0.png)

How it's supposed to look:
![image](https://user-images.githubusercontent.com/6791648/73156386-f58f9800-40dd-11ea-89c9-399d8b8fcba1.png)

**Comment by aliiftikhar** [comment]
I believe this is fixed, and this issue can be closed, right?

<img width="1543" alt="Screen Shot 2020-09-02 at 20 38 51" src="https://user-images.githubusercontent.com/3383922/92028728-6fff5500-ed5c-11ea-9f0c-9f5ff1a6e871.png">
