### ISSUE TITLE
Add support in List View columns to display node name from a content picker

### ISSUE THREAD

**Issue by webtimisten** [umbraco/Umbraco-CMS#7518]
Use the Template option as Nested Content does it to get the node name from a content picker.

Right now it shows the value umb://document/... instead of the name from the picked node.

**Comment by skttl** [comment]
It's already in since 8.4 (#6597)

**Comment by nul800sebastiaan** [comment]
Yep, you can use templates as Søren pointed out! 👍

**Comment by webtimisten** [comment]
Cool! Thank you. Maybe the documentation should be updated about this, since I couldn't find anything, when I Googled my ass off to find anything about templates in List Views :-)
