### ISSUE TITLE
NetCore: Introduce Image Url Generator Abstractions

### ISSUE THREAD

**Issue by bergmania** [umbraco/Umbraco-CMS#7538]
### Background History
For the .NET Core transformation, we need to be able to abstraction the image URL generation, because ImageProcessor is not supported.

### The task
This task is about introducing an `IImageUrlGenerator ` and an `ImageProcessorImageUrlGenerator`.

The interface only requires a single method
```
string GetImageUrl(ImageUrlGenerationOptions options);
```
And `ImageUrlGenerationOptions` needs to have all the options used for image generation in Umbraco. Like:
```
int Width;
int Height;
AnimationProcessMode(Enum) animationProcessMode;
ImageCropMode CropMode
ImageCrop AnchorAnchor
...
```
The `GetImageUrl` implementation is not responsible of looking up information from a named crop. This look up needs to be done before calling `GetImageUrl`

The `ImageProcessorImageUrlGenerator` need to take the functionality from `ImageCropperTemplateExtensions.GetCropUrl` and `ImageCropperTemplateExtensions.GetCropUrl` should call the new service with the options.

It is important that it is easy/possible to replace the `ImageProcessorImageUrlGenerator` with a custom implementation of `ImageUrlGenerationOptions`.

We will need to get the `IImageUrlGenerator` from the `Current` service locator in Razor views.

Occurrences that needs to replace hardcoded url generation:

| File        |
| ------------- |
| UserExtensions.cs    | 
| ImageCropperValue.cs    | 
| ImagesController.cs    | 
| ImageCropperTest.cs    | 
| ImageCropperTemplateExtensions.cs    | 
| RichTextEditorPastedImages.cs    | 
| HtmlImageSourceParserTests.cs    | 
| Media.cshtml    | 

Even though this change is for the .NET Core transition, it should be a non-breaking change, that makes sense to implement on Umbraco 8 ([v8/dev)](https://github.com/umbraco/Umbraco-CMS/tree/v8/dev).

**Comment by benjaminc** [comment]
I'll take a stab at this
