### ISSUE TITLE
NetCore: Introduce API to generate image URLs for BackOffice

### ISSUE THREAD

**Issue by bergmania** [umbraco/Umbraco-CMS#7539]
### Background History
For the .NET Core transformation, we need to be able to abstract the image URL generation, because ImageProcessor is not supported in .NET Core.

### The task
This task is about introducing an `ImageUrlGenerationController` to generate URLs for images within the Umbraco back-office. The controller will extend the UmbracoAuthorizedJsonController class, and will implement a single method that should call `ImageCropperTemplateExtensions.GetCropUrl` to generate a URL given the arguments. At a minimum, the controller method should take as arguments the `width`, `height`, `mode`, and `animationProcessMode` arguments of the `GetCropUrl` method.

Even though this change is for the .NET Core transition, it should be a non-breaking change that makes sense to implement on Umbraco 8 ([v8/dev](https://github.com/umbraco/Umbraco-CMS/tree/v8/dev)).

**Comment by benjaminc** [comment]
This has been implemented in PR #7616
