### ISSUE TITLE
Start-node located inside another start-node, invalidates the upper-most start-node

### ISSUE THREAD

**Issue by nielslyngsoe** [umbraco/Umbraco-CMS#7545]
**What Happened?**
If a user has several start-nodes and one of the start-nodes is located inside (as a descendant of a start-node) then the most upper ones of these start-nodes are taken out of business.
This might seem like an odd situation, but it could happen if people move nodes around. Or if a user specifically needs a bit more access than the user-group of theirs have defined.

**What did you expect to happen?**
I expected to have access to all my start nodes.

Screenshots of the issue:

![image](https://user-images.githubusercontent.com/6791648/73535755-a2db1680-4424-11ea-9fe1-4942cd9ed640.png)

![image](https://user-images.githubusercontent.com/6791648/73535804-c2723f00-4424-11ea-9545-c4f56ed2dddc.png)

**Comment by Shazwazza** [comment]
This is a regression. All of this used to work and I was sure we had tests for this.

**Comment by nul800sebastiaan** [comment]
@Shazwazza I have tested this in each minor version between 8.0.0 and 8.6.0 and in none of those cases did this work. Nor does this work in 7.15 by the way

v8.0.0
![image](https://user-images.githubusercontent.com/304656/76220297-88603e00-6217-11ea-9552-4c54b12a2f6b.png)


v7.15.3
![image](https://user-images.githubusercontent.com/304656/76220314-8d24f200-6217-11ea-87eb-62aebbb698fe.png)

**Comment by UnsungHeros** [comment]
If one follows a _deny_ permission by default as opposed to a _grant_ permission by default, this behavior makes sense.  If one has access to the root, and a page under the root is specified, one would not want to open up permissions to say the 'second child' node by accident.  You should have to explicitly state give access to 'second child'.
