### ISSUE TITLE
Fix spelling Dermine -> Determine

### ISSUE THREAD

**Issue by robertjf** [umbraco/Umbraco-CMS#7548]
Found a couple of private methods with incorrect spelling of "Determine" in them.  Fixed in related pull request.

## Umbraco version

I am seeing this issue on Umbraco version: 8.5.3

Reproduction
------------

N/A

### Bug summary

N/A

**Comment by nul800sebastiaan** [comment]
FYI: there's absolutely no need to create in issue before you create a PR any more, but thanks anyway! ;-)

**Comment by nul800sebastiaan** [comment]
Fixed in https://github.com/umbraco/Umbraco-CMS/pull/7549 👍
