### ISSUE TITLE
Umbraco lack of Consistency for Camel/Pascal case in writing ID

### ISSUE THREAD

**Issue by bielu** [umbraco/Umbraco-CMS#7552]
When I was looking into code I could notice the same aliases could be written in a different way as for example:
 **Parent ID**
Examine alias:
`"parentID"`
In same time DB:
`"ParentId"`
And reading the whole subject about how should be ID used in camel/pascal case this is quite complicated:
https://softwareengineering.stackexchange.com/questions/186277/should-the-variable-be-named-id-or-id
But still, we should be consistent about using aliases everywhere, it means if we are using ID we should use 
`"ParentID"` and `"parentID"` 
or for Id:
`"ParentId"` and `"parentId"` 

That issue is occurring for all aliases with the acronym "ID".

Code Examples:
`[DataMember(Name = "parentId")]`
` new FieldDefinition("parentID", FieldDefinitionTypes.Integer),`
`if (entity.IsPropertyDirty("ParentId"))`

**Comment by markadrake** [comment]
I think some of the confusion comes from the English language, and well the rest may come from the varying standards in languages and frameworks. 

In writing, we should use capital letters. The term **ID** stands for _**identifier document**_ (or similar). The term _id_ is an abbreviation already for _idem_.

So what are the standards proposed by and followed for C#, .NET Framework, SQL, and don't forget JavaScript? Often it can depend on where the letters fall at. In Javascript, if the variable name is `id` then obviously, I would not capitalize it, nor camel case it, or anything - I'd allow it to stay lower case.

I'm with you @bielu, if it makes sense to update it for consistency while following the rules of syntax and language. If my opinion matters at all, in every case you made above, `ID` should be written as **ID**.

I often find myself wishing to ignore the [naming conventions](https://docs.microsoft.com/en-us/dotnet/standard/design-guidelines/capitalization-conventions) and want to capitalize other acronyms like `html` and `url` or `uri` and the such, but it's supposedly only for identifiers of 2 letters.

**Comment by nul800sebastiaan** [comment]
Welcome to the world of legacy code! 

Unfortunately, we have a long history of naming things and they aren't consistent at the moment. It's a good point to keep in mind for the [Unicore project](https://umbraco.com/blog/the-unicore-team/) if we can so I've sent this off to the Unicore team for their consideration. For the current version, we won't be making any changes since this has the great potential to breaking all kinds of integrations where people are counting on the current inconsistencies.

**Comment by bielu** [comment]
@nul800sebastiaan and in same time we have breaking changes like:
https://github.com/umbraco/Umbraco-CMS/issues/5947
https://github.com/umbraco/Umbraco-CMS/issues/7189
And I would probably put all three in the same bag, things which should be done long time ago :)

**Comment by nul800sebastiaan** [comment]
Yep. We try really hard not to make breaking changes but sometimes things slip through, oh the joys of legacy.

**Comment by bielu** [comment]
@nul800sebastiaan the main reason for that issue was I wanted to move all hardcoded string to be in constants and that lack of Consistency is generating issues as I can't just convert between Pascal and camel case depends on the case. :C

**Comment by nul800sebastiaan** [comment]
Yeah it could be fine to move stuff to constants, but can you try to describe what you would be using it for?

**Comment by bielu** [comment]
@nul800sebastiaan mostly to have all same hardcoded strings in one place, as for example hardcoded Examine Fields aliases are repeating in code few times and in case if it will change anywhere it will have to be changed in few places.

**Comment by nul800sebastiaan** [comment]
If they changed that would be bad! 

However, what are YOU personally going to use these constants for? I am happy for a safe refactoring, I'm just wondering who it's going to benefit versus what it will cost us in time and effort. :-)

**Comment by nul800sebastiaan** [comment]
By the way, I am not trying to be argumentative, just curious.

I think it would be wonderful to have small, incremental PRs moving hardcoded strings to constants, it will make it easier for everyone to refer to them. I hope that this would be the purpose for you too?

**Comment by bielu** [comment]
@nul800sebastiaan really often I am sometimes using an alias of fields in Lucene queries, it would be just nicer to use constants instead of string :) and from the perspective of maintaining it is better, as it will be less probably to break in case if anything change :)

**Comment by nul800sebastiaan** [comment]
Sounds good to me! I would encourage you to send small PRs with updates to move a certain area of hardcoded strings to a constants class. 
No need to create an issue for each PR, they can be pretty stand-alone. 
Large PRs with many changes are difficult to review and it's hard to see what is affected, so if you start small there's a much greater chance the review will be quick and painless.

Does that sound good to you?

**Comment by bielu** [comment]
@nul800sebastiaan yeah, sound good but not all strings could be moved as issues with Consistency 👎.
