### ISSUE TITLE
Cannot schedule publishing for content item varying by culture

### ISSUE THREAD

**Issue by andreasrangholm** [umbraco/Umbraco-CMS#7559]
Brief description:
Endpoint /umbraco/backoffice/UmbracoApi/Content/PostSave returns status code 404 upon clicking 'Schedule', after setting 'Publish'date for one, more or all language variants of a content item.

Response:
')]}',
{"Message":"No variants flagged for saving"}'

Umbraco version:
8.5.3

Reproduction:
1) Under 'Settings' section, set permission 'Allow varying by culture' to enabled/true for a document type.
2) Under 'Content' section, create content based on document type.
3) Select 'Schedule' and set scheduled publishing for one or more language variants (reproduced when setting only Publish or Publish and Unpublish date).
4) Click 'Schedule' button.

Specifics:
- Browser: Google Chrome Version 79.0.3945.130 and Mozilla Firefox Developer Version 73.0b12

Expected result:
Notification message with success message 'Content saved. [name(s)-of-language-variant(s)] saved' or similar.

Actual result:
5a) Notification message is shown with error message 'Request error: The URL returned a 404 (not found): /umbraco/backoffice/UmbracoApi/Content/PostSave
5b) Browser dev tools show response message: ')]}',
{"Message":"No variants flagged for saving"}'

Might be related to:
[Issue #4854 ](https://github.com/umbraco/Umbraco-CMS/issues/4854)

**Comment by nul800sebastiaan** [comment]
Hi @andreasrangholm and sorry for the late reply! This is something we're fixing in the soon upcoming 8.6.0 version: https://github.com/umbraco/Umbraco-CMS/issues/7452

Make sure to keep an eye on that issue as I think we will need to do a new release of 8.5 as well so you have a small new upgrade to do instead of a bigger one.

**Comment by KasperBHansenAtPentia** [comment]
Tested in U8.6.0RC - seems to work

**Comment by iPszota** [comment]
Hi!

Facing the same issue on 8.6.7.
Any thoughts on how to solve it, please?

Thanks, Istvan
