### ISSUE TITLE
Describe why there is no create options at the content root

### ISSUE THREAD

**Issue by nielslyngsoe** [umbraco/Umbraco-CMS#7571]
When a user opens the create dialog on the root of the tree, but doesn't have any DocumentTypes allowed for creation in the root, the user sees the following screen:

![image](https://user-images.githubusercontent.com/6791648/73746186-f2874e00-4754-11ea-9720-3f71d4a0acb5.png)

Instead, we should allow all Document Types to be created at root, and thereby list them in the dialog. Or mention that a Document Type should be allowed.

And if there are no Document Types in the solution, we should show a screen describing that and link to the Settings Section, potential a direct link to create a new Document Type.

Something similar to this dialog, this example is taken from the create dialog on a content-node:
![image](https://user-images.githubusercontent.com/6791648/73746210-fca94c80-4754-11ea-935f-d53403bc3758.png)

**Comment by kjac** [comment]
@nielslyngsoe this used to be the case. But if you have a look at #6580 you'll see why it isn't any longer 😀

Instead of listing all content types at root when none are configured, #6573 was introduced to aid newcomers in setting things up correctly.

**Comment by nielslyngsoe** [comment]
@kjac thanks for highlighting that. Well good perspectives, we just need to ensure that newcomers don't reach a dead-end.
I will be back with an updated issue! :-)

**Comment by kjac** [comment]
@nielslyngsoe turns out the changes added in #6573 to help newcomers didn't work at all 🙈 

#7635 fixes it 👍

**Comment by nul800sebastiaan** [comment]
Fixed in https://github.com/umbraco/Umbraco-CMS/pull/7635
