### ISSUE TITLE
Not able to make spaces in TinyMCE when grid layout is in "Distraction Free" mode.

### ISSUE THREAD

**Issue by rndfm** [umbraco/Umbraco-CMS#7572]
When i set the Grid Layout property editor to Distraction Free mode I'm not able to enter spaces in my rich texts. Space key is simply ignored.

I am seeing this issue on Umbraco version: 8.5.3

Reproduction
------------

Set up a data type to use the Grid Layout editor and use Distraction Free mode.
Use the datatype on a document type. 
Create new page with that document type.
Add a rich editor in the grid and try to enters some text that contains spaces.

**Comment by nul800sebastiaan** [comment]
Yep, I can reproduce this (and also in v8.4.0 so it seems to have broken around that time).

**Comment by nul800sebastiaan** [comment]
I just remembered this COULD be closely related to the following issue: https://github.com/umbraco/Umbraco-CMS/issues/6508

**Comment by nathanwoulfe** [comment]
@nul800sebastiaan it's a dependency issue - we include angular-aria 1.7.5, which had an issue with how it managed the spacebar press in contenteditable elements inside an element decorated with an ng-click directive (phew!). I think the original thinking there was that an editable element wouldn't be inside an interactive element, but that doesn't allow for overlays etc, like in the grid, hence the issue.

I've fixed it locally by bumping the dep from 1.7.5 to 1.7.9, and all is well. 

How do you manage changes to package.json? Just update and push or is the lock file needed too?

**Comment by nul800sebastiaan** [comment]
@nathanwoulfe wow! Who would have thought.. good digging, what a great find! 🌟

Usually I try to get the change in the lock file that I wanted in there, but nothing else. So just the version bump. But no big deal if you commit the whole thing, as long as the hashes don't change down to SHA1 instead of SHA265 👍
