### ISSUE TITLE
[v8] Bug. This document is published but its url cannot be routed

### ISSUE THREAD

**Issue by bv-it** [umbraco/Umbraco-CMS#7575]
Hello,
Umbraco 8.2.2. 
**1. This document is published but its url cannot be routed**
![1](https://user-images.githubusercontent.com/16698614/73750872-06d84480-476f-11ea-9eeb-ca29bb5be7df.png)

**2. Cache Reload and Rebuild**
![2](https://user-images.githubusercontent.com/16698614/73751043-54ed4800-476f-11ea-85f1-522fecf3eb42.png)

**3. Problem solved! (this error occurs once or twice a day)**
![3](https://user-images.githubusercontent.com/16698614/73751047-57e83880-476f-11ea-8e49-33888ff00b19.png)

**Comment by bv-it** [comment]
The error is similar to the following tasks (the error returned in Umbraco 8.2.2):
https://github.com/umbraco/Umbraco-CMS/issues/5121
https://github.com/umbraco/Umbraco-CMS/issues/5016

**Comment by nul800sebastiaan** [comment]
Hi @bv-it, that does not look so nice! 

Quick question: are you hosting your site on Azure or somewhere else?

We've been working on various locking issues for both the content cache and the database in the last few releases. I would encourage you to upgrade to the latest version (8.5.3) and try again.

If this is still an issue on version 8.5.3 then let us know so we can re-open the issue! 👍

**Comment by bv-it** [comment]
- We use SQL server for this site.
- Ok. We will update and let you know if the error persists.

**Comment by shearer3000** [comment]
hi bv-it - can i ask what you did to resolve this issue? thanks

**Comment by bv-it** [comment]
Hi shearer3000, we execute this code after the site is launched (or try updating Umbraco to the latest version)
           

                var payloads_Media = new[] { new MediaCacheRefresher.JsonPayload(0, TreeChangeTypes.RefreshAll) };
                Umbraco.Web.Composing.Current.DistributedCache.RefreshByPayload(MediaCacheRefresher.UniqueId, payloads_Media);


                var payloads_Content = new[] { new ContentCacheRefresher.JsonPayload(0, TreeChangeTypes.RefreshAll) };
                Umbraco.Web.Composing.Current.DistributedCache.RefreshByPayload(ContentCacheRefresher.UniqueId, payloads_Content);


                var payloads_Domain = new[] { new DomainCacheRefresher.JsonPayload(0, DomainChangeTypes.RefreshAll) };
                Umbraco.Web.Composing.Current.DistributedCache.RefreshByPayload(DomainCacheRefresher.UniqueId, payloads_Domain);

**Comment by NikRimington** [comment]
Hi, so I'm getting this error on an 8.6 site. Random pages are suddenly giving this error and it takes either a republish/reload of cache/restart of site to get them to come back. This site hasn't had any "schema" changes (e.g. no new doctypes, no changes to doctypes etc) for about 3 months and it's happened a fair few times now. 

Is there anything that can be done to try and identify what is going on that causes the issue? 

Could improved logging be added here: https://github.com/umbraco/Umbraco-CMS/blob/3bfd9b71e290354744d677440983ecd06c5c0788/src/Umbraco.Web/Routing/UrlProviderExtensions.cs#L175 so that something shows up in the logs to help with this problem as it would be good to understand why it happens. @nul800sebastiaan , would this be an acceptable PR if someone was to create it to add extra logging around this?

**Comment by nul800sebastiaan** [comment]
@NikRimington Anything that can help get to the bottom of this issue, give it the `Debug` or `Verbose` log levels where appropriate, that means people need to opt in to extra logging but it also doesn't pollute the logs for most people who don't seem to have this problem.

**Comment by bv-it** [comment]
8.6.3 + MS SQL - Error "This document is published but its url cannot be routed" (after each restart of the site)

**Comment by NikRimington** [comment]
@bv-it , do you have multiple root nodes in your site? We did, and the fix we've found was to ensure a domain name was assigned to the first root node.

**Comment by bv-it** [comment]
@NikRimington our site has one root node.

**Comment by sbosell** [comment]
I'm seeing this exact same issue on an 8.9.1 site with one root node. There are several forum posts with others having this issue.  This should be reopened.
