### ISSUE TITLE
TopoGraph error importing simple package

### ISSUE THREAD

**Issue by PezCo** [umbraco/Umbraco-CMS#7585]
Ive got a simple package that contains a few data types and document types in a folder structure. Im trying to import and getting a vague exception of System.Exception: Missing dependency.

## Umbraco version

I am seeing this issue on Umbraco version: 8.5.3

Reproduction
------------

### Bug summary
This bug happens from a clean install of umbraco

### Specifics
first few line of exception.

`at Umbraco.Core.Collections.TopoGraph`2.<FindDependencies>d__9.MoveNext() in d:\a\1\s\src\Umbraco.Core\Collections\TopoGraph.cs:line 129
   at Umbraco.Core.Collections.TopoGraph`2.Visit(TItem item, ISet`1 visited, TItem[] sorted, Int32& index, Int32 incr, Boolean throwOnCycle, Boolean throwOnMissing) in d:\a\1\s\src\Umbraco.Core\Collections\TopoGraph.cs:line 114
   at Umbraco.Core.Collections.TopoGraph`2.GetSortedItems(Boolean throwOnCycle, Boolean throwOnMissing, Boolean reverse) in d:\a\1\s\src\Umbraco.Core\Collections\TopoGraph.cs:line 86
   at Umbraco.Core.Packaging.PackageDataInstallation.ImportDocumentTypes(IReadOnlyCollection`1 unsortedDocumentTypes, Boolean importStructure, Int32 userId) in d:\a\1\s\src\Umbraco.Core\Packaging\PackageDataInstallation.cs:line 458`

### Steps to reproduce

Install attached package (there is nothing archetype related here its just the name. its for a project where im converting from archetype to nested content)
[ArchetypeUpgrade_1.0.0.zip](https://github.com/umbraco/Umbraco-CMS/files/4160523/ArchetypeUpgrade_1.0.0.zip)

### Expected result

Package install succefully

### Actual result

Get error. Umbraco lists package as installed but nothing has changed.

**Comment by bielu** [comment]
@PezCo Actually Would be nice to have source code to see what is happening in your package, as I could see few scenarios why it is failing. :)

**Comment by PezCo** [comment]
Yep nothing too it a few data types and a few doc types no code

**Comment by PezCo** [comment]
@bielu are you able to confirm if you was able to repeat the error?

**Comment by bielu** [comment]
@PezCo I will look into that today as I have feeling it is a problem with content dependency resolving.

**Comment by bielu** [comment]
@PezCo I check package, I was able to reproduce and I could tell, it is missing Compositions:

          <Composition>meta</Composition>
          <Composition>sharedContent</Composition>
I am going to send PR which will add more description to the issue, instead of showing :
 System.Exception: Missing dependency.
It is going to show: 
 Missing dependency for type Node`2, with key meta

**Comment by PezCo** [comment]
Ah right yes an oversight by me. Thanks
But yes an updated error message is needed or maybe even don't allow the package to be made in the first place if its not going to be valid?

**Comment by bielu** [comment]
@PezCo yeah probably it should check dependencies also in a time of the creation of package, but it is more Umbraco HQ thing to discuss @nul800sebastiaan, as it changes how Package System would work.

**Comment by nul800sebastiaan** [comment]
Great to see you two worked it out! I like that a better error is thrown. The Package Team would probably love to change how the packager works in the future so that it catches these kinds of things before you try to do an install, I sent them a link to this issue for their consideration!

**Comment by bielu** [comment]
@nul800sebastiaan I still think it should be open, as PR is not solving fully issue. Umbraco Package Creator allowed for creating that package, I think it should be made also change validation of package on creation.

**Comment by nul800sebastiaan** [comment]
We don't need to solve the whole thing right now, if the Package Team is going to overhaul the package builder soon then we don't need to put in the time to do all of the validation (code which will then need to be maintained). 
So please have some patience for them to get back to this.

**Comment by poornimanayar** [comment]
PR in #7591
