### ISSUE TITLE
Recycle bin removing content on the website

### ISSUE THREAD

**Issue by patrickdemooij9** [umbraco/Umbraco-CMS#7590]
We currently have a multilanguage website that has a problem with the recycle bin. If I click on the recycle bin, it will go to the following url: /umbraco#/content/content/recyclebin?mculture=en-GB and show all the current items in the recycle bin. However if I try to go to /umbraco#/content/content/recyclebin, it lists the items in my root.
![image](https://user-images.githubusercontent.com/11466511/73920995-ce4b7e80-48c6-11ea-81e0-6e83978691a9.png)

And when I now delete something from the recycle bin, it will delete it from the content tree and remove it entirely from Umbraco. Meaning I cannot recover it anymore from the actual recycle bin.

I am currently using Umbraco version 8.4.1 and also encountered the same problem on Umbraco 8.5.2

The problem occurs because it uses GetAllowedChildren?contentId=-1 & GetChildren?id=-1, instead of using the actual recycle bin ID.

It also seems like this problem doesn't occur on a single language website.

---
_This item has been added to our backlog [AB#4955](https://dev.azure.com/umbraco/243e7927-03b2-44e2-908f-d4ac7ea5daaa/_workitems/edit/4955)_

**Comment by nul800sebastiaan** [comment]
Yikes, that sounds nasty! We'll have to reproduce and see what is going on!

**Comment by nul800sebastiaan** [comment]
This problem has been reproduced and I've added it to the list of things to look at in our next sprint starting Monday. Thanks for reporting!

**Comment by stevemegson** [comment]
It looks like the node ID is being lost before the list view reads it, so it ends up defaulting to ID -1.

- ContentRecycleBinController sets `$routeParams.id = "-20";`
- NavigationController.initNav sees that there are multiple languages configured but no`mculture` query parameter, so it grabs the default culture and adds it to the query.
- ListViewController.initView does `var id = $routeParams.id`, but this is now undefined.

On a single language site the second step doesn't happen, so `$routeParams.id` is still defined.

**Comment by kjac** [comment]
Uh ouh. I'll dig into this asap.

**Comment by kjac** [comment]
PR in #7654
