### ISSUE TITLE
Simple search - difference between two search boxes

### ISSUE THREAD

**Issue by PvanGeffen** [umbraco/Umbraco-CMS#7597]
The minimum amount of characters is different in both search boxes

----------

Hi,

We've got 2 search boxes on a website: One that searches the entire site and one that searches a particular group (knowledge base). They are basicly a copy of eachother.

Now we've noticed if you search a three-letter word in the entire site it works perfect. If we do this in the other one there's no result. So it looks like it ignores words less then four characters.

Is there someone who is familiar with this issue?

The search is based on [this example](https://our.umbraco.com/forum/umbraco-8/96004-simple-search-in-v8)

If there's any code requested, just hit me up!

## Umbraco version

I am seeing this issue on Umbraco version: 8.2.1

**Comment by nul800sebastiaan** [comment]
Hi there - this sounds like an excellent question for the forums where our friendly community can help you find the best solution for your requirements. 
Make sure to head on over to https://our.umbraco.com and ask follow up questions there! 👍

**Comment by PvanGeffen** [comment]
> Hi there - this sounds like an excellent question for the forums where our friendly community can help you find the best solution for your requirements.
> Make sure to head on over to https://our.umbraco.com and ask follow up questions there! 👍

I allready posted a question overthere yesterday. But thought give it a shot overhere

**Comment by nul800sebastiaan** [comment]
Sure thing! The issue tracker here is for bugs and feature requests for the Umbraco core source code, unfortunately we can't help you with your custom implementations of Umbraco.
