### ISSUE TITLE
Improve save dialog UX-flow

### ISSUE THREAD

**Issue by nielslyngsoe** [umbraco/Umbraco-CMS#7610]
I would like to optimize the save dialog flow.
The proposal is to hide the Unmodified variants and change the text a little.
As well I would like not to see the save-dialog if there is only one modified variant, in this scenario, the save action should be performed directly.

Today:
![image](https://user-images.githubusercontent.com/6791648/74028160-feb81900-49a9-11ea-859d-cca681050c44.png)

Proposal:
![image](https://user-images.githubusercontent.com/6791648/74028541-ded52500-49aa-11ea-9a9e-2ab42b7b2a38.png)

Similar proposal regarding the Save & Publish dialog: https://github.com/umbraco/Umbraco-CMS/issues/7611

**Comment by PerplexDaniel** [comment]
Yes, in multi-lingual sites with separate content trees per language you would get this pop-up all the time where you only ever want to save/publish a single language. Your proposed fix would solve this neatly.

**Comment by nathanwoulfe** [comment]
Awesome change. I'm only ever working with a single language, other than testing package stuff, but just in that context the popup can get a bit annoying. UI should stay out of the way as much as possible.

**Comment by nielslyngsoe** [comment]
Thanks for your inputs.

This change will come to life as part of the implementation of Segment Variants.

**Comment by nielslyngsoe** [comment]
Fixed https://github.com/umbraco/Umbraco-CMS/pull/7499
