### ISSUE TITLE
One picker to rule them all

### ISSUE THREAD

**Issue by mattbrailsford** [umbraco/Umbraco-CMS#7636]
Throughout the code base there are quite a few different pickers, and many either duplicate functionality or do things differently, making some pickers work one way, and others another.

I think it would be ideal if we had a single picker interface that is capable of being configured for multiple different data sources and that can be configured to display items in different way (providing custom item views) such that only one picker codebase is required to be maintained and ensures consistency across all picker interfaces.

**Comment by bjarnef** [comment]
We should also consider which approach to use to configurate the picker as single or multi picker. For example media picker has a "Multiple" boolean property, while multi url picker and MNTP have "Minimum" and "Maximum" properties, where the latter ones are multi picker if maximum is set to 1.

The "Minimum" and "Maximum" properties make it a bit more flexible, e.g. to have a media picker where it is possible to pick more than one images (but not unlimited), for example 5 or 10 images.

**Comment by nul800sebastiaan** [comment]
Thanks @mattbrailsford - this has been discussed before and is currently logged as a future idea. There's a lot of questions around this first but feel free to discuss on the existing issue for that. https://github.com/umbraco/Umbraco-CMS/issues/6181
