### ISSUE TITLE
Umbraco starter kit crashes

### ISSUE THREAD

**Issue by bjornnorlen** [umbraco/Umbraco-CMS#7638]
When visiting the page "Todo list for starter kit" in the Umbraco starter kit template the page crashes.  

## Umbraco version

I am seeing this issue on Umbraco version: 8.5.3

Reproduction
------------

### Specifics
Umbraco 8.5.3
Checked in Chrome and Firefox

### Steps to reproduce
- Install the latest version of Umbraco
- Visit the page localhost:XXXXX/about-us/todo-list-for-the-starter-kit/
- Visual Studio gets in break mode on the file Views/Partials/Grid/Bootstrap3-Fluid.cshtml
- When continuing, the page should give a YSOD

![Img1](https://user-images.githubusercontent.com/19406378/74238049-38a05c80-4cd5-11ea-9516-6d62ff637ea1.JPG)

### Expected result
The page for "Todo list for the starter kit"
 would be displayed.

### Actual result
A yellow screen of death is viewed stating that "Umbraco.Web.PublishedModels.ContentPage' does not contain a definition for 'sections'"

**Comment by nul800sebastiaan** [comment]
Hey there @bjornnorlen - that's annoying! 

Luckily it's not the experience most users have. I just had a look and can't reproduce the problem. 

This sounds like an excellent question for the forums where our friendly community can help you find the best solution for your requirements. 
Make sure to head on over to https://our.umbraco.com and ask follow up questions there! 👍
