### ISSUE TITLE
Multi node tree picker xpath query doesn't work for other cultures

### ISSUE THREAD

**Issue by PullensDennis** [umbraco/Umbraco-CMS#7657]
When adding a node using the MultiNodeTreePicker (MNTP) I am not starting on the correct node when using xpath on languages other than English (the default).

## Umbraco version

I've tested this in 8.2.2 and 8.5.3 (current latest stable)

Reproduction
------------

- Create two homepages, first one being the default language and the other one any other language
- Create a MNTP with a starting node using xpath. In both cases I've used something similar to "$site/settings/documents"
- Make sure you've got some doctype structure that leads to the path above
- When creating content for the default language, your starting node will be shown correctly
- When creating the same content in the other language your starting node won't show, and instead you'll be directed to the root of the tree

### Bug summary

When adding a node using the MultiNodeTreePicker (MNTP) I am not starting on the correct node when using languages other than English (the default).

### Specifics

I notice that in the contentPickerController the entityResource.getByQuery($scope.model.config.startNode.query, rootId, "Document") method returns the correct value for the default language but null for the other language. When changing the xpath query to "$site" I get the correct node for both languages, but "$site/settings" already returns null for the different language.

**Comment by nul800sebastiaan** [comment]
Thanks @PullensDennis! Yes, we're aware that MNTP currently completely disregards any multilingual setup. We're tracking this issue over here and there's a PR ready for it: https://github.com/umbraco/Umbraco-CMS/issues/7313

**Comment by PullensDennis** [comment]
My apologies @nul800sebastiaan. I saw that issue but somehow thought it was closed. My bad!

**Comment by nul800sebastiaan** [comment]
No problem at all! 👍
