### ISSUE TITLE
DB Error when UPDATING 7.14.0 to 8.2.0

### ISSUE THREAD

**Issue by VelizarT** [umbraco/Umbraco-CMS#7663]
Hi guys,

I'm trying to update from version 7.14.0 to 8.2.0 but the update fails with the fallowing error: ERROR: The database configuration failed with the following message: Cannot resolve collation conflict between "Latin1_General_CI_AS" and "SQL_Latin1_General_CP1_CI_AS" in CASE operator occurring in SELECT statement column 35.

Does anyone know what might be causing this?

**Comment by nul800sebastiaan** [comment]
Yes, I know that @stevemegson has a way to update the database, maybe even a SQL script, I am not sure, Steve?

Please note: you will likely run into more problems when migrating your database from v7 to v8, the process is not perfect yet but we're slowly working on making it better. There's a list of open issues that we still want to work on fixing: https://github.com/umbraco/Umbraco-CMS/labels/category%2Fcontent-migration

**Comment by nul800sebastiaan** [comment]
Ah I see that Steve has actually made a few health checks for this! Make sure to install this in your 7.14.0 project to do some fixes before trying to do the migration again, looks like the collation issue is covered as well: https://our.umbraco.com/packages/developer-tools/pre-migration-health-checks/

**Comment by stevemegson** [comment]
The health checks will warn that there are multiple collations in use, but I haven't come up with an automated fix yet.

I believe that that error message happens when the collation of the `umbracoNode.path` column doesn't match the database's default collation. We want to be able to do `concat(umbracoNode.path, ',%')`, and the literal `',%'` is treated as having the default collation.

**Comment by VelizarT** [comment]
It was indeed a collation issue,which was due to differences in dev/prod environments. Thank you for your help!!

**Comment by nul800sebastiaan** [comment]
Thanks for letting us know that this is fixed for now. I'll close this for now since we can't really make a good automated fix for it.

**Comment by mkyukov** [comment]
@VelizarT which column had the wrong collation? I am experiencing the same issue and trying to figure out which column collation I need to update.

**Comment by VelizarT** [comment]
@mkyukov I just made sure that the collation for the entire db was the right one.

**Comment by mkyukov** [comment]
@VelizarT it did! I changed the collation to be Danish_Norwegian_CI_AS and the migration succeeded.

**Comment by umbracocommunity** [comment]
This issue has been mentioned on **Umbraco community forum**. There might be relevant details there:

https://forum.umbraco.com/t/is-umbraco-17-supports-arabic-sql-collation-arabic-100-ci-ai/8411/2
