### ISSUE TITLE
Member Properties - Nested, multiple select, forloop errors

### ISSUE THREAD

**Issue by LTorson** [umbraco/Umbraco-CMS#7665]
Listing member properties that you need to forloop through throws errors. 
Object Null - on Nested content, multiple dropdowns, multi URL picker, multi-tree picker etc. 

member property also only has an EditedValue and not a PublishedValue. 

## Umbraco version

I am seeing this issue on Umbraco version: 8.5.3

Reproduction
------------
```
var memberService = Services.MemberService;
var members = memberService.GetAllMembers();
@foreach (var member in members)
{
     {
         var prof = member.GetValue("memberProfession"); // Returns a singular string value
         @prof 
     }
}
```

OR
```
{
       var prof = member.GetValue<IEnumerable<IPublishedElement>>("memberProfession"); // Nested or IPublishedContent for anything else
      
       foreach(var item in prof) {
          @item 
       }
}
```

OR
```
{
       var prof = member.GetValue<IEnumerable<IPublishedElement>>("memberProfession").toList(); // Nested or IPublishedContent for anything else
      
      foreach(var item in prof) {
          @item.Value("fieldValue")
      }
}
```

### Bug summary

displaying all members, then trying to list out member property values, errors on anything where there are multiple values.

### Specifics

Object reference not set to an instance of an object.
Description: An unhandled exception occurred during the execution of the current web request. Please review the stack trace for more information about the error and where it originated in the code.

Exception Details: System.NullReferenceException: Object reference not set to an instance of an object.
### Actual result

Object Error Screen

OR

Value cannot be null.
Parameter name: source

**Comment by nul800sebastiaan** [comment]
Ooh.. I don't know what the error is about but this is absolutely not the way to query all members, you're going straight to the database and this is a very heavy operation. 

I don't know your use case but to read member properties please don't use the Services APIs, that's not what they're there for! 

There's some more info in this documentation about using the Services for querying and why that's not a good idea: https://our.umbraco.com/documentation/reference/common-pitfalls/#using-the-services-layer-in-your-views

So I've whipped up a bit of an example, it's a bit unfortunate that you can't get all members from `Umbraco.Members` but you can from the Examine index and that's fast and cached:

So this is just a quick example in a View file, as you can see members are returned from the Member cache as IPublishedContent, so you can query Nested Content (and everything else) just like content.

```
@{
   
    var members = new List<IPublishedContent>();
    if (ExamineManager.Instance.TryGetIndex("MembersIndex", out var index))
    {
        var searcher = index.GetSearcher();
        var results = searcher.CreateQuery(IndexTypes.Member).All().Execute();
        members.AddRange(results.Select(result => Umbraco.Member(result.Id)));
    }
}

<h1>Members (@members.Count())</h1>
@foreach (var mem in members)
{
    var nester = mem.Value<IEnumerable<IPublishedElement>>("nester");

    if (nester != null)
    {
        <div>
            @foreach (var item in nester)
            {
                <div class="product-advantage">
                    <h4>@item.GetProperty("featureName").Value()</h4>
                    <h5>@item.GetProperty("featureDetails").Value()</h5>
                </div>
            }

        </div>
    }
}
```

I'm going to close this issue as this is not a help forum, so if you need more help, make sure to head on over to our forums at https://our.umbraco.com where our friendly community can help you further along!
