### ISSUE TITLE
File tree is not able to navigate folders

### ISSUE THREAD

**Issue by nielslyngsoe** [umbraco/Umbraco-CMS#7666]
The Application tree with the alias "files", does not work correctly.
Seems like the tree file system root is wrong, because if I change the tree to use another folder, like \~/umbraco/ then it works. Therefore I concluded that there is something wrong with "~/".

---
_This item has been added to our backlog [AB#5112](https://dev.azure.com/umbraco/243e7927-03b2-44e2-908f-d4ac7ea5daaa/_workitems/edit/5112)_

**Comment by kjac** [comment]
@nielslyngsoe what exactly seems to be wrong with it? From the package creation view I'm perfectly able to use it:

![image](https://user-images.githubusercontent.com/7405322/74756202-7e7c9800-5274-11ea-8df7-bf7f154ee49f.png)

**Comment by nielslyngsoe** [comment]
This seems to only be a problem if the server is running from a MacOS file system.
