### ISSUE TITLE
Add GetCropUrl in IMediaUrlProvider (or IMediaCropUrlProvider)

### ISSUE THREAD

**Issue by olibos** [umbraco/Umbraco-CMS#7671]
Hello,

I love the new MediaUrlProvider from #5282.
But I think we can go even further, if we take the sample of CdnMediaUrlProvider.
Umbraco could generate URLs for CDN with Image Processing capabilities like  https://www.imgix.com/ and bypass ImageProcessor.

Another use case could be a StaticMediaUrlProvider which generate static cropped files in the same media folder.

Sample:
---------
media.Url == "/media/xxxxxx/media.jpg"
media.GetCropUrl(cropAlias: "thumb")  == "/media/xxxxxx/media.thumb.jpg"
media.GetCropUrl(width: 100, height: 100) == "/media/xxxxxx/media.100x100.jpg"

The advantage of this approach is the same of IMediaUrlProvider, we set this provider once and all URLs of the project are changed we don't have to change all media.GetCropUrl() to media.GetStaticCropUrl()

What do you think?

**Comment by nul800sebastiaan** [comment]
Hey @olibos - the image URL generator has been abstracted for the upcoming v8.7.0, I believe that will help you achieve exactly what you wish! See this PR: https://github.com/umbraco/Umbraco-CMS/pull/7616
