### ISSUE TITLE
V8.6.0-RC - Unable to add multiple nested content items

### ISSUE THREAD

**Issue by NikRimington** [umbraco/Umbraco-CMS#7698]
Clicking `Add Content'` on nested content items only works the first time, you then have to save the page and refresh the browser to add another one.

## How to reproduce

1. install 8.6.0 RC with starter kit
2. goto a product page
3. try and add multiple features by clicking on `add content` (note: using Chrome latest)

## What is expected

Multiple items would be added

## What happens?

Only the first click adds an item, after that nothing happens.

---
_This item has been added to our backlog [AB#5252](https://dev.azure.com/umbraco/243e7927-03b2-44e2-908f-d4ac7ea5daaa/_workitems/edit/5252)_

**Comment by NikRimington** [comment]
Further details:

I believe this check is failing as stepping through the JS it hits the return line. 

```
if (vm.overlayMenu || vm.nodes.length >= vm.maxItems) {
                    return;
                }
```

Theory: vm.overlayMenu is meant to be set to null but for some reason it doesn't. 

Not tested: If this is only a problem for Nested Content where it only has a single available type, as the overly never shows here and as a result close event/method is never fired to clear it.

**Comment by nul800sebastiaan** [comment]
Yikes, yep I can reproduce this, we'll get it fixed, thanks very much for reporting!

**Comment by kjac** [comment]
I think I already fixed this .. lemme find a PR 😛

**Comment by kjac** [comment]
Ah yes... https://github.com/umbraco/Umbraco-CMS/pull/7630
