### ISSUE TITLE
[8.6RC] Can't add content to NC after copying one of the items

### ISSUE THREAD

**Issue by skttl** [umbraco/Umbraco-CMS#7714]
When copying a nested content item, the Add content button stops working. It throws no errors in the console, it just doesn't react at all.

To reproduce:
Click the copy icon of the NC item
![image](https://user-images.githubusercontent.com/3726467/75254221-55ae5280-57e0-11ea-9216-ce5c5beaec05.png)

Click Add content
![image](https://user-images.githubusercontent.com/3726467/75254253-6232ab00-57e0-11ea-8344-0564b81abf07.png)

Nothing happens.

Other Nested Content properties on the page still works.

Reload the page, and the Add content button works again, offering you the copied item.
![image](https://user-images.githubusercontent.com/3726467/75254347-87bfb480-57e0-11ea-96b3-3b736204e7ac.png)

**Comment by nul800sebastiaan** [comment]
Thanks, this duplicates https://github.com/umbraco/Umbraco-CMS/issues/7698 👍
