### ISSUE TITLE
[8.6RC] Opening media item in infinite editor saves the content

### ISSUE THREAD

**Issue by skttl** [umbraco/Umbraco-CMS#7715]
![Ii2LQAYuKb](https://user-images.githubusercontent.com/3726467/75254620-e8e78800-57e0-11ea-9a19-9f164a38f527.gif)

When opening a picked media item in an infinite editor, the current node gets saved. This could be quite annoying, and it didn't used to do this.

**Comment by nul800sebastiaan** [comment]
Hmm, looks familiar to https://github.com/umbraco/Umbraco-CMS/pull/7257 - will need to check if there's a `<button>` without `type="button"` attribute.

**Comment by nul800sebastiaan** [comment]
Yep, was fixed in #7643 - have cherrypicked for v8.6! https://github.com/umbraco/Umbraco-CMS/commit/5a35ba60c1fa3506eb6aa6467de1be846df5b6ca
