### ISSUE TITLE
After renaming umbraco folder it comes back every time I compile

### ISSUE THREAD

**Issue by sixeyes** [umbraco/Umbraco-CMS#7732]
A brief description of the issue goes here.

After renaming my umbraco folder (e.g. MyBackOffice), every time I rebuild the solution in Visual Studio 19 (v16.4.5) the umbraco folder reappears.

## Umbraco version 

I am seeing this issue on Umbraco version: 8.5.3

Reproduction
------------

I have followed the instructions here:

https://our.umbraco.org/documentation/getting-started/setup/install/install-umbraco-with-nuget

to create my Visual Studio solution. After creating my site I renamed the umbraco folder and changed the following settings:

	<add key="Umbraco.Core.ReservedUrls" value="~/MyBackOffice" />
        <add key="Umbraco.Core.ReservedPaths" value="~/MyBackOffice" />
        <add key="Umbraco.Core.Path" value="~/MyBackOffice" />
        <add key="umbracoPath" value="~/MyBackOffice" />

Every time I build the solution in Visual Studio the unwanted umbraco folder keeps being created.

### Bug summary

    * The umbraco folder keeps being created on each build from within Visual Studio

### Specifics

    * No URL is relevant
    * Umbraco v8.5.3 (NuGet)
    * Not using a browser

### Steps to reproduce

     * See reproduction above.

### Expected result

    * Once I'd renamed the back office URL I was not expecting the original folder to reappear each time I build the solution in Visual Studio

### Actual result

    * After renaming the back office folder, each build from Visual Studio recreates the original umbraco folder.

**Comment by sixeyes** [comment]
Just now I had an idea that I could work around this issue by adding a post build step to delete the folder but it didn't work.

The umbraco folder is being created AFTER the post build step. So the post build step deletes the folder but it's recreated immediately after.

Turning on diagnostic logging in Visual Studio revealed that the following build target is being run from the NuGet package:

UmbracoCms.8.5.3\build\UmbracoCms.targets:

    <?xml version="1.0" encoding="utf-8"?>
    <Project ToolsVersion="4.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
      <Target Name="CopyUmbracoFilesToWebRootForDeploy" AfterTargets="CopyAllFilesToSingleFolderForMsdeploy">
        <PropertyGroup>
          <UmbracoFilesFolder>$(MSBuildThisFileDirectory)..\UmbracoFiles\</UmbracoFilesFolder>
        </PropertyGroup>
        <ItemGroup>
          <UmbracoFiles Include="$(UmbracoFilesFolder)**\*" />
        </ItemGroup>
        <Copy SourceFiles="%(UmbracoFiles.FullPath)" DestinationFiles="$(_PackageTempDir)\%(RecursiveDir)%(Filename)%(Extension)" Condition="!Exists('%(RecursiveDir)%(Filename)%(Extension)')" />
      </Target>  
      <Target Name="CopyUmbracoFilesToWebRoot" BeforeTargets="AfterBuild">
        
        
        <PropertyGroup>
          <UmbracoFilesFolder>$(MSBuildThisFileDirectory)..\UmbracoFiles\</UmbracoFilesFolder>
        </PropertyGroup>
        <ItemGroup>
          <UmbracoFiles Include="$(UmbracoFilesFolder)**\*" />
        </ItemGroup>
        <Copy SourceFiles="%(UmbracoFiles.FullPath)" DestinationFiles="%(RecursiveDir)%(Filename)%(Extension)" Condition="!Exists('%(RecursiveDir)%(Filename)%(Extension)')" />
      </Target>
      <Target Name="AddUmbracoFilesToOutput">
        
        <ItemGroup>
          <CustomFilesToInclude Include=".\App_Browsers\**\*">
            <Dir>App_Browsers</Dir>
          </CustomFilesToInclude>
          <CustomFilesToInclude Include=".\App_Code\**\*">
            <Dir>App_Code</Dir>
          </CustomFilesToInclude>
          <CustomFilesToInclude Include=".\App_Plugins\**\*">
            <Dir>App_Plugins</Dir>
          </CustomFilesToInclude>
          <CustomFilesToInclude Include=".\bin\amd64\**\*">
            <Dir>bin\amd64</Dir>
          </CustomFilesToInclude>
          <CustomFilesToInclude Include=".\bin\x86\**\*">
            <Dir>bin\x86</Dir>
          </CustomFilesToInclude>
          <CustomFilesToInclude Include=".\Config\Splashes\**\*">
            <Dir>Config\Splashes</Dir>
          </CustomFilesToInclude>
          <CustomFilesToInclude Include=".\data\**\*">
            <Dir>data</Dir>
          </CustomFilesToInclude>
          <CustomFilesToInclude Include=".\umbraco\**\*">
            <Dir>umbraco</Dir>
          </CustomFilesToInclude>
          <CustomFilesToInclude Include=".\Global.asax">
            <Dir>.</Dir>
          </CustomFilesToInclude>
          <FilesForPackagingFromProject Include="@(CustomFilesToInclude)">
            <DestinationRelativePath>%(CustomFilesToInclude.Dir)\%(RecursiveDir)%(Filename)%(Extension)</DestinationRelativePath>
          </FilesForPackagingFromProject>
        </ItemGroup>
      </Target>
    </Project>

I looked at the content but since it's in a NuGet package I can't really edit it. The umbraco folder appears to be hard coded.

Could someone with more knowledge advise on how to fix it?

I'm assuming this build target is designed to ensure the back office files are correct. It would be brilliant if this could be redirected to the MyBackOffice folder instead.

**Comment by nul800sebastiaan** [comment]
I can reproduce this when using rebuild (which you really hardly ever should have to use, but that's a different discussion).

I could have sworn that the targets file should only kick in for deploying the site, that's what it's there for as far as I know. 

I don't think can make that location depend on the appSetting in web.config though. Ideas welcome! 

For now I'd say: exclude the `~/umbraco` folder from your project in VS and delete it from source control + add an ignore for your source control system to not pick it up again. The folder will still be there on your local machine but it's not doing anything.

**Comment by nul800sebastiaan** [comment]
Yep.. so the long explanation of why this target exists is here: https://issues.umbraco.org/issue/U4-6171

If there's a very clever workaround for your scenario where you're moving the Umbraco folder then I'm all ears but for now I don't want to mess with this setup that has worked well for people for many years. I think the proposed workaround while not elegant will work. 

I'll close this for now but if you have a dead simple fix for this then we'd be happy to consider it!

**Comment by sixeyes** [comment]
Thanks for looking into this. I've had a look this morning and I can't see how to fix it either. For now I've just commented out the Import line in my csproj so it doesn't get created.
