### ISSUE TITLE
Nested Content Lists Umbraco 8.6.0-rc

### ISSUE THREAD

**Issue by danielibanez** [umbraco/Umbraco-CMS#7733]
In Umbraco 8.6.0 a document type with nested content will only allow one item to be entered. Even when the nested content has blank for min and max. If you navigate away from the content section and back you will be able to add one more item.

## Umbraco version

I am seeing this issue on Umbraco version: 8.6.0-rc

Reproduction
------------

Create a document type with nested content. Leave min and max items in the nested content editor settings as blank. Create a content node with that document type. Add an item. Click "Add content." Unresponsive. Navigate away from the content section. Navigate back to the content section and add another nested content item.

### Bug summary

Cannot add content to lists of nested content without refreshing the content section.

### Specifics

Chrome: Version 80.0.3987.87

Firefox Developer: 74.0b8

### Expected result

This also affected previously created nested content lists (8.4.1).

**Comment by nul800sebastiaan** [comment]
Thanks for reporting! This is fixed and will be working in the final release: https://github.com/umbraco/Umbraco-CMS/issues/7714
