### ISSUE TITLE
Sensitive data not saving

### ISSUE THREAD

**Issue by GeorgePhillipson** [umbraco/Umbraco-CMS#7736]
Ticking 'Is Sensitive Data' does not save in Members

## Umbraco version

I am seeing this issue on Umbraco version: 8.5.2 and 8.5.4

Reproduction
------------

If you're filing a bug, please describe how to reproduce it. Include as much
relevant information as possible, such as:

### Bug summary

Add Custom property to Members as textstring and click 'Is Sensitive Data', click submit and save, TextString does not display 'Sensitive data' and checkbox is not saved as ticked 

### Specifics
Umbarco 8.5.2 and 8.5.4 
All browers
![SData](https://user-images.githubusercontent.com/9945386/75550357-a8c71600-5a29-11ea-9eec-fd819eb1ceaa.png)

### Steps to reproduce
Add Custom property to Members as textstring and click 'Is Sensitive Data', click submit and save, TextString does not display 'Sensitive data' and checkbox is not saved as ticked 

### Expected result

Sensitive data to be saved to textstring

### Actual result

Sensitive data NOT saved to textstring

**Comment by kjac** [comment]
Hi @GeorgePhillipson, thank you for taking the time to report this 👍 

This was fixed in #7273 and the fix is slated for 8.6 😄 

_Cross-linking this with #7270 as a duplicate._
