### ISSUE TITLE
[8.6RC] Uploaded images by the RTE Media Picker appear only after publishing content

### ISSUE THREAD

**Issue by saifobeidat** [umbraco/Umbraco-CMS#7739]
If you try to upload images from your PC directly by media picker in the RTE, they wouldn't appear in the RTE box until you save or publish the node.

Note that if you pick images from your current gallery, they would appear.

## Umbraco version

I am seeing this issue on Umbraco version: 8.6RC

### Specifics
Fresh Umbraco 8.6 RC installation

### Steps to reproduce
1- Create RTE property in any existing node
2- Upload images directly form your PC
3- Click Save or Save & Publish to be able to see the uploaded images in the RTE box

![2020-02-29_12-43-08](https://user-images.githubusercontent.com/24841143/75606009-4a656a80-5af1-11ea-837c-405428ba0d03.gif)

### Expected result
I expect to see the uploaded images in the RTE box

### Actual result
Uploaded images didn't appear

---
_This item has been added to our backlog [AB#5516](https://dev.azure.com/umbraco/243e7927-03b2-44e2-908f-d4ac7ea5daaa/_workitems/edit/5516)_

**Comment by kjac** [comment]
@saifobeidat hmmm I recall having fixed something along those lines at some point 🤔 and I don't see this bug in the latest `v8/contrib`. 

The media picker should display a new dialog subsequent to picking the uploaded image, but in your GIF it does not - it just closes. Are there any JS errors in the console?

**Comment by nul800sebastiaan** [comment]
I can reproduce, will have a look at the history of `v8/contrib` - the image is selected after upload, but it doesn't "actually" seem selected.

**Comment by nul800sebastiaan** [comment]
Looks like this would've fixed it, but it's not working any more: https://github.com/umbraco/Umbraco-CMS/pull/6995

**Comment by saifobeidat** [comment]
@nul800sebastiaan I believe it wasn't working even before, as it was stated in [Musab's comment](https://github.com/umbraco/Umbraco-CMS/issues/6844#issuecomment-566997506)

**Comment by kjac** [comment]
For the life of me I still can't reproduce this in `v8/contrib`. Is anyone seeing any console errors?

**Comment by saifobeidat** [comment]
@kjac yes there is an error appears on the console :

> http://localhost:64649/nothing.jpg 404 (Not Found)

it appears when I click "select" button, and appears again when I publish the node

**Comment by kjac** [comment]
Hmmmmm well I still can't reproduce on vLatest, but now at least I can see an error in the console:

**Comment by kjac** [comment]
PR in #7745

**Comment by saifobeidat** [comment]
@kjac this the version that I downloaded and has the issue: [https://our.umbraco.com/download/releases/860](url) I don't know if it's the same as latest `v8/contrib`

**Comment by nul800sebastiaan** [comment]
@saifobeidat That's not the same. This issue has now been fixed for the upcoming final release of 8.6.0 (due out next week).
