### ISSUE TITLE
V8 Installer, ask (and set) default language

### ISSUE THREAD

**Issue by TimGeyssens** [umbraco/Umbraco-CMS#7743]
Having a play with the new variants feature, it's great but what I found is if you setup your site it uses the default lang (en-us) so all content you enter will be linked to that lang... once you then decide to make it multilingual.... there seems to be no way of saying that the already entered content should actually be a different culture... so an easy win would be to ask this during initial setup of the new Umbraco instance

**Comment by nul800sebastiaan** [comment]
This one duplicates https://github.com/umbraco/Umbraco-CMS/issues/7653 - I'll post an update there!

**Comment by TimGeyssens** [comment]
Ok thanks!
