### ISSUE TITLE
V8: If a user has no Dashboards, Sections don't load

### ISSUE THREAD

**Issue by joepvtl** [umbraco/Umbraco-CMS#7758]
When a user has no Dashboard the Sections don't load and give an error once you login.

## Umbraco version

I have tested this on: Umbraco 8.4.0 and 8.6.0-rc

### Bug summary

It gives a 500 because the querystings parameter is empty when adding the recyclebin to the TreeNodes.

### Steps to reproduce

1. Install a clean version of Umbraco.
2. Create a user that has the default 'Writer' group.
3. Make sure the user has the Content root as startnode.
4. Remove the RedirectUrlDashboard in a composer.
5. Login as the user.

### Expected result

No errors when logging in and Sections in the navigation header.

### Actual result

A 500 error when logging in with no Sections.

---
_This item has been added to our backlog [AB#5716](https://dev.azure.com/umbraco/243e7927-03b2-44e2-908f-d4ac7ea5daaa/_workitems/edit/5716)_

**Comment by nul800sebastiaan** [comment]
Really weird! I'm looking into it.

**Comment by joepvtl** [comment]
Hey @nul800sebastiaan,

Any news regarding this issue?

**Comment by nul800sebastiaan** [comment]
Sorry @joepvtl it kinda fell off my radar when I couldn't figure out what to do about it. The code seems very weird to me and I don't understand it. I'm sure there's someone at HQ who can help.. :-)

In any case, this is something we'll look at in the future and we'll try to fix it for 8.7.0, so it's going to take a while. Until then I'm afraid you'll have to live with adding at least some kind of dashboard that all your users can see. Might I suggest a friendly dashboard telling your writers and editors where they can reach someone if they have some problems using the system, or for example something with useful links: https://our.umbraco.com/packages/backoffice-extensions/the-dashboard/ (I know there's no v8 version of this yet, but you could use it for inspiration! 👍

**Comment by joepvtl** [comment]
No problem! I already worked around it by just creating a Dashboard with an empty view.
