### ISSUE TITLE
A "folder" in Content that does not count in the url generation

### ISSUE THREAD

**Issue by runegronkjaer** [umbraco/Umbraco-CMS#7769]
This is actually a feature we have needed in many years, but first yesterday, we came up with this idea.

We should be able to create a document type that should, when used as Content, does not count in the url generation. This way you could arrange your pages neatly in the Content section, but not mess with page url's. From our editors' perspective this would clean up their content tree and give them a better overview.

A default example of content tree and url
- home
  - cases
    - case 1
url: /home/cases/case-1/

An example of a misc "folder" content under which we could place all the pages that editors does not use very often.
- home
  - misc pages <-- Doc type with no url influence
    - login
    - search
    - etc.
url: /home/login/

**Comment by kjac** [comment]
Hi @runegronkjaer .. thanks for your input 👍

I completely understand your use case. But I'm also seeing a ton of challenges in supporting the suggested approach at core level.

First and foremost there is the concern about URL collisions between two "folders" and how to communicate these to the editors.

Secondly I see a major UX challenge in how _sometimes_ a parent node maps to the URL structure in frontend (for regular parents) and other times it does not (for "folder" parents).

There is also an issue with querying content by path. Which path is correct...? The content tree path or the calculated URL with "folder" nodes left out?

However, I do believe you can solve your use case with the extensions already baked into the routing part of Umbraco... A content finder comes to mind as the easiest choice. 

For simpler use cases where the "folder" nodes are known in advance you could also solve it by using IIS url rewriting.

**Comment by runegronkjaer** [comment]
Hi @kjac 

Yes, I do see a large challenge. I just wanted to get the idea out there, as we think it could be a great feature.

Doing the same thing with a custom content finder and url provider would be dangerous. We have had issues making these in the past as they have a tendency to break once in a while with new updates to Umbraco.

Just maybe keep it in the back of your minds, if an opportunity should come by.

/Rune

**Comment by c9mbundy** [comment]
FWIW: I've actually emulated this structure - albeit in v7 - in a way that satisfies my own needs, simply by using a template that does a Server.TransferRequest of any request to it either to the first child or the root node, depending on what is available to the 'folder' node. This is an approach I 'borrowed' from years working with Sitefinity, where they have a similar implementation of pseudo-folders - redirecting any request to the folder either to the first child or root.

**Comment by runegronkjaer** [comment]
@c9mbundy - But will your structure change the url's of the children? I believe this is a central part of the feature, so url's will be flattened.

**Comment by c9mbundy** [comment]
No, of course you are absolutely correct that it doesn't address that requirement, and I would see the same challenge with URL clashes mentioned above, once the request path is potentially not unique.

**Comment by nul800sebastiaan** [comment]
Thanks @runegronkjaer - as @kjac suggests, we expect you to use content finders for scenarios like this. I am sorry if we have broken those for you in the past, we really try not to and are always happy to issue a patch release if we accidentally do break them.
