### ISSUE TITLE
RTE styles with more than 2 classes getting separated by a period

### ISSUE THREAD

**Issue by Stick97** [umbraco/Umbraco-CMS#7770]
When setting up a style to use in the formats dropdown (style select toolbar option) in the RTE, classes don't get added to the RTE correctly if there are more than 2 classes in the selector that was configured in the stylesheet(s) added to the RTE data type. The first 2 classes get separated by a space, but all the rest get separated by a period (.).

## Umbraco version

I am seeing this issue on Umbraco version: 8.5.4

Reproduction
------------

### Steps to reproduce

1. Create a stylesheet from the Settings backoffice
2. Add a 'Rich text editor style'
	a. Name: Button
	b. Selector: a.btn.btn-primary.btn-lg
	c. Styles: padding: 1rem; background-color:#00699;
3. I also added "@import url('https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css');" to the top of the stylesheet in the code editor. Not sure that's important, but it might help to see the issue better.
4. Add the stylesheet to a data type that uses the Rich Text Editor property editor. This also happens with RTEs in grid data types.
    a. Make sure at least the "Style select", and "Source code editor" toolbar options are selected. I have all the options selected.
5. Make sure the the data type is included in a document type.
6. Create a new item, or edit an existing one using the document type.
7. Enter some text in the field using the RTE property editor, select it, and choose the Button option from the Formats dropdown menu in the toolbar.
8. Click the Source code button in the toolbar, and find the element that the Button style was applied to.

### Expected result

I would expect a new <a> element be created with the class attribute to have a value of "btn btn-primary btn-lg".

### Actual result

The class attribute has a value of "btn btn-primary.btn-lg".

**Comment by nul800sebastiaan** [comment]
Hey thee @Stick97, the custom styles functionality was never meant to create complex styles such as what you're trying to implement here. I would encourage you to try using the Grid instead, in which each component can be styled exactly the way you would want to. 

Custom styles in the rich text editor were always envisioned as applying to either create a simple tag to style (h1, h2, strong, etc) OR a class to apply. To do what you're trying here, you need to create the selector as `.btn btn-primary btn-lg` and then when applied it will usually wrap the selection with a `span` with the class you were expecting:

![image](https://user-images.githubusercontent.com/304656/76196182-102f5380-61ea-11ea-90ed-483dbf9d9f64.png)

However, it really isn't meant for complex styling which I think might be what you're trying to do. We're happy with how the current Styles dropdown works and don't plan on making changes to it any time soon. Therefore I'll close this issue and will encourage you to investigate using the Grid or possibly Nested Content depending on what you're trying to do.

**Comment by c9mbundy** [comment]
Another possible option - totally dependent on the application requirements - is to investigate tinyMceConfig.config and the use of <customConfig><config key="style_formats"> ... </config></customConfig>  - the tinyMce format syntax does support 'selector' 'classes' and 'styles{}' for specifying a style_format, but finding good examples of how to do it is difficult. I've managed to get some pretty weird style_formats to work, but generally more by stubbornness and dumb luck than by skill. 🙈

**Comment by Stick97** [comment]
@nul800sebastiaan, thanks, i had a feeling that was the case, but a few classes on a single element seem like 'simple styles' to me. Sadly, nested content and the grid seem like complex solutions to some simple problems we're facing.

@c9mbundy, I'm using that now, but was hoping to get different styles for different RTE data types. Style_format in the tinyMceConfig applies the styles to all RTEs.
