### ISSUE TITLE
Ensure document outline on 404

### ISSUE THREAD

**Issue by andersbrohall** [umbraco/Umbraco-CMS#7771]
The built-in 404 is intentionally left ugly. I have no problem with that. 
However, it breaks the document outline. That would be to consider a cardinal sin. 

I'll attach a pull request correcting that.

**Comment by andersbrohall** [comment]
https://github.com/umbraco/Umbraco-CMS/pull/7772

**Comment by nul800sebastiaan** [comment]
Fixed in #7772
