### ISSUE TITLE
Inconsistency in Template alias when creating a DocType with a custom Alias

### ISSUE THREAD

**Issue by billavl** [umbraco/Umbraco-CMS#7774]
When as an admin I go and create a new Document Type and modify the class name (or alias) the template alias is not the same but auto generated from the DocTypeName (and Template name)

Most of the time I want the aliases of DocType to have something more dev friendly and consistent whereas I keep the Doc type names for my editors with a different name that is more friendly to them.

I want to have the same name for the template file (and alias) as well so I won't have to go and manually change it every time I create a new document type.

You can see an example here https://www.youtube.com/watch?v=ktHhINnOz1w&feature=youtu.be

The problem is that if you manage a multi-tenant installation with many similar template names you might have a difficult time to pinpoint which .cshtml file corresponds to the doctype you just created. 

Additionally it introduces an inconsistency which affects developers

I am seeing this issue on Umbraco version: 8.5.4

Apologies if this is supposed to be opened as a feature. This one looked more like a bug to me.

As a story it could be written like:
"As a user, when I create a DocType with a Template, I want to have the same alias as the custom alias of the DocType I just edited"

**Comment by nul800sebastiaan** [comment]
Hi @billavl, I understand the issue you you're describing but unfortunately for you, this is how we intend the system to work and that's how it has always worked. Note that with infinite editing you can always go to the template from the document type directly and rename it if needed:

Open Template editor directly from the document type
![image](https://user-images.githubusercontent.com/304656/76197440-7321ea00-61ec-11ea-97cc-11309213b6b1.png)

Rename the alias at the top-right to rename the file
![image](https://user-images.githubusercontent.com/304656/76197455-76b57100-61ec-11ea-905e-b665bea1d9e8.png)

When you open it again you can see the file name is updated
![image](https://user-images.githubusercontent.com/304656/76197445-74531700-61ec-11ea-89b9-3e28599b784a.png)


One other thing to remember: people rely on the current behavior and we can't just change it without confusing everyone who is already used to how it currently works.

**Comment by billavl** [comment]
Hi Sebastian,
I understand though we could argue for hours about it if it would cause regressions or not and if user behavior could be changed.

Personally I assumed that I wasn't the only one that had this issue. And I am pretty sure no-one except the person who is oddly specific about their aliases like me would have noticed but if you are primed on doing the work you still build the habit doing it. that doesn't mean that a system behavior cannot be improved.

Thanks for the infinite editing tip. I have been using umbraco since version 2.0 (I think? it was 2005...) and it's a welcome feature though still doesn't solve the issue. Manual work still needs to happen for the person designing a series of doctypes and it's more prone to human mistake.

I guess it's me being nitpicky here then ;)

Cheers!

**Comment by nul800sebastiaan** [comment]
We're always happy to consider change requests but there has to be real value for most of our users. As it stands, you don't seem to be in the category "most of our users who create document types find it annoying that their template gets the same name as the document type". 😅

Ps. 2005, wow! ⭐
