### ISSUE TITLE
target ResetConfigFiles skipped

### ISSUE THREAD

**Issue by james-lau** [umbraco/Umbraco-CMS#7776]
When I inspect the msbuild.umbraco.log file created by build.ps1, I got this message:

`ResetConfigFiles:
Skipping target "ResetConfigFiles" because it has no inputs.`

My understanding is the Itemgroup\ConfigFiles node should place outside the Target item and before it.
`ResetConfigFiles:
  ConfigFile: E:\umbraco\Umbraco-CMS-release-8.5.3\src\Umbraco.Web.UI\config\ClientDependency.config -> E:\umbraco\Umbraco-CMS-release-8.5.3\build.tmp\WebApp\\config\ClientDependency.config
  Copying file from "E:\umbraco\Umbraco-CMS-release-8.5.3\src\Umbraco.Web.UI\config\ClientDependency.Release.config" to "E:\umbraco\Umbraco-CMS-release-8.5.3\build.tmp\WebApp\config\ClientDependency.config".
ResetConfigFiles:
  ConfigFile: E:\umbraco\Umbraco-CMS-release-8.5.3\src\Umbraco.Web.UI\config\HealthChecks.config -> E:\umbraco\Umbraco-CMS-release-8.5.3\build.tmp\WebApp\\config\HealthChecks.config
  Copying file from "E:\umbraco\Umbraco-CMS-release-8.5.3\src\Umbraco.Web.UI\config\HealthChecks.Release.config" to "E:\umbraco\Umbraco-CMS-release-8.5.3\build.tmp\WebApp\config\HealthChecks.config".
ResetConfigFiles:
  ConfigFile: E:\umbraco\Umbraco-CMS-release-8.5.3\src\Umbraco.Web.UI\config\serilog.config -> E:\umbraco\Umbraco-CMS-release-8.5.3\build.tmp\WebApp\\config\serilog.config
  Copying file from "E:\umbraco\Umbraco-CMS-release-8.5.3\src\Umbraco.Web.UI\config\serilog.Release.config" to "E:\umbraco\Umbraco-CMS-release-8.5.3\build.tmp\WebApp\config\serilog.config".
ResetConfigFiles:
  ConfigFile: E:\umbraco\Umbraco-CMS-release-8.5.3\src\Umbraco.Web.UI\config\serilog.user.config -> E:\umbraco\Umbraco-CMS-release-8.5.3\build.tmp\WebApp\\config\serilog.user.config
  Copying file from "E:\umbraco\Umbraco-CMS-release-8.5.3\src\Umbraco.Web.UI\config\serilog.user.Release.config" to "E:\umbraco\Umbraco-CMS-release-8.5.3\build.tmp\WebApp\config\serilog.user.config".
ResetConfigFiles:
  ConfigFile: E:\umbraco\Umbraco-CMS-release-8.5.3\src\Umbraco.Web.UI\config\tinyMceConfig.config -> E:\umbraco\Umbraco-CMS-release-8.5.3\build.tmp\WebApp\\config\tinyMceConfig.config
  Copying file from "E:\umbraco\Umbraco-CMS-release-8.5.3\src\Umbraco.Web.UI\config\tinyMceConfig.Release.config" to "E:\umbraco\Umbraco-CMS-release-8.5.3\build.tmp\WebApp\config\tinyMceConfig.config".
ResetConfigFiles:
  ConfigFile: E:\umbraco\Umbraco-CMS-release-8.5.3\src\Umbraco.Web.UI\config\umbracoSettings.config -> E:\umbraco\Umbraco-CMS-release-8.5.3\build.tmp\WebApp\\config\umbracoSettings.config
  Copying file from "E:\umbraco\Umbraco-CMS-release-8.5.3\src\Umbraco.Web.UI\config\umbracoSettings.Release.config" to "E:\umbraco\Umbraco-CMS-release-8.5.3\build.tmp\WebApp\config\umbracoSettings.config".
`

**Comment by nul800sebastiaan** [comment]
Hi @james-lau! Can you say anything about why this is a problem and what it's preventing you from doing please?

**Comment by james-lau** [comment]
I guess the build script try to use *.release.config as template for config files, but the ResetConfigFiles target always get an empty input file set and skipped.
