### ISSUE TITLE
Media picker not working

### ISSUE THREAD

**Issue by GionataAladinoCanova** [umbraco/Umbraco-CMS#7779]
Media Picker not delete image and not show upload area. See attached video.

[Media Picker Not Working.zip](https://github.com/umbraco/Umbraco-CMS/files/4308027/Media.Picker.Not.Working.zip)

**Comment by nul800sebastiaan** [comment]
Hey there @GionataAladinoCanova - thanks for the report. Next time it would be great if you could tell in a few more words what is going on so we don't have to guess things.

I am using 8.5.4 and with the steps in your video I can not reproduce this problem, seems to be something wrong in your setup!

![7779](https://user-images.githubusercontent.com/304656/76240940-5b6e5400-6234-11ea-8acb-1c87330cffdf.gif)

**Comment by GionataAladinoCanova** [comment]
Correct! After a day of hell all run ok!
