### ISSUE TITLE
UX Bug: Submitting Invalid Grid JSON Config Loses Changes

### ISSUE THREAD

**Issue by SvenPam** [umbraco/Umbraco-CMS#7789]
When editing the editor config for grid content; validation happens on blur. This allows you to click submit straight away, subsequently closing the dilogue and (frustatingly) losing your changes.

## Umbraco version

I am seeing this issue on Umbraco version: 8.5.4

Reproduction
------------

If you're filing a bug, please describe how to reproduce it. Include as much
relevant information as possible, such as:

### Bug summary

This is more of a UX bug than an actual issue. Given that data is lost, it can be frustrating.

### Specifics

URL: /umbraco#/settings/dataTypes/edit/{your grid data type ID}
Version: 8.5.4
Browser: Firefox 73
Other Browser's Checked: No - UX issue
Error message (which flashes up): "This configuration is not valid json, and will not be saved."
Screenshot: ![image](https://user-images.githubusercontent.com/3789646/76409817-d5165700-6386-11ea-8055-96ab07ba5e54.png)

### Steps to reproduce
1. Go to a grid data type settings
2. Under settings, click edit
3. Add some invalid JSON
4. Click "Submit"

### Expected result

Modal should not close - text box should retain changes.

### Actual result

Error flashes and hard work disappear's with the modal. 😥

**Comment by SvenPam** [comment]
This issues was bugging me. Tried my best to follow the contrib guide - advanced apologies if this is totally wrong.

**Comment by nul800sebastiaan** [comment]
Thanks @SvenPam - that PR looks quite alright to me, we'll have to have a proper look at it!

**Comment by BatJan** [comment]
@SvenPam Looks like your PR for this issues has already been merged so closing this issue now - Thanks for your contribution 🙌🏻 🎉
