### ISSUE TITLE
[BUG] Nodes(w/o children) / Group Permissions

### ISSUE THREAD

**Issue by atsimourtos** [umbraco/Umbraco-CMS#7794]
I have created a new User Group which has a limited access to specific nodes. So let's suppose we have.

> Document Type "Cars"
> Document Type "Car" (can be as children node to document type Cars)

If you create a group and give all kind of permission access for the node "Cars", the user will not be able to see the children nodes, the nodes which are "Car" document type.

Apart from that and upon setting the permissions for a custom user group, the administrator doesn't actually select Document Types, but content. I believe both should be available to cover the below scenarios:

- We want to create a group with limited access to specific Document Types
- We want to create a group with limited access to specific Content

Bug exists up to Umbraco Version 8.5.4

**Comment by nul800sebastiaan** [comment]
Hi @atsimourtos, we have no feature to limit users to a certain doctype and we currently don't plan on introducing that feature. 
 
I am unsure what you're trying to do and what is not working for you, maybe you can illustrate with some screenshots what your user group configuration looks like and what you can't see/do in the tree?

**Comment by emma-hq** [comment]
Hi @atsimourtos,

Since this issue has needed more information for almost a year, we are going to close it. If you do wish to reopen and provide the screenshots, please go ahead and we'll look at labelling and progressing it. 

Emma
