### ISSUE TITLE
Missing usergroup aliases

### ISSUE THREAD

**Issue by erikjanwestendorp** [umbraco/Umbraco-CMS#7803]
The editor group and the writers group aliases are missing in [Constants-Security.cs](https://github.com/umbraco/Umbraco-CMS/blob/v8/contrib/src/Umbraco.Core/Constants-Security.cs)

Not a big issue of course, but would be nice to have them there 👍

**Comment by nul800sebastiaan** [comment]
@erikjanwestendorp Just so you know, when making a PR you don't have to link it to an issue. If an existing issue is present then of course link it, but no need to make a fresh issue for a new PR! 👍

**Comment by nul800sebastiaan** [comment]
Fixed in https://github.com/umbraco/Umbraco-CMS/pull/7804
