### ISSUE TITLE
Update ClientDependency to v1.9.9

### ISSUE THREAD

**Issue by nul800sebastiaan** [umbraco/Umbraco-CMS#7815]
Fixes the security issue as described in https://umbraco.com/blog/security-advisory-17th-of-march-patch-for-your-site-is-now-available/

**Comment by nul800sebastiaan** [comment]
Fixed in:

https://github.com/umbraco/Umbraco-CMS/commit/2d3388d6d3ff6882c9e7b9e92f717ece03834fbe and https://github.com/umbraco/Umbraco-CMS/commit/d52695d81f607cc24c8a96ac95a82f9869c2a065

**Comment by saifobeidat** [comment]
@nul800sebastiaan can you tell me what's the plan now about releasing 8.6?

**Comment by nul800sebastiaan** [comment]
As for the 8.6.0 release, we have had to focus on a security release first (https://umbraco.com/blog/security-advisory-17th-of-march-patch-for-your-site-is-now-available/) and of course everybody at the company is currently dealing as best we can with the changing circumstances resulting from the corona virus pandemic. Therefore we have had to delay the release of 8.6.0 final until at least next week, it's currently difficult to give an exact date.
