### ISSUE TITLE
Upgrade from 8.2.1 to 8.5.5 Fails

### ISSUE THREAD

**Issue by crick3t** [umbraco/Umbraco-CMS#7821]
I am trying to upgrade Umbraco from 8.2.1 to 8.5.5, but there is an error at boot time.

"Attempt by method 'Umbraco.ModelsBuilder.Embedded.Compose.DisabledModelsBuilderComponent.Initialize()' to access method 'Umbraco.Web.Features.UmbracoFeatures.get_Disabled()' failed."

Umbraco.Core.Exceptions.BootFailedException: Boot failed.

```
 System.MethodAccessException: Attempt by method 'Umbraco.ModelsBuilder.Embedded.Compose.DisabledModelsBuilderComponent.Initialize()' to access method 'Umbraco.Web.Features.UmbracoFeatures.get_Disabled()' failed.
    at Umbraco.ModelsBuilder.Embedded.Compose.DisabledModelsBuilderComponent.Initialize() in D:\a\1\s\src\Umbraco.ModelsBuilder.Embedded\Compose\DisabledModelsBuilderComponent.cs:line 23
    at Umbraco.Core.Composing.ComponentCollection.Initialize()
    at Umbraco.Core.Runtime.CoreRuntime.Boot(IRegister register, DisposableTimer timer)]
    Umbraco.Core.Exceptions.BootFailedException.Rethrow(BootFailedException bootFailedException) +226
    Umbraco.Web.<>c.<Init>b__18_0(Object sender, EventArgs args) +35
    System.Web.SyncEventExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute() +200
    System.Web.HttpApplication.ExecuteStepImpl(IExecutionStep step) +132
    System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously) +73
```

I suspect it is related to the ModelsBuilder.
My config is: 
```
  <add key="Umbraco.ModelsBuilder.Enable" value="true" />
  <add key="Umbraco.ModelsBuilder.ModelsMode" value="Dll" />
```

But I get the same error if I change it to:
```
  <add key="Umbraco.ModelsBuilder.Enable" value="false" />
  <add key="Umbraco.ModelsBuilder.ModelsMode" value="Nothing" />
```

**Comment by nul800sebastiaan** [comment]
We haven't seen that before, sounds like something went wrong in your upgrade somewhere.

This blog post is old but still very relevant: https://cultiv.nl/blog/how-to-diagnose-umbraco-upgrade-problems/

If you've double checked everything using that blog post and you still have this problem then I'd recommend you head to the forum to get some help from our friendly community: https://our.umbraco.com/

**Comment by sinkypars1885** [comment]
I'm getting this issue now too after upgrading to 8.5.5.

Maybe this is something to do with me generting the models into another project from the code? e.g.

<add key="Umbraco.ModelsBuilder.Enable" value="true" />
    <add key="Umbraco.ModelsBuilder.EnableApi" value="false" />
    <add key="Umbraco.ModelsBuilder.ModelsMode" value="AppData" />
    <add key="Umbraco.ModelsBuilder.ModelsDirectory" value="~/../OtherFolder/Generated/" />
    <add key="Umbraco.ModelsBuilder.AcceptUnsafeModelsDirectory" value="true" />

**Comment by crick3t** [comment]
In my case it turned out it the NuGet update that went wrong. I have wrote down my solution here
https://our.umbraco.com/forum/using-umbraco-and-getting-started/101578-upgrade-from-821-to-855-fails

Hope that helps.

**Comment by sinkypars1885** [comment]
Amazing, thanks @crick3t !

Deleting all the DLL's and rebuilding did the trick for me,
