### ISSUE TITLE
V8 - Content section custom dashboard tab issue

### ISSUE THREAD

**Issue by Cockney-Rob** [umbraco/Umbraco-CMS#7824]
I hope the answer to this will be quick and easy. I have a custom dashboard tab I would like to add in the 'Content' section. At the same time I would like to hide the 'Getting Started' tab in the same section. Advice on the latter is to use this;

composition.Dashboards().Remove\<ContentDashboard>();

This does indeed hide the 'Getting Started' tab, however it also hides my custom tab. 

Code attached. 
[dashboard.txt](https://github.com/umbraco/Umbraco-CMS/files/4354227/dashboard.txt)

Please advise.

**Comment by nul800sebastiaan** [comment]
Hi there @Cockney-Rob, I dropped your code into an 8.5.3 site (just in `App_Code`) and it works as expected.

![image](https://user-images.githubusercontent.com/304656/77066587-b7c73580-69e3-11ea-8947-555411d110e3.png)


This sounds like an excellent question for the forums where our friendly community can help you find the best solution for your requirements. 
Make sure to head on over to https://our.umbraco.com and ask follow up questions there! 👍

**Comment by Cockney-Rob** [comment]
Hi @nul800sebastiaan thanks for your time. I was fearing that would be the case. I'm using 8.5.1 so will upgrade and see if that resolves the issue.

**Comment by nul800sebastiaan** [comment]
8.5.5 is out now, but I don't think anything has changed for dashboards.. https://github.com/umbraco/Umbraco-CMS/compare/release-8.5.1...release-8.5.5

Think you're going to have to look elsewhere (custom code perhaps, user permissions.. who knows).

**Comment by Cockney-Rob** [comment]
Hi @nul800sebastiaan  just to inform you that the issue wasn't an issue at all, the problem being one of my own making and too embarrasing to share. Thanks for your time anyway.

**Comment by nul800sebastiaan** [comment]
I won't tell anyone! 🤐🤫😉
