### ISSUE TITLE
U8 changing PhysicalFileSystem path for media breaks GetBigThumbnail method in backoffice

### ISSUE THREAD

**Issue by chris-evansnz** [umbraco/Umbraco-CMS#7841]
## Umbraco version

I am seeing this issue on Umbraco version: 8.5.3

Reproduction
------------

Create new Visual Studio project, and install a clean version of Umbraco 8.5.3 from Nuget.

Using the documentation here:  
https://our.umbraco.com/documentation/Extending/FileSystemProviders/

Add a composer class and set a new PhysicalFileSystem path value of "~/app/test/media"

All media should now be loaded into this folder.

Create a new doctype called Home, add a single Media Picker property called Test Image.

### Bug summary

Image shows fine when uploaded to Media library; can open image in a new window and see it render properly at /app/test/media/gwedqkio/filename.jpg

Image also shows fine on the frontend in the browser when rendered on a page - uses correct updated path inside /app/test/media

But when picking the image using the Media Picker, the thumbnail does not show in the media flyout - shows a broken image instead. 

![image](https://user-images.githubusercontent.com/58791033/77504705-f8342100-6ec5-11ea-8960-9ac4c5e3f7d6.png)

This also shows after picking the image on the Media Picker property itself:

![image](https://user-images.githubusercontent.com/58791033/77504739-0c781e00-6ec6-11ea-886d-7ade620008ec.png)

The console shows a 500 error for /umbraco/backoffice/UmbracoApi/Images/GetBigThumbnail?originalImagePath=%2Fmedia%2Fgwedqkio%2Ffilename.jpg&rnd=0.948657119016634

![image](https://user-images.githubusercontent.com/58791033/77504465-4eed2b00-6ec5-11ea-80fd-388cbd099450.png)

When viewing this path in browser, shows the following error:

An error has occurred.
File '/media/gwedqkio/amarok.png' is outside this filesystem's root.
Umbraco.Core.IO.FileSecurityException
at Umbraco.Core.IO.PhysicalFileSystem.GetFullPath(String path) in d:\a\1\s\src\Umbraco.Core\IO\PhysicalFileSystem.cs:line 317

Note that the GetBigThumbnail is trying to find the media file at the default /media path instead of using the /app/test/media path as set by the Composer.

When updating the GetBigThumbnail call manually in the browser address bar to have the full path, image shows normally, e.g.

/umbraco/backoffice/UmbracoApi/Images/GetBigThumbnail?originalImagePath=%2Fapp%2Ftest%2Fmedia%2Fgwedqkio%2Ffilename.png&rnd=0.948657119016634

**Comment by nul800sebastiaan** [comment]
Thanks @chris-evansnz! This was [fixed for 8.6.0](https://github.com/umbraco/Umbraco-CMS/issues/6324) which will be out next week.

**Comment by chris-evansnz** [comment]
Thanks @nul800sebastiaan  - that's good to know.

Is there a hotfix available that we could apply before the 8.6.0 release?

**Comment by nul800sebastiaan** [comment]
@chris-evansnz Not really, the change is part of the RC https://umbraco.com/blog/umbraco-product-update-february-20th-2020/ but it has problems with nested content, if you don't use nested content you can happily use that.

The problem, ultimately, seems to stem from the path being stored in the UmbracoMediaVersion table, you can see it flipping the path here while I'm switching between 8.5.5 and 8.6.0: 

![image](https://user-images.githubusercontent.com/304656/77637717-645e6580-6f56-11ea-8399-a73e50a369ba.png)

So you could try to update the rows in this table with the correct path and recycling the app pool to clear the caches. You will have to do this for all new uploads though.
