### ISSUE TITLE
Image Selector of Rich Text Editor - Select Button Disabled

### ISSUE THREAD

**Issue by Rizen-Kris** [umbraco/Umbraco-CMS#7849]
If you select the image icon in the rich text editor and select an image... the "select" button is disabled.. but hitting Enter inserts image..

**Comment by nul800sebastiaan** [comment]
Hi there @Rizen-Kris, what version of Umbraco are you working with?

**Comment by Rizen-Kris** [comment]
8.5.5

**Comment by nul800sebastiaan** [comment]
Alright, thanks! I'm afraid I can't reproduce this, maybe some of your custom code is getting in the way? 

![7849](https://user-images.githubusercontent.com/304656/77911886-dce45f80-7291-11ea-905b-2b38a22da590.gif)

**Comment by Rizen-Kris** [comment]
What could effect this?

**Comment by Rizen-Kris** [comment]
Here is a video of the issue...

https://www.youtube.com/watch?v=Oh6SEDmJTdk

**Comment by nul800sebastiaan** [comment]
I have no idea either I'm afraid. I would walk through these steps here, it's an old blog post but the idea is still the same: https://cultiv.nl/blog/how-to-diagnose-umbraco-upgrade-problems/

Compare all the files in the clean 8.5.5 zip file and make sure that all of the files that we ship with are the same in your site, especially the `/umbraco` directory. Use WinMerge or BeyondCompare for example to do a complete directory compare.

Maybe an upgrade to 8.6.2 will be helpful as well, although I do believe I checked this in 8.5.5.

**Comment by nul800sebastiaan** [comment]
It's not really the point to follow the post exactly to the letter, but here's the settings I'm currently using. If you have a favorite compare too (WinMerge, KDiff, etc, then that's just as great to use).

[BCSettings20200611.zip](https://github.com/umbraco/Umbraco-CMS/files/4763113/BCSettings20200611.zip)
