### ISSUE TITLE
Nested Content Property Editor - SingleMode/Missing Model Id

### ISSUE THREAD

**Issue by SofusMunch** [umbraco/Umbraco-CMS#7854]
This is my first time reporting an issue, so forgive me for not following conventions. 

When creating a nested content datatype with multiple selectable document types with min and max items set to 1, the editor goes into singlemode and automatically selects the first document type. It isn't possible to select any other and furthermore not possible to delete the autoselected one. The problems seems to be here: (line 17596)

```
// Auto-fill with elementTypes, but only if we have one type to choose from, and if this property is empty.
 if (vm.singleMode === true && vm.nodes.length === 0 && model.config.minItems > 0) {
          for (var i = vm.nodes.length; i < model.config.minItems; i++) {
                 addNode(vm.scaffolds[0].contentTypeAlias);
           }
 }
```
If no nodes are created, it loops once adding the first doc types. It doesn't check whether there is only one to choose from. It should be:

```
if (vm.singleMode === true && vm.scaffolds.length === 1 && model.config.minItems > 0) {
           for (var i = vm.nodes.length; i < model.config.minItems; i++) {
                   addNode(vm.scaffolds[0].contentTypeAlias);
           }
 }
```

This change makes it possible to select from several possible doctypes but presents another problem. In singleMode the header is disabled, and it is then not possible to delete the item and select another doc type.

The following all applies to Line 17219

```
<div class="umb-nested-content__header-bar" ng-click="vm.editNode($index)" ng-hide="vm.singleMode">
```

Should be:

```
<div class="umb-nested-content__header-bar" ng-click="vm.editNode($index)" ng-hide="vm.singleMode && vm.scaffolds.length === 1">
```

Showing the header means the style removing margin on umb-pane in singleMode should only be applied if scaffolds.length === 1 and the header is hidden:

```
 \'umb-nested-content__item--single\' : vm.singleMode  }">}
```

Change to:

```
\'umb-nested-content__item--single\' : vm.singleMode && vm.scaffolds.length === 1 }">
```

Since max items is limited to 1, there is no need to show the "add button" if nodes >= maxItems, which seems to be the intent with:

```
<button class="btn-reset umb-nested-content__add-content umb-focus" ng-class="{ \'--disabled\': (!vm.scaffolds.length || vm.nodes.length >= maxItems) }"
```

Should be:

```
<button class="btn-reset umb-nested-content__add-content umb-focus" ng-class="{ \'--disabled\': (!vm.scaffolds.length || vm.nodes.length >= vm.maxItems) }"
```

Even better the check should be on the parent container since it has a margin-top/bottom, and leaves an empty space if the button is hidden.

Lastly the model is never set on the scope, so the following is empty:

```
<div id="umb-nested-content--{{model.id}}" 
```

Before (no selection possible, redundant add button):

![nested_before](https://user-images.githubusercontent.com/789813/77846260-198e5900-71b5-11ea-8031-14119e2d5b21.JPG)

After (selection possible, header visible, add button removed, umb-pane margin restored):

![nested_after1](https://user-images.githubusercontent.com/789813/77846445-6292dd00-71b6-11ea-8da6-5fd4d9d7e859.JPG)

![nested_after2](https://user-images.githubusercontent.com/789813/77846451-6fafcc00-71b6-11ea-847c-405769cf6f09.JPG)

Edit: It seems this is #5427 resurfacing, and solved more elegantly then.

**Comment by nul800sebastiaan** [comment]
Thanks for the elaborate explanation, but we're missing one important detail here.. what version are you on? 🙈 

Issue https://github.com/umbraco/Umbraco-CMS/issues/5427 you're referring to is fixed for version 8.6.0, which is going to be out tomorrow. I think that solves your problem?

**Comment by SofusMunch** [comment]
Yes of course. Version 8.5.5

Does 8.6 also fix the missing model id? It doesn’t seem to have any effect, but it might as well be fixed.

**Comment by nul800sebastiaan** [comment]
@SofusMunch I am not sure. I'd encourage you to play around with it and see how it feels to you, we can make more updates once it's released! 👍
