### ISSUE TITLE
New property in Element / Nested Content Not Being Saved Until Application Restart

### ISSUE THREAD

**Issue by ltctech** [umbraco/Umbraco-CMS#7870]
## Umbraco version

I am seeing this issue on Umbraco version: 8.6

Reproduction
------------

### Bug summary
When one creates a new property like a TextString on an element type used within a nested content property one is unable to store the value of the property until the application is restarted.

### Specifics
Browsers:
Firefox 74
Chrome 80

IDE:
Visual Studio 16.4.5
Debug Mode
Debugger Attached

### Steps to reproduce
1. Use Umbraco Starter Template
2. Create new TextString property under "Feature" Document Type
3. Enter a value for the new TextString property under a "Product" for an existing "Feature"
4. Click Save and Publsih
5. Refresh the page Ctrl+Shift+R

### Expected result
The value saved for the new property should be filled in on refresh.

### Actual result
The value for the new property is blank after refresh.

### Work Around
Stop debugging. Start debugging. Once application reloads it works correctly.

---
_This item has been added to our backlog [AB#6260](https://dev.azure.com/umbraco/243e7927-03b2-44e2-908f-d4ac7ea5daaa/_workitems/edit/6260)_

**Comment by nul800sebastiaan** [comment]
What Umbraco version are you using?

**Comment by ltctech** [comment]
I'm using 8.6.0 from Nuget. After updating a 7.5.3 project to 8.6.0 this morning I started experiencing this issue. The same also happens with a 7.5.5 project to updated to 8.6.0.

I have not tried replicating this issue with a brand new 8.6.0 project.

**Comment by nul800sebastiaan** [comment]
Thanks @ltctech - unfortunately this is not something we can reproduce in 8.6.0, something might not be quite alright with the migration you've done. Maybe you can get some help with this on the forum at https://our.umbraco.com/

**Comment by ltctech** [comment]
**Correction on my earlier comment:**
I was updating from 8.5.3 and 8.5.5 to 8.6.0.

I have reproduced the issue with a clean 8.6.0 project. The issue does not occur with a clean 8.5.5 project.

**New steps to reproduce:**
1. Use Umbraco Starter Template
2. Under Cotent open a "Feature" under a "Product" ensuring that NestedContentPropertyEditor is displayed (this caches content types under NestedContentPropertyEditor )
3. Under Settings create a new TextString property under "Feature" Document Type
4. Under Content enter a value for the new TextString property for an existing "Feature" under a "Product" 
5. Click Save and Publsih
6. Refresh the page Ctrl+Shift+R
7. Notice value was not saved

**Probable Cause:**
NestedContentPropertyEditor is a DataEditor singleton within PropertyEditorCollection.

It has a NestedContentPropertyValueEditor which has a NestedContentValues which has a Lazy IContentType Dictionary. When the NestedContentPropertyEditor is shown in the backoffice UI NestedContentValues.GetElementType is called initializing the Lazy IContentType Dictionary.

In 8.5.5 this is not an issue as DataEditor.GetValueEditor creates a new instance of NestedContentPropertyValueEditor each time it is requested. In 8.6.0 DataEditor.GetValueEditor caches the result using a property on the DataEditor singleton. The comments in the code specifically say not to cache it, yet that's exactly what it does in 8.6.0.

From that point on the NestedContentPropertyEditor singleton is using a cached and stale copy of content types. When new properties are added to a content type it doesn't know about them.

**Problematic Commit:**
https://github.com/umbraco/Umbraco-CMS/commit/15865d566b0549acf651b63cdd97b474e8a362d4#diff-9a89dd1eb30e7e890f5b455827c80189

**DataEditor.cs 8.5.5:**

```
        /// <inheritdoc />
        /// <remarks>
        /// <para>If an explicit value editor has been assigned, then this explicit
        /// instance is returned. Otherwise, a new instance is created by CreateValueEditor.</para>
        /// <para>The instance created by CreateValueEditor is not cached, i.e.
        /// a new instance is created each time the property value is retrieved. The
        /// property editor is a singleton, and the value editor cannot be a singleton
        /// since it depends on the datatype configuration.</para>
        /// <para>Technically, it could be cached by datatype but let's keep things
        /// simple enough for now.</para>
        /// </remarks>
        // TODO: point of that one? shouldn't we always configure?
        public IDataValueEditor GetValueEditor() => ExplicitValueEditor ?? CreateValueEditor();
```

**DataEditor.cs 8.6.0:**
```
        /// <inheritdoc />
        /// <remarks>
        /// <para>If an explicit value editor has been assigned, then this explicit
        /// instance is returned. Otherwise, a new instance is created by CreateValueEditor.</para>
        /// <para>The instance created by CreateValueEditor is not cached, i.e.
        /// a new instance is created each time the property value is retrieved. The
        /// property editor is a singleton, and the value editor cannot be a singleton
        /// since it depends on the datatype configuration.</para>
        /// <para>Technically, it could be cached by datatype but let's keep things
        /// simple enough for now.</para>
        /// </remarks>
        // TODO: point of that one? shouldn't we always configure?
        public IDataValueEditor GetValueEditor() => ExplicitValueEditor ?? (_dataValueEditor ?? (_dataValueEditor = CreateValueEditor()));
```

**Comment by Shazwazza** [comment]
Yes that seems like the issue and also the change goes against what the comments there say. I did make this change (5 months ago) for the media tracking changes... though I do not recall why the change was made :( 
I'll re-open this.

Any chance you are able to make a PR to revert this particular change and then re-test? We'll then need to try to figure out why this change was made, perhaps it was just a mistake, i just cannot recall.
