### ISSUE TITLE
Timeout Error while upgrading from 7.15.3 to Umbraco 8

### ISSUE THREAD

**Issue by raghavthakur1** [umbraco/Umbraco-CMS#7873]
While upgrading from Umbraco 7.15.3 to 8 , it fails at the following step with the below error even after repeated attempts. FYI The umbracolog table has been truncated so not sure where this is failing

 ```
Umbraco.Web.Install.InstallException: The database failed to upgrade. ERROR: The database configuration failed with the following message: Execution Timeout Expired.  The timeout period elapsed prior to completion of the operation or the server is not responding.
```

**Comment by nul800sebastiaan** [comment]
Thanks, there's a number of issue when running the migration from v7 to v8. You might have some better luck using the instructions from this comment: https://github.com/umbraco/Umbraco-CMS/pull/6002#issuecomment-591344554

For any additional issues not covered in on the discussion there, please comment there so we can collect them all together.

**Comment by raghavthakur1** [comment]
Solution: Increasing  the timeout in the webconfig sorted this issue

**Comment by ewanexer** [comment]
What settings did you change exactly in web.config?

I can see only 

`<add key="Umbraco.Core.TimeOutInMinutes" value="20" />`

but this relates to the backoffice session and also my timeout happens after just 1-2 minutes of the upgrade start while `TimeOutInMinutes` has 20 minutes span.

Is there any other setting that allows longer database await?

**Comment by nathanwoulfe** [comment]
Try setting the SqlCommand.Connection Timeout property in your connection string. 

<add name="umbracoDbDSN" connectionString="...truncated for brevity... Connection Timeout=3600" />
