### ISSUE TITLE
Package Section missing in Umbraco8

### ISSUE THREAD

**Issue by raghavthakur1** [umbraco/Umbraco-CMS#7878]
Hi ,

I managed to upgrade from 7.15.3 to 8 . However on the umbraco dashboard , package section is not visible. Am I missing any setting or is it a bug 
![Content - localhost - Google Chrome 2020-04-01 23](https://user-images.githubusercontent.com/10909369/78171025-7322ac00-7471-11ea-861b-cd227ac3837a.png)
?

**Comment by ronaldbarendse** [comment]
Looks like you don't have access to the Packages section (see the screenshots on https://our.umbraco.com/Documentation/Extending/Packages/package-types). You can manually add this section to the Administrators group (see https://our.umbraco.com/documentation/Getting-Started/Data/Users/).

I also noticed this on an upgraded site, so this is something that might be handled better in the v7 to v8 migrations. It is documented in the migration instructions however: https://our.umbraco.com/documentation/getting-started/setup/upgrading/migrating-to-v8#step-3-post-migration-checks.

**Comment by nul800sebastiaan** [comment]
This is fixed in 8.7.0 https://github.com/umbraco/Umbraco-CMS/pull/7641
