### ISSUE TITLE
Error getting remote dashboard data from "https://umbraco.com/""feeds/videos/members

### ISSUE THREAD

**Issue by ctf-umbraco** [umbraco/Umbraco-CMS#7881]
In the member section on Umbraco, I receive this error:  Error getting remote dashboard data from "https://umbraco.com/""feeds/videos/members.

This is because nothing is returned when this function calls API endpoint.

## Umbraco version

I am seeing this issue on Umbraco version: 8.5.5

Reproduction
------------

### Bug summary

This can be reproduced by following these steps:
1. install a clean Umbraco 8 project
2. Open the console log on the network tab
3. In the Umbraco CMS navigate to Members section
4. Look at the networks tab here you should see - feeds/videos/members that shows a 200 status code, however, there is no response to this.
5. Then go to the Settings tab in the CMS and navigate to Log viewer, here click number of errors and in the list, it presents you you should be able to find this  Error getting remote dashboard data from "https://umbraco.com/""feeds/videos/members"

### Specifics

    
    *happens on 8.5.5 - 8.6.0 - haven't tested on the other versions
    * chrome
    * I have not tested in other browsers
    * full error message: 
Exception
System.Net.Http.HttpRequestException: Response status code does not indicate success: 404 (Not Found).
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Umbraco.Web.Editors.DashboardController.<GetRemoteXml>d__5.MoveNext()

### Actual result

    * The result is a dashboard that does not fetch data from the feed

**Comment by nul800sebastiaan** [comment]
Thanks, we'll need to fix it on Umbraco.com, I've sent this to @hartviglarsen, he'll handle it from here.

**Comment by mirkomaty** [comment]
Well... I have the same phenomenon with Umbraco 10.8.6. Is there any solution for this?
