### ISSUE TITLE
Cannot add Format to existing link in RTE

### ISSUE THREAD

**Issue by andersbrohall** [umbraco/Umbraco-CMS#7883]
In the rich text editor: 
Selecting a pre-defined format for a.button doesn't stick to an existing a[href].

## Umbraco version

I am seeing this issue on Umbraco version: 8.6.0

Reproduction
------------
We have a pre-defined style with these settings:
Name: _Button_
Selector: _a.button_
Styles: _display:block; background-color:deeppink;_

The stylesheet is added to a RTE in backoffice. 

Scenario 1:
Type a text in a RTE: _My button_.
Mark the text.
Select _Button_ in the Formats dropdown.
Click the link-button and choose a link destination.

This sequence works. You can confirm that the a[href] also has a [class] when opening the markup window. 

Scenario 2: 
Type a text in a RTE: _My button_.
Mark the text.
Click the link-button and choose a link destination.
Select _Button_ in the Formats dropdown.

**This sequence does not work**. There is no [class] added to a-tag in the markup.

**Comment by nul800sebastiaan** [comment]
"Complex" CSS selectors are not very well supported, the only thing you can probably do in this case is to use `button`  as the selector. We currently don't have plans to support "complex" selectors. For more info see this issue comments as well: https://github.com/umbraco/Umbraco-CMS/issues/7770
