### ISSUE TITLE
8.6 ContentService.SaveAndPublish(item) does not save default template

### ISSUE THREAD

**Issue by Rizen-Kris** [umbraco/Umbraco-CMS#7888]
If you click save and publish in the back office it will set the template to the default if it is null. It does not when you do it from code (ContentService.SaveAndPublish(item)). 

## 8.6.0

I am seeing this issue on Umbraco version: 8.6.0

**Comment by nul800sebastiaan** [comment]
Hi there @Rizen-Kris - not sure how to reproduce this problem, the following code works fine:

```
var contentService = Services.ContentService;
var node = contentService.Create("Tester", 1104, "textPage");
contentService.SaveAndPublish(node);
```

I have multiple templates available for this content type and when I switch the default in Umbraco and then create a new node with the above code, that new default template is being set.

**Comment by Rizen-Kris** [comment]
NO, sorry, it's not that you can't set the template.. just wondering if it should set the default template when you save and there is not one set for the specific document.. Like the back-office does

**Comment by nul800sebastiaan** [comment]
I'm not sure what exactly you mean. 🤔 but almost anything is possible, make sure to head to the forum at https://our.umbraco.com to describe what you're trying to achieve and get some help from our friendly community.
