### ISSUE TITLE
Can't add composition to DocType which has children

### ISSUE THREAD

**Issue by dhymik** [umbraco/Umbraco-CMS#7891]
Umbraco 8.6

When I want to add a composition to a parent DocType which already has child DocTypes, I cannot add nor remove a composition. I get the message:

> This content type is used in a composition, and therefore cannot be composed itself.

When I add the composition to the parent DocType prior to adding child DocTypes, it works. Child DocTypes added to the parent later properly inherit the parent's compositions.

If this limitation is intentional and will stay, I am happy to append this information to the documentation.

**Comment by nul800sebastiaan** [comment]
Yep, this is completely intentional, nesting doctypes means you are composing them since the children inherit properties from the parent (== composition). 👍

**Comment by dhymik** [comment]
Sebastiaan, thank you for your reply.

So, I cannot create a DocType, add a child DocType, and then add a composition to the parent. Understood.

The confusing part is that _I can_ create a DocType, first add a composition DocType to it, and only then add a child DocType. So basically I now have _a composed DocType used in a composition_, and it works perfectly well - but then I cannot change the DocTypes used as composition for the parent, once the child DocType has been added 
I _can_, however, change the composition DocTypes properties lateron, and the changes will cascade through to the child DocType. 

Because of these inconsistencies, I smell that there might be an unnecessary limitation involved. 

If _this_ is indeed intentional and supposed to stay this way, please confirm this again, so I can make this clear in the docs. On the other hand, if this is only due to a limitation in the current Umbraco code which can be rectified, may be there can be a proposal to change this.

I drafted an addition for the Umbraco documentation on Our to explain the rules for using DocType composition, see below. Would you please glance over it to conform that what I wrote is in fact correct?

If you confirm that the above described behavior is true and correct, I will however have to change my draft, stating the exception and advising developers to think about composition before they add child DocTypes to a DocType.

Here starts my draft:

**Composed DocTypes**
A DocType _is composed_ if it contains (inherits) other DocTypes properties. This is the case when at least one of the following is true:

- it is the child DocType of a parent Doctype, or
- it contains other DocTypes as composition

**DocTypes used in a composition**
A Doctype is _used in a composition_ when at least one of the following is true:
- it is the parent DocType of child Doctypes, or
- it is used as composition in other DocTypes

**Limitations of DocType Composition**

Adding as Composition:
Only a DocType which is _not composed_ can be added as composition to a DocType. This means:
- a child DocType which inherits from other DocTypes cannot be added as composition to other DocTypes
- a DocType which itself is enhanced by other composition DocTypes cannot be added as composition to other DocTypes

Composing
Only a DocType which is _not used in a composition_ can be enhanced by adding composition DocTypes. This means:
- a DocType which is the parent to child DocTypes cannot be enhanced by composition
- a DocType which is used as composition in other DocTypes cannot be enhanced by composition

If a DocType does not qualify to be enhanced by composition, the Compositions tab in the DocType editor will display the message _"This content type is used in a composition, and therefore cannot be composed itself."_


Once a DocType is used as a parent for child Doctypes or in a composition of another DocType, then this DocType  itself cannot be composed anymore: you cannot add other DocTypes as compositions to this DocType.


**Colliding Property Alias**
A DocType can only be added to another DocType as composition if there is no property alias collision. DocTypes which contain colliding property aliases are grayed out in the composition selection dialog.

**Composition and Element Types**
In addition to the above limitations, the following limitations apply for element types:
- only element type DocTypes can be used as composition in an element type DocType

**Comment by medarke** [comment]
@dhymik What you have written from what I can tell is correct. - I agree with you that the limitation is not necessary and is not at first glace intuitive, even though you can use Inheritence and compositions togehter, going forward I won't. 
I will probably just use one or the other (probably compositions becuase they are more flexible) 

My overall view is that this should be changed, I'm currently doing a new Umbraco build using Umbraco 10 and have just discoved this limitation, I'm not to far in so though its not ideal I will stick with what I have got, but no more inheritance for me.

**Comment by c9mb** [comment]
@medarke I agree - if it's possible to add before children and not possible to add after, then that means you have to get it right first try, and that's not a good experience.

**Comment by alandraper** [comment]
Yes, definitely not a good experience. 

I have a base page type with several compositions. 

All page types inherit from that base page type so in turn they all have the compositions. 

Now I want to add a new composition to the base page type, but it won't allow. Makes no sense and means I have to break my structure, or "get everything perfect from the start" which ain't gonna happen. 

If you don't think inheritance and compositions should be used together, then you shouldn't allow it at all rather than allow it at first but not allow it to be changed.

**Comment by alandraper** [comment]
For anyone that lands on this page: to me it looks like the "inheritance" just adds the parent's composition to all of the child types. 

If I have this content type
1000 - BasePageType 
with this composition type
999 - NavigationProperties

And then create the following:
1001 - HomePageType (inherits from BasePageType)
1002 - LandingPageType (inherits from BasePageType)
1003 - RegularPageType (inherits from BasePageType)

Then in the database, cmsContentType2ContentType will have entries for 
parentContentTypeId | childContentTypeId
     999                               1000
     999                               1001
     999                               1002
     999                               1003

**Comment by alandraper** [comment]
This also means you can't _remove_ a composition from a base document type.

**Comment by alandraper** [comment]
Worked for me to insert cmsContentType2ContentType 
parentContentTypeId is the new composition type
childContentTypeId is the base type and all inherited types

Then delete umbraco temp data and restart site. 

<sad trombone />
