### ISSUE TITLE
Can't remove an item from Nested Content if Min/max = 1

### ISSUE THREAD

**Issue by Ric-Carey** [umbraco/Umbraco-CMS#7892]
Hi,

If you add a nested content with two document types in, and then set it to min items 1 and max items 1. As in meaning – the editor needs to pick one. They are presented with the first document type as a default, and the controls to delete the item are not present. Meaning they cannot change the item which is selected:
There is also a “add content” button which at present doesn’t do anything when clicked.
Umbraco version 8.5.4

Functionality should be that the user can still select to choose which item should be selected, and still have the ability to delete the item should they wish.

Many thanks,
Ric
![image](https://user-images.githubusercontent.com/20398415/78365741-732cc400-75b7-11ea-8abb-f9537129b92b.png)

![image](https://user-images.githubusercontent.com/20398415/78365754-76c04b00-75b7-11ea-97ef-d9aa964b9a1d.png)

Just to add - if the user leaves min items blank and max items 1 - then they can select and delete items.

**Comment by nul800sebastiaan** [comment]
Thanks @Ric-Carey - this is fixed in v8.6.0, I would suggest you upgrade when you get a chance!
