### ISSUE TITLE
Invalid character (ellipsis) in umbracoSettings.config causes YSOD during 8.6 upgrade

### ISSUE THREAD

**Issue by kinless** [umbraco/Umbraco-CMS#7894]
I was in the process of manually upgrading from v8.2.2 to v8.6.0 on Azure via FTP. After the usual copying/merging, when trying to load the upgrade screen, I got a YSOD with an object null reference exception. Looking at the logs revealed this error:

**Umbraco.Core.Exceptions.BootFailedException: Boot failed. ---> System.Configuration.ConfigurationErrorsException: Invalid character in the given encoding. Line 45, position 21. (D:\\home\\site\\wwwroot\\config\\umbracoSettings.config line 45) ---> System.Xml.XmlException: Invalid character in the given encoding. Line 45, position 21.**

Looking at the umbracoSettings.config file at the declared spot revealed this block of code to be the culprit:

`<a href="{0}/preview/?id={2}" class="umbraco-preview-badge__a open">
                    …
  </a>`

For whatever reason, the config file didn't like that ellipsis character. I changed it to standard three dots (...), which got rid of the error and allowed the upgrade process to begin, which was ultimately successful.

## Umbraco version

This issue was in Umbraco version: 8.6

Reproduction
------------

### Bug summary

Invalid character in umbracoSettings.config causes YSOD on the upgrade screen when attempting an upgrade to Umbraco 8.6.0

This happened on Windows 10 (1909) using Chrome 80.0.3987.149. I did not check any other browsers.
### Steps to reproduce

1. After upgrading files via manual copy, merge umbracoSettings.config to your project
2. Attempt to access the upgrade screen with your project URL
### Expected result

I expected the upgrade introduction screen when firing up the project URL

### Actual result

I received a YSOD null reference exception.

**Comment by nul800sebastiaan** [comment]
Hmm, it's XML, so I would think that this would be an expected error, you will need to encode it properly as a valide xml element, which would be: `$hellip;`.

**Comment by kinless** [comment]
That’s good to know, but the 8.6 package I downloaded contained the invalid character (I didn’t put it in there.) You may want to fix that for your 8.6.1 release.

**Comment by nul800sebastiaan** [comment]
@kinless Ah, I see! I also just noticed it's in a CDATA block so that would be valid XML anyway. So I am really not sure what happened, I've tried this upgrade, including updating the preview badge HTML but it worked just fine for me. 🤔

**Comment by kinless** [comment]
Maybe it was because I used WinMerge to update the existing config file (the invalid ellipsis was part of a new block of code that wasn’t in the 8.2.2 build) and the encoding got transposed somehow. In any case, probably better to just use the $hellip; encoding like you mentioned to avoid weird edge cases like that. Thanks for looking into it! Appreciate all your work.
