### ISSUE TITLE
dateHelper.getLocalDate is not a function

### ISSUE THREAD

**Issue by John-Blair** [umbraco/Umbraco-CMS#7897]
angular.module('umbraco.directives', ['umbraco.directives.editors', 'umbraco.directives.html', 'umbraco.directives.validation', 'ui.sortable']);

This needs to include 'umbraco.services' as a module to avoid the following error:

angular.js?cdv=3:15536 TypeError: dateHelper.getLocalDate is not a function
    at umbraco.directives.js?cdv=3:formatted:3758
    
in umbraco.directives.js at 

 function formatDatesToLocal() {
                    // get current backoffice user and format dates
                    userService.getCurrentUser().then(function(currentUser) {
                        scope.currentVariant.createDateFormatted = dateHelper.getLocalDate(scope.currentVariant.createDate, currentUser.locale, 'LLL');
                        scope.currentVariant.releaseDateFormatted = dateHelper.getLocalDate(scope.currentVariant.releaseDate, currentUser.locale, 'LLL');
                        scope.currentVariant.expireDateFormatted = dateHelper.getLocalDate(scope.currentVariant.expireDate, currentUser.locale, 'LLL');
                    });
                }

**Comment by abjerner** [comment]
Hi @John-Blair and thanks for reporting 👍 

Could you share some more details about when this is happening? Is it when using certain features of Umbraco?

What version of Umbraco are you using? In the most recent versions of Umbraco, line 3758 doesn't seem to contain anything related to this issue.

Umbraco contains a long list of directives, which in the source code lives in individual files. When Umbraco is released, the directives are merged into a single file, which is `umbraco.directives.js`.

So ideally if a directive is missing a resource, it should be handled in the specific directive, and not in `angular.module('umbraco.directives', ['umbraco.directives.editors', 'umbraco.directives.html', 'umbraco.directives.validation', 'ui.sortable']);` in the start of `umbraco.directives.js`.

**Comment by John-Blair** [comment]
hi @abjerner , 

I am using version 8.5.5.

I got this error when looking a content page with Chrome Dev Tools F12 open.

I have done some more research and I think it may be related to a collision with a service in my Back office section Plugin of the same name "dateHelper" - I have renamed the service and the error has gone away.  To help other plugin developers I was wondering if umbraco would consider adding a namespace to their exposed services and resources like "umb" to avoid random collisions with plugin developers?

Feel free to close this issue. Thanks.

**Comment by nul800sebastiaan** [comment]
@John-Blair Thanks for getting back to this one! Unfortunately, renaming the dateHelper now would be a breaking change for people already using it so we wouldn't want to do that at this point.

**Comment by John-Blair** [comment]
hi @nul800sebastiaan , Yes , I understand - I hate breaking changes myself. This is probably more of an angularjs issue - I found collisions like this when I loaded 2 of my plugins in the backofice as sections with slightly different implementations and they interfered with each other - I ended up namespacing them both - .....maybe the focus should be the other way round and update any plugin documentation you have to advise developers to namespace their plugins especially any exposed services,and resources,  Thanks.
