### ISSUE TITLE
language fallback not working in umbraco 8.6?

### ISSUE THREAD

**Issue by shearer3000** [umbraco/Umbraco-CMS#7901]
In an Umbraco 8 site using language variants, the IPublishedContent.value() method overload to specify a fallback does not appear to work.

Consider Umbraco with a default language of English and an additional language of Spanish. Spanish is configured to fallback to English.
A content page published in English (the default language) with a property (multinode tree picker) to pick ‘category’ nodes. 
On the website, the name of the ‘category’ nodes are displayed in English.
Now consider the page is also published in Spanish, but the ‘category’ property isn’t content loaded yet (NB Allow varying by culture set to true)

On the website, the expectation is the category name will fallback to the English name by template code of:
`var categoryIpcs = content.Value<IEnumerable<IPublishedContent>>(“myPropertyAlias”, fallback: Fallback.ToLanguage);`
(NB specifying the culture parameter with a value of “es” doesn’t seem to make a difference)

Actual result
The Value() method returns the IPublishedContent From the English language context (culture) but the Name property is Null (not the English name)

Expected result
The IPublishedContent Object has the English node name available. i.e. a ‘spanish’ node hasn’t been published so a “fallback” to the English node was used instead.

**Comment by nul800sebastiaan** [comment]
Please always specify the exact version of Umbraco you're working with so we can give you a better answer. 

I just gave this a test spin in 8.6.0. 

Doctype:
![image](https://user-images.githubusercontent.com/304656/78540316-474a5200-77f4-11ea-86a9-7d15fecb891d.png)

Picked an item in Dutch (NL):

![image](https://user-images.githubusercontent.com/304656/78540361-58935e80-77f4-11ea-8764-5ff8ac4c7e3a.png)

The item doesn't have anything filled in on the `testFallback` property in Dutch, but it has something in English:

![image](https://user-images.githubusercontent.com/304656/78540472-8082c200-77f4-11ea-83d0-7fb35e9c48e7.png)

Using the following template. 
Note: we're getting the fallbacks on properties instead of the whole content item because each property can have a fallback value.

```razor
@inherits Umbraco.Web.Mvc.UmbracoViewPage<ContentModels.TextPage>
@using ContentModels = Umbraco.Web.PublishedModels;
@{
	Layout = null;
	var multiPicker  = Model.Value<IEnumerable<IPublishedContent>>("multiPicker");
}

@foreach(var item in multiPicker) {
  <h2>@item.Name</h2>
  @(item.Value<string>("testFallBack", fallback: Fallback.ToLanguage))
}
```

This is where the fallback language comes up:

![image](https://user-images.githubusercontent.com/304656/78541096-64335500-77f5-11ea-9e87-67077de1a5dd.png)

**Comment by shearer3000** [comment]
hi Sebastiaan

The umbraco version is the latest, 8.6.0.
Sorry for the lack of screenshots, here they are now:

Language setup
![language-setup](https://user-images.githubusercontent.com/2433680/78595218-bfb91d80-789d-11ea-92a2-287517621d92.png)

English and Spanish content pages showing how the property is loaded
![nodes-en-es](https://user-images.githubusercontent.com/2433680/78595254-d2335700-789d-11ea-93bb-d4e40f2a61bd.png)

Template in English showing the category IPC
![property-english](https://user-images.githubusercontent.com/2433680/78595315-f131e900-789d-11ea-8a07-f54629949e95.png)

Template in Spanish showing the category IPC (**didn't fallback to English name**)
![property-spanish](https://user-images.githubusercontent.com/2433680/78595389-0a3a9a00-789e-11ea-87cd-047a0ccc0b2d.png)

and for completeness/reference, if i do publish the category in the spanish site and choose it on the content page property, then the template will show that name
![published-spanish](https://user-images.githubusercontent.com/2433680/78595494-30603a00-789e-11ea-9d28-a9dec0921b35.png)

thanks for helping with troubleshooting above, please take my word that i do put quite a bit of effort into verifying if an issue is a core one or our implementation before potentially taking up your time unnecessarily :)

regards,
Andrew

**Comment by nul800sebastiaan** [comment]
Hmm, I think I get it now, but how can you have a node that doesn't have a name and how do you expect to use it? If it's not published we wouldn't want to "leak" the saved, but not published name. For example, your editor might write: "I need to fill in this crappy field, otherwise it doesn't save" - you wouldn't want that as a fallback (nor would you want something more serious that is a secret until published to be a fallback text). Am I missing something?

**Comment by shearer3000** [comment]
No that’s correct, I’m definitely not wanting the website to show unpublished content (or content only saved).
What I was trying to do is tell my Spanish site to use the ‘category‘ content from the English site when there isn’t any content published in Spanish.
Granted, this could well me my understanding of how variants and “fallback” configuration is actually meant to work.

**Comment by shearer3000** [comment]
The only other thing I can add here is the following observation

If I set the Spanish language to have no fallback:
![spanish-lang](https://user-images.githubusercontent.com/2433680/78828530-f37c7a80-7a38-11ea-836a-661c98722ca2.png)
Then the method “Value<IEnumerable<IPublishedContent>>(alias, fallback: Fallback.ToLanguage)” returns null as expected.

But when I set the Spanish language To have a fallback to English, then the method starts returning the expected IPublishedContent, But the name property is still null.

**Comment by shearer3000** [comment]
Sorry to reopen this ticket but it appears Language fallback doesn’t work, so I wanted to re-explain the scenario with example screenshots.

Given the CMS has two languages (English and French) - NB English is the default, and French falls back to English:
![language-setup](https://user-images.githubusercontent.com/2433680/89588648-2bd17f80-d898-11ea-848c-66fb8850e9b1.png)


The homepage doctype has a property (multinode tree picker) for picking pods to show:
![english-content](https://user-images.githubusercontent.com/2433680/89588692-43a90380-d898-11ea-8692-214871ed1967.png)

Which display correctly on the website:
![english-website](https://user-images.githubusercontent.com/2433680/89588698-499ee480-d898-11ea-8bd0-10a286dabe50.png)

In contrast, the French page has no content picked for this property:
![french-content](https://user-images.githubusercontent.com/2433680/89588741-5b808780-d898-11ea-8249-84b255cdd8e0.png)

Given that the template integration is telling the extension method to use language fallback:
`var pods = Model.Value<IEnumerable<IPublishedContent>>("pods", fallback: Fallback.ToLanguage);`

It is therefore expected that the content nodes (IPCs) would be returned from the English language, but instead IPCs with no name or url property value are being returned:
![debug](https://user-images.githubusercontent.com/2433680/89588771-6affd080-d898-11ea-98bd-baa3610504f9.png)

So the french website doesn't show anything
![french-website](https://user-images.githubusercontent.com/2433680/89588781-6d622a80-d898-11ea-9061-93f01b2ca64d.png)
