### ISSUE TITLE
Multinode treepicker datatype: adding xpath query means picker will lose language context

### ISSUE THREAD

**Issue by shearer3000** [umbraco/Umbraco-CMS#7911]
reported for umbraco 8.6.0

In a site with language variants (English as default, and Spanish), I use a property (Multinode treepicker) to pick a 'category'.

In the Spanish site, the Multinode treepicker shows node names in that variant (spanish):
![treepicker-noxpath](https://user-images.githubusercontent.com/2433680/78734814-5587a200-799d-11ea-8ae2-462c70183275.png)

But if I use xpath to specify the starting location to a folder with the category nodes in it (i.e. the ones the content editor should pick from) then the treepicker only shows the name in English:
![treepicker-withxpath](https://user-images.githubusercontent.com/2433680/78734855-73550700-799d-11ea-8213-65347a8bca4d.png)

The xpath used is this case was: $site/contentFolder/categoryCollection

Expected result
Using xpath will change the starting context of the multimode treepicker, but the content tree is still in the context of the language of the main language selector

Actual result
Content tree in default language, not the language in the main language selector

**Comment by nul800sebastiaan** [comment]
Thanks, this will be fixed for the upcoming 8.7.0: https://github.com/umbraco/Umbraco-CMS/issues/7313

**Comment by shearer3000** [comment]
ok thanks 👍
