### ISSUE TITLE
Nesting nested content with Multi URL Picker - data not persisted

### ISSUE THREAD

**Issue by stefankip** [umbraco/Umbraco-CMS#7913]
Whenever I use a Nested Content datatype (with the Multi URL Picker inside the element type) as a property for a Nested Content element type (nesting NC), the data of the nested NC is not persisted when you save and publish a node.

Umbraco version 8.6.0

Example VS solution: 
[Umbraco 8.6 - NC nested test.zip](https://github.com/umbraco/Umbraco-CMS/files/4450654/Umbraco.8.6.-.NC.nested.test.zip)

Login: admin@admin.com / adminadmin

On the Home node I added an example NC. Try to add items to the nested NC and Save. Refresh the page and notice the data isn't persisted.

**Comment by stefankip** [comment]
I'm lost. I can't even seem to persist data (element with only a textstring and RTE property) without nesting a nested content... What the heck is going on? I'm trying to build a website which relies heavily on NC, but it's all failing so bad :-(

**Comment by stefankip** [comment]
It's getting even better; I disabled all custom composers/components I had in place and it suddenly worked. Then started to enable 1 by 1 and testing the persistence after each one and it kept working, even with all composers/components enabled again.
I'm really, really lost here...

**Comment by nul800sebastiaan** [comment]
I hate to do this, but.. I can't repro this problem on a clean install and if you can't reproduce it any more either then there's not much we can do. The example solution you attached works for me (but also doesn't include your custom composers/components). Maybe it's a browser cache thing from an older version? 🤷 

If you can repro somehow then drop a comment here!

**Comment by stefankip** [comment]
Wait, you weren't able to reproduce the issue with the steps provided in the TS?
Maybe it is related to browser caching then? I say the values get posted to the `PostSave` endpoint and inside the response the value was null again, so I really thought it is a back-end issue.

**Comment by nul800sebastiaan** [comment]
Yeah it saved my additional nested nested content items just fine..

**Comment by stefankip** [comment]
@nul800sebastiaan sorry for the late reply. I just tried to create a NC property in a project and the data didn't get persisted again. Changing the CD version number and recycling the appPool made it work again.
Is this 'fixable' one way or another?
