### ISSUE TITLE
Html.GetGridHtml() does not support  IPublishedElement

### ISSUE THREAD

**Issue by robertjf** [umbraco/Umbraco-CMS#7916]
Html.GetGridHtml() only supports IPublishedContent, so when using Grid Layout in a Nested Content element, I had to write my own extension.

## Umbraco version

I am seeing this issue on Umbraco version: 8.6.0

I'm going to create a PR to resolve this 👍

**Comment by nul800sebastiaan** [comment]
Fixed in https://github.com/umbraco/Umbraco-CMS/pull/7917
