### ISSUE TITLE
Include the functionality of the tour editor package in V8. 

### ISSUE THREAD

**Issue by melvinvanrookhuizen** [umbraco/Umbraco-CMS#7921]
Provide Tour Editor Package functionality out-of-the-box for all V8 so editors/agency can build their own tours in an easy way instead of code stuff. The tours come included in the CMS, so you must consider them essential for users. Logically, the editor functionality should also be.

And -wow! :-) - we could have some experienced editors create an entire manual in Tours. And they could be updated every time a new update ships, so its always up-to-date. This way new - potential- users would always have an help in the place its most handy.

I am available for help on testing (already suggested Dawoe to help convert the package to V8). Development hrs can be arranged if needed.

**Comment by nul800sebastiaan** [comment]
Hi @melvinvanrookhuizen, thanks for this feature request. Currently we are happy with this being a package and are not ready to take on the maintenance of this code in the core product. Note that we might reconsider this in the future.

Thanks again and good luck converting to v8! 👍
