### ISSUE TITLE
Starter kit doesn't show "insert macros" button in RTE by default

### ISSUE THREAD

**Issue by PeteDuncanson** [umbraco/Umbraco-CMS#7941]
Had to use the starter kit to test out a macro today but noticed that the default starter kit doesn't include the option to include a macro in a RTE.

Now this might be done on purpose to keep the surface area of "learning" to a minimum but it does raise the issue of discoverability. If you don't see it there you don't know it exists when its big stuff like that. Pondering if this might be helping with the seeming demise of this handy feature in the community?

This was on a v7.6.1 site but I don't think the starter kit has been touched in ages but might not be an issue in v8 (I haven't got a v8 site running to test it on as yet).

Probably opening up a can of worms about the color of bike sheds but wanted to open a wider chat about how could/should we sign post new users to the features of Umbraco through the most common entry point which is the starter kit? This issue might be killed off with a quick "we know the starter kit needs work and its coming" reply but if so how about we create somewhere to store tip-bits like this so the new starter includes them or at least has some discussion about them...guess a RFC of some sort but they always seem to be more "we are doing X, shout now or lose the chance" rather than "what should we do about X" :shrug:

**Comment by PeteDuncanson** [comment]
Updated the title to be more descriptive

**Comment by nul800sebastiaan** [comment]
Thanks @PeteDuncanson - I will indeed close this issue with a "we know the starter kit needs work and its coming". 😅 

We're currently not ready to work on this but when we are (and this is going to take a while) then we'll make sure to involve community in this process. 

RFCs are always about: after doing our research we are *thinking* of doing this, please provide feedback to make sure we're not forgetting about anything. 
We are very happy to change our mind, reject the RFC as it stands and start over, if the feedback warrants it.
