### ISSUE TITLE
Hide preview button if no template assigned

### ISSUE THREAD

**Issue by colin-tactuum** [umbraco/Umbraco-CMS#7962]
It would be good if the preview button was not shown on nodes where there is no template assigned or for there to be an option of disabling the preview button for a specific document type.

**Comment by nul800sebastiaan** [comment]
Thanks @colin-tactuum - at a glance this does make sense but once you dig into this there's a few ways that nodes could get a template even if it's not defined on a document type. Right now, we're happy with how the preview button works and are not planning any changes in the near future. For an in depth discussion, please have a look at: https://github.com/umbraco/Umbraco-CMS/pull/2878
