### ISSUE TITLE
SqlMainDomLock when configured via appSettings cannot be used unless umbraco is installed

### ISSUE THREAD

**Issue by Shazwazza** [umbraco/Umbraco-CMS#7967]
This is a setting for running Umbraco on Azure webapps but currently in order to use this setting Umbraco needs to first be installed otherwise a YSOD will occur on startup. 

Should be relatively easy to check the runtime state within SqlMainDomLock and ignore any database connections if the db is not available. 

---
_This item has been added to our backlog [AB#6274](https://dev.azure.com/umbraco/243e7927-03b2-44e2-908f-d4ac7ea5daaa/_workitems/edit/6274)_

**Comment by nul800sebastiaan** [comment]
Cherry picked for 8.6.4 in a88a5a0caec7a6c01bc4edd8fa56437e7a42f6ce
