### ISSUE TITLE
RTE css selectors are not properly displayed

### ISSUE THREAD

**Issue by skartknet** [umbraco/Umbraco-CMS#7976]
The CSS selectors created in the linked stylesheet of the RTE are not properly rendered when you enter more than 2.

## Umbraco version

I am seeing this issue on Umbraco version: 8.6

Reproduction
------------

If you're filing a bug, please describe how to reproduce it. Include as much
relevant information as possible, such as:

### Bug summary
The CSS selectors created in the linked stylesheet of the RTE are not properly rendered when you enter more than 2. The css selectors are not split correctly.

### Steps to reproduce

Create a rule in a RTE stylesheet with a selector as 'h5.text-extra-dark-gray.alt-font.font-weight-600'
and no styles.

Enter some text in an RTE and assign the previous rule from the Formats dropdown.

### Expected result

I would expect a tag displayed as:
`<h5 class="text-extra-dark-gray alt-font font-weight-600">some text</h5>`

### Actual result

The rendered element is:
`<h5 class="text-extra-dark-gray alt-font.font-weight-600">some text</h5>`

You can see that the third rule is not split and the dot is still there.

**Comment by nul800sebastiaan** [comment]
Hey there @skartknet - this seems like a bug, I believe that this should be possible.

I'll put this up for grabs with a caveat that debugging how Tiny works with these styles might be quite an "interesting" path to go down. 🙈

**Comment by kjac** [comment]
Oh nice one! I can repro, fix incoming.

**Comment by kjac** [comment]
PR in #8164

**Comment by nul800sebastiaan** [comment]
Fixed in https://github.com/umbraco/Umbraco-CMS/pull/8164
