### ISSUE TITLE
Umbraco 8: unpublished content being returned by IPC Value method

### ISSUE THREAD

**Issue by shearer3000** [umbraco/Umbraco-CMS#7979]
Reported for umbraco 8.6.0

I have noticed a situation where an “incomplete” IPublishedContent object is being returned for content that is in fact **unpublished**.

To simulate this issue, I have set up a new umbraco installation with 3 content pages. The page doctype only has one property, a “multinode treepicker” for the content editor to specify a related page. 

### Example 1
the “dolor” page has the “ipsum” page picked (and the picked page is published)
![dolor-cms](https://user-images.githubusercontent.com/2433680/79703016-16424500-82fd-11ea-8734-483f280f7da2.png)

The website shows the name of the related page:
![dolor-website](https://user-images.githubusercontent.com/2433680/79703018-1b9f8f80-82fd-11ea-837f-fd4df3f0a711.png)
![integration](https://user-images.githubusercontent.com/2433680/79703377-8f429c00-82ff-11ea-836c-b26b728dc952.png)

### Example 2
The “ipsum” page has the “lorem” page picked (and the picked page is unpublished)
![ipsum-cms](https://user-images.githubusercontent.com/2433680/79703342-4e4a8780-82ff-11ea-82fd-8ad256b99e52.png)
In this case the property has an IPublishedContent object representing the picked page **with a “Name” of null**:
![ipublishedcontent](https://user-images.githubusercontent.com/2433680/79703344-56a2c280-82ff-11ea-8ca1-c5da96f403b0.png)
![ipsum-website](https://user-images.githubusercontent.com/2433680/79703352-66baa200-82ff-11ea-8acc-6747b6cfbb03.png)

**Expected**
The property value should have a value of null as the picked page is unpublished

**Actual**
The property value has an IPublishedContent object but with no value for Name.

**Comment by shearer3000** [comment]
just checked on 8.6.1 and its the same issue

**Comment by nul800sebastiaan** [comment]
Hmm, unfortunately that is not something I can reproduce.. just asking for a picked item in a default Umbraco setup will give you a `null` for the picked item.

![image](https://user-images.githubusercontent.com/304656/80083586-0ffad580-8556-11ea-9b3e-b1b5a7007d9d.png)

I must assume there's something going on with some custom code there 🙈

**Comment by shearer3000** [comment]
Hi, hmm ok on the positive side it is good to hear I should be expecting null and that I’m not going crazy 😆

I was using a fresh install with literally only that little snippet of code above so not sure how I could go too far wrong, will have another try 😁

Thx

**Comment by shearer3000** [comment]
Ps did your trial use the .Value() extension method?

**Comment by shearer3000** [comment]
Hi again Sebastiaan – I’ve been trying to replicate this but now I see the same results as you i.e. null for the picked IPublishedContent item. Apologies for this, I’m really not sure what I did to my install to make it return an 'incomplete IPublishedContent' object for the unpublished content, but it seems to be rectified now 😊
