### ISSUE TITLE
Accessibility during docType Property Settings creation

### ISSUE THREAD

**Issue by craigs100** [umbraco/Umbraco-CMS#7985]
In V7 you could rapidly fill in docType property settings with just the keyboard and clearly tab around the slideout panels. Now the taborder gets lost or focus isn't clear resulting in loss of efficiency.

I am seeing this issue on Umbraco version: 8.6.0

Reproduction
------------

### Bug summary

Attempt to add a docType property from the keyboard. From the point at which the property setting name is entered it's possible to tab to enter the description and add the editor. Once the editor is added, the next tab doesn't necessarily take you to the next logical element in the sequence to complete the settings and save the property. In some cases it jumps out to the main Umbraco Menu (Content, etc).

### Steps to reproduce

Add a Property Setting, focus will then be on the "Enter a name" field.
Enter a property name and tab twice to put the focus on "Enter a description". 
Enter a description and tab to "Add editor" and notice the focus highlight follows you.
Hit "Enter" and enter "string" into the search box which now has focus.
Tab twice to select the "Textstring" editor and hit "Enter"
The next time you hit "Enter" nothing happens.
If you hit "Tab" then the focus moves to the "Content" main menu 

### Expected result

Once the Editor was set, the focus should have been on the "Validation" element for "Field is mandatory", then into the "Custom validation" dropdown and then "Close" followed by "Submit".

Once the slideout panel closes, the focus should then be on the next "Add property" link in the group you were working in.

### Actual result
Once the Editor is set then on the next "Tab" hit the focus moves to the "Content" main menu

**Comment by nul800sebastiaan** [comment]
Hmmm, that is indeed not ideal, there's some updates for that coming in v8.7 to lock you into the slide out panel, so that you don't end up in an unrelated part of the UI, this is what it looks like, I've only used the keyboard in this gif:

![7985](https://user-images.githubusercontent.com/304656/80085256-3e79b000-8558-11ea-9b4d-5aa189b6e514.gif)


I'll close this as fixed in 8.7!
