### ISSUE TITLE
Possibility to use the Umbraco.Web.Editors.UsersController class outside users section

### ISSUE THREAD

**Issue by FransdeJong** [umbraco/Umbraco-CMS#7997]
We have a usecase where we want to invite users outside the users section and set some basic settings on the user like startnodes for content and media and roles.

This would be possible out of the box if it werent for the     `[UmbracoApplicationAuthorize(Constants.Applications.Users)]` attribute. To do what we want to do right now we have to copy the entire class.

Is there a reason for the class to be restricted to the users section? Can the attribute be removed?

**Comment by nul800sebastiaan** [comment]
Which "entire class" are we talking about please?

Good that you found a workaround for now! I'm sure there's a good reason, one being security :-) 

But I don't know exactly if there's a way to make this secure without the attribute. Remember you're giving people the ability to invite anyone they want into the backoffice with the same or user rights that they already have, or fewer rights, there will need to be a lot of trust involved.

**Comment by FransdeJong** [comment]
The one in the title ;)

https://github.com/umbraco/Umbraco-CMS/blob/v8/contrib/src/Umbraco.Web/Editors/UsersController.cs

**Comment by Shazwazza** [comment]
The UsersController is specific to the Users section

> Is there a reason for the class to be restricted to the users section? Can the attribute be removed?

There is absolutely and it cannot be removed. Without it it would mean that every user can just go change/remove/add/update password/change groups/etc... of every other user basically making every user an admin of each other and bypassing security.

I would very very highly recommend *not* copying this entire controller and removing that attribute as this will mean you are allowing every user of Umbraco to have the ability to be an admin of every other user. 

If you want specific functionality like inviting users outside of the user's area then then you will need to write this yourself but you'll definitely want to be sure you aren't exposing security risks.

**Comment by FransdeJong** [comment]
Hi Shannon,

Thanks for the comment.

I have a few followup questions:

> ... basically making every user an admin of each other and bypassing security.
This is not entirely true right? If I grant access to the users section for a editor this editor can only see users of the same or lesser roles then himself. So there must be a extra security check.

I get that when this property is removed the methods will be available to everyone.

There are 2 issues I'm running into with this project.

1. For this specific issue I need the exact same usermanagement as we have in the user section for all users but than in a content app and confined to the startnode of that user

2. I want to reuse the umbraco user invite flow but I need to change some settings. The user that is inviting the new user must not be able to select the usergroup. Instead I want to set startnodes and role based on the current user and the node he is on. I can create the user, set everything I need and than I want to use the PostInviteUser method and let Umbraco handle the rest.

I've looked at the attribute in detail and the attribute doesn't specify the location from where the methods is used but if the section is present on the current logged in user right?

So if I create a specific usergroup that has access to the users section than I should be able to call the methods in the controller from the content section

The only thing I have to do after that is visually hide the users section for those specific user groups.

Would that be the prefered way?

**Comment by Shazwazza** [comment]
If a user is part of a group that has access to the user's section, then they have access to the users section and can modify other users. There are further authorization checks on various actions in that controller that do other checks, for example only an admin user can edit other admin users. But if a user is part of a user group that has access to the user section, then they have access to edit other users, though if they are not an admin they cannot edit admin users.

**Comment by FransdeJong** [comment]
If I hide the users section the security risk would be minimal. If a user is allowed in the backoffice and is allowed to edit users and they have extensive knowledge of Umbraco and a way to call api's than they could change other users but not the admin.

If they did that there is a timestamp and a username tied to that action so we can find out what happened.

That doesn't sound that bad right?

The other option would be to copy the controller, remove the attribute and create my own security attribute but than I have to maintain Umbraco code.

Seems there are drawbacks for both options

**Comment by Shazwazza** [comment]
> That doesn't sound that bad right?

That really depends on your needs and maybe it would be fine for your installation and users but that would be your call. We cannot change the security of this controller because this would not be acceptable for other users. 

You are able to create your own controller with whatever security attributes you would like and you can wrap the UsersController methods by just creating a new UsersController from within your controller and return results from it's methods. Else you might be able to use the `OverrideAuthorizationAttribute` class https://docs.microsoft.com/en-us/previous-versions/aspnet/dn308862(v%3Dvs.118) to override the upstream filters.

**Comment by FransdeJong** [comment]
Thanks for the help shannon. I get that this isn't a thing you would want to change in core.
