### ISSUE TITLE
Umbraco Upgrade to 8.6.1 issue

### ISSUE THREAD

**Issue by ifrahim** [umbraco/Umbraco-CMS#7999]
Hi, 
I have updated my Umbraco CMS (v 8.5.5) to latest v8.6.1 today. Which has crashed my project. 
When I run project after upgrade, I am getting "BootFailedException". 

I took these steps (as a standard process) to update CMS:
1.
- Update UmbracoCMS from Nuget package Manager
- Rebuild solution
- Restart IIS website
- Build Failed
- Ran project
- Build failed
2. 
- Update UmbracoCMS from package Manager console
- Rebuild solution
- Restart IIS website
- Build Failed
- Ran project
- Build failed
3. 
- Update UmbracoCMS and Installed Umbraco.ModelsBuilder
- Rebuild solution
- Restart IIS website
- Build Failed
- Ran project
- Build failed
4.
- Deleted Temp folder
- Excluded App_Data/Models folder 
- Update UmbracoCMS from package Manager console
- Rebuild solution
- Restart IIS website
- Build Failed
- Ran project
- Build failed

I have looked into other related posts. One of which said to install/update Umbraco.ModelsBuilder.Api which I also did but it was a failure as well.

![image](https://user-images.githubusercontent.com/5398591/79985252-395a2980-84a2-11ea-83ed-00ed8fed2d63.png)

**Comment by nul800sebastiaan** [comment]
I'll close this with the recommendation to check the blog post and then follow up on the forum if it's still a problem.
