### ISSUE TITLE
RTE obscuring 'insert' dialogues whilst in Fullscreen

### ISSUE THREAD

**Issue by OwainJ** [umbraco/Umbraco-CMS#8001]
This issue has been raised by a few of our clients.

The fullscreen RTE covers the Media Picker, insert link, embed and insert macro dialogue, requiring the user to exit fullscreen to see the dialogue.

![rte fullscreen import image](https://user-images.githubusercontent.com/17008780/80006601-03766e80-84bd-11ea-8260-c87d6def161b.gif)

## Umbraco version
I am seeing this issue on Umbraco version: 8.6.1

Reproduction
------------
### Steps to reproduce
- Create a content node with an RTE property
- Make the RTE fullscreen
- Click either 'insert link', 'media picker', 'embed' or 'insert macro' on the RTE toolbar

### Expected result
With the RTE in fullscreen, the 'insert link'/'media picker'/'embed'/'insert macro' dialogues should open over the RTE. 

### Actual result
The 'insert link'/'media picker'/'embed'/'insert macro' dialogues open behind the fullscreen RTE, requiring the user to close the RTE to see and use the dialogues.

Feedback from our clients is that having to exit fullscreen to see the dialogues is annoying their content editors.

**Comment by nul800sebastiaan** [comment]
Thanks @OwainJ - this has been fixed and will be available in v8.7.0: https://github.com/umbraco/Umbraco-CMS/issues/7576
