### ISSUE TITLE
Language files missing for tiny

### ISSUE THREAD

**Issue by lars-erik** [umbraco/Umbraco-CMS#8018]
Running the starter kit on Umbraco/contrib currently provokes an exception with tinymce.

![image](https://user-images.githubusercontent.com/350918/80370526-97b34d80-8890-11ea-830b-c6af140550f9.png)

Seems to be a result of updating the language files last year.  
https://github.com/umbraco/Umbraco-CMS/commit/59ba68dfd0767635290cc1ed51bd1fe52a57d471

Dunno which should be fixed. Language files, starter kit or user default language?

**Comment by bjarnef** [comment]
I guess https://github.com/umbraco/Umbraco-CMS/pull/8002 fixes this issue :)

**Comment by lars-erik** [comment]
And here I searched the prs for en-us and all. Need to fix my github search skills. 😆

**Comment by lars-erik** [comment]
There's still the issue of the missing en.js file, but at least the default user language isn't broken. Closing this, then.
