### ISSUE TITLE
Table toolbar in RTE appears over last row of table

### ISSUE THREAD

**Issue by russellshome** [umbraco/Umbraco-CMS#8024]
Sits over the text in the last row of the table, which means you can’t see what you are doing under the toolbar.

## Umbraco version

I am seeing this issue on Umbraco version: 8.5.4
And 7.15.4

Also refer to: https://github.com/umbraco/Umbraco-CMS/issues/5926

Reproduction
------------

### Bug summary

When entering content into a table in the rich text editor the table toolbar appears over the top of text in the bottom row.

### Specifics

Problem appears in IE11 and Chrome
![DisplayFile](https://user-images.githubusercontent.com/8239408/80418071-ec0b0b80-892a-11ea-9955-8c41c4ab9ae9.png)

### Steps to reproduce

In a RTE on a page add a table and start to add content in a table cell

### Expected result

toolbar should appear under the bottom of the table

### Actual result

toolbar appears over text in the table

**Comment by nul800sebastiaan** [comment]
Thanks, this duplicates #5926
