### ISSUE TITLE
Sorting doesnt work for a section with 100+ children

### ISSUE THREAD

**Issue by Vinod-aimleap** [umbraco/Umbraco-CMS#8028]
A brief description of the issue goes here.

Hi Team,
Umbraco sorting doesnt work for a section with 100+ children.

## Umbraco version

I am seeing this issue on Umbraco version: 8.6 

Reproduction
------------

If you're filing a bug, please describe how to reproduce it. Include as much
relevant information as possible, such as:

Create a section and add 100+ children and try to sort. The sort functionality keeps loading

**Comment by nul800sebastiaan** [comment]
Thanks @Vinod-aimleap - I am unable to reproduce this, it takes a while to sort everything for sure but it does complete. Make sure to check the console/network tab for errros, as you can see in my example, the request completed successfully.

![8028](https://user-images.githubusercontent.com/304656/81559556-ecc28980-938f-11ea-9cfd-42c4224aef46.gif)
