### ISSUE TITLE
Images uploaded through the Media Picker aren't selectable when set to 'pick images only'

### ISSUE THREAD

**Issue by junkin77** [umbraco/Umbraco-CMS#8041]
When the media picker is set to 'Pick only images' then the newly uploaded images can't be selected. Also, all newly uploaded images don't display the thumbnail image in the picker. If you then view the image under media the thumbnail image does display (see attached video).

## Umbraco version

I am seeing this issue on Umbraco version: Umbraco Cloud 8.6.1. We didn't see this before upgrading to 8.6 

Reproduction
------------

On a content page that uses the media picker try to upload a new image. When uploaded the image thumbnail doesn't display, it displays the image placeholder instead. If the Media picker is set to pick images only' then the newly uploaded image can't be selected. 

I'm using Chrome Version 81.0.4044.122

![umbraco-hascontentnodes-404v3](https://user-images.githubusercontent.com/25978840/80952480-a39f9200-8df1-11ea-8ea0-5e31edb0f59e.gif)

**Comment by deMD** [comment]
Seems like the same issue as #6441 

Do you use a custom media folder by any chance?

**Comment by junkin77** [comment]
We haven't used a custom folder, the files are stored under the default media folder. Does seem like the same, or related issue though. Everything worked fine before upgrade from 8.5.5 to 8.6.1

**Comment by nul800sebastiaan** [comment]
Thanks @junkin77, Like with issue #8042 - this works fine in a fresh install of 8.6.1 and I believe something went wrong with your upgrade somehwere. I would encourage you to reach out to Cloud support for some more help here!
