### ISSUE TITLE
Missing localization text for custom audit events.

### ISSUE THREAD

**Issue by KevinJump** [umbraco/Umbraco-CMS#8050]
Custom audit events are missing a label and text in the back end 

![image](https://user-images.githubusercontent.com/431231/80863111-d7ec4480-8c71-11ea-87c6-cc4126e323b0.png)

Ideally you should be able to set custom label / colour for custom events, but a quick fix is to add the labels in the Lang files so it shows parameters like the other audit events do.

**Comment by nul800sebastiaan** [comment]
Fixed in #8051
