### ISSUE TITLE
Unable to select a Content node after deleting associated Document Type 

### ISSUE THREAD

**Issue by GabrielUleia** [umbraco/Umbraco-CMS#8056]
A brief description of the issue goes here.

I create a Document Type with Template. Then I create a Content node based on this document type. The pageis working fine. If I delete the Document Type is OK, but when I want to select the content node asociated with it or the three dotsin the right I get errors. 

## Umbraco version

I am seeing this issue on Umbraco version: 8.6.1 

Reproduction
------------

### Bug summary
Unable to manipulate a Content Node after deletion of the associated Document Type 

### Specifics
It happens on a local installation of Umbraco 8.6.1 on a local Windows 10 system. 
Gooogle Chrome browser. 
In the screenshot attached, the first red message corespond at the click on the content text. The second red message correspond to the click on the three dots. 

### Steps to reproduce

1. Create a Document Type with Template. 
2. Then I create a Content node based on this document type. 
3. delete the Document Type
4. Try to select the content node asociated with it or to click on the three dots in the right of it

### Expected result
- Delete also the contet type associated 
or
- Give the possiblity to delete it from the content menu

### Actual result
The content node cannot be manipulated any more. 

![BugWhenDeleteDocumentType](https://user-images.githubusercontent.com/52895689/80919544-cc307900-8d6a-11ea-8973-8e5c9ff56a1e.png)

**Comment by nul800sebastiaan** [comment]
Hmm, strange, content nodes will be delete when you delete a document type, you even have to confirm this when deleting a document type:

![image](https://user-images.githubusercontent.com/304656/81568538-33b77b80-939e-11ea-813b-8d326a728933.png)

If you can reproduce somehow that the content items don't get deleted then we should look into why that it, but in a test I just did the content items are gone (I did have to refresh the tree to see that they were gone).
