### ISSUE TITLE
User gets 401 Unauthorized if no root  start node is set

### ISSUE THREAD

**Issue by elit0451** [umbraco/Umbraco-CMS#8062]
When a user with access to the Content section (apart from the administrator) clicks on the 3 dots next to the tree root name (**Content**) to check if there is a root node that can be created, gets thrown out of the back-office with **401 Unauthorized** error. This is happening because no Document type was set as a start root node. After that, if the user tries to login again, the Unauthorized error keeps preventing the login and the cache and cookies need to be cleared for a successful login.

## Umbraco version

Tested on the latest v8/dev branch, also on 8.6.1
This is not a problem in v7.

### Bug summary
Getting 401 because there isn't any start root node set. Can't login after getting the error.

### Steps to reproduce
1. Install a clean version of Umbraco.
2. Create a user that has the default 'Writer' or 'Editor' group.
3. Login as the user.
4. Click on the 3 dots next to the tree root name (Content).
5. After being thrown out of the back-office, try to login again.

### Expected result
No Unauthorized error. The result should be similar to what we get with an Admin user in the same scenario. We should see a column that opens with the text:
> Create an item under Content
There are no allowed document types available...

### Actual result
A 401 Unauthorized error when clicking on the 3 dots. Can't login again without clearing the cache and cookies.

**Comment by nathanwoulfe** [comment]
@elit0451 I've checked this on v8/contrib, no longer seems to be an issue. Will close this and my associated PR.
