### ISSUE TITLE
DocumentTypeEditor does not update preview of property-editor when changed

### ISSUE THREAD

**Issue by nielslyngsoe** [umbraco/Umbraco-CMS#8068]
When changing a properties data-type, the preview of the property-editor is not updated to reflect the new property-editor.

**Comment by kjac** [comment]
This has annoyed me as well... I'll have a look at a fix 👍

**Comment by kjac** [comment]
PR in #8104

**Comment by nul800sebastiaan** [comment]
Fixed in https://github.com/umbraco/Umbraco-CMS/pull/8104
