### ISSUE TITLE
Label for Decimal Property Editor does not put focus to input field.

### ISSUE THREAD

**Issue by nielslyngsoe** [umbraco/Umbraco-CMS#8077]
When clicking the label for the Decimal Property Editor it does not put focus to the input field.

![image](https://user-images.githubusercontent.com/6791648/81285132-54f72f80-905f-11ea-954f-da8966b0b4de.png)

**Comment by bjarnef** [comment]
Fixes in https://github.com/umbraco/Umbraco-CMS/pull/8078
