### ISSUE TITLE
Textarea character limit trimming trailing spaces

### ISSUE THREAD

**Issue by alanwthom** [umbraco/Umbraco-CMS#8082]
When adding a character limit to the textarea property, the character count only updates when the last character of the input is not a space.

## Umbraco version

I'd originally experienced this on v8.5.2, but have also been able to reproduce on v8.6.1.

Reproduction
------------

1. Install Umbraco 8.6.1 with starter kit
2. Update textarea datatype to have a character limit of 300
3. Go to Home node and update description field with something like "      foo"
4. Character limit does not update when space characters are added, only when a non-space character is the last character in the input

### Bug summary

Having looked at the source, it seems like the textarea input is missing an `ng-trim="false"` attribute. This issue doesn't look to apply to the textstring property as it already has an `ng-trim="false"` attribute. I'll try and submit a PR this afternoon. 🤞

**Comment by nul800sebastiaan** [comment]
Fixed in https://github.com/umbraco/Umbraco-CMS/pull/8083
