### ISSUE TITLE
Do we really need the newsletter pop inside the CMS?

### ISSUE THREAD

**Issue by dalyUSN** [umbraco/Umbraco-CMS#8084]
Hi there

Found this a little strange. Last few times we've spun up a fresh install of Umbraco CMS we've been prompted to signup for the mailing list after installation through a popup/overlay... and so have our content editors.

When someone installs they are asked to signup for the mailing list during setup - I think that's fair. Once the CMS is installed, we are now presented with an overlay prompting us to, again, signup for the mailing list... is this really necessary? Keep in mind that we only 2 minutes previously said yes/no to signing up and have then been shown the Tour overlay. To be presented with this additional prompt to sign up is a little overkill. 

<img width="1384" alt="Screenshot 2020-05-08 at 16 56 13" src="https://user-images.githubusercontent.com/24275922/81425094-d4176100-914e-11ea-925b-fcdee30c0104.png">

Not only that but every user who is added to the CMS is given this sign up too. Thus hindering our content editors ability to use the CMS. 

There could be a few options for a solution: 

a) If an email address assigned to a user is already in the mailing list then do not show.
b) Only show for the admin user who has installed the CMS. 
c) Only show for the admin user who has installed the CMS and provide an option to turn on/off for each additional user when you add them to the CMS.

It would be nice to know the thinking behind adding this into the CMS and thoughts for a better solution.

Sorry if this has already been discussed but I was unable to find any other post on it.

Thanks
Paul

**Comment by nul800sebastiaan** [comment]
While I am unfortunately not quite aware about the decision process of adding this additional question, I generally know that we wanted to be able to reach new Umbraco users with relevant content for them, on an opt-in basis. Further, we'd like to talk to more than just the people who are implementing Umbraco, we would love to send relevant content to all types of users in Umbraco if they're interested.

While we do ask for the newsletter preference during install, this is something that is easily skipped and especially on Umbraco Cloud nobody will ever see that. Additionally, we're working on making unattended installs a reality, so we'll again not get a chance to highlight why you might want to receive some updates from us.

And remember, not many people do multiple fresh installs per day, so you're in a luxury situation of getting to see that modal a bit more than the average Umbraco dev! 😉

Of course if you never want to see this step ever again you can opt out with a bit of code to filter out the specific tour: 

```
using System.Text.RegularExpressions;
using Umbraco.Core.Composing;
using Umbraco.Web.Tour;
namespace Umbraco.Web.UI
{
    [RuntimeLevel(MinLevel = RuntimeLevel.Run)]
    public class DisableEmailMarketing : IUserComposer
    {
        public void Compose(Composition composition)
        {
            composition.TourFilters()
                .AddFilter(new BackOfficeTourFilter(pluginName: null, tourFileName: null, tourAlias: new Regex("^umbEmailMarketing", RegexOptions.IgnoreCase)));
        }
    }
}
```
