### ISSUE TITLE
Login failed issue umbraco upgrade

### ISSUE THREAD

**Issue by HarjotMann** [umbraco/Umbraco-CMS#8086]
I am upgrading my site's umbraco version from 7.3.2 to 8.6.1, the websites is pretty simple. I used nuget to update all the packages. There are no build errors in VS. But every time it gets stuck here at the login screen. It is not upgrading the db. There are some errors in console. Please help
https://pasteboard.co/J7MTqNz.png
https://pasteboard.co/J7MTJsD.png

**Comment by nul800sebastiaan** [comment]
Hi there @HarjotMann  - this sounds like an excellent question for the forums where our friendly community can help you find the best solution for your requirements. 
Make sure to head on over to https://our.umbraco.com and ask follow up questions there! 👍

**Comment by nul800sebastiaan** [comment]
I forgot to add, there's a few hints here in this comment that might help: 

https://github.com/umbraco/Umbraco-CMS/pull/6002#issuecomment-591344554 

Specifically, make sure you get the `UsersMembershipProvider` correct.
