### ISSUE TITLE
Replacement of angularJS forEach to native forEach does not handle null or undefined

### ISSUE THREAD

**Issue by nielslyngsoe** [umbraco/Umbraco-CMS#8087]
After getting rid of the angularJS forEach, replaced by native forEach we now see issues where native forEach fails cause the given object is null or undefined.

the issue arrived in this PR: https://github.com/umbraco/Umbraco-CMS/pull/7928

---
_This item has been added to our backlog [AB#6618](https://dev.azure.com/umbraco/243e7927-03b2-44e2-908f-d4ac7ea5daaa/_workitems/edit/6618)_

**Comment by nielslyngsoe** [comment]
I'm working on a PR.

**Comment by bjarnef** [comment]
@nielslyngsoe have a look at this :)
https://docs.angularjs.org/api/ng/function/angular.forEach

> Unlike ES262's Array.prototype.forEach, providing 'undefined' or 'null' values for obj will not throw a TypeError, but rather just return the value provided.

**Comment by nielslyngsoe** [comment]
@bjarnef thank you, I did look at that.. working on an implementation that has the if(obj) {} wrapped around the native forEach. Cause the angularJS implementation is quite massive.

**Comment by nielslyngsoe** [comment]
PR https://github.com/umbraco/Umbraco-CMS/pull/8088
