### ISSUE TITLE
Add support for changing CustomType and Precision to DbModel annotations

### ISSUE THREAD

**Issue by LennardF1989** [umbraco/Umbraco-CMS#8096]
Right now pretty much all fields inside the ColumnDefinition model are covered by an annotation. See https://github.com/umbraco/Umbraco-CMS/blob/2f978e96d4fbf84d8786c3245566c8800916a74b/src/Umbraco.Core/Persistence/DatabaseModelDefinitions/ColumnDefinition.cs

However, neither CustomType or Precision can be influenced using annotations as can be observed in this piece of code.
https://github.com/umbraco/Umbraco-CMS/blob/2f978e96d4fbf84d8786c3245566c8800916a74b/src/Umbraco.Core/Persistence/DatabaseModelDefinitions/DefinitionFactory.cs#L62

This makes creating DbModels with decimals that need a specific precision really annoying in migrations. You either have to create the table, then manually alter all columns, or create the full table definition by hand.

Please add an annotation:
- to control the CustomType of the ColumnDefinition model 
- to set the size and precision of the ColumnDefinition model*

* Size can technically be set using the Length attribute, but seems suitable to group them together in another annotation as well, specifically for decimals.

**Comment by nul800sebastiaan** [comment]
Hi @LennardF1989 - unfortunately, as long as we have no specific need to do this in core, we won't be adding support for these annotations. 
The reason being that we'd rather not maintain code that we don't have a need for and is very specific to a handful of people's implementations. Sorry to disappoint!

**Comment by LennardF1989** [comment]
That's fine and understandable, but in that case I would really like a hook-in point somewhere to alter a TableDefinition before it leaves the DefinitionFactory (or better yet, make that overridable/injectable rather than static), so I can add the support myself gracefully without the need for compiling my own core.

There are ways around the need for such point (eg. making my own ISqlSyntaxProvider), but that's just nasty and you lose all context on what kind of class the original was based off.
