### ISSUE TITLE
Media Picker Error

### ISSUE THREAD

**Issue by timlaughlin** [umbraco/Umbraco-CMS#8113]
Media picker does not allow selection in RTE and throws error on media field type

![image](https://user-images.githubusercontent.com/8093200/81956130-9001e180-95d0-11ea-8333-a3ce1edb63e4.png)

## Umbraco version

I am seeing this issue on Umbraco version:  8.6.1

Reproduction
------------

### Bug summary

Select media within RTE field or media field.

### Expected result

Green check media selected

### Actual result

JS Error

**Comment by timlaughlin** [comment]
Also, RTE insert media -> media slide out -> select media shows second preview slide out but will not actually select media.

**Comment by nul800sebastiaan** [comment]
Hey there @timlaughlin, that's very surprising. We haven't heard about this before and it seems to  work in a clean install of 8.6.1. 

![8113](https://user-images.githubusercontent.com/304656/82344394-4c561000-99f4-11ea-9be3-5eb3548234ec.gif)

I'd recommend you head to our forum to get some help with this issue as it seems pretty localized to your specific install of Umbraco.
