### ISSUE TITLE
examineManager.TryGetIndex sometimes fails getting ExternalIndex on Umbraco Cloud 

### ISSUE THREAD

**Issue by robertjf** [umbraco/Umbraco-CMS#8117]
I have the following code in a Component:

```
    public class ContentIndexerComponent : IComponent
    {
        private readonly IExamineManager examineManager;
        private readonly ILogger logger;

        public ContentIndexerComponent(IExamineManager examineManager, ILogger logger)
        {
            this.examineManager = examineManager;
            this.logger = logger;
        }

        public void Initialize()
        {
            if (!examineManager.TryGetIndex("ExternalIndex", out IIndex index))
            {
                logger.Warn<ContentIndexerComponent>("No index found by the name ExternalIndex");
                throw new InvalidOperationException("No index found by the name ExternalIndex");
            }
        }
        public void Terminate() { }
    }

```

This throws the `InvalidOperationException` intermittently on Umbraco Cloud.

## Umbraco version

I am seeing this issue on Umbraco version: 8.5.5

**Comment by nul800sebastiaan** [comment]
I appreciate the report @robertjf, but I'm afraid we can't reproduce.. if you know of a good way to reproduce this reliably then it's something we can look into. 

As a wild guess: If you're doing anything related to load balancing on then you should update to v8.6.1 for more reliable behavior. 
If you're load balancing on azure web apps then note this comment: https://github.com/umbraco/UmbracoDocs/pull/2471/files#diff-30d3d5dde11eb1d153c5e0c28c64f48bR40
