### ISSUE TITLE
SqlMainDomLock setting causes application error if database not upgraded

### ISSUE THREAD

**Issue by idontbyte** [umbraco/Umbraco-CMS#8118]
On version 8.6.1
If you have not migrated your database
And you have `<add key="Umbraco.Core.MainDom.Lock" value="SqlMainDomLock" />` in app settings
Site will hang, 500 error because table does not exist.

This means upgrading to 8.6.1 in Azure is a two step process, 1. upgrade without app setting, 2. add app setting.

This is causing a bit of a pain for live websites that are using continuous deployment.

**Comment by rbottema** [comment]
Could this be the same as #7967?

**Comment by nul800sebastiaan** [comment]
Thanks! This is indeed fixed for the upcoming 8.6.2 in #7967.
