### ISSUE TITLE
Broken Twitter embed in RTE

### ISSUE THREAD

**Issue by jbarszczewski** [umbraco/Umbraco-CMS#8126]
Embedding Tweeter statuses stopped to work in RTE.

## Umbraco version

I am seeing this issue on Umbraco version: 8.6.1

Reproduction
------------
### Bug summary
When using RTE (tinyMCE) there is option to embed Twitter statuses. This option used to work but now it's broken once the content appear. At first the twitter iframe show up correctly but if you save content it's disappearing completely from CMS and frontend. There are html tags in RTE source.

### Steps to reproduce
- Click "Embed" in RTE
- Paste valid Twitter URL
- Save Content

### Expected result

Twitter embed should appear after reloading content.

### Actual result

Twitter embed is no longer visible

**Comment by nul800sebastiaan** [comment]
This is weird, I can reproduce but to be fair in 8.5 the embed function also makes the tweet look weird as it strips out the iframe. Maybe what is being returned from twitter's oEmbed service has changed.

In 8.5.5 it looks like this, does that look like what you expected?

![image](https://user-images.githubusercontent.com/304656/82346458-c8e9ee00-99f6-11ea-9e6b-75cb63abef4a.png)

**Comment by jbarszczewski** [comment]
Hi, I think the issue was on Twitter side as I tried to replicate the issue today to provide you with screenshots but it's working again. Before I was able to see similar content as on your screen but after saving the rte html was not loading properly so the tweet was just not there.

**Comment by nul800sebastiaan** [comment]
Weirdness! Happy it's working again! :-)
