### ISSUE TITLE
Can´t complete the Template tour in the backoffice if you close the template folder

### ISSUE THREAD

**Issue by Aaen** [umbraco/Umbraco-CMS#8137]
I have tried to start a trial on Umbraco Cloud and I can´t complete the tour in the template section if you close the template folder 

## Umbraco version

Umbraco 8.6.1
Forms 8.4.1
Deploy 3.4.4

Reproduction
------------

If you're filing a bug, please describe how to reproduce it. Include as much
relevant information as possible, such as:

### Bug summary

Just start the backoffice tour for templates and then you will get to step 5/8 and I can´t find a way to continue 

### Steps to reproduce

Just start the backoffice tour for temlates and if you close the tree for templates then you will get to step 5/8 and I can´t find a way to continue 

<img width="1437" alt="Skærmbillede 2020-05-19 kl  14 29 26" src="https://user-images.githubusercontent.com/2038482/82326660-76500800-99dd-11ea-9b13-0ccae789d130.png">

### Expected result
I expected that I could complete the tour 

### Actual result
Stuck in step 5/8

---
_This item has been added to our backlog [AB#6743](https://dev.azure.com/umbraco/243e7927-03b2-44e2-908f-d4ac7ea5daaa/_workitems/edit/6743)_

**Comment by warrenbuckley** [comment]
Fixed by this PR here - https://github.com/umbraco/Umbraco-CMS/pull/8235
