### ISSUE TITLE
Two model builder menu items under settings

### ISSUE THREAD

**Issue by deekoulos** [umbraco/Umbraco-CMS#8143]
Hey Guys,

I am facing a weird bug in the back office of all environments, where I can see two Model Builder menu items under settings: 

![image](https://user-images.githubusercontent.com/55948134/82433054-2c285e80-9a91-11ea-9bc8-64449f0345a4.png)

Unfortunately, I cannot describe how to reproduce this, since it just showed up and I don't know why and how...

## Umbraco version

I am seeing this issue on Umbraco version: 8.6.1

### Bug summary

Two Model Builder menu items under Settings, both work properly and look exactly the same. 

### Expected result

There is only one model builder menu item under settings in the back office.

### Actual result

There are two of them.

**Comment by nul800sebastiaan** [comment]
@deekoulos Hi there - this sounds like an excellent question for the forums where our friendly community can help you find the best solution for your requirements. 
Make sure to head on over to https://our.umbraco.com and ask follow up questions there! 👍
