### ISSUE TITLE
User cannot change password

### ISSUE THREAD

**Issue by z7paul** [umbraco/Umbraco-CMS#8174]
Unable to change own password in back office due to validation error on non-existent "old password" field.

## Umbraco version

I am seeing this issue on Umbraco version: 7.15.4

Reproduction
------------

### Steps to reproduce

1. Login to back office
2. Select your user icon (top left)
3. Click "Change password" button
4. Enter your "New Password" and "Confirm new password" values
(Note: no field for old password)
5. Click "Change password"

### Expected result

New password should be successfully saved (if valid).

### Actual result

The following validation message is then returned:
"Validation: Password cannot be changed without the old password"
(Note: no field exists in the UI to enter the old password)

**Comment by nul800sebastiaan** [comment]
Hi @z7paul, I would recommend you upgrade to 7.15.5, we made a few fixes to saving users and members and passwords in there! 👍
