### ISSUE TITLE
Old NuCache properties when using  _contextFactory.EnsureUmbracoContext().UmbracoContext.Content.GetById(IdHere) in ContentService.Published event

### ISSUE THREAD

**Issue by g0rski** [umbraco/Umbraco-CMS#8181]
Hi Recently I noticed an issue on my Umbraco based application - after save and publish of node, my custom examine index was propagated with CurrentVersion -1 of published document. I started digging and found out that I had mechanism that were rebuilding index on ContentService.Published, in there I used _contextFactory.EnsureUmbracoContext().UmbracoContext.Content.GetById(IdHere) to get currently rebuild node by id - which gave me previous version of my document (1 version older than the one that I just published)

Umbraco 8.5.5

**Comment by rbottema** [comment]
I think #4407 and maybe #7485 are related to this.
