### ISSUE TITLE
Deleted nodes are displayed in the content tree instead of the recycle bin

### ISSUE THREAD

**Issue by ClausFT** [umbraco/Umbraco-CMS#8182]
It seems like the node is moved to the recycling bin upon deleting it, but when refreshing the browser it is visible in the content tree again.

![2020-05-27_10-17-32](https://user-images.githubusercontent.com/4171055/82995618-1a503980-a004-11ea-8b37-142dfd097dc1.png)

**Comment by nul800sebastiaan** [comment]
Thanks @ClausFT, we unfortunately can't reproduce this. Seems like something might be going wrong when you try to delete this node, maybe you can see a javascript error or maybe there's an eventhandler preventing deletion..
Let us know if you can reproduce this in a clean install of Umbraco 8.6.1!

**Comment by Slipoch** [comment]
Confirming this error can still occur in Umbraco 8.14

I see a console log msg: 'A problem occurred syncing the tree! A path is probably incorrect.'
tested rebuilding indexes and no change.

I suspect the path to the node didn't get altered on delete however the parent may have been correctly changed to the recycle bin (depending on how the message at the top is generated).

![image](https://user-images.githubusercontent.com/11207625/186544658-bd25dfe7-afd8-4d74-8673-56ab714872c4.png)
