### ISSUE TITLE
Umbraco v8.5.5 - Opening preview window causes back office issues.

### ISSUE THREAD

**Issue by Cockney-Rob** [umbraco/Umbraco-CMS#8186]
We have a strange issue which appears to be connected to opening the preview window. 
Secenario : having created a number of links in a rich text editor window, click preview, click back to the content page, go to add another link, clicking the RTE link toolbar button does not display the link editor.
Opening the preview window also causes the content tree to freeze. Clicking another item of content in the back office results in the animated three-dot cursor which never recovers.
Refreshing the browser window restores functionality.
Evidential video attached.
[Untitled 2.zip](https://github.com/umbraco/Umbraco-CMS/files/4688898/Untitled.2.zip)

**Comment by nul800sebastiaan** [comment]
Very strange, I followed your repro steps in 8.6.1 and it seems to work fine. I do notice that you also have a very unusual RTE setup with more menus and buttons than are normally there, maybe one of your customizations breaks something for some reason? Not sure. 

So first I would recommend an 8.6.1 upgrade and see if that helps, if not, then have a look at javascript errors, and finally consider the RTE config and what might be happening there.

![8186](https://user-images.githubusercontent.com/304656/83029984-99109b00-a033-11ea-87d9-19650ea4152e.gif)

**Comment by Cockney-Rob** [comment]
Hi Sebastiaan, thanks for your time. As it turns out it was a recently added third party cookie consent plugin causing the problem in the preview window. Complete red herring, but thank you for your kind attention.
