### ISSUE TITLE
Umbraco 7 - Custom member types - allow custom properties to be added to Properties tab, or allow standard properties to be moved

### ISSUE THREAD

**Issue by lesley-w** [umbraco/Umbraco-CMS#8193]
We have a custom member type that has additional properties e.g. Organisation, Phone No. etc.

We can't add these properties to the default Properties tab, so have created a new Details tab. However, it would be good to be able to display the member's email on the same tab so that all the details of the member are on one tab e.g.

FirstName
LastName
Email
Phone No.
Organisation

I tried moving the Email field to the Details tab using the EditorModelEventManager_SendingMemberModel but this broke the member as umbraco.services.js only looks for _umb_email on the "general properties" tab and can't find it.

This means I am currently having to maintain and synchronise two email fields as the client wants all their fields on one tab.

Please consider either allowing custom properties to be added to the general properties tab, or update umbraco.services.js to search for standard fields such as email, login on other tabs if it doesn't find them on the properties tab.

**Comment by nul800sebastiaan** [comment]
Hey there @lesley-w - unfortunately, we're not considering any new features for Umbraco 7 any more, all of our efforts are focuses on v8 and beyond. Maybe head out to the forum at https://our.umbraco.com to see if someone can help you make your workarounds even better :-)
