### ISSUE TITLE
Add Unit Tests for Nested Content JSON Recursive Key work

### ISSUE THREAD

**Issue by warrenbuckley** [umbraco/Umbraco-CMS#8199]
We need to add C# unit tests for the PR to ensure the various scenarios for Nested Content JSON structures are updated with keys correctly - https://github.com/umbraco/Umbraco-CMS/pull/8177/

This not get done in the original PR - due to release timing.

## Tests to write
* Nested Content
* Nested Content --> Nested Content
* Nested Content --> Complex Editor (Grid/custom..) --> Nested Content

* Copying Node -> Generates new keys for all nested content items
* Saving/Publishing Node -> Only creates new keys for NC items that are missing the **key** property

---
_This item has been added to our backlog [AB#6928](https://dev.azure.com/umbraco/243e7927-03b2-44e2-908f-d4ac7ea5daaa/_workitems/edit/6928)_

**Comment by Shazwazza** [comment]
https://github.com/umbraco/Umbraco-CMS/pull/8214

**Comment by BatJan** [comment]
@Shazwazza I can see the reference PR has been merged - Can we close this issue then? 😃

**Comment by nul800sebastiaan** [comment]
Seems like it, let's close :-)
