### ISSUE TITLE
Hand Gesture on Upgrade screen

### ISSUE THREAD

**Issue by Myster** [umbraco/Umbraco-CMS#8217]
Hi, 
Hand gestures are notoriously bad at travelling between cultures. ( [examples ](https://www.dailymail.co.uk/travel/travel_news/article-3000521/Handy-infographic-explains-hand-gestures-world.html) )
As such I suggest the upgrade screen and other screens be a more boring/professional design.
I see a backwards I love you sign, why backwards? does that mean you hate me? I'm not sure so I googled it and found more confusion.
https://www.quora.com/What-does-it-mean-when-the-ILY-sign-is-pointed-towards-you-so-it-is-like-but-backwards

**Comment by Shazwazza** [comment]
I don't think that image is the installer image anymore, don't think it has been like that for quite a few versions now, see https://github.com/umbraco/Umbraco-CMS/blob/v8/contrib/src/Umbraco.Web.UI.Client/src/assets/img/installer.jpg

**Comment by Shazwazza** [comment]
but yes definitely a fair point and something to keep in mind for other images changes!

**Comment by nul800sebastiaan** [comment]
Took me a while to realize what image we were even talking about, this one is still being used in v7. We can replace that one for the next patch release: https://github.com/umbraco/Umbraco-CMS/blob/v7/dev/src/Umbraco.Web.UI.Client/src/assets/img/installer.jpg

**Comment by nul800sebastiaan** [comment]
Fixed in https://github.com/umbraco/Umbraco-CMS/commit/2d4b3c7dc51d60ebe110cffcaeaf279470c54a4e

Changed to: 

![installer](https://user-images.githubusercontent.com/304656/83503173-fb015280-a4c2-11ea-87ef-79cd38901ca0.jpg)
