### ISSUE TITLE
Content Editor Property Fluid width

### ISSUE THREAD

**Issue by thenexus00** [umbraco/Umbraco-CMS#8233]
If you are not using the Grid for content in your document type and the content picker is your main source of content it would be good to have a fluid width option so it can better fill the screen.

When you specify width and height in the property it is limited to pixels. It would be good to have an option to choose "Pixels" or "Percentage" for width and height so you have that ability.

The Back office is somewhat responsive but if you try to specify a wider content area it then does not scale down.

How can you help?
-------------------------------

Maybe if the work is not a quick one.

**Comment by nul800sebastiaan** [comment]
@thenexus00 Thanks! We have 3 sizes for the content picker overlay (what we call the infinite editor panes), `small`, `medium` and `large`. What I believe you are saying is that there's either not enough space for you to pick from or the overlay is in an inconvenient place for you to reach maybe?

To clarify, you're talking about this content picker, right?

![image](https://user-images.githubusercontent.com/304656/83859297-00a6a480-a71e-11ea-999f-ef3d98126dbf.png)
