### ISSUE TITLE
Copy Nested Content Function Not Work

### ISSUE THREAD

**Issue by duanleou90** [umbraco/Umbraco-CMS#8243]
## Umbraco version

I am seeing this issue on Umbraco version: 8.6.2

### Bug summary
- The Umbraco 8.6.2 release describes that the #7133 issue was fixed. But after upgrading to 8.6.2 from 8.6.1. I tried to copy a nested content and saw that the copy nested content function not worked.

### Specifics
- Umbraco version 8.6.2
- Chrome Version 83.0.4103.61
- The same problem with Firefox
- The error message in console log of the browser
![image](https://user-images.githubusercontent.com/15762936/83964392-085d7900-a8d7-11ea-8c4c-9f736baf8279.png)

### Steps to reproduce
- Copy an existing nested content
![image](https://user-images.githubusercontent.com/15762936/83964701-dea55180-a8d8-11ea-8368-50384f66a4e3.png)

- Click add content to choose the copied nested content
![image](https://user-images.githubusercontent.com/15762936/83964568-2e374d80-a8d8-11ea-8b66-fe2a4210b627.png)

- Can not see the copied nested content (the copy nested content function not work)
![image](https://user-images.githubusercontent.com/15762936/83964604-5c1c9200-a8d8-11ea-9a58-60e88887d35c.png)

- Check the console log of browser and get an error message

### Expected result
- After copying the nested content, can see the copied nested content when click add content

### Actual result
- Can not see the copied nested content (the copy nested content function not work)
- Got an error message in console log of the browser like below
![image](https://user-images.githubusercontent.com/15762936/83964790-8cb0fb80-a8d9-11ea-9093-1baeea8bcf30.png)

![image](https://user-images.githubusercontent.com/15762936/83964824-afdbab00-a8d9-11ea-8853-5e6fe64ab95b.png)

**Comment by joepvtl** [comment]
Hi,

This bug has already been reported #8223 and has an open PR #8226 .

-Joep

**Comment by duanleou90** [comment]
Hi @joepvtl,
I see it now. Thanks
