### ISSUE TITLE
v7.15.5: RTE Media picker deletes image if alternative text is changed

### ISSUE THREAD

**Issue by rgdagostino** [umbraco/Umbraco-CMS#8254]
The Media Picker in the Rich Text Editor deletes an image previously added when we select the image and try to change the "alternative text" field.

Umbraco Version
------------

I am seeing this issue on Umbraco version: 7.15.5

Reproduction
------------

### Specifics

This happens on all browsers I tested (firefox, chrome, edge)

### Steps to reproduce

In the Rich Text Editor:
1) Add an image using the "image picker" icon
2) Select the image
3) click on the "image picker" icon and the right hand side menu appears
4) change the alternative text
5) the image disappears

### Screenshot (gif)

![RteImagePickerBug](https://user-images.githubusercontent.com/8196233/84089768-2fc95880-aa33-11ea-8059-06bc61e8b4b1.gif)

### Expected result

The alternative text for an image changes

### Actual result

The image is broken 

---
_This item has been added to our backlog [AB#7088](https://dev.azure.com/umbraco/243e7927-03b2-44e2-908f-d4ac7ea5daaa/_workitems/edit/7088)_

**Comment by robgoddes** [comment]
I would love to see this fixed as a patch/version update. I have the exact same editing issue.

**Comment by nul800sebastiaan** [comment]
Hmm that's annoying, I bet this is because we changed the details we return for images in in 7.15 and up. We'll have to have a look.

**Comment by robgoddes** [comment]
@rgdagostino – You may want to share your resolution for this issue with the team. As well as fixing the ‘**Alternative text**’ field, I like your resolution that also incorporates **Width** and **Height** fields — which is important for Editors to easily resize images.

@nul800sebastiaan – Did the **Height** and **Width** also disappear in recent updates? They are missing on my **Umbraco version: 7.15.5**. It’s helpful to have them there so Editors can easily update image sizes (and scale with entered values proportionately).
 
<img width="512" alt="Screen Shot 2020-06-10 at 9 22 09 pm" src="https://user-images.githubusercontent.com/24960/84262305-be87c380-ab60-11ea-94fd-38379cd9956e.png">

**Comment by jrguay** [comment]
Hello.

I just wanted to ask if there is any progress on this as it is blocking the release of 7.15.6?

Thank you!

**Comment by drangus** [comment]
Came across this issue when upgrading to 7.15.3. Fixed it by modifying **Umbraco.Overlays.MediaPickerController** : reverted to older approach of using mediaResource rather than entityResource as the latter doesn't return the necessary info., including the url. In function 'run' changed 
`entityResource.getById(id, 'Media').then(function (node) {`
to
`mediaResource.getById(id).then(function (node) {`
and so far we've had no further problems.

**Comment by rgdagostino** [comment]
@nul800sebastiaan I pushed the fix here https://github.com/umbraco/Umbraco-CMS/pull/9246 . 
Hopefully I followed the protocol correctly as I had never contributed before.
Also, I know it's a bit off topic here, and I know Umbraco7 is just in maintenance mode, but do you think there's a chance I could also add the code to enhance the image handling in the rich text editor? As it's shown in the screenshots above, I added the possibility to change the size (keeping the image proportion). I did that development for a client and would be nice to have the feature for everyone.
Cheers,
Giampiero

**Comment by rgdagostino** [comment]
@UmbracoHQ @nul800sebastiaan we're approaching the one year mark since when I requested this pull request and it wasn't accepted yet. I wonder why it takes so long to add a line of code? It's a pretty relevant bug for the visual experience, and umbraco 7 is still used everywhere.

**Comment by nul800sebastiaan** [comment]
I'm very sorry @rgdagostino, unfortunately this didn't get the proper attention it deserved and we ran out of time to make it happen for v7, this is being closed along with the PR you made as we're moving our focus completely to v8 and v9: https://github.com/umbraco/Umbraco-CMS/pull/9246
