### ISSUE TITLE
Raise an event when deleting a document type to its dependents

### ISSUE THREAD

**Issue by thomasandresen** [umbraco/Umbraco-CMS#8256]
If a document type is allowed as a child in other document types, and the document type is being deleted, the dependents gets updated in the database and data is consistent. However since there is no event being triggered that the dependent document type has been changed, other won't be able to react on such change, e.g. when using deploy.

Fixes umbraco/Umbraco.Cloud.Issues#66

**Comment by nul800sebastiaan** [comment]
Fixed in https://github.com/umbraco/Umbraco-CMS/pull/8257
