### ISSUE TITLE
PropertyValueConverterBase contains unused HasValue method

### ISSUE THREAD

**Issue by ronaldbarendse** [umbraco/Umbraco-CMS#8259]
The `PropertyValueConverterBase` contains an unused `HasValue` method (that's not a member of the `IPropertyValueConverter` interface): https://github.com/umbraco/Umbraco-CMS/blob/3bfd9b71e290354744d677440983ecd06c5c0788/src/Umbraco.Core/PropertyEditors/PropertyValueConverterBase.cs#L25-L31

This method can probably be obsoleted (or removed, but that would be a breaking change, as it's a public, virtual method). The same code is already used in the `IsValue` method: https://github.com/umbraco/Umbraco-CMS/blob/3bfd9b71e290354744d677440983ecd06c5c0788/src/Umbraco.Core/PropertyEditors/PropertyValueConverterBase.cs#L14-L23

The same code is also used in `PublishedPropertyType`, but that returns a boolean for every type of `PropertyValueLevel` (not the same as the code above, that only returns true/false for the source value): https://github.com/umbraco/Umbraco-CMS/blob/3bfd9b71e290354744d677440983ecd06c5c0788/src/Umbraco.Core/Models/PublishedContent/PublishedPropertyType.cs#L179-L190

**Comment by ronaldbarendse** [comment]
Also, according to the documentation the `IsValue` method should return `null` for levels it can't determine: https://github.com/umbraco/Umbraco-CMS/blob/3bfd9b71e290354744d677440983ecd06c5c0788/src/Umbraco.Core/PropertyEditors/IPropertyValueConverter.cs#L20-L30

But `PropertyValueConverterBase` currently throws a `NotSupportedException` for the `Inter` and `Object` types!

**Comment by nul800sebastiaan** [comment]
What is the result of having an unused method? Is it in the way? People can inherit that class and use it? I don't really understand the problem.

**Comment by ronaldbarendse** [comment]
The biggest problem is probably confusion, as developers might override the `HasValue` (that doesn't do anything) instead of the `IsValue` method. This might cause bugs and/or wasted development time, which can be easily prevented by adding an `Obsolete` attribute indicating this.

Besides that, the `IsValue` method also throws exceptions when it shouldn't, so that's definitely a bug (the documentation explicitly states it should return `null` and the exception message indicates it should only be thrown on invalid enum values, not unhandled ones).
