### ISSUE TITLE
make goToItem() method available to Umbraco.PropertyEditors.ContentPickerController

### ISSUE THREAD

**Issue by elliottjb7** [umbraco/Umbraco-CMS#8261]
Hi, I am trying to extend the content picker in 7.15.2 with an edit button. In fact I have successfully done that using a custom property editor. However, the method goToItem() does not seem to be available to this controller. 

Is it deliberate that you can go straight to a picked content item from the point at which it was picked? For instance, anywhere an image is picked you can directly access the image using the edit button.

Thanks!

**Comment by nul800sebastiaan** [comment]
I just think it was never considered, for media items you might want to go and edit them, probably with the picked content item as well. Unfortunately we're no longer accepting any new feature requests for Umbraco 7 and won't be putting new features in. v7 is in bugfix-only mode and all of our efforts are going into working on v8 and beyond. 

As such, I'll close this issue. If you need some help with your customizations, make sure to head over to the forum at https://our.umbraco.com to leave questions for our community.
