### ISSUE TITLE
Query Nodes by Creator Id doesn't work

### ISSUE THREAD

**Issue by cheeseytoastie** [umbraco/Umbraco-CMS#8275]
Went to answer a query on the forum  - just filter by CreatorId I thought....
 
https://our.umbraco.com/forum/using-umbraco-and-getting-started/102525-get-nodes-created-by-specific-user-by-query

Nothing was returned in my simple razor Linq query:
```
@{
            var homeNode = Model.AncestorOrSelf(1);
            <h1>@homeNode.Name @homeNode.CreatorId</h1>

            var nodesByCreator = homeNode.Children().Where(x => x.CreatorId == 1);

            foreach (var curNode in nodesByCreator)
            {
                <h2>@curNode.Name - @curNode.CreatorId - @curNode.CreatorName</h2>
            }
        } 
```

Yet when I change it to CreatorName it works fine (string matching for the win). 

I tried this on v7 and it works as expected. 

## Umbraco version

I am seeing this issue on Umbraco version: v8.5.4 - v8.6.1

Reproduction
------------

### Bug summary

Fire up a starter kit - and put the razor script above in the master template

### Expected result

I expected to see all nodes - if you change the code to .CreatorName == "Steve Morgan" you'll see all the nodes as expected.

### Actual result

Seems the linq query returns an empty set.

**Comment by cheeseytoastie** [comment]
Razor above uses Children but I found it via DesecendantsOrSelf - both fail.

**Comment by nul800sebastiaan** [comment]
Are you sure your user Id is 1? The default for the first admin account is `-1`. 

Works for me! :-)

![image](https://user-images.githubusercontent.com/304656/84488612-c2226400-aca0-11ea-8764-f52fa384a780.png)

**Comment by cheeseytoastie** [comment]
Yesterday was clearly not a good day for alertness. You're right - it's minus 1. The output had a hypthen in the text and I misread the -1 and changed it to 1. 

More sleep required. And SORRY!

**Comment by nul800sebastiaan** [comment]
Hahaha! Well to be fair, I looked and it and went.. 🤔 Steve's right, that is super odd.. then I looked a closely again and I spotted the double hyphen! So it's not just you! 😉
