### ISSUE TITLE
Saving a Composite Document Type with pre-existing Documents leads to a Primary Key Violation on PK_cmsContentNu

### ISSUE THREAD

**Issue by georg-jung** [umbraco/Umbraco-CMS#8294]
When saving one specific document type (even without actually changing anything) I get a red server error box saying

> Failed to save data for content type id \<ID\>

in the backoffice. Saving similar document types still works.

## Umbraco version

I am seeing this issue on Umbraco version: 8.6.2

Reproduction
------------

### Bug summary

I'm trying to edit a document type `Artikel` (german for article) / ID 1111 that is composited and has pre-existing published as well as unpublished documents. That fails with (taken from trace log) warning `The query returned multiple property sets for content {ContentId}, {ContentTypeName}` followed by error `Violation of PRIMARY KEY constraint 'PK_cmsContentNu'. Cannot insert duplicate key in object 'dbo.cmsContentNu'. The duplicate key value is (1113, 0).`.

Now, 1113 is an existing document of document type 1111 / `Artikel`, that I'm trying to save. When looking at the db a row (1113, 0) exists as well as the (1113, 1) row that I assume should be there because the document is published. When deleting this row manually from the db and trying to save again from the backoffice, the same behaviour as described here happens again. The (1113, 0) row exists again afterwards.

### Specifics

I'm using [Chrome 83.0.4103.97 (64-Bit)](https://www.whatsmybrowser.org/b/6M5LI). [Edge 18](https://www.whatsmybrowser.org/b/YMC3X) shows the same behaviour. I'm using Windows 10.

My Umbraco is hosted as an Azure App Service on Windows. DB is Azure SQL. The same happens when running Umbraco locally from Visual Studio/IIS Express, still using the same Azure SQL as DB.

I started noticing this issue in Umbraco 8.5.5 (*not* after upgrading to 8.5.5; I originally installed 8.5.5 and it worked on that version before). It persisted after upgrading from 8.5.5 to 8.6.2. The relevant request URL is `https://XXX.XXX-XX.de/umbraco/backoffice/UmbracoApi/ContentType/PostSave`. That's called from `https://XXX.XXX-XX.de/umbraco/#/settings/documentTypes/edit/1111?mculture=de-DE`.

### Steps to reproduce

My doc types look like this:

![image](https://user-images.githubusercontent.com/5229609/84775899-5c0f4700-afe8-11ea-8e1a-abc595aa6c62.png)
![image](https://user-images.githubusercontent.com/5229609/84779822-87e0fb80-afed-11ea-8dd1-2e87461406a0.png)
![image](https://user-images.githubusercontent.com/5229609/84779925-a47d3380-afed-11ea-9415-eb46a5083e24.png)
![image](https://user-images.githubusercontent.com/5229609/84780148-e73f0b80-afed-11ea-8191-a0dc4b299e10.png)

HasContent has a group *Inhalt* (Content) that has properties `headline`and `contents`. The doc type I'm trying to save is `Artikel` (article). It inherits directly from `Standard` as it is it's child and it has `HasContent` as composition.

My intent was to add a property to the *Inhalt* group for article, but that fails. Saving without changing anything fails too. This broke at some point and I don't exactly know at which (it did work before; the ocmposition and documents of that type existed back then too). There are already documents of this type. Some are published some are not.

I do have a second doc type that is quite comparable to the `Artikel` one I want to save. It's called `Einfach` (german for simple). It inherits from `Standard` too, it has `HasContent` as a composition too, it has published documents in the tree too. Saving this one is possible. I have the feeling though that saving sometimes failed (seldomly) but I was not able to reproduce that (it might be irrelevant).

### Expected result

Doc type is saved without errors or with an error that is fixable from the user's perspective.

### Actual result

![image](https://user-images.githubusercontent.com/5229609/84778880-4865df80-afec-11ea-80f2-5725bcbbfb0a.png)

Red server error box. Trace log (stripped info replaced by X, json pretty printed):

    {
        "@t": "2020-06-16T12:50:03.5557598Z",
        "@mt": "The query returned multiple property sets for content {ContentId}, {ContentTypeName}",
        "@l": "Warning",
        "ContentId": 1113,
        "ContentTypeName": "Artikel",
        "SourceContext": "Umbraco.Core.Persistence.Repositories.Implement.ContentRepositoryBase`3[[System.Int32, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089],[Umbraco.Core.Models.IContent, Umbraco.Core, Version=8.0.0.0, Culture=neutral, PublicKeyToken=null],[Umbraco.Core.Persistence.Repositories.Implement.DocumentRepository, Umbraco.Core, Version=8.0.0.0, Culture=neutral, PublicKeyToken=null]]",
        "ProcessId": XXXXX,
        "ProcessName": "w3wp",
        "ThreadId": XX,
        "AppDomainId": X,
        "AppDomainAppId": "XXXXXXXXXXXXXXXXXXX",
        "MachineName": "XXXXXXXXXXXXXX",
        "Log4NetLevel": "WARN ",
        "HttpRequestNumber": 61,
        "HttpRequestId": "XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX"
    }
    {
        "@t": "2020-06-16T12:50:05.3369824Z",
        "@mt": "Unhandled controller exception occurred for request '{RequestUrl}'",
        "@l": "Error",
        "@x": "System.Data.SqlClient.SqlException (0x80131904): Violation of PRIMARY KEY constraint 'PK_cmsContentNu'. Cannot insert duplicate key in object 'dbo.cmsContentNu'. The duplicate key value is (1113, 0).\r\nThe statement has been terminated.\r\n   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)\r\n   at System.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)\r\n   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)\r\n   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)\r\n   at System.Data.SqlClient.TdsParser.Run(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj)\r\n   at System.Data.SqlClient.SqlBulkCopy.RunParser(BulkCopySimpleResultSet bulkCopyHandler)\r\n   at System.Data.SqlClient.SqlBulkCopy.CopyBatchesAsyncContinuedOnSuccess(BulkCopySimpleResultSet internalResults, String updateBulkCommandText, CancellationToken cts, TaskCompletionSource`1 source)\r\n   at System.Data.SqlClient.SqlBulkCopy.CopyBatchesAsyncContinued(BulkCopySimpleResultSet internalResults, String updateBulkCommandText, CancellationToken cts, TaskCompletionSource`1 source)\r\n   at System.Data.SqlClient.SqlBulkCopy.CopyBatchesAsync(BulkCopySimpleResultSet internalResults, String updateBulkCommandText, CancellationToken cts, TaskCompletionSource`1 source)\r\n   at System.Data.SqlClient.SqlBulkCopy.WriteToServerInternalRestContinuedAsync(BulkCopySimpleResultSet internalResults, CancellationToken cts, TaskCompletionSource`1 source)\r\n   at System.Data.SqlClient.SqlBulkCopy.WriteToServerInternalRestAsync(CancellationToken cts, TaskCompletionSource`1 source)\r\n   at System.Data.SqlClient.SqlBulkCopy.WriteToServerInternalAsync(CancellationToken ctoken)\r\n   at System.Data.SqlClient.SqlBulkCopy.WriteRowSourceToServerAsync(Int32 columnCount, CancellationToken ctoken)\r\n   at System.Data.SqlClient.SqlBulkCopy.WriteToServer(IDataReader reader)\r\n   at Umbraco.Core.Persistence.NPocoDatabaseExtensions.BulkInsertRecordsSqlServer[T](IUmbracoDatabase database, PocoData pocoData, IEnumerable`1 records) in D:\\a\\1\\s\\src\\Umbraco.Core\\Persistence\\NPocoDatabaseExtensions-Bulk.cs:line 257\r\n   at Umbraco.Core.Persistence.NPocoDatabaseExtensions.BulkInsertRecords[T](IUmbracoDatabase database, IEnumerable`1 records, Boolean useNativeBulkInsert) in D:\\a\\1\\s\\src\\Umbraco.Core\\Persistence\\NPocoDatabaseExtensions-Bulk.cs:line 81\r\n   at Umbraco.Web.PublishedCache.NuCache.PublishedSnapshotService.RebuildContentDbCacheLocked(IScope scope, Int32 groupSize, IEnumerable`1 contentTypeIds) in D:\\a\\1\\s\\src\\Umbraco.Web\\PublishedCache\\NuCache\\PublishedSnapshotService.cs:line 1535\r\n   at Umbraco.Web.PublishedCache.NuCache.PublishedSnapshotService.RebuildContentDbCache(Int32 groupSize, IEnumerable`1 contentTypeIds) in D:\\a\\1\\s\\src\\Umbraco.Web\\PublishedCache\\NuCache\\PublishedSnapshotService.cs:line 1473\r\n   at Umbraco.Web.PublishedCache.NuCache.PublishedSnapshotService.OnContentTypeRefreshedEntity(IContentTypeService sender, EventArgs args) in D:\\a\\1\\s\\src\\Umbraco.Web\\PublishedCache\\NuCache\\PublishedSnapshotService.cs:line 1318\r\n   at Umbraco.Core.Events.EventExtensions.RaiseEvent[TSender,TArgs](TypedEventHandler`2 eventHandler, TArgs args, TSender sender) in D:\\a\\1\\s\\src\\Umbraco.Core\\Events\\EventExtensions.cs:line 43\r\n   at Umbraco.Core.Services.Implement.ContentTypeServiceBase`2.OnUowRefreshedEntity(EventArgs args) in D:\\a\\1\\s\\src\\Umbraco.Core\\Services\\Implement\\ContentTypeServiceBaseOfTItemTService.cs:line 51\r\n   at Umbraco.Core.Services.Implement.ContentTypeServiceBase`3.Save(TItem item, Int32 userId) in D:\\a\\1\\s\\src\\Umbraco.Core\\Services\\Implement\\ContentTypeServiceBaseOfTRepositoryTItemTService.cs:line 429\r\n   at Umbraco.Web.Editors.ContentTypeController.<PostSave>b__17_1(IContentType type) in D:\\a\\1\\s\\src\\Umbraco.Web\\Editors\\ContentTypeController.cs:line 301\r\n   at Umbraco.Web.Editors.ContentTypeControllerBase`1.PerformPostSave[TContentTypeDisplay,TContentTypeSave,TPropertyType](TContentTypeSave contentTypeSave, Func`2 getContentType, Action`1 saveContentType, Action`1 beforeCreateNew) in D:\\a\\1\\s\\src\\Umbraco.Web\\Editors\\ContentTypeControllerBase.cs:line 295\r\n   at Umbraco.Web.Editors.ContentTypeController.PostSave(DocumentTypeSave contentTypeSave) in D:\\a\\1\\s\\src\\Umbraco.Web\\Editors\\ContentTypeController.cs:line 298\r\n   at lambda_method(Closure , Object , Object[] )\r\n   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.<>c__DisplayClass6_2.<GetExecutor>b__2(Object instance, Object[] methodParameters)\r\n   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.Execute(Object instance, Object[] arguments)\r\n   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ExecuteAsync(HttpControllerContext controllerContext, IDictionary`2 arguments, CancellationToken cancellationToken)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Controllers.ApiControllerActionInvoker.<InvokeActionAsyncCore>d__1.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__6.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__6.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Filters.ActionFilterAttribute.<ExecuteActionFilterAsyncCore>d__5.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__6.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__6.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Filters.ActionFilterAttribute.<ExecuteActionFilterAsyncCore>d__5.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__6.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__6.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Filters.ActionFilterAttribute.<ExecuteActionFilterAsyncCore>d__5.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__6.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__6.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Filters.ActionFilterAttribute.<ExecuteActionFilterAsyncCore>d__5.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__6.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__6.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Filters.ActionFilterAttribute.<ExecuteActionFilterAsyncCore>d__5.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Controllers.ActionFilterResult.<ExecuteAsync>d__5.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Filters.AuthorizationFilterAttribute.<ExecuteAuthorizationFilterAsyncCore>d__3.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Filters.AuthorizationFilterAttribute.<ExecuteAuthorizationFilterAsyncCore>d__3.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Filters.AuthorizationFilterAttribute.<ExecuteAuthorizationFilterAsyncCore>d__3.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Filters.AuthorizationFilterAttribute.<ExecuteAuthorizationFilterAsyncCore>d__3.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Controllers.ExceptionFilterResult.<ExecuteAsync>d__6.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Web.Http.Controllers.ExceptionFilterResult.<ExecuteAsync>d__6.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Dispatcher.HttpControllerDispatcher.<SendAsync>d__15.MoveNext()\r\nClientConnectionId:86271f3d-0e20-452e-b7c2-cbb6e9924efe\r\nError Number:2627,State:1,Class:14\r\nClientConnectionId before routing:XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX\r\nRouting Destination:fXXXXXXXXXXX.trXXXX.westeurope1-a.worker.database.windows.net,11003",
        "RequestUrl": "https://XXX.XXX-XX.de/umbraco/backoffice/UmbracoApi/ContentType/PostSave",
        "SourceContext": "Umbraco.Web.Editors.ContentTypeController",
        "ProcessId": XXXXX,
        "ProcessName": "w3wp",
        "ThreadId": XX,
        "AppDomainId": X,
        "AppDomainAppId": "XXXXXXXXXXXXXXXXXXX",
        "MachineName": "XXXXXXXXXXXXXX",
        "Log4NetLevel": "ERROR",
        "HttpRequestNumber": 61,
        "HttpRequestId": "XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX"
    }

**Comment by georg-jung** [comment]
@nul800sebastiaan (hope that I'm asking the right one) Do you think there's any more information that I can provide that could be helpful for solving this?

**Comment by nul800sebastiaan** [comment]
Sorry for the late reply @georg-jung and thanks for the in-depth problem description. Maybe I didn't read this properly but the problem seems to be isolated to a single doctype in your install right?

It would be really helpful if you could try to do a clean install of Umbraco 8.6.2 (on SQL CE so it's nicely portable) and replicate the doctype setup that is failing. If you can replicate this then it would be good to zip up the test install as it's then possible to have a look at where this error is coming from. 

Unfortunately I can't find anyone else with this problem though so it's very well possible that something in your specific setup might have become corrupted somehow.

**Comment by georg-jung** [comment]
Thanks for your response! 

> seems to be isolated to a single doctype in your install right?

Yes.

> possible that something in your specific setup might have become corrupted somehow.

I could imagine that too. I just don't know _how_ it got corrupted, since we just used the backoffice for editing. I thought, maybe even though this could be an edge case, there might be a more general solution. Like that the edge case just isn't handled in umbraco and happens seldomly, but still can be fixed. I looked at the corresponding source code but I got the feeling that someone, who is more into umbraco, might have a faster and smarter idea then me.

If you think it's impossible to gain enough insight without a portable repro, I'll try to create a setup as you described. Still, I'm not sure if I'll be able to reproduce it myself, because I don't really know what makes my specific doctype special. Still, I guess this is a bug :/

**Comment by nul800sebastiaan** [comment]
Thanks for the reply @georg-jung - indeed, it's frustrating that we don't know what's going on for that one doctype. But sometimes "stuff" just happens and we might never figure it out. I will close this for now, but at least this is now documented and someone else who runs into the same issue might have more information to add and get closer to a cause for it.
