### ISSUE TITLE
Using the tab key doesn't work anymore when selecting datatype

### ISSUE THREAD

**Issue by stefankip** [umbraco/Umbraco-CMS#8310]
When I'm editing a document type, I prefer to use my keyboard as much as possible.
In the past it was possible to do this:
- Add property
- Enter name _[tab]_
- Edit alias _[tab]_
- Enter description _[tab]_
- _[enter] [search for **texts** for example to find the Textstring] [tab] [enter]_ (now you return to the Add property dialog)
- **_[tab] [space]_ to enable Mandatory toggle**

But that's where it goes wrong nowadays (v8.6.2). After I press enter to confirm the datatype, I can't navigate to the Mandatory toggle with `<tab>`. Instead I'm `<tab>`ing through the sections (Content, Media etc.)

**Comment by nul800sebastiaan** [comment]
Yep, @BatJan is working on a fix for that - https://github.com/umbraco/Umbraco-CMS/pull/8141

Not sure if this immediately affects the doctype editor, but as soon as this is merged it can be used for many other areas of the backoffice.

**Comment by nul800sebastiaan** [comment]
Your route as described already works in the upcoming 8.7 though, so it's more that jumping out of that dialog to the sections would be something that we also want to prevent with Jan's PR!

![8310](https://user-images.githubusercontent.com/304656/85122301-9e25cc00-b226-11ea-94f8-76714555ec0b.gif)

**Comment by stefankip** [comment]
Nice!

**Comment by kjac** [comment]
The fix in #8141 should have closed this one, because indeed it does work nicely with tabbing now 😄
