### ISSUE TITLE
Next Gen Images (.webp, .svg etc) in the Media Section/Umbraco - v8

### ISSUE THREAD

**Issue by Ric-Carey** [umbraco/Umbraco-CMS#8314]
Hey, (let me know if I've "missed the memo" on this one, to enable support)

If you upload a webp image to the media section, no image cropper or thumbnails are rendered. Umbraco treats it as a file like a PDF. Just wondering with Google now advocating next-gen images in pagespeed - this going to start cropping up more. You can always convert JPGS/PNGs to WebP with the imageprocessor - but just thinking if a client uploads one to the media section it gives a bit of an unexpected experiance. 

Cheers
Ric

P.S. Come to think of it - this has been the case for SVGs for a while...

**Comment by ronaldbarendse** [comment]
This might already be possible if you install `ImageProcessor.Plugins.WebP` and add `webp` to the `imageFileTypes` in umbracoSetting.config:
```xml
<imaging>
	<!-- what file extension that should cause umbraco to create thumbnails -->
	<imageFileTypes>jpeg,jpg,gif,bmp,png,tiff,tif,svg</imageFileTypes>
</imaging>
```

As you can see, SVG files already have thumbnails (this was also fixed in 8.1.5: https://github.com/umbraco/Umbraco-CMS/issues/5857).

**Comment by Ric-Carey** [comment]
@ronaldbarendse - had a feeling it was going to be a config somewhere, cheers

**Comment by nul800sebastiaan** [comment]
Did that work for you @Ric-Carey? 

This might require some extra work maybe, but I'm not sure how webp images work..

The challenges we've had with SVGs:

- If they can contain executable code then it's a security risk, your editors might unwittingly upload files with code embedded in it - is this the case for webp too?
- SVG is vector graphics, so we can't show a cropper for it, just the thumbnail - is this the case for webp too?
- Not sure how imageprocessor deals with these, might need to render differently?

**Comment by nul800sebastiaan** [comment]
I'll close this one for now, it seems like what is needed is already possible - if any more work is needed for webp then we could look into that.
