### ISSUE TITLE
Force Automated Password Change

### ISSUE THREAD

**Issue by matt-parrott** [umbraco/Umbraco-CMS#8315]
Suggestion to add the feature for Umbraco Back office Users to have a password policy enabled which requires the backoffice account passwords to be changed every X days.

Ideally allow the administrator accounts to specify the password duration, then have Umbraco auto prompt the users to change their passwords on login after the specified duration.

**Comment by ronaldbarendse** [comment]
I don't think this is a feature that will be added to Umbraco itself, as password expiration has become an anti-pattern:
- https://docs.microsoft.com/en-gb/archive/blogs/secguide/security-baseline-final-for-windows-10-v1903-and-windows-server-v1903
- https://www.sans.org/security-awareness-training/blog/time-password-expiration-die
- https://www.microsoft.com/en-us/research/publication/password-guidance/

Umbraco is very extensible, so if you do still require this feature, you can swap out the default `UsersMembershipProvider` with your own version 👍

**Comment by nul800sebastiaan** [comment]
@matt-parrott Yes, @ronaldbarendse is correct, we have no plans to implement forced password changes, they're an outdated concept and are counterproductive. 

If you need help implementing such a feature I'd recommend you head on over to the forum get some assistance from our community at: https://our.umbraco.com
