### ISSUE TITLE
Members getting permanently locked out after password reset

### ISSUE THREAD

**Issue by kasperlau** [umbraco/Umbraco-CMS#8317]
Every time a Member reset there password, they get permanently locked out.

I have tried the following 2 versions of code. But it doesn't change anything. When the password is changed, and the member tries to login, they get locked out. After that, i can't undo it again in the dashboard.  When i remove the "Is Locked Out" on the member, it returns as soon as the member tryes to login again, even if i try resetting the password in the dashboard.

IMemberService memberService = Umbraco.Core.Composing.Current.Services.MemberService;
IMember member = memberService.GetByKey(new Guid(token.res_member_guid));
member.RawPasswordValue = (Membership.Providers["UsersMembershipProvider"] as UsersMembershipProvider).HashPasswordForStorage(password);
memberService.Save(member, false);

And

IMemberService memberService = Umbraco.Core.Composing.Current.Services.MemberService;
IMember member = memberService.GetByKey(new Guid(token.res_member_guid));
memberService.SavePassword(member, (Membership.Providers["UsersMembershipProvider"] as UsersMembershipProvider).HashPasswordForStorage(password));

I am seeing this issue on Umbraco version: 8.6.1 and 8.6.2

**Comment by enkelmedia** [comment]
Hi!

We're using members on the same versions of Umbraco but haven't seen the same issue.

Did you configure the membership provider to allow any specific number of failing passwords attempts?

Out of you example, the second one is the one I would use, I'm wondering about this line
```
memberService.SavePassword(member, (Membership.Providers["UsersMembershipProvider"] as UsersMembershipProvider).HashPasswordForStorage(password));
```csharp
One should not need to hash the password before (see docs https://our.umbraco.com/apidocs/v8/csharp/api/Umbraco.Core.Services.IMemberService.html) are performing the same hash during login? Otherwise the password in the db will be a hashed version of you hash which is probably not what you want.

It's still strange that the members ends up as locked out after one login attempt? Whats the value of your MaxInvalidPasswordAttempts-setting for the Provider?

Did you also configure allowManuallyChangingPassword for the provider? See the docs here:
https://our.umbraco.com/documentation/reference/security/Security-settings/

**Comment by kasperlau** [comment]
your correct about this line
memberService.SavePassword(member, (Membership.Providers["UsersMembershipProvider"] as UsersMembershipProvider).HashPasswordForStorage(password));

its of course just:
memberService.SavePassword(member, password);
I accidentally did a Copy paste error.

Heres  my provider settings
<add name="UmbracoMembershipProvider" type="Umbraco.Web.Security.Providers.MembersMembershipProvider, Umbraco.Web" minRequiredNonalphanumericCharacters="0" minRequiredPasswordLength="8" useLegacyEncoding="false" enablePasswordRetrieval="false" enablePasswordReset="true" requiresQuestionAndAnswer="false" defaultMemberTypeAlias="Member" passwordFormat="Hashed" allowManuallyChangingPassword="true" maxInvalidPasswordAttempts="50" />

The Locked Out Members only have 1  Failed Password Attempt.

**Comment by kasperlau** [comment]
Don't know if it means anything, but heres how i create members.

IMemberService memberService = Umbraco.Core.Composing.Current.Services.MemberService;
                IMember mem = memberService.CreateWithIdentity(email, email, h (Membership.Providers["UsersMembershipProvider"] as UsersMembershipProvider).HashPasswordForStorage(password), "Member", true);
                memberService.AssignRole(mem.Id, "Customer");
                mem.Name = name;
                mem.CreateDate = DateTime.Now;
                memberService.Save(mem);

**Comment by kasperlau** [comment]
I also just tried Deleting a test member, and recreated it with same name and username. He got locked out as soon as i tried to login in to the member page.  Heres my login code.

  public void memberlogin()
        {
            string status = "nouser";
            MembersMembershipProvider membershipProvider = new MembersMembershipProvider();
            
            string username = Request["username"];
            string password = Request["password"];


            if (membershipProvider.ValidateUser(username, password))
            {
                System.Web.Security.MembershipUser member = membershipProvider.GetUser(username, true);
                if (member.IsLockedOut)
                {
                    status = "user_logged_out";
                }
                else
                {
                    System.Web.Security.FormsAuthentication.SetAuthCookie(username, true);
                    status = "user_logged_in";
                }
                
            }
            Response.Clear();
            Response.Write(status);
            
        }

**Comment by enkelmedia** [comment]
Hi!

Your issue is that your trying to login with the wrong password and only have one attempt that means the account gets locked.

You should never need to hash the password your self and after a member is created you probably need to call “SetPassword”, can’t use the setter of the member (not 100% sure but I think).

I would remove all hashing that you are doing your self and try again.

**Comment by kasperlau** [comment]
Tried this approach as well.. nothing changed.. tried recreating the Member from back office, same isssue.. First login, it got locked out.

Heres some stats from the newly created member
Created
June 22, 2020 7:39 AM by Kasper
Last edited
June 22, 2020 7:39 AM
Failed Password Attempts
1
Last Lockout Date
6/22/2020 7:39:50 AM
Last Login Date
6/22/2020 7:39:42 AM
Last Password Change Date
6/22/2020 7:39:42 AM

**Comment by enkelmedia** [comment]
There is also /app_data/logs, have a look in there

Also make sure that you are using settings from the “Members-provider, not the “users” there is two different providers in Umbraco.

Start by setting the password in the back office and try to login in, then you’ll know if your “create”-/code has issues.

This article looks quite good: https://www.jondjones.com/learn-umbraco-cms/umbraco-7-tutorials/umbraco-component-tutorials/how-to-create-a-log-in-page-with-umbraco-7/

Also make sure to read the docs around this.

**Comment by kasperlau** [comment]
It is the Member provider :) 

I tried your suggestion, created the Member without logging ind.. but still got locked out on first try to login. 

Looked at the logs, heres what it contained
{"@t":"2020-06-22T14:52:37.4122837Z","@mt":"Login attempt failed for username {Username} from IP address {IpAddress}, the user is now locked out, max invalid password attempts exceeded","Username":"kontakt@website.dk","IpAddress":"::1","SourceContext":"Umbraco.Core.Security.UmbracoMembershipProviderBase","ProcessId":14852,"ProcessName":"iisexpress","ThreadId":67,"AppDomainId":129,"AppDomainAppId":"LMW3SVC11ROOT","MachineName":"LAPTOP-O8AL5ICE","Log4NetLevel":"INFO ","HttpSessionId":"02gkat2gccsj5lg0warig00e","HttpRequestNumber":17,"HttpRequestId":"aa139907-cc30-49a7-8bb0-88fef3264053"}

**Comment by kasperlau** [comment]
So i tried using the build in  MVC Login  template, and that works like a charm. How come i cant create a custom login code.

**Comment by kasperlau** [comment]
Found solution.

If your making custom login, do not use

MembersMembershipProvider membershipProvider = new MembersMembershipProvider();
And
membershipProvider.ValidateUser(username, password) 

instead use

 var memberHelper = Umbraco.Web.Composing.Current.UmbracoHelper;
And
memberHelper.MembershipHelper.Login(username, password)

**Comment by nul800sebastiaan** [comment]
Hey there @kasperlau good that you found a solution! 
Indeed, we remove the locking out part once you request a password reset.
I'll close this one.
