### ISSUE TITLE
Media item acts as folder if a folder of the same name as the media item is being dragged into a folder

### ISSUE THREAD

**Issue by OlePc** [umbraco/Umbraco-CMS#8325]
If you drag and drop a folder into another folder in the media section, and a media item in the same directory has the same name as the folder, this media item will be used as a folder (the content of the dragged folder is created as children of the media item).
This is an issue since the media picker don't treat the image as a folder, so the children can't be picked.

## Umbraco version
I am seeing this issue on Umbraco version: 8.6.2 on a blank install with starter kit.

Reproduction
------------
### Steps to reproduce

1. Go to the media section of Umbraco, and create a folder
2. In this folder upload an image called 'Image'
3. On your desktop, create a folder called 'Image' and add an image called 'Folder Image' to it
4. Drag and drop this folder into the media section of Umbraco
5. Notice that 'Folder Image' is now a child of 'Image'

### Expected result
When I upload a folder, I'd expect a folder in the media section to be created. If the issue is the dublicate name, then the folder should have the (1) suffix you normally get, when trying to create an item with the same name as another item.
Seems harder to reproduce in the root of the media section than inside a folder.

### Actual result
Content of the dragged folder is created as childs of the media item with the same name as the folder.
![image](https://user-images.githubusercontent.com/8521882/85372165-bc930c80-b531-11ea-8de6-2c46e4fc3e6b.png)

**Comment by kjac** [comment]
@OlePc that's a funny one! I can reproduce it... will have a look at a fix right away 👍

**Comment by kjac** [comment]
PR in #8344 👍
