### ISSUE TITLE
Member fields of type label are not shown in the backoffice

### ISSUE THREAD

**Issue by mcl-sz** [umbraco/Umbraco-CMS#8342]
When a membertype contains fields of the type label, they are not shown in de backoffice.

![afbeelding](https://user-images.githubusercontent.com/18614643/85840815-6de9aa80-b79d-11ea-9345-821a2f692fcd.png)

![afbeelding](https://user-images.githubusercontent.com/18614643/85840835-793cd600-b79d-11ea-94db-ab61b22fc979.png)

## Umbraco version

I am seeing this issue on Umbraco version: 8.6.2 and 8.6.3 (maybe earlier versions > 8.2.2)

Reproduction
------------

Create under de "Settings"-section a membertype and add a field of the type "Label". 
Go to the section "Members" and add an new member.

**Comment by kjac** [comment]
Oh good one, @mcl-sz ... I can reproduce. It's made that way in order to hide the system label properties, e.g. "Failed Password Attempts". But surely it can be done smarter... I'll fix 👍 

![image](https://user-images.githubusercontent.com/7405322/85859768-f6784300-b7bd-11ea-9812-1cd77434b897.png)

**Comment by kjac** [comment]
PR in #8346
