### ISSUE TITLE
Ability to Kill and Re-initialize Lucene/Examine Manager

### ISSUE THREAD

**Issue by NikRimington** [umbraco/Umbraco-CMS#8360]
# History behind request

We have an issue on Azure sites where the Examine Indexes "disappear". The files are still on disk when viewing through Kudu, but the Examine section of the back office throws an error, as does trying to perform searches.

The underlying error that is being logged is `AlreadyClosedExceptionLucene.Net.Index.IndexReader in EnsureOpen this IndexReader is closed` 

This appears to be related to the following issues:
https://github.com/Shazwazza/Examine/issues/98
https://github.com/umbraco/Umbraco-CMS/issues/8215#issuecomment-651165898
https://github.com/umbraco/Umbraco-CMS/issues/8006

From our investigations our sites are restarted a lot, and we believe that at some point something isn't shutting down properly when it comes to the Examine indexes.

# Request

The feature request I'm proposing is a healthcheck / option in the Examine section that can call `ExamineManager.Stop` to cleanly release all the indexes and dispose of them correctly, and then follow the correct procedure for re-initialising them. (However I'm unsure what this process is as there is no obvious `start` method).

This feature is targeted at apps running on Azure as the errors present themselves (predominantly) since the 8.6 upgrade.

**Comment by Shazwazza** [comment]
Hi @NikRimington , i really want to help everyone resolve issues they are having but in all of these threads people are not responding to my questions which makes it quite difficult to understand the issue and where to look to resolve it. Creating a kill switch isn't going to solve the problem and is just a band-aid that will inevitably cause other problems. I have re-asked further questions on those threads you mention. It would be great if we can keep discussions in one place so if you can respond to this https://github.com/umbraco/Umbraco-CMS/issues/8215#issuecomment-652101038 and please post any logs you have along with more information regarding "From our investigations our sites are restarted a lot" and the other questions I've posted on 8215. Many thanks.

**Comment by Shazwazza** [comment]
Closing this issue as the underlying problem was how Umbraco manages/disposes the index manager.
