### ISSUE TITLE
[v8] Bug. Error Update 8.2.2 to 8.6.3

### ISSUE THREAD

**Issue by bv-it** [umbraco/Umbraco-CMS#8362]
Hello

**Error Update 8.2.2 to 8.6.3**

![1](https://user-images.githubusercontent.com/16698614/86143579-45471500-bafd-11ea-943d-6b7f69b11a02.png)

**Comment by bv-it** [comment]
- 8.2.2 to 8.5.5 > OK (MS SQL)
- 8.2.2 to 8.6.0 > Error (MS SQL)
- 8.2.2 to 8.6.3 > Error (MS SQL)
- 8.5.5 to 8.6.0 > Error (MS SQL)
- 8.5.5 to 8.6.3 > Error (MS SQL)

The database failed to upgrade. ERROR: The database configuration failed with the following message: an Explicit DROP INDEX statement is invalid in the index "umbracoRelationType.IX_umbracoRelationType_alias". It is used to enforce the UNIQUE KEY constraint. Please check log file for additional information (can be found in '/App_Data/Logs/')

**Comment by nul800sebastiaan** [comment]
Thanks @bv-it - this duplicates issue: https://github.com/umbraco/Umbraco-CMS/issues/8291

We haven't found why these constraints are there but they can be safely dropped. See issue https://github.com/umbraco/Umbraco-CMS/issues/8291 and the linked forum posts for more information on how to do this.
