### ISSUE TITLE
Copying a document with nested content replaces values with GUID

### ISSUE THREAD

**Issue by Huguestre** [umbraco/Umbraco-CMS#8391]
**Current:**

When copying an Umbraco document with a NestedContent  property, the NestedContent  in the new document **and** the original document now display the same GUID instead of the original value.

## Umbraco version

I am seeing this issue on Umbraco version: 8.6.3

Reproduction
------------
- Create a document with at least one nestedContent property, ex:
![image](https://user-images.githubusercontent.com/34093212/86752108-0b16cf80-c037-11ea-85d3-5cc3de102dc4.png)
- Copy that document
- Open the document created (published or not)
- Check the nesteContent property, it's displaying a GUID instead of the value:
![image](https://user-images.githubusercontent.com/34093212/86752664-6ba60c80-c037-11ea-86da-f7168e441183.png)

- Open the original document and check the nested content property, it is also displaying the GUID instead of the value.
![image](https://user-images.githubusercontent.com/34093212/86752743-7b255580-c037-11ea-9d5d-d144effe509f.png)

### Expected result

The copied NestedContent should be the same as the original and they should both display the value and not the GUID.

### Actual result

A guid is displayed in both the new and the original nested content properties.

**Comment by Huguestre** [comment]
Might be related to #7133?

**Comment by joepvtl** [comment]
Hi, I think this is because you have named the property 'Key'. Every NestedContent item has a unique key value called 'Key' and I think because you have it named the same way it does some kind of logic on a copy to replace the value of the 'Key'. It would be good if they check these property names/alias and give you a message saying that you can't create a property with that alias.

**Comment by Huguestre** [comment]
Hi @joepvtl  very good shout, thank you! I will give that a go and will report here. It was working with v8.1.3 though, thanks again for the idea!

**Comment by Huguestre** [comment]
Very happy to report that this has 'fixed' it - I used another keyword for my property metadata and that did the trick, thank you very much @joepvtl. 

![image](https://user-images.githubusercontent.com/34093212/86761964-3d77fb00-c03e-11ea-960f-8e89f38248da.png)

I confirm also that this was working with the key 'key' under version v8.1.3, so suspect #7133 had some impact on this behaviour.
