### ISSUE TITLE
Umbraco 8.2.2 Examine: Querying feels like it's running in 'offline state' after startup

### ISSUE THREAD

**Issue by RunnicFusion** [umbraco/Umbraco-CMS#8406]
After some time searching on my client's website doesn't work as espected. When searching for documents at the front-end side of the webpage I've got 0 results. When I open the backoffice of Umbraco and start searching in the same index and use the same search quqery I've got some results back. And the funny thing is: when I start searching at the front-end results are popping up as expected. The first search on front-end side also looks slow compared to the searches I've made after the first one.

## Umbraco version
I am seeing this issue on Umbraco version: 8.2.2

Reproduction
------------

1) webpage restarts (app pool recycle, new release, web.config save for example)
2) index got rebuiled over night (seen in log file)
3) searching at front-end gives 0 results
4) seaching at the backoffice gives results
5) searching at the front-end gives results

## Thinks I've tried
1) rebuilding external index manually
2) saving document in backoffice
3) look for Examine errors in log file

**Comment by nul800sebastiaan** [comment]
Hey there @RunnicFusion - Haven't seen anything like this being reported before and usually when something this obvious is happening we'll get a few reports about it. 
I would recommend you upgrade to the latest version of Umbraco and seeing if that helps, if not then I suspect there's something in your setup that might be causing this. I'd recommend asking around on the forum if it still happens on the latest version, our friendly community can hopefully help you along: https://our.umbraco.com
