### ISSUE TITLE
Nested Content - stopped working

### ISSUE THREAD

**Issue by Ric-Carey** [umbraco/Umbraco-CMS#8448]
Hey,

Just raising this so its on the radar... bit of a strange one.

We've built a site in v8.6.1 - mainly out of Nested Nested Content. 

Was working fine, went live - then I logged in the other day and you couldn't add new items to the nested content. the button was there but clicking it just didnt do anything - there was an error in the console log but it was just to dependency handler and it didn't give any more info than that because of debug mode etc. 

Anyway i was in a bit of a rush, tried the rebuilding dashboard and restart web config and it still didn't work - anyway to make the quick change i needed, i did it on my local version and then transferred it across with usync. This imported fine, and did what i needed it to do as a bit of a hack. Anyway, i still couldn't add new items.

A day later, it was still an issue. I have been busy on other things and I don't think anyone else has been in the CMS over the last week - I logged in and the error was corrected and you could add new items again.  Really dont know what has caused this and what has corrected it - i assuming a process restart server-side perhaps? Anyway just flagging in case anyone else experiences it or it returns - i will keep an eye out. 

Cheers
Ric

**Comment by nul800sebastiaan** [comment]
Hey @Ric-Carey - thanks for reporting, next time the console log details will come in handy. Other than that, we'd need a way to reproduce the problem, maybe have the "invalid" data or something, not sure. I'll close this for now as there's really nothing we can do at this point. Feel free to flag this up if it happens again! 👍
