### ISSUE TITLE
Need ability to name nested content items, so I can find what I want quickly 

### ISSUE THREAD

**Issue by saifobeidat** [umbraco/Umbraco-CMS#8453]
As a user who wants sometimes to edit nested content items I would  have difficulty in searching the item that should be edited, so I need to open each item in the list to find it, which is kind of boring and long process.

I wish that there is an ability to name each item in the nested content, so if I want to edit an item later I would find it quickly.

Example of a named nested content item:

![image](https://user-images.githubusercontent.com/24841143/87918662-6c02c680-ca7f-11ea-99f6-961ea65cd0f6.png)

**Comment by nathanwoulfe** [comment]
Hi @saifobeidat, this is absolutely possible now - https://our.umbraco.com/documentation/getting-started/backoffice/property-editors/built-in-property-editors/Nested-Content/ explains how to configure Nested Content with custom item labels.

**Comment by saifobeidat** [comment]
@nathanwoulfe Perfect! thanks..
