### ISSUE TITLE
All controls return 404 inside nested control

### ISSUE THREAD

**Issue by mitraganesh** [umbraco/Umbraco-CMS#8456]
Hi,

I have upgrade my umbraco from 8.2.0 to 8.6.3. After upgrade my nested control broken. All controls under nested control return 404. No issue when upgrade. 

Like

/umbraco/textbox:1 Failed to load resource: the server responded with a status of 404 (Not Found)

/umbraco/mediapicker Failed to load resource: the server responded with a status of 404 (Not Found)

![Screenshot](https://user-images.githubusercontent.com/42875097/87967385-596aaa80-cadc-11ea-8fa1-0769aac65f78.png)

**Comment by mitraganesh** [comment]
Its working fine this morning. Not sure what happened last night.

**Comment by joecklau** [comment]
@mitraganesh do you remember any insight? I'm facing exactly same issue, scratching head now....

**Comment by joecklau** [comment]
I faced same situation when I try to upgrade from Umbraco 7 to Umbraco 10 with custom backoffice view. The root cause of my case is the usage of no-longer-existing directive `<umb-editor>` in umbraco 7.

    <umb-property property="property" ng-repeat="property in currentTab.properties">
        <umb-editor model="property"></umb-editor>
    </umb-property>

I fixed the case by replacing `<umb-editor>` directive with `<umb-property-editor>`
