### ISSUE TITLE
Groups in Document Types are being removed if there is a duplicate

### ISSUE THREAD

**Issue by rmarcelli** [umbraco/Umbraco-CMS#8465]
## Umbraco version

I am seeing this issue on Umbraco version: 8.5.4

Reproduction
------------

### Bug summary

Groups in Document Types are being removed if there is a duplicate!

### Specifics

I detected this when I tried to add a Group, followed by a Property, and I got the "Duplicate group names not allowed". But this only happens if I do it through a Content of that same Document Type (going in "Info" and then editing/adding through there). It does not happen if we do it through Settings -> Document Types.

I used Umbraco 8.5.4, with Google Chrome Version 84.0.4147.89 (Official Build) (64-bit). I have not checked in other browsers

### Steps to reproduce

Create a Document Type (in my case, it is one that has a Template associated).
Add a Group and a Property in that Group. Save it.

Create a content of that same Document Type, fill out fields and save.
Then, go to the "Info" tab, and edit the Document Type through there.
Add a Group with the name of the previously created Group and add a Property. The objective is to provoke a "duplicate error".
After the error, rename the Group and then save.

After all this, refresh the page of the content, and the original Group should disappear, along with the properties and the content (re-added the properties and the values were gone).

### Expected result

The expected result was to keep the original Group, and not delete it, along with the Properties and it's values.

Expected the same result if I made the same steps through Settings -> Document Types.

### Actual result

Message saying "Duplicate group names not allowed", and deletion of Group that already existed, along with Properties and it's values.

---
_This item has been added to our backlog [AB#7549](https://dev.azure.com/umbraco/243e7927-03b2-44e2-908f-d4ac7ea5daaa/_workitems/edit/7549)_

**Comment by nul800sebastiaan** [comment]
Ah interesting.. I can reproduce this! We'll have to have a look.

![8465](https://user-images.githubusercontent.com/304656/88290723-7c24db00-ccf7-11ea-9704-d7a43a80f7b0.gif)

**Comment by kjac** [comment]
Ha! That's a good one. I have tracked down the issue, will see about a PR later today.

**Comment by kjac** [comment]
PR in #8485

**Comment by nul800sebastiaan** [comment]
Fixed in https://github.com/umbraco/Umbraco-CMS/pull/8485
