### ISSUE TITLE
Add Umbraco Login/Logout events

### ISSUE THREAD

**Issue by LennardF1989** [umbraco/Umbraco-CMS#8470]
Sometimes it's useful to know when a User logged in or logged out of Umbraco so you can prepare/cleanup specific things on the session.  There is currently no proper way to detected either events. 

Would be great if said events can be added to BackOfficeSignInManager, which I suppose would be the right place.

https://github.com/umbraco/Umbraco-CMS/blob/d65041c2503fc85ac4619a4abcd703dcc20f067d/src/Umbraco.Web/Security/BackOfficeSignInManager.cs

Other solution would be adding support for overriding the BackOfficeSignInManager, which is currently not possible the same way like you can with the UserManager.

**Comment by nul800sebastiaan** [comment]
We have AuditEvents you can hook into. Hhaven't tried in v8 but for v7 that would look something like this: https://github.com/PerplexDigital/PerplexDashboards/blob/master/PerplexDashboards/Code/PerplexDashboardsEventHandler.cs#L36

Is there anything you're missing from there?

**Comment by LennardF1989** [comment]
Sleep deprivation must be kicking in, this was exactly what I was looking for. Thank you! ✋
