### ISSUE TITLE
Existing sections in user group section picker should be preselected

### ISSUE THREAD

**Issue by bjarnef** [umbraco/Umbraco-CMS#8487]
I noticed while editing sections for "Administrators" user group after removing media and wanted to re-add media section, the existing sections wasn't preselected, which they used to be.
Instead the list was cleared after selecting "Media" and only "Media" was added to sections list.

I was a bit too fast to save, so I was logged out. When logging back in I only had access to media section.
Tested with latest changes in `v8/contrib` branch.

![image](https://user-images.githubusercontent.com/2919859/88570641-b3b7be00-d03c-11ea-99e6-b30b0047df58.png)

It's quite unfortunate that you as an administrator is able to lock yourself out of the system 🙈 

Here is a demonstration - if saving after these steps I can't access these sections again via UI.

![2020-07-27_19-51-30](https://user-images.githubusercontent.com/2919859/88574524-c1704200-d042-11ea-8edd-4e3343fe59d2.gif)

I think the super user (user id -1) should always have access to users section and should not be able to remove this.

**Comment by bjarnef** [comment]
This is how it looked in Umbraco v8.4.0

![2020-07-27_19-59-12](https://user-images.githubusercontent.com/2919859/88575243-dbf6eb00-d043-11ea-87b1-62ef4afd0cb2.gif)

**Comment by bjarnef** [comment]
It seems `Utilities.copy` doesn't copy the items in the array to `currentSelection` as `angular.copy` did.


**Now**

```
function openSectionPicker() {
            var currentSelection = [];
            
            Utilities.copy(vm.userGroup.sections, currentSelection);

            var sectionPicker = {
                selection: currentSelection,
                submit: function (model) {
                    vm.userGroup.sections = model.selection;
                    editorService.close();
                },
                close: function () {
                    editorService.close();
                }
            };
            editorService.sectionPicker(sectionPicker);
}
```

![image](https://user-images.githubusercontent.com/2919859/88577235-fda5a180-d046-11ea-8c98-75ef9bb054e7.png)


**Before**

```
function openSectionPicker() {
            var currentSelection = [];
            
            angular.copy(vm.userGroup.sections, currentSelection);

            var sectionPicker = {
                selection: currentSelection,
                submit: function (model) {
                    vm.userGroup.sections = model.selection;
                    editorService.close();
                },
                close: function () {
                    editorService.close();
                }
            };
            editorService.sectionPicker(sectionPicker);
}
```

![image](https://user-images.githubusercontent.com/2919859/88577323-1d3cca00-d047-11ea-9cde-8bd1cfad60c8.png)


To test this change `Utilities.copy` to `angular.copy´ here:

https://github.com/umbraco/Umbraco-CMS/blob/bd26cb36ecce2bbe86f11b61dd1a01c314378c89/src/Umbraco.Web.UI.Client/src/views/users/group.controller.js#L104

**Comment by bjarnef** [comment]
Ahh, the new `Utilities.copy` doesn't expose a second optional parameter like `angular.copy` did:
https://docs.angularjs.org/api/ng/function/angular.copy

So it basically copy the array, but now copying it to the destination object, in this case `currentSelection`.
That's why the `currentSelection` is always empty after this change.

On the otherhand `Utilities.extend` does except two parameters:
https://github.com/umbraco/Umbraco-CMS/blob/v8/contrib/src/Umbraco.Web.UI.Client/src/utilities.js#L37

Just like `angular.extend`:
https://docs.angularjs.org/api/ng/function/angular.extend

**Comment by bjarnef** [comment]
PR submitted https://github.com/umbraco/Umbraco-CMS/pull/8488

**Comment by nul800sebastiaan** [comment]
Fixed in https://github.com/umbraco/Umbraco-CMS/pull/8488 - note this was fixed before 8.7.0 was released so shouldn't affect anyone.

Cherry picked to 8.7.0 - ca4f7bf41da058ac5a73f234f38dc9ce979327de

**Comment by bjarnef** [comment]
@nul800sebastiaan regarding the other issue mentioned here, where you are able to remove sections and save, where you via the UI can't get access again (especially if removing "users" section).
Maybe "remove" button shouldn't been available to the super user (-1). But other users with access to "admin" group can remove sections (and potentially remove access to "users" for super user).

Not sure what the best approach is to prevent this? Maybe "users" section should always be available to "admin" group and not possible to remove this under "admin" group?

**Comment by nul800sebastiaan** [comment]
I would love for people to VERY MUCH limit the "super user" at all times, for security reasons. So if something happens by mistakes, it's okay (to me) that it's painful to restore access. 🙂
