### ISSUE TITLE
Getting 404 WebApi

### ISSUE THREAD

**Issue by manishprajapati01** [umbraco/Umbraco-CMS#8491]
I am very very new in Umbraco and ASP .Net. Actually, I have to create a web API in Umbraco so that my frontend can consume. I am using Umbraco 8. What I have done:-

Created a "WeApi" folder in the root.
Created an API Controller called "ProductsController"
Then I am trying to hit "http://localhost:44314/umbraco/api/products/getproducts" but I am getting 404.
Here is the code:-

```csharp
using System.Collections.Generic;

using System.Web.Http;
using Umbraco.Web.WebApi;
using Umbraco.Core.Composing;
using Umbraco.Core;
namespace WebApplication30.Controllers
{
public class ProductsController : UmbracoApiController
{
    [HttpGet]
    public IEnumerable<string> GetProducts()
    {
        return new[] { "Table", "Chair", "Desk", "Computer", "Beer fridge" };
    }
} }
``` 

Do I need to add anything else? any config?

Could anyone help me?

**Comment by nul800sebastiaan** [comment]
Hi there @manishprajapati01, this sounds like an excellent question for the forums where our friendly community can help you find the best solution for your requirements. 
Make sure to head on over to https://our.umbraco.com and ask follow up questions there! 👍
