### ISSUE TITLE
True/False Property Type in an Element Type shows up in the BO as false even if the value is set to true

### ISSUE THREAD

**Issue by deekoulos** [umbraco/Umbraco-CMS#8516]
Umbraco v. 8.6.3

### Steps to reproduce

Create an element type with a property type "True/False"
![image](https://user-images.githubusercontent.com/55948134/88856127-3d5dbc00-d1f4-11ea-8408-0406d4a8a5d2.png)

Assign the element type to a member type
![image](https://user-images.githubusercontent.com/55948134/88856180-55cdd680-d1f4-11ea-9eaa-141d59c9d70c.png)

Create a member of that member type
![image](https://user-images.githubusercontent.com/55948134/88856258-76962c00-d1f4-11ea-8362-a98dff7558a6.png)

Programmatically create and set an item of the element type and add it to the member
![image](https://user-images.githubusercontent.com/55948134/88856358-a5140700-d1f4-11ea-9a39-7ed93aba57b4.png)

Ensure that the value is set to true and the alias is correct
![image](https://user-images.githubusercontent.com/55948134/88857175-11433a80-d1f6-11ea-9b00-502f0f7c689a.png)

Save the member programmatically and check the value in the BO for the member
![image](https://user-images.githubusercontent.com/55948134/88857294-4cde0480-d1f6-11ea-9cb2-17e4a8a3825e.png)

Now there are 2 scneraios: 1) The value true is not saved properly, since the BO is showing up false, 2) The value is set to true, but the BO is showing up the wrong state of the property type. 

So, after saving the member, get the same member again and check the real values, retrieved from the MemberService for that property type:
![image](https://user-images.githubusercontent.com/55948134/88857084-e953d700-d1f5-11ea-825f-244721cb03c3.png)

So it seems that the value is stored correctly, but in the BO, it always shows up the false state. It only displays the correct true state, if you save the value true through the back office.

**Comment by nul800sebastiaan** [comment]
Due to legacy reasons, this is stored as 1 for true and 0 for false, it should work if you give it a 1 or a 0 from your code.

**Comment by deekoulos** [comment]
thanks @nul800sebastiaan it worked!
