### ISSUE TITLE
New icon directive makes tags look a little weird

### ISSUE THREAD

**Issue by nul800sebastiaan** [umbraco/Umbraco-CMS#8526]
Now that #5293 has been merged some icons behave a little different than they did before. I just noticed that the tags delete icon is a too dark and is also causing a lot of extra padding on the tag itself.

![image](https://user-images.githubusercontent.com/304656/88939666-14d2d200-d287-11ea-9bb5-7e23b1f596d5.png)

![image](https://user-images.githubusercontent.com/304656/88939673-17352c00-d287-11ea-9ba2-4d8a46985c9c.png)

**Comment by bjarnef** [comment]
It does indeed not look as it should.
PR submitted: https://github.com/umbraco/Umbraco-CMS/pull/8528

**Comment by nul800sebastiaan** [comment]
Fixed in https://github.com/umbraco/Umbraco-CMS/pull/8528 - thanks again Bjarne!
