### ISSUE TITLE
Embed is editable from richtext editor but not from grid editor

### ISSUE THREAD

**Issue by bjarnef** [umbraco/Umbraco-CMS#8575]
About a year ago I submitted this PR https://github.com/umbraco/Umbraco-CMS/pull/4899 to select an embed in grid editor and e.g. edit dimensions.

However it doesn't seem this is possible anymore when checking latest changes in `v8/contrib` branch.

![2020-08-04_10-34-32](https://user-images.githubusercontent.com/2919859/89272327-46102100-d63e-11ea-9513-3127fda314f1.gif)

However this PR https://github.com/umbraco/Umbraco-CMS/pull/6341 seems to make it possible to edit existing embed in TinyMCE editor.

![2020-08-04_10-37-38](https://user-images.githubusercontent.com/2919859/89272622-b5861080-d63e-11ea-95de-c57ad3d1820a.gif)

It would be great it was consistent. Furthermore it probably don't need to reload the embed on blur in width and height field, when the values haven't changed.

**Comment by nul800sebastiaan** [comment]
Fixed in https://github.com/umbraco/Umbraco-CMS/pull/8576

Cherry picked for 8.7.0 in 7d8a6ce4fd778374e2f0c5ea94b36f7019852761
