### ISSUE TITLE
Unable to assign the correct member groups via the backoffice in Umbraco 8

### ISSUE THREAD

**Issue by e-states** [umbraco/Umbraco-CMS#8604]
https://drive.google.com/file/d/14jVATGcqbS2OonqE8qURUc0Q79qIBtPR/view

The above video highlights the problem, I'm unable to assign group public access, seems like there is a bug in assigning member groups. It always picks the last one irrespective of what I choose.

**Comment by bjarnef** [comment]
Which version of Umbraco are you using?

I can't reproduce this with latest changes in `v8/contrib` branch.

![2020-08-06_19-09-30](https://user-images.githubusercontent.com/2919859/89561285-8fb46380-d818-11ea-93a5-03e998350f75.gif)

**Comment by e-states** [comment]
https://our.umbraco.com/download/releases/863 

Try with custom Member Groups and custom Members. That is what I did, Could it be that something that needs to be implemented, isn't? but then I'll prefer a crash instead of this behavior.

**Comment by nul800sebastiaan** [comment]
@e-states How do we hook up this custom groupservice so it creates member groups in the backoffice please? I added this code to a site, and I have no membergroups to choose from.

**Comment by e-states** [comment]
@nul800sebastiaan 
`<membership defaultProvider="UmbracoMembershipProvider" userIsOnlineTimeWindow="15">
	  <providers>
		<clear />
		<add name="UmbracoMembershipProvider" type="Estates.Core.Members.EstatesMembershipProvider, Estates.Core" minRequiredNonalphanumericCharacters="0" minRequiredPasswordLength="10" useLegacyEncoding="false" enablePasswordRetrieval="false" enablePasswordReset="false" requiresQuestionAndAnswer="false" defaultMemberTypeAlias="Member" passwordFormat="Hashed" allowManuallyChangingPassword="false" />`

Some Web Config changes and then I implemented custom membership.
public class EstatesRoleProvider : RoleProvider
&
public class EstatesMembershipProvider : UmbracoMembershipProviderBase

**Comment by e-states** [comment]
`using System;
using System.Web.Security;
using Umbraco.Core.Security;

namespace Estates.Core.Members
{
	public class EstatesMembershipProvider : UmbracoMembershipProviderBase
	{
		public override string DefaultMemberTypeAlias => throw new NotImplementedException();

		public override bool DeleteUser(string username, bool deleteAllRelatedData)
		{
			throw new NotImplementedException();
		}

		public override MembershipUserCollection FindUsersByEmail(string emailToMatch, int pageIndex, int pageSize, out int totalRecords)
		{
			throw new NotImplementedException();
		}

		public override MembershipUserCollection FindUsersByName(string usernameToMatch, int pageIndex, int pageSize, out int totalRecords)
		{
			throw new NotImplementedException();
		}

		public override MembershipUserCollection GetAllUsers(int pageIndex, int pageSize, out int totalRecords)
		{
			throw new NotImplementedException();
		}

		public override int GetNumberOfUsersOnline()
		{
			throw new NotImplementedException();
		}

		public override MembershipUser GetUser(object providerUserKey, bool userIsOnline)
		{
			throw new NotImplementedException();
		}

		public override MembershipUser GetUser(string username, bool userIsOnline)
		{
			throw new NotImplementedException();
		}

		public override string GetUserNameByEmail(string email)
		{
			throw new NotImplementedException();
		}

		public override bool UnlockUser(string userName)
		{
			throw new NotImplementedException();
		}

		public override void UpdateUser(MembershipUser user)
		{
			throw new NotImplementedException();
		}

		public override bool ValidateUser(string username, string password)
		{
			if (string.IsNullOrWhiteSpace(username) || string.IsNullOrWhiteSpace(password))
			{
				return false;
			}
			return uSignIn.Auth.VerifyPassword(username, password);
		}
		
		protected override bool PerformChangePassword(string username, string oldPassword, string newPassword)
		{
			throw new NotImplementedException();
		}

		protected override bool PerformChangePasswordQuestionAndAnswer(string username, string password, string newPasswordQuestion, string newPasswordAnswer)
		{
			throw new NotImplementedException();
		}

		protected override MembershipUser PerformCreateUser(string memberTypeAlias, string username, string password, string email, string passwordQuestion, string passwordAnswer, bool isApproved, object providerUserKey, out MembershipCreateStatus status)
		{
			throw new NotImplementedException();
		}

		protected override string PerformGetPassword(string username, string answer)
		{
			throw new NotImplementedException();
		}

		protected override string PerformResetPassword(string username, string answer, string generatedPassword)
		{
			throw new NotImplementedException();
		}
	}
}`

and

`using System;
using System.Linq;
using System.Web.Security;

namespace Estates.Core.Members
{
	public class EstatesRoleProvider : RoleProvider
	{
		public override string ApplicationName { get => "UmbracoRoleProvider"; set => throw new NotImplementedException(); }

		public override void AddUsersToRoles(string[] usernames, string[] roleNames)
		{
			throw new NotImplementedException();
		}

		public override void CreateRole(string roleName)
		{
			throw new NotImplementedException();
		}

		public override bool DeleteRole(string roleName, bool throwOnPopulatedRole)
		{
			throw new NotImplementedException();
		}

		public override string[] FindUsersInRole(string roleName, string usernameToMatch)
		{
			throw new NotImplementedException();
		}

		public override string[] GetAllRoles()
		{
			return new EstatesGroupService().GetAll().Select(g => g.Name).ToArray();
		}

		public override string[] GetRolesForUser(string username)
		{
			var memberProfile = uSignIn.Auth.GetUserProfile(username); 
			if (memberProfile?.UserId == username)
			{
				if (memberProfile.MobileNumbers.Any() && memberProfile.Emails.Any())
				{
					return new EstatesGroupService().GetAll().Select(g => g.Name).ToArray();
				}
				else 
				{
					return new EstatesGroupService().GetAll().Where(r => r.Name == EstatesGroupService.UserWithInValidProfileUmbracoName).Select(g => g.Name).ToArray();
				}
			}
			return Array.Empty<string>();
		}

		public override string[] GetUsersInRole(string roleName)
		{
			throw new NotImplementedException();
		}

		public override bool IsUserInRole(string username, string roleName)
		{
			throw new NotImplementedException();
		}

		public override void RemoveUsersFromRoles(string[] usernames, string[] roleNames)
		{
			throw new NotImplementedException();
		}

		public override bool RoleExists(string roleName)
		{
			throw new NotImplementedException();
		}
	}
}
`

**Comment by bjarnef** [comment]
@e-states I tried implementation your custom MembershipProvider using latest changes in `v8/contrib`.
Instead of using "UmbracoRoleProvider" string you could also use the constants in `Umbraco.Core.Constants.Conventions.Member.UmbracoRoleProviderName`: https://github.com/umbraco/Umbraco-CMS/blob/a9d45413c89d67280ce54c7fd4182e90323bab6c/src/Umbraco.Core/Constants-Conventions.cs#L139

We can however not see what your `uSignIn` class does, so for `GetRolesForUser()` I have just returned the following:

```
public override string[] GetRolesForUser(string username)
{
    //var memberProfile = uSignIn.Auth.GetUserProfile(username); 
    //if (memberProfile?.UserId == username)
    //{
        //if (memberProfile.MobileNumbers.Any() && memberProfile.Emails.Any())
        //{
        //	return new EstatesGroupService().GetAll().Select(g => g.Name).ToArray();
        //}
        //else 
        //{
            return new EstatesGroupService().GetAll().Where(r => r.Name == EstatesGroupService.UserWithInValidProfileUmbracoName).Select(g => g.Name).ToArray();
        //}
    //}
    //return Array.Empty<string>();
}
```

However I could reproduce the same issue as in your video:

![2020-08-18_11-20-47](https://user-images.githubusercontent.com/2919859/90495617-1b958c00-e145-11ea-871b-4e862f3b6de6.gif)

Could you please open the browser console, to check if any errors are shown? It might not be related to a custom MembershipProvider, but could be a javascript error in a specific scenario.


![image](https://user-images.githubusercontent.com/2919859/90495908-74fdbb00-e145-11ea-8a4e-baf6f891f682.png)

Furthermore with the code you have submitted, I get an error when accessing a member. Probably because one of the methods not been implemented.

In latest changes in `v8/contrib` the interface `IMemberGroupService` also has the following method:

```
public IMemberGroup GetById(Guid id)
{
      throw new NotImplementedException();
}
```

**Comment by e-states** [comment]
Thanks for the tips on using the constant, instead of the string.
About the error, I'm aware of not implementing the functions to get the member information, I only plan to use Umbraco for managing roles of the members, about which pages they can access. Hence I have skipped implementing most of the functions in the interface. (I hope that this is not the root cause of the issue) :)

I'm happy that you got it working with my code, but seems like I still have the issue. I looked into the console and didn't find any errors, but I noticed something else: both roles seem to have the id '0', could that be a clue?

![image](https://user-images.githubusercontent.com/69314545/91495647-27a6e980-e8bb-11ea-96b4-cfd9f151aa5d.png)
These are details from the network tab in the developer console.

**Comment by e-states** [comment]
OMG: that was the problem. 

```
public IEnumerable<IMemberGroup> GetAll()
		{
			return new[] { new MemberGroup() { Name = UserWithValidProfileUmbracoName, Id = 0 }, new MemberGroup() { Name = UserWithInValidProfileUmbracoName, Id = 1 } };
		}

```

This fixed it. I think we need a nice documentation about creating Custom membership providers in Umbraco 8. or does this already exist?
