### ISSUE TITLE
Bogus.dll and Umbraco.TestData.dll added in v8.6.4 release

### ISSUE THREAD

**Issue by leekelleher** [umbraco/Umbraco-CMS#8616]
More of a question than bug report, I've noticed in latest v8.6.4 (released today, but _at the time of writing,_ not yet announced), comes with a couple of new DLLs, namely Bogus.dll and Umbraco.TestData.dll (diffs here: https://github.com/umbraco/Umbraco-CMS/compare/release-8.6.3...release-8.6.4)

**Are these meant to be bundled with the v8.6.4 release?**

If so, cool, ignore me. _(Although seems strange to add new dependencies - especially on Bogus - in a patch release)._

**Comment by nul800sebastiaan** [comment]
Oh no.. sharp observation, thanks @leekelleher! The testdata dll seems to have appeared here: https://github.com/umbraco/Umbraco-CMS/commit/f0dea44b4de0bae48a68bb7d963d316f29363d79#diff-3f867fef6d4fc971daa9cfa6d8ccbb17

I would assume that @Shazwazza accidentally included it in the wrong csproj? Can you clarify Shannon?

**Comment by Shazwazza** [comment]
Yes but I thought I removed that accidental reference some weeks ago. It won't be in the nuget release though? Just the zip if there's still accidentally a reference. We could edit and republish the zip.

**Comment by leekelleher** [comment]
I should have added, I'd spotted this from the ZIP download from Our. _(As part of doing my [Unofficial Archive](http://code.leekelleher.com/umbraco/archive/) diffs thing)._ I've no idea about the NuGet release.

**Comment by nul800sebastiaan** [comment]
Right, I checked the NuGets and they're not affected, this is specifically a problem for the zip file, which I've now re-uploaded without those dlls in it. Thanks for letting us know @leekelleher 👍

**Comment by nul800sebastiaan** [comment]
Also fixed this now so that we don't accidentally build this wrong again https://github.com/umbraco/Umbraco-CMS/commit/425d0ba544c897328c7efdf96c2532a49fbadef4

**Comment by stefankip** [comment]
Guys, I just spotted these files on the Umbraco Cloud 8.6.4 update commit:
![image](https://user-images.githubusercontent.com/46313552/90228356-60a08200-de16-11ea-9019-48451542c97e.png)

**Comment by nul800sebastiaan** [comment]
@stefankip Argh, so for the upgrader we do use the zip download. 🤦 

We'll fix it and remove them again during the next upgrade cycle for 8.6. Thanks for letting us know! 👍
