### ISSUE TITLE
deleting something on interface

### ISSUE THREAD

**Issue by erolakgul** [umbraco/Umbraco-CMS#8618]
When i want to delete some tag or anything else returns error 

"Invalid column name 'propertytypeid'."
System.Data.SqlClient.SqlException: Invalid column name 'propertytypeid'.

So, when i watch on the sql profiler, i saw the script like "sp_executesql N'DELETE FROM [umbracoPropertyData] WHERE **propertytypeid** = @0'" . After that, when i opened umbracoPropertyData table on the sql server, i saw the column name like **propertyTypeId** .

my database collation name => Turkish_CS_AS

## Umbraco version 

I am seeing this issue on Umbraco version: 8.6.3

I guess, main issue is integer field.

what should i do to solve this problem ?

**Comment by erolakgul** [comment]
yes i found solve. Umbraco.Core.Persistence.Repositories.Implement.ContentTypeRepositoryBase => 1187.line  i change the code propertytypeid => propertyTypeId.

**Comment by kjac** [comment]
@erolakgul I believe you need a case insensitive collation for things to work. see [this thread](https://our.umbraco.com/forum/using-umbraco-and-getting-started/86852-umbraco-sql-collation-issue) on Our.

**Comment by erolakgul** [comment]
thank you your answer kenn 👍 

In turkish, "I" and "i" are different characters. İ is upper case of i. Then "I" is upper case of ı. If we chosed turkish_ci... it does not work 1187. line in ContentTypeRepositoryBase.cs because of propertytypeid. It must be propertytypeid => propertyTypeId.

Or Latin1_General_CI_AS, it works.

had used this script, i had changed collation;

ALTER DATABASE DBName SET SINGLE_USER WITH ROLLBACK IMMEDIATE
ALTER DATABASE DBName COLLATE Latin1_General_CI_AS
ALTER DATABASE DBName SET MULTI_USER

**Comment by kjac** [comment]
@erolakgul thanks for the feedback. Have you noticed any challenges from using `Latin1_General_CI_AS` as collation?

**Comment by erolakgul** [comment]
Hi, I haven't seen a problem since I changed it.

> @erolakgul thanks for the feedback. Have you noticed any challenges from using `Latin1_General_CI_AS` as collation?

**Comment by nul800sebastiaan** [comment]
I'll close this issue now, recommend using a collation like the one mentioned above indeed.
