### ISSUE TITLE
jQuery dependency vulnerability on Umbraco 7.x.x

### ISSUE THREAD

**Issue by balsa0** [umbraco/Umbraco-CMS#8633]
Issue #8327 states that recent XSS vulnerability findings in jQuery "should not affect any of Umbraco" (v8). Does this also apply to version 7.x.x (specifically 7.15.5) too?

**Comment by nul800sebastiaan** [comment]
Correct, we never used the affected functionality. In v7 we're on version 2.2.4 and not using the methods that are marked as vulnerabilities there either (https://www.cvedetails.com/vulnerability-list/vendor_id-6538/product_id-11031/version_id-286394/Jquery-Jquery-2.2.4.html). 

We will stick with the v2 version in v7 unless there's critical security issues that will require  us to take action.
