### ISSUE TITLE
Problem with user invite email and SendGrid

### ISSUE THREAD

**Issue by johansuperstar** [umbraco/Umbraco-CMS#8644]
We're currently migrating an Umbraco 7.9.2 application to Azure, and have decided to use Sendgrid for sending mail. However, we're now facing issues with the user invite mail, when trying to invite a user the following exception is thrown "System.Net.Mail.SmtpException: The server committed a protocol violation". Sendgrid is configured in mailSettings in web.config according to this article https://sendgrid.com/docs/for-developers/sending-email/v2-csharp-code-example/#using-nets-built-in-smtp-library. I've also tried adding the enableSsl attribute without success. 

The issue occurs both locally and when deployed on Azure. I'm not able to reproduce the same error when sending mail with SmtpClient and the same configuration in an empty MVC application.

## Umbraco version

I am seeing this issue on Umbraco version: 7.9.2

Reproduction
------------

### Steps to reproduce
- Configure SendGrid according to https://sendgrid.com/docs/for-developers/sending-email/v2-csharp-code-example/#using-nets-built-in-smtp-library.
- Go to Users, and submit form under "Invite user".

### Expected result
Mail is sent correctly.

### Actual result
SmtpException is thrown.

**Comment by nul800sebastiaan** [comment]
Strange, many people are successfully using Sendgrid for sending emails!

This sounds like an excellent question for the forums where our friendly community can help you find the best solution for your requirements. 
Make sure to head on over to https://our.umbraco.com and ask follow up questions there! 👍
