### ISSUE TITLE
V8.7RC: Adding a new block definition creates a template on disk

### ISSUE THREAD

**Issue by nul800sebastiaan** [umbraco/Umbraco-CMS#8646]
In 8.7, you can add a Block List datatype to your document type. You need to configure the Block List and in the process add existing element types to it or create a new one. 

![image](https://user-images.githubusercontent.com/304656/90525493-9ffd0480-e16f-11ea-82ae-29093548bfd1.png)

When you do this, a new document type editor will appear for you which is automatically set to be an element type:

![image](https://user-images.githubusercontent.com/304656/90525634-c1f68700-e16f-11ea-8ddc-2bf59dd72799.png)

However, when you give this new element type a name, it will still create a template for you on disk. We don't need a template for an element type, it's not going to be an actual page. So this needs to be prevented.

We'd love some community help with fixing this, for now this will be a known bug for 8.7.0.

---
_This item has been added to our backlog [AB#8006](https://dev.azure.com/umbraco/243e7927-03b2-44e2-908f-d4ac7ea5daaa/_workitems/edit/8006)_

**Comment by poornimanayar** [comment]
Fixed in #9017
