### ISSUE TITLE
Suggestion: Switch Available Editors and Reuse tabs in the Document Types editor

### ISSUE THREAD

**Issue by nul800sebastiaan** [umbraco/Umbraco-CMS#8647]
<p>I would suggest switching the Available Editors and Reuse tabs in the Document Types editor.</p>
<p>I believe the majority of use are accustom to planning out, creating, and reusing the necessary datatypes. With the new Document Type editor you have to click the reuse tab in order to get to the existing datatypes. 9 out 10 times I am going to click Reuse. Also, the interface encourages creating a new datatype for every field, which probably wouldn't be that great of an idea.</p>
<p>Issue imported from old issue tracker: <a href="https://issues.umbraco.org/issue/U4-7947">U4-7947</a><p><strong>Note: This issue has attachments in the original issue</strong></p>

**Comment by nul800sebastiaan** [comment]
Requested by @dnwhte originally on the old issue tracker, we've given this a new spin. When you are selecting a property editor to use on your document type, there are no more tabs for "reuse" and "available editors", instead you get to choose each type of available editor for example a textbox: 

![image](https://user-images.githubusercontent.com/304656/90528033-785b6b80-e172-11ea-998f-daea091845d1.png)

And then you can pick an existing configuration, or create a new one: 

![image](https://user-images.githubusercontent.com/304656/90528197-a476ec80-e172-11ea-8b07-ee9bb5ea8fe2.png)

As before, when you do a search you get existing configurations and can also choose to create a new one: 

![image](https://user-images.githubusercontent.com/304656/90528291-be183400-e172-11ea-96e3-2ccde4591e0e.png)

**Comment by nielslyngsoe** [comment]
For reference, this UX change was done in this PR: https://github.com/umbraco/Umbraco-CMS/pull/5677
