### ISSUE TITLE
Installing 7.15.5 on empty project

### ISSUE THREAD

**Issue by croban** [umbraco/Umbraco-CMS#8649]
I have tried to install 7.15.5 inside empty mvc .net framework project and it can not finde imageprocessor.web.config 

Severity	Code	Description	Project	File	Line	Suppression State
Error		Unable to find a version of 'ImageProcessor.Web.Config' that is compatible with 'UmbracoCms 7.15.5 constraint: ImageProcessor.Web.Config (>= 2.5.0.100 && < 3.0.0)'.

**Comment by SteveVaneeckhout** [comment]
https://www.nuget.org/packages/ImageProcessor.Web.Config/

Version 2.6 is available so it should work. Which version of the .NET Framework are your targetting? You might have selected a very old version. You need at least 4.5.2.

**Comment by nul800sebastiaan** [comment]
Hi there @croban, this sounds like an excellent question for the forums where our friendly community can help you find the best solution for your requirements. 
Make sure to head on over to https://our.umbraco.com and ask follow up questions there! 👍
