### ISSUE TITLE
Alt Templates using the /templateAlias approach does not work

### ISSUE THREAD

**Issue by NikRimington** [umbraco/Umbraco-CMS#8650]
According to the [docs](https://our.umbraco.com/Documentation/Reference/Routing/custom-controllers#how-can-a-page-be-requested-via-two-different-templates) it should be possible to do `/page/altTemplateAlias` to tell a page to load using an alternative template. However, this does not appear to be the case any more. Testing this on a site with an alternative template set up results in a 404 page not found error.

From examining the source code it looks like the content finder responsible for finding content this way has been disabled:
[source code link](https://github.com/umbraco/Umbraco-CMS/blob/5d93d8e874f0d9a705ed5c3a4e91fb5491e21f3e/src/Umbraco.Web/Runtime/WebInitialComposer.cs#L205)

This raises 2 question... 

1. Why?
2. Is it safe to re-enable it?

**Comment by marcemarc** [comment]
@NikRiminton have seen this raised a lot in the forum - see previous issue: https://github.com/umbraco/Umbraco-CMS/issues/5290

where it has been raised an issue before - I added a note here: https://our.umbraco.com/Documentation/Reference/Routing/Request-Pipeline/IContentFinder#adding-and-removing-icontentfinders

but looks like it's mentioned in other places in the docs too without the note :-(

but don't know why exactly - other than it was to discourage it's use, as it was an 'odd' convention... but yes the ContentFinderByUrlAndTemplate works if added back in.

**Comment by NikRimington** [comment]
@marcemarc , okay that's cool, So I've added a PR to docs to update the details there on the fact it's disabled by default but can be added back. That answers my query really :-)
