### ISSUE TITLE
U8 Dictionary item not displaying what is the max allowed number of characters when you exceed it

### ISSUE THREAD

**Issue by Baracuda011** [umbraco/Umbraco-CMS#8656]
When I try to save a lengthier dictionary item containing some HTML, ie. I only get the error that something is wrong and not that I have exceeded the max allowed number of characters.

## Umbraco version

I am seeing this issue on Umbraco version: Umbraco Cloud 8.6.4

Reproduction
------------

When I try to save a lengthier dictionary item containing some HTML, ie. I only get the error that something is wrong and not that I have exceeded the max allowed number of characters.

### Bug summary

- No info about max allowed number of characters.
- No info about by how many characters I have exceeded the limit like you have for text data types.

### Specifics

- Any browser
- Umbraco Cloud 8.6.4

### Steps to reproduce

Past the longer text into a dictionary item.

### Expected result

Saved dictionary item or info that I have exceeded the max number of characters and what that number is.

### Actual result

Just a notification that something went wrong without any explanation.

https://snipboard.io/VE9SBH.jpg

**Comment by NikRimington** [comment]
@Baracuda011, just been examining the Umbraco source and in turn and Umbraco database. From this I can see that the max length the content of a dictionary item can be (per culture) is 1000 characters. I imagine anything over this either won't save at all, or will be truncated.

**Comment by Baracuda011** [comment]
@NikRimington, I kinda feel stupid now when I saw the characters limit :D

I do agree that storing this kind of info in the dictionary is not the best practice at all but at the given circumstances at the time this was the quickest solution.

I still think that a character counter of some kind would improve the user experience.

Thanks for the clarification.


Cheers,
Nemanja.

**Comment by NikRimington** [comment]
Oh I agree, if a field has a character limit there should be some sort of warning. Might be a nice feature request :-D

**Comment by Baracuda011** [comment]
@NikRimington agreed. Just created one.
