### ISSUE TITLE
Content disappears from the back office in 7.15.5

### ISSUE THREAD

**Issue by dshipston** [umbraco/Umbraco-CMS#8658]
For the past few years we have been suffering from a very random issue where content disapears from a page in the back office and if you don't notice and go ahead with another edit on the page and publish it, the missing content goes from the front end as you might expect.

This has been happening in 7.12.x as well as in our newly upgrade version 7.15.5 

**Symptom**
Every now and again, we notice in the back office, that various pages show the green dot marker indicating that the page has been changed and saved - but not published. 

Initially we thought that a less experienced editor might be messing things up, so we lived with this for a while and just reinstated the missing content by copying it back from the front end.

The content that goes missing is not conisitent either, sometimes it's text from a text editor and sometimes it can be placed macros on the page - and other times it can be both! but it's not all of the content on the page, just bits.

Living with this for sometime, we eventually started to keep a closer eye on this and we've now come to the conclusion that something weird is happening in Umbraco and something that is NOT down to any of us humans.

Recently I upgraded the site to 7.15.5 and after the upgrade I took a straight copy of the site and database and create seperate UAT server and DEV server copies for the team to work on - all identical and with all pages published and working fine.

The web team only work on the local UAT server and then use Courier to push changes to the LIVE site, which works fine.

I'm the only one with access to the DEV server as that is where I develop new features to later be pushed to the UAT server for the web team to approve before going live.

A couple of weeks ago I noticed a series of pages in the back office of the DEV site, all showing the green "saved" dot, which struck me as weird as I'd definately not been anywhere near any of the page content on the site, as I'd only been working on a new site menu.

I then checked the UAT and LIVE servers and found that they too had the SAME pages highlighted with the green "saved" indicator.

So we now have 3 seperate sites on 3 seperate servers all showing the same pages as having saved edits even though these pages haven't been edited or saved.

Checking the page audit doesn't help either as it doesn't show a recent save for the pages in question. However we have also noticed that sometimes (and not always) the simple act of clicking on a page to open it in the back office can cause a save action! I've experienced this myself by opening a page and going straight to  'Actions > Audit Trail' and seeing that it shows I just did a save, when I clearly haven't. Again this onlty happens sometimes and not all of the time.

I know this is going to be a real puzzler and difficult to fix if you can't replicate it, but Dennis from Umbraco support suggested I just post this here to see if anyone has a clue as to what could or might be happening?

At this stage any suggestions or advice would be greatfully recieved.

Dave

**Comment by nul800sebastiaan** [comment]
Hi @dshipston, that sounds really strange indeed. I would suspect a plugin that might be doing something under very specific circumstances. 

It's good to have the problem out here in public, but I also suggest you post this on the forum at https://our.umbraco.com to get some more eyes on it.
For issues on the issue tracker here, we need some way to reproduce the problem and as you've already noted, it appears "random". Therefore I'm going to close this issue. Of course if you ever have new information that could help diagnose a cause then we're happy to open this issue again.

Sorry you are having this problem and best of luck with it, hopefully the source if it can be found one day!
