### ISSUE TITLE
User status filter values not always displayed

### ISSUE THREAD

**Issue by kristianstruct** [umbraco/Umbraco-CMS#8670]
User status filter values are not displayed in user list if number of items contains number 0

Filter in `Umbraco-CMS\src\Umbraco.Web.UI.Client\src\views\users\views\users\users.html` checks for number of items contain the number 0. This should be a check for count > 0. 

` <umb-dropdown-item ng-repeat="userState in vm.userStatesFilter | filter:{ count: '!0', key: '!All'}" style="padding: 8px 20px 8px 16px;">`

## Umbraco version

I am seeing this issue on Umbraco version: 7.13.2

Reproduction
------------

### Bug summary

When number of users in a specific status contains number 0, the status value is not included in the user list 
![image](https://user-images.githubusercontent.com/60959097/90751799-dd2fd680-e2d6-11ea-90de-9dc82afd7b6f.png)

### Specifics

/umbraco#/users/users/overview?subview=users

### Steps to reproduce

Create 10 new users. Leave in state inactive

### Expected result

"Inactive" should be selectable in status drop down

### Actual result

Status is not inactive

**Comment by nul800sebastiaan** [comment]
Thanks! This has been fixed in 7.15.5: https://github.com/umbraco/Umbraco-CMS/issues/7780
