### ISSUE TITLE
V8.7RC - Block Editor: NC-property with mutliple elementypes doesn't work in "infiniteeditor-panel." but it works inline

### ISSUE THREAD

**Issue by madsoulswe** [umbraco/Umbraco-CMS#8680]
I am seeing this issue on Umbraco version: 8.7RC

Reproduction
------------

1. Create two simple element types.
2. Create Nested Content with the element types from step 1.
3. Create another element type that contains the Nested Content from step 2.
4. Create a Block list editor, add the element type from step 3.
5. Create a Content Type and add the Block List editor from step 4.
6. Add the Content Type as Content.

When you first try to edit the page you will se something like this, but after you close "infiniteeditor"; "add content" in NC will stop working.

The console shows no errors.

![image](https://user-images.githubusercontent.com/7071187/90799398-741a8400-e313-11ea-8846-e5dfd24216e4.png)
![image](https://user-images.githubusercontent.com/7071187/90799957-408c2980-e314-11ea-91fe-2d95b48e2678.png)

**Comment by clausjensen** [comment]
Closing this issue as we will be preventing usage of the nested content editor inside the block editor. No longer relevant - see https://github.com/umbraco/Umbraco-CMS/pull/8732 for details
