### ISSUE TITLE
V8.7RC Overlapping text in property editor picker

### ISSUE THREAD

**Issue by arknu** [umbraco/Umbraco-CMS#8702]
The new document type picker in 8.7 can have overlapping text when the name contains a long word without any spaces:

![image](https://user-images.githubusercontent.com/4654741/90883889-f73ce800-e3ae-11ea-8190-4ce38583f0c3.png)

### Steps to reproduce

Create a property editor configuration and/or property editor with a long single-word name. Find it in the property editor picker and observe how the names are overlapping.

### Expected result

The text is overlapping

### Actual result

No text overlap should occur

**Comment by warrenbuckley** [comment]
Fixed by PR - #8982

**Comment by arknu** [comment]
Is this supposed to be fixed in 8.8? Im still seeing the issue in 8.8...
![image](https://user-images.githubusercontent.com/4654741/95062676-97e82c80-06fd-11eb-91d3-3c44ea0730da.png)

**Comment by nul800sebastiaan** [comment]
It will be fixed in 8.8.1 as well, didn't make it to 8.8.0 unfortunately.
