### ISSUE TITLE
V8.7RC Nested Content inside the Block Editor can't add new items if clipboard is populated

### ISSUE THREAD

**Issue by marcemarc** [umbraco/Umbraco-CMS#8707]
This is working with the V8.7 RC testing out the new Block Editor - and this is the 'first thing I tried' eg adding Nested Content item within A Block Editor 'Block'.

A common scenario with this kind of editor is a row with 'three' or 'two' or 'four' boxes populated by the editor, and so in Stacked Content and the like you'll create a 'Row' and allow a Nested Content Property editor within, restricted to create 4 items max...

This works - however when you have a Nested Content item added to the clipboard - and you go to create a new Nested Content item in the Block Editor, 'nothing happens' and I think this is because it knows there is an item on the clipboard, and it wants to show you the choice of using the clipboard item instead of a new blank item - and it can't launch the dialog to offer this choice... and so in this circumstance it's not possible to add a new Nested Content item within a block editor if you have a Nested Content item on the clipboard!

Does that make sense as an explanation?

Basically create a new Element Type called 'Content Block' - give it a 'title-textbox' and a 'description-rich text editor' fields.

Create a new Element Type that has a Nested Content Property called 'Nested Block Row' that can 'repeat' the 'Content Block' item you just created.

Create a new Block Editor Data Type and allow the 'Nested Block Row' to be repeated within it.

Create a new Document Type, and add the Block Editor Data Type AND the Nested Block Row Data Types to it.

Create content based on this Document Type.

First, add some content to the 'Nested Content Property editor and copy it to the clipboard.

![image](https://user-images.githubusercontent.com/260802/90915127-ea33ef00-e3d6-11ea-8916-dafdcd6e3841.png)

Then add a new Nested Block Row to the Block Editor, and you'll find that it will open the infinite editor and present you with the button to add the Nested Content item - but pressing the Add button will do nothing. 

![image](https://user-images.githubusercontent.com/260802/90915192-06379080-e3d7-11ea-86de-b4c04c221b5b.png)

(or maybe it loads the dialog for choosing between clipboard or new item, behind the infinite editor?)

If you go back to the Nested Content editor outside of the block editor, - it will prompt you to use the clipboard contents or create a new item - you can delete the clipboard item from this dialog

![image](https://user-images.githubusercontent.com/260802/90915371-531b6700-e3d7-11ea-83e5-a059258e32a6.png)

now with the clipboard empty go back into the Block Editor, open the Nested Block Row - and YOU will be able to add nested content elements....
![image](https://user-images.githubusercontent.com/260802/90915433-70503580-e3d7-11ea-88ae-9ad978d52142.png)

So strongly think it's related to the appearance of the use a content item from the clipboard dialog not being visible within a nested content item with a block editor when the clipboard is populated.

**Comment by marcemarc** [comment]
If we do this: https://github.com/umbraco/Umbraco-CMS/pull/8732 then this 'might' not be a problem.

**Comment by clausjensen** [comment]
I'll close this one as we will be doing #8732 😄
