### ISSUE TITLE
V8.7RC Active background of changed Nested Content style not rendering properly

### ISSUE THREAD

**Issue by ronaldbarendse** [umbraco/Umbraco-CMS#8717]
The styling of Nested Content (NC) editor in the back-office has changed from:

![NC 8.6](https://user-images.githubusercontent.com/1051287/91144481-6028a680-e6b4-11ea-89d5-115f165af386.png)

To the following in 8.7:

![NC 8.7](https://user-images.githubusercontent.com/1051287/91144537-76366700-e6b4-11ea-9e0a-29cb727ee70f.png)

This aligns more with the new Block List (BL) editor, but NC uses an active background and that doesn't render properly (there's a white line between the border and background):

![NC 8.7 active](https://user-images.githubusercontent.com/1051287/91144654-a0882480-e6b4-11ea-8b4c-0f0adc1f8008.png)

## Umbraco version

I am seeing this issue on Umbraco version: 8.7RC.

Reproduction
------------

The quick fix would be to remove the `margin-top: 1px;` and `border-radius: 3px 3px 0 0;` from `.umb-nested-content__heading`, so it's rendered as: 

![NC 8.7 active fixed](https://user-images.githubusercontent.com/1051287/91145375-a6cad080-e6b5-11ea-808a-7c9e8acdf3ab.png)

Maybe the styling of the NC and BL editors can be aligned even more, as BL allows expanding multiple items (and shows an arrow before the icon/name), the BL uses a more grey background, larger copy/delete buttons?

**Comment by nul800sebastiaan** [comment]
Fixed in https://github.com/umbraco/Umbraco-CMS/pull/8718

Cherry picked for 8.7 in b1cb7923d65c56753a368739e2ee6e6a0512e5bd
