### ISSUE TITLE
V8.7RC Remove BlockListTemplateExtensions and default view/template

### ISSUE THREAD

**Issue by ronaldbarendse** [umbraco/Umbraco-CMS#8727]
PR https://github.com/umbraco/Umbraco-CMS/pull/8273 added the new Block List editor including an extension class [`BlockListTemplateExtensions`](https://github.com/umbraco/Umbraco-CMS/blob/0140d906a5a66d3ba512332e845a64d36169f911/src/Umbraco.Web/BlockListTemplateExtensions.cs) and a default view/template [`/Views/Partials/BlockList/Default.cshtml`](https://github.com/umbraco/Umbraco-CMS/blob/0140d906a5a66d3ba512332e845a64d36169f911/src/Umbraco.Web.UI/Views/Partials/BlockList/Default.cshtml).

In my opinion, these should be removed because there are multiple things wrong with this approach and the implementation:
- The default view includes a wrapper `<div class="umb-block-list">` that doesn't make sense in any frontend framework (or custom styling for that matter);
- Customizations in this view might get overwritten when Umbraco is updated (e.g. when a bugfix needs to be applied to this file);
- Just like the Grid and Forms views, you might not use it and because of the previous reason shouldn't customize this view either, so it doesn't make sense to ship it (as content);
- The extension class and default view both check whether any layouts exist (which is redundant);
- The `GetBlockListHtml()` methods don't return an `IHtmlString`, but the concrete, ASP.NET specific `MvcHtmlString`;
- It renders all HTML into a string, instead of using the slightly more performant `RenderPartial()` that directly writes to the output stream (and because this editor might contain whole page layouts, this might result in a significant increase in memory usage/object allocations);
- It's just a little bit of boilerplate that even throws exceptions when you haven't created a partial view in a specific folder (by default `BlockList/Components/{ContentTypeAlias}`).

This also breaks the 'clean canvas' philosophy of Umbraco and there are multiple, better ways to help get people started with this editor:
- Remove the view and include the HTML generation/partial rendering into the extension method (e.g. like the MVC form control helpers `Html.DropDownList()`);
- Include the default view as example in the documentation;
- Only include the view in a starter kit.

The same arguments apply to the Grid and Forms views: do not pollute client projects with views that aren't used or shouldn't be modified. Lets keep it simple and clean as possible, just like how Nested Content currently is!

## Umbraco version

I am seeing this issue on Umbraco version: 8.7RC.

**Comment by ronaldbarendse** [comment]
Issue https://github.com/umbraco/Umbraco-CMS/issues/8721 is a great example why the built-in/shipped by default views are a bad idea. Everyone upgrading to Umbraco 8.7 must ensure the updated grid view is overwritten (after PR https://github.com/umbraco/Umbraco-CMS/pull/8735 is merged), otherwise single column Bootstrap 3 grids will not work correctly.

**Comment by nul800sebastiaan** [comment]
Just to reply to your comment:

> Everyone upgrading to Umbraco 8.7 must ensure the updated grid view is overwritten (after PR #8735 is merged), otherwise single column Bootstrap 3 grids will not work correctly.

I don't really see this as a problem, we've made fixes to these things before and there are ways to customize these views without touching the ones we ship with.

Anyway, regarding the rest of the issue you raised, I have sent it to the team, they're deciding what they want to do with it.

**Comment by ronaldbarendse** [comment]
@nul800sebastiaan I've created 2 PRs to both improve the rendering of Block List items and fix the above issues: #8840 and #8841.

IMHO at least #8840 should be merged before the general release of Umbraco 8.7, as it would otherwise case a breaking-change and/or introduce multiple ways to render the list (that also both needs documentation)! Including #8841 would make it easier to write the Block List item partial views, so not having to learn and document the verbose ways of casting content/settings would also save a lot of time (both for implementing developers and the Documentation team).

**Comment by ronaldbarendse** [comment]
This issue shouldn't be closed (yet), as PR https://github.com/umbraco/Umbraco-CMS/pull/8840 actually removes the `BlockListTemplateExtensions` and the default view/template, but that's currently not merged.

**Comment by fouademi** [comment]
Simple jQuery fix:

$(".umb-block-list > div").unwrap();
