### ISSUE TITLE
V8.7RC Block Editor Label : Unable to access Settings values

### ISSUE THREAD

**Issue by liquidkool** [umbraco/Umbraco-CMS#8737]
I want to populate the label field with content from the settings tab. I can get content from the content tab using {{aliasName}}, however this doesnt work with content from the settings tab. I've tried {{settings.aliasName}}. Not sure if its possible?

Asked around the forum and slack, no one has an answer so not sure if a bug or just dont know the correct way to access properties added to the settings section.

**Comment by nul800sebastiaan** [comment]
Thanks @liquidkool - this overlaps with issue #8689 - I'll close this one and we can track updated to the label customizations there! 👍
