### ISSUE TITLE
V8.7RC Block Editor with Limited Amount Set

### ISSUE THREAD

**Issue by liquidkool** [umbraco/Umbraco-CMS#8749]
Validation only appears after you attempt to save a page with block editor content. This means editors can waste time adding content blocks only to find out they have exceeded the limit set by the property.

The "Add Content" button should disappear when the limit has been reached.

**Comment by nul800sebastiaan** [comment]
Thanks @liquidkool - that sounds like something we want to explore indeed! 👍 We'll have a chat about it soon and will let you know what came out of that.

**Comment by nul800sebastiaan** [comment]
We'll merge this into issue #8894 which has a pull request created for it! Thanks again!
