### ISSUE TITLE
V8.7RC When only one block available, don't show the catalogue

### ISSUE THREAD

**Issue by skttl** [umbraco/Umbraco-CMS#8760]
When you try to add content to a block list, you get the catalogue dialog shown in order to select the block type.
![image](https://user-images.githubusercontent.com/3726467/91637893-e5d98880-ea0b-11ea-8212-20f3c51836aa.png)

When you only have one block type configured, and nothing in the clipboard, this step should be omitted, and the block should just be added IMO.

**Comment by nul800sebastiaan** [comment]
Thanks @skttl, that's certainly a feature we want to revisit after the RC, not sure how yet since the panel also contains the clipboard, so maybe only if there's one item and nothing on the clipboard.

**Comment by skttl** [comment]
> When you only have one block type configured, and nothing in the clipboard, this step should be omitted, and the block should just be added IMO.

😉

**Comment by nul800sebastiaan** [comment]
Oh I see what you did there, hiding text under a big image so I wouldn't see it! 😉

**Comment by skttl** [comment]
And just to add to that, if something is in the clipboard, the catalogue should show the clipboard and nothing else :)

**Comment by nielslyngsoe** [comment]
Hi @skttl , thanks for bringing your eyes to how to solve this one. As Seb says this will be for the next release as it's not critical for this one.
We always wanted to do something different when only one option is available, but we have not been completely sure on how we want to solve it just jet.
But reading your comments made my start thinking about a solution that I would like to share as a conversation starter:

So as you propose, we should not show the catalog if only one item is available. But to avoid having different flows depending on the clipboard state I propose borrowing the UI concept from the settings part of blocks.
I propose a small clipboard button appears when the clipboard contains items of interest, this one will appear no matter the number of block types configured and will work as a shortcut to the clipboard-section of the block catalog. If there is only one Block Type available this will be the only option for the user to get to the clipboard-dialog, in this way the user journey for creating content of the block list editor will stay the same no matter the state of the clipboard.
As users using the copy-feature are of a more experienced kind, and already have found the copy-button it should be no problem for them to find the clipboard button in the scenario of having block-list with only one type.

![image](https://user-images.githubusercontent.com/6791648/92215029-80b2e680-ee94-11ea-83c0-fbe83659e70b.png)

**Comment by skttl** [comment]
I agree, it's better to keep "add new content" and "paste existing" content seperate.

**Comment by skttl** [comment]
I did a package once, enabling copying/pasting of grid editors, and I had the same way - a button for new content, and a button for pasting

![image](https://user-images.githubusercontent.com/3726467/92219281-a4792b00-ee9a-11ea-8b4f-18fb4ba8c595.png)

**Comment by kjac** [comment]
I didn't see this issue 🙈 but did a PR in #8829 that sort of do what @skttl outlined to start with. It doesn't split the "add new" and "paste existing" actions, but still I think it's a step up from the current handling of single item type block lists.

**Comment by ronaldbarendse** [comment]
Having a quick way to both add new (single type) blocks and paste them would indeed be great, especially with inline editing mode (so you don't need to switch to the dialog and back to the content).

@nielslyngsoe I agree with @skttl about having seperate buttons, instead of embedding the paste icon into the 'Add content' button. I've already created a mock-up for something similar in Nested Content a while back: https://github.com/umbraco/Umbraco-CMS/pull/6593#issuecomment-545164470.

**Comment by ronaldbarendse** [comment]
Another thing to keep in mind: if the block is directly added without showing the catalogue, you don't see the name of the block or the thumbnail (if one is added).

**Comment by nathanwoulfe** [comment]
This has been resolved in #9277 - can paste directly from the Add button, if content exists on the clipboard. Otherwise, adding a new fieldset bypasses the overlay when a single block type exists.

![image](https://user-images.githubusercontent.com/3248070/129497976-1bdd6f7b-dec9-4d41-b4c3-e64fcf86f287.png)
