### ISSUE TITLE
V8.7RC Thumbnail doesn't display

### ISSUE THREAD

**Issue by skartknet** [umbraco/Umbraco-CMS#8762]
I have created a new Block list with a few components. On one of them I have added an screenshot as a thumbnail be it's not displayed in the configuration preview. It is displayed though when I use the block list from the actual page.

## Umbraco version

I am seeing this issue on Umbraco version: 8.7 RC

Reproduction
------------

If you're filing a bug, please describe how to reproduce it. Include as much
relevant information as possible, such as:

### Bug summary

Create a block list with a component and add a thumbnail:

### Steps to reproduce

Add an image from the project folder.

![image](https://user-images.githubusercontent.com/1685262/91652579-17ba2000-eadc-11ea-8a72-5cbe3fdd00d1.png)

### Expected result

Preview should display

### Actual result

Image or icon are not displayed

![image](https://user-images.githubusercontent.com/1685262/91652603-37e9df00-eadc-11ea-88ec-e153c86660ea.png)

I can see on the source code that the generated URL is incorrect: 

![image](https://user-images.githubusercontent.com/1685262/91652633-77b0c680-eadc-11ea-932f-a3d8717574c7.png)

It looks like it shouldn't include the ~

**Comment by nul800sebastiaan** [comment]
Thanks @skartknet this has been fixed since the RC already, good catch though! 👍
