### ISSUE TITLE
Examine MemberIndex gives different DocumentCount numbers when reindexing repeatedly

### ISSUE THREAD

**Issue by inetzo** [umbraco/Umbraco-CMS#8764]
When i click the  "Rebuild index" button of the "MembersIndex" repeatedly, every time i get a different number of DocumentCount.
We found this because sometimes some members can not be found in the MemberIndex. The missing members get than indexed again but some other ones are gone after indexing. I would expect that there need to be as many members in the index as in the cmsMember table.

![afbeelding](https://user-images.githubusercontent.com/18665536/91667609-48af4a80-eb06-11ea-8a7d-0404612c09c2.png)

![afbeelding](https://user-images.githubusercontent.com/18665536/91667634-5bc21a80-eb06-11ea-9703-5e4114030955.png)

![afbeelding](https://user-images.githubusercontent.com/18665536/91667643-6d0b2700-eb06-11ea-9366-ff28c29a60db.png)

## Umbraco version

I am seeing this issue on Umbraco version: 8.6.4

Reproduction
------------
- Login to the Umbraco backoffice
- Goto the "Settings" section and click on "Examine Management".
- Select the "MemberIndex".
- Click on the "Rebuild Index" button a few times. Every time there is a different number of documents indexed.

**Comment by nul800sebastiaan** [comment]
Hmm, might be related to https://github.com/umbraco/Umbraco-CMS/issues/8766

Can you see anything in the logs that stands out at the time you're doing a rebuild?
Do you have any custom indexes or did you customize the built-in indexes at all?

**Comment by inetzo** [comment]
I have discovered that this is probably a display problem. After pressing the "Rebuild index" button a random DocumentCount number is displayed but when the screen is refreshed, the correct number is displayed which corresponds to the number of records in cmsMember.

**Comment by nul800sebastiaan** [comment]
@inetzo if it's a display problem then it doesn't sound like members sometimes disappear, right? If you see the correct number after a refresh?

I would recommend you have a read through https://github.com/umbraco/Umbraco-CMS/issues/8766 and https://github.com/umbraco/Umbraco-CMS/issues/6123 and see if any of this applies to you. I haven't heard other problems with this count and on my local installs it seems to work just fine (granted, I only have 9 members in there). If you can reproduce the problem in a clean Umbraco install we can investigate further, for the moment I have to assume it's a problem somewhere in your environment. 

But as said, happy to look again if you can reproduce it in a clean install! 👍
