### ISSUE TITLE
8.7RC Can't add NC item with copied NC items inside block editor

### ISSUE THREAD

**Issue by bjarnef** [umbraco/Umbraco-CMS#8773]
It seems when having a property using Nested Content on an Element Type using in block editor and then copying these items, these are shown in the block list clipboard. Is this expected? Shouldn't it only show copied block items?

![2020-08-31_17-19-49](https://user-images.githubusercontent.com/2919859/91737012-cf1f6700-ebae-11ea-8818-43d53dc37ac7.gif)

After this in clipboard I can't add more items to the Nested Content property. It does however not seems to be an issue with Nested Content directly on a document type.

---
_This item has been added to our backlog [AB#8164](https://dev.azure.com/umbraco/243e7927-03b2-44e2-908f-d4ac7ea5daaa/_workitems/edit/8164)_

**Comment by bjarnef** [comment]
@nielslyngsoe @nul800sebastiaan this seems to have some issues.
Should copied Nested Content items show up in the block list clipboard?

Furthermore with copied items the "Add Content" button shows an overlay (target), but this isn't shown correct inside the block list overlay (but should work correct if using inline mode).

![image](https://user-images.githubusercontent.com/2919859/91737324-35a48500-ebaf-11ea-94ca-61d098500cb0.png)

I shortly see the overlay here, but it is moved out of screen real estate I believe.

I previous noticed some calculation issue when using overlay with "target" position inside an overlay, because it calculated the position based on size of `#contentwrapper` (the editing area) instead of the isolated area in the overlay.

I have fixed these issues in the following two PR's for v8.8:

https://github.com/umbraco/Umbraco-CMS/pull/8416 (umb-tooltip)
https://github.com/umbraco/Umbraco-CMS/pull/8431 (umb-overlay)

**Comment by nul800sebastiaan** [comment]
Thanks @bjarnef - for the final release we'll make NC unavailable for now as it doesn't play well with the block editor (you noticed) but more importantly we think block editor can do everything NC can do and then some. 

I'm not sure though, if you have a page with NC and copy stuff, if that ends up on the clipboard for the block editor (even when NC is not available in the block editor). Is that what you're seeing?

**Comment by nul800sebastiaan** [comment]
For more info on removing NC as an option from the block editor: https://github.com/umbraco/Umbraco-CMS/pull/8732#issuecomment-684521643

**Comment by bjarnef** [comment]
@nul800sebastiaan okay, I haven't tested if there are other issues with NC inside block editor, besides the overlay with "target" position doesn't play well inside an opened overlay as in https://github.com/umbraco/Umbraco-CMS/pull/8416 (umb-tooltip) and https://github.com/umbraco/Umbraco-CMS/pull/8431 (umb-overlay).

Maybe NC shouldn't use "target" position when clicking "Add content" and having something in clipboard. Maybe it should instead open an overlay like block editor with sections "Content" and "Clipboard". It would make it more consistent and probably help making NC work inside block editor.

Yes, I think this copy of NC items ends up in block editor clipboard as well.

**Comment by nul800sebastiaan** [comment]
I've tested this and it's currently a known issue for v8.7, to summarize:

- I can copy a block element and paste it into a Nested Content editor with no problem (I only used a very simple element type though)
- I can copy a nested content item (or multiple items) and when pasting them in the block editor they are all empty, the content didn't get pasted

So there's definitely some problems there still that we want to look at for an 8.7.1 patch release.

**Comment by nielslyngsoe** [comment]
Bl should be able to accept NC copy entries. I will test why this doesn't work.

**Comment by nielslyngsoe** [comment]
Oh, NC prepends the alias of properties, this is why it does not transfer the data correctly...

**Comment by warrenbuckley** [comment]
Closed as fixed by #8981
