### ISSUE TITLE
Mandatory messages when splitview editing in a multilingual setup

### ISSUE THREAD

**Issue by JeffreyPerplex** [umbraco/Umbraco-CMS#8788]
I have Umbraco 8.7RC and the default starter kit installed. The only things I added is that

- I have added the language Dutch to the set of languages. The fallback language of Dutch is set to 'English'
- set the "Allow vary by culture" flag on the homepage to "True"
- set some properties on this document type to "Allow vary by culture" (The property "Hero background" (media picker - mandatory), "Font" (radiobuttonlist - mandatory), "Color theme" (radiobuttonlist - mandatory)

What I then do:

-  I go to the homepage and edit the content in splitview (left English, right Dutch)
- I do not select another Hero Image.... 
- I want to "Save and publish" => A required field error message is trigger

I would have expected:

- That this error message would not have been triggered... I have setup that English is my fallback language so I would expect that the required field validation would not trigger if there's something submitted in the English version....

See also this .gif

![fallback](https://user-images.githubusercontent.com/12457148/91856819-592b0680-ec67-11ea-8f54-40de12595deb.gif)

I know that this is a quite exotic case, but it is a reallife case... Some bonus info: if you have setup another language (French) where you don't specify a fallback language; in that case the required field exception should get triggered....

---
_This item has been added to our backlog [AB#8210](https://dev.azure.com/umbraco/243e7927-03b2-44e2-908f-d4ac7ea5daaa/_workitems/edit/8210)_

**Comment by nul800sebastiaan** [comment]
That's not what a fallback is made for though, if you set something to mandatory and it can vary by culture then you are basically editing 2 different properties with their own rules. The fallback language is only meant for querying, not for editing.

This is how it currently works and I'll need to ask the team if we might want to change that to make fallback language a thing during the editing of properties as well.

**Comment by mayhammf** [comment]
@JeffreyPerplex  I totally agree that it makes sense to be able to configure a field to be mandatory for the default language but optional for the variants, especially in the scenario you mentioned. 

@nul800sebastiaan  i think the description text of the "Mandatory language" toggle contributes a little to the confusion here:  
<img width="423" alt="image" src="https://user-images.githubusercontent.com/5937658/157857703-de49e4d3-a631-4b04-ac93-e87611d019fa.png">
The wording gives the impression that the configuration is indeed on property level. 

[This blog post](https://umbraco.com/blog/umbraco-8-language-variants/?_ga=2.110107397.1476393546.1646921004-36899822.1644992485) explains the "Mandatory language" feature in a clearer way 

----
Perhaps the option can be added on a property level when both "Field is mandatory" and "Allow vary by culture" are set to true
<img width="363" alt="image" src="https://user-images.githubusercontent.com/5937658/157859627-e8f5764f-8bf9-4531-873d-71402284f8d9.png">

**Comment by nul800sebastiaan** [comment]
Yes, and the next request for this to come in will be: oh, but the language should be mandatory for English and Danish but not for Dutch and German. 🙈 
Event handlers (v8)/Notification handlers (v9) can help for now. 

We'll put this on our ideas list for when we're doing a larger overhaul for variants again in the future, but please note that we don't have current plans on the roadmap for this. I'll close the issue since we are not actively going to work on it, nor can we encourage contributions at this point.  The `idea` label will allow us to find good ideas around variants later again though, so not rejecting the issue, just indicating we are not going to be able to work on it in the near future.
