### ISSUE TITLE
Sortorder not correctly set in listview

### ISSUE THREAD

**Issue by FransdeJong** [umbraco/Umbraco-CMS#8796]
Tested this issue in Umbraco 8.6.4

Steps to reproduce:

Create a custom listview and order by sort descending.
If you create a new item the new item will be added to the bottom of the list with sort 0.

![Sort issue](https://user-images.githubusercontent.com/29602162/91943105-54646200-ecfc-11ea-9ee8-ed842e250b0b.png)

What I expect to happen is that the item is added to the top with the highest number.

**Comment by nul800sebastiaan** [comment]
Thanks @FransdeJong I just tested this in 8.7 and I can not reproduce it, sorting by sortorder descending seems to work there, so I'm assuming it was fixed in the mean time! 👍 I'll close this one. 🙂
