### ISSUE TITLE
Using `clipboardService.copy` only for other things than Element Types

### ISSUE THREAD

**Issue by leekelleher** [umbraco/Umbraco-CMS#8801]
Is the `clipboardService.copy` function designed to only be used with Element Type schema data?

Can it be used for any JSON data structure?

**Back story**

For my [Contentment package](https://github.com/leekelleher/umbraco-contentment/), I'd developed my own block editor against earlier versions, (8.4, 8.5, 8.6). One of my features was to [copy block items using the `clipboardService.copy`](https://github.com/leekelleher/umbraco-contentment/blob/dev/v1.1/src/Umbraco.Community.Contentment/DataEditors/ContentBlocks/content-blocks.js#L202) - which worked great.  Prior to my first beta release, I'd tested against v8.6.1 and the copy feature was good.

I've noticed (whilst reviewing the v8.7-RC) that since v8.6.2 the `clipboardService.copy` now assumes that the JSON data has a `variants/tabs/properties` structure, (e.g. that of a Document/Element Type schema). _(As far as I can tell, added in PR #7133)_  This works well for Nested Content (and new Block List), but if the JSON data being copied doesn't fit the same structure, then an error is thrown.

> Here's added line of code in the `prepareEntryForStorage ` function, that explicitly assumes for `variants/tabs/properties` structure: <https://github.com/umbraco/Umbraco-CMS/blob/release-8.6.2/src/Umbraco.Web.UI.Client/src/common/services/clipboard.service.js#L76>

The problem I have on my Contentment package is that my JSON data structure doesn't follow the same structure as Nested Content/Block List. I've removed the `variants/tabs/properties` structure, storing a reduced set of property data.

If were are able to copy any JSON structure with the `clipboardService`, I had plans for using it on other property-editors in Contentment.  But if it's been designed to only work with Document/Element Type schema, then I'll park my ideas. 😕 

## Umbraco version

I am seeing this issue on Umbraco version: 8.6.2, 8.6.3, 8.6.4, 8.7.0-RC

Reproduction
--------------

_I've snipped out the reproduction steps, as it's more a question of intent._

---
_This item has been added to our backlog [AB#8090](https://dev.azure.com/umbraco/243e7927-03b2-44e2-908f-d4ac7ea5daaa/_workitems/edit/8090)_

**Comment by nielslyngsoe** [comment]
@leekelleher It was intended though to be flexible and used for everything. We are coming up with a fix, that will be slightly breaking as I intend to stop using "elementTypeArray" as a clipboard entry type. And ongoing use "elementType" for both single data and array data. Meaning that existing code now should handle if entry.data is an array. Using single entries should still be working but registering resolvers will change as well. PR is coming soon.

**Comment by nul800sebastiaan** [comment]
This was extended in PR https://github.com/umbraco/Umbraco-CMS/pull/8809 and I believe you discussed this with @nielslyngsoe - would be good to get this in the documentation as the supported way to use the clipboard service in plugins!
