### ISSUE TITLE
V8.7RC: Small bug on creating relation types and macros from the tree

### ISSUE THREAD

**Issue by nul800sebastiaan** [umbraco/Umbraco-CMS#8805]
Creating a macro and creating a relation type is broken on v8.7. You can create them from the tree but there seem to be some methods missing, so you don't get taken to the edit screen after creating them.

![image (19)](https://user-images.githubusercontent.com/304656/92084178-4b8c9280-edc7-11ea-8736-e8db4629c97f.png)

---
_This item has been added to our backlog [AB#8085](https://dev.azure.com/umbraco/243e7927-03b2-44e2-908f-d4ac7ea5daaa/_workitems/edit/8085)_

**Comment by kjac** [comment]
PR in #8817 👍

**Comment by nul800sebastiaan** [comment]
Fixed in https://github.com/umbraco/Umbraco-CMS/pull/8817

Cherry picked for 8.7.0 in e7ad346d930ff1d850b9edcbb4f20a7cfb65a8ce
