### ISSUE TITLE
404 not found when editing focal point of image in new document

### ISSUE THREAD

**Issue by maikevers** [umbraco/Umbraco-CMS#8810]
Editing focal point of an image within a new unsaved document results in 404 not found for the request: `/backoffice/UmbracoApi/Content/GetById?id=...`

## Umbraco version

- Bug happens in fresh install of 8.5.5
- Bug happens in update to 8.6.4 from fresh install of 8.5.5
- Bug does not happen in fresh install of 8.6.4

Reproduction
------------

### Specifics

- Bug happens when creating a new document (eg a new Product) and editing focal point of an image within the document
- Bug does not happen when editing existing documents
- Url where bug occurs: /umbraco#/content/content/edit/1105?doctype=product&create=true
- Browser: Chrome Version 85.0.4183.83 (64-bits)
- Error message:
`Request error: The URL returned a 404 (not found):
/umbraco/backoffice/UmbracoApi/Content/GetById`
- Console: 
`GET http://localhost:54060/umbraco/backoffice/UmbracoApi/Content/GetById?id=1132 404 (Not Found)`

### Steps to reproduce

1. Either fresh install umbraco 8.5.5 or fresh install 8.5.5 and update to 8.6.4
2. In the backoffice, go to Content tab > Home > Products
3. Click "Create Product"
4. Add any image to the "Photos" property
5. Click the edit icon of the photo
6. Set the focal point by clicking the image
7. Save and close the image
![editfocalpoint](https://user-images.githubusercontent.com/26776828/92121301-67f5f280-edfa-11ea-80fe-0f4c7dc5b1af.png)

### Actual result

The following 404 error occurs:
![aftereditingfocalpointandsavingimage](https://user-images.githubusercontent.com/26776828/92121334-72b08780-edfa-11ea-94d0-bc23407fdadc.PNG)

So the bug seems to be fixed for fresh installs of 8.6.4, however, what should I do about my existing install when updating does not fix the problem?

**Comment by nul800sebastiaan** [comment]
Hey there @maikevers, sounds like an upgrade problem, you're "missing" something. 

I blogged about this a long time ago and the steps here still apply to upgrades these days: https://cultiv.nl/blog/how-to-diagnose-umbraco-upgrade-problems/

Mostly, I think you probably need to bump the ClientDependency.config version number and check that all the new (js/html) files are in your upgraded site.

**Comment by maikevers** [comment]
Thanks Sebastiaan! That solved the problem.
