### ISSUE TITLE
Member history, like content

### ISSUE THREAD

**Issue by ruant** [umbraco/Umbraco-CMS#8813]
Would be really nice to be able to see a history of the member data, like you do on content.

**Comment by nul800sebastiaan** [comment]
Thanks for the feature request, it's very short though, so I have a lot of questions!

What would you like to see in this history? What would the purpose be, who would it be useful for and why?

**Comment by ruant** [comment]
Good questions Sebastiaan :)
More data is always nice to have? 😆 

What would work would be an exact copy of how content, all the different properties etc.
The "problem" arose for a project for a organization that wanted to keep track of custom properties that was added to the MemberType. Example, change of address, change of Membership type etc.
So they could go back and see, that for example, this member had this address at this point, that's why the organization paper newsletter was sent to the wrong place etc..

As I understand the Member properties use the same tables as content, so it would basically just be to copy the "Rollback" function from the Content section over to the Member section? ("simple as that".... 🤣 )

**Comment by nul800sebastiaan** [comment]
Thanks @ruant. I think this is a GDPR minefield, and I don't see us adding this as a feature to the CMS.

If you need this functionality then you can use the [MemberService events](https://our.umbraco.com/Documentation/Reference/Events/MemberService-Events/) and store historic information somewhere you choose. 🙂

I'll close this issue and would encourage you to challenge the legality of what you've been asked to do.. 🙈  (I am not a lawyer! 😅 ).
