### ISSUE TITLE
NetCore: Content picker throws 500 error after selecting content

### ISSUE THREAD

**Issue by markwemekamp** [umbraco/Umbraco-CMS#8814]
### Bug summary

After selecting a content node in a content picker an error thrown. It appears to be that `/umbraco/backoffice/umbracoapi/entity/GetUrl` is the problem

### Specifics

**Example url**
https://localhost:44312/umbraco/backoffice/umbracoapi/entity/GetUrl?id=1059

**Error message**
```
An unhandled exception occurred while processing the request.
AmbiguousMatchException: The request matched multiple endpoints. Matches:

Umbraco.Web.BackOffice.Controllers.EntityController.GetUrl (Umbraco.Web.BackOffice)
Umbraco.Web.BackOffice.Controllers.EntityController.GetUrl (Umbraco.Web.BackOffice)
```

**Stacktrace**
```
AmbiguousMatchException: The request matched multiple endpoints. Matches: Umbraco.Web.BackOffice.Controllers.EntityController.GetUrl (Umbraco.Web.BackOffice) Umbraco.Web.BackOffice.Controllers.EntityController.GetUrl (Umbraco.Web.BackOffice)
Microsoft.AspNetCore.Routing.Matching.DefaultEndpointSelector.ReportAmbiguity(CandidateState[] candidateState)
Microsoft.AspNetCore.Routing.Matching.DefaultEndpointSelector.ProcessFinalCandidates(HttpContext httpContext, CandidateState[] candidateState)
Microsoft.AspNetCore.Routing.Matching.DfaMatcher.MatchAsync(HttpContext httpContext)
Microsoft.AspNetCore.Routing.EndpointRoutingMiddleware.Invoke(HttpContext httpContext)
Microsoft.AspNetCore.Diagnostics.StatusCodePagesMiddleware.Invoke(HttpContext context)
Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
```

### Steps to reproduce

- Create a document type with a content picker property
- Create a node with the document type
- Select content in the content picker

Same error occurs when selecting a content node in the multi url picker

**Comment by bergmania** [comment]
Hi @markwemekamp..

Thanks for reporting. I fixed the issue here: https://github.com/umbraco/Umbraco-CMS/commit/d69c93e4eea871ac5029462423c86525e46e7be7

This is one of the things that is changed between ASP.NET and ASP.NET Core. We have created a  `DetermineAmbiguousActionByPassingParametersAttribute` to use on actions with the same signature/name.

If any other issues like this occur, feel free to try to use this attribute and submit a PR :)
