### ISSUE TITLE
Missing indexes

### ISSUE THREAD

**Issue by kimschurmann** [umbraco/Umbraco-CMS#8823]
Azure recommends adding two indices to the umbraco database.

Why not add them? :) 

CREATE NONCLUSTERED INDEX [nci_wi_umbracoContentVersion_AA818B5DF81721B17BDBC026F1477C74] ON [dbo].[umbracoContentVersion] ([nodeId], [current]) INCLUDE ([text], [userId], [versionDate]) WITH (ONLINE = ON)

CREATE NONCLUSTERED INDEX [nci_wi_cmsLanguageText_2F71916A004D7469ACC6AA6CEF759EED] ON [dbo].[cmsLanguageText] ([UniqueId]) INCLUDE ([languageId], [value]) WITH (ONLINE = ON)

These could be the tip of the iceberg - are there more free optimization of indices - probably should run a profiling?

**Comment by Shazwazza** [comment]
There's a lot of index research that needs to happen, there's some tasks for this: 

* https://github.com/umbraco/Umbraco-CMS/issues/6601
* https://github.com/umbraco/Umbraco-CMS/issues/7968

and there's some new indexes being added as part of a new perf enhancement in this branch: https://github.com/umbraco/Umbraco-CMS/pull/8376

The more indexes there are the slower it is to insert/update the data so we need to be aware of that too.  `INCLUDE` columns in MSSQL are not actually supported either but will be as part of #8376 and with that addition it becomes even more important to revisit all indexes to see what perf improvements we will get specifically on MSSQL.

**Comment by nul800sebastiaan** [comment]
Thanks Shannon! I'll close this as a "duplicate" of #6601, have added a note there to look into this recommendation.
