### ISSUE TITLE
V8.7RC Hide copy button on unsupported block

### ISSUE THREAD

**Issue by bjarnef** [umbraco/Umbraco-CMS#8830]
At the moment in block editor it is possible to copy a unsupported block and insert this from clipboard.
Does it make sense to copy unsupported blocks or should the copy button be hidden/removed in this case?

![2020-09-04_15-58-45](https://user-images.githubusercontent.com/2919859/92247689-d94fa700-eec7-11ea-9f7b-e7e72d2aa6e9.gif)

**Comment by bjarnef** [comment]
@nielslyngsoe does this make sense in block list editor?

**Comment by nielslyngsoe** [comment]
@bjarnef good spotting, yes it does not make sense to show the copy button. The copy-action could have made a little sense if it was possible to paste it into another context where it was supported BUT the copy-feature would not work right if it's not supported(doesn't have scaffolding for its data) therefor this will never make sense as we currently copy the ElementTypeModel(for shared compatibility) for the clipboard.

**Comment by bjarnef** [comment]
@nielslyngsoe yes, I think it would be great to hide the copy-button for unsupported block and with this PR it is easy to copy the JSON for the unsupported block: https://github.com/umbraco/Umbraco-CMS/pull/8828

**Comment by nielslyngsoe** [comment]
@bjarnef actually I think this is a bug, and it might be fixed in the latest version? At least it does not show the copy button if the configuration has been removed. I haven't tested if the ElementType is missing, so need to test that scenario.

**Comment by bjarnef** [comment]
@nielslyngsoe yes, it might be fixed in latest changes.
When working on this PR https://github.com/umbraco/Umbraco-CMS/pull/8828 I actually just comment out this line, so it might work correct when value of `unsupported` property is `true`.
https://github.com/umbraco/Umbraco-CMS/blob/v8/contrib/src/Umbraco.Web.UI.Client/src/views/propertyeditors/blocklist/umbBlockListPropertyEditor.component.js#L200

**Comment by nul800sebastiaan** [comment]
Yeah the button is not available in the current version, I'll close this one.
