### ISSUE TITLE
Dotnet Core Alpha User SMTP error

### ISSUE THREAD

**Issue by crgrieve** [umbraco/Umbraco-CMS#8834]
When creating a user, it goes to an error (although it has created user in background). This is not as expected based on behaviour in v8.

## Umbraco version

I am seeing this issue on Umbraco version: Dotnet core alpha (on Windows)

### Bug summary

Error when creating new User, looks related to not being able to send email.

### Steps to reproduce

Create a new user in Users section.

### Expected result

On v8, even with no SMTP details in config, you get to next step:
![image](https://user-images.githubusercontent.com/9353655/92304715-43278980-ef78-11ea-86c0-12a18dd4315e.png)

### Actual result

Error given: 
![image](https://user-images.githubusercontent.com/9353655/92304718-491d6a80-ef78-11ea-921a-2f9ff5c601bf.png)

**Comment by elit0451** [comment]
Hi @crgrieve 🙂 
Thank you for giving the alpha a try! 

Regarding this issue, I am not able to reproduce the error you got. In the **Steps to reproduce** you mention user creation, but when looking at the screenshotted error I can see that it was regarding inviting a user (*Failed to invite user*). I have tried both creating and inviting a new user, everything goes successfully. Could you tell us a bit more about your test?

When going to Users section do you see the **Create user** or **Invite user button**? Also, could you please check for me if you have an *"Smtp"* JSON object in  *appsettings.Development.json* file (meaning if you have configured the SMTP Settings)?

**Comment by bergmania** [comment]
To me, it looks from the error as SMTP is configured (I think this is a standard config in alpha001) but there is no SMTP available on the local machine.

**Comment by bergmania** [comment]
The SMTP info is disabled by default in the future.
