### ISSUE TITLE
Node Actions menu should be disabled when user has selected items in the list.

### ISSUE THREAD

**Issue by nielslyngsoe** [umbraco/Umbraco-CMS#8838]
If a user has selected items in the list-view, the "Action" button, top-right should be disabled.
That at least my preferred solution, if not posible, we can disabled the "Actions" all the time in the ListView tab.

![image](https://user-images.githubusercontent.com/6791648/92379997-ab0cda00-f108-11ea-8400-efb4b41623d1.png)

**Comment by BatJan** [comment]
Fixed in https://github.com/umbraco/Umbraco-CMS/pull/9021
