### ISSUE TITLE
Upload error in media with filesize over 2000mb

### ISSUE THREAD

**Issue by seanhakbb** [umbraco/Umbraco-CMS#8846]
We're having issues uploading files larger than 2gb on to our latest umbraco install in the media section.

## Umbraco version

I am seeing this issue on Umbraco version:  8.6.1

Reproduction
------------

If you're filing a bug, please describe how to reproduce it. Include as much
relevant information as possible, such as:

### Bug summary

When uploading a file bigger than 2000mb (2gb) the upload progressbar goes to 100% and fails/never gets added.

### Specifics

The angular progressbar goes really quick, faster than a normal file upload around 1.8gb, and the response is HTTP Error 400.0 - Bad request. ASP.NET detected invalid characters in the URL.
A file of 2000mb went through without any issues.

Our web.config is set to 
<requestLimits maxAllowedContentLength="4294967295" />
<httpRuntime maxRequestLength="2147483647" executionTimeout="99999" />

The request that fails is: /umbraco/backoffice/UmbracoApi/Media/PostAddFile
currentFolder: 5065
contentTypeAlias: umbracoAutoSelect
propertyAlias: umbracoFile
file: (binary)

### Steps to reproduce

Upload file larger than 2gb in media section.

### Expected result

File should be added or warn against file size limit.

**Comment by SteveVaneeckhout** [comment]
https://web.archive.org/web/20140407003943/http://blogs.msdn.com/b/friis/archive/2013/06/19/uploading-large-file-to-iis-7-5-or-8-using-file-input-element.aspx

This seems to be a limit in ASP.NET

**Comment by seanhakbb** [comment]
@SteveVaneeckhout Yes Indeed. Thanks for this article! I've never encountered this before, however we did realize the client made a mistake when zipping and managed to reduce the file size heavily to be considerably less than orginal 2.7gb (600mb instead)

I'm closing this bug ticket since it's not an umbraco bug.
