### ISSUE TITLE
Chunked uploads to media

### ISSUE THREAD

**Issue by seanhakbb** [umbraco/Umbraco-CMS#8855]
I found out .net 4 seems to have a file size upload limit for 2gb, this can be worked around using chunked uploads instead.
#8846 

How can you help?
-------------------------------

I'm not sure if you are using a open source component or custom built angular file uploader, it might already have support for chunk file upload, could this be explored and turned on if that's the case.
If current code needs to be replaced or rewritten to support chunk file upload, would it be worth it in time?
Being able to upload files larger than 2gb is one of the pros of using chunked uploads, Other benefits is faster speed/threading
and less likely to fail on bigger filesizes.

**Comment by nul800sebastiaan** [comment]
Thanks @seanhakbb while I do understand that some people might want to do this for various reasons, we don't really cater for Digital Asset Management scenarios and we would recommend, if you need to host/stream very large files, that you have a look at integrating DAM software with Umbraco. 
As we know from https://github.com/umbraco/Umbraco-CMS/issues/8380 - even if you might be able to do it with Umbraco, the experience on the frontend won't be optimal either. 

So for the same reason as #8380 I'll close this for now.
