### ISSUE TITLE
NetCore: Back-office - user's culture not set as configured

### ISSUE THREAD

**Issue by idseefeld** [umbraco/Umbraco-CMS#8856]
The configured (default: en-US) user's culture is not set in the back office api controllers.

- I found the issue on German (de-DE) Windows 10 system.
- I have just downloaded the netcore/netcore branch, build the solution an started the Umbraco.Web.UI.NetCore project within Visual Studio 2019. And I have tested the alpha release according to: https://umbraco.com/blog/net-core-alpha-release/
- The initial user was configured for English/US, but the back office was displayed in de-DE. This was probably caused by my system default language.
- I have also checked, that not the browser default language caused the issue.
- Setting the Windows language to English/US did change the back office to English.

@Shazwazza already mentioned `BackOfficeCultureFilter` as the place where this should be handled. But this does not seem to be used yet. And I could not figure out how this should be used:-(

Within one of the Api controllers e.g. `Umbraco.Web.BackOffice/Controllers/SectionController.cs` method `GetSections` you can see the culture is wrong (I added a debug line like: `var c = System.Threading.Thread.CurrentThread.CurrentCulture;`).

I have tried to add the following to `Umbraco.Web.BackOffice.Filters.UmbracoAuthorizeFilter`:
```
...
        public void OnAuthorization(AuthorizationFilterContext context)
        {
            if (!IsAuthorized())
            {
               ... 
            }
            else
            {
                if (context.HttpContext.User.Identity is Umbraco.Core.BackOffice.UmbracoBackOfficeIdentity cu)
                {
                    System.Threading.Thread.CurrentThread.CurrentCulture
                        = System.Threading.Thread.CurrentThread.CurrentUICulture
                        = new CultureInfo(cu.Culture);
                }
            }
        }
...
```
This works in a way, although you have to logout, reload the page and login again.

Hopefully this gives you enough details!

Dirk

**Comment by bergmania** [comment]
Hi @idseefeld..

Thanks for reporting.. I have a hard time reproducing - at least on windows. 

When I run the `netcore/netcore` branch and sets a breakpoint in `BackOfficeCultureFilter.OnActionExecuting` I see it is hit and sets the culture.

Can you confirm the BackOfficeCultureFilter.OnActionExecuting` is not hit when you test, but setting a breakpoint in the top of the method?

BR, Bjarke

**Comment by idseefeld** [comment]
Hi @bergmania,

I have just:

1. downloaded netcore/netcore branch (first time on a different computer: de-DE Windows 10 Pro)
2. build successfully
3. started IIS Express on Umbraco.Web.UI.NetCore
4. installed default (SqlCE) (debugging terminated)
5. again started IIS Express on Umbraco.Web.UI.NetCore

I still see the back-office in German. (see screenshot)

Then I set a breakpoint in `BackOfficeCultureFilter.OnActionExecuting` as you ask me. It got hit several times.
While the breakpoint was hit, I inspected the the `context.HttpContext.Request.Path` and there was not hit for path: `/umbraco/backoffice/umbracoapi/section/GetSections`, which is the request path for `GetSections `of `Umbraco.Web.BackOffice/Controllers/SectionController.cs`.

I added my mentioned check to `Umbraco.Web.BackOffice/Controllers/SectionController.cs` method `GetSections` and culture is still `de-DE` here.

Thus I can confirm `BackOfficeCultureFilter.OnActionExecuting` is not hit for `UmbracoAuthorizedJsonControllers` or at least `Umbraco.Web.BackOffice/Controllers/SectionController.cs`.

Anything else I could provide you?

KR, Dirk

**Comment by idseefeld** [comment]
![wrong-back-office-culture](https://user-images.githubusercontent.com/866917/92699053-66be4b80-f34d-11ea-8d12-30ab7c0aafbe.png)

**Comment by idseefeld** [comment]
Btw. my Windows 10 Pro is the latest build 2004

**Comment by bergmania** [comment]
FYI: We have created a task in the upcoming sprint (starting Monday) to look at this issue

**Comment by bergmania** [comment]
Could be related to this issue: https://github.com/umbraco/Umbraco-CMS/pull/8871
