### ISSUE TITLE
Block Editor - Columns?

### ISSUE THREAD

**Issue by crjc** [umbraco/Umbraco-CMS#8858]
The block editor is already really cool, but it would be great if we could specify block editors to display blocks to editors as **columns** rather rows. Perhaps a simple checkbox to switch between column/rows in the Datatype settings would do?

**Comment by soreng** [comment]
hi @carr-7 - the editor in 8.7 is called Block List Editor. This enforces the "list" part of the current impl.

There is/has been talks of a Block Grid Editor, where you would indeed be able to to rows and columns.

**Comment by nul800sebastiaan** [comment]
Thanks for the feature request, while Søren is right, we currently didn't mean for this to have columns, I'll have to ask around as to why exactly that is and what the plans around that are.
