### ISSUE TITLE
Prepopulate properties from the previously saved and published content node to the new one within the same parent

### ISSUE THREAD

**Issue by Baracuda011** [umbraco/Umbraco-CMS#8861]
Dear all,

I am currently populating a list of available materials for some products. A majority of these fields are repeating themselves within each new node.

It would be an excellent UX feature that when you Save and Publish have an option to automatically create another node in the same parent with prepopulated fields from the node you just Saved and Published. This will save a huge amount of time, and the content editor shouldn't go through the several steps of creating a copy of the specific node and put it in the proper location.

**Comment by soreng** [comment]
@Baracuda011 you could create a content template for this

https://our.umbraco.com/Documentation/Umbraco-Uno/Creating-Content/How-to-Set-up-Content-Template/

**Comment by Baracuda011** [comment]
Thanks @soreng, you are right.

This is also an option. But based on the state of my current project, I would have many different content templates, which I would like to avoid.
