### ISSUE TITLE
8.7 final: Error in block editor "Property uses editor 'Umbraco.NestedContent' which is not supported in Element Types."

### ISSUE THREAD

**Issue by arknu** [umbraco/Umbraco-CMS#8864]
In the 8.7 RC I created a site with blocks with Nested Content for things like slides in a slider. This worked fine.
However, in the final release, I now get an error that Nested Content is not supported in element types. Since when did this change? Seems rather a big change to make between RC and final. Nested Content has always worked fine, even inside other Nested Content editors, so the message seems to be bogus.

I suppose that an alternative is to use the blok editor instead.

## Umbraco version

8.7.0

### Steps to reproduce

Create a Block List Editor.
Add a block type with a Nested Content Property

### Expected result
Nested Content should work (it did in the RC)

### Actual result
Error as described:
![image](https://user-images.githubusercontent.com/4654741/92741086-96397c00-f37e-11ea-87ab-f84d62a9c87b.png)

**Comment by arknu** [comment]
This seems to be intentional based on this commit: https://github.com/umbraco/Umbraco-CMS/commit/055d1179a140afbeff159dbf9844509cef9c6bd6

However, I still find this change peculiar. Things like this should be mentioned in the blog post, so that people upgrading from the RC don't get nasty surprises like this.

**Comment by nul800sebastiaan** [comment]
Sorry about that, we realized that we couldn

**Comment by nul800sebastiaan** [comment]
Sorry about that, we realized that we didn't want to support this scenario after RC feedback. I'm afraid it comes with the territory of when you're testing an RC, we might make changes, even slightly radical ones. 🙈

I'll close this issue since it works as expected as noted in https://github.com/umbraco/Umbraco-CMS/pull/8732.
