### ISSUE TITLE
Block List Editor: Add an option to hide the label

### ISSUE THREAD

**Issue by arknu** [umbraco/Umbraco-CMS#8865]
Given the purpose of the block list editor, there should be an option to hide the label, like there is for Nested Content (which is now apparently deprecated). This would be especially useful when using previews since the label will take up rather a large amount of room...

**Comment by nul800sebastiaan** [comment]
Thanks @arknu!

We want to move away from the "hide label" paradigm in the future so we're not going to implement it for new editors. Instead, we want an additional new feature to put the label above the property. We're actively looking for contributions for that, or we might have to work on it ourselves soon. #6502

I'll close this feature request in favor of #6502 which is the direction we want to go in, thanks for clarifying!
