### ISSUE TITLE
CSS misalignment in confirm delete document type dialog

### ISSUE THREAD

**Issue by skttl** [umbraco/Umbraco-CMS#8868]
When deleting a content type you get this dialog. As you can see there is a slight misalignment in the css for the checkbox.

![image](https://user-images.githubusercontent.com/3726467/92911558-4bc10980-f429-11ea-9c7c-760d904bbb8d.png)

I am seeing this issue on Umbraco version: 8.7.0
Browser: MS Edge (chromium version)

---
_This item has been added to our backlog [AB#8234](https://dev.azure.com/umbraco/243e7927-03b2-44e2-908f-d4ac7ea5daaa/_workitems/edit/8234)_

**Comment by nul800sebastiaan** [comment]
Weird, we'll have to have a look!

**Comment by warrenbuckley** [comment]
Fixed by PR #/8985
