### ISSUE TITLE
Create New Block popup can get overwhelming

### ISSUE THREAD

**Issue by skttl** [umbraco/Umbraco-CMS#8869]
When adding new blocks to a block list, you get presented with this view:
![image](https://user-images.githubusercontent.com/3726467/92912271-e9b4d400-f429-11ea-8b9b-c45b7d7e9410.png)

It shows all the element types not already added to the block list. For a large site with lots of block types (you probably have the same problem with Uno) this can get quite overwhelming, and I would suggest that the layout should be changed for the better.

A small thing that would be very beneficial, would be to group the types by their parent folder. This way you can have a folder for all your content types, a folder for your setting types etc.

**Comment by paulwoodland** [comment]
I'd like to see this too, with a number of blocks available it quickly becomes hard to see what's what, especially for new users etc.

I added something to our installation to split them up for the moment, but it's very hacky, it would be good to see something properly supported. I've attached a picture of ours to show the kind of thing I'd be thinking of, with the category names being the folders they are contained in (or even better, some method of assigning categories when editing the blocks in the property type)

![umbblocklist#](https://user-images.githubusercontent.com/7717900/112675567-3a889900-8e5f-11eb-99fa-8d273d641498.png)

**Comment by nielslyngsoe** [comment]
This issue has been fixed, when creating a new block type in the prevalue editor, now we use a tree to navigate element types.
![image](https://user-images.githubusercontent.com/6791648/125064991-8a5b3b00-e0b1-11eb-87bf-ab0d28f311a9.png)


What @paulwoodland is suggesting is for the Block Catalog, aka. what content editors see when creating content. This is a great idea, had a similar idea when we developed this, but it didn't reach the first versioon and hasn't been followed up on. It should be fairly simple to add a divider-type to the list of configured blocks. And thereby make such layout. A nicer, maybe simpler, solution would be to have a layout property(property defining how the configured blocks should be presented), which allows for different groupings, this would be pure JSON and can be handled just by client-side code.

But for this request to be discoverable I think you need to create it as a separate request, so please do so @paulwoodland, thanks in advance :-)

**Comment by nielslyngsoe** [comment]
For clarification, this was done in 8.10 as part of this PR https://github.com/umbraco/Umbraco-CMS/pull/9322
