### ISSUE TITLE
Feature request: Replacement for Moment.js

### ISSUE THREAD

**Issue by bjarnef** [umbraco/Umbraco-CMS#8900]
I just had a look at the project status for momentjs: https://momentjs.com/docs/#/-project-status/

Currently Umbraco use moment.js in backoffice to format datetime in e.g. users section, but I wonder if there these days are better alternatives to use, e.g. some of the recommendations being metioned like [Luxon](https://moment.github.io/luxon/) or [Day.js](https://day.js.org/): 
https://momentjs.com/docs/#/-project-status/recommendations/

I also noticed this article [You Probably Don't Need Moment.js Anymore](https://dockyard.com/blog/2020/02/14/you-probably-don-t-need-moment-js-anymore)

It is probably not something being replaced anytime soon, but something to consider for vNext.

**Comment by mattbrailsford** [comment]
There are definitely more lightweight options. Even Lighthouse are suggesting alternatives for people now. 

https://twitter.com/addyosmani/status/1304676118822174721?s=21

Granted that’s for end websites, but still, if we can save on back office resources too then win win.

**Comment by bjarnef** [comment]
It seems `date-fns` currently is one of the popular alternatives to `moment.js`:
https://www.npmtrends.com/date-fns-vs-luxon-vs-moment-vs-dayjs

**Comment by bjarnef** [comment]
`Intl.DateTimeFormat()` can be used for much of what moment.js is used for in Umbraco core atm:
https://twitter.com/wesbos/status/1305846354791542785

https://caniuse.com/?search=Intl.DateTimeFormat

**Comment by filipbech** [comment]
Hey @bjarnef ... 
Thanks for bringing this up. Getting rid of moment will be a good thing - also just for the size of it... 
The plan for the next major release to be the netcore migration, and we currently plan on having no breaking changes to the backoffice. 
But this consideration will absolutely be part of vNextBackOffice (we should come up with a cool nickname soon)! 
Do you have any preferences in terms of what should be there instead of moment?

**Comment by bjarnef** [comment]
@filipbech sounds great and keeping it in mind when/if another JS framework will be added as a replacement of Angular (or if Angular still will be used in a newer version).

date-fns, luxon and dayjs all looks interessting and there are probably pros and cons for all of them.

However much it already supported in vanilla JS: https://twitter.com/wesbos/status/1185263826029174784
Maybe we don't even need a library in vNextBackOffice 🦄

**Comment by filipbech** [comment]
That sure would be nice! 
as for next backOffice I'm working on an RFC and starting a community group by end of this year (thats the target at least) - I hope you chime in there as well...
I'll close this issue, but please keep ideas/comments coming
