### ISSUE TITLE
Block Editor (Feature Request): Add ability to hide the label of the property

### ISSUE THREAD

**Issue by TRexStark** [umbraco/Umbraco-CMS#8903]
Similar to the NC, it will be great to have a toggle to hide the label.

**Comment by soreng** [comment]
https://github.com/umbraco/Umbraco-CMS/issues/8289

this was proposed earlier, but there are other plans :)

**Comment by nathanwoulfe** [comment]
Yup, there are plans brewing in #6502 - I'm closing this to keep all the discussion in the one place.
