### ISSUE TITLE
Copy and paste 2 levels of nested content causes duplicate content to show.

### ISSUE THREAD

**Issue by Myster** [umbraco/Umbraco-CMS#8910]
I have uncovered a bug in Umbraco. If anyone uses the copy and paste feature when there are nested children then the children don’t get a new GUID, they get a copy of the old GUID , which causes the content to come out duplicated in the front end.

In the screenshot, `#1` copy has a child `#2` so if `#1` is used then the children items don’t get a unique GUID and so they will be the same as where they were copied from., but `#2` copy can be used.

![image](https://user-images.githubusercontent.com/354777/93275363-d0889a80-f810-11ea-82fe-7670ef236f01.png)

The workaround is to delete the items at level 2 and re-create them  

you can copy and paste items at level 2 and it will not cause an issue, because there are no child items to mess up, so a quicker way to re-create the level 2 items is to copy and paste them, then delete the originals

I am seeing this issue on Umbraco version: 8.6.1

**Comment by rbottema** [comment]
Hi @Myster, I believe this is already fixed in 8.7 by #8842. Can you recheck on the newest version of Umbraco?

**Comment by nul800sebastiaan** [comment]
Thanks @rbottema - good suggestion, but that is specifically for the block editor, this bug is fixed in v8.6.2, I would recommend you upgrade to the latest v8.6 at least. 

This is the related issue: https://github.com/umbraco/Umbraco-CMS/issues/7133
