### ISSUE TITLE
Block List Editor doesn't allow removal of deleted elements

### ISSUE THREAD

**Issue by TRexStark** [umbraco/Umbraco-CMS#8911]
Setup:
- A block list property with 3 elements (Elem A, Elem B, Elem C)
- Delete any of the elements - as example, we delete Elem C
- Go to the DocType where you set the Block List property
- You will see an error (Expected)
- Go modify the Block List Property to remove the element that has been deleted.
- You would click on the trash icon when you hover the element

The element does not get deleted.

This has been tested in the infinite editor and directly on DataType.

**At the same time, you cannot add a new block either.**

**Comment by warrenbuckley** [comment]
Fixed in PR #8980  due for release in 8.7.1
