### ISSUE TITLE
8.8RC: NC icons are not centered correctly

### ISSUE THREAD

**Issue by nielslyngsoe** [umbraco/Umbraco-CMS#8922]
The icons in Nested Content are not centered vertically or horizontally correct.

![image](https://user-images.githubusercontent.com/6791648/93324381-1a27b400-f816-11ea-98d0-61a76cb3a756.png)

---
_This item has been added to our backlog [AB#8428](https://dev.azure.com/umbraco/243e7927-03b2-44e2-908f-d4ac7ea5daaa/_workitems/edit/8428)_

**Comment by ronaldbarendse** [comment]
Besides not being centered, the icons are also smaller compared to the Block List editor. It would be great if the icons (and other styling, like the action buttons/icons to the right) are made the same, so using NC and BL together will have a similar look.

**Comment by kjac** [comment]
@ronaldbarendse my words exactly! PR in #9024
