### ISSUE TITLE
Member Info content app layout is messed up

### ISSUE THREAD

**Issue by robertjf** [umbraco/Umbraco-CMS#8924]
A picture says a thousand words: 😉

![image](https://user-images.githubusercontent.com/818101/93389833-16e10680-f8b0-11ea-887c-d4828d720ac2.png)

I tested this with a brand new Member Type with no additional properties.

## Umbraco version

I am seeing this issue on Umbraco version: 8.7

Reproduction
------------

### Bug summary
See above

### Steps to reproduce

1. Create a new Member Type
2. Add a new member based on the member type
3. Inspect the Info Content App

### Expected result

Info Content App should be laid out correctly.

### Actual result

Info Content App layout is messed up.

---
_This item has been added to our backlog [AB#8315](https://dev.azure.com/umbraco/243e7927-03b2-44e2-908f-d4ac7ea5daaa/_workitems/edit/8315)_

**Comment by abjerner** [comment]
Great catch @robertjf 👍 

I did a quick comparison between 8.6 and 8.7, and the difference seems to be that 8.6 renders `<small class="control-description ng-binding" ng-bind-html="property.description | preserveNewLineInHtml"></small>` for the property - even when the property doesn't have a description. Via CSS, that element is being rendered as a block element.

In 8.7 there now appears to be an `ng-if` attribute on that element, so it doesn't get rendered when there isn't a description. And when the block element isn't there, the property renders as in your screenshot.

@nielslyngsoe do you remember the reasons for changing this? https://github.com/umbraco/Umbraco-CMS/commit/47147612774532eb694db25a0b22955f33b6a9af#diff-5d264656544cc4d5610b60a0c84dc428

I can see why it makes sense to hide the description element if there isn't a description. But it seems to be what is causing the properties to be rendered incorrectly. So should your commit be reverted? Or should the styling be updated so properties are still rendered correctly without the description element?

**Comment by nielslyngsoe** [comment]
@abjerner I remember that the description pushed the height in some situation leaving some unwanted spacing.
I think we should update the styling, we should try to become more flexible, so layouts aren't bound by having specific elements.

**Comment by warrenbuckley** [comment]
Fixed in PR #8994 due for release in 8.7.1
