### ISSUE TITLE
Block Editor Copy issue if Content contains Rich Text Editor

### ISSUE THREAD

**Issue by uSkinned** [umbraco/Umbraco-CMS#8929]
You can replicate the issue using UNO however I first discovered this with my own build of the block editor. Follow these steps to replicate.

1. Go to home node
2. Create empty 'Text and Images'. You dont need to add any content to test
3. SAVE THE PAGE. This step is important as the error does not happen if you copy a block without saving.
4. Copy your new 'Text and Images' to clipboard.
5. Click 'Add content' on the block editor.
6. Go to Clipboard. 
7. Select 'Text and Images'
8. This is where the error occurs and you will see that 'Text and Images' is not copied to the Block List.

Error happens in ~/umbraco/js/umbraco.services.js line 998. I am assuming RTE value is getting passed in here as an object which I dont think it should be. value.layout causes the error because value is null.

---
_This item has been added to our backlog [AB#8325](https://dev.azure.com/umbraco/243e7927-03b2-44e2-908f-d4ac7ea5daaa/_workitems/edit/8325)_

**Comment by nul800sebastiaan** [comment]
Thanks @uSkinned - that should work indeed.

Can repro:

![8929](https://user-images.githubusercontent.com/304656/93482628-31db6700-f900-11ea-9cb5-4c40ef61b7d8.gif)


Refers to this line of code: https://github.com/umbraco/Umbraco-CMS/blob/v8/contrib/src/Umbraco.Web.UI.Client/src/common/services/blockeditor.service.js#L71

**Comment by uSkinned** [comment]
Thanks for confirming, dont know where I got line 998 from, DOH!!!

**Comment by nul800sebastiaan** [comment]
No that line is about right, but you're seeing the compiled version of the JS file, just pointed to the original location before we build everything! 👍

**Comment by warrenbuckley** [comment]
Fixed by PR #8979
