### ISSUE TITLE
Starter Kit Installs Incomplete on 8.7 release

### ISSUE THREAD

**Issue by nobledm** [umbraco/Umbraco-CMS#8937]
When doing a fresh installation of the newest Umbraco release, and choosing to install the starter kit as part of it, the site loads in with the appropriate pages and content, document types and compositions, template page files/partials/macros/etc... but all of the template pages are blank, media files exist but don't have a preview or load, and the starter kit is not listed as part of the installed packages.

### Specifics

Version 8.7.0
Installation through NuGet or zip file

### Steps to reproduce

New Umbraco 8.7 installation, choose to install the starter kit.
I was going through the custom installation to connect to a local db

### Expected result

The starter kit would work out of the box as it did in 8.6.3 & earlier

### Actual result

Template code missing; not installed properly. Requires manual install of the starter kit package (which works as expected except the images)

**Comment by nul800sebastiaan** [comment]
Hey there @nobledm! You're right, I would expect the same thing. Luckily in all our tests this worked fine and I've just made sure that it still works, which it does. So I have to assume that there's a bit of a problem on your end. Make sure to check out the logs etc to see what could be wrong.
