### ISSUE TITLE
MemberService.CreateMember allows duplicate usernames

### ISSUE THREAD

**Issue by stefankip** [umbraco/Umbraco-CMS#8951]
Using Umbraco v8.6.4

I found out it's possible to create members with the same username using the `MemberService.CreateMember` method.
This shouldn't be possible, right?

**Comment by nul800sebastiaan** [comment]
Yes I believe it could be possible for the (admittedly probably never used) reason that you could do some kind of multi-tenancy (same member store, different sites using it, for example).
I doubt we're going to want to change this (it would probably break something for someone) but I'll ask around.

For now, check if a member with that username exists before you try and create it.

**Comment by vaags** [comment]
> I doubt we're going to want to change this (it would probably break something for someone) but I'll ask around.

Any updates on this?

**Comment by harry-gordon** [comment]
I would love to see this changed; I think in 90% of cases duplicate username/emails are undesirable. What even is the login behavior in this case? 🤯

In the meantime, if we wanted to work around this by adding a primary key on username could we just do it with migrations? 🤔

**Comment by elit0451** [comment]
The workaround for this is to call `MemberService.Exists(username)` or `MemberService.GetByUsername(username)` and/or `MemberService.GetByEmail(email)`.

**Comment by elit0451** [comment]
Hi again, 

We recognize the issue at hand, and generally, we try to improve our services and move the business logic from controllers to services for Umbraco 13. However, fixing the current implementation for previous Umbraco versions will be too breaking, therefore, the workarounds I mentioned will be necessary for checking for duplicate usernames or emails for newly created members through code.

Having said this, I will close the issue.
