### ISSUE TITLE
8.7 Blocklist editor - unclear what kind of template is expected for partial view in element doctype

### ISSUE THREAD

**Issue by Jay-umbr** [umbraco/Umbraco-CMS#8952]
Just a small, but an annoying thing: when picking a view file for blocklist (on an element), it expects a plain html file, and does not accept anything else. That is not mentioned anywhere on the picker. Maybe it should be?

## Umbraco version

8.7

Reproduction
------------

Create a new blocklist editor on your project with at least 1 element type. On that element type, try to pick a custom view file - you are only able to select html files. When you try selecting cshtml, the picker will be unresponsive - no error code, nothing.
![image](https://user-images.githubusercontent.com/56038614/94002291-fd512a80-fd99-11ea-8843-dc164e9b4e18.png)

### Suggestion

Perhaps specifying somewhere that the picker only allows html files would make it more clear - I had to go with a trial and error approach.
Another thing is that any view created in the backoffice of Umbraco is a cshtml file by default. That is a bit counterintuitive that we use cshtml everywhere else, but not in blocklist element.

**Comment by nul800sebastiaan** [comment]
Understood, this will become a lot more clear when we can create them from the backoffice. I'll close this and we can continue with any ideas on the related issues: https://github.com/umbraco/Umbraco-CMS/issues/8877 and https://github.com/umbraco/Umbraco-CMS/issues/8890
