### ISSUE TITLE
NetCore: Introduction tour can't be completed

### ISSUE THREAD

**Issue by elit0451** [umbraco/Umbraco-CMS#8955]
### Bug summary

(1) Introduction tour cannot be completed due to a lost step on **alpha02**.

### Steps to reproduce

Navigate to Getting Started tours and begin the introduction tour.

### Expected result

We can complete the Introduction tour.

### Actual result

The tour cannot continue after step 7.

![image](https://user-images.githubusercontent.com/21998037/94125252-69916400-fe56-11ea-8b25-28d2f986244b.png)

**Comment by benjaminc** [comment]
It looks like the PR for this has been merged, and the subsequent PR that fixes an issue found after the first PR is also merged.  Is there anything still outstanding on this issue, or should this be closed?

**Comment by bergmania** [comment]
Thanks @benjaminc .. It should be closed - My bad
