### ISSUE TITLE
Adding Media via API fails for standard image Media Type

### ISSUE THREAD

**Issue by bielu** [umbraco/Umbraco-CMS#8956]
### Code:
``` 
IMediaType contentType = Current.Services.MediaTypeService.Get("image");
     
Media media1 = new Media("my new shiny Media", parentId,  contentType);
      media1.Key = mediaDefinition.ReferenceGuid;
    media1.SetValue(Current.Services.ContentTypeBaseServices, propertyTypeAlias, filename, filestream, culture, segment)
```
### Expected Result:
Image is propagated corectly and image cropper works as intended
### Actual Result:
Umbraco will fail with following error
`Newtonsoft.Json.JsonReaderException: Error parsing comment. Expected: *, got m. Path '', line 1, position 1.`

Description of issue:
As That will property will be propagated with Value as following:
`/media/uoreetde/myImage.png`
Instead of:
`{"crops":null,"focalPoint":{"left":0.5,"top":0.5},"src":"/media/uoreetde/myImage.png"}}`
the image fails on operation: ImageCropperPropertyEditor,AutoFillProperties
:)

**Comment by nul800sebastiaan** [comment]
@bielu I've updated the title as this is not an upload from CMS but your custom upload component, right?

How is the image mediatype configured for you? Does it have crops, if so which?

**Comment by bielu** [comment]
@nul800sebastiaan I tried same on clear umbraco with default Image, I made custom component to upload (but it doesnt matter). 
I don't have any crops, Any additional setting in my Media Type

**Comment by nul800sebastiaan** [comment]
Have you tried it the way it's described in the docs? https://our.umbraco.com/documentation/Reference/Management/Services/MediaService/#creating-a-new-media-from-an-uploaded-file

So your code would change to:

```csharp
        // not needed
        // IMediaType contentType = Current.Services.MediaTypeService.Get("image");

        IMedia media1 = Services.MediaService.CreateMedia("my new shiny Media", parentId, Constants.Conventions.MediaTypes.Image);
    media1.SetValue(Current.Services.ContentTypeBaseServices, propertyTypeAlias, filename, filestream);
```

**Comment by bielu** [comment]
I didn't but will give a try

**Comment by bielu** [comment]
@nul800sebastiaan I played with that and that way solved issue with Newtonsoft.Json.JsonReaderException,
but properties for that are still not setup correctly missing dimensions of images. 
Can be that related to using stream to upload from Emmbed image file in dll?

**Comment by bielu** [comment]
@nul800sebastiaan 
I spend time digging into issue, first halve is still question for me, but after spend definitly too much time looking into that, 
I notice that part of code:
https://github.com/umbraco/Umbraco-CMS/blob/655befde420faf427f72f1b39cc585cc15a8641d/src/Umbraco.Web/Media/Exif/ImageFile.cs#L120
doesnt contain definition for PNG image 😂

**Comment by bielu** [comment]
I am closing that issue as I figure out what was issue with properties, If I use overload with cultures/segment it will not work but it is not issue with Api.
