### ISSUE TITLE
Multi Node treepicker in Split View doesn't take into account second language 

### ISSUE THREAD

**Issue by gvr37leo** [umbraco/Umbraco-CMS#8972]
Multi Node treepicker in Split View doesn't take into account second language.
When you try to chose a new item in a multi node treepicker it will always show the contenttree in the currently selected language. The multi node treepicker in the second panel should instead show the contenttree in the language of that panel.

## Umbraco version 

I am seeing this issue on Umbraco version: 8.5.3

Reproduction
------------

### Bug summary
right click open image in new tab if you cant read the text
This image shows the correct version of the contenttree being shown on the french side of the split view
![image](https://user-images.githubusercontent.com/11957906/94406464-5cd08100-0172-11eb-872d-f4930317a3af.png)

This image shows the contenttree being shown in the wrong language on the dutch side of the split view
![image](https://user-images.githubusercontent.com/11957906/94407324-9bb30680-0173-11eb-82f8-a1d73ca25e4b.png)

### Specifics
url:/umbraco#/content/content/edit/3668?mculture=fr-BE&list=3665&page=1&filter=&orderBy=name&orderDirection=asc&cculture=fr-BE
i dont think the issue has to do with the url
umbraco version:8.5.3
browser:chrome 85.0.4183.121
didnt check in other browsers
see screenshots above

### Steps to reproduce

1 create 2 languages
2 create a node/Content using the 2 languages(turn on "allow varying by culture" on everything to enable the multi language stuff)
create it with a document type that has a multi node treepicker and publish it in both languages(name the node something different in both languages to make the bug as obvious as possible)
3 go to that node
4 open the second language in split view (done by opening the dropdown next to the name of the node, then click on "Open in split view" )
5 click on the "add" button of the multi node treepicker that is on the second language (usually the right side)
6 check if the contenttree is shown in the correct language

### Expected result

the contenttree should show the language corresponding to the language of the side that the multi node treepicker is in.
So if you click the node picker on the right side it should show the contenttree in the language of the right side of the split view
instead it is always shown in the language of the left side of the split view.

### Actual result
Contenttree is always shown in the language of the left side of the split view

**Comment by nul800sebastiaan** [comment]
Thanks, at the moment, the dropdown above the content tree determines which language gets shown in the picker.

We are looking for some help with that issue and a good addition for that feature could be that pickers opened in side-by-side editing will use the culture from the side where the picker was opened. 

I'll close this so that the discussion can continue on #7546.
