### ISSUE TITLE
v8: Pressing "ENTER" key on a Media Node property removes the associated File

### ISSUE THREAD

**Issue by hfloyd** [umbraco/Umbraco-CMS#8988]
I have several custom properties on a MediaType. There is also the Upload control for attaching a file.

A few of the properties are Repeatable Textstrings type (Umbraco.MultipleTextstring). When using the "Add" button, this works fine, but if the ENTER key is pressed to get a "new line", the uploaded file gets removed.

Here is a small video demo: [
Umbraco 8 - Media Node ENTER bug.mp4 - With captions](https://drive.google.com/file/d/1SiRYUjRbQmFmyRGco_e8CG7PACtfWM7t/view?usp=sharing )
![Edit_ Test - (Local) Media - hind-hpi local](https://user-images.githubusercontent.com/1252593/94602613-17d84780-0263-11eb-8c51-bcc110a64ebe.gif)

### Umbraco version

I am seeing this issue on Umbraco version:  8.7.0

### Steps to reproduce

1. Create a MediaType with a Upload control and a repeatable textstring control.
2. Add a node of the type, add a file via the Upload. 
3. Add some textstring data, click the enter key after adding a line.
4. Notice the uploaded file gets cleared.

### Expected result

I'd expect that the file (and any other property data) would still be present.

### Actual result

The file gets removed.

**Comment by kjac** [comment]
Good catch @hfloyd ... PR in #9020

**Comment by hfloyd** [comment]
Awesome! Thanks for the quick fix, @kjac ! I hope it gets approved for the next release. :-)

**Comment by nul800sebastiaan** [comment]
Fixed in https://github.com/umbraco/Umbraco-CMS/pull/9020

**Comment by hfloyd** [comment]
FYI - I know this fix was affected with the reversal of the code in https://github.com/umbraco/Umbraco-CMS/pull/9604 (v8.10.1)
but wanted to document that now clicking ENTER does NOT remove the selected file, but DOES now cause a "Save" on the Media. Using "Ctrl+ENTER" on other properties will however, allow the addition of extra lines, etc.
