### ISSUE TITLE
EmbedProviders - throw System.Xml.XmlException

### ISSUE THREAD

**Issue by lucasmichaelsengorm** [umbraco/Umbraco-CMS#8989]
A brief description of the issue goes here.

## Umbraco version
I am seeing this issue on Umbraco version: 8.6.5 Cloud

Reproduction
------------
### Bug summary
There is not a way to reproduse it, right now i spotted the error due to that the Cloud App in Umbraco not succefully calling Viemo. 

The problem is the server is meaby not calling Vimeo, currect therefor getting invalid XML response. Couse it to throw an XmlException.

I´m not using Modelbuilder so my line of code is as following 
`public string VimeoVideo  => !string.IsNullOrWhiteSpace(Get<string>("heroVimeo")) ? new Vimeo().GetMarkup(Get<string>("heroVimeo")) : string.Empty; public string YoutubeVideo => !string.IsNullOrWhiteSpace(Get<string>("heroYoutube")) ?  new YouTube().GetMarkup(Get<string>("heroYoutube")) : string.Empty;`

So i use the inbuild Vimeo Embedprovider, the result should be the HTML from the OEmbed API in Embed insted i get the following error:

![image](https://user-images.githubusercontent.com/69140700/94651144-43f1d800-02f8-11eb-8320-dcca41428e33.png)

I suggest the in the EmbedBaseProvider controller is build a try catch along the Logging, to prevent the Exception to bust up and destroy the MVC render controller and prevent the website to work. Along with logging to tell why the call is not succeded.

**Comment by lucasmichaelsengorm** [comment]
Found near the same issue on the forum https://our.umbraco.com/forum/using-umbraco-and-getting-started/103199-vimeo-links-can-no-longer-be-embeded#comment-322490

**Comment by nul800sebastiaan** [comment]
Looks there might have been a temporary problem on the Vimeo side, seems to work fine now!

**Comment by lucasmichaelsengorm** [comment]
@nul800sebastiaan unfurturnaly not, ask Hjalte about the case. There next if a service is down, or infrastur is failing to succeed the call, the website should not run into an status 500 exeception, and kill the site. Let´s sat youtube is down for 2 whole days becuase a hacker attack the, website should be dead for thoese 2 days.
