### ISSUE TITLE
Feature: Begin able to copy a whole block (including layout and settings)

### ISSUE THREAD

**Issue by nielslyngsoe** [umbraco/Umbraco-CMS#8990]
As a content editor, I would like the copy feature on Blick List Property Editor to copy the whole block, including settings and layout specific properties.

For this to happen we would need to come up with a new type for Clipboard Service, properly named "Block". This should hold an object of the Content ElementType Data, Settings ElementType Data and the layout object.

We need a new paste-resolver to resolve this new type, the resolver should run the ElementType resolvers for the content part and the settings part.

In the situation of a Block-Tree type editor, I currently don't see this feature supporting child-blocks (Not referring to nested blocks), we would not consider copying child-blocks as part of this feature for now. This means that this feature cannot copy a parent block from a tree-structure including the tree-child blocks. Just a single Block.
To clarify you would still be able to have nested property editors of any kind, so nested block editors are supported.

This feature has been requested here:
https://github.com/umbraco/Umbraco-CMS/issues/8905

---
_This item has been added to our backlog [AB#8699](https://dev.azure.com/umbraco/243e7927-03b2-44e2-908f-d4ac7ea5daaa/_workitems/edit/8699)_

**Comment by uSkinned** [comment]
Settings should definitely be copied as well when copying a block. Do not understand why you wouldnt want this to happen.

**Comment by uSkinned** [comment]
Interestingly, settings on a nested block item are copied!

**Comment by nul800sebastiaan** [comment]
@uSkinned not sure I understand this comment: 

> Settings should definitely be copied as well when copying a block. Do not understand why you wouldnt want this to happen.

That's what this issue is for, as Niels says:

> As a content editor, I would like the copy feature on Blick List Property Editor to copy the whole block, including settings and layout specific properties.

Maybe I'm missing something?

----- 

_Note: Additional to this issue, this should fix the related issue https://github.com/umbraco/Umbraco.Uno.Issues/issues/25_

**Comment by uSkinned** [comment]
@nul800sebastiaan sorry for not being clear in my comment. I was just confirming the importance of copying settings and that it definitely should be part of the copy feature .

**Comment by ronaldbarendse** [comment]
@nielslyngsoe One thing to consider is that settings aren't directly visible and you might end up copying unwanted values. For example: some blocks might have an optional anchor value (to link to that content on the front-end) that must be unique to work correctly, but that property isn't used/entered enough to add it to the content data.

Maybe copying settings should be optional (configured per editor/block or on copy) or better yet: prompt whether to also paste the settings. This should only be required when the copied block contains settings...

Also, if we're extending the clipboard service, this should also support copying layout items that contain multiple blocks, e.g. complete rows/columns when a Block Grid editor becomes available.

**Comment by nielslyngsoe** [comment]
Hi @ronaldbarendse thanks for your thoughts.

This will defiantly also transfer layout props. But the specific concept of transferring related or child-blocks like in a grid-scenario is not supported, just jet. I did put a concept comment into the code. So did give it a few thoughts. The hard part is that most of the work needs to be done by the Property Editor implementing this. As in gathering the data for the inner blocks etc.
To others reading this, it's NOT in regards to nested Block Editors, this will work just fine.

In relation to Settings, I understand some users might not need to transfer this, but presenting the choice will make things more complicated and I think most users will be happy and find it initiative that this is included. And will basically have to revert the part of settings they are not happy with transferring.

I see the case where settings are used to define a lead/tracking key that is supposed to be unique to the given Block. We might need to look different on this case. I think what you are seeking to solve would be the ability to, on Property-level, define whether its data can be copied. Cause we would also need this implemented for cloning whole Documents, as the same case would come into play here. :-)

**Comment by warrenbuckley** [comment]
Is fixed in this PR and is due for 8.10
https://github.com/umbraco/Umbraco-CMS/pull/9258
