### ISSUE TITLE
Trying to remove a section from a user group tries to remove user from group

### ISSUE THREAD

**Issue by Mantus667** [umbraco/Umbraco-CMS#9036]
If I try to remove the Translation section from the Administrator Group I get an error indicating that I want to remove the user "undefined" from the actual group.

## Umbraco version

I am seeing this issue on Umbraco version: 8.8.0

Reproduction
------------

### Bug summary

Deleting a section from a user group shows a weird error message related to user deletion.

### Specifics

* Umbraco Version 8.8.0
* Chrome Brwoser 83.0.4103.116
* not checked in other browsers
![image](https://user-images.githubusercontent.com/1239113/94917224-6fb7be00-04b0-11eb-81ac-4234db77886d.png)

### Steps to reproduce

* Go to the User section
* Switch to the user groups
* Select the administrator group
* Click on "remove" of a section
* The error message should appear

### Expected result

The section should be removed from the editor without any error message

### Actual result

An error message is shown related to user not to user group indicating a user will be deleted

**Comment by kjac** [comment]
Oh my! Good catch, I can reproduce... will fix 👍

**Comment by kjac** [comment]
It also happens when removing granular permissions from groups... fix in #9048.

Thanks for reporting this, @Mantus667 

@nul800sebastiaan this might be relevant for a patch release is one is planned before 8.9

**Comment by Mantus667** [comment]
Thanks for the fast fix @kjac #h5yr
