### ISSUE TITLE
Pre fill List Name

### ISSUE THREAD

**Issue by sarahwilson2020** [umbraco/Umbraco-CMS#9084]
Hi,

We are using the list feature with multiple languages. Is it possible to pre-fill the name field for the secondary language with a copy of the primary language? 

<img width="755" alt="umbraco list" src="https://user-images.githubusercontent.com/72136840/95183598-1d331600-07be-11eb-92d8-c9e296eb6dad.PNG">

It seems like the secondary language already knows about the name field from the primary language, as it shows on this view.

<img width="631" alt="umbraco list view" src="https://user-images.githubusercontent.com/72136840/95183514-fd9bed80-07bd-11eb-8179-f30540c4334e.PNG">

At the moment we have to add in the name for every language, and it would be really helpful if this could be an inherited field, especially as we're about to create a global list that covers 31 languages.

I've also mentioned this on the Umbraco forum, apologies if this is a duplicate.

Thanks

Sarah

**Comment by nul800sebastiaan** [comment]
Hmm, it seems like you're the first one to request this and I am struggling a little bit with what the use case is exactly, assuming that Slayer is the band name and of course that won't vary in different languages? Maybe you can tell me a little more on what you're trying to do.

However, at the moment this is how the CMS works, we have assumed, so far, that each language would have it's own title so the title field is always variant. Not an easy fix! And not something we'd want to do by default, making the title field invariant. In fact, you'd probably also not like the title to be invariant, I imagine for SOME nodes you might want the title to be different? Making it invariant would no longer allow you to do edits on the other languages.. it's complex!

For now I could see a solution in adding some kind of javascript that would copy the node name over automatically, not sure how I would approach that but it's worth investigating.

**Comment by sarahwilson2020** [comment]
Hey, thanks for looking at this.  Since raising it, our developers have found a way to do this in javascript, so I'm happy to close it down.  Thanks for your time!
