### ISSUE TITLE
The value for custom member properties cannot be removed in the back office of v8.8 

### ISSUE THREAD

**Issue by deekoulos** [umbraco/Umbraco-CMS#9093]
Hey Guys,

this bug is new in 8.8. I tested this with 8.7 and it works fine there. 

Steps to Reproduce:

Add a custom property editor to the default member type:
![image](https://user-images.githubusercontent.com/55948134/95241866-af630a80-080e-11eb-987e-213587a36ab4.png)

Create a new member and add a string to the new property Phone
![image](https://user-images.githubusercontent.com/55948134/95241927-c7d32500-080e-11eb-9cba-47113dac4383.png)

Save and refresh the member editor page
The entered value should stay, which is fine.

Change the value, hit save and refresh
The entered value should stay, which is fine.
![image](https://user-images.githubusercontent.com/55948134/95242025-ec2f0180-080e-11eb-9eba-9761a18f9f51.png)

Now remove the entered value, hit save and refresh
The removed value is not removed
![image](https://user-images.githubusercontent.com/55948134/95242025-ec2f0180-080e-11eb-9eba-9761a18f9f51.png)

I tested this with other property types like member group picker or numerics. Same behaviour. So you can add values to custom properties, you can change them but you cant remove the values. 

I tested this behaviour on fresh installed solutions and it came up out of nowhere with the v8.8. Earlier versions work properly in this regard.

Really painful and critical bug in our case, since there are so many business logic related actions for editing members in the BO, which require to remove values from property types.... 

What I also see is that after every edit of a member, no matter if you have added new custom property types or you just edit the default properties, a warning is logged:
![image](https://user-images.githubusercontent.com/55948134/95251108-58176700-081b-11eb-9e7f-101d6e47cf0a.png)

First I thought this has something to do with our solution, then I tested this behaviour with a fresh installed solution 8.8, edited the member and saw the warning log after every edit and save. 

---
_This item has been added to our backlog [AB#8780](https://dev.azure.com/umbraco/243e7927-03b2-44e2-908f-d4ac7ea5daaa/_workitems/edit/8780)_

**Comment by dawoe** [comment]
Could be related to this PR : https://github.com/umbraco/Umbraco-CMS/pull/8525/
Is the only thing I can see in the 8.8 release that could affect this.

@nul800sebastiaan could someone from HQ look into this ?

**Comment by nul800sebastiaan** [comment]
Yep, thanks I was getting to this one, we'll need to have a look soon!

**Comment by nul800sebastiaan** [comment]
Yes, must be #8525 - I can repro in 8.6.5 as well and the nightly build of the upcoming 8.7.1. We should get it fixed soon!

**Comment by deekoulos** [comment]
@nul800sebastiaan do you see any relation between these 2 recent member bugs and the warning I posted here?

**Comment by nul800sebastiaan** [comment]
When I revert PR #8525 then this issue #9093 works again and so #9095 as well.

The warning is unrelated. I also get it when I revert #8525.

**Comment by nul800sebastiaan** [comment]
Fixed in https://github.com/umbraco/Umbraco-CMS/pull/9146

**Comment by deekoulos** [comment]
Hey @nul800sebastiaan ,

is the release assignment correct? since this bug was related to version 8.8, I am a bit confused that it's fixed within 8.7.1. I was expecting a fix in 8.8.1 instead.

**Comment by nul800sebastiaan** [comment]
It's very confusing: it was an issue introduced in 8.6.5. Not in 8.7.0 because we hadn't merged everything from 8.6.5 up to 8.7.0. However we did merge up from 8.6.5 to 8.8.0 so it was also a problem there. Soon we'll be able to equalize all the versions and not have all this confusion, sorry!

**Comment by deekoulos** [comment]
Hey @nul800sebastiaan 

as long as I remember, this issue was related to this one: https://github.com/umbraco/Umbraco-CMS/issues/9095

What is a bit confusing, is that this issue is not assigned to the version 8.9.1, but 9095 is assigned to 8.9.1. Since I would like to run an upgrade to 8.9.1, but only if this issue is also fixed in that version, could you please check this out and respond, if this is also fixed in 8.9.1?

Thanks 
Dee

**Comment by nul800sebastiaan** [comment]
Apologies! Updated, yes, also fixed in 8.9.1.

**Comment by deekoulos** [comment]
big thanks mate!
