### ISSUE TITLE
Backoffice translation questions

### ISSUE THREAD

**Issue by SteveVaneeckhout** [umbraco/Umbraco-CMS#9096]
I saw some missing Dutch translations in the backoffice so I decided to improve them for Hacktoberfest. I think I found the right directory: `Umbraco.Web.UI\Umbraco\config\lang`

I have a couple of questions first:
- Which file is leading to base my translations on? My guess would be `en_us.xml` judging by file size but I noticed `en.xml` contains some keys that `en_us.xml` does not.
- Is there a tool to make it easier to update the XML files or do I have to do it manually?
- Is it OK to order the XML elements alphabetically by key? I noticed double keys in a couple of translation files, this could have been prevented if they were ordered. It's also easier when comparing 2 files to see which translations are missing and need to be added.

**Comment by nul800sebastiaan** [comment]
@SteveVaneeckhout 

* Yes, `en_us.xml` it should be mostly in sync with `en.xml`
* Nope 😊 🙈 
* Please do not update the order, it is going to lead to massive merge conflicts 🤯 💥
