### ISSUE TITLE
Creating an empty template causes a duplicate template to get created.

### ISSUE THREAD

**Issue by nikolajlauridsen** [umbraco/Umbraco-CMS#9104]
If you create an empty template and don't click on the editor at all two templates will be created instead of one. 

![dupe template](https://user-images.githubusercontent.com/16456704/95340236-336fcd80-08b5-11eb-9c72-cd4a319171d1.gif)

### Steps to reproduce:
1. Create a template from the context menu
2. Give it a name
3. Click save
It's very important that you don't click the editor at all, or you will be redirected to the edit page URL, and the bug won't occur.

### Additional information
I have a feeling that there is an event that triggers when you click the editor, which also triggers when you click the save button, causing two save actions to start, but this is just a hunch, and the front end code is a foreign place for me, and I dare not venture too far into it 😅

**Comment by nul800sebastiaan** [comment]
I think it happens when the title field loses focus (so when you click the save button), at least that's what I've seen happening before, so it could be that you are able to repro by just giving it a title and then clicking in the code editor. Not sure, but I recall something like that.

**Comment by nikolajlauridsen** [comment]
Ah so that's when it happens, but I think we can close the issue again, this morning I could not reproduce manually, only with cypress tests, so I'm not quite sure what's going on.

But just to clarify, yesterday it would only happen if you clicked the save button directly after entering the name if you clicked anywhere else, and then save button, only one template would be created, it would however still perform the save action twice, once when clicking away from the name field, and once when you clicked the save button, but the save action when clicking the button would just update the existing template as intended.
