### ISSUE TITLE
DateTimePicker saves wrong time if crossing Summer/Winter time border

### ISSUE THREAD

**Issue by mirkomaty** [umbraco/Umbraco-CMS#9107]
There is a problem with the DateTimePicker that occurs in the following scenario: 

Currently we have daylight saving time. If I want to publish or unpublish a document at a date during winter time, the saved time will be an hour later than the entered time.

This occurs in V7 and V8. In V8 you can see the two different times at one screen, in version 7 I can't see the wrong time setting and have to remember to specify one hour less than I intend.

![Issue in V8](https://www.formfakten.de/media/umbracoissue/Datepicker2.png) 

## Umbraco version

I am seeing this issue on Umbraco version: 7.6.14 and 8.7.0

Reproduction
------------

### Steps to reproduce

If the current date is in summer time, plan publishing or unpublishing of a document at winter time. Enter a date AND time value. Save and refresh the page. You'll see a time 1 hour later than the time entered.

### Expected result

Umbraco saves the time I entered.

### Actual result

Umbraco saves a time value 1 our later. I guess, that crossing the border from winter time to summer time will result in -1 hour offset.

**Comment by nul800sebastiaan** [comment]
Thanks! We've put this in `up for grabs` before but nobody seemed to want to help fix it - https://github.com/umbraco/Umbraco-CMS/issues/3028

If you're happy to help fix it then we'd love that but I will say it's probably a huge task. I'll close this for now and if you're happy to work on this then I can re-open #3028!
