### ISSUE TITLE
8.9rc: x.properties.UmbracoBackOfficeExternalLoginOptions is undefined (Azure AD)

### ISSUE THREAD

**Issue by SimonHilo** [umbraco/Umbraco-CMS#9124]
x.properties.UmbracoBackOfficeExternalLoginOptions is undefined (Azure AD & 8.9RC)

I am trying to configure backoffice login with Azure AD in the new 8.9RC.

I run into a javascript error on the login page:

	TypeError: x.properties.UmbracoBackOfficeExternalLoginOptions is undefined
		hasDenyLocalLogin https://umbraco89.dev.shol.dk/umbraco/js/umbraco.services.js?cdv=1:4552
		any Underscore
		hasDenyLocalLogin https://umbraco89.dev.shol.dk/umbraco/js/umbraco.services.js?cdv=1:4551
		UmbLoginController https://umbraco89.dev.shol.dk/umbraco/js/umbraco.directives.js?cdv=1:687
		Angular 25
		<anonymous> https://umbraco89.dev.shol.dk/umbraco/Application?umb__rnd=98db4099b7f509b5ad38540a7d9bc7bc:43
		jQuery 9
		<anonymous> https://umbraco89.dev.shol.dk/umbraco/Application?umb__rnd=98db4099b7f509b5ad38540a7d9bc7bc:41
		i https://umbraco89.dev.shol.dk/umbraco/lib/lazyload-js/lazyload.min.js:1
		p https://umbraco89.dev.shol.dk/umbraco/lib/lazyload-js/lazyload.min.js:1
		k https://umbraco89.dev.shol.dk/umbraco/lib/lazyload-js/lazyload.min.js:1
		js https://umbraco89.dev.shol.dk/umbraco/lib/lazyload-js/lazyload.min.js:1
		<anonymous> https://umbraco89.dev.shol.dk/umbraco/Application?umb__rnd=98db4099b7f509b5ad38540a7d9bc7bc:1
	angular.js:15635:41
		Angular 18
		<anonym> https://umbraco89.dev.shol.dk/umbraco/Application?umb__rnd=98db4099b7f509b5ad38540a7d9bc7bc:43
		jQuery 9
		<anonym> https://umbraco89.dev.shol.dk/umbraco/Application?umb__rnd=98db4099b7f509b5ad38540a7d9bc7bc:41
		i https://umbraco89.dev.shol.dk/umbraco/lib/lazyload-js/lazyload.min.js:1
		p https://umbraco89.dev.shol.dk/umbraco/lib/lazyload-js/lazyload.min.js:1
		(Async: EventHandlerNonNull)
		k https://umbraco89.dev.shol.dk/umbraco/lib/lazyload-js/lazyload.min.js:1
		js https://umbraco89.dev.shol.dk/umbraco/lib/lazyload-js/lazyload.min.js:1
		<anonym> https://umbraco89.dev.shol.dk/umbraco/Application?umb__rnd=98db4099b7f509b5ad38540a7d9bc7bc:1
		
	
I have configured the backend according to the examples given in the two packages:
	Install-Package UmbracoCms.IdentityExtensions
	Install-Package UmbracoCms.IdentityExtensions.AzureActiveDirectory
	
I *think* my configuration is correct, and I wouldn't expect a frontend error like this if it was wrong.

---
_This item has been added to our backlog [AB#8847](https://dev.azure.com/umbraco/243e7927-03b2-44e2-908f-d4ac7ea5daaa/_workitems/edit/8847)_

**Comment by SimonHilo** [comment]
Screenshot:

![angular-error](https://user-images.githubusercontent.com/47662092/95560103-105e2e80-0a19-11eb-8c97-68558445b27b.png)

**Comment by nul800sebastiaan** [comment]
Thanks @SimonHilo Any chance you can share your configuration (without giving away the secrets that you need to put in there)?

**Comment by mebrein** [comment]
You need to configure with SetBackofficeExternalLoginProviderOptions:
```
adOptions.SetBackOfficeExternalLoginProviderOptions(new BackOfficeExternalLoginProviderOptions
            {
                AutoRedirectLoginToExternalProvider = true,
                DenyLocalLogin = false,
                AutoLinkOptions = new ExternalSignInAutoLinkOptions
                {
                    AllowManualLinking = true,
                    //OnAutoLinking =
                    
                }
            }); 
```

**Comment by SimonHilo** [comment]
@mebrein Yes, that solved the problem for me.

It would be helpful to include this in the initial UmbracoADAuthExtensions.

**Comment by Shazwazza** [comment]
we'll be sure to make it not throw and set a default value.

**Comment by lars-erik** [comment]
Hi all,  
Seems this is still affecting the user dialog in the backoffice.  
It just says "user.name".  
I'll see about our AD options later, but just thought I'd drop a heads up.

**Comment by yasserpadia** [comment]
> Hi all,
> Seems this is still affecting the user dialog in the backoffice. (8.9.1)
> It just says "user.name".
> I'll see about our AD options later, but just thought I'd drop a heads up.

We are also experiencing this issue. Is there a fix for it?

**Comment by Shazwazza** [comment]
I will also post your other question from the other places you've mentioned for completeness: 

* https://github.com/umbraco/UmbracoIdentityExtensions/issues/40#issuecomment-755719059
* https://shazwazza.com/post/configuring-azure-active-directory-login-with-umbraco/#comment-5216116129

**Comment by Shazwazza** [comment]
@yasserpadia can you replicate the issue from a vanilla Umbraco install? Can you replicate the problem in 8.9?

**Comment by yasserpadia** [comment]
> @yasserpadia can you replicate the issue from a vanilla Umbraco install? Can you replicate the problem in 8.9?

Yes this is a problem on vanilla as well.
The following from @mebrein post with a tweak has actually fixed this issue.
Changing autoLinkOptions.AllowManualLinking = **false** to **true** as below.
Are you able to check if this is a complete fix and if it needs to be added to any documentation?

_var autoLinkOptions = new ExternalSignInAutoLinkOptions(true);  // autoLinkExternalAccount = true
autoLinkOptions.AllowManualLinking = **true**;

adOptions.SetBackOfficeExternalLoginProviderOptions(new BackOfficeExternalLoginProviderOptions
{
    AutoRedirectLoginToExternalProvider = false,
    DenyLocalLogin = false, // if ANY external provider has this property set, local login will be disabled
    AutoLinkOptions = autoLinkOptions,
});_

**Comment by Shazwazza** [comment]
Thanks @yasserpadia that sounds like a bug, are you able to open a new one with simple steps to replicate?

**Comment by organicglenn** [comment]
@Shazwazza Do you still need a new bug opened for this?  I am having this problem in 8.9.1 and just confirmed it with a vanilla install of 8.10.1.

**Comment by thomashdk** [comment]
@organicglenn Have the same issue on 8.11.1

Did you fix it ?

**Comment by organicglenn** [comment]
No, this is still a bug.  I did not create a new Issue for it.

**Comment by qz2rg4** [comment]
Any news on the logout.The Account tab just shows "user.name". this I am running Umbraco 8.11.1

**Comment by jericyuen** [comment]
@thomashdk @qz2rg4 

I've added the below in my UmbracoADAuthExtensions.cs file

I've set the AllowManualLinking = true

And I'm on Umbraco 8.12.1

`adOptions.SetBackOfficeExternalLoginProviderOptions(
                new BackOfficeExternalLoginProviderOptions
                {
                    AutoLinkOptions = new ExternalSignInAutoLinkOptions(
                        // must be true for auto-linking to be enabled
                        autoLinkExternalAccount: false,

                        // Optionally specify default user group, else
                        // assign in the OnAutoLinking callback
                        // (default is editor)
                        defaultUserGroups: new[] { Constants.Security.EditorGroupAlias },

                        // Optionally specify the default culture to create
                        // the user as. If null it will use the default
                        // culture defined in the web.config, or it can
                        // be dynamically assigned in the OnAutoLinking
                        // callback.
                        defaultCulture: null)
                    {
                        // Optionally you can disable the ability to link/unlink
                        // manually from within the back office. Set this to false
                        // if you don't want the user to unlink from this external
                        // provider.
                        AllowManualLinking = true,
                    },

                    // Optionally you can disable the ability for users
                    // to login with a username/password. If this is set
                    // to true, it will disable username/password login
                    // even if there are other external login providers installed.
                    DenyLocalLogin = false,

                    // Optionally choose to automatically redirect to the
                    // external login provider so the user doesn't have
                    // to click the login button. This is
                    AutoRedirectLoginToExternalProvider = false
                });`

**Comment by alasdair-at-flasher** [comment]
This also applies to GoogleAuth in Umbraco 8.12.

`
public static void ConfigureBackOfficeGoogleAuth(this IAppBuilder app, string clientId, string clientSecret,
            string caption = "Google", string style = "btn-google", string icon = "fa-google")
        {
            var googleOptions = new GoogleOAuth2AuthenticationOptions
            {
                ClientId = clientId,
                ClientSecret = clientSecret, 
                //In order to allow using different google providers on the front-end vs the back office,
                // these settings are very important to make them distinguished from one another.
                SignInAsAuthenticationType = Constants.Security.BackOfficeExternalAuthenticationType,
                //  By default this is '/signin-google', you will need to change that default value in your
                //  Google developer settings for your web-app in the "REDIRECT URIS" setting
                CallbackPath = new PathString("/umbraco-google-signin")
            };
            googleOptions.ForUmbracoBackOffice(style, icon);
            googleOptions.Caption = caption;

            var autoLinkOptions = new ExternalSignInAutoLinkOptions(true);  // autoLinkExternalAccount = true
            autoLinkOptions.AllowManualLinking = true;

            googleOptions.SetBackOfficeExternalLoginProviderOptions(new BackOfficeExternalLoginProviderOptions
            {
                AutoRedirectLoginToExternalProvider = false,
                DenyLocalLogin = false, // if ANY external provider has this property set, local login will be disabled
                AutoLinkOptions = autoLinkOptions,
            });

            app.UseGoogleAuthentication(googleOptions);
        }
`
