### ISSUE TITLE
"More than 700 people from all over the world meet each year in Denmark"

### ISSUE THREAD

**Issue by soreng** [umbraco/Umbraco-CMS#9135]
When installing Umbraco, you get served random facts about Umbraco. One "fact" is not so factual:

"More than 700 people from all over the world meet each year in Denmark in May for our annual conference [...]"

## Umbraco version

I am seeing this issue on Umbraco version: all v8 versions

Reproduction
------------

If you're filing a bug, please describe how to reproduce it. Include as much
relevant information as possible, such as:

### Bug summary

install umbraco, and the message may appear

**Comment by kistva** [comment]
Hi @soreng
What do you propose the text should be then?

- "**Normally** more than 700 people from all over the world meet each year in Denmark  _in May_ for our annual conference [...]"
- "**Usually** more than 700 people from all over the world meet each year in Denmark  _in May_ for our annual conference [...]"
- "More than 700 people from all over the world meet each year in Denmark _in May_ for our annual conference [...]"


**Added text** and _Removed text_

**Comment by nul800sebastiaan** [comment]
I think the whole world is in agreement that 2020 doesn't count as a year.
