### ISSUE TITLE
Language variants - non-varying properties default to Default language, not Fallback language

### ISSUE THREAD

**Issue by Jay-umbr** [umbraco/Umbraco-CMS#9151]
When you work with multiple languages and have some properties that do not very by culture, those properties default to the "Default" backoffice language (Default: English-US). However, it would make more sense if the default content in that case was pulled from the Fallback language instead.

## Umbraco version

Umbraco 8.8.0 (though it probably is the same for previous versions)

Reproduction
------------

In the backoffice, create a new language- let's say Danish. Set Danish as Default. Fallback to none.
Add another language (or use English-US which is already there for new projects). Set that language fallback to Danish.
Add yet another language, in my example - Chinese. It should fallback to English.

Now, create a new document type. Allow vary by culture on the doctype - make a property and do NOT allow vary by culture on that. It should fallback to another language.

Create a new content node with that doctype on the default Danish language, then create another node in English language (you will see it will default to the text you set on the Danish version),

Create yet another node with the Chinese language. Since Chinese should fallback to English, we would expect to see the default property filled out from the English node - however, it will be inherited from the Danish language, since that is the default language.

### Expected result

Chinese node's property that is not variant by culture fallbacks to the language specified in Chinese's fallback - so it is in English.
![image](https://user-images.githubusercontent.com/56038614/95861226-6efd1280-0d61-11eb-8788-6b85e0b1703f.png)

### Actual result

Chinese node's property is inherited from the Danish language.
![image](https://user-images.githubusercontent.com/56038614/95861189-64db1400-0d61-11eb-8473-4dcacd7e8660.png)

**Comment by kjac** [comment]
Hi @Jay-umbr 😄 

Hmmm well if your property is non-variant, it won't really matter which language it defaults to, since you can only edit it in the default language anyway?

**Comment by Jay-umbr** [comment]
Hey Kenn!
Seems like I clearly did not think this through :)
Yeah, you are right. Closing this one

**Comment by kjac** [comment]
😊
