### ISSUE TITLE
C# API source links are broken

### ISSUE THREAD

**Issue by jannikanker** [umbraco/Umbraco-CMS#9152]
## Detailed description
I'm not sure where this issue belongs (stems from), but the content is on the Our domain so I figured I'd report it here. If I go to https://our.umbraco.com/apidocs/v8/csharp/api/Umbraco.Core.Attempt.html (example) and click "View Source" I am pointed towards https://github.com/umbraco/Umbraco-CMS/blob/8.8/src/Umbraco.Core/Attempt.cs/#L8 which gives me a Page Not Found.

However, https://github.com/umbraco/Umbraco-CMS/blob/v8/8.8/src/Umbraco.Core/Attempt.cs/#L8 works.

It seems to be the same on every page I've tried, so I'd venture a guess that it's a common issue for all the source links currently.

I'd be game to try and fix this myself if someone could point me towards where the magic happens? Or let me know if this issue actually belongs in another repo :-)

**Comment by jannikanker** [comment]
Argh indeed :-/ I'll take a look ASAP :-)

**Comment by nul800sebastiaan** [comment]
Fixed in https://github.com/umbraco/Umbraco-CMS/pull/9326

**Comment by nul800sebastiaan** [comment]
Bad news/good news: too bad, that didn't work. 

But! Good: The way to make it work is if we build the docs from a tag, it looks like we just can not have a / in the branch name, that messes up the docs. But now it works beautifully when using the tag `release-8.13.0` to build from. So all good now and we know what to do in the future.
