### ISSUE TITLE
Preview shows all configured languages even when not varying by culture

### ISSUE THREAD

**Issue by dawoe** [umbraco/Umbraco-CMS#9153]
The preview shows all configured languages even when a item is not varying by culture.

## Umbraco version

I am seeing this issue on Umbraco version: 8.7 and up, could be on lower onces as well.

Reproduction
------------

### Bug summary

When previewing all the languages are shown that are configured. I would only expect the language choice to popup when a item is configured to vary by culture. And only see the languages that are already created.

This is somehow how related to #7612. Would be nice if we can fix them in one go.

### Specifics

The languages are retreived here :
https://github.com/umbraco/Umbraco-CMS/blob/eec1e95eb29d9589ecb1b2de395dc9e5a91256b7/src/Umbraco.Web/Editors/PreviewController.cs#L67

### Steps to reproduce

1. Install a new Umbraco installation and use the default starter kit.
2. Add a additional language.
3. Preview a item. 

### Expected result

You will see no language choice in the preview

### Actual result

You see a language choice in the preview

![image](https://user-images.githubusercontent.com/1193822/95889166-5e10c900-0d82-11eb-9e38-1b4f950b3a46.png)

**Comment by patrickdemooij9** [comment]
PR: https://github.com/umbraco/Umbraco-CMS/pull/9183
