### ISSUE TITLE
Remove legacy Instagram oEmbed provider

### ISSUE THREAD

**Issue by ronaldbarendse** [umbraco/Umbraco-CMS#9155]
The Instagram oEmbed provider provided by Umbraco uses the endpoint that will be deprecated on October 24, 2020: 
https://github.com/umbraco/Umbraco-CMS/blob/e9627f2ee962a73cd8c007a42845c9129e3339ee/src/Umbraco.Web/Media/EmbedProviders/Instagram.cs#L7

More information can be found on https://developers.facebook.com/docs/instagram/oembed-legacy and about the new endpoint on https://developers.facebook.com/docs/instagram/oembed.

Because the new endpoint requires either an App Access Token (recommended) or Client Access Token, Instagram oEmbed support can't be provided out of the box anymore (and would otherwise at least require rewriting this provider).

The same applies to the Facebook page/post/video oEmbed endpoints, but it looks like Umbraco never provided support for those (see https://developers.facebook.com/docs/plugins/oembed-legacy and https://developers.facebook.com/docs/plugins/oembed).

**Comment by nul800sebastiaan** [comment]
Well that's unfortunate. The recommended replacement is not a very workable solution either as it requires a lot of setup work, unlike this one which worked without authentication whatsoever. 

I'll mark this as breaking because there's no alternative at the moment.

This is also quite disastrous for existing installs and I don't see any fixes apart from someone building a custom OEmbed provider that can take in keys as a config etc, super cumbersome. 😢

These are the new requirements: 
![image](https://user-images.githubusercontent.com/304656/95997436-10549900-0e34-11eb-9540-945b982fd7da.png)

**Comment by ronaldbarendse** [comment]
Very unfortunate indeed, especially because the depreciation period is very short, as the change is introduced as part of the new v8 API endpoints in August: https://developers.facebook.com/blog/post/2020/08/04/Introducing-graph-v8-marketing-api-v8/. Other CMSes also seem to drop core support and leave implementing the authorization to 3rd party plugins.

And I can say from experience that configuring a Facebook app per site, waiting for Facebook to review it before it's live, making sure the access tokens are automatically renewed (even long-lived tokens can expire), etc. is way too much work for having oEmbeds work. This is only gets worse when you need to consider GDPR/tracking laws when displaying the embedded HTML...

**Comment by ronaldbarendse** [comment]
Facebook posted a reminder yesterday on their [Facebook Developers blog](https://developers.facebook.com/blog/post/2020/10/14/required-migration-token-based-access-user-picture-oEmbed-endpoints/):
> We are also deprecating the existing Legacy API oEmbed endpoints for Facebook and Instagram on 10AM PDT on October 24, 2020, which will be replaced with new Graph API endpoints. **If developers don’t make this change and continue to attempt to call the existing oEmbed API, their requests will fail and developers will receive an error message instead.** These new endpoints will require client or app access tokens or ASID queries.
