### ISSUE TITLE
Sorting event not fired in ContentService

### ISSUE THREAD

**Issue by benjaminc** [umbraco/Umbraco-CMS#9157]
## Umbraco version

I am seeing this issue on Umbraco version: 8.7.0

The offending code can be seen at https://github.com/umbraco/Umbraco-CMS/blob/v8/contrib/src/Umbraco.Core/Services/Implement/ContentService.cs#L2359 where it references the Sorting event name, but actually passes in the Saving event handler.

Reproduction
------------

### Bug summary

When sorting content through the Umbraco back-office, it should first fire the Sorting event, then the Saving event, then the Saved event, and finally the Sorted event.  It instead fires the Saving event twice.

### Steps to reproduce

1. Create a Composer and Component that registers an event handler method for the ContentService.Sorting event and writes out a log message
2. Open the back-office and sort some nodes

### Expected result

There should be a log message written out that shows the sorting event fired.

### Actual result

No message is written

**Comment by patrickdemooij9** [comment]
Was still an issue in the latest contribution branch. I fixed it with this PR: https://github.com/umbraco/Umbraco-CMS/pull/9181

**Comment by nathanwoulfe** [comment]
Fixed in #9181 👍
