### ISSUE TITLE
Block List - default auto-select if only one block-type

### ISSUE THREAD

**Issue by danieljameswilliams** [umbraco/Umbraco-CMS#9158]
Just like feature for auto-selecting if only one type as seen in the Grid Layout. This should also be implemented in the new Block List.

![image](https://user-images.githubusercontent.com/4445229/95953919-ddda7a00-0dfa-11eb-8b76-7e5ef2b1fc10.png)
![image](https://user-images.githubusercontent.com/4445229/95953963-ed59c300-0dfa-11eb-8e79-7acb1be2e6e4.png)

**Comment by nul800sebastiaan** [comment]
Thanks this duplicates https://github.com/umbraco/Umbraco-CMS/issues/8760 - make sure to follow the conversation there! 👍
