### ISSUE TITLE
Not being able to update color labels in Color Picker

### ISSUE THREAD

**Issue by patrickdemooij9** [umbraco/Umbraco-CMS#9176]
I am not quite sure when this happened, but in the latest contrib branch, you aren't able to change the label of the colors in the color picker anymore:
![image](https://user-images.githubusercontent.com/11466511/96220321-cf21cd80-0f88-11eb-9e84-1800fe715d42.png)

I took a look at the code and saw it's because it's using labelEnabled instead of vm.labelEnabled, so an easy fix. But I think you should also be able to edit the color after setting it. So, I'll take a look at what I can do.

**Comment by patrickdemooij9** [comment]
PR: https://github.com/umbraco/Umbraco-CMS/pull/9177

**Comment by nul800sebastiaan** [comment]
Oh no, this used to work in 8.7.0, so it's a regression for 8.8.0, we'll have to fix it for 8.8.1, but your PR looks good too, adding more functionality! 👍

**Comment by nul800sebastiaan** [comment]
Oh, I take it back, all good in 8.8.0! So it must have happened in the contrib branch at some point recently. Will mark this for 8.10.0 instead since we really should have it fixed before the final release!
