### ISSUE TITLE
V7 - User with multiple media start nodes can't pick media

### ISSUE THREAD

**Issue by dawoe** [umbraco/Umbraco-CMS#9178]
When a user has multiple start nodes, that are not in the root of the media folder, he can't pick media items using the default media picker.

## Umbraco version

I am seeing this issue on Umbraco version: latest v7

Reproduction
------------

### Bug summary

We have a multi site solution where we have a media folder per site. These site media folders have several sub folders for grouping images, eg. headers, news pictures, etc....

Some user roles have a start node set to one of the subfolders of a site. When a user is in multiple roles and has multiple media start nodes he can't pick images using the media picker.

![media-issue-v7](https://user-images.githubusercontent.com/1193822/96228616-18c4e500-0f96-11eb-8b3c-fe60df592c0a.gif)

### Specifics

This issue only occurs when a user has multiple start nodes. When they only have one media startnode it works fine. It also checked V8 and I can not reproduce it there.

### Steps to reproduce

1. Create a site using latest v7 and use the default started kit
2. Create a folder in the media root 
3. Beneath that folder create 2 folders called "Blog" and "Products" and upload some photos in the folders
4. Create a user group called "Blog editors".
     - Give access to content and media sections
     - Set content start node to "Blog"
     - Set media start node to the blog folder created in step 3
     - Give the same permissions as the editors group
4. Create a user group called "Products editors".
     - Give access to content and media sections
     - Set content start node to "Products"
     - Set media start node to the product folder created in step 3
     - Give the same permissions as the editors group
5. Create a new user and assign the user to both the "Blog editors" and "Product editors" group
6. Create a new MediaPicker datatype which is configured as following
     - Pick multiple images = false
     - Pick Images only = true
     - Disable folder select = true
7. Add a new property to the product document type using the newly created datatype
8. Login to the backoffice with the new user and try to select a media item for the newly created property on a product item

### Expected result

User sees all his start nodes when using the media picker.

### Actual result

User sees a empty media picker

**Comment by dawoe** [comment]
Hi @nul800sebastiaan 

Why is this postponed another release. I got a gold partner support ticket that this one would be in the next v7 patch release. We are waiting for this one for a while now.

dave

**Comment by nul800sebastiaan** [comment]
Unfortunately this didn't get the proper attention it needed and we ran out of time to make it happen for v7, this is being closed along with the PR you made as we're moving our focus completely to v8 and v9. For a longer explanation please read the comment on PR #9178
