### ISSUE TITLE
Add support for accessibility checking to TinyMCE

### ISSUE THREAD

**Issue by RachBreeze** [umbraco/Umbraco-CMS#9196]
It would be really great if we could help content editors generate more accessible content.  TinyMCE has an accessibility plugin https://www.tiny.cloud/docs-4x/plugins/a11ychecker/ which can be added to TinyMCE 4.  In all honesty, I've struggled to track this plug in down.

I did make a start using a different plugin, here https://github.com/RachBreeze/Umbraco-CMS/tree/feature/v8/tmpa11ychecktinymce but got lost in dependencies.  Also, the project added doesn't use axe-core  (https://github.com/dequelabs/axe-core) which drives most accessibility checks.

My preference would be to add the TinyMCE4 plugin if we can please.  Thank you in advance

**Comment by nul800sebastiaan** [comment]
The plugin for v4 is nowhere to be found.. so I'm not sure how ethical this is, but I found a codepen with the plugin: https://codepen.io/tinymce/pen/NGegZK

Resolving to these file contents: [plugin.min.js.txt](https://github.com/umbraco/Umbraco-CMS/files/5397292/plugin.min.js.txt)

Then adding to the `tinyMceConfig.config` like so:

![image](https://user-images.githubusercontent.com/304656/96363645-f4a00a00-1135-11eb-93da-3421dd2feca5.png)

Results in me being able to check on the button: 

![image](https://user-images.githubusercontent.com/304656/96363661-fd90db80-1135-11eb-9980-6274ea7c8d7b.png)

However.. it doesn't appear in the toolbar.

What I was able to make work is enabling the menubar: 

![image](https://user-images.githubusercontent.com/304656/96363762-798b2380-1136-11eb-8093-b25b24a83358.png)

This does seem to work: 

![image](https://user-images.githubusercontent.com/304656/96363803-b525ed80-1136-11eb-85d2-da92fa7f8878.png)

However.. I cannot find information on the availability of the plugin, I can see that in v5 it is a paid addon, but that is not explicitly stated on the v4 version.

![image](https://user-images.githubusercontent.com/304656/96363824-dd155100-1136-11eb-965d-1bf598a864b8.png)

So this might be an okay usage, not sure. Someone will need to ask Tiny.

If it's okay, to use and distribute then we'll need to figure out why the button doesn't appear in the toolbar.

**Comment by bielu** [comment]
@nul800sebastiaan the accessibility plugin is part of their subscription for TinyMCE Enterprise, it mean you will probably will be working against the licence of that plugin. (it is also point in v4):
![image](https://user-images.githubusercontent.com/2244074/96364738-f072ed00-1133-11eb-9bfb-ed7aade3f16c.png)

**Comment by RachBreeze** [comment]
Hi @nul800sebastiaan and @bielu 

Thank you both for looking, I thought it was just me missing something in Tiny's docs.

I've reached out to Tiny for clarification

**Comment by RachBreeze** [comment]
Hi just a quick update on this I've spoken to Tiny and we definitely can't use the CodePen version @nul800sebastiaan.  The team there are going to check if its feasible to use a version for TinyMCE 4

**Comment by RachBreeze** [comment]
Hi
I'm closing this as Tiny requires the accessibility checker to be licenced under a paid for licence
