### ISSUE TITLE
Examine: cannot index queue items, the index is currently locked

### ISSUE THREAD

**Issue by skartknet** [umbraco/Umbraco-CMS#9214]
We are having issues with the Examine indexes not rebuilding and failing with a 'Cannot index queue items, the index is currently locked' error.

There are also some other errors in the log like:

```
Lucene.Net.Store.LockObtainFailedException: Lock obtain timed out: SimpleFSLock@D:\home\site\wwwroot\App_Data\TEMP\ExamineIndexes\External\write.lock
   at Lucene.Net.Store.Lock.Obtain(Int64 lockWaitTimeout) in d:\Lucene.Net\FullRepo\trunk\src\core\Store\Lock.cs:line 97
```

## Umbraco version

We are using version 8.8

Reproduction
------------

### Bug summary

After some random time (we haven't really found the cause) Examine indexes fail to sync with a 'Cannot index queue items, the index is currently locked' error.

### Specifics

We are using the recommended configuration for WebApps and using 'SyncTempEnvDirectoryFactory' as the 'LuceneDirectoryFactory'.

To currently avoid the problem we are using 'TempEnvDirectoryFactory ' as suggested [here](https://our.umbraco.com/forum/using-umbraco-and-getting-started/90867-examine-lock-error-brings-down-azure-site)

We are running the site as load-balanced so we have a Master and a Slave webapp. The index doesn't fail if we keep the public webapp with only one instance. As soon as we scale out the app we start getting lock issues. In our case, we scaled out to 5 instances.

If we navigate to the Examine Management section in the backoffice we also get an error and the dashboard with the indexes is not displayed.

### Steps to reproduce

We haven't found a cause for when the index starts failing. If we restart the app they work again for some time.

### Expected result

We should be able to use 'SyncTempEnvDirectoryFactory'.

### Actual result

We get lock issues if we use 'SyncTempEnvDirectoryFactory' on a scaled out webapp.

**Comment by Shazwazza** [comment]
>  The index doesn't fail if we keep the public webapp with only one instance. As soon as we scale out the app we start getting lock issues. In our case, we scaled out to 5 instances.

For scaling out your read-only web app (you cannot scale your master web app), you must only use TempEnvDirectoryFactory. 

This is documented here https://our.umbraco.com/documentation/Getting-Started/Setup/Server-Setup/Load-Balancing/azure-web-apps#luceneexamine-configuration

**Comment by skartknet** [comment]
Oh, thanks for that! How do you get to that doc? I'm wondering if the docs are wrongly linked.

**Comment by Shazwazza** [comment]
I agree, the load balancing / hosting docs need some help to make things a lot clearer but the link comes from here https://our.umbraco.com/documentation/Getting-Started/Setup/Server-Setup/Load-Balancing/#server-configuration
