### ISSUE TITLE
8.9RC: Invite user form doesn't allow saving the password

### ISSUE THREAD

**Issue by clausjensen** [umbraco/Umbraco-CMS#9217]
# Description
When using the invite user flow from the backoffice, the page allowing the invited user to set their password, does not work.

Getting error in console:
`The current scope requires a current form object (or ng-form) with a name assigned to it`

## Reproduction
------------
- Use the invite user flow.
- Click the link in the invite email.
- Try to set a password.

---
_This item has been added to our backlog [AB#8984](https://dev.azure.com/umbraco/243e7927-03b2-44e2-908f-d4ac7ea5daaa/_workitems/edit/8984)_

**Comment by Shazwazza** [comment]
Fixed in rev https://github.com/umbraco/Umbraco-CMS/commit/dce7076aabbd470666892a249486cbe3b480ca80

## Review

Test that the invite works and that the form to create a new password and submit a new avatar works.

**Comment by clausjensen** [comment]
Confirmed it works for both setting password and avatar 🎉
