### ISSUE TITLE
@Html.RenderUmbracoFormDependencies() does not put out complete JS code

### ISSUE THREAD

**Issue by brightspectrum-da-bomb** [umbraco/Umbraco-CMS#9223]
@Html.RenderUmbracoFormDependencies() does not write out the complete JS path in the <script> tag for 

## Umbraco version

I am seeing this issue on Umbraco version: 8.6.5

Reproduction
------------

### Bug summary
For the last <script> tag which is supposed to reference https://ajax.aspnetcdn.com/ajax/mvc/5.1/jquery.validate.unobtrusive.min.js instead it references https://ajax.aspnetcdn.com/ajax/mvc/5.1/jquery.validate.unobtrusive.min.j (notice no s at the end)

### Steps to reproduce

Place the @Html.RenderUmbracoFormDependencies() into the FORM.cshtml
Run the page and view the source

### Expected result

The proper JS file would be referenced without a error stating that it cannot be found. 

### Actual result

Developer Tools shows an error because it cannot find the file. Have to workaround it by adding the script tag manually.

**Comment by nul800sebastiaan** [comment]
Thanks, this is not a CMS issue, but a Forms issue and will be fixed in the upcoming Forms version 8.5.4: https://github.com/umbraco/Umbraco.Forms.Issues/issues/415
