### ISSUE TITLE
injected IContentService not update disctributed cache

### ISSUE THREAD

**Issue by yawkale** [umbraco/Umbraco-CMS#9224]
Backend Server1: connected to DB1 (master)
Front Server1+2: connected to DB1 (slave)
DB1:

IContentService injected by DI doen't update distributed cache

simple code create simple action for update page via api and check master and slave servers

**Bad:** - master updates, front doen't updates
var item = _contentService.GetById(2316);
item.SetValue("statisticsUpdateTime", DateTime.Now);
 _contentService.SaveAndPublish(item);

**Good** - master and slave udpated
var item = _contentService.GetById(2316);
item.SetValue("statisticsUpdateTime", DateTime.Now);
Current.Services.ContentService.SaveAndPublish(item);

## Umbraco version

I am seeing this issue on Umbraco version:  8.8.0

**Comment by soreng** [comment]
Hi @yawkale 

You should inject an IScopeProvider, and then wrap your code in a new scope

```
using (var scope = _scopeProvider.CreateScope())
{
    // ... now you can do your work
   scope.Complete(); // commit
}
```

Refer to the comments from Shannon here https://github.com/umbraco/Umbraco-CMS/issues/9164

**Comment by nul800sebastiaan** [comment]
Thanks @soreng - that is indeed what needs to be done here @yawkale ✔️
