### ISSUE TITLE
Segment properties on IContent

### ISSUE THREAD

**Issue by joepvtl** [umbraco/Umbraco-CMS#9228]
Hi,

I was wondering if there should also be EditedSegments/PublishedSegments properties on the IContent object? Since these properties do exist for cultures.

The reason I bring this up, is because I am working on a package where this could come in handy. And I think this could be a good addition to the Core project.

Let me know what you think!

-Joep

**Comment by dawoe** [comment]
Hi @joepvtl 

This is probably related to this issue as wel : #9147 

But this will introduce breaking changes on the IContent object.

Dave

**Comment by joepvtl** [comment]
Hey @dawoe ,

Yep, you are right. I feel like segmentation isn't really a done feature yet.
I hope HQ can shed more light on this.

I guess I will close this issue for now and keep track of yours 👍 

-Joep
