### ISSUE TITLE
BlockList items with Allow vary by culture not editable on multi-language site

### ISSUE THREAD

**Issue by rubbad** [umbraco/Umbraco-CMS#9232]
ElementTypes that has Allow vary by culture can't be edited when used in BlockList if more than one language is set up on the site.

## Umbraco version

I am seeing this issue on Umbraco version: 8.8.0, 8.9.0-rc

Reproduction
------------
### Specifics

Tried this in Chrome on Windows. In both a regular Umbraco site using 8.8.0 and one built from source on my local machine (8.9.0-rc).

### Steps to reproduce

* Activate more than one language on the site
* Add an ElementType with one/some properties, activate Allow vary by culture on ElementType
* Add a BlockList to a Page and allow the ElementType to be added to it
* Create a new Page and try to add an item to the BlockList and fill in its property

### Expected result
I'm expecting the properties to be editable. 

When trying to add the same ElementType to a NestedContent editor, the properties are editable as expected.

### Actual result
The property will not be editable (input field is locked) and the text "Inherited from" (with not language specified) is rendered.

See below for comparison between BlockList and NestedContent

![Result](https://i.imgur.com/KTvflzG.png)

**Comment by kjac** [comment]
Hi @rubbad,

I believe you need to set culture variance on the Block List property and *not* on the Element Type. In fact I would strongly advise against letting your Element Type vary by culture.

**Comment by nul800sebastiaan** [comment]
Yes, @kjac is correct. At this point you can only vary the whole blocklist editor in culture, not just parts of it. It is a feature we want to have in the future, but it's not something we're working on any time soon.

It could be helpful that copy/pasting in the block editor works across culture variants works as well.
