### ISSUE TITLE
V8 Bug, If a property where nested content is used has a value that isn't json... the content editor breaks...

### ISSUE THREAD

**Issue by TimGeyssens** [umbraco/Umbraco-CMS#9235]
Say you are working on a site, you first have a multi media picker, that stored the media ids... then switch this to a nested content since you need more then just an image...

Data stored is media ids but when changing to nested content it expects json... tries to DeserializeObject but fails... (leaving the editor with a error message and an non working content editor)...

 var rowValues = JsonConvert.DeserializeObject<List<NestedContentRowValue>>(propertyValue.ToString());

**Comment by TimGeyssens** [comment]
Fixed in pr #9236

**Comment by nathanwoulfe** [comment]
Thanks @TimGeyssens will take a look at the PR 👍

**Comment by TimGeyssens** [comment]
Thanks, pretty simple stuff... but just had this error on a site where we migrated from a media picker to nested content...
