### ISSUE TITLE
MultiUrlPicker with invalid label

### ISSUE THREAD

**Issue by patrickdemooij9** [umbraco/Umbraco-CMS#9238]
The Multi Url Picker in 8.8 seems to have an invalid label connected to it. Which makes it so it'll look like this:
![image](https://user-images.githubusercontent.com/11466511/96703462-27930980-1393-11eb-9c60-173f806b9744.png)

I don't know if this is also happening in 8.7. It wasn't happening on 8.6.

How to reproduce:

- Create a new data type 'Multi Url Picker' with a maximum.
- Add the data type to a page and check it out.

Judging from the changes made, it seems like every key was moved to the validation section except the addUpTo. Will fix this with an upcoming PR!

**Comment by patrickdemooij9** [comment]
PR: https://github.com/umbraco/Umbraco-CMS/pull/9239

**Comment by nathanwoulfe** [comment]
Thanks @patrickdemooij9, I'll take a look at the PR, should be all good though

**Comment by poornimanayar** [comment]
Fixed in #9239
