### ISSUE TITLE
property editor decimal does not behave as expected on step size =< 0 | and when minimum > maximum

### ISSUE THREAD

**Issue by renaa** [umbraco/Umbraco-CMS#9254]
### Bug summary

decimal step size less than or equal 0 makes it impossible to save content, the same is true if minimum value > maximum value

## Umbraco version

I am seeing this issue on Umbraco version: 8.8

Reproduction
------------

1. Create a new data type property editor:  Decimal 
1. set min and max values 
1. set step size: 0
1. add it to a document type
1. try to set it in content editor
1. save and watch it disappear

### Specifics

The buildt-in property editor; Decimal discards values that does not adhere to the maxvalue, step size and max value 
![image](https://user-images.githubusercontent.com/1050133/96920115-0a525e00-14ad-11eb-858f-56f0ffab3963.png)

here only 8, 8.5, 9, 9.5, and 10 would be possible to input in the content editor.
Other values are unset.

If the value is unset all decimal values between 8 and 10 are possible to input in the content editor.

When step size is zero or negative then no values are possible to input in the content editor.

I think that in this scenario it should rather be better to reset the value of **step size** in the type definition if its value is 0 or negative

The same is true when the minimum value is more than maximum. 

### ideas for solving

One could possibly reuse some of the logic that unsets the value in the content editor.
One could also check for if minimum > maximum and reset one or both of these if that is the case.

**Comment by bjarnef** [comment]
I noticed this as well where I needed to save X and Y coordinates between 0 and 1. When a specified step size e.g. 0.01 I couldn't save the data. For now I have leaved the step size blank in the configuration of the Decimal datatype.

**Comment by nathanwoulfe** [comment]
Hi @renaa and @bjarnef 

I've been fiddling with the editor, have a couple of questions:
 - how would a step size <= 0 be expected to work? I can't see how that would ever allow valid data
 - similar with min > max - I think that should be caught when setting config values so it never actually happens
 
I've tried with step = 0.5 and step = 0.01 on latest v8/contrib and it works fine - can save data so long as it matches the step size. 

Could we please verify this is still an issue on latest? That said, there's no UI feedback when the item is invalid - if I enter 1.5 when the max is 1, the value disappears on save - instead, the user should see feedback that the value is invalid and be able to fix it and re-save.

**Comment by bjarnef** [comment]
@nathanwoulfe in my case I have configurated the Decimal datatype instance like this.

![image](https://user-images.githubusercontent.com/2919859/97904836-5c16a600-1d41-11eb-85e8-13165f5bc1aa.png)

It seems I can save values like 0, 0.1, 0.2, ...., 1  ... but not a value like 0.01

The step size is used for the step attribute on the numeric input.

![image](https://user-images.githubusercontent.com/2919859/97905206-ea8b2780-1d41-11eb-8984-fd5888fbb599.png)

but this shouldn't prevent saving a value like 0.01, 0.05, etc. right?

**Comment by bjarnef** [comment]
![a9YVhDc3gN](https://user-images.githubusercontent.com/2919859/97908766-6dfb4780-1d47-11eb-96d4-08166f9983d6.gif)

**Comment by bjarnef** [comment]
It seems it might be an issue with `fix-number` directive added to the numeric input.
https://github.com/umbraco/Umbraco-CMS/blob/v8/contrib/src/Umbraco.Web.UI.Client/src/views/propertyeditors/decimal/decimal.html#L12

When using 2+ decimals `model.value` seems to return null or empty.

![jBmp9byCS4](https://user-images.githubusercontent.com/2919859/97909159-0eea0280-1d48-11eb-84c0-572fe90c9708.gif)

**Comment by bjarnef** [comment]
Okay, it seems when `<input type="number" />` have e.g. `step="0.1"` only values like `0, 0.1, 0.2, 0.3` etc is allowed but not values like `0.01` and `0.05`.

It would be great if this could have some validation. At the moment you the property editor save the property with an empty value (at least when not mandatory).

**Comment by nul800sebastiaan** [comment]
Fixed in https://github.com/umbraco/Umbraco-CMS/pull/9334
