### ISSUE TITLE
Password Automatically Reset Upon Save

### ISSUE THREAD

**Issue by Agrejus** [umbraco/Umbraco-CMS#9278]
A brief description of the issue goes here.

Upon saving a member in the backoffice, the password will automatically get reset on the second save.  Even if no changes are made to a member and save is pressed, the password will automatically be reset. 

## Umbraco version

I am seeing this issue on Umbraco version: 7.15.3 assembly: 1.0.7180.24662

Reproduction
------------

If you're filing a bug, please describe how to reproduce it. Include as much
relevant information as possible, such as:

[screen-capture.zip](https://github.com/umbraco/Umbraco-CMS/files/5440150/screen-capture.zip)

Attached is a video reproducing the issue

### Bug summary

When opening a member in the back office, on the second save, the password will automatically be reset.  Even if nothing changes and someone saves a member, and then saves them again the password will automatically reset.

### Specifics

Version: 7.15.3 assembly: 1.0.7180.24662
Browser: Chrome 86.0.4240.111 (Official Build) (64-bit)
Have not Tested in other browsers

### Steps to reproduce

Edit the Member Type to add a custom section.  In our case we added a custom section (tab) called IP Address Management

![image](https://user-images.githubusercontent.com/5512999/97199251-cf3a7e00-177d-11eb-8b87-1f1487149146.png)

Below is the Secure IP Addresses nested content Data Type:

![image](https://user-images.githubusercontent.com/5512999/97199512-145eb000-177e-11eb-926c-7a3db135f688.png)

Below is the Secure IP Address Doc Type:

![image](https://user-images.githubusercontent.com/5512999/97199654-3eb06d80-177e-11eb-9f75-00147d547a4c.png)

We also edited the generic properties of MemberType and added a field called CustomerId:

![image](https://user-images.githubusercontent.com/5512999/97199366-eed1a680-177d-11eb-8519-d5c7456359a8.png)

All Members are being created programatically via the IMemberService.  IsApproved and IsLockedOut are both true when creating a member.  We are creating a member using the CreateMemberMethod:  Below is a sample request

```
public string Register(IMemberService memberService)
{
	var name = "Test Name";
	var member = memberService.CreateMember("sample@email.com", "sample@email.com", name, "Member");

	member.IsApproved = true;
	member.IsLockedOut = true;

        // This is our custom field we added to Properties tab
	member.SetValue("CustomerId", customerContact.CustomerId.ToString());
	memberService.Save(member);
}
```

### Expected result

Expect password not to automatically be reset.

### Actual result

Password is automatically being reset when no changes are made

**Comment by nul800sebastiaan** [comment]
Thanks for the in-depth report @Agrejus - this problem was fixed in v7.15.5 and I would encourage you to upgrade to the latest v7 which is 7.15.6 - https://our.umbraco.com/download/releases/7156
