### ISSUE TITLE
buttons_saveAndPreview missing translation

### ISSUE THREAD

**Issue by stefankip** [umbraco/Umbraco-CMS#9293]
In v8.8 the edit view got changed and the key `buttons_saveAndPreview` is now used for the label on the preview button. But it's not included in the translation files.

https://github.com/umbraco/Umbraco-CMS/blob/2d931877bebef333928d9423e59f1822f0524ae8/src/Umbraco.Web.UI.Client/src/views/components/content/edit.html#L51

**Comment by nathanwoulfe** [comment]
Hi @stefankip, I've checked all the lang files in /umbraco/config/lang, all have `saveAndPreview` in the `buttons` section...

eg https://github.com/umbraco/Umbraco-CMS/blob/e9e8a0354ddb36d12ebdecddf0569132dc96f4be/src/Umbraco.Web.UI/Umbraco/config/lang/de.xml#L134

Wonder if something went awry in an upgrade and the lang files didn't merge correctly?

**Comment by stefankip** [comment]
Right, I was searching for `buttons_saveAndPreview` in the language files :-D
My local environment did show the translated text, but my umbraco cloud dev environment didn't, while the translation file does contain the `buttons\saveAndPreview` item.
Restarting the environment helped. Sorry for bothering!

**Comment by stefankip** [comment]
Hmm, I did encounter another text which isn't getting translated (`general_addUpTo`):
![image](https://user-images.githubusercontent.com/46313552/97542333-d99b8880-19c6-11eb-85d6-587873f11f93.png

Or should I create a new issue?
