### ISSUE TITLE
Ability to add granular members administration options

### ISSUE THREAD

**Issue by HTDL-Andrew** [umbraco/Umbraco-CMS#9297]
Currently you have to be an adminstrator to save and edit passwords for members. This is an area of the website / application clients often administer themselves, but without having full admin access cannot reset passwords or change passwords for their members. It would be great if you could set the administration of members to groups that do not require full administrator access.

**Comment by nathanwoulfe** [comment]
Hi @HTDL-Andrew, could this be resolved by creating a group (eg Member administrators) with access to the members section, then adding the required users to that group? That way you can grant access to the single section, without exposing the developer/admin-focused sections.

**Comment by nul800sebastiaan** [comment]
Ideally, none of your staff should ever have to know passwords, especially keeping GDPR in mind. A self-service password-reset functionality is what we recommend you implement for this.

An example from the Our Umbraco codebase is here (it's v7, but the code for v8 would be very similar): https://github.com/umbraco/OurUmbraco/blob/main/OurUmbraco/Our/Controllers/ResetPasswordController.cs

For questions around implementation, make sure to head to the forums where our friendly community can help you find the best solution for your requirements.
Make sure to head on over to https://our.umbraco.com and ask follow up questions there! 👍

**Comment by HTDL-Andrew** [comment]
Thank you I'll take a look. Ideally, this functionality should exist in Umbraco at least as code samples in a partial snippet alongside the register partial and login partials already available. Most CMS's provide this functionality without having to build this in as an additional feature with many providing a button to email the user with a link to reset the password from the admin control panel, maybe this could be added in a future build.
