### ISSUE TITLE
Umbraco V8 RTE - Make menu bar sticky

### ISSUE THREAD

**Issue by mattbrailsford** [umbraco/Umbraco-CMS#9315]
I'm pretty sure prior to Umbraco v8, the rich text editor fields were independently scrollable, however in v8 I think this has been updated so that the input resizes based on the content within it. This is cool, but now if you create a lot of rich text content the editor toolbar goes off page and can be a pain to relocate. I know there is a new "distraction free" mode, but I'm not a fan of that approach as it can be buggy to get the toolbar to show when you need it.

A nice, simple alternative could be to just make the RTE toolbar sticky such that when you scroll the main editor window, the rte toolbar remains stuck just below the main menu bar. If you were to scroll beyond the RTE area, you could then just let it disapear and only re-appear when the RTE comes back into view.

I think this would be a much nicer UX and means the RTE toolbar is never out of reach.

**Comment by mattbrailsford** [comment]
Just doing a real simple quick test, even just adding these styles seems to make a big difference (might need testing more though).

````
.umb-rte .mce-top-part {
	position: sticky;
	top: 0;
}
````

![Edit_ Deploying a Vendr Store with Umbraco Deploy and uSync - Content - vendr net](https://user-images.githubusercontent.com/527305/97699043-6f0b4b00-1aa1-11eb-9c14-fa19cecce6fb.gif)

**Comment by mattbrailsford** [comment]
PR #9316

**Comment by nul800sebastiaan** [comment]
Fixed in https://github.com/umbraco/Umbraco-CMS/pull/9316
