### ISSUE TITLE
Feature Request: HasConvertedValue("propAlias")

### ISSUE THREAD

**Issue by TimGeyssens** [umbraco/Umbraco-CMS#9320]
We just had an issue where the HasValue("propAlias") was true but the value using value converters was empty... should there be an additional method to allow this check?

For example you have a content picker, id is stored, HasValue is true... picked content is unpublished... HasValue is still true, using the value results in an error since the prop value convertor checks if the content is published...

**Comment by stefankip** [comment]
You don't use models buildeR?

**Comment by TimGeyssens** [comment]
Ok might be due to the fact that this was an older v7 site

**Comment by TimGeyssens** [comment]
Closing since indeed when using models builder it isn't an issue anymore...
