### ISSUE TITLE
Cannot login to back office when app service is behind AzureApp Gateway

### ISSUE THREAD

**Issue by ketaanhshah** [umbraco/Umbraco-CMS#9343]
Hi All,
We are using Umbraco 8.7.0 version and we have hosted our site on Azure App Service and *No Authentication enabled*. Everything works fine here for the content site and the Master site (/Umbraco). We are able to navigate and edit the content and publish no issues. Now the Infra team has put App Gateway in place and configured the backend pool for it and the URL is also internal URL only so that the site is not accessible to public but only when you are on INTRANET (basically VPN'ed in the network, we use Zscalar).

The content site renders fine with the new URL (the internal URL) and everything works fine, but when we go to the /Umbraco Master site and enter the credentials to login to the Master site (Note we dont use any Easy Auth) we end up with a WHITE PAGE with nothing on it and opening up the DEVELOPER TOOLBAR on the browser shows following (401):

![image](https://user-images.githubusercontent.com/12475114/98116623-8c139580-1e76-11eb-9a5d-3a7a717602fa.png)

I came across this issue https://issues.umbraco.org/issue/U4-7213 here but we dont use EASY Auth infact our AUTH is disabled. Not sure why and what Umbraco is not liking here when it is put behind  App-Gateway here and only the Master site is throwing this error. If there is no App-Gateway and we access this App Service using the Azure public URL it works properly and no errors. 

I tried to look a little deeper and what I have found so far is when accessing thru the Public URL the cookies (specifically the UMB_Context) has all details like domain etc (Check screenshot1 below) and samething when I try to access from our Intranet App-Gateway enabled URL the domain is blank and also that UMB_Context cookie is missing from the next/subsquent calls
Screenshot1 below from public URL where everything works fine:

![image](https://user-images.githubusercontent.com/12475114/98119321-7607d400-1e7a-11eb-8a0d-c03ad6a4fb17.png)

Screenshot 2 with Internal URL where things are not working:
![image](https://user-images.githubusercontent.com/12475114/98119180-41941800-1e7a-11eb-9cd8-84f39ced6359.png)

Any help on this is appreciated as we are stuck with this issue and cant proceed to UAT.

Thank you

**Comment by nul800sebastiaan** [comment]
Does it work with Umbraco 8.8?

**Comment by ketaanhshah** [comment]
No @nul800sebastiaan we are using 8.7.0 (unfortunately the guidance from our team above is to use 8.7.0 for testing before we move to further up).

**Comment by nul800sebastiaan** [comment]
Alright, a bit misleading as I assumed you were on 8.9.0 since the title said `Latest Umbraco`  😄 

I don't have anyone who can look into this for a few weeks I'm afraid, I don't know if you have a configuration error or what is happening, I'm not familiar with this setup. I recommend you head to the forum at https://our.umbraco.com where our friendly community can help you find the best solution for your requirements.

If you have a support contract with us then make sure to reach out to support to expedite the process.

**Comment by ketaanhshah** [comment]
Sorry about the Version confusion @nul800sebastiaan my bad, sure I will check with our internal folks and also raise this question back to the umbraco forum and check if we have support contract and if we can raise this one thru official channel. Thank you.

**Comment by ketaanhshah** [comment]
@nul800sebastiaan I had a quick update to share .. what we have observed is in the POSTLogin call the SET-Cookie doesnt work for UMB_UCONTEXT when its behind the application Gateway since our URL is http:// and not https://. Basically the screenshot below:
![image](https://user-images.githubusercontent.com/12475114/98253464-0f052080-1f49-11eb-813b-b222a70e4a63.png)


Same thing works fine when we have public url https enabled and UMB_UContext cookie which is marked as SECURE works fine in the reponse (basically set cookie works) and the UMB_UCONTEXT is passed to subsequent requests:-

![image](https://user-images.githubusercontent.com/12475114/98253741-6efbc700-1f49-11eb-9ad1-90fca63e0926.png)


Not sure whats happening and why the UMB_UCONTEXT cookie is not set when on HTTP.

**Comment by ketaanhshah** [comment]
This issue was RESOLVED, basically for now what we have done on the App Gateway is on the Listeneres instead of listening on port 443 we have changed it to PORT 80 (HTTP Settings on the App Gateway) and then assigned the rule in application Gateway to the backend pool. For now the cookies are running on HTTP its all intranet so we can live with it. Plan for future is to get a certificate done for the intranet domain and apply that and then use the Listeners on 443 as planned. So this issue was with the App Gateway settings on Azure and not with Umbraco. We can close this issue here.
