### ISSUE TITLE
Can't login to another account after logout

### ISSUE THREAD

**Issue by mPieczka** [umbraco/Umbraco-CMS#9344]
Hi,

When I create a new user with lower permissions than my account and logout, I can't login to the newly created account. After passing login credentials to form I'm redirected to the login page. After clearing browser data by clicking ctrl+f5, I can log.

## Umbraco version

I see this issue on Umbraco versions: 8.8, 8.8.1 and my colleague updated 8.8 to 8.9, and it still exists.

Reproduction
------------

### Bug summary

Can't log to newly created account.

### Specifics

It happens in firefox and chrome. I didn't check other browsers. No error occurs during this process. Gif below shows how it looks like. Umbraco logs inform that "User: test@account.co.uk logged in from IP address 127.0.0.1". Console Log 

![image](https://user-images.githubusercontent.com/26299040/98125146-65744f80-1eb4-11eb-9740-ef48f61a05ac.png)

![GNR1HJJmjf](https://user-images.githubusercontent.com/26299040/98121628-d7966580-1eaf-11eb-98ec-ba8e48c5e99c.gif)

### Steps to reproduce

1. Create new empty visual studio c# web project, and install umbraco via nuget.
2, Run the project and got through installation process.
3. Log in as admin
4. Go to user tab and add a user with the editors role
5. Logout
6. Try to login to newly created account

### Expected result

After logout i can login without clearing browser data.

### Actual result

After logout i can't login unless i click ctrl + f5.

**Comment by nul800sebastiaan** [comment]
It's because you were previously logged into the users section, when you log out Umbraco it expects to log you back in with the same user so it preserves where you were. The new user doesn't have access to the users section so when you try to log in, it will try to open the users section and it's not allowed. 

Not something we intend to fix, sorry 😃
