### ISSUE TITLE
Enable serving of static files if Umbraco fails to boot

### ISSUE THREAD

**Issue by JasonElkin** [umbraco/Umbraco-CMS#9345]
This is somewhere between a bug and a feature.

Currently, if Umbraco fails to boot then all requests for static files fail.

For example, if Umbraco fails to connect to a database, requests to `/some-static-file.html` or `/favicon.ico` will return an (ugly) error.

### It would be good if we could serve static files in the event of a failed boot because...

Sometimes we need to add static HTML files (or similar) to our sites for verification of things like SSL certificates, webmaster tools etc. It doesn't seem reasonable that a failed boot should stop these from working.

It's not unusual to have static assets being served that are not dependant on Umbraco itself. e.g. `/some-iframe.html` `/static-microsite/` etc. Currently these don't work if Umbraco fails to boot.

It would enable us to show custom error pages in the event of a failed boot.

### There are other solutions to these problems but...

most of them require some kind of separate app or are quite convoluted. Simply serving static files would mean they will "just work".

It doesn't seem reasonable that Umbraco should have to have booted before we can serve a `robots.txt` file.

### I'm happy to take a look...

But I'm not entirely sure where to start so could use some pointers. I wonder if simply having a list of paths that are ignored by the UmbracoModule (similar to how ReservedPaths in appSettings are used) would be enough.

**Comment by nul800sebastiaan** [comment]
I just don't think that's possible, but we're open for suggestions. 😄 Let us know what your investigation results in. 

Please don't spend too much time on it though, I need to talk to some people to see if this idea is even feasible or if we don't want to do that.

**Comment by JasonElkin** [comment]
Thanks @nul800sebastiaan, now there's a red rag to a bull 😊

I'm hoping it could be a case of simply not throwing the exception [here](https://github.com/umbraco/Umbraco-CMS/blob/2bfef741914297c802bc6c77cc48780d7534f920/src/Umbraco.Web/UmbracoInjectedModule.cs#L369) for _every_ request.

Once Umbraco has booted [some checks are already performed on the URL ](https://github.com/umbraco/Umbraco-CMS/blob/2bfef741914297c802bc6c77cc48780d7534f920/src/Umbraco.Web/UmbracoInjectedModule.cs#L63) so I'm hoping it would be as simple as performing similar checks and then conditionally throwing the BootFailedException.

**Comment by JasonElkin** [comment]
I've just noticed 89a001f73f5063f87968cb323a17c31ac8ae4f82 from @rasmusjp 

I'd started doing something similar as a first step to solving this so it could now be really easy to implement.

I'm thinking that the simplest solution would be to have an interface along the lines of the below injected into the UmbracoInjectedModule. Default implementation would just return `true`.

```
public interface IBootFailedRequestPolicy
{
  bool ShouldThrow(HttpContext http);
}
```
Custom implementations can then be injected (hooray for DI) and perform any logic we might need and and simply return false to prevent the exception being [thrown here](https://github.com/umbraco/Umbraco-CMS/blob/89a001f73f5063f87968cb323a17c31ac8ae4f82/src/Umbraco.Web/UmbracoInjectedModule.cs#L367).

**Comment by rasmusjp** [comment]
Hi @JasonElkin 

My PR does indeed allow for static files being served if a `BootFailedException` is thrown, so I think it inadvertently fixes this issue? 

Unfortunately I don't think registering an interface in the DI container would work as the boot failed most likely would happen before the DI container is ready.

Is there any reason you want to make it conditional? And not just serve static files all the time even if there's an error?

**Comment by JasonElkin** [comment]
@rasmusjp Ah yes, the point is the boot actually failed 🤦‍♂️

I _think_ that solves the main thrust of the issue. I've got a project at the moment that has a few edge cases that I thought would need some conditional logic to make work so I'll check out your branch see.

**Comment by rasmusjp** [comment]
@JasonElkin that make sense :) 

My PR should allow all static files to be shown. It shows a custom error page if `debug=false` in web.config otherwise it shows the exception. The custom error page can be overwritten with a html page if needed, see the second part of the description on the PR https://github.com/umbraco/Umbraco-CMS/pull/9531
