### ISSUE TITLE
High CPU usage during Examine indexing which takes 16h to complete

### ISSUE THREAD

**Issue by martin-rhodes** [umbraco/Umbraco-CMS#9348]
When examine indexes are created against a site with many Public Access protected nodes (and these protected nodes have many member roles assigned to them), the indexing process takes an extremely long time (16h for 1000 protected nodes on a P1v2:1 Azure App Service Plan).

## Umbraco version

I am seeing this issue on Umbraco version: 8.8

Reproduction
------------

I have a site with 4000 content nodes, of which around 1000 are protected by public access restrictions. The protected nodes have up to 10 different member roles assigned to them. When starting the site up with no ExamineIndexes folder, or when explicitly rebuilding the indexes, indexing lasts a very long time (16h!) and uses up a constant minimum of 50% CPU during this time, significantly slowing down the website and backoffice.

### Bug summary

Umbraco 8.8 has an issue when indexing many protected nodes that have many member roles associated with them.

I have actually investigated this problem against Umbraco 8.8 source, and using CPU profiling, narrowed it down to the `PerformDeepClone` method of `PublicAccessEntry.cs`, specifically the line:

`cloneEntity._ruleCollection.CollectionChanged -= _ruleCollection_CollectionChanged;`

When removing the public access entries from all nodes, the site indexes in matter of seconds to minutes. Likewise, when using a Custom UmbracoIndexConfig as detailed [here](https://our.umbraco.com/Documentation/Reference/Searching/Examine/indexing/#changing-ivaluesetvalidator) and setting supportProtectedContent to true in the following override, the indexing also finishes very quickly.

`IContentValueSetValidator IUmbracoIndexConfig.GetPublishedContentValueSetValidator() => new ContentValueSetValidator(true, true, PublicAccessService);`

This bypasses the offending block of code (as no checks are carried out to see if a node is protected) and is our current workaround for this issue.

### Steps to reproduce

- Create a site with many protected nodes, with many member roles set against each protected node (using the public access API)
- Index the site with Examine

### Expected result

The indexing takes a few minutes to finish

### Actual result

The indexing takes many, many hours (16h for 1000 protected nodes)

---
_This item has been added to our backlog [AB#9890](https://dev.azure.com/umbraco/243e7927-03b2-44e2-908f-d4ac7ea5daaa/_workitems/edit/9890)_

**Comment by nul800sebastiaan** [comment]
Hmm, sounds like it could be related to this change in v8.8 - https://github.com/umbraco/Umbraco-CMS/pull/7596 

We'll need to investigate.

**Comment by tobimax** [comment]
Hi,

We are suffering from a similar problem and have a setup similar to Martin with about 4,500 content nodes. Membership access is used extensively. 

We have used **umbraco/backoffice/UmbracoTrees/ApplicationTree/GetApplicationTrees?application=content&tree=&use=main** as the reproduceable behavior, but I'm sure it happens on any node that is fetched through `PerformDeepClone `

First start-up the GetApplicationTrees takes .5 seconds. Every subsequent request adds approx. .5 seconds to the request until the process is taking minutes and the site goes down, totally unreposnsive. We have to stop/start the application service (azure) to restore functionality. As you can imaging our client is not too happy about this.

We do not have any public facing pages as they are all behind membership authentication, and I don't think we are suffering with any Examine Index Rebuilds. 

We can reproduce this on 8.10.0 locally and in Azure. We need a a fix or a workaround as soon as possible. I'm happy to help anyone test this out and provide any traces or test data if that would be useful.

Thanks 

Toby

**Comment by Shazwazza** [comment]
> the indexing process takes an extremely long time (16h for 1000 protected nodes on a P1v2:1 Azure App Service Plan)

yikes. And thanks for the investigation work that will be helpful in resolving this.

> Hmm, sounds like it could be related to this change in v8.8 - #7596

I don't think it's related

@tobimax Your issue is a different issue than this one. I would recommend opening up a different issue with steps to replicate.

**Comment by tobimax** [comment]
Hi Shannon,

Would you still like me to open a new issue. This is hard to replicate as you need a complex set of externally protected nodes to see this working.

We migrated from v7 to v8 and it was fine in v7 so it's definitely related to changes in v8 behavior.

At the moment we are having to restart the clients app every few hours, it's not ideal and they are getting a bit frustrated. Any quick workarounds or suggestions would be most welcome.

Thanks

Toby

**Comment by Shazwazza** [comment]
@tobimax not yet, I've confirmed an issue which is very much the issue for all of this (along with another internal support ticket). I'll respond in details when investigation is done.

**Comment by Shazwazza** [comment]
This is fixed with this PR which contains a detailed report: https://github.com/umbraco/Umbraco-CMS/pull/9640

I'll discuss internally about how this gets rolled out.

**Comment by tobimax** [comment]
Thanks @Shazwazza  - you quick response is most appreciated.

**Comment by nul800sebastiaan** [comment]
This has been fixed with PR https://github.com/umbraco/Umbraco-CMS/pull/9640 and I've cherry picked this for all upcoming patch releases of 8.6 upwards. Additionally, this fix will be available in the upcoming v8.11.0 (of which the RC should be out later this week).

**Comment by martin-rhodes** [comment]
Awesome - good work team! 🥇

**Comment by nul800sebastiaan** [comment]
**Note:** This didn't make it into the 8.11.0-RC build but will be in the final build of 8.11.0.

**Comment by tobimax** [comment]
Hi, @nul800sebastiaan, 

Do you have an ETA for the 8.11 release? Is there a branch that the fix is committed on that we could try out?

Regards

Toby

**Comment by nul800sebastiaan** [comment]
@tobimax The release is scheduled for Thursday next week, the latest build, which is most likely the final build, can be found here in the "Zips" container: https://dev.azure.com/umbraco/Umbraco%20Cms/_build/results?buildId=55202&view=artifacts&pathAsName=false&type=publishedArtifacts
