### ISSUE TITLE
Can't register multiple trees in same tree group

### ISSUE THREAD

**Issue by callumbwhyte** [umbraco/Umbraco-CMS#9357]
There is supposedly 2 ways to register custom trees:

- Creating a controller that inherits from `TreeController` and decorating it with the `[Tree(...)]` attribute - this is then type scanned and auto-registered

- Creating a controller that inherits from `TreeControllerBase` and registering the tree in a composer with `composition.Trees().AddTree()`

A [comment](https://github.com/umbraco/Umbraco-CMS/blob/v8/contrib/src/Umbraco.Web/Trees/TreeCollectionBuilder.cs#L24) on the latter method says "this is useful for ... a single tree controller for different tree aliases ... the tree controller cannot be decorated with the TreeAttribute".

However when using this method, with a shared tree controller, but more than 1 tree is registered within the same "tree group" in the same "section" this fails. A cast error is thrown as it is expected the tree will implement `TreeController` which it cannot in this case.

Tested on the latest 8.9.0, but looking at the code this likely applies to all versions of V8.

**Comment by glombek** [comment]
Fixed in #9358
