### ISSUE TITLE
Nested validation freezes browser

### ISSUE THREAD

**Issue by PerplexDaniel** [umbraco/Umbraco-CMS#9360]
When you have a property editor that allows nesting of some sort (e.g. NestedContent) with at least 1 mandatory property the browser tab will completely freeze when Saving/Publishing when there are validation messages to display.

This seems to be caused by [`collectAllFormErrorsRecursively`](https://github.com/umbraco/Umbraco-CMS/blob/v8/contrib/src/Umbraco.Web.UI.Client/src/common/services/angularhelper.service.js#L13) of the AngularHelper service. This one is executed an insane amount of times (100K+, but I killed the tab at that point so it will be much more). It seems to increase exponentially when nesting increases.

Demo where I increase nesting. All fine at first but gets slower each step. At level 4 it just hangs forever (probably depends on hardware). The UI also starts to slow down noticably at the step before that. There are no console errors. It's just calling that `collectAllFormErrorsRecursively` function way too many times -- without a result apparently.
![slow](https://user-images.githubusercontent.com/24297947/98520403-45f17400-2272-11eb-8b58-ef4bf62002a3.gif)

When I disable `collectAllFormErrorsRecursively` (by placing a `return` immediately at the start), it runs flawlessly however deep you nest and also does not seem to break anything. So what is this function even used for :-)
![fast](https://user-images.githubusercontent.com/24297947/98519844-9d431480-2271-11eb-885f-070e14832920.gif)

This was tested on a new installation of 8.9 with an empty site and only 2 doctypes (Home + Block, where Block is the doctype used in NestedContent).

## Umbraco version

I am seeing this issue on Umbraco version: 8.9.0

### Steps to reproduce

1. Create some simple Nested Content doctype with at least 1 mandatory property and a property referencing itself (to nest it).
2. Create a datatype for this Nested Content
3. Add this data type to some doctype.
4. Add some content and make sure to nest it a couple of times (4+)
5. Keep the mandatory properties empty
6. Publish
7. Observe hanging browser

### Expected result

Validation messages show within a reasonable time :)

### Actual result

Browser tab hangs and does not respond anymore.

**Comment by nul800sebastiaan** [comment]
Thanks @PerplexDaniel - not sure why that method was necessary, it looks like it was added here, I'll have to ask around: https://github.com/umbraco/Umbraco-CMS/pull/8339

**Comment by nul800sebastiaan** [comment]
This is fixed with PR https://github.com/umbraco/Umbraco-CMS/pull/9677 which will be available in patch releases for 8.7, 8.8, 8.9, 8.10 and in the final release of 8.11, all coming next week.
