### ISSUE TITLE
Backoffice tab switches despite an editor choosing to stay on the same page

### ISSUE THREAD

**Issue by Jverschoor** [umbraco/Umbraco-CMS#9371]
When editing content if an editor tries to switch tabs (f.e. from content to media) the editor gets a warning that unsaved changes may be lost. But despite the editor choosing to stay on the same page, the tab still switches

## Umbraco version
I am seeing this issue on Umbraco version: 8.9.0

Reproduction
------------

### Steps to reproduce

1. Edit content in the content tab
2. Click on the media tab without saving first
3. Confirm that you want to stay on the same page

### Expected result

Tab does not switch to media but stays in content

### Actual result

Tab switches to media

![image](https://user-images.githubusercontent.com/23473606/98681258-cc857e80-2362-11eb-9865-3e40a44ee210.png)
![image](https://user-images.githubusercontent.com/23473606/98681317-ddce8b00-2362-11eb-90ef-ef7324f7b815.png)

**Comment by nul800sebastiaan** [comment]
Thanks for the report @Jverschoor  - I am on 8.9.1 and can't reproduce this, so I'm assuming it's been fixed along the way!

![9371_1](https://user-images.githubusercontent.com/304656/98813970-4da54a00-2425-11eb-97f4-5ff1f71c97db.gif)
