### ISSUE TITLE
Cache is broken after upgrading to v8.9.1 ?

### ISSUE THREAD

**Issue by JoseMarcenaro** [umbraco/Umbraco-CMS#9378]
After upgrading three different websites from v8.6.4 to v8.9.0 and v8.9.1, I noticed that the site behaved erratically after the upgrade (lots of published content items were missing).
In every case the problem was solved by performing a Database Cache [Rebuild] followed by a Memory Cache [Reload].
So it's no big deal ... but I don't remember having to do that in previous upgrades, I always thought it was done automatically during the upgrade process.

Did something change in the upgrade process that may cause that behavior?

It happens both locally  (dev machines) and on Azure servers. We are not using the `IgnoreLocalDb` published snapshot option.

Thanks!

**Comment by nul800sebastiaan** [comment]
Thanks @JoseMarcenaro - we haven't changed anything in the upgrade process and can't think of anything that would cause the cache to change really. I'll have to assume for now that it was a fluke in your specific upgrade, I just tried an upgrade myself and that went well. I'll keep an eye out for other similar reports.

**Comment by vaags** [comment]
I also experienced this, when upgrading from 8.6.1 to 8.11.1. It was solved by rebuilding the cache, as described by OP.

**Comment by kimschurmann** [comment]
I also experienced this going from 8.5.5 to 8.11.1 - why not just wipe the caches as a part of the upgrade proces? Just to be sure...?
