### ISSUE TITLE
Nested Content in Single Item mode looks broken

### ISSUE THREAD

**Issue by skttl** [umbraco/Umbraco-CMS#9393]
## Umbraco version

I am seeing this issue on Umbraco version: 8.9.0

Either it lacks some padding, or the border should be removed.

### Steps to reproduce

Add Nested Content property in Single Item Mode (set min AND max items to 1)

### Expected result

Expected it to look better. I would suggest without the border.

### Actual result

![image](https://user-images.githubusercontent.com/3726467/99082188-1ae58800-25c4-11eb-8fd6-6caf2546d4a4.png)

**Comment by callumbwhyte** [comment]
As @skttl points out, I fixed this in #9384.

This applies to 8.7 and above, not just 8.9. I don't know what the patching policy is but I'd personally love to see this patched into all the affected versions... It's a shame to invest so much in great UX with block list etc and leave this glaring hole...

**Comment by nul800sebastiaan** [comment]
Fixed in https://github.com/umbraco/Umbraco-CMS/pull/9384 - will be available in patches for 8.7 onwards and for the upcoming 8.11 release. I'll move the labels to the PR instead.

**Comment by callumbwhyte** [comment]
Good stuff - really happy to see this being patched so far back too!
