### ISSUE TITLE
Preview only shows published changes, not saved changes

### ISSUE THREAD

**Issue by mikeallen222** [umbraco/Umbraco-CMS#9395]
Umbraco version: 8.9

The preview button is only showing the published version, no the saved version

Steps to reproduce
1) Create new node
2) Save and preview node -- preview will say the item can't be found
3) Publish node
4) Save and preview node -- now I see my new node
5) Update content in node
6) Save and preview node -- I still see my original published content, not the change
7) Publish node
8) Save and preview node -- Now I see my change from step 5

Expected result
Preview shows the latest SAVED content

Actual result
Preview only shows the latest PUBLISHED content

**Comment by nul800sebastiaan** [comment]
Hmmm, I don't have this problem in 8.9.1, so something fishy seems to be going on in your install somehow: 

![9395](https://user-images.githubusercontent.com/304656/99246513-b44fac80-2805-11eb-8e21-03143d4b4372.gif)

If you have more steps to reproduce this somehow. I'll be happy to re-open the issue but for now I must assume that it's isolated to your specific install.
