### ISSUE TITLE
Unpublish with descendants doesn't unpublish child nodes

### ISSUE THREAD

**Issue by ATaat** [umbraco/Umbraco-CMS#9399]
Hi,

We use Umbraco Heartcore and we noticed that when we want to UNpublish a node with childnodes, only that particular node is unpublished and the childnodes shows the message "This document is published but is not visible because the parent '_pagetitle_' is unpublished". This doesn't make sense in our opinion. Because you can't navigate to this page and you can't find these pages in the search result, because it's parent node is unpublished. So why is this node still published then?

Our assumption is that the functionality to UNpublish nodes will be the same as the "publish with descendants", the opposite way. So also a checkbox to give the editor the option to also unpublish the childnodes.

**Comment by nul800sebastiaan** [comment]
Thanks @ATaat - this is completely normal and a good thing. 

- When you later choose to publish with descendants and don't enable the checkbox for  `Include drafts: also publish unpublished content items.` we know which items were previously published and which items had a draft version. So when you publish with descendants, we do not publish the drafts that were waiting before. Also consider that people might accidentally unpublish a node, it would be a nightmare to figure out manually which descendants need to be published and which absolutely shouldn't be.
- Performance is key here, by only removing the descendants from the cache but not updating them in the database we gain a whole lot of performance especially when large numbers of descendants are involved.

While there is no need to, you're welcome to hook into the `Unpublished` eventhandler to forcibly unpublish all descendants, but now that it comes with the costs explained above.
