### ISSUE TITLE
Inherited Document Type properties missing

### ISSUE THREAD

**Issue by drpeck** [umbraco/Umbraco-CMS#9418]
Half of my document types which inherited from a parent document type were missing any inherited properties.

## Umbraco version

I am seeing this issue on Umbraco version: 8.9.1 (no upgrades)

Reproduction
------------

### Bug summary

With a fresh install I created a bunch of document types, most of which _inherited_ from a document type called Page. A few days later I noticed that only _half_ of my child document types showed the properties which were added to Page. Creating a new child document type would create a document type with the inherited properties. Not wishing to recreate some of the content, I investigated the DB where I found that the erroneous document types were missing records within `cmsContentType2ContentType`. Adding the required records in, the issue was resolved.

`umbracoNode` correctly had the parent relationship. Based on the node ids and timestamps, the issue appears to have happened twice with two chronological groups of document types all experiencing the same issue. However there were document types created correctly seconds before and after those periods of time. 

Here is where this report is going to be a rubbish, I don't have any ability to re-create the issue. Just form evidence of it's existence, prior to my SQL INSERTs. I can understand why this report my not be investigable, and you need to close it. I wanted to report it though in case others experience the same thing.

### Specifics

There were no error log entries from the time of the error.
The only plugin I had installed at the time was Vendr. I have subsequently installed uSync, which I suppose could have deleted the records in question.

**Comment by nul800sebastiaan** [comment]
Thanks @drpeck - Indeed it's difficult to investigate in this case, I would maybe suspect uSync in the first place doing something strange accidentally but I also don't want to make "unfounded accusations". It's indeed good to have these things reported though, it helps create awareness for when we see more of these things!

I'll close this for now indeed and keep fingers crossed that this was just an edge case/accident! 🤞
