### ISSUE TITLE
Backoffice UI - checkboxes on doctype compositions uncheck after selecting an item

### ISSUE THREAD

**Issue by Jay-umbr** [umbraco/Umbraco-CMS#9432]
Adding a composition to a doctype - the checkboxes become greyed out after selecting an item for a composition, so you cannot take it out unless you re-open the side panel.

## Umbraco version

I am seeing this issue on Umbraco version: .8.9.1

Reproduction
------------
Hope a video is OK.
https://drive.google.com/file/d/1idIlLDupKkt3jGKzwNk7r59EDGLJpylX/view?usp=sharing
Create two document types in the backoffice and try to use one as a composition on the other doctype.

This does NOT happen on a version 8.6, from what I tested

### Expected result

We add the item in the composition, and while it is added, the checkbox remains checked.

### Actual result

Once the item is added the checkbox is greyed out, and the item cannot be removed as quickly.

**Comment by JasonElkin** [comment]
Also seeing this after upgrading to 8.9.1.

![compositions bug](https://user-images.githubusercontent.com/7151793/100280916-da412380-2f60-11eb-8889-d0b6902ddd74.gif)

**Comment by marcemarc** [comment]
![CompositionGreysOutUnexpectedly](https://user-images.githubusercontent.com/260802/101657575-f7372580-3a3b-11eb-91c2-1ab4bc6ced98.gif)
Let me add this as a reminder to myself to check the issue list first before creating the video!

**Comment by nul800sebastiaan** [comment]
This has been fixed with PR https://github.com/umbraco/Umbraco-CMS/pull/9644 and I've cherry picked this for all upcoming patch releases of 8.9 upwards. Additionally, this fix will be available in the upcoming v8.11.0 (of which the RC should be out later this week).

**Comment by nul800sebastiaan** [comment]
*Note:* This didn't make it into the 8.11.0-RC build but will be in the final build of 8.11.0.
