### ISSUE TITLE
Block List Datatype Editor - nullcheck error

### ISSUE THREAD

**Issue by ault** [umbraco/Umbraco-CMS#9434]
If a doctype element is added to a blocklist, then the doctype is deleted before being removed from the blocklist, it cannot be deleted from the blocklist datatype and new doctypes cannot be added. It also seems to create issues in content anywhere that blocklist is in use.

## Umbraco version

I am seeing this issue on Umbraco version: 8.7

![Screenshot 2020-11-23 120658](https://user-images.githubusercontent.com/7056441/99960910-d5784600-2d8d-11eb-8525-85693fbc3698.png)

## Results

If a doctype no longer exists, it does not correctly populate the blocklist data (see screenshot). The trashcan does not work, and you cannot add any further doctypes to the blocklist.

This is the least of your worries, as current instances of the blocklist in your content cannot be edited. (Sorry, no screenshot.)

## Dirty-fix
In order to get back up and running, I edited the json in umbracoDataType table.  This worked as expected and no further issues were experienced.  (I have not had the time to replicate the issue.)

**Comment by xanderekpl** [comment]
this looks like fixed in https://github.com/umbraco/Umbraco-CMS/issues/8911

tested in version 8.10rc but i think this PR 
https://github.com/umbraco/Umbraco-CMS/pull/8980 

was merged into 8.7.1
https://our.umbraco.com/download/releases/871

**Comment by nul800sebastiaan** [comment]
Thanks! Yep indeed this should be fixed in 8.7.1 and later releases.
