### ISSUE TITLE
Bring back Tabs to V8

### ISSUE THREAD

**Issue by TimGeyssens** [umbraco/Umbraco-CMS#9442]
Not gonna go in the whole history but here is the forum thread: https://our.umbraco.com/forum/umbraco-8/93641-discussion-about-tabs

V8 had no more tabs, but a lot of folks are missing that so there is of course an official recommended package: https://our.umbraco.com/packages/backoffice-extensions/matryoshka-tabs-for-umbraco-8/

But since it is not core it can also break during upgrades like mentioned here https://twitter.com/rsoeteman/status/1330890145097248768

So at last HQ has confirmed to bring back tabs: https://twitter.com/Filipbech/status/1330909426883170306

Already a couple of good ideas floating on twitter, should this be a setting on entire backend/ single doctype level or should the content editor decide how he want's to see the groups/tabs?

**Comment by nathanwoulfe** [comment]
It should be all those options- set the global default, set the default on a given doctype, but still allow the editor to toggle between tabs/groups. Different minds work in different ways, so should accommodate both UI variants.

**Comment by TimGeyssens** [comment]
not sure if you give the editor the toggle option you need to set a default?

**Comment by nathanwoulfe** [comment]
Still needs a default set somewhere, so might as well make that configurable too - sometimes it will make sense to default to groups rather than tabs, but sometimes too editors aren't sensible and will want the alternate UI

**Comment by TimGeyssens** [comment]
Sure makes sense :) I'm guessing the folks at HQ will have an internal talk about the best approach ... but I agree "Different minds work in different ways, so should accommodate both UI variants."

**Comment by skttl** [comment]
Just to be clear, the Matryoshka bug is not a result of an Umbraco upgrade, but me not testing things good enough.

For tabs in core, yes that would be good. Not sure if the toggle for editors is a good idea (why not let them toggle all sorts of stuff then?).

If we could have a settings doctype attached to a content doc type (like in block list), that would be great, and minimize most tab usecases IMO.

**Comment by mattbrailsford** [comment]
I don’t think toggling between tabs and groups would be that useful, I think a better, more useful feature would be tabs AND groups. Groups can then be thought of as fieldsets grouping related fields, but tabs could be used to group themes of fields / fieldsets. I probably mentioned this on the forum post though 😂

**Comment by c9mbundy** [comment]
@mattbrailsford I agree, and think that the way Matryoshka implements 'faux groups' within tabs is pretty close to the right presentation, if not necessarily the optimal implementation. Being able to organize fields into tabs and groups also opens the door to easier role-based access control, by simply hiding tabs/groups not needed or not wanted by a role. Not so sure about allowing editors to change the UI mode, unless this is something that the dev can manage - i.e. allow users to enable/disable tabs based on conditions that a dev might test - e.g. Tabs can be difficult to work with on small devices such as mobile phones.

**Comment by filipbech** [comment]
I must say I love the enthusiasm for tabs :-D 

Let me just clarify, that no work has been planned, so tabs isn't coming just yet! Don't think of my personal tweets as a public roadmap for Umbraco! 

What has changed since the discussion started, is that we have learnt that this is an issue that keeps coming up, and I believe that calls for us to take a fresh look at it. I have started those talks internally and I will post back what we come up with! 

But keep ideas, concerns etc coming...

**Comment by DanDiplo** [comment]
I'm with @mattbrailsford Tabs for separating distinct areas of a document type and, within those, groups to separate logically distinct fields. So both.

**Comment by TimGeyssens** [comment]
sound good @filipbech yes a fresh take without stubbornness would be ace! Keep it up!

**Comment by FransdeJong** [comment]
I think the title of this issue should be changed to "Bring back tabs to V8".
I do love the fact that there is movement at Umbraco HQ about this topic but to say it's happening sends out the wrong signal in my opinion.

I don't expect this to happen before Umbraco core/9. Don't get me wrong that's not a bad thing but the title will set expectations way to high.

**Comment by TimGeyssens** [comment]
@filipbech has spoken, this is the way!

**Comment by FransdeJong** [comment]
... _Let me just clarify, that no work has been planned, so tabs isn't coming just yet! ...

**Comment by TimGeyssens** [comment]
@FransdeJong details details details...
