### ISSUE TITLE
Add event to check for block data changes

### ISSUE THREAD

**Issue by bjarnef** [umbraco/Umbraco-CMS#9453]
When using custom views for block list editors, e.g. to get at nicer view for blocks using `Udi` properties, it isn't easy to know when the value of the block property changes, when selecting a different value or clearing the picked value in for example MNTP, Content Picker, Media Picker, etc.

It would be great to have a event here, when submitting the data from block list editor overlay or when the data changes in inline mode.

A workaround for now is to watch the parent scope and check if there is a change in the specific property value in block data.

```javascript
angular.module("umbraco").controller("My.Custom.BlockViewController", function ($scope, entityResource) {

    var entryUdi = $scope.block.data.myProperty;

    loadEntry(entryUdi);

    $scope.$watch("block.data", function (newValue, oldValue) {
        if (newValue !== oldValue) {
            console.log("watch parent block data", newValue, oldValue);
            if (newValue.myProperty) {
                loadEntry(newValue.myProperty);
            }
            else {
                $scope.entry = null;
            }
        }
    }, true);

    function loadEntry(udi) {
        entityResource.getById(udi, "Document")
            .then(function (entity) {
                $scope.entry = entity;
            });
    }

});
```

Tested on Umbraco v8.9.0

**Comment by bjarnef** [comment]
@warrenbuckley I guess you used a `watch` as well in your demo here to check if the images changed and in that case update the images in the custom view - or didn't the images simulate a "live" update?
https://twitter.com/warrenbuckley/status/1281531692193394690?lang=en

//cc @nielslyngsoe

**Comment by bjarnef** [comment]
I noticed we can use the following to watch a specific property or watch `block.data` which could be useful if using multiple `Udi`  properties in the custom view. However in this case v1 of `block.data` watch didn't work when submitting modal from overlay, where it needed the second parameter set to `true`.

```
$scope.$watch("block.data", function (newValue, oldValue) {
     console.log("block.data 1", newValue, oldValue);
});

$scope.$watch("block.data", function (newValue, oldValue) {
    console.log("block.data 2", newValue, oldValue);
}, true);

$scope.$watch("block.data.image", function (newValue, oldValue) {
     console.log("block.data.image", newValue, oldValue);
});
```

**Comment by bjarnef** [comment]
It should probably emit an event in the submit function here: https://github.com/umbraco/Umbraco-CMS/blob/v8/contrib/src/Umbraco.Web.UI.Client/src/views/propertyeditors/blocklist/umbBlockListPropertyEditor.component.js#L444-L460

so we can hook into this event to get the updated block data instead of using angular `$watch`.

```
scope.$emit("block.changed", { data: data, settings: settings });
```

```
$scope.$on("block.changed", onBlockChanged);

function onBlockChanged(event, args) {

    // Do something with updated block

}
```

**Comment by nielslyngsoe** [comment]
Using event is not a preferred approach as inner block editors would trigger such as well, performance-wise its much better to do specific watch. As your example here:

`$scope.$watch("block.data.image", function (newValue, oldValue) {
     console.log("block.data.image", newValue, oldValue);
});`

In this way, you would also be able to only update the data relevant to that property.

Performance performance performance, not a thing we have talked so much about. But Nested Content didn't perform well when there were more than 1000 items, The Block Editor is able to handle way more, especially clear when having multiple nested editors. The performance of my tests first started to become a noticeable problem when the browser had trouble rendering the amount of HTML.

I'm closing this one, but any AngularJS Helpers or similar that helps setup such watch mechanism, are very welcome. Making it easier for developers to write custom views.
