### ISSUE TITLE
Rich text editor opens very slowly and slides down a bit after every click

### ISSUE THREAD

**Issue by deekoulos** [umbraco/Umbraco-CMS#9463]
Version 8.9.1

see screencast
![rte issue](https://user-images.githubusercontent.com/55948134/100466950-05975000-30d2-11eb-80e0-d3b817e30a85.gif)

**Comment by nul800sebastiaan** [comment]
Thanks @deekoulos, that's luckily not typical behavior for a clean install of 8.9.1. I would recommend you check installed packages or browser extensions. 😅
