### ISSUE TITLE
Broken layout for member group id

### ISSUE THREAD

**Issue by bjarnef** [umbraco/Umbraco-CMS#9466]
With the latest changes in `v8/contrib` branch it seeems the layout of id on member groups is broken compared to how it used to look like and not matching the layout in e.g. content and media.

![image](https://user-images.githubusercontent.com/2919859/100518534-5d958b80-3192-11eb-8ed2-9e52d9b5307b.png)

**Comment by bjarnef** [comment]
@nielslyngsoe I noticed you recently made some changes in the "info" group - not sure of some of those changes have affected this issue?

**Comment by bjarnef** [comment]
This is how it looks in v8.9.0

![image](https://user-images.githubusercontent.com/2919859/100552370-20f78c00-3287-11eb-970e-4a8de150b282.png)

**Comment by nielslyngsoe** [comment]
@bjarnef thanks for noticing. Member groups info page was not set up correctly, but that's corrected in this PR.
https://github.com/umbraco/Umbraco-CMS/pull/9469

**Comment by warrenbuckley** [comment]
Will be due in 8.10
