### ISSUE TITLE
Stuck in the installation

### ISSUE THREAD

**Issue by Lailatski** [umbraco/Umbraco-CMS#9473]
Hi!
I am completely new to both Umbraco and the project I'm asked to work on, so please bear with me.
The project was made in Umbraco 7.15.4 and I'm using Visual Studio 2019 to run it,

When I run the project in debug mode I get this:
![Schermafbeelding 2020-11-30 102515](https://user-images.githubusercontent.com/44963618/100591764-8171e200-32f6-11eb-9cc9-30c253ca5f78.png)

After some Googling I found it could be due to the database not existing yet, so I removed the reference from the web.config. The result is: 
![Schermafbeelding 2020-11-30 121925](https://user-images.githubusercontent.com/44963618/100604076-51cad600-3306-11eb-922a-2def23dd50c9.png)

I tried some potential fixes (removing temp folder, running in private mode.), but nothing has solved my issues thus far. I doubt that Umbraco is installed at this moment.

Does anyone know how to solve either issue and get Umbracro installed properly? Thanks!

**Comment by rustybox** [comment]
> so I removed the reference from the web.config

What did you do here exactly.

To restart with new db there's two settings that need to be updated in web.config

1. Set connection string back to an empty string
2. Set value of umbracoConfigurationStatus to empty string

```xml

    <appSettings>
        ...
        <add key="umbracoConfigurationStatus" value="" />
        ...
    </appSettings>

    <connectionStrings>
        <remove name="umbracoDbDSN" />
        <add name="umbracoDbDSN" connectionString="" providerName="System.Data.SqlClient" />
    </connectionStrings>


```

**Comment by Lailatski** [comment]
> 
> To restart with new db there's two settings that need to be updated in web.config
> 
> 2. Set value of umbracoConfigurationStatus to empty string
> 
> ```
>     <appSettings>
>         ...
>         <add key="umbracoConfigurationStatus" value="" />
>         ...
> ```
That's what did the job! I'd already set the connectionString to an empty string, but that didn't work. 
Thank you so much :).
