### ISSUE TITLE
Multi Url Picker translation text (general_addUpTo) missing

### ISSUE THREAD

**Issue by martinbrud** [umbraco/Umbraco-CMS#9475]
This text hasn´t been translated, see screenshot: https://i.imgur.com/5M4Woou.png 

## Umbraco version

I am seeing this issue on Umbraco version: 8.9.1

Reproduction
------------

If you're filing a bug, please describe how to reproduce it. Include as much
relevant information as possible, such as:

### Bug summary

- Go to a node that has a MNTP property

**Comment by martinbrud** [comment]
Solved by adding key '<key alias="addUpTo">Add up to</key>' to Umbraco\Config\Lang\en.xml:
`  <area alias="general">
    <key alias="about">About</key>
    <key alias="action">Action</key>
    <key alias="addUpTo">Add up to</key>`

**Comment by nul800sebastiaan** [comment]
Thanks this has been fixed for the upcoming v8.10. https://github.com/umbraco/Umbraco-CMS/pull/9239

**Comment by reneemhaas-diagram** [comment]
FYI, this was an issue in 8.9.3.
