### ISSUE TITLE
8.10RC: Change prompt when preview mode has ended

### ISSUE THREAD

**Issue by hemraker** [umbraco/Umbraco-CMS#9484]
When navigation to a "preview tab" after you have ended preview mode the following prompt appears:

![image](https://user-images.githubusercontent.com/3663619/100867384-6c35b880-349a-11eb-990d-410311c78c5d.png)
This is phrased as a question but the user does not have a choice (whether to whatch saved or published content).

Solution:
I think it would be appropriate to ask the user if the want the published or preview version of the node:
![image](https://user-images.githubusercontent.com/3663619/100867633-c20a6080-349a-11eb-8ed3-076542dd7212.png)

## Umbraco version

I am seeing this issue on Umbraco version: 8.10RC

Reproduction
------------
1. Open two tabs with preview mode enabled
2. Exit preview mode in one of the tabs
3. Navigate to the second tab and the prompt in question will appear

**Comment by nielslyngsoe** [comment]
Additional note, mostly relevant for the Developer of this: The proposed solution is, identical with the dialog seen when visiting the live website when in Preview Mode, except for the description which says that preview mode was ended. This is done with full intention, to make the question recognizable for the user though this scenario is the opposite of the other one.

**Comment by nul800sebastiaan** [comment]
Fixed in https://github.com/umbraco/Umbraco-CMS/pull/9545
