### ISSUE TITLE
Block list overlay not returns nested block elements in correct order

### ISSUE THREAD

**Issue by bjarnef** [umbraco/Umbraco-CMS#9491]
When using a block list editor with a property "images" which is a Nested Block List editor and having a customer view + controller, where you watch the `block.data.images` property, the model from block list overlay is always retuned in the same order no matter of the sorting in the nested block list items.

Add a Block List editor with using an "Image" element type with the following properties:
- Image (Media Picker - single picker)
- Link (Multi URL Pikcer - single picker)

Add a second Block List editor using another element type "Double Image" with following properties:
- Images (the Block List editor mentioned before and with alias "images").
- Eventually some additional properties.. 

Add a custom view to the second Block List editor with a controller and the following code:

```javascript
// Watch change in property
$scope.$watch("block.data.images", function (newValue, oldValue) {
        if (newValue !== oldValue) {

            console.log("contentData", newValue.contentData);

            var nestedImages = newValue ? newValue.contentData : [];
            console.log("nestedImages", nestedImages);

            var udis = nestedImages.map(function (item) { return item.image; });

            console.log("udis", udis);

            loadMedia(udis);
        }
});

function loadMedia(udis) {
        if (udis) {

            $scope.images = [];

            /* mediaResource.getByIds(ids) doesn't support udi array at the moment,
             * so we look up each image for now.
             */

            for (var i = 0; i < udis.length; i++) {
                var udi = udis[i];

                mediaResource.getById(udi)
                    .then(function (media) {
                        $scope.images.push(media);
                    });
            }

            console.log("$scope.images", $scope.images);
        }
        else {
            $scope.images = [];
        }
    }
```

I am seeing this issue on Umbraco version: 8.9.0

**Comment by bjarnef** [comment]
Okay, it turns out I should use `layout` to get the correct sorting and then sort the `contentData` based on this order. It would probably be easier to get the items in `contentData` in the correct order or if each item in `contentData` had a `sortOrder` property (like some other backoffice elements).

However for now I have solved in this way:

```
// Watch change in property
$scope.$watch("block.data.images", function (newValue, oldValue) {
    if (newValue !== oldValue) {

        var layout = newValue.layout["Umbraco.BlockList"];
        var contentUdis = layout.map(function (layout) { return layout.contentUdi; });

        var nestedImages = newValue ? newValue.contentData : [];

        var udis = nestedImages.sort(function (a, b) {
            return contentUdis.indexOf(a.udi) - contentUdis.indexOf(b.udi);
        })
        .map(function (item) {
            return item.image;
        });

        loadMedia(udis);
    }
});

function loadMedia(udis) {
    if (udis) {

        $scope.images = [];

        /* mediaResource.getByIds(ids) doesn't support udi array at the moment,
            * so we look up each image for now.
            */

        for (var i = 0; i < udis.length; i++) {
            var udi = udis[i];

            mediaResource.getById(udi)
                .then(function (media) {
                    $scope.images.push(media);
                });
        }
    }
    else {
        $scope.images = [];
    }
}
```

**Comment by nielslyngsoe** [comment]
The reasoning for this does not being as obviously easy or as simple as you might expect is because of two things:

1. the concept of Block Editors is not specific to a List but can suit any data structure.
2. we do not have Property Value Converts or any similar concept for angularJS, meaning that you have to deal with the raw data of property editors your self.

So for this scenario, it's therefore needed to write the code that handles the raw data as a list, mapping the layout with the contentData.

Because the contentData is a flat array containing the data of the blocks (no matter the layout)
The layout is the part begin specific to the specific Block Editor, which just contains the order/structure(List, tree, grid, ...) with UIDs of items located in contentData.

I hope that helps anyone who gets in the same situation. Sadly we do not provide AngularJS helpers to manage this, therefor we would encourage you to improve documentation.

**Comment by bjarnef** [comment]
@nielslyngsoe it would be great to have some block list helpers or similar to make this easier to work with. I noticed we have `blockEditorService`, but not sure if this is the right place any helper functions.

In this case maybe something like `getSortedBlockData()`.

```
function getSortedBlockData(blockData) {

        var layout = blockData.layout["Umbraco.BlockList"];
        var contentUdis = layout.map(function (layout) { return layout.contentUdi; });

        var items = blockData? blockData.contentData : [];

        var data = items.sort(function (a, b) {
            return contentUdis.indexOf(a.udi) - contentUdis.indexOf(b.udi);
        })
        .map(function (item) {
            return item;
        });

      return data;
}
```

In block view we could then use something like this:

```
// Watch change in property
$scope.$watch("block.data.images", function (newValue, oldValue) {
    if (newValue !== oldValue) {

        var sortedBlockItems = blockListHelper.getSortedBlockData(newValue);
    }
});
```

**Comment by nielslyngsoe** [comment]
I would say that blockEditorService is intended for Property editors. I think such methods should be put in a service specially created for block editor custom views.

The only problem with your proposal is that it doesn't take settings into account. And it might become performance heavy. But I like the suggestion, we should do something like that.

Could you create a new Issue, requesting an angularJS service with helpers for custom views, and describe the scenarios/features you think such should hold. Then we might get to prioritize it at HQ, to make sure to get it right in regards to the above factors :-)

Thanks

**Comment by bjarnef** [comment]
@nielslyngsoe I have submitted a new feature request here: https://github.com/umbraco/Umbraco-CMS/issues/9553
