### ISSUE TITLE
Custom Validation

### ISSUE THREAD

**Issue by RachBreeze** [umbraco/Umbraco-CMS#9509]
Hello,

Firstly apologies if I have missed a setting here when raising error messages, but what would be really nice is a way to set on the custom error message the property that has caused the error.  If we look at the sample code for error handling provided on here https://our.umbraco.com/documentation/reference/events/contentservice-events it errors on this test:

```
                    var newsArticleTitle = node.GetValue<string>("newsTitle");
                    if (newsArticleTitle.Equals(newsArticleTitle.ToUpper()))
                    {
                        // Stop putting news article titles in upper case, so cancel publish
                        e.Cancel = true;

                        // Explain why the publish event is cancelled
                        e.Messages.Add(new Umbraco.Core.Events.EventMessage("Corporate style guideline infringement", "Don't put the news article title in upper case, no need to shout!", Umbraco.Core.Events.EventMessageType.Error));
                    }
```
Where `e` is `Umbraco.Core.Events.ContentPublishingEventArgs`

What would be great is if we could pass in to ` e.Messages.` the property that has caused the error in this case `newsTitle`.  This could then be highlighted on the front end as an error (with any relevant messages), and then focus could scroll to that error if it was the first error on the page.
There are a few edge cases I can think of where this wouldn't work for all errors, but it would really help, with error handling and accessibility.

Examples, where this wouldn't work, are:
- A value is dependant on another value being selected eg "Only select a state if the user has select USA as a country)
- It could be one value or another value "Eg Please enter the ISBN number of the SKU code but not both"
- You can't use this value as it is used by another page (where the user is given the page name)

**Comment by nul800sebastiaan** [comment]
Thanks @RachBreeze, this is a nice feature request but that's not what these eventhandlers are for and I doubt we could (or would want to) make it work this way, If you have specific needs like the examples mentioned here, it feels to me like a custom property editor is in order, that way you can handle errors on the client side as well. 

I'll close this for now but make sure to comment in case I'm missing something obvious.
