### ISSUE TITLE
Item picker overlay search is no longer working on the grid

### ISSUE THREAD

**Issue by ptilsed** [umbraco/Umbraco-CMS#9513]
After upgrading to the latest release (8.9.1) we have noticed that the search filter is no longer working on the grid editor when you have a large number of editors enabled. The search form is shown but inputting any text does not trigger the filter leaving editors with a long list of items and no way to find what they want quickly. 

## Umbraco version

I am seeing this issue on Umbraco version: 8.9.1

Reproduction
------------

Enable a grid editor with enough editors enabled to trigger the search feature to show. Type in a search term which should either produce no results or limit the results shown. Note editor list is not filtered.

![image](https://user-images.githubusercontent.com/1157593/101479016-726bdf00-3949-11eb-8cae-6e28d20cbfe1.png)

I would expect the list to be reduced to the items that match the search term the editor has provided.

The bug appears to be been introduced as part of PR#8141 as reverting *Umbraco\Views\common\overlays\itempicker\itempicker.html* to the version previous to this commit reenables the search  in this area. The change seems limited to the logic on showing the search form so I'm not sure why it would have an impact on the filter it's self.

**Comment by nul800sebastiaan** [comment]
Thanks, this is fixed for the upcoming version 8.9.2: https://github.com/umbraco/Umbraco-CMS/issues/9394
