### ISSUE TITLE
Upgrade TinyMCE from 4 to 5

### ISSUE THREAD

**Issue by keithlfs** [umbraco/Umbraco-CMS#9519]
Version 8.9.1 of Umbraco runs TinyMCE v4.9.11. We should upgrade to TinyMCE v5, as official support for V4 ends as of 31st December 2020.

https://www.tiny.cloud/blog/how-to-migrate-from-tinymce-4-to-tinymce-5/

It looks like a near drop-in replacement on the client side but I'm aware that there's probably some bespoke Umbraco integration for the back office which I'm not aware of, so unsure of the effort involved.

**Comment by nul800sebastiaan** [comment]
@keithlfs Thanks! We have talked about it before (at length, if you really want to dive in.. https://github.com/umbraco/rfcs/pull/16) but indeed not only would we have to rewrite all of the Umbraco plugins, anybody else who's written and distributed a plugin for Umbraco's Tiny implementation would also need to rewrite it, as such we decided that it was too big of a breaking change for too little benefit.
