### ISSUE TITLE
User disconnected from Backoffice when creating a media item

### ISSUE THREAD

**Issue by rizman** [umbraco/Umbraco-CMS#9520]
### Short description
When one of my users (who isn't in the Administrators group) creates a new Media Item (either using drag'n'drop or using the "Create" drop down button, he is disconnected from the backoffice and send back to the login screen

### Details
When my users (both in production and also local dev machine) try to create a new media item in the Umbraco Back Office, they are send back to the login screen. It looks like they have been disconnected/logged out. However, trying to login again does not work. The login page just reloads. They either have to wait a few minutes, or we have to empty the browser cache. 

This happens if users a adding a new media item both through Drag'n'drop or using the "Create" drop down button in the media section.

It also happens independently of the display language the user uses. (here I tried both English and German).

It happens whether the user is added to a predefined group or a custom group.

The behavior is NOT shown when the user is a member of the Administrator group. Here it works as expected

I also noticed, that the URL does NOT change. 

## Umbraco version

I am seeing this issue on Umbraco version: 8.9.1, after upgrading from 8.6.3

### Specifics

Umbraco Version 8.9.1

The problem occurs on this URL `/umbraco#/media/media/edit/1340`

Tested on Google Chrome Version 87.0.4280.88 (Official Build) (64-bit)
and Edge 44.19041.423.0

No error message can be seen in the Backoffice logs.
The Chrome developer log shows one error message:
`VM9:1 GET https://www.weiswampach.lu/umbraco/backoffice/UmbracoApi/Users/GetByIds? 401
(anonymous) @ VM9:1
(anonymous) @ DependencyHandler.axd`
![image](https://user-images.githubusercontent.com/745585/101627878-4b7fdc80-3a1f-11eb-968b-4338175e9005.png)

**Comment by nul800sebastiaan** [comment]
Hi @rizman - the 401 error indicates that they're not authorized to do something. I would recommend you check the permissions you've set for your user group.

For further questions, make sure to head on over to the forums at https://our.umbraco.com where our friendly community can help you find the best solution for your requirements! 👍

**Comment by rizman** [comment]
> Hi @rizman - the 401 error indicates that they're not authorized to do something. I would recommend you check the permissions you've set for your user group.
> 
> For further questions, make sure to head on over to the forums at https://our.umbraco.com where our friendly community can help you find the best solution for your requirements! 👍

Hi sebastiaan,

I asked on the Forums but didn't get a response...unfortunately.

To get back to your answer:
I haven't done any changes to the group permissions when upgrading from 8.6.3 to 8.9.1. To be sure, I checked, but my permissions seem to be all OK. Not really sure what else I could try.

**Comment by sebastiandammark** [comment]
I'm experiencing the same issues, but only with a specific document type.
It only happens when the User is in the **Editors** user group, if I move the user to another group everything is ok.

It's the same call that fails:
`/umbraco/backoffice/UmbracoApi/Users/GetByIds?`

**Comment by nul800sebastiaan** [comment]
I'm afraid I don't have much to offer here, this works on a clean install, so it would need to be checked out by adding a debugger connected to the source code.

**Comment by rizman** [comment]
> I'm afraid I don't have much to offer here, this works on a clean install, so it would need to be checked out by adding a debugger connected to the source code.

I might be able to try that if time allows at work. Can you point me in the right direction what files in the source code I'd need to check specifically? I'm not familiar with the Umbraco Source Code.

**Comment by nul800sebastiaan** [comment]
I believe that API endpoint ends up here: https://github.com/umbraco/Umbraco-CMS/blob/v8/contrib/src/Umbraco.Web/Editors/MediaController.cs#L183
