### ISSUE TITLE
GetContentForFutureRelease method

### ISSUE THREAD

**Issue by skartknet** [umbraco/Umbraco-CMS#9532]
I would like to develop a dashboard where I can list all the pages that I have scheduled for publishing. At the moment I can't know the dates where I have some content scheduled unless I go page by page checking them.

I haven't found a method in the ContentService that I can use for this.

I can see there's a method called GetContentForRelease where we could base the new method. It's basically the same but the comparison for the datetime would be >= instead <=

I can't create my own method because all the resources I need to use are internal.

How can you help?
-------------------------------

Happy to create a PR if the feature is useful and if there's not a workaround that I can't think of!

**Comment by nul800sebastiaan** [comment]
Thanks @skartknet - not sure why this is internal but there's probably a good reason for it, I'll ask around. 

In the mean time, you could "just" query the `umbracoContentSchedule` table yourself, I see no problem with that?

**Comment by nul800sebastiaan** [comment]
Hi again @skartknet, I got myself a little confused yesterday! Why can you use `ContentService.GetContentForRelease`? If you pass it a date far in the future it should give you all you need.

**Comment by skartknet** [comment]
OMG, it makes total sense. I can't believe it's that simple. Thanks!
