### ISSUE TITLE
8.5.3 upgrade to 8.9.0 installation fails under load-balanced environment with 'Could not clear temp files' - one time only

### ISSUE THREAD

**Issue by keitharowe** [umbraco/Umbraco-CMS#9534]
# Bug Summary
When upgrading Umbraco the install fails initially with the 'Could not clear temp files' error. However, it appears that the upgrade does complete. Restart of IIS application pool does not seem to clear, second deployment clears the error and site returns to functioning properly.

## 8.5.3 to 8.9.0

I am seeing this issue on Umbraco version: 8.5.3 when upgrading. This happened on client's UAT environment and under production environment as well.

### Additional Details

- Deployments are handled by Azure DevOps
- Have not tried to reproduce again on UAT environment due to client concerns
- ClientDependency.config version number is auto-updated with Azure DevOps build number using custom transform
- Confirmed that Application Pool Identity has 'Modify' permissions on entire web folder structure

### Error Log

```
{"@t":"2020-12-08T02:18:15.7242124Z","@mt":"Umbraco must install or upgrade.","@l":"Warning","SourceContext":"Umbraco.Web.UmbracoModule","ProcessId":5280,"ProcessName":"w3wp","ThreadId":23,"AppDomainId":3,"AppDomainAppId":"LMW3SVC1ROOT","MachineName":"****************","Log4NetLevel":"WARN ","HttpRequestNumber":1,"HttpRequestId":"81a40132-c42c-4939-997b-663f3db970e9"}
{"@t":"2020-12-08T02:18:18.3961010Z","@mt":"Could not clear temp files","@l":"Error","@x":"System.UnauthorizedAccessException: Access to the path '6119_bd11939ce62949d991a4aa073fa5c7fa.cdJ' is denied.\r\n   at System.IO.Directory.DeleteHelper(String fullPath, String userPath, Boolean recursive, Boolean throwOnTopLevelDirectoryNotFound, WIN32_FIND_DATA& data)\r\n   at System.IO.Directory.Delete(String fullPath, String userPath, Boolean recursive, Boolean checkHost)\r\n   at Umbraco.Web.JavaScript.ClientDependencyConfiguration.ClearTempFiles(HttpContextBase currentHttpContext) in D:\\a\\1\\s\\src\\Umbraco.Web\\JavaScript\\ClientDependencyConfiguration.cs:line 132","SourceContext":"Umbraco.Web.JavaScript.ClientDependencyConfiguration","ProcessId":5280,"ProcessName":"w3wp","ThreadId":15,"AppDomainId":3,"AppDomainAppId":"LMW3SVC1ROOT","MachineName":"****************","Log4NetLevel":"ERROR","HttpSessionId":"umyyxp3p0hk2yohd2yu12hkt","HttpRequestNumber":2,"HttpRequestId":"efb3b8a9-cd7b-4329-a4c3-e78b62c5fad4"}
{"@t":"2020-12-08T02:18:18.4429797Z","@mt":"Could not clear temp files","@l":"Error","@x":"System.UnauthorizedAccessException: Access to the path '5636_b8f4c497dcae43518d38dd2c3bdfdc46.cdJ' is denied.\r\n   at System.IO.Directory.DeleteHelper(String fullPath, String userPath, Boolean recursive, Boolean throwOnTopLevelDirectoryNotFound, WIN32_FIND_DATA& data)\r\n   at System.IO.Directory.Delete(String fullPath, String userPath, Boolean recursive, Boolean checkHost)\r\n   at Umbraco.Web.JavaScript.ClientDependencyConfiguration.ClearTempFiles(HttpContextBase currentHttpContext) in D:\\a\\1\\s\\src\\Umbraco.Web\\JavaScript\\ClientDependencyConfiguration.cs:line 132","SourceContext":"Umbraco.Web.JavaScript.ClientDependencyConfiguration","ProcessId":5280,"ProcessName":"w3wp","ThreadId":23,"AppDomainId":3,"AppDomainAppId":"LMW3SVC1ROOT","MachineName":"****************","Log4NetLevel":"ERROR","HttpSessionId":"3tmq4uucsd3stbjpstweu224","HttpRequestNumber":3,"HttpRequestId":"ffb1eb79-63a7-41e6-96b0-a4eb641e2b05"}
{"@t":"2020-12-08T02:19:01.7088845Z","@mt":"Umbraco must install or upgrade.","@l":"Warning","SourceContext":"Umbraco.Web.UmbracoModule","ProcessId":5280,"ProcessName":"w3wp","ThreadId":23,"AppDomainId":4,"AppDomainAppId":"LMW3SVC1ROOT","MachineName":"****************","Log4NetLevel":"WARN ","HttpRequestNumber":1,"HttpRequestId":"a3464308-40a9-49a3-bad3-42923fa040a5"}
```

### Expected result

Expected the installation upgrade process to complete

### Actual result

Install appears to "hang" as JavaScript error is seen on the console. 

#### Workaround

1. Thinking about writing a PowerShell script to delete the /APP_Data/Temp/ClientDependency folder, thoughts?

**Comment by nul800sebastiaan** [comment]
The error is thrown from this code that hasn't changed for years: https://github.com/umbraco/Umbraco-CMS/blame/v8/contrib/src/Umbraco.Web/JavaScript/ClientDependencyConfiguration.cs#L137

I think you'll need to figure out why the deletion fails, [according to this](https://stackoverflow.com/a/24796126/5018) it is due to one of four reasons: 

- The caller does not have the required permission.
- The file is an executable file that is in use.
- Path is a directory.
- Path specified a read-only file.

I suspect the files are in use due to your load balanced environment. I don't know enough about load balanced environments to make further suggestions. 
However a quick search does not indicate many other people running into this problem, so I suspect it might be your setup that's slightly off, not sure, I'll need to ask around.

**Comment by keitharowe** [comment]
@nul800sebastiaan thank you for your insight, much appreciated. I'm going to operate under the assumption that the file is in use as well, and troubleshoot/mitigate. No need to do anything further. I'll reopen/repost if I gain any further information. Thanks again.
