### ISSUE TITLE
Backoffice UI: the create new content form doesn't maintain the inputs after submitted and canceled by the third party plugin

### ISSUE THREAD

**Issue by nick-hoang** [umbraco/Umbraco-CMS#9538]
A brief description of the issue goes here.

## Umbraco version

I am seeing this issue on Umbraco version: 7.15.6

Reproduction
------------

If you're filing a bug, please describe how to reproduce it. Include as much
relevant information as possible, such as:

### Bug summary

The create new content form doesn't maintain the inputs after submitted and canceled by the third party plugin.

### Steps to reproduce

1. Create a dummy content type with some properties
2. Create a custom application event handler, hook to Content Saving event
3. In the event handler function, set e.Cancel = true and add a warning message, i.e: e.Message.Add(new EventMessage("Warning", "This is a warning message", EventMessageType.Warning))
4. Login the backoffice, do create new content and input some data and Click Save and Publish
5. The warning message appears, the content area is blank, all inputs gone
### Expected result

Don't show any error messages. The form should be visible and all inputs are maintained after submitted.

### Actual result

The form disappears, all imputing data done, the content area is blank. There's an error message says: Request error: The URL returned a 404 (not found): /umbraco/backoffice/UmbracoApi/Content/GetById

**Comment by nul800sebastiaan** [comment]
If you want the values to be retained then make sure to cancel the publish event, not the save event. 

For more help, this would be excellent questions for the forums where our friendly community can help you find the best solution for your requirements. 
Make sure to head on over to https://our.umbraco.com and ask follow up questions there! 👍
