### ISSUE TITLE
V8 -> Swap the default starter kit with uMazel 

### ISSUE THREAD

**Issue by TimGeyssens** [umbraco/Umbraco-CMS#9542]
Since there is no further dev planned on the current v8 starter kit (which I think is still the v7 one).

It would be great to swap it with the free kit uMazel https://www.dot-see.com/en/blog/the-new-umazel-starter-kit-for-umbraco-8/

This is a lot more feature rich + uses the block list editor instead of grid... so makes a lot more sense for folks that have the first experience with Umbraco to see this instead of something using old best practises

As a plus I would say: HQ -> sponsor Sotiris and team for the amazing work, so they can also open source it!

**Comment by sotirisf** [comment]
Regardless of outcome, we sincerely appreciate your suggestion! Truth is we could use some kind of sponsorship / financing! :) 
FYI, We're currently working on a second starter kit based on roughly the same codebase - it won't be free, but it will be ridiculously cheap in order for everyone to be able to have access.

**Comment by TimGeyssens** [comment]
Yeah it would make perfect sense! And yeah about the sponsorshop I can't decide that but seems like a lot of hours of work has gone into it... so instead of making something new they could just give you some financing...for a part of the dev hours

**Comment by nul800sebastiaan** [comment]
Thanks, there's currently no plans to swap out the default starter kit. We'll keep it in mind when we have time to work on the installer again, we're aware that the current one isn't ideal. 👍

**Comment by TimGeyssens** [comment]
Hey, sad to see this is just closed immediately... what if the PR is available and HQ just needs to merge? 100% community driven PR... with an up to date and flexible starter kit...

**Comment by nul800sebastiaan** [comment]
Unfortunately we don't have the resources to take on a whole new project at the moment, even if it is community-driven, we still need to spend time reviewing and maintaining it, fixing bugs, etc. Anything that we ship with is something that we need to be completely responsible for and that's currently not possible for this request.

**Comment by sotirisf** [comment]
Totally understandable by me Sebastiaan. Many thanks for the suggestion anyway, Tim!

**Comment by TimGeyssens** [comment]
Sure, but would you consider packages available in the package section (so installable from backend) also as something you ship with? If it is clear to folks that it is a community driven kit...not supported by HQ... anyway instead of swapping we can add it as an option...

**Comment by bjarnef** [comment]
It is always an option to find the starter kits here https://our.umbraco.com/packages/?category=Starter%20Kits or from backoffice installer.

![image](https://user-images.githubusercontent.com/2919859/102081254-3edcf900-3e10-11eb-9f4d-2dd0694411e9.png)

It can also lead to frustration if showing these starter kits in the installer and the starter kit isn't supported or doesn't work in a specific Umbraco version and when it isn't officially supported and tested by HQ.

**Comment by lars-erik** [comment]
I've long wanted for the `GetPackages` method called in that step to be customizable. I think that MSDI with dotnet core will finally give us the ability to swap out pretty much anything, including this. Then you could add a package to just swap out the default package source for starter kits.

It's pretty much a matter of replacing this method:  
https://github.com/umbraco/Umbraco-CMS/blob/1f44b94ef62adf0db4c489f5079ceb322503a523/src/Umbraco.Web/Install/InstallHelper.cs#L152

**Comment by stevetemple** [comment]
I think this is something that would really make sense to jump on in net core version. Have a picker during install for starter kits sourced from our that will work with the current version. 

Would be a nice friendly feature for those new to Umbraco, and as @lars-erik's says this becomes a bit easier with the MSDI

**Comment by TimGeyssens** [comment]
sure all good ideas! but postponing it to v next leaves out all the folks discovering Umbraco today, tomorrow, next months  before core version is ready... why have a default started kit that shows an outdated way of building sites... when with minimal effort we can fix this together... with the automated testing that is (planned) to happen before releasing a new version the small bugs can be found... and would also be ace to catch possible breaking changes with a more recent started kit taking advantages of the new stuff.

**Comment by TimGeyssens** [comment]
@bjarnef yeah everything that you can just install from the backend needs to be 100% compatible... you don't want to risk folks trying something and just ending in a YSOD in a couple of clicks

**Comment by TimGeyssens** [comment]
and the dot-see team even has docs: https://www.dot-see.com/en/blog/working-with-blocks-in-the-umazel-starter-kit-for-umbraco-v8/

I really don't see why this couldn't work out...unless there is a commercial conflict with UNO... but more people seeing and loving the power of the core CMS will lead to more sales in the long run...and a bigger community benefiting us all

**Comment by nul800sebastiaan** [comment]
As I said, the reason we don't prioritize this now is because we don't have the bandwith to do so with regards to testing, upgrading, bug fixing etc.

Once we do look at updating the default starter kit / the installer, we'll keep this in mind.

**Comment by TimGeyssens** [comment]
of fair enough but closing the issue seems like that won't be look at...

**Comment by nul800sebastiaan** [comment]
It won't be looked at in the foreseeable future, we'll have to evaluate what the world looks like when we do get to it, I've labeled it now for future searches.
