### ISSUE TITLE
Umbraco 8.9.1 Infinite Editing, Save and Close button not firing on benign doc type changes

### ISSUE THREAD

**Issue by jattwood** [umbraco/Umbraco-CMS#9563]
Using infinite editing in the umbraco back office, the "Save and Close" button does not fire on some benign document type updates.

I am seeing this issue on Umbraco version: Umbraco version 8.9.1

Reproduction
------------

- Open a content Item in the content section
- go to the info tab
- open the doc type
- do some type of benign update to the doctype that would not affect the model, for example, change the color of the icon.
- Hit save and close - the button will not fire. You must use "save and generate models" in order to affect a change.

NOTE. If this does not occur the first time around, make an update involving a more substantial change to the document type and then repeat the above steps. I have encountered this issue mainly after renaming the doc type alias, but it will happen on secondary updates to the doc type intermittantly.

### Expected result
 We would expect the Save and Close button to save and close the dialogue as expected.

### Actual result
Currently there is no action - the button does not fire

**Comment by nul800sebastiaan** [comment]
Thanks! This a bug that is fixed for the upcoming 8.9.2 version - https://github.com/umbraco/Umbraco-CMS/pull/9300
