### ISSUE TITLE
Umbraco 8.9.1 Infinite editing, template search not functioning

### ISSUE THREAD

**Issue by jattwood** [umbraco/Umbraco-CMS#9565]
Using Umbraco 8.9.1 Infinite editing, when attempting to search for a template associated with a document type, the search does not work either on key up or enter, causes 

## Umbraco version

I am seeing this issue on Umbraco version: 8.9.1

Reproduction
------------
- Open any content Item in content editor that has a template
- go to info tab
- open the doc type,
- click on templates,
- click on choose extra template,
- attempt a search

### Expected result

We would expect the search to function on key up event and enter event

### Actual result

Search does not work, error thrown: TypeError: Cannot read property 'alias' of undefined originating in DependencyHandler.
![image](https://user-images.githubusercontent.com/6452616/102418847-93c56e80-3fcc-11eb-9dd3-dc629f1007ce.png)

**Comment by nul800sebastiaan** [comment]
Sorry about that, seems like we broke something along the way :( This will be fixed for the upcoming v8.9.2 release, please follow the progress of that over here: https://github.com/umbraco/Umbraco-CMS/issues/9394
