### ISSUE TITLE
Cannot insert duplicate key in object 'dbo.cmsContentNu'  Umbraco 8.9.1

### ISSUE THREAD

**Issue by HevinPatel** [umbraco/Umbraco-CMS#9567]
A brief description of the issue goes here.

While we are trying to edit the existing entry of the content then we are getting the error saying that...
**Cannot insert duplicate key in object 'dbo.cmsContentNu'**

## Umbraco version

I am seeing this issue on Umbraco version: 8.9.1

Reproduction
------------

If you're filing a bug, please describe how to reproduce it. Include as much
relevant information as possible, such as:

### Bug summary

We have created a fresh project using Umbraco 8.9.1 nuget package installation. Everything works fine in the machine where the Visual Studio and Database both are located.

But we have to work in a team, so later on we have moved the database to the local server. So after moving the database on Local server we have perform some testing so that we can make sure that everything is working fine on local server as well.

However, we are running with issues after moving the database on the server as below.

1) We can create as many new content entries as we want so that the database working fine, but we when we try to edit any content of the existing entry then it was giving the duplicate key violation error.
2) We have tried to restore the working copy of database from the local machine on the server and still it is giving the same error.

We have verified the SQL Server version on local machine and server as well and both are SQL Server 2016.

### Specifics
Umbraco 8.9.1
Visual Studio 2019
MS SQL Server 2016 
We have checked in FF and Chrome

Error message : 
{"@t":"2020-12-17T11:49:01.7297996Z","@mt":"Exception ({InstanceId}).","@l":"Error","@x":"System.Data.SqlClient.SqlException (0x80131904): Violation of PRIMARY KEY constraint 'PK_cmsContentNu'. Cannot insert duplicate key in object 'dbo.cmsContentNu'. The duplicate key value is (1060, 0).\r\nThe statement has been terminated.\r\n   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)\r\n   at System.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)\r\n   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)\r\n   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)\r\n   at System.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString, Boolean isInternal, Boolean forDescribeParameterEncryption, Boolean shouldCacheForAlwaysEncrypted)\r\n   at System.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean async, Int32 timeout, Task& task, Boolean asyncWrite, Boolean inRetry, SqlDataReader ds, Boolean describeParameterEncryptionRequest)\r\n   at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry)\r\n   at System.Data.SqlClient.SqlCommand.InternalExecuteNonQuery(TaskCompletionSource`1 completion, String methodName, Boolean sendToPipe, Int32 timeout, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry)\r\n   at System.Data.SqlClient.SqlCommand.ExecuteNonQuery()\r\n   at StackExchange.Profiling.Data.ProfiledDbCommand.ExecuteNonQuery() in C:\\projects\\dotnet\\src\\MiniProfiler.Shared\\Data\\ProfiledDbCommand.cs:line 272\r\n   at Umbraco.Core.Persistence.FaultHandling.FaultHandlingDbCommand.<ExecuteNonQuery>b__31_0() in D:\\a\\1\\s\\src\\Umbraco.Core\\Persistence\\FaultHandling\\RetryDbConnection.cs:line 209\r\n   at Umbraco.Core.Persistence.FaultHandling.FaultHandlingDbCommand.<>c__DisplayClass33_0`1.<Execute>b__0() in D:\\a\\1\\s\\src\\Umbraco.Core\\Persistence\\FaultHandling\\RetryDbConnection.cs:line 222\r\n   at Umbraco.Core.Persistence.FaultHandling.RetryPolicy.ExecuteAction[TResult](Func`1 func) in D:\\a\\1\\s\\src\\Umbraco.Core\\Persistence\\FaultHandling\\RetryPolicy.cs:line 172\r\n   at Umbraco.Core.Persistence.FaultHandling.FaultHandlingDbCommand.Execute[T](Func`1 f) in D:\\a\\1\\s\\src\\Umbraco.Core\\Persistence\\FaultHandling\\RetryDbConnection.cs:line 219\r\n   at Umbraco.Core.Persistence.FaultHandling.FaultHandlingDbCommand.ExecuteNonQuery() in D:\\a\\1\\s\\src\\Umbraco.Core\\Persistence\\FaultHandling\\RetryDbConnection.cs:line 209\r\n   at NPoco.Database.ExecuteNonQueryHelper(DbCommand cmd)\r\n   at NPoco.Database.InsertImp[T](PocoData pocoData, String tableName, String primaryKeyName, Boolean autoIncrement, T poco)\r\nClientConnectionId:162b23fb-1893-47bc-acad-bd475943b857\r\nError Number:2627,State:1,Class:14","InstanceId":"a45808c7","SourceContext":"Umbraco.Core.Persistence.UmbracoDatabase","ProcessId":16644,"ProcessName":"iisexpress","ThreadId":35,"AppDomainId":4,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"HEVIN-LAPTOP","Log4NetLevel":"ERROR","HttpRequestNumber":10,"HttpRequestId":"b39b0e81-9094-446d-b5b2-0b3db49c636d"}

### Steps to reproduce
Moved the working copy of database in local machine with Umbraco website moved to the local server so that multiple team member can work on the same project.

### Expected result
It should work as it was working in the local machine, but content update not working.

### Actual result
It should work as it was working in local machine, but after moving the database on local server most of the things are working but when we are editing the content it is generating the "Cannot insert duplicate key in object 'dbo.cmsContentNu'" error, which is not expected.

**Comment by nul800sebastiaan** [comment]
Hi @HevinPatel, what you've done is that you've now created a load-balanced environment (multiple "servers", localhost site, editing in the same backoffice). This is not supported. You need to have 1 dedicated backoffice server where all editing is being done, this can not be each local copy of the code.

Documentation on how to set up a load balanced environment can be found here: https://our.umbraco.com/Documentation/Getting-Started/Setup/Server-Setup/Load-Balancing/

For more questions on how best work as a team on an Umbraco site I would recommend you [head over to the forums](https://our.umbraco.com) and describe how you ideal want to work. Our friendly community can help you find the best solution for your requirements.

**Comment by HevinPatel** [comment]
Hi Sebastiaan,

We do not have any load balancer setup, we are just trying to setting up 1 database server and 1 web so that we can manage backoffice from there, but for now we are not able to do the same.

If you look at the error then you can see that the code is trying to add the duplicate values in the database cmsContentNu table, wherein in local db it was working fine but when we try to setup on server we are facing that error.

Thanks.

**Comment by nul800sebastiaan** [comment]
@HevinPatel you indicated that you want to work as a team on the same database, so now you have multiple installs of Umbraco (each team member's install) connecting to the same database, that is the essence of a load balanced setup. Umbraco can not handle this.

This is explained in the first question of the FAQ in the documentation: https://our.umbraco.com/Documentation/Getting-Started/Setup/Server-Setup/Load-Balancing/#faqs

**Comment by HevinPatel** [comment]
I said that we have to work as a team but we are not using same database with multiple Umbraco install, as we are just setting up the db on server and backoffice on web, but still we are facing the issue.

Thanks.

**Comment by HevinPatel** [comment]
I have created new one with updated content with ID 9577, please do not close it before we find the solution... As for now we have not started working as a team but we have 1 umbraco setup and one database, but still it is generating the same error.

We will look into the provided link from you for the load balancing setup.

**Comment by Shazwazza** [comment]
Having multiple web apps pointing to the same DB is Load Balancing. It's not supported due to possible concurrency issues but it should not result in SQL exceptions like this.

I would suggest that you log in to the back office and go to the Published Cache dashboard and rebuild things in this order

![image](https://user-images.githubusercontent.com/1742685/102555720-6c30ec00-411b-11eb-91d1-4e87088790ed.png)

Then see if you still get the error.

**Comment by HevinPatel** [comment]
Hi @Shazwazza,

Tried but no luck, the issue is remain there as is.

Thanks

**Comment by nul800sebastiaan** [comment]
The only other thing I can imagine here is if you reseeded your database you might get this problem somehow. It's a very common scenario to move a dev database to a new server and start the site against the new server, so given that we haven't seen this issue at all before, I am going to have to assume something is off specifically for you. The only other issue I've found that might be somewhat related is https://github.com/umbraco/Umbraco-CMS/issues/8294 but that's a problem with editing a single doctype.

My only recommendation for now is to investigate your setup, maybe attach the umbraco source code to see what's going on.

I'll keep an eye out for similar reports to see if we can get to a better understanding of where the problem comes from.

**Comment by HevinPatel** [comment]
@nul800sebastiaan  I was also thought the same, so what we did today as below.

Started fresh installation of Umbraco...
1) Created new blank VS project using 4.7.2 framework
2) Install Umbaco CMS 8.9.1 package
3) Create new blank database on server
4) Run the project and use the newly created database during the backoffice installation

Now, we have created all steps again as below...
1) Created new template
2) Created new document type
3) Created new content entry for home page
4) Now, we are trying to editing the content entry created at step 3...

Still we are facing the same issue...

Not sure why but with the defined setup, when we are editing the content entry it was try to insert new record in the cmsContentNu table, while it should only update the existing one.

To understand what is happening we have removed the composite key created on the table and find that when we are editing a record it was update the existing one and increase the value of field named rv, but at the same time it was inserting another entries of the same content and nodeid in the table with rv value as 0.

Hope this will help to understand what went wrong...

Thanks

**Comment by nul800sebastiaan** [comment]
I don't know about step 3 in your new install

> Create new blank database on server

What happens if you back up your local database and restore that backup on the remote server and then use that?

**Comment by HevinPatel** [comment]
That is what we did yesterday per my comments, we did backup of local database and restore it on remote server.

In all the possible cases we are facing the same issue if we are using the remote database.

**Comment by nul800sebastiaan** [comment]
Sounds like something like this is going on: https://dba.stackexchange.com/questions/198827/restore-all-identity-seeds-out-of-sync-since-database-restore

**Comment by nul800sebastiaan** [comment]
Or something like this: https://dba.stackexchange.com/questions/163876/restoring-database-backup-makes-identity-column-start-at-1-again
