### ISSUE TITLE
Editing content generates an error : Cannot insert duplicate key in object 'dbo.cmsContentNu'  Umbraco 8.9.1

### ISSUE THREAD

**Issue by HevinPatel** [umbraco/Umbraco-CMS#9577]
While we are trying to edit the existing entry of the content then we are getting the error saying that...
Cannot insert duplicate key in object 'dbo.cmsContentNu'

## Umbraco version

I am seeing this issue on Umbraco version: 8.9.1

Reproduction
------------

If you're filing a bug, please describe how to reproduce it. Include as much
relevant information as possible, such as:

### Bug summary
We have created a fresh project using Umbraco 8.9.1 nuget package installation. Everything works fine in the machine where the Visual Studio and Database both are located. Later on we have moved the database to the local server. So after moving the database on Local server we have perform some testing so that we can make sure that everything is working fine on local server as well.

However, we are running with issues after moving the database on the server as below.

We can create as many new content entries as we want so that the database working fine, but we when we try to edit any content of the existing entry then it was giving the duplicate key violation error.

We have tried to restore the working copy of database from the local machine on the server and still it is giving the same error.

We have verified the SQL Server version on local machine and server as well and both are SQL Server 2016.
Specifics

### Specifics
Umbraco 8.9.1
Visual Studio 2019
MS SQL Server 2016
We have checked in FF and Chrome

### Steps to reproduce
{"@t":"2020-12-17T11:49:01.7297996Z","@mt":"Exception ({InstanceId}).","@l":"Error","@x":"System.Data.SqlClient.SqlException (0x80131904): Violation of PRIMARY KEY constraint 'PK_cmsContentNu'. Cannot insert duplicate key in object 'dbo.cmsContentNu'. The duplicate key value is (1060, 0).\r\nThe statement has been terminated.\r\n at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action1 wrapCloseInAction)\r\n at System.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action1 wrapCloseInAction)\r\n at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)\r\n at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)\r\n at System.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString, Boolean isInternal, Boolean forDescribeParameterEncryption, Boolean shouldCacheForAlwaysEncrypted)\r\n at System.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean async, Int32 timeout, Task& task, Boolean asyncWrite, Boolean inRetry, SqlDataReader ds, Boolean describeParameterEncryptionRequest)\r\n at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method, TaskCompletionSource1 completion, Int32 timeout, Task& task, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry)\r\n at System.Data.SqlClient.SqlCommand.InternalExecuteNonQuery(TaskCompletionSource1 completion, String methodName, Boolean sendToPipe, Int32 timeout, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry)\r\n at System.Data.SqlClient.SqlCommand.ExecuteNonQuery()\r\n at StackExchange.Profiling.Data.ProfiledDbCommand.ExecuteNonQuery() in C:\projects\dotnet\src\MiniProfiler.Shared\Data\ProfiledDbCommand.cs:line 272\r\n at Umbraco.Core.Persistence.FaultHandling.FaultHandlingDbCommand.b__31_0() in D:\a\1\s\src\Umbraco.Core\Persistence\FaultHandling\RetryDbConnection.cs:line 209\r\n at Umbraco.Core.Persistence.FaultHandling.FaultHandlingDbCommand.<>c__DisplayClass33_01.<Execute>b__0() in D:\\a\\1\\s\\src\\Umbraco.Core\\Persistence\\FaultHandling\\RetryDbConnection.cs:line 222\r\n at Umbraco.Core.Persistence.FaultHandling.RetryPolicy.ExecuteAction[TResult](Func1 func) in D:\a\1\s\src\Umbraco.Core\Persistence\FaultHandling\RetryPolicy.cs:line 172\r\n at Umbraco.Core.Persistence.FaultHandling.FaultHandlingDbCommand.Execute[T](Func`1 f) in D:\a\1\s\src\Umbraco.Core\Persistence\FaultHandling\RetryDbConnection.cs:line 219\r\n at Umbraco.Core.Persistence.FaultHandling.FaultHandlingDbCommand.ExecuteNonQuery() in D:\a\1\s\src\Umbraco.Core\Persistence\FaultHandling\RetryDbConnection.cs:line 209\r\n at NPoco.Database.ExecuteNonQueryHelper(DbCommand cmd)\r\n at NPoco.Database.InsertImp[T](PocoData pocoData, String tableName, String primaryKeyName, Boolean autoIncrement, T poco)\r\nClientConnectionId:162b23fb-1893-47bc-acad-bd475943b857\r\nError Number:2627,State:1,Class:14","InstanceId":"a45808c7","SourceContext":"Umbraco.Core.Persistence.UmbracoDatabase","ProcessId":16644,"ProcessName":"iisexpress","ThreadId":35,"AppDomainId":4,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"HEVIN-LAPTOP","Log4NetLevel":"ERROR","HttpRequestNumber":10,"HttpRequestId":"b39b0e81-9094-446d-b5b2-0b3db49c636d"}

### Expected result
Moved the working copy of database in local machine with Umbraco website moved to the local server should work as expected but it was generating an error.

### Actual result
It should work as it was working in local machine, but after moving the database on local server most of the things are working but when we are editing the content it is generating the "Cannot insert duplicate key in object 'dbo.cmsContentNu'" error, which is not expected.

**Comment by nul800sebastiaan** [comment]
This duplicates https://github.com/umbraco/Umbraco-CMS/issues/9567
