### ISSUE TITLE
MemberService_Saving event not persisting property values

### ISSUE THREAD

**Issue by Wiggee11** [umbraco/Umbraco-CMS#9582]
When listening to the MemberService_Saving event to set a property value when a new Member is created, the property value is set for the first 2 MemberService_Saving events but when the 3rd event is triggered the value is null and not persisted.

## Umbraco version
I am seeing this issue on Umbraco version: 8.9.1

### Bug summary
I'm listening in to the MemberService_Saving event to set a property value when a new Member is created:

```
private void MemberService_Saving(
	IMemberService sender,
	SaveEventArgs<IMember> e)
{
	foreach (var member in e.SavedEntities)
	{
		var newMember = !member.HasIdentity;
		if (newMember)
		{
			member.SetValue("propertyAlias", "value");
		}
	}
}
```

When a new Member is created in the backoffice, the MemberService_Saving event is triggered 3 times. The first 2 times it correctly sets the property value, but the 3rd time it seems to lose the value and is not persisted.

If I Save an existing Member then the MemberService_Saving event is only triggered once and the property value is saved correctly (if the newAccount check is removed).

Sounds like it could be a similar issue to this https://github.com/umbraco/Umbraco-CMS/issues/3320 and other community members are reporting experiences of the same issue.

### Specifics
- Umbraco 8.9.1 fresh install
- Property is a Label string
- Logging the entity in Saving and Saved events shows the same result
- I am not listening to the MemberService_Saving event anywhere else that could interfere

### Steps to reproduce
1. Install Umbraco 8.9.1
2. Add a Label string property to the Member Type
3. Register to the MemberService_Saving event, set a value for your label property and log the entity
4. Create and save a new Member in the backoffice
5. Inspect the entity in the log for your property value

### Expected result
When you set a property value for a new Member in the MemberService_Saving event, it should persist the value throughout the chain of events until the Member is saved.

### Actual result
When you set a property value for a new Member in the MemberService_Saving event, the value is not persisted when the Member is saved.

### Workaround
I have developed a workaround for now:

```
private void MemberService_Saving(
	IMemberService sender,
	SaveEventArgs<IMember> e)
{
	foreach (var member in e.SavedEntities)
	{
		var newMember = !member.HasIdentity;
		var propertyValueIsEmpty = string.IsNullOrWhiteSpace(member.GetValue<string>("propertyAlias"));
		if (newMember || propertyValueIsEmpty)
		{
			member.SetValue("propertyAlias", "value");
		}
	}
}
```

I've added an additional check to see whether the Member's property value is empty. This then gets triggered on the 3rd and final MemberService_Saving event and sets the value, which then gets persisted.

**Comment by nul800sebastiaan** [comment]
Looks like you're not saving them by calling `memberService.Save(member)`. 😃 

Of course you'll need to be careful because doing that will trigger another `MemberService_Saving` event, I believe you can pass a parameter to not raise additional events.

In any case, this is an excellent question for the forums where our friendly community can help you find the best solution for your requirements. 
Make sure to head on over to https://our.umbraco.com and ask follow up questions there! 👍
