### ISSUE TITLE
MySql.Data.dll version issue

### ISSUE THREAD

**Issue by kistva** [umbraco/Umbraco-CMS#9587]
Due a upgrade from 7.2.4 -> 7.15.6 we hit an error with the MySql.Data.dll

The bug came after the Nuget package for Umbraco 7.15.6 was installed. 

## Umbraco version

I am seeing this issue on Umbraco version: Then the 7.15.6 when upgrading with the Nuget for Umbraco 7.15.6
The version of MySql.Data.Dll for Umbraco 7.15.6 is 6.9.9.0
When installing with Nuget, it will install all references including the MySql.Data.DLL by Nuget packages,
But the MySql.Data.Dll Nuget package doesn't have version 6.9.9.0 at nuget.org and therefore installs version 6.9.12.0  
Which gives the error

To solve it I have added following in the web.config in the section
```
<runtime>
<assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1">
...

```

```
      <dependentAssembly>
        <assemblyIdentity name="MySql.Data" publicKeyToken="c5687fc88969c44d" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-6.9.12.0" newVersion="6.9.12.0" />
      </dependentAssembly>

```

**Note:** That if you just install the ZIP package it works fine since the ZIP has the right version of MySql.Data.dll (6.9.9.0)

Reproduction
------------

If you're filing a bug, please describe how to reproduce it. Include as much
relevant information as possible, such as:

### Bug summary
-- from the log
2020-12-18 08:16:26,983 [P22088/D2/T1] ERROR Umbraco.Core.UmbracoApplicationBase - An unhandled exception occurred
System.Reflection.ReflectionTypeLoadException: Could not load all types from "umbraco.DataLayer, Version=1.0.7537.31670, Culture=neutral, PublicKeyToken=null" due to LoaderExceptions, skipping:
. System.IO.FileLoadException: Filen eller assemblyen 'MySql.Data, Version=6.9.9.0, Culture=neutral, PublicKeyToken=c5687fc88969c44d' eller en af dens afhængigheder kunne ikke indlæses. Den fundne assemblys manifestdefinition svarer ikke til assemblyens reference. (Undtagelse fra HRESULT: 0x80131040)

### Specifics
-- from the log
2020-12-18 08:16:26,983 [P22088/D2/T1] ERROR Umbraco.Core.UmbracoApplicationBase - An unhandled exception occurred
System.Reflection.ReflectionTypeLoadException: Could not load all types from "umbraco.DataLayer, Version=1.0.7537.31670, Culture=neutral, PublicKeyToken=null" due to LoaderExceptions, skipping:
. System.IO.FileLoadException: Filen eller assemblyen 'MySql.Data, Version=6.9.9.0, Culture=neutral, PublicKeyToken=c5687fc88969c44d' eller en af dens afhængigheder kunne ikke indlæses. Den fundne assemblys manifestdefinition svarer ikke til assemblyens reference. (Undtagelse fra HRESULT: 0x80131040)

### Steps to reproduce
A solution with older version of Umbraco 7.4.2 and a VS web project. Then upgrade Umbraco to 7.12.6. And startup the site.

### Expected result
A YPOD will show out when loading the site. 
ERROR Umbraco.Core.UmbracoApplicationBase - An unhandled exception occurred
System.Reflection.ReflectionTypeLoadException: Could not load all types from "umbraco.DataLayer, Version=1.0.7537.31670, Culture=neutral, PublicKeyToken=null" due to LoaderExceptions, skipping:
. System.IO.FileLoadException: Filen eller assemblyen 'MySql.Data, Version=6.9.9.0, Culture=neutral, PublicKeyToken=c5687fc88969c44d' eller en af dens afhængigheder kunne ikke indlæses. Den fundne assemblys manifestdefinition svarer ikke til assemblyens reference. (Undtagelse fra HRESULT: 0x80131040)

### Actual result
-- see above

**Comment by bielu** [comment]
@kistva that is not Umbraco bug, but not perfect behavior of Nuget, which should insert for you assembly redirects, but for some reason it is not always happening. :)

**Comment by kistva** [comment]
Hi @bielu
That is correct - Since MySql.Data, in version=6.9.9.0 doesn't not exist any longer. I guess the solution is change the build to 6.9.12.0 in the nuget refs or add the bindingRedirect to that version in the web.config

**Comment by nul800sebastiaan** [comment]
Unfortunately as @bielu mentions we have very little control over this at the moment, MySql should've updated itself but it didn't. Good that you found the solution though!
