### ISSUE TITLE
Inconsistency vary multilingual nested content validation 

### ISSUE THREAD

**Issue by abanoubDotNetDeveloper** [umbraco/Umbraco-CMS#9593]
I'm using umbraco 8.9 and tested that with same scenario on v8.9.1 as latest one still having that issue which is
I have two languages site (Arabic : mandatory, English) , created allowed vary doc type with allowed vary also for all of its props as element for using it as nested content on home page 
on Arabic(Mandatory Lang) validation summary it working great with expanding the tap or collapsing it
on English language it only mark the tap without detailed validation as Arabic ,I attached below screen shots for more explanation
![image](https://user-images.githubusercontent.com/22732541/102884065-a5d65f80-4459-11eb-9887-4a159166b200.png)
![image](https://user-images.githubusercontent.com/22732541/102884217-e8983780-4459-11eb-8445-20fd3dd666cc.png)

**Comment by nul800sebastiaan** [comment]
Thanks @abanoubDotNetDeveloper - we're aware. This issue duplicates https://github.com/umbraco/Umbraco-CMS/issues/9362.
