### ISSUE TITLE
Grid layout - large images in grid do not scale down, text overflows

### ISSUE THREAD

**Issue by Jay-umbr** [umbraco/Umbraco-CMS#9596]
If you set up your grid like this
![image](https://user-images.githubusercontent.com/56038614/103002367-0b485000-452f-11eb-9029-15192998207f.png)
(pretty much default config)
And select an image in one of the cells, if you select a large enough image the text (tested with RTE on the right cell) will overflow on the image.
![image](https://user-images.githubusercontent.com/56038614/103002877-0637d080-4530-11eb-834c-5c66b118c032.png)
If you use a smaller image it should render properly, side by side.

## Umbraco version

Checked on 8.9.1

**Comment by nul800sebastiaan** [comment]
Hi @Jay-umbr - I haven't been able to reproduce:

![9596](https://user-images.githubusercontent.com/304656/103672332-7442b580-4f7c-11eb-9ea2-ba534b5d71fe.gif)


I also tried with this enormous image of 9865x3120 pixels: https://upload.wikimedia.org/wikipedia/commons/6/69/Very_Large_Telescope_Ready_for_Action_%28ESO%29.jpg

If you have any more steps to reproduce then we can have another look.
