### ISSUE TITLE
Can't upgrade 8.9.1 to 8.10.1

### ISSUE THREAD

**Issue by Baracuda011** [umbraco/Umbraco-CMS#9617]
This morning I tried to upgrade my Umbraco NuGet installation, from 8.9.1 to 8.10.1. With Umbraco, I also upgraded the following:

CsvHelper 18.0.0 => 19.0.0
HtmlAgilityPack 1.1.28 => 1.1.29
uSync 8.7.2 => 8.8.1
uSync.BackOffice.Core 8.7.2 => 8.8.1
uSync.Community.Contrib 8.7.2 => 8.8.1
uSync.ContentEdition 8.7.2 => 8.8.1
uSync.Core 8.7.2 => 8.8.1

This is a pretty much standard procedure to upgrade some available packages with each Umbraco upgrade.

When I call the upgrade wizard, I get the standard welcome screen with all the information on it and on the next step, I just get ERROR DURING INSTALLATION message. There is no browser console error and also no log entries in App_Data/Logs.

## Umbraco version

I am seeing this issue on Umbraco version: 8.9.1 (NuGet installation)

Reproduction
------------

If you're filing a bug, please describe how to reproduce it. Include as much
relevant information as possible, such as:

### Bug summary

This morning I tried to upgrade my Umbraco NuGet installation, from 8.9.1 to 8.10.1. With Umbraco, I also upgraded the following:

CsvHelper 18.0.0 => 19.0.0
HtmlAgilityPack 1.1.28 => 1.1.29
uSync 8.7.2 => 8.8.1
uSync.BackOffice.Core 8.7.2 => 8.8.1
uSync.Community.Contrib 8.7.2 => 8.8.1
uSync.ContentEdition 8.7.2 => 8.8.1
uSync.Core 8.7.2 => 8.8.1

This is a pretty much standard procedure to upgrade some available packages with each Umbraco upgrade.

When I call the upgrade wizard, I get the standard welcome screen with all the information on it and on the next step I just get ERROR DURING INSTALLATION message. There is no browser console error and also no log entries in App_Data/Logs.

### Steps to reproduce

1. Update Umbraco from NuGet
2. Rebuild solution
3. Upgrade additional NuGet packages
4. Rebuild solution

### Expected result

Umbraco upgrade wizard, then to be redirected to the back-office.

### Actual result

ERROR DURING INSTALLATION message. There is no browser console error and also no log entries in App_Data/Logs.
![2021-01-06_09-36-20](https://user-images.githubusercontent.com/14230396/103734232-fa0a4380-5004-11eb-8652-2a6de13c140a.png)
![2021-01-06_09-36-34](https://user-images.githubusercontent.com/14230396/103734240-fd053400-5004-11eb-8698-5480b522e904.png)
![2021-01-06_09-45-59](https://user-images.githubusercontent.com/14230396/103734252-00002480-5005-11eb-918f-1496c8f0f9ff.png)

**Comment by nul800sebastiaan** [comment]
Hi @Baracuda011 - That's not nice! Unfortunately, it's just you who has this problem, other people are upgrading just fine, so we must assume there's something in your environment that's causing problems for you.

I've written a guide on how to try and diagnose upgrade problems, some of which it looks like you already followed: https://cultiv.nl/blog/how-to-diagnose-umbraco-upgrade-problems/

Make sure to head on out to the forums to get some more help on this, our friendly community should be able to help you further along: https://our.umbraco.com/

**Comment by Baracuda011** [comment]
Thanks @nul800sebastiaan , I am glad to hear that it's only me. I mean, not glad, but you know what I mean :D I will let you know about my progress and thank you again for the assistance.

**Comment by Baracuda011** [comment]
@nul800sebastiaan I have an update with some browser console errors.

![2021-01-06_13-06-41](https://user-images.githubusercontent.com/14230396/103750397-2c756a00-5020-11eb-9798-30810b7d3c5d.png)
![2021-01-06_13-07-04](https://user-images.githubusercontent.com/14230396/103750404-2ed7c400-5020-11eb-87f0-3e9d6202511f.png)

**Comment by nul800sebastiaan** [comment]
Yeah, so looks like one of your dlls is forcing POSTs to GETs.. 😮

**Comment by rasmusjp** [comment]
@Baracuda011 It looks like you have a redirect rule that's adding a trailing slash. That should not be enabled for  `App_Plugins` and `umbraco`

**Comment by Baracuda011** [comment]
Brilliant, @rasmusfjord, it works perfectly!!! Thank you very much. never would've thought of that.
