### ISSUE TITLE
Redirect URLs broken as of 8.10.0

### ISSUE THREAD

**Issue by zakinaeem-arq** [umbraco/Umbraco-CMS#9636]
Redirect URLs don't work on 8.10.0+

## Umbraco version

I am seeing this issue on Umbraco version: 8.10.0 as well as 8.10.1

Reproduction
------------

### Bug summary

Renaming a node via Backoffice (regardless of the Doc type) adds a redirect to old URL of the page, as expected. This however results in the old URL returning a 404. This also means that if you had any redirects as a result of node renaming, upgrading to 8.10.0 or 8.10.1 will break them.

This happens on an existing project as well as a clean Umbraco install.

### Steps to reproduce

* Create a new node (any Document type) and name it "Sample page"
* Save and publish the node
* Confirm the node is accessible on "/sample-page/"
* Rename the "Sample page" node to "Sample page renamed"
* The node should now be accessible on "/sample-page-renamed/" and a redirect should automatically be added mapping "/sample-page/" to "/sample-page-renamed/". This can be verified in the "Info" tab of the node

### Expected result
* Accessing "/sample-page/" should redirect the user's browser to "/sample-page-renamed/"

### Actual result
* "/sample-page/" returns a 404

**Comment by radospanny** [comment]
same to us

**Comment by zakinaeem-arq** [comment]
Some findings:

I believe this is related to the updates introduced to handle the following issue https://github.com/umbraco/Umbraco-CMS/issues/8568

In a default setting, website would have a Default language however the redirects persisted in "umbracoRedirectUrl" table don't have a "Culture" value associated to them. Based on the updates [here](https://github.com/umbraco/Umbraco-CMS/pull/9191/commits/e4706fd4176852bc5ca1bd55ecfc6250e66e79d1), this would result "PublishedRequest" culture in **ContentFinderByRedirectUrl.cs** to be that of Default language, which is passed down to the "RedirectUrlService.cs" and eventually "RedirectUrlRepository.cs" resulting in zero matches.

I can handle this temporarily with a custom implementation of IContentLastChanceFinder but that would mean yet another step for the application in a fallback scenario. Looking for suggestions if there is a cleaner way to handle this until fixed.

**Comment by dawoe** [comment]
Hi @zakinaeem-arq 

I think this can be solved with updating the umbracoRedirects table by setting the culture column to the default culture. But Ideally this should be handled by the upgrade.

Dave

**Comment by zakinaeem-arq** [comment]
Thanks @dawoe  - definitely works for existing redirects, but breaks for any new redirects added to the table. I have for now resorted to **IContentLastChanceFinder** with pretty much the same code as in the original **ContentFinderByRedirectUrl**. It is a double pass (means an extra hit to DB) but serves the purpose.

Looking forward to v8.11 :)

**Comment by nul800sebastiaan** [comment]
This is not (yet) fixed in 8.11 but we'll have to have a look, also a patch release for 8.10 will be required. We're on it!

**Comment by NikRimington** [comment]
@nul800sebastiaan I've found the issue and I've got a fix for it. However it could do with a unit test to prevent this happening again but I'm not sure how to write the test for this though as I think it needs more "test data" setting up and I don't quite get it.

**Comment by nul800sebastiaan** [comment]
This is fixed in https://github.com/umbraco/Umbraco-CMS/pull/9653  and will be available in the upcoming 8.10.2 and 8.11.0 which are due for release next week (https://our.umbraco.com/download/releases/progress)
