### ISSUE TITLE
ModelsBuilder in AppData mode error when making change to doctype

### ISSUE THREAD

**Issue by giacomolanza** [umbraco/Umbraco-CMS#9652]
An error occurs when making change to a doctype and regenerate models using Models Builder in AppData mode.
The same issue was discussed and should have been fixed in #5671

## Umbraco version

I am seeing this issue on Umbraco version: 8.9

Reproduction
------------

### Bug summary

When I make some changes to a doctype pressing the "Generate model" button and refresh the front end of the website I receive the following error:

Cannot bind source content type Umbraco.Web.PublishedModels.Destination to model type Umbraco.Web.PublishedModels.Destination. 

I need to delete the /App_Data/TEMP folder and reload the site to make it works.

### Specifics

This is my ModelsBuilder configuration:

`<add key="Umbraco.ModelsBuilder.Enable" value="true" />`
`<add key="Umbraco.ModelsBuilder.ModelsMode" value="AppData" />`
`<add key="Umbraco.ModelsBuilder.ModelsDirectory" value="~/App_Code/Umbraco.Web.PublishedModels" />`

### Steps to reproduce

Just make some changes to a doctype and press "Generate models" on Models Builder dashboard.

### Actual result

An error occurs. Here is a screenshot:

![Image 2](https://user-images.githubusercontent.com/10447223/104476527-a083b500-55c0-11eb-9cd8-9682d3e7c29c.jpg)

**Comment by nul800sebastiaan** [comment]
That's annoying @giacomolanza - even more annoying is probably that I can not reproduce the problem 😞 

I've updated my web.config with the 3 keys you provided, added a propery to a doctype, regenerated the models and the content on the types of pages that was updated is working just fine. Any additional steps?

![9652](https://user-images.githubusercontent.com/304656/105060645-edf89a00-5a78-11eb-99b4-050063eb6712.gif)

**Comment by giacomolanza** [comment]
@nul800sebastiaan as you can see from the recorded screen the steps to reproduce the issue are the same.
Are there any info I can provide to allow you to reproduce the steps?
Are there any other checks I can do?

![Screen](https://user-images.githubusercontent.com/10447223/105850108-92cb2800-5fe1-11eb-9e7c-c62318bdc0da.gif)

**Comment by giacomolanza** [comment]
@nul800sebastiaan is there a temporary fix or something that I can do to force Umbraco 8 cache refresh when models are automatically regenerated?

**Comment by nul800sebastiaan** [comment]
@giacomolanza Afraid not.. if we can't reproduce we also can't make a fix for it, even temporary 😞 

Only thing I can think of at the moment is to use a different modelsbuilder mode I'm afraid.

**Comment by giacomolanza** [comment]
@nul800sebastiaan thank you for your help.
Since the Umbraco cache is not working in this case, do you think that installing a version that supports Dll ModelsMode is a good idea?

In this documentation page there is the section "Installing":
[https://our.umbraco.com/documentation/reference/templating/modelsbuilder/introduction](https://our.umbraco.com/documentation/reference/templating/modelsbuilder/introduction)
that says "The Models Builder is by default embedded in Umbraco. If you need any complex features, you still need to add the full package. Check the official releases on the Models Builder GitHub repository for more details.".
The link points to a GitHub project: [https://github.com/modelsbuilder/ModelsBuilder.Original/releases](https://github.com/modelsbuilder/ModelsBuilder.Original/releases)

I'm trying to install this ModelsBuilder version but an error occurs:
![Image 3](https://user-images.githubusercontent.com/10447223/107971271-90416a00-6fb2-11eb-82c8-3b7616b6a083.jpg)

**Comment by prosperva** [comment]
I have run into similar issues. What version of Umbraco are you using?

**Comment by giacomolanza** [comment]
@prosperva in the first comment of this thread you can find all my settings including the Umbraco versione that is 8.9 (I had the same error in v8.10).
