### ISSUE TITLE
Blank block overlay after switching language

### ISSUE THREAD

**Issue by bjarnef** [umbraco/Umbraco-CMS#9663]
I noticed when having a document type which allow to vary by culture and a property e.g. "Sections" using Blocklist editor the block overlay sometimes is blank after switching language.

It only seems to happen when you have opened an overlay on the current language, switch language and edit a block element here.

**Steps to reproduce**
- Allow a document to vary by culture
- Add a property, e.g. sections, which allow to vary by culture and use Block List editor.
- Create e.g. a "Text" element type which is added to Block List editor configuration.
- Create a two languages
- Add a Text Block to Block List editor for language 1 and 2
- On language 1 open the block item and close the overlay again.
- Switch to language 2 via language selector in header
- On language 2 open the block item
- The overlay is now blank
- If not seing this try switching back to language 1 and open the block item overlay here.

![image](https://user-images.githubusercontent.com/2919859/104732098-0137fc80-573d-11eb-8a68-16021b57aead.png)

However after refreshing page for language 2 and open the block item overlay, the properties are shown again.

Seen on Umbraco v8.9.0

---
_This item has been added to our backlog [AB#10781](https://dev.azure.com/umbraco/243e7927-03b2-44e2-908f-d4ac7ea5daaa/_workitems/edit/10781)_

**Comment by bjarnef** [comment]
I can reproduce this as well with latest changes in `v8/contrib` branch.

**Comment by bjarnef** [comment]
@nielslyngsoe @nathanwoulfe I wonder if you guys have noticed this issue and have an idea what goes wrong? I can't see any specific console error, so I guess something is missing in the data being passed in to blockeditor inifinite editor or in the inifinite editor itself.

**Comment by bjarnef** [comment]
I also noticed we have a few references to `umbTabs`, but where does this exist?
I searched a bit around and found we previous had this directive:
https://github.com/umbraco/Umbraco-CMS/pull/2205/files#diff-ff6ca671d28462c72c38cec25b88de820db1207fd7f1feebf24de0037e98a749

But I can't find this anywhere with the latest changes:
https://github.com/umbraco/Umbraco-CMS/tree/v8/contrib/src/Umbraco.Web.UI.Client/src/common/directives/components/tabs

However we still have a few references:
https://github.com/umbraco/Umbraco-CMS/blob/v8/contrib/src/Umbraco.Web.UI.Client/src/common/directives/components/forms/umbautoresize.directive.js#L4

https://github.com/umbraco/Umbraco-CMS/search?q=umb-tabs

The `umb-tabs.less` seems to references to `umb-tabs-nav` class:
https://github.com/umbraco/Umbraco-CMS/blob/v8/contrib/src/Umbraco.Web.UI.Client/src/less/components/umb-tabs.less

Is it a mistake this hasn't been cleaned up?
It seems it was part of v7 https://github.com/umbraco/Umbraco-CMS/tree/v7/7.15/src/Umbraco.Web.UI.Client/src/common/directives/components/tabs but removed in v8 https://github.com/umbraco/Umbraco-CMS/tree/v8/8.0/src/Umbraco.Web.UI.Client/src/common/directives/components/tabs

**Comment by nielslyngsoe** [comment]
That was a tuff one, we had issues with old scope references. Here is a fix https://github.com/umbraco/Umbraco-CMS/pull/10195

**Comment by nul800sebastiaan** [comment]
Fixed in https://github.com/umbraco/Umbraco-CMS/pull/10195
