### ISSUE TITLE
Umbraco radio buttons not checked by default (on load)

### ISSUE THREAD

**Issue by zspasojevic** [umbraco/Umbraco-CMS#9683]
We're implementing some custom cms section and trying to use umbraco radio buttons there.
The default button selection is not working on page load despite the fact that is has model="true" set properly. 

## Umbraco version

Seems like all 8+ versions including the current

Reproduction
------------

### Steps to reproduce

Create some custom section in CMS that has a radio button with multiple options in it and set one of them to be selected by default on page load.

### Expected result

To have an option selected by default on page load

### Actual result

None of the radio button options is selected on page load.

We had a look at some of the source files since with umbraco checkboxes this functionality works. We noticed the differences with the localisationService not being passed in inside onLoad() function for radio buttons. Could this be what's causing it to fail?

[Radio Button](https://github.com/umbraco/Umbraco-CMS/blob/v8/contrib/src/Umbraco.Web.UI.Client/src/common/directives/components/forms/umbradiobutton.directive.js)

[Checkbox](https://github.com/umbraco/Umbraco-CMS/blob/v8/contrib/src/Umbraco.Web.UI.Client/src/common/directives/components/forms/umbcheckbox.directive.js)

![image](https://user-images.githubusercontent.com/43961181/105060908-33b56280-5a79-11eb-84f1-f3708f48540e.png)

**Comment by bjarnef** [comment]
@zspasojevic strange anyone hasn't noticed this. Yeah, it seems this PR https://github.com/umbraco/Umbraco-CMS/pull/6797 added `localizationService` to the controller, but didn't inject the service.

**Comment by bjarnef** [comment]
@zspasojevic do you use the `label-key` with `<umb-radiobutton>`? 

Also ensure the component has a end-closing tag end not is self-closing (void element).

**Comment by zspasojevic** [comment]
Hi @bjarnef. No, we're not using the label-key, we don't have a need for dictionary/localization. This is a code snippet: 
![image](https://user-images.githubusercontent.com/43961181/105144510-9fd9aa00-5afd-11eb-87ff-c5e84a65d090.png)
So even if we hardcode the model to true, it won't be checked by default.

**Comment by bjarnef** [comment]
Okay, the missing `localizationService` might still affect this. We need to check this with the latest changes, where the missing service is injected.

However I think the issue here is that you set `value="0"` and `value="3"`, but model is `true` and `false` so they will never match.

You can see this example from core, where it is used for relation types:
https://github.com/umbraco/Umbraco-CMS/blob/v8/contrib/src/Umbraco.Web.UI.Client/src/views/relationtypes/views/relationType.html#L11-L28

You should probably either remove the `value` attributes and handle the logic in the on-change function or use something like `vm.selectedValue` in the `model` attributes.

**Comment by nul800sebastiaan** [comment]
The localizationService problem is fixed with PR https://github.com/umbraco/Umbraco-CMS/pull/9685 and I've cherry picked this for all upcoming patch releases of 8.6 upwards. Additionally, this fix will be available in the upcoming v8.11.0 (of which the RC should be out later this week).

**Comment by bjarnef** [comment]
@nul800sebastiaan v8.11.0-RC is already out 😁  .. but great to include this in final release of v8.11.0 👍 
https://umbraco.com/blog/umbraco-811-release-candidate/
https://our.umbraco.com/download/releases/8110

**Comment by nul800sebastiaan** [comment]
duh.. too eagerly copy-pasted 🙈
