### ISSUE TITLE
After deleting a member the index is not updated and an exception is thrown

### ISSUE THREAD

**Issue by emmagarland** [umbraco/Umbraco-CMS#9684]
This is a regression of #8525

This means that when a member is deleted, the index does not remove that data.

---

## Umbraco version

- This happens on the latest `netcore\netcore` branch 
- I've replicated this on the `v8\contrib` branch so could be resolved in either. 

Reproduction
------------

### Bug summary

After deleting a member, a reindex is attempted

### Specifics

After deleting a member, a reindex is attempted, which fails because the member is now null. It seems it is returned as a null item in a list of 1 member

### Steps to reproduce

- After deleting a member, a reindex is attempted and this throws an exception under the hood. 
- You need to have exceptions enabled during debugging in your IDE to see this.

### Expected result

If the member was deleted, I wouldn't expect it to attempt to be reindexed.

### Actual result

When I break on all exceptions after deleting a member, I come to this point (line 258) in `ExamineComponent.cs`, where the member has already been deleted but it tries to reindex it:

image
![image](https://user-images.githubusercontent.com/1649855/105065592-ef749300-5a75-11eb-8b8f-289003adc7c3.png)

The member service returns a null member object even though it hasn't matched anything against the `Payload` (populated with the now deleted member details):

image
![image](https://user-images.githubusercontent.com/1649855/105065990-6447cd00-5a76-11eb-960d-fc47fc017499.png)

The code seems to be trying to run `ReindexForMember` method but fails because the properties are null.

I checked in `v8\contrib` and the same behaviour happens when deleting a member. `DeferedReIndexForMember` is called and then the member properties are null, an exception happens under the hood:

![image](https://user-images.githubusercontent.com/1649855/105066619-e33d0580-5a76-11eb-8e5d-79fee553bec1.png)

**Comment by Shazwazza** [comment]
I have fixed in this PR https://github.com/umbraco/Umbraco-CMS/pull/9807

This is a regression of https://github.com/umbraco/Umbraco-CMS/pull/8525

@nul800sebastiaan Just pinging you here about this one.

**Comment by nul800sebastiaan** [comment]
Fixed in https://github.com/umbraco/Umbraco-CMS/pull/9807

We'll have to have a look at backporting this to before 8.12 as well.
