### ISSUE TITLE
Setting media start node for user group still shows parent and grandparent folders

### ISSUE THREAD

**Issue by FrkKruso** [umbraco/Umbraco-CMS#9687]
## Umbraco version

I am seeing this issue on Umbraco version: 8.1.5

Reproduction
------------

### Bug summary

When restricting user group to a media start node which has a folder as a parent, then all of it parents/grandparents can be seen in a second tree without access to it. In the image the user group "Editors" have been restricted to "indhold" mappen but can also see the Products folder in the second tree. We would like to be able to remove the second tree entirely and assume it's not on purpose that it is shown? If the restriction would be set to a folder inside "indhold" we would be able to see both the Products and indhold folder still.

### Specifics

- Umbraco version 8.1.5
- I'm using Chrome and have testet it with internet explorer as well, same issue
- Was reproduced in vanilla 8.1.5 Umbraco.

### Steps to reproduce

Set media start node for a user group to a folder that has another folder as parent. Then login with a user in that group.

### Expected result

Only the folder that the user group is restricted to is shown.

### Actual result

A second tree is shown with the parent (and grandparents) are shown, but with no access.

 ![image](https://user-images.githubusercontent.com/75838780/105150365-f991a280-5b04-11eb-945f-0091b0fa91d8.png)

Comments
------------

We have assumed this is a bug, but if it's not, is there a way to disable the showing of this?

**Comment by nul800sebastiaan** [comment]
@FrkKruso I know this is a problem that has since been fixed, but I can't remember exactly in which version. I can very much recommend you upgrade to the latest version to get all the bugfixes and new features.

**Comment by rbottema** [comment]
Looks like it was fixed in #6815, which is included in Umbraco 8.6 onwards.
