### ISSUE TITLE
Limitation of total of concatenated rolenames (Member groups)

### ISSUE THREAD

**Issue by Aaen** [umbraco/Umbraco-CMS#9695]
A brief description of the issue goes here.

There seems to be an issue with the maximum number of roles that can be added to a Page. This seems to be dependent of the total concatenated string of all the role names that are added to it.
No more roles can be added when the total role names exceed a length of about 1024 characters.
When there are about 15 roles of 90 characters no more roles can be added.

## Umbraco version

8.10.1 

Reproduction
------------
This can easy being tested.

1. Create a new Umbraco Demo Site (8.10.1)
2. Create 25 different Member groups. with a length of at least 100 characters
3. Add all of them via the Public Access to just one node, for example 'Home'.
4. The result is an error (see attachment)
5. When they only add 18 of them, no error will appear.

![2021-01-20 13_29_27-Edit_ Home - Content - localhost](https://user-images.githubusercontent.com/2038482/105323588-95391680-5bca-11eb-85e0-4be834b30e8d.png)

**Comment by nul800sebastiaan** [comment]
Strange! I don't immediately see any problems with database storage, relevant fields are set to much longer lengths (basically unlimited). Would be good to get it fixed.

**Comment by vlaellayug** [comment]
Hello @Aaen, @nul800sebastiaan

It doesn't reach the [PostPublicAccess](https://github.com/umbraco/Umbraco-CMS/blob/v8/contrib/src/Umbraco.Web/Editors/ContentController.cs#L2439) route.

and it looks like it has to do something on the default value of "[maxQueryStringLength](https://docs.microsoft.com/en-us/dotnet/api/system.web.configuration.httpruntimesection.maxquerystringlength?view=netframework-4.7.2#property-value)" and "[maxQueryString](https://docs.microsoft.com/en-us/previous-versions/iis/settings-schema/ms689462(v=vs.90)#attributes)" which is 2048 based from the documentation.
