### ISSUE TITLE
Grid Editor - Allow All Editors setting does not allow drag an drop of all editors

### ISSUE THREAD

**Issue by JohanCroukamp** [umbraco/Umbraco-CMS#9698]
In grid editors I went through row configurations and found that all of them were set to 'allow all editors'. However this did not allow any dragging and dropping of editors in the grid.
When I then switched OFF the allow all setting,  and only selected one type of editor to move, it DID work for that editor.
So leaving the allow all setting off and manually selecting all of the editors allows the drag and drop to work. That must be a bug.

**Comment by nul800sebastiaan** [comment]
What version of Umbraco are you using please?

**Comment by JohanCroukamp** [comment]
Cloud 8.9.1

Regards,

Johan Croukamp
JHNet Web Development
F12 Pinewood Square, Pinewood Office Park, 33 Riley Street, Woodmead
T: +27 11 234 6165 (Direct Ext: 301) | Help Desk: support@jhnet.co.za<mailto:support@jhnet.co.za>
[FaceBook-icon (1)]<http://www.facebook.com/pages/JHNet-Web-Development/145727918807482>  [Twitter-icon (1)] <http://twitter.com/JHNetWeb/>   [Linked-In-icon] <http://za.linkedin.com/pub/jhnet-web-development/26/4b8/232>
http://www.jhnet.co.za<http://www.jhnet.co.za/>

[cid:image004.png@01D6F31F.854CD8B0]<http://www.jhnet.co.za/>
