### ISSUE TITLE
Upgrade error from 7.14.0 to 8.6.3

### ISSUE THREAD

**Issue by prosperva** [umbraco/Umbraco-CMS#9701]
I am trying to upgrade from 7.14.0 to 8.6.3 and I get the following error:

**The database failed to upgrade. ERROR: The database configuration failed with the following message: The constraint 'PK_user' is being referenced by table 'umbracoUser2UserGroup', foreign key constraint 'FK_umbracoUser2UserGroup_umbracoUser_id'. Could not drop constraint. See previous errors. Please check log file for additional information (can be found in '/App_Data/Logs/')**

How is this solved?

**Comment by nathanwoulfe** [comment]
Have you tried installing @stevemegson's health checks? It will help with removing indexes and highlight some other potential migration traps. 

https://our.umbraco.com/packages/developer-tools/pre-migration-health-checks/

**Comment by prosperva** [comment]
I couldn't install it as it is not supported by 7.14.0

**Comment by nathanwoulfe** [comment]
Bump to 7.15.5 first?

**Comment by prosperva** [comment]
That is my next try.

**Comment by prosperva** [comment]
I was upgrade from 7.14.0 -> 8.1.0  -> 8.1.0 -> 8.4.0 -> 8.4.0 -> 8.6.0 -> 8.6.0 -> 8.6.3
