### ISSUE TITLE
Use Respawn to reset the test database state between tests

### ISSUE THREAD

**Issue by nzdev** [umbraco/Umbraco-CMS#9707]
Consider using Respawn to reset the database state between tests instead of setting up new databases to reduce the time it takes for tests to run.
https://github.com/jbogard/Respawn

**Comment by Shazwazza** [comment]
We do this in netcore already though we don't use respawn and instead do some other wrangling to reset it. 

Not seen respawn before though, not sure if it would be any faster than the custom stuff we do. Maybe @bergmania might know?

**Comment by bergmania** [comment]
Sounds interesting, but I did not know about it.  I only think it makes sense to try it out for netcore, but could be very interesting to see if it can speed up tests. Especially the time it takes on Azure Pipeline windows agents is worth reducing.

**Comment by nul800sebastiaan** [comment]
Looks like an interesting project! On v8 we use SQL CE and respawn is not compatible so I'll put it up for grabs for an experiment in vNext. If anyone is going to try this out then please make sure to do a few simple tests first and show the results, before overhauling the complete test project. A simple test and a successful result on the build server should give us an idea if we want to implement it for the whole test suite.

**Comment by Shazwazza** [comment]
In v8 with SQL CE tests we have a highly specialized way of respawning the DB for maximum performance (which is also why that is faster than using LocalDb). In the netcore project we also have a specialized way of respawning the DB to try to maximize performance. It would be nice to maintain less code in the netcore project for this and although I'm a little skeptical that it could be faster, it would be very interesting to see if respawn could actually be faster.

**Comment by nzdev** [comment]
I was not aware that resetting was occurring already,
