### ISSUE TITLE
Examine FluentAPI  .Not().Field("parentID", -1) results in +(parentID:[-1 TO -1]) ?

### ISSUE THREAD

**Issue by mistyn8** [umbraco/Umbraco-CMS#9708]
Umbraco 8.10.1...

whilst trying to exclude trashed nodes from a examine fluent API came across this...

```
if (ExamineManager.Instance.TryGetIndex(Constants.UmbracoIndexes.InternalIndexName, out var index))
        {
            searcher = index.GetSearcher();
            searcher.CreateQuery(IndexTypes.Content)
                        .NodeTypeAlias("Tour")
                        .And().Field("axumCompoundProductId", (item.CompoundProductId ?? 0).ToString())
                        .Not().Field("parentID", -1);
            ...
        }
```
looking at the raw lucene query generated...

`+__NodeTypeAlias:tour +axumCompoundProductId:22 +(parentID:[-1 TO -1])`

the NOT is converted to and AND?
this should be

`+__NodeTypeAlias:tour +axumCompoundProductId:22 -(parentID:[-1 TO -1])`

PS Can't do .Not().Field("parentID", "-1"); although this results in the correct NOT the indexer used for internalIndex strips the "-" from strings resulting in 
`+__NodeTypeAlias:tour +axumCompoundProductId:22 -parentID:1`

Have I got something fundamentally wrong here any pointers?

**Comment by mistyn8** [comment]
realised ParentId(-1) just means at root... so equally applicable to deleted and un-deleted content... 

`.Not().Field(UmbracoExamineIndex.IndexPathFieldName, "-1,-20,".MultipleCharacterWildcard());`
was what I needed..

though leaving this issue open for NOT resulting in a range query ends up as AND.

**Comment by Shazwazza** [comment]
This isn't an Umbraco issue, this is purely an Examine question. If you can re-open the on http://github.com/shazwazza/examine that would be great (i.e. for the `for NOT resulting in a range query ends up as AND`)

parentId is a numerically defined field, that is why it behaves that way when creating a query.

**Comment by mistyn8** [comment]
reopened - https://github.com/Shazwazza/Examine/issues/207#issue-793192687
