### ISSUE TITLE
8.11RC: Logged out during "Welcome to Umbraco Tour"

### ISSUE THREAD

**Issue by greystate** [umbraco/Umbraco-CMS#9710]
I installed the 8.11.0 RC and went through the installer without installing the Starter site.

Decided to try the Tour and got to the point where I'm asked to click my profile image. When I clicked it I was presented with the login screen.

After logging back in, I found myself in mid-tour, where my profile overlay/sidebar was open and the Tour description "window" was empty. I couldn't click on anything and had to reload the page to interact again - then I was presented with the initial "Welcome to Umbraco" tour screen again. This time I was able to complete the introductory tour.

## Umbraco version

I am seeing this issue on Umbraco version: **8.11.0-rc**

Using **Safari** version **14.0.2** on **macOS Big Sur (v11.1)**

**Comment by nul800sebastiaan** [comment]
Hi @greystate! Apologies for the late reply! We have the tour being clicked through in our Cypress tests and that seems to work.. If you can still reproduce then it would be great to see what happens in your dev tools, see if there's an error, a request that doesn't complete or something like that. Might be a Safari issue as well, not sure. 

For now, I haven't been able to repro so I'll close this but we can take another look if you have more info. 👍
