### ISSUE TITLE
Umbraco 8.10.1: Save and Publish with Descendants does not fire ContentService.Published.

### ISSUE THREAD

**Issue by uSkinned** [umbraco/Umbraco-CMS#9712]
You can see other people with same issue here:

https://our.umbraco.com/forum/using-umbraco-and-getting-started/99763-contentservicepublished-not-firing-when-using-publish-with-descendants

**Comment by nul800sebastiaan** [comment]
Thanks! This duplicates #9167 - make sure to follow that issue for updates.
