### ISSUE TITLE
Forms - an error is displayed when On Send action is Message On Submit and the current page uses a custom controller and viewmodel

### ISSUE THREAD

**Issue by seanrockster** [umbraco/Umbraco-CMS#9714]
The page that displays the form is a custom controller, i.e. it inherits from RenderMvcController and uses a custom ViewModel. We would like to display a message on this page when the form is submitted however an error is showing when submitting the form.

**The model item passed into the dictionary is of type 'Umbraco.Web.Models.RenderModel', but this dictionary requires a model item of type 'AmspecCMS.ViewModels.Projects.ProjectFilterViewModel'.**

## Umbraco version

I am seeing this issue on Umbraco version:  7.11.1 

Reproduction
------------

* form with message on submit
* controller that inherits from RenderMvcController with action that returns template and custom view model
* template with the form and that uses custom view model
* submit the form

### Expected result

Display the specified Message on submit when the form is submitted 

### Actual result
Error as shown above

**Comment by nul800sebastiaan** [comment]
Hi @seanrockster and apologies for the late reply.. are you talking about any old form or are you using Umbraco Forms?

Do you have some sample code for your `RenderMvcController` and custom ViewModel that we could look into? 

Just to make it clear, you're using Umbraco 7.11.1 and I suspect Umbraco Forms, if so, which version?
