### ISSUE TITLE
Umbraco.Tests.Persistence.Repositories.SimilarNodeNameTests.TestMany unit test fails

### ISSUE THREAD

**Issue by csharpforevermore** [umbraco/Umbraco-CMS#9719]
Umbraco.Tests.Persistence.Repositories.SimilarNodeNameTests.TestMany fails. 

## Umbraco version

I am seeing this issue on Umbraco version: v8.10.1

Reproduction
------------

If you're filing a bug, please describe how to reproduce it. Include as much
relevant information as possible, such as:

### Bug summary

Test fails:: _Umbraco.Tests.Persistence.Repositories.SimilarNodeNameTests.TestMany_
This demonstrates a bug in the logic for: _Umbraco.Core.Persistence.Repositories.Implement.SimilarNodeName.GetUniqueName()_

### Steps to reproduce

Download the latest source code. Run nUnit tests.

### Expected result

Test should pass.

### Actual result

Test fails

**Comment by nul800sebastiaan** [comment]
Hi @csharpforevermore, I think that must be something on your machine. All of the builds on the 8.10 branch have succeeded: https://dev.azure.com/umbraco/Umbraco%20Cms/_build?definitionId=75&_a=summary&repositoryFilter=34&branchFilter=7712%2C7712%2C7712%2C7712

Additionally when you use the latest source code, that's typically on the `v8/contrib` branch and the builds have also succeeded for the last week: https://dev.azure.com/umbraco/Umbraco%20Cms/_build?definitionId=75&_a=summary&repositoryFilter=34&branchFilter=4625%2C4625%2C4625%2C4625

**Comment by nul800sebastiaan** [comment]
These are the tests failing in the last 14 days by the way: https://dev.azure.com/umbraco/Umbraco%20Cms/_test/analytics?definitionId=75&contextType=build - don't see this test mentioned I'm affraid. :-)

**Comment by csharpforevermore** [comment]
Someone had put a comment in saying that it failed.  v8/contrib branch.

**Comment by rbottema** [comment]
There were some fixes done for this in Netcore: #9221. Does it make sense to backport them to Umbraco 8?

**Comment by csharpforevermore** [comment]
What's the official policy on this?  What about back-porting to v7?

As a side note - is there a good help document about getting the NetCore version running?

**Comment by rbottema** [comment]
I'm not 100% sure of the official policy, but from what I've seen most non-breaking functional improvements that are relevant for v8 are backported. For v7 no new development is taking place (only fixes), so I would definitely not expect it there.

The [blog post about the .NET Core alpha release](https://umbraco.com/blog/net-core-alpha-release/) contains information about getting it running.
