### ISSUE TITLE
Revert NPoco from v4 to v3

### ISSUE THREAD

**Issue by nul800sebastiaan** [umbraco/Umbraco-CMS#9725]
Due to some undocumented and undiscovered breaking changes we can't yet upgrade to NPoco v4. Specifically when using `database.BeginTransaction();` you will get an error saying: `Umbraco.Core.Exceptions.BootFailedException: Boot failed. ---> System.MissingMethodException: Method not found: 'Void NPoco.IDatabase.BeginTransaction()`.

After investigating this was the result:

> in 4.0.2 they moved all handling of transactions from `IDatabase` to `IBaseDatabase` which does not exist in 3.9.4.

**Comment by nul800sebastiaan** [comment]
Fixed for 8.11.1 in https://github.com/umbraco/Umbraco-CMS/commit/abb469a404eac06cd00a87ac6ad4295e50dbde46

**Comment by nul800sebastiaan** [comment]
Needed an additional commit: https://github.com/umbraco/Umbraco-CMS/commit/e62cef6151fd6de1e1fce53ad4c1d19467da4068

**Comment by rbottema** [comment]
I recall having the same or similar issue with NPoco once, and I recall it being because I was running different NPoco versions in different projects. Just dropping that here in case that helps =)

**Comment by SimonAntony** [comment]
I'm getting this error when trying to install the patch - Unable to find a version of 'NPoco' that is compatible with 'UmbracoCms.Core 8.11.1 constraint: NPoco (>= 3.9.4 && < 3.999999.0)'.

**Comment by nul800sebastiaan** [comment]
@SimonAntony  Hmm, I think if you've been unlucky to already have installed 8.11.0 then you will be on v4, which NuGet then doesn't automatically downgrade. So in order to make it work you will probably have to uninstall (`Uninstall-Package NPoco -Force`) which should allow you to upgrade from 8.11.0 to 8.11.1.

Very sorry about the inconvenience. :-(

Ps. I've just upgraded from 8.10 to 8.11.1 with no problems. I'll verify what happens if I go to 8.11.0 first.

**Comment by SimonAntony** [comment]
Yup exactly that - already downgraded it so 8.11.1 is now updating as we speak

**Comment by ronaldbarendse** [comment]
Ah, the dreadful [binary breaking change](https://docs.microsoft.com/en-us/dotnet/standard/library-guidance/breaking-changes#binary-breaking-change) strikes again! Great to see it patched so quickly! 🎉

**Comment by nul800sebastiaan** [comment]
Just to confirm:

1. If you've already upgraded to 8.11.0 using NuGet, you will be faced with the error `Unable to find a version of 'NPoco' that is compatible with 'UmbracoCms.Core 8.11.1 constraint: NPoco (>= 3.9.4 && < 3.999999.0)'`.
2. In the package manage console you can run `Uninstall-Package NPoco -Force` to remove NPoco 4 from the project, make sure to do it for all of your projects in the solution.
3. After that a regular NuGet upgrade to 8.11.1 will succeed and NuGet will install the 3.9.4 version of NPoco since it's a dependency Umbraco needs.

**Comment by TRexStark** [comment]
@nul800sebastiaan What happens if we install 8.11.0 as a fresh install with NPoco v4?

**Comment by nul800sebastiaan** [comment]
Same thing, if you want to upgrade to 8.11.1 and later you will need to uninstall NPoco 4 first. We might decide to move on to NPoco 4 but not in future 8.11 releases, considering the breaking changes it's probably also not worth it for 8.12 and beyond.
