### ISSUE TITLE
v.8 Numeric data type min/max value validation isn't working in backoffice frontend

### ISSUE THREAD

**Issue by EneldoDev** [umbraco/Umbraco-CMS#9727]
While filling numeric property, with min/max value defined in data type, validation on frontend (in backoffice) is not triggered. Save/save and publish operations can be performed, but value is not saved in database. This happens only when "Field is mandatory" toggle is set to false.

## Umbraco version

I am seeing this issue on Umbraco version: pure 8.11.0 installation.

Reproduction
------------

Create custom numeric (Umbraco.Integer) data type. Set "Minimum" property to 4 and "Maximum" to 10. Create document type with previously created custom numeric property. Leave "Field is mandatory" validation toggle as false. 
Create content using this document type. Set numeric property below 4 or above 10. Save/Save and publish. 

### Expected result

Frontend validation is triggered with proper error message. Document is not saved.

### Actual result

Document is saved, but after page reload property value is empty.

Tested on Chrome Version 87.0.4280.141
I've compared behavior of this data type with older version of Umbraco (7.15.2) - I wasn't able to input any value below min/above max.

**Comment by emma-hq** [comment]
Hey @EneldoDev 

I've had a play with this and I think it's linked to your email validation issue that you raised here #9761. I've added a note to that ticket and I'll close this one as, in a sense, it's a duplicate.

Thanks,

Emma
