### ISSUE TITLE
Icon's resized when tree width changed with ui-resizable

### ISSUE THREAD

**Issue by Adamanderss** [umbraco/Umbraco-CMS#9745]
Noticed that icons in the tree will be shrinked when resizing the tree, like this:

![tree icon issue 8-11-1](https://user-images.githubusercontent.com/31885400/106600825-3628b980-655b-11eb-9808-8b44e217ba41.gif)

This only happens when the node name length is long.

## Umbraco version
I am seeing this issue on Umbraco version: 8.11.1

Reproduction
------------

Just create a node with a long name and resize the tree like the gif shows.

### Expected result
Would expect the icon size to be the same at all times.

Note: I have a PR coming to fix this.

**Comment by bjarnef** [comment]
I think this has been fixed with the changes in https://github.com/umbraco/Umbraco-CMS/pull/9718
I haven't checked the recent changes in `v8/contrib` branch.

Maybe @nul800sebastiaan or @nathanwoulfe can confirm?

**Comment by nathanwoulfe** [comment]
@bjarnef almost fixed - when working on #9739, I found the same issue appears in search results, so the flex change on .umb-tree-icon isn't enough, it needs to be on .umb-icon. I've moved it, just haven't merged yet. 

Long story short, fix is incoming.

**Comment by bjarnef** [comment]
@nathanwoulfe okay great. I recall I previous have worked with flexbox on tree items, where we should ensure using tabs key still focus e.g. tree icon and action button.

**Comment by nathanwoulfe** [comment]
Per the comments on #9746, and the conversation here, this has been fixed elsewhere (and will be merged in a few minutes once I deal with a conflict)
