### ISSUE TITLE
TemplateId not updated/removed on content

### ISSUE THREAD

**Issue by ronaldbarendse** [umbraco/Umbraco-CMS#9751]
I've just noticed some very strange behavior when changing/removing allowed templates on a document type: existing content still uses the old (now invalid) template and you can't remove the template from the content (to make it unroutable).

## Umbraco version

I am seeing this issue on Umbraco version 8.11.1.

Reproduction
------------
### Steps to reproduce
* Remove all allowed templates from a document type, choose another default template, save changes
* All content of this document type still has the removed template ID and the `Template` dropdown on the Info app doesn't have a selected item, but the `Open` link still opens the old template:
  ![No selected template](https://user-images.githubusercontent.com/1051287/106735700-da226b80-6614-11eb-8b21-101ad08bcce7.png)
* Publishing the content also doesn't remove the invalid template ID (even though there's no selected item in the template dropdown)
* Only manually changing the template to the new (default) template and publishing the content will result in using the correct template on the front-end

### Expected result
When all allowed templates are removed from a document type, all content template IDs should be removed/set to `null`. When a new default template is set, all content without a template ID should get populated with the new default template ID.

### Actual result
After removing all allowed templates, the template ID on content is unchanged. It's not possible to manually remove the (now invalid) template ID and changes are only applied when the template is manually changed and published for every content node.

**Comment by nul800sebastiaan** [comment]
As for not updating all affected content when a doctype is updated, this is unfortunately not something we've built yet (same for when you update a property to a different datatype, we don't update each node). Two reasons: first of all, this could potentially be a big performance hit, second of all: the update you made could be a mistake (!) and you can't revert easily if everything has already been updated.
Anyway, I dream of one day having a "Refactor doctype" button that will help you with what is going to change, make all the changes, remaps properties/templates and what have you. That is not on the roadmap though.

Other than that, this duplicates https://github.com/umbraco/Umbraco-CMS/issues/9303 and I'd love to see that specific issue fixed. 👍

**Comment by ronaldbarendse** [comment]
Very true about the possible performance hit and it's not a good idea to directly update live/published content indeed 😄 You might argue renaming document type and/or property aliasses already does this though, although that seems to be more because of foreign key relations and thus no changes to the actual content data are done (e.g. in the `umbracoPropertyData` or `umbracoDocumentVersion` tables).

I've added my comments to #9303, as that already tracks the issue of not removing the template ID when (re)publishing the content.

**Comment by Shazwazza** [comment]
> You might argue renaming document type and/or property aliasses already does this though, 

Yep this is true, that type of thing will cause quite a big bump in overhead. Ideally we'd change how the process of persisting things is done:

* Should inform the user if things are going to be expensive
* Should offer the user options (where possible) to do expensive operations - such as this where we could bulk change the template on all existing content items
* Should be eventually consistent instead of trying to process all of this in a sync thread - this is a much bigger story though and the UI would need to change to take this into account
