### ISSUE TITLE
inviteEmailCopyFormat always returns http

### ISSUE THREAD

**Issue by Bakersbakebread** [umbraco/Umbraco-CMS#9753]
When sending a new user an invite request if the page is served over https the corresponding email always links to HTTP://... causing the confirmation token to be invalid and redirect to http://domain/umbraco#/login/false?invite=1

I am seeing this issue on Umbraco version: 8.8.0

Reproduction
------------

Invite a new user to join umbraco back office, if prefixing with https manually it works just fine :) 

### Steps to reproduce

1) Invite new user
2) Click on link in email sent 
![image](https://user-images.githubusercontent.com/29239704/106742956-a72ca780-6615-11eb-9eef-5d2db8f1b82a.png)
3) Redirects to 
![image](https://user-images.githubusercontent.com/29239704/106742997-b1e73c80-6615-11eb-876d-3048cd0095d4.png)

### Expected result

User should be able to accept invite and join as back office

### Actual result

User is redirected to login

**Comment by nul800sebastiaan** [comment]
I think that might be because we're using the setting `<add key="Umbraco.Core.UseHttps" value="false" />` in web.config, setting this to `true` should fix it and also make other parts of Umbraco choose https by default.

I'll close this for now, let me know if that doesn't help for you.

**Comment by Bakersbakebread** [comment]
Changing that config setting renders no links:
![image](https://user-images.githubusercontent.com/29239704/106765251-8160cc00-6630-11eb-95a3-3ec7f0e2b370.png)

**Comment by nul800sebastiaan** [comment]
I am not sure what your edit means exactly, but it sounds like you've had success with `UseHttps` set to `true`, right?
