### ISSUE TITLE
Fail to save after the validation fail the first time in a nested content doctype

### ISSUE THREAD

**Issue by juanlondonoforero** [umbraco/Umbraco-CMS#9775]
A brief description of the issue goes here.

I'm just technically replicating the same description as in https://github.com/skttl/umbraco-doc-type-grid-editor/issues/230 and https://github.com/umbraco/Umbraco-CMS/issues/9341 but this time for Umbraco 8.11.1

One of the doctypes we have configured includes a Nested Content property. This property only has one element type configured and this element has a few mandatory properties. If I enter all the properties, all works. But if I miss one of the mandatory properties, then I fix it then I can't save, I keep getting an error on the editor warning me about that something is wrong. The error message doesn't;t point to an specific property but to the whole item

## Umbraco version

8.11.1

Reproduction
------------

Create a new nested element
Don't input all the mandatory field
Save -> you will see the validation errors
Input all the mandatory fields
User is unable to save because the save button is spinning and you can't click on it

User needs to close the and start again from the beginning.

![image](https://user-images.githubusercontent.com/46343500/107245993-ae91ed80-6a27-11eb-91e8-be06b3192350.png)

**Comment by cornehoskam** [comment]
I can confirm, and extend this issue to not only be for nested content, but also be for any kind of Regular Expression validation! Same reproduction method too.

**Comment by emma-hq** [comment]
Hi @juanlondonoforero - thanks for reporting this! We have an open issue for this [here ](https://github.com/umbraco/Umbraco-CMS/issues/8954)

I'll close this one and you can follow the one attached if you want to stay up to date with the progress.

Emma

**Comment by juanlondonoforero** [comment]
Hi Thanks for your email
I can see there’s an open issue since September 2020 but I don’t see any updates regarding the fix.
Do you have any updates regarding this?
Thanks
