### ISSUE TITLE
Composition groups appear in different orders in different doctypes

### ISSUE THREAD

**Issue by TwoMoreThings** [umbraco/Umbraco-CMS#9791]
I created 2 compositions, then added them to 2 new doctypes and they appear in different orders in each of the doctypes.

It appears that each new composition is added at the top of a doctype, so I must have selected them in a different order in each of my doctypes.

Reproduction
------------

Create 2 (or more) compositions
Create 2 or more doctypes
Select the compositions for each doctype, but click on them in a different order
They will then appear in a different order in each doctype.

I would expect the composition groups to appear in the same order in each doctype where they are used.
Initially I thought this was potentially a nice new feature it doesn't logically sit with the ability to reorder the elements within a doctype as I would expect reordering to affect all places where a composition group is used.

I've attached a screenshot showing the groups in different orders

![composition group order issue](https://user-images.githubusercontent.com/13945979/107434919-5809d980-6b23-11eb-97b9-6b5d67066a77.png)

I'm using the latest Chrome on Windows
Using  Unicore Alpha 3 release
Not checked in any other browsers

regards
t

**Comment by bergmania** [comment]
Hi @TwoMoreThings 
Thanks for reporting. Are you sure this is not the same behaviour as Umbraco 8? I don't recall we have made any intentional changes to this functionality for our .NET Core migration.

**Comment by louisjrdev** [comment]
If I recall correctly this has been the functionality of compositions even back to V7.

**Comment by elit0451** [comment]
Hey @TwoMoreThings 

Your observations are correct! However, the difference in behaviour origins back to v8, here is an example:
- the behaviour in v7 and v8 is deferent when it comes to ordering of compositions
  - in v7 if the order of the compositions is defaulted or simply the same (ex: all have 2 as a position), when added to a doc type they will be reordered depending on the order in which they are created, not the order in which they are selected;
  - in v8 and in netcore respectively, the historical order of creation is not considered, so they will follow the order of selection. In case you prefer a specific order, you'd have to specify it in the compositions themselves and then the order of selection will not matter.

Hope the above helps to convince you that this is not a netcore specific issue, therefore I will go ahead and remove the `project/net-core` label and refer you to @nul800sebastiaan to advise if this is a suitable feature request. 🌟

**Comment by ThomasSkyldahl** [comment]
You can manually change the order on the groups in the Compositions upfront then they will follow the order specified, I think the default for all groups is zero, and then they follow the order of appearance i guess.

This can be done in the reorder functionality by manually specifying the order.

I normally spread the composition groups with 100 between them then there is room to place other groups between in the final doctype

**Comment by TwoMoreThings** [comment]
Sorry, I assumed this was new in the dotnetcore version as I've never seen this behaviour before. I guess I always added compositions in the same order before now.
regards
t

**Comment by nul800sebastiaan** [comment]
Thanks all! We'll close this one as "normal" behavior, you have full control over where everything appears with the Reorder button and manual sort order fields. 


![image](https://user-images.githubusercontent.com/304656/109807329-0803cb80-7c26-11eb-825e-9a0fcb9ef6cb.png)
