### ISSUE TITLE
IsLoggedIn erroneously returning false

### ISSUE THREAD

**Issue by Rizen-Kris** [umbraco/Umbraco-CMS#9809]
A brief description of the issue goes here.

This code:

if (Members.Login(model.Login, model.Password))
  {
      var result = Members.IsLoggedIn();
  }

value of "result" above is false? How is that possible since Login() returned true?
## Umbraco version

I am seeing this issue on Umbraco version: 8.11.1

**Comment by nul800sebastiaan** [comment]
`Members.Login` will set a cookie that will be available in the next request, the current request doesn't know about this yet. 

If `Login` returned true then the credentials provider were correct and you can trust that the member is actually who they say they are.
