### ISSUE TITLE
localized content showing as bracketed keys in backoffice

### ISSUE THREAD

**Issue by jdanl89** [umbraco/Umbraco-CMS#9811]
Using the Alpha 3 template, I published my app to an EC2 instance (a t2.micro containing 64bit Amazon Linux 2 v2.1.2 running .NET Core.) When I go into the Backoffice, everything is in square brackets. My initial investigation showed that the `config/lang` directory and contents did not persist in the publish (confirmed by SSHing into the EC2 instance). I tried manually creating the en-US.xml language file, but that did not resolve the issue. I tried publishing in both Release and Debug configurations. Same problem.

![image](https://user-images.githubusercontent.com/33011611/107869869-928fb100-6e58-11eb-98d6-b8ae7558468f.png)

![image](https://user-images.githubusercontent.com/33011611/107869926-5741b200-6e59-11eb-945b-c70de7e0838f.png)

**Comment by bergmania** [comment]
Hi @jdanl89.. Thanks for reporting. Can you confirm, it works if you change the ItemGroup in the csproj from
```
    <ItemGroup>
        <None Remove="umbraco\models\**" />
        <None Remove="umbraco\Data\**" />
        <None Remove="umbraco\logs\**" />
        <None Remove="umbraco\MediaCache\**" />
    </ItemGroup>
```

```
    <ItemGroup>
        <None Remove="umbraco\models\**" />
        <None Remove="umbraco\Data\**" />
        <None Remove="umbraco\logs\**" />
        <None Remove="umbraco\MediaCache\**" />
        <None Include="config\**\*.*">
            <ExcludeFromSingleFile>true</ExcludeFromSingleFile>
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
            <CopyToPublishDirectory>Always</CopyToPublishDirectory>
        </None>
        <None Include="umbraco\**\*.*">
            <ExcludeFromSingleFile>true</ExcludeFromSingleFile>
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
            <CopyToPublishDirectory>Always</CopyToPublishDirectory>
        </None>
    </ItemGroup>
```
