### ISSUE TITLE
Backoffice memory leak

### ISSUE THREAD

**Issue by sebkirller** [umbraco/Umbraco-CMS#9819]
During my Umbraco fundamentals training I noticed Chrome started to chug a bit and crashed with Out Of Memory errors.
This happened even when I just left the backoffice page open in the background.
It's seems to leak memory by starting a lot of timeouts to fetch icons from cache.

## Umbraco version

I am seeing this issue on Umbraco version: 8.11.1

Reproduction
------------

### Bug summary

Umbraco backoffice seems to leak memory fetching icons from cache.

### Specifics

Here is a 30 seconds capture from Chrome Debugger:
![billede](https://user-images.githubusercontent.com/20014835/107958918-fde59a00-6fa2-11eb-86ca-08a072c8a7f5.png)

### Steps to reproduce

- Be on Chrome Version 88.0.4324.150
- Just sit in backoffice and watch memory go to the moon 🚀

### Expected result

Chrome not dying slowly 😅

### Actual result

Out Of Memory error crashes tabs with Umbraco Backoffice.

**Comment by Shazwazza** [comment]
@nathanwoulfe this is related to the other Icon conversation https://github.com/umbraco/Umbraco-CMS/pull/9200

**Comment by vaags** [comment]
Is there a chance this will be fixed in 8.11.2?

**Comment by nathanwoulfe** [comment]
It's fixed in #9200, needs review and merging. I'd like to see it in 8.12 given it's a substantial issue.

**Comment by vaags** [comment]
Yes, indeed. I was hoping it would also be in 8.11.2.

**Comment by nul800sebastiaan** [comment]
This is fixed in PR https://github.com/umbraco/Umbraco-CMS/pull/9200 and will be available in upcoming patch releases for 8.8 and all minors after that.
