### ISSUE TITLE
Filtering in block picker doesn't work

### ISSUE THREAD

**Issue by bjarnef** [umbraco/Umbraco-CMS#9824]
When using the filter/search input in block picker it doesn't filter any of the blocks.

## Umbraco version

Umbraco v8.11.1

Reproduction
------------

### Bug summary

When using the filter in the block picker I would expect it the filter the available blocks, but it doesn't seem to be the case.
https://github.com/umbraco/Umbraco-CMS/blob/v8/contrib/src/Umbraco.Web.UI.Client/src/views/common/infiniteeditors/blockpicker/blockpicker.html#L22

@madsrasmussen recently added this change to item picker in this PR https://github.com/umbraco/Umbraco-CMS/pull/9641, and it might be a similar fix the need here.

### Steps to reproduce

Open block picker in a property using Block List editor and try filtering the blocks on their names.

### Expected result

The block picker should only show filtered results.

### Actual result

The block picker still shows all available blocks.

![image](https://user-images.githubusercontent.com/2919859/108039992-11ddda00-703d-11eb-859c-34284337ffbf.png)

**Comment by Nicholas-Westby** [comment]
Can confirm I am able to reproduce this in Umbraco 8.11.1:

![A search term entered, but the list of blocks isn't filtered](https://user-images.githubusercontent.com/5933222/108131640-706b7e00-7066-11eb-81b1-002843f1b10c.png)

I would expect the rich text item to be shown, and the other items that don't contain the word "rich" to not be shown. I tried typing (expecting the filter to be instant), I tried pressing ENTER, and I tried clicking the search icon to the left of the search term. None of the filtered anything.

**Comment by bjarnef** [comment]
I have fixed this in https://github.com/umbraco/Umbraco-CMS/pull/9831

**Comment by bjarnef** [comment]
@Nicholas-Westby off-topic, I noticed you have the block "Columns". I wonder which approach you use to handle columns in the block list editor?

**Comment by Nicholas-Westby** [comment]
@bjarnef Probably not as exciting as you might imagine. That one is probably just built specifically for columns of rich text, and has no special presentation in the back office. We just ported from Nested Content to Block List, so haven't had much time to explore it in depth just yet.

**Comment by bjarnef** [comment]
Ahh okay, I still experiment with this, but it depends from project to project. A simple approach is a Grid / Columns block with a Nested Block List and create the columns based on the selected items, but it can sure be more complex with more column configurations especially when columns need to has different widths.

**Comment by nul800sebastiaan** [comment]
Fixed in https://github.com/umbraco/Umbraco-CMS/pull/9831
