### ISSUE TITLE
Icons in tree shrink with long names

### ISSUE THREAD

**Issue by arknu** [umbraco/Umbraco-CMS#9828]
![image](https://user-images.githubusercontent.com/4654741/108069648-e4f0ed80-7063-11eb-8620-d9ed76366f6a.png)

As can be seen from the screenshot, icons in the tree (in this case the media tree, but I assume all tree will behave in the same way) will shrink when text is longer than can be displayed. It would seem to be an issue with Flexbox shrinking the icon when it shouldn't.

## Umbraco version

I am seeing this issue on Umbraco version: 8.11.1 (and 8.10.2)

Reproduction
------------

### Steps to reproduce

Create some media items (or content) with long names
Resize the tree and watch the icons shrink

### Expected result

The icons should retain their fixed size and the text be shortened with an ellipsis as needed.

### Actual result

The text is shortened, however the icons also shrink.

**Comment by bjarnef** [comment]
This has already been fixed in https://github.com/umbraco/Umbraco-CMS/pull/9718

**Comment by arknu** [comment]
@bjarnef Yes, indeed. It seems my searching skills failed me here... Closing this one.
