### ISSUE TITLE
Miniprofiler Always On

### ISSUE THREAD

**Issue by Myster** [umbraco/Umbraco-CMS#9829]
I'd like to be able to configure miniprofiler to always be on.
It would probably only be configured this way for when using localhost.

**Comment by kjac** [comment]
Hi @Myster,

This is possible already - on a per-browser basis (using a cookie in said browser). 

![image](https://user-images.githubusercontent.com/7405322/108467924-3f699400-7286-11eb-837b-e1695cef47c5.png)
