### ISSUE TITLE
Broken grid editor settings [regression: 8.10+]

### ISSUE THREAD

**Issue by lars-erik** [umbraco/Umbraco-CMS#9836]
#8827 seems to have removed the support for schemas used to display custom settings for grid editors.

## Umbraco version

8.10.x

Reproduction
------------

Pre 8.10 this modification of the built-in heading grid-editor would work:

```json
    {
        "name": "Headline",
        "nameTemplate": "{{ value }}",
        "alias": "headline",
        "view": "textstring",
        "icon": "icon-coin",
        "config": {
            "style": "font-size: 36px; line-height: 45px; font-weight: bold",
            "markup": "<h1>#value#</h1>",
            "settings": {
                "color": {
                    "key": "color",
                    "label": "Color",
                    "view": "textstring"
                }
            }
        }
    },
```

After 8.10, the settings property _has_ to be an array, otherwise nothing shows. So it will have to be as such:

```json
    {
        "name": "Headline",
        "nameTemplate": "{{ value }}",
        "alias": "headline",
        "view": "textstring",
        "icon": "icon-coin",
        "config": {
            "style": "font-size: 36px; line-height: 45px; font-weight: bold",
            "markup": "<h1>#value#</h1>",
            "settings": [
                {
                    "key": "color",
                    "label": "Color",
                    "view": "textstring"
                }
            ]
        }
    },
```

### Bug summary

It breaks my contentlist package as well as a s**tload of other editors we've built through the years.  
I appreciate it's not documented, but still - this is a major backwards compatibility problem imo.

---
_This item has been added to our backlog [AB#10590](https://dev.azure.com/umbraco/243e7927-03b2-44e2-908f-d4ac7ea5daaa/_workitems/edit/10590)_

**Comment by bjarnef** [comment]
@lars-erik I never think that has been a supported format in grid editor configuration although it might have worked, og hasn't been documented. The officially format of styles and settings, should be a array of objects:
https://our.umbraco.com/documentation/getting-started/backoffice/property-editors/built-in-property-editors/grid-layout/settings-and-styles

It is probably more an issue that this hasn't been restricted to this earlier and I think the default grid render expect settings and styles to be array of objects as well.

**Comment by lars-erik** [comment]
@bjarnef We're talking grid editors, not the other grid settings. I appreciate the other settings have had that schema.  
TBH I have no idea where I learned that we could use the `config.settings` thing any more.

Never the less, it's been working, hence used, and that means this is a breaking change. I'm looking into whether it's easy to re-enable the expected behavior. I for one will have a lot of unplanned work if the behavior isn't enabled again.

**Comment by bjarnef** [comment]
@lars-erik yes I know, but compared to grid settings/styles it isn't really consistent. I have really seen documentation on this format is officially supported, so it is really hard to ensure backward compatibility to something undocumented.

**Comment by lars-erik** [comment]
@bjarnef That's half the problem of the existing backoffice. Half of it isn't documented. That doesn't mean we should be free to change it willy nilly if doing so breaks custimizations and packages.

That being said, #9837 should fix it. About to give it a spin.

**Comment by nul800sebastiaan** [comment]
Thanks @lars-erik your PR was merged, I moved the labels over there. We'll get some patch releases out with this fix in it, sorry for breaking it for you! 🙈
