### ISSUE TITLE
Wrong focus on Nested Content with max items set to 1

### ISSUE THREAD

**Issue by jesperweber** [umbraco/Umbraco-CMS#9841]
When having a nested content field with max items set to 1, the field will take focus when loading the node in the Umbraco backoffice.

This means if you have multiple fields on the document type and the nested content field is not at the top, the page will scroll down to the nested content field, since it takes focus, and you have to scroll to the top of the page yourself every time you load the node.

![image](https://user-images.githubusercontent.com/2575817/108368277-8d38ba80-71fa-11eb-98b4-a32beb52d78e.png)

![image](https://user-images.githubusercontent.com/2575817/108371602-3503b780-71fe-11eb-92d4-48f0683e5f5f.png)

### Umbraco version

I am seeing this issue on Umbraco version: 8.11.1

### Expected result

I would not expect the field to take focus when loading the node.

**Comment by patrickdemooij9** [comment]
Created a PR for this: https://github.com/umbraco/Umbraco-CMS/pull/9863
I do wonder if we should also have an option to not auto-open the nested content item on page load.

**Comment by jesperweber** [comment]
Thanks @patrickdemooij9 

Yes I have many cases where I would like the nested content item to not auto open just because I have set the max to 1, so I like the idea of an option to disable it.

**Comment by patrickdemooij9** [comment]
Created a different PR for the not auto open feature: https://github.com/umbraco/Umbraco-CMS/pull/9883
