### ISSUE TITLE
Limit the possibilty to delete media items that are in use

### ISSUE THREAD

**Issue by jesperlofgrensappa** [umbraco/Umbraco-CMS#9858]
In Umbraco Heartcore it is possible to delete a Media item that is published inside a document. This can cause published media to disapear from the live website

Our feature request is to limit the possibilty to delete published media items, or at least show a warning that the media item the user is trying to delete is published somewhere.

Thanks in advance. My team is super happy with the Umbraco Heartcore product!

How can you help?
-------------------------------

**Comment by nul800sebastiaan** [comment]
Right, to be honest I stopped reading after "In Umbraco Heartcore" 🙈 

We have tracking on media items already, but nothing to tell us when we're deleting a media item that it's in use.

![image](https://user-images.githubusercontent.com/304656/108618063-437aea80-741b-11eb-844d-c23ced53f207.png)

![image](https://user-images.githubusercontent.com/304656/108618071-58f01480-741b-11eb-9340-917c440e86c4.png)

Might be good on that delete dialog to add: this is being used in 12 other places, are you SURE?

**Comment by RyuLindow** [comment]
Yeah, that's exactly what I was thinking.

It'll also help with the Deploy error that says something like "this node cannot be deployed because it depends on a file that is in the recycle bin/is deleted."

Can't remember the exact wording but it's one of the most common ones.
