### ISSUE TITLE
RootNodeByDomainRouteHandler does not support one-level domain

### ISSUE THREAD

**Issue by chrisdent14** [umbraco/Umbraco-CMS#9867]
RootNodeByDomainRouteHandler appears not to take one-level domains into account when determining the correct root node.

I have a custom route which loads a Sitemap controller, however this is not found and throws a 404 if I set the domain on my root node to a "one-level" domain, e.g. /de or test.localtest.me/de.

As per the 'Culture and Hostnames' panel, this should be supported:
_Valid domain names are: "example.com", "www.example.com", "example.com:8080", or "https://www.example.com/". Furthermore also one-level paths in domains are supported, eg. "example.com/en" or "/en"._

- http://en-test.localtest.me/sitemap.xml - Works
- http://test.localtest.me/de/sitemap.xml - Doesn't work, throws a 404

I have tried the latter of the above domains as 'http://test.localtest.me/de' and '/de' as per the instructions but both yield the same 404 result.

The code for my custom rote is as follows:

```
public class SitemapXmlRouteComposer : IUserComposer
{
    public void Compose(Composition composition)
    {
        composition.Components().Insert<SitemapXmlRouteComponent>();
    }
}

public class SitemapXmlRouteComponent : IComponent
{
    private readonly IUmbracoContextFactory _umbracoContextFactory;
    
    public SitemapXmlRouteComponent(IUmbracoContextFactory umbracoContextFactory)
    {
        _umbracoContextFactory = umbracoContextFactory;
    }
    
    public void Initialize()
    {
        System.Web.Routing.RouteTable.Routes.MapUmbracoRoute(
            "SitemapXml",
            "sitemap.xml",
            new
            {
                controller = "SitemapXml",
                action = "Index"
            },
            new RootNodeByDomainRouteHandler(_umbracoContextFactory)
        );
    }
    
    public void Terminate()
    {
    
    }
}
```

## Umbraco version

I am seeing this issue on Umbraco version: 8.10.0

### Expected result

I would expect the below domains, when set in 'Culture and Hostnames' on two different nodes, to produce a successful result and display the sitemap displaying the descendants of that root node:
- en-test.localtest.me
- test.localtest.me/de

![image](https://user-images.githubusercontent.com/22013176/108735301-4ca5ad80-7528-11eb-9e8a-14b4b36d6b43.png)

### Actual result

- en-test.localtest.me
- - Works as expected, custom route returns the result of the Sitemap controller which returns a sitemap displaying the descendants of the root node
- test.localtest.me/de - 404 error thrown as custom route is not picked up

![image](https://user-images.githubusercontent.com/22013176/108735334-57f8d900-7528-11eb-97cf-a988100d9020.png)

If you need any other info, please let me know, thanks

**Comment by Shazwazza** [comment]
Hi, `RootNodeByDomainRouteHandler` is not part of the CMS. I believe that code is part of this 3rd party package. You'll need to register this bug with that repository.

https://github.com/callumbwhyte/umbraco-routing-extensions/blob/dev/src/Our.Umbraco.Extensions.Routing/RootNodeByDomainRouteHandler.cs

**Comment by chrisdent14** [comment]
Apologies @Shazwazza and thanks
