### ISSUE TITLE
Member Failed Password Attempts not Incrementing

### ISSUE THREAD

**Issue by reneemhaas-diagram** [umbraco/Umbraco-CMS#9868]
The failed password attempts count only increments once for members. After the first failed attempt, any failed attempts afterward to not result in the failed password attempts to increments. If the app is refreshed, it will increment again, and only once more.

## Umbraco version

8.9.2
8.11.1

Reproduction
------------

Steps to replicate:
1. Attempt to log in as a valid, active member with an incorrect password. Go to the backoffice to see that the failed attempts count has incremented.
2. Attempt to log in as a valid, active member with an incorrect password again and see that the failed attempts login does not increment.
3. Restart the app.
4. Repeat steps 1 and 2. See that the count increments once and not again with repeated failed login attempts.

### Specifics

Verified this issue is consistent in Google Chrome and Firefox.

### Expected result

Expecting the failed login attempts to continue to increment until the member has reached the max attempts and their account is locked.

### Actual result

Failed login attempts does not increment correctly.

**Comment by nul800sebastiaan** [comment]
Thanks! This looks like a regression that we should look at, make sure to follow the other reported issue for this which is: #9861

**Comment by Myster** [comment]
I found this to be an issue in umbraco 13.7.2
