### ISSUE TITLE
Override label and description of composition properties

### ISSUE THREAD

**Issue by bjarnef** [umbraco/Umbraco-CMS#9871]
Currently compositions are useful, when having a set of properties used on many other document/element types.
However when properties are inherited from a composition the property is also locked on the document/element type itself.

It is fine the alias and the datatype is locked, however it could be useful to be able to override the label and description of the property to add a more detailed description. E.g. when working with blocks different block can inherit same base properties, but you might want to add a more detailed description for the specific block.

**Comment by nul800sebastiaan** [comment]
Hi @bjarnef we just had our regular meet at HQ and while the idea definitely is interesting it will require the implementation of not just inheritance but also an override. Unfortunately this would be too large an engineering effort to undertake for fairly limited benefit while raising the complexity to a large degree. 

So in this case we feel this is not a fit for Umbraco and I'll close the issue as such.
