### ISSUE TITLE
Drag Upload File not working

### ISSUE THREAD

**Issue by nadiamac** [umbraco/Umbraco-CMS#9886]
After upgrading from 8.6.4 to the latest version 8.11.1, the ability to drag and upload a file in the media section no longer working.

note: The file upload still works when you click and select on it. Also the drag and drop on the folder level still works

## Umbraco version

I am seeing this issue on Umbraco version: 8.11.1 

Reproduction
------------

### Steps to reproduce

1. Go to media section
2. Select Create new File
3. In file explorer, pick file to upload and drag to the upload area

### Expected result

File is loaded into box, same as when you click on upload and select the file

### Actual result
Nothing happens

---
_This item has been added to our backlog [AB#10606](https://dev.azure.com/umbraco/243e7927-03b2-44e2-908f-d4ac7ea5daaa/_workitems/edit/10606)_

**Comment by emma-hq** [comment]
Hey @nadiamac 

Thanks for this issue report! I have done a bit of investigating and the last release the drag and drop worked on was 8.7.2 - by 8.0.0, it's not happening at all. 

Emma

**Comment by bjarnef** [comment]
I wonder if the issue described is the same as this one, where it is still possible to upload via "click" though or from dropzone in folder level.
https://github.com/umbraco/Umbraco-CMS/issues/9342

**Comment by emma-hq** [comment]
Hi @bjarnef - yes I think this is related. Thanks for this - it's a really helpful bit of info for someone working with this.

**Comment by nul800sebastiaan** [comment]
This was fixed in PR https://github.com/umbraco/Umbraco-CMS/pull/9933 and a fix will be available in the listed versions. Thanks for reporting! 👍
