### ISSUE TITLE
Migrated site: Published Content url gives 404 even though Url is generated

### ISSUE THREAD

**Issue by robertjf** [umbraco/Umbraco-CMS#9890]
I have a situation where a site we've migrated from U4.x via 6.2.6 -> 7.7.x -> 7.15.x to Umbraco 8 gives 404 errors for published content.

When we publish a specific page by itself, it will show up on the website, if we attempt to publish with children, none of the child/ancestors that are already published render correctly unless they've previously been published specifically.

## Umbraco version

I am seeing this issue on Umbraco version: 8.11.1

Reproduction
------------

I suspect it's related to a database corruption - I can supply a copy of the database privately if required.

I also think this has something to do with the nuCache.

**Comment by robertjf** [comment]
I could have done that screen recording better - the status of the content node that was displaying the 404 was Published, with the url `/why-buy-australian-made/australian-makers/` in the Content Info App.

**Comment by nul800sebastiaan** [comment]
Hi @robertjf! Have you tried to rebuild the NuCache in the Settings section (`Published Status`)? And what happens if you publish the current document and it's (grand)parents manually?

**Comment by nul800sebastiaan** [comment]
Oh you said that, publishing works. It's a known limitation that publishing with children won't work in this case as we don't do an actual "publish"  (insert a new version into the database and set that as published), rather, we have a "published" flag on the current version and if you publish including children then that version is moved back into the cache, this is of course to speed things up and not to make unnecessary versions. 

Still curious if a rebuild of the caches from the Settings section works for you.

**Comment by robertjf** [comment]
@nul800sebastiaan rebuilding the nuCache (tried all 3 options) doesn't make any difference - the content is already published (i.e. it has published versions in the database) and interestingly, when you reference it on another page it shows up, but when you navigate to it from that page you still get the 404 error.

For example - this page is the news base page (/latest-news/) and shows the individual articles:
![image](https://user-images.githubusercontent.com/818101/109052686-00c55500-7730-11eb-8259-5d57c2ac5d76.png)

When I click on the first article (/latest-news/2020/australian-made-logo-now-protected-in-the-eu-uk-and-uae/) I get the 404 Page not found screen.

**Comment by nul800sebastiaan** [comment]
Thanks @robertjf, that sounds frustrating! I would love to get a copy of the db! sj @ umbraco .dk

**Comment by robertjf** [comment]
@nul800sebastiaan great :). Just sent you a bacpac of the database...

**Comment by nul800sebastiaan** [comment]
Thanks @robertjf! Did you clean up version data before migrating? The query `SELECT * FROM umbracoContentVersion WHERE id NOT IN (SELECT DISTINCT versionId FROM umbracoPropertyData)` gives me 539 results of versions that have no property data whatsoever, this is after I saw things in the logs when I try to start the site of missing  data (`System.InvalidOperationException: No data for media 1260 at Umbraco.Web.PublishedCache.NuCache.DataSource.DatabaseDataSource.CreateMediaNodeKit(ContentSourceDto dto) in D:\Temp\UmbracoCMS8Clean2\src\Umbraco.Web\PublishedCache\NuCache\DataSource\DatabaseDataSource.cs:line 279`)

**Comment by nul800sebastiaan** [comment]
And you can see which nodes they are (501 of them) with this query: `SELECT * FROM umbracoNode WHERE Id IN(SELECT DISTINCT(nodeId) FROM umbracoContentVersion WHERE id NOT IN (SELECT DISTINCT versionId FROM umbracoPropertyData))` - some are trashed but most of them are not. So not sure what happened to the property data for them?

**Comment by robertjf** [comment]
@nul800sebastiaan thanks - will take a look and see what happens after I clean up - there are some scripts that are being run prior to migration to clean up some of the old versions, but it's an old v4 database and there was already some issues with the data from the outset.  I must have missed some of it...

**Comment by nul800sebastiaan** [comment]
Thanks @robertjf - I'll close this for now, let us know if it still doesn't work when there's proper versions in place.

**Comment by robertjf** [comment]
@nul800sebastiaan so.  The saga continues... 

Much of the contentVersions without any Property Data are due to nodes that have no properties or none of the property values have been filled in.  This would be a valid state by the look of it; I compared the original database at 4.9.2 with the final version:

* 4.9.2: 75 records in cmsContentVersion that don't have corresponding records in cmsPropertyData
* 8.11.1: 956 records in umbracoContentVersion that don't have corresponding records in umbracoPropertyData.

Also, I noticed that when I created a new node with a document type that has no properties, then saved and published it, it too results in a umbracoContentVersion record with no corresponding records in umbracoPropertyData.

I did however resolve some of the issues in the upgrade process, and the nuCache databases are now reporting OK instead of NOT ok, so that's a start.

I still can't publish everything using Batch Publish though, and the issue remains unchanged... can you please re-open this ticket, as I don't believe the missing umbracoPropertyData records were the issue...

**Comment by nul800sebastiaan** [comment]
Good to hear you have at least managed to get Umbraco running, my site crashes immediately when I attach your db, not sure why, but presumably because it's missing some data.

I still think there would be something wrong with the content versions, not something that we can fix in Umbraco for you. I will recommend you try to brute force this publish, be aware that it might take a very long time so you might want to test it out on a smaller branch of the tree first. 

Here's some code to get you started, it takes the node you're publishing and then does a publish on all the descendants. This creates a brand new version for each descendant and might help you fix the missing data and getting all the rendering to now work (not sure what you meant by the fact they don't render correctly until published). 

```csharp
using Umbraco.Core;
using Umbraco.Core.Composing;
using Umbraco.Core.Services.Implement;
using Umbraco.Web;

namespace UmbCustomCode
{
    [RuntimeLevel(MinLevel = RuntimeLevel.Run)]
    public class SubscribeToPublishEventComposer : ComponentComposer<SubscribeToPublishEventComponent>
    {
    }

    public class SubscribeToPublishEventComponent : IComponent
    {
        private readonly IUmbracoContextFactory _context;

        public SubscribeToPublishEventComponent(IUmbracoContextFactory context)
        {
            _context = context;
        }

        public void Initialize()
        {
            ContentService.Publishing += ContentService_Publishing;
        }

        private void ContentService_Publishing(Umbraco.Core.Services.IContentService sender,
            Umbraco.Core.Events.ContentPublishingEventArgs e)
        {
            var cs = Current.Services.ContentService;
            foreach (var entity in e.PublishedEntities)
            {
                using (var cref = _context.EnsureUmbracoContext())
                {
                    var cache = cref.UmbracoContext.ContentCache;
                    var node = cache.GetById(entity.Id);
                    foreach (var descendant in node.Descendants())
                    {
                        var content = cs.GetById(descendant.Id);
                        cs.SaveAndPublish(content, raiseEvents: false);
                    }
                }
            }
        }

        public void Terminate()
        {
            ContentService.Publishing -= ContentService_Publishing;
        }
    }
}
```

**Comment by robertjf** [comment]
Hey @nul800sebastiaan I'm actually doing something similar using an api endpoint - but even though everything gets published, I still get the 404 errors.  The only way they go away is if I individually by hand publish each node - and even then it's not guaranteed.

It's also worth noting that some of the nodes with missing data are created after the migration is complete - they don't have properties as they are essentially folders.  So the missing data itself is either intentional because there's no data to be populated, or there's a bug in Umbraco somewhere I've yet to uncover?

Any other thoughts?

**Comment by robertjf** [comment]
oh, by "render correctly" - I mean we get a 404 error instead of the actual content.  But going back to one of the original comments, if the node is referenced on say an aggregation page, it's content is available, just not when you try to visit the node directly (and yes, there's a valid URL, template and the node reports as published in the back-office).

**Comment by nul800sebastiaan** [comment]
Hmm, unfortunately there's not much I can say.. I am pretty sure there's some data that is corrupt that needs fixing but who knows..

If the site started as a version 4.9.2 then there's all kinds of things that were messily done back then. We've tried our hardest to get upgrades to work and to smooth out past mistakes, but can't catch all the weird edge cases. 

At this point all I have for you is: try to attach a debugger to the Umbraco source code and see where it goes wrong 🙈 

>if the node is referenced on say an aggregation page, it's content is available, 

Make sure to disable all custom code and packages, this sound like there's some weird UrlProvider or ContentFinder doing some black magic?

I find it very strange that I can't even boot a clean Umbraco instance against your database, but maybe you've fixed that problem in the new database (I'll be happy to get another copy to confirm).

**Comment by robertjf** [comment]
@nul800sebastiaan I agree - but tracking it down is proving difficult - I can run the site with a vanilla Umbraco (that's how the migration is done), there's no custom routing/UrlProvider/ContentFinder or anything like that; all the content is being discovered and all urls generated out of the box.  I've tried debugging from the Umbraco source without much success in this instance, but will go back to that and report back as I can't remember exactly what I found - something about cache being disposed in some cases, but didn't seem specific to the missing content...

**Comment by robertjf** [comment]
@nul800sebastiaan I finally tracked down the problem - the umbracoDocumentVersion table is missing the template ids for most of the content...

```
SELECT *
  FROM [umbracoContentVersion] cv
  INNER JOIN [umbracoDocumentVersion] dv on dv.id = cv.id
WHERE dv.published = 1
and templateId IS NOT NULL
```
shows only 13 rows, while inverting the where condition to IS NULL shows around 2,000 rows...

trying to track down where the data went missing in the migration, as the original database shows 2,336 rows in the cmsDocument table:

```
SELECT *
  FROM [cmsDocument]
  where templateid is not null
  and newest = 1
```

**Comment by robertjf** [comment]
Ok, so here's what I think happened:  I ran uSync as a last step on the new instance of Umbraco - all the templates have been replaced with new ones, and it looks like while uSync reconfigured the document types properly, it effectively nullified most of the template references in the umbracoDocumentVersion table.

I ran the following script to fix most of it up, save a few nodes that were using alternative templates:

```
update dv
SET dv.templateId = ct.templateNodeId
FROM umbracoDocumentVersion as dv
JOIN umbracoContentVersion cv ON dv.id = cv.id
LEFT JOIN umbracoContent c ON cv.nodeId = c.nodeId
LEFT JOIN cmsDocumentType ct ON c.contentTypeId = ct.contentTypeNodeId
where ct.IsDefault = 1
and dv.published = 1
and dv.templateId is null
```

Still a few small niggling issues, but that seems to have resolved the bulk of it :)
