### ISSUE TITLE
Rich text editor is adding an empty div at the beginning

### ISSUE THREAD

**Issue by Baracuda011** [umbraco/Umbraco-CMS#9897]
While working on some Google structured data and constantly monitoring the source, I have discovered that the rich text editor is adding **`<div style="display: none;"></div>`** at the beginning of every data property where it's being used.

I tried another option where in a grid and you add a new RTE, the default source code looks like this:

**`<div style="display: none;"></div><p></p>`**

Again with the empty div on top.

In both cases, it stays there permanently even after manually removing it from the source.

## Umbraco version

I am seeing this issue on Umbraco version: 8.11.1

Reproduction
------------

If you're filing a bug, please describe how to reproduce it. Include as much
relevant information as possible, such as:

### Bug summary

Rich text editor is adding **`<div style="display: none;"></div>`** at the beginning of every data property where it's being used.

https://user-images.githubusercontent.com/14230396/109100947-44738b00-773f-11eb-86d0-2501f225562a.mp4

### Steps to reproduce

1. Add rich text editor as a data property
2. Add any content to it, lorem ipsum ie.
3. View source
4. Empty div will be the first thing at the top

### Expected result

Source code should not contain **`<div style="display: none;"></div>`**

### Actual result

Source code is formatted correctly with **`<div style="display: none;"></div>`** at the beginning.

**Comment by nul800sebastiaan** [comment]
Thanks @Baracuda011, unfortunately I can't reproduce this in 8.11.1:


https://user-images.githubusercontent.com/304656/109127558-dafb7880-774e-11eb-9273-76539a10fd35.mp4

The only thing I can think of right now is this thing you have here: 

![image](https://user-images.githubusercontent.com/304656/109127700-01211880-774f-11eb-805c-a7f459c91a02.png)

That's a font size dropdown I guess? I don't have that one as an option so maybe it's a plugin, maybe it's doing this? Not sure. 

I'll close for now but if you have additional steps to reproduce on a clean install of Umbraco we can have a look.

**Comment by Baracuda011** [comment]
Hi @nul800sebastiaan,

I have nothing special in the config besides what's recommended in tinyMCE documentation.

Here is a section from my config file:

```
	<plugins>
		<plugin>paste</plugin>
		<plugin>anchor</plugin>
		<plugin>charmap</plugin>
		<plugin>table</plugin>
		<plugin>lists</plugin>
		<plugin>advlist</plugin>
		<plugin>autolink</plugin>
		<plugin>directionality</plugin>
		<plugin>tabfocus</plugin>
		<plugin>searchreplace</plugin>
		<plugin>fullscreen</plugin>
		<plugin>textcolor</plugin>
		<plugin>colorpicker</plugin>
	</plugins>
	<customConfig>
		<config key="entity_encoding">raw</config>
		<config key="textcolor_map">
			[
			"7ebfc5", "Blue",
			"d2232a", "Red",
			"67a900", "Green",
			"373f41", "Dark grey",
			"c5c5c5", "Light grey",
			"000000", "Black",
			"ffffff", "White"
			]
		</config>
		<config key="fontsize_formats">12px 14px 16px 18px 20px 22px 24px 26px 28px 30px 32px 34px 36px 38px 40px</config>
	</customConfig>
```

As you can see, nothing out of the ordinary is in there.
