### ISSUE TITLE
Need meaningful error messages

### ISSUE THREAD

**Issue by prosperva** [umbraco/Umbraco-CMS#9901]
While migrating from v7 to v8, I noticed that if the user being used to run the upgrade does not have the right privileges, the error shown looks like this:

**Create table permission denied in database soandso**

Is Umbraco trying to create a table or this is a random error that is being thrown?

I tried to track how Umbraco checks for permissions during upgrade in the source code to no avail.

**Comment by emma-hq** [comment]
Hey @prosperva 

Thanks for the issue you've raised here. We've a list of known errors on the docs around upgrading that might be useful to you, [here](https://our.umbraco.com/Documentation/Getting-Started/Setup/Upgrading/migrating-to-v8#known-issues). The error messages can be a bit limited so we'd encourage people upgrading to look in the logs for more information. If you don't find what you need there, hop over to our very friendly forum at [our.umbraco.com](https://our.umbraco.com/forum/) and post something with what you have. One of our community members will be happy to share their experience with you.

Finally, we can recommend an excellent [package by Proworks](https://www.nuget.org/packages/ProWorks.Umbraco8.Migrations) that can assist with upgrading from v7 to v8 - and there's a fantastic [blog post](https://www.proworks.com/blog/archive/how-to-upgrade-umbraco-version-7-to-version-8) that serves as a walkthrough.

Emma
