### ISSUE TITLE
8.12RC Bug with "Document Type" option for creating document types

### ISSUE THREAD

**Issue by poornimanayar** [umbraco/Umbraco-CMS#9903]
I noticed that when choosing the new option "Document Type" to create a document type to serve as a data node, you can still create a default template. I am not sure whether it's intended or not. The same applies to creating a new "Composition"

Steps to reproduce

1. Try to create a new doc type
2. Choose the option "Document Type"
3. Save
4.  Go to templates and you can see that the button to create a matching template is available.

![image](https://user-images.githubusercontent.com/3941753/109317224-660a6a80-7844-11eb-87f9-d435b3f3067d.png)

**Comment by bjarnef** [comment]
@poornimanayar I don't think this is a bug. It is still valid to create a template for a document type.

If creating an element type, it is disabled though.

**Comment by poornimanayar** [comment]
Hmm, I can see the composition option too having the create template button. Again, don't know whether its intentional :-)

**Comment by bjarnef** [comment]
A composition is just a regular document type. Nothing special about until it is used on another document type :)

**Comment by nul800sebastiaan** [comment]
This is correct, it's "just" a doctype and this behavior hasn't changed from 8.11 👍
