### ISSUE TITLE
Database permission cache

### ISSUE THREAD

**Issue by prosperva** [umbraco/Umbraco-CMS#9907]
I recently upgraded a site from 7.12.4 to 7.14.0 and everything went well. Somehow database privileges were changed and Umbraco threw a permission error saying **Create table permission denied on database blabla**

Once the database permission was fixed, accessing the site went into upgrade mode and showed that it needed to upgrade from 7.14.0 to 7.14.0. It didn’t make sense because the upgrade was previously done and was completed.

I then went to IIS and recycled the App Pool being used by the site and the site was back to normal. 

Is this an Umbraco cache issue or IIS?

**Comment by nul800sebastiaan** [comment]
Sounds like the upgrade wasn't complete since there was an error. Good that it recovered when you fixed the error! 

"Somehow database privileges were changed" sounds like a manual action somewhere. Nothing to do with Umbraco or IIS.
