### ISSUE TITLE
[NETCORE] Remove MembersMembershipProvider.cs

### ISSUE THREAD

**Issue by emmagarland** [umbraco/Umbraco-CMS#9911]
MembersMembershipProvider needs to be deleted once all has been replaced in terms of macros.

_Originally posted by @emmagarland in https://github.com/umbraco/Umbraco-CMS/pull/9472#discussion_r570429233_

**Comment by emma-hq** [comment]
Hey Em - ta for this! 👍

**Comment by emmagarland** [comment]
@Shazwazza same as before. just going through some previous issues from the TODO list - another one that I think has moved on now?

**Comment by Shazwazza** [comment]
yep this is done too 👍

**Comment by emmagarland** [comment]
Cool stuff
