### ISSUE TITLE
[NETCORE] MembershipHelper to be removed once all replaced

### ISSUE THREAD

**Issue by emmagarland** [umbraco/Umbraco-CMS#9912]
`MembershipHelper.cs` to be removed once all methods have been analysed, moved/removed since most methods will occur on the manager via identity implementation

_Originally posted by @emmagarland in https://github.com/umbraco/Umbraco-CMS/pull/9472#r584350572_

Links to https://github.com/umbraco/Umbraco-CMS/pull/9472/files#issuecomment-783812509

**Comment by emma-hq** [comment]
Hola Em,

thanks for this one too - labelled 👍 

Em

**Comment by emmagarland** [comment]
@Shazwazza just going through some previous issues - can we close this one do you think?

**Comment by Shazwazza** [comment]
yep this is done will close 👍

**Comment by emmagarland** [comment]
Awesome!
