### ISSUE TITLE
[NETCORE] Implement role functionality for members

### ISSUE THREAD

**Issue by emmagarland** [umbraco/Umbraco-CMS#9913]
### Description

Implement role functionality for members in .NET Core (identity roles, store and manager). 

_Originally posted by @emmagarland in https://github.com/umbraco/Umbraco-CMS/pull/9472#r584351235_

Based on the new ASP.NET Core identity implementation and [UmbracoIdentity](https://github.com/Shazwazza/UmbracoIdentity).

This relates to the larger issue for the whole members migration #9471

- No database changes
- Implementation of a store, manager and user for the members role (groups) identity implementation

### Additional points

- See discussion in https://github.com/umbraco/Umbraco-CMS/pull/9472#discussion_r572614436

**Comment by emma-hq** [comment]
Hey Em,

Thanks for raising this one. We've labelled net-core 👍 

Em

**Comment by emmagarland** [comment]
I believe this can now be closed @Shazwazza based on #9946 being merged?

**Comment by Shazwazza** [comment]
yep!
