### ISSUE TITLE
NetCore: Access to Translation section Required to get documenttypes

### ISSUE THREAD

**Issue by mvanhelmont** [umbraco/Umbraco-CMS#9938]
### Bug summary

When removing access to the translation sections, you can't create new document types or create new documents. You will get the following messages:

**Create new content:**

Authorization error: Unauthorized access to URL: 
/umbraco/backoffice/umbracoapi/contenttype/GetCount
Contact your administrator for information.

**Create new document type**

Authorization error: Unauthorized access to URL: 
/umbraco/backoffice/umbracotrees/contenttypetree/GetMenu
Contact your administrator for information.

### Specifics

    * Umbraco version 0.5.0-beta001 (nightly build)
    * Safari
    * Google Chrome

![Schermafbeelding 2021-03-04 om 15 21 27](https://user-images.githubusercontent.com/5310629/109977959-aadb4900-7cfd-11eb-91c5-c41f2e9e5ca1.png)

### Steps to reproduce

    * Remove translation section from group and try to create a new document type of content.

### Expected result

    * Don't have to have translation section for single language variant site.

### Actual result

    * Not possible to create document types or content

**Comment by bergmania** [comment]
Hi @mvanhelmont, Thanks for reporting. We will get that fixed :)

**Comment by bergmania** [comment]
This is fixed in #9965
