### ISSUE TITLE
You need to find ProfiledDbCommand.cs to view the source for the current call stack frame

### ISSUE THREAD

**Issue by sheikmohamed90** [umbraco/Umbraco-CMS#9945]
A brief description of the issue goes here.

## Umbraco version

I am seeing this issue on Umbraco version:7.6.3 to  7.15.0

Reproduction
------------

If you're filing a bug, please describe how to reproduce it. Include as much
relevant information as possible, such as:

### Bug summary

     Auto Update ask when i run the application but error coming. my web site working fine but i'm not able to login 

c:\Code\github\SamSaffron\MiniProfiler\StackExchange.Profiling\Data\ProfiledDbCommand.cs'. Checksum: MD5 {c5 d3 ec e0 dc 7e 24 98 a1 6d 1e 26 6a ad bd 20}
The file 'c:\Code\github\SamSaffron\MiniProfiler\StackExchange.Profiling\Data\ProfiledDbCommand.cs' does not exist.
Looking in script documents for 'c:\Code\github\SamSaffron\MiniProfiler\StackExchange.Profiling\Data\ProfiledDbCommand.cs'...
Looking in the Edit-and-Continue directory 'D:\Visual Studio 2017\Projects\TechnoOrbit\enc_temp_folder\'...
The file with the matching checksum was not found in the Edit-and-Continue directory.
Looking in the projects for 'c:\Code\github\SamSaffron\MiniProfiler\StackExchange.Profiling\Data\ProfiledDbCommand.cs'.
The file was not found in a project.
Looking in directory 'C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\VC\Tools\MSVC\14.16.27023\include\'...
Looking in directory 'C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\VC\Tools\MSVC\14.16.27023\include\cvt\'...
Looking in directory 'C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\VC\Tools\MSVC\14.16.27023\include\msclr\'...
Looking in directory 'C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\VC\Tools\MSVC\14.16.27023\include\sys\'...
Looking in directory 'C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\VC\Tools\MSVC\14.16.27023\include\thr\'...
Looking in directory 'C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\VC\Tools\MSVC\14.16.27023\crt\src\'...
Looking in directory 'C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\VC\Tools\MSVC\14.16.27023\crt\src\x64\'...
Looking in directory 'C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\VC\Tools\MSVC\14.16.27023\crt\src\arm\'...
Looking in directory 'C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\VC\Tools\MSVC\14.16.27023\crt\src\concrt\'...
Looking in directory 'C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\VC\Tools\MSVC\14.16.27023\crt\src\i386\'...
Looking in directory 'C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\VC\Tools\MSVC\14.16.27023\crt\src\linkopts\'...
Looking in directory 'C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\VC\Tools\MSVC\14.16.27023\crt\src\stl\'...
Looking in directory 'C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\VC\Tools\MSVC\14.16.27023\crt\src\vccorlib\'...
Looking in directory 'C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\VC\Tools\MSVC\14.16.27023\crt\src\vcruntime\'...
Looking in directory 'C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\VC\Tools\MSVC\14.16.27023\atlmfc\src\mfc\'...
Looking in directory 'C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\VC\Tools\MSVC\14.16.27023\atlmfc\src\atl\'...
Looking in directory 'C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\VC\Tools\MSVC\14.16.27023\atlmfc\include\'...
Looking in directory 'd:\'...

**Comment by nul800sebastiaan** [comment]
Hi there - this sounds like an upgrade problem, make this blog post might help you get some more insight into what went wrong: https://cultiv.nl/blog/how-to-diagnose-umbraco-upgrade-problems/ 

The blog post is a little old but most of the information is still correct to this day.

For follow up questions make sure to head to the forum at  https://our.umbraco.com, where our friendly community can help you identify the problem. Remember to describe what you did, what is going wrong and what you tried to do to fix it. 👍
