### ISSUE TITLE
Can't edit property aliases or groups.

### ISSUE THREAD

**Issue by HGCollier** [umbraco/Umbraco-CMS#9969]
I cannot edit or even see the property aliases and group names.
![image](https://user-images.githubusercontent.com/25365699/110774376-a3fc8b00-8255-11eb-9202-23827e358677.png)

It's the same in the dialog.
![image](https://user-images.githubusercontent.com/25365699/110774477-c1c9f000-8255-11eb-94a7-78619f288b3b.png)

After trying to type in the group name textbox it just doesn't display anything.
![image](https://user-images.githubusercontent.com/25365699/110774615-e9b95380-8255-11eb-9bdc-8e56412ed20a.png)

**Comment by nul800sebastiaan** [comment]
Hi @HGCollier, luckily that's not the experience most people are having.
What version of Umbraco are you using? What did you do before it stopped working (assuming it was working at all)?

**Comment by HGCollier** [comment]
> What version of Umbraco are you using? What did you do before it stopped working (assuming it was working at all)?

Sorry, forgot to include. I am using v8.12.0, this happens after a fresh install. I even re-installed it and the problem persisted.

**Comment by nul800sebastiaan** [comment]
@HGCollier Hmm, strange, I am pretty sure it must be some kind of browser cache or something..? Did you use NuGet to install? Maybe not all the files were copied over to where they need to be..?

**Comment by HGCollier** [comment]
@nul800sebastiaan I used Visual Studio 2019 package manager console, which I believe is NuGet. If that were the case then wouldn't a fresh re-install have helped? You might be onto something with the caching though. Let me check

**Comment by HGCollier** [comment]
Just cleared my browsing data and the problem is still occurring. I tried it in Chrome and it works, so it could just be an issue with Microsoft Edge (the non-chromium version)?

**Comment by nul800sebastiaan** [comment]
Maybe.. it's was end of life 2 days ago and while we didn't actively remove support for it, we won't be supporting it from now on. It's been automatically removed from my machine since the last windows update so I can't even check any more! 😅 

So all I can say is: maybe it was browser cache, maybe it was Edge. I'm going to close this issue and recommend using new egde or other still supported browsers. 👍
