### ISSUE TITLE
Getting kicked, if document type has a Umbraco.UserPicker property

### ISSUE THREAD

**Issue by sebastiandammark** [umbraco/Umbraco-CMS#9983]
If an Umbraco user, without access to the Users section, enters a page in backoffice, and the page has a Umbraco.UserPicker property, then the user is kicked out.

## Umbraco version

I am seeing this issue on Umbraco version: Umbraco version 8.10.2

Reproduction
------------

If you're filing a bug, please describe how to reproduce it. Include as much
relevant information as possible, such as:

### Bug summary

1. Create a document type with a Umbraco.UserPicker property.
2. Access this page with a user that doesn't have access to the Users section.
3. You're getting kicked

### Specifics

It's tested in Chrome, Edge, Firefox

### Steps to reproduce

See the bug summary

### Expected result

I was expecting to see the Umbraco.UserPicker, with a list of users.
The only restriction should be the access to the actual User section

### Actual result

You're getting kicked from Umbraco back office

**Comment by nul800sebastiaan** [comment]
Ah yeah, looks like this was changed in @bjarnef's PR, this `[AdminUsersAuthorize]` https://github.com/umbraco/Umbraco-CMS/pull/7613/files#diff-ad812d8541ec737529d24ea85f83a1891a4eecd4a515d2d9bae9ba3281aa823aR187 shouldn't be there, we'll have a look.

**Comment by bjarnef** [comment]
@nul800sebastiaan it was basically copied from the existing `GetById()` method here https://github.com/bjarnef/Umbraco-CMS/blob/c7d09099f846e72f5ccfcb3152a2efa942777604/src/Umbraco.Web/Editors/UsersController.cs#L169

So I you e.g. had a custom property editor using that method I guess the same would happen.

**Comment by nul800sebastiaan** [comment]
I've added a long description in https://github.com/umbraco/Umbraco-CMS/pull/10002 with a temporary fix. We'll need to figure out a better way to fix this so we can have paging but this is similar to what the old picker used to do so it will at least fix the regression for now.
